### ISSUE TITLE
Access denied when loading frozen inference graph

### ISSUE THREAD

**Issue by rzimmerdev** [tensorflow/tensorflow#41482]
------------------------

### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: No
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 Home
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**: No
-   **TensorFlow installed from (source or binary)**: Source
-   **TensorFlow version (use command below)**: 1.14.0
-   **Python version**: 3.6.7
-   **Bazel version (if compiling from source)**: Not using Bazel
-   **GCC/Compiler version (if compiling from source)**: Not using GCC
-   **CUDA/cuDNN version**: CUDA/cuDNN: 10.0
-   **GPU model and memory**: NVIDIA GeForce GTX 1080, 12G
-   **Exact command to reproduce**:
image_data = tf.gfile.FastGFile('ssd_mobilenet_v1_coco_2017_11_17/output_inference_graph_v1.pb', 'rb').read() 

**Error:**
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\rzimm\anaconda3\envs\rapidrzr\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 122, in read
    self._preread_check()
  File "C:\Users\rzimm\anaconda3\envs\rapidrzr\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 84, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.UnknownError: NewRandomAccessFile failed to Create/Open: ssd_mobilenet_v1_coco_2017_11_17\output_inference_graph_v1.pb : Access is denied.
; Input/output error
>>> image_data = tf.gfile.FastGFile('ssd_mobilenet_v1_coco_2017_11_17/output_inference_graph_v1.pb', 'rb').read()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\rzimm\anaconda3\envs\rapidrzr\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 122, in read
    self._preread_check()
  File "C:\Users\rzimm\anaconda3\envs\rapidrzr\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 84, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.UnknownError: NewRandomAccessFile failed to Create/Open: ssd_mobilenet_v1_coco_2017_11_17/output_inference_graph_v1.pb : Access is denied.`

### Describe the problem
I tried using the Object Detection Tutorial Notebook to classify some images, but instead of using the downloaded model, I substituted by another model I had trained. When trying to substitute, it returns an error, not allowing me to use the model I had trained with Tensorflow.

**Comment by amahendrakar** [comment]
@rzimmerdev,
I was able to load the default model without any issues. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/3f79b58ce5ccd6299bba4ead37f49190/41482.ipynb).

In order to reproduce the issue, could you please share the code and the model you've built. Thanks!

**Comment by rzimmerdev** [comment]
Yes, this is the model I froze and am now trying to use to predict the labels:
(I used the following command to freeze the model, as suggested in [the tutorial](https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html)):
`python export_inference_graph.py --input_type image_tensor --pipeline_config_path training/ssd_inception_v2_coco.config --trained_checkpoint_prefix training/model.ckpt-13302 --output_directory trained-inference-graphs/output_inference_graph_v1.pb`

[Frozen model](https://drive.google.com/drive/folders/1xnwN6kYJtWo4JHSEpWUfH0KHlx-YyP5u?usp=sharing)

The command used to try and load the model was:
`image_data = tf.gfile.FastGFile('ssd_mobilenet_v1_coco_2017_11_17/output_inference_graph_v1.pb', 'rb').read()`

Before loading the model, I moved the .pb file to another folder, but I don't happen to think this should lead to any changes.

**Comment by rzimmerdev** [comment]
I am so sorry for my mistake, as I have solved the issue myself. 
The problem was that I was freezing my model in a folder ending with .pb, and not a file with the .pb extension, as I thought that the default frozen model for the tutorial was also a folder with the .pb extension. 

**Redirecting my path to the .pb file inside my previous folder with the .pb ending changed the problem**, and I no longer received the Access Denied Error

**Comment by larawehbe** [comment]
@rzimmerdev  Solved my problem after a full day of troubleshooting !! Thanks !!

**Comment by ttoavina** [comment]
> I am so sorry for my mistake, as I have solved the issue myself. The problem was that I was freezing my model in a folder ending with .pb, and not a file with the .pb extension, as I thought that the default frozen model for the tutorial was also a folder with the .pb extension.
> 
> **Redirecting my path to the .pb file inside my previous folder with the .pb ending changed the problem**, and I no longer received the Access Denied Error

In my case , i have two .pb file `keras_metadata.pb` and `saved_model.pb` , which pb file should i use to load weight?

**Comment by rzimmerdev** [comment]
Ise the saved_model.pb

**Comment by ttoavina** [comment]
When i use `saved_model.pb` , there is another error on my terminal:

`
2022-07-13 18:18:14.670004: W tensorflow/core/util/tensor_slice_reader.cc:96] Could not open C:\Users\Toavina\PycharmProjects\flask-ml-bridge\model_weight\saved_model.pb: DATA_LOSS: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
  File "C:\Users\Toavina\PycharmProjects\flask-ml-bridge\test.py", line 5, in <module>
    predictor = Predictor()
  File "C:\Users\Toavina\PycharmProjects\flask-ml-bridge\transformer\predictor\predictor.py", line 43, in __init__
    self.transformer.load_weights(self.model)
  File "C:\Users\Toavina\PycharmProjects\flask-ml-bridge\venv\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Toavina\PycharmProjects\flask-ml-bridge\venv\lib\site-packages\h5py\_hl\files.py", line 533, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "C:\Users\Toavina\PycharmProjects\flask-ml-bridge\venv\lib\site-packages\h5py\_hl\files.py", line 226, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 106, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
`
this problem happen when i'm trying to load a pretrained weight
I'm using tensorflow v2.9 on my local project and this error is always shownig but when i try to copy/paste my code on google on google colab , then it work fine

**Comment by aravinthk00** [comment]
I also froze on same issue , anyone help me in this error . I  am very new this field so could you give clear solution 

(myenv) C:\Users\Downloads\Function-level>python main.py --config config\config.yaml --data_dir=data\ --embedding ELMo
Using TensorFlow backend.
2022-08-11 10:41:35.159324: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
[INFO] Start training process....
[INFO] Loading data from C:\Users\30863\Downloads\Function-level\data\....
[INFO] The length of the loaded data list is : 622
[INFO] Applying ELMo model!
[INFO] Setting padding length 1000 for ELMo model. Each textual sequence contains 1000 elements.
[INFO] Patition the data ....
[INFO] Data processing completed!
[INFO] -------------------------------------------------------
[INFO] There are 397 total samples in the training set. 28 vulnerable samples.
[INFO] There are 100 total samples in the validation set. 8 vulnerable samples.
[INFO] -------------------------------------------------------
2022-08-11 10:41:37.696665: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2022-08-11 10:41:37.706766: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2022-08-11 10:41:37.706953: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
2022-08-11 10:41:37.714121: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: 30863-436055
2022-08-11 10:41:37.715064: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: 30863-436055
[INFO] No GPU detected.
[INFO] Using CPU for training. It may take considerable time!
[INFO] Loading the elmo model.
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    helper.exec()
  File "C:\Users\30863\Downloads\Function-level\src\helper.py", line 251, in exec
    model_func = elmo_network.build_elmo_network(GPU_flag)
  File "C:\Users\30863\Downloads\Function-level\src\models\elmo_network.py", line 43, in build_elmo_network
    elmo_embedding = Lambda(self.make_elmo_embedding, output_shape=(None, 1024))(elmo_input)
  File "C:\Users\30863\Anaconda3\envs\myenv\lib\site-packages\keras\engine\base_layer.py", line 489, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\Users\30863\Anaconda3\envs\myenv\lib\site-packages\keras\layers\core.py", line 716, in call
    return self.function(inputs, **arguments)
  File "C:\Users\30863\Downloads\Function-level\src\models\elmo_network.py", line 35, in make_elmo_embedding
    elmo_model = hub.Module("https://tfhub.dev/google/elmo/2", trainable=True)
  File "C:\Users\30863\Anaconda3\envs\myenv\lib\site-packages\tensorflow_hub\module.py", line 157, in __init__
    self._spec = as_module_spec(spec)
  File "C:\Users\30863\Anaconda3\envs\myenv\lib\site-packages\tensorflow_hub\module.py", line 30, in as_module_spec
    return load_module_spec(spec)
  File "C:\Users\30863\Anaconda3\envs\myenv\lib\site-packages\tensorflow_hub\module.py", line 65, in load_module_spec
    return registry.loader(path)
  File "C:\Users\30863\Anaconda3\envs\myenv\lib\site-packages\tensorflow_hub\registry.py", line 51, in __call__
    return impl(*args, **kwargs)
  File "C:\Users\30863\Anaconda3\envs\myenv\lib\site-packages\tensorflow_hub\native_module.py", line 139, in __call__
    module_def_proto = self._get_module_def_proto(path)
  File "C:\Users\30863\Anaconda3\envs\myenv\lib\site-packages\tensorflow_hub\native_module.py", line 130, in _get_module_def_proto
    module_def_proto.ParseFromString(f.read())
  File "C:\Users\30863\Anaconda3\envs\myenv\lib\site-packages\tensorflow_core\python\lib\io\file_io.py", line 122, in read
    self._preread_check()
  File "C:\Users\30863\Anaconda3\envs\myenv\lib\site-packages\tensorflow_core\python\lib\io\file_io.py", line 84, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: C:\Users\30863\AppData\Local\Temp\tfhub_modules\9bb74bc86f9caffc8c47dd7b33ec4bb354d9602d\tfhub_module.pb : The system cannot find the file specified.
; No such file or directory

Thanks in advance...

**Comment by larawehbe** [comment]
> When i use `saved_model.pb` , there is another error on my terminal:
> 
> `2022-07-13 18:18:14.670004: W tensorflow/core/util/tensor_slice_reader.cc:96] Could not open C:\Users\Toavina\PycharmProjects\flask-ml-bridge\model_weight\saved_model.pb: DATA_LOSS: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator? Traceback (most recent call last): File "C:\Users\Toavina\PycharmProjects\flask-ml-bridge\test.py", line 5, in <module> predictor = Predictor() File "C:\Users\Toavina\PycharmProjects\flask-ml-bridge\transformer\predictor\predictor.py", line 43, in __init__ self.transformer.load_weights(self.model) File "C:\Users\Toavina\PycharmProjects\flask-ml-bridge\venv\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler raise e.with_traceback(filtered_tb) from None File "C:\Users\Toavina\PycharmProjects\flask-ml-bridge\venv\lib\site-packages\h5py\_hl\files.py", line 533, in __init__ fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr) File "C:\Users\Toavina\PycharmProjects\flask-ml-bridge\venv\lib\site-packages\h5py\_hl\files.py", line 226, in make_fid fid = h5f.open(name, flags, fapl=fapl) File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper File "h5py\h5f.pyx", line 106, in h5py.h5f.open OSError: Unable to open file (file signature not found)` this problem happen when i'm trying to load a pretrained weight I'm using tensorflow v2.9 on my local project and this error is always shownig but when i try to copy/paste my code on google on google colab , then it work fine

Hi, Check the version of TensorFlow on google colab. it might be TensorFlow version issue

**Comment by aravinthk00** [comment]
tensorflow 1.15 need for in my project , that's why used that version only comfortable. please give me a solution

**Comment by sparky-redstone** [comment]
W tensorflow/core/util/tensor_slice_reader.cc:96] Could not open D:\Coding\Projects\chatbot_Model: UNKNOWN: NewRandomAccessFile failed to Create/Open: D:\Coding\Projects\chatbot_Model : Access is denied.

This error is occures while i'm trying to load the model. can anybody tell what's the issue...

**Comment by larawehbe** [comment]
> W tensorflow/core/util/tensor_slice_reader.cc:96] Could not open D:\Coding\Projects\chatbot_Model: UNKNOWN: NewRandomAccessFile failed to Create/Open: D:\Coding\Projects\chatbot_Model : Access is denied.
> 
> This error is occures while i'm trying to load the model. can anybody tell what's the issue...

Make sure that you have the requried permission. The error says "Access is denied"
So, the file you are trying to call in your file directory "D:\Coding\Projects\chatbot_Model", you are not granted with the full permission for it. 
You have two options:
1. Find how to give more permissions for the current user you are using ( I dont know how to do it in windows so you need to search for it)
2. Put the file in a folder where you have general access to it, for example C:/ or Desktop might (or might not, you need to test) work.

**Comment by Zemulax** [comment]
Sorry, guys, but where is the solution? Permissions is not working for me, neither is changing the file location.
Thanks!
