### ISSUE TITLE
Building fails at //tensorflow/python/keras/api:keras_python_api_gen_compat_v1

### ISSUE THREAD

**Issue by hans-ekbrand** [tensorflow/tensorflow#41490]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian "sid"
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): NA
- TensorFlow version: r2.3
- Python version: 3.8
- Installed using virtualenv? pip? conda?: NA
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): 8.4.0
- CUDA/cuDNN version: 10.1/7.6.5
- GPU model and memory: NA
I should mention that this box has a CPU without AVX support (which is why I need to build from source).

The build fails almost at the end with this stack trace

```ERROR: /home/hans/src/tensorflow.bak/tensorflow/python/keras/api/BUILD:123:1: Executing genrule //tensorflow/python/keras/api:keras_python_api_gen_compat_v1 failed (Exit 1)
Traceback (most recent call last):
  File "/home/hans/.cache/bazel/_bazel_hans/2d6565a8de40a1199bd197af102140f1/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: /home/hans/.cache/bazel/_bazel_hans/2d6565a8de40a1199bd197af102140f1/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZTIN6icu_678ByteSinkE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hans/.cache/bazel/_bazel_hans/2d6565a8de40a1199bd197af102140f1/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 26, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/home/hans/.cache/bazel/_bazel_hans/2d6565a8de40a1199bd197af102140f1/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "/home/hans/.cache/bazel/_bazel_hans/2d6565a8de40a1199bd197af102140f1/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/eager/context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "/home/hans/.cache/bazel/_bazel_hans/2d6565a8de40a1199bd197af102140f1/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/hans/.cache/bazel/_bazel_hans/2d6565a8de40a1199bd197af102140f1/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/hans/.cache/bazel/_bazel_hans/2d6565a8de40a1199bd197af102140f1/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: /home/hans/.cache/bazel/_bazel_hans/2d6565a8de40a1199bd197af102140f1/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZTIN6icu_678ByteSinkE


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/hans/src/tensorflow.bak/tensorflow/tools/pip_package/BUILD:66:1 Executing genrule //tensorflow/python/keras/api:keras_python_api_gen_compat_v1 failed (Exit 1)
INFO: Elapsed time: 32684.441s, Critical Path: 205.34s
INFO: 23720 processes: 23720 local.
FAILED: Build did NOT complete successfully
```
The command was a straight 
`bazel build //tensorflow/tools/pip_package:build_pip_package`

The content of `tf_configure.bazel`

```build --action_env PYTHON_BIN_PATH="/usr/bin/python3"
build --action_env PYTHON_LIB_PATH="/usr/lib/python3/dist-packages"
build --python_path="/usr/bin/python3"
build --config=xla
build --action_env CUDA_TOOLKIT_PATH="/usr/local/cuda"
build --action_env TF_CUDA_COMPUTE_CAPABILITIES="6.1"
build --action_env GCC_HOST_COMPILER_PATH="/usr/bin/x86_64-linux-gnu-gcc-8"
build --config=cuda
build:opt --copt=-march=native
build:opt --host_copt=-march=native
build:opt --define with_default_optimizations=true
test --flaky_test_attempts=3
test --test_size_filters=small,medium
test --test_env=LD_LIBRARY_PATH
test:v1 --test_tag_filters=-benchmark-test,-no_oss,-no_gpu,-oss_serial
test:v1 --build_tag_filters=-benchmark-test,-no_oss,-no_gpu
test:v2 --test_tag_filters=-benchmark-test,-no_oss,-no_gpu,-oss_serial,-v1only
test:v2 --build_tag_filters=-benchmark-test,-no_oss,-no_gpu,-v1only
build --action_env TF_CONFIGURE_IOS="0"```

**Comment by amahendrakar** [comment]
@hans-ekbrand,
Could you please check if you have installed the TensorFlow pip package dependencies as mentioned in [this guide](https://www.tensorflow.org/install/source#install_python_and_the_tensorflow_package_dependencies).

```
pip install -U --user pip six 'numpy<1.19.0' wheel setuptools mock 'future>=0.17.1'
pip install -U --user keras_applications --no-deps
pip install -U --user keras_preprocessing --no-deps
```

Please take a look at this similar issue [#36903](https://github.com/tensorflow/tensorflow/issues/36903) for reference. Thanks!

**Comment by hans-ekbrand** [comment]
Thanks for helping me out, @amahendrakar. Here are the installed modules in this virtual environment:

```hans@gpu-master:~$ source ~/.virtualenvs/tf_dev/bin/activate
(tf_dev) hans@gpu-master:~$ pip list
Package             Version
------------------- -------
future              0.18.2
Keras-Applications  1.0.8
Keras-Preprocessing 1.1.2
mock                4.0.2
numpy               1.18.5
pip                 20.1.1
pkg-resources       0.0.0
setuptools          49.2.0
six                 1.15.0
wheel               0.34.2
```

**Comment by hans-ekbrand** [comment]
Can one replicate the failing step manually? I was thinking about using `strace` to identify the files that the failing step opens.

**Comment by mihaimaruseac** [comment]
````
ImportError: .../_pywrap_tensorflow_internal.so: undefined symbol: _ZTIN6icu_678ByteSinkE
```

This means there is a linker error. [Demangling](https://demangler.com/) says that `typeinfo for icu_67::ByteSink` is not found. This does not look like a TF error, though, since TF does not directly depend on ICU. Most likely your system has an incompatible version of that library.

**Comment by hans-ekbrand** [comment]
This is the version of icu I seem to have installed, which version should I have?
```
dpkg -l | grep "icu" | grep ^ii
ii  icu-devtools                               67.1-2                          amd64        Development utilities for International Components for Unicode
ii  libharfbuzz-icu0:amd64                     2.6.7-1                         amd64        OpenType text shaping engine ICU backend
ii  libicu-dev:amd64                           67.1-2                          amd64        Development files for International Components for Unicode
ii  libicu67:amd64                             67.1-2                          amd64        International Components for Unicode
```

**Comment by gowthamkpr** [comment]
@hans-ekbrand Were you able to figure out the cause of this issue?
