### ISSUE TITLE
Tensorflow

### ISSUE THREAD

**Issue by Parrass** [tensorflow/tensorflow#41512]
When I try using keras, says that I dont have tensorflow 2.2.0 installed, but i do. Can someone help me? I already uninstalled tensorflow and the same thing happens. Also I reinstalled Anaconda and nothing.

from keras.models import Sequential
Traceback (most recent call last):

  File "C:\Users\luiz_\anaconda3\lib\site-packages\keras\__init__.py", line 3, in <module>
    from tensorflow.keras.layers.experimental.preprocessing import RandomRotation

  File "C:\Users\luiz_\AppData\Roaming\Python\Python37\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util

  File "C:\Users\luiz_\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context

  File "C:\Users\luiz_\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe

  File "C:\Users\luiz_\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow

ImportError: cannot import name 'pywrap_tensorflow' from 'tensorflow.python' (C:\Users\luiz_\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-1-9c5e0a19b646>", line 1, in <module>
    from keras.models import Sequential

  File "C:\Users\luiz_\anaconda3\lib\site-packages\keras\__init__.py", line 6, in <module>
    'Keras requires TensorFlow 2.2 or higher. '

ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`

**Comment by lordtt13** [comment]
Try using Keras from inside TF if you have TF installed.
```python
from tensorflow.keras.models import Sequential
```

**Comment by Parrass** [comment]
I tried and this happened:

from tensorflow.keras.models import Sequential
Traceback (most recent call last):

  File "<ipython-input-2-f05745da3b73>", line 1, in <module>
    from tensorflow.keras.models import Sequential

  File "C:\Users\luiz_\AppData\Roaming\Python\Python37\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util

  File "C:\Users\luiz_\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context

  File "C:\Users\luiz_\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe

  File "C:\Users\luiz_\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow

ImportError: cannot import name 'pywrap_tensorflow' from 'tensorflow.python' (C:\Users\luiz_\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\__init__.py)

**Comment by lordtt13** [comment]
Try one thing, remove all your python installations and CUDA installation and download using [Anaconda](https://docs.anaconda.com/anaconda/install/linux/) and you can install TF2 with CUDA bindings using:
```bash
conda install -c anaconda tensorflow-gpu
```

**Comment by Parrass** [comment]
I tried, didnt work...

from tensorflow.keras.models import Sequential
Traceback (most recent call last):

  File "<ipython-input-2-f05745da3b73>", line 1, in <module>
    from tensorflow.keras.models import Sequential

  File "C:\Users\luiz_\AppData\Roaming\Python\Python37\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util

  File "C:\Users\luiz_\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context

  File "C:\Users\luiz_\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe

  File "C:\Users\luiz_\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow

ImportError: cannot import name 'pywrap_tensorflow' from 'tensorflow.python' (C:\Users\luiz_\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\__init__.py)

**Comment by lordtt13** [comment]
Can you describe your system details:
#### System information:
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on a mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by Parrass** [comment]
**Systeminformation:**
**OS Platform and Distribution (e.g., Linux Ubuntu 16.04):** Microsoft Windows 10
**TensorFlow installed from (source or binary):** Binary
**TensorFlow version (use command below):** TensorFlow 2.2.0
**Python version:** 3.7.6
**Bazel version (if compiling from source):**
**GCC/Compiler version (if compiling from source):**
**CUDA/cuDNN version:** 10.0.130
**GPU model and memory:**GeForce MX130; 8Gb RAM

**Comment by lordtt13** [comment]
So I don't think GeForce MX130 has CUDA support, [(check here)](https://developer.nvidia.com/cuda-gpus)

[PyWrap Error resolved here](https://stackoverflow.com/questions/35953210/error-running-basic-tensorflow-example)

**Comment by mihaimaruseac** [comment]
Please always fill in issue template.

Please use ` ``` ` before and after code and error blocks to make them readable.

Please post output of `pip list`.
