### ISSUE TITLE
No gradients provided for any variable. TF 2.1.0

### ISSUE THREAD

**Issue by rensjochemsen** [tensorflow/tensorflow#41528]
I am trying to build an implicit quantile network. I build a custom loss function but do not get it working. I get the error 'no gradients available' but I belief I only use functions that should provide gradients, like tf.tile and stuff. I dont explicityly cast something in my loss_kv_iq() function.

Below I provide the code for my custom layer ( IQNlayer ) , the network I use (IQN),  and my custom loss function. Also a small piece of code in the __main__  that should be able to reproduce the error. 

TF version: 2.1.0

```
import tensorflow as tf
import tensorflow.keras as keras
import numpy as np
  
class IQN(keras.Model):
    def __init__(self, quantile_dims, fc_dims, n_actions, n_quantiles):
        super(IQN, self).__init__()
        self.n_quantiles = n_quantiles
                
        initializer = keras.initializers.he_uniform()
    
        self.iq = IQNlayer(quantile_dims, n_quantiles)
        self.dense = keras.layers.Dense(fc_dims, activation='relu', kernel_initializer = initializer)
        self.out = keras.layers.Dense(n_actions, activation = None)
    
    def call(self, state, tau):
        batch_size, state_size = state.shape
        
        x = self.iq(state, tau)
        x = self.dense(x)
        x = self.out(x)
        
        x = tf.transpose(tf.split(x, batch_size, axis=0), perm=[0, 2, 1])
        return x
    
      
class IQNlayer(keras.layers.Layer):
    def __init__(self, quantile_dims, n_quantiles):
        super(IQNlayer, self).__init__()
        self.quantile_dims = quantile_dims
        self.n_quantiles = n_quantiles
        
        self.fc1 = keras.layers.Dense(self.quantile_dims, activation = tf.nn.selu)
        self.fc2 = keras.layers.Dense(self.quantile_dims, activation = tf.nn.relu)
        
    def call(self, state, tau):
        batch_size, state_size = state.shape
        
        state_tile = tf.tile(state, [1, self.n_quantiles])
        state_reshape = tf.reshape(state_tile, [-1, state_size])
        state_net = self.fc1(state_reshape)
        
        tau = tf.reshape(tau, [-1, 1])
        pi_mtx = tf.constant(np.expand_dims(np.pi * np.arange(0, 64), axis=0), dtype=tf.float32)
        cos_tau = tf.cos(tf.matmul(tau, pi_mtx))
        phi = self.fc2(cos_tau)
        
        net = tf.multiply(state_net, phi)
        return net
    

def loss_kv_iq(x, tau, action_hot, theta_target):
    expand_dim_action = tf.expand_dims(action_hot, -1)
    main_support = tf.reduce_sum(x * expand_dim_action, axis=1)

    theta_loss_tile = tf.tile(tf.expand_dims(main_support, axis=2), [1, 1, N_QUANTILES])
    logit_valid_tile = tf.tile(tf.expand_dims(theta_target, axis=1), [1, N_QUANTILES, 1])
    Huber_loss = hloss(logit_valid_tile, theta_loss_tile)
    
    inv_tau = 1 - tau
    tau = tf.tile(tf.expand_dims(tau, axis=1), [1, N_QUANTILES, 1])
    inv_tau = tf.tile(tf.expand_dims(inv_tau, axis=1), [1, N_QUANTILES, 1])
    error_loss = logit_valid_tile - theta_loss_tile

    Loss = tf.where(tf.less(error_loss, 0.0), inv_tau * Huber_loss, tau * Huber_loss)
    loss = tf.reduce_mean(tf.reduce_sum(tf.reduce_mean(Loss, axis=2), axis=1))
    return loss
        
if __name__ == '__main__':
    hloss = tf.keras.losses.Huber(reduction = tf.keras.losses.Reduction.NONE)
    
    N_QUANTILES = 10
    BATCH_SIZE = 2
    ACTION_SIZE = 5
    STATE_SIZE = 16
    
    # FOR EXAMPLE: RANDOM BATCH
    cs = np.random.rand(BATCH_SIZE,STATE_SIZE)
    a = np.random.randint(0,5,size=(2))
    r = np.random.randint(0,500,size=(2))
    ns = np.random.rand(BATCH_SIZE,STATE_SIZE)
    
    tau = np.random.uniform(size=(BATCH_SIZE, N_QUANTILES))
    tau = tau.astype('float32')    
    iq = IQN(128,128,ACTION_SIZE,N_QUANTILES)
    
    action_hot = np.zeros((BATCH_SIZE,ACTION_SIZE), dtype = np.float32)
    action_hot[np.arange(BATCH_SIZE), a] = 1
    
    Q = iq(ns, tau)
    theta_target = np.random.rand(BATCH_SIZE,N_QUANTILES)
    theta_target = theta_target.astype('float32')
    
    optimizer = tf.keras.optimizers.Adam(lr = 1e-3)
    
    with tf.GradientTape() as tape:
        loss = loss_kv_iq(Q, tau, action_hot, theta_target)
        grads = tape.gradient(loss, iq.trainable_weights)
        optimizer.apply_gradients(zip(grads,iq.trainable_weights))
```

Error:

```
Traceback (most recent call last):

  File "C:\Users\rensj\.spyder-py3\Thesis\test.py", line 106, in <module>
    optimizer.apply_gradients(zip(grads,iq.trainable_weights))

  File "C:\Users\rensj\Anaconda3\envs\tfnew\lib\site-packages\tensorflow_core\python\keras\optimizer_v2\optimizer_v2.py", line 426, in apply_gradients
    grads_and_vars = _filter_grads(grads_and_vars)

  File "C:\Users\rensj\Anaconda3\envs\tfnew\lib\site-packages\tensorflow_core\python\keras\optimizer_v2\optimizer_v2.py", line 1039, in _filter_grads
    ([v.name for _, v in grads_and_vars],))

ValueError: No gradients provided for any variable: ['iqn_4/iq_nlayer_4/dense_16/kernel:0', 'iqn_4/iq_nlayer_4/dense_16/bias:0', 'iqn_4/iq_nlayer_4/dense_17/kernel:0', 'iqn_4/iq_nlayer_4/dense_17/bias:0', 'iqn_4/dense_18/kernel:0', 'iqn_4/dense_18/bias:0', 'iqn_4/dense_19/kernel:0', 'iqn_4/dense_19/bias:0'].
```

EDIT: Someone pointed out that I used numpy operation in the following line:
```
 pi_mtx = tf.constant(np.expand_dims(np.pi * np.arange(0, 64), axis=0), dtype=tf.float32)
```

I changed this line to 
```
pi_mtx = tf.constant(tf.expand_dims(tf.constant(np.pi) * tf.range(0, 64, dtype=tf.float32), axis=0), dtype=tf.float32)
   ```
But keep getting the same error

--
CORRELATED TO:
https://github.com/tensorflow/tensorflow/issues/1511

**Comment by rensjochemsen** [comment]
https://github.com/tensorflow/tensorflow/issues/1511

**Comment by Saduf2019** [comment]
@rensjochemsen 
Can you please refer to [this link](https://stackoverflow.com/questions/41689451/valueerror-no-gradients-provided-for-any-variable) with same error reported and let us know if it helps.
[link](https://stackoverflow.com/questions/49289930/tensorflow-no-gradients-provided-for-any-variable?rq=1) [link1](https://www.reddit.com/r/tensorflow/comments/ghcwcj/user_error_or_bug_valueerror_no_gradients/)

**Comment by rensjochemsen** [comment]
@Saduf2019  Thanks for your answer and sorry for my late reply. I looked at the topics you mention but it did not help me solve my problem.

**Comment by jvishnuvardhan** [comment]
@rensjochemsen I am noticing a size incompatibility error. Please check the [gist](https://colab.research.google.com/gist/jvishnuvardhan/3ceea259576d2b01750ab7a8a953e305/untitled.ipynb) and update if it is required. Specifically, shape of `Huber_loss` is breaking the code.

```
    print(error_loss.shape) # this is (2, 10, 10)
    print(inv_tau.shape)    # this is (2, 10, 10)
    print(tau.shape)        # this is (2, 10, 10)
    print(Huber_loss.shape) # this is (2, 10)
```

Please check whether this is the error you are noticing? Thanks

**Comment by rensjochemsen** [comment]
@jvishnuvardhan Thanks for your help and answer, although I am quite sure the dimensions are correct.

I did solve my error/problem, and I a little bit ashamed by it actually. I had to calculate the 'predictions' within the scope of the tf.GradientTape():

OLD CODE:
```
## .... stufff
Q = iq(ns, tau)
## .... stuff
with tf.GradientTape() as tape:
        loss = loss_kv_iq(Q, tau, action_hot, theta_target)
        grads = tape.gradient(loss, iq.trainable_weights)
        optimizer.apply_gradients(zip(grads,iq.trainable_weights))

```


NEW, WORKING CODE:
```
## .. stuff
with tf.GradientTape() as tape:
        Q = iq(ns, tau)
        loss = loss_kv_iq(Q, tau, action_hot, theta_target)
        grads = tape.gradient(loss, iq.trainable_weights)
        optimizer.apply_gradients(zip(grads,iq.trainable_weights))



```
so it was merely moving one line code
