### ISSUE TITLE
tensorflow_gpu-1.4.0 requires libcudart.so.10.0 rather than libcudart.so.8.0

### ISSUE THREAD

**Issue by xuyifangreeneyes** [tensorflow/tensorflow#41541]
**System information**
- OS Platform and Distribution: Linux Ubuntu 16.04
- Mobile device if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.4.0
- Python version: 3.6.10
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 8.0 / 6
- GPU model and memory: Tesla V100-SXM2-16GB

**Describe the problem**
I tried to use openai's [blocksparse](https://github.com/openai/blocksparse), which requires CUDA 8 and Tensorflow 1.4.0. When I `import blocksparse`, the error `tensorflow.python.framework.errors_impl.NotFoundError: libcudart.so.10.0: cannot open shared object file: No such file or directory` is raised. Since tensorflow_gpu-1.4.0 is compatible with CUDA 8, I wonder why `libcudart.so.10.0` is required rather than `libcudart.so.8.0`. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
First I created a conda environment and activated it.
```
conda create -n py36-bs python=3.6
conda activate py36-bs
```
Then I installed TensorFlow 1.4.0.
```
pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.4.0-cp36-cp36m-linux_x86_64.whl
```
Next I installed [blocksparse](https://github.com/openai/blocksparse).
```
pip install blocksparse
```
When I tried to `import bloacksparse`, an error occurred.
```
Python 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import blocksparse
/home/ubuntu/anaconda3/envs/py36-bs/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:469: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/ubuntu/anaconda3/envs/py36-bs/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:470: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/ubuntu/anaconda3/envs/py36-bs/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:471: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/ubuntu/anaconda3/envs/py36-bs/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:472: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/ubuntu/anaconda3/envs/py36-bs/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:473: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/ubuntu/anaconda3/envs/py36-bs/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:476: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/ubuntu/anaconda3/envs/py36-bs/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/py36-bs/lib/python3.6/site-packages/blocksparse/__init__.py", line 3, in <module>
    from blocksparse.utils import (
  File "/home/ubuntu/anaconda3/envs/py36-bs/lib/python3.6/site-packages/blocksparse/utils.py", line 16, in <module>
    _op_module = tf.load_op_library(os.path.join(data_files_path, 'blocksparse_ops.so'))
  File "/home/ubuntu/anaconda3/envs/py36-bs/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/home/ubuntu/anaconda3/envs/py36-bs/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: libcudart.so.10.0: cannot open shared object file: No such file or directory
>>>
```

**Any other info / logs**
I checked several things related to CUDA.
```
(py36-bs) ubuntu@xxx:~$ ls -l /usr/local/cuda
lrwxrwxrwx 1 root root 19 Jul 19 13:13 /usr/local/cuda -> /usr/local/cuda-8.0
```
```
(py36-bs) ubuntu@xxx:~$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
```
```
(py36-bs) ubuntu@xxx:~$ echo $PATH
/home/ubuntu/anaconda3/envs/py36-bs/bin:/home/ubuntu/anaconda3/bin:/home/ubuntu/anaconda3/bin:/home/ubuntu/anaconda3/bin:/usr/local/cuda/bin:/usr/local/bin:/opt/aws/bin:/usr/local/mpi/bin:/usr/local/cuda/bin:/usr/local/bin:/opt/aws/bin:/home/ubuntu/.dl_binaries/bin:/usr/local/mpi/bin:/opt/aws/neuron/bin:/home/ubuntu/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/bin:/home/ubuntu/anaconda3/bin:/home/ubuntu/bin:/home/ubuntu/.local/bin:/home/ubuntu/anaconda3/condabin:/home/ubuntu/anaconda3/bin:/usr/local/cuda/bin:/usr/local/bin:/opt/aws/bin:/usr/local/mpi/bin:/usr/local/cuda/bin:/usr/local/bin:/opt/aws/bin:/home/ubuntu/.dl_binaries/bin:/usr/local/mpi/bin:/opt/aws/neuron/bin:/usr/local/cuda/bin:/usr/local/bin:/opt/aws/bin:/usr/local/mpi/bin:/opt/amazon/openmpi/bin:/opt/amazon/efa/bin:/home/ubuntu/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/bin:/home/ubuntu/anaconda3/bin:/home/ubuntu/bin:/home/ubuntu/.local/bin:/home/ubuntu/anaconda3/bin:/usr/local/cuda/bin:/usr/local/bin:/opt/aws/bin:/usr/local/mpi/bin:/usr/local/cuda/bin:/usr/local/bin:/opt/aws/bin:/home/ubuntu/.dl_binaries/bin:/usr/local/mpi/bin:/opt/aws/neuron/bin:/usr/local/cuda/bin:/usr/local/bin:/opt/aws/bin:/usr/local/mpi/bin:/opt/amazon/openmpi/bin:/opt/amazon/efa/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```
```
(py36-bs) ubuntu@xxx:~$ echo $LD_LIBRARY_PATH
/usr/lib64/openmpi/lib/:/usr/local/cuda/lib64:/usr/local/lib:/usr/lib:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/mpi/lib:/lib/:/usr/local/cuda-9.0/lib/:/usr/lib64/openmpi/lib/:/usr/local/cuda/lib64:/usr/local/lib:/usr/lib:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/mpi/lib:/lib/:/usr/local/cuda-9.0/lib/:/usr/lib64/openmpi/lib/:/usr/local/cuda/lib64:/usr/local/lib:/usr/lib:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/mpi/lib:/lib/:/usr/local/cuda-9.0/lib/:/usr/lib64/openmpi/lib/:/usr/local/cuda/lib64:/usr/local/lib:/usr/lib:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/mpi/lib:/lib/:/usr/local/cuda-9.0/lib/:/usr/lib64/openmpi/lib/:/usr/local/cuda/lib64:/usr/local/lib:/usr/lib:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/mpi/lib:/lib/:/usr/local/cuda-9.0/lib/:
```
`libcudart.so.8.0` exists but TensorFlow asked for `libcudart.so.10.0`. 
```
(py36-bs) ubuntu@xxx:~$ ls -l /usr/local/cuda/lib64/libcudart.so.8.0
lrwxrwxrwx 1 root root 19 Jun 17 01:36 /usr/local/cuda/lib64/libcudart.so.8.0 -> libcudart.so.8.0.61
```
Besides, there exist multiple versions of CUDA on my machine.
```
(py36-bs) ubuntu@xxx:~$ ls /usr/local/
bin  cuda  cuda-10.0  cuda-10.1  cuda-10.2  cuda-8.0  cuda-9.0  cuda-9.2  etc  games  include  init  lib  man  mpi  sbin  share  src
```
Is the problem related to GPU driver? When I entered `nvidia-smi`, `CUDA Version` is `10.2`.

Since I met some wired problems when I tried to run [blocksparse](https://github.com/openai/blocksparse) with CUDA 10.0, I want to use CUDA 8.0, which is the version authors of [blocksparse](https://github.com/openai/blocksparse) use. Could anyone help me with the error? Thanks a lot!

tensorflow_gpu-1.4.0 requires libcudart.so.10.0 rather than libcudart.so.8.0

**Comment by jvishnuvardhan** [comment]
@xuyifangreeneyes I guess this issue is more suitable to be posted on [blocksparse](https://github.com/openai/blocksparse/issues) repo. Please post your issue there as this repo is related to core Tensorflow. 


I am closing this issue. Please feel free to reopen if I am mistaken. Thanks!

**Comment by KhuongDiep911** [comment]
Hi,

Did you solve your problem?
I'm using tensorflow 2 but surfering this problem. Can you help me, please?

Thanks in advance.
