### ISSUE TITLE
RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 1 (FlexRandomStandardNormal) failed to prepare.

### ISSUE THREAD

**Issue by Pyrsos** [tensorflow/tensorflow#41558]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): 2.2.0

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

Colab link here: https://colab.research.google.com/gist/Pyrsos/2e1021981a779b0d41ee51de5b3fd321/bayesiannn_tflite_issue.ipynb

And in case the link does not work here is the code:
```
import tensorflow as tf
import tensorflow_probability as tfp
from tensorflow_probability import distributions as tfd

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

x_train = x_train.astype('float32')/255.
x_test = x_test.astype('float32')/255.

kl_divergence_function = (lambda q, p, _: tfd.kl_divergence(q, p) /
                          tf.cast(x_train.shape[0], dtype=tf.float32))

model = tf.keras.Sequential([
    tf.keras.layers.Flatten(),
    tfp.layers.DenseFlipout(
        10, kernel_divergence_fn=kl_divergence_function,
        activation=tf.nn.softmax
    ),
])

optimizer = tf.keras.optimizers.Adam(lr=0.001)
model.compile(optimizer, loss='sparse_categorical_crossentropy')
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=3)

tflite_converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                              tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = tflite_converter.convert()

tflite_interpreter = tf.lite.Interpreter(model_content=tflite_model)
tflite_interpreter.allocate_tensors()

```

**The output from the converter invocation**

```
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
11493376/11490434 [==============================] - 1s 0us/step
2020-07-20 12:34:31.727019: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-07-20 12:34:31.727189: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
2020-07-20 12:34:31.727228: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (0effea1c9ee4): /proc/driver/nvidia/version does not exist
2020-07-20 12:34:31.727927: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-07-20 12:34:31.739524: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2192950000 Hz
2020-07-20 12:34:31.739933: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fd2d0000b20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-20 12:34:31.739972: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-07-20 12:34:31.758131: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 188160000 exceeds 10% of free system memory.
Epoch 1/3
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/layers/util.py:106: Layer.add_variable (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.add_weight` method instead.
1871/1875 [============================>.] - ETA: 0s - loss: 0.80902020-07-20 12:34:36.954654: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 31360000 exceeds 10% of free system memory.
1875/1875 [==============================] - 5s 3ms/step - loss: 0.8086 - val_loss: 0.5851
Epoch 2/3
1854/1875 [============================>.] - ETA: 0s - loss: 0.55612020-07-20 12:34:42.216506: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 31360000 exceeds 10% of free system memory.
1875/1875 [==============================] - 5s 3ms/step - loss: 0.5546 - val_loss: 0.5113
Epoch 3/3
1863/1875 [============================>.] - ETA: 0s - loss: 0.50292020-07-20 12:34:47.170768: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 31360000 exceeds 10% of free system memory.
1875/1875 [==============================] - 5s 3ms/step - loss: 0.5030 - val_loss: 0.4894
2020-07-20 12:34:47.848009: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2020-07-20 12:34:47.848232: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-07-20 12:34:47.852393: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:797] Optimization results for grappler item: graph_to_optimize
2020-07-20 12:34:47.852454: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   function_optimizer: function_optimizer did nothing. time = 0.003ms.
2020-07-20 12:34:47.852466: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-07-20 12:34:47.946289: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2020-07-20 12:34:47.946632: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-07-20 12:34:47.962972: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:797] Optimization results for grappler item: graph_to_optimize
2020-07-20 12:34:47.963044: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   constant_folding: Graph size after: 66 nodes (-64), 67 edges (-65), time = 8.269ms.
2020-07-20 12:34:47.963056: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   constant_folding: Graph size after: 66 nodes (0), 67 edges (0), time = 1.115ms.
Traceback (most recent call last):
  File "example.py", line 31, in <module>
    tflite_interpreter.allocate_tensors()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/interpreter.py", line 242, in allocate_tensors
    return self._interpreter.AllocateTensors()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py", line 110, in AllocateTensors
    return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 0 (FlexRandomUniformInt) failed to prepare.
```

**Also, please include a link to the saved model or GraphDef**

[model.zip](https://github.com/tensorflow/tensorflow/files/4947761/model.zip)

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
Conversion completes successfully but when the interpreter is used to invoke the converted tflite model the following error appears:
```
RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 0 (FlexRandomUniformInt) failed to prepare.
``` 

**Any other info / logs**

I opened a previous issue regarding this #40119, and was giving guidelines to surpass it. I have now applied this recommendation but I receive the error described in this post.

**Comment by ravikyram** [comment]
@Pyrsos 

I have not seeing any issue in TF nightly versions.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/c67a19c37ff28f02c67e36542555fd75/untitled153.ipynb).Please, verify once and close the issue.Thanks!

**Comment by Pyrsos** [comment]
@ravikyram 

It works!! Thank you for your quick response, I am closing down the issue.

**Comment by ZHHJemotion** [comment]
@Pyrsos  

Hi, I met one similar problem when I installed tf-2.3.0 on MacOS, it said tf lite cannot support "FlexRandomUniform". Luckly, when I installed tf-nightly-2.4.0.dev20200926, the bug was fixed. My colleagues did not meet this bug when he only used the same version tf-2.3.0 on Ubuntu. I have no idea why MacOS shows this bug, but Ubuntu doesn't.

**Comment by Threemages** [comment]
What if my board/system is 32 bit that tensorflow cannot be installed.
