### ISSUE TITLE
CategoryEncoding not working when loading model again

### ISSUE THREAD

**Issue by jclaessens97** [tensorflow/tensorflow#41552]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Linux Ubuntu 20.04 LTS** 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **N/A**
- TensorFlow installed from (source or binary): **nightly binary (tf-nightly-gpu)**
- TensorFlow version (use command below): **2.4.0-dev20200719**
- Python version: **3.8.2**
- Bazel version (if compiling from source): **N/A**
- GCC/Compiler version (if compiling from source): **N/A**
- CUDA/cuDNN version: **V10.1.243**
- GPU model and memory: **NVIDIA RTX2070s 8GB VRAM**

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When running **[this example](https://keras.io/examples/structured_data/structured_data_classification_from_scratch/)** but saving the model at the end and moving the predict code to another file (predict.py), I get the following error while loading the model: **RuntimeError: If you construct a `CategoryEncoding` layer with `max_tokens=None`, you need to call `adapt()` on it before using it**. 

**Describe the expected behavior**
I don't expect the error, but just being able to load the model and call predict on the model.

**Standalone code to reproduce the issue**
/

**Other info / logs** 
```
2020-07-19 19:11:26.244328: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Invalid MIT-MAGIC-COOKIE-1 key2020-07-19 19:11:27.161486: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-07-19 19:11:27.164500: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-19 19:11:27.164743: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:03:00.0 name: GeForce RTX 2070 SUPER computeCapability: 7.5
coreClock: 1.8GHz coreCount: 40 deviceMemorySize: 7.77GiB deviceMemoryBandwidth: 417.29GiB/s
2020-07-19 19:11:27.164756: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-07-19 19:11:27.165592: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-07-19 19:11:27.166145: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-07-19 19:11:27.166487: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-07-19 19:11:27.167819: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-07-19 19:11:27.168359: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2020-07-19 19:11:27.168437: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudnn.so.7'; dlerror: libcudnn.so.7: cannot open shared object file: No such file or directory
2020-07-19 19:11:27.168457: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1753] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-07-19 19:11:27.168681: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-07-19 19:11:27.172281: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 3600000000 Hz
2020-07-19 19:11:27.172519: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4b78d40 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-19 19:11:27.172531: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-07-19 19:11:27.175397: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-07-19 19:11:27.175415: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      
Traceback (most recent call last):
  File "predict.py", line 5, in <module>
    model = load_model("models/model")
  File "/home/jeroen/.local/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 187, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "/home/jeroen/.local/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 120, in load
    model = tf_load.load_internal(
  File "/home/jeroen/.local/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 632, in load_internal
    loader = loader_cls(object_graph_proto, saved_model_proto, export_dir,
  File "/home/jeroen/.local/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 194, in __init__
    super(KerasObjectLoader, self).__init__(*args, **kwargs)
  File "/home/jeroen/.local/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 130, in __init__
    self._load_all()
  File "/home/jeroen/.local/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 221, in _load_all
    self._finalize_objects()
  File "/home/jeroen/.local/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 530, in _finalize_objects
    self._reconstruct_all_models()
  File "/home/jeroen/.local/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 548, in _reconstruct_all_models
    self._reconstruct_model(model_id, model, layers)
  File "/home/jeroen/.local/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 588, in _reconstruct_model
    created_layers) = functional_lib.reconstruct_from_config(
  File "/home/jeroen/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/functional.py", line 1210, in reconstruct_from_config
    process_node(layer, node_data)
  File "/home/jeroen/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/functional.py", line 1158, in process_node
    output_tensors = layer(input_tensors, **kwargs)
  File "/home/jeroen/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 919, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "/home/jeroen/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1111, in _functional_construction_call
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/home/jeroen/.local/lib/python3.8/site-packages/tensorflow/python/keras/layers/preprocessing/category_encoding.py", line 282, in call
    raise RuntimeError(
RuntimeError: If you construct a `CategoryEncoding` layer with `max_tokens=None`, you need to call `adapt()` on it before using it
```

**Comment by IaroslavElistratov** [comment]
Same problem

**Comment by lukashondrich** [comment]
same here

**Comment by scd75** [comment]
got the same issue. Happens both when saving under a .h5 format, or tensorflow SavedModel

**Comment by Bernix01** [comment]
Workaround is to explicitly set the max_tokens and re-train->save->load, even if you call `adapt`.

**Comment by gowthamkpr** [comment]
@jclaessens97 @scd75 @lukashondrich @IaroslavElistratov As mentioned in the above comment, the workaround is to specify max_tokens in CategoryEncoding. Please find the [gist](https://colab.research.google.com/gist/gowthamkpr/93d57b30ed262aa7e5388a34a092be64/structured_data_classification_from_scratch.ipynb)

**Comment by DachuanZhao** [comment]
Any processing ?

**Comment by AITutorials** [comment]
same here

**Comment by grofte** [comment]
same - and the work-around is bit nonsense isn't it? The point of the preprocessing layer is to preprocess. If I have to do the same preprocessing... Okay so my workaround is going to be to make two preprocessing layers, adapt one with max_tokens=None, get the size of the vocabulary, adapt again on the second layer but with max_tokens=len(first_vectorizer.get_vocabulary()). Only return the second layer. 

Really dumb but at least I can write the same code twice (and wait twice as long for the adapt step) instead of having to write separate code that figures out what max_tokens should be.

**Comment by johnpaulett** [comment]
An alternative workaround is setting the max_tokens after adapt


```python
    ...
    # Learn the space of possible indices
    encoder.adapt(feature_ds)

    # WORKAROUND for tensorflow/tensorflow#41552
    # Lock the max_tokens to allow load_model
    encoder.max_tokens = encoder._combiner.max_tokens = len(index.get_vocabulary())

    # Apply one-hot encoding to our indices
    encoded_feature = encoder(encoded_feature)
    return encoded_feature
```

Still, would be nice to "freeze" the max_tokens automatically when saving the model.

**Comment by grofte** [comment]
@johnpaulett 
```python
len(index.get_vocabulary())
```
Don't you mean `encoder.get_vocabulary()`? Otherwise you still have to adapt twice.

**Comment by nikitamaia** [comment]
Running the second example from @gowthamkpr with `max_tokens = None` seems to be working in current TF Nightly. Please update this thread with an example if you're still seeing this error in nightly.

**Comment by NADA87** [comment]
Installing tensorflow version 2.5.0 will solve the problem

! pip install tensorflow==2.5.0

**Comment by Saduf2019** [comment]
@jclaessens97 
As the issue does not appear on tf 2.5, could you please upgrade and let us know.
