### ISSUE TITLE
tensorflow lite for android a bug: Node number 213 (TfLiteGpuDelegateV2) failed to invoke.

### ISSUE THREAD

**Issue by Kasqqqqqqq** [tensorflow/tensorflow#41550]
2020-07-20 13:21:08.699 24598-24632/org.gddi.ai.camera E/AndroidRuntime: FATAL EXCEPTION: Thread-5
    Process: org.gddi.ai.camera, PID: 24598
    java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: TfLiteGpuDelegate Invoke: Failed to read data from GPU (clEnqueueReadBuffer) - Execution status error for events in wait list
    Node number 213 (TfLiteGpuDelegateV2) failed to invoke.
    
        at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:158)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:343)
        at org.tensorflow.lite.Interpreter.run(Interpreter.java:304)
        at com.ncnn.demo.tflite.TfLiteFaceRecognitionModel.recognizeImage(TfLiteFaceRecognitionModel.java:77)
        at com.ncnn.demo.loopTask.FaceComparisonLoopTask.run(FaceComparisonLoopTask.java:103)
        at java.lang.Thread.run(Thread.java:764)

**Comment by ymodak** [comment]
Can you please provide more information like what device you are trying this on? What TF version you are using?
