### ISSUE TITLE
Failed to load the native TensorFlow runtime

### ISSUE THREAD

**Issue by Debasish2003** [tensorflow/tensorflow#41598]
Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.12.0 -- An enhanced Interactive Python.

runcell(0, 'C:/Debasish/personal/DS_city/Practice with Dataset_Mine/NLP Code/untitled0.py')
Traceback (most recent call last):

  File "C:\Users\edebago\Anaconda3\Anaconda_new3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *

  File "C:\Users\edebago\Anaconda3\Anaconda_new3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()

  File "C:\Users\edebago\Anaconda3\Anaconda_new3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)

  File "C:\Users\edebago\Anaconda3\Anaconda_new3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)

  File "C:\Users\edebago\Anaconda3\Anaconda_new3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)

ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Debasish\personal\DS_city\Practice with Dataset_Mine\NLP Code\untitled0.py", line 8, in <module>
    import tensorflow as tf

  File "C:\Users\edebago\Anaconda3\Anaconda_new3\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util

  File "C:\Users\edebago\Anaconda3\Anaconda_new3\lib\site-packages\tensorflow\python\__init__.py", line 50, in <module>
    from tensorflow.python import pywrap_tensorflow

  File "C:\Users\edebago\Anaconda3\Anaconda_new3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 69, in <module>
    raise ImportError(msg)

ImportError: Traceback (most recent call last):
  File "C:\Users\edebago\Anaconda3\Anaconda_new3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\edebago\Anaconda3\Anaconda_new3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\edebago\Anaconda3\Anaconda_new3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\edebago\Anaconda3\Anaconda_new3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\edebago\Anaconda3\Anaconda_new3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by Saduf2019** [comment]
@Debasish2003 
Please refer to [this link](https://github.com/tensorflow/tensorflow/issues/36683#issuecomment-585097726) and let us know.
