### ISSUE TITLE
ImportError: cannot import name 'tensorflow' from 'opt_einsum.backends' 

### ISSUE THREAD

**Issue by surabhijain123** [tensorflow/tensorflow#41606]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
- TensorFlow version:2.1
- Python version:3.7.7
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.1 cuda
- GPU model and memory: GTX 1650

**Describe the problem**
Another environment with tensorflow cpu has setup with no issues. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
SET PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin;%PATH%
SET PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\extras\CUPTI\lib64;%PATH%
SET PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include;%PATH%
SET PATH=C:\tools\cuda\bin;%PATH%
I have set these variables too

**Any other info / logs**
>>> import tensorflow
2020-07-22 00:42:00.297809: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Lenovo\anaconda3\envs\tf-gpu-cuda10\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\Lenovo\anaconda3\envs\tf-gpu-cuda10\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Lenovo\anaconda3\envs\tf-gpu-cuda10\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\Lenovo\anaconda3\envs\tf-gpu-cuda10\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\Lenovo\anaconda3\envs\tf-gpu-cuda10\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Lenovo\anaconda3\envs\tf-gpu-cuda10\lib\site-packages\tensorflow_core\python\__init__.py", line 85, in <module>
    from tensorflow.python.ops.standard_ops import *
  File "C:\Users\Lenovo\anaconda3\envs\tf-gpu-cuda10\lib\site-packages\tensorflow_core\python\ops\standard_ops.py", line 48, in <module>
    from tensorflow.python.ops.special_math_ops import *
  File "C:\Users\Lenovo\anaconda3\envs\tf-gpu-cuda10\lib\site-packages\tensorflow_core\python\ops\special_math_ops.py", line 30, in <module>
    import opt_einsum
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python37\site-packages\opt_einsum\__init__.py", line 9, in <module>
    from .contract import contract, contract_path, contract_expression
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python37\site-packages\opt_einsum\contract.py", line 10, in <module>
    from . import backends, blas, helpers, parser, paths, sharing
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python37\site-packages\opt_einsum\backends\__init__.py", line 7, in <module>
    from .dispatch import (get_func, has_einsum, has_tensordot, build_expression, evaluate_constants, has_backend)
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python37\site-packages\opt_einsum\backends\dispatch.py", line 13, in <module>
    from . import tensorflow as _tensorflow
ImportError: cannot import name 'tensorflow' from 'opt_einsum.backends' (C:\Users\Lenovo\AppData\Roaming\Python\Python37\site-packages\opt_einsum\backends\__init__.py)

**Comment by amahendrakar** [comment]
@surabhijain123,
Installation issues within the Anaconda environment are tracked in the Anaconda repo.

Could you please submit a new issue using [this link](https://github.com/ContinuumIO/anaconda-issues/issues/new) and fill in the template, so that the issue can be tracked there. Thanks!
