### ISSUE TITLE
[ TF 2.0 ] tf.function throws error

### ISSUE THREAD

**Issue by ayushch3** [tensorflow/tensorflow#41642]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): pip install tensorflow==2.0.0
- Python version:3.7.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I ported n gram computation for truecasing to tf-2.0 and it works fine when I run the function but fails when I try to wrap the function with tf.function

**Describe the expected behavior**

The tf.function wrapper is needed so that the model can be exported to run with tf.serving. The code functions correctly when its provided an input. But the code fails with the error attached when tf.function wrapper is added

**Standalone code to reproduce the issue**
```
    @tf.function(input_signature=[tf.TensorSpec(shape=None, dtype=tf.string, name="input_text")])
    def get_true_case(self, tokens_tensor):
        cap_first_token = tf.reshape(tokens_tensor[0], [1])

        trueCasedTokens = cap_first_token
        tokens_tensor = tf.slice(tokens_tensor, [1], [-1])

        condition = lambda tokens_tensor, trueCasedTokens: tf.greater(tf.size(tokens_tensor), 0)

        def body(tokens_tensor, trueCasedTokens):
            cur_tokens_tensor = tf.concat([trueCasedTokens[-1:], tokens_tensor], 0)
            curToken = tf.get_static_value(tf.slice(cur_tokens_tensor, [1], [1]))[0]
            curToken = tf.get_static_value(tf.strings.lower(curToken))

            prevToken = tf.slice(cur_tokens_tensor, [0], [1])
            if tf.get_static_value(tf.greater(tf.size(cur_tokens_tensor), [3]))[0]:
                nextToken = tf.slice(cur_tokens_tensor, [2], [1])
            else:
                nextToken = None

            wordCasingLookup = tf.reshape(self.get_alternative_tokens(tf.constant(curToken)), [-1])
            if tf.get_static_value(tf.equal(tf.size(wordCasingLookup), [0]))[0]:
                trueCasedTokens = tf.concat([trueCasedTokens, tf.constant(curToken)], 0)
            if tf.get_static_value(tf.equal(tf.size(wordCasingLookup), [1]))[0]:
                trueCasedTokens = tf.concat([trueCasedTokens, wordCasingLookup], 0)
            else:
                scores = tf.map_fn(lambda x: self.get_score(prevToken, x, nextToken),
                                   wordCasingLookup, dtype=tf.float32)
                maxElementIndx = tf.get_static_value(tf.argmax(scores))[0]
                trueVariant = tf.slice(wordCasingLookup, [maxElementIndx], [1])
                trueCasedTokens = tf.concat([trueCasedTokens, trueVariant], 0)

            tokens_tensor = tf.slice(tokens_tensor, [1], [-1])
            return tokens_tensor, trueCasedTokens

        res = tf.while_loop(condition,
                            lambda tokens_tensor, trueCasedTokens: body(tokens_tensor, trueCasedTokens),
                            [tokens_tensor, trueCasedTokens])                    
        res = res[1]
        res = tf.gather(res, tf.where(res != b''))

        return res

```
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
```
  File "/Users/ayushc/transcript-post-processor/truecaser.py", line 67, in truecase_tokenize
    res = tf_model.get_true_case(tokens_tensor)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 503, in _call
    self._initialize(args, kwds, add_initializers_to=initializer_map)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 408, in _initialize
    *args, **kwds))
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1848, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2150, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2041, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 915, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 358, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2658, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 905, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in converted code:

    ./truecaser/truecaser_tf.py:160 body  *
        curToken = tf.get_static_value(tf.slice(cur_tokens_tensor, [1], [1]))[0]
    /usr/local/lib/python3.7/site-packages/tensorflow_core/python/ops/control_flow_ops.py:2478 while_loop_v2
        return_same_structure=True)
    /var/folders/4j/sdgl7s9j3w51c50b5wy4v_p00000gn/T/tmpw4oa0q3i.py:21 body
        curToken = ag__.converted_call(tf.get_static_value, body_scope.callopts, (ag__.converted_call(tf.slice, body_scope.callopts, (cur_tokens_tensor, [1], [1]), None, body_scope),), None, body_scope)[0]

    TypeError: 'NoneType' object is not subscriptable
```

**Comment by ravikyram** [comment]
@ayushch3 

I think code is incomplete.Request you to provide colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by ayushch3** [comment]
@ravikyram I added all the relevant code in this git: https://github.com/ayushch3/truecaser_tf

If you try to run export_truecaser file, you will see all the relevant errors. The code basically needs to export the files that can be used directly in tf-serving

**Comment by ravikyram** [comment]
@ayushch3 

I think en_`truecasing_model.ob file is missing.Please, share the file to reproduce the issue.
This issue is more suitable for TensorFlow Serving repo. Please post it on Serving repo from [here.](https://github.com/tensorflow/serving/issues) Thanks!

**Comment by ayushch3** [comment]
@ravikyram the link to the truecasing_model.obj file is in readme: https://drive.google.com/file/d/1DpmsDYm-gzcwXCJT4sMCUXmtHGSxKiIR/view?usp=sharing

Sharing it again just in case. I don't think its an issue with the serving itself, I haven't been able to export the model in the first place using tf.function wrapper. I have looked at bunch of configurations for the signature definition for tf.function, but none of them seem to work. The file that needs to run to export the model is export_truecaser.py from the git file. I'd appreciate if you can give any inputs on what's causing that behavior

**Comment by ravikyram** [comment]
@ayushch3 

I tried in colab with TF 2.2 .Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/7d16a2073ea5ba72a49054084c91411a/untitled178.ipynb).Thanks!

**Comment by ayushch3** [comment]
@ravikyram I added the requirements file so that our environments can match: https://github.com/ayushch3/truecaser_tf/blob/master/requirements.txt

I am able to reproduce the same issue with these version of libraries as stated above. Let me know if you have any other issues running the code

**Comment by ayushch3** [comment]
Also adding a try/except block in the body function within get_true_case leads to this error:

```
'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "export_model_truecaser.py", line 26, in <module>
    tf.TensorSpec(shape=(None), dtype=tf.string, name="input_text"))
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 959, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 865, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 506, in _initialize
    *args, **kwds))
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2446, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2777, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2667, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 441, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3299, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 968, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    ./truecaser/truecaser_tf.py:186 get_true_case  *
        res = tf.while_loop(condition,
    /usr/local/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py:574 new_func  **
        return func(*args, **kwargs)
    /usr/local/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py:2491 while_loop_v2
        return_same_structure=True)
    /usr/local/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py:2688 while_loop
        back_prop=back_prop)
    /usr/local/lib/python3.7/site-packages/tensorflow/python/ops/while_v2.py:196 while_loop
        add_control_dependencies=add_control_dependencies)
    /usr/local/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py:981 func_graph_from_py_func
        func_outputs = python_func(*func_args, **func_kwargs)
    /usr/local/lib/python3.7/site-packages/tensorflow/python/ops/while_v2.py:180 wrapped_body
        expand_composites=True)
    /usr/local/lib/python3.7/site-packages/tensorflow/python/util/nest.py:385 assert_same_structure
        % (str(e), str1, str2))

    ValueError: The two structures don't have the same nested structure.
    
    First structure: type=list str=[None]
    
    Second structure: type=list str=[<tf.Tensor 'Slice:0' shape=(None,) dtype=string>, <tf.Tensor 'Reshape:0' shape=(1,) dtype=string>]
    
    More specifically: The two structures don't have the same number of elements. First structure: type=list str=[None]. Second structure: type=list str=[<tf.Tensor 'Slice:0' shape=(None,) dtype=string>, <tf.Tensor 'Reshape:0' shape=(1,) dtype=string>]
    Entire first structure:
    [.]
    Entire second structure:
    [., .]
```

**Comment by ayushch3** [comment]
@gowthamkpr any update on this issue what's causing this error when using the tf.function wrapper

**Comment by mdanatg** [comment]
Hi, I'm trying to run the reproduction code but keep running into various errors. At first the cell told me about a missing en_truecasing_model.obj, then after I found the link and downloaded it, I'm getting this error:

```
Traceback (most recent call last):
  File "/content/truecaser_tf/export_truecaser.py", line 20, in <module>
    wordCasingLookup, uniDist, backwardBiDist, forwardBiDist, trigramDist = load_truecasing_model(truecaser_weights)
  File "/content/truecaser_tf/export_truecaser.py", line 11, in load_truecasing_model
    uni_dist = pickle.load(bin_file)
ValueError: could not convert string to int
```

Please place the code to reproduce the bug into a single colab notebook, that can run independently, without needing to download any other files. For example, I doubt we need the saved model part and can just test the model with some random inputs.

**Comment by mdanatg** [comment]
I finally got it to work, it seems that it takes a while for the file to upload in colab. So I'm running the code in TF 2.3 and it runs without error. For reference, this is the code I ran:

```
import tensorflow as tf


class NGramTF(tf.Module):
    def __init__(self):
        self.oov_score = 0
        self.pseudo_count = 5.0
        pass

    def fit_tf_lookup_table(self, dist):
        keys_tensor = tf.constant(list(dist.keys()))
        vals_tensor = tf.constant(list(dist.values()))
        initializer = tf.lookup.KeyValueTensorInitializer(keys_tensor, vals_tensor)
        table = tf.lookup.StaticHashTable(initializer, self.oov_score)
        return table

    def fit_word_casing(self, wordCasingLookup):
        indices = []
        values = []
        tokens = []
        for idx, (token, items) in enumerate(wordCasingLookup.items()):
            tokens.append(token)
            for j, item in enumerate(items):
                indices.append([idx, j])
                values.append(item)
        word_casing_lookup_shape = [len(tokens), max([len(item) for item in wordCasingLookup.values()])]
        word_casing_lookup_tf = tf.SparseTensor(indices=indices, values=values, dense_shape=word_casing_lookup_shape)
        word_casing_indices = tf.range(0, len(tokens))
        dense_word_casing_lookup_tf = tf.sparse.to_dense(word_casing_lookup_tf, default_value='')

        initializer = tf.lookup.KeyValueTensorInitializer(tf.constant(tokens), word_casing_indices)

        # TODO: this does ot work
        table = tf.lookup.StaticHashTable(initializer, -1)
        return table, dense_word_casing_lookup_tf

    def fit(self, wordCasingLookup, uniDist, backwardBiDist, forwardBiDist, trigramDist):
        self.word_casing, self.word_casing_lookup = self.fit_word_casing(wordCasingLookup)
        self.tf_uni_dist = self.fit_tf_lookup_table(uniDist)
        self.backwardBiDist = self.fit_tf_lookup_table(backwardBiDist)
        self.forwardBiDist = self.fit_tf_lookup_table(forwardBiDist)
        self.trigramDist = self.fit_tf_lookup_table(trigramDist)

    def get_unigram_score(self, possible_token):

        input_tensor = tf.constant(possible_token)

        nominator = tf.dtypes.cast(self.tf_uni_dist.lookup(input_tensor), tf.float32) + self.pseudo_count

        input_tensor_lower = tf.strings.lower(input_tensor)
        idx = self.word_casing.lookup(input_tensor_lower)
        alternative_tokens = self.word_casing_lookup[idx]
        alternative_tokens = tf.gather(alternative_tokens, tf.where(alternative_tokens != b''))

        # t_idx = self.word_casing_lookup.indices[idx]
        # alternative_tokens = tf.gather(self.word_casing_lookup.values, t_idx)

        denominator = self.tf_uni_dist.lookup(alternative_tokens)
        denominator_sum = tf.math.reduce_sum(tf.dtypes.cast(denominator, tf.float32) + self.pseudo_count)
        unigram_score = nominator / denominator_sum

        return unigram_score

    def get_alternative_tokens(self, possible_token_tensor):
        idx = self.word_casing.lookup(possible_token_tensor)

        def f1(): return tf.constant([], dtype=tf.dtypes.string)

        def f2(): return tf.gather(self.word_casing_lookup[idx[0]], tf.where(self.word_casing_lookup[idx[0]] != b''))

        alternative_tokens = tf.cond(tf.equal(idx, [-1]), f1, f2)
        return alternative_tokens

    def compute_unigram_score(self, possible_token_tensor, alternative_tokens):
        nominator = tf.dtypes.cast(self.tf_uni_dist.lookup(possible_token_tensor), tf.float32) + self.pseudo_count
        denominator = self.tf_uni_dist.lookup(alternative_tokens)
        denominator_sum = tf.math.reduce_sum(tf.dtypes.cast(denominator, tf.float32) + self.pseudo_count)
        score = nominator / denominator_sum
        return score

    def compute_bigram_backward_score(self, possible_token_tensor, prev_token_tensor, alternative_tokens):
        x = prev_token_tensor + tf.constant('_') + possible_token_tensor
        nominator = tf.dtypes.cast(self.backwardBiDist.lookup(x), tf.float32) + self.pseudo_count
        alternative_tokens_m = prev_token_tensor + tf.constant('_') + alternative_tokens
        denominator = self.backwardBiDist.lookup(alternative_tokens_m)
        denominator_sum = tf.math.reduce_sum(tf.dtypes.cast(denominator, tf.float32) + self.pseudo_count)
        score = nominator / denominator_sum
        return score

    def compute_bigram_forward_score(self, possible_token_tensor, next_token_tensor, alternative_tokens):
        x = possible_token_tensor + tf.constant('_') + tf.strings.lower(next_token_tensor)
        nominator = tf.dtypes.cast(self.forwardBiDist.lookup(x), tf.float32) + self.pseudo_count
        alternative_tokens_m = alternative_tokens + tf.constant('_') + tf.strings.lower(next_token_tensor)
        denominator = self.forwardBiDist.lookup(alternative_tokens_m)
        denominator_sum = tf.math.reduce_sum(tf.dtypes.cast(denominator, tf.float32) + self.pseudo_count)
        score = nominator / denominator_sum
        return score

    def compute_trigram_score(self, possible_token_tensor, prev_token_tensor, next_token_tensor, alternative_tokens):
        x = prev_token_tensor + tf.constant('_') + possible_token_tensor + tf.constant('_') + tf.strings.lower(
            next_token_tensor)
        nominator = tf.dtypes.cast(self.trigramDist.lookup(x), tf.float32) + self.pseudo_count
        alternative_tokens_m = prev_token_tensor + tf.constant('_') + alternative_tokens + tf.constant(
            '_') + tf.strings.lower(next_token_tensor)
        denominator = self.trigramDist.lookup(alternative_tokens_m)
        denominator_sum = tf.math.reduce_sum(tf.dtypes.cast(denominator, tf.float32) + self.pseudo_count)
        score = nominator / denominator_sum
        return score

    def get_score(self, prev_token, possible_token, next_token):

        possible_token_l = tf.strings.lower(possible_token)
        alternative_tokens = self.get_alternative_tokens(possible_token_l)

        unigram_score = self.compute_unigram_score(possible_token, alternative_tokens)
        result = tf.math.log(unigram_score)

        if prev_token is not None:
            bigram_backward_score = self.compute_bigram_backward_score(possible_token, prev_token, alternative_tokens)
            result += tf.math.log(bigram_backward_score)

        if next_token is not None:
            bigram_forward_score = self.compute_bigram_forward_score(possible_token, next_token, alternative_tokens)
            result += tf.math.log(bigram_forward_score)

        if prev_token is not None and next_token is not None:
            trigram_score = self.compute_trigram_score(possible_token, prev_token, next_token, alternative_tokens)
            result += tf.math.log(trigram_score)
        return result

    def capitalize_str(self, token_tensor):
        token_tensor = tf.reshape(token_tensor, [1])
        char_tensor = tf.compat.v1.string_split(token_tensor, delimiter='').values

        first_char = char_tensor[0]
        first_char_cap = tf.strings.upper(first_char)

        cap_char_tensor = tf.concat([tf.reshape(first_char_cap, [1]), char_tensor[1:]], 0)
        cap_tensor = tf.strings.reduce_join(cap_char_tensor)
        return tf.reshape(cap_tensor, [1])

    @tf.function
    def get_true_case(self, tokens_tensor):
        cap_first_token = self.capitalize_str(tokens_tensor[0:1])
        cur_token0 = tokens_tensor[0:1]

        true_cased_tokens0 = cap_first_token
        tokens_tensor0 = tokens_tensor[1:-1]
        i0 = tf.constant(1)
        condition = lambda i, true_cased_tokens, tokens_tensor: tf.less_equal(i, tf.size(tokens_tensor0) + 1)

        def body(i, true_cased_tokens, tokens_tensor):
            cur_token = tokens_tensor[i: i + 1]
            prev_token = true_cased_tokens[-1:]

            def f1(): return tokens_tensor[i + 1: i + 2]

            def f2(): return tf.constant([b''])

            next_token = tf.cond(tf.less(i, tf.size(tokens_tensor)),
                                 f1,
                                 f2)
            ind = self.word_casing.lookup(cur_token)
            word_casing_lookup = self.get_alternative_tokens(cur_token)

            def f_true_cased_0():
                return cur_token

            def f_true_cased_1():
                return word_casing_lookup[0]

            cur_token_transformed = tf.cond(tf.equal(tf.size(word_casing_lookup), 0),
                                            f_true_cased_0,
                                            f_true_cased_1)

            def f_return_cur():
                return cur_token_transformed

            def f_find_best():
                scores = tf.map_fn(lambda x: self.get_score(prev_token, x, next_token),
                                   word_casing_lookup, dtype=tf.float32)
                max_el_ind = tf.argmax(scores)
                truecased_token = word_casing_lookup[max_el_ind[0]: max_el_ind[0] + 1]
                return truecased_token[0]

            cur_token_transformed = tf.cond(tf.greater(tf.size(word_casing_lookup), 1), f_find_best, f_return_cur)

            true_cased_tokens = tf.concat([true_cased_tokens, cur_token_transformed], 0)

            return [tf.add(i, 1), true_cased_tokens, tokens_tensor]

        res = tf.while_loop(condition,
                            body,
                            [i0, true_cased_tokens0, tokens_tensor],
                            shape_invariants=[tf.TensorShape([]), tf.TensorShape([None]), tf.TensorShape([None])])
        return res[1]

import pickle

def load_truecasing_model(model_filename):
    with open(model_filename, 'rb') as bin_file:
        uni_dist = pickle.load(bin_file)
        backward_bi_dist = pickle.load(bin_file)
        forward_bi_dist = pickle.load(bin_file)
        trigram_dist = pickle.load(bin_file)
        word_casing_lookup = pickle.load(bin_file)
        return word_casing_lookup, uni_dist, backward_bi_dist, forward_bi_dist, trigram_dist

truecaser_weights = 'en_truecasing_model.obj'
wordCasingLookup, uniDist, backwardBiDist, forwardBiDist, trigramDist = load_truecasing_model(truecaser_weights)

model = NGramTF()
export_path = './truecaser_serving/1/'
model.fit(wordCasingLookup, uniDist, backwardBiDist, forwardBiDist, trigramDist)

signature_def = model.get_true_case.get_concrete_function(tf.TensorSpec(shape=(None), dtype=tf.string, name="input_text"))
tf.saved_model.save(model,export_path,signatures={'serving_default': signature_def})
```

@ayushch3 , could you verify that this works in 2.3 on your end as well?

**Comment by mdanatg** [comment]
On a related note, you can use AutoGraph in tf.function to write the control flow in a more Pyhtonic form. I rewrote the function as an example. I only tested that it works without error, please verify it on actual data before using it:

```
    @tf.function
    def get_true_case(self, tokens_tensor):
        cap_first_token = self.capitalize_str(tokens_tensor[0:1])
        true_cased_tokens = cap_first_token
        tokens_tensor = tokens_tensor[1:-1]

        i = tf.constant(1)
        while i <= (tf.size(tokens_tensor) + 1):
            tf.autograph.experimental.set_loop_options(
                shape_invariants=(
                    (true_cased_tokens, tf.TensorShape([None])),
                )
            )

            cur_token = tokens_tensor[i: i + 1]
            prev_token = true_cased_tokens[-1:]

            if i < tf.size(tokens_tensor):
              next_token = tokens_tensor[i + 1: i + 2]
            else:
              next_token = tf.constant([b''])

            ind = self.word_casing.lookup(cur_token)
            word_casing_lookup = self.get_alternative_tokens(cur_token)

            if tf.size(word_casing_lookup) == 0:
              cur_token_transformed = cur_token
            else:
              cur_token_transformed = word_casing_lookup[0]

            if tf.size(word_casing_lookup) > 1:
                scores = tf.map_fn(lambda x: self.get_score(prev_token, x, next_token),
                                   word_casing_lookup, dtype=tf.float32)
                max_el_ind = tf.argmax(scores)
                truecased_token = word_casing_lookup[max_el_ind[0]: max_el_ind[0] + 1]
                cur_token_transformed = truecased_token[0]

            true_cased_tokens = tf.concat([true_cased_tokens, cur_token_transformed], 0)
            i += 1

        return true_cased_tokens
```
