### ISSUE TITLE
I cant install/import tensorflow

### ISSUE THREAD

**Issue by 000Nobody** [tensorflow/tensorflow#41702]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 1904
- TensorFlow version: Trying to install version 2.2
- Python version: 3.8.2
- Installed using virtualenv? pip? conda?: trying to install with pip
- CUDA/cuDNN version: 11.0
- GPU model and memory: Its a laptop, that has both an Intel(R) UHD Graphics 630 and a Nvidia GTX 1060

**Describe the problem**
I get an error when trying to pip install tensorflow, however, I assumed that it was because I am using python 3.8, so I tried doing a special install with: `python -m pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.12.0-py3-none-any.whl` and that installed it, however when running a script that simply imports tensorflow, I get the error: `No module named '_pywrap_tensorflow_internal'` I know that it is tensorflow 1.12, but when I uninstalled and tried to do a special install of 2.2, it didn't work. Sorry if I'm just being stupid here but I cant figure it out.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
ran `python -m pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.12.0-py3-none-any.whl` in the cmd and when I try to import tensorflow I get the error `No module named '_pywrap_tensorflow_internal'`.

**Any other info / logs**
The entire traceback:
```
Traceback (most recent call last):
  File "C:\Users\LORI\AppData\Local\Programs\Python\Python38-32\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow_internal', [dirname(__file__)])
  File "C:\Users\LORI\AppData\Local\Programs\Python\Python38-32\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\LORI\AppData\Local\Programs\Python\Python38-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\LORI\AppData\Local\Programs\Python\Python38-32\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\LORI\AppData\Local\Programs\Python\Python38-32\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    import _pywrap_tensorflow_internal
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\LORI\Desktop\Python Projects\Tensor Flow Project\main.py", line 1, in <module>
    import tensorflow
  File "C:\Users\LORI\AppData\Local\Programs\Python\Python38-32\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\LORI\AppData\Local\Programs\Python\Python38-32\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\LORI\AppData\Local\Programs\Python\Python38-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\LORI\AppData\Local\Programs\Python\Python38-32\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow_internal', [dirname(__file__)])
  File "C:\Users\LORI\AppData\Local\Programs\Python\Python38-32\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\LORI\AppData\Local\Programs\Python\Python38-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\LORI\AppData\Local\Programs\Python\Python38-32\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\LORI\AppData\Local\Programs\Python\Python38-32\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    import _pywrap_tensorflow_internal
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'
```

**Comment by mihaimaruseac** [comment]
Something does not make sense. Why would you install a mac pip on windows?

**Comment by 000Nobody** [comment]
Sorry, when writing this issue I had pasted the wrong command, I didn't actually install the mac one, I had installed the windows one. Also if it helps, when I tried to also install TensorFlow 2.2 through `https://storage.googleapis.com/tensorflow/windows/gpu/tensorflow_gpu-2.2.0-cp38-cp38-win_amd64.whl` It gives the error that it is not a supported wheel on this platform. It also did the same thing when I tried the CPU only version

**Comment by mihaimaruseac** [comment]
What is the output of

```
pip list
pip --version
python -vv
python -w
```

In general you don't need to download the pip from `storage.googleapis.com`, a `pip install tensorflow` should be able to get it, assuming your Python is on 64 bits, your pip is up to date, you have the needed MSVC redistributable installed and that Python is installed from the Python website, not from Microsoft Marketplace (apparently, there is a bug with that)
