### ISSUE TITLE
quantize deeplab model trained on PASCAL VOC，TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'

### ISSUE THREAD

**Issue by shakey-cuimiao** [tensorflow/tensorflow#41767]
When I change quantize_delay_step=-1 to quantize_delay_step=0, I run the following command, 
python deeplab/train.py \
    --logtostderr \
    --training_number_of_steps=3000 \
    --train_split="train" \
    --model_variant="mobilenet_v2" \
    --output_stride=16 \
    --train_crop_size="513,513" \
    --train_batch_size=8 \
    --base_learning_rate=3e-5 \
    --dataset="pascal_voc_seg" \
    --quantize_delay_step=0 \
I get an error：
Traceback (most recent call last):
  File "train.py", line 464, in <module>
    tf.app.run()
  File "/home/sherry/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/sherry/.local/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/sherry/.local/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "train.py", line 391, in main
    quant_delay=FLAGS.quantize_delay_step)
  File "/home/sherry/.local/lib/python3.6/site-packages/tensorflow/contrib/quantize/python/quantize_graph.py", line 122, in create_training_graph
    freeze_bn_delay=freeze_bn_delay)
  File "/home/sherry/.local/lib/python3.6/site-packages/tensorflow/contrib/quantize/python/quantize_graph.py", line 73, in _create_graph
    is_training=is_training)
  File "/home/sherry/.local/lib/python3.6/site-packages/tensorflow/contrib/quantize/python/fold_batch_norms.py", line 53, in FoldBatchNorms
    graph, is_training, freeze_batch_norm_delay=freeze_batch_norm_delay)
  File "/home/sherry/.local/lib/python3.6/site-packages/tensorflow/contrib/quantize/python/fold_batch_norms.py", line 98, in _FoldFusedBatchNorms
    freeze_batch_norm_delay=freeze_batch_norm_delay))
  File "/home/sherry/.local/lib/python3.6/site-packages/tensorflow/contrib/quantize/python/fold_batch_norms.py", line 384, in _ComputeBatchNormCorrections
    match.moving_variance_tensor + match.batch_epsilon)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'

**Comment by amahendrakar** [comment]
@shakey-cuimiao,
Could you please provide the TensorFlow version you are using and the complete code or the sequence of commands to reproduce the issue reported here. Thanks!

**Comment by shakey-cuimiao** [comment]
@amahendrakar
Tensorflow Version：1.14.0
I required to quantize DeepLab model and convert it to TFLite。The main steps: Quantization-aware training。
When I change quantize_delay_step=-1 to quantize_delay_step=0, I run the following command：
python train.py
--logtostderr
--training_number_of_steps=3000
--train_split="train"
--model_variant="mobilenet_v2"
--output_stride=16
--train_crop_size="513,513"
--train_batch_size=8
--base_learning_rate=3e-5
--dataset="pascal_voc_seg"
--quantize_delay_step=0

**Comment by amahendrakar** [comment]
@shakey-cuimiao,
TensorFlow v1.14 is not actively supported. Please update TensorFlow to 2.x or v1.15 and check if you are facing the same issue. 

Also, please take a look at [this similar](https://github.com/tensorflow/tensorflow/issues/20867#issuecomment-422246723) issue and let us know if it works. Thanks!

**Comment by balazsbanto** [comment]
I was able to solve this issue by upgrading tensorflow version from 1.15 to 1.15.3.

**Comment by amahendrakar** [comment]
@balazsbanto,
Thank you for the update. Marking this issue as close since it is resolved.
