### ISSUE TITLE
RuntimeError: external/org_tensorflow/tensorflow/lite/core/subgraph.cc:1044 required_bytes != bytes (602112 != 150528)

### ISSUE THREAD

**Issue by LINYOUWEI0804** [tensorflow/tensorflow#41799]
Training and conversion model equipment：ubuntu18.04
tf :2.2.0
tb-nightly               1.14.0a20190603
tf-estimator-nightly     1.14.0.dev2019060501

I use Dev Board to predict：
edgetpu  ： 2.14.0       
tflite-runtime： 2.1.0.post1  
----------------------------------------------
My training and conversion model code:
[2.2.0.ipynb.zip](https://github.com/tensorflow/tensorflow/files/4986035/2.2.0.ipynb.zip)
hdf5 model:
[0.03-0.98.hdf5.zip](https://github.com/tensorflow/tensorflow/files/4986041/0.03-0.98.hdf5.zip)
tflite model:
[st2_io.tflite.zip](https://github.com/tensorflow/tensorflow/files/4986048/st2_io.tflite.zip)

Prediction program running on Dev Board：
[classify_image.py.zip](https://github.com/tensorflow/tensorflow/files/4986066/classify_image.py.zip)
edgetpu model(Model used for prediction）:
[st2_io_edgetpu.tflite.zip](https://github.com/tensorflow/tensorflow/files/4986053/st2_io_edgetpu.tflite.zip)
label:
[sparrow (1).txt](https://github.com/tensorflow/tensorflow/files/4986071/sparrow.1.txt)
Image:
[edgetest.zip](https://github.com/tensorflow/tensorflow/files/4986075/edgetest.zip)
-------------------------------------------------------
I got this error after executing classify_image.py on Dev Board：

mendel@orange-eft:~/sparrow$ python3 classify_image.py --model st2_io_edgetpu.tflite 
Traceback (most recent call last):
  File "classify_image.py", line 27, in <module>
    main()
  File "classify_image.py", line 21, in main
    for result in engine.classify_with_image(img, top_k=3):
  File "/usr/lib/python3/dist-packages/edgetpu/classification/engine.py", line 99, in classify_with_image
    return self.classify_with_input_tensor(input_tensor, threshold, top_k)
  File "/usr/lib/python3/dist-packages/edgetpu/classification/engine.py", line 123, in classify_with_input_tensor
    input_tensor)
  File "/usr/lib/python3/dist-packages/edgetpu/basic/basic_engine.py", line 136, in run_inference
    result = self._engine.RunInference(input)
  File "/usr/lib/python3/dist-packages/edgetpu/swig/edgetpu_cpp_wrapper.py", line 111, in RunInference
    return _edgetpu_cpp_wrapper.BasicEnginePythonWrapper_RunInference(self, input)
RuntimeError: external/org_tensorflow/tensorflow/lite/core/subgraph.cc:1044 required_bytes != bytes (602112 != 150528)

**Comment by tyqin97** [comment]
is there any solution yet? I am facing the same problem here

**Comment by maettuki** [comment]
is there any solution yet? I am facing the same problem here
