### ISSUE TITLE
incompatible with expected float_ref.

### ISSUE THREAD

**Issue by ZhouKai90** [tensorflow/tensorflow#41805]
Traceback (most recent call last):
  File "convert_TFLite.py", line 90, in <module>
    convert_from_savedModel(savedModelDir, TFLiteFile, quan=True, integerOnly=True)
  File "convert_TFLite.py", line 50, in convert_from_savedModel
    TFLiteModel = converter.convert()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/lite/python/lite.py", line 459, in convert
    self._funcs[0], lower_control_flow=False))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/convert_to_constants.py", line 707, in convert_variables_to_constants_v2_as_graph
    frozen_func = _construct_concrete_function(func, graph_def, converted_inputs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/convert_to_constants.py", line 406, in _construct_concrete_function
    new_output_names)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/eager/wrap_function.py", line 633, in function_from_graph_def
    wrapped_import = wrap_function(_imports_graph_def, [])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/eager/wrap_function.py", line 611, in wrap_function
    collections={}),
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/eager/wrap_function.py", line 86, in __call__
    return self.call_with_variable_creator_scope(self._fn)(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/eager/wrap_function.py", line 92, in wrapped
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/eager/wrap_function.py", line 631, in _imports_graph_def
    importer.import_graph_def(graph_def, name="")
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 501, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: Input 0 of node conv21/pointwise/BatchNorm/cond/Assign/Switch was passed float from conv21/pointwise/BatchNorm/moving_mean:0 incompatible with expected float_ref.

when I use "tf.lite.TFLiteConverter.from_saved_model()" to convert checkpoint to tflite，I got above err about BatchNorm, please help me, ths.

_Originally posted by @ZhouKai90 in https://github.com/tensorflow/tensorflow/issues/3628#issuecomment-663382551_

**Comment by abattery** [comment]
Switch is not supported by TFLite. Please use the v2 control flow ops while creating a TF graph. https://www.tensorflow.org/api_docs/python/tf/compat/v1/enable_control_flow_v2

**Comment by Saduf2019** [comment]
@ZhouKai90 
Can you please provide with simple stand alone code and tf version for us to replicate the issue or if possible share colab gist with the error.
