### ISSUE TITLE
TPU Error: Unable to destroy remote tensor handles. If you are running a tf.function, it usually indicates some op in the graph gets an error: Socket closed

### ISSUE THREAD

**Issue by caffeine-lab** [tensorflow/tensorflow#41817]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
https://www.kaggle.com/ratthachat/flickr-image-captioning-tpu-tf2-glove

- TensorFlow installed from (source or binary): installed source
- TensorFlow version (use command below): 2.2
- Python version: 3.7

**Describe the current behavior**

I was running the provided code from Kaggle on a Google cloud TPU.
Hardware: v3-8

It was training fine till when I had 500000 Images. but the moment I increase the amount of data to 1 million. at almost the end of 1st epoch, I am getting the following error. I am new to TPUs so any help will be appreciated.

Traceback (most recent call last):
  File "flickr-image-captioning-tpu-tf2-glove.py", line 178, in <module>
    for (batch, inputs) in tqdm_notebook(enumerate(train_dist_dataset)): # by .repeat() this will indefinitely run
  File "/usr/local/lib/python3.7/dist-packages/tqdm/notebook.py", line 218, in __iter__
    for obj in super(tqdm_notebook, self).__iter__(*args, **kwargs):
  File "/usr/local/lib/python3.7/dist-packages/tqdm/std.py", line 1129, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/input_lib.py", line 296, in __next__
    return self.get_next()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/input_lib.py", line 328, in get_next
    global_has_value, replicas = _get_next_as_optional(self, self._strategy)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/input_lib.py", line 192, in _get_next_as_optional
    iterator._iterators[i].get_next_as_list(new_name))  # pylint: disable=protected-access
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/input_lib.py", line 1150, in get_next_as_list
    strict=True,
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1204, in cond
    if pred:
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 884, in __bool__
    return bool(self._numpy())
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 929, in _numpy
    six.raise_from(core._status_to_exception(e.code, e.message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnavailableError: Socket closed
Additional GRPC error information:
{"created":"@1595426699.706157313","description":"Error received from peer ipv4:10.255.26.210:8470","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}
2020-07-22 14:05:01.237755: W tensorflow/core/distributed_runtime/eager/remote_tensor_handle_data.cc:76] Unable to destroy remote tensor handles. If you are running a tf.function, it usually indicates some op in the graph gets an error: Socket closed
Additional GRPC error information:
{"created":"@1595426699.706157313","description":"Error received from peer ipv4:10.255.26.210:8470","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@caffeine-lab 
Cold you please share stand alone code with dependencies to replicate this issue or if possible share a colab gist with the error faced.

With respect to the error faced please find similar issues below:
 [link](https://www.kaggle.com/dimitreoliveira/bug-report-unavailableerror-socket-closed) [link1](https://github.com/tensorflow/tensorflow/issues/36136#issuecomment-627731715)
