### ISSUE TITLE
java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: OpenCL library not loaded - dlopen failed: library "libOpenCL-pixel.so" not found Falling back to OpenGL TfLiteGpuDelegate Invoke: Write to buffer failed. Source data is larger than buffer. 

### ISSUE THREAD

**Issue by iglaweb** [tensorflow/tensorflow#41839]
**System information**
- Android 9.
- TensorFlow Lite.
- Google Pixel

build.gradle:
```
implementation('org.tensorflow:tensorflow-lite:2.2.0')
implementation ('org.tensorflow:tensorflow-lite-gpu:2.2.0')
```

**Describe the current behavior**

Exception is thrown on Google Pixel while running Blazeface model taken from Mediapipe repo (https://github.com/google/mediapipe/blob/master/mediapipe/models/face_detection_front.tflite). But this model works successfully on Samsung S10 and Xiaomi MI8.

```
 Internal error: Failed to run on the given Interpreter: Following operations are not supported by GPU delegate:
    DEQUANTIZE: 
    164 operations will run on the GPU, and the remaining 0 operations will run on the CPU.
    Can not open OpenCL library on this device - dlopen failed: library "libOpenCL.so" not found
    Falling back to OpenGL
    TfLiteGpuDelegate Invoke: GpuDelegate must run on the same thread where it was initialized.
    Node number 164 (TfLiteGpuDelegateV2) failed to invoke.
    
    TfLiteGpuDelegate Invoke: GpuDele [DevelopReportingTree.log:18]
    java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: Following operations are not supported by GPU delegate:
    DEQUANTIZE: 
    164 operations will run on the GPU, and the remaining 0 operations will run on the CPU.
    Can not open OpenCL library on this device - dlopen failed: library "libOpenCL.so" not found
    Falling back to OpenGL
    TfLiteGpuDelegate Invoke: GpuDelegate must run on the same thread where it was initialized.
    Node number 164 (TfLiteGpuDelegateV2) failed to invoke.
    
    TfLiteGpuDelegate Invoke: GpuDele
        at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:158)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:343)
```

When I change tflite dependencies from nightly to v. 2.2 and modify interpreter initialization, error will be a bit different for Google Pixel:

```
java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: OpenCL library not loaded - dlopen failed: library "libOpenCL-pixel.so" not found
Falling back to OpenGL
TfLiteGpuDelegate Invoke: Write to buffer failed. Source data is larger than buffer. 
```

**Describe the expected behavior**

Successfully recognizes faces without exceptions

**Standalone code to reproduce the issue**

 ```
    private static final int BATCH_SIZE = 1;
    private ByteBuffer imgData;
    private int[] intValues;
    private static final int PIXEL_SIZE = 3;

       Interpreter tfLite = createTfliteInterpreter(assetManager, "face_detection_front_blazefast.tflite");
         imgData = ByteBuffer.allocateDirect(BATCH_SIZE * 128 * 128 * PIXEL_SIZE * 4);
        imgData.order(ByteOrder.nativeOrder());
        intValues = new int[inputSize * inputSize];

    public List<Recognition> recognizeImage(Bitmap bitmap) {
        final int previewWidth = bitmap.getWidth();
        final int previewHeight = bitmap.getHeight();

        int sensorOrientation = 0;
        Matrix frameToCropTransform =
                getTransformationMatrix(
                        previewWidth,
                        previewHeight,
                        128, 128,
                        sensorOrientation,
                        false
                );

        // to restore location object
        cropToFrameTransform = new Matrix();
        frameToCropTransform.invert(cropToFrameTransform);

        // crop image
        Canvas canvas = new Canvas(croppedBitmap);
        canvas.drawBitmap(bitmap, frameToCropTransform, null);

        convertBitmapToByteBuffer(
                croppedBitmap,
                imgData,
                intValues,
                128
        );

        Map<Integer, Object> outputs = provideOutput();
        Object[] inputArray = {imgData};
        try {
            tfLite.runForMultipleInputsOutputs(inputArray, outputs);
        } catch (Exception e) {
            Timber.e(e);
        }
        return getDetections(bitmap, outputs);
    }

    public Map<Integer, Object> provideOutput() {
        float[][][] boxesResult = new float[1][896][16];
        float[][][] scoresResult = new float[1][896][1];
        HashMap<Integer, Object> outputs = new HashMap<>();
        outputs.put(0, boxesResult);
        outputs.put(1, scoresResult);
        return outputs;
    }

    Interpreter createTfliteInterpreter(AssetManager assetManager, String modelPath) {
        try {
            final Interpreter.Options options;
                GpuDelegate.Options options1 = new GpuDelegate.Options()
                        .setPrecisionLossAllowed(true)
                        .setInferencePreference(GpuDelegate.Options.INFERENCE_PREFERENCE_FAST_SINGLE_ANSWER);
                GpuDelegate delegate = new GpuDelegate(options1);
                options = new Interpreter.Options()
                        .addDelegate(delegate);
            return new Interpreter(
                    loadModelFile(assetManager, modelPath),
                    options
            );
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    public static void convertBitmapToByteBuffer(Bitmap bitmap, ByteBuffer imgData, int[] intValues, int mInputSize) {
        bitmap.getPixels(intValues, 0, bitmap.getWidth(), 0, 0, bitmap.getWidth(), bitmap.getHeight());
        imgData.rewind();
        int pixel = 0;
        for (int i = 0; i < mInputSize; ++i) {
            for (int j = 0; j < mInputSize; ++j) {
                final int pixelValue = intValues[pixel++];
                imgData.putFloat(((pixelValue >> 16) & 0xFF) / 255.0f);
                imgData.putFloat(((pixelValue >> 8) & 0xFF) / 255.0f);
                imgData.putFloat((pixelValue & 0xFF) / 255.0f);
            }
        }
    }

public static Matrix getTransformationMatrix(
            final int srcWidth,
            final int srcHeight,
            final int dstWidth,
            final int dstHeight,
            final int applyRotation,
            final boolean maintainAspectRatio) {
        final Matrix matrix = new Matrix();

        if (applyRotation != 0) {
            if (applyRotation % 90 != 0) {
                Timber.w("Rotation of %d % 90 != 0", applyRotation);
            }

            // Translate so center of image is at origin.
            matrix.postTranslate(-srcWidth / 2.0f, -srcHeight / 2.0f);

            // Rotate around origin.
            matrix.postRotate(applyRotation);
        }

        // Account for the already applied rotation, if any, and then determine how
        // much scaling is needed for each axis.
        final boolean transpose = (Math.abs(applyRotation) + 90) % 180 == 0;

        final int inWidth = transpose ? srcHeight : srcWidth;
        final int inHeight = transpose ? srcWidth : srcHeight;

        // Apply scaling if necessary.
        if (inWidth != dstWidth || inHeight != dstHeight) {
            final float scaleFactorX = dstWidth / (float) inWidth;
            final float scaleFactorY = dstHeight / (float) inHeight;

            if (maintainAspectRatio) {
                // Scale by minimum factor so that dst is filled completely while
                // maintaining the aspect ratio. Some image may fall off the edge.
                final float scaleFactor = Math.max(scaleFactorX, scaleFactorY);
                matrix.postScale(scaleFactor, scaleFactor);
            } else {
                // Scale exactly to fill dst from src.
                matrix.postScale(scaleFactorX, scaleFactorY);
            }
        }

        if (applyRotation != 0) {
            // Translate back from origin centered reference to destination frame.
            matrix.postTranslate(dstWidth / 2.0f, dstHeight / 2.0f);
        }

        return matrix;
    }
```

**Comment by multiverse-tf** [comment]
This issue looks similar to https://github.com/tensorflow/tensorflow/issues/44659.  Just wondering does more recent tflite build fix the issue? Thx!

**Comment by sushreebarsa** [comment]
@iglaweb This looks more similar to this [issue](https://github.com/tensorflow/tensorflow/issues/44659)  & Could you please execute your code using Latest Version 2.4.1 or 2.5 and let us know if the issue still persists? Thanks!

**Comment by iglaweb** [comment]
> This looks more similar to this [issue](https://github.com/tensorflow/tensorflow/issues/44659) & Could you please execute your code using Latest Version 2.4.1 or 2.5 and let us know if the issue still persists? Thanks!

All delegates (CPU, GPU, Hexagon, NNAPI) do not throw errors now with TensorflowLite 2.5. Thanks!

**Comment by StewardH** [comment]
The same issue reoccurred on Android 12 while running the SSDtiny model on GPU.  The same code works fine on android 8. 

I am running tfLite 2.8.0 . Is there anything that needs to be upgraded in order for tfLite to use the available GPU resources on android 12 ?

**Comment by amol-tw** [comment]
@StewardH Did you find a solution to this? I have opened a similar issue [here](https://github.com/tensorflow/tensorflow/issues/56533) but no luck so far.
