### ISSUE TITLE
Exception: TensorFlow Lite currently doesn't support control flow ops: Merge, Switch.

### ISSUE THREAD

**Issue by apupu1** [tensorflow/tensorflow#41849]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 18.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):1.14

**Provide the text output from tflite_convert**

```
tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.
2020-07-29 15:27:21.979509: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 1402 operators, 2593 arrays (0 quantized)
2020-07-29 15:27:22.011911: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After Removing unused ops pass 1: 1290 operators, 2425 arrays (0 quantized)
2020-07-29 15:27:22.054821: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 1290 operators, 2425 arrays (0 quantized)
2020-07-29 15:27:22.098145: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 1062 operators, 2194 arrays (0 quantized)
2020-07-29 15:27:22.139738: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Group bidirectional sequence lstm/rnn: 1062 operators, 2194 arrays (0 quantized)
2020-07-29 15:27:22.172354: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 1062 operators, 2194 arrays (0 quantized)
2020-07-29 15:27:22.219537: I tensorflow/lite/toco/allocate_transient_arrays.cc:345] Total transient array allocated size: 1228800 bytes, theoretical optimal value: 921600 bytes.
2020-07-29 15:27:22.231094: E tensorflow/lite/toco/toco_tooling.cc:456] TensorFlow Lite currently doesn't support control flow ops: Merge, Switch.
Traceback (most recent call last):
  File "/home/ps/anaconda3/envs/rknn/bin/toco_from_protos", line 11, in <module>
    sys.exit(main())
  File "/home/ps/.local/lib/python3.6/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 59, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/home/ps/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/ps/.local/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/ps/.local/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/ps/.local/lib/python3.6/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 33, in execute
    output_str = tensorflow_wrap_toco.TocoConvert(model_str, toco_str, input_str)
Exception: TensorFlow Lite currently doesn't support control flow ops: Merge, Switch.
```

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

**Comment by Saduf2019** [comment]
@apupu1 
This has already been reported and resolved, please refer to [this link](https://github.com/tensorflow/tensorflow/issues/41547#issuecomment-660781354).

**Comment by apupu1** [comment]
@Saduf2019 thanks
