### ISSUE TITLE
tf.data.Dataset API with ImageGenerator => ValueError: as_list() is not defined on an unknown TensorShape.

### ISSUE THREAD

**Issue by vladbph** [tensorflow/tensorflow#41843]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): See the colab link below
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 18.04
- TensorFlow installed from (source or binary): pip install tensorflow-gpu==2.2.0
- TensorFlow version (use command below): 2.2.0
- Python version: sys.version_info(major=3, minor=6, micro=9, releaselevel='final', serial=0)
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: colab: CPU/GPU/TPU

**Describe the current behavior**
When using tf.data.Dataset API fit throws an exception:
INFO:tensorflow:Error reported to Coordinator: as_list() is not defined on an unknown TensorShape.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/mirrored_strategy.py", line 998, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 262, in wrapper
    return converted_call(f, args, kwargs, options=options)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 418, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 346, in _call_unconverted
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 543, in train_step
    self.compiled_metrics.update_state(y, y_pred, sample_weight)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/compile_utils.py", line 391, in update_state
    self._build(y_pred, y_true)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/compile_utils.py", line 322, in _build
    self._metrics, y_true, y_pred)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/nest.py", line 1118, in map_structure_up_to
    **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/nest.py", line 1214, in map_structure_with_tuple_paths_up_to
    *flat_value_lists)]
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/nest.py", line 1213, in <listcomp>
    results = [func(*args, **kwargs) for args in zip(flat_path_list,
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/nest.py", line 1116, in <lambda>
    lambda _, *values: func(*values),  # Discards the path arg.
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/compile_utils.py", line 421, in _get_metric_objects
    return [self._get_metric_object(m, y_t, y_p) for m in metrics]
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/compile_utils.py", line 421, in <listcomp>
    return [self._get_metric_object(m, y_t, y_p) for m in metrics]
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/compile_utils.py", line 442, in _get_metric_object
    y_t_rank = len(y_t.shape.as_list())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_shape.py", line 1173, in as_list
    raise ValueError("as_list() is not defined on an unknown TensorShape.")
ValueError: as_list() is not defined on an unknown TensorShape.

**Describe the expected behavior**
No exception.

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1TnU5zWWyLeDnk2K-6aVeur0W9zEscWuX?usp=sharing

Provide a reproducible test case that is the bare minimum necessary to generate
the problem.https://colab.research.google.com/drive/1TnU5zWWyLeDnk2K-6aVeur0W9zEscWuX?usp=sharing

**Other info / logs** 
Please use **use_dataset_api** flag to toggle using dataset API vs ImageGenerator, which works

**Comment by vladbph** [comment]
Found the solution by explicitly providing output_shapes output_shapes = ([None, 28, 28, 1],[None,10]) for the example above. However it raises the following questions, 1) why the output_shapes is optional? 2) why the shapes cannot be deduced from the provided generator? 3) The error message is very confusing and loosely referencing to the source of the issue...
`output_shapes = ([None, 28, 28, 1],[None,10]);
train_generator = tf.data.Dataset.from_generator( make_generator, ( tf.float32, tf.float32 ),
                    output_shapes = output_shapes )
`

**Comment by aaudiber** [comment]
Hi @vladbph, I get permission denied when I try to access the colab. Can you make it publicly accessible? Thanks.

**Comment by vladbph** [comment]
> Hi @vladbph, I get permission denied when I try to access the colab. Can you make it publicly accessible? Thanks.

Sorry for the delay. I did make it publicly available, just added anyone can edit rights... Could you please try it.
https://colab.research.google.com/drive/1TnU5zWWyLeDnk2K-6aVeur0W9zEscWuX?usp=sharing

**Comment by nikitamaia** [comment]
Hi @vladbph, seems to me like this the same issue as #32912 and the error message is raised from `model.fit`. In that case it's less surprising that the `output_shapes` argument is optional, as there are other uses for the generator other than passing it to `model.fit`.
