### ISSUE TITLE
TFLiteConverter: ConvertError: loc("Func/StatefulPartitionedCall/input/_0"): requires all operands and results to have compatible element types

### ISSUE THREAD

**Issue by mgalgs** [tensorflow/tensorflow#41877]
**System information**
- OS Platform and Distribution: Manjaro running Ubuntu 18.04 under Docker (using the `tensorflow/tensorflow:2.2.0-gpu-jupyter` image)
- TensorFlow installed from (source or binary): Using official docker image, actually not sure if it's source or binary.
- TensorFlow version (or github SHA if from source): 2.2.0

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```python
import sys
import os

import tensorflow as tf


def usage():
    proggie = os.path.basename(sys.argv[0])
    print(f"""\
Usage: {proggie} <input_saved_model_dir> <output>

Example: {proggie} output_inference_graph_v1.pb/saved_model converted_model.tflite""")


if __name__ == "__main__":
    if len(sys.argv) != 3 or '-h' in sys.argv or '--help' in sys.argv:
        usage()
        sys.exit(1)

    saved_model_dir, outfile = sys.argv[1:]
    converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
    tflite_model = converter.convert()
    with tf.io.gfile.GFile('model.tflite', 'wb') as f:
        f.write(tflite_model)
    print(f"{outfile} written")
```

**The output from the converter invocation**

```
docker exec -ti tf2 \
        bash -c \
        "cd /tf/routespotter/training/routesv3/ && python /tf/routespotter/scripts/convert_to_tflite.py trained-inference-graphs/output/saved_model trained-inference-graphs/output/converted_model.tflite"
2020-07-29 21:30:35.933784: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-07-29 21:30:37.541131: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-07-29 21:30:37.554309: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:
pciBusID: 0000:65:00.0 name: GeForce GTX 1070 computeCapability: 6.1
coreClock: 1.835GHz coreCount: 15 deviceMemorySize: 7.93GiB deviceMemoryBandwidth: 238.66GiB/s
2020-07-29 21:30:37.554340: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-07-29 21:30:37.555786: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-07-29 21:30:37.557191: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-07-29 21:30:37.557467: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-07-29 21:30:37.558961: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-07-29 21:30:37.559781: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2020-07-29 21:30:37.562688: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-07-29 21:30:37.563390: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-07-29 21:30:37.563659: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-07-29 21:30:37.569752: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 3301490000 Hz
2020-07-29 21:30:37.571232: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0xaf61e40 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-29 21:30:37.571276: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-07-29 21:30:37.718561: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0xafcdab0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-07-29 21:30:37.718596: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 1070, Compute Capability 6.1
2020-07-29 21:30:37.719275: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:
pciBusID: 0000:65:00.0 name: GeForce GTX 1070 computeCapability: 6.1
coreClock: 1.835GHz coreCount: 15 deviceMemorySize: 7.93GiB deviceMemoryBandwidth: 238.66GiB/s
2020-07-29 21:30:37.719308: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-07-29 21:30:37.719337: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-07-29 21:30:37.719357: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-07-29 21:30:37.719375: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-07-29 21:30:37.719394: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-07-29 21:30:37.719406: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2020-07-29 21:30:37.719422: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-07-29 21:30:37.720408: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-07-29 21:30:37.720450: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-07-29 21:30:38.075379: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-07-29 21:30:38.075416: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0
2020-07-29 21:30:38.075422: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N
2020-07-29 21:30:38.076193: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7091 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:65:00.0, compute capability: 6.1)
2020-07-29 21:30:47.046860: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 1
2020-07-29 21:30:47.046987: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-07-29 21:30:47.047691: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:
pciBusID: 0000:65:00.0 name: GeForce GTX 1070 computeCapability: 6.1
coreClock: 1.835GHz coreCount: 15 deviceMemorySize: 7.93GiB deviceMemoryBandwidth: 238.66GiB/s
2020-07-29 21:30:47.047721: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-07-29 21:30:47.047745: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-07-29 21:30:47.047755: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-07-29 21:30:47.047765: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-07-29 21:30:47.047775: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-07-29 21:30:47.047788: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2020-07-29 21:30:47.047798: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-07-29 21:30:47.048149: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-07-29 21:30:47.048174: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-07-29 21:30:47.048181: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0
2020-07-29 21:30:47.048188: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N
2020-07-29 21:30:47.048560: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7091 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:65:00.0, compute capability: 6.1)
2020-07-29 21:30:47.229748: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816] Optimization results for grappler item: graph_to_optimize
2020-07-29 21:30:47.229790: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:818]   function_optimizer: Graph size after: 4275 nodes (3787), 4874 edges (4379), time = 107.259ms.
2020-07-29 21:30:47.229795: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:818]   function_optimizer: function_optimizer did nothing. time = 3.916ms.
2020-07-29 21:30:51.658251: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:313] Ignored output_format.
2020-07-29 21:30:51.658289: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:316] Ignored drop_control_dependency.
loc("Func/StatefulPartitionedCall/input/_0"): error: requires all operands and results to have compatible element types
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert.py", line 199, in toco_convert_protos
    enable_mlir_converter)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/wrap_toco.py", line 38, in wrapped_toco_convert
    enable_mlir_converter)
Exception: <unknown>:0: error: loc("Func/StatefulPartitionedCall/input/_0"): requires all operands and results to have compatible element types
<unknown>:0: note: loc("Func/StatefulPartitionedCall/input/_0"): see current operation: %1 = "tf.Identity"(%arg0) {device = ""} : (tensor<1x?x?x3x!tf.quint8>) -> tensor<1x?x?x3xui8>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tf/routespotter/scripts/convert_to_tflite.py", line 22, in <module>
    tflite_model = converter.convert()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py", line 1076, in convert
    return super(TFLiteConverterV2, self).convert()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py", line 900, in convert
    self).convert(graph_def, input_tensors, output_tensors)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py", line 633, in convert
    **converter_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert.py", line 574, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert.py", line 202, in toco_convert_protos
    raise ConverterError(str(e))
tensorflow.lite.python.convert.ConverterError: <unknown>:0: error: loc("Func/StatefulPartitionedCall/input/_0"): requires all operands and results to have compatible element types
<unknown>:0: note: loc("Func/StatefulPartitionedCall/input/_0"): see current operation: %1 = "tf.Identity"(%arg0) {device = ""} : (tensor<1x?x?x3x!tf.quint8>) -> tensor<1x?x?x3xui8>
```

**Also, please include a link to the saved model or GraphDef**

Custom trained model based on [ssd_resnet50_v1_fpn_640x640_coco17_tpu-8](http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_resnet50_v1_fpn_640x640_coco17_tpu-8.tar.gz) by following the [tensorflow-object-detection-api-tutorial](https://tensorflow-object-detection-api-tutorial.readthedocs.io). I know my custom trained model works because I've run it through the [object_detection_tutorial](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/object_detection_tutorial.ipynb) using test images from my dataset and I get successful detections. Not sure if I'm just using an unsupported operand for tflite? Having a hard time deciphering the error message...

```
https://drive.google.com/file/d/1O_c12RAALroTomEvDaH8gwukYzNZDegq/view?usp=sharing
```

**Failure details**
- Conversion process fails

**RNN conversion support**
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title. :x:  

**Any other info / logs**

See traceback above.

**Comment by amahendrakar** [comment]
@mgalgs,
Looks like the issue has been resolved in the latest TF-nightly. I was able to convert the model successfully after adding the below lines to the code. 

```
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir,signature_keys=['serving_default'])
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.experimental_new_converter = True
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
```

Please check [this gist](https://colab.research.google.com/gist/amahendrakar/36de658face01b4d232f25352bca1655/41877-tf-nightly.ipynb) for reference. Thanks!

**Comment by mgalgs** [comment]
@amahendrakar awesome, that worked! Getting an error when I actually try to load the model on the mobile side but I think that might be a separate issue... I'll open another issue after some more debugging. Thanks again.

**Comment by DjangoPeng** [comment]
Same issue on `ssd_mobilenet_v1_fpn_640x640_coco17_tpu-8` with tf v2.3

**Comment by DjangoPeng** [comment]
After installing tf-nightly, another issue occurs:

![image](https://user-images.githubusercontent.com/16943353/90093579-88ccaa00-dd5e-11ea-8f9e-a95b689b0cc0.png)

It seems like I can't import tf-nightly successfully.

Device info: Nvidia V100 on Azure.

Driver info: 
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64.00    Driver Version: 440.64.00    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  On   | 00000001:00:00.0 Off |                    0 |
| N/A   27C    P0    24W / 250W |      0MiB / 16160MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by amahendrakar** [comment]
@DjangoPeng,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

**Comment by vadim-SX** [comment]
@amahendrakar I have done all the steps, using the cpu docker tensorflow

running::
import sys
import os
import tensorflow as tf
saved_model_dir = "/tmp/ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8/saved_model/"
outfile = "/tmp/ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8/saved_model/"
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir,signature_keys=['serving_default'])
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.experimental_new_converter = True
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]

tflite_model = converter.convert()
with tf.io.gfile.GFile('model.tflite', 'wb') as f:
    f.write(tflite_model)
print(f"{outfile} written")

the output is :
/tmp/ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8/saved_model/ written

but there is no file written, what can be the problem?`

**Comment by smohan10** [comment]
The issue still exists in TF 2.3.0. Is anyone still facing the same problem?

**Comment by srjoglekar246** [comment]
@mgalgs @smohan10 For converting SSD TF2 models to TFLite, could you see [this comment](https://github.com/tensorflow/models/issues/9033#issuecomment-686628182)? We are tracking TFLite support for TF2 ODAPI models there.
