### ISSUE TITLE
Import TensorFlow Failed

### ISSUE THREAD

**Issue by liyy0** [tensorflow/tensorflow#41883]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows10 x64
- TensorFlow installed from (source or binary): anaconda prompt
- TensorFlow version: tensorflow2.3.0 only cpu
- Python version: 3.7
- Installed using virtualenv? pip? conda?: from anaconda prompt- [pip install tensorflow]
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: I dont have a GPU

**Describe the problem**
I'm new to tensorflow. Sorry if it's a dummy question.
I downloaded the tensorflow from anaconda prompt as I listed above. Then I only run "import tensorflow as tf" as the turtorial said but it goes wrong as below. I check the path and there's no such a dll file. Can anyone help me?

**Any other info / logs**

runfile('C:/Users/13926/zzz/untitled1.py', wdir='C:/Users/13926/zzz')
Traceback (most recent call last):

  File "C:\Users\13926\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *

ImportError: DLL load failed: The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\13926\zzz\untitled1.py", line 8, in <module>
    import tensorflow as tf

  File "C:\Users\13926\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util

  File "C:\Users\13926\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context

  File "C:\Users\13926\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe

  File "C:\Users\13926\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow

  File "C:\Users\13926\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)

ImportError: Traceback (most recent call last):
  File "C:\Users\13926\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The specified module could not be found

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by Saduf2019** [comment]
@liyy0 
Please refer to [this link](https://github.com/tensorflow/tensorflow/issues/36683#issuecomment-585097726) of resolved issue and let us know.
