### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found

### ISSUE THREAD

**Issue by manidevi** [tensorflow/tensorflow#41895]
**System information**
- OS Platform and Distribution : Windows 10
- TensorFlow installed from (source or binary): Source (branch r2.1)
- Python version: 3.6
- Bazel version :0.29.1
- GCC/Compiler version :
- Memory: 8GB

**Describe the problem**
 Compiling Tensorflow with mkl on Windows ends up in 
"ERROR: C:/users/dm212/documents/devi/tensorflow/tensorflow/python/keras/api/BUILD:115:1: Executing genrule //tensorflow/python/keras/api:keras_python_api_gen_compat_v1 failed (Exit 1)". 
I followed the steps from **https://www.tensorflow.org/install/source_windows**. Also checked few solutions in similar issues, but didn't help.

 **Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel --output_base="C:/Users/dm212/Documents/TF"  build --config=mkl --config=opt  --config=v2                            --define=no_tensorflow_py_deps=true   //tensorflow/tools/pip_package:build_pip_package 

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
```
ERROR: C:/users/dm212/documents/devi/tensorflow/tensorflow/python/keras/api/BUILD:115:1: Executing genrule //tensorflow/python/keras/api:keras_python_api_gen_compat_v1 failed (Exit 1)
Traceback (most recent call last):
  File "\\?\C:\Users\dm212\AppData\Local\Temp\Bazel.runfiles_8o1_a1ke\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "\\?\C:\Users\dm212\AppData\Local\Temp\Bazel.runfiles_8o1_a1ke\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "\\?\C:\Users\dm212\AppData\Local\Temp\Bazel.runfiles_8o1_a1ke\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\dm212\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\dm212\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\\?\C:\Users\dm212\AppData\Local\Temp\Bazel.runfiles_8o1_a1ke\runfiles\org_tensorflow\tensorflow\python\tools\api\generator\create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "\\?\C:\Users\dm212\AppData\Local\Temp\Bazel.runfiles_8o1_a1ke\runfiles\org_tensorflow\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "\\?\C:\Users\dm212\AppData\Local\Temp\Bazel.runfiles_8o1_a1ke\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "\\?\C:\Users\dm212\AppData\Local\Temp\Bazel.runfiles_8o1_a1ke\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "\\?\C:\Users\dm212\AppData\Local\Temp\Bazel.runfiles_8o1_a1ke\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "\\?\C:\Users\dm212\AppData\Local\Temp\Bazel.runfiles_8o1_a1ke\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\dm212\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\dm212\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
ERROR: C:/users/dm212/documents/devi/tensorflow/tensorflow/tools/pip_package/BUILD:114:1 Executing genrule //tensorflow:tf_python_api_gen_v2 failed (Exit 1)
INFO: Elapsed time: 24724.095s, Critical Path: 20460.98s
INFO: 5794 processes: 5794 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

```

**Comment by ravikyram** [comment]
@manidevi 

What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the [latest microsoft visual c++ redistributable from here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).
.Also, please follow the instructions from to install from [Tensorflow website](https://www.tensorflow.org/install/source_windows).

Please, check Your CPU/Python is on 32 bits?Please, refer #36167 and see if it helps you.
Please, refer similar issue #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
Thanks!

**Comment by manidevi** [comment]
> @manidevi
> 
> What is make/model of your cpu?
> I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
> Make sure to download the [latest microsoft visual c++ redistributable from here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).
> .Also, please follow the instructions from to install from [Tensorflow website](https://www.tensorflow.org/install/source_windows).
> 
> Please, check Your CPU/Python is on 32 bits?Please, refer #36167 and see if it helps you.
> Please, refer similar issue #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
> Thanks!

CPU Model : AMD Ryzen 3700, 4 cores/8 threads
I checked all the requirements you mentioned

- CPU has AVX and AVX2 support
- Microsoft 2015-2019 redistributable has been installed
- Python is of 64 bits
`Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32` 

I get the error with the above setup only.

**Comment by ravikyram** [comment]
@manidevi 

Please, check the below comments 

1.You need to install the MSVC 2019 redistributable
2.There is a library that is in a different location/not installed on your system that cannot be loaded.

**Comment by manidevi** [comment]
@ravikyram 

  Installed the lastest MSVC redistributable from [here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads). Still the ImportError exists.
 Is there a way to find the missing library or libraries required by tensorflow?

**Comment by ymodak** [comment]
You may use https://www.dependencywalker.com/ to find missing dll files.
