### ISSUE TITLE
Can't use tensorflow

### ISSUE THREAD

**Issue by Parrass** [tensorflow/tensorflow#41945]
I'm trying to use keras, but the output says that keras requires tensorflow 2.2 or higher, which I already have installed. And when I try this command 
`import tensorflow as tf
hello = tf.constant('Hello, TensorFlow!')
sess = tf.Session()
print(sess.run(hello))`
Returns: 
`Traceback (most recent call last):

  File "C:\Users\luiz_\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *

ImportError: DLL load failed while importing _pywrap_tensorflow_internal: Não foi possível encontrar o módulo especificado.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-4-9d5f9c01b035>", line 1, in <module>
    import tensorflow as tf

  File "C:\Users\luiz_\anaconda3\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util

  File "C:\Users\luiz_\anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context

  File "C:\Users\luiz_\anaconda3\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe

  File "C:\Users\luiz_\anaconda3\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow

  File "C:\Users\luiz_\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)

ImportError: Traceback (most recent call last):
  File "C:\Users\luiz_\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: Não foi possível encontrar o módulo especificado.

Failed to load the native TensorFlow runtime.`

Please help! I installed both tensorflow and keras with pip install

**Comment by Saduf2019** [comment]
@Parrass 
What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the latest [microsoft visual c++ redistributable from here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).
.Also, please follow the instructions from to install from [Tensorflow website](https://www.tensorflow.org/install/source_windows).


#41314 #40459 [link](https://github.com/tensorflow/tensorflow/issues/38916#issuecomment-619798621)

**Comment by Parrass** [comment]
I have a i7 8th gen. I dont think that it is the problem. In the course I did they recommended to use Spyder, from Anaconda. The installing process is the same?

**Comment by Saduf2019** [comment]
@Parrass 
Please refer to [this link](https://docs.anaconda.com/anaconda/install/) for anaconda, we do not handle anaconda installation related issues.
