### ISSUE TITLE
Syntax Errors in Python 3.5 : Installed using pip3

### ISSUE THREAD

**Issue by gszep** [tensorflow/tensorflow#4194]
I followed the instructions on [installing TensorFlow using pip](https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html#optional-install-cuda-gpus-on-linux) and installed both the ```Ubuntu/Linux 64-bit, GPU enabled, Python 3.5``` and ```Ubuntu/Linux 64-bit, GPU enabled, Python 2.7``` versions using pip3 and pip2 respectively. The package imports correctly in Python 2.7 but the following SyntaxErrors occur for Python 3.5.

```terminal
python3
Python 3.5.2 (default, Jul  5 2016, 12:43:10) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
```
```python
>>> import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
...
  File "/home/gszep/.local/lib/python3.5/site-packages/dateutil/parser.py", line 158
    l.append("%s=%s" % (attr, `value`))
                              ^
SyntaxError: invalid syntax
```

**Comment by gszep** [comment]
After editing line 158 in ```/home/gszep/.local/lib/python3.5/site-packages/dateutil/parser.py```, replacing ``` `value` ``` with ``` 'value' ``` which is probably the ascii character causing the problem, I get a new import error:
```python
>>> import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
  File "/home/gszep/.local/lib/python3.5/site-packages/dateutil/parser.py", line 303
    raise ValueError, "unknown string format"
                    ^
SyntaxError: invalid syntax
```

**Comment by gszep** [comment]
Editing lines 303 and 326 in that file finally fixed the problem. The change has to do with the update syntax ```ValueError, "string" ``` to  ```ValueError("string") ```

**Comment by naseemfico** [comment]
I have this fixed by installing python-dateutil fom pypi.org.
pip install python-dateutil
OR
pipenv install python-dateutil
