### ISSUE TITLE
tflite on Android: Didn't find op for builtin opcode 'CONV_2D' version '5'

### ISSUE THREAD

**Issue by mgalgs** [tensorflow/tensorflow#41943]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android emulator (Android 10.0+ (Google APIs))
- TensorFlow installed from (source or binary): Model was generated with TF from binary
- TensorFlow version (or github SHA if from source): Model was generated with `tf-2.2.0` and converted to tflite with `tf-nightly-2.4.0.dev20200730`. Using [`tflite` v1.1.1](https://pub.dev/packages/tflite) flutter bindings.

**Provide the text output from tflite_convert**

No issues with `tflite_convert` (thanks to @amahendrakar in #41877). My issue is with using my model on the mobile side, using the [`tflite`](https://pub.dev/packages/tflite) flutter bindings.

I'm getting the following error when I try to load my custom model:

```
Unsupported value: java.lang.IllegalArgumentException: Internal error: Cannot create interpreter: Didn't find op for builtin opcode 'CONV_2D' version '5'

Registration failed.
```

**Standalone code to reproduce the issue** 

See [this gist](https://gist.github.com/mgalgs/f92d78e6c7ee09b8298cd325bf4f3ed6). The error is happening when I try to [load the model](https://gist.github.com/mgalgs/f92d78e6c7ee09b8298cd325bf4f3ed6#file-home-dart-L31-L35).

If I swap out my custom generated tflite model (see #41877 for how the model was generated) for an off-the-shelf SSD model detection works just fine.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

Stack trace:

**Dart**
```
StandardMethodCodec.decodeEnvelope (message_codecs.dart:569)
MethodChannel.invokeMethod (platform_channel.dart:321)
<asynchronous gap>
Tflite.loadModel (tflite.dart:15)
_HomePageState.loadModel (home.dart:30)
_HomePageState.initState (home.dart:26)
StatefulElement._firstBuild (framework.dart:4355)
ComponentElement.mount (framework.dart:4201)
Element.inflateWidget (framework.dart:3194)
Element.updateChild (framework.dart:2988)
... snipped a bunch of framework stuff ...
```

**Native (Android)**
```
java.lang.IllegalArgumentException: Internal error: Cannot create interpreter: Didn't find op for builtin opcode 'CONV_2D' version '5'

Registration failed.

	at org.tensorflow.lite.NativeInterpreterWrapper.createInterpreter(Native Method)
	at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:72)
	at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:63)
	at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:266)
	at sq.flutter.tflite.TflitePlugin.loadModel(TflitePlugin.java:232)
	at sq.flutter.tflite.TflitePlugin.onMethodCall(TflitePlugin.java:98)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:183)
	at android.app.ActivityThread.main(ActivityThread.java:7476)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:939)
```

**Comment by ValentinBlokhin** [comment]
@mgalgs I'm having the same issue, but on ios. Did you found the solution?

**Comment by mgalgs** [comment]
@ValentinBlokhin no 😭

**Comment by jdduke** [comment]
I believe this was due to some improvements made to the post-training quantization pipeline, which requires the latest TFLite runtime (2.3 or more recent).

For now, you can either downgrade to TF 2.2 for model conversion, or file an issue (or submit a PR) to upgrade the flutter bindings to use the latest TFLite 2.3 release (see https://github.com/shaqian/flutter_tflite).

**Comment by mgalgs** [comment]
@jdduke shoot, I had to use something newer than 2.2 due to #41877 , so downgrading to 2.2 for model conversion isn't really an option :thinking: I'll try to get `flutter_tflite` updated and will report back with results.

**Comment by mgalgs** [comment]
@jdduke I've updated my `flutter_tflite` to use `org.tensorflow:tensorflow-lite:2.3.0` ([commit](https://github.com/mgalgs/flutter_tflite/commit/e7356bd07129bb35dde8a2f094b20ecaf5248502)) but I'm still getting this same error.

**Comment by mgalgs** [comment]
Here's the native-side stack trace under Android:

```
java.lang.IllegalArgumentException: Internal error: Cannot create interpreter: Didn't find op for builtin opcode 'CONV_2D' version '5'

Registration failed.

	at org.tensorflow.lite.NativeInterpreterWrapper.createInterpreter(Native Method)
	at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:72)
	at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:63)
	at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:266)
	at sq.flutter.tflite.TflitePlugin.loadModel(TflitePlugin.java:232)
	at sq.flutter.tflite.TflitePlugin.onMethodCall(TflitePlugin.java:98)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:183)
	at android.app.ActivityThread.main(ActivityThread.java:7476)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:939)
```

**Comment by jdduke** [comment]
If you're converting with the TF nightly, you'll need to use the nightly TFLite runtime for this particular op. That is, `org.tensorflow:tensorflow-lite:0.0.0-nightly`.

**Comment by mgalgs** [comment]
@jdduke changing to `org.tensorflow:tensorflow-lite:0.0.0-nightly` worked, thanks!

**Comment by ArtanBerisha1** [comment]
> @jdduke changing to `org.tensorflow:tensorflow-lite:0.0.0-nightly` worked, thanks!


In tf v2.2.0, I am getting the error:
Internal error: Cannot create interpreter: Didn't find op for builtin opcode 'SUB' version '3'

in v2.3.0, I am getting the error: 
Internal error: Cannot create interpreter: Didn't find op for builtin opcode 'CONV_2D' version '5'

Also I tried your solution @mgalgs , added implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly' , and got the error: 
Internal error: Cannot create interpreter: Did not get operators or tensors in subgraph 1.

Could you be more specifics, did you change anything else ?

**Comment by mgalgs** [comment]
> Could you be more specifics, did you change anything else ?

@ArtanBerisha1 this is the change I made: https://github.com/mgalgs/flutter_tflite/commit/82d62fdab9ee1826e875b11bc8c137e8d421a30e

That got me past the initial error but now I'm hitting another error preventing me from using my custom model on mobile (works fine on desktop). The stack trace is:

```
java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
	at sq.flutter.tflite.TflitePlugin$RunSSDMobileNet.<init>(TflitePlugin.java:654)
	at sq.flutter.tflite.TflitePlugin.detectObjectOnFrame(TflitePlugin.java:634)
	at sq.flutter.tflite.TflitePlugin.onMethodCall(TflitePlugin.java:135)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:183)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

I've moved on to another component with hopes that this stuff will resolve itself in `tf-nightly` while I work on other things, but I'm pushing up against this again and might spend some more time on it soon.

If anyone else gets `flutter-tflite` working I'd love to hear about your training and model conversion pipeline, because clearly I'm missing something...

**Comment by MareSeestern** [comment]
Any progress?

**Comment by adizagade20** [comment]
Try adding

**_`implementation 'org.tensorflow:tensorflow-lite:2.4.0'`_**

**Comment by AhmadRaza159** [comment]
Check out the version of Tensorflow which you use while training, Use the same version in android build.gridle(app).
I use tensorflow 2.4.0 (which is latest) in colab while training, so I put (implementation 'org.tensorflow:tensorflow-lite:2.4.0') in my android build.gridle(app)

**Comment by duongbaoquy** [comment]
Sorry but I'm getting the same error. I have tried the above suggestions but it still doesn't work.
I used TS version 2.4.1 to train, so even though I replaced the line `implementation 'org.tensorflow:tensorflow-lite:x.x.x` with xxx is different versions such as: 2.0.0 - 2.3.0 - 0.0.0 nightly, or 2.4.0
But all of them didn't work.

**Comment by AhmadRaza159** [comment]
Duongbaoquy you should use this, implementation 'org.tensorflow:tensorflow-lite:2.4.1'

**Comment by duongbaoquy** [comment]
I tried with 2.4.1 after reading your comment above, but then I get this error 
```
  > Could not find org.tensorflow:tensorflow-lite:2.4.1.
```

**Comment by AhmadRaza159** [comment]
2.4.1 is recent release, so that's why. Downgrade on training side may helpful

**Comment by duongbaoquy** [comment]
I tried downgrading the versions from 2.4.0 to 2.0.0
And it worked at version 2.0.0
But I also suddenly realized that the problem is not with which version you use.
I found this error will occur when you try to optimize the size of the model file, if you skip the size optimization step, the error will be resolved.
[Follow this tutorial](https://colab.research.google.com/github/tensorflow/examples/blob/master/lite/codelabs/digit_classifier/ml/step2_train_ml_model.ipynb) if you skip step [optimization](https://colab.research.google.com/github/tensorflow/examples/blob/master/lite/codelabs/digit_classifier/ml/step2_train_ml_model.ipynb#scrollTo=ahTP3T60nYJb) error will be resolved
Hope this helpful
Thanks

**Comment by adizagade20** [comment]
f

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.

**Comment by yechta** [comment]
How do you change what tensorflow_lite version flutter_tflite uses?

I added the dependency in build.gradle but I still get the same error.

**Comment by gptshubham595** [comment]
simple solution is that worked for me is

check version `!pip show tensorflow` mine was 2.12

so I used `implementation 'org.tensorflow:tensorflow-lite:2.12.0'` and it worked

**Comment by saurabhkumar8112** [comment]
If you're tflite_flutter, just make sure you use their latest version, 0.10.0, this issue has been fixed there.
