### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: 'DummySeedGenerator'

### ISSUE THREAD

**Issue by IOTpreneur** [tensorflow/tensorflow#41972]
On Google Colab using TPU

2020-08-01 18:34:58.551171: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Using TensorFlow backend.
TENSORFLOW version: 2.3.0
Tensorflow device List:
2020-08-01 18:35:01.566174: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-08-01 18:35:01.575940: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2300000000 Hz
2020-08-01 18:35:01.576357: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2fc4a00 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-01 18:35:01.576430: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-08-01 18:35:01.581369: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-08-01 18:35:01.585626: E tensorflow/stream_executor/cuda/cuda_driver.cc:314] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2020-08-01 18:35:01.585692: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (cbed57a08e06): /proc/driver/nvidia/version does not exist
Running on TPU  ['10.102.83.42:8470']
2020-08-01 18:35:01.604749: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job worker -> {0 -> 10.102.83.42:8470}
2020-08-01 18:35:01.604991: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:34406}
2020-08-01 18:35:01.624392: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job worker -> {0 -> 10.102.83.42:8470}
2020-08-01 18:35:01.624476: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:34406}
2020-08-01 18:35:01.625695: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:405] Started server with target: grpc://localhost:34406
REPLICAS:  8
train dataset:  665 , validation dataset:  36
2020-08-01 18:35:40.190966: E tensorflow/core/common_runtime/eager/context.cc:678] Failed to register function remotely due to 'DummySeedGenerator' is neither a type of a primitive operation nor a name of a function registered in binary running on n-a43c3c58-w-0. Make sure the operation or function is registered in the binary running in this process.
_**This shouldn't happen, please file a bug to tensorflow team.**_
Traceback (most recent call last):
  File "scripts/tf_imgseg_train.py", line 196, in <module>
    callbacks=callbacks)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 1063, in fit
    steps_per_execution=self._steps_per_execution)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/data_adapter.py", line 1102, in __init__
    self._steps_per_execution_value = steps_per_execution.numpy().item()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/values.py", line 662, in numpy
    return self.read_value().numpy()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1063, in numpy
    maybe_arr = self._numpy()  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1031, in _numpy
    six.raise_from(core._status_to_exception(e.code, e.message), None)  # pylint: disable=protected-access
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.NotFoundError: 'DummySeedGenerator' is neither a type of a primitive operation nor a name of a function registered in binary running on n-a43c3c58-w-0. Make sure the operation or function is registered in the binary running in this process.
2020-08-01 18:35:40.194364: W tensorflow/core/distributed_runtime/eager/remote_tensor_handle_data.cc:76] Unable to destroy remote tensor handles. If you are running a tf.function, it usually indicates some op in the graph gets an error: 'DummySeedGenerator' is neither a type of a primitive operation nor a name of a function registered in binary running on n-a43c3c58-w-0. Make sure the operation or function is registered in the binary running in this process.
2020-08-01 18:35:40.195337: W ./tensorflow/core/distributed_runtime/eager/destroy_tensor_handle_node.h:57] Ignoring an error encountered when deleting remote tensors handles: Invalid argument: Unable to find the relevant tensor remote_handle: Op ID: 6815, Output num: 0
Additional GRPC error information from remote target /job:worker/replica:0/task:0:
:{"created":"@1596306940.195137527","description":"Error received from peer ipv4:10.102.83.42:8470","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Unable to find the relevant tensor remote_handle: Op ID: 6815, Output num: 0","grpc_status":3}
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/tpu_strategy.py", line 540, in async_wait
    context.async_wait()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/context.py", line 2319, in async_wait
    context().sync_executors()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/context.py", line 658, in sync_executors
    pywrap_tfe.TFE_ContextSyncExecutors(self._context_handle)
tensorflow.python.framework.errors_impl.NotFoundError: 'DummySeedGenerator' is neither a type of a primitive operation nor a name of a function registered in binary running on n-a43c3c58-w-0. Make sure the operation or function is registered in the binary running in this process.

**Comment by Saduf2019** [comment]
@IOTpreneur 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]
