### ISSUE TITLE
Fail to load model from ModelCheckpoint in java.

### ISSUE THREAD

**Issue by jimmy6** [tensorflow/tensorflow#42060]
Fail to load model in java.

**Python**
checkpoint = ModelCheckpoint(weight_path, monitor='val_loss', verbose=1, 
                             save_best_only=True, mode='min', save_weights_only = True)
**Java**
SavedModelBundle model = SavedModelBundle.load("C:\\workspace\\tools\\cross-360p-high2Tp1Cl100VpConc.1.09.hdf5", "serve" );	

**System information**
libtensorflow-2.3.0.jar

**Other info / logs**
2020-08-05 21:17:29.484400: I tensorflow/cc/saved_model/reader.cc:31] Reading SavedModel from: C:\workspace\tools\cross-360p-high2Tp1Cl100VpConc.1.09.hdf5
2020-08-05 21:17:29.484980: I tensorflow/cc/saved_model/loader.cc:311] SavedModel load for tags { serve }; Status: fail. Took 554 microseconds.
Exception in thread "main" org.tensorflow.TensorFlowException: Could not find SavedModel .pb or .pbtxt at supplied export directory path: C:\workspace\tools\cross-360p-high2Tp1Cl100VpConc.1.09.hdf5
	at org.tensorflow.SavedModelBundle.load(Native Method)
	at org.tensorflow.SavedModelBundle.access$000(SavedModelBundle.java:27)
	at org.tensorflow.SavedModelBundle$Loader.load(SavedModelBundle.java:32)
	at org.tensorflow.SavedModelBundle.load(SavedModelBundle.java:95)
	at com.TensorFlowEngine.main(TensorFlowEngine.java:9)

**Comment by ravikyram** [comment]
@jimmy6

Request you to fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).
Can you please share  complete code snippet to reproduce the issue in our environment.Thanks!

**Comment by jimmy6** [comment]
This link show how ModelCheckpoint coded.
https://github.com/jimmy6/j6stock-deeplearning/blob/master/Transformer_1D-CNN_Feature_Extraction/xau_usd_OHLCTail2Tp1Cl100VpConc0_4801Vl-TF2.2.ipynb

**Comment by ymodak** [comment]
From the stack trace it says `Could not find SavedModel .pb or .pbtxt at supplied export`.
Can you confirm if you have those files in your export?
Thanks!

**Comment by jimmy6** [comment]
It should be able to read h5 or .hdf5 right?

**Comment by ymodak** [comment]
You are required to have your model in SavedModel format.
See https://www.tensorflow.org/guide/saved_model#the_savedmodel_format_on_disk
Currently you are saving your model in `h5` whereas `SavedModelBundel.load()` is searching for an export directory containing SavedModel.pb
See https://www.tensorflow.org/api_docs/java/org/tensorflow/SavedModelBundle#public-static-savedmodelbundle-load-string-exportdir,-string...-tags
