### ISSUE TITLE
multi worker in nccl mode with something wrong

### ISSUE THREAD

**Issue by ImMrMa** [tensorflow/tensorflow#42062]
System information

Have I written custom code (as opposed to using a stock example script provided in TensorFlow):N/A
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
TensorFlow installed from (source or binary): Binary
TensorFlow version (use command below): 2.3.0
Python version: 3.7.4
Bazel version (if compiling from source): N/A
GCC/Compiler version (if compiling from source): N/A
CUDA/cuDNN version: 10.1.243/N
GPU model and memory: V100 32GB

I just run a sample code with keras training api  in NCCL multi worker mode with 2*8V100gpus.
Sometimes I the training process with failed with this error. But sometimes not, and the training process is same as before.

Here is the error information:

>`2020-08-05 20:21:04.420413: E tensorflow/core/common_runtime/ring_alg.cc:274] Aborting RingReduce with Invalid argument: [_Derived_]indices[4] = 14 is not in [0, 14)
	 [[{{node GatherV2}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNextAsOptional_3]]
	 [[GroupCrossDeviceControlEdges_3/div_no_nan/_619]]
Additional GRPC error information from remote target /job:worker/replica:0/task:0:
:{"created":"@1596630064.420329728","description":"Error received from peer ipv4:10.128.98.77:9000","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"[_Derived_]indices[4] = 14 is not in [0, 14)\n\t [[{{node GatherV2}}]]\n\t [[MultiDeviceIteratorGetNextFromShard]]\n\t [[RemoteCall]]\n\t [[IteratorGetNextAsOptional_3]]\n\t [[GroupCrossDeviceControlEdges_3/div_no_nan/_619]]","grpc_status":3}
2020-08-05 20:21:04.420665: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at collective_ops.cc:257 : Invalid argument: [_Derived_]indices[4] = 14 is not in [0, 14)
	 [[{{node GatherV2}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNextAsOptional_3]]
	 [[GroupCrossDeviceControlEdges_3/div_no_nan/_619]]
Additional GRPC error information from remote target /job:worker/replica:0/task:0:
:{"created":"@1596630064.420329728","description":"Error received from peer ipv4:10.128.98.77:9000","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"[_Derived_]indices[4] = 14 is not in [0, 14)\n\t [[{{node GatherV2}}]]\n\t [[MultiDeviceIteratorGetNextFromShard]]\n\t [[RemoteCall]]\n\t [[IteratorGetNextAsOptional_3]]\n\t [[GroupCrossDeviceControlEdges_3/div_no_nan/_619]]","grpc_status":3}
Traceback (most recent call last):
  File "/opt/tiger/mta/scripts/keras/../../scripts/keras/train_model.py", line 115, in <module>
    main(args)
  File "/opt/tiger/mta/scripts/keras/../../scripts/keras/train_model.py", line 110, in main
    trainer.fit(task_index,num_devices)
  File "/opt/tiger/mta/mta/keras/trainer.py", line 170, in fit
    steps_per_epoch=self._config.train.steps_per_epoch,verbose=self._config.train.verbose_mode,callbacks=[CusCallBack(self._config,task_index,self._lr_scheduler,num_devices),self._ckpt_callback])
  File "/home/tiger/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 117, in _method_wrapper
    mode=dc.CoordinatorMode.INDEPENDENT_WORKER)
  File "/home/tiger/.local/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_coordinator.py", line 860, in run_distribute_coordinator
    task_id, session_config, rpc_layer)
  File "/home/tiger/.local/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_coordinator.py", line 360, in _run_single_worker
    return worker_fn(strategy)
  File "/home/tiger/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 115, in <lambda>
    lambda _: method(self, *args, **kwargs),
  File "/home/tiger/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1098, in fit
    tmp_logs = train_function(iterator)
  File "/home/tiger/.local/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/home/tiger/.local/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 807, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/home/tiger/.local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/tiger/.local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/home/tiger/.local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/tiger/.local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/home/tiger/.local/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  [_Derived_]indices[4] = 14 is not in [0, 14)
	 [[{{node GatherV2}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNextAsOptional_3]]
	 [[GroupCrossDeviceControlEdges_3/div_no_nan/_619]]
Additional GRPC error information from remote target /job:worker/replica:0/task:0:
:{"created":"@1596630064.420329728","description":"Error received from peer ipv4:10.128.98.77:9000","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"[_Derived_]indices[4] = 14 is not in [0, 14)\n\t [[{{node GatherV2}}]]\n\t [[MultiDeviceIteratorGetNextFromShard]]\n\t [[RemoteCall]]\n\t [[IteratorGetNextAsOptional_3]]\n\t [[GroupCrossDeviceControlEdges_3/div_no_nan/_619]]","grpc_status":3}
	 [[allreduce/CollectiveReduce]]
	 [[replica_4/Size_3/_270]] [Op:__inference_train_function_116225]

Function call stack:`
I will be grateful if anyone who help me save the problem.

**Comment by amahendrakar** [comment]
@ImMrMa,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!
