### ISSUE TITLE
Building Tensorflow Lite Locally :  Unrecoverable error while evaluating node 

### ISSUE THREAD

**Issue by amitDaMan** [tensorflow/tensorflow#42064]
I am building on Linux Ubuntu 16.04, and following the Android quickstart guide:
https://www.tensorflow.org/lite/guide/android

I build the image with the given DockerFile:
https://raw.githubusercontent.com/tensorflow/tensorflow/master/tensorflow/tools/dockerfiles/tflite-android.Dockerfile
docker build . -t tflite-builder -f tflite-android.Dockerfile

I run it with the following command:

docker run -it -w /tensorflow_src -v $PWD:/mnt -e HOST_PERMS="$(id -u):$(id -g)" \
    tensorflow/tensorflow:devel bash

Additional android tools in the container:
android update sdk --no-ui -a --filter tools,platform-tools,android-${ANDROID_API_LEVEL},build-tools-${ANDROID_BUILD_TOOLS_VERSION}

and finally the build command in bazel:
bazel build -c opt --fat_apk_cpu=x86,x86_64,arm64-v8a,armeabi-v7a \
  --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
  //tensorflow/lite/java:tensorflow-lite

giving error:
FAILED: Build did NOT complete successfully (65 packages loaded, 1078 targets configured)
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '@bazel_tools//src/tools/android/java/com/google/devtools/build/android/incrementaldeployment:incremental_stub_application BuildConfigurationValue.Key[291c4977886154b7d32d07c6d0dba1da3dce0bb2e69fd7a43e21c0fea58a22d0] false' (requested by nodes '@bazel_tools//tools/android:incremental_stub_application BuildConfigurationValue.Key[291c4977886154b7d32d07c6d0dba1da3dce0bb2e69fd7a43e21c0fea58a22d0] false')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:515)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at com.google.devtools.build.lib.rules.android.BusyBoxActionBuilder.addAapt(BusyBoxActionBuilder.java:315)
        at com.google.devtools.build.lib.rules.android.AndroidResourcesProcessorBuilder.createAapt2ApkAction(AndroidResourcesProcessorBuilder.java:279)
        at com.google.devtools.build.lib.rules.android.AndroidResourcesProcessorBuilder.build(AndroidResourcesProcessorBuilder.java:208)
        at com.google.devtools.build.lib.rules.android.AndroidResourcesProcessorBuilder.buildWithoutLocalResources(AndroidResourcesProcessorBuilder.java:179)
        at com.google.devtools.build.lib.rules.android.ResourceApk.processFromTransitiveLibraryData(ResourceApk.java:328)
        at com.google.devtools.build.lib.rules.android.AndroidLibrary.create(AndroidLibrary.java:178)
        at com.google.devtools.build.lib.rules.android.AndroidLibrary.create(AndroidLibrary.java:42)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:484)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:190)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:888)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:899)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:338)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
        ... 7 more
java.lang.RuntimeException: Unrecoverable error while evaluating node '@bazel_tools//src/tools/android/java/com/google/devtools/build/android/incrementaldeployment:incremental_stub_application BuildConfigurationValue.Key[291c4977886154b7d32d07c6d0dba1da3dce0bb2e69fd7a43e21c0fea58a22d0] false' (requested by nodes '@bazel_tools//tools/android:incremental_stub_application BuildConfigurationValue.Key[291c4977886154b7d32d07c6d0dba1da3dce0bb2e69fd7a43e21c0fea58a22d0] false')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:515)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at com.google.devtools.build.lib.rules.android.BusyBoxActionBuilder.addAapt(BusyBoxActionBuilder.java:315)
        at com.google.devtools.build.lib.rules.android.AndroidResourcesProcessorBuilder.createAapt2ApkAction(AndroidResourcesProcessorBuilder.java:279)
        at com.google.devtools.build.lib.rules.android.AndroidResourcesProcessorBuilder.build(AndroidResourcesProcessorBuilder.java:208)
        at com.google.devtools.build.lib.rules.android.AndroidResourcesProcessorBuilder.buildWithoutLocalResources(AndroidResourcesProcessorBuilder.java:179)
        at com.google.devtools.build.lib.rules.android.ResourceApk.processFromTransitiveLibraryData(ResourceApk.java:328)
        at com.google.devtools.build.lib.rules.android.AndroidLibrary.create(AndroidLibrary.java:178)
        at com.google.devtools.build.lib.rules.android.AndroidLibrary.create(AndroidLibrary.java:42)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:484)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:190)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:888)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:899)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:338)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
FAILED: Build did NOT complete successfully (65 packages loaded, 1078 targets configured)

**Comment by amitDaMan** [comment]
Additional Information: I was able to successfully build the C++ shared libraries with command:
bazel build -c opt --config=android_arm64 //tensorflow/lite:libtensorflowlite.so

**Comment by amitDaMan** [comment]
Any update?

**Comment by terryheo** [comment]
Did you run "./configure" to configure Android SDK and NDK?

**Comment by amitDaMan** [comment]
As illustrated above I am using a dockerfile from the Android quickstart: 
https://raw.githubusercontent.com/tensorflow/tensorflow/master/tensorflow/tools/dockerfiles/tflite-android.Dockerfile

Therefore this bit of infrastructure is taken care of without the need for ./configure 

Heres the guide again:
https://www.tensorflow.org/lite/guide/android#build_tensorflow_lite_locally

**Comment by amitDaMan** [comment]
any sort of input on this

**Comment by Vincent-bin** [comment]
I got the same issue here, did you fix it?

**Comment by ichisadashioko** [comment]
I tracked down when the guide was written. It was about [more than a year ago](https://github.com/tensorflow/tensorflow/commit/fce56a775dfde2a4465888d26ab705e713af5968#diff-f03969229b47807f413de9b51492d8312c1f172a25be052fa9ccd412e2beeae6) so the instructions may not work with current latest docker image (`tensorflow/tensorflow:devel`) and codebase. I will try to use an image published around the time of writing to see if we can build TensorFlow Lite with the instructions.

**Comment by ichisadashioko** [comment]
The instructions for building with Docker was only added around June this year. I tried to pull a Docker image from a year ago but there was no `tensorflow_src` in that image.

**Comment by terryheo** [comment]
You can find updated doc here.
https://www.tensorflow.org/lite/guide/build_android
There is a step to download Docker file.

**Comment by ichisadashioko** [comment]
@terryheo Was you able to reproduce a successful build with the instructions? Was the Docker file updated recently (during 2 days ago)?

I just tried to build TensorFlow Lite again with that Docker file but it is still failing as reported in this issue.

**Comment by thaink** [comment]
@amitDaMan As I understand, you can build it successfully locally but fail with docker?

**Comment by thaink** [comment]
I was able to reproduce this issue. However, the error is gone after running ./configure with configuration for Android builds under /tensorflow_src
The ./configure add some flags needed for bazel so please run it even you are using docker.

Besides, if you would like to reduce the binary size, I would recommend to take a look at https://www.tensorflow.org/lite/guide/reduce_binary_size

**Comment by thaink** [comment]
Closing this issue here. Feel free to reopen it if you still face this error after running ./configure.
