### ISSUE TITLE
File "/home/ray/anaconda3/envs/tf1/lib/python3.8/site-packages/tensorflow/python/feature_column/dense_features.py", line 30, in <module>     class DenseFeatures(fc._BaseFeaturesLayer):  # pylint: disable=protected-access AttributeError: module 'tensorflow.python.feature_column.feature_column_v2' has no attribute '_BaseFeaturesLayer'

### ISSUE THREAD

**Issue by raydjr** [tensorflow/tensorflow#42080]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version: 2.3.0
- Python version: 3.8.3
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA 11.0 / cuDNN 7.6.5
- GPU model and memory: RTX 2070 super

**Describe the problem**
Can not run tensorboard
**Provide the exact sequence of commands / steps that you executed before running into the problem**
conda activate tf1 #(where I have tensor installed)
pip install -U tensorboard
tensorboard --logdir=models/my_ssd_resnet50_v1_fpn
tensorboard dev --help  #(doesn't work either, gives error narrowed down to title) 

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

2020-08-05 18:01:41.991550: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "/home/ray/anaconda3/envs/tf1/bin/tensorboard", line 5, in <module>
    from tensorboard.main import run_main
  File "/home/ray/anaconda3/envs/tf1/lib/python3.8/site-packages/tensorboard/main.py", line 43, in <module>
    from tensorboard import default
  File "/home/ray/anaconda3/envs/tf1/lib/python3.8/site-packages/tensorboard/default.py", line 40, in <module>
    from tensorboard.plugins.beholder import beholder_plugin_loader
  File "/home/ray/anaconda3/envs/tf1/lib/python3.8/site-packages/tensorboard/plugins/beholder/__init__.py", line 22, in <module>
    from tensorboard.plugins.beholder.beholder import Beholder
  File "/home/ray/anaconda3/envs/tf1/lib/python3.8/site-packages/tensorboard/plugins/beholder/beholder.py", line 225, in <module>
    class BeholderHook(tf.estimator.SessionRunHook):
  File "/home/ray/anaconda3/envs/tf1/lib/python3.8/site-packages/tensorflow/python/util/lazy_loader.py", line 62, in __getattr__
    module = self._load()
  File "/home/ray/anaconda3/envs/tf1/lib/python3.8/site-packages/tensorflow/python/util/lazy_loader.py", line 45, in _load
    module = importlib.import_module(self.__name__)
  File "/home/ray/anaconda3/envs/tf1/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/ray/anaconda3/envs/tf1/lib/python3.8/site-packages/tensorflow_estimator/__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1 import estimator
  File "/home/ray/anaconda3/envs/tf1/lib/python3.8/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1.estimator import experimental
  File "/home/ray/anaconda3/envs/tf1/lib/python3.8/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py", line 10, in <module>
    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder
  File "/home/ray/anaconda3/envs/tf1/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py", line 23, in <module>
    from tensorflow.python.feature_column import dense_features
  File "/home/ray/anaconda3/envs/tf1/lib/python3.8/site-packages/tensorflow/python/feature_column/dense_features.py", line 30, in <module>
    class DenseFeatures(fc._BaseFeaturesLayer):  # pylint: disable=protected-access
AttributeError: module 'tensorflow.python.feature_column.feature_column_v2' has no attribute '_BaseFeaturesLayer'

**Comment by amahendrakar** [comment]
@raydjr,
Issues related to Tensorboard are tracked in the Tensorboard repo. Please submit a new issue from [this link](https://github.com/tensorflow/tensorboard/issues/new/choose) and fill in the template,so that we can track the issue there. Thanks!
