### ISSUE TITLE
[ROCm] Cannot find rocm library hip_hcc

### ISSUE THREAD

**Issue by acxz** [tensorflow/tensorflow#42081]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.3.0
- Python version: 3.8.5
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): 3.4.1
- GCC/Compiler version (if compiling from source): 10.1.0
- CUDA/cuDNN version: N/A
- ROCm version: 3.5.0
- GPU model and memory:

**Describe the problem**

When building I am getting the following error:
```
Repository rule rocm_configure defined at:
  /home/acxz/vcs/git/github/rocm-arch/tensorflow-rocm/src/tensorflow-2.2.0-rocm/third_party/gpus/rocm_configure.bzl:861:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_rocm':
   Traceback (most recent call last):
	File "/home/acxz/vcs/git/github/rocm-arch/tensorflow-rocm/src/tensorflow-2.2.0-rocm/third_party/gpus/rocm_configure.bzl", line 840
		_create_local_rocm_repository(<1 more arguments>)
	File "/home/acxz/vcs/git/github/rocm-arch/tensorflow-rocm/src/tensorflow-2.2.0-rocm/third_party/gpus/rocm_configure.bzl", line 647, in _create_local_rocm_repository
		_find_libs(repository_ctx, <2 more arguments>)
	File "/home/acxz/vcs/git/github/rocm-arch/tensorflow-rocm/src/tensorflow-2.2.0-rocm/third_party/gpus/rocm_configure.bzl", line 449, in _find_libs
		_select_rocm_lib_paths(<3 more arguments>)
	File "/home/acxz/vcs/git/github/rocm-arch/tensorflow-rocm/src/tensorflow-2.2.0-rocm/third_party/gpus/rocm_configure.bzl", line 418, in _select_rocm_lib_paths
		auto_configure_fail(<1 more arguments>)
	File "/home/acxz/vcs/git/github/rocm-arch/tensorflow-rocm/src/tensorflow-2.2.0-rocm/third_party/gpus/rocm_configure.bzl", line 162, in auto_configure_fail
		fail(<1 more arguments>)

ROCm Configuration Error: Cannot find rocm library hip_hcc
INFO: Repository com_google_protobuf instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule tf_http_archive defined at:
  /home/acxz/vcs/git/github/rocm-arch/tensorflow-rocm/src/tensorflow-2.2.0-rocm/third_party/repo.bzl:134:34: in <toplevel>
ERROR: Skipping '//tensorflow:install_headers': no such package '@local_config_rocm//rocm': Traceback (most recent call last):
	File "/home/acxz/vcs/git/github/rocm-arch/tensorflow-rocm/src/tensorflow-2.2.0-rocm/third_party/gpus/rocm_configure.bzl", line 840
		_create_local_rocm_repository(<1 more arguments>)
	File "/home/acxz/vcs/git/github/rocm-arch/tensorflow-rocm/src/tensorflow-2.2.0-rocm/third_party/gpus/rocm_configure.bzl", line 647, in _create_local_rocm_repository
		_find_libs(repository_ctx, <2 more arguments>)
	File "/home/acxz/vcs/git/github/rocm-arch/tensorflow-rocm/src/tensorflow-2.2.0-rocm/third_party/gpus/rocm_configure.bzl", line 449, in _find_libs
		_select_rocm_lib_paths(<3 more arguments>)
	File "/home/acxz/vcs/git/github/rocm-arch/tensorflow-rocm/src/tensorflow-2.2.0-rocm/third_party/gpus/rocm_configure.bzl", line 418, in _select_rocm_lib_paths
		auto_configure_fail(<1 more arguments>)
	File "/home/acxz/vcs/git/github/rocm-arch/tensorflow-rocm/src/tensorflow-2.2.0-rocm/third_party/gpus/rocm_configure.bzl", line 162, in auto_configure_fail
		fail(<1 more arguments>)

ROCm Configuration Error: Cannot find rocm library hip_hcc
ERROR: no such package '@local_config_rocm//rocm': Traceback (most recent call last):
	File "/home/acxz/vcs/git/github/rocm-arch/tensorflow-rocm/src/tensorflow-2.2.0-rocm/third_party/gpus/rocm_configure.bzl", line 840
		_create_local_rocm_repository(<1 more arguments>)
	File "/home/acxz/vcs/git/github/rocm-arch/tensorflow-rocm/src/tensorflow-2.2.0-rocm/third_party/gpus/rocm_configure.bzl", line 647, in _create_local_rocm_repository
		_find_libs(repository_ctx, <2 more arguments>)
	File "/home/acxz/vcs/git/github/rocm-arch/tensorflow-rocm/src/tensorflow-2.2.0-rocm/third_party/gpus/rocm_configure.bzl", line 449, in _find_libs
		_select_rocm_lib_paths(<3 more arguments>)
	File "/home/acxz/vcs/git/github/rocm-arch/tensorflow-rocm/src/tensorflow-2.2.0-rocm/third_party/gpus/rocm_configure.bzl", line 418, in _select_rocm_lib_paths
		auto_configure_fail(<1 more arguments>)
	File "/home/acxz/vcs/git/github/rocm-arch/tensorflow-rocm/src/tensorflow-2.2.0-rocm/third_party/gpus/rocm_configure.bzl", line 162, in auto_configure_fail
		fail(<1 more arguments>)

ROCm Configuration Error: Cannot find rocm library hip_hcc
INFO: Elapsed time: 5.658s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow ... (2 packages)
==> ERROR: A failure occurred in build().
    Aborting...
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

1. git clone
2. `export TF_NEED_ROCM=1`
3. `./configure`
4. 
```
  bazel \
        build --config=mkl --config=avx2_linux -c opt \
          //tensorflow:libtensorflow.so \
          //tensorflow:libtensorflow_cc.so \
          //tensorflow:install_headers \
          //tensorflow/tools/pip_package:build_pip_package
      bazel-bin/tensorflow/tools/pip_package/build_pip_package --gpu "${srcdir}"/tmpoptrocm
```

To be exactly precise I am using the following build script (PKGBUILD):
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=tensorflow-rocm

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Downstream issue: https://github.com/rocm-arch/tensorflow-rocm/issues/5

**Comment by ravikyram** [comment]
@acxz 

Can you please refer similar issue #27352 and see if it helps you.Thanks!

**Comment by acxz** [comment]
Although the issue there is similar, that issue is not helpful since it does not provide a solution to the problem just tries to go around it by saying use docker and post issue at the tensorflow-rocm repo (a corresponding issue wasn't posted either)

**Comment by acxz** [comment]
I opened up the following PR which resolves this for Arch Linux users. https://github.com/tensorflow/tensorflow/pull/42095

Let's have it go through the CI so that we can ensure it also works for other build configurations.
