### ISSUE TITLE
ImportError: DLL load failed with error code 3221225501 while importing _pywrap_ tensorflow_internal in Python3.8

### ISSUE THREAD

**Issue by AIabdoPr** [tensorflow/tensorflow#42103]
<em>How i can solve this error while import TensorFlow</em>

**System information:**
 - Python 3.8.4.
 - Windows 7 Ultimate 64bit.
 - 2GB Ram.
 - Intel(R) Celeron(R) CPU N2840 @ 2.16GHz.
 - Intel(R) HD Graphics.

**Error Text/Logs:**
```
>>> import tensorflow as tf
Traceback (most recent call last):
  File "G:\Users\Abdo-Prgraming\AppData\Roaming\Python\Python38\site-packages\te
nsorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed with error code 3221225501 while importing _pywrap_
tensorflow_internal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "G:\Users\Abdo-Prgraming\AppData\Roaming\Python\Python38\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "G:\Users\Abdo-Prgraming\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "G:\Users\Abdo-Prgraming\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "G:\Users\Abdo-Prgraming\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "G:\Users\Abdo-Prgraming\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "G:\Users\Abdo-Prgraming\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed with error code 3221225501 while importing _pywrap_tensorflow_internal


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by ravikyram** [comment]
@AIabdoPr 

What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)

TF Version >= 1.13 requires CUDA 10.0 and TF Version < 1.13 (till TF 1.5) requires CUDA 9.0.

If you have above configuration and using Windows platform -
Try adding the CUDA, CUPTI, and cuDNN installation directories to the %PATH% environment variable.
Refer windows [setup guide](https://www.tensorflow.org/install/gpu#windows_setup).

**Comment by ravikyram** [comment]
@AIabdoPr 

 I guess this is an issue with mixing two or more versions.

1.Check multiple tensorflow folder under 'site-packages/` folder and delete them
2.check environmental file and check for path system variable, if the path are not pointing to correct version of software (python), then adjust accordingly
3.Uninstalled tensorflow-->uninstalled python-->restart computer
4. python--> set and check system variables in the environmental file
5.install TF and then check whether everything is working as expected or not.

Also, i guess this issue you might not have faced with python 3.7 or 3.6.Can you please see whether you are facing this issue with python 3.6 , 3.7 also or only with python 3.8 

Thanks!

**Comment by naoualberbiche** [comment]
How i can solve this error while import TensorFlow

(TF_PY) C:\Users\hp>python -c "import tensorflow as tf;print(tf.reduce_sum(tf.ra
ndom.normal([1000, 1000])))"
Traceback (most recent call last):
  File "C:\Users\hp\anaconda3\envs\TF_PY\lib\site-packages\tensorflow\python\pyw
rap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: Le module spécifié est introuvable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\hp\anaconda3\envs\TF_PY\lib\site-packages\tensorflow\__init__.p
y", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\hp\anaconda3\envs\TF_PY\lib\site-packages\tensorflow\python\__i
nit__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\hp\anaconda3\envs\TF_PY\lib\site-packages\tensorflow\python\eag
er\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "C:\Users\hp\anaconda3\envs\TF_PY\lib\site-packages\tensorflow\python\pyw
rap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\hp\anaconda3\envs\TF_PY\lib\site-packages\tensorflow\python\pyw
rap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\hp\anaconda3\envs\TF_PY\lib\site-packages\tensorflow\python\pyw
rap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: Le module spécifié est introuvable.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
