### ISSUE TITLE
tf.keras.models.load_model unable to load model in TF 2.3.0 - "int() argument must be a string, a bytes-like object or a number, not 'NoneType' "

### ISSUE THREAD

**Issue by adityapaul** [tensorflow/tensorflow#42106]
My first time posting a GitHub issue, so excuse me if I leave something out.

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mac OSX 10.12.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
Binary
- TensorFlow version (use command below):
2.3.0
- Python version:
3.7

**Describe the current behavior**
Every time I call `tf.keras.models.load_model` on my SavedModel in version 2.3.0, the model fails to load. I had saved the model with tensorflow 2.0.0 installed, and I could load it with 2.0.0, but when I upgraded to 2.3.0, I got the following error:

```python
Traceback (most recent call last):
  File "../python/recommender.py", line 501, in <module>
    new_topics=args.new_topic_path)
  File "../python/recommender.py", line 51, in load_data
    add_to_matrix(tdf, vdf, save_matrix, corr_matrix, new_values, new_topics)
  File "../python/recommender.py", line 352, in add_to_matrix
    df2 = get_corrs(ntdf, vdf)
  File "../python/recommender.py", line 401, in get_corrs
    model = load_model(model_dir, None)
  File "/Users/aditya/Documents/Internships/phoenix/recommender/venv/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py", line 187, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "/Users/aditya/Documents/Internships/phoenix/recommender/venv/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 121, in load
    path, options=options, loader_cls=KerasObjectLoader)
  File "/Users/aditya/Documents/Internships/phoenix/recommender/venv/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 633, in load_internal
    ckpt_options)
  File "/Users/aditya/Documents/Internships/phoenix/recommender/venv/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 194, in __init__
    super(KerasObjectLoader, self).__init__(*args, **kwargs)
  File "/Users/aditya/Documents/Internships/phoenix/recommender/venv/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 130, in __init__
    self._load_all()
  File "/Users/aditya/Documents/Internships/phoenix/recommender/venv/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 215, in _load_all
    self._layer_nodes = self._load_layers()
  File "/Users/aditya/Documents/Internships/phoenix/recommender/venv/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 315, in _load_layers
    layers[node_id] = self._load_layer(proto.user_object, node_id)
  File "/Users/aditya/Documents/Internships/phoenix/recommender/venv/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 341, in _load_layer
    obj, setter = self._revive_from_config(proto.identifier, metadata, node_id)
  File "/Users/aditya/Documents/Internships/phoenix/recommender/venv/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 359, in _revive_from_config
    self._revive_layer_from_config(metadata, node_id))
  File "/Users/aditya/Documents/Internships/phoenix/recommender/venv/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 445, in _revive_layer_from_config
    built = self._try_build_layer(obj, node_id, build_input_shape)
  File "/Users/aditya/Documents/Internships/phoenix/recommender/venv/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 482, in _try_build_layer
    obj.build(build_input_shape)
  File "/Users/aditya/Documents/Internships/phoenix/recommender/venv/lib/python3.7/site-packages/tensorflow/python/keras/layers/wrappers.py", line 685, in build
    self.forward_layer.build(input_shape)
  File "/Users/aditya/Documents/Internships/phoenix/recommender/venv/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 581, in build
    self.cell.build(step_input_shape)
  File "/Users/aditya/Documents/Internships/phoenix/recommender/venv/lib/python3.7/site-packages/tensorflow/python/keras/utils/tf_utils.py", line 323, in wrapper
    output_shape = fn(instance, input_shape)
  File "/Users/aditya/Documents/Internships/phoenix/recommender/venv/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 2367, in build
    caching_device=default_caching_device)
  File "/Users/aditya/Documents/Internships/phoenix/recommender/venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 614, in add_weight
    caching_device=caching_device)
  File "/Users/aditya/Documents/Internships/phoenix/recommender/venv/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 750, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "/Users/aditya/Documents/Internships/phoenix/recommender/venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 145, in make_variable
    shape=variable_shape if variable_shape else None)
  File "/Users/aditya/Documents/Internships/phoenix/recommender/venv/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 260, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/Users/aditya/Documents/Internships/phoenix/recommender/venv/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 221, in _variable_v1_call
    shape=shape)
  File "/Users/aditya/Documents/Internships/phoenix/recommender/venv/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 199, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/Users/aditya/Documents/Internships/phoenix/recommender/venv/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py", line 2597, in default_variable_creator
    shape=shape)
  File "/Users/aditya/Documents/Internships/phoenix/recommender/venv/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 264, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/Users/aditya/Documents/Internships/phoenix/recommender/venv/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1518, in __init__
    distribute_strategy=distribute_strategy)
  File "/Users/aditya/Documents/Internships/phoenix/recommender/venv/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1651, in _init_from_args
    initial_value() if init_from_fn else initial_value,
  File "/Users/aditya/Documents/Internships/phoenix/recommender/venv/lib/python3.7/site-packages/tensorflow/python/keras/initializers/initializers_v2.py", line 397, in __call__
    return super(VarianceScaling, self).__call__(shape, dtype=_get_dtype(dtype))
  File "/Users/aditya/Documents/Internships/phoenix/recommender/venv/lib/python3.7/site-packages/tensorflow/python/ops/init_ops_v2.py", line 545, in __call__
    fan_in, fan_out = _compute_fans(scale_shape)
  File "/Users/aditya/Documents/Internships/phoenix/recommender/venv/lib/python3.7/site-packages/tensorflow/python/ops/init_ops.py", line 1425, in _compute_fans
    return int(fan_in), int(fan_out)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Describe the expected behavior**
Ideally, I should be able to load up my model and just use it from there.

**Standalone code to reproduce the issue**
I could reproduce this with the model in [model.zip](https://github.com/tensorflow/tensorflow/files/5037874/model.zip) and with the following code:

```bash
python3
>>> import tensorflow as tf
>>> tf.keras.models.load_model('model/');
```

**Comment by bhack** [comment]
I have not analyzed your model but can you verify if it is compliant with `saved_model` [documented compatibility constrains](https://www.tensorflow.org/guide/versions#compatibility_of_savedmodels_graphs_and_checkpoints)?

**Comment by adityapaul** [comment]
@bhack how would we go about finding the `GraphDef` version? I didn't use any deprecated APIs, so I'd assume that that's the problem, if it is indeed incompatiblity.

**Comment by bhack** [comment]
Also if you don't use deprecated or experimental API in your model as you are trying `2.0.0->2.3.0` you are not compliant with this constrain:
> Any SavedModel supported in TensorFlow major version N can be loaded and executed with TensorFlow major version N+1

**Comment by amahendrakar** [comment]
@adityapaul,
I was able to reproduce the issue. Facing an error while loading the model with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/9b4eae0b61ca33c70e4ccb0a68c470ea/42106-2-3.ipynb), whereas the code runs fine on [TF v2.0](https://colab.research.google.com/gist/amahendrakar/c022e29a8c2021eabd2d0ea575a96fd1/42106.ipynb). Please find the attached gist. 

In order to expedite the trouble-shooting process, could you please provide the code you had to used to build the model. Thanks!

**Comment by bhack** [comment]
Yes It could be useful to double check "non-deprecated, non-experimental, non-compatibility APIs"

**Comment by adityapaul** [comment]
@bhack Thanks! I'll take a look one more time to make sure I didn't use anything non-compatible. I could also load the model in TF 2.1, but got an error later in my code; it's probably something wrong with my code itself in that case, though.

@amahendrakar Here's the code that I used to train the model. Let me know if you need anything else!

```python
import tensorflow as tf

class LuongAttention(tf.keras.Model):
    def __init__(self, input_dim=max_len, att_type='dot'):
        super(LuongAttention, self).__init__()
        w_init = tf.random_normal_initializer()
        self.att_type = att_type
        self.W = tf.Variable(
            initial_value = np.identity(input_dim, dtype='float32'),
            trainable=False
        )
        self.WLayer = tf.keras.layers.Dense(input_dim, 
                                           kernel_regularizer=tf.keras.regularizers.l2(0.01))
        if self.att_type == 'general':
            self.W = tf.Variable(
                initial_value=w_init(shape=(input_dim, input_dim), dtype="float32"),
                trainable=True
            )
        self.loss = 1e-5 * tf.nn.l2_loss(self.W)
    def call(self, inputs):
        self.add_loss(self.loss)
        if self.att_type == 'concat':
            score = tf.matmul(inputs[0], self.WLayer(inputs[1]), transpose_b=True)
            alignment = tf.nn.softmax(score, axis=2)
        else:
            score = tf.matmul(self.W, inputs[1])
            score = tf.matmul(inputs[0], score, transpose_b=True)
            alignment = tf.nn.softmax(score, axis=2)
        return alignment

# Build the model
from tensorflow.keras.layers import Input, Embedding, Bidirectional, LSTM, Attention
from tensorflow.keras.layers import Dense, Concatenate, Reshape
from tensorflow.keras.activations import linear
from tensorflow.keras.regularizers import l1, l2, l1_l2
from tensorflow.keras.models import Model

in1 = Input((max_len,))
in2 = Input((max_len,))

emb = Embedding(len(tokenizer.word_index) + 1, 
                embedding_dim, 
                input_length=max_len)
if use_embedding: 
    emb = Embedding(len(tokenizer.word_index) + 1, 
                    embedding_dim, 
                    weights=[embedding_matrix],
                    input_length=max_len, 
                    trainable=emb_trainable)

# First sequence branch
branch1 = emb(in1)
branch1l = Bidirectional(LSTM(25, 
                              activation='elu', 
                              return_sequences=True, 
                              kernel_regularizer=l2(0.01)))(branch1)

# Second sequence branch
branch2 = emb(in2)
branch2l = Bidirectional(LSTM(25, 
                              activation='elu', 
                              return_sequences=True, 
                              kernel_regularizer=l2(0.01)))(branch2)

# Concatenate with Luong attention (eventually add word embedding as value)
attention1 = LuongAttention(input_dim=max_len, 
                            att_type='general')([branch1, branch2])
attention2 = LuongAttention(input_dim=max_len, 
                            att_type='general')([branch1l, branch2l])
concat = Concatenate(axis=-1)([attention1, attention2])

# Process concatenated output
out = Bidirectional(LSTM(80, activation='elu', kernel_regularizer=l2(0.01)))(concat)
out = Dense(1, activation='sigmoid')(out)

model = Model(inputs=[in1, in2], outputs=[out])
model.compile(loss='mean_squared_error', 
              optimizer='adam', metrics=['mean_absolute_error'])
model.summary()

# Fit the model
from tensorflow.keras.callbacks import ReduceLROnPlateau

my_callbacks = [
    ReduceLROnPlateau(factor=0.25, mode="min")
]

history2 = model.fit([X_train[:, 0, :], X_train[:, 1, :]],
                    y_train, 
                    epochs=epochs, 
                    validation_split=0.2,
                    use_multiprocessing=True,
                    sample_weight=sample_weights,
                    callbacks=my_callbacks)
```

**Comment by sarthak3248** [comment]
@adityapaul  In the behaviour statement you have written "elu" instead of "relu" in the activation section !
This might help!

**Comment by adityapaul** [comment]
@sarthak3248 Hmmm, I had used ELU activations in the two models that were portable to TF 2.3, so I'm not too sure if that's the problem I'm facing. Thank you though!

**Comment by amahendrakar** [comment]
@sarthak3248,
On running the code, I am facing an error stating `NameError: name 'max_len' is not defined`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/1ad2d0ac60ece6190c4fe1f37b606cb8/42106.ipynb). 

Could you please provide the complete code and the dataset you are using to save the model? Thanks!

**Comment by adityapaul** [comment]
Sure. The full code is here:

```python
import csv
import pandas as pd
import numpy as np

# read in sentence dataset
with open('SICK.txt', 'r') as file:
    sdf = pd.read_table(file)

# re-edit scores so that it's a single relatedness measure
scoreAB = []
scoreBA = []
for pair in sdf.iterrows():
    if pair[1]['entailment_AB'] == 'A_entails_B':
        scoreAB.append(pair[1]['relatedness_score'] - 1)
    elif pair[1]['entailment_AB'] == 'A_neutral_B':
        scoreAB.append(pair[1]['relatedness_score'] - 3)
    else:
        scoreAB.append(1 - pair[1]['relatedness_score'])
    if pair[1]['entailment_BA'] == 'B_entails_A':
        scoreBA.append(pair[1]['relatedness_score'] - 1)
    elif pair[1]['entailment_BA'] == 'B_neutral_A':
        scoreBA.append(pair[1]['relatedness_score'] - 3)
    else:
        scoreBA.append(1 - pair[1]['relatedness_score'])
sdf['relatedness_score_AB'] = scoreAB
sdf['relatedness_score_BA'] = scoreBA

# define hyperparameters
vocab_size = None
oov_tok = '<OOV>'
max_len = 75
pad_pos = 'post'
trunc_pos = 'post'
embedding_dim = 50
epochs = 25
emb_trainable = False
use_embedding = True
dim_factor = 0.7
out_range = (0, 1)

# A little bit of preprocessing

# First, add beginning and end of string words
trim = lambda x: x #"<BOS> " + x + " <EOS>" if "<BOS>" not in x else x

sdf['sentence_A'] = sdf['sentence_A'].apply(trim)
sdf['sentence_B'] = sdf['sentence_B'].apply(trim)
sdf['sentence_A_original'] = sdf['sentence_A_original'].apply(trim)
sdf['sentence_B_original'] = sdf['sentence_B_original'].apply(trim)

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

tokenizer = Tokenizer(num_words=vocab_size, oov_token=oov_tok)
tokenizer.fit_on_texts(sdf['sentence_A'] + 
                       sdf['sentence_B'] + 
                       sdf['sentence_A_original'] + 
                       sdf['sentence_B_original'])
sa = tokenizer.texts_to_sequences(sdf['sentence_A'])
sb = tokenizer.texts_to_sequences(sdf['sentence_B'])
sao = tokenizer.texts_to_sequences(sdf['sentence_A_original'])
sbo = tokenizer.texts_to_sequences(sdf['sentence_B_original'])

sa = pad_sequences(sa, maxlen=max_len, padding=pad_pos, truncating=trunc_pos)
sb = pad_sequences(sb, maxlen=max_len, padding=pad_pos, truncating=trunc_pos)
sao = pad_sequences(sao, maxlen=max_len, padding=pad_pos, truncating=trunc_pos)
sbo = pad_sequences(sbo, maxlen=max_len, padding=pad_pos, truncating=trunc_pos)

# construct sentence dataset
ds_pairs = (sa, 
            sb, 
            sdf['relatedness_score_AB'])
orig_pairs = (sao, 
              sbo, 
              [dim_factor * x for x in sdf['relatedness_score_AB']])

# construct reversed semantic relationships
ds_pairs_reversed = (sb, 
                     sa, 
                     sdf['relatedness_score_BA'])
orig_pairs_reversed = (sbo,
                       sao,
                       [dim_factor * x for x in sdf['relatedness_score_BA']])

"""
uncomment to include reversed semantic relationships in dataset
"""
# ds_pairs = np.concatenate([ds_pairs, ds_pairs_reversed])
# orig_pairs = np.concatenate([orig_pairs, orig_pairs_reversed])

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

# set up
X_ds = np.transpose(np.array([ds_pairs[0], ds_pairs[1]]), axes=(1,0,2))
X_orig = np.transpose(np.array([orig_pairs[0], orig_pairs[1]]), axes=(1,0,2))
y_ds = np.array(ds_pairs[2])
y_orig = np.array(orig_pairs[2])

# normalize the output values for the sake of everything
scaler = MinMaxScaler(feature_range=out_range)
scaler.fit(np.concatenate([y_ds, y_orig]).reshape(-1, 1))
y_ds = scaler.transform(y_ds.reshape(-1, 1)).transpose()[0, :]
y_orig = scaler.transform(y_orig.reshape(-1, 1)).transpose()[0, :]

"""
Uncomment to incorporate original sentences into training set.
Not recommended, because semantic relationships aren't as strong.
Tune hyperparameter dim_factor to establish how much you want to edit score.
"""
# X = np.concatenate([X_ds, X_orig])
# y = np.concatenate([y_ds, y_orig])

# Split up 
X = X_ds
y = y_ds
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

# We define the embedding layer here.
import os

embeddings_index = {}
f = open(os.path.join('./glove', 'glove.6B.50d.txt'))
for line in f:
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    embeddings_index[word] = coefs
f.close()

print('Found %s word vectors.' % len(embeddings_index))

embedding_matrix = np.zeros((len(tokenizer.word_index) + 1, embedding_dim))
for word, i in tokenizer.word_index.items():
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
        # words not found in embedding index will be all-zeros.
        embedding_matrix[i] = embedding_vector

# Build the model
from tensorflow.keras.layers import Input, Embedding, Bidirectional, LSTM, Attention
from tensorflow.keras.layers import Dense, Concatenate, Reshape
from tensorflow.keras.activations import linear
from tensorflow.keras.regularizers import l1, l2, l1_l2
from tensorflow.keras.models import Model

in1 = Input((max_len,))
in2 = Input((max_len,))

emb = Embedding(len(tokenizer.word_index) + 1, 
                embedding_dim, 
                input_length=max_len)
if use_embedding: 
    emb = Embedding(len(tokenizer.word_index) + 1, 
                    embedding_dim, 
                    weights=[embedding_matrix],
                    input_length=max_len, 
                    trainable=emb_trainable)

# First sequence branch
branch1 = emb(in1)
branch1l = Bidirectional(LSTM(25, 
                              activation='elu', 
                              return_sequences=True, 
                              kernel_regularizer=l2(0.01)))(branch1)

# Second sequence branch
branch2 = emb(in2)
branch2l = Bidirectional(LSTM(25, 
                              activation='elu', 
                              return_sequences=True, 
                              kernel_regularizer=l2(0.01)))(branch2)

# Concatenate with Luong attention (eventually add word embedding as value)
attention1 = Attention(use_scale=True)([branch1, branch2])
attention2 = Attention(use_scale=True)([branch1l, branch2l])
concat = Concatenate(axis=-1)([attention1, attention2])

# Process concatenated output
out = Bidirectional(LSTM(80, activation='elu', kernel_regularizer=l2(0.01)))(concat)
out = Dense(1, activation='sigmoid')(out)

model = Model(inputs=[in1, in2], outputs=[out])
model.compile(loss='mean_squared_error', 
              optimizer='adam', 
              metrics=['kullback_leibler_divergence'])
model.summary()

# Fit the model
from tensorflow.keras.callbacks import ReduceLROnPlateau

my_callbacks = [
    ReduceLROnPlateau(factor=0.25,
                      mode="min")
]

history1 = model.fit([X_train[:, 0, :], X_train[:, 1, :]],
                    y_train, 
                    epochs=epochs, 
                    validation_split=0.2,
                    callbacks=my_callbacks)

model.evaluate([X_test[:, 0, :], X_test[:, 1, :]], y_test, batch_size=25)
```

The SICK dataset is attached [here](https://github.com/tensorflow/tensorflow/files/5065041/SICK.txt). The 50-dimensional GloVe vectors are too large to upload here, but can be downloaded with

```bash
wget http://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
unzip glove.6B.zip -d glove/
rm glove.6B.zip
```

**Comment by amahendrakar** [comment]
@adityapaul,
Thank you for the update. 

I was able to reproduce the issue with TF v2.3 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/25901ff72e3e0acd95aafc418e0d0941/42106.ipynb#scrollTo=maIk1n0vuAML). Thanks!

**Comment by bhack** [comment]
@adityapaul I see a deprecation warning on your model save:
> WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/resource_variable_ops.py:1781: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
INFO:tensorflow:Assets written to: saved_model/my_model/assets

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF 2.6.0-dev20210603,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/0dd9026dab55cbaf2a9c22cc564ba409/untitled219.ipynb)..Thanks !

**Comment by tilakrayal** [comment]
@adityapaul,
I tried to execute the code and when compare to the older gist attached, I was not able to find any deprecated warnings and also the model has been saved. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/5b5d3b3cc728095a9b16bafad950291b/untitled219.ipynb) and let us know if the issue still persists. Thank you!
