### ISSUE TITLE
[TF 2.2] tensorflow.python.framework.errors_impl.InvalidArgumentError: 'func' argument to TF_GraphCopyFunction cannot be null

### ISSUE THREAD

**Issue by ayushch3** [tensorflow/tensorflow#42239]
System information

Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
TensorFlow installed from (source or binary): binary
TensorFlow version (use command below): pip install tensorflow==2.0.0
Python version:3.7.5
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory:
Describe the current behavior
I am able to export the model with tf.saved_model.save but when I try to run the exported model with tf-serving, it runs to seg fault and running the saved_model_cli throws the error attached

Describe the expected behavior

The exported model from tf.saved_model.save should work correctly with tf-serving

Standalone code to reproduce the issue

```
class NGramTF(tf.Module):
    def __init__(self):
        self.oov_score = 0
        self.pseudo_count = 5.0
        pass

    def fit_tf_lookup_table(self, dist):
        keys_tensor = tf.constant(list(dist.keys()))
        vals_tensor = tf.constant(list(dist.values()))
        initializer = tf.lookup.KeyValueTensorInitializer(keys_tensor, vals_tensor)
        table = tf.lookup.StaticHashTable(initializer, self.oov_score)
        return table

    def fit_word_casing(self, wordCasingLookup):
        indices = []
        values = []
        tokens = []
        for idx, (token, items) in enumerate(wordCasingLookup.items()):
            tokens.append(token)
            for j, item in enumerate(items):
                indices.append([idx, j])
                values.append(item)
        word_casing_lookup_shape = [len(tokens), max([len(item) for item in wordCasingLookup.values()])]
        word_casing_lookup_tf = tf.SparseTensor(indices=indices, values=values, dense_shape=word_casing_lookup_shape)
        word_casing_indices = tf.range(0, len(tokens))
        dense_word_casing_lookup_tf = tf.sparse.to_dense(word_casing_lookup_tf, default_value='')

        initializer = tf.lookup.KeyValueTensorInitializer(tf.constant(tokens), word_casing_indices)

        # TODO: this does ot work
        table = tf.lookup.StaticHashTable(initializer, -1)
        return table, dense_word_casing_lookup_tf

    def fit(self, wordCasingLookup, uniDist, backwardBiDist, forwardBiDist, trigramDist):
        self.word_casing, self.word_casing_lookup = self.fit_word_casing(wordCasingLookup)
        self.tf_uni_dist = self.fit_tf_lookup_table(uniDist)
        self.backwardBiDist = self.fit_tf_lookup_table(backwardBiDist)
        self.forwardBiDist = self.fit_tf_lookup_table(forwardBiDist)
        self.trigramDist = self.fit_tf_lookup_table(trigramDist)
```

Code to export the model:

```
def load_truecasing_model(model_filename):
    with open(model_filename, 'rb') as bin_file:  # from s3://workfit-models/auto-punc/
        uni_dist = pickle.load(bin_file)
        backward_bi_dist = pickle.load(bin_file)
        forward_bi_dist = pickle.load(bin_file)
        trigram_dist = pickle.load(bin_file)
        word_casing_lookup = pickle.load(bin_file)
        return word_casing_lookup, uni_dist, backward_bi_dist, forward_bi_dist, trigram_dist

truecaser_weights = 'en/en_truecasing_model.obj'
export_path = './truecaser_serving/1/'
wordCasingLookup, uniDist, backwardBiDist, forwardBiDist, trigramDist = load_truecasing_model(truecaser_weights)
tf_model = truecaser_tf.NGramTF()
tf_model.fit(wordCasingLookup, uniDist, backwardBiDist, forwardBiDist, trigramDist)
signature_def = tf_model.get_true_case.get_concrete_function(
        tf.TensorSpec(shape=(None), dtype=tf.string, name="input_text"))
tf.saved_model.save(tf_model,export_path,signatures={'serving_default': signature_def})

```

Other info / logs Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['__saved_model_init_op']:
  The given SavedModel SignatureDef contains the following input(s):
  The given SavedModel SignatureDef contains the following output(s):
    outputs['__saved_model_init_op'] tensor_info:
        dtype: DT_INVALID
        shape: unknown_rank
        name: NoOp
  Method name is: 

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['input_text'] tensor_info:
        dtype: DT_STRING
        shape: unknown_rank
        name: serving_default_input_text:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['output_0'] tensor_info:
        dtype: DT_STRING
        shape: (-1)
        name: StatefulPartitionedCall_5:0
  Method name is: tensorflow/serving/predict
2020-07-31 10:32:36.828182: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-07-31 10:32:36.864779: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7ffd54e04ae0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-31 10:32:36.864800: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version

Defined Functions:
  Function Name: 'get_true_case'
    Option tensorflow/serving#1
      Callable with:
        Argument tensorflow/serving#1
          input_text: TensorSpec(shape=<unknown>, dtype=tf.string, name='input_text')
Exception ignored in: <function CapturableResourceDeleter.__del__ at 0x12f849050>
Traceback (most recent call last):
tensorflow.python.framework.errors_impl.InvalidArgumentError: 'func' argument to TF_GraphCopyFunction cannot be null
Exception ignored in: <function CapturableResourceDeleter.__del__ at 0x12f849050>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/training/tracking/tracking.py", line 191, in __del__
    self._destroy_resource()
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 627, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 506, in _initialize
    *args, **kwds))
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2446, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2777, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2667, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 441, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/saved_model/function_deserialization.py", line 241, in restored_function_body
    return _call_concrete_function(function, inputs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/saved_model/function_deserialization.py", line 72, in _call_concrete_function
    result = function._call_flat(tensor_inputs, function._captured_inputs)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 101, in _call_flat
    cancellation_manager)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1760, in _call_flat
    flat_outputs = forward_function.call(ctx, args_with_tangents)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 627, in call
    executor_type=executor_type)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/functional_ops.py", line 1165, in partitioned_call
    f.add_to_graph(graph)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 543, in add_to_graph
    g._add_function(self)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3187, in _add_function
    gradient)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 'func' argument to TF_GraphCopyFunction cannot be null
WARNING:tensorflow:Unresolved object in checkpoint: (root).word_casing._initializer
WARNING:tensorflow:Unresolved object in checkpoint: (root).tf_uni_dist._initializer
WARNING:tensorflow:Unresolved object in checkpoint: (root).backwardBiDist._initializer
WARNING:tensorflow:Unresolved object in checkpoint: (root).forwardBiDist._initializer
WARNING:tensorflow:Unresolved object in checkpoint: (root).trigramDist._initializer
WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.
```

The code can be accessed here to look at the entire source code:
https://github.com/ayushch3/truecaser_tf

The weights file can be accessed here: https://drive.google.com/file/d/1DpmsDYm-gzcwXCJT4sMCUXmtHGSxKiIR/view?usp=sharing

**Comment by martinwicke** [comment]
@ayushch3 is it easy to verify whether the problem persists with a newer version of TensorFlow?

**Comment by ayushch3** [comment]
the code is running tf 2.2.0 @martinwicke

**Comment by martinwicke** [comment]
Thanks (the template said 2.0.0, hence the question).

I'll let this be picked up by triage.

**Comment by amahendrakar** [comment]
@ayushch3,
On exporting the model with TF v2.3, I did not face any error running the `saved_model_cli` command. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/1e67f1a509d0459a9b8c01993a17e00f/42239.ipynb).

Could you please update TensorFlow to v2.3 and check if you are still facing the same issue? Thanks!

**Comment by ayushch3** [comment]
@gowthamkpr @amahendrakar if you use the tag --all with show_model_cli you would be able to reciprocate the issue with the following error:
saved_model_cli show --dir dir_name --all

tensorflow.python.framework.errors_impl.InvalidArgumentError: 'func' argument to TF_GraphCopyFunction cannot be null
WARNING:tensorflow:Unresolved object in checkpoint: (root).word_casing._initializer
WARNING:tensorflow:Unresolved object in checkpoint: (root).tf_uni_dist._initializer
WARNING:tensorflow:Unresolved object in checkpoint: (root).backwardBiDist._initializer
WARNING:tensorflow:Unresolved object in checkpoint: (root).forwardBiDist._initializer
WARNING:tensorflow:Unresolved object in checkpoint: (root).trigramDist._initializer
WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.

**Comment by amahendrakar** [comment]
@ayushch3,
Even on adding the `--all` flag, I did not face the  `tensorflow.python.framework.errors_impl.InvalidArgumentError: 'func' argument to TF_GraphCopyFunction cannot be null` error. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/b9f6bbef876cec0c1e677f9a3d6465c0/42239.ipynb). Thanks!
