### ISSUE TITLE
Unable to build tflite aar file on windows

### ISSUE THREAD

**Issue by nikroc896** [tensorflow/tensorflow#42258]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): tensorflow github repo
- TensorFlow version: 2.0
- Python version: 3.6.0
- Installed using virtualenv? pip? conda?: NA
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): MSVC 2017
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the problem**
I am unable to build the tflite aar files using this build command: 
 bazel build //tensorflow/lite/java:tensorflow-lite --cxxopt=--std=c++14 -c opt --fat_apk_cpu=armeabi-v7a  --verbose_failures 

This warning pops up a lot of times
cl : Command line warning D9002 : ignoring unknown option '--std=c++14'
And I get this error in the end 
Exception in thread "main" java.nio.file.InvalidPathException: Illegal character [:] in path at index 4: ///C:/Users/nikhil/AppData/Local/Temp/android_resources_tmp11744088656958341427/linked/bin.-pb.apk

**Comment by ymodak** [comment]
Can you try setting the flag as `/std:c++14`?

**Comment by nikroc896** [comment]
@ymodak I tried this build command : bazel build //tensorflow/lite/java:tensorflow-lite --cxxopt=/std:c++14 -c opt --fat_apk_cpu=armeabi-v7a --verbose_failures
The warnings stopped. But I still get this error in the end. 

bazel-out/x64_windows-opt/bin/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/ResourceProcessorBusyBox.exe @bazel-out/x64_windows-opt/bin/tensorflow/lite/java/tensorflow-lite_dummy_app_for_so_symbols/R.txt-0.params
Execution platform: @bazel_tools//platforms:host_platform
Aug 14, 2020 11:07:08 AM com.google.devtools.build.android.ResourceProcessorBusyBox processRequest
SEVERE: Error during processing
java.nio.file.InvalidPathException: Illegal character [:] in path at index 4: ///C:/Users/nikhil/AppData/Local/Temp/android_resources_tmp5138593176805055845/linked/bin.-pb.apk
        at java.base/sun.nio.fs.WindowsPathParser.nextSlash(WindowsPathParser.java:212)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:111)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at com.google.devtools.build.android.aapt2.ProtoApk.asApkPath(ProtoApk.java:203)
        at com.google.devtools.build.android.aapt2.ResourceLinker.link(ResourceLinker.java:555)
        at com.google.devtools.build.android.aapt2.ResourceLinker.link(ResourceLinker.java:536)
        at com.google.devtools.build.android.Aapt2ResourcePackagingAction.main(Aapt2ResourcePackagingAction.java:185)
        at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$14.call(ResourceProcessorBusyBox.java:144)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:240)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:203)

Exception in thread "main" java.nio.file.InvalidPathException: Illegal character [:] in path at index 4: ///C:/Users/nikhil/AppData/Local/Temp/android_resources_tmp5138593176805055845/linked/bin.-pb.apk
        at java.base/sun.nio.fs.WindowsPathParser.nextSlash(WindowsPathParser.java:212)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:111)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at com.google.devtools.build.android.aapt2.ProtoApk.asApkPath(ProtoApk.java:203)
        at com.google.devtools.build.android.aapt2.ResourceLinker.link(ResourceLinker.java:555)
        at com.google.devtools.build.android.aapt2.ResourceLinker.link(ResourceLinker.java:536)
        at com.google.devtools.build.android.Aapt2ResourcePackagingAction.main(Aapt2ResourcePackagingAction.java:185)
        at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$14.call(ResourceProcessorBusyBox.java:144)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:240)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:203)
Target //tensorflow/lite/java:tensorflow-lite failed to build

**Comment by terryheo** [comment]
Have you try TensorFlow 2.2 or higher?

**Comment by nikroc896** [comment]
@terryheo Yep. 2.2 works fine. Even master works fine. I can see this error for both tf2.0 and tf2.1

**Comment by nickkchenn** [comment]
@nikroc896 hello,I met similar question while trying to build tflite 1.15.2 on win10,I wonder how did you solve this problem then?
Thank u

**Comment by sanatmpa1** [comment]
@nikroc896,

We are checking to see if this is still an issue. Can you try updating to latest stable version i.e `2.6.0` and let us know if the issue persists? Thanks!

**Comment by nikroc896** [comment]
@sanatmpa1  
It wasn't an issue in tf2.2 at the time so it should not persist. I encountered it just in tf2.0 and tf2.1
