### ISSUE TITLE
When converting tf to tflite it changes the dtypes so operations like add won't work beacuse of different dtypes RuntimeError: tensorflow/lite/kernels/add.cc:93 input1->type != input2->type (INT32 != FLOAT32)Node number 296 (ADD) failed to prepare.

### ISSUE THREAD

**Issue by danielsernabuitrago** [tensorflow/tensorflow#42335]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 18.04.5 LTS
- TensorFlow installed from (source or binary):
tensorflow 1.15 installed with pip. altough I have tried with older versions

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
# Copy and paste here the exact command
tflite_convert --graph_def_file=./saved_model2.pb --output_file=./mask-rcnn-model2.tflite --output_format=TFLITE --input_arrays=input_image,input_image_meta,input_anchors --input_shapes=1,1024,1024,3:1,14:1,261888,4 --output_arrays=mrcnn_class/Softmax,mrcnn_bbox/Reshape --enable_select_tf_ops --allow_custom_ops --target_ops=TFLITE_BUILTINS,SELECT_TF_OPS
```

**The output from the converter invocation**

```
# Copy and paste the output here.
2020-08-12 16:57:53.877756: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-08-12 16:57:53.899894: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE: forward compatibility was attempted on non supported HW
2020-08-12 16:57:53.899966: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: AI
2020-08-12 16:57:53.899989: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: AI
2020-08-12 16:57:53.900089: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 450.57.0
2020-08-12 16:57:53.900150: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 440.100.0
2020-08-12 16:57:53.900158: E tensorflow/stream_executor/cuda/cuda_diagnostics.cc:313] kernel version 440.100.0 does not match DSO version 450.57.0 -- cannot find working devices in this configuration
2020-08-12 16:57:53.900446: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-08-12 16:57:53.905236: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2799925000 Hz
2020-08-12 16:57:53.905657: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x58a7850 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-12 16:57:53.905678: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
/home/tensorbook/.local/lib/python3.6/site-packages/tensorflow_core/lite/python/lite.py:854: UserWarning: Property target_ops is deprecated, please use target_spec.supported_ops instead.
  "target_spec.supported_ops instead." % name)
2020-08-12 16:57:55.568703: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2020-08-12 16:57:55.568867: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-08-12 16:58:22.490992: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:786] Optimization results for grappler item: graph_to_optimize
2020-08-12 16:58:22.491020: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:788]   constant_folding: Graph size after: 1967 nodes (-1026), 2180 edges (-1093), time = 26054.7871ms.
2020-08-12 16:58:22.491025: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:788]   constant_folding: Graph size after: 1967 nodes (0), 2180 edges (0), time = 410.548ms.
```

**Also, please include a link to the saved model or GraphDef**

```
# Put link here or attach to the issue.
https://drive.google.com/file/d/17JF-Gco7xSbszPXAL-qjFbdDdlW73QJM/view?usp=sharing        "saved frozed model"
https://drive.google.com/file/d/1t2sNK8wBatOUum3XHprO0EejWaGoMKGB/view?usp=sharing     "tflite converted model"
```

**Failure details**
I'm working with instance segmentation keras/tensorflow model "https://github.com/matterport/Mask_RCNN", I'm not using the standard model but retrained or transfer learned to a different dataset... 

the model was converted successfully, but when I try to infer with this code:

```
interpreter = tf.lite.Interpreter(model_path="../../logs/mask-rcnn-model2.tflite")
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

image = cv2.imread('./655.png')
image = image[..., ::-1]
image = image.astype(np.float32)
resized = cv2.resize(image, (1024,1024))

interpreter.set_tensor(input_details[0]['index'], [resized])

interpreter.invoke()

output_data = interpreter.get_tensor(output_details[0]['index'])
```

but if fails at interpreter.invoke() as I said in the title:

```
Traceback (most recent call last):
  File "infer_tflite.py", line 529, in <module>
    interpreter.invoke()
  File "/home/tensorbook/Documents/Mask_RCNN_Kikes/tf_night_env/lib/python3.6/site-packages/tensorflow/lite/python/interpreter.py", line 525, in invoke
    self._interpreter.Invoke()
RuntimeError: tensorflow/lite/kernels/add.cc:93 input1->type != input2->type (INT32 != FLOAT32)Node number 296 (ADD) failed to prepare.
```

I've tried using tf.cast() or even keras K.cast() from tf.float32 to tf.int32 cause later I will bump with a tf.gather_ND which only accepts int32 as index... I'm able to advance and solve the error if I cast to tf.float32 but when I try to cast it back to int32 it does it in tf but in tflite it doesn't cast it. the model architecture is something like this...

```
image_area = tf.cast(image_shape[0] * image_shape[1], tf.float32)
roi_level = log2_graph(tf.sqrt(h * w) / (224.0 / tf.sqrt(image_area)))
roi_level_2 = K.cast(tf.round(roi_level), tf.int32)
sum_to_roi_level = K.cast(4, tf.int32)
roi_level = tf.minimum(5, tf.maximum(
    2, sum_to_roi_level + roi_level_2))
roi_level = tf.squeeze(roi_level, 2)

# Loop through levels and apply ROI pooling to each. P2 to P5.
pooled = []
box_to_level = []
for i, level in enumerate(range(2, 6)):
    ix = tf.where(tf.equal(roi_level, level))
    level_boxes = tf.gather_nd(boxes, ix)
```

Any toughts on this ? I have tried many cast to many elements in the model but the casts to int32 doesn't seem to make effect on tflite. I would greatly appreciate your help. thanks a lot in advance.

**Comment by Saduf2019** [comment]
@danielsernabuitrago 
The code seems incomplete to replicate, please share complete stand alone code such that we can replicate the error faced or if possible share a colab gist with the error faced.
