### ISSUE TITLE
TF 2.3 fails to build with CUDA 11.0 using only 7.5 compute

### ISSUE THREAD

**Issue by quasar66** [tensorflow/tensorflow#42340]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Pro x64 2004 Edition
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.3.0
- Python version: 3.8.5
- Installed using virtualenv? pip? conda?: No, a direct accessible installation
- Bazel version (if compiling from source): 3.4.1
- GCC/Compiler version (if compiling from source): MSVC 2019 C++ compiler
- CUDA/cuDNN version: 11.0/ cuDNN ver 8.0
- GPU model and memory: RTX 2080 GPU memory : 8 GB , system memory 32 GB

**Describe the problem**
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
Repository command failed
'C:/Program' is not recognized as an internal or external command, operable program or batch file.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Step 0 : git cloned the master, cd tensorflow, git checkout r2.3
Step 1 : python ./configure.py
   -> specified : (1) Python and default library path to the installed python 3.8.5 64 bit with all requisite keras packages.
  -> yes to CUDA : Found CUDA 11.0 and Found cuDNN 8.0, specified a compute capability of 7.5 (only one)
  -> optimization flags : /arch:AVX2 and /std:c++17
  -> eigen inline : N (longer compile time acceptable).
 -> no to ROCm, and no to android.
Step 2 :  bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package

Proceeded a few steps for one minute and then failed.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

 PS C:\Users\gautam\tensorflow> bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [cuda, using_cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=120
INFO: Reading rc options for 'build' from c:\users\gautam\tensorflow\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=C:/Program Files/Python3/python.exe
INFO: Reading rc options for 'build' from c:\users\gautam\tensorflow\.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=v2
INFO: Reading rc options for 'build' from c:\users\gautam\tensorflow\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=C:/Program Files/Python3/python.exe --action_env PYTHON_LIB_PATH=C:/Program Files/Python3/lib/site-packages --python_path=C:/Program Files/Python3/python.exe --config=xla --action_env CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.0 --action_env TF_CUDA_COMPUTE_CAPABILITIES=7.5 --config=cuda --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:v2 in file c:\users\gautam\tensorflow\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file c:\users\gautam\tensorflow\.bazelrc: --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true
INFO: Found applicable config definition build:cuda in file c:\users\gautam\tensorflow\.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file c:\users\gautam\tensorflow\.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain
INFO: Found applicable config definition build:opt in file c:\users\gautam\tensorflow\.tf_configure.bazelrc: --copt=/arch:AVX2 --copt=/std:c++17 --define with_default_optimizations=true
INFO: Found applicable config definition build:cuda in file c:\users\gautam\tensorflow\.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file c:\users\gautam\tensorflow\.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain
INFO: Found applicable config definition build:windows in file c:\users\gautam\tensorflow\.bazelrc: --copt=/w --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --experimental_strict_action_env=true --verbose_failures --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file c:\users\gautam\tensorflow\.bazelrc: --define framework_shared_object=false
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
DEBUG: Repository io_bazel_rules_docker instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule git_repository defined at:
  C:/users/gautam/_bazel_gautam/4wn3vkrp/external/bazel_tools/tools/build_defs/repo/git.bzl:195:33: in <toplevel>
INFO: Repository local_config_cuda instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule cuda_configure defined at:
  C:/users/gautam/tensorflow/third_party/gpus/cuda_configure.bzl:1399:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
        File "C:/users/gautam/tensorflow/third_party/gpus/cuda_configure.bzl", line 1369
                _create_local_cuda_repository(<1 more arguments>)
        File "C:/users/gautam/tensorflow/third_party/gpus/cuda_configure.bzl", line 1051, in _create_local_cuda_repository
                _find_libs(repository_ctx, <2 more arguments>)
        File "C:/users/gautam/tensorflow/third_party/gpus/cuda_configure.bzl", line 598, in _find_libs
                _check_cuda_libs(repository_ctx, <2 more arguments>)
        File "C:/users/gautam/tensorflow/third_party/gpus/cuda_configure.bzl", line 500, in _check_cuda_libs
                execute(repository_ctx, <1 more arguments>)
        File "C:/users/gautam/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
'C:/Program' is not recognized as an internal or external command,
operable program or batch file.
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "C:/users/gautam/tensorflow/third_party/gpus/cuda_configure.bzl", line 1369
                _create_local_cuda_repository(<1 more arguments>)
        File "C:/users/gautam/tensorflow/third_party/gpus/cuda_configure.bzl", line 1051, in _create_local_cuda_repository
                _find_libs(repository_ctx, <2 more arguments>)
        File "C:/users/gautam/tensorflow/third_party/gpus/cuda_configure.bzl", line 598, in _find_libs
                _check_cuda_libs(repository_ctx, <2 more arguments>)
        File "C:/users/gautam/tensorflow/third_party/gpus/cuda_configure.bzl", line 500, in _check_cuda_libs
                execute(repository_ctx, <1 more arguments>)
        File "C:/users/gautam/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
'C:/Program' is not recognized as an internal or external command,
operable program or batch file.
WARNING: Target pattern parsing failed.
ERROR: no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "C:/users/gautam/tensorflow/third_party/gpus/cuda_configure.bzl", line 1369
                _create_local_cuda_repository(<1 more arguments>)
        File "C:/users/gautam/tensorflow/third_party/gpus/cuda_configure.bzl", line 1051, in _create_local_cuda_repository
                _find_libs(repository_ctx, <2 more arguments>)
        File "C:/users/gautam/tensorflow/third_party/gpus/cuda_configure.bzl", line 598, in _find_libs
                _check_cuda_libs(repository_ctx, <2 more arguments>)
        File "C:/users/gautam/tensorflow/third_party/gpus/cuda_configure.bzl", line 500, in _check_cuda_libs
                execute(repository_ctx, <1 more arguments>)
        File "C:/users/gautam/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
'C:/Program' is not recognized as an internal or external command,
operable program or batch file.
INFO: Elapsed time: 55.288s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package
19:14:49 PS C:\Users\gautam\tensorflow>

**Comment by ravikyram** [comment]
@quasar66 

Can you try with tested build configurations from [here](https://www.tensorflow.org/install/source_windows#gpu) and try building TensorFlow with CUDA 10.1, and check if it works.
Please, refer #[42084 (comment) ](https://github.com/tensorflow/tensorflow/issues/42084#issuecomment-670208947) for cuda 11.0 support. Thanks!

**Comment by quasar66** [comment]
Hi...
Update - the build process fails for CUDA 10.2, and 10.1 with identical errors at same stage. The input parameters remain the same : namely, use GPU, use AVX2, use c++17.
An observation : The error seems to be a string parsing error as the software seems to be searching for 'C:\Program' which is probably incorrect use of ' '(space character) for parsing a execution string (short for C:\Program Files\...)

The source is release 2.3.

**Comment by wolwire** [comment]
Try changing your python path since the python path created similar problem for me

**Comment by wolwire** [comment]
--python_path=C:/Program Files/Python3/python.exe -> this to C:/Python3/python.exe somethinglike this

**Comment by quasar66** [comment]
Hi...
The build process kickstarted properly with the change in Python installation directory .. However, fails to handle the cudnn with the error as shown below.
ERROR: C:/users/gautam/tensorflow/tensorflow/stream_executor/cuda/BUILD:319:11: undeclared inclusion(s) in rule '//tensorflow/stream_executor/cuda:cudnn_stub':
this rule is missing dependency declarations for the following files included by 'tensorflow/stream_executor/cuda/cudnn_stub.cc':
  'tensorflow/stream_executor/cuda/cudnn_version.h'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 2652.569s, Critical Path: 377.54s
INFO: 5670 processes: 5670 local.
FAILED: Build did NOT complete successfully

The opt : AVX2, dropped the other opt (c++17 as most of the compilation overwrote the flag to c++14 - the default C++).

But thanks @wolwire for the idea regarding the python installation path !! Wondering why I didn't think of it myself...
@ravikyram - I need to recompile from source as I need to generate the C++ library for running loadsavedmodel() in a C++ program.

Any advice please?

**Comment by quasar66** [comment]
Hi..

Further attempt to compile completely without CUDA support, and taking ONLY the default options also failed. This time the error is not very clear, but the only error line seems to be (not sure why we need b_float compatibility)

ERROR: C:/users/gautam/tensorflow/tensorflow/python/BUILD:501:11: C++ compilation of rule '//tensorflow/python:bfloat16_lib' failed (Exit 2): cl.exe failed: error executing command
<many more lines of output>
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 6344.527s, Critical Path: 390.88s
INFO: 8875 processes: 8875 local.
FAILED: Build did NOT complete successfully

Environment : bazel 3.4.1 - all Windows C++ specifications installed, MSYS2 installed, MSVC 14.27.29110, Windows SDK : 10.0.19041.1
running on windows 10 Pro 64 bit updated to 2004 Edition.

Thanks..

**Comment by gunan** [comment]
@meteorcloudy could you take a look?

**Comment by meteorcloudy** [comment]
Hi @quasar66 , can you rebuild  with `--verbose_failures` and provide the error message here? Thanks!

**Comment by quasar66** [comment]
Hi @meteorcloudy 

I am currently attempting to build with Bazel 3.1.0, AVX2, c++17, the master branch (not r2.3), CUDA 11.0, cuDNN 8 , build for tensorflow.dll (which is what I actually need) - and its been running for last 16 hours (my PC is little old) but has not yet shown any errors. 14107 of 14375 .. 100% CPU for last 16 hours :-) and for some time it indeed had used up all 32 GB of RAM.

If this succeeds, I will most certainly let you know. If it fails, I shall run with the flag you mentioned and will share the result.

Thanks...
