### ISSUE TITLE
Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by yanivbarlev** [tensorflow/tensorflow#42407]
Hi,

After pip installing tensorflow I get the following message when importing it.

import tensorflow
Traceback (most recent call last):

  File "C:\Users\yaniv_cfrphva\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *

  File "C:\Users\yaniv_cfrphva\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()

  File "C:\Users\yaniv_cfrphva\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)

  File "C:\Users\yaniv_cfrphva\Anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)

  File "C:\Users\yaniv_cfrphva\Anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)

ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-9-d6579f534729>", line 1, in <module>
    import tensorflow

  File "C:\Users\yaniv_cfrphva\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util

  File "C:\Users\yaniv_cfrphva\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 50, in <module>
    from tensorflow.python import pywrap_tensorflow

  File "C:\Users\yaniv_cfrphva\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 69, in <module>
    raise ImportError(msg)

ImportError: Traceback (most recent call last):
  File "C:\Users\yaniv_cfrphva\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\yaniv_cfrphva\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\yaniv_cfrphva\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\yaniv_cfrphva\Anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\yaniv_cfrphva\Anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by FirefoxMetzger** [comment]
Are you using Windows? In this case, have you installed the [ Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)? If not, this is a quite likely cause.

**Comment by Saduf2019** [comment]
@yanivbarlev 
Please refer to [this comment](https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156), to ensure your system suits the requirements.


also, refer similar issues and let us know:

#36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204 #39007
Thanks!

**Comment by zyjcs** [comment]
ImportError: /usr/lib64/libm.so.6: version `GLIBC_2.23' not found (required by /data//anaconda3/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

ImportError: /usr/lib64/libm.so.6: version `GLIBC_2.23' not found (required by /data//anaconda3/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

During handling of the above exception, another exception occurred:

**Comment by Aastik-Mandil** [comment]
Failed to load the native TensorFlow runtime.
I am facing this issue

**Comment by rsandaruwansd22** [comment]
**(Not for conda) Simple thing to do is ADD TO THE PATH...**

Check where the packages are installed (the directory...)  
        WARNING: The script (name).exe is installed in '_C:\Users\(name)\AppData\Roaming\Python\Python39\Scripts_' which is not 
        on PATH. **Consider adding this directory to PATH** or, if you prefer to suppress this warning, use --no-warn-script-location.

just transfer the folders from 
        _'C:\Users\(name)\AppData\Roaming\Python\Python39\Scripts'_ 
         to _C:\Users\(name)\AppData\Local\Programs\Python\Python39_

then import the module and verify...

**Comment by rsandaruwansd22** [comment]
> **(Not for conda) Simple thing to do is ADD TO THE PATH...**
> 
> Check where the packages are installed (the directory...)
> WARNING: The script (name).exe is installed in '_C:\Users(name)\AppData\Roaming\Python\Python39\Scripts_' which is not
> on PATH. **Consider adding this directory to PATH** or, if you prefer to suppress this warning, use --no-warn-script-location.
> 
> then import the module and verify...

**Comment by meghbhalerao** [comment]
Facing this issue on Ubuntu 20 and tf 1.12.0

any solutions?

**Comment by dungdo123** [comment]
Using 'conda' instead of 'pip' maybe help:
conda install -c anaconda tensorflow-gpu
