### ISSUE TITLE
Segmentation fault in tf.image.combined_non_max_suppression

### ISSUE THREAD

**Issue by mjkim720** [tensorflow/tensorflow#42421]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.12.1-38999-g56548c2425 2.4.0-dev20200811
- Python version: 3.7.6
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
A segfault occurs when `max_total_size` is large.  If I execute the same input repetitively, I get different errors in different executions such as `Segmentation Fault`, `what():  vector::_M_fill_insert`, and `what():  terminate called recursively`.

**Describe the expected behavior**
I would expect a runtime exception in python rather than a segfault.  

**Standalone code to reproduce the issue**
```python
import tensorflow as tf
tf.image.combined_non_max_suppression(boxes=tf.ones((11,8,2,4)), scores=tf.ones((11,8,2)), max_output_size_per_class=5, max_total_size=311452676677046672)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
```
Segmentation fault (core dumped)
```
```
what():  terminate called recursively
```
```
what():  vector::_M_fill_insert
```

**Comment by Saduf2019** [comment]
@mjkim720 
I ran your code on 1.15 and do not see "Segmentation fault (core dumped)", as there is support for tf 1.15 and 2.x, please upgrade to later versions and let us know if you are still facing any issue.
please find the gist for [tf 1.15](https://colab.research.google.com/gist/Saduf2019/6c1152184e8961c317eef2c45fdcf74f/untitled372.ipynb).

**Comment by mjkim720** [comment]
Actually, I used the nightly version as of 20200811, not 1.15. I can reproduce the issue with the latest version in Colab.  The session crashed due to the fault in c++ [here](https://colab.research.google.com/drive/1s7vRS_K-OcUL1_rF8T1fHiv_p924ezmB?usp=sharing).

**Comment by sushreebarsa** [comment]
Was able to reproduce the issue in TF 2.6.0-dev20210528,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/44e8b9890a41820a2f9b5aa0a87dfab5/untitled62.ipynb#scrollTo=SlSYBpJ3diVv)..Thanks !

**Comment by yongtang** [comment]
With the latest tf-nightly I believe the issue has been resolved with no crash anymore:
```
# python3
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2021-09-02 15:21:04.937701: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-09-02 15:21:04.937746: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
>>> tf.image.combined_non_max_suppression(boxes=tf.ones((11,8,2,4)), scores=tf.ones((11,8,2)), max_output_size_per_class=5, max_total_size=311452676677046672)
2021-09-02 15:21:06.423863: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-09-02 15:21:06.423905: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2021-09-02 15:21:06.423943: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ip-172-31-87-192): /proc/driver/nvidia/version does not exist
2021-09-02 15:21:06.424317: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py", line 7096, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: cannot compute CombinedNonMaxSuppression as input #3(zero-based) was expected to be a int32 tensor but is a int64 tensor [Op:CombinedNonMaxSuppression]
>>> 

```

**Comment by yongtang** [comment]
@mjkim720 I will close this issue for now, but feel free to re-open if the issue persists.
