### ISSUE TITLE
Cannot install tensorflow via pip

### ISSUE THREAD

**Issue by kanitw** [tensorflow/tensorflow#425]
## 1) If I install directly

(I already have pip in my machine):

```sh
sudo pip install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
sudo easy_install --upgrade six
```
I receive the following errors: 
```
Downloading/unpacking https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
  Downloading tensorflow-0.5.0-py2-none-any.whl (9.8MB): 9.8MB downloaded
  Running setup.py egg_info for package from https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-Kf4UD9-build/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

IOError: [Errno 2] No such file or directory: '/tmp/pip-Kf4UD9-build/setup.py'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /tmp/pip-Kf4UD9-build
Storing complete log in /Users/kanitw/.pip/pip.log
```

## 2) If I install via virtualenv

```sh
virtualenv --system-site-packages ~/tensorflow
source ~/tensorflow/bin/activate
pip install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
```

I receive the following errors: 
```
Downloading/unpacking https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
  Downloading tensorflow-0.5.0-py2-none-any.whl (9.8MB): 9.8MB downloaded
  Running setup.py egg_info for package from https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
    IOError: [Errno 2] No such file or directory: '/var/folders/h3/9m4gf8ln7yngtp_36k84d9hm0000gn/T/pip-Wy0s9g-build/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

IOError: [Errno 2] No such file or directory: '/var/folders/h3/9m4gf8ln7yngtp_36k84d9hm0000gn/T/pip-Wy0s9g-build/setup.py'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /var/folders/h3/9m4gf8ln7yngtp_36k84d9hm0000gn/T/pip-Wy0s9g-build
Storing complete log in /Users/kanitw/.pip/pip.log
```

**Comment by vrv** [comment]
https://www.tensorflow.org/versions/master/get_started/os_setup.html#pip-installation-issues ?

**Comment by kanitw** [comment]
That works, thank you for super-fast reply!

**Comment by Alchemist77** [comment]
https://www.tensorflow.org/versions/master/get_started/os_setup.html#pip-installation-issues

**Comment by abhigarg** [comment]
@vrv 
the link you have shared is broken

**Comment by vrv** [comment]
https://www.tensorflow.org/install/install_linux#common_installation_problems
