### ISSUE TITLE
How can I use dropout on input layer?

### ISSUE THREAD

**Issue by JohnnyY8** [tensorflow/tensorflow#4253]
Hi everyone:
I try to combine softmax classifier and dropout algorithm, because there are only input layer and classfier. According tutorial, I want to use dropout on input layer like following:
![image](https://cloud.githubusercontent.com/assets/12611573/18319468/6cd13298-7558-11e6-997d-0f87349b0015.png)
But I got the following error:
Traceback (most recent call last):
  File "softmax.py", line 255, in <module>
    Start_building_and_training(num_sample, x_data_merged_dnaid[:], y_label[:], num_batch)
  File "softmax.py", line 213, in Start_building_and_training
    prob = sess.run(y, feed_dict={x: batch_xs, y_: batch_ys})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 717, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 915, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 985, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_1' with dtype float
	 [[Node: Placeholder_1 = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
	 [[Node: Softmax/_5 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_24_Softmax", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
Caused by op u'Placeholder_1', defined at:
  File "softmax.py", line 255, in <module>
    Start_building_and_training(num_sample, x_data_merged_dnaid[:], y_label[:], num_batch)
  File "softmax.py", line 194, in Start_building_and_training
    keep_x = tf.placeholder(tf.float32)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1270, in placeholder
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 1530, in _placeholder
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2334, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1253, in __init__
    self._traceback = _extract_stack()

Can anyone help me ? Thanks a lot!

**Comment by tatatodd** [comment]
Hi @JohnnyY8!  The concept behind dropout is to randomly drop some nodes *from the hidden layer* while training.  In the code you've highlighted above, you're applying dropout *to the input layer*, which is the problem.

For an example of how to apply dropout see this:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py#L109

Hope this helps!  FYI we primarily use github issues to track bugs and installation issues; in the future please ask these types of questions on StackOverflow and tag it with the `tensorflow` tag.  Thanks!

**Comment by fwalch** [comment]
From the error message and the code, I think the problem is rather that the `keep_x` placeholder is not fed into session.run. Giving a name to the placeholder should make the error message more obvious.

**Comment by JohnnyY8** [comment]
@tatatodd Hi:
Thanks for your answer. But applying dropout to the input layer maybe not the root problem, I think it is good for input and hidden layer. Thank you for your help again.

**Comment by JohnnyY8** [comment]
@fwalch Hi:
Thank you, I am just a beginner for tensorflow and do not understand how to feed the placeholder into session.run?

**Comment by JohnnyY8** [comment]
@tomermeged Truly thanks!
