### ISSUE TITLE
Access Denied when fetching local_config_cuda while building TF from source

### ISSUE THREAD

**Issue by NikhilBartwal** [tensorflow/tensorflow#42587]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.3.+
- Python version:  3.7.4
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 10.1/7.6.5
- GPU model and memory: Nvidia GeForce 940 MX 4Gb

**Describe the problem**
When i try to build the tensorflow from the source i got from the repo, the build fails when trying to build package for TF 2.x
**Provide the exact sequence of commands / steps that you executed before running into the problem**
All steps were followed as mentioned in the official documentation [here](https://www.tensorflow.org/install/source_windows#setup_for_windows)
Step 0: Got all the mentioned pre-requisites and included them all in the path variables
Step 1: Downloaded and checkout the master branch of tensorflow repo using git
Step 2: `cd tensorflow`
`python ./configure.py`

The output of the configure file is as follows: 
```
F:\tfrep\tensorflow>python configure.py
You have bazel 3.1.0 installed.
Please specify the location of python. [Default is F:\python\python.exe]:


Found possible Python library paths:
  F:\python\lib\site-packages
Please input the desired Python library path to use.  Default is [F:\python\lib\site-packages]

Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Found CUDA 10.1 in:
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/lib/x64
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include
Found cuDNN 7 in:
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/lib/x64
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include


Please specify a list of comma-separated CUDA compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus. Each capability can be specified as "x.y" or "compute_xy" to include both virtual and binary GPU code, or as "sm_xy" to only include the binary code.
Please note that each additional compute capability significantly increases your build time and binary size, and that TensorFlow only supports compute capabilities >= 3.5 [Default is: 3.5,7.0]: 5.0


Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]:


Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]:
Eigen strong inline overridden.

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]:
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=monolithic     # Config for mostly static monolithic build.
        --config=ngraph         # Build with Intel nGraph support.
        --config=numa           # Build with NUMA support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
        --config=v2             # Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=noaws          # Disable AWS S3 filesystem support.
        --config=nogcp          # Disable GCP support.
        --config=nohdfs         # Disable HDFS support.
        --config=nonccl         # Disable NVIDIA NCCL support.
```

Even the cuDNN version and the path as shown in the output is not valid since i have cuDNN version 7.6.5 installed in `C:/cuda`
Step 4: `bazel build //tensorflow/tools/pip_package:build_pip_package`
This is where the problem originates:
Output:-
```
F:\tfrep\tensorflow>bazel build //tensorflow/tools/pip_package:build_pip_package
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=211
INFO: Reading rc options for 'build' from f:\tfrep\tensorflow\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=F:/python/python.exe
INFO: Reading rc options for 'build' from f:\tfrep\tensorflow\.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=short_logs --config=v2
INFO: Reading rc options for 'build' from f:\tfrep\tensorflow\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=F:/python/python.exe --action_env PYTHON_LIB_PATH=F:/python/lib/site-packages --python_path=F:/python/python.exe --config=xla --action_env CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1 --action_env TF_CUDA_COMPUTE_CAPABILITIES=5.0 --config=cuda --define=override_eigen_strong_inline=true --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:short_logs in file f:\tfrep\tensorflow\.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file f:\tfrep\tensorflow\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file f:\tfrep\tensorflow\.bazelrc: --define=with_xla_support=true
INFO: Found applicable config definition build:cuda in file f:\tfrep\tensorflow\.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file f:\tfrep\tensorflow\.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=1
INFO: Found applicable config definition build:windows in file f:\tfrep\tensorflow\.bazelrc: --copt=/w --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --experimental_strict_action_env=true --verbose_failures --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file f:\tfrep\tensorflow\.bazelrc: --define framework_shared_object=false
INFO: Repository local_config_cuda instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule cuda_configure defined at:
  F:/tfrep/tensorflow/third_party/gpus/cuda_configure.bzl:1407:18: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
        File "F:/tfrep/tensorflow/third_party/gpus/cuda_configure.bzl", line 1377
                _create_local_cuda_repository(<1 more arguments>)
        File "F:/tfrep/tensorflow/third_party/gpus/cuda_configure.bzl", line 1221, in _create_local_cuda_repository
                to_list_of_strings(<1 more arguments>)
        File "F:/tfrep/tensorflow/third_party/gpus/cuda_configure.bzl", line 1222, in to_list_of_strings
                _cuda_include_path(<2 more arguments>)
        File "F:/tfrep/tensorflow/third_party/gpus/cuda_configure.bzl", line 364, in _cuda_include_path
                inc_entries.append(<1 more arguments>)
        File "F:/tfrep/tensorflow/third_party/gpus/cuda_configure.bzl", line 364, in inc_entries.append
                realpath(repository_ctx, <1 more arguments>)
        File "F:/tfrep/tensorflow/third_party/remote_config/common.bzl", line 268, in realpath
                execute(repository_ctx, <1 more arguments>)
        File "F:/tfrep/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
java.io.IOException: ERROR: src/main/native/windows/process.cc(199): CreateProcessW("C:\msys64\usr\bin" -c "realpath \"C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\""): Access is denied.
 (error: 5)
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "F:/tfrep/tensorflow/third_party/gpus/cuda_configure.bzl", line 1377
                _create_local_cuda_repository(<1 more arguments>)
        File "F:/tfrep/tensorflow/third_party/gpus/cuda_configure.bzl", line 1221, in _create_local_cuda_repository
                to_list_of_strings(<1 more arguments>)
        File "F:/tfrep/tensorflow/third_party/gpus/cuda_configure.bzl", line 1222, in to_list_of_strings
                _cuda_include_path(<2 more arguments>)
        File "F:/tfrep/tensorflow/third_party/gpus/cuda_configure.bzl", line 364, in _cuda_include_path
                inc_entries.append(<1 more arguments>)
        File "F:/tfrep/tensorflow/third_party/gpus/cuda_configure.bzl", line 364, in inc_entries.append
                realpath(repository_ctx, <1 more arguments>)
        File "F:/tfrep/tensorflow/third_party/remote_config/common.bzl", line 268, in realpath
                execute(repository_ctx, <1 more arguments>)
        File "F:/tfrep/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
java.io.IOException: ERROR: src/main/native/windows/process.cc(199): CreateProcessW("C:\msys64\usr\bin" -c "realpath \"C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\""): Access is denied.
 (error: 5)
WARNING: Target pattern parsing failed.
ERROR: no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "F:/tfrep/tensorflow/third_party/gpus/cuda_configure.bzl", line 1377
                _create_local_cuda_repository(<1 more arguments>)
        File "F:/tfrep/tensorflow/third_party/gpus/cuda_configure.bzl", line 1221, in _create_local_cuda_repository
                to_list_of_strings(<1 more arguments>)
        File "F:/tfrep/tensorflow/third_party/gpus/cuda_configure.bzl", line 1222, in to_list_of_strings
                _cuda_include_path(<2 more arguments>)
        File "F:/tfrep/tensorflow/third_party/gpus/cuda_configure.bzl", line 364, in _cuda_include_path
                inc_entries.append(<1 more arguments>)
        File "F:/tfrep/tensorflow/third_party/gpus/cuda_configure.bzl", line 364, in inc_entries.append
                realpath(repository_ctx, <1 more arguments>)
        File "F:/tfrep/tensorflow/third_party/remote_config/common.bzl", line 268, in realpath
                execute(repository_ctx, <1 more arguments>)
        File "F:/tfrep/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
java.io.IOException: ERROR: src/main/native/windows/process.cc(199): CreateProcessW("C:\msys64\usr\bin" -c "realpath \"C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\""): Access is denied.
 (error: 5)
INFO: Elapsed time: 1.523s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Even if using no flag during `configure.py` for CUDA, the **Access enied** error originates again, although with a different error.

```
F:\tfrep\tensorflow>bazel build //tensorflow/tools/pip_package:build_pip_package
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=211
INFO: Reading rc options for 'build' from f:\tfrep\tensorflow\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=F:/python/python.exe
INFO: Reading rc options for 'build' from f:\tfrep\tensorflow\.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=short_logs --config=v2
INFO: Reading rc options for 'build' from f:\tfrep\tensorflow\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=F:/python/python.exe --action_env PYTHON_LIB_PATH=F:/python/lib/site-packages --python_path=F:/python/python.exe --config=xla --define=override_eigen_strong_inline=true --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:short_logs in file f:\tfrep\tensorflow\.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file f:\tfrep\tensorflow\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file f:\tfrep\tensorflow\.bazelrc: --define=with_xla_support=true
INFO: Found applicable config definition build:windows in file f:\tfrep\tensorflow\.bazelrc: --copt=/w --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --experimental_strict_action_env=true --verbose_failures --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file f:\tfrep\tensorflow\.bazelrc: --define framework_shared_object=false
INFO: Repository flatbuffers instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule third_party_http_archive defined at:
  F:/tfrep/tensorflow/third_party/repo.bzl:216:28: in <toplevel>
INFO: Repository 'flatbuffers' used the following cache hits instead of downloading the corresponding file.
 * Hash '62f2223fb9181d1d6338451375628975775f7522185266cd5296571ac152bc45' for https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/flatbuffers/archive/v1.12.0.tar.gz
If the definition of 'flatbuffers' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'flatbuffers':
   Traceback (most recent call last):
        File "F:/tfrep/tensorflow/third_party/repo.bzl", line 193
                _apply_delete(ctx, <1 more arguments>)
        File "F:/tfrep/tensorflow/third_party/repo.bzl", line 74, in _apply_delete
                _execute_and_check_ret_code(ctx, <1 more arguments>)
        File "F:/tfrep/tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
                fail(<1 more arguments>)
Non-zero return code(256) when executing 'C:\msys64\usr\bin -l -c "rm" "-rf" "C:/users/nikhil/appdata/roaming/spb_data/_bazel_nikhil/5i2b27md/external/flatbuffers/build_defs.bzl"':
Stdout:
Stderr: java.io.IOException: ERROR: src/main/native/windows/process.cc(199): CreateProcessW("C:\msys64\usr\bin" -l -c "\"rm\" \"-rf\" \"C:/users/nikhil/appdata/roaming/spb_data/_bazel_nikhil/5i2b27md/external/flatbuffers/build_defs.bzl\""): Access is denied.
 (error: 5)
ERROR: F:/tfrep/tensorflow/tensorflow/tools/pip_package/BUILD:284:1: //tensorflow/tools/pip_package:build_pip_package depends on //tensorflow/lite/python:tflite_convert in repository @ which failed to fetch. no such package '@flatbuffers//': Traceback (most recent call last):
        File "F:/tfrep/tensorflow/third_party/repo.bzl", line 193
                _apply_delete(ctx, <1 more arguments>)
        File "F:/tfrep/tensorflow/third_party/repo.bzl", line 74, in _apply_delete
                _execute_and_check_ret_code(ctx, <1 more arguments>)
        File "F:/tfrep/tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
                fail(<1 more arguments>)
Non-zero return code(256) when executing 'C:\msys64\usr\bin -l -c "rm" "-rf" "C:/users/nikhil/appdata/roaming/spb_data/_bazel_nikhil/5i2b27md/external/flatbuffers/build_defs.bzl"':
Stdout:
Stderr: java.io.IOException: ERROR: src/main/native/windows/process.cc(199): CreateProcessW("C:\msys64\usr\bin" -l -c "\"rm\" \"-rf\" \"C:/users/nikhil/appdata/roaming/spb_data/_bazel_nikhil/5i2b27md/external/flatbuffers/build_defs.bzl\""): Access is denied.
 (error: 5)
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@flatbuffers//': Traceback (most recent call last):
        File "F:/tfrep/tensorflow/third_party/repo.bzl", line 193
                _apply_delete(ctx, <1 more arguments>)
        File "F:/tfrep/tensorflow/third_party/repo.bzl", line 74, in _apply_delete
                _execute_and_check_ret_code(ctx, <1 more arguments>)
        File "F:/tfrep/tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
                fail(<1 more arguments>)
Non-zero return code(256) when executing 'C:\msys64\usr\bin -l -c "rm" "-rf" "C:/users/nikhil/appdata/roaming/spb_data/_bazel_nikhil/5i2b27md/external/flatbuffers/build_defs.bzl"':
Stdout:
Stderr: java.io.IOException: ERROR: src/main/native/windows/process.cc(199): CreateProcessW("C:\msys64\usr\bin" -l -c "\"rm\" \"-rf\" \"C:/users/nikhil/appdata/roaming/spb_data/_bazel_nikhil/5i2b27md/external/flatbuffers/build_defs.bzl\""): Access is denied.
 (error: 5)
INFO: Elapsed time: 2.584s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (49 packages loaded, 14 targets configured)
    currently loading: tensorflow/lite/python
```

I have been working on TFDS for quite some time now and would like to work on TF as well. Therefore, I need to build the source ASAP. Thanks in advance!

**Comment by NikhilBartwal** [comment]
Hey @Saduf2019, Thanks for the reply. After correcting the MSVC path variable and re-installing the Windows SDK, I was able to run the build, which took exceptionally long time (~6-7 hours on i7 7th gen 8GB laptop). In the end the bazel build got stuck at
`[12638/12791] Linking tensorflow/python/_pywrap_tensorflow_internal.so 50000s`
The seconds go on increasing but nothing happens.

**Comment by NikhilBartwal** [comment]
@Saduf2019 One more thing that I wanted to ask was that how much time does the build supposed to take on a single cpu? and Am i supposed to build it every time new commits are done to the repo?

**Comment by NikhilBartwal** [comment]
@Saduf2019 After i shut it down and re build it using the bazel command as mentioned in the instructions [here](bazel build //tensorflow/tools/pip_package:build_pip_package), it now got stuck at

```
C:\Users\nikhil\tensorflow>bazel build //tensorflow/tools/pip_package:build_pip_package
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=120
INFO: Reading rc options for 'build' from c:\users\nikhil\tensorflow\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=F:/python/python.exe
INFO: Reading rc options for 'build' from c:\users\nikhil\tensorflow\.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=short_logs --config=v2
INFO: Reading rc options for 'build' from c:\users\nikhil\tensorflow\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=F:/python/python.exe --action_env PYTHON_LIB_PATH=F:/python/lib/site-packages --python_path=F:/python/python.exe --config=xla --action_env CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1 --action_env TF_CUDA_COMPUTE_CAPABILITIES=5.0 --config=cuda --define=override_eigen_strong_inline=true --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:short_logs in file c:\users\nikhil\tensorflow\.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file c:\users\nikhil\tensorflow\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file c:\users\nikhil\tensorflow\.bazelrc: --define=with_xla_support=true
INFO: Found applicable config definition build:cuda in file c:\users\nikhil\tensorflow\.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file c:\users\nikhil\tensorflow\.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=1
INFO: Found applicable config definition build:windows in file c:\users\nikhil\tensorflow\.bazelrc: --copt=/w --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --experimental_strict_action_env=true --verbose_failures --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file c:\users\nikhil\tensorflow\.bazelrc: --define framework_shared_object=false
INFO: Analyzed target //tensorflow/tools/pip_package:build_pip_package (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
[2 / 203] checking cached actions
```
