### ISSUE TITLE
Failed precondition: Could not find required function definition __inference_tf_data_experimental_parallel_interleave_<class 'abc.ABCMeta'>

### ISSUE THREAD

**Issue by jaykumar16** [tensorflow/tensorflow#42607]
Hey, I am trying to convert the code from tensorflow=1.9 to tensorflow=1.14 and I am getting the following error: 

Failed precondition: Could not find required function definition __inference_tf_data_experimental_parallel_interleave_<class 'abc.ABCMeta'>_40
	 [[{{node OptimizeDataset/create_dataset/ExperimentalParallelInterleaveDataset}}]]
2020-08-23 15:34:01.711575: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at iterator_ops.cc:973 : Failed precondition: Could not find required function definition __inference_tf_data_experimental_parallel_interleave_<class 'abc.ABCMeta'>_40
	 [[{{node OptimizeDataset/create_dataset/ExperimentalParallelInterleaveDataset}}]]
Traceback (most recent call last):
  File "/home/jay/Documents/Reconstraction/DeepRecon/dl-inavJayV2/TV2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/jay/Documents/Reconstraction/DeepRecon/dl-inavJayV2/TV2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/jay/Documents/Reconstraction/DeepRecon/dl-inavJayV2/TV2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.FailedPreconditionError: 2 root error(s) found.
  (0) Failed precondition: Could not find required function definition __inference_tf_data_experimental_parallel_interleave_<class 'abc.ABCMeta'>_40
	 [[{{node OptimizeDataset/create_dataset/ExperimentalParallelInterleaveDataset}}]]
	 [[OneShotIterator]]
	 [[IteratorGetNext/_711]]
  (1) Failed precondition: Could not find required function definition __inference_tf_data_experimental_parallel_interleave_<class 'abc.ABCMeta'>_40
	 [[{{node OptimizeDataset/create_dataset/ExperimentalParallelInterleaveDataset}}]]
	 [[OneShotIterator]]

May you please me with this issue?

**Comment by amahendrakar** [comment]
@jaykumar16,
TensorFlow 1.x is not actively supported. Could you please update TensorFlow to v2.3 and check if it works. 

Please take a look at this code [migration guide](https://www.tensorflow.org/guide/migrate) for more information. Thanks!
