### ISSUE TITLE
Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by Toastmanv3** [tensorflow/tensorflow#42751]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Windows 10 Home 1909**
- TensorFlow installed from (source or binary): **Tensorflow.org**
- TensorFlow version: **1.13.2 gpu**
- Python version: **3.75 (64-bit)**
- Installed using virtualenv? pip? conda?: **pip**
- CUDA/cuDNN version: **10.0**
- GPU model and memory: **ZOTAC GeForce GT 1030 2GB GDDR5**

**Describe the problem**

So I was trying to run "CorentinJ's Real Time Voice Cloning project" using a guide for windows 10 (https://poorlydocumented.com/2019/11/installing-corentinjs-real-time-voice-cloning-project-on-windows-10-from-scratch/) and I followed the guide exactly as it said to.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

`C:\Users\Dolphin EMU\appdata\local\programs\python\python37\scripts\real-time-voice-cloning-master> .\pip install tensorflow-gpu==1.13.2`

**I restarted powershell after installation finished**

`C:\Users\Dolphin EMU\appdata\local\programs\python\python37\scripts\real-time-voice-cloning-master> .\python.exe demo_toolbox.py`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
Traceback (most recent call last):
  File "demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "C:\Users\Dolphin EMU\appdata\local\programs\python\python37\scripts\real-time-voice-cloning-master\toolbox\__init__.py", line 3, in <module>
    from synthesizer.inference import Synthesizer
  File "C:\Users\Dolphin EMU\appdata\local\programs\python\python37\scripts\real-time-voice-cloning-master\synthesizer\inference.py", line 1, in <module>
    from synthesizer.tacotron2 import Tacotron2
  File "C:\Users\Dolphin EMU\appdata\local\programs\python\python37\scripts\real-time-voice-cloning-master\synthesizer\tacotron2.py", line 3, in <module>
    from synthesizer.models import create_model
  File "C:\Users\Dolphin EMU\appdata\local\programs\python\python37\scripts\real-time-voice-cloning-master\synthesizer\models\__init__.py", line 1, in <module>
    from .tacotron import Tacotron
  File "C:\Users\Dolphin EMU\appdata\local\programs\python\python37\scripts\real-time-voice-cloning-master\synthesizer\models\tacotron.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\Dolphin EMU\appdata\local\programs\python\python37\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Dolphin EMU\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Dolphin EMU\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Dolphin EMU\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Dolphin EMU\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Dolphin EMU\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Dolphin EMU\appdata\local\programs\python\python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Dolphin EMU\appdata\local\programs\python\python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by rohanbennur43** [comment]
Please assign me this issur

**Comment by rohanbennur43** [comment]
Please assign me this issue

**Comment by rohanbennur43** [comment]
Please assign me this issue

**Comment by ravikyram** [comment]
@Toastmanv3 

What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the [latest microsoft visual c++ redistributable from here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).
.Also, please follow the instructions from to install from [Tensorflow website](https://www.tensorflow.org/install/source_windows).

Please, check Your CPU/Python is on 32 bits?Please, refer #36167 and see if it helps you.Please, refer similar issues #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
Thanks!
