### ISSUE TITLE
ModuleNotFoundError: No module named 'gast'

### ISSUE THREAD

**Issue by akksa** [tensorflow/tensorflow#42761]
<em>Tensorflow==2.3 installed successfully, but, while importing, it throws "ModuleNotFoundError: No module named 'gast'".  where as gast==0.3.3 is installed. </em>

**System information**
- MacOS 10.15.6
- Environment:  Anaconda
- TensorFlow installed from (source or binary): pip install tensorflow
- TensorFlow version:2.3
- Python version:Python 3.7.6
- Installed using virtualenv? pip? conda?:conda
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:NO
- GPU model and memory:16 GB

**Describe the problem**

I am able to install tensorflow 2.3 successfully (actually upgraded, then uninstalled, and installed again). but, while importing it throws

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 46, in <module>
    from tensorflow.python import distribute
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/distribute/__init__.py", line 23, in <module>
    from tensorflow.python.distribute import cross_device_ops
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/distribute/cross_device_ops.py", line 29, in <module>
    from tensorflow.python.distribute import cross_device_utils
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/distribute/cross_device_utils.py", line 25, in <module>
    from tensorflow.python.distribute import values as value_lib
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/distribute/values.py", line 23, in <module>
    from tensorflow.python.distribute import distribute_lib
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py", line 200, in <module>
    from tensorflow.python.autograph.core import ag_ctx as autograph_ctx
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/__init__.py", line 37, in <module>
    from tensorflow.python.autograph.core.converter import ConversionOptions
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/core/converter.py", line 69, in <module>
    from tensorflow.python.autograph.pyct import anno
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/anno.py", line 28, in <module>
    import gast
ModuleNotFoundError: No module named 'gast'

**Comment by Dynmi** [comment]
`pip install gast`

**Comment by ravikyram** [comment]
@akksa 

Can you please try 

```
pip uninstall gast
pip install tensorflow
```
Thanks!

**Comment by Saduf2019** [comment]
@akksa 
Please refer to below resolved issues with similar error and let us know if it helps:

#26376: pip uninstall gast   pip install tensorflow
 [link](https://stackoverflow.com/questions/58582373/modulenotfounderror-no-module-named-tensorflow)

**Comment by akksa** [comment]
Yes, tried uninstalling gast and installed TensorFlow, but, keep getting the other dependency module not found. Created a separate environment with Tensorflow2.3 and got it solved. maybe an issue with anaconda env too. closing this issue.
