### ISSUE TITLE
Can's Training by using the data on external SSD

### ISSUE THREAD

**Issue by Ageneinair** [tensorflow/tensorflow#42844]
**System information**
- Have I written custom code: yes
- OS Platform and Distribution: macOS Catalina
- Mobile device if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.0
- Python version: 3.7.4
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

### Bug Summary
I am training an image classifier on the local machine, it works ok when the data is on the local machine, however, when I tried the data which on my external SSD, error pops out. The data on external SSD can be read and decoded separately by using the following code:
```
import tensorflow as tf
IMG_HEIGHT = 90
IMG_WIDTH = 160
path = "/Volumes/External-SSD/dataset/labeled/gaming/Fresh_68799179400006397.bmp"

def load_and_preprocess_image(path):
    img = tf.io.read_file(path)
    img = tf.image.decode_bmp(img, channels=3)
    img = tf.image.resize(img, [IMG_HEIGHT, IMG_WIDTH])
    img /= 255.0  # normalize to [0,1] range
    return img

load_and_preprocess_image(path)
```

### My code

- Dataloader
```
class DataSetGenerator():
    def __init__(self, IMG_HEIGHT, IMG_WIDTH):
        self.IMG_HEIGHT = IMG_HEIGHT
        self.IMG_WIDTH = IMG_WIDTH

    def load_and_preprocess_image(self, path):
        img = tf.io.read_file(path)
        img = tf.image.decode_bmp(img, channels=3)
        img = tf.image.resize(img, [self.IMG_HEIGHT, self.IMG_WIDTH])
        img /= 255.0  # normalize to [0,1] range
        return img

    def prepare_for_training(self, ds, cache=True):
        if cache:
            if isinstance(cache, str):
                ds = ds.cache(cache)
        else:
          ds = ds.cache()

        ds = ds.shuffle(buffer_size=self.SHUFFLE_SIZE)

        ds = ds.batch(self.BATCH_SIZE)

        # `prefetch` lets the dataset fetch batches in the background while the model
        # is training.
        ds = ds.prefetch(buffer_size=self.AUTOTUNE)

        return ds

    def labeled_dataset(self, image_paths, labels):
        # a dataset that returns image paths
        path_ds = tf.data.Dataset.from_tensor_slices(image_paths)

        # a dataset that returns images (loaded off disk, decoded, and preprocessed)
        image_ds = path_ds.map(self.load_and_preprocess_image, num_parallel_calls=self.AUTOTUNE)

        # a dataset that returns labels
        label_ds = tf.data.Dataset.from_tensor_slices(tf.cast(labels, tf.int64))

        # a dataset that returns images and labels
        image_label_ds = tf.data.Dataset.zip((image_ds, label_ds))

        return image_label_ds

    def get_final_dataset(self, data_root, SHUFFLE_SIZE, BATCH_SIZE):
        self.SHUFFLE_SIZE = SHUFFLE_SIZE
        self.BATCH_SIZE = BATCH_SIZE
        self.AUTOTUNE = tf.data.experimental.AUTOTUNE

        # a dataset that returns image paths
        data_root = pathlib.Path(data_root)
        all_image_paths = list(data_root.glob('*/**/*'))
        all_image_paths = [str(path) for path in all_image_paths if str(path).lower().endswith("bmp")]
                                                
        random.shuffle(all_image_paths)

        self.label_names = sorted(item.name for item in data_root.glob('*/') if item.is_dir())
        label_to_index = dict((name, index) for index, name in enumerate(self.label_names))
        all_labels = [label_to_index[path.split('/')[-2]]
                        for path in all_image_paths]

        # separate dataset
        train_paths, test_paths, train_labels, test_labels = train_test_split(all_image_paths, all_labels)

        train_ds = self.labeled_dataset(train_paths, train_labels)
        train_ds = self.prepare_for_training(train_ds)

        test_ds = self.labeled_dataset(test_paths, test_labels)
        test_ds = self.prepare_for_training(test_ds)

        return train_ds, test_ds
```
- Model:
```
def GamingModel(IMG_HEIGHT, IMG_WIDTH, category_num):
    model = models.Sequential()
    model.add(layers.Conv2D(32, (3, 3), activation='relu', 
                            input_shape=(IMG_HEIGHT, IMG_WIDTH, 3)))
    model.add(layers.MaxPooling2D())
    model.add(layers.Conv2D(64, (3, 3), activation='relu'))
    model.add(layers.MaxPooling2D())
    model.add(layers.Flatten())
    model.add(layers.Dropout(rate=0.2))
    model.add(layers.Dense(category_num, activation='softmax'))
    model.compile(optimizer='adam',
                loss='sparse_categorical_crossentropy',
                metrics=['accuracy'])
    model.summary()

    return model
```
- Train:
```
from dataloader import DataSetGenerator
from models import GamingModel
from datetime import datetime

IMG_HEIGHT = 90
IMG_WIDTH = 160

data_root = "/Volumes/External-SSD/dataset/labeled"
dsg = DataSetGenerator(IMG_HEIGHT, IMG_WIDTH)
train_ds, test_ds = dsg.get_final_dataset(data_root, SHUFFLE_SIZE=4000, BATCH_SIZE=32)

category_num = len(dsg.label_names)

model = GamingModel(IMG_HEIGHT, IMG_WIDTH, category_num)
es_callback = tf.keras.callbacks.EarlyStopping(monitor='val_accuracy', patience=2, mode='auto')
history = model.fit(train_ds, validation_data=test_ds, epochs=10, callbacks=[es_callback])

now = datetime.now()
now = now.strftime("%Y%m%d-%H%M")
model.save(f"../endpoints/game_state_{now}.h5")
```

### Log
```
2020-08-31 17:33:39.847255: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-08-31 17:33:39.860848: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fd061d24690 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-31 17:33:39.860873: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
conv2d (Conv2D)              (None, 88, 158, 32)       896
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 44, 79, 32)        0
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 42, 77, 64)        18496
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 21, 38, 64)        0
_________________________________________________________________
flatten (Flatten)            (None, 51072)             0
_________________________________________________________________
dropout (Dropout)            (None, 51072)             0
_________________________________________________________________
dense (Dense)                (None, 12)                612876
=================================================================
Total params: 632,268
Trainable params: 632,268
Non-trainable params: 0
_________________________________________________________________
Epoch 1/10
Traceback (most recent call last):
  File "train.py", line 24, in <module>
    history = model.fit(train_ds, validation_data=test_ds, epochs=10, callbacks=[es_callback])
  File "/Users/macuser/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/Users/macuser/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1098, in fit
    tmp_logs = train_function(iterator)
  File "/Users/macuser/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/Users/macuser/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 840, in _call
    return self._stateless_fn(*args, **kwds)
  File "/Users/macuser/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/Users/macuser/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/Users/macuser/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/Users/macuser/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/Users/macuser/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  channels attribute 3 does not match bits per pixel from file 288
	 [[{{node DecodeBmp}}]]
	 [[IteratorGetNext]] [Op:__inference_train_function_755]

Function call stack:
train_function
```

**Comment by Ageneinair** [comment]
I see the problem is not from the SSD, is a part of data can't be decode, how I can solve that?

**Comment by Ageneinair** [comment]
I solved that, follow up for others need it. It was because of some broken images and hidden auto-generated images can't be decoded. Preprocess all images one by one using Tensorflow would tell you which image can't be decoded.
