### ISSUE TITLE
Converting keras (`.h5`) models to `.tflite` fails with error `Windows fatal exception: access violation`

### ISSUE THREAD

**Issue by chrismit3s** [tensorflow/tensorflow#42867]
**System information**
- OS Platform and Distribution: Windows 10, Version 1909
- TensorFlow installed from: binary
- TensorFlow version (or github SHA if from source): 2.2.0

**Command used to run the converter or code if you’re using the Python API**

Basically I just modified the example from https://www.tensorflow.org/lite/convert/python_api#converting_a_keras_model_.

```
import tensorflow as tf

# Load the model.
model = tf.keras.models.load_model("model.h5")

# Convert the model.
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

# Save the TF Lite model.
with tf.io.gfile.GFile('model.tflite', 'wb') as f:
  f.write(tflite_model)
```

**The output from the converter invocation**

```
2020-09-01 17:24:41.539597: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-09-01 17:24:43.716706: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-09-01 17:24:44.420857: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 860M computeCapability: 5.0
coreClock: 1.0195GHz coreCount: 5 deviceMemorySize: 2.00GiB deviceMemoryBandwidth: 74.65GiB/s
2020-09-01 17:24:44.427385: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-09-01 17:24:44.433460: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-09-01 17:24:44.444426: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-09-01 17:24:44.448774: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-09-01 17:24:44.463120: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-09-01 17:24:44.468504: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-09-01 17:24:44.482707: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-09-01 17:24:44.486066: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-09-01 17:24:44.489318: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-09-01 17:24:44.502237: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x19f102e43f0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-01 17:24:44.507055: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-01 17:24:44.509839: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 860M computeCapability: 5.0
coreClock: 1.0195GHz coreCount: 5 deviceMemorySize: 2.00GiB deviceMemoryBandwidth: 74.65GiB/s
2020-09-01 17:24:44.514421: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-09-01 17:24:44.517064: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-09-01 17:24:44.519967: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-09-01 17:24:44.524530: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-09-01 17:24:44.528097: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-09-01 17:24:44.530805: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-09-01 17:24:44.532843: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-09-01 17:24:44.535760: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-09-01 17:24:45.755590: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-01 17:24:45.758598: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0
2020-09-01 17:24:45.760523: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N
2020-09-01 17:24:45.762401: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1368 MB memory) -> physical GPU (device: 0, name: GeForce GTX 860M, pci bus id: 0000:01:00.0, compute capability: 5.0)
2020-09-01 17:24:45.771301: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x19f2c581570 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-09-01 17:24:45.775896: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 860M, Compute Capability 5.0
2020-09-01 17:24:46.935305: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2020-09-01 17:24:46.939007: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-09-01 17:24:46.942082: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 860M computeCapability: 5.0
coreClock: 1.0195GHz coreCount: 5 deviceMemorySize: 2.00GiB deviceMemoryBandwidth: 74.65GiB/s
2020-09-01 17:24:46.945811: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-09-01 17:24:46.947792: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-09-01 17:24:46.950626: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-09-01 17:24:46.953424: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-09-01 17:24:46.955355: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-09-01 17:24:46.958176: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-09-01 17:24:46.961427: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-09-01 17:24:46.963952: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-09-01 17:24:46.965588: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-01 17:24:46.967750: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0
2020-09-01 17:24:46.968919: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N
2020-09-01 17:24:46.970130: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1368 MB memory) -> physical GPU (device: 0, name: GeForce GTX 860M, pci bus id: 0000:01:00.0, compute capability: 5.0)
2020-09-01 17:24:47.005582: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:797] Optimization results for grappler item: graph_to_optimize
2020-09-01 17:24:47.009765: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   function_optimizer: function_optimizer did nothing. time = 0.003ms.
2020-09-01 17:24:47.013518: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-09-01 17:24:48.527683: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2020-09-01 17:24:48.531120: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-09-01 17:24:48.533535: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 860M computeCapability: 5.0
coreClock: 1.0195GHz coreCount: 5 deviceMemorySize: 2.00GiB deviceMemoryBandwidth: 74.65GiB/s
2020-09-01 17:24:48.537018: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-09-01 17:24:48.538710: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-09-01 17:24:48.540380: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-09-01 17:24:48.543054: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-09-01 17:24:48.546077: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-09-01 17:24:48.549536: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-09-01 17:24:48.552508: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-09-01 17:24:48.554275: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-09-01 17:24:48.556311: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-01 17:24:48.559038: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0
2020-09-01 17:24:48.561108: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N
2020-09-01 17:24:48.562745: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1368 MB memory) -> physical GPU (device: 0, name: GeForce GTX 860M, pci bus id: 0000:01:00.0, compute capability: 5.0)
2020-09-01 17:24:49.508141: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:797] Optimization results for grappler item: graph_to_optimize
2020-09-01 17:24:49.511726: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   constant_folding: Graph size after: 135 nodes (-70), 166 edges (-71), time = 496.187ms.
2020-09-01 17:24:49.513808: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   constant_folding: Graph size after: 135 nodes (0), 166 edges (0), time = 142.545ms.
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    tflite_model = converter.convert()
  File "C:\Users\chrismit3s\projects\lemon-finder\nn\venv\lib\site-packages\tensorflow\lite\python\lite.py", line 514, in convert
    result = _toco_convert_impl(
  File "C:\Users\chrismit3s\projects\lemon-finder\nn\venv\lib\site-packages\tensorflow\lite\python\convert.py", line 491, in toco_convert_impl
    data = toco_convert_protos(
  File "C:\Users\chrismit3s\projects\lemon-finder\nn\venv\lib\site-packages\tensorflow\lite\python\convert.py", line 227, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
2020-09-01 17:25:45.917994: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-09-01 17:25:48.444793: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:144] Ignored output_format.
2020-09-01 17:25:48.444956: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:147] Ignored drop_control_dependency.
2020-09-01 17:25:48.612894: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-09-01 17:25:48.620668: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x24e9af13c60 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-01 17:25:48.620946: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-01 17:25:48.621845: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-09-01 17:25:48.985335: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 860M computeCapability: 5.0
coreClock: 1.0195GHz coreCount: 5 deviceMemorySize: 2.00GiB deviceMemoryBandwidth: 74.65GiB/s
2020-09-01 17:25:48.985688: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-09-01 17:25:48.988892: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-09-01 17:25:48.991552: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-09-01 17:25:48.992478: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-09-01 17:25:48.997442: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-09-01 17:25:48.999418: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-09-01 17:25:49.005007: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-09-01 17:25:49.005431: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-09-01 17:25:50.289313: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-01 17:25:50.289550: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0
2020-09-01 17:25:50.289627: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N
2020-09-01 17:25:50.289970: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1354 MB memory) -> physical GPU (device: 0, name: GeForce GTX 860M, pci bus id: 0000:01:00.0, compute capability: 5.0)
2020-09-01 17:25:50.293330: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x24ec910a3e0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-09-01 17:25:50.293537: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 860M, Compute Capability 5.0
loc(callsite("sequential/batch_normalization_1/FusedBatchNormV3"("C:\Users\chrismit3s\projects\lemon-finder\nn\venv\lib\site-packages\tensorflow\python\eager\def_function.py":865:0) at callsite("C:\Users\chrismit3s\projects\lemon-finder\nn\venv\lib\site-packages\tensorflow\python\eager\def_function.py":959:0 at callsite("C:\Users\chrismit3s\projects\lemon-finder\nn\venv\lib\site-packages\tensorflow\lite\python\lite.py":435:0 at "test.py":15:0)))): error: non-broadcastable operands
Windows fatal exception: access violation

Current thread 0x000036e4 (most recent call first):
  File "c:\users\chrismit3s\projects\lemon-finder\nn\venv\lib\site-packages\tensorflow\lite\toco\python\toco_from_protos.py", line 50 in execute
  File "c:\users\chrismit3s\projects\lemon-finder\nn\venv\lib\site-packages\absl\app.py", line 251 in _run_main
  File "c:\users\chrismit3s\projects\lemon-finder\nn\venv\lib\site-packages\absl\app.py", line 300 in run
  File "c:\users\chrismit3s\projects\lemon-finder\nn\venv\lib\site-packages\tensorflow\python\platform\app.py", line 40 in run
  File "c:\users\chrismit3s\projects\lemon-finder\nn\venv\lib\site-packages\tensorflow\lite\toco\python\toco_from_protos.py", line 93 in main
  File "C:\Users\chrismit3s\projects\lemon-finder\nn\venv\Scripts\toco_from_protos.exe\__main__.py", line 7 in <module>
  File "C:\Python38\lib\runpy.py", line 86 in _run_code
  File "C:\Python38\lib\runpy.py", line 193 in _run_module_as_main
```

**Also, please include a link to the saved model or GraphDef**

https://drive.google.com/file/d/17V3oYDLKiAB_N13kNJZIk4ukcwyP44Yp/view?usp=sharing

_Model definition:_

```
m = Sequential()

m.add(Input(shape=(100, 100, 3)))
m.add(GaussianNoise(stddev=0.06))

m.add(Conv2D(filters=64, kernel_size=(5, 5), padding="valid", data_format="channels_last", activation="swish"))
m.add(Conv2D(filters=64, kernel_size=(5, 5), padding="valid", data_format="channels_last", activation="swish"))
m.add(Conv2D(filters=64, kernel_size=(5, 5), padding="valid", data_format="channels_last", activation="swish"))
m.add(Conv2D(filters=64, kernel_size=(5, 5), padding="valid", data_format="channels_last", strides=(2, 2)))
m.add(GaussianNoise(stddev=0.02))
m.add(BatchNormalization(axis=3))
m.add(Activation(activation="swish"))

m.add(Conv2D(filters=256, kernel_size=(5, 5), padding="valid", data_format="channels_last", activation="swish"))
m.add(Conv2D(filters=256, kernel_size=(5, 5), padding="valid", data_format="channels_last", activation="swish"))
m.add(Conv2D(filters=256, kernel_size=(5, 5), padding="valid", data_format="channels_last", activation="swish"))
m.add(Conv2D(filters=256, kernel_size=(5, 5), padding="valid", data_format="channels_last", strides=(2, 2)))
m.add(GaussianNoise(stddev=0.02))
m.add(BatchNormalization(axis=3))
m.add(Activation(activation="swish"))

m.add(Flatten())

m.add(Dense(units=256, activation="swish"))
m.add(Dense(units=256, activation="swish"))
m.add(Dense(units=256, activation="swish"))
m.add(Dense(units=256))
m.add(GaussianNoise(stddev=0.02))
m.add(BatchNormalization(axis=3))
m.add(Activation(activation="swish"))

m.add(Dense(units=64, activation="swish"))
m.add(Dense(units=64, activation="swish"))
m.add(Dense(units=64, activation="swish"))
m.add(Dense(units=64, activation="swish"))

m.add(Dense(units=4, activation="softmax"))

m.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["acc"])
```

EDIT:

Running the same model through the `tflite_convert` script fails in a similar manner. With the `--experimental_new_converter=False` it still fails, just with a different error ([output](https://pastebin.com/SZ4N7zg4)).

**Comment by bhack** [comment]
Can you share your model definition? Thanks

**Comment by chrismit3s** [comment]
Oh, yeah sure:

```
m = Sequential()

m.add(Input(shape=input_shape))
m.add(GaussianNoise(stddev=0.06))

m.add(Conv2D(filters=64, kernel_size=(5, 5), padding="valid", data_format="channels_last", activation="swish"))
m.add(Conv2D(filters=64, kernel_size=(5, 5), padding="valid", data_format="channels_last", activation="swish"))
m.add(Conv2D(filters=64, kernel_size=(5, 5), padding="valid", data_format="channels_last", activation="swish"))
m.add(Conv2D(filters=64, kernel_size=(5, 5), padding="valid", data_format="channels_last", strides=(2, 2)))
m.add(GaussianNoise(stddev=0.02))
m.add(BatchNormalization(axis=3))
m.add(Activation(activation="swish"))

m.add(Conv2D(filters=256, kernel_size=(5, 5), padding="valid", data_format="channels_last", activation="swish"))
m.add(Conv2D(filters=256, kernel_size=(5, 5), padding="valid", data_format="channels_last", activation="swish"))
m.add(Conv2D(filters=256, kernel_size=(5, 5), padding="valid", data_format="channels_last", activation="swish"))
m.add(Conv2D(filters=256, kernel_size=(5, 5), padding="valid", data_format="channels_last", strides=(2, 2)))
m.add(GaussianNoise(stddev=0.02))
m.add(BatchNormalization(axis=3))
m.add(Activation(activation="swish"))

m.add(Flatten())

m.add(Dense(units=256, activation="swish"))
m.add(Dense(units=256, activation="swish"))
m.add(Dense(units=256, activation="swish"))
m.add(Dense(units=256))
m.add(GaussianNoise(stddev=0.02))
m.add(BatchNormalization(axis=3))
m.add(Activation(activation="swish"))

m.add(Dense(units=64, activation="swish"))
m.add(Dense(units=64, activation="swish"))
m.add(Dense(units=64, activation="swish"))
m.add(Dense(units=64, activation="swish"))

m.add(Dense(units=4, activation="softmax"))

m.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["acc"])
```

**Comment by bhack** [comment]
What is your `input_shape`?

**Comment by chrismit3s** [comment]
Dammit, I knew I missed something... It's `(100, 100, 3)`

**Comment by bhack** [comment]
Sure about `BatchNormalization(axis=3)`? Can you compile it?

**Comment by bhack** [comment]
Double check your axis cause this seems it is working.
```
import tensorflow as tf
from tensorflow.keras.layers import (
    Conv2D,
    GaussianNoise,
    Activation,
    BatchNormalization,
    Input,
    Dense,
    Flatten
)

# Load the model.
# Convert the model.
m = tf.keras.models.Sequential()

m.add(Input(shape=(100, 100, 3)))
m.add(GaussianNoise(stddev=0.06))

m.add(Conv2D(filters=64, kernel_size=(5, 5), padding="valid", data_format="channels_last", activation="swish"))
m.add(Conv2D(filters=64, kernel_size=(5, 5), padding="valid", data_format="channels_last", activation="swish"))
m.add(Conv2D(filters=64, kernel_size=(5, 5), padding="valid", data_format="channels_last", activation="swish"))
m.add(Conv2D(filters=64, kernel_size=(5, 5), padding="valid", data_format="channels_last", strides=(2, 2)))
m.add(GaussianNoise(stddev=0.02))
m.add(BatchNormalization())
m.add(Activation(activation="swish"))

m.add(Conv2D(filters=256, kernel_size=(5, 5), padding="valid", data_format="channels_last", activation="swish"))
m.add(Conv2D(filters=256, kernel_size=(5, 5), padding="valid", data_format="channels_last", activation="swish"))
m.add(Conv2D(filters=256, kernel_size=(5, 5), padding="valid", data_format="channels_last", activation="swish"))
m.add(Conv2D(filters=256, kernel_size=(5, 5), padding="valid", data_format="channels_last", strides=(2, 2)))
m.add(GaussianNoise(stddev=0.02))
m.add(BatchNormalization())
m.add(Activation(activation="swish"))

m.add(Flatten())

m.add(Dense(units=256, activation="swish"))
m.add(Dense(units=256, activation="swish"))
m.add(Dense(units=256, activation="swish"))
m.add(Dense(units=256))
m.add(GaussianNoise(stddev=0.02))
m.add(BatchNormalization())
m.add(Activation(activation="swish"))

m.add(Dense(units=64, activation="swish"))
m.add(Dense(units=64, activation="swish"))
m.add(Dense(units=64, activation="swish"))
m.add(Dense(units=64, activation="swish"))

m.add(Dense(units=4, activation="softmax"))

m.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["acc"])
m.save("/tmp/model.h5")
recovered_model = tf.keras.models.load_model("/tmp/model.h5")
converter = tf.lite.TFLiteConverter.from_keras_model(recovered_model)

tflite_model = converter.convert()

# Save the TF Lite model.
with tf.io.gfile.GFile("/tmp/model.tflite", "wb") as f:
    f.write(tflite_model)
```

**Comment by chrismit3s** [comment]
Yep, you were right, I got the axis wrong :) keras' docs are not too thorough on what the `axis` param acutally does, but [this](https://stackoverflow.com/q/47538391) stackoverflow post explains it pretty well.

But what's weird is I could _train_ the model [and got decent(-ish) results], so why does fail only now, when I try to convert it to tflite?

**Comment by bhack** [comment]
@chrismit3s Track the `axis` paramter in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/layers/normalization.py#L162. At the end in `call` you can see that the underline call is `nn.batch_normalization` that don't consume the index.
So I think it is still interesting your `axis=1` case cause it is better that converter not get a segmentation fault.

@amahendrakar Can you mention a the TFlite maintainer?

**Comment by amahendrakar** [comment]
@ymodak,
Could you please take a look? Thanks!
