### ISSUE TITLE
Keras inconsistent behavior when using model.predict for accessing intermediate layers output with spektral GCN

### ISSUE THREAD

**Issue by abdullahmansoor** [tensorflow/tensorflow#42939]
**Describe the current behavior**
I'm trying to access output of intermediate layers of Graph Convolutional Networks (GCN) and model.predict is throwing InvalidArgument Error for input value where as model.fit is working fine with the same input.

I have copied my code below and it using 'CORA' citation dataset from OGB provided by spektral library (https://graphneural.network/) that provide algorithms and examples for Graph Convolutional network. My code is based on one of the example from the same library, here (https://graphneural.network/getting-started/)

I am using Functional API and I have also verified that the same logic works if I apply it on cases other than Graph Convolutional network. 

**Describe the expected behavior**
The error message is related to mismatch of inner dimensions for multiplication. I tried to use the transponse for input like model_input = [X, At] to fix the issue but still face the same error.

Since, the model gets trailed and evaluated without problems on the input i.e. [X,A], it is expected that model.predict should also work consistently. 

**Standalone code to reproduce the issue**
`from spektral.datasets import citation
from spektral.layers import GraphConv
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dropout, Dense
import numpy as np

A, X, y, train_mask, val_mask, test_mask = citation.load_data('cora')

At = A.transpose()

N = A.shape[0]
F = X.shape[-1]
n_classes = y.shape[-1]

X_in = Input(shape=(F, ))
A_in = Input((N, ), sparse=True)
X_1 = GraphConv(16, 'relu', name="layer1")([X_in, A_in])
X_1 = Dropout(0.5, name="layer2")(X_1)
X_2 = GraphConv(n_classes, 'softmax', name="output")([X_1, A_in])
model = Model(inputs=[X_in, A_in], outputs=X_2)

A = GraphConv.preprocess(A).astype('f4')
At = GraphConv.preprocess(At).astype('f4')

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              weighted_metrics=['acc'])
model.summary()

# Prepare data
X = X.toarray()
A = A.astype('f4')
At = At.astype('f4')
validation_data = ([X, A], y, val_mask)

# Train model
model.fit([X, A], 
          y,
          sample_weight=train_mask,
          validation_data=validation_data,
          epochs=1,
          batch_size=N,
          shuffle=False
)

# Access intemediate layers of model
layer_name = 'layer2'
intermediate_layer_model = Model(inputs=model.input,
                                 outputs=model.get_layer(layer_name).output)

model_input = [X,A]
intermediate_output = intermediate_layer_model.predict(model_input)
print("\n\nIntermediate_output=",intermediate_output,"\n\n")`

**Other info / logs** 
`Traceback (most recent call last):
  File "PLGcn_example4_stackflow_debug.py", line 53, in <module>
    intermediate_output = intermediate_layer_model.predict(model_input)
  File "/home/mansoor4/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 130, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/mansoor4/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1599, in predict
    tmp_batch_outputs = predict_function(iterator)
  File "/home/mansoor4/.local/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/home/mansoor4/.local/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 846, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "/home/mansoor4/.local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/home/mansoor4/.local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/mansoor4/.local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/home/mansoor4/.local/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Cannot multiply A and B because inner dimension does not match: 2708 vs. 32.  Did you forget a transpose?  Dimensions of A: [32, 2708).  Dimensions of B: [32,16]
         [[node functional_3/layer1/SparseTensorDenseMatMul/SparseTensorDenseMatMul (defined at /home/mansoor4/.local/lib/python3.7/site-packages/spektral/layers/ops/matmul.py:33) ]] [Op:__inference_predict_function_22928]

Errors may have originated from an input operation.
Input Source operations connected to node functional_3/layer1/SparseTensorDenseMatMul/SparseTensorDenseMatMul:
 stack (defined at PLGcn_example4_stackflow_debug.py:53)
 functional_3/layer1/MatMul (defined at /home/mansoor4/.local/lib/python3.7/site-packages/spektral/layers/ops/matmul.py:45)

Function call stack:
predict_function`
== check pips ===================================================
numpy                  1.18.5
protobuf               3.13.0
tensorflow             2.3.0
tensorflow-estimator   2.3.0

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.version.VERSION = 2.3.0
tf.version.GIT_VERSION = v2.3.0-rc2-23-gb36436b087
tf.version.COMPILER_VERSION = 7.3.1 20180303

== check python ===================================================
python version: 3.7.5
python branch:
python build version: ('default', 'Dec 16 2019 14:09:08')
python compiler version: GCC 6.3.0
python implementation: CPython

== check os platform ===============================================
os: Linux
os kernel version: #1 SMP Tue Mar 17 23:49:17 UTC 2020
os release version: 3.10.0-1062.18.1.el7.x86_64
os platform: Linux-3.10.0-1062.18.1.el7.x86_64-x86_64-with-centos-7.7.1908-Core
linux distribution: ('CentOS Linux', '7.7.1908', 'Core')
linux os distribution: ('centos', '7.7.1908', 'Core')
mac version: ('', ('', '', ''), '')
uname: uname_result(system='Linux', node='login1.cluster', release='3.10.0-1062.18.1.el7.x86_64', version='#1 SMP Tue Mar 17 23:49:17 UTC 2020', machine='x86_64', processor='x86_64')
architecture: ('64bit', 'ELF')
machine: x86_64

== are we in docker =============================================
No

== compiler =====================================================
c++ (GCC) 6.3.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== env ==========================================================
LD_LIBRARY_PATH /vol/apps/gcc/gcc-6.3.0/lib/:/vol/apps/gcc/gcc-6.3.0/lib64:/vol/apps/gcc/gcc-6.3.0/lib/gcc/x86_64-redhat-linux/6.3.0
DYLD_LIBRARY_PATH is unset

== tensorflow installed from info ==================
Name: tensorflow
Version: 2.3.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /home/mansoor4/.local/lib/python3.7/site-packages
Required-by: spektral

== python version  ==============================================
(major, minor, micro, releaselevel, serial)
(3, 7, 5, 'final', 0)

**Comment by abdullahmansoor** [comment]
I realized that there was a problem in my logic that caused the issue and it is not Keras issue.  Daniele Grattarola pointed out on stackoverflow that it could be fixed by adding Batchsize=N in the model.predict call. 

`intermediate_output = intermediate_layer_model.predict(model_input, batch_size=N)`

Sorry for the inconvenience.
