### ISSUE TITLE
Did not find a parser for CONV_2D with latest repo download

### ISSUE THREAD

**Issue by RolfSchlup** [tensorflow/tensorflow#42972]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Running on Raspberry Raspian ( latest version )
- TensorFlow installed from (source or binary): source
- Tensorflow version (commit SHA if source): 2.3.0
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Raspian

**Describe the problem**
With latest sources, I get Did not find a parser for CONV_2D when I try to load a converted model that contains
  model = models.Sequential([
   layers.Conv2D(32, (3, 3), activation='relu', input_shape=(height, width,1)),
   layers.Conv2D(64, (3, 3), activation='relu',padding='same'),
   layers.MaxPooling2D(pool_size=(2, 2),padding='same'),
   layers.Conv2D(128, (3, 3), activation='relu',padding='same'),
   layers.MaxPooling2D(pool_size=(2, 2),padding='same'),
   layers.Conv2D(64, 3, padding='same', activation='relu'),
   layers.MaxPooling2D(pool_size=(2, 2),padding='same'),
   layers.Flatten(),
   layers.Dense(128, activation='linear'),
   layers.Dense(num_classes, activation='softmax')
 ])

I got rid of all layer operations that aren't supported by tf micro.  I got a RESHAPE version error, so I updated from the tensorflow source repo and rebuilt the tf micro library for rpi.  Now I get "Did not find a parser for CONV_2D" when I run

bool PositionML::setup()
  {
    // Not sure why they did it this way, but all examples do it this way
    static tflite::MicroErrorReporter micro_error_reporter;
    mErrorReporter = &micro_error_reporter;

    mModel = tflite::GetModel(model_kara_cnn_tflite);
    if (mModel->version() != TFLITE_SCHEMA_VERSION) {
      TF_LITE_REPORT_ERROR(mErrorReporter, "Model provided is schema version %d not equal to supported version %d.", mModel->version(), TFLITE_SCHEMA_VERSION);
      return false;
    }

    constexpr int tensor_arena_size = 16 * 1024;
    uint8_t tensor_arena[tensor_arena_size];
    tflite::MicroMutableOpResolver<4> resolver;
    resolver.AddConv2D();
    resolver.AddFullyConnected();
    resolver.AddMaxPool2D();
    resolver.AddSoftmax();

    tflite::MicroInterpreter interpreter(mModel, resolver, tensor_arena, tensor_arena_size, mErrorReporter);
    TfLiteStatus allocate_status = interpreter.AllocateTensors();
    if (allocate_status != kTfLiteOk) {
      TF_LITE_REPORT_ERROR(mErrorReporter, "AllocateTensors() failed");
      return false;
    }

    std::cout << "Setup complete" << std::endl;
    return true;
  }

**Comment by thaink** [comment]
@nkreeger Could you take a look at this issue?

**Comment by RolfSchlup** [comment]
Has there been any progress on this?

**Comment by nkreeger** [comment]
@RolfSchlup sorry for the lag - long holiday weekend. 

Can you post the exact error that is happening? I see the original model source - but it's unclear what is going on. Any chance you can try and run the model visualization tool and post the generated HTML file here:

From root tensorflow checkout:

bazel run tensorflow/lite/tools:visualize /path/to/my-model.tflite /tmp/my-model.tflite.html

We use this tool to understand what is in the flatbuffer itself.

**Comment by RolfSchlup** [comment]
This is the error that I get 
"Did not find a parser for CONV_2D"

I wanted to run the bazel command, but now I found that on CentOS 7 ( the machine where the full tensorflow is running), the gcc version does not support c++14.  So, I'm currently updating it to gcc 8.2.0.   On the pi where tensorflow lite micro is running, the gcc version is already at 8.3.0

**Comment by RolfSchlup** [comment]
I just updated gcc to 8.2.0 and reran the command.  I also got the latest from tensorflow master branch.  Got rid of the unknown option -std=c++14 error.  Now I get


Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=183
INFO: Reading rc options for 'run' from /home/rolf/tensorflow-master/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'run' from /home/rolf/tensorflow-master/.bazelrc:
  Inherited 'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=short_logs --config=v2
INFO: Found applicable config definition build:short_logs in file /home/rolf/tensorflow-master/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/rolf/tensorflow-master/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:linux in file /home/rolf/tensorflow-master/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
INFO: Found applicable config definition build:dynamic_kernels in file /home/rolf/tensorflow-master/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
DEBUG: Repository io_bazel_rules_docker instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule git_repository defined at:
  /home/rolf/.cache/bazel/_bazel_rolf/4da7831c14df8ef17ee1e6d70dca59a7/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18: in <toplevel>
INFO: Analyzed target //tensorflow/lite/tools:visualize (30 packages loaded, 191 targets configured).
INFO: Found 1 target...
ERROR: /home/rolf/tensorflow-master/tensorflow/lite/python/BUILD:10:1: Generating flatbuffer files for <source file tensorflow/lite/schema/schema.fbs>: failed (Exit 1): flatc failed: error executing command
  (cd /home/rolf/.cache/bazel/_bazel_rolf/4da7831c14df8ef17ee1e6d70dca59a7/execroot/org_tensorflow && \
  exec env - \
  bazel-out/host/bin/external/flatbuffers/flatc --python -o bazel-out/k8-opt/bin/tensorflow/lite/python/schema_py_srcs_no_include_all -I ./ -I bazel-out/k8-opt/bin -I bazel-out/k8-opt/bin --no-includes --no-union-value-namespacing --gen-object-api tensorflow/lite/schema/schema.fbs)
Execution platform: @local_execution_config_platform//:platform
bazel-out/host/bin/external/flatbuffers/flatc: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by bazel-out/host/bin/external/flatbuffers/flatc)
bazel-out/host/bin/external/flatbuffers/flatc: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by bazel-out/host/bin/external/flatbuffers/flatc)
bazel-out/host/bin/external/flatbuffers/flatc: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by bazel-out/host/bin/external/flatbuffers/flatc)
Target //tensorflow/lite/tools:visualize failed to build
INFO: Elapsed time: 46.606s, Critical Path: 12.87s
INFO: 32 processes: 32 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

**Comment by RolfSchlup** [comment]
I have bazel release 3.10 installed

**Comment by RolfSchlup** [comment]
@nkreeger What is the minimum version of gcc? I'm going to try again with 8.30

**Comment by RolfSchlup** [comment]
@nkreeger 
Ok.  I rebuilt tensorflow from scratch using sources.  Now I have Tensorflow 2.4.0 installed.  Since I'm running this inside of a CentOS8 VM 64 bit, I disabled all CUDA support

The following is the result of running the bazel visualize script

INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=171
INFO: Reading rc options for 'run' from /home/rolf/tensorflow-master/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'run' from /home/rolf/tensorflow-master/.bazelrc:
  Inherited 'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=short_logs --config=v2
INFO: Reading rc options for 'run' from /home/rolf/tensorflow-master/.tf_configure.bazelrc:
  Inherited 'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env PYTHON_LIB_PATH=/usr/local/lib64/python3.6/site-packages --python_path=/usr/bin/python3 --config=xla --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:short_logs in file /home/rolf/tensorflow-master/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/rolf/tensorflow-master/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file /home/rolf/tensorflow-master/.bazelrc: --define=with_xla_support=true
INFO: Found applicable config definition build:linux in file /home/rolf/tensorflow-master/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
INFO: Found applicable config definition build:dynamic_kernels in file /home/rolf/tensorflow-master/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
DEBUG: Repository io_bazel_rules_docker instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule git_repository defined at:
  /home/rolf/.cache/bazel/_bazel_rolf/4da7831c14df8ef17ee1e6d70dca59a7/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18: in <toplevel>
INFO: Analyzed target //tensorflow/lite/tools:visualize (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //tensorflow/lite/tools:visualize up-to-date:
  bazel-bin/tensorflow/lite/tools/visualize
INFO: Elapsed time: 1.528s, Critical Path: 0.02s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
Traceback (most recent call last):
  File "/home/rolf/.cache/bazel/_bazel_rolf/4da7831c14df8ef17ee1e6d70dca59a7/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite/tools/visualize.runfiles/org_tensorflow/tensorflow/lite/tools/visualize.py", line 517, in <module>
    main(sys.argv)
  File "/home/rolf/.cache/bazel/_bazel_rolf/4da7831c14df8ef17ee1e6d70dca59a7/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite/tools/visualize.runfiles/org_tensorflow/tensorflow/lite/tools/visualize.py", line 513, in main
    CreateHtmlFile(tflite_input, html_output)
  File "/home/rolf/.cache/bazel/_bazel_rolf/4da7831c14df8ef17ee1e6d70dca59a7/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite/tools/visualize.runfiles/org_tensorflow/tensorflow/lite/tools/visualize.py", line 429, in CreateHtmlFile
    data = CreateDictFromFlatbuffer(file_data)
  File "/home/rolf/.cache/bazel/_bazel_rolf/4da7831c14df8ef17ee1e6d70dca59a7/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite/tools/visualize.runfiles/org_tensorflow/tensorflow/lite/tools/visualize.py", line 414, in CreateDictFromFlatbuffer
    model_obj = schema_fb.Model.GetRootAsModel(buffer_data, 0)
AttributeError: module 'tensorflow.lite.python.schema_py_generated' has no attribute 'Model'

**Comment by RolfSchlup** [comment]
Found a solution to the above from another issue solution.  Now I have instead 
AttributeError: module 'flatbuffers' has no attribute 'encode'

**Comment by RolfSchlup** [comment]
@nkreeger 
Traceback (most recent call last):
  File "/home/rolf/.cache/bazel/_bazel_rolf/4da7831c14df8ef17ee1e6d70dca59a7/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite/tools/visualize.runfiles/org_tensorflow/tensorflow/lite/tools/visualize.py", line 517, in <module>
    main(sys.argv)
  File "/home/rolf/.cache/bazel/_bazel_rolf/4da7831c14df8ef17ee1e6d70dca59a7/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite/tools/visualize.runfiles/org_tensorflow/tensorflow/lite/tools/visualize.py", line 513, in main
    CreateHtmlFile(tflite_input, html_output)
  File "/home/rolf/.cache/bazel/_bazel_rolf/4da7831c14df8ef17ee1e6d70dca59a7/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite/tools/visualize.runfiles/org_tensorflow/tensorflow/lite/tools/visualize.py", line 429, in CreateHtmlFile
    data = CreateDictFromFlatbuffer(file_data)
  File "/home/rolf/.cache/bazel/_bazel_rolf/4da7831c14df8ef17ee1e6d70dca59a7/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite/tools/visualize.runfiles/org_tensorflow/tensorflow/lite/tools/visualize.py", line 414, in CreateDictFromFlatbuffer
    model_obj = schema_fb.Model.GetRootAsModel(buffer_data, 0)
  File "/home/rolf/.cache/bazel/_bazel_rolf/4da7831c14df8ef17ee1e6d70dca59a7/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite/tools/visualize.runfiles/org_tensorflow/tensorflow/lite/python/schema_py_generated.py", line 9948, in GetRootAsModel
    n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
AttributeError: module 'flatbuffers' has no attribute 'encode'

**Comment by RolfSchlup** [comment]
@nkreeger The problem seems to be that flatbuffers' attribute has been deprecated.  schema_py_generated.py is a generated file so it should be a matter of modifying the generation script.  Which file needs to be modified?

**Comment by RolfSchlup** [comment]
@nkreeger 
The generated schema_py_generated.py file needs 
```from flatbuffers import encode as flatbuffers.encode```
or something similar

**Comment by RolfSchlup** [comment]
Has anyone looked at this for me.  I tried running
bazel run tensorflow/lite/tools:visualize /path/to/my-model.tflite /tmp/my-model.tflite.htm
as suggested, but I get


Traceback (most recent call last):
  File "/home/rolf/.cache/bazel/_bazel_rolf/4da7831c14df8ef17ee1e6d70dca59a7/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite/tools/visualize.runfiles/org_tensorflow/tensorflow/lite/tools/visualize.py", line 517, in <module>
    main(sys.argv)
  File "/home/rolf/.cache/bazel/_bazel_rolf/4da7831c14df8ef17ee1e6d70dca59a7/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite/tools/visualize.runfiles/org_tensorflow/tensorflow/lite/tools/visualize.py", line 513, in main
    CreateHtmlFile(tflite_input, html_output)
  File "/home/rolf/.cache/bazel/_bazel_rolf/4da7831c14df8ef17ee1e6d70dca59a7/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite/tools/visualize.runfiles/org_tensorflow/tensorflow/lite/tools/visualize.py", line 429, in CreateHtmlFile
    data = CreateDictFromFlatbuffer(file_data)
  File "/home/rolf/.cache/bazel/_bazel_rolf/4da7831c14df8ef17ee1e6d70dca59a7/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite/tools/visualize.runfiles/org_tensorflow/tensorflow/lite/tools/visualize.py", line 414, in CreateDictFromFlatbuffer
    model_obj = schema_fb.Model.GetRootAsModel(buffer_data, 0)
  File "/home/rolf/.cache/bazel/_bazel_rolf/4da7831c14df8ef17ee1e6d70dca59a7/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite/tools/visualize.runfiles/org_tensorflow/tensorflow/lite/python/schema_py_generated.py", line 9948, in GetRootAsModel
    n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
AttributeError: module 'flatbuffers' has no attribute 'encode'

**Comment by RolfSchlup** [comment]
@nkreeger 
I just updated the entire tensorflow library and rebuild it from source
Now running
bazel run tensorflow/lite/tools:visualize /path/to/my-model.tflite /tmp/my-model.tflite.html
I get
```
  File "/home/rolf/.cache/bazel/_bazel_rolf/71df654fc5fbedc3c54b5bf44b8a24d2/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite/tools/visualize.runfiles/org_tensorflow/tensorflow/lite/tools/visualize.py", line 517, in <module>
    main(sys.argv)
  File "/home/rolf/.cache/bazel/_bazel_rolf/71df654fc5fbedc3c54b5bf44b8a24d2/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite/tools/visualize.runfiles/org_tensorflow/tensorflow/lite/tools/visualize.py", line 513, in main
    CreateHtmlFile(tflite_input, html_output)
  File "/home/rolf/.cache/bazel/_bazel_rolf/71df654fc5fbedc3c54b5bf44b8a24d2/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite/tools/visualize.runfiles/org_tensorflow/tensorflow/lite/tools/visualize.py", line 429, in CreateHtmlFile
    data = CreateDictFromFlatbuffer(file_data)
  File "/home/rolf/.cache/bazel/_bazel_rolf/71df654fc5fbedc3c54b5bf44b8a24d2/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite/tools/visualize.runfiles/org_tensorflow/tensorflow/lite/tools/visualize.py", line 414, in CreateDictFromFlatbuffer
    model_obj = schema_fb.Model.GetRootAsModel(buffer_data, 0)
AttributeError: module 'tensorflow.lite.python.schema_py_generated' has no attribute 'Model'

**Comment by RolfSchlup** [comment]
I just updated the entire tensorflow library and rebuild it from source
Running
bazel run tensorflow/lite/tools:visualize /path/to/my-model.tflite /tmp/my-model.tflite.html
I still get
```Traceback (most recent call last):
  File "/home/rolf/.cache/bazel/_bazel_rolf/71df654fc5fbedc3c54b5bf44b8a24d2/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite/tools/visualize.runfiles/org_tensorflow/tensorflow/lite/tools/visualize.py", line 517, in <module>
    main(sys.argv)
  File "/home/rolf/.cache/bazel/_bazel_rolf/71df654fc5fbedc3c54b5bf44b8a24d2/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite/tools/visualize.runfiles/org_tensorflow/tensorflow/lite/tools/visualize.py", line 513, in main
    CreateHtmlFile(tflite_input, html_output)
  File "/home/rolf/.cache/bazel/_bazel_rolf/71df654fc5fbedc3c54b5bf44b8a24d2/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite/tools/visualize.runfiles/org_tensorflow/tensorflow/lite/tools/visualize.py", line 429, in CreateHtmlFile
    data = CreateDictFromFlatbuffer(file_data)
  File "/home/rolf/.cache/bazel/_bazel_rolf/71df654fc5fbedc3c54b5bf44b8a24d2/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite/tools/visualize.runfiles/org_tensorflow/tensorflow/lite/tools/visualize.py", line 414, in CreateDictFromFlatbuffer
    model_obj = schema_fb.Model.GetRootAsModel(buffer_data, 0)
AttributeError: module 'tensorflow.lite.python.schema_py_generated' has no attribute 'Model'

**Comment by sushreebarsa** [comment]
@RolfSchlup Could you please make sure to use the latest TF version with a compatible flat buffer version and let us know if the issue still persists? Please find a similar [issue](https://github.com/tensorflow/tensorflow/issues/41846).
Thank you!
