### ISSUE TITLE
UnimplementedError: Fusion is not implemented: [BiasAdd,Add]

### ISSUE THREAD

**Issue by ppwwyyxx** [tensorflow/tensorflow#42976]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):archlinux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:n/a
- TensorFlow installed from (source or binary):some source, some binary
- TensorFlow version (use command below):unknown 2.3.0
- Python version:3.8
- Bazel version (if compiling from source):n/a
- GCC/Compiler version (if compiling from source):n/a
- CUDA/cuDNN version:11/8
- GPU model and memory: GTX1070

**Describe the current behavior**
Running the following code with TF 2.3:
```python
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()

def model():
    a = tf.get_variable('x1', [1, 256, 200, 304])
    b = tf.get_variable('x2', [1, 256, 100, 152])

    def upsample2x(x):
        resize = tf.image.resize_images
        shp2d = tf.shape(x)[2:]
        x = tf.transpose(x, [0, 2, 3, 1])
        x = resize(x, shp2d * 2, 'nearest')
        x = tf.transpose(x, [0, 3, 1, 2])
        return x

    def conv(x, kernel):
        return tf.layers.Conv2D(256, kernel, padding='SAME',
                data_format='channels_first')(x)

    a, b = [conv(c, 1) for c in [a, b]]
    a = a + upsample2x(b)
    out = [conv(x, 3) for x in [a, b]]

    loss = tf.add_n([tf.reduce_mean(x) for x in out])
    train_op = tf.train.GradientDescentOptimizer(0.01).minimize(loss,
            var_list=tf.trainable_variables())
    return train_op

with tf.device('/gpu:0'):
    train_op = model()
config = tf.ConfigProto()
sess = tf.Session(config=config)
with sess.as_default():
    sess.run(tf.global_variables_initializer())
    train_op.run()
```

throws the following error in __certain__ environments:
```
2020-09-04 18:42:52.932125: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
2020-09-04 18:42:53.726786: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-04 18:42:53.731417: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 3600000000 Hz
2020-09-04 18:42:53.731651: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x562fabf1f410 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-04 18:42:53.731662: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-04 18:42:53.733086: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-09-04 18:42:53.796642: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-04 18:42:53.797070: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x562fabfc86d0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-09-04 18:42:53.797085: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 1070, Compute Capability 6.1
2020-09-04 18:42:53.797204: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-04 18:42:53.797483: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1070 computeCapability: 6.1
coreClock: 1.683GHz coreCount: 15 deviceMemorySize: 7.93GiB deviceMemoryBandwidth: 238.66GiB/s
2020-09-04 18:42:53.797507: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
2020-09-04 18:42:53.799077: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.11
2020-09-04 18:42:53.799724: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-09-04 18:42:53.799867: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-09-04 18:42:53.801546: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-09-04 18:42:53.801930: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.11
2020-09-04 18:42:53.802055: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.8
2020-09-04 18:42:53.802122: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-04 18:42:53.802476: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-04 18:42:53.802778: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-09-04 18:42:53.802801: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
2020-09-04 18:42:54.070300: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-04 18:42:54.070324: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 
2020-09-04 18:42:54.070330: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N 
2020-09-04 18:42:54.070460: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-04 18:42:54.070791: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-04 18:42:54.071130: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5626 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
2020-09-04 18:42:54.071508: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
2020-09-04 18:42:54.294130: W tensorflow/core/framework/op_kernel.cc:1744] OP_REQUIRES failed at conv_ops_fused_impl.h:700 : Unimplemented: Fusion is not implemented: [BiasAdd,Add]
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1349, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "/usr/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1441, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.UnimplementedError: Fusion is not implemented: [BiasAdd,Add]
         [[{{node add}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bug.py", line 37, in <module>
    train_op.run()
  File "/usr/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 2551, in run
    _run_using_default_session(self, feed_dict, self.graph, session)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 5547, in _run_using_default_session
    session.run(operation, feed_dict)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 957, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "/usr/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1180, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "/usr/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1358, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "/usr/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnimplementedError: Fusion is not implemented: [BiasAdd,Add]
         [[node add (defined at bug.py:23) ]]

Errors may have originated from an input operation.
Input Source operations connected to node add:
 transpose_1 (defined at bug.py:15)
 conv2d/BiasAdd (defined at bug.py:19)

Original stack trace for 'add':
  File "bug.py", line 32, in <module>
    train_op = model()
  File "bug.py", line 23, in model
    a = a + upsample2x(b)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/ops/math_ops.py", line 1125, in binary_op_wrapper
    return func(x, y, name=name)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/ops/math_ops.py", line 1447, in _add_dispatch
    return gen_math_ops.add_v2(x, y, name=name)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/ops/gen_math_ops.py", line 495, in add_v2
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "/usr/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py", line 742, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "/usr/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3477, in _create_op_internal
    ret = Operation(
  File "/usr/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1949, in __init__
    self._traceback = tf_stack.extract_stack()
```

Environment that I have tried:
1. GTX1070, cuda11, cudnn8: failed
2. GTX1080Ti, cuda10.2, cudnn8: failed
3. GTX1080Ti, cuda10.2, cudnn7.6: failed
    * under the same environment, using TF1.15 instead of TF2.3: succeed
4. P100, cuda10.1, cudnn7.6: succeed
5. V100, cuda10.1, cudnn7.6: succeed
6. Colab with Tesla T4, cuda10.x, cudnn7: succeed

Maybe this is unique to GPUs that have compute capability 6.1

**Comment by amahendrakar** [comment]
@ppwwyyxx,
Looks like the issue is with the cuDNN and CUDA packages. TensorFlow 2.3 is compatible with cuDNN 7.6 and CUDA 10.1.

For more information, please check the [tested build configurations](https://www.tensorflow.org/install/source#gpu). Thanks!

**Comment by ppwwyyxx** [comment]
> TensorFlow 2.3 is compatible with cuDNN 7.6 and CUDA 10.1.

More precisely, __the prebuilt binaries of TensorFlow 2.3__ is compatible with cuDNN 7.6 and CUDA 10.1. But the code of TensorFlow 2.3 is compatible with at least cuDNN 7~8 and CUDA 10~11.
For all the versions I tested that are not using cuDNN 7.6 and CUDA 10.1, I was using tensorflow built by myself or by the archlinux distro. 

However, providing a reproducible build so others can reproduce the issue is too much work. I guess I'll just close this for now and wait to see if the bug can be reproduced when TF officially builds with CUDA 10.2+
