### ISSUE TITLE
LSTM Input Shape Error

### ISSUE THREAD

**Issue by adam-grant-hendry** [tensorflow/tensorflow#42986]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **No**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Ubuntu 18.04 (through WSL 2 on Windows 10, Version 2004, Build 20206.1000)**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **No**
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version (use command below): **2.3.0**
- Python version: **3.7.9**
- Bazel version (if compiling from source): **N/A**
- GCC/Compiler version (if compiling from source): **N/A**
- CUDA/cuDNN version: **10.1, 7.6.5.32**
- GPU model and memory: **Titan V, 12 GiB HBM2**

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Running LSTM example code produces error

```
ValueError: Input 0 of layer lstm is incompatible with the layer: expected ndim=3, found ndim=4. Full shape received: [None, 28, 28, 1]
```

**Describe the expected behavior**
Sample code works.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Source:**
======
```
import tensorflow as tf
import tensorflow_datasets as tfds
from tensorflow.compat.v1.train import Saver
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam

BATCH_SIZE = 64

(ds_train, ds_test), ds_info = tfds.load(
    "mnist",
    split=["train", "test"],
    shuffle_files=True,
    as_supervised=True,
    with_info=True,
)


def normalize_img(image, label):
    """Normalizes images: `uint8` -> `float32`."""
    return tf.cast(image, tf.float32) / 255.0, label


ds_train = ds_train.map(normalize_img, num_parallel_calls=tf.data.experimental.AUTOTUNE)
ds_train = ds_train.cache()
ds_train = ds_train.shuffle(ds_info.splits["train"].num_examples)
ds_train = ds_train.batch(128)
ds_train = ds_train.prefetch(tf.data.experimental.AUTOTUNE)

ds_test = ds_test.map(normalize_img, num_parallel_calls=tf.data.experimental.AUTOTUNE)
ds_test = ds_test.batch(128)
ds_test = ds_test.cache()
ds_test = ds_test.prefetch(tf.data.experimental.AUTOTUNE)

shape = (28, 28, 1)
print(shape)

model = Sequential(
    [
        LSTM(128, input_shape=shape, return_sequences=True),
        Dropout(0.2),
        LSTM(128),
        Dropout(0.2),
        Dense(32, activation="relu"),
        Dropout(0.2),
        Dense(10, activation="softmax"),
    ]
)

model.compile(
    loss="sparse_categorical_crossentropy",
    optimizer=Adam(lr=1e-3, decay=1e-5),
    metrics=["accuracy"],
)

model.fit(
    ds_train,
    epochs=6,
    validation_data=ds_test,
)

model.save("mnist_model.h5")
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Results:**
=======

```
2020-09-05 13:12:19.582270: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-09-05 13:12:20.625604: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-09-05 13:12:20.819050: E tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:968] could not open file to read NUMA node: /sys/bus/pci/devices/0000:41:00.0/numa_node
Your kernel may have been built without NUMA support.
2020-09-05 13:12:20.819191: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:41:00.0 name: TITAN V computeCapability: 7.0
coreClock: 1.455GHz coreCount: 80 deviceMemorySize: 12.00GiB deviceMemoryBandwidth: 607.97GiB/s
2020-09-05 13:12:20.819233: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-09-05 13:12:20.820267: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-09-05 13:12:20.821208: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-09-05 13:12:20.821395: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-09-05 13:12:20.822386: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-09-05 13:12:20.822973: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2020-09-05 13:12:20.825025: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-09-05 13:12:20.825824: E tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:968] could not open file to read NUMA node: /sys/bus/pci/devices/0000:41:00.0/numa_node
Your kernel may have been built without NUMA support.
2020-09-05 13:12:20.827090: E tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:968] could not open file to read NUMA node: /sys/bus/pci/devices/0000:41:00.0/numa_node
Your kernel may have been built without NUMA support.
2020-09-05 13:12:20.827504: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-09-05 13:12:20.827843: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-05 13:12:20.834505: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2304005000 Hz
2020-09-05 13:12:20.836670: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x556ef1d85530 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-05 13:12:20.836696: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-05 13:12:21.114332: E tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:968] could not open file to read NUMA node: /sys/bus/pci/devices/0000:41:00.0/numa_node
Your kernel may have been built without NUMA support.
2020-09-05 13:12:21.114811: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x556ef1df11a0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-09-05 13:12:21.114841: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): TITAN V, Compute Capability 7.0
2020-09-05 13:12:21.115526: E tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:968] could not open file to read NUMA node: /sys/bus/pci/devices/0000:41:00.0/numa_node
Your kernel may have been built without NUMA support.
2020-09-05 13:12:21.115846: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:41:00.0 name: TITAN V computeCapability: 7.0
coreClock: 1.455GHz coreCount: 80 deviceMemorySize: 12.00GiB deviceMemoryBandwidth: 607.97GiB/s
2020-09-05 13:12:21.115883: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-09-05 13:12:21.115904: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-09-05 13:12:21.115913: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-09-05 13:12:21.115943: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-09-05 13:12:21.115971: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-09-05 13:12:21.115983: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2020-09-05 13:12:21.115992: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-09-05 13:12:21.116516: E tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:968] could not open file to read NUMA node: /sys/bus/pci/devices/0000:41:00.0/numa_node
Your kernel may have been built without NUMA support.
2020-09-05 13:12:21.117082: E tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:968] could not open file to read NUMA node: /sys/bus/pci/devices/0000:41:00.0/numa_node
Your kernel may have been built without NUMA support.
2020-09-05 13:12:21.117231: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-09-05 13:12:21.117269: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-09-05 13:12:21.793471: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-05 13:12:21.793510: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 
2020-09-05 13:12:21.793518: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N 
2020-09-05 13:12:21.794276: E tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:968] could not open file to read NUMA node: /sys/bus/pci/devices/0000:41:00.0/numa_node
Your kernel may have been built without NUMA support.
2020-09-05 13:12:21.794418: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1485] Could not identify NUMA node of platform GPU id 0, defaulting to 0.  Your kernel may not have been built with NUMA support.
2020-09-05 13:12:21.794805: E tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:968] could not open file to read NUMA node: /sys/bus/pci/devices/0000:41:00.0/numa_node
Your kernel may have been built without NUMA support.
2020-09-05 13:12:21.794965: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10218 MB memory) -> physical GPU (device: 0, name: TITAN V, pci bus id: 0000:41:00.0, compute capability: 7.0)
(28, 28, 1)
Traceback (most recent call last):
  File "test.py", line 46, in <module>
    Dense(10, activation="softmax"),
  File "/home/hendra11/Code/Glucose_Challenge/.venv_py3_ubuntu/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/hendra11/Code/Glucose_Challenge/.venv_py3_ubuntu/lib/python3.7/site-packages/tensorflow/python/keras/engine/sequential.py", line 142, in __init__
    self.add(layer)
  File "/home/hendra11/Code/Glucose_Challenge/.venv_py3_ubuntu/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/hendra11/Code/Glucose_Challenge/.venv_py3_ubuntu/lib/python3.7/site-packages/tensorflow/python/keras/engine/sequential.py", line 206, in add
    layer(x)
  File "/home/hendra11/Code/Glucose_Challenge/.venv_py3_ubuntu/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 663, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "/home/hendra11/Code/Glucose_Challenge/.venv_py3_ubuntu/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 926, in __call__
    input_list)
  File "/home/hendra11/Code/Glucose_Challenge/.venv_py3_ubuntu/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1092, in _functional_construction_call
    input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
  File "/home/hendra11/Code/Glucose_Challenge/.venv_py3_ubuntu/lib/python3.7/site-packages/tensorflow/python/keras/engine/input_spec.py", line 180, in assert_input_compatibility
    str(x.shape.as_list()))
ValueError: Input 0 of layer lstm is incompatible with the layer: expected ndim=3, found ndim=4. Full shape received: [None, 28, 28, 1]
```

**Comment by adam-grant-hendry** [comment]
I do not know why, but for some reason the following works. I do not see the difference between this and the above, so an explanation would be appreciated for my edification:

```
import tensorflow as tf
import tensorflow_datasets as tfds
from tensorflow.compat.v1.train import Saver
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam

BATCH_SIZE = 64

mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

model = Sequential()

model.add(LSTM(128, input_shape=x_train.shape[1:], return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(128))
model.add(Dropout(0.2))
model.add(Dense(32, activation="relu"))
model.add(Dropout(0.2))
model.add(Dense(10, activation="softmax"))

# model = Sequential(
#     [
#         LSTM(128, input_shape=x_train.shape[1:], return_sequences=True),
#         Dropout(0.2),
#         LSTM(128),
#         Dropout(0.2),
#         Dense(32, activation="relu"),
#         Dropout(0.2),
#         Dense(10, activation="softmax"),
#     ]
# )

model.compile(
    loss="sparse_categorical_crossentropy",
    optimizer=Adam(lr=1e-3, decay=1e-5),
    metrics=["accuracy"],
)

model.fit(
    x_train,
    y_train,
    epochs=6,
    validation_data=(x_test, y_test),
)

model.save("mnist_model.h5")
```

**Comment by WindQAQ** [comment]
Change shape from `(28, 28, 1)` to `(28, 28)` in your first code-snippet, and it works as expected.

**Comment by amahendrakar** [comment]
@adam-grant-hendry,
Please check @WindQAQ's comment and also [this](https://stackoverflow.com/a/44583919) similar StackOverflow comment and let us know if it helps. Thanks!
