### ISSUE TITLE
Cannot import after installing with pip

### ISSUE THREAD

**Issue by piiswrong** [tensorflow/tensorflow#43]
I installed the binary with gpu support from pip, but when I import it, I get this error:
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jxie/anaconda/lib/python2.7/site-packages/tensorflow/__init__.py", line 4, in <module>
    from tensorflow.python import *
  File "/home/jxie/anaconda/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 13, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/jxie/anaconda/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 8, in <module>
    from google.protobuf import reflection as _reflection
  File "/home/jxie/anaconda/lib/python2.7/site-packages/google/protobuf/reflection.py", line 56, in <module>
    from google.protobuf.pyext import cpp_message as message_impl
  File "/home/jxie/anaconda/lib/python2.7/site-packages/google/protobuf/pyext/cpp_message.py", line 42, in <module>
    class GeneratedProtocolMessageType(_message.MessageMeta):
AttributeError: 'module' object has no attribute 'MessageMeta'

**Comment by mrry** [comment]
Hi there,

Can you check whether the `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION` environment variable is set in your shell? It looks like it might be set to `"cpp"`, which is causing an issue with the version of protobuf that ships with the binary distribution.

The following should work:

```bash
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
python
>>> import tensorflow as tf
>>>
```

**Comment by piiswrong** [comment]
That fixed it.
Thanks a lot!
