### ISSUE TITLE
ImportError: DLL load failed: The specified procedure could not be found.

### ISSUE THREAD

**Issue by danieltarita** [tensorflow/tensorflow#43026]
**System information**
OS Name	Microsoft Windows 10 Pro
Version	10.0.17134 Build 17134
System Type	x64-based PC

**Describe the problem**
I was following this [guide](https://towardsdatascience.com/object-detection-with-10-lines-of-code-d6cb4d86f606)
So I installed the dependencies in the terminal:

`pip3 install tensorflow==1.13.1 `
`pip3 install opencv-python`
`pip3 install keras==2.2.4`
`pip3 install numpy==1.16.1`
`pip3 install imageai --upgrade`

**Python Version:**
```
C:\Users\danieltsilva\Documents\Python\document_segmentaton36>python --version
Python 3.6.0
```
**Some more info:**
```
C:\Users\danieltsilva\Documents\Python\document_segmentaton36>python -m pip list
Package              Version
-------------------- ---------
absl-py              0.10.0
astor                0.8.1
certifi              2020.6.20
cycler               0.10.0
gast                 0.4.0
google-pasta         0.2.0
grpcio               1.31.0
h5py                 2.10.0
imageai              2.1.5
importlib-metadata   1.7.0
Keras                2.2.4
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.2
kiwisolver           1.2.0
Markdown             3.2.2
matplotlib           3.3.1
mock                 4.0.2
numpy                1.16.1
opencv-python        4.4.0.42
Pillow               7.2.0
pip                  20.2.2
protobuf             3.13.0
pyparsing            2.4.7
python-dateutil      2.8.1
PyYAML               5.3.1
scipy                1.5.2
setuptools           50.3.0
six                  1.15.0
tensorboard          1.13.1
tensorflow           1.13.1
tensorflow-estimator 1.13.0
termcolor            1.1.0
Werkzeug             1.0.1
wheel                0.35.1
wrapt                1.12.1
zipp                 3.1.0
```
**The code Im running** (the one on the guide i mentioned):

```
from imageai.Detection import ObjectDetection
import os

execution_path = os.getcwd()

detector = ObjectDetection()
detector.setModelTypeAsRetinaNet()
detector.setModelPath( os.path.join(execution_path , "resnet50_coco_best_v2.0.1.h5"))
detector.loadModel()
detections = detector.detectObjectsFromImage(input_image=os.path.join(execution_path , "image.jpg"), output_image_path=os.path.join(execution_path , "imagenew.jpg"))

for eachObject in detections:
    print(eachObject["name"] , " : " , eachObject["percentage_probability"] )
```

**The error I get:**
```

C:\Users\danieltsilva\Documents\Python\document_segmentaton36\venv\new_env\Scripts\python.exe C:\Users\danieltsilva\Documents\Python\document_segmentaton36\venv\new_env\document_extraction.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Users\danieltsilva\Documents\Python\document_segmentaton36\venv\new_env\document_extraction.py", line 1, in <module>
    from imageai.Detection import ObjectDetection
  File "C:\Users\danieltsilva\Documents\Python\document_segmentaton36\venv\new_env\lib\site-packages\imageai\Detection\__init__.py", line 2, in <module>
    from imageai.Detection.keras_retinanet.models.resnet import resnet50_retinanet
  File "C:\Users\danieltsilva\Documents\Python\document_segmentaton36\venv\new_env\lib\site-packages\imageai\Detection\keras_retinanet\models\resnet.py", line 19, in <module>
    import keras
  File "C:\Users\danieltsilva\Documents\Python\document_segmentaton36\venv\new_env\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Users\danieltsilva\Documents\Python\document_segmentaton36\venv\new_env\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Users\danieltsilva\Documents\Python\document_segmentaton36\venv\new_env\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Users\danieltsilva\Documents\Python\document_segmentaton36\venv\new_env\lib\site-packages\keras\backend\__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "C:\Users\danieltsilva\Documents\Python\document_segmentaton36\venv\new_env\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "C:\Users\danieltsilva\Documents\Python\document_segmentaton36\venv\new_env\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\danieltsilva\Documents\Python\document_segmentaton36\venv\new_env\lib\site-packages\tensorflow\python\__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "C:\Users\danieltsilva\Documents\Python\document_segmentaton36\venv\new_env\lib\site-packages\tensorflow\core\framework\graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "C:\Users\danieltsilva\Documents\Python\document_segmentaton36\venv\new_env\lib\site-packages\google\protobuf\descriptor.py", line 48, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.

Process finished with exit code 1

```

I don´t really know what's failing. If there is a similar issue pls hit me up (i haven´t found it), or if you have any tip tho share with me. Thank you <3

**Comment by ravikyram** [comment]
@danieltarita 

Can you please refer the [link](https://stackoverflow.com/questions/52092810/tensorflow-error-dll-load-failed-the-specified-procedure-could-not-be-found) and see if it helps you. Thanks!

**Comment by danieltarita** [comment]
Thank you, it worked! Problem solved.
Just had to run
`pip install protobuf==3.6.0`

**Comment by ravikyram** [comment]
@danieltarita 

Please, close this thread as your issue was resolved. Thanks!
