### ISSUE TITLE
A dynamic link library (DLL) initialization routine failed. 

### ISSUE THREAD

**Issue by FriedaSmith** [tensorflow/tensorflow#43130]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Window 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): libtensorflow_jni-cpu-windows-x86_64-1.14.0
- TensorFlow version: 1.14

**Describe the problem**
So I was trying to run `` using a guide for [windows 10](https://www.tensorflow.org/install/lang_java#windows) and I followed the guide exactly as it said to.
line 108 in `org/tensorflow/NativeLibrary.java`: System.load(extractResource(jniResource, jniLibName, tempDirectory));, the exception occurred:

Exception in thread "main" java.lang.UnsatisfiedLinkError: I:\Code\Android\test\SpeechRecognition_tf_lite\lib\tensorflow_jni.dll: A dynamic link library (DLL) initialization routine failed. 
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.load0(Unknown Source)
	at java.lang.System.load(Unknown Source)
	at org.tensorflow.NativeLibrary.load(NativeLibrary.java:108)
	at org.tensorflow.TensorFlow.init(TensorFlow.java:67)
	at org.tensorflow.TensorFlow.<clinit>(TensorFlow.java:82)
	at org.tensorflow.Graph.<clinit>(Graph.java:479)
	at TFInterface.TensorFlowInferenceInterface.<init>(TensorFlowInferenceInterface.java:61)
	at ASR.Chain.<init>(Chain.java:60)
	at ASR.ASR.main(ASR.java:6)

**Comment by ravikyram** [comment]
@FriedaSmith 

What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the [latest microsoft visual c++ redistributable from here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).
.Also, please follow the instructions from to install from [Tensorflow website](https://www.tensorflow.org/install/source_windows).

Please, check Your CPU/Python is on 32 bits?Please, refer #36167 and see if it helps you.
Please, refer similar issue #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
Thanks!

**Comment by FriedaSmith** [comment]
@ravikyram Hello. Must source code be used to build tensorflow? Can only `libtensorflow_jni-cpu-windows-x86_64-1.14.0/tensorflow_jni.dll` and `libtensorflow-1.14.0.jar` be used tensorflow?
In eclipse, I just use `System.load (extractresource (jniresource, jnilibname, tempdirectory))` function loads `tensorflow_ jni.dll`. I also installed latest microsoft visual c++ redistributable. 
CPU: intel core i7 880 64bit

**Comment by ravikyram** [comment]
@FriedaSmith 

Please, provide the exact sequence of commands / steps that you executed before running into the problem. Thanks!

**Comment by FriedaSmith** [comment]
1. Go to: https://www.tensorflow.org/install/lang_java and download libtensorflow.jar and Java Native Interface (JNI) file, save it to project root;
2. Copy Example code from https://www.tensorflow.org/install/lang_java and save `HelloTensorFlow .java`

import org.tensorflow.Graph;
import org.tensorflow.Session;
import org.tensorflow.Tensor;
import org.tensorflow.TensorFlow;

public class HelloTensorFlow {
	public static void main(String[] args) throws Exception {
		try (Graph g = new Graph()) {
			final String value = "Hello from " + TensorFlow.version();
			try (Tensor t = Tensor.create(value.getBytes("UTF-8"))) {
				g.opBuilder("Const", "MyConst").setAttr("dtype", t.dataType()).setAttr("value", t).build();
			}

			try (Session s = new Session(g); Tensor output = s.runner().fetch("MyConst").run().get(0)) {
				System.out.println(new String(output.bytesValue(), "UTF-8"));
			}
		}
	}
}

3. Put `HelloTensorFlow.java`, `libtensorflow.jar`, and `tensorflow_jni.dll` in the same directory.
4. Run the command: `javac -cp libtensorflow-1.3.0.jar HelloTensorFlow.java` and `java -cp libtensorflow-1.3.0.jar;. -Djava.library.path=jni HelloTensorFlow`.
I:\Code\Android\test\test>`javac -cp libtensorflow-1.3.0.jar HelloTensorFlow.java`
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

I:\Code\Android\test\test>`java -cp libtensorflow-1.3.0.jar;. -Djava.library.path=jni HelloTensorFlow`
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Exception in thread "main" java.lang.UnsatisfiedLinkError: Cannot find TensorFlow native library for OS: windows, architecture: x86_64. See https://github.com/tensorflow/tensorflow/tree/master/tensorflow/java/README.md for possible solutions (such as building the library from source). Additional information on attempts to find the native library can be obtained by adding org.tensorflow.NativeLibrary.DEBUG=1 to the system properties of the JVM.
        at org.tensorflow.NativeLibrary.load(NativeLibrary.java:66)
        at org.tensorflow.TensorFlow.init(TensorFlow.java:36)
        at org.tensorflow.TensorFlow.<clinit>(TensorFlow.java:40)
        at org.tensorflow.Graph.<clinit>(Graph.java:194)
        at HelloTensorFlow.main(HelloTensorFlow.java:8)

**Comment by gowthamkpr** [comment]
@FriedaSmith Please take a look at this [issue](https://github.com/tensorflow/tensorflow/issues/14456) and let me know it it helps.!

**Comment by FriedaSmith** [comment]
@gowthamkpr Thank you. This is a CPU problem. So I changed my computer and it worked.
