### ISSUE TITLE
While training fasterRCNN with Tensoflow Object Detection API 2.(using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.)

### ISSUE THREAD

**Issue by danial880** [tensorflow/tensorflow#43175]
**System information**
- OS Platform and Distribution: Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): conda
- TensorFlow version (use command below): 2.2.0
- Python version: 3.6.10
- CUDA/cuDNN version: 10.1.243 / 7.6.5
- GPU model and memory: 1080ti 11GB

Command used to run training:
    python3 model_main_tf2.py     --pipeline_config_path=training/pipeline.config     --model_dir=training     --num_train_steps=10000     --sample_1_of_n_eval_examples=1     --alsologtostderr

Traceback:
2020-09-12 14:20:06.611317: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-09-12 14:20:07.902280: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-09-12 14:20:07.932835: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-12 14:20:07.933417: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.721GHz coreCount: 28 deviceMemorySize: 10.91GiB deviceMemoryBandwidth: 451.17GiB/s
2020-09-12 14:20:07.933439: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-09-12 14:20:07.934581: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-09-12 14:20:07.935660: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-09-12 14:20:07.935852: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-09-12 14:20:07.937035: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-09-12 14:20:07.937660: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2020-09-12 14:20:07.940093: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-09-12 14:20:07.940227: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-12 14:20:07.940860: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-12 14:20:07.941301: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-09-12 14:20:07.941543: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-12 14:20:07.945801: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 4200000000 Hz
2020-09-12 14:20:07.946049: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x56548f8ff7c0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-12 14:20:07.946060: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-12 14:20:08.017594: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-12 14:20:08.028832: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x565490ae2c00 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-09-12 14:20:08.028848: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 1080 Ti, Compute Capability 6.1
2020-09-12 14:20:08.029003: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-12 14:20:08.029293: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.721GHz coreCount: 28 deviceMemorySize: 10.91GiB deviceMemoryBandwidth: 451.17GiB/s
2020-09-12 14:20:08.029314: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-09-12 14:20:08.029341: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-09-12 14:20:08.029354: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-09-12 14:20:08.029367: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-09-12 14:20:08.029379: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-09-12 14:20:08.029392: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2020-09-12 14:20:08.029405: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-09-12 14:20:08.029445: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-12 14:20:08.029749: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-12 14:20:08.030020: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-09-12 14:20:08.030039: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-09-12 14:20:08.314944: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-12 14:20:08.314974: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 
2020-09-12 14:20:08.314995: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N 
2020-09-12 14:20:08.315166: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-12 14:20:08.315535: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-12 14:20:08.315849: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9866 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)
I0912 14:20:08.317715 140151783593792 mirrored_strategy.py:341] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)
INFO:tensorflow:Maybe overwriting train_steps: 10000
I0912 14:20:08.320816 140151783593792 config_util.py:552] Maybe overwriting train_steps: 10000
INFO:tensorflow:Maybe overwriting use_bfloat16: False
I0912 14:20:08.320905 140151783593792 config_util.py:552] Maybe overwriting use_bfloat16: False
WARNING:tensorflow:num_readers has been reduced to 1 to match input file shards.
W0912 14:20:08.454587 140151783593792 dataset_builder.py:83] num_readers has been reduced to 1 to match input file shards.
WARNING:tensorflow:From /home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/object_detection/builders/dataset_builder.py:100: parallel_interleave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.experimental.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.experimental_deterministic`.
W0912 14:20:08.457228 140151783593792 deprecation.py:323] From /home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/object_detection/builders/dataset_builder.py:100: parallel_interleave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.experimental.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.experimental_deterministic`.
WARNING:tensorflow:From /home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/object_detection/builders/dataset_builder.py:175: DatasetV1.map_with_legacy_function (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.map()
W0912 14:20:08.479154 140151783593792 deprecation.py:323] From /home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/object_detection/builders/dataset_builder.py:175: DatasetV1.map_with_legacy_function (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.map()
WARNING:tensorflow:AutoGraph could not transform <bound method TfExampleDecoder.decode of <object_detection.data_decoders.tf_example_decoder.TfExampleDecoder object at 0x7f775eae7940>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Constant'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
W0912 14:20:08.549343 140151783593792 ag_logging.py:146] AutoGraph could not transform <bound method TfExampleDecoder.decode of <object_detection.data_decoders.tf_example_decoder.TfExampleDecoder object at 0x7f775eae7940>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Constant'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING:tensorflow:AutoGraph could not transform <function train_input.<locals>.transform_and_pad_input_data_fn at 0x7f775eab3400> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
W0912 14:20:08.632742 140151783593792 ag_logging.py:146] AutoGraph could not transform <function train_input.<locals>.transform_and_pad_input_data_fn at 0x7f775eab3400> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING:tensorflow:From /home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py:201: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
W0912 14:20:08.635260 140151783593792 deprecation.py:323] From /home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py:201: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
Traceback (most recent call last):
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 584, in converted_call
    converted_f = conversion.convert(target_entity, program_ctx)
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/autograph/impl/conversion.py", line 119, in convert
    entity, program_ctx.options, program_ctx, custom_vars)
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 412, in transform_function
    extra_locals)
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 373, in _transformed_factory
    nodes, ctx = self._transform_function(fn, user_context)
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 339, in _transform_function
    node = self.transform_ast(node, context)
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/autograph/impl/conversion.py", line 70, in transform_ast
    node = activity.resolve(node, ctx, None)
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/autograph/pyct/static_analysis/activity.py", line 705, in resolve
    return ActivityAnalyzer(context, parent_scope).visit(node)
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/autograph/pyct/transformer.py", line 445, in visit
    result = super(Base, self).visit(node)
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/autograph/pyct/static_analysis/activity.py", line 575, in visit_FunctionDef
    node = self._visit_arg_annotations(node)
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/autograph/pyct/static_analysis/activity.py", line 551, in _visit_arg_annotations
    node = self._visit_arg_declarations(node)
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/autograph/pyct/static_analysis/activity.py", line 556, in _visit_arg_declarations
    node.args.posonlyargs = self._visit_node_list(node.args.posonlyargs)
AttributeError: 'arguments' object has no attribute 'posonlyargs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "model_main_tf2.py", line 113, in <module>
    tf.compat.v1.app.run()
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "model_main_tf2.py", line 110, in main
    record_summaries=FLAGS.record_summaries)
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/object_detection/model_lib_v2.py", line 526, in train_loop
    train_dataset_fn)
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py", line 1128, in experimental_distribute_datasets_from_function
    dataset_fn, options)
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/distribute/mirrored_strategy.py", line 503, in _experimental_distribute_datasets_from_function
    self._container_strategy())
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/distribute/input_lib.py", line 136, in get_distributed_datasets_from_function
    strategy)
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/distribute/input_lib.py", line 1183, in __init__
    dataset_fn))
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/distribute/input_lib.py", line 1767, in _create_datasets_per_worker_with_input_context
    dataset = dataset_fn(ctx)
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/object_detection/model_lib_v2.py", line 521, in train_dataset_fn
    input_context=input_context)
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/object_detection/inputs.py", line 838, in train_input
    reduce_to_frame_fn=reduce_to_frame_fn)
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/object_detection/builders/dataset_builder.py", line 196, in build
    batch_size, input_reader_config)
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/object_detection/builders/dataset_builder.py", line 175, in dataset_map_fn
    fn_to_map, num_parallel_calls=num_parallel_calls)
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2564, in map_with_legacy_function
    use_legacy_function=True))
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 4084, in __init__
    use_legacy_function=use_legacy_function)
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3339, in __init__
    self._function.add_to_graph(ops.get_default_graph())
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 544, in add_to_graph
    self._create_definition_if_needed()
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 376, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 407, in _create_definition_if_needed_impl
    capture_resource_var_by_value=self._capture_resource_var_by_value)
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 969, in func_graph_from_py_func
    outputs = func(*func_graph.inputs)
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3331, in wrapper_fn
    ret = _wrapper_helper(*args)
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3299, in _wrapper_helper
    ret = autograph.tf_convert(func, ag_ctx)(*nested_args)
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 255, in wrapper
    return converted_call(f, args, kwargs, options=options)
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 591, in converted_call
    return _fall_back_unconverted(f, args, kwargs, options, e)
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 398, in _fall_back_unconverted
    return _call_unconverted(f, args, kwargs, options)
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 339, in _call_unconverted
    return f(*args, **kwargs)
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/object_detection/inputs.py", line 819, in transform_and_pad_input_data_fn
    tensor_dict=transform_data_fn(tensor_dict),
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/object_detection/inputs.py", line 249, in transform_input_data
    out_tensor_dict = data_augmentation_fn(out_tensor_dict)
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/object_detection/inputs.py", line 577, in augment_input_data
    include_dense_pose=include_dense_pose))
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/object_detection/core/preprocessor.py", line 4591, in preprocess
    results = func(*args, **params)
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/object_detection/core/preprocessor.py", line 4093, in random_square_crop_by_scale
    if ymin == 0:
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 877, in __bool__
    self._disallow_bool_casting()
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 490, in _disallow_bool_casting
    self._disallow_in_graph_mode("using a `tf.Tensor` as a Python `bool`")
  File "/home/convsys/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 479, in _disallow_in_graph_mode
    " this function with @tf.function.".format(task))
tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.

Config File
`

model {
  faster_rcnn {
    num_classes: 33
    image_resizer {
      keep_aspect_ratio_resizer {
        min_dimension: 800
        max_dimension: 1333
        pad_to_max_dimension: true
      }
    }
    feature_extractor {
      type: 'faster_rcnn_resnet101_keras'
    }
    first_stage_anchor_generator {
      grid_anchor_generator {
        scales: [0.25, 0.5, 1.0, 2.0]
        aspect_ratios: [0.5, 1.0, 2.0]
        height_stride: 16
        width_stride: 16
      }
    }
    first_stage_box_predictor_conv_hyperparams {
      op: CONV
      regularizer {
        l2_regularizer {
          weight: 0.0
        }
      }
      initializer {
        truncated_normal_initializer {
          stddev: 0.01
        }
      }
    }
    first_stage_nms_score_threshold: 0.0
    first_stage_nms_iou_threshold: 0.7
    first_stage_max_proposals: 300
    first_stage_localization_loss_weight: 2.0
    first_stage_objectness_loss_weight: 1.0
    initial_crop_size: 14
    maxpool_kernel_size: 2
    maxpool_stride: 2
    second_stage_box_predictor {
      mask_rcnn_box_predictor {
        use_dropout: false
        dropout_keep_probability: 1.0
        fc_hyperparams {
          op: FC
          regularizer {
            l2_regularizer {
              weight: 0.0
            }
          }
          initializer {
            variance_scaling_initializer {
              factor: 1.0
              uniform: true
              mode: FAN_AVG
            }
          }
        }
      }
    }
    second_stage_post_processing {
      batch_non_max_suppression {
        score_threshold: 0.0
        iou_threshold: 0.6
        max_detections_per_class: 100
        max_total_detections: 100
      }
      score_converter: SOFTMAX
    }
    second_stage_localization_loss_weight: 2.0
    second_stage_classification_loss_weight: 1.0
  }
}

train_config: {
  batch_size: 4
  num_steps: 200000
  optimizer {
    momentum_optimizer: {
      learning_rate: {
        cosine_decay_learning_rate {
          learning_rate_base: 0.01
          total_steps: 200000
          warmup_learning_rate: 0.0
          warmup_steps: 5000
        }
      }
      momentum_optimizer_value: 0.9
    }
    use_moving_average: false
  }
  gradient_clipping_by_norm: 10.0
  fine_tune_checkpoint_version: V2
  fine_tune_checkpoint: "/media/convsys/c924758e-a96b-40c5-86de-4d47f53b16db/models-master/research/object_detection/faster_rcnn_resnet101_v1_800x1333_coco17_gpu-8/checkpoint/ckpt-0"
  fine_tune_checkpoint_type: "classification"
  data_augmentation_options {
    random_horizontal_flip {
    }
  }

  data_augmentation_options {
    random_adjust_hue {
    }
  }

  data_augmentation_options {
    random_adjust_contrast {
    }
  }

  data_augmentation_options {
    random_adjust_saturation {
    }
  }

  data_augmentation_options {
     random_square_crop_by_scale {
      scale_min: 0.6
      scale_max: 1.3
    }
  }
}

train_input_reader: {
  label_map_path: "training/fashion.pbtxt"
  tf_record_input_reader {
    input_path: "training/train.record"
  }
}

eval_config: {
  metrics_set: "coco_detection_metrics"
  use_moving_averages: false
  batch_size: 1;
}

eval_input_reader: {
  label_map_path: "training/fashion.pbtxt"
  shuffle: false
  num_epochs: 1
  tf_record_input_reader {
    input_path: "training/test.record"
  }
}`

**Comment by danial880** [comment]
Already seen [https://github.com/tensorflow/tensorflow/issues/40143](url)

**Comment by bhack** [comment]
Are you using https://github.com/tensorflow/models/tree/master/research/object_detection?

**Comment by danial880** [comment]
> Are you using https://github.com/tensorflow/models/tree/master/research/object_detection?

yes

**Comment by bhack** [comment]
Ok please check that you have a fresh version of that repository. If you still have a problem please close this and open an issue directly in that repository.
