### ISSUE TITLE
Issue with Training CenterNet Resnet50 V2 Keypoints 512x512 

### ISSUE THREAD

**Issue by pardeep-kesnani1234** [tensorflow/tensorflow#43179]
Hello i am trying to train  CenterNet Resnet50 V2 Keypoints 512x512  with hand dataset 'https://www.robots.ox.ac.uk/~vgg/data/hands/downloads/hand_dataset.tar.gz'  but facing issue with label_map.pbxt and don't know how to resolve this issue. 

**Errors i got during training:**  
File "/usr/local/lib/python3.6/dist-packages/object_detection/builders/model_builder.py", line 991, in _build_center_net_model
    kp_params = keypoint_proto_to_params(task, keypoint_map_dict)
  File "/usr/local/lib/python3.6/dist-packages/object_detection/builders/model_builder.py", line 809, in keypoint_proto_to_params
    label_map_item = keypoint_map_dict[kp_config.keypoint_class_name]
KeyError: '/m/01g317'

**Comment by bhack** [comment]
Are you using Centernet from model garden?

**Comment by pardeep-kesnani1234** [comment]
> Are you using Centernet from model garden?

yes brother, i am using from model garden with these model files: 
![image](https://user-images.githubusercontent.com/26037495/93018021-70aeab80-f5e6-11ea-8fba-f38d96544a16.png)

**Comment by bhack** [comment]
Ok, so please close this and open the ticket on https://github.com/tensorflow/models

**Comment by Saduf2019** [comment]
@pardeep-kesnani1234 
Please feel free to close this issue as, it will be tracked in the models repo.

**Comment by PranavPuranik** [comment]
Even I am getting a key error for centernet

Traceback - 
```
Traceback (most recent call last):
  File "/content/models/research/object_detection/model_main_tf2.py", line 113, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/content/models/research/object_detection/model_main_tf2.py", line 110, in main
    record_summaries=FLAGS.record_summaries)
  File "/usr/local/lib/python3.6/dist-packages/object_detection/model_lib_v2.py", line 511, in train_loop
    model_config=model_config, is_training=True)
  File "/usr/local/lib/python3.6/dist-packages/object_detection/builders/model_builder.py", line 1089, in build
    add_summaries)
  File "/usr/local/lib/python3.6/dist-packages/object_detection/builders/model_builder.py", line 996, in _build_center_net_model
    kp_params = keypoint_proto_to_params(task, keypoint_map_dict)
  File "/usr/local/lib/python3.6/dist-packages/object_detection/builders/model_builder.py", line 814, in keypoint_proto_to_params
    label_map_item = keypoint_map_dict[kp_config.keypoint_class_name]
KeyError: '/m/01g317'
```

configs - 
```
'centernet_hourglass_3': {
        'model_name': 'centernet_hourglass104_512x512_kpts_coco17_tpu-32',
        'base_pipeline_file': 'centernet_hourglass104_512x512_kpts_coco17_tpu-32.config',
        'pretrained_checkpoint': 'centernet_hg104_512x512_kpts_coco17_tpu-32.tar.gz',
        'batch_size': 8
    },
```
