### ISSUE TITLE
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

### ISSUE THREAD

**Issue by Pranab-pronay** [tensorflow/tensorflow#43192]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):win10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
- TensorFlow version:2.2.0
- Python version:3.8.5
- Installed using virtualenv? pip? conda?:conda
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.1
- GPU model and memory:nvidia940m, 4 gb

**Describe the problem**  I am confident that I've installed Cuda and cudnn properly and added path in the environment variable, but still, I am getting this error

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I am following their step: https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/install.html#tensorflow-object-detection-api-installation
When I tried for "python object_detection/builders/model_builder_tf2_test.py" I am facing this error

**Any other info / logs**  (tensorflow1) C:\tensorflow1\models\research>python object_detection/builders/model_builder_tf2_test.py
Traceback (most recent call last):
  File "C:\Users\Pranab\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Pranab\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Pranab\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Pranab\Anaconda3\envs\tensorflow1\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Pranab\Anaconda3\envs\tensorflow1\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "object_detection/builders/model_builder_tf2_test.py", line 21, in <module>
    import tensorflow.compat.v1 as tf
  File "C:\Users\Pranab\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Pranab\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\__init__.py", line 50, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Pranab\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 69, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Pranab\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Pranab\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Pranab\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Pranab\Anaconda3\envs\tensorflow1\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Pranab\Anaconda3\envs\tensorflow1\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by bhack** [comment]
We don't support Anaconda installation.
Please try to install TF with pip/venv as https://www.tensorflow.org/install/pip
If you need Anaconda you could rely on third party support at https://docs.anaconda.com/anaconda/user-guide/tasks/tensorflow/

/cc @karmel @av8ramit We could improve this new @tensorflow-butler reply with a better text when there is an Anaconda string in the issue description. 
It Is a quite recurrent case specially for Windows tickets. I've triaged many of these just the last few days.

**Comment by Pranab-pronay** [comment]
I fixed this by running system.py, Btw thanks for the reply.

**Comment by bhack** [comment]
From you last log I still see that you are inside an `Anaconda3 envs`. 
Under the [conda tab in the documentation](https://www.tensorflow.org/install/pip#conda): 
> While the TensorFlow provided pip package is recommended, a community-supported Anaconda package is available. To install, read the Anaconda TensorFlow guide.

**Comment by Pranab-pronay** [comment]
Sorry boss, I meant that I've used pip to install tf, yes I am using anaconda. Maybe still I am wrong

**Comment by bhack** [comment]
We support python venv and pip. If you want you can follow the guidelines at https://www.tensorflow.org/install/pip#windows_1.

Instead if you still need to use conda envs and Anaconda you need to find support at: https://docs.anaconda.com/anaconda/user-guide/tasks/tensorflow/

Please also respect our code of conduct (/cc @theadactyl) : https://github.com/tensorflow/tensorflow/blob/master/CODE_OF_CONDUCT.md

**Comment by Pranab-pronay** [comment]
I meant sir by addressing boss, Maybe it sounded offensive due to cultural differences,  Thankyou

**Comment by Pranab-pronay** [comment]
@bhack can you help me out:-

(tensorflow1) C:\tensorflow1\models\research>python object_detection/builders/model_builder_tf2_test.py
Traceback (most recent call last):
  File "object_detection/builders/model_builder_tf2_test.py", line 21, in <module>
    import tensorflow.compat.v1 as tf
  File "C:\Users\Pranab\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Pranab\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\Pranab\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\eager\context.py", line 32, in <module>
    from tensorflow.core.framework import function_pb2
  File "C:\Users\Pranab\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\core\framework\function_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: cannot import name 'descriptor' from 'google.protobuf' (unknown location)

I am not getting this error.

**Comment by bhack** [comment]
We cannot support you on Anacoda sorry.

**Comment by Saduf2019** [comment]
@Pranab-pronay 
You could be facing this issue because of the following reasons

- You you running 32-bit Python or 32-bit OS
- Please take a look at the [system requirements](https://www.tensorflow.org/install/pip#system-requirements) and check if you have the correct dependencies installed.
- Your CPU does not support AVX instructions, please provide the make and model of your CPU in this case.

Also, check these similar duplicate issues: #42058 #41596 #40459 #39007 #38916 #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 .

In case you still face issues after verifying the above, please create a issue on [Anaconda repo](https://github.com/ContinuumIO/anaconda-issues/issues)., and move this to closed status.
Thanks!
