### ISSUE TITLE
Class weights issue with sparse data from tf.data.dataset where y.shape.rank is None

### ISSUE THREAD

**Issue by hyw2** [tensorflow/tensorflow#43248]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: yes
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
-   **TensorFlow installed from (source or binary)**:
-   **TensorFlow version (use command below)**: 2.2
-   **Python version**: 3.6.7
-   **CUDA/cuDNN version**: 10.2
-   **GPU model and memory**: RTX 2070, 32
-   **Exact command to reproduce**:

Sorry, this is my first time submitting an issue, this is a small issue with a simple fix but I'm not sure if what I added is a long-term solution. Unfortunately, I can't divulge the full code, but I can explain the steps I took to reproduce the error. I have a simple 3-layer deep model and a tf.dataset generate like so:

```
#model instantiated above
model.compile(
            loss = 'sparse_categorical_crossentropy',
            metrics=['sparse_categorical_accuracy'],
            optimizer=tf.keras.optimizers.Adam(learning_rate=0.01)
            )

class generator:
    def __call__(self, file, batch_size): #file is a parquet file
        actual_file = file.decode("utf-8") 
        df = pd.read_parquet(actual_file)
        df = df.astype("float16")
        df[df.columns[df.shape[1]-1]] = df[df.columns[df.shape[1]-1]].astype(int)
        filefinish = False
        fileIndex = 0
        fileEnd = df.shape[0]
        fileX = df.shape[1]
        while not filefinish:
            if fileIndex + batch_size >= fileEnd:
                yield df.iloc[fileIndex:fileEnd, 0:fileX-1].values, df.iloc[fileIndex:fileEnd, fileX-1:fileX].values.reshape(fileEnd-fileIndex)
                filefinish = True
            else:
                yield df.iloc[fileIndex:fileIndex+batch_size, 0:fileX-1].values, df.iloc[fileIndex:fileIndex+batch_size, fileX-1:fileX].values.reshape(batch_size)
                fileIndex += batch_size

training_files_dir = [LIST OF TRAINING FILES]
BATCH_SIZE, EPOCHS = 4096, 10

training_generator = tf.data.Dataset.from_tensor_slices(training_files_dir)
training_generator = training_generator.interleave(lambda filename: tf.data.Dataset.from_generator(
        generator(), 
        output_types=(tf.float16, tf.int8),
        args=(filename, BATCH_SIZE,)), num_parallel_calls=tf.data.experimental.AUTOTUNE, cycle_length=2)
training_generator = training_generator.repeat(EPOCHS)

model.fit(x=training_generator, epochs=EPOCHS, steps_per_epoch=EPOCH_STEPS, validation_steps=VALIDATION_STEPS, validation_data=validation_generator, class_weight=class_weights, callbacks=all_callbacks, verbose=1)
```

### Describe the problem
Using class weights on fit function and sparse data from tf.data produces the error below as y.shape.rank is None. I added an if statement to data_adapter.py to fix it, but I'm not sure if this is a sustainable fix to leave in for the future.

```
if y.shape.rank != None:
        if y.shape.rank > 2:
          raise ValueError("`class_weight` not supported for "
                                                  "3+ dimensional targets.")
```

### Source code / logs
```
Traceback (most recent call last):
  File "c:/Users/Harry Wang/Desktop/fnma-deep-mortage-risk/fnma_dnn/main.py", line 448, in <module>
    model._model.fit(x=training_generator, epochs=EPOCHS, steps_per_epoch=EPOCH_STEPS, validation_steps=VALIDATION_STEPS, validation_data=validation_generator, class_weight=class_weights, callbacks=all_callbacks, verbose=1)
  File "C:\Users\Harry Wang\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training.py", line 66, in _method_wrapper 
    return method(self, *args, **kwargs)
  File "C:\Users\Harry Wang\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training.py", line 815, in fit
    model=self)
  File "C:\Users\Harry Wang\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 1117, in __init__  
    dataset = dataset.map(_make_class_weight_map_fn(class_weight))
  File "C:\Users\Harry Wang\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 1621, in map
    return MapDataset(self, map_func, preserve_cardinality=True)
  File "C:\Users\Harry Wang\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 3981, in __init__
    use_legacy_function=use_legacy_function)
  File "C:\Users\Harry Wang\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 3221, in __init__       
    self._function = wrapper_fn.get_concrete_function()
  File "C:\Users\Harry Wang\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\function.py", line 2532, in get_concrete_function
    *args, **kwargs)
  File "C:\Users\Harry Wang\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\function.py", line 2496, in _get_concrete_function_garbage_collected
    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
  File "C:\Users\Harry Wang\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\function.py", line 2777, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\Users\Harry Wang\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\function.py", line 2667, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "C:\Users\Harry Wang\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Users\Harry Wang\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 3214, in wrapper_fn
    ret = _wrapper_helper(*args)
  File "C:\Users\Harry Wang\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 3156, in _wrapper_helper
    ret = autograph.tf_convert(func, ag_ctx)(*nested_args)
  File "C:\Users\Harry Wang\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 262, in wrapper
    return converted_call(f, args, kwargs, options=options)
  File "C:\Users\Harry Wang\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 492, in converted_call
    return _call_unconverted(f, args, kwargs, options)
  File "C:\Users\Harry Wang\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 346, in _call_unconverted
    return f(*args, **kwargs)
  File "C:\Users\Harry Wang\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 1248, in _class_weights_map_fn
    if y.shape.rank > 2:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

**Comment by bhack** [comment]
Check https://github.com/keras-team/keras/issues/3653#issuecomment-243939748

**Comment by hyw2** [comment]
My apologies, thanks for the link! Out of curiosity, would there be any way to improve how sample weights could be implemented? Adding weights with each input seems to be a little repetitive with large datasets with large numbers of classes.

**Comment by bhack** [comment]
> Out of curiosity, would there be any way to improve how sample weights could be implemented? Adding weights with each input seems to be a little repetitive with large datasets with large numbers of classes.

This type of support requests are for our Stackoverflow: https://stackoverflow.com/questions/tagged/tensorflow

**Comment by yufengma** [comment]
I encountered the same issue. 
I think the root cause comes from not specifying the output_shapes during from_generator() so that during class weighting, y.shape.rank returns None.
