### ISSUE TITLE
Importing Tensorflow after using pyinstaller (ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.)

### ISSUE THREAD

**Issue by ApurvaDani** [tensorflow/tensorflow#43259]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.14
- Python version: 3.7.8
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: None (CPU)
- GPU model and memory: None

**Describe the problem**
I have installed tensorflow using conda and it works fine in the conda environment. I converted my app into binary file using pyinstaller. While running .exe file, it throws ImportError

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Used pyinstaller to convert my flask app to .exe file
First issue encountered: No module named tensorflow
Copied the tensorflow folder from the conda environment and pasted it in directory where app.exe is located.
Now facing the Import Error
Is there something else, I need to copy to the working directory or a path to set?

**Any other info / logs**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "R:\armorfinal\cheque_locate_ws\dist\app\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "R:\armorfinal\cheque_locate_ws\dist\app\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "R:\armorfinal\cheque_locate_ws\dist\app\tensorflow\python\pywrap_tensorflow.py", line 59, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "R:\armorfinal\cheque_locate_ws\dist\app\tensorflow\python\pywrap_tensorflow_internal.py", line 35, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "R:\armorfinal\cheque_locate_ws\dist\app\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Apurva\AppData\Local\Programs\Python\Python38\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Apurva\AppData\Local\Programs\Python\Python38\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

**Comment by ApurvaDani** [comment]
It was using pyinstaller installed in the base environment which did not have tensorflow installed.
This solved the issue

conda activate your_env_name
conda install -c conda-forge pyinstaller
