### ISSUE TITLE
ImportError: No module named _pywrap_tensorflow

### ISSUE THREAD

**Issue by trsonderm** [tensorflow/tensorflow#4326]
Traceback (most recent call last):
  File "./train.py", line 3, in <module>
    import tensorflow as tf
  File "/Users/thomassonderman/tensorflow_gpu/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/Users/thomassonderman/tensorflow_gpu/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 48, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/thomassonderman/tensorflow_gpu/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 21, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/Users/thomassonderman/tensorflow_gpu/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _pywrap_tensorflow

Related Problem:
SyntaxNet ImportError: No module named _pywrap_tensorflow #97
Fix did not work

Environment:
Macbook retina Nvidia Os: El Capitan 

Installed version of CUDA and cuDNN: 
cuda 7.5

(tensorflow_gpu) Thomass-MacBook-Pro:DIS thomassonderman$ python -c "import tensorflow; print(tensorflow.__version__)"
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.7.5.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.5.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.7.5.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.1.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.7.5.dylib locally
0.10.0rc0

If installed from source, provide 

The commit hash (`git rev-parse HEAD`)

3cb39956e622b322e43547cf2b6e337020643f21

Build label: 0.3.1-homebrew
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Aug 4 09:58:27 2016 (1470304707)
Build timestamp: 1470304707
Build timestamp as int: 1470304707

import tensorflow works, just not any examples

### What other attempted solutions have you tried?
redownloading the source and recompiling, reinstalling pip package.
setting up bazel-completion

**Comment by trsonderm** [comment]
I was running it as ./train.py instead of python train.py
