### ISSUE TITLE
Can't Access Tensorflow Dependencies After Install

### ISSUE THREAD

**Issue by lkoll** [tensorflow/tensorflow#43272]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary):  pip install tensorflow
- TensorFlow version:
- Python version: 3.7
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1/cudnn-10.1-windows10-x64-v7.6.5.32
- GPU model and memory: nvidia rtx 2060 

**Describe the problem**
Tensorflow not recognizing cudnn is installed. I have verified the files exist in the directories that I have added to my path variable, still says the file doesn't exist.
![image](https://user-images.githubusercontent.com/21284577/93372548-a4bde280-f819-11ea-98aa-ea549bdd06e3.png)
![image](https://user-images.githubusercontent.com/21284577/93372639-c5863800-f819-11ea-8a0c-3ac1c420910c.png)

**Provide the exact sequence of commands / steps that you executed before running into the problem**
 from keras.models import Sequential

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

from keras.models import Sequential
Using TensorFlow backend.
Traceback (most recent call last):

  File "C:\Users\Luke\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\platform\self_check.py", line 87, in preload_check
    ctypes.WinDLL(build_info.cudnn_dll_name)

  File "C:\Users\Luke\anaconda3\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)

OSError: [WinError 126] The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-1-9c5e0a19b646>", line 1, in <module>
    from keras.models import Sequential

  File "C:\Users\Luke\anaconda3\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils

  File "C:\Users\Luke\anaconda3\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils

  File "C:\Users\Luke\anaconda3\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K

  File "C:\Users\Luke\anaconda3\lib\site-packages\keras\backend\__init__.py", line 1, in <module>
    from .load_backend import epsilon

  File "C:\Users\Luke\anaconda3\lib\site-packages\keras\backend\load_backend.py", line 90, in <module>
    from .tensorflow_backend import *

  File "C:\Users\Luke\anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf

  File "C:\Users\Luke\AppData\Roaming\Python\Python37\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import

  File "C:\Users\Luke\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow

  File "C:\Users\Luke\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()

  File "C:\Users\Luke\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\platform\self_check.py", line 97, in preload_check
    % (build_info.cudnn_dll_name, build_info.cudnn_version_number))

ImportError: Could not find 'cudnn64_7.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 7 from this URL: https://developer.nvidia.com/cudnn

**Comment by ravikyram** [comment]
@lkoll 

Can you please follow the guidelines from [here](https://www.tensorflow.org/install/gpu) and please make sure that all software and hardware requirements are met from [here](https://www.tensorflow.org/install/gpu#windows_setup).Thanks!
