### ISSUE TITLE
Problem with using tf.contrib.metrics.streaming_mean_iou

### ISSUE THREAD

**Issue by ziky90** [tensorflow/tensorflow#4331]
I am trying to use `tf.contrib.metrics.streaming_mean_iou` in my network and I am getting following Error.

```
W tensorflow/core/framework/op_kernel.cc:940] Failed precondition: Attempting to use uninitialized value mean_iou/total_confusion_matrix
	 [[Node: mean_iou/total_confusion_matrix/read = Identity[T=DT_INT64, _class=["loc:@mean_iou/total_confusion_matrix"], _device="/job:localhost/replica:0/task:0/cpu:0"](mean_iou/total_confusion_matrix)]]
Traceback (most recent call last):
....
....
File "/Users/janzikes/anaconda2/envs/research/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 710, in run
    run_metadata_ptr)
  File "/Users/janzikes/anaconda2/envs/research/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 908, in _run
    feed_dict_string, options, run_metadata)
  File "/Users/janzikes/anaconda2/envs/research/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 958, in _do_run
    target_list, options, run_metadata)
  File "/Users/janzikes/anaconda2/envs/research/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 978, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.FailedPreconditionError: Attempting to use uninitialized value mean_iou/total_confusion_matrix
	 [[Node: mean_iou/total_confusion_matrix/read = Identity[T=DT_INT64, _class=["loc:@mean_iou/total_confusion_matrix"], _device="/job:localhost/replica:0/task:0/cpu:0"](mean_iou/total_confusion_matrix)]]
....
....
File "/Users/janzikes/anaconda2/envs/research/lib/python2.7/site-packages/tensorflow/contrib/metrics/python/ops/metric_ops.py", line 1805, in streaming_mean_iou
    dtype=dtypes.int64)
  File "/Users/janzikes/anaconda2/envs/research/lib/python2.7/site-packages/tensorflow/contrib/metrics/python/ops/metric_ops.py", line 79, in _create_local
    collections=collections)
  File "/Users/janzikes/anaconda2/envs/research/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 211, in __init__
    dtype=dtype)
  File "/Users/janzikes/anaconda2/envs/research/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 323, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "/Users/janzikes/anaconda2/envs/research/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1106, in identity
    result = _op_def_lib.apply_op("Identity", input=input, name=name)
  File "/Users/janzikes/anaconda2/envs/research/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/Users/janzikes/anaconda2/envs/research/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2317, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/janzikes/anaconda2/envs/research/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1239, in __init__
    self._traceback = _extract_stack()
```

It seems to me that there might be some bug in the `tf.contrib.metrics.streaming_mean_iou`since all the variables are already initialised.

I am using it as follows:
```
accuracy_increment, iou_increment = self.session.run(
                [self.accuracy, self.mean_iou], feed_dict={
                self.X: eval_patches[
                        q * self.microbatch_size:
                        q * self.microbatch_size +
                        self.microbatch_size],
                self.Y: eval_labels[
                        q * self.microbatch_size:
                        q * self.microbatch_size +
                        self.microbatch_size],
                self.p_keep_conv: 1})
```

And the mean iou is computed in the object as:
```
self.mean_iou, _ = tf.contrib.metrics.streaming_mean_iou(
            self.predictions, tf.argmax(self.Y, dimension=3), num_classes=2)
```

I am using from source build tensorflow (branch r10.0) and it's happening to me on both CPU and GPU.

I am not 100% sure that I am using the `tf.contrib.metrics.streaming_mean_iou` correctly, but I have played with that a lot, but there is quite lack of the documentation, so I am currently stuck assuming that there is either some bug in the `tf.contrib.metrics.streaming_mean_iou` or not enough documentation for me to make it work.

I thank in advance anyone for any comments.

**Comment by martinwicke** [comment]
iou is using a local variable, have you called initialize_local_variables()?

**Comment by martinwicke** [comment]
(sorry our initialization functions are wrongly named -- we're working on it)

**Comment by ziky90** [comment]
Than you, this was the problem, I did not call `initialize_local_variables()`.

**Comment by holyseven** [comment]
@martinwicke @ziky90 Hi I am currently using streaming_mean_iou function too. I want to know if there is a way to get the confusion matrix for precision of each class, not only the average.

**Comment by martinwicke** [comment]
That would be a better question for StackOverflow.
