### ISSUE TITLE
Faild build windows

### ISSUE THREAD

**Issue by sonfire86** [tensorflow/tensorflow#43345]
System information

OS Platform and Distribution: Windows 10
TensorFlow installed from: source
TensorFlow version: 2.3
Python version: 3.8.3
Bazel version (if compiling from source): 3.1.0
CUDA/cuDNN version: 11.0.2_451.48/8.0.2.39
GPU model and memory: 1060 super
```
Repository rule cuda_configure defined at:
  G:/tensorflow/third_party/gpus/cuda_configure.bzl:1407:18: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
        File "G:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1377
                _create_local_cuda_repository(<1 more arguments>)
        File "G:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1221, in _create_local_cuda_repository
                to_list_of_strings(<1 more arguments>)
        File "G:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1222, in to_list_of_strings
                _cuda_include_path(<2 more arguments>)
        File "G:/tensorflow/third_party/gpus/cuda_configure.bzl", line 364, in _cuda_include_path
                inc_entries.append(<1 more arguments>)
        File "G:/tensorflow/third_party/gpus/cuda_configure.bzl", line 364, in inc_entries.append
                realpath(repository_ctx, <1 more arguments>)
        File "G:/tensorflow/third_party/remote_config/common.bzl", line 268, in realpath
                execute(repository_ctx, <1 more arguments>)
        File "G:/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
[FATAL 22:56:20.372 src/main/cpp/blaze.cc:1290] Unknown startup option: '-c'.
  For more info, run 'bazel help startup_options'.
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "G:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1377
                _create_local_cuda_repository(<1 more arguments>)
        File "G:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1221, in _create_local_cuda_repository
                to_list_of_strings(<1 more arguments>)
        File "G:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1222, in to_list_of_strings
                _cuda_include_path(<2 more arguments>)
        File "G:/tensorflow/third_party/gpus/cuda_configure.bzl", line 364, in _cuda_include_path
                inc_entries.append(<1 more arguments>)
        File "G:/tensorflow/third_party/gpus/cuda_configure.bzl", line 364, in inc_entries.append
                realpath(repository_ctx, <1 more arguments>)
        File "G:/tensorflow/third_party/remote_config/common.bzl", line 268, in realpath
                execute(repository_ctx, <1 more arguments>)
        File "G:/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
[FATAL 22:56:20.372 src/main/cpp/blaze.cc:1290] Unknown startup option: '-c'.
  For more info, run 'bazel help startup_options'.
WARNING: Target pattern parsing failed.
ERROR: no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "G:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1377
                _create_local_cuda_repository(<1 more arguments>)
        File "G:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1221, in _create_local_cuda_repository
                to_list_of_strings(<1 more arguments>)
        File "G:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1222, in to_list_of_strings
                _cuda_include_path(<2 more arguments>)
        File "G:/tensorflow/third_party/gpus/cuda_configure.bzl", line 364, in _cuda_include_path
                inc_entries.append(<1 more arguments>)
        File "G:/tensorflow/third_party/gpus/cuda_configure.bzl", line 364, in inc_entries.append
                realpath(repository_ctx, <1 more arguments>)
        File "G:/tensorflow/third_party/remote_config/common.bzl", line 268, in realpath
                execute(repository_ctx, <1 more arguments>)
        File "G:/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
[FATAL 22:56:20.372 src/main/cpp/blaze.cc:1290] Unknown startup option: '-c'.
  For more info, run 'bazel help startup_options'.
INFO: Elapsed time: 1.209s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package
```

**Comment by ravikyram** [comment]
@sonfire86 

Please, see tested build configurations from [here](https://www.tensorflow.org/install/source_windows#gpu).

Please, refer hardware and software requirements from [here](https://www.tensorflow.org/install/gpu#windows_setup).Thanks!

**Comment by sonfire86** [comment]
![image](https://user-images.githubusercontent.com/26105224/93659751-2902a680-fa62-11ea-8832-806aa0fba853.png)
Im set path `cuda`

**Comment by bhack** [comment]
Cuda 11 requires master branch.

**Comment by sonfire86** [comment]
I have tried build master branch and the same error

**Comment by ravikyram** [comment]
@sonfire86 

If you are using TF 2.3 please use cuda 10.1 as per builded test configurations from [here](https://www.tensorflow.org/install/source_windows#gpu).If you want to use CUDA 11 please try with master branch. Thanks!

**Comment by sonfire86** [comment]
@ravikyram I have tried build master branch and the same error

**Comment by sonfire86** [comment]
I have updated everything to the latest version
![Screenshot_74](https://user-images.githubusercontent.com/26105224/93785179-3a58d800-fc47-11ea-87e1-4e8af2c9731f.png)
![Screenshot_75](https://user-images.githubusercontent.com/26105224/93785180-3af16e80-fc47-11ea-8e38-354b8120c11f.png)

**Comment by bhack** [comment]
You need to install `coreutils` package

**Comment by sonfire86** [comment]
I put it, the error is the same

**Comment by bhack** [comment]
Is the same with realpath command not found?

**Comment by sonfire86** [comment]
Get  realpath error? Error cuda

**Comment by sonfire86** [comment]
yes, realpath command not found

**Comment by bhack** [comment]
You are working on an Anaconda env. We don't support Anaconda here.
Please use our official build documentation or ask for support to the Anaconda project if you still require anaconda.

**Comment by sonfire86** [comment]
Im not work Anaconda env. Im work system python

**Comment by bhack** [comment]
But you are using Anaconda python. Please follow our official build guide.

**Comment by sonfire86** [comment]
Ok, I'm try build for with official python

**Comment by sonfire86** [comment]
@bhack 
Build successful with official python.
With cuda 11 can I only build maset or 2.3 branch too?

**Comment by bhack** [comment]
Officially for Cuda 11 only master (and of course the next 2.4 release).

**Comment by sonfire86** [comment]
It might be worth adding that Anaconda is not supported for installation on Windows

**Comment by bhack** [comment]
> It might be worth adding that Anaconda is not supported for installation on Windows

There Is already in the installation Docs but It isn't so visibile. I've alteady asked to @lamberta how to better exposed this in another ticket.

**Comment by AndreyPlotkinOr** [comment]
> You need to install `coreutils` package

How do I install it?
I have the same error now. Using default python 3.6.
![image](https://user-images.githubusercontent.com/46108258/118174272-38b96b80-b3f4-11eb-8546-364639129b38.png)

**Comment by AndreyPlotkinOr** [comment]
Managed to solve it by installing coreutils in msys2:
pacman -S coreutils
