### ISSUE TITLE
distributed_dataset tensorflow.python.framework.errors_impl.UnavailableError: Socket closed

### ISSUE THREAD

**Issue by ksjae** [tensorflow/tensorflow#43362]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian Buster
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): bin
- TensorFlow version (use command below): 2.3.0
- Python version: 3.7.7
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: TPU v3-8

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out> in Colab,
tensorflow.python.framework.errors_impl.UnavailableError: Socket closed in GCE VM

**Describe the expected behavior**
Not having these errors(code ran just fine a few hours ago)

**Standalone code to reproduce the issue**
[COLAB](https://colab.research.google.com/drive/173UJ_icUBvl-a6-ujSZHoHHLL2qj9B-3?usp=sharing)

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
in Colab:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1325, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1264, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1310, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1259, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 976, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 948, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out
```

in VM:
```
Traceback (most recent call last):
  File "train_gpt2.py", line 77, in <module>
    train()
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "train_gpt2.py", line 64, in train
    model.fit(iter(dist_dataset), graph_mode)
  File "/home/ksjcom0705_gmail_com/gpt-2-tensorflow2.0/gpt2_model.py", line 343, in fit
    (inputs, targets) = next(train_dataset)
  File "/home/ksjcom0705_gmail_com/.local/lib/python3.7/site-packages/tensorflow/python/distribute/input_lib.py", line 649, in __next__
    return self.get_next()
  File "/home/ksjcom0705_gmail_com/.local/lib/python3.7/site-packages/tensorflow/python/distribute/input_lib.py", line 706, in get_next
    global_has_value, replicas = _get_next_as_optional(self, self._strategy)
  File "/home/ksjcom0705_gmail_com/.local/lib/python3.7/site-packages/tensorflow/python/distribute/input_lib.py", line 548, in _get_next_as_optional
    iterator._iterators[i].get_next_as_list(new_name))  # pylint: disable=protected-access
  File "/home/ksjcom0705_gmail_com/.local/lib/python3.7/site-packages/tensorflow/python/distribute/input_lib.py", line 1512, in get_next_as_list
    strict=True,
  File "/home/ksjcom0705_gmail_com/.local/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/ksjcom0705_gmail_com/.local/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
2020-09-19 08:05:53.047063: W tensorflow/core/distributed_runtime/eager/remote_tensor_handle_data.cc:76] Unable to destroy remote tensor handles. If you are running
 a tf.function, it usually indicates some op in the graph gets an error: Socket closed
Additional GRPC error information from remote target /job:worker/replica:0/task:0:
:{"created":"@1600502753.043380028","description":"Error received from peer ipv4:10.82.138.50:8470","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.
cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}
    return func(*args, **kwargs)
  File "/home/ksjcom0705_gmail_com/.local/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1207, in cond
    if pred:
  File "/home/ksjcom0705_gmail_com/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 984, in __bool__
    return bool(self._numpy())
  File "/home/ksjcom0705_gmail_com/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1031, in _numpy
    six.raise_from(core._status_to_exception(e.code, e.message), None)  # pylint: disable=protected-access   
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnavailableError: Socket closed
Additional GRPC error information from remote target /job:worker/replica:0/task:0:```...

**Comment by Saduf2019** [comment]
@ksjae 
Please refer to this issue and let us know: #42228 #41817

**Comment by bhack** [comment]
@ksjae This example is too much articulated. We need something that has a smaller surface to investigate reproduce it (copy, paste and run it). 
Can you share a very minimal example that we could run on colab without too much gcs or too much filesystem dependencies (e.g. dummy inputs). 
Thanks

**Comment by ksjae** [comment]
Done. Example is now minimal enough for testing (I hope).
Also, I found out that on GPUs, the code gives 'Segmentation Fault' on the very same line.

**Comment by Saduf2019** [comment]
@ksjae 
I ran the code shared and face a different error please find the [gist here](https://colab.research.google.com/gist/Saduf2019/42d69bf831c8d69d2e3ae01d9b47e4ee/untitled.ipynb).
Please share a colab gist with the error reported in the gist.

**Comment by bhack** [comment]
@Saduf2019 this Is a specific nightly issue like https://github.com/tensorflow/tensorflow/issues/43254#issuecomment-693461228

**Comment by nikitamaia** [comment]
I ran the notebook in the original post with tf 2.3 and was able to reproduce the error. 
When I set `tpu = False` on a GPU runtime the session crashes. Do you see that as well?

You can see in this similar issue here  #36136 that this error message is sometimes caused from `trying to cache a large dataset into memory` so I'm wondering if the root cause here is an OOM issue.

**Comment by ksjae** [comment]
I've been consistently able to reproduce this(haven't ran this for a few days though, just used another training code).

Slightly doubtful about OOMs, since I tried setting batch size from 8 and it still crashed.

**Comment by CalebEverett** [comment]
I experienced this issue today with tf 2.3.

```
UnavailableError: Socket closed
Additional GRPC error information from remote target /job:worker/replica:0/task:0:
:{"created":"@1607389193.224325108","description":"Error received from peer ipv4:10.77.25.2:8470","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}
```

There was no error with either CPU or GPU.

Here is a colab that reproduces the error:

https://colab.research.google.com/drive/1C09OUXP-7Es4KIthVA6daRcGq_bJKGe8?usp=sharing

**Comment by hongjunChoi** [comment]
@CalebEverett : Above error seems to be from user code. 

Normally "UnavailableError: Socket closed" is an aftermath of an underlying error

` TypeError: tensordot() got an unexpected keyword argument 'dtype' ` 

Could you try updating `call` function to use correct semantics for tensordot()?

**Comment by CalebEverett** [comment]
@hongjunChoi Hi, thanks for looking into this. I've taken out that dtype argument and it is still producing the same error. I must have put that in as I was trying to get it work.

The colab is updated. https://colab.research.google.com/drive/1C09OUXP-7Es4KIthVA6daRcGq_bJKGe8?usp=sharing

**Comment by sushreebarsa** [comment]
Was able to replicate the issue with TF v2.5,please find the gist [here ](https://colab.research.google.com/gist/sushreebarsa/7c419e9f182d90587aed40f755b0df9c/untitled266.ipynb)..Thanks !

**Comment by sushreebarsa** [comment]
@ksjae Could you let us know if you tried updating the call function to use correct semantics with latest TF version and still faces this issue. Please upgrade to the latest version as older versions are not actively supported.
Thank you!
