### ISSUE TITLE
Commit that breaks Bazel 0.3.0 support

### ISSUE THREAD

**Issue by gustavla** [tensorflow/tensorflow#4343]
If I try to configure the lastest master branch (db45268db0203fcdb0e48e3e558b01244424c0a6) using Bazel 0.3.0, I get:

```
ERROR: [...]/tensorflow/tensorflow/tensorflow.bzl:568:26: Traceback (most recent call last):
        File "[...]/tensorflow/tensorflow/tensorflow.bzl", line 562
                rule(attrs = {"srcs": attr.label_list..."), <3 more arguments>)}, <2 more arguments>)
        File "[...]/tensorflow/tensorflow/tensorflow.bzl", line 568, in rule
                attr.label_list(cfg = "data", allow_files = True)
expected ConfigurationTransition or NoneType for 'cfg' while calling label_list but got string instead: data.
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension file 'tensorflow/tensorflow.bzl' has errors.
```

Using 0.3.1 avoids this and reverting the offending commit 7bcdcbbf60fc08346fd8016270a0563f4b51362b also fixes it.

### Environment info

Setup: CentOS, Bazel 0.3.0, CUDA 7.5, CuDNN 5.1, Tensorflow master (db45268db0203fcdb0e48e3e558b01244424c0a6)

I run `configure` and set it up for GPU support. I see the error above if I use bazel 0.3.0.

### Fix

Upgrade to 0.3.1, obviously. However, since 0.3.0 is still officially supported, I thought this deserves to be an issue.

Another fix is to revert the commit 7bcdcbbf60fc08346fd8016270a0563f4b51362b. Note, I didn't have to revert to its parent; undoing that commit alone is enough:
```
git show -R 7bcdcbbf | git apply
```

**Comment by gustavla** [comment]
Sorry, this is a duplicate of #4319. I'm closing this.
