### ISSUE TITLE
top_k crashes for certain large structures

### ISSUE THREAD

**Issue by amitport** [tensorflow/tensorflow#43447]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
v2.2.0-rc4-8-g2b96f3662b 2.2.0
- Python version:
3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
10.1 update 2
- GPU model and memory:
GTX 960m

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
The following operation crashes (possible because of gpu l2 usage (?)
```python
import tensorflow as tf
x = tf.random.stateless_normal(shape=(1_000_000, 2), dtype=tf.float32, seed=(4,2))
print(tf.math.top_k(x, k=1)[0][:2])
```

Crashes on my machine. Interestingly using a shape of (2, 1_000_000) works fine

**Describe the expected behavior**
it shouldn't crash, and if there is a memory limitation it should be specified in the crash. this problem user that indirectly use top_k and not throwing the correct exception makes it very hard to debug (see https://github.com/tensorflow/probability/issues/1086)

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
2020-09-22 06:51:17.737213: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-09-22 06:51:19.945793: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-09-22 06:51:20.385293: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 960M computeCapability: 5.0
coreClock: 1.176GHz coreCount: 5 deviceMemorySize: 4.00GiB deviceMemoryBandwidth: 74.65GiB/s
2020-09-22 06:51:20.385745: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-09-22 06:51:20.390534: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-09-22 06:51:20.395306: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-09-22 06:51:20.396930: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-09-22 06:51:20.402414: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-09-22 06:51:20.405454: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-09-22 06:51:20.415167: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-09-22 06:51:20.416576: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-09-22 06:51:20.417067: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-09-22 06:51:20.427041: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1a8f253a180 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-22 06:51:20.427523: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-22 06:51:20.429145: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 960M computeCapability: 5.0
coreClock: 1.176GHz coreCount: 5 deviceMemorySize: 4.00GiB deviceMemoryBandwidth: 74.65GiB/s
2020-09-22 06:51:20.429756: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-09-22 06:51:20.429991: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-09-22 06:51:20.430219: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-09-22 06:51:20.430449: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-09-22 06:51:20.430672: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-09-22 06:51:20.430902: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-09-22 06:51:20.431136: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-09-22 06:51:20.432293: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-09-22 06:51:21.959567: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-22 06:51:21.959917: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-09-22 06:51:21.960127: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-09-22 06:51:21.961302: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3031 MB memory) -> physical GPU (device: 0, name: GeForce GTX 960M, pci bus id: 0000:01:00.0, compute capability: 5.0)
2020-09-22 06:51:21.965674: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1a89849b300 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-09-22 06:51:21.966109: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 960M, Compute Capability 5.0
2020-09-22 06:51:25.072632: E tensorflow/stream_executor/cuda/cuda_driver.cc:939] could not synchronize on CUDA context: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure :: 0x00007FFBB77F8E85	tensorflow::CurrentStackTrace
0x00007FFBB752A4BE	tensorflow::DeviceProperties::l2_cache_size
0x00007FFBB7530BEE	stream_executor::StreamExecutor::EnablePeerAccessTo
0x00007FFBA431BF38	tensorflow::StepStats::internal_default_instance
0x00007FFBA432D064	google::protobuf::RepeatedPtrField<tensorflow::InterconnectLink>::Add
0x00007FFBA4067712	std::vector<tensorflow::DtypeAndPartialTensorShape,std::allocator<tensorflow::DtypeAndPartialTensorShape> >::operator=
0x00007FFB9EE4A4D1	tensorflow::MemoryLogRawDeallocation::deferred
0x00007FFB9EE54A01	TFE_TensorHandleResolve
0x00007FFB9EBBD6A3	TFE_Py_TensorShapeSlice
0x00007FFB9EBBADDA	std::vector<tensorflow::monitoring::Point::Label,std::allocator<tensorflow::monitoring::Point::Label> >::reserve
0x00007FFC7010BDEF	PyMethodDef_RawFastCallKeywords
0x00007FFC7010B6E7	PyArg_UnpackStack
0x00007FFC70118484	PyEval_EvalFrameDefault
0x00007FFC7010B841	PyArg_UnpackStack
0x00007FFC70118484	PyEval_EvalFrameDefault
0x00007FFC7010C0FC	PyEval_EvalCodeWithName
0x00007FFC7010B95C	PyArg_UnpackStack
0x00007FFC70118A6E	PyEval_EvalFrameDefault
0x00007FFC7010B294	PyFunction_FastCallDict
0x00007FFC700F22D4	PyObject_FastCall_Prepend
0x00007FFC700F2225	PySequence_GetItem
0x00007FFC700FE78D	PyObject_Str
0x00007FFC7013807E	PyFile_WriteObject
0x00007FFC70137F5D	PySys_EndInit
0x00007FFC7010BE06	PyMethodDef_RawFastCallKeywords
0x00007FFC7010B8A3	PyArg_UnpackStack
0x00007FFC70118A6E	PyEval_EvalFrameDefault
0x00007FFC7010C0FC	PyEval_EvalCodeWithName
0x00007FFC70120197	PyEval_EvalCodeEx
0x00007FFC701200F5	PyEval_EvalCode
0x00007FFC7012009F	PyArena_Free
0x00007FFC70293E5D	PyRun_FileExFlags
0x00007FFC702945F9	PyRun_SimpleFileExFlags
0x00007FFC70293D3B	PyRun_AnyFileExFlags
0x00007FFC701E1054	Py_UnixMain
0x00007FFC701E10FB	Py_UnixMain
0x00007FFC7017936E	PyErr_NoMemory
0x00007FFC701309DB	Py_Main
0x00007FFC701309B6	Py_Main
0x00007FF7E889126D	(unknown)
0x00007FFCBAAA6FD4	BaseThreadInitThunk
0x00007FFCBB0DCEC1	RtlUserThreadStart

Traceback (most recent call last):
  File "<project>/bug4.py", line 6, in <module>
    print(tf.math.top_k(x, k=1)[0][:2])
  File "<env>\lib\site-packages\tensorflow\python\framework\ops.py", line 904, in __str__
    return "tf.Tensor(%s, shape=%s, dtype=%s)" % (numpy_text(self), self.shape,
  File "<env>\lib\site-packages\tensorflow\python\framework\ops.py", line 264, in numpy_text
    text = repr(tensor._numpy()) if is_repr else str(tensor._numpy())
  File "<env>\lib\site-packages\tensorflow\python\framework\ops.py", line 929, in _numpy
    six.raise_from(core._status_to_exception(e.code, e.message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InternalError: GPU sync failed

Process finished with exit code 1
```

**Comment by ravikyram** [comment]
@amitport 

I have tried in colab with TF version 2.3 and nightly version(2.4.0-dev20200921) and i am not seeing any issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/0000dda34bef8368b310e3690b40dce2/untitled382.ipynb).Please,verify once and close the issue. Thanks!

**Comment by amitport** [comment]
@ravikyram response: this is hardware related. Seem to have something to do with gpu l2 cache size from the log
(still very much an issue)

**Comment by jvishnuvardhan** [comment]
@amitport Is this still an issue for you. I ran it with `TF2.4.1` and don't see any issue. Please let us know whether the issue persists with newer TF versions. Thanks!

**Comment by amitport** [comment]
I have other problems with 2.4 and 2.5 on my GTX 960M machine, I moved on the use the cloud more for now since this. Closing this, since I can't determine if it is solved or not. Thanks
