### ISSUE TITLE
Duplicate node name in graph: 'ones'

### ISSUE THREAD

**Issue by Israel-Lopez-Herreros** [tensorflow/tensorflow#43534]
Hi,

I have the following error testing the yolov3 example: https://github.com/pythonlessons/TensorFlow-2.x-YOLOv3

2020-09-24 11:28:23.492471: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "C:\Users\c81441\AppData\Local\Continuum\Anaconda3_64_2020_02\envs\tensor_flow_env_test\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1610, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Duplicate node name in graph: 'ones'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3\helpers\pydev\pydevd.py", line 1683, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3\helpers\pydev\pydevd.py", line 1677, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3\helpers\pydev\pydevd.py", line 1087, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/c81441/Documents/75-GIT-PYTHON-PHOTOGRAMMETRY/deep_learning/20-TensorFlow-2.x-YOLOv3-master/detection_demo.py", line 22, in <module>
    yolo = Load_Yolo_model()
  File "C:/Users/c81441/Documents/75-GIT-PYTHON-PHOTOGRAMMETRY/deep_learning/20-TensorFlow-2.x-YOLOv3-master\yolov3\utils.py", line 84, in Load_Yolo_model
    yolo = Create_Yolo(input_size=YOLO_INPUT_SIZE, CLASSES=YOLO_COCO_CLASSES)
  File "C:/Users/c81441/Documents/75-GIT-PYTHON-PHOTOGRAMMETRY/deep_learning/20-TensorFlow-2.x-YOLOv3-master\yolov3\yolov4.py", line 398, in Create_Yolo
    pred_tensor = decode(conv_tensor, NUM_CLASS, i)
  File "C:/Users/c81441/Documents/75-GIT-PYTHON-PHOTOGRAMMETRY/deep_learning/20-TensorFlow-2.x-YOLOv3-master\yolov3\yolov4.py", line 427, in decode
    xy_grid = tf.meshgrid(tf.range(output_size), tf.range(output_size))
  File "C:\Users\c81441\AppData\Local\Continuum\Anaconda3_64_2020_02\envs\tensor_flow_env_test\lib\site-packages\tensorflow_core\python\ops\array_ops.py", line 2954, in meshgrid
    mult_fact = ones(shapes, output_dtype)
  File "C:\Users\c81441\AppData\Local\Continuum\Anaconda3_64_2020_02\envs\tensor_flow_env_test\lib\site-packages\tensorflow_core\python\ops\array_ops.py", line 2583, in ones
    output = fill(shape, constant(one, dtype=dtype), name=name)
  File "C:\Users\c81441\AppData\Local\Continuum\Anaconda3_64_2020_02\envs\tensor_flow_env_test\lib\site-packages\tensorflow_core\python\ops\array_ops.py", line 171, in fill
    result = gen_array_ops.fill(dims, value, name=name)
  File "C:\Users\c81441\AppData\Local\Continuum\Anaconda3_64_2020_02\envs\tensor_flow_env_test\lib\site-packages\tensorflow_core\python\ops\gen_array_ops.py", line 3601, in fill
    "Fill", dims=dims, value=value, name=name)
  File "C:\Users\c81441\AppData\Local\Continuum\Anaconda3_64_2020_02\envs\tensor_flow_env_test\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 793, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\c81441\AppData\Local\Continuum\Anaconda3_64_2020_02\envs\tensor_flow_env_test\lib\site-packages\tensorflow_core\python\framework\func_graph.py", line 548, in create_op
    compute_device)
  File "C:\Users\c81441\AppData\Local\Continuum\Anaconda3_64_2020_02\envs\tensor_flow_env_test\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3429, in _create_op_internal
    op_def=op_def)
  File "C:\Users\c81441\AppData\Local\Continuum\Anaconda3_64_2020_02\envs\tensor_flow_env_test\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1773, in __init__
    control_input_ops)
  File "C:\Users\c81441\AppData\Local\Continuum\Anaconda3_64_2020_02\envs\tensor_flow_env_test\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1613, in _create_c_op
    raise ValueError(str(e))
ValueError: Duplicate node name in graph: 'ones'

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 7, 64bits
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0. I have tested with different tf/pythons versions and I get the same error
- Python version: 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Comment by bhack** [comment]
Please open the ticket in the third_party repository https://github.com/pythonlessons/TensorFlow-2.x-YOLOv3 and close this one. Ten reopen this if they debug that is a Tensorflow bug.

**Comment by Israel-Lopez-Herreros** [comment]
The error is inside of tf module and I have seen some similar issues in tf

**Comment by bhack** [comment]
Have you seen?
https://github.com/pythonlessons/TensorFlow-2.x-YOLOv3/issues/37

**Comment by bhack** [comment]
Can you close this?

**Comment by Israel-Lopez-Herreros** [comment]
I tested with tf 2.3 and I have the same error. I think that it could be a tf bug

**Comment by bhack** [comment]
We don't support Anaconda setup directly  here.
As the same ticket on the model repository was close as solved with TF 2.3 Can you try with the official installation https://www.tensorflow.org/install/pip
