### ISSUE TITLE
confusion_matrix should use cast rather than convert to tensor for size

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#4353]
This does not work:

```
>>> cm = tf.contrib.metrics.confusion_matrix(
...     [1,2,3], [4,5,5], num_classes=tf.constant(3, dtype=tf.int32))
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/metrics/python/ops/confusion_matrix_ops.py", line 84, in confusion_matrix
    indices=indices, values=values, shape=shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 981, in __init__
    shape = convert_to_tensor(shape, name="shape", dtype=dtypes.int64)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 628, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 571, in _TensorTensorConversionFunction
    % (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype int64 for Tensor with dtype int32: 'Tensor("confusion_matrix/pack:0", shape=(2,), dtype=int32)'
```

where as this does:

```
tf.contrib.metrics.confusion_matrix(
    [1,2,3], [4,5,5], num_classes=tf.constant(3, dtype=tf.int64))
```

This seems related: https://github.com/tensorflow/tensorflow/pull/2187

Machine:

```
 bazel version
INFO: Reading 'startup' options from /root/.bazelrc: --batch
Extracting Bazel installation...
Build label: 0.3.0
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jun 10 11:38:23 2016 (1465558703)
Build timestamp: 1465558703
Build timestamp as int: 1465558703
```

```
 git rev-parse HEAD
58b37cf745c6c30d44878ddf5987c4283ed12c3c
```

```
ls -l /usr/lib/x86_64-linux-gnu/libcud*
lrwxrwxrwx 1 root root       29 Aug 12 05:11 /usr/lib/x86_64-linux-gnu/libcudnn.so -> /etc/alternatives/libcudnn_so
lrwxrwxrwx 1 root root       17 Jun 10 13:07 /usr/lib/x86_64-linux-gnu/libcudnn.so.5 -> libcudnn.so.5.1.3
-rw-r--r-- 1 root root 60696704 Jun 10 13:07 /usr/lib/x86_64-linux-gnu/libcudnn.so.5.1.3
lrwxrwxrwx 1 root root       32 Aug 12 05:11 /usr/lib/x86_64-linux-gnu/libcudnn_static.a -> /etc/alternatives/libcudnn_stlib
-rw-r--r-- 1 root root 59715990 Jun 10 13:07 /usr/lib/x86_64-linux-gnu/libcudnn_static_v5.a
```

```
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so.7.5 locally
```

**Comment by andydavis1** [comment]
Looks like a fix is on its way...

**Comment by drpngx** [comment]
Closing, assuming that the fix was committed. Feel free to open again if the problem persists in more recent versions.
