### ISSUE TITLE
tf.numpy_function() does not support symbolic Tensors

### ISSUE THREAD

**Issue by loic-ehrhardt** [tensorflow/tensorflow#43542]
**System information**
- I have written custom code (see below)
- Red Hat Enterprise Linux Server release 7.7 (Maipo)
- TensorFlow installed from: binary (pip)
- TensorFlow version: v2.3.0-rc2-23-gb36436b087 2.3.0
- Python version: 3.6.9

**Describe the current behavior**
Calling `tf.numpy_function()` with symbolic Tensor crashes (see below). This prevents `tf.numpy_function()` from being directly used when building a Keras Model with the Functional API.

**Describe the expected behavior**
Calling `tf.numpy_function()` with symbolic Tensor should return the symbolic Tensors which are the result of the operation.

**Standalone code to reproduce the issue**
```python
>>> import tensorflow as tf, numpy as np
>>> (tf.__version__, np.__version__)
('2.3.0', '1.18.5')

# Create a symbolic Tensor.
>>> x = tf.keras.layers.Input(shape=(2,))
>>> x
<tf.Tensor 'input_2:0' shape=(None, 2) dtype=float32>

# Calling it on tf.sin() gives a symbolic Tensor as output.
>>> tf.sin(x)
<tf.Tensor 'Sin:0' shape=(None, 2) dtype=float32>

# Calling it on tf.numpy_function() with np.sin() fails:
>>> tf.numpy_function(np.sin, [x], [tf.float32])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/loic/venv/tf/lib64/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/loic/venv/tf/lib64/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 632, in numpy_function
    return py_func_common(func, inp, Tout, stateful=True, name=name)
  File "/home/loic/venv/tf/lib64/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 519, in py_func_common
    result = func(*[np.array(x) for x in inp])
  File "/home/loic/venv/tf/lib64/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 519, in <listcomp>
    result = func(*[np.array(x) for x in inp])
  File "/home/loic/venv/tf/lib64/python3.6/site-packages/tensorflow/python/framework/ops.py", line 848, in __array__
    " a NumPy call, which is not supported".format(self.name))
NotImplementedError: Cannot convert a symbolic Tensor (input_2:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported
```

**Other info / logs**
`tf.numpy_function()` works as expected under other circumstances.
```python
# With an eager Tensor.
>>> x = tf.constant([0., 1.])
>>> x
<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 1.], dtype=float32)>
>>> tf.sin(x)
<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.        , 0.84147096], dtype=float32)>
>>> tf.numpy_function(np.sin, [x], [tf.float32])
<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.        , 0.84147096], dtype=float32)>
```
```python
# When eager execution is disabled.
>>> import tensorflow as tf, numpy as np
>>> tf.python.framework.ops.disable_eager_execution()
>>> x = tf.keras.layers.Input(shape=(2,))
>>> tf.numpy_function(np.sin, [x], [tf.float32])
[<tf.Tensor 'PyFunc:0' shape=<unknown> dtype=float32>]
```
```python
# When wrapping tf.numpy_function() inside a Keras Lambda Layer.
>>> import tensorflow as tf, numpy as np
>>> x = tf.keras.layers.Input(shape=(2,))
>>> tf.keras.layers.Lambda(lambda t: tf.numpy_function(np.sin, [t], [tf.float32]))(x)
[<tf.Tensor 'lambda/PyFunc:0' shape=<unknown> dtype=float32>]
```

**Comment by meSajied** [comment]
```
tf.py_function` and `tf.numpy_function` are very similar, except that
  `tf.numpy_function` takes numpy arrays, and not `tf.Tensor`s. If you want the
  function to contain `tf.Tensors`, and have any TensorFlow operations executed
  in the function be differentiable, please use `tf.py_function`
```

**Comment by Saduf2019** [comment]
@loic-ehrhardt 
Please refer to this issue and let us know: #43154

**Comment by loic-ehrhardt** [comment]
Thanks @meSajied and @Saduf2019 for your replies.

@meSajied
```
tf.py_function` and `tf.numpy_function` are very similar,
except that `tf.numpy_function` takes numpy arrays, and not `tf.Tensor`s.
If you want the function to contain `tf.Tensors`, [...] please use `tf.py_function`.
```
I do not want the function to contain `tf.Tensors`. I would like to use `np.sin()`, *not* `tf.sin()` (obviously, the numpy function I actually want to use is more complex but I use `np.sin()` here as minimal example to show the bug).
Moreover, `tf.py_function()` also fails with `tf.keras.layers.Input()`:
```python
>>> import tensorflow as tf
>>> x = tf.keras.layers.Input(shape=(2,))
>>> tf.py_function(tf.sin, [x], [tf.float32])
2020-09-25 03:10:32.888622: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-09-25 03:10:32.888671: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-09-25 03:10:32.888709: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (mill.circularcapital.com): /proc/driver/nvidia/version does not exist
2020-09-25 03:10:32.901200: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2700105000 Hz
2020-09-25 03:10:32.903706: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4bfbb20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-25 03:10:32.903734: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/loic/venv/tf/lib64/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/loic/venv/tf/lib64/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 457, in eager_py_func
    func=func, inp=inp, Tout=Tout, eager=True, name=name)
  File "/home/loic/venv/tf/lib64/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 342, in _internal_py_func
    name=name)
  File "/home/loic/venv/tf/lib64/python3.6/site-packages/tensorflow/python/ops/gen_script_ops.py", line 55, in eager_py_func
    ctx=_ctx)
  File "/home/loic/venv/tf/lib64/python3.6/site-packages/tensorflow/python/ops/gen_script_ops.py", line 96, in eager_py_func_eager_fallback
    _attr_Tin, input = _execute.convert_to_mixed_eager_tensors(input, ctx)
  File "/home/loic/venv/tf/lib64/python3.6/site-packages/tensorflow/python/eager/execute.py", line 291, in convert_to_mixed_eager_tensors
    types = [t._datatype_enum() for t in v]  # pylint: disable=protected-access
  File "/home/loic/venv/tf/lib64/python3.6/site-packages/tensorflow/python/eager/execute.py", line 283, in <listcomp>
    types = [t._datatype_enum() for t in v]  # pylint: disable=protected-access
AttributeError: 'Tensor' object has no attribute '_datatype_enum'
```

@Saduf2019
It looks like #43154 refers to a warning about AutoGraph not being able to transform some function and then falling back to running it as is. This seems unrelated to my issue. In my case, I have a plain crash. Moreover, I see in the release notes (https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md#release-220) that since tensorflow 2.2.0, `AutoGraph no longer converts functions passed to tf.py_function, tf.py_func and tf.numpy_function` (by the way I tried with TF 2.1 and it also crashes).

**Comment by loic-ehrhardt** [comment]
Hi @Saduf2019. Do you have further insights into this or do you think this should be escalated? It looks like #43154  is closed.

**Comment by jvishnuvardhan** [comment]
@loic-ehrhardt I am able to reproduce the error with `TF2.3`. However, there is no error when `tf-nightly` was used. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/c94aec48f9fbd5df7d781a5423206efe/untitled54.ipynb). Thanks!

**Comment by loic-ehrhardt** [comment]
@jvishnuvardhan Thanks for your reply. This seems indeed fixed in the new TF version. I think we can close this ticket then. My goal was to actually use `tf.numpy_function()` with `tf.custom_gradient()` to compute both the output and the gradient with numpy. This is still not working with tf_nightly. I opened the new issue #43916, would you mind looking into this too?
Bests, Loïc.
