### ISSUE TITLE
[comp:lite] App crashes while using GPU Delegate with Float_MobileNet or Float_EffieintNet

### ISSUE THREAD

**Issue by xintin** [tensorflow/tensorflow#43551]
Hi,
I am trying out the following example: [TFLite on Android (with Android (Studio)](https://www.tensorflow.org/lite/performance/gpu)

I could see it working for CPU, but while using GPU Delegate with Float_MobileNet or Float_EffieintNet, the app is crashing. Added
```
dependencies {
    ...
    implementation 'org.tensorflow:tensorflow-lite:2.3.0'
    implementation 'org.tensorflow:tensorflow-lite-gpu:2.3.0'
}
```

in order to use GPU delegate. And yes, the GPU delegate does not support Quantized models yet, so I can not even test that.

As per @jdduke's suggestion, I tried
```
implementation('org.tensorflow:tensorflow-lite:0.0.0-nightly') { changing = true }
implementation('org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly') { changing = true }
```
but could not succeed.

**Hardware Details**
Pixel 3a XL 6.0 1080x2160 xhdpi
Q Android 10.0  x86

If someone can help me out here, it would be a great help. 

Reference: [TFLite Google Group](https://groups.google.com/a/tensorflow.org/g/tflite/c/h2wSUviSywo/m/BSWIETLZBgAJ)

Thanks

**Comment by jdduke** [comment]
Can you attach the logcat that includes the crash? https://developer.android.com/studio/debug/am-logcat#running. Tentatively to @lintian06 to try to repro.

**Comment by xintin** [comment]
[Logcat_Failed_To_Run_Inferenec_On_GPU.txt](https://github.com/tensorflow/tensorflow/files/5284623/Logcat_Failed_To_Run_Inferenec_On_GPU.txt)

Kindly let me know if you want me to manually log any information. 

Thanks.

**Comment by jdduke** [comment]
```
    java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Following operations are not supported by GPU delegate:
    SQUEEZE: Operation is not supported.
    29 operations will run on the GPU, and the remaining 2 operations will run on the CPU.
    Can not open OpenCL library on this device - dlopen failed: library "libOpenCL.so" not found
    Falling back to OpenGL
    TfLiteGpuDelegate Init: No EGL error, but eglChooseConfig failed.
    TfLiteGpuDelegate Prepare: delegate is not initialized
    Node number 31 (TfLiteGpuDelegateV2) failed to prepa
        at org.tensorflow.lite.NativeInterpreterWrapper.applyDelegate(Native Method)
```

Just be clear, in your hardware details you state:
```
Pixel 3a XL 6.0 1080x2160 xhdpi
Q Android 10.0 x86
```

What do you mean by x86 here? Are you running your app in the emulator or on the (ARM) Pixel 3a?

**Comment by xintin** [comment]
I am using Emulator. 
x86 is the ABI (System Image), API Level 29.

**Comment by jdduke** [comment]
Generally speaking, the GPU delegate does not work on emulators, and requires GLES 3.1+. We can try to make the error message a bit more specific on this.

**Comment by xintin** [comment]
Oh, I see. Thanks, that'd be helpful. 

Can you redirect me to any end-to-end official tutorial for TFLite with OpenGL ES?

**Comment by lintian06** [comment]
Hi Gaurav,

I just want to confirm with you if you are using [tensorflow/examples](https://github.com/tensorflow/examples)'s demo. That one contains a class [ClassifierFloatEfficientNet.java](https://github.com/tensorflow/examples/blob/master/lite/examples/image_classification/android/lib_support/src/main/java/org/tensorflow/lite/examples/classification/tflite/ClassifierFloatEfficientNet.java) to handle EfficientNet. We use [EfficientNet-lite](https://github.com/tensorflow/examples/blob/0ef3d93e2af95d325c70ef3bcbbd6844d0631e07/lite/examples/image_classification/android/models/download.gradle#L4) optimized by making ops GPU-compatible, and we have [EfficientNet-lite in TFHub](https://tfhub.dev/tensorflow/efficientnet/lite0/classification/2) (efficientnet-lite0 to lite4) to make it reusable.

```
git clone https://github.com/tensorflow/examples
cd examples/lite/examples/image_classification/android

# Use Android Studio to build
# Or use gradle with ANDROID_HOME set correctly to your SDK.
./gradlew build
```

The code inside [TFLite on Android (with Android (Studio)](https://www.tensorflow.org/lite/performance/gpu) is OK for EfficientNet CPU, however it didn't contain the treatment that is mentioned above.

**Comment by xintin** [comment]
Hi Tian,

Yes, I was using the same demo. Now, as per your suggestion, I have updated the `ClassifierFloatEfficientNet.java` located at `..\android\examples\lite\examples\image_classification\android\lib_support\src\main\java\org\tensorflow\lite\examples\classification\tflite` from [here](https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/android/lib_support/src/main/java/org/tensorflow/lite/examples/classification/tflite). Also, this is my newest [download.gradle](https://github.com/tensorflow/examples/blob/0ef3d93e2af95d325c70ef3bcbbd6844d0631e07/lite/examples/image_classification/android/models/download.gradle#L4). Still it is crashing for me. I understand there is no OpenCL but OpenGL should not fail, right? Below is the trace: 



```
2020-09-23 15:53:19.618 8675-8714/? I/tflite: Created 0 GPU delegate kernels.
2020-09-23 15:53:19.619 8675-8714/? E/AndroidRuntime: FATAL EXCEPTION: inference
    Process: org.tensorflow.lite.examples.classification, PID: 8675
    java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Following operations are not supported by GPU delegate:
    SQUEEZE: Operation is not supported.
    29 operations will run on the GPU, and the remaining 2 operations will run on the CPU.
    Can not open OpenCL library on this device - dlopen failed: library "libOpenCL.so" not found
    Falling back to OpenGL
    TfLiteGpuDelegate Init: No EGL error, but eglChooseConfig failed.
    TfLiteGpuDelegate Prepare: delegate is not initialized
    Node number 31 (TfLiteGpuDelegateV2) failed to prepa
        at org.tensorflow.lite.NativeInterpreterWrapper.applyDelegate(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.applyDelegates(NativeInterpreterWrapper.java:351)
        at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:82)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:63)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:266)
        at org.tensorflow.lite.examples.classification.tflite.Classifier.<init>(Classifier.java:214)
        at org.tensorflow.lite.examples.classification.tflite.ClassifierFloatMobileNet.<init>(ClassifierFloatMobileNet.java:47)
        at org.tensorflow.lite.examples.classification.tflite.Classifier.create(Classifier.java:118)
        at org.tensorflow.lite.examples.classification.ClassifierActivity.recreateClassifier(ClassifierActivity.java:147)
        at org.tensorflow.lite.examples.classification.ClassifierActivity.lambda$onInferenceConfigurationChanged$0$ClassifierActivity(ClassifierActivity.java:126)
        at org.tensorflow.lite.examples.classification.-$$Lambda$ClassifierActivity$83lGy2TUjuj0M5n4BhMB9qlLgSY.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2020-09-23 15:53:19.627 1995-6756/system_process W/ActivityTaskManager:   Force finishing activity org.tensorflow.lite.examples.classification/.ClassifierActivity
```

Appreciate your help.

**Comment by lintian06** [comment]
> I am using Emulator.
> x86 is the ABI (System Image), API Level 29.

Do you still use Emulator or a real phone?

FYI, just as Jared did, I tried on Pixel 3 with Android 10 again, which works.

**Comment by xintin** [comment]
Thanks, Tian. It worked on a real phone.

**Comment by walterdumba** [comment]
Hi everybody,

Apologies if this is not the appropriate place for this, but I'm trying to run [this](https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/android) example
 on my device and I'm having the same symptoms described on this ticket. In my case i cannot run both Float classifiers at all (neither in CPU nor GPU mode)
Here's my configuration:
OnePlus One
Android 10

And here's what i got from logs:

2021-01-31 13:31:51.479 27048-27099/org.tensorflow.lite.examples.classification I/Manager: DeviceManager::DeviceManager
2021-01-31 13:31:51.480 27048-27099/org.tensorflow.lite.examples.classification I/Manager: findAvailableDevices
2021-01-31 13:31:51.493 27048-27099/org.tensorflow.lite.examples.classification D/ClassifierWithSupport: Created a Tensorflow Lite Image Classifier.
2021-01-31 13:31:55.660 27048-27086/org.tensorflow.lite.examples.classification W/Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
2021-01-31 13:31:59.282 27048-27048/org.tensorflow.lite.examples.classification D/tensorflow: CameraActivity: Updating  model: FLOAT_EFFICIENTNET
2021-01-31 13:31:59.300 27048-27099/org.tensorflow.lite.examples.classification D/tensorflow: ClassifierActivity: Closing classifier.
2021-01-31 13:31:59.311 27048-27099/org.tensorflow.lite.examples.classification D/tensorflow: ClassifierActivity: Creating classifier (model=FLOAT_EFFICIENTNET, device=NNAPI, numThreads=1)
2021-01-31 13:31:59.327 27048-27099/org.tensorflow.lite.examples.classification D/ClassifierWithSupport: Created a Tensorflow Lite Image Classifier.
2021-01-31 13:32:14.213 27048-27086/org.tensorflow.lite.examples.classification W/Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
2021-01-31 13:32:19.638 27048-27048/org.tensorflow.lite.examples.classification D/tensorflow: CameraActivity: Updating  device: GPU
2021-01-31 13:32:19.743 27048-27099/org.tensorflow.lite.examples.classification D/tensorflow: ClassifierActivity: Closing classifier.
2021-01-31 13:32:19.747 27048-27099/org.tensorflow.lite.examples.classification D/tensorflow: ClassifierActivity: Creating classifier (model=FLOAT_EFFICIENTNET, device=GPU, numThreads=1)
2021-01-31 13:32:19.756 27048-27099/org.tensorflow.lite.examples.classification I/tflite: Created TensorFlow Lite delegate for GPU.
2021-01-31 13:32:19.766 27048-27099/org.tensorflow.lite.examples.classification A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 27099 (inference), pid 27048 (.classification)

Thank you in advance
