### ISSUE TITLE
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by Strange1-7** [tensorflow/tensorflow#43579]
Getting this Error, please help me to resolve this issue.
(tensor) C:\Users\Bkmaurya>python
Python 3.6.12 |Anaconda, Inc.| (default, Sep  9 2020, 00:29:25) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "C:\Users\Bkmaurya\anaconda3\envs\tensor\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
**ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Bkmaurya\anaconda3\envs\tensor\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Bkmaurya\anaconda3\envs\tensor\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\Bkmaurya\anaconda3\envs\tensor\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "C:\Users\Bkmaurya\anaconda3\envs\tensor\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Bkmaurya\anaconda3\envs\tensor\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Bkmaurya\anaconda3\envs\tensor\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

Thanks!

**Comment by reachpranjal** [comment]
Trying uninstalling and re-installing TensorFlow 1.15. Make sure that you use conda install instead of pip.

**Comment by amahendrakar** [comment]
@Strange1-7,
Installation issues within the Anaconda environment are tracked in the Anaconda repo.

Could you please submit a new issue using [this link](https://github.com/ContinuumIO/anaconda-issues/issues) and fill in the template, so that the issue can be tracked there. Thanks!
