### ISSUE TITLE
Tensorflow lite(ssd_mobilenet_v2_fpnlite_640*640)  Android APP detect nothing

### ISSUE THREAD

**Issue by hxhexi** [tensorflow/tensorflow#43583]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):**Linux Ubuntu 16.04**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:  **Motorola**
- TensorFlow installed from (source or binary): **Binary**
- TensorFlow version (use command below): **Tf-nightly 2.4.0**
- Python version: **3.6.10**
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: **CUDA 10.2 cuDNN**
- GPU model and memory: **GeForce GTX 1080 8G**

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
1. Use my data to retrain the model **ssd_mobilenet_v2_fpnlite_640*640**, [link](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md)
2. train command: **model_main_tf2.tf** [,link](https://github.com/tensorflow/models/blob/master/research/object_detection/model_main_tf2.py)
    export command: **export_tflite_graph_tf2.py**, [link](https://github.com/tensorflow/models/blob/master/research/object_detection/export_tflite_graph_tf2.py)

**model convert :**
`model = tf.saved_model.load("./saved_model")
model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY].inputs[0].set_shape([1, 640, 640, 3])
tf.saved_model.save(model, "saved_model_updated", signatures=model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY])
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir='./saved_model', signature_keys=['serving_default'])
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()
open("./ssd_resnet50.tflite", "wb").write(tflite_model)`

3. Android app, [link](https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android)
4. main lines in **DetectActivity.java** 

` private static final int TF_OD_API_INPUT_SIZE = 640;

  private static final boolean TF_OD_API_IS_QUANTIZED = true;

  private static final String TF_OD_API_MODEL_FILE = "detect.tflite";

  private static final String TF_OD_API_LABELS_FILE = "labelmap.txt";

  private static final DetectorMode MODE = DetectorMode.TF_OD_API;

  // Minimum detection confidence to track a detection.
  private static final float MINIMUM_CONFIDENCE_TF_OD_API = 0.5f;

  private static final boolean MAINTAIN_ASPECT = false;

  private static final Size DESIRED_PREVIEW_SIZE = new Size(640, 480);`

**Describe the expected behavior**
**Android app should  detect objects  with their names location** 

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
**When run app, errs are like this:**

`2020-09-26 10:13:37.689 21845-21845/org.tensorflow.lite.examples.detection E/tensorflow: CameraActivity: Exception!
    java.lang.IllegalStateException: This model does not contain associated files, and is not a Zip file.
        at org.tensorflow.lite.support.metadata.MetadataExtractor.assertZipFile(MetadataExtractor.java:325)
        at org.tensorflow.lite.support.metadata.MetadataExtractor.getAssociatedFile(MetadataExtractor.java:165)
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.create(TFLiteObjectDetectionAPIModel.java:116)
        at org.tensorflow.lite.examples.detection.DetectorActivity.onPreviewSizeChosen(DetectorActivity.java:106)
        at org.tensorflow.lite.examples.detection.CameraActivity.onPreviewFrame(CameraActivity.java:200)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1175)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6695)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:772)`

**By the way i tested the converted tflite and it's ok.**

**Comment by cevher** [comment]
I have the same problem, anyone with suggestions?

**Comment by quickgrid** [comment]
I followed this guide below with tf1 `ssd_mobilenetv2_oidv4` model and got similar error on [Android sample](https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android). 
https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md


My model conversion script with `tensorflow 1` following the guide,
https://nbviewer.jupyter.org/github/quickgrid/CodeLab/blob/master/tensorflow/TFlite_custom_object_detection_model_Export_TF1.ipynb?flush_cache=True


Label map as mentioned in the guide,
[labelmap.txt](https://github.com/tensorflow/tensorflow/files/5315227/labelmap.txt)


Exported `detect.tflite` properties,
![model - Copy](https://user-images.githubusercontent.com/1857293/94872821-71ad5d00-046f-11eb-8a19-75748d60bd48.jpg)


Partial error message,
```
Process: org.tensorflow.lite.examples.detection, PID: 6129
    java.lang.IllegalStateException: This model does not contain associated files, and is not a Zip file.
        at org.tensorflow.lite.support.metadata.MetadataExtractor.assertZipFile(MetadataExtractor.java:325)
        at org.tensorflow.lite.support.metadata.MetadataExtractor.getAssociatedFile(MetadataExtractor.java:165)
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.create(TFLiteObjectDetectionAPIModel.java:116)
        at org.tensorflow.lite.examples.detection.DetectorActivity.onPreviewSizeChosen(DetectorActivity.java:105)
        at org.tensorflow.lite.examples.detection.CameraActivity$7.onPreviewSizeChosen(CameraActivity.java:446)
        at org.tensorflow.lite.examples.detection.CameraConnectionFragment.setUpCameraOutputs(CameraConnectionFragment.java:357)
        at org.tensorflow.lite.examples.detection.CameraConnectionFragment.openCamera(CameraConnectionFragment.java:362)
        at org.tensorflow.lite.examples.detection.CameraConnectionFragment.access$300(CameraConnectionFragment.java:66)
        at org.tensorflow.lite.examples.detection.CameraConnectionFragment$3.onSurfaceTextureAvailable(CameraConnectionFragment.java:171)
```

**Comment by quickgrid** [comment]
Seems like the problem is maybe missing instructions for android example code. It did not mention about metadata,

https://github.com/tensorflow/examples/blob/e13e7cc1d2df1c006f14a931906f3f409e91c97d/lite/examples/object_detection/android/app/src/main/java/org/tensorflow/lite/examples/detection/tflite/TFLiteObjectDetectionAPIModel.java#L113 


The sample code uses `metadata` implementation,

https://github.com/tensorflow/examples/blob/e13e7cc1d2df1c006f14a931906f3f409e91c97d/lite/examples/object_detection/android/app/build.gradle#L48

Related doc,

https://www.tensorflow.org/lite/convert/metadata#read_the_metadata_in_java


Here it mentions about `tflite` becoming a `zip`, but still keeping `tflite` extension,

> The associated files can now be bundled with the model through the metadata Python library. The new TensorFlow Lite model becomes a zip file that contains both the model and the associated files. It can be unpacked with common zip tools. This new model format keeps using the same file extension, .tflite. It is compatible with existing TFLite framework and Interpreter.

https://www.tensorflow.org/lite/convert/metadata#pack_the_associated_files


I was able get `SSD MobileNet v2 320x320` working with python tflite inference api on colab. Bounding boxes seem correct, labels seem to be wrong.


[Code ](https://github.com/tensorflow/examples/blob/e13e7cc1d2df1c006f14a931906f3f409e91c97d/lite/examples/object_detection/android/app/src/main/java/org/tensorflow/lite/examples/detection/tflite/TFLiteObjectDetectionAPIModel.java#L113 ) from sample,

```
MappedByteBuffer modelFile = loadModelFile(assetManager, modelFilename);
MetadataExtractor metadata = new MetadataExtractor(modelFile);
BufferedReader br =
    new BufferedReader(new InputStreamReader(metadata.getAssociatedFile(labelFilename)));
String line;
while ((line = br.readLine()) != null) {
  LOGGER.w(line);
  d.labels.add(line);
}
br.close();
```

I commented and added this below above code in `TFLiteObjectDetectionAPIModel.java`. It should work by replacing code below with reading `labelmap.txt` line by line and adding to `d`.

```
for(int i = 0; i < 91; i++){
  d.labels.add("label: " + i);
}
```

Seems if the model does not have metadata then `labelmap.txt` can be read into `d`. My takeaway is either the model should be  zipped with metadata or that code in java must be replaced to make the sample work.

https://github.com/tensorflow/examples/blob/e13e7cc1d2df1c006f14a931906f3f409e91c97d/lite/examples/object_detection/android/app/src/main/java/org/tensorflow/lite/examples/detection/tflite/TFLiteObjectDetectionAPIModel.java#L111

**Comment by KevinCS17** [comment]
@quickgrid hmm sorry
I'am using ssd mobilenet V2 coco 300x300 trained using tensorflow 2 following this [tutorial](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md#running-our-model-on-android)

this is my error
`2020-10-13 01:44:23.049 19435-19435/org.tensorflow.lite.examples.detection E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.tensorflow.lite.examples.detection, PID: 19435
    java.lang.IllegalStateException: This model does not contain associated files, and is not a Zip file.
        at org.tensorflow.lite.support.metadata.MetadataExtractor.assertZipFile(MetadataExtractor.java:325)
        at org.tensorflow.lite.support.metadata.MetadataExtractor.getAssociatedFile(MetadataExtractor.java:165)
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.create(TFLiteObjectDetectionAPIModel.java:118)
        at org.tensorflow.lite.examples.detection.DetectorActivity.onPreviewSizeChosen(DetectorActivity.java:99)
        at org.tensorflow.lite.examples.detection.CameraActivity$7.onPreviewSizeChosen(CameraActivity.java:446)
        at org.tensorflow.lite.examples.detection.CameraConnectionFragment.setUpCameraOutputs(CameraConnectionFragment.java:357)
        at org.tensorflow.lite.examples.detection.CameraConnectionFragment.openCamera(CameraConnectionFragment.java:362)
        at org.tensorflow.lite.examples.detection.CameraConnectionFragment.access$300(CameraConnectionFragment.java:66)
        at org.tensorflow.lite.examples.detection.CameraConnectionFragment$3.onSurfaceTextureAvailable(CameraConnectionFragment.java:171)
        at android.view.TextureView.getTextureLayer(TextureView.java:400)
        at android.view.TextureView.draw(TextureView.java:349)
        at android.view.View.updateDisplayListIfDirty(View.java:22062)
        at android.view.View.draw(View.java:22917)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
        at android.view.View.updateDisplayListIfDirty(View.java:22048)
        at android.view.View.draw(View.java:22917)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
        at android.view.View.updateDisplayListIfDirty(View.java:22048)
        at android.view.View.draw(View.java:22917)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
        at android.view.View.draw(View.java:23190)
        at android.view.View.updateDisplayListIfDirty(View.java:22062)
        at android.view.View.draw(View.java:22917)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1246)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
        at android.view.View.draw(View.java:23190)
        at android.view.View.updateDisplayListIfDirty(View.java:22062)
        at android.view.View.draw(View.java:22917)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
        at android.view.View.updateDisplayListIfDirty(View.java:22048)
        at android.view.View.draw(View.java:22917)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
        at android.view.View.updateDisplayListIfDirty(View.java:22048)
        at android.view.View.draw(View.java:22917)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
        at android.view.View.updateDisplayListIfDirty(View.java:22048)
        at android.view.View.draw(View.java:22917)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
        at android.view.View.updateDisplayListIfDirty(View.java:22048)
        at android.view.View.draw(View.java:22917)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
        at android.view.View.draw(View.java:23190)
        at com.android.internal.policy.DecorView.draw(DecorView.java:1154)
        at android.view.View.updateDisplayListIfDirty(View.java:22062)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:588)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:594)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:667)
2020-10-13 01:44:23.049 19435-19435/org.tensorflow.lite.examples.detection E/AndroidRuntime:     at android.view.ViewRootImpl.draw(ViewRootImpl.java:4296)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4080)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3348)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2225)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9126)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
        at android.view.Choreographer.doCallbacks(Choreographer.java:797)
        at android.view.Choreographer.doFrame(Choreographer.java:732)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
2020-10-13 01:44:24.749 19435-21998/org.tensorflow.lite.examples.detection W/System: A resource failed to call close. 
`

Its crashing when the compile finished
I already read your answer
but can you make it step by step what should I do, because I am new about this
so i cant understand what really I need to do with your answer recently

please help me :)

**Comment by quickgrid** [comment]
@KevinCS17 Seems code was updated and many things changed, https://github.com/tensorflow/examples/commit/bac70589c2b206614f7f95ca84b624a9d6e9449e. You can try with latest one.

**Comment by Jangbyeongwook** [comment]
@KevinCS17 I use below code  in aTFLiteObjectDetectionAPIModel.java : 
`InputStream is = assetManager.open(labelFilename);
    BufferedReader br = new BufferedReader(new InputStreamReader(is));`

instead

` BufferedReader br =
        new BufferedReader(new InputStreamReader(metadata.getAssociatedFile(labelFilename)));`

**Comment by KevinCS17** [comment]
> @KevinCS17 Seems code was updated and many things changed, [tensorflow/examples@bac7058](https://github.com/tensorflow/examples/commit/bac70589c2b206614f7f95ca84b624a9d6e9449e). You can try with latest one.

Yup it just updated last night (1 am in my country), and I work in 12 - 4 am.. dont know if that just updated.. I must try the new one..

**Comment by KevinCS17** [comment]
> @KevinCS17 I use below code in aTFLiteObjectDetectionAPIModel.java :
> `InputStream is = assetManager.open(labelFilename); BufferedReader br = new BufferedReader(new InputStreamReader(is));`
> 
> instead
> 
> ` BufferedReader br = new BufferedReader(new InputStreamReader(metadata.getAssociatedFile(labelFilename)));`

Thank you for the help and fast responds..
I'll try that one later as soon as possible.. and report its work or not.. 🙏🙏

**Comment by KevinCS17** [comment]
ITS WORKKKK
the label map a little but problem i think

`???
person
car
bicycle
motorcycle
stop sign`

its already as same as the class
but
when detecting person it say "???"
detecting car it say "person"
until stop sign it saya "motorcycle"

so the class = class + 1

so I'll already fix it with
changing the labelmap.txt to
`person
car
bicycle
motorcycle
stop sign
`

**Comment by KevinCS17** [comment]
So what I did is using 

> @KevinCS17 Seems code was updated and many things changed, [tensorflow/examples@bac7058](https://github.com/tensorflow/examples/commit/bac70589c2b206614f7f95ca84b624a9d6e9449e). You can try with latest one.

this new github

changing this 

> @KevinCS17 I use below code in aTFLiteObjectDetectionAPIModel.java :
> `InputStream is = assetManager.open(labelFilename); BufferedReader br = new BufferedReader(new InputStreamReader(is));`
> 
> instead
> 
> ` BufferedReader br = new BufferedReader(new InputStreamReader(metadata.getAssociatedFile(labelFilename)));`

from
`    try (BufferedReader br =
        new BufferedReader(
            new InputStreamReader(
                metadata.getAssociatedFile(labelFilename), Charset.defaultCharset()))) {
      String line;
      while ((line = br.readLine()) != null) {
        Log.w(TAG, line);
        d.labels.add(line);
      }
    }`

to this

`try (InputStream is = assetManager.open(labelFilename); BufferedReader br = new BufferedReader(new InputStreamReader(is))) {
      String line;
      while ((line = br.readLine()) != null) {
        Log.w(TAG, line);
        d.labels.add(line);
      }
    }`

I dont use quantized models so changing this line
`private static final boolean TF_OD_API_IS_QUANTIZED = true;`
to
`private static final boolean TF_OD_API_IS_QUANTIZED = false;`

**Comment by mpa74** [comment]
> try (InputStream is = assetManager.open(labelFilename); BufferedReader br = new BufferedReader(new InputStreamReader(is))) { String line; while ((line = br.readLine()) != null) { Log.w(TAG, line); d.labels.add(line); } }

not worked for me: i have error "error: cannot find symbol InputStream"
*Repository https://github.com/tensorflow/examples downloaded 15.10.2020*

**Comment by KevinCS17** [comment]
> > try (InputStream is = assetManager.open(labelFilename); BufferedReader br = new BufferedReader(new InputStreamReader(is))) { String line; while ((line = br.readLine()) != null) { Log.w(TAG, line); d.labels.add(line); } }
> 
> not worked for me: i have error "error: cannot find symbol InputStream"
> _Repository https://github.com/tensorflow/examples downloaded 15.10.2020_

have you already alt + enter to import the new class?

if it doesnt work , try to see your own model.tflite models in [Netron](https://lutzroeder.github.io/netron/)
just drag and drop your model file to the Netron browser
compare it with the detect.tflite in the example
the example using ssd_mobilnet_v1 I think... (but I am not sure about the models)

**Comment by mpa74** [comment]
> > > try (InputStream is = assetManager.open(labelFilename); BufferedReader br = new BufferedReader(new InputStreamReader(is))) { String line; while ((line = br.readLine()) != null) { Log.w(TAG, line); d.labels.add(line); } }
> > 
> > 
> > not worked for me: i have error "error: cannot find symbol InputStream"
> > _Repository https://github.com/tensorflow/examples downloaded 15.10.2020_
> 
> have you already alt + enter to import the new class on Android Studio?
> 
> if it doesnt work , try to see your own model.tflite models in [Netron](https://lutzroeder.github.io/netron/)
> just drag and drop your model file to the Netron browser
> compare it with the detect.tflite in the example
> the example using ssd_mobilnet_v1 I think... (but I am not sure about the models)

Thanks! Alt+enter resolve error

**Comment by KevinCS17** [comment]
> Thanks! Alt+enter resolve error

Very well.. happy to hear that too :)

**Comment by Jangbyeongwook** [comment]
@KevinCS17 
When I tested it on the new github, it worked as follows.
`    //add line
    AssetManager am = context.getAssets();
    InputStream is = am.open(labelFilename);

    MappedByteBuffer modelFile = loadModelFile(context.getAssets(), modelFilename);
    MetadataExtractor metadata = new MetadataExtractor(modelFile);
    try (BufferedReader br =
        new BufferedReader(
            new InputStreamReader(is))) {
      String line;
      while ((line = br.readLine()) != null) {
        Log.w(TAG, line);
        d.labels.add(line);
      }
    }`
I hope it helps
Sorry for not speaking English well :(

**Comment by zacky131** [comment]
@Jangbyeongwook Thank you so much!!!! you are really savior of my life. This solve all my problems after a week unable to sleep very well :)

**Comment by tusu18** [comment]
@KevinCS17 
I tweaked the same thing into my code
Although log cat shows following error
Still none of the objects are detected

2020-11-05 14:45:52.620 772-9676/? E/DataTable: hwcam_data_table_set_entry_data failed,error id : 22
2020-11-05 14:45:52.620 772-18232/? I/AntiBanding: onSubAlgoProcess() mAlgoCtx.continue_detect_cnt :0, mAlgoCtx.succ_detect_cnt : 0, mAlgoCtx.motion_flag = 0, detect_result:0, frequency_detected = 0,cur_expo = 70000
2020-11-05 14:45:52.620 772-9676/? E/ImagingSystemUtils: setMetadata: set metadata failed, data_max_count(76), type_size(1), Tag(2147484178)

**Comment by cachvico** [comment]
https://github.com/tensorflow/examples/compare/master...cachvico:darren/fix-od for clarity

Although I'm not yet getting results.. does anyone have an example of a colab they got this to work with?

**Comment by SOTASHE** [comment]
![Screenshot from 2021-01-28 17-46-08](https://user-images.githubusercontent.com/48323383/106164365-8afeb580-6192-11eb-87a7-71ab0655d6d2.png)




I trained a tensorflow model (SSD MOBILE NET V2) and converted to tflite to detect on android using tensorflow object detection demo app but the model does not detect any object. Please help!

**Comment by SOTASHE** [comment]
> @Jangbyeongwook Thank you so much!!!! you are really savior of my life. This solve all my problems after a week unable to sleep very well :)

hi, I'm facing the same problem. please help

**Comment by SOTASHE** [comment]
> @KevinCS17 Seems code was updated and many things changed, [tensorflow/examples@bac7058](https://github.com/tensorflow/examples/commit/bac70589c2b206614f7f95ca84b624a9d6e9449e). You can try with latest one.

I cloned the updated repo but still getting the same error. The app runs but does not detect object

**Comment by etekumoses** [comment]
> @Jangbyeongwook Thank you so much!!!! you are really savior of my life. This solve all my problems after a week unable to sleep very well :)

I am still getting this issue kindly help.
java.lang.IllegalArgumentException: Cannot copy to a TensorFlowLite tensor (serving_default_mobilenetv2_1.00_224_input:0) with 602112 bytes from a Java Buffer with 178608 bytes.
