### ISSUE TITLE
Beginner tutorial fails with internal error

### ISSUE THREAD

**Issue by kreegah** [tensorflow/tensorflow#43606]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

My pc runs windows 10 pro
Installed anaconda 3 individual edition, Python 3.8
Installed tensorflow 2.3.1 using pip install tensorflow

Bug appears running the very first beginner tutorial  beginner.ipynb.
An exception is raised while trying to create the model object in the third tutorial's command. Below a copy of the console putput:

Python 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.16.1 -- An enhanced Interactive Python.

import tensorflow as tf

2020-09-27 11:38:37.267183: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll

mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

2020-09-27 11:38:37.267183: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2020-09-27 11:39:35.773790: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library nvcuda.dll
Traceback (most recent call last):

  File "<ipython-input-3-9eaab81d20e2>", line 1, in <module>
    model = tf.keras.models.Sequential([

  File "C:\Users\nmb31\anaconda3\lib\site-packages\tensorflow\python\training\tracking\base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)

  File "C:\Users\nmb31\anaconda3\lib\site-packages\tensorflow\python\keras\engine\sequential.py", line 116, in __init__
    super(functional.Functional, self).__init__(  # pylint: disable=bad-super-call

  File "C:\Users\nmb31\anaconda3\lib\site-packages\tensorflow\python\training\tracking\base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)

  File "C:\Users\nmb31\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py", line 308, in __init__
    self._init_batch_counters()

  File "C:\Users\nmb31\anaconda3\lib\site-packages\tensorflow\python\training\tracking\base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)

  File "C:\Users\nmb31\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py", line 317, in _init_batch_counters
    self._train_counter = variables.Variable(0, dtype='int64', aggregation=agg)

  File "C:\Users\nmb31\anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 262, in __call__
    return cls._variable_v2_call(*args, **kwargs)

  File "C:\Users\nmb31\anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 244, in _variable_v2_call
    return previous_getter(

  File "C:\Users\nmb31\anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 237, in <lambda>
    previous_getter = lambda **kws: default_variable_creator_v2(None, **kws)

  File "C:\Users\nmb31\anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2633, in default_variable_creator_v2
    return resource_variable_ops.ResourceVariable(

  File "C:\Users\nmb31\anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 264, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)

  File "C:\Users\nmb31\anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1507, in __init__
    self._init_from_args(

  File "C:\Users\nmb31\anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1661, in _init_from_args
    handle = eager_safe_variable_handle(

  File "C:\Users\nmb31\anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 242, in eager_safe_variable_handle
    return _variable_handle_from_shape_and_dtype(

  File "C:\Users\nmb31\anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 174, in _variable_handle_from_shape_and_dtype
    gen_logging_ops._assert(  # pylint: disable=protected-access

  File "C:\Users\nmb31\anaconda3\lib\site-packages\tensorflow\python\ops\gen_logging_ops.py", line 49, in _assert
    _ops.raise_from_not_ok_status(e, name)

  File "C:\Users\nmb31\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 6843, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)

  File "<string>", line 3, in raise_from

InvalidArgumentError: assertion failed: [0] [Op:Assert] name: EagerVariableNameReuse

2020-09-27 11:38:37.267183: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2020-09-27 11:39:35.773790: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library nvcuda.dll
2020-09-27 11:39:36.282700: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce 940MX computeCapability: 5.0
coreClock: 1.189GHz coreCount: 3 deviceMemorySize: 4.00GiB deviceMemoryBandwidth: 37.33GiB/s
2020-09-27 11:39:36.282745: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2020-09-27 11:39:36.288963: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
2020-09-27 11:39:36.292338: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cufft64_10.dll
2020-09-27 11:39:36.293694: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library curand64_10.dll
2020-09-27 11:39:36.298451: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusolver64_10.dll
2020-09-27 11:39:36.301791: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusparse64_10.dll
2020-09-27 11:39:36.311463: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2020-09-27 11:39:36.312165: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-09-27 11:39:36.312794: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-27 11:39:36.320212: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1ed9b2f1ee0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-27 11:39:36.320264: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-27 11:39:36.321043: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce 940MX computeCapability: 5.0
coreClock: 1.189GHz coreCount: 3 deviceMemorySize: 4.00GiB deviceMemoryBandwidth: 37.33GiB/s
2020-09-27 11:39:36.321082: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2020-09-27 11:39:36.321094: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
2020-09-27 11:39:36.321102: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cufft64_10.dll
2020-09-27 11:39:36.321110: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library curand64_10.dll
2020-09-27 11:39:36.321117: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusolver64_10.dll
2020-09-27 11:39:36.321125: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusparse64_10.dll
2020-09-27 11:39:36.321132: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2020-09-27 11:39:36.321849: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-09-27 11:39:36.379494: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-27 11:39:36.379521: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 
2020-09-27 11:39:36.379530: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N 
2020-09-27 11:39:36.380229: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3128 MB memory) -> physical GPU (device: 0, name: GeForce 940MX, pci bus id: 0000:01:00.0, compute capability: 5.0)
2020-09-27 11:39:36.383452: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1ed9e39a4d0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-09-27 11:39:36.383481: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce 940MX, Compute Capability 5.0

**Comment by amahendrakar** [comment]
@kreegah,
I was able to run the code without any issues on TF v2.3, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/9a9529f36a2977b1b72444a89ec5526e/43606.ipynb).

Also, please check [this comment](https://github.com/tensorflow/tensorflow/issues/38518#issuecomment-619538236) from a similar issue and let us know if it helps. Thanks!

**Comment by kreegah** [comment]
Hi Abhilash Mahendrakar,
what python version did you run your notebook on?
I suspect my problem might have to do with my current python installation.
A wild guess.

**Comment by kreegah** [comment]
amahendrakar I can run your notebook on colab without problems but if I try to do it on my local pc the error appears. Being a newb I'm left clueless.

**Comment by kreegah** [comment]
Hi,
all is well. I guess. I followed a hint from stackoverflow and inserted  a
command so tensorflow ignores my GPU, like this (please refer to the sample
code you linked):

> import tensorflow as tf
> tf.config.set_visible_devices([], 'GPU')

# remaining code follows here

It worked perfectly, just as in the tutorial. So I guess we'll have to work
without GPUs.

Thanks!

**Comment by amahendrakar** [comment]
@kreegah,
Sorry for the delayed response. 
> what python version did you run your notebook on?

The Python version of the notebook is Python v3.6.9.
> It worked perfectly, just as in the tutorial. 

Marking the issue as closed since it is resolved. Please feel free to re-open the issue if necessary. Thanks!
