### ISSUE TITLE
TFLite android image classification demo failed on samsung note10 whose soc is snapdragon 855

### ISSUE THREAD

**Issue by qipengwang** [tensorflow/tensorflow#43663]
- system platform: macos 10.15

- example: [tflite image classification official demo](https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/android)

- IDE: android studio 4.0.1

- hardware: samsung note10 equiped with snapdragon 855

errors: when I tried to use the dsp delegate on the phone, I modified the code like this:
```
case DSP:
                dspDelegate = new HexagonDelegate(activity);
                tfliteOptions.addDelegate(dspDelegate);
                break;
```
in the [classifier.java](https://github.com/tensorflow/examples/blob/master/lite/examples/image_classification/android/lib_support/src/main/java/org/tensorflow/lite/examples/classification/tflite/Classifier.java#L201)

so I built and run the demo and selected quantized_efficientnet & dsp to run the DNN on the hexagon and it was ok.

However, when I download the android NDK 21.3.6528147, android studio tell me that I need to install NDK 21.0.6113669, I followed the instruction and re-built and re-run the app. When I selected quantized_efficientnet & dsp again, I got the following error:

```
E/AndroidRuntime: FATAL EXCEPTION: inference
E/org.tensorflow.lite.examples.classification: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/apps_std_imp.c:729:Error 45: fopen failed for testsig-0xfe534ed3.so. (No such file or directory)
E/org.tensorflow.lite.examples.classification: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/apps_std_imp.c:729:Error 45: fopen failed for testsig.so. (No such file or directory)
D/org.tensorflow.lite.examples.classification: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:989: Error 0x80000406: remote_handle_open_domain: dynamic loading failed for file:///libhexagon_nn_skel_v66.so?hexagon_nn_domains_skel_handle_invoke&_modver=1.0&_dom=cdsp on domain 3 (dlerror segment 0 failed signature verification (0xF4 B) for libhexagon_nn_s
    vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:1027: Error 0x80000406: remote_handle64_open failed for file:///libhexagon_nn_skel_v66.so?hexagon_nn_domains_skel_handle_invoke&_modver=1.0&_dom=cdsp
W/tflite: Failed to fetch Hexagon NN version. This might be because you're using incompatible versions of libhexagon_interface and libhexagon_nn_skel. You must use compatible versions. Refer to Tensorflow Lite Hexagon Delegate Guide.
I/tflite: Hexagon Delegate is not supported.
E/AndroidRuntime: FATAL EXCEPTION: inference
    Process: org.tensorflow.lite.examples.classification, PID: 9186
    java.lang.UnsupportedOperationException: This Device doesn't support Hexagon DSP execution.
        at org.tensorflow.lite.HexagonDelegate.<init>(HexagonDelegate.java:39)
        at org.tensorflow.lite.examples.classification.tflite.Classifier.<init>(Classifier.java:257)
        at org.tensorflow.lite.examples.classification.tflite.ClassifierQuantizedEfficientNet.<init>(ClassifierQuantizedEfficientNet.java:46)
        at org.tensorflow.lite.examples.classification.tflite.Classifier.create(Classifier.java:159)
        at org.tensorflow.lite.examples.classification.ClassifierActivity.recreateClassifier(ClassifierActivity.java:162)
        at org.tensorflow.lite.examples.classification.ClassifierActivity.lambda$onInferenceConfigurationChanged$0$ClassifierActivity(ClassifierActivity.java:132)
        at org.tensorflow.lite.examples.classification.-$$Lambda$ClassifierActivity$83lGy2TUjuj0M5n4BhMB9qlLgSY.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:216)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

where Classifier.java:257 is 
dspDelegate = new HexagonDelegate(activity); // (definition is: private HexagonDelegate dspDelegate = null;)

so I uninstalled the NDK and it was ok again.

**Comment by karimnosseir** [comment]
1)
In the initialize line for the delegate
(e.g.) hexagonDelegate = new HexagonDelegate(activity);
Can you print
activity.getApplicationInfo().nativeLibraryDir
and check that the shared lib files are on the device under the same path.
adb shell ls -al <PATH_PRINTED_FROM_ABOVE>

If you can paste the results in the reply will be good.

3) Are you using app bundle ?

**Comment by qipengwang** [comment]
I added 
`System.out.println("activity.getApplicationInfo().nativeLibraryDir: " + activity.getApplicationInfo().nativeLibraryDir);`
before initialize line for the dsp delegate like this:
```
case DSP:
                System.out.println("activity.getApplicationInfo().nativeLibraryDir: " + activity.getApplicationInfo().nativeLibraryDir);
                dspDelegate = new HexagonDelegate(activity);
                tfliteOptions.addDelegate(dspDelegate);
```

when I build an run it without NDK, 
the output is
`I/System.out: activity.getApplicationInfo().nativeLibraryDir: /data/app/org.tensorflow.lite.examples.classification-7iQPWk8WX-zeI0qENU6CHw==/lib/arm64`

and I check the path on the device and the output is
```
total 8526
drwxr-xr-x 2 system system    3488 2020-10-07 10:28 .
drwxr-xr-x 3 system system    3488 2020-10-07 10:28 ..
-rwxr-xr-x 1 system system   88096 1981-01-01 01:01 libhexagon_interface.so
-rwxr-xr-x 1 system system 1148720 1981-01-01 01:01 libhexagon_nn_skel.so
-rwxr-xr-x 1 system system 1165168 1981-01-01 01:01 libhexagon_nn_skel_v65.so
-rwxr-xr-x 1 system system 1161072 1981-01-01 01:01 libhexagon_nn_skel_v66.so
-rwxr-xr-x 1 system system 2178720 1981-01-01 01:01 libtensorflowlite_gpu_jni.so
-rwxr-xr-x 1 system system  531432 1981-01-01 01:01 libtensorflowlite_hexagon_jni.so
-rwxr-xr-x 1 system system 2440400 1981-01-01 01:01 libtensorflowlite_jni.so
```

so I download the NDK and re-do the same steps above
and I get the output like this:

`I/System.out: activity.getApplicationInfo().nativeLibraryDir: /data/app/org.tensorflow.lite.examples.classification-lFI9puZibQIiXlcPlB0lxw==/lib/arm64`

which is different from the above one. So I also check the dir and the output is like this:

```
total 8526
drwxr-xr-x 2 system system    3488 2020-10-07 10:38 .
drwxr-xr-x 3 system system    3488 2020-10-07 10:38 ..
-rwxr-xr-x 1 system system   88088 1981-01-01 01:01 libhexagon_interface.so
-rwxr-xr-x 1 system system 1148720 1981-01-01 01:01 libhexagon_nn_skel.so
-rwxr-xr-x 1 system system 1165168 1981-01-01 01:01 libhexagon_nn_skel_v65.so
-rwxr-xr-x 1 system system 1161072 1981-01-01 01:01 libhexagon_nn_skel_v66.so
-rwxr-xr-x 1 system system 2178720 1981-01-01 01:01 libtensorflowlite_gpu_jni.so
-rwxr-xr-x 1 system system  531432 1981-01-01 01:01 libtensorflowlite_hexagon_jni.so
-rwxr-xr-x 1 system system 2440400 1981-01-01 01:01 libtensorflowlite_jni.so
```

and I find both the output of the adb shell are same, including 7 files with the same filename 

while the build ouput with NDK is like this:
```
Executing tasks: [:app:assembleDebug] in project /Users/wangqipeng/Project/tflite_image_classification

WARNING: The specified Android SDK Build Tools version (28.0.0) is ignored, as it is below the minimum supported version (29.0.2) for Android Gradle Plugin 4.0.0.
Android SDK Build Tools 29.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '28.0.0'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
WARNING: The specified Android SDK Build Tools version (28.0.0) is ignored, as it is below the minimum supported version (29.0.2) for Android Gradle Plugin 4.0.0.
Android SDK Build Tools 29.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '28.0.0'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :lib_support:preBuild UP-TO-DATE
> Task :lib_support:preDebugBuild UP-TO-DATE
> Task :models:downloadEfficientNetFloat UP-TO-DATE
> Task :models:unzipModelEfficientNetFloat UP-TO-DATE
> Task :models:downloadEfficientNetQuant UP-TO-DATE
> Task :models:unzipModelEfficientNetQuant UP-TO-DATE
> Task :models:downloadModelFloat UP-TO-DATE

> Task :models:unzipModelFloat
Unzipping build/intermediates/mobilenet_v1_1.0_224.tgz

> Task :models:downloadModelQuant UP-TO-DATE

> Task :models:unzipModelQuant
Unzipping build/intermediates/mobilenet_v1_1.0_224_quant.tgz

> Task :models:cleanUnusedFiles
> Task :models:preBuild
> Task :models:preDebugBuild
> Task :models:compileDebugAidl NO-SOURCE
> Task :lib_support:compileDebugAidl NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :lib_support:packageDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:javaPreCompileDebug UP-TO-DATE
> Task :app:generateDebugResValues UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :models:packageDebugRenderscript NO-SOURCE
> Task :lib_support:generateDebugResValues UP-TO-DATE
> Task :models:compileDebugRenderscript NO-SOURCE
> Task :models:generateDebugResValues UP-TO-DATE
> Task :lib_support:compileDebugRenderscript NO-SOURCE
> Task :lib_support:generateDebugResources UP-TO-DATE
> Task :lib_support:packageDebugResources UP-TO-DATE
> Task :models:generateDebugResources UP-TO-DATE
> Task :models:packageDebugResources UP-TO-DATE
> Task :app:mergeDebugResources UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:extractDeepLinksDebug UP-TO-DATE
> Task :lib_support:extractDeepLinksDebug UP-TO-DATE
> Task :lib_support:processDebugManifest UP-TO-DATE
> Task :models:extractDeepLinksDebug UP-TO-DATE
> Task :models:processDebugManifest UP-TO-DATE
> Task :app:processDebugManifest UP-TO-DATE
> Task :lib_support:compileDebugLibraryResources UP-TO-DATE
> Task :lib_support:parseDebugLocalResources UP-TO-DATE
> Task :models:parseDebugLocalResources UP-TO-DATE
> Task :models:generateDebugRFile UP-TO-DATE
> Task :lib_support:generateDebugRFile UP-TO-DATE
> Task :models:compileDebugLibraryResources UP-TO-DATE
> Task :app:processDebugResources UP-TO-DATE
> Task :lib_support:generateDebugBuildConfig UP-TO-DATE
> Task :lib_support:javaPreCompileDebug UP-TO-DATE
> Task :models:generateDebugBuildConfig UP-TO-DATE
> Task :models:javaPreCompileDebug UP-TO-DATE
> Task :models:compileDebugJavaWithJavac UP-TO-DATE
> Task :models:bundleLibCompileToJarDebug UP-TO-DATE
> Task :lib_support:compileDebugJavaWithJavac UP-TO-DATE
> Task :lib_support:bundleLibCompileToJarDebug UP-TO-DATE
> Task :app:compileDebugJavaWithJavac UP-TO-DATE
> Task :app:compileDebugSources UP-TO-DATE
> Task :app:mergeDebugShaders UP-TO-DATE
> Task :app:compileDebugShaders NO-SOURCE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :lib_support:mergeDebugShaders UP-TO-DATE
> Task :lib_support:compileDebugShaders NO-SOURCE
> Task :lib_support:generateDebugAssets UP-TO-DATE
> Task :lib_support:packageDebugAssets UP-TO-DATE
> Task :models:mergeDebugShaders UP-TO-DATE
> Task :models:compileDebugShaders NO-SOURCE
> Task :models:generateDebugAssets UP-TO-DATE
> Task :models:packageDebugAssets UP-TO-DATE
> Task :app:mergeDebugAssets UP-TO-DATE
> Task :app:processDebugJavaRes NO-SOURCE
> Task :lib_support:processDebugJavaRes NO-SOURCE
> Task :lib_support:bundleLibResDebug NO-SOURCE
> Task :models:processDebugJavaRes NO-SOURCE
> Task :models:bundleLibResDebug NO-SOURCE
> Task :app:mergeDebugJavaResource UP-TO-DATE
> Task :app:desugarDebugFileDependencies UP-TO-DATE
> Task :app:checkDebugDuplicateClasses UP-TO-DATE
> Task :app:mergeExtDexDebug UP-TO-DATE
> Task :lib_support:bundleLibRuntimeToJarDebug UP-TO-DATE
> Task :models:bundleLibRuntimeToJarDebug UP-TO-DATE
> Task :app:dexBuilderDebug UP-TO-DATE
> Task :app:mergeLibDexDebug UP-TO-DATE
> Task :app:mergeProjectDexDebug UP-TO-DATE
> Task :app:mergeDebugJniLibFolders UP-TO-DATE
> Task :lib_support:mergeDebugJniLibFolders UP-TO-DATE
> Task :lib_support:mergeDebugNativeLibs UP-TO-DATE
> Task :lib_support:stripDebugDebugSymbols
> Task :lib_support:copyDebugJniLibsProjectOnly
> Task :models:mergeDebugJniLibFolders UP-TO-DATE
> Task :models:mergeDebugNativeLibs UP-TO-DATE
> Task :models:stripDebugDebugSymbols NO-SOURCE
> Task :models:copyDebugJniLibsProjectOnly UP-TO-DATE
> Task :app:validateSigningDebug UP-TO-DATE
> Task :app:mergeDebugNativeLibs
> Task :app:stripDebugDebugSymbols
> Task :app:packageDebug
> Task :app:assembleDebug

BUILD SUCCESSFUL in 4s
67 actionable tasks: 8 executed, 59 up-to-date

Build Analyzer results available
```

**Comment by emakryo** [comment]
Are there any updates on this issue?
I have a similar issue with my Sony Xperia XZ2 phone.

**Comment by karimnosseir** [comment]
Wondering if it might be related to app bundle
see https://www.tensorflow.org/lite/performance/hexagon_delegate#add_the_shared_library_to_your_app

@emakryo what other log you get beside the testsig one ?

**Comment by mohantym** [comment]
Hi @qipengwang ! This issue is running fine in Android studio latest version . Can you let us know from your side ?
