### ISSUE TITLE
Converter fails when using a channel first model and batchnorm

### ISSUE THREAD

**Issue by PoseAI** [tensorflow/tensorflow#43676]
**System information**
- OS Platform and Distribution: Linux Ubuntu 18:04
- TensorFlow installed from: binary (mini conda)
- TensorFlow version: 2.2

**Command used to run the converter or code if you’re using the Python API**
```
#  A VERY SIMPLE TWO LAYER MODEL WHICH FAILS ONLY WHEN CHANNELS FIRST

DATA_FORMAT = "channels_first"
backend.set_image_data_format(DATA_FORMAT)
img_inputs = keras.Input(shape=(3, 384, 384))
x = layers.Conv2D(8, kernel_size=3, strides=1, padding='same', use_bias=False, data_format=DATA_FORMAT,
                  activation=None, name='conv')(img_inputs)
x = layers.BatchNormalization(axis=1, epsilon=1e-3, momentum=0.999, name='BN')(x)
model = keras.Model(inputs=img_inputs, outputs=x, name="channel_first_test")
model.summary()

converter = tf.lite.TFLiteConverter.from_keras_model(model)

# fails with and without these next options, (but without even just Conv2D also fails with channels first)
converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
converter.allow_custom_ops=True
converter.experimental_new_converter =True

tflite_model = converter.convert()

```

**The output from the converter invocation**

```

2020-09-30 17:26:45.007381: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-09-30 17:26:45.037941: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-30 17:26:45.038216: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.65GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2020-09-30 17:26:45.038315: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-09-30 17:26:45.039124: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-09-30 17:26:45.039929: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-09-30 17:26:45.040053: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-09-30 17:26:45.040893: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-09-30 17:26:45.041375: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-09-30 17:26:45.043242: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-09-30 17:26:45.043302: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-30 17:26:45.043595: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-30 17:26:45.043841: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-09-30 17:26:45.044038: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-09-30 17:26:45.047755: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 3999980000 Hz
2020-09-30 17:26:45.048058: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x557076b6a340 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-30 17:26:45.048068: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-30 17:26:45.048152: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-30 17:26:45.048409: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.65GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2020-09-30 17:26:45.048426: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-09-30 17:26:45.048433: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-09-30 17:26:45.048439: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-09-30 17:26:45.048445: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-09-30 17:26:45.048451: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-09-30 17:26:45.048456: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-09-30 17:26:45.048462: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-09-30 17:26:45.048488: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-30 17:26:45.048749: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-30 17:26:45.048988: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-09-30 17:26:45.049004: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-09-30 17:26:45.104115: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-30 17:26:45.104128: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-09-30 17:26:45.104132: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-09-30 17:26:45.104216: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-30 17:26:45.104484: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-30 17:26:45.104733: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-30 17:26:45.104974: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9708 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
2020-09-30 17:26:45.106002: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55707a4518d0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-09-30 17:26:45.106009: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
Model: "channel_first_test"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         [(None, 3, 384, 384)]     0         
_________________________________________________________________
conv (Conv2D)                (None, 8, 384, 384)       216       
_________________________________________________________________
BN (BatchNormalization)      (None, 8, 384, 384)       32        
=================================================================
Total params: 248
Trainable params: 232
Non-trainable params: 16
_________________________________________________________________
2020-09-30 17:26:45.464048: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-30 17:26:45.464203: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 1
2020-09-30 17:26:45.464263: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-09-30 17:26:45.464463: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-30 17:26:45.464599: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.65GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2020-09-30 17:26:45.464618: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-09-30 17:26:45.464625: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-09-30 17:26:45.464631: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-09-30 17:26:45.464637: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-09-30 17:26:45.464643: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-09-30 17:26:45.464649: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-09-30 17:26:45.464655: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-09-30 17:26:45.464680: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-30 17:26:45.464824: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-30 17:26:45.464947: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-09-30 17:26:45.464961: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-30 17:26:45.464964: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-09-30 17:26:45.464966: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-09-30 17:26:45.465005: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-30 17:26:45.465150: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-30 17:26:45.465279: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9708 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
2020-09-30 17:26:45.466142: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:797] Optimization results for grappler item: graph_to_optimize
2020-09-30 17:26:45.466150: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   function_optimizer: function_optimizer did nothing. time = 0.002ms.
2020-09-30 17:26:45.466152: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-09-30 17:26:45.474700: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-30 17:26:45.474845: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 1
2020-09-30 17:26:45.474873: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-09-30 17:26:45.475055: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-30 17:26:45.475192: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.65GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2020-09-30 17:26:45.475208: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-09-30 17:26:45.475214: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-09-30 17:26:45.475220: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-09-30 17:26:45.475225: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-09-30 17:26:45.475231: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-09-30 17:26:45.475237: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-09-30 17:26:45.475243: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-09-30 17:26:45.475267: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-30 17:26:45.475409: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-30 17:26:45.475530: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-09-30 17:26:45.475541: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-30 17:26:45.475544: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-09-30 17:26:45.475546: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-09-30 17:26:45.475583: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-30 17:26:45.475725: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-30 17:26:45.475852: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9708 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
2020-09-30 17:26:45.477438: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:797] Optimization results for grappler item: graph_to_optimize
2020-09-30 17:26:45.477447: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   constant_folding: Graph size after: 9 nodes (-5), 8 edges (-5), time = 0.361ms.
2020-09-30 17:26:45.477450: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   constant_folding: Graph size after: 9 nodes (0), 8 edges (0), time = 0.108ms.
Traceback (most recent call last):
  File "/home/m/PycharmProjects/test/model/tflite_test.py", line 43, in <module>
    tflite_model = converter.convert()
  File "/home/m/miniconda3/envs/tf/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 514, in convert
    result = _toco_convert_impl(
  File "/home/m/miniconda3/envs/tf/lib/python3.8/site-packages/tensorflow/lite/python/convert.py", line 491, in toco_convert_impl
    data = toco_convert_protos(
  File "/home/mn/miniconda3/envs/tf/lib/python3.8/site-packages/tensorflow/lite/python/convert.py", line 227, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
2020-09-30 17:26:46.253082: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:144] Ignored output_format.
2020-09-30 17:26:46.253096: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:147] Ignored drop_control_dependency.
2020-09-30 17:26:46.257083: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-09-30 17:26:46.279406: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 3999980000 Hz
2020-09-30 17:26:46.279736: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x560c77ff6240 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-30 17:26:46.279747: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-30 17:26:46.280153: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-09-30 17:26:46.282831: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-30 17:26:46.282979: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.65GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2020-09-30 17:26:46.283066: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-09-30 17:26:46.283843: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-09-30 17:26:46.284635: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-09-30 17:26:46.284757: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-09-30 17:26:46.285563: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-09-30 17:26:46.286029: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-09-30 17:26:46.287805: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-09-30 17:26:46.287859: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-30 17:26:46.288029: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-30 17:26:46.288155: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-09-30 17:26:46.288174: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-09-30 17:26:46.323961: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-30 17:26:46.323977: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-09-30 17:26:46.323981: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-09-30 17:26:46.324065: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-30 17:26:46.324234: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-30 17:26:46.324384: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-30 17:26:46.324525: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 105 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
2020-09-30 17:26:46.325513: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x560c78d5dc30 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-09-30 17:26:46.325522: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
Fatal Python error: Segmentation fault

Current thread 0x00007f70cdd84740 (most recent call first):
  File "/home/m/miniconda3/envs/tf/lib/python3.8/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 50 in execute
  File "/home/m/miniconda3/envs/tf/lib/python3.8/site-packages/absl/app.py", line 251 in _run_main
  File "/home/m/miniconda3/envs/tf/lib/python3.8/site-packages/absl/app.py", line 300 in run
  File "/home/m/miniconda3/envs/tf/lib/python3.8/site-packages/tensorflow/python/platform/app.py", line 40 in run
  File "/home/m/miniconda3/envs/tf/lib/python3.8/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 93 in main
  File "/home/m/miniconda3/envs/tf/bin/toco_from_protos", line 11 in <module>
Segmentation fault (core dumped)




Process finished with exit code 1

```

**Also, please include a link to the saved model or GraphDef**

```
# Put link here or attach to the issue.
```

**Failure details**
Expect the tflite converter to work on channel-first models 

**RNN conversion support**
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

**Any other info / logs**
Same two layer test model successfully converts when set up as _channel last_ 
Removing the batchnorm layer succesfully converts with _channel first_.
However, even just a lone conv2d layer fails with _channel first_ if I do not include the extra 'converter.' parameters

**Comment by jvishnuvardhan** [comment]
@PoseAI When I used `tf-nightly`, I was not able to reproduce the issue. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/59797706487551888b539cc0519816a6/untitled51.ipynb).

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by PoseAI** [comment]
hi, i confirm current tf-nightly resolves the issue.  hopefully conda upgrades soon as i try to avoid nightly builds.
thanks
