### ISSUE TITLE
XLA Compilation does not work with Embeddings Layer

### ISSUE THREAD

**Issue by n2cholas** [tensorflow/tensorflow#43687]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): Default on colab
- TensorFlow version (use command below): 2.3.0
- Python version: 3.6.9
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: 10.1
- GPU model and memory: Tesla P4 (8gb)

**Describe the current behavior**
I'm using a simple model with Embeddings which works with normal `tf.function` but does not work with `tf.function(experimental_compile=True)`. I suspect it is because Embeddings are kept on the CPU while the other model layers are on the GPU, however, moving the tensors explicitly to the right device did not help (as demonstrated in the script).

**Describe the expected behavior**
The function should run without errors just like with a normal `tf.function`.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

https://colab.research.google.com/drive/1dDjBiks335If3zqBleL_CPrNZ8CIanPP?usp=sharing

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@n2cholas 

I have tried in TF-nightly version (2.4.0-dev20200930) and i am not seeing any issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/8dc30c27c6cc9afe663c07be997868e8/untitled406.ipynb#scrollTo=l0HX6JYYzAVW). Thanks!

**Comment by n2cholas** [comment]
@ravikyram Thanks! I was able to get it running on colab, but I still get the error on my local machine even with tf-nightly. Here are the specifications:

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): pip (so binary)
- TensorFlow version (use command below): 2.4.0-dev20200930
- Python version: 3.8.5
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: 11.0
- GPU model and memory: Titan RTX (24gb)

**Comment by ravikyram** [comment]
@n2cholas 

Can you please share the error log.Thanks!

**Comment by n2cholas** [comment]
@ravikyram here's all the output from running it:

```
2020-10-05 13:56:02.579136: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
2020-10-05 13:56:07.217818: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-10-05 13:56:07.218509: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-10-05 13:56:07.284812: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:17:00.0 name: TITAN V computeCapability: 7.0
coreClock: 1.455GHz coreCount: 80 deviceMemorySize: 11.78GiB deviceMemoryBandwidth: 607.97GiB/s
2020-10-05 13:56:07.284838: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
2020-10-05 13:56:07.286588: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.11
2020-10-05 13:56:07.287851: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-10-05 13:56:07.288096: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-10-05 13:56:07.289287: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-10-05 13:56:07.289664: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.11
2020-10-05 13:56:07.289776: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.8
2020-10-05 13:56:07.290790: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2020-10-05 13:56:07.291078: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-10-05 13:56:07.291830: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-10-05 13:56:07.293287: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:17:00.0 name: TITAN V computeCapability: 7.0
coreClock: 1.455GHz coreCount: 80 deviceMemorySize: 11.78GiB deviceMemoryBandwidth: 607.97GiB/s
2020-10-05 13:56:07.293321: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
2020-10-05 13:56:07.293346: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.11
2020-10-05 13:56:07.293363: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-10-05 13:56:07.293378: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-10-05 13:56:07.293399: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-10-05 13:56:07.293416: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.11
2020-10-05 13:56:07.293434: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.8
2020-10-05 13:56:07.299268: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2020-10-05 13:56:07.299335: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
2020-10-05 13:56:07.749866: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-05 13:56:07.749896: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 
2020-10-05 13:56:07.749901: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N 
2020-10-05 13:56:07.751331: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10910 MB memory) -> physical GPU (device: 0, name: TITAN V, pci bus id: 0000:17:00.0, compute capability: 7.0)
WARNING:tensorflow:Layer lstm will not use cuDNN kernel since it doesn't meet the cuDNN kernel criteria. It will use generic GPU kernel as fallback when running on GPU
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernel since it doesn't meet the cuDNN kernel criteria. It will use generic GPU kernel as fallback when running on GPU
WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernel since it doesn't meet the cuDNN kernel criteria. It will use generic GPU kernel as fallback when running on GPU
2020-10-05 13:56:11.378588: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1be075d0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-10-05 13:56:11.378619: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): TITAN V, Compute Capability 7.0
2020-10-05 13:56:11.927927: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.11
2020-10-05 13:56:20.457126: I tensorflow/compiler/jit/xla_compilation_cache.cc:325] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
2020-10-05 13:56:21.618453: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at xla_ops.cc:231 : Invalid argument: Trying to access resource _AnonymousVar10 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
/job:localhost/replica:0/task:0/device:CPU:0
/job:localhost/replica:0/task:0/device:GPU:0
/job:localhost/replica:0/task:0/device:CPU:0
Traceback (most recent call last):
  File "main.py", line 83, in <module>
    forward(train_data[:batch_size], train_labels[:batch_size])
  File "/local/nvadivelu/jax-paper/tmp/env/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 795, in __call__
    result = self._call(*args, **kwds)
  File "/local/nvadivelu/jax-paper/tmp/env/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 822, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/local/nvadivelu/jax-paper/tmp/env/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2947, in __call__
    return graph_function._call_flat(
  File "/local/nvadivelu/jax-paper/tmp/env/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1927, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/local/nvadivelu/jax-paper/tmp/env/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 556, in call
    outputs = execute.execute(
  File "/local/nvadivelu/jax-paper/tmp/env/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Trying to access resource _AnonymousVar10 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0 [Op:__inference_forward_16492]
```

Here is the output of `pip freeze`:
```
absl-py==0.10.0
astunparse==1.6.3
cachetools==4.1.1
certifi==2020.6.20
chardet==3.0.4
flatbuffers==1.12
gast==0.3.3
google-auth==1.22.1
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
grpcio==1.32.0
h5py==2.10.0
idna==2.10
Keras==2.4.3
Keras-Preprocessing==1.1.2
Markdown==3.2.2
numpy==1.18.5
oauthlib==3.1.0
opt-einsum==3.3.0
protobuf==3.13.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
PyYAML==5.3.1
requests==2.24.0
requests-oauthlib==1.3.0
rsa==4.6
scipy==1.5.2
six==1.15.0
tb-nightly==2.4.0a20201005
tensorboard-plugin-wit==1.7.0
termcolor==1.1.0
tf-estimator-nightly==2.4.0.dev2020100501
tf-nightly-gpu==2.4.0.dev20201005
typing-extensions==3.7.4.3
urllib3==1.25.10
Werkzeug==1.0.1
wrapt==1.12.1
```

**Comment by Saduf2019** [comment]
@n2cholas 
 It looks like you are using an older Version of Tensorflow . Many bugs have been fixed in the latest version. Could you please execute your code using Latest Version 2.5 and let us know if the issue still persists? Thanks!

**Comment by n2cholas** [comment]
@Saduf2019 the issue still persists with 2.5.0. With 2.6.0, the code works there is a different issue.  Consider the following snippet (directly from the colab):

```py
def to_cpu(x):
    with tf.device('/CPU:0'): return tf.identity(x)
 
def to_gpu(x):
    with tf.device('/GPU:0'): return tf.identity(x)
 
x = tf.convert_to_tensor([1, 2, 3])
print(x.device)
print(to_gpu(x).device)
print(to_cpu(to_gpu(x)).device)
```
This prints the following in 2.5.0 (which is correct):
```
/job:localhost/replica:0/task:0/device:CPU:0
/job:localhost/replica:0/task:0/device:GPU:0
/job:localhost/replica:0/task:0/device:CPU:0
```
But in 2.6.0, it prints:
```
/job:localhost/replica:0/task:0/device:CPU:0
/job:localhost/replica:0/task:0/device:CPU:0
/job:localhost/replica:0/task:0/device:CPU:0
```
The second line should be `GPU`. Why is this happening? is this a bug?

**Comment by serach24** [comment]
I met the same problem, did you know how to solve it now?

**Comment by tilakrayal** [comment]
@n2cholas,
I tried to execute the mentioned code on tensorflow v2.14(GPU) and it was executed without any issue/error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/7648d5367871176936b8f7b5d04e9a5c/xla_embedding_issue.ipynb). 

Also the code was providing the output as GPU which you are mentioning the above. Kindly find the screenshot for the reference.

![image](https://github.com/tensorflow/tensorflow/assets/81610181/025fef9b-a29c-4549-9f08-a0bcfd47835c)


Thank you!
