### ISSUE TITLE
TFBertMainLayer cannot be loaded from .h5

### ISSUE THREAD

**Issue by redrussianarmy** [tensorflow/tensorflow#43721]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.4 LTS
- TensorFlow version (use command below): 2.3.0
- Python version: 3.6.9
- CUDA/cuDNN version: 10.1 / 7.6.5
- GPU model and memory: GeForce RTX 2080ti 

**The Issue**
When I try to load the model according to the [documentation](https://www.tensorflow.org/tutorials/keras/save_and_load), I face with following issue:

Running code:
```python
new_model.model = tf.keras.models.load_model(os.path.join(load_folder_path, trans_model_name))
```

Error:
```python
ValueError: Unknown layer: Custom>TFBertMainLayer
```

Traceback (most recent call last):
```python
  File "bert_nlu_basic_api.py", line 105, in <module>
    initialize()
  File "bert_nlu_basic_api.py", line 46, in initialize
    model = JointTransBertModel.load(load_folder_path)
  File "/home/hakan/Documents/HB/dialog-nlu/models/joint_trans_bert.py", line 42, in load
    return BaseJointTransformerModel.load_model_by_class(BaseJointTransformerModel, load_folder_path, 'joint_bert_model.h5')
  File "/home/hakan/Documents/HB/dialog-nlu/models/base_joint_trans.py", line 121, in load_model_by_class
    new_model.model = tf.keras.models.load_model(os.path.join(load_folder_path, trans_model_name))
  File "/home/hakan/.local/share/virtualenvs/dialog-nlu-TCo_F89F/lib/python3.6/site-packages/tensorflow/python/keras/saving/save.py", line 182, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/hakan/.local/share/virtualenvs/dialog-nlu-TCo_F89F/lib/python3.6/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 178, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "/home/hakan/.local/share/virtualenvs/dialog-nlu-TCo_F89F/lib/python3.6/site-packages/tensorflow/python/keras/saving/model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/hakan/.local/share/virtualenvs/dialog-nlu-TCo_F89F/lib/python3.6/site-packages/tensorflow/python/keras/layers/serialization.py", line 175, in deserialize
    printable_module_name='layer')
  File "/home/hakan/.local/share/virtualenvs/dialog-nlu-TCo_F89F/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 358, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/hakan/.local/share/virtualenvs/dialog-nlu-TCo_F89F/lib/python3.6/site-packages/tensorflow/python/keras/engine/functional.py", line 617, in from_config
    config, custom_objects)
  File "/home/hakan/.local/share/virtualenvs/dialog-nlu-TCo_F89F/lib/python3.6/site-packages/tensorflow/python/keras/engine/functional.py", line 1204, in reconstruct_from_config
    process_layer(layer_data)
  File "/home/hakan/.local/share/virtualenvs/dialog-nlu-TCo_F89F/lib/python3.6/site-packages/tensorflow/python/keras/engine/functional.py", line 1186, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "/home/hakan/.local/share/virtualenvs/dialog-nlu-TCo_F89F/lib/python3.6/site-packages/tensorflow/python/keras/layers/serialization.py", line 175, in deserialize
    printable_module_name='layer')
  File "/home/hakan/.local/share/virtualenvs/dialog-nlu-TCo_F89F/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 347, in deserialize_keras_object
    config, module_objects, custom_objects, printable_module_name)
  File "/home/hakan/.local/share/virtualenvs/dialog-nlu-TCo_F89F/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 296, in class_and_config_for_serialized_keras_object
    raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
ValueError: Unknown layer: Custom>TFBertMainLayer
```

**Comment by jvishnuvardhan** [comment]
@redrussianarmy Looks like you have a custom layer in your model. When you save a model (that has a custom layer) in `h5` format, then you need to use `custom_objects` when loading the model as described [here](https://www.tensorflow.org/tutorials/keras/save_and_load#saving_custom_objects). 

For example
`new_model = keras.models.load_model('model.h5',custom_objects={'CustomMetric':CustomMetric()})`

**Comment by redrussianarmy** [comment]
Thank you. I will try.

**Comment by rbrtjwrk** [comment]
@redrussianarmy was it possible for you to load the .h5 model with a custom layer (the way @jvishnuvardhan suggested) even if you didn't use get_config() method while saving it?

**Comment by wojiaodawei** [comment]
Hey @redrussianarmy could you explain how you handled this please? 
cc @rbrtjwrk did you manage to load the .h5 model with a custom layer?

**Comment by rocchdi** [comment]
In my case I'm working with a bert model, using tf.keras.models library and the saving , loading is performed as followed : 

saving the model :  tf.keras.models.save_model(model, 'bert_model.h5')

loading the model :  loaded_model = tf.keras.models.load_model('bert_model.h5',custom_objects={'TFBertModel':TFBertModel})

Actually, my model  uses a bert model  based on a pretrained  TFBertModel  :
**bert_model = TFBertModel.from_pretrained('bert-base-uncased')**
 
my_model = create_model(bert_model, MAX_LEN)   

here is an extract of the create_model method that creates my_model :

def create_model(bert_model, max_len=MAX_LEN):
    #params
    input_ids = tf.keras.Input(shape=(max_len,),dtype='int32')
    attention_masks = tf.keras.Input(shape=(max_len,),dtype='int32')  
    embeddings = **bert_model**([input_ids,attention_masks])[1]
    output = tf.keras.layers.Dense(2, activation="softmax")(embeddings)
    model = tf.keras.models.Model(inputs = [input_ids,attention_masks], outputs = output)
    model.compile(opt, loss=loss, metrics=accuracy)
    return model

as has said before by @redrussianarmy When you save a model (that has a custom layer) in h5 format, then you need to use custom_objects when loading the model :
loaded_model = tf.keras.models.load_model('bert_model.h5',**custom_objects={'TFBertModel':TFBertModel}**)

hope this helps.

**Comment by rbrtjwrk** [comment]
Hi, @rocchdi, thanks for your answer!
I also managed to load .h5 model using only tf.keras.lmodels.load_model(...) without any additional arguments. 
Importing TFBertModel, BertConfig, and TFBertMainLayer from transformers helped.
