### ISSUE TITLE
creating tf.data.Dataset object from generator gives error for incorrect file name

### ISSUE THREAD

**Issue by AkshayRoyal** [tensorflow/tensorflow#43757]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **No**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Windows 10 **
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): **conda**
- TensorFlow version (use command below): **2.3.0**
- Python version: **3.8 and 3.6**
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: **10.1.243/7.6.5**
- GPU model and memory: **Nvidia RTX2070 8 GB**

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
On trying to consume batches from the dataset `ds` I get InvalidArgumentError
**Describe the expected behavior**

**Standalone code to reproduce the issue**
[official tfdata colab](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/guide/data.ipynb)
In the above file. Go to Consuming Python Generators section and in the code cell
```
ds = tf.data.Dataset.from_generator(
    img_gen.flow_from_directory, args=[flowers], 
    output_types=(tf.float32, tf.float32), 
    output_shapes=([32,256,256,3], [32,5])
)

ds
```
add `next(iter(ds))` to consume a batch of `ds`
**Other info / logs** 
```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/context.py in execution_mode(mode)
   2101       ctx.executor = executor_new
-> 2102       yield
   2103     finally:

10 frames
InvalidArgumentError: TypeError: endswith first arg must be bytes or a tuple of bytes, not str
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 711, in get_iterator
    return self._iterators[iterator_id]

KeyError: 1


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py", line 244, in __call__
    ret = func(*args)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 302, in wrapper
    return func(*args, **kwargs)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 827, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 713, in get_iterator
    iterator = iter(self._generator(*self._args.pop(iterator_id)))

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/preprocessing/image.py", line 959, in flow_from_directory
    interpolation=interpolation)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/preprocessing/image.py", line 397, in __init__
    **kwargs)

  File "/usr/local/lib/python3.6/dist-packages/keras_preprocessing/image/directory_iterator.py", line 135, in __init__
    classes, filenames = res.get()

  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value

  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))

  File "/usr/local/lib/python3.6/dist-packages/keras_preprocessing/image/utils.py", line 221, in _list_valid_filenames_in_directory
    for root, fname in valid_files:

  File "/usr/local/lib/python3.6/dist-packages/keras_preprocessing/image/utils.py", line 178, in _iter_valid_files
    if fname.lower().endswith('.tiff'):

TypeError: endswith first arg must be bytes or a tuple of bytes, not str


	 [[{{node PyFunc}}]] [Op:IteratorGetNext]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/executor.py in wait(self)
     65   def wait(self):
     66     """Waits for ops dispatched in this executor to finish."""
---> 67     pywrap_tfe.TFE_ExecutorWaitForAllPendingNodes(self._handle)
     68 
     69   def clear_error(self):

InvalidArgumentError: TypeError: endswith first arg must be bytes or a tuple of bytes, not str
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 711, in get_iterator
    return self._iterators[iterator_id]

KeyError: 1


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py", line 244, in __call__
    ret = func(*args)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 302, in wrapper
    return func(*args, **kwargs)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 827, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 713, in get_iterator
    iterator = iter(self._generator(*self._args.pop(iterator_id)))

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/preprocessing/image.py", line 959, in flow_from_directory
    interpolation=interpolation)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/preprocessing/image.py", line 397, in __init__
    **kwargs)

  File "/usr/local/lib/python3.6/dist-packages/keras_preprocessing/image/directory_iterator.py", line 135, in __init__
    classes, filenames = res.get()

  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value

  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))

  File "/usr/local/lib/python3.6/dist-packages/keras_preprocessing/image/utils.py", line 221, in _list_valid_filenames_in_directory
    for root, fname in valid_files:

  File "/usr/local/lib/python3.6/dist-packages/keras_preprocessing/image/utils.py", line 178, in _iter_valid_files
    if fname.lower().endswith('.tiff'):

TypeError: endswith first arg must be bytes or a tuple of bytes, not str


	 [[{{node PyFunc}}]]
```

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/e111c8e4edca3eadedea8e791a45615a/43757.ipynb). Thanks!

**Comment by bhack** [comment]
@AkshayRoyal can you give a run with
```
ds = tf.data.Dataset.from_generator(
    lambda: img_gen.flow_from_directory(flowers),
    output_types=(tf.float32, tf.float32), 
    output_shapes=([32,256,256,3], [32,5])
)
```

**Comment by AkshayRoyal** [comment]
@bhack . Thanks for answering. Please fix the issue with the example too as it does not work the way it was expected and it should be removed from example as it is misleading

What worked?
```
ds = tf.data.Dataset.from_generator(
    lambda: img_gen.flow_from_directory(flowers),
    output_types=(tf.float32, tf.float32), 
    output_shapes=([32,256,256,3], [32,5])
)
```
AND

```
from funtools import partial
ds = tf.data.Dataset.from_generator(
    partial(img_gen.flow_from_directory,flowers),
    output_types=(tf.float32, tf.float32), 
    output_shapes=([32,256,256,3], [32,5])
)
```

**Comment by MarkDaoust** [comment]
Fix incoming.

Thanks @AkshayRoyal.
Thanks @bhack.
