### ISSUE TITLE
Import issue with tensor flow Windows 10 python 3.7

### ISSUE THREAD

**Issue by andrejmz** [tensorflow/tensorflow#43750]
Hi 

I am trying to make this tutorial work : https://github.com/ildoonet/tf-pose-estimation/blob/master/.
I am having an error in file tf-pose-estimation-master\tf_pose\estimator.py",
The import """import tensorflow.contrib.tensorrt as trt""" was causing an error, after having read about this issue, using 
from tensorflow.python.compiler.tensorrt import trt didnt fix it either, what must i do ?

Best regards

**Comment by jvishnuvardhan** [comment]
@andrejmz The link you provided is not working. I ran your code mentioned above wiithout any issue. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/45899b5ba07198f475b3ac04c85fe770/untitled.ipynb). Thanks!

**Comment by andrejmz** [comment]
Hi 

Here is the link: https://github.com/ildoonet/tf-pose-estimation
I've just uninstalled tensorflow, than installed tensorflow-1.15.3 as you recommended.
I still have the error:

  File "run_webcam_picture.py", line 8, in <module>
    from tf_pose.estimator import TfPoseEstimator
  File "C:\Users\mz\Downloads\tf-pose-estimation-master\tf_pose\__init__.py", line 5, in <module>
    from tf_pose.runner import infer, Estimator, get_estimator
  File "C:\Users\mz\Downloads\tf-pose-estimation-master\tf_pose\runner.py", line 8, in <module>
    from tf_pose import eval
  File "C:\Users\mz\Downloads\tf-pose-estimation-master\tf_pose\eval.py", line 13, in <module>
    from tf_pose.estimator import TfPoseEstimator
  File "C:\Users\mz\Downloads\tf-pose-estimation-master\tf_pose\estimator.py", line 14, in <module>
    import tensorflow.contrib.tensorrt as trt
ModuleNotFoundError: No module named 'tensorflow.contrib.tensorrt'

But I have read about pip silently not removing the files correctly or caching stuff or something like that.

Best regards

**Comment by ashwin-phadke** [comment]
@andrejmz  I would suggest you to use https://github.com/gsethi2409/tf-pose-estimation this version with the latest tensorflow version.

**Comment by andrejmz** [comment]
So

I have downloaded files from this link https://github.com/gsethi2409/tf-pose-estimation
Than cd into the appropriate directory than pip install -r requirements.txt
than python run_webcam_picture.py
and i have errors:

C:\Users\mz\Downloads\tf-pose-estimation-master (3)\tf-pose-estimation-master>python run_webcam.py
2020-10-03 23:58:13.307125: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-10-03 23:58:13.309845: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "run_webcam.py", line 8, in <module>
    from tf_pose.estimator import TfPoseEstimator
  File "C:\Users\mz\Downloads\tf-pose-estimation-master (3)\tf-pose-estimation-master\tf_pose\__init__.py", line 5, in <module>
    from tf_pose.runner import infer, Estimator, get_estimator
  File "C:\Users\mz\Downloads\tf-pose-estimation-master (3)\tf-pose-estimation-master\tf_pose\runner.py", line 8, in <module>
    from tf_pose import eval
  File "C:\Users\mz\Downloads\tf-pose-estimation-master (3)\tf-pose-estimation-master\tf_pose\eval.py", line 13, in <module>
    from tf_pose.estimator import TfPoseEstimator
  File "C:\Users\mz\Downloads\tf-pose-estimation-master (3)\tf-pose-estimation-master\tf_pose\estimator.py", line 14, in <module>
    from tensorflow.python.compiler.tensorrt import trt_convert as trt
ImportError: cannot import name 'trt_convert' from 'tensorflow.python.compiler.tensorrt' (C:\Users\mz\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\compiler\tensorrt\__init__.py)

What did i do wrong ?

Best regards

**Comment by ashwin-phadke** [comment]
Did you try going through numerous such cases already on stackoverflow and issue tab here , I guess https://github.com/tensorflow/tensorflow/issues/23692 is something that can help you maybe this too https://forums.developer.nvidia.com/t/importerror-cannot-import-name-tensorrt-from-tensorflow-python-compiler/80633/2. You need to look into searching for your errors. As i am using Linux I cannot trace your error here, It works fine for me in Linux, also did you compile the c++ library for post processing as mentioned here https://github.com/ildoonet/tf-pose-estimation/tree/master/tf_pose/pafprocess .

**Comment by jvishnuvardhan** [comment]
@andrejmz Please follow the guidance from @ashwin-phadke and also follow the instructions at https://github.com/ildoonet/tf-pose-estimation.

I am closing this issue as this is not related to a bug or performance related to tensorflow. Please feel free to let me know if I am mistaken. Please post it in Stackoverflow where there is a large community to support this kind of questions. Thanks!
