### ISSUE TITLE
tensorflow is not running on my miniconda

### ISSUE THREAD

**Issue by Mova-2020** [tensorflow/tensorflow#43769]
I have installed tensorflow using pip install, but it does not run.

When trying to run it, I receive the following error message:

(base) PS C:\WINDOWS\system32> python
Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)] :: Ana
conda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow_core\python\pywra
p_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow_core\python\pywra
p_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow_core\python\pywra
p_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\ProgramData\Miniconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\ProgramData\Miniconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routin
e failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\__init__.py", lin
e 98, in <module>
    from tensorflow_core import *
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow_core\__init__.py"
, line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\__init__.py", lin
e 50, in __getattr__
    module = self._load()
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\__init__.py", lin
e 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\ProgramData\Miniconda3\lib\importlib\__init__.py", line 127, in impor
t_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow_core\python\__ini
t__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow_core\python\pywra
p_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow_core\python\pywra
p_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow_core\python\pywra
p_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow_core\python\pywra
p_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\ProgramData\Miniconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\ProgramData\Miniconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routin
e failed.

Failed to load the native TensorFlow runtime.

Please help to fix it.

**Comment by Mova-2020** [comment]
Thank you, tensorflow-butler.
