### ISSUE TITLE
LookupError: gradient registry has no entry for: TensorScatterMax

### ISSUE THREAD

**Issue by anshkumar** [tensorflow/tensorflow#43765]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.4 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.0
- Python version: 3.6.9
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: 10.1
- GPU model and memory: Tesla P100-PCIE, 16280MiB

**Describe the current behavior**

I'm making YOLACT and while creating semantic_segmentation_loss function, I've used `tensor_scatter_nd_max` function which was introduced in tf 2.3. The function is as follows:

```
def _loss_semantic_segmentation(pred_seg, mask_gt, classes):
    batch_size, mask_h, mask_w, num_classes = tf.shape(pred_seg)
    loss_s = 0

    for i in range(batch_size):
        cur_segment = pred_seg[i]
        cur_class_gt = classes[i]
        masks = mask_gt[i]

        masks = tf.expand_dims(masks, axis=-1)
        masks = tf.image.resize(masks, [mask_h, mask_w], method=tf.image.ResizeMethod.BILINEAR)
        masks = tf.cast(masks + 0.5, tf.int64)
        masks = tf.squeeze(tf.cast(masks, tf.float32))

        segment_gt = tf.zeros_like(cur_segment) # [height, width, num_cls]
        segment_gt = tf.transpose(segment_gt, perm=(2, 0, 1))

        obj_cls = tf.expand_dims(cur_class_gt, axis=-1)
        segment_gt = tf.tensor_scatter_nd_max(segment_gt, indices=obj_cls, updates=masks)
        segment_gt = tf.transpose(segment_gt, perm=(1, 2, 0))

        loss_s += tf.reduce_sum(tf.nn.sigmoid_cross_entropy_with_logits(segment_gt, cur_segment))

    return loss_s / mask_h / mask_w
```

But it throws me following error:
```
Traceback (most recent call last):
  File "train.py", line 300, in <module>
    app.run(main)
  File "/home/deploy/.local/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/deploy/.local/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "train.py", line 208, in main
    labels)
  File "/home/deploy/.local/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 761, in __call__
    return self._python_function(*args, **kwds)
  File "train.py", line 54, in train_step
    grads = tape.gradient(total_loss, model.trainable_variables)
  File "/home/deploy/.local/lib/python3.6/site-packages/tensorflow/python/eager/backprop.py", line 1073, in gradient
    unconnected_gradients=unconnected_gradients)
  File "/home/deploy/.local/lib/python3.6/site-packages/tensorflow/python/eager/imperative_grad.py", line 77, in imperative_grad
    compat.as_str(unconnected_gradients.value))
  File "/home/deploy/.local/lib/python3.6/site-packages/tensorflow/python/eager/backprop.py", line 151, in _gradient_function
    grad_fn = ops._gradient_registry.lookup(op_name)  # pylint: disable=protected-access
  File "/home/deploy/.local/lib/python3.6/site-packages/tensorflow/python/framework/registry.py", line 97, in lookup
    "%s registry has no entry for: %s" % (self._name, name))
LookupError: gradient registry has no entry for: TensorScatterMax

```

**Describe the expected behavior**
No error should come

**Standalone code to reproduce the issue**
The link to my repository is [this](https://github.com/anshkumar/yolact). 
To run:

> python3 train.py -tfrecord_dir '/home/deploy/ved/data' -weights '/home/deploy/ved/ckpt'  -train_iter '100000'  -batch_size '2' 

If you need tfrecord let me know.

**Comment by Saduf2019** [comment]
@anshkumar 
Please provide with simple stand alone code such that we can replicate the issue faced or if possible share a colab gist with the error reported.
