### ISSUE TITLE
Google Cloud Storage cannot be used in tf.keras.callbacks.experimental.BackupAndRestore as a back-up dir

### ISSUE THREAD

**Issue by kalosisz** [tensorflow/tensorflow#43789]
**System information**
- Run in official container: tensorflow/tensorflow:2.3.1
- Host OS:  Debian GNU/Linux 10 (Cloud shell)

**Describe the current behavior**
On successful training, the checkpoints produced by `tf.keras.callbacks.experimental.BackupAndRestore` should be removed. However, if one provided a Cloud Storage location, the cleanup fails. This is not the case for specifying a local backup location.

**Describe the expected behavior**
`tf.keras.callbacks.experimental.BackupAndRestore` should be able to remove the checkpoint upon successful training. 

**Standalone code to reproduce the issue**
[Colab Notebook](https://colab.research.google.com/drive/1XocuDL8I8tivEa-DCgH6iWBcpV5WiJRJ?usp=sharing)
*Please change the Cloud Storage location to a bucket owned by you.*

**Other info / logs**
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/trainig/trainer/task.py", line 69, in <module>
    main(args)
  File "/trainig/trainer/task.py", line 41, in main
    callbacks=callbacks
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 1145, in fit
    callbacks.on_train_end(logs=training_logs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/callbacks.py", line 514, in on_train_end
    callback.on_train_end(logs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/callbacks.py", line 1547, in on_train_end
    self._training_state.delete_backup()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/distribute/worker_training_state.py", line 124, in delete_backup
    file_io.delete_recursively(pathname)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py", line 586, in delete_recursively
    delete_recursively_v2(dirname)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py", line 599, in delete_recursively_v2
    _pywrap_file_io.DeleteRecursively(compat.as_bytes(path))
tensorflow.python.framework.errors_impl.NotFoundError: gs://[bucket]/training/backup/ckpt-2.data-00000-of-00001 doesn't exist or not a directory.
```

**Comment by kalosisz** [comment]
I have also looked in the codebase and believe the culprit is that even though `file_io.delete_recursively_v2` is used, it is used for all the files found the the looked up directories, [code snippet](https://github.com/tensorflow/tensorflow/blob/ac4e209f8cd33aab482d5414b38043e03fc72ef5/tensorflow/python/keras/distribute/worker_training_state.py#L115-L120). `file_io.delete_recursively_v2`, however, can remove the content recursively. This recursive call is not compatible with Cloud Storage when calling on files and not directories.

The preceding checkpoints are deleted on epoch ends and that is implemented using `file_io.delete_file`. This works well with Cloud Storage. 

A possible solution is to not to call `file_io.delete_recursively_v2` on looked up files, but on the directories itself. For instance,
```python
file_io.delete_recursively_v2(self.write_checkpoint_manager._prefix)
file_io.delete_recursively_v2(
  os.path.join(self.write_checkpoint_manager.directory, 'checkpoint'))
```

**Comment by saikumarchalla** [comment]
@kalosisz Closing the issue since the necessary changes are implemented.Please feel free to re-open the issue if you have any concern.Thanks!

**Comment by kalosisz** [comment]
@saikumarchalla Thank you for the fix!
