### ISSUE TITLE
Converting a LSTM model from Pytorch to Tensorflow using ONNX

### ISSUE THREAD

**Issue by Nitya05** [tensorflow/tensorflow#43808]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.0
- Python version: 3.6.9
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: 10.1
- GPU model and memory:

**Describe the current behavior**
I am trying to convert a very simple LSTM model from Pytorch to Tensorflow using ONNX. The model conversion from Pytorch to ONNX is happening, but I am unable to convert that ONNX model to Tensorflow.

**Describe the expected behavior**
Successfully convert LSTM from .onnx to .pb.

**Standalone code to reproduce the issue**
import onnx
from onnx_tf.backend import prepare

onnx_model = onnx.load("./SimpleLSTM.onnx")
tf_rep = prepare(onnx_model)
tf_rep.export_graph('./SimpleLSTM.pb')

**Other info / logs** 
Traceback (most recent call last):
  File "testLSTM.py", line 14, in <module>
    tf_rep.export_graph('./SimpleLSTM.pb')
  File "/workspace/ctg_nitya/onnx-tensorflow/onnx_tf/backend_rep.py", line 93, in export_graph
    tf.saved_model.save(self.tf_module, path, signatures=self.tf_module.__call__.get_concrete_function(**self.signatures))
  File "/workspace/ctg_nitya/python3_venv_tf_2.3_gpu/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 1167, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/workspace/ctg_nitya/python3_venv_tf_2.3_gpu/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 1074, in _get_concrete_function_garbage_collected
    self._initialize_uninitialized_variables(initializers)
  File "/workspace/ctg_nitya/python3_venv_tf_2.3_gpu/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 965, in _initialize_uninitialized_variables
    return initialize_variables.get_concrete_function()()
  File "/workspace/ctg_nitya/python3_venv_tf_2.3_gpu/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2939, in get_concrete_function
    *args, **kwargs)
  File "/workspace/ctg_nitya/python3_venv_tf_2.3_gpu/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2906, in _get_concrete_function_garbage_collected
    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
  File "/workspace/ctg_nitya/python3_venv_tf_2.3_gpu/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/workspace/ctg_nitya/python3_venv_tf_2.3_gpu/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3075, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/workspace/ctg_nitya/python3_venv_tf_2.3_gpu/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/workspace/ctg_nitya/python3_venv_tf_2.3_gpu/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 957, in initialize_variables
    inits, ops.get_default_graph(), op_map=op_map)
  File "/workspace/ctg_nitya/python3_venv_tf_2.3_gpu/lib/python3.6/site-packages/tensorflow/python/eager/lift_to_graph.py", line 260, in lift_to_graph
    add_sources=add_sources))
  File "/workspace/ctg_nitya/python3_venv_tf_2.3_gpu/lib/python3.6/site-packages/tensorflow/python/ops/op_selector.py", line 413, in map_subgraph
    % (repr(init_tensor), repr(op), _path_from(op, init_tensor, sources)))
**tensorflow.python.ops.op_selector.UnliftableError: Unable to lift tensor <tf.Tensor 'concat_2:0' shape=(6, 12) dtype=float32> because it depends transitively on placeholder <tf.Operation 'Squeeze_1/60' type=Placeholder> via at least one path, e.g.: concat_2 (ConcatV2) <- transpose_1 (Transpose) <- concat_1 (ConcatV2) <- split_1 (Split) <- Squeeze_1 (Squeeze) <- Squeeze_1/60 (Placeholder)**

**Comment by Saduf2019** [comment]
@Nitya05 
please share stand alone code to replicate the issue.

**Comment by Nitya05** [comment]
Following is the Pytorch code for creating an ONNX model for a LSTM:

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

import torch.onnx
import torchvision

torch.manual_seed(1)

lstm = nn.LSTM(3, 3, num_layers=1)
lstm.eval()

with torch.no_grad():
inputs = [torch.randn(1,3) for _ in range(5)] #make a sequence of length 5
inputs = torch.cat(inputs).view(len(inputs), 1, -1)
h0 = torch.randn(1, 1, 3)
c0 = torch.randn(1, 1, 3)
out, (hn, cn) = lstm(inputs, (h0, c0))

input_names = [“input”, “h0”, “c0”]
output_names = [“output”, “hn”, “cn”]

torch.onnx.export(lstm, (inputs, (h0, c0)), “SimpleLSTM.onnx”, input_names=input_names, output_names=output_names)


And, I am using the below code for converting the obtained ONNX model to Tensorflow:

import onnx
from onnx_tf.backend import prepare

onnx_model = onnx.load("./SimpleLSTM.onnx")
tf_rep = prepare(onnx_model)
tf_rep.export_graph('./SimpleLSTM.pb')

**Comment by jvishnuvardhan** [comment]
@Nitya05 I am not an expert in pytorch. Can you please share a standalone code in google colab or jupyter notebook that can be run. I tried your code in google colab. Please check [gist here](https://colab.research.google.com/gist/jvishnuvardhan/3a79da9f92ccc137c873cfa564bc8c94/untitled.ipynb). Thanks!

**Comment by Nitya05** [comment]
Hi @jvishnuvardhan 
I have made required installations in [here](https://colab.research.google.com/gist/jvishnuvardhan/3a79da9f92ccc137c873cfa564bc8c94/untitled.ipynb#scrollTo=83AWhRhpgK40). But, I am getting a different tensorflow error now :

AttributeError: module 'tensorflow' has no attribute 'ceil'

**Comment by khandeas** [comment]
Hi..

 Just came across this issue - I am facing the same problem trying to convert a LSTM model in ONNX format to Tensor flow.  To make sure, I also tried on the example provided in the issue and can confirm I get the same error.

**Comment by dhruvsakalley** [comment]
> @Nitya05 I am not an expert in pytorch. Can you please share a standalone code in google colab or jupyter notebook that can be run. I tried your code in google colab. Please check [gist here](https://colab.research.google.com/gist/jvishnuvardhan/3a79da9f92ccc137c873cfa564bc8c94/untitled.ipynb). Thanks!

Hi @jvishnuvardhan @Nitya05 ,
I changed your notebook to use tensorflow 1.15 and the error seems to go away and you do get you model exported into tensorflow format.
https://colab.research.google.com/gist/dhruvsakalley/4ea0b1b4b1ea8c1e755eae731709d968/untitled.ipynb#scrollTo=83AWhRhpgK40

**Comment by dhruvsakalley** [comment]
Additionally this issue seems to be related, let me know if you get it working with tf2 https://github.com/onnx/onnx-tensorflow/issues/454

**Comment by jvishnuvardhan** [comment]
@Nitya05 I think this is more related to onnx and i think @dhruvsakalley solution will help you. When I tried with TF2.x, the following part of the code was throwing an error. I think `onnx` was updated recent for `TF2.x`. hence, `from onnx_tf.backend import prepare` line throws an error.

```
import onnx
from onnx_tf.backend import prepare
onnx_model = onnx.load("./SimpleLSTM.onnx")
tf_rep = prepare(onnx_model)
tf_rep.export_graph('./SimpleLSTM.pb')
```
Please close the issue if this was resolved for you. Thanks!

**Comment by Nitya05** [comment]
Hi @dhruvsakalley,
I tried to follow the solution mentioned in onnx/onnx-tensorflow#454, but it did not help in resolving my problem. I am still getting the following error:

**tensorflow.python.ops.op_selector.UnliftableError: Unable to lift tensor <tf.Tensor 'concat_2:0' shape=(6, 12) dtype=float32> because it depends transitively on placeholder <tf.Operation 'Squeeze_1/60' type=Placeholder> via at least one path, e.g.: concat_2 (ConcatV2) <- transpose_1 (Transpose) <- concat_1 (ConcatV2) <- split_1 (Split) <- Squeeze_1 (Squeeze) <- Squeeze_1/60 (Placeholder)**


Also, I tried to use tensorflow 1.15 to run my code, but the import of onnx_tf is giving the following warning and error:

**UserWarning: Tensorflow Addons supports using Python ops for all Tensorflow versions above or equal to 2.2.0 and strictly below 2.4.0 (nightly versions are not supported). 
 The versions of TensorFlow you are currently using is 1.15.0 and is not supported. 
Some things might work, some things might not.
If you were to encounter a bug, do not file an issue.
If you want to make sure you're using a tested and supported configuration, either change the TensorFlow version or the TensorFlow Addons's version. 
You can find the compatibility matrix in TensorFlow Addon's readme:
https://github.com/tensorflow/addons
  UserWarning,
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/ctg_nitya/python3_venv_tf_1.15_gpu/lib/python3.6/site-packages/onnx_tf/__init__.py", line 1, in <module>
    from . import backend
  File "/workspace/ctg_nitya/python3_venv_tf_1.15_gpu/lib/python3.6/site-packages/onnx_tf/backend.py", line 27, in <module>
    from onnx_tf.common.handler_helper import get_all_backend_handlers
  File "/workspace/ctg_nitya/python3_venv_tf_1.15_gpu/lib/python3.6/site-packages/onnx_tf/common/handler_helper.py", line 3, in <module>
    from onnx_tf.handlers.backend import *  # noqa
  File "/workspace/ctg_nitya/python3_venv_tf_1.15_gpu/lib/python3.6/site-packages/onnx_tf/handlers/backend/hardmax.py", line 3, in <module>
    import tensorflow_addons as tfa
  File "/workspace/ctg_nitya/python3_venv_tf_1.15_gpu/lib/python3.6/site-packages/tensorflow_addons/__init__.py", line 21, in <module>
    from tensorflow_addons import activations
  File "/workspace/ctg_nitya/python3_venv_tf_1.15_gpu/lib/python3.6/site-packages/tensorflow_addons/activations/__init__.py", line 17, in <module>
    from tensorflow_addons.activations.gelu import gelu
  File "/workspace/ctg_nitya/python3_venv_tf_1.15_gpu/lib/python3.6/site-packages/tensorflow_addons/activations/gelu.py", line 27, in <module>
    @tf.keras.utils.register_keras_serializable(package="Addons")
  File "/workspace/ctg_nitya/python3_venv_tf_1.15_gpu/lib/python3.6/site-packages/tensorflow_core/python/util/module_wrapper.py", line 193, in __getattr__
    attr = getattr(self._tfmw_wrapped_module, name)
AttributeError: module 'tensorflow.python.keras.api._v1.keras.utils' has no attribute 'register_keras_serializable'**


@jvishnuvardhan I am able to successfully import prepare. The problem happens while doing **tf_rep.export_graph('./SimpleLSTM.pb')**. Is there anything else that can be done to rectify this issue?

**Comment by Nitya05** [comment]
I forgot to mention that I am able to successfully run the onnx model using onnxruntime. The problem happens only when I try to export the .onnx model to .pb.

**Comment by khandeas** [comment]
@Nitya05 

 I would recommend setting up a fresh conda/venv environment and install the following in order:

!pip install tensorflow==1.15
!pip install onnx
!pip install onnx-tf

 It was the only way I got onnx-tf working.

**Comment by Nitya05** [comment]
Thanks @khandeas. I did try a fresh install earlier, but I was using python3 then. I just tried to use python2 with tensorflow-1.15, and it worked. Thanks.

**Comment by jvishnuvardhan** [comment]
I am closing this issue as it was resolved. Thanks!
