### ISSUE TITLE
TFLite ConverterError: Node has inputs from different frames

### ISSUE THREAD

**Issue by mattiadg** [tensorflow/tensorflow#43849]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): with pip
- TensorFlow version (or github SHA if from source):  2.3.0

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
import os
import tensorflow as tf

export_dir = os.path.join('export_dir', 'out')

if not os.path.exists('export_dir'):
    os.mkdir('export_dir')

tf.compat.v1.enable_control_flow_v2()
tf.compat.v1.enable_v2_tensorshape()

def wrap_frozen_graph(graph_def, inputs, outputs):
    def _imports_graph_def():
        tf.compat.v1.import_graph_def(graph_def, name="")
    wrapped_import = tf.compat.v1.wrap_function(_imports_graph_def, [])
    import_graph = wrapped_import.graph
    return wrapped_import.prune(
             tf.nest.map_structure(import_graph.as_graph_element, inputs),
             tf.nest.map_structure(import_graph.as_graph_element, outputs))

graph_def = tf.compat.v1.GraphDef()
loaded = graph_def.ParseFromString(open(os.path.join(export_dir, 'saved_model.pb'),'rb').read())

concrete_func = wrap_frozen_graph(
        graph_def, inputs=['extern_data/placeholders/data/data:0', 'extern_data/placeholders/data/data_dim0_size:0'],
        outputs=['output/output_batch_major:0'])
concrete_func.inputs[0].set_shape([1, 50])
concrete_func.inputs[1].set_shape([1])
concrete_func.outputs[0].set_shape([1, 100])

converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])
converter.experimental_new_converter = True
converter.post_training_quantize=True
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                               tf.lite.OpsSet.SELECT_TF_OPS]
converter.allow_custom_ops=True

tflite_model = converter.convert()

# Save the model.
if not os.path.exists('tflite'):
    os.mkdir('tflite')
output_model = os.path.join('tflite', 'model.tflite')
with open(output_model, 'wb') as f:
     f.write(tflite_model)

```

**The output from the converter invocation**

```
Traceback (most recent call last):
  File "/home/mdigangi/environments/venv-tflite2/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 199, in toco_convert_protos
    enable_mlir_converter)
  File "/home/mdigangi/environments/venv-tflite2/lib/python3.6/site-packages/tensorflow/lite/python/wrap_toco.py", line 38, in wrapped_toco_convert
    enable_mlir_converter)
Exception: {{node output/rec/target0_embed/linear/embedding_lookup}} has inputs from different frames. The input {{node output/rec/target0_embed/linear/embedding_lookup/Enter}} is in frame 'output/rec/while/while_context'. The input {{node output/rec/target0_embed/linear/embedding_lookup/axis}} is in frame ''.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/mdigangi/bin/tflite-toolkit/tools/ckpt2pb.py", line 52, in <module>
    tflite_model = converter.convert()
  File "/home/mdigangi/environments/venv-tflite2/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 1076, in convert
    return super(TFLiteConverterV2, self).convert()
  File "/home/mdigangi/environments/venv-tflite2/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 900, in convert
    self).convert(graph_def, input_tensors, output_tensors)
  File "/home/mdigangi/environments/venv-tflite2/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 633, in convert
    **converter_kwargs)
  File "/home/mdigangi/environments/venv-tflite2/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 574, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "/home/mdigangi/environments/venv-tflite2/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 202, in toco_convert_protos
    raise ConverterError(str(e))
tensorflow.lite.python.convert.ConverterError: {{node output/rec/target0_embed/linear/embedding_lookup}} has inputs from different frames. The input {{node output/rec/target0_embed/linear/embedding_lookup/Enter}} is in frame 'output/rec/while/while_context'. The input {{node output/rec/target0_embed/linear/embedding_lookup/axis}} is in frame ''.
```

**Also, please include a link to the saved model or GraphDef**

```
https://drive.google.com/file/d/1DUyxmwA4eIl5SqZ_R5jMJ1ACH3_0jOFK/view?usp=sharing
```

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:

- Producing wrong results and/or decrease in accuracy
- Producing correct results, but the model is slower than expected (model generated from old converter)

**RNN conversion support**
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

I trained this Tranformer for NMT using [Returnn](https://github.com/rwth-i6/returnn/), which creates a TF model. It uses tf.compat.v1 for retrocompatibility. After creating the model, I freezed it using 
```
freeze_graph.py --output_graph export_dir/out/checkpoint_FROZEN.pb --clear_devices --output_node_names output/output_batch_major --input_meta_graph export_dir/0/params.003.compiled.meta --input_checkpoint export_dir/0/params.003.compiled --input_binary True
```
this script succeeds but adds the node output/rec/target0_embed/linear/embedding_lookup/axis, which creates the error. The node is added [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/convert_to_constants.py#L404-L420).  The node creating the error is the embedding layer of the decoder, which must be called recursively. I tried some quick hacks like remove the "frame_name" from one node, adding it to the other, or setting the first to '', but nothing of this works. 

Added 9 October 2020: if I use the concrete function for inference, it also doesn't work. Maybe it is a problem of TF2 in interpreting frozen graph produced with style of TF1

Added 12 October 2020: I tried to write a minimal code that can reproduce the issue and I've found out that maybe the problem is not due to the last node not being in the frame but the second one. This is the interesting part of the GraphDef of the graph that generates the error:
```
[name: "source_embed_raw/linear/embedding_lookup/axis"
op: "Const"
attr {
  key: "_class"
  value {
    list {
      s: "loc:@source_embed_raw/W"
    }
  }
}
attr {
  key: "_output_shapes"
  value {
    list {
      shape {
      }
    }
  }
}
attr {
  key: "dtype"
  value {
    type: DT_INT32
  }
}
attr {
  key: "value"
  value {
    tensor {
      dtype: DT_INT32
      tensor_shape {
      }
      int_val: 0
    }
  }
}
, name: "source_embed_raw/linear/embedding_lookup"
op: "GatherV2"
input: "source_embed_raw/W/read"
input: "extern_data/placeholders/data/data"
input: "source_embed_raw/linear/embedding_lookup/axis"
attr {
  key: "Taxis"
  value {
    type: DT_INT32
  }
}
attr {
  key: "Tindices"
  value {
    type: DT_INT32
  }
}
attr {
  key: "Tparams"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "_class"
  value {
    list {
      s: "loc:@source_embed_raw/W"
    }
  }
}
attr {
  key: "_output_shapes"
  value {
    list {
      shape {
        dim {
          size: -1
        }
        dim {
          size: -1
        }
        dim {
          size: 512
        }
      }
    }
  }
}
attr {
  key: "batch_dims"
  value {
    i: 0
  }
}
, name: "source_embed_raw/linear/embedding_lookup/Identity"
op: "Identity"
input: "source_embed_raw/linear/embedding_lookup"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "_output_shapes"
  value {
    list {
      shape {
        dim {
          size: -1
        }
        dim {
          size: -1
        }
        dim {
          size: 512
        }
      }
    }
  }
}
, name: "output/rec/target_embed_raw/linear/embedding_lookup/axis"
op: "Const"
input: "^output/rec/while/Identity"
attr {
  key: "_class"
  value {
    list {
      s: "loc:@output/rec/target_embed_raw/W"
    }
  }
}
attr {
  key: "_output_shapes"
  value {
    list {
      shape {
      }
    }
  }
}
attr {
  key: "dtype"
  value {
    type: DT_INT32
  }
}
attr {
  key: "value"
  value {
    tensor {
      dtype: DT_INT32
      tensor_shape {
      }
      int_val: 0
    }
  }
}
, name: "output/rec/target_embed_raw/linear/embedding_lookup"
op: "GatherV2"
input: "output/rec/target_embed_raw/linear/embedding_lookup/Enter"
input: "output/rec/output/Reshape_2"
input: "output/rec/target_embed_raw/linear/embedding_lookup/axis"
attr {
  key: "Taxis"
  value {
    type: DT_INT32
  }
}
attr {
  key: "Tindices"
  value {
    type: DT_INT32
  }
}
attr {
  key: "Tparams"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "_class"
  value {
    list {
      s: "loc:@output/rec/target_embed_raw/W"
    }
  }
}
attr {
  key: "_output_shapes"
  value {
    list {
      shape {
        dim {
          size: -1
        }
        dim {
          size: 512
        }
      }
    }
  }
}
attr {
  key: "batch_dims"
  value {
    i: 0
  }
}
, name: "output/rec/target_embed_raw/linear/embedding_lookup/Enter"
op: "Enter"
input: "output/rec/target_embed_raw/W/read"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "_class"
  value {
    list {
      s: "loc:@output/rec/target_embed_raw/W"
    }
  }
}
attr {
  key: "_output_shapes"
  value {
    list {
      shape {
        dim {
          size: 22526
        }
        dim {
          size: 512
        }
      }
    }
  }
}
attr {
  key: "frame_name"
  value {
    s: "output/rec/while/while_context"
  }
}
attr {
  key: "is_constant"
  value {
    b: true
  }
}
attr {
  key: "parallel_iterations"
  value {
    i: 10
  }
}
, name: "output/rec/target_embed_raw/linear/embedding_lookup/Identity"
op: "Identity"
input: "output/rec/target_embed_raw/linear/embedding_lookup"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "_output_shapes"
  value {
    list {
      shape {
        dim {
          size: -1
        }
        dim {
          size: 512
        }
      }
    }
  }
}
]
```
The error is about the /Axis node not being in the frame but also the Reshape child is not in the frame. 
In this small example instead:
```
import tensorflow as tf
import os
import numpy as np

def loop(m):
    x = tf.compat.v1.get_variable("x", dtype=tf.float32, shape=[5, 5], initializer=tf.random_uniform_initializer())
    l = tf.constant(0.005)
    m = tf.math.abs(tf.nn.embedding_lookup(x, y)) + tf.math.abs(m) + l
    return m

def cond(m):
    return tf.less(tf.math.reduce_sum(m), tf.Variable(1.0))

graph = tf.Graph()
with graph.as_default():
    with tf.compat.v1.variable_scope("init", reuse=tf.compat.v1.AUTO_REUSE) as scope:
        y = tf.compat.v1.placeholder(name="y", shape=[5], dtype=tf.int32)
        m = tf.Variable([[0.0]*5]*5, shape=[5, 5], dtype=tf.float32, name="m")
        z = tf.while_loop(body=loop, cond=cond, loop_vars=[m], name="z")[0]
    output = tf.math.reduce_sum(z, name="output")

nodes = [n for n in graph.as_graph_def().node if "embedding_lookup" in n.name]
print(nodes)
with tf.compat.v1.Session(graph=graph) as sess:
    sess.run(tf.compat.v1.global_variables_initializer())
    print(sess.run(output, feed_dict={y: [0, 1, 2, 3, 4]}))
    tf.compat.v1.saved_model.simple_save(sess, os.path.join("export_dir", "0"), inputs={"y": y}, outputs={"output": output})
```
```
[name: "init/z/embedding_lookup/axis"
op: "Const"
input: "^init/z/Identity"
attr {
  key: "_class"
  value {
    list {
      s: "loc:@init/x"
    }
  }
}
attr {
  key: "dtype"
  value {
    type: DT_INT32
  }
}
attr {
  key: "value"
  value {
    tensor {
      dtype: DT_INT32
      tensor_shape {
      }
      int_val: 0
    }
  }
}
, name: "init/z/embedding_lookup"
op: "GatherV2"
input: "init/z/embedding_lookup/Enter"
input: "init/z/embedding_lookup/Enter_1"
input: "init/z/embedding_lookup/axis"
attr {
  key: "Taxis"
  value {
    type: DT_INT32
  }
}
attr {
  key: "Tindices"
  value {
    type: DT_INT32
  }
}
attr {
  key: "Tparams"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "_class"
  value {
    list {
      s: "loc:@init/x"
    }
  }
}
attr {
  key: "batch_dims"
  value {
    i: 0
  }
}
, name: "init/z/embedding_lookup/Enter"
op: "Enter"
input: "init/x/read"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "_class"
  value {
    list {
      s: "loc:@init/x"
    }
  }
}
attr {
  key: "frame_name"
  value {
    s: "init/z/while_context"
  }
}
attr {
  key: "is_constant"
  value {
    b: true
  }
}
attr {
  key: "parallel_iterations"
  value {
    i: 10
  }
}
, name: "init/z/embedding_lookup/Enter_1"
op: "Enter"
input: "init/y"
attr {
  key: "T"
  value {
    type: DT_INT32
  }
}
attr {
  key: "_class"
  value {
    list {
      s: "loc:@init/x"
    }
  }
}
attr {
  key: "frame_name"
  value {
    s: "init/z/while_context"
  }
}
attr {
  key: "is_constant"
  value {
    b: true
  }
}
attr {
  key: "parallel_iterations"
  value {
    i: 10
  }
}
, name: "init/z/embedding_lookup/Identity"
op: "Identity"
input: "init/z/embedding_lookup"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
]
```
The GatherV2 Op has an Enter and a RefEnter input, both having the same frame, besides the Axis input. In this case it converts successfully to TFLite and the axis not being in the frame does not cause any errors. This works despite the lack of output shapes in this second GraphDef. Any ideas?

Update 13 October 2020: If I don't set tf.enable_control_flow_v2() the conversion succeeds but then the interpreter is not able to use the model.

**Comment by mattiadg** [comment]
I converted the existing code to TF2, using the compat.v1 APIs, but with the TF2 behavior enabled (it wasn't before) and I got into the same error as #42410. The error is probably due to a bug in the TFLite implementation of tf.nn.embedding_lookup.
I need to clean up the code a bit and ensure that this is the case, because now I'm getting more errors...

**Comment by gowthamkpr** [comment]
@mattiadg I am glad you were able to solve the issue. Can you please close the issue as its already being tracked [here](https://github.com/tensorflow/tensorflow/issues/42410). Thanks!
