### ISSUE TITLE
getting these errors in tensorflow.contrib, TfPoseEstimator etc. while running the command "python run_webcam.py --model=mobilenet_thin --resize=432x368 --camera=0" . I have build the pafprocess c++ files swig successfully, but also I'm getting the errors

### ISSUE THREAD

**Issue by jangalasriramd7** [tensorflow/tensorflow#43853]
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    from tf_pose import common
  File "D:\tf-pose-estimation\tf_pose\__init__.py", line 5, in <module>
    from tf_pose.runner import infer, Estimator, get_estimator
  File "D:\tf-pose-estimation\tf_pose\runner.py", line 8, in <module>
    from tf_pose import eval
  File "D:\tf-pose-estimation\tf_pose\eval.py", line 14, in <module>
    from tf_pose.networks import model_wh, get_graph_path
  File "D:\tf-pose-estimation\tf_pose\networks.py", line 6, in <module>
    from tf_pose.network_mobilenet import MobilenetNetwork
  File "D:\tf-pose-estimation\tf_pose\network_mobilenet.py", line 5, in <module>
    from tf_pose import network_base
  File "D:\tf-pose-estimation\tf_pose\network_base.py", line 8, in <module>
    import tensorflow.contrib.slim as slim
ModuleNotFoundError: No module named 'tensorflow.contrib'

**Comment by amahendrakar** [comment]
@jangalasriramd7,
In order to reproduce the issue reported here, could you please provide the TensorFlow version, the complete code and the dataset you are using. Thanks!

**Comment by amahendrakar** [comment]
Also, please go through issue [#40802](https://github.com/tensorflow/tensorflow/issues/40802#issuecomment-651292851), with a similar error and let us know if it helps. Thanks!
