### ISSUE TITLE
tf.signal.stft has side effects

### ISSUE THREAD

**Issue by bliep** [tensorflow/tensorflow#43909]
**Describe the current behavior**
**Describe the expected behavior**
**Standalone code to reproduce the issue**

The following script crashes if the designated line is **uncommented**, else it runs fine. Note that the output of tf.signal.stft is not used.

```
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# uncomment the next line for serious side effects on the GPU (tf 2.1.x, OK on 2.3.x, 2.2.x)
# x = tf.signal.stft(tf.ones((16000,)), frame_length=512, frame_step=256)
x = tf.ones((61, 257), dtype=tf.float32)

# model
l0 = keras.Input(shape=x.shape)
l1 = layers.GRU(100)(l0)
l2 = layers.Dense(100, activation="relu")(l1)
model = keras.Model(inputs=l0, outputs=l2)
print(model.summary())

# call
x = tf.expand_dims(x, 0)
y = model(x)
```

**Other info / logs**
This is a partial crash log:
```
2020-10-09 12:45:02.659125: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-10-09 12:45:03.818397: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-10-09 12:45:03.974618: E tensorflow/stream_executor/cuda/cuda_blas.cc:238] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2020-10-09 12:45:03.982373: E tensorflow/stream_executor/cuda/cuda_blas.cc:238] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2020-10-09 12:45:03.982410: W tensorflow/stream_executor/stream.cc:2041] attempting to perform BLAS operation using StreamExecutor without BLAS support
Traceback (most recent call last):
  File "bug.py", line 18, in <module>
    y = model(x)
  File "/home/adev/.pyenv/versions/ndp120/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 822, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/home/adev/.pyenv/versions/ndp120/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 717, in call
    convert_kwargs_to_constants=base_layer_utils.call_context().saving)
  File "/home/adev/.pyenv/versions/ndp120/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 891, in _run_internal_graph
    output_tensors = layer(computed_tensors, **kwargs)
  File "/home/adev/.pyenv/versions/ndp120/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 822, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/home/adev/.pyenv/versions/ndp120/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/core.py", line 1142, in call
    outputs = gen_math_ops.mat_mul(inputs, self.kernel)
  File "/home/adev/.pyenv/versions/ndp120/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_math_ops.py", line 5616, in mat_mul
    _ops.raise_from_not_ok_status(e, name)
  File "/home/adev/.pyenv/versions/ndp120/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 6606, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InternalError: Blas GEMM launch failed : a.shape=(1, 100), b.shape=(100, 100), m=1, n=100, k=100 [Op:MatMul]
```

[tf_env.txt](https://github.com/tensorflow/tensorflow/files/5354967/tf_env.txt)

**Comment by ravikyram** [comment]
@bliep 

I am not seeing any issue in TF nightly version(`2.4.0-dev20201007`).Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/eb574159bb2868a8b643cb0f813f6920/untitled440.ipynb).Please, verify once and close the issue.Please, use the latest TF versions for better performance.Thanks!

**Comment by bliep** [comment]
@ravikyram 

This applies 2.1.x
