### ISSUE TITLE
Keras Functional API does not support tf.custom_gradient() with tf.numpy_function()

### ISSUE THREAD

**Issue by loic-ehrhardt** [tensorflow/tensorflow#43916]
**System information**

- I have written custom code (see below)
- Red Hat Enterprise Linux Server release 7.7 (Maipo)
- TensorFlow installed from: binary (pip)
- TensorFlow version: v2.3.0-rc2-23-gb36436b087 2.3.0 AND v1.12.1-42951-ge8766a151d 2.4.0-dev20201005
- Python version: 3.6.9

**Describe the current behavior**

Functions with custom gradients (i.e. decorated with `tf.custom_gradient()`) using numpy functions internally (with `tf.numpy_function()`) cannot be used directly with the Keras Functional API (plain crash when calling these for example with `tf.keras.layers.Input(shape=(2,))` Tensor).

**Describe the expected behavior**

Calling these functions on Tensors originating from a `tf.keras.layers.Input()` Tensor should return another symbolic Tensor usable with the Keras Functional API.

**Standalone code to reproduce the issue**

```python
>>> import tensorflow as tf, numpy as np
>>> (tf.__version__, np.__version__)
('2.3.0', '1.18.5')

>>> x = tf.keras.layers.Input(shape=(2,))
>>> x
<tf.Tensor 'input_1:0' shape=(None, 2) dtype=float32>

>>> @tf.custom_gradient
... def my_sin_with_gradient_using_numpy_function(x):
...     def _sin_and_gradient_numpy(x):
...         return (np.sin(x), np.cos(x))
...     (y, dy_dx) = tf.numpy_function(_sin_and_gradient_numpy, [x], [tf.float32, tf.float32])
...     def grad_fn(grad_y):
...         return grad_y * dy_dx
...     return (y, grad_fn)

>>> my_sin_with_gradient_using_numpy_function(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/loic/venv/tf/lib64/python3.6/site-packages/tensorflow/python/ops/custom_gradient.py", line 264, in __call__
    return self._d(self._f, a, k)
  File "/home/loic/venv/tf/lib64/python3.6/site-packages/tensorflow/python/ops/custom_gradient.py", line 218, in decorated
    return _eager_mode_decorator(wrapped, args, kwargs)
  File "/home/loic/venv/tf/lib64/python3.6/site-packages/tensorflow/python/ops/custom_gradient.py", line 412, in _eager_mode_decorator
    result, grad_fn = f(*args, **kwargs)
  File "<stdin>", line 5, in my_sin_with_gradient_using_numpy_function
  File "/home/loic/venv/tf/lib64/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/loic/venv/tf/lib64/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 632, in numpy_function
    return py_func_common(func, inp, Tout, stateful=True, name=name)
  File "/home/loic/venv/tf/lib64/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 519, in py_func_common
    result = func(*[np.array(x) for x in inp])
  File "/home/loic/venv/tf/lib64/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 519, in <listcomp>
    result = func(*[np.array(x) for x in inp])
  File "/home/loic/venv/tf/lib64/python3.6/site-packages/tensorflow/python/framework/ops.py", line 848, in __array__
    " a NumPy call, which is not supported".format(self.name))
NotImplementedError: Cannot convert a symbolic Tensor (input_1:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported
```

**Other info / logs**

This ticket is related to #43542 where I mention the fact that `tf.numpy_function()` does not support symbolic Tensors as of TF 2.3. It looks like this is going to be fixed in TF 2.4 (tested with tf_nightly), but the crash here still happens in a somewhat different fashion.

Below are some observations/tests with TF 2.3 and tf_nightly.

```python
>>> tf.__version__
'2.3.0' # TF 2.3
'2.4.0-dev20201005' # tf_nightly


# Let us define the following implementations of the sin() function:

# sin() with custom gradient, using tensorflow ops:
>>> @tf.custom_gradient
... def my_sin_with_gradient_using_tensorflow_ops(x):
...     def grad_fn(grad_y):
...         return grad_y * tf.cos(x)
...     return (tf.sin(x), grad_fn)

# sin() without custom gradient, using numpy function:
>>> def my_sin_without_gradient_using_numpy_function(x):
...     return tf.numpy_function(np.sin, [x], np.float32)

# sin() with custom gradient, using numpy function:
# This is the function of interest here.
>>> @tf.custom_gradient
... def my_sin_with_gradient_using_numpy_function(x):
...     def _sin_and_gradient_numpy(x):
...         return (np.sin(x), np.cos(x))
...     (y, dy_dx) = tf.numpy_function(_sin_and_gradient_numpy, [x], [tf.float32, tf.float32])
...     def grad_fn(grad_y):
...         return grad_y * dy_dx
...     return (y, grad_fn)


# All these variants return the expected values and gradients with eager Tensors:

>>> x = tf.constant([0.5])
>>> x
<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.5], dtype=float32)> # TF 2.3 and tf_nightly

>>> my_sin_with_gradient_using_tensorflow_ops(x)
<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.47942555], dtype=float32)> # TF 2.3 and tf_nightly
>>> tf.test.compute_gradient(my_sin_with_gradient_using_tensorflow_ops, [x])
((array([[0.87758255]], dtype=float32),), (array([[0.877574]], dtype=float32),)) # TF 2.3 and tf_nightly

>>> my_sin_without_gradient_using_numpy_function(x)
<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.47942555], dtype=float32)> # TF 2.3 and tf_nightly
>>> tf.test.compute_gradient(my_sin_without_gradient_using_numpy_function, [x])
((array([[0.]], dtype=float32),), (array([[0.877574]], dtype=float32),)) # TF 2.3 and tf_nightly

>>> my_sin_with_gradient_using_numpy_function(x)
<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.47942555], dtype=float32)> # TF 2.3 and tf_nightly
>>> tf.test.compute_gradient(my_sin_with_gradient_using_numpy_function, [x])
((array([[0.87758255]], dtype=float32),), (array([[0.877574]], dtype=float32),)) # TF 2.3 and tf_nightly


# However, both fail with Keras Functional API:


>>> x = tf.keras.layers.Input(shape=(2,))
>>> x
<tf.Tensor 'input_1:0' shape=(None, 2) dtype=float32> # TF 2.3
<KerasTensor: shape=(None, 2) dtype=float32 (created by layer 'input_1')> # tf_nightly

# tf.custom_gradient() no longer works with Functional API with new TF version (new bug).
>>> my_sin_with_gradient_using_tensorflow_ops(x)
<tf.Tensor 'Identity_3:0' shape=(None, 2) dtype=float32> # TF 2.3 (ok)
TypeError: Cannot convert a symbolic Keras input/output to a numpy array. # tf_nightly

# tf.numpy_function() works with Functional API with new TF version (fixed bug, see issue #43542).
>>> my_sin_without_gradient_using_numpy_function(x)
NotImplementedError: Cannot convert a symbolic Tensor (input_1:0) to a numpy array # TF 2.3
<KerasTensor: shape=<unknown> dtype=float32 (created by layer 'tf.numpy_function_8')> # tf_nightly

# tf.custom_gradient() used with tf.numpy_function() does not work with Functional API.
>>> my_sin_with_gradient_using_numpy_function(x)
NotImplementedError: Cannot convert a symbolic Tensor (input_1:0) to a numpy array # TF 2.3
TypeError: Cannot convert a symbolic Keras input/output to a numpy array # tf_nightly

# As with issue #43542, wrapping this function into tf.keras.layers.Lambda() is a workaround but the root issue remains.
>>> tf.keras.layers.Lambda(my_sin_with_gradient_using_numpy_function)(x)
<tf.Tensor 'lambda/IdentityN:0' shape=<unknown> dtype=float32> # TF 2.3
<KerasTensor: shape=<unknown> dtype=float32 (created by layer 'lambda_1')> # tf_nightly
```

**Comment by Saduf2019** [comment]
@loic-ehrhardt 
I ran the code shared above its difficult to replicate due to indentation issues can you please share the same in a colab gist.

**Comment by loic-ehrhardt** [comment]
Hi @Saduf2019. I created a github gist [here](https://colab.research.google.com/gist/loic-ehrhardt/2f0827698eaec79f245a3932356c5ae0/untitled0.ipynb). The minimal code to reproduce is in section "Standalone code to reproduce the issue" and what follows in the notebook are the extra information not necessary to reproduce it (but to help debugging this).

**Comment by Saduf2019** [comment]
I am able to replicate the issue reported, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/d3ac43343b72d7e2a45dfd423386b5cb/untitled436.ipynb).

**Comment by loic-ehrhardt** [comment]
Hi, do you have more information regarding this issue? Should we assign this ticket to some tensorflower?

**Comment by loic-ehrhardt** [comment]
Hi,

The issue still exists in TensorFlow 2.4.1:

```python3
import tensorflow as tf

@tf.custom_gradient
def identity(x):
    def grad_fn(grad_y):
        return grad_y
    return (x, grad_fn)

print("-" * 20, "Eager Tensor", "-" * 20)
eager_tensor = tf.constant([4.0])
print(identity(eager_tensor))

print("-" * 20, "Keras Tensor", "-" * 20)
keras_tensor = tf.keras.layers.Input(shape=(2))
print(identity(keras_tensor))
```

which gives:
```
$ python3 main.py 
-------------------- Eager Tensor --------------------
tf.Tensor([4.], shape=(1,), dtype=float32)
-------------------- Keras Tensor --------------------
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    print(identity(keras_tensor))
  File "/home/loic/venv/tf/lib64/python3.6/site-packages/tensorflow/python/ops/custom_gradient.py", line 261, in __call__
    return self._d(self._f, a, k)
  File "/home/loic/venv/tf/lib64/python3.6/site-packages/tensorflow/python/ops/custom_gradient.py", line 215, in decorated
    return _eager_mode_decorator(wrapped, args, kwargs)
  File "/home/loic/venv/tf/lib64/python3.6/site-packages/tensorflow/python/ops/custom_gradient.py", line 457, in _eager_mode_decorator
    flat_result = [gen_array_ops.identity(x) for x in flat_result]
  File "/home/loic/venv/tf/lib64/python3.6/site-packages/tensorflow/python/ops/custom_gradient.py", line 457, in <listcomp>
    flat_result = [gen_array_ops.identity(x) for x in flat_result]
  File "/home/loic/venv/tf/lib64/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3938, in identity
    input, name=name, ctx=_ctx)
  File "/home/loic/venv/tf/lib64/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3957, in identity_eager_fallback
    _attr_T, (input,) = _execute.args_to_matching_eager([input], ctx, [])
  File "/home/loic/venv/tf/lib64/python3.6/site-packages/tensorflow/python/eager/execute.py", line 274, in args_to_matching_eager
    t, dtype, preferred_dtype=default_dtype, ctx=ctx)
  File "/home/loic/venv/tf/lib64/python3.6/site-packages/tensorflow/python/profiler/trace.py", line 163, in wrapped
    return func(*args, **kwargs)
  File "/home/loic/venv/tf/lib64/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1540, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/loic/venv/tf/lib64/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 339, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/loic/venv/tf/lib64/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 265, in constant
    allow_broadcast=True)
  File "/home/loic/venv/tf/lib64/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 276, in _constant_impl
    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
  File "/home/loic/venv/tf/lib64/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 301, in _constant_eager_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "/home/loic/venv/tf/lib64/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 98, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
  File "/home/loic/venv/tf/lib64/python3.6/site-packages/tensorflow/python/keras/engine/keras_tensor.py", line 274, in __array__
    'Cannot convert a symbolic Keras input/output to a numpy array. '
TypeError: Cannot convert a symbolic Keras input/output to a numpy array. This error may indicate that you're trying to pass a symbolic value to a NumPy call, which is not supported. Or, you may be trying to pass Keras symbolic inputs/outputs to a TF API that does not register dispatching, preventing Keras from automatically converting the API call to a lambda layer in the Functional Model.
```

**Comment by jvishnuvardhan** [comment]
@loic-ehrhardt Based on error description, if you disable eager model by `tf.compat.v1.disable_eager_execution()` , then your code runs without an issue. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/2d956509d3dec4298d2c493b8df90966/untitled.ipynb). Thanks!

**Comment by hosford42** [comment]
So tf.custom_gradient is incompatible with eager execution? This is bad news! I need both for my use case.
