### ISSUE TITLE
installing tflite-model-maker encounters errors in regards to tf-nightly==2.4.0.dev20200810

### ISSUE THREAD

**Issue by shilan** [tensorflow/tensorflow#43986]
**System information**
- OS Platform and Distribution (e.g., windows):
- TensorFlow installed from both source and binary: tried on both
- TensorFlow version:  source 2.2.0 , binary 2.0.0
- Python version: 3.7.4
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 3.2.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: N/A

**Describe the problem**
I am trying to pip install tflite-model-maker, (tried from the source too) but I keep getting this error:
ERROR: No matching distribution found for tf-nightly==2.4.0.dev2.4.0.dev20201012
It seems that there is no version of tf-nightly 2.4.0.dev2.4.0.dev20201012
I tried to install another version of tf-nightly but that also encounters other error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\chingool\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 228, in _main
    status = self.run(options, args)
  File "c:\users\chingool\anaconda3\lib\site-packages\pip\_internal\cli\req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "c:\users\chingool\anaconda3\lib\site-packages\pip\_internal\commands\install.py", line 324, in run
    reqs, check_supported_wheels=not options.target_dir
  File "c:\users\chingool\anaconda3\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "c:\users\chingool\anaconda3\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 388, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "c:\users\chingool\anaconda3\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 340, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "c:\users\chingool\anaconda3\lib\site-packages\pip\_internal\operations\prepare.py", line 469, in prepare_linked_requirement
    hashes=self._get_linked_req_hashes(req)
  File "c:\users\chingool\anaconda3\lib\site-packages\pip\_internal\operations\prepare.py", line 259, in unpack_url
    hashes=hashes,
  File "c:\users\chingool\anaconda3\lib\site-packages\pip\_internal\operations\prepare.py", line 130, in get_http_url
    link, downloader, temp_dir.path, hashes
  File "c:\users\chingool\anaconda3\lib\site-packages\pip\_internal\operations\prepare.py", line 282, in _download_http_url
    for chunk in download.chunks:
  File "c:\users\chingool\anaconda3\lib\site-packages\pip\_internal\cli\progress_bars.py", line 168, in iter
    for x in it:
  File "c:\users\chingool\anaconda3\lib\site-packages\pip\_internal\network\utils.py", line 88, in response_chunks
    decode_content=False,
  File "c:\users\chingool\anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "c:\users\chingool\anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "c:\users\chingool\anaconda3\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\chingool\anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 442, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

I feel like I will never be able to install tflite-model-maker, though it looks to be very useful.
Is there any other alternative to that?

**Comment by ymodak** [comment]
Nightly versions change everyday and all the nightly versions are not saved in PyPi only the latest ones.
`tf-nightly==2.4.0.dev20200810` tries to install nightly package built on 08/10/2020 which is not available.
Can you try;
```python
pip install tflite-model-maker-nightly
```
This worked for me.
For installing latest TF try,
```python
pip install tf-nightly
```

**Comment by shilan** [comment]
I tried the nightly build too. Didn't work. 
However later I realized that tf-nightly 2.4.0.dev2.4.0.dev20201012 version has no wheel for python3.7, upgrading to 3.8 and running it again solved the problem.
However now I get another error:
AttributeError: module 'tensorflow_lite_support.metadata.metadata_schema_py_generated' has no attribute 'ModelMetadataT'

**Comment by ymodak** [comment]
Yes nightly wheels get updated daily and are not saved in Pypi.
How are you hitting?
```python
AttributeError: module 'tensorflow_lite_support.metadata.metadata_schema_py_generated' has no attribute 'ModelMetadataT'
```
Do you have a repro code to share?

**Comment by shilan** [comment]
yeah I didn't know that. I am quite new to Python. Things were different in Java world.

> Do you have a repro code to share?
Yes, it just happens at the last line of example, which is exporting. As a matter of fact I just raised an issue here:
https://github.com/tensorflow/tensorflow/issues/44062

**Comment by ymodak** [comment]
I will close this issue since the original topic is solved. We can continue the discussion on the other thread you created. Thanks!
