### ISSUE TITLE
Error while installation on virtual environment

### ISSUE THREAD

**Issue by champnaman** [tensorflow/tensorflow#4403]
I'm trying to install Tensor Flow on my virtual environment with Python 2.7.6. 

When I try the command `pip install --upgrade $TF_BINARY_URL` as mentioned in the [documentation](https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html#virtualenv-installation), I get the following error - 

Downloading/unpacking https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0-cp27-none-linux_x86_64.whl
  Downloading tensorflow-0.10.0-cp27-none-linux_x86_64.whl (36.6MB): 8.4MB downloaded
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/home/naman/tensorflow/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/naman/tensorflow/local/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/naman/tensorflow/local/lib/python2.7/site-packages/pip/req.py", line 1197, in prepare_files
    do_download,
  File "/home/naman/tensorflow/local/lib/python2.7/site-packages/pip/req.py", line 1375, in unpack_url
    self.session,
  File "/home/naman/tensorflow/local/lib/python2.7/site-packages/pip/download.py", line 572, in unpack_http_url
    download_hash = _download_url(resp, link, temp_location)
  File "/home/naman/tensorflow/local/lib/python2.7/site-packages/pip/download.py", line 433, in _download_url
    for chunk in resp_read(4096):
  File "/home/naman/tensorflow/local/lib/python2.7/site-packages/pip/download.py", line 421, in resp_read
    chunk_size, decode_content=False):
  File "/home/naman/tensorflow/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 236, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/naman/tensorflow/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 183, in read
    data = self._fp.read(amt)
  File "/usr/lib/python2.7/httplib.py", line 573, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/ssl.py", line 341, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 260, in read
    return self._sslobj.read(len)
SSLError: [Errno 1] _ssl.c:1429: error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac

Storing debug log for failure in /tmp/tmpcvH6K0

I'm using Ubuntu 14.04 wubi on top of Windows 7. Please sort this error.

**Comment by aselle** [comment]
That looks like possibly a transient network error. Did you try rerunning it again?

**Comment by champnaman** [comment]
I have tried it many times, but the same error again.

**Comment by aselle** [comment]
You can try googling for that Python error. It is definitely not unique to TensorFlow, and given that the package works for me on Ubuntu 14, it has to either be your Python or SSL configuration or your network. You can try downloading the file manually with wget and then pip installing afterwards.

i.e.

wget  $TF_BINARY_URL
pip <downloaded file>

**Comment by gunan** [comment]
A quick google search points to a known openssl issue. 
Closing.
