### ISSUE TITLE
not able to find libcudnn.so.7

### ISSUE THREAD

**Issue by nitin7999** [tensorflow/tensorflow#44040]
**System information**
Operating System: 20.04.4 LTS
TensorFlow version: 2.3.1
Python version: 3.7.4
GCC/Compiler: 7.3.0
CUDA: 10.1.243
cuDNN: 8.0.4
GPU model and memory: GeForce GTX 960m, 4 Gb
NVIDIA-SMI: 450.80.02

2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

2020-10-15 13:01:11.746116: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
v2.3.0-54-gfcc4b966f1 2.3.1

>>> import tensorflow as tf

2020-10-15 12:44:04.961178: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
>>> 
>>> tf.config.list_physical_devices("GPU")
2020-10-15 12:44:11.883542: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-10-15 12:44:11.915652: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-10-15 12:44:11.916045: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:02:00.0 name: GeForce GTX 960M computeCapability: 5.0
coreClock: 1.176GHz coreCount: 5 deviceMemorySize: 3.95GiB deviceMemoryBandwidth: 74.65GiB/s
2020-10-15 12:44:11.916111: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-10-15 12:44:11.918107: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-10-15 12:44:11.919968: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-10-15 12:44:11.920310: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-10-15 12:44:11.922495: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-10-15 12:44:11.923927: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
**2020-10-15 12:44:11.924102: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudnn.so.7'; dlerror: libcudnn.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib/cuda/include:/usr/lib/cuda/lib64:/home/nitin/catkin_ws/devel/lib:/usr/lib/cuda/include:/usr/lib/cuda/lib64
2020-10-15 12:44:11.924120: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1753] Cannot dlopen some GPU libraries.** 
Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
[]

**Comment by ravikyram** [comment]
@nitin7999 

Please, see tested build configurations from [here](https://www.tensorflow.org/install/source#gpu).
Refer the[ issue comment](https://github.com/tensorflow/tensorflow/issues/20271#issuecomment-622990424), [link](https://github.com/tensorflow/tensorflow/issues/38164#issuecomment-656767462) and see if it helps you. Thanks!

**Comment by nitin7999** [comment]
ok how should i go about to change the cudnn installation alone. i guess cudnn 8.0.4 is not supported.

**Comment by nitin7999** [comment]
What to do for this?

>>> tf.test.is_gpu_available(cuda_only=False, min_cuda_compute_capability=None)
WARNING:tensorflow:From <stdin>:1: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
2020-10-15 22:07:08.142338: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-10-15 22:07:08.411314: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2599990000 Hz
2020-10-15 22:07:08.412772: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x561ebe611de0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-15 22:07:08.412847: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-10-15 22:07:08.663373: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-10-15 22:07:08.664875: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x561ebe6a5fe0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-10-15 22:07:08.664954: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 960M, Compute Capability 5.0
2020-10-15 22:07:08.683250: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-10-15 22:07:08.684234: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:02:00.0 name: GeForce GTX 960M computeCapability: 5.0
coreClock: 1.176GHz coreCount: 5 deviceMemorySize: 3.95GiB deviceMemoryBandwidth: 74.65GiB/s
2020-10-15 22:07:08.684358: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-10-15 22:07:08.684445: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-10-15 22:07:08.684507: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-10-15 22:07:08.684569: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-10-15 22:07:08.684626: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-10-15 22:07:08.684702: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2020-10-15 22:07:08.684780: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-10-15 22:07:08.685009: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-10-15 22:07:08.685986: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-10-15 22:07:08.686827: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-10-15 22:07:08.700697: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nitin/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/nitin/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/test_util.py", line 1563, in is_gpu_available
    for local_device in device_lib.list_local_devices():
  File "/home/nitin/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/device_lib.py", line 43, in list_local_devices
    _convert(s) for s in _pywrap_device_lib.list_devices(serialized_config)
**RuntimeError: CUDA runtime implicit initialization on GPU:0 failed. Status: device kernel image is invalid**
>>>

**Comment by ravikyram** [comment]
@nitin7999 

cuDNN 8 is not supported. Please try installing cuDNN 7.6 and check if you are facing the same issue? 
Thanks!

**Comment by nitin7999** [comment]
that is the resuilt shown after installing cuDNN 7.6

**Comment by ymodak** [comment]
@nitin7999 Apologies for the delay in response. I see you are using GeForce GTX 960M which has 5.0 cuda compute capability.
See https://developer.nvidia.com/cuda-gpus
As of now we have TensorFlow pip pre built packages that support CUDA® architectures 3.5, 3.7, 5.2, 6.0, 6.1, 7.0 and higher than 7.0
Unfortunately your gpu is not among the supported pip packages.
See https://www.tensorflow.org/install/gpu#hardware_requirements

Solution here will be to build a pip package from source that supports your gpu architecture.
Thanks!
