### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfa in position 3: invalid start byte

### ISSUE THREAD

**Issue by vineethdas** [tensorflow/tensorflow#44042]
While converting my trained model from saved.pb and checkpoint file to frozen.pb getting the below error :

Traceback (most recent call last):
  File "/home/micronagri/Desktop/tf2_configure/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 491, in <module>
    run_main()
  File "/home/micronagri/Desktop/tf2_configure/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 487, in run_main
    app.run(main=my_main, argv=[sys.argv[0]] + unparsed)
  File "/home/micronagri/Desktop/tf2_configure/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/micronagri/Desktop/tf2_configure/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/absl_py/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/micronagri/Desktop/tf2_configure/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/absl_py/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/micronagri/Desktop/tf2_configure/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 486, in <lambda>
    my_main = lambda unused_args: main(unused_args, flags)
  File "/home/micronagri/Desktop/tf2_configure/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 372, in main
    freeze_graph(flags.input_graph, flags.input_saver, flags.input_binary,
  File "/home/micronagri/Desktop/tf2_configure/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 338, in freeze_graph
    input_graph_def = _parse_input_graph_proto(input_graph, input_binary)
  File "/home/micronagri/Desktop/tf2_configure/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 253, in _parse_input_graph_proto
    text_format.Merge(f.read(), input_graph_def)
  File "/home/micronagri/Desktop/tf2_configure/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/lib/io/file_io.py", line 122, in read
    return self._prepare_value(self._read_buf.read(length))
  File "/home/micronagri/Desktop/tf2_configure/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/lib/io/file_io.py", line 94, in _prepare_value
    return compat.as_str_any(val)
  File "/home/micronagri/Desktop/tf2_configure/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/util/compat.py", line 139, in as_str_any
    return as_str(value)
  File "/home/micronagri/Desktop/tf2_configure/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/util/compat.py", line 118, in as_str
    return as_text(bytes_or_text, encoding)
  File "/home/micronagri/Desktop/tf2_configure/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/util/compat.py", line 109, in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfa in position 3: invalid start byte

Below are my system details :

OS: Ubuntu  - 20.04.1
Python Version : 3.8.5

I found couple of threads detailing the use of 'rb' instead of 'r', but I'm not sure of its working here.

**Comment by amahendrakar** [comment]
@vineethdas,
In order to reproduce the issue reported here, could you please provide the TensorFlow version, the complete code and the dataset you are using. Thanks!

**Comment by vineethdas** [comment]
The model was trained in the Windows System with the Tensorflow Version: 2.3.1
I used the git repository - https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/tools/freeze_graph.py

Though I trained the model in Windows 10, I'm trying to extract the frozen-graph using ubuntu.
The input to the program are the saved.pb and chkpt-00 file.
Let me know if that is possible, (using a windows trained model in linux environment)

**Comment by amahendrakar** [comment]
@vineethdas,
Could you please provide the complete code to build the model and the saved model files as well, so that we can reproduce the issue on our end? Thanks!
