### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.python.tools'

### ISSUE THREAD

**Issue by tekumara** [tensorflow/tensorflow#44141]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 20.04.1 LTS (Focal Fossa)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.3.1
- Python version: 3.8.5
- Installed using virtualenv? pip? conda?: pip using a virtualenv
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

```
$ . venv/bin/activate
$ python
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/code/tfr-transforms/venv/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
ModuleNotFoundError: No module named 'tensorflow.python.tools'
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
$ pip freeze
absl-py==0.10.0
appdirs==1.4.4
astunparse==1.6.3
attrs==20.2.0
autopep8==1.5.4
boto3==1.14.33
boto3-stubs==1.14.33.0
botocore==1.17.63
cachetools==4.1.1
certifi==2020.6.20
cffi==1.14.3
cfgv==3.2.0
chardet==3.0.4
cycler==0.10.0
Cython==0.29.21
dataclasses==0.6
dill==0.3.2
distlib==0.3.1
dm-tree==0.1.5
docutils==0.15.2
filelock==3.0.12
findspark==1.4.2
flake8==3.8.4
flake8-annotations==2.4.1
flake8-colors==0.1.6
future==0.18.2
gast==0.3.3
gin-config==0.3.0
google-api-core==1.22.4
google-api-python-client==1.12.3
google-auth==1.22.1
google-auth-httplib2==0.0.4
google-auth-oauthlib==0.4.1
google-cloud-bigquery==2.1.0
google-cloud-core==1.4.3
google-crc32c==1.0.0
google-pasta==0.2.0
google-resumable-media==1.1.0
googleapis-common-protos==1.52.0
grpcio==1.32.0
h5py==2.10.0
httplib2==0.18.1
identify==1.5.6
idna==2.10
importlib-metadata==1.7.0
importlib-resources==3.0.0
iniconfig==1.1.1
isort==5.5.4
jmespath==0.10.0
kaggle==1.5.8
Keras-Preprocessing==1.1.2
kiwisolver==1.2.0
linecache2==1.0.0
Markdown==3.3.1
matplotlib==3.3.2
mccabe==0.6.1
mypy-boto3==1.14.33.0
mypy-boto3-ec2==1.14.33.0
mypy-boto3-emr==1.14.33.0
mypy-boto3-s3==1.14.33.0
nodeenv==1.5.0
numpy==1.18.5
oauthlib==3.1.0
opencv-python-headless==4.4.0.44
opt-einsum==3.3.0
packaging==20.4
pandas==1.1.3
Pillow==8.0.0
pluggy==0.13.1
pre-commit==2.7.1
promise==2.3
proto-plus==1.10.2
protobuf==3.13.0
psutil==5.7.2
py==1.9.0
py-cpuinfo==7.0.0
py4j==0.10.9
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.6.0
pycparser==2.20
pyflakes==2.2.0
pyparsing==2.4.7
pyspark==2.4.5
pyspark-stubs==3.0.0.post1
pytest==6.1.1
python-dateutil==2.8.1
python-slugify==4.0.1
pytz==2020.1
PyYAML==5.3.1
requests==2.24.0
requests-oauthlib==1.3.0
rsa==4.6
s3transfer==0.3.3
scipy==1.5.3
sentencepiece==0.1.91
six==1.15.0
slugify==0.0.1
spark-data-testing==0.1.1
spark-testing-base==0.10.0
tensorboard==2.3.0
tensorboard-plugin-wit==1.7.0
tensorflow==2.3.1
tensorflow-addons==0.11.2
tensorflow-datasets==4.0.1
tensorflow-estimator==2.3.0
tensorflow-hub==0.9.0
tensorflow-metadata==0.24.0
tensorflow-model-optimization==0.5.0
tensorflow-ranking==0.3.2
tensorflow-serving-api==2.3.0
termcolor==1.1.0
text-unidecode==1.3
tf-models-official==2.3.0
tf-slim==1.1.0
toml==0.10.1
tqdm==4.50.2
traceback2==1.4.0
typeguard==2.10.0
unittest2==1.1.0
uritemplate==3.0.1
urllib3==1.25.10
virtualenv==20.0.35
Werkzeug==1.0.1
wrapt==1.12.1
zipp==3.3.1
```

**Comment by PrattJena** [comment]
I found stackoverflow answer to your query. You can find the link [here](https://stackoverflow.com/questions/41415629/importerror-no-module-named-tensorflow-python)

**Comment by tekumara** [comment]
I've deleted the virtualenv and recreated it. On the second install it worked.

I wonder if it was because during the first installation I had some wheel build failures which required installing some build tools.
