### ISSUE TITLE
Error while install tensorflow with pip install and python 3.5.2

### ISSUE THREAD

**Issue by brando90** [tensorflow/tensorflow#4422]
I was trying to in tensorflow from pip following the standard instructions and I get this error every time:

```
$ pip install --ignore-installed --upgrade $TF_BINARY_URL
Collecting tensorflow==0.10.0 from https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.10.0-cp35-cp35m-linux_x86_64.whl
  Using cached https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.10.0-cp35-cp35m-linux_x86_64.whl
Collecting six>=1.10.0 (from tensorflow==0.10.0)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting wheel>=0.26 (from tensorflow==0.10.0)
Exception:
Traceback (most recent call last):
  File "/home/brando90/envs/tf_gpu/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/brando90/envs/tf_gpu/lib/python3.5/site-packages/pip/commands/install.py", line 310, in run
    wb.build(autobuilding=True)
  File "/home/brando90/envs/tf_gpu/lib/python3.5/site-packages/pip/wheel.py", line 750, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/brando90/envs/tf_gpu/lib/python3.5/site-packages/pip/req/req_set.py", line 370, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/brando90/envs/tf_gpu/lib/python3.5/site-packages/pip/req/req_set.py", line 522, in _prepare_file
    finder, self.upgrade, require_hashes)
  File "/home/brando90/envs/tf_gpu/lib/python3.5/site-packages/pip/req/req_install.py", line 268, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/home/brando90/envs/tf_gpu/lib/python3.5/site-packages/pip/index.py", line 442, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/home/brando90/envs/tf_gpu/lib/python3.5/site-packages/pip/index.py", line 400, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/home/brando90/envs/tf_gpu/lib/python3.5/site-packages/pip/index.py", line 545, in _get_pages
    page = self._get_page(location)
  File "/home/brando90/envs/tf_gpu/lib/python3.5/site-packages/pip/index.py", line 648, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/home/brando90/envs/tf_gpu/lib/python3.5/site-packages/pip/index.py", line 757, in get_page
    "Cache-Control": "max-age=600",
  File "/home/brando90/envs/tf_gpu/lib/python3.5/site-packages/pip/_vendor/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/home/brando90/envs/tf_gpu/lib/python3.5/site-packages/pip/download.py", line 378, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/home/brando90/envs/tf_gpu/lib/python3.5/site-packages/pip/_vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/brando90/envs/tf_gpu/lib/python3.5/site-packages/pip/_vendor/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/home/brando90/envs/tf_gpu/lib/python3.5/site-packages/pip/_vendor/cachecontrol/adapter.py", line 36, in send
    cached_response = self.controller.cached_request(request)
  File "/home/brando90/envs/tf_gpu/lib/python3.5/site-packages/pip/_vendor/cachecontrol/controller.py", line 111, in cached_request
    resp = self.serializer.loads(request, cache_data)
  File "/home/brando90/envs/tf_gpu/lib/python3.5/site-packages/pip/_vendor/cachecontrol/serialize.py", line 114, in loads
    return getattr(self, "_loads_v{0}".format(ver))(request, data)
  File "/home/brando90/envs/tf_gpu/lib/python3.5/site-packages/pip/_vendor/cachecontrol/serialize.py", line 170, in _loads_v2
    cached = json.loads(zlib.decompress(data).decode("utf8"))
zlib.error: Error -5 while decompressing data: incomplete or truncated stream

```

Googling didn't help me so I'm here. Some more info:

Operating System:

    Linux openmind7 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Installed version of CUDA and cuDNN: 
    cuda 7.5 
    cuDNN 5

I know its good to give reproducible examples but I'm not doing anything special. I have a virgin conda environment with 3 packes:

 ```
pip (8.1.2)
setuptools (27.2.0)
wheel (0.29.0)
```

Some info about my python:

```
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
```

**Comment by usmankha123** [comment]
Use nightly build of tensorflow for python 3.5
Visit https://github.com/tensorflow/tensorflow   scroll down
Click on build history for python 3.5
replace storage..... link with this one
hope it helps

**Comment by aselle** [comment]
Closing automatically due to lack of recent activity. Please reopen when further information becomes available. Thank you.
