### ISSUE TITLE
tensorflow.map_fn support in Custom Layer.

### ISSUE THREAD

**Issue by kumar10725** [tensorflow/tensorflow#44253]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Pro
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary):  binary
- TensorFlow version (use command below): 2.1.0
- Python version: 3.7.8
- Bazel version (if compiling from source): None
- GCC/Compiler version (if compiling from source): None
- CUDA/cuDNN version: 10.1.243 / 7.6.5
- GPU model and memory: GeForce GTX 950M 2GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I am trying to create a custom layer that calculates the forward kinematics for a robotic arm using 'DH parameters'. In my code, I am using the 6 joint angles as the input of the custom layer (Kinematics_Physics) and I am using tensorflow.map_fn to iteratively calculate the forward kinematics of each set of angles in the input. My goal is to set the 'DH parameters' as the trainable weights and train a model to optimize the 'DH parameters'.  when I test the custom layer with tf.Variable as input it works without any error. Also, when I used the custom layer wrapped in a tensorflow.keras.layers.Lambda layers, there are no errors but obviously the weights of my custom layer is not visible to the tensorflow. as can be seen from the model.summary() output. However when I try to use the custom layer as it is in the model, tensorflow throws the error as "TypeError: 'Tensor' object cannot be interpreted as an integer".

**Describe the expected behavior**
There could be something wrong in my implementation of the custom layer or probably the Tensorflow API doesn't support the map_fn for layers in the Functional API for building models. Is there a workaround for this problem? Any recommendations?

**Standalone code to reproduce the issue**
```
import tensorflow as tf
print(tf.__version__)
from tensorflow import math as m
from tensorflow.keras import layers

class Kinematics_Physics(layers.Layer):

    def __init__(self,):
        super(Kinematics_Physics, self).__init__()
        # define initial variables
        self.TF_PI = tf.constant(3.1415926535897932, dtype =tf.float32)
        self.TF_180 = tf.constant(180.0, dtype =tf.float32)
        self.TINY_VALUE = tf.constant(1e-6, dtype =tf.float32)
        self.out_Pose=tf.Variable([0,0,0,0,0,0],  dtype =tf.float32, trainable = False)
        self.A_Deg = tf.Variable(0,dtype = tf.float32, trainable = False)
        self.B_Deg = tf.Variable(0,dtype = tf.float32, trainable = False)
        self.C_Deg = tf.Variable(0,dtype = tf.float32, trainable = False)
        self.sA = tf.Variable(0,dtype = tf.float32, trainable = False)
        self.cA = tf.Variable(0,dtype = tf.float32, trainable = False)
        self.b = tf.Variable(tf.zeros((4,4),dtype = tf.float32),dtype = tf.float32, trainable = False)
        
        # initial dh parameters: 6 x 4 parameters for a robotic arm with 6 joints.
        dh = tf.constant([  [0 ,    180.,   -650.,  0.],
                            [270.,   90.,      0.,  0.],
                            [800.,    0.,      0.,  0.],
                            [140.,   90.,   -908.,  0.],
                            [0.,    -96.,      0.,  0.],
                            [0.,    -65.,   260.,   0.]] ,dtype = tf.float32)
        
        # convert to trainable weights?? for further optimization 
        self.dh = tf.Variable(initial_value=dh, trainable=True)

        # initialize a buffer to calculate the the modified angles
        self.dh_processed = tf.Variable(tf.zeros(self.dh.shape,dtype = tf.float32),dtype = tf.float32, trainable = False)
        # buffer for transformation matrix
        self.trans_matrix = tf.Variable(tf.zeros((4,4),dtype = tf.float32),  dtype =tf.float32, trainable = False)


    @tf.function
    def radians(self,a):
        return m.multiply(a,(tf.divide(self.TF_PI, self.TF_180 )))
    
    @tf.function
    def degrees(self,a):
        return m.multiply(a,(tf.divide(self.TF_180 , self.TF_PI)))
    
    @tf.function
    def joint_transform(self,input_values):
        '''input: format --> 1D array = [a, α, d, θ]'''
    
        a = input_values[0] # a
        alpha = self.radians(input_values[1]) #convert degrees to radians
        d = input_values[2] # d
        theta = self.radians(input_values[3]) #convert degrees to radians θ
        
        self.trans_matrix.assign(
                                [[      m.cos(theta),             -m.sin(theta),              0,                a],
                                [m.multiply(m.sin(theta),m.cos(alpha)),  m.multiply(m.cos(theta),m.cos(alpha)), -m.sin(alpha), m.multiply(-m.sin(alpha),d)],
                                [m.multiply(m.sin(theta),m.sin(alpha)),  m.multiply(m.cos(theta),m.sin(alpha)),  m.cos(alpha),  m.multiply(m.cos(alpha),d)],
                                [        0,                             0,                     0,            1        ]])
        return self.trans_matrix
    
    @tf.function
    def to_pose(self,T):
        # converts the transformation matrix to pose [x, y, z, alpha ]
        if(m.abs(T[1,2]) <= self.TINY_VALUE and m.abs(T[2,2]) <= self.TINY_VALUE): #% singular : B = +-90 (Gimbal Lock)
            self.C_Deg.assign(tf.constant(0, dtype =tf.float32))
            self.B_Deg.assign(self.degrees(m.atan2( T[0,2] , m.divide_no_nan(T[2,2], m.cos(self.C_Deg)) ))) #convert radians to degree
            self.A_Deg.assign(self.degrees(m.atan2( T[1,0] ,  m.divide_no_nan(T[1,1], m.cos(self.C_Deg)) ))) #convert radians to degree
        
        else:
            self.A_Deg.assign(self.degrees(m.atan2(-T[0,1] , T[0,0]))) #convert radians to degree
            self.sA.assign(m.sin(self.radians(self.A_Deg)))
            self.cA.assign(m.cos(self.radians(self.A_Deg)))
            self.B_Deg.assign(self.degrees(m.atan2(T[0,2] , m.multiply(self.cA,T[0,0]) - m.multiply(self.sA,T[0,1]))))#convert radians to degree
            self.C_Deg.assign(self.degrees(m.atan2(-T[1,2] , T[2,2]))) #convert radians to degree
        
        self.out_Pose.assign([ T[0,3], T[1,3], T[2,3],self.A_Deg, self.B_Deg , self.C_Deg])
        return self.out_Pose
    
    
    @tf.function
    def forward_kinematics(self, theta):
        
        # add the dh_theta to measured theta to get the final theta
        actual_theta = m.add(self.dh[:,3] ,theta)
        
        # create new dh_table with modified theta for forward kinematics calculation
        self.dh_processed[:,0].assign(self.dh[:,0])
        self.dh_processed[:,1].assign(self.dh[:,1])
        self.dh_processed[:,2].assign(self.dh[:,2])
        self.dh_processed[:,3].assign(actual_theta)
        b = tf.eye(4, dtype = tf.float32)
        for i in tf.range(6):
            b = (tf.linalg.matmul(b,self.joint_transform(self.dh_processed[i])))
        return self.to_pose(b)
      
    def __call__(self, inputs):
        return tf.map_fn(self.forward_kinematics, inputs, parallel_iterations=True, dtype=tf.float32)
    
    def get_config(self):
        config = super(Kinematics_Physics, self).get_config()
        return config
    

if __name__ == "__main__":
    # create a list of six joint angles
    ang = tf.Variable([[20,10,20,10,10,20],[15,10,20,22,20,32]], dtype = tf.float32, trainable=False)
    # Call the Kinematics_physics layer
    fk = Kinematics_Physics()
    print("trainable weights: ", len(fk.trainable_weights))
    print("non-trainable weights: ", len(fk.non_trainable_weights))
    print("trainable_weights: ", fk.trainable_weights)
    print("forward kinematic transform: ", fk(ang[:10]))
    # Everything works up to this.

    # # create a model using functional API and custom layer wrapped in Lambda layer
    in_= layers.Input(shape=(6,))
    for_kin = layers.Lambda(Kinematics_Physics())(in_)
    model = tf.keras.models.Model(inputs=in_, outputs=for_kin) 
    model.summary() 
    # Works but the weights are not trainable in this case
    
    
    # create a model using functional API
    in_= layers.Input(shape=(6,))
    for_kin = Kinematics_Physics()(in_)
    model = tf.keras.models.Model(inputs=in_, outputs=for_kin) 
    model.summary() 
    # Error: expected behavior => should create a model with 24 trainable parameters
    #        but the error happens in tf.map_fn of Kinematics_Physics().__call__ function
```
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
2020-10-23 16:16:20.529396: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2.1.0
2020-10-23 16:16:23.763749: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-10-23 16:16:23.980052: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 950M computeCapability: 5.0
coreClock: 0.928GHz coreCount: 5 deviceMemorySize: 2.00GiB deviceMemoryBandwidth: 74.65GiB/s
2020-10-23 16:16:23.980403: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-10-23 16:16:23.991313: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll 
2020-10-23 16:16:23.997168: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll  
2020-10-23 16:16:23.999492: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll 
2020-10-23 16:16:24.006531: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-10-23 16:16:24.014520: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-10-23 16:16:24.031075: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-23 16:16:24.035576: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-10-23 16:16:24.037553: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2020-10-23 16:16:24.041785: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 950M computeCapability: 5.0
coreClock: 0.928GHz coreCount: 5 deviceMemorySize: 2.00GiB deviceMemoryBandwidth: 74.65GiB/s
2020-10-23 16:16:24.043759: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-10-23 16:16:24.044399: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-10-23 16:16:24.045042: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-10-23 16:16:24.045625: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-10-23 16:16:24.046172: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-10-23 16:16:24.046644: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-10-23 16:16:24.065410: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-23 16:16:24.070724: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-10-23 16:16:25.336541: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-23 16:16:25.337273: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0 
2020-10-23 16:16:25.338396: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N
2020-10-23 16:16:25.358220: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1370 MB memory) -> physical GPU (device: 0, name: GeForce GTX 950M, pci bus id: 0000:01:00.0, compute capability: 5.0)
trainable weights:  1
non-trainable weights:  9
trainable_weights:  [<tf.Variable 'Variable:0' shape=(6, 4) dtype=float32, numpy=
array([[   0.,  180., -650.,    0.],
       [ 270.,   90.,    0.,    0.],
       [ 800.,    0.,    0.,    0.],
       [ 140.,   90., -908.,    0.],
       [   0.,  -96.,    0.,    0.],
       [   0.,  -65.,  260.,    0.]], dtype=float32)>]
2020-10-23 16:16:27.011142: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
forward kinematic transform:  tf.Tensor(
[[ 548.9288   -118.251114 -527.5552     47.53804   -30.621014 -144.55815 ]
 [ 511.83533   -85.7232   -492.43372    49.052803  -46.484085 -145.28882 ]], shape=(2, 6), dtype=float32)
WARNING:tensorflow:
The following Variables were used a Lambda layer's call (lambda), but
are not present in its tracked objects:
  <tf.Variable 'Variable:0' shape=(6, 4) dtype=float32>
It is possible that this is intended behavior, but it is more likely
an omission. This is a strong indication that this layer should be
formulated as a subclassed Layer rather than a Lambda layer.
Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_1 (InputLayer)         [(None, 6)]               0
_________________________________________________________________
lambda (Lambda)              (None, 6)                 0
=================================================================
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
Traceback (most recent call last):
  File "c:/Users/ABCD/Desktop/physics_layer.py", line 127, in <module>
    for_kin = Kinematics_Physics()(in_)
  File "c:/Users/ABCD/Desktop/physics_layer.py", line 99, in __call__
    return tf.map_fn(self.forward_kinematics, inputs, parallel_iterations=True, dtype=tf.float32)
  File "C:\ProgramData\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow_core\python\ops\map_fn.py", line 228, in map_fn
    for elem in elems_flat]
  File "C:\ProgramData\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow_core\python\ops\map_fn.py", line 228, in <listcomp>
    for elem in elems_flat]
  File "C:\ProgramData\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow_core\python\ops\tensor_array_ops.py", line 1078, in __init__
    name=name)
  File "C:\ProgramData\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow_core\python\ops\tensor_array_ops.py", line 716, in __init__
    self._tensor_array = [None for _ in range(size)]
TypeError: 'Tensor' object cannot be interpreted as an integer
```

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.1 and [TF v2.3](https://colab.research.google.com/gist/amahendrakar/9debe2f689e568a98b33ad6c0238cb59/44253.ipynb). 

However, on running the code with [TF-nightly](https://colab.research.google.com/gist/amahendrakar/db65d519032cdfa0dfb4952b58961b62/44253-tf-nightly.ipynb#scrollTo=iv9S1HHP_G_S) the error changes to `TypeError: Could not build a TypeSpec for <KerasTensor: shape=(None, 6) dtype=float32 (created by layer 'input_2')> with type KerasTensor`. Please find the attached gist. Thanks!

**Comment by fchollet** [comment]
It appears that you are overriding the `__call__` method on `Layer`, but you should actually be overriding `call`. Try to see if it fixes your issue (there may be multiple issues with your code).

**Comment by jvishnuvardhan** [comment]
@kumar10725 I think this was resolved. when I updated your code based on @fchollet suggestion, I don't see any error. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/2222de56f93623682119d69c27a6b1b3/44253-tf-nightly.ipynb).

Please verify once and close the issue. Thanks!

**Comment by jvishnuvardhan** [comment]
@kumar10725 Closing this issue as this was resolved. Please feel free to reopen if I am mistaken. Thanks!
