### ISSUE TITLE
Failed build with Cuda-11.1/TF2.3/cuDNN 8.0.4

### ISSUE THREAD

**Issue by kvndhrty** [tensorflow/tensorflow#44251]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 2.3
- Python version: 3.8.6
- Installed using virtualenv? pip? conda?: venv with pip
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): MSVC 2019
- CUDA/cuDNN version: 11.1 / 8.0.4
- GPU model and memory: RTX 3090 w/ 24 GB 

**Describe the problem**
Bazel (via Baselisk) errors in `local_config_cuda`. I've referenced issues: listed [here](https://github.com/tensorflow/tensorflow/issues/38660#issuecomment-616581116) and [here](https://github.com/tensorflow/tensorflow/issues/37888). I have set the Bazel `BAZEL_VC` path, and MSYS2 is installed and pathed correctly.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
C:\Users\Kevin>.virtualenvs\tf_sourcebuild\Scripts\activate

(tf_sourcebuild) C:\Users\Kevin>cd TF_2.3_Source\tensorflow

(tf_sourcebuild) C:\Users\Kevin\TF_2.3_Source\tensorflow>configure.py
You have bazel 3.1.0 installed.
Please specify the location of python. [Default is C:\Users\Kevin\.virtualenvs\tf_sourcebuild\Scripts\python.exe]:


Found possible Python library paths:
  C:\Users\Kevin\AppData\Local\Programs\Python\Python38\lib\site-packages
Please input the desired Python library path to use.  Default is [C:\Users\Kevin\AppData\Local\Programs\Python\Python38\lib\site-packages]

Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Found CUDA 11.1 in:
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.1/lib/x64
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.1/include
Found cuDNN 8 in:
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.1/lib/x64
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.1/include


Please specify a list of comma-separated CUDA compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus. Each capability can be specified as "x.y" or "compute_xy" to include both virtual and binary GPU code, or as "sm_xy" to only include the binary code.
Please note that each additional compute capability significantly increases your build time and binary size, and that TensorFlow only supports compute capabilities >= 3.5 [Default is: 3.5,7.0]: 8.6


Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]: --copt=-march=native


Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]: y
Eigen strong inline overridden.

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: n
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=monolithic     # Config for mostly static monolithic build.
        --config=ngraph         # Build with Intel nGraph support.
        --config=numa           # Build with NUMA support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
        --config=v2             # Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=noaws          # Disable AWS S3 filesystem support.
        --config=nogcp          # Disable GCP support.
        --config=nohdfs         # Disable HDFS support.
        --config=nonccl         # Disable NVIDIA NCCL support.

(tf_sourcebuild) C:\Users\Kevin\TF_2.3_Source\tensorflow>bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package
```

**Any other info / logs**
```
WARNING: The following configs were expanded more than once: [cuda, using_cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=120
INFO: Reading rc options for 'build' from c:\users\kevin\tf_2.3_source\tensorflow\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=C:/Users/Kevin/.virtualenvs/tf_sourcebuild/Scripts/python.exe
INFO: Reading rc options for 'build' from c:\users\kevin\tf_2.3_source\tensorflow\.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=v2
INFO: Reading rc options for 'build' from c:\users\kevin\tf_2.3_source\tensorflow\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=C:/Users/Kevin/.virtualenvs/tf_sourcebuild/Scripts/python.exe --action_env PYTHON_LIB_PATH=C:/Users/Kevin/AppData/Local/Programs/Python/Python38/lib/site-packages --python_path=C:/Users/Kevin/.virtualenvs/tf_sourcebuild/Scripts/python.exe --config=xla --action_env TF_CUDA_VERSION=11.1 --action_env TF_CUBLAS_VERSION=11 --action_env TF_CUDNN_VERSION=8.0.4 --action_env TF_TENSORRT_VERSION=7.2.1 --action_env TF_CUDA_PATHS=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1 --action_env CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.1 --action_env TF_CUDA_COMPUTE_CAPABILITIES=8.6 --config=cuda --define=override_eigen_strong_inline=true --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:v2 in file c:\users\kevin\tf_2.3_source\tensorflow\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file c:\users\kevin\tf_2.3_source\tensorflow\.bazelrc: --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true
INFO: Found applicable config definition build:cuda in file c:\users\kevin\tf_2.3_source\tensorflow\.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file c:\users\kevin\tf_2.3_source\tensorflow\.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain
INFO: Found applicable config definition build:opt in file c:\users\kevin\tf_2.3_source\tensorflow\.tf_configure.bazelrc: --copt=--copt=-march=native --define with_default_optimizations=true
INFO: Found applicable config definition build:cuda in file c:\users\kevin\tf_2.3_source\tensorflow\.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file c:\users\kevin\tf_2.3_source\tensorflow\.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain
INFO: Found applicable config definition build:windows in file c:\users\kevin\tf_2.3_source\tensorflow\.bazelrc: --copt=/w --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --experimental_strict_action_env=true --verbose_failures --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file c:\users\kevin\tf_2.3_source\tensorflow\.bazelrc: --define framework_shared_object=false
INFO: Repository local_config_cuda instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule cuda_configure defined at:
  C:/users/kevin/tf_2.3_source/tensorflow/third_party/gpus/cuda_configure.bzl:1399:18: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
        File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 1369
                _create_local_cuda_repository(<1 more arguments>)
        File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 955, in _create_local_cuda_repository
                _get_cuda_config(repository_ctx, <1 more arguments>)
        File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 657, in _get_cuda_config
                find_cuda_config(repository_ctx, <2 more arguments>)
        File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 635, in find_cuda_config
                _exec_find_cuda_config(<3 more arguments>)
        File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 629, in _exec_find_cuda_config
                execute(repository_ctx, <1 more arguments>)
        File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
The system cannot find the path specified.
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 1369
                _create_local_cuda_repository(<1 more arguments>)
        File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 955, in _create_local_cuda_repository
                _get_cuda_config(repository_ctx, <1 more arguments>)
        File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 657, in _get_cuda_config
                find_cuda_config(repository_ctx, <2 more arguments>)
        File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 635, in find_cuda_config
                _exec_find_cuda_config(<3 more arguments>)
        File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 629, in _exec_find_cuda_config
                execute(repository_ctx, <1 more arguments>)
        File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
The system cannot find the path specified.
WARNING: Target pattern parsing failed.
ERROR: no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 1369
                _create_local_cuda_repository(<1 more arguments>)
        File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 955, in _create_local_cuda_repository
                _get_cuda_config(repository_ctx, <1 more arguments>)
        File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 657, in _get_cuda_config
                find_cuda_config(repository_ctx, <2 more arguments>)
        File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 635, in find_cuda_config
                _exec_find_cuda_config(<3 more arguments>)
        File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 629, in _exec_find_cuda_config
                execute(repository_ctx, <1 more arguments>)
        File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
The system cannot find the path specified.
INFO: Elapsed time: 0.524s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package
```
```
TF_CUDA_PATHS = "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1, C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include,C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\lib\x64,C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin"
```
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by kvndhrty** [comment]
I've now also tried to build the master branch but no luck

**Comment by ravikyram** [comment]
@kvndhrty 

Please, see tested build configurations from [here](https://www.tensorflow.org/install/source_windows#gpu).
Also, refer similar issues #43947, #43720 and see if it helps you. Thanks!

**Comment by kvndhrty** [comment]
Ok, I tried with TF2.3 and the master dev branch with CUDA 11/cuDNN 8.0.4 and I get the same error. Am I doing something else wrong here?

**Comment by ravikyram** [comment]
@kvndhrty 

Please, share the error log with the above mentioned configuration you are seeing. Can you try to reinstall from scratch in a fresh environment and see if the issue still persists. Thanks!

**Comment by kvndhrty** [comment]
Ok, I cleaned and re-installed everything (other than the virtualenv, happy to do that as well) and got the same error:

```
Repository rule cuda_configure defined at:
  C:/users/kevin/tf_2.3_source/tensorflow/third_party/gpus/cuda_configure.bzl:1430:18: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
        File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 1400
                _create_local_cuda_repository(<1 more arguments>)
        File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 977, in _create_local_cuda_repository
                _get_cuda_config(repository_ctx, <1 more arguments>)
        File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 666, in _get_cuda_config
                find_cuda_config(repository_ctx, <2 more arguments>)
        File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 643, in find_cuda_config
                _exec_find_cuda_config(<3 more arguments>)
        File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 637, in _exec_find_cuda_config
                execute(repository_ctx, <1 more arguments>)
        File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/remote_config/common.bzl", line 217, in execute
                fail(<1 more arguments>)
Repository command failed
The system cannot find the path specified.
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 1400
                _create_local_cuda_repository(<1 more arguments>)
        File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 977, in _create_local_cuda_repository
                _get_cuda_config(repository_ctx, <1 more arguments>)
        File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 666, in _get_cuda_config
                find_cuda_config(repository_ctx, <2 more arguments>)
        File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 643, in find_cuda_config
                _exec_find_cuda_config(<3 more arguments>)
        File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 637, in _exec_find_cuda_config
                execute(repository_ctx, <1 more arguments>)
        File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/remote_config/common.bzl", line 217, in execute
                fail(<1 more arguments>)
Repository command failed
The system cannot find the path specified.
WARNING: Target pattern parsing failed.
ERROR: no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 1400
                _create_local_cuda_repository(<1 more arguments>)
        File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 977, in _create_local_cuda_repository
                _get_cuda_config(repository_ctx, <1 more arguments>)
        File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 666, in _get_cuda_config
                find_cuda_config(repository_ctx, <2 more arguments>)
        File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 643, in find_cuda_config
                _exec_find_cuda_config(<3 more arguments>)
        File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 637, in _exec_find_cuda_config
                execute(repository_ctx, <1 more arguments>)
        File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/remote_config/common.bzl", line 217, in execute
                fail(<1 more arguments>)
Repository command failed
The system cannot find the path specified.
INFO: Elapsed time: 13.937s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package
```

Is cuDNN 8.0.4 the issue? Is there something else that has a missing path? The error doesn't give me much of a hint

**Comment by mihaimaruseac** [comment]
The error seems to be a bad path:

```
The system cannot find the path specified.
```

Can you edit `File "C:/users/kevin/tf_2.3_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 1400` to identify what path the code is looking for and then validate that it exists?

**Comment by mihaimaruseac** [comment]
This seems to have stalled. Will close but please reopen if there is more information.
