### ISSUE TITLE
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by KingTamo** [tensorflow/tensorflow#44284]
I am using python 3.7.2 and I have installed the packages required for a code but I have encountered an error while trying to run the code 
This is what I received

`Traceback (most recent call last):
  File "C:\Users\Future\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 6, in <module>
    import cvlib as cv
  File "C:\Users\Future\AppData\Local\Programs\Python\Python37\lib\site-packages\cvlib\__init__.py", line 8, in <module>
    from .gender_detection import detect_gender
  File "C:\Users\Future\AppData\Local\Programs\Python\Python37\lib\site-packages\cvlib\gender_detection.py", line 3, in <module>
    from tensorflow.keras.utils import get_file
  File "C:\Users\Future\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Future\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\Future\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "C:\Users\Future\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Future\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Future\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.`

How can this be solved?

**Comment by ravikyram** [comment]
@KingTamo 

What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the [latest microsoft visual c++ redistributable from here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).
.Also, please follow the instructions from to install from [Tensorflow website.](https://www.tensorflow.org/install/source_windows)

Please, check Your CPU/Python is on 32 bits?

Please, refer duplicate issue #43130
Thanks!
