### ISSUE TITLE
Failed to build due to keras import error (Executing genrule //tensorflow/python/keras/api:keras_python_api_gen failed)

### ISSUE THREAD

**Issue by suhasshastry** [tensorflow/tensorflow#44315]
I am trying to build tensorflow by pulling recent code changes. Keras is not built as part of tensorflow.

**System information**
- OS Platform and Distribution: Linux Ubuntu 20.04
- TensorFlow installed from: source
- TensorFlow version: 2.1
- Python version: 3.8.4
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): 9.3.0
- CUDA/cuDNN version: 11
- GPU model and memory: Nvidia RTX 2070

```
from tensorflow.python.keras.preprocessing import image
  File "/home/zero/.cache/bazel/_bazel_zero/6a745063bb93c191166f02cd77ede64a/execroot/org_tensorflow/bazel-out/k8-opt-exec-50AE0418/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/keras/preprocessing/image.py", line 24, in <module>
    from keras_preprocessing import image
  File "/home/zero/env/lib/python3.8/site-packages/keras_preprocessing/image.py", line 18, in <module>
    backend = get_keras_submodule('backend')
  File "/home/zero/env/lib/python3.8/site-packages/keras_preprocessing/__init__.py", line 24, in get_keras_submodule
    raise ImportError('You need to first `import keras` '
ImportError: You need to first `import keras` in order to use `keras_preprocessing`. For instance, you can do:

import keras
from keras_preprocessing import image

Or, preferably, this equivalent formulation:

from keras import preprocessing


Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/zero/tensorflow/tensorflow/python/tools/BUILD:226:1 Executing genrule //tensorflow/python/keras/api:keras_python_api_gen_compat_v1 failed (Exit 1)
```

**Comment by suhasshastry** [comment]
I saw warning somewhere in between the logs. I am building on Ubuntu (not windows).

```
Auto-Configuration Warning: 'TMP' environment variable is not set, using 'C:\Windows\Temp' as default
```

**Comment by vaibhavthapli** [comment]
use 
Module: tf.keras.preprocessing.image

**Comment by vaibhavthapli** [comment]
> I am trying to build tensorflow by pulling recent code changes. Keras is not built as part of tensorflow.
> 
> **System information**
> 
> * OS Platform and Distribution: Linux Ubuntu 20.04
> * TensorFlow installed from: source
> * TensorFlow version: 2.1
> * Python version: 3.8.4
> * Installed using virtualenv? pip? conda?: virtualenv
> * Bazel version (if compiling from source): 3.1.0
> * GCC/Compiler version (if compiling from source): 9.3.0
> * CUDA/cuDNN version: 11
> * GPU model and memory: Nvidia RTX 2070
> 
> ```
> from tensorflow.python.keras.preprocessing import image
>   File "/home/zero/.cache/bazel/_bazel_zero/6a745063bb93c191166f02cd77ede64a/execroot/org_tensorflow/bazel-out/k8-opt-exec-50AE0418/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/keras/preprocessing/image.py", line 24, in <module>
>     from keras_preprocessing import image
>   File "/home/zero/env/lib/python3.8/site-packages/keras_preprocessing/image.py", line 18, in <module>
>     backend = get_keras_submodule('backend')
>   File "/home/zero/env/lib/python3.8/site-packages/keras_preprocessing/__init__.py", line 24, in get_keras_submodule
>     raise ImportError('You need to first `import keras` '
> ImportError: You need to first `import keras` in order to use `keras_preprocessing`. For instance, you can do:
> 
> import keras
> from keras_preprocessing import image
> 
> Or, preferably, this equivalent formulation:
> 
> from keras import preprocessing
> 
> 
> Target //tensorflow/tools/pip_package:build_pip_package failed to build
> Use --verbose_failures to see the command lines of failed build steps.
> ERROR: /home/zero/tensorflow/tensorflow/python/tools/BUILD:226:1 Executing genrule //tensorflow/python/keras/api:keras_python_api_gen_compat_v1 failed (Exit 1)
> ```


Use 
Module: tf.keras.preprocessing.image

**Comment by suhasshastry** [comment]
Thanks @vaibhavthapli 
I tried changing `from tensorflow.python.keras.preprocessing import image` to `from tensorflow.keras.preprocessing import image` as you suggested in `/tensorflow/tensorflow/python/keras/preprocessing/__init__.py`. Got this error.
```
  from tensorflow.python.keras.preprocessing.sequence import _remove_long_seq
  File "/home/zero/.cache/bazel/_bazel_zero/6a745063bb93c191166f02cd77ede64a/execroot/org_tensorflow/bazel-out/k8-opt-exec-50AE0418/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/keras/preprocessing/__init__.py", line 26, in <module>
    from tensorflow.keras.preprocessing import image
ModuleNotFoundError: No module named 'tensorflow.keras'
```

**Comment by vaibhavthapli** [comment]
You have to write 
Import tensorflow as tf
Then
tf.keras.preprocessing import  image

**Comment by vaibhavthapli** [comment]
Don't use 
tensorflow.keras.prerocessing 
Bcz u give tensorflow name as tf.

**Comment by suhasshastry** [comment]
I am not getting this error while importing tensorflow in my code. I am seeing these errors while building tensorflow from source code.

Full trace of logs

```
ERROR: /home/zero/tensorflow/tensorflow/python/keras/api/BUILD:124:1: Executing genrule //tensorflow/python/keras/api:keras_python_api_gen_compat_v1 failed (Exit 1)
2020-10-26 09:45:38.438376: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "/home/zero/.cache/bazel/_bazel_zero/6a745063bb93c191166f02cd77ede64a/execroot/org_tensorflow/bazel-out/k8-opt-exec-50AE0418/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 807, in <module>
    main()
  File "/home/zero/.cache/bazel/_bazel_zero/6a745063bb93c191166f02cd77ede64a/execroot/org_tensorflow/bazel-out/k8-opt-exec-50AE0418/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 786, in main
    importlib.import_module(package)
  File "/home/zero/.pyenv/versions/3.8.4/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/zero/.cache/bazel/_bazel_zero/6a745063bb93c191166f02cd77ede64a/execroot/org_tensorflow/bazel-out/k8-opt-exec-50AE0418/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/keras/datasets/imdb.py", line 25, in <module>
    from tensorflow.python.keras.preprocessing.sequence import _remove_long_seq
  File "/home/zero/.cache/bazel/_bazel_zero/6a745063bb93c191166f02cd77ede64a/execroot/org_tensorflow/bazel-out/k8-opt-exec-50AE0418/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/keras/preprocessing/__init__.py", line 26, in <module>
    from tensorflow.python.keras.preprocessing import image
  File "/home/zero/.cache/bazel/_bazel_zero/6a745063bb93c191166f02cd77ede64a/execroot/org_tensorflow/bazel-out/k8-opt-exec-50AE0418/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/keras/preprocessing/image.py", line 24, in <module>
    from keras_preprocessing import image
  File "/home/zero/env/lib/python3.8/site-packages/keras_preprocessing/image.py", line 18, in <module>
    backend = get_keras_submodule('backend')
  File "/home/zero/env/lib/python3.8/site-packages/keras_preprocessing/__init__.py", line 24, in get_keras_submodule
    raise ImportError('You need to first `import keras` '
ImportError: You need to first `import keras` in order to use `keras_preprocessing`. For instance, you can do:

```
import keras
from keras_preprocessing import image
```

Or, preferably, this equivalent formulation:

```
from keras import preprocessing
```

Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/zero/tensorflow/tensorflow/python/tools/BUILD:82:1 Executing genrule //tensorflow/python/keras/api:keras_python_api_gen_compat_v1 failed (Exit 1)
INFO: Elapsed time: 2.019s, Critical Path: 1.57s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

**Comment by ravikyram** [comment]
@suhasshastry 

I have tried in colab with TF version 2.1, 2.3 and i am not seeing any issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/a7306c1c6ad2cd08fbaa6925c7b1b793/untitled86.ipynb?authuser=1). Please, verify once and close  the issue. Thanks!

**Comment by ravikyram** [comment]
@suhasshastry 

Please, try with tested build configurations from [here](https://www.tensorflow.org/install/source#gpu).Thanks!

**Comment by suhasshastry** [comment]
Re-cloned and built from scratch. Issue is resolved.
