### ISSUE TITLE
How to restore the model when use distributed  tensorflow ??

### ISSUE THREAD

**Issue by thewintersun** [tensorflow/tensorflow#4436]
I write a simple distributed tensorflow example, the code is here:
https://github.com/thewintersun/distributeTensorflowExample

I use 2 server as the ps server, 2 server as the worker server. 
**The command is as follow:**
**At ps server:**

CUDA_VISIBLE_DEVICES='' python distribute.py --ps_hosts=192.168.100.42:2222,192.168.100.22:2223 --worker_hosts=192.168.100.30:2224,192.168.100.253:2225 --job_name=ps --task_index=0

CUDA_VISIBLE_DEVICES='' python distribute.py --ps_hosts=192.168.100.42:2222,192.168.100.22:2223 --worker_hosts=192.168.100.30:2224,192.168.100.253:2225 --job_name=ps --task_index=1

**At worker server:**

CUDA_VISIBLE_DEVICES=0 python distribute.py --ps_hosts=192.168.100.42:2222,192.168.100.22:2223 --worker_hosts=192.168.100.30:2224,192.168.100.253:2225 --job_name=worker --task_index=0

CUDA_VISIBLE_DEVICES=0 python distribute.py --ps_hosts=192.168.100.42:2222,192.168.100.22:2223 --worker_hosts=192.168.100.30:2224,192.168.100.253:2225 --job_name=worker --task_index=1

**The train process is ok.
But when I stop the chief worker process and restart it ,  I expect the program will restore the model from the checkpoint file , but it print the following error and exit :**
-----------------------------------------
I tensorflow/core/common_runtime/gpu/gpu_device.cc:839] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 970, pci bus id: 0000:01:00.0)
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:206] Initialize HostPortsGrpcChannelCache for job ps -> {192.168.100.42:2222, 192.168.100.22:2223}
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:206] Initialize HostPortsGrpcChannelCache for job worker -> {localhost:2224, 192.168.100.253:2225}
I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:202] Started server with target: grpc://localhost:2224
E tensorflow/core/client/tensor_c_api.cc:485] Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./checkpoint/model.ckpt-0
         [[Node: save/restore_slice_2 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:ps/replica:0/task:1/cpu:0"](_recv_save/Const_0_S1, save/restore_slice_2/tensor_name, save/restore_slice_2/shape_and_slice)]]
Traceback (most recent call last):
  File "distribute.py", line 77, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "distribute.py", line 60, in main
    with sv.managed_session(server.target) as sess:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 942, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 768, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 357, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 931, in managed_session
    start_standard_services=start_standard_services)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 680, in prepare_or_wait_for_session
    init_feed_dict=self._init_feed_dict, init_fn=self._init_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/session_manager.py", line 164, in prepare_session
    max_wait_secs=max_wait_secs, config=config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/session_manager.py", line 224, in recover_session
    saver.restore(sess, ckpt.model_checkpoint_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1129, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 382, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 655, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 723, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 743, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./checkpoint/model.ckpt-0
         [[Node: save/restore_slice_2 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:ps/replica:0/task:1/cpu:0"](_recv_save/Const_0_S1, save/restore_slice_2/tensor_name, save/restore_slice_2/shape_and_slice)]]
Caused by op u'save/restore_slice_2', defined at:
  File "distribute.py", line 77, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "distribute.py", line 49, in main
    saver = tf.train.Saver()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 861, in __init__
    restore_sequentially=restore_sequentially)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 519, in build
    filename_tensor, vars_to_save, restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 272, in _AddRestoreOps
    values = self.restore_op(filename_tensor, vs, preferred_shard)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 187, in restore_op
    preferred_shard=preferred_shard)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/io_ops.py", line 203, in _restore_slice
    preferred_shard, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 359, in _restore_slice
    preferred_shard=preferred_shard, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2310, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1232, in __init__
    self._traceback = _extract_stack()
-----------------------------------------------

Is anyone can tell me how to restore the model when use distribute tensorflow??

**Comment by arg0** [comment]
I am facing the same problem. I suppose that is /job:ps/.. and /job:worker/.. on the same machine would be translated to /job:lcoalhost/....... But It still be translated to /job:localhost even your ps is another machine, so the saver.restore can not find the right ps==localhost . I am trying on freeze_graph function. PS.still have no success

**Comment by hholst80** [comment]
@arg0 I don't think that is the real problem. This is something I also see on my machine (the hostname is translated into "localhost" if it matches the IP of the machine) and check-pointing works fine there. Are you using the r0.10 release candidate?

@thewintersun can you replicate the problem with only one worker? Are you using a shared network filesystem such that all nodes can access the checkpoint directory (and read from it)?

**Comment by jmchen-g** [comment]
Usually the summary is written by the chief worker to some dir and when it restores, the ps need to be able to locate and have access to that dir also. Is it the case for you guys?

**Comment by thewintersun** [comment]
@hholst80 
1. If use only one worker, the problem is the same , still can not reload the model at the chief worker if the chief worker and the ps not run at the same machine. 
2. I am not using a shared network filesystem. But I think there is not need a shared network system.

**Comment by thewintersun** [comment]
@jmchen-g 
yes. 

It seems that the ps can not find the checkpoint file. 

I did another test: I run the ps and the worker at the same machine , and run in different dir. 
then the problem is the same: " Failed to find any matching files for ./checkpoint/model.ckpt-58080"

I guess when the chief worker reload the model , the worker notify the ps to reload paramter value from the same checkpoint dir . 

Is that means the chief worker and ps must in the same machine and run in the same dir???

**Comment by thewintersun** [comment]
@jmchen-g 
yes.

It seems that the ps can not find the checkpoint file.


I guess when the chief worker reload the model , the worker notify the ps to reload paramter value from the same checkpoint dir .

Is that means the chief worker and ps must in the same machine ???

**Comment by zhichao-li** [comment]
@thewintersun met the same problem too, wondering have you solved that?

**Comment by tatatodd** [comment]
@thewintersun Are you still having problems with this?

**Comment by thewintersun** [comment]
@tatatodd 
yes, still have this problem

**Comment by tatatodd** [comment]
@thewintersun I believe you need to use a shared network filesystem, so that the PS can read the checkpoints that were written by the chief.  You do not need to run the chief and ps on the same machine; a shared filesystem is enough.

@concretevitamin will know for sure.

**Comment by thewintersun** [comment]
@tatatodd  ok

**Comment by concretevitamin** [comment]
Todd is exactly correct (try using HDFS)  :)

**Comment by thewintersun** [comment]
@concretevitamin  
is the tensorflow already support the HDFS?

**Comment by xiaop1987** [comment]
@thewintersun hdfs has been supported by the latest version(r0.11) of tf. Check this [How to run tensorflow on hadoop](https://www.tensorflow.org/versions/r0.11/how_tos/hadoop/index.html#how-to-run-tensorflow-on-hadoop) plz.

**Comment by tatatodd** [comment]
@thewintersun I hope this answers your question.  I'm closing this out, but feel free to comment on this issue or file a new issue if you still run into problems.  Thanks!
