### ISSUE TITLE
Datatype mismatch error

### ISSUE THREAD

**Issue by rajeshgupta88** [tensorflow/tensorflow#44368]
I am trying to run the TFLite recommendation system example code but getting the following error while running the "Training Model" commands. Please suggest if I am missing something?

Documentation Link: https://github.com/tensorflow/examples/tree/master/lite/examples/recommendation/ml

TypeError: Value passed to parameter 'indices' has DataType float32 not in list of allowed values: uint8, int32, int64

#######################
Full snippet:

INFO:tensorflow:Setting up train and eval input_fns.
I1027 21:22:29.326874 140339508344576 app.py:251] Setting up train and eval input_fns.
INFO:tensorflow:Build keras model for mode: train_and_eval.
I1027 21:22:29.326983 140339508344576 app.py:251] Build keras model for mode: train_and_eval.
2020-10-27 21:22:29.336519: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-10-27 21:22:29.340825: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 4007930000 Hz
2020-10-27 21:22:29.341035: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x563fc6e69aa0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-27 21:22:29.341056: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-10-27 21:22:29.341118: I tensorflow/core/common_runtime/process_util.cc:147] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
2020-10-27 21:22:29.577370: I tensorflow/core/profiler/lib/profiler_session.cc:159] Profiler session started.
Epoch 1/10000
Traceback (most recent call last):
  File "/home/rajesh/anaconda3/envs/tf-2-gpu/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/rajesh/anaconda3/envs/tf-2-gpu/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rajesh/Documents/Privacy/TFLite/Tutorial/Recommendation_Google/model/recommendation_model_launcher_keras.py", line 253, in <module>
    app.run(main)
  File "/home/rajesh/anaconda3/envs/tf-2-gpu/lib/python3.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/rajesh/anaconda3/envs/tf-2-gpu/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/rajesh/Documents/Privacy/TFLite/Tutorial/Recommendation_Google/model/recommendation_model_launcher_keras.py", line 240, in main
    eval_steps=FLAGS.num_eval_steps)
  File "/home/rajesh/Documents/Privacy/TFLite/Tutorial/Recommendation_Google/model/recommendation_model_launcher_keras.py", line 180, in train_and_eval
    callbacks=callbacks)
  File "/home/rajesh/anaconda3/envs/tf-2-gpu/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/rajesh/anaconda3/envs/tf-2-gpu/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 848, in fit
    tmp_logs = train_function(iterator)
  File "/home/rajesh/anaconda3/envs/tf-2-gpu/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/home/rajesh/anaconda3/envs/tf-2-gpu/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 627, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/home/rajesh/anaconda3/envs/tf-2-gpu/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 506, in _initialize
    *args, **kwds))
  File "/home/rajesh/anaconda3/envs/tf-2-gpu/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2446, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/rajesh/anaconda3/envs/tf-2-gpu/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2777, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/rajesh/anaconda3/envs/tf-2-gpu/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2667, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/rajesh/anaconda3/envs/tf-2-gpu/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/rajesh/anaconda3/envs/tf-2-gpu/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 441, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/rajesh/anaconda3/envs/tf-2-gpu/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 968, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    /home/rajesh/anaconda3/envs/tf-2-gpu/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:571 train_function  *
        outputs = self.distribute_strategy.run(
    /home/rajesh/Documents/Privacy/TFLite/Tutorial/Recommendation_Google/model/keras_losses.py:83 call  *
        full_labels = tf.one_hot(
    /home/rajesh/anaconda3/envs/tf-2-gpu/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:180 wrapper  **
        return target(*args, **kwargs)
    /home/rajesh/anaconda3/envs/tf-2-gpu/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py:4010 one_hot
        name)
    /home/rajesh/anaconda3/envs/tf-2-gpu/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py:6200 one_hot
        off_value=off_value, axis=axis, name=name)
    /home/rajesh/anaconda3/envs/tf-2-gpu/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:578 _apply_op_helper
        param_name=input_name)
    /home/rajesh/anaconda3/envs/tf-2-gpu/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:61 _SatisfiesTypeConstraint
        ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))

    TypeError: Value passed to parameter 'indices' has DataType float32 not in list of allowed values: uint8, int32, int64

**Comment by Saduf2019** [comment]
@rajeshgupta88 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]

Please refer to similar resolved issues and let us know. [link](https://stackoverflow.com/questions/42319337/tensorflow-type-error-value-passed-to-parameter-shape-has-datatype-float32-no), [link1](https://github.com/keras-team/keras/issues/6171), [link2](https://github.com/tjvandal/srcnn-tensorflow/issues/1).

**Comment by lintian06** [comment]
Hi Rajesh,

Please provide more information about the environment. Can you reformat the question in the issue template suggested by @Saduf2019 ? 

I ran the code before, it seemed OK.

**Comment by rajeshgupta88** [comment]
Hi All,
Sorry about the delayed response. It is working fine now. Seems like it was a bad day.

Thanks for your support. I am closing this issue.
