### ISSUE TITLE
InvalidZoneinfoFile when trying to create a GMT pendulum object

### ISSUE THREAD

**Issue by laserpedro** [tensorflow/tensorflow#44372]
Hello, I encountered the issue below when trying to execute this code

**System information**
- Windows 10
- python 3.7
- pendulum 2.0.2
- pytzdata: 2020.1 (dependency installed by pendulum)

**Code**
`import pendulum` 
`gmt_time = pendulum.now('GMT')`

**Workaround**
This [issue](https://github.com/sdispater/pendulum/issues/300) was closed  but it seem that with my current config it re-appears.
I downgraded my pytzdata version to an old one `2018.3` as a workaround.

**Traceback**
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\pnouhaud\.conda\envs\asbooker_prod_py37\lib\site-packages\pendulum\__init__.py", line 212, in now
    tz = _safe_timezone(tz)
  File "C:\Users\pnouhaud\.conda\envs\asbooker_prod_py37\lib\site-packages\pendulum\__init__.py", line 82, in _safe_timezone
    return timezone(obj)
  File "C:\Users\pnouhaud\.conda\envs\asbooker_prod_py37\lib\site-packages\pendulum\tz\__init__.py", line 36, in timezone
    tz = _Timezone(name, extended=extended)
  File "C:\Users\pnouhaud\.conda\envs\asbooker_prod_py37\lib\site-packages\pendulum\tz\timezone.py", line 30, in __init__
    tz = read(name, extend=extended)
  File "C:\Users\pnouhaud\.conda\envs\asbooker_prod_py37\lib\site-packages\pendulum\tz\zoneinfo\__init__.py", line 9, in read
    return Reader(extend=extend).read_for(name)
  File "C:\Users\pnouhaud\.conda\envs\asbooker_prod_py37\lib\site-packages\pendulum\tz\zoneinfo\reader.py", line 52, in read_for
    return self.read(file_path)
  File "C:\Users\pnouhaud\.conda\envs\asbooker_prod_py37\lib\site-packages\pendulum\tz\zoneinfo\reader.py", line 64, in read
    return self._parse(fd)
  File "C:\Users\pnouhaud\.conda\envs\asbooker_prod_py37\lib\site-packages\pendulum\tz\zoneinfo\reader.py", line 115, in _parse
    type_idx = self._parse_type_idx(fd, hdr.transitions)
  File "C:\Users\pnouhaud\.conda\envs\asbooker_prod_py37\lib\site-packages\pendulum\tz\zoneinfo\reader.py", line 198, in _parse_type_idx
    buff = self._check_read(fd, n)
  File "C:\Users\pnouhaud\.conda\envs\asbooker_prod_py37\lib\site-packages\pendulum\tz\zoneinfo\reader.py", line 77, in _check_read
    nbytes, fd.name, len(result) if result else 0
pendulum.tz.zoneinfo.exceptions.InvalidZoneinfoFile: Expected 0 bytes reading C:\Users\pnouhaud\.conda\envs\asbooker_prod_py37\lib\site-packages\pytzdata\zoneinfo\GMT, but got 0

**Comment by laserpedro** [comment]
Incorrect project
