### ISSUE TITLE
tf.where raises TypeError for a RaggedTensor argument 'condition'

### ISSUE THREAD

**Issue by klausk55** [tensorflow/tensorflow#44386]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): `pip install tensorflow`
- TensorFlow version (use command below): v2.3.0-54-gfcc4b966f1 2.3.1
- Python version: 3.8.2 64-bit ('venv')

**Describe the current behavior**
Calling tf.where raises TypeError for a RaggedTensor argument 'condition' `TypeError: Expected bool passed to parameter 'condition' of op 'SelectV2', got tf.RaggedTensor`.

**Describe the expected behavior**
tf.where should support RaggedTensor

**Other info / logs** 
Source code snippet:

`input_action_mask = tf.where(tf.math.equal(action_mask, 0), NO_ZERO_INPUT_VALUE, action_mask, name="input_action_mask")`

`action_mask` is a RaggedTensor, `NO_ZERO_INPUT_VALUE` is a float (I think broadcasting should not be a problem here)

```
2020-10-28 15:26:31,076 ERROR worker.py:1018 -- Possible unhandled error from worker: ray::RolloutWorker.__init__() (pid=3809, ip=172.28.211.149)
  File "/home/user/venv/lib/python3.8/site-packages/tensorflow/python/framework/tensor_util.py", line 268, in inner
    _check_failed(v)
  File "/home/user/venv/lib/python3.8/site-packages/tensorflow/python/framework/tensor_util.py", line 249, in _check_failed
    raise ValueError(v)
ValueError: tf.RaggedTensor(values=Tensor("tu_policy/Equal_1:0", shape=(?, 1, 133), dtype=bool), row_splits=Tensor("tu_policy/Placeholder_12:0", shape=(?,), dtype=int64))

During handling of the above exception, another exception occurred:

ray::RolloutWorker.__init__() (pid=3809, ip=172.28.211.149)
  File "/home/user/venv/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py", line 465, in _apply_op_helper
    values = ops.convert_to_tensor(
  File "/home/user/venv/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1499, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/user/venv/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 338, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/user/venv/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 263, in constant
    return _constant_impl(value, dtype, shape, name, verify_shape=False,
  File "/home/user/venv/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 280, in _constant_impl
    tensor_util.make_tensor_proto(
  File "/home/user/venv/lib/python3.8/site-packages/tensorflow/python/framework/tensor_util.py", line 456, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/home/user/venv/lib/python3.8/site-packages/tensorflow/python/framework/tensor_util.py", line 335, in _AssertCompatible
    raise TypeError("Expected %s, got %s of type '%s' instead." %
TypeError: Expected bool, got tf.RaggedTensor(values=Tensor("tu_policy/Equal_1:0", shape=(?, 1, 133), dtype=bool), row_splits=Tensor("tu_policy/Placeholder_12:0", shape=(?,), dtype=int64)) of type 'RaggedTensor' instead.

During handling of the above exception, another exception occurred:

ray::RolloutWorker.__init__() (pid=3809, ip=172.28.211.149)
  File "python/ray/_raylet.pyx", line 479, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 483, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 484, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 438, in ray._raylet.execute_task.function_executor
  File "/home/user/venv/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 416, in __init__
    self._build_policy_map(policy_dict, policy_config)
  File "/home/user/venv/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1008, in _build_policy_map
    policy_map[name] = cls(obs_space, act_space, merged_conf)
  File "/home/user/venv/lib/python3.8/site-packages/ray/rllib/policy/tf_policy_template.py", line 206, in __init__
    DynamicTFPolicy.__init__(
  File "/home/user/venv/lib/python3.8/site-packages/ray/rllib/policy/dynamic_tf_policy.py", line 198, in __init__
    self.model = ModelCatalog.get_model_v2(
  File "/home/user/venv/lib/python3.8/site-packages/ray/rllib/models/catalog.py", line 339, in get_model_v2
    raise e
  File "/home/user/venv/lib/python3.8/site-packages/ray/rllib/models/catalog.py", line 324, in get_model_v2
    instance = model_cls(obs_space, action_space,
  File "/mnt/c/Users/user/Desktop/KI_Galvanik/MARL_for_Galvanic_per_second_2_TUs/articleSchedulingModel.py", line 41, in __init__
    input_action_mask = tf.where(tf.math.equal(action_mask, 0), NO_ZERO_INPUT_VALUE, action_mask, name="input_action_mask")
  File "/home/user/venv/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/user/venv/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 4461, in where_v2
    return gen_math_ops.select_v2(condition=condition, t=x, e=y, name=name)
  File "/home/user/venv/lib/python3.8/site-packages/tensorflow/python/ops/gen_math_ops.py", line 8874, in select_v2
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "/home/user/venv/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py", line 475, in _apply_op_helper
    raise TypeError(
TypeError: Expected bool passed to parameter 'condition' of op 'SelectV2', got tf.RaggedTensor(values=Tensor("tu_policy/Equal_1:0", shape=(?, 1, 133), dtype=bool), row_splits=Tensor("tu_policy/Placeholder_12:0", shape=(?,), dtype=int64)) of type 'RaggedTensor' instead. Error: Expected bool, got tf.RaggedTensor(values=Tensor("tu_policy/Equal_1:0", shape=(?, 1, 133), dtype=bool), row_splits=Tensor("tu_policy/Placeholder_12:0", shape=(?,), dtype=int64)) of type 'RaggedTensor' instead.
```

**Comment by Saduf2019** [comment]
@klausk55 
Please share simple stand alone code to replicate the issue or if possible share a colab gist with the error reported.

**Comment by klausk55** [comment]
In the following stand alone code I get a different error.

```
import tensorflow as tf

print(tf.version.VERSION, tf.version.GIT_VERSION)

NO_ZERO_INPUT_VALUE = 1e-6

action_mask = tf.keras.layers.Input(shape=(None, 1, 133), name="action_mask", ragged=True)

input_action_mask = tf.where(tf.math.equal(action_mask, 0), NO_ZERO_INPUT_VALUE, action_mask, name="input_action_mask")
```

```
2020-10-28 16:41:33.727533: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-10-28 16:41:33.727579: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2.3.1 v2.3.0-54-gfcc4b966f1
2020-10-28 16:46:39.442645: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-10-28 16:46:39.442705: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-10-28 16:46:39.442727: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ODU-GALV1): /proc/driver/nvidia/version does not exist
2020-10-28 16:46:39.443208: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-10-28 16:46:39.450030: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2207995000 Hz
2020-10-28 16:46:39.450744: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4abb7f0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-28 16:46:39.450822: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/user/.vscode-server/extensions/ms-python.python-2020.9.114305/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/user/.vscode-server/extensions/ms-python.python-2020.9.114305/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/user/.vscode-server/extensions/ms-python.python-2020.9.114305/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "/usr/lib/python3.8/runpy.py", line 263, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mnt/c/Users/user/Desktop/KI_Galvanik/MARL_for_Galvanic_per_second_2_TUs/test.py", line 10, in <module>
    input_action_mask = tf.where(tf.math.equal(action_mask, 0), NO_ZERO_INPUT_VALUE, action_mask, name="input_action_mask")
  File "/home/user/venv/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/user/venv/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 4461, in where_v2
    return gen_math_ops.select_v2(condition=condition, t=x, e=y, name=name)
  File "/home/user/venv/lib/python3.8/site-packages/tensorflow/python/ops/gen_math_ops.py", line 8869, in select_v2
    return select_v2_eager_fallback(
  File "/home/user/venv/lib/python3.8/site-packages/tensorflow/python/ops/gen_math_ops.py", line 8889, in select_v2_eager_fallback
    _attr_T, _inputs_T = _execute.args_to_matching_eager([t, e], ctx)
  File "/home/user/venv/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 262, in args_to_matching_eager
    ops.convert_to_tensor(
  File "/home/user/venv/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1499, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/user/venv/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 338, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/user/venv/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 263, in constant
    return _constant_impl(value, dtype, shape, name, verify_shape=False,
  File "/home/user/venv/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 275, in _constant_impl
    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
  File "/home/user/venv/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 300, in _constant_eager_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "/home/user/venv/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 98, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: TypeError: object of type 'RaggedTensor' has no len()
```

Oh my goodness what a fucking day! Sorry.

**Comment by Saduf2019** [comment]
@klausk55
I ran the code shared and it has been fixed in tf-nightly [2.5.0-dev20201028]  do not face any error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/d709353d6640ca2a25fa9f946e00d266/untitled455.ipynb). Thanks!

**Comment by klausk55** [comment]
Any ideas regarding the first reported error?

`TypeError: Expected bool passed to parameter 'condition' of op 'SelectV2', got tf.RaggedTensor(values=Tensor("tu_policy/Equal_1:0", shape=(?, 1, 133), dtype=bool), row_splits=Tensor("tu_policy/Placeholder_12:0", shape=(?,), dtype=int64)) of type 'RaggedTensor' instead. Error: Expected bool, got tf.RaggedTensor(values=Tensor("tu_policy/Equal_1:0", shape=(?, 1, 133), dtype=bool), row_splits=Tensor("tu_policy/Placeholder_12:0", shape=(?,), dtype=int64)) of type 'RaggedTensor' instead.`


By the way, are currently RaggedTensors supported by any further `tf.keras.layers` types or yet only by `tf.keras.layers.Input`?

**Comment by Saduf2019** [comment]
@klausk55 
Can you please try on nightly and see if you are facing the error.

**Comment by klausk55** [comment]
No more facing the error on nightly!
