### ISSUE TITLE
tflite_convert produce 1kb tensorflow lite file

### ISSUE THREAD

**Issue by fanto88** [tensorflow/tensorflow#44393]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): source if i remember correctly
- TensorFlow version (or github SHA if from source): 2.3.1

**Command used to run the converter or code if you’re using the Python API**
So, i'm trying to use [SSD ResNet101 V1 FPN 640x640 (RetinaNet101) found here][1] model for my android application. 
I download the model on desktop and then i use this command

`    python object_detection/export_tflite_graph_tf2.py --pipeline_config_path C:\Users\Davide\Desktop\ssd_resnet101_v1_fpn_640x640_coco17_tpu-8\pipeline.config --trained_checkpoint_dir C:\Users\Davide\Desktop\ssd_resnet101_v1_fpn_640x640_coco17_tpu-8\checkpoint --output_directory C:\Users\Davide\Desktop\fine_tuned`

After a bit on desktop a new folder "fine_tuned" appear, after that i use the second command:

    `tflite_convert --saved_model_dir=C:\Users\Davide\Desktop\fine_tuned\saved_model --output_file=C:\Users\Davide\Desktop\mobilenet.tflite`

And the file appear on the desktop, the problem is that it's 1kb. When i try to use it inside my application i get this error:

        `java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.sd_detect/com.example.sd_detect.MainActivity}: java.lang.IllegalStateException: This model does not contain associated files, and is not a Zip file.`

  [1]: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md

output from tflite_convert

   ```
 2020-10-26 15:11:42.511698: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
    2020-10-26 15:11:42.511837: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
    2020-10-26 15:12:01.023376: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
    2020-10-26 15:12:01.023482: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
    2020-10-26 15:12:01.030610: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DESKTOP-II0SFO3
    2020-10-26 15:12:01.030829: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DESKTOP-II0SFO3
    2020-10-26 15:12:01.042164: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x17c13580870 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
    2020-10-26 15:12:01.042253: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
    I1026 15:14:04.769973  1808 lite.py:624] Using experimental converter: If you encountered a problem please file a bug. You can opt-out by setting experimental_new_converter=False
    2020-10-26 15:14:13.437234: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:313] Ignored output_format.
    2020-10-26 15:14:13.437349: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:316] Ignored drop_control_dependency.
    2020-10-26 15:14:13.439460: I tensorflow/cc/saved_model/reader.cc:31] Reading SavedModel from: C:\Users\Davide\Desktop\fine_tuned\saved_model
    2020-10-26 15:14:13.642525: I tensorflow/cc/saved_model/reader.cc:54] Reading meta graph with tags { serve }
    2020-10-26 15:14:13.642639: I tensorflow/cc/saved_model/loader.cc:250] Reading SavedModel debug info (if present) from: C:\Users\Davide\Desktop\fine_tuned\saved_model
    2020-10-26 15:14:14.428409: I tensorflow/cc/saved_model/loader.cc:215] Restoring SavedModel bundle.
    2020-10-26 15:14:16.534036: I tensorflow/cc/saved_model/loader.cc:199] Running initialization op on SavedModel bundle at path: C:\Users\Davide\Desktop\fine_tuned\saved_model
    2020-10-26 15:14:17.186241: I tensorflow/cc/saved_model/loader.cc:319] SavedModel load for tags { serve }; Status: success: OK. Took 3746762 microseconds.
```

**Comment by ravikyram** [comment]
@fanto88 

I have tried in TF nightly version and i am not seeing any issue. Please, find the gist here.Please, verify once and close the [issue](https://colab.research.google.com/gist/ravikyram/6a82614b71b7fe759099d3daee477d78/untitled94.ipynb?authuser=1).Thanks!

**Comment by fanto88** [comment]
Thanks for the comment. Now the model converted is 71mb, so it should be fine. But when i try to use it instead of the model used in the Android Example for object detection an exception occurs:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.sd_detect, PID: 23556
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.sd_detect/com.example.sd_detect.MainActivity}: java.lang.IllegalStateException: This model does not contain associated files, and is not a Zip file.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3374)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3513)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by ravikyram** [comment]
@fanto88 

Since the original issue was resolved. Can you please close this issue and create a new one by filling issue template.Thanks!

**Comment by fanto88** [comment]
Yeah, i will do it for sure. Thanks!

**Comment by brianestadimas** [comment]
@fanto88 could you please share your solution? i am having same issue using tflite_convert, i have tensorflow 2.3.0, object detection ssd_mobilenet_v1

**Comment by brianestadimas** [comment]
and it produces only 1kb file of tflite

**Comment by fanto88** [comment]
Like @ravikyram suggested, using the nighly version of TF fixed the problem automatically.

**Comment by Leci37** [comment]
You have to add metadata:

can you do it with mdata_write_all_in_tflite_FULL() funtion:

```python
# https://techzizou.com/build-android-app-for-custom-object-detection-using-tf2/#tf2_step21


# '''*********************************
#   FOR FULL INTEGER QUANTIZATION
# ************************************
# The internal quantization remains the same as previous float fallback quantization method,
# but you can see the input and output tensors here are also now integer format'''
import os
from tflite_support.metadata_writers import object_detector
from tflite_support import metadata
import flatbuffers
from tensorflow_lite_support.metadata import metadata_schema_py_generated as _metadata_fb
from tensorflow_lite_support.metadata.python import metadata as _metadata
from tensorflow_lite_support.metadata.python.metadata_writers import writer_utils

PATH_MODEL = "escarabajo"
_MODEL_PATH = PATH_MODEL+"/model_G3.tflite"
_LABEL_FILE = "model_cat_dog_zombie/mscoco_label_map.pbtxt"
_SAVE_TO_PATH = _MODEL_PATH.replace("model_G3", "model_mdata_G3")

def mdata_write_all_in_tflite_SIMPLE(MODEL_PATH_LITE, SAVE_TO_PATH_LITE, LABEL_FILE ):
    writer = object_detector.MetadataWriter.create_for_inference(
        writer_utils.load_file(MODEL_PATH_LITE), input_norm_mean=[127.5],
        input_norm_std=[127.5], label_file_paths=[LABEL_FILE])
    writer_utils.save_file(writer.populate(), SAVE_TO_PATH_LITE)

    print("saved! SIMPLE SAVE_TO_PATH: ", SAVE_TO_PATH_LITE)

ObjectDetectorWriter = object_detector.MetadataWriter

def mdata_write_all_in_tflite_FULL(MODEL_PATH_LITE, SAVE_TO_PATH_LITE, LABEL_FILE ):
    print("MODEL_PATH: ", MODEL_PATH_LITE)
    writer = ObjectDetectorWriter.create_for_inference(
        writer_utils.load_file(MODEL_PATH_LITE), [127.5], [127.5], [LABEL_FILE])
    writer_utils.save_file(writer.populate(), SAVE_TO_PATH_LITE)
    # Verify the populated metadata and associated files.
    displayer = metadata.MetadataDisplayer.with_model_file(SAVE_TO_PATH_LITE)
    print("Metadata populated:")
    print(displayer.get_metadata_json())
    print("Associated file(s) populated:")
    print(displayer.get_packed_associated_file_list())
    model_meta = _metadata_fb.ModelMetadataT()
    model_meta.name = "SSD_Detector: " + MODEL_PATH_LITE
    model_meta.description = (MODEL_PATH_LITE+
        "Identify which of a known set of objects might be present and provide "
        "information about their positions within the given image or a video "
        "stream.")
    # Creates input info.
    input_meta = _metadata_fb.TensorMetadataT()
    input_meta.name = "image"
    input_meta.content = _metadata_fb.ContentT()
    input_meta.content.contentProperties = _metadata_fb.ImagePropertiesT()
    input_meta.content.contentProperties.colorSpace = (
        _metadata_fb.ColorSpaceType.RGB)
    input_meta.content.contentPropertiesType = (
        _metadata_fb.ContentProperties.ImageProperties)
    input_normalization = _metadata_fb.ProcessUnitT()
    input_normalization.optionsType = (
        _metadata_fb.ProcessUnitOptions.NormalizationOptions)
    input_normalization.options = _metadata_fb.NormalizationOptionsT()
    input_normalization.options.mean = [127.5]
    input_normalization.options.std = [127.5]
    input_meta.processUnits = [input_normalization]
    input_stats = _metadata_fb.StatsT()
    input_stats.max = [255]
    input_stats.min = [0]
    input_meta.stats = input_stats
    # Creates outputs info.
    #LOCATION
    output_location_meta = _metadata_fb.TensorMetadataT()
    output_location_meta.name = "location"
    output_location_meta.description = "The LOCATIONS of the detected boxes."
    output_location_meta.content = _metadata_fb.ContentT()
    output_location_meta.content.contentPropertiesType = (
        _metadata_fb.ContentProperties.BoundingBoxProperties)
    output_location_meta.content.contentProperties = (
        _metadata_fb.BoundingBoxPropertiesT())
    output_location_meta.content.contentProperties.index = [1, 0, 3, 2]
    output_location_meta.content.contentProperties.type = (
        _metadata_fb.BoundingBoxType.BOUNDARIES)
    output_location_meta.content.contentProperties.coordinateType = (
        _metadata_fb.CoordinateType.RATIO)
    output_location_meta.content.range = _metadata_fb.ValueRangeT()
    output_location_meta.content.range.min = 2
    output_location_meta.content.range.max = 2
    # CATEGORY
    output_class_meta = _metadata_fb.TensorMetadataT()
    output_class_meta.name = "category"
    output_class_meta.description = "The CATEGORIES of the detected boxes."
    output_class_meta.content = _metadata_fb.ContentT()
    output_class_meta.content.contentPropertiesType = (
        _metadata_fb.ContentProperties.FeatureProperties)
    output_class_meta.content.contentProperties = (
        _metadata_fb.FeaturePropertiesT())
    output_class_meta.content.range = _metadata_fb.ValueRangeT()
    output_class_meta.content.range.min = 2
    output_class_meta.content.range.max = 2
    #LABEL MAP
    label_file = _metadata_fb.AssociatedFileT()
    label_file.name = os.path.basename("tflite_label_map.txt")
    label_file.description = "Label of objects that this model can recognize."
    label_file.type = _metadata_fb.AssociatedFileType.TENSOR_VALUE_LABELS
    output_class_meta.associatedFiles = [label_file]
    #SCORE
    output_score_meta = _metadata_fb.TensorMetadataT()
    output_score_meta.name = "score"
    output_score_meta.description = "The SCORE of the detected boxes."
    output_score_meta.content = _metadata_fb.ContentT()
    output_score_meta.content.contentPropertiesType = (
        _metadata_fb.ContentProperties.FeatureProperties)
    output_score_meta.content.contentProperties = (
        _metadata_fb.FeaturePropertiesT())
    output_score_meta.content.range = _metadata_fb.ValueRangeT()
    output_score_meta.content.range.min = 2
    output_score_meta.content.range.max = 2
    #NUMBER OF DETECTIONS
    output_number_meta = _metadata_fb.TensorMetadataT()
    output_number_meta.name = "number of detections"
    output_number_meta.description = "The NUMber of the detected boxes."
    output_number_meta.content = _metadata_fb.ContentT()
    output_number_meta.content.contentPropertiesType = (
        _metadata_fb.ContentProperties.FeatureProperties)
    output_number_meta.content.contentProperties = (
        _metadata_fb.FeaturePropertiesT())

    # Creates subgraph info.
    group = _metadata_fb.TensorGroupT()
    group.name = "detection result"
    group.tensorNames = [
        output_location_meta.name, output_class_meta.name,
        output_score_meta.name
    ]
    subgraph = _metadata_fb.SubGraphMetadataT()
    subgraph.inputTensorMetadata = [input_meta]
    subgraph.outputTensorMetadata = [
        output_location_meta, output_class_meta, output_score_meta,
        output_number_meta
    ]
    subgraph.outputTensorGroups = [group]
    model_meta.subgraphMetadata = [subgraph]
    b = flatbuffers.Builder(0)
    b.Finish(
        model_meta.Pack(b),
        _metadata.MetadataPopulator.METADATA_FILE_IDENTIFIER)
    metadata_buf = b.Output()
    print("saved! FULL SAVE_TO_PATH: ", SAVE_TO_PATH_LITE)



def log_metadata_info_tflite(save_path):
    displayer = metadata.MetadataDisplayer.with_model_file(save_path)
    str_matadata = displayer.get_metadata_json()
    with open(save_path.replace(".tflite", "_mdata.json"), 'w') as filetowrite:
        filetowrite.write(str_matadata)
    print("Metadata populated in :", save_path.replace(".tflite", "_mdata.json"))


```
