### ISSUE TITLE
tensorflow read multi-type csv error

### ISSUE THREAD

**Issue by ericyue** [tensorflow/tensorflow#4441]
my csv file has 10 column, CONTINUOUS_COLUMNS are  float , and left are string.
my code : 
`parse_fn = lambda example:tf.decode_csv(example, [tf.constant([], dtype=tf.float32) if i in CONTINUOUS_COLUMNS else tf.constant([], dtype=tf.string)  for i in COLUMNS ]  ,field_delim='\t' )`
`inputs = tf.contrib.learn.read_batch_examples([FLAGS.train], 256, tf.TextLineReader,num_epochs=1,queue_capacity=10000, parse_fn=parse_fn)`

error 
`Traceback (most recent call last):
  File "wide-batch.py", line 241, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "wide-batch.py", line 238, in main
    train_and_eval()
  File "wide-batch.py", line 232, in train_and_eval
    m.fit(input_fn=lambda: input_fn(stat), steps=FLAGS.train_steps,monitors=[validation_monitor])
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 240, in fit
    max_steps=max_steps)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 548, in _train_model
    features, targets = input_fn()
  File "wide-batch.py", line 232, in <lambda>
    m.fit(input_fn=lambda: input_fn(stat), steps=FLAGS.train_steps,monitors=[validation_monitor])
  File "wide-batch.py", line 180, in input_fn
    inputs = tf.contrib.learn.read_batch_examples([FLAGS.train], 256, tf.TextLineReader,num_epochs=1,queue_capacity=10000, parse_fn=parse_fn)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_io/graph_io.py", line 82, in read_batch_examples
    read_batch_size=read_batch_size, parse_fn=parse_fn, name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_io/graph_io.py", line 210, in read_keyed_batch_examples
    allow_smaller_final_batch=allow_smaller_final_batch)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 899, in shuffle_batch_join
    tensor_list_list = _validate_join(tensor_list_list)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 421, in _validate_join
    for tl in tensor_list_list]
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 737, in convert_n_to_tensor_or_indexed_slices
    as_ref=as_ref))
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 698, in convert_to_tensor_or_indexed_slices
    return convert_to_tensor(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 621, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 630, in _autopacking_conversion_function
    return _autopacking_helper(v, inferred_dtype, name or "packed")
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 572, in _autopacking_helper
    "%s to %s (Tensor is: %r)" % (elem.dtype, dtype, elem))
TypeError: Cannot convert a list containing a tensor of dtype <dtype: 'string'> to <dtype: 'float32'> (Tensor is: <tf.Tensor 'read_batch_examples/read/DecodeCSV:1' shape=() dtype=string>)`

**Comment by jmchen-g** [comment]
Can you follow the example here and see if it works for you? http://stackoverflow.com/questions/37091899/how-to-actually-read-csv-data-in-tensorflow

**Comment by aselle** [comment]
Closing automatically due to lack of recent activity. Please reopen when further information becomes available. Thank you.

**Comment by RohinMohanadas** [comment]
I would think this makes more sense : https://stackoverflow.com/questions/43674569/is-there-a-general-way-to-set-the-record-defaults-for-tf-decode-csv
