### ISSUE TITLE
Install tensorflow in python 3

### ISSUE THREAD

**Issue by RarDay** [tensorflow/tensorflow#44546]
Hello!
I have easy question, how i can install tensorflow?

Required Info |  
-- | --
Operating System | Ubuntu 18.04
Language | Python 3.6
Platform | NVIDIA Jetson Nano
CPU | Quad-core ARM A57
GPU | 128-core Maxwell

### Issue Description
I performed a million actions in the console and now I'm at this stage:
pip3 install tensorflow => no error
import tensorflow => 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /usr/local/lib/python3.6/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so: invalid ELF header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /usr/local/lib/python3.6/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so: invalid ELF header

Failed to load the native TensorFlow runtime.
```

**Comment by Saduf2019** [comment]
@RarDay 
Please [verify](https://github.com/tensorflow/tensorflow/issues/1711#issuecomment-207794680) if you have installed the correct version,please let us know the tf version used.
Just to verify did you follow the instructions in [tensorflow website](https://www.tensorflow.org/install/source?hl=en) . Please, see tested build configurations from [here](https://www.tensorflow.org/install/source?hl=en#tested_build_configurations).
Please refer to: #38552 [link](https://github.com/tensorflow/tensorflow/issues/25315),

**Comment by RarDay** [comment]
I have:
```
tensorboard==1.12.2
tensorflow @ https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.3.0-py3-none-any.whl
tensorflow-estimator==1.13.0
tensorflow-gpu==1.13.1+nv19.3
tensorflow-tensorboard==0.1.8
tensorrt==7.1.3.0
```

**Comment by mihaimaruseac** [comment]
1.13 is too old. I'd suggest starting a new virtual environment and installing at least 1.15.

**Comment by Saduf2019** [comment]
@RarDay
Could you please install 1.15 and update us.
