### ISSUE TITLE
" ImportError: cannot import name 'anchor_generator_pb2' from 'object_detection.protos' " when trying to convert a custom model for use in the Object Detection Android example app

### ISSUE THREAD

**Issue by LucasStromberg** [tensorflow/tensorflow#44554]
Hi, I'm want to use the Android example app for Object Detection with a model with greater resolution than the standard 300x300. I have downloaded the **ssd_resnet_50_fpn_coco** model from [https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md](url), and I'm following the guide in the section _Custom model used_ on [https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android](url).

When running:
`python object_detection/export_tflite_ssd_graph.py --pipeline_config_path ssd_resnet50_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03/pipeline.config --trained_checkpoint_prefix ssd_resnet50_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03/model.ckpt --output_directory exported_model`

I get the output:
`2020-11-03 15:25:55.004086: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2020-11-03 15:25:55.009217: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "object_detection/export_tflite_ssd_graph.py", line 97, in <module>
    from object_detection import export_tflite_ssd_graph_lib
  File "C:\Users\Lucas\.conda\envs\python37\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\export_tflite_ssd_graph_lib.py", line 27, in <module>
    from object_detection import exporter
  File "C:\Users\Lucas\.conda\envs\python37\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\exporter.py", line 24, in <module>
    from object_detection.builders import model_builder
  File "C:\Users\Lucas\.conda\envs\python37\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\builders\model_builder.py", line 20, in <module>
    from object_detection.builders import anchor_generator_builder
  File "C:\Users\Lucas\.conda\envs\python37\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\builders\anchor_generator_builder.py", line 27, in <module>
    from object_detection.protos import anchor_generator_pb2
ImportError: cannot import name 'anchor_generator_pb2' from 'object_detection.protos' (C:\Users\Lucas\.conda\envs\python37\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\protos\__init__.py)`

I have also tried this with the model **ssd_mobilenet_v2_oid_v4** as mentioned in the guide, which yields the same output.

Some extra info:
- Windows 10
- Python 3.7.9
- Tensorflow 1.15.0

**Comment by LucasStromberg** [comment]
Okay, I was able to solve this problem by downloading **proto.exe** from [https://github.com/protocolbuffers/protobuf/releases/tag/v3.13.0](url), placing it in /models/research/ and in there run:

`protoc object_detection/protos/*.proto --python_out=.
cp object_detection/packages/tf2/setup.py .`

I then can go to the next step in the guide and run:

`tflite_convert --input_shape=1,640,640,3 --input_arrays=normalized_input_image_tensor --output_arrays=TFLite_Detection_PostProcess,TFLite_Detection_PostProcess:1,TFLite_Detection_PostProcess:2,TFLite_Detection_PostProcess:3 --allow_custom_ops --graph_def_file=exported_model/tflite_graph.pb --output_file=export/detect.tflite`

This generates the model detect.tflite, which I can then place in the assets folder of the Android app.

I then also change:
`private static final int TF_OD_API_INPUT_SIZE = 300;`
to
`private static final int TF_OD_API_INPUT_SIZE = 640;`

and
`private static final boolean TF_OD_API_IS_QUANTIZED = true;`
to
`private static final boolean TF_OD_API_IS_QUANTIZED = false;`

However when deploying the app I now get the error:

`java.lang.IllegalStateException: This model does not contain associated files, and is not a Zip file.`

Full error log:

`2020-11-03 15:54:25.008 14893-14893/org.tensorflow.lite.examples.detection E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.tensorflow.lite.examples.detection, PID: 14893
    java.lang.IllegalStateException: This model does not contain associated files, and is not a Zip file.
        at org.tensorflow.lite.support.metadata.MetadataExtractor.assertZipFile(MetadataExtractor.java:325)
        at org.tensorflow.lite.support.metadata.MetadataExtractor.getAssociatedFile(MetadataExtractor.java:165)
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.create(TFLiteObjectDetectionAPIModel.java:126)
        at org.tensorflow.lite.examples.detection.DetectorActivity.onPreviewSizeChosen(DetectorActivity.java:99)
        at org.tensorflow.lite.examples.detection.CameraActivity$7.onPreviewSizeChosen(CameraActivity.java:446)
        at org.tensorflow.lite.examples.detection.CameraConnectionFragment.setUpCameraOutputs(CameraConnectionFragment.java:357)
        at org.tensorflow.lite.examples.detection.CameraConnectionFragment.openCamera(CameraConnectionFragment.java:362)
        at org.tensorflow.lite.examples.detection.CameraConnectionFragment.access$300(CameraConnectionFragment.java:66)
        at org.tensorflow.lite.examples.detection.CameraConnectionFragment$3.onSurfaceTextureAvailable(CameraConnectionFragment.java:171)
        at android.view.TextureView.getTextureLayer(TextureView.java:415)
        at android.view.TextureView.draw(TextureView.java:360)
        at android.view.View.updateDisplayListIfDirty(View.java:21335)
        at android.view.View.draw(View.java:22200)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
        at android.view.View.updateDisplayListIfDirty(View.java:21326)
        at android.view.View.draw(View.java:22200)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
        at android.view.View.updateDisplayListIfDirty(View.java:21326)
        at android.view.View.draw(View.java:22200)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
        at android.view.View.draw(View.java:22484)
        at android.view.View.updateDisplayListIfDirty(View.java:21335)
        at android.view.View.draw(View.java:22200)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1246)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
        at android.view.View.draw(View.java:22484)
        at android.view.View.updateDisplayListIfDirty(View.java:21335)
        at android.view.View.draw(View.java:22200)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
        at android.view.View.updateDisplayListIfDirty(View.java:21326)
        at android.view.View.draw(View.java:22200)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
        at android.view.View.updateDisplayListIfDirty(View.java:21326)
        at android.view.View.draw(View.java:22200)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
        at android.view.View.updateDisplayListIfDirty(View.java:21326)
        at android.view.View.draw(View.java:22200)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
        at android.view.View.updateDisplayListIfDirty(View.java:21326)
        at android.view.View.draw(View.java:22200)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
        at android.view.View.draw(View.java:22484)
        at com.android.internal.policy.DecorView.draw(DecorView.java:812)
        at android.view.View.updateDisplayListIfDirty(View.java:21335)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:647)
2020-11-03 15:54:25.008 14893-14893/org.tensorflow.lite.examples.detection E/AndroidRuntime:     at android.view.ViewRootImpl.draw(ViewRootImpl.java:4332)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4059)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3312)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2151)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8614)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1316)
        at android.view.Choreographer.doCallbacks(Choreographer.java:1113)
        at android.view.Choreographer.doFrame(Choreographer.java:1013)
        at android.view.Choreographer$FrameHandler.handleMessage(Choreographer.java:1239)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:245)
        at android.app.ActivityThread.main(ActivityThread.java:7945)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)`

I found that a similar problem exists in the issue: [https://github.com/tensorflow/tensorflow/issues/44431](url). Maybe this is the same problem, I'm not sure. Either way that issue is not yet solved, and it seems weird to get this error when exactly following the official guide for using custom models for the Android app.

**Comment by LucasStromberg** [comment]
I found a workaround by following this:
[https://github.com/tensorflow/models/issues/9341](url)

Now I no longer get any crash when using the app. However, I don't get any inference results at all. No bounding boxes. 
Example log:
`2020-11-03 16:33:24.408 23251-25655/org.tensorflow.lite.examples.detection I/tensorflow: DetectorActivity: Preparing image 423 for detection in bg thread.
2020-11-03 16:33:24.476 23251-25654/org.tensorflow.lite.examples.detection I/tensorflow: DetectorActivity: Running detection on image 423
2020-11-03 16:33:26.413 23251-25654/org.tensorflow.lite.examples.detection I/tensorflow: MultiBoxTracker: Processing 0 results from 423`

Note that this is using the **ssd_resnet_50_fpn_coco** model. When I use the **ssd_mobilenet_v2_oid_v4** model as in the example, I actually get bounding boxes, but these seem to have the wrong labels, even though I added the label map as described in the example.

As I need to use high-resolution inference, why could this problem occur?

**Comment by srjoglekar246** [comment]
Can you share the labels file you are using to test the second model. One thing that causes issues is that the first label from COCO's list is a 'null' one, so you might just need to add a dummy label on the first line in your labels file.

**Comment by LucasStromberg** [comment]
I'm using the same labels as for the original model.
[labelmap.txt](https://github.com/tensorflow/tensorflow/files/5500276/labelmap.txt)

But I believe I figured out a solution by following the recently solved topic I linked above:
https://github.com/tensorflow/tensorflow/issues/44431

I changed the mean and standard deviation for the model in the **TFLiteObjectDetectionAPIModel.java** file to:

`private static final float IMAGE_MEAN = 0f;
private static final float IMAGE_STD = 1f`

and now I get bounding boxes!

However the inference is terribly slow. I learned that mobilenet is supposed to be faster than resnet, so now I'm using the _ssd_mobilenet_v1_fpn_coco ☆_ model (640x640) instead. However inference takes approximately 1.5s on my phone, as compared to just 20ms for the standard 300x300 model...

**Comment by srjoglekar246** [comment]
I see. 
Yeah the inference latency is expected. Can you try the [GPU delegate](https://www.tensorflow.org/lite/performance/gpu) for your use-case? We have seen much better latencies with acceleration.

**Comment by LucasStromberg** [comment]
I have not tried that yet. Might do so soon!

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
