### ISSUE TITLE
tensorflow.python.framework.errors_impl.UnknownError: Access is denied.

### ISSUE THREAD

**Issue by fanto88** [tensorflow/tensorflow#44596]
Hi again!

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary):  binary i think
- TensorFlow version: 2.5.0-dev20201028
- Python version: Python 3.8.3
- Installed using virtualenv? pip? conda?: pip

**Describe the problem**
I can't train the model to recognize custom object.

```
So, my structure folder is like these:
-SistemiDigitali
    - ImageCollector
        - images
             - test
                    -images with xml file
             - train
                    -images with xml file
             - test.record
             - test_labels.csv
             - train.record
             - train_labels.csv
    - model (the folder where tensorflow model is located)
    - models-master (folder from git cloning the models repo)

```

So i have changed the pipeline inside model like this:
```

model {
  ssd {
    num_classes: 1
    image_resizer {
      fixed_shape_resizer {
        height: 320
        width: 320
      }
    }
    feature_extractor {
      type: "ssd_mobilenet_v2_fpn_keras"
      depth_multiplier: 1.0
      min_depth: 16
      conv_hyperparams {
        regularizer {
          l2_regularizer {
            weight: 3.9999998989515007e-05
          }
        }
        initializer {
          random_normal_initializer {
            mean: 0.0
            stddev: 0.009999999776482582
          }
        }
        activation: RELU_6
        batch_norm {
          decay: 0.996999979019165
          scale: true
          epsilon: 0.0010000000474974513
        }
      }
      use_depthwise: true
      override_base_feature_extractor_hyperparams: true
      fpn {
        min_level: 3
        max_level: 7
        additional_layer_depth: 128
      }
    }
    box_coder {
      faster_rcnn_box_coder {
        y_scale: 10.0
        x_scale: 10.0
        height_scale: 5.0
        width_scale: 5.0
      }
    }
    matcher {
      argmax_matcher {
        matched_threshold: 0.5
        unmatched_threshold: 0.5
        ignore_thresholds: false
        negatives_lower_than_unmatched: true
        force_match_for_each_row: true
        use_matmul_gather: true
      }
    }
    similarity_calculator {
      iou_similarity {
      }
    }
    box_predictor {
      weight_shared_convolutional_box_predictor {
        conv_hyperparams {
          regularizer {
            l2_regularizer {
              weight: 3.9999998989515007e-05
            }
          }
          initializer {
            random_normal_initializer {
              mean: 0.0
              stddev: 0.009999999776482582
            }
          }
          activation: RELU_6
          batch_norm {
            decay: 0.996999979019165
            scale: true
            epsilon: 0.0010000000474974513
          }
        }
        depth: 128
        num_layers_before_predictor: 4
        kernel_size: 3
        class_prediction_bias_init: -4.599999904632568
        share_prediction_tower: true
        use_depthwise: true
      }
    }
    anchor_generator {
      multiscale_anchor_generator {
        min_level: 3
        max_level: 7
        anchor_scale: 4.0
        aspect_ratios: 1.0
        aspect_ratios: 2.0
        aspect_ratios: 0.5
        scales_per_octave: 2
      }
    }
    post_processing {
      batch_non_max_suppression {
        score_threshold: 9.99999993922529e-09
        iou_threshold: 0.6000000238418579
        max_detections_per_class: 100
        max_total_detections: 100
        use_static_shapes: false
      }
      score_converter: SIGMOID
    }
    normalize_loss_by_num_matches: true
    loss {
      localization_loss {
        weighted_smooth_l1 {
        }
      }
      classification_loss {
        weighted_sigmoid_focal {
          gamma: 2.0
          alpha: 0.25
        }
      }
      classification_weight: 1.0
      localization_weight: 1.0
    }
    encode_background_as_zeros: true
    normalize_loc_loss_by_codesize: true
    inplace_batchnorm_update: true
    freeze_batchnorm: false
  }
}
train_config {
  batch_size: 128
  data_augmentation_options {
    random_horizontal_flip {
    }
  }
  data_augmentation_options {
    random_crop_image {
      min_object_covered: 0.0
      min_aspect_ratio: 0.75
      max_aspect_ratio: 3.0
      min_area: 0.75
      max_area: 1.0
      overlap_thresh: 0.0
    }
  }
  sync_replicas: true
  optimizer {
    momentum_optimizer {
      learning_rate {
        cosine_decay_learning_rate {
          learning_rate_base: 0.07999999821186066
          total_steps: 50000
          warmup_learning_rate: 0.026666000485420227
          warmup_steps: 1000
        }
      }
      momentum_optimizer_value: 0.8999999761581421
    }
    use_moving_average: false
  }
  fine_tune_checkpoint: "D:/Davide/Uni/SistemiDigitali/model/checkpoint/ckpt-0"
  num_steps: 50000
  startup_delay_steps: 0.0
  replicas_to_aggregate: 8
  max_number_of_boxes: 100
  unpad_groundtruth_tensors: false
  fine_tune_checkpoint_type: "detection"
  fine_tune_checkpoint_version: V2
}
train_input_reader {
  label_map_path: "D:/Davide/Uni/SistemiDigitali/ImageCollector/label_map.pbtxt"
  tf_record_input_reader {
    input_path: "D:/Davide/Uni/SistemiDigitali/ImageCollector/images/train.record"
  }
}
eval_config {
  metrics_set: "coco_detection_metrics"
  use_moving_averages: false
}
eval_input_reader {
  label_map_path: "D:/Davide/Uni/SistemiDigitali/ImageCollector/label_map.pbtxt"
  shuffle: false
  num_epochs: 1
  tf_record_input_reader {
    input_path: "D:/Davide/Uni/SistemiDigitali/ImageCollector/images/test.record"
  }
}
```

But when i run this command:

`python models-master/research/object_detection/model_main_tf2.py --pipeline_config_path=model/pipeline.config --model_dir=model --alsologtostderr`

I get this exception

```
WARNING:tensorflow:model\checkpoint: Checkpoint ignored
W1104 21:34:18.945756  6844 checkpoint_management.py:296] model\checkpoint: Checkpoint ignored
Traceback (most recent call last):
  File "models-master/research/object_detection/model_main_tf2.py", line 113, in <module>
    tf.compat.v1.app.run()
  File "C:\Users\Davide\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\Davide\AppData\Local\Programs\Python\Python38\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\Users\Davide\AppData\Local\Programs\Python\Python38\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "models-master/research/object_detection/model_main_tf2.py", line 104, in main
    model_lib_v2.train_loop(
  File "C:\Users\Davide\AppData\Local\Programs\Python\Python38\lib\site-packages\object_detection-0.1-py3.8.egg\object_detection\model_lib_v2.py", line 630, in train_loop
    manager.save()
  File "C:\Users\Davide\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\training\checkpoint_management.py", line 824, in save
    self._record_state()
  File "C:\Users\Davide\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\training\checkpoint_management.py", line 727, in _record_state
    update_checkpoint_state_internal(
  File "C:\Users\Davide\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\training\checkpoint_management.py", line 247, in update_checkpoint_state_internal
    file_io.atomic_write_string_to_file(coord_checkpoint_filename,
  File "C:\Users\Davide\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 573, in atomic_write_string_to_file
    rename(temp_pathname, filename, overwrite)
  File "C:\Users\Davide\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 532, in rename
    rename_v2(oldname, newname, overwrite)
  File "C:\Users\Davide\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 548, in rename_v2
    _pywrap_file_io.RenameFile(
tensorflow.python.framework.errors_impl.UnknownError: Failed to rename: model\checkpoint.tmp2ddac8459ee545f28c333f066a5292cc to: model\checkpoint : Access is denied.
; Input/output error
```

**Comment by fanto88** [comment]
I'm sorry about that. I have actually solved the problem.

Now i get this output:

```
INFO:tensorflow:Step 100 per-step time 2.474s loss=0.629
I1105 00:47:38.029456 12864 model_lib_v2.py:649] Step 100 per-step time 2.474s loss=0.629
```
So i suppose everything is fine. The error was that i didn't understand how everything worked. I had to copy pipeline.config inside a new folder, and this is where the new model will be created. Instead of doing so i edited the pipeline.config of the model i have downloaded from internet and i gave that pipeline.config and folder to the training script.

**Comment by amahendrakar** [comment]
@fanto88,
Is this still an issue? Please feel free to close the issue if resolved. Thanks!

**Comment by RMC-G** [comment]
> I'm sorry about that. I have actually solved the problem.
> 
> Now i get this output:
> 
> ```
> INFO:tensorflow:Step 100 per-step time 2.474s loss=0.629
> I1105 00:47:38.029456 12864 model_lib_v2.py:649] Step 100 per-step time 2.474s loss=0.629
> ```
> 
> So i suppose everything is fine. The error was that i didn't understand how everything worked. I had to copy pipeline.config inside a new folder, and this is where the new model will be created. Instead of doing so i edited the pipeline.config of the model i have downloaded from internet and i gave that pipeline.config and folder to the training script.

I have this issue and can't figure it out can you please explain how you solved it, as i am confused by your file structure
