### ISSUE TITLE
TypeError: An op outside of the function building code is being passed

### ISSUE THREAD

**Issue by charlet-antoine** [tensorflow/tensorflow#44631]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution: MacOs Catalina 10.15
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from: pip
- TensorFlow version: v2.3.0-54-gfcc4b966f1 2.3.1
- Python version: 3.7.7

**Describe the current behavior**
The modelCheckpoint callback seems to trigger the issue, everything run smoothly without it. 

**Standalone code to reproduce the issue**

```
import pandas as pd
import numpy as np
import os
import time

import tensorflow as tf
import tensorflow_hub as hub

def make_dataset(path, n_samples):
    df = pd.read_csv(path, usecols=[6,9], nrows=n_samples)
    df.columns = ['ratings', 'title']

    text = df['title'].tolist()
    text = [str(t).encode('ascii', 'replace') for t in text]
    text = np.array(text, dtype='object')[:]

    labels = df['ratings'].tolist()
    labels = [1 if i>= 4 else 0 if i == 3 else -1 for i in labels]

    labels = np.array(pd.get_dummies(labels), dtype=int)[:]

    return labels, text


def get_model():
    embed = hub.KerasLayer("https://tfhub.dev/google/nnlm-en-dim50/1",
     output_shape=[50],
     input_shape=[],
     dtype=tf.string,
     name='input',
     trainable=False)

    model = tf.keras.Sequential()
    model.add(embed)
    model.add(tf.keras.layers.Dense(16, activation='relu'))
    model.add(tf.keras.layers.Dense(3, activation='softmax', name='output'))
    model.compile(loss='categorical_crossentropy', optimizer='Adam', metrics=['acc'])
    model.summary()
    return model

def train(epochs=5, bs=32):
    y_train, x_train = make_dataset('reviews_train.csv', n_samples=100000)
    y_val, x_val = make_dataset('reviews_test.csv', n_samples=10000)
    model_checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(
                                filepath='model_checkpoint',
                                save_weights_only=False,
                                monitor='val_acc',
                                mode='max',
                                save_best_only=True)
    model = get_model()
    model.fit(x_train, y_train, batch_size=bs, epochs=epochs, verbose=1,
         validation_data=(x_val, y_val),
         callbacks=[model_checkpoint_callback])



if __name__ == "__main__":
    train()

```
**Other info / logs** 
`Traceback (most recent call last):
  File "train.py", line 58, in <module>
    train()
  File "train.py", line 53, in train
    callbacks=[model_checkpoint_callback])
  File "/Users/antoine/.virtualenvs/amazon-review/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/Users/antoine/.virtualenvs/amazon-review/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1137, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/Users/antoine/.virtualenvs/amazon-review/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 412, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/Users/antoine/.virtualenvs/amazon-review/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 1249, in on_epoch_end
    self._save_model(epoch=epoch, logs=logs)
  File "/Users/antoine/.virtualenvs/amazon-review/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 1301, in _save_model
    self.model.save(filepath, overwrite=True, options=self._options)
  File "/Users/antoine/.virtualenvs/amazon-review/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1979, in save
    signatures, options)
  File "/Users/antoine/.virtualenvs/amazon-review/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py", line 134, in save_model
    signatures, options)
  File "/Users/antoine/.virtualenvs/amazon-review/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/save.py", line 80, in save
    save_lib.save(model, filepath, signatures, options)
  File "/Users/antoine/.virtualenvs/amazon-review/lib/python3.7/site-packages/tensorflow/python/saved_model/save.py", line 985, in save
    options=ckpt_options)
  File "/Users/antoine/.virtualenvs/amazon-review/lib/python3.7/site-packages/tensorflow/python/training/tracking/util.py", line 1200, in save
    file_prefix_tensor, object_graph_tensor, options)
  File "/Users/antoine/.virtualenvs/amazon-review/lib/python3.7/site-packages/tensorflow/python/training/tracking/util.py", line 1145, in _save_cached_when_graph_building
    save_op = saver.save(file_prefix, options=options)
  File "/Users/antoine/.virtualenvs/amazon-review/lib/python3.7/site-packages/tensorflow/python/training/saving/functional_saver.py", line 293, in save
    tf_function_save()
  File "/Users/antoine/.virtualenvs/amazon-review/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/Users/antoine/.virtualenvs/amazon-review/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 846, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "/Users/antoine/.virtualenvs/amazon-review/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/Users/antoine/.virtualenvs/amazon-review/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/Users/antoine/.virtualenvs/amazon-review/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/Users/antoine/.virtualenvs/amazon-review/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 75, in quick_execute
    raise e
  File "/Users/antoine/.virtualenvs/amazon-review/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: embeddings/part_0/Read/ReadVariableOp:0`

**Comment by ravikyram** [comment]
@charlet-antoine 

Please, provide colab link or simple standalone code snippet with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by charlet-antoine** [comment]
@ravikyram 
Hi there, you can git clone the mini project on your local:
https://github.com/charlet-antoine/tensorflow-serving-exemple.git

**Comment by ravikyram** [comment]
@charlet-antoine 

I have tried in colab with TF version 2.3 and nightly version(`2.5.0-dev20201109`) and was able to reproduce the issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/c64fcae0bc93c8abeba883b2cfcb5513/untitled497.ipynb).
This issue is more suitable for TensorFlow Hub repo. Please post it on hub repo from [here](https://github.com/tensorflow/hub/issues/new). Thanks!
