### ISSUE TITLE
AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'swapaxes'

### ISSUE THREAD

**Issue by NaghmehShahverdi** [tensorflow/tensorflow#44645]
I am building a CNN model. model compile fine but when i fit the model it does not work: The code fine in my jupyttor but not in kaggle
#metric

```
def iou_metric_batch(y_true_in, y_pred_in):
    batch_size = y_true_in.shape[0]
    metric = []
    for batch in range(batch_size):
        value = iou_metric(y_true_in[batch], y_pred_in[batch])
        metric.append(value)
    return np.array(np.mean(metric), dtype=np.float32)

def my_iou_metric(label, pred):
    metric_value = tf.py_function(iou_metric_batch, [label, pred], tf.float32)
    return metric_value

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=[my_iou_metric])
tf.compat.v1.disable_eager_execution()
model_path = "nuclei_finder_unet_1.h5"

checkpoint = ModelCheckpoint(model_path,
                             monitor="val_loss",
                             mode="min",
                             save_best_only = True,
                             verbose=1)

earlystop = EarlyStopping(monitor = 'val_loss', 
                          min_delta = 0, 
                          patience = 5,
                          verbose = 1,
                          restore_best_weights = True)

# Fit our model 
results = model.fit(X_train, Y_train, validation_split=0.1,
                    batch_size=16, epochs=10,callbacks=[earlystop, checkpoint])



```Erroe:
```
nknownError: AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'swapaxes'
Traceback (most recent call last):

  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 242, in __call__
    stateful=None,

  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 131, in __call__
    """

  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 302, in wrapper

  File "<ipython-input-99-1bbcb510438c>", line 58, in iou_metric_batch
    value = iou_metric(y_true_in[batch], y_pred_in[batch])

  File "<ipython-input-99-1bbcb510438c>", line 2, in iou_metric
    labels = label(y_true_in > 0.5)

  File "/opt/conda/lib/python3.7/site-packages/skimage/measure/_label.py", line 93, in label
    return clabel(input, neighbors, background, return_num, connectivity)

  File "skimage/measure/_ccomp.pyx", line 348, in skimage.measure._ccomp.label_cython

  File "skimage/measure/_ccomp.pyx", line 322, in skimage.measure._ccomp.reshape_array

  File "skimage/measure/_ccomp.pyx", line 299, in skimage.measure._ccomp._apply_swaps

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'swapaxes'

	 [[{{node metrics_10/my_iou_metric/EagerPyFunc}}]]
```

**Comment by Saduf2019** [comment]
@NaghmehShahverdi 
Please share the tf version used, i ran the code shared and face a [different issue](https://colab.research.google.com/gist/Saduf2019/d6341c5809b9c1e823e6cccdd5bbb2e0/untitled458.ipynb).
