### ISSUE TITLE
Python/Django

### ISSUE THREAD

**Issue by ImJustError** [tensorflow/tensorflow#44647]
I just wanted to make a new application on Django. There were no problems during installation. But when I decided to create a new project, I received an unknown error. I didn’t find a solution in google. Here is what I wrote: 

_django-admin startproject mysite_

This is what it gave me:

 _Traceback (most recent call last):
  File "c:\users\danii\appdata\local\programs\python\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\danii\appdata\local\programs\python\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\danii\AppData\Local\Programs\Python\Python38-32\Scripts\django-admin.exe\__main__.py", line 4, in <module>
  File "c:\users\danii\appdata\local\programs\python\python38-32\lib\site-packages\django\core\management\__init__.py", line 12, in <module>
    from django.conf import settings
  File "c:\users\danii\appdata\local\programs\python\python38-32\lib\site-packages\django\conf\__init__.py", line 19, in <module>
    from django.core.validators import URLValidator
  File "c:\users\danii\appdata\local\programs\python\python38-32\lib\site-packages\django\core\validators.py", line 8, in <module>
    from django.utils.encoding import punycode
  File "c:\users\danii\appdata\local\programs\python\python38-32\lib\site-packages\django\utils\encoding.py", line 8, in <module>
    from django.utils.deprecation import RemovedInDjango40Warning
  File "c:\users\danii\appdata\local\programs\python\python38-32\lib\site-packages\django\utils\deprecation.py", line 1, in <module>
    import asyncio
  File "c:\users\danii\appdata\local\programs\python\python38-32\lib\asyncio\__init__.py", line 8, in <module>
    from .base_events import *
  File "c:\users\danii\appdata\local\programs\python\python38-32\lib\asyncio\base_events.py", line 40, in <module>
    from . import events
  File "c:\users\danii\appdata\local\programs\python\python38-32\lib\asyncio\events.py", line 783, in <module>
    from _asyncio import (_get_running_loop, _set_running_loop,
AttributeError: module 'traceback' has no attribute 'extract_stack'_

Python 3.9
Django  3.1.3
This error can be very stupid, but I started doing this recently.If you have additional questions, I'm ready to answer
Thanks

**Comment by ravikyram** [comment]
@ImJustError 

Is this issue related to Tensorflow?.

This question is better asked on StackOverflow since it is not a bug or feature request related to Tensorflow. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!
