### ISSUE TITLE
Problem building from source with cuda 11.1

### ISSUE THREAD

**Issue by king398** [tensorflow/tensorflow#44671]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):Source 
- TensorFlow version:2.3.0
- Python version:3.7
- Installed using virtualenv? pip? conda?:conda
- Bazel version (if compiling from source):3.1.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:11.1,8.0
- GPU model and memory:RTX 3070

**Describe the problem**
I I have brought a RTX 3070. To use it with tensorflow I need to use cuda 11.1.So I built it from source. the problem is that the compiler is asking for files that do not exist in CUDA 11.1. You can see does file in the log below
**Provide the exact sequence of commands / steps that you executed before running into the problem**
I followed all the commands from the https://www.tensorflow.org/install/source_windows guide and at it worked fine.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
.\bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package
WARNING: Output user root "C:/Users/pc/_bazel_my new pc" contains a space. This will probably break the build. You should set a different --output_user_root.
WARNING: The following configs were expanded more than once: [cuda, using_cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=210
INFO: Reading rc options for 'build' from c:\tensorflow\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=F:/anaconda/envs/tf/python.exe
INFO: Reading rc options for 'build' from c:\tensorflow\.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=v2
INFO: Reading rc options for 'build' from c:\tensorflow\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=F:/anaconda/python.exe --action_env PYTHON_LIB_PATH=F:/anaconda/lib/site-packages --python_path=F:/anaconda/python.exe --config=xla --action_env TF_CUDA_VERSION=11.1 --action_env TF_CUDNN_VERSION=8 --action_env TF_CUDA_PATHS=C:Program FilesNVIDIA GPU Computing ToolkitCUDAv11.1,C:cuda --action_env CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.1 --action_env TF_CUDA_COMPUTE_CAPABILITIES=8.6 --config=cuda --define=override_eigen_strong_inline=true --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:v2 in file c:\tensorflow\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file c:\tensorflow\.bazelrc: --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true
INFO: Found applicable config definition build:cuda in file c:\tensorflow\.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file c:\tensorflow\.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain
INFO: Found applicable config definition build:opt in file c:\tensorflow\.tf_configure.bazelrc: --copt=/arch:AVX --define with_default_optimizations=true
INFO: Found applicable config definition build:cuda in file c:\tensorflow\.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file c:\tensorflow\.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain
INFO: Found applicable config definition build:windows in file c:\tensorflow\.bazelrc: --copt=/w --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --experimental_strict_action_env=true --verbose_failures --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file c:\tensorflow\.bazelrc: --define framework_shared_object=false
INFO: Repository local_config_cuda instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule cuda_configure defined at:
  C:/tensorflow/third_party/gpus/cuda_configure.bzl:1399:18: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1369
                _create_local_cuda_repository(<1 more arguments>)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 955, in _create_local_cuda_repository
                _get_cuda_config(repository_ctx, <1 more arguments>)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 657, in _get_cuda_config
                find_cuda_config(repository_ctx, <2 more arguments>)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 635, in find_cuda_config
                _exec_find_cuda_config(<3 more arguments>)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 629, in _exec_find_cuda_config
                execute(repository_ctx, <1 more arguments>)
        File "C:/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
Could not find any cublas_api.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
INFO: Repository rules_cc instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule tf_http_archive defined at:
  C:/tensorflow/third_party/repo.bzl:134:19: in <toplevel>
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
DEBUG: Repository io_bazel_rules_docker instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule git_repository defined at:
  C:/users/pc/_bazel_my new pc/xv6zejqw/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18: in <toplevel>
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1369
                _create_local_cuda_repository(<1 more arguments>)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 955, in _create_local_cuda_repository
                _get_cuda_config(repository_ctx, <1 more arguments>)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 657, in _get_cuda_config
                find_cuda_config(repository_ctx, <2 more arguments>)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 635, in find_cuda_config
                _exec_find_cuda_config(<3 more arguments>)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 629, in _exec_find_cuda_config
                execute(repository_ctx, <1 more arguments>)
        File "C:/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
Could not find any cublas_api.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
WARNING: Target pattern parsing failed.
ERROR: no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1369
                _create_local_cuda_repository(<1 more arguments>)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 955, in _create_local_cuda_repository
                _get_cuda_config(repository_ctx, <1 more arguments>)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 657, in _get_cuda_config
                find_cuda_config(repository_ctx, <2 more arguments>)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 635, in find_cuda_config
                _exec_find_cuda_config(<3 more arguments>)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 629, in _exec_find_cuda_config
                execute(repository_ctx, <1 more arguments>)
        File "C:/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
Could not find any cublas_api.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
INFO: Elapsed time: 1.046s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package

**Comment by king398** [comment]
log 
`.\bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package
WARNING: Output user root "C:/Users/pc/_bazel_my new pc" contains a space. This will probably break the build. You should set a different --output_user_root.
WARNING: The following configs were expanded more than once: [cuda, using_cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=210
INFO: Reading rc options for 'build' from c:\tensorflow\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=F:/anaconda/envs/tf/python.exe
INFO: Reading rc options for 'build' from c:\tensorflow\.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=v2
INFO: Reading rc options for 'build' from c:\tensorflow\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=F:/anaconda/python.exe --action_env PYTHON_LIB_PATH=F:/anaconda/lib/site-packages --python_path=F:/anaconda/python.exe --config=xla --action_env TF_CUDA_VERSION=11.1 --action_env TF_CUDNN_VERSION=8 --action_env TF_CUDA_PATHS=C:Program FilesNVIDIA GPU Computing ToolkitCUDAv11.1,C:cuda --action_env CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.1 --action_env TF_CUDA_COMPUTE_CAPABILITIES=8.6 --config=cuda --define=override_eigen_strong_inline=true --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:v2 in file c:\tensorflow\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file c:\tensorflow\.bazelrc: --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true
INFO: Found applicable config definition build:cuda in file c:\tensorflow\.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file c:\tensorflow\.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain
INFO: Found applicable config definition build:opt in file c:\tensorflow\.tf_configure.bazelrc: --copt=/arch:AVX --define with_default_optimizations=true
INFO: Found applicable config definition build:cuda in file c:\tensorflow\.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file c:\tensorflow\.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain
INFO: Found applicable config definition build:windows in file c:\tensorflow\.bazelrc: --copt=/w --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --experimental_strict_action_env=true --verbose_failures --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file c:\tensorflow\.bazelrc: --define framework_shared_object=false
INFO: Repository local_config_cuda instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule cuda_configure defined at:
  C:/tensorflow/third_party/gpus/cuda_configure.bzl:1399:18: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1369
                _create_local_cuda_repository(<1 more arguments>)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 955, in _create_local_cuda_repository
                _get_cuda_config(repository_ctx, <1 more arguments>)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 657, in _get_cuda_config
                find_cuda_config(repository_ctx, <2 more arguments>)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 635, in find_cuda_config
                _exec_find_cuda_config(<3 more arguments>)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 629, in _exec_find_cuda_config
                execute(repository_ctx, <1 more arguments>)
        File "C:/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
Could not find any cublas_api.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
INFO: Repository rules_cc instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule tf_http_archive defined at:
  C:/tensorflow/third_party/repo.bzl:134:19: in <toplevel>
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
DEBUG: Repository io_bazel_rules_docker instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule git_repository defined at:
  C:/users/pc/_bazel_my new pc/xv6zejqw/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18: in <toplevel>
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1369
                _create_local_cuda_repository(<1 more arguments>)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 955, in _create_local_cuda_repository
                _get_cuda_config(repository_ctx, <1 more arguments>)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 657, in _get_cuda_config
                find_cuda_config(repository_ctx, <2 more arguments>)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 635, in find_cuda_config
                _exec_find_cuda_config(<3 more arguments>)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 629, in _exec_find_cuda_config
                execute(repository_ctx, <1 more arguments>)
        File "C:/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
Could not find any cublas_api.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
WARNING: Target pattern parsing failed.
ERROR: no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1369
                _create_local_cuda_repository(<1 more arguments>)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 955, in _create_local_cuda_repository
                _get_cuda_config(repository_ctx, <1 more arguments>)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 657, in _get_cuda_config
                find_cuda_config(repository_ctx, <2 more arguments>)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 635, in find_cuda_config
                _exec_find_cuda_config(<3 more arguments>)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 629, in _exec_find_cuda_config
                execute(repository_ctx, <1 more arguments>)
        File "C:/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
Could not find any cublas_api.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
INFO: Elapsed time: 1.046s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package`

**Comment by king398** [comment]
You can also suggest other ways to install tensorflow on rtx 3070
