### ISSUE TITLE
Could not load dynamic library 'libcuda.so.1'

### ISSUE THREAD

**Issue by tekumara** [tensorflow/tensorflow#44761]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.3.1
- Python version: 3.7.9
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: cuda 10.1 cudnn7
- GPU model and memory: K80

**Describe the problem**
```
$ python -c "import tensorflow as tf; hello = tf.constant('hello world'); sess = tf.Session()"
2020-11-11 10:40:12.930534: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-11-11 10:40:14.016970: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2020-11-11 10:40:14.017024: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-11-11 10:40:14.017053: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (16c54693e7f2): /proc/driver/nvidia/version does not exist
2020-11-11 10:40:14.017450: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-11-11 10:40:14.041823: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2300060000 Hz
2020-11-11 10:40:14.042236: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x558b3bbe0d40 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-11-11 10:40:14.042293: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'Session'
```

**Comment by tekumara** [comment]
```
$ find /usr/ -iname 'libcuda*'
/usr/local/cuda-10.1/compat/libcuda.so.1
/usr/local/cuda-10.1/compat/libcuda.so
/usr/local/cuda-10.1/compat/libcuda.so.418.165.02
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudart.so.10.1
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudart.so.10.1.243
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudadevrt.a
/usr/local/cuda-10.1/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudart_static.a
/usr/local/cuda-10.1/extras/Debugger/lib64/libcudacore.a
/usr/local/cuda-10.1/extras/Debugger/include/libcudacore.h
```

**Comment by tekumara** [comment]
When setting LD_LIBRARY_PATH, I get `CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected` instead:
```
$ export LD_LIBRARY_PATH=/usr/local/cuda-10.1/compat/:$LD_LIBRARY_PATH
python3 -c "import tensorflow as tf; hello = tf.constant('hello world'); sess = tf.Session()"
2020-11-11 10:46:36.362374: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-11-11 10:46:37.459527: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-11-11 10:46:37.467224: E tensorflow/stream_executor/cuda/cuda_driver.cc:314] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2020-11-11 10:46:37.467270: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (16c54693e7f2): /proc/driver/nvidia/version does not exist
2020-11-11 10:46:37.467664: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-11-11 10:46:37.493842: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2300060000 Hz
2020-11-11 10:46:37.494252: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55dd7ef8bc70 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-11-11 10:46:37.494301: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'Session'
```

**Comment by tekumara** [comment]
Setting LD_LIBRARY_PATH resolves the issue:

```
export LD_LIBRARY_PATH=/usr/local/cuda-10.1/compat/:$LD_LIBRARY_PATH
```
