### ISSUE TITLE
Failed to serialize the input pipeline graph: PyFunc is stateful. [Op:DatasetToGraphV2]

### ISSUE THREAD

**Issue by Ecclesiast** [tensorflow/tensorflow#44763]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04):
- TensorFlow installed from (source or binary): binary build from branch `2.3.0`
- TensorFlow version (use command below): 2.3.0
- Python version: 3.8.5
- Bazel version (if compiling from source): 3.1.0
- CUDA/cuDNN version: 11.1, 8.0.4
- GPU model and memory: Nvidia GeForce 1060 6Gb

**Describe the current behavior**
I am using a custom model that inherits from `tf.Module`. Also for some logic I am using `tf-addons==0.11.2`
Everything trains ok, without problem, however when I am using `tf.saved_model.save(custom_model, path)` I get the error below in logs section.
I found this issue after tensorflow update 2.1.0 source to 2.3.0 binary.

**Standalone code to reproduce the issue**
Below is my train code:
```
import tensorflow as tf
import tensorflow_addons as tfa

class NERTrainer(tf.Module):
    ..........
    def _helpers_(self):
        pass
    ..........
    def train(self):
        ix = 0
        for words, chars, labels, sentence_lengths in self._training_dataset:
            with tf.GradientTape() as tape:
                embeddings = self._add_embeddings_transformations(words, chars, ix)
                logits = self._add_logits(embeddings, ix)
                labels = tf.cast(labels, tf.int32)
                sentence_lengths = tf.cast(sentence_lengths, tf.int32)

                log_likelihood, transition_parameters = tfa.text.crf_log_likelihood(
                    logits, labels, sentence_lengths
                )
                log_likelihood = tf.reduce_mean(-log_likelihood)
            gradients = tape.gradient(log_likelihood, self._trainables)
            self.optimizer.apply_gradients(zip(gradients, self._trainables))
            ix += 1

        self._transition_parameters = tf.constant(transition_parameters.numpy())
        scores = self._run_evaluation(train_dataset=False)
        return {'avg_f1': np.mean(scores['f1'])}

if '__name__' == '__main__':
    nn_trainer = NERTrainer()
    num_epochs = 10
    for ix in range(num_epochs):
            print('Epoch #{}'.format(ix))
            logger.info('Epoch #{}'.format(ix))
    
            nn_trainer.train()
            nn_trainer.lr *= nn_trainer.lr_decay
            
            tf.saved_model.save(nn_trainer, target_save_path)
```

**Other info / logs** Include any logs or source code that would be helpful to
All logs while training:
```
2020-11-11 14:21:33.948277: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-11-11 14:21:33.948441: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-11-11 14:21:33.948969: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:0a:00.0 name: GeForce GTX 1060 6GB computeCapability: 6.1
coreClock: 1.8095GHz coreCount: 10 deviceMemorySize: 5,93GiB deviceMemoryBandwidth: 178,99GiB/s
2020-11-11 14:21:33.948983: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.1
2020-11-11 14:21:33.950141: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.11
2020-11-11 14:21:33.950597: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-11-11 14:21:33.950717: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-11-11 14:21:33.951851: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.11
2020-11-11 14:21:33.952087: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.11
2020-11-11 14:21:33.952157: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.8
2020-11-11 14:21:33.952243: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-11-11 14:21:33.952820: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-11-11 14:21:33.953190: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-11-11 14:21:33.953398: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-11-11 14:21:33.980819: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 3792500000 Hz
2020-11-11 14:21:33.981555: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x791e0e0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-11-11 14:21:33.981578: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-11-11 14:21:34.038911: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-11-11 14:21:34.039310: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x78fa260 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-11-11 14:21:34.039330: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 1060 6GB, Compute Capability 6.1
2020-11-11 14:21:34.039561: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-11-11 14:21:34.040024: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:0a:00.0 name: GeForce GTX 1060 6GB computeCapability: 6.1
coreClock: 1.8095GHz coreCount: 10 deviceMemorySize: 5,93GiB deviceMemoryBandwidth: 178,99GiB/s
2020-11-11 14:21:34.040053: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.1
2020-11-11 14:21:34.040099: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.11
2020-11-11 14:21:34.040122: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-11-11 14:21:34.040141: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-11-11 14:21:34.040160: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.11
2020-11-11 14:21:34.040178: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.11
2020-11-11 14:21:34.040196: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.8
2020-11-11 14:21:34.040286: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-11-11 14:21:34.040790: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-11-11 14:21:34.041208: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-11-11 14:21:34.041240: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.1
2020-11-11 14:21:34.268942: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-11-11 14:21:34.268983: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 
2020-11-11 14:21:34.268992: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N 
2020-11-11 14:21:34.269251: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-11-11 14:21:34.269571: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-11-11 14:21:34.269829: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5006 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:0a:00.0, compute capability: 6.1)
Epoch #0
2020-11-11 14:21:34.496695: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.8
2020-11-11 14:21:34.824964: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.11
2020-11-11 14:22:03.651363: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
Traceback (most recent call last):
  File "ner.py", line 358, in <module>
    tf.saved_model.save(nn_trainer, target_save_path)
  File "/home/kirill/.local/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py", line 975, in save
    _, exported_graph, object_saver, asset_info = _build_meta_graph(
  File "/home/kirill/.local/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py", line 1061, in _build_meta_graph
    _ = _SaveableView(checkpoint_graph_view)
  File "/home/kirill/.local/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py", line 216, in __init__
    function._list_all_concrete_functions_for_serialization())  # pylint: disable=protected-access
  File "/home/kirill/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 1030, in _list_all_concrete_functions_for_serialization
    concrete_functions = self._list_all_concrete_functions()
  File "/home/kirill/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 1012, in _list_all_concrete_functions
    self.get_concrete_function()
  File "/home/kirill/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 1167, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/home/kirill/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 1073, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/home/kirill/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 696, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/home/kirill/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2855, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/kirill/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/kirill/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3065, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/home/kirill/.local/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/kirill/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 600, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/kirill/.local/lib/python3.8/site-packages/tensorflow/python/training/tracking/tracking.py", line 262, in _creator
    resource = self._create_resource()
  File "/home/kirill/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 205, in <lambda>
    lambda: weak_self._trace_variant_creation()()),  # pylint: disable=unnecessary-lambda,protected-access
  File "/home/kirill/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 277, in _trace_variant_creation
    self._as_serialized_graph(external_state_policy=distribute_options
  File "/home/kirill/.local/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/kirill/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 248, in _as_serialized_graph
    return gen_dataset_ops.dataset_to_graph_v2(
  File "/home/kirill/.local/lib/python3.8/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 1122, in dataset_to_graph_v2
    _ops.raise_from_not_ok_status(e, name)
  File "/home/kirill/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 6843, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.FailedPreconditionError: Failed to serialize the input pipeline graph: PyFunc is stateful. [Op:DatasetToGraphV2]
```
I see this error the first time. Didn't find something similar.
Could you help me with this issue please?

**Comment by Saduf2019** [comment]
@Ecclesiast 
I ran the code shared it has syntax errors and is not indented, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/a0c28aa761df5a8df9671438fb01cff8/untitled460.ipynb). could you please share indented code such that we could replicate the issue or is possible share a colab gist with the error.
