### ISSUE TITLE
Python returns multiple errors on using gTTS module

### ISSUE THREAD

**Issue by GOdOfTHuNdeR007** [tensorflow/tensorflow#44795]
`from gtts import gTTS`
`test=gTTS(text="Hello World", lang='en')`
`test.save('sample.mp3')`

### **Error:**
C:\Program Files\Python37\lib\http\cookiejar.py:1623: UserWarning: http.cookiejar bug!
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\http\cookiejar.py", line 1621, in make_cookies
    parse_ns_headers(ns_hdrs), request)
  File "C:\Program Files\Python37\lib\http\cookiejar.py", line 1577, in _cookies_from_attrs_set
    cookie = self._cookie_from_cookie_tuple(tup, request)
  File "C:\Program Files\Python37\lib\http\cookiejar.py", line 1570, in _cookie_from_cookie_tuple
    rest)
  File "C:\Program Files\Python37\lib\http\cookiejar.py", line 793, in __init__
    self._rest = copy.copy(rest)
AttributeError: module 'copy' has no attribute 'copy'

  _warn_unhandled_exception()
C:\Program Files\Python37\lib\http\cookiejar.py:1623: UserWarning: http.cookiejar bug!
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\http\cookiejar.py", line 1621, in make_cookies
    parse_ns_headers(ns_hdrs), request)
  File "C:\Program Files\Python37\lib\http\cookiejar.py", line 1577, in _cookies_from_attrs_set
    cookie = self._cookie_from_cookie_tuple(tup, request)
  File "C:\Program Files\Python37\lib\http\cookiejar.py", line 1570, in _cookie_from_cookie_tuple
    rest)
  File "C:\Program Files\Python37\lib\http\cookiejar.py", line 793, in __init__
    self._rest = copy.copy(rest)
AttributeError: module 'copy' has no attribute 'copy'

  _warn_unhandled_exception()
Traceback (most recent call last):
  File "c:\Users\Benison\OneDrive\Programs\Python\XII\test.py", line 5, in <module>
    tts.save("synthesized.mp3")
    prepared_requests = self._prepare_requests()                                        e 295, in save
  File "C:\Users\Benison\AppData\Roaming\Python\Python37\site-packages\gtts\tts.py", line 194, in _prepare_requests                                                             e 251, in write_to_fp
    part_tk = self.token.calculate_token(part)
  File "C:\Users\Benison\AppData\Roaming\Python\Python37\site-packages\gtts_token\gtts_te 194, in _prepare_requestsoken.py", line 28, in calculate_token
    seed = self._get_token_key()                                                        oken.py", line 28, in calculate_token  
  File "C:\Users\Benison\AppData\Roaming\Python\Python37\site-packages\gtts_token\gtts_token.py", line 59, in _get_token_key                                                    oken.py", line 59, in _get_token_key   
    "Unable to find token seed! Did https://translate.google.com change?"
ValueError: Unable to find token seed! Did https://translate.google.com change?
PS C:\Users\Benison\OneDrive\Programs\Python>  cd 'c:\Users\Benison\OneDrive\Programs\Python'; & 'C:\Program Files\Python37\python.exe' 'c:\Users\Benison\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\lib\python\debugpy\launcher' '59434' '--' 'c:\Users\Benison\OneDrive\Programs\Python\XII\test.py' 
C:\Program Files\Python37\lib\http\cookiejar.py:1623: UserWarning: http.cookiejar bug!
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\http\cookiejar.py", line 1621, in make_cookies    
    parse_ns_headers(ns_hdrs), request)
  File "C:\Program Files\Python37\lib\http\cookiejar.py", line 1577, in _cookies_from_attrs_set
    cookie = self._cookie_from_cookie_tuple(tup, request)
  File "C:\Program Files\Python37\lib\http\cookiejar.py", line 1570, in _cookie_from_cookie_tuple
    rest)
  File "C:\Program Files\Python37\lib\http\cookiejar.py", line 793, in __init__
    self._rest = copy.copy(rest)
AttributeError: module 'copy' has no attribute 'copy'

  _warn_unhandled_exception()
C:\Program Files\Python37\lib\http\cookiejar.py:1623: UserWarning: http.cookiejar bug!
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\http\cookiejar.py", line 1621, in make_cookies    
    parse_ns_headers(ns_hdrs), request)
  File "C:\Program Files\Python37\lib\http\cookiejar.py", line 1577, in _cookies_from_attrs_set
    cookie = self._cookie_from_cookie_tuple(tup, request)
  File "C:\Program Files\Python37\lib\http\cookiejar.py", line 1570, in _cookie_from_cookie_tuple
    rest)
  File "C:\Program Files\Python37\lib\http\cookiejar.py", line 793, in __init__
    self._rest = copy.copy(rest)
AttributeError: module 'copy' has no attribute 'copy'

  _warn_unhandled_exception()

**Comment by Saduf2019** [comment]
@GOdOfTHuNdeR007 
This does not seem like a tensorflow related issue, please create the issue in the correct repo and move this to closed status.
