### ISSUE TITLE
Make tf.debugging.assert_shapes message more flexible

### ISSUE THREAD

**Issue by joelberkeley** [tensorflow/tensorflow#44889]
**System information**
- TensorFlow version (you are using): 2.3.1
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
`tf.debugging.assert_shapes` currently states that the tensors must have the shape specified by the constraints e.g.
```
>>> tf.debugging.assert_shapes([([0, 0], [1])])
ValueError: .  Specified explicitly.  Tensor shape=(2,) dtype=int32 dimension 0 must have size 1.  Received size 2, shape (2,)
```.
This design makes sense, but doesn't allow for when you want to compare the shapes of two tensors, and you don't know if either of them is right, you just know they have to be the same. If I have two tensors `x` and `y`, and I do `tf.debugging.assert_shapes([(x, y.shape)])`, the error message states that `x` should have the shape of `y` at the call site, but it might be that `y` is wrong as well/instead, in which case the message is misleading. The argument `message` can help here, but it would have to contradict the default message.

**Will this change the current api? How?**
Only if we consider error messages as public API.

**Who will benefit with this feature?**
Users? Not sure I can say anything more useful here

**Comment by joelberkeley** [comment]
It may be that a new function would be better for this, e.g. `tf.debugging.assert_shapes_equal`

**Comment by rmothukuru** [comment]
@joelberkeley,
You have mentioned:

> 1. you don't know if either of them is right, you just know they have to be the same
> 
> 2. the error message states that x should have the shape of y at the call site, but it might be that y is wrong as well/instead, in which case the message is misleading.

Can you please explain how the above 2 issues can be addressed with the new function, `tf.debugging.assert_shapes_equal`. 

Also, can you please specify a Real Time Use Case where the `new function` will be effective compared to that of the existing `Functions/APIs`. Thanks!

**Comment by joelberkeley** [comment]
`tf.debugging.assert_shapes_equal` (or whatever it's called) would mean you get an error message like
```
>>> tf.debugging.assert_shapes_equal([([0, 0], [1])])
ValueError: .  Specified explicitly.  Tensor shapes must match, but received Tensor shape=(2,) dtype=int32 dimension 0 and Tensor shape=(1,), dtype=int32.
```
I did try to word it so that it works both for "the shape must be ...", and "the shapes must be equal", but I can't think of a suitable wording.

On further digging, I see that my original use case doesn't actually need it, so I don't have an immediate use for it, but to give an example: an object defined in terms of n points in some arbitrary-rank space (like a shape or volume in this space). It would be odd to work with points that are merely broadcastable to the same shape, rather than the exact same shape, when you know that they need to mean the same thing, but with different element values.

**Comment by rmothukuru** [comment]
@joelberkeley,
What I understand from your comment is that we can make the "Error Message more Explicit/Clear". 

The purpose of the API, `tf.debugging.assert_shapes` is to Debug our Code and we can always use the [argument](https://www.tensorflow.org/api_docs/python/tf/debugging/assert_shapes#args), `messsage` to customize the `Error Message` and to make it as clear/explicit as we want.

Please let us know if we have answered your question so that we can close this issue. Thanks!

**Comment by joelberkeley** [comment]
@rmothukuru not really, no. The limitation of the `message` argument is that it's worded in a way that assumes the right hand side of the shape check is correct. I'd like to use the function in a way that _doesn't_ assume this. Adding a `message` doesn't fix the problem because it would have to contradict the default message, and contradictory text in an error message is going to make debugging harder

**Comment by joelberkeley** [comment]
I guess one way would be to be able to customize the error message more than we can already.

**Comment by joelberkeley** [comment]
I've just found that this works, but it's a bit heavy on the boilerplate
```
>>> x = tf.ones([1, 2])
>>> y = tf.ones([3, 2])
>>> tf.TensorShape(tf.shape(x)).assert_is_compatible_with(tf.shape(y))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/joel.berkeley/.venv/trieste/joelberkeley/dev/lib/python3.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 1134, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (1, 2) and tf.Tensor([3 2], shape=(2,), dtype=int32) are incompatible
```

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

**Comment by joelberkeley** [comment]
I don't have any interest in continuing with this issue. Indeed it's been open for four years. Do with it what you will.
