### ISSUE TITLE
RuntimeError: tensorflow/lite/kernels/concatenation.cc:76 t->dims->data[d] != t0->dims->data[d] (32 != 1)Node number 23 (CONCATENATION) failed to prepare. Node number 30 (WHILE) failed to invoke.

### ISSUE THREAD

**Issue by Angel3636** [tensorflow/tensorflow#44938]
**System information**
-  Linux Ubuntu 16.04
- TensorFlow installed from 2.3:
- Tf-nightly: 2..4.0a20201112
- Keras = 2.4.3

** I am able to convert to the tflite model but i am getting error while conversion.
Error: "Traceback (most recent call last):
  File "/home/PycharmProjects/keras-ctpn/test.py", line 74, in <module>
    interpreter.invoke()
  File "/home/anaconda3/envs/sentiment_analysis/lib/python3.7/site-packages/tensorflow/lite/python/interpreter.py", line 540, in invoke
    self._interpreter.Invoke()
RuntimeError: tensorflow/lite/kernels/concatenation.cc:76 t->dims->data[d] != t0->dims->data[d] (32 != 1)Node number 23 (CONCATENATION) failed to prepare.
Node number 30 (WHILE) failed to invoke."

My python Script:

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
import cv2
import keras
import numpy as np
import tensorflow as tf
import keras.backend as K
import keras.layers as KL
import keras.models as KM
from keras.applications.vgg16 import VGG16 as vgg
from keras.layers import TimeDistributed
from keras.models import Sequential

input_image = KL.Input(shape=[512, 512, 3], name="input_image")
vgg = vgg(input_tensor=input_image, include_top=False)
x = vgg.get_layer('block5_conv3').output
x = KL.Conv2D(512, 3, padding='same', activation='relu', kernel_initializer='he_normal')(x)
temp = KL.Bidirectional(KL.LSTM(128, return_sequences=True))
x = KL.TimeDistributed(temp)(x)
new_output = KL.Dense(10, activation="sigmoid")(x)
headModel = KL.Flatten(name="flatten")(new_output)
headModel = KL.Dense(2, activation="softmax")(headModel)
print(K.int_shape(x))
model = KM.Model(inputs=input_image, outputs=x)
model.save('i_bilstm.h5')

model = keras.models.load_model('i_bilstm.h5')

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
converter.experimental_new_converter = True
tflite_model = converter.convert()
open("i_bilstm.tflite", "wb").write(tflite_model)

interpreter = tf.lite.Interpreter(
    model_path='i_bilstm.tflite')
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
print(input_details)
print(output_details)
floating_model = input_details[0]['dtype'] == np.float32
height = input_details[0]['shape'][1]
width = input_details[0]['shape'][2]
img = cv2.imread('006.jpg')
img = cv2.resize(img, (512, 512))
input_data = np.expand_dims(img, axis=0)

print(img.shape)
img = img.reshape(1, 512, 512, 3)
print('shape ', img.shape)
if floating_model:
    img = (np.float32(img) - 127.5) / 127.5

print('input_details[0]', input_details[0]['index'])
interpreter.set_tensor(input_details[0]['index'], img)
interpreter.invoke()
rects = interpreter.get_tensor(
    output_details[0]['index'])
print('score ', rects)
scores = interpreter.get_tensor(
    output_details[0]['index'])
print('score ', scores)

Also I have attached the file:

# Full console log:

/home/anaconda3/envs/sentiment_analysis/bin/python /home/PycharmProjects/keras-ctpn/test.py
2020-11-17 16:55:41.346730: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2020-11-17 16:55:41.346748: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-11-17 16:55:42.364414: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-11-17 16:55:42.364557: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-11-17 16:55:42.364568: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2020-11-17 16:55:42.364584: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (PC13): /proc/driver/nvidia/version does not exist
2020-11-17 16:55:42.364708: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-11-17 16:55:42.365362: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set

WARNING:tensorflow:No training configuration found in the save file, so the model was *not* compiled. Compile it manually.
/home/anaconda3/envs/sentiment_analysis/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:2342: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  warnings.warn('`Model.state_updates` will be removed in a future version. '
2020-11-17 16:55:44.987273: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
/home/anaconda3/envs/sentiment_analysis/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py:1395: UserWarning: `layer.updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  warnings.warn('`layer.updates` will be removed in a future version. '
WARNING:absl:Found untraced functions such as bidirectional_layer_call_fn, bidirectional_layer_call_and_return_conditional_losses, forward_lstm_layer_call_fn, forward_lstm_layer_call_and_return_conditional_losses, backward_lstm_layer_call_fn while saving (showing 5 of 25). These functions will not be directly callable after loading.
2020-11-17 16:55:49.339432: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:319] Ignored output_format.
2020-11-17 16:55:49.339456: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:322] Ignored drop_control_dependency.
2020-11-17 16:55:49.340091: I tensorflow/cc/saved_model/reader.cc:32] Reading SavedModel from: /tmp/tmp9mpttm0t
2020-11-17 16:55:49.353959: I tensorflow/cc/saved_model/reader.cc:55] Reading meta graph with tags { serve }
2020-11-17 16:55:49.353980: I tensorflow/cc/saved_model/reader.cc:93] Reading SavedModel debug info (if present) from: /tmp/tmp9mpttm0t
2020-11-17 16:55:49.354016: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-11-17 16:55:49.391851: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:251] None of the MLIR optimization passes are enabled (registered 0 passes)
2020-11-17 16:55:49.404005: I tensorflow/cc/saved_model/loader.cc:206] Restoring SavedModel bundle.
2020-11-17 16:55:49.433978: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2899885000 Hz
2020-11-17 16:55:49.540582: I tensorflow/cc/saved_model/loader.cc:190] Running initialization op on SavedModel bundle at path: /tmp/tmp9mpttm0t
2020-11-17 16:55:49.598145: I tensorflow/cc/saved_model/loader.cc:277] SavedModel load for tags { serve }; Status: success: OK. Took 258055 microseconds.
2020-11-17 16:55:49.758440: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:194] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2020-11-17 16:55:49.921397: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
[{'name': 'serving_default_input_image:0', 'index': 0, 'shape': array([  1, 512, 512,   3], dtype=int32), 'shape_signature': array([ -1, 512, 512,   3], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
[{'name': 'StatefulPartitionedCall:0', 'index': 87, 'shape': array([  1,  32,  32, 256], dtype=int32), 'shape_signature': array([ -1,  32,  32, 256], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
Traceback (most recent call last):
  File "/home/PycharmProjects/keras-ctpn/test.py", line 71, in <module>
    interpreter.invoke()
  File "/home/anaconda3/envs/sentiment_analysis/lib/python3.7/site-packages/tensorflow/lite/python/interpreter.py", line 540, in invoke
    self._interpreter.Invoke()
RuntimeError: tensorflow/lite/kernels/concatenation.cc:76 t->dims->data[d] != t0->dims->data[d] (32 != 1)Node number 23 (CONCATENATION) failed to prepare.
Node number 30 (WHILE) failed to invoke.

Process finished with exit code 1

[tflite_conv.py.txt](https://github.com/tensorflow/tensorflow/files/5553142/tflite_conv.py.txt)

**Comment by amahendrakar** [comment]
Session crashes on running the code with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/ad9f99c922f71ec262e15ba5fa7df1a8/44938.ipynb). 

Whereas running with [TF v2.4.0rc1](https://colab.research.google.com/gist/amahendrakar/4116e8c9cb359db4af5c5f70a5f3b38d/44938-2-4.ipynb#scrollTo=aao5xPEIKJN2) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/ca8643cc1e01ff9940317e99ba07771f/44938-tf-nightly.ipynb#scrollTo=6LlvVYtMGDLK) throws an error stating `error: OpenCV(4.1.2) /io/opencv/modules/imgproc/src/resize.cpp:3720: error: (-215:Assertion failed) !ssize.empty() in function 'resize'`

Please find the attached gist. Thanks!

**Comment by Angel3636** [comment]
@amahendrakar Thank you for reply. I have attached the sample image. Sorry for the missing file. Now i am able to reproduce the error using the image file. Can you please take a look now.

![006](https://user-images.githubusercontent.com/14245664/99519704-354ea580-29b8-11eb-9426-ef464ca11079.jpg)

**Comment by jvishnuvardhan** [comment]
@Angel3636 I can reproduce the error. Interpreter is throwing the following error. [Here](https://colab.research.google.com/gist/jvishnuvardhan/078848a173cc7cb58874cea4959468cb/44938-tf-nightly.ipynb) is the gist for our reference.

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-21-066e1310d25e> in <module>()
      6 interpreter.set_tensor(input_details[0]['index'], input_data)
      7 # interpreter.set_tensor(input_details[0]['index'], img)
----> 8 interpreter.invoke()

/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/interpreter.py in invoke(self)
    538     """
    539     self._ensure_safe()
--> 540     self._interpreter.Invoke()
    541 
    542   def reset_all_variables(self):

RuntimeError: tensorflow/lite/kernels/concatenation.cc:76 t->dims->data[d] != t0->dims->data[d] (32 != 1)Node number 23 (CONCATENATION) failed to prepare.
Node number 30 (WHILE) failed to invoke.
tensorflow/lite/kernels/concatenation.cc:76 t->dims->data[d] != t0->dims->data[d] (32 != 1)Node number 23 (CONCATENATION) failed to prepare.
Node number 30 (WHILE) failed to invoke.
tensorflow/lite/kernels/concatenation.cc:76 t->dims->data[d] != t0->dims->data[d] (32 != 1)Node number 23 (CONCATENATION) failed to prepare.
Node number 30 (WHILE) failed to invoke.
tensorflow/lite/kernels/concatenation.cc:76 t->dims->data[d] != t0->dims->data[d] (32 != 1)Node number 23 (CONCATENATION) failed to prepare.
Node number 30 (WHILE) failed to invoke.
tensorflow/lite/kernels/concatenation.cc:76 t->dims->data[d] != t0->dims->data[d] (32 != 1)Node number 23 (CONCATENATION) failed to prepare.
Node number 30 (WHILE) failed to invoke.
```

I am not sure whether the Bidirectional LSTM completely implemented or not. @srjoglekar246 Any thoughts on this? Thanks!

**Comment by Angel3636** [comment]
I am not sure whether the Bidirectional LSTM completely implemented or not. @srjoglekar246 Any thoughts on this? Thanks!

# 
@jvishnuvardhan  How can i check this?, because if i do the  inference using save model 'bilstm.h5' i get the results without any problem, but if i try with tflite,  i am getting error that shown in gist
 "tensorflow/lite/kernels/concatenation.cc:76 t->dims->data[d] != t0->dims->data[d] (32 != 1)Node number 23 (CONCATENATION) failed to prepare.
Node number 30 (WHILE) failed to invoke"

**Comment by renjie-liu** [comment]
Hi Haoliang,

can you help take a look?

thanks!

**Comment by haozha111** [comment]
Bidi-LSTM is fully supported by the new converter. Could you share your .tflite file? This seems to be some shape mismatch that just get messed up.

**Comment by Angel3636** [comment]
Hi @haozha111, Thanks for reply, My file size is to big, So i have uploaded on drive. Here is the link:
https://drive.google.com/file/d/1B_laiJYNHzHDgvxwKqrAQerctXzad6so/view?usp=sharing

**Comment by haozha111** [comment]
seems that i dont have access, could you grant permission?

**Comment by Angel3636** [comment]
> 
> 
> seems that i dont have access, could you grant permission?

Sorry for that, can you please check it now.

**Comment by mohantym** [comment]
Hi @Angel3636!
Could you please try on latest stable version of tf 2.6  and let us know if this is still an issue.Thanks!

**Comment by nmfisher** [comment]
Think I'm experiencing the same, was this fixed?
