### ISSUE TITLE
Quantization op for Reshape is not supported in keras

### ISSUE THREAD

**Issue by deandx** [tensorflow/tensorflow#44961]
Tensorflow version 2.2.0
For the experiment, I build a simple model and try to quantized aware training with reshape function.

```
def test_model(final_depth = 24):
    inputs = layers.Input(shape=(None, None,24))
    input_shape = tf.shape(inputs)
    rs_1 = tf.reshape(inputs, [input_shape[0], input_shape[1] * input_shape[2], input_shape[3], 1])
    conv1 = layers.ReLU(negative_slope = 0.2)(layers.Conv2D(1, (1,3), activation = None, padding = 'same', kernel_initializer = 'glorot_uniform')(rs_1))
    out = tf.reshape(conv1, [input_shape[0], input_shape[1], input_shape[2], input_shape[3]])
    model = tf.keras.Model(inputs = inputs, outputs = out)
    return model
```

Then I got an error like this:

```
Traceback (most recent call last):
  File "/root/anaconda3/envs/tf2/lib/python3.8/site-packages/tensorflow_model_optimization/python/core/quantization/keras/quantize.py", line 383, in quantize_apply
    model_copy = _clone_model_with_weights(model)
  File "/root/anaconda3/envs/tf2/lib/python3.8/site-packages/tensorflow_model_optimization/python/core/quantization/keras/quantize.py", line 332, in _clone_model_with_weights
    cloned_model = keras.models.clone_model(model_to_clone)
  File "/root/anaconda3/envs/tf2/lib/python3.8/site-packages/tensorflow/python/keras/models.py", line 426, in clone_model
    return _clone_functional_model(
  File "/root/anaconda3/envs/tf2/lib/python3.8/site-packages/tensorflow/python/keras/models.py", line 199, in _clone_functional_model
    network.reconstruct_from_config(model_config,
  File "/root/anaconda3/envs/tf2/lib/python3.8/site-packages/tensorflow/python/keras/engine/network.py", line 2029, in reconstruct_from_config
    process_node(layer, node_data)
  File "/root/anaconda3/envs/tf2/lib/python3.8/site-packages/tensorflow/python/keras/engine/network.py", line 1977, in process_node
    output_tensors = layer(input_tensors, **kwargs)
  File "/root/anaconda3/envs/tf2/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 897, in __call__
    self._maybe_build(inputs)
  File "/root/anaconda3/envs/tf2/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2416, in _maybe_build
    self.build(input_shapes)  # pylint:disable=not-callable
  File "/root/anaconda3/envs/tf2/lib/python3.8/site-packages/tensorflow/python/keras/layers/wrappers.py", line 58, in build
    self.layer.build(input_shape)
  File "/root/anaconda3/envs/tf2/lib/python3.8/site-packages/tensorflow/python/keras/layers/convolutional.py", line 153, in build
    input_channel = self._get_input_channel(input_shape)
  File "/root/anaconda3/envs/tf2/lib/python3.8/site-packages/tensorflow/python/keras/layers/convolutional.py", line 293, in _get_input_channel
    raise ValueError('The channel dimension of the inputs '
ValueError: The channel dimension of the inputs should be defined. Found `None`.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tools/train_oppo_template_yuv_24pack.py", line 227, in <module>
    main()
  File "./tools/train_oppo_template_yuv_24pack.py", line 114, in main
    model = tfmot.quantization.keras.quantize_apply(annotated_model)
  File "/root/anaconda3/envs/tf2/lib/python3.8/site-packages/tensorflow_model_optimization/python/core/quantization/keras/quantize.py", line 385, in quantize_apply
    raise ValueError(
ValueError: Unable to clone model. This generally happens if you used custom Keras layers or objects in your model. Please specify them via `quantize_scope` for your calls to `quantize_model` and `quantize_apply`.
```

It looks like the reshape operation is not supported. So I try to skip the quantized reshape op just as the other unsupported operations. Stil got the same error

```
def annotate(layer):
    if layer._name.startswith('tf_op_layer_Reshape'):
      return layer
    # quantize everything else
    return tfmot.quantization.keras.quantize_annotate_layer(layer)

annotated_model = tf.keras.models.clone_model(model, clone_function=annotate)
model = tfmot.quantization.keras.quantize_apply(annotated_model)
```

**I did another experiment with the simple model for the reshape function. I directly connect the reshape function to the output (did not skip the quantized reshape op)**
```
def test_model(final_depth = 24):
    inputs = layers.Input(shape=(None, None,24))
    input_shape = tf.shape(inputs)
   conv1 = layers.ReLU(negative_slope = 0.2)(layers.Conv2D(final_depth, 3, activation = None, padding = 'same', kernel_initializer = 'glorot_uniform')(inputs))
    out = tf.reshape(conv1, [input_shape[0], input_shape[1], input_shape[2], input_shape[3]])
    model = tf.keras.Model(inputs = inputs, outputs = out)
    return model
```
Got the error like this:
```
Traceback (most recent call last):
  File "./tools/train_oppo_template_yuv_24pack.py", line 227, in <module>
    main()
  File "./tools/train_oppo_template_yuv_24pack.py", line 114, in main
    model = tfmot.quantization.keras.quantize_apply(annotated_model)
  File "/root/anaconda3/envs/tf2/lib/python3.8/site-packages/tensorflow_model_optimization/python/core/quantization/keras/quantize.py", line 420, in quantize_apply
    return keras.models.clone_model(
  File "/root/anaconda3/envs/tf2/lib/python3.8/site-packages/tensorflow/python/keras/models.py", line 426, in clone_model
    return _clone_functional_model(
  File "/root/anaconda3/envs/tf2/lib/python3.8/site-packages/tensorflow/python/keras/models.py", line 195, in _clone_functional_model
    model_config, created_layers = _clone_layers_and_model_config(
  File "/root/anaconda3/envs/tf2/lib/python3.8/site-packages/tensorflow/python/keras/models.py", line 246, in _clone_layers_and_model_config
    config = network.get_network_config(model, serialize_layer_fn=_copy_layer)
  File "/root/anaconda3/envs/tf2/lib/python3.8/site-packages/tensorflow/python/keras/engine/network.py", line 2119, in get_network_config
    layer_config = serialize_layer_fn(layer)
  File "/root/anaconda3/envs/tf2/lib/python3.8/site-packages/tensorflow/python/keras/models.py", line 243, in _copy_layer
    created_layers[layer.name] = layer_fn(layer)
  File "/root/anaconda3/envs/tf2/lib/python3.8/site-packages/tensorflow_model_optimization/python/core/quantization/keras/quantize.py", line 370, in _quantize
    raise RuntimeError(
RuntimeError: Layer tf_op_layer_Reshape/shape:<class 'tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer'> is not supported. You can quantize this layer by passing a `tfmot.quantization.keras.QuantizeConfig` instance to the `quantize_annotate_layer` API.
```

If I do skip the quantized reshape op like above, I can run the model. But I found out that the channel dimension after reshape becomes "None", Therefore I can't connect reshape layer to any other layer e.g. conv2d
```
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_1 (InputLayer)            [(None, None, None,  0                                            
__________________________________________________________________________________________________
quantize_layer (QuantizeLayer)  (None, None, None, 2 3           input_1[0][0]                    
__________________________________________________________________________________________________
tf_op_layer_Shape (TensorFlowOp (4,)                 0           quantize_layer[1][0]             
__________________________________________________________________________________________________
quant_conv2d (QuantizeWrapper)  (None, None, None, 2 5259        quantize_layer[1][0]             
__________________________________________________________________________________________________
tf_op_layer_strided_slice (Tens ()                   0           tf_op_layer_Shape[1][0]          
__________________________________________________________________________________________________
tf_op_layer_strided_slice_1 (Te ()                   0           tf_op_layer_Shape[1][0]          
__________________________________________________________________________________________________
tf_op_layer_strided_slice_2 (Te ()                   0           tf_op_layer_Shape[1][0]          
__________________________________________________________________________________________________
tf_op_layer_strided_slice_3 (Te ()                   0           tf_op_layer_Shape[1][0]          
__________________________________________________________________________________________________
quant_re_lu (QuantizeWrapper)   (None, None, None, 2 3           quant_conv2d[0][0]               
__________________________________________________________________________________________________
tf_op_layer_Reshape/shape (Tens (4,)                 0           tf_op_layer_strided_slice[1][0]  
                                                                 tf_op_layer_strided_slice_1[1][0]
                                                                 tf_op_layer_strided_slice_2[1][0]
                                                                 tf_op_layer_strided_slice_3[1][0]
__________________________________________________________________________________________________
tf_op_layer_Reshape (TensorFlow (None, None, None, N 0           quant_re_lu[0][0]                
                                                                 tf_op_layer_Reshape/shape[1][0]  
==================================================================================================
Total params: 5,265
Trainable params: 5,208
Non-trainable params: 57
__________________________________________________________________________________________________
```
I think the problem is that quantized reshape is unsupported. Even if I skip quantizing the reshape function, the channel dimension of output become 'None' so I can't connect it to the other conv function

**Comment by deandx** [comment]
My tensorflow version is 2.2.0

**Comment by Saduf2019** [comment]
@deandx 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]

Please paste the error message (using makrdown formatting around it) instead of screenshotting. Screenshots are not searchable so they don't help in looking for the issue and also don't help other people having the same error from finding about the issue.

**Comment by deandx** [comment]
@Saduf2019 
I update the issue

**Comment by Saduf2019** [comment]
@deandx 
I ran the code on nightly and do not face any errors as reported, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/f69fc005750d5fffc769eeac40f63d14/untitled463.ipynb).

**Comment by deandx** [comment]
@Saduf2019 
    Thanks for your reply. You need to install the tfmot for  tensorflow quantization. 
    You can use the command:
**pip install tensorflow-model-optimization**

you can run my code after install the tfmot
```
import tensorflow as tf
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
import tensorflow_model_optimization as tfmot

def main():

  def test_model(final_depth = 24):
    inputs = layers.Input(shape=(None, None,24))
    input_shape = tf.shape(inputs)
    rs_1 = tf.reshape(inputs, [input_shape[0], input_shape[1] * input_shape[2], input_shape[3], 1])
    conv1 = layers.ReLU(negative_slope = 0.2)(layers.Conv2D(1, (1,3), activation = None, padding = 'same', kernel_initializer = 'glorot_uniform')(rs_1))
    out = tf.reshape(conv1, [input_shape[0], input_shape[1], input_shape[2], input_shape[3]])
    model = tf.keras.Model(inputs = inputs, outputs = out)
    return model

  model = test_model()

  def annotate(layer):
    if layer._name.startswith('tf_op_layer_Reshape'):
      return layer
    # quantize everything else
    return tfmot.quantization.keras.quantize_annotate_layer(layer)
 
  annotated_model = tf.keras.models.clone_model(model, clone_function=annotate)
  model = tfmot.quantization.keras.quantize_apply(annotated_model)

  model.summary()

if __name__ == "__main__":
    main()
```

Then I got the error as reported

**Comment by Saduf2019** [comment]
@deandx 
I ran the code shared and face a different error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/aa01edd5b375de6ac8c07e2c3db43aed/untitled463.ipynb).

**Comment by deandx** [comment]
@Saduf2019 1
  The shape layer also not supported.  You can update this function to avoid using the quantized shape function. Thanks!
```
def annotate(layer):
    if layer._name.startswith('tf_op_layer_Reshape'):
      return layer
    elif layer._name.startswith('tf_op_layer_Shape'):
        return layer
    elif layer._name.startswith('concatenate'):
      return layer
    elif layer._name.startswith('tf_op_layer_strided_slice'):
      return layer
    # quantize everything else
    return tfmot.quantization.keras.quantize_annotate_layer(layer)
```

**Comment by sachinprasadhs** [comment]
While trying to reproduce your issue in Tf Nightly 2.6 facing some different error, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/dda816a5f47b965ee753494e83d94629/44961.ipynb), Thanks!

**Comment by chunduriv** [comment]
@deandx, Sorry for late response. We are checking to see if you still need help on this issue.

Many bugs have been fixed in the recent versions of TF. Could you please try with TF2.7 and let us know if the issue still persists?
