### ISSUE TITLE
bidirectional_dynamic_rnn: Negative indices are currently unsupported

### ISSUE THREAD

**Issue by bluemonk482** [tensorflow/tensorflow#4497]
I am getting the 'negaive indexing' error since I switched from using `bidirectional_rnn` to `bidirectional_dynamic_rnn`:

```
			(output_fw, output_bw), output_states  = tf.nn.bidirectional_dynamic_rnn(
				cell_fw=lstm_fw_cell,
				cell_bw=lstm_bw_cell,
				inputs=x,
				dtype=tf.float32,
				sequence_length=seq_len
				)
			output_fw = tf.transpose(output_fw, perm=[1,0,2])
			output_bw = tf.transpose(output_bw, perm=[1,0,2])
			rnn_outputs = tf.concat(2, [output_fw, output_bw])

		with tf.variable_scope('output', reuse=reuse):
			with tf.variable_scope('softmax'):
				W = tf.get_variable('W', [self.num_hidden*2, self.num_classes],
									initializer=tf.truncated_normal_initializer(stddev=0.1))
				b = tf.get_variable('b', [self.num_classes], initializer=tf.constant_initializer(0.1))
			logits = tf.matmul(rnn_outputs[-1], W) + b
```

```
Traceback (most recent call last):
  File "train_lstm.py", line 62, in <module>
    logits = model.inference()
  File "/home/ccrmad/Code/TDLSTM/models/rnn_classifier.py", line 70, in inference
    logits = tf.matmul(rnn_outputs[-1], W) + b
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 334, in _SliceHelper
    raise NotImplementedError("Negative indices are currently unsupported")
NotImplementedError: Negative indices are currently unsupported
```

How come I could negative-index the output from `bidirectional_rnn` but not `bidirectional_dynamic_rnn` this way? Thanks.

**Comment by ofirnachum** [comment]
bidirectional_rnn works and returns lists of tensors while bidirectional_dynamic_rnn works and returns tensors (each tensor packed along time-dimension).  Could this be the issue?

**Comment by bluemonk482** [comment]
Thanks I have just noticed that. I will close this issue now.
