### ISSUE TITLE
Gives error on dumping images to the tensorboard when training with TPU using gradient tape.

### ISSUE THREAD

**Issue by coreqode** [tensorflow/tensorflow#44981]
I am using colab_tpu with tensorflow version 2.3.0
Dumping of scalars work good, but on dumping images it gives error. Inputs and Output are in tf.float32. The code is present [here](https://github.com/coreqode/tboard_issue/blob/master/base_module.py)

1.  When, I call ```_train_dump_images```  function inside the ```train_step_zero```, it gives following error ([here](https://github.com/coreqode/tboard_issue/blob/b0af0c08e03e8c2ba6912a07cd0d5028d4f6725f/base_module.py#L108)):

```
Traceback (most recent call last):
  File "grapy.py", line 156, in <module>
    main()
  File "grapy.py", line 152, in main
    grapy.train()
  File "/content/TensorFlow-TryOn/base_module.py", line 237, in train
    losses = self.tpu_train_step_zero(train_iterator)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 823, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 697, in _initialize
    *args, **kwds))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 2855, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 3075, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 600, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 3735, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py", line 973, in wrapper
    raise e.ag_error_metadata.to_exception(e)
tensorflow.python.framework.errors_impl.InaccessibleTensorError: in user code:

    /content/TensorFlow-TryOn/base_module.py:287 tpu_train_step_zero  *
        losses = self.strategy.run(self.train_step_zero, args=(next(iterator)))
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/tpu_strategy.py:346 run  **
        return self.extended.tpu_run(fn, args, kwargs, options)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/tpu_strategy.py:1095 tpu_run
        return func(args, kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/tpu_strategy.py:1162 tpu_function
        padding_spec=padding_spec)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/tpu/tpu.py:915 replicate
        padding_spec=padding_spec)[1]
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/tpu/tpu.py:1380 split_compile_and_replicate
        outputs = computation(*computation_inputs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/tpu_strategy.py:1124 replicated_fn
        result[0] = fn(*replica_args, **replica_kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py:780 __call__
        result = self._call(*args, **kwds)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py:840 _call
        return self._stateless_fn(*args, **kwds)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py:2829 __call__
        return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py:1848 _filtered_call
        cancellation_manager=cancellation_manager)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py:1938 _call_flat
        flat_outputs = forward_function.call(ctx, args_with_tangents)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py:579 call
        executor_type=executor_type)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/functional_ops.py:1207 partitioned_call
        op = graph.create_op(op_name, args, tout, name=op_name, attrs=op_attrs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py:507 new_func
        return func(*args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py:3416 create_op
        attrs, op_def, compute_device)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py:589 _create_op_internal
        inp = self.capture(inp)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py:639 capture
        % (tensor, tensor.graph, self))

    InaccessibleTensorError: The tensor 'Tensor("model_inputs:0", shape=(16, 512, 256, 3), dtype=float32)' cannot be accessed here: it is defined in another function or code block. Use return values, explicit Python locals or TensorFlow collections to access it. Defined in: FuncGraph(name=train_step_zero, id=140465465202672); accessed from: FuncGraph(name=tpu_train_step_zero, id=140465463508440).
```
2.  When, I call ```_train_dump_images```  function outside the ```train_step_zero``` from the training loop (similar to [this](https://github.com/coreqode/tboard_issue/blob/b0af0c08e03e8c2ba6912a07cd0d5028d4f6725f/base_module.py#L47)), it gives following error:
```
Traceback (most recent call last):
  File "grapy.py", line 156, in <module>
    main()
  File "grapy.py", line 152, in main
    grapy.train()
  File "/content/TensorFlow-TryOn/base_module.py", line 253, in train
    self._train_dump_images(tf.constant(self.step, dtype=tf.int64))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 846, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py", line 75, in quick_execute
    raise e
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: model_inputs:0
```

**Comment by Saduf2019** [comment]
@coreqode 
I ran the code shared on tf nightly+tpu and do not see any error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/22a8ad472c53f708c4fd5999369bc3e2/untitled463.ipynb)
