### ISSUE TITLE
OSX PIP Install: Setup.py missing

### ISSUE THREAD

**Issue by joshpearce** [tensorflow/tensorflow#45]
I have Python 2.7.4 installed from MacPorts on El Capitan

This seems to be a more fundamental error that the "six" dependency.

/var/folders/_1/nd1fyl516b79rmsz9xs3_wsc0000gn/T/pip-2CPCqy-build/setup.py is indeed not there.

```
(tensor)joshuapearce@ZOSIMA:~$ pip install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
Downloading/unpacking https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
  Downloading tensorflow-0.5.0-py2-none-any.whl (9.8MB): 9.8MB downloaded
  Running setup.py egg_info for package from https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
    IOError: [Errno 2] No such file or directory: '/var/folders/_1/nd1fyl516b79rmsz9xs3_wsc0000gn/T/pip-2CPCqy-build/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

IOError: [Errno 2] No such file or directory: '/var/folders/_1/nd1fyl516b79rmsz9xs3_wsc0000gn/T/pip-2CPCqy-build/setup.py'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /var/folders/_1/nd1fyl516b79rmsz9xs3_wsc0000gn/T/pip-2CPCqy-build
Storing complete log in /Users/joshuapearce/.pip/pip.log
(tensor)joshuapearce@ZOSIMA:~$ python --version
Python 2.7.4
```

**Comment by joshpearce** [comment]
Solved by updating PIP
