### ISSUE TITLE
Unable to perform subsampling using tf.data.Dataset map() method.

### ISSUE THREAD

**Issue by animesh-wynk** [tensorflow/tensorflow#45005]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.3.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
The preprocessing of sequences can easily be a bottleneck in the Deep Learning pipeline. And tf.data.Dataset provides us ways to optimize the input pipeline. But there are limitations to using a custom python function as a preprocessing step. For example, I am trying to train a model to predict the next item(an item can be a movie, song, book etc), given a history of the items consumed. And I want to use a subsampling function to be passed in the map method. The main challenge here is that I can not pass the item2prob dictionary to my custom subsampling function through the map method. And I am not sure if there are any methods available to pull this off.

**Will this change the current api? How?**
The current API will support python dictionaries to be passed into a custom python function through the map method.

**Who will benefit with this feature?**
This feature will open up possibilities for people trying to optimize their input pipeline using custom preprocessing functions.

**Any Other info.**
Here is what I have trying to do-

```
# make a python generator

def get_generator_random():
    '''
    yields 10 sequences of varying lengths (3 to 7) with values ranging from 0, 5
    '''
    num_seq = 10
    seq_count = 0
    while seq_count < num_seq:
        rand_seq_len = np.random.randint(3, 8)
        seq = np.random.randint(0,6,rand_seq_len)
        yield seq
        seq_count += 1

py_gen = get_generator_random()
for i in py_gen:
    print(i)

```

Output:

```
[2 2 2 3 5 4]
[3 2 0]
[0 2 1 3 4]
[2 4 4 2 2 4 2]
[5 1 3 0 4 5 4]
[2 5 4 5]
[0 2 2 2 0]
[0 2 3]
[0 4 0]
[2 2 1 4 0 1 0]
```

```
# make tf dataset from python generator 

def get_tf_gen():
    tf_gen = tf.data.Dataset.from_generator(
        get_generator,
        output_types=tf.int32, 
        output_shapes = (None, )
    )

    return tf_gen


tf_gen = get_tf_gen()
for i in tf_gen:
  print(i)
```

Output:

```
tf.Tensor([2 2], shape=(2,), dtype=int32)
tf.Tensor([5 1 2 3 4], shape=(5,), dtype=int32)
tf.Tensor([5 1 2 3 4 5], shape=(6,), dtype=int32)
tf.Tensor([5 1 2 2 4 5], shape=(6,), dtype=int32)
tf.Tensor([3 1 2 2 4 2], shape=(6,), dtype=int32)
tf.Tensor([1 1 2 3 3 5], shape=(6,), dtype=int32)
tf.Tensor([2 1 5 3 1 5], shape=(6,), dtype=int32)
tf.Tensor([5 2 2 4 4 2], shape=(6,), dtype=int32)
```

```
# define item2prob (prob of removing an item)

item2prob = {}
for i in range(1, 9):
    if i < 5:
        item2prob[i] = 1
    else:
        item2prob[i] = 0.0

print(item2prob)
```

`{1: 1, 2: 1, 3: 1, 4: 1, 5: 0.0, 6: 0.0, 7: 0.0, 8: 0.0}`

```
def subsample(seq):
    seq_new = []
    random_numbers = tf.random.uniform(shape=(len(seq), ), minval=0, maxval=1, dtype=tf.dtypes.float32,).numpy()
    for s_idx, s in enumerate(seq):
        if random_numbers[s_idx] >= item2prob[s]: # this is where the error occurs
            seq_new.append(s)
    return seq_new  

def tf_subsample(seq):  
    seq_new = tf.py_function(subsample, inp=[seq], Tout=tf.int32)
    return seq_new

tf_gen = get_tf_gen()
tf_gen = tf_gen.map(tf_subsample)
tf_gen = tf_gen.padded_batch(4, padded_shapes=5)

print('\nGenerating data...')
for i in tf_gen:
    print(i)
```

Following is the error message-

```
Generating data...
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/context.py in execution_mode(mode)
   2101       ctx.executor = executor_new
-> 2102       yield
   2103     finally:

10 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py in _next_internal(self)
    757             output_types=self._flat_output_types,
--> 758             output_shapes=self._flat_output_shapes)
    759 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_dataset_ops.py in iterator_get_next(iterator, output_types, output_shapes, name)
   2609     except _core._NotOkStatusException as e:
-> 2610       _ops.raise_from_not_ok_status(e, name)
   2611     except _core._FallbackException:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in raise_from_not_ok_status(e, name)
   6842   # pylint: disable=protected-access
-> 6843   six.raise_from(core._status_to_exception(e.code, message), None)
   6844   # pylint: enable=protected-access

/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: TypeError: Tensor is unhashable. Instead, use tensor.ref() as the key.
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py", line 242, in __call__
    return func(device, token, args)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py", line 131, in __call__
    ret = self._func(*args)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 302, in wrapper
    return func(*args, **kwargs)

  File "<ipython-input-79-e5206ab2321d>", line 5, in subsample
    if random_numbers[s_idx] >= item2prob[s]: # this is where the error occurs

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 823, in __hash__
    raise TypeError("Tensor is unhashable. "

TypeError: Tensor is unhashable. Instead, use tensor.ref() as the key.


	 [[{{node EagerPyFunc}}]] [Op:IteratorGetNext]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-79-e5206ab2321d> in <module>()
     16 
     17 print('\nGenerating data...')
---> 18 for i in tf_gen:
     19     print(i)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py in __next__(self)
    734 
    735   def __next__(self):  # For Python 3 compatibility
--> 736     return self.next()
    737 
    738   def _next_internal(self):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py in next(self)
    770   def next(self):
    771     try:
--> 772       return self._next_internal()
    773     except errors.OutOfRangeError:
    774       raise StopIteration

/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py in _next_internal(self)
    762         return self._element_spec._from_compatible_tensor_list(ret)  # pylint: disable=protected-access
    763       except AttributeError:
--> 764         return structure.from_compatible_tensor_list(self._element_spec, ret)
    765 
    766   @property

/usr/lib/python3.6/contextlib.py in __exit__(self, type, value, traceback)
     97                 value = type()
     98             try:
---> 99                 self.gen.throw(type, value, traceback)
    100             except StopIteration as exc:
    101                 # Suppress StopIteration *unless* it's the same exception that

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/context.py in execution_mode(mode)
   2103     finally:
   2104       ctx.executor = executor_old
-> 2105       executor_new.wait()
   2106 
   2107 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/executor.py in wait(self)
     65   def wait(self):
     66     """Waits for ops dispatched in this executor to finish."""
---> 67     pywrap_tfe.TFE_ExecutorWaitForAllPendingNodes(self._handle)
     68 
     69   def clear_error(self):

InvalidArgumentError: TypeError: Tensor is unhashable. Instead, use tensor.ref() as the key.
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py", line 242, in __call__
    return func(device, token, args)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py", line 131, in __call__
    ret = self._func(*args)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 302, in wrapper
    return func(*args, **kwargs)

  File "<ipython-input-79-e5206ab2321d>", line 5, in subsample
    if random_numbers[s_idx] >= item2prob[s]: # this is where the error occurs

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 823, in __hash__
    raise TypeError("Tensor is unhashable. "

TypeError: Tensor is unhashable. Instead, use tensor.ref() as the key.


	 [[{{node EagerPyFunc}}]]
```

**Comment by bhack** [comment]
@animesh0794 Are you working on recommender systems?

**Comment by animesh0794** [comment]
@bhack  yes I am.

**Comment by bhack** [comment]
> @bhack  yes I am.

We have a new project in ecosystem:
https://www.tensorflow.org/recommenders
https://blog.tensorflow.org/2020/09/introducing-tensorflow-recommenders.html
https://www.tensorflow.org/recommenders/examples/quickstart

**Comment by animesh0794** [comment]
@bhack I am aware of it. But thanks anyway. I just wanted to try my own code first, before trying TFRS : )

**Comment by bhack** [comment]
Yes but you can still be indpired on how dataset are managed https://github.com/tensorflow/recommenders/blob/main/tensorflow_recommenders/examples/movielens.py

**Comment by animesh0794** [comment]
@bhack thanks, i would surely check that out.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
