### ISSUE TITLE
Error while loading .jpg images. Please help

### ISSUE THREAD

**Issue by Liquidten** [tensorflow/tensorflow#45019]
Traceback (most recent call last):
  File "/gpfs/data/ahsan-lab/Sameep/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/eager/context.py", line 2102, in execution_mode
    yield
  File "/gpfs/data/ahsan-lab/Sameep/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 758, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "/gpfs/data/ahsan-lab/Sameep/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2610, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/gpfs/data/ahsan-lab/Sameep/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 6843, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected image (JPEG, PNG, or GIF), got unknown format starting with '\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000'
	 [[{{node DecodeJpeg}}]] [Op:IteratorGetNext]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "model_vgg.py", line 212, in <module>
    model, base_model = make_model(IMG_SIZE = IMG_SIZE, num_classes=3)
  File "model_vgg.py", line 161, in make_model
    image_batch, label_batch = next(iter(train_ds))
  File "/gpfs/data/ahsan-lab/Sameep/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 736, in __next__
    return self.next()
  File "/gpfs/data/ahsan-lab/Sameep/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 772, in next
    return self._next_internal()
  File "/gpfs/data/ahsan-lab/Sameep/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 764, in _next_internal
    return structure.from_compatible_tensor_list(self._element_spec, ret)
  File "/gpfs/data/ahsan-lab/Sameep/tensorflow-gpu/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/gpfs/data/ahsan-lab/Sameep/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/eager/context.py", line 2105, in execution_mode
    executor_new.wait()
  File "/gpfs/data/ahsan-lab/Sameep/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/eager/executor.py", line 67, in wait
    pywrap_tfe.TFE_ExecutorWaitForAllPendingNodes(self._handle)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected image (JPEG, PNG, or GIF), got unknown format starting with '\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000'
	 [[{{node DecodeJpeg}}]]
2020-11-19 13:35:49.049747: W tensorflow/core/kernels/data/cache_dataset_ops.cc:798] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.

**Comment by ymodak** [comment]
Can you try renaming your .jpg images with .jpeg extensions and try again.
Refer [StackOverflow thread](https://stackoverflow.com/questions/57719879/invalidargumenterror-expected-image-jpeg-png-or-gif-got-unknown-format-sta)

**Comment by Liquidten** [comment]
@ymodak I tried changing the file names to .png seems like there might be some corrupt files. Do you think that might have caused the issue?
Traceback (most recent call last):
  File "convetpic.py", line 21, in <module>
    im = Image.open(filename)
  File "/tensorflow-gpu/lib/python3.6/site-packages/PIL/Image.py", line 2862, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file 'Best/keratosis/20196301.jpg'

**Comment by ymodak** [comment]
Can you try to update to latest `PIL` version and try again. If issue still exists then you may want to remove the corrupt images.

**Comment by Liquidten** [comment]
@ravikyram  issue solved Thanks

**Comment by ravikyram** [comment]
@Liquidten 

Please, close this thread if your issue was resolved. Thanks!
