### ISSUE TITLE
Invalid argument:  assertion failed: [Unable to decode bytes as JPEG, PNG, GIF, or BMP]

### ISSUE THREAD

**Issue by Liquidten** [tensorflow/tensorflow#45023]
2020-11-19 17:13:14.386367: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:172] Filling up shuffle buffer (this may take a while): 168 of 256
2020-11-19 17:13:24.373184: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:172] Filling up shuffle buffer (this may take a while): 213 of 256
2020-11-19 17:13:26.240500: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:221] Shuffle buffer filled.
 6/83 [=>............................] - ETA: 1:13 - loss: 1.0636 - accuracy: 0.4635Traceback (most recent call last):
  File "model_vgg.py", line 241, in <module>
    loss0, accuracy0 = model.evaluate(validation_dataset)
  File "/gpfs/data/ahsan-lab/Sameep/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/gpfs/data/ahsan-lab/Sameep/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1379, in evaluate
    tmp_logs = test_function(iterator)
  File "/gpfs/data/ahsan-lab/Sameep/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/gpfs/data/ahsan-lab/Sameep/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 807, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/gpfs/data/ahsan-lab/Sameep/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/gpfs/data/ahsan-lab/Sameep/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/gpfs/data/ahsan-lab/Sameep/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/gpfs/data/ahsan-lab/Sameep/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/gpfs/data/ahsan-lab/Sameep/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  assertion failed: [Unable to decode bytes as JPEG, PNG, GIF, or BMP]
	 [[{{node decode_image/cond_jpeg/else/_1/decode_image/cond_jpeg/cond_png/else/_20/decode_image/cond_jpeg/cond_png/cond_gif/else/_39/decode_image/cond_jpeg/cond_png/cond_gif/Assert/Assert}}]]
	 [[IteratorGetNext]]
	 [[IteratorGetNext/_4]]
  (1) Invalid argument:  assertion failed: [Unable to decode bytes as JPEG, PNG, GIF, or BMP]
	 [[{{node decode_image/cond_jpeg/else/_1/decode_image/cond_jpeg/cond_png/else/_20/decode_image/cond_jpeg/cond_png/cond_gif/else/_39/decode_image/cond_jpeg/cond_png/cond_gif/Assert/Assert}}]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored. [Op:__inference_test_function_1802]

Function call stack:
test_function -> test_function

**Comment by ravikyram** [comment]
@Liquidten 

Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!
