### ISSUE TITLE
Wheel repairing broken when using tensorflow/tensorflow:custom-op-gpu-ubuntu16 docker image

### ISSUE THREAD

**Issue by akarmi** [tensorflow/tensorflow#45032]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: nightly (master branch)
- Python version: 3.6
- Installed using virtualenv? pip? conda?: n/a
- Bazel version (if compiling from source): 3.1.0 (installed by bazelisk v1.3.0 using install_bazelisk from tensorflow/tools/ci_build/release/common.sh)
- GCC/Compiler version (if compiling from source): gcc7_manylinux2010-nvcc-cuda10.1
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

When building "manylinux2010" TensorFlow wheel package using custom-op-gpu-ubuntu16 docker image, the repair step using auditwheel package fails with the following stack trace:

> Traceback (most recent call last):
>   File "/usr/local/bin/auditwheel", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.6/dist-packages/auditwheel/main.py", line 47, in main
>     rval = args.func(args, p)
>   File "/usr/local/lib/python3.6/dist-packages/auditwheel/main_repair.py", line 45, in execute
>     from .repair import repair_wheel
>   File "/usr/local/lib/python3.6/dist-packages/auditwheel/repair.py", line 14, in <module>
>     from .wheeltools import InWheelCtx, add_platforms
>   File "/usr/local/lib/python3.6/dist-packages/auditwheel/wheeltools.py", line 15, in <module>
>     from wheel.util import urlsafe_b64encode, open_for_csv, native  # type: ignore
> ImportError: cannot import name 'open_for_csv' 
> 

The exact command that causes the error is
auditwheel repair --plat manylinux2010_x86_64 -w . tf_nightly_v2-2.5.0-cp36-cp36m-linux_x86_64.whl 

It appears that the failure may be related to [this change](https://github.com/tensorflow/tensorflow/commit/38bc69da9c441e9811d0364fe5cad576c654db3f) that pins down the version of wheel package to a relatively new 0.35 while auditwheel version stayed at 2.0.0, as installed in the docker image using [install_auditwheel.sh](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/install/install_auditwheel.sh).

It is possible to work around this problem by, for example, installing a newer version of auditwheel after calling [install_ubuntu_16_pip_deps](https://github.com/tensorflow/tensorflow/blob/84d0c4e84036e24fe5bd2765428c1624300cc8b4/tensorflow/tools/ci_build/release/common.sh#L106), but a proper fix should probably be done. I am not a specialist in TensorFlow build system and I would not be able to test such a fix thoroughly, but I could provide the initial patch to update the version of auditwheel in [install_auditwheel.sh](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/install/install_auditwheel.sh). Would that be the right course of action, or am I doing something wrong?

**Comment by akarmi** [comment]
@sushreebarsa, thank you for your suggestions. We checked it and got some compilation errors when building tensorflow.

I am closing this issue as it is a very old one. We switched to using tensorflow-testing/nosla-cuda11.2-cudnn8.1-ubuntu18.04-manylinux2010-multipython docker image a few months ago since tensorflow/tensorflow:custom-op-gpu-ubuntu16 does not get updated any more.
