### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 50: invalid start byte

### ISSUE THREAD

**Issue by qufdl0357** [tensorflow/tensorflow#45036]
`Traceback (most recent call last):
  File "object_detection/train.py", line 167, in <module>
    tf.compat.v1.app.run()
  File "C:\Users\info\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\info\Anaconda3\envs\tensorflow\lib\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "C:\Users\info\Anaconda3\envs\tensorflow\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "object_detection/train.py", line 163, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "C:\Users\info\Anaconda3\envs\tensorflow\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\legacy\trainer.py", line 279, in train
    train_config.prefetch_queue_capacity, data_augmentation_options)
  File "C:\Users\info\Anaconda3\envs\tensorflow\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\legacy\trainer.py", line 58, in create_input_queue
    tensor_dict = create_tensor_dict_fn()
  File "object_detection/train.py", line 120, in get_next
    dataset_builder.build(config)).get_next()
  File "C:\Users\info\Anaconda3\envs\tensorflow\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\builders\dataset_builder.py", line 231, in build
    config.input_path[:], input_reader_config, filename_shard_fn=shard_fn)
  File "C:\Users\info\Anaconda3\envs\tensorflow\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\builders\dataset_builder.py", line 150, in read_dataset
    filename_shard_fn)
  File "C:\Users\info\Anaconda3\envs\tensorflow\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\builders\dataset_builder.py", line 76, in _read_dataset_internal
    filenames = tf.gfile.Glob(input_files)
  File "C:\Users\info\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 350, in get_matching_files
    return get_matching_files_v2(filename)
  File "C:\Users\info\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 415, in get_matching_files_v2
    for single_filename in pattern
  File "C:\Users\info\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 417, in <listcomp>
    compat.as_bytes(single_filename))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 50: invalid start byte
[ERROR|main.py:37] 2020-11-20 18:26:38,251 > Transfer leaarning Error
`

I can't find what is the problem.
I set tf_example_decoder.py > dct_method='INTEGER_FAST'  (NOT WORK)
When read TFRecord and Make TFRecord, I can see this error.
help me!

I used Anaconda 4.3 / Tensorflow 2.3.0 / Python 3.7

**Comment by bhack** [comment]
We don't officially support Anaconda here. Can you share a  very minimal "copy and run" example or Colab to reproduce this?

**Comment by Saduf2019** [comment]
@qufdl0357 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]

**Comment by qufdl0357** [comment]
I fixed it. It was a problem with data input type or path.
I changed xml files tag <path>. 
Thanks for trying to help! 
(but still cannot saved checkpoint type "classification" check point)
