### ISSUE TITLE
XLA tests compiled even when XLA is not enabled

### ISSUE THREAD

**Issue by Flamefire** [tensorflow/tensorflow#45045]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): RHEL 7.5
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.4.0-rc2
- Python version: 3.7.4

**Describe the problem**

In my efforts in getting the TF unit tests to run I ran into a problem where the tests seem to require XLA but that isn't available and hence the tests fail with
`ImportError: Unable to import _pywrap_tfcompile; you must build TensorFlow with XLA.  You may need to build tensorflow with flag --define=with_xla_support=true.  Original error: cannot import name '_pywrap_tfcompile' from 'tensorflow.python'`

Checking this further it seems to be a call to `saved_model_compile_aot` with `name = "aot_compiled_vars_and_arithmetic",` and `force_without_xla_support_flag = False,` so that looks all fine.

Is there any advice or solution you can provide? Some bug in the TF bazel files?

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
bazel  test --compilation_mode=opt --config=opt --subcommands --verbose_failures --config=noaws --jobs=64 --copt="-fPIC" --action_env=PYTHONPATH --action_env=PYTHONNOUSERSITE=1 --distinct_host_configuration=false --local_test_jobs=1  -- //tensorflow/python/... -//tensorflow/python/integration_testing/...
```

**Any other info / logs**

Error from log (paths shortened):

```
ERROR: /tmp/tensorflow-r2.4/tensorflow/python/tools/BUILD:461:24: Executing genrule //tensorflow/python/tools:aot_compiled_vars_and_arithmetic_gen failed (Exit 1): bash failed: error executing command 
  (cd /tmp/output_base/execroot/org_tensorflow && \
  exec env - \
    [env vars] \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/ppc-opt/bin/tensorflow/python/tools/saved_model_cli aot_compile_cpu --dir "$(dirname tensorflow/cc/saved_model/testdata/VarsAndArithmeticObjectGraph/saved_model.pb)" --output_prefix bazel-out/ppc-opt/bin/tensorflow/python/tools/aot_compiled_vars_and_arithmetic --cpp_class VarsAndArithmetic --variables_to_feed variable_x --signature_def_key serving_default --multithreading False --target_triple ppc64le-ibm-linux-gnu --tag_set serve ')
Execution platform: @local_execution_config_platform//:platform
2020-11-20 15:36:23.668303: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "/tmp/output_base/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python/tools/saved_model_cli.runfiles/org_tensorflow/tensorflow/python/tools/saved_model_cli.py", line 1196, in <module>
    sys.exit(main())
  File "/tmp/output_base/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python/tools/saved_model_cli.runfiles/org_tensorflow/tensorflow/python/tools/saved_model_cli.py", line 1192, in main
    args.func(args)
  File "/tmp/output_base/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python/tools/saved_model_cli.runfiles/org_tensorflow/tensorflow/python/tools/saved_model_cli.py", line 835, in aot_compile_cpu
    multithreading=args.multithreading.lower() not in ('f', 'false', '0'))
  File "/tmp/output_base/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python/tools/saved_model_cli.runfiles/org_tensorflow/tensorflow/python/tools/saved_model_aot_compile.py", line 259, in aot_compile_cpu_meta_graph_def
    raise _pywrap_tfcompile_import_error  # pylint: disable=raising-bad-type
ImportError: Unable to import _pywrap_tfcompile; you must build TensorFlow with XLA.  You may need to build tensorflow with flag --define=with_xla_support=true.  Original error: cannot import name '_pywrap_tfcompile' from 'tensorflow.python' (/tmp/output_base/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python/tools/saved_model_cli.runfiles/org_tensorflow/tensorflow/python/__init__.py)
```

There is also no mentioning of XLA (like `--config=xla`) in the log/output

**Comment by Flamefire** [comment]
Looks like this is caused by *not* using `--build_tests_only`, so I guess this is a non-issue as passing that flag solves it.
