### ISSUE TITLE
AttributeError: module 'tensorflow.python.framework.ops' has no attribute 'register_tensor_conversion_function'

### ISSUE THREAD

**Issue by talhaanwarch** [tensorflow/tensorflow#45069]
AttributeError: module 'tensorflow.python.framework.ops' has no attribute 'register_tensor_conversion_function'

I got this error when I run the file in cmd. But when I run in spyder, I did not get the error
**Code**
```
from tensorflow.keras.models import load_model
model=load_model('tf_model.h5')
print(model.summary())
```

**Packages**
absl-py==0.11.0
alabaster==0.7.12
appdirs==1.4.4
astor==0.8.1
astroid==2.4.2
astunparse==1.6.3
async-generator==1.10
atomicwrites==1.4.0
attrs==20.3.0
autopep8==1.5.4
Babel==2.9.0
backcall==0.2.0
bcrypt==3.2.0
black==20.8b1
bleach==3.2.1
cached-property==1.5.2
cachetools==4.1.1
certifi==2020.11.8
cffi==1.14.3
chardet==3.0.4
click==7.1.2
cloudpickle==1.6.0
colorama==0.4.4
cryptography==3.2.1
decorator==4.4.2
defusedxml==0.6.0
diff-match-patch==20200713
docutils==0.16
entrypoints==0.3
flake8==3.8.4
gast==0.3.3
google-auth==1.23.0
google-auth-oauthlib==0.4.2
google-pasta==0.2.0
grpcio==1.33.2
h5py==2.10.0
helpdev==0.7.1
idna==2.10
imagesize==1.2.0
importlib-metadata==2.0.0
intervaltree==3.1.0
ipykernel==5.3.4
ipython==7.19.0
ipython-genutils==0.2.0
isort==5.6.4
jedi==0.17.2
Jinja2==2.11.2
joblib==0.17.0
jsonschema==3.2.0
jupyter-client==6.1.7
jupyter-core==4.7.0
jupyterlab-pygments==0.1.2
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
keyring==21.5.0
lazy-object-proxy==1.4.3
Markdown==3.3.3
MarkupSafe==1.1.1
mccabe==0.6.1
mistune==0.8.4
mypy-extensions==0.4.3
nbclient==0.5.1
nbconvert==6.0.7
nbformat==5.0.8
nest-asyncio==1.4.3
numpy==1.19.4
numpydoc==1.1.0
oauthlib==3.1.0
opt-einsum==3.3.0
packaging==20.4
pandas==1.1.4
pandocfilters==1.4.3
paramiko==2.7.2
parso==0.7.0
pathspec==0.8.1
pathtools==0.1.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.0.1
pluggy==0.13.1
prompt-toolkit==3.0.8
protobuf==3.14.0
psutil==5.7.3
ptyprocess==0.6.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.6.0
pycparser==2.20
pydocstyle==5.1.1
pyflakes==2.2.0
Pygments==2.7.2
pylint==2.6.0
pyls-black==0.4.6
pyls-spyder==0.1.1
PyNaCl==1.4.0
pyparsing==2.4.7
PyQt5==5.12.3
PyQt5-sip==12.8.1
PyQtWebEngine==5.12.1
pyrsistent==0.17.3
python-dateutil==2.8.1
python-jsonrpc-server==0.4.0
python-language-server==0.36.1
pytz==2020.4
pywin32==300
pywin32-ctypes==0.2.0
pyzmq==20.0.0
QDarkStyle==2.8.1
QtAwesome==1.0.1
qtconsole==4.7.7
QtPy==1.9.0
regex==2020.11.13
requests==2.25.0
requests-oauthlib==1.3.0
rope==0.18.0
rsa==4.6
scikit-learn==0.23.2
scipy==1.4.1
six==1.15.0
snowballstemmer==2.0.0
sortedcontainers==2.3.0
Sphinx==3.3.1
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
spyder==4.2.0
spyder-kernels==1.10.0
tensorboard==2.2.2
tensorboard-plugin-wit==1.7.0
tensorflow-cpu==2.2.0
tensorflow-estimator==2.2.0
termcolor==1.1.0
testpath==0.4.4
threaded==4.1.0
threadpoolctl==2.1.0
three-merge==0.1.1
toml==0.10.2
tornado==6.1
traitlets==5.0.5
typed-ast==1.4.1
typing-extensions==3.7.4.3
ujson==4.0.1
urllib3==1.26.2
watchdog==0.10.4
wcwidth==0.2.5
webencodings==0.5.1
Werkzeug==1.0.1
wrapt==1.12.1
yapf==0.30.0
zipp==3.4.0

**Error**
```
Traceback (most recent call last):
  File "code3.py", line 77, in <module>
    from tensorflow.keras.models import load_model
  File "D:\fiverr\traffic\gui\venv\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "D:\fiverr\traffic\gui\venv\lib\site-packages\tensorflow\python\__init__.py", line 64, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "D:\fiverr\traffic\gui\venv\lib\site-packages\tensorflow\python\framework\framework_lib.py", line 25, in <module>
    from tensorflow.python.framework.ops import Graph
  File "D:\fiverr\traffic\gui\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 64, in <module>
    from tensorflow.python.platform import app
  File "D:\fiverr\traffic\gui\venv\lib\site-packages\tensorflow\python\platform\app.py", line 23, in <module>
    from absl.app import run as _run
  File "D:\fiverr\traffic\gui\venv\lib\site-packages\absl\app.py", line 35, in <module>
    import pdb
  File "C:\Anaconda3\lib\pdb.py", line 76, in <module>
    import code
  File "D:\fiverr\traffic\gui\code.py", line 107, in <module>
    from tensorflow.keras.models import load_model
  File "D:\fiverr\traffic\gui\venv\lib\site-packages\tensorflow\keras\__init__.py", line 14, in <module>
    from . import activations
  File "D:\fiverr\traffic\gui\venv\lib\site-packages\tensorflow\keras\activations\__init__.py", line 10, in <module>
    from tensorflow.python.keras.activations import deserialize
  File "D:\fiverr\traffic\gui\venv\lib\site-packages\tensorflow\python\keras\__init__.py", line 27, in <module>
    from tensorflow.python.keras import models
  File "D:\fiverr\traffic\gui\venv\lib\site-packages\tensorflow\python\keras\models.py", line 23, in <module>
    from tensorflow.python.keras import backend as K
  File "D:\fiverr\traffic\gui\venv\lib\site-packages\tensorflow\python\keras\backend.py", line 36, in <module>
    from tensorflow.python.client import session as session_module
  File "D:\fiverr\traffic\gui\venv\lib\site-packages\tensorflow\python\client\session.py", line 38, in <module>
    from tensorflow.python.framework import sparse_tensor
  File "D:\fiverr\traffic\gui\venv\lib\site-packages\tensorflow\python\framework\sparse_tensor.py", line 29, in <module>
    from tensorflow.python.framework import constant_op
  File "D:\fiverr\traffic\gui\venv\lib\site-packages\tensorflow\python\framework\constant_op.py", line 324, in <module>
    ops.register_tensor_conversion_function(
AttributeError: module 'tensorflow.python.framework.ops' h
```as no attribute 'register_tensor_conversion_function'

**Comment by Saduf2019** [comment]
@talhaanwarch 
Could you please share simple stand alone indented code to replicate the issue or if possible share a colab gist with the error reported.
Can you try on an updated tf version if the issue exists.
