### ISSUE TITLE
"NotFoundError: No CPU devices are available in this process" when trying to use GPU / Cuda

### ISSUE THREAD

**Issue by adlzanchetta** [tensorflow/tensorflow#45156]
**System information**
- OS: Windows 10, build 1904:
- TensorFlow installed from: conda
- TensorFlow version: tensorflow-gpu 2.1.0
- Python version: 3.7.9
- Installed using: conda
- CUDA version: cudatoolkit 10.1.243
- cdNN version: cudnn 7.6.5
- GPU model and memory: GeForce RTX 2070

When I run a script that imports tensorflow, I got the initial message that says that we are good to go:

```
2020-11-24 10:34:33.383215: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-11-24 10:34:35.172255: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-11-24 10:34:35.201507: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce RTX 2070 computeCapability: 7.5
coreClock: 1.62GHz coreCount: 36 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 417.29GiB/s
2020-11-24 10:34:35.201929: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-11-24 10:34:35.205687: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-11-24 10:34:35.208452: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-11-24 10:34:35.209263: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-11-24 10:34:35.212090: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-11-24 10:34:35.213642: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-11-24 10:34:35.219337: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-11-24 10:34:35.219630: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
```

And the code runs well until the point a NN structure is to be fit(). There, I get the following error:

`tensorflow.python.framework.errors_impl.NotFoundError: No CPU devices are available in this process`

From what I understand, tensorflow is trying to use my CPU when it should be using my GPUs, correct?

If so, **is there something I should do in my installation to deactivate the usage of CPUs and only force it to use GPUs?**
Or **is it missing some line of code here/there to make this forcing?**

Thanks.

Full error stack:

```
Traceback (most recent call last):
  File "postProc01_QRNN_win10.py", line 280, in <module>
    _cur_nn_model, _cur_model_custom_objs = create_empty_model(_li_df[X_COLS], [20, 20], [0.25, 0.5, 0.75])
  File "postProc01_QRNN_win10.py", line 189, in create_empty_model
    output_activation="relu", input_normalization=True, metrics=[])
  File "D:\andre\git_repos\tibagi_codes\coding_playground\TK_proj_downscalingComparisons\lib\my_quantile_mapping_lib_v2.py", line 54, in build_mqnn
    normalizer.adapt(training_x_values)
  File "C:\Users\dellalia\Anaconda_3_7\envs\ai_geo_gpu_3_7\lib\site-packages\tensorflow_core\python\keras\engine\base_preprocessing_layer.py", line 180, in adapt
    self.build(shape)
  File "C:\Users\dellalia\Anaconda_3_7\envs\ai_geo_gpu_3_7\lib\site-packages\tensorflow_core\python\keras\layers\preprocessing\normalization.py", line 94, in build
    initializer=init_ops.zeros_initializer)
  File "C:\Users\dellalia\Anaconda_3_7\envs\ai_geo_gpu_3_7\lib\site-packages\tensorflow_core\python\keras\engine\base_preprocessing_layer.py", line 107, in _add_state_variable
    **kwargs)
  File "C:\Users\dellalia\Anaconda_3_7\envs\ai_geo_gpu_3_7\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 446, in add_weight
    caching_device=caching_device)
  File "C:\Users\dellalia\Anaconda_3_7\envs\ai_geo_gpu_3_7\lib\site-packages\tensorflow_core\python\training\tracking\base.py", line 744, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "C:\Users\dellalia\Anaconda_3_7\envs\ai_geo_gpu_3_7\lib\site-packages\tensorflow_core\python\keras\engine\base_layer_utils.py", line 142, in make_variable
    shape=variable_shape if variable_shape else None)
  File "C:\Users\dellalia\Anaconda_3_7\envs\ai_geo_gpu_3_7\lib\site-packages\tensorflow_core\python\ops\variables.py", line 258, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "C:\Users\dellalia\Anaconda_3_7\envs\ai_geo_gpu_3_7\lib\site-packages\tensorflow_core\python\ops\variables.py", line 219, in _variable_v1_call
    shape=shape)
  File "C:\Users\dellalia\Anaconda_3_7\envs\ai_geo_gpu_3_7\lib\site-packages\tensorflow_core\python\ops\variables.py", line 197, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "C:\Users\dellalia\Anaconda_3_7\envs\ai_geo_gpu_3_7\lib\site-packages\tensorflow_core\python\ops\variable_scope.py", line 2596, in default_variable_creator
    shape=shape)
  File "C:\Users\dellalia\Anaconda_3_7\envs\ai_geo_gpu_3_7\lib\site-packages\tensorflow_core\python\ops\variables.py", line 262, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "C:\Users\dellalia\Anaconda_3_7\envs\ai_geo_gpu_3_7\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py", line 1411, in __init__
    distribute_strategy=distribute_strategy)
  File "C:\Users\dellalia\Anaconda_3_7\envs\ai_geo_gpu_3_7\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py", line 1542, in _init_from_args
    initial_value() if init_from_fn else initial_value,
  File "C:\Users\dellalia\Anaconda_3_7\envs\ai_geo_gpu_3_7\lib\site-packages\tensorflow_core\python\keras\engine\base_layer_utils.py", line 122, in <lambda>
    init_val = lambda: initializer(shape, dtype=dtype)
  File "C:\Users\dellalia\Anaconda_3_7\envs\ai_geo_gpu_3_7\lib\site-packages\tensorflow_core\python\ops\init_ops.py", line 114, in __call__
    return array_ops.zeros(shape, dtype)
  File "C:\Users\dellalia\Anaconda_3_7\envs\ai_geo_gpu_3_7\lib\site-packages\tensorflow_core\python\ops\array_ops.py", line 2434, in zeros
    output = _constant_if_small(zero, shape, dtype, name)
  File "C:\Users\dellalia\Anaconda_3_7\envs\ai_geo_gpu_3_7\lib\site-packages\tensorflow_core\python\ops\array_ops.py", line 2392, in _constant_if_small
    return constant(value, shape=shape, dtype=dtype, name=name)
  File "C:\Users\dellalia\Anaconda_3_7\envs\ai_geo_gpu_3_7\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 258, in constant
    allow_broadcast=True)
  File "C:\Users\dellalia\Anaconda_3_7\envs\ai_geo_gpu_3_7\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 266, in _constant_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "C:\Users\dellalia\Anaconda_3_7\envs\ai_geo_gpu_3_7\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 95, in convert_to_eager_tensor
    ctx.ensure_initialized()
  File "C:\Users\dellalia\Anaconda_3_7\envs\ai_geo_gpu_3_7\lib\site-packages\tensorflow_core\python\eager\context.py", line 509, in ensure_initialized
    context_handle = pywrap_tensorflow.TFE_NewContext(opts)
tensorflow.python.framework.errors_impl.NotFoundError: No CPU devices are available in this process
```

**Comment by Saduf2019** [comment]
@adlzanchetta 
This issue is more suitable on [Continuum Anaconda](https://github.com/ContinuumIO/anaconda-issues/issues) repo since its related to TF installation with Anaconda.
Please post it on [Continuum Anaconda](https://github.com/ContinuumIO/anaconda-issues/issues).
Thanks!
With respect to the error please refer to: [link](https://github.com/tensorflow/tensorflow/issues/2175),

**Comment by adlzanchetta** [comment]
Found issue. It was in the code. There was a line that unregistered the CPUs to be used as an attempt to force the use of GPUs, but for some reason the GPUs were just not being used. Thanks for the support.

**Comment by jabowery** [comment]
I'm running into the same problem and am confused by adlzanchetta's resolution of this issue when he says "for some reason".  Wasn't the original problem that the GPUs were not being used?  Why must the CPUs be registered for the GPUs to be used?
