### ISSUE TITLE
MirrorStrategy incompatible with tf.Estimator when pulling model from tf hub

### ISSUE THREAD

**Issue by CRSilkworth** [tensorflow/tensorflow#45163]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): 
Yes

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 16.04

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
binary Docker image - tensorflow/tensorflow:2.3.1-gpu

- TensorFlow version (use command below):
v2.3.0-54-gfcc4b966f1 2.3.1

- Python version:
Python 3.6.9

- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
cuda: 10.1, V10.1.243
CUDNN_MAJOR 7
CUDNN_MINOR 6
CUDNN_PATCHLEVEL 5

- GPU model and memory:
GeForce GTX 1060 6GB x 2

**Describe the current behavior**
When running estimator which has a hub.KerasLayer defined in the model_fn, using a mirrored strategy to train fails with a "TypeError: Expected tf.group() expected Tensor arguments not 'None' with type '<class 'NoneType'>". 

Some other notes:
* Using a single device strategy trains without issue.
* Running without a hub.KerasLayer defined in the model_fn using mirrored strategy also trains without issue.
* Tried using a a couple different hub.KerasLayers and both failed in mirrored strategy - 
   * https://tfhub.dev/tensorflow/bert_multi_cased_L-12_H-768_A-12/3
   * https://tfhub.dev/google/nnlm-en-dim50/2

It seems to an issue with how the weights are being initialized when using a hub.KerasLayer in the model_fn when using a mirrored strategy. Maybe global_variables() isn't pulling in the relevant variables?

**Describe the expected behavior**
The estimator should train in both the one device strategy and the mirrored strategy.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Dockerfile:
```
FROM tensorflow/tensorflow:2.3.1-gpu AS tf_build
RUN python3 -m pip install tensorflow-hub==0.10.0
```

temp.py:
```python
import tensorflow as tf
import tensorflow_hub as hub
import numpy as np

num_examples = 100
str_len = 5
num_labels = 3
batch_size = 4


def model_fn(features, labels, mode):
  bert_layer = hub.KerasLayer(
    'https://tfhub.dev/tensorflow/bert_multi_cased_L-12_H-768_A-12/3',
    trainable=True
  )
  encoder_inputs = dict(
    input_word_ids=features['input_word_ids'],
    input_mask=features['input_mask'],
    input_type_ids=features['input_type_ids']
  )
  encoder_outputs = bert_layer(encoder_inputs)
  logits = encoder_outputs['pooled_output']

  dense_layer = tf.keras.layers.Dense(
    num_labels, activation=None, dtype=tf.float32)
  logits = dense_layer(logits)

  loss = tf.nn.softmax_cross_entropy_with_logits(
    labels=features['labels'], logits=logits)
  loss = tf.reduce_mean(loss)

  global_step = tf.compat.v1.train.get_or_create_global_step()
  optimizer = tf.compat.v1.train.AdamOptimizer()
  train_op = optimizer.minimize(loss=loss, global_step=global_step)

  probs = tf.nn.softmax(logits)

  return tf.estimator.EstimatorSpec(
    mode=mode,
    loss=loss,
    train_op=train_op,
    predictions={'probs': probs}
  )


strategy = tf.distribute.MirroredStrategy()
# strategy = tf.distribute.OneDeviceStrategy(device='/gpu:0')
run_config = tf.estimator.RunConfig(
  model_dir='./tmp',
  save_summary_steps=1000,
  log_step_count_steps=1,
  save_checkpoints_secs=1000,
  keep_checkpoint_max=1,
  train_distribute=strategy,
)

est = tf.estimator.Estimator(model_fn=model_fn, config=run_config)


def input_fn():
  labels = np.zeros((num_examples, num_labels))
  labels[np.arange(num_examples), np.random.randint(low=0, high=num_labels)] = 1

  features = dict(
    input_word_ids=np.random.randint(
      low=1, high=100, size=(num_examples, str_len), dtype='int32'),
    input_mask=np.zeros((num_examples, str_len), dtype='int32'),
    input_type_ids=np.zeros((num_examples, str_len), dtype='int32'),
    labels=labels.astype('float32'),
  )

  dataset = tf.data.Dataset.from_tensor_slices(features)
  return dataset.repeat().batch(batch_size)


est.train(input_fn, steps=500)
```

to run:
build docker image:
```
docker build . -t temp_image/temp_image:latest
```
run script:
```
docker run --gpus all -it -v ${PWD}:/tmp -w /tmp --rm temp_image/temp_image:latest python temp.py
```
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

stack trace:
```
2020-11-25 01:06:04.045230: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-11-25 01:06:05.718785: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-11-25 01:06:05.762730: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:04:00.0 name: GeForce GTX 1060 6GB computeCapability: 6.1
coreClock: 1.7085GHz coreCount: 10 deviceMemorySize: 5.93GiB deviceMemoryBandwidth: 178.99GiB/s
2020-11-25 01:06:05.763811: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 1 with properties: 
pciBusID: 0000:81:00.0 name: GeForce GTX 1060 6GB computeCapability: 6.1
coreClock: 1.7085GHz coreCount: 10 deviceMemorySize: 5.94GiB deviceMemoryBandwidth: 178.99GiB/s
2020-11-25 01:06:05.763864: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-11-25 01:06:05.766507: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-11-25 01:06:05.768582: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-11-25 01:06:05.768936: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-11-25 01:06:05.771694: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-11-25 01:06:05.773286: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2020-11-25 01:06:05.778866: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-11-25 01:06:05.782227: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0, 1
2020-11-25 01:06:05.795975: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2100095000 Hz
2020-11-25 01:06:05.806344: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5b3c870 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-11-25 01:06:05.806381: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-11-25 01:06:06.064338: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5ba86c0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-11-25 01:06:06.064388: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 1060 6GB, Compute Capability 6.1
2020-11-25 01:06:06.064401: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (1): GeForce GTX 1060 6GB, Compute Capability 6.1
2020-11-25 01:06:06.065488: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:04:00.0 name: GeForce GTX 1060 6GB computeCapability: 6.1
coreClock: 1.7085GHz coreCount: 10 deviceMemorySize: 5.93GiB deviceMemoryBandwidth: 178.99GiB/s
2020-11-25 01:06:06.066152: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 1 with properties: 
pciBusID: 0000:81:00.0 name: GeForce GTX 1060 6GB computeCapability: 6.1
coreClock: 1.7085GHz coreCount: 10 deviceMemorySize: 5.94GiB deviceMemoryBandwidth: 178.99GiB/s
2020-11-25 01:06:06.066202: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-11-25 01:06:06.066235: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-11-25 01:06:06.066257: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-11-25 01:06:06.066278: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-11-25 01:06:06.066298: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-11-25 01:06:06.066324: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2020-11-25 01:06:06.066346: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-11-25 01:06:06.068886: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0, 1
2020-11-25 01:06:06.068937: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-11-25 01:06:07.467433: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-11-25 01:06:07.467507: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 1 
2020-11-25 01:06:07.467523: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N N 
2020-11-25 01:06:07.467533: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 1:   N N 
2020-11-25 01:06:07.469936: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5547 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:04:00.0, compute capability: 6.1)
2020-11-25 01:06:07.472078: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 5548 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1060 6GB, pci bus id: 0000:81:00.0, compute capability: 6.1)
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/multi_device_iterator_ops.py:339: get_next_as_optional (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Iterator.get_next_as_optional()` instead.
WARNING:tensorflow:Efficient allreduce is not supported for 1 IndexedSlices
WARNING:tensorflow:Efficient allreduce is not supported for 1 IndexedSlices
WARNING:tensorflow:AutoGraph could not transform <function _combine_distributed_scaffold.<locals>.<lambda> at 0x7fa56ae5a158> and will run it as-is.
Cause: could not parse the source code:

      lambda scaffold: scaffold.ready_op, args=(grouped_scaffold,))

This error may be avoided by creating the lambda in a standalone statement.

To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING:tensorflow:AutoGraph could not transform <function _combine_distributed_scaffold.<locals>.<lambda> at 0x7fa56ae5a158> and will run it as-is.
Cause: could not parse the source code:

      lambda scaffold: scaffold.ready_op, args=(grouped_scaffold,))

This error may be avoided by creating the lambda in a standalone statement.

To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING:tensorflow:Issue encountered when serializing variables.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
'NoneType' object has no attribute 'name'
WARNING:tensorflow:Issue encountered when serializing variables.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
'NoneType' object has no attribute 'name'
WARNING:tensorflow:Issue encountered when serializing trainable_variables.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
'NoneType' object has no attribute 'name'
WARNING:tensorflow:Issue encountered when serializing trainable_variables.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
'NoneType' object has no attribute 'name'
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/util.py:96: DistributedIteratorV1.initialize (from tensorflow.python.distribute.input_lib) is deprecated and will be removed in a future version.
Instructions for updating:
Use the iterator's `initializer` property instead.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/util.py:96: DistributedIteratorV1.initialize (from tensorflow.python.distribute.input_lib) is deprecated and will be removed in a future version.
Instructions for updating:
Use the iterator's `initializer` property instead.
Traceback (most recent call last):
  File "temp.py", line 76, in <module>
    est.train(input_fn, steps=500)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1173, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1235, in _train_model_distributed
    self._config._train_distribute, input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1349, in _actual_train_model_distributed
    saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1507, in _train_with_estimator_spec
    log_step_count_steps=log_step_count_steps) as mon_sess:
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 604, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1038, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 749, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1231, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1236, in _create_session
    return self._sess_creator.create_session()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 902, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 660, in create_session
    self._scaffold.finalize()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 200, in finalize
    default_init_op)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 297, in get_or_default
    op = default_constructor()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 196, in default_init_op
    variables.global_variables_initializer(),
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variables.py", line 3290, in global_variables_initializer
    return variables_initializer(global_variables())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variables.py", line 3267, in variables_initializer
    return control_flow_ops.group(*[v.initializer for v in var_list], name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2923, in group
    "'%s' with type '%s'" % (inp, type(inp)))
TypeError: Expected tf.group() expected Tensor arguments not 'None' with type '<class 'NoneType'>'
```

**Comment by amahendrakar** [comment]
@CRSilkworth,
TF Hub issues are tracked in tensorflow/hub repo. Could you please submit a new issue from [this link](https://github.com/tensorflow/hub/issues/new) and fill in the template, so that we can track the issue there. Thanks!

**Comment by CRSilkworth** [comment]
Ok, will do.

**Comment by amahendrakar** [comment]
@CRSilkworth,
Marking this issue as closed, since it is being tracked in TF-hub repo. Please feel free to re-open the issue if necessary. Thanks!
