### ISSUE TITLE
mbed build broken with upgrade to Python 3.9 as part of CI

### ISSUE THREAD

**Issue by advaitjain** [tensorflow/tensorflow#45164]
@tensorflow/micro

https://github.com/tensorflow/tensorflow/commit/bdde0e95363f7799dc9d59eb9e01d66b3ad836e2 updated the docker image used for TFLM for the CI servers. This update to Python 3.9 resulted in the mbed failing with the following error:
```
[mbed] Auto-installing missing Python modules (jsonschema, mbed_cloud_sdk, jinja2, mbed_ls, mbed_host_tests, mbed_greentea, pyelftools, manifest_tool, icetea, pycryptodome, pyusb, cmsis_pack_manager, cryptography, click, cbor)...
Traceback (most recent call last):
  File "/workspace/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4/prj/hello_world/mbed/mbed-os/tools/make.py", line 30, in <module>
    from tools.utils import args_error
  File "/workspace/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4/prj/hello_world/mbed/mbed-os/tools/utils.py", line 33, in <module>
    from intelhex import IntelHex
  File "/usr/local/lib/python3.9/site-packages/intelhex/__init__.py", line 44, in <module>
    from intelhex.compat import (
  File "/usr/local/lib/python3.9/site-packages/intelhex/compat.py", line 60, in <module>
    array_tobytes = getattr(array.array, "tobytes", array.array.tostring)
AttributeError: type object 'array.array' has no attribute 'tostring'
[mbed] ERROR: "/usr/local/bin/python" returned error.
       Code: 1
       Path: "/workspace/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4/prj/hello_world/mbed"
       Command: "/usr/local/bin/python -u /workspace/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4/prj/hello_world/mbed/mbed-os/tools/make.py -t GCC_ARM -m DISCO_F746NG --source . --build ./BUILD/DISCO_F746NG/GCC_ARM"
       Tip: You could retry the last command with "-v" flag for verbose output
---
```

**Comment by cclauss** [comment]
Is this fixed?

**Comment by advaitjain** [comment]
mbed + python 3.9 + CI is not fixed. However, with TFLM moving to a [standalone github repo](https://www.github.com/tensorflow/tflite-micro) the CI will be quite different and the current issue can be closed as a `wontfix`.
