### ISSUE TITLE
Pretrained Xception takes more memory than an InceptionResNetV2, despite having half of the parameters

### ISSUE THREAD

**Issue by Moldoteck** [tensorflow/tensorflow#45209]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): with pip
- TensorFlow version (use command below): 2.2.0
- Python version: 3.8
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1
- GPU model and memory: Nvidia Quadro T2000 

**Describe the current behavior**
I'll attach the script below. 
So, the problem is that if i am using pre-trained InceptionResNetV2 and Xception from keras, turns out that with allow_memory_growth, Inception takes ~ 1GB of my GPU memory when predictiong and Xception takes ~2.8GB, despite being 2x smaller than inception. Is this an expected behaviour?

**Describe the expected behavior**
Xception should be less memory consuming compared to InceptionResNetV2 

**Standalone code to reproduce the issue**

Code for Inception:

```

import tensorflow as tf
from tensorflow.keras.applications.inception_resnet_v2 import InceptionResNetV2
from tensorflow.keras.models import load_model
import numpy as np

gpu_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(gpu_devices[0], True)
logical_gpu_devices = tf.config.list_logical_devices('GPU')

model = InceptionResNetV2()
img = np.zeros([299,299,3],dtype=np.uint8)

print(model.predict(np.array([tf.keras.applications.inception_resnet_v2.preprocess_input(img)])))

```

Code for Xception:

```

import tensorflow as tf
from tensorflow.keras.applications.xception import Xception
from tensorflow.keras.models import load_model
import numpy as np


gpu_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(gpu_devices[0], True)
logical_gpu_devices = tf.config.list_logical_devices('GPU')

model = Xception()
img = np.zeros([299,299,3],dtype=np.uint8)

print(model.predict(np.array([tf.keras.applications.xception.preprocess_input(img)])))

```

**Other info / logs** 
Screenshots for memory consumption:
Inception:
![image](https://user-images.githubusercontent.com/9899064/100369665-dfa87780-300d-11eb-8989-4f4e9e34888d.png)
Xception
![image](https://user-images.githubusercontent.com/9899064/100369597-c30c3f80-300d-11eb-9399-0fe7866f1603.png)

**Comment by amahendrakar** [comment]
@Moldoteck,
Please use the memory profile tool as show in [this guide](https://www.tensorflow.org/guide/profiler#gpu_kernel_stats) to monitor and compare the GPU usage.

Also, go through [this debugging guide](https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras#debug_performance_bottlenecks) and let us know if it helps. Thanks!

**Comment by Moldoteck** [comment]
@amahendrakar I don't know how to use this tool, especially for prediction-only use-case. I tried to make a colab with tensorboard profiler, but i don't know how to measure the GPU performance:
https://colab.research.google.com/drive/1NQWpSzXD2_dbkPh0HHTxBKHwoUnsrw2M?usp=sharing

The thing is that with this code, if i run locally on my PC, InceptionResNetV2 will consume 1GB for prediction, but Xception will use~ 2.8GB
Here is the image for Inception
![image](https://user-images.githubusercontent.com/9899064/100456123-86514e80-30c8-11eb-9865-09fec4990021.png)


Here is the image for Xception
![image](https://user-images.githubusercontent.com/9899064/100455669-c19f4d80-30c7-11eb-8738-d9daa0290b65.png)

**Comment by Moldoteck** [comment]
Also, if i add this line:
`tf.config.experimental.set_virtual_device_configuration(
        gpu_devices[0],
        [tf.config.experimental.VirtualDeviceConfiguration(memory_limit=128)])`

The Xception will consume only 0.6 GB, so the model certainly can run with smaller amount of memory

**Comment by amahendrakar** [comment]
@Moldoteck,
Could you please update TensorFlow to v2.3 or v2.4.0rc3 and check if you are facing the same issue? Thanks!

**Comment by Moldoteck** [comment]
@amahendrakar just tested with tf 2.3.1 and nothing have changed

**Comment by DDoIt** [comment]
Hello,
I have the same GPU model "Nvidia Quadro T2000" and have another issue. If I run the code above:

```
import tensorflow as tf

from tensorflow.keras.applications.xception import Xception
from tensorflow.keras.models import load_model
import numpy as np


gpu_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(gpu_devices[0], True)
logical_gpu_devices = tf.config.list_logical_devices('GPU')

model = Xception()
img = np.zeros([299,299,3],dtype=np.uint8)

print(model.predict(np.array([tf.keras.applications.xception.preprocess_input(img)])))
```
I will get this output:
```
2020-12-04 10:48:24.193552: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-12-04 10:48:24.877442: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-12-04 10:48:24.881036: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-12-04 10:48:24.881216: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: Quadro T2000 computeCapability: 7.5
coreClock: 1.785GHz coreCount: 16 deviceMemorySize: 3.81GiB deviceMemoryBandwidth: 119.24GiB/s
2020-12-04 10:48:24.881230: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-12-04 10:48:24.882154: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-12-04 10:48:24.883150: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-12-04 10:48:24.883338: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-12-04 10:48:24.884305: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-12-04 10:48:24.884879: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2020-12-04 10:48:24.887016: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-12-04 10:48:24.887124: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-12-04 10:48:24.887341: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-12-04 10:48:24.887497: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-12-04 10:48:24.887753: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-12-04 10:48:24.892969: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2599990000 Hz
2020-12-04 10:48:24.894302: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5d6ef60 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-12-04 10:48:24.894335: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-12-04 10:48:24.949224: W tensorflow/compiler/xla/service/platform_util.cc:210] unable to create StreamExecutor for CUDA:0: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY: out of memory; total memory reported: 4093444096
2020-12-04 10:48:24.949357: I tensorflow/compiler/jit/xla_gpu_device.cc:161] Ignoring visible XLA_GPU_JIT device. Device number is 0, reason: Internal: no supported devices found for platform CUDA
2020-12-04 10:48:24.949616: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-12-04 10:48:24.949811: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: Quadro T2000 computeCapability: 7.5
coreClock: 1.785GHz coreCount: 16 deviceMemorySize: 3.81GiB deviceMemoryBandwidth: 119.24GiB/s
2020-12-04 10:48:24.949846: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-12-04 10:48:24.949896: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-12-04 10:48:24.949924: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-12-04 10:48:24.949946: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-12-04 10:48:24.949974: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-12-04 10:48:24.949981: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2020-12-04 10:48:24.950002: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-12-04 10:48:24.950073: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-12-04 10:48:24.950241: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-12-04 10:48:24.950392: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-12-04 10:48:24.950427: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "test3.py", line 9, in <module>
    logical_gpu_devices = tf.config.list_logical_devices('GPU')
  File "/home/david/.local/lib/python3.7/site-packages/tensorflow/python/framework/config.py", line 403, in list_logical_devices
    return context.context().list_logical_devices(device_type=device_type)
  File "/home/david/.local/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 1344, in list_logical_devices
    self.ensure_initialized()
  File "/home/david/.local/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 539, in ensure_initialized
    context_handle = pywrap_tfe.TFE_NewContext(opts)
tensorflow.python.framework.errors_impl.InternalError: CUDA runtime implicit initialization on GPU:0 failed. Status: out of memory
```
**System information**

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 10
- TensorFlow installed from (source or binary): with pip
- TensorFlow version (use command below): 2.3.1
- Python version: 3.7.3
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1
- GPU model and memory: Nvidia Quadro T2000

**Question**
Is this issue because of the GPU model "Nvidia Quadro T2000" ?

cheers
David

**Comment by Moldoteck** [comment]
@DDoIt i have exactly same GPU and it works, so i think the problem for you is either bad drivers or bad tf environment. I think the root should be in drivers, since i am using Windows 10 and you are using Debian 10, which rely on different drivers

**Comment by DDoIt** [comment]
@Moldoteck You are right. I didn't deallocate memory from previous runs.Sorry.

**Comment by sachinprasadhs** [comment]
I'm able to see less memory consumption in `Xception` model than the `InceptionResNetV2`, please find the gist reference for [Xception](https://colab.research.google.com/gist/sachinprasadhs/27cbf439a4d8c603f4372e612b689b4e/xception.ipynb) and [InceptionResNetV2](https://colab.research.google.com/gist/sachinprasadhs/64c8fdbd966e46a9ea18a662b817bde4/inception.ipynb)
