### ISSUE TITLE
Tensorflow Runtime error

### ISSUE THREAD

**Issue by RD191295** [tensorflow/tensorflow#45293]
Traceback (most recent call last):
  File "C:\Users\raj\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\raj\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\raj\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\raj\anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\raj\anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "model_main_tf2.py", line 31, in <module>
    import tensorflow.compat.v2 as tf
  File "C:\Users\raj\anaconda3\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\raj\anaconda3\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\raj\anaconda3\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\raj\anaconda3\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\raj\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\raj\anaconda3\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\raj\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\raj\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\raj\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\raj\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\raj\anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\raj\anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by RD191295** [comment]
When i Import tensorflow in python enviorment it is working fine but when i use model_main_tf2.py file for training it is giving this error.

**Comment by ravikyram** [comment]
@RD191295 

What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download [the latest microsoft visual c++ redistributable from here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).
.Also, please follow the instructions from to install from [Tensorflow website](https://www.tensorflow.org/install/source_windows).
Please, check Your CPU/Python is on 32 bits?Please, refer #36167

Thanks!

**Comment by RD191295** [comment]
i am using intel i3 processor and windows 10. visual c++ is already installed. system is 64 bit.

**Comment by RD191295** [comment]
seems like tensorflow is not installed properly with my system. can you please give some guide that help me to install correctly? i am using anaconda distribution.

**Comment by ravikyram** [comment]
@RD191295 

Please, follow this [guide](https://www.tensorflow.org/install/pip) for installing Tensorflow.Also, please let me know your model number of cpu. Thanks!

**Comment by RD191295** [comment]
it 's intel (R)  Pentium(R)  3850U @ 1.90GHZ

**Comment by ravikyram** [comment]
@RD191295 


As per Intel's [product specification](https://ark.intel.com/content/www/us/en/ark/products/84813/intel-pentium-processor-3805u-2m-cache-1-90-ghz.html), your CPU doesn't support AVX. For more information, please take a look at the [hardware requirements](https://www.tensorflow.org/install/pip#hardware-requirements) to install TensorFlow with pip.

As an alternative in this case, you can [build TensorFlow from source](https://www.tensorflow.org/install/source_windows) or use [Google Colab](https://colab.research.google.com/). Thanks!

**Comment by RD191295** [comment]
i try to use Google co lab but it's encounter resource exhausted error while doing training.
