### ISSUE TITLE
KeyError: "The name 'import/final_result' refers to an Operation not in the graph."

### ISSUE THREAD

**Issue by shaowujie** [tensorflow/tensorflow#45303]
Traceback (most recent call last):
  File "D:/xcr/human-action-classification-master/human-action-classification-master/run_webcam.py", line 65, in <module>
    pose_class = label_img.classify(image)
  File "D:\xcr\human-action-classification-master\human-action-classification-master\scripts\label_image.py", line 99, in classify
    output_operation = graph.get_operation_by_name(output_name)
  File "C:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\ops.py", line 3606, in get_operation_by_name
    return self.as_graph_element(name, allow_tensor=False, allow_operation=True)
  File "C:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\ops.py", line 3478, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "C:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\ops.py", line 3538, in _as_graph_element_locked
    "graph." % repr(name))
KeyError: "The name 'import/final_result' refers to an Operation not in the graph."

**Comment by amahendrakar** [comment]
@shaowujie,
In order to reproduce the issue reported here, could you please provide the TensorFlow version, the complete code and the dataset you are using. Thanks!

**Comment by libby-h** [comment]
Hi there,

I have generated the same error:

2022-01-15 13:02:21.671933: W tensorflow/core/framework/op_def_util.cc:355] Op BatchNormWithGlobalNormalization is deprecated. It will cease to work in GraphDef version 9. Use tf.nn.batch_normalization().
Traceback (most recent call last):
  File "run_image.py", line 51, in <module>
    scene_class = label_img_scene.classify(args.image)
  File "C:\Users\libby\Documents\Python\new-human-action-classification-g\human-action-classification-g\scripts\label_image_scene.py", line 87, in classify
    output_operation = graph.get_operation_by_name(output_name);
  File "C:\Users\libby\Anaconda3\envs\action-classification\lib\site-packages\tensorflow\python\framework\ops.py", line 3606, in get_operation_by_name
    return self.as_graph_element(name, allow_tensor=False, allow_operation=True)
  File "C:\Users\libby\Anaconda3\envs\action-classification\lib\site-packages\tensorflow\python\framework\ops.py", line 3478, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "C:\Users\libby\Anaconda3\envs\action-classification\lib\site-packages\tensorflow\python\framework\ops.py", line 3538, in _as_graph_element_locked
    "graph." % repr(name))
KeyError: "The name 'import/final_result' refers to an Operation not in the graph."

I'm on Tensorflow 1.13.1
