### ISSUE TITLE
ValueError: Input 0 of layer dense_2 is incompatible with the layer: expected axis -1 of input shape to have value 50176 but received input with shape [None, 57600]

### ISSUE THREAD

**Issue by SeanLink11** [tensorflow/tensorflow#45362]
System information

I have written codes similar to that in the Tensorflow page for checking the label on my image based on the model that I trained
- OS Platform and Distribution : Windows 10
- TensorFlow installed from: pip, tf 2.3.0, gpu
- Python version: - 3.6.8

I had run a simple code to test the model with the images
```
model = tf.keras.models.load_model(
            "D:\\Python Projects\\Final Year Project\\assets\\resource\\micro.h5")
path_img = pathlib.Path("D:/Python Projects/Final Year Project/assets/resource/train_images/Acinetobacter.baumanii/edited/img0.png")
image = keras.preprocessing.image.load_img(path_img, target_size=(244, 244)
image_array = keras.preprocessing.image.img_to_array(image)
image_array = tf.expand_dims(image_array, 0)
prediction = model.predict(image_array )
```

Error Info
```
WARNING:tensorflow:Model was constructed with shape (None, 224, 224, 3) for input Tensor("sequential_1_input:0", shape=(None, 224, 224, 3), dtype=float32), but it was called on an input with incompatible shape (None, 244, 244, 3).
WARNING:tensorflow:Model was constructed with shape (None, 224, 224, 3) for input Tensor("random_flip_input:0", shape=(None, 224, 224, 3), dtype=float32), but it was called on an input with incompatible shape (None, 244, 244, 3).
Traceback (most recent call last):
  File "d:\Python Projects\Final Year Project\controller\Image_Recognition.py", line 136, in toProcess
    prediction = self.imgReg.model.predict(img_array)
  File "c:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training.py", line 130, in _method_wrapper
    return method(self, *args, **kwargs)
  File "c:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1599, in predict
    tmp_batch_outputs = predict_function(iterator)
  File "c:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "c:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\def_function.py", line 823, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "c:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\def_function.py", line 697, in _initialize
    *args, **kwds))
  File "c:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\function.py", line 2855, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "c:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "c:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\function.py", line 3075, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "c:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "c:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\def_function.py", line 600, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "c:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\func_graph.py", line 973, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    c:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training.py:1462 predict_function  *
        return step_function(self, iterator)
    c:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training.py:1452 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    c:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1211 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    c:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2585 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    c:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2945 _call_for_each_replica
        return fn(*args, **kwargs)
    c:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training.py:1445 run_step  **
        outputs = model.predict_step(data)
    c:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training.py:1418 predict_step
        return self(x, training=False)
    c:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:985 __call__
        outputs = call_fn(inputs, *args, **kwargs)
    c:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\sequential.py:372 call
        return super(Sequential, self).call(inputs, training=training, mask=mask)
    c:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\functional.py:386 call
        inputs, training=training, mask=mask)
    c:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\functional.py:508 _run_internal_graph
        outputs = node.layer(*args, **kwargs)
    c:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:976 __call__
        self.name)
    c:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\input_spec.py:216 assert_input_compatibility
        ' but received input with shape ' + str(shape))

    ValueError: Input 0 of layer dense_2 is incompatible with the layer: expected axis -1 of input shape to have value 50176 but received input with shape [None, 57600]
```
I had run the code on Google Colab with the same model and image and it works there, but it doesn't on my local computer

**Comment by amahendrakar** [comment]
@SeanLink11,
On running the given code snippet, I am facing an error stating `NameError: name 'self' is not defined`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/ce20278a9df4ed20a33316284122e530/45362.ipynb#scrollTo=W8b0FpBrHMW6).

In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and all the files required to run the code. 

Alternatively, you can share the gist of the Colab Notebook you are running. Thanks!

**Comment by SeanLink11** [comment]
Hi, I managed to get it to work, apparently, I was not sure why, but it works now
![image](https://user-images.githubusercontent.com/43125734/101020840-0c2e3780-35aa-11eb-988b-7407dc3a9cc4.png)

**Comment by SeanLink11** [comment]
@amahendrakar,
Hi, I have edited the code snippet for when it uses self, but do you want me to share the model and images so that you can test it?

**Comment by SeanLink11** [comment]
@amahendrakar I've been testing and I discovered is that if I pass the images with the dimension 224*224, then it works, other sizes doesn't, so I resize them to be that

**Comment by SeanLink11** [comment]
@amahendrakar I tested, and found that it doesn't need to be 224*224, as long as the dimensions' product is the same, which is equal to 50176, it works, however, for images of .tif extension, it doesn't work, why is that?

**Comment by amahendrakar** [comment]
> but do you want me to share the model and images so that you can test it?

@SeanLink11,
Yes please. Could you please share the latest code and the dataset so that we can reproduce the issue on our end. Thanks!
