### ISSUE TITLE
ValueError: Could not find matching function to call loaded from the SavedModel.

### ISSUE THREAD

**Issue by ardamavi** [tensorflow/tensorflow#45385]
Code:
```
import tensorflow as tf
from tensorflow.keras.layers import Input

model = tf.keras.models.load_model("Model")
print(model) # First line of output.

inputs = Input(shape=(1, 12, 12))
outputs = model(inputs) # Error appears on this line.
```
Output:
```
<tensorflow.python.saved_model.load.Loader._recreate_base_user_object.<locals>._UserObject object at 0x7fc5335efd00>

Traceback (most recent call last):
  File "example.py", line 12, in <module>
    outputs = model(inputs)
  File "/Users/name/opt/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py", line 509, in _call_attribute
    return instance.__call__(*args, **kwargs)
  File "/Users/name/opt/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/Users/name/opt/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 823, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/Users/name/opt/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 697, in _initialize
    *args, **kwds))
  File "/Users/name/opt/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2855, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/Users/name/opt/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/Users/name/opt/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3075, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/Users/name/opt/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/Users/name/opt/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 600, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/Users/name/opt/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/saved_model/function_deserialization.py", line 257, in restored_function_body
    "\n\n".join(signature_descriptions)))
ValueError: Could not find matching function to call loaded from the SavedModel. Got:
  Positional arguments (1 total):
    * Tensor("None_0:0", shape=(None, 1, 12, 12), dtype=float32)
  Keyword arguments: {}

Expected these arguments to match one of the following 1 option(s):

Option 1:
  Positional arguments (0 total):
    *
  Keyword arguments: {'main_input': TensorSpec(shape=(None, 1, 12, 12), dtype=tf.float32, name='main_input')}
```

**System information**
- Python 3.6.12
- Tensorflow 2.3.1 (CPU)
- Keras 2.4.3

**Comment by ravikyram** [comment]
@ardamavi 

Please,share `Model` file to reproduce the issue in our environment.It helps us in localizing the issue faster.Please, try with TF nightly versions as well and see if the issue still persists.

Thanks!

**Comment by ardamavi** [comment]
@ravikyram 
The model comes from outside, I cannot make changes on it.

When I try with TF nightly version I got this error:
`Cannot convert a symbolic Tensor to a numpy array. `
I am trying to call `model()` inside of `Lambda Layer` but I got the same error that I share first.

**Comment by jvishnuvardhan** [comment]
@ardamavi Can you please share simple standalone code? The current code is incomplete as the saved model is not uploaded. Can you please use any simple model to demonstrate the issue? Thanks!

**Comment by seongkyun** [comment]
I have exactly same problem.
Did you solve it?

**Comment by seongkyun** [comment]
I solved this problem.

your code:
<pre><code>
import tensorflow as tf
from tensorflow.keras.layers import Input

model = tf.keras.models.load_model("Model")
print(model) # First line of output.

inputs = Input(shape=(1, 12, 12))
outputs = model(inputs) # Error appears on this line.
</code></pre>

and change it as below:

<pre><code>
import tensorflow as tf
from tensorflow.keras.layers import Input

model = tf.keras.models.load_model("Model")
print(model) # First line of output.

inputs = Input(shape=(1, 12, 12))
inference = model.signatures["serving_default"]
outputs = inference(inputs) # Error appears on this line.
</code></pre>

then, it might work :)

**Comment by ardamavi** [comment]
> I solved this problem.
> 
> your code:
> 
> ```
> 
> import tensorflow as tf
> from tensorflow.keras.layers import Input
> 
> model = tf.keras.models.load_model("Model")
> print(model) # First line of output.
> 
> inputs = Input(shape=(1, 12, 12))
> outputs = model(inputs) # Error appears on this line.
> ```
> 
> and change it as below:
> 
> ```
> 
> import tensorflow as tf
> from tensorflow.keras.layers import Input
> 
> model = tf.keras.models.load_model("Model")
> print(model) # First line of output.
> 
> inputs = Input(shape=(1, 12, 12))
> inference = model.signatures["serving_default"]
> outputs = inference(inputs) # Error appears on this line.
> ```
> 
> then, it might work :)

@seongkyun
I try your suggestion, this time I get another error:
```
Traceback (most recent call last):
  File "/Users/name/opt/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: input_1:0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/name/opt/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1655, in __call__
    return self._call_impl(args, kwargs)
  File "/Users/name/opt/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1673, in _call_impl
    return self._call_with_flat_signature(args, kwargs, cancellation_manager)
  File "/Users/name/opt/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1722, in _call_with_flat_signature
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "/Users/name/opt/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py", line 106, in _call_flat
    cancellation_manager)
  File "/Users/name/opt/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/Users/name/opt/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/Users/name/opt/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 74, in quick_execute
    "tensors, but found {}".format(keras_symbolic_tensors))
tensorflow.python.eager.core._SymbolicException: Inputs to eager execution function cannot be Keras symbolic tensors, but found [<tf.Tensor 'input_1:0' shape=(None, 1, 12, 12) dtype=float32>]
```

**Comment by seongkyun** [comment]
type below at terminal then you can see the I/O shapes of the model:

$ saved_model_cli show --dir PATH/TO/PB/FILE --tag_set serve --signature_def serving_default

the PATH/TO/PB/FILE is the folder including asset, variables folders and saved_model.pb file.

Is the input shape correct?

**Comment by ardamavi** [comment]
> type below at terminal then you can see the I/O shapes of the model:
> 
> $ saved_model_cli show --dir PATH/TO/PB/FILE --tag_set serve --signature_def serving_default
> 
> the PATH/TO/PB/FILE is the folder including asset, variables folders and saved_model.pb file.
> 
> Is the input shape correct?

@seongkyun 
Yes, the input shape is correct:
```
dtype: DT_FLOAT
shape: (-1, 1, 12, 12)
```

**Comment by jvishnuvardhan** [comment]
@ardamavi Is this Sequential/Functional/Subclass model? 

Is it possible to take a simple public dataset and create a standalone code for us to reproduce your issue. Issue can be resolved faster with a Standalone code. Thanks!
