### ISSUE TITLE
error when load the model use keras.models.load_model

### ISSUE THREAD

**Issue by Jiaxin8122** [tensorflow/tensorflow#45443]
**System information**

- OS Platform: Windows10
- TensorFlow version: 2.3.1
- Python version: 3.8.4
- CPU

I used AutoKeras generate a model and saved as 'tf' format.
model.save('ak_best_model', save_format='tf')
Then i use:
keras.models.load_model('ak_best_model')   in the same script
It works well...

But i open a new script and use Keras load the same model, error occured:

RuntimeError: Unable to restore a layer of class Custom>MultiCategoryEncoding. Layers of class Custom>MultiCategoryEncoding require that the class be provided to the model loading code, either by registering the class using @keras.utils.register_keras_serializable on the class def and including that file in your program, or by passing the class in a keras.utils.CustomObjectScope that wraps this load call.

here is my script:

df = pd.read_excel('total.xlsx', dtype=np.float32)

y = df[['Static_Fric', 'Rolling_Fric']].values
x = df.drop(labels = ['Static_Fric', 'Rolling_Fric'], axis =1)

x_train, x_test, y_train, y_test = train_test_split(
    x, y,
    test_size=0.2,
    shuffle=True
    )
keras_model = load_model(r'D:\Program Files\Desktop\ML\AutoKeras\ak_best_model')

**Comment by amahendrakar** [comment]
@Jiaxin8122,
On running the code, I am facing an error stating `FileNotFoundError: [Errno 2] No such file or directory: 'total.xlsx'`.

In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and the dataset you are using. 

Also, please go through issue [#44199](https://github.com/tensorflow/tensorflow/issues/44199#issuecomment-730297817) with a similar error and let us know if it helps. Thanks!

**Comment by Jiaxin8122** [comment]
here is the dataset:
[total.xlsx](https://github.com/tensorflow/tensorflow/files/5652212/total.xlsx)

import numpy as np
import pandas as pd

from keras.models import load_model
from sklearn.model_selection import train_test_split

df = pd.read_excel('total.xlsx', dtype=np.float32)

y = df[['Static_Fric', 'Rolling_Fric']].values
x = df.drop(labels = ['Static_Fric', 'Rolling_Fric'], axis =1)

x_train, x_test, y_train, y_test = train_test_split(
    x, y,
    test_size=0.2,
    shuffle=True
    )

keras_model = load_model(r'D:\Program Files\Desktop\ML\AutoKeras\ak_best_model')

But my model based on training from AutoKeras...I saved it as 'tf' format.

The error:

Traceback (most recent call last):
  File "E:\Pycharm\pythonProject\venv\lib\site-packages\tensorflow\python\keras\saving\saved_model\load.py", line 416, in _revive_layer_from_config
    obj = layers_module.deserialize(
  File "E:\Pycharm\pythonProject\venv\lib\site-packages\tensorflow\python\keras\layers\serialization.py", line 171, in deserialize
    return generic_utils.deserialize_keras_object(
  File "E:\Pycharm\pythonProject\venv\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 346, in deserialize_keras_object
    (cls, cls_config) = class_and_config_for_serialized_keras_object(
  File "E:\Pycharm\pythonProject\venv\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 296, in class_and_config_for_serialized_keras_object
    raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
ValueError: Unknown layer: Custom>MultiCategoryEncoding
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "E:\Pycharm\pythonProject\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-5bbd59fbc60c>", line 1, in <module>
    runfile('D:/Program Files/Desktop/ML/Reinforcement/RL.py', wdir='D:/Program Files/Desktop/ML/Reinforcement')
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/Program Files/Desktop/ML/Reinforcement/RL.py", line 33, in <module>
    keras_model = load_model(r'D:\Program Files\Desktop\ML\AutoKeras\ak_best_model')
  File "E:\Pycharm\pythonProject\venv\lib\site-packages\tensorflow\python\keras\saving\save.py", line 187, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "E:\Pycharm\pythonProject\venv\lib\site-packages\tensorflow\python\keras\saving\saved_model\load.py", line 120, in load
    model = tf_load.load_internal(
  File "E:\Pycharm\pythonProject\venv\lib\site-packages\tensorflow\python\saved_model\load.py", line 632, in load_internal
    loader = loader_cls(object_graph_proto, saved_model_proto, export_dir,
  File "E:\Pycharm\pythonProject\venv\lib\site-packages\tensorflow\python\keras\saving\saved_model\load.py", line 194, in __init__
    super(KerasObjectLoader, self).__init__(*args, **kwargs)
  File "E:\Pycharm\pythonProject\venv\lib\site-packages\tensorflow\python\saved_model\load.py", line 130, in __init__
    self._load_all()
  File "E:\Pycharm\pythonProject\venv\lib\site-packages\tensorflow\python\keras\saving\saved_model\load.py", line 215, in _load_all
    self._layer_nodes = self._load_layers()
  File "E:\Pycharm\pythonProject\venv\lib\site-packages\tensorflow\python\keras\saving\saved_model\load.py", line 315, in _load_layers
    layers[node_id] = self._load_layer(proto.user_object, node_id)
  File "E:\Pycharm\pythonProject\venv\lib\site-packages\tensorflow\python\keras\saving\saved_model\load.py", line 341, in _load_layer
    obj, setter = self._revive_from_config(proto.identifier, metadata, node_id)
  File "E:\Pycharm\pythonProject\venv\lib\site-packages\tensorflow\python\keras\saving\saved_model\load.py", line 359, in _revive_from_config
    self._revive_layer_from_config(metadata, node_id))
  File "E:\Pycharm\pythonProject\venv\lib\site-packages\tensorflow\python\keras\saving\saved_model\load.py", line 420, in _revive_layer_from_config
    raise RuntimeError(
RuntimeError: Unable to restore a layer of class Custom>MultiCategoryEncoding. Layers of class Custom>MultiCategoryEncoding require that the class be provided to the model loading code, either by registering the class using @keras.utils.register_keras_serializable on the class def and including that file in your program, or by passing the class in a keras.utils.CustomObjectScope that wraps this load call.

best wishes!

**Comment by krishdb38** [comment]
@Jiaxin8122  did you solve the problem.
I am also facing the same problem
