### ISSUE TITLE
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above. [Op:Conv2D]

### ISSUE THREAD

**Issue by wanusic** [tensorflow/tensorflow#45458]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.1.0
- Python version: 3.6
- Installed using virtualenv? pip? conda?: conda 4.9.1
- Bazel version (if compiling from source): --
- GCC/Compiler version (if compiling from source): --
- CUDA/cuDNN version: cuda 10.1 / cudnn 7.6.5
- GPU model and memory: Geforce GTX 1650Ti, 4 GB, 7.5 capability 

**Describe the problem**
Application outputs an error message (tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above. [Op:Conv2D]). I have tensorflow-gpu 2.1.0 installed via conda. This error happened first when installing tensorflow via conda, and after I read other issues, some suggested installing via pip because of possible mismatch between conda installed cuda and cudnn. However, even with pip-installed tensorflow, I am still receiving this error. Error is persistent also for tensorflow 2.2.0. 

I have tried different version of cudnn (7.6.0, for cuda 10.1) but the error persists. I have system install of cuda and cudnn, and have set the environment variables as per [tensorflow guide](https://www.tensorflow.org/install/gpu).

**Any other info / logs**
`2020-12-09 18:25:30.256782: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-12-09 18:25:31.215117: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1650 Ti computeCapability: 7.5
coreClock: 1.485GHz coreCount: 16 deviceMemorySize: 4.00GiB deviceMemoryBandwidth: 178.84GiB/s
2020-12-09 18:25:31.215279: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-12-09 18:25:31.218433: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-12-09 18:25:31.220939: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-12-09 18:25:31.221819: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-12-09 18:25:31.225000: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-12-09 18:25:31.227314: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-12-09 18:25:31.240284: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-12-09 18:25:31.240428: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-12-09 18:25:31.240721: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-12-09 18:25:31.247163: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1a1643df6a0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-12-09 18:25:31.247314: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-12-09 18:25:31.247518: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1650 Ti computeCapability: 7.5
coreClock: 1.485GHz coreCount: 16 deviceMemorySize: 4.00GiB deviceMemoryBandwidth: 178.84GiB/s
2020-12-09 18:25:31.247692: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-12-09 18:25:31.247812: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-12-09 18:25:31.247930: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-12-09 18:25:31.248007: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-12-09 18:25:31.248105: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-12-09 18:25:31.248187: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-12-09 18:25:31.248283: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-12-09 18:25:31.248447: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-12-09 18:25:31.669306: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-12-09 18:25:31.669402: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-12-09 18:25:31.669453: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-12-09 18:25:31.669628: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2913 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1650 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
2020-12-09 18:25:31.672216: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1a101d2a3a0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-12-09 18:25:31.672324: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 1650 Ti, Compute Capability 7.5
2020-12-09 18:25:33.789645: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-12-09 18:25:34.661555: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
2020-12-09 18:25:34.662100: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
Traceback (most recent call last):
  File "A:\ProgramFiles\anaconda3\envs\tf-gpu\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 926, in conv2d
    "dilations", dilations)
tensorflow.python.eager.core._FallbackException: Expecting int64_t value for attr strides, got numpy.int32

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "A:/projekti/diplomski/train.py", line 61, in <module>
    run_train(yolo_model, num_epochs=2)
  File "A:/projekti/diplomski/train.py", line 39, in run_train
    y_preds = model(x_batch)
  File "A:\ProgramFiles\anaconda3\envs\tf-gpu\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 968, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "A:\ProgramFiles\anaconda3\envs\tf-gpu\lib\site-packages\tensorflow\python\keras\engine\network.py", line 719, in call
    convert_kwargs_to_constants=base_layer_utils.call_context().saving)
  File "A:\ProgramFiles\anaconda3\envs\tf-gpu\lib\site-packages\tensorflow\python\keras\engine\network.py", line 888, in _run_internal_graph
    output_tensors = layer(computed_tensors, **kwargs)
  File "A:\ProgramFiles\anaconda3\envs\tf-gpu\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 968, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "A:\ProgramFiles\anaconda3\envs\tf-gpu\lib\site-packages\tensorflow\python\keras\layers\convolutional.py", line 207, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "A:\ProgramFiles\anaconda3\envs\tf-gpu\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1106, in __call__
    return self.conv_op(inp, filter)
  File "A:\ProgramFiles\anaconda3\envs\tf-gpu\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 638, in __call__
    return self.call(inp, filter)
  File "A:\ProgramFiles\anaconda3\envs\tf-gpu\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 237, in __call__
    name=self.name)
  File "A:\ProgramFiles\anaconda3\envs\tf-gpu\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 2014, in conv2d
    name=name)
  File "A:\ProgramFiles\anaconda3\envs\tf-gpu\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 933, in conv2d
    data_format=data_format, dilations=dilations, name=name, ctx=_ctx)
  File "A:\ProgramFiles\anaconda3\envs\tf-gpu\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 1022, in conv2d_eager_fallback
    ctx=ctx, name=name)
  File "A:\ProgramFiles\anaconda3\envs\tf-gpu\lib\site-packages\tensorflow\python\eager\execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above. [Op:Conv2D]`

This is how i use convolution in code: 

`  

    def conv_norm_lrelu(inputs, filters, kernel_size, stride=1, training=True, **conv_kwargs):

        stride = tf.cast(stride, tf.int64)

        conv = tf.keras.layers.Conv2D(filters, kernel_size, strides=(stride, stride), padding='same', **conv_kwargs)(inputs)

        bn = tf.keras.layers.BatchNormalization(trainable=training)(conv)

        return tf.keras.layers.LeakyReLU(alpha=0.1)(bn)

`

**Comment by bhack** [comment]
We don't support ananconda here. Please use the default pip install in venv or try to get support at https://github.com/AnacondaRecipes/tensorflow_recipes

**Comment by wanusic** [comment]
@bhack If you read my post, you will see that I tried both pip and anaconda install

**Comment by bhack** [comment]
But pip inside a conda env?

**Comment by wanusic** [comment]
> But pip inside a conda env?

Yes, is that a problem?

**Comment by bhack** [comment]
Here we don't officially support conda also as env. It could work but It Is hard to get support in this repo for a conda setup.

Please try to make a clean install as in the official guide:
https://www.tensorflow.org/install/pip

**Comment by OfekShochat** [comment]
The issue is that another application uses the cudnn services. So you cant run two instances of training and using the network because its using it. If you are running lc0 in the background it could be it. Try to close it

**Comment by OfekShochat** [comment]
So it's not a "build/install"

**Comment by ravikyram** [comment]
@wanusic 

In order to reproduce the issue reported here, could you please provide the complete code and the dataset you are using.

Also, please go through issue #24828 with a similar error and let us know if it helps. Thanks!

**Comment by wanusic** [comment]
> @wanusic
> 
> In order to reproduce the issue reported here, could you please provide the complete code and the dataset you are using.
> 
> Also, please go through issue #24828 with a similar error and let us know if it helps. Thanks!

I have updated the stack trace. 

Possible issues:
-  Incompatibility between conda installed version of cuda and cudnn. I have removed these from anaconda, so I only have system wide install. Also conda list cuda, and conda list cudnn returns empty. 

-  Tensorflow GPU guide uses cudnn 7.6.x version, i have tried both highest (7.6.5) and lowest (7.6.0) while still supported by cuda 
    10.1 (Some people in #24828 mentioned downgrading or upgrading cudnn have helped, but none seem to work for me)

- Using config.gpu_options.allow_growth=True. I am using keras and tf.compat.v1.keras.backend.set_session doesn't take any arguments except session. I am not sure how to use this since I am not explicitly creating a tf.Session in my code (using functional api in keras).

**Comment by wanusic** [comment]
In the end I think this is a memory issue. I tried using config.gpu_options.per_process_gpu_memory_fraction = 0.4 which eliminates the cudnn issue. I think that cudnn tries to allocate the memory for the entire neural network at once which exceeds limitations of my memory so cudnn cannot allocate handle. Still dynamically allocating memory does not work because it will still exceed memory limitation. In my case, I need a smaller network or more memory :(
