### ISSUE TITLE
TFLite java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter on Android SDK 29

### ISSUE THREAD

**Issue by mynameisteodora** [tensorflow/tensorflow#45540]
Hello. I have a simple Android app connected to an accelerometer. I have a few tflite models in the app, one of which is throwing  a "Failed to run on the given Interpreter" error without any additional information. The code works fine on SDK 25.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android SDK 29
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Samsung Galaxy A20e, Android version 10
- TFLite version: "org.tensorflow:tensorflow-lite:1.13.1"

**Describe the current behavior**
When the interpreter is called on the Android 10 phone, this error is thrown: 
```
java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: 
2020-12-09 13:08:10.985 30085-30561/com.specknet.respeckmodeltesting W/System.err:     at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
2020-12-09 13:08:10.985 30085-30561/com.specknet.respeckmodeltesting W/System.err:     at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:145)
2020-12-09 13:08:10.985 30085-30561/com.specknet.respeckmodeltesting W/System.err:     at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:250)
2020-12-09 13:08:10.985 30085-30561/com.specknet.respeckmodeltesting W/System.err:     at com.specknet.respeckmodeltesting.classification.Classifier.classifyActivityWithFeatures(Classifier.kt:111)
2020-12-09 13:08:10.986 30085-30561/com.specknet.respeckmodeltesting W/System.err:     at com.specknet.respeckmodeltesting.live.LiveDataActivity$onCreate$2.onReceive(LiveDataActivity.kt:176)
2020-12-09 13:08:10.986 30085-30561/com.specknet.respeckmodeltesting W/System.err:     at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1646)
2020-12-09 13:08:10.986 30085-30561/com.specknet.respeckmodeltesting W/System.err:     at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
2020-12-09 13:08:10.986 30085-30561/com.specknet.respeckmodeltesting W/System.err:     at android.os.Handler.handleCallback(Handler.java:883)
2020-12-09 13:08:10.986 30085-30561/com.specknet.respeckmodeltesting W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:100)
2020-12-09 13:08:10.987 30085-30561/com.specknet.respeckmodeltesting W/System.err:     at android.os.Looper.loop(Looper.java:237)
2020-12-09 13:08:10.987 30085-30561/com.specknet.respeckmodeltesting W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:67)

```
**Describe the expected behavior**
The code works fine and classifies correctly when run on an Android 7.1.2 phone.
There is no code change between these two phones. Furthermore, other tflite models work on both phones. The only difference I see between the working models and the ones that crash are the conversion types. The models that crash have been "MLIR Converted" (inspected with Netron), and the models that do not crash are TOCO converted. 

Is there something preventing MLIR converted models from running on more recent Android versions? 

Thank you for your help.

**Comment by abattery** [comment]
The TFLite runtime version should be the same version with or higher version than the TFLite converter Python version.

For example, if you convert the model with TF 1.15, you need to use TFLite runtime version 1.15 at least.

Could you make sure that your TFLite runtime version is aligned with the TFLite converter Python version, which is used for the TFLite model generation, especially regarding MLIR converted models?

**Comment by mynameisteodora** [comment]
I do not have access to the original model unfortunately, but I tried importing the model as per the instructions here: https://www.tensorflow.org/lite/guide/android and this way it works. So it must be the way I was doing it before might be deprecated?

**Comment by abattery** [comment]
@mynameisteodora can you share what the difference was for the other users?
