### ISSUE TITLE
raise ValueError("Shapes %s and %s are incompatible" % (self, other)) ValueError: Shapes (2, 56, 56, 1024) and () are incompatible

### ISSUE THREAD

**Issue by Malithi-gif** [tensorflow/tensorflow#45566]
Traceback (most recent call last):
  File "main.py", line 191, in <module>
    tf.app.run()
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "main.py", line 187, in main
    run_training()
  File "main.py", line 164, in run_training
    loss_align_reg, vs_train_op, vs_eval_op, offset_pred, loss_reg = model.construct_model()
  File "C:\Users\User\Desktop\video search\TALL-master\ctrl_model.py", line 167, in construct_model
    sim_reg_mat, sim_reg_mat_test = self.visual_semantic_infer(self.visual_featmap_ph_train, self.sentence_ph_train, self.visual_featmap_ph_test, self.sentence_ph_test)
  File "C:\Users\User\Desktop\video search\TALL-master\ctrl_model.py", line 78, in visual_semantic_infer
    cross_modal_vec_train = self.cross_modal_comb(transformed_clip_train_norm, transformed_sentence_train_norm, self.batch_size)
  File "C:\Users\User\Desktop\video search\TALL-master\ctrl_model.py", line 59, in cross_modal_comb
    concat_feature = tf.reshape(tf.concat(2,[vv_feature, ss_feature]),[batch_size, batch_size, self.semantic_size+self.semantic_size])
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\util\dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\ops\array_ops.py", line 1297, in concat
    tensor_shape.scalar())
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\framework\tensor_shape.py", line 1103, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (2, 56, 56, 1024) and () are incompatible

Can anyone fix this issue?

**Comment by Saduf2019** [comment]
@Malithi-gif 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]

**Comment by Malithi-gif** [comment]
After updating TensorFlow it was fixed.

Thank you

**Comment by Saduf2019** [comment]
@Malithi-gif 
Glad the issue is resolved, please move this to closed status.

**Comment by Malithi-gif** [comment]
Saduf2019 again it happens. Tensorflow Version: 2.3.1

**Comment by Saduf2019** [comment]
@Malithi-gif 
As requested before please share information for us to analyse[ or if possible share  a colab gist with the error], can you upgrade tf and check if the issue persist.

**Comment by Malithi-gif** [comment]
Saduf2019 I'm trying to run temporary activity localization code, written in Python and TensorFlow. Code is too long. I will share it.

**Comment by mihaimaruseac** [comment]
Please minimize code. Likely, as the error suggests, this is an error on your side.
