### ISSUE TITLE
Object Detection doesn't work

### ISSUE THREAD

**Issue by CloneHub94** [tensorflow/tensorflow#45586]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- Windows
- TensorFlow installed from source:
- TensorFlow version 2.3.1
- Python version 3.8.3
- CUDA/cuDNN version 11.1, 11, 10.1, and 9.0 installed on my pc
- GPU model: GeForce GTX 1050 (4 GB of memory)

**Actual Behavior**
When I run the script I use to do object_detection on a selection of images the script ran to the end without actually doing anything. Outputting to the terminal:

Running inference image001.jpg... Done

After some time it started producing a new error at "detections = detect_fn(input_tensor)":

```
PS C:\Users\mauri> & C:/Users/mauri/AppData/Local/Programs/Python/Python38/python.exe d:/Maurice_Doc/AI/Tensorflow/scripts/preprocessing/detect_object.py
2020-12-10 22:17:31.572529: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-12-10 22:17:45.294140: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-12-10 22:17:46.342342: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1050 computeCapability: 6.1
coreClock: 1.493GHz coreCount: 5 deviceMemorySize: 4.00GiB deviceMemoryBandwidth: 104.43GiB/s
2020-12-10 22:17:46.343628: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-12-10 22:17:46.362359: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-12-10 22:17:46.385461: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-12-10 22:17:46.411085: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-12-10 22:17:46.441132: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-12-10 22:17:46.458760: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-12-10 22:17:46.492894: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-12-10 22:17:46.493462: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-12-10 22:17:46.494738: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-12-10 22:17:46.532117: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1ffbf1b1960 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-12-10 22:17:46.537696: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-12-10 22:17:46.538486: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 1050 computeCapability: 6.1
coreClock: 1.493GHz coreCount: 5 deviceMemorySize: 4.00GiB deviceMemoryBandwidth: 104.43GiB/s
2020-12-10 22:17:46.561378: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-12-10 22:17:46.562003: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-12-10 22:17:46.565033: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-12-10 22:17:46.565437: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-12-10 22:17:46.565838: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-12-10 22:17:46.568388: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-12-10 22:17:46.568766: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-12-10 22:17:46.569282: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-12-10 22:17:47.930696: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-12-10 22:17:47.931148: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-12-10 22:17:47.931566: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N
2020-12-10 22:17:47.932159: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2993 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050, pci bus id: 0000:01:00.0, compute capability: 6.1)
2020-12-10 22:17:47.955511: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1ffdb384350 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-12-10 22:17:47.969376: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 1050, Compute Capability 6.1
2020-12-10 22:18:53.677422: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-12-10 22:18:55.271299: W tensorflow/stream_executor/gpu/redzone_allocator.cc:314] Internal: Invoking GPU asm compilation is supported on Cuda non-Windows platforms only
Relying on driver to perform ptx compilation.
Modify $PATH to customize ptxas location.
This message will be only logged once.
2020-12-10 22:18:55.441293: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
Running inference for bdc1db0ac17.jpg... Done
Running inference for test.png... Traceback (most recent call last):
  File "d:/Maurice_Doc/AI/Tensorflow/scripts/preprocessing/detect_object.py", line 59, in <module>
    detections = detect_fn(input_tensor)
  File "C:\Users\mauri\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\saved_model\load.py", line 486, in _call_attribute
    return instance.__call__(*args, **kwargs)
  File "C:\Users\mauri\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\mauri\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\def_function.py", line 618, in _call
    results = self._stateful_fn(*args, **kwds)
  File "C:\Users\mauri\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 2419, in __call__
    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
  File "C:\Users\mauri\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 2734, in _maybe_define_function
    args, kwargs = self._function_spec.canonicalize_function_inputs(
  File "C:\Users\mauri\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 2235, in canonicalize_function_inputs
    inputs = _convert_inputs_to_signature(
  File "C:\Users\mauri\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 2304, in _convert_inputs_to_signature
    raise ValueError("Python inputs incompatible with input_signature:\n%s" %
ValueError: Python inputs incompatible with input_signature:
  inputs: (
    tf.Tensor(
[[[[255 255 255 255]
   [255 255 255 255]
   [255 255 255 255]
   ...
   [255 255 255 255]
   [255 255 255 255]
   [255 255 255 255]]

  [[255 255 255 255]
   [255 255 255 255]
   [255 255 255 255]
   ...
   [255 255 255 255]
   [255 255 255 255]
   [255 255 255 255]]

  [[255 255 255 255]
   [255 255 255 255]
   [255 255 255 255]
   ...
   [255 255 255 255]
   [255 255 255 255]
   [255 255 255 255]]

  ...

  [[255 255 255 255]
   [255 255 255 255]
   [255 255 255 255]
   ...
   [255 255 255 255]
   [255 255 255 255]
   [255 255 255 255]]

  [[255 255 255 255]
   [255 255 255 255]
   [255 255 255 255]
   ...
   [255 255 255 255]
   [255 255 255 255]

  [[255 255 255 255]
   [255 255 255 255]
   [255 255 255 255]
   ...
   [255 255 255 255]
   [255 255 255 255]
   [255 255 255 255]]]], shape=(1, 480, 640, 4), dtype=uint8))
  input_signature: (
    TensorSpec(shape=(1, None, None, 3), dtype=tf.uint8, name='input_tensor'))
```

**Expected Behavior**

The expected behavior is that it should display the images with the detected objects based on the trained model that I have. As shown in the example here(https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/auto_examples/plot_object_detection_saved_model.html#load-the-model)

I've tried changing matplotlib.rcParams withing the script too matplotlib.rcParams['backend'] = "Qt4Agg".
I've tried changing  backend in config/matplotlib/matplotlibrc to backend:qt4agg aswell as other values.
For the second error I've deleting and recreating the saved_model.pb file but nothing seems to solve the problem.

**Source Code**

```
import numpy as np
import os
from PIL import Image
import tensorflow as tf
from object_detection.utils import label_map_util
from object_detection.utils import visualization_utils as viz_utils
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')   # Suppress Matplotlib warnings

category_index = label_map_util.create_category_index_from_labelmap("D:/Maurice_Doc/AI/Tensorflow/workspace/training_demo/images/annotations/label_map.pbtxt",
                                                                    use_display_name=True)

os.chdir('D:/Maurice_Doc/AI/Tensorflow/workspace/training_demo/images/test')
IMAGE_PATHS =os.listdir()
detect_fn = tf.saved_model.load("D:/Maurice_Doc/AI/Tensorflow/workspace/training_demo/exported-models/my_model/saved_model")

def load_image_into_numpy_array(path):
    """Load an image from file into a numpy array.

    Puts image into numpy array to feed into tensorflow graph.
    Note that by convention we put it into a numpy array with shape
    (height, width, channels), where channels=3 for RGB.

    Args:
      path: the file path to the image

    Returns:
      uint8 numpy array with shape (img_height, img_width, 3)
    """
    return np.array(Image.open(path))


for image_path in IMAGE_PATHS:

    print('Running inference for {}... '.format(image_path), end='')

    image_np = load_image_into_numpy_array(image_path)

    # Things to try:
    # Flip horizontally
    # image_np = np.fliplr(image_np).copy()

    # Convert image to grayscale
    # image_np = np.tile(
    #     np.mean(image_np, 2, keepdims=True), (1, 1, 3)).astype(np.uint8)

    # The input needs to be a tensor, convert it using `tf.convert_to_tensor`.
    input_tensor = tf.convert_to_tensor(image_np)
    # The model expects a batch of images, so add an axis with `tf.newaxis`.
    input_tensor = input_tensor[tf.newaxis, ...]

    # input_tensor = np.expand_dims(image_np, 0)
    detections = detect_fn(input_tensor)

    # All outputs are batches tensors.
    # Convert to numpy arrays, and take index [0] to remove the batch dimension.
    # We're only interested in the first num_detections.
    num_detections = int(detections.pop('num_detections'))
    detections = {key: value[0, :num_detections].numpy()
                   for key, value in detections.items()}
    detections['num_detections'] = num_detections

    # detection_classes should be ints.
    detections['detection_classes'] = detections['detection_classes'].astype(np.int64)

    image_np_with_detections = image_np.copy()

    viz_utils.visualize_boxes_and_labels_on_image_array(
          image_np_with_detections,
          detections['detection_boxes'],
          detections['detection_classes'],
          detections['detection_scores'],
          category_index,
          use_normalized_coordinates=True,
          max_boxes_to_draw=200,
          min_score_thresh=.30,
          agnostic_mode=False)

    plt.figure()
    plt.imshow(image_np_with_detections)
    print('Done')
plt.show()

```
Has someone possibly had this same issue or know how I could solve it?

**Comment by amahendrakar** [comment]
@CloneHub94,
Issues related to TensorFlow object detection module are tracked in the tensorflow/models repo. 

Could you please submit a new issue from [this link](https://github.com/tensorflow/models/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!
