### ISSUE TITLE
tensorflow.python.framework.errors_impl.UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.

### ISSUE THREAD

**Issue by zaheerbeg21** [tensorflow/tensorflow#45616]
## My machine have - Cuda Version - 10.1.105, ##cuDNN Version - 7.6 , ##Device - GeForce GTX 1660 SUPER 
##Tensorflow - 2.3.1 , ##Python 3.8.3 , O.S - Windows 10
=====================================================
E:\xtreme_vision_yolo>python train_yolov4.py
2020-12-12 02:49:01.254777: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
class path E:/xtreme_vision_yolo/classes.names
train images file E:/xtreme_vision_yolo/train_images_file.txt
train image dir E:/xtreme_vision_yolo/train_img_dir/
2020-12-12 02:49:18.534478: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library nvcuda.dll
2020-12-12 02:49:18.585778: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 1660 SUPER computeCapability: 7.5
coreClock: 1.785GHz coreCount: 22 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 312.97GiB/s
2020-12-12 02:49:18.594476: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2020-12-12 02:49:19.157955: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
2020-12-12 02:49:19.495738: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cufft64_10.dll
2020-12-12 02:49:19.529529: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library curand64_10.dll
2020-12-12 02:49:19.880640: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusolver64_10.dll
2020-12-12 02:49:20.170330: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusparse64_10.dll
2020-12-12 02:49:20.477234: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2020-12-12 02:49:20.482540: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-12-12 02:49:20.487618: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-12-12 02:49:20.508225: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x25fa6271050 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-12-12 02:49:20.516217: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-12-12 02:49:20.524054: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 1660 SUPER computeCapability: 7.5
coreClock: 1.785GHz coreCount: 22 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 312.97GiB/s
2020-12-12 02:49:20.536073: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2020-12-12 02:49:20.543032: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
2020-12-12 02:49:20.548638: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cufft64_10.dll
2020-12-12 02:49:20.554466: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library curand64_10.dll
2020-12-12 02:49:20.559750: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusolver64_10.dll
2020-12-12 02:49:20.566821: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusparse64_10.dll
2020-12-12 02:49:20.572949: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2020-12-12 02:49:20.580348: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-12-12 02:49:22.507429: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-12-12 02:49:22.513254: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0
2020-12-12 02:49:22.517366: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N
2020-12-12 02:49:22.521455: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4618 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1660 SUPER, pci bus id: 0000:01:00.0, compute capability: 7.5)
2020-12-12 02:49:22.533883: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x25fd40d41e0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-12-12 02:49:22.542623: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 1660 SUPER, Compute Capability 7.5
Downloading weights file...
Please wait...
2020-12-12 02:49:34.825447: I tensorflow/core/profiler/lib/profiler_session.cc:164] Profiler session started.
2020-12-12 02:49:34.829432: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1391] Profiler found 1 GPUs
2020-12-12 02:49:34.835081: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cupti64_101.dll'; dlerror: cupti64_101.dll not found
2020-12-12 02:49:34.843967: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cupti.dll'; dlerror: cupti.dll not found
2020-12-12 02:49:34.850964: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1441] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI could not be loaded or symbol could not be found.

Epoch 00001: LearningRateScheduler reducing learning rate to tf.Tensor(9.0483736e-05, shape=(), dtype=float32).
Epoch 1/500
2020-12-12 02:50:13.332541: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2020-12-12 02:50:14.779540: E tensorflow/stream_executor/cuda/cuda_dnn.cc:328] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
2020-12-12 02:50:14.789174: E tensorflow/stream_executor/cuda/cuda_dnn.cc:328] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
Traceback (most recent call last):
  File "train_yolov4.py", line 18, in <module>
    model.train(epochs=500, lr=1e-4, steps_per_epoch=400)
  File "C:\ProgramData\Anaconda3\lib\site-packages\xtreme_vision\Detection\Custom\yolo.py", line 186, in train
    self.model.fit(
  File "C:\ProgramData\Anaconda3\lib\site-packages\xtreme_vision\Detection\yolov4\tf\__init__.py", line 260, in fit
    self.model.fit(
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1098, in fit
    tmp_logs = train_function(iterator)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\eager\def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\eager\def_function.py", line 840, in _call
    return self._stateless_fn(*args, **kwds)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\eager\function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\eager\function.py", line 1843, in _filtered_call
    return self._call_flat(
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\eager\function.py", line 1923, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\eager\function.py", line 545, in call
    outputs = execute.execute(
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node YOLOv4/CSPDarknet53/yolo_conv2d/sequential/conv2d/Conv2D (defined at C:\ProgramData\Anaconda3\lib\site-packages\xtreme_vision\Detection\yolov4\model\common.py:92) ]] [Op:__inference_train_function_54586]

Errors may have originated from an input operation.
Input Source operations connected to node YOLOv4/CSPDarknet53/yolo_conv2d/sequential/conv2d/Conv2D:
 IteratorGetNext (defined at C:\ProgramData\Anaconda3\lib\site-packages\xtreme_vision\Detection\yolov4\tf\__init__.py:260)

Function call stack:
train_function
## Kindly suggest solution

**Comment by Saduf2019** [comment]
@zaheerbeg21 
Please refer to these resolved issue with same error and let us know: #44885 #43764 #45458

**Comment by zaheerbeg21** [comment]
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you.

No issue is same as before..

**Comment by jvishnuvardhan** [comment]
@zaheerbeg21 Can you please explain your issue with little more details? Do you have any issue running TF only on GPU? Did you try to run any simple model with GPU? Can you please share any simple standalone code to reproduce the issue? thanks!
