### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xXX in position YY : invalid continuation byte

### ISSUE THREAD

**Issue by AphroMad** [tensorflow/tensorflow#45617]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): I'm trying to adapt a code that I found the code [here](https://medium.com/@martin.lees/image-recognition-with-machine-learning-in-python-and-tensorflow-b893cd9014d2). But this code doesn't work (well, I have an error)
- OS Platform and Distribution : Windows 10
- TensorFlow version (use command below):TF 2.0
- Python version: 3.8

**Describe the current behavior**
Run, but got this UnicodeDecodeError at the end so it stops. 

**Describe the expected behavior**
Should run without the error at the end. 

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
ATTENTION RESULTAT  0.8888889 #% it's not a mistake, I just put 5 pic in each folder just to see if it was working
Traceback (most recent call last):

  File "D:\pokemon\PogoBot\PoGo-Adb\ml_test_data_test.py", line 108, in <module>
    tf.app.run(main=main)

  File "C:\Users\pierr\anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)

  File "C:\Users\pierr\anaconda3\lib\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)

  File "C:\Users\pierr\anaconda3\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))

  File "D:\pokemon\PogoBot\PoGo-Adb\ml_test_data_test.py", line 104, in main
    saver.save(sess, "./model")

  File "C:\Users\pierr\anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1183, in save
    model_checkpoint_path = sess.run(

  File "C:\Users\pierr\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 957, in run
    result = self._run(None, fetches, feed_dict, options_ptr,

  File "C:\Users\pierr\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1180, in _run
    results = self._do_run(handle, final_targets, final_fetches,

  File "C:\Users\pierr\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1358, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,

  File "C:\Users\pierr\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1365, in _do_call
    return fn(*args)

  File "C:\Users\pierr\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1349, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,

  File "C:\Users\pierr\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1441, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 109: invalid continuation byte
```

**Standalone code to reproduce the issue**
````
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
import cv2
from os import listdir
from os.path import isfile, join
import numpy as np
import tensorflow as tf2
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import math



class Capchat:
    data_dir = "data_test//"
    nb_categories = 9
    X_train = None # X is the data array
    Y_train = None # Y is the labels array, you'll see this notation pretty often
    
    train_nb = 0 # number of train images
    X_test = None
    Y_test = None
    test_nb = 0 # number of tests images
    index = 0 # the index of the array we will fill 
    def readimg(self, file, label, train = True):
        im = cv2.imread(file); # read the image to PIL image
        im = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY).flatten() # put it in black and white and as a vector
        # the train var definies if we fill the training dataset or the test dataset
        if train : 
            self.X_train[self.index] = im
            self.Y_train[self.index][label - 1] = 1
        else :
            self.X_test[self.index] = im
            self.Y_test[self.index][label - 1] = 1
        self.index += 1
    def __init__(self):
        total_size = [f for f in listdir(self.data_dir + "1/") if isfile(join(self.data_dir + "1/", f))].__len__() # ge the total size of the dataset
        self.train_nb = math.floor(total_size * 0.8) # we get 80% of the data to train
        self.test_nb = math.ceil(total_size *0.2) # 20% to test
        
        # We fill the arrays with zeroes 840 is the number of pixels in an image
        self.X_train = np.zeros((self.train_nb*self.nb_categories, 735), np.int32)
        self.Y_train = np.zeros((self.train_nb*self.nb_categories, 3), np.int32)
        self.X_test = np.zeros((self.test_nb*self.nb_categories, 735), np.int32)
        self.Y_test = np.zeros((self.test_nb*self.nb_categories, 3), np.int32)
        # grab all the files 
        files_1 = [f for f in listdir(self.data_dir+"1/") if isfile(join(self.data_dir+"1/", f))]
        files_2 = [f for f in listdir(self.data_dir+"2/") if isfile(join(self.data_dir+"2/", f))]
        files_3 = [f for f in listdir(self.data_dir+"3/") if isfile(join(self.data_dir+"3/", f))]

        for i in range(self.train_nb):
            # add all the files to training dataset
            self.readimg(self.data_dir+"1/"+files_1[i], 1)
            self.readimg(self.data_dir+"2/"+files_2[i], 2)
            self.readimg(self.data_dir+"3/"+files_3[i], 3)

        self.index = 0
        
        for i  in range (self.train_nb, self.train_nb + self.test_nb):
            self.readimg(self.data_dir+"1/" + files_1[i], 1, False)
            self.readimg(self.data_dir+"2/" + files_2[i], 2, False)
            self.readimg(self.data_dir+"3/" + files_3[i], 3, False)
        print("donnée triée")


def main(_):
  # Import the data
  cap = Capchat()
  # Create the model
  x = tf.placeholder(tf.float32, [None, 735])
  W = tf.Variable(tf.zeros([735, 3]), name="weights")
  b = tf.Variable(tf.zeros([3]), name="biases")
  mult = tf.matmul(x, W) # W * X...
  y = tf.add(mult, b, name="calc") # + b
  # Define loss and optimizer
  y_ = tf.placeholder(tf.float32, [None, 3])
  # cost function
  cross_entropy = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=y_, logits=y))
  # optimizer
  train_step = tf.train.GradientDescentOptimizer(0.5).minimize(cross_entropy)
  # allows to save the model later
  saver = tf.train.Saver()
  # start a session to run the network on
  sess = tf.InteractiveSession()
  # initialize global variables
  tf.global_variables_initializer().run()
  # Train for 1000 steps, notice the cap.X_train and cap.Y_train
  for _ in range(1000):
    sess.run(train_step, feed_dict={x: cap.X_train, y_: cap.Y_train})
  # Extract one hot encoded output via argmax
  correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(y_, 1))
  # Test for accuraccy on the testset, notice the cap.X_test and cap.Y_test
  accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
  print("\nATTENTION RESULTAT ",sess.run(accuracy, feed_dict={x: cap.X_test,
                                      y_: cap.Y_test}))
  # save the model learned weights and biases
  saver.save(sess, "./model")
  
  
if __name__ == '__main__':
  tf.app.run(main=main)

**Comment by mihaimaruseac** [comment]
I see you are using TF 2.0. Can you try TF 2.3 please? Or, 2.4, it is supposed to come out next Monday (but there are release candidates now)

**Comment by AphroMad** [comment]
> I see you are using TF 2.0. Can you try TF 2.3 please? Or, 2.4, it is supposed to come out next Monday (but there are release candidates now)

I just did this, I still got the problem sir :(

**Comment by aaronmondal** [comment]
Could it be that you are using invalid folder names or printing non-standard symbols? A `UnicodeDecodeError` may indicate that some string (e.g. a filename, foldername or print statement) you are using is not a valid UTF-8 string: https://stackoverflow.com/questions/5552555/unicodedecodeerror-invalid-continuation-byte

**Comment by AphroMad** [comment]
> Could it be that you are using invalid folder names or printing non-standard symbols? A `UnicodeDecodeError` may indicate that some string (e.g. a filename, foldername or print statement) you are using is not a valid UTF-8 string: https://stackoverflow.com/questions/5552555/unicodedecodeerror-invalid-continuation-byte

At the end, the error was caused by this line : 
`saver.save(sess, "./model")`
Because I'm on windows, the computer didn't like this line, so I changed it with 
`saver.save(sess, "model\\model")`

Thank you for helping guys, this message really helped me ! :)

**Comment by KeoYang** [comment]
OS Platform and Distribution : Windows 10
TensorFlow version (use command below):TF 2.2.0
Python version: 3.7

when copy project: [tensorflow/object_detection](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/object_detection_tutorial.ipynb)
label_map_util.create_category_index_from_labelmap(PATH_TO_LABELS, use_display_name=True)
occur the same error, I solved the bug by
chage path
`PATH_TO_LABELS = models/research/object_detection/data/mscoco_label_map.pbtxt`
to
`PATH_TO_LABELS = D:\\Users\\models-master\\models-master\\research\\object_detection\\data\\mscoco_label_map.pbtxt`
