### ISSUE TITLE
RTX 3060 TI, creating GPU device take about 5 Minutes

### ISSUE THREAD

**Issue by Doev** [tensorflow/tensorflow#45635]
Windows 10 Prof.
RTX 3060 TI
TensorFlow 2.1.0
Installer: Anaconda

Note: Same with Ubuntu 20.04 LTS and PIP Installing

Code:

```
import tensorflow as tf
tf.test.is_gpu_available()
```
Output:

WARNING:tensorflow:From <stdin>:1: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
2020-12-13 10:23:03.545074: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2020-12-13 10:23:03.555731: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-12-13 10:23:03.609505: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce RTX 3060 Ti computeCapability: 8.6
coreClock: 1.665GHz coreCount: 38 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 417.29GiB/s
2020-12-13 10:23:03.621055: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-12-13 10:23:03.636314: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-12-13 10:23:03.649406: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-12-13 10:23:03.657126: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-12-13 10:23:03.672274: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-12-13 10:23:03.682682: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-12-13 10:23:03.704980: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-12-13 10:23:03.709446: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-12-13 10:28:51.751301: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-12-13 10:28:51.758864: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0
2020-12-13 10:28:51.763278: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N
2020-12-13 10:28:51.768347: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device 

**<---- about 5 minutes nothing ---->**

(/device:GPU:0 with 6281 MB memory) -> physical GPU (device: 0, name: GeForce RTX 3060 Ti, pci bus id: 0000:01:00.0, compute capability: 8.6)
True

**Comment by Doev** [comment]
another Test based on this paper:

```
import tensorflow as tf
import time

mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

start = time.time()

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

end = time.time()
print("Time delta: ", end - start)
```

Output: Time delta:  218.35683226585388

**Comment by ravikyram** [comment]
@Doev 

Just to verify are you facing the same issue with latest stable TF version 2.3 and nightly versions as well? 
Thanks!

**Comment by Doev** [comment]
I found out, that it is not the amount of training data, but the number of trainable parameters that causes the delay.

With tensorflow-gpu 2.3 (Anaconda), I have the problem, that is only running at the cpu. I will try to setup and virtual environement with pip, that is the same as another px with an GTS 450 Ti.

So far I have no idea how to use the nightly build.

**Comment by Doev** [comment]
The Problem with Tensorflow-gpu 2.3 (Anaconda) is, that it does not install cudnn correctly and for that, it goes with the cpu.

I copyed the the virtual environemnt (tf 2.3) from the pc with the good running GTS 1050 Ti and have the same problem (Long delays while starting tf or before first training).

I would test the nightly, but currently, I am not able to install it.

**Comment by Doev** [comment]
[W 09:24:27.040 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20201214092417 (::1) 10.03ms referer=http://localhost:8888/notebooks/Untitled.ipynb
[I 09:24:27.262 NotebookApp] Kernel started: 4c268691-1393-4bc4-860d-f2264de97874, name: python3
2020-12-14 09:24:30.113136: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
[I 09:26:27.238 NotebookApp] Saving file at /Untitled.ipynb
2020-12-14 09:27:37.473538: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library nvcuda.dll
2020-12-14 09:27:37.505228: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce RTX 3060 Ti computeCapability: 8.6
coreClock: 1.665GHz coreCount: 38 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 417.29GiB/s
2020-12-14 09:27:37.505433: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2020-12-14 09:27:37.525331: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
2020-12-14 09:27:37.531209: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cufft64_10.dll
2020-12-14 09:27:37.534229: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library curand64_10.dll
2020-12-14 09:27:37.541114: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusolver64_10.dll
2020-12-14 09:27:37.544944: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusparse64_10.dll
2020-12-14 09:27:37.557576: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2020-12-14 09:27:37.557832: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-12-14 09:27:37.559870: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-12-14 09:27:37.570839: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x201435ac8f0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-12-14 09:27:37.570934: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-12-14 09:27:37.571772: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce RTX 3060 Ti computeCapability: 8.6
coreClock: 1.665GHz coreCount: 38 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 417.29GiB/s
2020-12-14 09:27:37.572394: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2020-12-14 09:27:37.573126: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
2020-12-14 09:27:37.573677: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cufft64_10.dll
2020-12-14 09:27:37.576330: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library curand64_10.dll
2020-12-14 09:27:37.578139: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusolver64_10.dll
2020-12-14 09:27:37.580568: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusparse64_10.dll
2020-12-14 09:27:37.581116: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2020-12-14 09:27:37.582098: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0

**Comment by Doev** [comment]
I will now test the nightly: tf_nightly-2.5.0.dev20201213-cp38-cp38-win_amd64.whl

`import tensorflow as tf`

 ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\doev\venv\tf_nightly\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\doev\venv\tf_nightly\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\doev\venv\tf_nightly\lib\site-packages\tensorflow\python\eager\context.py", line 29, in <module>
    import numpy as np
  File "C:\Users\doev\venv\tf_nightly\lib\site-packages\numpy\__init__.py", line 305, in <module>
    _win_os_check()
  File "C:\Users\doev\venv\tf_nightly\lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
    raise RuntimeError(msg.format(__file__)) from None
RuntimeError: The current Numpy installation ('C:\\Users\\doev\\venv\\tf_nightly\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86

**Comment by ymodak** [comment]
TF 2.X packages come with gpu support however if the gpu environment setup is not compatible it silently falls back on cpu for computations.
TensorFlow 2.4 pip packages are built with CUDA11 and cuDNN 8.0.2.
See TF gpu, cuda cudnn [compatibility matrix](https://github.com/tensorflow/tensorflow/releases/tag/v2.4.0)

**Comment by Doev** [comment]
Actually I get an new error:

Windows 10
virtual environment / pip: Tensorflow 2.4.0
GPU-Driver: 460.79
cuda_11.0.2_451.48_win10
cudnn-11.0-windows-x64-v8.0.2.39

Everything works no without delays until I call modell.fit:

### python error:

UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node model/conv2d/Relu (defined at <ipython-input-1-3ca5da3d7565>:35) ]] [Op:__inference_train_function_3041]

### commandline:

2020-12-15 15:14:23.681512: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-12-15 15:14:23.683266: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce RTX 3060 Ti computeCapability: 8.6
coreClock: 1.665GHz coreCount: 38 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 417.29GiB/s
2020-12-15 15:14:23.683427: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2020-12-15 15:14:23.683584: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2020-12-15 15:14:23.683754: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2020-12-15 15:14:23.683895: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2020-12-15 15:14:23.684031: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2020-12-15 15:14:23.684189: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2020-12-15 15:14:23.684326: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2020-12-15 15:14:23.684453: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2020-12-15 15:14:23.684649: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2020-12-15 15:14:25.689226: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-12-15 15:14:25.689412: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0
2020-12-15 15:14:25.689792: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N
2020-12-15 15:14:25.692672: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6617 MB memory) -> physical GPU (device: 0, name: GeForce RTX 3060 Ti, pci bus id: 0000:01:00.0, compute capability: 8.6)
2020-12-15 15:14:25.697317: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-12-15 15:14:42.325717: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2020-12-15 15:14:44.210420: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2020-12-15 15:14:46.178140: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2020-12-15 15:14:46.219817: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2020-12-15 15:14:48.158021: E tensorflow/stream_executor/cuda/cuda_dnn.cc:336] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2020-12-15 15:14:48.158231: E tensorflow/stream_executor/cuda/cuda_dnn.cc:340] Error retrieving driver version: Unimplemented: kernel reported driver version not implemented on Windows
2020-12-15 15:14:48.162046: E tensorflow/stream_executor/cuda/cuda_dnn.cc:336] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2020-12-15 15:14:48.162241: E tensorflow/stream_executor/cuda/cuda_dnn.cc:340] Error retrieving driver version: **Unimplemented: kernel reported driver version not implemented on Windows**
2020-12-15 15:14:48.162715: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at conv_ops_fused_impl.h:697 : Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.

**Comment by Doev** [comment]
A simple mnist-test-network with flatten, dense and dropout layers works fine on the gpu.

**Comment by ymodak** [comment]
Can you try [limiting gpu memory growth](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth)? Shut down all your python processes and in new session/colab try your example.
```python
#On top of your script
import tensorflow as tf
gpus = tf.config.experimental.list_physical_devices('GPU')
tf.config.experimental.set_visible_devices(gpus[0], 'GPU')
# Rest of your code
 ...
```

**Comment by Doev** [comment]
I used the same code to compare two environemnts:

1) Windows 10, GTX 1050 Ti, TF 2.3.1
2) Windows 10, RTX 3060 Ti, TF 2.4.0

The code runs as expected on environment 1 with no error-messages on the console. It fails on environment 2 and the error messages are already pasted above.

The code above to limiting gpu memory shows no effect on both environments. GPU memory is always used for nearly 100%. But the code runs fine with the 4GB of the G TS450 Ti.

The command where the exception happens is:

```
...
     61   except core._NotOkStatusException as e:

UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node model/conv2d/Relu (defined at <ipython-input-17-7f1bbb39a367>:1) ]] [Op:__inference_train_function_1658]

Function call stack:
train_function
```

Console Error:
```
2020-12-16 21:33:18.290073: E tensorflow/stream_executor/cuda/cuda_dnn.cc:336] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2020-12-16 21:33:18.290200: E tensorflow/stream_executor/cuda/cuda_dnn.cc:340] Error retrieving driver version: Unimplemented: kernel reported driver version not implemented on Windows
2020-12-16 21:33:18.290830: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at conv_ops_fused_impl.h:697 : Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
```

Maybe I can test TF 2.4.0 with linux soon.

**Comment by ymodak** [comment]
I apologize I gave incomplete code prior. Can you please try:
```python
#On top of your script
import tensorflow as tf
gpu = tf.config.list_physical_devices('GPU')
tf.config.set_visible_devices(gpu[0], 'GPU')
tf.config.experimental.set_memory_growth(gpu[0], True) #limits gpu memory
# Rest of your code
```

**Comment by Doev** [comment]
When I do use memory limiting the ram usage stays low, until I call model.fit(). After that it grows again until short before 100%. There are many new lines at the console log:

2020-12-16 23:36:03.051777: I tensorflow/core/platform/windows/subprocess.cc:308] SubProcess ended with return code: 4294967295

But training now works now on the RTX 3060 Ti. Training is about 2,5 times faster, an GPU goes up to 8% (GTS 1050 Ti 85%). I can use a higher batch. That are good news.

Thank you!

**Comment by ymodak** [comment]
Glad it worked. I will close this issue now. Thanks!
