### ISSUE TITLE
No registered 'ResourceScatterNdUpdate' OpKernel for 'GPU' 

### ISSUE THREAD

**Issue by Flamefire** [tensorflow/tensorflow#45663]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 7
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.4.0rc4
- Python version: 3.7.4
- Bazel version (if compiling from source): 3.4.1
- GCC/Compiler version (if compiling from source): GCC 8.3.0
- CUDA/cuDNN version: 10.1
- GPU model and memory: V100

**Describe the current behavior**
A test shows that a GPU implementation for BOOL inputs of ResourceScatterNdUpdate is seemingly missing.
The test is //tensorflow/python/kernel_tests:batch_scatter_ops_test -> ScatterTest.testBooleanScatterUpdate

**Standalone code to reproduce the issue**
Run bazel test

**Other info / logs**
```
ERROR: testBooleanScatterUpdate (__main__.ScatterTest)
ScatterTest.testBooleanScatterUpdate
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/bazel-tf/20db8ac50b74c328e6dea9b20829b459/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python/kernel_tests/batch_scatter_ops_test.runfiles/org_tensorflow/tensorflow/python/kernel_tests/batch_scatter_ops_test.py", line 91, in testBooleanScatterUpdate
    update0 = state_ops.batch_scatter_update(var, [1], [True])
  File "/tmp/bazel-tf/20db8ac50b74c328e6dea9b20829b459/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python/kernel_tests/batch_scatter_ops_test.runfiles/org_tensorflow/tensorflow/python/util/deprecation.py", line 340, in new_func
    return func(*args, **kwargs)
  File "/tmp/bazel-tf/20db8ac50b74c328e6dea9b20829b459/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python/kernel_tests/batch_scatter_ops_test.runfiles/org_tensorflow/tensorflow/python/ops/state_ops.py", line 915, in batch_scatter_update
    ref, final_indices, updates, use_locking=use_locking)
  File "/tmp/bazel-tf/20db8ac50b74c328e6dea9b20829b459/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python/kernel_tests/batch_scatter_ops_test.runfiles/org_tensorflow/tensorflow/python/ops/state_ops.py", line 368, in scatter_nd_update
    name=name))
  File "/tmp/bazel-tf/20db8ac50b74c328e6dea9b20829b459/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python/kernel_tests/batch_scatter_ops_test.runfiles/org_tensorflow/tensorflow/python/ops/gen_state_ops.py", line 740, in resource_scatter_nd_update
    _ops.raise_from_not_ok_status(e, name)
  File "/tmp/bazel-tf/20db8ac50b74c328e6dea9b20829b459/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python/kernel_tests/batch_scatter_ops_test.runfiles/org_tensorflow/tensorflow/python/framework/ops.py", line 6862, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.NotFoundError: No registered 'ResourceScatterNdUpdate' OpKernel for 'GPU' devices compatible with node {{node ResourceScatterNdUpdate}}
	 (OpKernel was found, but attributes didn't match) Requested Attributes: T=DT_BOOL, Tindices=DT_INT32, use_locking=true
	.  Registered:  device='GPU'; T in [DT_COMPLEX128]; Tindices in [DT_INT64]
  device='GPU'; T in [DT_COMPLEX128]; Tindices in [DT_INT32]
  device='GPU'; T in [DT_COMPLEX64]; Tindices in [DT_INT64]
  device='GPU'; T in [DT_COMPLEX64]; Tindices in [DT_INT32]
  device='GPU'; T in [DT_DOUBLE]; Tindices in [DT_INT64]
  device='GPU'; T in [DT_DOUBLE]; Tindices in [DT_INT32]
  device='GPU'; T in [DT_FLOAT]; Tindices in [DT_INT64]
  device='GPU'; T in [DT_FLOAT]; Tindices in [DT_INT32]
  device='GPU'; T in [DT_HALF]; Tindices in [DT_INT64]
  device='GPU'; T in [DT_HALF]; Tindices in [DT_INT32]
  device='GPU'; T in [DT_INT64]; Tindices in [DT_INT64]
  device='GPU'; T in [DT_INT64]; Tindices in [DT_INT32]
  device='GPU'; T in [DT_INT32]; Tindices in [DT_INT64]
  device='GPU'; T in [DT_INT32]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_BOOL]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_BOOL]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_STRING]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_STRING]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_COMPLEX128]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_COMPLEX128]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_COMPLEX64]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_COMPLEX64]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_DOUBLE]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_DOUBLE]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_FLOAT]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_FLOAT]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_BFLOAT16]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_BFLOAT16]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_HALF]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_HALF]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_INT32]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_INT32]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_INT8]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_INT8]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_UINT8]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_UINT8]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_INT16]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_INT16]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_UINT16]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_UINT16]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_UINT32]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_UINT32]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_INT64]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_INT64]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_UINT64]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_UINT64]; Tindices in [DT_INT32]
 [Op:ResourceScatterNdUpdate]
```

**Comment by amahendrakar** [comment]
@Flamefire,
TensorFlow 2.4 is tested and built against CUDA 11 and cuDNN 8. For more information, please take a look at the [tested build configurations](https://www.tensorflow.org/install/source#gpu).

Could you please check if you are facing the same error with CUDA 11 and cuDNN 8 as well? Thanks!

**Comment by Flamefire** [comment]
As I can't use CUDA 11 I retested that with TF 2.3 and `python git/tensorflow/tensorflow/python/kernel_tests/batch_scatter_ops_test.py ScatterTest.testBooleanScatterUpdate` and am seeing the same issue. So I'd assume that this is not related to the version.

**Comment by Flamefire** [comment]
The issue is fully expected looking at the source: The bool kernel is simply never declared for GPU, the relevant line is https://github.com/tensorflow/tensorflow/blob/b5c8d770f553c529165292c607bcda46ce370c08/tensorflow/core/kernels/scatter_nd_op_gpu.cu.cc#L201

That uses https://github.com/tensorflow/tensorflow/blob/b5c8d770f553c529165292c607bcda46ce370c08/tensorflow/core/framework/register_types.h#L195-L196

And as one can see the Bool type is missing. I guess using `TF_CALL_GPU_ALL_TYPES` would be the right choice here

**Comment by mohantym** [comment]
Hi @Flamefire!

We are checking whether you still need any assistance in this issue.
Could you check the above test with Bazel 5.0.0 and TF 2.9 and let us know.

`!bazel test //tensorflow/python/kernel_tests:batch_scatter_ops_test `

Attached gist for reference. 

Thank you!

**Comment by Flamefire** [comment]
Test has only moved here: https://github.com/tensorflow/tensorflow/blob/v2.9.1/tensorflow/python/kernel_tests/array_ops/batch_scatter_ops_test.py#L86

And code looks still the same: https://github.com/tensorflow/tensorflow/blob/v2.9.1/tensorflow/core/kernels/scatter_nd_op_gpu.cu.cc#L201

https://github.com/tensorflow/tensorflow/blob/v2.9.1/tensorflow/core/framework/register_types.h#L195-L196

So yes the issue persists.

**Comment by mohantym** [comment]
Hi @Flamefire !
Test seems to be passing in 2.9 , Bazel 5.0.0 and Gcc 7.3 . Attached [gist](https://colab.sandbox.google.com/gist/mohantym/0c1666873ac27fa61c69265ab774da36/tensorflow-ranking.ipynb#scrollTo=skRg4_WPi616) for reference.
Thank you!

**Comment by Flamefire** [comment]
Sorry but your gist doesn't show the test passing. Last lines I see are 
```
 [5,459 / 9,765] 2 actions running
    Compiling .../mlir/expansions/segmentation_spmd_expander.cc; 13s local
    Compiling llvm/lib/Target/X86/X86FastTileConfig.cpp; 1s local
```

As shown in the source there is simply no Boolean type registered for the "ResourceScatterNdUpdate".
So if you evaluate the last expression of  
```
var = variables.Variable([True, False])
update0 = state_ops.batch_scatter_update(var, [1], [True])
```
on GPU it will try to find a GPU kernel for a bool tensor(see code at https://github.com/tensorflow/tensorflow/blob/v2.9.1/tensorflow/python/ops/state_ops.py#L1041 ) and fail with the above error.

I'm not familiar enough with TF to know how to evaluate the above on GPU but if you do that should be enough to reproduce.

Again: This only fails when run on GPU as the CPU kernels is registered for bool: https://github.com/tensorflow/tensorflow/blob/v2.9.1/tensorflow/core/kernels/scatter_nd_op.cc#L501-L502

**Comment by mohantym** [comment]
Thanks @Flamefire for the update.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

**Comment by Flamefire** [comment]
The issue still persists: Only a CPU implementation is registered: https://github.com/tensorflow/tensorflow/blob/v2.17.0/tensorflow/core/kernels/scatter_nd_op.cc#L655-L657

**Comment by Kayyuri** [comment]
Hi @Flamefire, 
Thank you so much for filing this issue! We truly appreciate your support. At the moment, this request is not prioritized and mark it for community contributions. If you would like to contribute on a fix, please feel free to fork the repository and submit a pull request in accordance with the TensorFlow [CONTRIBUTION GUIDELINES](https://www.tensorflow.org/community/contribute/code) and link this issue in your PR to ensure the maintainers can easily review and collaborate.
To avoid duplicate work, please leave a comment here if you decide to take it on!

Thank you again for your interest and we look forward to seeing your contributions!

**Comment by Kayyuri** [comment]
Hi @Flamefire,
We are closing this issue due to inactivity. If this is still relevant and you would like to work on it, please feel free to reopen the issue or submit a pull request referencing it.

Thank you for your understanding!
