### ISSUE TITLE
change LSTM to CuDNNLSTM cause core dumped

### ISSUE THREAD

**Issue by mingwugmail** [tensorflow/tensorflow#45709]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04.1 LTS x86_64 GNU/Linux
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tensorflow-gpu                     1.15.0, v1.15.0-rc3-22-g590d6ee 1.15.0
- Python version: python3.6
- CUDA/cuDNN version:  Cuda compilation tools, release 10.0, V10.0.130 / libcudnn.so.7
- GPU model and memory: GeForce GTX 1660 Ti with Max-Q Design

**Describe the current behavior**
https://stackoverflow.com/questions/65311478/change-lstm-to-cudnnlstm-cause-core-dumped

I tried a model, and changed LSTM (which is running fine) to CuDNNLSTM, then it core dumped.

```
from tensorflow.keras.layers import CuDNNLSTM as LSTM  # no core dump if just use LSTM

...
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
gaussian_noise (GaussianNois (None, 63, 41)            0         
_________________________________________________________________
cu_dnnlstm_1 (CuDNNLSTM)     (None, 20)                5040      
_________________________________________________________________
dense (Dense)                (None, 1)                 21        
_________________________________________________________________
batch_normalization (BatchNo (None, 1)                 4         
_________________________________________________________________
re_lu (ReLU)                 (None, 1)                 0         
_________________________________________________________________
lambda (Lambda)              (None, 1)                 0         
=================================================================
Total params: 5,065
Trainable params: 5,063
Non-trainable params: 2
_________________________________________________________________

Epoch 1/1000
2020-12-15 12:58:38.233733: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-12-15 12:58:38.410567: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
Segmentation fault (core dumped)


package versions:

Keras                              2.2.0
tensorflow-gpu                     1.15.0
```

**Describe the expected behavior**
CuDNNLSTM should running fine just as LSTM.

**Other info / logs** Include any logs or source code that would be helpful to

the stack trace from the core file:
```
$ gdb python3 core 
GNU gdb (Ubuntu 9.1-0ubuntu1) 9.1
...
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007ff4a50edfc0 in tensorflow::Tensor::Tensor(tensorflow::Tensor const&) ()
   from /home/z/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so
[Current thread is 1 (Thread 0x7ff42cffd700 (LWP 12422))]
(gdb) where
#0  0x00007ff4a50edfc0 in tensorflow::Tensor::Tensor(tensorflow::Tensor const&) ()
   from /home/z/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so
#1  0x00007ff4a5f1c4af in tensorflow::CudnnRNNForwardOpV2<Eigen::GpuDevice, double>::MaybeAutoTune(tensorflow::OpKernelContext*, tensorflow::(anonymous namespace)::CudnnRnnModelShapes const&, stream_executor::dnn::RnnInputMode const&, tensorflow::Tensor const*, tensorflow::Tensor const*, tensorflow::Tensor const*, tensorflow::Tensor const*, tensorflow::Tensor*, tensorflow::Tensor*, tensorflow::Tensor*, stream_executor::dnn::AlgorithmConfig*) () from /home/z/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so
#2  0x00007ff4a5f15e1f in tensorflow::CudnnRNNForwardOp<Eigen::GpuDevice, double>::ComputeAndReturnAlgorithm(tensorflow::OpKernelContext*, stream_executor::dnn::AlgorithmConfig*, bool, bool, int) ()
   from /home/z/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so
#3  0x00007ff4a5f17400 in tensorflow::CudnnRNNForwardOpV2<Eigen::GpuDevice, double>::Compute(tensorflow::OpKernelContext*) ()
   from /home/z/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so
#4  0x00007ff4a1788dc2 in tensorflow::BaseGPUDevice::Compute(tensorflow::OpKernel*, tensorflow::OpKernelContext*) ()
   from /home/z/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/../libtensorflow_framework.so.1
#5  0x00007ff4a17e4b47 in tensorflow::(anonymous namespace)::ExecutorState::Process(tensorflow::(anonymous namespace)::ExecutorState::TaggedNode, long long) () from /home/z/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/../libtensorflow_framework.so.1
#6  0x00007ff4a17e513f in std::_Function_handler<void (), tensorflow::(anonymous namespace)::ExecutorState::ScheduleReady(absl::InlinedVector<tensorflow::(anonymous namespace)::ExecutorState::TaggedNode, 8ul, std::allocator<tensorflow::(anonymous namespace)::ExecutorState::TaggedNode> > const&, tensorflow::(anonymous namespace)::ExecutorState::TaggedNodeReadyQueue*)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
   from /home/z/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/../libtensorflow_framework.so.1
#7  0x00007ff4a1895021 in Eigen::ThreadPoolTempl<tensorflow::thread::EigenEnvironment>::WorkerLoop(int) ()
   from /home/z/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/../libtensorflow_framework.so.1
#8  0x00007ff4a1892718 in std::_Function_handler<void (), tensorflow::thread::EigenEnvironment::CreateThread(std::function<void ()>)::{lambda()#1}>::_M_invoke(std::_Any_data const&) () from /home/z/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/../libtensorflow_framework.so.1
#9  0x00007ff4a1eefb1f in std::execute_native_thread_routine (__p=0x55f81d1f75f0) at /dt7-src/libstdc++-v3/src/nonshared11/../c++11/thread.cc:83
#10 0x00007ff50f75f609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#11 0x00007ff50f686103 in clone () from /usr/lib/x86_64-linux-gnu/libc.so.6
(gdb) q
```

**Comment by amahendrakar** [comment]
@mingwugmail,
TensorFlow 1.x is not actively supported. Could you please update TensorFlow to v2.4 and check if you are facing the same issue.

Also, in order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and the dataset you are using. Thanks!

**Comment by mingwugmail** [comment]
Yes, CuDNNLSTM in v2.4 is working.
