### ISSUE TITLE
TPU guide doesn't work, but used to - `Op type not registered 'DecodeImage' in binary`

### ISSUE THREAD

**Issue by SamuelMarks** [tensorflow/tensorflow#45874]
## URL(s) with the issue:

https://www.tensorflow.org/guide/tpu
https://github.com/tensorflow/docs/blob/master/site/en/guide/tpu.ipynb

## Description of issue (what needs changing):

Last time I tried it worked: 
  - [gcloud_scripts/test.bash @ `851b306`](https://github.com/SamuelMarks/ml-glaucoma/blob/851b306/gcloud_scripts/test.bash) using [tensorflow/docs/site/en/guide/tpu.ipynb @ `7931afd`](https://github.com/tensorflow/docs/blob/7931afd/site/en/guide/tpu.ipynb)

But now it does not work:
  - [gcloud_scripts/test.bash @ `a1dffb1`](https://github.com/SamuelMarks/ml-glaucoma/blob/a1dffb1/gcloud_scripts/test.bash) using [tensorflow/docs/site/en/guide/tpu.ipynb @ `945a448`](https://github.com/tensorflow/docs/blob/945a448/site/en/guide/tpu.ipynb)

### Clear description

My scripts are pretty simple, I made them from my [**Nothing to TPU in 5 Google Cloud commands** gist](https://gist.github.com/SamuelMarks/d5e4e4233c0a1401635f783994366daa), they just use the [`gcloud` CLI](https://cloud.google.com/sdk/gcloud), and it's as easy as:

```sh
$ git clone https://github.com/SamuelMarks/ml-glaucoma
# Set env vars (you'll want to update the various IDs here…):
$ . ./ml-glaucoma/gcloud_scripts/.env.sh
# Create network, firewall, compute, and tpu:
$ . ./ml-glaucoma/gcloud_scripts/init.sh
# Install Python deps, convert the Jupyter Notebook to a Python script, then run it:
$ . ./ml-glaucoma/gcloud_scripts/test.sh
# Destroy network, firewall, compute, and tpu
$ . ./ml-glaucoma/gcloud_scripts/teardown.sh
```

Unfortunately it fails in the `test.sh` phase, here's the relevant snippet:
```
2020-12-19 08:38:55.052102: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job worker -> {0 -> 192.168.0.2:8470}
2020-12-19 08:38:55.052147: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:31480}
2020-12-19 08:38:55.068584: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job worker -> {0 -> 192.168.0.2:8470}
2020-12-19 08:38:55.068633: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:31480}
2020-12-19 08:38:55.069112: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:411] Started server with target: grpc://localhost:31480
All devices:  [LogicalDevice(name='/job:worker/replica:0/task:0/device:TPU:7', device_type='TPU'), LogicalDevice(name='/job:worker/replica:0/task:0/device:TPU:6', device_type='TPU'), LogicalDevice(name='/job:worker/replica:0/task:0/device:TPU:5', device_type='TPU'), LogicalDevice(name='/job:worker/replica:0/task:0/device:TPU:4', device_type='TPU'), LogicalDevice(name='/job:worker/replica:0/task:0/device:TPU:0', device_type='TPU'), LogicalDevice(name='/job:worker/replica:0/task:0/device:TPU:1', device_type='TPU'), LogicalDevice(name='/job:worker/replica:0/task:0/device:TPU:2', device_type='TPU'), LogicalDevice(name='/job:worker/replica:0/task:0/device:TPU:3', device_type='TPU')]
c device:  /job:worker/replica:0/task:0/device:TPU:0
tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)
PerReplica:{
  0: tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32),
  1: tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32),
  2: tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32),
  3: tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32),
  4: tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32),
  5: tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32),
  6: tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32),
  7: tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)
}
Traceback (most recent call last):
  File "tpu-tester.py", line 85, in <module>
    train_dataset = get_dataset(batch_size, is_training=True)
  File "tpu-tester.py", line 52, in get_dataset
    dataset, info = tfds.load(name='mnist', split=split, with_info=True,
  File "tensorflow_datasets/core/load.py", line 356, in load
    ds = dbuilder.as_dataset(**as_dataset_kwargs)
  File "tensorflow_datasets/core/dataset_builder.py", line 552, in as_dataset
    datasets = utils.map_nested(build_single_dataset, split, map_tuple=True)
  File "tensorflow_datasets/core/utils/py_utils.py", line 183, in map_nested
    return function(data_struct)
  File "tensorflow_datasets/core/dataset_builder.py", line 582, in _build_single_dataset
    ds = ds.cache()
  File "tensorflow/python/data/ops/dataset_ops.py", line 1400, in cache
    return CacheDataset(self, filename)
  File "tensorflow/python/data/ops/dataset_ops.py", line 3779, in __init__
    variant_tensor = gen_dataset_ops.cache_dataset_v2(
  File "tensorflow/python/ops/gen_dataset_ops.py", line 782, in cache_dataset_v2
    _ops.raise_from_not_ok_status(e, name)
  File "tensorflow/python/framework/ops.py", line 6862, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'DecodeImage' in binary running on n-73dd04c3-w-0. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed. [Op:CacheDatasetV2]
2020-12-19 08:39:12.439461: W tensorflow/core/distributed_runtime/eager/remote_tensor_handle_data.cc:76] Unable to destroy remote tensor handles. If you are running a tf.function, it usually indicates some op in the graph gets an error: Op type not registered 'DecodeImage' in binary running on n-73dd04c3-w-0. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "tensorflow/python/distribute/tpu_strategy.py", line 738, in async_wait
    context.async_wait()
  File "tensorflow/python/eager/context.py", line 2330, in async_wait
    context().sync_executors()
  File "tensorflow/python/eager/context.py", line 645, in sync_executors
    pywrap_tfe.TFE_ContextSyncExecutors(self._context_handle)
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'DecodeImage' in binary running on n-73dd04c3-w-0. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
2020-12-19 08:39:12.516206: W ./tensorflow/core/distributed_runtime/eager/destroy_tensor_handle_node.h:57] Ignoring an error encountered when deleting remote tensors handles: Invalid argument: Unable to find the relevant tensor remote_handle: Op ID: 399, Output num: 0
Additional GRPC error information from remote target /job:worker/replica:0/task:0:
:{"created":"@1608367152.516107804","description":"Error received from peer ipv4:192.168.0.2:8470","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Unable to find the relevant tensor remote_handle: Op ID: 399, Output num: 0","grpc_status":3}
```

**Comment by Saduf2019** [comment]
@SamuelMarks 
Is this still  an issue, could you please try on the latest version of tensorflow and let us know.

**Comment by sachinprasadhs** [comment]
Hi, could you please try with the latest Tensorflow version and let us know if this is still an issue. Thanks!
