### ISSUE TITLE
tf.train.Saver and saver.restore do not work when data_augmentation_options rgb_to_gray and random_vertical_flip are configured in the pipeline config file

### ISSUE THREAD

**Issue by smeyg** [tensorflow/tensorflow#45915]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No (but added a workaround to overcome first issue which will be explained)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS Linux 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.13.2 (also with 1.14.0)
- Python version: 3.6.4
- Bazel version (if compiling from source): 0.20.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
I am using object detection api and training my model using faster_rcnn_resnet152. Training and evaluation worked fine until I added below data augmentation options in the pipeline config file. The evaluation script (I am using old eval.py on purpose) fails with below error. The error seems to be due to rgb_to_gray option. Pipeline config file has also subtract_channel_mean  and random_horizontal_flip options, however they work fine until the other two configurations are added. To overcome the error I added "reshape=True" argument to saver = tf.train.Saver(variables_to_restore) line in the legcy/evaluator.py line 270 and it started to work if only saver.restore(sess, latest_checkpoint) is commented out in the line 274. When the line is enabled this time it throws the second exception given below. Could you propose a solution/workaround without having to upgrade tensorflow/python etc versions?

  data_augmentation_options {
    rgb_to_gray {
    }
  }
  data_augmentation_options {
    random_vertical_flip {
    }

ERROR:1
------------------------------
Assign requires shapes of both tensors to match. lhs shape= [7,7,3,64] rhs shape= [7,7,1,64]
         [[node save/Assign_780 (defined at /truba/home/iuzun/Tensorflow/models/research/object_detection/legacy/evaluator.py:270) ]]

Caused by op 'save/Assign_780', defined at:
  File "legacy/eval.py", line 149, in <module>
    tf.app.run()
  File "/truba/home/iuzun/anaconda3/envs/tensorflow_cpu1/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/truba/home/iuzun/anaconda3/envs/tensorflow_cpu1/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "legacy/eval.py", line 145, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/truba/home/iuzun/Tensorflow/models/research/object_detection/legacy/evaluator.py", line 270, in evaluate
    saver = tf.train.Saver(variables_to_restore)
  File "/truba/home/iuzun/anaconda3/envs/tensorflow_cpu1/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 832, in __init__
    self.build()
  File "/truba/home/iuzun/anaconda3/envs/tensorflow_cpu1/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/truba/home/iuzun/anaconda3/envs/tensorflow_cpu1/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File "/truba/home/iuzun/anaconda3/envs/tensorflow_cpu1/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 513, in _build_internal
    restore_sequentially, reshape)
  File "/truba/home/iuzun/anaconda3/envs/tensorflow_cpu1/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 354, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "/truba/home/iuzun/anaconda3/envs/tensorflow_cpu1/lib/python3.6/site-packages/tensorflow/python/training/saving/saveable_object_util.py", line 73, in restore
    self.op.get_shape().is_fully_defined())
  File "/truba/home/iuzun/anaconda3/envs/tensorflow_cpu1/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 223, in assign
    validate_shape=validate_shape)
  File "/truba/home/iuzun/anaconda3/envs/tensorflow_cpu1/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py", line 64, in assign
    use_locking=use_locking, name=name)
  File "/truba/home/iuzun/anaconda3/envs/tensorflow_cpu1/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/truba/home/iuzun/anaconda3/envs/tensorflow_cpu1/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/truba/home/iuzun/anaconda3/envs/tensorflow_cpu1/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/truba/home/iuzun/anaconda3/envs/tensorflow_cpu1/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [7,7,3,64] rhs shape= [7,7,1,64]
         [[node save/Assign_780 (defined at /truba/home/iuzun/Tensorflow/models/research/object_detection/legacy/evaluator.py:270) ]]
------------------------------------------

ERROR:2
----------------------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "legacy/eval.py", line 154, in <module>
    tf.app.run()
  File "/truba/home/iuzun/anaconda3/envs/tensorflow_cpu1/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/truba/home/iuzun/anaconda3/envs/tensorflow_cpu1/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "legacy/eval.py", line 150, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/truba/home/iuzun/Tensorflow/models/research/object_detection/legacy/evaluator.py", line 302, in evaluate
    eval_export_path=eval_config.export_path)
  File "/truba/home/iuzun/Tensorflow/models/research/object_detection/eval_util.py", line 519, in repeated_checkpoint_run
    process_metrics_fn=process_metrics_fn)
  File "/truba/home/iuzun/Tensorflow/models/research/object_detection/eval_util.py", line 314, in _run_checkpoint_once
    restore_fn(sess)
  File "/truba/home/iuzun/Tensorflow/models/research/object_detection/legacy/evaluator.py", line 280, in _restore_latest_checkpoint
    saver.restore(sess, latest_checkpoint)
  File "/truba/home/iuzun/anaconda3/envs/tensorflow_cpu1/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1312, in restore
    err, "a mismatch between the current graph and the graph")
tensorflow.python.framework.errors_impl.InvalidArgumentError: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Input to reshape is a tensor with 3136 values, but the requested shape has 9408
         [[node save/Reshape_780 (defined at /truba/home/iuzun/Tensorflow/models/research/object_detection/legacy/evaluator.py:270) ]]

Caused by op 'save/Reshape_780', defined at:
  File "legacy/eval.py", line 154, in <module>
    tf.app.run()
  File "/truba/home/iuzun/anaconda3/envs/tensorflow_cpu1/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/truba/home/iuzun/anaconda3/envs/tensorflow_cpu1/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "legacy/eval.py", line 150, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/truba/home/iuzun/Tensorflow/models/research/object_detection/legacy/evaluator.py", line 270, in evaluate
    saver = tf.train.Saver(var_list=variables_to_restore,reshape=True)
  File "/truba/home/iuzun/anaconda3/envs/tensorflow_cpu1/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 832, in __init__
    self.build()
  File "/truba/home/iuzun/anaconda3/envs/tensorflow_cpu1/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/truba/home/iuzun/anaconda3/envs/tensorflow_cpu1/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File "/truba/home/iuzun/anaconda3/envs/tensorflow_cpu1/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 513, in _build_internal
    restore_sequentially, reshape)
  File "/truba/home/iuzun/anaconda3/envs/tensorflow_cpu1/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 354, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "/truba/home/iuzun/anaconda3/envs/tensorflow_cpu1/lib/python3.6/site-packages/tensorflow/python/training/saving/saveable_object_util.py", line 68, in restore
    restored_tensor = array_ops.reshape(restored_tensor, restored_shapes[0])
  File "/truba/home/iuzun/anaconda3/envs/tensorflow_cpu1/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 7179, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/truba/home/iuzun/anaconda3/envs/tensorflow_cpu1/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/truba/home/iuzun/anaconda3/envs/tensorflow_cpu1/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/truba/home/iuzun/anaconda3/envs/tensorflow_cpu1/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/truba/home/iuzun/anaconda3/envs/tensorflow_cpu1/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Input to reshape is a tensor with 3136 values, but the requested shape has 9408
         [[node save/Reshape_780 (defined at /truba/home/iuzun/Tensorflow/models/research/object_detection/legacy/evaluator.py:270) ]]
----------------------------------------------------------------------------------------------------------

Executed command:
python legacy/eval.py --logtostderr --pipeline_config_path=training/faster_rcnn_resnet152_coco.config --checkpoint_dir=training/ --eval_dir=eval/

Thanks in advance

**Comment by amahendrakar** [comment]
@smeyg,
TensorFlow 1.x is not actively supported. Could you please update TensorFlow to v2.4 and check if you are facing the same issue. Thanks!
