### ISSUE TITLE
TF 2.4 met 'TypeError: can't pickle _thread.lock objects' where 2.3 did not.

### ISSUE THREAD

**Issue by UrmsOne** [tensorflow/tensorflow#45918]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v.2.4
- Python version: 3.6.9
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
I am working on distributed learning in tensorflow through estimators API using below simple code template:

```
def multi_worker_strategy_estimator():
    mirrored_strategy = tf.distribute.MultiWorkerMirroredStrategy()
    config = tf.estimator.RunConfig(train_distribute=mirrored_strategy, eval_distribute=mirrored_strategy)
    regressor = tf.estimator.LinearRegressor(
        feature_columns=[tf.feature_column.numeric_column('feats')],
        optimizer='SGD',
        config=config)

    def input_fn():
        dataset = tf.data.Dataset.from_tensors(({"feats": [1.]}, [1.]))
        return dataset.repeat(1000).batch(10)

    train_spec = tf.estimator.TrainSpec(
        input_fn=input_fn,
        max_steps=FLAGS.train_steps,
        hooks=[]
    )
    eval_spec = tf.estimator.EvalSpec(input_fn=input_fn)
    tf.estimator.train_and_evaluate(regressor, train_spec, eval_spec)
    print("---training finished---")
```

Then I encountered the errors as follow:
```
Traceback (most recent call last):
  File "/root/PycharmProjects/urmsone-multi-gpu-tf-demo/test-mutiworker-strategy.py", line 318, in <module>
    test()
  File "/root/PycharmProjects/urmsone-multi-gpu-tf-demo/test-mutiworker-strategy.py", line 66, in test
    config=config)
  File "/root/PycharmProjects/urmsone-multi-gpu-tf-demo/venv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/canned/linear.py", line 1369, in __init__
    warm_start_from=warm_start_from)
  File "/root/PycharmProjects/urmsone-multi-gpu-tf-demo/venv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 183, in __init__
    config, model_dir)
  File "/root/PycharmProjects/urmsone-multi-gpu-tf-demo/venv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1832, in maybe_overwrite_model_dir_and_session_config
    config = run_config.RunConfig.replace(config, session_config=session_config)
  File "/root/PycharmProjects/urmsone-multi-gpu-tf-demo/venv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/run_config.py", line 923, in replace
    copy.deepcopy(self),
  File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "/root/PycharmProjects/urmsone-multi-gpu-tf-demo/venv/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py", line 1542, in __deepcopy__
    setattr(result, k, copy.deepcopy(v, memo))
  File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle _thread.lock objects
```

The same code runs on Tensorflow v2.3  without this problem. 

Is this a bug in the  v2.4？

**Comment by amahendrakar** [comment]
@UrmsOne,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!

**Comment by UrmsOne** [comment]
The complete code as follows:
```
# @Author: urmsone urmsone@163.com
# @Date: 12/22/20 20:37
# @Name: github-issue
# @Description

import os
import json
import argparse
import numpy as np
import tensorflow as tf


def multi_worker_strategy_estimator():
    try:
        mirrored_strategy = tf.distribute.MultiWorkerMirroredStrategy()
    except Exception as e:
        print("Error: ", e)
        mirrored_strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy()
    config = tf.estimator.RunConfig(train_distribute=mirrored_strategy, eval_distribute=mirrored_strategy)
    regressor = tf.estimator.LinearRegressor(
        feature_columns=[tf.feature_column.numeric_column('feats')],
        optimizer='SGD',
        config=config)

    def input_fn():
        dataset = tf.data.Dataset.from_tensors(({"feats": [1.]}, [1.]))
        return dataset.repeat(1000).batch(10)

    train_spec = tf.estimator.TrainSpec(
        input_fn=input_fn,
        max_steps=FLAGS.train_steps,
        hooks=[]
    )
    eval_spec = tf.estimator.EvalSpec(input_fn=input_fn)
    tf.estimator.train_and_evaluate(regressor, train_spec, eval_spec)
    print("---training finished---")


def init_env():
    if not os.environ.get('TF_CONFIG'):
        # cluster = {'worker': ['localhost:2220', 'localhost:2221', 'localhost:2222'], }
        cluster = {'chief': ['localhost:2220'], 'worker': ['localhost:2221', 'localhost:2222'], }
        # cluster = {'chief': ['localhost:2220'], }

        os.environ['TF_CONFIG'] = json.dumps({
            'cluster': cluster,
            'task': {'type': FLAGS.job_name, 'index': FLAGS.task_index}
        })
    print(os.environ.get('TF_CONFIG'))


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--batch_size', default=100, type=int, help='batch size')
    parser.add_argument('--train_steps', default=3000, type=int,
                        help='number of training steps')
    parser.add_argument('--job_name', type=str, help='job_name')  # worker
    parser.add_argument('--task_index', type=int, help='task_index')
    parser.add_argument('--save_checkpoints_steps', default=500, type=int, help='save_checkpoints_steps')
    parser.add_argument('--save_checkpoints_secs', default=60 * 10, type=int, help='save_checkpoints_secs')
    parser.add_argument('--keep_checkpoint_max', default=2, type=int, help='keep_checkpoint_max')
    parser.add_argument('--num_gpus_per_worker', default=0, type=int, help='num_gpus_per_worker')
    FLAGS, unparsed = parser.parse_known_args()

    init_env()
    multi_worker_strategy_estimator()

```

Quick run on docker
```
root@ubuntu:/home/prometheus# docker run -it --name tf-24 -v /root/PycharmProjects/urmsone-multi-gpu-tf-demo:/home/tf  tensorflow/tensorflow:2.3.0-gpu /bin/bash

________                               _______________                
___  __/__________________________________  ____/__  /________      __
__  /  _  _ \_  __ \_  ___/  __ \_  ___/_  /_   __  /_  __ \_ | /| / /
_  /   /  __/  / / /(__  )/ /_/ /  /   _  __/   _  / / /_/ /_ |/ |/ / 
/_/    \___//_/ /_//____/ \____//_/    /_/      /_/  \____/____/|__/


WARNING: You are running this container as root, which can cause new files in
mounted volumes to be created as the root user on your host machine.

To avoid this, run the container by specifying your user's userid:

$ docker run -u $(id -u):$(id -g) args...

root@05246d8eb041:/# cd /home/tf/
root@05246d8eb041:/home/tf# python github-issue.py --task_index=0 --job_name=chief > /tmp/chief-0.log 2>&1
root@05246d8eb041:/home/tf# python github-issue.py --task_index=0 --job_name=worker > /tmp/worker-0.log 2>&1
root@05246d8eb041:/home/tf# python github-issue.py --task_index=1 --job_name=worker > /tmp/worker-1.log 2>&1
```

Output logs as follows:
```
root@7363a4713c6f:/home/tf# tail -fn 100 /tmp/worker-1.log 
2020-12-22 12:47:22.825393: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2020-12-22 12:47:23.766955: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-12-22 12:47:23.767090: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2020-12-22 12:47:23.767110: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: UNKNOWN ERROR (-1)
2020-12-22 12:47:23.767124: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (7363a4713c6f): /proc/driver/nvidia/version does not exist
2020-12-22 12:47:23.767672: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-12-22 12:47:23.767936: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-12-22 12:47:23.770861: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job chief -> {0 -> localhost:2220}
2020-12-22 12:47:23.770893: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job worker -> {0 -> localhost:2221, 1 -> localhost:2222}
2020-12-22 12:47:23.771081: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:411] Started server with target: grpc://localhost:2222
{"cluster": {"chief": ["localhost:2220"], "worker": ["localhost:2221", "localhost:2222"]}, "task": {"type": "worker", "index": 1}}
Traceback (most recent call last):
  File "github-issue.py", line 62, in <module>
    multi_worker_strategy_estimator()
  File "github-issue.py", line 19, in multi_worker_strategy_estimator
    config=config)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/canned/linear.py", line 1369, in __init__
    warm_start_from=warm_start_from)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 183, in __init__
    config, model_dir)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1832, in maybe_overwrite_model_dir_and_session_config
    config = run_config.RunConfig.replace(config, session_config=session_config)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/run_config.py", line 923, in replace
    copy.deepcopy(self),
  File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py", line 1542, in __deepcopy__
    setattr(result, k, copy.deepcopy(v, memo))
  File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle _thread.lock objects
```

**Comment by jbcaep** [comment]
I encountered the same problem, Is this a bug in the Tensorflow v2.4？

**Comment by jbcaep** [comment]
I used tf.distribute.experimental.MultiWorkerMirroredStrategy() in TF v2.4 :
mirrored_strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy()

**Comment by amahendrakar** [comment]
@UrmsOne,
The code you've provided runs indefinitely without messages in the output log. Could you please provide a minimal code snippet to reproduce the issue? Thanks!

**Comment by jbcaep** [comment]
@amahendrakar:
https://github.com/tensorflow/docs/blob/master/site/en/tutorials/distribute/multi_worker_with_estimator.ipynb
try: multi_worker_with_estimator.py in TF2.4

**Comment by amahendrakar** [comment]
> The code you've provided runs indefinitely without messages in the output log. Could you please provide a minimal code snippet to reproduce the issue? Thanks!

@UrmsOne,
Any updates regarding this? 

@jbcaep,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track your issue separately. 

Thanks!

**Comment by UrmsOne** [comment]
@amahendrakar 

I also use this code  thar I provided for test， and met the error `TypeError: can't pickle _thread.lock objects` in TF-2.4.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.4 and TF-nightly. 
- [worker-1.log](https://github.com/tensorflow/tensorflow/files/5844222/worker-1.log)
- [worker-0.log](https://github.com/tensorflow/tensorflow/files/5844223/worker-0.log)
- [chief-0.log](https://github.com/tensorflow/tensorflow/files/5844224/chief-0.log)


Whereas with TF v2.3 the script throws an `Aborted (core dumped)` error. 
![Screenshot 2021-01-20 at 10 13 21 PM](https://user-images.githubusercontent.com/57165142/105213379-a48d7500-5b74-11eb-8e89-8af4d2410182.png)

Please check the attached logs and screenshot for reference. Thanks!

**Comment by GeforceTesla** [comment]
I am also seeing this exact issue. Is there a workaround?

**Comment by nikitamaia** [comment]
Current suggestion is to use `tf.compat.v1.disable_eager_execution()`
Other workarounds can be found in duplicate thread #46556

**Comment by yuefengz** [comment]
Estimator + MultiWorkerMirroredStrategy in **eager** mode is not a blessed path. Please either use the workaround mentioned above or use Keras. Thanks!
