### ISSUE TITLE
SavedModel: KeyError on concrete_functions 

### ISSUE THREAD

**Issue by Bilgee** [tensorflow/tensorflow#45945]
**System information**
-Google Colab
-Tensorflow version 2.4.0

I wrote encoder_network, decoder_network using Keras Functional API and saved in SavedModel Format.
But when I use 'saved_model_cli show --dir model  --all', it shows those errors

2020-12-23 17:23:49.847954: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1

MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['__saved_model_init_op']:
  The given SavedModel SignatureDef contains the following input(s):
  The given SavedModel SignatureDef contains the following output(s):
    outputs['__saved_model_init_op'] tensor_info:
        dtype: DT_INVALID
        shape: unknown_rank
        name: NoOp
  Method name is: 

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['input_2'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 110, 470, 3)
        name: serving_default_input_2:0
    inputs['input_3'] tensor_info:
        dtype: DT_INT32
        shape: (-1, -1)
        name: serving_default_input_3:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['decoder_network'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, -1, 37)
        name: StatefulPartitionedCall:0
  Method name is: tensorflow/serving/predict
Traceback (most recent call last):
  File "/usr/local/bin/saved_model_cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/tools/saved_model_cli.py", line 1185, in main
    args.func(args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/tools/saved_model_cli.py", line 715, in show
    _show_all(args.dir)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/tools/saved_model_cli.py", line 307, in _show_all
    _show_defined_functions(saved_model_dir)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/tools/saved_model_cli.py", line 187, in _show_defined_functions
    trackable_object = load.load(saved_model_dir)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/load.py", line 603, in load
    return load_internal(export_dir, tags, options)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/load.py", line 633, in load_internal
    ckpt_options)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/load.py", line 130, in __init__
    self._load_all()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/load.py", line 141, in _load_all
    self._load_nodes()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/load.py", line 283, in _load_nodes
    node, setter = self._recreate(proto, node_id)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/load.py", line 393, in _recreate
    return factory[kind]()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/load.py", line 382, in <lambda>
    "function": lambda: self._recreate_function(proto.function),
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/load.py", line 421, in _recreate_function
    proto, self._concrete_functions), setattr
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/function_deserialization.py", line 261, in recreate_function
    concrete_function_objects.append(concrete_functions[concrete_function_name])
KeyError: '__inference_functional_3_layer_call_fn_718866'

Do you have any hint how to fix this ? What am I doing wrong here ? is it because I am using Keras Functional API?

**Comment by ravikyram** [comment]
@Bilgee 

Please, share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by Bilgee** [comment]
@ravikyram Colab link: https://colab.research.google.com/drive/1o00sUhX93xtY4eLo7U8Nrz1xpaevHrz8?usp=sharing

Thank you.

**Comment by ravikyram** [comment]
@Bilgee 

Please, grant me the access for the colab link. Thanks!

**Comment by Bilgee** [comment]
@ravikyram I am sorry. It is done.

**Comment by ravikyram** [comment]
@Bilgee 

I have tried in colab with TF version 2.4 and was able to reproduce the issue.In TF nightly version i am seeing the different error message. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/55b2ae3622369cb62d64413402ecb792/untitled583.ipynb). Thanks!

**Comment by Bilgee** [comment]
@ravikyram Thank you. I am trying to run the model in C++ using SavedModel format. But it failed, maybe because I could not save my model correctly in SavedModel Format.

**Comment by Bilgee** [comment]
@ravikyram  @ymodak any updates?

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
 Thanks!

**Comment by Bilgee** [comment]
@ymodak Why did you close this issue? I think it is a bug. If a model is saved correctly, saved_model_cli must shows the right results, right?. But right now, we cannot save the model in TF format correctly.

**Comment by ymodak** [comment]
Does your model contain custom objects? If yes then you may want to switch Keras Model Subclassing API.
