### ISSUE TITLE
windows 10 build failed (ERROR: An error occurred during the fetch of repository 'local_config_cuda':)

### ISSUE THREAD

**Issue by aligoglos** [tensorflow/tensorflow#46005]
I've tried to install tensorflow step by step from [source_windows](https://www.tensorflow.org/install/source_windows)
but got error
**System information**
- OS Platform and Distribution : windows10 x64
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.4.0
- Python version: 3.7.7
- Bazel version : 3.7.2
- GCC/Compiler version (if compiling from source): visual studio 2019
- CUDA/cuDNN version: 10.2
- GPU model and memory: 960m, 4G

output of `python ./configure.py`:
```
You have bazel 3.7.2 installed.
Please specify the location of python. [Default is C:\Users\127051\AppData\Local\Programs\Python\Python37\python.exe]:


Found possible Python library paths:
  C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages
Please input the desired Python library path to use.  Default is [C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages]

Do you wish to build TensorFlow with ROCm support? [y/N]: N
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Found CUDA 10.2 in:
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2/lib/x64
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2/include
Found cuDNN 8 in:
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2/lib/x64
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2/include


Please specify a list of comma-separated CUDA compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus. Each capability can be specified as "x.y" or "compute_xy" to include both virtual and binary GPU code, or as "sm_xy" to only include the binary code.
Please note that each additional compute capability significantly increases your build time and binary size, and that TensorFlow only supports compute capabilities >= 3.5 [Default is: 3.5,7.0]: 5.0


Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]:


Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]: Y
Eigen strong inline overridden.

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: N
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=mkl_aarch64    # Build with oneDNN support for Aarch64.
        --config=monolithic     # Config for mostly static monolithic build.
        --config=ngraph         # Build with Intel nGraph support.
        --config=numa           # Build with NUMA support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
        --config=v2             # Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=noaws          # Disable AWS S3 filesystem support.
        --config=nogcp          # Disable GCP support.
        --config=nohdfs         # Disable HDFS support.
        --config=nonccl         # Disable NVIDIA NCCL support.
```
Install error:
```
bazel build //tensorflow/tools/pip_package:build_pip_package
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=164
INFO: Reading rc options for 'build' from d:\softwareinstaltion\tensorflow-2.4.0\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=C:/Users/127051/AppData/Local/Programs/Python/Python37/python.exe
INFO: Reading rc options for 'build' from d:\softwareinstaltion\tensorflow-2.4.0\.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=short_logs --config=v2
INFO: Reading rc options for 'build' from d:\softwareinstaltion\tensorflow-2.4.0\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=C:/Users/127051/AppData/Local/Programs/Python/Python37/python.exe --action_env PYTHON_LIB_PATH=C:/Users/127051/AppData/Local/Programs/Python/Python37/lib/site-packages --python_path=C:/Users/127051/AppData/Local/Programs/Python/Python37/python.exe --config=xla --action_env CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2 --action_env TF_CUDA_COMPUTE_CAPABILITIES=5.0 --config=cuda --define=override_eigen_strong_inline=true --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:short_logs in file d:\softwareinstaltion\tensorflow-2.4.0\.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file d:\softwareinstaltion\tensorflow-2.4.0\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file d:\softwareinstaltion\tensorflow-2.4.0\.bazelrc: --define=with_xla_support=true
INFO: Found applicable config definition build:cuda in file d:\softwareinstaltion\tensorflow-2.4.0\.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file d:\softwareinstaltion\tensorflow-2.4.0\.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=1
INFO: Found applicable config definition build:windows in file d:\softwareinstaltion\tensorflow-2.4.0\.bazelrc: --copt=/W0 --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=/experimental:preprocessor --host_copt=/experimental:preprocessor --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --experimental_strict_action_env=true --verbose_failures --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file d:\softwareinstaltion\tensorflow-2.4.0\.bazelrc: --define framework_shared_object=false
INFO: Repository local_config_cuda instantiated at:
  D:/softwareinstaltion/tensorflow-2.4.0/WORKSPACE:19:16: in <toplevel>
  D:/softwareinstaltion/tensorflow-2.4.0/tensorflow/workspace.bzl:96:19: in tf_repositories
Repository rule cuda_configure defined at:
  D:/softwareinstaltion/tensorflow-2.4.0/third_party/gpus/cuda_configure.bzl:1430:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
        File "D:/softwareinstaltion/tensorflow-2.4.0/third_party/gpus/cuda_configure.bzl", line 1400, column 38, in _cuda_autoconf_impl
                _create_local_cuda_repository(repository_ctx)
        File "D:/softwareinstaltion/tensorflow-2.4.0/third_party/gpus/cuda_configure.bzl", line 1244, column 56, in _create_local_cuda_repository
                host_compiler_includes + _cuda_include_path(
        File "D:/softwareinstaltion/tensorflow-2.4.0/third_party/gpus/cuda_configure.bzl", line 364, column 32, in _cuda_include_path
                inc_entries.append(realpath(repository_ctx, cuda_config.cuda_toolkit_path + "/include"))
        File "D:/softwareinstaltion/tensorflow-2.4.0/third_party/remote_config/common.bzl", line 277, column 19, in realpath
                return execute(repository_ctx, [bash_bin, "-c", "realpath \"%s\"" % path]).stdout.strip()
        File "D:/softwareinstaltion/tensorflow-2.4.0/third_party/remote_config/common.bzl", line 217, column 13, in execute
                fail(
Error in fail: Repository command failed
/usr/bin/realpath: missing operand
Try '/usr/bin/realpath --help' for more information.
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': no such package '@local_config_cuda//cuda': Repository command failed
/usr/bin/realpath: missing operand
Try '/usr/bin/realpath --help' for more information.
WARNING: Target pattern parsing failed.
ERROR: no such package '@local_config_cuda//cuda': Repository command failed
/usr/bin/realpath: missing operand
Try '/usr/bin/realpath --help' for more information.
INFO: Elapsed time: 1.781s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package

```

**Comment by Saduf2019** [comment]
@aligoglos 
Every TensorFlow release is compatible with a certain CUDA and cuDNN version. Please go through the [tested build configurations ](https://www.tensorflow.org/install/source#gpu)for more information.

Please try building TensorFlow 2.4 with CUDA 11 and cuDNN 8 and check if you are facing the same error. 
Also refer to similar issues: #45762, #45001 , #44251 Thanks!

**Comment by ZoeZhang91** [comment]
My GPU is GeForce RTX 2080ti, CUDA11.0, cuDNN 8.0.5，i‘ve tried to switch  tensorflow 2.4.0rc1, rc2, rc3, rc4 and 2.4.1, also tried to change the cuDNN version to 8.1.0, but they all still  got the same error as above...
Really need some help.
