### ISSUE TITLE
SparseTensor mul. broadcasting gradient fails

### ISSUE THREAD

**Issue by jackd** [tensorflow/tensorflow#46008]
## System information
- Have I written custom code: yes
- OS Platform and Distribution: Linux Ubuntu 18.04
- TensorFlow installed from: binary
- TensorFlow version: v1.12.1-47912-gec43aacb56f 2.5.0-dev20201219
- Python version: 3.7

## Current behavior

Computing gradients of scaled `tf.SparseTensor`s fails. This is resolved be adding dimensions to scalar.

## Expected behavior

Gradient computation compatible with automatic dimension adding when broadcasting leading dimensions.

## Standalone code to reproduce the issue

[Notebook](https://colab.research.google.com/drive/1R-HV0570iNzbY3yUGXSuqnikPWZd6aDO?usp=sharing)

Code copied below for convenience

```python
import tensorflow as tf

n = 5
values = tf.Variable(tf.random.uniform((n,)))
indices = tf.sparse.eye(n).indices
with tf.GradientTape() as tape:
    tape.watch(values)
    st = tf.SparseTensor(indices, values, (n, n))
    st = st * 2.                        # doesn't work
    # st = st * tf.reshape(2., (1, 1))  # works
    loss = tf.sparse.reduce_sum(st)

grad = tape.gradient(loss, values)
print(grad)
```

## Stack Trace

```txt
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    grad = tape.gradient(loss, values)
  File "/home/jackd/anaconda3/envs/tf-nightly/lib/python3.7/site-packages/tensorflow/python/eager/backprop.py", line 1073, in gradient
    unconnected_gradients=unconnected_gradients)
  File "/home/jackd/anaconda3/envs/tf-nightly/lib/python3.7/site-packages/tensorflow/python/eager/imperative_grad.py", line 77, in imperative_grad
    compat.as_str(unconnected_gradients.value))
  File "/home/jackd/anaconda3/envs/tf-nightly/lib/python3.7/site-packages/tensorflow/python/eager/backprop.py", line 162, in _gradient_function
    return grad_fn(mock_op, *out_grads)
  File "/home/jackd/anaconda3/envs/tf-nightly/lib/python3.7/site-packages/tensorflow/python/ops/sparse_grad.py", line 247, in _SparseDenseCwiseMulGrad
    return _SparseDenseCwiseMulOrDivGrad(op, grad, True)
  File "/home/jackd/anaconda3/envs/tf-nightly/lib/python3.7/site-packages/tensorflow/python/ops/sparse_grad.py", line 227, in _SparseDenseCwiseMulOrDivGrad
    dense_vals = array_ops.gather_nd(y, scaled_indices)
  File "/home/jackd/anaconda3/envs/tf-nightly/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/home/jackd/anaconda3/envs/tf-nightly/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 5348, in gather_nd
    return gen_array_ops.gather_nd(params, indices, name=name)
  File "/home/jackd/anaconda3/envs/tf-nightly/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3695, in gather_nd
    _ops.raise_from_not_ok_status(e, name)
  File "/home/jackd/anaconda3/envs/tf-nightly/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 6870, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: params must be at least a vector [Op:GatherNd]
```

**Comment by Saduf2019** [comment]
I am able to replicate this issue on [tf 1.2](https://colab.research.google.com/gist/Saduf2019/a75de213ce562219ff1fd1bbd9eed796/untitled490.ipynb), and [2.x](https://colab.research.google.com/gist/Saduf2019/861409296603acc6294111438a54eedb/untitled489.ipynb). please find the gist [here](https://colab.research.google.com/gist/Saduf2019/6a81a7394447e5a06cac4022baa17b81/untitled488.ipynb).

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
