### ISSUE TITLE
 java.lang.NoClassDefFoundError: Failed resolution of: Lorg/tensorflow/lite/schema/Model;

### ISSUE THREAD

**Issue by doudou199291** [tensorflow/tensorflow#46029]
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/tensorflow/lite/schema/Model;
        at org.tensorflow.lite.support.metadata.ModelInfo.assertTFLiteModel(ModelInfo.java:222)
        at org.tensorflow.lite.support.metadata.ModelInfo.<init>(ModelInfo.java:64)
        at org.tensorflow.lite.support.metadata.MetadataExtractor.<init>(MetadataExtractor.java:75)
        at com.gc.testt.tflite.TFLiteObjectDetectionAPIModel.create(TFLiteObjectDetectionAPIModel.java:129)
        at com.gc.testt.ADetectorActivity.onPreviewSizeChosen(ADetectorActivity.java:84)
        at com.gc.testt.ACameraActivity.onPreviewFrame(ACameraActivity.java:147)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1512)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:192)
        at android.app.ActivityThread.main(ActivityThread.java:6738)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:525)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825)
     Caused by: java.lang.ClassNotFoundException: org.tensorflow.lite.schema.Model
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at org.tensorflow.lite.support.metadata.ModelInfo.assertTFLiteModel(ModelInfo.java:222) 
        at org.tensorflow.lite.support.metadata.ModelInfo.<init>(ModelInfo.java:64) 
        at org.tensorflow.lite.support.metadata.MetadataExtractor.<init>(MetadataExtractor.java:75) 
        at com.gc.testt.tflite.TFLiteObjectDetectionAPIModel.create(TFLiteObjectDetectionAPIModel.java:129) 
        at com.gc.testt.ADetectorActivity.onPreviewSizeChosen(ADetectorActivity.java:84) 
        at com.gc.testt.ACameraActivity.onPreviewFrame(ACameraActivity.java:147) 
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1512) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:192) 
        at android.app.ActivityThread.main(ActivityThread.java:6738) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:525) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/flatbuffers/Table;
        at org.tensorflow.lite.support.metadata.ModelInfo.assertTFLiteModel(ModelInfo.java:222) 
        at org.tensorflow.lite.support.metadata.ModelInfo.<init>(ModelInfo.java:64) 
        at org.tensorflow.lite.support.metadata.MetadataExtractor.<init>(MetadataExtractor.java:75) 
        at com.gc.testt.tflite.TFLiteObjectDetectionAPIModel.create(TFLiteObjectDetectionAPIModel.java:129) 
        at com.gc.testt.ADetectorActivity.onPreviewSizeChosen(ADetectorActivity.java:84) 
        at com.gc.testt.ACameraActivity.onPreviewFrame(ACameraActivity.java:147) 
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1512) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:192) 
        at android.app.ActivityThread.main(ActivityThread.java:6738) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:525) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.flatbuffers.Table" on path: DexPathList[[zip file "/data/app/com.gc.testt-RmxHcdzbPpW7fPFnmeS8Rw==/base.apk"],nativeLibraryDirectories=[/data/app/com.gc.testt-RmxHcdzbPpW7fPFnmeS8Rw==/lib/arm64, /data/app/com.gc.testt-RmxHcdzbPpW7fPFnmeS8Rw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64, /system/vendor/lib64/hw]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at org.tensorflow.lite.support.metadata.ModelInfo.assertTFLiteModel(ModelInfo.java:222) 
        at org.tensorflow.lite.support.metadata.ModelInfo.<init>(ModelInfo.java:64) 
        at org.tensorflow.lite.support.metadata.MetadataExtractor.<init>(MetadataExtractor.java:75) 
        at com.gc.testt.tflite.TFLiteObjectDetectionAPIModel.create(TFLiteObjectDetectionAPIModel.java:129) 
        at com.gc.testt.ADetectorActivity.onPreviewSizeChosen(ADetectorActivity.java:84) 
        at com.gc.testt.ACameraActivity.onPreviewFrame(ACameraActivity.java:147) 
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1512) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:192) 
        at android.app.ActivityThread.main(ActivityThread.java:6738) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:525) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825) 

Androidstudio using the Tensorflow-lite-Metadata - 0.0.0.0-Nightly JAR file, the Table file could not be found；

**Comment by doudou199291** [comment]
jar file download link  ：
https://bintray.com/google/tensorflow/tensorflow-lite-metadata/0.0.0-nightly#files/org%2Ftensorflow%2Ftensorflow-lite-metadata%2F0.0.0-nightly

**Comment by lu-wang-g** [comment]
We did have some issues with the process to upload Jcenter package. Not sure if that affected the metadata library or not, since the known issues are found to the Task library and the Support library. 

As I tested it just now, Tensorflow-lite-Metadata - 0.0.0.0-Nightly, works fine for me. Do you mind to try it again and see if you still see the issue?

**Comment by lu-wang-g** [comment]
Update: [TFLite metadata 0.1.0](https://bintray.com/google/tensorflow/tensorflow-lite-metadata) is now available. It should be much stable than the nightly version.
