### ISSUE TITLE
Bug: Converting quantized Keras models to TFLite

### ISSUE THREAD

**Issue by msquigle** [tensorflow/tensorflow#46054]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: Yes
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
-   **TensorFlow installed from (source or binary)**: binary
-   **TensorFlow version (use command below)**: 2.3.1
-   **Python version**: 3.8.2

### Describe the problem
Appears to be a bug when trying to convert quantized Keras models to TFLite. Goal is to be able to generate TFLite models using quantized TFHub models.

### Source code / logs
Source Code
import tensorflow as tf
import tensorflow_hub as hub

input_val = tf.keras.layers.Input(shape=(320,320,3), dtype=tf.uint8)
module = hub.KerasLayer('https://tfhub.dev/tensorflow/ssd_mobilenet_v2/fpnlite_320x320/1')(input_val)
model = tf.keras.models.Model(inputs=[input_val], outputs=[module])
model.summary()
converter = tf.lite.TFLiteConverter.from_keras_model(model)
model_out = converter.convert()

Error
tensorflow.lite.python.convert.ConverterError: <unknown>:0: error: loc("Func/functional_1/keras_layer/StatefulPartitionedCall/input/_1"): requires all operands and results to have compatible element types
<unknown>:0: note: loc("Func/functional_1/keras_layer/StatefulPartitionedCall/input/_1"): see current operation: %1 = "tf.Identity"(%arg0) {_class = ["loc:@Func/functional_1/keras_layer/StatefulPartitionedCall/StatefulPartitionedCall/input/_411"], device = ""} : (tensor<?x320x320x3x!tf.quint8>) -> tensor<?x320x320x3xui8>

TF 2.4.0 Error
line 32, in wrapped_toco_convert
    return _pywrap_toco_api.TocoConvert(
Exception: <unknown>:0: error: loc("Func/model/keras_layer/StatefulPartitionedCall/input/_1"): requires all operands and results to have compatible element types

line 216, in toco_convert_protos
    raise ConverterError(str(e))
tensorflow.lite.python.convert.ConverterError: <unknown>:0: error: loc("Func/model/keras_layer/StatefulPartitionedCall/input/_1"): requires all operands and results to have compatible element types

**Comment by sayakpaul** [comment]
Hey. 

The hub modules for SSD MobileNet might not be directly convertible to TensorFlow Lite. The idea here is to first convert it to something that compatible with the current opset of TensorFlow Lite. This is detailed [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tf2.md). 

However, [here's a repository](https://github.com/sayakpaul/E2E-Object-Detection-in-TFLite) that would show you an end-to-end example of converting an SSD MobileNet to TFLite and running inference with it. I hope you'd find it useful.

**Comment by msquigle** [comment]
It doesn't appear to be an issue with any operations as if we create a single output ssd model where the two outputs are concatenated together, we can use tf.keras.Sequential with the model and the TFLiteConverter will work. Also using a float version of the model does not lead to any issues. It appears to be an issue with the datatypes, where it is unable to handle uint8 tensors as seen with the error  (tensor<?x320x320x3x!tf.quint8>) -> tensor<?x320x320x3xui8> with the tf.Identity operation. I also was testing with the https://tfhub.dev/tensorflow/ssd_mobilenet_v2/2 model which I know has all of the supported ops in TFLite, it still gives the error of "requires all operands and results to have compatible element types" which leads me back to the issue with datatype conversion in the TFLiteConverter.

Thanks though for the links, I'll take a look to see if there could be an unsupported op with the fpnlite version of the SSD

**Comment by WindQAQ** [comment]
@msquigle It appears that your input is uint8, which is supported only in quantization mode. As a workaround, you can do the following things. If you want to do some post training quantization, please follow the [guideline](https://www.tensorflow.org/lite/performance/post_training_quantization). Thank you!

```python
float_input = tf.keras.layers.Input(shape=(320, 320, 3), dtype=tf.float32)
uint8_input = tf.cast(float_input, dtype=tf.uint8)
module = hub.KerasLayer('https://tfhub.dev/tensorflow/ssd_mobilenet_v2/fpnlite_320x320/1')(uint8_input)
model = tf.keras.models.Model(inputs=[float_input], outputs=[module])
model.summary()
model.save("/tmp/ssd_mobilenet_v2")
converter = tf.lite.TFLiteConverter.from_keras_model(model)
model_out = converter.convert()
```

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/python/lite.py#L551-L568

**Comment by msquigle** [comment]
So that snippet of code definitely seems to move things in the right direction, but it leads to the following error

Traceback (most recent call last):
  File "tfhub_functional.py", line 12, in <module>
    model_out = converter.convert()
  File "lib\site-packages\tensorflow\lite\python\lite.py", line 873, in convert
    return super(TFLiteKerasModelConverterV2,
  File "lib\site-packages\tensorflow\lite\python\lite.py", line 624, in convert
    result = _toco_convert_impl(
  File "lib\site-packages\tensorflow\lite\python\convert.py", line 608, in toco_convert_impl
    data = toco_convert_protos(
  File "lib\site-packages\tensorflow\lite\python\convert.py", line 216, in toco_convert_protos
    raise ConverterError(str(e))
tensorflow.lite.python.convert.ConverterError: lib\site-packages\tensorflow\python\saved_model\load.py:889:0: error: 'tf.Size' op is neither a custom op nor a flex op
lib\site-packages\tensorflow\python\saved_model\load.py:859:0: note: called from
lib\site-packages\tensorflow_hub\module_v2.py:106:0: note: called from
lib\site-packages\tensorflow_hub\keras_layer.py:421:0: note: called from
lib\site-packages\tensorflow_hub\keras_layer.py:152:0: note: called from
tfhub_functional.py:6:0: note: called from
<unknown>:0: error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):
        tf.Size {device = ""}

I attempted using the experimental converter as well as a few other small modifications, but it seems to always result in that error.

**Comment by abattery** [comment]
You can enable tf.Size through Select TF option. https://www.tensorflow.org/lite/guide/ops_select

**Comment by mohantym** [comment]
Hi @msquigle , This issue is not replicating in latest version 2.6 . Attaching [Gist](https://colab.research.google.com/gist/mohantym/4b559854514c414c372112ebc6b0246f/github_46054.ipynb) for reference. Please create a new issue if it is persisting in latest version.Thanks!
