### ISSUE TITLE
undefined symbol: _ZN6tflite12tensor_utils27NeonSymmetricQuantizeFloatsEPKfiPaPfS4_S4_

### ISSUE THREAD

**Issue by RunChengNi** [tensorflow/tensorflow#46082]
when I run .tflite file in my Raspberry Pi 3B+ ,some errors happened.
Python version: 3.7.3
Tensorflow version: 1.13.1
GCC: 8.3.0
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
I have changed tf version but it did not worK. 
Please help!!
here is the error:
`Traceback (most recent call last):
  File "/home/pi/project/test.py", line 62, in <module>
    interpreter = tf.lite.Interpreter(model_path=tflite_path)
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/lite/python/interpreter.py", line 154, in __init__
    _interpreter_wrapper.InterpreterWrapper_CreateWrapperCPPFromFile(
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/util/lazy_loader.py", line 62, in __getattr__
    module = self._load()
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/util/lazy_loader.py", line 45, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py", line 28, in <module>
    _tensorflow_wrap_interpreter_wrapper = swig_import_helper()
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py", line 24, in swig_import_helper
    _mod = imp.load_module('_tensorflow_wrap_interpreter_wrapper', fp, pathname, description)
  File "/usr/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/pi/.local/lib/python3.7/site-packages/tensorflow_core/lite/python/interpreter_wrapper/_tensorflow_wrap_interpreter_wrapper.so: undefined symbol: _ZN6tflite12tensor_utils24NeonVectorScalarMultiplyEPKaifPf
`

**Comment by RunChengNi** [comment]
> From the template it looks like you are installing **TensorFlow** (TF) prebuilt binaries:
> 
> * For TF-GPU - See point 1
> * For TF-CPU - See point 2
> 
> **1. Installing **TensorFlow-GPU** (TF) prebuilt binaries**
> 
> Make sure you are using compatible TF and CUDA versions. Please refer following TF version and CUDA version compatibility table.
> 
> TF	CUDA
> 2.1.0 - 2.2.0	10.1
> 1.13.1 - 2.0	10.0
> 1.5.0 - 1.12.0	9.0
> * If you have above configuration and using _**Windows**_ platform -
>   
>   * Try adding the CUDA, CUPTI, and cuDNN installation directories to the %PATH% environment variable.
>   * Refer [windows setup guide](https://www.tensorflow.org/install/gpu#windows_setup).
> * If you have above configuration and using _**Ubuntu/Linux**_ platform -
>   
>   * Try adding the CUDA, CUPTI, and cuDNN installation directories to the $LD_LIBRARY_PATH environment variable.
>   * Refer [linux setup guide](https://www.tensorflow.org/install/gpu#linux_setup).
> * If error still persists then, apparently your CPU model does not support AVX instruction sets.
>   
>   * Refer [hardware requirements](https://www.tensorflow.org/install/pip#hardware-requirements).
> 
> **2. Installing **TensorFlow** (TF) CPU prebuilt binaries**
> 
> _TensorFlow release binaries version 1.6 and higher are prebuilt with AVX instruction sets._
> 
> Therefore on any CPU that does not have these instruction sets, either CPU or GPU version of TF will fail to load.
> Apparently, your CPU model does not support AVX instruction sets. You can still use TensorFlow with the alternatives given below:
> 
> * Try Google Colab to use TensorFlow.
>   
>   * The easiest way to use TF will be to switch to [google colab](https://colab.sandbox.google.com/notebooks/welcome.ipynb#recent=true). You get pre-installed latest stable TF version. Also you can use `pip install`  to install any other preferred TF version.
>   * It has an added advantage since you can you easily switch to different hardware accelerators (cpu, gpu, tpu) as per the task.
>   * All you need is a good internet connection and you are all set.
> * Try to build TF from sources by changing CPU optimization flags.
> 
> _Please let us know if this helps._

Thanks，i will try.

**Comment by ravikyram** [comment]
@RunChengNi 

Is it possible for you to try latest TF stable version 2.4 or nightly versivons and let us know whether the issue persists? There were lots of performance improvements in the latest versions. Thanks!

**Comment by RunChengNi** [comment]
@ravikyram Yeah,it worked,I try TF version 2.4.But it should be noted that using pip directly was uesless,I downloaded whl file，and then pip it.
