### ISSUE TITLE
ProfilerNotRunningError: Cannot stop profiling. No profiler is running. raised using profiler in tf.function

### ISSUE THREAD

**Issue by JacdDev** [tensorflow/tensorflow#46103]
Hello. I'm trying to use profiling in my custom tf.function, but I'm getting the following error calling `tf.summary.trace_export` 

`tensorflow.python.eager.profiler.ProfilerNotRunningError: Cannot stop profiling. No profiler is running.`

I followed the tutorial in [https://www.tensorflow.org/tensorboard/graphs](https://www.tensorflow.org/tensorboard/graphs) and I realized the error is raised in the tutorial too in line `tf.summary.trace_export(
      name="my_func_trace",
      step=0,
      profiler_outdir=logdir)`. I ran it using google colab in remote enviroment so I guess is a bug in version 2.4

Does anybody another way to achieve it?

**Comment by JacdDev** [comment]
I've just tried the google colab script using tensorflow 2.2 with `!pip install tensorflow==2.2` and it runs perfectly, it also works well in 2.3, when I come back to tensorflow 2.4 it fails again so it's a problem in the 2.4 version.

**Comment by ravikyram** [comment]
@JacdDev 

The issue was fixed in TF nightly version. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/6d100b4fcd1f33709b9eac13d29a6a4f/untitled592.ipynb).Please, verify once and close the issue. Thanks!

**Comment by JacdDev** [comment]
@ravikyram 

The code runs perfectly using tf-nightly, but when I try to visualize the tensorboard panel running `%tensorboard --logdir logs/func` it trows the following error, I don't know if they are related or it is a different issue:

ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
2021-01-04 08:57:20.911634: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2021-01-04 08:57:20.911700: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/usr/local/bin/tensorboard", line 8, in <module>
    sys.exit(run_main())
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/main.py", line 71, in run_main
    app.run(tensorboard.main, flags_parser=tensorboard.configure)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/program.py", line 283, in main
    return runner(self.flags) or 0
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/program.py", line 299, in _run_serve_subcommand
    server = self._make_server()
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/program.py", line 436, in _make_server
    deprecated_multiplexer,
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/backend/application.py", line 149, in TensorBoardWSGIApp
    experimental_middlewares,
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/backend/application.py", line 257, in __init__
    "Duplicate plugins for name %s" % plugin.plugin_name
ValueError: Duplicate plugins for name projector

**Comment by ravikyram** [comment]
@JacdDev 

Please, refer the [link](https://github.com/tensorflow/tensorboard/issues/3443), [link1](https://stackoverflow.com/questions/57228487/valueerror-duplicate-plugins-for-name-projector) and see if it helps you. Thanks!

**Comment by JacdDev** [comment]
@ravikyram 

Thanks, the problem was solved unistalling tensorboard before installing tf-nighlty as said in [this comment](https://github.com/tensorflow/tensorboard/issues/3443#issuecomment-618114726)
