### ISSUE TITLE
ImportError: cannot import name 'function_pb2' from 'tensorflow.core.framework' (unknown location)

### ISSUE THREAD

**Issue by xiedeacc** [tensorflow/tensorflow#46102]
**System information**
- ubuntu20.04
- build tf from source
- TensorFlow version (use command below):2.5
- Python version:3.8.5
- Bazel version (if compiling from source):3.7.2
- GCC/Compiler version (if compiling from source):gcc-9
- CUDA/cuDNN version:11.1

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: libtensorflow_framework.so.2: cannot open shared object file: No such file or directory

**Comment by xiedeacc** [comment]
first: coundn't run python -c "import tensorflow as tf; print(tf.__version__)" in tensorflow source code directory.
second, shoud build libtensorflow target and copy all *.so file to library search path
