### ISSUE TITLE
Bazel out of memory at checking cache actions when building for ARMv8

### ISSUE THREAD

**Issue by KumaTea** [tensorflow/tensorflow#46120]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

### System information
- OS Platform and Distribution: Ubuntu 20.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: v2.4.0
- Python version: 3.8
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 9.3.0
- CUDA/cuDNN version: None
- GPU model and memory: None

### Describe the problem

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Hello.

I am tried to build tensorflow v2.4.0 from source for aarch64 / ARMv8 devices. I did this on a quad core A53 single board with 1GB RAM.

The process was always terminated at the time when about 3000 targets were done. At that moment, Bazel showed **Checking cache actions**, stuck for a while and raise java out of memory error.

I thought that the RAM and swap might be not enough, so I picked a 8GB USB drive and use it as swap. But the building process still crashed.

So, how much memory does it need when building tensorflow? Should I at least double the swap size, or any step is wrong?

Thank you.

**Comment by bhack** [comment]
Can you try to test with https://docs.bazel.build/versions/master/memory-saving-mode.html ?

**Comment by KumaTea** [comment]
> Can you try to test with https://docs.bazel.build/versions/3.1.0/memory-saving-mode.html?

Thanks. I've tried `--host_jvm_args=-Xmx512m` before and failed. I'll try `--host_jvm_args=-Xmx8g` now...

**Comment by mihaimaruseac** [comment]
Note that likely this is not a TF bug.

**Comment by bhack** [comment]
@mihaimaruseac many people want to have this Documented. E.g. see https://github.com/tensorflow/tensorflow/issues/42066

**Comment by KumaTea** [comment]
### Status Update

Since 3 days ago I have been trying to build with that flag. The building process has crushed for roughly 10 times, but only one of them is **`java.lang.OutOfMemoryError: Java heap space`**:

```
root@cacd588b8a9d:~/tensorflow/tf# bazel build //tensorflow/tools/pip_package:build_pip_package
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=156
INFO: Reading rc options for 'build' from /root/tensorflow/tf/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /root/tensorflow/tf/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=short_logs --config=v2
INFO: Reading rc options for 'build' from /root/tensorflow/tf/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env PYTHON_LIB_PATH=/usr/lib/python3/dist-packages --python_path=/usr/bin/python3 --config=xla --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:short_logs in file /root/tensorflow/tf/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /root/tensorflow/tf/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file /root/tensorflow/tf/.bazelrc: --define=with_xla_support=true
INFO: Found applicable config definition build:linux in file /root/tensorflow/tf/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
INFO: Found applicable config definition build:dynamic_kernels in file /root/tensorflow/tf/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
INFO: Analyzed target //tensorflow/tools/pip_package:build_pip_package (404 packages loaded, 30546 targets configured).
INFO: Found 1 target...
ERROR: /root/tensorflow/tf/tensorflow/python/BUILD:733:27: C++ compilation of rule '//tensorflow/python:_pywrap_tfprof.so' failed (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 119 argument(s) skipped)
tensorflow/python/util/tfprof_wrapper.cc: In constructor 'pybind11::cpp_function::cpp_function(Func&&, const Extra& ...) [with Func = pybind11::detail::all_type_info_get_cache(PyTypeObject*)::<lambda(pybind11::handle)>; Extra = {}; <template-parameter-1-3> = void]':
tensorflow/python/util/tfprof_wrapper.cc:46:1: internal compiler error: Segmentation fault
   46 | }
      | ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-9/README.Bugs> for instructions.
Internal error thrown during build. Printing stack trace: java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.Arrays.copyOfRange(Unknown Source)
        at java.base/java.lang.StringCoding.decodeLatin1(Unknown Source)
        at java.base/java.lang.StringCoding.decode(Unknown Source)
        at java.base/java.lang.String.<init>(Unknown Source)
        at java.base/java.lang.String.<init>(Unknown Source)
        at com.google.devtools.build.lib.analysis.actions.FileWriteAction$CompressedString.toString(FileWriteAction.java:210)
        at com.google.devtools.build.lib.analysis.actions.FileWriteAction.getFileContents(FileWriteAction.java:231)
        at com.google.devtools.build.lib.analysis.actions.FileWriteAction.computeKey(FileWriteAction.java:261)
        at com.google.devtools.build.lib.actions.ActionKeyCacher.computeActionKey(ActionKeyCacher.java:52)
        at com.google.devtools.build.lib.actions.ActionKeyCacher.getKey(ActionKeyCacher.java:41)
        at com.google.devtools.build.lib.actions.ActionCacheChecker.mustExecute(ActionCacheChecker.java:343)
        at com.google.devtools.build.lib.actions.ActionCacheChecker.getTokenIfNeedToExecute(ActionCacheChecker.java:292)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.checkActionCache(SkyframeActionExecutor.java:576)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:765)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:314)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

ERROR: bazel crash in async thread:
java.lang.OutOfMemoryError: Java heap space
        at com.google.common.io.ByteStreams.toByteArrayInternal(ByteStreams.java:176)
        at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:221)
        at com.google.common.io.ByteSource.read(ByteSource.java:286)
        at com.google.devtools.build.lib.vfs.FileSystemUtils.readContent(FileSystemUtils.java:820)
        at com.google.devtools.build.lib.vfs.FileSystemUtils.readContentAsLatin1(FileSystemUtils.java:789)
        at com.google.devtools.build.lib.server.PidFileWatcher.pidFileValid(PidFileWatcher.java:100)
        at com.google.devtools.build.lib.server.PidFileWatcher.runPidFileChecks(PidFileWatcher.java:77)
        at com.google.devtools.build.lib.server.PidFileWatcher.run(PidFileWatcher.java:68)
[2,595 / 2,848] checking cached actions

Server terminated abruptly (error code: 14, error message: 'Socket closed', log file: '/root/.cache/bazel/_bazel_root/2e11e70b086253c0d6d49f106d1e85c5/server/jvm.out')
```

And the rest are **`internal compiler error: Segmentation fault`**:

```
INFO: Deleting stale sandbox base /root/.cache/bazel/_bazel_root/2e11e70b086253c0d6d49f106d1e85c5/sandbox
[5,864 / 7,381] 4 actions, 1 running
    Compiling tensorflow/core/grappler/optimizers/function_optimizer.cc; 427s local
    [Sched] Compiling tensorflow/core/grappler/optimizers/dependency_optimizer.cc; 427s
    [Sched] Compiling aws/aws-cpp-sdk-core/source/auth/AWSCredentialsProvider.cpp; 426s
    [Sched] Compiling tensorflow/core/grappler/utils/transitive_fanin.cc; 426s
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=short_logs --config=v2
INFO: Reading rc options for 'build' from /root/tensorflow/tf/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env PYTHON_LIB_PATH=/usr/lib/python3.8/dist-packages --python_path=/usr/bin/python3 --config=xla --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:short_logs in file /root/tensorflow/tf/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /root/tensorflow/tf/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file /root/tensorflow/tf/.bazelrc: --define=with_xla_support=true
INFO: Found applicable config definition build:linux in file /root/tensorflow/tf/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
INFO: Found applicable config definition build:dynamic_kernels in file /root/tensorflow/tf/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
INFO: Analyzed target //tensorflow/tools/pip_package:build_pip_package (404 packages loaded, 30546 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base /root/.cache/bazel/_bazel_root/2e11e70b086253c0d6d49f106d1e85c5/sandbox
ERROR: /root/tensorflow/tf/tensorflow/core/grappler/optimizers/BUILD:159:11: C++ compilation of rule '//tensorflow/core/grappler/optimizers:function_optimizer' failed (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 95 argument(s) skipped)
tensorflow/core/grappler/optimizers/function_optimizer.cc: In member function 'tensorflow::Status tensorflow::grappler::FunctionOptimizer::RunFunctionOptimizerPass(const tensorflow::grappler::GrapplerItem&, tensorflow::GraphDef*) const':
tensorflow/core/grappler/optimizers/function_optimizer.cc:1429:8: internal compiler error: Segmentation fault
 1429 | Status FunctionOptimizer::RunFunctionOptimizerPass(
      |        ^~~~~~~~~~~~~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-9/README.Bugs> for instructions.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 6347.840s, Critical Path: 568.99s
INFO: 588 processes: 17 internal, 571 local.
FAILED: Build did NOT complete successfully
```

```
root@cacd588b8a9d:~/tensorflow/tf# bazel --host_jvm_args=-Xmx8g build //tensorflow/tools/pip_package:build_pip_package --local_cpu_resources=1
Killed non-responsive server process (pid=35)
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=111
INFO: Reading rc options for 'build' from /root/tensorflow/tf/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /root/tensorflow/tf/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=short_logs --config=v2
INFO: Reading rc options for 'build' from /root/tensorflow/tf/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env PYTHON_LIB_PATH=/usr/lib/python3.8/dist-packages --python_path=/usr/bin/python3 --config=xla --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:short_logs in file /root/tensorflow/tf/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /root/tensorflow/tf/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file /root/tensorflow/tf/.bazelrc: --define=with_xla_support=true
INFO: Found applicable config definition build:linux in file /root/tensorflow/tf/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
INFO: Found applicable config definition build:dynamic_kernels in file /root/tensorflow/tf/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
INFO: Analyzed target //tensorflow/tools/pip_package:build_pip_package (404 packages loaded, 30546 targets configured).
INFO: Found 1 target...
ERROR: /root/tensorflow/tf/tensorflow/core/grappler/optimizers/BUILD:659:11: C++ compilation of rule '//tensorflow/core/grappler/optimizers:meta_optimizer' failed (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 109 argument(s) skipped)
In file included from external/com_google_absl/absl/container/flat_hash_map.h:41,
                 from ./tensorflow/core/framework/function.h:26,
                 from ./tensorflow/core/graph/graph.h:45,
                 from ./tensorflow/core/framework/device.h:44,
                 from ./tensorflow/core/common_runtime/device.h:18,
                 from ./tensorflow/core/common_runtime/device_set.h:23,
                 from ./tensorflow/core/grappler/optimizers/meta_optimizer.h:19,
                 from tensorflow/core/grappler/optimizers/meta_optimizer.cc:16:
external/com_google_absl/absl/container/internal/raw_hash_map.h: In instantiation of 'std::pair<typename absl::lts_2020_02_25::container_internal::raw_hash_map<Policy, Hash, Eq, Alloc>::raw_hash_set::iterator, bool> absl::lts_2020_02_25::container_internal::raw_hash_map<Policy, Hash, Eq, Alloc>::try_emplace_impl(K&&, Args&& ...) [with K = std::__cxx11::basic_string<char>; Args = {}; Policy = absl::lts_2020_02_25::container_internal::NodeHashMapPolicy<std::__cxx11::basic_string<char>, absl::lts_2020_02_25::flat_hash_set<tensorflow::NodeDef*> >; Hash = absl::lts_2020_02_25::container_internal::StringHash; Eq = absl::lts_2020_02_25::container_internal::StringHashEq::Eq; Alloc = std::allocator<std::pair<const std::__cxx11::basic_string<char>, absl::lts_2020_02_25::flat_hash_set<tensorflow::NodeDef*> > >; typename absl::lts_2020_02_25::container_internal::raw_hash_map<Policy, Hash, Eq, Alloc>::raw_hash_set::iterator = absl::lts_2020_02_25::container_internal::raw_hash_set<absl::lts_2020_02_25::container_internal::NodeHashMapPolicy<std::__cxx11::basic_string<char>, absl::lts_2020_02_25::flat_hash_set<tensorflow::NodeDef*> >, absl::lts_2020_02_25::container_internal::StringHash, absl::lts_2020_02_25::container_internal::StringHashEq::Eq, std::allocator<std::pair<const std::__cxx11::basic_string<char>, absl::lts_2020_02_25::flat_hash_set<tensorflow::NodeDef*> > > >::iterator]':
external/com_google_absl/absl/container/internal/raw_hash_map.h:121:76:   required from 'std::pair<typename absl::lts_2020_02_25::container_internal::raw_hash_map<Policy, Hash, Eq, Alloc>::raw_hash_set::iterator, bool> absl::lts_2020_02_25::container_internal::raw_hash_map<Policy, Hash, Eq, Alloc>::try_emplace(absl::lts_2020_02_25::container_internal::raw_hash_map<Policy, Hash, Eq, Alloc>::key_arg<K>&&, Args&& ...) [with K = std::__cxx11::basic_string<char>; Args = {}; typename std::enable_if<(! std::is_convertible<K, typename absl::lts_2020_02_25::container_internal::raw_hash_map<Policy, Hash, Eq, Alloc>::raw_hash_set::const_iterator>::value), int>::type <anonymous> = 0; K* <anonymous> = 0; Policy = absl::lts_2020_02_25::container_internal::NodeHashMapPolicy<std::__cxx11::basic_string<char>, absl::lts_2020_02_25::flat_hash_set<tensorflow::NodeDef*> >; Hash = absl::lts_2020_02_25::container_internal::StringHash; Eq = absl::lts_2020_02_25::container_internal::StringHashEq::Eq; Alloc = std::allocator<std::pair<const std::__cxx11::basic_string<char>, absl::lts_2020_02_25::flat_hash_set<tensorflow::NodeDef*> > >; typename absl::lts_2020_02_25::container_internal::raw_hash_map<Policy, Hash, Eq, Alloc>::raw_hash_set::iterator = absl::lts_2020_02_25::container_internal::raw_hash_set<absl::lts_2020_02_25::container_internal::NodeHashMapPolicy<std::__cxx11::basic_string<char>, absl::lts_2020_02_25::flat_hash_set<tensorflow::NodeDef*> >, absl::lts_2020_02_25::container_internal::StringHash, absl::lts_2020_02_25::container_internal::StringHashEq::Eq, std::allocator<std::pair<const std::__cxx11::basic_string<char>, absl::lts_2020_02_25::flat_hash_set<tensorflow::NodeDef*> > > >::iterator; absl::lts_2020_02_25::container_internal::raw_hash_map<Policy, Hash, Eq, Alloc>::key_arg<K> = std::__cxx11::basic_string<char>]'
external/com_google_absl/absl/container/internal/raw_hash_map.h:163:62:   required from 'absl::lts_2020_02_25::container_internal::raw_hash_map<Policy, Hash, Eq, Alloc>::MappedReference<P> absl::lts_2020_02_25::container_internal::raw_hash_map<Policy, Hash, Eq, Alloc>::operator[](absl::lts_2020_02_25::container_internal::raw_hash_map<Policy, Hash, Eq, Alloc>::key_arg<K>&&) [with K = std::__cxx11::basic_string<char>; P = absl::lts_2020_02_25::container_internal::NodeHashMapPolicy<std::__cxx11::basic_string<char>, absl::lts_2020_02_25::flat_hash_set<tensorflow::NodeDef*> >; K* <anonymous> = 0; Policy = absl::lts_2020_02_25::container_internal::NodeHashMapPolicy<std::__cxx11::basic_string<char>, absl::lts_2020_02_25::flat_hash_set<tensorflow::NodeDef*> >; Hash = absl::lts_2020_02_25::container_internal::StringHash; Eq = absl::lts_2020_02_25::container_internal::StringHashEq::Eq; Alloc = std::allocator<std::pair<const std::__cxx11::basic_string<char>, absl::lts_2020_02_25::flat_hash_set<tensorflow::NodeDef*> > >; absl::lts_2020_02_25::container_internal::raw_hash_map<Policy, Hash, Eq, Alloc>::MappedReference<P> = absl::lts_2020_02_25::flat_hash_set<tensorflow::NodeDef*>&; typename absl::lts_2020_02_25::container_internal::raw_hash_map<Policy, Hash, Eq, Alloc>::reference = std::pair<const std::__cxx11::basic_string<char>, absl::lts_2020_02_25::flat_hash_set<tensorflow::NodeDef*> >&; absl::lts_2020_02_25::container_internal::raw_hash_map<Policy, Hash, Eq, Alloc>::key_arg<K> = std::__cxx11::basic_string<char>]'
./tensorflow/core/grappler/utils.h:126:17:   required from 'tensorflow::grappler::internal::NodeMapInternal<GraphDefT, NodeDefT>::NodeMapInternal(GraphDefT*) [with GraphDefT = tensorflow::GraphDef; NodeDefT = tensorflow::NodeDef]'
./tensorflow/core/grappler/utils.h:235:60:   required from here
external/com_google_absl/absl/container/internal/raw_hash_map.h:190:3: internal compiler error: Segmentation fault
  190 |   }
      |   ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-9/README.Bugs> for instructions.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2289.998s, Critical Path: 678.29s
INFO: 40 processes: 5 internal, 35 local.
FAILED: Build did NOT complete successfully
```

Each time the file that raised error are not same.

This is not caused by out of memory, as far as I think. So this issue could be closed. I'll try to find solutions or create a new issue about that. Thank you!

P.S.: Each time I start building, `bazel` seems to start from beginning. I've seen some components to be compiled more than 3 times. That's wired and different from most compilers, which could be continue from where they stops, as I know.

**Comment by bhack** [comment]
For that board board It Is more the case to build and use TF lite:

https://www.tensorflow.org/lite/guide/build_arm64?hl=en

**Comment by KumaTea** [comment]
> For that board board It Is more the case to build and use TF lite:
> 
> https://www.tensorflow.org/lite/guide/build_arm64?hl=en

Thank you. Tensorflow Lite could be successfully built on the board, and I just want to try if the whole package can be built. 

I've found this nice repo [lhelontra/tensorflow-on-arm](https://github.com/lhelontra/tensorflow-on-arm) and successfully cross-compiled a working `whl` of `tensorflow` v2.4.0.

I would conclude this issue as an impossibile trial due to hardware restrictions. Thanks for the help again!
