### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by Kai-Beast223** [tensorflow/tensorflow#46127]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10 enterprise
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version: nightly or 2.4
- Python version: 3.8.6
- Installed using virtualenv? pip? conda?: normal pip
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: 11.0 (Recomemded
- GPU model and memory: gtx 1060 6gb

**Describe the problem**

I run pip install tf-nightly or pip install tensorflow and get the following error
 ERROR: Command errored out with exit status 1:
     command: 'c:\users\kai\appdata\local\programs\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\kai\\AppData\\Local\\Temp\\pip-install-w2yenss2\\wrapt\\setup.py'"'"'; __file__='"'"'C:\\Users\\kai\\AppData\\Local\\Temp\\pip-install-w2yenss2\\wrapt\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\kai\AppData\Local\Temp\pip-pip-egg-info-bql118ug'
         cwd: C:\Users\kai\AppData\Local\Temp\pip-install-w2yenss2\wrapt\
    Complete output (26 lines):
    Traceback (most recent call last):
      File "c:\users\kai\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 2866, in get_entry_map
        ep_map = self._ep_map
      File "c:\users\kai\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 2824, in __getattr__
        raise AttributeError(attr)
    AttributeError: _ep_map

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\kai\AppData\Local\Temp\pip-install-w2yenss2\wrapt\setup.py", line 102, in <module>
        run_setup(with_extensions=True)
      File "C:\Users\kai\AppData\Local\Temp\pip-install-w2yenss2\wrapt\setup.py", line 72, in run_setup
        setup(**setup_kwargs_tmp)
      File "c:\users\kai\appdata\local\programs\python\python38\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\users\kai\appdata\local\programs\python\python38\lib\site-packages\setuptools\dist.py", line 427, in __init__
        for ep in pkg_resources.iter_entry_points('distutils.setup_keywords'):
      File "c:\users\kai\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 655, in <genexpr>
        for entry in dist.get_entry_map(group).values()
      File "c:\users\kai\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 2868, in get_entry_map
        ep_map = self._ep_map = EntryPoint.parse_map(
      File "c:\users\kai\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 2549, in parse_map
        raise ValueError("Entry points must be listed in groups")
    ValueError: Entry points must be listed in groups
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by mihaimaruseac** [comment]
This looks like your setup of python tools is broken, the error does not come from TF.

**Comment by Kai-Beast223** [comment]
how would i fix this then?

**Comment by Kai-Beast223** [comment]
This is a on a fresh install of python so not sure.

**Comment by mihaimaruseac** [comment]
Did you install python from the Windows marketplace or from the official site?

**Comment by Kai-Beast223** [comment]
official site 3.8.7 to be exact

**Comment by Kai-Beast223** [comment]
I fixed that issue now i just have to figure out why tf is loading due to numpy  ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
  File "C:\Users\kai\Desktop\test.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\kai\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
  File "C:\Users\kai\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\kai\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\context.py", line 29, in <module>
    import numpy as np
  File "C:\Users\kai\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\__init__.py", line 305, in <module>
    _win_os_check()
heck
    raise RuntimeError(msg.format(__file__)) from None
RuntimeError: The current Numpy installation ('C:\\Users\\kai\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
im on numpy 1.9.4 so not sure.
