### ISSUE TITLE
Installation/Import issue. Help required.

### ISSUE THREAD

**Issue by the-it-weirdo** [tensorflow/tensorflow#46124]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
  -  OS Name:                   Microsoft Windows 10 Home Single Language
  -  OS Version:                10.0.18363 N/A Build 18363
  -  OS Manufacturer:           Microsoft Corporation
  -  OS Configuration:          Standalone Workstation
  -  OS Build Type:             Multiprocessor Free

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): pip
- TensorFlow version: 2.x
- Python version: 3.7.3
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Installed without any issue. But when trying to import, ImportError occurs.**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
 1. ```pip install tensorflow --verbose --user```
 2. Then opened a .py file with first and only line as : ```import tensorflow```
 3. Saved the .py file and opened a new cmd window in the same directory.
 4. Executed ```python name_of_the_file.py```

**Any other info / logs**

Traceback (most recent call last):
  File "C:\Users\ddsme\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <
module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ddsme\AppData\Roaming\Python\Python37\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\ddsme\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\__init__.py", line 39, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "C:\Users\ddsme\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <
module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\ddsme\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <
module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

**Comment by the-it-weirdo** [comment]
**Update**
Installing _'Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019'_ solved the issue.
