### ISSUE TITLE
java.lang.IllegalArgumentException: Internal error: Cannot create interpreter: Didn't find op for builtin opcode 'CONV_2D' version '5'

### ISSUE THREAD

**Issue by vaibhavgupta2507** [tensorflow/tensorflow#46136]
I am going through the following codelab:
https://developer.android.com/codelabs/digit-classifier-tflite#5

## Description of issue:
I get the following error

  2021-01-04 14:58:02.547 27206-27283/org.tensorflow.lite.codelabs.digitclassifier E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
      Process: org.tensorflow.lite.codelabs.digitclassifier, PID: 27206
      java.lang.IllegalArgumentException: Internal error: Cannot create interpreter: Didn't find op for builtin opcode 'CONV_2D' version '5'
      
      Registration failed.
      
          at org.tensorflow.lite.NativeInterpreterWrapper.createInterpreter(Native Method)
          at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:70)
          at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:61)
          at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:224)
          at org.tensorflow.lite.codelabs.digitclassifier.DigitClassifier.initializeInterpreter(DigitClassifier.kt:64)
          at org.tensorflow.lite.codelabs.digitclassifier.DigitClassifier.access$initializeInterpreter(DigitClassifier.kt:31)
          at org.tensorflow.lite.codelabs.digitclassifier.DigitClassifier$initialize$1.run(DigitClassifier.kt:48)
          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
          at java.lang.Thread.run(Thread.java:919)

### Clear description

I have looked this up online. It points to some differences in the TF and TFLite versions. But I followed the steps exactly in the codelab and did not expect something like this.

**Comment by amahendrakar** [comment]
@vaibhavgupta2507,
In order to expedite the trouble-shooting process, could you please provide the following information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

and also the exact sequence of commands / steps that you executed before running into the error. Thanks!

**Comment by vaibhavgupta2507** [comment]
OS: Ubuntu 20.04
Mobile Device: Realme 9 Pro
Tensorflow: Used the colab notebook
Tensorflow version: 2.4.0
Python version: 3.6.9
Bazel Version: (`bazel version` command fails, saying that the term bazel is not recognized)
Cuda Version: 10.1 (got from the nvidia-smi command)

Steps:
I simply ran the notebook from (https://developer.android.com/codelabs/digit-classifier-tflite#5)
After downloading the model (from the notebook), I placed it in the assets folder of the Android app
But I get a runtime error with the above logs

**Comment by abattery** [comment]
Could you make sure the the android application has the same TensorFlow version with TensorFlow Python version that was used for TFLite model conversion?

**Comment by vaibhavgupta2507** [comment]
I tried using the same version of Tensorflow for the Android app as suggested

`implementation 'org.tensorflow:tensorflow-lite:2.4.0'`

But now I am getting a new error:-
```
2021-01-05 18:05:16.092 12296-12408/org.tensorflow.lite.codelabs.digitclassifier E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
    Process: org.tensorflow.lite.codelabs.digitclassifier, PID: 12296
    java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.
        at org.tensorflow.lite.NativeInterpreterWrapper.applyDelegate(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.applyDelegates(NativeInterpreterWrapper.java:373)
        at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:85)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:63)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:277)
        at org.tensorflow.lite.codelabs.digitclassifier.DigitClassifier.initializeInterpreter(DigitClassifier.kt:64)
        at org.tensorflow.lite.codelabs.digitclassifier.DigitClassifier.access$initializeInterpreter(DigitClassifier.kt:31)
        at org.tensorflow.lite.codelabs.digitclassifier.DigitClassifier$initialize$1.run(DigitClassifier.kt:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by abattery** [comment]
In the colab, it does not fix the batch size of the keras model but it just does preprocessing and postprocessing of the data. You need to set a batch size in the keras model after training or you can set a batch size through TFLite converter V1 API with the input_shapes argument.
