### ISSUE TITLE
TF2.1 .h5 file to .pb

### ISSUE THREAD

**Issue by EdwardVincentMa** [tensorflow/tensorflow#46288]
```
from tensorflow.python.keras.models import load_model
import tensorflow as tf


H5Path = "xxx.h5"
YoloV5s_model = load_model(H5Path, compile=False)
YoloV5s_model.summary()
YoloV5s_model.save("a.pb")
```

2021-01-08 20:36:37.248006: W tensorflow/python/util/util.cc:319] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
Traceback (most recent call last):
  File "TFLoadH5AndInfer.py", line 18, in <module>
    YoloV5s_model.save("Yolov5s_1.pb")
  File "C:\ProgramData\anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 1008, in save
    signatures, options)
  File "C:\ProgramData\anaconda3\lib\site-packages\tensorflow_core\python\keras\saving\save.py", line 115, in save_model
    signatures, options)
  File "C:\ProgramData\anaconda3\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\save.py", line 78, in save
    save_lib.save(model, filepath, signatures, options)
  File "C:\ProgramData\anaconda3\lib\site-packages\tensorflow_core\python\saved_model\save.py", line 899, in save
    _ = _SaveableView(checkpoint_graph_view)
  File "C:\ProgramData\anaconda3\lib\site-packages\tensorflow_core\python\saved_model\save.py", line 165, in __init__
    self.checkpoint_view.objects_ids_and_slot_variables())
  File "C:\ProgramData\anaconda3\lib\site-packages\tensorflow_core\python\training\tracking\graph_view.py", line 415, in objects_ids_and_slot_variables
    trackable_objects, path_to_root = self._breadth_first_traversal()
  File "C:\ProgramData\anaconda3\lib\site-packages\tensorflow_core\python\training\tracking\graph_view.py", line 199, in _breadth_first_traversal
    for name, dependency in self.list_dependencies(current_trackable):
  File "C:\ProgramData\anaconda3\lib\site-packages\tensorflow_core\python\saved_model\save.py", line 113, in list_dependencies
    for name, dep in super(_AugmentedGraphView, self).list_dependencies(obj):
  File "C:\ProgramData\anaconda3\lib\site-packages\tensorflow_core\python\training\tracking\graph_view.py", line 159, in list_dependencies
    return obj._checkpoint_dependencies
  File "C:\ProgramData\anaconda3\lib\site-packages\tensorflow_core\python\training\tracking\data_structures.py", line 744, in __getattribute__
    return object.__getattribute__(self, name)
  File "C:\ProgramData\anaconda3\lib\site-packages\tensorflow_core\python\training\tracking\data_structures.py", line 786, in _checkpoint_dependencies
    "ignored." % (self,))
ValueError: Unable to save the object {1: ListWrapper([0, 0, 0, 0]), 2: ListWrapper([0, 0, 0, 0]), 3: ListWrapper([1, 2, 2, 1])} (a dictionary wrapper constructed automatically on attribute assignment). The wrapped dictionary contains a non-string key which maps to a trackable object or mutable data structure.

If you don't need this dictionary checkpointed, wrap it in a tf.contrib.checkpoint.NoDependency object; it will be automatically un-wrapped and subsequently ignored.

**Comment by Saduf2019** [comment]
@EdwardVincentMa 
I ran the code shared and face different error due to dependencies not shared, please find [gist here](https://colab.research.google.com/gist/Saduf2019/88a0600859c52a5195d7b90155850013/untitled492.ipynb).

**Comment by bhack** [comment]
@Saduf2019 I think @EdwardVincentMa with `xxx.h5` means its own model.

@EdwardVincentMa can you share your model definition, a code snippet that we can just copy, past and run or a colab to reproduce your error?

**Comment by Saduf2019** [comment]
@bhack 
Our standard replies have "request for dependencies" which is the request for model used by user [so we could replicate the issue faced].

**Comment by bhack** [comment]
> @bhack
> Our standard replies have "request for dependencies" which is the request for model used by user [so we could replicate the issue faced].

Yes I understand but if the user can share a small model definition and saving code to reproduce this instead of only the saved model Is better for debugging the issue directly than make another round to request model definition.

Generally I think that if the user could minimize the code surface to reproduce the bug and not exactly share Its working example directly It Is faster to triage ISSUES.
