### ISSUE TITLE
Error at importing! 

### ISSUE THREAD

**Issue by sahilsngh** [tensorflow/tensorflow#46308]
### My 'tensorflow-GPU' was working fine yesterday but when I import it now it says-
 `Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Sahil Singh\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Sahil Singh\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\Sahil Singh\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\context.py", line 32, in <module>
    from tensorflow.core.framework import function_pb2
  File "C:\Users\Sahil Singh\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\core\framework\function_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "C:\Users\Sahil Singh\AppData\Local\Programs\Python\Python38\lib\site-packages\google\protobuf\__init__.py", line 37, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "C:\Users\Sahil Singh\AppData\Local\Programs\Python\Python38\lib\site-packages\pkg_resources.py", line 1479, in <module>
    register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)'`
`AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader`

**Comment by sahilsngh** [comment]
sorry my bad just installed `pip install tensorflow-gpu==2.3.0` it worked.
Thanks.
