### ISSUE TITLE
TfLite: Internal error: Cannot create interpreter: Didn't find op for builtin opcode 'CONV_2D' version '5'

### ISSUE THREAD

**Issue by bug-L** [tensorflow/tensorflow#46409]
I was trying to create the digit classifier Android app from [codelabs](https://developer.android.com/codelabs/digit-classifier-tflite#0)

At runtime, I get this error:

E/AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
    Process: org.tensorflow.lite.codelabs.digitclassifier, PID: 18122
    java.lang.IllegalArgumentException: Internal error: Cannot create interpreter: Didn't find op for builtin opcode 'CONV_2D' version '5'
    
    Registration failed.
    
        at org.tensorflow.lite.NativeInterpreterWrapper.createInterpreter(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:72)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:63)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:237)
        at org.tensorflow.lite.codelabs.digitclassifier.DigitClassifier.initializeInterpreter(DigitClassifier.kt:66)
        at org.tensorflow.lite.codelabs.digitclassifier.DigitClassifier.access$initializeInterpreter(DigitClassifier.kt:31)
        at org.tensorflow.lite.codelabs.digitclassifier.DigitClassifier$initialize$1.run(DigitClassifier.kt:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

I have tried changing the tflite version on build.gradle. Any other ideas on how to resolve this issue?

**Comment by Mohammad96Assaf** [comment]
try to use the same version of Tensorflow in the Android app in build.gradle.

**Comment by AhmadRaza159** [comment]
Check out the version of Tensorflow which you use while training, Use the same version in android build.gridle(app).
I use tensorflow 2.4.0 (which is latest) in colab while training, so I put (implementation 'org.tensorflow:tensorflow-lite:2.4.0')  in my android build.gridle(app)
