### ISSUE TITLE
LSTM doesnot work after tf_upgrade_v2 with keras.models.load_model, but tf.keras.models.load_model works

### ISSUE THREAD

**Issue by SingleBone** [tensorflow/tensorflow#46421]
**System information**
- Linux Ubuntu 16.04
- TensorFlow installed from pip
- TensorFlow version: v2.1.0-rc2-17-ge5bf8de 2.1.0
- Keras version: 2.3.1
- Python version: 3.6.12
- CUDA/cuDNN version: 11.1/7

At first, I have codes written by tensorflow v1 that can't run. so I use 

```shell
tf_upgrade_v2 --infile tensorflow_backend.py --outfile tensorflow_backend.py
```
to  upgrade the keras .py file in xx/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/backend/

it works after upgrade, however, later I found it goes wrong when load LSTM model(.h5)

the LSTM model can be acessed [here](https://github.com/SingleBone/origin_models/blob/main/lstm0-sinewave_origin.h5)

**the current behavior**
when load a LSTM model with **keras.models.load_model**

```python
import keras
model = keras.models.load_model('lstm0-sinewave_origin.h5')
```

, got RuntimeError
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/engine/saving.py", line 584, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/engine/saving.py", line 274, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/engine/saving.py", line 627, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/layers/__init__.py", line 168, in deserialize
    printable_module_name='layer')
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 147, in deserialize_keras_object
    list(custom_objects.items())))
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/engine/sequential.py", line 302, in from_config
    model.add(layer)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/engine/sequential.py", line 166, in add
    layer(x)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/layers/recurrent.py", line 541, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 76, in symbolic_fn_wrapper
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/engine/base_layer.py", line 463, in __call__
    self.build(unpack_singleton(input_shapes))
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/layers/recurrent.py", line 502, in build
    self.cell.build(step_input_shape)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/layers/recurrent.py", line 1942, in build
    constraint=self.bias_constraint)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/engine/base_layer.py", line 282, in add_weight
    constraint=constraint)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 621, in variable
    value, dtype=dtype, name=name, constraint=constraint)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 814, in variable
    constraint=constraint)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py", line 260, in __call__
    return cls._variable_v2_call(*args, **kwargs)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py", line 254, in _variable_v2_call
    shape=shape)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py", line 235, in <lambda>
    previous_getter = lambda **kws: default_variable_creator_v2(None, **kws)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py", line 2645, in default_variable_creator_v2
    shape=shape)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py", line 262, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py", line 1411, in __init__
    distribute_strategy=distribute_strategy)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py", line 1543, in _init_from_args
    name="initial_value", dtype=dtype)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1280, in convert_to_tensor
    raise RuntimeError("Attempting to capture an EagerTensor without "
RuntimeError: Attempting to capture an EagerTensor without building a function.
```

**the expected behavior**
when use **tensorflow.keras.models.load_model**

```python
import tensorflow
model = tensorflow.keras.models.load_model('lstm0-sinewave_origin.h5')
```
, it works without error

**the whole process to triger this issue**
```bash
(tensorflow) root@53125cc00c44:/data/origin_model# python
Python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 23:10:56) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
# here is where it goes wrong
>>> import keras
>>> model = keras.models.load_model('lstm0-sinewave_origin.h5')
WARNING:tensorflow:From /root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1635: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
2021-01-14 07:36:41.711121: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2021-01-14 07:36:41.728295: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:02:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.582GHz coreCount: 28 deviceMemorySize: 10.92GiB deviceMemoryBandwidth: 451.17GiB/s
2021-01-14 07:36:41.729095: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 1 with properties: 
pciBusID: 0000:84:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.582GHz coreCount: 28 deviceMemorySize: 10.92GiB deviceMemoryBandwidth: 451.17GiB/s
2021-01-14 07:36:41.729486: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2021-01-14 07:36:41.732935: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2021-01-14 07:36:41.735810: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2021-01-14 07:36:41.736327: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2021-01-14 07:36:41.739862: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2021-01-14 07:36:41.741934: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2021-01-14 07:36:41.749515: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2021-01-14 07:36:41.753192: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0, 1
2021-01-14 07:36:41.753681: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-01-14 07:36:41.772855: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2197465000 Hz
2021-01-14 07:36:41.776310: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55b853a3c2f0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-01-14 07:36:41.776354: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-01-14 07:36:42.013802: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55b853aa2730 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-01-14 07:36:42.013851: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 1080 Ti, Compute Capability 6.1
2021-01-14 07:36:42.013862: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (1): GeForce GTX 1080 Ti, Compute Capability 6.1
2021-01-14 07:36:42.015095: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:02:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.582GHz coreCount: 28 deviceMemorySize: 10.92GiB deviceMemoryBandwidth: 451.17GiB/s
2021-01-14 07:36:42.015643: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 1 with properties: 
pciBusID: 0000:84:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.582GHz coreCount: 28 deviceMemorySize: 10.92GiB deviceMemoryBandwidth: 451.17GiB/s
2021-01-14 07:36:42.015709: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2021-01-14 07:36:42.015745: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2021-01-14 07:36:42.015784: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2021-01-14 07:36:42.015809: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2021-01-14 07:36:42.015829: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2021-01-14 07:36:42.015849: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2021-01-14 07:36:42.015883: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2021-01-14 07:36:42.018395: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0, 1
2021-01-14 07:36:42.018444: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2021-01-14 07:36:42.020294: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-01-14 07:36:42.020317: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0 1 
2021-01-14 07:36:42.020328: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N N 
2021-01-14 07:36:42.020337: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 1:   N N 
2021-01-14 07:36:42.022501: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10171 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1)
2021-01-14 07:36:42.023440: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 2116 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:84:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/engine/saving.py", line 584, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/engine/saving.py", line 274, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/engine/saving.py", line 627, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/layers/__init__.py", line 168, in deserialize
    printable_module_name='layer')
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 147, in deserialize_keras_object
    list(custom_objects.items())))
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/engine/sequential.py", line 302, in from_config
    model.add(layer)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/engine/sequential.py", line 166, in add
    layer(x)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/layers/recurrent.py", line 541, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 76, in symbolic_fn_wrapper
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/engine/base_layer.py", line 463, in __call__
    self.build(unpack_singleton(input_shapes))
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/layers/recurrent.py", line 502, in build
    self.cell.build(step_input_shape)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/layers/recurrent.py", line 1942, in build
    constraint=self.bias_constraint)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/engine/base_layer.py", line 282, in add_weight
    constraint=constraint)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 621, in variable
    value, dtype=dtype, name=name, constraint=constraint)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 814, in variable
    constraint=constraint)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py", line 260, in __call__
    return cls._variable_v2_call(*args, **kwargs)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py", line 254, in _variable_v2_call
    shape=shape)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py", line 235, in <lambda>
    previous_getter = lambda **kws: default_variable_creator_v2(None, **kws)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py", line 2645, in default_variable_creator_v2
    shape=shape)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py", line 262, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py", line 1411, in __init__
    distribute_strategy=distribute_strategy)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py", line 1543, in _init_from_args
    name="initial_value", dtype=dtype)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1280, in convert_to_tensor
    raise RuntimeError("Attempting to capture an EagerTensor without "
RuntimeError: Attempting to capture an EagerTensor without building a function.
# tensorflow.keras.models.load_model 
>>> import tensorflow
>>> model = tensorflow.keras.models.load_model('lstm0-sinewave_origin.h5')
2021-01-14 07:39:55.578518: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:02:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.582GHz coreCount: 28 deviceMemorySize: 10.92GiB deviceMemoryBandwidth: 451.17GiB/s
2021-01-14 07:39:55.579080: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 1 with properties: 
pciBusID: 0000:84:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.582GHz coreCount: 28 deviceMemorySize: 10.92GiB deviceMemoryBandwidth: 451.17GiB/s
2021-01-14 07:39:55.579141: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2021-01-14 07:39:55.579165: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2021-01-14 07:39:55.579186: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2021-01-14 07:39:55.579207: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2021-01-14 07:39:55.579224: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2021-01-14 07:39:55.579241: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2021-01-14 07:39:55.579259: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2021-01-14 07:39:55.581588: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0, 1
2021-01-14 07:39:55.581630: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-01-14 07:39:55.581644: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0 1 
2021-01-14 07:39:55.581652: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N N 
2021-01-14 07:39:55.581659: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 1:   N N 
2021-01-14 07:39:55.583609: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10171 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1)
2021-01-14 07:39:55.584122: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 2116 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:84:00.0, compute capability: 6.1)
WARNING:tensorflow:No training configuration found in save file: the model was *not* compiled. Compile it manually.
>>> import tensorflow
>>> model = tensorflow.keras.models.load_model('lstm0-sinewave_origin.h5')
WARNING:tensorflow:No training configuration found in save file: the model was *not* compiled. Compile it manually.
```

**Comment by jvishnuvardhan** [comment]
@SingleBone I ran your code with your model without any issue. May be the older tensorflow version you are using might have some bug. Can you please try with recent TF versions and let us know whether the issue persists with recent TF version. Thanks!

[Here](https://colab.research.google.com/gist/jvishnuvardhan/1a5d43f2a946f6cb5512f8e05cd50612/untitled72.ipynb) is the gist with `keras.load_model`.

[Here](https://colab.research.google.com/gist/jvishnuvardhan/447737fc5c57186cd46eef4296223c7f/untitled71.ipynb) is the gist with `tensorflow.keras.load_model`. 

Please close the issue if this was resolved for you. Thanks!
