### ISSUE TITLE
Very slow tf.TensorArray and a possible bug when used with range()

### ISSUE THREAD

**Issue by ghost** [tensorflow/tensorflow#46518]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code : Yes
- OS Platform and Distribution: macOS Big Sur and Ubuntu 18 (Google colab)
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.4
- Python version: 3.8.7 on macOS and 3.6 on google colab

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

I created a few functions to benchmark `tf.TensorArray.write()` operations with python lists and it takes ages in comparison when writing 1000+ numbers. Here's a colab [notebook](https://colab.research.google.com/drive/1CySveLoSpbXB5uNWVcCB7ITlTN9dlYDA?usp=sharing) and the results are shown below:

    from time import perf_counter
    import tensorflow as tf
    
    
    def list_appends(n):
        l = []
        for i in range(n):
            l.append(i)
    
    def list_to_tensor(n):
        l = []
        for i in range(n):
            l.append(i)
        l = tf.convert_to_tensor(l)
        return 
    
    
    def t_array(n):
        t = tf.TensorArray(dtype=tf.int32, size=0, dynamic_size=True)
        for i in range(n):
            t = t.write(i, i)
        t = t.stack()
        return 
    
    
    @tf.function
    def t_array_tff(n):
        t = tf.TensorArray(dtype=tf.int32, size=0, dynamic_size=True)
        for i in range(n):
            t = t.write(i, i)
        t = t.stack()
        return 
    
    
    @tf.function
    def t_array_tff_tfr(n):
        t = tf.TensorArray(dtype=tf.int32, size=0, dynamic_size=True)
        for i in tf.range(n):
            t = t.write(i, i)
        t = t.stack()
        return 

**Tests:**

    n = 100000

    %timeit list_appends(n)

100 loops, best of 3: 9.09 ms per loop

    %timeit list_to_tensor(n)  # Same function + converts the resulting list to tf.Tensor

The slowest run took 4.30 times longer than the fastest. This could mean that an intermediate result is being cached.
10 loops, best of 3: 36 ms per loop

    %timeit t_array(n)  #  TensorArray

1 loop, best of 3: 3.25 s per loop

    %timeit t_array_tff_tfr(n)  # TensorArray + tf.function + tf.range()

1 loop, best of 3: 1.53 s per loop

The following gets stuck until I kill the code, throws a lot of errors and I'm not sure whether this is a normal behavior.

    %timeit t_array_tff(n)  # TensorArray + tf.function + range()

Error:

    ERROR:root:Internal Python error in the inspect module.
    Below is the traceback from this internal error.
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
        exec(code_obj, self.user_global_ns, self.user_ns)
      File "<ipython-input-8-2ea8237511a6>", line 1, in <module>
        get_ipython().magic('timeit t_array_tff(n)  # TensorArray + tf.function + range()')
      File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2160, in magic
        return self.run_line_magic(magic_name, magic_arg_s)
      File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2081, in run_line_magic
        result = fn(*args,**kwargs)
      File "<decorator-gen-59>", line 2, in timeit
      File "/usr/local/lib/python3.6/dist-packages/IPython/core/magic.py", line 188, in <lambda>
        call = lambda f, *a, **k: f(*a, **k)
      File "/usr/local/lib/python3.6/dist-packages/IPython/core/magics/execution.py", line 1057, in timeit
        time_number = timer.timeit(number)
      File "/usr/local/lib/python3.6/dist-packages/IPython/core/magics/execution.py", line 139, in timeit
        timing = self.inner(it, self.timer)
      File "<magic-timeit>", line 1, in inner
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
        result = self._call(*args, **kwds)
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 871, in _call
        self._initialize(args, kwds, add_initializers_to=initializers)
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 726, in _initialize
        *args, **kwds))
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 2969, in _get_concrete_function_internal_garbage_collected
        graph_function, _ = self._maybe_define_function(args, kwargs)
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function
        graph_function = self._create_graph_function(args, kwargs)
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 3206, in _create_graph_function
        capture_by_value=self._capture_by_value),
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
        func_outputs = python_func(*func_args, **func_kwargs)
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 634, in wrapped_fn
        out = weak_wrapped_fn().__wrapped__(*args, **kwds)
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py", line 973, in wrapper
        user_requested=True,
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 459, in converted_call
        result = converted_f(*effective_args, **kwargs)
      File "/tmp/tmp1hatjldp.py", line 24, in tf__t_array_tff
        ag__.for_stmt(ag__.converted_call(ag__.ld(range), (ag__.ld(n),), None, fscope), None, loop_body, get_state, set_state, ('t',), {'iterate_names': 'i'})
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/operators/control_flow.py", line 444, in for_stmt
        _py_for_stmt(iter_, extra_test, body, None, None)
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/operators/control_flow.py", line 473, in _py_for_stmt
        body(target)
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/operators/control_flow.py", line 459, in protected_body
        original_body(protected_iter)
      File "/tmp/tmp1hatjldp.py", line 22, in loop_body
        t = ag__.converted_call(ag__.ld(t).write, (ag__.ld(i), ag__.ld(i)), None, fscope)
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 350, in converted_call
        return _call_unconverted(f, args, kwargs, options, False)
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 479, in _call_unconverted
        return f(*args)
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/tf_should_use.py", line 247, in wrapped
        return _add_should_use_warning(fn(*args, **kwargs),
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/tensor_array_ops.py", line 1159, in write
        return self._implementation.write(index, value, name=name)
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/tensor_array_ops.py", line 543, in write
        name=name)
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/list_ops.py", line 202, in tensor_list_set_item
        index >= input_list_size,
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 4937, in less_equal
        "LessEqual", x=x, y=y, name=name)
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 522, in _apply_op_helper
        preferred_dtype=default_dtype)
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/profiler/trace.py", line 163, in wrapped
        return func(*args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1540, in convert_to_tensor
        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_conversion_registry.py", line 52, in _default_conversion_function
        return constant_op.constant(value, dtype, name=name)
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py", line 265, in constant
        allow_broadcast=True)
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py", line 287, in _constant_impl
        "Const", [], [dtype_value.type], attrs=attrs, name=name).outputs[0]
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py", line 592, in _create_op_internal
        compute_device)
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3536, in _create_op_internal
        op_def=op_def)
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 2027, in __init__
        output_type = pywrap_tf_session.TF_OperationOutputType(tf_output)
    KeyboardInterrupt
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 1823, in showtraceback
        stb = value._render_traceback_()
    AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/IPython/core/ultratb.py", line 1132, in get_records
        return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
      File "/usr/local/lib/python3.6/dist-packages/IPython/core/ultratb.py", line 313, in wrapped
        return f(*args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/IPython/core/ultratb.py", line 358, in _fixed_getinnerframes
        records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
      File "/usr/lib/python3.6/inspect.py", line 1490, in getinnerframes
        frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
      File "/usr/lib/python3.6/inspect.py", line 1452, in getframeinfo
        lines, lnum = findsource(frame)
      File "/usr/local/lib/python3.6/dist-packages/IPython/core/ultratb.py", line 170, in findsource
        file = getsourcefile(object) or getfile(object)
      File "/usr/lib/python3.6/inspect.py", line 696, in getsourcefile
        if getattr(getmodule(object, filename), '__loader__', None) is not None:
      File "/usr/lib/python3.6/inspect.py", line 732, in getmodule
        for modname, module in list(sys.modules.items()):
    KeyboardInterrupt
    ---------------------

**Describe the expected behavior**

is this normal behavior? I was expecting better performance specially when used with `tf.function` but it's either not a proper use case or an issue.

**Standalone code to reproduce the issue**
Included in the demonstration above.

Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
I ran the code shared and face memory related issues, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/75fdc0dad0344355c9b02a21b6263f07/untitled503.ipynb)

**Comment by emadboctorx** [comment]
@Saduf2019 3.27s per loop, are you sure this is a memory issue?

**Comment by mdanatg** [comment]
`t_array_tff` is definitely not recommended. Within `tf.function`, you almost always want to use `tf.range`. The `range` version is there just for compatibility reasons. For more detail, `t_array_tff` is equivalent to a function where you write `t = t.write(i, i)` 100000 times, which takes a very long time to compile.

Another caveat: `tf.function` is compiled just-in-time, when it's first called. That means that the first call will be much slower. So when benchmarking, it's usualy a good idea to do a warm-up run to get rid of the one-time compilation costs. It's also a good idea to pass `tf.constant` arguments, otherwise the function might recompile. Something like this should do:

```
t_array_tff_tfr(tf.constant(1))  # Dry run, to compile the function
%timeit t_array_tff_tfr(tf.constant(n))
```

It also means that if you have a `tf.function` that you only ever call once, it will probably not give you good performance.

The lower performance of `t_array` and `t_array_tff_tfr` is expected (but there are some good news, read on). In general, TF ops (like `tf.TensorArray` and `for ... in tf.range`) have relatively large overhead making them inefficient at working with small Tensors. This is being actively looked at, and different runtimes are expected to have much improved performance. But in the meantime, you'll need to be mindful when writing code that performs a lot of steps with small tensors.

It's also expected that `t_array_tff_tfr` is about 3x faster than `t_array` - usually `tf.function` gives better performance over Eager.

Now, there is a way to get a very efficient `tf.function` by setting the flag `experimental_compile=True` (in tf-nightly, that flag is `jit_compile=True`). That enables XLA compilation, which gives you better-than-Python performance (~10x in my tests). The caveat is that it doesn't always work with dynamic sizes, so for instance in our case it means you have to pre-allocate the TensorArray:

```
@tf.function(experimental_compile=True)
def t_array_tff_tfr_comp(n):
    t = tf.TensorArray(dtype=tf.int32, size=n, dynamic_size=False)
    for i in tf.range(n):
        t = t.write(i, i)
    return t.stack()
```

**Comment by emadboctorx** [comment]
@mdanatg Thanks, that's very informative. I initially did this test because I have several methods that are called within another method decorated by tf.function. There are 3 loops that use python `range()` as well as 5 lists that are being populated inside the loop and I'm considering whether the transition is likely to improve performance vs introduce more bottlenecks. Here are the 3 methods in question:


    def calculate_returns(self, masks, rewards, values, log_probs, entropies):
        states = tf.numpy_function(func=self.get_states, inp=[], Tout=tf.float32)
        for step in range(self.transition_steps):
            actions, step_log_probs, step_entropies, step_values = self.model(states)
            states, step_rewards, step_dones = tf.numpy_function(
                self.step_envs,
                [actions],
                (tf.float32, tf.float32, tf.float32),
            )
            step_masks = 1 - step_dones
            log_probs.append(step_log_probs)
            values.append(step_values)
            rewards.append(step_rewards)
            masks.append(step_masks)
            entropies.append(step_entropies)
        next_values = self.model(states)[-1]
        returns = [next_values]
        for step in reversed(range(self.transition_steps)):
            returns.insert(0, rewards[step] + masks[step] * self.gamma * returns[0])
        return returns

    def calculate_loss(self, returns, values, log_probs, entropies):
        value_loss = 0.0
        action_loss = 0.0
        entropy_loss = 0.0
        for step in range(self.transition_steps):
            advantages = tf.stop_gradient(returns[step]) - values[step]
            value_loss += tf.reduce_mean(tf.square(advantages))
            action_loss += -tf.reduce_mean(
                tf.stop_gradient(advantages) * log_probs[step]
            )
            entropy_loss += tf.reduce_mean(entropies[step])
        value_loss /= self.transition_steps
        action_loss /= self.transition_steps
        entropy_loss /= self.transition_steps
        return (
            self.value_loss_coef * value_loss
            + action_loss
            - entropy_loss * self.entropy_coef
        )

    @tf.function
    def train_step(self, clip_norm=0.5):
        """
        Do 1 training step.
        Args:
            clip_norm: Gradient clipping value passed to tf.clip_by_global_norm()

        Returns:
            None
        """
        masks = []
        rewards = []
        values = []
        log_probs = []
        entropies = []
        with tf.GradientTape() as tape:
            returns = self.calculate_returns(
                masks, rewards, values, log_probs, entropies
            )
            loss = self.calculate_loss(returns, values, log_probs, entropies)
        gradients = tape.gradient(loss, self.model.trainable_variables)
        gradients, _ = tf.clip_by_global_norm(gradients, clip_norm)
        self.model.optimizer.apply_gradients(
            zip(gradients, self.model.trainable_variables)
        )

**Comment by mdanatg** [comment]
I see, that makes sense. In this case, because you're already inside a tf.function (it applies recursively), switching these lists and loops to their TF counterparts should add more overhead, although I'd expect it to be small compared to the bulk of the function (that is `self.model` and gradient calculations). So the difference is more like:

```
@tf.function
def list_appends_tff(n):
    l = []
    for i in range(n):
        l.append(i)
    return tf.stack(l)

@tf.function
def t_array_tff_tfr(n):
    t = tf.TensorArray(dtype=tf.int32, size=0, dynamic_size=True)
    for i in tf.range(n):
        t = t.write(i, i)
    return t.stack()
```

The former is really equivalent to writing (because all Python code runs at compilation, and is used to generate the graph):

```
@tf.function
def list_appends_tff(n):
    t1 = 0  # from l.append(0)
    t2 = 1
    ...
    tn = n
    return tf.stack([t1, t2, ..., tn])
```

So you see it has lots more code, but no loops or lists so it should be fastest to run (but will compile slower).

The most important factor you need to consider is whether the lists and loops are static, that is, whether they have the same length and number of steps every time. At a glance, that amounts to the question: "is self.transition_steps constant?". If the answer is yes, then I'd move to the second question. If the answer is no, then you will need TensorArray and tf.range for things to work correctly (and there are a few other caveats to watch out for in that case).

If `self.transition_steps` is constant, then the next question is how large is it. If it's small, say ~10, then list/range should be fine, your graph will be larger, but not by a whole lot. If `transition_steps` is larger, then you might end up with a graph that's much larger than it could be, and switching to `tf.range` ought to give you improved startup times (although each step is potentially slower).

Note that if you switch to TensorArray, you'll also need to refactor `calculate_returns` a bit, because you'll have to write e.g. `log_probs = log_probs.write(step, step_log_probs)` instead of just `log_probs.append(step_log_probs)`. I think I'd try gradual changes: start with changing just one of the lists to see if that changes performance in any way, and take it from there.

**Comment by tilakrayal** [comment]
@ghost,
Could you please take a look at this [comment](https://github.com/tensorflow/tensorflow/issues/46518#issuecomment-767746510) from the developer and update to the latest tensorflow v2.9 and let us know if the issue still persists. Thank you!
