### ISSUE TITLE
AssertionError: Nesting violated for default stack of <class 'tensorflow.python.framework.ops.Graph'> objects

### ISSUE THREAD

**Issue by gongel** [tensorflow/tensorflow#46535]
I want to make a prediction(do beam search) after every save of ckpt using Estimator for saving best ckpt. So I add a saving_listeners(CheckpointSaverListener) to estimator.train. But every time I raise a mistake. 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macos
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.15
- Python version: 3.6

Here is my CheckpointSaverListener code.
```
class SaveBestCheckpointSaverListener(tf.train.CheckpointSaverListener):
    def __init__(self, save_checkpoints_steps, keep_checkpoint_max, output_dir):
        self.best_ckpt = None
        self.best_path_match = None
        self.best_global_step_value = None
        self.save_checkpoints_steps = save_checkpoints_steps
        self.keep_checkpoint_max = keep_checkpoint_max
        self.output_dir = output_dir

    def begin(self):
        # You can add ops to the graph here.
        print('Starting the session.')
        # self.your_tensor = ...

    def before_save(self, session, global_step_value):
        print('About to write a checkpoint')

    def after_save(self, session, global_step_value):
        print('Done writing checkpoint at {}.'.format(global_step_value))
        global_step_value = int(global_step_value)
        if global_step_value == 0:
            return
        current_ckpt = 'model.ckpt-{}'.format(global_step_value)
       # do beam search prediction
        current_path_match = do_predict()
        print('current result: {} : {}'.format(current_ckpt, current_path_match))
        if not self.best_ckpt:
            self.best_ckpt = current_ckpt
            self.best_path_match = current_path_match
            self.best_global_step_value = str(global_step_value)
        else:
            if current_path_match > self.best_path_match:
                self.best_ckpt = current_ckpt
                self.best_path_match = current_path_match
                self.best_global_step_value = str(global_step_value)
                print('Saved best ckpt with path_match {}'.format(current_path_match))

    def end(self, session, global_step_value):
        print('best model {}, remove useless models.'.format(self.best_ckpt))
        # for f in os.listdir(self.output_dir):
        #     file = os.path.join(self.output_dir, f)
        #     if os.path.isfile(file) and f.startswith('model'):
        #         model_global_step = f[f.index('-') + 1:f.rindex('.')]
        #         if model_global_step != self.best_global_step_value:
        #             os.remove(file)
        #             print('remove {}'.format(file))

```
After all ckpts were saved, training process will report errors. Here are errors.
```
Traceback (most recent call last):
  File "run_classifier_nsp_multitask_typeEmb.py", line 797, in <module>
    tf.app.run()
  File "/Users/bytedance/opt/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/Users/bytedance/opt/anaconda3/lib/python3.6/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/Users/bytedance/opt/anaconda3/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "run_classifier_nsp_multitask_typeEmb.py", line 767, in main
    estimator.train(input_fn=train_input_fn, max_steps=FLAGS.num_train_steps, hooks=hooks, saving_listeners=[listener])
  File "/Users/bytedance/opt/anaconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/Users/bytedance/opt/anaconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1161, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/Users/bytedance/opt/anaconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1195, in _train_model_default
    saving_listeners)
  File "/Users/bytedance/opt/anaconda3/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/Users/bytedance/opt/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 5480, in get_controller
    yield g
  File "/Users/bytedance/opt/anaconda3/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/Users/bytedance/opt/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 5295, in get_controller
    type(default))
AssertionError: Nesting violated for default stack of <class 'tensorflow.python.framework.ops.Graph'> objects
```

**Comment by Saduf2019** [comment]
@gongel 
Please upgrade to 2.x as there is no support for 1.x and let us know if you face any issues.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
