### ISSUE TITLE
set_weights() for tf.keras.layers.Layer not working for type string.

### ISSUE THREAD

**Issue by MansBermellLeo** [tensorflow/tensorflow#46553]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Cataline 10.15.7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 2.4.0
- Python version: 3.7.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): clang 11.0.3
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
When trying to `set_weights()` for a layer where the weights are strings the data type `string` is not understood. See the standalone code below.  

**Describe the expected behavior**
The weights should be updated with no error.

**Standalone code to reproduce the issue**
```
import tensorflow as tf


def initializer(shape, dtype=None):
    return tf.reshape(tf.constant([str(x) for x in range(shape[0])]), shape)


class CustomLayer(tf.keras.layers.Layer):

    def __init__(self, length=10, **kwargs):
        super(CustomLayer, self).__init__(**kwargs)
        self.length = length

    def build(self, input_shape=None):
        self.keys = self.add_weight(shape=(self.length,),
                                    name='keys',
                                    initializer=initializer,
                                    dtype=tf.string,
                                    trainable=False)

        self.built = True

    def call(self, x):
        return self.keys

    def get_config(self):
        config = super(CustomLayer, self).get_config()
        config.update({'length': self.length})
        return config


inputs = tf.keras.layers.Input(shape=())
outputs = CustomLayer(name='lookup')(inputs)
model = tf.keras.Model(inputs, outputs)
model.compile()

model.get_layer('lookup').set_weights(model.get_layer('lookup').get_weights())
```

**Other info / logs** 
```
Traceback (most recent call last):
  File "example.py", line 37, in <module>
    model.get_layer('lookup').set_weights(model.get_layer('lookup').get_weights())
  File "/Users/mans.bermell/.pyenv/versions/tensorflow2.4/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1877, in set_weights
    backend.batch_set_value(weight_value_tuples)
  File "/Users/mans.bermell/.pyenv/versions/tensorflow2.4/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/Users/mans.bermell/.pyenv/versions/tensorflow2.4/lib/python3.7/site-packages/tensorflow/python/keras/backend.py", line 3706, in batch_set_value
    x.assign(np.asarray(value, dtype=dtype(x)))
  File "/Users/mans.bermell/.pyenv/versions/tensorflow2.4/lib/python3.7/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: data type 'string' not understood
```

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.3,2.4 and Nightly version(`2.5.0-dev20210119`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/60925393fd76ea4a37ea09c4d3669c21/untitled626.ipynb).Thanks!

**Comment by bhack** [comment]
What is the scope of having trainable weights as string? Do you need non trainable variables https://www.tensorflow.org/guide/keras/custom_layers_and_models#layers_can_have_non-trainable_weights?

**Comment by MansBermellLeo** [comment]
@bhack you are right, using `tf.Variable()`works for my use case. Using version 2.2.0 (AI platform on google does not support 2.4.0 yet) and had to create a custom layer for a lookup table. However, using a Variable will work as well. As long as there is no reason to have weights as strings this issue can be closed.

**Comment by bhack** [comment]
@mihaimaruseac Can you evaluate if we could "fast fail" for trainabile weights with string dtype?

**Comment by MansBermellLeo** [comment]
> @mihaimaruseac Can you evaluate if we could "fail-fast" for trainabile weights with string dtype?

Also non-trainable weights, no?

**Comment by MansBermellLeo** [comment]
I tried using a non-trainable `tf.Variable` instead, however there are still some issues with loading the model. My understanding is the difference between how TensorFlow and Numpy treats `dtype`.

```
import tensorflow as tf

class CustomLayer(tf.keras.layers.Layer):

    def __init__(self, **kwargs):
        super(CustomLayer, self).__init__(**kwargs)

    def build(self, input_shape=None):
        self.keys = tf.Variable(['foo'],
                                shape=(1,),
                                trainable=False,
                                dtype=tf.string)
        self.built = True

    def call(self, x):
        return x

inputs = tf.keras.layers.Input(shape=())
outputs = CustomLayer(name='lookup')(inputs)
model = tf.keras.Model(inputs, outputs)
model.compile(loss='mse')

callbacks = [
    tf.keras.callbacks.EarlyStopping(monitor='loss', restore_best_weights=True)
]

model.fit([1], [1], epochs=10, callbacks=callbacks)
```

```
Epoch 1/10
1/1 [==============================] - 0s 92ms/step - loss: 0.0000e+00
Epoch 2/10
1/1 [==============================] - 0s 1ms/step - loss: 0.0000e+00
Traceback (most recent call last):
  File "temp.py", line 29, in <module>
    model.fit([1], [1], epochs=10, callbacks=callbacks)
  File "/Users/mans.bermell/.pyenv/versions/tensorflow2.4/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1145, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/Users/mans.bermell/.pyenv/versions/tensorflow2.4/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 432, in on_epoch_end
    callback.on_epoch_end(epoch, numpy_logs)
  File "/Users/mans.bermell/.pyenv/versions/tensorflow2.4/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 1778, in on_epoch_end
    self.model.set_weights(self.best_weights)
  File "/Users/mans.bermell/.pyenv/versions/tensorflow2.4/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1877, in set_weights
    backend.batch_set_value(weight_value_tuples)
  File "/Users/mans.bermell/.pyenv/versions/tensorflow2.4/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/Users/mans.bermell/.pyenv/versions/tensorflow2.4/lib/python3.7/site-packages/tensorflow/python/keras/backend.py", line 3706, in batch_set_value
    x.assign(np.asarray(value, dtype=dtype(x)))
  File "/Users/mans.bermell/.pyenv/versions/tensorflow2.4/lib/python3.7/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: data type 'string' not understood
```

**Comment by mihaimaruseac** [comment]
I think it's better to send that as a PR.

**Comment by bhack** [comment]
@MansBermellLeo You can try to make a PR with

```
dtype=dtypes_module.as_dtype(x.dtype).as_numpy_dtype)
```

**Comment by bhack** [comment]
We can close this.

**Comment by bhack** [comment]
@mihaimaruseac Is the reverting bot fixed to reopen this on revert?

**Comment by mihaimaruseac** [comment]
I don't think so. We basically need GitHub to know that reverting a commit that closes an issue reopens it.

In this case, the issue was closed manually, so for sure we'd have to do manual work in case of revert.

**Comment by bhack** [comment]
@mihaimaruseac If we cover the first case we could use a policy for the reviewer to connect the ticket before merge if the PR author didn't mentionted correctly the original ticket for Github PR-issue auto-link.
