### ISSUE TITLE
Request to add tf.Cholesky and tf.MatrixTriangularSolve to tensorflow lite operations 

### ISSUE THREAD

**Issue by AiaHaruv** [tensorflow/tensorflow#46577]
**System information**
- OS Platform and Distribution: Linux Ubuntu 18.04.5
- Python version: 3.7.4
- Tensorflow : 2.4.0

I'm trying to use the function tf.linalg.lstsq inside my module and I'm getting this error for the converter: 

**Provide the text output from tflite_convert**

    ```
    Traceback (most recent call last):
      File "/home/aia/anaconda3/envs/notebooks/lib/python3.7/site-packages/tensorflow/lite/python/convert.py", line 213, in toco_convert_protos
        enable_mlir_converter)
      File "/home/aia/anaconda3/envs/notebooks/lib/python3.7/site-packages/tensorflow/lite/python/wrap_toco.py", line 38, in wrapped_toco_convert
        enable_mlir_converter)
    Exception: <unknown>:0: error: loc(callsite(callsite(callsite("matrix_solve_ls_1/cond/Cholesky@matrix_solve_ls_1_cond_false_28664" at "matrix_solve_ls_1/cond@__inference_calcute_hbr_31510") at "PartitionedCall@__inference_signature_wrapper_31523") at "PartitionedCall")): 'tf.Cholesky' op is neither a custom op nor a flex op
    <unknown>:0: note: loc("PartitionedCall"): called from
    <unknown>:0: error: loc(callsite(callsite(callsite("matrix_solve_ls_1/cond/cholesky_solve/MatrixTriangularSolve@matrix_solve_ls_1_cond_false_28664" at "matrix_solve_ls_1/cond@__inference_calcute_hbr_31510") at "PartitionedCall@__inference_signature_wrapper_31523") at "PartitionedCall")): 'tf.MatrixTriangularSolve' op is neither a custom op nor a flex op
    <unknown>:0: note: loc("PartitionedCall"): called from
    <unknown>:0: error: loc(callsite(callsite(callsite("matrix_solve_ls_1/cond/cholesky_solve/MatrixTriangularSolve_1@matrix_solve_ls_1_cond_false_28664" at "matrix_solve_ls_1/cond@__inference_calcute_hbr_31510") at "PartitionedCall@__inference_signature_wrapper_31523") at "PartitionedCall")): 'tf.MatrixTriangularSolve' op is neither a custom op nor a flex op
    <unknown>:0: note: loc("PartitionedCall"): called from
    <unknown>:0: error: loc(callsite(callsite(callsite("matrix_solve_ls_1/cond/Cholesky@matrix_solve_ls_1_cond_true_28663" at "matrix_solve_ls_1/cond@__inference_calcute_hbr_31510") at "PartitionedCall@__inference_signature_wrapper_31523") at "PartitionedCall")): 'tf.Cholesky' op is neither a custom op nor a flex op
    <unknown>:0: note: loc("PartitionedCall"): called from
    <unknown>:0: error: loc(callsite(callsite(callsite("matrix_solve_ls_1/cond/cholesky_solve/MatrixTriangularSolve@matrix_solve_ls_1_cond_true_28663" at "matrix_solve_ls_1/cond@__inference_calcute_hbr_31510") at "PartitionedCall@__inference_signature_wrapper_31523") at "PartitionedCall")): 'tf.MatrixTriangularSolve' op is neither a custom op nor a flex op
    <unknown>:0: note: loc("PartitionedCall"): called from
    <unknown>:0: error: loc(callsite(callsite(callsite("matrix_solve_ls_1/cond/cholesky_solve/MatrixTriangularSolve_1@matrix_solve_ls_1_cond_true_28663" at "matrix_solve_ls_1/cond@__inference_calcute_hbr_31510") at "PartitionedCall@__inference_signature_wrapper_31523") at "PartitionedCall")): 'tf.MatrixTriangularSolve' op is neither a custom op nor a flex op
    <unknown>:0: note: loc("PartitionedCall"): called from
    <unknown>:0: error: loc(callsite(callsite(callsite("matrix_solve_ls/cond/Cholesky@matrix_solve_ls_cond_false_25991" at "matrix_solve_ls/cond@__inference_calcute_hbr_31510") at "PartitionedCall@__inference_signature_wrapper_31523") at "PartitionedCall")): 'tf.Cholesky' op is neither a custom op nor a flex op
    <unknown>:0: note: loc("PartitionedCall"): called from
    <unknown>:0: error: loc(callsite(callsite(callsite("matrix_solve_ls/cond/cholesky_solve/MatrixTriangularSolve@matrix_solve_ls_cond_false_25991" at "matrix_solve_ls/cond@__inference_calcute_hbr_31510") at "PartitionedCall@__inference_signature_wrapper_31523") at "PartitionedCall")): 'tf.MatrixTriangularSolve' op is neither a custom op nor a flex op
    <unknown>:0: note: loc("PartitionedCall"): called from
    <unknown>:0: error: loc(callsite(callsite(callsite("matrix_solve_ls/cond/cholesky_solve/MatrixTriangularSolve_1@matrix_solve_ls_cond_false_25991" at "matrix_solve_ls/cond@__inference_calcute_hbr_31510") at "PartitionedCall@__inference_signature_wrapper_31523") at "PartitionedCall")): 'tf.MatrixTriangularSolve' op is neither a custom op nor a flex op
    <unknown>:0: note: loc("PartitionedCall"): called from
    <unknown>:0: error: loc(callsite(callsite(callsite("matrix_solve_ls/cond/Cholesky@matrix_solve_ls_cond_true_25990" at "matrix_solve_ls/cond@__inference_calcute_hbr_31510") at "PartitionedCall@__inference_signature_wrapper_31523") at "PartitionedCall")): 'tf.Cholesky' op is neither a custom op nor a flex op
    <unknown>:0: note: loc("PartitionedCall"): called from
    <unknown>:0: error: loc(callsite(callsite(callsite("matrix_solve_ls/cond/cholesky_solve/MatrixTriangularSolve@matrix_solve_ls_cond_true_25990" at "matrix_solve_ls/cond@__inference_calcute_hbr_31510") at "PartitionedCall@__inference_signature_wrapper_31523") at "PartitionedCall")): 'tf.MatrixTriangularSolve' op is neither a custom op nor a flex op
    <unknown>:0: note: loc("PartitionedCall"): called from
    <unknown>:0: error: loc(callsite(callsite(callsite("matrix_solve_ls/cond/cholesky_solve/MatrixTriangularSolve_1@matrix_solve_ls_cond_true_25990" at "matrix_solve_ls/cond@__inference_calcute_hbr_31510") at "PartitionedCall@__inference_signature_wrapper_31523") at "PartitionedCall")): 'tf.MatrixTriangularSolve' op is neither a custom op nor a flex op
    <unknown>:0: note: loc("PartitionedCall"): called from
    <unknown>:0: error: loc(callsite(callsite("matrix_solve_ls_1/cond@__inference_calcute_hbr_31510" at "PartitionedCall@__inference_signature_wrapper_31523") at "PartitionedCall")): failed while converting: 'tf.IfRegion306_else': Ops that need custom implementation (enabled via setting the -emit-custom-ops flag):
	    tf.Cholesky {device = ""}
	    tf.MatrixTriangularSolve {adjoint = false, device = "", lower = true}
	    tf.MatrixTriangularSolve {adjoint = true, device = "", lower = true}
    <unknown>:0: note: loc("PartitionedCall"): called from
    
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/aia/repos/algo-pipeline/TF_HBR.py", line 144, in <module>
        tflite_model = converter.convert()
      File "/home/aia/anaconda3/envs/notebooks/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 739, in convert
        result = _convert_saved_model(**converter_kwargs)
      File "/home/aia/anaconda3/envs/notebooks/lib/python3.7/site-packages/tensorflow/lite/python/convert.py", line 637, in convert_saved_model
        enable_mlir_converter=True)
      File "/home/aia/anaconda3/envs/notebooks/lib/python3.7/site-packages/tensorflow/lite/python/convert.py", line 216, in toco_convert_protos
        raise ConverterError(str(e))
    tensorflow.lite.python.convert.ConverterError: <unknown>:0: error: loc(callsite(callsite(callsite("matrix_solve_ls_1/cond/Cholesky@matrix_solve_ls_1_cond_false_28664" at "matrix_solve_ls_1/cond@__inference_calcute_hbr_31510") at "PartitionedCall@__inference_signature_wrapper_31523") at "PartitionedCall")): 'tf.Cholesky' op is neither a custom op nor a flex op
    <unknown>:0: note: loc("PartitionedCall"): called from
    <unknown>:0: error: loc(callsite(callsite(callsite("matrix_solve_ls_1/cond/cholesky_solve/MatrixTriangularSolve@matrix_solve_ls_1_cond_false_28664" at "matrix_solve_ls_1/cond@__inference_calcute_hbr_31510") at "PartitionedCall@__inference_signature_wrapper_31523") at "PartitionedCall")): 'tf.MatrixTriangularSolve' op is neither a custom op nor a flex op
    <unknown>:0: note: loc("PartitionedCall"): called from
    <unknown>:0: error: loc(callsite(callsite(callsite("matrix_solve_ls_1/cond/cholesky_solve/MatrixTriangularSolve_1@matrix_solve_ls_1_cond_false_28664" at "matrix_solve_ls_1/cond@__inference_calcute_hbr_31510") at "PartitionedCall@__inference_signature_wrapper_31523") at "PartitionedCall")): 'tf.MatrixTriangularSolve' op is neither a custom op nor a flex op
    <unknown>:0: note: loc("PartitionedCall"): called from
    <unknown>:0: error: loc(callsite(callsite(callsite("matrix_solve_ls_1/cond/Cholesky@matrix_solve_ls_1_cond_true_28663" at "matrix_solve_ls_1/cond@__inference_calcute_hbr_31510") at "PartitionedCall@__inference_signature_wrapper_31523") at "PartitionedCall")): 'tf.Cholesky' op is neither a custom op nor a flex op
    <unknown>:0: note: loc("PartitionedCall"): called from
    <unknown>:0: error: loc(callsite(callsite(callsite("matrix_solve_ls_1/cond/cholesky_solve/MatrixTriangularSolve@matrix_solve_ls_1_cond_true_28663" at "matrix_solve_ls_1/cond@__inference_calcute_hbr_31510") at "PartitionedCall@__inference_signature_wrapper_31523") at "PartitionedCall")): 'tf.MatrixTriangularSolve' op is neither a custom op nor a flex op
    <unknown>:0: note: loc("PartitionedCall"): called from
    <unknown>:0: error: loc(callsite(callsite(callsite("matrix_solve_ls_1/cond/cholesky_solve/MatrixTriangularSolve_1@matrix_solve_ls_1_cond_true_28663" at "matrix_solve_ls_1/cond@__inference_calcute_hbr_31510") at "PartitionedCall@__inference_signature_wrapper_31523") at "PartitionedCall")): 'tf.MatrixTriangularSolve' op is neither a custom op nor a flex op
    <unknown>:0: note: loc("PartitionedCall"): called from
    <unknown>:0: error: loc(callsite(callsite(callsite("matrix_solve_ls/cond/Cholesky@matrix_solve_ls_cond_false_25991" at "matrix_solve_ls/cond@__inference_calcute_hbr_31510") at "PartitionedCall@__inference_signature_wrapper_31523") at "PartitionedCall")): 'tf.Cholesky' op is neither a custom op nor a flex op
    <unknown>:0: note: loc("PartitionedCall"): called from
    <unknown>:0: error: loc(callsite(callsite(callsite("matrix_solve_ls/cond/cholesky_solve/MatrixTriangularSolve@matrix_solve_ls_cond_false_25991" at "matrix_solve_ls/cond@__inference_calcute_hbr_31510") at "PartitionedCall@__inference_signature_wrapper_31523") at "PartitionedCall")): 'tf.MatrixTriangularSolve' op is neither a custom op nor a flex op
    <unknown>:0: note: loc("PartitionedCall"): called from
    <unknown>:0: error: loc(callsite(callsite(callsite("matrix_solve_ls/cond/cholesky_solve/MatrixTriangularSolve_1@matrix_solve_ls_cond_false_25991" at "matrix_solve_ls/cond@__inference_calcute_hbr_31510") at "PartitionedCall@__inference_signature_wrapper_31523") at "PartitionedCall")): 'tf.MatrixTriangularSolve' op is neither a custom op nor a flex op
    <unknown>:0: note: loc("PartitionedCall"): called from
    <unknown>:0: error: loc(callsite(callsite(callsite("matrix_solve_ls/cond/Cholesky@matrix_solve_ls_cond_true_25990" at "matrix_solve_ls/cond@__inference_calcute_hbr_31510") at "PartitionedCall@__inference_signature_wrapper_31523") at "PartitionedCall")): 'tf.Cholesky' op is neither a custom op nor a flex op
    <unknown>:0: note: loc("PartitionedCall"): called from
    <unknown>:0: error: loc(callsite(callsite(callsite("matrix_solve_ls/cond/cholesky_solve/MatrixTriangularSolve@matrix_solve_ls_cond_true_25990" at "matrix_solve_ls/cond@__inference_calcute_hbr_31510") at "PartitionedCall@__inference_signature_wrapper_31523") at "PartitionedCall")): 'tf.MatrixTriangularSolve' op is neither a custom op nor a flex op
    <unknown>:0: note: loc("PartitionedCall"): called from
    <unknown>:0: error: loc(callsite(callsite(callsite("matrix_solve_ls/cond/cholesky_solve/MatrixTriangularSolve_1@matrix_solve_ls_cond_true_25990" at "matrix_solve_ls/cond@__inference_calcute_hbr_31510") at "PartitionedCall@__inference_signature_wrapper_31523") at "PartitionedCall")): 'tf.MatrixTriangularSolve' op is neither a custom op nor a flex op
    <unknown>:0: note: loc("PartitionedCall"): called from
    <unknown>:0: error: loc(callsite(callsite("matrix_solve_ls_1/cond@__inference_calcute_hbr_31510" at "PartitionedCall@__inference_signature_wrapper_31523") at "PartitionedCall")): failed while converting: 'tf.IfRegion306_else': Ops that need custom implementation (enabled via setting the -emit-custom-ops flag):
	    tf.Cholesky {device = ""}
	    tf.MatrixTriangularSolve {adjoint = false, device = "", lower = true}
	    tf.MatrixTriangularSolve {adjoint = true, device = "", lower = true}
    <unknown>:0: note: loc("PartitionedCall"): called from```

**Standalone code to reproduce the issue** 

https://colab.research.google.com/gist/AiaHaruv/396c2473b4601e9d35332884dbd02fa9/tflie_gist.ipynb

**Any other info / logs**
In the colab, the traceback is: 
          4 frames
          Exception: <unknown>:0: error: 
  loc(callsite(callsite("matrix_solve_ls/cholesky_solve/MatrixTriangularSolve@__inference_calculate_403" at 
  "PartitionedCall@__inference_signature_wrapper_411") at "PartitionedCall")): 'tf.MatrixTriangularSolve' op is neither a custom 
  op nor a flex op
          <unknown>:0: note: loc("PartitionedCall"): called from
          <unknown>:0: error: 
  loc(callsite(callsite("matrix_solve_ls/cholesky_solve/MatrixTriangularSolve_1@__inference_calculate_403" at 
  "PartitionedCall@__inference_signature_wrapper_411") at "PartitionedCall")): 'tf.MatrixTriangularSolve' op is neither a custom 
  op nor a flex op
          <unknown>:0: note: loc("PartitionedCall"): called from
          <unknown>:0: error: failed while converting: 'main': Ops that need custom implementation (enabled via setting the -emit- 
  custom-ops flag):
	          tf.MatrixTriangularSolve {adjoint = false, device = "", lower = true}
	          tf.MatrixTriangularSolve {adjoint = true, device = "", lower = true}
          
        
    During handling of the above exception, another exception occurred:
    
    ConverterError                            Traceback (most recent call last)
    /usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
        214       return model_str
        215     except Exception as e:
    --> 216       raise ConverterError(str(e))
        217 
        218   if distutils.spawn.find_executable(_toco_from_proto_bin) is None:
    
    ConverterError: <unknown>:0: error: loc(callsite(callsite("matrix_solve_ls/cholesky_solve/MatrixTriangularSolve@__inference_calculate_403" at "PartitionedCall@__inference_signature_wrapper_411") at "PartitionedCall")): 'tf.MatrixTriangularSolve' op is neither a custom op nor a flex op
    <unknown>:0: note: loc("PartitionedCall"): called from
    <unknown>:0: error: loc(callsite(callsite("matrix_solve_ls/cholesky_solve/MatrixTriangularSolve_1@__inference_calculate_403" at "PartitionedCall@__inference_signature_wrapper_411") at "PartitionedCall")): 'tf.MatrixTriangularSolve' op is neither a custom op nor a flex op
    <unknown>:0: note: loc("PartitionedCall"): called from
    <unknown>:0: error: failed while converting: 'main': Ops that need custom implementation (enabled via setting the -emit-custom-ops flag):
	    tf.MatrixTriangularSolve {adjoint = false, device = "", lower = true}
	    tf.MatrixTriangularSolve {adjoint = true, device = "", lower = true}

Thanks you

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/f5edf08a8b21c7137bfffa5b5adf1349/46577-2-3.ipynb) , [TF v2.4](https://colab.research.google.com/gist/amahendrakar/d2646e8c29a2c10a357d7cd313848bfa/46577.ipynb#scrollTo=dV8_F-td9OZP) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/2755c27d44a9f27746f351750b270a33/46577-tf-nightly.ipynb). Please check the linked gist for reference. Thanks!

**Comment by abattery** [comment]
First, we will support them via Select TF option. https://www.tensorflow.org/lite/guide/ops_select Will add those ops to the Select TF option.

**Comment by abattery** [comment]
Please use the tomorrow's tf-nightly version and convert your model with the Select TF option.

**Comment by AiaHaruv** [comment]
Thanks you, I installed the latest nightly version and indeed the conversion with these operations now work.
However, I have a new issue with the tflite converter which is happening only when using nightly (it isn't happening when using tensorflow main branch). I tried as much as I can to create the minimal code to reproduce: 

    !pip install tf-nightly
    import tensorflow as tf
    import os
    import numpy as np
    
    class EXAMPLE(tf.Module):
    
        @tf.function(input_signature=[tf.TensorSpec(shape=[100], dtype=tf.float32)])
        def calculate(self, x):
        
          maxima_ind = tf.where(x > 0.8)
          maxima_ind = tf.gather(maxima_ind,0,axis=1)
    
          maxima_ind = tf.cast(maxima_ind, dtype=tf.float32)
    
          if len(maxima_ind) > 10:
              maxima_ind = tf.cast(maxima_ind, dtype=tf.float32)
    
          return maxima_ind
          
    to_export = EXAMPLE()
    np.random.seed(54)
    buffer_size = 100
    x1  = tf.convert_to_tensor(np.random.rand(buffer_size).astype('float32'))
    
    
    solution = to_export.calculate(x1)
    print(solution)
    models_dir = '/content/model_example/'
    tf.saved_model.save(to_export, models_dir)
    imported = tf.saved_model.load(models_dir)
    converter = tf.lite.TFLiteConverter.from_saved_model(models_dir) # path to the SavedModel directory
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                            tf.lite.OpsSet.SELECT_TF_OPS]
    
    tflite_model = converter.convert()
    with open(models_dir + 'model_example.tflite', 'wb') as f:
      f.write(tflite_model)

When running it, I'm getting this error: 

    Exception                                 Traceback (most recent call last)
    /usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
        216                                                  debug_info_str,
    --> 217                                                  enable_mlir_converter)
        218       return model_str
    
    4 frames
    Exception: <unknown>:0: error: loc("cond@__inference_calculate_3155"): 'tf.If' op 'then_branch' input type tensor<?xf32> is incompatible with input type tensor<?xi64> at index 0
    
    
    During handling of the above exception, another exception occurred:
    
        ConverterError                            Traceback (most recent call last)
        /usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
            218       return model_str
            219     except Exception as e:
        --> 220       raise ConverterError(str(e))
            221 
            222   if distutils.spawn.find_executable(_toco_from_proto_bin) is None:
        
        ConverterError: <unknown>:0: error: loc("cond@__inference_calculate_3155"): 'tf.If' op 'then_branch' input type tensor<?xf32> is incompatible with input type tensor<?xi64> at index 0

You can also use this gist (which include the above code): 
I understand there is a thing with the types but I'm using casting before the if statement and inside of it I'm actually doing nothing, and it isn't happening in the main branch..  
Any help will be appreciated. Thank you

**Comment by abattery** [comment]
@AiaHaruv thank you for filing a bug to us :-) Could you file a separate issue for the if op behavior in order to track the issue without the unrelated stuffs?

**Comment by AiaHaruv** [comment]
@abattery - sure, [opened here](https://github.com/tensorflow/tensorflow/issues/46656) 
Thank you
