### ISSUE TITLE
cannot convert tf savedmodel to onnx

### ISSUE THREAD

**Issue by zhaohb** [tensorflow/tensorflow#46573]
**System information**
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 18.04
TensorFlow installed from (source or binary):
binary
TensorFlow version (use command below):
tf-nightly-gpu         2.5.0.dev20210119
Python version:
3.6 (Anaconda)
Tensorflow-onnx version:
1.8.0. build from source

my command line :
```shell
python -m tf2onnx.convert --saved-model ./model.savedmodel --output fea.onnx --custom-ops Bucketize,AsString,StringToHashBucketFast --signature_def serving_default --tag serve --opset 12 
```
But I got the following error：
```shell
......
2021-01-21 11:29:41,413 - ERROR - Could not find table resource to replace placeholder unknown_172
2021-01-21 11:29:41,415 - ERROR - Could not find table resource to replace placeholder unknown_174
2021-01-21 11:29:41,416 - ERROR - Could not find table resource to replace placeholder unknown_176
2021-01-21 11:29:41,417 - ERROR - Could not find table resource to replace placeholder unknown_178
2021-01-21 11:29:41,418 - ERROR - Could not find table resource to replace placeholder unknown_180
2021-01-21 11:29:41,418 - ERROR - Could not find table resource to replace placeholder unknown_183
2021-01-21 11:29:41,418 - ERROR - Could not find table resource to replace placeholder unknown_185
2021-01-21 11:29:41,418 - ERROR - Could not find table resource to replace placeholder unknown_187
2021-01-21 11:29:41,418 - ERROR - Could not find table resource to replace placeholder unknown_189
2021-01-21 11:29:41,418 - ERROR - Could not find table resource to replace placeholder unknown_193
2021-01-21 11:29:41,418 - ERROR - Could not find table resource to replace placeholder unknown_195
2021-01-21 11:29:41,419 - ERROR - Could not find table resource to replace placeholder unknown_197
......
tensorflow.python.framework.errors_impl.InvalidArgumentError: 'func' argument to TF_GraphCopyFunction cannot be null
Exception ignored in: <bound method CapturableResourceDeleter.__del__ of <tensorflow.python.training.tracking.tracking.CapturableResourceDeleter object at 0x7f70486cbcf8>>
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/tf2.2-n/lib/python3.6/site-packages/tensorflow/python/training/tracking/tracking.py", line 208, in __del__
    self._destroy_resource()
  File "/usr/local/anaconda3/envs/tf2.2-n/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 797, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/anaconda3/envs/tf2.2-n/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 841, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/usr/local/anaconda3/envs/tf2.2-n/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 695, in _initialize
    *args, **kwds))
  File "/usr/local/anaconda3/envs/tf2.2-n/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2981, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/anaconda3/envs/tf2.2-n/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3373, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/anaconda3/envs/tf2.2-n/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3218, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/usr/local/anaconda3/envs/tf2.2-n/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 998, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/anaconda3/envs/tf2.2-n/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 603, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/local/anaconda3/envs/tf2.2-n/lib/python3.6/site-packages/tensorflow/python/saved_model/function_deserialization.py", line 257, in restored_function_body
    return _call_concrete_function(function, inputs)
  File "/usr/local/anaconda3/envs/tf2.2-n/lib/python3.6/site-packages/tensorflow/python/saved_model/function_deserialization.py", line 75, in _call_concrete_function
    result = function._call_flat(tensor_inputs, function._captured_inputs)  # pylint: disable=protected-access
  File "/usr/local/anaconda3/envs/tf2.2-n/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py", line 116, in _call_flat
    cancellation_manager)
  File "/usr/local/anaconda3/envs/tf2.2-n/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1944, in _call_flat
    flat_outputs = forward_function.call(ctx, args_with_tangents)
  File "/usr/local/anaconda3/envs/tf2.2-n/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 590, in call
    executor_type=executor_type)
  File "/usr/local/anaconda3/envs/tf2.2-n/lib/python3.6/site-packages/tensorflow/python/ops/functional_ops.py", line 1206, in partitioned_call
    f.add_to_graph(graph)
  File "/usr/local/anaconda3/envs/tf2.2-n/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 506, in add_to_graph
    g._add_function(self)
  File "/usr/local/anaconda3/envs/tf2.2-n/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3403, in _add_function
    gradient)

```
I want to get the ONNX model, desperate for some advice！

thank you very much

**Comment by ravikyram** [comment]
@zhaohb 

Please, share colab link or complete code snippet along with supporting files t reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by zhaohb** [comment]
@ravikyram I can send the model file to you by email. Is that OK? Then you can repeat the question.

**Comment by zhaohb** [comment]
[https://colab.research.google.com/drive/1wxu8piPR9qyAC8EjtDd6-STZqek77BO7?usp=sharing](url)
colab link

**Comment by jvishnuvardhan** [comment]
@zhaohb Sorry for the late response. I notice you have opened same issue in the onnx repo https://github.com/onnx/tensorflow-onnx/issues/1287 and also getting the responses to resolve your issue. That is the correct repo for your issue.

I am closing this issue from this repo. Thanks!
