### ISSUE TITLE
Mixed Precision - Conv3D - error: No algorithm worked!

### ISSUE THREAD

**Issue by emiliocoutinho** [tensorflow/tensorflow#46589]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes, I wrote a custom code.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux (CentOS 7)
- TensorFlow installed from (source or binary):
Installed using PIP
- TensorFlow version (use command below):
v2.4.0-rc4-71-g582c8d236cb 2.4.0
- Python version:
3.8.0
- CUDA/cuDNN version:
CUDA/11.1.1
cuDNN/8.0.4.30-CUDA-11.1.1
- GPU model and memory:
2 NVIDIA A100-PCIE-40GB
2 GPUs on the same computer

**Describe the current behavior**
When running the code with double precision, the code does not generate errors. When running with mixed precision, launches an error:

**Describe the expected behavior**
Not having errors when running with mixed precision.

**Standalone code to reproduce the issue**
I tried to create a google colab for this code. There is no error there, but I could not get a google colab with 2 GPUs, like in my enviroment.
```
import tensorflow as tf
from tensorflow.keras.mixed_precision import experimental as mixed_precision
from tensorflow.keras import layers, Model, optimizers
import numpy as np

# If you comment the following 2 lines, the code runs
policy = mixed_precision.Policy('mixed_float16')
mixed_precision.set_policy(policy)


mirrored_strategy = tf.distribute.MirroredStrategy()
with mirrored_strategy.scope():
    x_input = layers.Input(shape=(60, 60, 2, 32))

    x = layers.Conv3D(filters=32, kernel_size=(3, 3, 1), strides=(1, 1, 1), padding = 'same')(x_input)
    x = layers.BatchNormalization()(x)
    x_out = layers.ReLU()(x)

    test_model = Model(inputs=x_input, outputs=x_out, name='test_model')
    adam = optimizers.Adam(learning_rate=1E-4)

test_model.compile(optimizer=adam, loss="mse", metrics=["mae"])

input_data = np.random.random((1000, 60, 60, 2, 32))
target_data = np.random.random((1000, 60, 60, 2, 32))

ds_tuple = tf.data.Dataset.from_tensor_slices((input_data,target_data))
ds_tuple = ds_tuple.shuffle(1000).batch(100)

history = test_model.fit(ds_tuple, epochs=10, verbose=1)
```

**Other info / logs** 
This is the log of the run when I try running with mixed precision:
```
2021-01-21 15:37:22.318957: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-01-21 15:37:36.119468: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-01-21 15:37:36.123358: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-01-21 15:37:36.201391: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
pciBusID: 0000:3b:00.0 name: A100-PCIE-40GB computeCapability: 8.0
coreClock: 1.41GHz coreCount: 108 deviceMemorySize: 39.59GiB deviceMemoryBandwidth: 1.41TiB/s
2021-01-21 15:37:36.204229: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 1 with properties:
pciBusID: 0000:d8:00.0 name: A100-PCIE-40GB computeCapability: 8.0
coreClock: 1.41GHz coreCount: 108 deviceMemorySize: 39.59GiB deviceMemoryBandwidth: 1.41TiB/s
2021-01-21 15:37:36.204423: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-01-21 15:37:37.945043: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-01-21 15:37:37.945235: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2021-01-21 15:37:37.998423: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2021-01-21 15:37:38.072705: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2021-01-21 15:37:38.207114: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2021-01-21 15:37:38.574293: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2021-01-21 15:37:38.612582: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-01-21 15:37:38.624584: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0, 1
2021-01-21 15:37:38.624772: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-01-21 15:37:38.626778: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
WARNING:tensorflow:From /scratch/user/eee/conda/myEnvs/tf_2.4/lib/python3.8/site-packages/tensorflow/python/keras/mixed_precision/loss_scale.py:56: DynamicLossScale.__init__ (from tensorflow.python.training.experimental.loss_scale) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.keras.mixed_precision.LossScaleOptimizer instead. LossScaleOptimizer now has all the functionality of DynamicLossScale
2021-01-21 15:37:38.638220: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX512F
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-01-21 15:37:38.638847: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-01-21 15:37:38.840057: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
pciBusID: 0000:3b:00.0 name: A100-PCIE-40GB computeCapability: 8.0
coreClock: 1.41GHz coreCount: 108 deviceMemorySize: 39.59GiB deviceMemoryBandwidth: 1.41TiB/s
2021-01-21 15:37:38.842228: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 1 with properties:
pciBusID: 0000:d8:00.0 name: A100-PCIE-40GB computeCapability: 8.0
coreClock: 1.41GHz coreCount: 108 deviceMemorySize: 39.59GiB deviceMemoryBandwidth: 1.41TiB/s
2021-01-21 15:37:38.842375: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-01-21 15:37:38.842436: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-01-21 15:37:38.842486: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2021-01-21 15:37:38.842536: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2021-01-21 15:37:38.842585: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2021-01-21 15:37:38.842635: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2021-01-21 15:37:38.842683: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2021-01-21 15:37:38.842733: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-01-21 15:37:38.850268: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0, 1
2021-01-21 15:37:38.850360: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-01-21 15:37:40.396681: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-01-21 15:37:40.396829: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 1
2021-01-21 15:37:40.396881: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N Y
2021-01-21 15:37:40.396925: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 1:   Y N
2021-01-21 15:37:40.407031: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 37570 MB memory) -> physical GPU (device: 0, name: A100-PCIE-40GB, pci bus id: 0000:3b:00.0, compute capability: 8.0)
2021-01-21 15:37:40.414936: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 37570 MB memory) -> physical GPU (device: 1, name: A100-PCIE-40GB, pci bus id: 0000:d8:00.0, compute capability: 8.0)
     --->     Running Tensorflow in Mixed Precision...
WARNING:tensorflow:tf.keras.mixed_precision.experimental.LossScaleOptimizer is deprecated. Please use tf.keras.mixed_precision.LossScaleOptimizer instead. Note that the non-experimental LossScaleOptimizer does not take a DynamicLossScale but instead takes the dynamic configuration directly in the constructor. For example:
  opt = tf.keras.mixed_precision.experimental.LossScaleOptimizer(opt)

2021-01-21 15:37:47.583748: W tensorflow/core/grappler/optimizers/data/auto_shard.cc:656] In AUTO-mode, and switching to DATA-based sharding, instead of FILE-based sharding as we cannot find appropriate reader dataset op(s) to shard. Error: Found an unshardable source dataset: name: "TensorSliceDataset/_2"
op: "TensorSliceDataset"
input: "Placeholder/_0"
input: "Placeholder/_1"
attr {
  key: "Toutput_types"
  value {
    list {
      type: DT_DOUBLE
      type: DT_DOUBLE
    }
  }
}
attr {
  key: "output_shapes"
  value {
    list {
      shape {
        dim {
          size: 60
        }
        dim {
          size: 60
        }
        dim {
          size: 2
        }
        dim {
          size: 32
        }
      }
      shape {
        dim {
          size: 60
        }
        dim {
          size: 60
        }
        dim {
          size: 2
        }
        dim {
          size: 32
        }
      }
    }
  }
}

2021-01-21 15:37:48.602974: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-01-21 15:37:48.606716: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 3000000000 Hz
Epoch 1/10
2021-01-21 15:37:56.331798: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-01-21 15:39:18.436971: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-01-21 15:39:28.779314: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2021-01-21 15:39:31.933180: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at conv_grad_ops_3d.cc:1994 : Not found: No algorithm worked!
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    history = test_model.fit(ds_tuple, epochs=10, verbose=1)
  File "/scratch/user/eee/conda/myEnvs/tf_2.4/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
  File "/scratch/user/eee/conda/myEnvs/tf_2.4/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/scratch/user/eee/conda/myEnvs/tf_2.4/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 888, in _call
    return self._stateless_fn(*args, **kwds)
  File "/scratch/user/eee/conda/myEnvs/tf_2.4/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2942, in __call__
    return graph_function._call_flat(
  File "/scratch/user/eee/conda/myEnvs/tf_2.4/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1918, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/scratch/user/eee/conda/myEnvs/tf_2.4/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 555, in call
    outputs = execute.execute(
  File "/scratch/user/eee/conda/myEnvs/tf_2.4/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.NotFoundError: 3 root error(s) found.
  (0) Not found:  No algorithm worked!
         [[node gradient_tape/test_model/conv3d/Conv3D/Conv3DBackpropFilterV2 (defined at /threading.py:932) ]]
  (1) Not found:  No algorithm worked!
         [[node gradient_tape/test_model/conv3d/Conv3D/Conv3DBackpropFilterV2 (defined at /threading.py:932) ]]
         [[cond_4/then/_40/cond_4/cond/pivot_t/_256/_187]]
  (2) Not found:  No algorithm worked!
         [[node gradient_tape/test_model/conv3d/Conv3D/Conv3DBackpropFilterV2 (defined at /threading.py:932) ]]
         [[div_no_nan/ReadVariableOp_3/_108]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_2870]

Function call stack:
train_function -> train_function -> train_function

```

**Comment by ymodak** [comment]
Can you please try with cuda 11.0 and TF 2.4 final version?

**Comment by Jie1Zhong** [comment]
Met the same problem, have you solved it?

**Comment by emiliocoutinho** [comment]
> Can you please try with cuda 11.0 and TF 2.4 final version?

@ymodak , I installed TF 2.4.1 from PIP and using CUDA/11.0.2 and cuDNN/8.0.4.30, and got the same error with Mixed Precision.

**Comment by itsmeshreyans** [comment]
Same error, any solution??

**Comment by HLuSLB** [comment]
Same error.

**Comment by reedwm** [comment]
Upgrading to cuDNN 8.0.5 fixes this. 8.0.5 is compatible with TF 2.4 and tf-nightly, so please upgrade.

I can reproduce with cuDNN 8.0.3 and 8.0.4, but not with cuDNN 8.0.2 and 8.0.5, so this has been fixed by 8.0.5. If it's feasible to check the cuDNN version at runtime, I'll improve the error message to state 8.0.5 should be used. @nluehr do you know if there are any workarounds for 8.0.3 and 8.0.4?

@sanjoy, can we update the [GPU support](https://www.tensorflow.org/install/gpu) guide to recommend 8.0.5? Currently it recommends 8.0.4. 

For reference, with 8.0.5, the only `cudnnConvolutionBwdFilterAlgo_t` which works is `CUDNN_CONVOLUTION_BWD_FILTER_ALGO_1`. This fails on 8.0.3 and 8.0.4 though.

**Comment by Jie1Zhong** [comment]
> Upgrading to cuDNN 8.0.5 fixes this. 8.0.5 is compatible with TF 2.4 and tf-nightly, so please upgrade.
> 
> I can reproduce with cuDNN 8.0.3 and 8.0.4, but not with cuDNN 8.0.2 and 8.0.5, so this has been fixed by 8.0.5. If it's feasible to check the cuDNN version at runtime, I'll improve the error message to state 8.0.5 should be used. @nluehr do you know if there are any workarounds for 8.0.3 and 8.0.4?
> 
> @sanjoy, can we update the [GPU support](https://www.tensorflow.org/install/gpu) guide to recommend 8.0.5? Currently it recommends 8.0.4.
> 
> For reference, with 8.0.5, the only `cudnnConvolutionBwdFilterAlgo_t` which works is `CUDNN_CONVOLUTION_BWD_FILTER_ALGO_1`. This fails on 8.0.3 and 8.0.4 though.
Reinstall cuDNN 8.0.5 worked for me, thanks!

**Comment by Jie1Zhong** [comment]
> Upgrading to cuDNN 8.0.5 fixes this. 8.0.5 is compatible with TF 2.4 and tf-nightly, so please upgrade.
> 
> I can reproduce with cuDNN 8.0.3 and 8.0.4, but not with cuDNN 8.0.2 and 8.0.5, so this has been fixed by 8.0.5. If it's feasible to check the cuDNN version at runtime, I'll improve the error message to state 8.0.5 should be used. @nluehr do you know if there are any workarounds for 8.0.3 and 8.0.4?
> 
> @sanjoy, can we update the [GPU support](https://www.tensorflow.org/install/gpu) guide to recommend 8.0.5? Currently it recommends 8.0.4.
> 
> For reference, with 8.0.5, the only `cudnnConvolutionBwdFilterAlgo_t` which works is `CUDNN_CONVOLUTION_BWD_FILTER_ALGO_1`. This fails on 8.0.3 and 8.0.4 though.
*********
Reinstall cuDNN 8.0.5 worked for me, thanks!

**Comment by bashkanov** [comment]
Same error.

**Comment by emiliocoutinho** [comment]
After updating to cuDNN 8.0.5 the problem was solved. Thanks, @reedwm.
