### ISSUE TITLE
google.protobuf.text_format.ParseError: 161:14 : Message type "object_detection.protos.Optimizer" has no field named "i".

### ISSUE THREAD

**Issue by aarju123** [tensorflow/tensorflow#46655]
sparse.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/aarju/anaconda3/envs/demo_model/lib:/usr/lib/x86_64-linux-gnu:/home/aarju/anaconda3/envs/caffe/lib:/usr/lib/x86_64-linux-gnu
2021-01-25 14:30:04.810886: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/aarju/anaconda3/envs/demo_model/lib:/usr/lib/x86_64-linux-gnu:/home/aarju/anaconda3/envs/caffe/lib:/usr/lib/x86_64-linux-gnu
2021-01-25 14:30:04.810902: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1757] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2021-01-25 14:30:04.811643: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-01-25 14:30:04.814596: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-01-25 14:30:04.814714: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-01-25 14:30:04.814742: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]
WARNING:tensorflow:There are non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce.
W0125 14:30:04.820366 140452454930176 cross_device_ops.py:1321] There are non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce.
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',)
I0125 14:30:04.821369 140452454930176 mirrored_strategy.py:350] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',)
Traceback (most recent call last):
  File "model_main_tf2.py", line 113, in <module>
    tf.compat.v1.app.run()
  File "/home/aarju/anaconda3/envs/demo_model/lib/python3.8/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/aarju/anaconda3/envs/demo_model/lib/python3.8/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/aarju/anaconda3/envs/demo_model/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "model_main_tf2.py", line 104, in main
    model_lib_v2.train_loop(
  File "/home/aarju/anaconda3/envs/demo_model/lib/python3.8/site-packages/object_detection/model_lib_v2.py", line 466, in train_loop
    configs = get_configs_from_pipeline_file(
  File "/home/aarju/anaconda3/envs/demo_model/lib/python3.8/site-packages/object_detection/utils/config_util.py", line 139, in get_configs_from_pipeline_file
    text_format.Merge(proto_str, pipeline_config)
  File "/home/aarju/anaconda3/envs/demo_model/lib/python3.8/site-packages/google/protobuf/text_format.py", line 728, in Merge
    return MergeLines(
  File "/home/aarju/anaconda3/envs/demo_model/lib/python3.8/site-packages/google/protobuf/text_format.py", line 802, in MergeLines
    return parser.MergeLines(lines, message)
  File "/home/aarju/anaconda3/envs/demo_model/lib/python3.8/site-packages/google/protobuf/text_format.py", line 827, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/home/aarju/anaconda3/envs/demo_model/lib/python3.8/site-packages/google/protobuf/text_format.py", line 849, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/home/aarju/anaconda3/envs/demo_model/lib/python3.8/site-packages/google/protobuf/text_format.py", line 974, in _MergeField
    merger(tokenizer, message, field)
  File "/home/aarju/anaconda3/envs/demo_model/lib/python3.8/site-packages/google/protobuf/text_format.py", line 1048, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/aarju/anaconda3/envs/demo_model/lib/python3.8/site-packages/google/protobuf/text_format.py", line 974, in _MergeField
    merger(tokenizer, message, field)
  File "/home/aarju/anaconda3/envs/demo_model/lib/python3.8/site-packages/google/protobuf/text_format.py", line 1048, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/aarju/anaconda3/envs/demo_model/lib/python3.8/site-packages/google/protobuf/text_format.py", line 939, in _MergeField
    raise tokenizer.ParseErrorPreviousToken(
google.protobuf.text_format.ParseError: 161:14 : Message type "object_detection.protos.Optimizer" has no field named "i".

### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

-   **TensorFlow installed from (source or binary)**:
-   **TensorFlow version (use command below)**:: 2.4
-   **Python version**: : 3.7
-   **Bazel version (if compiling from source)**:
-   **GCC/Compiler version (if compiling from source)**:
-   **CUDA/cuDNN version**: 10.2
-   **GPU model and memory**:
-   **Exact command to reproduce**:

**Comment by amahendrakar** [comment]
@aarju123,
In order to reproduce the issue reported here, could you please provide the TensorFlow version, the complete code and the dataset you are using. Thanks!

**Comment by aarju123** [comment]
this is protos error getting to run program, using tensorlow 2.4.1

**Comment by amahendrakar** [comment]
@aarju123,
Could you please share the script you are running, so that we can reproduce the issue on our end. Thanks!
