### ISSUE TITLE
Tensorflow 2.4 Compile

### ISSUE THREAD

**Issue by aloizo03** [tensorflow/tensorflow#46664]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):  with command  pip install tensorflow-gpu==2.4.0
- TensorFlow version: 2.4.0
- Python version: Python 3.6.9
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: cuda :11.0,  cuDNN :  8.0.2
- Driver Version: 450.102.04
- GPU model and memory: Gigabyte Nvidia GForce 1660 6GB

**Describe the problem**

I execute the basic command 
import tensorflow as tf
print(tf.test.gpu_device_name())

to see if tensorflow 2.4 is execute in my ubuntu i have all installed than we need for this version like cuda version, cuddn version and driver version. What maybe is the problem ? 
With tensorflow 2.3 compile successfully but he cannnot load the cuddn library and cuda.

**Any other info / logs**
From compiler i get this message : 
2021-01-25 16:27:37.386741: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 435, in <module>
    _ll.load_library(_main_dir)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/load_library.py", line 153, in load_library
    py_tf.TF_LoadLibrary(lib)
tensorflow.python.framework.errors_impl.NotFoundError: /home/antreas/.local/lib/python3.6/site-packages/tensorflow/core/kernels/libtfkernel_sobol_op.so: undefined symbol: _ZN10tensorflow8OpKernel11TraceStringEPNS_15OpKernelContextEb

**Comment by amahendrakar** [comment]
@aloizo03,
Could you please try installing TensorFlow in a new virtual environment and check if it works?

Also, try installing TensorFlow v2.4.1 using the below command and let us know if you are facing the same error. 

`pip install tensorflow==2.4.1`

Thanks!

**Comment by aloizo03** [comment]
@amahendrakar  
I install the 2.4.1 and i get this
2021-01-25 18:50:21.072974: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-01-25 18:50:21.821691: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-01-25 18:50:21.822075: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-01-25 18:50:22.001576: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-01-25 18:50:23.284599: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-25 18:50:23.285193: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:2d:00.0 name: GeForce GTX 1660 computeCapability: 7.5
coreClock: 1.86GHz coreCount: 22 deviceMemorySize: 5.80GiB deviceMemoryBandwidth: 178.86GiB/s
2021-01-25 18:50:23.285219: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-01-25 18:50:23.972534: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-01-25 18:50:23.972624: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2021-01-25 18:50:24.478819: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2021-01-25 18:50:24.722951: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2021-01-25 18:50:25.546900: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2021-01-25 18:50:25.561327: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2021-01-25 18:50:25.566373: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-01-25 18:50:25.566510: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-25 18:50:25.567143: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-25 18:50:25.567663: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-01-25 18:50:25.567697: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-01-25 18:50:25.978800: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-01-25 18:50:25.978832: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 
2021-01-25 18:50:25.978837: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N 
2021-01-25 18:50:25.978997: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-25 18:50:25.979305: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-25 18:50:25.979582: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-25 18:50:25.979852: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/device:GPU:0 with 4937 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1660, pci bus id: 0000:2d:00.0, compute capability: 7.5)
/device:GPU:0

It's ok now ?
And thanks for the help and the quick response i appreciate very much!!

**Comment by mihaimaruseac** [comment]
Those seems to be all information messages (`I`). Seems ok to me.

**Comment by amahendrakar** [comment]
> It's ok now ?
> And thanks for the help and the quick response i appreciate very much!!

@aloizo03,
Happy to help :)

The logs are just to confirm that TensorFlow has successfully detected the GPU on your machine. You can safely ignore those information logs. 

Please feel free to close the issue if resolved. Thanks!
