### ISSUE TITLE
tf wide and deep model save error

### ISSUE THREAD

**Issue by Litchilitchy** [tensorflow/tensorflow#46719]
I am using TF 2.2, the `save` method raises error, 

very brief code to reproduce, nearly all code are from TF official doc https://www.tensorflow.org/api_docs/python/tf/keras/experimental/WideDeepModel
```
import tensorflow as tf
from tensorflow.python.keras.premade.linear import LinearModel
from tensorflow.python.keras.premade.wide_deep import WideDeepModel
import numpy as np

linear_model = LinearModel()
dnn_model = tf.keras.Sequential([tf.keras.layers.Dense(units=64),
                              tf.keras.layers.Dense(units=1)])
combined_model = WideDeepModel(linear_model, dnn_model)
combined_model.compile(optimizer=['sgd', 'adam'], loss='mse', metrics=['mse'])
# define dnn_inputs and linear_inputs as separate numpy arrays or
# a single numpy array if dnn_inputs is same as linear_inputs.
linear_inputs = np.random.random((2, 3))
dnn_inputs = np.random.random((2, 3))
y = np.random.randint(0, 2, (2, 2))

combined_model.fit([linear_inputs, dnn_inputs], y, epochs=1)
combined_model.save('tf-wide-deep')
```
error is 
```
1/1 [==============================] - 0s 365us/step - loss: 0.4376 - mse: 0.4376
2021-01-27 13:36:54.121411: W tensorflow/python/util/util.cc:329] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
WARNING:tensorflow:From /home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:1817: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.

Error
Traceback (most recent call last):
  File "/home/litchy/rec-pro/tf-models/test_tf_models.py", line 23, in test_wide_deep
    combined_model.save('tf-wide-deep')
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1052, in save
    signatures, options)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/keras/saving/save.py", line 138, in save_model
    signatures, options)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/save.py", line 78, in save
    save_lib.save(model, filepath, signatures, options)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 951, in save
    obj, export_dir, signatures, options, meta_graph_def)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 1037, in _build_meta_graph
    asset_info.asset_index)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 697, in _serialize_object_graph
    saveable_view.function_name_map)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 737, in _write_object_proto
    metadata=obj._tracking_metadata)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2742, in _tracking_metadata
    return self._trackable_saved_model_saver.tracking_metadata
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/base_serialization.py", line 54, in tracking_metadata
    return json_utils.Encoder().encode(self.python_properties)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 41, in python_properties
    return self._python_properties_internal()
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/model_serialization.py", line 38, in _python_properties_internal
    self.obj, include_optimizer=True, require_config=False))
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 188, in model_metadata
    model.optimizer.get_config()
AttributeError: 'ListWrapper' object has no attribute 'get_config'

```

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.2, nightly version (`2.5.0-dev20210126`) and was able to reproduce the issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/db71114bed69f93906e38c5435d5ba56/untitled637.ipynb). Thanks!

**Comment by timruning** [comment]
this is a bug that tf can't get optimizer from list. 
you can save model with no optimizer like "model.save(include_optimizer=False)"
than feed a new optimizer after load the model , when you want to train it again.

**Comment by rnyak** [comment]
Hello, is there any progress regarding this issue? Thanks.

**Comment by saikumarchalla** [comment]
Still an issue in TF Nightly 2.6 Version. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/1c813432cc3e4167d874b93a8c8edcbd/untitled92.ipynb).Thanks!

**Comment by gadagashwini** [comment]
@Litchilitchy,
Issue with the optimizers list.
`optimizer=['sgd', 'adam']`
When we use multiple optimizers, we can use Multi Optimizer Wrapper `tfa.optimizers.MultiOptimizer`.

**Working sample code**
```
import tensorflow as tf
#from tensorflow.keras.premade.linear import LinearModel
#from tensorflow.keras.premade.wide_deep import WideDeepModel
from tensorflow.keras.experimental import LinearModel
from tensorflow.keras.experimental import WideDeepModel
import numpy as np
import tensorflow_addons as tfa

linear_model = LinearModel()
dnn_model = tf.keras.Sequential([tf.keras.layers.Dense(units=64),
                             tf.keras.layers.Dense(units=1)])
combined_model = WideDeepModel(linear_model, dnn_model)
#combined_model.compile(optimizer=['sgd', 'adam'], 'mse', ['mse'])
optimizers = [
    tf.keras.optimizers.SGD(learning_rate=1e-4),
    tf.keras.optimizers.Adam(learning_rate=1e-2)
]
optimizers_and_layers = [(optimizers[0], dnn_model.layers[0:]), (optimizers[1], dnn_model.layers[1:])]
optimizer = tfa.optimizers.MultiOptimizer(optimizers_and_layers)
combined_model.compile(optimizer=optimizer, loss='mse', metrics=['mse'])

# define dnn_inputs and linear_inputs as separate numpy arrays or
# a single numpy array if dnn_inputs is same as linear_inputs.

linear_inputs = np.random.random((2, 3))
dnn_inputs = np.random.random((2, 3))
y = np.random.randint(0, 2, (2, 2))

combined_model.fit([linear_inputs, dnn_inputs], y, epochs=1)

combined_model.save('tf-wide-deep')
```

**Output**
```
1/1 [==============================] - 0s 314ms/step - loss: 0.3535 - mse: 0.3535
<keras.callbacks.History at 0x7f4edc0442d0>

INFO:tensorflow:Assets written to: tf-wide-deep/assets
```

**Comment by Litchilitchy** [comment]
@gadagashwini thanks, I would try. The code is from official example so that it seems need some change if this works.

**Comment by gadagashwini** [comment]
@Litchilitchy, Official example code is not complete code snippet. If you make changes to optimizers, you can use the code given in the Tensorflow website. 
Can we move this issue to closure, since its resolved .Thanks!
