### ISSUE TITLE
Converting TF2 Object detection API model to frozen graph

### ISSUE THREAD

**Issue by Bleach665** [tensorflow/tensorflow#46740]
Win10, Tensorflow 2.4, Object detection API bcc9ab69195489dae89ad784f882f81f90bf93e4.

`ssd_resnet50_v1_fpn_640x640_coco17_tpu-8` model trained using Tensorflow object detection API using
https://github.com/tensorflow/models/blob/master/research/object_detection/model_main_tf2.py

After exported to `Save model`:
 `.\exporter_main_v2.py --input_type image_tensor --pipeline_config_path .\models\my_ssd_resnet50_v1_fpn\pipeline.config --trained_checkpoint_dir .\models\my_ssd_resnet50_v1_fpn\ --output_directory .\exported-models\models\Bel_model` using
https://github.com/tensorflow/models/blob/master/research/object_detection/exporter_main_v2.py

On this step inference work fine with Tensorflow.

Inference from `Saved model`:
<details>

````
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'    # Suppress TensorFlow logging (1)
import pathlib
import tensorflow as tf

tf.get_logger().setLevel('ERROR')           # Suppress TensorFlow logging (2)

# Enable GPU dynamic memory allocation
gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)


PATH_TO_LABELS = "label_map.pbtxt" 

# %%
# Load the model
# ~~~~~~~~~~~~~~
# Next we load the downloaded model
import time
from object_detection.utils import label_map_util
from object_detection.utils import visualization_utils as viz_utils

PATH_TO_SAVED_MODEL = "models\\Bel_model\\saved_model"

print('Loading model...', end='')
start_time = time.time()

# Load saved model and build the detection function
detect_fn = tf.saved_model.load(PATH_TO_SAVED_MODEL)

end_time = time.time()
elapsed_time = end_time - start_time
print('Done! Took {} seconds'.format(elapsed_time))

# %%
# Load label map data (for plotting)
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Label maps correspond index numbers to category names, so that when our convolution network
# predicts `5`, we know that this corresponds to `airplane`.  Here we use internal utility
# functions, but anything that returns a dictionary mapping integers to appropriate string labels
# would be fine.

category_index = label_map_util.create_category_index_from_labelmap(PATH_TO_LABELS,
                                                                    use_display_name=True)

# %%
# Putting everything together
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~
# The code shown below loads an image, runs it through the detection model and visualizes the
# detection results, including the keypoints.
#
# Note that this will take a long time (several minutes) the first time you run this code due to
# tf.function's trace-compilation --- on subsequent runs (e.g. on new images), things will be
# faster.
#
# Here are some simple things to try out if you are curious:
#
# * Modify some of the input images and see if detection still works. Some simple things to try out here (just uncomment the relevant portions of code) include flipping the image horizontally, or converting to grayscale (note that we still expect the input image to have 3 channels).
# * Print out `detections['detection_boxes']` and try to match the box locations to the boxes in the image.  Notice that coordinates are given in normalized form (i.e., in the interval [0, 1]).
# * Set ``min_score_thresh`` to other values (between 0 and 1) to allow more detections in or to filter out more detections.
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')   # Suppress Matplotlib warnings

def load_image_into_numpy_array(path):
    """Load an image from file into a numpy array.

    Puts image into numpy array to feed into tensorflow graph.
    Note that by convention we put it into a numpy array with shape
    (height, width, channels), where channels=3 for RGB.

    Args:
      path: the file path to the image

    Returns:
      uint8 numpy array with shape (img_height, img_width, 3)
    """
    return np.array(Image.open(path))

IMAGE_PATHS = ['1.png', '2.png']

for image_path in IMAGE_PATHS:

    print('Running inference for {}... '.format(image_path), end='')

    image_np = load_image_into_numpy_array(image_path)

    # Things to try:
    # Flip horizontally
    # image_np = np.fliplr(image_np).copy()

    # Convert image to grayscale
    # image_np = np.tile(
    #     np.mean(image_np, 2, keepdims=True), (1, 1, 3)).astype(np.uint8)

    # The input needs to be a tensor, convert it using `tf.convert_to_tensor`.
    input_tensor = tf.convert_to_tensor(image_np)
    # The model expects a batch of images, so add an axis with `tf.newaxis`.
    input_tensor = input_tensor[tf.newaxis, ...]

    # input_tensor = np.expand_dims(image_np, 0)
    detections = detect_fn(input_tensor)

    # All outputs are batches tensors.
    # Convert to numpy arrays, and take index [0] to remove the batch dimension.
    # We're only interested in the first num_detections.
    num_detections = int(detections.pop('num_detections'))
    detections = {key: value[0, :num_detections].numpy()
                   for key, value in detections.items()}
    detections['num_detections'] = num_detections

    # detection_classes should be ints.
    detections['detection_classes'] = detections['detection_classes'].astype(np.int64)

    image_np_with_detections = image_np.copy()

    viz_utils.visualize_boxes_and_labels_on_image_array(
          image_np_with_detections,
          detections['detection_boxes'],
          detections['detection_classes'],
          detections['detection_scores'],
          category_index,
          use_normalized_coordinates=True,
          max_boxes_to_draw=200,
          min_score_thresh=.30,
          agnostic_mode=False)  
    
    plt.figure()
    plt.imshow(image_np_with_detections)
    
    #***
    newname =  image_path.replace('.', '_out.') 
    plt.savefig(newname)
    
    print('Done')
plt.show()

# sphinx_gallery_thumbnail_number = 2
````
</details>

Inference from `Checkpoint`:
<details>

````
#!/usr/bin/env python
# coding: utf-8
"""
Object Detection From TF2 Checkpoint
====================================
"""

import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'    # Suppress TensorFlow logging (1)
import pathlib
import tensorflow as tf

PATH_TO_LABELS = "label_map.pbtxt" 
PATH_TO_MODEL_DIR = "models/Bel_model"

# %%
# Load the model
# ~~~~~~~~~~~~~~
# Next we load the downloaded model
import time
from object_detection.utils import label_map_util
from object_detection.utils import config_util
from object_detection.utils import visualization_utils as viz_utils
from object_detection.builders import model_builder

PATH_TO_CFG = PATH_TO_MODEL_DIR + "/pipeline.config"
PATH_TO_CKPT = PATH_TO_MODEL_DIR + "/checkpoint"

print('Loading model... ', end='')
start_time = time.time()

# Load pipeline config and build a detection model
configs = config_util.get_configs_from_pipeline_file(PATH_TO_CFG)
model_config = configs['model']
detection_model = model_builder.build(model_config=model_config, is_training=False)

# Restore checkpoint
ckpt = tf.compat.v2.train.Checkpoint(model=detection_model)
ckpt.restore(os.path.join(PATH_TO_CKPT, 'ckpt-0')).expect_partial()

@tf.function
def detect_fn(image):
    """Detect objects in image."""

    image, shapes = detection_model.preprocess(image)
    prediction_dict = detection_model.predict(image, shapes)
    detections = detection_model.postprocess(prediction_dict, shapes)

    return detections

end_time = time.time()
elapsed_time = end_time - start_time
print('Done! Took {} seconds'.format(elapsed_time))

# %%
# Load label map data (for plotting)
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Label maps correspond index numbers to category names, so that when our convolution network
# predicts `5`, we know that this corresponds to `airplane`.  Here we use internal utility
# functions, but anything that returns a dictionary mapping integers to appropriate string labels
# would be fine.

category_index = label_map_util.create_category_index_from_labelmap(PATH_TO_LABELS,
                                                                    use_display_name=True)

# %%
# Putting everything together
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~
# The code shown below loads an image, runs it through the detection model and visualizes the
# detection results, including the keypoints.
#
# Note that this will take a long time (several minutes) the first time you run this code due to
# tf.function's trace-compilation --- on subsequent runs (e.g. on new images), things will be
# faster.
#
# Here are some simple things to try out if you are curious:
#
# * Modify some of the input images and see if detection still works. Some simple things to try out here (just uncomment the relevant portions of code) include flipping the image horizontally, or converting to grayscale (note that we still expect the input image to have 3 channels).
# * Print out `detections['detection_boxes']` and try to match the box locations to the boxes in the image.  Notice that coordinates are given in normalized form (i.e., in the interval [0, 1]).
# * Set ``min_score_thresh`` to other values (between 0 and 1) to allow more detections in or to filter out more detections.
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')   # Suppress Matplotlib warnings

def load_image_into_numpy_array(path):
    """Load an image from file into a numpy array.

    Puts image into numpy array to feed into tensorflow graph.
    Note that by convention we put it into a numpy array with shape
    (height, width, channels), where channels=3 for RGB.

    Args:
      path: the file path to the image

    Returns:
      uint8 numpy array with shape (img_height, img_width, 3)
    """
    return np.array(Image.open(path))

IMAGE_PATHS = ['1.png', '2.png']

for image_path in IMAGE_PATHS:

    print('Running inference for {}... '.format(image_path), end='')

    image_np = load_image_into_numpy_array(image_path)        
    
    plt.figure()
    plt.imshow(image_np)

    # Things to try:
    # Flip horizontally
    # image_np = np.fliplr(image_np).copy()

    # Convert image to grayscale
    # image_np = np.tile(
    #     np.mean(image_np, 2, keepdims=True), (1, 1, 3)).astype(np.uint8)

    input_tensor = tf.convert_to_tensor(np.expand_dims(image_np, 0), dtype=tf.float32)

    detections = detect_fn(input_tensor)

    # All outputs are batches tensors.
    # Convert to numpy arrays, and take index [0] to remove the batch dimension.
    # We're only interested in the first num_detections.
    num_detections = int(detections.pop('num_detections'))
    detections = {key: value[0, :num_detections].numpy()
                  for key, value in detections.items()}
    detections['num_detections'] = num_detections

    # detection_classes should be ints.
    detections['detection_classes'] = detections['detection_classes'].astype(np.int64)

    label_id_offset = 1
    image_np_with_detections = image_np.copy()

    viz_utils.visualize_boxes_and_labels_on_image_array(
            image_np_with_detections,
            detections['detection_boxes'],
            detections['detection_classes']+label_id_offset,
            detections['detection_scores'],
            category_index,
            use_normalized_coordinates=True,
            max_boxes_to_draw=200,
            min_score_thresh=.30,
            agnostic_mode=False)

    plt.figure()
    plt.imshow(image_np_with_detections)  
    
    #***
    newname =  image_path.replace('.', '_out_cp.') 
    plt.savefig(newname)
    
    print('Done')
plt.show()

# sphinx_gallery_thumbnail_number = 2
````
</details>

But when I try to convert `Saved model` to `Frozen graph` 
````
import tensorflow as tf
print(tf.__version__)

from tensorflow.python.framework.convert_to_constants import convert_variables_to_constants_v2

loaded = tf.saved_model.load('models/mnist_test')
infer = loaded.signatures['serving_default']

f = tf.function(infer).get_concrete_function(flatten_input=tf.TensorSpec(shape=[None, 28, 28, 1], dtype=tf.float32))
f2 = convert_variables_to_constants_v2(f)
graph_def = f2.graph.as_graph_def()

# Export frozen graph
with tf.io.gfile.GFile('frozen_graph.pb', 'wb') as f:
   f.write(graph_def.SerializeToString())
````
as suggested here
https://github.com/opencv/opencv/issues/16879#issuecomment-603815872
I receive error:
<details>

````
2021-01-27 14:20:25.689687: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-01-27 14:20:25.689761: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-01-27 14:20:33.819028: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-01-27 14:20:33.819694: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2021-01-27 14:20:33.821661: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-01-27 14:20:33.825189: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: Eclipse
2021-01-27 14:20:33.825303: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: Eclipse
2021-01-27 14:20:33.826001: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-01-27 14:20:33.826483: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
Traceback (most recent call last):
  File ".\frozen_graph.py", line 8, in <module>
    f = tf.function(infer).get_concrete_function(input_1=tf.TensorSpec(shape=[None, 640, 640, 3], dtype=tf.float32))
  File "C:\Users\Bleach\miniconda3\envs\TFstd\lib\site-packages\tensorflow\python\eager\def_function.py", line 1299, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "C:\Users\Bleach\miniconda3\envs\TFstd\lib\site-packages\tensorflow\python\eager\def_function.py", line 1205, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "C:\Users\Bleach\miniconda3\envs\TFstd\lib\site-packages\tensorflow\python\eager\def_function.py", line 725, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "C:\Users\Bleach\miniconda3\envs\TFstd\lib\site-packages\tensorflow\python\eager\function.py", line 2969, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "C:\Users\Bleach\miniconda3\envs\TFstd\lib\site-packages\tensorflow\python\eager\function.py", line 3361, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\Users\Bleach\miniconda3\envs\TFstd\lib\site-packages\tensorflow\python\eager\function.py", line 3196, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "C:\Users\Bleach\miniconda3\envs\TFstd\lib\site-packages\tensorflow\python\framework\func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Users\Bleach\miniconda3\envs\TFstd\lib\site-packages\tensorflow\python\eager\def_function.py", line 634, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "C:\Users\Bleach\miniconda3\envs\TFstd\lib\site-packages\tensorflow\python\framework\func_graph.py", line 977, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    C:\Users\Bleach\miniconda3\envs\TFstd\lib\site-packages\tensorflow\python\eager\function.py:1669 __call__  *
        return self._call_impl(args, kwargs)
    C:\Users\Bleach\miniconda3\envs\TFstd\lib\site-packages\tensorflow\python\eager\function.py:1685 _call_impl  **
        raise structured_err
    C:\Users\Bleach\miniconda3\envs\TFstd\lib\site-packages\tensorflow\python\eager\function.py:1678 _call_impl
        return self._call_with_structured_signature(args, kwargs,
    C:\Users\Bleach\miniconda3\envs\TFstd\lib\site-packages\tensorflow\python\eager\function.py:1756 _call_with_structured_signature
        self._structured_signature_check_missing_args(args, kwargs)
    C:\Users\Bleach\miniconda3\envs\TFstd\lib\site-packages\tensorflow\python\eager\function.py:1775 _structured_signature_check_missing_args
        raise TypeError("{} missing required arguments: {}".format(

    TypeError: signature_wrapper(*, input_tensor) missing required arguments: input_tensor
````
</details>

**Comment by captainst** [comment]
First, it seems that you have a CUDA environment problem. The 1st line of error says that you don't have CUDA11 properly installed.

If you change the line
`f = tf.function(infer).get_concrete_function(input_1=tf.TensorSpec(shape=[None, 640, 640, 3], dtype=tf.float32))`
to 
`f = tf.function(infer).get_concrete_function(input=tf.TensorSpec(shape=[None, 640, 640, 3], dtype=tf.float32))`
then probably you are able to get the frozen model. But in my case, this frozen model has problems and can't be loaded.

Still looking for a solution ...

**Comment by captainst** [comment]
First, it seems that you have a CUDA environment problem. The 1st line of error says that you don't have CUDA11 properly installed.

If you change the line
`f = tf.function(infer).get_concrete_function(input_1=tf.TensorSpec(shape=[None, 640, 640, 3], dtype=tf.float32))`
to 
`f = tf.function(infer).get_concrete_function(input=tf.TensorSpec(shape=[None, 640, 640, 3], dtype=tf.float32))`
then probably you are able to get the frozen model. But in my case, this frozen model has problems and can't be loaded.

Still looking for a solution ...

**Comment by epsilon11101** [comment]
```
import tensorflow as tf
from tensorflow.python.framework.convert_to_constants import convert_variables_to_constants_v2_as_graph
from tensorflow.lite.python.util import run_graph_optimizations, get_grappler_config
import numpy as np

def convert_saved_model_to_pb(output_node_names, input_saved_model_dir, output_graph_dir):
    from tensorflow.python.tools import freeze_graph

    output_node_names = ','.join(output_node_names)

    freeze_graph.freeze_graph(input_graph=None, input_saver=None,
                              input_binary=None,
                              input_checkpoint=None,
                              output_node_names=output_node_names,
                              restore_op_name=None,
                              filename_tensor_name=None,
                              output_graph=output_graph_dir,
                              clear_devices=None,
                              initializer_nodes=None,
                              input_saved_model_dir=input_saved_model_dir)


def save_output_tensor_to_pb():
    output_names = ['StatefulPartitionedCall']
    save_pb_model_path = 'model/freeze_graph.pb'
    model_dir = 'graph/saved_model'
    convert_saved_model_to_pb(output_names, model_dir, save_pb_model_path)


save_output_tensor_to_pb()
```

works for me

**Comment by 870746602** [comment]
> ```
> import tensorflow as tf
> from tensorflow.python.framework.convert_to_constants import convert_variables_to_constants_v2_as_graph
> from tensorflow.lite.python.util import run_graph_optimizations, get_grappler_config
> import numpy as np
> 
> def convert_saved_model_to_pb(output_node_names, input_saved_model_dir, output_graph_dir):
>     from tensorflow.python.tools import freeze_graph
> 
>     output_node_names = ','.join(output_node_names)
> 
>     freeze_graph.freeze_graph(input_graph=None, input_saver=None,
>                               input_binary=None,
>                               input_checkpoint=None,
>                               output_node_names=output_node_names,
>                               restore_op_name=None,
>                               filename_tensor_name=None,
>                               output_graph=output_graph_dir,
>                               clear_devices=None,
>                               initializer_nodes=None,
>                               input_saved_model_dir=input_saved_model_dir)
> 
> 
> def save_output_tensor_to_pb():
>     output_names = ['StatefulPartitionedCall']
>     save_pb_model_path = 'model/freeze_graph.pb'
>     model_dir = 'graph/saved_model'
>     convert_saved_model_to_pb(output_names, model_dir, save_pb_model_path)
> 
> 
> save_output_tensor_to_pb()
> ```
> 
> 为我工作



> ```
> import tensorflow as tf
> from tensorflow.python.framework.convert_to_constants import convert_variables_to_constants_v2_as_graph
> from tensorflow.lite.python.util import run_graph_optimizations, get_grappler_config
> import numpy as np
> 
> def convert_saved_model_to_pb(output_node_names, input_saved_model_dir, output_graph_dir):
>     from tensorflow.python.tools import freeze_graph
> 
>     output_node_names = ','.join(output_node_names)
> 
>     freeze_graph.freeze_graph(input_graph=None, input_saver=None,
>                               input_binary=None,
>                               input_checkpoint=None,
>                               output_node_names=output_node_names,
>                               restore_op_name=None,
>                               filename_tensor_name=None,
>                               output_graph=output_graph_dir,
>                               clear_devices=None,
>                               initializer_nodes=None,
>                               input_saved_model_dir=input_saved_model_dir)
> 
> 
> def save_output_tensor_to_pb():
>     output_names = ['StatefulPartitionedCall']
>     save_pb_model_path = 'model/freeze_graph.pb'
>     model_dir = 'graph/saved_model'
>     convert_saved_model_to_pb(output_names, model_dir, save_pb_model_path)
> 
> 
> save_output_tensor_to_pb()
> ```
> 
> works for me
 well,  I have succeeded according to your program,  but How to use it in OpenCV.

I tried the following:

cvNet = cv.dnn.readNetFromTensorflow(r"D:\Vs_Projects\py_Project\TF-Total\ObjDetection\Tensorflow\workspace\models\my_ssd_mobnet\export\saved_model\ssd_mobilenet_v2_320x320_coco17_tpu-8_freeze_graph.pb")

img = cv.imread(r"D:\Vs_Projects\py_Project\TF-Total\ObjDetection\Tensorflow\workspace\images\test\eye_20210709_100249_915.jpg")
rows = img.shape[0]
cols = img.shape[1]
cvNet.setInput(cv.dnn.blobFromImage(img, size=(300, 300), swapRB=True, crop=False))
cvOut = cvNet.forward('StatefulPartitionedCall')

but something was wrong:
cvOut = cvNet.forward('StatefulPartitionedCall')
cv2.error: OpenCV(4.5.2) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-t9hleyt8\opencv\modules\dnn\src\dnn.cpp:621: error: (-2:Unspecified error) Can't create layer "StatefulPartitionedCall" of type "StatefulPartitionedCall" in function 'cv::dnn::dnn4_v20210301::LayerData::getLayerInstance'

Thanks.

**Comment by AI-P-K** [comment]
> ```
> import tensorflow as tf
> from tensorflow.python.framework.convert_to_constants import convert_variables_to_constants_v2_as_graph
> from tensorflow.lite.python.util import run_graph_optimizations, get_grappler_config
> import numpy as np
> 
> def convert_saved_model_to_pb(output_node_names, input_saved_model_dir, output_graph_dir):
>     from tensorflow.python.tools import freeze_graph
> 
>     output_node_names = ','.join(output_node_names)
> 
>     freeze_graph.freeze_graph(input_graph=None, input_saver=None,
>                               input_binary=None,
>                               input_checkpoint=None,
>                               output_node_names=output_node_names,
>                               restore_op_name=None,
>                               filename_tensor_name=None,
>                               output_graph=output_graph_dir,
>                               clear_devices=None,
>                               initializer_nodes=None,
>                               input_saved_model_dir=input_saved_model_dir)
> 
> 
> def save_output_tensor_to_pb():
>     output_names = ['StatefulPartitionedCall']
>     save_pb_model_path = 'model/freeze_graph.pb'
>     model_dir = 'graph/saved_model'
>     convert_saved_model_to_pb(output_names, model_dir, save_pb_model_path)
> 
> 
> save_output_tensor_to_pb()
> ```
> 
> works for me

It only works when you are able to load it with OpenCV dnn module... until then you have nothing. The exported frozen model from you function is not usable... hence not working

**Comment by CometManAtGitHub** [comment]
Hi,

Thanks for checking ideas and work arounds so far.

Exporting to ONNX didn't work for me either in OpenCV 4.5.1.
You can export the frozen graph as a *.pb file via the ONNX export tool tf2onnx.convert() by adding the appropriate keyword. The OpenCV tf_text_graph_faster_rcnn.py seems not to work with this exported graph. Maybe one can load the frozen graph directly without tf_text_graph_faster_rcnn.py (not tested).

However, you can load your models and do inference with the Tensorflow C-API of Tensorflow-2.7. These resources should help:

https://github.com/AmirulOm/tensorflow_capi_sample
https://danishshres.medium.com/tensorflow-1-vs-tensorflow-2-c-api-d94982a5eb16 https://github.com/danishshres/ssd_c_api/tree/tf_2
https://danishshres.medium.com/tensorflow-1-vs-tensorflow-2-c-api-d94982a5eb16

Hope this helps.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

**Comment by Bleach665** [comment]
Yes. Most likely, it is no longer relevant.
