### ISSUE TITLE
flattening operation using tf.reshape inside @tf.function graph raises ValueError

### ISSUE THREAD

**Issue by nyanye** [tensorflow/tensorflow#46776]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): `No`
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): `Windows 10 19042.746`
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): `binary`
- TensorFlow version (use command below): `2.4.1`
- Python version: `3.8.5`
- CUDA/cuDNN version: `11.0/8.0`
- GPU model and memory: `2x RTX2080 12GB`

**Describe the current behavior**
Calling function wrapped with @tf.function and reshaping operation properly reshapes tensor with value `-1` for flattening raises `ValueError`

**Describe the expected behavior**
Calling function wrapped with @tf.function and reshaping operation properly reshapes tensor with value `-1` for flattening converts tensor into `1D` shape

**Standalone code to reproduce the issue**
```python
@tf.function
def tf_function_wrapped_function():
  reshaped = tf.reshape(tf.ones((64, 64)), -1)
```

**Full TraceBack**

```python
Traceback (most recent call last):
  File ".\tests\test_tf_dark_com_preds.py", line 36, in <module>
    test_tf_reshape()
  File ".\tests\test_tf_dark_com_preds.py", line 32, in test_get_com_preds
    assert test_tf_reshape()
  File "C:\Users\iam\.conda\envs\alyce\lib\site-packages\tensorflow\python\eager\def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\iam\.conda\envs\alyce\lib\site-packages\tensorflow\python\eager\def_function.py", line 871, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "C:\Users\iam\.conda\envs\alyce\lib\site-packages\tensorflow\python\eager\def_function.py", line 725, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "C:\Users\iam\.conda\envs\alyce\lib\site-packages\tensorflow\python\eager\function.py", line 2969, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "C:\Users\iam\.conda\envs\alyce\lib\site-packages\tensorflow\python\eager\function.py", line 3361, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\Users\iam\.conda\envs\alyce\lib\site-packages\tensorflow\python\eager\function.py", line 3196, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "C:\Users\iam\.conda\envs\alyce\lib\site-packages\tensorflow\python\framework\func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Users\iam\.conda\envs\alyce\lib\site-packages\tensorflow\python\eager\def_function.py", line 634, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "C:\Users\iam\.conda\envs\alyce\lib\site-packages\tensorflow\python\framework\func_graph.py", line 977, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:
    .\tests\test_tf_reshape.py:27 tf_function_wrapped_function  *
        reshaped = tf.reshape(tf.ones((64, 64)), -1)
    C:\Users\iam\.conda\envs\alyce\lib\site-packages\tensorflow\python\util\dispatch.py:201 wrapper  **
        return target(*args, **kwargs)
    C:\Users\iam\.conda\envs\alyce\lib\site-packages\tensorflow\python\ops\array_ops.py:195 reshape
        result = gen_array_ops.reshape(tensor, shape, name)
    C:\Users\iam\.conda\envs\alyce\lib\site-packages\tensorflow\python\ops\gen_array_ops.py:8376 reshape
        _, _, _op, _outputs = _op_def_library._apply_op_helper(
    C:\Users\iam\.conda\envs\alyce\lib\site-packages\tensorflow\python\framework\op_def_library.py:748 _apply_op_helper
        op = g._create_op_internal(op_type_name, inputs, dtypes=None,
    C:\Users\iam\.conda\envs\alyce\lib\site-packages\tensorflow\python\framework\func_graph.py:590 _create_op_internal
        return super(FuncGraph, self)._create_op_internal(  # pylint: disable=protected-access
    C:\Users\iam\.conda\envs\alyce\lib\site-packages\tensorflow\python\framework\ops.py:3528 _create_op_internal
        ret = Operation(
    C:\Users\iam\.conda\envs\alyce\lib\site-packages\tensorflow\python\framework\ops.py:2015 __init__
        self._c_op = _create_c_op(self._graph, node_def, inputs,
    C:\Users\iam\.conda\envs\alyce\lib\site-packages\tensorflow\python\framework\ops.py:1856 _create_c_op
        raise ValueError(str(e))

    ValueError: Shape must be rank 1 but is rank 0 for '{{node Reshape}} = Reshape[T=DT_FLOAT, Tshape=DT_INT32](ones, Reshape/shape)' with input shapes: [64,64], [].
```
**Findings**

1. This example raises `ValueError`
```python
@tf.function
def tf_function_wrapped_function():
  reshaped = tf.reshape(tf.ones((64, 64)), 64*64)
```

2. This example do not raise any error
```python
@tf.function
def tf_function_wrapped_function():
  reshaped = tf.reshape(tf.ones((64, 64)), [1, 64*64])
```

3. This example raises `ValueError`
```python
@tf.function
def tf_function_wrapped_function():
  reshaped = tf.reshape(tf.ones((64, 64, 64)), 64*64)
```

4. This example do not raise any error
 ```python
def tf_function_wrapped_function():
  reshaped = tf.reshape(tf.ones((64, 64)), -1)
```

5. This is an alternative way that I passed this ValueError
 ```python
@tf.function
def tf_function_wrapped_function():
  reshaped = tf.reshape(tf.ones((64, 64)), (1, 64*64))[0]
```

**Comment by Saduf2019** [comment]
@nyanye 
I ran the code shared but do not see any error as reported, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/f36092446a679ac58056dea78f2e7d15/untitled511.ipynb)

**Comment by nyanye** [comment]
@Saduf2019 I think the error is not an universal one but very specific one for my TensorFlow distribution which is compiled for Python 3.8.5 and Windows operating system.

**Comment by Saduf2019** [comment]
@nyanye
Could you please try on virtual env and let us know if you still face the issue.

**Comment by s4sarath** [comment]
The error is till there

**Comment by GabrielGlzSa** [comment]
I am using a custom constraint with tf.reshape and it causes the error when using @tf.function.

https://colab.research.google.com/drive/1nD8j4j387lyPsrucTXw1wJoxUoPXM1nx?usp=sharing
