### ISSUE TITLE
Failed when trying to install TensorFlow 2.x into my laptop. Ubuntu 18.04(Desktop). From source

### ISSUE THREAD

**Issue by 25thengineer** [tensorflow/tensorflow#46799]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04(Desktop)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: None
- TensorFlow installed from (source or binary): Source code
- TensorFlow version: 2.2
- Python version: 3.7.5
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): clang 11.0.0
- CUDA/cuDNN version: CUDA 11.2 / cuDNN 8.0.4
- GPU model and memory: GTX 1050 ti / 4 GB

**Describe the problem**
Hey, guys. I'm trying to install TensorFlow into my laptop(Dell G3 3579) but failed. There is the error information list below(**Any other info / logs**).

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```bash
sudo bazel build --config=opt --config=v2  --config=cuda //tensorflow/tools/pip_package:build_pip_package
```

**Any other info / logs**
```bash
(base) river@river-G3-3579:~/Downloads/Ubuntu_installation_essential_components/tensorflow$ sudo bazel build --config=opt --config=v2  --config=cuda //tensorflow/tools/pip_package:build_pip_package
[sudo] password for river: 
Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [cuda_clang, using_cuda, v2]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=141
INFO: Reading rc options for 'build' from /home/river/Downloads/Ubuntu_installation_essential_components/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/river/Downloads/Ubuntu_installation_essential_components/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=short_logs --config=v2
INFO: Reading rc options for 'build' from /home/river/Downloads/Ubuntu_installation_essential_components/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/local/bin/python3 --action_env PYTHON_LIB_PATH=/usr/local/lib/python3.7/site-packages --python_path=/usr/local/bin/python3 --config=xla --config=tensorrt --action_env TF_CUDA_VERSION=11.2 --action_env TF_CUDNN_VERSION=8 --action_env TF_TENSORRT_VERSION=7 --action_env TF_NCCL_VERSION=2.7 --action_env TF_CUDA_PATHS=/usr/local/cuda-11.2/,/usr/local/cuda-11.2/targets/x86_64-linux/include/,/usr/local/include/,/usr/local/lib/,/home/river/Documents/OS_unitility/TensorRT/include/,/home/river/Documents/OS_unitility/TensorRT/util --action_env CUDA_TOOLKIT_PATH=/usr/local/cuda-11.2 --action_env TF_CUDA_COMPUTE_CAPABILITIES=6.1 --action_env LD_LIBRARY_PATH=:/usr/local/jdk1.8/lib:/usr/local/jdk1.8/jre/lib:/usr/local/cuda-11.2/lib64:/usr/local/cuda-11.2/extras/Debugger/lib64:/usr/local/cuda-11.2/nvvm/lib64:/usr/local/cuda-11.2/nvvm-prev/lib64 --config=cuda_clang --action_env CLANG_CUDA_COMPILER_PATH=/usr/local/bin/clang --config=cuda_clang --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:short_logs in file /home/river/Downloads/Ubuntu_installation_essential_components/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/river/Downloads/Ubuntu_installation_essential_components/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file /home/river/Downloads/Ubuntu_installation_essential_components/tensorflow/.bazelrc: --define=with_xla_support=true
INFO: Found applicable config definition build:tensorrt in file /home/river/Downloads/Ubuntu_installation_essential_components/tensorflow/.bazelrc: --action_env TF_NEED_TENSORRT=1
INFO: Found applicable config definition build:cuda_clang in file /home/river/Downloads/Ubuntu_installation_essential_components/tensorflow/.bazelrc: --config=using_cuda --define=using_cuda_clang=true --define=using_clang=true --action_env TF_CUDA_CLANG=1
INFO: Found applicable config definition build:using_cuda in file /home/river/Downloads/Ubuntu_installation_essential_components/tensorflow/.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=1
INFO: Found applicable config definition build:cuda_clang in file /home/river/Downloads/Ubuntu_installation_essential_components/tensorflow/.bazelrc: --config=using_cuda --define=using_cuda_clang=true --define=using_clang=true --action_env TF_CUDA_CLANG=1
INFO: Found applicable config definition build:using_cuda in file /home/river/Downloads/Ubuntu_installation_essential_components/tensorflow/.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=1
INFO: Found applicable config definition build:opt in file /home/river/Downloads/Ubuntu_installation_essential_components/tensorflow/.tf_configure.bazelrc: --copt=-Wno-sign-compare --host_copt=-Wno-sign-compare --define with_default_optimizations=true
INFO: Found applicable config definition build:v2 in file /home/river/Downloads/Ubuntu_installation_essential_components/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:cuda in file /home/river/Downloads/Ubuntu_installation_essential_components/tensorflow/.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file /home/river/Downloads/Ubuntu_installation_essential_components/tensorflow/.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=1
INFO: Found applicable config definition build:linux in file /home/river/Downloads/Ubuntu_installation_essential_components/tensorflow/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
INFO: Found applicable config definition build:dynamic_kernels in file /home/river/Downloads/Ubuntu_installation_essential_components/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
INFO: Repository local_config_cuda instantiated at:
  /home/river/Downloads/Ubuntu_installation_essential_components/tensorflow/WORKSPACE:15:10: in <toplevel>
  /home/river/Downloads/Ubuntu_installation_essential_components/tensorflow/tensorflow/workspace2.bzl:13:20: in workspace
  /home/river/Downloads/Ubuntu_installation_essential_components/tensorflow/tensorflow/workspace.bzl:95:19: in tf_repositories
Repository rule cuda_configure defined at:
  /home/river/Downloads/Ubuntu_installation_essential_components/tensorflow/third_party/gpus/cuda_configure.bzl:1424:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
	File "/home/river/Downloads/Ubuntu_installation_essential_components/tensorflow/third_party/gpus/cuda_configure.bzl", line 1394, column 38, in _cuda_autoconf_impl
		_create_local_cuda_repository(repository_ctx)
	File "/home/river/Downloads/Ubuntu_installation_essential_components/tensorflow/third_party/gpus/cuda_configure.bzl", line 977, column 35, in _create_local_cuda_repository
		cuda_config = _get_cuda_config(repository_ctx, find_cuda_config_script)
	File "/home/river/Downloads/Ubuntu_installation_essential_components/tensorflow/third_party/gpus/cuda_configure.bzl", line 666, column 30, in _get_cuda_config
		config = find_cuda_config(repository_ctx, find_cuda_config_script, ["cuda", "cudnn"])
	File "/home/river/Downloads/Ubuntu_installation_essential_components/tensorflow/third_party/gpus/cuda_configure.bzl", line 643, column 41, in find_cuda_config
		exec_result = _exec_find_cuda_config(repository_ctx, script_path, cuda_libraries)
	File "/home/river/Downloads/Ubuntu_installation_essential_components/tensorflow/third_party/gpus/cuda_configure.bzl", line 637, column 19, in _exec_find_cuda_config
		return execute(repository_ctx, [python_bin, "-c", decompress_and_execute_cmd])
	File "/home/river/Downloads/Ubuntu_installation_essential_components/tensorflow/third_party/remote_config/common.bzl", line 219, column 13, in execute
		fail(
Error in fail: Repository command failed
script.py:124: DeprecationWarning: invalid escape sequence \d
  match = re.match("#define %s +(\d+)" % name, line)
script.py:260: DeprecationWarning: invalid escape sequence \d
  pattern = "Cuda compilation tools, release \d+\.\d+, V(\d+\.\d+\.\d+)"
script.py:553: DeprecationWarning: invalid escape sequence \w
  match = re.match("^(/[^/ ]*)+/lib/\w+-linux-gnu/?$", os.environ[env_name])
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/cuda-11.2/include/cuda.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/cuda-11.2/include/cublas_api.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/cuda-11.2/include/cusolver_common.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/cuda-11.2/include/curand.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/cuda-11.2/include/cufft.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/cuda-11.2/include/cusparse.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/cuda-11.2/include/cudnn.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/cuda-11.2/include/cudnn_version.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
INFO: Repository rules_cc instantiated at:
  /home/river/Downloads/Ubuntu_installation_essential_components/tensorflow/WORKSPACE:15:10: in <toplevel>
  /home/river/Downloads/Ubuntu_installation_essential_components/tensorflow/tensorflow/workspace2.bzl:13:20: in workspace
  /home/river/Downloads/Ubuntu_installation_essential_components/tensorflow/tensorflow/workspace.bzl:1001:20: in tf_repositories
Repository rule tf_http_archive defined at:
  /home/river/Downloads/Ubuntu_installation_essential_components/tensorflow/third_party/repo.bzl:131:34: in <toplevel>
INFO: Repository bazel_skylib instantiated at:
  /home/river/Downloads/Ubuntu_installation_essential_components/tensorflow/WORKSPACE:15:10: in <toplevel>
  /home/river/Downloads/Ubuntu_installation_essential_components/tensorflow/tensorflow/workspace2.bzl:13:20: in workspace
  /home/river/Downloads/Ubuntu_installation_essential_components/tensorflow/tensorflow/workspace.bzl:1065:20: in tf_repositories
Repository rule tf_http_archive defined at:
  /home/river/Downloads/Ubuntu_installation_essential_components/tensorflow/third_party/repo.bzl:131:34: in <toplevel>
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': no such package '@local_config_cuda//cuda': Repository command failed
script.py:124: DeprecationWarning: invalid escape sequence \d
  match = re.match("#define %s +(\d+)" % name, line)
script.py:260: DeprecationWarning: invalid escape sequence \d
  pattern = "Cuda compilation tools, release \d+\.\d+, V(\d+\.\d+\.\d+)"
script.py:553: DeprecationWarning: invalid escape sequence \w
  match = re.match("^(/[^/ ]*)+/lib/\w+-linux-gnu/?$", os.environ[env_name])
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/cuda-11.2/include/cuda.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/cuda-11.2/include/cublas_api.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/cuda-11.2/include/cusolver_common.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/cuda-11.2/include/curand.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/cuda-11.2/include/cufft.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/cuda-11.2/include/cusparse.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/cuda-11.2/include/cudnn.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/cuda-11.2/include/cudnn_version.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
WARNING: Target pattern parsing failed.
ERROR: no such package '@local_config_cuda//cuda': Repository command failed
script.py:124: DeprecationWarning: invalid escape sequence \d
  match = re.match("#define %s +(\d+)" % name, line)
script.py:260: DeprecationWarning: invalid escape sequence \d
  pattern = "Cuda compilation tools, release \d+\.\d+, V(\d+\.\d+\.\d+)"
script.py:553: DeprecationWarning: invalid escape sequence \w
  match = re.match("^(/[^/ ]*)+/lib/\w+-linux-gnu/?$", os.environ[env_name])
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/cuda-11.2/include/cuda.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/cuda-11.2/include/cublas_api.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/cuda-11.2/include/cusolver_common.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/cuda-11.2/include/curand.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/cuda-11.2/include/cufft.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/cuda-11.2/include/cusparse.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/cuda-11.2/include/cudnn.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/cuda-11.2/include/cudnn_version.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
INFO: Elapsed time: 7.982s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package
    Fetching @local_config_tensorrt; fetching
```

**Comment by amahendrakar** [comment]
@25thengineer,
Every TensorFlow release is compatible with certain CUDA and cuDNN versions. For more information, please take a look at the [tested build configurations](https://www.tensorflow.org/install/source#gpu).


Version | Python version | Compiler | Build tools | cuDNN | CUDA
-- | -- | -- | -- | -- | --
tensorflow-2.4.0 | 3.6-3.8 | GCC 7.3.1 | Bazel 3.1.0 | 8.0 | 11.0
tensorflow-2.3.0 | 3.5-3.8 | GCC 7.3.1 | Bazel 3.1.0 | 7.6 | 10.1
tensorflow-2.2.0 | 3.5-3.8 | GCC 7.3.1 | Bazel 2.0.0 | 7.6 | 10.1
tensorflow-2.1.0 | 2.7, 3.5-3.7 | GCC 7.3.1 | Bazel 0.27.1 | 7.6 | 10.1


Could you please try building **TensorFlow v2.4** with **CUDA 11.0** and **cuDNN 8** and let us know if you are facing the same issue. Thanks!
