### ISSUE TITLE
Problem with jit compiler:

### ISSUE THREAD

**Issue by MartinPri** [tensorflow/tensorflow#46815]
When trying your example programm:
import tensorflow as tf
import tensorflow_probability as tfp

# Pretend to load synthetic data set.
features = tfp.distributions.Normal(loc=0., scale=1.).sample(int(100e3))
labels = tfp.distributions.Bernoulli(logits=1.618 * features).sample()

# Specify model.
model = tfp.glm.Bernoulli()

# Fit model given data.
coeffs, linear_response, is_converged, num_iter = tfp.glm.fit(
    model_matrix=features[:, tf.newaxis],
    response=tf.cast(labels, dtype=tf.float32),
    model=model)
# ==> coeffs is approximately [1.618] (We're golden!)

I get the following log message:
2021-01-31 13:51:01.420629: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
Traceback (most recent call last):
  File "D:/PyProjects/PILCO-master/other.py", line 2, in <module>
    import tensorflow_probability as tfp
  File "C:\Users\Martin\Anaconda3\lib\site-packages\tensorflow_probability\__init__.py", line 20, in <module>
    from tensorflow_probability import substrates
  File "C:\Users\Martin\Anaconda3\lib\site-packages\tensorflow_probability\substrates\__init__.py", line 21, in <module>
    from tensorflow_probability.python.internal import all_util
  File "C:\Users\Martin\Anaconda3\lib\site-packages\tensorflow_probability\python\__init__.py", line 142, in <module>
    dir(globals()[pkg_name])  # Forces loading the package from its lazy loader.
  File "C:\Users\Martin\Anaconda3\lib\site-packages\tensorflow_probability\python\internal\lazy_loader.py", line 61, in __dir__
    module = self._load()
  File "C:\Users\Martin\Anaconda3\lib\site-packages\tensorflow_probability\python\internal\lazy_loader.py", line 44, in _load
    module = importlib.import_module(self.__name__)
  File "C:\Users\Martin\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Martin\Anaconda3\lib\site-packages\tensorflow_probability\python\experimental\__init__.py", line 35, in <module>
    from tensorflow_probability.python.experimental import bijectors
  File "C:\Users\Martin\Anaconda3\lib\site-packages\tensorflow_probability\python\experimental\bijectors\__init__.py", line 17, in <module>
    from tensorflow_probability.python.bijectors.ldj_ratio import inverse_log_det_jacobian_ratio
  File "C:\Users\Martin\Anaconda3\lib\site-packages\tensorflow_probability\python\bijectors\__init__.py", line 23, in <module>
    from tensorflow_probability.python.bijectors.absolute_value import AbsoluteValue
  File "C:\Users\Martin\Anaconda3\lib\site-packages\tensorflow_probability\python\bijectors\absolute_value.py", line 23, in <module>
    from tensorflow_probability.python.bijectors import bijector
  File "C:\Users\Martin\Anaconda3\lib\site-packages\tensorflow_probability\python\bijectors\bijector.py", line 35, in <module>
    from tensorflow_probability.python.math import gradient
  File "C:\Users\Martin\Anaconda3\lib\site-packages\tensorflow_probability\python\math\__init__.py", line 30, in <module>
    from tensorflow_probability.python.math.generic import log1mexp
  File "C:\Users\Martin\Anaconda3\lib\site-packages\tensorflow_probability\python\math\generic.py", line 151, in <module>
    _kahan_reduction, _kahan_reduce_bwd, _kahan_reduce_tangents)
  File "C:\Users\Martin\Anaconda3\lib\site-packages\tensorflow_probability\python\internal\variadic_reduce.py", line 122, in make_variadic_reduce
    @tf.function(jit_compile=True)
TypeError: function() got an unexpected keyword argument 'jit_compile'

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.4 ,nightly version(`2.5.0-dev20210131`) and I am not seeing any issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/3639430154b53d3fc76528f7612f5ba1/untitled648.ipynb).Thanks!
