### ISSUE TITLE
Possible bug: tf2 raise `OverflowError: Python int too large to convert to C long` for `feature_column.crossed_column`

### ISSUE THREAD

**Issue by BruceChen2017** [tensorflow/tensorflow#46929]
**System information**
window 10 python 3.7.9 tf 2.3.x cpu/gpu, for tf-gpu, cuda 10.1 

**Describe the current behavior**
This is my code
```
import tensorflow as tf
from tensorflow.keras import layers
# import pandas as pd

data = {
    "feat": [0,1,2],
    "gender": ["f", "f", "m"]
}


feat_c = tf.feature_column.categorical_column_with_identity(
    "feat", 3
)

gender_c = tf.feature_column.categorical_column_with_vocabulary_list(
    "gender", ['f', 'm']
)

feat = tf.feature_column.indicator_column(feat_c)
gender = tf.feature_column.indicator_column(gender_c)

feat_gender_cross_c = tf.feature_column.crossed_column(
    [feat_c, gender_c], 5
)

feat_gender_cross = tf.feature_column.indicator_column(feat_gender_cross_c)

feature_columns = [feat_gender_cross]

dense = layers.DenseFeatures(feature_columns)
print(dense(data))
```  

Error msg from `dense(data)`:    
```
Traceback (most recent call last):
  File "D:\Python\Python37\lib\site-packages\tensorflow\python\keras\feature_column\dense_features.py", line 167, in call
    transformation_cache, self._state_manager, training=training)
TypeError: get_dense_tensor() got an unexpected keyword argument 'training'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python\Python37\lib\site-packages\tensorflow\python\feature_column\feature_column_v2.py", line 2353, in get
    self, state_manager, training=training)
TypeError: transform_feature() got an unexpected keyword argument 'training'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python\Python37\lib\site-packages\tensorflow\python\feature_column\feature_column_v2.py", line 2353, in get
    self, state_manager, training=training)
TypeError: transform_feature() got an unexpected keyword argument 'training'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:/test.py", line 32, in <module>
    print(dense(data))
  File "D:\Python\Python37\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 985, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "D:\Python\Python37\lib\site-packages\tensorflow\python\keras\feature_column\dense_features.py", line 170, in call
    self._state_manager)
  File "D:\Python\Python37\lib\site-packages\tensorflow\python\feature_column\feature_column_v2.py", line 4158, in get_dense_tensor
    return transformation_cache.get(self, state_manager)
  File "D:\Python\Python37\lib\site-packages\tensorflow\python\feature_column\feature_column_v2.py", line 2355, in get
    transformed = column.transform_feature(self, state_manager)
  File "D:\Python\Python37\lib\site-packages\tensorflow\python\feature_column\feature_column_v2.py", line 4095, in transform_feature
    transformation_cache, state_manager)
  File "D:\Python\Python37\lib\site-packages\tensorflow\python\feature_column\feature_column_v2.py", line 3952, in get_sparse_tensors
    transformation_cache.get(self, state_manager), None)
  File "D:\Python\Python37\lib\site-packages\tensorflow\python\feature_column\feature_column_v2.py", line 2355, in get
    transformed = column.transform_feature(self, state_manager)
  File "D:\Python\Python37\lib\site-packages\tensorflow\python\feature_column\feature_column_v2.py", line 3913, in transform_feature
    hash_key=self.hash_key)
  File "D:\Python\Python37\lib\site-packages\tensorflow\python\ops\sparse_ops.py", line 677, in sparse_cross_hashed
    name=name)
  File "D:\Python\Python37\lib\site-packages\tensorflow\python\ops\sparse_ops.py", line 756, in _sparse_cross_internal
    name=name)
  File "D:\Python\Python37\lib\site-packages\tensorflow\python\ops\gen_sparse_ops.py", line 1068, in sparse_cross
    internal_type=internal_type, name=name, ctx=_ctx)
  File "D:\Python\Python37\lib\site-packages\tensorflow\python\ops\gen_sparse_ops.py", line 1146, in sparse_cross_eager_fallback
    attrs=_attrs, ctx=ctx, name=name)
  File "D:\Python\Python37\lib\site-packages\tensorflow\python\eager\execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
OverflowError: Python int too large to convert to C long
```   

I test above code  with tf2.3.x -cpu/gpu tf2.4-cpu on windows (and window server), they all give me same error. But on linux, it runs well

**Comment by amahendrakar** [comment]
@BruceChen2017,
As you've mentioned, I was able to run the code without any issues on Linux, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/944fc8b884efbb20f2d49bccae08743e/46929.ipynb). 

Could you please try running the code in a new virtual environment and let us know if you are facing the same error.

Also, please take a look at these comments [link #1](https://stackoverflow.com/a/49329034), [link #2](https://stackoverflow.com/a/52796383)  from similar StackOverflow queries and check if it helps. 

Thanks!

**Comment by BruceChen2017** [comment]
@amahendrakar   
As  I point out in last line `I test above code with tf2.3.x -cpu/gpu tf2.4-cpu on windows (and window server), they all give me same error. But on linux, it runs well`, I have tested it with tf2.3.x with cpu version and gpu version and tf2.4 with cpu on different virtual environment (created by `conda create`), even tf2.3.1 with cpu on another machine, whose system is windows server .    
I check two links above, changing to `np.array([0,1,2], dtype=np.int64)`  is also no help.

**Comment by chunduriv** [comment]
@BruceChen2017,

Sorry for the late response. I tried on windows using `TF2.9.1` and it is working as expected.

```
import tensorflow as tf
from tensorflow.keras import layers
# import pandas as pd

data = {
    "feat": [0,1,2],
    "gender": ["f", "f", "m"]
}


feat_c = tf.feature_column.categorical_column_with_identity(
    "feat", 3
)

gender_c = tf.feature_column.categorical_column_with_vocabulary_list(
    "gender", ['f', 'm']
)

feat = tf.feature_column.indicator_column(feat_c)
gender = tf.feature_column.indicator_column(gender_c)

feat_gender_cross_c = tf.feature_column.crossed_column(
    [feat_c, gender_c], 5
)

feat_gender_cross = tf.feature_column.indicator_column(feat_gender_cross_c)

feature_columns = [feat_gender_cross]

dense = layers.DenseFeatures(feature_columns)
print(dense(data))
```
 Output:
```
tf.Tensor(
[[0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]], shape=(3, 5), dtype=float32)
```

Thank you.
