### ISSUE TITLE
Tensorflow GPU Not Recognizing GPUs

### ISSUE THREAD

**Issue by bojake** [tensorflow/tensorflow#46935]
**System information**
- Windows 10 Pro 19042.746
- TensorFlow installed from conda/pip
- TensorFlow version: 2.3.0
- TensorFlow GPU version: 2.3.0
- Python version: 3.8.5
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 11.2 as of 2/4/2021
- GPU model and memory: TITAN RTX 303MiB / 24576MiB
- GPU model and memory: GeForce GTX 1070 Ti 1720MiB /  8192MiB

_tflow_select             2.3.0                       gpu
tensorboard               2.3.0              pyh4dce500_0
tensorboard-plugin-wit    1.6.0                      py_0
tensorflow                2.3.0           mkl_py38h8557ec7_0
tensorflow-base           2.3.0           eigen_py38h75a453f_0
tensorflow-estimator      2.3.0              pyheb71bc4_0
tensorflow-gpu            2.3.0                he13fc11_0

The GPUs are not displayed when querying with list_local_devices() and they are used when explicitly declaring them to be used in  with tf.device('GPU:1'). Yet, tensorflow does not complain when I reference the GPU devices, but the GPUs do not show any load whatsoever during LSTM evaluation.
```
>>> from tensorflow.python.client import device_lib
>>> print(device_lib.list_local_devices())
2021-02-04 11:37:27.094309: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 18092632807336689748
]
```
Did the following commands to verify:
```
>>> from tensorflow.python.client import device_lib
>>> print(device_lib.list_local_devices())
```
Output from nvidia-smi:

```
Thu Feb  4 11:38:59 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 461.09       Driver Version: 461.09       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  TITAN RTX          WDDM  | 00000000:1B:00.0 Off |                  N/A |
| 41%   29C    P8    16W / 280W |    303MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 107... WDDM  | 00000000:68:00.0  On |                  N/A |
|  0%   38C    P8    10W / 180W |   1720MiB /  8192MiB |      4%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

**Comment by bojake** [comment]
I also tried Theano and it barfed on trying to use version 11 of the nVidia drivers. There is no 'nvrtc64_70.dll' in the installation of version 11. There is an nvrtc.lib in the cuda install directory. Seems like none of the python libraries support version 11 of the nVidia drivers...

```
C:\miniconda3\envs\gymgpu\lib\site-packages\theano\gpuarray\dnn.py:184: UserWarning: Your cuDNN version is more recent than Theano. If you encounter problems, try updating Theano or downgrading cuDNN to a version >= v5 and <= v7.
  warnings.warn("Your cuDNN version is more recent than "
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "C:\miniconda3\envs\gymgpu\lib\site-packages\theano\gpuarray\__init__.py", line 227, in <module>
    use(config.device)
  File "C:\miniconda3\envs\gymgpu\lib\site-packages\theano\gpuarray\__init__.py", line 214, in use
    init_dev(device, preallocate=preallocate)
  File "C:\miniconda3\envs\gymgpu\lib\site-packages\theano\gpuarray\__init__.py", line 95, in init_dev
    context = pygpu.init(
  File "pygpu\gpuarray.pyx", line 658, in pygpu.gpuarray.init
  File "pygpu\gpuarray.pyx", line 587, in pygpu.gpuarray.pygpu_init
pygpu.gpuarray.GpuArrayException: b'Could not load "nvrtc64_70.dll": The specified module could not be found.\r\n'
```

**Comment by bojake** [comment]
Anaconda seems to think that it only has tensorflow 2.3:

https://anaconda.org/anaconda/tensorflow

Yet, to get nVidia version 11 support we need tensorflow 2.4 ..... where do we get that?

**Comment by bojake** [comment]
I was able to finally see the GPUs by specifying tensorflow==2.4.1 in the pip install section of my conda env yaml.
