### ISSUE TITLE
model train InvalidArgumentError:Input is empty

### ISSUE THREAD

**Issue by 2vin2vin** [tensorflow/tensorflow#46958]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 18
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.4(latest)
- Python version:latest

**Describe the current behavior**
I am about to train the model using the model_main_tf2.py and it seems to show this error and stop. I have tried it on centernet_resnet50_v1_fpn_512x512 and ssd_mobilenet_v2_fpnlite_320x320 and it is the same for both. when I ran this on AWS it did not show any errors but it did not seem to generate any checkpoints either.
**Describe the expected behavior**
Expect it to run without showing any errors

I guess the error is in the tfrecord file but all the paths and the values have been verified.
the code for generating tfrecord
writer = tf.io.TFRecordWriter(outputPath)
        total = 0
        for k in keys:

            encoded = np.asarray(Image.open(k))
            h,w,ch=encoded.shape
            filename = k.split(os.path.sep)[-1]
            encoding = filename[filename.rfind(".") + 1:]

            image = encoded.tostring() 
            xMins,xMaxs,yMins,yMaxs,textLabels,classes=[],[],[],[],[],[]
            for (label,(startX, startY, endX, endY)) in D[k]:
                endX,endY=endX-startX,endY-startY
                xMin = (startX+endX/2) / w
                xMax = endX / w
                yMin = (startY+endY/2) / h
                yMax = endY / h
                if xMin<0 or xMax<0 or yMin<0 or yMax<0 or xMin>1 or xMax>1 or yMin>1 or yMax>1:
                    continue
                xMins.append(xMin)
                xMaxs.append(xMax)
                yMins.append(yMin)
                yMaxs.append(yMax)
                textLabels.append(label.encode("utf-8"))
                classes.append(CLASSES[label])

            total += 1

            classes=np.array(classes)            
            example = tf.train.Example(features=tf.train.Features(feature={
           'image/height': int64_feature(h),
           'image/width': int64_feature(w),
           'image/filename': bytes_feature(filename.encode('utf-8')),
           'image/source_id': bytes_feature(filename.encode('utf-8')),
           'image/image_raw': bytes_feature(image),
           'image/format': bytes_feature(encoding.encode('utf-8')),
           'image/object/bbox/xmin': float_list_feature(xMins),
           'image/object/bbox/xmax': float_list_feature(xMaxs),
           'image/object/bbox/ymin': float_list_feature(yMins),
           'image/object/bbox/ymax': float_list_feature(yMaxs),
           'image/object/class/text': bytes_list_feature(textLabels),
           'image/object/class/label': int64_list_feature(classes),
 }))

            writer.write(example.SerializeToString())

        writer.close()

**Other info / logs** 
2021-02-05 23:08:11.056603: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-02-05 23:08:11.056634: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-02-05 23:08:13.273009: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-02-05 23:08:13.273186: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-02-05 23:08:13.273204: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-02-05 23:08:13.273234: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (kingsman-desktop): /proc/driver/nvidia/version does not exist
2021-02-05 23:08:13.274261: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
WARNING:tensorflow:There are non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce.
W0205 23:08:13.275029 140202867857216 cross_device_ops.py:1321] There are non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce.
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',)
I0205 23:08:13.275206 140202867857216 mirrored_strategy.py:350] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',)
INFO:tensorflow:Maybe overwriting train_steps: None
I0205 23:08:13.295096 140202867857216 config_util.py:552] Maybe overwriting train_steps: None
INFO:tensorflow:Maybe overwriting use_bfloat16: False
I0205 23:08:13.295231 140202867857216 config_util.py:552] Maybe overwriting use_bfloat16: False
WARNING:tensorflow:From /home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/object_detection/model_lib_v2.py:523: StrategyBase.experimental_distribute_datasets_from_function (from tensorflow.python.distribute.distribute_lib) is deprecated and will be removed in a future version.
Instructions for updating:
rename to distribute_datasets_from_function
W0205 23:08:13.363639 140202867857216 deprecation.py:339] From /home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/object_detection/model_lib_v2.py:523: StrategyBase.experimental_distribute_datasets_from_function (from tensorflow.python.distribute.distribute_lib) is deprecated and will be removed in a future version.
Instructions for updating:
rename to distribute_datasets_from_function
INFO:tensorflow:Reading unweighted datasets: ['/home/kingsman/deepl/records/train.tfrecord']
I0205 23:08:13.371121 140202867857216 dataset_builder.py:163] Reading unweighted datasets: ['/home/kingsman/deepl/records/train.tfrecord']
INFO:tensorflow:Reading record datasets for input file: ['/home/kingsman/deepl/records/train.tfrecord']
I0205 23:08:13.371364 140202867857216 dataset_builder.py:80] Reading record datasets for input file: ['/home/kingsman/deepl/records/train.tfrecord']
INFO:tensorflow:Number of filenames to read: 1
I0205 23:08:13.371473 140202867857216 dataset_builder.py:81] Number of filenames to read: 1
WARNING:tensorflow:num_readers has been reduced to 1 to match input file shards.
W0205 23:08:13.371576 140202867857216 dataset_builder.py:88] num_readers has been reduced to 1 to match input file shards.
WARNING:tensorflow:From /home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/object_detection/builders/dataset_builder.py:105: parallel_interleave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.experimental_deterministic`.
W0205 23:08:13.373951 140202867857216 deprecation.py:339] From /home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/object_detection/builders/dataset_builder.py:105: parallel_interleave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.experimental_deterministic`.
WARNING:tensorflow:From /home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/object_detection/builders/dataset_builder.py:237: DatasetV1.map_with_legacy_function (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.map()
W0205 23:08:13.397681 140202867857216 deprecation.py:339] From /home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/object_detection/builders/dataset_builder.py:237: DatasetV1.map_with_legacy_function (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.map()
WARNING:tensorflow:From /home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py:201: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
W0205 23:08:20.996112 140202867857216 deprecation.py:339] From /home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py:201: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
WARNING:tensorflow:From /home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py:201: sample_distorted_bounding_box (from tensorflow.python.ops.image_ops_impl) is deprecated and will be removed in a future version.
Instructions for updating:
`seed2` arg is deprecated.Use sample_distorted_bounding_box_v2 instead.
W0205 23:08:24.354368 140202867857216 deprecation.py:339] From /home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py:201: sample_distorted_bounding_box (from tensorflow.python.ops.image_ops_impl) is deprecated and will be removed in a future version.
Instructions for updating:
`seed2` arg is deprecated.Use sample_distorted_bounding_box_v2 instead.
WARNING:tensorflow:From /home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/object_detection/inputs.py:281: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
W0205 23:08:26.214364 140202867857216 deprecation.py:339] From /home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/object_detection/inputs.py:281: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
2021-02-05 23:08:28.723569: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-02-05 23:08:28.745519: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 3400075000 Hz
Traceback (most recent call last):
  File "/home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/tensorflow/python/eager/context.py", line 2113, in execution_mode
    yield
  File "/home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 733, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "/home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2579, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 6862, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input is empty.
	 [[{{node case/cond/else/_10/case/cond/cond_jpeg/else/_105/case/cond/cond_jpeg/decode_image/DecodeImage}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]] [Op:IteratorGetNext]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "object_detection/model_main_tf2.py", line 113, in <module>
    tf.compat.v1.app.run()
  File "/home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "object_detection/model_main_tf2.py", line 110, in main
    record_summaries=FLAGS.record_summaries)
  File "/home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/object_detection/model_lib_v2.py", line 566, in train_loop
    unpad_groundtruth_tensors)
  File "/home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/object_detection/model_lib_v2.py", line 344, in load_fine_tune_checkpoint
    features, labels = iter(input_dataset).next()
  File "/home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/tensorflow/python/distribute/input_lib.py", line 628, in next
    return self.__next__()
  File "/home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/tensorflow/python/distribute/input_lib.py", line 632, in __next__
    return self.get_next()
  File "/home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/tensorflow/python/distribute/input_lib.py", line 663, in get_next
    self._iterators[i].get_next_as_list_static_shapes(new_name))
  File "/home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/tensorflow/python/distribute/input_lib.py", line 1619, in get_next_as_list_static_shapes
    return self._format_data_list_with_options(self._iterator.get_next())
  File "/home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/tensorflow/python/data/ops/multi_device_iterator_ops.py", line 585, in get_next
    result.append(self._device_iterators[i].get_next())
  File "/home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 800, in get_next
    return self._next_internal()
  File "/home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 739, in _next_internal
    return structure.from_compatible_tensor_list(self._element_spec, ret)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/tensorflow/python/eager/context.py", line 2116, in execution_mode
    executor_new.wait()
  File "/home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/tensorflow/python/eager/executor.py", line 69, in wait
    pywrap_tfe.TFE_ExecutorWaitForAllPendingNodes(self._handle)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input is empty.
	 [[{{node case/cond/else/_10/case/cond/cond_jpeg/else/_105/case/cond/cond_jpeg/decode_image/DecodeImage}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]

**Comment by AdityaKane2001** [comment]
@2vin2vin  I think you can take one of your TFRecords and decode it and check whether things are getting written in TFRecords. Other thing is that TFRecords suffer data loss for large sizes (>2 GB or so). Thus, it is a  better idea to shard the data in multiple TFRecords. 
Hope this helps.

**Comment by 2vin2vin** [comment]
i converted the data to shards as you said and when I try to train I get this error

I also converted the images to jpeg and tried it but the same error shows up


Traceback (most recent call last):
  File "/home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/tensorflow/python/eager/context.py", line 2113, in execution_mode
    yield
  File "/home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 733, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "/home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2579, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 6862, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unknown image file format. One of JPEG, PNG, GIF, BMP required.
	 [[{{node case/cond/else/_10/case/cond/cond_jpeg/else/_105/case/cond/cond_jpeg/decode_image/DecodeImage}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]] [Op:IteratorGetNext]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "object_detection/model_main_tf2.py", line 113, in <module>
    tf.compat.v1.app.run()
  File "/home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "object_detection/model_main_tf2.py", line 110, in main
    record_summaries=FLAGS.record_summaries)
  File "/home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/object_detection/model_lib_v2.py", line 574, in train_loop
    unpad_groundtruth_tensors)
  File "/home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/object_detection/model_lib_v2.py", line 352, in load_fine_tune_checkpoint
    features, labels = iter(input_dataset).next()
  File "/home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/tensorflow/python/distribute/input_lib.py", line 628, in next
    return self.__next__()
  File "/home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/tensorflow/python/distribute/input_lib.py", line 632, in __next__
    return self.get_next()
  File "/home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/tensorflow/python/distribute/input_lib.py", line 663, in get_next
    self._iterators[i].get_next_as_list_static_shapes(new_name))
  File "/home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/tensorflow/python/distribute/input_lib.py", line 1619, in get_next_as_list_static_shapes
    return self._format_data_list_with_options(self._iterator.get_next())
  File "/home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/tensorflow/python/data/ops/multi_device_iterator_ops.py", line 585, in get_next
    result.append(self._device_iterators[i].get_next())
  File "/home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 800, in get_next
    return self._next_internal()
  File "/home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 739, in _next_internal
    return structure.from_compatible_tensor_list(self._element_spec, ret)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/tensorflow/python/eager/context.py", line 2116, in execution_mode
    executor_new.wait()
  File "/home/kingsman/.virtualenvs/deepl/lib/python3.6/site-packages/tensorflow/python/eager/executor.py", line 69, in wait
    pywrap_tfe.TFE_ExecutorWaitForAllPendingNodes(self._handle)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unknown image file format. One of JPEG, PNG, GIF, BMP required.
	 [[{{node case/cond/else/_10/case/cond/cond_jpeg/else/_105/case/cond/cond_jpeg/decode_image/DecodeImage}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]

**Comment by AdityaKane2001** [comment]
Two things:
1. Could you please share the source code and driver code in full? Also could you please share the directory structure of source of images and TFRecords directory?
2. Please use " ` " (the key below esc) to mark code. 😅  It becomes more readable.  Use "  ``` " to start and end large code blocks.

**Comment by 2vin2vin** [comment]
images_dir=/home/kingsman/tfod/visdr/final_images/        #  it contains both jpg and jpeg images
records_dir=/home/kingsman/tfod/visdr/records/                 #   train and test records along with label_map.pbtxt
config=/home/kingsman/models/research/centernet_resnet50_v1_fpn_512x512_coco17_tpu-8/pipeline.config

**Comment by AdityaKane2001** [comment]
Sorry but TBH, I have no experience with TensorFlow Model Garden  object detection API. I usually use [TF Hub](https://tfhub.dev/tensorflow/collections/object_detection/1) for my purposes. Please visit it. It is easy to use and you can use it on locally, on Colab or on Kaggle.

**Comment by 2vin2vin** [comment]
I have to train the model on a local system that does not have connection to the internet and I have been looking through the TF HUB but i didn't find resources on training detection models using it. If possible could you help me out with the error.
Thanks @AdityaKane2001

**Comment by AdityaKane2001** [comment]
I'll try my best. 
Can you please share the code used to make the TFRecords ?

**Comment by 2vin2vin** [comment]
The tensorflow model is .pb file that is available in the tensorflow model zoo

the tfrecord code is as follows

the k in keys is the imagefile from home directory
example:  /home/kingsman/tfod/visdr/final_images/9999998_00119_d_0000097.jpeg

```
for (dType, keys, outputPath) in datasets:
        print("[UPDATE] processing '{}'...".format(dType))
        ntotal=0
        nt=1
        outputPath='./records/'+dType+'_%.5d-of-%.5d.record'%(count,nt)                          #change this
        writer = tf.io.TFRecordWriter(outputPath)
        total, ntotal = 0 , 0
        for k in keys:

            encoded = Image.open(k)#.split("/")[-1], "rb").read()
            pilImage = encoded
            encoded = (np.array(encoded)).tostring()
            
            (w, h) = pilImage.size[:2]
            
            filename = k.split(os.path.sep)[-1]
            encoding = filename[filename.rfind(".") + 1:]
            
            image = bytes_feature(encoded)
            encoding = bytes_feature(encoding.encode('utf-8'))
            filename = bytes_feature(filename.encode('utf-8'))
            filename1 = bytes_feature(k.encode('utf-8'))
            width = int64_feature(w)
            height = int64_feature(h)
            ntotal+=1
            xMins,xMaxs,yMins,yMaxs,textLabels,classes,cl=[],[],[],[],[],[],[]
            if ntotal==20:
                writer.close()
                ntotal=0
                count+=1
                print(count)
            #    if count==2:
             #       count=1
              #      break
                outputPath='./records/'+dType+'_%.5d-of-%.5d.record'%(count,nt)                      #change this
                writer = tf.io.TFRecordWriter(outputPath)
            for (label, (startX, startY, endX, endY)) in D[k]:
                # if image sizes are different w1 and h1 are data dimensions
 #               startX,startY,endX,endY=startX/w1*w,startY/h1*h,endX/w1*w,endY/h1*h
                xMin = startX / w
                xMax = endX / w
                yMin = startY / h
                yMax = endY / h

                xMins.append(xMin)
                xMaxs.append(xMax)
                yMins.append(yMin)
                yMaxs.append(yMax)
                textLabels.append(label.encode("utf-8"))
                classes.append(CLASSES[label])
#                difficult.append(0)

                total += 1
            #,
 #           "image/object/difficult": difficult}
            #print(classes)
            features = tf.train.Features(feature = {
            "image/height": height,
            "image/width": width,
            "image/filename": filename,
            "image/source_id": filename1,
            "image/encoded": image,
            "image/format": encoding,
            "image/object/bbox/xmin": float_list_feature(xMins),
            "image/object/bbox/xmax": float_list_feature(xMaxs),
            "image/object/bbox/ymin": float_list_feature(yMins),
            "image/object/bbox/ymax": float_list_feature(yMaxs),
            "image/object/class/text": bytes_list_feature(textLabels),
            "image/object/class/label": int64_list_feature(classes)})
            example = tf.train.Example(features=features)

            writer.write(example.SerializeToString())

        writer.close()
        print("[UPDATE] {} examples saved for '{}'".format(total, dType))

```

**Comment by amahendrakar** [comment]
@2vin2vin.
In order to reproduce the issue reported here, could you please share the Python script/notebook you are running and also the dataset you are using. Thanks!

**Comment by 2vin2vin** [comment]
I am using the Visdrone dataset, performing augmentation, generating tf records and running the training like mentioned in the below link
https://gilberttanner.com/blog/tensorflow-object-detection-with-tensorflow-2-creating-a-custom-model

**Comment by amahendrakar** [comment]
@2vin2vin,
The code provided is fairly complex hence it would be difficult for us to pinpoint the issue. Could you please get the example down to the simplest possible repro? That will allow us to determine the source of the issue easily. 

You can also run your code on [Google Colab](https://colab.research.google.com/) and share the notebook with us. Thanks!

**Comment by 2vin2vin** [comment]
@amahendrakar,
it started working for me when I changed the tfrecord code of the image.
earlier: encoded = Image.open(k)
            image=bytes_feature(encoded)

now: image=bytes_feature(open('filename','rb').read())

also in the config file I changed the fine tune checkpoint to none rather than pointing it to the checkpoint
