### ISSUE TITLE
Confiuguration error 

### ISSUE THREAD

**Issue by robertorovella91** [tensorflow/tensorflow#46978]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: Linux Ubuntu 18 with qemu and docker aarch64 image for jetson platform

- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.14.0
- Python version: 3
 
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): gcc (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0
- CUDA/cuDNN version: 10.2 8
- GPU model and memory: gtx 1070

Hi everyone I have a problem in the configuration phase. When asking for Cuda and cudnn library I get this error:
Traceback (most recent call last):
  File "third_party/gpus/find_cuda_config.py", line 497, in <module>
    main()
  File "third_party/gpus/find_cuda_config.py", line 489, in main
    for key, value in sorted(find_cuda_config().items()):
  File "third_party/gpus/find_cuda_config.py", line 468, in find_cuda_config
    result.update(_find_cudnn_config(cudnn_paths, cudnn_version))
  File "third_party/gpus/find_cuda_config.py", line 346, in _find_cudnn_config
    get_header_version)
  File "third_party/gpus/find_cuda_config.py", line 235, in _find_header
    required_version, get_version)
  File "third_party/gpus/find_cuda_config.py", line 224, in _find_versioned_file
    actual_version = get_version(file)
  File "third_party/gpus/find_cuda_config.py", line 342, in get_header_version
    return ".".join(version)
  File "third_party/gpus/find_cuda_config.py", line 341, in <genexpr>
    for name in ("CUDNN_MAJOR", "CUDNN_MINOR", "CUDNN_PATCHLEVEL"))
  File "third_party/gpus/find_cuda_config.py", line 123, in _get_header_version
    for line in io.open(path, "r", encoding="utf-8").readlines():
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 18: invalid start byte
Asking for detailed CUDA configuration...

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Please specify the comma-separated list of base paths to look for CUDA libraries and headers. [Leave empty to use the default]: /folder_shared/lib64,/usr/local/cuda-10.2/targets/aarch64-linux/include/,/usr/local/cuda-10.2/bin/,/usr/local/cuda-10.2/nvvm/libdevice,/usr/local/cuda-10.2/nvvmx/libdevice,/usr/local/cuda-10.2/nvvmx/libdevice/libdevice.10.bc,/usr/local/cuda-10.2,/usr/include,/folder_shared,/folder_shared/cudnn8/

**Comment by ravikyram** [comment]
@robertorovella91 

Please, see tested build configuration from [here](https://www.tensorflow.org/install/source#gpu). Thanks!
