### ISSUE TITLE
freeze graph from .ckpt to .pd file fail

### ISSUE THREAD

**Issue by civilmanxx** [tensorflow/tensorflow#4698]
Now i am using tensor flow to train inception v1 (in slim model folder) on my data set. i am using the latest nightly build 0.10.
 i want to convert the big .ckpt to .pd file. i try "freeze graph" in the tool box but fail.

the command is: (the graph format is default pbtxt)

bazel-bin/tensorflow/python/tools/freeze_graph --input_graph=/home/DeepLearning/tensorflow/v1/graph.pbtxt --input_checkpoint=/home/DeepLearning/tensorflow/v1/model.ckpt-1315 --output_graph=/home/DeepLearning/tensorflow/v1/test.pb --output_node_names=softmax
---------------------------------------------------------------------------

the error message is:

Traceback (most recent call last):
  File "/home/DeepLearning/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 134, in <module>
    tf.app.run()
  File "/home/DeepLearning/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/home/DeepLearning/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 131, in main
    FLAGS.output_graph, FLAGS.clear_devices, FLAGS.initializer_nodes)
  File "/home/DeepLearning/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 103, in freeze_graph
    _ = tf.import_graph_def(input_graph_def, name="")
  File "/home/DeepLearning/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/framework/importer.py", line 252, in import_graph_def
    op_def = op_dict[node.op]
**KeyError: u'RestoreV2'**

---------------------------------------------

I am not clear about **KeyError: u'RestoreV2**. is there anyone meet the same issue?

thanks!

**Comment by civilmanxx** [comment]
I pull the lastest code of tensorflow and rebuild by running: 
bazel build tensorflow/python/tools:freeze_graph 
the issue is gone.
