### ISSUE TITLE
post-quantizing and loading a a trained model in keras using tflite issue

### ISSUE THREAD

**Issue by zubaidah93** [tensorflow/tensorflow#47097]
**System information**
- google colab ( intended to be used on raspberry pi)
- TensorFlow 1.14
- python 2.7 ( i know its old and not supported but i have to use it) 
-

**Provide the text output from tflite_convert**
```
/usr/local/lib/python2.7/dist-packages/tensorflow_core/lite/python/convert.pyc in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)

ConverterError: See console for info.
2021-02-11 22:29:16.405546: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: AddV2
2021-02-11 22:29:16.424912: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 57 operators, 100 arrays (0 quantized)
2021-02-11 22:29:16.425598: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 57 operators, 100 arrays (0 quantized)
2021-02-11 22:29:16.427571: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 25 operators, 53 arrays (0 quantized)
2021-02-11 22:29:17.452115: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 2: 24 operators, 52 arrays (0 quantized)
2021-02-11 22:29:17.452530: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 3: 23 operators, 50 arrays (0 quantized)
2021-02-11 22:29:17.452823: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Group bidirectional sequence lstm/rnn: 23 operators, 50 arrays (0 quantized)
2021-02-11 22:29:17.453000: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 23 operators, 50 arrays (0 quantized)
2021-02-11 22:29:17.453320: I tensorflow/lite/toco/allocate_transient_arrays.cc:345] Total transient array allocated size: 16777216 bytes, theoretical optimal value: 16777216 bytes.
2021-02-11 22:29:17.453614: E tensorflow/lite/toco/toco_tooling.cc:456] We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CONV_2D, FULLY_CONNECTED, MAX_POOL_2D, MUL, SOFTMAX. Here is a list of operators for which you will need custom implementations: AddV2.
Traceback (most recent call last):
  File "/usr/local/bin/toco_from_protos", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 59, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 33, in execute
    output_str = tensorflow_wrap_toco.TocoConvert(model_str, toco_str, input_str)
Exception: We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CONV_2D, FULLY_CONNECTED, MAX_POOL_2D, MUL, SOFTMAX. Here is a list of operators for which you will need custom implementations: AddV2.

```

**Standalone code to reproduce the issue** 

# WHOLE MODEL
import tensorflow as tf
from tensorflow import lite
from tensorflow import keras
from keras.models import load_model
import os

model=keras.models.load_model('/content/drive/MyDrive/disease classification/AGAIN/end_model_acc1.h5')
allow_custom_ops=True 
#--enable_select_tf_ops
converter = tf.lite.TFLiteConverter.from_keras_model(model)

tfmodel = converter.convert()
open ("model.tflite" , "wb") .write(tfmodel)

#loading quantized model and interprete it 

interpreter = tf.lite.Interpreter(model_content=tfmodel)
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()
output_details= interpreter.get_output_details()
#interpreter.resize_tensor_input(input_details[0]['index'],(10, 224, 224, 3))
#interpreter.resize_tensor_input(output_details[0]['index'], (15, 224,224,3))
interpreter.allocate_tensors()
os.chdir("/content/drive/MyDrive/disease classification/The End/") 
!pwd

**Any other info / logs**
the model is used for image classification of 10 classes using CNN to be performed on the raspberry pi , i would appreciate any feedback regarding the process as i am new to this. thank you.

**Comment by abattery** [comment]
There is an TF operator, that isn't covered by TFLite builtin kernels. You can enable select TF option for this case. https://www.tensorflow.org/lite/guide/ops_select

```
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
tfmodel = converter.convert()
```

**Comment by zubaidah93** [comment]
Thank you very much! it worked.
