### ISSUE TITLE
TFLite GPU Delegate Fails 

### ISSUE THREAD

**Issue by jasonw247** [tensorflow/tensorflow#47168]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Google Pixel XL
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.4.0,  2.5.0-dev20210212
- Python version: 3.6.12
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 7.1.3-1+cuda11.0
- GPU model and memory: NVIDIA Tesla V100, 16GB

**Describe the current behavior**
I am attempting to use the GPU delegate with a TFLite model on an Android device. I am testing using the benchmark app from: https://www.tensorflow.org/lite/performance/measurement.

I am able to benchmark performance using the default (None/CPU) and XNNPACK delegates, but am running into an error when attempting to use the GPU delegate (--use_gpu=true). 

With an undefined (None) batch size, I get the error: 
```
Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.
```

With a batch size of 1 (to avoid dynamic shapes):
```python
inputs = tf.keras.Input(shape=(48,), dtype=tf.int32, batch_size=1)
```

or forcing the input shape after saving:
``` python
model = tf.saved_model.load(save_dir)
concrete_func = model.signatures[
  tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY]

# set to batch size 1 so there are no dynamic shapes
concrete_func.inputs[0].set_shape([1, 48])
```

I am getting: 
```
02-15 10:04:31.620 32268 32268 I tflite_BenchmarkModelActivity: Running TensorFlow Lite benchmark with args: --graph=/data/local/tmp/test.tflite               --num_threads=4              --use_gpu=true
02-15 10:04:31.628 32268 32268 I tflite  : Initialized TensorFlow Lite runtime.
02-15 10:04:31.630 32268 32268 I tflite  : Created TensorFlow Lite delegate for GPU.
02-15 10:04:31.631 32268 32268 E tflite  : Following operations are not supported by GPU delegate:
02-15 10:04:31.631 32268 32268 E tflite  : DEQUANTIZE:
02-15 10:04:31.631 32268 32268 E tflite  : GATHER: Operation is not supported.
02-15 10:04:31.631 32268 32268 E tflite  : 233 operations will run on the GPU, and the remaining 2 operations will run on the CPU.
02-15 10:04:31.632 32268 32268 E tflite  : TfLiteGpuDelegate Init: ADD: Expected a 3D tensor of shape HxWxC or a 4D tensor of shape 1xHxWxC but got 48x100
02-15 10:04:31.632 32268 32268 I tflite  : Created 0 GPU delegate kernels.
02-15 10:04:31.632 32268 32268 E tflite  : TfLiteGpuDelegate Prepare: delegate is not initialized
02-15 10:04:31.632 32268 32268 E tflite  : Node number 235 (TfLiteGpuDelegateV2) failed to prepare.
02-15 10:04:31.632 32268 32268 E tflite  : Restored original execution plan after delegate application failure.
```
**Describe the expected behavior**
The GPU delegate does not raise an error, and the delegate is successful.

**Standalone code to reproduce the issue**
``` python
import numpy as np
import tensorflow as tf

# from: https://github.com/keras-team/keras-io/blob/master/examples/nlp/text_classification_with_transformer.py
class TransformerBlock(tf.keras.layers.Layer):
    def __init__(self, embed_dim, num_heads, ff_dim, rate=0.1):
        super(TransformerBlock, self).__init__()
        self.att = tf.keras.layers.MultiHeadAttention(num_heads=num_heads, key_dim=embed_dim)
        self.ffn = tf.keras.Sequential(
            [tf.keras.layers.Dense(ff_dim, activation="relu"), tf.keras.layers.Dense(embed_dim),]
        )
        self.layernorm1 = tf.keras.layers.LayerNormalization(epsilon=1e-6)
        self.layernorm2 = tf.keras.layers.LayerNormalization(epsilon=1e-6)
        self.dropout1 = tf.keras.layers.Dropout(rate)
        self.dropout2 = tf.keras.layers.Dropout(rate)

    def call(self, inputs, training):
        attn_output = self.att(inputs, inputs)
        attn_output = self.dropout1(attn_output, training=training)
        out1 = self.layernorm1(inputs + attn_output)
        ffn_output = self.ffn(out1)
        ffn_output = self.dropout2(ffn_output, training=training)
        return self.layernorm2(out1 + ffn_output)

# from: https://github.com/keras-team/keras-io/blob/master/examples/nlp/text_classification_with_transformer.py
class TokenAndPositionEmbedding(tf.keras.layers.Layer):
    def __init__(self, maxlen, vocab_size, embed_dim):
        super(TokenAndPositionEmbedding, self).__init__()
        self.token_emb = tf.keras.layers.Embedding(input_dim=vocab_size, output_dim=embed_dim)
        self.pos_emb = tf.keras.layers.Embedding(input_dim=maxlen, output_dim=embed_dim)

    def call(self, x):
        maxlen = tf.shape(x)[-1]
        positions = tf.range(start=0, limit=maxlen, delta=1)
        positions = self.pos_emb(positions)
        x = self.token_emb(x)
        return x + positions
    
X_train = np.ones((10, 48))
X_test = np.ones((10,48))
y_train = np.ones(10)
y_test = np.ones(10)

inputs = tf.keras.Input(shape=(48,), dtype=tf.int32, batch_size=1)

embeddings = TokenAndPositionEmbedding(
            maxlen=48, vocab_size=10, embed_dim=100)(inputs)

sequence_layer = TransformerBlock(100, 12, 16)(embeddings)
global_pool = tf.keras.layers.GlobalAveragePooling1D()(sequence_layer)
dense_layer = tf.keras.layers.Dense(16, activation='relu')(global_pool)
pred = tf.keras.layers.Dense(2, activation='softmax', name="prediction")(dense_layer)

model = tf.keras.Model(inputs, outputs=pred)

model.compile(optimizer="Adam",
              loss=tf.keras.losses.SparseCategoricalCrossentropy(),
              metrics=["accuracy"],
             )

model.fit(
    x=X_train,
    y=y_train,
    epochs=1,
    steps_per_epoch=10,
    verbose=1,
)

converter = tf.lite.TFLiteConverter.from_keras_model(model)

converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_types = [tf.float16]

converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS,
]

tflite_model = converter.convert()

with open('models/test.tflite', 'wb') as f:
    f.write(tflite_model)
```

**Comment by teijeong** [comment]
colab: https://colab.research.google.com/gist/teijeong/502d046bda89a20675628928becfd01e/47168.ipynb

**Comment by teijeong** [comment]
Ran benchmark with generated model with Galaxy S10e (Exynos) and Pixel 2 XL, and both works fine with latest benchmark apk. Can you make sure if your TFLite runtime is up to date?

**Comment by jasonw247** [comment]
I redownloaded the latest apk (https://storage.googleapis.com/tensorflow-nightly-public/prod/tensorflow/release/lite/tools/nightly/latest/android_aarch64_benchmark_model.apk) and tested on Pixel XL and Pixel 3a, both gave the following error:

```

**Comment by impjdi** [comment]
Many of the GPU ops are optimized for the image domain and works in a 3D mode with width height channel dimensions.  You are doing text classification with a 2D input tensor (that's what I assume from the error message; I haven't generated or taken a look at the .tflite model).  Is it possible to insert a RESHAPE op to convert 48x100 to e.g. 1x48x100 ?

**Comment by jasonw247** [comment]
I've tried using both `reshape` and a combination of `expand_dims` and `squeeze` (looking at: https://www.tensorflow.org/mlir/tfl_ops for compatibility). I am able to get both approaches to convert using `tf.lite.OpsSet.SELECT_TF_OPS`

I'm not able to test it in the flex delegate apk (https://storage.googleapis.com/tensorflow-nightly-public/prod/tensorflow/release/lite/tools/nightly/latest/android_aarch64_benchmark_model_plus_flex.apk), as I'm getting an error:
```
02-17 10:19:39.294 19111 19111 I tflite_BenchmarkModelActivity: Running TensorFlow Lite benchmark with args: --graph=/data/local/tmp/test.tflite               --num_threads=4              --use_gpu=true
02-17 10:19:39.307 19111 19111 E AndroidRuntime: Process: org.tensorflow.lite.benchmark, PID: 19111
02-17 10:19:39.307 19111 19111 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.tensorflow.lite.benchmark-gjEn3C-N8sQzuah5t0ZG-w==/base.apk"],nativeLibraryDirectories=[/data/app/org.tensorflow.lite.benchmark-gjEn3C-N8sQzuah5t0ZG-w==/lib/arm64, /system/fake-libs64, /data/app/org.tensorflow.lite.benchmark-gjEn3C-N8sQzuah5t0ZG-w==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/product/lib64]]] couldn't find "libtensorflowlite_benchmark.so"
02-17 10:19:39.307 19111 19111 E AndroidRuntime: 	at org.tensorflow.lite.benchmark.BenchmarkModel.<clinit>(BenchmarkModel.java:21)
02-17 10:19:39.307 19111 19111 E AndroidRuntime: 	at org.tensorflow.lite.benchmark.BenchmarkModel.run(BenchmarkModel.java:28)
02-17 10:19:39.307 19111 19111 E AndroidRuntime: 	at org.tensorflow.lite.benchmark.BenchmarkModelActivity.onCreate(BenchmarkModelActivity.java:46)
02-17 10:19:39.317   926  3811 W ActivityTaskManager:   Force finishing activity org.tensorflow.lite.benchmark/.BenchmarkModelActivity
02-17 10:19:39.349   926  1412 I ActivityManager: Process org.tensorflow.lite.benchmark (pid 19111) has died: prcp TPSL
02-17 10:19:39.593   926  1013 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{e2543f1 u0 org.tensorflow.lite.benchmark/.BenchmarkModelActivity t-1 f}
```

**Comment by OleksandrGrument** [comment]
@jasonw247 Hi try to use 2.3.0 gpu delegate. It looks like bug in 2.4.0 and 2.5.0. I have the same error.
https://github.com/tensorflow/tensorflow/issues/45845

**Comment by terryheo** [comment]
BTW, if you're using tf-nightly you can use Model Analyzer API to check which node has the compatibility issue.

```
import tensorflow as tf

tf.lite.experimental.Analyzer.analyze(model_path='model.tflite', gpu_compatibility=True)
```

**Comment by pjpratik** [comment]
@jasonw247 I was able to run this in TF 2.11 without any error.  Could you please check this [gist](https://colab.research.google.com/gist/pjpratik/ec4a2ed37cf1172a78c8487c32868bce/47168.ipynb) and let us know if it helps. Thank you.
