### ISSUE TITLE
`ValueError: None values not supported` when using the Estimator API

### ISSUE THREAD

**Issue by Xaenalt** [tensorflow/tensorflow#47173]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: Yes
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Fedora 33
-   **TensorFlow installed from (source or binary)**: Attempted both
-   **TensorFlow version (use command below)**: Attempted v2.4.1-0-g85c8b2a817f 2.4.1 (source) and v2.4.0-49-g85c8b2a817f 2.4.1 (binary)
-   **Python version**: Python 3.9.1 and Python 3.7.7 :: Intel(R) Corporation
-   **Bazel version (if compiling from source)**: Used Bazelisk, which listed 3.1.0 as the version it's using
-   **GCC/Compiler version (if compiling from source)**: gcc (GCC) 10.2.1 20201125 (Red Hat 10.2.1-9)
-   **CUDA/cuDNN version**: N/A
-   **GPU model and memory**: N/A
-   **Exact command to reproduce**: Attached code snippet

### Describe the problem
I have been attempting to use TensorFlow to build a random forest classifier, in this case using the built-in boosted trees classifier. I have attempted two different datasets, but the same general idea in the code. After these attempts, I'm thinking I might be hitting a bug of some sort
The code errors out with: `ValueError: None values not supported.` in a way that's extremely unclear what's going on

Test1.py:
```
Traceback (most recent call last):
  File "/home/user/tensorflow-random-forest/test.py", line 38, in <module>
    estimator.train(input_fn=create_input_fn('train'), max_steps=100)
  File "/usr/local/lib/python3.9/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.9/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1175, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.9/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1203, in _train_model_default
    estimator_spec = self._call_model_fn(features, labels, ModeKeys.TRAIN,
  File "/usr/local/lib/python3.9/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1163, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/tensorflow_estimator/python/estimator/canned/boosted_trees.py", line 2081, in _model_fn
    return _bt_model_fn(
  File "/usr/local/lib/python3.9/site-packages/tensorflow_estimator/python/estimator/canned/boosted_trees.py", line 1259, in _bt_model_fn
    batch_size = tf.compat.v1.shape(labels)[0]
  File "/usr/local/lib64/python3.9/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib64/python3.9/site-packages/tensorflow/python/ops/array_ops.py", line 649, in shape
    return shape_internal(input, name, optimize=True, out_type=out_type)
  File "/usr/local/lib64/python3.9/site-packages/tensorflow/python/ops/array_ops.py", line 673, in shape_internal
    input = ops.convert_to_tensor(input)
  File "/usr/local/lib64/python3.9/site-packages/tensorflow/python/profiler/trace.py", line 163, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib64/python3.9/site-packages/tensorflow/python/framework/ops.py", line 1540, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib64/python3.9/site-packages/tensorflow/python/framework/constant_op.py", line 339, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib64/python3.9/site-packages/tensorflow/python/framework/constant_op.py", line 264, in constant
    return _constant_impl(value, dtype, shape, name, verify_shape=False,
  File "/usr/local/lib64/python3.9/site-packages/tensorflow/python/framework/constant_op.py", line 281, in _constant_impl
    tensor_util.make_tensor_proto(
  File "/usr/local/lib64/python3.9/site-packages/tensorflow/python/framework/tensor_util.py", line 445, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.
```

Test2.py:
```
Traceback (most recent call last):
  File "/home/user/tensorflow-random-forest/test2.py", line 61, in <module>
    estimator.train(input_fn=create_input_fn(train=True))
  File "/usr/local/lib/python3.9/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.9/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1175, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.9/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1203, in _train_model_default
    estimator_spec = self._call_model_fn(features, labels, ModeKeys.TRAIN,
  File "/usr/local/lib/python3.9/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1163, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/tensorflow_estimator/python/estimator/canned/boosted_trees.py", line 2233, in _model_fn
    return _bt_model_fn(
  File "/usr/local/lib/python3.9/site-packages/tensorflow_estimator/python/estimator/canned/boosted_trees.py", line 1222, in _bt_model_fn
    batch_size = tf.compat.v1.shape(labels)[0]
  File "/usr/local/lib64/python3.9/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib64/python3.9/site-packages/tensorflow/python/ops/array_ops.py", line 649, in shape
    return shape_internal(input, name, optimize=True, out_type=out_type)
  File "/usr/local/lib64/python3.9/site-packages/tensorflow/python/ops/array_ops.py", line 673, in shape_internal
    input = ops.convert_to_tensor(input)
  File "/usr/local/lib64/python3.9/site-packages/tensorflow/python/profiler/trace.py", line 163, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib64/python3.9/site-packages/tensorflow/python/framework/ops.py", line 1540, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib64/python3.9/site-packages/tensorflow/python/framework/constant_op.py", line 339, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib64/python3.9/site-packages/tensorflow/python/framework/constant_op.py", line 264, in constant
    return _constant_impl(value, dtype, shape, name, verify_shape=False,
  File "/usr/local/lib64/python3.9/site-packages/tensorflow/python/framework/constant_op.py", line 281, in _constant_impl
    tensor_util.make_tensor_proto(
  File "/usr/local/lib64/python3.9/site-packages/tensorflow/python/framework/tensor_util.py", line 445, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.
```

### Source code / logs
These two snippets produce the same type of error, it's possible I'm making some fundamental coding mistake, but I'm not seeing how.
(github wanted me to change the .py to .txt to attach them, just remove to run)
[test2.py.txt](https://github.com/tensorflow/tensorflow/files/5984443/test2.py.txt)
[test.py.txt](https://github.com/tensorflow/tensorflow/files/5984444/test.py.txt)

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/70710486ff57db6a9cafe8629dbcf4cf/47173.ipynb). Thanks!

**Comment by Xaenalt** [comment]
Does that mean I found an actual bug rather than it just being a coding issue? o.O

**Comment by rmothukuru** [comment]
@Xaenalt,
Can you please confirm if you have gone through the instructions specified in the [Estimator Guide](https://www.tensorflow.org/guide/estimator) and have build your models accordingly? Thanks!

**Comment by Xaenalt** [comment]
Well, I had thought so, the only major difference was using TFDS, which I had assumed set the label_name field to inform the model of what the labels are. Though the error hasn't given me much to go on
