### ISSUE TITLE
Error with running tensorflow after installation

### ISSUE THREAD

**Issue by Zahra-zso** [tensorflow/tensorflow#47188]
I just installed tensorflow 2.4.1.  I use python 3.6 and there were no problem when I installed tensorflow. But the error comes up exactly after importing Tensorflow when I run:

import tensorflow as tf
I will get:

ITraceback (most recent call last):
  File "C:\Users\Python36\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/MultiCNN.py", line 9, in <module>
    import tensorflow as tf
  File "C:\Users\Python36\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Python36\site-packages\tensorflow\python\__init__.py", line 39, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "C:\Users\Python36\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Python36\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

**Comment by amahendrakar** [comment]
@Zahra-zso,
You might be facing this issue because of the following reasons

- You are running 32-bit Python or 32-bit OS
- You have not installed the [Microsoft Visual C++ Redistributable](https://support.microsoft.com/help/2977003/the-latest-supported-visual-c-downloads) package
- Your CPU does not support AVX instructions. 

Please take a look at the [system requirements](https://www.tensorflow.org/install/pip#system-requirements) and check if you have the correct dependencies installed.

Also, check this similar duplicate issue: #36167

Thanks!
