### ISSUE TITLE
Conv2D operator not XLA compliant with Windows 10

### ISSUE THREAD

**Issue by jplu** [tensorflow/tensorflow#47184]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.1
- Python version: conda 3.8.5
- CUDA/cuDNN version: 11.0
- GPU model and memory: RTX 2080 super

**Describe the current behavior**
The following error is raised, either the code is run on CPU or GPU:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\snake\miniconda3\envs\transformers\lib\site-packages\tensorflow\python\eager\def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\snake\miniconda3\envs\transformers\lib\site-packages\tensorflow\python\eager\def_function.py", line 894, in _call
    return self._concrete_stateful_fn._call_flat(
  File "C:\Users\snake\miniconda3\envs\transformers\lib\site-packages\tensorflow\python\eager\function.py", line 1918, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "C:\Users\snake\miniconda3\envs\transformers\lib\site-packages\tensorflow\python\eager\function.py", line 555, in call
    outputs = execute.execute(
  File "C:\Users\snake\miniconda3\envs\transformers\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Function invoked by the following node is not compilable: {{node __inference_test_9}} = __inference_test_9[_XlaMustCompile=true, config_proto="\n\007\n\003CPU\020\001\n\007\n\003GPU\020\0012\005*\0010J\0008\001\202\001\000", executor_type=""](dummy_input, dummy_input).
Uncompilable nodes:
Conv2D: unsupported op: No registered 'Conv2D' OpKernel for XLA_GPU_JIT devices compatible with node {{node Conv2D}}
        Stacktrace:
                Node: __inference_test_9, function:
                Node: Conv2D, function: __inference_test_9
 [Op:__inference_test_9]
```

**Describe the expected behavior**
I'm expecting to have the `Conv2D` op compliant with XLA on GPU and CPU as stated in the TF documentation https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/tf2xla/g3doc/gpu_supported_ops.md and get the following result:
```
<tf.Tensor: shape=(1, 4, 4, 2), dtype=float32, numpy=
array([[[[10.        ,  1.8999999 ],
         [ 9.999999  ,  2.1999998 ],
         [ 5.999999  ,  1.5999999 ],
         [ 6.        ,  2.        ]],

        [[11.999998  ,  1.3999999 ],
         [14.999998  ,  2.1999998 ],
         [12.999999  ,  2.6999998 ],
         [12.999998  ,  1.7       ]],

        [[ 6.999999  ,  1.6999998 ],
         [10.999998  ,  1.3       ],
         [15.999998  ,  1.3       ],
         [ 7.        ,  1.        ]],

        [[10.        ,  0.59999996],
         [ 7.        ,  1.3999999 ],
         [ 4.        ,  1.5       ],
         [ 6.9999995 ,  1.4000001 ]]]], dtype=float32)>
```

**Standalone code to reproduce the issue**
Here a piece of code to reproduce the issue:
```python
import tensorflow as tf
import numpy as np

x_in = np.array([[
  [[2], [1], [2], [0], [1]],
  [[1], [3], [2], [2], [3]],
  [[1], [1], [3], [3], [0]],
  [[2], [2], [0], [1], [1]],
  [[0], [0], [3], [1], [2]], ]])

kernel_in = np.array([
 [ [[2, 0.1]], [[3, 0.2]] ],
 [ [[0, 0.3]],[[1, 0.4]] ], ])

x = tf.constant(x_in, dtype=tf.float32)
kernel = tf.constant(kernel_in, dtype=tf.float32)

@tf.function(experimental_compile=True)
def run_xla():
  return tf.nn.conv2d(x, kernel, strides=[1, 1, 1, 1], padding='VALID')

run_xla()
```

This issue appears only on Windows, but not on Linux, then it might be an OS related issue.

**Comment by amahendrakar** [comment]
As mentioned, I was able to run the code on Colab (Linux) without any issues. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/5eaf0d636d9d7cb831195bacdf88a611/47184.ipynb). Thanks!

**Comment by jplu** [comment]
@amahendrakar Thanks but as stated in the title I'm not on Linux, but on Windows, you cannot reproduce this bug in colab.

**Comment by sachinprasadhs** [comment]
Can you try again by creating virtual environment with latest Tensorflow version on your Windows machine and let us know if you still face the issue. Thanks!

**Comment by jplu** [comment]
Thanks a lot! It works as expected.
