### ISSUE TITLE
bazel test numpy issue: RuntimeError: module compiled against API version a but this version of numpy is 7

### ISSUE THREAD

**Issue by yjernite** [tensorflow/tensorflow#472]
Hello everyone,

  I just wrote my own op, and finally got it to compile, but I'm having trouble running bazel test. Specifically, I get the following error:

> RuntimeError: module compiled against API version a but this version of numpy is 7

I am surprised as I was able to compile tensorflow with bazel, and import it without any problems. Any ideas as to what might be causing this? My test is the following:

```python
import tensorflow as tf

class ChainCRFTest(tf.test.TestCase):
    def testChainCRF(self):
        with self.test_session():
            pre_pots = [[[1, 3, 1], [4, 1, 2], [2, 1, 1]],
                        [[2, 2, 1], [3, 1, 1], [1, 2, 3]],
                        [[3, 1, 1], [2, 1, 2], [1, 3, 2]],
                        [[1, 2, 1], [4, 1, 3], [1, 1, 1]]]
            potentials = tf.convert_to_tensor(pre_pots, tf.float32)
            result = tf.user_ops.chain_crf(potentials)
            print(result.eval()) # TODO

# bazel test tensorflow/python:chain_crf_op_test --verbose_failures
```
And the full error:

```
$ cat /home/jernite/.cache/bazel/_bazel_jernite/f9fe393f3882802b0a658bd50e054d61/tensorflow/bazel-out/local_linux-fastbuild/testlogs/tensorflow/python/chain_crf_op_test/test.log
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
RuntimeError: module compiled against API version a but this version of numpy is 7
Traceback (most recent call last):
  File "/home/jernite/.cache/bazel/_bazel_jernite/f9fe393f3882802b0a658bd50e054d61/tensorflow/bazel-out/local_linux-fastbuild/bin/tensorflow/python/chain_crf_op_test.runfiles/tensorflow/python/kernel_tests/chain_crf_op_test.py", line 1, in <module>
    import tensorflow as tf
  File "/home/jernite/.cache/bazel/_bazel_jernite/f9fe393f3882802b0a658bd50e054d61/tensorflow/bazel-out/local_linux-fastbuild/bin/tensorflow/python/chain_crf_op_test.runfiles/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/home/jernite/.cache/bazel/_bazel_jernite/f9fe393f3882802b0a658bd50e054d61/tensorflow/bazel-out/local_linux-fastbuild/bin/tensorflow/python/chain_crf_op_test.runfiles/tensorflow/python/__init__.py", line 50, in <module>
    from tensorflow.python.framework.framework_lib import *
  File "/home/jernite/.cache/bazel/_bazel_jernite/f9fe393f3882802b0a658bd50e054d61/tensorflow/bazel-out/local_linux-fastbuild/bin/tensorflow/python/chain_crf_op_test.runfiles/tensorflow/python/framework/framework_lib.py", line 62, in <module>
    from tensorflow.python.framework.ops import Graph
  File "/home/jernite/.cache/bazel/_bazel_jernite/f9fe393f3882802b0a658bd50e054d61/tensorflow/bazel-out/local_linux-fastbuild/bin/tensorflow/python/chain_crf_op_test.runfiles/tensorflow/python/framework/ops.py", line 40, in <module>
    from tensorflow.python.framework import versions
  File "/home/jernite/.cache/bazel/_bazel_jernite/f9fe393f3882802b0a658bd50e054d61/tensorflow/bazel-out/local_linux-fastbuild/bin/tensorflow/python/chain_crf_op_test.runfiles/tensorflow/python/framework/versions.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/jernite/.cache/bazel/_bazel_jernite/f9fe393f3882802b0a658bd50e054d61/tensorflow/bazel-out/local_linux-fastbuild/bin/tensorflow/python/chain_crf_op_test.runfiles/tensorflow/python/pywrap_tensorflow.py", line 26, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/home/jernite/.cache/bazel/_bazel_jernite/f9fe393f3882802b0a658bd50e054d61/tensorflow/bazel-out/local_linux-fastbuild/bin/tensorflow/python/chain_crf_op_test.runfiles/tensorflow/python/pywrap_tensorflow.py", line 22, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: numpy.core.multiarray failed to import
```

Thanks in advance,
Yacine

**Comment by martinwicke** [comment]
This looks like a numpy version issue. Maybe you have more than one version of numpy installed in various places? If you installed from source using the instructions, you should have built against numpy 1.10 (version a), but maybe your runtime environment is set up using an older version?

**Comment by girving** [comment]
Do the tests pass without your new op?  It seems very weird that the new op would have anything to do with this, but I haven't looked at that code path and could easily be wrong.

**Comment by yjernite** [comment]
Hello,

  Thanks for the quick reply. Other tests also fail with the same error. I checked my version of numpy (using >>>import numpy; numpi.version.version :  1.10.1),  and was unable to find another (but I'm unfamiliar with how the modules are organized on that machine).

  I ended up just compiling with my new op, and it works. However, if someone wants to help debug bazel-test, I'm happy to run more tests. 

Best,
Yacine

**Comment by girving** [comment]
I'm hitting this too now, though I'm not sure if it's the same issue.  If I run `python3` directly, or invoke it indirectly using `bazel run`, `import numpy` pulls in something from `/usr/local/lib/python3.4/dist-packages/numpy`.  This is also the version of numpy picked up if I compile.

However, if I use `bazel test`, it pulls in a version of numpy from `/usr/lib/python3/dist-packages`, which in my case is incompatible.  Presumably bazel is messing with paths in an inconsistent manner, though I haven't investigated fully yet.

**Comment by martinwicke** [comment]
Sounds like it's worth asking the bazel folks about.

**Comment by girving** [comment]
Bazel folks asked: https://github.com/bazelbuild/bazel/issues/753

**Comment by vrv** [comment]
Closing due to inactivity / likely bazel / environment related

**Comment by PangZhi** [comment]
@vrv I also get the same error message.  Should we reopen this issue?

**Comment by vrv** [comment]
I don't think it's a TensorFlow issue -- your numpy version at runtime has to match the version that TensorFlow was compiled with.

**Comment by CanoeFZH** [comment]
I met the same problem. But you should notice that when you install tensorflow  it use numpy version A and when you run app of tensorflow you use numpy version 7. Does not match. 
You can check your running numpy version by: pip freeze or import numpy and numpy.version.version to verify this. The solution is to update your numpy to the tensorflow installing dependent numpy version.
