### ISSUE TITLE
Support for tf.where without x and y arguments in XLA

### ISSUE THREAD

**Issue by jplu** [tensorflow/tensorflow#47211]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Debian 10 / Linux Ubuntu 20.04 / Windows 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.1
- Python version: conda 3.8.5
- CUDA/cuDNN version: 11.0
- GPU model and memory: RTX 2080 Super

**Describe the current behavior**
The following error is raised, either the code is run on CPU or GPU:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/jplu-transformers/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/opt/anaconda3/envs/jplu-transformers/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 895, in _call
    filtered_flat_args, self._concrete_stateful_fn.captured_inputs)  # pylint: disable=protected-access
  File "/opt/anaconda3/envs/jplu-transformers/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1919, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/opt/anaconda3/envs/jplu-transformers/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 560, in call
    ctx=ctx)
  File "/opt/anaconda3/envs/jplu-transformers/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Function invoked by the following node is not compilable: {{node __inference_where_7}} = __inference_where_7[_XlaMustCompile=true, config_proto="\n\007\n\003CPU\020\001\n\007\n\003GPU\020\0012\005*\0010J\0008\001\202\001\000", executor_type=""](dummy_input).
Uncompilable nodes:
Where: unsupported op: No registered 'Where' OpKernel for XLA_GPU_JIT devices compatible with node {{node Where}}
        Stacktrace:
                Node: __inference_where_7, function:
                Node: Where, function: __inference_where_7
 [Op:__inference_where_7]
```

**Describe the expected behavior**
I'm expecting to have the Where op compliant with XLA on GPU and CPU as stated by @blakehechtman in https://github.com/tensorflow/tpu/issues/584 and get the following result:
```python
<tf.Tensor: shape=(2, 1), dtype=int64, numpy=
array([[0],
       [1]], dtype=int64)>
```

**Standalone code to reproduce the issue**
Here a piece of code to reproduce the issue:
```python
import tensorflow as tf

mask = tf.constant([True, True, False])

@tf.function(experimental_compile=True)
def test():
  return tf.where(mask)

test()
```

The context is that I need to have the indices of the `True` values in a mask in order to be able to use the `tf.gather_nd`, `tf.scatter_nd` and `tf.tensor_scatter_nd_update` methods.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/4088eeedda640a3629f8223af5f97f5f/47211.ipynb). Thanks!

**Comment by yunxing** [comment]
This is supported on XLA-TPU but not on XLA-GPU yet.

**Comment by jplu** [comment]
Oh, I see. Thanks for the answer! Any ETA for it to come on XLA-GPU (CPU)?

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tf Nightly 2.6.0-dev20210603, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/720f64c46754ecec93f9695797b559d5/47211.ipynb). Thanks!

**Comment by sushreebarsa** [comment]
@jplu Could you please have a look at the colab  [gist](https://colab.research.google.com/gist/sushreebarsa/2a8ef5dafb0e1f1d9e61da0e3855bd31/untitled68.ipynb) here ?Please let us know if  this issue is resolved for you.Thanks!

**Comment by jplu** [comment]
I do confirm, this is properly fixed in 2.8.0. Thanks a lot!
