### ISSUE TITLE
Cannot assign a device for operation using Google Cloud TPU

### ISSUE THREAD

**Issue by StevenShi-23** [tensorflow/tensorflow#47244]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
The codebase can be found at https://github.com/google/compare_gan.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu on Google Cloud.
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
Not applicable.
- TensorFlow installed from (source or binary):
Binary
- TensorFlow version (use command below):
TF v1.15
- Python version:
3.8
- Bazel version (if compiling from source):
Not applicable.
- GCC/Compiler version (if compiling from source):
Not applicable.
- CUDA/cuDNN version:
Not applicable.
- GPU model and memory:
TPU v3-8

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
v1.15.0-rc3-22-g590d6ee 1.15.0
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
The original issue can be found at [here](https://github.com/google/compare_gan/issues/53). I used the exact same software setup as stated in the CompareGAN repo, and ran it on V3-8 TPU with 4 vCPU VM. 
 
I had the following error: 
 
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation input_pipeline_task0/TensorSliceDataset: node input_pipeline_task0/TensorSliceDataset (defined at /usr/local/lib/python3.5/dist-packages/tensorflow_core/python/framework/ops.py:1748)  was explicitly assigned to /job:worker/task:0/device:CPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0 ]. Make sure the device specification refers to a valid device.

It looks to me that this error is caused by different naming conventions from older TF. The original repo uses TensorFlow 1.15, while the firmware of TPU/VM might have been updated over time, thus, it may not properly recognize the device name. I tried a workaround as suggested here (https://github.com/google/compare_gan/issues/53), but using a GPU instance can be very expensive and it goes against the reason of using TPUs. 

Therefore, I wonder if there is a way to rename the device from TensorFlow, or manually assign the device for input_pipeline handling?

**Describe the expected behavior**
I expect TF to recognize the device name properly. 

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

You can use the following command if you have a TPU:
```python3 compare_gan/main.py --use_tpu=True  --gin_config=/home/xxx/compare_gan/example_configs/resnet_cifar10.gin ```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
 File "/home/xxx/.local/lib/python3.5/site-packages/tensorflow_datasets/core/api_utils.py", line 52, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "/home/xxx/.local/lib/python3.5/site-packages/tensorflow_datasets/core/dataset_builder.py", line 236, in download_and_prepare
    self.info.compute_dynamic_properties()
  File "/home/xxx/.local/lib/python3.5/site-packages/tensorflow_datasets/core/dataset_info.py", line 245, in compute_dynamic_properties
    self._compute_dynamic_properties(self._builder)
  File "/home/xxx/.local/lib/python3.5/site-packages/tensorflow_datasets/core/dataset_info.py", line 258, in _compute_dynamic_properties
    builder, split_name)
  File "/home/xxx/.local/lib/python3.5/site-packages/tensorflow_datasets/core/dataset_info.py", line 447, in get_dataset_feature_statistics
    for example in tqdm.tqdm(np_dataset, unit=" examples"):
  File "/usr/local/lib/python3.5/dist-packages/tqdm/std.py", line 1107, in __iter__
    for obj in iterable:
  File "/home/xxx/.local/lib/python3.5/site-packages/tensorflow_datasets/core/dataset_utils.py", line 98, in _graph_dataset_iterator
    yield sess.run(ds_item)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation input_pipeline_task0/TensorSliceDataset: node input_pipeline_task0/TensorSliceDataset (defined at /usr/local/lib/python3.5/dist-packages/tensorflow_core/python/framework/ops.py:1748)  was explicitly assigned to /job:worker/task:0/device:CPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0 ]. Make sure the device specification refers to a valid device.
         [[input_pipeline_task0/TensorSliceDataset]]
```

**Comment by amahendrakar** [comment]
@StevenShi-23,
TensorFlow 1.x is not actively supported. Could you please update TensorFlow to the latest stable version v2.4.1 and check if you are facing the same issue. Thanks!

**Comment by StevenShi-23** [comment]
Hi @amahendrakar , thanks for the prompt reply!

I've tried to port the original repo to TF v2, but it requires much more changes than fixing this issue, and some code explicitly depends on TF v1. Therefore, I resort to finding a fix from TF v1. In my humble option, It should be easy, as we only need to mask the device name, but I don't know where to start. May you advise please?

Many thanks in advance!

**Comment by StevenShi-23** [comment]
A quick update: I ported the code to TF v2.4.1, but the same error occurs:

```
Traceback (most recent call last):
  File "/home/xxx/miniconda3/envs/tf2.4/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1375, in _do_call
    return fn(*args)
  File "/home/xxx/miniconda3/envs/tf2.4/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1358, in _run_fn
    self._extend_graph()
  File "/home/xxx/miniconda3/envs/tf2.4/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1398, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation input_pipeline_task0/TensorSliceDataset: {{node input_pipeline_task0/TensorSliceDataset}} was explicitly assigned to /job:worker/task:0/device:CPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
         [[input_pipeline_task0/TensorSliceDataset]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "compare_gan/main.py", line 135, in <module>
    app.run(main)
  File "/home/xxx/miniconda3/envs/tf2.4/lib/python3.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/xxx/miniconda3/envs/tf2.4/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "compare_gan/main.py", line 129, in main
    eval_every_steps=FLAGS.eval_every_steps)
  File "/home/xxx/xxx/compare_gan/runner_lib.py", line 337, in run_with_schedule
    hooks=train_hooks)
  File "/home/xxx/miniconda3/envs/tf2.4/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3130, in train
    rendezvous.raise_errors()
  File "/home/xxx/miniconda3/envs/tf2.4/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 150, in raise_errors
    six.reraise(typ, value, traceback)
  File "/home/xxx/miniconda3/envs/tf2.4/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/xxx/miniconda3/envs/tf2.4/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3125, in train
    saving_listeners=saving_listeners)
  File "/home/xxx/miniconda3/envs/tf2.4/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/xxx/miniconda3/envs/tf2.4/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1175, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/xxx/miniconda3/envs/tf2.4/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1204, in _train_model_default
    self.config)
  File "/home/xxx/miniconda3/envs/tf2.4/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2962, in _call_model_fn
    config)
  File "/home/xxx/miniconda3/envs/tf2.4/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1163, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/xxx/miniconda3/envs/tf2.4/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3242, in _model_fn
    input_holders.generate_infeed_enqueue_ops_and_dequeue_fn())
  File "/home/xxx/miniconda3/envs/tf2.4/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1484, in generate_infeed_enqueue_ops_and_dequeue_fn
    self._invoke_input_fn_and_record_structure())
  File "/home/xxx/miniconda3/envs/tf2.4/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1591, in _invoke_input_fn_and_record_structure
    host_device, host_id))
  File "/home/xxx/miniconda3/envs/tf2.4/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 927, in generate_per_host_enqueue_ops_fn_for_host
    inputs = _Inputs.from_input_fn(input_fn(user_context))
  File "/home/xxx/miniconda3/envs/tf2.4/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3096, in _input_fn
    return input_fn(**kwargs)
  File "/home/xxx/xxx/compare_gan/gans/modular_gan.py", line 426, in input_fn
    preprocess_fn=self._preprocess_fn)
  File "/home/xxx/xxx/compare_gan/datasets.py", line 334, in input_fn
    return self.train_input_fn(params=params, preprocess_fn=preprocess_fn)
  File "/home/xxx/xxx/compare_gan/datasets.py", line 284, in train_input_fn
    ds = self._load_dataset(split=self._train_split)
  File "/home/xxx/xxx/compare_gan/datasets.py", line 245, in _load_dataset
    as_dataset_kwargs={"shuffle_files": False})
  File "/home/xxx/miniconda3/envs/tf2.4/lib/python3.7/site-packages/tensorflow_datasets/core/api_utils.py", line 52, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "/home/xxx/miniconda3/envs/tf2.4/lib/python3.7/site-packages/tensorflow_datasets/core/registered.py", line 253, in load
    dbuilder.download_and_prepare(**download_and_prepare_kwargs)
  File "/home/xxx/miniconda3/envs/tf2.4/lib/python3.7/site-packages/tensorflow_datasets/core/api_utils.py", line 52, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "/home/xxx/miniconda3/envs/tf2.4/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py", line 236, in download_and_prepare
    self.info.compute_dynamic_properties()
  File "/home/xxx/miniconda3/envs/tf2.4/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_info.py", line 245, in compute_dynamic_properties
    self._compute_dynamic_properties(self._builder)
  File "/home/xxx/miniconda3/envs/tf2.4/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_info.py", line 258, in _compute_dynamic_properties
    builder, split_name)
  File "/home/xxx/miniconda3/envs/tf2.4/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_info.py", line 447, in get_dataset_feature_statistics
    for example in tqdm.tqdm(np_dataset, unit=" examples"):
  File "/home/xxx/miniconda3/envs/tf2.4/lib/python3.7/site-packages/tqdm/std.py", line 1170, in __iter__
    for obj in iterable:
  File "/home/xxx/miniconda3/envs/tf2.4/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_utils.py", line 98, in _graph_dataset_iterator
    yield sess.run(ds_item)
  File "/home/xxx/miniconda3/envs/tf2.4/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 968, in run
    run_metadata_ptr)
  File "/home/xxx/miniconda3/envs/tf2.4/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1191, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/xxx/miniconda3/envs/tf2.4/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1369, in _do_run
    run_metadata)
  File "/home/xxx/miniconda3/envs/tf2.4/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation input_pipeline_task0/TensorSliceDataset: node input_pipeline_task0/TensorSliceDataset (defined at /home/xxx/miniconda3/envs/tf2.4/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_utils.py:76)  was explicitly assigned to /job:worker/task:0/device:CPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
         [[input_pipeline_task0/TensorSliceDataset]]

```

**Comment by amahendrakar** [comment]
> I ported the code to TF v2.4.1, but the same error occurs:

@StevenShi-23,
Could you please provide the ported code, so that we can reproduce the issue on our end. Thanks!
