### ISSUE TITLE
`saved_model_cli show` report a error when apply it to a bert fine-tuned model

### ISSUE THREAD

**Issue by HarborZeng** [tensorflow/tensorflow#47301]
**System information**
- Have I written custom code: No
- OS Platform and Distribution: Ubuntu 16.04.2 LTS
- TensorFlow installed from binary 
- TensorFlow version v2.4.0-rc4-71-g582c8d236cb 2.4.0
- Python version: 3.7.9
- CUDA/cuDNN version: 11.0
- GPU model and memory: Quadro P5000 16G

**Describe the current behavior**

I am fine-tune a bert model for text classification, and there are preprocess procedure inside the model. The pre-trained model and preprocess model are all from tfhub so it should be fine, and code written by me is all about read file, build model with a few dense layers, fit, evaluate, predict and save.

After all these, I want to use `saved_model_cli` before serving like introduced in [this tutorial](https://www.tensorflow.org/tfx/tutorials/serving/rest_simple#save_your_model)

When using command

```bash
$ saved_model_cli show --dir training_checkpoints_sm/ --all
2021-02-22 11:38:35.613708: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0

MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['__saved_model_init_op']:
  The given SavedModel SignatureDef contains the following input(s):
  The given SavedModel SignatureDef contains the following output(s):
    outputs['__saved_model_init_op'] tensor_info:
        dtype: DT_INVALID
        shape: unknown_rank
        name: NoOp
  Method name is: 

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['text'] tensor_info:
        dtype: DT_STRING
        shape: (-1)
        name: serving_default_text:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['classifier'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 1)
        name: StatefulPartitionedCall_2:0
  Method name is: tensorflow/serving/predict
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/gang/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3929, in _get_op_def
    return self._op_def_cache[type]
KeyError: 'RegexSplitWithOffsets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/gang/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 890, in load_internal
    ckpt_options, filters)
  File "/home/user/anaconda3/envs/gang/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 132, in __init__
    meta_graph.graph_def.library))
  File "/home/user/anaconda3/envs/gang/lib/python3.7/site-packages/tensorflow/python/saved_model/function_deserialization.py", line 340, in load_function_def_library
    func_graph = function_def_lib.function_def_to_graph(copy)
  File "/home/kingsoft/anaconda3/envs/gang/lib/python3.7/site-packages/tensorflow/python/framework/function_def_to_graph.py", line 59, in function_def_to_graph
    fdef, input_shapes)
  File "/home/user/anaconda3/envs/gang/lib/python3.7/site-packages/tensorflow/python/framework/function_def_to_graph.py", line 220, in function_def_to_graph_def
    op_def = default_graph._get_op_def(node_def.op)  # pylint: disable=protected-access
  File "/home/user/anaconda3/envs/gang/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3934, in _get_op_def
    buf)
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'RegexSplitWithOffsets' in binary running on k8s-w-10-13-84-8. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/gang/bin/saved_model_cli", line 8, in <module>
    sys.exit(main())
  File "/home/user/anaconda3/envs/gang/lib/python3.7/site-packages/tensorflow/python/tools/saved_model_cli.py", line 1192, in main
    args.func(args)
  File "/home/user/anaconda3/envs/gang/lib/python3.7/site-packages/tensorflow/python/tools/saved_model_cli.py", line 719, in show
    _show_all(args.dir)
  File "/home/user/anaconda3/envs/gang/lib/python3.7/site-packages/tensorflow/python/tools/saved_model_cli.py", line 307, in _show_all
    _show_defined_functions(saved_model_dir)
  File "/home/user/anaconda3/envs/gang/lib/python3.7/site-packages/tensorflow/python/tools/saved_model_cli.py", line 187, in _show_defined_functions
    trackable_object = load.load(saved_model_dir)
  File "/home/user/anaconda3/envs/gang/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 859, in load
    return load_internal(export_dir, tags, options)["root"]
  File "/home/user/anaconda3/envs/gang/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 893, in load_internal
    str(err) + "\n If trying to load on a different device from the "
FileNotFoundError: Op type not registered 'RegexSplitWithOffsets' in binary running on k8s-w-10-13-84-8. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
 If trying to load on a different device from the computational device, consider using setting the `experimental_io_device` option on tf.saved_model.LoadOptions to the io_device such as '/job:localhost'.
```

This error `KeyError: 'RegexSplitWithOffsets'` really looks like when I forget to import `tensorflow_text` in my code.

```python
import tensorflow_text as text  # Registers the ops.
```

**Describe the expected behavior**

Expected behavior is I can import tensorflow_text when using this tool `saved_model_cli`.

**Standalone code to reproduce the issue**
```python
def build_classifier_model():
    text_input = tf.keras.layers.Input(shape=(), dtype=tf.string, name='text')
    preprocessor = hub.KerasLayer(
        "https://tfhub.dev/tensorflow/bert_zh_preprocess/3", name="preprocessor")
    encoder_inputs = preprocessor(text_input)
    encoder = hub.KerasLayer(
        "https://tfhub.dev/tensorflow/bert_zh_L-12_H-768_A-12/3",
        trainable=True,
        name="BERT_encoder")
    outputs = encoder(encoder_inputs)
    net = outputs['pooled_output']
    net = tf.keras.layers.Dropout(0.1)(net)
    net = tf.keras.layers.Dense(1, activation='sigmoid', name='classifier')(net)
    return tf.keras.Model(text_input, net)

...

history = classifier_model.fit(x=train_dataset,
                               epochs=epochs,
                               callbacks=[checkpoint_callback, early_stopping],
                               validation_data=val_dataset,
                               class_weight=class_weight)

...

classifier_model.save(checkpoint_dir + "_sm")

...

```

Can I successfully use `saved_model_cli`? or skip this part in that tutorial maybe?

**Comment by Saduf2019** [comment]
@HarborZeng 
The code provided is not complete  hence it would be difficult for us to pinpoint the issue. Please share complete stand alone code to replicate the issue or a colab gist with the error reported.? That will allow us to determine the source of the issue easily. 
Thanks!

**Comment by HarborZeng** [comment]
@Saduf2019 Hey here is a colab example: <https://colab.research.google.com/drive/1wW7p79YsSJDy9fvED7OnJ6mk37zlvFW8?usp=sharing>

**Comment by Saduf2019** [comment]
I am able to replicate the issue reported on tf 2.4 and nightly, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/a25ebe2bc7f8b06644bce4a7e97799d4/untitled548.ipynb).
Thanks!

**Comment by sushreebarsa** [comment]
Was able reproduce this issue in TF v2.5,please check the gist [here](https://colab.research.google.com/gist/sushreebarsa/a8da6e7b2920ac0a70757900b74b12ff/untitled14.ipynb)..Thanks !

**Comment by sachinprasadhs** [comment]
Have you tried the solution mentioned [here](https://github.com/tensorflow/hub/issues/732). Thanks!

**Comment by HarborZeng** [comment]
> Have you tried the solution mentioned [here](https://github.com/tensorflow/hub/issues/732). Thanks!

It's more like a binary executable bug rather than my python code import-related problem.

**Comment by HarborZeng** [comment]
But it does not matter anymore because it has been so many months passed..........
