### ISSUE TITLE
Having issue with NotImplemented Tensor to NumPy

### ISSUE THREAD

**Issue by yparam98** [tensorflow/tensorflow#47360]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
Arch Linux
Tensorflow version 2.4.1
Python version 3.9.1

I am doing the [TensorFlow tutorial](https://www.tensorflow.org/tutorials/images/classification#data_augmentation) and am getting NotImplemented errors at the Data Augmentation stage:

```
data_augmentation = keras.Sequential(
    [
        layers.experimental.preprocessing.RandomFlip("horizontal",
                                                     input_shape=(img_height,
                                                                  img_width,
                                                                  3)),
        layers.experimental.preprocessing.RandomRotation(0.1),
        layers.experimental.preprocessing.RandomZoom(0.1),
    ]
)
```

Error Trace:
```
Traceback (most recent call last):
  File "/home/yathavan/Documents/tensorflow/flowers/flowers.py", line 136, in <module>
    data_augmentation = keras.Sequential(
  File "/usr/lib/python3.9/site-packages/tensorflow/python/training/tracking/base.py", line 517, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/engine/sequential.py", line 144, in __init__
    self.add(layer)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/training/tracking/base.py", line 517, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/engine/sequential.py", line 223, in add
    output_tensor = layer(self.outputs[0])
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer.py", line 951, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1090, in _functional_construction_call
    outputs = self._keras_tensor_symbolic_call(
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer.py", line 822, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer.py", line 863, in _infer_output_signature
    outputs = call_fn(inputs, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/layers/preprocessing/image_preprocessing.py", line 866, in call
    output = control_flow_util.smart_cond(training, random_rotated_inputs,
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/utils/control_flow_util.py", line 114, in smart_cond
    return smart_module.smart_cond(
  File "/usr/lib/python3.9/site-packages/tensorflow/python/framework/smart_cond.py", line 54, in smart_cond
    return true_fn()
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/layers/preprocessing/image_preprocessing.py", line 861, in random_rotated_inputs
    get_rotation_matrix(angles, img_hd, img_wd),
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/layers/preprocessing/image_preprocessing.py", line 757, in get_rotation_matrix
    array_ops.zeros((num_angles, 2), dtypes.float32),
  File "/usr/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/ops/array_ops.py", line 2819, in wrapped
    tensor = fun(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/ops/array_ops.py", line 2868, in zeros
    output = _constant_if_small(zero, shape, dtype, name)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/ops/array_ops.py", line 2804, in _constant_if_small
    if np.prod(shape) < 1000:
  File "<__array_function__ internals>", line 5, in prod
  File "/usr/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 3030, in prod
    return _wrapreduction(a, np.multiply, 'prod', axis, dtype, out,
  File "/usr/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 852, in __array__
    raise NotImplementedError(
NotImplementedError: Cannot convert a symbolic Tensor (random_rotation/rotation_matrix/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported
```

**Comment by ghylander** [comment]
seems to be a compatibility issue between numpy 1.20+ and tf, #47263

**Comment by amahendrakar** [comment]
@yparam98,
I was able to run the code without any issues, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/6b61ab9b4c2f1e038b9392d155827582/classification.ipynb).

Currently TensorFlow is not compatible with Python 3.9. Could you please try running the code with Python 3.8 and check if you are facing the same error. Thanks!

**Comment by yparam98** [comment]
By god it works... 

Thanks @amahendrakar! 👍🏽
