### ISSUE TITLE
tf_upgrade_v2: UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 385: character maps to <undefined>

### ISSUE THREAD

**Issue by kiflowb777** [tensorflow/tensorflow#47371]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.4.0
- Python version: 3.6.1
- CUDA/cuDNN version: 11.1
- GPU model and memory: RTX3070 8GB

I tried to update my project with script tf_upgrade_v2 and command:
```
tf_upgrade_v2  --intree D:\Work\in_dir --outtree D:\Work\out_dir --reportfile D:\Work\report.txt --print_all
```
but I get error:
```
Traceback (most recent call last):
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\python36\Scripts\tf_upgrade_v2.exe\__main__.py", line 7, in <module>
  File "c:\python36\lib\site-packages\tensorflow\tools\compatibility\tf_upgrade_v2_main.py", line 178, in main
    args.input_tree, output_tree, args.copy_other_files)
  File "c:\python36\lib\site-packages\tensorflow\tools\compatibility\ast_edits.py", line 1076, in process_tree
    _, l_report, l_errors = self.process_file(input_path, output_path)
  File "c:\python36\lib\site-packages\tensorflow\tools\compatibility\ast_edits.py", line 921, in process_file
    temp_file)
  File "c:\python36\lib\site-packages\tensorflow\tools\compatibility\ast_edits.py", line 982, in process_opened_file
    lines = in_file.readlines()
  File "c:\python36\lib\encodings\cp1250.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 385: character maps to <undefined>
```

How to check which file in my project is troublesome?

**Comment by ravikyram** [comment]
@kiflowb777 

Please, share colab link or simple standalone code to reproduce the issue. It helps us in debugging further. Thanks!
