### ISSUE TITLE
Keras model saving erroring: TypeError: get_config() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by CharlesSS07** [tensorflow/tensorflow#47450]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: unknown
- TensorFlow installed from (source or binary): binary, conda
- TensorFlow version (use command below): 2.2
- Python version: 3.8
- CUDA/cuDNN version: 7.6

Bug demonstrated here:
https://stackoverflow.com/questions/57154799/keras-model-saving-erroring-typeerror-get-config-missing-1-required-position

Saving model that has weights initialized by tf.keras.initializers.zeros instead of tf.keras.initializers.Zeros() does not work because tf.keras.initializers.zeros is a class while tf.keras.initializers.Zeros() is an instance. Tf tries to look at fields of class but can't because it is not an instance. I cannot save my own model like this, and instead, have to save the weights and python code to construct it.

I get the following error after calling model.save(filename) on my tf.keras Model:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-52-4285f74de661> in <module>
----> 1 ae.save(
      2     os.path.join(folder, 'model'),
      3     include_optimizer=False
      4 )

~/anaconda3/envs/tf-2.2/lib/python3.8/site-packages/tensorflow/python/keras/engine/network.py in save(self, filepath, overwrite, include_optimizer, save_format, signatures, options)
   1049     ```
   1050     """
-> 1051     save.save_model(self, filepath, overwrite, include_optimizer, save_format,
   1052                     signatures, options)
   1053 

~/anaconda3/envs/tf-2.2/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py in save_model(model, filepath, overwrite, include_optimizer, save_format, signatures, options)
    135         model, filepath, overwrite, include_optimizer)
    136   else:
--> 137     saved_model_save.save(model, filepath, overwrite, include_optimizer,
    138                           signatures, options)
    139 

~/anaconda3/envs/tf-2.2/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/save.py in save(model, filepath, overwrite, include_optimizer, signatures, options)
     76     # we use the default replica context here.
     77     with distribution_strategy_context._get_default_replica_context():  # pylint: disable=protected-access
---> 78       save_lib.save(model, filepath, signatures, options)
     79 
     80   if not include_optimizer:

~/anaconda3/envs/tf-2.2/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py in save(obj, export_dir, signatures, options)
    948   meta_graph_def = saved_model.meta_graphs.add()
    949 
--> 950   _, exported_graph, object_saver, asset_info = _build_meta_graph(
    951       obj, export_dir, signatures, options, meta_graph_def)
    952   saved_model.saved_model_schema_version = constants.SAVED_MODEL_SCHEMA_VERSION

~/anaconda3/envs/tf-2.2/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py in _build_meta_graph(obj, export_dir, signatures, options, meta_graph_def)
   1034         function_aliases[fdef.name] = alias
   1035 
-> 1036   object_graph_proto = _serialize_object_graph(saveable_view,
   1037                                                asset_info.asset_index)
   1038   meta_graph_def.object_graph_def.CopyFrom(object_graph_proto)

~/anaconda3/envs/tf-2.2/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py in _serialize_object_graph(saveable_view, asset_file_def_index)
    694 
    695   for obj, obj_proto in zip(saveable_view.nodes, proto.nodes):
--> 696     _write_object_proto(obj, obj_proto, asset_file_def_index,
    697                         saveable_view.function_name_map)
    698   return proto

~/anaconda3/envs/tf-2.2/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py in _write_object_proto(obj, proto, asset_file_def_index, function_name_map)
    735           version=versions_pb2.VersionDef(
    736               producer=1, min_consumer=1, bad_consumers=[]),
--> 737           metadata=obj._tracking_metadata)
    738       # pylint:enable=protected-access
    739     proto.user_object.CopyFrom(registered_type_proto)

~/anaconda3/envs/tf-2.2/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py in _tracking_metadata(self)
   2740   @property
   2741   def _tracking_metadata(self):
-> 2742     return self._trackable_saved_model_saver.tracking_metadata
   2743 
   2744   def _list_extra_dependencies_for_serialization(self, serialization_cache):

~/anaconda3/envs/tf-2.2/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/base_serialization.py in tracking_metadata(self)
     52     # TODO(kathywu): check that serialized JSON can be loaded (e.g., if an
     53     # object is in the python property)
---> 54     return json_utils.Encoder().encode(self.python_properties)
     55 
     56   def list_extra_dependencies_for_serialization(self, serialization_cache):

~/anaconda3/envs/tf-2.2/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py in python_properties(self)
     39   def python_properties(self):
     40     # TODO(kathywu): Add python property validator
---> 41     return self._python_properties_internal()
     42 
     43   def _python_properties_internal(self):

~/anaconda3/envs/tf-2.2/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/model_serialization.py in _python_properties_internal(self)
     33 
     34   def _python_properties_internal(self):
---> 35     metadata = super(ModelSavedModelSaver, self)._python_properties_internal()
     36     metadata.update(
     37         saving_utils.model_metadata(

~/anaconda3/envs/tf-2.2/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/network_serialization.py in _python_properties_internal(self)
     31 
     32   def _python_properties_internal(self):
---> 33     metadata = super(NetworkSavedModelSaver, self)._python_properties_internal()
     34 
     35     # Network stateful property is dependent on the child layers.

~/anaconda3/envs/tf-2.2/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py in _python_properties_internal(self)
     55         stateful=self.obj.stateful)
     56 
---> 57     metadata.update(get_config(self.obj))
     58     if self.obj.input_spec is not None:
     59       # Layer's input_spec has already been type-checked in the property setter.

~/anaconda3/envs/tf-2.2/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py in get_config(obj)
    113     # When loading, the program will attempt to revive the object from config,
    114     # and if that fails, the object will be revived from the SavedModel.
--> 115     config = generic_utils.serialize_keras_object(obj)['config']
    116 
    117   if config is not None:

~/anaconda3/envs/tf-2.2/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py in serialize_keras_object(instance)
    268     name = get_registered_name(instance.__class__)
    269     try:
--> 270       config = instance.get_config()
    271     except NotImplementedError as e:
    272       if _SKIP_FAILED_SERIALIZATION:

~/anaconda3/envs/tf-2.2/lib/python3.8/site-packages/tensorflow/python/keras/engine/network.py in get_config(self)
    966     if not self._is_graph_network:
    967       raise NotImplementedError
--> 968     return copy.deepcopy(get_network_config(self))
    969 
    970   @classmethod

~/anaconda3/envs/tf-2.2/lib/python3.8/site-packages/tensorflow/python/keras/engine/network.py in get_network_config(network, serialize_layer_fn)
   2117           filtered_inbound_nodes.append(node_data)
   2118 
-> 2119     layer_config = serialize_layer_fn(layer)
   2120     layer_config['name'] = layer.name
   2121     layer_config['inbound_nodes'] = filtered_inbound_nodes

~/anaconda3/envs/tf-2.2/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py in serialize_keras_object(instance)
    268     name = get_registered_name(instance.__class__)
    269     try:
--> 270       config = instance.get_config()
    271     except NotImplementedError as e:
    272       if _SKIP_FAILED_SERIALIZATION:

~/anaconda3/envs/tf-2.2/lib/python3.8/site-packages/tensorflow/python/keras/layers/convolutional.py in get_config(self)
    261         'activation': activations.serialize(self.activation),
    262         'use_bias': self.use_bias,
--> 263         'kernel_initializer': initializers.serialize(self.kernel_initializer),
    264         'bias_initializer': initializers.serialize(self.bias_initializer),
    265         'kernel_regularizer': regularizers.serialize(self.kernel_regularizer),

~/anaconda3/envs/tf-2.2/lib/python3.8/site-packages/tensorflow/python/keras/initializers.py in serialize(initializer)
    164 @keras_export('keras.initializers.serialize')
    165 def serialize(initializer):
--> 166   return serialize_keras_object(initializer)
    167 
    168 

~/anaconda3/envs/tf-2.2/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py in serialize_keras_object(instance)
    268     name = get_registered_name(instance.__class__)
    269     try:
--> 270       config = instance.get_config()
    271     except NotImplementedError as e:
    272       if _SKIP_FAILED_SERIALIZATION:

TypeError: get_config() missing 1 required positional argument: 'self'
```

**Comment by amahendrakar** [comment]
@CharlesSS07,
In order to reproduce the issue reported here, could you please provide the complete code and the dataset you are using.

Also, please update TensorFlow to the latest stable version v2.4.1 and check if you are facing the same error. Thanks!

**Comment by CharlesSS07** [comment]
Certainly @amahendrakar ,

I'll show two simple python files, and the resulting terminal output, which I ran on the tf 2.4.1 docker on my mac (no GPU). The first does not save successfully. The second does.

**File 1: failure**

```
import tensorflow as tf

input_shape = [64, 64, 3]

h = inputs = tf.keras.Input(shape=input_shape)

layer = tf.keras.layers.Conv2D( # a simple convolutional layer
    32,
    24,
    kernel_initializer=tf.initializers.glorot_uniform(), # a CLASS which is used to initialize the weights
)

h = layer(h)

model = tf.keras.Model(inputs=inputs, outputs=h)
model.compile(optimizer=tf.optimizers.Adamax(), loss='mse')
model.summary()

output_shape = model.predict(tf.zeros(shape=[1,*input_shape], dtype=tf.float32))[0].shape
print('Output shape:', output_shape)
# model.predict causes the weights to initialize, if not already

# train as much or as little as you want

model.save('./saved-model')

print('saved model')
```

**File 1 output:**

```
# python3 failed_test.py
2021-03-01 15:47:15.745023: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-03-01 15:47:15.745236: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-03-01 15:47:17.066388: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-03-01 15:47:17.066701: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-03-01 15:47:17.066746: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-03-01 15:47:17.066863: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (5ca126ea0fc1): /proc/driver/nvidia/version does not exist
2021-03-01 15:47:17.067202: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-03-01 15:47:17.067515: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         [(None, 64, 64, 3)]       0         
_________________________________________________________________
conv2d (Conv2D)              (None, 41, 41, 32)        55328     
=================================================================
Total params: 55,328
Trainable params: 55,328
Non-trainable params: 0
_________________________________________________________________
2021-03-01 15:47:17.137908: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-03-01 15:47:17.138614: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2492380000 Hz
Output shape: (41, 41, 32)
2021-03-01 15:47:17.291897: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
Traceback (most recent call last):
  File "failed_test.py", line 27, in <module>
    model.save('./saved-model')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 2002, in save
    signatures, options, save_traces)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/save.py", line 157, in save_model
    signatures, options, save_traces)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/save.py", line 89, in save
    save_lib.save(model, filepath, signatures, options)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/save.py", line 1033, in save
    obj, signatures, options, meta_graph_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/save.py", line 1198, in _build_meta_graph
    return _build_meta_graph_impl(obj, signatures, options, meta_graph_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/save.py", line 1163, in _build_meta_graph_impl
    asset_info.asset_index)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/save.py", line 755, in _serialize_object_graph
    saveable_view.function_name_map)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/save.py", line 800, in _write_object_proto
    metadata=obj._tracking_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 3079, in _tracking_metadata
    return self._trackable_saved_model_saver.tracking_metadata
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/base_serialization.py", line 55, in tracking_metadata
    return json_utils.Encoder().encode(self.python_properties)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 41, in python_properties
    return self._python_properties_internal()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/model_serialization.py", line 35, in _python_properties_internal
    metadata = super(ModelSavedModelSaver, self)._python_properties_internal()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 59, in _python_properties_internal
    metadata.update(get_config(self.obj))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 118, in get_config
    config = generic_utils.serialize_keras_object(obj)['config']
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/generic_utils.py", line 245, in serialize_keras_object
    config = instance.get_config()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/functional.py", line 650, in get_config
    return copy.deepcopy(get_network_config(self))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/functional.py", line 1349, in get_network_config
    layer_config = serialize_layer_fn(layer)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/generic_utils.py", line 245, in serialize_keras_object
    config = instance.get_config()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/convolutional.py", line 321, in get_config
    initializers.serialize(self.kernel_initializer),
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/initializers/__init__.py", line 135, in serialize
    return generic_utils.serialize_keras_object(initializer)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/generic_utils.py", line 245, in serialize_keras_object
    config = instance.get_config()
TypeError: get_config() missing 1 required positional argument: 'self'
# 
```

**File 2: success**
```
import tensorflow as tf

input_shape = [64, 64, 3]

h = inputs = tf.keras.Input(shape=input_shape)

layer = tf.keras.layers.Conv2D( # a simple convolutional layer
    32,
    24,
    kernel_initializer=tf.initializers.glorot_uniform(), # a INSTANCE which is used to initialize the weights
)

h = layer(h)

model = tf.keras.Model(inputs=inputs, outputs=h)
model.compile(optimizer=tf.optimizers.Adamax(), loss='mse')
model.summary()

output_shape = model.predict(tf.zeros(shape=[1,*input_shape], dtype=tf.float32))[0].shape
print('Output shape:', output_shape)
# model.predict causes the weights to initialize, if not already

# train as much or as little as you want

model.save('./saved-model')

print('saved model')
```

**File 2 output:**
```
# python3 sucessful_test.py
2021-03-01 15:48:05.010560: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-03-01 15:48:05.010612: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-03-01 15:48:06.358511: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-03-01 15:48:06.358718: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-03-01 15:48:06.358737: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-03-01 15:48:06.358755: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (5ca126ea0fc1): /proc/driver/nvidia/version does not exist
2021-03-01 15:48:06.359019: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-03-01 15:48:06.360054: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         [(None, 64, 64, 3)]       0         
_________________________________________________________________
conv2d (Conv2D)              (None, 41, 41, 32)        55328     
=================================================================
Total params: 55,328
Trainable params: 55,328
Non-trainable params: 0
_________________________________________________________________
2021-03-01 15:48:06.432318: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-03-01 15:48:06.432802: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2492380000 Hz
Output shape: (41, 41, 32)
2021-03-01 15:48:06.587815: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
saved model
# 
```

The only difference between these two files is this line:
```kernel_initializer=tf.initializers.glorot_uniform```, which is
```kernel_initializer=tf.initializers.glorot_uniform()``` in file 2.
In both cases, the weights are initialized without error and successfully predict on a dummy example. It seems to me that since there was no errors raised during initialization, saving should therefore work in both cases? If they all represent the same thing, why do we have the option to use tf.keras.initializers.glorot_uniform, tf.keras.initializers.glorot_uniform(), "glorot_uniform", or tf.keras.initializers.GlorotUniform as the initializer in a layer?

Thanks, and hoping to understand this better.

**Comment by amahendrakar** [comment]
@CharlesSS07,
I did not face any errors while running both the code snippets with TF v2.4.1, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/b5e7b289755797b911f71af5a098be7a/47450.ipynb).

Could you please try running the code in a new virtual environment and check if it helps. Thanks!

**Comment by CharlesSS07** [comment]
Hi @amahendrakar ,

Looks like I made a mistake while copying and pasting those two code snippets. I have edited my previous comment. The mistake was in the first code snippet which was supposed to error, and I had accidentally added a '()'. This mistake made the two code snippets equivalent, and so the error never occurred in your gist.

Thanks for catching that, I have no idea how it happened. Could you try it again in your gist, without the parentheses after the initializer of the conv2d layer?

**Comment by amahendrakar** [comment]
@CharlesSS07,
Thank you for the update.

Please take a look at similar issue [#47054](https://github.com/tensorflow/tensorflow/issues/47054) and the fix for it [#47128](https://github.com/tensorflow/tensorflow/pull/47128) and check if it helps.

**Comment by CharlesSS07** [comment]
Hi @amahendrakar ,

Both of those issues display the same behavior, and they say that tf.initializers.zeros is supposed to be a pre-initialized version of tf.initializers.Zeros, for example, but that you have to call tf.initializers.zeros() to avoid the error. The bug behavior is in that passing tf.initializers.zeros to a model works for training, but not for saving, whereas passing tf.initializers.zeros() works for both saving and training. It's logical that if a function works for training, then it should also work for saving, so there should either be an error on passing tf.initializers.zeros to a layer, or getting tf.initializers.zeros would return the value of calling tf.initializers.zeros().

Thanks, and is it possible to change the behavior of tf.initializers.zeros to return the value of tf.initializers.zeros()?

**Comment by amahendrakar** [comment]
@ymodak,
I was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/18ca363a469ad1beede9cd52103b9983/47450.ipynb#scrollTo=-xSgFNJafS94). Thanks!

**Comment by ymodak** [comment]
This is fixed latest tf-nightly. See [gist](https://colab.research.google.com/gist/ymodak/e9a4b5c63742ab13bd2eb94718681190/47450.ipynb)

**Comment by CharlesSS07** [comment]
Thanks everyone. I think we can close this out now.
