### ISSUE TITLE
[_Derived_]RecvAsync is cancelled Error when training with LSTM on tf-gpu 

### ISSUE THREAD

**Issue by NasonZ** [tensorflow/tensorflow#47453]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
```
model = tf.keras.Sequential([
        tf.keras.layers.Embedding(vocab_size, store.embedding_dim,
                                  batch_input_shape=[batch_size, None]),
        tf.keras.layers.Dropout(store.dropout_rate),
        tf.keras.layers.LSTM(store.rnn_units,
                             return_sequences=True,
                             stateful=True,
                             recurrent_initializer=store.rnn_initializer),
        tf.keras.layers.Dropout(store.dropout_rate),
        tf.keras.layers.LSTM(store.rnn_units,
                             return_sequences=True,
                             stateful=True,
                             recurrent_initializer=store.rnn_initializer),
        tf.keras.layers.Dropout(store.dropout_rate),
        tf.keras.layers.Dense(vocab_size)
    ])
    model.compile(optimizer=optimizer, loss=loss, metrics=["accuracy"])

```
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow version (use command below):  v2.4.0-49-g85c8b2a817f 2.4.1
- Python version: 3.8.8
- CUDA/cuDNN version: CUDA 11.0.3 / CUDNN 8.0.5.77
- GPU model and memory: GTX 1070 (8GB)

**Describe the current behavior**
I've been working on a LSTM model, when training with $ `model.fit()` , it runs for 6 epochs and then gives this error 

```
  File "C:\Users\Me\anaconda3\envs\tf_gpu24\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
  File "C:\Users\Me\anaconda3\envs\tf_gpu24\lib\site-packages\tensorflow\python\eager\def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\Me\anaconda3\envs\tf_gpu24\lib\site-packages\tensorflow\python\eager\def_function.py", line 855, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "C:\Users\Me\anaconda3\envs\tf_gpu24\lib\site-packages\tensorflow\python\eager\function.py", line 2942, in __call__
    return graph_function._call_flat(
  File "C:\Users\Me\anaconda3\envs\tf_gpu24\lib\site-packages\tensorflow\python\eager\function.py", line 1918, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "C:\Users\Me\anaconda3\envs\tf_gpu24\lib\site-packages\tensorflow\python\eager\function.py", line 555, in call
    outputs = execute.execute(
  File "C:\Users\Me\anaconda3\envs\tf_gpu24\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.CancelledError:  [_Derived_]RecvAsync is cancelled.
         [[{{node gradient_tape/sequential/embedding/embedding_lookup/Reshape/_20}}]] [Op:__inference_train_function_4800]

Function call stack:
train_function
```

**Describe the expected behavior**
Model should complete training without issue.
I know the code is fine because I trained on the same code with no issue in an old environment I was using 2 months ago. It also runs fine in a CPU only tensorflow environment.  

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem.

```
Epoch 1/50
2021-02-27 14:50:38.552734: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-02-27 14:50:38.882403: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-02-27 14:50:39.546250: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021-02-27 14:50:39.794953: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
37/37 [==============================] - 7s 55ms/step - loss: 7.0684 - accuracy: 0.1270
Epoch 2/50
37/37 [==============================] - 2s 54ms/step - loss: 4.8889 - accuracy: 0.1828
Epoch 3/50
37/37 [==============================] - 2s 54ms/step - loss: 4.7884 - accuracy: 0.1666
Epoch 4/50
37/37 [==============================] - 2s 54ms/step - loss: 4.6866 - accuracy: 0.1480
Epoch 5/50
37/37 [==============================] - 2s 55ms/step - loss: 4.5179 - accuracy: 0.1630
Epoch 6/50
17/37 [============>.................] - ETA: 1s - loss: 4.2505 - accuracy: 0.14842021-02-27 14:50:55.955000: E tensorflow/stream_executor/dnn.cc:616] CUDNN_STATUS_INTERNAL_ERROR
in tensorflow/stream_executor/cuda/cuda_dnn.cc(2004): 'cudnnRNNBackwardWeights( cudnn.handle(), rnn_desc.handle(), model_dims.max_seq_length, input_desc.handles(), input_data.opaque(), input_h_desc.handle(), input_h_data.opaque(), output_desc.handles(), output_data.opaque(), workspace.opaque(), workspace.size(), rnn_desc.params_handle(), params_backprop_data->opaque(), reserve_space_data->opaque(), reserve_space_data->size())'
2021-02-27 14:50:55.955194: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at cudnn_rnn_ops.cc:1926 : Internal: Failed to call ThenRnnBackward with model config: [rnn_mode, rnn_input_mode, rnn_direction_mode]: 2, 0, 0 , [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size, cell_num_units]: [1, 256, 256, 1, 100, 64, 256]
2021-02-27 14:50:55,957 : MainThread : INFO : Saving model history to model_history.csv
2021-02-27 14:50:55,961 : MainThread : INFO : Saving model to D:\project\project_engine\fftest_checkpoints\batch_0\synthetic
Traceback (most recent call last):
  File "runTrain.py", line 65, in <module>
    model.train()
  ...
  ... 
  ...
  File "D:\project\project_engine\runTrain.py", line 201, in train_rnn
    model.fit(dataset, epochs=store.epochs, callbacks=_callbacks)
  File "C:\Users\Me\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
  File "C:\Users\Me\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\eager\def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\Me\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\eager\def_function.py", line 855, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "C:\Users\Me\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\eager\function.py", line 2942, in __call__
    return graph_function._call_flat(
  File "C:\Users\Me\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\eager\function.py", line 1918, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "C:\Users\Me\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\eager\function.py", line 555, in call
    outputs = execute.execute(
  File "C:\Users\Me\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.CancelledError:  [_Derived_]RecvAsync is cancelled.
         [[{{node gradient_tape/sequential/embedding/embedding_lookup/Reshape/_20}}]] [Op:__inference_train_function_4800]

Function call stack:
train_function
```

**Comment by amahendrakar** [comment]
@NasonZ,
On running the given code snippet, I am facing an error stating `NameError: name 'vocab_size' is not defined`. In order to reproduce the issue reported here, could you please provide the complete code and the dataset you are using.

Also, please try limiting GPU memory growth using any of the methods listed [here](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth) and check if it helps. Thanks!
