### ISSUE TITLE
Validation fails while model fit

### ISSUE THREAD

**Issue by ferryvg** [tensorflow/tensorflow#47550]
**System information**
- OS Platform and Distribution: Linux Mint 19.3
- TensorFlow installed from: pypi
- TensorFlow version: v2.4.0-49-g85c8b2a817f 2.4.1
- Python version: 3.8

[tf_env.txt](https://github.com/tensorflow/tensorflow/files/6081336/tf_env.txt)

**Describe the current behavior**
Train finished complete, but validation fails

**Describe the expected behavior**
Train and validation succeeded

**Standalone code to reproduce the issue**
I have some TF.Example files and load it as:
```python
def get_dataset(files_pattern: str, strategy: tf.distribute.Strategy, batch_size: int):
    global_batch_size = _get_global_batch_size(strategy, batch_size)
    dataset = tf.data.TFRecordDataset(tf.io.gfile.glob(files_pattern))
    dataset = dataset.shuffle(10 * batch_size)
    # dataset = dataset.repeat()
    dataset = dataset.batch(global_batch_size)
    dataset = dataset.map(_parse_example)  # vectorised tf.train.Example parsing
    dataset = dataset.prefetch(buffer_size=tf.data.experimental.AUTOTUNE)

    options = dataset_ops.Options()
    options.experimental_distribute.auto_shard_policy = dataset_ops.distribute_options.AutoShardPolicy.DATA
    dataset = dataset.with_options(options)

    return dataset
```

Model training:
```python
def run_local(train_pattern, eval_pattern, batch_size, model_dir, log_path):
    strategy = tf.distribute.OneDeviceStrategy(device="/cpu:0")

    train_ds = data.get_dataset(train_pattern, strategy, batch_size)
    eval_ds = data.get_dataset(eval_pattern, strategy, batch_size)

    with strategy.scope():
        model = _build_keras_model(
            hidden_units=DNN_HIDDEN_UNITS,
            learning_rate=LEARNING_RATE)

    profile_options = tf.profiler.experimental.ProfilerOptions(
        host_tracer_level=1, python_tracer_level=1, device_tracer_level=1,
    )
    tf.profiler.experimental.start(log_path, options=profile_options)

    # Write logs to path
    callbacks = get_callbacks(log_path, 0)

    model.fit(
        train_ds,
        validation_data=eval_ds,
        callbacks=callbacks)

    tf.profiler.experimental.stop()

    _save_model(model_dir, model, strategy)
```

**Other info / logs**
```
Train on None steps
   1000/Unknown - 492s 491ms/step - batch: 499.5000 - size: 1.0000 - loss: 0.0650 - tp: 32328.0000 - fp: 28630.0000 - tn: 9838817.0000 - fn: 100225.0000 - accuracy: 0.9871 - precision: 0.5303 - recall: 0.2439 - auc: 0.8881 - mse: 0.0125 - binary_crossentropy: 0.0646/home/local/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:2325: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  warnings.warn('`Model.state_updates` will be removed in a future version. '
Traceback (most recent call last):
  File "/snap/pycharm-community/226/plugins/python-ce/helpers/pydev/pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-community/226/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/local/projects/***/model/local_train.py", line 12, in <module>
    run_local(train_pattern, eval_pattern, batch_size, model_path, log_path)
  File "/home/local/projects/***/model/keras.py", line 310, in run_local
    model.fit(
  File "/home/local/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training_v1.py", line 789, in fit
    return func.fit(
  File "/home/local/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training_distributed_v1.py", line 675, in fit
    return training_arrays_v1.fit_loop(
  File "/home/local/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training_arrays_v1.py", line 417, in model_iteration
    val_results = model_iteration(
  File "/home/local/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training_arrays_v1.py", line 347, in model_iteration
    index_array = np.arange(num_samples_or_steps)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```

**Comment by amahendrakar** [comment]
@ferryvg,
In the given code snippet, you have defined the functions but are not calling them anywhere. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/156837ac5e88bef8d10badc553ec840f/47550.ipynb).

In order to reproduce the issue reported here, could you please provide the complete code and the dataset you are using. Thanks!

**Comment by ferryvg** [comment]
@amahendrakar , it's works in notebook, very strange

**Comment by ferryvg** [comment]
Error raises when i use `tf.compat.v1.disable_eager_execution()`
