### ISSUE TITLE
AttributeError: type object 'NewBase' has no attribute 'is_abstract'

### ISSUE THREAD

**Issue by dxin1234** [tensorflow/tensorflow#4758]
I uninstalled anaconda and reinstalled tensorflow using the pip installation. 

Originally it was having trouble updating numpy, but after I fixed that now I'm getting this error:
```
import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/Library/Python/2.7/site-packages/tensorflow/python/__init__.py", line 98, in <module>
    from tensorflow.python.platform import test
  File "/Library/Python/2.7/site-packages/tensorflow/python/platform/test.py", line 63, in <module>
    from tensorflow.python.framework import test_util
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/test_util.py", line 43, in <module>
    from tensorflow.python.platform import googletest
  File "/Library/Python/2.7/site-packages/tensorflow/python/platform/googletest.py", line 32, in <module>
    from tensorflow.python.platform import benchmark  # pylint: disable=unused-import
  File "/Library/Python/2.7/site-packages/tensorflow/python/platform/benchmark.py", line 122, in <module>
    class Benchmark(six.with_metaclass(_BenchmarkRegistrar, object)):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six.py", line 566, in with_metaclass
    return meta("NewBase", bases, {})
  File "/Library/Python/2.7/site-packages/tensorflow/python/platform/benchmark.py", line 117, in __new__
    if not newclass.is_abstract():
AttributeError: type object 'NewBase' has no attribute 'is_abstract'
```
Could this be because uninstalling anaconda left some residual effects. I noticed my $PATH still has anaconda prepended to it
`$PATH -bash: /Users/usr/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/usr/texbin: No such file or directory`

**Comment by tatatodd** [comment]
@dxin1234 Please provide at least the command that you're running that leads to the error.  Also provide the information from the default template, which appears when you click on the green "New issue" button.

---

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)


### What other attempted solutions have you tried?


### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).
