### ISSUE TITLE
My python version is 3.6. I successfully installed tensorflow, but when I imported in idle it gives error as following :

### ISSUE THREAD

**Issue by oberon98** [tensorflow/tensorflow#47588]
>>> import tensorflow
2021-03-05 18:13:41.002427: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-03-05 18:13:41.003385: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\sushi\AppData\Roaming\Python\Python36\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\sushi\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\__init__.py", line 41, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\sushi\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\eager\context.py", line 32, in <module>
    from tensorflow.core.framework import function_pb2
  File "C:\Users\sushi\AppData\Roaming\Python\Python36\site-packages\tensorflow\core\framework\function_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "C:\Users\sushi\AppData\Local\Programs\Python\Python36\lib\site-packages\google\protobuf\descriptor.py", line 48, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by Saduf2019** [comment]
@oberon98 
Please refer to these resolved issues and let us know: #47517, #45398
