### ISSUE TITLE
AttributeError: 'module' object has no attribute 'NodeDef'

### ISSUE THREAD

**Issue by hfutxrg** [tensorflow/tensorflow#4759]
I tried to run the distributed Tensorflow for inception-v3 example, but I have the following errors in worker nodes:
```
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:197] Initialize GrpcChannelCache for job ps -> {0 -> 10.149.0.1:2222}
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:197] Initialize GrpcChannelCache for job worker -> {0 -> localhost:2222, 1 -> 10.149.0.3:2222}
I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:206] Started server with target: grpc://localhost:2222
Traceback (most recent call last):
  File "/cm/shared/scratch/rengan/DL/models/inception/bazel-bin/inception/imagenet_distributed_train.runfiles/inception/inception/imagenet_distributed_train.py", line 65, in <module>
    tf.app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/cm/shared/scratch/rengan/DL/models/inception/bazel-bin/inception/imagenet_distributed_train.runfiles/inception/inception/imagenet_distributed_train.py", line 61, in main
    inception_distributed_train.train(server.target, dataset, cluster_spec)
  File "/cm/shared/scratch/rengan/DL/models/inception/bazel-bin/inception/imagenet_distributed_train.runfiles/inception/inception/inception_distributed_train.py", line 120, in train
    global_step = slim.variables.global_step()
  File "/cm/shared/scratch/rengan/DL/models/inception/bazel-bin/inception/imagenet_distributed_train.runfiles/inception/inception/slim/scopes.py", line 155, in func_with_args
    return func(*args, **current_args)
  File "/cm/shared/scratch/rengan/DL/models/inception/bazel-bin/inception/imagenet_distributed_train.runfiles/inception/inception/slim/variables.py", line 242, in global_step
    with tf.device(variable_device(device, 'global_step')):
  File "/cm/shared/scratch/rengan/DL/models/inception/bazel-bin/inception/imagenet_distributed_train.runfiles/inception/inception/slim/variables.py", line 214, in variable_device
    var_def = graph_pb2.NodeDef(name=var_name, op='Variable')
AttributeError: 'module' object has no attribute 'NodeDef'
```

Based on the information, the line 214 is 
var_def = graph_pb2.NodeDef(name=var_name, op='Variable')

And at the beginning of variables.py, it has the line
from tensorflow.core.framework import graph_pb2

But I could not find any graph_pb2 from tensorflow/tensorflow/core/framework. Any idea why I got this error? 

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem? 
No other related posts were found.

Environment info

Operating System: Redhat 7.2

Installed version of CUDA and cuDNN: 
(please attach the output of ls -l /path/to/cuda/lib/libcud*):
-rw-r--r-- 1 root root 560184 May 8 02:00 /usr/local/cuda-8.0/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root 16 Sep 12 15:13 /usr/local/cuda-8.0/lib64/libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root root 19 Sep 12 15:13 /usr/local/cuda-8.0/lib64/libcudart.so.8.0 -> libcudart.so.8.0.27
-rwxr-xr-x 1 root root 394472 May 8 02:00 /usr/local/cuda-8.0/lib64/libcudart.so.8.0.27
-rw-r--r-- 1 root root 737516 May 8 02:00 /usr/local/cuda-8.0/lib64/libcudart_static.a
-rwxr-xr-x 1 root root 60696704 Sep 24 09:12 /usr/local/cuda-8.0/lib64/libcudnn.so
-rwxr-xr-x 1 root root 60696704 Sep 24 09:12 /usr/local/cuda-8.0/lib64/libcudnn.so.5
-rwxr-xr-x 1 root root 60696704 Sep 24 09:12 /usr/local/cuda-8.0/lib64/libcudnn.so.5.1.3
-rw-r--r-- 1 root root 59715990 Sep 24 09:12 /usr/local/cuda-8.0/lib64/libcudnn_static.a

If installed from source, provide 
1. The commit hash (git rev-parse HEAD): a63b0cbcabc79531e155a0663a08656debf2fe07
2. The output of bazel version:
.
Build label: 0.3.1- (@non-git)
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Sep 29 22:19:27 2016 (1475187567)
Build timestamp: 1475187567
Build timestamp as int: 1475187567

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by tatatodd** [comment]
@hfutxrg I'm suspecting that there's a mismatch in your source code.

You mention that you've installed from source at commit hash a63b0cb.  But the stack trace above shows files under `/usr/lib/python2.7/site-packages/tensorflow`, which probably isn't where the sources are.

Try to ensure you're actually picking up the code from whereever you put your sources.  See #4200 for a similar issue.

**Comment by hfutxrg** [comment]
I do not understand that. Shouldn't we have two locations? One location is our source, and another location is where we install tensorflow using pip.

In my environment, the tensorflow source is in 
/cm/shared/scratch/rengan/DL/tensorflow

My original post used /usr/lib/python2.7/site-packages/tensorflow as the installation location, but I just change the installation to
/cm/shared/scratch/rengan/packages/usr/lib/python2.7/site-packages/tensorflow

The file system is NFS, so both the source and installation directories are shared by ps server, worker0 and worker1. 

The thread you referred to didn't solve that issue. I also tried to include the source in PYTHONPATH
export PYTHONPATH=/cm/shared/scratch/rengan/DL/tensorflow:$PYTHONPATH

But when I ran the command on any worker node
bazel-bin/inception/imagenet_distributed_train \
--batch_size=64 \
--max_steps=2000 \
--data_dir=/cm/shared/scratch/rengan/Data/imagenet-data \
--job_name='worker' \
--task_id=0 \
--ps_hosts='10.141.0.1:2222' \
--worker_hosts='10.141.0.2:2222,10.141.0.3:2222'

it had error:
Traceback (most recent call last):
  File "/cm/shared/scratch/rengan/DL/models/inception/bazel-bin/inception/imagenet_distributed_train.runfiles/inception/inception/imagenet_distributed_train.py", line 24, in <module>
    import tensorflow as tf
  File "/cm/shared/scratch/rengan/DL/tensorflow/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/cm/shared/scratch/rengan/DL/tensorflow/tensorflow/python/__init__.py", line 60, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/cm/shared/scratch/rengan/DL/tensorflow/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
ImportError: cannot import name pywrap_tensorflow

Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.

**Comment by tatatodd** [comment]
@hfutxrg This is a little confusing.  There are two git repositories:

https://github.com/tensorflow/tensorflow (let's call this the tensorflow repo)
https://github.com/tensorflow/models (let's call this the models repo)

First let's talk about the tensorflow repo.  In general, there are many ways to install the tensorflow repo:
https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#download-and-setup

You're only supposed to pick one of the above ways to install tensorflow.  E.g. if you install via pip, that includes python source files that are consistent with the pip version that you installed.  If instead you install the sources (i.e. via `git clone ...`), that also includes python source files that are consistent.  If you end up with both a pip install and source install, you run the risk of having inconsistent source files.

E.g. it looks like your pip install is under `/usr/lib/python2.7/site-packages/tensorflow`, while your source install is under `/cm/shared/scratch/rengan/DL/tensorflow`.  The problem you're hitting is that these two installs have different python source code.

The confusing part is that people typically install the models repo directly from sources (e.g. `git clone ...`).  I believe you've done that here.  There isn't a good versioning scheme in place between the tensorflow repo and the models repo, so things may get out-of-sync.  And that problem gets worse if you also have multiple version of the tensorflow repo (i.e. both from pip and from sources).

One way to ensure everything is consistent is to install both the tensorflow repo and the models repo from sources.  Another way is to pip-install a nightly version of tensorflow (see https://github.com/tensorflow/tensorflow#installation), and install the models repo from sources.

Let me know if that helps.

**Comment by hfutxrg** [comment]
Hi @tatatodd, 

I installed both tensorflow and models from source. But even installing tensorflow from source, we still need pip to install it in the last step. 

Based on tensorflow document, "When building from source, you will still build a pip package and install that." And the last step is 
"$ sudo pip install /tmp/tensorflow_pkg/tensorflow-0.11.0rc0-py2-none-any.whl"

That's why I have two locations. /cm/shared/scratch/rengan/DL/tensorflow is the location of tensorflow source code. And /usr/lib/python2.7/site-packages/tensorflow is the installed location after installation from source, or where the above command "pip install" installed to.

I think the issue here is the out-of-sync between tensorflow and models repos. Perhaps models used some module not available on tensorflow repo anymore. But inception-v3 in models repo is the only distributed training example I could find. If there is any other distributed training model example in tensorflow repo, please let me know. Thanks.

**Comment by tatatodd** [comment]
@hfutxrg I see, thanks for the explanation.  Yes, in that case I think the issue is that the tensorflow and models repos are out-of-sync.

Wrt distributed training, have you seen the following:
https://github.com/tensorflow/models/tree/master/slim
https://github.com/tensorflow/models/tree/master/slim#training-a-model-from-scratch
https://github.com/tensorflow/models/blob/master/slim/deployment/model_deploy.py

Hope that helps!

**Comment by qingzew** [comment]
I have the same problem, also I found that `image_processing.py` must use `0.11`, because of `tf.image.resize_images`, but in `graph_pb2.py` there is no definitions about `NodeDef`

**Comment by jart** [comment]
Closing due to inactivity. I'll open again with new information. Thanks for helping with support @qingzew.
