### ISSUE TITLE
keras.callbacks.EarlyStopping fails with RuntimeError: basic_string::_S_construct null not valid.

### ISSUE THREAD

**Issue by max0x7ba** [tensorflow/tensorflow#47624]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.5 LTS.
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/a.
- TensorFlow installed from (source or binary): Binary, using `pip install tensorflow`.
- TensorFlow version (use command below): v2.4.0-rc4-71-g582c8d236cb 2.4.0.
- Python version: Python 3.6.9.
- Bazel version (if compiling from source): N/a.
- GCC/Compiler version (if compiling from source): N/a.
- CUDA/cuDNN version: N/a.
- GPU model and memory: N/a.

**Describe the current behavior**
```
Traceback (most recent call last):
  File "./tune.py", line 304, in train2
    keras.callbacks.EarlyStopping(monitor='Alpha', mode="max", patience=1, min_delta=0.0001)
  File "/home/max/python-quant/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
  File "/home/max/python-quant/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/home/max/python-quant/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 855, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/home/max/python-quant/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2943, in __call__
    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
  File "/home/max/python-quant/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1919, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/max/python-quant/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 592, in call
    custom_gradient.copy_handle_data(func_graph_output, outputs[i])
  File "/home/max/python-quant/lib/python3.6/site-packages/tensorflow/python/ops/handle_data_util.py", line 53, in copy_handle_data
    if (target_t.dtype == dtypes.resource or
  File "/home/max/python-quant/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py", line 203, in __eq__
    return self._type_enum == other._type_enum  # pylint: disable=protected-access
RuntimeError: basic_string::_S_construct null not valid
```

**Describe the expected behavior**
No exception, no fail.

**Standalone code to reproduce the issue**
No reproduction yet. The issue happens during hyperparamter tuning, but the specific parameters are unavailable. It happened in 4 trials out of 100.

**Other info / logs** 
Exception message `basic_string::_S_construct null not valid` strongly suggests that `tensorflow` library passes a null pointer into `std::basic_string` constructor, which is a programming error in `tensorflow` code.

**Comment by amahendrakar** [comment]
@max0x7ba,
In order to reproduce the issue reported here, could you please provide the complete code and the dataset you are using. Thanks!
