### ISSUE TITLE
Pip install issue

### ISSUE THREAD

**Issue by alkaris2** [tensorflow/tensorflow#47709]
**System information**
- OS Platform and Distribution: Manjaro Linux
- TensorFlow installed from: Pip
- TensorFlow version: 2.4.1
- Python version: 3.9.2
- Installed using virtualenv? pip? conda?: pip 20.3.1
- GPU model and memory: Asus GTX 1070 8GB OC Snow Edition

**Describe the problem**

An issue with Pip is preventing being able to install Tensorflow just by doing `pip install tensorflow` and can't search for it either with Pip because they've shut down the PyPI XMLRPC Search, which has remained shut down since Jan 12 2021 according to their site status page → https://status.python.org

Attempting to install tensorflow produces the following error;

```
$ pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement tensorflow
ERROR: No matching distribution found for tensorflow
```

and attempting to search for the package produces the following error as mentioned with the search being shut down;

```
$ pip search tensorflow
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 224, in _main
    status = self.run(options, args)
  File "/usr/lib/python3.9/site-packages/pip/_internal/commands/search.py", line 62, in run
    pypi_hits = self.search(query, options)
  File "/usr/lib/python3.9/site-packages/pip/_internal/commands/search.py", line 82, in search
    hits = pypi.search({'name': query, 'summary': query}, 'or')
  File "/usr/lib/python3.9/xmlrpc/client.py", line 1116, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.9/xmlrpc/client.py", line 1456, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.9/site-packages/pip/_internal/network/xmlrpc.py", line 46, in request
    return self.parse_response(response.raw)
  File "/usr/lib/python3.9/xmlrpc/client.py", line 1348, in parse_response
    return u.close()
  File "/usr/lib/python3.9/xmlrpc/client.py", line 662, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault -32500: "RuntimeError: PyPI's XMLRPC API is currently disabled due to unmanageable load and will be deprecated in the near future. See https://status.python.org/ for more information.">
```

**Any other info / logs**

**Comment by ymodak** [comment]
Python 3.9 is not supported currently.
See https://www.tensorflow.org/install/pip#system-requirements

**Comment by ymodak** [comment]
This is marked as feature request. duplicate #44481
Thanks!
