### ISSUE TITLE
I cannot predict with f.data.experimental.bucket_by_sequence_length

### ISSUE THREAD

**Issue by funmathgt** [tensorflow/tensorflow#47736]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.4.1
- Python version: 3.8.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA v11.0, cuDNN 8
- GPU model and memory: Nvidia Quadro P2000 64 GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

I cannot predict with f.data.experimental.bucket_by_sequence_length.

**Describe the expected behavior**

I don't know if there is a bug in my code or there is a bug in the implementation. How come training with dataset using tf.data.experimental.bucket_by_sequence_length is ok, but predicting is not ok? My error has to do with incorrect dimension but isn't that what tf.data.experimental.bucket_by_sequence_length  and assigning shaped of (None, X) are used for?

**Standalone code to reproduce the issue**

```
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

def gen_train():     
         for x, y in zip(X_train, y_train):         
                yield (x, y)  
def gen_val():     
         for x, y in zip(X_test, y_test):         
         yield (x, y)   

X_train_to_dataset = tf.data.Dataset.from_generator(lambda: X_train,  output_types=(tf.float64),  output_shapes=(tf.TensorShape([None, len(X_train[0][0])])))

train_data = tf.data.Dataset.from_generator(gen_train,  output_types=(tf.float64,
tf.float64),output_shapes(tf.TensorShape([None, len(X_train[0][0])]),   tf.TensorShape([None, len(y_train[0][0])])))

  train_data = tf.data.Dataset.zip((train_data.map(lambda c, d: c), train_data.map(lambda a, b: tf.expand_dims(b[:, 1], axis=1))))  

val_data = tf.data.Dataset.from_generator(gen_val,  output_types=(tf.float64, tf.float64),   output_shapes=(tf.TensorShape([None, len(X_train[0][0])]),  tf.TensorShape([None, len(y_train[0][0])])) )  

val_data = tf.data.Dataset.zip((val_data.map(lambda c, d: c), val_data.map(lambda a, b: tf.expand_dims(b[:, 1], axis=1)))) 

def element_length_fn(x, y):     
         return tf.shape(x)[0]   

max_train = len(max(X_train, key=len)) 
min_train = len(min(X_train, key=len)) 
max_val = len(max(X_test, key=len)) 
min_val = len(min(X_test, key=len))  
batch_size = 64 
bucket_boundaries_train = list(np.arange(min_train, max_train, 10)) 
bucket_batch_sizes_train = [batch_size] * (len(bucket_boundaries_train) + 1)
bucket_boundaries_val = list(np.arange(min_val, max_val, 10)) 
bucket_batch_sizes_val = [batch_size] * (len(bucket_boundaries_val) + 1)

  train_data = train_data.apply(tf.data.experimental.bucket_by_sequence_length(
              element_length_func=element_length_fn, 
              bucket_batch_sizes=bucket_batch_sizes_train,
              bucket_boundaries=bucket_boundaries_train ) )  

val_data = val_data.apply( tf.data.experimental.bucket_by_sequence_length(
              element_length_func=element_length_fn, 
              bucket_batch_sizes=bucket_batch_sizes_val,
              bucket_boundaries=bucket_boundaries_val,)

def create_model():     
     i = Input(shape=(None, len(X_train[0][0]))) 
     x = Bidirectional(LSTM(128, return_sequences=True))(i)     
     x = TimeDistributed(Dense(1))(x)     
     return tf.keras.Model(inputs=i, outputs=x)

model = create_model()     
model.compile( loss='mse', optimizer='adam',metrics=[metrics.RootMeanSquaredError()])  
model.fit(train_data,
         epochs=5,
         validation_data=val_data )

NormLayer = preprocessing.Normalization() 
NormLayer.adapt(X_train_to_dataset) 
model = create_model_bdlstm128(NormLayer) 

model.compile( loss='mse',optimizer='adam', metrics=[metrics.RootMeanSquaredError()]) 

model.fit( train_data, epochs=5000,  validation_data=val_data)

y_pred = model.predict(val_data.map(lambda a, b: a))  


```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

The below is the error for ```y_pred = model.predict(val_data.map(lambda a, b: a))  ```:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\ipancorbo\Anaconda3\envs\tf_recsys\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1646, in predict
    all_outputs = nest.map_structure_up_to(batch_outputs, concat, outputs)
  File "C:\Users\ipancorbo\Anaconda3\envs\tf_recsys\lib\site-packages\tensorflow\python\util\nest.py", line 1159, in map_structure_up_to
    return map_structure_with_tuple_paths_up_to(
  File "C:\Users\ipancorbo\Anaconda3\envs\tf_recsys\lib\site-packages\tensorflow\python\util\nest.py", line 1257, in map_structure_with_tuple_paths_up_to
    results = [
  File "C:\Users\ipancorbo\Anaconda3\envs\tf_recsys\lib\site-packages\tensorflow\python\util\nest.py", line 1258, in <listcomp>
    func(*args, **kwargs) for args in zip(flat_path_gen, *flat_value_gen)
  File "C:\Users\ipancorbo\Anaconda3\envs\tf_recsys\lib\site-packages\tensorflow\python\util\nest.py", line 1161, in <lambda>
    lambda _, *values: func(*values),  # Discards the path arg.
  File "C:\Users\ipancorbo\Anaconda3\envs\tf_recsys\lib\site-packages\tensorflow\python\keras\engine\training.py", line 2716, in concat
    return array_ops.concat(tensors, axis=axis)
  File "C:\Users\ipancorbo\Anaconda3\envs\tf_recsys\lib\site-packages\tensorflow\python\util\dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\ipancorbo\Anaconda3\envs\tf_recsys\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1677, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
  File "C:\Users\ipancorbo\Anaconda3\envs\tf_recsys\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 1192, in concat_v2
    _ops.raise_from_not_ok_status(e, name)
  File "C:\Users\ipancorbo\Anaconda3\envs\tf_recsys\lib\site-packages\tensorflow\python\framework\ops.py", line 6862, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [64,29,1] vs. shape[3] = [64,30,1] [Op:ConcatV2] name: concat

```

**Comment by inespancorbo** [comment]
Ok, I realized that this is probably because model.predict returns a bumpy array and thus concatenates every prediction (which are obviously, in my case, not equal size, and hence the concatenation error). Does tf.keras have no solution for this??

**Comment by Saduf2019** [comment]
@inespancorbo 
The code provided is not reproducible, please share a colab gist for us to replicate the error reported.
