### ISSUE TITLE
Dataset Iterator fails with exception: InvalidArgumentError: Requires delta != 0: 0

### ISSUE THREAD

**Issue by LukeBolly** [tensorflow/tensorflow#47750]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.4.1
- Python version: 3.8
- CUDA/cuDNN version: 11.0
- GPU model and memory: GTX 980M

**Describe the current behavior**
Dataset iterator fails intermittently for an unknown reason, with error InvalidArgumentError: Requires delta != 0: 0. Sometimes the error will happen after thousands of iterations, other times the error will happen immediately.

**Describe the expected behavior**
The Dataset Iterator should succeed, or at least provide a useful error message describing what the issue is. I have no idea what delta is or why it is 0.

**Standalone code to reproduce the issue**
I can't provide my full pipeline for IP reasons, though this is generally it. I've basically got a bunch of files that I transform, then sample evenly from.

```
def get_balanced_class_repeating_dataset(folder_list, parser):
    num_files_to_shuffle = 20
    # TODO: fix num_samples to use partition multiple once partitions get big enough
    num_samples_to_shuffle = 200  # some multiple of the size of a partition to improve shuffling
    dataset_array = []
    for folder in folder_list:
        file_count = len(folder_list[folder])
        filename_list = tf.data.Dataset.from_tensor_slices(folder_list[folder]).shuffle(file_count).repeat(-1)
        ds = filename_list.interleave(lambda filename: tf.data.TFRecordDataset(filename), cycle_length=num_files_to_shuffle)  # shuffle the files then interleave 10
        ds = ds.shuffle(num_samples_to_shuffle)
        ds = ds.repeat(-1)  # repeat the shuffled dataset, not the other way around
        dataset_array.append(ds)
    dataset = tf.data.experimental.sample_from_datasets(dataset_array, weights=None, seed=None)
    dataset = dataset.map(lambda record: parser(record))
    return dataset
```

    def get_training_dataset(self):
        dataset = get_balanced_class_repeating_dataset(self.train_files, self._parse_tfrecord_train)
        dataset = dataset.batch(self.batch_size)
        return dataset

**Other info / logs** 
Stack Trace
```
Traceback (most recent call last):
  File "C:\Users\lukeb\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\eager\context.py", line 2113, in execution_mode
    yield
  File "C:\Users\lukeb\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 730, in _next_internal
    ret = gen_dataset_ops.iterator_get_next(
  File "C:\Users\lukeb\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\ops\gen_dataset_ops.py", line 2578, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "C:\Users\lukeb\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\framework\ops.py", line 6862, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Requires delta != 0: 0
	 [[{{node range}}]] [Op:IteratorGetNext]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/health-AI/python/cardiac/v03/train_model.py", line 31, in <module>
    model_trainer.train()
  File "C:\health-AI\python\cardiac\v03\trainers\v1\classifier_trainer_v1.py", line 32, in train
    for train_step, (data, labels) in enumerate(train_ds):
  File "C:\Users\lukeb\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 747, in __next__
    return self._next_internal()
  File "C:\Users\lukeb\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 739, in _next_internal
    return structure.from_compatible_tensor_list(self._element_spec, ret)
  File "C:\Users\lukeb\Anaconda3\envs\tf2\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\lukeb\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\eager\context.py", line 2116, in execution_mode
    executor_new.wait()
  File "C:\Users\lukeb\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\eager\executor.py", line 69, in wait
    pywrap_tfe.TFE_ExecutorWaitForAllPendingNodes(self._handle)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Requires delta != 0: 0
	 [[{{node range}}]]

Process finished with exit code 1
```

**Comment by amahendrakar** [comment]
@LukeBolly,
In the given code snippet, you have defined the functions but are not calling them anywhere. Without a reproducible code, it would be difficult for us to debug the issue. 

> I can't provide my full pipeline for IP reasons

In this case, could you please provide a dummy code to reproduce the issue reported here? Thanks!

**Comment by LukeBolly** [comment]
One of my functions uses tf.range which has a delta parameter so I think that was the cause. It would be nice if the iterator logged which op it was actually failing at though I guess that's not possible when dataset processing is compiled as a graph.
