### ISSUE TITLE
tensorflow.keras.utils.Sequence does not work with TPU

### ISSUE THREAD

**Issue by bjourne** [tensorflow/tensorflow#47769]
Paste the self-contained mwe below into a Google Colab instance. It runs fine if hardware acceleration is CPU or GPU but if it is TPU then the following traceback will be produced:
```
   /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py:1540 convert_to_tensor
        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/constant_op.py:339 _constant_tensor_conversion_function
        return constant(v, dtype=dtype, name=name)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/constant_op.py:265 constant
        allow_broadcast=True)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/constant_op.py:283 _constant_impl
        allow_broadcast=allow_broadcast))
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/tensor_util.py:445 make_tensor_proto
        raise ValueError("None values not supported.")

    ValueError: None values not supported.
```
I suspect the error has something to do with the `element_spec` attribute which is present on `tensorflow.data.Dataset` objects but not on `tensorflow.keras.utils.Sequence` objects. The logic I have implemented in the `RandomBatches` class is, afaik, not reimplementable using the tensorflow.data API.
```
from os import environ
from tensorflow.config import *
from tensorflow.data import *
from tensorflow.distribute import *
from tensorflow.distribute.cluster_resolver import *
from tensorflow.keras import *
from tensorflow.keras.layers import *
from tensorflow.keras.losses import SparseCategoricalCrossentropy
from tensorflow.keras.optimizers import *
from tensorflow.keras.utils import Sequence
from tensorflow.tpu.experimental import *
import numpy as np
import tensorflow as tf

def select_strategy():
    gpus = list_physical_devices('GPU')
    tpu_addr = environ.get('COLAB_TPU_ADDR')
    if not tpu_addr:
        dev = '/GPU:0' if gpus else '/CPU:0'
        return OneDeviceStrategy(device = dev)
    resolver = TPUClusterResolver('grpc://' + tpu_addr)
    experimental_connect_to_cluster(resolver)
    initialize_tpu_system(resolver)
    tpus = list_logical_devices('TPU')
    return TPUStrategy(resolver)
def make_dataset(seq, sl, bs):
    def split_input_target(chunk):
        return chunk[:-1], chunk[1:]
    def flatten_window(win):
        return win.batch(sl + 1, drop_remainder = True)
    source = tf.constant(seq, dtype = tf.int32)
    return Dataset.from_tensor_slices(seq) \
                  .window(sl + 1, sl, drop_remainder = True) \
                  .flat_map(flatten_window) \
                  .map(split_input_target) \
                  .batch(bs, drop_remainder = True)
class RandomBatches(Sequence):
    def __init__(self, d, sl, bs):
        self.d = d
        self.sl = sl
        self.bs = bs
        self.batches = self.random_batches()
    def __len__(self):
        return len(self.d) // self.sl // self.bs
    def on_epoch_end(self):
        self.batches = self.random_batches()
    def random_batches(self):
        hi = len(self.d) - self.sl - 1
        return np.random.randint(hi, size = (len(self), self.bs))
    def __getitem__(self, i):
        d, bs, sl = self.d, self.bs, self.sl
        batch = self.batches[i]
        return (np.array([d[s:s + sl] for s in batch]),
                np.array([d[s + 1:s + sl + 1] for s in batch]))

BS, SL = 128, 256
seq = np.random.randint(100, size = 10_000_000)
with select_strategy().scope():
    inp = Input(shape = (None,), batch_size = BS, dtype = tf.int32)
    embedding = Embedding(input_dim = 100, output_dim = 100)
    lstm = LSTM(512, stateful = False, return_sequences = True)
    time_dist = TimeDistributed(Dense(100))
    out = time_dist(lstm(embedding(inp)))
    model = Model(inputs = [inp], outputs = [out])
    loss = SparseCategoricalCrossentropy(from_logits = True)
    opt = RMSprop(learning_rate = 0.004)
    model.compile(optimizer = opt, loss = loss)
    model.summary()
    model.fit(x = RandomBatches(seq, SL, BS), epochs = 100)
    # model.fit(x = make_dataset(seq, SL, BS), epochs = 100)
```

**Comment by AdityaKane2001** [comment]
@bjourne 
According to `tf.keras.Input` docs
>inp = Input(shape = (None,), batch_size = BS, dtype = tf.int32)


raises `ValueError` as mentioned [here](https://www.tensorflow.org/api_docs/python/tf/keras/Input#raises_1).
AFAIK, you need not mention match size in `Input` layer.

**Comment by bjourne** [comment]
But why does it work when I use the GPU and TPU? 

If I change the definition of the input layer to `inp = Input(shape = (SL,), batch_size = BS, dtype = tf.int64)` I get the following error:
```
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/nest.py", line 659, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/utils/tf_utils.py", line 510, in _to_single_numpy_or_python_type
    x = t.numpy()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 1071, in numpy
    maybe_arr = self._numpy()  # pylint: disable=protected-access
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 1039, in _numpy
    six.raise_from(core._status_to_exception(e.code, e.message), None)  # pylint: disable=protected-access
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnavailableError: 5 root error(s) found.
  (0) Unavailable: {{function_node __inference_train_function_6281}} failed to connect to all addresses
Additional GRPC error information from remote target /job:localhost/replica:0/task:0/device:CPU:0:
:{"created":"@1615650981.567818546","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":4143,"referenced_errors":[{"created":"@1615650981.567817207","description":"failed to connect to all addresses","file":"third_party/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}
         [[{{node MultiDeviceIteratorGetNextFromShard}}]]
         [[RemoteCall]]
         [[IteratorGetNextAsOptional]]
         [[strided_slice_73/_310]]
  (1) Unavailable: {{function_node __inference_train_function_6281}} failed to connect to all addresses
Additional GRPC error information from remote target /job:localhost/replica:0/task:0/device:CPU:0:
:{"created":"@1615650981.567818546","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":4143,"referenced_errors":[{"created":"@1615650981.567817207","description":"failed to connect to all addresses","file":"third_party/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}
         [[{{node MultiDeviceIteratorGetNextFromShard}}]]
         [[RemoteCall]]
         [[IteratorGetNextAsOptional]]
         [[ConstantFoldingCtrl/cond_6/switch_pred/_56_0/_110]]
  (2) Unavailable: {{function_node __inference_train_function_6281}} failed to connect to all addresses
Additional GRPC error information from remote target /job:localhost/replica:0/task:0/device:CPU:0:
:{"created":"@1615650981.567818546","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":4143,"referenced_errors":[{"created":"@1615650981.567817207","description":"failed to connect to all addresses","file":"third_party/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}
         [[{{node MultiDeviceIteratorGetNextFromShard}}]]
         [[RemoteCall]]
         [[IteratorGetNextAsOptional]]
         [[strided_slice_54/_280]]
  (3) Unavailable: {{function_node __inference_train_function_6281}} failed to connect to all addresses
Additional GRPC error information from remote target /job:localhost/replica:0/task:0/device:CPU:0:
:{"created":"@1615650981.567818546","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":4143,"referenced_errors":[{"created":"@1615650981.567817207","description":"failed to connect to all addresses","file":"third_party/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}
         [[{{node MultiDeviceIteratorGetNextFromShard}}]]
         [[RemoteCall]]
         [[IteratorGetNextAsOptional]]
         [[Cast_1/_60]]
  (4) Unavailable: {{function_node __inference_t ... [truncated]
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/tpu_strategy.py", line 738, in async_wait
    context.async_wait()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/context.py", line 2330, in async_wait
    context().sync_executors()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/context.py", line 645, in sync_executors
    pywrap_tfe.TFE_ContextSyncExecutors(self._context_handle)
tensorflow.python.framework.errors_impl.UnavailableError: 5 root error(s) found.
  (0) Unavailable: {{function_node __inference_train_function_6281}} failed to connect to all addresses
Additional GRPC error information from remote target /job:localhost/replica:0/task:0/device:CPU:0:
:{"created":"@1615650981.567818546","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":4143,"referenced_errors":[{"created":"@1615650981.567817207","description":"failed to connect to all addresses","file":"third_party/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}
         [[{{node MultiDeviceIteratorGetNextFromShard}}]]
         [[RemoteCall]]
         [[IteratorGetNextAsOptional]]
         [[strided_slice_73/_310]]
  (1) Unavailable: {{function_node __inference_train_function_6281}} failed to connect to all addresses
Additional GRPC error information from remote target /job:localhost/replica:0/task:0/device:CPU:0:
:{"created":"@1615650981.567818546","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":4143,"referenced_errors":[{"created":"@1615650981.567817207","description":"failed to connect to all addresses","file":"third_party/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}
         [[{{node MultiDeviceIteratorGetNextFromShard}}]]
         [[RemoteCall]]
         [[IteratorGetNextAsOptional]]
         [[ConstantFoldingCtrl/cond_6/switch_pred/_56_0/_110]]
  (2) Unavailable: {{function_node __inference_train_function_6281}} failed to connect to all addresses
Additional GRPC error information from remote target /job:localhost/replica:0/task:0/device:CPU:0:
:{"created":"@1615650981.567818546","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":4143,"referenced_errors":[{"created":"@1615650981.567817207","description":"failed to connect to all addresses","file":"third_party/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}
         [[{{node MultiDeviceIteratorGetNextFromShard}}]]
         [[RemoteCall]]
         [[IteratorGetNextAsOptional]]
         [[strided_slice_54/_280]]
  (3) Unavailable: {{function_node __inference_train_function_6281}} failed to connect to all addresses
Additional GRPC error information from remote target /job:localhost/replica:0/task:0/device:CPU:0:
:{"created":"@1615650981.567818546","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":4143,"referenced_errors":[{"created":"@1615650981.567817207","description":"failed to connect to all addresses","file":"third_party/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}
         [[{{node MultiDeviceIteratorGetNextFromShard}}]]
         [[RemoteCall]]
         [[IteratorGetNextAsOptional]]
         [[Cast_1/_60]]
  (4) Unavailable: {{function_node __inference_t ... [truncated]
2021-03-13 15:56:21.787417: W ./tensorflow/core/distributed_runtime/eager/destroy_tensor_handle_node.h:57] Ignoring an error encountered when deleting remote tensors handles: Invalid argument: Unable to find the relevant tensor remote_handle: Op ID: 812, Output num: 0
Additional GRPC error information from remote target /job:worker/replica:0/task:0:
:{"created":"@1615650981.784021655","description":"Error received from peer ipv4:10.38.153.218:8470","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Unable to find the relevant tensor remote_handle: Op ID: 812, Output num: 0","grpc_status":3}
```
If I change it to `inp = Input(tensor = tf.constant([[0] * SL] * (BS // 8), dtype = tf.int32))` I get:
```
File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py", line 1105, in fit
    callbacks.on_train_batch_end(end_step, logs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/callbacks.py", line 454, in on_train_batch_end
    self._call_batch_hook(ModeKeys.TRAIN, 'end', batch, logs=logs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/callbacks.py", line 296, in _call_batch_hook
    self._call_batch_end_hook(mode, batch, logs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/callbacks.py", line 316, in _call_batch_end_hook
    self._call_batch_hook_helper(hook_name, batch, logs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/callbacks.py", line 356, in _call_batch_hook_helper
    hook(batch, logs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/callbacks.py", line 1020, in on_train_batch_end
    self._batch_update_progbar(batch, logs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/callbacks.py", line 1084, in _batch_update_progbar
    logs = tf_utils.to_numpy_or_python_type(logs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/utils/tf_utils.py", line 514, in to_numpy_or_python_type
    return nest.map_structure(_to_single_numpy_or_python_type, tensors)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/nest.py", line 659, in map_structure
    structure[0], [func(*x) for x in entries],
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/nest.py", line 659, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/utils/tf_utils.py", line 510, in _to_single_numpy_or_python_type
    x = t.numpy()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 1071, in numpy
    maybe_arr = self._numpy()  # pylint: disable=protected-access
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 1039, in _numpy
    six.raise_from(core._status_to_exception(e.code, e.message), None)  # pylint: disable=protected-access
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnavailableError: 8 root error(s) found.
  (0) Unavailable: {{function_node __inference_train_function_6284}} failed to connect to all addresses
Additional GRPC error information from remote target /job:localhost/replica:0/task:0/device:CPU:0:
:{"created":"@1615651392.431855787","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":4143,"referenced_errors":[{"created":"@1615651392.431853148","description":"failed to connect to all addresses","file":"third_party/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}
         [[{{node MultiDeviceIteratorGetNextFromShard}}]]
         [[RemoteCall]]
         [[IteratorGetNextAsOptional]]
         [[strided_slice_73/_310]]
  (1) Unavailable: {{function_node __inference_train_function_6284}} failed to connect to all addresses
...
```
So I don't know how I should define my `Input` layer to make it work with my `tensorflow.keras.utils.Sequence` data.

**Comment by AdityaKane2001** [comment]
Can you try replacing
`model = Model(inputs = [inp], outputs = [out]) `
to
`model = Model(inputs = inp, outputs = out)` ?

**Comment by bjourne** [comment]
Yes. I get the exact same errors.

**Comment by Saduf2019** [comment]
I am able to replicate the issue reported on tf 2.3,2.4 and nightly. please find the [gist here](https://colab.research.google.com/gist/Saduf2019/54a02f595891dcdd90bd4ad3a1499af6/untitled563.ipynb).

**Comment by sachinprasadhs** [comment]
Was able to replicate your issue in Tensorflow 2.5, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/8047b2c9ad32ff894012afa756ba27ef/47769.ipynb). Thanks!
