### ISSUE TITLE
TensorFlow 2.4.1 offline build fails

### ISSUE THREAD

**Issue by marcjoos-phd** [tensorflow/tensorflow#47815]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): RHEL 7.7
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.4.1
- Python version: 3.7.5
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 8.3.0
- CUDA/cuDNN version: 10.2.89/7
- GPU model and memory: V100 

**Describe the problem**

I try to do an offline compilation of TensorFlow. I am able to partially circumvent dependencies download problems through the `--distdir` Bazel flag (locating third parties I got in `./deps` directory):

```
bazel build --config=mkl --config=opt --distdir=deps //tensorflow/tools/pip_package:build_pip_package
```
However, it fails first on two `bazel_rules` retrievals (`io_bazel_rules_go` and `io_bazel_rules_docker`) but I corrected these issues with the following patch in `WORKSPACE`:

```
diff --git a/WORKSPACE b/WORKSPACE
index 9db1d9b80eb..4284b9834cb 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -20,6 +20,40 @@ tf_repositories()
 
 register_toolchains("@local_config_python//:py_toolchain")
 
+# workaround for git fetch bazel_rules_go
+load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
+
+http_archive(
+    name = "io_bazel_rules_go",
+    sha256 = "7c10271940c6bce577d51a075ae77728964db285dac0a46614a7934dc34303e6",
+    urls = [
+        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.26.0/rules_go-v0.26.0.tar.gz",
+        "https://github.com/bazelbuild/rules_go/releases/download/v0.26.0/rules_go-v0.26.0.tar.gz",
+    ],
+)
+
+load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")
+
+go_rules_dependencies()
+
+go_register_toolchains(version = "1.16")
+##
+
+# workaround for git fetch bazel_rules_docker
+load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
+
+http_archive(
+    name = "io_bazel_rules_docker",
+    sha256 = "1698624e878b0607052ae6131aa216d45ebb63871ec497f26c67455b34119c80",
+    strip_prefix = "rules_docker-0.15.0",
+    urls = ["https://github.com/bazelbuild/rules_docker/releases/download/v0.15.0/rules_docker-v0.15.0.tar.gz"],
+)
+
+load("@io_bazel_rules_docker//toolchains/docker:toolchain.bzl",
+    docker_toolchain_configure="toolchain_configure"
+)
+##
+
 load("@io_bazel_rules_closure//closure:defs.bzl", "closure_repositories")
 
 closure_repositories()
```
And now I am stuck in getting `go_sdk`:

```
INFO: Repository go_sdk instantiated at:
  /<path>/<user>/tensorflow-2.4/tensorflow/WORKSPACE:39:23: in <toplevel>
  /dev/shm/cache/bazel/_bazel_<user>/5ce46efa3d3981c979b373758ad421d2/external/io_bazel_rules_go/go/pr
ivate/sdk.bzl:453:28: in go_register_toolchains
  /dev/shm/cache/bazel/_bazel_<user>/5ce46efa3d3981c979b373758ad421d2/external/io_bazel_rules_go/go/pr
ivate/sdk.bzl:129:21: in go_download_sdk
Repository rule _go_download_sdk defined at:
  /dev/shm/cache/bazel/_bazel_<user>/5ce46efa3d3981c979b373758ad421d2/external/io_bazel_rules_go/go/pr
ivate/sdk.bzl:116:35: in <toplevel>
WARNING: Download from https://golang.org/dl/?mode=json&include=all failed: class java.io.IOException 
connect timed out
WARNING: Download from https://golang.google.cn/dl/?mode=json&include=all failed: class java.io.IOExce
ption connect timed out
ERROR: An error occurred during the fetch of repository 'go_sdk':
   Traceback (most recent call last):
        File "/dev/shm/cache/bazel/_bazel_<user>/5ce46efa3d3981c979b373758ad421d2/external/io_bazel_ru
les_go/go/private/sdk.bzl", line 70, column 21, in _go_download_sdk_impl
                ctx.download(
Error in download: java.io.IOException: Error downloading [https://golang.org/dl/?mode=json&include=al
l, https://golang.google.cn/dl/?mode=json&include=all] to /dev/shm/cache/bazel/_bazel_<user>/5ce46efa3
d3981c979b373758ad421d2/external/go_sdk/versions.json: connect timed out
INFO: Repository nasm instantiated at:
  /<path>/<user>/tensorflow-2.4/tensorflow/WORKSPACE:19:16: in <toplevel>
  /<path>/<user>/tensorflow-2.4/tensorflow/tensorflow/workspace.bzl:105:27: in tf_repositories
  /<path>/<user>/tensorflow-2.4/tensorflow/tensorflow/workspace.bzl:58:9: in initialize_third_party
  /<path>/<user>/tensorflow-2.4/tensorflow/third_party/nasm/workspace.bzl:6:29: in repo
Repository rule third_party_http_archive defined at:
  /<path>/<user>/tensorflow-2.4/tensorflow/third_party/repo.bzl:216:43: in <toplevel>
INFO: Repository icu instantiated at:
  /<path>/<user>/tensorflow-2.4/tensorflow/WORKSPACE:19:16: in <toplevel>
  /<path>/<user>/tensorflow-2.4/tensorflow/tensorflow/workspace.bzl:105:27: in tf_repositories
  /<path>/<user>/tensorflow-2.4/tensorflow/tensorflow/workspace.bzl:55:8: in initialize_third_party
  /<path>/<user>/tensorflow-2.4/tensorflow/third_party/icu/workspace.bzl:11:29: in repo
Repository rule third_party_http_archive defined at:
  /<path>/<user>/tensorflow-2.4/tensorflow/third_party/repo.bzl:216:43: in <toplevel>
Internal error thrown during build. Printing stack trace: java.lang.IllegalStateException: Unexpected analysis error: ConfiguredTargetKey{label=//tensorflow/tools/pip_package:build_pip_package, config=BuildConfigurationValue.Key[5571dcfb554a54b9da4a644e7486ba4a135325361c2a73df816ddb7739d121f6]} -> ErrorInfo{exception=Traceback (most recent call last):
        File "/dev/shm/cache/bazel/_bazel_<user>/5ce46efa3d3981c979b373758ad421d2/external/io_bazel_rules_go/go/private/sdk.bzl", line 70, column 21, in _go_download_sdk_impl
                ctx.download(
Error in download: java.io.IOException: Error downloading [https://golang.org/dl/?mode=json&include=all, https://golang.google.cn/dl/?mode=json&include=all] to /dev/shm/cache/bazel/_bazel_<user>/5ce46efa3d3981c979b373758ad421d2/external/go_sdk/versions.json: connect timed out, rootCauses=[REPOSITORY_DIRECTORY:@go_sdk], cycles=[], isCatastrophic=false, rootCauseOfException=REPOSITORY_DIRECTORY:@go_sdk, isDirectlyTransient=false, isTransitivelyTransient=true}, ([ConfiguredTargetKey{label=//tensorflow/tools/pip_package:build_pip_package, config=BuildConfigurationValue.Key[5571dcfb554a54b9da4a644e7486ba4a135325361c2a73df816ddb7739d121f6]}])
[...]
FAILED: Build did NOT complete successfully (229 packages loaded, 3879 targets configured)
Internal error thrown during build. Printing stack trace: java.lang.IllegalStateException: Unexpected analysis error: ConfiguredTargetKey{label=//tensorflow/tools/pip_package:build_pip_package, config=BuildConfigurationValue.Key[5571dcfb554a54b9da4a644e7486ba4a135325361c2a73df816ddb7739d121f6]} -> ErrorInfo{exception=Traceback (most recent call last):
        File "/dev/shm/cache/bazel/_bazel_<user>/5ce46efa3d3981c979b373758ad421d2/external/io_bazel_rules_go/go/private/sdk.bzl", line 70, column 21, in _go_download_sdk_impl
                ctx.download(
Error in download: java.io.IOException: Error downloading [https://golang.org/dl/?mode=json&include=all, https://golang.google.cn/dl/?mode=json&include=all] to /dev/shm/cache/bazel/_bazel_<user>/5ce46efa3d3981c979b373758ad421d2/external/go_sdk/versions.json: connect timed out, rootCauses=[REPOSITORY_DIRECTORY:@go_sdk], cycles=[], isCatastrophic=false, rootCauseOfException=REPOSITORY_DIRECTORY:@go_sdk, isDirectlyTransient=false, isTransitivelyTransient=true}, ([ConfiguredTargetKey{label=//tensorflow/tools/pip_package:build_pip_package, config=BuildConfigurationValue.Key[5571dcfb554a54b9da4a644e7486ba4a135325361c2a73df816ddb7739d121f6]}])
[...]
java.lang.IllegalStateException: Unexpected analysis error: ConfiguredTargetKey{label=//tensorflow/tools/pip_package:build_pip_package, config=BuildConfigurationValue.Key[5571dcfb554a54b9da4a644e7486ba4a135325361c2a73df816ddb7739d121f6]} -> ErrorInfo{exception=Traceback (most recent call last):
        File "/dev/shm/cache/bazel/_bazel_<user>/5ce46efa3d3981c979b373758ad421d2/external/io_bazel_rules_go/go/private/sdk.bzl", line 70, column 21, in _go_download_sdk_impl
                ctx.download(
Error in download: java.io.IOException: Error downloading [https://golang.org/dl/?mode=json&include=all, https://golang.google.cn/dl/?mode=json&include=all] to /dev/shm/cache/bazel/_bazel_<user>/5ce46efa3d3981c979b373758ad421d2/external/go_sdk/versions.json: connect timed out, rootCauses=[REPOSITORY_DIRECTORY:@go_sdk], cycles=[], isCatastrophic=false, rootCauseOfException=REPOSITORY_DIRECTORY:@go_sdk, isDirectlyTransient=false, isTransitivelyTransient=true}, ([ConfiguredTargetKey{label=//tensorflow/tools/pip_package:build_pip_package, config=BuildConfigurationValue.Key[5571dcfb554a54b9da4a644e7486ba4a135325361c2a73df816ddb7739d121f6]}])
[...]
FAILED: Build did NOT complete successfully (229 packages loaded, 3879 targets configured)
```
From what I get, it comes from Bazel internals and TensorFlow dependencies to `io_bazel_rules_go` (that is a bit hard to find since it is not directly in TensorFlow sources, or so it seems).

Is there anyway to circumvent this issue and to build TensorFlow offline?

**Comment by 438-gm-24** [comment]
OS Platform and Distribution (e.g., Linux Ubuntu 20.04): RHEL 7.7
TensorFlow version: 2.4.1
Python version: 3.8.5
CPU 
NVIDIA Corporation GP102
I try to run this code 
python -m CycleGAN_TensorFlow.create_cyclegan_dataset --image_path_a=folder_a --image_path_b=folder_b --dataset_name="horse2zebra_train" --do_shuffle=0

I have this error 
RuntimeError: Input pipelines based on Queues are not supported when eager execution is enabled. Please use tf.data to ingest data into your model instead.

**Comment by marcjoos-phd** [comment]
> OS Platform and Distribution (e.g., Linux Ubuntu 20.04): RHEL 7.7
> TensorFlow version: 2.4.1
> Python version: 3.8.5
> CPU
> NVIDIA Corporation GP102
> I try to run this code
> python -m CycleGAN_TensorFlow.create_cyclegan_dataset --image_path_a=folder_a --image_path_b=folder_b --dataset_name="horse2zebra_train" --do_shuffle=0
> 
> I have this error
> RuntimeError: Input pipelines based on Queues are not supported when eager execution is enabled. Please use tf.data to ingest data into your model instead.

You should open another issue as it is not related with the original one.

**Comment by kevint324** [comment]
I'm suffering from the same issue. any updates? @angerson

**Comment by tilakrayal** [comment]
@marcjoos-phd,
I tried to replicate the issue on tensorflow v2.9 with Bazel 5.0.0 and it was not failing as before. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/a5d0b2766e14c9d8b13f7065088ceb8c/tensorflow-ranking.ipynb) and confirm if the issue still persists. Thank you!

**Comment by rookie-z-x** [comment]
When I build tensorflow v2.13 with bazel 5.3.0 ,  I'm suffering from the same issue. any updates?
