### ISSUE TITLE
`tf.scan` has Unexpected Behavior on Python CLI/Shell

### ISSUE THREAD

**Issue by craymichael** [tensorflow/tensorflow#4781]
### Version Info

'0.10.0rc0'
OS: Ubuntu
### Issue

While this doesn't affect runtime behavior, using the high level function `tf.scan` in the python shell results in unexpected behavior. Running the op whilst functional yields expected results. Running again with bad parameters (wrong dtype) raises exception, which is also expected. Running the original op again raises the same exception, which is not expected.
### To Reproduce

Via python CLI, run a working `tf.scan` function, run one that doesn't work, then run the original.

```
>>> import tensorflow as tf

>>> tf.Session().run(tf.scan(lambda a, x: [a[0] + 1, tf.to_int64(0)], tf.constant([1,2,3,4,5],dtype=tf.int64), initializer=[tf.to_int64(-1), tf.to_int64(0)]))

[array([0, 1, 2, 3, 4]), array([0, 0, 0, 0, 0])]

>>> tf.Session().run(tf.scan(lambda a, x: [1, tf.to_int64(0)], tf.constant([1,2,3,4,5],dtype=tf.int64), initializer=[tf.to_int64(-1), tf.to_int64(0)]))
E tensorflow/core/client/tensor_c_api.cc:485] Input 1 of node scan_1/while/Merge_1 was passed int32 from scan_1/while/NextIteration_1:0 incompatible with expected int64.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 382, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 655, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 723, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 743, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InvalidArgumentError: Input 1 of node scan_1/while/Merge_1 was passed int32 from scan_1/while/NextIteration_1:0 incompatible with expected int64.

>>> tf.Session().run(tf.scan(lambda a, x: [a[0] + 1, tf.to_int64(0)], tf.constant([1,2,3,4,5],dtype=tf.int64), initializer=[tf.to_int64(-1), tf.to_int64(0)]))
E tensorflow/core/client/tensor_c_api.cc:485] Input 1 of node scan_1/while/Merge_1 was passed int32 from scan_1/while/NextIteration_1:0 incompatible with expected int64.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 382, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 655, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 723, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 743, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InvalidArgumentError: Input 1 of node scan_1/while/Merge_1 was passed int32 from scan_1/while/NextIteration_1:0 incompatible with expected int64.
```

**Comment by tatatodd** [comment]
I can reproduce the behavior, and it seems like a bug to me.  @ebrevdo might have some thoughts.

**Comment by ebrevdo** [comment]
There are two problems:

1. always create all your nodes before passing them to session.run.  even if it's a new local session.  strange things can happen if you don't.  this is because when you call session.run, it serializes your graph; and if you add new nodes after this, it'll serialize more of the graph and upload that.  but sometimes it'll still use some cached nodes.  @yuanbyu this may be a bug here.

2. this code:

```
tf.Session().run(tf.scan(lambda a, x: [1, tf.to_int64(0)], tf.constant([1,2,3,4,5],dtype=tf.int64), initializer=[tf.to_int64(-1), tf.to_int64(0)]))
```

is incorrect: replace the body with `[tf.to_int64(1), tf.to_int64(0)]` and it'll work.

to summarize:

```
tf.Session().run(tf.scan(lambda a, x: [1, tf.to_int64(0)], tf.constant([1,2,3,4,5],dtype=tf.int64), initializer=[tf.to_int64(-1), tf.to_int64(0)]))
...
InvalidArgumentError: Input 1 of node scan/while/Merge_1 was passed int32 from scan/while/NextIteration_1:0 incompatible with expected int64.


tf.reset_default_graph()

tf.Session().run(tf.scan(lambda a, x: [tf.to_int64(1), tf.to_int64(0)], tf.constant([1,2,3,4,5],dtype=tf.int64), initializer=[tf.to_int64(-1), tf.to_int64(0)]))

[array([1, 1, 1, 1, 1]), array([0, 0, 0, 0, 0])]
```

but really, it's not idiomatic to create new sessions and immediately add new nodes to them and execute at the same time.  create your nodes first, and when you're done execute all your session.run calls.

**Comment by craymichael** [comment]
Ah, thanks for the response! That's generally the way I go about my sessions with the exception of fooling around in the Python shell, but good to know the possible cause of this.
