### ISSUE TITLE
Conv2D output not compatible with ZeroPadding3D input

### ISSUE THREAD

**Issue by markstrefford** [tensorflow/tensorflow#47829]
I need to zero pad outputs of multiple CNN layers in order to concatenate them together as input to another layer. 

A simple way to demonstrate this is:

```
x = Input(shape=(256, 256, 3))
x = Conv2D(32, (2,2), (2,2))(x)     # 1st CNN layer
x = ZeroPadding3D(padding=(2, 2, 2))(x)
```

This fails on the output of the CNN layer, irrespective of what values I provide for padding.

The error I get is:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Mark\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 951, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "C:\Users\Mark\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1090, in _functional_construction_call
    outputs = self._keras_tensor_symbolic_call(
  File "C:\Users\Mark\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 822, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "C:\Users\Mark\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 862, in _infer_output_signature
    self._maybe_build(inputs)
  File "C:\Users\Mark\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 2684, in _maybe_build
    input_spec.assert_input_compatibility(
  File "C:\Users\Mark\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\keras\engine\input_spec.py", line 219, in assert_input_compatibility
    raise ValueError('Input ' + str(input_index) + ' of layer ' +
ValueError: Input 0 of layer zero_padding3d_4 is incompatible with the layer: expected ndim=5, found ndim=4. Full shape received: (None, 128, 128, 32)
```
I have looked at the example of ZeroPadding2D and this appears to work OK [in the Pix2Pix example](https://www.tensorflow.org/tutorials/generative/pix2pix), but only works on the first 2 dimensions. I need to pad 3 dimensions.

The documentation for [ZeroPadding3D](https://www.tensorflow.org/api_docs/python/tf/keras/layers/ZeroPadding3D) also does not show how this layer can be used in a network.

Output of `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`:

`v2.4.0-49-g85c8b2a817f 2.4.1`
Python version = 3.8.5
OS = Windows 10 (Latest developer release)
NVIDIA-SMI 465.51       
Driver Version: 465.51       
CUDA Version: 11.3
GPU = RTX3070 (8GB)
Tensorflow installed from binary (pip)

The expected behaviour is that I can use ZeroPadding3D as a layer within my CNN to pad the output of a convolutional layer in all 3 dimensions.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/02297354e15b5036f1b88a48c117ffaf/47829.ipynb). Thanks!

**Comment by ymodak** [comment]
ZeroPadding3D expects a [5D tensor](https://www.tensorflow.org/api_docs/python/tf/keras/layers/ZeroPadding3D#input_shape) whereas your input Conv2D gives [4D tensor](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Conv2D#output_shape_2).
Switching to ZeroPadding2D  for Conv2D works;
```python
x = Input(shape=(256, 256, 3))
x = Conv2D(32, (2,2), (2,2))(x)     # 1st CNN layer
x = ZeroPadding2D(padding=(2,2))(x)
```
