### ISSUE TITLE
Incompatibility between `set_visible_devices()` and `from_dlpack()`

### ISSUE THREAD

**Issue by karlhigley** [tensorflow/tensorflow#47866]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.10
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.4.0-49-g85c8b2a817f 2.4.1
- Python version: 3.8.8
- CUDA/cuDNN version: 11.2
- GPU model and memory: GTX 1080Ti 11GB

**Describe the current behavior**

After selecting which GPU to use via `tf.config.experimental.set_visible_devices()`, converting external arrays from dlpack with `tf.experimental.dlpack.from_dlpack()` only works for device 0. Using other devices results in the error `InvalidArgumentError: GPU:1 unknown device.`

**Describe the expected behavior**

Converting external arrays from dlpack with `tf.experimental.dlpack.from_dlpack()` should work for all devices.

**Standalone code to reproduce the issue**
```python
import cupy
import random

import tensorflow as tf

# gpu_to_use = 0      # Works
gpu_to_use = 1        # Errors

gpus = tf.config.experimental.list_physical_devices("GPU")
if gpus:
    tf.config.experimental.set_visible_devices(gpus[gpu_to_use], "GPU")

# Converting from TF to CuPy with dlpack works for both devices
tensor = tf.random.uniform((10,))

dltensor = tf.experimental.dlpack.to_dlpack(tensor)
array1 = cupy.fromDlpack(dltensor)

# Converting from CuPy to TF with dlpack only works for device 0
array1 = cupy.array([random.uniform(0.0, 1.0) for i in range(10)], dtype=cupy.float32)
dltensor = array1.toDlpack()
x = tf.experimental.dlpack.from_dlpack(dltensor)

# Using device 1 results in the following error

# Traceback (most recent call last):
#   File "examples/multi-gpu/tf-dlpack-repro.py", line 22, in <module>
#     x = tf.experimental.dlpack.from_dlpack(dltensor)
#   File "/home/karl/miniconda3/envs/nvtabular_dev_11.0/lib/python3.8/site-packages/tensorflow/python/dlpack/dlpack.py", line 66, in from_dlpack
#     return pywrap_tfe.TFE_FromDlpackCapsule(dlcapsule, context.context()._handle)
# tensorflow.python.framework.errors_impl.InvalidArgumentError: GPU:1 unknown device.
```

**Comment by VoVAllen** [comment]
If we use `tf.config.experimental.set_visible_devices(gpus[1])`, the real gpu 1 will be labeled as 0 or 1 in tensorflow? This brings in the inconsistent device labeling between tensorflow and other framework, which is not ideal. Could you use `CUDA_VISIBLE_DEVICES` to control this instead?

**Comment by karlhigley** [comment]
Unfortunately, we can't use `CUDA_VISIBLE_DEVICES`, because we're trying to integrate Horovod and need to pick which GPU to use after Tensorflow has already been initialized. :slightly_frowning_face: 

Given the possibility of different device numbering across frameworks, it seems like Tensorflow should be using the physical (instead of logical) device number when converting DLpack objects coming from other frameworks. Is there a reasonable way to do that?

**Comment by amahendrakar** [comment]
@rmothukuru,
I was able to reproduce the issue with TF v2.4 and TF-nightly. Please check the attached screenshot for reference. 

![Screenshot 2021-03-18 9 22 42 PM](https://user-images.githubusercontent.com/57165142/111658196-21199880-8832-11eb-9b7d-8ff492e21958.png)


Thanks!

**Comment by VoVAllen** [comment]
I didn't see an easy way to resolve this issue. Probably Tensorflow should preserve the GPU labeling on the logical devices after `set_visible_device`

**Comment by sanjoy** [comment]
OOC, how did `array1`'s device get to be GPU:1?  Is it inferring that from the earlier call to `cupy.fromDlpack`?

> Probably Tensorflow should preserve the GPU labeling on the logical devices after set_visible_device

Can `TFE_FromDlpackCapsule` reconstruct that from `tf.config.experimental.get_visible_devices("GPU")` and `tf.config.experimental.list_visible_devices("GPU")`?

**Comment by karlhigley** [comment]
@sanjoy I'm not entirely sure, but the same error happens even when skipping the earlier call to `cupy.fromDlpack`, so I'm guessing it's a side effect of `set_visible_devices` somehow?

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF nightly-2.6.0.dev20210603,please find the gist[ here](https://colab.research.google.com/gist/sushreebarsa/8957dc224050ebcc25a06df67c1e517d/untitled164.ipynb?authuser=1)..Thanks !

**Comment by wjxiz1992** [comment]
Reproduced on TF 2.5.0.

**Comment by TheonlyIcebear** [comment]
I am getting this same error, except I never ran set_visible_devices:

```
Traceback (most recent call last):
  File "C:\Users\ekila\Downloads\Neural Network Framkework\xor.py", line 36, in <module>
    for idx, cost in enumerate(network.fit(xdata, ydata, learning_rate=0.01, batch_size = batch_size, epochs = 1000)):
  File "C:\Users\ekila\Downloads\Neural Network Framkework\utils\network.py", line 165, in fit
    model_output = self.forward(selected_xdata)
  File "C:\Users\ekila\Downloads\Neural Network Framkework\utils\network.py", line 84, in forward
    activations = layer.forward(activations, training=training)
  File "C:\Users\ekila\Downloads\Neural Network Framkework\utils\layers.py", line 376, in forward
    input_activations = Processing.to_tensorflow(input_activations)
  File "C:\Users\ekila\Downloads\Neural Network Framkework\utils\functions.py", line 31, in to_tensorflow
    array = from_dlpack(cp.ascontiguousarray(array).toDlpack())
  File "C:\Users\ekila\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\dlpack\dlpack.py", line 63, in from_dlpack
    return pywrap_tfe.TFE_FromDlpackCapsule(dlcapsule, context.context()._handle)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: GPU:0 unknown device.
```
