### ISSUE TITLE
undefined symbol: PyUnicode_AsUTF8String

### ISSUE THREAD

**Issue by lorenzoferrone** [tensorflow/tensorflow#479]
Hi, when I try to do `import tensorflow` I receive the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 50, in <module>
    from tensorflow.python.framework.framework_lib import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/framework_lib.py", line 62, in <module>
    from tensorflow.python.framework.ops import Graph
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 40, in <module>
    from tensorflow.python.framework import versions
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/versions.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: PyUnicode_AsUTF8String
```

OS is Ubuntu 14.04, and I get the same error with both python2.7 and python3.4.

The binaries works fine, but I'm trying to install from source cause I need support for CUDA 3.0.

Thanks

**Comment by girving** [comment]
Is the version of Python you passed to `./configure` the same as the one you're importing tensorflow from?

**Comment by lorenzoferrone** [comment]
I thought it was but I was probably mistaken (?).
Redoing every steps in the installation guide fixed the problem form me.

**Comment by girving** [comment]
We would ideally provide a better error message in this case, but I'm not sure how to do it.  By the time we'd realize the problem, linking has already taken place.

**Comment by penguin42** [comment]
I hit the same missing symbol building on Fedora 24; I'd configured with python3 so I'm wondering if something is trying to use a different version at some stage.
This is from the end of:
bazel build -c opt //tensorflow/tools/pip_package:build_pip_package


ERROR: /discs/more/git/tensorflow/tensorflow/contrib/session_bundle/example/BUILD:38:1: Executing genrule //tensorflow/contrib/session_bundle/example:half_plus_two failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Traceback (most recent call last):
  File "/home/dg/.cache/bazel/_bazel_dg/9495d50bfa6d27aea1920e0978e97106/execroot/tensorflow/bazel-out/host/bin/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/org_tensorflow/tensorflow/contrib/session_bundle/example/export_half_plus_two.py", line 32, in <module>
    import tensorflow as tf
  File "/home/dg/.cache/bazel/_bazel_dg/9495d50bfa6d27aea1920e0978e97106/execroot/tensorflow/bazel-out/host/bin/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/org_tensorflow/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/home/dg/.cache/bazel/_bazel_dg/9495d50bfa6d27aea1920e0978e97106/execroot/tensorflow/bazel-out/host/bin/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 48, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/dg/.cache/bazel/_bazel_dg/9495d50bfa6d27aea1920e0978e97106/execroot/tensorflow/bazel-out/host/bin/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/home/dg/.cache/bazel/_bazel_dg/9495d50bfa6d27aea1920e0978e97106/execroot/tensorflow/bazel-out/host/bin/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: /home/dg/.cache/bazel/_bazel_dg/9495d50bfa6d27aea1920e0978e97106/execroot/tensorflow/bazel-out/host/bin/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: PyUnicode_AsUTF8String
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 811.088s, Critical Path: 661.59s

**Comment by bman7903** [comment]
make sure yout python-config is pointing to your python bin.  For simplicity just use python2 for building and you wont have to fix as much

**Comment by zhuihunmiling** [comment]
我也遇到了同样了问题，在CentOS 7 下，这是由于Python编译时没有指定编码导致的，详细的解决过程参见http://www.jianshu.com/p/b0b8ab2be12c，当然，Ubuntu系统和CentOS不一样，请注意甄别。祝你好运！

**Comment by artuntun** [comment]
Hi, I am encountering the same error. 
I have two Python installations, one of them works fine(2.7.6) with TF and the other(2.7.13) gets this error. I installed separaetly in each one.

@girving How can I check where ./configure is pointing?

**Comment by girving** [comment]
@artuntun Look in `tensorflow/tools/python_bin_path.sh`.
