### ISSUE TITLE
iOS cannot run the new trained Inception v1 model <no registered kernels>

### ISSUE THREAD

**Issue by civilman628** [tensorflow/tensorflow#4790]
### Environment info

iOS
### steps:

1, i train inception v1 (slim) on a subset of ImageNet dataset (269 of 1000)
2, convert .ckpt into .pb by freeze_graph
3, convert .pb file into 8bit precision
4, load into iOS and run
### Logs

simple/RunModelViewController.mm:222] Running model failed: Invalid argument: **No OpKernel was registered to support Op 'RandomUniform' with these attrs.  Registered kernels:**

 <**no registered kernels**>

[[Node: InceptionV1/Logits/Dropout_0b/dropout/random_uniform/RandomUniform = RandomUniform[T=DT_INT32, _output_shapes=[[128,1,1,1024]], dtype=DT_FLOAT, seed=0, seed2=0](InceptionV1/Logits/Dropout_0b/dropout/Shape)]]

I tensorflow/core/framework/op_kernel.cc:802] OpKernel ('op: "ArgMin" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_INT32 } } } host_memory_arg: "dimension"')

I tensorflow/core/framework/op_kernel.cc:802] OpKernel ('op: "ArgMin" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_FLOAT } } } host_memory_arg: "dimension"')

I tensorflow/core/framework/op_kernel.cc:802] OpKernel ('op: "ArgMax" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_INT32 } } } host_memory_arg: "dimension"')

I tensorflow/core/framework/op_kernel.cc:802] OpKernel ('op: "ArgMax" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_FLOAT } } } host_memory_arg: "dimension"')

I tensorflow/core/framework/op_kernel.cc:802] OpKernel ('op: "AvgPoolGrad" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_FLOAT } } } host_memory_arg: "orig_input_shape"')

I tensorflow/core/framework/op_kernel.cc:802] OpKernel ('op: "BatchNormWithGlobalNormalizationGrad" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_FLOAT } } }')

I tensorflow/core/framework/op_kernel.cc:802] OpKernel ('op: "BroadcastGradientArgs" device_type: "GPU" host_memory_arg: "s0" host_memory_arg: "s1" host_memory_arg: "r0" host_memory_arg: "r1"')

I tensorflow/core/framework/op_kernel.cc:802] OpKernel ('op: "BroadcastGradientArgs" device_type: "CPU" host_memory_arg: "s0" host_memory_arg: "s1" host_memory_arg: "r0" host_memory_arg: "r1"')

I tensorflow/core/framework/op_kernel.cc:802] OpKernel ('op: "BiasAddGrad" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_INT32 } } }')

I tensorflow/core/framework/op_kernel.cc:802] OpKernel ('op: "BiasAddGrad" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_FLOAT } } }')

I tensorflow/core/framework/op_kernel.cc:802] OpKernel ('op: "BiasAddV1" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_INT32 } } }')

I tensorflow/core/framework/op_kernel.cc:802] OpKernel ('op: "BiasAddV1" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_FLOAT } } }')

I tensorflow/core/framework/op_kernel.cc:802] OpKernel ('op: "CheckNumerics" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_FLOAT } } }')

I tensorflow/core/framework/op_kernel.cc:802] OpKernel ('op: "ConcatOffset" device_type: "GPU" host_memory_arg: "concat_dim" host_memory_arg: "shape" host_memory_arg: "offset"')

I tensorflow/core/framework/op_kernel.cc:802] OpKernel ('op: "ConcatOffset" device_type: "CPU"')

I tensorflow/core/framework/op_kernel.cc:802] OpKernel ('op: "Concat" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_INT32 } } } host_memory_arg: "concat_dim"')

I tensorflow/core/framework/op_kernel.cc:802] OpKernel ('op: "Concat" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_FLOAT } } } host_memory_arg: "concat_dim"')

I tensorflow/core/framework/op_kernel.cc:802] OpKernel ('op: "Concat" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_QUINT8 } } } host_memory_arg: "concat_dim"')

I tensorflow/core/framework/op_kernel.cc:802] OpKernel ('op: "Concat" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_QINT8 } } } host_memory_arg: "concat_dim"')

I tensorflow/core/framework/op_kernel.cc:802] OpKernel ('op: "Concat" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_QUINT16 } } } host_memory_arg: "concat_dim"')

I tensorflow/core/framework/op_kernel.cc:802] OpKernel ('op: "Concat" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_QINT16 } } } host_memory_arg: "concat_dim"')

I tensorflow/core/framework/op_kernel.cc:802] OpKernel ('op: "Concat" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_QINT32 } } } host_memory_arg: "concat_dim"')

I tensorflow/core/framework/op_kernel.cc:802] OpKernel ('op: "Concat" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_BFLOAT16 } } } host_memory_arg: "concat_dim"')

I tensorflow/core/framework/op_kernel.cc:802] OpKernel ('op: "Placeholder" device_type: "GPU"')

I tensorflow/core/framework/op_kernel.cc:802] OpKernel ('op: "Placeholder" device_type: "CPU"')

**Comment by civilmanxx** [comment]
i do not know why the .pb file, which i download from below, convert into 8bit only take 4M, but my trained inception v1 model .pb file convert to 8bit takes 6.5M. 

https://storage.googleapis.com/download.tensorflow.org/models/inception5h.zip

BTW, **freeze_graph** already move out unused nodes for prediction phase, is that right? 

The .ckpt file size I get is 23.6M but .pb file size is 24M. it seems remove nothing.

dropout should not be in the prediction phase, but i can see dropout in error log.

**Comment by andrewharp** [comment]
freeze_graph will not remove any nodes. For that you need [optimize_for_inference.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/optimize_for_inference.py) (or strip_unused, but I believe that is deprecated now).

**Comment by andrewharp** [comment]
@petewarden Is there any reason to keep strip_unused around now that you've added optimize_for_inference?

**Comment by petewarden** [comment]
@andrewharp No, I don't think it is useful, so it might make things less confusing to remove strip_unused.

**Comment by civilmanxx** [comment]
@andrewharp I try  optimize_for_inference.py, But it seems that the fix is still there.


1, I freeze the .ckpt file into .pb file, which size is 24M
2, run optimize_for_inference.py to ouput a new file. This new .pb file is 23.9M, which mean very limited nodes are removed, as size drop 0.1M.
3, convert this .pd file into 8bit file, which size is 6.5M as well.
4, load into iOS and run. the error is the same:

No OpKernel was registered to support Op 'RandomUniform' with these attrs. Registered kernels

\<no registered kernels\>

**Comment by petewarden** [comment]
I'm surprised to see RandomUniform used in an inference graph. I believe you might need to set training=False when you create your model to get rid of ops like dropout that might use this, but I'm cc-ing @sguada since I'm hoping he might have some ideas on this?

**Comment by civilmanxx** [comment]
I just set --training=False for optimize_for_inference.py script, but the output file size is still 23.9M

**Comment by petewarden** [comment]
The output file size isn't significant. Most of the space is taken up by a few large weight parameter sets, so a lot of nodes can be removed without it changing the length significantly. Does the resulting model still fail with the same error?

**Comment by civilmanxx** [comment]
I just carefully review the script **optimize_for_inference.py**. It seems that there is no parameter for  --training=False/True. I cann't see this parameter. only 4 parameters below:

--input=frozen_inception_graph.pb \ 
--output=optimized_inception_graph.pb \ 
--input_names=Mul \ 
--output_names=softmax

**Comment by petewarden** [comment]
It's a parameter for the slim training library. I don't know the details, but I've seen it show up in similar issues, so I cc-ed @sguada for more info.

**Comment by civilmanxx** [comment]
Is there any update on this issue?

**Comment by petewarden** [comment]
No, I'm awaiting response from @sguada on the slim question.

**Comment by sguada** [comment]
To get the version of the graph for inference, just built the network passing is_training=False.

https://github.com/tensorflow/tensorflow/blob/754048a0453a04a761e112ae5d99c149eb9910dd/tensorflow/contrib/slim/python/slim/nets/inception_v1.py#L248

**Comment by civilmanxx** [comment]
The folder i use is from **Model** folder for inception v1.

https://github.com/tensorflow/models/tree/master/slim 

but not **contrib** foler

https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/slim/python/slim

I think they should be the same one, is that right?

So i should change **is_training=True** to **False** of the line below for training. correct me if wrong.

https://github.com/tensorflow/models/blob/master/slim/train_image_classifier.py#L424

**Comment by civilmanxx** [comment]
I get new error: for **'FIFOQueue'** 

Could not create TensorFlow Graph: Invalid argument: No OpKernel was registered to support Op 'FIFOQueue' with these attrs.  Registered kernels:

  <no registered kernels>

[[Node: prefetch_queue/fifo_queue = FIFOQueue[_output_shapes=[[2]], capacity=2, component_types=[DT_FLOAT, DT_FLOAT], container="", shapes=[[128,224,224,3], [128,269]], shared_name=""]()]]

F /Users/Bonan1/tensorflow/tensorflow/contrib/ios_examples/camera/CameraExampleViewController.mm:392] Couldn't load model: Invalid argument: No OpKernel was registered to support Op 'FIFOQueue' with these attrs.  Registered kernels:

  <no registered kernels>

**Comment by civilmanxx** [comment]
If Google publish a tensorflow iOS version is only want to prove that tensorflow **could** run under iOS, but not want to support iOS strategically, since iOS is from Apple, then it should be clearly point out on the website that Only the published iOS example works on iOS, but not any new user defined, even for inception v1.

**Comment by civilmanxx** [comment]
Pixel can beat iPhone? Maybe...

**Comment by petewarden** [comment]
There's a guide to preparing models for mobile devices here:
https://petewarden.com/2016/09/27/tensorflow-for-mobile-poets/
The problem you're hitting (which is true across both Android and iOS versions) is that only certain ops are included in the library by default:

> Mobile devices have limited amounts of memory, and apps need to be downloaded, so by default the iOS version of TensorFlow only includes support for operations that are common in inference and don’t have large external dependencies. You can see the list of supported ops in the tensorflow/contrib/makefile/tf_op_files.txt file.

In this case, using a FifoQueue op for inference doesn't make much sense, so I believe you should be able to fix it by running the optimize_for_inference script as described in the tutorial. The tricky part will be figuring out the correct input and output node names for the model, but you'll need those when you run it, so hopefully you have them already.

**Comment by civilmanxx** [comment]
How do I know why there is a **FifoQueue** in inception v1 mode? 

What I use is exactly the guideline on the Tensorflow website and the info from @sguada above. I only train a subset (269 of 1000) of ImageNet dataset on inception v1 slim model and set **--is_training=False** as provided by @sguada. It is supposed to remove all training nodes from **graph.pbtxt**, which are not used for inference phase.

However, after I get .ckpt files and freeze the graph to deploy to iOS device, it still does not work. I meet new error: **No OpKernel was registered to support Op 'FIFOQueue' with these attrs.**

I can't see any **Official Guideline** on Tensorflow website about how to **REPRODUCE** that inception v1 model .pb file for iOS. It is all about **"CAN DO",** but not **"HOW TO DO".**  The key step is skipped. So how do you let other one to believe Tensorflow is a really **OPEN** framework? **弄巧成拙**  is not a smart choice.

We can't develop an app that one feature only support Android, but not support iOS. If only one works, then we will drop all. A global view is critical. 

I do not believe any developer will drop iOS platform just become android support Deep Learning model.

**Comment by civilmanxx** [comment]
@sguada do you mean I run twice? Run once with **is_training=False** to get a graph def just for inference nodes purpose (stop the process once I get this file), because if I set **is_training=False**, the loss do not goes down, which mean the network does not converge.

after I get the graph def file for inference nodes, I still need use the .ckpt file which is created under **is_training=True**, since this .ckpt file contains the correct values for weights.

I use the graph def under **is_training=False** + .ckpt file under **is_training=True** to  get a freeze graph. Is that right?

**Comment by civilmanxx** [comment]
I already modify the code of **retrain.py** to support Inception V1 model. I will check in and share with community.

**Comment by vade** [comment]
I'm running into this issue on desktop - running optimize_for_inference drastically changes my model size, but it also appears to change the output tensors names, even if I specify the input and output tensors Im interested in the script.

I understand that optimize_for_inference changes the graph, but should the i/o node names not stay the same since, well, you're asking the script to do so?

Apologies for poking at a closed issue, trying to wrap my head around this. 

Specifics are here: http://stackoverflow.com/questions/40747431/running-optimize-for-inference-on-inceptionv1-results-in-different-output-tensor

**Comment by AdamWP** [comment]
I made a model, froze it, optimized for inference, yet I'm getting an error message about FIFOQueue on iOS

"Could not create TensorFlow Graph: Invalid argument: No OpKernel was registered to support Op 'FIFOQueue' with these attrs. Registered devices: [CPU], Registered kernels: <no registered kernels>
[[Node: fifo_queue = FIFOQueue[capacity=30, component_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], container="", shapes=[[640,480,3], [300,1,2], [300,1,4]], shared_name=""]()]]"

I even tried setting is_training=False in tensorflow/contrib/slim/python/slim/nets/inception_v1.py before training and getting my input_graph.pb

Did you ever find a solution @civilman628 ?   Or is FIFOQueue not supported in TensorFlow for iOS?

**Comment by civilman628** [comment]
First, Google does not plan to support iOS well. Tensorflow is a very sham open source project. They let users to help them test and find bugs only, but not wish fully support if you meet problems.

You can see my code in #7172 about how to get .pbtxt file and freeze the models in .pb files like inception v1-v4 and inception_resnetv2...  The first node is "Placeholder", which accept a image, like [1,224,224,3] but not FIFOQueue anymore.

I already load **inception v2** into iOS device. You may meet the issue like #5764. just update one line code can fix the issue.

**Comment by AdamWP** [comment]
I added "tensorflow/core/kernels/fifo_queue_op.cc" to tensorflow/contrib/makefile/tf_op_files.txt then ran compile_ios_tensorflow.sh .  It seems to have done the trick.

**Comment by civilman628** [comment]
this way will retain many unnecessary nodes, which are not needed for inference phase. you can print out the nodes to see.

**Comment by aselle** [comment]
The bottom line is that android and ios have a subset of all ops. They need to be stripped down to have smaller binaries. Our engineers use TensorFlow for Android and IOS apps, but the process of stripping a model is currently not as easy as we would like. @civilman628, do you have any idea to contribute on how to make this process better? If not, you could certainly submit a pull request to improve the documentation. Adding all <op>.cc's to the Makefile in the limit would end up with all the ops in every ios binary.

@petewarden, do you have anything to add?

**Comment by civilman628** [comment]
@aselle  There is no document about how you make this file: 
https://storage.googleapis.com/download.tensorflow.org/models/inception5h.zip

As I said previously, we can't reproduce it. only a fixed model, which can predict 1000 classes is useless.

**Comment by civilman628** [comment]
If you can only use one demo on iOS, but can't create their own model, then it is meaningless.

**Comment by civilman628** [comment]
see my solution on #4766 for retrain V1 model.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activityand the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by arun-kumark** [comment]
Hi,
I am new to this issue. 
I want to serialize my Resnet101 based model.
I am using the script optimize_for_inference.py, I don't know how to edit this script for Resnet101 model.
When I run this script, I get the following errors: 

```
/home/arun/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "optimize_for_inference.py", line 146, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/arun/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "optimize_for_inference.py", line 90, in main
    FLAGS.output_names.split(","), FLAGS.placeholder_type_enum)
  File "/home/arun/anaconda3/lib/python3.6/site-packages/tensorflow/python/tools/optimize_for_inference_lib.py", line 109, in optimize_for_inference
    placeholder_type_enum)
  File "/home/arun/anaconda3/lib/python3.6/site-packages/tensorflow/python/tools/strip_unused_lib.py", line 83, in strip_unused
    raise KeyError("The following input nodes were not found: %s\n" % not_found)
KeyError: "The following input nodes were not found: {'input'}\n"
```
I want to make this script work to serialize my Resnet model. I need help, if someone can help me.

Kind Regards
Arun

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.
