### ISSUE TITLE
Build fails on Arch Linux

### ISSUE THREAD

**Issue by iLeW** [tensorflow/tensorflow#47915]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux, LSB version 1.4, Linux 5.10.23-1-lts, x86-64 
- TensorFlow installed from (source or binary): source 
- TensorFlow version: 2.4.1
- Python version: 3.9
- Installed using virtualenv? pip? conda?: virtualenv, pip
- Bazel version (if compiling from source): 4.0.0
- GCC/Compiler version (if compiling from source): 10.2.0
- CUDA/cuDNN version: CUDA 11.2.0-3, cuDNN 8.0.5.39-1
- GPU model and memory: Nvidia GeForce RTX 280 Ti 11016MiB

**Describe the problem**
I have two problems. These problems are related to two different types of situations. However, I have opened just one issue because, even if the problems could not be related themselves, they are probably related to building/installation problems.

1. Manual compilation of TensorFlow (2.4.1 version) using the instruction related to Arch Linux ([see the PKGBUILD file here](https://github.com/archlinux/svntogit-community/blob/packages/tensorflow/trunk/PKGBUILD)) fails. The error is the following (I'll log the entire output, error at the end). Note: The compilation has been started outside any virtualenv.
```bash
patching file tensorflow/tools/ci_build/install/install_centos_pip_packages.sh
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file tensorflow/tools/ci_build/install/install_centos_pip_packages.sh.rej
patching file tensorflow/tools/ci_build/install/install_pip_packages.sh
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file tensorflow/tools/ci_build/install/install_pip_packages.sh.rej
patching file tensorflow/tools/ci_build/install/install_python3.5_pip_packages.sh
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file tensorflow/tools/ci_build/install/install_python3.5_pip_packages.sh.rej
patching file tensorflow/tools/ci_build/install/install_python3.6_pip_packages.sh
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file tensorflow/tools/ci_build/install/install_python3.6_pip_packages.sh.rej
patching file tensorflow/tools/ci_build/release/common_win.bat
Reversed (or previously applied) patch detected!  Skipping patch.
2 out of 2 hunks ignored -- saving rejects to file tensorflow/tools/ci_build/release/common_win.bat.rej
patching file tensorflow/tools/pip_package/setup.py
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file tensorflow/tools/pip_package/setup.py.rej
patching file tensorflow/python/keras/saving/hdf5_format.py
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file tensorflow/python/keras/saving/hdf5_format.py.rej
patching file tensorflow/python/keras/saving/hdf5_format.py
Reversed (or previously applied) patch detected!  Skipping patch.
3 out of 3 hunks ignored -- saving rejects to file tensorflow/python/keras/saving/hdf5_format.py.rej
patching file tensorflow/python/keras/saving/hdf5_format.py
Reversed (or previously applied) patch detected!  Skipping patch.
2 out of 2 hunks ignored -- saving rejects to file tensorflow/python/keras/saving/hdf5_format.py.rej
patching file tensorflow/compiler/mlir/tensorflow/tests/tf_saved_model/common.py
Hunk #2 FAILED at 80.
1 out of 2 hunks FAILED -- saving rejects to file tensorflow/compiler/mlir/tensorflow/tests/tf_saved_model/common.py.rej
patching file tensorflow/compiler/mlir/tensorflow/tests/tf_saved_model/common.py
Hunk #2 FAILED at 79.
1 out of 2 hunks FAILED -- saving rejects to file tensorflow/compiler/mlir/tensorflow/tests/tf_saved_model/common.py.rej
patching file tensorflow/compiler/mlir/tensorflow/tests/tf_saved_model/common.py
patching file tensorflow/compiler/mlir/tensorflow/tests/tf_saved_model/common.py
patching file tensorflow/python/pywrap_mlir.py
Hunk #1 succeeded at 38 (offset 1 line).
patching file tensorflow/python/pywrap_mlir.py
Hunk #1 succeeded at 38 (offset 1 line).
You have bazel 4.0.0 installed.
Found CUDA 11.2 in:
    /opt/cuda/targets/x86_64-linux/lib
    /opt/cuda/targets/x86_64-linux/include
Found cuDNN 8 in:
    /usr/lib
    /usr/include
Found NCCL 2 in:
    /usr/lib
    /usr/include


Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=mkl_aarch64    # Build with oneDNN support for Aarch64.
        --config=monolithic     # Config for mostly static monolithic build.
        --config=ngraph         # Build with Intel nGraph support.
        --config=numa           # Build with NUMA support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
        --config=v2             # Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=noaws          # Disable AWS S3 filesystem support.
        --config=nogcp          # Disable GCP support.
        --config=nohdfs         # Disable HDFS support.
        --config=nonccl         # Disable NVIDIA NCCL support.
Configuration finished
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=198
INFO: Reading rc options for 'build' from /run/media/federico/XData/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /run/media/federico/XData/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=short_logs --config=v2
INFO: Reading rc options for 'build' from /run/media/federico/XData/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python --action_env PYTHON_LIB_PATH=/usr/lib/python3.9/site-packages --python_path=/usr/bin/python --config=xla --action_env TF_CUDA_VERSION=11.2 --action_env TF_CUDNN_VERSION=8 --action_env TF_NCCL_VERSION=2.8 --action_env TF_CUDA_PATHS=/opt/cuda,/usr/lib,/usr,/usr/include,/usr/local/lib --action_env CUDA_TOOLKIT_PATH=/opt/cuda --action_env NCCL_INSTALL_PATH=/usr --action_env TF_CUDA_COMPUTE_CAPABILITIES=6.1,7.5 --action_env LD_LIBRARY_PATH=/opt/cuda/extras/CUPTI/lib64: --action_env GCC_HOST_COMPILER_PATH=/usr/bin/gcc --config=cuda --action_env TF_SYSTEM_LIBS=boringssl,curl,cython,gif,icu,libjpeg_turbo,lmdb,nasm,pcre,png,pybind11,zlib --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:short_logs in file /run/media/federico/XData/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /run/media/federico/XData/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file /run/media/federico/XData/tensorflow/.bazelrc: --define=with_xla_support=true
INFO: Found applicable config definition build:cuda in file /run/media/federico/XData/tensorflow/.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file /run/media/federico/XData/tensorflow/.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=1
INFO: Found applicable config definition build:avx2_linux in file /run/media/federico/XData/tensorflow/.bazelrc: --copt=-mavx2
INFO: Found applicable config definition build:mkl in file /run/media/federico/XData/tensorflow/.bazelrc: --define=build_with_mkl=true --define=enable_mkl=true --define=tensorflow_mkldnn_contraction_kernel=0 --define=build_with_openmp=true -c opt
INFO: Found applicable config definition build:linux in file /run/media/federico/XData/tensorflow/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
INFO: Found applicable config definition build:dynamic_kernels in file /run/media/federico/XData/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
DEBUG: Rule 'io_bazel_rules_go' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1557349968 -0400"
DEBUG: Repository io_bazel_rules_go instantiated at:
  /run/media/federico/XData/tensorflow/WORKSPACE:37:30: in <toplevel>
  /home/federico/.cache/bazel/_bazel_federico/9ebe032d906e33a6e519d86fafa71920/external/bazel_toolchains/repositories/repositories.bzl:55:23: in repositories
Repository rule git_repository defined at:
  /home/federico/.cache/bazel/_bazel_federico/9ebe032d906e33a6e519d86fafa71920/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
DEBUG: /home/federico/.cache/bazel/_bazel_federico/9ebe032d906e33a6e519d86fafa71920/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:118:10: 
Auto-Configuration Warning: 'TMP' environment variable is not set, using 'C:\Windows\Temp' as default
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
DEBUG: Repository io_bazel_rules_docker instantiated at:
  /run/media/federico/XData/tensorflow/WORKSPACE:37:30: in <toplevel>
  /home/federico/.cache/bazel/_bazel_federico/9ebe032d906e33a6e519d86fafa71920/external/bazel_toolchains/repositories/repositories.bzl:37:23: in repositories
Repository rule git_repository defined at:
  /home/federico/.cache/bazel/_bazel_federico/9ebe032d906e33a6e519d86fafa71920/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
INFO: Analyzed 4 targets (418 packages loaded, 31513 targets configured).
INFO: Found 4 targets...
INFO: Deleting stale sandbox base /home/federico/.cache/bazel/_bazel_federico/9ebe032d906e33a6e519d86fafa71920/sandbox
ERROR: /run/media/federico/XData/tensorflow/tensorflow/python/keras/api/BUILD:111:19: Executing genrule //tensorflow/python/keras/api:keras_python_api_gen failed: (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)
2021-03-18 20:25:35.715885: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "/home/federico/.cache/bazel/_bazel_federico/9ebe032d906e33a6e519d86fafa71920/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 26, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/home/federico/.cache/bazel/_bazel_federico/9ebe032d906e33a6e519d86fafa71920/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 48, in <module>
    from tensorflow.python import keras
  File "/home/federico/.cache/bazel/_bazel_federico/9ebe032d906e33a6e519d86fafa71920/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/keras/__init__.py", line 27, in <module>
    from tensorflow.python.keras import models
  File "/home/federico/.cache/bazel/_bazel_federico/9ebe032d906e33a6e519d86fafa71920/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/keras/models.py", line 26, in <module>
    from tensorflow.python.keras.engine import functional
  File "/home/federico/.cache/bazel/_bazel_federico/9ebe032d906e33a6e519d86fafa71920/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/keras/engine/functional.py", line 38, in <module>
    from tensorflow.python.keras.engine import training as training_lib
  File "/home/federico/.cache/bazel/_bazel_federico/9ebe032d906e33a6e519d86fafa71920/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/keras/engine/training.py", line 52, in <module>
    from tensorflow.python.keras.engine import data_adapter
  File "/home/federico/.cache/bazel/_bazel_federico/9ebe032d906e33a6e519d86fafa71920/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/keras/engine/data_adapter.py", line 65, in <module>
    import pandas as pd  # pylint: disable=g-import-not-at-top
  File "/usr/lib/python3.9/site-packages/pandas/__init__.py", line 29, in <module>
    from pandas._libs import hashtable as _hashtable, lib as _lib, tslib as _tslib
  File "/usr/lib/python3.9/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
ERROR: /run/media/federico/XData/tensorflow/tensorflow/python/tools/BUILD:282:10 Middleman _middlemen/tensorflow_Spython_Stools_Sprint_Uselective_Uregistration_Uheader-runfiles failed: (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)
INFO: Elapsed time: 7946.935s, Critical Path: 567.22s
INFO: 28075 processes: 5830 internal, 22245 local.
FAILED: Build did NOT complete successfully

```
2. Manual compilation of TensorFlow (git cloned and checked out at r2.4/v2.4.1) following the instruction [here](https://www.tensorflow.org/install/source) seems to work. The `pip install` of the wheel produced correctly works too. However, trying to create a new CustoOps, in particular a basic one `zero_out.cc` as proposed [here](https://www.tensorflow.org/guide/create_op#define_the_op_interface), after having compiled with bazel, when I try to test it as described [here](https://www.tensorflow.org/guide/create_op#use_the_op_in_python) I receive this error (demangled):
`tensorflow::OpKernel::TraceString(tensorflow::OpKernelContext const&, bool) const`

**Provide the exact sequence of commands / steps that you executed before running into the problem**

1. Regarding the first problem, I have tried to compile TensorFlow following a subset of the instruction in this [PKGBUILD](https://github.com/archlinux/svntogit-community/blob/packages/tensorflow/trunk/PKGBUILD) file (see below for the exact subset of commands I have used). In particular:

* I've used the `tensorflow-2.4.1-cuda-opt` extracted from the source indicated in the `PKGBUILD` (`source=("$pkgname-$pkgver.tar.gz::https://github.com/tensorflow/tensorflow/archive/v${_pkgver}.tar.gz"`)
* Renamed the folder into `tensorflow`
* Put the `fix-h5py3.0.patch` into the above `tensorflow` folder
* From the mentioned `PKGBUILD` file, I've used this subset of instructions:
```bash
#!/bin/bash          

# Set the bazel version
echo "4.0.0" > .bazelversion

# Patch the h5py
patch -Np1 -d . -i fix-h5py3.0.patch

# Get rid of hardcoded versions. Not like we ever cared about what upstream
# thinks about which versions should be used anyway. ;) (FS#68772) 
sed -i -E "s/'([0-9a-z_-]+) .= [0-9].+[0-9]'/'\1'/" tensorflow/tools/pip_package/setup.py

# Set the variables
export PYTHON_BIN_PATH=/usr/bin/python
export USE_DEFAULT_PYTHON_LIB_PATH=1
export TF_NEED_JEMALLOC=1
export TF_NEED_KAFKA=1
export TF_NEED_OPENCL_SYCL=0
export TF_NEED_AWS=1
export TF_NEED_GCP=1
export TF_NEED_HDFS=1
export TF_NEED_S3=1
export TF_ENABLE_XLA=1
export TF_NEED_GDR=0
export TF_NEED_VERBS=0
export TF_NEED_OPENCL=0
export TF_NEED_MPI=0
export TF_NEED_TENSORRT=0
export TF_NEED_NGRAPH=0
export TF_NEED_IGNITE=0
export TF_NEED_ROCM=0
# See https://github.com/tensorflow/tensorflow/blob/master/third_party/systemlibs/syslibs_configure.bzl
export TF_SYSTEM_LIBS="boringssl,curl,cython,gif,icu,libjpeg_turbo,lmdb,nasm,pcre,png,pybind11,zlib"
export TF_SET_ANDROID_WORKSPACE=0
export TF_DOWNLOAD_CLANG=0
export TF_NCCL_VERSION=2.8
export TF_IGNORE_MAX_BAZEL_VERSION=1
export TF_MKL_ROOT=/opt/intel/mkl
export NCCL_INSTALL_PATH=/usr
export GCC_HOST_COMPILER_PATH=/usr/bin/gcc
export HOST_C_COMPILER=/usr/bin/gcc
export HOST_CXX_COMPILER=/usr/bin/g++
export TF_CUDA_CLANG=0  # Clang currently disabled because it's not compatible at the moment.
export CLANG_CUDA_COMPILER_PATH=/usr/bin/clang
export TF_CUDA_PATHS=/opt/cuda,/usr/lib,/usr,/usr/include,/usr/local/lib
export TF_CUDA_VERSION=$(/opt/cuda/bin/nvcc --version | sed -n 's/^.*release \(.*\),.*/\1/p')
export TF_CUDNN_VERSION=$(sed -n 's/^#define CUDNN_MAJOR\s*\(.*\).*/\1/p' /usr/include/cudnn_version.h)
export TF_CUDA_COMPUTE_CAPABILITIES=6.1,7.5
export CC=gcc
export CXX=g++
export BAZEL_ARGS="--config=mkl -c opt --copt=-I/usr/include/openssl-1.0 --host_copt=-I/usr/include/openssl-1.0 --linkopt=-l:libssl.so.1.0.0 --linkopt=-l:libcrypto.so.1.0.0 --host_linkopt=-l:libssl.so.1.0.0 --host_linkopt=-l:libcrypto.so.1.0.0"
export BAZEL_ARGS="$BAZEL_ARGS --host_copt=-Wno-stringop-truncation"


echo "Building with cuda and with non-x86-64 optimizations" 
export CC_OPT_FLAGS="-march=haswell -O3"
export TF_NEED_CUDA=1
./configure
bazel build --config=avx2_linux ${BAZEL_ARGS[@]} //tensorflow:libtensorflow.so //tensorflow:libtensorflow_cc.so //tensorflow:install_headers //tensorflow/tools/pip_package:build_pip_package
```
2. For the second problem, related to the successful build and installation, I reproduced the steps indicated in the official build guide [here](https://www.tensorflow.org/install/source), and then I have installed the wheel inside a virtualenv with python 3.9. The only thing I had to do to succeed in the installation process has been to downgrade the  `hdf5` library installed on my system from the `1.12.0-2` to the `1.10.5-1`.

Any hint will be appreciated. Thank you.

**Comment by Saduf2019** [comment]
@iLeW 
We see that you have cuda 11.2 which is compatible with tf nightly 2.5, can you downgrade to cuda 11.0 and let us know.

**Comment by iLeW** [comment]
> @iLeW We see that you have cuda 11.2 which is compatible with tf nightly 2.5, can you downgrade to cuda 11.0 and let us know. you may refer to [this link](https://github.com/tensorflow/tensorflow/issues/44159#issuecomment-735542190) and let us know.

Ok, some time has passed since the last reply. I'm replying just for completeness. Finally, we moved to another version and into a new solution. The problem was probably tied to the CUDA version. We can keep this closed.
