### ISSUE TITLE
ValueError: Calling `Model.fit` in graph mode is not supported when the `Model` instance was constructed with eager mode enabled. Please construct your `Model` instance in graph mode or call `Model.fit` with eager mode enabled.

### ISSUE THREAD

**Issue by Michal-Kolomanski** [tensorflow/tensorflow#47959]
**System information**
- Windows 10
- TensorFlow version 2.4.1
- Keras 2.4.1
- Python version: 3.7
- CUDA/cuDNN version: v11.2/11.2
- GPU model and memory: MSI geforce rtx 3060 12GB

**Describe the current behavior**
The program fails to start. 

**Describe the expected behavior**
It should work. 

**Standalone code to reproduce the issue**
I have deep Q learning class: 
```
class DQNAgent:
    def __init__(self):
        self.model = self.create_model()
        self.target_model = self.create_model()
        self.target_model.set_weights(self.model.get_weights())

        self.replay_memory = deque(maxlen=REPLAY_MEMORY_SIZE)

        self.tensorboard = ModifiedTensorBoard(log_dir=f"logs/{MODEL_NAME}-{int(time.time())}")

        self.target_update_counter = 0
        self.graph = tf.compat.v1.get_default_graph()

        self.terminate = False
        self.last_log_episode = 0
        self.training_initialized = False

    def create_model(self):
        base_model = Xception(weights=None, include_top=False, input_shape=(IM_HEIGHT, IM_WIDTH, 3))

        x = base_model.output
        x = GlobalAveragePooling2D()(x)

        predictions = Dense(3, activation='linear')(x)
        model = Model(inputs=base_model.input, outputs=predictions)
        model.compile(loss='mse', optimizer=Adam(lr=0.001), metrics=['accuracy'])
        return model

    def update_replay_memory(self, transition):
        # transition = (current_state, action, reward, new_state, done)
        self.replay_memory.append(transition)

    def train(self):
        if len(self.replay_memory) < MIN_REPLAY_MEMORY_SIZE:
            return

        minibatch = random.sample(self.replay_memory, MINIBATCH_SIZE)

        current_states = np.array([transition[0] for transition in minibatch])/255
        with self.graph.as_default():
            current_qs_list = self.model.predict(current_states, PREDICTION_BATCH_SIZE)

        new_current_states = np.array([transition[3] for transition in minibatch]) / 255
        with self.graph.as_default():
            future_qs_list = self.target_model.predict(new_current_states, PREDICTION_BATCH_SIZE)

        X = []
        y = []

        # we want to update q table only when there exists a future state. If a car crashed just save the last q values
        for index, (current_state, action, reward, new_state, done) in enumerate(minibatch):
            if not done:
                max_future_q = np.max(future_qs_list[index])
                new_q = reward + DISCOUNT * max_future_q
            else:
                new_q = reward

            current_qs = current_qs_list[index]
            current_qs[action] = new_q

            X.append(current_state)
            y.append(current_qs)

        log_this_step = False
        if self.tensorboard.step > self.last_logged_episode:
            log_this_step = True
            self.last_logged_episode = self.tensorboard.step

        with self.graph.as_default():
            self.model.fit(np.array(X)/255, np.array(y), batch_size=TRAINING_BATCH_SIZE, verbose=0, shuffle=False, callbacks=[self.tensorboard] if log_this_step else None)

        if log_this_step:
            self.target_update_counter += 1

        if self.target_update_counter > UPDATE_TARGET_EVERY:
            self.target_model.set_weights(self.model.get_weights())
            self.target_update_counter = 0

    def get_qs(self, state):
        return self.model.predict(np.array(state).reshape(-1, *state.shape)/255)[0]

    def train_in_loop(self):
        X = np.random.uniform(size=(1, IM_HEIGHT, IM_WIDTH, 3)).astype(np.float32)
        y = np.random.uniform(size=(1, 3)).astype(np.float32)

        with self.graph.as_default():
            self.model.fit(X, y, verbose=False, batch_size=1)

        self.training_initialized = True

        while True:
            if self.terminate:
                return
            self.train()
            time.sleep(0.01)
```

When I run the program: 
```
2021-03-21 18:50:05.877519: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
Using TensorFlow backend.
WARNING:tensorflow:From C:/Users/Michał/Desktop/Magisterka/Project/Carla_0.9.11_env/sentex_carla/sentex_full_tut.py:291: The name tf.keras.backend.set_session is deprecated. Please use tf.compat.v1.keras.backend.set_session instead.

2021-03-21 18:50:07.803967: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-03-21 18:50:07.806461: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2021-03-21 18:50:07.827618: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce RTX 3060 computeCapability: 8.6
coreClock: 1.837GHz coreCount: 28 deviceMemorySize: 12.00GiB deviceMemoryBandwidth: 335.32GiB/s
2021-03-21 18:50:07.827846: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-03-21 18:50:07.834034: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-03-21 18:50:07.834164: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021-03-21 18:50:07.837381: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2021-03-21 18:50:07.838887: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2021-03-21 18:50:07.843668: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2021-03-21 18:50:07.846965: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2021-03-21 18:50:07.848560: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021-03-21 18:50:07.848732: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-03-21 18:50:08.633848: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-03-21 18:50:08.634021: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 
2021-03-21 18:50:08.634128: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N 
2021-03-21 18:50:08.634412: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4915 MB memory) -> physical GPU (device: 0, name: GeForce RTX 3060, pci bus id: 0000:01:00.0, compute capability: 8.6)
2021-03-21 18:50:08.635416: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-03-21 18:50:08.660884: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-03-21 18:50:08.661049: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce RTX 3060 computeCapability: 8.6
coreClock: 1.837GHz coreCount: 28 deviceMemorySize: 12.00GiB deviceMemoryBandwidth: 335.32GiB/s
2021-03-21 18:50:08.661286: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-03-21 18:50:08.661415: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-03-21 18:50:08.661545: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021-03-21 18:50:08.661688: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2021-03-21 18:50:08.662177: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2021-03-21 18:50:08.662341: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2021-03-21 18:50:08.662515: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2021-03-21 18:50:08.662726: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021-03-21 18:50:08.663120: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-03-21 18:50:08.663570: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce RTX 3060 computeCapability: 8.6
coreClock: 1.837GHz coreCount: 28 deviceMemorySize: 12.00GiB deviceMemoryBandwidth: 335.32GiB/s
2021-03-21 18:50:08.663900: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-03-21 18:50:08.664065: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-03-21 18:50:08.664222: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021-03-21 18:50:08.664385: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2021-03-21 18:50:08.664546: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2021-03-21 18:50:08.664710: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2021-03-21 18:50:08.664866: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2021-03-21 18:50:08.665026: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021-03-21 18:50:08.665225: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-03-21 18:50:08.665395: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-03-21 18:50:08.665567: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 
2021-03-21 18:50:08.665683: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N 
2021-03-21 18:50:08.665901: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4915 MB memory) -> physical GPU (device: 0, name: GeForce RTX 3060, pci bus id: 0000:01:00.0, compute capability: 8.6)
2021-03-21 18:50:08.666224: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-03-21 18:50:10.410494: I tensorflow/core/profiler/lib/profiler_session.cc:136] Profiler session initializing.
2021-03-21 18:50:10.410594: I tensorflow/core/profiler/lib/profiler_session.cc:155] Profiler session started.
2021-03-21 18:50:10.410692: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1365] Profiler found 1 GPUs
2021-03-21 18:50:10.411657: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cupti64_110.dll'; dlerror: cupti64_110.dll not found
2021-03-21 18:50:10.412499: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cupti.dll'; dlerror: cupti.dll not found
2021-03-21 18:50:10.412642: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1415] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI could not be loaded or symbol could not be found.
2021-03-21 18:50:10.412928: I tensorflow/core/profiler/lib/profiler_session.cc:172] Profiler session tear down.
2021-03-21 18:50:10.413062: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1496] function cupti_interface_->Finalize()failed with error CUPTI could not be loaded or symbol could not be found.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Michał\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Michał\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:/Users/Michał/Desktop/Magisterka/Project/Carla_0.9.11_env/sentex_carla/sentex_full_tut.py", line 268, in train_in_loop
    self.model.fit(X, y, verbose=False, batch_size=1)
  File "C:\Users\Michał\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1031, in fit
    version_utils.disallow_legacy_graph('Model', 'fit')
  File "C:\Users\Michał\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\utils\version_utils.py", line 122, in disallow_legacy_graph
    raise ValueError(error_msg)
ValueError: Calling `Model.fit` in graph mode is not supported when the `Model` instance was constructed with eager mode enabled. Please construct your `Model` instance in graph mode or call `Model.fit` with eager mode enabled.
```

I have tried adding to model.compile an argument: , run_eagerly equals: True, None, False - the result was still the same.

The whole code is here: https://pastebin.pl/view/10e9e350

Due to the fact that I am working with the Carla environment, it will be hard to reproduce exactly my setup.
The code is from: [sentex](https://pythonprogramming.net/reinforcement-learning-self-driving-autonomous-cars-carla-python/?completed=/reinforcement-learning-agent-self-driving-autonomous-cars-carla-python/)
For him that code worked perfectly. I guess that he was using a significantly older version of TensorFlow., so the error is most likely because I am using 2.4.1 version of TF.

**Comment by Saduf2019** [comment]
@Michal-Kolomanski 
I ran the code shared by you and do not see any error as reported, please refer to  the [gist here](https://colab.research.google.com/gist/Saduf2019/c04182de0f0b2a826b46a8c9943bd135/untitled568.ipynb).

**Comment by Michal-Kolomanski** [comment]
> @Michal-Kolomanski
> I ran the code shared by you and do not see any error as reported, please refer to the [gist here](https://colab.research.google.com/gist/Saduf2019/c04182de0f0b2a826b46a8c9943bd135/untitled568.ipynb).


I prepared a notebook with exactly the same error: [colab](https://colab.research.google.com/drive/1-B1KmaVtu5cJJgmS0h0rMADrx79vVNvD?usp=sharing).

**Comment by Saduf2019** [comment]
@Michal-Kolomanski 
I ran the colab but face a different error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/4d6000997a868fe08867b634d98362d4/untitled572.ipynb).

**Comment by Michal-Kolomanski** [comment]
> @Michal-Kolomanski
> I ran the colab but face a different error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/4d6000997a868fe08867b634d98362d4/untitled572.ipynb).

Please install:
`!pip install tensorflow==2.4.1`
`!pip install keras==2.4.1`
It should solve your problem.

**Comment by Saduf2019** [comment]
I am able to replicate the issue on tf 2.3,2.4 and nightly, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/1e7bbddc6b2d34a06cf86ab326bee316/untitled567.ipynb)

**Comment by jvishnuvardhan** [comment]
@Michal-Kolomanski I have looked at your code. There is a mix of graph mode and eager mode (and by default TF2.x is eager). Error is mainly due to mix of both modes. We don't support debugging of long code. I think this is more suited for Stackoveflow as there is a larger community who support this kind of questions.

GitHub is mainly for bugs and performance related issues. Thanks!

**Comment by Michal-Kolomanski** [comment]
> @Michal-Kolomanski I have looked at your code. There is a mix of graph mode and eager mode (and by default TF2.x is eager). Error is mainly due to mix of both modes. We don't support debugging of long code. I think this is more suited for Stackoveflow as there is a larger community who support this kind of questions.
> 
> GitHub is mainly for bugs and performance related issues. Thanks!

Now I am 100% sure that the issue is due to using a newer version of TF. Thank you for the response.
