### ISSUE TITLE
CUDA Issue: Initialization of a toy model takes 5GB graphical memory

### ISSUE THREAD

**Issue by realwsq** [tensorflow/tensorflow#47964]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
conda
- TensorFlow version (use command below):
tf.version.VERSION = 2.3.0
tf.version.GIT_VERSION = v2.3.0-rc2-23-gb36436b087
tf.version.COMPILER_VERSION = 7.3.1 20180303
- Python version:
== check python ===================================================
python version: 3.8.5
python branch: 
python build version: ('default', 'Sep  4 2020 07:30:14')
python compiler version: GCC 7.3.0
python implementation: CPython

- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
== compiler =====================================================
c++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
- CUDA/cuDNN version:
CUDA Version: 11.0
- GPU model and memory:
```python
class MyModel(tf.keras.Model):

  def __init__(self):
    pdb.set_trace()
    super(MyModel, self).__init__()
    pdb.set_trace()

    self.dense1 = tf.keras.layers.Dense(4, activation=tf.nn.relu)
    pdb.set_trace()
    self.dense2 = tf.keras.layers.Dense(5, activation=tf.nn.softmax)
    pdb.set_trace()

  def call(self, inputs):
    x = self.dense1(inputs)
    return self.dense2(x)
```
This chosen model is tiny, but it still takes 5GB graphical memory when I run it.

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I have a personal workstation with Nvidia RTX 2060s card. I tried to run my ml model using cuda while the graphical memory immediately ran out once the model is initiated. In order to eliminate the error from my model, I tried with the following tiny model, and the memory still ran out once it's initiated.

**Describe the expected behavior**
model should only takes a few MB graphical memory as it's indeed tiny.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```
import pdb
import tensorflow as tf


class MyModel(tf.keras.Model):

  def __init__(self):
    pdb.set_trace() # trace1
    super(MyModel, self).__init__()
    pdb.set_trace() # trace2

    self.dense1 = tf.keras.layers.Dense(4, activation=tf.nn.relu)
    pdb.set_trace()
    self.dense2 = tf.keras.layers.Dense(5, activation=tf.nn.softmax)
    pdb.set_trace()

  def call(self, inputs):
    x = self.dense1(inputs)
    return self.dense2(x)

model = MyModel()
```
According to the nvidia-smi, the graphical memory increases from 2767MB to 7755MB after running the object initiation between trace1 and trace2.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```bash
$python runnet.py 
2021-03-21 20:30:55.223213: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Working dir: /home/shuqi/Documents/2step-glm
manual save dir: /home/shuqi/Documents/2step-glm/manualsave/1616355056
2021-03-21 20:30:56.200025: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2021-03-21 20:30:56.238946: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-21 20:30:56.239299: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:29:00.0 name: GeForce RTX 2060 SUPER computeCapability: 7.5
coreClock: 1.65GHz coreCount: 34 deviceMemorySize: 7.79GiB deviceMemoryBandwidth: 417.29GiB/s
2021-03-21 20:30:56.239314: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-03-21 20:30:56.240455: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2021-03-21 20:30:56.241618: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2021-03-21 20:30:56.241779: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2021-03-21 20:30:56.242891: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2021-03-21 20:30:56.243485: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2021-03-21 20:30:56.245888: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2021-03-21 20:30:56.246000: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-21 20:30:56.246377: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-21 20:30:56.246673: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2021-03-21 20:30:56.246919: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-03-21 20:30:56.251829: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 3600030000 Hz
2021-03-21 20:30:56.252237: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55872d90cd40 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-03-21 20:30:56.252250: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-03-21 20:30:56.339116: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-21 20:30:56.339497: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55872d909050 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-03-21 20:30:56.339519: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2060 SUPER, Compute Capability 7.5
2021-03-21 20:30:56.339804: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-21 20:30:56.340317: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:29:00.0 name: GeForce RTX 2060 SUPER computeCapability: 7.5
coreClock: 1.65GHz coreCount: 34 deviceMemorySize: 7.79GiB deviceMemoryBandwidth: 417.29GiB/s
2021-03-21 20:30:56.340346: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-03-21 20:30:56.340379: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2021-03-21 20:30:56.340396: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2021-03-21 20:30:56.340412: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2021-03-21 20:30:56.340428: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2021-03-21 20:30:56.340444: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2021-03-21 20:30:56.340460: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2021-03-21 20:30:56.340541: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-21 20:30:56.341052: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-21 20:30:56.341503: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2021-03-21 20:30:56.341532: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-03-21 20:30:56.643133: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-03-21 20:30:56.643167: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 
2021-03-21 20:30:56.643176: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N 
2021-03-21 20:30:56.643404: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-21 20:30:56.643752: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-21 20:30:56.644045: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4658 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2060 SUPER, pci bus id: 0000:29:00.0, compute capability: 7.5)
2021-03-21 20:30:56.645082: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:30:56.687899: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:30:56.688103: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op LogicalNot in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:30:56.688291: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op Assert in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:30:56.688487: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:30:56.688718: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:30:56.688740: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:30:56.688791: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op LogicalNot in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:30:56.688863: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op Assert in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:30:56.688908: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:30:56.689016: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:30:56.689036: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:30:56.689082: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op LogicalNot in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:30:56.689153: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op Assert in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:30:56.689196: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
> /home/shuqi/Documents/2step-glm/src/buildnet.py(345)__init__()
-> self.conv2a = tf.keras.layers.Conv1D(FLAGS.conv1, FLAGS.conv1size, strides=1, padding='same',
(Pdb) c
> /home/shuqi/Documents/2step-glm/src/buildnet.py(349)__init__()
-> self.maxpool2a = tf.keras.layers.MaxPool1D(FLAGS.nk1, strides=FLAGS.nstride1, padding='same')
(Pdb) c
> /home/shuqi/Documents/2step-glm/src/buildnet.py(353)__init__()
-> self.conv2b = tf.keras.layers.Conv1D(FLAGS.conv2, FLAGS.conv2size, strides=1, padding='same',
(Pdb) c
> /home/shuqi/Documents/2step-glm/src/buildnet.py(357)__init__()
-> self.maxpool2b = tf.keras.layers.MaxPool1D(FLAGS.nk2, strides=FLAGS.nstride2, padding='same')
(Pdb) c
> /home/shuqi/Documents/2step-glm/src/buildnet.py(363)__init__()
-> self.flatten = tf.keras.layers.Flatten()
(Pdb) c
> /home/shuqi/Documents/2step-glm/src/buildnet.py(387)build_model()
-> inputnet(np.random.rand(FLAGS.batch_size, 31, FLAGS.numconsframes))  # dummy call
(Pdb) c
WARNING:tensorflow:Layer conv2 is casting an input tensor from dtype float64 to the layer's dtype of float32, which is new behavior in TensorFlow 2.  The layer has dtype float32 because its dtype defaults to floatx.

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

2021-03-21 20:31:02.226508: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op Cast in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:31:02.227279: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op RandomUniform in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:31:02.227682: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op Sub in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:31:02.228007: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op Mul in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:31:02.228116: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op Add in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:31:02.228343: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:31:02.228386: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:31:02.228489: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op LogicalNot in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:31:02.228620: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op Assert in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:31:02.228799: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:31:02.229711: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op Fill in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:31:02.229888: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:31:02.229926: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:31:02.229993: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op LogicalNot in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:31:02.230095: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op Assert in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:31:02.230188: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:31:02.230797: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op ExpandDims in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:31:02.230876: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:31:02.230913: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op ExpandDims in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:31:02.231055: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op Conv2D in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:31:02.231237: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2021-03-21 20:31:02.589000: E tensorflow/stream_executor/cuda/cuda_dnn.cc:328] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2021-03-21 20:31:02.590836: E tensorflow/stream_executor/cuda/cuda_dnn.cc:328] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Traceback (most recent call last):
  File "runnet.py", line 95, in <module>
    inputnet, rnn, cell = build_model(ncell, FLAGS) # thr=0.4 if no buffer
  File "/home/shuqi/Documents/2step-glm/src/buildnet.py", line 387, in build_model
    inputnet(np.random.rand(FLAGS.batch_size, 31, FLAGS.numconsframes))  # dummy call
  File "/home/shuqi/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 985, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/shuqi/Documents/2step-glm/src/buildnet.py", line 366, in call
    x = self.conv2a(input_tensor)
  File "/home/shuqi/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 985, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/shuqi/.local/lib/python3.8/site-packages/tensorflow/python/keras/layers/convolutional.py", line 247, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/home/shuqi/.local/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/shuqi/.local/lib/python3.8/site-packages/tensorflow/python/ops/nn_ops.py", line 1011, in convolution_v2
    return convolution_internal(
  File "/home/shuqi/.local/lib/python3.8/site-packages/tensorflow/python/ops/nn_ops.py", line 1141, in convolution_internal
    return op(
  File "/home/shuqi/.local/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/shuqi/.local/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py", line 574, in new_func
    return func(*args, **kwargs)
  File "/home/shuqi/.local/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py", line 574, in new_func
    return func(*args, **kwargs)
  File "/home/shuqi/.local/lib/python3.8/site-packages/tensorflow/python/ops/nn_ops.py", line 1881, in conv1d
    result = gen_nn_ops.conv2d(
  File "/home/shuqi/.local/lib/python3.8/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 938, in conv2d
    _ops.raise_from_not_ok_status(e, name)
  File "/home/shuqi/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 6843, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above. [Op:Conv2D]
2021-03-21 20:31:02.714717: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op DestroyResourceOp in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:31:02.714808: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op DestroyResourceOp in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:31:02.714833: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op DestroyResourceOp in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:31:02.714856: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op DestroyResourceOp in device /job:localhost/replica:0/task:0/device:GPU:0
2021-03-21 20:31:02.714883: I tensorflow/core/common_runtime/eager/execute.cc:611] Executing op DestroyResourceOp in device /job:localhost/replica:0/task:0/device:GPU:0

```

**Comment by Saduf2019** [comment]
@realwsq 
I tried running your code on colab , please find the [gist here](https://colab.research.google.com/gist/Saduf2019/5fd44f0b6bdd9c11c8d75cce5a362ad0/untitled567.ipynb), could you let us know the value for pdb as prompted in the gist.

**Comment by realwsq** [comment]
@Saduf2019 Hi, thank you for your reply. Here is the result running the gist. I stepped over to each breakpoint.
```
2021-03-22 08:14:16.041630: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
> /home/shuqi/Documents/2step-glm/test.py(9)__init__()
-> super(MyModel, self).__init__()
(Pdb) c
2021-03-22 08:14:39.444495: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2021-03-22 08:14:39.485378: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-22 08:14:39.485746: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:29:00.0 name: GeForce RTX 2060 SUPER computeCapability: 7.5
coreClock: 1.65GHz coreCount: 34 deviceMemorySize: 7.79GiB deviceMemoryBandwidth: 417.29GiB/s
2021-03-22 08:14:39.485765: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-03-22 08:14:39.517930: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2021-03-22 08:14:39.530904: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2021-03-22 08:14:39.533790: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2021-03-22 08:14:39.553771: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2021-03-22 08:14:39.556535: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2021-03-22 08:14:39.591204: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2021-03-22 08:14:39.591549: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-22 08:14:39.592104: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-22 08:14:39.592924: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2021-03-22 08:14:39.593475: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-03-22 08:14:39.610149: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 3600030000 Hz
2021-03-22 08:14:39.610779: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55829230d670 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-03-22 08:14:39.610898: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-03-22 08:14:39.723811: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-22 08:14:39.724495: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x558292379080 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-03-22 08:14:39.724515: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2060 SUPER, Compute Capability 7.5
2021-03-22 08:14:39.725297: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-22 08:14:39.725703: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:29:00.0 name: GeForce RTX 2060 SUPER computeCapability: 7.5
coreClock: 1.65GHz coreCount: 34 deviceMemorySize: 7.79GiB deviceMemoryBandwidth: 417.29GiB/s
2021-03-22 08:14:39.725770: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-03-22 08:14:39.725808: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2021-03-22 08:14:39.725821: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2021-03-22 08:14:39.725832: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2021-03-22 08:14:39.725843: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2021-03-22 08:14:39.725854: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2021-03-22 08:14:39.725865: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2021-03-22 08:14:39.725927: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-22 08:14:39.726336: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-22 08:14:39.726629: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2021-03-22 08:14:39.726967: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-03-22 08:14:40.481770: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-03-22 08:14:40.481817: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 
2021-03-22 08:14:40.481823: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N 
2021-03-22 08:14:40.482657: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-22 08:14:40.483110: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-22 08:14:40.483474: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4341 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2060 SUPER, pci bus id: 0000:29:00.0, compute capability: 7.5)
> /home/shuqi/Documents/2step-glm/test.py(12)__init__()
-> self.dense1 = tf.keras.layers.Dense(4, activation=tf.nn.relu)
(Pdb) c
> /home/shuqi/Documents/2step-glm/test.py(14)__init__()
-> self.dense2 = tf.keras.layers.Dense(5, activation=tf.nn.softmax)
(Pdb) c
--Return--
> /home/shuqi/Documents/2step-glm/test.py(14)__init__()->None
-> self.dense2 = tf.keras.layers.Dense(5, activation=tf.nn.softmax)
(Pdb) c
```

**Comment by sanjoy** [comment]
TF by default tries to preallocate all memory on the device.  Does setting [`set_memory_growth`](https://www.tensorflow.org/api_docs/python/tf/config/experimental/set_memory_growth) to `true` help?

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF 2.6.0-dev20210603,please find the gist[ here](https://colab.research.google.com/gist/sushreebarsa/a1c10a698e46a0438f64e70339c20b29/untitled216.ipynb)..Thanks !

**Comment by jvishnuvardhan** [comment]
@realwsq Did you try `set_memory_growth` as suggested by @sanjoy . I ran it in colab and didn't notice high memory usage. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/54a58d8d598a847d0a45be64fe413af1/untitled216.ipynb). Thanks!
