### ISSUE TITLE
ImportError: DLL load failed while importing _pywrap_tensorflow_internal

### ISSUE THREAD

**Issue by HessianHunter** [tensorflow/tensorflow#47979]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): idk
- TensorFlow version: 2.4.1
- Python version: 3.8
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): idk
- GCC/Compiler version (if compiling from source): idk
- CUDA/cuDNN version: idk
- GPU model and memory: n/a

**Describe the problem**
I am trying to install and use DeepLabCut on my CPU, which requires Tensorflow. Tensorflow 2.4.1 seems to be installed but whenever I try to import it I get error messages saying 

"ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

Failed to load the native TensorFlow runtime."

To address common fixes I see for this error - I have the most recent update of Visual C++, I am running 64-bit Python on a 64 bit machine, and my machine supports AVX2 (here are my specs https://ark.intel.com/content/www/us/en/ark/products/78937/intel-core-i7-4810mq-processor-6m-cache-up-to-3-80-ghz.html)

Some people have apparently solved this problem by creating a separate environment, but I am new to Python and have no idea what that means or how to do it.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
import tensorflow as tf
Traceback (most recent call last):

  File "C:\Users\pc\anaconda3\envs\DLC-CPU\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *

  File "C:\Users\pc\anaconda3\envs\DLC-CPU\Lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()

  File "C:\Users\pc\anaconda3\envs\DLC-CPU\Lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)

  File "C:\Users\pc\anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)

  File "C:\Users\pc\anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)

ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-39-64156d691fe5>", line 1, in <module>
    import tensorflow as tf

  File "C:\Users\pc\anaconda3\envs\DLC-CPU\Lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import

  File "C:\Users\pc\anaconda3\envs\DLC-CPU\Lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow

  File "C:\Users\pc\anaconda3\envs\DLC-CPU\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)

ImportError: Traceback (most recent call last):
  File "C:\Users\pc\anaconda3\envs\DLC-CPU\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\pc\anaconda3\envs\DLC-CPU\Lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\pc\anaconda3\envs\DLC-CPU\Lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\pc\anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\pc\anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

Failed to load the native TensorFlow runtime.

**Any other info / logs**
This is what happens when I try to import DeepLabCut.

import deeplabcut
Traceback (most recent call last):

  File "C:\Users\pc\anaconda3\envs\DLC-CPU\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *

  File "C:\Users\pc\anaconda3\envs\DLC-CPU\Lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()

  File "C:\Users\pc\anaconda3\envs\DLC-CPU\Lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)

  File "C:\Users\pc\anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)

  File "C:\Users\pc\anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)

ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-19-cfa4f159dfc5>", line 1, in <module>
    import deeplabcut

  File "C:\Users\pc\anaconda3\envs\DLC-CPU\Lib\site-packages\deeplabcut\__init__.py", line 14, in <module>
    import tensorflow as tf

  File "C:\Users\pc\anaconda3\envs\DLC-CPU\Lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import

  File "C:\Users\pc\anaconda3\envs\DLC-CPU\Lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow

  File "C:\Users\pc\anaconda3\envs\DLC-CPU\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)

ImportError: Traceback (most recent call last):
  File "C:\Users\pc\anaconda3\envs\DLC-CPU\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\pc\anaconda3\envs\DLC-CPU\Lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\pc\anaconda3\envs\DLC-CPU\Lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\pc\anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\pc\anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

Failed to load the native TensorFlow runtime.

**Comment by amahendrakar** [comment]
> Some people have apparently solved this problem by creating a separate environment, but I am new to Python and have no idea what that means or how to do it.

@HessianHunter,
Please take a look at [this guide](https://www.tensorflow.org/install/pip#2.-create-a-virtual-environment-recommended) to install TensorFlow in a new virtual environment and check if it helps. Thanks!
