### ISSUE TITLE
Training becomes increasingly slower when creating models in a loop

### ISSUE THREAD

**Issue by mattia-** [tensorflow/tensorflow#47971]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): BINARY
- TensorFlow version (use command below): v2.4.0-49-g85c8b2a817f 2.4.1
- Python version: 3.7.6
- CUDA/cuDNN version: NO GPU
- GPU model and memory: NO GPU

**Describe the current behavior**
When creating and training a model multiple times in a loop, the training process gets increasingly slower with each model.

**Describe the expected behavior**
I expected the training times to be roughly the same.

**Standalone code to reproduce the issue**
```
import numpy as np
import tensorflow as tf
import time

n_samples = 300000
n_features = 100
n_targets = 5
batch_size = 100
n_inducing_points = 100
x = np.array(range(n_samples * n_features), dtype=np.float64).reshape((n_samples, n_features))
y = np.array(range(n_samples * n_targets), dtype=np.float64).reshape((n_samples, n_targets))
for t_idx in range(10):
    tf.keras.backend.clear_session()
    dataset = [x, y]
    dataset = tf.data.Dataset.from_tensor_slices(tuple(dataset)).shuffle(n_samples).repeat().batch(batch_size=batch_size).prefetch(tf.data.experimental.AUTOTUNE)
    data_iterator = iter(dataset)

    inputs = tf.keras.Input(shape=(n_features,), name='input')
    outputs = tf.keras.layers.Dense(n_features, name='dense_1', activation=tf.keras.activations.relu)(inputs)
    outputs = tf.keras.layers.Dense(n_features, name='dense_2', activation=tf.keras.activations.relu)(outputs)
    outputs = tf.keras.layers.Dense(n_features, name='dense_3', activation=tf.keras.activations.relu)(outputs)
    outputs = tf.keras.layers.Dense(n_features, name='dense_4', activation=tf.keras.activations.relu)(outputs)
    outputs = tf.keras.layers.Dense(n_targets, name='output', activation=tf.keras.activations.linear)(outputs)
    model = tf.keras.Model(inputs=inputs, outputs=outputs)

    trainable_variables = list(model.trainable_variables)

    adam_opt = tf.optimizers.Adam(learning_rate=0.001)


    @tf.function
    def loss(batch):
        x_, y_ = batch
        y_pred_ = model(x_)
        return tf.keras.losses.MSE(y_pred_, y_)


    @tf.function
    def optimization_step():
        batch = next(data_iterator)
        def f(): return loss(batch)
        adam_opt.minimize(f, var_list=trainable_variables)

    iterations = 50000
    loop_start = time.time()
    optimization_times = []
    for idx in range(iterations):
        optimization_step()

    loop_end = time.time()
    print(f'Elapsed: {loop_end - loop_start}')
```

Using `model.fit()` is not an option, since this code was obtained by stripping down a much more complicated code, where the call to `model.fit()` is not possible.

**Other info / logs**
Output obtained with the script above:
```
Elapsed: 49.798316955566406
Elapsed: 55.18571472167969
Elapsed: 58.57510209083557
Elapsed: 64.41855955123901
Elapsed: 66.76858448982239
Elapsed: 68.3305652141571
Elapsed: 67.73438382148743
Elapsed: 69.73751258850098
Elapsed: 73.59102845191956
Elapsed: 73.14124798774719
```
As you can see, training times have a clear upward trend. Moreover, this does not happen on my Linux machine (same python version, same tensorflow version, on a clean virtualenv; Ubuntu 18.04).

**Comment by amahendrakar** [comment]
@mattia-,
Could you please restart your machine, close all the programs running in the background before running the script and let us know if you are still facing the same issue? Thanks!

**Comment by mattia-** [comment]
@amahendrakar,
Thanks for taking the time to reply!
I can confirm the issue still stands after a clean reboot. Can you reproduce the same behaviour on your machine or is it just me?

**Comment by amahendrakar** [comment]
@rmothukuru,
I did not face any issues while running the code on a **Linux machine** with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.sandbox.google.com/gist/amahendrakar/c3fd3719669e2ac558c3432205aab8df/47971.ipynb). Thanks!

**Comment by mattia-** [comment]
@rmothukuru,
Just to confirm that this looks like a Windows-only problem. I did not face any issues running my script on Linux either (and neither on Mac or on WSL, for that matter). Thanks!

**Comment by jvishnuvardhan** [comment]
@mattia- I ran your code on Win10 with `tf-nightly` and I don't see the issue of slowing down. Please check the output below

```
Elapsed: 51.30133318901062
Elapsed: 57.163376331329346
Elapsed: 57.61692833900452
Elapsed: 55.73898267745972
Elapsed: 58.43379831314087
Elapsed: 56.97764277458191
Elapsed: 57.768574237823486
Elapsed: 57.758583784103394
Elapsed: 58.231318950653076
Elapsed: 58.51157069206238

Process finished with exit code 0
```
Can you please verify with `tf-nightly` and let us know what you see. Thanks!

**Comment by mattia-** [comment]
Hi @jvishnuvardhan 

I tried to test what you suggested, but I'm having some problems with the use of `tf-nightly`:
```
Traceback (most recent call last):
File ".\tmp.py", line 16, in <module>
dataset = tf.data.Dataset.from_tensor_slices(tuple(dataset)).shuffle(n_samples).repeat().batch(batch_size=batch_size).prefetch(tf.data.experimental.AUTOTUNE)
File "C:\Users\XXX\tmp\venv_tf_nightly\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 685, in from_tensor_slices
return TensorSliceDataset(tensors)
File "C:\Users\XXX\tmp\venv_tf_nightly\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 3844, in __init__
element = structure.normalize_element(element)
File "C:\Users\XXX\tmp\venv_tf_nightly\lib\site-packages\tensorflow\python\data\util\structure.py", line 129, in normalize_element
ops.convert_to_tensor(t, name="component_%d" % i, dtype=dtype))
File "C:\Users\XXX\tmp\venv_tf_nightly\lib\site-packages\tensorflow\python\profiler\trace.py", line 163, in wrapped
return func(*args, **kwargs)
File "C:\Users\XXX\tmp\venv_tf_nightly\lib\site-packages\tensorflow\python\framework\ops.py", line 1566, in convert_to_tensor
ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
File "C:\Users\XXX\tmp\venv_tf_nightly\lib\site-packages\tensorflow\python\framework\tensor_conversion_registry.py", line 52, in _default_conversion_function
return constant_op.constant(value, dtype, name=name)
File "C:\Users\XXX\tmp\venv_tf_nightly\lib\site-packages\tensorflow\python\framework\constant_op.py", line 272, in constant
allow_broadcast=True)
File "C:\Users\XXX\tmp\venv_tf_nightly\lib\site-packages\tensorflow\python\framework\constant_op.py", line 283, in _constant_impl
return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
File "C:\Users\XXX\tmp\venv_tf_nightly\lib\site-packages\tensorflow\python\framework\constant_op.py", line 308, in _constant_eager_impl
t = convert_to_eager_tensor(value, ctx, dtype)
File "C:\Users\XXX\tmp\venv_tf_nightly\lib\site-packages\tensorflow\python\framework\constant_op.py", line 105, in convert_to_eager_tensor
ctx.ensure_initialized()
File "C:\Users\XXX\tmp\venv_tf_nightly\lib\site-packages\tensorflow\python\eager\context.py", line 536, in ensure_initialized
config_str = self.config.SerializeToString()
File "C:\Users\XXX\tmp\venv_tf_nightly\lib\site-packages\tensorflow\python\eager\context.py", line 964, in config
self._initialize_physical_devices()
File "C:\Users\XXX\tmp\venv_tf_nightly\lib\site-packages\tensorflow\python\eager\context.py", line 1293, in _initialize_physical_devices
devs = pywrap_tfe.TF_ListPhysicalDevices()
tensorflow.python.framework.errors_impl.InternalError: Cannot dlopen all CUDA libraries.
```

`tf-nightly` was installed with
```
pip install tf-nightly
```

Any suggestions? Thanks!

**Comment by jvishnuvardhan** [comment]
@mattia- which version was installed? can you do `print(tf.__version__)` after `import tensorflow as tf`. thanks!

**Comment by mattia-** [comment]
@jvishnuvardhan 

> which version was installed? can you do `print(tf.__version__)` after `import tensorflow as tf`
```
>>> import tensorflow as tf
>>> print(tf.__version__)
2.7.0-dev20210630 
```



> Another question. Are you trying to use TF with GPU?

Nope, I'm using (or, at least, trying to use) the plain CPU version.

Thanks!

**Comment by jvishnuvardhan** [comment]
@mattia- Do you have GPU in your system? can you try reinstalling TF as `!pip install tf-nightly-cpu`. If you just use `!pip install tf-nightly`, it looks for GPU. If you have GPU, then automatically it installs GPU enabled TF.

As far as I know, this is not an issue with TF code but something with the system. So, may be unistall and reinstall TF-cpu and test again. You could also check it in google colab. Thanks

**Comment by mattia-** [comment]
@jvishnuvardhan 

I managed to install it and test it. Here are the results on my machine:
```
>>> tf.__version__
'2.7.0-dev20210704'
```
```
Elapsed: 49.9630708694458
Elapsed: 53.02399563789368
Elapsed: 53.265995502471924
Elapsed: 53.51599383354187
Elapsed: 54.79951238632202
Elapsed: 55.34299564361572
Elapsed: 56.96799683570862
Elapsed: 57.81099009513855
Elapsed: 59.2099826335907
Elapsed: 59.92298483848572
```

It looks better than before, but to be honest I can still see the upwards trend in the training times.
Thanks!

**Comment by jvishnuvardhan** [comment]
My recent runtime (without any other programs running) show that there is a small increase but that is expected. Please check the runtime below

```
Elapsed: 54.97995686531067
Elapsed: 52.393901348114014
Elapsed: 53.56126165390015
Elapsed: 53.747889280319214
Elapsed: 54.081284284591675
Elapsed: 55.353312253952026
Elapsed: 56.64463949203491
Elapsed: 55.35281229019165
Elapsed: 55.846272230148315
Elapsed: 56.97290635108948
```
