### ISSUE TITLE
Installing tensorflow nightly

### ISSUE THREAD

**Issue by ideepankarsharma2003** [tensorflow/tensorflow#48034]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- windows 10:
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip install tf-nightly

- TensorFlow version:2.5.0
- Python version:3.9
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: 6 gb ram and gt710

**Describe the problem**
it just threw a lot of exception errors , i'm 17 y/o noobie, really aint into this .....
total noobie

**Provide the exact sequence of commands / steps that you executed before running into the problem**
  File "c:\users\ts\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 171, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'tf-nightly-gpu'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\ts\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher        
    yield
  File "c:\users\ts\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\urllib3\response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "c:\users\ts\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "c:\users\ts\appdata\local\programs\python\python39\lib\http\client.py", line 458, in read
    n = self.readinto(b)
  File "c:\users\ts\appdata\local\programs\python\python39\lib\http\client.py", line 502, in readinto
    n = self.fp.readinto(b)
  File "c:\users\ts\appdata\local\programs\python\python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "c:\users\ts\appdata\local\programs\python\python39\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "c:\users\ts\appdata\local\programs\python\python39\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\ts\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\cli\base_command.py", line 189, in _main
    status = self.run(options, args)
  File "c:\users\ts\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\cli\req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "c:\users\ts\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\commands\install.py", line 316, in run
    requirement_set = resolver.resolve(
  File "c:\users\ts\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "c:\users\ts\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "c:\users\ts\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 318, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "c:\users\ts\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "c:\users\ts\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 82, in from_requirement   
    if not cands:
  File "c:\users\ts\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 124, in __bool__
    return bool(self._sequence)
  File "c:\users\ts\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in __bool__
    return any(self)
  File "c:\users\ts\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 38, in _iter_built
    candidate = func()
  File "c:\users\ts\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 167, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "c:\users\ts\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 300, in __in    super().__init__(
  File "c:\users\ts\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 144, in __init__
    self.dist = self._prepare()
  File "c:\users\ts\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 226, in _pre    dist = self._prepare_distribution()
  File "c:\users\ts\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 311, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File "c:\users\ts\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\operations\prepare.py", line 457, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "c:\users\ts\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\operations\prepare.py", line 480, in _prepare_linked_re    local_file = unpack_url(
  File "c:\users\ts\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\operations\prepare.py", line 230, in unpack_url        
    file = get_http_url(
  File "c:\users\ts\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\operations\prepare.py", line 108, in get_http_url      
    from_path, content_type = download(link, temp_dir.path)
  File "c:\users\ts\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\network\download.py", line 163, in __call__
    for chunk in chunks:
  File "c:\users\ts\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\cli\progress_bars.py", line 159, in iter
  File "c:\users\ts\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\network\utils.py", line 64, in response_chunks
    for chunk in response.raw.stream(
  File "c:\users\ts\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\urllib3\response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "c:\users\ts\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\urllib3\response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "c:\users\ts\appdata\local\programs\python\python39\lib\contextlib.py", line 135, in __exit__
  File "c:\users\ts\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\urllib3\response.py", line 443, in _error_catcher        
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@ideepankarsharma2003,
Could you please check if you are facing the same issue with other Python packages like `numpy` and `pandas` as well?

Alternatively to install the TensorFlow package, you can download the `.whl` file for Windows 10 and Python 3.9 from [this link](https://pypi.org/project/tf-nightly/2.5.0.dev20210323/#files) and install it offline.

Thanks!

**Comment by ideepankarsharma2003** [comment]
I don't have a GPU though , I think

**Comment by ideepankarsharma2003** [comment]
> @ideepankarsharma2003,
> Could you please check if you are facing the same issue with other Python packages like `numpy` and `pandas` as well?
> 
> Alternatively to install the TensorFlow package, you can download the `.whl` file for Windows 10 and Python 3.9 from [this link](https://pypi.org/project/tf-nightly/2.5.0.dev20210323/#files) and install it offline.
> 
> Thanks!

Thanks I'll see if it works

**Comment by mihaimaruseac** [comment]
It looks like a timeout issue.

Can you try `pip install tf-nightly-cpu`?

**Comment by ideepankarsharma2003** [comment]
It's done thanks guys

**Comment by amahendrakar** [comment]
@ideepankarsharma2003,
Thank you for the update. 

Closing this issue as it is resolved. Please feel free to re-open if necessary.
