### ISSUE TITLE
TF2.4 ModelCheckpoint Cant Save Model

### ISSUE THREAD

**Issue by rcx986635** [tensorflow/tensorflow#48102]
**System information**
- OS Platform and Distribution (e.g., Linux Redhat 7.4):
- TensorFlow installed from conda install
- TensorFlow version (use command below): tf 2.4.1
- Python version: 3.6.8
- CUDA/cuDNN version:  11.2/8.0.4
- GPU model and memory:   GTX3090   24G

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
checkpoint1 = ModelCheckpoint(best_model_filepath,monitor= 'loss',verbose=1,save_best_only= True,mode= 'min',period= 1)  
checkpoint2 = ModelCheckpoint(best_model_filepath,monitor= 'loss',verbose=1,save_best_only= True,
                                 save_weights_only=True,mode= 'min',period=1)
callbacks_list  = [checkpoint1,learning_rate_scheduler]
model.fit(train_generator.generator(),steps_per_epoch=1000,epochs=300,callbacks=callbacks_list)

The checkpoint1  will cause an error, otherwise checkpoint2 will run successly.
THE ERROR LOG  Part:

        312/312 [==============================] - 139s 398ms/step - loss: 94.4598 - CounterAttack_LL_loss: 93.7615 - CounterAttack_cls_out_loss: 0.6983

Epoch 00001: loss improved from inf to 93.23533, saving model to model/CounterAttack_best_model.h5
Traceback (most recent call last):
  File "train_v2.py", line 1213, in <module>
    train(continue_train=True)
  File "train_v2.py", line 1070, in train
    callbacks=callbacks_list)
  File "/root/python_env/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1145, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/root/python_env/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 428, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/root/python_env/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 1344, in on_epoch_end
    self._save_model(epoch=epoch, logs=logs)
  File "/root/python_env/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 1396, in _save_model
    self.model.save(filepath, overwrite=True, options=self._options)
  File "/root/python_env/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 2002, in save
    signatures, options, save_traces)
  File "/root/python_env/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/saving/save.py", line 154, in save_model
    model, filepath, overwrite, include_optimizer)
  File "/root/python_env/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 115, in save_model_to_hdf5
    model_metadata = saving_utils.model_metadata(model, include_optimizer)
  File "/root/python_env/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 155, in model_metadata
    model_config['config'] = model.get_config()
  File "/root/python_env/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/functional.py", line 650, in get_config
    return copy.deepcopy(get_network_config(self))
  File "/root/python_env/anaconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/root/python_env/anaconda3/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/root/python_env/anaconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)

... ...  (many repeat lines)

  File "/root/python_env/anaconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/root/python_env/anaconda3/lib/python3.6/copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/root/python_env/anaconda3/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/root/python_env/anaconda3/lib/python3.6/copy.py", line 274, in _reconstruct
    y = func(*args)
  File "/root/python_env/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 190, in __init__
    if value < 0:
RecursionError: maximum recursion depth exceeded in comparison
2021-03-26 15:34:35.680528: W tensorflow/core/kernels/data/generator_dataset_op.cc:107] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]

**Comment by Saduf2019** [comment]
@rcx986635 
Please share simple stand alone code or a colab gist with the issue reported.
