### ISSUE TITLE
LoadDataset op uses a bytes string as its name

### ISSUE THREAD

**Issue by ruler501** [tensorflow/tensorflow#48162]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux NixOS 20.09
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.4.0-49-g85c8b2a817f 2.4.1
- Python version: 3.8.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
When trying to use an `op_regex` in `tf.debugging.experimental.enable_dump_debug_info` while using `tf.data.experimental.load` you get an error that you `cannot use a string pattern on a bytes-like object`. Looking at the stack trace (below) it appears the error comes from the fact that the `LoadDataset` op is using a bytes string for the op name while other ops in `load` use regular strings. 

**Describe the expected behavior**
You should be able to use a regex to filter ops as described on the api reference page for `tf.data.experimental.load`.

**Other info / logs**
With a string regex
```
Traceback (most recent call last):
  File "/nix/store/v3bj7jrns4sk6yj2rp30p6v2l7p707az-python3-3.8.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/nix/store/v3bj7jrns4sk6yj2rp30p6v2l7p707az-python3-3.8.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/NVME/CubeCobraRecommender/src/ml/train_draftbots.py", line 114, in <module>
    train_dataset = load_picks(pick_cache_dir / 'train', batch_size)
  File "/mnt/NVME/CubeCobraRecommender/src/non_ml/parse_picks.py", line 395, in load_picks
    return tf.data.experimental.load(
  File "/mnt/NVME/CubeCobraRecommender/.venv/lib/python3.8/site-packages/tensorflow/python/data/experimental/ops/io.py", line 201, in load
    return _LoadDataset(
  File "/mnt/NVME/CubeCobraRecommender/.venv/lib/python3.8/site-packages/tensorflow/python/data/experimental/ops/io.py", line 129, in __init__
    variant_tensor = gen_experimental_dataset_ops.load_dataset(
  File "/mnt/NVME/CubeCobraRecommender/.venv/lib/python3.8/site-packages/tensorflow/python/ops/gen_experimental_dataset_ops.py", line 5636, in load_dataset
    return load_dataset_eager_fallback(
  File "/mnt/NVME/CubeCobraRecommender/.venv/lib/python3.8/site-packages/tensorflow/python/ops/gen_experimental_dataset_ops.py", line 5698, in load_dataset_eager_fallback
    _result = _execute.execute(b"LoadDataset", 1, inputs=_inputs_flat,
  File "/mnt/NVME/CubeCobraRecommender/.venv/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 140, in execute_with_callbacks
    callback(op_name, tuple(inputs), attrs, tensors, name)
  File "/mnt/NVME/CubeCobraRecommender/.venv/lib/python3.8/site-packages/tensorflow/python/debug/lib/dumping_callback.py", line 595, in callback
    writer.WriteExecution(self._dump_eager_tensors(
  File "/mnt/NVME/CubeCobraRecommender/.venv/lib/python3.8/site-packages/tensorflow/python/debug/lib/dumping_callback.py", line 505, in _dump_eager_tensors
    if (self._should_dump_tensor(op_type, tensor.dtype) and
  File "/mnt/NVME/CubeCobraRecommender/.venv/lib/python3.8/site-packages/tensorflow/python/debug/lib/dumping_callback.py", line 675, in _should_dump_tensor
    re.match(self._op_regex, op_type))
  File "/nix/store/v3bj7jrns4sk6yj2rp30p6v2l7p707az-python3-3.8.8/lib/python3.8/re.py", line 191, in match
    return _compile(pattern, flags).match(string)
TypeError: cannot use a string pattern on a bytes-like object
```
and with a bytes regex
```
Traceback (most recent call last):
  File "/nix/store/v3bj7jrns4sk6yj2rp30p6v2l7p707az-python3-3.8.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/nix/store/v3bj7jrns4sk6yj2rp30p6v2l7p707az-python3-3.8.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/NVME/CubeCobraRecommender/src/ml/train_draftbots.py", line 114, in <module>
    train_dataset = load_picks(pick_cache_dir / 'train', batch_size)
  File "/mnt/NVME/CubeCobraRecommender/src/non_ml/parse_picks.py", line 395, in load_picks
    return tf.data.experimental.load(
  File "/mnt/NVME/CubeCobraRecommender/.venv/lib/python3.8/site-packages/tensorflow/python/data/experimental/ops/io.py", line 201, in load
    return _LoadDataset(
  File "/mnt/NVME/CubeCobraRecommender/.venv/lib/python3.8/site-packages/tensorflow/python/data/experimental/ops/io.py", line 122, in __init__
    self._reader_func = dataset_ops.StructuredFunctionWrapper(
  File "/mnt/NVME/CubeCobraRecommender/.venv/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3525, in __init__
    self._function = wrapper_fn.get_concrete_function()
  File "/mnt/NVME/CubeCobraRecommender/.venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3051, in get_concrete_function
    graph_function = self._get_concrete_function_garbage_collected(
  File "/mnt/NVME/CubeCobraRecommender/.venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3019, in _get_concrete_function_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/mnt/NVME/CubeCobraRecommender/.venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/mnt/NVME/CubeCobraRecommender/.venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3196, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/mnt/NVME/CubeCobraRecommender/.venv/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 906, in func_graph_from_py_func
    func_args = _get_defun_inputs_from_args(
  File "/mnt/NVME/CubeCobraRecommender/.venv/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 1142, in _get_defun_inputs_from_args
    return _get_defun_inputs(
  File "/mnt/NVME/CubeCobraRecommender/.venv/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 1215, in _get_defun_inputs
    placeholder = graph_placeholder(
  File "/mnt/NVME/CubeCobraRecommender/.venv/lib/python3.8/site-packages/tensorflow/python/eager/graph_only_ops.py", line 45, in graph_placeholder
    callback_outputs = op_callbacks.invoke_op_callbacks(
  File "/mnt/NVME/CubeCobraRecommender/.venv/lib/python3.8/site-packages/tensorflow/python/framework/op_callbacks.py", line 202, in invoke_op_callbacks
    new_outputs = callback(
  File "/mnt/NVME/CubeCobraRecommender/.venv/lib/python3.8/site-packages/tensorflow/python/debug/lib/dumping_callback.py", line 581, in callback
    return self._instrument_symbolic_tensors(
  File "/mnt/NVME/CubeCobraRecommender/.venv/lib/python3.8/site-packages/tensorflow/python/debug/lib/dumping_callback.py", line 415, in _instrument_symbolic_tensors
    if (not self._should_dump_tensor(op_type, tensor.dtype) or
  File "/mnt/NVME/CubeCobraRecommender/.venv/lib/python3.8/site-packages/tensorflow/python/debug/lib/dumping_callback.py", line 675, in _should_dump_tensor
    re.match(self._op_regex, op_type))
  File "/nix/store/v3bj7jrns4sk6yj2rp30p6v2l7p707az-python3-3.8.8/lib/python3.8/re.py", line 191, in match
    return _compile(pattern, flags).match(string)
TypeError: cannot use a bytes pattern on a string-like object
```

**Comment by rmothukuru** [comment]
@ruler501,
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!
