### ISSUE TITLE
RaggedTensor with irregular shape breaks when yielded from `tf.keras.utils.Sequence`

### ISSUE THREAD

**Issue by dakshvar22** [tensorflow/tensorflow#48188]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOs
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.2
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the current behavior**

I am trying to pass tensors with irregular shapes to a custom keras model. I am using a custom data generator which inherits from `tf.keras.utils.Sequence`. This custom data generator is important because we want to control how data is batched after each epoch. I've reproduced my issue in this sample code:

```
import numpy as np
import tensorflow as tf
import random

class BatchGen(tf.keras.utils.Sequence):
    def __len__(self):
        return 100
    
    def __getitem__(self, idx):
        for i in range(100):
            return self.gen_ragged_tensors()
    
    @staticmethod
    def gen_ragged_tensors():
        seq_len = np.random.randint(1,3)
        a = np.zeros((seq_len,2), dtype=np.float32)

        seq_len = np.random.randint(1,3)
        b = np.ones((seq_len,2), dtype=np.float32)
        c = tf.ragged.constant([a,b], dtype=tf.float32)
        return c

class Model(tf.keras.models.Model):
    
    def calc_loss(self, batch_in):
        # dummy operation
        return tf.reduce_mean(batch_in - tf.constant(0, dtype=tf.float32))
    
    @tf.function
    def train_step(self, batch_in):
        
        with tf.GradientTape(persistent=True) as tape:
            prediction_loss = self.calc_loss(batch_in)
        prediction_gradients = tape.gradient(prediction_loss, self.trainable_variables)
        self.optimizer.apply_gradients(zip(prediction_gradients, self.trainable_variables))
        self.add_loss(lambda: prediction_loss)
        return {"loss": prediction_loss}
        
    def call(self, inputs, training):
        return self.train_step(inputs)

model = Model()
model.compile(optimizer=tf.keras.optimizers.Adam(0.001))


data_gen = BatchGen()
model.fit(data_gen, epochs=10)
```

Running the above code gives the following error - 
```
Epoch 1/10
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-5-71ab935a83be> in <module>
----> 1 model.fit(data_gen, epochs=10)

~/miniconda3/envs/rasa_master/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
    106   def _method_wrapper(self, *args, **kwargs):
    107     if not self._in_multi_worker_mode():  # pylint: disable=protected-access
--> 108       return method(self, *args, **kwargs)
    109 
    110     # Running inside `run_distribute_coordinator` already.

~/miniconda3/envs/rasa_master/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1096                 batch_size=batch_size):
   1097               callbacks.on_train_batch_begin(step)
-> 1098               tmp_logs = train_function(iterator)
   1099               if data_handler.should_sync:
   1100                 context.async_wait()

~/miniconda3/envs/rasa_master/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    778       else:
    779         compiler = "nonXla"
--> 780         result = self._call(*args, **kwds)
    781 
    782       new_tracing_count = self._get_tracing_count()

~/miniconda3/envs/rasa_master/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    844               *args, **kwds)
    845       # If we did not create any variables the trace we have is good enough.
--> 846       return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
    847 
    848     def fn_with_cond(*inner_args, **inner_kwds):

~/miniconda3/envs/rasa_master/lib/python3.7/site-packages/tensorflow/python/eager/function.py in _filtered_call(self, args, kwargs, cancellation_manager)
   1846                            resource_variable_ops.BaseResourceVariable))],
   1847         captured_inputs=self.captured_inputs,
-> 1848         cancellation_manager=cancellation_manager)
   1849 
   1850   def _call_flat(self, args, captured_inputs, cancellation_manager=None):

~/miniconda3/envs/rasa_master/lib/python3.7/site-packages/tensorflow/python/eager/function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1922       # No tape is watching; skip to running the function.
   1923       return self._build_call_outputs(self._inference_function.call(
-> 1924           ctx, args, cancellation_manager=cancellation_manager))
   1925     forward_backward = self._select_forward_and_backward_functions(
   1926         args,

~/miniconda3/envs/rasa_master/lib/python3.7/site-packages/tensorflow/python/eager/function.py in call(self, ctx, args, cancellation_manager)
    548               inputs=args,
    549               attrs=attrs,
--> 550               ctx=ctx)
    551         else:
    552           outputs = execute.execute_with_cancellation(

~/miniconda3/envs/rasa_master/lib/python3.7/site-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

InvalidArgumentError:  TypeError: `generator` yielded an element that could not be converted to the expected type. The expected type was float32, but the yielded element was <tf.RaggedTensor [[[0.0, 0.0], [0.0, 0.0]], [[1.0, 1.0], [1.0, 1.0]]]>.
Traceback (most recent call last):

  File "/Users/daksh/miniconda3/envs/rasa_master/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 843, in generator_py_func
    ret, dtype=dtype.as_numpy_dtype))

  File "/Users/daksh/miniconda3/envs/rasa_master/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 204, in _convert
    result = np.asarray(value, dtype=dtype, order="C")

  File "/Users/daksh/miniconda3/envs/rasa_master/lib/python3.7/site-packages/numpy/core/numeric.py", line 538, in asarray
    return array(a, dtype, copy=False, order=order)

ValueError: setting an array element with a sequence.


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/Users/daksh/miniconda3/envs/rasa_master/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 244, in __call__
    ret = func(*args)

  File "/Users/daksh/miniconda3/envs/rasa_master/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 302, in wrapper
    return func(*args, **kwargs)

  File "/Users/daksh/miniconda3/envs/rasa_master/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 848, in generator_py_func
    "element was %s." % (dtype.name, ret)), sys.exc_info()[2])

  File "/Users/daksh/miniconda3/envs/rasa_master/lib/python3.7/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)

  File "/Users/daksh/miniconda3/envs/rasa_master/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 843, in generator_py_func
    ret, dtype=dtype.as_numpy_dtype))

  File "/Users/daksh/miniconda3/envs/rasa_master/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 204, in _convert
    result = np.asarray(value, dtype=dtype, order="C")

  File "/Users/daksh/miniconda3/envs/rasa_master/lib/python3.7/site-packages/numpy/core/numeric.py", line 538, in asarray
    return array(a, dtype, copy=False, order=order)

TypeError: `generator` yielded an element that could not be converted to the expected type. The expected type was float32, but the yielded element was <tf.RaggedTensor [[[0.0, 0.0], [0.0, 0.0]], [[1.0, 1.0], [1.0, 1.0]]]>.


	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]] [Op:__inference_train_function_170]

Function call stack:
train_function
```

The error seems to be coming because the inner rows of the ragged tensor have different size of the first dimension.

Note, that there is no error when I replace `gen_ragged_tensors` with:

```
def gen_ragged_tensors():
        seq_len = np.random.randint(1,3)
        a = np.zeros((seq_len,2), dtype=np.float32)
        b = np.ones((seq_len,2), dtype=np.float32)
        c = tf.ragged.constant([a,b], dtype=tf.float32, inner_shape=(2, seq_len, 2))
        return c
```

This is not useful in reality because this needs me to firstly use the same size of first dimension for all rows of the ragged tensor and secondly requires me to specify the `inner_shape` which is not guaranteed to be known because we want to pass irregular shaped tensors to our model.

Any suggestions on what might be going wrong are very helpful.

**Describe the expected behavior**

Successfully being able to pass irregular shaped ragged tensors into a custom keras model. These ragged tensors should be yielded by a data generator of type `tf.keras.utils.Sequence`.

**Standalone code to reproduce the issue**
Provided above

**Comment by Saduf2019** [comment]
@dakshvar22 
I ran the code shared and face "invalid syntax: error, can you please check you code and share a colab gist with the error reported.

**Comment by dakshvar22** [comment]
@Saduf2019 There was a missing parenthesis. Updated the code. It should work now.

**Comment by Saduf2019** [comment]
I am able to replicate this issue on 2.3,2.4 and nightly, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/33af235b715ba87e27cbe0243e277283/untitled579.ipynb).

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF nightly-2.6.0.dev20210603,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/13c2de2d81f4820f0a17cf1281d8f0ac/untitled211.ipynb)..Thanks !

**Comment by jvishnuvardhan** [comment]
@dakshvar22 Looks like this was resolved in recent `tf-nightly`. [Here](https://colab.research.google.com/gist/jvishnuvardhan/d37c0552f50a0c5aba0ee3f127105d62/untitled211.ipynb) is a gist for reference.

Can you please verify once and close the issue if this was resolved for you.

If this was not resolved, can you please open the issue in keras-team/keras repo as keras development moved to that repo to focus mainly on Keras. 

Please note that Keras development moved to [keras-team/keras repo](https://github.com/keras-team/keras/issues) repository to focus entirely on only keras. Thanks!
