### ISSUE TITLE
Error when loading trained model with tf.keras.models.load_model

### ISSUE THREAD

**Issue by bjkomer** [tensorflow/tensorflow#48235]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.1
- Python version: 3.8.0
- CUDA/cuDNN version: 11.0.221 / 8.0.4 
- GPU model and memory: RTX 3090 24GB

**Describe the current behavior**

When loading a model with `tf.keras.models.load_model` that has been saved with `model.save` the following error occurs:

```
Traceback (most recent call last):
  File "loading_minimal_example.py", line 29, in <module>
    model = tf.keras.models.load_model(
  File "/home/bjkomer/anaconda3/envs/myenv/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 212, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "/home/bjkomer/anaconda3/envs/myenv/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 138, in load
    keras_loader.load_layers(compile=compile)
  File "/home/bjkomer/anaconda3/envs/myenv/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 380, in load_layers
    self.loaded_nodes[node_metadata.node_id] = self._load_layer(
  File "/home/bjkomer/anaconda3/envs/myenv/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 417, in _load_layer
    obj, setter = self._revive_from_config(identifier, metadata, node_id)
  File "/home/bjkomer/anaconda3/envs/myenv/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 431, in _revive_from_config
    obj = self._revive_metric_from_config(metadata)
  File "/home/bjkomer/anaconda3/envs/myenv/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 540, in _revive_metric_from_config
    obj = metrics.deserialize(
  File "/home/bjkomer/anaconda3/envs/myenv/lib/python3.8/site-packages/tensorflow/python/keras/metrics.py", line 3446, in deserialize
    return deserialize_keras_object(
  File "/home/bjkomer/anaconda3/envs/myenv/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 346, in deserialize_keras_object
    (cls, cls_config) = class_and_config_for_serialized_keras_object(
  File "/home/bjkomer/anaconda3/envs/myenv/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 311, in class_and_config_for_serialized_keras_object
    deserialized_objects[key] = deserialize_keras_object(
  File "/home/bjkomer/anaconda3/envs/myenv/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 360, in deserialize_keras_object
    return cls.from_config(cls_config)
  File "/home/bjkomer/anaconda3/envs/myenv/lib/python3.8/site-packages/tensorflow/python/keras/metrics.py", line 642, in from_config
    return super(MeanMetricWrapper, cls).from_config(config)
  File "/home/bjkomer/anaconda3/envs/myenv/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 720, in from_config
    return cls(**config)
TypeError: __init__() got an unexpected keyword argument 'reduction'
```

**Describe the expected behavior**

The model will be loaded without errors.

**Standalone code to reproduce the issue**

```python
import tensorflow as tf
import numpy as np
from tensorflow.keras.layers import Input
from tensorflow.keras.models import Model

inp = Input(shape=(None, 10))

out = tf.keras.layers.LSTM(50)(inp)

model = Model(inputs=inp, outputs=out)
  
optimizer = tf.keras.optimizers.Adam(learning_rate=1e-3)
loss = tf.keras.losses.BinaryCrossentropy()

model.compile(
    optimizer=optimizer,
    loss=loss,
    metrics=loss,
)


history = model.fit(
    np.zeros((32, 16, 10)),
    np.zeros((32, 50)),
    steps_per_epoch=1,
    epochs=2,
) 

model.save("my_model")

del model
  
model = tf.keras.models.load_model(
    "my_model", compile=False
)
```

Note that if `model.fit` is not called, the model will be loaded fine. Also, if metrics are not given to `model.compile` it will also be loaded fine. This error only occurs if the model has been trained while reporting metrics.
Edit: the model doesn't need to be recurrent, the issue also happens with a single dense layer

**Comment by amahendrakar** [comment]
@bjkomer,
Looks like the error was caused because of using the same loss function `loss = tf.keras.losses.BinaryCrossentropy()` for both `loss` and `metrics`.

On adding the metric function `metric = tf.keras.metrics.BinaryCrossentropy()`, I was able to run the code without any issues. 

Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/226883d6d57c84caf98c7df91d60bf66/48235.ipynb#scrollTo=mY_NlmWsXrWw). Thanks!

**Comment by bjkomer** [comment]
Thanks! Using that separate metric function made it work for me as well.

Interestingly I also noticed it seems to run fine using the same loss function for both `loss` and `metrics` if it is a custom loss function. For example:

```python
# ...
loss = tf.keras.losses.BinaryCrossentropy()

def custom_loss(y_true, y_pred):
    return loss(y_true, y_pred)

model.compile(
    optimizer=optimizer,
    loss=custom_loss,
    metrics=custom_loss,
)
# ...
model = tf.keras.models.load_model(
    "my_model", compile=False,
    custom_objects={"custom_loss": custom_loss},
)
```

**Comment by amahendrakar** [comment]
> Thanks! Using that separate metric function made it work for me as well.

@bjkomer,
Thank you for the update. 

Is this still an issue? Please feel free to close the issue if it is resolved.

**Comment by bjkomer** [comment]
For my specific case this has been resolved. There is still the related issue of the error message not being very helpful and inconsistent behaviour of the original model and restored model when `model.fit` is called. That could be treated as a separate issue though.

**Comment by stengoes** [comment]
@bjkomer: you need to use `tf.keras.losses.BinaryCrossentropy` for loss and `tf.keras.metrics.BinaryCrossentropy` for metrics.
