### ISSUE TITLE
Failed to get convolution algorithm

### ISSUE THREAD

**Issue by kbrajwani** [tensorflow/tensorflow#48266]
**System information**
- OS Platform and Distribution Linux Ubuntu 18.04 aws dlami
- TensorFlow version : tensorflow==2.5.0rc0
- Python version:  3.6
- CUDA/cuDNN version: cuda 11.0
- GPU model and memory:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:1E.0 Off |                    0 |
| N/A   31C    P0    32W /  70W |   6220MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2685      C   python                           6217MiB |
+-----------------------------------------------------------------------------+

** current behaviour**
```2021-04-02 05:38:06.872091: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-04-02 05:38:06.888553: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2499995000 Hz
2021-04-02 05:38:07.028741: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-04-02 05:38:07.528481: E tensorflow/stream_executor/cuda/cuda_dnn.cc:352] Loaded runtime CuDNN library: 8.0.5 but source was compiled with: 8.1.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2021-04-02 05:38:07.531403: E tensorflow/stream_executor/cuda/cuda_dnn.cc:352] Loaded runtime CuDNN library: 8.0.5 but source was compiled with: 8.1.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2021-04-02 05:38:07.532382: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at conv_ops_fused_impl.h:698 : Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/tf_pytorch_p36/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1727, in predict
    tmp_batch_outputs = self.predict_function(iterator)
  File "/home/ubuntu/anaconda3/envs/tf_pytorch_p36/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 872, in __call__
    result = self._call(*args, **kwds)
  File "/home/ubuntu/anaconda3/envs/tf_pytorch_p36/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 940, in _call
    filtered_flat_args, self._concrete_stateful_fn.captured_inputs)  # pylint: disable=protected-access
  File "/home/ubuntu/anaconda3/envs/tf_pytorch_p36/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1961, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/ubuntu/anaconda3/envs/tf_pytorch_p36/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 596, in call
    ctx=ctx)
  File "/home/ubuntu/anaconda3/envs/tf_pytorch_p36/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node model/block1_conv1/Relu (defined at <stdin>:1) ]] [Op:__inference_predict_function_618]

Function call stack:
predict_function
```

I am getting error with latest tensorflow 2.5.0 its working fine with tensorflow 2.4.0. Also it's work with tensorflow 2.5.0 in colab but in my server is giving me error.

**Comment by ymodak** [comment]
Please try with cuda 11.2 for TF 2.5.X versions.

**Comment by kbrajwani** [comment]
hey @ymodak 
I have changed cuda version but still getiing same error

command for installation : 
```
sudo apt install cuda-11.2
sudo apt-get install --no-install-recommends nvidia-driver-460
```

nvidia-smi
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.39       Driver Version: 460.39       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   32C    P0    26W /  70W |  10091MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      3040      C   python                           6229MiB |
|    0   N/A  N/A      3224      C   python                           3859MiB |
+-----------------------------------------------------------------------------+

```

**Comment by ymodak** [comment]
> Loaded runtime CuDNN library: 8.0.5 but source was compiled with: 8.1.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.

Can you also upgrade your cudnn to 8.1.0?
