### ISSUE TITLE
ERROR: An error occurred during the fetch of repository 'local_config_python':

### ISSUE THREAD

**Issue by TropicalTsunami** [tensorflow/tensorflow#48264]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.4.1
- Python version: 3.8
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 2.7.2
- GCC/Compiler version (if compiling from source): not sure how to check this
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the problem**
Building TF with bazel is not working. The cause seems to be:
**ERROR: An error occurred during the fetch of repository 'local_config_python'**:
I am not sure what exactly the error means or how to fix it. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**

(build_tf_apr21) C:\git_repositories\BlinkGuard\code\tensorflow>python configure.py
You have bazel 3.7.2 installed.
Please specify the location of python. [Default is C:\Users\gerri\anaconda3\envs\build_tf_apr21\python.exe]:

Found possible Python library paths:
  C:\Users\gerri\anaconda3\envs\build_tf_apr21\lib\site-packages
Please input the desired Python library path to use.  Default is [C:\Users\gerri\anaconda3\envs\build_tf_apr21\lib\site-packages]

Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: n
No CUDA support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]:

Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]: n
Not overriding eigen strong inline, some compilations could take more than 20 mins.

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: n
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=mkl_aarch64    # Build with oneDNN and Compute Library for the Arm Architecture (ACL).
        --config=monolithic     # Config for mostly static monolithic build.
        --config=numa           # Build with NUMA support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
        --config=v2             # Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=noaws          # Disable AWS S3 filesystem support.
        --config=nogcp          # Disable GCP support.
        --config=nohdfs         # Disable HDFS support.
        --config=nonccl         # Disable NVIDIA NCCL support.

(build_tf_apr21) C:\git_repositories\BlinkGuard\code\tensorflow>bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --copt=-
msse4.1 --copt=-msse4.2 -k //tensorflow/tools/pip_package:build_pip_package
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=152
INFO: Reading rc options for 'build' from c:\git_repositories\blinkguard\code\tensorflow\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=C:/Users/gerri/anaconda3/envs/build_tf_apr21/python.exe
INFO: Reading rc options for 'build' from c:\git_repositories\blinkguard\code\tensorflow\.bazelrc:
  'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_to
olchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --a
nnounce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --d
efine=with_xla_support=true --config=short_logs --config=v2
INFO: Reading rc options for 'build' from c:\git_repositories\blinkguard\code\tensorflow\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=C:/Users/gerri/anaconda3/envs/build_tf_apr21/python.exe --action_env PYTHON_LIB_PATH=C:/Users/gerri/anac
onda3/envs/build_tf_apr21/lib/site-packages --python_path=C:/Users/gerri/anaconda3/envs/build_tf_apr21/python.exe --copt=/d2ReducedOptimizeHugeFunctions
 --host_copt=/d2ReducedOptimizeHugeFunctions
INFO: Found applicable config definition build:short_logs in file c:\git_repositories\blinkguard\code\tensorflow\.bazelrc: --output_filter=DONT_MATCH_AN
YTHING
INFO: Found applicable config definition build:v2 in file c:\git_repositories\blinkguard\code\tensorflow\.bazelrc: --define=tf_api_version=2 --action_en
v=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:windows in file c:\git_repositories\blinkguard\code\tensorflow\.bazelrc: --copt=/W0 --copt=/D_USE_MATH_DE
FINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_
LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=/experimental:preprocessor --host_copt=/experimental:preprocessor --linkopt=/DEBUG --host_linkop
t=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --verbose_failures --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file c:\git_repositories\blinkguard\code\tensorflow\.bazelrc: --define framework_shared_obj
ect=false
DEBUG: C:/users/gerri/_bazel_gerri/wwc5pzrd/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA prop
rietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree t
o the terms of the license agreement, do not use the software.
WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/40548a2974f1aea06215272d9c2b47a14a24e556.tar.gz failed: class c
om.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: Build options --copt, --define, and --host_copt have changed, discarding analysis cache.
INFO: Repository local_execution_config_python instantiated at:
  C:/git_repositories/blinkguard/code/tensorflow/WORKSPACE:15:14: in <toplevel>
  C:/git_repositories/blinkguard/code/tensorflow/tensorflow/workspace2.bzl:1099:19: in workspace
  C:/git_repositories/blinkguard/code/tensorflow/tensorflow/workspace2.bzl:85:27: in _tf_toolchains
  C:/users/gerri/_bazel_gerri/wwc5pzrd/external/tf_toolchains/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  C:/users/gerri/_bazel_gerri/wwc5pzrd/external/tf_toolchains/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  C:/git_repositories/blinkguard/code/tensorflow/third_party/py/python_configure.bzl:275:41: in <toplevel>
INFO: Repository local_config_python instantiated at:
  C:/git_repositories/blinkguard/code/tensorflow/WORKSPACE:15:14: in <toplevel>
  C:/git_repositories/blinkguard/code/tensorflow/tensorflow/workspace2.bzl:1099:19: in workspace
  C:/git_repositories/blinkguard/code/tensorflow/tensorflow/workspace2.bzl:95:21: in _tf_toolchains
Repository rule python_configure defined at:
  C:/git_repositories/blinkguard/code/tensorflow/third_party/py/python_configure.bzl:294:35: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/git_repositories/blinkguard/code/tensorflow/third_party/py/python_configure.bzl", line 209, column 22, in _create_local_python_reposito
ry
                _check_python_bin(repository_ctx, python_bin)
        File "C:/git_repositories/blinkguard/code/tensorflow/third_party/py/python_configure.bzl", line 143, column 52, in _check_python_bin
                result = raw_exec(repository_ctx, [get_bash_bin(repository_ctx), "-c", cmd])
        File "C:/git_repositories/blinkguard/code/tensorflow/third_party/remote_config/common.bzl", line 77, column 26, in get_bash_bin
                bash_bin_path = which(repository_ctx, "bash")
        File "C:/git_repositories/blinkguard/code/tensorflow/third_party/remote_config/common.bzl", line 27, column 23, in which
                return execute(
        File "C:/git_repositories/blinkguard/code/tensorflow/third_party/remote_config/common.bzl", line 219, column 13, in execute
                fail(
Error in fail: Repository command failed
INFO: Could not find files for the given pattern(s).
ERROR: An error occurred during the fetch of repository 'local_config_python':
   Traceback (most recent call last):
        File "C:/git_repositories/blinkguard/code/tensorflow/third_party/py/python_configure.bzl", line 267, column 40, in _python_autoconf_impl
                _create_local_python_repository(repository_ctx)
        File "C:/git_repositories/blinkguard/code/tensorflow/third_party/py/python_configure.bzl", line 209, column 22, in _create_local_python_reposito
ry
                _check_python_bin(repository_ctx, python_bin)
        File "C:/git_repositories/blinkguard/code/tensorflow/third_party/py/python_configure.bzl", line 143, column 52, in _check_python_bin
                result = raw_exec(repository_ctx, [get_bash_bin(repository_ctx), "-c", cmd])
        File "C:/git_repositories/blinkguard/code/tensorflow/third_party/remote_config/common.bzl", line 77, column 26, in get_bash_bin
                bash_bin_path = which(repository_ctx, "bash")
        File "C:/git_repositories/blinkguard/code/tensorflow/third_party/remote_config/common.bzl", line 27, column 23, in which
                return execute(
        File "C:/git_repositories/blinkguard/code/tensorflow/third_party/remote_config/common.bzl", line 219, column 13, in execute
                fail(
Error in fail: Repository command failed
INFO: Could not find files for the given pattern(s).
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -040
0"
DEBUG: Repository io_bazel_rules_docker instantiated at:
  C:/git_repositories/blinkguard/code/tensorflow/WORKSPACE:23:14: in <toplevel>
  C:/git_repositories/blinkguard/code/tensorflow/tensorflow/workspace0.bzl:108:34: in workspace
  C:/users/gerri/_bazel_gerri/wwc5pzrd/external/bazel_toolchains/repositories/repositories.bzl:37:23: in repositories
Repository rule git_repository defined at:
  C:/users/gerri/_bazel_gerri/wwc5pzrd/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
WARNING: errors encountered while analyzing target '//tensorflow/tools/pip_package:build_pip_package': it will not be built
INFO: Analyzed target //tensorflow/tools/pip_package:build_pip_package (0 packages loaded, 4017 targets configured).
INFO: Found 0 targets...
ERROR: command succeeded, but not all targets were analyzed
INFO: Elapsed time: 4.195s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
FAILED: Build did NOT complete successfully

**Comment by TropicalTsunami** [comment]
Update: 

I wondered if the actual problem could have been:
WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/40548a2974f1aea06215272d9c2b47a14a24e556.tar.gz failed: class c
om.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found

I tried 
bazel clean --expunge

Then I repeated bazel build using a VPN (I am **not** in China). This time I get no download warning but still the same error as before:

(build_tf_apr21) C:\git_repositories\BlinkGuard\code\tensorflow>bazel clean --expunge
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=152
INFO: Reading rc options for 'clean' from c:\git_repositories\blinkguard\code\tensorflow\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  Inherited 'build' options: --python_path=C:/Users/gerri/anaconda3/envs/build_tf_apr21/python.exe
INFO: Reading rc options for 'clean' from c:\git_repositories\blinkguard\code\tensorflow\.bazelrc:
  Inherited 'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolch
ain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone
-c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_
config --define=with_xla_support=true --config=short_logs --config=v2
INFO: Reading rc options for 'clean' from c:\git_repositories\blinkguard\code\tensorflow\.tf_configure.bazelrc:
  Inherited 'build' options: --action_env PYTHON_BIN_PATH=C:/Users/gerri/anaconda3/envs/build_tf_apr21/python.exe --action_env PYTHON_LIB_PATH=C:/Users/
gerri/anaconda3/envs/build_tf_apr21/lib/site-packages --python_path=C:/Users/gerri/anaconda3/envs/build_tf_apr21/python.exe --copt=/d2ReducedOptimizeHug
eFunctions --host_copt=/d2ReducedOptimizeHugeFunctions
INFO: Found applicable config definition build:short_logs in file c:\git_repositories\blinkguard\code\tensorflow\.bazelrc: --output_filter=DONT_MATCH_AN
YTHING
INFO: Found applicable config definition build:v2 in file c:\git_repositories\blinkguard\code\tensorflow\.bazelrc: --define=tf_api_version=2 --action_en
v=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:windows in file c:\git_repositories\blinkguard\code\tensorflow\.bazelrc: --copt=/W0 --copt=/D_USE_MATH_DE
FINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_
LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=/experimental:preprocessor --host_copt=/experimental:preprocessor --linkopt=/DEBUG --host_linkop
t=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --verbose_failures --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file c:\git_repositories\blinkguard\code\tensorflow\.bazelrc: --define framework_shared_obj
ect=false
INFO: Starting clean.

(build_tf_apr21) C:\git_repositories\BlinkGuard\code\tensorflow>bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --copt=-
msse4.1 --copt=-msse4.2 -k //tensorflow/tools/pip_package:build_pip_package
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=152
INFO: Reading rc options for 'build' from c:\git_repositories\blinkguard\code\tensorflow\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=C:/Users/gerri/anaconda3/envs/build_tf_apr21/python.exe
INFO: Reading rc options for 'build' from c:\git_repositories\blinkguard\code\tensorflow\.bazelrc:
  'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_to
olchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --a
nnounce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --d
efine=with_xla_support=true --config=short_logs --config=v2
INFO: Reading rc options for 'build' from c:\git_repositories\blinkguard\code\tensorflow\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=C:/Users/gerri/anaconda3/envs/build_tf_apr21/python.exe --action_env PYTHON_LIB_PATH=C:/Users/gerri/anac
onda3/envs/build_tf_apr21/lib/site-packages --python_path=C:/Users/gerri/anaconda3/envs/build_tf_apr21/python.exe --copt=/d2ReducedOptimizeHugeFunctions
 --host_copt=/d2ReducedOptimizeHugeFunctions
INFO: Found applicable config definition build:short_logs in file c:\git_repositories\blinkguard\code\tensorflow\.bazelrc: --output_filter=DONT_MATCH_AN
YTHING
INFO: Found applicable config definition build:v2 in file c:\git_repositories\blinkguard\code\tensorflow\.bazelrc: --define=tf_api_version=2 --action_en
v=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:windows in file c:\git_repositories\blinkguard\code\tensorflow\.bazelrc: --copt=/W0 --copt=/D_USE_MATH_DE
FINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_
LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=/experimental:preprocessor --host_copt=/experimental:preprocessor --linkopt=/DEBUG --host_linkop
t=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --verbose_failures --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file c:\git_repositories\blinkguard\code\tensorflow\.bazelrc: --define framework_shared_obj
ect=false
DEBUG: C:/users/gerri/_bazel_gerri/wwc5pzrd/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA prop
rietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree t
o the terms of the license agreement, do not use the software.
INFO: Repository local_execution_config_python instantiated at:
  C:/git_repositories/blinkguard/code/tensorflow/WORKSPACE:15:14: in <toplevel>
  C:/git_repositories/blinkguard/code/tensorflow/tensorflow/workspace2.bzl:1099:19: in workspace
  C:/git_repositories/blinkguard/code/tensorflow/tensorflow/workspace2.bzl:85:27: in _tf_toolchains
  C:/users/gerri/_bazel_gerri/wwc5pzrd/external/tf_toolchains/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  C:/users/gerri/_bazel_gerri/wwc5pzrd/external/tf_toolchains/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  C:/git_repositories/blinkguard/code/tensorflow/third_party/py/python_configure.bzl:275:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/git_repositories/blinkguard/code/tensorflow/third_party/py/python_configure.bzl", line 209, column 22, in _create_local_python_reposito
ry
                _check_python_bin(repository_ctx, python_bin)
        File "C:/git_repositories/blinkguard/code/tensorflow/third_party/py/python_configure.bzl", line 143, column 52, in _check_python_bin
                result = raw_exec(repository_ctx, [get_bash_bin(repository_ctx), "-c", cmd])
        File "C:/git_repositories/blinkguard/code/tensorflow/third_party/remote_config/common.bzl", line 77, column 26, in get_bash_bin
                bash_bin_path = which(repository_ctx, "bash")
        File "C:/git_repositories/blinkguard/code/tensorflow/third_party/remote_config/common.bzl", line 27, column 23, in which
                return execute(
        File "C:/git_repositories/blinkguard/code/tensorflow/third_party/remote_config/common.bzl", line 219, column 13, in execute
                fail(
Error in fail: Repository command failed
INFO: Could not find files for the given pattern(s).
INFO: Repository local_config_python instantiated at:
  C:/git_repositories/blinkguard/code/tensorflow/WORKSPACE:15:14: in <toplevel>
  C:/git_repositories/blinkguard/code/tensorflow/tensorflow/workspace2.bzl:1099:19: in workspace
  C:/git_repositories/blinkguard/code/tensorflow/tensorflow/workspace2.bzl:95:21: in _tf_toolchains
Repository rule python_configure defined at:
  C:/git_repositories/blinkguard/code/tensorflow/third_party/py/python_configure.bzl:294:35: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_python':
   Traceback (most recent call last):
        File "C:/git_repositories/blinkguard/code/tensorflow/third_party/py/python_configure.bzl", line 267, column 40, in _python_autoconf_impl
                _create_local_python_repository(repository_ctx)
        File "C:/git_repositories/blinkguard/code/tensorflow/third_party/py/python_configure.bzl", line 209, column 22, in _create_local_python_reposito
ry
                _check_python_bin(repository_ctx, python_bin)
        File "C:/git_repositories/blinkguard/code/tensorflow/third_party/py/python_configure.bzl", line 143, column 52, in _check_python_bin
                result = raw_exec(repository_ctx, [get_bash_bin(repository_ctx), "-c", cmd])
        File "C:/git_repositories/blinkguard/code/tensorflow/third_party/remote_config/common.bzl", line 77, column 26, in get_bash_bin
                bash_bin_path = which(repository_ctx, "bash")
        File "C:/git_repositories/blinkguard/code/tensorflow/third_party/remote_config/common.bzl", line 27, column 23, in which
                return execute(
        File "C:/git_repositories/blinkguard/code/tensorflow/third_party/remote_config/common.bzl", line 219, column 13, in execute
                fail(
Error in fail: Repository command failed
INFO: Could not find files for the given pattern(s).
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -040
0"
DEBUG: Repository io_bazel_rules_docker instantiated at:
  C:/git_repositories/blinkguard/code/tensorflow/WORKSPACE:23:14: in <toplevel>
  C:/git_repositories/blinkguard/code/tensorflow/tensorflow/workspace0.bzl:108:34: in workspace
  C:/users/gerri/_bazel_gerri/wwc5pzrd/external/bazel_toolchains/repositories/repositories.bzl:37:23: in repositories
Repository rule git_repository defined at:
  C:/users/gerri/_bazel_gerri/wwc5pzrd/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
WARNING: errors encountered while analyzing target '//tensorflow/tools/pip_package:build_pip_package': it will not be built
INFO: Analyzed target //tensorflow/tools/pip_package:build_pip_package (234 packages loaded, 4017 targets configured).
INFO: Found 0 targets...
ERROR: command succeeded, but not all targets were analyzed
INFO: Elapsed time: 727.072s, Critical Path: 0.03s
INFO: 1 process: 1 internal.
FAILED: Build did NOT complete successfully

**Comment by TropicalTsunami** [comment]
resolved. I was missing MSYS2.

Suggestions:

1) On https://www.tensorflow.org/install/source link to the instructions for windows. I was following the instructions on the URL linked before which gives the impression as the same steps apply to windows, just that windows is not actively supported. Despite that there is a guide for windows: https://www.tensorflow.org/install/source_windows 
2) Print a descriptive error message that MSYS2 is missing. The current error message does not point the user towards what is the exact cause or fix of the error.
