### ISSUE TITLE
ImportError: No module named '_pywrap_tensorflow_internal'

### ISSUE THREAD

**Issue by vanshika-653** [tensorflow/tensorflow#48267]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows 10 64amd
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:1.5.0
- Python version:3.5.2 , 3.6,3.7,3.8 & 3.9.2 64amd 
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
C:\Users\Vanshika Gupta\AppData\Local\Programs\Python\Python39\sign-language-gesture-recognition-master>python retrain.py --bottleneck_dir=bottlenecks --summaries_dir=training_summaries/long --output_graph=retrained_graph.pb --output_labels=retrained_labels.txt --image_dir=train_frames
Traceback (most recent call last):
  File "C:\Users\Vanshika Gupta\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
  File "C:\Users\Vanshika Gupta\AppData\Local\Programs\Python\Python39\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vanshika Gupta\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\__init__.py", line 66, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Vanshika Gupta\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\Users\Vanshika Gupta\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ModuleNotFoundError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vanshika Gupta\AppData\Local\Programs\Python\Python39\sign-language-gesture-recognition-master\retrain.py", line 132, in <module>
    import tensorflow as tf
  File "C:\Users\Vanshika Gupta\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\Vanshika Gupta\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Vanshika Gupta\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
  File "C:\Users\Vanshika Gupta\AppData\Local\Programs\Python\Python39\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vanshika Gupta\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\__init__.py", line 66, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Vanshika Gupta\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\Users\Vanshika Gupta\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ModuleNotFoundError: No module named '_pywrap_tensorflow'

Failed to load the native TensorFlow runtime.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@vanshika-653 
We see that you are using an old version of TensorFlow for which there is no support, can you please upgrade to 2.x [2.4] and let us know if you till face the issue reported.
You may refer to few old issues with same error: #22512, [link](https://github.com/tensorflow/tensorflow/issues/7529), [link1](https://github.com/tensorflow/tensorflow/issues/40668#issuecomment-647885727)

**Comment by grantcroft** [comment]
I am getting a similar error: 

when running in jupyter notebook:

ModuleNotFoundError: No module named '_pywrap_tensorflow'


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.







when just trying to import if va cmd: 
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'




Any solutions would be great! thanks

**Comment by Saduf2019** [comment]
@grantcroft 
Please share your code such that we can replicate the issue reported, or a colab gist with the error and version used.

**Comment by nsa-123** [comment]
I am also facing the same error.

python --version gave
Python 3.7.0

Tensorflow version is

(0.12.0)

I have already installed Microsoft Visual C++ Redistribution (x64) 9.0.30729.17/.6161 / .21022 /(x86) 30729.17/ (x86) 30729.6161

Microsoft Visual C++ Redistribution2015-2019 (x64) 14.25.28508
Microsoft Visual C++ Redistribution2015-2019 (x64) 14.31.31103

I have included path to all dlls to environment variable path.

OS is Win 7 Ultimate.

When I do
import tensorflow as tf

I get following error
`---------------------------------------------------------------------------
ImportError Traceback (most recent call last)
h:\python installed\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in swig_import_helper()
17 try:
---> 18 fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(file)])
19 except ImportError:

h:\python installed\lib\imp.py in find_module(name, path)
296 else:
--> 297 raise ImportError(_ERR_MSG.format(name), name=name)
298

ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

ModuleNotFoundError Traceback (most recent call last)
h:\python installed\lib\site-packages\tensorflow\python_init_.py in
53 # use dlopen() for dynamic loading.
---> 54 from tensorflow.python import pywrap_tensorflow
55 except ImportError:

h:\python installed\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in
27 return _mod
---> 28 _pywrap_tensorflow = swig_import_helper()
29 del swig_import_helper

h:\python installed\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in swig_import_helper()
19 except ImportError:
---> 20 import _pywrap_tensorflow
21 return _pywrap_tensorflow

ModuleNotFoundError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

ImportError Traceback (most recent call last)
in
----> 1 import tensorflow as tf
2 from tensorflow.keras.utils import to_categorical

h:\python installed\lib\site-packages\tensorflow_init_.py in
22
23 # pylint: disable=wildcard-import
---> 24 from tensorflow.python import *
25 # pylint: enable=wildcard-import
26

h:\python installed\lib\site-packages\tensorflow\python_init_.py in
58 please exit the tensorflow source tree, and relaunch your python interpreter
59 from there.""" % traceback.format_exc()
---> 60 raise ImportError(msg)
61
62 # Protocol buffers

ImportError: Traceback (most recent call last):
File "h:\python installed\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(file)])
File "h:\python installed\lib\imp.py", line 297, in find_module
raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "h:\python installed\lib\site-packages\tensorflow\python_init_.py", line 54, in
from tensorflow.python import pywrap_tensorflow
File "h:\python installed\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in
_pywrap_tensorflow = swig_import_helper()
File "h:\python installed\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
import _pywrap_tensorflow
ModuleNotFoundError: No module named '_pywrap_tensorflow'

Error importing tensorflow. Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.`
