### ISSUE TITLE
TFLite Android 'Didn't find op for builtin opcode 'RESIZE_NEAREST_NEIGHBOR' version '3''

### ISSUE THREAD

**Issue by Ean244** [tensorflow/tensorflow#48277]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Huawei Nova 3i
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.3
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I am trying to convert this YoloV3 model, written for tensorflow v2.0 to a tflite model. https://github.com/YunYang1994/tensorflow-yolov3
The model is first compiled and saved. Then, it is converted.
Here is my code for converting the model:
```
import tensorflow as tf

converter = tf.lite.TFLiteConverter.from_saved_model("model")
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
tflite_model = converter.convert()
open("converted_model/model.tflite", "wb").write(tflite_model)
```

The tflite model is imported into Android Studio using New > Other > Tflite Model
However, when running the model an error occurred:
```
Registration failed.
    
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5078)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5120)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: java.lang.IllegalArgumentException: Internal error: Cannot create interpreter: Didn't find op for builtin opcode 'RESIZE_NEAREST_NEIGHBOR' version '3'
```
I am using
```
    implementation 'org.tensorflow:tensorflow-lite-support:0.1.0'
    implementation 'org.tensorflow:tensorflow-lite-metadata:0.1.0'
    implementation 'org.tensorflow:tensorflow-lite-gpu:2.4.0'
```

Thanks.

**Comment by abattery** [comment]
Could you use the tf 2.4.1 or tf-nightly version?

'org.tensorflow:tensorflow-lite-gpu:2.4.1'

or

org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly

**Comment by Ean244** [comment]
May I know what is the repository for 'org.tensorflow:tensorflow-lite-gpu:2.4.1'?
Thanks

**Comment by abattery** [comment]
I figure out that you need to add the following dependency as well. 

org.tensorflow:tensorflow-lite:2.4.0

See also the dependency part in https://www.tensorflow.org/lite/performance/gpu#android_with_android_studio

**Comment by Ean244** [comment]
While trying with org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly, it seems to be working.
However, a new issue arises
```
at android.app.ActivityThread.deliverResults(ActivityThread.java:5078)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5120)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: tensorflow/lite/kernels/reshape.cc:58 stretch_dim != -1 (0 != -1)
    Node number 168 (RESHAPE) failed to prepare.
```

The java code which is causing the issue:
```
Model model = Model.newInstance(context);

            TensorBuffer feature = TensorBuffer.createFixedSize(new int[]{1, 416, 416, 3}, DataType.FLOAT32);
            feature.loadBuffer(tImage.getBuffer());

Line 44 -->            Model.Outputs outputs = model.process(feature);
```

**Comment by abattery** [comment]
We recommend using the same TF versions for both conversion and android applications. There is possibility that the model is not well converted with the old TF version. Could you try conversion with tf-nightly version and try again at the android application?

**Comment by abattery** [comment]
@Ean244 could you share how to reproduce the conversion? If possible, sharing a form of the gist will be very helpful.
