### ISSUE TITLE
[RNN] input->type != output->type (UINT8 != FLOAT32)Node number 18 (TANH) failed to prepare

### ISSUE THREAD

**Issue by fvollmer** [tensorflow/tensorflow#48282]
### 1. System information

- Windows 10
- pip install tf-nightly
- 2.6.0.dev20210330

### 2. Code
The following code converts and quantizes a stateless lstm layer with additional inputs and outputs to handle the state by the user program. This was suggested at https://www.tensorflow.org/lite/convert/rnn
> It is still possible to model a stateful Keras LSTM layer using the underlying stateless Keras LSTM layer and managing the state explicitly in the user program. Such a TensorFlow program can still be converted to TensorFlow Lite using the feature being described here.

```
from tensorflow import keras
from tensorflow.keras import layers
import tensorflow as tf
import numpy as np

rng = np.random.default_rng()


def representative_dataset():
    yield [rng.random((1, 1024), dtype=np.float32),
           rng.random((1, 1, 1024), dtype=np.float32),
           rng.random((1, 1024), dtype=np.float32)]


def create_keras_model(keras_file_name, stateful=True):
    input = keras.Input(shape=(1, 1024,), name="input")
    hidden_state = keras.Input(shape=(1024,), name="lstm_hidden_state")
    cell_state = keras.Input(shape=(1024,), name="lstm_cell_state")
    output, new_hidden_state, new_cell_state = layers.LSTM(units=1024, return_sequences=True, unroll=True,
                                                           return_state=True,
                                                           name="lstm")(input, initial_state=[hidden_state, cell_state])
    model = keras.Model([input, hidden_state, cell_state],
                        [output, new_hidden_state, new_cell_state])
    model.summary()
    model.compile()
    model.save(keras_file_name)


def convert_to_tflite(keras_file_name, tflite_filename):
    converter = tf.lite.TFLiteConverter.from_saved_model(keras_file_name)
    #converter.experimental_new_converter = True
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_dataset
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.target_spec.supported_types = [tf.int8]
    converter.inference_input_type = tf.uint8
    converter.inference_output_type = tf.uint8
    tflite_model = converter.convert()
    with open(tflite_filename, 'wb') as f:
        f.write(tflite_model)


def main():
    keras_file_name = "example_model"
    tflite_filename = "example_model.tflite"
    create_keras_model(keras_file_name)
    convert_to_tflite(keras_file_name, tflite_filename)

    # run model with random input
    interpreter = tf.lite.Interpreter(tflite_filename)
    interpreter.allocate_tensors()
    for input_detail in interpreter.get_input_details():
        scale, zero_point = input_detail['quantization']
        input_tensor = rng.random(input_detail["shape"], dtype=np.float32)
        input_tensor = input_detail["dtype"](input_tensor / scale + zero_point)
        interpreter.set_tensor(input_detail["index"], input_tensor)

    interpreter.invoke()


if __name__ == '__main__':
    main()
```

![grafik](https://user-images.githubusercontent.com/16699443/113432571-e7be5c80-93dd-11eb-8bff-629fcaf1b275.png)

### 3. Failure after conversion

Running the model after conversion fails with:
```
Traceback (most recent call last):
  File "C:/Users/user/PycharmProjects/Project/LSTM_tflite_playground.py", line 62, in <module>
    main()
  File "C:/Users/user/PycharmProjects/Project/LSTM_tflite_playground.py", line 51, in main
    interpreter.allocate_tensors()
  File "C:\Users\user\PycharmProjects\Project\venv\lib\site-packages\tensorflow\lite\python\interpreter.py", line 408, in allocate_tensors
    return self._interpreter.AllocateTensors()
RuntimeError: tensorflow/lite/kernels/activations.cc:393 input->type != output->type (UINT8 != FLOAT32)Node number 18 (TANH) failed to prepare.
```
A normal stateless model without the additional in and outputs runs fine. Is there any workaround?

**Comment by abattery** [comment]
I confirmed that putting `converter.experimental_new_quantizer = False` will resolve the problem.

**Comment by fvollmer** [comment]
Thanks! The only problem is that without the new quantizer there isn't support for ops like "ELU". So using the old quantizer is only a workaround for the toy example above. Any other ideas for a workaround to archive a quantized stateful lstm with tflite?

Example from above with an additional elu activation layer:
```python
from tensorflow import keras
from tensorflow.keras import layers
import tensorflow as tf
import numpy as np
from tensorflow.keras import activations

rng = np.random.default_rng()


def representative_dataset():
    yield [rng.random((1, 1024), dtype=np.float32),
           rng.random((1, 1, 1024), dtype=np.float32),
           rng.random((1, 1024), dtype=np.float32)]


def create_keras_model(keras_file_name, stateful=True):
    input = keras.Input(shape=(1, 1024,), name="input")
    hidden_state = keras.Input(shape=(1024,), name="lstm_hidden_state")
    cell_state = keras.Input(shape=(1024,), name="lstm_cell_state")
    lstm_output, new_hidden_state, new_cell_state = layers.LSTM(units=1024, return_sequences=True, unroll=True,
                                                           return_state=True,
                                                           name="lstm")(input, initial_state=[hidden_state, cell_state])
    output = layers.Activation(activations.elu)(lstm_output)
    model = keras.Model([input, hidden_state, cell_state],
                        [output, new_hidden_state, new_cell_state])
    model.summary()
    model.compile()
    model.save(keras_file_name)
    keras.utils.plot_model(model, to_file='example.png', show_shapes=True)


def convert_to_tflite(keras_file_name, tflite_filename):
    converter = tf.lite.TFLiteConverter.from_saved_model(keras_file_name)
    converter.experimental_new_quantizer = False  # https://github.com/tensorflow/tensorflow/issues/48282
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_dataset
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.target_spec.supported_types = [tf.int8]
    converter.inference_input_type = tf.uint8
    converter.inference_output_type = tf.uint8
    tflite_model = converter.convert()
    with open(tflite_filename, 'wb') as f:
        f.write(tflite_model)


def main():
    keras_file_name = "example_model"
    tflite_filename = "example_model.tflite"
    create_keras_model(keras_file_name)
    convert_to_tflite(keras_file_name, tflite_filename)

    # run model with random input
    interpreter = tf.lite.Interpreter(tflite_filename)
    interpreter.allocate_tensors()
    for input_detail in interpreter.get_input_details():
        scale, zero_point = input_detail['quantization']
        input_tensor = rng.random(input_detail["shape"], dtype=np.float32)
        input_tensor = input_detail["dtype"](input_tensor / scale + zero_point)
        interpreter.set_tensor(input_detail["index"], input_tensor)

    interpreter.invoke()


if __name__ == '__main__':
    main()
```

**Comment by liufengdb** [comment]
fvollmer@, can you confirmed that the issue is resolved with tf-nightly?

**Comment by fvollmer** [comment]
@liufengdb Seems to work fine. I can't reproduce the problem anymore. Thanks!

**Comment by jakobwowy** [comment]
@fvollmer Great example how to handle the state by the user program. Do you have a hint how to handle the states of multiple LSTM layers?
