### ISSUE TITLE
TFLite: Manipulating the hardware accelerators is not allowed in the Task library currently. Only CPU is allowed

### ISSUE THREAD

**Issue by ekremcet** [tensorflow/tensorflow#48306]
Hello, 

I am trying to run the image classification code [here](https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/android). It works fine until I switch to the NNAPI option in the device. When I do that it throws the following error:
```
2021-04-05 15:26:22.086 23313-23349/org.tensorflow.lite.examples.classification E/tensorflow: ClassifierActivity: Failed to create classifier.
    java.lang.IllegalArgumentException: Manipulating the hardware accelerators is not allowed in the Task library currently. Only CPU is allowed.
        at org.tensorflow.lite.examples.classification.tflite.Classifier.<init>(Classifier.java:169)
        at org.tensorflow.lite.examples.classification.tflite.ClassifierQuantizedEfficientNet.<init>(ClassifierQuantizedEfficientNet.java:33)
        at org.tensorflow.lite.examples.classification.tflite.Classifier.create(Classifier.java:90)
        at org.tensorflow.lite.examples.classification.ClassifierActivity.recreateClassifier(ClassifierActivity.java:147)
        at org.tensorflow.lite.examples.classification.ClassifierActivity.lambda$onInferenceConfigurationChanged$0$ClassifierActivity(ClassifierActivity.java:126)
        at org.tensorflow.lite.examples.classification.-$$Lambda$ClassifierActivity$83lGy2TUjuj0M5n4BhMB9qlLgSY.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:233)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

I am using Xiaomi Mi 11 as the test device (Snapdragon 888, Adreno 660) with the latest updates. Could you please help me with this issue?

Thanks!

**Comment by abattery** [comment]
@lintian06 could you triage this issue?

**Comment by lu-wang-g** [comment]
The Java API doesn't support acceleration yet, but we are working actively to enable it. Please stay tuned.

**Comment by alexanderfrey** [comment]
Hi, I'm also working on using a object detection on the snapdragon 888. Have you already been able to make use of the hexagon dsp ?  Maybe via the hexagon 1.21 delegate or nnapi ?

**Comment by lu-wang-g** [comment]
Through Task library, it's not supported yet. But you can leverage the TFLite Interpreter API. See the example [here](https://github.com/tensorflow/examples/blob/master/lite/examples/object_detection/android/lib_interpreter/src/main/java/org/tensorflow/lite/examples/detection/tflite/TFLiteObjectDetectionAPIModel.java). Follow the instruction [here](https://www.tensorflow.org/lite/performance/hexagon_delegate#hexagon_delegate_java_api) to add the hexagon delegate.

**Comment by alexanderfrey** [comment]
Thanks for your answer. So if I understand correctly you are using the hexagon 1.21 delegate example from tensorflow ? For me it keeps telling me about incompatibility issues with the version so I thought it might be because of the fact that snapdragon 888 is not yet supported ?!

**Comment by lu-wang-g** [comment]
@karimnosseir Can you please help to take a look at this issue? Thanks!

**Comment by karimnosseir** [comment]
This is similar to https://github.com/tensorflow/tensorflow/issues/47246
888 is a new hardware and different that doesn't work with Hexagon NN.

**Comment by karimnosseir** [comment]
@lu-wang-g  do you want to keep the issue for Java API acceleration support.

**Comment by lu-wang-g** [comment]
Thanks @karimnosseir! I'll close the issue for now. Stay tuned for the upcoming updates about the Java acceleration support. Feel free to reopen this issue for any questions.
