### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by redmlr** [tensorflow/tensorflow#48368]
Hello,

I'm trying to train a model using the `model.fit()` function, but it keeps throwing me an error which I cannot resolve. 
The error is:
```
Traceback (most recent call last):
  File "train.py", line 355, in <module>
    main()
  File "/Users/pietmuller/Dokumente/code/AI/E2EASRS/tensor_venv/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 620, in wrapper
    return func(*args, **kwargs)
  File "train.py", line 338, in main
    history = model.fit(
  File "/Users/pietmuller/Dokumente/code/AI/E2EASRS/tensor_venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
  File "/Users/pietmuller/Dokumente/code/AI/E2EASRS/tensor_venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/Users/pietmuller/Dokumente/code/AI/E2EASRS/tensor_venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 871, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/Users/pietmuller/Dokumente/code/AI/E2EASRS/tensor_venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 725, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/Users/pietmuller/Dokumente/code/AI/E2EASRS/tensor_venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2969, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/Users/pietmuller/Dokumente/code/AI/E2EASRS/tensor_venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/Users/pietmuller/Dokumente/code/AI/E2EASRS/tensor_venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3196, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/Users/pietmuller/Dokumente/code/AI/E2EASRS/tensor_venv/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/Users/pietmuller/Dokumente/code/AI/E2EASRS/tensor_venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 634, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/Users/pietmuller/Dokumente/code/AI/E2EASRS/tensor_venv/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 977, in wrapper
    raise e.ag_error_metadata.to_exception(e)
AttributeError: in user code:

    /Users/pietmuller/Dokumente/code/AI/E2EASRS/tensor_venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:805 train_function  *
        return step_function(self, iterator)
    /Users/pietmuller/Dokumente/code/AI/E2EASRS/tensor_venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:795 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /Users/pietmuller/Dokumente/code/AI/E2EASRS/tensor_venv/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:1259 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /Users/pietmuller/Dokumente/code/AI/E2EASRS/tensor_venv/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:2730 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /Users/pietmuller/Dokumente/code/AI/E2EASRS/tensor_venv/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:3417 _call_for_each_replica
        return fn(*args, **kwargs)
    /Users/pietmuller/Dokumente/code/AI/E2EASRS/tensor_venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:788 run_step  **
        outputs = model.train_step(data)
    /Users/pietmuller/Dokumente/code/AI/E2EASRS/tensor_venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:758 train_step
        self.compiled_metrics.update_state(y, y_pred, sample_weight)
    /Users/pietmuller/Dokumente/code/AI/E2EASRS/tensor_venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/compile_utils.py:387 update_state
        self.build(y_pred, y_true)
    /Users/pietmuller/Dokumente/code/AI/E2EASRS/tensor_venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/compile_utils.py:317 build
        self._metrics = nest.map_structure_up_to(y_pred, self._get_metric_objects,
    /Users/pietmuller/Dokumente/code/AI/E2EASRS/tensor_venv/lib/python3.8/site-packages/tensorflow/python/util/nest.py:1159 map_structure_up_to
        return map_structure_with_tuple_paths_up_to(
    /Users/pietmuller/Dokumente/code/AI/E2EASRS/tensor_venv/lib/python3.8/site-packages/tensorflow/python/util/nest.py:1257 map_structure_with_tuple_paths_up_to
        results = [
    /Users/pietmuller/Dokumente/code/AI/E2EASRS/tensor_venv/lib/python3.8/site-packages/tensorflow/python/util/nest.py:1258 <listcomp>
        func(*args, **kwargs) for args in zip(flat_path_gen, *flat_value_gen)
    /Users/pietmuller/Dokumente/code/AI/E2EASRS/tensor_venv/lib/python3.8/site-packages/tensorflow/python/util/nest.py:1161 <lambda>
        lambda _, *values: func(*values),  # Discards the path arg.
    /Users/pietmuller/Dokumente/code/AI/E2EASRS/tensor_venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/compile_utils.py:418 _get_metric_objects
        return [self._get_metric_object(m, y_t, y_p) for m in metrics]
    /Users/pietmuller/Dokumente/code/AI/E2EASRS/tensor_venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/compile_utils.py:418 <listcomp>
        return [self._get_metric_object(m, y_t, y_p) for m in metrics]
    /Users/pietmuller/Dokumente/code/AI/E2EASRS/tensor_venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/compile_utils.py:439 _get_metric_object
        y_t_rank = len(y_t.shape.as_list())

    AttributeError: 'NoneType' object has no attribute 'shape'
```

This is my `.fit()` function:

```
history = model.fit(
        train_ds, 
        validation_data=val_ds, 
        epochs=EPOCHS, 
        batch_size=BATCH_SIZE,
        callbacks=[earlyStopping, modelCheckpoint]
    )
```

My train dataset is a `tf.data.Dataset` and is of type: `<class 'tensorflow.python.data.ops.dataset_ops.BatchDataset'>` 

The model is building and compiling fine, but training...

When I try to look at the dataset using:

```
for batch in train_ds.take(1):
    input_shape = batch["spectrogram"].shape
    label_shape = batch["label"].shape
    print('Input shape:', input_shape)
```

It outputs the shape just fine.

I'm looking forward for help:)

**Comment by amahendrakar** [comment]
@redmlr,
In order to reproduce the issue reported here, could you please provide the TensorFlow version, the complete code and the dataset you are using. Thanks!

**Comment by redmlr** [comment]
All you need is in this simple `colab.https://colab.research.google.com/drive/1MuPS8uruRzWo_tEFJjgVPUOD8NqGPrQG?usp=sharing`

**Comment by amahendrakar** [comment]
@redmlr,
Thank you for the update.

However, I do not have access to the Colab notebook. Could you please provide the required permissions to view the file?

**Comment by redmlr** [comment]
@amahendrakar it should work now:) https://colab.research.google.com/drive/1MuPS8uruRzWo_tEFJjgVPUOD8NqGPrQG?usp=sharing

**Comment by amahendrakar** [comment]
@redmlr,
Thank you for the gist. 

In the given code snippet, the `mod_func` function returns a Python dictionary. And since Python dictionaries do not have the `shape` attribute the `AttributeError: 'dict' object has no attribute 'shape'` error is thrown. 

If you require the `shape` attribute, I'd suggest you to use an alternative data structure. Thanks!

**Comment by amahendrakar** [comment]
@redmlr,
In this case, you can either return the strings as a Tensor or use the `len()` function instead of shape for the dictionary. 

Please check [this gist](https://colab.research.google.com/gist/amahendrakar/9e01e74b727fe4b5041982bdfdbfff77/48368.ipynb#scrollTo=yDEvUrPfqfif&line=2&uniqifier=1) for reference. Thanks!

**Comment by redmlr** [comment]
@amahendrakar Well, unfortunately it's not that simple. The error occurred in the `model.fit()` function where I don't have any control over using `len()` or `.shape`.

**Comment by amahendrakar** [comment]
@redmlr,
Could you please provide the complete code snippet along with the `model.fit()` function, so that we can look into this? Thanks!

**Comment by redmlr** [comment]
This is the main function: 
```
def main():
    train_list, validation_list, test_list = load_json_into_lists(TRAIN_DS_PATH, TEST_DS_PATH)
    train_ds = preprocess_dataset(train_list)
    val_ds = preprocess_dataset(validation_list)
    test_ds = preprocess_dataset(test_list)

    for spectrogram, label in train_ds.take(1):
        input_shape = spectrogram.shape

    train_ds = train_ds.cache().prefetch(AUTOTUNE)
    val_ds = val_ds.cache().prefetch(AUTOTUNE)

    model = build_model(input_shape)
    model.summary()

    earlyStopping = Keras.callbacks.EarlyStopping(monitor="val_loss", mode="min", patience=10, restore_best_weights=True)

    train_ds = train_ds.batch(BATCH_SIZE)
    val_ds = val_ds.batch(BATCH_SIZE)

    print(type(train_ds))

    history = model.fit(
        train_ds, 
        validation_data=val_ds, 
        epochs=EPOCHS, 
        callbacks=[earlyStopping]
    )

```

```
def preprocess_dataset(files):

    # Creating a new list, just including the filenames
    filenames_train_list = [sample[0] for sample in files]

    # Converting the filenames into tensors
    filename_tensors = string_to_tensor(tf.constant(filenames_train_list))

    # Creating a tensorflow dataset containing audio filenames
    files_ds = tf.data.Dataset.from_tensor_slices(filename_tensors)

    # Conversion into a waveform dataset (filenames converted to waveforms)
    waveform_ds = files_ds.map(lambda file_path: tf.py_function(get_waveform_and_label, [file_path], [tf.float32, tf.string]), num_parallel_calls=AUTOTUNE) 

    # Next Conversion: waveforms into spectrograms
    spectrogram_ds = waveform_ds.map(
        get_spectrogram_and_label, num_parallel_calls=AUTOTUNE
    )

    return spectrogram_ds 
```

**Comment by amahendrakar** [comment]
@redmlr,
You have defined the functions but are not calling them anywhere. On calling the main() function, I am facing an error stating `NameError: name 'load_json_into_lists' is not defined`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/3ebad085a7493cce8c3d154feb0d8de6/48368.ipynb#scrollTo=jDObUjkfolzd).


Could you please provide the complete code along with the dataset, so that we can reproduce the issue. Alternatively, you can run the code on [Google Colab](https://colab.research.google.com/) and share the notebook with us. Thanks!

**Comment by redmlr** [comment]
@amahendrakar Sorry! I updated the gist with some code and comment instructions now.

**Comment by amahendrakar** [comment]
@redmlr,
Looks like the changes were not saved in the gist. I still see the same code. 

![Screenshot 2021-04-22 9 15 51 PM](https://user-images.githubusercontent.com/57165142/115745681-48bfcb80-a3b1-11eb-9d47-412064136899.png)

Could you please save the changes and share the updated link. You can also save the gist using the following method 'File' -> 'Save a copy as Github Gist', and share the link of the new window. Thanks!
