### ISSUE TITLE
tf.switch_case not working with KerasTensor

### ISSUE THREAD

**Issue by Vaunorage** [tensorflow/tensorflow#48375]
**System information**
- Documentation exemple : https://www.tensorflow.org/api_docs/python/tf/switch_case
- Windows 10
- TensorFlow version 2
- Python version: 3.7

**Current behavior**

```
import tensorflow as tf
from tensorflow.keras.layers import Input
def f1(): return tf.constant(17)
def f2(): return tf.constant(31)
def f3(): return tf.constant(-1)
t_input = Input(shape=(1,), name="t_input")
r = tf.switch_case(t_input, branch_fns={0: f1, 1: f2}, default=f3)
```
```
Traceback (most recent call last):
  File "C:\Users\gen06917\PycharmProjects\BaysianTarnet\.venv\lib\site-packages\IPython\core\interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-bd285228541c>", line 5, in <module>
    r = tf.switch_case(t_input, branch_fns={0: f1, 1: f2}, default=f3)
  File "C:\Users\gen06917\PycharmProjects\BaysianTarnet\.venv\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 3616, in switch_case
    return _indexed_case_helper(branch_fns, default, branch_index, name)
  File "C:\Users\gen06917\PycharmProjects\BaysianTarnet\.venv\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 3315, in _indexed_case_helper
    branch_fns, default, branch_index)
  File "C:\Users\gen06917\PycharmProjects\BaysianTarnet\.venv\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 3249, in _indexed_case_verify_and_canonicalize_args
    type(branch_index)))
TypeError: branch_index must a Tensor, got <class 'tensorflow.python.keras.engine.keras_tensor.KerasTensor'>
```

**Comment by amahendrakar** [comment]
@Vaunorage,
As per the [documentation](https://www.tensorflow.org/api_docs/python/tf/switch_case), **branch_index** should be an **int Tensor**.

With an int Tensor passed as the argument, I was able to run the code without any issues. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/2d3343ae70db798f9d85b7c3a35aaa80/48375.ipynb). Thanks!

**Comment by Vaunorage** [comment]
Thank you,

However, I need to use it with an input which is a KerasTensor ? How this would work ? 
Otherwise, I can use tf.case but it is less practical ..

**Comment by Vaunorage** [comment]
Hi, for those who wonder how to train multiple branches of a neural network with Keras. just make a function yourself like so :

https://stackoverflow.com/questions/67065868/training-different-branches-of-model-network-with-tf-switch-case/67067644#67067644
