### ISSUE TITLE
Using same group key in CollectiveBcastSend/RecvV2 and CollectiveReduceV2 raises an error

### ISSUE THREAD

**Issue by ktaebum** [tensorflow/tensorflow#48372]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.12.1-54425-g18a6a9fc87f 2.6.0-dev20210407
- Python version: 3.8.8
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: 11.0.3 / 7.6.5
- GPU model and memory: TITAN Xp (12GB)

**Describe the current behavior**

If I use 2 consecutive CollectiveCommunication Operations (CollectiveBcastSend / Recv V2 => CollectiveReduceV2) on the same devices, the program is aborted by InternalError

**Describe the expected behavior**

The program should not be aborted and should execute two collective operations

**Standalone code to reproduce the issue**

```
import tensorflow as tf

from tensorflow.core.protobuf import config_pb2
from tensorflow.python.ops import collective_ops

def main():
  g = tf.Graph()
  with g.as_default():
    c = tf.random.normal(shape=(10, 20))
    with tf.device("/GPU:0"):
      b0 = collective_ops.broadcast_send_v2(c, group_size=2, group_key=1, instance_key=1)
      r0 = collective_ops.all_reduce_v2(b0, group_size=2, group_key=1, instance_key=2)
    with tf.device("/GPU:1"):
      b1 = collective_ops.broadcast_recv_v2(c.shape, c.dtype, group_size=2, group_key=1, instance_key=1)
      r1 = collective_ops.all_reduce_v2(b1, group_size=2, group_key=1, instance_key=2)

    with tf.compat.v1.Session(graph=g) as sess:
        options = config_pb2.RunOptions()
        options.experimental.collective_graph_key = 1
        sess.run([r0, r1], options=options)

if __name__ == "__main__":
  main()
```

**Other info / logs** Include any logs or source code that would be helpful to

The error logs are
```
Traceback (most recent call last):
  File "/home/ktaebum/Program/anaconda3/envs/temp/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1375, in _do_call
    return fn(*args)
  File "/home/ktaebum/Program/anaconda3/envs/temp/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1359, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "/home/ktaebum/Program/anaconda3/envs/temp/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1451, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.InternalError: [_Derived_]Collective ops is aborted by: Collective Op CollectiveReduceV2: ReduceV2(Add,Id) is assigned to device /job:localhost/replica:0/task:0/device:GPU:0 with type GPU and group_key 1 but that group has type DEFAULT
The error could be from a previous operation. Restart your program to reset.
         [[{{node CollectiveReduceV2_1}}]]
         [[CollectiveReduceV2/_1]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "collective.py", line 31, in <module>
    main()
  File "collective.py", line 28, in main
    print(sess.run([r0, r1], options=options))
  File "/home/ktaebum/Program/anaconda3/envs/temp/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 967, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "/home/ktaebum/Program/anaconda3/envs/temp/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1190, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "/home/ktaebum/Program/anaconda3/envs/temp/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1368, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "/home/ktaebum/Program/anaconda3/envs/temp/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: [_Derived_]Collective ops is aborted by: Collective Op CollectiveReduceV2: ReduceV2(Add,Id) is assigned to device /job:localhost/replica:0/task:0/device:GPU:0 with type GPU and group_key 1 but that group has type DEFAULT
The error could be from a previous operation. Restart your program to reset.
         [[node CollectiveReduceV2_1 (defined at collective.py:21) ]]
         [[CollectiveReduceV2/_1]]

Errors may have originated from an input operation.
Input Source operations connected to node CollectiveReduceV2_1:
 CollectiveBcastRecvV2 (defined at collective.py:20)

Original stack trace for 'CollectiveReduceV2_1':
  File "collective.py", line 31, in <module>
    main()
  File "collective.py", line 21, in main
    r1 = collective_ops.all_reduce_v2(b1, 2, 1, 2)
  File "/home/ktaebum/Program/anaconda3/envs/temp/lib/python3.8/site-packages/tensorflow/python/ops/collective_ops.py", line 111, in all_reduce_v2
    return gen_collective_ops.collective_reduce_v2(
  File "/home/ktaebum/Program/anaconda3/envs/temp/lib/python3.8/site-packages/tensorflow/python/ops/gen_collective_ops.py", line 779, in collective_reduce_v2
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "/home/ktaebum/Program/anaconda3/envs/temp/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py", line 748, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "/home/ktaebum/Program/anaconda3/envs/temp/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3561, in _create_op_internal
    ret = Operation(
  File "/home/ktaebum/Program/anaconda3/envs/temp/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 2049, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)
```

Interestingly, if I give a different `group_key` to collective reduce as
```
import tensorflow as tf

from tensorflow.core.protobuf import config_pb2
from tensorflow.python.ops import collective_ops

def main():
  g = tf.Graph()
  with g.as_default():
    c = tf.random.normal(shape=(10, 20))
    with tf.device("/GPU:0"):
      b0 = collective_ops.broadcast_send_v2(c, group_size=2, group_key=1, instance_key=1)
      r0 = collective_ops.all_reduce_v2(b0, group_size=2, group_key=2, instance_key=2)
    with tf.device("/GPU:1"):
      b1 = collective_ops.broadcast_recv_v2(c.shape, c.dtype, group_size=2, group_key=1, instance_key=1)
      r1 = collective_ops.all_reduce_v2(b1, group_size=2, group_key=2, instance_key=2)

    with tf.compat.v1.Session(graph=g) as sess:
        options = config_pb2.RunOptions()
        options.experimental.collective_graph_key = 1
        sess.run([r0, r1], options=options)

if __name__ == "__main__":
  main()
```
, the program runs without an error.
However, from my understanding, I can use the same `group_key` for different collective operations if the participant devices are same (only `instance_key` should be different) because CollectiveReduce => CollectiveGather works well if I run
```
import tensorflow as tf

from tensorflow.core.protobuf import config_pb2
from tensorflow.python.ops import collective_ops

def main():
  g = tf.Graph()
  with g.as_default():
    c = tf.random.normal(shape=(10, 20))
    with tf.device("/GPU:0"):
      r0 = collective_ops.all_reduce_v2(c, group_size=2, group_key=2, instance_key=2)
      r0 = collective_ops.all_gather_v2(r0, group_size=2, group_key=2, instance_key=3)
    with tf.device("/GPU:1"):
      r1 = collective_ops.all_reduce_v2(c, group_size=2, group_key=2, instance_key=2)
      r1 = collective_ops.all_gather_v2(r1, group_size=2, group_key=2, instance_key=3)

    with tf.compat.v1.Session(graph=g) as sess:
        options = config_pb2.RunOptions()
        options.experimental.collective_graph_key = 1
        sess.run([r0, r1], options=options)

if __name__ == "__main__":
  main()
```

**Comment by amahendrakar** [comment]
@ymodak,
On running the code with TF v2.4.1, I am facing an error stating `AttributeError: module 'tensorflow.python.ops.collective_ops' has no attribute 'broadcast_send_v2'`

Whereas with TF v2.5.0rc0 and TF-nightly, I was able to reproduce the issue. Please check the attached screenshot for reference. 
![Screenshot 2021-04-10 12 13 43 AM](https://user-images.githubusercontent.com/57165142/114226968-f97da200-9991-11eb-97ec-9d779907ed95.png)
Thanks!

**Comment by sushreebarsa** [comment]
@ktaebum I tried to replicate the issue and faced a different error in latest TF version using colab. Could you please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/4ec7ff8660b3b06f48c62b4cc83027c1/48372.ipynb) and confirm the same. Thank you!
