### ISSUE TITLE
tf.switch_case not working

### ISSUE THREAD

**Issue by Vaunorage** [tensorflow/tensorflow#48373]
**System information**
- Documentation exemple : https://www.tensorflow.org/api_docs/python/tf/switch_case
- Windows 10
- TensorFlow version 2
- Python version: 3.7

**Current behavior**

```
def f1(): return tf.constant(17)
def f2(): return tf.constant(31)
def f3(): return tf.constant(-1)
r = tf.switch_case(tf.convert_to_tensor([1, 0]), branch_fns={0: f1, 1: f2}, default=f3)
```
```
Traceback (most recent call last):
  File "C:\Users\gen06917\PycharmProjects\BaysianTarnet\.venv\lib\site-packages\IPython\core\interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-04e5a20bbcd0>", line 4, in <module>
    r = tf.switch_case(tf.convert_to_tensor([1, 0]), branch_fns={0: f1, 1: f2}, default=f3)
  File "C:\Users\gen06917\PycharmProjects\BaysianTarnet\.venv\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 3616, in switch_case
    return _indexed_case_helper(branch_fns, default, branch_index, name)
  File "C:\Users\gen06917\PycharmProjects\BaysianTarnet\.venv\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 3321, in _indexed_case_helper
    len(branch_fns) - 1, branch_index)
  File "C:\Users\gen06917\PycharmProjects\BaysianTarnet\.venv\lib\site-packages\tensorflow\python\util\dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\gen06917\PycharmProjects\BaysianTarnet\.venv\lib\site-packages\tensorflow\python\ops\array_ops.py", line 4483, in where
    return gen_math_ops.select(condition=condition, x=x, y=y, name=name)
  File "C:\Users\gen06917\PycharmProjects\BaysianTarnet\.venv\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 8675, in select
    _ops.raise_from_not_ok_status(e, name)
  File "C:\Users\gen06917\PycharmProjects\BaysianTarnet\.venv\lib\site-packages\tensorflow\python\framework\ops.py", line 6862, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: 'then' must be at least a vector, but saw shape: [] [Op:Select]
```

**Comment by tilakrayal** [comment]
@Vaunorage,
Looks like this is a duplicate of issue [#48375](https://github.com/tensorflow/tensorflow/issues/48375). 

Can we close this issue since it is already being tracked there? Thanks!

**Comment by Vaunorage** [comment]
It is the same function in both cases but not the same error message
