### ISSUE TITLE
AttributeError during pip install when building from source

### ISSUE THREAD

**Issue by oxrider** [tensorflow/tensorflow#4838]
I was trying to build TensorFlow from source, and all went well until I was in the last step 
`sudo pip install /tmp/tensorflow-pkg/tensorflow-0.11.0rc0-py2-none-any.whl
`
it crashes with this error message: 

> Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 317, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 448, in _prepare_file
    req_to_install, finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 387, in _check_skip_installed
    req_to_install.check_if_exists()
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1011, in check_if_exists
    self.req.project_name
AttributeError: 'Requirement' object has no attribute 'project_name'

I did some search online and found that this may be due to an upstream bug and it's been happening in other projects too. Is there anyway to work around this issue? I currently can't use a pre-compiled whl because I'm using gtx1080 and CUDA8, i think the precompiled whl only supports 7.5

I'm using Ubuntu 16.04, python 2.7, pip 8.1.1

**Comment by oxrider** [comment]
It turns out all I had to do was to update pip to latest outside virtualenv.
