### ISSUE TITLE
tensorRT does not support defining OP.

### ISSUE THREAD

**Issue by Mr-Nineteen** [tensorflow/tensorflow#48388]
1. Use TensorFlow package: TFRA(https://github.com/tensorflow/recommenders-addons)
2. After saving the model, use tensorRT for model conversion:

TFRA code:
```
deep_dynamic_variables = dynamic_embedding.get_variable(
        name="deep_dynamic_embeddings",
        initializer=initializer,
        dim=embedding_size,
        devices=ps_list,
        trainable=is_training,
        partitioner=addone_partition_fn,
        checkpoint=True
    )
```

tensorRT conversion code:
```
import tensorflow as tf
import tensorflow_recommenders_addons as tfra
from tensorflow.python.compiler.tensorrt import trt_convert as trt

path = 'models/de'
converter = trt.TrtGraphConverterV2(input_saved_model_dir=path)
converter.convert()

converted_model_path = 'models/c'
converter.save(converted_model_path)
```
3. Error message:
KeyError: "The name 'deep_dynamic_embeddings' refers to an Operation not in the graph."

**Comment by tilakrayal** [comment]
@Mr-Nineteen ,

In order to expedite the trouble-shooting process, could you please provide the following information
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
TensorFlow installed from (source or binary):
TensorFlow version:
Python version:
Installed using virtualenv? pip? conda?:
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory:
 
and the the exact sequence of commands / steps that you executed before running into the problem


Thanks!

**Comment by Mr-Nineteen** [comment]
@tilakrayal 

The verification is the fusion of TFRA and TRT, without using the GPU environment.

conda env：

1. python version : 3
2. TF related installation library:
```
tensorflow                     2.4.1
tensorflow-datasets            4.2.0
tensorflow-estimator           2.4.0
tensorflow-metadata            0.29.0
tensorflow-recommenders-addons 0.1.0
```
3. Test model address: https://github.com/Mr-Nineteen/models/blob/main/1617949817.zip
4. test code：
```
import tensorflow as tf
import tensorflow_recommenders_addons as tfra
from tensorflow.python.compiler.tensorrt import trt_convert as trt

path = '1617949817'
converter = trt.TrtGraphConverterV2(input_saved_model_dir=path)
converter.convert()

converted_model_path = 'c'
converter.save(converted_model_path)
```
5. Error message:
```
Traceback (most recent call last):
  File "/Users/dxwang/repo/pycharm-repo/tensorflow-2.0-demo/com/opensource/demo/tftrt/trtconvert-yz.py", line 8, in <module>
    converter.convert()
  File "/Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow/python/compiler/tensorrt/trt_convert.py", line 1094, in convert
    self._input_saved_model_tags)
  File "/Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py", line 859, in load
    return load_internal(export_dir, tags, options)["root"]
  File "/Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py", line 909, in load_internal
    root = load_v1_in_v2.load(export_dir, tags)
  File "/Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow/python/saved_model/load_v1_in_v2.py", line 279, in load
    return loader.load(tags=tags)
  File "/Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow/python/saved_model/load_v1_in_v2.py", line 225, in load
    signature=[])
  File "/Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow/python/eager/wrap_function.py", line 628, in wrap_function
    collections={}),
  File "/Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow/python/eager/wrap_function.py", line 87, in __call__
    return self.call_with_variable_creator_scope(self._fn)(*args, **kwargs)
  File "/Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow/python/eager/wrap_function.py", line 93, in wrapped
    return fn(*args, **kwargs)
  File "/Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow/python/saved_model/load_v1_in_v2.py", line 93, in load_graph
    meta_graph_def)
  File "/Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1485, in _import_meta_graph_with_return_elements
    **kwargs))
  File "/Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow/python/framework/meta_graph.py", line 886, in import_scoped_meta_graph_with_return_elements
    ops.prepend_name_scope(value, scope_to_prepend_to_names))
  File "/Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3726, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/Users/dxwang/opt/anaconda3/envs/tfra/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3786, in _as_graph_element_locked
    "graph." % repr(name))
KeyError: "The name 'deep_dynamic_embeddings' refers to an Operation not in the graph."
```

Thanks!

**Comment by amahendrakar** [comment]
@ymodak,
I was able to reproduce the issue with TF v2.4.1, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/1c82bdfec34ba52b3cc064609424fcd1/48388.ipynb#scrollTo=32-gTBbyV99S).

 Whereas with TF v2.5.0rc1 and TF-nightly, the dependency `tensorflow-recommenders-addons` is not compatible. Thanks!

**Comment by ymodak** [comment]
Did you try converting your model using [tf.experimental.tensorrt.Converter()](https://www.tensorflow.org/api_docs/python/tf/experimental/tensorrt/Converter)?

**Comment by Mr-Nineteen** [comment]
@ymodak  it's ok, thx.
