### ISSUE TITLE
ImportError: DLL load failed: No se puede encontrar el módulo especificado.

### ISSUE THREAD

**Issue by Germanferraris** [tensorflow/tensorflow#48409]
**System information**
- OS Platform and Distribution: Windows 10
- TensorFlow installed from :pip install
- TensorFlow version:1.13.1
- Python version:3.5
- Installed using: virtualenv, pip and conda?:
- Bazel version (if compiling from source): none
- CUDA/cuDNN version:10 and 7.4
- GPU model and memory: GF -GTX1070Ti

**PROBLEM**
I am trying to download and use tensorflow-gpu version 1.13.1 and apparently I've done something wrong and I don't really know where. I am using cuda and cudnn versión that are compatible acording to "https://www.tensorflow.org/install/source_windows".

**COMMANDS**
conda create -n tensorflow1 pip python=3.5
pip install --upgrade tensorflow-gpu==1.13.1
python
>>>import tensorflow as tf

**LOG**

Traceback (most recent call last):
  File "D:\Users\germa\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\Users\germa\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\Users\germa\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "D:\Users\germa\anaconda3\envs\tensorflow1\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "D:\Users\germa\anaconda3\envs\tensorflow1\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: No se puede encontrar el módulo especificado.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Users\germa\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "D:\Users\germa\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "D:\Users\germa\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "D:\Users\germa\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\Users\germa\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\Users\germa\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "D:\Users\germa\anaconda3\envs\tensorflow1\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "D:\Users\germa\anaconda3\envs\tensorflow1\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: No se puede encontrar el módulo especificado.

Failed to load the native TensorFlow runtime.

**Comment by tilakrayal** [comment]
@Germanferraris,

TensorFlow **1.x** is not actively supported. Could you please update TensorFlow to the latest stable version **v2.4.1** and check if you are facing the same issue. Thanks!
