### ISSUE TITLE
Cannot build Tensorflow with Cuda

### ISSUE THREAD

**Issue by l1x** [tensorflow/tensorflow#48438]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.5
- Python version: 3.9
- Installed using virtualenv? pip? conda?: venv + pip
- Bazel version (if compiling from source):  3.7.2
- GCC/Compiler version (if compiling from source): gcc version 10.2.1 20210110 (Debian 10.2.1-6)
- CUDA/cuDNN version: 11.2
- GPU model and memory: Tesla T4

**Describe the problem**

```
Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10]: 11.2


Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7]: 8.1.1


Please specify the locally installed NCCL version you want to use. [Leave empty to use http://github.com/nvidia/nccl]:


Please specify the comma-separated list of base paths to look for CUDA libraries and headers. [Leave empty to use the default]: /usr/include/linux/,/home/admin/cuda/include/


Traceback (most recent call last):
  File "/home/admin/tensorflow/third_party/gpus/find_cuda_config.py", line 653, in <module>
    main()
  File "/home/admin/tensorflow/third_party/gpus/find_cuda_config.py", line 645, in main
    for key, value in sorted(find_cuda_config().items()):
  File "/home/admin/tensorflow/third_party/gpus/find_cuda_config.py", line 583, in find_cuda_config
    result.update(_find_cuda_config(cuda_paths, cuda_version))
  File "/home/admin/tensorflow/third_party/gpus/find_cuda_config.py", line 255, in _find_cuda_config
    cuda_header_path, header_version = _find_header(base_paths, "cuda.h",
  File "/home/admin/tensorflow/third_party/gpus/find_cuda_config.py", line 243, in _find_header
    return _find_versioned_file(base_paths, _header_paths(), header_name,
  File "/home/admin/tensorflow/third_party/gpus/find_cuda_config.py", line 233, in _find_versioned_file
    actual_version = get_version(file)
  File "/home/admin/tensorflow/third_party/gpus/find_cuda_config.py", line 250, in get_header_version
    version = int(_get_header_version(path, "CUDA_VERSION"))
ValueError: invalid literal for int() with base 10: ''
Asking for detailed CUDA configuration...
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
(venv) admin@ip-172-30-0-223:~/tensorflow$ ./configure
You have bazel 3.7.2 installed.
Please specify the location of python. [Default is /home/admin/venv/bin/python3]:


Found possible Python library paths:
  /home/admin/venv/lib/python3.9/site-packages
Please input the desired Python library path to use.  Default is [/home/admin/venv/lib/python3.9/site-packages]

Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Do you wish to build TensorFlow with TensorRT support? [y/N]: n
No TensorRT support will be enabled for TensorFlow.

Could not find any cudnn.h, cudnn_version.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
        'local/cuda/extras/CUPTI/include'
of:
        '/lib'
        '/lib/x86_64-linux-gnu'
        '/lib32'
        '/usr'
        '/usr/lib/x86_64-linux-gnu/libfakeroot'
        '/usr/local/cuda'
        '/usr/local/cuda/targets/x86_64-linux/lib'

Asking for detailed CUDA configuration...

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10]:
```

What is the correct way to specify CUDA + cuDNN versions and paths? Thank you in advance.

**Comment by Saduf2019** [comment]
@l1x 

Can you please follow the below box with the version that you have chosen [11.2 and 8.1] and let us know:
```Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10.0]: 11.0

Please specify the location where CUDA 10.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: /usr/local/cuda-11.0

Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7.0]: 8.0

Please specify the location where cuDNN 7 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: /usr/local/cuda-11.0```
