### ISSUE TITLE
pipenv shell not working

### ISSUE THREAD

**Issue by TaahaKhan** [tensorflow/tensorflow#48461]
I have been trying to call "pipenv shell" but it gives this error:|
                                                                                                 \/

Traceback (most recent call last):
  File "c:\users\yaseen\appdata\local\programs\python\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\yaseen\appdata\local\programs\python\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\yaseen\AppData\Local\Programs\Python\Python38-32\Scripts\pipenv.exe\__main__.py", line 7, in <module>
  File "C:\Users\yaseen\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\yaseen\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\yaseen\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\yaseen\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\yaseen\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\yaseen\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Users\yaseen\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\yaseen\appdata\local\programs\python\python38-32\lib\site-packages\pipenv\cli\command.py", line 428, in shell
    do_shell(
  File "c:\users\yaseen\appdata\local\programs\python\python38-32\lib\site-packages\pipenv\core.py", line 2356, in do_shell
    ensure_project(
  File "c:\users\yaseen\appdata\local\programs\python\python38-32\lib\site-packages\pipenv\core.py", line 576, in ensure_project
    ensure_virtualenv(
  File "c:\users\yaseen\appdata\local\programs\python\python38-32\lib\site-packages\pipenv\core.py", line 498, in ensure_virtualenv
    python = ensure_python(three=three, python=python)
  File "c:\users\yaseen\appdata\local\programs\python\python38-32\lib\site-packages\pipenv\core.py", line 388, in ensure_python
    path_to_python = find_a_system_python(python)
  File "c:\users\yaseen\appdata\local\programs\python\python38-32\lib\site-packages\pipenv\core.py", line 350, in find_a_system_python
    return next(iter(finder.find_all_python_versions()), None)
  File "c:\users\yaseen\appdata\local\programs\python\python38-32\lib\site-packages\pipenv\vendor\pythonfinder\pythonfinder.py", line 328, in find_all_python_versions
    path_list = sorted(versions, key=version_sort, reverse=True)
AttributeError: 'NoneType' object has no attribute 'version_sort'

**Comment by mihaimaruseac** [comment]
This is not a TF error.

**Comment by ymodak** [comment]
@TaahaKhan You may want to post this issue on https://github.com/pypa/pipenv/issues repository if still need help, Since the error you are facing is not TF related.
