### ISSUE TITLE
Select-tf-ops Is Not Working in Android Kitkat 4.4 (API 19)

### ISSUE THREAD

**Issue by malik-anhar** [tensorflow/tensorflow#48532]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Samsung Galaxy Tab 3 (Android KitKat with API 19)
- TensorFlow installed from (source or binary): Installed using pip
- TensorFlow version (use command below): 2.4.3
- Python version: 3.7.6
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: CUDA 10.1 / cuDNN 7.6.4
- GPU model and memory: Tesla T4 16GB

**Describe the problem**
I'm trying to implement YoloV3 on android application based on this [implementation](https://github.com/zzh8829/yolov3-tf2). To convert the model I have to enable the custom operation by adding this snippet code while converting the model
```
converter.target_spec.supported_ops = [
   tf.lite.OpsSet.TFLITE_BUILTINS,
   tf.lite.OpsSet.SELECT_TF_OPS ]
```
the model conversion was successful, and to implement the model on android application, I added the select-tf-ops dependency 
```
implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly'
implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:0.0.0-nightly'
```
The application working correctly on my Android 5.0 (API 21) and Android 10 (API 29), but it gives an error when I run the application on Android 4.4.2 (API 19)
```
04-14 09:18:33.912 8903-8903/com.example.posm W/System.err: java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.
04-14 09:18:33.912 8903-8903/com.example.posm W/System.err: Node number 65 (FlexSize) failed to prepare.
04-14 09:18:33.912 8903-8903/com.example.posm W/System.err: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.
04-14 09:18:33.912 8903-8903/com.example.posm W/System.err: Node number 65 (FlexSize) failed to prepare.
04-14 09:18:33.912 8903-8903/com.example.posm W/System.err: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before infer
04-14 09:18:33.942 8903-8903/com.example.posm W/System.err:     at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
04-14 09:18:33.942 8903-8903/com.example.posm W/System.err:     at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:204)
04-14 09:18:33.942 8903-8903/com.example.posm W/System.err:     at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:378)
04-14 09:18:33.942 8903-8903/com.example.posm W/System.err:     at com.example.posm.yolo.Yolo.predict(Yolo.java:71)
04-14 09:18:33.942 8903-8903/com.example.posm W/System.err:     at com.example.posm.POSM.predict(POSM.java:45)
04-14 09:18:33.942 8903-8903/com.example.posm W/System.err:     at com.example.posm.MainActivity.run_posm(MainActivity.java:110)
04-14 09:18:33.942 8903-8903/com.example.posm W/System.err:     at com.example.posm.MainActivity.lambda$onCreate$1$MainActivity(MainActivity.java:75)
04-14 09:18:33.942 8903-8903/com.example.posm W/System.err:     at com.example.posm.-$$Lambda$MainActivity$w2a9VvlIKLLPHcyHZBUHuFlJhQA.onClick(lambda)
04-14 09:18:33.942 8903-8903/com.example.posm W/System.err:     at android.view.View.performClick(View.java:4640)
04-14 09:18:33.942 8903-8903/com.example.posm W/System.err:     at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1119)
04-14 09:18:33.952 8903-8903/com.example.posm W/System.err:     at android.view.View$PerformClick.run(View.java:19431)
04-14 09:18:33.952 8903-8903/com.example.posm W/System.err:     at android.os.Handler.handleCallback(Handler.java:733)
04-14 09:18:33.952 8903-8903/com.example.posm W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
04-14 09:18:33.952 8903-8903/com.example.posm W/System.err:     at android.os.Looper.loop(Looper.java:146)
04-14 09:18:33.952 8903-8903/com.example.posm W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5598)
04-14 09:18:33.952 8903-8903/com.example.posm W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
04-14 09:18:33.952 8903-8903/com.example.posm W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
04-14 09:18:33.952 8903-8903/com.example.posm W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
04-14 09:18:33.952 8903-8903/com.example.posm W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
04-14 09:18:33.952 8903-8903/com.example.posm W/System.err:     at dalvik.system.NativeStart.main(Native Method)
04-14 09:18:33.952 8903-8903/com.example.posm E/ERROR: Exception java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.
    Node number 65 (FlexSize) failed to prepare.
    
    Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.
    Node number 65 (FlexSize) failed to prepare.
    
    Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before infer
```
Based on my experience, this happened when I run the Android project without select-tf-ops dependency, then after adding the select-tf-ops dependency in my project, the application working correctly in Android 5.0 and Android 10. Is it a compatibility issue with older android APIs?

I have tested by adding the ```FlexDelegate.initTensorFlowForTesting();``` before running the model, and it gives another error
```
04-15 10:53:58.399 358-358/com.example.posm E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.posm, PID: 358
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "wcsnrtombs" referenced by "libtensorflowlite_flex_jni.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:364)
        at java.lang.System.loadLibrary(System.java:526)
        at org.tensorflow.lite.flex.FlexDelegate.<clinit>(FlexDelegate.java:61)
        at com.example.posm.MainActivity.onCreate(MainActivity.java:71)
        at android.app.Activity.performCreate(Activity.java:5459)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2364)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2458)
        at android.app.ActivityThread.access$900(ActivityThread.java:172)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1305)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:146)
        at android.app.ActivityThread.main(ActivityThread.java:5598)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
        at dalvik.system.NativeStart.main(Native Method)
04-15 10:54:01.952 358-358/com.example.posm I/Process: Sending signal. PID: 358 SIG: 9
```

**Describe the current behavior**
The select-tf-ops dependency is not working on Android 4.4.2 

**Describe the expected behavior**
The select-tf-ops dependency working correctly on any devices and the model running well

**Standalone code to reproduce the issue**
Here's the link to the [model](https://drive.google.com/file/d/1yW1KxUZuNIbWXhOzEh3zFBAC5Cb7Ztpa/view?usp=sharing) that cannot be run in Android 4.4.2 even tough I've added the select-tf-ops dependency on it.

**Comment by malik-anhar** [comment]
Hopefully I can get some advice from @thaink

**Comment by abattery** [comment]
@thaink could you take a look?

**Comment by malik-anhar** [comment]
In order to reproduce the issue on the Android, here is my build.gradle file
```
plugins {
    id 'com.android.application'
}
apply plugin: 'kotlin-android'

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.3"

    defaultConfig {
        applicationId "com.example.posm"
        minSdkVersion 16
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    aaptOptions {
        noCompress "tflite"
        noCompress "lite"
    }
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.3.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'

    // Tensorflow-lite
    implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly'
    implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:0.0.0-nightly'

    implementation "androidx.core:core-ktx:+"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
repositories {
    maven { url 'https://dl.bintray.com/kotlin/kotlin-eap' }
    mavenCentral()
}
```

**Comment by thaink** [comment]
Did it happen in with the stable version?
implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:2.4.0'

**Comment by malik-anhar** [comment]
It gives another error
```
04-16 09:07:25.726 10132-10132/com.example.posm E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.posm, PID: 10132
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "fegetround" referenced by "libtensorflowlite_flex_jni.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:364)
        at java.lang.System.loadLibrary(System.java:526)
        at org.tensorflow.lite.flex.FlexDelegate.<clinit>(FlexDelegate.java:61)
        at com.example.posm.MainActivity.onCreate(MainActivity.java:71)
        at android.app.Activity.performCreate(Activity.java:5459)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2364)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2458)
        at android.app.ActivityThread.access$900(ActivityThread.java:172)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1305)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:146)
        at android.app.ActivityThread.main(ActivityThread.java:5598)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
        at dalvik.system.NativeStart.main(Native Method)
```
seems like the select-tf-ops dependency incompatible with the Android 4.4.2

**Comment by thaink** [comment]
I actually found fenv.h in Android 4.4.2
https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/host/i686-linux-glibc2.7-4.4.3/+/refs/tags/android-4.4.2_r1/sysroot/usr/include/fenv.h
Not sure why this happens.

**Comment by chunduriv** [comment]
@malik-anhar, Does [this](https://github.com/tensorflow/tensorflow/issues/48532#issuecomment-820896677) reference helps you? We see that you are using old version of tensorflow(2.4) , Could you please try to execute your code using latest stable version of TF 2.6.0 and let us know if the issue still persists in newer versions .Thanks!
