### ISSUE TITLE
tensorflow.python.framework.errors_impl.InternalError: CUDA runtime implicit initialization on GPU:0 failed. Status: all CUDA-capable devices are busy or unavailable

### ISSUE THREAD

**Issue by Leiga** [tensorflow/tensorflow#48558]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: cloud server
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.2.0
- Python version: 3.7.7
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 2..0.0
- GCC/Compiler version (if compiling from source): 7.5
- CUDA/cuDNN version: CUDA 10.1 & cuDNN 7.6.5
- GPU model and memory: 
00:07.0 VGA compatible controller: NVIDIA Corporation Device 1eb8 (rev a1) (prog-if 00 [VGA controller])
	Subsystem: NVIDIA Corporation Device 130e
	Physical Slot: 7
	Flags: bus master, fast devsel, latency 0, IRQ 37
	Memory at fc000000 (32-bit, non-prefetchable) [size=16M]
	Memory at e0000000 (64-bit, prefetchable) [size=256M]
	Memory at fa000000 (64-bit, non-prefetchable) [size=32M]
	I/O ports at c500 [size=128]
	Capabilities: [68] MSI: Enable+ Count=1/1 Maskable- 64bit+
	Kernel driver in use: nvidia
	Kernel modules: nvidiafb, nouveau, nvidia_drm, nvidia

![Screen Shot 2021-04-16 at 6 59 05 PM](https://user-images.githubusercontent.com/11975415/115015147-d26d2600-9ee5-11eb-91db-2fb3c863fa4f.png)

**Describe the problem**

Here is how i got the error

``Python 3.7.7 (default, May  7 2020, 21:25:33) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> hello = tf.constant('Hello, TensorFlow!')
2021-04-16 16:46:25.884063: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2021-04-16 16:46:25.888707: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-16 16:46:25.889366: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:00:07.0 name: GRID T4-4Q computeCapability: 7.5
coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 3.97GiB deviceMemoryBandwidth: 298.08GiB/s
2021-04-16 16:46:25.889562: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2021-04-16 16:46:25.891366: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2021-04-16 16:46:25.893293: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2021-04-16 16:46:25.893593: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2021-04-16 16:46:25.895611: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2021-04-16 16:46:25.896780: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2021-04-16 16:46:25.901308: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2021-04-16 16:46:25.901433: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-16 16:46:25.902118: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-16 16:46:25.902701: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2021-04-16 16:46:25.903031: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2021-04-16 16:46:25.910663: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2500000000 Hz
2021-04-16 16:46:25.910940: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fa728000b20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-04-16 16:46:25.910965: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-04-16 16:46:25.967935: W tensorflow/compiler/xla/service/platform_util.cc:210] unable to create StreamExecutor for CUDA:0: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_UNKNOWN: unknown error
2021-04-16 16:46:25.968035: I tensorflow/compiler/jit/xla_gpu_device.cc:161] Ignoring visible XLA_GPU_JIT device. Device number is 0, reason: Internal: no supported devices found for platform CUDA
2021-04-16 16:46:25.968258: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-16 16:46:25.968912: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:00:07.0 name: GRID T4-4Q computeCapability: 7.5
coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 3.97GiB deviceMemoryBandwidth: 298.08GiB/s
2021-04-16 16:46:25.968993: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2021-04-16 16:46:25.969017: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2021-04-16 16:46:25.969042: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2021-04-16 16:46:25.969066: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2021-04-16 16:46:25.969089: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2021-04-16 16:46:25.969113: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2021-04-16 16:46:25.969140: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2021-04-16 16:46:25.969237: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-16 16:46:25.969898: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-16 16:46:25.970481: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2021-04-16 16:46:25.970546: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/miniconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 262, in constant
    allow_broadcast=True)
  File "/home/miniconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 270, in _constant_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "/home/miniconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 95, in convert_to_eager_tensor
    ctx.ensure_initialized()
  File "/home/miniconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 515, in ensure_initialized
    context_handle = pywrap_tfe.TFE_NewContext(opts)
tensorflow.python.framework.errors_impl.InternalError: CUDA runtime implicit initialization on GPU:0 failed. Status: all CUDA-capable devices are busy or unavailable
**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Indeed, before this error, I had another error:

Could not load dynamic library 'libcublas.so.10'; dlerror: libcublasLt.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.1/lib64:

I didn't know why, but libcublas.so.10 and libcublasLt.so.10 were in /usr/local/cuda-10.2/targets/x86_64-linux/lib instead of /usr/local/cuda-10.1/lib64, so I copied them both to /usr/local/cuda-10.1/lib64 and it solved the problem. Would there be any connections between these two errors? If no, any help would be appreciated !

**Comment by Saduf2019** [comment]
@Leiga 
this seems Nvidia related error, please refer to these links and let us know if it helps:
[Link](https://forums.developer.nvidia.com/t/failure-to-set-vgpu-computing-mode-from-prohibited-to-default/107067/2), [link1](https://stackoverflow.com/questions/41965187/nvidia-device-error-in-tensorflow),[link2](https://github.com/NVIDIA/nvidia-docker/issues/262),[link3](https://stackoverflow.com/questions/6966496/nvidia-cuda-error-all-cuda-capable-devices-are-busy-or-unavailable-on-osx)

Also please confirm if you have referred to these [tested build configurations](https://www.tensorflow.org/install/source#gpu).
You may also try:
Restart the program with os.environ["CUDA_VISIBLE_DEVICES"] = '0'

**Comment by ymodak** [comment]
@Leiga Let's try [limiting gpu memory growth](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth) and see if it helps. Before that please make sure you close all python sessions and exit python interpreter, we want to make sure your gpu is not utilized any simulations.
```python
# on the top of your script
import tensorflow as tf
gpus = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(gpus[0], True)
# Paste rest of your code here
```

**Comment by Leiga** [comment]
> @Leiga Let's try [limiting gpu memory growth](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth) and see if it helps. Before that please make sure you close all python sessions and exit python interpreter, we want to make sure your gpu is not utilized any simulations.
> 
> ```python
> # on the top of your script
> import tensorflow as tf
> gpus = tf.config.list_physical_devices('GPU')
> tf.config.experimental.set_memory_growth(gpus[0], True)
> # Paste rest of your code here
> ```

I have tried putting those on top of my test script and run it. Unfortunately, It produced the same error as mentioned above.

**Comment by Leiga** [comment]
> @Leiga
> this seems Nvidia related error, please refer to these links and let us know if it helps:
> [Link](https://forums.developer.nvidia.com/t/failure-to-set-vgpu-computing-mode-from-prohibited-to-default/107067/2), [link1](https://stackoverflow.com/questions/41965187/nvidia-device-error-in-tensorflow),[link2](https://github.com/NVIDIA/nvidia-docker/issues/262),[link3](https://stackoverflow.com/questions/6966496/nvidia-cuda-error-all-cuda-capable-devices-are-busy-or-unavailable-on-osx)
> 
> Also please confirm if you have referred to these [tested build configurations](https://www.tensorflow.org/install/source#gpu).
> You may also try:
> Restart the program with os.environ["CUDA_VISIBLE_DEVICES"] = '0'

I have tried using `os.environ["CUDA_VISIBLE_DEVICES"] = '0'`  but it did not solve the problem.

After browsing this [link](https://forums.developer.nvidia.com/t/how-to-run-devicequery/54624) you recommended, I found that I had an issue with the Recommended [Actions](http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#recommended-post) under Post-Installation Actions from Nvidia docs

I tried running `/usr/bin/nvidia-persistenced --verbose`

but it raised an unexpected error:

`nvidia-persistenced failed to initialize. Check syslog for more details.`

And I had a trouble running ./deviceQuery. Would those cause the problem?

**Comment by ymodak** [comment]
Perhaps this [thread ](https://forums.developer.nvidia.com/t/nvidia-persistenced-failed-to-initialize-check-syslog-for-more-details/74052/5)can help you fix 
> nvidia-persistenced failed to initialize. Check syslog for more details.

**Comment by Saduf2019** [comment]
@Leiga 
Same error is reported and solved at Nvidia webiste shared below, please follow it and move this issue to closed status as it is not a tensorflow related issue, in case of any further questions related to same issue you may open a ticket with Nvidia.

https://forums.developer.nvidia.com/t/nvidia-persistenced-failed-to-initialize-check-syslog-for-more-details/74052

**Comment by Leiga** [comment]
> @Leiga
> Same error is reported and solved at Nvidia webiste shared below, please follow it and move this issue to closed status as it is not a tensorflow related issue, in case of any further questions related to same issue you may open a ticket with Nvidia.
> 
> https://forums.developer.nvidia.com/t/nvidia-persistenced-failed-to-initialize-check-syslog-for-more-details/74052

Are you sure the error `nvidia-persistenced failed to initialize. Check syslog for more details.` is the main cause of `tensorflow.python.framework.errors_impl.InternalError: CUDA runtime implicit initialization on GPU:0 failed. Status: all CUDA-capable devices are busy or unavailable` ? I have checked my nvidia-persistenced status with `systemctl status nvidia-persistenced` and it was active.
