### ISSUE TITLE
Fails building example projects for ESP micro

### ISSUE THREAD

**Issue by jruk** [tensorflow/tensorflow#48570]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): OSX 10.12.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): 2.5.0-rc1
- TensorFlow version:
- Python version:3.9
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
1. Got tensorflow-master
2. make -f tensorflow/lite/micro/tools/make/Makefile PARSE_THIRD_PARTY=true TARGET=esp generate_projects
3. Results in the following
tensorflow/lite/micro/tools/make/downloads/flatbuffers already exists, skipping the download.
tensorflow/lite/micro/tools/make/downloads/pigweed already exists, skipping the download.
Traceback (most recent call last):
  File "tensorflow/lite/micro/tools/make/generate_keil_project.py", line 122, in <module>
    parse_args()
  File "tensorflow/lite/micro/tools/make/generate_keil_project.py", line 118, in parse_args
    main(unparsed, flags)
  File "tensorflow/lite/micro/tools/make/generate_keil_project.py", line 40, in main
    six.ensure_str(flags.executable),
AttributeError: 'module' object has no attribute 'ensure_str'
make: *** [tensorflow/lite/micro/examples//hello_world/Makefile.inc:36: tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32_default/prj/hello_world_test/keil/keil_project.uvprojx] Error 1

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by vikramdattu** [comment]
Hi @jruk do you still have an issue?

Can you please share ESP-IDF version?

I would recommend to use esp-idf `release/v4.2`.

Please follow IDF setup instructions. i.e., goto IDF directory,
1.  run  `./install.sh` do install required packages including python and toolchain
2.  In the same directory run `. ./export.sh` to setup the environment.
3. Generate, build, flash and run the example as mentioned in example readme.

**Comment by jruk** [comment]
Hi Vikram,
Thank you for the reply. I have found a branch that works with PlatformIO
for ESP32 (somebody took care of building it from the sources).  I was
able to convert a model to TFLite and then to microformat.  Still very
difficult to find complete examples for 2D cases (including model,
transformation, microcontroller code).  How to map 2D arrays to the input
tensor preserving row and column order...  In some cases C++ code is
available, but corresponding models are not.   I hope that there will be
more complete cases learn from...

-Alex

**Comment by vikramdattu** [comment]
Hello again,

The examples here are pretty good IMHO: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples 

You can find exact instructions to generate and build the examples in README under each example: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples/hello_world#deploy-to-esp32 

Currently supported examples for ESP are: hello_world (sign wave generator), micro_speech (YES/NO/UNKNOWN words detector) and person_detection.

You can find one and start with it.

> Still very
> difficult to find complete examples for 2D cases (including model,
> transformation, microcontroller code).  How to map 2D arrays to the input
> tensor preserving row and column order...  In some cases C++ code is
> available, but corresponding models are not.

The CPP code, simply takes all the data in an array an interprets it as required. 
Do refer person_detection example provided by tflite for the same.

There are many resources available on training a model from scratch or re-training and conversion to quantized tflite format. 

I have created on example myself (cats_and_dogs). For your reference: https://github.com/vikramdattu/tensorflow/tree/master/cats_and_dogs

**Comment by jruk** [comment]
Hi Vikram, Thanks for the info!   I will look closer at the references you
have sent.
Alex
