### ISSUE TITLE
Keras plot_model: AttributeError: 'ResourceVariable' object has no attribute '_keras_history'

### ISSUE THREAD

**Issue by benjs** [tensorflow/tensorflow#48608]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): v2.4.0-49-g85c8b2a817f 2.4.1

The following things probably don't matter:
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04
- Python version: 3.8.5
- CUDA/cuDNN version: 11.2/8.1
- GPU model and memory: RTX3070, 8GB

**Describe the current behavior**
Error: `AttributeError: 'ResourceVariable' object has no attribute '_keras_history'`

**Describe the expected behavior**
Plot is saved to 'model.png'

**Standalone code to reproduce the issue**
Copy into colab or standalone file:
```python
import tensorflow as tf
from tensorflow.keras import Model, Input
from tensorflow.keras.layers import Add


class MyModel(Model):
    def __init__(self):
        super(MyModel, self).__init__()

        self.bias = self.add_weight(shape=(10, 64, 64, 256))
        self.add = Add()

    def call(self, x):
        return self.add([x, self.bias])


if __name__ == '__main__':
    mm = MyModel()

    x = Input(shape=(64, 64, 256), batch_size=10, name='Input')
    m = Model(inputs=[x], outputs=mm.call(x))
    tf.keras.utils.plot_model(m)

```

**Other info / logs** 
```
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    tf.keras.utils.plot_model(m)
  File "/home/benjs/Documents/projects/hpe/venv/lib/python3.8/site-packages/tensorflow/python/keras/utils/vis_utils.py", line 322, in plot_model
    dot = model_to_dot(
  File "/home/benjs/Documents/projects/hpe/venv/lib/python3.8/site-packages/tensorflow/python/keras/utils/vis_utils.py", line 235, in model_to_dot
    for inbound_layer in nest.flatten(node.inbound_layers):
  File "/home/benjs/Documents/projects/hpe/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/node.py", line 258, in inbound_layers
    inbound_layers = nest.map_structure(lambda t: t._keras_history.layer,
  File "/home/benjs/Documents/projects/hpe/venv/lib/python3.8/site-packages/tensorflow/python/util/nest.py", line 867, in map_structure
    structure[0], [func(*x) for x in entries],
  File "/home/benjs/Documents/projects/hpe/venv/lib/python3.8/site-packages/tensorflow/python/util/nest.py", line 867, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "/home/benjs/Documents/projects/hpe/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/node.py", line 258, in <lambda>
    inbound_layers = nest.map_structure(lambda t: t._keras_history.layer,
AttributeError: 'ResourceVariable' object has no attribute '_keras_history'
```

**Comment by Saduf2019** [comment]
@benjs 
The code shared works on 1.x, please refer to the (does not throw any error)[gist here](https://colab.research.google.com/gist/Saduf2019/efa031a154c8e6d526efe730e892d904/untitled589.ipynb).

You can find same error reported and resolved as mentioned above here:
[link](https://stackoverflow.com/questions/44889187/attributeerror-tensor-object-has-no-attribute-keras-history), [link1](https://github.com/keras-team/keras-contrib/issues/554)

**Comment by bhack** [comment]
isn't ` m = Model(inputs=[x], outputs=mm(x))` ?

**Comment by Saduf2019** [comment]
@benjs 
Please move this issue to closed status as its resolved.

**Comment by benjs** [comment]
Isn't it a bug, that `keras.utils.plot_model` cannot plot such models?
