### ISSUE TITLE
NameError: name 'wait' is not defined when executing tf.distribute.MirroredStrategy()

### ISSUE THREAD

**Issue by NafeesPhD** [tensorflow/tensorflow#48600]
**System information*
- TensorFlow version : 2.6.0
- Python version: 3.8
- GCC/Compiler version (if compiling from source):
- CUDA version:  11.2

I want to train the model using TensorFlow's MirroredStrategy on several GPUs. I've used `strategy = tf.distribute.MirroredStrategy()` many times before but this time when I executed it, I got an unusually long error and the mechanism became stuck for an extended period of time.

**Traceback (most recent call last)**
`File "/research/dept8/gds/anafees/anaconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1')
    self.run()
  File "/research/dept8/gds/anafees/anaconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/research/dept8/gds/anafees/anaconda3/lib/python3.8/multiprocessing/pool.py", line 519, in _handle_workers
    cls._wait_for_updates(current_sentinels, change_notifier)
  File "/research/dept8/gds/anafees/anaconda3/lib/python3.8/multiprocessing/pool.py", line 499, in _wait_for_updates
    wait(sentinels, timeout=timeout)
NameError: name 'wait' is not defined`
Note: It works flawlessly on a single GPU but causes the above problem on two GPUs.

**Comment by NafeesPhD** [comment]
I reinstalled TensorFlow and now everything is fine.
