### ISSUE TITLE
SavedModel file does not exist at

### ISSUE THREAD

**Issue by worknotalent** [tensorflow/tensorflow#48670]
Cannot load model whereas it does exist at the specified location.

I'm using tf.keras.models.load_model(PATH_TO_FILE) to do so, like it's explained [here](https://www.tensorflow.org/tutorials/keras/save_and_load#savedmodel_format), but it keeps on throwing:

Traceback (most recent call last):
  File "C:\Rasp\project\main.py", line 37, in <module>
    model = tf.keras.models.load_model(PATH_TO_FILE)
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\keras\saving\save.py", line 206, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\keras\saving\saved_model\load.py", line 121, in load
    meta_graph_def = loader_impl.parse_saved_model(path).meta_graphs[0]
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\saved_model\loader_impl.py", line 113, in parse_saved_model
    raise IOError(
OSError: SavedModel file does not exist at: C:\Rasp\experts_bit_r50x1_in21k_bird_1\saved_model.pb\{saved_model.pbtxt|saved_model.pb}

I tried with some of the models [here](https://tfhub.dev/s?q=bird).

**Comment by worknotalent** [comment]
I needed to target to wrapping folder, not the file.

**Comment by shanmukh05** [comment]
@worknotalent Can you share the code? It will be helpful to see where the error is occurring.
Thanks

**Comment by ymodak** [comment]
Try using `hub.load()` to [load](https://www.tensorflow.org/hub/api_docs/python/hub/load) models from TF Hub.
See [gist](https://colab.research.google.com/gist/ymodak/304c5d8adad525a7da868cf5f61ce602/untitled17.ipynb) that explains the usage.

**Comment by tilakrayal** [comment]
@worknotalent ,

Please take a look at @[ymodak](https://github.com/tensorflow/tensorflow/issues/48670#issuecomment-824195656)   comment and let us know if you are still facing the same issue? Thanks!

**Comment by worknotalent** [comment]
Sorry, I was just targetting the file instead of the containing folder, but anyways I discovered `hub.load()` and it works just fine, I'm just having a problem when I choose another model from the one used in the tutorial I followed:

`Traceback (most recent call last):
  File "C:\RealTimeObjectDetection\h.py", line 154, in <module>
    run_detector(detector, downloaded_image_path)
  File "C:\RealTimeObjectDetection\h.py", line 137, in run_detector
    result = detector(converted_img)
  File "C:\Users\axelc\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\eager\function.py", line 1711, in __call__
    return self._call_impl(args, kwargs)
  File "C:\Users\axelc\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\eager\wrap_function.py", line 246, in _call_impl
    return super(WrappedFunction, self)._call_impl(
  File "C:\Users\axelc\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\eager\function.py", line 1729, in _call_impl
    return self._call_with_flat_signature(args, kwargs, cancellation_manager)
  File "C:\Users\axelc\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\eager\function.py", line 1778, in _call_with_flat_signature
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "C:\Users\axelc\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\eager\function.py", line 1960, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "C:\Users\axelc\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\eager\function.py", line 591, in call
    outputs = execute.execute(
  File "C:\Users\axelc\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Matrix size-incompatible: In[0]: [1,239360], In[1]: [1280,965]
         [[node Logits/BiasAdd (defined at Users\axelc\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow_hub\module_v2.py:106) ]] [Op:__inference_pruned_3535]

Function call stack:
pruned`

The problem doesn't occur while loading the model from the hub but when I pass it an image, I'm pretty sure it's because of the shape of the image.

Is the wanted shape somewhere inside the loaded model?

**Comment by tilakrayal** [comment]
@worknotalent ,

Could you please confirm if the issue is resolved. if yes, please feel free to move this issue to closed status and please submit a new issue from this [link](https://github.com/tensorflow/models/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!
