### ISSUE TITLE
can not install tensorflow

### ISSUE THREAD

**Issue by ggproRIC** [tensorflow/tensorflow#48676]
import tensorflow as tf
Traceback (most recent call last):

  File "C:\Users\Home\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-13-64156d691fe5>", line 1, in <module>
    import tensorflow as tf

  File "C:\Users\Home\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import

  File "C:\Users\Home\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *

  File "C:\Users\Home\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 114
    def TFE_ContextOptionsSetAsync(arg1, async):
                                             ^
SyntaxError: invalid syntax

**Comment by saikumarchalla** [comment]
@ggproRIC  Could you please provide the  below information:

OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

Also, Please provide the exact sequence of commands that you have executed before running into the error. Thanks!

**Comment by saikumarchalla** [comment]
@ggproRIC  Do  you have any update on this?

**Comment by ggproRIC** [comment]
> @ggproRIC Do you have any update on this?

I solved it.
