### ISSUE TITLE
Skipping timesteps with ConvLSTM2D layer

### ISSUE THREAD

**Issue by maximgeller** [tensorflow/tensorflow#48678]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux RHEL 7.9
- TensorFlow installed from: binary
- TensorFlow version: 2.0.0 and 2.2.0
- Python version: 3.6.13

**Describe the current behavior**
I am working with 2D data with a variable number of timesteps, so I padded my data with zeroes and use a masking layer with the ConvLSTM2D layer; however I get an error telling me my dimensions are mismatched (traceback below)

**Describe the expected behavior**
I would expect the ConvLSTM2D layer to correctly skip the timesteps that have a value of 0 like the regular LSTM layer does. 
Note that without the masking layer, the code below runs fine.

**Standalone code to reproduce the issue**
```
import tensorflow as tf
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Flatten, ConvLSTM2D, MaxPooling2D, Masking, Input

inputs = Input(shape=(None,11,11,1)) 
mask = Masking(mask_value=0)(inputs)
conv2d_1 = ConvLSTM2D(64, (3, 3), activation="relu", padding="same")(mask)
max_pool_1 = MaxPooling2D((2,2), padding="same")(conv2d_1)
flatten = Flatten()(max_pool_1)
out = Dense(1, activation="sigmoid")(flatten)

x = np.random.rand(64, 300, 11, 11, 1)
y = np.random.randint(2, size=(64,1))

model = Model(inputs=inputs, outputs=out)
model.compile(loss='binary_crossentropy', optimizer='sgd', metrics=['accuracy'])
model.summary()
model.fit(x, y, epochs=2, batch_size=16)
```

**Other info / logs**
```
Traceback (most recent call last):
  File "/home/mgeller/.conda/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1610, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 1 in both shapes must be equal, but are 11 and 121. Shapes are [?,11,11,64] and [?,121,121,64]. for 'Select' (op: 'Select') with input shapes: [?,121,121,64], [?,11,11,64], [?,11,11,64].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "issue.py", line 8, in <module>
    conv2d_1 = ConvLSTM2D(64, (3, 3), activation="relu", padding="same")(mask)
  File "/home/mgeller/.conda/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/keras/layers/convolutional_recurrent.py", line 299, in __call__
    return super(ConvRNN2D, self).__call__(inputs, **kwargs)
  File "/home/mgeller/.conda/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/keras/layers/recurrent.py", line 623, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "/home/mgeller/.conda/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 842, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/home/mgeller/.conda/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/keras/layers/convolutional_recurrent.py", line 939, in call
    initial_state=initial_state)
  File "/home/mgeller/.conda/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/keras/layers/convolutional_recurrent.py", line 393, in call
    input_length=timesteps)
  File "/home/mgeller/.conda/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 4122, in rnn
    **while_loop_kwargs)
  File "/home/mgeller/.conda/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/ops/control_flow_ops.py", line 2675, in while_loop
    back_prop=back_prop)
  File "/home/mgeller/.conda/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/ops/while_v2.py", line 198, in while_loop
    add_control_dependencies=add_control_dependencies)
  File "/home/mgeller/.conda/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 915, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/mgeller/.conda/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/ops/while_v2.py", line 176, in wrapped_body
    outputs = body(*_pack_sequence_as(orig_loop_vars, args))
  File "/home/mgeller/.conda/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 4099, in _step
    tiled_mask_t, flat_output, flat_mask_output))
  File "/home/mgeller/.conda/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 4098, in <genexpr>
    array_ops.where(m, o, zo) for m, o, zo in zip(
  File "/home/mgeller/.conda/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/home/mgeller/.conda/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py", line 3753, in where
    return gen_math_ops.select(condition=condition, x=x, y=y, name=name)
  File "/home/mgeller/.conda/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_math_ops.py", line 9441, in select
    "Select", condition=condition, t=x, e=y, name=name)
  File "/home/mgeller/.conda/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 793, in _apply_op_helper
    op_def=op_def)
  File "/home/mgeller/.conda/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 548, in create_op
    compute_device)
  File "/home/mgeller/.conda/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3429, in _create_op_internal
    op_def=op_def)
  File "/home/mgeller/.conda/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1773, in __init__
    control_input_ops)
  File "/home/mgeller/.conda/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1613, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 1 in both shapes must be equal, but are 11 and 121. Shapes are [?,11,11,64] and [?,121,121,64]. for 'Select' (op: 'Select') with input shapes: [?,121,121,64], [?,11,11,64], [?,11,11,64].
```

**Comment by UsharaniPagadala** [comment]
@maximgeller 

I reproduced the code shared on tf 2.4, tf 2.5rc0 and tf-nightly and didn't get any errors.please find the [gist](https://colab.research.google.com/gist/UsharaniPagadala/7c09134e95ca294cb93604be37547be3/-48678.ipynb) here.
Could you please upgrade your tf version and let us know.Thanks

**Comment by maximgeller** [comment]
> I reproduced the code shared on tf 2.4, tf 2.5rc0 and tf-nightly and didn't get any errors.please find the [gist](https://colab.research.google.com/gist/UsharaniPagadala/7c09134e95ca294cb93604be37547be3/-48678.ipynb) here.
> Could you please upgrade your tf version and let us know.Thanks

I was successfully able to run the code on the newer TensorFlow version @UsharaniPagadala. However, my project is dependent on the version I tested on, so is there any fix that could work for 2.0.0 or 2.2.0?

**Comment by maximgeller** [comment]
update: I was able to run the code using TF 2.2.0 successfully, but I would really like to know if there could be a fix for r2.0

**Comment by UsharaniPagadala** [comment]
@maximgeller 

Please confirm if the issue still persist

**Comment by maximgeller** [comment]
@UsharaniPagadala This is still an issue for me when using r2.0 as that is the version my project is dependent on

**Comment by UsharaniPagadala** [comment]
@maximgeller 

Could you please reopen the issue with tf2.0 as it is fixed in tf2.2, and move this to closed status.Thanks
