### ISSUE TITLE
How to reopen eager_execution after close it ?

### ISSUE THREAD

**Issue by YanqingWu** [tensorflow/tensorflow#48747]
system: Macos X
TF version: 2.4.1

After turn off eager_execution,  I get the follow error.

Traceback (most recent call last):
  File "/Users/yanqing/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-52f64b3b4137>", line 12, in <module>
    convert_variables_to_constants_v2(func)
  File "/Users/yanqing/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/convert_to_constants.py", line 1068, in convert_variables_to_constants_v2
    converter_data = _FunctionConverterData(
  File "/Users/yanqing/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/convert_to_constants.py", line 806, in __init__
    self._build_tensor_data()
  File "/Users/yanqing/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/convert_to_constants.py", line 823, in _build_tensor_data
    data = map_index_to_variable[idx].numpy()
  File "/Users/yanqing/anaconda3/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 619, in numpy
    raise NotImplementedError(
NotImplementedError: numpy() is only available when eager execution is enabled.

```python
import tensorflow as tf
from tensorflow.python.framework.convert_to_constants import convert_variables_to_constants_v2


tf.compat.v1.disable_eager_execution()

# do something with tf1

module = tf.keras.layers.PReLU()
func = tf.function(lambda x0: module(x0))
func = func.get_concrete_function(tf.TensorSpec((10, 24, 24, 3), dtype=tf.float32))
convert_variables_to_constants_v2(func)
```

**Comment by Saduf2019** [comment]
@YanqingWu 
with respect to the error reported, this has been already reported, please refer to [this comment](https://github.com/tensorflow/tensorflow/issues/27491#issuecomment-770848466) and let us know if it helps you resolve the error reported. [you may also refer to similar issue :#37052, [link](https://analyticsindiamag.com/beginners-guide-to-tensorflow-eager-execution-machine-learning-developers/)]
