### ISSUE TITLE
Warnings related to Custom Layer 

### ISSUE THREAD

**Issue by pedrogalher** [tensorflow/tensorflow#48785]
**System information**
- Windows 10 (64-bit): 
- TensorFlow version: 2.1.0
- Python version: 3.6
- CPU

**Describe the current behavior**
I have implemented the custom layer described [here](https://github.com/fabianbormann/Tensorflow-DeconvNet-Segmentation/blob/master/DeconvNet.py). This layer is the UpSampling layer described in the SegNet model.

In order to test the implementation, I wrote a short dummy code (see in the standalone version): 

After  running, the following Info, Warning and Errors appear:

```

INFO:tensorflow:Converted call: <bound method UnpoolingLayer.call of <__main__.UnpoolingLayer object at 0x00000223E0021748>>
    args: (<tf.Tensor 'stage1_conv1_4/Identity:0' shape=(None, 64, 64, 64) dtype=float32>,)
    kwargs: {}

Converted call: <bound method UnpoolingLayer.call of <__main__.UnpoolingLayer object at 0x00000223E0021748>>
    args: (<tf.Tensor 'stage1_conv1_4/Identity:0' shape=(None, 64, 64, 64) dtype=float32>,)
    kwargs: {}

INFO:tensorflow:Error transforming entity <bound method UnpoolingLayer.call of <__main__.UnpoolingLayer object at 0x00000223E0021748>>
Traceback (most recent call last):
  File "C:\Users\zz19101\Anaconda3\envs\tf21\lib\site-packages\tensorflow_core\python\autograph\impl\api.py", line 526, in converted_call
    converted_f = conversion.convert(target_entity, program_ctx)
  File "C:\Users\zz19101\Anaconda3\envs\tf21\lib\site-packages\tensorflow_core\python\autograph\impl\conversion.py", line 328, in convert
    return _instantiate(entity, converted_entity_info, free_nonglobal_var_names)
  File "C:\Users\zz19101\Anaconda3\envs\tf21\lib\site-packages\tensorflow_core\python\autograph\impl\conversion.py", line 266, in _instantiate
    factory = converted_entity_info.get_factory()
  File "C:\Users\zz19101\Anaconda3\envs\tf21\lib\site-packages\tensorflow_core\python\autograph\impl\conversion.py", line 92, in get_factory
    assert self.module_name in sys.modules
AssertionError
Error transforming entity <bound method UnpoolingLayer.call of <__main__.UnpoolingLayer object at 0x00000223E0021748>>
WARNING:tensorflow:AutoGraph could not transform <bound method UnpoolingLayer.call of <__main__.UnpoolingLayer object at 0x00000223E0021748>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 
WARNING: AutoGraph could not transform <bound method UnpoolingLayer.call of <__main__.UnpoolingLayer object at 0x00000223E0021748>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 
Model: "model_4"

Traceback (most recent call last):
  File "C:\Users\zz19101\Anaconda3\envs\tf21\lib\site-packages\tensorflow_core\python\autograph\impl\api.py", line 526, in converted_call
    converted_f = conversion.convert(target_entity, program_ctx)
  File "C:\Users\zz19101\Anaconda3\envs\tf21\lib\site-packages\tensorflow_core\python\autograph\impl\conversion.py", line 328, in convert
    return _instantiate(entity, converted_entity_info, free_nonglobal_var_names)
  File "C:\Users\zz19101\Anaconda3\envs\tf21\lib\site-packages\tensorflow_core\python\autograph\impl\conversion.py", line 266, in _instantiate
    factory = converted_entity_info.get_factory()
  File "C:\Users\zz19101\Anaconda3\envs\tf21\lib\site-packages\tensorflow_core\python\autograph\impl\conversion.py", line 92, in get_factory
    assert self.module_name in sys.modules
AssertionError

```

**Standalone code to reproduce the issue**

```
def max_pool_with_argmax(x):
    """According to the documentation, the value at each position in the argmax tensor 
    is calculated according to:  so that a maximum value at position [b, y, x, c] 
    becomes flattened index: (y * width + x) * channels + c if include_batch_in_index 
    is False; ((b * height + y) * width + x) * channels + c if include_batch_in_index is True.
    
    """
    return tf.nn.max_pool_with_argmax(x, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='SAME')


class UnpoolingLayer(Layer):
    
    """ This class generates the Unpooling Layer present in the Segnet and 
    DeconvNet models.
    """
    def __init__(self, pooling_argmax, stride=[1,2,2,1], **kwargs):
        self.stride = stride
        self.pooling_argmax = pooling_argmax
        super(UnpoolingLayer, self).__init__(**kwargs)
        
    def build(self, input_shape):
        super(UnpoolingLayer, self).build(input_shape)

        
    def call(self, inputs):
       input_shape = K.cast(K.shape(inputs), dtype='int64')  # Convert
       
       output_shape = (input_shape[0],
                       input_shape[1]*self.stride[1],
                       input_shape[2]*self.stride[2],
                       input_shape[3])
       
       argmax = self.pooling_argmax
       one_like_mask = K.ones_like(argmax) # Create Tensor of 1s with same shape as argmax --> 4-dimensional tensor
       batch_range = K.reshape(K.arange(start=0, stop=input_shape[0], dtype='int64'), 
                                 shape=[input_shape[0], 1, 1, 1]) # Create a tensor of shape (Batch Size, 1 ,1 ,1)
       
       b = one_like_mask * batch_range  # 4 dimensional tensor
       #Multiply the ones mask by the batch range, so that we have a 4-dimension tensor, wth the pixels in the first dimension indicating the batch id for each index
       y = argmax // (output_shape[2] * output_shape[3])
       x = argmax % (output_shape[2] * output_shape[3]) // output_shape[3]
       feature_range = K.arange(start=0, stop=output_shape[3], dtype='int64')  # Indicate the channel index
       f = one_like_mask * feature_range
       
       updates_size = tf.size(inputs)  # Number of elements in the tensor
       indices = K.transpose(K.reshape(K.stack([b, y, x, f]), [4, updates_size]))   # Generate a 2D array where the rows are the b, y, x , f values and the columns are actually the number of elements in the input tensor, and then just transpose it
       values = K.reshape(inputs, [updates_size]) # flatten it to one dimension so that they can be feed to the tf.scatter
       
       
       return tf.scatter_nd(indices, values, output_shape)
   
    def compute_output_shape(self, input_shape):
        return (input_shape[0], input_shape[1] * 2, input_shape[2] * 2, input_shape[3])
    
    
    def get_config(self):
        base_config = super(UnpoolingLayer, self).get_config()
        base_config['pooling_argmax'] = self.pooling_argmax
        base_config['stride'] = self.stride
        return base_config

    @classmethod
    def from_config(cls, config):
        return cls(**config)
       

if __name__ == "__main__":
    
    
   input_tensor = Input(shape=(128,128,1))
   
   pool1, pool1_argmax = Lambda(max_pool_with_argmax, name='max_pool1')(input_tensor)
   
   x = Conv2D(64, kernel_size=3, padding='same', kernel_initializer='he_normal', name='stage1_conv1')(pool1)
   
   unpool1 = UnpoolingLayer(pool1_argmax, name='unpool1')(x)
   unpool1.set_shape(pool1.get_shape())
   
   x = Conv2D(64, kernel_size=3, padding='same', kernel_initializer='he_normal', name='stage1_conv1')(unpool1)
   
   model = Model(inputs = input_tensor, outputs = unpool1)
   model.summary()
```

What can be causing these warnings? Can I just ignore them?

**Comment by UsharaniPagadala** [comment]
@pedrogalher 

I ran the code shared but face a different error, please find the [gist](https://colab.research.google.com/gist/UsharaniPagadala/123b3202121c7b47cf0de23d769f3509/-48785.ipynb) here and share all dependencies such that we can replicate the issue reported .

**Comment by pedrogalher** [comment]
@UsharaniPagadala 

Hi, thanks for your answer. I run the code in TF 13.1 and Keras 2.2.4 and it apparently works now. Here is the [colab].(https://colab.research.google.com/drive/15j1qVC_33zQmtn12Cjbz30WY7m9P1n5g#scrollTo=qRlHE_bO77o9)

Can you test it in your machine with this setup and double-check that it actually works?

Thank you

**Comment by UsharaniPagadala** [comment]
@pedrogalher 
Thank you for your update, glad its working fine for you, kindly move this issue to closed status as it is resolved.

I don't have access to the colab you shared.Please provide me the access if it is required to reproduced the issue in the above mentioned tf versions .Please open a new issue if you'd like to work on this further.Thanks




</div></b>

**Comment by pedrogalher** [comment]
@UsharaniPagadala 

Hi! Could you try with this link: [https://colab.research.google.com/drive/15j1qVC_33zQmtn12Cjbz30WY7m9P1n5g?usp=sharing](colab)

**Comment by UsharaniPagadala** [comment]
@pedrogalher 
I tried running your [colab](https://colab.research.google.com/gist/UsharaniPagadala/9ba3cec01c42e4dc9594714b1fb85a3a/deconvnet.ipynb) provided,yes I could access it and didn't face any error.Thanks
