### ISSUE TITLE
Help : Incorrect read of byte[] { Cannot convert between a TensorFlowLite tensor with type FLOAT32 and a Java object of type [B (which is compatible with the TensorFlowLite type UINT8)  }

### ISSUE THREAD

**Issue by karundawadi** [tensorflow/tensorflow#48791]
The official tutorial mentions that tensor flow should support Byte[]. However, when passed to the model , the following error occurs: 
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.se, PID: 6529
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=65537, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/audio:31 flg=0x1 }} to activity {com.example.se/com.example.se.Homepage}: java.lang.RuntimeException: java.lang.IllegalArgumentException: Cannot convert between a TensorFlowLite tensor with type FLOAT32 and a Java object of type [B (which is compatible with the TensorFlowLite type UINT8).
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5015)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5056)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Cannot convert between a TensorFlowLite tensor with type FLOAT32 and a Java object of type [B (which is compatible with the TensorFlowLite type UINT8).
        at com.example.se.Classify.onActivityResult(Classify.java:164)
        at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:170)
        at android.app.Activity.dispatchActivityResult(Activity.java:8310)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5008)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5056) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
     Caused by: java.lang.IllegalArgumentException: Cannot convert between a TensorFlowLite tensor with type FLOAT32 and a Java object of type [B (which is compatible with the TensorFlowLite type UINT8).
        at org.tensorflow.lite.Tensor.throwIfTypeIsIncompatible(Tensor.java:427)
        at org.tensorflow.lite.Tensor.getInputShapeIfDifferent(Tensor.java:287)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:146)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:360)
        at org.tensorflow.lite.Interpreter.run(Interpreter.java:319)
        at com.example.se.Classify.onActivityResult(Classify.java:161)
        at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:170) 
        at android.app.Activity.dispatchActivityResult(Activity.java:8310) 
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5008) 
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5056) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```
My main code is :
```
package com.example.se;

import android.content.Context;
import android.content.Intent;
import android.content.res.AssetFileDescriptor;
import android.content.res.AssetManager;
import android.database.Cursor;
import android.media.AudioManager;
import android.net.Uri;
import android.net.rtp.AudioStream;
import android.os.Bundle;
import android.os.FileUtils;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.fragment.app.Fragment;

import org.tensorflow.lite.Interpreter;
import org.tensorflow.lite.flex.FlexDelegate;
import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.lang.Object;
import java.net.URISyntaxException;
import java.nio.ByteBuffer;
import java.nio.MappedByteBuffer;
import java.nio.channels.FileChannel;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class Classify extends Fragment {
    private Button choose_file_button;
    private Button stop_classify;
    public static final int PICKFILE_RESULT_CODE = 1;
    private Uri fileUri;
    private String filePath; // This is the final file path
    View classify_view;

    // To load from asset folder
    private static final String LABEL_FILENAME = "file:///android_asset/labels.txt";
    private static final String MODEL_FILENAME = "file:///android_asset/soundclassifier.tflite";
    private static final String LOG_TAG = "Log tagges is here";

    // For label and modelfile
    private List<String> labels = new ArrayList<String>();
    private List<String> displayedLabels = new ArrayList<>();

    // For the audio file
    ByteArrayOutputStream out = new ByteArrayOutputStream();
    InputStream in;
    byte[] audioBytes;


    // For machine learning
    private final Interpreter.Options tfliteOptions = new Interpreter.Options();
    private MappedByteBuffer tfLiteModel;
    private Interpreter tfLite;
    private final Interpreter.Options ftliteOptions = new Interpreter.Options();
    float[] outputs;
    private RecognizeCommands recognizeCommands = null;
    // ToDo : Remove this if not needed

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        classify_view = inflater.inflate(R.layout.classify,container,false);

        // Both finds the classify and stop classify button
        choose_file_button = (Button) classify_view.findViewById(R.id.classify_button);
        stop_classify = (Button) classify_view.findViewById(R.id.stop_classify);

        // For labels file
        String actualLabelFilename = LABEL_FILENAME.split("file:///android_asset/",-1)[1];
        Log.i(LOG_TAG,"Reading labels from " + actualLabelFilename);

        BufferedReader br = null;
        try{
            br = new BufferedReader(new InputStreamReader(classify_view.getContext().getAssets().open(actualLabelFilename)));
            String line;
            while ((line = br.readLine()) != null){
                labels.add(line);
                if (line.charAt(0) != '_'){
                    displayedLabels.add(line.substring(0,1).toUpperCase()+ line.substring(1));
                }
            }
        } catch (IOException e){
            throw new RuntimeException("Problem reading the label file!",e);
        }
        // Creates the equal number of labels on the output file
        outputs = new float[displayedLabels.size()];
        Log.i(LOG_TAG,"Labels file messages are :"+ displayedLabels);

        // ToDo : Implement Recognize Commands if not working

        // Opening the model file
        String actualModelFilename = MODEL_FILENAME.split("file:///android_asset/",-1)[1];
        try{
            tfLiteModel = loadModelFile(classify_view.getContext().getAssets(), actualModelFilename);
        } catch (Exception e){
            throw new RuntimeException(e);
        }

        Log.i(LOG_TAG,"The modal file is :"+actualModelFilename);
        Log.i(LOG_TAG,"The actual content is :"+tfLiteModel);

        // ToDo : Model file opened here
        try{
            ftliteOptions.setNumThreads(1);
            FlexDelegate flex = new FlexDelegate();
            ftliteOptions.addDelegate(flex);
            File openThis = new File(MODEL_FILENAME);
            tfLite = new Interpreter(tfLiteModel,ftliteOptions);
            // tfLite = new Interpreter(openThis);
        } catch (Exception e){
            throw new RuntimeException(e);
        }
        Log.i(LOG_TAG,"TF lite file loaded. ");

        choose_file_button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent chooseFile = new Intent(Intent.ACTION_GET_CONTENT);
                chooseFile.setType("*/*");
                chooseFile = Intent.createChooser(chooseFile, "Choose a file");
                startActivityForResult(chooseFile, PICKFILE_RESULT_CODE);
                // At this point we have the path of the file
                // File path working.
                /*
                    For pie chart we can have : https://github.com/PhilJay/MPAndroidChart
                 * */
            }
        });
        return classify_view;
    }
    // This gets the file path
    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        switch (requestCode) {
            case PICKFILE_RESULT_CODE:
                if (resultCode == -1) {
                    fileUri = data.getData();
                    filePath = fileUri.getPath();
                    System.out.println("The selected file path is :"+filePath);
                    open_audio_file(fileUri);
                    // Opens main audio file
                    try{
                        // Todo : Remove another loadModelFile @Depreciated
                        tfLite.run(audioBytes,outputs);
                        Log.i(LOG_TAG,"The output is :"+ outputs);
                    }catch(Exception e){
                        throw new RuntimeException(e);
                    }
                }
                break;
        }
    }

    public void open_audio_file(Uri filePath){
        try{
            in = new BufferedInputStream(getContext().getContentResolver().openInputStream(filePath));

            int read;
            byte[] buff = new byte[1024];
            while ((read = in.read(buff)) > 0)
            {
                out.write(buff, 0, read);
            }
            out.flush();
        }catch(Exception e){
            throw new RuntimeException(e);
        }
        //Todo : Change the audio file to a float pointer
        audioBytes = out.toByteArray();
        for (int i = 0;i < audioBytes.length;i++){
            Log.i(LOG_TAG,i+" "+audioBytes[i]);
        }
    }

    // This method loads the TF lite file
    private static MappedByteBuffer loadModelFile(AssetManager assets, String modelFileName)
            throws IOException{
        AssetFileDescriptor fileDescriptor = assets.openFd(modelFileName);
        FileInputStream inputStream = new FileInputStream(fileDescriptor.getFileDescriptor());
        FileChannel fileChannel = inputStream.getChannel();
        long startOffset = fileDescriptor.getStartOffset();
        long declaredLength = fileDescriptor.getDeclaredLength();
        return fileChannel.map(FileChannel.MapMode.READ_ONLY,startOffset,declaredLength);
    }

}
```

I am trying to convert the.wav file into an byte array using the function : 
```
public void open_audio_file(Uri filePath){
        try{
            in = new BufferedInputStream(getContext().getContentResolver().openInputStream(filePath));

            int read;
            byte[] buff = new byte[1024];
            while ((read = in.read(buff)) > 0)
            {
                out.write(buff, 0, read);
            }
            out.flush();
        }catch(Exception e){
            throw new RuntimeException(e);
        }
        //Todo : Change the audio file to a float pointer
        audioBytes = out.toByteArray();
        for (int i = 0;i < audioBytes.length;i++){
            Log.i(LOG_TAG,i+" "+audioBytes[i]);
        }
    }
```

**Comment by karundawadi** [comment]
I did verify that the byte[] file created is actually generating the output. This was done using the for loop and also verified using the [StackOverflow answer](https://stackoverflow.com/questions/67290748/how-to-read-wav-file-as-byte-array-in-android-studio).

**Comment by abattery** [comment]
This is an intended behavior. You need to provide a float array for float inputs not the byte array.

**Comment by karundawadi** [comment]
@abattery I am reading in a .wav file from the system, what would be the best way to convert it to a float array?

**Comment by abattery** [comment]
@lintian06 could you help? Looks like this issue is related to the sound classification example.

**Comment by abattery** [comment]
@karundawadi If your model is generated from the Sound classification example from the Teachable Machine, you need to create a float buffer that holds audio PCM sample.

**Comment by karundawadi** [comment]
@abattery I converted a wav file to byte[] and converted it to a float buffer. However, upon passing it, it showed me a newer type of error, 

The error is : 
```
 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.se, PID: 8184
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=65537, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/audio:31 flg=0x1 }} to activity {com.example.se/com.example.se.Homepage}: java.lang.RuntimeException: java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: tensorflow/lite/kernels/reshape.cc:69 num_input_elements != num_output_elements (28750 != 0)
    Node number 12 (RESHAPE) failed to invoke.
    
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5015)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5056)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: tensorflow/lite/kernels/reshape.cc:69 num_input_elements != num_output_elements (28750 != 0)
    Node number 12 (RESHAPE) failed to invoke.
    
        at com.example.se.Classify.onActivityResult(Classify.java:165)
        at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:170)
        at android.app.Activity.dispatchActivityResult(Activity.java:8310)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5008)
        	... 11 more
     Caused by: java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: tensorflow/lite/kernels/reshape.cc:69 num_input_elements != num_output_elements (28750 != 0)
    Node number 12 (RESHAPE) failed to invoke.
    
        at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:163)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:360)
        at org.tensorflow.lite.Interpreter.run(Interpreter.java:319)
        at com.example.se.Classify.onActivityResult(Classify.java:162)
        	... 14 more

```
The code is : 
```
 byte[] audioBytes;
 float[] audioInput;
audioBytes = out.toByteArray();
        audioInput = new float[audioBytes.length];
        outputs = new float[audioBytes.length];
        for (int i = 0;i < audioBytes.length;i++){
            audioInput[i] = (float) audioBytes[i];
        }
```

All other remaining aspects of the program was kept the same. The output and input both are in float [].

**Comment by abattery** [comment]
Is it possible to share your TFLite to us to take a look at the graph?

**Comment by karundawadi** [comment]
Yes, I have attached the file to this comment. 

The link redirects to my google drive, where all the files are present. 

[Link to File](https://drive.google.com/drive/folders/1HA_90Bgic60Zurla_5OAK75Uu83EpKlB?usp=sharing)

**Comment by abattery** [comment]
I ran your TFLite model with the TFLite model benchmark tool. It was successfully done. According to the model spec, you need to provide a float [1][44032] array. Please make sure that your inference code meets the model spec's requirement.

**Comment by karundawadi** [comment]
Thank you I implemented the float specifications as you provided, it worked. 

Thank you!

**Comment by abattery** [comment]
Glad to hear that!
