### ISSUE TITLE
AttributeError: module 'tensorflow.compat.v2.__internal__' has no attribute 'tf2

### ISSUE THREAD

**Issue by Davidelvis** [tensorflow/tensorflow#48799]
Hey
Some help on this bug, 
I am using tensorflow ==1.15

Traceback (most recent call last):
  File "a2c.py", line 7, in <module>
    import  keras.backend as K
  File "/home/david/miniconda3/envs/kedro-environment/lib/python3.7/site-packages/keras/__init__.py", line 20, in <module>
    from . import initializers
  File "/home/david/miniconda3/envs/kedro-environment/lib/python3.7/site-packages/keras/initializers/__init__.py", line 124, in <module>
    populate_deserializable_objects()
  File "/home/david/miniconda3/envs/kedro-environment/lib/python3.7/site-packages/keras/initializers/__init__.py", line 49, in populate_deserializable_objects
    LOCAL.GENERATED_WITH_V2 = tf.__internal__.tf2.enabled()
AttributeError: module 'tensorflow.compat.v2.__internal__' has no attribute 'tf2'

**Comment by bhack** [comment]
We don't support TensorFlow 1.x anymore. Please upgrade to a more recent TF version.

**Comment by Davidelvis** [comment]
I get the same error while using tensorflow ==2.4.1
 Error
 Traceback (most recent call last):
  File "a2c.py", line 7, in <module>
    import  keras.backend as K
  File "/home/david/miniconda3/envs/kedro-environment/lib/python3.7/site-packages/keras/__init__.py", line 20, in <
module>
    from . import initializers
  File "/home/david/miniconda3/envs/kedro-environment/lib/python3.7/site-packages/keras/initializers/__init__.py", 
line 124, in <module>
    populate_deserializable_objects()
  File "/home/david/miniconda3/envs/kedro-environment/lib/python3.7/site-packages/keras/initializers/__init__.py", 
line 49, in populate_deserializable_objects
    LOCAL.GENERATED_WITH_V2 = tf.__internal__.tf2.enabled()
AttributeError: module 'tensorflow.compat.v2.__internal__' has no attribute 'tf2'

**Comment by Saduf2019** [comment]
@Davidelvis 

Can you install with PIP as follows,
pip install tensorflow==2.4.1       [pip install tensorflow-estimator==2.4.*]
Let us know if issue still persists. 
Could you also try installing TensorFlow in a new virtual environment and check if you are facing the same issue? 
Thanks!

**Comment by Davidelvis** [comment]
Thanks so much @Saduf2019 and @bhack

**Comment by Saduf2019** [comment]
@Davidelvis 
Please move the issue to closed status as resolved.
