### ISSUE TITLE
Needed to install `pbr` and `funcsigs`

### ISSUE THREAD

**Issue by daj** [tensorflow/tensorflow#4880]
I was following the [Pip Installation](https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#pip-installation) instructions.  When I ran the [Test the TensorFlow installation](https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#test-the-tensorflow-installation) steps, I hit two errors, listed below.

### The Fix!
To fix, I ran `pip install pbr funcsigs`, then the test Python program worked.

### Environment info
Operating System: Mac OSX 10.10.5

If installed from binary pip package, provide:

1. A link to the pip package you installed:
I installed this one:
```
# Mac OS X, CPU only, Python 2.7:
$ export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.11.0rc0-py2-none-any.whl
```
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
```
0.11.0rc0
```

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
I was following the existing instructions, I don't _think_ I missed any steps...

### Logs or other output that would be helpful

Here are the two errors that I saw:

1) 
```
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 98, in <module>
    from tensorflow.python.platform import test
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/platform/test.py", line 77, in <module>
    import mock                # pylint: disable=g-import-not-at-top,unused-import
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mock/__init__.py", line 2, in <module>
    import mock.mock as _mock
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mock/mock.py", line 69, in <module>
    from pbr.version import VersionInfo
ImportError: No module named pbr.version
```

2)
```
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 98, in <module>
    from tensorflow.python.platform import test
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/platform/test.py", line 77, in <module>
    import mock                # pylint: disable=g-import-not-at-top,unused-import
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mock/__init__.py", line 2, in <module>
    import mock.mock as _mock
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mock/mock.py", line 80, in <module>
    import funcsigs
ImportError: No module named funcsigs
```

**Comment by jart** [comment]
According to #3714 "El Capitan has a protection feature built-in that prevents overwriting some python dirs even with sudo" and "Do not use sudo pip on Mac. use `pip install --user <package_name>`." Maybe those security features are why pip wasn't able to install pbr and funcsigs, even though they're dependencies of mock, which was installed.

But since mock declares its dependencies in an unusual way, maybe testing-cabal/mock#261 is relevant. Do you need to upgrade setuptools or pip?

**Comment by daj** [comment]
I was installing TensorFlow as part of setting up [this neural style project](https://github.com/anishathalye/neural-style).  At some point while installing all the dependencies I _did_ find that I needed to upgrade pip, as I was running pip 1.5.2.  I upgraded it to pip 8.1.2.  If a minimum pip version is required maybe add that to the [Pip Installation](https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#pip-installation) documentation?

**Comment by jart** [comment]
We know pip 1.5.4 works because that's what comes with Ubuntu 14.04. Is there anything in the [pip release notes](https://pip.pypa.io/en/stable/news/) that you think might have caused this issue?

![image](https://cloud.githubusercontent.com/assets/49262/19413056/375c65f4-92d8-11e6-8c27-5dbd457ec3ef.png)

Also I'm not even sure if it's possible for us to tune our setup.py to throw an error if a particular version of pip is being used. pip seems independent of the setuptools process.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please provide further information when it becomes available, and we will reopen the issue.
