### ISSUE TITLE
xla Compiling and Bug issues

### ISSUE THREAD

**Issue by raj-brown** [tensorflow/tensorflow#48810]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution : UBUNTU 18.04
- TensorFlow installed from (source or binary): NVIDIA Container 21.03
- TensorFlow version (use command below): 1.15.5
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:11.2/8.1.1
- GPU model and memory: A100 40GB

Dear All-

We tried to run a tensorflow based program with xla option on and with Float64. It throws the following error

2021-04-28 21:33:40.228029: W ./tensorflow/compiler/xla/service/hlo_pass_fix.h:50] Unexpectedly high number of iterations in HLO passes 'simplification' exiting fixed point loop.
2021-04-28 21:34:18.432071: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:70] Can't find ptxas binary in ${CUDA_DIR}/bin.  Will back to the GPU driver for PTX -> sass compilation.  This is OK so long as you don't see a warning below about an out-of-date driver version. Custom ptxas location can be specified using $PATH.
2021-04-28 21:34:18.432136: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:71] Searched for CUDA in the following directories:
2021-04-28 21:34:18.432146: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   ./cuda_sdk_lib
2021-04-28 21:34:18.432150: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   /usr/local/cuda
2021-04-28 21:34:18.432153: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   .
2021-04-28 21:34:18.432157: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:76] You can choose the search directory by setting xla_gpu_cuda_data_dir in HloModule's DebugOptions.  For most apps, setting the environment variable XLA_FLAGS=--xla_gpu_cuda_data_dir=/path/to/cuda will work.
2021-04-28 21:34:18.489483: I tensorflow/compiler/jit/xla_compilation_cache.cc:241] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
2021-04-28 21:34:21.374512: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:70] Can't find ptxas binary in ${CUDA_DIR}/bin.  Will back to the GPU driver for PTX -> sass compilation.  This is OK so long as you don't see a warning below about an out-of-date driver version. Custom ptxas location can be specified using $PATH.
2021-04-28 21:34:21.374608: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:71] Searched for CUDA in the following directories:
2021-04-28 21:34:21.374616: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   ./cuda_sdk_lib
2021-04-28 21:34:21.374620: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   /usr/local/cuda
2021-04-28 21:34:21.374624: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   .
2021-04-28 21:34:21.374629: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:76] You can choose the search directory by setting xla_gpu_cuda_data_dir in HloModule's DebugOptions.  For most apps, setting the environment variable XLA_FLAGS=--xla_gpu_cuda_data_dir=/path/to/cuda will work.
2021-04-28 21:34:21.432005: I tensorflow/compiler/jit/xla_compilation_cache.cc:241] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
2021-04-28 21:34:22.707773: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:70] Can't find ptxas binary in ${CUDA_DIR}/bin.  Will back to the GPU driver for PTX -> sass compilation.  This is OK so long as you don't see a warning below about an out-of-date driver version. Custom ptxas location can be specified using $PATH.
2021-04-28 21:34:22.707843: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:71] Searched for CUDA in the following directories:
2021-04-28 21:34:22.707865: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   ./cuda_sdk_lib
2021-04-28 21:34:22.707870: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   /usr/local/cuda
2021-04-28 21:34:22.707875: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   .
2021-04-28 21:34:22.707881: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:76] You can choose the search directory by setting xla_gpu_cuda_data_dir in HloModule's DebugOptions.  For most apps, setting the environment variable XLA_FLAGS=--xla_gpu_cuda_data_dir=/path/to/cuda will work.
2021-04-28 21:34:22.770755: I tensorflow/compiler/jit/xla_compilation_cache.cc:241] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
2021-04-28 21:34:23.269560: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:70] Can't find ptxas binary in ${CUDA_DIR}/bin.  Will back to the GPU driver for PTX -> sass compilation.  This is OK so long as you don't see a warning below about an out-of-date driver version. Custom ptxas location can be specified using $PATH.
2021-04-28 21:34:23.269643: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:71] Searched for CUDA in the following directories:
2021-04-28 21:34:23.269654: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   ./cuda_sdk_lib
2021-04-28 21:34:23.269658: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   /usr/local/cuda
2021-04-28 21:34:23.269664: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   .
2021-04-28 21:34:23.269668: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:76] You can choose the search directory by setting xla_gpu_cuda_data_dir in HloModule's DebugOptions.  For most apps, setting the environment variable XLA_FLAGS=--xla_gpu_cuda_data_dir=/path/to/cuda will work.
2021-04-28 21:34:23.335512: I tensorflow/compiler/jit/xla_compilation_cache.cc:241] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
2021-04-28 21:34:25.538813: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:70] Can't find ptxas binary in ${CUDA_DIR}/bin.  Will back to the GPU driver for PTX -> sass compilation.  This is OK so long as you don't see a warning below about an out-of-date driver version. Custom ptxas location can be specified using $PATH.
2021-04-28 21:34:25.538892: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:71] Searched for CUDA in the following directories:
2021-04-28 21:34:25.538902: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   ./cuda_sdk_lib
2021-04-28 21:34:25.538907: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   /usr/local/cuda
2021-04-28 21:34:25.538910: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   .
2021-04-28 21:34:25.538915: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:76] You can choose the search directory by setting xla_gpu_cuda_data_dir in HloModule's DebugOptions.  For most apps, setting the environment variable XLA_FLAGS=--xla_gpu_cuda_data_dir=/path/to/cuda will work.
2021-04-28 21:34:25.597336: I tensorflow/compiler/jit/xla_compilation_cache.cc:241] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
2021-04-28 21:34:26.675753: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:70] Can't find ptxas binary in ${CUDA_DIR}/bin.  Will back to the GPU driver for PTX -> sass compilation.  This is OK so long as you don't see a warning below about an out-of-date driver version. Custom ptxas location can be specified using $PATH.
2021-04-28 21:34:26.675825: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:71] Searched for CUDA in the following directories:
2021-04-28 21:34:26.675835: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   ./cuda_sdk_lib
2021-04-28 21:34:26.675839: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   /usr/local/cuda
2021-04-28 21:34:26.675844: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   .
2021-04-28 21:34:26.675873: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:76] You can choose the search directory by setting xla_gpu_cuda_data_dir in HloModule's DebugOptions.  For most apps, setting the environment variable XLA_FLAGS=--xla_gpu_cuda_data_dir=/path/to/cuda will work.
2021-04-28 21:34:26.738493: I tensorflow/compiler/jit/xla_compilation_cache.cc:241] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
2021-04-28 21:34:28.676419: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:70] Can't find ptxas binary in ${CUDA_DIR}/bin.  Will back to the GPU driver for PTX -> sass compilation.  This is OK so long as you don't see a warning below about an out-of-date driver version. Custom ptxas location can be specified using $PATH.
2021-04-28 21:34:28.676522: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:71] Searched for CUDA in the following directories:
2021-04-28 21:34:28.676543: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   ./cuda_sdk_lib
2021-04-28 21:34:28.676550: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   /usr/local/cuda
2021-04-28 21:34:28.676554: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   .
2021-04-28 21:34:28.676558: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:76] You can choose the search directory by setting xla_gpu_cuda_data_dir in HloModule's DebugOptions.  For most apps, setting the environment variable XLA_FLAGS=--xla_gpu_cuda_data_dir=/path/to/cuda will work.
2021-04-28 21:34:28.692114: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:70] Can't find ptxas binary in ${CUDA_DIR}/bin.  Will back to the GPU driver for PTX -> sass compilation.  This is OK so long as you don't see a warning below about an out-of-date driver version. Custom ptxas location can be specified using $PATH.
2021-04-28 21:34:28.692203: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:71] Searched for CUDA in the following directories:
2021-04-28 21:34:28.692213: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   ./cuda_sdk_lib
2021-04-28 21:34:28.692219: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   /usr/local/cuda
2021-04-28 21:34:28.692223: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   .
2021-04-28 21:34:28.692226: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:76] You can choose the search directory by setting xla_gpu_cuda_data_dir in HloModule's DebugOptions.  For most apps, setting the environment variable XLA_FLAGS=--xla_gpu_cuda_data_dir=/path/to/cuda will work.
2021-04-28 21:34:28.741081: I tensorflow/compiler/jit/xla_compilation_cache.cc:241] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
2021-04-28 21:34:28.754700: I tensorflow/compiler/jit/xla_compilation_cache.cc:241] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
2021-04-28 21:34:30.031037: E tensorflow/stream_executor/cuda/cuda_driver.cc:614] failed to load PTX text as a module: CUDA_ERROR_INVALID_PTX: a PTX JIT compilation failed
2021-04-28 21:34:30.031132: E tensorflow/stream_executor/cuda/cuda_driver.cc:619] error log buffer (1024 bytes): ptxas error   : Entry function 'fusion_466' uses too much shared data (0xc600 bytes, 0xc000 max)
ptxas error   : Entry function 'fusion_462' uses too much shared data (0xc600 bytes, 0xc000 max)
ptxas error   : Entry function 'fusion_488' uses too much shared data (0xc600 bytes, 0xc000 max)
ptxas error   : Entry function 'fusion_498' uses too much shared data (0xc600 bytes, 0xc000 max)
ptxas error   : Entry function 'fusion_490' uses too much shared data (0xc600 bytes, 0xc000 max)
ptxas error   : Entry function 'fusion_500' uses too much shared data (0xc600 bytes, 0xc000 max)
ptxas error   : Entry function 'fusion_520' uses too much shared data (0xc600 bytes, 0xc000 max)
ptxas error   : Entry function 'fusion_524' uses too much shared data (0xc600 bytes, 0xc000 max)
ptxas error   : Entry function 'fusion_460' uses too much shared data (0xc600 bytes, 0xc000 max)
ptxas error   : Entry function 'fusion_534' uses too much shared data (0xc600 bytes, 0xc000 max)
ptxas error   : Entry function 'fusion_464' uses too 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 1349, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 1441, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.InternalError: Failed to load PTX text as a module: CUDA_ERROR_INVALID_PTX: a PTX JIT compilation failed
	 [[{{node cluster_2_1/xla_run}}]]
The same code run with out the xla option on. The xla option work seamlessly for float32 and tf32.

We will appreciate your help.

Thanks!
Raj

**Comment by UsharaniPagadala** [comment]
@raj-brown 

In order to expedite the trouble-shooting process, please provide a code snippet/colab gist to reproduce the issue reported here. Thanks!

**Comment by UsharaniPagadala** [comment]
@raj-brown 
Can you please confirm if you face this issue on stable version 2.4.1 along with cuda 11.0 [cuda version 11.2 is tested with tf 2.5, there is no update on 11.3].Thanks
