### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Failed to load native TensorFlow Lite methods.

### ISSUE THREAD

**Issue by Duskley** [tensorflow/tensorflow#48857]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Samsung Galaxy s5 min
- TensorFlow installed from (source or binary): source 
- TensorFlow version: 'org.tensorflow:tensorflow-lite:2.4.0' + org.tensorflow:tensorflow-android:1.13.1'
- Python version:
- Installed using virtualenv? pip? conda?: 
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

hello little question for a computer project in computer license I have to refactor an old application and make it modular. But here's when I build my generate signed bundle and I launch a feature on demand who use tensorflow on my android I have this error:

FATAL EXCEPTION: Thread-9
Process: descartes.info.l3ak2.eyetrek, PID: 7275
java.lang.UnsatisfiedLinkError: Failed to load native TensorFlow Lite methods. Check that the correct native libraries are present, and, if using a custom native library, have been properly loaded via System.loadLibrary():
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/androidx.test.tools.crawler-gvh38WebyoKL_IpGVoIEuw==/base.apk", zip file "/data/app/descartes.info.l3ak2.eyetrek-h1-hReoVf26OAguR-8QZHw==/base.apk", zip file "/data/app/descartes.info.l3ak2.eyetrek-h1-hReoVf26OAguR-8QZHw==/split_config.xxhdpi.apk", zip file "/data/app/descartes.info.l3ak2.eyetrek-h1-hReoVf26OAguR-8QZHw==/split_moduleastronomie.apk", zip file "/data/app/descartes.info.l3ak2.eyetrek-h1-hReoVf26OAguR-8QZHw==/split_moduleastronomie.config.xxhdpi.apk", zip file "/data/app/descartes.info.l3ak2.eyetrek-h1-hReoVf26OAguR-8QZHw==/split_modulereconnaissancechantsoiseaux.apk", zip file "/data/app/descartes.info.l3ak2.eyetrek-h1-hReoVf26OAguR-8QZHw==/split_modulereconnaissancechantsoiseaux.config.xxhdpi.apk", zip file "/data/app/descartes.info.l3ak2.eyetrek-h1-hReoVf26OAguR-8QZHw==/split_modulereconnaissancefeuille.apk", zip file "/data/app/descartes.info.l3ak2.eyetrek-h1-hReoVf26OAguR-8QZHw==/split_modulereconnaissancefeuille.config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/androidx.test.tools.crawler-gvh38WebyoKL_IpGVoIEuw==/lib/arm64, /data/app/descartes.info.l3ak2.eyetrek-h1-hReoVf26OAguR-8QZHw==/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libtensorflowlite_jni.so"
at org.tensorflow.lite.TensorFlowLite.init(TensorFlowLite.java:80)
at org.tensorflow.lite.NativeInterpreterWrapper.(NativeInterpreterWrapper.java:52)
at org.tensorflow.lite.Interpreter.(Interpreter.java:277)
at org.tensorflow.lite.Interpreter.(Interpreter.java:262)
at descartes.info.l3ak2.eyetrek.module_reconnaissance_feuille.tensorflow.ImageClassifierFpasF.(ImageClassifierFpasF.java:102)
at descartes.info.l3ak2.eyetrek.module_reconnaissance_feuille.fragment.FragmentScanFeuille$6.run(FragmentScanFeuille.java:1306)
at java.lang.Thread.run(Thread.java:764)

how can I resolve this ?

**Comment by abattery** [comment]
@Duskley 
would you share the below deatils to help you out the above problem,
1- build script which use to compile android app?
2- your handset cpu abi version(adb shell getprop ro.product.cpu.abi)?
3- sdk and ndk version which you configure with tensorflow?

**Comment by Duskley** [comment]
> @Duskley
> would you share the below deatils to help you out the above problem,
> 1- build script which use to compile android app?
> 2- your handset cpu abi version(adb shell getprop ro.product.cpu.abi)?
> 3- sdk and ndk version which you configure with tensorflow?

Of course, is that enough for you?

apply plugin: 'com.android.application'

android {
    compileSdkVersion 30
    defaultConfig {
        applicationId "descartes.info.l3ak2.eyetrek"
        minSdkVersion 23
        targetSdkVersion 30
        versionCode 63
        versionName "6.0"
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
        renderscriptTargetApi 28 //must match target sdk and build tools
        renderscriptSupportModeEnabled true

        /*arm64-v8a,*/
        ndk {
            abiFilters 'arm64-v8a,armeabi-v7a'
        }
         
    }
    lintOptions {
        abortOnError false
        checkReleaseBuilds false
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        intermediaire {
        }
    }
    aaptOptions {
        noCompress "tflite"
        noCompress "lite"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    dataBinding {
        enabled true
    }

    splits
    {
        density
         {
            enable false
            exclude "ldpi", "xxhdpi", "xxxhdpi"
            compatibleScreens 'small', 'normal', 'large', 'xlarge'
         }
    }

    sourceSets { main { jni.srcDirs = ['src/main/jni', 'src/main/jniLibs/'] } }

    buildToolsVersion = '28.0.3'

    dynamicFeatures = [':features:moduleastronomie',
                       ':features:modulereconnaissancechantsoiseaux',
                       ':features:modulereconnaissancefeuille']
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    // mise en place modularite L3AK2

    api 'org.tensorflow:tensorflow-lite:2.4.0'
    api 'org.tensorflow:tensorflow-android:1.13.1'
    api 'org.tensorflow:tensorflow-lite:2.4.0'
    api 'org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly'
    api project(':openCVLibrary3413')

    implementation 'androidx.annotation:annotation:1.1.0'
    api "androidx.appcompat:appcompat:${versions.appcompat}"
    api 'androidx.constraintlayout:constraintlayout:2.0.4'
    api 'com.google.android.material:material:1.3.0'
    api "com.google.android.play:core:${versions.playcore}"
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'

    implementation 'pl.droidsonroids.gif:android-gif-drawable:1.2.23'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    implementation 'com.google.android.material:material:1.3.0'
    implementation 'com.github.mmin18:realtimeblurview:1.2.1'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
    implementation 'com.squareup.retrofit2:retrofit:2.3.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.3.0'
    implementation 'com.getkeepsafe.taptargetview:taptargetview:1.11.0'
    implementation 'de.hdodenhof:circleimageview:1.2.1'
    implementation 'net.danlew:android.joda:2.9.9.1'
    implementation 'androidx.palette:palette:1.0.0'
    implementation('com.github.bumptech.glide:glide:4.6.1')
    {
        exclude group: "com.android.support"
    }
    implementation 'androidx.fragment:fragment:1.3.1'
    implementation 'life.knowledge4:k4l-video-trimmer:1.0'
    implementation 'androidx.recyclerview:recyclerview:1.1.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'com.android.volley:volley:1.2.0'
    implementation 'com.github.wendykierp:JTransforms:3.1'
    implementation 'pl.droidsonroids.gif:android-gif-drawable:1.2.19'
    implementation 'jp.wasabeef:blurry:3.0.0'
}

**Comment by Duskley** [comment]
> Could you also share your handset cpu abi version(adb shell getprop ro.product.cpu.abi)?

I do not know enough Android studio how to do?

**Comment by abattery** [comment]
Fyi, https://support.google.com/android/answer/7680439?hl=en

**Comment by Duskley** [comment]
> Fyi, https://support.google.com/android/answer/7680439?hl=en

Version android : 6.01
Security patch level : ASKS v1.2 Release 161011

**Comment by Duskley** [comment]
> > Fyi, https://support.google.com/android/answer/7680439?hl=en
> 
> Version android : 6.01
> Security patch level : ASKS v1.2 Release 161011

I specify I changed the software of my phone so that I can do the tests in android 6.0. The application must work at least in 6.0 (it is recorded on the specifications ^^)

**Comment by abattery** [comment]
@thaink could you take a look?

**Comment by Duskley** [comment]
I am still waiting for your answer. have you found a solution to my problem ^^ ?

**Comment by abattery** [comment]
Instead of using the mixed version like the below one;

```
api 'org.tensorflow:tensorflow-lite:2.4.0'
api 'org.tensorflow:tensorflow-android:1.13.1'
api 'org.tensorflow:tensorflow-lite:2.4.0'
api 'org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly'
```

Use the same version:

```
   // Import tflite dependencies
    implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly-SNAPSHOT'
    // The GPU delegate library is optional. Depend on it as needed.
    implementation 'org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly-SNAPSHOT'
```

**Comment by Duskley** [comment]
> Instead of using the mixed version like the below one;
> 
> ```
> api 'org.tensorflow:tensorflow-lite:2.4.0'
> api 'org.tensorflow:tensorflow-android:1.13.1'
> api 'org.tensorflow:tensorflow-lite:2.4.0'
> api 'org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly'
> ```
> 
> Use the same version:
> 
> ```
>    // Import tflite dependencies
>     implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly-SNAPSHOT'
>     // The GPU delegate library is optional. Depend on it as needed.
>     implementation 'org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly-SNAPSHOT'
> ```

ok i will try I'll let you know ^^

**Comment by Duskley** [comment]
> Instead of using the mixed version like the below one;
> 
> ```
> api 'org.tensorflow:tensorflow-lite:2.4.0'
> api 'org.tensorflow:tensorflow-android:1.13.1'
> api 'org.tensorflow:tensorflow-lite:2.4.0'
> api 'org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly'
> ```
> 
> Use the same version:
> 
> ```
>    // Import tflite dependencies
>     implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly-SNAPSHOT'
>     // The GPU delegate library is optional. Depend on it as needed.
>     implementation 'org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly-SNAPSHOT'
> ```

the same error yet 

i try to put alone implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly-SNAPSHOT' in my app graddle (no work) and the same for api 'org.tensorflow:tensorflow-lite:2.4.0'

**Comment by thaink** [comment]
@Duskley Does it work on emulator with the same Android version?

**Comment by Duskley** [comment]
> @Duskley Does it work on emulator with the same Android version?

Hello, yes it works very well. To switch from an aab format to an apk format I have to change the ndk filters. I'm going from arm64-v8a, armeabi-v7a to armeabi-v7a (My phone only supports armeabi-v7a). Does this crash have something to do with ndk filters?

**Comment by thaink** [comment]
Not sure but I suspect that or `sourceSets` might be the problem.
Could you check if the .so file does exists in the apk and tests several option on these fields?

**Comment by Duskley** [comment]
> Not sure but I suspect that or `sourceSets` might be the problem.
> Could you check if the .so file does exists in the apk and tests several option on these fields?

Hello, sorry for the late reply. I have checked in my apk and the libtensorflowlite.so file is present but in the aab file it cannot be found, so I think my problem is due to the libtensorflowlite.so file which is nonexistent in my aab file. The question now is "is there a step to include .so files in the aab?". I specify there are normally other .so which are present in my apk but which are not found in the aab

**Comment by thaink** [comment]
I am not familiar with aab bundling. Hope this link could help: https://developer.android.com/studio/build/configure-apk-splits#configure-split

**Comment by Duskley** [comment]
> I am not familiar with aab bundling. Hope this link could help: https://developer.android.com/studio/build/configure-apk-splits#configure-split

ok
