### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by its-shubham2323** [tensorflow/tensorflow#48886]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution ( Windows 10 Home ):
- TensorFlow installed from (source ):
- TensorFlow version: don't know 
- Python version: 3.9.4
- Installed using virtualenv? pip? conda?: pip 
- GPU model and memory: AMD Redeon R4 integrated graphics card 4 gb memory 

**Describe the problem**

Traceback (most recent call last):
  File "c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in _main
    status = self.run(options, args)
  File "c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\cli\req_command.py", line 204, in wrapper
    return func(self, options, args)
  File "c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\commands\install.py", line 318, in run
    requirement_set = resolver.resolve(
  File "c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 127, in resolve       
    result = self._result = resolver.resolve(
  File "c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 473, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 341, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _merge_into_criterion     
    if not criterion.candidates:
  File "c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 139, in __bool__
    return bool(self._sequence)
  File "c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in __bool__
    return any(self)
  File "c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 129, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 33, in _iter_built
    candidate = func()
  File "c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 200, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 306, in __init__    
    super().__init__(
  File "c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 151, in __init__    
    self.dist = self._prepare()
  File "c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 234, in _prepare    
    dist = self._prepare_distribution()
  File "c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 317, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File "c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\operations\prepare.py", line 508, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\operations\prepare.py", line 550, in _prepare_linked_requirement
    local_file = unpack_url(
  File "c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\operations\prepare.py", line 239, in unpack_url
    file = get_http_url(
  File "c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\operations\prepare.py", line 102, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\network\download.py", line 157, in __call__
    for chunk in chunks:
  File "c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\cli\progress_bars.py", line 152, in iter
    for x in it:
  File "c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\network\utils.py", line 62, in response_chunks
    for chunk in response.raw.stream(
  File "c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\urllib3\response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\urllib3\response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "c:\users\lenovo\appdata\local\programs\python\python39\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\urllib3\response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
WARNING: Ignoring invalid distribution -yqt5-sip (c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -yqt5-sip (c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages) 

**Provide the exact sequence of commands/steps that you executed before running into the problem**
`pip install tenserflow`

**Any other info/logs**
Include any logos or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@its-shubham2323 

We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]

Based on the error please refer to: #48034,#43986,#38235, [link](https://stackoverflow.com/questions/43298872/how-to-solve-readtimeouterror-httpsconnectionpoolhost-pypi-python-org-port) and let us know.

**Comment by ymodak** [comment]
> pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

Looks you are having weak internet connection which fails to download the pip package.
Please try with a stable connection.

**Comment by its-shubham2323** [comment]
> > pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
> 
> Looks you are having weak internet connection which fails to download the pip package.
> Please try with a stable connection.

Okkk

**Comment by Saduf2019** [comment]
@its-shubham2323 
please move this to closed status if resolved.

**Comment by ankur-rana99** [comment]
Try to set socket timeout to a higher value:

pip3 install -U --upgrade --timeout 10000 tensorflow

it worked for me while installing jupyter
