### ISSUE TITLE
tensorflow hello world catch error

### ISSUE THREAD

**Issue by looveu** [tensorflow/tensorflow#489]
this is my installation info
```
sudo -H pip install https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): tensorflow==0.5.0 from https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): six>=1.10.0 in /Library/Python/2.7/site-packages (from tensorflow==0.5.0)
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.9.2 in /Library/Python/2.7/site-packages (from tensorflow==0.5.0)
```
but when I run the code in readme I got this error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/tensorflow/__init__.py", line 4, in <module>
    from tensorflow.python import *
  File "/Library/Python/2.7/site-packages/tensorflow/python/__init__.py", line 13, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/Library/Python/2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 8, in <module>
    from google.protobuf import reflection as _reflection
  File "/Library/Python/2.7/site-packages/google/protobuf/reflection.py", line 58, in <module>
    from google.protobuf.internal import python_message as message_impl
  File "/Library/Python/2.7/site-packages/google/protobuf/internal/python_message.py", line 59, in <module>
    import six.moves.copyreg as copyreg
ImportError: No module named copyreg
```
six i has installed.
I'm a python fresher.

**Comment by krishpop** [comment]
Did you try upgrading six with pip? Just run pip --upgrade six

**Comment by looveu** [comment]
I find this on https://www.tensorflow.org/versions/master/get_started/os_setup.html#mac-os-x-importerror-no-module-named-copyreg

**Comment by looveu** [comment]
```
sudo easy_install -U six
```
