### ISSUE TITLE
 TypeError: __init__() got an unexpected keyword argument 'state_is_tuple'

### ISSUE THREAD

**Issue by tthtlc** [tensorflow/tensorflow#4890]
Please help me resolved the error:

```
I tensorflow/core/common_runtime/gpu/gpu_device.cc:717] Creating TensorFlow device (/gpu:3) -> (device: 3, name: GeForce GTX TITAN X, pci bus id: 0000:05:00.0)
..
======================================================================
ERROR: testAttentionDecoderStateIsTuple (__main__.Seq2SeqTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tensorflow/tensorflow/python/kernel_tests/seq2seq_test.py", line 308, in testAttentionDecoderStateIsTuple
    cell = tf.nn.rnn_cell.BasicLSTMCell(2, state_is_tuple=True)
TypeError: __init__() got an unexpected keyword argument 'state_is_tuple'

======================================================================
ERROR: testDynamicAttentionDecoder1 (__main__.Seq2SeqTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tensorflow/tensorflow/python/kernel_tests/seq2seq_test.py", line 271, in testDynamicAttentionDecoder1
    enc_outputs, enc_state = tf.nn.dynamic_rnn(cell, inp, dtype=tf.float32)
TypeError: dynamic_rnn() takes at least 3 arguments (3 given)

======================================================================
ERROR: testDynamicAttentionDecoder2 (__main__.Seq2SeqTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tensorflow/tensorflow/python/kernel_tests/seq2seq_test.py", line 290, in testDynamicAttentionDecoder2
    enc_outputs, enc_state = tf.nn.dynamic_rnn(cell, inp, dtype=tf.float32)
TypeError: dynamic_rnn() takes at least 3 arguments (3 given)

======================================================================
ERROR: testEmbeddingAttentionDecoder (__main__.Seq2SeqTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tensorflow/tensorflow/python/kernel_tests/seq2seq_test.py", line 368, in testEmbeddingAttentionDecoder
    embedding_size=2, output_size=3)
TypeError: embedding_attention_decoder() got an unexpected keyword argument 'embedding_size'

======================================================================
ERROR: testEmbeddingAttentionSeq2Seq (__main__.Seq2SeqTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tensorflow/tensorflow/python/kernel_tests/seq2seq_test.py", line 382, in testEmbeddingAttentionSeq2Seq
    cell = tf.nn.rnn_cell.BasicLSTMCell(2, state_is_tuple=True)
TypeError: __init__() got an unexpected keyword argument 'state_is_tuple'

======================================================================
ERROR: testEmbeddingRNNDecoder (__main__.Seq2SeqTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tensorflow/tensorflow/python/kernel_tests/seq2seq_test.py", line 85, in testEmbeddingRNNDecoder
    cell = tf.nn.rnn_cell.BasicLSTMCell(2, state_is_tuple=True)
TypeError: __init__() got an unexpected keyword argument 'state_is_tuple'

======================================================================
ERROR: testEmbeddingRNNSeq2Seq (__main__.Seq2SeqTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tensorflow/tensorflow/python/kernel_tests/seq2seq_test.py", line 105, in testEmbeddingRNNSeq2Seq
    cell = tf.nn.rnn_cell.BasicLSTMCell(2, state_is_tuple=True)
TypeError: __init__() got an unexpected keyword argument 'state_is_tuple'

======================================================================
ERROR: testEmbeddingTiedRNNSeq2Seq (__main__.Seq2SeqTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tensorflow/tensorflow/python/kernel_tests/seq2seq_test.py", line 170, in testEmbeddingTiedRNNSeq2Seq
    cell = tf.nn.rnn_cell.BasicLSTMCell(2, state_is_tuple=True)
TypeError: __init__() got an unexpected keyword argument 'state_is_tuple'

======================================================================
ERROR: testModelWithBooleanFeedPrevious (__main__.Seq2SeqTest)
Test the model behavior when feed_previous is True.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tensorflow/tensorflow/python/kernel_tests/seq2seq_test.py", line 764, in testModelWithBooleanFeedPrevious
    TestModel(model)
  File "tensorflow/tensorflow/python/kernel_tests/seq2seq_test.py", line 695, in TestModel
    enc_inp, dec_inp_fp_true, feed_previous=True)
  File "tensorflow/tensorflow/python/kernel_tests/seq2seq_test.py", line 685, in ForwardBackward
    dec_op, _ = seq2seq(enc_inp, dec_inp, feed_previous=feed_previous)
  File "tensorflow/tensorflow/python/kernel_tests/seq2seq_test.py", line 726, in EmbeddingRNNSeq2SeqF
    cell = tf.nn.rnn_cell.BasicLSTMCell(2, state_is_tuple=True)
TypeError: __init__() got an unexpected keyword argument 'state_is_tuple'

======================================================================
ERROR: testModelWithBuckets (__main__.Seq2SeqTest)
Larger tests that does full sequence-to-sequence model training.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tensorflow/tensorflow/python/kernel_tests/seq2seq_test.py", line 617, in testModelWithBuckets
    _, losses = SampleGRUSeq2Seq(inp, out, weights)
  File "tensorflow/tensorflow/python/kernel_tests/seq2seq_test.py", line 609, in SampleGRUSeq2Seq
    softmax_loss_function=SampledLoss)
  File "/usr/local/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/seq2seq.py", line 926, in model_with_buckets
    decoder_inputs[:bucket[1]])
  File "tensorflow/tensorflow/python/kernel_tests/seq2seq_test.py", line 598, in GRUSeq2Seq
    state_is_tuple=True)
TypeError: __init__() got an unexpected keyword argument 'state_is_tuple'

======================================================================
ERROR: testModelWithBucketsScopeAndLoss (__main__.Seq2SeqTest)
Test that variable scope reuse is not reset after model_with_buckets.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tensorflow/tensorflow/python/kernel_tests/seq2seq_test.py", line 568, in testModelWithBucketsScopeAndLoss
    _, losses1 = SampleGRUSeq2Seq(inp, out, weights, per_example_loss=False)
  File "tensorflow/tensorflow/python/kernel_tests/seq2seq_test.py", line 561, in SampleGRUSeq2Seq
    per_example_loss=per_example_loss)
  File "/usr/local/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/seq2seq.py", line 926, in model_with_buckets
    decoder_inputs[:bucket[1]])
  File "tensorflow/tensorflow/python/kernel_tests/seq2seq_test.py", line 554, in GRUSeq2Seq
    state_is_tuple=True)
TypeError: __init__() got an unexpected keyword argument 'state_is_tuple'

======================================================================
ERROR: testOne2ManyRNNSeq2Seq (__main__.Seq2SeqTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tensorflow/tensorflow/python/kernel_tests/seq2seq_test.py", line 452, in testOne2ManyRNNSeq2Seq
    cell = tf.nn.rnn_cell.BasicLSTMCell(2, state_is_tuple=True)
TypeError: __init__() got an unexpected keyword argument 'state_is_tuple'

----------------------------------------------------------------------
Ran 20 tests in 1.935s
```

**Comment by jart** [comment]
How are you invoking these tests? What version are you using?

**Comment by aselle** [comment]
Closing automatically due to lack of recent activity. Please reopen when further information becomes available. Thank you.
