### ISSUE TITLE
tf.ragged.constant fails on list of np.array

### ISSUE THREAD

**Issue by JRice15** [tensorflow/tensorflow#48941]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): OSX Catalina 10.15
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.5.0rc2
- Python version: 3.9.2

**Describe the current behavior**

Passing a list of Numpy arrays of rank > 1 one breaks tf.ragged.constant. Happens in both tf 2.4 and 2.5

**Describe the expected behavior**

That it would create the requests multidimensional ragged constant. I think this is a pretty common use case; for example, I have N variable-sized lists of xyz points, shape (None, 3), and want to turn them into one ragged constant of shape (N, None, 3).

**Standalone code to reproduce the issue**

https://colab.research.google.com/drive/1Zi40gL5IdARNeKid_7R_2b7_JcnWDW0T?usp=sharing 

**Other info / logs** Include any logs or source code that would be helpful to
`Traceback (most recent call last):
  File "/Users/user1/Desktop/CS/ML/trees/trees-pointnet/test.py", line 31, in <module>
    b = tf.ragged.constant(a, ragged_rank=1)
  File "/Users/user1/anaconda3/envs/tf2.5/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/Users/user1/anaconda3/envs/tf2.5/lib/python3.9/site-packages/tensorflow/python/ops/ragged/ragged_factory_ops.py", line 86, in constant
    return _constant_value(ragged_factory, constant_op.constant, pylist, dtype,
  File "/Users/user1/anaconda3/envs/tf2.5/lib/python3.9/site-packages/tensorflow/python/ops/ragged/ragged_factory_ops.py", line 218, in _constant_value
    inner_shape = _default_inner_shape_for_pylist(pylist, ragged_rank)
  File "/Users/user1/anaconda3/envs/tf2.5/lib/python3.9/site-packages/tensorflow/python/ops/ragged/ragged_factory_ops.py", line 311, in _default_inner_shape_for_pylist
    inner_shape = get_inner_shape(flat_values)
  File "/Users/user1/anaconda3/envs/tf2.5/lib/python3.9/site-packages/tensorflow/python/ops/ragged/ragged_factory_ops.py", line 285, in get_inner_shape
    return (len(item),) + get_inner_shape(item[0])
  File "/Users/user1/anaconda3/envs/tf2.5/lib/python3.9/site-packages/tensorflow/python/ops/ragged/ragged_factory_ops.py", line 284, in get_inner_shape
    elif item:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

**Comment by bhack** [comment]
Can you check with https://github.com/tensorflow/tensorflow/pull/48945?

**Comment by JRice15** [comment]
That looks like it should do it

**Comment by tilakrayal** [comment]
@JRice15 ,

Please close this issue once PR is merged.Thanks

**Comment by tilakrayal** [comment]
@Saduf2019 ,

I was able to reproduce the issue in tf v2.4,v2.5 and nightly.Please find the [gist](https://colab.research.google.com/gist/tilakrayal/002794e031c0d95a282f4f108bcd7511/48941.ipynb) here.

**Comment by bhack** [comment]
Please close this. The PR Is merged.
