### ISSUE TITLE
DeepDream tutorial and TFSlim

### ISSUE THREAD

**Issue by bhack** [tensorflow/tensorflow#4907]
What do you think to switch the DeepDream tutorial  notebook to MetaGraph? I see that  fine tuning and new inception models are more oriented on tfslim and slim models use the new meta+check point.

**Comment by bhack** [comment]
@vrv What do you think of this? I can also try to make a PR but I need some support on how to handle this..

**Comment by vrv** [comment]
It sounds reasonable.  In addition, there's also support coming for the even more general "SavedModel" which builds on MetaGraph, the details of which I'm not familiar.  Assigning this to Sherry who can comment!

cc @sherrym @nfiedel

**Comment by bhack** [comment]
I see also that models are too inhomogeneous between sample. The InceptionV3 in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/image_retraining is not the same of DeepDream tutorial that it is different from slims models and its finetune instructions.

**Comment by bhack** [comment]
I think that we can restore a tfslim model meta and checkpoint using:
```
new_saver = tf.train.import_meta_graph(<meta_graph>)
new_saver.restore(sess, <checkpoint>)
```
But after notebook uses 
```
tf.import_graph_def(graph_def, {'input':t_preprocessed})
````
I've tryied to substitute with

```
tf.import_graph_def(graph.as_graph_def(), {'distort_image/ExpandDims':t_preprocessed})
```
to maintain the next cells code and change only layers names in the notebook but I think that it is not the right way to do it.

**Comment by vrv** [comment]
Assigning to Pete, since I believe he set up the inception5h.zip which has the raw GraphDef rather than the MetaGraph.  I don't know how to regenerate the MetaGraph for inception easily.  Presumably someone could take an inception model from github.com/tensorflow/models.git and do this for us as a learning exercise, if Pete or someone else doesn't get to it.

**Comment by bhack** [comment]
@vrv Following [Slim Readme](https://github.com/tensorflow/models/blob/master/slim/README.md) for finetuning we have Meta+Checkpoint. Input tensor it is not named "input" like in inception5h and layers name changes. Probably for DeepDream with finetuning on user data we need to propose a larger trainable_scope than "InceptionV3/Logits,InceptionV3/AuxLogits".

**Comment by bhack** [comment]
Also https://github.com/tensorflow/models/blob/master/inception/README.md has cross reference with https://github.com/tensorflow/models/blob/master/slim/README.md but models are different and create a little bit of confusion.

**Comment by bhack** [comment]
Could be partially related to https://github.com/tensorflow/tensorflow/issues/5036

**Comment by vilemduha** [comment]
I am really fighting with getting deepdream running with slim inception model....
While it was running with a pre-trained model as is in the tutorial, I trained a model from models/slim/nets/inception_v3, and simply can't get it running at all..

while I got to passing the model with the instructions from bhack:
```
new_saver = tf.train.import_meta_graph(<meta_graph>)
new_saver.restore(sess, <checkpoint>)
tf.import_graph_def(graph.as_graph_def(), {'distort_image/ExpandDims':t_preprocessed})

```
I simply can't get past that point while getting this error:
```
Traceback (most recent call last):
  File "tensorflowdream_simple.py", line 165, in <module>
    render_naive('outputs/experiments/naive',T(layer)[:,:,:,channel], img_noise, 40)
  File "tensorflowdream_simple.py", line 157, in render_naive
    g, score = sess.run([t_grad, t_score], {t_input:img})
  File "/home/vilem/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/home/vilem/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 969, in _run
    fetch_handler = _FetchHandler(self._graph, fetches, feed_dict_string)
  File "/home/vilem/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 408, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  File "/home/vilem/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 230, in for_fetch
    return _ListFetchMapper(fetch)
  File "/home/vilem/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 337, in __init__
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "/home/vilem/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 227, in for_fetch
    (fetch, type(fetch)))
TypeError: Fetch argument None has invalid type <type 'NoneType'>
```



Sincerely, when I started with tf, I hoped it would be simple as it can be with such a complex thing as neural networks, and everything looked that way until the point where I wanted to go my own way.The networks aren't hard at all in the end, compared with learning how to read, write a graph, use it, or create own dataset....

**Comment by yaroslavvb** [comment]
@vilemduha from the error I'm guessing `t_grad` and/or `t_score` are `None` instead of being tensors

**Comment by vilemduha** [comment]
yaroslavvb - 
Exactly...I found that allready by placing a print of the fetches in the session py file.
 but I don't get why?
the code is otherwise actually the same as in tutorial. 

this is start:```


checkpoint_folder = '/media/vilem/RYCHLEJ/nntrain/train/scan3d/all/'


    
# We retrieve our checkpoint fullpath
checkpoint = tf.train.get_checkpoint_state(checkpoint_folder)
input_checkpoint = checkpoint.model_checkpoint_path

# We clear devices to allow TensorFlow to control on which device it will load operations
clear_devices = True

# We import the meta graph and retrieve a Saver
saver = tf.train.import_meta_graph(input_checkpoint + '.meta', clear_devices=clear_devices)

# We retrieve the protobuf graph definition
#graph = tf.get_default_graph()
#graph_def = graph.as_graph_def()

# We start a session and restore the graph weights
sess = tf.InteractiveSession()
saver.restore(sess, input_checkpoint)  
graph = sess.graph
graph_def = sess.graph_def
    
t_input = tf.placeholder(np.float32, name='input') # define the input tensor
imagenet_mean = 117.0
t_preprocessed = tf.expand_dims(t_input-imagenet_mean, 0)


tf.import_graph_def(graph_def, {'distort_image/Mul':t_preprocessed})
```

and this is a function call later:```




img_noise = np.random.uniform(size=(299,299,3)) + 100.0
def render_naive(fname, t_obj, img0=img_noise, iter_n=20, step=1.0):
    t_score = tf.reduce_mean(t_obj) # defining the optimization objective
    t_grad = tf.gradients(t_score, t_input)[0] # behold the power of automatic differentiation!
    
    
   
    
    img = img0.copy()
    for i in range(iter_n):
        g, score = sess.run([t_grad, t_score], {t_input:img0})
        # normalizing the gradient, so the same step size should work 
        g /= g.std()+1e-8         # for different layers and networks
        img += g*step
        print(score, end = ' ')
    #clear_output()
    showarray(visstd(img), fname)

render_naive('outputs/experiments/naive',T(layer)[:,:,:,channel], img_noise, 40)
```

**Comment by vilemduha** [comment]
I forgot to append - 
the printout from the 'fetches' is 
[None, <tf.Tensor 'Mean:0' shape=() dtype=float32>]
so t_grad is None.

**Comment by ProGamerGov** [comment]
@vilemduha Did you ever get the DeepDream tutorial working with the meta graphs?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity, but please let me know if I'm mistaken. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.

**Comment by dynamicwebpaige** [comment]
Closing this issue, as TF-Slim is no longer officially supported and will be [sunset in TensorFlow 2.0](https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md). Please reopen if you have any questions. Thanks!
