### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: Key BeamSearchDecoderStep/multi_rnn_cell/cell_0_attention/attention_wrapper/lstm_cell_9/bias not found in checkpoint

### ISSUE THREAD

**Issue by YR123-123** [tensorflow/tensorflow#49105]
**System information**
- TensorFlow version: 2.4.0
- Python version: 3.6.2

**Problem**
I am trying to upgrade the LAS model from tensorflow 1.8.0 version to 2.4.0. There is no problem in training the model, but in the testing phase, loading the model will show that there is a parameter not found. I printed the saved model file, there is a parameter named 1 in it. I don't understand where the problem is. I would be very grateful if you can answer my question!

**Error Message**
```
2021-05-11 17:09:25.582423: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-05-11 17:09:25.582893: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
INFO:tensorflow:Using config: {'_model_dir': './data_kss/Kspon_dataset/model_test', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_checkpoint_save_graph_def': True, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Building listener
2021-05-11 17:09:33.837384: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-05-11 17:09:33.841199: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2021-05-11 17:09:33.841721: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-11 17:09:33.850617: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DESKTOP-I630CDV
2021-05-11 17:09:33.851304: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DESKTOP-I630CDV
2021-05-11 17:09:33.852078: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-05-11 17:09:33.853485: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
INFO:tensorflow:Building speller
WARNING:tensorflow:From C:\Users\yangrui\Desktop\PythonProject\Korean_Speech\las\model.py:346: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2021-05-11T17:09:47Z
INFO:tensorflow:Graph was finalized.
2021-05-11 17:09:48.052221: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
INFO:tensorflow:Restoring parameters from ./data_kss/Kspon_dataset/model_test\model.ckpt-0
2021-05-11 17:09:48.135902: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:196] None of the MLIR optimization passes are enabled (registered 0 passes)
2021-05-11 17:09:48.321843: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at save_restore_v2_ops.cc:205 : Not found: Key BeamSearchDecoderStep/multi_rnn_cell/cell_0_attention/attention_wrapper/lstm_cell_9/bias not found in checkpoint
Traceback (most recent call last):
  File "C:\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\client\session.py", line 1375, in _do_call
    return fn(*args)
  File "C:\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\client\session.py", line 1360, in _run_fn
    target_list, run_metadata)
  File "C:\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\client\session.py", line 1453, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key BeamSearchDecoderStep/multi_rnn_cell/cell_0_attention/attention_wrapper/lstm_cell_9/bias not found in checkpoint
	 [[{{node save/RestoreV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\saver.py", line 1298, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "C:\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\client\session.py", line 968, in run
    run_metadata_ptr)
  File "C:\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\client\session.py", line 1191, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\client\session.py", line 1369, in _do_run
    run_metadata)
  File "C:\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\client\session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key BeamSearchDecoderStep/multi_rnn_cell/cell_0_attention/attention_wrapper/lstm_cell_9/bias not found in checkpoint
	 [[node save/RestoreV2 (defined at \Anaconda3\envs\tf2\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py:1647) ]]

Original stack trace for 'save/RestoreV2':
  File "/Users/yangrui/Desktop/PythonProject/Korean_Speech/eval.py", line 114, in <module>
    main(args)
  File "/Users/yangrui/Desktop/PythonProject/Korean_Speech/eval.py", line 85, in main
    input_fn=lambda: input_fn(
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 467, in evaluate
    name=name)
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 510, in _actual_eval
    return _evaluate()
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 499, in _evaluate
    output_dir=self.eval_dir(name))
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1647, in _evaluate_run
    config=self._session_config)
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\evaluation.py", line 269, in _evaluate_once
    session_creator=session_creator, hooks=hooks) as session:
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1038, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\monitored_session.py", line 749, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1231, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1236, in _create_session
    return self._sess_creator.create_session()
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\monitored_session.py", line 902, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\monitored_session.py", line 660, in create_session
    self._scaffold.finalize()
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\monitored_session.py", line 235, in finalize
    self._saver = training_saver._get_saver_or_default()  # pylint: disable=protected-access
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\saver.py", line 606, in _get_saver_or_default
    saver = Saver(sharded=True, allow_empty=True)
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\saver.py", line 835, in __init__
    self.build()
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\saver.py", line 847, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\saver.py", line 885, in _build
    build_restore=build_restore)
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\saver.py", line 509, in _build_internal
    restore_sequentially, reshape)
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\saver.py", line 388, in _AddShardedRestoreOps
    name="restore_shard"))
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\saver.py", line 335, in _AddRestoreOps
    restore_sequentially)
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\saver.py", line 582, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1510, in restore_v2
    name=name)
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 750, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\framework\ops.py", line 3536, in _create_op_internal
    op_def=op_def)
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\framework\ops.py", line 1990, in __init__
    self._traceback = tf_stack.extract_stack()


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\py_checkpoint_reader.py", line 70, in get_tensor
    self, compat.as_bytes(tensor_str))
RuntimeError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\saver.py", line 1308, in restore
    names_to_keys = object_graph_key_mapping(save_path)
  File "C:\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\saver.py", line 1626, in object_graph_key_mapping
    object_graph_string = reader.get_tensor(trackable.OBJECT_GRAPH_PROTO_KEY)
  File "C:\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\py_checkpoint_reader.py", line 74, in get_tensor
    error_translator(e)
  File "C:\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\py_checkpoint_reader.py", line 35, in error_translator
    raise errors_impl.NotFoundError(None, None, error_message)
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/yangrui/Desktop/PythonProject/Korean_Speech/eval.py", line 114, in <module>
    main(args)
  File "C:/Users/yangrui/Desktop/PythonProject/Korean_Speech/eval.py", line 85, in main
    input_fn=lambda: input_fn(
  File "C:\Anaconda3\envs\tf2\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 467, in evaluate
    name=name)
  File "C:\Anaconda3\envs\tf2\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 510, in _actual_eval
    return _evaluate()
  File "C:\Anaconda3\envs\tf2\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 499, in _evaluate
    output_dir=self.eval_dir(name))
  File "C:\Anaconda3\envs\tf2\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1647, in _evaluate_run
    config=self._session_config)
  File "C:\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\evaluation.py", line 269, in _evaluate_once
    session_creator=session_creator, hooks=hooks) as session:
  File "C:\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1038, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "C:\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\monitored_session.py", line 749, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "C:\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1231, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "C:\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1236, in _create_session
    return self._sess_creator.create_session()
  File "C:\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\monitored_session.py", line 902, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "C:\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\monitored_session.py", line 669, in create_session
    init_fn=self._scaffold.init_fn)
  File "C:\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\session_manager.py", line 295, in prepare_session
    config=config)
  File "C:\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\session_manager.py", line 209, in _restore_checkpoint
    saver.restore(sess, checkpoint_filename_with_path)
  File "C:\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\saver.py", line 1314, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key BeamSearchDecoderStep/multi_rnn_cell/cell_0_attention/attention_wrapper/lstm_cell_9/bias not found in checkpoint
	 [[node save/RestoreV2 (defined at \Anaconda3\envs\tf2\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py:1647) ]]

Original stack trace for 'save/RestoreV2':
  File "/Users/yangrui/Desktop/PythonProject/Korean_Speech/eval.py", line 114, in <module>
    main(args)
  File "/Users/yangrui/Desktop/PythonProject/Korean_Speech/eval.py", line 85, in main
    input_fn=lambda: input_fn(
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 467, in evaluate
    name=name)
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 510, in _actual_eval
    return _evaluate()
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 499, in _evaluate
    output_dir=self.eval_dir(name))
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1647, in _evaluate_run
    config=self._session_config)
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\evaluation.py", line 269, in _evaluate_once
    session_creator=session_creator, hooks=hooks) as session:
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1038, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\monitored_session.py", line 749, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1231, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1236, in _create_session
    return self._sess_creator.create_session()
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\monitored_session.py", line 902, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\monitored_session.py", line 660, in create_session
    self._scaffold.finalize()
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\monitored_session.py", line 235, in finalize
    self._saver = training_saver._get_saver_or_default()  # pylint: disable=protected-access
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\saver.py", line 606, in _get_saver_or_default
    saver = Saver(sharded=True, allow_empty=True)
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\saver.py", line 835, in __init__
    self.build()
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\saver.py", line 847, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\saver.py", line 885, in _build
    build_restore=build_restore)
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\saver.py", line 509, in _build_internal
    restore_sequentially, reshape)
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\saver.py", line 388, in _AddShardedRestoreOps
    name="restore_shard"))
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\saver.py", line 335, in _AddRestoreOps
    restore_sequentially)
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\saver.py", line 582, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1510, in restore_v2
    name=name)
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 750, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\framework\ops.py", line 3536, in _create_op_internal
    op_def=op_def)
  File "\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\framework\ops.py", line 1990, in __init__
    self._traceback = tf_stack.extract_stack()


Process finished with exit code 1

```

**Part of my code:**
```
import tensorflow as tf
import numpy as np
from tensorflow.python.util import nest
import tensorflow_addons as tfa

from las.ops import lstm_cell
from las.ops import pyramidal_bilstm
# assert tf.executing_eagerly()
__all__ = [
    'listener',
    'speller',
]


"""Reference: https://github.com/tensorflow/nmt/blob/master/nmt/gnmt_model.py"""


class AttentionMultiCell(tf.keras.layers.StackedRNNCells):
# class AttentionMultiCell(tf.compat.v1.nn.rnn_cell.MultiRNNCell):
    """A MultiCell with attention style."""

    def __init__(self, attention_cell, cells, use_new_attention=False):
        """Creates a AttentionMultiCell.
        Args:
          attention_cell: An instance of AttentionWrapper.
          cells: A list of RNNCell wrapped with AttentionInputWrapper.
          use_new_attention: Whether to use the attention generated from current
            step bottom layer's output. Default is False.
        """
        cells = [attention_cell] + cells
        self.use_new_attention = use_new_attention
        super(AttentionMultiCell, self).__init__(
            cells)

    def __call__(self, inputs, state, training=False, scope=None):
        """Run the cell with bottom layer's attention copied to all upper layers."""
        if not nest.is_sequence(state):
            raise ValueError(
                "Expected state to be a tuple of length %d, but received: %s"
                % (len(self.state_size), state))

        with tf.compat.v1.variable_scope(scope or "multi_rnn_cell"):
            new_states = []

            with tf.compat.v1.variable_scope("cell_0_attention"):
                attention_cell = self.cells[0]
                attention_state = state[0]
                cur_inp, new_attention_state = attention_cell(
                    inputs, attention_state)

                new_states.append(new_attention_state)

            for i in range(1, len(self.cells)):
                with tf.compat.v1.variable_scope("cell_%d" % i):

                    cell = self.cells[i]
                    cur_state = state[i]

                    if self.use_new_attention:
                        cur_inp = tf.concat(
                            [cur_inp, new_attention_state.attention], -1)
                    else:
                        cur_inp = tf.concat(
                            [cur_inp, attention_state.attention], -1)

                    cur_inp, new_state = cell(cur_inp, cur_state)
                    new_states.append(new_state)
        return cur_inp, new_states


class CustomAttention(tfa.seq2seq.LuongAttention):
    def __init__(self,
                 num_units,
                 memory,
                 memory_sequence_length=None,
                 scale=False,
                 probability_fn=None,
                 score_mask_value=None,
                 dtype=None,
                 name="CustomAttention"):

        super(CustomAttention, self).__init__(
            num_units=num_units,
            memory=memory,
            memory_sequence_length=memory_sequence_length,
            scale=scale,
            probability_fn=probability_fn,
            score_mask_value=score_mask_value,
            dtype=dtype,
            name=name)

        self._query_layer = tf.compat.v1.layers.Dense(
            num_units, name='query_layer', use_bias=False, dtype=dtype)

        self._keys = tf.nn.relu(self.keys)

    def __call__(self, query, state):
        processed_query = tf.nn.relu(self.query_layer(query))

        return super(CustomAttention, self).__call__(processed_query, state)


def listener(encoder_inputs,
             source_sequence_length,
             mode,
             hparams):

    if hparams['use_pyramidal']:
        return pyramidal_bilstm(encoder_inputs, source_sequence_length, mode, hparams)
    else:
        forward_cell_list, backward_cell_list = [], []
        for layer in range(hparams['num_layers']):
            with tf.compat.v1.variable_scope('fw_cell_{}'.format(layer)):
                cell = lstm_cell(hparams['num_units'], hparams['dropout'], mode)

            forward_cell_list.append(cell)

            with tf.compat.v1.variable_scope('bw_cell_{}'.format(layer)):
                cell = lstm_cell(hparams['num_units'], hparams['dropout'], mode)

            backward_cell_list.append(cell)

        forward_cell = tf.keras.layers.StackedRNNCells(forward_cell_list)
        backward_cell = tf.keras.layers.StackedRNNCells(backward_cell_list)

        encoder_outputs, encoder_state = tf.keras.layers.Bidirectional(
            forward_cell,
            backward_cell,
            encoder_inputs,
            sequence_length=source_sequence_length,
            dtype=tf.float32)
        # outputs:[batch_size, max_time, forward_cell.output_size]
        # [batch_size, max_time, hidden_size]

        encoder_outputs = tf.concat(encoder_outputs, -1)

        return (encoder_outputs, source_sequence_length), encoder_state


def attend(encoder_outputs,
           source_sequence_length,
           mode,
           hparams):

    memory = encoder_outputs

    if hparams['attention_type'] == 'luong':
        attention_fn = tfa.seq2seq.LuongAttention
    elif hparams['attention_type'] == 'bahdanau':
        attention_fn = tfa.seq2seq.BahdanauAttention
    elif hparams['attention_type'] == 'custom':
        attention_fn = CustomAttention

    attention_mechanism = attention_fn(
        hparams['num_units'], memory, source_sequence_length)

    cell_list = []
    for layer in range(hparams['num_layers']):

        with tf.compat.v1.variable_scope('decoder_cell_'.format(layer)):
            cell = lstm_cell(hparams['num_units'], hparams['dropout'], mode)

        # cell = lstm_cell(hparams['num_units'], hparams['dropout'], mode)
        cell_list.append(cell)

    alignment_history = (mode != tf.estimator.ModeKeys.TRAIN)

    if hparams['bottom_only']: # False
        #  Only wrap the bottom layer with the attention mechanism.

        attention_cell = cell_list.pop(0)
        # attention_cell = tf.cast(attention_cell, dtype='float32')
        # attention_mechanism = tf.cast(attention_mechanism, dtype='float32')
        attention_cell = tfa.seq2seq.AttentionWrapper(
            attention_cell, attention_mechanism,
            attention_layer_size=hparams['attention_layer_size'],
            alignment_history=alignment_history)

        decoder_cell = AttentionMultiCell(attention_cell, cell_list)
    else:
        decoder_cell = tf.keras.layers.StackedRNNCells(cell_list)

        decoder_cell = tfa.seq2seq.AttentionWrapper(
            decoder_cell, attention_mechanism,
            attention_layer_size=hparams['attention_layer_size'],
            alignment_history=alignment_history)

    return decoder_cell


def speller(encoder_outputs,
            encoder_state,
            decoder_inputs,
            source_sequence_length,
            target_sequence_length,
            mode,
            hparams):

    batch_size = tf.shape(input=encoder_outputs)[0]
    beam_width = hparams['beam_width']

    if mode == tf.estimator.ModeKeys.PREDICT and beam_width > 0:
        encoder_outputs = tfa.seq2seq.tile_batch(
            encoder_outputs, multiplier=beam_width)
        source_sequence_length = tfa.seq2seq.tile_batch(
            source_sequence_length, multiplier=beam_width)
        encoder_state = tfa.seq2seq.tile_batch(
            encoder_state, multiplier=beam_width)
        batch_size = batch_size * beam_width


    if mode == tf.estimator.ModeKeys.EVAL and beam_width > 0:
        encoder_outputs = tfa.seq2seq.tile_batch(
            encoder_outputs, multiplier=beam_width)
        source_sequence_length = tfa.seq2seq.tile_batch(
            source_sequence_length, multiplier=beam_width)
        encoder_state = tfa.seq2seq.tile_batch(
            encoder_state, multiplier=beam_width)
        batch_size = batch_size * beam_width

    def embedding_fn(ids):
        # pass callable object to avoid OOM when using one-hot encoding
        if hparams['embedding_size'] != 0:
            target_embedding = tf.compat.v1.get_variable(
                'target_embedding', [
                    hparams['target_vocab_size'], hparams['embedding_size']],
                dtype=tf.float32, initializer=tf.compat.v1.keras.initializers.VarianceScaling(scale=1.0, mode="fan_avg", distribution="uniform"))

            return tf.nn.embedding_lookup(params=target_embedding, ids=ids)
        else:
            return tf.one_hot(ids, hparams['target_vocab_size'])

    decoder_cell = attend(
        encoder_outputs, source_sequence_length, mode, hparams)

    projection_layer = tf.keras.layers.Dense(
        hparams['target_vocab_size'], use_bias=True, name='projection_layer')

    if hparams['pass_hidden_state'] and hparams['bottom_only']:
        initial_state = tuple(
            zs.clone(cell_state=es)
            if isinstance(zs, tfa.seq2seq.AttentionWrapperState) else es
            for zs, es in zip(
                decoder_cell.get_initial_state(batch_size=batch_size, dtype=tf.float32), encoder_state))
    else:
        initial_state = decoder_cell.get_initial_state(batch_size=batch_size, dtype=tf.float32)

    maximum_iterations = None
    if mode != tf.estimator.ModeKeys.TRAIN:
        max_source_length = tf.reduce_max(input_tensor=source_sequence_length)
        maximum_iterations = tf.cast(tf.round(tf.cast(
            max_source_length, dtype=tf.float32) * hparams['decoding_length_factor']), dtype=tf.int32)

    if mode == tf.estimator.ModeKeys.TRAIN:
        decoder_inputs = embedding_fn(decoder_inputs)
        decay_steps = hparams['decay_steps']
        iter_num = tf.compat.v1.train.get_global_step()
        inverse_probability = tf.compat.v1.train.polynomial_decay(
            1.0, iter_num, decay_steps, 0.6)
        sampling_probability = 1.0 - inverse_probability
        if hparams['sampling_probability']:
            helper = tfa.seq2seq.ScheduledEmbeddingTrainingSampler(
                sampling_probability=sampling_probability,
                embedding_fn=embedding_fn
            )
        else:
            helper = tfa.seq2seq.TrainingSampler()

        decoder = tfa.seq2seq.BasicDecoder(
            cell=decoder_cell,
            sampler=helper,
            output_layer=projection_layer,
            maximum_iterations=maximum_iterations
        )
     
        decoder_outputs, final_context_state, final_sequence_length = tfa.seq2seq.dynamic_decode(
            decoder, training=True, decoder_init_input=decoder_inputs, decoder_init_kwargs={
                'initial_state': initial_state, 'sequence_length': target_sequence_length
            })

    elif mode == tf.estimator.ModeKeys.PREDICT and beam_width > 0:
        start_tokens = tf.fill(
            [tf.compat.v1.div(batch_size, beam_width)], hparams['sos_id'])

        decoder = tfa.seq2seq.BeamSearchDecoder(
            cell=decoder_cell,
            embedding_fn=embedding_fn,
            beam_width=beam_width,
            output_layer=projection_layer,
            maximum_iterations=maximum_iterations
        )
        decoder_outputs, final_context_state, final_sequence_length = tfa.seq2seq.dynamic_decode(
            decoder, decoder_inputs=embedding_fn(decoder_inputs),
            training=False, decoder_init_kwargs={
                'start_tokens': start_tokens, 'end_token': hparams['eos_id'],
                'initial_state': initial_state
            })
    else:
        '''
        start_tokens = tf.fill([batch_size], hparams.sos_id)

        helper = tf.contrib.seq2seq.GreedyEmbeddingHelper(
            embedding_fn, start_tokens, hparams.eos_id)
        
        decoder = tf.contrib.seq2seq.BasicDecoder(
            decoder_cell, helper, initial_state, output_layer=projection_layer)
        '''

        start_tokens = tf.fill(
            [tf.compat.v1.div(batch_size, beam_width)], hparams['sos_id'])

        decoder = tfa.seq2seq.BeamSearchDecoder(
            cell=decoder_cell,
            embedding_fn=embedding_fn,
            beam_width=beam_width,
            output_layer=projection_layer,
            maximum_iterations=maximum_iterations
        )

       

        decoder_outputs, final_context_state, final_sequence_length = tfa.seq2seq.dynamic_decode(
            decoder, decoder_inputs=embedding_fn(decoder_inputs),
            training=False, decoder_init_kwargs={
                'start_tokens':start_tokens,
                'end_token':hparams['eos_id'],
                'initial_state': initial_state
            })

    return decoder_outputs, final_context_state, final_sequence_length


```
Besides,  I use tf.estimator.Estimator for training and evaluation.

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
