### ISSUE TITLE
AttributeError: 'MirroredStrategy' object has no attribute 'experimental_run_v2'

### ISSUE THREAD

**Issue by ucasiggcas** [tensorflow/tensorflow#49187]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (Linux Ubuntu 18.04):
- TensorFlow installed from (pip3):
- TensorFlow version (use command below):
`pip3 install tensorflow-gpu==2.4.1`
- Python version:3.8.0
- CUDA/cuDNN version: cuda11.3 driver 465.19
- GPU model and memory: eight 3090 cards

codes as the [URL](https://github.com/tensorflow/docs/blob/master/site/en/tutorials/distribute/custom_training.ipynb)
never modified

bugs
```
2021-05-14 18:00:34.332244: W tensorflow/core/grappler/optimizers/data/auto_shard.cc:656] In AUTO-mode, and switching to DATA-based sharding, instead of FILE-based sharding as we cannot find appropriate reader dataset op(s) to shard. Error: Found an unshardable source dataset: name: "TensorSliceDataset/_2"
op: "TensorSliceDataset"
input: "Placeholder/_0"
input: "Placeholder/_1"
attr {
  key: "Toutput_types"
  value {
    list {
      type: DT_FLOAT
      type: DT_UINT8
    }
  }
}
attr {
  key: "output_shapes"
  value {
    list {
      shape {
        dim {
          size: 28
        }
        dim {
          size: 28
        }
        dim {
          size: 1
        }
      }
      shape {
      }
    }
  }
}

2021-05-14 18:00:34.366102: W tensorflow/core/grappler/optimizers/data/auto_shard.cc:656] In AUTO-mode, and switching to DATA-based sharding, instead of FILE-based sharding as we cannot find appropriate reader dataset op(s) to shard. Error: Found an unshardable source dataset: name: "TensorSliceDataset/_2"
op: "TensorSliceDataset"
input: "Placeholder/_0"
input: "Placeholder/_1"
attr {
  key: "Toutput_types"
  value {
    list {
      type: DT_FLOAT
      type: DT_UINT8
    }
  }
}
attr {
  key: "output_shapes"
  value {
    list {
      shape {
        dim {
          size: 28
        }
        dim {
          size: 28
        }
        dim {
          size: 1
        }
      }
      shape {
      }
    }
  }
}

2021-05-14 18:00:35.243992: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-05-14 18:00:35.262293: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2500000000 Hz
Traceback (most recent call last):
  File "/data/prod/xulm1/custom_training.py", line 113, in <module>
    total_loss += distributed_train_step(x)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 871, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 725, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 2969, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 3196, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 634, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/func_graph.py", line 977, in wrapper
    raise e.ag_error_metadata.to_exception(e)
AttributeError: in user code:

    /data/prod/xulm1/custom_training.py:99 distributed_train_step  *
        per_replica_losses = strategy.experimental_run_v2(train_step,

    AttributeError: 'MirroredStrategy' object has no attribute 'experimental_run_v2'


```

how to deal with this ?
thx

**Comment by ucasiggcas** [comment]
I found that v2 wasn't the Attribute, as below
```
>>> strategy.ex
strategy.experimental_distribute_dataset(
strategy.experimental_distribute_datasets_from_function(
strategy.experimental_distribute_values_from_function(
strategy.experimental_local_results(
**strategy.experimental_run(**
```
and i use the last 
but got another bug
```
Traceback (most recent call last):
  File "/data/prod/xulm1/custom_training.py", line 113, in <module>
    total_loss += distributed_train_step(x)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 871, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 725, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 2969, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 3196, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 634, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/func_graph.py", line 977, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    /data/prod/xulm1/custom_training.py:99 distributed_train_step  *
        per_replica_losses = strategy.experimental_run(train_step,

    TypeError: experimental_run() got an unexpected keyword argument 'args'

```

**Comment by abhilash1910** [comment]
Hi @ucasiggcas ,I think that ```mirroredstrategy.experimental_run_v2```  has been deprecated since Tensorflow 2.2 .This can found from the release pages:
https://github.com/tensorflow/tensorflow/blob/93360e5c3bb1c7f3d5de2267d564bc8c77dfe3de/RELEASE.md
It has been renamed to ```mirroredstrategy.run``` method as specified in this segment:

```Deprecated experimental_run_v2 method for distribution strategies and renamed the method run as it is no longer experimental.```

 Raised a PR  #49219  for logging messages.

**Comment by ymodak** [comment]
On a side note for using gpus with TF 2.4 pre built binary compatible cuda version is 11.0 and cudnn 8.0

**Comment by ucasiggcas** [comment]
ok
thx
