### ISSUE TITLE
Undefined symbol zungqr_

### ISSUE THREAD

**Issue by Nytish** [tensorflow/tensorflow#49366]
Traceback (most recent call last):
  File "real_time_object_detection.py", line 2, in <module>
    from imutils.video import VideoStream
  File "/var/rootdirs/home/root/tflite/tflite-env/lib/python3.8/site-packages/imutils/__init__.py", line 8, in <module>
    from .convenience import translate
  File "/var/rootdirs/home/root/tflite/tflite-env/lib/python3.8/site-packages/imutils/convenience.py", line 5, in <module>
    import numpy as np
  File "/var/rootdirs/home/root/tflite/tflite-env/lib/python3.8/site-packages/numpy/__init__.py", line 148, in <module>
    from . import lib
  File "/var/rootdirs/home/root/tflite/tflite-env/lib/python3.8/site-packages/numpy/lib/__init__.py", line 25, in <module>
    from .index_tricks import *
  File "/var/rootdirs/home/root/tflite/tflite-env/lib/python3.8/site-packages/numpy/lib/index_tricks.py", line 12, in <module>
    import numpy.matrixlib as matrixlib
  File "/var/rootdirs/home/root/tflite/tflite-env/lib/python3.8/site-packages/numpy/matrixlib/__init__.py", line 4, in <module>
    from .defmatrix import *
  File "/var/rootdirs/home/root/tflite/tflite-env/lib/python3.8/site-packages/numpy/matrixlib/defmatrix.py", line 11, in <module>
    from numpy.linalg import matrix_power
  File "/var/rootdirs/home/root/tflite/tflite-env/lib/python3.8/site-packages/numpy/linalg/__init__.py", line 73, in <module>
    from .linalg import *
  File "/var/rootdirs/home/root/tflite/tflite-env/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 33, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg
ImportError: /var/rootdirs/home/root/tflite/tflite-env/lib/python3.8/site-packages/numpy/linalg/lapack_lite.cpython-38-arm-linux-gnueabi.so: undefined symbol: zungqr_

**Comment by tilakrayal** [comment]
@Nytish,

We see that the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced] or if possible share a colab gist with the issue reported.

Thanks!

**Comment by Nytish** [comment]
Steps
1.Installed lapack on system 
2. Try to run my Python code
3. Got this error as shown above

**Comment by tilakrayal** [comment]
@Nytish,

We see that you are using tf version 1.0, 1.x is not actively supported, please update to 2.x and let us know if you are using same issue.

Also looks like your numpy installation is broken. Numpy appears installed by linked incorrectly to lapack.
Thanks!

**Comment by Nytish** [comment]
How to upgrade tf to 2.x

Numpy version 1.17.4 i installed

**Comment by tilakrayal** [comment]
@Nytish ,

Can you please refer to this [link](https://www.tensorflow.org/install) for installing tensorflow latest version.

Thanks!
