### ISSUE TITLE
Training a Model

### ISSUE THREAD

**Issue by Florent4223** [tensorflow/tensorflow#49464]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.5.0
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: NC
- GPU model and memory: KVM

**Describe the problem**
I'm trying to train a new model. I am the official Tensorflow tutorial. nevertheless I block towards the end on the training of the model (script : model_main_tf2.py )
`python model_main_tf2.py --model_dir=models/my_ssd_resnet50_v1_fpn --pipeline_config_path=models/my_ssd_resnet50_v1_fpn/pipeline.config
2021-05-21 15:27:42.920609: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-21 15:27:42.921036: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-21 15:27:47.225166: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-21 15:27:47.225469: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-21 15:27:47.225561: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (reco-objets): /proc/driver/nvidia/version does not exist
2021-05-21 15:27:47.226220: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:tensorflow:There are non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce.
W0521 15:27:47.227876 139889528895296 cross_device_ops.py:1387] There are non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce.
WARNING:tensorflow:Collective ops is not configured at program startup. Some performance features may not be enabled.
W0521 15:27:47.228754 139889528895296 mirrored_strategy.py:379] Collective ops is not configured at program startup. Some performance features may not be enabled.
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',)
I0521 15:27:47.234278 139889528895296 mirrored_strategy.py:369] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',)
INFO:tensorflow:Maybe overwriting train_steps: None
I0521 15:27:47.242940 139889528895296 config_util.py:552] Maybe overwriting train_steps: None
INFO:tensorflow:Maybe overwriting use_bfloat16: False
I0521 15:27:47.243463 139889528895296 config_util.py:552] Maybe overwriting use_bfloat16: False
WARNING:tensorflow:From /home/sic/.local/lib/python3.6/site-packages/object_detection/model_lib_v2.py:551: StrategyBase.experimental_distribute_datasets_from_function (from tensorflow.python.distribute.distribute_lib) is deprecated and will be removed in a future version.
Instructions for updating:
rename to distribute_datasets_from_function
W0521 15:27:47.352285 139889528895296 deprecation.py:336] From /home/sic/.local/lib/python3.6/site-packages/object_detection/model_lib_v2.py:551: StrategyBase.experimental_distribute_datasets_from_function (from tensorflow.python.distribute.distribute_lib) is deprecated and will be removed in a future version.
Instructions for updating:
rename to distribute_datasets_from_function
Traceback (most recent call last):
  File "model_main_tf2.py", line 113, in <module>
    tf.compat.v1.app.run()
  File "/home/sic/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/sic/.local/lib/python3.6/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/sic/.local/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "model_main_tf2.py", line 110, in main
    record_summaries=FLAGS.record_summaries)
  File "/home/sic/.local/lib/python3.6/site-packages/object_detection/model_lib_v2.py", line 551, in train_loop
    train_dataset_fn)
  File "/home/sic/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 337, in new_func
    return func(*args, **kwargs)
  File "/home/sic/.local/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py", line 1168, in experimental_distribute_datasets_from_function
    return self.distribute_datasets_from_function(dataset_fn, options)
  File "/home/sic/.local/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py", line 1160, in distribute_datasets_from_function
    dataset_fn, options)
  File "/home/sic/.local/lib/python3.6/site-packages/tensorflow/python/distribute/mirrored_strategy.py", line 597, in _distribute_datasets_from_function
    options)
  File "/home/sic/.local/lib/python3.6/site-packages/tensorflow/python/distribute/input_lib.py", line 168, in get_distributed_datasets_from_function
    input_contexts, dataset_fn, options)
  File "/home/sic/.local/lib/python3.6/site-packages/tensorflow/python/distribute/input_lib.py", line 1566, in __init__
    input_contexts, self._input_workers, dataset_fn))
  File "/home/sic/.local/lib/python3.6/site-packages/tensorflow/python/distribute/input_lib.py", line 2301, in _create_datasets_from_function_with_input_context
    dataset = dataset_fn(ctx)
  File "/home/sic/.local/lib/python3.6/site-packages/object_detection/model_lib_v2.py", line 546, in train_dataset_fn
    input_context=input_context)
  File "/home/sic/.local/lib/python3.6/site-packages/object_detection/inputs.py", line 898, in train_input
    reduce_to_frame_fn=reduce_to_frame_fn)
  File "/home/sic/.local/lib/python3.6/site-packages/object_detection/builders/dataset_builder.py", line 210, in build
    decoder = decoder_builder.build(input_reader_config)
  File "/home/sic/.local/lib/python3.6/site-packages/object_detection/builders/decoder_builder.py", line 64, in build
    load_keypoint_depth_features=input_reader_config
  File "/home/sic/.local/lib/python3.6/site-packages/object_detection/data_decoders/tf_example_decoder.py", line 416, in __init__
    default_value=''),
  File "/home/sic/.local/lib/python3.6/site-packages/object_detection/data_decoders/tf_example_decoder.py", line 89, in __init__
    label_map_proto_file, use_display_name=False)
  File "/home/sic/.local/lib/python3.6/site-packages/object_detection/utils/label_map_util.py", line 201, in get_label_map_dict
    label_map = load_labelmap(label_map_path_or_proto)
  File "/home/sic/.local/lib/python3.6/site-packages/object_detection/utils/label_map_util.py", line 168, in load_labelmap
    label_map_string = fid.read()
  File "/home/sic/.local/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 117, in read
    self._preread_check()
  File "/home/sic/.local/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 80, in _preread_check
    compat.path_to_str(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: PATH_TO_BE_CONFIGURED; No such file or directory
`
do you have an idea?

I confirm that I have the folder where the file is present:
model_dir=models/my_ssd_resnet50_v1_fpn 
pipeline_config_path=models/my_ssd_resnet50_v1_fpn/pipeline.config
 

thanks

**Comment by UsharaniPagadala** [comment]
@Florent4223 

Looking at the error log, seems like this is similar to issues [#3762](https://github.com/tensorflow/models/issues/3762), [#3954](https://github.com/tensorflow/models/issues/3954).Please let us know if you still face the problem.Thanks

**Comment by Florent4223** [comment]
Hello
Thank you for the feedback. I confirm that the anomaly reported in the
topics indicated are different. The 1st touches another script (which
I did successfully), the 2nd touches the same script, but I use the
correct command (in any case the one indicated on the Tensorflow site)

The problem therefore remains

Thanks


Le ven. 21 mai 2021 à 16:26, UsharaniPagadala ***@***.***> a
écrit :

**Comment by UsharaniPagadala** [comment]
@Florent4223 

Could you please share the standalone code/colab gist.Thanks

**Comment by Florent4223** [comment]
sorry  I have find the error, my erro was in pipeline.config

but after starting the training, I never indicated the 100%

at the end I stop the process

[code]
WARNING:tensorflow:Unresolved object in checkpoint:
(root).model._box_predictor._base_tower_layers_for_heads.class_predictions_with_background.4.10.beta
W0528 11:36:52.936134 140000602519360 util.py:162] Unresolved object
in checkpoint: (root).model._box_predictor._base_tower_layers_for_heads.class_predictions_with_background.4.10.beta
WARNING:tensorflow:Unresolved object in checkpoint:
(root).model._box_predictor._base_tower_layers_for_heads.class_predictions_with_background.4.10.moving_mean
W0528 11:36:52.936249 140000602519360 util.py:162] Unresolved object
in checkpoint: (root).model._box_predictor._base_tower_layers_for_heads.class_predictions_with_background.4.10.moving_mean
WARNING:tensorflow:Unresolved object in checkpoint:
(root).model._box_predictor._base_tower_layers_for_heads.class_predictions_with_background.4.10.moving_variance
W0528 11:36:52.936391 140000602519360 util.py:162] Unresolved object
in checkpoint: (root).model._box_predictor._base_tower_layers_for_heads.class_predictions_with_background.4.10.moving_variance
WARNING:tensorflow:A checkpoint was restored (e.g.
tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not
all checkpointed values were used. See above for specific issues. Use
expect_partial() on the load status object, e.g.
tf.train.Checkpoint.restore(...).expect_partial(), to silence these
warnings, or use assert_consumed() to make the check explicit. See
https://www.tensorflow.org/guide/checkpoint#loading_mechanics for
details.
W0528 11:36:52.936520 140000602519360 util.py:170] A checkpoint was
restored (e.g. tf.train.Checkpoint.restore or
tf.keras.Model.load_weights) but not all checkpointed values were
used. See above for specific issues. Use expect_partial() on the load
status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(),
to silence these warnings, or use assert_consumed() to make the check
explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics
for details.
WARNING:tensorflow:From
/home/sic/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py:602:
calling map_fn_v2 (from tensorflow.python.ops.map_fn) with dtype is
deprecated and will be removed in a future version.
Instructions for updating:
Use fn_output_signature instead
W0528 11:37:12.378952 139997839599360 deprecation.py:534] From
/home/sic/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py:602:
calling map_fn_v2 (from tensorflow.python.ops.map_fn) with dtype is
deprecated and will be removed in a future version.
Instructions for updating:
Use fn_output_signature instead
Processus arrêté

[/code]



Le ven. 28 mai 2021 à 10:19, Florent Decitre ***@***.***> a
écrit :

**Comment by rmothukuru** [comment]
@Florent4223,
Can you please help us to reproduce your issue so that we can try to resolve it? Thanks!

**Comment by Florent4223** [comment]
Hello
Thank you for the feedback.
I follow the procedure of the site https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html

I specify that beforehand I installed all the required packages + tensorflow + TF API

1) I created the same folder architecture as the doc
2 ) I found some images of my object, and I annotated them with labelimg and divided between test and training
3) I created the label map
4) Convert *.xml to *.record wicth python generate_tfrecord.py
5) I recovered ssd_resnet50_v1_fpn_640x640_coco17_tpu-8  and configure (it was my previous error I had configured it incorrectly)
6) I now want to train the model on my new object with the model_main_tf2.py script

This "training" lasts a few seconds and stops by itself

I hope I answered the question and I remain at your disposal for any questions thank you

**Comment by Florent4223** [comment]
initiale command:

`cardio@cardiohp:~/Tensorflow/workspace/training_demo$ python model_main_tf2.py --model_dir=models/my_ssd_resnet50_v1_fpn --pipeline_config_path=models/my_ssd_resnet50_v1_fpn/pipeline.config
`
logs:
`
2021-06-09 11:38:53.793053: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-06-09 11:38:53.793085: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-06-09 11:38:56.018428: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type
2021-06-09 11:38:56.018469: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-06-09 11:38:56.018508: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (cardiohp): /proc/driver/nvidia/version does not exist
2021-06-09 11:38:56.018786: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:tensorflow:There are non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce.
W0609 11:38:56.019701 140657181075264 cross_device_ops.py:1387] There are non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce.
WARNING:tensorflow:Collective ops is not configured at program startup. Some performance features may not be enabled.
W0609 11:38:56.019944 140657181075264 mirrored_strategy.py:379] Collective ops is not configured at program startup. Some performance features may not be enabled.
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',)
I0609 11:38:56.022413 140657181075264 mirrored_strategy.py:369] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',)
INFO:tensorflow:Maybe overwriting train_steps: None
I0609 11:38:56.026477 140657181075264 config_util.py:552] Maybe overwriting train_steps: None
INFO:tensorflow:Maybe overwriting use_bfloat16: False
I0609 11:38:56.026618 140657181075264 config_util.py:552] Maybe overwriting use_bfloat16: False
WARNING:tensorflow:From /home/cardio/.local/lib/python3.8/site-packages/object_detection/model_lib_v2.py:557: StrategyBase.experimental_distribute_datasets_from_function (from tensorflow.python.distribute.distribute_lib) is deprecated and will be removed in a future version.
Instructions for updating:
rename to distribute_datasets_from_function
W0609 11:38:56.052769 140657181075264 deprecation.py:330] From /home/cardio/.local/lib/python3.8/site-packages/object_detection/model_lib_v2.py:557: StrategyBase.experimental_distribute_datasets_from_function (from tensorflow.python.distribute.distribute_lib) is deprecated and will be removed in a future version.
Instructions for updating:
rename to distribute_datasets_from_function
INFO:tensorflow:Reading unweighted datasets: ['annotations/train.record']
I0609 11:38:56.059633 140657181075264 dataset_builder.py:163] Reading unweighted datasets: ['annotations/train.record']
INFO:tensorflow:Reading record datasets for input file: ['annotations/train.record']
I0609 11:38:56.059836 140657181075264 dataset_builder.py:80] Reading record datasets for input file: ['annotations/train.record']
INFO:tensorflow:Number of filenames to read: 1
I0609 11:38:56.059911 140657181075264 dataset_builder.py:81] Number of filenames to read: 1
WARNING:tensorflow:num_readers has been reduced to 1 to match input file shards.
W0609 11:38:56.059973 140657181075264 dataset_builder.py:87] num_readers has been reduced to 1 to match input file shards.
WARNING:tensorflow:From /home/cardio/.local/lib/python3.8/site-packages/object_detection/builders/dataset_builder.py:101: parallel_interleave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.experimental_deterministic`.
W0609 11:38:56.067752 140657181075264 deprecation.py:330] From /home/cardio/.local/lib/python3.8/site-packages/object_detection/builders/dataset_builder.py:101: parallel_interleave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.experimental_deterministic`.
WARNING:tensorflow:From /home/cardio/.local/lib/python3.8/site-packages/object_detection/builders/dataset_builder.py:236: DatasetV1.map_with_legacy_function (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.map()
W0609 11:38:56.105435 140657181075264 deprecation.py:330] From /home/cardio/.local/lib/python3.8/site-packages/object_detection/builders/dataset_builder.py:236: DatasetV1.map_with_legacy_function (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.map()
WARNING:tensorflow:From /home/cardio/.local/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py:206: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
W0609 11:39:03.725294 140657181075264 deprecation.py:330] From /home/cardio/.local/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py:206: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
WARNING:tensorflow:From /home/cardio/.local/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py:206: sample_distorted_bounding_box (from tensorflow.python.ops.image_ops_impl) is deprecated and will be removed in a future version.
Instructions for updating:
`seed2` arg is deprecated.Use sample_distorted_bounding_box_v2 instead.
W0609 11:39:07.325738 140657181075264 deprecation.py:330] From /home/cardio/.local/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py:206: sample_distorted_bounding_box (from tensorflow.python.ops.image_ops_impl) is deprecated and will be removed in a future version.
Instructions for updating:
`seed2` arg is deprecated.Use sample_distorted_bounding_box_v2 instead.
WARNING:tensorflow:From /home/cardio/.local/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py:464: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
W0609 11:39:09.254939 140657181075264 deprecation.py:330] From /home/cardio/.local/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py:464: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
2021-06-09 11:39:11.756661: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-06-09 11:39:11.784659: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2595000000 Hz
2021-06-09 11:39:12.178699: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 39321600 exceeds 10% of free system memory.
2021-06-09 11:39:12.206940: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 39321600 exceeds 10% of free system memory.
2021-06-09 11:39:12.213958: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 39321600 exceeds 10% of free system memory.
2021-06-09 11:39:12.227869: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 39321600 exceeds 10% of free system memory.
2021-06-09 11:39:12.238191: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 39321600 exceeds 10% of free system memory.
/home/cardio/.local/lib/python3.8/site-packages/tensorflow/python/keras/backend.py:435: UserWarning: `tf.keras.backend.set_learning_phase` is deprecated and will be removed after 2020-10-11. To update it, simply pass a True/False value to the `training` argument of the `__call__` method of your layer or model.
  warnings.warn('`tf.keras.backend.set_learning_phase` is deprecated and '
WARNING:tensorflow:From /home/cardio/.local/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py:602: calling map_fn_v2 (from tensorflow.python.ops.map_fn) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Use fn_output_signature instead
W0609 11:39:57.860589 140653728098048 deprecation.py:528] From /home/cardio/.local/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py:602: calling map_fn_v2 (from tensorflow.python.ops.map_fn) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Use fn_output_signature instead
Processus arrêté
`

thanks for your answer

**Comment by mihaimaruseac** [comment]
Can you try with the latest `tf-nightly`?

**Comment by tilakrayal** [comment]
@Florent4223 ,
As commented please try tf-nightly or tf v2.6 and let us know if the issue still persists.Thanks!
