### ISSUE TITLE
ValueError: `handle` is not available outside the replica context or a `tf.distribute.Strategy.update()` call.

### ISSUE THREAD

**Issue by all-over-the-place** [tensorflow/tensorflow#49521]
<em>This is a issue similar to the issues #35226 and #36392.</em>

**System information**
- I am testing  a code available at  https://github.com/hehefan/PointRNN on my system(which is a slurm cluster):
- TensorFlow version (use command below): 2.3.0
- Python version: 3.8.3
- CUDA/cuDNN version: 10.1 / 7.6

**Traceback**
```
`Use `tf.keras.layers.Conv1D` instead.
Traceback (most recent call last):
  File "dist_arg.py", line 119, in <module>
    model = create_model()
  File "dist_arg.py", line 106, in create_model
    model = Model(batch_size=args.batch_size,
  File "/home/srijan.singh/convert_PointRNN_2/models/dist_arg.py", line 158, in __init__
    gradients = tape.gradient(self.loss, params)
  File "/home/srijan.singh/.local/lib/python3.8/site-packages/tensorflow/python/eager/backprop.py", line 1051, in gradient
    flat_sources = [_handle_or_self(x) for x in flat_sources]
  File "/home/srijan.singh/.local/lib/python3.8/site-packages/tensorflow/python/eager/backprop.py", line 1051, in <listcomp>
    flat_sources = [_handle_or_self(x) for x in flat_sources]
  File "/home/srijan.singh/.local/lib/python3.8/site-packages/tensorflow/python/eager/backprop.py", line 729, in _handle_or_self
    return x.handle
  File "/home/srijan.singh/.local/lib/python3.8/site-packages/tensorflow/python/distribute/values.py", line 571, in handle
    raise ValueError("`handle` is not available outside the replica context"
ValueError: `handle` is not available outside the replica context or a `tf.distribute.Strategy.update()` call.`
```
**dist.arg.py**
```
mport os
import sys
import io
from datetime import datetime
import argparse
import numpy as np
from PIL import Image
import tensorflow as tf
#import matplotlib.pyplot as plt
#from mpl_toolkits.mplot3d import axes3d, Axes3D
from PIL import Image
import time

strategy = tf.distribute.MirroredStrategy()

BATCH_SIZE_PER_REPLICA = 2
GLOBAL_BATCH_SIZE = BATCH_SIZE_PER_REPLICA * strategy.num_replicas_in_sync
BUFFER_SIZE = 8
EPOCHS = 200000

import models.dist_arg as models

parser = argparse.ArgumentParser()
parser.add_argument('--data-dir', default='data/argo-5m', help='Dataset directory [default: data/argo-5m]')
parser.add_argument('--dataset', default='argo', help='Dataset. argo or nu [default: argo]')
parser.add_argument('--batch-size', type=int, default=8, help='Batch Size during training [default: 4]')
parser.add_argument('--num-iters', type=int, default=200000, help='Iterations to run [default: 200000]')
parser.add_argument('--save-iters', type=int, default=1000, help='Iterations to save checkpoints [default: 1000]')
parser.add_argument('--learning-rate', type=float, default=1e-5, help='Learning rate [default: 1e-5]')
parser.add_argument('--max-gradient-norm', type=float, default=5.0, help='Clip gradients to this norm [default: 5.0].')
parser.add_argument('--seq-length', type=int, default=10, help='Length of sequence [default: 10]')
parser.add_argument('--num-points', type=int, default=1024, help='Number of points [default: 1024]')
parser.add_argument('--num-samples', type=int, default=8, help='Number of samples [default: 8]')
parser.add_argument('--unit', type=str, default='pointrnn', help='Unit. pointrnn, pointgru or pointlstm [default: pointlstm]')
parser.add_argument('--alpha', type=float, default=1.0, help='Weigh on CD loss [default: 1.0]')
parser.add_argument('--beta', type=float, default=1.0, help='Weigh on EMD loss [default: 1.0]')
parser.add_argument('--log-dir', default='outputs', help='Log dir [default: outputs]')

args = parser.parse_args()
np.random.seed(999)
tf.compat.v1.set_random_seed(999)
print ('-'*60)
print ("arguments_parsed")
print ('-'*60)
print (tf.distribute.get_strategy())

args.log_dir += '/%s-%s'%(args.dataset, args.unit)

if args.dataset == 'argo':
    from datasets.argo_nu import Argoverse as Dataset
if args.dataset == 'nu':
    from datasets.argo_nu import nuScenes as Dataset

train_dataset = Dataset(root=args.data_dir,
                        seq_length=args.seq_length,
                        num_points=args.num_points,
                        train=True)



print ('Number of devices: {}'.format(strategy.num_replicas_in_sync))

def get_batch(dataset, batch_size):
    batch_data = []
    for i in range(batch_size):
        sample = dataset[0]
        batch_data.append(sample)
    return np.stack(batch_data, axis=0)

batch_data = tf.convert_to_tensor(get_batch(dataset=train_dataset, batch_size=args.batch_size))
dataset = tf.data.Dataset.from_tensor_slices(batch_data).shuffle(BUFFER_SIZE).batch(GLOBAL_BATCH_SIZE)
train_dist_dataset = strategy.experimental_distribute_dataset(dataset)
print(type(batch_data), batch_data.shape, dataset.element_spec)

print ('-'*60)
print ("distributed dataset")

def create_model():
    model_name = 'Point' + args.unit[5:].upper()
    Model = getattr(models, model_name)
    model = Model(batch_size=args.batch_size,
              seq_length=args.seq_length,
              num_points=args.num_points,
              num_samples=args.num_samples,
              knn=True,
              alpha=args.alpha,
              beta=args.beta,
              learning_rate=args.learning_rate,
              max_gradient_norm=args.max_gradient_norm,
              is_training=True)
    return model

with strategy.scope():
  model = create_model()

print ('-'*60)
print ("model_made")

@tf.function
def distributed_train_step(dataset_inputs):

        los, cd, emd, step, summary, predictions, _ = strategy.experimental_run_v2([model.loss, model.cd, model.emd, model.global_step, summary_op, model.predicted_frames, model.train_op], args=(dataset_inputs,))
        return strategy.reduce(tf.distribute.ReduceOp.SUM, los, axis=None)

for epoch in range(args.num_iters):
        # TRAIN LOOP
        total_loss = 0.0
        num_batches = 0
        for x in train_dist_dataset:
                total_loss += distributed_train_step(x)
                num_batches += 1
        train_loss = total_loss / num_batches

```
It calls the **model/dist_arg.py** which leads to the issue observed.

**models/dist.arg.py**
```
import os
import sys
import tensorflow as tf

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.dirname(BASE_DIR)
sys.path.append(os.path.join(ROOT_DIR, 'modules'))
sys.path.append(os.path.join(ROOT_DIR, 'modules/tf_ops/nn_distance'))
sys.path.append(os.path.join(ROOT_DIR, 'modules/tf_ops/approxmatch'))

from pointnet2 import *
from pointrnn_cell_impl import *
import tf_nndistance
import tf_approxmatch
"""
strategy = tf.distribute.MirroredStrategy()
"""
strategy = tf.distribute.get_strategy()

BATCH_SIZE_PER_REPLICA = 2
GLOBAL_BATCH_SIZE = BATCH_SIZE_PER_REPLICA * strategy.num_replicas_in_sync
BUFFER_SIZE = 8
EPOCHS = 200000

strategy = tf.distribute.get_strategy()

tf.compat.v1.disable_eager_execution()

class PointRNN(object):
    def __init__(self, batch_size, seq_length, num_points=1024, num_samples=8, knn=False, alpha=1.0, beta=1.0, learning_rate=0.001, max_gradient_norm=5.0, is_training=False):

        self.global_step = tf.Variable(0, trainable=False)

        self.inputs = tf.compat.v1.placeholder(tf.float32, [batch_size, seq_length, num_points, 3])
        frames = tf.split(value=self.inputs, num_or_size_splits=seq_length, axis=1)
        frames = [tf.squeeze(input=frame, axis=[1]) for frame in frames]

        cell1 = PointRNNCell(radius=1.0+1e-6, nsample=3*num_samples, out_channels=128, knn=knn, pooling='max')
        cell2 = PointRNNCell(radius=2.0+1e-6, nsample=2*num_samples, out_channels=256, knn=knn, pooling='max')
        cell3 = PointRNNCell(radius=4.0+1e-6, nsample=1*num_samples, out_channels=512, knn=knn, pooling='max')

        # context
        states1 = None
        states2 = None
        states3 = None
        for i in range(int(seq_length/2)):
            # 512
            xyz1, _, _, _ = sample_and_group(int(num_points/2), radius=0.5+1e-6, nsample=num_samples, xyz=frames[i], points=None, knn=False, use_xyz=False)
            with tf.compat.v1.variable_scope('encoder_1', reuse=tf.compat.v1.AUTO_REUSE) as scope:
                states1 = cell1((xyz1, None), states1)
                s_xyz1, s_feat1 = states1
            # 256
            xyz2, feat2, _, _ = sample_and_group(int(num_points/2/2), radius=1.0+1e-6, nsample=num_samples, xyz=s_xyz1, points=s_feat1, knn=False, use_xyz=False)
            feat2 = tf.reduce_max(input_tensor=feat2, axis=[2], keepdims=False, name='maxpool')
            with tf.compat.v1.variable_scope('encoder_2', reuse=tf.compat.v1.AUTO_REUSE) as scope:
                states2 = cell2((xyz2, feat2), states2)
                s_xyz2, s_feat2 = states2
            # 128
            xyz3, feat3, _, _ = sample_and_group(int(num_points/2/2/2), radius=2.0+1e-6, nsample=num_samples, xyz=s_xyz2, points=s_feat2, knn=False, use_xyz=False)
            feat3 = tf.reduce_max(input_tensor=feat3, axis=[2], keepdims=False, name='maxpool')
            with tf.compat.v1.variable_scope('encoder_3', reuse=tf.compat.v1.AUTO_REUSE) as scope:
                states3 = cell3((xyz3, feat3), states3)

        # prediction
        predicted_motions = []
        predicted_frames = []
        input_frame = frames[int(seq_length/2)-1]
        for i in range(int(seq_length/2), seq_length):
            # 512
            xyz1, _, _, _ = sample_and_group(int(num_points/2), radius=0.5+1e-6, nsample=num_samples, xyz=input_frame, points=None, knn=False, use_xyz=False)
            with tf.compat.v1.variable_scope('decoder_1', reuse=tf.compat.v1.AUTO_REUSE) as scope:
                states1 = cell1((xyz1, None), states1)
                s_xyz1, s_feat1 = states1
            # 256
            xyz2, feat2, _, _ = sample_and_group(int(num_points/2/2), radius=1.0+1e-6, nsample=num_samples, xyz=s_xyz1, points=s_feat1, knn=False, use_xyz=False)
            feat2 = tf.reduce_max(input_tensor=feat2, axis=[2], keepdims=False, name='maxpool')
            with tf.compat.v1.variable_scope('decoder_2', reuse=tf.compat.v1.AUTO_REUSE) as scope:
                states2 = cell2((xyz2, feat2), states2)
                s_xyz2, s_feat2 = states2
            # 128
            xyz3, feat3, _, _ = sample_and_group(int(num_points/2/2/2), radius=2.0+1e-6, nsample=num_samples, xyz=s_xyz2, points=s_feat2, knn=False, use_xyz=False)
            feat3 = tf.reduce_max(input_tensor=feat3, axis=[2], keepdims=False, name='maxpool')
            with tf.compat.v1.variable_scope('decoder_3', reuse=tf.compat.v1.AUTO_REUSE) as scope:
                states3 = cell3((xyz3, feat3), states3)
                s_xyz3, s_feat3 = states3


            with tf.compat.v1.variable_scope('fp', reuse=tf.compat.v1.AUTO_REUSE) as scope:
                l2_feat = pointnet_fp_module(xyz2,
                                             xyz3,
                                             s_feat2,
                                             s_feat3,
                                             mlp=[256],
                                             last_mlp_activation=True,
                                             scope='fp2')
                l1_feat = pointnet_fp_module(xyz1,
                                             xyz2,
                                             s_feat1,
                                             l2_feat,
                                             mlp=[256],
                                             last_mlp_activation=True,
                                             scope='fp1')
                l0_feat = pointnet_fp_module(input_frame,
                                             xyz1,
                                             None,
                                             l1_feat,
                                             mlp=[256],
                                            xyz1,
                                             None,
                                             l1_feat,
                                             mlp=[256],
                                             last_mlp_activation=True,
                                             scope='fp0')

            with tf.compat.v1.variable_scope('fc', reuse=tf.compat.v1.AUTO_REUSE) as scope:
                predicted_motion = tf.compat.v1.layers.conv1d(inputs=l0_feat, filters=128, kernel_size=1, strides=1, padding='valid', data_format='channels_last', activation=tf.nn.relu, name='fc1')
                predicted_motion = tf.compat.v1.layers.conv1d(inputs=predicted_motion, filters=3, kernel_size=1, strides=1, padding='valid', data_format='channels_last', activation=None, name='fc2')

            predicted_motions.append(predicted_motion)
            input_frame += predicted_motion
            predicted_frames.append(input_frame)

        # loss
        if is_training:
            with tf.GradientTape() as tape:
                optimizer = tf.compat.v1.train.AdamOptimizer(learning_rate)
                self.loss = self.emd = self.cd = 0
                for i in range(int(seq_length/2)):
                    match = tf_approxmatch.approx_match(frames[i+int(seq_length/2)], predicted_frames[i])
                    #input_emd = tf_approxmatch.match_cost(frames[i+int(seq_length/2)], predicted_frames[i], match)
                    emd_distance = tf_approxmatch.match_cost(frames[i+int(seq_length/2)], predicted_frames[i], match)
                    ####################################################
                    #print (i, match, input_emd, emd_distance)
                    loss_emd = emd_distance
                    self.emd += loss_emd

                    dists_forward, _, dists_backward, _ = tf_nndistance.nn_distance(predicted_frames[i], frames[i+int(seq_length/2)])
                    #loss_cd = tf.reduce_mean(input_tensor=dists_forward+dists_backward)
                    loss_cd = dists_forward + dists_backward
                    ######################################################
                    self.cd += loss_cd

                    self.loss += (alpha*loss_cd + beta*loss_emd)

                self.cd /= int(seq_length/2)
                self.emd /= (int(seq_length/2)*num_points)

                self.loss /= int(seq_length/2)

                self.lais /= (int(seq_length/2)*num_points)

                self.loss = tf.nn.compute_average_loss(self.loss, global_batch_size=GLOBAL_BATCH_SIZE)

            params = tf.compat.v1.trainable_variables()
            gradients = tape.gradient(self.loss, params)
            #gradients = tf.gradients(ys=self.loss, xs=params)
            #clipped_gradients, norm = tf.clip_by_global_norm(gradients, max_gradient_norm)
            #self.train_op = tf.compat.v1.train.AdamOptimizer(learning_rate).apply_gradients(zip(clipped_gradients, params), global_step=self.global_step)
            #self.train_op = optimizer.apply_gradients(zip(gradients, model.trainable_variables))
            self.train_op = optimizer(learning_rate).apply_gradients(zip(clipped_gradients, params), global_step=self.global_step)

        self.predicted_motions = tf.stack(values=predicted_motions, axis=1)
        self.predicted_frames = tf.stack(values=predicted_frames, axis=1)
        self.saver = tf.compat.v1.train.Saver(tf.compat.v1.global_variables(), max_to_keep=1)

```

The trace mentions the line 
```
gradients = tape.gradient(self.loss, params)
```
in the **models/dist_arg.py** (the second file shown above).

I have used 
```
strategy.experimental_run_v2([model.loss, model.cd, model.emd, model.lais, model.global_step, summary_op, model.predicted_frames, model.train_op], args=(dataset_inputs,)) 
```
as mentioned in similar issues and enclosed my loss computation part within

``` 
used tf.GradientTape() as tape:
```
and also commented
``` 
clipped_gradients, norm = tf.clip_by_global_norm(gradients, max_gradient_norm)  
```
as it was also mentioned that normalization was causing an error,  though the model was different(CNN).

Can someone please find any error on my part(as i have added/changed some lines of code to make it run on multiple gpus) or is it a tensorflow error?

**Comment by Saduf2019** [comment]
@all-over-the-place 
Can you please share a colab gist with the issue reported.
