### ISSUE TITLE
`tf.keras.layers.LayerNormalization` may produce CPU->GPU Memcpy error

### ISSUE THREAD

**Issue by vbod** [tensorflow/tensorflow#49600]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): YES
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.4.1
- Python version: 3.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 11.2 / 8.1.1
- GPU model and memory: Quadro T1000 (computeCapability: 7.5)

**Describe the current behavior**

`tf.keras.layers.LayerNormalization` may produce an error when epsilon is too high (in my case it was 1e-3 but when setting it to 1e-7 it works as expected):
```
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal:  cuDNN launch failure : input shape ([1,256,128,1])
         [[node GenieDelay/label/layer_norm/FusedBatchNormV3 (defined at Workspace\CompanyTransformer\company_transformer\src\company_transformer\genie\delay\modeling.py:53) ]]
         [[div_no_nan_3/ReadVariableOp/_566]]
  (1) Internal:  cuDNN launch failure : input shape ([1,256,128,1])
         [[node GenieDelay/label/layer_norm/FusedBatchNormV3 (defined at Workspace\CompanyTransformer\company_transformer\src\company_transformer\genie\delay\modeling.py:53) ]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_21841]
Function call stack:
train_function -> train_function
2021-05-24 19:06:14.571178: I tensorflow/stream_executor/stream.cc:1404] [stream=000001C31D860660,impl=000001C331B8A6D0] did not wait for [stream=000001C31D860D20,impl=000001C331B8A670]
2021-05-24 19:06:14.574031: F tensorflow/core/common_runtime/gpu/gpu_util.cc:340] CPU->GPU Memcpy failed
```

**Describe the expected behavior**

Not quite sure what should be expected here because I'm not quite sure why copying a float32[] from CPU to GPU fails but I guess if it's due to some precision (why so?) cropping should be applied. If it's due to NaN then maybe a proper logging would be fine (note that in that case, `tf.keras.callbacks.TerminateOnNaN()` was not hit, but I guess this is called only as a callback at then end of a batch but here it seems to occur in the middle of the calculation). Otherwise, I can't say why copying the buffer fails.

**[Contributing](https://www.tensorflow.org/community/contribute)** - Do you
want to contribute a PR? (yes/no): - Briefly describe your candidate solution
(if contributing): Haven't investigated in the code right now but I can dig if need be.

**Standalone code to reproduce the issue**
Unfortunately I cannot provide the data as they're confidential but I don't think they matter that much actually. I use a `HuggingFace's` BERT-like Transformer (just the architecture, I adapated it to run on custom financial data) which I stack with other embeddings and standalone features, and append a head. The input vector size of this head is roughly ~300: the 256 first dimensions come from a pooled-CLS of a Transformer so having values between [-1,1] as they're output from `tanh`, there are roughly 10 features that are unscaled but positive, and the rest are embeddings gotten from layers three layers `tf.keras.layers.Embedding` with output dimension 16 (all weights are initialized with `tf.keras.initializers.TruncatedNormal(stddev=0.02)`). The error comes in the head and here the code stub (without data, I'll try to produce fake data that makes it fail if ever needed):
```Python
class DelayHead(tf.keras.layers.Layer):
    def __init__(self,
                 number_heads: int,
                 head_hidden_size: int,
                 initializer_range: float,
                 head_layer_norm_eps: float,
                 head_dropout_prob: float,
                 **kwargs):
        super().__init__(**kwargs)

        self.number_heads = number_heads
        self.denses = []
        self.layer_norms = []
        for _ in range(self.number_heads):
            self.denses.append(
                tf.keras.layers.Dense(
                    units=head_hidden_size,
                    kernel_initializer=tf.keras.initializers.TruncatedNormal(stddev=0.02),
                    name='dense'
                )
            )
            self.layer_norms.append(
                tf.keras.layers.LayerNormalization(
                    epsilon=head_layer_norm_eps,
                    name='layer_norm'
                )
            )
        self.dropout = tf.keras.layers.Dropout(
            rate=head_dropout_prob
        )
        self.labeling = tf.keras.layers.Dense(
            units=1,
            activation='linear',
            name='label'
        )

    def call(self, hidden_state: tf.Tensor) -> tf.Tensor:
        for i in range(self.number_heads):
            hidden_state = self.denses[i](hidden_state)
            hidden_state = self.layer_norms[i](hidden_state)
        hidden_state = self.dropout(hidden_state)
        return self.labeling(hidden_state)
```

**Other info / logs** 

Logs can be slightly different from one run to another, but it boils down to a CPU->GPU memcpy error in the end. Here are two different logs I got:
```
2021-05-24 20:42:11.957505: E tensorflow/stream_executor/cuda/cuda_dnn.cc:336] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2021-05-24 20:42:11.957815: E tensorflow/stream_executor/cuda/cuda_dnn.cc:340] Error retrieving driver version: Unimplemented: kernel reported driver version not implemented on 
Windows
2021-05-24 20:42:11.958364: W .\tensorflow/stream_executor/stream.h:2048] attempting to perform DNN operation using StreamExecutor without DNN support
Traceback (most recent call last):
  File "company_transformer\src\company_transformer\genie\delay\task.py", line 150, in <module>
    main(
  File "C:\Workspace\CompanyTransformer\company_transformer\src\company_transformer\utils.py", line 86, in decorated
    return func(*args, **kwargs)
  File "company_transformer\src\company_transformer\genie\delay\task.py", line 131, in main
    model.fit(
  File "C:\Users\vince\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
  File "C:\Users\vince\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\vince\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\def_function.py", line 888, in _call
    return self._stateless_fn(*args, **kwds)
  File "C:\Users\vince\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 2942, in __call__
    return graph_function._call_flat(
  File "C:\Users\vince\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 1918, in _call_flat
  File "C:\Users\vince\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 555, in call
    outputs = execute.execute(
  File "C:\Users\vince\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal:  cuDNN launch failure : input shape ([1,256,128,1])
         [[node GenieDelay/label/layer_norm/FusedBatchNormV3 (defined at Workspace\CompanyTransformer\company_transformer\src\company_transformer\genie\delay\modeling.py:53) ]] 
         [[gradient_tape/GenieDelay/company_transformer/company_transformer_embeddings/RaggedToTensor/strided_slice/_626]]
  (1) Internal:  cuDNN launch failure : input shape ([1,256,128,1])
         [[node GenieDelay/label/layer_norm/FusedBatchNormV3 (defined at Workspace\CompanyTransformer\company_transformer\src\company_transformer\genie\delay\modeling.py:53) ]] 
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_21841]

Function call stack:
train_function -> train_function

2021-05-24 20:42:12.384440: I tensorflow/stream_executor/stream.cc:1404] [stream=0000016D1BA41AA0,impl=0000016D2FC1F860] did not wait for [stream=0000016D1BA40540,impl=0000016D2FC1F830]
2021-05-24 20:42:12.385247: F tensorflow/core/common_runtime/gpu/gpu_util.cc:340] CPU->GPU Memcpy failed
```
and:
```
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal:  cuDNN launch failure : input shape ([1,256,128,1])
         [[node GenieDelay/label/layer_norm/FusedBatchNormV3 (defined at Workspace\CompanyTransformer\company_transformer\src\company_transformer\genie\delay\modeling.py:53) ]]
         [[div_no_nan_3/ReadVariableOp/_566]]
  (1) Internal:  cuDNN launch failure : input shape ([1,256,128,1])
         [[node GenieDelay/label/layer_norm/FusedBatchNormV3 (defined at Workspace\CompanyTransformer\company_transformer\src\company_transformer\genie\delay\modeling.py:53) ]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_21841]

Function call stack:
train_function -> train_function

2021-05-24 19:06:14.571178: I tensorflow/stream_executor/stream.cc:1404] [stream=000001C31D860660,impl=000001C331B8A6D0] did not wait for [stream=000001C31D860D20,impl=000001C331B8A670]
2021-05-24 19:06:14.574031: F tensorflow/core/common_runtime/gpu/gpu_util.cc:340] CPU->GPU Memcpy failed
```

**Comment by tilakrayal** [comment]
@vbod ,

In order to expedite the trouble-shooting process, could you please provide the complete code and dataset to reproduce the issue reported here.

**Comment by tilakrayal** [comment]
Please try limiting GPU memory growth using any of the methods listed [here](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth) and tensorflow v2.4 is compatible with cuda11.0.
Please take a look at configurations [here](https://www.tensorflow.org/install/source_windows#gpu) and check if it helps. Thanks!
