### ISSUE TITLE
CRC Error on Retraining Inception_v3

### ISSUE THREAD

**Issue by MaKuehn** [tensorflow/tensorflow#4970]
Hi.

I tried to follow the tutorial given on https://www.tensorflow.org/versions/r0.9/how_tos/image_retraining/index.html. I'm on MacOS Sierra and installed a separate version of python via homebrew, which is located in "/usr/local/bin/python".

Now, I installed and compiled tensorflow from source and set the python location to "/usr/local/bin/python" and the library path to "/usr/local/lib/python2.7/site-packages". After compiling the retrain files, I get an error on running 
```
bazel-bin/tensorflow/examples/image_retraining/retrain` --image_dir ~/flower_photos
```
which is
```
Traceback (most recent call last):
  File "/Users/marcel/dev/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/examples/image_retraining/retrain.py", line 1014, in <module>
    tf.app.run()
  File "/Users/marcel/dev/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/Users/marcel/dev/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/examples/image_retraining/retrain.py", line 752, in main
    maybe_download_and_extract()
  File "/Users/marcel/dev/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/examples/image_retraining/retrain.py", line 314, in maybe_download_and_extract
    tarfile.open(filepath, 'r:gz').extractall(dest_directory)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 2079, in extractall
    self.extract(tarinfo, path)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 2116, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 2192, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 2233, in makefile
    copyfileobj(source, target)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 266, in copyfileobj
    shutil.copyfileobj(src, dst)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 49, in copyfileobj
    buf = fsrc.read(length)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 831, in read
    buf += self.fileobj.read(size - len(buf))
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 743, in read
    return self.readnormal(size)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 758, in readnormal
    return self.__read(size)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 748, in __read
    buf = self.fileobj.read(size)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 315, in _read
    self._read_eof()
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 354, in _read_eof
    hex(self.crc)))
IOError: CRC check failed 0x39de13a7 != 0x630e11cfL
```

Any insights on that? Sounds like the download is corrupted and I already re-downloaded the images several times. I think it actually doesn't rely on the images, because the error is the same no matter what directory I hand to --image_dir.

Thanks in advance

**Comment by jart** [comment]
It seems issues like this have come up before in #3401. Could you try manually downloading with:

```
wget -O /tmp/imagenet/inception-2015-12-05.tgz http://download.tensorflow.org/models/image/imagenet/inception-2015-12-05.tgz
```

And see if that solves your problem?

**Comment by Emtschikay** [comment]
That sounds very reasonable. Never thought of the fact that the model has to be downloaded as well. Thanks a lot, will get back to you on Monday when I'm in the office again.

**Comment by jart** [comment]
Also can you do me a favor and run:

```
curl -I --noproxy '*' http://download.tensorflow.org/models/image/imagenet/inception-2015-12-05.tgz
```

And paste the output into this issue?

See also: tensorflow/models#541

**Comment by MaKuehn** [comment]
First of all, thanks for your help. This is the output of the curl:
'''
HTTP/1.1 200 OK
X-GUploader-UploadID: AEnB2UpUAytFdWWiywt5qa2nJ7oHtP-1dnGOjhvQtIT57Wumy13dxfddFfIH32dm4LTvdu0eJOb6txr3LjSXUWUmzdzfbeqG_A
Expires: Mon, 17 Oct 2016 09:02:37 GMT
Date: Mon, 17 Oct 2016 08:02:37 GMT
Cache-Control: public, max-age=3600
Last-Modified: Sat, 05 Dec 2015 02:23:10 GMT
ETag: "28395d1479e87ee86da70419d1ba2c3c"
x-goog-generation: 1449282190011000
x-goog-metageneration: 2
x-goog-stored-content-encoding: identity
x-goog-stored-content-length: 88931400
Content-Type: application/x-compressed-tar
x-goog-hash: crc32c=ef9Stw==
x-goog-hash: md5=KDldFHnofuhtpwQZ0bosPA==
x-goog-storage-class: STANDARD
Accept-Ranges: bytes
Content-Length: 88931400
Server: UploadServer
'''

I'll try to manually download the model now and see if it works, will post back later :)
