### ISSUE TITLE
The finish project is crashing in the device.

### ISSUE THREAD

**Issue by Rontu22** [tensorflow/tensorflow#49766]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No , the finish project only.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Realme 7
- TensorFlow installed from (source or binary): Used google colab
- TensorFlow version (use command below): 2.5.0
- Python version: 3.7.10 (Used google colab )
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: Colab free GPU

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
The "finish" app given in "Build a handwritten digit classifier app with TensorFlow Lite " tutorial is crashing everytime in the device.
I am facing the problem from trying to build the "finish" app from this :
https://developer.android.com/codelabs/digit-classifier-tflite?authuser=1#2

And then trying to build project from the folder below :
lite/codelabs/digit_classifier/android/finish/

Android Studio Version :
4.2.1

**Describe the expected behavior**
The app "finish" should recognize text digits.

**[Contributing](https://www.tensorflow.org/community/contribute)** - Do you
want to contribute a PR? (yes/no): - Briefly describe your candidate solution
(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

I am using the device realme RMX2151 ,it is built fine but while opening the app it is directly crashing. Can anyone suggest any fix to it or anyone found this issue earlier ??

**Comment by tilakrayal** [comment]
@Rontu22 ,

In order to expedite the trouble-shooting process, could you please provide the complete code and dataset to reproduce the issue reported here.

Also please take a look at this [issue](https://github.com/tensorflow/tensorflow/issues/38688) with similar error.It helps.
Thanks

**Comment by Rontu22** [comment]
@tilakrayal  following is the error occured after building the app : 

2021-05-27 12:42:48.320 29720-29758/org.tensorflow.lite.codelabs.digitclassifier E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
    Process: org.tensorflow.lite.codelabs.digitclassifier, PID: 29720
    java.lang.IllegalArgumentException: Internal error: Cannot create interpreter: Didn't find op for builtin opcode 'CONV_2D' version '5'
    
    Registration failed.
    
        at org.tensorflow.lite.NativeInterpreterWrapper.createInterpreter(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:72)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:63)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:237)
        at org.tensorflow.lite.codelabs.digitclassifier.DigitClassifier.initializeInterpreter(DigitClassifier.kt:66)
        at org.tensorflow.lite.codelabs.digitclassifier.DigitClassifier.access$initializeInterpreter(DigitClassifier.kt:31)
        at org.tensorflow.lite.codelabs.digitclassifier.DigitClassifier$initialize$1.run(DigitClassifier.kt:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by Rontu22** [comment]
The logccat output is as follows : 

2021-05-27 12:42:47.915 29720-29720/? I/digitclassifie: Late-enabling -Xcheck:jni
2021-05-27 12:42:47.948 29720-29720/? E/digitclassifie: Unknown bits set in runtime_flags: 0x8000
2021-05-27 12:42:47.963 29720-29720/? E/RefClass: java.lang.reflect.InvocationTargetException
2021-05-27 12:42:48.245 29720-29720/org.tensorflow.lite.codelabs.digitclassifier W/digitclassifie: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
2021-05-27 12:42:48.246 29720-29720/org.tensorflow.lite.codelabs.digitclassifier W/digitclassifie: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
2021-05-27 12:42:48.294 29720-29720/org.tensorflow.lite.codelabs.digitclassifier W/digitclassifie: Accessing hidden method Landroid/graphics/FontFamily;-><init>()V (greylist, reflection, allowed)
2021-05-27 12:42:48.294 29720-29720/org.tensorflow.lite.codelabs.digitclassifier W/digitclassifie: Accessing hidden method Landroid/graphics/FontFamily;->addFontFromAssetManager(Landroid/content/res/AssetManager;Ljava/lang/String;IZIII[Landroid/graphics/fonts/FontVariationAxis;)Z (greylist, reflection, allowed)
2021-05-27 12:42:48.294 29720-29720/org.tensorflow.lite.codelabs.digitclassifier W/digitclassifie: Accessing hidden method Landroid/graphics/FontFamily;->addFontFromBuffer(Ljava/nio/ByteBuffer;I[Landroid/graphics/fonts/FontVariationAxis;II)Z (greylist, reflection, allowed)
2021-05-27 12:42:48.294 29720-29720/org.tensorflow.lite.codelabs.digitclassifier W/digitclassifie: Accessing hidden method Landroid/graphics/FontFamily;->freeze()Z (greylist, reflection, allowed)
2021-05-27 12:42:48.294 29720-29720/org.tensorflow.lite.codelabs.digitclassifier W/digitclassifie: Accessing hidden method Landroid/graphics/FontFamily;->abortCreation()V (greylist, reflection, allowed)
2021-05-27 12:42:48.294 29720-29720/org.tensorflow.lite.codelabs.digitclassifier W/digitclassifie: Accessing hidden method Landroid/graphics/Typeface;->createFromFamiliesWithDefault([Landroid/graphics/FontFamily;Ljava/lang/String;II)Landroid/graphics/Typeface; (greylist, reflection, allowed)
2021-05-27 12:42:48.316 29720-29720/org.tensorflow.lite.codelabs.digitclassifier I/SurfaceFactory: [static] sSurfaceFactory = com.mediatek.view.impl.SurfaceFactoryImpl@6dd0dd3
2021-05-27 12:42:48.320 29720-29758/org.tensorflow.lite.codelabs.digitclassifier E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
    Process: org.tensorflow.lite.codelabs.digitclassifier, PID: 29720
    java.lang.IllegalArgumentException: Internal error: Cannot create interpreter: Didn't find op for builtin opcode 'CONV_2D' version '5'
    
    Registration failed.
    
        at org.tensorflow.lite.NativeInterpreterWrapper.createInterpreter(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:72)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:63)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:237)
        at org.tensorflow.lite.codelabs.digitclassifier.DigitClassifier.initializeInterpreter(DigitClassifier.kt:66)
        at org.tensorflow.lite.codelabs.digitclassifier.DigitClassifier.access$initializeInterpreter(DigitClassifier.kt:31)
        at org.tensorflow.lite.codelabs.digitclassifier.DigitClassifier$initialize$1.run(DigitClassifier.kt:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2021-05-27 12:42:48.325 29720-29720/org.tensorflow.lite.codelabs.digitclassifier D/ColorViewRootUtil: initSwipState, isDisplayCompatApp false
2021-05-27 12:42:48.325 29720-29720/org.tensorflow.lite.codelabs.digitclassifier D/ColorViewRootUtil: updateScreenSize, mScreenHeight 2400,mScreenWidth:1080,height:2400,width:1080
2021-05-27 12:42:48.328 29720-29720/org.tensorflow.lite.codelabs.digitclassifier D/WindowManager: Add to mViews: DecorView@92843c5[MainActivity], this = android.view.WindowManagerGlobal@a29111a,pkg= org.tensorflow.lite.codelabs.digitclassifier
2021-05-27 12:42:48.347 29720-29758/? I/Process: Sending signal. PID: 29720 SIG: 9

**Comment by Rontu22** [comment]
I am facing the problem from trying to build the "finish" app from this : 
[https://developer.android.com/codelabs/digit-classifier-tflite?authuser=1#2](url)

And then trying to build  project from the folder below : 
lite/codelabs/digit_classifier/android/finish/ 



Android Studio Version : 
4.2.1

**Comment by khanhlvg** [comment]
Fixing in https://github.com/tensorflow/examples/pull/322

**Comment by lintian06** [comment]
Thanks @khanhlvg! "2.+" sounds a good idea.

**Comment by Rontu22** [comment]
Thanks a lot for all of your kind support.

**Comment by Rontu22** [comment]
After applying (implementation 'org.tensorflow:tensorflow-lite:2.+') in the final app , I am getting the following error message . Please some one help me out.


2021-06-02 22:46:43.774 17776-17776/? I/digitclassifie: Late-enabling -Xcheck:jni
2021-06-02 22:46:43.796 17776-17776/? E/digitclassifie: Unknown bits set in runtime_flags: 0x8000
2021-06-02 22:46:43.806 17776-17776/? E/RefClass: java.lang.reflect.InvocationTargetException
2021-06-02 22:46:44.043 17776-17776/? W/digitclassifie: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
2021-06-02 22:46:44.044 17776-17776/? W/digitclassifie: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
2021-06-02 22:46:44.076 17776-17776/? W/digitclassifie: Accessing hidden method Landroid/graphics/FontFamily;-><init>()V (greylist, reflection, allowed)
2021-06-02 22:46:44.076 17776-17776/? W/digitclassifie: Accessing hidden method Landroid/graphics/FontFamily;->addFontFromAssetManager(Landroid/content/res/AssetManager;Ljava/lang/String;IZIII[Landroid/graphics/fonts/FontVariationAxis;)Z (greylist, reflection, allowed)
2021-06-02 22:46:44.076 17776-17776/? W/digitclassifie: Accessing hidden method Landroid/graphics/FontFamily;->addFontFromBuffer(Ljava/nio/ByteBuffer;I[Landroid/graphics/fonts/FontVariationAxis;II)Z (greylist, reflection, allowed)
2021-06-02 22:46:44.076 17776-17776/? W/digitclassifie: Accessing hidden method Landroid/graphics/FontFamily;->freeze()Z (greylist, reflection, allowed)
2021-06-02 22:46:44.076 17776-17776/? W/digitclassifie: Accessing hidden method Landroid/graphics/FontFamily;->abortCreation()V (greylist, reflection, allowed)
2021-06-02 22:46:44.076 17776-17776/? W/digitclassifie: Accessing hidden method Landroid/graphics/Typeface;->createFromFamiliesWithDefault([Landroid/graphics/FontFamily;Ljava/lang/String;II)Landroid/graphics/Typeface; (greylist, reflection, allowed)
2021-06-02 22:46:44.089 17776-17811/? I/tflite: Initialized TensorFlow Lite runtime.
2021-06-02 22:46:44.090 17776-17811/? I/tflite: Created TensorFlow Lite delegate for NNAPI.
2021-06-02 22:46:44.092 17776-17811/? E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
    Process: org.tensorflow.lite.codelabs.digitclassifier, PID: 17776
    java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.
        at org.tensorflow.lite.NativeInterpreterWrapper.applyDelegate(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.applyDelegates(NativeInterpreterWrapper.java:492)
        at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:88)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:66)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:287)
        at org.tensorflow.lite.codelabs.digitclassifier.DigitClassifier.initializeInterpreter(DigitClassifier.kt:66)
        at org.tensorflow.lite.codelabs.digitclassifier.DigitClassifier.access$initializeInterpreter(DigitClassifier.kt:31)
        at org.tensorflow.lite.codelabs.digitclassifier.DigitClassifier$initialize$1.run(DigitClassifier.kt:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2021-06-02 22:46:44.097 17776-17776/? I/SurfaceFactory: [static] sSurfaceFactory = com.mediatek.view.impl.SurfaceFactoryImpl@9a0d8f5
2021-06-02 22:46:44.103 17776-17776/? D/ColorViewRootUtil: initSwipState, isDisplayCompatApp false
2021-06-02 22:46:44.104 17776-17776/? D/ColorViewRootUtil: updateScreenSize, mScreenHeight 2400,mScreenWidth:1080,height:2400,width:1080
2021-06-02 22:46:44.107 17776-17776/? D/WindowManager: Add to mViews: DecorView@1730f71[MainActivity], this = android.view.WindowManagerGlobal@f183156,pkg= org.tensorflow.lite.codelabs.digitclassifier
2021-06-02 22:46:44.113 17776-17811/? I/Process: Sending signal. PID: 17776 SIG: 9

**Comment by khanhlvg** [comment]
Sorry for the issue - it looks like the TFLite model converted with TF 2.5 isn't compatible with NNAPI. I submitted a temporary fix https://github.com/tensorflow/examples/commit/f8ea518e0efdbf5d7c75b314133b29e8e0212e70 to avoid using NNAPI while we look further into the issue.
