### ISSUE TITLE
Installation exception in EI Capitan

### ISSUE THREAD

**Issue by ad26kt** [tensorflow/tensorflow#498]
I just installed homebrew, and also set brew python as default.
when I import tensorflow:
```javascript
Python 2.7.11 (default, Dec 13 2015, 19:34:28)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 43, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named protobuf


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.```

what is the problem?
I can't find the solution anywhere

**Comment by migel** [comment]
Try: `brew update && brew reinstall --devel protobuf` see #258.

**Comment by vrv** [comment]
De-duping with #258 -- reopen if this is different.

**Comment by Archivus** [comment]
Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.

Still getting the above error on the latest El-Capitan released today

**Comment by orcaman** [comment]
Getting something similar. Any ideas?

```
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 41, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 35, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 8, in <module>
    from google.protobuf import reflection as _reflection
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/google/protobuf/reflection.py", line 58, in <module>
    from google.protobuf.internal import python_message as message_impl
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 53, in <module>
    from io import BytesIO
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.
```

**Comment by JackSullivan** [comment]
@orcaman @Archivus I was having the same issue after installing tensorflow from bazel, on mac. I fixed it with
```
sudo pip uninstall tensorflow
sudo pip uninstall protobuf
sudo pip install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.7.1-cp27-none-any.whl
```
ie. Uninstalling both tensorflow and protobuf, then reinstalling

**Comment by keunwoochoi** [comment]
```python
Traceback (most recent call last):
  File "cnn_cropping.py", line 48, in <module>
    model.add(cropping.Cropping2D(cropping=((2,2),(2,2)) ))
  File "/Users/gnu/anaconda/lib/python2.7/site-packages/keras/models.py", line 146, in add
    output_tensor = layer(self.outputs[0])
  File "/Users/gnu/anaconda/lib/python2.7/site-packages/keras/engine/topology.py", line 485, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/Users/gnu/anaconda/lib/python2.7/site-packages/keras/engine/topology.py", line 543, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/Users/gnu/anaconda/lib/python2.7/site-packages/keras/engine/topology.py", line 148, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/Users/gnu/Gnubox/keras_cropping/cropping.py", line 56, in call
    return x[:, :, self.cropping[0][0]:-self.cropping[0][1], self.cropping[1][0]:-self.cropping[1][1]]
  File "/Users/gnu/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 315, in _SliceHelper
    "Negative stop indices are not currently supported")
NotImplementedError: Negative stop indices are not currently supported
```

Does anyone have any idea? I think I should be able to use `self.input_shape` to clarify the index, but 
```python
(Pdb) self.input_shape
*** Exception: The layer has never been called and thus has no defined input shape.
```
it doesn't work.
