### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by yinqihuang** [tensorflow/tensorflow#49841]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows version 20h2
- Python version:  3.7.7
- Installed using conda

Trying to run python in terminal, already done:

`(base) C:\Users\Yinqi\trRosetta2\trRosetta>conda create -n tf tensorflow`

But ran into this error:

`ImportError: DLL load failed: The specified module could not be found. Failed to load the native TensorFlow runtime.`

Full traceback:

```
File "C:\Users\Yinqi\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
        from tensorflow.python._pywrap_tensorflow_internal import *
    ImportError: DLL load failed: The specified module could not be found.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "predict.py", line 6, in <module>
        import tensorflow as tf
      File "C:\Users\Yinqi\anaconda3\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
        from tensorflow.python.tools import module_util as _module_util
      File "C:\Users\Yinqi\anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
        from tensorflow.python.eager import context
      File "C:\Users\Yinqi\anaconda3\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
        from tensorflow.python import pywrap_tfe
      File "C:\Users\Yinqi\anaconda3\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
        from tensorflow.python import pywrap_tensorflow
      File "C:\Users\Yinqi\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
        raise ImportError(msg)
    ImportError: Traceback (most recent call last):
      File "C:\Users\Yinqi\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
        from tensorflow.python._pywrap_tensorflow_internal import *
    ImportError: DLL load failed: The specified module could not be found.
```

**Comment by tilakrayal** [comment]
@yinqihuang ,

 We can see you are using conda env to install TF, You may want to raise this issue on [anaconda repo](https://github.com/ContinuumIO/anaconda-issues/issues) for better support.
 Also please take a look at this issues with similar error log.[Link1](https://github.com/tensorflow/tensorflow/issues/35598#issuecomment-573211235),[link2](https://github.com/tensorflow/tensorflow/issues/42394),[link3](https://github.com/tensorflow/tensorflow/issues/36138). It helps.

Thanks!
