### ISSUE TITLE
Error building tensorflow from source

### ISSUE THREAD

**Issue by joyjeni** [tensorflow/tensorflow#4988]
Getting below error while building tensorflow from source.  

$ sudo bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

/home/jenisha/.cache/bazel/_bazel_root/d76a8cba20478b6f06262b0e7e986df4/external/nanopb_git/BUILD:6:1: undeclared inclusion(s) in rule '@nanopb_git//:nanopb':
this rule is missing dependency declarations for the following files included by 'external/nanopb_git/pb_common.c':
  '/usr/include/stdc-predef.h'
  '/usr/lib/gcc/x86_64-linux-gnu/4.8/include/stdint.h'
  '/usr/include/stdint.h'
  '/usr/include/features.h'
  '/usr/include/x86_64-linux-gnu/sys/cdefs.h'
  '/usr/include/x86_64-linux-gnu/bits/wordsize.h'
  '/usr/include/x86_64-linux-gnu/gnu/stubs.h'
  '/usr/include/x86_64-linux-gnu/gnu/stubs-64.h'
  '/usr/include/x86_64-linux-gnu/bits/wchar.h'
  '/usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h'
  '/usr/lib/gcc/x86_64-linux-gnu/4.8/include/stdbool.h'
  '/usr/include/string.h'
  '/usr/include/xlocale.h'
  '/usr/include/x86_64-linux-gnu/bits/string.h'
  '/usr/include/x86_64-linux-gnu/bits/string2.h'
  '/usr/include/endian.h'
  '/usr/include/x86_64-linux-gnu/bits/endian.h'
  '/usr/include/x86_64-linux-gnu/bits/byteswap.h'
  '/usr/include/x86_64-linux-gnu/bits/types.h'
  '/usr/include/x86_64-linux-gnu/bits/typesizes.h'
  '/usr/include/x86_64-linux-gnu/bits/byteswap-16.h'
  '/usr/include/stdlib.h'
  '/usr/include/x86_64-linux-gnu/bits/string3.h'.

**Comment by AFAgarap** [comment]
What's your config? CUDA and cuDNN version? Your OS version? @joyjeni

**Comment by joyjeni** [comment]
Cuda 8.0 , Cudann 5.1, Ubuntu 16.04

**Comment by AFAgarap** [comment]
@joyjeni We have hit the same issue. As I was told, support for CUDA 8.0 will come officially in TensorFlow version 0.11rc1. Referencing my issue #4841 .

**Comment by asimshankar** [comment]
@joyjeni : I'm having trouble reproducing your error and from the snippet above, it doesn't appear to be CUDA related. Do you get the same error when building for CPU only? (using `bazel build -c opt //tensorflow/tools/pip_package:build_pip_package`).

Please include all the information requested for in the ["New Issue" template](https://github.com/tensorflow/tensorflow/issues/new), as that would help in diagnosing the problem. (And in the future, please do fill in the template when filing issues).

**Comment by joyjeni** [comment]
[installtf.pdf](https://github.com/tensorflow/tensorflow/files/537691/installtf.pdf)

Attached list of steps followed while building tensorflow from source

**Comment by asimshankar** [comment]
Do you get the same error when building for CPU only?
Can you run bazel with `--verbose_failures` to get more insight into the failing command?

**Comment by joyjeni** [comment]
Yes with CPU also I get error.

ERROR: /home/jenisha/.cache/bazel/_bazel_jenisha/09415e5fa53b65f11f76c6af77c3c91f/external/local_config_cuda/crosstool/BUILD:4:1: Traceback (most recent call last):
	File "/home/jenisha/.cache/bazel/_bazel_jenisha/09415e5fa53b65f11f76c6af77c3c91f/external/local_config_cuda/crosstool/BUILD", line 4
		error_gpu_disabled()
	File "/home/jenisha/.cache/bazel/_bazel_jenisha/09415e5fa53b65f11f76c6af77c3c91f/external/local_config_cuda/crosstool/error_gpu_disabled.bzl", line 3, in error_gpu_disabled
		fail("ERROR: Building with --config=c...")
ERROR: Building with --config=cuda but TensorFlow is not configured to build with GPU support. Please re-run ./configure and enter 'Y' at the prompt to build with GPU support.
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'CONFIGURATION_FRAGMENT:com.google.devtools.build.lib.skyframe.ConfigurationFragmentValue$ConfigurationFragmentKey@2abbbba' (requested by nodes 'CONFIGURATION_COLLECTION:com.google.devtools.build.lib.skyframe.ConfigurationCollectionValue$ConfigurationCollectionKey@1764fa10', 'CONFIGURATION_FRAGMENT:com.google.devtools.build.lib.skyframe.ConfigurationFragmentValue$ConfigurationFragmentKey@253fcc46', 'CONFIGURATION_FRAGMENT:com.google.devtools.build.lib.skyframe.ConfigurationFragmentValue$ConfigurationFragmentKey@ee578016')
INFO: Elapsed time: 1.400s
java.lang.RuntimeException: Unrecoverable error while evaluating node 'CONFIGURATION_FRAGMENT:com.google.devtools.build.lib.skyframe.ConfigurationFragmentValue$ConfigurationFragmentKey@2abbbba' (requested by nodes 'CONFIGURATION_COLLECTION:com.google.devtools.build.lib.skyframe.ConfigurationCollectionValue$ConfigurationCollectionKey@1764fa10', 'CONFIGURATION_FRAGMENT:com.google.devtools.build.lib.skyframe.ConfigurationFragmentValue$ConfigurationFragmentKey@253fcc46', 'CONFIGURATION_FRAGMENT:com.google.devtools.build.lib.skyframe.ConfigurationFragmentValue$ConfigurationFragmentKey@ee578016')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:1070)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:474)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: com.google.devtools.build.lib.packages.NoSuchTargetException: no such target '@local_config_cuda//crosstool:toolchain': target 'toolchain' not declared in package 'crosstool' defined by /home/jenisha/.cache/bazel/_bazel_jenisha/09415e5fa53b65f11f76c6af77c3c91f/external/local_config_cuda/crosstool/BUILD
	at com.google.devtools.build.lib.rules.cpp.CrosstoolConfigurationLoader.getCrosstoolProtofromBuildFile(CrosstoolConfigurationLoader.java:179)
	at com.google.devtools.build.lib.rules.cpp.CrosstoolConfigurationLoader.findCrosstoolConfiguration(CrosstoolConfigurationLoader.java:239)
	at com.google.devtools.build.lib.rules.cpp.CrosstoolConfigurationLoader.readCrosstool(CrosstoolConfigurationLoader.java:281)
	at com.google.devtools.build.lib.rules.cpp.CppConfigurationLoader.createParameters(CppConfigurationLoader.java:128)
	at com.google.devtools.build.lib.rules.cpp.CppConfigurationLoader.create(CppConfigurationLoader.java:73)
	at com.google.devtools.build.lib.rules.cpp.CppConfigurationLoader.create(CppConfigurationLoader.java:48)
	at com.google.devtools.build.lib.skyframe.ConfigurationFragmentFunction.compute(ConfigurationFragmentFunction.java:78)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:1016)
	... 4 more
Caused by: com.google.devtools.build.lib.packages.NoSuchTargetException: no such target '@local_config_cuda//crosstool:toolchain': target 'toolchain' not declared in package 'crosstool' defined by /home/jenisha/.cache/bazel/_bazel_jenisha/09415e5fa53b65f11f76c6af77c3c91f/external/local_config_cuda/crosstool/BUILD
	at com.google.devtools.build.lib.packages.Package.makeNoSuchTargetException(Package.java:559)
	at com.google.devtools.build.lib.packages.Package.getTarget(Package.java:543)
	at com.google.devtools.build.lib.skyframe.SkyframePackageLoaderWithValueEnvironment.getTarget(SkyframePackageLoaderWithValueEnvironment.java:71)
	at com.google.devtools.build.lib.skyframe.ConfigurationFragmentFunction$ConfigurationBuilderEnvironment.getTarget(ConfigurationFragmentFunction.java:193)
	at com.google.devtools.build.lib.rules.cpp.CrosstoolConfigurationLoader.getCrosstoolProtofromBuildFile(CrosstoolConfigurationLoader.java:177)
	... 11 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'CONFIGURATION_FRAGMENT:com.google.devtools.build.lib.skyframe.ConfigurationFragmentValue$ConfigurationFragmentKey@2abbbba' (requested by nodes 'CONFIGURATION_COLLECTION:com.google.devtools.build.lib.skyframe.ConfigurationCollectionValue$ConfigurationCollectionKey@1764fa10', 'CONFIGURATION_FRAGMENT:com.google.devtools.build.lib.skyframe.ConfigurationFragmentValue$ConfigurationFragmentKey@253fcc46', 'CONFIGURATION_FRAGMENT:com.google.devtools.build.lib.skyframe.ConfigurationFragmentValue$ConfigurationFragmentKey@ee578016')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:1070)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:474)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: com.google.devtools.build.lib.packages.NoSuchTargetException: no such target '@local_config_cuda//crosstool:toolchain': target 'toolchain' not declared in package 'crosstool' defined by /home/jenisha/.cache/bazel/_bazel_jenisha/09415e5fa53b65f11f76c6af77c3c91f/external/local_config_cuda/crosstool/BUILD
	at com.google.devtools.build.lib.rules.cpp.CrosstoolConfigurationLoader.getCrosstoolProtofromBuildFile(CrosstoolConfigurationLoader.java:179)
	at com.google.devtools.build.lib.rules.cpp.CrosstoolConfigurationLoader.findCrosstoolConfiguration(CrosstoolConfigurationLoader.java:239)
	at com.google.devtools.build.lib.rules.cpp.CrosstoolConfigurationLoader.readCrosstool(CrosstoolConfigurationLoader.java:281)
	at com.google.devtools.build.lib.rules.cpp.CppConfigurationLoader.createParameters(CppConfigurationLoader.java:128)
	at com.google.devtools.build.lib.rules.cpp.CppConfigurationLoader.create(CppConfigurationLoader.java:73)
	at com.google.devtools.build.lib.rules.cpp.CppConfigurationLoader.create(CppConfigurationLoader.java:48)
	at com.google.devtools.build.lib.skyframe.ConfigurationFragmentFunction.compute(ConfigurationFragmentFunction.java:78)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:1016)
	... 4 more
Caused by: com.google.devtools.build.lib.packages.NoSuchTargetException: no such target '@local_config_cuda//crosstool:toolchain': target 'toolchain' not declared in package 'crosstool' defined by /home/jenisha/.cache/bazel/_bazel_jenisha/09415e5fa53b65f11f76c6af77c3c91f/external/local_config_cuda/crosstool/BUILD
	at com.google.devtools.build.lib.packages.Package.makeNoSuchTargetException(Package.java:559)
	at com.google.devtools.build.lib.packages.Package.getTarget(Package.java:543)
	at com.google.devtools.build.lib.skyframe.SkyframePackageLoaderWithValueEnvironment.getTarget(SkyframePackageLoaderWithValueEnvironment.java:71)
	at com.google.devtools.build.lib.skyframe.ConfigurationFragmentFunction$ConfigurationBuilderEnvironment.getTarget(ConfigurationFragmentFunction.java:193)
	at com.google.devtools.build.lib.rules.cpp.CrosstoolConfigurationLoader.getCrosstoolProtofromBuildFile(CrosstoolConfigurationLoader.java:177)
	... 11 more

**Comment by asimshankar** [comment]
That seems to be a different error, see the error log message:
`ERROR: Building with --config=cuda but TensorFlow is not configured to build with GPU support. Please re-run ./configure and enter 'Y' at the prompt to build with GPU support.`

When building for CPU, please re-run `./configure` and do not use `--config=cuda`

**Comment by joyjeni** [comment]
It's taking more than 5 hours to build. I will not build from source again will continue with binary.

**Comment by asimshankar** [comment]
Seems like there is something specific about your environment which we cannot get to the bottom of.

Hopefully the binary installation works for you.

If you do need to install from source and run into trouble again, please do file a new issue with as much information about your specific environment as you can provide. Thanks.

**Comment by AFAgarap** [comment]
What's your bazel version, @joyjeni ?

**Comment by joyjeni** [comment]
Build label: 0.3.1

**Comment by AFAgarap** [comment]
Will you please try re-installing it? I got rid of those Java errors when I re-installed it / upgraded it (can't remember which one was it though) @joyjeni
