### ISSUE TITLE
AutoGraph could not transform call method of keras.Model subclass

### ISSUE THREAD

**Issue by marktodisco** [tensorflow/tensorflow#49962]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
    - I am following along with a tutorial provided by TensorFlow:
        - https://www.tensorflow.org/tutorials/structured_data/time_series
        - The error messages arise when compiling/evaluating the "Baseline" model.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
    - Ubuntu 20.04.2 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
    - N/A
- TensorFlow installed from (source or binary):
    - Anaconda
- TensorFlow version (use command below):
    - After running the command `conda list --export`:
        ```
        # This file may be used to create an environment using:
        # $ conda create --name <env> --file <this file>
        # platform: linux-64
        _libgcc_mutex=0.1=main
        _tflow_select=2.3.0=mkl
        absl-py=0.12.0=py39h06a4308_0
        aiohttp=3.7.4=py39h27cfd23_1
        anyio=2.2.0=py39h06a4308_1
        argon2-cffi=20.1.0=py39h27cfd23_1
        astor=0.8.1=py39h06a4308_0
        astunparse=1.6.3=py_0
        async-timeout=3.0.1=py39h06a4308_0
        async_generator=1.10=pyhd3eb1b0_0
        attrs=21.2.0=pyhd3eb1b0_0
        babel=2.9.1=pyhd3eb1b0_0
        backcall=0.2.0=pyhd3eb1b0_0
        blas=1.0=mkl
        bleach=3.3.0=pyhd3eb1b0_0
        blinker=1.4=py39h06a4308_0
        brotlipy=0.7.0=py39h27cfd23_1003
        c-ares=1.17.1=h27cfd23_0
        ca-certificates=2021.5.25=h06a4308_1
        cachetools=4.2.2=pyhd3eb1b0_0
        certifi=2021.5.30=py39h06a4308_0
        cffi=1.14.5=py39h261ae71_0
        chardet=3.0.4=py39h06a4308_1003
        click=8.0.1=pyhd3eb1b0_0
        coverage=5.5=py39h27cfd23_2
        cryptography=3.4.7=py39hd23ed53_0
        cycler=0.10.0=py39h06a4308_0
        cython=0.29.23=py39h2531618_0
        dbus=1.13.18=hb2f20db_0
        decorator=5.0.9=pyhd3eb1b0_0
        defusedxml=0.7.1=pyhd3eb1b0_0
        entrypoints=0.3=py39h06a4308_0
        expat=2.4.1=h2531618_2
        fontconfig=2.13.1=h6c09931_0
        freetype=2.10.4=h5ab3b9f_0
        gast=0.4.0=py_0
        glib=2.68.2=h36276a3_0
        google-auth=1.30.1=pyhd3eb1b0_0
        google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
        google-pasta=0.2.0=py_0
        grpcio=1.36.1=py39h2157cd5_1
        gst-plugins-base=1.14.0=h8213a91_2
        gstreamer=1.14.0=h28cd5cc_2
        h5py=2.10.0=py39hec9cf62_0
        hdf5=1.10.6=hb1b8bf9_0
        icu=58.2=he6710b0_3
        idna=2.10=pyhd3eb1b0_0
        importlib-metadata=3.10.0=py39h06a4308_0
        importlib_metadata=3.10.0=hd3eb1b0_0
        intel-openmp=2021.2.0=h06a4308_610
        ipykernel=5.3.4=py39hb070fc8_0
        ipython=7.22.0=py39hb070fc8_0
        ipython_genutils=0.2.0=pyhd3eb1b0_1
        jedi=0.17.2=py39h06a4308_1
        jinja2=3.0.0=pyhd3eb1b0_0
        jpeg=9b=h024ee3a_2
        json5=0.9.5=py_0
        jsonschema=3.2.0=py_2
        jupyter-packaging=0.7.12=pyhd3eb1b0_0
        jupyter_client=6.1.12=pyhd3eb1b0_0
        jupyter_core=4.7.1=py39h06a4308_0
        jupyter_server=1.4.1=py39h06a4308_0
        jupyterlab=3.0.14=pyhd3eb1b0_1
        jupyterlab_pygments=0.1.2=py_0
        jupyterlab_server=2.4.0=pyhd3eb1b0_0
        keras-preprocessing=1.1.2=pyhd3eb1b0_0
        kiwisolver=1.3.1=py39h2531618_0
        lcms2=2.12=h3be6417_0
        ld_impl_linux-64=2.33.1=h53a641e_7
        libffi=3.3=he6710b0_2
        libgcc-ng=9.1.0=hdf63c60_0
        libgfortran-ng=7.3.0=hdf63c60_0
        libpng=1.6.37=hbc83047_0
        libprotobuf=3.14.0=h8c45485_0
        libsodium=1.0.18=h7b6447c_0
        libstdcxx-ng=9.1.0=hdf63c60_0
        libtiff=4.2.0=h85742a9_0
        libuuid=1.0.3=h1bed415_2
        libwebp-base=1.2.0=h27cfd23_0
        libxcb=1.14=h7b6447c_0
        libxml2=2.9.10=hb55368b_3
        lz4-c=1.9.3=h2531618_0
        markdown=3.3.4=py39h06a4308_0
        markupsafe=2.0.1=py39h27cfd23_0
        matplotlib=3.3.4=py39h06a4308_0
        matplotlib-base=3.3.4=py39h62a2d02_0
        mistune=0.8.4=py39h27cfd23_1000
        mkl=2021.2.0=h06a4308_296
        mkl-service=2.3.0=py39h27cfd23_1
        mkl_fft=1.3.0=py39h42c9631_2
        mkl_random=1.2.1=py39ha9443f7_2
        multidict=5.1.0=py39h27cfd23_2
        nbclassic=0.2.6=pyhd3eb1b0_0
        nbclient=0.5.3=pyhd3eb1b0_0
        nbconvert=6.0.7=py39h06a4308_0
        nbformat=5.1.3=pyhd3eb1b0_0
        ncurses=6.2=he6710b0_1
        nest-asyncio=1.5.1=pyhd3eb1b0_0
        notebook=6.4.0=py39h06a4308_0
        numpy=1.20.2=py39h2d18471_0
        numpy-base=1.20.2=py39hfae3a4d_0
        oauthlib=3.1.0=py_0
        olefile=0.46=py_0
        openssl=1.1.1k=h27cfd23_0
        opt_einsum=3.3.0=pyhd3eb1b0_1
        packaging=20.9=pyhd3eb1b0_0
        pandas=1.2.4=py39h2531618_0
        pandoc=2.12=h06a4308_0
        pandocfilters=1.4.3=py39h06a4308_1
        parso=0.7.0=py_0
        pcre=8.44=he6710b0_0
        pexpect=4.8.0=pyhd3eb1b0_3
        pickleshare=0.7.5=pyhd3eb1b0_1003
        pillow=8.2.0=py39he98fc37_0
        pip=21.1.1=py39h06a4308_0
        prometheus_client=0.10.1=pyhd3eb1b0_0
        prompt-toolkit=3.0.17=pyh06a4308_0
        protobuf=3.14.0=py39h2531618_1
        ptyprocess=0.7.0=pyhd3eb1b0_2
        pyasn1=0.4.8=py_0
        pyasn1-modules=0.2.8=py_0
        pycparser=2.20=py_2
        pygments=2.9.0=pyhd3eb1b0_0
        pyjwt=2.1.0=py39h06a4308_0
        pyopenssl=20.0.1=pyhd3eb1b0_1
        pyparsing=2.4.7=pyhd3eb1b0_0
        pyqt=5.9.2=py39h2531618_6
        pyrsistent=0.17.3=py39h27cfd23_0
        pysocks=1.7.1=py39h06a4308_0
        python=3.9.5=hdb3f193_3
        python-dateutil=2.8.1=pyhd3eb1b0_0
        python-flatbuffers=1.12=pyhd3eb1b0_0
        pytz=2021.1=pyhd3eb1b0_0
        pyzmq=20.0.0=py39h2531618_1
        qt=5.9.7=h5867ecd_1
        readline=8.1=h27cfd23_0
        requests=2.25.1=pyhd3eb1b0_0
        requests-oauthlib=1.3.0=py_0
        rsa=4.7.2=pyhd3eb1b0_1
        scipy=1.6.2=py39had2a1c9_1
        seaborn=0.11.1=pyhd3eb1b0_0
        send2trash=1.5.0=pyhd3eb1b0_1
        setuptools=52.0.0=py39h06a4308_0
        sip=4.19.13=py39h2531618_0
        six=1.15.0=py39h06a4308_0
        sniffio=1.2.0=py39h06a4308_1
        sqlite=3.35.4=hdfb4753_0
        tensorboard=2.4.0=pyhc547734_0
        tensorboard-plugin-wit=1.6.0=py_0
        tensorflow=2.4.1=mkl_py39h4683426_0
        tensorflow-base=2.4.1=mkl_py39h43e0292_0
        tensorflow-estimator=2.5.0=pyh7b7c402_0
        termcolor=1.1.0=py39h06a4308_1
        terminado=0.9.4=py39h06a4308_0
        testpath=0.4.4=pyhd3eb1b0_0
        tk=8.6.10=hbc83047_0
        tornado=6.1=py39h27cfd23_0
        traitlets=5.0.5=pyhd3eb1b0_0
        typing-extensions=3.7.4.3=hd3eb1b0_0
        typing_extensions=3.7.4.3=pyh06a4308_0
        tzdata=2020f=h52ac0ba_0
        urllib3=1.26.4=pyhd3eb1b0_0
        wcwidth=0.2.5=py_0
        webencodings=0.5.1=py39h06a4308_1
        werkzeug=1.0.1=pyhd3eb1b0_0
        wheel=0.36.2=pyhd3eb1b0_0
        wrapt=1.12.1=py39he8ac12f_1
        xz=5.2.5=h7b6447c_0
        yarl=1.6.3=py39h27cfd23_0
        zeromq=4.3.4=h2531618_0
        zipp=3.4.1=pyhd3eb1b0_0
        zlib=1.2.11=h7b6447c_3
        zstd=1.4.9=haebb681_0
        ```
- Python version:
    - 3.9.5
- Bazel version (if compiling from source):
    - N/A
- GCC/Compiler version (if compiling from source):
    - N/A
- CUDA/cuDNN version:
    - After running the command `nvcc  --version`:
        ```
        nvcc: NVIDIA (R) Cuda compiler driver
        Copyright (c) 2005-2020 NVIDIA Corporation
        Built on Mon_Oct_12_20:09:46_PDT_2020
        Cuda compilation tools, release 11.1, V11.1.105
        Build cuda_11.1.TC455_06.29190527_0
        ```
- GPU model and memory:
    - GeForce RTX 3090, 24 GB
    - NVIDIA-SMI: 460.73.01
    - Driver Version: 460.73.01
    - CUDA Version: 11.2

**Describe the current behavior**
When I  execute the following code:
```
tf.autograph.set_verbosity(10)

baseline = Baseline(label_index=column_indices['T (degC)'])

baseline.compile(loss=tf.losses.MeanSquaredError(),
                 metrics=[tf.metrics.MeanAbsoluteError()])

val_performance = {}
performance = {}
val_performance['Baseline'] = baseline.evaluate(single_step_window.val)
performance['Baseline'] = baseline.evaluate(single_step_window.test, verbose=0)
```
I receive the following error messages:
```
INFO:tensorflow:Converted call: <function timeseries_dataset_from_array.<locals>.<lambda> at 0x7f3b4c2773a0>
    args: (<tf.Tensor 'args_0:0' shape=() dtype=int64>, <tf.Tensor 'args_1:0' shape=(14017,) dtype=int32>)
    kwargs: {}

INFO:tensorflow:Allowlisted: <function timeseries_dataset_from_array.<locals>.<lambda> at 0x7f3b4c2773a0>: DoNotConvert rule for tensorflow
INFO:tensorflow:Converted call: <function sequences_from_indices.<locals>.<lambda> at 0x7f3b4b9509d0>
    args: (<tf.Tensor 'args_0:0' shape=(14018, 19) dtype=float32>, <tf.Tensor 'args_1:0' shape=(None,) dtype=int32>)
    kwargs: {}

INFO:tensorflow:Allowlisted: <function sequences_from_indices.<locals>.<lambda> at 0x7f3b4b9509d0>: DoNotConvert rule for tensorflow
INFO:tensorflow:Converted call: <bound method WindowGenerator.split_window of Total window size: 2
Input indices: [0]
Label indices: [1]
Label column name(s): ['T (degC)']>
    args: (<tf.Tensor 'args_0:0' shape=(None, None, 19) dtype=float32>,)
    kwargs: {}

INFO:tensorflow:Allowlisted <bound method WindowGenerator.split_window of Total window size: 2
Input indices: [0]
Label indices: [1]
Label column name(s): ['T (degC)']>: from cache
INFO:tensorflow:Converted call: <function Model.make_test_function.<locals>.test_function at 0x7f3b4b950280>
    args: (<tensorflow.python.data.ops.iterator_ops.OwnedIterator object at 0x7f3b4b954df0>,)
    kwargs: {}

INFO:tensorflow:<function Model.make_test_function.<locals>.test_function at 0x7f3b4b950280> is not cached for subkey ConversionOptions[{}]
INFO:tensorflow:Source code of <function Model.make_test_function.<locals>.test_function at 0x7f3b4b950280>:

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
def test_function(iterator):
  """Runs an evaluation execution with one step."""
  return step_function(self, iterator)


INFO:tensorflow:Transformed <function Model.make_test_function.<locals>.test_function at 0x7f3b4b950280>:

# coding=utf-8
def tf__test_function(iterator):
    'Runs an evaluation execution with one step.'
    with ag__.FunctionScope('test_function', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
        do_return = False
        retval_ = ag__.UndefinedReturnValue()
        try:
            do_return = True
            retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
        except:
            do_return = False
            raise
        return fscope.ret(retval_, do_return)

INFO:tensorflow:Defaults of <function outer_factory.<locals>.inner_factory.<locals>.tf__test_function at 0x7f3b4b7f2310> : None
INFO:tensorflow:KW defaults of <function outer_factory.<locals>.inner_factory.<locals>.tf__test_function at 0x7f3b4b7f2310> : None
INFO:tensorflow:Calling <function outer_factory.<locals>.inner_factory.<locals>.tf__test_function at 0x7f3b4b7f2310> with
    iterator: <tensorflow.python.data.ops.iterator_ops.OwnedIterator object at 0x7f3b4b954df0>

INFO:tensorflow:Converted call: <function Model.make_test_function.<locals>.step_function at 0x7f3b4b91bca0>
    args: (<__main__.Baseline object at 0x7f3b4b8e75e0>, <tensorflow.python.data.ops.iterator_ops.OwnedIterator object at 0x7f3b4b954df0>)
    kwargs: None

INFO:tensorflow:Allowlisted: <function Model.make_test_function.<locals>.step_function at 0x7f3b4b91bca0>: DoNotConvert rule for tensorflow
INFO:tensorflow:Converted call: <function Model.make_test_function.<locals>.step_function.<locals>.run_step at 0x7f3b4b7f2ca0>
    args: ((<tf.Tensor 'IteratorGetNext:0' shape=(None, 1, 19) dtype=float32>, <tf.Tensor 'IteratorGetNext:1' shape=(None, 1, 1) dtype=float32>),)
    kwargs: {}

INFO:tensorflow:Allowlisted: <function Model.make_test_function.<locals>.step_function.<locals>.run_step at 0x7f3b4b7f2ca0>: DoNotConvert rule for tensorflow
INFO:tensorflow:Converted call: <bound method Baseline.call of <__main__.Baseline object at 0x7f3b4b8e75e0>>
    args: (<tf.Tensor 'IteratorGetNext:0' shape=(None, 1, 19) dtype=float32>,)
    kwargs: {}

INFO:tensorflow:Not allowed: <method-wrapper '__call__' of method object at 0x7f3b4b932a80>: default rule
INFO:tensorflow:Not allowed: <class '__main__.Baseline'>: default rule
INFO:tensorflow:Not allowed: <bound method Baseline.call of <__main__.Baseline object at 0x7f3b4b8e75e0>>: default rule
INFO:tensorflow:<bound method Baseline.call of <__main__.Baseline object at 0x7f3b4b8e75e0>> is not cached for subkey ConversionOptions[{}]
INFO:tensorflow:Source code of <bound method Baseline.call of <__main__.Baseline object at 0x7f3b4b8e75e0>>:

def call(self, inputs):
    if self.label_index is None:
        return inputs
    result = inputs[:, :, self.label_index]
    return result[:, :, tf.newaxis]


INFO:tensorflow:Error transforming entity <bound method Baseline.call of <__main__.Baseline object at 0x7f3b4b8e75e0>>
Traceback (most recent call last):
  File "/home/mark/anaconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 447, in converted_call
    converted_f = _convert_actual(target_entity, program_ctx)
  File "/home/mark/anaconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 284, in _convert_actual
    transformed, module, source_map = _TRANSPILER.transform(entity, program_ctx)
  File "/home/mark/anaconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 286, in transform
    return self.transform_function(obj, user_context)
  File "/home/mark/anaconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 470, in transform_function
    nodes, ctx = super(PyToPy, self).transform_function(fn, user_context)
  File "/home/mark/anaconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 363, in transform_function
    result = self.transform_ast(node, context)
  File "/home/mark/anaconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 252, in transform_ast
    node = self.initial_analysis(node, ctx)
  File "/home/mark/anaconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 239, in initial_analysis
    node = qual_names.resolve(node)
  File "/home/mark/anaconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/python/autograph/pyct/qual_names.py", line 252, in resolve
    return QnResolver().visit(node)
  File "/home/mark/anaconda3/envs/tf2/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/home/mark/anaconda3/envs/tf2/lib/python3.9/ast.py", line 483, in generic_visit
    value = self.visit(value)
  File "/home/mark/anaconda3/envs/tf2/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/home/mark/anaconda3/envs/tf2/lib/python3.9/ast.py", line 492, in generic_visit
    new_node = self.visit(old_value)
  File "/home/mark/anaconda3/envs/tf2/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/home/mark/anaconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/python/autograph/pyct/qual_names.py", line 232, in visit_Subscript
    if not isinstance(s, gast.Index):
AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:AutoGraph could not transform <bound method Baseline.call of <__main__.Baseline object at 0x7f3b4b8e75e0>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
INFO:tensorflow:Converted call: <bound method LossFunctionWrapper.call of <tensorflow.python.keras.losses.MeanSquaredError object at 0x7f3b4b30ec10>>
    args: (<tf.Tensor 'IteratorGetNext:1' shape=(None, 1, 1) dtype=float32>, <tf.Tensor 'baseline/strided_slice_1:0' shape=(None, 1, 1) dtype=float32>)
    kwargs: {}

INFO:tensorflow:Allowlisted: <bound method LossFunctionWrapper.call of <tensorflow.python.keras.losses.MeanSquaredError object at 0x7f3b4b30ec10>>: DoNotConvert rule for tensorflow
INFO:tensorflow:Converted call: <bound method Reduce.update_state of <tensorflow.python.keras.metrics.Mean object at 0x7f3b4b89cb80>>
    args: (<tf.Tensor 'mean_squared_error/weighted_loss/value:0' shape=() dtype=float32>,)
    kwargs: {'sample_weight': <tf.Tensor 'strided_slice:0' shape=() dtype=int32>}

INFO:tensorflow:Allowlisted: <bound method Reduce.update_state of <tensorflow.python.keras.metrics.Mean object at 0x7f3b4b89cb80>>: DoNotConvert rule for tensorflow
INFO:tensorflow:Converted call: <bound method MeanMetricWrapper.update_state of <tensorflow.python.keras.metrics.MeanAbsoluteError object at 0x7f3b4b89c460>>
    args: (<tf.Tensor 'IteratorGetNext:1' shape=(None, 1, 1) dtype=float32>, <tf.Tensor 'baseline/strided_slice_1:0' shape=(None, 1, 1) dtype=float32>)
    kwargs: {'sample_weight': None}

INFO:tensorflow:Allowlisted: <bound method MeanMetricWrapper.update_state of <tensorflow.python.keras.metrics.MeanAbsoluteError object at 0x7f3b4b89c460>>: DoNotConvert rule for tensorflow
INFO:tensorflow:Converted call: <bound method Reduce.result of <tensorflow.python.keras.metrics.Mean object at 0x7f3b4b89cb80>>
    args: ()
    kwargs: {}

INFO:tensorflow:Allowlisted: <bound method Reduce.result of <tensorflow.python.keras.metrics.Mean object at 0x7f3b4b89cb80>>: DoNotConvert rule for tensorflow
INFO:tensorflow:Converted call: <bound method Reduce.result of <tensorflow.python.keras.metrics.MeanAbsoluteError object at 0x7f3b4b89c460>>
    args: ()
    kwargs: {}

INFO:tensorflow:Allowlisted <bound method Reduce.result of <tensorflow.python.keras.metrics.MeanAbsoluteError object at 0x7f3b4b89c460>>: from cache
439/439 [==============================] - 0s 514us/step - loss: 0.0135 - mean_absolute_error: 0.0806
INFO:tensorflow:Converted call: <function timeseries_dataset_from_array.<locals>.<lambda> at 0x7f3b4b9500d0>
    args: (<tf.Tensor 'args_0:0' shape=() dtype=int64>, <tf.Tensor 'args_1:0' shape=(7009,) dtype=int32>)
    kwargs: {}

INFO:tensorflow:Allowlisted: <function timeseries_dataset_from_array.<locals>.<lambda> at 0x7f3b4b9500d0>: DoNotConvert rule for tensorflow
INFO:tensorflow:Converted call: <function sequences_from_indices.<locals>.<lambda> at 0x7f3b4b3f88b0>
    args: (<tf.Tensor 'args_0:0' shape=(7010, 19) dtype=float32>, <tf.Tensor 'args_1:0' shape=(None,) dtype=int32>)
    kwargs: {}

INFO:tensorflow:Allowlisted: <function sequences_from_indices.<locals>.<lambda> at 0x7f3b4b3f88b0>: DoNotConvert rule for tensorflow
INFO:tensorflow:Converted call: <bound method WindowGenerator.split_window of Total window size: 2
Input indices: [0]
Label indices: [1]
Label column name(s): ['T (degC)']>
    args: (<tf.Tensor 'args_0:0' shape=(None, None, 19) dtype=float32>,)
    kwargs: {}

INFO:tensorflow:Allowlisted <bound method WindowGenerator.split_window of Total window size: 2
Input indices: [0]
Label indices: [1]
Label column name(s): ['T (degC)']>: from cache
```

**Describe the expected behavior**
I expect to receive zero error messages.

**[Contributing](https://www.tensorflow.org/community/contribute)** - Do you want to contribute a PR? (yes/no): - Briefly describe your candidate solution (if contributing):
No.

**Standalone code to reproduce the issue**
All of the code is available in the TensorFlow tutorial at: https://www.tensorflow.org/tutorials/structured_data/time_series
The Anaconda environment may also be created in the "TensorFlow version" section above.

**Comment by UsharaniPagadala** [comment]
@marktodisco 
Make sure you followed the same tested build configurations for [gpu](https://github.com/ContinuumIO/anaconda-issues/issues)
`

Version | Python version | Compiler | Build tools | cuDNN | CUDA
-- | -- | -- | -- | -- | --
tensorflow_gpu-2.5.0 | 3.6-3.9 | MSVC 2019 | Bazel 3.7.2 | 8.1 | 11.2
tensorflow_gpu-2.4.0 | 3.6-3.8 | MSVC 2019 | Bazel 3.1.0 | 8.0 | 11.0


<br class="Apple-interchange-newline">`
 and
We don't support for Anaconda Environment,Please post this in this respective [repo](https://github.com/ContinuumIO/anaconda-issues/issues).Thanks

**Comment by marktodisco** [comment]
Apparently, I did not install TensorFlow correctly, so thank you for the clarification. However, I personally think TensorFlow-GPU has an overly complicated installation process when compared with PyTorch. I hope the TensorFlow team can address this issue in the future, opening the doors to a much broader userbase.
