### ISSUE TITLE
ValueError: inputs must be an iterable of at least one Tensor/IndexedSlices with the same dtype and shape

### ISSUE THREAD

**Issue by ucasiggcas** [tensorflow/tensorflow#50014]
```
>>> for epoch in range(3):
...         for inputs in train2.batch(1):
...             inputs=[tf.squeeze(k) for k in inputs]
...             with tf.GradientTape() as tape:
...                 loss=model.train_step(inputs)
```

codes similar as the [issue](https://github.com/tensorflow/tensorflow/issues/49907), but the bug is not

```
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/data/logs/xulm1/debiasing_rush/tf2_dist_data2.py", line 145, in train_step
    loss=self.loss_function(next_item,logits)
  File "/data/logs/xulm1/debiasing_rush/tf2_dist_data2.py", line 132, in loss_function
    self.loss_train = self.loss + tf.add_n([tf.nn.l2_loss(v) for v in tf.compat.v1.trainable_variables()]) * self.l2#最后一项影响较大
  File "/data/logs/xulm1/myconda/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/data/logs/xulm1/myconda/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py", line 3497, in add_n
    raise ValueError("inputs must be an iterable of at least one "
ValueError: inputs must be an iterable of at least one Tensor/IndexedSlices with the same dtype and shape
```

could you please help me ?
thx

**Comment by ucasiggcas** [comment]
```
>>> inputs
[<tf.Tensor: shape=(512, 19, 19), dtype=float32, numpy=...>, <tf.Tensor: shape=(512, 19, 19), dtype=float32, numpy=..., dtype=float32)>, <tf.Tensor: shape=(512, 19), dtype=int32, numpy=..., dtype=int32)>, <tf.Tensor: shape=(512,), dtype=int32, numpy=..., dtype=int32)>, <tf.Tensor: shape=(512,), dtype=int32, numpy=...>
```
so what's the problem ?
thx

**Comment by ucasiggcas** [comment]
Now I find the problem ,
`tf.add_n([tf.nn.l2_loss(v) for v in tf.compat.v1.trainable_variables()]) * self.l2`
but how to modify the up code in tf2 version ? 
I want the all trainable variables !
please help me ?
thx

**Comment by ucasiggcas** [comment]
and how to change the code down, same as up
`gradients = tape.gradient(loss, tf.compat.v1.trainable_variables())`

**Comment by tilakrayal** [comment]
@ucasiggcas ,

In order to expedite the trouble-shooting process, could you please provide a minimal code snippet or gist and the TensorFlow version you are using.

Thanks!

**Comment by ucasiggcas** [comment]
hi，dear
the problem is how to translate the code to tf2,
`tf.compat.v1.trainable_variables()`

**Comment by Saduf2019** [comment]
@ucasiggcas 
please refer to the example in [this link](https://www.tensorflow.org/guide/keras/writing_a_training_loop_from_scratch)which explains everything from scratch in detail.
