### ISSUE TITLE
Failed to convert SparseTensor to Tensor (TensorFlow 2.5)

### ISSUE THREAD

**Issue by SohamBhattacharya** [tensorflow/tensorflow#50078]
Dear experts,
I am using TensorFlow 2.5 with Python 3.8.10. I have pip-installed TF2.5 within an anaconda environment.
When trying out this code [1] (where I create a dummy dataset consisting of 2 classes (label) of `SparseTensor`s and use it to train a simple CNN), I get the error [2]. I have seen that this issue has been raised for TF2.4 (https://github.com/tensorflow/tensorflow/issues/47931), but didn't see an issue raised for TF2.5. I know I can convert the sparse tensor to dense 'on-the-fly' in a generator Dataset and pass that is input. However, I wanted to run the training on sparse tensors themselves to speed it up. Is there any workaround known for TF2.5?

Thanks in advance.

[1]
```
import numpy
import tensorflow

from tensorflow.keras import datasets, layers, models
from tensorflow.keras import mixed_precision


# No. of images
nImg = 1000

nBinX = 50
nBinY = 50

# No. of layers/channels
nLayer = 1

nPixelTot = nBinX*nBinY

l_idx = []
l_val = []
l_label = []

# Create a sparse dataset with random entries
for iImg in range(0, nImg) :
    
    # Fill at most 60 pixels
    nFill = numpy.random.randint(low = 1, high = 61)
    
    for iFill in range(0, nFill) :
        
        # Index of the filled pixel
        # [image idx, row idx, col idx, layer]
        idx = [
            iImg,
            numpy.random.randint(low = 0, high = nBinY),
            numpy.random.randint(low = 0, high = nBinX),
            nLayer-1,
        ]
        
        if (idx in l_idx) :
            continue
        
        l_idx.append(idx)
        l_val.append(numpy.random.rand())
    
    l_label.append(numpy.random.randint(low = 0, high = 2))


img_shape = (nBinY, nBinX, nLayer)
dense_shape = (nImg, nBinY, nBinX, nLayer)

# Create the sparse rensor
input_img_sparseTensor = tensorflow.sparse.reorder(tensorflow.sparse.SparseTensor(
    indices = l_idx,
    values = l_val,
    dense_shape = dense_shape,
))


print("=====> Creating dataset...")

dataset_img = tensorflow.data.Dataset.from_tensor_slices(input_img_sparseTensor)
dataset_label = tensorflow.data.Dataset.from_tensor_slices(l_label)

batch_size = 100

dataset = tensorflow.data.Dataset.zip((dataset_img, dataset_label)).batch(batch_size)

print("dataset.element_spec:", dataset.element_spec)
print("=====> Created dataset...")


# Dummy CNN model
model = models.Sequential()

##model.add(layers.InputLayer(input_shape = img_shape, sparse = True, batch_size = batch_size))
model.add(layers.Conv2D(10, kernel_size = (10, 10), activation = "relu", input_shape = img_shape))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(5, kernel_size = (5, 5), activation = "relu"))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Flatten())
model.add(layers.Dense(50, activation = "relu"))
model.add(layers.Dense(2, activation = "relu"))

model.summary()

print("=====> Compiling model...")

model.compile(
    optimizer = "adam",
    loss = tensorflow.keras.losses.SparseCategoricalCrossentropy(from_logits = True),
    metrics = ["accuracy"],
)

print("=====> Compiled model...")

print("=====> Starting fit...")

# Use the same data for train and test, just to check if it runs
history = model.fit(
    x = dataset,
    epochs = 5,
    #batch_size = batch_size,
    validation_data = dataset,
    shuffle = False,
)
```

[2]
```
Traceback (most recent call last):
  File "test_tensorflowSparseTensor.py", line 100, in <module>
    history = model.fit(
  File "/nfs/dust/cms/user/sobhatta/opt/anaconda3p8/envs/conda_env_python3p8/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1183, in fit
    tmp_logs = self.train_function(iterator)
  File "/nfs/dust/cms/user/sobhatta/opt/anaconda3p8/envs/conda_env_python3p8/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "/nfs/dust/cms/user/sobhatta/opt/anaconda3p8/envs/conda_env_python3p8/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 933, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/nfs/dust/cms/user/sobhatta/opt/anaconda3p8/envs/conda_env_python3p8/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 763, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/nfs/dust/cms/user/sobhatta/opt/anaconda3p8/envs/conda_env_python3p8/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3050, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/nfs/dust/cms/user/sobhatta/opt/anaconda3p8/envs/conda_env_python3p8/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3444, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/nfs/dust/cms/user/sobhatta/opt/anaconda3p8/envs/conda_env_python3p8/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3279, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/nfs/dust/cms/user/sobhatta/opt/anaconda3p8/envs/conda_env_python3p8/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 999, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/nfs/dust/cms/user/sobhatta/opt/anaconda3p8/envs/conda_env_python3p8/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 672, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/nfs/dust/cms/user/sobhatta/opt/anaconda3p8/envs/conda_env_python3p8/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 986, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    /nfs/dust/cms/user/sobhatta/opt/anaconda3p8/envs/conda_env_python3p8/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:855 train_function  *
        return step_function(self, iterator)
    /nfs/dust/cms/user/sobhatta/opt/anaconda3p8/envs/conda_env_python3p8/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:845 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /nfs/dust/cms/user/sobhatta/opt/anaconda3p8/envs/conda_env_python3p8/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:1285 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /nfs/dust/cms/user/sobhatta/opt/anaconda3p8/envs/conda_env_python3p8/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:2833 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /nfs/dust/cms/user/sobhatta/opt/anaconda3p8/envs/conda_env_python3p8/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:3608 _call_for_each_replica
        return fn(*args, **kwargs)
    /nfs/dust/cms/user/sobhatta/opt/anaconda3p8/envs/conda_env_python3p8/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:838 run_step  **
        outputs = model.train_step(data)
    /nfs/dust/cms/user/sobhatta/opt/anaconda3p8/envs/conda_env_python3p8/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:795 train_step
        y_pred = self(x, training=True)
    /nfs/dust/cms/user/sobhatta/opt/anaconda3p8/envs/conda_env_python3p8/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py:1030 __call__
        outputs = call_fn(inputs, *args, **kwargs)
    /nfs/dust/cms/user/sobhatta/opt/anaconda3p8/envs/conda_env_python3p8/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py:380 call
        return super(Sequential, self).call(inputs, training=training, mask=mask)
    /nfs/dust/cms/user/sobhatta/opt/anaconda3p8/envs/conda_env_python3p8/lib/python3.8/site-packages/tensorflow/python/keras/engine/functional.py:420 call
        return self._run_internal_graph(
    /nfs/dust/cms/user/sobhatta/opt/anaconda3p8/envs/conda_env_python3p8/lib/python3.8/site-packages/tensorflow/python/keras/engine/functional.py:556 _run_internal_graph
        outputs = node.layer(*args, **kwargs)
    /nfs/dust/cms/user/sobhatta/opt/anaconda3p8/envs/conda_env_python3p8/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py:1030 __call__
        outputs = call_fn(inputs, *args, **kwargs)
    /nfs/dust/cms/user/sobhatta/opt/anaconda3p8/envs/conda_env_python3p8/lib/python3.8/site-packages/tensorflow/python/keras/layers/convolutional.py:249 call
        outputs = self._convolution_op(inputs, self.kernel)
    /nfs/dust/cms/user/sobhatta/opt/anaconda3p8/envs/conda_env_python3p8/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py:206 wrapper
        return target(*args, **kwargs)
    /nfs/dust/cms/user/sobhatta/opt/anaconda3p8/envs/conda_env_python3p8/lib/python3.8/site-packages/tensorflow/python/ops/nn_ops.py:1012 convolution_v2
        return convolution_internal(
    /nfs/dust/cms/user/sobhatta/opt/anaconda3p8/envs/conda_env_python3p8/lib/python3.8/site-packages/tensorflow/python/ops/nn_ops.py:1142 convolution_internal
        return op(
    /nfs/dust/cms/user/sobhatta/opt/anaconda3p8/envs/conda_env_python3p8/lib/python3.8/site-packages/tensorflow/python/ops/nn_ops.py:2596 _conv2d_expanded_batch
        return gen_nn_ops.conv2d(
    /nfs/dust/cms/user/sobhatta/opt/anaconda3p8/envs/conda_env_python3p8/lib/python3.8/site-packages/tensorflow/python/ops/gen_nn_ops.py:969 conv2d
        _, _, _op, _outputs = _op_def_library._apply_op_helper(
    /nfs/dust/cms/user/sobhatta/opt/anaconda3p8/envs/conda_env_python3p8/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py:525 _apply_op_helper
        raise err
    /nfs/dust/cms/user/sobhatta/opt/anaconda3p8/envs/conda_env_python3p8/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py:517 _apply_op_helper
        values = ops.convert_to_tensor(
    /nfs/dust/cms/user/sobhatta/opt/anaconda3p8/envs/conda_env_python3p8/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py:163 wrapped
        return func(*args, **kwargs)
    /nfs/dust/cms/user/sobhatta/opt/anaconda3p8/envs/conda_env_python3p8/lib/python3.8/site-packages/tensorflow/python/framework/ops.py:1566 convert_to_tensor
        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    /nfs/dust/cms/user/sobhatta/opt/anaconda3p8/envs/conda_env_python3p8/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py:339 _constant_tensor_conversion_function
        return constant(v, dtype=dtype, name=name)
    /nfs/dust/cms/user/sobhatta/opt/anaconda3p8/envs/conda_env_python3p8/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py:264 constant
        return _constant_impl(value, dtype, shape, name, verify_shape=False,
    /nfs/dust/cms/user/sobhatta/opt/anaconda3p8/envs/conda_env_python3p8/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py:281 _constant_impl
        tensor_util.make_tensor_proto(
    /nfs/dust/cms/user/sobhatta/opt/anaconda3p8/envs/conda_env_python3p8/lib/python3.8/site-packages/tensorflow/python/framework/tensor_util.py:551 make_tensor_proto
        raise TypeError("Failed to convert object of type %s to Tensor. "

    TypeError: Failed to convert object of type <class 'tensorflow.python.framework.sparse_tensor.SparseTensor'> to Tensor. Contents: SparseTensor(indices=Tensor("DeserializeSparse:0", shape=(None, 4), dtype=int64), values=Tensor("DeserializeSparse:1", shape=(None,), dtype=float32), dense_shape=Tensor("stack:0", shape=(4,), dtype=int64)). Consider casting elements to a supported type.
```

**Comment by UsharaniPagadala** [comment]
@Saduf2019 

I was able to replicate the issue tf2.5 and tf nightly.Please find the [gist](https://colab.research.google.com/gist/UsharaniPagadala/64694ec1286c6d6d40620666088d2709/untitled79.ipynb).Thanks

**Comment by s-pike** [comment]
I think [this](https://stackoverflow.com/questions/67933642/tensoflow-sparsetensor-input-gives-value-error-for-multi-dimensional-input-shape) is a simple version of the same problem:

I have a keras model which takes multi-dimensional input data. When I build a model, setting the input shape to anything with multiple dimensions  and sparse=True, I get the following error:
> ValueError: Attempt to convert a value (<tensorflow.python.framework.sparse_tensor.SparseTensor object at 0x000002D24207B400>) with an unsupported type (<class 'tensorflow.python.framework.sparse_tensor.SparseTensor'>) to a Tensor.

Following [the sparse tensor guide][1], this works for me:
```
import tensorflow as tf

x = tf.keras.Input(shape=(4,), sparse=True)
y = tf.keras.layers.Dense(4)(x)
model = tf.keras.Model(x, y)
```
But if I add in another dimension, I get the error (which occurs at the second line):
```
x = tf.keras.Input(shape=(4,2, ), sparse=True)
y = tf.keras.layers.Dense(4)(x)
model = tf.keras.Model(x, y)
```
If I set `sparse=False` then the error goes away:
```
x = tf.keras.Input(shape=(4,2, ), sparse=False)
y = tf.keras.layers.Dense(4)(x)
model = tf.keras.Model(x, y)
```


  [1]: https://www.tensorflow.org/guide/sparse_tensor#tfkeras

**Comment by Saduf2019** [comment]
You may follow [this colab](https://colab.research.google.com/drive/1tKQlRLhD7hvsuewM2NXSUqbEx1EwO3s8?usp=sharing), where the issue does not occur.

**Comment by SohamBhattacharya** [comment]
> You may follow [this colab](https://colab.research.google.com/drive/1tKQlRLhD7hvsuewM2NXSUqbEx1EwO3s8?usp=sharing), where the issue does not occur.
> 
> Lambda layer created and appended on top of your model, which converts your sparse tensor to dense.

@Saduf2019 Thank you for the pointer.
Yes, I'm aware that I can create a Lamda layer and convert the sparse tensor to dense 'on the fly', but that adds another preprocessing step. I was wondering if I can apply Conv2D on a sparse tensor directly. From the documentation, this does not seem to be forbidden -- so is this bug fixed in some nightly version?

**Comment by jvishnuvardhan** [comment]
@SohamBhattacharya I think sparse input is not supported by `Conv2D`. Some other layers like `Dense` supports sparse tensors. As mentioned above, You could convert sparse tensors into dense tensors and pass it to the Conv layers. Thanks!

https://www.tensorflow.org/guide/sparse_tensor

If your use case demands this kind of feature, then open a feature request in [keras-team/keras](https://github.com/keras-team/keras/issues) repo as Keras team moved to that repo to focus entirely on keras development. Also, mention more details about your feature request when you open the issue. Thanks!

**Comment by SohamBhattacharya** [comment]
@jvishnuvardhan Thanks for the clarification and suggestion.
