### ISSUE TITLE
ImportError: DLL load failed with error code 3221225501 while importing _pywrap_tensorflow_internal

### ISSUE THREAD

**Issue by 1619513467** [tensorflow/tensorflow#50115]
Traceback (most recent call last):
  File "C:\Users\风中叶子\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\风中叶子\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\风中叶子\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "F:\python\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "F:\python\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code 3221225501 while importing _pywrap_tensorflow_internal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo5.py", line 2, in <module>
    import tensorflow as tf
  File "C:\Users\风中叶子\AppData\Roaming\Python\Python38\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\风中叶子\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\__init__.py", line 50, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\风中叶子\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\pywrap_tensorflow.py", line 69, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\风中叶子\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\风中叶子\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\风中叶子\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "F:\python\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "F:\python\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code 3221225501 while importing _pywrap_tensorflow_internal

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by tilakrayal** [comment]
@1619513467 ,

In order to expedite the trouble-shooting process, could you please provide the following information
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
TensorFlow installed from (source or binary):
TensorFlow version:
Python version:
Installed using virtualenv? pip? conda?:
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory:
 
and the exact sequence of commands / steps that you executed before running into the problem

**Comment by tilakrayal** [comment]
Looking at the error log, seems like it is similar to this issues and let us know if it helps.[Link1](https://github.com/tensorflow/tensorflow/issues/42103#issuecomment-670291410),[Link2](https://github.com/tensorflow/tensorflow/issues/35598).
Thanks!
