### ISSUE TITLE
Error executing download_and_preprocess_imagenet

### ISSUE THREAD

**Issue by klattimer** [tensorflow/tensorflow#5012]
### Environment info

Operating System: macOS Yosemite

Installed version of CUDA and cuDNN: 
None (CPU only)

If installed from binary pip package, provide:
1. A link to the pip package you installed:
   https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.11.0rc0-py3-none-any.whl
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
   0.11.0rc0
### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

When following the guide (https://github.com/tensorflow/models/tree/master/inception) for configuring inceptionv3 I ran this command;
bazel-bin/inception/download_and_preprocess_imagenet "${DATA_DIR}"
### What other attempted solutions have you tried?

None
### Logs or other output that would be helpful

Finished downloading and preprocessing the ImageNet data.
Saving results to /Volumes/Seagate External/imagenet
Successfully read 615299 bounding boxes across 544546 images.
Determining list of input files and labels from /Volumes/Seagate External/imagenet/raw-data/validation/.
Finished finding files in 100 of 1000 classes.
Finished finding files in 200 of 1000 classes.
Finished finding files in 300 of 1000 classes.
Finished finding files in 400 of 1000 classes.
Finished finding files in 500 of 1000 classes.
Finished finding files in 600 of 1000 classes.
Finished finding files in 700 of 1000 classes.
Finished finding files in 800 of 1000 classes.
Finished finding files in 900 of 1000 classes.
Finished finding files in 1000 of 1000 classes.
Traceback (most recent call last):
 File "/private/var/tmp/_bazel_karllattimer/ed3d80c94eb22e8491a82fd78ab7022c/inception/bazel-out/local-fastbuild/bin/inception/build_imagenet_data.runfiles/inception/inception/data/build_imagenet_data.py", line 704, in <module>
   tf.app.run()
 File "/Users/karllattimer/Projects/tensorflow-testing/venv/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 30, in run
   sys.exit(main(sys.argv[:1] + flags_passthrough))
 File "/private/var/tmp/_bazel_karllattimer/ed3d80c94eb22e8491a82fd78ab7022c/inception/bazel-out/local-fastbuild/bin/inception/build_imagenet_data.runfiles/inception/inception/data/build_imagenet_data.py", line 698, in main
   FLAGS.validation_shards, synset_to_human, image_to_bboxes)
 File "/private/var/tmp/_bazel_karllattimer/ed3d80c94eb22e8491a82fd78ab7022c/inception/bazel-out/local-fastbuild/bin/inception/build_imagenet_data.runfiles/inception/inception/data/build_imagenet_data.py", line 597, in _process_dataset
   filenames, synsets, labels = _find_image_files(directory, FLAGS.labels_file)
 File "/private/var/tmp/_bazel_karllattimer/ed3d80c94eb22e8491a82fd78ab7022c/inception/bazel-out/local-fastbuild/bin/inception/build_imagenet_data.runfiles/inception/inception/data/build_imagenet_data.py", line 529, in _find_image_files
   random.shuffle(shuffled_index)
 File "/Users/karllattimer/Projects/tensorflow-testing/venv/lib/python3.5/random.py", line 272, in shuffle
   x[i], x[j] = x[j], x[i]

**Comment by asimshankar** [comment]
It seems you're using Python 3.5 and the `download_and_preprocess_imagenet` tool is written for 2.7. (I'm guessing, but could you confirm that the last line of the output was: `TypeError: 'range' object does not support item assignment`?)

Can you try with either using python 2.7 or changing [line number 529](https://github.com/tensorflow/models/blob/master/inception/inception/data/build_imagenet_data.py#L529) in `inception/data/build_imagenet_data.py` from `random.shuffle(shuffled_index)` to `random.shuffle(list(shuffled_index))` before rerunning `bazel build inception/download_and_preprocess_imagenet`?

Thanks.

**Comment by aselle** [comment]
@klattimer, any luck with changing what @asimshankar suggests?

**Comment by klattimer** [comment]
I'm hoping to get time shortly.

**Comment by girving** [comment]
@klattimer Closing due to lack of response, but we're happy to reopen if you're still having the problem.

**Comment by samkitjain** [comment]
I was facing same problem. Proposed solution fixes it.
