### ISSUE TITLE
What is the reason for very low GPU utilization?

### ISSUE THREAD

**Issue by monacv** [tensorflow/tensorflow#50139]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
```
$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.9.2009 (Core)
Release:	7.9.2009
Codename:	Core
```

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):
```
$ pip freeze | grep tensorflow
tensorflow-estimator==2.2.0
tensorflow-gpu==2.2.0
 
```
- Python version:
```
$ python
Python 3.8.5 (default, Mar 31 2021, 02:37:07) 
[GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux
```

- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
```
$ gcc --version
gcc (GCC) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
```
- CUDA/cuDNN version:
```
stat /usr/local/cuda
  File: ‘/usr/local/cuda’ -> ‘/usr/local/cuda-10.2’
  Size: 20          Blocks: 0          IO Block: 4096   symbolic link
Device: fd00h/64768d    Inode: 67157410    Links: 1
Access: (0777/lrwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Context: unconfined_u:object_r:usr_t:s0
Access: 2021-05-20 10:43:06.864530636 -0400
Modify: 2020-09-21 09:39:18.559883390 -0400
Change: 2020-09-21 09:39:18.559883390 -0400
 Birth: -
```

- GPU model and memory:
```
$ sudo lshw -C display
[sudo] password for jalal: 
  *-display                 
       description: VGA compatible controller
       product: GP102 [GeForce GTX 1080 Ti]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:06:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:89 memory:f8000000-f8ffffff memory:a0000000-afffffff memory:b0000000-b1ffffff ioport:d000(size=128) memory:f9000000-f907ffff
  *-display
       description: VGA compatible controller
       product: GP102 [GeForce GTX 1080 Ti]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:05:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:88 memory:fa000000-faffffff memory:c0000000-cfffffff memory:d0000000-d1ffffff ioport:e000(size=128) memory:fb000000-fb07ffff

```

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
```
>>> import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)
v2.2.0-rc4-8-g2b96f3662b 2.2.0

```
**Describe the current behavior**

**Describe the expected behavior**

**[Contributing](https://www.tensorflow.org/community/contribute)** - Do you
want to contribute a PR? (yes/no): - Briefly describe your candidate solution
(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

I am not sure why this code is barely using GPU memory and why the GPU utilization is very low? It shows it is using both of my GPUs indeed. How can I fix this? Also, for 1000 images, how long does this step take approximately?

`$ python Feature_extraction.py --input_list ../vertex_path_GT.txt --model pointnet_hico --model_path ../Feature_extraction/model_10000.ckpt`

I run the code from this directory:
`/scratch3/research/code/DJ-RN-dawnlight/pointnet`

![Screenshot from 2021-06-08 02-13-21](https://user-images.githubusercontent.com/76495162/121132783-8fea0a80-c7ff-11eb-83c6-980227676076.png)
![Screenshot from 2021-06-08 02-13-26](https://user-images.githubusercontent.com/76495162/121132785-8fea0a80-c7ff-11eb-81ff-672f69a94151.png)

Here's a copy of your code:

```
import argparse
import math
import h5py
import numpy as np
#import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import socket
import importlib
import os
import sys
#import cPickle as pickle
import pickle
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.append(BASE_DIR)
sys.path.append(os.path.join(BASE_DIR, 'models'))
sys.path.append(os.path.join(BASE_DIR, 'utils'))
import tf_util

parser = argparse.ArgumentParser()
parser.add_argument('--gpu', type=int, default=0, help='GPU to use [default: GPU 0]')
parser.add_argument('--model', default='pointnet_hico', help='Model name: pointnet_cls or pointnet_cls_basic [default: pointnet_cls]')
parser.add_argument('--num_point', type=int, default=1228, help='Point Number [256/512/1024/2048] [default: 1024]')
parser.add_argument('--model_path', default='log/model.ckpt', help='model checkpoint file path [default: log/model.ckpt]')
parser.add_argument('--input_list', default='./', help='Path list of your point cloud files [default: ./pc_list.txt]')
FLAGS = parser.parse_args()


NUM_POINT = FLAGS.num_point
#GPU_INDEX = FLAGS.gpu
GPU_INDEX = 1
print("GPU_INDEX: ", GPU_INDEX)
MODEL_PATH = FLAGS.model_path
BATCH_SIZE = 1
MODEL = importlib.import_module(FLAGS.model) # import network module
MODEL_FILE = os.path.join(BASE_DIR, 'models', FLAGS.model+'.py')

MAX_NUM_POINT = 1228
NUM_CLASSES = 600

HOSTNAME = socket.gethostname()
print('HOSTNAME: ', HOSTNAME)

def evaluate():
    #with tf.device('/gpu:'+str(GPU_INDEX)):
    with tf.device('/device:gpu:1'):
        pointclouds_pl = MODEL.placeholder_inputs(BATCH_SIZE, NUM_POINT)
        is_training_pl = tf.placeholder(tf.bool, shape=())


        # simple model
        feat = MODEL.get_model(pointclouds_pl, is_training_pl)
        
        # Add ops to save and restore all the variables.
        saver = tf.train.Saver()
        
    # Create a session
    config = tf.ConfigProto()
    config.gpu_options.allow_growth = True
    config.allow_soft_placement = True
    config.log_device_placement = True
    sess = tf.Session(config=config)

    # Restore variables from disk.
    saver.restore(sess, MODEL_PATH)

    ops = {'pointclouds_pl': pointclouds_pl,
           'is_training_pl': is_training_pl,
           'feat': feat}

    eval_one_epoch(sess, ops)

   
def eval_one_epoch(sess, ops):
    is_training = False
    input_list = None
    with open(FLAGS.input_list, 'r') as f:
        input_list = f.readlines()
    
    for fn in range(len(input_list)):
        current_data = pickle.load(open(fn, 'rb'))
        current_data = current_data[None, :NUM_POINT, :]
        
            
        feed_dict = {ops['pointclouds_pl']: current_data,
                     ops['is_training_pl']: is_training}
        feat = sess.run([ops['feat']], feed_dict=feed_dict)
        print('filename: ', fn)
        pickle.dump(feat, open(fn[:-4] + '_feature.pkl', 'wb'))

with tf.Graph().as_default():
    evaluate()
```

here's `nvtop` output:
![Screenshot from 2021-06-08 02-24-06](https://user-images.githubusercontent.com/76495162/121133688-a6449600-c800-11eb-9893-b2763ebbbaca.png)

https://github.com/DirtyHarryLYL/DJ-RN/issues/64

**Comment by tilakrayal** [comment]
@monacv ,

Could you please run the below code snippet and share the results.

import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Also, take a look at the TensorFlow profiling tool [link #1](https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras), [link #2](https://www.tensorflow.org/guide/profiler#gpu_kernel_stats) ,[Link](https://github.com/tensorflow/tensorflow/issues/47001#issuecomment-780457956) and let us know if it helps. Thanks!

**Comment by monacv** [comment]
@tilakrayal 

Thanks for your response.

Here's the result that you requested:

```
(djrn) [jalal@goku ~]$ python
Python 3.8.5 (default, Mar 31 2021, 02:37:07) 
[GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))
2021-06-09 02:09:07.837418: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2021-06-09 02:09:07.893068: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:05:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.6705GHz coreCount: 28 deviceMemorySize: 10.92GiB deviceMemoryBandwidth: 451.17GiB/s
2021-06-09 02:09:07.894680: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 1 with properties: 
pciBusID: 0000:06:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.6705GHz coreCount: 28 deviceMemorySize: 10.92GiB deviceMemoryBandwidth: 451.17GiB/s
2021-06-09 02:09:07.895123: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2021-06-09 02:09:07.898138: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2021-06-09 02:09:07.901479: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2021-06-09 02:09:07.902020: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2021-06-09 02:09:07.905551: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2021-06-09 02:09:07.907255: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2021-06-09 02:09:07.913275: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2021-06-09 02:09:07.918778: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0, 1
Num GPUs Available:  2
```

**Comment by monacv** [comment]
@tilakrayal could you please have a look at here (it kind of gets stuck here):

https://pastebin.com/raw/ke8FK3pT

example lines (cannot copy whole thing here):
```
(djrn) [jalal@goku ~]$ cd /scratch3/research/code/DJ-RN-dawnlight/pointnet/
(djrn) [jalal@goku pointnet]$ python Feature_extraction.py --input_list ../vertex_path_GT.txt --model pointnet_hico --model_path ../Feature_extraction/model_10000.ckpt
WARNING:tensorflow:From /scratch3/venv/djrn/lib/python3.8/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
GPU_INDEX:  1
HOSTNAME:  goku.bu.edu
WARNING:tensorflow:Variable += will be deprecated. Use variable.assign_add if you want assignment to the variable value or 'x = x + y' if you want a new python Tensor object.
WARNING:tensorflow:Variable += will be deprecated. Use variable.assign_add if you want assignment to the variable value or 'x = x + y' if you want a new python Tensor object.
2021-06-09 02:11:40.272649: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-06-09 02:11:40.278565: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 3597875000 Hz
2021-06-09 02:11:40.279186: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4639580 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-06-09 02:11:40.279212: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-06-09 02:11:40.281451: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2021-06-09 02:11:40.992891: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x469faa0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-06-09 02:11:40.992980: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 1080 Ti, Compute Capability 6.1
2021-06-09 02:11:40.993014: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (1): GeForce GTX 1080 Ti, Compute Capability 6.1
2021-06-09 02:11:41.002244: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:05:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.6705GHz coreCount: 28 deviceMemorySize: 10.92GiB deviceMemoryBandwidth: 451.17GiB/s
2021-06-09 02:11:41.003897: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 1 with properties: 
pciBusID: 0000:06:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.6705GHz coreCount: 28 deviceMemorySize: 10.92GiB deviceMemoryBandwidth: 451.17GiB/s
2021-06-09 02:11:41.004425: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2021-06-09 02:11:41.009093: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2021-06-09 02:11:41.012839: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2021-06-09 02:11:41.013441: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2021-06-09 02:11:41.017564: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2021-06-09 02:11:41.019963: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2021-06-09 02:11:41.027162: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2021-06-09 02:11:41.034845: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0, 1
2021-06-09 02:11:41.034924: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2021-06-09 02:11:41.039735: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-06-09 02:11:41.039784: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 1 
2021-06-09 02:11:41.039810: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N Y 
2021-06-09 02:11:41.039834: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 1:   Y N 
2021-06-09 02:11:41.043792: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10360 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:05:00.0, compute capability: 6.1)
2021-06-09 02:11:41.045616: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 10376 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:06:00.0, compute capability: 6.1)
Device mapping:
/job:localhost/replica:0/task:0/device:XLA_CPU:0 -> device: XLA_CPU device
/job:localhost/replica:0/task:0/device:XLA_GPU:0 -> device: XLA_GPU device
/job:localhost/replica:0/task:0/device:XLA_GPU:1 -> device: XLA_GPU device
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:05:00.0, compute capability: 6.1
/job:localhost/replica:0/task:0/device:GPU:1 -> device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:06:00.0, compute capability: 6.1
2021-06-09 02:11:41.046866: I tensorflow/core/common_runtime/direct_session.cc:359] Device mapping:
/job:localhost/replica:0/task:0/device:XLA_CPU:0 -> device: XLA_CPU device
/job:localhost/replica:0/task:0/device:XLA_GPU:0 -> device: XLA_GPU device
/job:localhost/replica:0/task:0/device:XLA_GPU:1 -> device: XLA_GPU device
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:05:00.0, compute capability: 6.1
/job:localhost/replica:0/task:0/device:GPU:1 -> device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:06:00.0, compute capability: 6.1

transform_net1/ExpandDims: (ExpandDims): /job:localhost/replica:0/task:0/device:GPU:1
2021-06-09 02:11:41.086675: I tensorflow/core/common_runtime/placer.cc:114] transform_net1/ExpandDims: (ExpandDims): /job:localhost/replica:0/task:0/device:GPU:1
transform_net1/tconv1/weights/Initializer/random_uniform/RandomUniform: (RandomUniform): /job:localhost/replica:0/task:0/device:CPU:0
2021-06-09 02:11:41.086731: I tensorflow/core/common_runtime/placer.cc:114] transform_net1/tconv1/weights/Initializer/random_uniform/RandomUniform: (RandomUniform): /job:localhost/replica:0/task:0/device:CPU:0
transform_net1/tconv1/weights/Initializer/random_uniform/sub: (Sub): /job:localhost/replica:0/task:0/device:CPU:0
2021-06-09 02:11:41.086758: I tensorflow/core/common_runtime/placer.cc:114] transform_net1/tconv1/weights/Initializer/random_uniform/sub: (Sub): /job:localhost/replica:0/task:0/device:CPU:0
transform_net1/tconv1/weights/Initializer/random_uniform/mul: (Mul): /job:localhost/replica:0/task:0/device:CPU:0
2021-06-09 02:11:41.086793: I tensorflow/core/common_runtime/placer.cc:114] transform_net1/tconv1/weights/Initializer/random_uniform/mul: (Mul): /job:localhost/replica:0/task:0/device:CPU:0
transform_net1/tconv1/weights/Initializer/random_uniform: (Add): /job:localhost/replica:0/task:0/device:CPU:0
2021-06-09 02:11:41.086822: I tensorflow/core/common_runtime/placer.cc:114] transform_net1/tconv1/weights/Initializer/random_uniform: (Add): /job:localhost/replica:0/task:0/device:CPU:0
transform_net1/tconv1/weights: (VariableV2): /job:localhost/replica:0/task:0/device:CPU:0
2021-06-09 02:11:41.086856: I tensorflow/core/common_runtime/placer.cc:114] transform_net1/tconv1/weights: (VariableV2): /job:localhost/replica:0/task:0/device:CPU:0
transform_net1/tconv1/weights/Assign: (Assign): /job:localhost/replica:0/task:0/device:CPU:0
2021-06-09 02:11:41.086878: I tensorflow/core/common_runtime/placer.cc:114] transform_net1/tconv1/weights/Assign: (Assign): /job:localhost/replica:0/task:0/device:CPU:0
transform_net1/tconv1/weights/read: (Identity): /job:localhost/replica:0/task:0/device:CPU:0
2021-06-09 02:11:41.086904: I tensorflow/core/common_runtime/placer.cc:114] transform_net1/tconv1/weights/read: (Identity): /job:localhost/replica:0/task:0/device:CPU:0
transform_net1/tconv1/L2Loss: (L2Loss): /job:localhost/replica:0/task:0/device:GPU:1
2021-06-09 02:11:41.086933: I tensorflow/core/common_runtime/placer.cc:114] transform_net1/tconv1/L2Loss: (L2Loss): /job:localhost/replica:0/task:0/device:GPU:1
transform_net1/tconv1/weight_loss: (Mul): /job:localhost/replica:0/task:0/device:GPU:1
2021-06-09 02:11:41.086957: I tensorflow/core/common_runtime/placer.cc:114] transform_net1/tconv1/weight_loss: (Mul): /job:localhost/replica:0/task:0/device:GPU:1
transform_net1/tconv1/Conv2D: (Conv2D): /job:localhost/replica:0/task:0/device:GPU:1
2021-06-09 02:11:41.086980: I tensorflow/core/common_runtime/placer.cc:114] transform_net1/tconv1/Conv2D: (Conv2D): /job:localhost/replica:0/task:0/device:GPU:1
transform_net1/tconv1/biases: (VariableV2): /job:localhost/replica:0/task:0/device:CPU:0
2021-06-09 02:11:41.087004: I tensorflow/core/common_runtime/placer.cc:114] transform_net1/tconv1/biases: (VariableV2): /job:localhost/replica:0/task:0/device:CPU:0
transform_net1/tconv1/biases/Assign: (Assign): /job:localhost/replica:0/task:0/device:CPU:0
2021-06-09 02:11:41.087032: I tensorflow/core/common_runtime/placer.cc:114] transform_net1/tconv1/biases/Assign: (Assign): /job:localhost/replica:0/task:0/device:CPU:0
transform_net1/tconv1/biases/read: (Identity): /job:localhost/replica:0/task:0/device:CPU:0
2021-06-09 02:11:41.087056: I tensorflow/core/common_runtime/placer.cc:114] transform_net1/tconv1/biases/read: (Identity): /job:localhost/replica:0/task:0/device:CPU:0
transform_net1/tconv1/BiasAdd: (BiasAdd): /job:localhost/replica:0/task:0/device:GPU:1
2021-06-09 02:11:41.087080: I tensorflow/core/common_runtime/placer.cc:114] transform_net1/tconv1/BiasAdd: (BiasAdd): /job:localhost/replica:0/task:0/device:GPU:1
transform_net1/tconv1/bn/beta: (VariableV2): /job:localhost/replica:0/task:0/device:GPU:1
2021-06-09 02:11:41.087109: I tensorflow/core/common_runtime/placer.cc:114] transform_net1/tconv1/bn/beta: (VariableV2): /job:localhost/replica:0/task:0/device:GPU:1
transform_net1/tconv1/bn/beta/Assign: (Assign): /job:localhost/replica:0/task:0/device:GPU:1
2021-06-09 02:11:41.087135: I tensorflow/core/common_runtime/placer.cc:114] transform_net1/tconv1/bn/beta/Assign: (Assign): /job:localhost/replica:0/task:0/device:GPU:1
transform_net1/tconv1/bn/beta/read: (Identity): /job:localhost/replica:0/task:0/device:GPU:1
2021-06-09 02:11:41.087158: I tensorflow/core/common_runtime/placer.cc:114] transform_net1/tconv1/bn/beta/read: (Identity): /job:localhost/replica:0/task:0/device:GPU:1
transform_net1/tconv1/bn/gamma: (VariableV2): /job:localhost/replica:0/task:0/device:GPU:1
2021-06-09 02:11:41.087184: I tensorflow/core/common_runtime/placer.cc:114] transform_net1/tconv1/bn/gamma: (VariableV2): /job:localhost/replica:0/task:0/device:GPU:1
transform_net1/tconv1/bn/gamma/Assign: (Assign): /job:localhost/replica:0/task:0/device:GPU:1
2021-06-09 02:11:41.087210: I tensorflow/core/common_runtime/placer.cc:114] transform_net1/tconv1/bn/gamma/Assign: (Assign): /job:localhost/replica:0/task:0/device:GPU:1
transform_net1/tconv1/bn/gamma/read: (Identity): /job:localhost/replica:0/task:0/device:GPU:1
2021-06-09 02:11:41.087234: I tensorflow/core/common_runtime/placer.cc:114] transform_net1/tconv1/bn/gamma/read: (Identity): /job:localhost/replica:0/task:0/device:GPU:1
transform_net1/tconv1/bn/moments/mean: (Mean): /job:localhost/replica:0/task:0/device:GPU:1
2021-06-09 02:11:41.087257: I tensorflow/core/common_runtime/placer.cc:114] transform_net1/tconv1/bn/moments/mean: (Mean): /job:localhost/replica:0/task:0/device:GPU:1
transform_net1/tconv1/bn/moments/StopGradient: (StopGradient): /job:localhost/replica:0/task:0/device:GPU:1
2021-06-09 02:11:41.087281: I tensorflow/core/common_runtime/placer.cc:114] transform_net1/tconv1/bn/moments/StopGradient: (StopGradient): /job:localhost/replica:0/task:0/device:GPU:1
```

As for profiler, unfortunately I never used the Tensorflow profiler and I am not even sure how to incorporate it to this code (which isn't mine) :(

**Comment by monacv** [comment]
Another thing that is pretty much confusing me is that if we are setting TF to use GPU 1, why is it also using GPU 0 as shown below that PID 11680 is using both GPU 0 and GPU 1? Yet, both have a near-zero GPU utilization.
![Screenshot from 2021-06-09 02-18-07](https://user-images.githubusercontent.com/76495162/121303462-1b7b9e00-c8c9-11eb-8520-74f0ff77ba5f.png)

**Comment by monacv** [comment]
also, when I CTL+ c that, I see the below. Does it get stuck in some sort of IO?
```

t/replica:0/task:0/device:CPU:0
^T^C^XTraceback (most recent call last):
  File "Feature_extraction.py", line 92, in <module>
    evaluate()
  File "Feature_extraction.py", line 71, in evaluate
    eval_one_epoch(sess, ops)
  File "Feature_extraction.py", line 81, in eval_one_epoch
    current_data = pickle.load(open(fn, 'rb'))
KeyboardInterrupt
```

**Comment by monacv** [comment]
There was an error in the original code by the authors. They should have written
`
    for fn in input_list:`

instead of

`    for fn in range(len(input_list)):`
