### ISSUE TITLE
tensorflow load saved_model throw error: google.protobuf.message.DecodeError: Error parsing message

### ISSUE THREAD

**Issue by lnshi** [tensorflow/tensorflow#50167]
Background: i set up a new MBP with MacOS Big Sur 11.4 then my TensorFlow model loading script is not working anymore (which works previously and still works on my another laptop), i tried to set up exactly same python virtual environment, and even use exactly same Dockerfile, still one is working and the other is not working...

So apparently this is OS setup issue, i just cannot figure out what is wrong, and already hit the wall for days....

**Pls help to point out what potential stuffs i can check to fix this...**

(and if possible pls don't close, as i already asked this question in StackOverflow yesterday: https://stackoverflow.com/q/67886470/7658313 and till now no answer yet)

And the other confusion is: how come within the docker container also one laptop is working and another is not working, so it must be some physical host OS stuff can even affect the docker container...

The error trace stack:
```
Traceback (most recent call last):
  File "/venvs/tf1_15/lib/python3.6/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 68, in parse_saved_model
    saved_model.ParseFromString(file_content)
google.protobuf.message.DecodeError: Error parsing message

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "naive_tf1_model_loader.py", line 55, in <module>
    "/tf1_models/object_detection/1"
  File "naive_tf1_model_loader.py", line 14, in __init__
    self._sess, [tf.saved_model.SERVING], model_path
  File "/venvs/tf1_15/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/venvs/tf1_15/lib/python3.6/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 268, in load
    loader = SavedModelLoader(export_dir)
  File "/venvs/tf1_15/lib/python3.6/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 284, in __init__
    self._saved_model = parse_saved_model(export_dir)
  File "/venvs/tf1_15/lib/python3.6/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 71, in parse_saved_model
    raise IOError("Cannot parse file %s: %s." % (path_to_pb, str(e)))
OSError: Cannot parse file b'/path/saved_model.pb': Error parsing message.
```

The model is downloaded from [tensorflow model zoo: this one][1].

-----

FYI: the model loading script:
```
import time
import tensorflow as tf

_INPUT_KEYS_TO_TENSOR       = "input_keys_to_tensor"
_OUTPUT_KEYS_KEYS_TO_TENSOR = "output_keys_to_tensor"

class TF1Model:

  def __init__(self, model_path):
    self._sess = tf.compat.v1.Session()

    if hasattr(tf.compat.v1.saved_model, "load"):
      graph_meta_def = tf.compat.v1.saved_model.load(
        self._sess, [tf.saved_model.SERVING], model_path
      )
    else:
      graph_meta_def = tf.compat.v1.saved_model.loader.load(
        self._sess, [tf.saved_model.SERVING], model_path
      )

    signature = graph_meta_def.signature_def

    self._signature_tensor_mapping = {}
    for signature_name in signature.keys():
      indiv_sig_data = self._signature_tensor_mapping[signature_name] = {
        _INPUT_KEYS_TO_TENSOR: {},
        _OUTPUT_KEYS_KEYS_TO_TENSOR: {}
      }

      inputs = signature[signature_name].inputs
      for k in inputs.keys():
        tensor = self._sess.graph.get_tensor_by_name(inputs[k].name)
        indiv_sig_data[_INPUT_KEYS_TO_TENSOR][k] = tensor

      outputs = signature[signature_name].outputs
      for k in outputs.keys():
        tensor = self._sess.graph.get_tensor_by_name(outputs[k].name)
        indiv_sig_data[_OUTPUT_KEYS_KEYS_TO_TENSOR][k] = tensor

  def predict(self, payload):
    start = time.time()
    payload_sig = payload["signature_name"]
    res = self._sess.run(
      self._signature_tensor_mapping[payload_sig][_OUTPUT_KEYS_KEYS_TO_TENSOR],
      {
        self._signature_tensor_mapping[payload_sig][_INPUT_KEYS_TO_TENSOR]["inputs"]: payload["inputs"]["inputs"]
      }
    )
    print("prediction took: {}s".format(time.time() - start))
    return res

if __name__ == "__main__":

  model = TF1Model("/tf1_models/object_detection/1")

  payload = {
    "signature_name":"serving_default",
    "inputs":{
      "inputs":[
        [[[0, 0, 0], [0, 0, 0]]]
      ]
    }
  }

  for _ in range(3):
    model.predict(payload)
```

  [1]: http://download.tensorflow.org/models/object_detection/ssd_resnet50_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03.tar.gz

**Comment by lnshi** [comment]
sorry, false alarm closing...
