### ISSUE TITLE
tensorflow / tfjs-examples have a bug

### ISSUE THREAD

**Issue by starzhouchina** [tensorflow/tensorflow#50221]
1.  tfjs-examples  have a bug:
D:\proj_tensorflow\tfjs-examples-master\mobilenet>yarn watch
yarn run v1.22.10
$ cross-env NODE_ENV=development parcel index.html --no-hmr --open
Server running at http://localhost:1234
×  D:\proj_tensorflow\tfjs-examples-master\mobilenet\cat.jpg: function (prevType) {
  this.state.exprAllowed = false;

  if (prevType === types._let || prevType === types._c...<omitted>...
} could not be cloned.
  this.state.exprAllowed = false;

  if (prevType === types._let || prevType === types._c...<omitted>...
} could not be cloned.
    at Object.serialize (v8.js:256:7)
    at _default (D:\proj_tensorflow\tfjs-examples-master\mobilenet\node_modules\@babel\core\lib\transformation\util\clone-deep.js:16:30)
    at normalizeFile (D:\proj_tensorflow\tfjs-examples-master\mobilenet\node_modules\@babel\core\lib\transformation\normalize-file.js:52:36)
    at normalizeFile.next (<anonymous>)
    at run (D:\proj_tensorflow\tfjs-examples-master\mobilenet\node_modules\@babel\core\lib\transformation\index.js:31:50)
    at run.next (<anonymous>)
    at Function.<anonymous> (D:\proj_tensorflow\tfjs-examples-master\mobilenet\node_modules\@babel\core\lib\transform-ast.js:20:41)
    at Generator.next (<anonymous>)
    at evaluateSync (D:\proj_tensorflow\tfjs-examples-master\mobilenet\node_modules\gensync\index.js:251:28)
    at Function.sync (D:\proj_tensorflow\tfjs-examples-master\mobilenet\node_modules\gensync\index.js:89:14)

how to fix it?

**Comment by starzhouchina** [comment]
×  D:\proj_tensorflow\tfjs-examples-master\mobilenet\cat.jpg: function (prevType) {
  this.state.exprAllowed = false;

  if (prevType === types._let || prevType === types._c...<omitted>...
} could not be cloned.

the error is above

**Comment by starzhouchina** [comment]
run on  windows x64 and  ubuntu , have same errors as above. tensorflow @ 2.3, or 2.4
