### ISSUE TITLE
ValueError: numpy.ndarray size changed with numpy 1.19.5

### ISSUE THREAD

**Issue by Mabedin00** [tensorflow/tensorflow#50233]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- Windows 10 
- TensorFlow installed from package: python-tensorflow
- TensorFlow version: 2.5.0
- Python version: 3.7
- Numpy: 1.19.5
- Installed using virtualenv? pip? conda?: Conda

When I try to train my model I get the error 
`ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject`
The solutions I found online all tell me to upgrade numpy to 1.20; however, as far as I am aware that has compatibility issues with Tensorflow. 
I run the command 
`python model_main_tf2.py --pipeline_config_path=training/ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8.config --model_dir=training --alsologtostderr`

**Logs*

> 2021-06-11 19:10:57.108835: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-06-11 19:10:57.110211: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "model_main_tf2.py", line 32, in <module>
    from object_detection import model_lib_v2
  File "C:\Users\Mohidul Efaz\anaconda3\envs\trash\lib\site-packages\object_detection\model_lib_v2.py", line 29, in <module>
    from object_detection import eval_util
  File "C:\Users\Mohidul Efaz\anaconda3\envs\trash\lib\site-packages\object_detection\eval_util.py", line 35, in <module>
    from object_detection.metrics import coco_evaluation
  File "C:\Users\Mohidul Efaz\anaconda3\envs\trash\lib\site-packages\object_detection\metrics\coco_evaluation.py", line 25, in <module>
    from object_detection.metrics import coco_tools
  File "C:\Users\Mohidul Efaz\anaconda3\envs\trash\lib\site-packages\object_detection\metrics\coco_tools.py", line 51, in <module>
    from pycocotools import coco
  File "C:\Users\Mohidul Efaz\anaconda3\envs\trash\lib\site-packages\pycocotools\coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "C:\Users\Mohidul Efaz\anaconda3\envs\trash\lib\site-packages\pycocotools\mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "pycocotools\_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

**Comment by Saduf2019** [comment]
@Mabedin00 
please confirm if you followed as per this [link](https://stackoverflow.com/questions/66060487/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility-exp) and restarted your system. [pip install pycocotools==2.0.0]

For the error logs shared please follow:[link](https://github.com/tensorflow/tensorflow/issues/48868#issuecomment-841396124)

**Comment by Zethson** [comment]
Is Tensorflow 2.6.0 compatible with numpy 1.20?

**Comment by Saduf2019** [comment]
@Zethson 
Please follow [this pr](https://github.com/tensorflow/tensorflow/pull/48935) for numpy 1.20 compatibility
