### ISSUE TITLE
Android studio:Error occurred when detecting the image

### ISSUE THREAD

**Issue by raulpopa98** [tensorflow/tensorflow#50248]
I had trained my custom model with different objects for the detection purpose. I had used ssd_mobilenet_v1_coco for my training. I could pull out the object detection on desktop with the customised trained model by using the webcam or passing an image. After converted my tf model to tflite model, adding metadata and quantized my model I obtained the following error when I run my application in Android Studio:

E/AndroidRuntime: FATAL EXCEPTION: inference
    Process: org.tensorflow.lite.examples.detection, PID: 28456
    java.lang.AssertionError: Error occurred when detecting the image: Label map does not contain enough elements: model returned class index 79 but label map only contains 2 elements.
        at org.tensorflow.lite.task.vision.detector.ObjectDetector.detectNative(Native Method)
        at org.tensorflow.lite.task.vision.detector.ObjectDetector.detect(ObjectDetector.java:421)
        at org.tensorflow.lite.task.vision.detector.ObjectDetector.detect(ObjectDetector.java:401)
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.recognizeImage(TFLiteObjectDetectionAPIModel.java:94)
        at org.tensorflow.lite.examples.detection.DetectorActivity$2.run(DetectorActivity.java:181)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)
I/Process: Sending signal. PID: 28456 SIG: 9

My application detect the objects, but after approximately 1 minute, the application stop every time I run the program .
Has anyone encountered this error before ?

**Comment by tilakrayal** [comment]
@raulpopa98 ,

In order to expedite the trouble-shooting process, could you please provide the tensorflow version,complete code and dataset to reproduce the issue reported here.

Thanks!
