### ISSUE TITLE
Cannot save custom model

### ISSUE THREAD

**Issue by markub3327** [tensorflow/tensorflow#50247]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on a mobile device: -
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5.0
- Python version: 3.8.5
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): 9.3.0
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the current behaviour**
```bash
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/rl-toolkit/rl_toolkit/__main__.py", line 155, in <module>
    agent.save()
  File "/root/rl-toolkit/rl_toolkit/policy/learner.py", line 215, in save
    self.model.save(os.path.join(self._save_path, "model"))
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/training.py", line 2111, in save
    save.save_model(self, filepath, overwrite, include_optimizer, save_format,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/saving/save.py", line 150, in save_model
    saved_model_save.save(model, filepath, overwrite, include_optimizer,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/saving/saved_model/save.py", line 89, in save
    saved_nodes, node_paths = save_lib.save_and_return_nodes(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py", line 1103, in save_and_return_nodes
    _build_meta_graph(obj, signatures, options, meta_graph_def,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py", line 1290, in _build_meta_graph
    return _build_meta_graph_impl(obj, signatures, options, meta_graph_def,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py", line 1207, in _build_meta_graph_impl
    signatures = signature_serialization.find_function_to_export(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/signature_serialization.py", line 99, in find_function_to_export
    functions = saveable_view.list_functions(saveable_view.root)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py", line 154, in list_functions
    obj_functions = obj._list_functions_for_serialization(  # pylint: disable=protected-access
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/training.py", line 2713, in _list_functions_for_serialization
    functions = super(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 3016, in _list_functions_for_serialization
    return (self._trackable_saved_model_saver
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/saving/saved_model/base_serialization.py", line 92, in list_functions_for_serialization
    fns = self.functions_to_serialize(serialization_cache)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 73, in functions_to_serialize
    return (self._get_serialized_attributes(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 89, in _get_serialized_attributes
    object_dict, function_dict = self._get_serialized_attributes_internal(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/saving/saved_model/model_serialization.py", line 48, in _get_serialized_attributes_internal
    default_signature = save_impl.default_save_signature(self.obj)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 215, in default_save_signature
    fn = saving_utils.trace_model_call(layer)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/saving/saving_utils.py", line 119, in trace_model_call
    raise_model_input_error(model)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/saving/saving_utils.py", line 90, in raise_model_input_error
    raise ValueError(
ValueError: Model <rl_toolkit.networks.actor_critic.ActorCritic object at 0x7f6d059b2ee0> cannot be saved because the input shapes have not been set. Usually, input shapes are automatically determined from calling `.fit()` or `.predict()`. To manually set the shapes, call `model.build(input_shape)`.
```

But before I'm saving the model, I ran:
```python
# Actor network (for learner)
self.model = ActorCritic(
    num_of_outputs=tf.reduce_prod(self._env.action_space.shape),
    gamma=gamma,
    tau=tau,
)
self.model.build((None,) + self._env.observation_space.shape)
self.model.compile(
    actor_optimizer=Adam(learning_rate=actor_learning_rate),
    critic_optimizer=Adam(learning_rate=critic_learning_rate),
    alpha_optimizer=Adam(learning_rate=alpha_learning_rate),
)

self.model.summary()
```

The result of `summary()`:
```bash
Model: "actor_critic"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
actor (Actor)                multiple                  139108
_________________________________________________________________
multi_critic (MultiCritic)   multiple                  270802
_________________________________________________________________
multi_critic_1 (MultiCritic) multiple                  270802
=================================================================
Total params: 680,714
Trainable params: 678,313
Non-trainable params: 2,401
_________________________________________________________________
```

Definition of custom model:
```python
class ActorCritic(Model):
    def __init__(self, num_of_outputs: int, gamma: float, tau: float, **kwargs):
        super(ActorCritic, self).__init__(**kwargs)

        self.gamma = tf.constant(gamma)
        self.tau = tf.constant(tau)

        # init param 'alpha' - Lagrangian constraint
        self.log_alpha = tf.Variable(0.0, trainable=True, name="log_alpha")
        self.alpha = tf.Variable(0.0, trainable=False, name="alpha")
        self.target_entropy = tf.cast(-num_of_outputs, dtype=tf.float32)

        # Actor
        self.actor = Actor(num_of_outputs)

        # Critic
        self.critic = MultiCritic(2)
        self.critic_target = MultiCritic(2)
        self._train_target(self.critic, self.critic_target, tau=tf.constant(1.0))

    def train_step(self, data):
        with tf.GradientTape(persistent=True) as tape:

        # ....

        return {
            "actor_loss": actor_loss,
            "critic_loss": Q_loss,
            "alpha_loss": alpha_loss,
        }

    def _train_target(self, source, target, tau):
        for source_weight, target_weight in zip(
            source.trainable_variables, target.trainable_variables
        ):
            target_weight.assign(tau * source_weight + (1.0 - tau) * target_weight)

    def call(self, inputs):
        action, log_pi = self.actor(inputs, with_log_prob=True)
        Q_value = tf.reduce_min(self.critic([inputs, action]), axis=1)
        Q_value_target = tf.reduce_min(self.critic_target([inputs, action]), axis=1)
        return [Q_value, Q_value_target, action, log_pi]

    def compile(self, actor_optimizer, critic_optimizer, alpha_optimizer):
        super(ActorCritic, self).compile()
        self.actor_optimizer = actor_optimizer
        self.critic_optimizer = critic_optimizer
        self.alpha_optimizer = alpha_optimizer
```

How can I use `self.model.save()` correctly on a custom model?
Thanks.

**Comment by jvishnuvardhan** [comment]
@markub3327 Custom models are little different. Before saving the model, You need to call them on some input as shown in [this section](https://www.tensorflow.org/guide/keras/save_and_serialize#how_savedmodel_handles_custom_objects) of the `save and load` tutorial. Thanks!

Share a simple standalone to reproduce the issue if the above tutorial didn't help you. Thanks!

**Comment by markub3327** [comment]
Yeah, I call only layers individually, but the model's `call()` method never use. The model's call() method is unnecessary for me ... Also, can I call it on `tf.zeros` before saving (the content of the model's call method is only for illustration in order to init all layer contained in the model with input_shape)? Why not enough use only `.build(input_shape)` before saving? I think that the `.build(input_shape)` method use `call()` automatically when is used. Thanks.

**Comment by jvishnuvardhan** [comment]
@markub3327 Yes, you can call the model with your input (any input, just to set the random weights) or run `model.build()` method. Can you try that and share a standalone code to reproduce any issues. Thanks!

**Comment by markub3327** [comment]
[Here is the reproducible code](https://colab.research.google.com/gist/markub3327/6fd3075359b21e8708dcbcd356874c83/untitled2.ipynb)

What means `ValueError: Model <__main__.ActorCritic object at 0x7f7a1544b550> cannot be saved because the input shapes have not been set. Usually, input shapes are automatically determined from calling `.fit()` or `.predict()`. To manually set the shapes, call `model.build(input_shape)`.`, when I call `model.build(input_shape)` before saving (please look at snippet). I thought that this error talks about using `model.build(input_shape)`. Thanks!

**Comment by markub3327** [comment]
Now, when I use `call()` in `train_step()` during saving I get a new error:
```
WARNING:absl:Found untraced functions such as fc1_layer_call_and_return_conditional_losses, fc1_layer_call_fn, activation_layer_call_and_return_conditional_losses, activation_layer_call_fn, layer_normalization_layer_call_and_return_conditional_losses while saving (showing 5 of 140). These functions will not be directly callable after loading.
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/rl-toolkit/rl_toolkit/__main__.py", line 168, in <module>
    agent.save()
  File "/root/rl-toolkit/rl_toolkit/policy/learner.py", line 229, in save
    self.model.save(os.path.join(self._save_path, "model"))
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/training.py", line 2111, in save
    save.save_model(self, filepath, overwrite, include_optimizer, save_format,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/saving/save.py", line 150, in save_model
    saved_model_save.save(model, filepath, overwrite, include_optimizer,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/saving/saved_model/save.py", line 89, in save
    saved_nodes, node_paths = save_lib.save_and_return_nodes(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py", line 1103, in save_and_return_nodes
    _build_meta_graph(obj, signatures, options, meta_graph_def,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py", line 1290, in _build_meta_graph
    return _build_meta_graph_impl(obj, signatures, options, meta_graph_def,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py", line 1234, in _build_meta_graph_impl
    object_graph_proto, saved_object_metadata = _serialize_object_graph(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py", line 787, in _serialize_object_graph
    has_saved_object_metadata = _write_object_proto(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py", line 832, in _write_object_proto
    metadata = obj._tracking_metadata
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 3009, in _tracking_metadata
    return self._trackable_saved_model_saver.tracking_metadata
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/saving/saved_model/base_serialization.py", line 53, in tracking_metadata
    return json_utils.Encoder().encode(self.python_properties)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/saving/saved_model/json_utils.py", line 46, in encode
    return super(Encoder, self).encode(_encode_tuple(obj))
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/saving/saved_model/json_utils.py", line 43, in default
    return get_json_type(obj)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/saving/saved_model/json_utils.py", line 143, in get_json_type
    raise TypeError('Not JSON Serializable:', obj)
TypeError: ('Not JSON Serializable:', <tf.Tensor: shape=(), dtype=int32, numpy=8>)
```
I don't know why this new error isn't reproducible on [Colab](https://colab.research.google.com/gist/markub3327/6fd3075359b21e8708dcbcd356874c83/untitled2.ipynb).

**Comment by markub3327** [comment]
```
ValueError: Could not find matching function to call loaded from the SavedModel. Got:
  Positional arguments (4 total):
    * Tensor("inputs:0", shape=(1, 24), dtype=float32)
    * False
    * None
    * None
  Keyword arguments: {}

Expected these arguments to match one of the following 2 option(s):

Option 1:
  Positional arguments (4 total):
    * TensorSpec(shape=(None, 24), dtype=tf.float32, name='inputs')
    * False
    * True
    * None
  Keyword arguments: {}

Option 2:
  Positional arguments (4 total):
    * TensorSpec(shape=(None, 24), dtype=tf.float32, name='inputs')
    * True
    * True
    * None
  Keyword arguments: {}
```
How can I use the saved model with other parameters, that weren't used during training? I have only 2 option to use `call()`, but I need the third option like `call(inputs, None, None, True)`

Reproducible code is [here](https://colab.research.google.com/gist/markub3327/6fd3075359b21e8708dcbcd356874c83/untitled2.ipynb).

Thanks.

**Comment by jvishnuvardhan** [comment]
@markub3327 I tried with the options you are looking (call(inputs, None, None, True)) and was able to run it without any issue. Only last `model.save` was throwing error as we need to call the model on some data or run `model.predict`. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/782843967723cb5309a830970726f153/untitled2.ipynb). Thanks!

**Comment by markub3327** [comment]
So sorry, I don't know what part of my model definition has been bad that I post it all, for the future, I will be shorter.

1. Yes, it's necessary to run call() before saving the model and **use only build() is not enough**!
2. With parameters that I need It's still not working: model.actor(tf.random.normal([1, 24]),training=False, with_log_prob=False, deterministic=True). You tested it on one of the possible configurations like here is described:
```
Expected these arguments to match one of the following 2 option(s):

Option 1:
  Positional arguments (4 total):
    * TensorSpec(shape=(None, 24), dtype=tf.float32, name='inputs')
    * False
    * True
    * None
  Keyword arguments: {}

Option 2:
  Positional arguments (4 total):
    * TensorSpec(shape=(None, 24), dtype=tf.float32, name='inputs')
    * True
    * True
    * None
  Keyword arguments: {}
```
3. How can I show the graph of this custom model, because I see the model like one node.
