### ISSUE TITLE
Trouble with mnist_rnn model

### ISSUE THREAD

**Issue by chinphing** [tensorflow/tensorflow#5027]
When running with script 'tensorflow/tensorflow/examples/skflow/mnist_rnn.py', I got the following error.

Traceback (most recent call last):
  File "mnist_rnn.py", line 68, in <module>
    classifier.fit(X_train, y_train, logdir="/tmp/mnist_rnn")
  File "/home/xing/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/base.py", line 257, in fit
    monitors=monitors)
  File "/home/xing/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 662, in _train_model
    train_op, loss_op = self._get_train_ops(features, targets)
  File "/home/xing/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 963, in _get_train_ops
    _, loss, train_op = self._call_model_fn(features, targets, ModeKeys.TRAIN)
  File "/home/xing/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 946, in _call_model_fn
    return self._model_fn(features, targets, mode=mode)
  File "/home/xing/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/base.py", line 493, in _model_fn
    predictions, loss = model_fn(features, targets)
  File "mnist_rnn.py", line 60, in rnn_model
    return learn.models.logistic_regression(encoding, y)
  File "/home/xing/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/models.py", line 148, in logistic_regression
    'weights', [x.get_shape()[1], y.get_shape()[-1]], dtype=dtype)
AttributeError: 'LSTMStateTuple' object has no attribute 'get_shape'

Is there something wrong with learn package? My tensor version is 0.11.0rc0, installed with pip.

**Comment by asimshankar** [comment]
There is something to be fixed, see also #4930 
Closing this as a duplicate, further discussion on #4930
