### ISSUE TITLE
mix precison bfloat16 lstm/conv1d support

### ISSUE THREAD

**Issue by BuaaAlban** [tensorflow/tensorflow#50282]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): v2.5.0-rc3-213-ga4dfb8d1a71 **2.5.0**

- Python version: 3.8.10
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: 11.2
- GPU model and memory: 32G, tesla V100

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
```
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import mixed_precision
 
policy = mixed_precision.Policy('bfloat16')  #'mixed_float16' 'mixed_bfloat16'等多种选择，后续的都会是该设置的类型
mixed_precision.set_global_policy(policy)
print('Compute dtype: %s' % policy.compute_dtype)
print('Variable dtype: %s' % policy.variable_dtype)
 

inputs = keras.Input(shape=(784,), name='digits')
if tf.config.list_physical_devices('GPU'):
  print('The model will run with 4096 units on a GPU')
  num_units = 4096
else:
  print('The model will run with 64 units on a CPU')
  num_units = 64
 
#dense test #测试cpu/GPU上可以跑
dense1 = layers.Dense(num_units, activation='relu', name='dense_1')
x = dense1(inputs)
dense2 = layers.Dense(num_units, activation='relu', name='dense_2')
x = dense2(x)
 
#lstm gpu test
inputs = tf.random.normal([32, 10, 8])
lstm = tf.keras.layers.LSTM(4)
output = lstm(inputs)
print(output.shape)
"""
>>> output = lstm(inputs)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py", line 668, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1023, in __call__
    self._maybe_build(inputs)
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2625, in _maybe_build
    self.build(input_shapes)  # pylint:disable=not-callable
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py", line 586, in build
    self.cell.build(step_input_shape)
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/keras/utils/tf_utils.py", line 270, in wrapper
    output_shape = fn(instance, input_shape)
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py", line 2361, in build
    self.recurrent_kernel = self.add_weight(
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 639, in add_weight
    variable = self._add_variable_with_custom_getter(
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py", line 810, in _add_variable_wi
th_custom_getter
    new_variable = getter(
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 127, in make_vari
able
    return tf_variables.VariableV1(
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/ops/variables.py", line 260, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/ops/variables.py", line 206, in _variable_v1_call
    return previous_getter(
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/ops/variables.py", line 199, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/ops/variable_scope.py", line 2612, in default_variable_cr
eator
    return resource_variable_ops.ResourceVariable(
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/ops/variables.py", line 264, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1584, in __init__
    self._init_from_args(
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1722, in _init_from_a
rgs
    initial_value = initial_value()
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/keras/initializers/initializers_v2.py", line 606, in __ca
ll__
    q, r = gen_linalg_ops.qr(a, full_matrices=False)
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/ops/gen_linalg_ops.py", line 2072, in qr
    _ops.raise_from_not_ok_status(e, name)
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 6897, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Value for attr 'T' of bfloat16 is not in the list of allowed values: double, float, half, comple
x64, complex128
        ; NodeDef: {{node Qr}}; Op<name=Qr; signature=input:T -> q:T, r:T; attr=full_matrices:bool,default=false; attr=T:type,allowed=[DT_DOUBLE, DT_FLOAT, DT
_HALF, DT_COMPLEX64, DT_COMPLEX128]> [Op:Qr]
```
"""
 
#conv1d gpu test
input_shape = (4, 10, 128)
x = tf.random.normal(input_shape)
y = tf.keras.layers.Conv1D(32, 3, activation='relu',input_shape=input_shape[1:])(x)
'''
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1030, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/keras/layers/convolutional.py", line 249, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/ops/nn_ops.py", line 1012, in convolution_v2
    return convolution_internal(
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/ops/nn_ops.py", line 1142, in convolution_internal
    return op(
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py", line 602, in new_func
    return func(*args, **kwargs)
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py", line 602, in new_func
    return func(*args, **kwargs)
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/ops/nn_ops.py", line 1907, in conv1d
    return array_ops.squeeze(result, [spatial_start_dim])
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py", line 535, in new_func
    return func(*args, **kwargs)
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 4471, in squeeze
    return gen_array_ops.squeeze(input, axis, name)
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/ops/gen_array_ops.py", line 10176, in squeeze
    _ops.raise_from_not_ok_status(e, name)
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 6897, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Tried to squeeze dim index -3 for tensor with 1 dimensions. [Op:Squeeze
'''
#conv2d gpu test
input_shape = (4, 28, 28, 3)
x = tf.random.normal(input_shape)
y = tf.keras.layers.Conv2D(2, 3, activation='relu', input_shape=input_shape[1:])(x)
'''
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1030, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/keras/layers/convolutional.py", line 267, in call
    outputs = nn.bias_add(
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/ops/nn_ops.py", line 3377, in bias_add
    return gen_nn_ops.bias_add(
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 678, in bias_add
    _ops.raise_from_not_ok_status(e, name)
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/tfasr/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 6897, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: cannot compute BiasAdd as input #1(zero-based) was expected to be a float tensor but is a bfloat16 tensor [Op:BiasAdd]
'''
**Describe the expected behavior**
lstm/conv1d run successfully as dense layers

**[Contributing](https://www.tensorflow.org/community/contribute)** - Do you
want to contribute a PR? (yes/no): - Briefly describe your candidate solution
(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by saikumarchalla** [comment]
@BuaaAlban Was able to reproduce the issue in TF 2.5. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/acab2c7110dbad7ca7f1acef921ff160/untitled.ipynb).Thanks!

**Comment by jvishnuvardhan** [comment]
Based on error message, it looks like only double, float, half, complex64, complex128 dtypes are implemented.

```
InvalidArgumentError: Value for attr 'T' of bfloat16 is not in the list of allowed values: double, float, half, complex64, complex128
	; NodeDef: {{node Qr}}; Op<name=Qr; signature=input:T -> q:T, r:T; attr=full_matrices:bool,default=false; attr=T:type,allowed=[DT_DOUBLE, DT_FLOAT, DT_HALF, DT_COMPLEX64, DT_COMPLEX128]> [Op:Qr]
```

Can you please open it as a feature in keras-team/keras repo as Keras development moved to that repo.

Keras development moved to another repository to focus on only keras. Could you please repost this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
