### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError:  No algorithm worked!

### ISSUE THREAD

**Issue by WoJiaYouTingShu** [tensorflow/tensorflow#50302]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
  no,the code from a example in [here](https://tensorflow.google.cn/tutorials/quickstart/advanced)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
   windows 10
- TensorFlow installed from (source or binary):
   Installed using PIP
- TensorFlow version (use command below):2.4.0
- Python version:3.8
- CUDA/cuDNN version:
   cuda:11.3
   cudnn:8.2.0
- GPU model and memory:NVIDIA GeForce RTX3060 Laptop GPU, 6g

**Describe the current behavior**
when i runing the code from example like this:
```
import tensorflow as tf
from tensorflow.keras import Model
from tensorflow.keras.layers import Conv2D, Flatten, Dense
import os

os.environ['TF_XLA_FLAGS'] = '--tf_xla_enable_xla_devices'

# 加载数据
mnist = tf.keras.datasets.mnist
# dataset = mnist.load_data()
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

# Add a channels dimension(60000, 28, 28)->(60000, 28, 28, 1)
x_train = x_train[..., tf.newaxis]
x_test = x_test[..., tf.newaxis]

# 用tf.data将数据打乱并分成batch,Batch_size = 32
train_ds = tf.data.Dataset.from_tensor_slices((x_train, y_train)).shuffle(10000).batch(32)
test_ds = tf.data.Dataset.from_tensor_slices((x_test, y_test)).batch(32)


class MyModel(Model):
    def get_config(self):
        pass

    def __init__(self):
        super(MyModel, self).__init__()
        self.conv1 = Conv2D(32, 3, activation='relu')
        self.flatten = Flatten()
        self.d1 = Dense(128, activation='relu')
        self.d2 = Dense(10, activation='softmax')

    def call(self, x, training=None, mask=None):
        x = self.conv1(x)
        x = self.flatten(x)
        x = self.d1(x)
        return self.d2(x)


model = MyModel()

# 设置损失函数以及优化器
loss_object = tf.keras.losses.SparseCategoricalCrossentropy()
optimizer = tf.keras.optimizers.Adam()
# 选择衡量指标来评估模型的损失以及准确率
train_loss = tf.keras.metrics.Mean(name='train_loss')
train_accuracy = tf.keras.metrics.SparseCategoricalAccuracy(name='train_accuracy')

test_loss = tf.keras.metrics.Mean(name='test_loss')
test_accuracy = tf.keras.metrics.SparseCategoricalAccuracy(name='test_accuracy')


# 使用tf.GradientTape训练模型
@tf.function
def train_step(images, labels):
    with tf.GradientTape() as tape:
        predictions = model(images)
        # 计算损失
        loss = loss_object(labels, predictions)
    gradients = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(gradients, model.trainable_variables))

    train_loss(loss)
    train_accuracy(labels, predictions)


# 测试模型
@tf.function
def test_step(images, labels):
    predictions = model(images)
    t_loss = loss_object(labels, predictions)
    test_loss(t_loss)
    test_accuracy(labels, predictions)


EPOCHS = 5
for epoch in range(EPOCHS):
    # 在下一个epoch开始时，重置评估指标
    train_loss.reset_states()
    train_accuracy.reset_states()
    test_loss.reset_states()
    test_accuracy.reset_states()

    for images, labels in train_ds:
        train_step(images, labels)
    for test_images, test_labels in test_ds:
        test_step(test_images, test_labels)

    template = 'Epoch:{} loss:{} accuracy:{}, test loss:{}, test accuracy:{}'
    print(template.format(epoch + 1,
                          train_loss.result(),
                          train_accuracy.result() * 100,
                          test_loss.result(),
                          test_accuracy.result() * 100))
```
i have a error like this:
```
tensorflow.python.framework.errors_impl.NotFoundError:  No algorithm worked!
	 [[node my_model/conv2d/Conv2D (defined at E:/python/learnTensorFlow/UserGuide/快速入门.py:35) ]] [Op:__inference_train_step_531]
Errors may have originated from an input operation.
Input Source operations connected to node my_model/conv2d/Conv2D:
 Cast (defined at E:/python/learnTensorFlow/UserGuide/快速入门.py:58)
Function call stack:
train_step
```
when i runing the code, the full output info is:
```
2021-06-16 17:38:03.802929: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-06-16 17:38:13.895377: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2021-06-16 17:38:13.921252: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA GeForce RTX 3060 Laptop GPU computeCapability: 8.6
coreClock: 1.425GHz coreCount: 30 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 312.97GiB/s
2021-06-16 17:38:13.921449: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-06-16 17:38:13.933513: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-06-16 17:38:13.933669: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021-06-16 17:38:13.937037: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2021-06-16 17:38:13.938456: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2021-06-16 17:38:13.940974: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2021-06-16 17:38:13.943627: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2021-06-16 17:38:13.944370: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021-06-16 17:38:13.944532: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-06-16 17:38:13.944860: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-06-16 17:38:13.951923: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x201621b5d40 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-06-16 17:38:13.952116: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-06-16 17:38:13.952322: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA GeForce RTX 3060 Laptop GPU computeCapability: 8.6
coreClock: 1.425GHz coreCount: 30 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 312.97GiB/s
2021-06-16 17:38:13.952504: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-06-16 17:38:13.952593: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-06-16 17:38:13.952686: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021-06-16 17:38:13.952770: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2021-06-16 17:38:13.952857: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2021-06-16 17:38:13.952940: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2021-06-16 17:38:13.953019: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2021-06-16 17:38:13.953121: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021-06-16 17:38:13.953223: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-06-16 17:38:14.323054: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-06-16 17:38:14.323167: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 
2021-06-16 17:38:14.323238: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N 
2021-06-16 17:38:14.323417: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4733 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 3060 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6)
2021-06-16 17:38:14.326010: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x201295d7b30 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-06-16 17:38:14.326134: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA GeForce RTX 3060 Laptop GPU, Compute Capability 8.6
2021-06-16 17:38:14.799589: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-06-16 17:38:14.825461: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-06-16 17:38:15.341945: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021-06-16 17:38:15.343490: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021-06-16 17:38:16.059391: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at conv_ops.cc:1106 : Not found: No algorithm worked!
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\PyCharm Community Edition 2021.1.1\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\PyCharm Community Edition 2021.1.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/python/learnTensorFlow/UserGuide/快速入门.py", line 86, in <module>
    train_step(images, labels)
  File "D:\anaconda3\envs\LearnKeras_GPU\lib\site-packages\tensorflow\python\eager\def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "D:\anaconda3\envs\LearnKeras_GPU\lib\site-packages\tensorflow\python\eager\def_function.py", line 888, in _call
    return self._stateless_fn(*args, **kwds)
  File "D:\anaconda3\envs\LearnKeras_GPU\lib\site-packages\tensorflow\python\eager\function.py", line 2943, in __call__
    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
  File "D:\anaconda3\envs\LearnKeras_GPU\lib\site-packages\tensorflow\python\eager\function.py", line 1919, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "D:\anaconda3\envs\LearnKeras_GPU\lib\site-packages\tensorflow\python\eager\function.py", line 560, in call
    ctx=ctx)
  File "D:\anaconda3\envs\LearnKeras_GPU\lib\site-packages\tensorflow\python\eager\execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.NotFoundError:  No algorithm worked!
	 [[node my_model/conv2d/Conv2D (defined at E:/python/learnTensorFlow/UserGuide/快速入门.py:35) ]] [Op:__inference_train_step_531]
Errors may have originated from an input operation.
Input Source operations connected to node my_model/conv2d/Conv2D:
 Cast (defined at E:/python/learnTensorFlow/UserGuide/快速入门.py:58)
Function call stack:
train_step
```

**Comment by tilakrayal** [comment]
@WoJiaYouTingShu ,

Every TensorFlow release is compatible with a certain version, for more information please take a look at the [tested build configurations](https://www.tensorflow.org/install/source_windows#gpu).In this case, can you please try installing TensorFlow v2.4 with CUDA 11.0 and cuDNN 8 and check if you are facing the same error. 


Version | Python version | Compiler | Build tools | cuDNN | CUDA
-- | -- | -- | -- | -- | --
tensorflow_gpu-2.5.0 | 3.6-3.9 | MSVC 2019 | Bazel 3.7.2 | 8.1 | 11.2
tensorflow_gpu-2.4.0 | 3.6-3.8 | MSVC 2019 | Bazel 3.1.0 | 8.0 | 11.0
tensorflow_gpu-2.3.0 | 3.5-3.8 | MSVC 2019 | Bazel 3.1.0 | 7.6 | 10.1



I was able to execute the code without any issues.Please find the gist [here](https://colab.research.google.com/gist/tilakrayal/ec6c25c79d3976cb0ceb6052ce93c9c7/untitled50302.ipynb).Thanks

**Comment by WoJiaYouTingShu** [comment]
hello, I installed cuda11.0 and cudnn8.0, but the problem still exists. @tilakrayal

**Comment by tilakrayal** [comment]
@WoJiaYouTingShu ,

Can you please try to install cudnn8.0.1 for cuda11.0. As mentioned above code is executing with out any issues please find the [gist](https://colab.research.google.com/gist/tilakrayal/ec6c25c79d3976cb0ceb6052ce93c9c7/untitled50302.ipynb).

Please feel free to move this issue to closed status and please submit a new issue from this [link](https://github.com/tensorflow/models/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!
