### ISSUE TITLE
Failed to build TensorFlow package builder

### ISSUE THREAD

**Issue by notooth1** [tensorflow/tensorflow#50340]
Can anyone help me fix this error:
```
$ bazel build --config=opt --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" //tensorflow/tools/pip_package:build_pip_package
...
ERROR: /mnt/Archive/Downloads/tensorflow/tensorflow/tools/pip_package/BUILD:179:10: error loading package '@com_github_grpc_grpc//': at /home/notooth/.cache/bazel/_bazel_notooth/d5b3b610a5827abc5897d0ec1ef6cd79/external/com_github_grpc_grpc/bazel/grpc_build_system.bzl:28:6: at /home/notooth/.cache/bazel/_bazel_notooth/d5b3b610a5827abc5897d0ec1ef6cd79/external/build_bazel_rules_apple/apple/ios.bzl:37:5: initialization of module 'apple/internal/ios_rules.bzl' failed and referenced by '//tensorflow/tools/pip_package:licenses'
...
```

**Comment by mihaimaruseac** [comment]
Can you fill in issue template? What is the commit you are building at?

What is the full error log?

**Comment by notooth1** [comment]
> Can you fill in issue template? What is the commit you are building at?

My system information:
- Debian 11
- HP DL380 G7
- TensorFlow r2.5 failed to install from source
- Python 3.9.2
- Installed using virtualenv 20.4.7, pip 21.1.2
- Bazel 5.0.0-pre.20210604.6
- GCC 10.2.1
- No CUDA

I am building Tensorflow to use Google T5.

Here is the full error log:
```
$ /home/notooth/bin/bazel build --config=opt --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" //tensorflow/tools/pip_package:build_pip_package
Starting local Bazel server and connecting to it...
WARNING: Option 'java_toolchain' is deprecated
WARNING: Option 'host_java_toolchain' is deprecated
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=121
INFO: Reading rc options for 'build' from /mnt/Archive/Downloads/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /mnt/Archive/Downloads/tensorflow/.bazelrc:
  'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2
INFO: Reading rc options for 'build' from /mnt/Archive/Downloads/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/home/notooth/.venv-py3/bin/python3 --action_env PYTHON_LIB_PATH=/home/notooth/.venv-py3/lib/python3.9/site-packages --python_path=/home/notooth/.venv-py3/bin/python3
INFO: Found applicable config definition build:short_logs in file /mnt/Archive/Downloads/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /mnt/Archive/Downloads/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:opt in file /mnt/Archive/Downloads/tensorflow/.tf_configure.bazelrc: --copt=-march=native --host_copt=-march=native --copt=-mssse3 --host_copt=-mssse3 --copt=-mcx16 --host_copt=-mcx16 --copt=-msse4.1 --host_copt=-msse4.1 --copt=-msse4.2 --host_copt=-msse4.2 --copt=-mpopcnt --host_copt=-mpopcnt
INFO: Found applicable config definition build:linux in file /mnt/Archive/Downloads/tensorflow/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
INFO: Found applicable config definition build:dynamic_kernels in file /mnt/Archive/Downloads/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
ERROR: Traceback (most recent call last):
        File "/home/notooth/.cache/bazel/_bazel_notooth/d5b3b610a5827abc5897d0ec1ef6cd79/external/build_bazel_rules_apple/apple/internal/testing/ios_rules.bzl", line 63, column 71, in <toplevel>
                _ios_internal_ui_test_bundle = rule_factory.create_apple_bundling_rule(
        File "/home/notooth/.cache/bazel/_bazel_notooth/d5b3b610a5827abc5897d0ec1ef6cd79/external/build_bazel_rules_apple/apple/internal/rule_factory.bzl", line 955, column 55, in _create_apple_bundling_rule
                rule_attrs.append(_common_binary_linking_attrs(rule_descriptor))
        File "/home/notooth/.cache/bazel/_bazel_notooth/d5b3b610a5827abc5897d0ec1ef6cd79/external/build_bazel_rules_apple/apple/internal/rule_factory.bzl", line 233, column 21, in _common_binary_linking_attrs
                apple_common.objc_proto_aspect,
Error: 'apple_common' value has no field or method 'objc_proto_aspect'
INFO: Repository functools32_archive instantiated at:
  /mnt/Archive/Downloads/tensorflow/WORKSPACE:15:14: in <toplevel>
  /mnt/Archive/Downloads/tensorflow/tensorflow/workspace2.bzl:1118:21: in workspace
  /mnt/Archive/Downloads/tensorflow/tensorflow/workspace2.bzl:418:20: in _tf_repositories
  /mnt/Archive/Downloads/tensorflow/third_party/repo.bzl:112:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  /mnt/Archive/Downloads/tensorflow/third_party/repo.bzl:65:35: in <toplevel>
INFO: Repository go_sdk instantiated at:
  /mnt/Archive/Downloads/tensorflow/WORKSPACE:23:14: in <toplevel>
  /mnt/Archive/Downloads/tensorflow/tensorflow/workspace0.bzl:117:20: in workspace
  /home/notooth/.cache/bazel/_bazel_notooth/d5b3b610a5827abc5897d0ec1ef6cd79/external/com_github_grpc_grpc/bazel/grpc_extra_deps.bzl:36:27: in grpc_extra_deps
  /home/notooth/.cache/bazel/_bazel_notooth/d5b3b610a5827abc5897d0ec1ef6cd79/external/io_bazel_rules_go/go/toolchain/toolchains.bzl:379:28: in go_register_toolchains
  /home/notooth/.cache/bazel/_bazel_notooth/d5b3b610a5827abc5897d0ec1ef6cd79/external/io_bazel_rules_go/go/private/sdk.bzl:65:21: in go_download_sdk
Repository rule _go_download_sdk defined at:
  /home/notooth/.cache/bazel/_bazel_notooth/d5b3b610a5827abc5897d0ec1ef6cd79/external/io_bazel_rules_go/go/private/sdk.bzl:53:35: in <toplevel>
INFO: Repository highwayhash instantiated at:
  /mnt/Archive/Downloads/tensorflow/WORKSPACE:15:14: in <toplevel>
  /mnt/Archive/Downloads/tensorflow/tensorflow/workspace2.bzl:1111:28: in workspace
  /mnt/Archive/Downloads/tensorflow/tensorflow/workspace2.bzl:65:16: in _initialize_third_party
  /mnt/Archive/Downloads/tensorflow/third_party/highwayhash/workspace.bzl:6:20: in repo
  /mnt/Archive/Downloads/tensorflow/third_party/repo.bzl:112:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  /mnt/Archive/Downloads/tensorflow/third_party/repo.bzl:65:35: in <toplevel>
INFO: Repository aws instantiated at:
  /mnt/Archive/Downloads/tensorflow/WORKSPACE:15:14: in <toplevel>
  /mnt/Archive/Downloads/tensorflow/tensorflow/workspace2.bzl:1111:28: in workspace
  /mnt/Archive/Downloads/tensorflow/tensorflow/workspace2.bzl:56:8: in _initialize_third_party
  /mnt/Archive/Downloads/tensorflow/third_party/aws/workspace.bzl:9:20: in repo
  /mnt/Archive/Downloads/tensorflow/third_party/repo.bzl:112:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  /mnt/Archive/Downloads/tensorflow/third_party/repo.bzl:65:35: in <toplevel>
INFO: Repository rules_java instantiated at:
  /mnt/Archive/Downloads/tensorflow/WORKSPACE:23:14: in <toplevel>
  /mnt/Archive/Downloads/tensorflow/tensorflow/workspace0.bzl:117:20: in workspace
  /home/notooth/.cache/bazel/_bazel_notooth/d5b3b610a5827abc5897d0ec1ef6cd79/external/com_github_grpc_grpc/bazel/grpc_extra_deps.bzl:29:18: in grpc_extra_deps
  /home/notooth/.cache/bazel/_bazel_notooth/d5b3b610a5827abc5897d0ec1ef6cd79/external/com_google_protobuf/protobuf_deps.bzl:34:21: in protobuf_deps
Repository rule http_archive defined at:
  /home/notooth/.cache/bazel/_bazel_notooth/d5b3b610a5827abc5897d0ec1ef6cd79/external/bazel_tools/tools/build_defs/repo/http.bzl:339:31: in <toplevel>
INFO: Repository llvm-project instantiated at:
  /mnt/Archive/Downloads/tensorflow/WORKSPACE:15:14: in <toplevel>
  /mnt/Archive/Downloads/tensorflow/tensorflow/workspace2.bzl:1118:21: in workspace
  /mnt/Archive/Downloads/tensorflow/tensorflow/workspace2.bzl:667:9: in _tf_repositories
  /mnt/Archive/Downloads/tensorflow/third_party/llvm/workspace.bzl:10:20: in repo
  /mnt/Archive/Downloads/tensorflow/third_party/repo.bzl:112:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  /mnt/Archive/Downloads/tensorflow/third_party/repo.bzl:65:35: in <toplevel>
INFO: Repository enum34_archive instantiated at:
  /mnt/Archive/Downloads/tensorflow/WORKSPACE:15:14: in <toplevel>
  /mnt/Archive/Downloads/tensorflow/tensorflow/workspace2.bzl:1118:21: in workspace
  /mnt/Archive/Downloads/tensorflow/tensorflow/workspace2.bzl:506:20: in _tf_repositories
  /mnt/Archive/Downloads/tensorflow/third_party/repo.bzl:112:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  /mnt/Archive/Downloads/tensorflow/third_party/repo.bzl:65:35: in <toplevel>
INFO: Repository rules_python instantiated at:
  /mnt/Archive/Downloads/tensorflow/WORKSPACE:15:14: in <toplevel>
  /mnt/Archive/Downloads/tensorflow/tensorflow/workspace2.bzl:1118:21: in workspace
  /mnt/Archive/Downloads/tensorflow/tensorflow/workspace2.bzl:973:20: in _tf_repositories
  /mnt/Archive/Downloads/tensorflow/third_party/repo.bzl:112:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  /mnt/Archive/Downloads/tensorflow/third_party/repo.bzl:65:35: in <toplevel>
INFO: Repository clog instantiated at:
  /mnt/Archive/Downloads/tensorflow/WORKSPACE:15:14: in <toplevel>
  /mnt/Archive/Downloads/tensorflow/tensorflow/workspace2.bzl:1111:28: in workspace
  /mnt/Archive/Downloads/tensorflow/tensorflow/workspace2.bzl:57:9: in _initialize_third_party
  /mnt/Archive/Downloads/tensorflow/third_party/clog/workspace.bzl:6:20: in repo
  /mnt/Archive/Downloads/tensorflow/third_party/repo.bzl:112:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  /mnt/Archive/Downloads/tensorflow/third_party/repo.bzl:65:35: in <toplevel>
INFO: Repository sobol_data instantiated at:
  /mnt/Archive/Downloads/tensorflow/WORKSPACE:15:14: in <toplevel>
  /mnt/Archive/Downloads/tensorflow/tensorflow/workspace2.bzl:1111:28: in workspace
  /mnt/Archive/Downloads/tensorflow/tensorflow/workspace2.bzl:75:15: in _initialize_third_party
  /mnt/Archive/Downloads/tensorflow/third_party/sobol_data/workspace.bzl:6:20: in repo
  /mnt/Archive/Downloads/tensorflow/third_party/repo.bzl:112:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  /mnt/Archive/Downloads/tensorflow/third_party/repo.bzl:65:35: in <toplevel>
INFO: Repository ruy instantiated at:
  /mnt/Archive/Downloads/tensorflow/WORKSPACE:15:14: in <toplevel>
  /mnt/Archive/Downloads/tensorflow/tensorflow/workspace2.bzl:1111:28: in workspace
  /mnt/Archive/Downloads/tensorflow/tensorflow/workspace2.bzl:74:8: in _initialize_third_party
  /mnt/Archive/Downloads/tensorflow/third_party/ruy/workspace.bzl:6:20: in repo
  /mnt/Archive/Downloads/tensorflow/third_party/repo.bzl:112:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  /mnt/Archive/Downloads/tensorflow/third_party/repo.bzl:65:35: in <toplevel>
INFO: Repository absl_py instantiated at:
  /mnt/Archive/Downloads/tensorflow/WORKSPACE:15:14: in <toplevel>
  /mnt/Archive/Downloads/tensorflow/tensorflow/workspace2.bzl:1118:21: in workspace
  /mnt/Archive/Downloads/tensorflow/tensorflow/workspace2.bzl:489:20: in _tf_repositories
  /mnt/Archive/Downloads/tensorflow/third_party/repo.bzl:112:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  /mnt/Archive/Downloads/tensorflow/third_party/repo.bzl:65:35: in <toplevel>
INFO: Repository gif instantiated at:
  /mnt/Archive/Downloads/tensorflow/WORKSPACE:15:14: in <toplevel>
  /mnt/Archive/Downloads/tensorflow/tensorflow/workspace2.bzl:1118:21: in workspace
  /mnt/Archive/Downloads/tensorflow/tensorflow/workspace2.bzl:358:20: in _tf_repositories
  /mnt/Archive/Downloads/tensorflow/third_party/repo.bzl:112:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  /mnt/Archive/Downloads/tensorflow/third_party/repo.bzl:65:35: in <toplevel>
INFO: Repository rules_proto instantiated at:
  /mnt/Archive/Downloads/tensorflow/WORKSPACE:23:14: in <toplevel>
  /mnt/Archive/Downloads/tensorflow/tensorflow/workspace0.bzl:117:20: in workspace
  /home/notooth/.cache/bazel/_bazel_notooth/d5b3b610a5827abc5897d0ec1ef6cd79/external/com_github_grpc_grpc/bazel/grpc_extra_deps.bzl:29:18: in grpc_extra_deps
  /home/notooth/.cache/bazel/_bazel_notooth/d5b3b610a5827abc5897d0ec1ef6cd79/external/com_google_protobuf/protobuf_deps.bzl:42:21: in protobuf_deps
Repository rule http_archive defined at:
  /home/notooth/.cache/bazel/_bazel_notooth/d5b3b610a5827abc5897d0ec1ef6cd79/external/bazel_tools/tools/build_defs/repo/http.bzl:339:31: in <toplevel>
ERROR: /mnt/Archive/Downloads/tensorflow/tensorflow/tools/pip_package/BUILD:179:10: error loading package '@com_github_grpc_grpc//': at /home/notooth/.cache/bazel/_bazel_notooth/d5b3b610a5827abc5897d0ec1ef6cd79/external/com_github_grpc_grpc/bazel/grpc_build_system.bzl:28:6: at /home/notooth/.cache/bazel/_bazel_notooth/d5b3b610a5827abc5897d0ec1ef6cd79/external/build_bazel_rules_apple/apple/ios.bzl:22:5: initialization of module 'apple/internal/testing/ios_rules.bzl' failed and referenced by '//tensorflow/tools/pip_package:licenses'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Analysis failed
INFO: Elapsed time: 8.916s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (193 packages loaded, 3622 targets configured)
    currently loading: @com_google_protobuf// ... (3 packages)
    Fetching ...docker; Cloning 251f6a68b439744094faff800cd029798edf9faa of https://github.com/bazelbuild/rules_docker.\
git
```

**Comment by mihaimaruseac** [comment]
```
ERROR: Traceback (most recent call last):
        File "/home/notooth/.cache/bazel/_bazel_notooth/d5b3b610a5827abc5897d0ec1ef6cd79/external/build_bazel_rules_apple/apple/internal/testing/ios_rules.bzl", line 63, column 71, in <toplevel>
                _ios_internal_ui_test_bundle = rule_factory.create_apple_bundling_rule(
        File "/home/notooth/.cache/bazel/_bazel_notooth/d5b3b610a5827abc5897d0ec1ef6cd79/external/build_bazel_rules_apple/apple/internal/rule_factory.bzl", line 955, column 55, in _create_apple_bundling_rule
                rule_attrs.append(_common_binary_linking_attrs(rule_descriptor))
        File "/home/notooth/.cache/bazel/_bazel_notooth/d5b3b610a5827abc5897d0ec1ef6cd79/external/build_bazel_rules_apple/apple/internal/rule_factory.bzl", line 233, column 21, in _common_binary_linking_attrs
                apple_common.objc_proto_aspect,
Error: 'apple_common' value has no field or method 'objc_proto_aspect'
```

Seems like a Bazel issue.

Are you building from `r2.5` branch?

**Comment by notooth1** [comment]
> Are you building from `r2.5` branch?

Yes, I had already chosen Tensorflow r2.5:
```
$ git checkout  r2.5           
Branch 'r2.5' set up to track remote branch 'r2.5' from 'origin'.
Switched to a new branch 'r2.5'
```

**Comment by mihaimaruseac** [comment]
Can you try

```
bazel clean --expunge && bazel build  --config=opt --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" //tensorflow/tools/pip_package:build_pip_package
```

If it has the same error, then it is a Bazel issue, not a TF one

**Comment by notooth1** [comment]
> Can you try
> 
> ```
> bazel clean --expunge && bazel build  --config=opt --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" //tensorflow/tools/pip_package:build_pip_package
> ```
> 
> If it has the same error, then it is a Bazel issue, not a TF one

I tried, and it had the same error. I think it is a Bazel issue.

**Comment by mohantym** [comment]
Hi @notooth1 ! Did you check  with [--define=no_tensorflow_py_deps=true](https://www.tensorflow.org/install/source_windows#bazel_build_options)  command too?
