### ISSUE TITLE
Does not furhter progress after `Successfully opened dynamic library libcublasLt` using multi NVIDIA V100 GPUs

### ISSUE THREAD

**Issue by mschnepf** [tensorflow/tensorflow#50363]
TensorFlow program runs successfully with one GPU. It also works with multiple NVIDIA GTX Titian GPUs within 2 minutes. However, when more than one NVIDIA V100 GPU should be used, TensorFlow does not further progress after `Successfully opened dynamic library libcublasLt.so.11` and the GPU utilization raises to 100% according to `nvidia-smi`. 

**System information**
- OS Platform and Distribution:
  - CentOS 7
- TensorFlow installed from pip
- TensorFlow version 2.5.0
- Python version 3.6.8
- CUDA version 11.2
- cuDNN version 8.2.1.32
- GPU NVIDIA V100 32GB

**Standalone code to reproduce the issue**
```
#!/usr/bin/env python3
import tensorflow as tf
import os

print("Tensorflow version: {}".format(tf.__version__))
import tensorflow_datasets as tfds

# load dataset
tfds.download.DownloadManager(download_dir=os.path.dirname(os.path.realpath(__file__)))
datasets, info = tfds.load(name='mnist', with_info=True, as_supervised=True,
                           data_dir=os.path.dirname(os.path.realpath(__file__)))
mnist_train, mnist_test = datasets['train'], datasets['test']

# Set Strategy
strategy = tf.distribute.MirroredStrategy()
print('Number of devices: {}'.format(strategy.num_replicas_in_sync))
num_train_examples = info.splits['train'].num_examples
num_test_examples = info.splits['test'].num_examples
BUFFER_SIZE = 10000
BATCH_SIZE_PER_REPLICA = 64
BATCH_SIZE = BATCH_SIZE_PER_REPLICA * strategy.num_replicas_in_sync

def scale(image, label):
  image = tf.cast(image, tf.float32)
  image /= 255
  return image, label

train_dataset = mnist_train.map(scale).cache().shuffle(BUFFER_SIZE).batch(BATCH_SIZE)
eval_dataset = mnist_test.map(scale).batch(BATCH_SIZE)
# Create model
with strategy.scope():
  model = tf.keras.Sequential([
      tf.keras.layers.Conv2D(32, 3, activation='relu', input_shape=(28, 28, 1)),
      tf.keras.layers.MaxPooling2D(),
      tf.keras.layers.Flatten(),
      tf.keras.layers.Dense(64, activation='relu'),
      tf.keras.layers.Dense(10)
  ])

  model.compile(loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
                optimizer=tf.keras.optimizers.Adam(),
                metrics=['accuracy'])
## Define the checkpoint directory to store the checkpoints
checkpoint_dir = './training_checkpoints'
## Name of the checkpoint files
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt_{epoch}")

# Function for decaying the learning rate.
def decay(epoch):
  if epoch < 3:
    return 1e-3
  elif epoch >= 3 and epoch < 7:
    return 1e-4
  else:
    return 1e-5

# Callback for printing the LR at the end of each epoch.
class PrintLR(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs=None):
    print('\nLearning rate for epoch {} is {}'.format(epoch + 1,
                                                      model.optimizer.lr.numpy()))
callbacks = [
    tf.keras.callbacks.TensorBoard(log_dir='./logs'),
    tf.keras.callbacks.ModelCheckpoint(filepath=checkpoint_prefix,
                                       save_weights_only=True),
    tf.keras.callbacks.LearningRateScheduler(decay),
    PrintLR()
]

# Train and evaluate
model.fit(train_dataset, epochs=12, callbacks=callbacks)
model.load_weights(tf.train.latest_checkpoint(checkpoint_dir))
eval_loss, eval_acc = model.evaluate(eval_dataset)
print('Eval loss: {}, Eval Accuracy: {}'.format(eval_loss, eval_acc))


# Export to SavedModel
path = 'saved_model/'
model.save(path, save_format='tf')
unreplicated_model = tf.keras.models.load_model(path)
unreplicated_model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=tf.keras.optimizers.Adam(),
    metrics=['accuracy'])

eval_loss, eval_acc = unreplicated_model.evaluate(eval_dataset)
print('Eval loss: {}, Eval Accuracy: {}'.format(eval_loss, eval_acc))


with strategy.scope():
  replicated_model = tf.keras.models.load_model(path)
  replicated_model.compile(loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
                           optimizer=tf.keras.optimizers.Adam(),
                           metrics=['accuracy'])
  eval_loss, eval_acc = replicated_model.evaluate(eval_dataset)
  print ('Eval loss: {}, Eval Accuracy: {}'.format(eval_loss, eval_acc))
```

**LOG with multiple V100 GPUs**
```
2021-06-19 11:38:35.846512: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-06-19 11:38:37.567052: W tensorflow/core/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "Not found: Could not locate the credentials file.". Retrieving token from GCE failed with "Failed precondition: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Could not resolve host: metadata".
Extraction completed...: 100%|##########| 4/4 [00:00<00:00,  5.59 file/s]
Dl Size...: 100%|##########| 10/10 [00:00<00:00, 13.96 MiB/s]
Dl Completed...: 100%|##########| 4/4 [00:00<00:00,  5.58 url/s]9 file/s]
Generating splits...:   0%|          | 0/2 [00:00<?, ? splits/2021-06-19 11:38:38.388762: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2021-06-19 11:38:38.495458: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA Tesla V100S-PCIE-32GB computeCapability: 7.0
coreClock: 1.597GHz coreCount: 80 deviceMemorySize: 31.75GiB deviceMemoryBandwidth: 1.03TiB/s
2021-06-19 11:38:38.499057: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 1 with properties: 
pciBusID: 0000:25:00.0 name: NVIDIA Tesla V100S-PCIE-32GB computeCapability: 7.0
coreClock: 1.597GHz coreCount: 80 deviceMemorySize: 31.75GiB deviceMemoryBandwidth: 1.03TiB/s
2021-06-19 11:38:38.499141: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-06-19 11:38:38.505167: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2021-06-19 11:38:38.505300: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
2021-06-19 11:38:38.507215: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcufft.so.10
2021-06-19 11:38:38.507603: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcurand.so.10
2021-06-19 11:38:38.509115: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusolver.so.11
2021-06-19 11:38:38.510381: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusparse.so.11
2021-06-19 11:38:38.510627: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudnn.so.8
2021-06-19 11:38:38.521523: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0, 1
2021-06-19 11:38:38.522242: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-06-19 11:38:39.059808: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA Tesla V100S-PCIE-32GB computeCapability: 7.0
coreClock: 1.597GHz coreCount: 80 deviceMemorySize: 31.75GiB deviceMemoryBandwidth: 1.03TiB/s
2021-06-19 11:38:39.065165: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 1 with properties: 
pciBusID: 0000:25:00.0 name: NVIDIA Tesla V100S-PCIE-32GB computeCapability: 7.0
coreClock: 1.597GHz coreCount: 80 deviceMemorySize: 31.75GiB deviceMemoryBandwidth: 1.03TiB/s
2021-06-19 11:38:39.079312: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0, 1
2021-06-19 11:38:39.079492: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-06-19 11:38:39.860307: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-06-19 11:38:39.860413: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0 1 
2021-06-19 11:38:39.860431: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N Y 
2021-06-19 11:38:39.860442: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 1:   Y N 
2021-06-19 11:38:39.876738: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 30995 MB memory) -> physical GPU (device: 0, name: NVIDIA Tesla V100S-PCIE-32GB, pci bus id: 0000:01:00.0, compute capability: 7.0)
2021-06-19 11:38:39.880520: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 30995 MB memory) -> physical GPU (device: 1, name: NVIDIA Tesla V100S-PCIE-32GB, pci bus id: 0000:25:00.0, compute capability: 7.0)
WARNING:tensorflow:Collective ops is not configured at program startup. Some performance features may not be enabled.
WARNING:tensorflow:Collective ops is not configured at program startup. Some performance features may not be enabled.
2021-06-19 11:38:58.854683: I tensorflow/core/profiler/lib/profiler_session.cc:126] Profiler session initializing.
2021-06-19 11:38:58.854764: I tensorflow/core/profiler/lib/profiler_session.cc:141] Profiler session started.
2021-06-19 11:38:58.854849: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1611] Profiler found 2 GPUs
2021-06-19 11:38:58.856387: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcupti.so.11.2
2021-06-19 11:38:59.211473: I tensorflow/core/profiler/lib/profiler_session.cc:159] Profiler session tear down.
2021-06-19 11:38:59.216559: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1743] CUPTI activity buffer flushed
2021-06-19 11:38:59.323866: W tensorflow/core/grappler/optimizers/data/auto_shard.cc:461] The `assert_cardinality` transformation is currently not handled by the auto-shard rewrite and will be removed.
2021-06-19 11:38:59.406847: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-06-19 11:38:59.407366: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 1999970000 Hz
2021-06-19 11:39:04.122930: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudnn.so.8
2021-06-19 11:39:04.528403: I tensorflow/stream_executor/cuda/cuda_dnn.cc:359] Loaded cuDNN version 8201
2021-06-19 11:39:05.177074: I tensorflow/stream_executor/cuda/cuda_dnn.cc:359] Loaded cuDNN version 8201
2021-06-19 11:39:05.622628: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2021-06-19 11:39:06.126034: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
```

**Comment by sanjoy** [comment]
Can you try to get a backtrace of the stuck process?  You can do that by starting `gdb`, [attaching](https://sourceware.org/gdb/onlinedocs/gdb/Attach.html) to the stuck python process and [getting a backtrace](https://sourceware.org/gdb/current/onlinedocs/gdb/Backtrace.html).

**Comment by mschnepf** [comment]
Hi sanjoy,
Thanks for the helpful comment. Here is the backtrace of my program:
```
#0  0x00007f80fc073d19 in syscall () from /usr/lib64/libc.so.6
#1  0x00007f7eb7b2e9ab in nsync::nsync_mu_semaphore_p_with_deadline(nsync::nsync_semaphore_s_*, timespec) ()
   from /home/schnepf/venv/lib64/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#2  0x00007f7eb7b2dfc9 in nsync::nsync_sem_wait_with_cancel_(nsync::waiter*, timespec, nsync::nsync_note_s_*) ()
   from /home/schnepf/venv/lib64/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#3  0x00007f7eb7b2b58b in nsync::nsync_cv_wait_with_deadline_generic(nsync::nsync_cv_s_*, void*, void (*)(void*), void (*)(void*), timespec, nsync::nsync_note_s_*) ()
   from /home/schnepf/venv/lib64/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#4  0x00007f7eb7b2ba63 in nsync::nsync_cv_wait_with_deadline(nsync::nsync_cv_s_*, nsync::nsync_mu_s_*, timespec, nsync::nsync_note_s_*) () from /home/schnepf/venv/lib64/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#5  0x00007f7eb2b0eaac in tensorflow::KernelAndDeviceFunc::Run(tensorflow::ScopedStepContainer*, tensorflow::EagerKernelArgs const&, std::vector<absl::lts_2020_09_23::variant<tensorflow::Tensor, tensorflow::TensorShape>, std::allocator<absl::lts_2020_09_23::variant<tensorflow::Tensor, tensorflow::TensorShape> > >*, tensorflow::CancellationManager*, absl::lts_2020_09_23::optional<tensorflow::EagerRemoteFunctionParams> const&, absl::lts_2020_09_23::optional<tensorflow::ManagedStackTrace> const&) ()
   from /home/schnepf/venv/lib64/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#6  0x00007f7eac7aad84 in tensorflow::EagerKernelExecute(tensorflow::EagerContext*, absl::lts_2020_09_23::InlinedVector<tensorflow::TensorHandle*, 4ul, std::allocator<tensorflow::TensorHandle*> > const&, absl::lts_2020_09_23::optional<tensorflow::EagerRemoteFunctionParams> const&, std::unique_ptr<tensorflow::KernelAndDevice, tensorflow::core::RefCountDeleter> const&, tensorflow::GraphCollector*, tensorflow::CancellationManager*, absl::lts_2020_09_23::Span<tensorflow::TensorHandle*>, absl::lts_2020_09_23::optional<tensorflow::ManagedStackTrace> const&) () from /home/schnepf/venv/lib64/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#7  0x00007f7eac7ab9f1 in tensorflow::ExecuteNode::Run() ()
   from /home/schnepf/venv/lib64/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#8  0x00007f7eb305e45f in tensorflow::EagerExecutor::SyncExecute(tensorflow::EagerNode*) ()
   from /home/schnepf/venv/lib64/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#9  0x00007f7eac7a8095 in tensorflow::(anonymous namespace)::EagerLocalExecute(tensorflow::EagerOperation*, tensorflow::TensorHandle**, int*) () from /home/schnepf/venv/lib64/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#10 0x00007f7eac7a90f0 in tensorflow::EagerExecute(tensorflow::EagerOperation*, tensorflow::TensorHandle**, int*) ()
   from /home/schnepf/venv/lib64/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#11 0x00007f7eac50ff89 in tensorflow::EagerOperation::Execute(absl::lts_2020_09_23::Span<tensorflow::AbstractTensorHandle*>, int*)
    () from /home/schnepf/venv/lib64/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#12 0x00007f7eb2b1d951 in tensorflow::CustomDeviceOpHandler::Execute(tensorflow::ImmediateExecutionOperation*, tensorflow::ImmediateExecutionTensorHandle**, int*) ()
   from /home/schnepf/venv/lib64/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#13 0x00007f7eabf194ed in TFE_Execute ()
   from /home/schnepf/venv/lib64/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#14 0x00007f7eabe850a5 in TFE_Py_ExecuteCancelable(TFE_Context*, char const*, char const*, absl::lts_2020_09_23::InlinedVector<TFE_TensorHandle*, 4ul, std::allocator<TFE_TensorHandle*> >*, _object*, TFE_CancellationManager*, absl::lts_2020_09_23::InlinedVector<TFE_TensorHandle*, 2ul, std::allocator<TFE_TensorHandle*> >*, TF_Status*) ()
   from /home/schnepf/venv/lib64/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#15 0x00007f7ea5751167 in tensorflow::TFE_Py_ExecuteCancelable_wrapper(pybind11::handle const&, char const*, char const*, pybind11::handle const&, pybind11::handle const&, tensorflow::CancellationManager*, pybind11::handle const&) ()
   from /home/schnepf/venv/lib64/python3.6/site-packages/tensorflow/python/_pywrap_tfe.so
#16 0x00007f7ea5753ee8 in void pybind11::cpp_function::initialize<pybind11_init__pywrap_tfe(pybind11::module_&)::{lambda(pybind11::handle const&, char const*, char const*, pybind11::handle const&, pybind11::handle const&, pybind11::handle const&)#42}, pybind11::object, pybind11::handle const&, char const*, char const*, pybind11::handle const&, pybind11::handle const&, pybind11::handle const&, pybind11::name, pybind11::scope, pybind11::sibling>(pybind11_init__pywrap_tfe(pybind11::module_&)::{lambda(pybind11::handle const&, char const*, char const*, pybind11::handle const&, pybind11::handle const&, pybind11::handle const&)#42}&&, pybind11::object (*)(pybind11::handle const&, char const*, char const*, pybind11::handle const&, pybind11::handle const&, pybind11::handle const&), pybind11::name const&, pybind11::scope const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call) () from /home/schnepf/venv/lib64/python3.6/site-packages/tensorflow/python/_pywrap_tfe.so
#17 0x00007f7ea576bc64 in pybind11::cpp_function::dispatcher(_object*, _object*, _object*) ()
   from /home/schnepf/venv/lib64/python3.6/site-packages/tensorflow/python/_pywrap_tfe.so
#18 0x00007f80fcd53f91 in _PyCFunction_FastCallDict () from /usr/lib64/libpython3.6m.so.1.0
#19 0x00007f80fcdbe66f in call_function () from /usr/lib64/libpython3.6m.so.1.0
#20 0x00007f80fcdb2db7 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#21 0x00007f80fcdbd5fa in _PyEval_EvalCodeWithName () from /usr/lib64/libpython3.6m.so.1.0
#22 0x00007f80fcdbe50a in fast_function () from /usr/lib64/libpython3.6m.so.1.0
#23 0x00007f80fcdbe793 in call_function () from /usr/lib64/libpython3.6m.so.1.0
#24 0x00007f80fcdb403b in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#25 0x00007f80fcdbd5fa in _PyEval_EvalCodeWithName () from /usr/lib64/libpython3.6m.so.1.0
#26 0x00007f80fcdbe50a in fast_function () from /usr/lib64/libpython3.6m.so.1.0
#27 0x00007f80fcdbe793 in call_function () from /usr/lib64/libpython3.6m.so.1.0
#28 0x00007f80fcdb403b in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#29 0x00007f80fcdbd5fa in _PyEval_EvalCodeWithName () from /usr/lib64/libpython3.6m.so.1.0
#30 0x00007f80fcdbe50a in fast_function () from /usr/lib64/libpython3.6m.so.1.0
#31 0x00007f80fcdbe793 in call_function () from /usr/lib64/libpython3.6m.so.1.0
#32 0x00007f80fcdb403b in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#33 0x00007f80fcdbd5fa in _PyEval_EvalCodeWithName () from /usr/lib64/libpython3.6m.so.1.0
#34 0x00007f80fcdbfa1e in _PyFunction_FastCallDict () from /usr/lib64/libpython3.6m.so.1.0
#35 0x00007f80fcd161fe in _PyObject_FastCallDict () from /usr/lib64/libpython3.6m.so.1.0
#36 0x00007f80fcd16311 in _PyObject_Call_Prepend () from /usr/lib64/libpython3.6m.so.1.0
#37 0x00007f80fcd15f83 in PyObject_Call () from /usr/lib64/libpython3.6m.so.1.0
#38 0x00007f80fcd6998d in slot_tp_call () from /usr/lib64/libpython3.6m.so.1.0
#39 0x00007f80fcd15f83 in PyObject_Call () from /usr/lib64/libpython3.6m.so.1.0
#40 0x00007f80fcdb4a41 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#41 0x00007f80fcdbda33 in _PyEval_EvalCodeWithName () from /usr/lib64/libpython3.6m.so.1.0
#42 0x00007f80fcdbfa1e in _PyFunction_FastCallDict () from /usr/lib64/libpython3.6m.so.1.0
#43 0x00007f80fcd161fe in _PyObject_FastCallDict () from /usr/lib64/libpython3.6m.so.1.0
#44 0x00007f80fcd16311 in _PyObject_Call_Prepend () from /usr/lib64/libpython3.6m.so.1.0
#45 0x00007f80fcd15f83 in PyObject_Call () from /usr/lib64/libpython3.6m.so.1.0
#46 0x00007f80fcdb4a41 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#47 0x00007f80fcdbd5fa in _PyEval_EvalCodeWithName () from /usr/lib64/libpython3.6m.so.1.0
#48 0x00007f80fcdbfa1e in _PyFunction_FastCallDict () from /usr/lib64/libpython3.6m.so.1.0
#49 0x00007f80fcd161fe in _PyObject_FastCallDict () from /usr/lib64/libpython3.6m.so.1.0
#50 0x00007f80fcd16311 in _PyObject_Call_Prepend () from /usr/lib64/libpython3.6m.so.1.0
#51 0x00007f80fcd15f83 in PyObject_Call () from /usr/lib64/libpython3.6m.so.1.0
#52 0x00007f80fcd6998d in slot_tp_call () from /usr/lib64/libpython3.6m.so.1.0
#53 0x00007f80fcd16180 in _PyObject_FastCallDict () from /usr/lib64/libpython3.6m.so.1.0
#54 0x00007f80fcdbe81c in call_function () from /usr/lib64/libpython3.6m.so.1.0
#55 0x00007f80fcdb2db7 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#56 0x00007f80fcdbd5fa in _PyEval_EvalCodeWithName () from /usr/lib64/libpython3.6m.so.1.0
#57 0x00007f80fcdbe50a in fast_function () from /usr/lib64/libpython3.6m.so.1.0
#58 0x00007f80fcdbe793 in call_function () from /usr/lib64/libpython3.6m.so.1.0
#59 0x00007f80fcdb403b in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#60 0x00007f80fcdbea35 in PyEval_EvalCodeEx () from /usr/lib64/libpython3.6m.so.1.0
#61 0x00007f80fcdbf7cb in PyEval_EvalCode () from /usr/lib64/libpython3.6m.so.1.0
#62 0x00007f80fce47dfe in run_mod () from /usr/lib64/libpython3.6m.so.1.0
#63 0x00007f80fccf4f43 in PyRun_FileExFlags () from /usr/lib64/libpython3.6m.so.1.0
#64 0x00007f80fccf5315 in PyRun_SimpleFileExFlags () from /usr/lib64/libpython3.6m.so.1.0
#65 0x00007f80fce4e2d2 in Py_Main () from /usr/lib64/libpython3.6m.so.1.0
#66 0x0000000000400ab9 in main ()
```

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
