### ISSUE TITLE
groups parameter for convolution layers is broken

### ISSUE THREAD

**Issue by fischeru** [tensorflow/tensorflow#50392]
### System information

- Custom code
- Linux Debian buster
- tensorflow from binary 2.6.0-dev20210621
- python 3-7
- CPU only

### Code to reproduce the problem

```
  import tensorflow as tf
  import numpy as np
  
 
  def try_call_with_gradient(model, input_shape):
      try:
          for _ in range(2):
              with tf.GradientTape() as tape:
                  x = np.random.normal(size=input_shape).astype(np.float32)
                  y = np.random.randint(2, size=(input_shape[0])).astype(np.int32)
  
                  out = model(x)
                  out = tf.reduce_mean(out, list(range(1, len(input_shape))))
  
                  loss = tf.keras.losses.binary_crossentropy(y, out, from_logits=True)
  
              grads = tape.gradient(loss, model.trainable_variables)
      except Exception as e:
          print(e)

  input_shape_1d = (3,12,4)
  model_1d = tf.keras.layers.Conv1D(filters=6, kernel_size=3, groups=2)
  try_call_with_gradient(model_1d, input_shape_1d)
  

  input_shape_2d = (3,12,12,4)
  model_2d = tf.keras.layers.Conv2D(filters=6, kernel_size=3, groups=2)
  try_call_with_gradient(model_2d, input_shape_2d)
  

  input_shape_3d = (3,12,12,12,4)
  model_3d = tf.keras.layers.Conv3D(filters=6, kernel_size=3, groups=2)
  try_call_with_gradient(model_3d, input_shape_3d)

```
Output:
```
Computed input depth 4 doesn't match filter input depth 2 [Op:Conv2DBackpropInput]
Computed input depth 4 doesn't match filter input depth 2 [Op:Conv2DBackpropInput]
Number of channels in filter (2) must match last dimension of input (4) [Op:Conv3D]
```

### Describe the problem
Convolution layers with non-trivial groups parameter are broken. 

Additionally Conv1D and Conv2D have different behavior than Conv3D, regarding when an error is thrown. The former break at the gradient computation, the latter at the forward call.

From my understanding and from the documentation, the only requirement for the **groups** parameter is that **filters** and **input channels** must be a multiple of **groups**. So the parameter choices look just fine to me. 

### Full Tracebacks

Once for 1D
```
Traceback (most recent call last):
  File ".../scratches/scratch.py", line 23, in <module>
    try_call_with_gradient(model_1d, input_shape_1d)
  File ".../scratches/scratch.py", line 17, in try_call_with_gradient
    grads = tape.gradient(loss, model.trainable_variables)
  File ".../python3.7/site-packages/tensorflow/python/eager/backprop.py", line 1090, in gradient
    unconnected_gradients=unconnected_gradients)
  File ".../python3.7/site-packages/tensorflow/python/eager/imperative_grad.py", line 77, in imperative_grad
    compat.as_str(unconnected_gradients.value))
  File ".../python3.7/site-packages/tensorflow/python/eager/backprop.py", line 159, in _gradient_function
    return grad_fn(mock_op, *out_grads)
  File ".../python3.7/site-packages/tensorflow/python/ops/nn_grad.py", line 590, in _Conv2DGrad
    data_format=data_format),
  File "...python3.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1247, in conv2d_backprop_input
    _ops.raise_from_not_ok_status(e, name)
  File ".../python3.7/site-packages/tensorflow/python/framework/ops.py", line 6941, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Computed input depth 4 doesn't match filter input depth 2 [Op:Conv2DBackpropInput]

Process finished with exit code 1
```
and once for 3D
```
Traceback (most recent call last):
  File ".../scratches/scratch.py", line 33, in <module>
    try_call_with_gradient(model_3d, input_shape_3d)
  File ".../scratches/scratch.py", line 12, in try_call_with_gradient
    out = model(x)
  File ".../python3.7/site-packages/keras/engine/base_layer.py", line 1037, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File ".../python3.7/site-packages/keras/layers/convolutional.py", line 249, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File ".../python3.7/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File ".../python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1138, in convolution_v2
    name=name)
  File ".../python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1268, in convolution_internal
    name=name)
  File ".../python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 3136, in _conv3d_expanded_batch
    name=name)
  File "...python3.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1400, in conv3d
    _ops.raise_from_not_ok_status(e, name)
  File ".../python3.7/site-packages/tensorflow/python/framework/ops.py", line 6941, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Number of channels in filter (2) must match last dimension of input (4) [Op:Conv3D]

Process finished with exit code 1
```

**Comment by fischeru** [comment]
I had some deeper look into the generic 'Conv' class in tensorflow/python/keras/layers/convolutional.py.

Besides some checks the **groups** parameter is only used to adjust the size of the allocated kernel variable. It has no impact on the created convolution op as far as I can see.

Basically the use of grouped convolutions is not implemented...

**Comment by saikumarchalla** [comment]
Was able to reproduce the issue. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/0f3c77993e5d39082329bfcdaebe4306/untitled99.ipynb).Thanks!

**Comment by RemiLacroix-IDRIS** [comment]
@fischeru: I'm wondering if I have stumbled on the same issue:
```python
import tensorflow as tf                 
cg2=tf.keras.layers.Conv1D(4,4,groups=2)
print("cg2",cg2(tf.zeros((2,16,4))))    
```
causes error:
```
>>> import tensorflow as tf                 
>>> cg2=tf.keras.layers.Conv1D(4,4,groups=2)
>>> print("cg2",cg2(tf.zeros((2,16,4))))    
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/gpfslocalsup/pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1030, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/gpfslocalsup/pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/keras/layers/convolutional.py", line 249, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/gpfslocalsup/pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/gpfslocalsup/pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1019, in convolution_v2
    name=name)
  File "/gpfslocalsup/pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1149, in convolution_internal
    name=name)
  File "/gpfslocalsup/pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/gpfslocalsup/pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 602, in new_func
    return func(*args, **kwargs)
  File "/gpfslocalsup/pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 602, in new_func
    return func(*args, **kwargs)
  File "/gpfslocalsup/pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1892, in conv1d
    name=name)
  File "/gpfslocalsup/pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 932, in conv2d
    _ops.raise_from_not_ok_status(e, name)
  File "/gpfslocalsup/pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 6897, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: input and filter must have the same depth: 4 vs 2 [Op:Conv2D]
```

**Comment by fischeru** [comment]
@RemiLacroix-IDRIS: strange, for me this runs just fine with tensorflow 2.5. can this be a difference between tensorflow and tensorflow-gpu? I didn't know that tensorflow-gpu still exists as a separate package.

**Comment by RemiLacroix-IDRIS** [comment]
@fischeru: `tensorflow-gpu` is just the name of the Conda env here but it's the regular TensorFlow package.

Anyway turns out the issue is probably different as it happens only for our own builds, see #50628.

**Comment by gowthamkpr** [comment]
@fischeru I dont run into this issue in tensorflow 2.8.0. Please find the gist [here](https://colab.research.google.com/gist/gowthamkpr/b0e22698d986f397b90a09df4eb49819/untitled99.ipynb). Thanks!
