### ISSUE TITLE
NaNs/Infs in gradient of tf.image.ssim_multiscale

### ISSUE THREAD

**Issue by TrevorG** [tensorflow/tensorflow#50400]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): Installed from pip
- TensorFlow version (use command below): v2.5.0-rc3-213-ga4dfb8d1a71 2.5.0
- Python version: 3.6
- CUDA/cuDNN version: 11.2/8.1.1
- GPU model and memory: GTX 1060 6GB

**Describe the current behavior**
Calculating gradient of `tf.image.ssim_multiscale` fails (resulting in NaNs and +Infs) in case of MS-SSIM being equal to 0 (e.g. with negated images as inputs). 

**Describe the expected behavior**
Calculated gradient does not contain NaNs and Infs.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):  no

**Standalone code to reproduce the issue**
```python
import tensorflow as tf

tf.debugging.enable_check_numerics()

x = tf.Variable(tf.random.uniform(shape=(10, 64, 64, 1), minval=0, maxval=1))

with tf.GradientTape() as tape:
    y = tf.image.ssim_multiscale(x, 1 - x, max_val=1, filter_size=11, filter_sigma=1.5, power_factors=(0.07105472, 0.45297383, 0.47597145), k1=0.01, k2=0.045)

tape.gradient(y, x)
```

**Other info / logs**
Output of code above:
```
2021-06-22 13:49:31.098596: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudart64_110.dll
2021-06-22 13:49:33.278314: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library nvcuda.dll
2021-06-22 13:49:33.305643: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 1060 6GB computeCapability: 6.1
coreClock: 1.7715GHz coreCount: 10 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 178.99GiB/s
2021-06-22 13:49:33.305856: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudart64_110.dll
2021-06-22 13:49:33.313716: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cublas64_11.dll
2021-06-22 13:49:33.313841: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cublasLt64_11.dll
2021-06-22 13:49:33.317789: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cufft64_10.dll
2021-06-22 13:49:33.319230: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library curand64_10.dll
2021-06-22 13:49:33.324269: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cusolver64_11.dll
2021-06-22 13:49:33.327990: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cusparse64_11.dll
2021-06-22 13:49:33.328966: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudnn64_8.dll
2021-06-22 13:49:33.329199: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-06-22 13:49:33.329609: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-06-22 13:49:33.330158: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 1060 6GB computeCapability: 6.1
coreClock: 1.7715GHz coreCount: 10 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 178.99GiB/s
2021-06-22 13:49:33.330405: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-06-22 13:49:33.925802: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-06-22 13:49:33.925979: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
2021-06-22 13:49:33.926031: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
2021-06-22 13:49:33.926529: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4624 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
2021-06-22 13:49:34.160168: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudnn64_8.dll
2021-06-22 13:49:34.532402: I tensorflow/stream_executor/cuda/cuda_dnn.cc:359] Loaded cuDNN version 8101
2021-06-22 13:49:34.874100: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cublas64_11.dll
2021-06-22 13:49:35.251241: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cublasLt64_11.dll
Traceback (most recent call last):
  File "ssim_multiscale.py", line 12, in <module>
    tape.gradient(y, x)
  File "C:\python36_ver\cuda11_2_gpu_5_1_trunk\lib\site-packages\tensorflow\python\eager\backprop.py", line 1080, in gradient
    unconnected_gradients=unconnected_gradients)
  File "C:\python36_ver\cuda11_2_gpu_5_1_trunk\lib\site-packages\tensorflow\python\eager\imperative_grad.py", line 77, in imperative_grad
    compat.as_str(unconnected_gradients.value))
  File "C:\python36_ver\cuda11_2_gpu_5_1_trunk\lib\site-packages\tensorflow\python\eager\backprop.py", line 159, in _gradient_function
    return grad_fn(mock_op, *out_grads)
  File "C:\python36_ver\cuda11_2_gpu_5_1_trunk\lib\site-packages\tensorflow\python\ops\math_grad.py", line 1519, in _PowGrad
    gx = grad * y * math_ops.pow(x, y - 1)
  File "C:\python36_ver\cuda11_2_gpu_5_1_trunk\lib\site-packages\tensorflow\python\util\dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "C:\python36_ver\cuda11_2_gpu_5_1_trunk\lib\site-packages\tensorflow\python\ops\math_ops.py", line 688, in pow
    return gen_math_ops._pow(x, y, name=name)
  File "C:\python36_ver\cuda11_2_gpu_5_1_trunk\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 6722, in _pow
    _ctx, "Pow", name, x, y)
  File "C:\python36_ver\cuda11_2_gpu_5_1_trunk\lib\site-packages\tensorflow\python\debug\lib\check_numerics_callback.py", line 301, in callback
    path_length_limit=self._path_length_limit))
  File "C:\python36_ver\cuda11_2_gpu_5_1_trunk\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 1003, in check_numerics_v2
    _ops.raise_from_not_ok_status(e, name)
  File "C:\python36_ver\cuda11_2_gpu_5_1_trunk\lib\site-packages\tensorflow\python\framework\ops.py", line 6897, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError:

!!! Detected Infinity or NaN in output 0 of eagerly-executing op "Pow" (# of outputs: 1) !!!
  dtype: <dtype: 'float32'>
  shape: (10, 1, 3)
  # of +Inf elements: 20

  Input tensors (2):
         0: tf.Tensor(
[[[0.         0.         0.6353643 ]]

 [[0.         0.         0.53395146]]

 [[0.         0.         0.535903  ]]

 [[0.         0.         0.67927223]]

 [[0.         0.         0.5929147 ]]

 [[0.         0.         0.5948703 ]]

 [[0.         0.         0.6313471 ]]

 [[0.         0.         0.62584317]]

 [[0.         0.         0.71081793]]

 [[0.         0.         0.56649375]]], shape=(10, 1, 3), dtype=float32)
         1: tf.Tensor([-0.9289453  -0.54702616 -0.52402854], shape=(3,), dtype=float32)

 : Tensor had +Inf values [Op:CheckNumericsV2]
```

During diagnosing this problem, I have discovered that adding epsilon to `mcs_and_ssim` (e.g. in `image_ops_impl.py:4531`) seems to solve a problem. Probably, this is not a valid solution, but maybe it provides some useful information.

**Comment by UsharaniPagadala** [comment]
@Saduf2019 

I was able to replicate the issue reported here.Please find the [gist](https://colab.research.google.com/gist/UsharaniPagadala/572f7415ddb97f4008d0cede840335f5/untitled109.ipynb).Thanks

**Comment by UsharaniPagadala** [comment]
@Saduf2019 

I was able to replicate the issue reported here.Please find the [gist](https://colab.research.google.com/gist/UsharaniPagadala/572f7415ddb97f4008d0cede840335f5/untitled109.ipynb) .Thanks

**Comment by Saduf2019** [comment]
@TrevorG 
Could you please refer to [this link](https://stackoverflow.com/questions/38810424/how-does-one-debug-nan-values-in-tensorflow), which explains all the reasons and let us know if it helps.

**Comment by TrevorG** [comment]
I have read that post and, frankly speaking, I don't know how it relates to this specific problem. I have already (at least, I think so) located the source of Infs (I admit, it might not be clear from the post): it happens when at least one value in `mcs_and_ssim` is 0. It leads to Infs during calculating gradient of `math_ops.pow(mcs_and_ssim, power_factors)' in `image_ops_impl.py:4522`. The gradient is calculated with `pow(mcs_and_ssim, power_factors - 1)` (see `math_grad.py:1512`), AFAIU. And `power_factors` contains values in (0, 1) interval.

**Comment by zhujun98** [comment]
I just encountered the same issue. My code worked with version 2.4.3 started to produce Nan loss from the first epoch. The implementation in `image_ops_impl.py` has not changed. The issue persists in 2.6.0.

**Comment by MahmoudAshraf97** [comment]
The issue still exists, only solved by adding a very small number as mentioned in the original post, another workaround is to train for some iterations using MSE and then start the training from a saved checkpoint and continue using MS-SSIM

**Comment by gabrielpeixoto-cvai** [comment]
I have the same issue. I followed @MahmoudAshraf97 and trained using MSE for couple epochs then started a new training from MSe checkpoints with MS-SSIM, which went well for one epoch, before falling back to NaN on the second epoch. I am using tensorflow version 2.4.1.

**Comment by MahmoudAshraf97** [comment]
@gabrielpeixoto-cvai 
It's totally dependent on the model and the learning rate but in general the ms-ssim requires a good initial state or else it will fail to NaN regardless of the epoch when the output and the target have a very low ms-ssim score

**Comment by mohantym** [comment]
It is still replicating in [2.8](https://colab.sandbox.google.com/gist/mohantym/ea143fafbf3acb4eee5671d97632903c/github_50400.ipynb) .  Output of y values were 0 in the list which is causing **inf** gradient in this case.

**Comment by bhack** [comment]
https://arxiv.org/abs/2006.13846

![immagine](https://user-images.githubusercontent.com/1710528/187418653-8f5d43bd-7b37-4b04-bbf2-bca810920c2e.png)

Many implementations introduce a clamp:
https://kornia.readthedocs.io/en/latest/_modules/kornia/losses/ssim.html

**Comment by CamdenCU** [comment]
I'm still being affected by this.  When a color channel is anti-correlated between the two images it yields a negative number that is set to 0 through a nn_ops.relu (https://github.com/tensorflow/tensorflow/blob/v2.12.0/tensorflow/python/ops/image_ops_impl.py#L4570) before being raised to a fractional power (still 0) and multiplied by non-zero stuff (https://github.com/tensorflow/tensorflow/blob/v2.12.0/tensorflow/python/ops/image_ops_impl.py#L4578-4579).

`
import tensorflow as tf
a = tf.Variable(-3.0)
with tf.GradientTape() as tape:
  b = tf.math.pow(tf.nn.relu(a),tf.constant(0.7))
  gradients = tape.gradient(b,[a])

print(gradients)
`

The gradient of the 0 input to the pow is (sensibly) inf.  However, then the gradient of the negative input to the relu is nan.  I would want it to be 0---there is no local dependence of the relu output on the input conditioned on the input being negative.

Any workaround short of implementing my own relu?

**Comment by JXRiver** [comment]
This could because relu uses its input instead of output for gradient computation.

```
x = tf.Variable(-3.)
with tf.GradientTape() as tape:
  b = tf.math.pow(x, tf.constant(0.7))
  gradients = tape.gradient(b, [x])

print(gradients) # (gives nan)
```

One workaround is to use custom_gradient, which may or may not work depending on your use case. Something like

```
@tf.custom_gradient
def relu(x):
  y = tf.nn.relu(x)
  def grad(upstream):
    if x < 0:
      return tf.zeros_like(upstream)
    if x == 0:
      return nan
    return upstream
  return y, grad

a = tf.Variable(-3.0)
with tf.GradientTape() as tape:
  b = tf.math.pow(relu(a),tf.constant(0.7))
  gradients = tape.gradient(b,[a])

print(gradients) # (gives 0.0)
```
