### ISSUE TITLE
faster_rcnn_resnet101_v1_640x640_coco17_tpu-8 model showing error on Tensorflow 2.5

### ISSUE THREAD

**Issue by Priyabrata409** [tensorflow/tensorflow#50411]
I am using python3.8 and Tensorflow 2.5.  I am trying to use faster_rcnn_resnet101_v1_640x640_coco17_tpu-8 model to do object detection but it is showing me following error
I0623 11:55:46.608306  5796 config_util.py:552] Maybe overwriting use_bfloat16: False
Traceback (most recent call last):
  File "Tensorflow\models\research\object_detection\model_main_tf2.py", line 113, in <module>
    tf.compat.v1.app.run()
  File "C:\Users\priyabrata\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\priyabrata\anaconda3\envs\new_tfod_env\lib\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "C:\Users\priyabrata\anaconda3\envs\new_tfod_env\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "Tensorflow\models\research\object_detection\model_main_tf2.py", line 104, in main
    model_lib_v2.train_loop(
  File "C:\Users\priyabrata\anaconda3\envs\new_tfod_env\lib\site-packages\object_detection-0.1-py3.8.egg\object_detection\model_lib_v2.py", line 535, in train_loop
    detection_model = MODEL_BUILD_UTIL_MAP['detection_model_fn_base'](
  File "C:\Users\priyabrata\anaconda3\envs\new_tfod_env\lib\site-packages\object_detection-0.1-py3.8.egg\object_detection\builders\model_builder.py", line 1199, in build
    return build_func(getattr(model_config, meta_architecture), is_training,
  File "C:\Users\priyabrata\anaconda3\envs\new_tfod_env\lib\site-packages\object_detection-0.1-py3.8.egg\object_detection\builders\model_builder.py", line 391, in _build_ssd_model
    _check_feature_extractor_exists(ssd_config.feature_extractor.type)
  File "C:\Users\priyabrata\anaconda3\envs\new_tfod_env\lib\site-packages\object_detection-0.1-py3.8.egg\object_detection\builders\model_builder.py", line 263, in _check_feature_extractor_exists
    raise ValueError('{} is not supported. See `model_builder.py` for features '
ValueError:  is not supported. See `model_builder.py` for features extractors compatible with different versions of Tensorflow

**Comment by tilakrayal** [comment]
@Priyabrata409 ,

This issue is more suitable for TensorFlow Models repo. Please post it on Tensorflow Models repo from [here](https://github.com/tensorflow/models/issues/new/choose). Thanks!
