### ISSUE TITLE
'CuDNNLSTM' object has no attribute 'unroll'

### ISSUE THREAD

**Issue by dosier** [tensorflow/tensorflow#50475]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
N/A
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
2.5.0
- Python version:
3.8
- Bazel version (if compiling from source):
N/A
- GCC/Compiler version (if compiling from source):
N/A
- CUDA/cuDNN version:
CUDA = 11.3
cuDNN = 8201
- GPU model and memory:
Nvidia RTX 3070 (24gb)

**Describe the current behavior**
Model fails to save using ModelCheckPoint callback. 

**Describe the expected behavior**
Model saves best version using ModelCheckPoint callback

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
No
- Briefly describe your candidate solution(if contributing):
N/A

**Standalone code to reproduce the issue**
```Python
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
import numpy
from tensorflow.python.keras import Sequential
from tensorflow.python.keras.callbacks import ModelCheckpoint
from tensorflow.python.keras.layers import CuDNNLSTM

X = [
    [[1, 1, 1]],
    [[1, 1, 1]]
]

Y = [
    [1, 1, 1],
    [1, 1, 1]
]

X = numpy.array(X)
Y = numpy.array(Y)

model = Sequential()  # initialize a sequential model
model.add(CuDNNLSTM(3, return_sequences=False, input_shape=(1, 3)))  # 2nd layer of LSTM
model.compile(loss='mse', optimizer='rmsprop', metrics=['accuracy'])

model_checkpoint_callback = ModelCheckpoint(
    filepath='/tmp/checkpoint',
    save_weights_only=False,
    monitor='val_accuracy',
    mode='max',
    save_best_only=True)

model.fit(X, Y, batch_size=1, epochs=100, callbacks=[model_checkpoint_callback], validation_split=0.5)

```

**Other info / logs** Include any logs or source code that would be helpful to

> Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\31619\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\211.7442.45\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Users\31619\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\211.7442.45\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/31619/PycharmProjects/nn-drum-midi-synthesis/stackoverflow.py", line 30, in <module>
    model.fit(X, Y, batch_size=1, epochs=100, callbacks=[model_checkpoint_callback], validation_split=0.5)
  File "C:\Users\31619\PycharmProjects\nn-drum-midi-synthesis\venv\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1229, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "C:\Users\31619\PycharmProjects\nn-drum-midi-synthesis\venv\lib\site-packages\tensorflow\python\keras\callbacks.py", line 435, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "C:\Users\31619\PycharmProjects\nn-drum-midi-synthesis\venv\lib\site-packages\tensorflow\python\keras\callbacks.py", line 1369, in on_epoch_end
    self._save_model(epoch=epoch, logs=logs)
  File "C:\Users\31619\PycharmProjects\nn-drum-midi-synthesis\venv\lib\site-packages\tensorflow\python\keras\callbacks.py", line 1421, in _save_model
    self.model.save(filepath, overwrite=True, options=self._options)
  File "C:\Users\31619\PycharmProjects\nn-drum-midi-synthesis\venv\lib\site-packages\tensorflow\python\keras\engine\training.py", line 2111, in save
    save.save_model(self, filepath, overwrite, include_optimizer, save_format,
  File "C:\Users\31619\PycharmProjects\nn-drum-midi-synthesis\venv\lib\site-packages\tensorflow\python\keras\saving\save.py", line 150, in save_model
    saved_model_save.save(model, filepath, overwrite, include_optimizer,
  File "C:\Users\31619\PycharmProjects\nn-drum-midi-synthesis\venv\lib\site-packages\tensorflow\python\keras\saving\saved_model\save.py", line 89, in save
    saved_nodes, node_paths = save_lib.save_and_return_nodes(
  File "C:\Users\31619\PycharmProjects\nn-drum-midi-synthesis\venv\lib\site-packages\tensorflow\python\saved_model\save.py", line 1103, in save_and_return_nodes
    _build_meta_graph(obj, signatures, options, meta_graph_def,
  File "C:\Users\31619\PycharmProjects\nn-drum-midi-synthesis\venv\lib\site-packages\tensorflow\python\saved_model\save.py", line 1290, in _build_meta_graph
    return _build_meta_graph_impl(obj, signatures, options, meta_graph_def,
  File "C:\Users\31619\PycharmProjects\nn-drum-midi-synthesis\venv\lib\site-packages\tensorflow\python\saved_model\save.py", line 1207, in _build_meta_graph_impl
    signatures = signature_serialization.find_function_to_export(
  File "C:\Users\31619\PycharmProjects\nn-drum-midi-synthesis\venv\lib\site-packages\tensorflow\python\saved_model\signature_serialization.py", line 99, in find_function_to_export
    functions = saveable_view.list_functions(saveable_view.root)
  File "C:\Users\31619\PycharmProjects\nn-drum-midi-synthesis\venv\lib\site-packages\tensorflow\python\saved_model\save.py", line 154, in list_functions
    obj_functions = obj._list_functions_for_serialization(  # pylint: disable=protected-access
  File "C:\Users\31619\PycharmProjects\nn-drum-midi-synthesis\venv\lib\site-packages\tensorflow\python\keras\engine\training.py", line 2713, in _list_functions_for_serialization
    functions = super(
  File "C:\Users\31619\PycharmProjects\nn-drum-midi-synthesis\venv\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 3016, in _list_functions_for_serialization
    return (self._trackable_saved_model_saver
  File "C:\Users\31619\PycharmProjects\nn-drum-midi-synthesis\venv\lib\site-packages\tensorflow\python\keras\saving\saved_model\base_serialization.py", line 92, in list_functions_for_serialization
    fns = self.functions_to_serialize(serialization_cache)
  File "C:\Users\31619\PycharmProjects\nn-drum-midi-synthesis\venv\lib\site-packages\tensorflow\python\keras\saving\saved_model\layer_serialization.py", line 73, in functions_to_serialize
    return (self._get_serialized_attributes(
  File "C:\Users\31619\PycharmProjects\nn-drum-midi-synthesis\venv\lib\site-packages\tensorflow\python\keras\saving\saved_model\layer_serialization.py", line 89, in _get_serialized_attributes
    object_dict, function_dict = self._get_serialized_attributes_internal(
  File "C:\Users\31619\PycharmProjects\nn-drum-midi-synthesis\venv\lib\site-packages\tensorflow\python\keras\saving\saved_model\model_serialization.py", line 53, in _get_serialized_attributes_internal
    super(ModelSavedModelSaver, self)._get_serialized_attributes_internal(
  File "C:\Users\31619\PycharmProjects\nn-drum-midi-synthesis\venv\lib\site-packages\tensorflow\python\keras\saving\saved_model\layer_serialization.py", line 99, in _get_serialized_attributes_internal
    functions = save_impl.wrap_layer_functions(self.obj, serialization_cache)
  File "C:\Users\31619\PycharmProjects\nn-drum-midi-synthesis\venv\lib\site-packages\tensorflow\python\keras\saving\saved_model\save_impl.py", line 154, in wrap_layer_functions
    original_fns = _replace_child_layer_functions(layer, serialization_cache)
  File "C:\Users\31619\PycharmProjects\nn-drum-midi-synthesis\venv\lib\site-packages\tensorflow\python\keras\saving\saved_model\save_impl.py", line 284, in _replace_child_layer_functions
    child_layer._trackable_saved_model_saver._get_serialized_attributes(
  File "C:\Users\31619\PycharmProjects\nn-drum-midi-synthesis\venv\lib\site-packages\tensorflow\python\keras\saving\saved_model\layer_serialization.py", line 89, in _get_serialized_attributes
    object_dict, function_dict = self._get_serialized_attributes_internal(
  File "C:\Users\31619\PycharmProjects\nn-drum-midi-synthesis\venv\lib\site-packages\tensorflow\python\keras\saving\saved_model\layer_serialization.py", line 151, in _get_serialized_attributes_internal
    super(RNNSavedModelSaver, self)._get_serialized_attributes_internal(
  File "C:\Users\31619\PycharmProjects\nn-drum-midi-synthesis\venv\lib\site-packages\tensorflow\python\keras\saving\saved_model\layer_serialization.py", line 99, in _get_serialized_attributes_internal
    functions = save_impl.wrap_layer_functions(self.obj, serialization_cache)
  File "C:\Users\31619\PycharmProjects\nn-drum-midi-synthesis\venv\lib\site-packages\tensorflow\python\keras\saving\saved_model\save_impl.py", line 161, in wrap_layer_functions
    call_collection = LayerCallCollection(layer)
  File "C:\Users\31619\PycharmProjects\nn-drum-midi-synthesis\venv\lib\site-packages\tensorflow\python\keras\saving\saved_model\save_impl.py", line 411, in __init__
    self._input_signature = self._generate_input_signature(layer)
  File "C:\Users\31619\PycharmProjects\nn-drum-midi-synthesis\venv\lib\site-packages\tensorflow\python\keras\saving\saved_model\save_impl.py", line 436, in _generate_input_signature
    layer._use_input_spec_as_call_signature):  # pylint: disable=protected-access
  File "C:\Users\31619\PycharmProjects\nn-drum-midi-synthesis\venv\lib\site-packages\tensorflow\python\keras\layers\recurrent.py", line 445, in _use_input_spec_as_call_signature
    if self.unroll:
AttributeError: 'CuDNNLSTM' object has no attribute 'unroll'

**Comment by UsharaniPagadala** [comment]
@dosier 
In TensorFlow V2.0, the built-in LSTM and GRU layers have been updated to leverage CuDNN kernels by default when a GPU is available. 
Pease refer the [document](https://www.tensorflow.org/guide/keras/rnn#performance_optimization_and_cudnn_kernels).I have done minimal code changes and didn't face any errors.Please find the [gist](https://colab.research.google.com/gist/UsharaniPagadala/e73753dacc1911aafa93cb3addb855e9/untitled119.ipynb#scrollTo=8Eg98fJQ2Q8k) ,and let us know if it helps.Thanks

**Comment by dosier** [comment]
Hi @UsharaniPagadala , thanks for the reply. I must be doing something wrong, `tf.python.keras.layers.LSTM` is much slower for me than `tf.python.keras.layers.CuDNNLSTM` is. I can put this in a separate issue though. Unless you have some quick tips on why this might be. 

These are the logs I get for using the bilt-in LSTM

> 2021-06-28 17:39:39.494450: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library nvcuda.dll
> 2021-06-28 17:39:39.531066: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
> pciBusID: 0000:01:00.0 name: NVIDIA GeForce RTX 3070 computeCapability: 8.6
> coreClock: 1.725GHz coreCount: 46 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 417.29GiB/s
> 2021-06-28 17:39:39.531587: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudart64_110.dll
> 2021-06-28 17:39:39.539789: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cublas64_11.dll
> 2021-06-28 17:39:39.540000: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cublasLt64_11.dll
> 2021-06-28 17:39:39.543534: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cufft64_10.dll
> 2021-06-28 17:39:39.544986: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library curand64_10.dll
> 2021-06-28 17:39:39.547731: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cusolver64_11.dll
> 2021-06-28 17:39:39.550825: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cusparse64_11.dll
> 2021-06-28 17:39:39.551568: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudnn64_8.dll
> 2021-06-28 17:39:39.551831: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
> 2021-06-28 17:39:39.552477: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
> To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
> 2021-06-28 17:39:39.553337: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
> pciBusID: 0000:01:00.0 name: NVIDIA GeForce RTX 3070 computeCapability: 8.6
> coreClock: 1.725GHz coreCount: 46 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 417.29GiB/s
> 2021-06-28 17:39:39.553861: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
> 2021-06-28 17:39:40.017993: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2021-06-28 17:39:40.018269: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0 
> 2021-06-28 17:39:40.018419: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N 
> 2021-06-28 17:39:40.018710: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5466 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 3070, pci bus id: 0000:01:00.0, compute capability: 8.6)
> Model: "drum_prediction"
> _________________________________________________________________
> Layer (type)                 Output Shape              Param #   
> =================================================================
> lstm (LSTM)                  (None, 512)               1069056   
> _________________________________________________________________
> dropout (Dropout)            (None, 512)               0         
> _________________________________________________________________
> dense (Dense)                (None, 9)                 4617      
> _________________________________________________________________
> activation (Activation)      (None, 9)                 0         
> =================================================================
> Total params: 1,073,673
> Trainable params: 1,073,673
> Non-trainable params: 0
> _________________________________________________________________
> 2021-06-28 17:39:40.530131: I tensorflow/core/profiler/lib/profiler_session.cc:126] Profiler session initializing.
> 2021-06-28 17:39:40.530317: I tensorflow/core/profiler/lib/profiler_session.cc:141] Profiler session started.
> 2021-06-28 17:39:40.530479: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1611] Profiler found 1 GPUs
> 2021-06-28 17:39:40.531881: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cupti64_112.dll
> 2021-06-28 17:39:40.643283: I tensorflow/core/profiler/lib/profiler_session.cc:159] Profiler session tear down.
> 2021-06-28 17:39:40.643559: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1743] CUPTI activity buffer flushed
> 2021-06-28 17:39:40.732297: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
> Epoch 1/500
> 2021-06-28 17:39:43.090319: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cublas64_11.dll
> 2021-06-28 17:39:43.903428: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cublasLt64_11.dll
> 2021-06-28 17:39:43.903753: I tensorflow/stream_executor/cuda/cuda_blas.cc:1838] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
> 1/6 [====>.........................] - ETA: 16s - loss: 0.69322021-06-28 17:39:44.702895: I tensorflow/core/profiler/lib/profiler_session.cc:126] Profiler session initializing.
> 2021-06-28 17:39:44.703048: I tensorflow/core/profiler/lib/profiler_session.cc:141] Profiler session started.
> 2/6 [=========>....................] - ETA: 4s - loss: 0.6877 2021-06-28 17:39:45.172997: I tensorflow/core/profiler/lib/profiler_session.cc:66] Profiler session collecting data.
> 2021-06-28 17:39:45.173997: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1743] CUPTI activity buffer flushed
> 2021-06-28 17:39:45.282066: I tensorflow/core/profiler/internal/gpu/cupti_collector.cc:673]  GpuTracer has collected 2908 callback api events and 2906 activity events. 
> 2021-06-28 17:39:45.367369: I tensorflow/core/profiler/lib/profiler_session.cc:159] Profiler session tear down.
> 2021-06-28 17:39:45.461905: I tensorflow/core/profiler/rpc/client/save_profile.cc:137] Creating directory: ./logs/nn-drum-synthesis\train\plugins\profile\2021_06_28_15_39_45
> 2021-06-28 17:39:45.507035: I tensorflow/core/profiler/rpc/client/save_profile.cc:143] Dumped gzipped tool data for trace.json.gz to ./logs/nn-drum-synthesis\train\plugins\profile\2021_06_28_15_39_45\DESKTOP-FEJLLI2.trace.json.gz
> 2021-06-28 17:39:45.624130: I tensorflow/core/profiler/rpc/client/save_profile.cc:137] Creating directory: ./logs/nn-drum-synthesis\train\plugins\profile\2021_06_28_15_39_45
> 2021-06-28 17:39:45.637734: I tensorflow/core/profiler/rpc/client/save_profile.cc:143] Dumped gzipped tool data for memory_profile.json.gz to ./logs/nn-drum-synthesis\train\plugins\profile\2021_06_28_15_39_45\DESKTOP-FEJLLI2.memory_profile.json.gz
> 2021-06-28 17:39:45.666741: I tensorflow/core/profiler/rpc/client/capture_profile.cc:251] Creating directory: ./logs/nn-drum-synthesis\train\plugins\profile\2021_06_28_15_39_45Dumped tool data for xplane.pb to ./logs/nn-drum-synthesis\train\plugins\profile\2021_06_28_15_39_45\DESKTOP-FEJLLI2.xplane.pb
> Dumped tool data for overview_page.pb to ./logs/nn-drum-synthesis\train\plugins\profile\2021_06_28_15_39_45\DESKTOP-FEJLLI2.overview_page.pb
> Dumped tool data for input_pipeline.pb to ./logs/nn-drum-synthesis\train\plugins\profile\2021_06_28_15_39_45\DESKTOP-FEJLLI2.input_pipeline.pb
> Dumped tool data for tensorflow_stats.pb to ./logs/nn-drum-synthesis\train\plugins\profile\2021_06_28_15_39_45\DESKTOP-FEJLLI2.tensorflow_stats.pb
> Dumped tool data for kernel_stats.pb to ./logs/nn-drum-synthesis\train\plugins\profile\2021_06_28_15_39_45\DESKTOP-FEJLLI2.kernel_stats.pb
>

**Comment by UsharaniPagadala** [comment]
@dosier 
Thanks for the update,glad it worked for you.Please move this to closed status and open a new issue with that error.

Thanks!
