### ISSUE TITLE
map_fn can't process sparse tensor in graph mode

### ISSUE THREAD

**Issue by breadbread1984** [tensorflow/tensorflow#50554]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5.0
- Python version: 3.8.5
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

v2.5.0-rc3-213-ga4dfb8d1a71 2.5.0

**Describe the current behavior**

the following customized keras layer can't be executed in graph mode.

```python
#!/usr/bin/python3

import numpy as np;
import tensorflow as tf;

# please ignore this function, it is just for generating a sparse tensor
def Dense2Sparse():
  dense = tf.keras.Input((None, None, None)); # dense.shape = (batch, num_heads, query_length, key_length)
  mask = tf.keras.Input((1, None, None)); # mask.shape = (batch, 1, query_length or 1, key_length)
  reshaped_mask = tf.keras.layers.Lambda(lambda x: tf.cond(tf.math.not_equal(tf.shape(x[0])[2], tf.shape(x[1])[2]), lambda: tf.tile(x[0], [1,1,tf.shape(x[1])[2],1,]), lambda: x[0]))([mask, dense]); # mask.shape = (batch, 1, query_length, key_length)
  reshaped_mask = tf.keras.layers.Lambda(lambda x: tf.tile(x[0],[1,tf.shape(x[1])[1],1,1]))([reshaped_mask, dense]); # mask.shape = (batch, num_heads, query_length, key_length)
  indices = tf.keras.layers.Lambda(lambda x: tf.where(tf.cast(x, dtype = tf.int32)))(reshaped_mask); # indices.shape = (num non zero values, 4)
  values = tf.keras.layers.Lambda(lambda x: tf.gather_nd(x[0], x[1]))([dense, indices]); # values.shape = (num non zero values)
  sparse = tf.keras.layers.Lambda(lambda x: tf.sparse.SparseTensor(x[0], values = x[1], dense_shape = tf.cast(tf.shape(x[2]), dtype = tf.int64)))([indices, values, dense]);
  return tf.keras.Model(inputs = (dense, mask), outputs = sparse);

# NOTE: ***this layer cannot be executed in graph mode***
class SparseDenseMatMul(tf.keras.layers.Layer):
  def __init__(self, **kwargs):
    super(SparseDenseMatMul, self).__init__(**kwargs);
  def call(self, inputs):
    a = inputs[0]; # a.shape = (batch, heads, query_length, key_length)
    b = inputs[1]; # b.shape = (batch, heads, key_length, value_dim)
    reshaped_a = tf.sparse.reshape(a, (-1, tf.shape(a)[-2], tf.shape(a)[-1])); # reshaped_a.shape = (batch * heads, query_length, key_length)
    reshaped_b = tf.reshape(b, (-1, tf.shape(b)[-2], tf.shape(b)[-1])); # reshaped_b.shape = (batch * heads, key_length, value_dim)
    def dot(x):
      a = x[0];
      b = x[1];
      c = tf.sparse.sparse_dense_matmul(a,b);
      return c; # c.shape = (query_length, value_dim)
    results = tf.map_fn(dot, (reshaped_a, reshaped_b), fn_output_signature = tf.TensorSpec((tf.shape(reshaped_a)[-2], tf.shape(reshaped_b)[-1]), dtype = tf.float32));
    results = tf.reshape(results, (tf.shape(a)[0], tf.shape(a)[1], tf.shape(results)[-2], tf.shape(results)[-1]));
    return results;

a = np.random.normal(size = (4,3,10,40));
mask = np.random.randint(low = 0, high = 2, size = (4,1,10,40));
a = Dense2Sparse()([a, mask]);
b = np.random.normal(size = (4,3,40,20)).astype(np.float32);

print(SparseDenseMatMul()([a,b])); # eager mode is OK

inputs_a = tf.keras.Input((None, None, None), sparse = True);
inputs_b = tf.keras.Input((None, None, None));
results_c = SparseDenseMatMul()([inputs_a,inputs_b]);
model = tf.keras.Model(inputs = (inputs_a, inputs_b), outputs = results_c);
print(model([a,b])); # graph mode is failed
```

**Describe the expected behavior**

map_fn should process sparse tensor in both eager and graph mode.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no 
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```python
#!/usr/bin/python3

import numpy as np;
import tensorflow as tf;

# please ignore this function, it is just for generating a sparse tensor
def Dense2Sparse():
  dense = tf.keras.Input((None, None, None)); # dense.shape = (batch, num_heads, query_length, key_length)
  mask = tf.keras.Input((1, None, None)); # mask.shape = (batch, 1, query_length or 1, key_length)
  reshaped_mask = tf.keras.layers.Lambda(lambda x: tf.cond(tf.math.not_equal(tf.shape(x[0])[2], tf.shape(x[1])[2]), lambda: tf.tile(x[0], [1,1,tf.shape(x[1])[2],1,]), lambda: x[0]))([mask, dense]); # mask.shape = (batch, 1, query_length, key_length)
  reshaped_mask = tf.keras.layers.Lambda(lambda x: tf.tile(x[0],[1,tf.shape(x[1])[1],1,1]))([reshaped_mask, dense]); # mask.shape = (batch, num_heads, query_length, key_length)
  indices = tf.keras.layers.Lambda(lambda x: tf.where(tf.cast(x, dtype = tf.int32)))(reshaped_mask); # indices.shape = (num non zero values, 4)
  values = tf.keras.layers.Lambda(lambda x: tf.gather_nd(x[0], x[1]))([dense, indices]); # values.shape = (num non zero values)
  sparse = tf.keras.layers.Lambda(lambda x: tf.sparse.SparseTensor(x[0], values = x[1], dense_shape = tf.cast(tf.shape(x[2]), dtype = tf.int64)))([indices, values, dense]);
  return tf.keras.Model(inputs = (dense, mask), outputs = sparse);

# NOTE: ***this layer cannot be executed in graph mode***
class SparseDenseMatMul(tf.keras.layers.Layer):
  def __init__(self, **kwargs):
    super(SparseDenseMatMul, self).__init__(**kwargs);
  def call(self, inputs):
    a = inputs[0]; # a.shape = (batch, heads, query_length, key_length)
    b = inputs[1]; # b.shape = (batch, heads, key_length, value_dim)
    reshaped_a = tf.sparse.reshape(a, (-1, tf.shape(a)[-2], tf.shape(a)[-1])); # reshaped_a.shape = (batch * heads, query_length, key_length)
    reshaped_b = tf.reshape(b, (-1, tf.shape(b)[-2], tf.shape(b)[-1])); # reshaped_b.shape = (batch * heads, key_length, value_dim)
    def dot(x):
      a = x[0];
      b = x[1];
      c = tf.sparse.sparse_dense_matmul(a,b);
      return c; # c.shape = (query_length, value_dim)
    results = tf.map_fn(dot, (reshaped_a, reshaped_b), fn_output_signature = tf.TensorSpec((tf.shape(reshaped_a)[-2], tf.shape(reshaped_b)[-1]), dtype = tf.float32));
    results = tf.reshape(results, (tf.shape(a)[0], tf.shape(a)[1], tf.shape(results)[-2], tf.shape(results)[-1]));
    return results;

a = np.random.normal(size = (4,3,10,40));
mask = np.random.randint(low = 0, high = 2, size = (4,1,10,40));
a = Dense2Sparse()([a, mask]);
b = np.random.normal(size = (4,3,40,20)).astype(np.float32);

print(SparseDenseMatMul()([a,b])); # eager mode is OK

inputs_a = tf.keras.Input((None, None, None), sparse = True);
inputs_b = tf.keras.Input((None, None, None));
results_c = SparseDenseMatMul()([inputs_a,inputs_b]);
model = tf.keras.Model(inputs = (inputs_a, inputs_b), outputs = results_c);
print(model([a,b])); # graph mode is failed
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
Traceback (most recent call last):
  File "test.py", line 44, in <module>
    results_c = SparseDenseMatMul()([inputs_a,inputs_b]);
  File "/home/xieyi/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 969, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "/home/xieyi/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1107, in _functional_construction_call
    outputs = self._keras_tensor_symbolic_call(
  File "/home/xieyi/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 840, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/home/xieyi/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 880, in _infer_output_signature
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/xieyi/.local/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 695, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    test.py:32 call  *
        results = tf.map_fn(dot, (reshaped_a, reshaped_b), fn_output_signature = tf.TensorSpec((tf.shape(reshaped_a)[-2], tf.shape(reshaped_b)[-1]), dtype = tf.float32));
    /home/xieyi/.local/lib/python3.8/site-packages/tensorflow/python/framework/tensor_spec.py:51 __init__  **
        self._shape = tensor_shape.TensorShape(shape)
    /home/xieyi/.local/lib/python3.8/site-packages/tensorflow/python/framework/tensor_shape.py:765 __init__
        self._dims = [Dimension(d) for d in dims]
    /home/xieyi/.local/lib/python3.8/site-packages/tensorflow/python/framework/tensor_shape.py:765 <listcomp>
        self._dims = [Dimension(d) for d in dims]
    /home/xieyi/.local/lib/python3.8/site-packages/tensorflow/python/framework/tensor_shape.py:206 __init__
        six.raise_from(
    <string>:3 raise_from
        

    TypeError: Dimension value must be integer or None or have an __index__ method, got value '<tf.Tensor 'sparse_dense_mat_mul_1/strided_slice_4:0' shape=() dtype=int32>' with type '<class 'tensorflow.python.framework.ops.Tensor'>'

```

**Comment by UsharaniPagadala** [comment]
@breadbread1984 
Some Arguments are deprecated in map_fn like dtype in future versions,for this refer  the [document](https://www.tensorflow.org/api_docs/python/tf/map_fn),might be that is causing [TypeError](https://www.tensorflow.org/api_docs/python/tf/map_fn#raises).

Looking at the error log at is looks like this [#169](https://github.com/tensorflow/transform/issues/169) and let us know if it helps.Thanks

**Comment by breadbread1984** [comment]
I am not using dtype of map_fn, the dtype is argument of TensorSpec.

**Comment by UsharaniPagadala** [comment]
@Saduf2019 

I was able to replicate the issue reported.Please find the [gist](https://colab.research.google.com/gist/UsharaniPagadala/4db7aa27dfe54a10038656d0a5dbeb59/-50554.ipynb) here.Thanks

**Comment by Saduf2019** [comment]
@breadbread1984 
Please post this issue on [keras-team/keras repo](https://github.com/keras-team/keras/issues).
To know more refer to:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999

**Comment by JXRiver** [comment]
To make your example work, you could simply replace
```
    results = tf.map_fn(dot, (reshaped_a, reshaped_b), fn_output_signature = tf.TensorSpec((tf.shape(reshaped_a)[-2], tf.shape(reshaped_b)[-1]), dtype = tf.float32));
```
with
```
    results = tf.map_fn(dot, (reshaped_a, reshaped_b), fn_output_signature = tf.TensorSpec((reshaped_a.shape[-2], reshaped_b.shape[-1]), dtype = tf.float32));
```
In graph mode, `tf.shape` returns a `tf.Tensor` which is not statically known in graph mode. As the error message suggested, `Dimension value must be integer or None or have an __index__ method` and cannot be a tensor. The `shape` attribute of a SparseTensor is a TensorShape which is statically known.
