### ISSUE TITLE
Issue with Conv1D when groups > 1 and using our own TensorFlow builds

### ISSUE THREAD

**Issue by RemiLacroix-IDRIS** [tensorflow/tensorflow#50628]
**System information**
- OS Platform and Distribution: Linux Red Hat Enterprise 8.1
- TensorFlow installed from: source
- TensorFlow version: v2.5.0-0-ga4dfb8d1a71 2.5.0 (more generally any version starting from 2.3.1)
- Python version: 3.7.10
- Bazel version: 3.7.2
- GCC/Compiler version: 8.3.1
- CUDA/cuDNN version: 11.2 / 8.0
- GPU model and memory: NVIDIA V100

**Describe the current behavior**

When using our own TensorFlow builds (starting at version 2.3.1 which added the  `groups` parameter), the following code snippet fails for `groups` greater than 1:
```python
import tensorflow as tf
import traceback

for g in (1,2,4):
    try:
        print(f"groups={g}")
        c = tf.keras.layers.Conv1D(4,4,groups=g)
        print(c(tf.ones((2,16,4))))
    except Exception as e:
        traceback.print_exc()
    finally:
        print()
```

Output is as follow:
```
groups=1
tf.Tensor(
[[[ 0.28654966  0.9454404  -1.1466699  -0.91166556]
  [ 0.28654966  0.9454404  -1.1466699  -0.91166556]
  [ 0.28654966  0.9454404  -1.1466699  -0.91166556]
  [ 0.28654966  0.9454404  -1.1466699  -0.91166556]
  [ 0.28654966  0.9454404  -1.1466699  -0.91166556]
  [ 0.28654966  0.9454404  -1.1466699  -0.91166556]
  [ 0.28654966  0.9454404  -1.1466699  -0.91166556]
  [ 0.28654966  0.9454404  -1.1466699  -0.91166556]
  [ 0.28654966  0.9454404  -1.1466699  -0.91166556]
  [ 0.28654966  0.9454404  -1.1466699  -0.91166556]
  [ 0.28654966  0.9454404  -1.1466699  -0.91166556]
  [ 0.28654966  0.9454404  -1.1466699  -0.91166556]
  [ 0.28654966  0.9454404  -1.1466699  -0.91166556]]

 [[ 0.28654966  0.9454404  -1.1466699  -0.91166556]
  [ 0.28654966  0.9454404  -1.1466699  -0.91166556]
  [ 0.28654966  0.9454404  -1.1466699  -0.91166556]
  [ 0.28654966  0.9454404  -1.1466699  -0.91166556]
  [ 0.28654966  0.9454404  -1.1466699  -0.91166556]
  [ 0.28654966  0.9454404  -1.1466699  -0.91166556]
  [ 0.28654966  0.9454404  -1.1466699  -0.91166556]
  [ 0.28654966  0.9454404  -1.1466699  -0.91166556]
  [ 0.28654966  0.9454404  -1.1466699  -0.91166556]
  [ 0.28654966  0.9454404  -1.1466699  -0.91166556]
  [ 0.28654966  0.9454404  -1.1466699  -0.91166556]
  [ 0.28654966  0.9454404  -1.1466699  -0.91166556]
  [ 0.28654966  0.9454404  -1.1466699  -0.91166556]]], shape=(2, 13, 4), dtype=float32)

groups=2
Traceback (most recent call last):
  File "groups.py", line 8, in <module>
    print(c(tf.ones((2,16,4))))
  File "/.../pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1030, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/.../pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/keras/layers/convolutional.py", line 249, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/.../pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/.../pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1019, in convolution_v2
    name=name)
  File "/.../pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1149, in convolution_internal
    name=name)
  File "/.../pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/.../pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 602, in new_func
    return func(*args, **kwargs)
  File "/.../pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 602, in new_func
    return func(*args, **kwargs)
  File "/.../pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1892, in conv1d
    name=name)
  File "/.../pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 932, in conv2d
    _ops.raise_from_not_ok_status(e, name)
  File "/.../pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 6897, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: input and filter must have the same depth: 4 vs 2 [Op:Conv2D]

groups=4
Traceback (most recent call last):
  File "groups.py", line 8, in <module>
    print(c(tf.ones((2,16,4))))
  File "/.../pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1030, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/.../pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/keras/layers/convolutional.py", line 249, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/.../pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/.../pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1019, in convolution_v2
    name=name)
  File "/.../pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1149, in convolution_internal
    name=name)
  File "/.../pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/.../pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 602, in new_func
    return func(*args, **kwargs)
  File "/.../pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 602, in new_func
    return func(*args, **kwargs)
  File "/.../pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1892, in conv1d
    name=name)
  File "/.../pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 932, in conv2d
    _ops.raise_from_not_ok_status(e, name)
  File "/.../pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 6897, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: input and filter must have the same depth: 4 vs 1 [Op:Conv2D]
```

**Describe the expected behavior**

If I run the same code snippet using a TensorFlow build from `pip`, I do not get any errors but I have a hard time understanding how this can build dependent:
```
groups=1
tf.Tensor(
[[[-0.05965281 -1.473797   -0.5487337  -0.34858704]
  [-0.05965281 -1.473797   -0.5487337  -0.34858704]
  [-0.05965281 -1.473797   -0.5487337  -0.34858704]
  [-0.05965281 -1.473797   -0.5487337  -0.34858704]
  [-0.05965281 -1.473797   -0.5487337  -0.34858704]
  [-0.05965281 -1.473797   -0.5487337  -0.34858704]
  [-0.05965281 -1.473797   -0.5487337  -0.34858704]
  [-0.05965281 -1.473797   -0.5487337  -0.34858704]
  [-0.05965281 -1.473797   -0.5487337  -0.34858704]
  [-0.05965281 -1.473797   -0.5487337  -0.34858704]
  [-0.05965281 -1.473797   -0.5487337  -0.34858704]
  [-0.05965281 -1.473797   -0.5487337  -0.34858704]
  [-0.05965281 -1.473797   -0.5487337  -0.34858704]]

 [[-0.05965281 -1.473797   -0.5487337  -0.34858704]
  [-0.05965281 -1.473797   -0.5487337  -0.34858704]
  [-0.05965281 -1.473797   -0.5487337  -0.34858704]
  [-0.05965281 -1.473797   -0.5487337  -0.34858704]
  [-0.05965281 -1.473797   -0.5487337  -0.34858704]
  [-0.05965281 -1.473797   -0.5487337  -0.34858704]
  [-0.05965281 -1.473797   -0.5487337  -0.34858704]
  [-0.05965281 -1.473797   -0.5487337  -0.34858704]
  [-0.05965281 -1.473797   -0.5487337  -0.34858704]
  [-0.05965281 -1.473797   -0.5487337  -0.34858704]
  [-0.05965281 -1.473797   -0.5487337  -0.34858704]
  [-0.05965281 -1.473797   -0.5487337  -0.34858704]
  [-0.05965281 -1.473797   -0.5487337  -0.34858704]]], shape=(2, 13, 4), dtype=float32)

groups=2
tf.Tensor(
[[[ 0.555179   -0.11330175  0.22858751 -1.1606797 ]
  [ 0.555179   -0.11330175  0.22858751 -1.1606797 ]
  [ 0.555179   -0.11330175  0.22858751 -1.1606797 ]
  [ 0.555179   -0.11330175  0.22858751 -1.1606797 ]
  [ 0.555179   -0.11330175  0.22858751 -1.1606797 ]
  [ 0.555179   -0.11330175  0.22858751 -1.1606797 ]
  [ 0.555179   -0.11330175  0.22858751 -1.1606797 ]
  [ 0.555179   -0.11330175  0.22858751 -1.1606797 ]
  [ 0.555179   -0.11330175  0.22858751 -1.1606797 ]
  [ 0.555179   -0.11330175  0.22858751 -1.1606797 ]
  [ 0.555179   -0.11330175  0.22858751 -1.1606797 ]
  [ 0.555179   -0.11330175  0.22858751 -1.1606797 ]
  [ 0.555179   -0.11330175  0.22858751 -1.1606797 ]]

 [[ 0.555179   -0.11330175  0.22858751 -1.1606797 ]
  [ 0.555179   -0.11330175  0.22858751 -1.1606797 ]
  [ 0.555179   -0.11330175  0.22858751 -1.1606797 ]
  [ 0.555179   -0.11330175  0.22858751 -1.1606797 ]
  [ 0.555179   -0.11330175  0.22858751 -1.1606797 ]
  [ 0.555179   -0.11330175  0.22858751 -1.1606797 ]
  [ 0.555179   -0.11330175  0.22858751 -1.1606797 ]
  [ 0.555179   -0.11330175  0.22858751 -1.1606797 ]
  [ 0.555179   -0.11330175  0.22858751 -1.1606797 ]
  [ 0.555179   -0.11330175  0.22858751 -1.1606797 ]
  [ 0.555179   -0.11330175  0.22858751 -1.1606797 ]
  [ 0.555179   -0.11330175  0.22858751 -1.1606797 ]
  [ 0.555179   -0.11330175  0.22858751 -1.1606797 ]]], shape=(2, 13, 4), dtype=float32)

groups=4
tf.Tensor(
[[[-0.9354149   0.7340534  -0.01698902  0.4960574 ]
  [-0.9354149   0.7340534  -0.01698902  0.4960574 ]
  [-0.9354149   0.7340534  -0.01698902  0.4960574 ]
  [-0.9354149   0.7340534  -0.01698902  0.4960574 ]
  [-0.9354149   0.7340534  -0.01698902  0.4960574 ]
  [-0.9354149   0.7340534  -0.01698902  0.4960574 ]
  [-0.9354149   0.7340534  -0.01698902  0.4960574 ]
  [-0.9354149   0.7340534  -0.01698902  0.4960574 ]
  [-0.9354149   0.7340534  -0.01698902  0.4960574 ]
  [-0.9354149   0.7340534  -0.01698902  0.4960574 ]
  [-0.9354149   0.7340534  -0.01698902  0.4960574 ]
  [-0.9354149   0.7340534  -0.01698902  0.4960574 ]
  [-0.9354149   0.7340534  -0.01698902  0.4960574 ]]

 [[-0.9354149   0.7340534  -0.01698902  0.4960574 ]
  [-0.9354149   0.7340534  -0.01698902  0.4960574 ]
  [-0.9354149   0.7340534  -0.01698902  0.4960574 ]
  [-0.9354149   0.7340534  -0.01698902  0.4960574 ]
  [-0.9354149   0.7340534  -0.01698902  0.4960574 ]
  [-0.9354149   0.7340534  -0.01698902  0.4960574 ]
  [-0.9354149   0.7340534  -0.01698902  0.4960574 ]
  [-0.9354149   0.7340534  -0.01698902  0.4960574 ]
  [-0.9354149   0.7340534  -0.01698902  0.4960574 ]
  [-0.9354149   0.7340534  -0.01698902  0.4960574 ]
  [-0.9354149   0.7340534  -0.01698902  0.4960574 ]
  [-0.9354149   0.7340534  -0.01698902  0.4960574 ]
  [-0.9354149   0.7340534  -0.01698902  0.4960574 ]]], shape=(2, 13, 4), dtype=float32)
```

Any ideas would be greatly appreciated!

**Comment by UsharaniPagadala** [comment]
@RemiLacroix-IDRIS 

I was able to reproduce the code shared in tf2.5 with no errors.Please find the [gist](https://colab.research.google.com/gist/UsharaniPagadala/1b99df45ccd916c456ecf8d92586a08d/untitled132.ipynb) here.

similar issue tracking [here](https://github.com/tensorflow/tensorflow/issues/50397) follow the thread aswell and also refer this [comment](https://stackoverflow.com/questions/66415623/group-convolution-in-keras).Thanks!

**Comment by RemiLacroix-IDRIS** [comment]
@UsharaniPagadala : As mentioned, that code works fine with the TensorFlow builds from pip but crashes with the builds we compile from source but that doesn't seem to make any sense.

I don't see how compilation can have in impact on this.

**Comment by RemiLacroix-IDRIS** [comment]
I had a closer look and the call path seems to be the same for both our compiled build and the build from pip.

The last call I could track is in function `conv2d` in `tensorflow/python/ops/gen_nn_ops.py`:
```python
  _ctx = _context._context or _context.context()
  tld = _ctx._thread_local_data
  if tld.is_eager:
    try:
      _result = pywrap_tfe.TFE_Py_FastPathExecute(
        _ctx, "Conv2D", name, input, filter, "strides", strides,
        "use_cudnn_on_gpu", use_cudnn_on_gpu, "padding", padding,
        "explicit_paddings", explicit_paddings, "data_format", data_format,
        "dilations", dilations)
      return _result
    except _core._NotOkStatusException as e:
      _ops.raise_from_not_ok_status(e, name)
    except _core._FallbackException:
      pass
```

The call to `pywrap_tfe.TFE_Py_FastPathExecute` returns successfully in the PIP build but fails with ours. Not sure how to get more information on what happens in that call.

Note that the issue occurs both in a CPU only-context and a GPU context.

**Comment by RemiLacroix-IDRIS** [comment]
Not sure if it can help troubleshooting but it seems that non-eager mode works as expected on both our builds and the PIP builds:
```python
import tensorflow as tf

class test(object):
   def __init__(self):
     self.cg1=tf.keras.layers.Conv1D(4,4,groups=1)
     self.cg2=tf.keras.layers.Conv1D(4,4,groups=2)
     self.cg4=tf.keras.layers.Conv1D(4,4,groups=4)

   @tf.function
   def call(self, inputs):
      tf.print("cgn", self.cg(inputs))
      tf.print("cg1", self.cg1(inputs))
      tf.print("cg2", self.cg2(inputs))
      tf.print("cg4", self.cg4(inputs))

tt=test()
tt.call(tf.ones((2,16,4)))
```

**Comment by RemiLacroix-IDRIS** [comment]
Not sure if it can help troubleshooting the issue but it seems that **non-eager mode** works as expected on both our builds and the PIP builds **when using a GPU device**:
```python
import tensorflow as tf

class test(object):
   def __init__(self):
     self.cg1=tf.keras.layers.Conv1D(4,4,groups=1)
     self.cg2=tf.keras.layers.Conv1D(4,4,groups=2)
     self.cg4=tf.keras.layers.Conv1D(4,4,groups=4)

   @tf.function
   def call(self, inputs):
      tf.print("cg1", self.cg1(inputs))
      tf.print("cg2", self.cg2(inputs))
      tf.print("cg4", self.cg4(inputs))

tt=test()
tt.call(tf.ones((2,16,4)))
```
but **it still crashes when using a CPU device** and **the error is different depending on the build used**:
* our own build:
```
Traceback (most recent call last):
  File "groups_non_eager.py", line 19, in <module>
    tt.call(tf.ones((2,16,4)))
  File "/.../pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "/.../pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 950, in _call
    return self._stateless_fn(*args, **kwds)
  File "/.../pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3024, in __call__
    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
  File "/.../pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1961, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/.../pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 596, in call
    ctx=ctx)
  File "/.../pub/anaconda-py3/2020.11/envs/tensorflow-gpu-2.5.0/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  input and filter must have the same depth: 4 vs 2
         [[node conv1d_3/conv1d (defined at groups_non_eager.py:16) ]] [Op:__inference_call_162]

Function call stack:
call
```
* PIP build:
```
Traceback (most recent call last):
  File "groups_non_eager.py", line 19, in <module>
    tt.call(tf.ones((2,16,4)))
  File "~/.local/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "~/.local/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 950, in _call
    return self._stateless_fn(*args, **kwds)
  File "~/.local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3024, in __call__
    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
  File "~/.local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1961, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "~/.local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 596, in call
    ctx=ctx)
  File "~/.local/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.UnimplementedError:  Fused conv implementation does not support grouped convolutions for now.
         [[node conv1d_3/conv1d (defined at groups_non_eager.py:16) ]] [Op:__inference_call_162]

Function call stack:
call
```

**Comment by RemiLacroix-IDRIS** [comment]
Hello,

I just realized that our builds have XLA enabled (`XLA_FLAGS=--xla_hlo_profile`), I guess it could be relevant for this issue.

**Comment by RemiLacroix-IDRIS** [comment]
@angerson : Hi. Would it be possible to have some feedback on this issue?

**Comment by RemiLacroix-IDRIS** [comment]
Hi. Any news regarding this issue?

**Comment by mohantym** [comment]
Hi @RemiLacroix-IDRIS ! I was not getting any error in 2.8 though. Can you please let us know from your end?

**Comment by RemiLacroix-IDRIS** [comment]
> Hi @RemiLacroix-IDRIS ! I was not getting any error in [2.8](https://colab.sandbox.google.com/drive/18HX1KyC1AEcZ2nosRaz-518p2B35FTuY?resourcekey=0-aXCTPqWy-yo9LmvlNArjNQ#scrollTo=k2LTRWLzO0uC) though. Can you please let us know from your end?

We currently don't have our own build of 2.8 since I couldn't try yet. It matters because the version from pip always was unaffected, my guess would be because it does not have `XLA_FLAGS=--xla_hlo_profile`.

**Comment by RemiLacroix-IDRIS** [comment]
The problem does not seem to appear in version 2.8.0 compiled from source.
