### ISSUE TITLE
Keras model compiled with custom loss raises "Cannot convert a symbolic Keras input/output to a numpy array" error.

### ISSUE THREAD

**Issue by Alexanderstaehle** [tensorflow/tensorflow#50678]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.5.0-rc3-213-ga4dfb8d1a71
- Python version: 3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
When trying to train a keras model compiled with a custom loss, model.train_on_batch raises the following exception (full traceback is below):
```  
TypeError: Cannot convert a symbolic Keras input/output to a numpy array. This error may indicate that you're trying to pass a symbolic value to a NumPy call, which is not supported. Or, you may be trying to pass Keras symbolic inputs/outputs to a TF API that does not register dispatching, preventing Keras from automatically converting the API call to a lambda layer in the Functional Model.
```
This error only occurs in the `gradient_penalty_loss` and not in the `wasserstein_loss` which is also a custom loss function

**Describe the expected behavior**
The `gradient_penalty_loss` should accept an extra argument like seen **[here](https://github.com/tensorflow/tensorflow/issues/38319#issuecomment-610475806)**

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):no
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
I am a bit new to the topic I am working on so I couldn't reduce the code further than this but i included `TODO`-comments to mark the important lines of code
```
from __future__ import print_function, division

import numpy as np
import tensorflow.keras.backend as K
import tensorflow.keras.layers
from tensorflow.keras.layers import BatchNormalization, Bidirectional, LSTM
from tensorflow.keras.layers import Input, Dense, Reshape
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.optimizers import RMSprop
from tensorflow.python.keras.layers import LeakyReLU
from tensorflow.python.keras.layers.merge import _Merge


class RandomWeightedAverage(_Merge):
    """Provides a (random) weighted average between real and generated trajectory samples"""

    def _merge_function(self, inputs):
        alpha = K.random_uniform((1, 144, 1))
        return (alpha * inputs[0]) + ((1 - alpha) * inputs[1])

def gradient_penalty_loss(averaged_samples):
    def loss(y_true, y_pred):
        """
        Computes gradient penalty based on prediction and weighted real / fake samples
        """
        gradients = K.gradients(y_pred, averaged_samples)[0]
        # compute the euclidean norm by squaring ...
        gradients_sqr = K.square(gradients)
        #   ... summing over the rows ...
        gradients_sqr_sum = K.sum(gradients_sqr,
                                  axis=np.arange(1, len(gradients_sqr.shape)))
        #   ... and sqrt
        gradient_l2_norm = K.sqrt(gradients_sqr_sum)
        # compute lambda * (1 - ||grad||)^2 still for each single sample
        gradient_penalty = K.square(1 - gradient_l2_norm)
        # return the mean as loss over all the batch samples
        return K.mean(gradient_penalty)

    return loss


def wasserstein_loss(y_true, y_pred):
    return K.mean(y_true * y_pred)


class WGANGP():
    def __init__(self):
        self.max_length = 144
        self.features = 1
        self.traj_shape = (self.max_length, self.features)
        self.latent_dim = 100

        # Following parameter and optimizer set as recommended in paper
        self.n_discriminator = 5
        optimizer = RMSprop(learning_rate=0.00005)

        # Build the generator and discriminator
        self.generator = self.build_generator()
        self.discriminator = self.build_discriminator()

        # -------------------------------
        # Construct Computational Graph
        #       for the Discriminator
        # -------------------------------

        # Freeze generator's layers while training discriminator
        self.generator.trainable = False

        # Trajectory input (real sample)
        real_traj = Input(shape=self.traj_shape)

        # Noise input
        noise_d = Input(shape=(self.latent_dim,))
        # Generate trajectory based of noise (fake sample)
        fake_traj = self.generator(noise_d)

        # Discriminator determines validity of the real and fake trajectories
        fake = self.discriminator(fake_traj)
        valid = self.discriminator(real_traj)

        # Construct weighted average between real and fake trajectories
        interpolated_traj = RandomWeightedAverage()([real_traj, fake_traj])
        # Determine validity of weighted sample
        validity_interpolated = self.discriminator(interpolated_traj)

        self.discriminator_model = Model(inputs=[real_traj, noise_d],
                                         outputs=[valid, fake, validity_interpolated])
        self.discriminator_model.compile(loss=[wasserstein_loss,
                                               wasserstein_loss,
                                               gradient_penalty_loss(averaged_samples=interpolated_traj)],
                                         optimizer=optimizer,
                                         loss_weights=[1, 1, 10])
        # -------------------------------
        # Construct Computational Graph
        #         for Generator
        # -------------------------------

        # For the generator we freeze the discriminator's layers
        self.discriminator.trainable = False
        self.generator.trainable = True

        # Sampled noise for input to generator
        noise_gen = Input(shape=(self.latent_dim,))
        # Generate trajectory based of noise
        traj = self.generator(noise_gen)
        # Discriminator determines validity
        valid = self.discriminator(traj)
        # Defines generator model
        self.generator_model = Model(noise_gen, valid)
        self.generator_model.compile(loss=wasserstein_loss, optimizer=optimizer)

    def build_generator(self):

        model = Sequential()

        model.add(Dense(256, input_dim=self.latent_dim))
        model.add(LeakyReLU(alpha=0.2))
        model.add(BatchNormalization(momentum=0.8))
        model.add(Dense(512))
        model.add(LeakyReLU(alpha=0.2))
        model.add(BatchNormalization(momentum=0.8))
        model.add(Dense(1024))
        model.add(LeakyReLU(alpha=0.2))
        model.add(BatchNormalization(momentum=0.8))
        model.add(Dense(np.prod(self.traj_shape), activation='tanh'))
        model.add(Reshape(self.traj_shape))

        model.summary()

        noise = Input(shape=(self.latent_dim,))
        img = model(noise)

        return Model(noise, img)

    def build_discriminator(self):

        model = Sequential()

        model.add(LSTM(512, input_shape=self.traj_shape, return_sequences=True))
        model.add(Bidirectional(LSTM(512)))
        model.add(Dense(512))
        model.add(LeakyReLU(alpha=0.2))
        model.add(Dense(256))
        model.add(LeakyReLU(alpha=0.2))
        model.add(Dense(1, activation='tanh'))

        model.summary()

        traj = Input(shape=self.traj_shape)
        validity = model(traj)

        return Model(traj, validity)

    def train(self, epochs, batch_size, sample_interval=50):
        # Training data
        X_train = np.load('data/preprocessed/train.npy', allow_pickle=True)

        # Adversarial ground truths
        valid = -np.ones((batch_size, 1))
        fake = np.ones((batch_size, 1))
        dummy = np.zeros((batch_size, 1))  # Dummy gt for gradient penalty
        for epoch in range(epochs):

            for _ in range(self.n_discriminator):
                # ---------------------
                #  Train Discriminator
                # ---------------------

                # Select a random batch of trajectories
                idx = np.random.randint(0, X_train.shape[0], batch_size)
                trajs = X_train[idx]
                # Sample generator input
                noise = np.random.normal(0, 1, (batch_size, self.latent_dim))
                # Train the discriminator
                #TODO: Error appears here after the first iteration
                d_loss = self.discriminator_model.train_on_batch([trajs, noise],
                                                                 [valid, fake, dummy])

            # ---------------------
            #  Train Generator
            # ---------------------

            g_loss = self.generator_model.train_on_batch(noise, valid)

            # Plot the progress
            print("%d [D loss: %f] [G loss: %f]" % (epoch, d_loss[0], g_loss))


if __name__ == '__main__':
    wgan = WGANGP()
    wgan.train(epochs=2000, batch_size=64, sample_interval=10)
```

**Other info / logs**
I attached some sample data to use to reproduce here: [train.zip](https://github.com/tensorflow/tensorflow/files/6785899/train.zip)
I mainly copied the code from **[here](https://github.com/keras-team/keras-contrib/blob/master/examples/improved_wgan.py)** where it seams to work using the partial function but that threw an error, so i applied the proposed changes from **[this issue](https://github.com/tensorflow/tensorflow/issues/38319#issuecomment-610475806)** but now i get the described error.
Full traceback of this issue:
```
Traceback (most recent call last):
  File "C:\Users\test\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\path\to\project\venv\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2833, in variable_creator_scope
    yield
  File "C:\path\to\project\venv\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1825, in train_on_batch
    logs = self.train_function(iterator)
  File "C:\path\to\project\venv\lib\site-packages\tensorflow\python\eager\def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "C:\path\to\project\venv\lib\site-packages\tensorflow\python\eager\def_function.py", line 933, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "C:\path\to\project\venv\lib\site-packages\tensorflow\python\eager\def_function.py", line 763, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "C:\path\to\project\venv\lib\site-packages\tensorflow\python\eager\function.py", line 3050, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "C:\path\to\project\venv\lib\site-packages\tensorflow\python\eager\function.py", line 3444, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\path\to\project\venv\lib\site-packages\tensorflow\python\eager\function.py", line 3279, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "C:\path\to\project\venv\lib\site-packages\tensorflow\python\framework\func_graph.py", line 999, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\path\to\project\venv\lib\site-packages\tensorflow\python\eager\def_function.py", line 672, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "C:\path\to\project\venv\lib\site-packages\tensorflow\python\framework\func_graph.py", line 986, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    C:\path\to\project\venv\lib\site-packages\tensorflow\python\keras\engine\training.py:855 train_function  *
        return step_function(self, iterator)
    CC:/path/to/project/lstm_wgan.py:37 loss  *
        gradients = K.gradients(y_pred, averaged_samples)[0]
    C:\path\to\project\venv\lib\site-packages\tensorflow\python\keras\backend.py:4131 gradients  **
        return gradients_module.gradients(
    C:\path\to\project\venv\lib\site-packages\tensorflow\python\ops\gradients_impl.py:169 gradients
        return gradients_util._GradientsHelper(
    C:\path\to\project\venv\lib\site-packages\tensorflow\python\ops\gradients_util.py:531 _GradientsHelper
        xs = ops.internal_convert_n_to_tensor_or_indexed_slices(
    C:\path\to\project\venv\lib\site-packages\tensorflow\python\framework\indexed_slices.py:369 internal_convert_n_to_tensor_or_indexed_slices
        internal_convert_to_tensor_or_indexed_slices(
    C:\path\to\project\venv\lib\site-packages\tensorflow\python\framework\indexed_slices.py:330 internal_convert_to_tensor_or_indexed_slices
        return ops.convert_to_tensor(value, dtype=dtype, name=name, as_ref=as_ref)
    C:\path\to\project\venv\lib\site-packages\tensorflow\python\profiler\trace.py:163 wrapped
        return func(*args, **kwargs)
    C:\path\to\project\venv\lib\site-packages\tensorflow\python\framework\ops.py:1566 convert_to_tensor
        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    C:\path\to\project\venv\lib\site-packages\tensorflow\python\framework\constant_op.py:339 _constant_tensor_conversion_function
        return constant(v, dtype=dtype, name=name)
    C:\path\to\project\venv\lib\site-packages\tensorflow\python\framework\constant_op.py:264 constant
        return _constant_impl(value, dtype, shape, name, verify_shape=False,
    C:\path\to\project\venv\lib\site-packages\tensorflow\python\framework\constant_op.py:281 _constant_impl
        tensor_util.make_tensor_proto(
    C:\path\to\project\venv\lib\site-packages\tensorflow\python\framework\tensor_util.py:435 make_tensor_proto
        values = np.asarray(values)
    C:\path\to\project\venv\lib\site-packages\numpy\core\_asarray.py:83 asarray
        return array(a, dtype, copy=False, order=order)
    C:\path\to\project\venv\lib\site-packages\tensorflow\python\keras\engine\keras_tensor.py:254 __array__
        raise TypeError(

    TypeError: Cannot convert a symbolic Keras input/output to a numpy array. This error may indicate that you're trying to pass a symbolic value to a NumPy call, which is not supported. Or, you may be trying to pass Keras symbolic inputs/outputs to a TF API that does not register dispatching, preventing Keras from automatically converting the API call to a lambda layer in the Functional Model.

```

**Comment by Alexanderstaehle** [comment]
[train.zip](https://github.com/tensorflow/tensorflow/files/6785913/train.zip)

**Comment by tilakrayal** [comment]
@Alexanderstaehle ,

I ran the code shared and face error, please find the [gist](https://colab.research.google.com/gist/tilakrayal/1df33312c18a68f6c7eab38d6a1be023/untitled50678.ipynb) here and share all dependencies to replicate the issue or share a colab gist with the reported error.Thanks!

**Comment by Alexanderstaehle** [comment]
Hey @tilakrayal :) Thanks for the answer! The error occurs because the sample data was not uploaded :) i tried including it in a gist [here](https://colab.research.google.com/gist/Alexanderstaehle/afca7b85a227e676baa96116a4e07981/untitled50678.ipynb) but you can also find it in the initial description of the error under the bulletpoint "Othee info/logs" or under this link [here.](https://github.com/tensorflow/tensorflow/files/6785899/train.zip) Hope that helps :)

**Comment by Saduf2019** [comment]
@Alexanderstaehle 

Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more refer to:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999

**Comment by TheWindWillNotStop** [comment]
I had the same problem when i use tf==2.4.1 and numpy==1.20,but when i downgrade numpy to 1.19.5,i got 
`ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject`
The answer I found in past issues is to upgrade numpy to 1.20, this is too strange.I'm now stuck in a dead end with the numpy version

**Comment by Saduf2019** [comment]
@TheWindWillNotStop 
Does the issue occur with tf 2.5 as well, can you please confrim.

**Comment by alexCranfield** [comment]
I was also having this issue, using tf 2.5.0 whilst attempting to make a VAE.

I've found a workaround however, removing the initialisation of the custom loss function from the model compile function and instead adding it prior.

So what was:
`vae.compile(optimizer=optimiser, loss = vae_custom_loss)`

is now:

`vae.add_loss(vae_custom_loss(inputs,outputs))
vae.compile(optimizer=optimiser)`

If you require further information please let me know. I'm very new to machine learning so I may have missed something out!

**Comment by Saduf2019** [comment]
Moving this to closed status due to lack of activity.
