### ISSUE TITLE
"RuntimeError: Division by 0Node number 1252 (FLOOR_MOD) failed to invoke." after conversion from TensorFlow to tflite

### ISSUE THREAD

**Issue by floriandotpy** [tensorflow/tensorflow#50689]
### 1. System information

-    OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
-    TensorFlow installation (pip package or built from source): `tb-nightly==2.6.0a20210706` installed via pip

### 2. Code

I am trying to convert a model from Pytorch -> ONNX -> Tensorflow -> tflite. The conversion works, but the results diverge between Tensorflow and tflite.

The original model is a Faster-RCNN with a MobileNet backbone (`fasterrcnn_mobilenet_v3_large_320_fpn` to be exact). I am having a similar, but different issue when converting the same model with a Resnet backbone (see my other issue for that: https://github.com/tensorflow/tensorflow/issues/50676 )

```python
import tensorflow as tf
import numpy as np

# tensorflow inference: works
model_tf = tf.saved_model.load('assets/tfsavedmodel')
sample = np.zeros((1, 3, 256, 256), dtype=np.float32)
model_tf(input=sample)  #works

# tflite inference: fails
interpreter = tf.lite.Interpreter('assets/model.tflite')
print(interpreter.get_input_details()[0]['shape'])  # array([  1,   3, 256, 256], dtype=int32)
model_tflite = interpreter.get_signature_runner()
out_tflite = model_tflite(input=sample)
```

Fails with error:

```
Traceback (most recent call last):
  File "/home/florian/projects/video-analysis-prototype/model-conversion/convert.py", line 375, in <module>
    Converter().verify()
  File "/home/florian/projects/video-analysis-prototype/model-conversion/convert.py", line 371, in verify
    verify_tflite(self.target_dir/self.fname_tflite, x)
  File "/home/florian/projects/video-analysis-prototype/model-conversion/convert.py", line 45, in verify_tflite
    output = signature(input=tf.constant(np.zeros_like(sample)))  # FIXME: get actual sample in
  File "/home/florian/projects/video-analysis-prototype/model-conversion/venv/lib/python3.8/site-packages/tensorflow/lite/python/interpreter.py", line 239, in __call__
    self._interpreter.invoke()
  File "/home/florian/projects/video-analysis-prototype/model-conversion/venv/lib/python3.8/site-packages/tensorflow/lite/python/interpreter.py", line 905, in invoke
    self._interpreter.Invoke()
RuntimeError: Division by 0Node number 1252 (FLOOR_MOD) failed to invoke.
```

Model files mentioned can be found here: https://florianletsch.de/media/assets-tflite.zip (468 MB)

This is how I converted the model (note that this takes >1hr, not sure why)

```
converter = tf.lite.TFLiteConverter.from_saved_model('assets/tfsavedmodel')
converter.experimental_enable_resource_variables = True  # requires tf-nightly or tf-nightly-cpu
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS,
  tf.lite.OpsSet.SELECT_TF_OPS
]

tflite_model = converter.convert()
with open('assets/model.tflite', 'wb') as f:
    f.write(tflite_model)
```

### 3. Failure after conversion

- Conversion works but model can't be loaded for inference, see error message above.

### Environment 

Output of `pip freeze`

```
absl-py==0.13.0
astunparse==1.6.3
cachetools==4.2.2
certifi==2021.5.30
chardet==4.0.0
flatbuffers==1.12
gast==0.4.0
google-auth==1.32.1
google-auth-oauthlib==0.4.4
google-pasta==0.2.0
grpcio==1.38.1
h5py==3.1.0
idna==2.10
keras-nightly==2.6.0.dev2021062500
Keras-Preprocessing==1.1.2
libclang==12.0.0
Markdown==3.3.4
netron==5.0.0
numpy==1.19.2
oauthlib==3.1.1
onnx==1.9.0
onnx-tf==1.8.0
onnxruntime==1.8.0
opt-einsum==3.3.0
Pillow==8.3.1
protobuf==3.17.3
pyasn1==0.4.8
pyasn1-modules==0.2.8
PyYAML==5.4.1
requests==2.25.1
requests-oauthlib==1.3.0
rsa==4.7.2
six==1.15.0
tb-nightly==2.6.0a20210706
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
tensorflow-addons==0.13.0
termcolor==1.1.0
tf-estimator-nightly==2.6.0.dev2021062501
tf-nightly-cpu==2.7.0.dev20210706
torch==1.9.0
torchvision==0.10.0
typeguard==2.12.1
typing-extensions==3.7.4
urllib3==1.26.6
Werkzeug==2.0.1
wrapt==1.12.1
```

**Comment by srjoglekar246** [comment]
@thaink Can you take a look at this?

**Comment by pkgoogle** [comment]
Currently this runs into a different issue with tf-nightly: [gist](https://colab.sandbox.google.com/gist/pkgoogle/15d5e2aecc8e9041ce04fc245bc82edf/50689.ipynb)

```python
2.15.0-dev20230814
[  1   3 256 256]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-2-b10951ef2781>](https://localhost:8080/#) in <cell line: 11>()
      9 print(interpreter.get_input_details()[0]['shape'])  # array([  1,   3, 256, 256], dtype=int32)
     10 model_tflite = interpreter.get_signature_runner()
---> 11 out_tflite = model_tflite(input=sample)

[/usr/local/lib/python3.10/dist-packages/tensorflow/lite/python/interpreter.py](https://localhost:8080/#) in __call__(self, **kwargs)
    247                                           self._subgraph_index)
    248 
--> 249     self._interpreter_wrapper.Invoke(self._subgraph_index)
    250     result = {}
    251     for output_name, output_index in self._outputs:

RuntimeError: tensorflow/lite/kernels/non_max_suppression.cc:108 (max_output_size_value >= 0) was not true.Node number 5 (NON_MAX_SUPPRESSION_V4) failed to prepare.Node number 7 (WHILE) failed to prepare.Node number 9 (WHILE) failed to prepare.Node number 544 (IF) failed to prepare.
```

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
