### ISSUE TITLE
Custom training and and inference functions defined outside k-fold loop cause FailedPreconditionError

### ISSUE THREAD

**Issue by MPKenning** [tensorflow/tensorflow#50691]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5.0
- Python version: 3.9.6
- GCC/Compiler version (if compiling from source): Apple clang version 12.0.0 (clang-1200.0.32.29)

I am not running this code on a GPU on my personal computer, but a colleague has run it on a computer with an NVIDIA card and has confirmed this error.

**Describe the current behavior**
I have implemented k-fold cross-validation for use on a custom Tensorflow model (extending tf.keras.Model). At the start of each loop the model is instantiated, the weights are initialised (with `model.build()`) and so is the Adam optimiser, since it has its own learned variables. The `_train_step` and `_inference_step` functions are called outside the fold while-loop since they are the same for each model and Tensorflow warns that retracing is an expensive process.

The code throws a `FailedPreconditionError`, however, complaining of some variable being missing. It is never the same variable.

The error disappears when I enable eager execution, by which I mean that I comment out the decorator `@tf.function` and use gradient tape.

**Describe the expected behavior**
I expect that this error wouldn't be thrown, and that I wouldn't have to redefine the aforementioned functions each time the loop is called.

**Standalone code to reproduce the issue**
[Working and faulty code.](https://colab.research.google.com/drive/1mUKEOcQqGYX4YC-mrX1WgzWHbLL5JpXL?usp=sharing)

**Other info / logs**
`
python3.9/bin/python3.9 "training_example.py"
2021-07-09 11:25:50.103064: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-07-09 11:25:50.957307: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
fold 0: epoch 1: train_loss: 0.99761 train_prec: 1.00000 train_recall: 0.30856
fold 0: epoch 1: val_loss: 0.98867 val_prec: 1.00000 val_recall: 0.23142
fold 0: epoch 2: train_loss: 0.99167 train_prec: 1.00000 train_recall: 0.13224
fold 0: epoch 2: val_loss: 0.98676 val_prec: 1.00000 val_recall: 0.11571
Traceback (most recent call last):
  File "training_example.py", line 118, in <module>
    for batch_features, batch_labels in training_set: _train_step(batch_features,
  File "python3.9/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "python3.9/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 917, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "python3.9/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 3023, in __call__
    return graph_function._call_flat(
  File "python3.9/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 1960, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "python3.9/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 591, in call
    outputs = execute.execute(
  File "python3.9/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.FailedPreconditionError:  Could not find variable _AnonymousVar13. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status=Not found: Resource localhost/_AnonymousVar13/N10tensorflow3VarE does not exist.
	 [[node test_model/dense_2/Tensordot/ReadVariableOp (defined at training_example.py:32) ]] [Op:__inference__train_step_1082]

Function call stack:
_train_step
`

**Comment by tilakrayal** [comment]
@Saduf2019 ,
I was able to to reproduce the issue in tf [v2.4](https://colab.research.google.com/gist/tilakrayal/f288a30344ae20134e81bc3bb5aefed8/2-4broken_training_example.ipynb) and [v2.5](https://colab.research.google.com/gist/tilakrayal/4db737ebdfb6e35835ebc811a3097076/2-5broken_training_example.ipynb).Please find the gist here.

**Comment by chunduriv** [comment]
@MPKenning,

Sorry for the late response. This issue was fixed now. Please find the [gist](https://colab.sandbox.google.com/gist/chunduriv/bde4327c309502f6c9ccc999e0e015c9/broken_training_example.ipynb) for reference. Thank you.
