### ISSUE TITLE
Error when applying tf.map_fn on symbolic tensors

### ISSUE THREAD

**Issue by DenisUllmann** [tensorflow/tensorflow#50694]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): YES
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): conda
- TensorFlow version (use command below): tensorflow-gpu 2.3.0 (from conda install - he13fc11_0)
- Python version: 3.8.10
- Bazel version (if compiling from source): No
- GCC/Compiler version (if compiling from source): No
- CUDA/cuDNN version: cudatoolkit 10.1.243 (from conda install), cudnn 7.6.5 (from conda install)
- GPU model and memory: NVIDIA GeForce GT 730M (1GB)

**Current behavior**
Error when applying tf.map_fn on symbolic tensors

**Describe the expected behavior**
No error when applying tf.map_fn on symbolic tensors

**Standalone code to reproduce the issue**
This is a toy example, of course I would like to perform a specific per-row function:

```
import tensorflow as tf
input = tf.keras.layers.Input(shape=[1,1,3], 
                              batch_size=4,
                              dtype=tf.double)
result = tf.map_fn(lambda x: x,
                   input)
```

I would like the function to be applied on each of the 4 elems of the batch dimension.

**Traceback:**
```
Traceback (most recent call last):

  File "<ipython-input-119-118c58833a26>", line 4, in <module>
    result = tf.map_fn(lambda x: x,

  File "C:\ProgramData\Anaconda3\envs\py3tf2_3\lib\site-packages\tensorflow\python\util\deprecation.py", line 574, in new_func
    return func(*args, **kwargs)

  File "C:\ProgramData\Anaconda3\envs\py3tf2_3\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)

  File "C:\ProgramData\Anaconda3\envs\py3tf2_3\lib\site-packages\tensorflow\python\ops\map_fn.py", line 633, in map_fn_v2
    return map_fn(

  File "C:\ProgramData\Anaconda3\envs\py3tf2_3\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)

  File "C:\ProgramData\Anaconda3\envs\py3tf2_3\lib\site-packages\tensorflow\python\ops\map_fn.py", line 440, in map_fn
    elems_batchable_ta = [

  File "C:\ProgramData\Anaconda3\envs\py3tf2_3\lib\site-packages\tensorflow\python\ops\map_fn.py", line 441, in <listcomp>
    tensor_array_ops.TensorArray(

  File "C:\ProgramData\Anaconda3\envs\py3tf2_3\lib\site-packages\tensorflow\python\ops\tensor_array_ops.py", line 1071, in __init__
    self._implementation = implementation(

  File "C:\ProgramData\Anaconda3\envs\py3tf2_3\lib\site-packages\tensorflow\python\ops\tensor_array_ops.py", line 718, in __init__
    self._tensor_array = [None for _ in range(size)]

TypeError: 'Tensor' object cannot be interpreted as an integer
```

**Comment by DenisUllmann** [comment]
Sorry, I could resolve in this way:

```
import tensorflow as tf
input = tf.keras.layers.Input(shape=[1,1,3], 
                              batch_size=4,
                              dtype=tf.double)
fcn = lambda x: x
result = tf.keras.layers.Lambda(fcn)(input)
```

I closed the issue.
