### ISSUE TITLE
KerasTensors do not support tf.custom_gradient()

### ISSUE THREAD

**Issue by loic-ehrhardt** [tensorflow/tensorflow#50741]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Red Hat Enterprise Linux release 8.2 (Ootpa)
- TensorFlow installed from (source or binary): binary (pip)
- TensorFlow version: v1.12.1-59375-ga5317d67e6c 2.6.0-rc0
- Python version: 3.6.8

**Describe the current behavior**
`tf.KerasTensor` cannot be used with `tf.custom_gradient()`. Trying to do so results in a `TypeError`.

**Describe the expected behavior**
This should be possible and return another `tf.KerasTensor`.

**Standalone code to reproduce the issue**
```python3
import tensorflow as tf

@tf.custom_gradient
def identity(x):
    def grad_fn(grad_y):
        return grad_y
    return (x, grad_fn)

keras_tensor = tf.keras.layers.Input(shape=(2,))
print(keras_tensor)
print(identity(keras_tensor))
```

which gives:

```
KerasTensor(type_spec=TensorSpec(shape=(None, 2), dtype=tf.float32, name='input_1'), name='input_1', description="created by layer 'input_1'")
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    print(identity(keras_tensor))
  File "/home/loic/venv/tf_2.6.0rc0/lib64/python3.6/site-packages/tensorflow/python/ops/custom_gradient.py", line 309, in __call__
    return self._d(self._f, a, k)
  File "/home/loic/venv/tf_2.6.0rc0/lib64/python3.6/site-packages/tensorflow/python/ops/custom_gradient.py", line 263, in decorated
    return _eager_mode_decorator(wrapped, args, kwargs)
  File "/home/loic/venv/tf_2.6.0rc0/lib64/python3.6/site-packages/tensorflow/python/ops/custom_gradient.py", line 510, in _eager_mode_decorator
    flat_result = [gen_array_ops.identity(x) for x in flat_result]
  File "/home/loic/venv/tf_2.6.0rc0/lib64/python3.6/site-packages/tensorflow/python/ops/custom_gradient.py", line 510, in <listcomp>
    flat_result = [gen_array_ops.identity(x) for x in flat_result]
  File "/home/loic/venv/tf_2.6.0rc0/lib64/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3941, in identity
    input, name=name, ctx=_ctx)
  File "/home/loic/venv/tf_2.6.0rc0/lib64/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3960, in identity_eager_fallback
    _attr_T, (input,) = _execute.args_to_matching_eager([input], ctx, [])
  File "/home/loic/venv/tf_2.6.0rc0/lib64/python3.6/site-packages/tensorflow/python/eager/execute.py", line 274, in args_to_matching_eager
    t, dtype, preferred_dtype=default_dtype, ctx=ctx)
  File "/home/loic/venv/tf_2.6.0rc0/lib64/python3.6/site-packages/tensorflow/python/profiler/trace.py", line 163, in wrapped
    return func(*args, **kwargs)
  File "/home/loic/venv/tf_2.6.0rc0/lib64/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1566, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/loic/venv/tf_2.6.0rc0/lib64/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 346, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/loic/venv/tf_2.6.0rc0/lib64/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 272, in constant
    allow_broadcast=True)
  File "/home/loic/venv/tf_2.6.0rc0/lib64/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 283, in _constant_impl
    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
  File "/home/loic/venv/tf_2.6.0rc0/lib64/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 308, in _constant_eager_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "/home/loic/venv/tf_2.6.0rc0/lib64/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 106, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
  File "/home/loic/venv/tf_2.6.0rc0/lib64/python3.6/site-packages/keras/engine/keras_tensor.py", line 245, in __array__
    'Cannot convert a symbolic Keras input/output to a numpy array. '
TypeError: Cannot convert a symbolic Keras input/output to a numpy array. This error may indicate that you're trying to pass a symbolic value to a NumPy call, which is not supported. Or, you may be trying to pass Keras symbolic inputs/outputs to a TF API that does not register dispatching, preventing Keras from automatically converting the API call to a lambda layer in the Functional Model.
```

**Other info / logs**

This works with Eager tensors.

```python3
eager_tensor = tf.constant([4.0])
print(identity(eager_tensor))
```

gives

```
tf.Tensor([4.], shape=(1,), dtype=float32)
```

**Comment by loic-ehrhardt** [comment]
Hi @saikumarchalla, I think you placed the wrong tag. This issue refers to the *new* tensorflow version: 2.6.0-rc0

> TensorFlow version: v1.12.1-59375-ga5317d67e6c __2.6.0-rc0__

I actually used the suggested command to print the versions:
```python3
import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)                                                                                       
v1.12.1-59375-ga5317d67e6c 2.6.0-rc0
```

**Comment by saikumarchalla** [comment]
Was able to reproduce the issueon colab. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/7734534ff4121be31884dea28fd53a7f/untitled111.ipynb). Thanks!

**Comment by tomerk** [comment]
This is unfortunately unfixable in the near future as it would require more significant refactoring of the dispatching mechanism TF operators use. Similarly, gradients on KerasTensors themselves are currently unsupported.

I believe it should work if you put this inside a custom keras layer.
Will close for now, though perhaps it will be revisited in the future.

**Comment by hosford42** [comment]
I have a custom keras layer that uses a custom gradient function. It worked fine for a previous project, but now I'm trying to reuse the layer and I'm getting this error. The only potentially meaningful difference I can see is that I have multiple undefined batch dims in the model I'm building now. (I'm using the layer on the results of a convolution.) Could that impact the dispatching somehow?
