### ISSUE TITLE
Dataset.as_numpy_iterator() throws error inside tensorflow.numpy_function

### ISSUE THREAD

**Issue by kurudinesh** [tensorflow/tensorflow#50740]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 and Google Colab 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5.0
- Python version: 3.8.10
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: CPU 8GB

**Describe the expected behavior** tensorflow.data.Dataset.as_numpy_iterator should return iterator when called from inside tensorflow.py_func used inside Dataset.interleave's map_function.

**Describe the current behavior** Throwing error 'Tensorflow.python.framework.errors_impl.DataLossError: inflate() failed with error -3: incorrect header check [Op:IteratorGetNext]'

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing): NA

**Standalone code to reproduce the issue**
````
import tensorflow as tf
path = "saved_data_2"

# Save a dataset
dataset = tf.data.Dataset.range(10)
tf.data.experimental.save(dataset, path)
new_dataset = tf.data.experimental.load(path)
for elem in new_dataset:
  print(elem)


#flat_map code error below
filenames = [path]
dataset = tf.data.Dataset.from_tensor_slices(filenames)


def parse_fn(filename):
    part_ds = tf.data.experimental.load(bytes.decode(filename),compression='GZIP')
    ar = []
    for i in part_ds.as_numpy_iterator():
        ar.append(i)
    return ar

dataset = dataset.interleave(lambda x:tf.data.Dataset.from_tensor_slices(
            tf.numpy_function(parse_fn,[x],[tf.int64])),
            cycle_length=4, block_length=16)

for item in dataset.as_numpy_iterator():
    print(item)
````

**Other info / logs** 

````
C:\Users\kurud\Anaconda3\envs\DrowsyDetectCNNmodel\python.exe C:/Users/kurud/Documents/ineaurondeeplearn/internship/DrowsyDetectCNNmodel/DataPipelineIssues2.py
2021-07-12 21:14:47.985114: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-07-12 21:14:47.985404: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-07-12 21:14:50.932059: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2021-07-12 21:14:50.932192: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-07-12 21:14:50.935815: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: LAPTOP-76MAP85S
2021-07-12 21:14:50.936005: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: LAPTOP-76MAP85S
2021-07-12 21:14:50.936609: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-07-12 21:14:50.967628: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-07-12 21:14:51.013124: E tensorflow/core/framework/dataset.cc:825] Unimplemented: Cannot merge options for dataset of type LoadDataset, because the dataset does not implement `InputDatasets`.
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
2021-07-12 21:14:51.017583: E tensorflow/core/framework/dataset.cc:825] Unimplemented: Cannot merge options for dataset of type LoadDataset, because the dataset does not implement `InputDatasets`.
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)
2021-07-12 21:14:51.102540: E tensorflow/core/framework/dataset.cc:825] Unimplemented: Cannot merge options for dataset of type LoadDataset, because the dataset does not implement `InputDatasets`.
2021-07-12 21:14:51.109462: E tensorflow/core/framework/dataset.cc:825] Unimplemented: Cannot merge options for dataset of type LoadDataset, because the dataset does not implement `InputDatasets`.
2021-07-12 21:14:51.133405: W tensorflow/core/framework/op_kernel.cc:1755] Unknown: DataLossError: inflate() failed with error -3: incorrect header check [Op:IteratorGetNext]
Traceback (most recent call last):

  File "C:\Users\kurud\Anaconda3\envs\DrowsyDetectCNNmodel\lib\site-packages\tensorflow\python\ops\script_ops.py", line 249, in __call__
    ret = func(*args)

  File "C:\Users\kurud\Anaconda3\envs\DrowsyDetectCNNmodel\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 645, in wrapper
    return func(*args, **kwargs)

  File "C:/Users/kurud/Documents/ineaurondeeplearn/internship/DrowsyDetectCNNmodel/DataPipelineIssues2.py", line 20, in parse_fn
    for i in part_ds.as_numpy_iterator():

  File "C:\Users\kurud\Anaconda3\envs\DrowsyDetectCNNmodel\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 4194, in __next__
    return nest.map_structure(to_numpy, next(self._iterator))

  File "C:\Users\kurud\Anaconda3\envs\DrowsyDetectCNNmodel\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 761, in __next__
    return self._next_internal()

  File "C:\Users\kurud\Anaconda3\envs\DrowsyDetectCNNmodel\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 744, in _next_internal
    ret = gen_dataset_ops.iterator_get_next(

  File "C:\Users\kurud\Anaconda3\envs\DrowsyDetectCNNmodel\lib\site-packages\tensorflow\python\ops\gen_dataset_ops.py", line 2727, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)

  File "C:\Users\kurud\Anaconda3\envs\DrowsyDetectCNNmodel\lib\site-packages\tensorflow\python\framework\ops.py", line 6897, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)

  File "<string>", line 3, in raise_from

tensorflow.python.framework.errors_impl.DataLossError: inflate() failed with error -3: incorrect header check [Op:IteratorGetNext]


Traceback (most recent call last):
  File "C:/Users/kurud/Documents/ineaurondeeplearn/internship/DrowsyDetectCNNmodel/DataPipelineIssues2.py", line 28, in <module>
    for item in dataset.as_numpy_iterator():
  File "C:\Users\kurud\Anaconda3\envs\DrowsyDetectCNNmodel\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 4194, in __next__
    return nest.map_structure(to_numpy, next(self._iterator))
  File "C:\Users\kurud\Anaconda3\envs\DrowsyDetectCNNmodel\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 761, in __next__
    return self._next_internal()
  File "C:\Users\kurud\Anaconda3\envs\DrowsyDetectCNNmodel\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 744, in _next_internal
    ret = gen_dataset_ops.iterator_get_next(
  File "C:\Users\kurud\Anaconda3\envs\DrowsyDetectCNNmodel\lib\site-packages\tensorflow\python\ops\gen_dataset_ops.py", line 2727, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "C:\Users\kurud\Anaconda3\envs\DrowsyDetectCNNmodel\lib\site-packages\tensorflow\python\framework\ops.py", line 6897, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnknownError: DataLossError: inflate() failed with error -3: incorrect header check [Op:IteratorGetNext]
Traceback (most recent call last):

  File "C:\Users\kurud\Anaconda3\envs\DrowsyDetectCNNmodel\lib\site-packages\tensorflow\python\ops\script_ops.py", line 249, in __call__
    ret = func(*args)

  File "C:\Users\kurud\Anaconda3\envs\DrowsyDetectCNNmodel\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 645, in wrapper
    return func(*args, **kwargs)

  File "C:/Users/kurud/Documents/ineaurondeeplearn/internship/DrowsyDetectCNNmodel/DataPipelineIssues2.py", line 20, in parse_fn
    for i in part_ds.as_numpy_iterator():

  File "C:\Users\kurud\Anaconda3\envs\DrowsyDetectCNNmodel\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 4194, in __next__
    return nest.map_structure(to_numpy, next(self._iterator))

  File "C:\Users\kurud\Anaconda3\envs\DrowsyDetectCNNmodel\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 761, in __next__
    return self._next_internal()

  File "C:\Users\kurud\Anaconda3\envs\DrowsyDetectCNNmodel\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 744, in _next_internal
    ret = gen_dataset_ops.iterator_get_next(

  File "C:\Users\kurud\Anaconda3\envs\DrowsyDetectCNNmodel\lib\site-packages\tensorflow\python\ops\gen_dataset_ops.py", line 2727, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)

  File "C:\Users\kurud\Anaconda3\envs\DrowsyDetectCNNmodel\lib\site-packages\tensorflow\python\framework\ops.py", line 6897, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)

  File "<string>", line 3, in raise_from

tensorflow.python.framework.errors_impl.DataLossError: inflate() failed with error -3: incorrect header check [Op:IteratorGetNext]


	 [[{{node PyFunc}}]] [Op:IteratorGetNext]

Process finished with exit code 1

````

**Comment by UsharaniPagadala** [comment]
@kurudinesh 

Could you please refer these [link1](https://www.tensorflow.org/api_docs/python/tf/data/Dataset) and [link2](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/data/ops/dataset_ops.py) and let us know if  it helps.Thanks

**Comment by kurudinesh** [comment]
@UsharaniPagadala  

I am trying to convert dataset loaded using tf.data.experimental.load method to a numpy array in Eager mode and in the documentation link it mentioned 'as_numpy_iterator' works in eager mode.

**Comment by UsharaniPagadala** [comment]
@rmothukuru 

I was able to replicate the issue in tf 2.5 and tf-nightly.Please find  the [gist](https://colab.research.google.com/gist/UsharaniPagadala/08f1f940d0637fe3b55a942daa01865a/-50740.ipynb).Thanks

**Comment by rmothukuru** [comment]
@kurudinesh,
While we look into the issue, I feel that you have swapped the content for **Current Behavior** and the **Expected Behavior**. If it is so, please correct it in the issue, order to avoid confusion. Thanks!

**Comment by aaudiber** [comment]
@kurudinesh There were two issues with the code:

1) The code was being saved as uncompressed data, but loaded as compressed data. The `compression` argument needs to match between `save` and `load`.
2) tf.numpy_function must return a numpy array, so the list you are returning must be converted to a list, e.g. with `np.asarray(ar)`

With these changes the below code runs successfully:

```python
import tensorflow as tf
import numpy as np
path = "saved_data_2"

# Save a dataset
dataset = tf.data.Dataset.range(10)
tf.data.experimental.save(dataset, path, compression="GZIP")
filenames = [path]
dataset = tf.data.Dataset.from_tensor_slices(filenames)

def parse_fn(filename):
    part_ds = tf.data.experimental.load(bytes.decode(filename), compression="GZIP")
    ar = []
    for i in part_ds.as_numpy_iterator():
        ar.append(i)
    return np.asarray(ar)

dataset = dataset.interleave(lambda x:tf.data.Dataset.from_tensor_slices(
            tf.numpy_function(parse_fn,[x],[tf.int64])),
            cycle_length=4, block_length=16)

list(dataset)
```

**Comment by kurudinesh** [comment]
@aaudiber Thank you for your corrections. Small suggestion please change `load` method to threw `FileNotFoundError` when it could not find dataset file in gzip file format.

**Comment by kurudinesh** [comment]
> @kurudinesh There were two issues with the code:
> 
> 1. The code was being saved as uncompressed data, but loaded as compressed data. The `compression` argument needs to match between `save` and `load`.
> 2. tf.numpy_function must return a numpy array, so the list you are returning must be converted to a list, e.g. with `np.asarray(ar)`
> 
> With these changes the below code runs successfully:
> 
> ```python
> import tensorflow as tf
> import numpy as np
> path = "saved_data_2"
> 
> # Save a dataset
> dataset = tf.data.Dataset.range(10)
> tf.data.experimental.save(dataset, path, compression="GZIP")
> filenames = [path]
> dataset = tf.data.Dataset.from_tensor_slices(filenames)
> 
> def parse_fn(filename):
>     part_ds = tf.data.experimental.load(bytes.decode(filename), compression="GZIP")
>     ar = []
>     for i in part_ds.as_numpy_iterator():
>         ar.append(i)
>     return np.asarray(ar)
> 
> dataset = dataset.interleave(lambda x:tf.data.Dataset.from_tensor_slices(
>             tf.numpy_function(parse_fn,[x],[tf.int64])),
>             cycle_length=4, block_length=16)
> 
> list(dataset)
> ```

I got single element of size (1,10) as output. I was expecting dataset to be of shape (10,1).

**Comment by aaudiber** [comment]
@kurudinesh That is happening because the numpy_function's `Tout` is set to `[tf.int64]` instead of `tf.int64`. As a result, the output of `parse_fn` being wrapped in an extra dimension. Removing the list around the `tf.int64` should give the expected (10, 1) shape

**Comment by kurudinesh** [comment]
> @kurudinesh That is happening because the numpy_function's `Tout` is set to `[tf.int64]` instead of `tf.int64`. As a result, the output of `parse_fn` being wrapped in an extra dimension. Removing the list around the `tf.int64` should give the expected (10, 1) shape

@aaudiber 
Thank you. 

I am still unclear about `Tout – A list or tuple of tensorflow data types or a single tensorflow data type if there is only one, indicating what `func` returns.`  Did they mean list or tuple of single tensorflow data type or can we mix it like [tf.int32,tf.double]?

In the below code I am trying to return data array of size `[432,3]`, type `numpy.float64` along with its label(`numpy.int32`) from numpy_function. Tried two approaches using parse_fn and parse_fn2.

Inside `parse_fn2`, I tried to return a `numpy.ndarray` of `tuples(list (shape =[432,3] ), int32)`  and could not find corresponding tensorflow datatype for numpy object dtype.

In '`parse_fn`' method I tried to return data array and label array separately and got errors.

Currently, I am using two numpy arrays inside from_tensorflow_slices which return list of data, labels.

#50594  I tried this before and could not get help.

```
import tensorflow as tf
import numpy as np
path = "saved_data_2"



# Save a dataset
ar = np.random.randn(10,482,3)
dataset = tf.data.Dataset.from_tensor_slices(ar)
tf.data.experimental.save(dataset, path, compression="GZIP")

#creating dataset with labels
filenames = [path]
dataset = tf.data.Dataset.from_tensor_slices(filenames)

def parse_fn(filename):
    part_ds = tf.data.experimental.load(bytes.decode(filename), compression="GZIP")
    ar = []
    label=[]
    for i in part_ds.as_numpy_iterator():
        ar.append(i)
        label.append(1)
    # print(ar[0])
    return np.asarray(ar),label

def parse_fn2(filename):
    part_ds = tf.data.experimental.load(bytes.decode(filename), compression="GZIP")
    ar = []
    # label=[]
    for i in part_ds.as_numpy_iterator():
        ar.append((i,1))
        # label.append(1)
    # print(ar[0])
    return np.asarray(ar)


dataset = dataset.interleave(lambda x:tf.data.Dataset.from_tensor_slices((
            tf.numpy_function(parse_fn,[x],[tf.double,tf.int64]))),
            cycle_length=4).cache()

for i in dataset.take(3).take(1).as_numpy_iterator():
    print(i[0].shape,i[1].shape)
    print(i.shape)#expeting element with size 1 but getting i with shape (1,10)
    # break;

print(tf.data.experimental.cardinality(dataset))


# tf.keras.Sequential
```
