### ISSUE TITLE
apply_gradients() with Adam Optimizer gives error

### ISSUE THREAD

**Issue by arpitjjw** [tensorflow/tensorflow#50769]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution: maOS 11.4
- TensorFlow version: 2.5.0
- Python version: 3.9.6
- GPU model and memory: Apple M1 

**Describe the current behavior**
SGD and Adam gives error when using **apply_gradients()**, please see output and source code below 
When adam is used in **model.fit()** it works normally
- Do you want to contribute a PR? (yes/no): no

**Other info / logs** 
Installed TensorFlow after following instructions from [Getting Started with tensorflow-metal PluggableDevice](https://developer.apple.com/metal/tensorflow-plugin/)

Source code for training: 
```
'''---- Training -----'''
model=tf.keras.Sequential() # model has 1 hidden layer
model.add(tf.keras.layers.Dense(20,input_shape=(dimVectors,),activation='relu'))
model.add(tf.keras.layers.Dense(5,activation='softmax')) # 5 is ouput shape
optimizer=tf.keras.optimizers.Adam(
    learning_rate=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-07, amsgrad=False,
    name='Adam'
)
epochs=10
# without padding
wordVectors=tf.Variable(tf.convert_to_tensor(wordVectors))
trainLabels=tf.keras.utils.to_categorical(trainLabels,5)
for epoch in range(epochs):
    sent_count=0
    print("---Epoch no:",epoch,"----")
    #one sentence in each batch
    for sent in train_Sentences:
        if((sent_count%10)==0):
            print("Optimizing sentence number",sent_count+1)
        sent_count+=1
        len_sent=len(sent)
        one_hot=np.zeros((len_sent,total_words))
        label=(trainLabels[sent_count-1]).reshape(-1,1)
        label=tf.convert_to_tensor(label)
        for i,word in enumerate(sent):
            index=token_dict[word]
            one_hot[i,index]=1
        one_hot=tf.convert_to_tensor(one_hot)
        with tf.GradientTape() as tape:
            #tape.watch(wordVectors)
            feature=tf.matmul(one_hot,wordVectors)
            feature_sum=tf.math.reduce_sum(feature,axis=0,keepdims=True)
            y_pred=model(feature_sum)
            loss=tf.losses.MeanSquaredError()(y_pred,label)
        gradients=tape.gradient(loss,[wordVectors]+model.trainable_variables)
        if(((sent_count-1)%10)==0):
                print("Loss: ",loss)
        '''wordVectors.assign(wordVectors-learning_rate*gradients[0])
        (model.trainable_variables[0]).assign(model.trainable_variables[0]-learning_rate*gradients[1])
        (model.trainable_variables[1]).assign(model.trainable_variables[1]-learning_rate*gradients[2])
        (model.trainable_variables[2]).assign(model.trainable_variables[2]-learning_rate*gradients[3])
        (model.trainable_variables[3]).assign(model.trainable_variables[3]-learning_rate*gradients[4])'''
        optimizer.apply_gradients(zip(gradients,[wordVectors]+model.trainable_variables))
    
```
Traceback :
```
Traceback (most recent call last):
  File "/Users/arpitjjw/Desktop/Training Program/Module 2/Sentiment_day1/model-tf.py", line 152, in <module>
    optimizer.apply_gradients(zip(gradients,[wordVectors]+model.trainable_variables))
  File "/Users/arpitjjw/miniforge3/envs/tf-m1/lib/python3.9/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py", line 667, in apply_gradients
    return self._distributed_apply(strategy, grads_and_vars, name,
  File "/Users/arpitjjw/miniforge3/envs/tf-m1/lib/python3.9/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py", line 714, in _distributed_apply
    update_op = distribution.extended.update(
  File "/Users/arpitjjw/miniforge3/envs/tf-m1/lib/python3.9/site-packages/tensorflow/python/distribute/distribute_lib.py", line 2576, in update
    return self._update(var, fn, args, kwargs, group)
  File "/Users/arpitjjw/miniforge3/envs/tf-m1/lib/python3.9/site-packages/tensorflow/python/distribute/distribute_lib.py", line 3622, in _update
    return self._update_non_slot(var, fn, (var,) + tuple(args), kwargs, group)
  File "/Users/arpitjjw/miniforge3/envs/tf-m1/lib/python3.9/site-packages/tensorflow/python/distribute/distribute_lib.py", line 3628, in _update_non_slot
    result = fn(*args, **kwargs)
  File "/Users/arpitjjw/miniforge3/envs/tf-m1/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 597, in wrapper
    return func(*args, **kwargs)
  File "/Users/arpitjjw/miniforge3/envs/tf-m1/lib/python3.9/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py", line 697, in apply_grad_to_update_var
    update_op = self._resource_apply_dense(grad, var, **apply_kwargs)
  File "/Users/arpitjjw/miniforge3/envs/tf-m1/lib/python3.9/site-packages/tensorflow/python/keras/optimizer_v2/adam.py", line 172, in _resource_apply_dense
    return gen_training_ops.ResourceApplyAdam(
  File "/Users/arpitjjw/miniforge3/envs/tf-m1/lib/python3.9/site-packages/tensorflow/python/util/tf_export.py", line 404, in wrapper
    return f(**kwargs)
  File "/Users/arpitjjw/miniforge3/envs/tf-m1/lib/python3.9/site-packages/tensorflow/python/ops/gen_training_ops.py", line 1427, in resource_apply_adam
    _ops.raise_from_not_ok_status(e, name)
  File "/Users/arpitjjw/miniforge3/envs/tf-m1/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 6897, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.NotFoundError: No registered 'ResourceApplyAdam' OpKernel for 'GPU' devices compatible with node {{node ResourceApplyAdam}}
	 (OpKernel was found, but attributes didn't match) Requested Attributes: T=DT_DOUBLE, use_locking=true, use_nesterov=false
	.  Registered:  device='GPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_COMPLEX128]
 [Op:ResourceApplyAdam]
```

**Comment by saikumarchalla** [comment]
@arpitjjw  It looks like your Issue relates to the Keras component. Please submit it to the [github.com/keras-team/keras](github.com/keras-team/keras) repository instead. As ([previously announced](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999/)), all future development of Keras is expected to happen in the [github.com/keras-team/keras](github.com/keras-team/keras) repository. If your issue lies with the TF-Core area please comment back with your explanation and we can look into it further. Thanks!

**Comment by saikumarchalla** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
