### ISSUE TITLE
Installed successfully the TensorFlow-gpu==1.15 but got error tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot place the graph because a reference or resource edge connects colocation groups with incompatible resource devices: /device:CPU:0 vs /device:GPU:0. The edge src node is input_producer , and the dst node is ReaderReadV2

### ISSUE THREAD

**Issue by jocelynbaduria** [tensorflow/tensorflow#50795]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS BigSur
- TensorFlow installed from (source or binary): source
- TensorFlow version: tensorflow 2.5.0
- Python version: 3.9.6
- Installed using virtualenv? pip? conda?: pip3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: TensorFlow-gpu==1.15 

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Environment and Configuration needed to run the evaluation code.
Python 3.6.4 --> version 3.9.6
Tensorflow-gpu 1.8.0 (pip install tensorflow-gpu==1.8.0) --> not available instead installed the TensorFlow-gpu==1.15.
Tensorpack (pip install tensorpack) version - 

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Executed code :
_user@Olens-MacBook-Air SELFIE % python3 -m pip3 install tensorflow-gpu==1.15
/Library/Frameworks/Python.framework/Versions/3.9/bin/python3: No module named pip3
user@Olens-MacBook-Air SELFIE % python3 -m pip3 install tensorflow-gpu==1.8.0
/Library/Frameworks/Python.framework/Versions/3.9/bin/python3: No module named pip3
user@Olens-MacBook-Air SELFIE % python3 main.py  0  CIFAR-10  DenseNet-10-12  SELFIE  pair  0.05  /Users/user/Desktop/Summer\ 2021/log_
['main.py', '0', 'CIFAR-10', 'DenseNet-10-12', 'SELFIE', 'pair', '0.05', '/Users/olenbaduria/Desktop/Summer 2021/log']
------------------------------------------------------------------------
This code trains Densnet(L={10,25,40}, k=12) using SELFIE in tensorflow-gpu environment.

Description -----------------------------------------------------------
Please download datasets from our github before running command.
For SELFIE, the hyperparameter was set to be uncertainty threshold = 0.05 and  history length=15.
For Training, we follow the same configuration in our paper
For Training, training_epoch = 100, batch = 128, initial_learning rate = 0.1 (decayed 50% and 75% of total number of epochs), use momentum of 0.9, warm_up=25, restart=2, ...
You can easily change the value in main.py
Dataset exists in  /Users/user/Desktop/Summer 2021/SELFIE/SELFIE/dataset/CIFAR-10
2021-07-15 17:50:10.016830: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Now read following files.
['/Users/user/Desktop/Summer 2021/SELFIE/SELFIE/dataset/CIFAR-10/data_batch_1.bin', '/Users/user/Desktop/Summer 2021/SELFIE/SELFIE/dataset/CIFAR-10/data_batch_2.bin', '/Users/user/Desktop/Summer 2021/SELFIE/SELFIE/dataset/CIFAR-10/data_batch_3.bin', '/Users/user/Desktop/Summer 2021/SELFIE/SELFIE/dataset/CIFAR-10/data_batch_4.bin', '/Users/user/Desktop/Summer 2021/SELFIE/SELFIE/dataset/CIFAR-10/data_batch_5.bin']
Filling queue with 20000 data before starting to train. This will take a few minutes.
Now read following files.
['/Users/user/Desktop/Summer 2021/SELFIE/SELFIE/dataset/CIFAR-10/test_batch.bin']
Filling queue with 4000 data before starting to train. This will take a few minutes.
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer_v1.py:1692: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
[0715 17:50:10 @registry.py:90] 'DenseNet/conv0': [?, 32, 32, 3] --> [?, 32, 32, 16]
[0715 17:50:10 @registry.py:90] 'DenseNet/block1/dense_layer.0/conv1': [?, 32, 32, 16] --> [?, 32, 32, 12]
[0715 17:50:10 @registry.py:90] 'DenseNet/block1/dense_layer.1/conv1': [?, 32, 32, 28] --> [?, 32, 32, 12]
[0715 17:50:10 @registry.py:90] 'DenseNet/block1/transition1/conv1': [?, 32, 32, 40] --> [?, 32, 32, 40]
[0715 17:50:10 @registry.py:90] 'DenseNet/block1/transition1/pool': [?, 32, 32, 40] --> [?, 16, 16, 40]
[0715 17:50:10 @registry.py:90] 'DenseNet/block2/dense_layer.0/conv1': [?, 16, 16, 40] --> [?, 16, 16, 12]
[0715 17:50:10 @registry.py:90] 'DenseNet/block2/dense_layer.1/conv1': [?, 16, 16, 52] --> [?, 16, 16, 12]
[0715 17:50:10 @registry.py:90] 'DenseNet/block2/transition2/conv1': [?, 16, 16, 64] --> [?, 16, 16, 64]
[0715 17:50:10 @registry.py:90] 'DenseNet/block2/transition2/pool': [?, 16, 16, 64] --> [?, 8, 8, 64]
[0715 17:50:10 @registry.py:90] 'DenseNet/block3/dense_layer.0/conv1': [?, 8, 8, 64] --> [?, 8, 8, 12]
[0715 17:50:10 @registry.py:90] 'DenseNet/block3/dense_layer.1/conv1': [?, 8, 8, 76] --> [?, 8, 8, 12]
[0715 17:50:10 @registry.py:90] 'DenseNet/gap': [?, 8, 8, 88] --> [?, 88]
[0715 17:50:10 @registry.py:90] 'DenseNet/linear': [?, 88] --> [?, 10]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1375, in _do_call
    return fn(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1358, in _run_fn
    self._extend_graph()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1398, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot place the graph because a reference or resource edge connects colocation groups with incompatible resource devices: /device:CPU:0 vs /device:GPU:0. The edge src node is input_producer , and the dst node is ReaderReadV2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/Desktop/Summer 2021/SELFIE/SELFIE/main.py", line 108, in <module>
    main()
  File "/Users/user/Desktop/Summer 2021/SELFIE/SELFIE/main.py", line 104, in main
    selfie(gpu_id, input_reader, model_name, total_epochs, batch_size, lr_boundaries, lr_values, optimizer, noise_rate, noise_type, warm_up, threshold, queue_size, restart=restart, log_dir=log_dir)
  File "/Users/user/Desktop/Summer 2021/SELFIE/SELFIE/algorithm/selfie.py", line 167, in selfie
    train_batch_patcher.bulk_load_in_memory(sess, train_ids, train_images, train_labels)
  File "/Users/user/Desktop/Summer 2021/SELFIE/SELFIE/reader/batch_patcher.py", line 40, in bulk_load_in_memory
    mini_ids, mini_images, mini_labels = sess.run([ids, images, labels])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 967, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1190, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1368, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: **_Cannot place the graph because a reference or resource edge connects colocation groups with incompatible resource devices: /device:CPU:0 vs /device:GPU:0. The edge src node is input_producer , and the dst node is ReaderReadV2_**
user@Olens-MacBook-Air SELFIE % python3 --version
Python 3.9.6

**Comment by Saduf2019** [comment]
@jocelynbaduria 
Please refer to [this issue](https://github.com/tensorflow/tensorflow/issues/30748) with similar error, and let us know.

**Comment by jocelynbaduria** [comment]
@Saduf2019 I upgraded the version to tensorflow==2.5.0 still got an error.

see error below, running the code main.py in Colab.

2021-07-18 18:22:40.196041: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
['/content/drive/Shareddrives/Eranti-Vijay-Su21-2/code/Updated_SELFIE/SELFIE/SELFIE/main.py', '0', 'CIFAR-100', 'DenseNet-25-12', 'SELFIE', 'pair', '0.4', 'log/CIFAR-100/SELFIE']
------------------------------------------------------------------------
This code trains Densnet(L={10,25,40}, k=12) using SELFIE in tensorflow-gpu environment.

Description -----------------------------------------------------------
Please download datasets from our github before running command.
For SELFIE, the hyperparameter was set to be uncertainty threshold = 0.05 and  history length=15.
For Training, we follow the same configuration in our paper
For Training, training_epoch = 100, batch = 128, initial_learning rate = 0.1 (decayed 50% and 75% of total number of epochs), use momentum of 0.9, warm_up=25, restart=2, ...
You can easily change the value in main.py
Dataset exists in  /content/drive/Shareddrives/Eranti-Vijay-Su21-2/code/Updated_SELFIE/SELFIE/SELFIE/dataset/CIFAR-100
2021-07-18 18:22:41.999102: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-07-18 18:22:42.000147: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2021-07-18 18:22:42.026919: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-18 18:22:42.027498: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:00:04.0 name: Tesla T4 computeCapability: 7.5
coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.75GiB deviceMemoryBandwidth: 298.08GiB/s
2021-07-18 18:22:42.027562: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-07-18 18:22:42.037067: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2021-07-18 18:22:42.037147: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
2021-07-18 18:22:42.038817: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcufft.so.10
2021-07-18 18:22:42.039187: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcurand.so.10
2021-07-18 18:22:42.039639: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2021-07-18 18:22:42.040275: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusparse.so.11
2021-07-18 18:22:42.040462: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudnn.so.8
2021-07-18 18:22:42.040489: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1766] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2021-07-18 18:22:42.239995: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-07-18 18:22:42.240038: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0 
2021-07-18 18:22:42.240054: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N 
Now read following files.
['/content/drive/Shareddrives/Eranti-Vijay-Su21-2/code/Updated_SELFIE/SELFIE/SELFIE/dataset/CIFAR-100/data_batch_1.bin']
Filling queue with 20000 data before starting to train. This will take a few minutes.
Now read following files.
['/content/drive/Shareddrives/Eranti-Vijay-Su21-2/code/Updated_SELFIE/SELFIE/SELFIE/dataset/CIFAR-100/test_batch.bin']
Filling queue with 4000 data before starting to train. This will take a few minutes.
/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py:1692: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
[0718 18:22:42 @registry.py:90] 'DenseNet/conv0': [?, 32, 32, 3] --> [?, 32, 32, 16]
[0718 18:22:42 @registry.py:90] 'DenseNet/block1/dense_layer.0/conv1': [?, 32, 32, 16] --> [?, 32, 32, 12]
[0718 18:22:42 @registry.py:90] 'DenseNet/block1/dense_layer.1/conv1': [?, 32, 32, 28] --> [?, 32, 32, 12]
[0718 18:22:42 @registry.py:90] 'DenseNet/block1/dense_layer.2/conv1': [?, 32, 32, 40] --> [?, 32, 32, 12]
[0718 18:22:42 @registry.py:90] 'DenseNet/block1/dense_layer.3/conv1': [?, 32, 32, 52] --> [?, 32, 32, 12]
[0718 18:22:42 @registry.py:90] 'DenseNet/block1/dense_layer.4/conv1': [?, 32, 32, 64] --> [?, 32, 32, 12]
[0718 18:22:42 @registry.py:90] 'DenseNet/block1/dense_layer.5/conv1': [?, 32, 32, 76] --> [?, 32, 32, 12]
[0718 18:22:42 @registry.py:90] 'DenseNet/block1/dense_layer.6/conv1': [?, 32, 32, 88] --> [?, 32, 32, 12]
[0718 18:22:42 @registry.py:90] 'DenseNet/block1/transition1/conv1': [?, 32, 32, 100] --> [?, 32, 32, 100]
[0718 18:22:42 @registry.py:90] 'DenseNet/block1/transition1/pool': [?, 32, 32, 100] --> [?, 16, 16, 100]
[0718 18:22:42 @registry.py:90] 'DenseNet/block2/dense_layer.0/conv1': [?, 16, 16, 100] --> [?, 16, 16, 12]
[0718 18:22:42 @registry.py:90] 'DenseNet/block2/dense_layer.1/conv1': [?, 16, 16, 112] --> [?, 16, 16, 12]
[0718 18:22:42 @registry.py:90] 'DenseNet/block2/dense_layer.2/conv1': [?, 16, 16, 124] --> [?, 16, 16, 12]
[0718 18:22:42 @registry.py:90] 'DenseNet/block2/dense_layer.3/conv1': [?, 16, 16, 136] --> [?, 16, 16, 12]
[0718 18:22:42 @registry.py:90] 'DenseNet/block2/dense_layer.4/conv1': [?, 16, 16, 148] --> [?, 16, 16, 12]
[0718 18:22:42 @registry.py:90] 'DenseNet/block2/dense_layer.5/conv1': [?, 16, 16, 160] --> [?, 16, 16, 12]
[0718 18:22:42 @registry.py:90] 'DenseNet/block2/dense_layer.6/conv1': [?, 16, 16, 172] --> [?, 16, 16, 12]
[0718 18:22:43 @registry.py:90] 'DenseNet/block2/transition2/conv1': [?, 16, 16, 184] --> [?, 16, 16, 184]
[0718 18:22:43 @registry.py:90] 'DenseNet/block2/transition2/pool': [?, 16, 16, 184] --> [?, 8, 8, 184]
[0718 18:22:43 @registry.py:90] 'DenseNet/block3/dense_layer.0/conv1': [?, 8, 8, 184] --> [?, 8, 8, 12]
[0718 18:22:43 @registry.py:90] 'DenseNet/block3/dense_layer.1/conv1': [?, 8, 8, 196] --> [?, 8, 8, 12]
[0718 18:22:43 @registry.py:90] 'DenseNet/block3/dense_layer.2/conv1': [?, 8, 8, 208] --> [?, 8, 8, 12]
[0718 18:22:43 @registry.py:90] 'DenseNet/block3/dense_layer.3/conv1': [?, 8, 8, 220] --> [?, 8, 8, 12]
[0718 18:22:43 @registry.py:90] 'DenseNet/block3/dense_layer.4/conv1': [?, 8, 8, 232] --> [?, 8, 8, 12]
[0718 18:22:43 @registry.py:90] 'DenseNet/block3/dense_layer.5/conv1': [?, 8, 8, 244] --> [?, 8, 8, 12]
[0718 18:22:43 @registry.py:90] 'DenseNet/block3/dense_layer.6/conv1': [?, 8, 8, 256] --> [?, 8, 8, 12]
[0718 18:22:43 @registry.py:90] 'DenseNet/gap': [?, 8, 8, 268] --> [?, 268]
[0718 18:22:43 @registry.py:90] 'DenseNet/linear': [?, 268] --> [?, 100]
2021-07-18 18:22:43.507170: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-18 18:22:43.507770: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:00:04.0 name: Tesla T4 computeCapability: 7.5
coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.75GiB deviceMemoryBandwidth: 298.08GiB/s
2021-07-18 18:22:43.507799: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1766] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1375, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1358, in _run_fn
    self._extend_graph()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1398, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot place the graph because a reference or resource edge connects colocation groups with incompatible resource devices: /device:CPU:0 vs /device:GPU:0. The edge src node is input_producer , and the dst node is ReaderReadV2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/drive/Shareddrives/Eranti-Vijay-Su21-2/code/Updated_SELFIE/SELFIE/SELFIE/main.py", line 108, in <module>
    main()
  File "/content/drive/Shareddrives/Eranti-Vijay-Su21-2/code/Updated_SELFIE/SELFIE/SELFIE/main.py", line 104, in main
    selfie(gpu_id, input_reader, model_name, total_epochs, batch_size, lr_boundaries, lr_values, optimizer, noise_rate, noise_type, warm_up, threshold, queue_size, restart=restart, log_dir=log_dir)
  File "/content/drive/Shareddrives/Eranti-Vijay-Su21-2/code/Updated_SELFIE/SELFIE/SELFIE/algorithm/selfie.py", line 170, in selfie
    train_batch_patcher.bulk_load_in_memory(sess, train_ids, train_images, train_labels)
  File "/content/drive/Shareddrives/Eranti-Vijay-Su21-2/code/Updated_SELFIE/SELFIE/SELFIE/reader/batch_patcher.py", line 40, in bulk_load_in_memory
    mini_ids, mini_images, mini_labels = sess.run([ids, images, labels])
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 968, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1191, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1369, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot place the graph because a reference or resource edge connects colocation groups with incompatible resource devices: /device:CPU:0 vs /device:GPU:0. The edge src node is input_producer , and the dst node is ReaderReadV2

**Comment by Saduf2019** [comment]
@jocelynbaduria 
Can you please share the code your running, or try it on colab and share a gist with us.

**Comment by jocelynbaduria** [comment]
HI @Saduf2019 

It worked now using the version 2.0.0.

#!pip install tensorflow-gpu==2.5.0 - does not work.
!pip install tensorflow-gpu==2.0.0

Thanks
