### ISSUE TITLE
Issue running code on linux server remotely

### ISSUE THREAD

**Issue by Neha10252018** [tensorflow/tensorflow#50806]
I am doing ssh to my university sever in order to run my code which makes use of large dataset, however when i run my code i am getting bellow error after feature extraction in the code, Can someone please help as i am doing my final year project and should rectify this within 2 days

2021-07-10 09:35:48.234847: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2021-07-10 09:35:48.238831: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-07-10 09:35:49.584522: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at conv_ops_fused_impl.h:697 : Not found: No algorithm worked!
Traceback (most recent call last):
File "copy_of_copy_of_copy_of_untitled9.py", line 157, in
train_validate_features = extract_features(image_dataset_path, train_validate_images)
File "copy_of_copy_of_copy_of_untitled9.py", line 143, in extract_features
feature = model.predict(image, verbose=0)
File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/training.py", line 1629, in predict
tmp_batch_outputs = self.predict_function(iterator)
File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 828, in call
result = self._call(*args, **kwds)
File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 894, in _call
return self._concrete_stateful_fn._call_flat(
File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 1918, in _call_flat
return self._build_call_outputs(self._inference_function.call(
File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 555, in call
outputs = execute.execute(
File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.NotFoundError: No algorithm worked!
[[node model/block1_conv1/Relu (defined at copy_of_copy_of_copy_of_untitled9.py:143) ]] [Op:__inference_predict_function_610]

Function call stack:
predict_function

**Comment by saikumarchalla** [comment]
@Neha10252018 It looks like your Issue relates to the Keras component. Please submit it to the [github.com/keras-team/keras](github.com/keras-team/keras) repository instead. As ([previously announced](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999/)), all future development of Keras is expected to happen in the [github.com/keras-team/keras](github.com/keras-team/keras) repository. If your issue lies with the TF-Core area please comment back with your explanation and we can look into it further. Thanks!
