### ISSUE TITLE
tf.function runs correctly in eager mode, but breaks in graph mode

### ISSUE THREAD

**Issue by shawnwang18** [tensorflow/tensorflow#50832]
### System information

= check python ===================================================
python version: 3.8.10
python branch: 
python build version: ('default', 'Jun  2 2021 10:49:15')
python compiler version: GCC 9.4.0
python implementation: CPython

== check os platform ===============================================

== are we in docker =============================================
Yes

== compiler =====================================================
c++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== check pips ===================================================
numpy                         1.19.5
protobuf                      3.17.3
tensorflow                    2.5.0+nv
tensorflow-addons             0.13.1
tensorflow-datasets           3.2.1
tensorflow-dot-based-interact 0.0.1
tensorflow-estimator          2.5.0
tensorflow-metadata           1.1.0

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.version.VERSION = 2.5.0
tf.version.GIT_VERSION = unknown
tf.version.COMPILER_VERSION = 9.3.0

== env ==========================================================
LD_LIBRARY_PATH /usr/local/cuda/compat/lib.real:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
DYLD_LIBRARY_PATH is unset

== cuda libs  ===================================================
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudart.so.11.4.43
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudart_static.a

== tensorflow installed from info ==================
Name: tensorflow
Version: 2.5.0+nv
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /usr/local/lib/python3.8/dist-packages
Required-by: tensorflow-dot-based-interact, nvtx-plugins

== python version  ==============================================
(major, minor, micro, releaselevel, serial)
(3, 8, 10, 'final', 0)

== bazel version  ===============================================
Build label: 3.7.2
Build time: Thu Dec 17 16:57:23 2020 (1608224243)
Build timestamp: 1608224243
Build timestamp as int: 1608224243

### Describe the problem

When doing perf analysis of Tensorflow2 models, we want to breakdown the training flow into separate phases: forward, loss, backward, weight_update etc. The main idea to do the time breakdown is to run the flow in overall eager mode, but each phase is wrapped in tf.function API, so to run the phase in graph mode. We have an issue that a tf.function can run correctly under eager mode, but breaks in graph mode. 

I created a minimum tests to reproduce the issue pasted below.

in the direct test, we want to run optimizer.minimize in graph mode by wrapping with tf.function, when running the tf.function in eager mode throught setting tf.config.experimental_run_functions_eagerly(True), it works. 

But fails with if running the graph mode with below error: 

Traceback (most recent call last):
  File "direct_test.py", line 119, in <module>
    dummy_model.fit(dummy_data_generator,steps_per_epoch = 100)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/training.py", line 1183, in fit
    tmp_logs = self.train_function(iterator)
  File "direct_test.py", line 59, in train_function
    return step_function(self, iterator)
  File "direct_test.py", line 49, in step_function
    outputs = model.distribute_strategy.run(run_step, args=(data,))
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/distribute/distribute_lib.py", line 1285, in run
    return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/distribute/distribute_lib.py", line 2833, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/distribute/distribute_lib.py", line 3608, in _call_for_each_replica
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/autograph/impl/api.py", line 597, in wrapper
    return func(*args, **kwargs)
  File "direct_test.py", line 41, in run_step
    outputs = model.train_step(data)
  File "direct_test.py", line 88, in train_step
    self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 933, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 763, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 3050, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 3444, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 3279, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/func_graph.py", line 999, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 672, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/func_graph.py", line 986, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:530 minimize  *
        return self.apply_gradients(grads_and_vars, name=name)
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:630 apply_gradients  **
        grads_and_vars = optimizer_utils.filter_empty_gradients(grads_and_vars)
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/optimizer_v2/utils.py:75 filter_empty_gradients
        raise ValueError("No gradients provided for any variable: %s." %

    ValueError: No gradients provided for any variable: ['training_model/dense/kernel:0', 'training_model/dense/bias:0'].

2021-07-15 03:29:43.999375: W tensorflow/core/kernels/data/generator_dataset_op.cc:107] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
         [[{{node PyFunc}}]]

### Source code / logs

[direct_test.txt](https://github.com/tensorflow/tensorflow/files/6838642/direct_test.txt)

**Comment by old-school-kid** [comment]
Can you check the code again please.
The code provided throws an error in line 49 `outputs = model.distribute_strategy.run(run_step, args=(data,))`

ValueError: No gradients provided for any variable: ['training_model/dense/kernel:0', 'training_model/dense/bias:0'].

**Comment by shawnwang18** [comment]
@old-school-kid This issue is as expected, and it is why we filing the issue in this thread. 

if un-comment the code in line 20 to run the tf.function with eager mode:  
tf.config.experimental_run_functions_eagerly(True)

the test will pass without reporting the issue.

**Comment by kumariko** [comment]
@shawnwang18 In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!
