### ISSUE TITLE
tensorflow does not recognize gpu

### ISSUE THREAD

**Issue by WayneHsiao0225** [tensorflow/tensorflow#50842]
**System information**
- OS Platform and Distribution : Linux Ubuntu 20.04.2 LTS
- TensorFlow version: tensorflow-gpu 2.5.0
- Python version: Python 3.8
- Installed using virtualenv? pip? conda?:  pycharm venv
- GPU model and memory: Nvidia TU102[TITANRTX]
- CUDA/cuDNN version: CUDA 10.1 / 11.1
![](https://i.imgur.com/KQOzYES.png)
![](https://i.imgur.com/DamemJ7.png)

**Describe the problem**
I ran my deep reinforcement learning code(tensorflow model) on CPU and the code worked.The output is below:
```
2021-07-18 15:40:19.039476: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-07-18 15:40:20.551477: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2021-07-18 15:40:20.584382: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:65:00.0 name: TITAN RTX computeCapability: 7.5
coreClock: 1.77GHz coreCount: 72 deviceMemorySize: 23.65GiB deviceMemoryBandwidth: 625.94GiB/s
2021-07-18 15:40:20.584422: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-07-18 15:40:20.587696: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2021-07-18 15:40:20.587764: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
2021-07-18 15:40:20.588983: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcufft.so.10
2021-07-18 15:40:20.589327: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcurand.so.10
2021-07-18 15:40:20.589548: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64
2021-07-18 15:40:20.590170: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusparse.so.11
2021-07-18 15:40:20.590293: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudnn.so.8
2021-07-18 15:40:20.590310: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1766] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2021-07-18 15:40:20.590571: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-07-18 15:40:20.591825: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-07-18 15:40:20.591846: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      
/home/wayne/PycharmProjects/stock_point_/venv/lib/python3.8/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:374: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(
 
```
But it required so much memory(nearly 100%).According to my cudnn and cuda version. I installed ```tensorflow-gpu 2.5.0```. 
I checked and ensured I had the lastest tensorflow gpu release installed.The command and output is below:
- command
```
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))
```
- output
```
2021-07-18 15:46:34.898115: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-07-18 15:46:35.945751: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2021-07-18 15:46:35.975290: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:65:00.0 name: TITAN RTX computeCapability: 7.5
coreClock: 1.77GHz coreCount: 72 deviceMemorySize: 23.65GiB deviceMemoryBandwidth: 625.94GiB/s
2021-07-18 15:46:35.975330: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-07-18 15:46:35.978463: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2021-07-18 15:46:35.978520: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
2021-07-18 15:46:35.979857: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcufft.so.10
2021-07-18 15:46:35.980175: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcurand.so.10
2021-07-18 15:46:35.980391: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64
2021-07-18 15:46:35.981033: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusparse.so.11
2021-07-18 15:46:35.981142: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudnn.so.8
2021-07-18 15:46:35.981158: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1766] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
Num GPUs Available:  0

```
I tried to install other tensorflow gpu version (2.4.0,2.3.0.....).The error is below:
```
(venv) wayne:~/PycharmProjects/stock_point_$ python train.py ^GSPC 10 1000
2021-07-18 15:50:49.752192: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "train.py", line 1, in <module>
    from agent.agent import Agent
  File "/home/wayne/PycharmProjects/stock_point_/agent/agent.py", line 1, in <module>
    import keras
  File "/home/wayne/PycharmProjects/stock_point_/venv/lib/python3.8/site-packages/keras/__init__.py", line 25, in <module>
    from keras import models
  File "/home/wayne/PycharmProjects/stock_point_/venv/lib/python3.8/site-packages/keras/models.py", line 19, in <module>
    from keras import backend
  File "/home/wayne/PycharmProjects/stock_point_/venv/lib/python3.8/site-packages/keras/backend.py", line 37, in <module>
    from tensorflow.python.eager.context import get_config
ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context' (/home/wayne/PycharmProjects/stock_point_/venv/lib/python3.8/site-packages/tensorflow/python/eager/context.py)

```

Could you help me solve this problem.Thanks in advance.

**Comment by tilakrayal** [comment]
@WayneHsiao0225 ,

Can you please try installing TensorFlow v2.5 with CUDA 11.2 and cuDNN 8.1 and check if you are facing the same error. Also please take a look at the [tested build configurations](https://www.tensorflow.org/install/source#gpu).


Version | Python version | Compiler | Build tools | cuDNN | CUDA
-- | -- | -- | -- | -- | --
tensorflow-2.5.0 | 3.6-3.9 | GCC 7.3.1 | Bazel 3.7.2 | 8.1 | 11.2
tensorflow-2.4.0 | 3.6-3.8 | GCC 7.3.1 | Bazel 3.1.0 | 8.0 | 11.0
tensorflow-2.3.0 | 3.5-3.8 | GCC 7.3.1 | Bazel 3.1.0 | 7.6 | 10.1



Thanks!

**Comment by old-school-kid** [comment]
@WayneHsiao0225 
instead of importing keras as 
`import keras`
please try and import it like 
`from tensorflow import keras`
also in your code if you have imported any package from keras try and import it from tensorflow.keras instead
