### ISSUE TITLE
GazeML upgrade problem TF 1.4.0 to TF 2.5 (tf.contrib.layers.batch_norm)

### ISSUE THREAD

**Issue by louis960126** [tensorflow/tensorflow#50850]
ubnutu 20.04
Tensorflow 2.5

This is an open source GazeML from github. I am trying to modify this code to tensorflow 2.5 but have some problem in GazeML/src/models/elg.py 

  def _apply_bn(self, tensor):
        return tf.contrib.layers.batch_norm(
            tensor,
            scale=True,
            center=True,
            is_training=self.use_batch_statistics,
            trainable=True,
            data_format=self._data_format,
            updates_collections=None,
        )

AttributeError: module 'tensorflow.compat.v1' has no attribute 'contrib'

i tried 
def _apply_bn(self, tensor):
        return tf.keras.layers.LayerNormalization(
            tensor,
            scale=True,
            center=True,
            is_training=self.use_batch_statistics,
            trainable=True,
            data_format=self._data_format,
            updates_collections=None,
        )

 File "/home/user/GazeML/src/models/elg.py", line 178, in _apply_bn
    return tf.keras.layers.LayerNormalization( #tf.contrib.layers.batch_norm(
  File "/home/user/.local/lib/python3.8/site-packages/tensorflow/python/keras/layers/normalization.py", line 1119, in __init__
    super(LayerNormalization, self).__init__(**kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py", line 522, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer_v1.py", line 159, in __init__
    generic_utils.validate_kwargs(kwargs, allowed_kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 1137, in validate_kwargs
    raise TypeError(error_message, kwarg)
TypeError: ('Keyword argument not understood:', 'is_training')
Exception ignored in: <function BaseModel.__del__ at 0x7f3a09e553a0>
Traceback (most recent call last):
  File "/home/user/GazeML/src/core/model.py", line 110, in __del__
  File "/home/user/GazeML/src/core/data_source.py", line 157, in cleanup
  File "/home/user/.local/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 967, in run
  File "/home/user/.local/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1114, in _run
RuntimeError: Attempted to use a closed Session.

How do I modify this code?
Thank you guys!

**Comment by tilakrayal** [comment]
@louis960126 

Can you please take a look at this [comment](https://stackoverflow.com/questions/55870127/module-tensorflow-has-no-attribute-contrib) with similar error.It helps.Thanks!
