### ISSUE TITLE
word2vec_basic: matplotlib warning

### ISSUE THREAD

**Issue by loretoparisi** [tensorflow/tensorflow#5089]
Running the example: `word2vec_basic` - https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/word2vec/word2vec_basic.py

returns the following warning 

```
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/collections.py:548: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self._edgecolors == 'face':
```

platforms

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12
BuildVersion:	16A323
$ python -c 'import tensorflow; print tensorflow.__version__'
0.11.0rc0
```

**Comment by asimshankar** [comment]
Which version of numpy and matplotlib do you have installed?
You can use the following to obtain them:
```
python -c "import matplotlib; import numpy as np; print matplotlib.__version__; print np.__version__"
```

**Comment by loretoparisi** [comment]
@asimshankar 

```
$ python -c "import matplotlib; import numpy as np; print matplotlib.__version__; print np.__version__"
1.3.1
1.11.2
```

I did via

```
$ sudo virtualenv --system-site-packages ~/tensorflow
$ source ~/tensorflow/bin/activate
```

to update dependencies. So it seems they are not updating?

**Comment by loretoparisi** [comment]
**[UPDATE]**

Ok I did

```
$ sudo pip install matplotlib --upgrade
```

now I get

```
$ python -c "import matplotlib; import numpy as np; print matplotlib.__version__; print np.__version__"
1.5.3
1.11.2
```

I will try again then.

**Comment by loretoparisi** [comment]
**[UPDATE]**

This this I get a weird error from `matplotlib`:

```
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are Working with Matplotlib in a virtual enviroment see 'Working with Matplotlib in Virtual environments' in the Matplotlib FAQ
```

here it is the stacktrace

```
Traceback (most recent call last):
  File "word2vec_basic.py", line 240, in <module>
    import matplotlib.pyplot as plt
  File "/Users/admin/tensorflow/lib/python2.7/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/Users/admin/tensorflow/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/Users/admin/tensorflow/lib/python2.7/site-packages/matplotlib/backends/backend_macosx.py", line 24, in <module>
    from matplotlib.backends import _macosx
```

**Comment by asimshankar** [comment]
Unfortunately, how to get other packages such as matplotlib to work in specific environments is not our area of expertise and not something that we can debug in the TensorFlow project.

That said, just going off the error message you pointed to above, have you looked at ["Working with Matplotlib in Virtual environments"](http://matplotlib.org/faq/virtualenv_faq.html) in the Matplotlib FAQ.

Perhaps you can get advice on stackoverflow or on the Matplotlib project. You may also find this link: http://matplotlib.org/faq/installing_faq.html#which-python-for-os-x interesting.

Hope you find a solution, best of luck!
