### ISSUE TITLE
TFLite Conversion Error: Element Shape Required to be 1D

### ISSUE THREAD

**Issue by Hana-Ali** [tensorflow/tensorflow#50942]
### 1. System information

- Windows 10 PC, TensorFlow version 2.5.0

### 2. Code

```
import tensorflow as tf
import model as modellib
import coco
import os 
import sys

# Enable eager execution
tf.compat.v1.enable_eager_execution()

class InferenceConfig(coco.CocoConfig):
    GPU_COUNT = 1
    IMAGES_PER_GPU = 1
config = InferenceConfig()
model = modellib.MaskRCNN(mode="inference", model_dir='logs', config=config)
model.load_weights('mask_rcnn_coco.h5', by_name=True)
model = model.keras_model

tf.saved_model.save(model, "tflite")

# Preparing before conversion - making the representative dataset
ROOT_DIR = os.path.abspath("../")
CARS = os.path.join(ROOT_DIR, 'Mask_RCNN\\mrcnn\\smallCar')

IMAGE_SIZE = 224
datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

def representative_data_gen():
    dataset_list = tf.data.Dataset.list_files(CARS)
    for i in range(100):
        image = next(iter(dataset_list))
        image = tf.io.read_file(image)
        image = tf.io.decode_jpeg(image, channels=3)
        image = tf.image.resize(image, [IMAGE_SIZE, IMAGE_SIZE])
        image = tf.cast(image / 255., tf.float32)
        image = tf.expand_dims(image, 0)
        yield [image]


converter = tf.lite.TFLiteConverter.from_keras_model(model)
# This enables quantization
converter.optimizations = [tf.lite.Optimize.DEFAULT]
# This sets the representative dataset for quantization
converter.representative_dataset = representative_data_gen
# This ensures that if any ops can't be quantized, the converter throws an error
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
# For full integer quantization, though supported types defaults to int8 only, we explicitly declare it for clarity.
converter.target_spec.supported_types = [tf.int8]
# These set the input and output tensors to uint8 (added in r2.3)
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
tflite_model = converter.convert()

with open('modelQuantized.tflite', 'wb') as f:
  f.write(tflite_model)
```

### 3. Failure after conversion
I get the following error for the `tflite_model = converter.convert()` line:

`error: 'tf.TensorListReserve' op requires element_shape to be 1D tensor during TF Lite transformation pass`

Not sure what the error is, or how to fix it. Any help is appreciated!

**Comment by abattery** [comment]
converter.target_spec.supported_ops = [
          tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS
      ]
converter._experimental_lower_tensor_list_ops = True

**Comment by abattery** [comment]
Please use the Select TF ops and disable tensor list op lowering.

**Comment by Hana-Ali** [comment]
H

> 
> 
> Please use the Select TF ops and disable tensor list op lowering.

Thank you for the response!
I tried the above code you attached, and got this error instead:

Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\tensorflow\lite\python\optimize\calibrator.py", line 69, in __init__
    _calibration_wrapper.CalibrationWrapper(
TypeError: pybind11::init(): factory function returned nullptr

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "d:\Mask_RCNN\mrcnn\convertQuantize.py", line 58, in <module>
    tflite_model = converter.convert()
  File "C:\Python39\lib\site-packages\tensorflow\lite\python\lite.py", line 1057, in convert
    result = super(TFLiteKerasModelConverterV2,
  File "C:\Python39\lib\site-packages\tensorflow\lite\python\lite.py", line 795, in convert
    result = self._calibrate_quantize_model(result, **flags)
  File "C:\Python39\lib\site-packages\tensorflow\lite\python\lite.py", line 517, in _calibrate_quantize_model
    calibrate_quantize = _calibrator.Calibrator(result,
  File "C:\Python39\lib\site-packages\tensorflow\lite\python\optimize\calibrator.py", line 73, in __init__
    raise ValueError("Failed to parse the model: %s." % e)
ValueError: Failed to parse the model: pybind11::init(): factory function returned nullptr.
```
Not sure what this means :(

The code added is as follows:

```
converter = tf.lite.TFLiteConverter.from_keras_model(model)
# This enables quantization
converter.optimizations = [tf.lite.Optimize.DEFAULT]
# This sets the representative dataset for quantization
converter.representative_dataset = representative_data_gen
# This ensures that if any ops can't be quantized, the converter throws an error

converter.target_spec.supported_ops = [
tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS
]
converter._experimental_lower_tensor_list_ops = False

# For full integer quantization, though supported types defaults to int8 only, we explicitly declare it for clarity.
converter.target_spec.supported_types = [tf.int8]
# These set the input and output tensors to uint8 (added in r2.3)
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
tflite_model = converter.convert()

with open('modelQuantized.tflite', 'wb') as f:
  f.write(tflite_model)
```

I got the same error using both `True` and `False` for `converter._experimental_lower_tensor_list_ops`, since I wasn't sure which you meant! :)

**Comment by abattery** [comment]
Please try out tf-nightly version.

**Comment by Hana-Ali** [comment]
Hey @abattery 

Sorry I'm not sure I follow, this is my first model-project!! Can you elaborate? Do I just uninstall tensorflow and install tf-nightly instead? What do I do?

Thank you

**Comment by abattery** [comment]
Yes, there is a chance to fix your conversion problem with the very recent version.

**Comment by Hana-Ali** [comment]
Trying it now, will tell you how it goes! :)

**Comment by Hana-Ali** [comment]
Welp, I got a new issue this time :/

```
2021-07-26 01:34:28.913146: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-07-26 01:34:29.401304: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1504] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 5555 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 2070 SUPER, pci bus id: 0000:01:00.0, compute capability: 7.5
WARNING:tensorflow:From C:\Python39\lib\site-packages\tensorflow\python\util\deprecation.py:617: calling map_fn_v2 (from tensorflow.python.ops.map_fn) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Use fn_output_signature instead
2021-07-26 01:34:55.793182: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
2021-07-26 01:38:48.185690: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:351] Ignored output_format.
2021-07-26 01:38:48.189239: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:354] Ignored drop_control_dependency.
2021-07-26 01:38:48.193918: I tensorflow/cc/saved_model/reader.cc:98] Reading SavedModel from: C:\Users\HANAPC~1\AppData\Local\Temp\tmpvn6f94hw
2021-07-26 01:38:48.305417: I tensorflow/cc/saved_model/reader.cc:98] Reading SavedModel from: C:\Users\HANAPC~1\AppData\Local\Temp\tmpvn6f94hw
2021-07-26 01:38:48.413851: I tensorflow/cc/saved_model/reader.cc:69] Reading meta graph with tags { serve }
2021-07-26 01:38:48.418463: I tensorflow/cc/saved_model/reader.cc:131] Reading SavedModel debug info (if present) from: C:\Users\HANAPC~1\AppData\Local\Temp\tmpvn6f94hw
2021-07-26 01:38:48.976753: I tensorflow/cc/saved_model/loader.cc:212] Restoring SavedModel bundle.
2021-07-26 01:38:50.403641: I tensorflow/cc/saved_model/loader.cc:196] Running initialization op on SavedModel bundle at path: C:\Users\HANAPC~1\AppData\Local\Temp\tmpvn6f94hw
2021-07-26 01:38:50.741048: I tensorflow/cc/saved_model/loader.cc:289] SavedModel load for tags { serve }; Status: success: OK. Took 2435630 microseconds.
2021-07-26 01:38:52.040270: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:210] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2021-07-26 01:38:55.378590: W tensorflow/compiler/mlir/lite/flatbuffer_export.cc:1861] TFLite interpreter needs to link Flex delegate in order to run the model since it contains the following flex op(s):
Flex ops: FlexCropAndResize, FlexDenseToDenseSetOperation, FlexTensorListFromTensor, FlexTensorListGetItem, FlexTensorListReserve, FlexTensorListSetItem, FlexTensorListStack
Details:
        tf.CropAndResize(tensor<?x?x?x256xf32>, tensor<?x4xf32>, tensor<?xi32>, tensor<2xi32>) -> (tensor<?x14x14x256xf32>) : {T = f32, device = "", extrapolation_value = 0.000000e+00 : f32, method = "bilinear"}
        tf.CropAndResize(tensor<?x?x?x256xf32>, tensor<?x?xf32>, tensor<?xi32>, tensor<2xi32>) -> (tensor<?x7x7x256xf32>) : {T = f32, device = "", extrapolation_value = 0.000000e+00 : f32, method = "bilinear"}  
        tf.DenseToDenseSetOperation(tensor<1x?xi64>, tensor<1x?xi64>) -> (tensor<?x2xi64>, tensor<?xi64>, tensor<2xi64>) : {T = i64, device = "", set_operation = "intersection", validate_indices = true}
        tf.TensorListFromTensor(tensor<?xi32>, tensor<0xi32>) -> (tensor<!tf.variant<tensor<i32>>>) : {device = ""}
        tf.TensorListGetItem(tensor<!tf.variant<tensor<i32>>>, tensor<i32>, tensor<0xi32>) -> (tensor<i32>) : {device = ""}
        tf.TensorListReserve(tensor<i32>, tensor<i32>) -> (tensor<!tf.variant<tensor<*xi64>>>) : {device = ""}
        tf.TensorListSetItem(tensor<!tf.variant<tensor<*xi64>>>, tensor<i32>, tensor<?xi64>) -> (tensor<!tf.variant<tensor<*xi64>>>) : {device = ""}
        tf.TensorListStack(tensor<!tf.variant<tensor<*xi64>>>, tensor<1xi32>) -> (tensor<?x100xi64>) : {device = "", num_elements = -1 : i64}
INFO: Created TensorFlow Lite delegate for select TF ops.
2021-07-26 01:38:56.607760: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1504] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 5555 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 2070 SUPER, pci bus id: 0000:01:00.0, compute capability: 7.5
INFO: TfLiteFlexDelegate delegate: 13 nodes delegated out of 555 nodes with 6 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 3 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 2 nodes delegated out of 18 nodes with 2 partitions.

Traceback (most recent call last):
  File "d:\Mask_RCNN\mrcnn\convertQuantize.py", line 58, in <module>
    tflite_model = converter.convert()
  File "C:\Python39\lib\site-packages\tensorflow\lite\python\lite.py", line 731, in wrapper
    return self._convert_and_export_metrics(convert_func, *args, **kwargs)
  File "C:\Python39\lib\site-packages\tensorflow\lite\python\lite.py", line 717, in _convert_and_export_metrics
    result = convert_func(self, *args, **kwargs)
  File "C:\Python39\lib\site-packages\tensorflow\lite\python\lite.py", line 1124, in convert
    saved_model_convert_result = self._convert_as_saved_model()
  File "C:\Python39\lib\site-packages\tensorflow\lite\python\lite.py", line 1106, in _convert_as_saved_model
    return super(TFLiteKerasModelConverterV2,
  File "C:\Python39\lib\site-packages\tensorflow\lite\python\lite.py", line 906, in convert
    return self._optimize_tflite_model(
  File "C:\Python39\lib\site-packages\tensorflow\lite\python\convert_phase.py", line 222, in wrapper
    raise error from None  # Re-throws the exception.
  File "C:\Python39\lib\site-packages\tensorflow\lite\python\convert_phase.py", line 212, in wrapper
    return func(*args, **kwargs)
  File "C:\Python39\lib\site-packages\tensorflow\lite\python\lite.py", line 691, in _optimize_tflite_model
    model = self._quantize(
  File "C:\Python39\lib\site-packages\tensorflow\lite\python\lite.py", line 513, in _quantize
    calibrated = calibrate_quantize.calibrate(
  File "C:\Python39\lib\site-packages\tensorflow\lite\python\convert_phase.py", line 222, in wrapper
    raise error from None  # Re-throws the exception.
  File "C:\Python39\lib\site-packages\tensorflow\lite\python\convert_phase.py", line 212, in wrapper
    return func(*args, **kwargs)
  File "C:\Python39\lib\site-packages\tensorflow\lite\python\optimize\calibrator.py", line 184, in calibrate
    self._calibrator.Prepare([list(s.shape) for s in sample])
ValueError: Invalid input shapes: expected 3 items got 1 items.
```

I really appreciate the help. Thank you for taking the time, sorry I'm so new haha!

**Comment by abattery** [comment]
According to the message, the calibration function should return three input values but it provided only one input value.

**Comment by Hana-Ali** [comment]
Yes, but I’m not sure how to fix that. Is there something wrong with the representative data gen or?

**Comment by abattery** [comment]
Yes, the representative data gen is related.

**Comment by Hana-Ali** [comment]
Ah, do you know how I would need to change the function? :)

**Comment by abattery** [comment]
It is related with the model structure you are using. Please check out that model input/output speicifications and make sure the calibration generator follow that.

**Comment by rino20** [comment]
Hey Hana, 

In your representative_dataset function, you can add more data fields for model input as below
yield [image, data_field1, data_field2] 

I guess for mask_rcnn model, you might need to provide input shape and anchor box data.
