### ISSUE TITLE
Can't save the LSTM model. (AttributeError: 'CuDNNLSTM' object has no attribute 'unroll')

### ISSUE THREAD

**Issue by tarik0** [tensorflow/tensorflow#50945]
Hey,

I'm trying to build a `LSTM` model with CuDNN and this is the model I'm using.

```
model = Sequential()
model.add(CuDNNLSTM(256, input_shape=(train_x.shape[1:]), return_sequences=True))
model.add(Dropout(0.2))

model.add(CuDNNLSTM(256, return_sequences=False))
model.add(Dropout(0.2))
model.add(Dense(1))
model.add(Activation("tanh"))

# Compile the model.
model.compile(loss="mse", optimizer="rmsprop", metrics=["accuracy"])
print("Compiled!")

# Train the model.
model.fit(train_x, train_y, epochs=epoch, batch_size=512, validation_split=0.05)
```

But when I try to save the model with  `model.save(...)` I get this error.

```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\saving\save.py", line 150, in save_model
    saved_model_save.save(model, filepath, overwrite, include_optimizer,
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\saving\saved_model\save.py", line 90, in save
    saved_nodes, node_paths = save_lib.save_and_return_nodes(
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\saved_model\save.py", line 1103, in save_and_return_nodes
    _build_meta_graph(obj, signatures, options, meta_graph_def,
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\saved_model\save.py", line 1290, in _build_meta_graph
    return _build_meta_graph_impl(obj, signatures, options, meta_graph_def,
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\saved_model\save.py", line 1207, in _build_meta_graph_impl
    signatures = signature_serialization.find_function_to_export(
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\saved_model\signature_serialization.py", line 99, in find_function_to_export
    functions = saveable_view.list_functions(saveable_view.root)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\saved_model\save.py", line 154, in list_functions
    obj_functions = obj._list_functions_for_serialization(  # pylint: disable=protected-access
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\engine\training.py", line 2688, in _list_functions_for_serialization
    functions = super(
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\engine\base_layer.py", line 2992, in _list_functions_for_serialization
    return (self._trackable_saved_model_saver
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\saving\saved_model\base_serialization.py", line 93, in list_functions_for_serialization
    fns = self.functions_to_serialize(serialization_cache)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\saving\saved_model\layer_serialization.py", line 73, in functions_to_serialize
    return (self._get_serialized_attributes(
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\saving\saved_model\layer_serialization.py", line 89, in _get_serialized_attributes
    object_dict, function_dict = self._get_serialized_attributes_internal(
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\saving\saved_model\model_serialization.py", line 53, in _get_serialized_attributes_internal
    super(ModelSavedModelSaver, self)._get_serialized_attributes_internal(
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\saving\saved_model\layer_serialization.py", line 99, in _get_serialized_attributes_internal
    functions = save_impl.wrap_layer_functions(self.obj, serialization_cache)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\saving\saved_model\save_impl.py", line 149, in wrap_layer_functions
    original_fns = _replace_child_layer_functions(layer, serialization_cache)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\saving\saved_model\save_impl.py", line 279, in _replace_child_layer_functions
    child_layer._trackable_saved_model_saver._get_serialized_attributes(
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\saving\saved_model\layer_serialization.py", line 89, in _get_serialized_attributes
    object_dict, function_dict = self._get_serialized_attributes_internal(
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\saving\saved_model\layer_serialization.py", line 151, in _get_serialized_attributes_internal
    super(RNNSavedModelSaver, self)._get_serialized_attributes_internal(
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\saving\saved_model\layer_serialization.py", line 99, in _get_serialized_attributes_internal
    functions = save_impl.wrap_layer_functions(self.obj, serialization_cache)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\saving\saved_model\save_impl.py", line 156, in wrap_layer_functions
    call_collection = LayerCallCollection(layer)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\saving\saved_model\save_impl.py", line 406, in __init__
    self._input_signature = self._generate_input_signature(layer)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\saving\saved_model\save_impl.py", line 431, in _generate_input_signature
    layer._use_input_spec_as_call_signature):  # pylint: disable=protected-access
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\layers\recurrent.py", line 437, in _use_input_spec_as_call_signature
    if self.unroll:
AttributeError: 'CuDNNLSTM' object has no attribute 'unroll'
python-BaseException
```

**Comment by UsharaniPagadala** [comment]
@tarik0

Could you please refer similar issues [comment](https://stackoverflow.com/questions/61659414/attributeerror-module-tensorflow-has-no-attribute-cudnnlstm) and also refer this [documentation](https://www.tensorflow.org/guide/keras/rnn#performance_optimization_and_cudnn_kernels) for more information,let us know if it helps.Thanks

**Comment by UsharaniPagadala** [comment]
@tarik0 

Could you please provide the colab gist with all the dependencies to analyse the issue better.Thanks

**Comment by UsharaniPagadala** [comment]
@tarik0 

Could you please provide the colab gist with all the dependencies to analyse the issue better.Thanks

**Comment by mariisaschmidt** [comment]
Hi! Did you solve this issue? Because I am having the same problem, when I try to save my CuDNNLSTM model.
