### ISSUE TITLE
Could not find the DLL(s) 'msvcp140.dll or msvcp140_1.dll'

### ISSUE THREAD

**Issue by RostyslavUA** [tensorflow/tensorflow#50955]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.5.0
- Python version: 3.8.10
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: Intel(R) Iris(R) Plus Graphics

**Describe the problem**

`import tensorflow `
yields

`ImportError: Could not find the DLL(s) 'msvcp140.dll or msvcp140_1.dll'. TensorFlow requires that these DLLs be installed in a directory that is named in your %PATH% environment variable. You may install these DLLs by downloading "Microsoft C++ Redistributable for Visual Studio 2015, 2017 and 2019" for your platform from this URL: https://support.microsoft.com/help/2977003/the-latest-supported-visual-c-downloads`

even when I have both `msvcp140.dll` and `msvcp140_1.dll` installed and they are both placed in the directory specified by %PATH% environment variable

```
C:\Users\Rostyslav>where msvcp140.dll
C:\Program Files\Java\jdk-16\bin\msvcp140.dll
C:\Windows\System32\msvcp140.dll
C:\Users\Rostyslav\AppData\Local\Programs\Python\Python39\msvcp140.dll <-- HERE
C:\Users\Rostyslav\AppData\Local\Programs\MiKTeX\miktex\bin\x64\msvcp140.dll
```

Path environment variable looks like this:

![image](https://user-images.githubusercontent.com/49762976/127005254-b1c797c5-ec19-43c5-bb81-564ae13230ab.png)

**Provide the exact sequence of commands / steps that you executed before running into the problem**

in cmd prompt I run `python run_model.py --train --save`, which is a script from github repository that can be found 
[here](https://machine-reasoning-ufrgs.github.io/GNN-GCP/)
**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

I also tried to get more information about the problem, so I modified tensorflow's `self_check.py`. In `preload_check` in the `except OSError:` handler I added a line `import traceback; traceback.print_exc()`

The whole traceback is
```(base) PS C:\Users\Rostyslav\git\gnn-gcp> python run_model.py --train --save
Traceback (most recent call last):
  File "C:\Users\Rostyslav\anaconda3\lib\site-packages\tensorflow\python\platform\self_check.py", line 50, in preload_check
    ctypes.WinDLL(dll_name)
  File "C:\Users\Rostyslav\anaconda3\lib\ctypes\__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 87] The parameter is incorrect
Traceback (most recent call last):
  File "C:\Users\Rostyslav\anaconda3\lib\site-packages\tensorflow\python\platform\self_check.py", line 50, in preload_check
    ctypes.WinDLL(dll_name)
  File "C:\Users\Rostyslav\anaconda3\lib\ctypes\__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 87] The parameter is incorrect
Traceback (most recent call last):
  File "run_model.py", line 6, in <module>
    import tensorflow as tf
  File "C:\Users\Rostyslav\anaconda3\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Rostyslav\anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\Rostyslav\anaconda3\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "C:\Users\Rostyslav\anaconda3\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Rostyslav\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    self_check.preload_check()
  File "C:\Users\Rostyslav\anaconda3\lib\site-packages\tensorflow\python\platform\self_check.py", line 55, in preload_check
    raise ImportError(
ImportError: Could not find the DLL(s) 'msvcp140.dll or msvcp140_1.dll'. TensorFlow requires that these DLLs be installed in a directory that is named in your %PATH% environment variable. You may install these DLLs by downloading "Microsoft C++ Redistributable for Visual Studio 2015, 2017 and 2019" for your platform from this URL: https://support.microsoft.com/help/2977003/the-latest-supported-visual-c-downloads```

**Comment by Saduf2019** [comment]
@RostyslavUA 
Please refer to [this link](https://stackoverflow.com/questions/60157335/cant-pip-install-tensorflow-msvcp140-1-dll-missing) and let us know. [[link1](https://stackoverflow.com/questions/50777013/tensorflow-importerror-could-not-find-msvcp140-dll/50777261),[link2](https://www.programmersought.com/article/89164220428/)]

You have to installing the DLL as in the error message for which verify:

Check the path variable it must be inside local/prpgrams/python39 if u have previously installed 32 bit python the path must be inside roaming
So make sure you hyave 64 bit python installed
C++ redistributable may vary for your system so download it according to your configuration

**Comment by RostyslavUA** [comment]
I have already VC_redist.x64.exe installed as error-message suggests. 
The list of my installed programs are as follows:
```
C:\Users\Rostyslav>wmic
wmic:root\cli>product get name
Name
Python 3.9.1 Core Interpreter (64-bit)
Python 3.9.1 Tcl/Tk Support (64-bit)
Python 3.9.1 Standard Library (64-bit)
Python 3.9.1 pip Bootstrap (64-bit)
Python 3.9.1 Utility Scripts (64-bit)
Python 3.9.1 Test Suite (64-bit)
Python 3.9.1 Executables (64-bit)
Python 3.9.1 Development Libraries (64-bit)
Python 3.9.1 Documentation (64-bit)
Office 16 Click-to-Run Extensibility Component
Office 16 Click-to-Run Localization Component
Office 16 Click-to-Run Localization Component
Office 16 Click-to-Run Licensing Component
Texmaker 5.0.4 (64-bit)
Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.4148
Microsoft Visual C++ 2008 Redistributable - x64 9.0.21022
Microsoft Visual C++ 2019 X64 Additional Runtime - 14.29.30040
Microsoft Visual C++ 2013 x86 Minimum Runtime - 12.0.21005
Microsoft Visual C++ 2013 x86 Additional Runtime - 12.0.21005
Microsoft Visual C++ 2019 X64 Minimum Runtime - 14.29.30040
Java 8 Update 271 (64-bit)
Microsoft Update Health Tools
ESET Security
Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.6161
Verification / 1.90
Python Launcher
PDF-XChange Editor
WAGO BACnetObjectMerger

Microsoft Visual C++ 2012 x86 Additional Runtime - 11.0.61030
HP PC Hardware Diagnostics UEFI
Microsoft Visual C++ 2010  x86 Redistributable - 10.0.30319
Microsoft Visual C++ 2012 x86 Minimum Runtime - 11.0.61030
Java(TM) SE Development Kit 16 (64-bit)
Java Auto Updater
```

I also have 64 bit architecture system:

```
C:\Users\Rostyslav>set processor
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 126 Stepping 5, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=7e05
```
As in the accepted answer at the [link](https://stackoverflow.com/a/60336262/15452880) you suggested, I can find `msvcp140.dll` and `msvcp140_1.dll` in `C:\Windows\System32` directory.

But none of this unfortunately solves the problem. What else could I try?
Thank you!

**Comment by Saduf2019** [comment]
@RostyslavUA 
Can you verify the version of the DLL, should be Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019 only.

**Comment by RostyslavUA** [comment]
After many days of search and struggle, I ended up with the conclusion that I have conflicting packages with tensorflow. I got the information from [link1](https://github.com/tensorflow/tensorflow/issues/22512), [link2](https://github.com/protocolbuffers/protobuf/issues/5046#issuecomment-413726611), [link3](https://answers.microsoft.com/en-us/windows/forum/all/msvcp1401dll-missing-even-after-installing/9ffe1025-000c-4dda-b686-08b3ae00d074), [link4](https://stackoverflow.com/a/59957040/15452880).
I have downgraded my tensorflow to `tensorflow 2.0`, because it often solved the same problem of peoples, but it did not work in my case. Now I get this error

```
(hiwi-kt) PS C:\Users\Rostyslav\git\gnn-gcp> python run_model.py --train --save
Traceback (most recent call last):
  File "run_model.py", line 6, in <module>
    import tensorflow as tf
  File "C:\Users\Rostyslav\anaconda3\envs\hiwi-kt\lib\site-packages\tensorflow\__init__.py", line 98, in <module>
    from tensorflow_core import *
  File "C:\Users\Rostyslav\anaconda3\envs\hiwi-kt\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 947, in _find_and_load_unlocked
  File "C:\Users\Rostyslav\anaconda3\envs\hiwi-kt\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\Rostyslav\anaconda3\envs\hiwi-kt\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\Rostyslav\anaconda3\envs\hiwi-kt\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Rostyslav\anaconda3\envs\hiwi-kt\lib\site-packages\tensorflow_core\python\__init__.py", line 83, in <module>
    from tensorflow.python import keras
  File "C:\Users\Rostyslav\anaconda3\envs\hiwi-kt\lib\site-packages\tensorflow_core\python\keras\__init__.py", line 26, in <module>
    from tensorflow.python.keras import activations
  File "C:\Users\Rostyslav\anaconda3\envs\hiwi-kt\lib\site-packages\tensorflow_core\python\keras\__init__.py", line 26, in <module>
    from tensorflow.python.keras import activations
  File "C:\Users\Rostyslav\anaconda3\envs\hiwi-kt\lib\site-packages\tensorflow_core\python\keras\activations.py", line 23, in <module>
    from tensorflow.python.keras.utils.generic_utils import deserialize_keras_object
  File "C:\Users\Rostyslav\anaconda3\envs\hiwi-kt\lib\site-packages\tensorflow_core\python\keras\utils\__init__.py", line 38, in <module>
    from tensorflow.python.keras.utils.multi_gpu_utils import multi_gpu_model
  File "C:\Users\Rostyslav\anaconda3\envs\hiwi-kt\lib\site-packages\tensorflow_core\python\keras\utils\multi_gpu_utils.py", line 22, in <module>
    from tensorflow.python.keras.engine.training import Model
  File "C:\Users\Rostyslav\anaconda3\envs\hiwi-kt\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 47, in <module>
    from tensorflow.python.keras.engine import training_arrays
  File "C:\Users\Rostyslav\anaconda3\envs\hiwi-kt\lib\site-packages\tensorflow_core\python\keras\engine\training_arrays.py", line 41, in <module>
    from scipy.sparse import issparse  # pylint: disable=g-import-not-at-top
  File "C:\Users\Rostyslav\anaconda3\envs\hiwi-kt\lib\site-packages\scipy\__init__.py", line 106, in <module>
    from . import _distributor_init
  File "C:\Users\Rostyslav\anaconda3\envs\hiwi-kt\lib\site-packages\scipy\_distributor_init.py", line 26, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Users\Rostyslav\anaconda3\envs\hiwi-kt\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

I have tried to follow [link4](https://stackoverflow.com/a/59957040/15452880) to obtain the same package versions to resolve the issue, and now my current list looks like this:

```
# Name                    Version                   Build  Channel
absl-py                   0.13.0                   pypi_0    pypi
argon2-cffi               20.1.0                   pypi_0    pypi
astor                     0.8.1                    pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
async-generator           1.10                     pypi_0    pypi
attrs                     21.2.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
bleach                    3.3.1                    pypi_0    pypi
ca-certificates           2021.7.5             haa95532_1
cachetools                4.2.2                    pypi_0    pypi
certifi                   2021.5.30        py36haa95532_0
cffi                      1.14.6                   pypi_0    pypi
charset-normalizer        2.0.3                    pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
cpuonly                   1.0                           0    pytorch
dataclasses               0.8                      pypi_0    pypi
debugpy                   1.4.1                    pypi_0    pypi
decorator                 5.0.9                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
entrypoints               0.3                      pypi_0    pypi
flatbuffers               1.12                     pypi_0    pypi
gast                      0.2.2                    pypi_0    pypi
google-auth               1.33.1                   pypi_0    pypi
google-auth-oauthlib      0.4.4                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.34.1                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
idna                      3.2                      pypi_0    pypi
importlib-metadata        3.7.3                    pypi_0    pypi
ipykernel                 6.0.3                    pypi_0    pypi
ipython                   7.25.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.6.3                    pypi_0    pypi
jedi                      0.18.0                   pypi_0    pypi
jinja2                    3.0.1                    pypi_0    pypi
jsonschema                3.2.0                    pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            6.1.12                   pypi_0    pypi
jupyter-console           6.4.0                    pypi_0    pypi
jupyter-core              4.7.1                    pypi_0    pypi
jupyterlab-pygments       0.1.2                    pypi_0    pypi
jupyterlab-widgets        1.0.0                    pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-nightly             2.5.0.dev2021032900          pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
markdown                  3.3.4                    pypi_0    pypi
markupsafe                2.0.1                    pypi_0    pypi
matplotlib-inline         0.1.2                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
nbclient                  0.5.3                    pypi_0    pypi
nbconvert                 6.1.0                    pypi_0    pypi
nbformat                  5.1.3                    pypi_0    pypi
nest-asyncio              1.5.1                    pypi_0    pypi
notebook                  6.4.0                    pypi_0    pypi
numpy                     1.19.5                   pypi_0    pypi
oauthlib                  3.1.1                    pypi_0    pypi
openssl                   1.1.1k               h2bbff1b_0
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 21.0                     pypi_0    pypi
pandocfilters             1.4.3                    pypi_0    pypi
parso                     0.8.2                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    8.3.1                    pypi_0    pypi
pip                       20.0.2                   py36_3
prometheus-client         0.11.0                   pypi_0    pypi
prompt-toolkit            3.0.19                   pypi_0    pypi
protobuf                  3.8.0                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.20                     pypi_0    pypi
pygments                  2.9.0                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pyrsistent                0.18.0                   pypi_0    pypi
python                    3.6.8                h9f7ef89_7
python-dateutil           2.8.2                    pypi_0    pypi
pywin32                   301                      pypi_0    pypi
pywinpty                  1.1.3                    pypi_0    pypi
pyzmq                     22.1.0                   pypi_0    pypi
qtconsole                 5.1.1                    pypi_0    pypi
qtpy                      1.9.0                    pypi_0    pypi
requests                  2.26.0                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.7.2                    pypi_0    pypi
scipy                     1.4.1                    pypi_0    pypi
send2trash                1.7.1                    pypi_0    pypi
setuptools                52.0.0           py36haa95532_0
six                       1.16.0                   pypi_0    pypi
sqlite                    3.36.0               h2bbff1b_0
tensorboard               2.0.2                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.0                    pypi_0    pypi
tensorflow                2.0.0                    pypi_0    pypi
tensorflow-estimator      2.0.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.10.1                   pypi_0    pypi
testpath                  0.5.0                    pypi_0    pypi
torch                     1.9.0                    pypi_0    pypi
torchaudio                0.9.0                    pypi_0    pypi
torchvision               0.10.0                   pypi_0    pypi
tornado                   6.1                      pypi_0    pypi
traitlets                 5.0.5                    pypi_0    pypi
typing-extensions         3.7.4.3                  pypi_0    pypi
urllib3                   1.26.6                   pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
werkzeug                  2.0.1                    pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0
widgetsnbextension        3.5.1                    pypi_0    pypi
wincertstore              0.2              py36h7fe50ca_0
wrapt                     1.12.1                   pypi_0    pypi
zipp                      3.5.0                    pypi_0    pypi
```

There is probably still some conflict between the packages, but I am not sure where.

Also note that I have erased and installed `anaconda3` from scratch. 

Regarding your question about the version of DLL - I am not sure how to verify it. But note that I have also tried to install the newest DLLs suitable for my architecture from [here](https://www.dll-files.com/msvcp140.dll.html). However, this does not resolve the issue.

Sorry if I confuse you introducing different types of errors. Thus feel free to point me to any of those or to ask for any missing information.

Thank you!

**Comment by Saduf2019** [comment]
@RostyslavUA 

This issue is more suitable on Continuum Anaconda repo since its related to TF installation with Anaconda.
Please post it on [Continuum Anaconda](https://github.com/ContinuumIO/anaconda-issues/issues).Thanks!

You may also refer to this [issue once](https://github.com/tensorflow/tensorflow/issues/41831#issuecomment-665388718)

**Comment by justanotheranonymoususer** [comment]
I had the same problem, this guide helped me:
https://winbindex.m417z.com/?file=msvcp140_1.dll
