### ISSUE TITLE
Node number 106 (FlexTensorScatterUpdate) failed to prepare.

### ISSUE THREAD

**Issue by whalefa1I** [tensorflow/tensorflow#50970]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows 10
- TensorFlow installed from (source or binary):source  ,pip install tensorflow-gpu==2.5.0
- TensorFlow version (or github SHA if from source):2.5.0

**Provide the text output from tflite_convert**

```
WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.
WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.
Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_images (InputLayer)    [(1, 128, 128, 3)]        0         
_________________________________________________________________
face_detetor_1 (FaceDetetor) (None, 1, 17)             101390    
=================================================================
Total params: 101,390
Trainable params: 101,390
Non-trainable params: 0
_________________________________________________________________
```

**Standalone code to reproduce the issue** 

[colab](https://colab.research.google.com/drive/1T9kF-dn4WeH1ndN19ao5Hj0SV9Kuutrr?usp=sharing) 
[blazeface_tf.h5](https://drive.google.com/file/d/1yKLW5F7-6x9ylH65MgVxH5N5oQJgK8wq/view?usp=sharing)

**Any other info / logs**
I use this [codes](https://colab.research.google.com/drive/1T9kF-dn4WeH1ndN19ao5Hj0SV9Kuutrr?usp=sharing)  to  add some postprocess layer since I need to use NMS op after the origin model.After add postprocess layer and convert keras model to savedmodel, I convert the savedmodel to tf-lite model and there is a correct result. Then I need to depoly the tf-lite model in Android, I got an error when loading the tf-lite model:
```
try {
      detector =
          TFLiteObjectDetectionAPIModel.create(
              getAssets(),
              TF_OD_API_MODEL_FILE,
              TF_OD_API_LABELS_FILE,
              TF_OD_API_INPUT_SIZE,
              TF_OD_API_IS_QUANTIZED);
      cropSize = TF_OD_API_INPUT_SIZE;
    } catch (final IOException e) {
      e.printStackTrace();
      LOGGER.e(e, "Exception initializing classifier!");
      Toast toast =
          Toast.makeText(
              getApplicationContext(), "Classifier could not be initialized", Toast.LENGTH_SHORT);
      toast.show();
      finish();
    }
```
log
```
I/tflite: Initialized TensorFlow Lite runtime.
E/tensorflow: CameraActivity: Exception!
    java.lang.RuntimeException: java.lang.IllegalStateException: Internal error: Unexpected failure when preparing tensor allocations: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.
    Node number 106 (FlexTensorScatterUpdate) failed to prepare.
    
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.create(TFLiteObjectDetectionAPIModel.java:129)
        at org.tensorflow.lite.examples.detection.DetectorActivity.onPreviewSizeChosen(DetectorActivity.java:122)
        at org.tensorflow.lite.examples.detection.CameraActivity.onPreviewFrame(CameraActivity.java:200)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1264)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8393)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
     Caused by: java.lang.IllegalStateException: Internal error: Unexpected failure when preparing tensor allocations: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.
    Node number 106 (FlexTensorScatterUpdate) failed to prepare.
    
        at org.tensorflow.lite.NativeInterpreterWrapper.allocateTensors(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:87)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:63)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:266)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:251)
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.create(TFLiteObjectDetectionAPIModel.java:127)
        	... 9 more
```
 
Thank you for your reply!

**Comment by abattery** [comment]
The converted model has the Select TF op(s). Consider adding the dependency on the Select TF op aar.

**Comment by abattery** [comment]
https://www.tensorflow.org/lite/guide/ops_select

**Comment by chunduriv** [comment]
@whalefa1I, Did you tried as suggested [here](https://github.com/tensorflow/tensorflow/issues/50970#issuecomment-887351872)?
