### ISSUE TITLE
None of the Demo Edge TPU Models Work - “Module Provided has model identifier 'l><b', should be 'TFL3'”

### ISSUE THREAD

**Issue by Hana-Ali** [tensorflow/tensorflow#50974]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows 10

- TensorFlow installed from (source or binary):
Tensorflow 2.5

- Python version:
Python 3.8
- Installed using virtualenv? pip? conda?:
pip

****Describe the problem****

Using a Coral Devboard, and trying to run the `detect.py` file from https://github.com/google-coral/pycoral/blob/master/examples/detect_image.py with the models on the https://coral.ai/models/object-detection/ page. Tried `ssd mobilenetv2` and `EfficientDet Lite`, both get the same error:

```
Traceback (most recent call last):
  File "detect.py", line 108, in <module>
    main()
  File "detect.py", line 73, in main
    interpreter = make_interpreter(args.model)
  File "/usr/lib/python3/dist-packages/pycoral/utils/edgetpu.py", line 93, in make_interpreter
    model_path=model_path_or_content, experimental_delegates=delegates)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 351, in __init__
    experimental_preserve_all_tensors))
ValueError: Model provided has model identifier 'l><b', should be 'TFL3'
```

Not sure what the problem is, since both get the exact same error. Help is appreciated!

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I ran the command `python3 detect.py -m efficientdet_lite3_512_ptq_edgetpu.tflite -i parking.jpg -l coco_labels.txt -o result.jpg`

**Comment by abattery** [comment]
Could you file this bug report at the google coral project instead?

**Comment by Hana-Ali** [comment]
Yes sure! Thank you
