### ISSUE TITLE
Segmentation fault with basic indexing and slicing 

### ISSUE THREAD

**Issue by guillaumeBellec** [tensorflow/tensorflow#5109]
The following code generates a segmentation fault.
It should obviously return an error because op has only one dimension and a ask for two.
But an alert is probably more informative than a segmentation fault.
(Tensorflow 0.11.0rc0)

```
import tensorflow as tf

v = tf.Variable([1,1,1])
op = v * v
value = op[0,:]

sess = tf.Session()
print(sess.run(value))
```

**Comment by asimshankar** [comment]
Thanks very much for the report @guillaumeBellec . Fortunately, this bug was inadvertently fixed in abc663f2efabf9feed92461c91c7212df004162e. Unfortunately, that change is not included in the 0.11 release.

I'll see if we can include this in a release candidate for 0.11, but it will surely be fixed in the next release. (At head the program above results in the following exception:
```
Traceback (most recent call last):
  File "/x/test.py", line 5, in <module>
    value = op[0,:]
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 384, in _SliceHelper
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 538, in strided_slice
    shrink_axis_mask=shrink_axis_mask)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 3028, in strided_slice
    shrink_axis_mask=shrink_axis_mask, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 748, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2405, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1790, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1638, in _DelegateStridedSliceShape
    return common_shapes.call_cpp_shape_fn(op, input_tensors_needed=[1, 2, 3])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 596, in call_cpp_shape_fn
    raise ValueError(err.message)
ValueError: Index out of range using input dim 1; input has only 1 dims for 'strided_slice' (op: 'StridedSlice') with input shapes: [3], [2], [2], [2].
```
)
