### ISSUE TITLE
WARNING:tensorflow:AutoGraph could not transform <function> 

### ISSUE THREAD

**Issue by mrwunderbar666** [tensorflow/tensorflow#51125]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No, following this tutorial: https://www.tensorflow.org/text/tutorials/text_generation
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): binary (via pip)
- TensorFlow version (use command below): 2.5.0
- Python version: 3.8.10
- Bazel version (if compiling from source): None
- GCC/Compiler version (if compiling from source): 9.3.0
- CUDA/cuDNN version: 11.4
- GPU model and memory: NVIDIA RTX A4000, 16GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

Tensorflow throws a warning when mapping a function to a dataset. The stacktrace told me to report this (see full stack trace below):

```
WARNING: AutoGraph could not transform <function split_input_target at 0x7f24c012aa60> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Unable to locate the source code of <function split_input_target at 0x7f24c012aa60>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
```

**Describe the expected behavior**

No warning

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): No

**Standalone code to reproduce the issue**

Code taken from [tutorial](https://www.tensorflow.org/text/tutorials/text_generation):
```python
import tensorflow as tf
from tensorflow.keras.layers.experimental import preprocessing

import numpy as np
import os
import time

path_to_file = tf.keras.utils.get_file('shakespeare.txt', 'https://storage.googleapis.com/download.tensorflow.org/data/shakespeare.txt')

with open(path_to_file, 'rb') as f:
    text = f.read().decode(encoding='utf-8')

vocab = sorted(set(text))

# process the text

example_texts = ['abcdefg', 'xyz']
# unicode_split = tokenizer, split by unicode character
chars = tf.strings.unicode_split(example_texts, input_encoding='UTF-8')

# StringLookup maps strings to integers, vocab list is single chars
ids_from_chars = preprocessing.StringLookup(
            vocabulary=list(vocab), mask_token=None)

ids = ids_from_chars(chars)

# inverted operation

chars_from_ids = tf.keras.layers.experimental.preprocessing.StringLookup(
    vocabulary=ids_from_chars.get_vocabulary(), invert=True, mask_token=None)

chars = chars_from_ids(ids)
# tf & numpy way of joining a list:
tf.strings.reduce_join(chars, axis=-1).numpy()

def text_from_ids(ids):
  return tf.strings.reduce_join(chars_from_ids(ids), axis=-1)


# create training dataset

all_ids = ids_from_chars(tf.strings.unicode_split(text, 'UTF-8'))

ids_dataset = tf.data.Dataset.from_tensor_slices(all_ids)

for ids in ids_dataset.take(10):
    print(chars_from_ids(ids).numpy().decode('utf-8'))

seq_length = 100
examples_per_epoch = len(text) // (seq_length+1)

sequences = ids_dataset.batch(seq_length+1, drop_remainder=True)

for seq in sequences.take(5):
  print(text_from_ids(seq).numpy())

# create input and label pairs
# input: current character
# label: next character

def split_input_target(sequence):
    input_text = sequence[:-1]
    target_text = sequence[1:]
    return input_text, target_text

split_input_target(list("Tensorflow"))

dataset = sequences.map(split_input_target)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Full error:

```
INFO:tensorflow:Converted call: <function split_input_target at 0x7f24c012aa60>
    args: (<tf.Tensor 'args_0:0' shape=(101,) dtype=int64>,)
    kwargs: {}

Converted call: <function split_input_target at 0x7f24c012aa60>
    args: (<tf.Tensor 'args_0:0' shape=(101,) dtype=int64>,)
    kwargs: {}

INFO:tensorflow:Not allowed: <method-wrapper '__call__' of function object at 0x7f24c012aa60>: default rule
Not allowed: <method-wrapper '__call__' of function object at 0x7f24c012aa60>: default rule
INFO:tensorflow:Not allowed: <function split_input_target at 0x7f24c012aa60>: default rule
Not allowed: <function split_input_target at 0x7f24c012aa60>: default rule
INFO:tensorflow:<function split_input_target at 0x7f24c012aa60> is not cached for subkey ConversionOptions[{}]
<function split_input_target at 0x7f24c012aa60> is not cached for subkey ConversionOptions[{}]
INFO:tensorflow:Error transforming entity <function split_input_target at 0x7f24c012aa60>
Traceback (most recent call last):
  File "/redacted//.local/lib/python3.8/site-packages/tensorflow/python/autograph/pyct/parser.py", line 154, in parse_entity
    original_source = inspect_utils.getimmediatesource(entity)
  File "/redacted//.local/lib/python3.8/site-packages/tensorflow/python/autograph/pyct/inspect_utils.py", line 151, in getimmediatesource
    lines, lnum = inspect.findsource(obj)
  File "/usr/lib/python3.8/inspect.py", line 798, in findsource
    raise OSError('could not get source code')
OSError: could not get source code

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/redacted//.local/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 432, in converted_call
    converted_f = _convert_actual(target_entity, program_ctx)
  File "/redacted//.local/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 274, in _convert_actual
    transformed, module, source_map = _TRANSPILER.transform(entity, program_ctx)
  File "/redacted//.local/lib/python3.8/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 286, in transform
    return self.transform_function(obj, user_context)
  File "/redacted//.local/lib/python3.8/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 470, in transform_function
    nodes, ctx = super(PyToPy, self).transform_function(fn, user_context)
  File "/redacted//.local/lib/python3.8/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 346, in transform_function
    node, source = parser.parse_entity(fn, future_features=future_features)
  File "/redacted//.local/lib/python3.8/site-packages/tensorflow/python/autograph/pyct/parser.py", line 156, in parse_entity
    raise ValueError(
ValueError: Unable to locate the source code of <function split_input_target at 0x7f24c012aa60>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code
Error transforming entity <function split_input_target at 0x7f24c012aa60>
Traceback (most recent call last):
  File "/redacted//.local/lib/python3.8/site-packages/tensorflow/python/autograph/pyct/parser.py", line 154, in parse_entity
    original_source = inspect_utils.getimmediatesource(entity)
  File "/redacted//.local/lib/python3.8/site-packages/tensorflow/python/autograph/pyct/inspect_utils.py", line 151, in getimmediatesource
    lines, lnum = inspect.findsource(obj)
  File "/usr/lib/python3.8/inspect.py", line 798, in findsource
    raise OSError('could not get source code')
OSError: could not get source code

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/redacted//.local/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 432, in converted_call
    converted_f = _convert_actual(target_entity, program_ctx)
  File "/redacted//.local/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 274, in _convert_actual
    transformed, module, source_map = _TRANSPILER.transform(entity, program_ctx)
  File "/redacted//.local/lib/python3.8/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 286, in transform
    return self.transform_function(obj, user_context)
  File "/redacted//.local/lib/python3.8/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 470, in transform_function
    nodes, ctx = super(PyToPy, self).transform_function(fn, user_context)
  File "/redacted//.local/lib/python3.8/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 346, in transform_function
    node, source = parser.parse_entity(fn, future_features=future_features)
  File "/redacted//.local/lib/python3.8/site-packages/tensorflow/python/autograph/pyct/parser.py", line 156, in parse_entity
    raise ValueError(
ValueError: Unable to locate the source code of <function split_input_target at 0x7f24c012aa60>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code
WARNING:tensorflow:AutoGraph could not transform <function split_input_target at 0x7f24c012aa60> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Unable to locate the source code of <function split_input_target at 0x7f24c012aa60>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING: AutoGraph could not transform <function split_input_target at 0x7f24c012aa60> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Unable to locate the source code of <function split_input_target at 0x7f24c012aa60>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
```

**Comment by UsharaniPagadala** [comment]
@mrwunderbar666 
I was able to reproduce the issue in tf2.5 with no warning. Please find the [gist](https://colab.research.google.com/gist/UsharaniPagadala/98bdf8b059c2f8d8b081e6b7276d7699/untitled160.ipynb).Thanks

**Comment by mrwunderbar666** [comment]
@UsharaniPagadala 
I guess it is because I ran my code snipped in python repl. No error when executed as file.
Nevertheless, the warning told me to report this to the tensorflow devs

**Comment by UsharaniPagadala** [comment]
@mrwunderbar666 

Could you please refer similar issues [#30895](https://github.com/tensorflow/tensorflow/issues/30895) and [#28316](https://github.com/tensorflow/tensorflow/issues/28316) and let us know if it helps.Thanks
