### ISSUE TITLE
TypeError: Cannot convert a symbolic Keras input/output to a numpy array by using a custom layer

### ISSUE THREAD

**Issue by sunw70** [tensorflow/tensorflow#51351]
**System information**
* OS Platform and Distribution: Linux Ubuntu 20.10
* TensorFlow installation: pip package
* Tensorflow version: 2.6.0rc1
* Python version: 3.8

I created a Keras custom layer which implements a custom causal Conv1D. To do it, I simply used the classes Conv and Conv1D (they are in tensorflow/python/keras/layers/convolutional.py) and modified Conv. I'll show you how I use this layer with a very silly example dataset, which is characterized by only two training samples (given an ordered sequence of numbers as a training sample, the model should predict its next sequence: for example, if I've [0, 1, 2] the output will be [3, 4, 5]). However I get the following error:

   ```
 Traceback (most recent call last):
File "model.py", line 406, in <module>
model = build_model(x_train, y_train)
File "model.py", line 373, in build_model
r=Myconv1D(filters=1,kernel_size=3,padding='causal',dilation_rate=1,use_bias=False,name="MyConv")(inp)
File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1057, in __call__
outputs = call_fn(inputs, *args, **kwargs)
File "model.py", line 181, in call
z[0,4+i,0].assign(inputs[0,i,0])  
File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 1235, in assign
return var._strided_slice_assign(
File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1392, in   
_strided_slice_assign
value=ops.convert_to_tensor(value, dtype=self.dtype),
File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py", line 163, in wrapped
return func(*args, **kwargs)
File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1566, in convert_to_tensor
ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 346, in    
 _constant_tensor_conversion_function
return constant(v, dtype=dtype, name=name)
File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 271, in constant
return _constant_impl(value, dtype, shape, name, verify_shape=False,
File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 283, in    
_constant_impl
return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 308, in   
_constant_eager_impl
t = convert_to_eager_tensor(value, ctx, dtype)
File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 106, in    
convert_to_eager_tensor
return ops.EagerTensor(value, ctx.device_name, dtype)
File "/home/es/venv/lib/python3.8/site-packages/keras/engine/keras_tensor.py", line 244, in __array__
raise TypeError(
TypeError: Cannot convert a symbolic Keras input/output to a numpy array. This error may indicate that you're trying to pass a     
symbolic value to a NumPy call, which is not supported. Or, you may be trying to pass Keras symbolic inputs/outputs to a TF    
API that does not register dispatching, preventing Keras from automatically converting the API call to a lambda layer in the     
Functional Model.

```

I attached the example code used to train the model:
[model.zip](https://github.com/tensorflow/tensorflow/files/6946190/model.zip)

**Comment by sushreebarsa** [comment]
@sunw70  Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!
