### ISSUE TITLE
Conversion fails at model loading

### ISSUE THREAD

**Issue by lucapericlp** [tensorflow/tensorflow#51430]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04.7
- TensorFlow installation (pip package or built from source): pip package
- TensorFlow library (version, if pip package or github SHA, if built from source): v2.6.0-rc2

### 2. Code

`converter = tf.lite.TFLiteConverter.from_saved_model(str(SAVED_MODEL_DIR))`

Where `SAVED_MODEL_DIR` is a path which contains an efficientnet-b4 in the expected `SavedModel` format.

### 3. Failure after conversion
If the conversion is successful, but the generated model is wrong, then state what is wrong:

N.A

### 4. (optional) RNN conversion support

N.A

### 5. (optional) Any other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

[output.log](https://github.com/tensorflow/tensorflow/files/6969158/output.log)

Traceback (most recent call last):
  File "convert_to_tflite.py", line 92, in <module>
    main()
  File "convert_to_tflite.py", line 74, in main
    converter = tf.lite.TFLiteConverter.from_saved_model(str(SAVED_MODEL_DIR))
  File "/home/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 1348, in from_saved_model
    saved_model = _load(saved_model_dir, tags)
  File "/home/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 864, in load
    result = load_internal(export_dir, tags, options)["root"]
  File "/home/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 903, in load_internal
    ckpt_options, options, filters)
  File "/home/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 162, in __init__
    self._load_all()
  File "/home/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 259, in _load_all
    self._load_nodes()
  File "/home/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 448, in _load_nodes
    slot_variable = optimizer_object.add_slot(
AttributeError: '_UserObject' object has no attribute 'add_slot'

**Comment by ymodak** [comment]
Can you please provide a colab gist that reproduces the issue reported? Thanks!
