### ISSUE TITLE
unable to create tf.variables inside a function that is decorated with @tf.function

### ISSUE THREAD

**Issue by sjtusmartboy** [tensorflow/tensorflow#51453]
tf 2.5

@tf.function
def weight_fn():
    w = tf.Variable(tf.truncated_normal())

I have a function like above that would be called about **50 times**, each time it should generate a new variable and return. But according to the hint below,

```
    ValueError: A tf.Variable created inside your tf.function has been garbage-collected. Your code needs to keep Python references to variables created inside `tf.function`s.
    
    A common way to raise this error is to create and return a variable only referenced inside your function:
    
    @tf.function
    def f():
      v = tf.Variable(1.0)
      return v
    
    v = f()  # Crashes with this error message!
    
    The reason this crashes is that @tf.function annotated function returns a **`tf.Tensor`** with the **value** of the variable when the function is called rather than the variable instance itself. As such there is no code holding a reference to the `v` created inside the function and Python garbage collects it.
    
    The simplest way to fix this issue is to create variables outside the function and capture them:
    
    v = tf.Variable(1.0)
    
    @tf.function
    def f():
      return v
    
    f()  # <tf.Tensor: numpy=1.>
    v.assign_add(1.)
    f()  # <tf.Tensor: numpy=2.>

```

I should define the weight variable outside the tf.function, which means I should manually define over 50 weight variables, each line with a weight variable.

```
w1 = tf.Variable(tf.truncated_normal())
w2 = tf.Variable(tf.truncated_normal())
w3 = tf.Variable(tf.truncated_normal())
......
w50 = tf.Variable(tf.truncated_normal())

```

Undoubtedly, this kind of behavior is really stupid, any solutions to this kind of unreasonable rule?

**Comment by sumanthratna** [comment]
not sure if you saw https://github.com/tensorflow/tensorflow/pull/49310#issuecomment-900321706, but `ALLOW_DYNAMIC_VARIABLE_CREATION` may help: (untested)

```python
from tensorflow.python.eager import def_function  # def_function.function is the same as tf.function
from tensorflow.python.ops import variables


def_function.ALLOW_DYNAMIC_VARIABLE_CREATION = True

vars = {}

@def_function.function
def weight_fn(val, key):
    if key not in vars:
      vars[key] = variables.Variable(val)

weights = [weight_fn(tf.truncated_normal(), f"w{ind+1}") for ind in range(50)]
```

**Comment by sjtusmartboy** [comment]
@sumanthratna Thanks for your remind.You are very kind. It seems this is the best solution we can get for now.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

**Comment by sumanthratna** [comment]
@Venkat6871 This is still an issue: 
```
Traceback (most recent call last):
  File "/private/tmp/i51453.py", line 9, in <module>
    v = f()
  File "/private/tmp/venv/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/var/folders/l4/r2p4k6bs3j12wkvrpn5l9k180000gn/T/__autograph_generated_file3iqbdzso.py", line 10, in tf__f
    v = ag__.converted_call(ag__.ld(tf).Variable, (1.0,), None, fscope)
ValueError: in user code:

    File "/private/tmp/i51453.py", line 6, in f  *
        v = tf.Variable(1.0)

    ValueError: tf.function only supports singleton tf.Variables created on the first call. Make sure the tf.Variable is only created once or created outside tf.function. See https://www.tensorflow.org/guide/function#creating_tfvariables for more information.

```
