### ISSUE TITLE
ValueError: Tensor data is null. Run allocate_tensors() first 

### ISSUE THREAD

**Issue by rajeshdhanda** [tensorflow/tensorflow#51479]
class ImageEncoder(object):

    def __init__(self, checkpoint_filename, input_name="images",
                 output_name="features"):
        self.session = tf.Session()
        interpreter = tf.lite.Interpreter(model_path="model.tflite")
        interpreter.allocate_tensors()
        self.input_var = interpreter.get_tensor(0)
        self.output_var = interpreter.get_tensor(130)

  File "\tools\generate_detections.py", line 115, in __init__
    self.output_var = interpreter.get_tensor(130)
  File "C:\envs\yolov4-cpu\lib\site-packages\tensorflow\lite\python\interpreter.py", line 810, in get_tensor
    return self._interpreter.GetTensor(tensor_index)
_**ValueError: Tensor data is null. Run allocate_tensors() first**_

**Comment by tilakrayal** [comment]
@rajeshdhanda ,

In order to expedite the trouble-shooting process, could you please provide complete code and the TensorFlow version you are using.Thanks!

**Comment by ankitchandracs** [comment]
can anyone elaborate how the issue was resolved? i am facing the same error while trying to extract weights from tflite model.

**Comment by raulfrk** [comment]
This seems to still be a problem, has anyone figured out how to solve it? I encounter this from TF version >= 2.8

**Comment by margilt** [comment]
I'm getting this too with _Tensorflow 2.10.0_.

**Here's a code to reproduce:**

```python
import tensorflow as tf

print("TF version:", tf.__version__)

model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(units=1, input_shape=[1]),
    tf.keras.layers.Dense(units=16, activation='relu'),
    tf.keras.layers.Dense(units=1)
])

converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

interpreter = tf.lite.Interpreter(model_content=tflite_model)
interpreter.allocate_tensors()

tensor_details = interpreter.get_tensor_details()
print("Found", len(tensor_details), "tensors:")
for tensor in tensor_details:
    print(f"Tensor {tensor['index']}: {tensor['name']}")
    numpy_tensor = interpreter.get_tensor(tensor["index"])
    print("numpy shape:", numpy_tensor.shape)
```

**My run:**

```terminal
# python tests/functional/test_tflite_bug.py 
2022-09-30 18:48:49.190440: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
TF version: 2.10.0
2022-09-30 18:48:50.700174: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-09-30 18:48:51.386990: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:362] Ignored output_format.
2022-09-30 18:48:51.387051: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:365] Ignored drop_control_dependency.
2022-09-30 18:48:51.387815: I tensorflow/cc/saved_model/reader.cc:45] Reading SavedModel from: /tmp/tmp9zntcxg8
2022-09-30 18:48:51.388897: I tensorflow/cc/saved_model/reader.cc:89] Reading meta graph with tags { serve }
2022-09-30 18:48:51.388941: I tensorflow/cc/saved_model/reader.cc:130] Reading SavedModel debug info (if present) from: /tmp/tmp9zntcxg8
2022-09-30 18:48:51.391959: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:354] MLIR V1 optimization pass is not enabled
2022-09-30 18:48:51.393032: I tensorflow/cc/saved_model/loader.cc:229] Restoring SavedModel bundle.
2022-09-30 18:48:51.409210: I tensorflow/cc/saved_model/loader.cc:213] Running initialization op on SavedModel bundle at path: /tmp/tmp9zntcxg8
2022-09-30 18:48:51.415109: I tensorflow/cc/saved_model/loader.cc:305] SavedModel load for tags { serve }; Status: success: OK. Took 27301 microseconds.
2022-09-30 18:48:51.428541: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Found 7 tensors:
Tensor 0: serving_default_dense_input:0
numpy shape: (1, 1)
Tensor 1: sequential/dense/MatMul1
numpy shape: (1, 1)
Tensor 2: sequential/dense_1/MatMul
numpy shape: (16, 1)
Tensor 3: sequential/dense_2/MatMul
numpy shape: (1, 16)
Tensor 4: sequential/dense/MatMul2
Traceback (most recent call last):
  File "tests/functional/test_tflite_bug.py", line 23, in <module>
    numpy_tensor = interpreter.get_tensor(tensor["index"])
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/interpreter.py", line 852, in get_tensor
    return self._interpreter.GetTensor(tensor_index, subgraph_index)
ValueError: Tensor data is null. Run allocate_tensors() first
```

**Comment by AndyBanker** [comment]
In case it helps, I had the same problem, but noticed it was only occuring for layers with negative dimensions for which my understanding is that they have dynamic shape. I resolved by passing input data per .set_tensor, and then .invoke(). Also, possibly helpful was experimental_preserve_all_tensors=True.  
e.g (assuming only 1 input here for simplicity)
interpreter = tf.lite.Interpreter(model_path=filename, experimental_preserve_all_tensors=True)
interpreter.allocate_tensors()
interpreter.set_tensor(interpreter.get_input_details()[0]['index'], numpy.zeros(interpreter.get_input_details()[0]['shape']))
interpreter.invoke()
.. 
after which no more error when obtaining tensor details.
