### ISSUE TITLE
ValueError: No gradients provided for any variable

### ISSUE THREAD

**Issue by sjtusmartboy** [tensorflow/tensorflow#51489]
tensorflow 2.6

```
import tensorflow as tf

class Dense(tf.Module):
    def __init__(self, input_dim, output_size, name=None):
        super(Dense, self).__init__(name=name)
        self.w = tf.Variable(
            tf.random.normal([input_dim, output_size]), name='w')
        self.b = tf.Variable(tf.zeros([output_size]), name='b')
    def __call__(self, x):
        y = tf.matmul(x, self.w) + self.b
        return tf.nn.relu(y)

test = Dense(2,4)
output = test([[7.0,3]])
# print(output)
# print(test.trainable_variables)

def loss_fn():
    y_true = tf.ones([1,4])

    loss = tf.reduce_mean(tf.square(y_true - output))
    return loss

for i in range(10):
    train_op = tf.compat.v1.train.AdamOptimizer(0.4).minimize(loss_fn, var_list=test.trainable_variables)
    print(train_op)
```

```
Traceback (most recent call last):
  File "test8.py", line 29, in <module>
    train_op = tf.compat.v1.train.AdamOptimizer(0.4).minimize(loss_fn, var_list=test.trainable_variables)
  File "/home/sjtusmartboy/.local/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 418, in minimize
    ([str(v) for _, v in grads_and_vars], loss))
ValueError: No gradients provided for any variable, check your graph for ops that do not support gradients, between variables ["<tf.Variable 'b:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>", "<tf.Variable 'w:0' shape=(2, 4) dtype=float32, numpy=\narray([[-0.45559826,  0.6512007 , -0.9461316 ,  0.8137609 ],\n       [ 1.2699044 , -0.7115798 ,  0.60503614, -0.96902734]],\n      dtype=float32)>"] and loss <function loss_fn at 0x7f98016a3730>.


```

**Comment by sushreebarsa** [comment]
@sjtusmartboy  In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!

**Comment by sjtusmartboy** [comment]
@sushreebarsa 
python3.6
ubuntu18.10
tensorflow2.6

**Comment by sjtusmartboy** [comment]
I've changed the code a little bit, and it worked, but it's quite strange why         `# loss = tf.reduce_mean(tf.square(y_true - self.output)) # error` will cause error. Any reasonable explanation? Please show the manual instructions on tf website.
```
import tensorflow as tf

class Dense(tf.Module):
    def __init__(self, input_dim, output_size, name=None):
        super(Dense, self).__init__(name=name)
        self.w = tf.Variable(
            tf.random.normal([input_dim, output_size]), name='w')
        self.b = tf.Variable(tf.zeros([output_size]), name='b')


    def __call__(self, x):
        y = tf.matmul(x, self.w) + self.b
        return tf.nn.relu(y)

model = Dense(2,4)

class Test(object):
    def __init__(self):
        self.output = model([[7.0, 3]])

    def loss_fn(self):
        y_true = tf.ones([1,4])

        # loss = tf.reduce_mean(tf.square(y_true - self.output)) # error

        output2 = model([[7.0, 3]])
        loss = tf.reduce_mean(tf.square(y_true - output2))

        print(loss)
        return loss

    def run(self):
        for i in range(20):
            train_op = tf.compat.v1.train.AdamOptimizer(0.4).minimize(self.loss_fn)

Test().run()
```

**Comment by sjtusmartboy** [comment]
The following code also causes error, why? `self.output` is updated in the for-loop for every training step.
```
import tensorflow as tf

class Dense(tf.Module):
    def __init__(self, input_dim, output_size, name=None):
        super(Dense, self).__init__(name=name)
        self.w = tf.Variable(
            tf.random.normal([input_dim, output_size]), name='w')
        self.b = tf.Variable(tf.zeros([output_size]), name='b')


    def __call__(self, x):
        y = tf.matmul(x, self.w) + self.b
        return tf.nn.relu(y)

model = Dense(2,4)

class Test(object):
    def __init__(self):
        self.output = model([[7.0, 3]])

    def loss_fn(self):
        y_true = tf.ones([1,4])

        loss = tf.reduce_mean(tf.square(y_true - self.output)) 

        print(loss)
        return loss

    def run(self):
        for i in range(20):
            train_op = tf.compat.v1.train.AdamOptimizer(0.4).minimize(self.loss_fn)
            self.output = model([[7.0, 3]])

Test().run()
```

**Comment by sushreebarsa** [comment]
@sjtusmartboy Could you please refer to the[ link](https://www.tensorflow.org/api_docs/python/tf/compat/v1/train/AdamOptimizer?version=nightly), [link1](https://www.tensorflow.org/api_docs/python/tf/compat/v1/reduce_mean) and let us know if it helps? Thank you!

**Comment by sjtusmartboy** [comment]
@sushreebarsa Could you please explain why `self.output = model([[7.0, 3]])` has to be inside the `loss_fn`. I haven't seen any explanations from your links

**Comment by sushreebarsa** [comment]
@sjtusmartboy `loss_fn` is a callable which calculates labeled loss from labels, predictions, and sample_weights. An example would be a tf.keras.losses.Loss object.It is one of the  arguments required for compiling a model . Could you please refer to the [link](https://www.tensorflow.org/neural_structured_learning/api_docs/python/nsl/keras/adversarial_loss) , [link1](https://keras.io/api/losses/) and let us know if it helps? Was able to replicate your code on colab using  TF [v2.5](https://colab.research.google.com/gist/sushreebarsa/d7fd15569fa672493b68196886970d3b/untitled385.ipynb), [2.6.0 ](https://colab.research.google.com/gist/sushreebarsa/dffe8da26898642b00541ef389698985/untitled391.ipynb), please find the attached gists for reference .Thank you!
