### ISSUE TITLE
Could not find device for node (`reduce_max` of complex)

### ISSUE THREAD

**Issue by OverLordGoldDragon** [tensorflow/tensorflow#51502]
```python
tf.reduce_max(tf.constant([1 + 1j]))
```
[TF 2.5.0](https://anaconda.org/anaconda/tensorflow), Windows 10, Python 3.9.6.

<details>
  <summary><b>Error</b></summary>

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda\envs\tf25_env\lib\site-packages\tensorflow\python\util\dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "D:\Anaconda\envs\tf25_env\lib\site-packages\tensorflow\python\ops\math_ops.py", line 2908, in reduce_max
    return reduce_max_with_dims(input_tensor, axis, keepdims, name,
  File "D:\Anaconda\envs\tf25_env\lib\site-packages\tensorflow\python\ops\math_ops.py", line 2920, in reduce_max_with_dims
    gen_math_ops._max(input_tensor, dims, keepdims, name=name))
  File "D:\Anaconda\envs\tf25_env\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 5781, in _max
    _ops.raise_from_not_ok_status(e, name)
  File "D:\Anaconda\envs\tf25_env\lib\site-packages\tensorflow\python\framework\ops.py", line 6897, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Value for attr 'T' of complex128 is not in the list of allowed values: float, double, int32, uint8, int16, int8, int64, bfloat16, uint16, half, uint32, uint64, qint8, quint8, qint32, qint16, quint16
        ; NodeDef: {{node Max}}; Op<name=Max; signature=input:T, reduction_indices:Tidx -> output:T; attr=keep_dims:bool,default=false; attr=T:type,allowed=[DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT16, DT_INT8, DT_INT64, DT_BFLOAT16, DT_UINT16, DT_HALF, DT_UINT32, DT_UINT64, DT_QINT8, DT_QUINT8, DT_QINT32, DT_QINT16, DT_QUINT16]; attr=Tidx:type,default=DT_INT32,allowed=[DT_INT32, DT_INT64]> [Op:Max]
```
</details>

**Comment by collinzrj** [comment]
It is said that
```
Value for attr 'T' of complex128 is not in the list of allowed values: float, double, int32, uint8, int16, int8, int64, bfloat16, uint16, half, uint32, uint64, qint8, quint8, qint32, qint16, quint16
```
I believe complex number is not supported yet?

**Comment by sanatmpa1** [comment]
@OverLordGoldDragon,

As mentioned in the  error message and by @collinzrj, `complex128` is not supported by `tf.reduce_max` at this point of time. I've also tested in latest stable version`2.6.0` and its not supported yet. Thanks!

**Comment by OverLordGoldDragon** [comment]
@sanatmpa1 This is an unhandled exception - it helps the user to see something like

```python
   torch.max(torch.tensor([1 + 1j]))

RuntimeError: "max_all" not implemented for 'ComplexFloat
```

**Comment by mohantym** [comment]
It is still replicating in 2.9 and nightly. Attached [gist](https://colab.sandbox.google.com/gist/mohantym/6858ff76dd5f7e35d943683b4d8dd2f1/untitled79.ipynb#scrollTo=rt5eLIgAfLEU) for reference.

**Comment by cantonios** [comment]
This error message is consistent for all ops across TF when you try to run something on a dtype that isn't supported.  I suggest we keep as is for reduce max.  There are separate efforts for improving error messages across the entire TF codebase.
