### ISSUE TITLE
RuntimeError: tensorflow/lite/kernels/conv.cc:349 input->dims->data[3] != filter->dims->data[3] (64 != 2)Node number 12 (CONV_2D) failed to prepare.

### ISSUE THREAD

**Issue by hotpeppeper** [tensorflow/tensorflow#51570]
### 1. System information

- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow installation (pip package or built from source): pip package 
- TensorFlow library (version, if pip package or github SHA, if built from source): tf-nightly-2.7.0.dev20210818
- model arc: CRNN

- my converter code, succeeded in tf2.6.0 and tf-nightly but failed in tf2.3.0,
```
converter = tf.lite.TFLiteConverter.from_saved_model(model_path)
converter.experimental_new_converter = True
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
converter._experimental_lower_tensor_list_ops = False
converter.representative_dataset = representative_data_gen
lite_model = converter.convert()
lite_model_file = f'{fp16_model_path}/crnn_lite.tflite'
with open(lite_model_file, 'wb') as f:
    f.write(lite_model)
```
after call **interpreter.allocate_tensors()**, runtime errors occur。in this issue [https://github.com/tensorflow/tensorflow/issues/44548](url), install tf-nightly can fix this. please help me how can i fix this? thanks

**Comment by mohantym** [comment]
Hi!@hotpeppeper , Can you please share complete code  including` interpreter.allocate_tensors()` snippet  . Also Could you check out this [link](https://www.tensorflow.org/api_docs/python/tf/lite/Interpreter#usage_4) whether the code is as per official document.

**Comment by hotpeppeper** [comment]
@mohantym 
```
interpreter = tf.lite.Interpreter(model_path=model_file)
print(interpreter.get_input_details())
print(interpreter.get_output_details())
interpreter.allocate_tensors()
```

**Comment by mohantym** [comment]
Could you try with this snippet 
```
interpreter = tf.lite.Interpreter(model_path=model_file)
interpreter.allocate_tensors()
print(interpreter.get_input_details())
print(interpreter.get_output_details())
```

**Comment by hotpeppeper** [comment]
@mohantym the same runtime error

**Comment by mohantym** [comment]
Could you  please confirm the issue is not replicating in the latest version 2.6 or nightly but only in 2.3?

**Comment by hotpeppeper** [comment]
@mohantym convert to tflite failed when i am using tf2.3
```
loc(callsite(callsite(callsite(unknown at "crnn/bi_rnn/sequential_8/bidirectional/backward_lstm/PartitionedCall@__inference__wrapped_model_20624") at "StatefulPartitionedCall@__inference_signature_wra pper_72516") at "StatefulPartitionedCall")): error: We cannot duplicate the value since it's not constant.
 error: Failed to duplicate values for the stateful op

load model path:/data/xjming/model/Parse/crnn_ocr/git_loss_model/iter_19765000_weight_model.h5
Traceback (most recent call last):
File "/root/anaconda3/envs/ocr_tf2.3/lib/python3.7/site-packages/tensorflow/lite/python/convert.py", line 199, in toco_convert_protos
enable_mlir_converter)
File "/root/anaconda3/envs/ocr_tf2.3/lib/python3.7/site-packages/tensorflow/lite/python/wrap_toco.py", line 38, in wrapped_toco_convert
enable_mlir_converter)
Exception: <unknown>:0: error: loc(callsite(callsite(callsite(unknown at "crnn/bi_rnn/sequential_8/bidirectional/backward_lstm/PartitionedCall@__inference__wrapped_model_20624") at "StatefulPartitione dCall@__inference_signature_wrapper_72516") at "StatefulPartitionedCall")): We cannot duplicate the value since it's not constant.
```

**Comment by hotpeppeper** [comment]
@mohantym this's the whole log [https://drive.google.com/file/d/1dNODup4OJwx8ShQFxfJNRh1rp-2PgwYe/view?usp=sharing](url)

**Comment by mohantym** [comment]
Hi @hotpeppeper ,Could you please provide a Colab gist with necessary model files ?

**Comment by mohantym** [comment]
Hi @ymodak ,Could you please look at this issue.
