### ISSUE TITLE
TypeError: EndVector() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by neesetifa** [tensorflow/tensorflow#51590]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  ArchLinux
- TensorFlow installation (pip package or built from source):  pip package   
- TensorFlow library (version, if pip package or github SHA, if built from source):  v2.5.0

### 2. Code

Provide code to help us reproduce your issues using one of the following options:

```
import tensorflow as tf
import numpy as np
import pathlib


gpus = tf.config.experimental.list_physical_devices(device_type='GPU')
if gpus:
    for gpu in gpus:
        tf.config.experimental.set_memory_growth(device = gpu, enable = True)


# Set keras model name
keras_model = "weight.h5"
        
# Load MNIST dataset
mnist = tf.keras.datasets.mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()


# Normalize the input image so that each pixel value is between 0 to 1.
train_images = train_images.astype(np.float32) / 255.0
test_images = test_images.astype(np.float32) / 255.0

# Define the model architecture
model = tf.keras.Sequential([
  tf.keras.layers.InputLayer(input_shape=(28, 28)),
  tf.keras.layers.Reshape(target_shape=(28, 28, 1)),
  tf.keras.layers.Conv2D(filters=12, kernel_size=(3, 3), activation='relu'),
  tf.keras.layers.MaxPooling2D(pool_size=(2, 2)),  
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(10)
])


# Set training details
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

# Train model
model.fit(
  train_images,
  train_labels,
  epochs=5,
  validation_data=(test_images, test_labels)
)

# Save model
model.save_weights(filepath = keras_model, save_format = 'h5')

# Load keras model weight
model.load_weights(filepath = keras_model)


# Define representative dataset
def representative_data_gen():
  for input_value in tf.data.Dataset.from_tensor_slices(train_images).batch(1).take(100):
    yield [input_value]


# Do conversion
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_data_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8

tflite_model_quant = converter.convert()   # FAILED HERE


# Save the quantized model
tflite_models_dir = pathlib.Path("")
tflite_model_quant_file = tflite_models_dir/tflite_model
tflite_model_quant_file.write_bytes(tflite_model_quant)
```

### 3. Failure after conversion
Not able to convert

### 4. (optional) RNN conversion support
N/A

### 5. (optional) Any other info / logs
2021-08-20 16:27:43.366934: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
fully_quantize: 0, inference_type: 6, input_inference_type: 9, output_inference_type: 9
Traceback (most recent call last):
  File "/home/xxx/Desktop/TFLite_practice/convert_tflite.py", line 56, in <module>
    tflite_model_quant = converter.convert()
  File "/usr/lib/python3.9/site-packages/tensorflow/lite/python/lite.py", line 1057, in convert
    result = super(TFLiteKerasModelConverterV2,
  File "/usr/lib/python3.9/site-packages/tensorflow/lite/python/lite.py", line 800, in convert
    result = _modify_model_io_type(result, **flags_modify_model_io_type)
  File "/usr/lib/python3.9/site-packages/tensorflow/lite/python/util.py", line 906, in modify_model_io_type
    return _convert_model_from_object_to_bytearray(model_object)
  File "/usr/lib/python3.9/site-packages/tensorflow/lite/python/util.py", line 556, in _convert_model_from_object_to_bytearray
    model_offset = model_object.Pack(builder)
  File "/usr/lib/python3.9/site-packages/tensorflow/lite/python/schema_py_generated.py", line 5630, in Pack
    operatorCodes = builder.EndVector(len(self.operatorCodes))
TypeError: EndVector() takes 1 positional argument but 2 were given

**Comment by neesetifa** [comment]
anyone can help, please?

**Comment by yjwen** [comment]
I got the same error and solved  by downgrading flatbuffer from 2.0.0 to 1.12.0. It looks like a version mismatch between tflite and flatbuffer

**Comment by lu-wang-g** [comment]
+1. This is because your Flatbuffer version is 2.0.0, while TF 2.5/2.6 expects Flatbuffer 1.12. Reinstall TF will refresh the Flabuffer version. Or you can imply downgrade your Flatbuffer version.

**Comment by Mohit-Ak** [comment]
```
pip3 uninstall flatbuffers
pip3 install flatbuffers==1.13
```

**Comment by lu-wang-g** [comment]
We're working on the migration to Flatbuffer 2.0. Hopefully the issue will be resolved soon.

**Comment by OllyJ918** [comment]
I had to do the following for it to work, I must have installed nightly builds and it resulted in mismatches, but this worked for me: 

pip install tflite-model-maker==0.4.1
pip install tflite-support==0.4.1

I think I had a nightly version of tflite-support which was causing problems on writing the metadata to the model.

**Comment by domenicostefani** [comment]
Had the same problem and solved it with Tensorflow 2.4.1
I am using anaconda and it didn't work by downgrading the "flatbuffers" package to 1.12.0
Solved it with downgrading **python-flatbuffers** instead:
```
conda install python-flatbuffers=1.12.0
```
