### ISSUE TITLE
error

### ISSUE THREAD

**Issue by monzer511** [tensorflow/tensorflow#51620]
Internal Server Error: /form/
Traceback (most recent call last):
  File "C:\Users\MONZER\Desktop\progect\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\MONZER\Desktop\progect\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\MONZER\Desktop\progect\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MONZER\Desktop\progect\djangoAPI\MyAPI\views.py", line 80, in cxcontact
    answer=approvereject(ohevalue(df))[0]
  File "C:\Users\MONZER\Desktop\progect\djangoAPI\MyAPI\views.py", line 52, in approvereject
    y_pred=mdl.predict(X)
  File "C:\Users\MONZER\Desktop\progect\lib\site-packages\keras\engine\training.py", line 1693, in predict
    if self.distribute_strategy._should_use_with_coordinator:  # pylint: disable=protected-access
  File "C:\Users\MONZER\Desktop\progect\lib\site-packages\keras\engine\training.py", line 716, in distribute_strategy
    return self._distribution_strategy or tf.distribute.get_strategy()
AttributeError: 'Sequential' object has no attribute '_distribution_strategy'
[21/Aug/2021 22:54:34] "POST /form/ HTTP/1.1" 500 88802

**Comment by tilakrayal** [comment]
@monzer511 ,

 In order to expedite the trouble-shooting process, could you please provide a complete code and the TensorFlow version you are using.Thanks!

**Comment by tilakrayal** [comment]
Also please take a look at this links for information with similar error.[Link1](https://stackoverflow.com/questions/59765784/attributeerror-sequential-object-has-no-attribute-get-distribution-strategy),[Link2](https://newbedev.com/keras-and-tensorboard-attributeerror-sequential-object-has-no-attribute-get-distribution-strategy).It helps.Thanks!
