### ISSUE TITLE
Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by dogevspenguin** [tensorflow/tensorflow#51638]
**System information**
- OS Platform and Distribution: Mac OS X 10.11.6
- TensorFlow installed:from terminal
- TensorFlow version:~
- Python version:3.8
- Installed using pip
- Bazel version ~
- GCC/Compiler version not compiled from source
- CUDA/cuDNN version:No cuda graphic card
- GPU model and memory:memory 10 gb GPU~

**Describe the problem**
So ive ran mlagents-learn config/trainer_config.yaml --run-id=firstrun3dball --train which give error Failed to load the native TensorFlow runtime. which ive traced that is not the package problem but instead tensor flow problem

**Any other info / logs**
full log:Traceback (most recent call last):
  File "/Users/phukhao/opt/anaconda3/envs/ML-agent/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/Users/phukhao/opt/anaconda3/envs/ML-agent/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _SecKeyCopyExternalRepresentation
  Referenced from: /Users/phukhao/opt/anaconda3/envs/ML-agent/lib/python3.8/site-packages/tensorflow/python/../libtensorflow_framework.2.dylib
  Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
 in /Users/phukhao/opt/anaconda3/envs/ML-agent/lib/python3.8/site-packages/tensorflow/python/../libtensorflow_framework.2.dylib

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/phukhao/opt/anaconda3/envs/ML-agent/bin/mlagents-learn", line 33, in <module>
    sys.exit(load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')())
  File "/Users/phukhao/opt/anaconda3/envs/ML-agent/bin/mlagents-learn", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/phukhao/opt/anaconda3/envs/ML-agent/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/phukhao/opt/anaconda3/envs/ML-agent/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/phukhao/Downloads/ml-agents-release_1/ml-agents/mlagents/trainers/learn.py", line 12, in <module>
    from mlagents import tf_utils
  File "/Users/phukhao/Downloads/ml-agents-release_1/ml-agents/mlagents/tf_utils/__init__.py", line 1, in <module>
    from mlagents.tf_utils.tf import tf as tf  # noqa
  File "/Users/phukhao/Downloads/ml-agents-release_1/ml-agents/mlagents/tf_utils/tf.py", line 3, in <module>
    import tensorflow as tf  # noqa I201
  File "/Users/phukhao/opt/anaconda3/envs/ML-agent/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/Users/phukhao/opt/anaconda3/envs/ML-agent/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "/Users/phukhao/opt/anaconda3/envs/ML-agent/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "/Users/phukhao/opt/anaconda3/envs/ML-agent/lib/python3.8/site-packages/tensorflow/python/pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/phukhao/opt/anaconda3/envs/ML-agent/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Users/phukhao/opt/anaconda3/envs/ML-agent/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/Users/phukhao/opt/anaconda3/envs/ML-agent/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _SecKeyCopyExternalRepresentation
  Referenced from: /Users/phukhao/opt/anaconda3/envs/ML-agent/lib/python3.8/site-packages/tensorflow/python/../libtensorflow_framework.2.dylib
  Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
 in /Users/phukhao/opt/anaconda3/envs/ML-agent/lib/python3.8/site-packages/tensorflow/python/../libtensorflow_framework.2.dylib

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by dogevspenguin** [comment]
ok its pillow problem,and its unsolved

**Comment by mohantym** [comment]
Hi @dogevspenguin ,    Template is not completely filled ,Tensorflow version is missing . Could you please look at the [comments](https://github.com/tensorflow/tensorflow/issues/24642#issuecomment-452911775) in this issues , It suggests upgrading to macOS 10.12.6 (Sierra) or later. To use Tensorflow on old CPUs you'll need to build a binary on your own.  Also try uninstall tensorflow and install using `"conda install tensorflow" `command
