### ISSUE TITLE
No module named 'keras.api' after compiling tensorflow

### ISSUE THREAD

**Issue by FuzzyWuzzyIsABear** [tensorflow/tensorflow#51639]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.6.0
- Python version: 3.8.10
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 9.3.0
- CUDA/cuDNN version: none
- GPU model and memory: none

**Describe the problem**

I manually compiled tensorflow from sources. After compiling, my script is giving the error message "No module named 'keras.api'". 

**Provide the exact sequence of commands / steps that you executed before running into the problem**

i can't post my script but this is the import section...

import os
#os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
from pandas import read_csv, DataFrame, concat
from numpy import array
import numpy as np
import pandas as pd
from tensorflow import keras
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import LSTM, Dense, Input, Bidirectional, Attention, Conv1D, TimeDistributed
import tensorflow as tf
tf.config.optimizer.set_jit(True)
from math import fabs, floor, ceil, isnan
from sklearn import preprocessing
from tensorflow.keras import Input, layers, models
import itertools
import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import kpss
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error, r2_score
from deap import base, creator, tools, algorithms
import random
import multiprocessing
import pickle
from fredapi import Fred
import csv

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

There's no traceback. There's no error. The script pumps out that keras.api is missing.

I think I compiled it wrong. Any help greatly appreciated.

EDIT:

I dug in and its the tf.keras.optimizers.Adam function. 

Here's the traceback.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tensorflow/python/util/lazy_loader.py", line 62, in __getattr__
    module = self._load()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tensorflow/python/util/lazy_loader.py", line 45, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'keras.api'

**Comment by FuzzyWuzzyIsABear** [comment]
I fixed it reinstalling keras using pip.
