### ISSUE TITLE
[tf2.6] Model saving error for a customized model and loss function

### ISSUE THREAD

**Issue by OniReimu** [tensorflow/tensorflow#51665]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
-- Dockerfile: 
```
FROM python:3.8

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "python", "./test.py" ]
```
-- requirements.txt:
```
numpy
tensorflow
```
and
`docker build -t python-docker .`

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Not tested
- TensorFlow installed from (source or binary): Docker on Mac mini (2018)
- TensorFlow version (use command below): TF2.6
- Python version: 3.8
- Bazel version (if compiling from source): Not tested, unlikely to be related to this issue
- GCC/Compiler version (if compiling from source): Not tested, unlikely to be related to this issue
- CUDA/cuDNN version: No CUDA on this Mac mini
- GPU model and memory: N/A

**Describe the current behavior**
Typing `docker run -it --rm -v "$PWD":/usr/src/app -w /usr/src/app python-docker python test.py` in my environment will end up getting the following error, **if the `self.compiled_loss(targets, logits)` and `model.compile(optimizer=Adam(lr_schedule), loss=mean_huber_loss)` are used.**

```
KeyError: "Failed to add concrete function b'__inference_train_step_1086' to object based saved model as it captures tensor tf.Tensor(<unprintable>, shape=(), dtype=resource) which is unsupported or not reachable from root. One reason could be that a stateful object or a variable that the function depends on is not assigned to an attribute of the serialized trackable object (see SaveTest.test_captures_unreachable_variable)."
```

**If instead I use `loss = self.criterion(targets, logits)` and `model.compile(optimizer=Adam(lr_schedule))` everything works perfectly.**

**Describe the expected behavior**
Model should be properly saved to the assigned folder regardless of the two different combinations above.

**Standalone code to reproduce the issue**
```python
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.optimizers import Adam

BATCH_SIZE = 2 ** 7
NUM_ACTION = 11
STATE_DIM = 1

def _huber_loss(y_true, y_pred, max_grad=1.):
    a = tf.abs(y_true - y_pred)
    less_than_max = 0.5 * tf.square(a)
    greater_than_max = max_grad * (a - 0.5 * max_grad)
    return tf.where(a <= max_grad, x=less_than_max, y=greater_than_max)

def mean_huber_loss(y_true, y_pred):
    return tf.reduce_mean(_huber_loss(y_true, y_pred))

class NonDistributionalModel(keras.Model):
    def __init__(self, inputs, outputs):
        super(NonDistributionalModel, self).__init__(inputs=inputs, outputs=outputs)

        self.loss_tracker = keras.metrics.Mean(name="loss")
        self.abs_metric = keras.metrics.MeanTensor(name="abs") # Returns a tensor with the same shape of the input tensors

        self.criterion = mean_huber_loss

    @tf.function
    def train_step(self, data):
        states, targets = data

        with tf.GradientTape() as tape:
            logits = self(states, training=True)
            loss = self.compiled_loss(targets, logits)
            # loss = self.criterion(targets, logits)

        trainable_vars = self.trainable_variables
        gradients = tape.gradient(loss, trainable_vars)
        self.optimizer.apply_gradients(zip(gradients, trainable_vars))

        self.loss_tracker.update_state(loss)
        self.abs_metric.update_state(tf.reduce_mean(tf.math.abs(targets - logits), axis=-1))
        
        return {"loss": self.loss_tracker.result(), "abs": self.abs_metric.result()}     

    @property
    def metrics(self):
        # We list our `Metric` objects here so that `reset_states()` can be
        # called automatically at the start of each epoch
        # or at the start of `evaluate()`.
        # If you don't implement this property, you have to call
        # `reset_states()` yourself at the time of your choosing.
        return [self.loss_tracker, self.abs_metric]   

inputs = keras.Input(shape=(STATE_DIM,))
outputs = keras.layers.Dense(NUM_ACTION)(inputs)
model = NonDistributionalModel(inputs, outputs)

lr_schedule = tf.keras.optimizers.schedules.CosineDecayRestarts(initial_learning_rate=0.1,
                                                                       first_decay_steps=1000)
model.compile(optimizer=Adam(lr_schedule), loss=mean_huber_loss)
# model.compile(optimizer=Adam(lr_schedule))

x = np.random.random((BATCH_SIZE, 1))
y = np.random.random((BATCH_SIZE, NUM_ACTION))
model.fit(x, y, batch_size=BATCH_SIZE, epochs=1)

model.save('model')

```

**Other info / logs** 
```
2021-08-25 08:06:24.613536: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-08-25 08:06:24.613609: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Memory usage: 0.2776603698730469 GB
Total processing time: 1.830595807s
2021-08-25 08:06:26.613800: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-08-25 08:06:26.613940: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2021-08-25 08:06:26.613981: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (b9da2514de51): /proc/driver/nvidia/version does not exist
2021-08-25 08:06:26.614187: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-08-25 08:06:26.669676: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
1/1 [==============================] - 1s 567ms/step - loss: 0.1817 - abs: 0.5033
2021-08-25 08:06:27.407536: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/saved_model/function_serialization.py", line 65, in serialize_concrete_function
    bound_inputs.append(node_ids[capture])
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/util/object_identity.py", line 139, in __getitem__
    return self._storage[self._wrap_key(key)]
KeyError: <_ObjectIdentityWrapper wrapping <tf.Tensor: shape=(), dtype=resource, numpy=<unprintable>>>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test1.py", line 238, in <module>
    model.save('model')
  File "/usr/local/lib/python3.8/site-packages/keras/engine/training.py", line 2145, in save
    save.save_model(self, filepath, overwrite, include_optimizer, save_format,
  File "/usr/local/lib/python3.8/site-packages/keras/saving/save.py", line 149, in save_model
    saved_model_save.save(model, filepath, overwrite, include_optimizer,
  File "/usr/local/lib/python3.8/site-packages/keras/saving/saved_model/save.py", line 90, in save
    saved_nodes, node_paths = save_lib.save_and_return_nodes(
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py", line 1228, in save_and_return_nodes
    _build_meta_graph(obj, signatures, options, meta_graph_def))
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py", line 1399, in _build_meta_graph
    return _build_meta_graph_impl(obj, signatures, options, meta_graph_def)
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py", line 1362, in _build_meta_graph_impl
    object_graph_proto = _serialize_object_graph(
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py", line 936, in _serialize_object_graph
    serialized = function_serialization.serialize_concrete_function(
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/saved_model/function_serialization.py", line 67, in serialize_concrete_function
    raise KeyError(
KeyError: "Failed to add concrete function b'__inference_train_step_1086' to object based saved model as it captures tensor tf.Tensor(<unprintable>, shape=(), dtype=resource) which is unsupported or not reachable from root. One reason could be that a stateful object or a variable that the function depends on is not assigned to an attribute of the serialized trackable object (see SaveTest.test_captures_unreachable_variable)."
```

Any ideas? Thank you for your time.

**Comment by mohantym** [comment]
Hi @OniReimu , was able to replicate and resolve in TF 2.6 , providing [gist ](https://colab.research.google.com/gist/mohantym/aedce04fa6d0e00f4557d9ed5507e232/github_51565.ipynb)for reference.

Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues) for further help
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999) . Thanks!

**Comment by mohantym** [comment]
ok! @OniReimu ,Could you close this issue here?
