### ISSUE TITLE
py_function doesn't work with functions with no return values and inputs as keras.Input

### ISSUE THREAD

**Issue by kaiyu-pony** [tensorflow/tensorflow#51677]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): v2.6.0-rc2-32-g919f693420e 2.6.0
- Python version: 3.8.5
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 11.2
- GPU model and memory: GeForce RTX 2080; Memory: 8G

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

```python
>>> import tensorflow as tf
>>> a = tf.keras.Input((1,), dtype=tf.int32, name='a')
>>> tf.py_function(lambda a: None, [a], [])
```

Raises error:

```
Traceback (most recent call last):
  File "/home/kaiyu/tmp/py_env/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/home/kaiyu/tmp/py_env/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 512, in eager_py_func
    return _eager_py_func(
  File "/home/kaiyu/tmp/py_env/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 414, in _eager_py_func
    return _internal_py_func(
  File "/home/kaiyu/tmp/py_env/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 343, in _internal_py_func
    result = gen_script_ops.eager_py_func(
  File "/home/kaiyu/tmp/py_env/lib/python3.8/site-packages/tensorflow/python/ops/gen_script_ops.py", line 53, in eager_py_func
    return eager_py_func_eager_fallback(
  File "/home/kaiyu/tmp/py_env/lib/python3.8/site-packages/tensorflow/python/ops/gen_script_ops.py", line 96, in eager_py_func_eager_fallback
    _attr_Tin, input = _execute.convert_to_mixed_eager_tensors(input, ctx)
  File "/home/kaiyu/tmp/py_env/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 295, in convert_to_mixed_eager_tensors
    v = [ops.convert_to_tensor(t, ctx=ctx) for t in values]
  File "/home/kaiyu/tmp/py_env/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 295, in <listcomp>
    v = [ops.convert_to_tensor(t, ctx=ctx) for t in values]
  File "/home/kaiyu/tmp/py_env/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py", line 163, in wrapped
    return func(*args, **kwargs)
  File "/home/kaiyu/tmp/py_env/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1566, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/kaiyu/tmp/py_env/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 346, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/kaiyu/tmp/py_env/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 271, in constant
    return _constant_impl(value, dtype, shape, name, verify_shape=False,
  File "/home/kaiyu/tmp/py_env/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 283, in _constant_impl
    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
  File "/home/kaiyu/tmp/py_env/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 308, in _constant_eager_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "/home/kaiyu/tmp/py_env/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 106, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
  File "/home/kaiyu/tmp/py_env/lib/python3.8/site-packages/keras/engine/keras_tensor.py", line 244, in __array__
    raise TypeError(
TypeError: Cannot convert a symbolic Keras input/output to a numpy array. This error may indicate that you're trying to pass a symbolic value to a NumPy call, which is not supported. Or, you may be trying to pass Keras symbolic inputs/outputs to a TF API that does not register dispatching, preventing Keras from automatically converting the API call to a lambda layer in the Functional Model.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kaiyu/tmp/py_env/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 210, in wrapper
    result = dispatch(wrapper, args, kwargs)
  File "/home/kaiyu/tmp/py_env/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 126, in dispatch
    result = dispatcher.handle(op, args, kwargs)
  File "/home/kaiyu/tmp/py_env/lib/python3.8/site-packages/keras/layers/core.py", line 1473, in handle
    return TFOpLambda(op)(*args, **kwargs)
  File "/home/kaiyu/tmp/py_env/lib/python3.8/site-packages/keras/engine/base_layer.py", line 976, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "/home/kaiyu/tmp/py_env/lib/python3.8/site-packages/keras/engine/base_layer.py", line 1114, in _functional_construction_call
    outputs = self._keras_tensor_symbolic_call(
  File "/home/kaiyu/tmp/py_env/lib/python3.8/site-packages/keras/engine/base_layer.py", line 848, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/home/kaiyu/tmp/py_env/lib/python3.8/site-packages/keras/engine/base_layer.py", line 893, in _infer_output_signature
    outputs = tf.nest.map_structure(
  File "/home/kaiyu/tmp/py_env/lib/python3.8/site-packages/tensorflow/python/util/nest.py", line 869, in map_structure
    structure[0], [func(*x) for x in entries],
  File "/home/kaiyu/tmp/py_env/lib/python3.8/site-packages/tensorflow/python/util/nest.py", line 869, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "/home/kaiyu/tmp/py_env/lib/python3.8/site-packages/keras/engine/keras_tensor.py", line 584, in keras_tensor_from_tensor
    out = keras_tensor_cls.from_tensor(tensor)
  File "/home/kaiyu/tmp/py_env/lib/python3.8/site-packages/keras/engine/keras_tensor.py", line 172, in from_tensor
    type_spec = tf.type_spec_from_value(tensor)
  File "/home/kaiyu/tmp/py_env/lib/python3.8/site-packages/tensorflow/python/framework/type_spec.py", line 609, in type_spec_from_value
    raise TypeError("Could not build a TypeSpec for %r with type %s" %
TypeError: Could not build a TypeSpec for <tf.Operation 'tf.py_function_1/EagerPyFunc' type=EagerPyFunc> with type Operation
```

**Describe the expected behavior**

Should simply pass.

If `a` is a constant instead, it works.

```python
>>> import tensorflow as tf
>>> a = tf.constant(1)
>>> tf.py_function(lambda a: None, [a], [])
[]
```

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing): N/A

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

https://colab.research.google.com/drive/19qhwT5fPmVX0SB6FgNJYZvaI3kXCSzOG?usp=sharing

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@kaiyu-pony 
You can use "tf.compat.v1.disable_eager_execution()" to avoid the error, please refer to this [gist here](https://colab.research.google.com/gist/Saduf2019/eedfcb6027362d1c0dc5db5ce5aca460/untitled631.ipynb).

**Comment by kaiyu-pony** [comment]
@Saduf2019 I see. But for some reason I need to avoid that in my project.
Is this the expected behavior? If so, could you please make the error message clearer? Otherwise, could you please fix it?

**Comment by tilakrayal** [comment]
@kaiyu-pony,
Could you please try to execute the code as suggested [here](https://github.com/tensorflow/tensorflow/issues/51677#issuecomment-910455345). Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/06368b656fbe291b12c16b71419cbf0a/untitled591.ipynb) and let us know if the issue still persists. Thank you!

**Comment by kaiyu-pony** [comment]
> @kaiyu-pony, Could you please try to execute the code as suggested [here](https://github.com/tensorflow/tensorflow/issues/51677#issuecomment-910455345). Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/06368b656fbe291b12c16b71419cbf0a/untitled591.ipynb) and let us know if the issue still persists. Thank you!

Hi @tilakrayal , just wanted to confirm, is `tf.py_function` expected to fail when given `tf.keras.Input` as inputs under eager execution mode? If so, would it be better to check the inputs in the `tf.py_function` and give explicit error messages noticing the users about this?

**Comment by SuryanarayanaY** [comment]
Hi,
Iam able to replicate the issue in TF2.10 and nightly versions.Please refer attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/a254ff456169b4c8751a2a284849d9a7/51677.ipynb) here.
Thankyou!

**Comment by tilakrayal** [comment]
@kaiyu-pony,
The `tf.py_function` is expected to fail when given **tf.keras.Input** as inputs under eager execution mode. tf.py_function allows embedding python code within the tensorFlow graphs for flexibility. However, it can be difficult in gradient calculation and optimization.  Also **keras.input** works with eager execution, but not directly with **tf.py_function**.   

 **tf.py_function** expects concrete tensors as inputs, not tf.keras.Input placeholders. Attempting to pass `tf.keras.Input to tf.py_function` results in a type error due to incompatibility.    

Kindly find the [gist](https://colab.research.google.com/gist/tilakrayal/50f0860ba275b493b2d20b1c75e89a47/untitled1710.ipynb) with the informative error in the latest versions. Thank you!
