### ISSUE TITLE
Unable to generate train.record, but for text.record it works fine

### ISSUE THREAD

**Issue by MePando** [tensorflow/tensorflow#51729]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): nope
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): I used the guide at https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/install.html
- TensorFlow version (use command below): 2.6.0
- Python version: Python 3.8.8
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source): nope 
- CUDA/cuDNN version: nope
- GPU model and memory: nope

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior** When following the guide command to change format from xml to record, it doesn't work for train but works for text

**Describe the expected behavior**

it should output something like: Successfully created the TFRecord file: /home/jrhin/Tensorflow/workspace/training_demo/annotations/train.record

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

python generate_tfrecord.py -x ~/Tensorflow/workspace/training_demo/images/train -l ~/Tensorflow/workspace/training_demo/annotations/label_map.pbtxt -o ~/Tensorflow/workspace/training_demo/annotations/train.record

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Traceback (most recent call last):
  File "generate_tfrecord.py", line 172, in <module>
    tf.app.run()
  File "/home/jrhin/anaconda3/lib/python3.8/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/jrhin/anaconda3/lib/python3.8/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/jrhin/anaconda3/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "generate_tfrecord.py", line 162, in main
    tf_example = create_tf_example(group, path)
  File "generate_tfrecord.py", line 136, in create_tf_example
    classes.append(class_text_to_int(row['class']))
  File "generate_tfrecord.py", line 105, in class_text_to_int
    return label_map_dict[row_label]
KeyError: 'w'

**Comment by MePando** [comment]
Ok, I've find out that you have to first divide the images into train and test folder. Then you can add labeling to them. After that TF records are generated successfully!
But the guide tells you to first add label and then divide them into train and test folders!!! https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html
