### ISSUE TITLE
When use keras + TensorBoard with parameter server strategy, error on worker is raised and core is dumped.

### ISSUE THREAD

**Issue by zpcalan** [tensorflow/tensorflow#51768]
Hi, developers of tensorflow.
The environment, code, and issue I encountered are listed below:

TF version: nightly
OS: ubuntu16.04
cuda: 11.0

Worker code: (PS code is almost the same as this one)
```
import multiprocessing
import os
import json
import random
import portpicker
import tensorflow as tf
from tensorflow.keras.layers.experimental import preprocessing


def create_in_process_cluster(num_workers, num_ps):
  """Creates and starts local servers and returns the cluster_resolver."""
  worker_ports = [portpicker.pick_unused_port() for _ in range(num_workers)]
  ps_ports = [portpicker.pick_unused_port() for _ in range(num_ps)]

  cluster_dict = {}
  cluster_dict["worker"] = ["ip:port"]
  if num_ps > 0:
    cluster_dict["ps"] = ["ip:port"]
  print("==========================", cluster_dict["worker"], cluster_dict["ps"])
  cluster_spec = tf.train.ClusterSpec(cluster_dict)

  # Workers need some inter_ops threads to work properly.
  worker_config = tf.compat.v1.ConfigProto()
  if multiprocessing.cpu_count() < num_workers + 1:
    worker_config.inter_op_parallelism_threads = num_workers + 1
  
  os.environ["TF_CONFIG"] = json.dumps({
    "cluster": {
        "worker": cluster_dict["worker"],
        "ps": cluster_dict["ps"],
    },
    "task": {"type": "worker", "index": 0}
  })
  cluster_resolver = tf.distribute.cluster_resolver.TFConfigClusterResolver()
  return cluster_resolver

# Set the environment variable to allow reporting worker and ps failure to the
# coordinator. This is a workaround and won't be necessary in the future.
os.environ["GRPC_FAIL_FAST"] = "use_caller"

NUM_WORKERS = 1
NUM_PS = 1

cluster_resolver = create_in_process_cluster(NUM_WORKERS, NUM_PS)
os.environ["GRPC_FAIL_FAST"] = "use_caller"
if cluster_resolver.task_type in ("worker", "ps"):
    server = tf.distribute.Server(
        cluster_resolver.cluster_spec(),
        job_name=cluster_resolver.task_type,
        task_index=cluster_resolver.task_id,
        protocol=cluster_resolver.rpc_layer or "grpc",
        start=True)


strategy = tf.distribute.experimental.ParameterServerStrategy(cluster_resolver)
    
def dataset_fn(input_context):
  global_batch_size = 64
  batch_size = input_context.get_per_replica_batch_size(global_batch_size)

  x = tf.random.uniform((10, 10))
  y = tf.random.uniform((10,))

  dataset = tf.data.Dataset.from_tensor_slices((x, y)).shuffle(10).repeat()
  dataset = dataset.shard(
      input_context.num_input_pipelines,
      input_context.input_pipeline_id)
  dataset = dataset.batch(batch_size)
  dataset = dataset.prefetch(2)

  return dataset

dc = tf.keras.utils.experimental.DatasetCreator(dataset_fn)

with strategy.scope():
  model = tf.keras.models.Sequential([tf.keras.layers.Dense(10)])

model.compile(tf.keras.optimizers.SGD(), loss='mse', metrics=['accuracy'], steps_per_execution=10)


working_dir = './my_working_dir'
log_dir = os.path.join(working_dir, 'log')
ckpt_filepath = os.path.join(working_dir, 'ckpt')
backup_dir = os.path.join(working_dir, 'backup')

callbacks = [
    tf.keras.callbacks.TensorBoard(log_dir=log_dir),
    tf.keras.callbacks.ModelCheckpoint(filepath=ckpt_filepath),
    tf.keras.callbacks.experimental.BackupAndRestore(backup_dir=backup_dir),
    tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)
]

tf.summary.trace_on()

model.fit(dc, epochs=50000, steps_per_epoch=20, callbacks=callbacks)

import time
time.sleep(100000)
```

The error of the Worker process:

```
Traceback (most recent call last):
  File "worker_in_process_ps.py", line 99, in <module>
    model.fit(dc, epochs=50000, steps_per_epoch=20, callbacks=callbacks)
  File "keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "tensorflow/python/ops/summary_ops_v2.py", line 1342, in trace_export
    raise ValueError("Must enable trace before export.")
ValueError: Must enable trace before export.
terminate called without an active exception
Aborted (core dumped)
```

I want to check the graph on the worker by TensorBoard. Anyone knows how to fix this issue?

**Comment by zpcalan** [comment]
https://stackoverflow.com/questions/56663388/tensorboard-errortrace-already-enabled-how-to-solve 
I refer to the link above and I pass `profile_batch = 100000000` to the tensorboard callback and solve this issue.
Anyway, issue closed.

**Comment by mohantym** [comment]
Hi @zpcalan ,  look at this [comment](https://github.com/tensorflow/tensorboard/issues/2819#issuecomment-572678589) too. For further queries ,Raise an issue in [Tensorboard ](https://github.com/tensorflow/tensorboard)Repository. Thanks!

**Comment by zpcalan** [comment]
Thanks for your reply! I've fixed this issue using the method in the comment.
Now I have another question. Please check this [issue](https://github.com/tensorflow/tensorflow/issues/51778).
