### ISSUE TITLE
Unable to restore the model with shared ops using from_config()

### ISSUE THREAD

**Issue by l-bat** [tensorflow/tensorflow#51793]
**System information**
- OS Platform and Distribution:  Linux Ubuntu 18.04
- TensorFlow installed from pip
- TensorFlow version: 2.6.0
- Python version: 3.7.11
- CUDA Version: 11.2
-  Driver Version: 460.80

**Describe the current behavior**
Can not load model with shared ops from config. During loading, the outputs of the shared operation are placed in the wrong positions.

**Describe the expected behavior**
The original model and the restored model are the same

**Standalone code to reproduce the issue**
```python
import numpy as np
import tensorflow as tf

print(tf.__version__)

def get_test_model():
    input_1 = tf.keras.Input(shape=(5, 5, 2))
    input_2 = tf.keras.Input(shape=(5, 5, 2))
    image_shape = tf.keras.Input(shape=(1, 2), name='image_shape')

    clips = []
    relu = tf.keras.layers.ReLU()
    for inp in [input_1, input_2]:
        dy = inp[..., 0:1]
        dx = inp[..., 1:2]

        y = relu(relu(dy) + dx)
        x = relu(relu(dx) + dy)
        cat = tf.concat([y, x], -1)

        height, width = tf.unstack(image_shape, axis=-1)
        max_length = tf.stack(
            [relu(height), relu(width)], axis=-1)

        clip = tf.math.minimum(cat, max_length)
        clips.append(clip)

    out = tf.concat(clips, axis=1)
    return tf.keras.Model(inputs=[input_1, input_2, image_shape], outputs=out)


input_1 = np.random.rand(1, 5, 5, 2)
input_2 = np.random.rand(1, 5, 5, 2)
image_shape = np.random.rand(1, 1, 2)
inputs = [input_1, input_2, image_shape]

model = get_test_model()

ref = model.predict(inputs)
print(ref.shape)  # succsess (1, 10, 5, 2)

restored_model = tf.keras.Model.from_config(model.get_config())  # failed
out = restored_model.predict(inputs)
print(out.shape)
```
original frozen graph
![image](https://user-images.githubusercontent.com/22346860/131807492-4cc0a0e4-c94b-4928-9deb-c96945770510.png)

Error with restore model from config:
```bash
Traceback (most recent call last):
  File "/home/miniconda3/envs/tf2.6.0/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1880, in _create_c_op
    c_op = pywrap_tf_session.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape must be rank 4 but is rank 2 for '{{node tf.concat/concat}} = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32](Placeholder, Placeholder_1, tf.concat/concat/axis)' with input shapes: [?,5,5,1], [?,1], [].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tf_bug.py", line 42, in <module>
    restored_model = tf.keras.Model.from_config(model.get_config())  # failed
  File "/home/miniconda3/envs/tf2.6.0/lib/python3.7/site-packages/keras/engine/training.py", line 2397, in from_config
    functional.reconstruct_from_config(config, custom_objects))
  File "/home/miniconda3/envs/tf2.6.0/lib/python3.7/site-packages/keras/engine/functional.py", line 1283, in reconstruct_from_config
    process_node(layer, node_data)
  File "/home/miniconda3/envs/tf2.6.0/lib/python3.7/site-packages/keras/engine/functional.py", line 1231, in process_node
    output_tensors = layer(input_tensors, **kwargs)
  File "/home/miniconda3/envs/tf2.6.0/lib/python3.7/site-packages/keras/engine/base_layer.py", line 977, in __call__
    input_list)
  File "/home/miniconda3/envs/tf2.6.0/lib/python3.7/site-packages/keras/engine/base_layer.py", line 1115, in _functional_construction_call
    inputs, input_masks, args, kwargs)
  File "/home/miniconda3/envs/tf2.6.0/lib/python3.7/site-packages/keras/engine/base_layer.py", line 848, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/home/miniconda3/envs/tf2.6.0/lib/python3.7/site-packages/keras/engine/base_layer.py", line 888, in _infer_output_signature
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/miniconda3/envs/tf2.6.0/lib/python3.7/site-packages/keras/layers/core.py", line 1350, in _call_wrapper
    return self._call_wrapper(*args, **kwargs)
  File "/home/miniconda3/envs/tf2.6.0/lib/python3.7/site-packages/keras/layers/core.py", line 1382, in _call_wrapper
    result = self.function(*args, **kwargs)
  File "/home/miniconda3/envs/tf2.6.0/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/home/miniconda3/envs/tf2.6.0/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 1769, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
  File "/home/miniconda3/envs/tf2.6.0/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1228, in concat_v2
    "ConcatV2", values=values, axis=axis, name=name)
  File "/home/miniconda3/envs/tf2.6.0/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 750, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/home/miniconda3/envs/tf2.6.0/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 601, in _create_op_internal
    compute_device)
  File "/home/miniconda3/envs/tf2.6.0/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3569, in _create_op_internal
    op_def=op_def)
  File "/home/miniconda3/envs/tf2.6.0/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 2042, in __init__
    control_input_ops, op_def)
  File "/home/miniconda3/envs/tf2.6.0/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1883, in _create_c_op
    raise ValueError(str(e))
ValueError: Shape must be rank 4 but is rank 2 for '{{node tf.concat/concat}} = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32](Placeholder, Placeholder_1, tf.concat/concat/axis)' with input shapes: [?,5,5,1], [?,1], [].
```

**Comment by sanatmpa1** [comment]
@l-bat,

I see that the error occurs in `2.6.0` whereas with `tf-nightly` it works fine. Please take a look at the [gist here](https://colab.research.google.com/gist/sanatmpa1/4dcda01fe2bbafe77f98d787e0feee8e/51793.ipynb). Thanks!

**Comment by l-bat** [comment]
@sanatmpa1
Great!
Can we close the issue when TF 2.7.0 is released?

**Comment by sanatmpa1** [comment]
@l-bat,

As its working in nightly, can you close this issue and open it again if its still an issue on later release. Thanks!
