### ISSUE TITLE
GPU Error: Check failed: work_element_count > 0 (0 vs. 0) 

### ISSUE THREAD

**Issue by makisgrammenos** [tensorflow/tensorflow#51803]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.6.0
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.2/8.1.0.77
- GPU model and memory: GTX 1060 6GB

Hey everyone,

I am experiencing a strange issue when trying to train  a 3DConv with Custom data generator.
Whne I call `model.fit(train_data,epochs=10)`  where `train_data` is the generator I get this GPU related error
`2021-09-02 12:27:24.281505: F .\tensorflow/core/util/gpu_launch_config.h:129] Check failed: work_element_count > 0 (0 vs. 0)`
The error seems to disappear when not using GPU 
I

The generator is this:

```python
class Dataset(tf.keras.utils.Sequence):
    def __init__(self, data, batch_size=BATCH_SIZE, shuffle=True):
        self.data = np.array(data)
        self.batch_size = batch_size
        self.shuffle = shuffle
        self.indices = data.index.tolist()

    # @staticmethod
    def __load_dicom_image(self,path, img_size=IMAGE_SIZE, voi_lut=True, rotate=0):
        dicom = pydicom.read_file(path)
        data = dicom.pixel_array
        if voi_lut:
            data = apply_voi_lut(dicom.pixel_array, dicom)
        else:
            data = dicom.pixel_array

        if rotate > 0:
            rot_choices = [0, cv2.ROTATE_90_CLOCKWISE, cv2.ROTATE_90_COUNTERCLOCKWISE, cv2.ROTATE_180]
            data = cv2.rotate(data, rot_choices[rotate])

        data = cv2.resize(data, (img_size, img_size))
        return data

    

    def __load_dicom_images_3d(self, scan_id, num_imgs=NUM_IMAGES, img_size=IMAGE_SIZE, mri_type="FLAIR", split="train",
                               rotate=0):

        files = sorted(glob.glob(f"{data_directory}/{split}/{scan_id}/{mri_type}/*.dcm"),
                       key=lambda var: [int(x) if x.isdigit() else x for x in re.findall(r'[^0-9]|[0-9]+', var)])

        middle = len(files) // 2
        num_imgs2 = num_imgs // 2
        p1 = max(0, middle - num_imgs2)
        p2 = min(len(files), middle + num_imgs2)
        img3d = np.stack([self.__load_dicom_image(f, rotate=rotate) for f in files[p1:p2]]).T
        if img3d.shape[-1] < num_imgs:
            n_zero = np.zeros((img_size, img_size, num_imgs - img3d.shape[-1]))
            img3d = np.concatenate((img3d, n_zero), axis=-1)

        if np.min(img3d) < np.max(img3d):
            img3d = img3d - np.min(img3d)
            img3d = img3d / np.max(img3d)

        return np.expand_dims(img3d, 0)

    def __len__(self):
        return len(self.indices) // self.batch_size

    def __get_data(self, data):
        data = np.array(data)
        images = []
        X = []
        Y = []
        for id in data:
            images.append([self.__load_dicom_images_3d(scan_id=id[0]), id[1]])
        for img in images:
            X.append(img[0])
            Y.append(img[1])
        Y = list(map(int,Y))
        return np.array(X), np.array(Y)

    def __getitem__(self, index):
        print(index)
        data = self.data[index * self.batch_size:(index + 1) * self.batch_size]
        x, y = self.__get_data(data)
       
        return x, y
```

and the 3D CovNet is this:

```python
class MultiBranchCNN(tf.keras.Model):
    def __init__(self):
        super(MultiBranchCNN,self).__init__()
        # self.inputA = tf.keras.Input(shape=(1,256,256,64))

        self.conv3d = Conv3D(64, input_shape=(1,256,256,64),kernel_size=(3, 3,3), activation='relu', padding='same')
        self.maxpool3d = MaxPool3D(pool_size=(3,3, 3))
        self.conv3d2 = Conv3D(64, kernel_size=(3,3, 3), activation='relu', padding='same')
        self.maxpool3d2 = MaxPool3D(pool_size=(3,3 ,3))
        self.conv3d3 = Conv3D(64, kernel_size=(3,3, 3), activation='relu', padding='same')
        self.maxpool3d3 = MaxPool3D(pool_size=(3,3, 3))
        self.Flatten = Flatten()
        self.Dense = Dense(512, activation='relu')
        self.Dropout = Dropout(0.1)
        self.Dense2 = Dense(1, activation='sigmoid')

    def call(self, inputs):
        print(type(inputs))
        # x = self.inputA(inputs)
        x = self.conv3d(inputs)
        x = self.maxpool3d(x)
        x = self.conv3d2(x)
        x = self.maxpool3d2(x)
        x = self.conv3d3(x)
        x = self.maxpool3d3(x)
        x = self.Flatten(x)
        x = self.Dense(x)
        x = self.Dropout(x)
        x = self.Dense2(x)
        return x

```
This error occurs in `Epoch 1/10` (no train happens at all)
I've been trying to change the model architecture and Dataset shape but with no luck.
 
Is this a bug or I am doing something wrong?
Thanks in advance

**Comment by sanatmpa1** [comment]
@makisgrammenos,

Can you take a look at this similar issues [link1](https://github.com/keras-team/keras/issues/9870), [link2](https://github.com/matterport/Mask_RCNN/issues/521) and this [SO thread](https://stackoverflow.com/questions/51704365/tensorflow-check-failed-work-element-count-0/53586477)

**Comment by makisgrammenos** [comment]
Already checked them but nothing helped so far.
 I have added some print functions to help debug this problem int `__getitem__`  (data generator) and  in  `__call__` (model)
here is the updated version

get item
```
   def __getitem__(self, index):
       
        data = self.data[index * self.batch_size:(index + 1) * self.batch_size]
        x, y = self.__get_data(data)
        print(x.shape , y.shape , index)
       
        return x, y
```


call function:
```

def call(self, inputs):
        print(type(inputs))
        print(inputs)
        # x = self.inputA(inputs)
        x = self.conv3d(inputs)
        
        x = self.maxpool3d(x)
        
        x = self.conv3d2(x)
        
        x = self.maxpool3d2(x)
      
        x = self.conv3d3(x)
      
        x = self.maxpool3d3(x)
       
        x = self.Flatten(x)
       
        x = self.Dense(x)
       
        x = self.Dropout(x)
       
        return self.Dense2(x)
```

and here is the output:
```
2021-09-04 17:30:08.821150: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-09-04 17:30:10.758939: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 4628 MB memory:  -> device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:01:00.0, compute capability: 6.1
(4, 1, 256, 256, 64) (4,) 0
<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(
[[[[[0.00025782 0.00025896 0.         ... 0.00019592 0.
     0.        ]
    [0.00025782 0.00025896 0.         ... 0.00019592 0.
     0.        ]
    [0.00025782 0.00025896 0.         ... 0.00019592 0.
     0.        ]
    ...
    [0.00025782 0.00025896 0.         ... 0.00019592 0.
     0.        ]
    [0.00025782 0.00025896 0.         ... 0.00019592 0.
     0.        ]
    [0.00025782 0.00025896 0.         ... 0.00019592 0.
     0.        ]]

   [[0.00025782 0.00025896 0.         ... 0.00019592 0.
     0.        ]
    [0.00025782 0.00025896 0.         ... 0.00019592 0.
     0.        ]
    [0.00025782 0.00025896 0.         ... 0.00019592 0.
     0.        ]
    ...
    [0.00025782 0.00025896 0.         ... 0.00019592 0.
     0.        ]
    [0.00025782 0.00025896 0.         ... 0.00019592 0.
     0.        ]
    [0.00025782 0.00025896 0.         ... 0.00019592 0.
     0.        ]]

   [[0.00025782 0.00025896 0.         ... 0.00019592 0.
     0.        ]
    [0.00025782 0.00025896 0.         ... 0.00019592 0.
     0.        ]
    [0.00025782 0.00025896 0.         ... 0.00019592 0.
     0.        ]
    ...
    [0.00025782 0.00025896 0.         ... 0.00019592 0.
     0.        ]
    [0.00025782 0.00025896 0.         ... 0.00019592 0.
     0.        ]
    [0.00025782 0.00025896 0.         ... 0.00019592 0.
     0.        ]]

   ...

   [[0.00025782 0.00025896 0.         ... 0.00019592 0.
     0.        ]
    [0.00025782 0.00025896 0.         ... 0.00019592 0.
     0.        ]
    [0.00025782 0.00025896 0.         ... 0.00019592 0.
     0.        ]
    ...
    [0.00025782 0.00025896 0.         ... 0.00019592 0.
     0.        ]
    [0.00025782 0.00025896 0.         ... 0.00019592 0.
     0.        ]
    [0.00025782 0.00025896 0.         ... 0.00019592 0.
     0.        ]]

   [[0.00025782 0.00025896 0.         ... 0.00019592 0.
     0.        ]
    [0.00025782 0.00025896 0.         ... 0.00019592 0.
     0.        ]
    [0.00025782 0.00025896 0.         ... 0.00019592 0.
     0.        ]
    ...
    [0.00025782 0.00025896 0.         ... 0.00019592 0.
     0.        ]
    [0.00025782 0.00025896 0.         ... 0.00019592 0.
     0.        ]
    [0.00025782 0.00025896 0.         ... 0.00019592 0.
     0.        ]]

   [[0.00025782 0.00025896 0.         ... 0.00019592 0.
     0.        ]
    [0.00025782 0.00025896 0.         ... 0.00019592 0.
     0.        ]
    [0.00025782 0.00025896 0.         ... 0.00019592 0.
     0.        ]
    ...
    [0.00025782 0.00025896 0.         ... 0.00019592 0.
     0.        ]
    [0.00025782 0.00025896 0.         ... 0.00019592 0.
     0.        ]
    [0.00025782 0.00025896 0.         ... 0.00019592 0.
     0.        ]]]]



 [[[[0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]
    ...
    [0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]]

   [[0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]
    ...
    [0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]]

   [[0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]
    ...
    [0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]]

   ...

   [[0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]
    ...
    [0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]]

   [[0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]
    ...
    [0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]]

   [[0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]
    ...
    [0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]]]]



 [[[[0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]
    ...
    [0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]]

   [[0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]
    ...
    [0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]]

   [[0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]
    ...
    [0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]]

   ...

   [[0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]
    ...
    [0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]]

   [[0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]
    ...
    [0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]]

   [[0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]
    ...
    [0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]
    [0.         0.         0.         ... 0.         0.
     0.        ]]]]



 [[[[0.00016502 0.         0.00016319 ... 0.         0.00019763
     0.        ]
    [0.00016502 0.         0.00016319 ... 0.         0.00019763
     0.        ]
    [0.00016502 0.         0.00016319 ... 0.         0.00019763
     0.        ]
    ...
    [0.00016502 0.         0.00016319 ... 0.         0.00019763
     0.        ]
    [0.00016502 0.         0.00016319 ... 0.         0.00019763
     0.        ]
    [0.00016502 0.         0.00016319 ... 0.         0.00019763
     0.        ]]

   [[0.00016502 0.         0.00016319 ... 0.         0.00019763
     0.        ]
    [0.00016502 0.         0.00016319 ... 0.         0.00019763
     0.        ]
    [0.00016502 0.         0.00016319 ... 0.         0.00019763
     0.        ]
    ...
    [0.00016502 0.         0.00016319 ... 0.         0.00019763
     0.        ]
    [0.00016502 0.         0.00016319 ... 0.         0.00019763
     0.        ]
    [0.00016502 0.         0.00016319 ... 0.         0.00019763
     0.        ]]

   [[0.00016502 0.         0.00016319 ... 0.         0.00019763
     0.        ]
    [0.00016502 0.         0.00016319 ... 0.         0.00019763
     0.        ]
    [0.00016502 0.         0.00016319 ... 0.         0.00019763
     0.        ]
    ...
    [0.00016502 0.         0.00016319 ... 0.         0.00019763
     0.        ]
    [0.00016502 0.         0.00016319 ... 0.         0.00019763
     0.        ]
    [0.00016502 0.         0.00016319 ... 0.         0.00019763
     0.        ]]

   ...

   [[0.00016502 0.         0.00016319 ... 0.         0.00019763
     0.        ]
    [0.00016502 0.         0.00016319 ... 0.         0.00019763
     0.        ]
    [0.00016502 0.         0.00016319 ... 0.         0.00019763
     0.        ]
    ...
    [0.00016502 0.         0.00016319 ... 0.         0.00019763
     0.        ]
    [0.00016502 0.         0.00016319 ... 0.         0.00019763
     0.        ]
    [0.00016502 0.         0.00016319 ... 0.         0.00019763
     0.        ]]

   [[0.00016502 0.         0.00016319 ... 0.         0.00019763
     0.        ]
    [0.00016502 0.         0.00016319 ... 0.         0.00019763
     0.        ]
    [0.00016502 0.         0.00016319 ... 0.         0.00019763
     0.        ]
    ...
    [0.00016502 0.         0.00016319 ... 0.         0.00019763
     0.        ]
    [0.00016502 0.         0.00016319 ... 0.         0.00019763
     0.        ]
    [0.00016502 0.         0.00016319 ... 0.         0.00019763
     0.        ]]

   [[0.00016502 0.         0.00016319 ... 0.         0.00019763
     0.        ]
    [0.00016502 0.         0.00016319 ... 0.         0.00019763
     0.        ]
    [0.00016502 0.         0.00016319 ... 0.         0.00019763
     0.        ]
    ...
    [0.00016502 0.         0.00016319 ... 0.         0.00019763
     0.        ]
    [0.00016502 0.         0.00016319 ... 0.         0.00019763
     0.        ]
    [0.00016502 0.         0.00016319 ... 0.         0.00019763
     0.        ]]]]], shape=(4, 1, 256, 256, 64), dtype=float32)
2021-09-04 17:30:16.534560: I tensorflow/stream_executor/cuda/cuda_dnn.cc:369] Loaded cuDNN version 8100
2021-09-04 17:30:20.413557: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
Epoch 1/10
<class 'tensorflow.python.framework.ops.Tensor'>
Tensor("IteratorGetNext:0", shape=(None, None, None, None, None), dtype=float32)
<class 'tensorflow.python.framework.ops.Tensor'>
Tensor("IteratorGetNext:0", shape=(None, None, None, None, None), dtype=float32)
(4, 1, 256, 256, 64) (4,) 125
2021-09-04 17:30:25.331454: F .\tensorflow/core/util/gpu_launch_config.h:129] Check failed: work_element_count > 0 (0 vs. 0)

(ai) C:\Users\makis\rsna>
```

It seems the tensors with ` shape=(None, None, None, None, None)` are causing the error but I can't figure out why since the data generator returns the batch normaly as it should

**Comment by makisgrammenos** [comment]
Still no solution found.
Anyone  know how to fix it?

**Comment by makisgrammenos** [comment]
After hours of searching it seems that there's a bug in tensorflow when it comes to subclass a model using GPU with this  model architecture.
By using the functional API and the same model architecture everythign seems to work fine and the model trains as it should

**Comment by H0lzm1ch3l** [comment]
I personally experienced this problem due to model.call being called outside the train_step with raw data from a custom data generator. When a model is not yet built you would expect it to be built upon first calling it within the overwritten train_step, however this already happens before that when the data adapter is initialized. This situation can be avoided by either doing preprocessing in the data generator or in the model.call itself.

**Comment by gototophao** [comment]
hello, @makisgrammenos @H0lzm1ch3l  i still cant solve this problem, may i ask how to solve it? i am a new one in tensorflow, and train my autoencoder model with hyperband and big data. Tensorflow always tell me this question.

**Comment by albertz** [comment]
For reference, others report (https://github.com/matterport/Mask_RCNN/issues/521#issuecomment-780459992):

> I had accidentally created a Dense layer with zero "units" (layers in the output)

The error likely originates from sth like that.

**Comment by albertz** [comment]
I have the same crash, with TF 2.3 (https://github.com/rwth-i6/returnn/issues/1190). Here some C++ stacktrace:
```
Thread 12 "python3" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fff917cd700 (LWP 28017)]
0x00007ffff7282438 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff7282438 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff728403a in __GI_abort () at abort.c:89
#2  0x00007fffd9decfe7 in tensorflow::internal::LogMessageFatal::~LogMessageFatal() ()
   from /u/zeyer/.local/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#3  0x00007fffd69a948d in tensorflow::GpuLaunchConfig tensorflow::GetGpuLaunchConfig<void (*)(tensorflow::random::UniformFullIntDistribution<tensorflow::random::PhiloxRandom, unsigned long long>, long long, long long, long long*, unsigned long long*)>(int, Eigen::GpuDevice const&, void (*)(tensorflow::random::UniformFullIntDistribution<tensorflow::random::PhiloxRandom, unsigned long long>, long long, long long, long long*, unsigned long long*), unsigned long, int) ()
   from /u/zeyer/.local/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#4  0x00007fffd69aa3cd in tensorflow::UpdateVariableAndFill_Philox<Eigen::GpuDevice, tensorflow::random::UniformDistribution<tensorflow::random::PhiloxRandom, int> >::operator()(tensorflow::OpKernelContext*, Eigen::GpuDevice const&, tensorflow::random::UniformDistribution<tensorflow::random::PhiloxRandom, int>, tensorflow::UpdateVariableAndFill_Philox_Arg*, int*) ()
   from /u/zeyer/.local/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#5  0x00007fffd69a6369 in tensorflow::Status tensorflow::UpdateVariableAndFill<Eigen::GpuDevice, tensorflow::random::UniformDistribution<tensorflow::random::PhiloxRandom, int> >(tensorflow::OpKernelContext*, tensorflow::random::UniformDistribution<tensorflow::random::PhiloxRandom, int>, int, bool, long long, long long, tensorflow::random::UniformDistribution<tensorflow::random::PhiloxRandom, int>::ResultElementType*) ()
   from /u/zeyer/.local/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#6  0x00007fffd69a64af in void tensorflow::StatefulRandomCompute<Eigen::GpuDevice, tensorflow::random::UniformDistribution<tensorflow::random::PhiloxRandom, int> >(tensorflow::OpKernelContext*, tensorflow::random::UniformDistribution<tensorflow::random::PhiloxRandom, int>, int, int, bool, long long) ()
   from /u/zeyer/.local/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#7  0x00007fffd69a6642 in tensorflow::StatefulUniformIntOp<Eigen::GpuDevice, int>::Compute(tensorflow::OpKernelContext*) () from /u/zeyer/.local/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#8  0x00007fffcb97c65c in tensorflow::BaseGPUDevice::Compute(tensorflow::OpKernel*, tensorflow::OpKernelContext*) () from /u/zeyer/.local/lib/python3.8/site-packages/tensorflow/python/../libtensorflow_framework.so.2
#9  0x00007fffcba402d4 in tensorflow::(anonymous namespace)::ExecutorState<tensorflow::PropagatorState>::Process(tensorflow::PropagatorState::TaggedNode, long long) ()
   from /u/zeyer/.local/lib/python3.8/site-packages/tensorflow/python/../libtensorflow_framework.so.2
#10 0x00007fffcba40d7f in std::_Function_handler<void (), tensorflow::(anonymous namespace)::ExecutorState<tensorflow::PropagatorState>::ScheduleReady(absl::lts_2020_02_25::InlinedVector<tensorflow::PropagatorState::TaggedNode, 8ul, std::allocator<tensorflow::PropagatorState::TaggedNode> >*, tensorflow::PropagatorState::TaggedNodeReadyQueue*)::{lambda()#2}>::_M_invoke(std::_Any_data const&) ()
   from /u/zeyer/.local/lib/python3.8/site-packages/tensorflow/python/../libtensorflow_framework.so.2
#11 0x00007fffcbaecb92 in Eigen::ThreadPoolTempl<tensorflow::thread::EigenEnvironment>::WorkerLoop(int) ()
   from /u/zeyer/.local/lib/python3.8/site-packages/tensorflow/python/../libtensorflow_framework.so.2
#12 0x00007fffcbae9008 in std::_Function_handler<void (), tensorflow::thread::EigenEnvironment::CreateThread(std::function<void ()>)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
   from /u/zeyer/.local/lib/python3.8/site-packages/tensorflow/python/../libtensorflow_framework.so.2
#13 0x00007fffcbada539 in tensorflow::(anonymous namespace)::PThread::ThreadFn(void*) ()
   from /u/zeyer/.local/lib/python3.8/site-packages/tensorflow/python/../libtensorflow_framework.so.2
#14 0x00007ffff761e6ba in start_thread (arg=0x7fff917cd700) at pthread_create.c:333
#15 0x00007ffff735451d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```
So, as you see, it appears in `UniformFullIntDistribution`, so some of the random ops. Likely they were called for some zero shape.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
