### ISSUE TITLE
self.add_weight in custom Keras Layers breaks model saving in TF format

### ISSUE THREAD

**Issue by BearNinja123** [tensorflow/tensorflow#51835]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution: Debian 10
- TensorFlow installed from: binary
- TensorFlow version: 2.5.0
- Python version: 3.7.3

**Describe the current behavior**
I have a model that seems to fail in saving with TF format (.h5 is completely fine) when I call self.add_weight in a custom Keras layer:
```
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Layer, Input
import tensorflow as tf
from model import load_gen

class ResAdd(Layer):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.res_gain = self.add_weight(shape=(), initializer='zeros', trainable=True)

    def call(self, inputs):
        res, skip = inputs
        gain = tf.cast(self.res_gain, res.dtype)
        out = res * gain + skip
        return out 

inp = Input((32, 32, 3)) 
out = ResAdd()([inp, inp])
model = Model(inp, out)

model.save('model')
```

The error states:
```
Traceback (most recent call last):
  File "bring.py", line 23, in <module>
    model.save('model')
  File "/home/tgpu/.local/lib/python3.7/site-packages/keras/engine/training.py", line 2146, in save
    signatures, options, save_traces)
  File "/home/tgpu/.local/lib/python3.7/site-packages/keras/saving/save.py", line 150, in save_model
    signatures, options, save_traces)
  File "/home/tgpu/.local/lib/python3.7/site-packages/keras/saving/saved_model/save.py", line 91, in save
    model, filepath, signatures, options)
  File "/home/tgpu/.local/lib/python3.7/site-packages/tensorflow/python/saved_model/save.py", line 1228, in save_and_return_nodes
    _build_meta_graph(obj, signatures, options, meta_graph_def))
  File "/home/tgpu/.local/lib/python3.7/site-packages/tensorflow/python/saved_model/save.py", line 1399, in _build_meta_graph
    return _build_meta_graph_impl(obj, signatures, options, meta_graph_def)
  File "/home/tgpu/.local/lib/python3.7/site-packages/tensorflow/python/saved_model/save.py", line 1349, in _build_meta_graph_impl
    wrapped_functions)
  File "/home/tgpu/.local/lib/python3.7/site-packages/tensorflow/python/saved_model/save.py", line 200, in __init__
    self._trace_all_concrete_functions()
  File "/home/tgpu/.local/lib/python3.7/site-packages/tensorflow/python/saved_model/save.py", line 289, in _trace_all_concrete_functions
    for obj in self.checkpoint_view.list_objects():
  File "/home/tgpu/.local/lib/python3.7/site-packages/tensorflow/python/training/tracking/graph_view.py", line 460, in list_objects
    trackable_objects, _, _ = self.objects_ids_and_slot_variables()
  File "/home/tgpu/.local/lib/python3.7/site-packages/tensorflow/python/training/tracking/graph_view.py", line 455, in objects_ids_and_slot_variables
    self.objects_ids_and_slot_variables_and_paths())
  File "/home/tgpu/.local/lib/python3.7/site-packages/tensorflow/python/training/tracking/graph_view.py", line 443, in objects_ids_and_slot_variables_and_paths
    object_names[obj] = _object_prefix_from_path(path)
  File "/home/tgpu/.local/lib/python3.7/site-packages/tensorflow/python/training/tracking/graph_view.py", line 64, in _object_prefix_from_path
    for trackable in path_to_root))
  File "/home/tgpu/.local/lib/python3.7/site-packages/tensorflow/python/training/tracking/graph_view.py", line 64, in <genexpr>
    for trackable in path_to_root))
  File "/home/tgpu/.local/lib/python3.7/site-packages/tensorflow/python/training/tracking/graph_view.py", line 57, in _escape_local_name
    return (name.replace(_ESCAPE_CHAR, _ESCAPE_CHAR + _ESCAPE_CHAR)
AttributeError: 'NoneType' object has no attribute 'replace'
```

Note that I fixed this error by replacing:
```
self.res_gain = self.add_weight(shape=(), initializer='zeros', trainable=True)
```
with
```
self.res_gain = tf.Variable(0.0, trainable=True)
```

**Describe the expected behavior**

That the behavior of 
```
self.res_gain = self.add_weight(shape=(), initializer='zeros', trainable=True)
```
is equal to 
```
self.res_gain = tf.Variable(0.0, trainable=True)
```
when initializing a model and that saving the model in TF format won't raise an error

**Comment by sushreebarsa** [comment]
@BearNinja123 Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!
