### ISSUE TITLE
Cannot create interpreter error occurred when test 'On-Device Training in TensorFlow Lite'

### ISSUE THREAD

**Issue by hyeonsu94** [tensorflow/tensorflow#51849]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04.2 LTS
- TensorFlow installation (pip package or built from source): pip package (pip install tf-nightly)
- TensorFlow library (version, if pip package or github SHA, if built from source): 
![image](https://user-images.githubusercontent.com/37358784/132177843-72c65706-a28e-43f2-9ec4-b6285ca12b5f.png)

#### - model & tflite converter
```
import tensorflow as tf

IMG_SIZE = 28

class Model(tf.Module):

  def __init__(self):
    self.model = tf.keras.Sequential([
        tf.keras.layers.Flatten(input_shape=(IMG_SIZE, IMG_SIZE)),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dense(10, activation='softmax')
    ])
    self.model.compile(
        optimizer='sgd',
        loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True),
        metrics=['accuracy'])
    self._LOSS_FN = tf.keras.losses.CategoricalCrossentropy()
    self._OPTIM = tf.optimizers.SGD()

  @tf.function(input_signature=[
      tf.TensorSpec([None, IMG_SIZE, IMG_SIZE], tf.float32),
      tf.TensorSpec([None, 10], tf.float32),
  ])
  def train(self, x, y):
    with tf.GradientTape() as tape:
      prediction = self.model(x)
      loss = self._LOSS_FN(prediction, y)
    gradients = tape.gradient(loss, self.model.trainable_variables)
    self._OPTIM.apply_gradients(
        zip(gradients, self.model.trainable_variables))
    result = {"loss": loss}
    for grad in gradients:
      result[grad.name] = grad
    return result

  @tf.function(input_signature=[tf.TensorSpec([None, IMG_SIZE, IMG_SIZE], tf.float32)])
  def predict(self, x):
    return {
        "output": self.model(x)
    }

  @tf.function(input_signature=[tf.TensorSpec(shape=[], dtype=tf.string)])
  def save(self, checkpoint_path):
    tensor_names = [weight.name for weight in self.model.weights]
    tensors_to_save = [weight.read_value() for weight in self.model.weights]
    tf.raw_ops.Save(
        filename=checkpoint_path, tensor_names=tensor_names,
        data=tensors_to_save, name='save')
    return {
        "checkpoint_path": checkpoint_path
    }

  @tf.function(input_signature=[tf.TensorSpec(shape=[], dtype=tf.string)])
  def restore(self, checkpoint_path):
    restored_tensors = {}
    for var in self.model.weights:
      restored = tf.raw_ops.Restore(
          file_pattern=checkpoint_path, tensor_name=var.name, dt=var.dtype,
          name='restore')
      var.assign(restored)
      restored_tensors[var.name] = restored
    return restored_tensors

SAVED_MODEL_DIR = "saved_model"
m= Model()
tf.saved_model.save(
    m,
    SAVED_MODEL_DIR,
    signatures={
        'train':
            m.train.get_concrete_function(),
        'infer':
            m.predict.get_concrete_function(),
        'save':
            m.save.get_concrete_function(),
        'restore':
            m.restore.get_concrete_function(),
    })

# Convert the model
converter = tf.lite.TFLiteConverter.from_saved_model(SAVED_MODEL_DIR)
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS,  # enable TensorFlow Lite ops.
    tf.lite.OpsSet.SELECT_TF_OPS  # enable TensorFlow ops.
]
converter.experimental_enable_resource_variables = True
tflite_model = converter.convert()
with open('model.tflite','wb') as f:
    f.write(tflite_model)
# Press the green button in the gutter to run the script.
if __name__ == '__main__':
    print("main")
```
#### - android root gradle

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext.kotlin_version = "1.4.32"
    repositories {
        mavenCentral()
        maven {  // Only for snapshot artifacts
            name 'ossrh-snapshot'
            url 'https://oss.sonatype.org/content/repositories/snapshots'
        }
        google()
        jcenter()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:7.0.2"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
#### - android app gradle

```
plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.3"

    defaultConfig {
        applicationId "com.tvstorm.tflitetest"
        minSdkVersion 28
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures {
        mlModelBinding true
    }
}

dependencies {
    implementation('commons-io:commons-io:2.6')
    implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly-SNAPSHOT'
    implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:0.0.0-nightly-SNAPSHOT'
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.6.0'
    implementation 'androidx.appcompat:appcompat:1.3.1'
    implementation 'com.google.android.material:material:1.3.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.0'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
}
```
#### - android activity code

```
class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        runTFLite()
    }

    val NUM_EPOCHS = 100
    val NUM_TRAININGS = 60000
    val trainImages = Array(NUM_TRAININGS) { Array(28) { FloatArray(28) } }
    val trainLabels = Array(NUM_TRAININGS) { FloatArray(10) }

    fun runTFLite() {
        val interpreter = Interpreter(convertInputStreamToFile(resources.openRawResource(R.raw.model)))
        for (i in 0 until NUM_EPOCHS) {
            val inputs: MutableMap<String, Any> = HashMap()
            inputs["x"] = trainImages
            inputs["y"] = trainLabels
            val outputs: MutableMap<String, Any> = HashMap()
            val loss: FloatBuffer = FloatBuffer.allocate(1)
            outputs["loss"] = loss
            interpreter.runSignature(inputs, outputs, "train")
        }
    }

    fun convertInputStreamToFile(inputStream: InputStream): File {
        val tempFile = File.createTempFile(java.lang.String.valueOf(inputStream.hashCode()), ".tmp")
        tempFile.deleteOnExit()
        copyInputStreamToFile(inputStream, tempFile) // commons-io:commons-io
        return tempFile
    }
}
```

### 3. Failure after conversion

We have referenced the article in the link below.
https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/examples/on_device_training/overview.ipynb

A few warnings occurred in the process of creating the tflite model, but they were made. When loading this model in android tflite, the following error log occurs.

#### - Converter side

```
2021-09-06 16:34:59.531193: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.1/lib64
2021-09-06 16:34:59.531227: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1850] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2021-09-06 16:34:59.532327: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-09-06 16:35:01.916373: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
WARNING:absl:Importing a function (__inference_internal_grad_fn_1051) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_internal_grad_fn_1079) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
2021-09-06 16:35:03.747781: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:363] Ignored output_format.
2021-09-06 16:35:03.747821: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:366] Ignored drop_control_dependency.
2021-09-06 16:35:03.747826: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:372] Ignored change_concat_input_ranges.
2021-09-06 16:35:03.749030: I tensorflow/cc/saved_model/reader.cc:43] Reading SavedModel from: saved_model
2021-09-06 16:35:03.752172: I tensorflow/cc/saved_model/reader.cc:107] Reading meta graph with tags { serve }
2021-09-06 16:35:03.752276: I tensorflow/cc/saved_model/reader.cc:148] Reading SavedModel debug info (if present) from: saved_model
2021-09-06 16:35:03.769526: I tensorflow/cc/saved_model/loader.cc:210] Restoring SavedModel bundle.
2021-09-06 16:35:03.815918: I tensorflow/cc/saved_model/loader.cc:194] Running initialization op on SavedModel bundle at path: saved_model
2021-09-06 16:35:03.826002: I tensorflow/cc/saved_model/loader.cc:283] SavedModel load for tags { serve }; Status: success: OK. Took 76975 microseconds.
2021-09-06 16:35:03.861382: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:237] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2021-09-06 16:35:03.957610: W tensorflow/compiler/mlir/lite/flatbuffer_export.cc:1890] TFLite interpreter needs to link Flex delegate in order to run the model since it contains the following Select TFop(s):
Flex ops: FlexBroadcastGradientArgs, FlexReluGrad, FlexRestore, FlexSave
Details:
	tf.BroadcastGradientArgs(tensor<2xi32>, tensor<2xi32>) -> (tensor<?xi32>, tensor<?xi32>) : {device = ""}
	tf.ReluGrad(tensor<?x128xf32>, tensor<?x128xf32>) -> (tensor<?x128xf32>) : {device = ""}
	tf.Restore(tensor<!tf_type.string>, tensor<!tf_type.string>) -> (tensor<*xf32>) : {device = "", preferred_shard = -1 : i64}
	tf.Save(tensor<!tf_type.string>, tensor<4x!tf_type.string>, tensor<784x128xf32>, tensor<128xf32>, tensor<128x10xf32>, tensor<10xf32>) -> () : {device = ""}
See instructions: https://www.tensorflow.org/lite/guide/ops_select
WARNING:absl:Buffer deduplication procedure will be skipped when flatbuffer library is not properly loaded
main
```

#### - mobile side error log

```

2021-09-06 16:23:34.298 18282-18282/com.tvstorm.tflitetest D/AndroidRuntime: Shutting down VM
2021-09-06 16:23:34.298 18282-18282/com.tvstorm.tflitetest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tvstorm.tflitetest, PID: 18282
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tvstorm.tflitetest/com.tvstorm.tflitetest.MainActivity}: java.lang.IllegalArgumentException: Internal error: Cannot create interpreter: Op builtin_code out of range: 142. Are you using old TFLite binary with newer model?
    Registration failed.
    
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3792)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8512)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: java.lang.IllegalArgumentException: Internal error: Cannot create interpreter: Op builtin_code out of range: 142. Are you using old TFLite binary with newer model?
    Registration failed.
    
        at org.tensorflow.lite.NativeInterpreterWrapper.createInterpreter(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:75)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:51)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:227)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:202)
        at com.tvstorm.tflitetest.MainActivity.runTFLite(MainActivity.kt:34)
        at com.tvstorm.tflitetest.MainActivity.onCreate(MainActivity.kt:20)
        at android.app.Activity.performCreate(Activity.java:8198)
        at android.app.Activity.performCreate(Activity.java:8182)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3765)
        	... 11 more
```

**Comment by abattery** [comment]
Could you remove `jcenter()` from the gradle file and depend on the only ossrh-snapshot only?

    repositories {
        google()
        mavenCentral()  // For versioned releases
        maven {         // For snapshot releases
            name 'ossrh-snapshot'
            url 'http://oss.sonatype.org/content/repositories/snapshots'
        }
    }

**Comment by abattery** [comment]
I could reproduce your issue. The jcenter dependency in the build.gradle in your application setting makes the android application depend on the March 31st version of the TensorFlow Lite library.

You can fix the problem by the removal of the `jcenter()` through following the above build.gradle example.

**Comment by raggyie** [comment]
Still experiencing this issue :/ 
java.lang.IllegalArgumentException: Internal error: Cannot create interpreter: Op builtin_code out of range: 142. Are you using old TFLite binary with newer model?

`// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        mavenCentral()
        maven {  // Only for snapshot artifacts
            name 'ossrh-snapshot'
            url 'https://oss.sonatype.org/content/repositories/snapshots'
        }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:7.0.0"
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}`

Please help me out.

**Comment by raggyie** [comment]
###Cannot create interpreter: Op builtin_code out of range: 142. Are you using old TFLite binary with newer model?

Still facing this issue even without jcenter()

Please Help

`// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        mavenCentral()
        maven {  // Only for snapshot artifacts
            name 'ossrh-snapshot'
            url 'https://oss.sonatype.org/content/repositories/snapshots'
        }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:7.0.0"
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}`


> I could reproduce your issue. The jcenter dependency in the build.gradle in your application setting makes the android application depend on the March 31st version of the TensorFlow Lite library.
> 
> You can fix the problem by the removal of the `jcenter()` as the above build.gradle example.
