### ISSUE TITLE
Failed to load the native TensorFlow runtime

### ISSUE THREAD

**Issue by bulgarianboy** [tensorflow/tensorflow#51907]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS 10.9.5
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 2.2.1
- Python version: 3.6.4
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**

I have created a conda env with py 3.6.4 installing several dependencies. I wanted to install tensorflow 2.2.0rc4 but it was not available, instead I did 2.2.1. I got errors from gprcio saying:

```
Building wheels for collected packages: grpcio
  Building wheel for grpcio (setup.py) ...
ERROR: Command errored out with exit status 1:
```
And a huge amount of other messages. Needless to say tf did not install.

I thought I found a workaround by first installing with

`pip3 install --no-cache-dir  --force-reinstall -Iv grpcio==1.24.3`

This succesfully installed and allowed me to succesfully install tf 2.2.1. Or so I thought.

When I try import tensorflow I get these errors

`Traceback (most recent call last):
  File "/Users/nsabherwal/anaconda3/envs/test/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Users/nsabherwal/anaconda3/envs/test/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Users/nsabherwal/anaconda3/envs/test/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/Users/nsabherwal/anaconda3/envs/test/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/nsabherwal/anaconda3/envs/test/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/nsabherwal/anaconda3/envs/test/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _SecKeyCopyExternalRepresentation
  Referenced from: /Users/nsabherwal/anaconda3/envs/test/lib/python3.6/site-packages/tensorflow/python/../libtensorflow_framework.2.dylib
  Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
 in /Users/nsabherwal/anaconda3/envs/test/lib/python3.6/site-packages/tensorflow/python/../libtensorflow_framework.2.dylib

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nsabherwal/anaconda3/envs/test/lib/python3.6/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/Users/nsabherwal/anaconda3/envs/test/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 50, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/nsabherwal/anaconda3/envs/test/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 69, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Users/nsabherwal/anaconda3/envs/test/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Users/nsabherwal/anaconda3/envs/test/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Users/nsabherwal/anaconda3/envs/test/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/Users/nsabherwal/anaconda3/envs/test/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/nsabherwal/anaconda3/envs/test/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/nsabherwal/anaconda3/envs/test/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _SecKeyCopyExternalRepresentation
  Referenced from: /Users/nsabherwal/anaconda3/envs/test/lib/python3.6/site-packages/tensorflow/python/../libtensorflow_framework.2.dylib
  Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
 in /Users/nsabherwal/anaconda3/envs/test/lib/python3.6/site-packages/tensorflow/python/../libtensorflow_framework.2.dylib

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.`

**Describe the expected behavior**

Expect simple install and running of tensorflow.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by tilakrayal** [comment]
@bulgarianboy ,
Could you please update TensorFlow to the latest stable version v2.6 and let us know if you are facing the same error. Thanks!

**Comment by tilakrayal** [comment]
Also please check the tested build [configurations](https://www.tensorflow.org/install/source#gpu) and try to install latest tensorflow version with compatible Cuda and cudnn.Thanks!
