### ISSUE TITLE
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by ArniusOm** [tensorflow/tensorflow#51926]
Hello,
I ran this comand in Conda:

(style-transfer) E:\Python\fast-style-transfer>python evaluate.py --checkpoint ./rain-princess.ckpt --in-path <E:\Python\fast-style-transfer\arnius_gali.jpg> --out-path ./arnius_gali2.jpg

Got this error message:

Traceback (most recent call last):
  File "C:\Users\User\anaconda3\envs\style-transfer\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Python\fast-style-transfer\evaluate.py", line 4, in <module>
    import transform, numpy as np, vgg, pdb, os
  File "E:\Python\fast-style-transfer\src\transform.py", line 1, in <module>
    import tensorflow as tf, pdb
  File "C:\Users\User\anaconda3\envs\style-transfer\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\User\anaconda3\envs\style-transfer\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\User\anaconda3\envs\style-transfer\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "C:\Users\User\anaconda3\envs\style-transfer\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\User\anaconda3\envs\style-transfer\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\User\anaconda3\envs\style-transfer\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.

How can I find out what I did wrong and how to fix it?

Thank you

**Comment by tilakrayal** [comment]
@ArniusOm ,
Can you please take a look at this [comment](https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156) from the issue with similar error.It helps.Also in order to expedite the trouble-shooting process, could you please provide the following information
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
TensorFlow installed from (source or binary):
TensorFlow version:
Python version:
Installed using virtualenv? pip? conda?:
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory:
 
and the exact sequence of commands / steps that you executed before running into the problem.Thanks

**Comment by ArniusOm** [comment]
Hey Tilakrayal, thanks for taking your time.

Here are my specifications:

Windows 10 Pro
Tensor Flow was installed vs most recent Anacoda version
Tensor flow 2.5.0
Python 3.9.6
Installed using Conda
Cudatoolkit 11.0.221
Cudnn 8.2.1
Gpu NVIDIA GeForce GT 1030
2,048 MB GDDR5

Regarding what I ran:

This was the command that I ran:

python evaluate.py --checkpoint ./rain-princess.ckpt --in-path <E:\Python\fast-style-transfer\arnius_gali.jpg> --out-path ./arnius_gali2.jpg

Would appreciate if you could give me some guidance on what to do at this point.

Thank you

**Comment by tilakrayal** [comment]
Glad the suggested above comment worked for you to resolve the issue.Thanks!
