### ISSUE TITLE
Init node head/predictions/class_string_lookup/table_init/LookupTableImportV2 doesn't exist in graph

### ISSUE THREAD

**Issue by fsx950223** [tensorflow/tensorflow#51944]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):debian 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):2.6.0
- Python version:3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
```
2021-09-11 12:21:06.193462: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-09-11 12:21:06.193522: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-09-11 12:21:09.808281: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-09-11 12:21:09.808359: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2021-09-11 12:21:09.808396: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (penguin): /proc/driver/nvidia/version does not exist
2021-09-11 12:21:09.808686: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-09-11 12:21:10.927031: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
2021-09-11 12:21:11.938166: I tensorflow/core/grappler/devices.cc:66] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2021-09-11 12:21:11.938620: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2021-09-11 12:21:11.961714: E tensorflow/core/grappler/grappler_item_builder.cc:669] Init node head/predictions/class_string_lookup/table_init/LookupTableImportV2 doesn't exist in graph
Traceback (most recent call last):
  File "tflite.py", line 29, in <module>
    model = converter.convert()
  File "/home/fsx950223/anaconda3/envs/venv/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 1396, in convert
    return super(TFLiteConverterV2, self).convert()
  File "/home/fsx950223/anaconda3/envs/venv/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 729, in wrapper
    return self._convert_and_export_metrics(convert_func, *args, **kwargs)
  File "/home/fsx950223/anaconda3/envs/venv/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 715, in _convert_and_export_metrics
    result = convert_func(self, *args, **kwargs)
  File "/home/fsx950223/anaconda3/envs/venv/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 1201, in convert
    self._freeze_concrete_function())
  File "/home/fsx950223/anaconda3/envs/venv/lib/python3.6/site-packages/tensorflow/lite/python/convert_phase.py", line 218, in wrapper
    raise error from None  # Re-throws the exception.
  File "/home/fsx950223/anaconda3/envs/venv/lib/python3.6/site-packages/tensorflow/lite/python/convert_phase.py", line 208, in wrapper
    return func(*args, **kwargs)
  File "/home/fsx950223/anaconda3/envs/venv/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 1177, in _freeze_concrete_function
    self._funcs[0], lower_control_flow=False))
  File "/home/fsx950223/anaconda3/envs/venv/lib/python3.6/site-packages/tensorflow/python/framework/convert_to_constants.py", line 1229, in convert_variables_to_constants_v2_as_graph
    aggressive_inlining=aggressive_inlining)
  File "/home/fsx950223/anaconda3/envs/venv/lib/python3.6/site-packages/tensorflow/python/framework/convert_to_constants.py", line 809, in __init__
    aggressive_inlining)
  File "/home/fsx950223/anaconda3/envs/venv/lib/python3.6/site-packages/tensorflow/python/framework/convert_to_constants.py", line 1043, in _run_inline_graph_optimization
    return tf_optimizer.OptimizeGraph(config, meta_graph)
  File "/home/fsx950223/anaconda3/envs/venv/lib/python3.6/site-packages/tensorflow/python/grappler/tf_optimizer.py", line 58, in OptimizeGraph
    graph_id, strip_default_attributes)
ValueError: Failed to import metagraph, check error log for more info.
```
**Describe the expected behavior**
Works same as ```converter = tf.lite.TFLiteConverter.from_saved_model('./saved_model', signature_keys=[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY])```
**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```python
import tensorflow as tf
import tensorflow_text as text
model = tf.saved_model.load('./saved_model')
concrete_func = model.signatures[
    tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY]
concrete_func.inputs[0].set_shape([1])
converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])
# converter = tf.lite.TFLiteConverter.from_saved_model('./saved_model', signature_keys=[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY])
converter.optimizations=[tf.lite.Optimize.DEFAULT]
converter.inference_type=tf.float32
converter.target_spec.supported_ops=[tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
model = converter.convert()
tf.io.write_file('guesslang.tflite', model)
```
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
Saved model: [saved_model.zip](https://github.com/tensorflow/tensorflow/files/7147206/saved_model.zip)

**Comment by abattery** [comment]
Please try out the tf-nightly version. The newer version already fixed this problem.

**Comment by abattery** [comment]
Noted that you need to provide the model object as well in the tf-nightly version.
```converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func], model)```

**Comment by vilmara** [comment]
@google-admin, did you solve this issue?

@abattery, I have a similar issue with TF 2.7, what do you recommend?

`$ saved_model_cli convert --dir saved_model --output_dir /exoeriment/trt --tag_set serve tensorrt`
Error:
`2022-05-04 03:55:24.078820: E tensorflow/core/grappler/grappler_item_builder.cc:670] Init node index_to_string/table_init/LookupTableImportV2 doesn't exist in graph`

**Comment by zhaohb** [comment]
@vilmara @abattery I alse have a similar issue with tf 2.7, I want convert a model(.savedmodel) to tf-trt model.
my code:
```python
import tensorflow as tf
from tensorflow.python.compiler.tensorrt import trt_convert as trt

input_saved_model_dir = '../20220613161603/model.savedmodel/'
conversion_params = trt.DEFAULT_TRT_CONVERSION_PARAMS
conversion_params = conversion_params._replace(precision_mode="FP16")
converter = trt.TrtGraphConverterV2(
    input_saved_model_dir=input_saved_model_dir,
    conversion_params=conversion_params)
converter.convert()
#def my_input_fn():
## Input for a single inference call, for a network that has two input tensors:
#  Inp1 = np.random.normal(size=(8, 16, 16, 3)).astype(np.float32)
#  inp2 = np.random.normal(size=(8, 16, 16, 3)).astype(np.float32)
#  yield (inp1, inp2)
#converter.build(input_fn=my_input_fn)
converter.save(output_saved_model_dir)

saved_model_loaded = tf.saved_model.load(
    output_saved_model_dir, tags=[tag_constants.SERVING])
graph_func = saved_model_loaded.signatures[
    signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY]
output = graph_func(input_data)[0].numpy()
```

how to solve that issue? thank you very much.

**Comment by momodagithub** [comment]
also meet the problem ,when  i use  
python -m tf2onnx.convert --saved-model ./export_model/1741258661   --output multi_class.onnx  --large_model
to convert a model to onnx , i get:
2025-03-06 20:06:36.789083: E tensorflow/core/grappler/grappler_item_builder.cc:670] Init node dense_features_1/actor_education_offline_X_receiver_education_offline_embedding_1/actor_education_offline_lookup/hash_table/table_init/LookupTableImportV2 doesn't exist in graph
...................................................
ValueError: Failed to import metagraph, check error log for more info.

so how to solve it?
my tensorflow version is tf2.8
the pb is got by the estimator  export_saved_model

I guess the reason is i use hash bucket in the feature column input layer
but i do not konw how to solve it
