### ISSUE TITLE
GPU delegate problems in tensorflow-lite in android studio

### ISSUE THREAD

**Issue by yanzxcasdqwe** [tensorflow/tensorflow#52061]
hello everyone! I'm new in the community so please bear with me. I would like to get some help with my problem that I've been stuck in for a while now. I get an error when I run my app in android studio and through my mobile phone. I am following ElectroCode's tutorial videos in making sign language recognition app on youtube.

This is my error log:

		E/AndroidRuntime: FATAL EXCEPTION: Thread-4
		    Process: com.example.imagepro, PID: 7161
		    java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: Next operations are not supported by GPU delegate:
		    CUSTOM TFLite_Detection_PostProcess: Operation is not supported.
		    First 98 operations will run on the GPU, and the remaining 1 on the CPU.
		    OpenCL library not loaded - dlopen failed: library "libOpenCL-pixel.so" not found
		    Falling back to OpenGL
		    TfLiteGpuDelegate Invoke: ToTensorConverter: input data size does not match expected size.
		       Node number 99 (TfLiteGpuDelegateV2) failed to invoke.
    
	        	at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
	        	at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:163)
	        	at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:360)
	        	at com.example.imagepro.objectDetectorClass.recognizeImage(objectDetectorClass.java:159)
	        	at com.example.imagepro.CameraActivity.onCameraFrame(CameraActivity.java:130)
		        at org.opencv.android.CameraBridgeViewBase.deliverAndDrawFrame(CameraBridgeViewBase.java:392)
		        at org.opencv.android.JavaCameraView$CameraWorker.run(JavaCameraView.java:373)
	 	       at java.lang.Thread.run(Thread.java:929)
		D/CameraBridge: call checkCurrentState

**Comment by mohantym** [comment]
Hi @yanzxcasdqwe ! 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced].Thanks!
