### ISSUE TITLE
Cannot load saved tf model (AttributeError: '_UserObject' object has no attribute 'add_slot')

### ISSUE THREAD

**Issue by daniel-kukiela** [tensorflow/tensorflow#52091]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04 LTS
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.6.0
- Python version: 3.9
- CUDA/cuDNN version: 11.3/8.2.1
- GPU model and memory: RTX 8000, 48 GB

**Describe the current behavior**
I'm loading our upsample model and saving it as a saved model:
```py
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow_addons.layers import InstanceNormalization, SpectralNormalization

model = load_model('upsample---[_20]---[______3171]---[_____63420].h5', custom_objects={'InstanceNormalization': InstanceNormalization, 'SpectralNormalization': SpectralNormalization})

tf.saved_model.save(model, 'upsample_saved_model')
```
Then, when I'm trying to load it (do not use the same runtime if running in Collab):
```py
import tensorflow as tf

model = tf.saved_model.load('upsample_saved_model')
```
It errors with:
```
Traceback (most recent call last):
  File "/home/daniel/trt/2_find_layer_names.py", line 4, in <module>
    model = tf.saved_model.load('upsample_saved_model')
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/python/saved_model/load.py", line 864, in load
    result = load_internal(export_dir, tags, options)["root"]
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/python/saved_model/load.py", line 902, in load_internal
    loader = loader_cls(object_graph_proto, saved_model_proto, export_dir,
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/python/saved_model/load.py", line 162, in __init__
    self._load_all()
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/python/saved_model/load.py", line 259, in _load_all
    self._load_nodes()
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/python/saved_model/load.py", line 448, in _load_nodes
    slot_variable = optimizer_object.add_slot(
AttributeError: '_UserObject' object has no attribute 'add_slot'
```

The same code works just fine in TensorFlow 2.5.

If you need the model to test: https://github.com/Sentdex/GANTheftAuto/tree/main/trained_models (it's the upsample one).

**Describe the expected behavior**
This should not error and load the model like in TensorFlow 2.5

**Standalone code to reproduce the issue**
As described above.

Additionally, I mentioned this issue here: https://github.com/tensorflow/tensorflow/issues/52013#issuecomment-920475505 and 
mohantym created a notebook and ran it in Collab: https://colab.research.google.com/gist/mohantym/187d7a2dc387998237211d7c590c6b1a/github_52013_sentdex.ipynb - you can replicate the issue in this notebook too, but after downloading/installing all the dependencies, then loading the model and saving it as the saved model, use Runtime -> Restart runtime before attempting to load saved model, otherwise this bug is not going to be triggered.

**Comment by mohantym** [comment]
Hi @daniel-kukiela !Could you please try again  Python 3.7/3.8? Tried to replicate in [2.5](https://colab.research.google.com/gist/mohantym/de39207fdedadde6861bf60eae50f9b5/github_52013_sentdex.ipynb#scrollTo=AwimBoSxRdv8),[2.6](https://colab.research.google.com/gist/mohantym/187d7a2dc387998237211d7c590c6b1a/github_52013_sentdex.ipynb#scrollTo=x0Jbyu8RaJpP) and [2.7](https://colab.research.google.com/gist/mohantym/6d58b25b5dc4fa20239b9729806d77cc/github_52013_sentdex.ipynb#scrollTo=J-mTHl22UhJv) .Thanks!

**Comment by daniel-kukiela** [comment]
@mohantym I mentioned twice (one in this other issue and once here) that you cannot load the save modes in the current runtime. You need to load it in fresh runtime (for example by invoking Runtime -> Restart runtime). When you are running it in the same runtime that you used to save the model (like if you run it all in a single script), this bug does not trigger. By restartting runtime you are loading a model like from a separate script, and then this bug occurs.

I ran your TF 2.6 notebook in Collab, but restarted runtime before loading the model (as in my steps to reproduce in Collab):
![image](https://user-images.githubusercontent.com/4561245/134351979-31581182-fa1f-4b0f-8732-72832b65effd.png)

Can you please follow my steps to replicate it under TF 2.6? TF 2.5 works ok.

**Comment by daniel-kukiela** [comment]
Hmm, I checked your TF 2.7 nightly notebook and the issue seems to be gone there. It is possible that someone already found this bug and fixed it then.

Sounds like we should consider it fixed in TF 2.7 then?


Thank you

**Comment by mohantym** [comment]
Thanks @daniel-kukiela for confirming the same .Feel free to close the issue if it is fixed in nightly.
