### ISSUE TITLE
libtensorflowlite.so building problem tf2.3

### ISSUE THREAD

**Issue by YongyuG** [tensorflow/tensorflow#52103]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): source
- TensorFlow version: r2.3
- Python version: 3.7
- Installed using virtualenv? pip? conda?: no
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): 5.5
- CUDA/cuDNN version: 10.2
- GPU model and memory: 1080ti

**Describe the problem**
I am going to build **libtensorflowlite.so** for raspberry pi 3b using `bazel build --config=elinux_armhf -c opt //tensorflow/lite:libtensorflowlite.so `.
However,  I get the error as shown bellow, I dont know how to fix that proble, it seems like like cross-compile toolchains errors `Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '@local_config_embedded_arm//:aarch64_toolchain_config BuildConfigurationValue.Key[6b681d7708c478d1cd948cd10629a4e4fb7eb97326825b5498e94f895f792b01] false' (requested by nodes '@local_config_embedded_arm//:cc-compiler-aarch64 BuildConfigurationValue.Key[6b681d7708c478d1cd948cd10629a4e4fb7eb97326825b5498e94f895f792b01] false'),` I have tried several ways to download ruy btw,  but still cannot get the bazel build works
**Provide the exact sequence of commands / steps that you executed before running into the problem**
1.  I put the following into **tensorflow/lite/BUILD**

```
cc_binary(
    name="libtensorflowLite.so",
    linkopts=[
        "-shared",
        "-Wl,-soname=libtensorflowLite.so"
    ],
    linkshared = 1,
    copts = tflite_copts(),
    deps=[
        ":framework",
        "//tensorflow/lite/kernels:builtin_ops"
    ]
)
```

2.  `bazel build --config=elinux_armhf -c opt //tensorflow/lite:libtensorflowlite.so
`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=211
INFO: Reading rc options for 'build' from /home/yckj1497/tf_23/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/yckj1497/tf_23/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=v2
INFO: Reading rc options for 'build' from /home/yckj1497/tf_23/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/home/yckj2211/anaconda3/bin/python3 --action_env PYTHON_LIB_PATH=/home/yckj2211/anaconda3/lib/python3.6/site-packages --python_path=/home/yckj2211/anaconda3/bin/python3 --config=xla --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:v2 in file /home/yckj1497/tf_23/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file /home/yckj1497/tf_23/tensorflow/.bazelrc: --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true
INFO: Found applicable config definition build:elinux_armhf in file /home/yckj1497/tf_23/tensorflow/.bazelrc: --config=elinux --cpu=armhf
INFO: Found applicable config definition build:elinux in file /home/yckj1497/tf_23/tensorflow/.bazelrc: --crosstool_top=@local_config_embedded_arm//:toolchain --host_crosstool_top=@bazel_tools//tools/cpp:toolchain
INFO: Found applicable config definition build:linux in file /home/yckj1497/tf_23/tensorflow/.bazelrc: --copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
INFO: Found applicable config definition build:dynamic_kernels in file /home/yckj1497/tf_23/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
INFO: Repository ruy instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule third_party_http_archive defined at:
  /home/yckj1497/tf_23/tensorflow/third_party/repo.bzl:223:28: in <toplevel>
ERROR: An error occurred during the fetch of repository 'ruy':
   java.io.IOException: thread interrupted
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '@local_config_embedded_arm//:aarch64_toolchain_config BuildConfigurationValue.Key[6b681d7708c478d1cd948cd10629a4e4fb7eb97326825b5498e94f895f792b01] false' (requested by nodes '@local_config_embedded_arm//:cc-compiler-aarch64 BuildConfigurationValue.Key[6b681d7708c478d1cd948cd10629a4e4fb7eb97326825b5498e94f895f792b01] false')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:515)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1040)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
Caused by: java.lang.IllegalStateException: com.google.protobuf.TextFormat$ParseException: 10:13: Invalid escape sequence: '\y'
	at com.google.devtools.build.lib.rules.cpp.CppActionConfigs.getLegacyFeatures(CppActionConfigs.java:983)
	at com.google.devtools.build.lib.rules.cpp.CcModule.ccToolchainConfigInfoFromSkylark(CcModule.java:902)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.devtools.build.lib.syntax.MethodDescriptor.call(MethodDescriptor.java:130)
	at com.google.devtools.build.lib.syntax.BuiltinCallable.fastcall(BuiltinCallable.java:73)
	at com.google.devtools.build.lib.syntax.Starlark.fastcall(Starlark.java:359)
	at com.google.devtools.build.lib.syntax.Eval.doEval(Eval.java:588)
	at com.google.devtools.build.lib.syntax.Eval.eval(Eval.java:423)
	at com.google.devtools.build.lib.syntax.Eval.doEval(Eval.java:674)
	at com.google.devtools.build.lib.syntax.Eval.eval(Eval.java:423)
	at com.google.devtools.build.lib.syntax.Eval.execReturn(Eval.java:215)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:259)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:231)
	at com.google.devtools.build.lib.syntax.Eval.execStatements(Eval.java:53)
	at com.google.devtools.build.lib.syntax.Eval.execFunctionBody(Eval.java:37)
	at com.google.devtools.build.lib.syntax.StarlarkFunction.fastcall(StarlarkFunction.java:115)
	at com.google.devtools.build.lib.syntax.Starlark.fastcall(Starlark.java:359)
	at com.google.devtools.build.lib.syntax.Starlark.call(Starlark.java:334)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.buildRule(SkylarkRuleConfiguredTargetUtil.java:136)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:468)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:190)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:888)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:899)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:338)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
	... 7 more
Caused by: com.google.protobuf.TextFormat$ParseException: 10:13: Invalid escape sequence: '\y'
	at com.google.protobuf.TextFormat$Tokenizer.parseException(TextFormat.java:1238)
	at com.google.protobuf.TextFormat$Tokenizer.consumeByteString(TextFormat.java:1228)
	at com.google.protobuf.TextFormat$Tokenizer.consumeByteString(TextFormat.java:1200)
	at com.google.protobuf.TextFormat$Tokenizer.consumeString(TextFormat.java:1181)
	at com.google.protobuf.TextFormat$Parser.consumeFieldValue(TextFormat.java:1987)
	at com.google.protobuf.TextFormat$Parser.consumeFieldValues(TextFormat.java:1877)
	at com.google.protobuf.TextFormat$Parser.mergeField(TextFormat.java:1823)
	at com.google.protobuf.TextFormat$Parser.consumeFieldValue(TextFormat.java:1944)
	at com.google.protobuf.TextFormat$Parser.consumeFieldValues(TextFormat.java:1877)
	at com.google.protobuf.TextFormat$Parser.mergeField(TextFormat.java:1812)
	at com.google.protobuf.TextFormat$Parser.consumeFieldValue(TextFormat.java:1944)
	at com.google.protobuf.TextFormat$Parser.consumeFieldValues(TextFormat.java:1877)
	at com.google.protobuf.TextFormat$Parser.mergeField(TextFormat.java:1812)
	at com.google.protobuf.TextFormat$Parser.mergeField(TextFormat.java:1689)
	at com.google.protobuf.TextFormat$Parser.merge(TextFormat.java:1675)
	at com.google.protobuf.TextFormat$Parser.merge(TextFormat.java:1566)
	at com.google.protobuf.TextFormat.merge(TextFormat.java:1370)
	at com.google.devtools.build.lib.rules.cpp.CppActionConfigs.getFeature(CppActionConfigs.java:1594)
	at com.google.devtools.build.lib.rules.cpp.CppActionConfigs.getLegacyFeatures(CppActionConfigs.java:413)
	... 34 more

INFO: Elapsed time: 24.924s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (41 packages loaded, 251 targets configured)
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '@local_config_embedded_arm//:aarch64_toolchain_config BuildConfigurationValue.Key[6b681d7708c478d1cd948cd10629a4e4fb7eb97326825b5498e94f895f792b01] false' (requested by nodes '@local_config_embedded_arm//:cc-compiler-aarch64 BuildConfigurationValue.Key[6b681d7708c478d1cd948cd10629a4e4fb7eb97326825b5498e94f895f792b01] false')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:515)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1040)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
Caused by: java.lang.IllegalStateException: com.google.protobuf.TextFormat$ParseException: 10:13: Invalid escape sequence: '\y'
	at com.google.devtools.build.lib.rules.cpp.CppActionConfigs.getLegacyFeatures(CppActionConfigs.java:983)
	at com.google.devtools.build.lib.rules.cpp.CcModule.ccToolchainConfigInfoFromSkylark(CcModule.java:902)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.devtools.build.lib.syntax.MethodDescriptor.call(MethodDescriptor.java:130)
	at com.google.devtools.build.lib.syntax.BuiltinCallable.fastcall(BuiltinCallable.java:73)
	at com.google.devtools.build.lib.syntax.Starlark.fastcall(Starlark.java:359)
	at com.google.devtools.build.lib.syntax.Eval.doEval(Eval.java:588)
	at com.google.devtools.build.lib.syntax.Eval.eval(Eval.java:423)
	at com.google.devtools.build.lib.syntax.Eval.doEval(Eval.java:674)
	at com.google.devtools.build.lib.syntax.Eval.eval(Eval.java:423)
	at com.google.devtools.build.lib.syntax.Eval.execReturn(Eval.java:215)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:259)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:231)
	at com.google.devtools.build.lib.syntax.Eval.execStatements(Eval.java:53)
	at com.google.devtools.build.lib.syntax.Eval.execFunctionBody(Eval.java:37)
	at com.google.devtools.build.lib.syntax.StarlarkFunction.fastcall(StarlarkFunction.java:115)
	at com.google.devtools.build.lib.syntax.Starlark.fastcall(Starlark.java:359)
	at com.google.devtools.build.lib.syntax.Starlark.call(Starlark.java:334)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.buildRule(SkylarkRuleConfiguredTargetUtil.java:136)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:468)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:190)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:888)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:899)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:338)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
	... 7 more
Caused by: com.google.protobuf.TextFormat$ParseException: 10:13: Invalid escape sequence: '\y'
	at com.google.protobuf.TextFormat$Tokenizer.parseException(TextFormat.java:1238)
	at com.google.protobuf.TextFormat$Tokenizer.consumeByteString(TextFormat.java:1228)
	at com.google.protobuf.TextFormat$Tokenizer.consumeByteString(TextFormat.java:1200)
	at com.google.protobuf.TextFormat$Tokenizer.consumeString(TextFormat.java:1181)
	at com.google.protobuf.TextFormat$Parser.consumeFieldValue(TextFormat.java:1987)
	at com.google.protobuf.TextFormat$Parser.consumeFieldValues(TextFormat.java:1877)
	at com.google.protobuf.TextFormat$Parser.mergeField(TextFormat.java:1823)
	at com.google.protobuf.TextFormat$Parser.consumeFieldValue(TextFormat.java:1944)
	at com.google.protobuf.TextFormat$Parser.consumeFieldValues(TextFormat.java:1877)
	at com.google.protobuf.TextFormat$Parser.mergeField(TextFormat.java:1812)
	at com.google.protobuf.TextFormat$Parser.consumeFieldValue(TextFormat.java:1944)
	at com.google.protobuf.TextFormat$Parser.consumeFieldValues(TextFormat.java:1877)
	at com.google.protobuf.TextFormat$Parser.mergeField(TextFormat.java:1812)
	at com.google.protobuf.TextFormat$Parser.mergeField(TextFormat.java:1689)
	at com.google.protobuf.TextFormat$Parser.merge(TextFormat.java:1675)
	at com.google.protobuf.TextFormat$Parser.merge(TextFormat.java:1566)
	at com.google.protobuf.TextFormat.merge(TextFormat.java:1370)
	at com.google.devtools.build.lib.rules.cpp.CppActionConfigs.getFeature(CppActionConfigs.java:1594)
	at com.google.devtools.build.lib.rules.cpp.CppActionConfigs.getLegacyFeatures(CppActionConfigs.java:413)
	... 34 more
java.lang.RuntimeException: Unrecoverable error while evaluating node '@local_config_embedded_arm//:aarch64_toolchain_config BuildConfigurationValue.Key[6b681d7708c478d1cd948cd10629a4e4fb7eb97326825b5498e94f895f792b01] false' (requested by nodes '@local_config_embedded_arm//:cc-compiler-aarch64 BuildConfigurationValue.Key[6b681d7708c478d1cd948cd10629a4e4fb7eb97326825b5498e94f895f792b01] false')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:515)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1040)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
Caused by: java.lang.IllegalStateException: com.google.protobuf.TextFormat$ParseException: 10:13: Invalid escape sequence: '\y'
	at com.google.devtools.build.lib.rules.cpp.CppActionConfigs.getLegacyFeatures(CppActionConfigs.java:983)
	at com.google.devtools.build.lib.rules.cpp.CcModule.ccToolchainConfigInfoFromSkylark(CcModule.java:902)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.devtools.build.lib.syntax.MethodDescriptor.call(MethodDescriptor.java:130)
	at com.google.devtools.build.lib.syntax.BuiltinCallable.fastcall(BuiltinCallable.java:73)
	at com.google.devtools.build.lib.syntax.Starlark.fastcall(Starlark.java:359)
	at com.google.devtools.build.lib.syntax.Eval.doEval(Eval.java:588)
	at com.google.devtools.build.lib.syntax.Eval.eval(Eval.java:423)
	at com.google.devtools.build.lib.syntax.Eval.doEval(Eval.java:674)
	at com.google.devtools.build.lib.syntax.Eval.eval(Eval.java:423)
	at com.google.devtools.build.lib.syntax.Eval.execReturn(Eval.java:215)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:259)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:231)
	at com.google.devtools.build.lib.syntax.Eval.execStatements(Eval.java:53)
	at com.google.devtools.build.lib.syntax.Eval.execFunctionBody(Eval.java:37)
	at com.google.devtools.build.lib.syntax.StarlarkFunction.fastcall(StarlarkFunction.java:115)
	at com.google.devtools.build.lib.syntax.Starlark.fastcall(Starlark.java:359)
	at com.google.devtools.build.lib.syntax.Starlark.call(Starlark.java:334)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.buildRule(SkylarkRuleConfiguredTargetUtil.java:136)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:468)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:190)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:888)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:899)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:338)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
	... 7 more
Caused by: com.google.protobuf.TextFormat$ParseException: 10:13: Invalid escape sequence: '\y'
	at com.google.protobuf.TextFormat$Tokenizer.parseException(TextFormat.java:1238)
	at com.google.protobuf.TextFormat$Tokenizer.consumeByteString(TextFormat.java:1228)
	at com.google.protobuf.TextFormat$Tokenizer.consumeByteString(TextFormat.java:1200)
	at com.google.protobuf.TextFormat$Tokenizer.consumeString(TextFormat.java:1181)
	at com.google.protobuf.TextFormat$Parser.consumeFieldValue(TextFormat.java:1987)
	at com.google.protobuf.TextFormat$Parser.consumeFieldValues(TextFormat.java:1877)
	at com.google.protobuf.TextFormat$Parser.mergeField(TextFormat.java:1823)
	at com.google.protobuf.TextFormat$Parser.consumeFieldValue(TextFormat.java:1944)
	at com.google.protobuf.TextFormat$Parser.consumeFieldValues(TextFormat.java:1877)
	at com.google.protobuf.TextFormat$Parser.mergeField(TextFormat.java:1812)
	at com.google.protobuf.TextFormat$Parser.consumeFieldValue(TextFormat.java:1944)
	at com.google.protobuf.TextFormat$Parser.consumeFieldValues(TextFormat.java:1877)
	at com.google.protobuf.TextFormat$Parser.mergeField(TextFormat.java:1812)
	at com.google.protobuf.TextFormat$Parser.mergeField(TextFormat.java:1689)
	at com.google.protobuf.TextFormat$Parser.merge(TextFormat.java:1675)
	at com.google.protobuf.TextFormat$Parser.merge(TextFormat.java:1566)
	at com.google.protobuf.TextFormat.merge(TextFormat.java:1370)
	at com.google.devtools.build.lib.rules.cpp.CppActionConfigs.getFeature(CppActionConfigs.java:1594)
	at com.google.devtools.build.lib.rules.cpp.CppActionConfigs.getLegacyFeatures(CppActionConfigs.java:413)
FAILED: Build did NOT complete successfully (41 packages loaded, 251 targets configured)

```

**Comment by YongyuG** [comment]
and how to get the bazel build work if i download the third_party packages mannually and unzip it in **~/.cache/bazel/_bazel_AD\xxx/xxx/external/{third_party_name}**

**Comment by mohantym** [comment]
Hi @jvishnuvardhan ! ,Could you please look at this issue?

**Comment by thaink** [comment]
There is a rule named "tensorflowlite" in tensorflow/lite/BUILD.
I wonder why do you need to add your own rule?

**Comment by YongyuG** [comment]
> There is a rule named "tensorflowlite" in tensorflow/lite/BUILD. I wonder why do you need to add your own rule?

same issues occur for `bazel build --config=elinux_armhf -c opt //tensorflow/lite:tensorflowlite`

**Comment by mohantym** [comment]
Hi @YongyuG ! I was able to build above file with following config in lite/build as add-on. Attaching [gist](https://colab.sandbox.google.com/gist/mohantym/59e9e4da38295aff8c8f4c06a96e65fc/tensorflow-ranking.ipynb#scrollTo=ehy9T_FxySK6) for reference . Thanks!
```
cc_library(             // you can check with cc_binary too. 
    name="libtensorflowLite.so",
    linkopts=[
        "-shared",
        "-Wl,-soname=libtensorflowLite.so"
    ],
   
    copts = tflite_copts(),
    deps=[
        ":framework",
        "//tensorflow/lite/kernels:builtin_ops"
    ]
)
```
