### ISSUE TITLE
Saving customized RNN model, got error of "Tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError"

### ISSUE THREAD

**Issue by haozh7109** [tensorflow/tensorflow#52121]
**System information**
- I have written the customized simple RNN model based on TF layers:
- OS Platform and Distribution: Windows 10 
- TensorFlow installed from (source or binary): TF2.6 
- TensorFlow version (use command below): v2.6.0-rc2-32-g919f693420e 2.6.0
- Python version: Python 3.7.11
- CUDA/cuDNN version: 11.4
- GPU model and memory: NVIDIA TITAN RTX 24 G

**Describe the current behavior**
v2.6.0-rc2-32-g919f693420e 2.6.0

**Describe the expected behavior**
I have implemented a simple RNN model by using customized layers. The model is running ok with the eager execution and graph execution in the stage of the model building. However, while I tried to save the generated dummy model, I got the following error: 

 "tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed: AutoGraph did convert this function. This might indicate you are trying to use an unsupported feature." 

**Standalone code to reproduce the issue:** 

import tensorflow as tf
import numpy as np
from tensorflow.keras.layers import Layer
from tensorflow.python.framework.ops import disable_eager_execution

##### ------- (1)  check if the eager execution is used -----

non_eager_execution = False
if non_eager_execution:
    tf.compat.v1.disable_eager_execution()
else:
    tf.config.run_functions_eagerly(True)

print("Eager execution is: " + str(tf.executing_eagerly()))

##### ------- (2)   define the customized RNN layer -----

class RNN_simple_layer(Layer):

    def __init__(self, neurons_numbers, return_sequences=False,**kwargs):
        super(RNN_simple_layer, self).__init__()
        self.neurons_numbers  = neurons_numbers
        self.return_sequences = return_sequences

    def build(self, input_shape):
        self.kernel_input = self.add_weight('kernel_input', shape=[int(input_shape[-1]), self.neurons_numbers], initializer="random_normal",trainable=True)
        self.kernel_state = self.add_weight('kernel_state', shape=[self.neurons_numbers,self.neurons_numbers], initializer="random_normal",trainable=True)
        self.bias = self.add_weight('bias', shape=[self.neurons_numbers,],initializer="zeros",trainable=True)

    def call(self, inputs):

        sequence_length = inputs.shape[-2]

        # outputs = []
        outputs = tf.TensorArray(tf.float32, size=sequence_length)
        states  = tf.TensorArray(tf.float32, size=sequence_length)
        inital_states  = tf.zeros(shape=[tf.shape(inputs)[0],self.neurons_numbers])

        states = inital_states
        for i_step in tf.range(sequence_length):
            output_i_step = tf.tanh(tf.matmul(inputs[:,i_step,:],self.kernel_input) + tf.matmul(states, self.kernel_state) + self.bias)
            states        = output_i_step
            outputs = outputs.write(i_step,output_i_step)

        # output the RNN resuts
        if self.return_sequences == True:
            output = tf.transpose(outputs.stack(), [1,0,2])
        else:
            output = outputs.stack()[-1]
        return output

    def get_config(self):
        config = super().get_config()
        config.update({
            'neurons_numbers': self.neurons_numbers,
            'return_sequences': self.return_sequences
        })
        return config

##### ------- (3)   Test the customized simple RNN layer-----

RNN_layer    = RNN_simple_layer(4,return_sequences=True)
input_array  = tf.ones((32,10,8))
output_array = RNN_layer(input_array)

print('RNN input tensor shape:' + str(input_array.shape))
print('RNN input tensor has batch size:' + str(input_array.shape[0]))
print('RNN input tensor has time samples:' + str(input_array.shape[-2]))
print('RNN input tensor has features of each sample:' + str(input_array.shape[-1]))
print('RNN output tensor shape:' + str(output_array.shape))

##### ------- (4)   build a dummy Tensorflow model-----

inputs  = tf.keras.Input(shape=(10,20))
x       = tf.keras.layers.Conv1D(10,3)(inputs)
x       = RNN_simple_layer(4,return_sequences=True)(x)
outputs = tf.keras.layers.Dense(30, activation="relu")(x)

model = tf.keras.Model(inputs=inputs, outputs=outputs, name="test_model")
model.summary()

##### ------- (5)   save the customized dummy model-----
model.save('Model_simple_RNN')

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Eager execution is: True
RNN input tensor shape:(32, 10, 8)
RNN input tensor has batch size:32
RNN input tensor has time samples:10
RNN input tensor has features of each sample:8
RNN output tensor shape:(32, 10, 4)
Model: "test_model"

#####  =================================================================
Total params: 820
Trainable params: 820
Non-trainable params: 0
_________________________________________________________________

model.save('Model_simple_RNN')
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
Traceback (most recent call last):
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\IPython\core\interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-6d9b393b5457>", line 1, in <module>
    model.save('Model_simple_RNN')
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\keras\engine\training.py", line 2146, in save
    signatures, options, save_traces)
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\keras\saving\save.py", line 150, in save_model
    signatures, options, save_traces)
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\keras\saving\saved_model\save.py", line 91, in save
    model, filepath, signatures, options)
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\tensorflow\python\saved_model\save.py", line 1228, in save_and_return_nodes
    _build_meta_graph(obj, signatures, options, meta_graph_def))
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\tensorflow\python\saved_model\save.py", line 1399, in _build_meta_graph
    return _build_meta_graph_impl(obj, signatures, options, meta_graph_def)
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\tensorflow\python\saved_model\save.py", line 1336, in _build_meta_graph_impl
    checkpoint_graph_view)
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\tensorflow\python\saved_model\signature_serialization.py", line 99, in find_function_to_export
    functions = saveable_view.list_functions(saveable_view.root)
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\tensorflow\python\saved_model\save.py", line 164, in list_functions
    self._serialization_cache)
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\keras\engine\training.py", line 2813, in _list_functions_for_serialization
    Model, self)._list_functions_for_serialization(serialization_cache)
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\keras\engine\base_layer.py", line 3086, in _list_functions_for_serialization
    .list_functions_for_serialization(serialization_cache))
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\keras\saving\saved_model\base_serialization.py", line 93, in list_functions_for_serialization
    fns = self.functions_to_serialize(serialization_cache)
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\keras\saving\saved_model\layer_serialization.py", line 74, in functions_to_serialize
    serialization_cache).functions_to_serialize)
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\keras\saving\saved_model\layer_serialization.py", line 90, in _get_serialized_attributes
    serialization_cache)
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\keras\saving\saved_model\model_serialization.py", line 57, in _get_serialized_attributes_internal
    serialization_cache))
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\keras\saving\saved_model\layer_serialization.py", line 99, in _get_serialized_attributes_internal
    functions = save_impl.wrap_layer_functions(self.obj, serialization_cache)
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\keras\saving\saved_model\save_impl.py", line 197, in wrap_layer_functions
    fn.get_concrete_function()
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\contextlib.py", line 119, in __exit__
    next(self.gen)
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\keras\saving\saved_model\save_impl.py", line 359, in tracing_scope
    fn.get_concrete_function(*args, **kwargs)
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\tensorflow\python\eager\def_function.py", line 1233, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\tensorflow\python\eager\def_function.py", line 1213, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\tensorflow\python\eager\def_function.py", line 760, in _initialize
    *args, **kwds))
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\tensorflow\python\eager\function.py", line 3066, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\tensorflow\python\eager\function.py", line 3463, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\tensorflow\python\eager\function.py", line 3308, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\tensorflow\python\framework\func_graph.py", line 1007, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\tensorflow\python\eager\def_function.py", line 668, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\keras\saving\saved_model\save_impl.py", line 572, in wrapper
    ret = method(*args, **kwargs)
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\keras\saving\saved_model\utils.py", line 166, in wrap_with_training_arg
    lambda: replace_training_and_call(False))
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\keras\utils\control_flow_util.py", line 106, in smart_cond
    pred, true_fn=true_fn, false_fn=false_fn, name=name)
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\tensorflow\python\framework\smart_cond.py", line 58, in smart_cond
    return false_fn()
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\keras\saving\saved_model\utils.py", line 166, in <lambda>
    lambda: replace_training_and_call(False))
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\keras\saving\saved_model\utils.py", line 162, in replace_training_and_call
    return wrapped_call(*args, **kwargs)
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\keras\saving\saved_model\save_impl.py", line 651, in call
    return call_and_return_conditional_losses(inputs, *args, **kwargs)[0]
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\keras\saving\saved_model\save_impl.py", line 609, in __call__
    return self.wrapped_call(*args, **kwargs)
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\tensorflow\python\eager\def_function.py", line 862, in __call__
    return self._python_function(*args, **kwds)
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\keras\saving\saved_model\save_impl.py", line 572, in wrapper
    ret = method(*args, **kwargs)
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\keras\saving\saved_model\utils.py", line 166, in wrap_with_training_arg
    lambda: replace_training_and_call(False))
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\keras\utils\control_flow_util.py", line 106, in smart_cond
    pred, true_fn=true_fn, false_fn=false_fn, name=name)
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\tensorflow\python\framework\smart_cond.py", line 58, in smart_cond
    return false_fn()
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\keras\saving\saved_model\utils.py", line 166, in <lambda>
    lambda: replace_training_and_call(False))
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\keras\saving\saved_model\utils.py", line 162, in replace_training_and_call
    return wrapped_call(*args, **kwargs)
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\keras\saving\saved_model\save_impl.py", line 633, in call_and_return_conditional_losses
    call_output = layer_call(*args, **kwargs)
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\keras\engine\functional.py", line 415, in call
    inputs, training=training, mask=mask)
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\keras\engine\functional.py", line 550, in _run_internal_graph
    outputs = node.layer(*args, **kwargs)
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\keras\engine\base_layer.py", line 1037, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\keras\saving\saved_model\utils.py", line 68, in return_outputs_and_add_losses
    outputs, losses = fn(*args, **kwargs)
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\keras\saving\saved_model\save_impl.py", line 609, in __call__
    return self.wrapped_call(*args, **kwargs)
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\tensorflow\python\eager\def_function.py", line 862, in __call__
    return self._python_function(*args, **kwds)
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\keras\saving\saved_model\save_impl.py", line 572, in wrapper
    ret = method(*args, **kwargs)
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\keras\saving\saved_model\save_impl.py", line 633, in call_and_return_conditional_losses
    call_output = layer_call(*args, **kwargs)
  File "<ipython-input-8-4f4d66e68e0a>", line 45, in call
    for i_step in tf.range(sequence_length):
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\tensorflow\python\framework\ops.py", line 520, in __iter__
    self._disallow_iteration()
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\tensorflow\python\framework\ops.py", line 513, in _disallow_iteration
    self._disallow_when_autograph_enabled("iterating over `tf.Tensor`")
  File "C:\Users\zhaoh\anaconda3\envs\tensorflowV26\lib\site-packages\tensorflow\python\framework\ops.py", line 491, in _disallow_when_autograph_enabled
    " indicate you are trying to use an unsupported feature.".format(task))
tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed: AutoGraph did convert this function. This might indicate you are trying to use an unsupported feature.

**Comment by mohantym** [comment]
Hi @haozh7109 !Could you look at this[ thread ](https://stackoverflow.com/a/58799021/11530462)for answer ?

**Comment by haozh7109** [comment]
Hi @mohantym, thanks for your response. I have added the get_config() function in the customized layer but still got the same error. I have updated the modified code accordingly.

**Comment by mohantym** [comment]
Hi @sanatmpa1 ,
Could you please look at this issue!Issue is replicating is [2.5](https://colab.research.google.com/gist/mohantym/c255b8fa54c273b44e57a52be619825b/github_52121.ipynb#scrollTo=8bPRtXAlfRh6),[2.6](https://colab.research.google.com/gist/mohantym/c255b8fa54c273b44e57a52be619825b/github_52121.ipynb#scrollTo=8bPRtXAlfRh6) and [2.7.0dev(nightly)](https://colab.research.google.com/gist/mohantym/761cb638942802433e3e488ca3b16640/github_52121.ipynb#scrollTo=8bPRtXAlfRh6)

**Comment by sanatmpa1** [comment]
I am able to reproduce `OperatorNotAllowedInGraphError` error and here's the [gist](https://colab.research.google.com/gist/sanatmpa1/40b4c7ddae7a8559bfc7a09e60cab6c7/52121.ipynb). Found a similar issue #44430

**Comment by haozh7109** [comment]
I managed to save the model by decorating the call( ) function in the customized class and replace the 'tf.range()' to 'range()' for the loop. however, I still got errors in the TensorFlow-lite conversion which might relate to the customized model setting. please find the enclosed [Revised_gist](https://colab.research.google.com/gist/haozh7109/90c20c6401c6b38e501a533a8fb2735e/github_52121_2-6_revision.ipynb).

**Comment by gowthamkpr** [comment]
@haozh7109 Please take a look at the solution mentioned [here](https://github.com/tensorflow/tensorflow/issues/53333#issuecomment-1005368027), which should help. Thanks!!

**Comment by mohantym** [comment]
Hi @haozh7109 !
I was getting different error this in 2.11 version. Attached [gist](https://colab.sandbox.google.com/gist/mohantym/fa5bd071c27ecd3d5b314111e67db166/github_52121.ipynb#scrollTo=qkZR--VCfsjR) for reference. 
Fusion code instruction were not working in my earlier trials. 

Please check with [RNN-TFlite](https://www.tensorflow.org/lite/models/convert/rnn#user-defined_lstm_conversion_examples) documentation and [quantization debuggers ](https://www.tensorflow.org/lite/performance/quantization_debugger) once to debug the quantization issues here.
Thank you!

**Comment by haozh7109** [comment]
Hi @mohantym, 

Thanks for the solution provided by @gowthamkpr, I manage to save the customized RNN model and convert it to TensorFlowLite.

Please take a look at the two revised Gists on TF 2.9.2 [(gist-1)](https://colab.research.google.com/gist/haozh7109/3514b0aed51e2bc720e90558968b755e/github_52121_2-9-2_revision.ipynb#scrollTo=tS9kqnMz0aCF) and TF 2.11 [(gist-2)](https://colab.research.google.com/gist/haozh7109/1f40249eae00c0d1cc9eb073cea1cc4b/github_52121_2-11_revision.ipynb).
