### ISSUE TITLE
TPU not working in virtualenv in Cloud TPU-VM

### ISSUE THREAD

**Issue by kamalkraj** [tensorflow/tensorflow#52149]
TF failed to connect to TPU when TF installed in virtualenv.
get the following error

```
Tensorflow version 2.6.0
2021-09-27 08:27:32.379081: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-09-27 08:27:32.420848: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
Traceback (most recent call last):
  File "/home/raj/env/lib/python3.8/site-packages/tensorflow/python/tpu/tpu_strategy_util.py", line 107, in initialize_tpu_system
    output = _tpu_init_fn()
  File "/home/raj/env/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3039, in __call__
    return graph_function._call_flat(
  File "/home/raj/env/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1963, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/home/raj/env/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 591, in call
    outputs = execute.execute(
  File "/home/raj/env/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'ConfigureDistributedTPU' used by {{node ConfigureDistributedTPU}} with these attrs: [compilation_failure_closes_chips=false, tpu_embedding_config="", is_global_init=false, embedding_config="", enable_whole_mesh_compilations=false]
Registered devices: [CPU]
Registered kernels:
  <no registered kernels>

         [[ConfigureDistributedTPU]] [Op:__inference__tpu_init_fn_4]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tpu-test.py", line 10, in <module>
    tf.tpu.experimental.initialize_tpu_system(cluster_resolver)
  File "/home/raj/env/lib/python3.8/site-packages/tensorflow/python/tpu/tpu_strategy_util.py", line 110, in initialize_tpu_system
    raise errors.NotFoundError(
tensorflow.python.framework.errors_impl.NotFoundError: TPUs not found in the cluster. Failed in initialization: No OpKernel was registered to support Op 'ConfigureDistributedTPU' used by {{node ConfigureDistributedTPU}} with these attrs: [compilation_failure_closes_chips=false, tpu_embedding_config="", is_global_init=false, embedding_config="", enable_whole_mesh_compilations=false]
Registered devices: [CPU]
Registered kernels:
  <no registered kernels>

         [[ConfigureDistributedTPU]] [Op:__inference__tpu_init_fn_4]
```
code runs successfully with pre-installed TensorFlow. Fails when installed in a virtualenv
pre-installed TF version `tf-nightly==2.6.0`

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
TPU-VM create
```bash
gcloud alpha compute tpus tpu-vm create deberta --accelerator-type=v3-8 --version=v2-alpha --zone europe-west4-a
```
```bash
virtualenv env
source env/bin/activate
```
```python
import tensorflow as tf
print("Tensorflow version " + tf.__version__)

@tf.function
def add_fn(x,y):
  z = x + y
  return z

cluster_resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu='local')
tf.tpu.experimental.initialize_tpu_system(cluster_resolver)
strategy = tf.distribute.TPUStrategy(cluster_resolver)

x = tf.constant(1.)
y = tf.constant(1.)
z = strategy.run(add_fn, args=(x,y))
print(z)
```
```
python tpu-test.py
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by sachinprasadhs** [comment]
Inside the VM for `TPUClusterResolver`, fpr the argument tpu It can be the TPU name or TPU worker `gRPC` address. If not set, it will try automatically resolve the TPU address on Cloud TPUs. 
But, If set to "`local`", it will assume that the TPU is directly connected to the VM instead of over the network.

**Comment by kamalkraj** [comment]
@sachinprasadhs 
I am trying to execute the code in the TPU-VM. Where TPU is directly attached to the VM

**Comment by allenwang28** [comment]
Currently TensorFlow on TPU VM requires a special build of TensorFlow that comes pre-installed on the VM. `tf-nightly` or `tensorflow` in PyPI unfortunately won't work with TPU VM.

There is a wheel that should be included within the TPU VM at `/usr/share/tpu/*.whl` which I think you can pip install in your virtualenv instead?

**Comment by ayaka14732** [comment]
@allenwang28 

> There is a wheel that should be included within the TPU VM at `/usr/share/tpu/*.whl`

Thank you! Currently there is a `tf_nightly-2.7.0-cp38-cp38-linux_x86_64.whl`, which is Python 3.8. Would you please consider adding Python 3.9 and Python 3.10 versions as well?

**Comment by sachinprasadhs** [comment]
@ayaka14732 , You can try with the latest Tensorflow version 2.9 which was wheel file for pytthon 3.9 and 3.10.

**Comment by nalzok** [comment]
Hi there, this directory is not present on my TPU VM created through the following command, probably because I specified the runtime version to be `tpu-vm-base` instead of `tpu-vm-tf-2.9.1`.

```
gcloud alpha compute tpus tpu-vm create trc-01 \
            --zone us-central1-a \
            --accelerator-type v3-8 \
            --version tpu-vm-base
```

There seems to be a workaround though: the wheels can be downloaded from https://cloud.google.com/tpu/docs/supported-tpu-versions#tpu_software_versions

**Comment by Anan5a** [comment]
> Currently TensorFlow on TPU VM requires a special build of TensorFlow that comes pre-installed on the VM. `tf-nightly` or `tensorflow` in PyPI unfortunately won't work with TPU VM.
> 
> There is a wheel that should be included within the TPU VM at `/usr/share/tpu/*.whl` which I think you can pip install in your virtualenv instead?

This really should be documented on the official kaggle doc

**Comment by kentslaney** [comment]
This helped me because it's true in the default colab runtime as well: the default tensorflow built for TPU is out of date, and these links need to be used instead of PyPI. `cloud-tpu-tpuvm-artifacts` is actually a GCS bucket, so you can access the downloads via the `gcloud` CLI as well.
