### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by omxpro** [tensorflow/tensorflow#52143]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 16.04 and 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Samsung galaxy m12
- TensorFlow installed from (source or binary): I used the venv code
- TensorFlow version (use command below): none: read below
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: mediatek and 6gb

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
`(venv) om@localhost:~/twitchtubemain$ python3 -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
> import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)
>`

**Describe the current behavior**
(venv) om@localhost:~/twitchtubemain$ pip install --upgrade tensorflow
Collecting tensorflow
  Cache entry deserialization failed, entry ignored
  Could not find a version that satisfies the requirement tensorflow (from versions: )
No matching distribution found for tensorflow
(venv) om@localhost:~/twitchtubemain$
**Describe the expected behavior**
Tensor flow getting installed using pip

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
(venv) om@localhost:~/twitchtubemain$ pip install --upgrade tensorflow
Collecting tensorflow
  Cache entry deserialization failed, entry ignored
  Could not find a version that satisfies the requirement tensorflow (from versions: )
No matching distribution found for tensorflow
(venv) om@localhost:~/twitchtubemain$

**Comment by omxpro** [comment]
(venv) om@localhost:~/twitchtubemain$ python
Python 3.6.9 (default, Jan 26 2021, 15:33:00)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow'
>>>

**Comment by omxpro** [comment]
Heyy, how is your day going

**Comment by Saduf2019** [comment]
@omxpro 
Please refer to similar error issue: [link](https://stackoverflow.com/questions/46568913/tensorflow-import-error-no-module-named-tensorflow/48159412),[link1](https://stackoverflow.com/questions/42244198/importerror-no-module-named-tensorflow),[link2](https://www.pythonpool.com/no-module-named-tensorflow-error-solved/),[link3](https://github.com/tensorflow/tensorflow/issues/32147#issuecomment-534791929)


Also verify:

You are running 32-bit Python or 32-bit OS
You have not installed the [Microsoft Visual C++ Redistributable](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0) package
Your CPU does not support AVX instructions.
Please take a look at the [system requirements](https://www.tensorflow.org/install/pip#system-requirements) and check if you have the correct dependencies installed.

Thanks!

**Comment by omxpro** [comment]
I tried link and link1 none of those worker And I also tried `python3 -m pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.0-py3-none-any.whl` and it installed tensorflow but I got this error

Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.

**Comment by omxpro** [comment]
Link2 dosn't help either

**Comment by omxpro** [comment]
Idk how to check avx CPU  and I haven't installed vscode package I am running Tensorflow on terminal on mobile

**Comment by Saduf2019** [comment]
@omxpro 
Can you please confirm if you are using pip install or bazel and for pip have you followed [guide](https://www.tensorflow.org/install/pip), [you may refer to [link](https://www.youtube.com/watch?v=YBnLVZJs6ps),[link1](https://www.youtube.com/watch?v=s4Lcf9du9L8])

**Comment by omxpro** [comment]
I used pip install

**Comment by omxpro** [comment]
And my terminal is running aarch64 aka 64 bits

**Comment by omxpro** [comment]
Uninstalled tersorflow installing it again using official instructions

**Comment by omxpro** [comment]
t:/usr/local/lib/python3.6/dist-packages$ pip install --upgrade tensorflow
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow
om@localhost:/usr/local/lib/python3.6/dist-packages$

**Comment by Saduf2019** [comment]
@omxpro 
please verify all requirements, ex is your python 32 bits.
#48733 #50399 #47151 [this is clearly a compatibility issue

**Comment by omxpro** [comment]
It's 64 bits I checked it

**Comment by omxpro** [comment]
I used a method from #47151 and thus is the error I got after that

`om@localhost:~/twitchtubemain$ pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.0-py3-none-any.whl
Collecting tensorflow==0.12.0                           Using cached https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.0-py3-none-any.whl (38.4 MB)                                                     Requirement already satisfied: protobuf==3.1.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow==0.12.0) (3.1.0)                                        Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow==0.12.0) (1.16.0)                                           Requirement already satisfied: wheel>=0.26 in /usr/local/lib/python3.6/dist-packages (from tensorflow==0.12.0) (0.37.0)                                           Requirement already satisfied: numpy>=1.11.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow==0.12.0) (1.19.5)                                         Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from protobuf==3.1.0->tensorflow==0.12.0) (58.1.0)                           Installing collected packages: tensorflow             Successfully installed tensorflow-0.12.0              om@localhost:~/twitchtubemain$                        om@localhost:~/twitchtubemain$ python main.py         Traceback (most recent call last):                      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/__init__.py", line 49, in <module>             from tensorflow.python import pywrap_tensorflow     File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>    _pywrap_tensorflow = swig_import_helper()           File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper                                                _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)                                   File "/usr/lib/python3.6/imp.py", line 243, in load_module                                                    return load_dynamic(name, filename, file)           File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic                                                   return _load(spec)                                ImportError: /usr/local/lib/python3.6/dist-packages/tensorflow/python/_pywrap_tensorflow.so: invalid ELF header
During handling of the above exception, another exception occurred:
Traceback (most recent call last):                      File "main.py", line 1, in <module>                     from src.ClipHandler import ClipHandler             File "/home/om/twitchtubemain/src/ClipHandler.py", line 8, in <module>                                        import tensorflow as tf                             File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 24, in <module>                    from tensorflow.python import *                     File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/__init__.py", line 60, in <module>             raise ImportError(msg)                            ImportError: Traceback (most recent call last):         File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/__init__.py", line 49, in <module>             from tensorflow.python import pywrap_tensorflow     File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>    _pywrap_tensorflow = swig_import_helper()           File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper                                                _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)                                   File "/usr/lib/python3.6/imp.py", line 243, in load_module                                                    return load_dynamic(name, filename, file)           File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic                                                   return _load(spec)                                ImportError: /usr/local/lib/python3.6/dist-packages/tensorflow/python/_pywrap_tensorflow.so: invalid ELF header

Error importing tensorflow.  Unless you are using bazel,                                                    you should not try to import tensorflow from its source directory;                            om@localhost:~/twitchtubemain$` 

Issue comment link: https://github.com/tensorflow/tensorflow/issues/47151#issuecomment-808707401

**Comment by omxpro** [comment]
[Error file.txt](https://github.com/tensorflow/tensorflow/files/7236810/Error.file.txt)
Error file to make you see the error better

**Comment by mihaimaruseac** [comment]
Why are you installing mac wheel when you are on Linux?

**Comment by omxpro** [comment]
> Why are you installing mac wheel when you are on Linux?

I tried Linux wheel too

**Comment by mihaimaruseac** [comment]
> aarch64

The official wheels only support x86_64.

**Comment by omxpro** [comment]
Okay
