### ISSUE TITLE
Tensorflow lite conversion error when converting the bidirectional LSTM

### ISSUE THREAD

**Issue by lizaibeim** [tensorflow/tensorflow#52168]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows
-   **TensorFlow installed from (source or binary)**: binary
-   **TensorFlow version (use command below)**: 2.3.0
-   **Python version**: 3.8.10

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with:

```bash
python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
```

### Describe the problem
I am trying to convert a tensorflow model into the tensorflow lite format. It prompts that it failed to duplicate values for the stateful op when the conversion goes to the bidirectional lstm layer. Here below is the network structure.
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   

conv1d (Conv1D)              (None, 1558, 32)          5024      

max_pooling1d (MaxPooling1D) (None, 389, 32)           0       
  
batch_normalization (BatchNo (None, 389, 32)           128       

conv1d_1 (Conv1D)            (None, 386, 64)           8256      

max_pooling1d_1 (MaxPooling1 (None, 96, 64)            0         

batch_normalization_1 (Batch (None, 96, 64)            256       

bidirectional (Bidirectional (None, 50)                18000     

dense (Dense)                (None, 32)                1632      

dense_1 (Dense)              (None, 25)                825       

Total params: 34,121
Trainable params: 33,929
Non-trainable params: 192
__________________________

### Source code / logs
Here is the code to raised this error.
`converter = tf.lite.TFLiteConverter.from_saved_model(save_model_dir)`
`converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                           tf.lite.OpsSet.SELECT_TF_OPS]`
` tflite_model = converter.convert()`
 `with open('converted_model.tflite', 'wb') as f:`
`        f.write(tflite_model)`

**Here below are the logs:**
```
2021-09-28 16:44:25.817579: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:313] Ignored output_format.
2021-09-28 16:44:25.817782: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:316] Ignored drop_control_dependency.
2021-09-28 16:44:25.819144: I tensorflow/cc/saved_model/reader.cc:31] Reading SavedModel from: D:\VoiceRecognition\trained_model
2021-09-28 16:44:25.884916: I tensorflow/cc/saved_model/reader.cc:54] Reading meta graph with tags { serve }
2021-09-28 16:44:25.885104: I tensorflow/cc/saved_model/loader.cc:234] Reading SavedModel debug info (if present) from: D:\VoiceRecognition\trained_model
2021-09-28 16:44:26.135034: I tensorflow/cc/saved_model/loader.cc:199] Restoring SavedModel bundle.
2021-09-28 16:44:26.476369: I tensorflow/cc/saved_model/loader.cc:183] Running initialization op on SavedModel bundle at path: D:\VoiceRecognition\trained_model
2021-09-28 16:44:26.761966: I tensorflow/cc/saved_model/loader.cc:303] SavedModel load for tags { serve }; Status: success: OK. Took 942808 microseconds.
loc(callsite(callsite(callsite(unknown at "sequential/bidirectional/backward_lstm/PartitionedCall@__inference__wrapped_model_44427") at "StatefulPartitionedCall@__inference_signature_wrapper_52710") at "StatefulPartitionedCall")): error: We cannot duplicate the value since it's not constant.

error: Failed to duplicate values for the stateful op

Traceback (most recent call last):
  File "C:\Users\lizai\anaconda3\envs\SpectrumAnalysis\lib\site-packages\tensorflow\lite\python\convert.py", line 196, in toco_convert_protos
    model_str = wrap_toco.wrapped_toco_convert(model_flags_str,
  File "C:\Users\lizai\anaconda3\envs\SpectrumAnalysis\lib\site-packages\tensorflow\lite\python\wrap_toco.py", line 32, in wrapped_toco_convert
    return _pywrap_toco_api.TocoConvert(
Exception: <unknown>:0: error: loc(callsite(callsite(callsite(unknown at "sequential/bidirectional/backward_lstm/PartitionedCall@__inference__wrapped_model_44427") at "StatefulPartitionedCall@__inference_signature_wrapper_52710") at "StatefulPartitionedCall")): We cannot duplicate the value since it's not constant.

<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: note: loc(callsite(callsite(callsite(unknown at "sequential/bidirectional/backward_lstm/PartitionedCall@__inference__wrapped_model_44427") at "StatefulPartitionedCall@__inference_signature_wrapper_52710") at "StatefulPartitionedCall")): see current operation: %23 = "tfl.unidirectional_sequence_lstm"(%22, %cst_20, %cst_21, %cst_22, %cst_23, %cst_12, %cst_13, %cst_14, %cst_15, %cst_7, %cst_7, %cst_7, %cst_16, %cst_17, %cst_18, %cst_19, %cst_7, %cst_7, %21, %21, %cst_7, %cst_7, %cst_7, %cst_7) {cell_clip = 1.000000e+01 : f32, fused_activation_function = "TANH", proj_clip = 0.000000e+00 : f32, time_major = false} : (tensor<?x96x64xf32>, tensor<25x64xf32>, tensor<25x64xf32>, tensor<25x64xf32>, tensor<25x64xf32>, tensor<25x25xf32>, tensor<25x25xf32>, tensor<25x25xf32>, tensor<25x25xf32>, none, none, none, tensor<25xf32>, tensor<25xf32>, tensor<25xf32>, tensor<25xf32>, none, none, tensor<?x25xf32>, tensor<?x25xf32>, none, none, none, none) -> tensor<?x96x25xf32>
<unknown>:0: error: Failed to duplicate values for the stateful op

```

**Comment by lizaibeim** [comment]
I have solved this problem by converting the bidirectional lstm into to unidirectional lstm. The solution is referenced by [https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/experimental_new_converter/Keras_LSTM_fusion_Codelab.ipynb?pli=1#scrollTo=0-b0IKK2FGuO](url)
