### ISSUE TITLE
tf.image.resize() behaves differently when wrapped in a tf.data.Dataset.map()

### ISSUE THREAD

**Issue by goncinious** [tensorflow/tensorflow#52167]
`tf.image.resize()` gives different results if used as is (plain) or if wrapped in a `tf.data.Dataset.map()`, however, I except the output to be the same in both cases. The behaviour is shown in the output of the snipped below.

Specifically, this issue seems related to the specific interpolation method `tf.image.ResizeMethod.BILINEAR` (default) with uses `tensorflow.python.ops.gen_image_ops.resize_bilinear` under-the-hood. Changing the interp method (e.g. to `tf.image.ResizeMethod.BICUBIC`, or setting bilinear + `antialias=True`, which uses a different method) no longer show any differences.

Environment:
- Tensorflow 2.6.0
- Python 3.8.6
- Linux 20.04
- Driver Version: 460.32.03
- CUDA Version: 11.2
- cuDNN 8.1.0
- NVIDIA T4 GPU (16GB)

Reproducible script:
```

import tensorflow as tf
import numpy as np
from PIL import Image

print(tf.__version__)

@tf.function
def tf_read_and_resize_image(filename):
    image_string = tf.io.read_file(filename)
    image = tf.image.decode_jpeg(image_string, channels=3)
    image=tf.cast(image, tf.float32)
    image = tf.image.resize(image, (224, 224), method=tf.image.ResizeMethod.BILINEAR)
    return image

# create random uint8 image
np.random.seed(42)
im = np.random.randint(low=0, high=255, size=(100, 100, 3), dtype=np.uint8)
im_filename = "/tmp/test_image.jpg"
im = Image.fromarray(im).save(im_filename)

# plain function
plain_tensor = tf_read_and_resize_image(im_filename)

# wrapped in tf.data map()
ds = tf.data.Dataset.from_tensor_slices([im_filename])
ds = ds.map(tf_read_and_resize_image)
ds_tensor = next(ds.as_numpy_iterator())

assert plain_tensor.dtype == ds_tensor.dtype == "float32"
assert plain_tensor.shape == ds_tensor.shape == (224, 224, 3)
np.testing.assert_array_equal(plain_tensor, ds_tensor) # fails with ~11% diff.
```

Output:
```
(tf_issue) root@f1f0235af85c:/srv/2D3Dreg/deeplearning# python test.py 
2.6.0
2021-09-28 14:10:08.987749: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-28 14:10:08.997055: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-28 14:10:08.997667: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-28 14:10:08.998427: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-09-28 14:10:08.999018: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-28 14:10:08.999644: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-28 14:10:09.000204: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-28 14:10:09.584861: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-28 14:10:09.585487: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-28 14:10:09.586072: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-28 14:10:09.586636: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13666 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:1e.0, compute capability: 7.5
2021-09-28 14:10:09.596141: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
Traceback (most recent call last):
  File "test.py", line 30, in <module>
    np.testing.assert_array_equal(input_tensor_read, ds_read) # fails with ~11% diff.
  File "/srv/2D3Dreg/deeplearning/tf_issue/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 930, in assert_array_equal
    assert_array_compare(operator.__eq__, x, y, err_msg=err_msg,
  File "/srv/2D3Dreg/deeplearning/tf_issue/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 840, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

Mismatched elements: 16381 / 150528 (10.9%)
Max absolute difference: 0.00051498
Max relative difference: 1.0005011e-05
 x: array([[[164.      , 208.      , 131.      ],
        [154.83928 , 198.83928 , 124.55357 ],
        [130.73215 , 174.73215 , 107.58929 ],...
 y: array([[[164.      , 208.      , 131.      ],
        [154.83928 , 198.83928 , 124.55357 ],
        [130.73215 , 174.73215 , 107.58929 ],...
```

**Comment by mohantym** [comment]
Hi @goncinious! , I tried to replicate this issue with  the code  you shared  in Colab ,Could not find the above Error Stack Trace . Can you please share the same as Colab Gist? Attaching [GIST](https://colab.research.google.com/gist/mohantym/09fd474860213fb96cecb108e3403d59/github_52167.ipynb) for reference.

**Comment by goncinious** [comment]
Thanks @mohamedadaly,

I wasn't able to reproduce the result in the Colab environment either (with or without GPU support), but I was able to reproduce it using the official [Tensorflow Docker images](https://www.tensorflow.org/install/docker#download_a_tensorflow_docker_image), which is similar to my setup (also running from within a Docker container).

Environment:
- GPU: NVIDIA Quadro T2000 (also tested on a NVIDIA T4)
- Docker version 20.10.7, build f0df350
- host OS: Ubuntu 20.04
- Driver Version: 460.91.03


Here are the steps to reproduce this issue:

1. Pull official Docker image with GPU support 
```
docker pull tensorflow/tensorflow:latest-gpu
```

2. Run docker command with GPU support, mounting `test.py` (see [GIST](https://colab.research.google.com/gist/goncinious/c326400ecf1c860ffe69f106c18fefc3/tf_image_resize_debug.ipynb)) script to `/srv`
```
docker run --network host --gpus all -v /home/goncalo/test.py:/srv/test.py -it tensorflow/tensorflow:latest-gpu /bin/bash
```

3. Install `PIL` dependency
```
pip install Pillow
```
4. `cd` to `/srv` and run test script
```
cd /srv
python test.py
```

Here's the obtained output:
```
root@goncalo-laptop:/srv# python test.py
2.6.0
3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0]
2021-09-29 16:34:10.381327: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-29 16:34:10.385631: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-29 16:34:10.386060: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
2021-09-29 16:34:10.443339: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-09-29 16:34:10.444913: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-29 16:34:10.445410: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-29 16:34:10.445940: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-29 16:34:10.797101: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-29 16:34:10.797604: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-29 16:34:10.798019: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-29 16:34:10.798349: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1690 MB memory:  -> device: 0, name: Quadro T2000, pci bus id: 0000:01:00.0, compute capability: 7.5
2021-09-29 16:34:10.806638: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
Traceback (most recent call last):
  File "test.py", line 34, in <module>
    np.testing.assert_array_equal(plain_tensor, ds_tensor) # fails with ~11% diff.
  File "/usr/local/lib/python3.6/dist-packages/numpy/testing/_private/utils.py", line 931, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/local/lib/python3.6/dist-packages/numpy/testing/_private/utils.py", line 840, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

Mismatched elements: 16381 / 150528 (10.9%)
Max absolute difference: 0.00051498
Max relative difference: 1.0005011e-05
 x: array([[[164.      , 208.      , 131.      ],
        [154.83928 , 198.83928 , 124.55357 ],
        [130.73215 , 174.73215 , 107.58929 ],...
 y: array([[[164.      , 208.      , 131.      ],
        [154.83928 , 198.83928 , 124.55357 ],
        [130.73215 , 174.73215 , 107.58929 ],...
```

The issue appears GPU-related, as the test pass fine without GPU support:

```
root@goncalo-laptop:/srv# CUDA_VISIBLE_DEVICES="" python test.py

2.6.0
3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0]
2021-09-29 16:34:44.403763: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-09-29 16:34:44.403789: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: goncalo-laptop
2021-09-29 16:34:44.403793: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: goncalo-laptop
2021-09-29 16:34:44.403860: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 460.91.3
2021-09-29 16:34:44.403889: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 460.91.3
2021-09-29 16:34:44.403915: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 460.91.3
[]
2021-09-29 16:34:44.463146: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-09-29 16:34:44.471553: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
passed!
```

**Comment by mohantym** [comment]
Hi @sanatmpa1! Could you please look at this issue! Issue is not replicating in Colab environment.Providing GIST in [2.5,](https://colab.research.google.com/drive/1cbtFq7U_EDthDCn4AnwhUa-kLdACbcET?resourcekey=0-1DdAxOrBl4XFZqdNx_e1pA#scrollTo=1kwpXalNBgrn),[2.6 ](https://colab.research.google.com/gist/mohantym/09fd474860213fb96cecb108e3403d59/github_52167.ipynb#scrollTo=1kwpXalNBgrn)and [2.7](https://colab.research.google.com/gist/mohantym/e62ed7d4dd5196fee732c2b9b8ee32a3/github_52167.ipynb#scrollTo=1kwpXalNBgrn)  for reference.

**Comment by ashishpatel26** [comment]
Solution is always simple I will explain with example.

* Let's say you are using tensorflow, numpy, pandas, or any other library which contains the function of seeds.
* This packages have their own way to define seeds method.
* So, **Solution is that try to creat the function which is generate the seeds from this all package. this way you can produce same results everytime.**

Example Function
```python
import random
import numpy as np
import tensorflow as tf

def random_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    tf.random.set_seed(seed)

rseed = random_seed(2022)

tf.keras.Dropout(0.25, seed=rseed)
```

I hope this helps...!!! Feel free to share your thought on this.

**Comment by goncinious** [comment]
Thanks @ashishpatel26 for your reply.

Fixing the seeds didn't fix the issue described. I can also confirm that the issue persists on the latest TF Docker image (with TF 2.7.0). (see [previous comment](https://github.com/tensorflow/tensorflow/issues/52167#issuecomment-930357745) for steps to reproduce).

I also tried setting `TF_DETERMINIC_OPS` and `num_parallel_calls=1` in `map()` (see [GIST](https://colab.research.google.com/drive/1IWl9M2yIVxs8_JTCZMShSyNPu-lZkU6I?usp=sharing)), but I continue to get different results using resize + BILINEAR interp method, inside vs. outside of the map() method.

Finally, I tried the [`nightly-gpu`](https://hub.docker.com/layers/tensorflow/tensorflow/nightly-gpu/images/sha256-cf86db348de66caa93a4248020c41fd783d8a83a9e9dacb42f870a6999547f74?context=explore) image (TF 2.9.0-dev20220124) and used the recently introduced [tf.config.experimental.enable_op_determinism](https://www.tensorflow.org/api_docs/python/tf/config/experimental/enable_op_determinism) function - made no difference.

**Comment by jvishnuvardhan** [comment]
@goncinious Is this still an issue. I couldn't reproduce the issue when I ran your code with `tf-nightly` and the following two line at the start of your code. [Here](https://colab.research.google.com/gist/jvishnuvardhan/3624a43bfa923f8d30ddec597bc560b0/tf_image_resize_bilinear_issue.ipynb) is a gist for reference. Thanks!

```
import tensorflow as tf
tf.keras.utils.set_random_seed(1)
tf.config.experimental.enable_op_determinism()
```

Can you please verify once and close the issue if this was resolved for you. Thanks!

**Comment by goncinious** [comment]
I can confirm that this is still an issue even when the two lines are included at the top of the code. @jvishnuvardhan, have you tested o a machine with GPU? As mentioned in https://github.com/tensorflow/tensorflow/issues/52167#issuecomment-930357745 (see bottom of the comment), this issue only seems to occur when running on GPU.

I've just tested the latest `nightly-gpu` TensorFlow container (`sha256:bcf90aa34b1dd1322c981c780bf7ee8f6546ecc27b2175b3ed28ab883173cb29`) and the issue persists when running on NVIDIA A10G or Tesla T4 GPUs.

**Comment by jvishnuvardhan** [comment]
@goncinious Looks like team is working on updating ops to work as deterministic. Thanks!

**Comment by goncinious** [comment]
Thanks for the update, @jvishnuvardhan! Could you please also update the tag `2.6.0` -> `2.8.0`, since this concerns the latest version of TF as well?

**Comment by goncinious** [comment]
I can confirm that this is still an issue in TF 2.9.1. Tested with `tensorflow/tensorflow:latest-gpu` (`sha256:a34c2420739cd5a7b5662449bc21eb32d3d1c98063726ae2bd7db819cc93d72f`) on a NVIDIA A10G GPU.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

Could you please try with tensorflow v2.17 which contains the Keras3.0 version.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
