### ISSUE TITLE
Tensorflow GPU 2.4 from source - fatal error in compilation

### ISSUE THREAD

**Issue by louim-lbs** [tensorflow/tensorflow#52180]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): W10 Pro 21H1
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.4
- Python version: 3.7.8 64-bits
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.0/8
- GPU model and memory: Nvidia Quadro K4200

**Describe the problem**

I try to compile Tensorflow 2.4 from source for GPU compute capability 3.0 compatibility. I run into a weird fail (log below) I don't understand and for wich I don't find any ressource online. It seems to be related to Cython maybe.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

From https://www.tensorflow.org/install/source_windows

```git clone https://github.com/tensorflow/tensorflow.git
git checkout r2.4
.\configure.py
bazel build --config=opt --copt=-nvcc_options=disable-warnings --copt=-DTF_EXTRA_CUDA_CAPABILITIES=3.0 --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package
```

**Any other info / logs**

.configure.py log
```
PS C:\Users\*username*\tensorflow> C:\Users\*username*\AppData\Local\Programs\Python\Python37\python.exe .\configure.py
You have bazel 3.1.0 installed.
Please specify the location of python. [Default is C:\Users\*username*\AppData\Local\Programs\Python\Python37\python.exe]:


Found possible Python library paths:
  C:\Users\*username*\AppData\Local\Programs\Python\Python37\lib\site-packages
Please input the desired Python library path to use.  Default is [C:\Users\*username*\AppData\Local\Programs\Python\Python37\lib\site-packages]

Do you wish to build TensorFlow with ROCm support? [y/N]:
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Found CUDA 11.0 in:
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.0/lib/x64
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.0/include
Found cuDNN 8 in:
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.0/lib/x64
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.0/include


Please specify a list of comma-separated CUDA compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus. Each capability can be specified as "x.y" or "compute_xy" to include both virtual and binary GPU code, or as "sm_xy" to only include the binary code.
Please note that each additional compute capability significantly increases your build time and binary size, and that TensorFlow only supports compute capabilities >= 3.5 [Default is: 3.5,7.0]: 3.0


WARNING: XLA does not support CUDA compute capabilities lower than 3.5. Disable XLA when running on older GPUs.
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]:


Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]:
Eigen strong inline overridden.

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]:
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=mkl_aarch64    # Build with oneDNN support for Aarch64.
        --config=monolithic     # Config for mostly static monolithic build.
        --config=ngraph         # Build with Intel nGraph support.
        --config=numa           # Build with NUMA support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
        --config=v2             # Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=noaws          # Disable AWS S3 filesystem support.
        --config=nogcp          # Disable GCP support.
        --config=nohdfs         # Disable HDFS support.
        --config=nonccl         # Disable NVIDIA NCCL support.
```

Build log with the error
```
PS C:\Users\*username*\tensorflow> bazel build --config=opt --copt=-nvcc_options=disable-warnings --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package
WARNING: The following configs were expanded more than once: [cuda, using_cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=209
INFO: Reading rc options for 'build' from c:\users\*username*\tensorflow\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=C:/Users/*username*/AppData/Local/Programs/Python/Python39/python.exe
INFO: Reading rc options for 'build' from c:\users\*username*\tensorflow\.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=short_logs --config=v2
INFO: Reading rc options for 'build' from c:\users\*username*\tensorflow\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=C:/Users/*username*/AppData/Local/Programs/Python/Python37/python.exe --action_env PYTHON_LIB_PATH=C:/Users/*username*/AppData/Local/Programs/Python/Python37/lib/site-packages --python_path=C:/Users/*username*/AppData/Local/Programs/Python/Python37/python.exe --config=xla --action_env CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.0 --action_env TF_CUDA_COMPUTE_CAPABILITIES=3.0 --config=cuda --define=override_eigen_strong_inline=true --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:short_logs in file c:\users\*username*\tensorflow\.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file c:\users\*username*\tensorflow\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file c:\users\*username*\tensorflow\.bazelrc: --define=with_xla_support=true
INFO: Found applicable config definition build:cuda in file c:\users\*username*\tensorflow\.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file c:\users\*username*\tensorflow\.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=1
INFO: Found applicable config definition build:opt in file c:\users\*username*\tensorflow\.tf_configure.bazelrc: --copt=/arch:AVX --host_copt=/arch:AVX --define with_default_optimizations=true
INFO: Found applicable config definition build:cuda in file c:\users\*username*\tensorflow\.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file c:\users\*username*\tensorflow\.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=1
INFO: Found applicable config definition build:windows in file c:\users\*username*\tensorflow\.bazelrc: --copt=/W0 --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=/experimental:preprocessor --host_copt=/experimental:preprocessor --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --experimental_strict_action_env=true --verbose_failures --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file c:\users\*username*\tensorflow\.bazelrc: --define framework_shared_object=false
INFO: Build option --copt has changed, discarding analysis cache.
INFO: Repository cython instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule tf_http_archive defined at:
  C:/users/*username*/tensorflow/third_party/repo.bzl:131:19: in <toplevel>
INFO: Repository 'cython' used the following cache hits instead of downloading the corresponding file.
 * Hash 'bccc9aa050ea02595b2440188813b936eaf345e85fb9692790cecfe095cf91aa' for https://storage.googleapis.com/mirror.tensorflow.org/github.com/cython/cython/archive/0.28.4.tar.gz
If the definition of 'cython' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'cython':
   Traceback (most recent call last):
        File "C:/users/*username*/tensorflow/third_party/repo.bzl", line 105
                _apply_delete(ctx, <1 more arguments>)
        File "C:/users/*username*/tensorflow/third_party/repo.bzl", line 74, in _apply_delete
                _execute_and_check_ret_code(ctx, <1 more arguments>)
        File "C:/users/*username*/tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
                fail(<1 more arguments>)
Non-zero return code(256) when executing 'C:\msys64\usr\bin\bash.exe -l -c "rm" "-rf" "C:/cygwin64/home/*username*/_bazel_*username*/feynteyc/external/cython/BUILD.bazel"':
Stdout:
Stderr:       1 [main] bash (14200) C:\msys64\usr\bin\bash.exe: *** fatal error - add_item ("\??\C:\msys64", "/", ...) failed, errno 1
Stack trace:
Frame        Function    Args
000FFFF8630  00180063085 (00180297142, 00180272E41, 0000000003F, 000FFFF8B10)
000FFFF8B60  001800488F2 (000FFFFFFFF, 00180020010, 000FFFFABCA, 000FFFF9BB0)
000FFFF9B70  00180048931 (000FFFF9BB0, 00000000001, 0000000003F, 00000000001)
000FFFF9C00  001800E658D (00000000000, 00140000024, 00000000000, 000FFFFCC50)
000FFFFCC70  00180136D95 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFCCE0  00180048F75 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFCDA0  0018004794A (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFCE50  00180047A0C (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
ERROR: C:/users/*username*/tensorflow/tensorflow/python/BUILD:7748:1: //tensorflow/python:framework/fast_tensor_util.pyx_cython_translation depends on @cython//:cython_binary in repository @cython which failed to fetch. no such package '@cython//': Traceback (most recent call last):
        File "C:/users/*username*/tensorflow/third_party/repo.bzl", line 105
                _apply_delete(ctx, <1 more arguments>)
        File "C:/users/*username*/tensorflow/third_party/repo.bzl", line 74, in _apply_delete
                _execute_and_check_ret_code(ctx, <1 more arguments>)
        File "C:/users/*username*/tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
                fail(<1 more arguments>)
Non-zero return code(256) when executing 'C:\msys64\usr\bin\bash.exe -l -c "rm" "-rf" "C:/cygwin64/home/*username*/_bazel_*username*/feynteyc/external/cython/BUILD.bazel"':
Stdout:
Stderr:       1 [main] bash (14200) C:\msys64\usr\bin\bash.exe: *** fatal error - add_item ("\??\C:\msys64", "/", ...) failed, errno 1
Stack trace:
Frame        Function    Args
000FFFF8630  00180063085 (00180297142, 00180272E41, 0000000003F, 000FFFF8B10)
000FFFF8B60  001800488F2 (000FFFFFFFF, 00180020010, 000FFFFABCA, 000FFFF9BB0)
000FFFF9B70  00180048931 (000FFFF9BB0, 00000000001, 0000000003F, 00000000001)
000FFFF9C00  001800E658D (00000000000, 00140000024, 00000000000, 000FFFFCC50)
000FFFFCC70  00180136D95 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFCCE0  00180048F75 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFCDA0  0018004794A (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFCE50  00180047A0C (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@cython//': Traceback (most recent call last):
        File "C:/users/*username*/tensorflow/third_party/repo.bzl", line 105
                _apply_delete(ctx, <1 more arguments>)
        File "C:/users/*username*/tensorflow/third_party/repo.bzl", line 74, in _apply_delete
                _execute_and_check_ret_code(ctx, <1 more arguments>)
        File "C:/users/*username*/tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
                fail(<1 more arguments>)
Non-zero return code(256) when executing 'C:\msys64\usr\bin\bash.exe -l -c "rm" "-rf" "C:/cygwin64/home/*username*/_bazel_*username*/feynteyc/external/cython/BUILD.bazel"':
Stdout:
Stderr:       1 [main] bash (14200) C:\msys64\usr\bin\bash.exe: *** fatal error - add_item ("\??\C:\msys64", "/", ...) failed, errno 1
Stack trace:
Frame        Function    Args
000FFFF8630  00180063085 (00180297142, 00180272E41, 0000000003F, 000FFFF8B10)
000FFFF8B60  001800488F2 (000FFFFFFFF, 00180020010, 000FFFFABCA, 000FFFF9BB0)
000FFFF9B70  00180048931 (000FFFF9BB0, 00000000001, 0000000003F, 00000000001)
000FFFF9C00  001800E658D (00000000000, 00140000024, 00000000000, 000FFFFCC50)
000FFFFCC70  00180136D95 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFCCE0  00180048F75 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFCDA0  0018004794A (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFCE50  00180047A0C (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
INFO: Elapsed time: 26.147s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded, 15684 targets configured)
    Fetching @llvm-project; fetching 24s
    Fetching @local_config_git; fetching 24s
    Fetching ...me/*username*/_bazel_*username*/feynteyc/external/llvm-project; Extracting C:/cygwin64/home/*username*/_bazel_*username*/feynteyc/external/llvm-project/f402e682d0ef5598eeffc9a21a691b03e602ff58.tar.gz 22s
    Fetching @aws; fetching 22s
    Fetching C:/cygwin64/home/*username*/_bazel_*username*/feynteyc/external/aws; Extracting C:/cygwin64/home/*username*/_bazel_*username*/feynteyc/external/aws/1.7.336.tar.gz 22s
``

**Comment by mohantym** [comment]
Hi @louim-lbs! Could you please look at this  [similar issue](https://github.com/tensorflow/tensorflow/issues/4279).

**Comment by louim-lbs** [comment]
Hi @mohantym! Thanks for your answer.
I've looked at this issue, and tried to configure.py again before to build, but it changed nothing...

**Comment by mohantym** [comment]
Hi @Saduf2019! Could you please look at this issue!

**Comment by Saduf2019** [comment]
@louim-lbs 
Please refer to [this comment](https://github.com/tensorflow/tensorflow/issues/49263#issuecomment-857868501) and let us know.

**Comment by louim-lbs** [comment]
I need this specific version (<= 2.4) for compatibility issue with other packages. So I won't try newer ones, although it surely might work.

But I find an other way: using tensorflow windows wheel provided by @fo40225 at [https://github.com/fo40225/tensorflow-windows-wheel.git](url).

**Comment by Saduf2019** [comment]
@louim-lbs 
Can you please confirm if the above solutions helps resolve the issue faced by you.

**Comment by Saduf2019** [comment]
@louim-lbs 
Sure please update us after upgrading tf version.
