### ISSUE TITLE
Object Detection Android App Crash 

### ISSUE THREAD

**Issue by myasser63** [tensorflow/tensorflow#52183]
I am trying to convert my custom  `MobileNet Single Shot Detector (v2)` to `tflite` using Roboflow tutorial colab (https://colab.research.google.com/drive/1qXn9q6m5ug7EWJsJov6mHaotHhCUY-wG?usp=sharing). After Conversion I deploy it on Tensorflow android app demo (https://github.com/tensorflow/examples.git). When I run the app it always crashes after lunch immediately showing the following error:

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.tensorflow.lite.examples.detection, PID: 10743
    java.lang.AssertionError: Error occurred when initializing ObjectDetector: Input tensor has type kTfLiteFloat32: it requires specifying NormalizationOptions metadata to preprocess input images.
        at org.tensorflow.lite.task.vision.detector.ObjectDetector.initJniWithByteBuffer(Native Method)
        at org.tensorflow.lite.task.vision.detector.ObjectDetector.access$100(ObjectDetector.java:86)
        at org.tensorflow.lite.task.vision.detector.ObjectDetector$3.createHandle(ObjectDetector.java:211)
        at org.tensorflow.lite.task.core.TaskJniUtils.createHandleFromLibrary(TaskJniUtils.java:91)
        at org.tensorflow.lite.task.vision.detector.ObjectDetector.createFromBufferAndOptions(ObjectDetector.java:207)
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.<init>(TFLiteObjectDetectionAPIModel.java:87)
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.create(TFLiteObjectDetectionAPIModel.java:81)
        at org.tensorflow.lite.examples.detection.DetectorActivity.onPreviewSizeChosen(DetectorActivity.java:99)
        at org.tensorflow.lite.examples.detection.CameraActivity$7.onPreviewSizeChosen(CameraActivity.java:446)
        at org.tensorflow.lite.examples.detection.CameraConnectionFragment.setUpCameraOutputs(CameraConnectionFragment.java:357)
        at org.tensorflow.lite.examples.detection.CameraConnectionFragment.openCamera(CameraConnectionFragment.java:362)
        at org.tensorflow.lite.examples.detection.CameraConnectionFragment.access$300(CameraConnectionFragment.java:66)
        at org.tensorflow.lite.examples.detection.CameraConnectionFragment$3.onSurfaceTextureAvailable(CameraConnectionFragment.java:171)
        at android.view.TextureView.getTextureLayer(TextureView.java:415)
        at android.view.TextureView.draw(TextureView.java:360)
        at android.view.View.updateDisplayListIfDirty(View.java:21389)
        at android.view.View.draw(View.java:22254)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
        at android.view.View.updateDisplayListIfDirty(View.java:21380)
        at android.view.View.draw(View.java:22254)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
        at android.view.View.updateDisplayListIfDirty(View.java:21380)
        at android.view.View.draw(View.java:22254)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
        at android.view.View.draw(View.java:22538)
        at android.view.View.updateDisplayListIfDirty(View.java:21389)
        at android.view.View.draw(View.java:22254)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
        at android.view.View.draw(View.java:22538)
        at android.view.View.updateDisplayListIfDirty(View.java:21389)
        at android.view.View.draw(View.java:22254)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
        at android.view.View.updateDisplayListIfDirty(View.java:21380)
        at android.view.View.draw(View.java:22254)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
        at android.view.View.updateDisplayListIfDirty(View.java:21380)
        at android.view.View.draw(View.java:22254)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
        at android.view.View.updateDisplayListIfDirty(View.java:21380)
        at android.view.View.draw(View.java:22254)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
        at android.view.View.updateDisplayListIfDirty(View.java:21380)
        at android.view.View.draw(View.java:22254)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
        at android.view.View.draw(View.java:22538)
        at com.android.internal.policy.DecorView.draw(DecorView.java:848)
        at android.view.View.updateDisplayListIfDirty(View.java:21389)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:647)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:4417)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4144)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3391)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2182)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8730)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
        at android.view.Choreographer.doCallbacks(Choreographer.java:1149)
        at android.view.Choreographer.doFrame(Choreographer.java:1049)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1333)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8010)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
I/Process: Sending signal. PID: 10743 SIG: 9

**Comment by myasser63** [comment]
@sushreebarsa  Could provide assistance?

**Comment by vulkomilev** [comment]
java.lang.AssertionError: Error occurred when initializing ObjectDetector: Input tensor has type kTfLiteFloat32: it requires specifying NormalizationOptions metadata to preprocess input images.

Did you specify this?
Are you sure the two programs are compatible

**Comment by sushreebarsa** [comment]
@myasser63 In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),Thanks!

**Comment by myasser63** [comment]
I have added the new issue on Tensorflow lite converter

**Comment by myasser63** [comment]
> java.lang.AssertionError: Error occurred when initializing ObjectDetector: Input tensor has type kTfLiteFloat32: it requires specifying NormalizationOptions metadata to preprocess input images.
> 
> Did you specify this? Are you sure the two programs are compatible

How can I specify the normalization options?

**Comment by sushreebarsa** [comment]
@myasser63 We see that new[ issue ](https://github.com/tensorflow/tensorflow/issues/52194) has been created , Could you please confirm if we can close this ticket as we will track the other one ?Thanks!

**Comment by myasser63** [comment]
Sure, you can close this issue
