### ISSUE TITLE
TensorFlow Object Detection : Error while executing python model_main_tf2.py

### ISSUE THREAD

**Issue by SHILPASHIVAMALLU** [tensorflow/tensorflow#52221]
Environment:

1. TensorFlow:2.6
2. Python : 3.9.6
3. Transfer learning for Object Detection using TensorFlow
4. Dataset : Digital Meter
5. Example Link: https://medium.com/analytics-vidhya/digit-recognition-of-digital-meters-using-tensorflow-2-object-detection-api-48364cd678a9 
6. Pre-trained Model : ssd_mobilenet_v1_fpn_640x640_coco17_tpu-8
7. Generated Tf Record successfully( train.record and test.record )
8. Python command:  python model_main_tf2.py --model_dir=models/my_ssd_mobilenet_
9. v1_fpn --pipeline_config_path=models/my_ssd_mobilenet_v1_fpn/pipeline.config

**Error:** 
**2021-10-02 01:05:11.264437: W tensorflow/core/framework/dataset.cc:679] Input of GeneratorDatasetOp::Dataset will not be op
timized because the dataset does not implement the AsGraphDefInternal() method needed to apply optimizations.
C:\Users\shilpa.m\PycharmProjects\TensorFlow_OD\venv\lib\site-packages\keras\backend.py:401: UserWarning: `tf.keras.backend
.set_learning_phase` is deprecated and will be removed after 2020-10-11. To update it, simply pass a True/False value to th
e `training` argument of the `__call__` method of your layer or model.
  warnings.warn('`tf.keras.backend.set_learning_phase` is deprecated and '
Traceback (most recent call last):
  File "C:\Users\shilpa.m\PycharmProjects\TensorFlow_OD\Workspace\model_main_tf2.py", line 115, in <module>
    tf.compat.v1.app.run()
  File "C:\Users\shilpa.m\PycharmProjects\TensorFlow_OD\venv\lib\site-packages\tensorflow\python\platform\app.py", line 40,
 in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\shilpa.m\PycharmProjects\TensorFlow_OD\venv\lib\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "C:\Users\shilpa.m\PycharmProjects\TensorFlow_OD\venv\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "C:\Users\shilpa.m\PycharmProjects\TensorFlow_OD\Workspace\model_main_tf2.py", line 106, in main
    model_lib_v2.train_loop(
  File "C:\Users\shilpa.m\PycharmProjects\TensorFlow_OD\venv\lib\site-packages\object_detection\model_lib_v2.py", line 618,
 in train_loop
    ckpt.restore(latest_checkpoint)
  File "C:\Users\shilpa.m\PycharmProjects\TensorFlow_OD\venv\lib\site-packages\tensorflow\python\training\tracking\util.py"
, line 2335, in restore
    status = self.read(save_path, options=options)
  File "C:\Users\shilpa.m\PycharmProjects\TensorFlow_OD\venv\lib\site-packages\tensorflow\python\training\tracking\util.py"
, line 2220, in read
    result = self._saver.restore(save_path=save_path, options=options)
  File "C:\Users\shilpa.m\PycharmProjects\TensorFlow_OD\venv\lib\site-packages\tensorflow\python\training\tracking\util.py"
, line 1382, in restore
    base.CheckpointPosition(
  File "C:\Users\shilpa.m\PycharmProjects\TensorFlow_OD\venv\lib\site-packages\tensorflow\python\training\tracking\base.py"
, line 254, in restore
    restore_ops = trackable._restore_from_checkpoint_position(self)  # pylint: disable=protected-access
  File "C:\Users\shilpa.m\PycharmProjects\TensorFlow_OD\venv\lib\site-packages\tensorflow\python\training\tracking\base.py"
, line 980, in _restore_from_checkpoint_position
    current_position.checkpoint.restore_saveables(
  File "C:\Users\shilpa.m\PycharmProjects\TensorFlow_OD\venv\lib\site-packages\tensorflow\python\training\tracking\util.py"
, line 351, in restore_saveables
    new_restore_ops = functional_saver.MultiDeviceSaver(
  File "C:\Users\shilpa.m\PycharmProjects\TensorFlow_OD\venv\lib\site-packages\tensorflow\python\training\saving\functional
_saver.py", line 339, in restore
    restore_ops = restore_fn()
  File "C:\Users\shilpa.m\PycharmProjects\TensorFlow_OD\venv\lib\site-packages\tensorflow\python\training\saving\functional
_saver.py", line 323, in restore_fn
    restore_ops.update(saver.restore(file_prefix, options))
  File "C:\Users\shilpa.m\PycharmProjects\TensorFlow_OD\venv\lib\site-packages\tensorflow\python\training\saving\functional
_saver.py", line 115, in restore
    restore_ops[saveable.name] = saveable.restore(
  File "C:\Users\shilpa.m\PycharmProjects\TensorFlow_OD\venv\lib\site-packages\tensorflow\python\distribute\values.py", lin
e 1079, in restore
    return values_util.get_on_write_restore_ops(self._mirrored_variable,
  File "C:\Users\shilpa.m\PycharmProjects\TensorFlow_OD\venv\lib\site-packages\tensorflow\python\distribute\values_util.py"
, line 94, in get_on_write_restore_ops
    tuple(
  File "C:\Users\shilpa.m\PycharmProjects\TensorFlow_OD\venv\lib\site-packages\tensorflow\python\distribute\values_util.py"
, line 95, in <genexpr>
    assign_on_device(v.device, v, tensor)
  File "C:\Users\shilpa.m\PycharmProjects\TensorFlow_OD\venv\lib\site-packages\tensorflow\python\distribute\values_util.py"
, line 302, in assign_on_device
    return variable.assign(tensor)
  File "C:\Users\shilpa.m\PycharmProjects\TensorFlow_OD\venv\lib\site-packages\tensorflow\python\ops\resource_variable_ops.
py", line 899, in assign
    raise ValueError(
ValueError: Cannot assign to variable WeightSharedConvolutionalBoxPredictor/WeightSharedConvolutionalClassHead/ClassPredict
or/bias:0 due to variable shape (66,) and value shape (72,) are incompatible**

**Comment by tilakrayal** [comment]
@SHILPASHIVAMALLU ,
This issue is more suitable for TensorFlow Models repo. Please post it on Tensorflow Models repo from [here](https://github.com/tensorflow/models/issues/new/choose). Also please take a look at this [link](https://github.com/tensorflow/models/issues/9703) with the similar error.It helps.Thanks!
