### ISSUE TITLE
Build r2.2.0 fails when build ppc64le machine

### ISSUE THREAD

**Issue by aoki897** [tensorflow/tensorflow#52283]
when i Compiling tensorflow-gpu from source,I do not know how to solve the following error

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):source
- TensorFlow version:v2.2.0
- Python version:3.6
- Installed using virtualenv? pip? conda?:conda
- Bazel version (if compiling from source):2.0.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:CUDA 10.1/cuDNN 7
- GPU model and memory:k80

./configure
You have bazel 2.0.0- (@non-git) installed.
Please specify the location of python. [Default is /home/owner/anaconda3/envs/tensorflow/bin/python]: /home/owner/anaconda3/envs/tensorflow/bin/python3.6

Found possible Python library paths:
  /home/owner/anaconda3/envs/tensorflow/lib/python3.6/site-packages
Please input the desired Python library path to use.  Default is [/home/owner/anaconda3/envs/tensorflow/lib/python3.6/site-packages]

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: n
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Do you wish to build TensorFlow with TensorRT support? [y/N]: n
No TensorRT support will be enabled for TensorFlow.

Found CUDA 10.1 in:
    /usr/local/cuda/lib64
    /usr/local/cuda/include
Found cuDNN 7 in:
    /usr/local/cuda/lib64
    /usr/local/cuda/include

Please specify a list of comma-separated CUDA compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size, and that TensorFlow only supports compute capabilities >= 3.5 [Default is: 3.5,7.0]: 

Do you want to use clang as CUDA compiler? [y/N]: n
nvcc will be used as CUDA compiler.

Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -mcpu=native]: 

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: n
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
	--config=mkl         	# Build with MKL support.
	--config=monolithic  	# Config for mostly static monolithic build.
	--config=ngraph      	# Build with Intel nGraph support.
	--config=numa        	# Build with NUMA support.
	--config=dynamic_kernels	# (Experimental) Build kernels into separate shared objects.
	--config=v2          	# Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
	--config=noaws       	# Disable AWS S3 filesystem support.
	--config=nogcp       	# Disable GCP support.
	--config=nohdfs      	# Disable HDFS support.
	--config=nonccl      	# Disable NVIDIA NCCL support.
Configuration finished

when build blow error is happen and abend build...

ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
	File "/home/owner/Downloads/tensorflow-2.2.0/third_party/gpus/cuda_configure.bzl", line 1210
		_create_local_cuda_repository(<1 more arguments>)
	File "/home/owner/Downloads/tensorflow-2.2.0/third_party/gpus/cuda_configure.bzl", line 934, in _create_local_cuda_repository
		_find_libs(repository_ctx, <2 more arguments>)
	File "/home/owner/Downloads/tensorflow-2.2.0/third_party/gpus/cuda_configure.bzl", line 577, in _find_libs
		_check_cuda_libs(repository_ctx, <2 more arguments>)
	File "/home/owner/Downloads/tensorflow-2.2.0/third_party/gpus/cuda_configure.bzl", line 479, in _check_cuda_libs
		execute(repository_ctx, <1 more arguments>)
	File "/home/owner/Downloads/tensorflow-2.2.0/third_party/remote_config/common.bzl", line 208, in execute
		fail(<1 more arguments>)
Repository command failed
Traceback (most recent call last):
  File "script.py", line 88, in <module>
    main()
  File "script.py", line 77, in main
    check_cuda_lib(path, check_soname=args[i + 1] == "True")
  File "script.py", line 62, in check_cuda_lib
    output = subprocess.check_output([objdump, "-p", path]).decode("ascii")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 40: ordinal not in range(128)
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/owner/Downloads/tensorflow-2.2.0/third_party/gpus/cuda_configure.bzl", line 1210
		_create_local_cuda_repository(<1 more arguments>)
	File "/home/owner/Downloads/tensorflow-2.2.0/third_party/gpus/cuda_configure.bzl", line 934, in _create_local_cuda_repository
		_find_libs(repository_ctx, <2 more arguments>)
	File "/home/owner/Downloads/tensorflow-2.2.0/third_party/gpus/cuda_configure.bzl", line 577, in _find_libs
		_check_cuda_libs(repository_ctx, <2 more arguments>)
	File "/home/owner/Downloads/tensorflow-2.2.0/third_party/gpus/cuda_configure.bzl", line 479, in _check_cuda_libs
		execute(repository_ctx, <1 more arguments>)
	File "/home/owner/Downloads/tensorflow-2.2.0/third_party/remote_config/common.bzl", line 208, in execute
		fail(<1 more arguments>)
Repository command failed
Traceback (most recent call last):
  File "script.py", line 88, in <module>
    main()
  File "script.py", line 77, in main
    check_cuda_lib(path, check_soname=args[i + 1] == "True")
  File "script.py", line 62, in check_cuda_lib
    output = subprocess.check_output([objdump, "-p", path]).decode("ascii")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 40: ordinal not in range(128)
WARNING: Target pattern parsing failed.
ERROR: no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/owner/Downloads/tensorflow-2.2.0/third_party/gpus/cuda_configure.bzl", line 1210
		_create_local_cuda_repository(<1 more arguments>)
	File "/home/owner/Downloads/tensorflow-2.2.0/third_party/gpus/cuda_configure.bzl", line 934, in _create_local_cuda_repository
		_find_libs(repository_ctx, <2 more arguments>)
	File "/home/owner/Downloads/tensorflow-2.2.0/third_party/gpus/cuda_configure.bzl", line 577, in _find_libs
		_check_cuda_libs(repository_ctx, <2 more arguments>)
	File "/home/owner/Downloads/tensorflow-2.2.0/third_party/gpus/cuda_configure.bzl", line 479, in _check_cuda_libs
		execute(repository_ctx, <1 more arguments>)
	File "/home/owner/Downloads/tensorflow-2.2.0/third_party/remote_config/common.bzl", line 208, in execute
		fail(<1 more arguments>)
Repository command failed
Traceback (most recent call last):
  File "script.py", line 88, in <module>
    main()
  File "script.py", line 77, in main
    check_cuda_lib(path, check_soname=args[i + 1] == "True")
  File "script.py", line 62, in check_cuda_lib
    output = subprocess.check_output([objdump, "-p", path]).decode("ascii")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 40: ordinal not in range(128)
INFO: Elapsed time: 0.404s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package

**Comment by aoki897** [comment]
a new error is :Fetching ...docker; Cloning 251f6a68b439744094faff800cd029798edf9faa of ht\
tps://github.com/bazelbuild/rules_docker.git.it can`t clone reles_docker.git
