### ISSUE TITLE
SyntaxError: invalid syntax && ImportError: cannot import name pywrap_tensorflow

### ISSUE THREAD

**Issue by zdj-creator** [tensorflow/tensorflow#52282]
**System information**
- Linux Ubuntu 16.04
- TensorFlow version: tensorflow-gpu 1.5
- Python version: 2.7
- Installed using virtualenv: pip
- CUDA/cuDNN version: CUDA9.0 & CUDNN7.0

**Describe the problem**
    Using anaconda to create a virtual environment named tf.
```
(tf) ➜  ~ python                         
Python 2.7.18 |Anaconda, Inc.| (default, Jun  4 2021, 14:47:46) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xander/anaconda3/envs/tf/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/xander/anaconda3/envs/tf/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/xander/anaconda3/envs/tf/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/home/xander/anaconda3/envs/tf/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 113
    class DescriptorBase(metaclass=DescriptorMetaclass):
                                  ^
SyntaxError: invalid syntax
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xander/anaconda3/envs/tf/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/xander/anaconda3/envs/tf/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
ImportError: cannot import name pywrap_tensorflow
```

**Comment by zdj-creator** [comment]
Thanks for your  reply! @mohantym 
I have tried many times, and the env name is not the problem.And older versions are often preferred in production environments.
Whatever,Thanks.

**Comment by mohantym** [comment]
Hi @zdj-creator , Did you try with python 3.6  yet? 
[Reference](https://stackoverflow.com/questions/60705802/importerror-cannot-import-name-pywrap-tensorflow)

**Comment by zdj-creator** [comment]
Sorry,the existing code is based on python 2.7.Let me try it later.
