### ISSUE TITLE
Problems to convert a TF model with mutable variables even if I use converter.experimental_enable_resource_variables = True

### ISSUE THREAD

**Issue by sunw70** [tensorflow/tensorflow#52330]
### System information

- OS Platform and Distribution: Linux Ubuntu 20.10
- TensorFlow installation: pip package
- Tensorflow version: 2.6.0
-  Python version: 3.8

I'm trying to convert a TF model which uses a custom layer where there are some tf.Variable (instead of numpy arrays for partial computations) and for loops statements (not tf.while_loop statements). The model works fine without the custom layer. 
In order to convert the model I use these lines of code:

    tmpdir = tempfile.mkdtemp()
    model_save_path = os.path.join(tmpdir, "model/1/")
    tf.saved_model.save(model, model_save_path) 
    
    converter = tf.lite.TFLiteConverter.from_saved_model(model_save_path)
    converter.target_spec.supported_ops = [
       tf.lite.OpsSet.TFLITE_BUILTINS, 
       tf.lite.OpsSet.SELECT_TF_OPS 
    ]
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    tflite_model = converter.convert()
    with open('model.tflite', 'wb') as f:
       f.write(tflite_model)

However I get this error:
    
    WARNING:absl:Found untraced functions such as mylayer_layer_call_and_return_conditional_losses, mylayer_layer_call_fn,     
    mylayer_layer_call_fn, mylayer_layer_call_and_return_conditional_losses, mylayer_layer_call_and_return_conditional_losses    
    while saving (showing 5 of 5). These functions will not be directly callable after loading.
    2021-10-11 19:37:04.586845: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:351] Ignored output_format.
    2021-10-11 19:37:04.586883: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:354] Ignored     
    drop_control_dependency.
    2021-10-11 19:37:04.586892: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:360] Ignored   
    change_concat_input_ranges.
    2021-10-11 19:37:04.587804: I tensorflow/cc/saved_model/reader.cc:38] Reading SavedModel from: /tmp/tmp332hc4f9  
    /model/1/
    2021-10-11 19:37:04.647880: I tensorflow/cc/saved_model/reader.cc:90] Reading meta graph with tags { serve }
    2021-10-11 19:37:04.647960: I tensorflow/cc/saved_model/reader.cc:132] Reading SavedModel debug info (if present) from:     
    /tmp/tmp332hc4f9/model/1/
    2021-10-11 19:37:04.990385: I tensorflow/cc/saved_model/loader.cc:211] Restoring SavedModel bundle.
    2021-10-11 19:37:05.508553: I tensorflow/cc/saved_model/loader.cc:195] Running initialization op on SavedModel bundle at   
    path: /tmp/tmp332hc4f9/model/1/
    2021-10-11 19:37:05.985453: I tensorflow/cc/saved_model/loader.cc:283] SavedModel load for tags { serve }; Status: success: 
    OK. Took 1397650 microseconds.
    2021-10-11 19:37:07.818608: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:210] disabling MLIR crash 
    reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
    loc("module_wrapper/mylayer/Variable"): error: is not immutable, try removing mutable variables in your model since mutable 
    variables are currently not supported through this converter
    Traceback (most recent call last):
    File "model.py", line 231, in <module>
    tflite_model = converter.convert()
    File "/home/es/venv/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 729, in wrapper
    return self._convert_and_export_metrics(convert_func, *args, **kwargs)
    File "/home/es/venv/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 715, in _convert_and_export_metrics
    result = convert_func(self, *args, **kwargs)
    File "/home/es/venv/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 994, in convert
    result = _convert_saved_model(**converter_kwargs)
    File "/home/es/venv/lib/python3.8/site-packages/tensorflow/lite/python/convert_phase.py", line 215, in wrapper
    raise converter_error from None  # Re-throws the exception.
    File "/home/es/venv/lib/python3.8/site-packages/tensorflow/lite/python/convert_phase.py", line 208, in wrapper
    return func(*args, **kwargs)
    File "/home/es/venv/lib/python3.8/site-packages/tensorflow/lite/python/convert.py", line 821, in convert_saved_model
    data = toco_convert_protos(
    File "/home/es/venv/lib/python3.8/site-packages/tensorflow/lite/python/convert.py", line 313, in toco_convert_protos
    raise converter_error
    tensorflow.lite.python.convert_phase.ConverterError: <unknown>:0: error: loc("module_wrapper/mylayer/Variable"): is not   
    immutable, try removing mutable variables in your model since mutable variables are currently not supported through this    
    converter

Instead, if I add this line:
  
    converter.experimental_enable_resource_variables =True

I get this:

    WARNING:absl:Found untraced functions such as mylayer_layer_call_and_return_conditional_losses, mylayer_layer_call_fn,     
    mylayer_layer_call_fn, mylayer_layer_call_and_return_conditional_losses, mylayer_layer_call_and_return_conditional_losses    
    while saving (showing 5 of 5). These functions will not be directly callable after loading.
    2021-10-11 19:37:04.586845: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:351] Ignored output_format.
    2021-10-11 19:37:04.586883: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:354] Ignored     
    drop_control_dependency.
    2021-10-11 19:37:04.586892: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:360] Ignored   
    change_concat_input_ranges.
    2021-10-11 19:37:04.587804: I tensorflow/cc/saved_model/reader.cc:38] Reading SavedModel from: /tmp/tmp332hc4f9  
    /model/1/
    2021-10-11 19:37:04.647880: I tensorflow/cc/saved_model/reader.cc:90] Reading meta graph with tags { serve }
    2021-10-11 19:37:04.647960: I tensorflow/cc/saved_model/reader.cc:132] Reading SavedModel debug info (if present) from:     
    /tmp/tmp332hc4f9/model/1/
    2021-10-11 19:37:04.990385: I tensorflow/cc/saved_model/loader.cc:211] Restoring SavedModel bundle.
    2021-10-11 19:37:05.508553: I tensorflow/cc/saved_model/loader.cc:195] Running initialization op on SavedModel bundle at   
    path: /tmp/tmp332hc4f9/model/1/
    2021-10-11 19:37:05.985453: I tensorflow/cc/saved_model/loader.cc:283] SavedModel load for tags { serve }; Status: success: 
    OK. Took 1397650 microseconds.
    2021-10-11 19:37:07.818608: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:210] disabling MLIR crash 
    reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.

    segmentation fault (core dumped)

With these lines:

    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.target_spec.supported_ops = [
       tf.lite.OpsSet.TFLITE_BUILTINS, 
       tf.lite.OpsSet.SELECT_TF_OPS 
    ]
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    tflite_model = converter.convert()
    with open('model.tflite', 'wb') as f:
       f.write(tflite_model)

I have this error:
   
    WARNING:absl:Found untraced functions such as mylayer_layer_call_fn, mylayer_layer_call_and_return_conditional_losses, 
    mylayer_layer_call_fn, mylayer_layer_call_and_return_conditional_losses, mylayer_layer_call_and_return_conditional_losses 
    while saving (showing 5 of 5). These functions will not be directly callable after loading.
    2021-10-11 19:57:58.096866: I tensorflow/core/grappler/devices.cc:66] Number of eligible GPUs (core count >= 8, compute    
    capability >= 0.0): 0
    2021-10-11 19:57:58.097108: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
    2021-10-11 19:58:00.117971: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:1137] Optimization results for grappler   
    item: graph_to_optimize
    function_optimizer: Graph size after: 41 nodes (24), 46 edges (27), time = 273.451ms.
    function_optimizer: Graph size after: 41 nodes (0), 46 edges (0), time = 471.521ms.
    Optimization results for grappler item: while_body_119
    function_optimizer: function_optimizer did nothing. time = 0.019ms.
    function_optimizer: function_optimizer did nothing. time = 0.002ms.
    Optimization results for grappler item: while_cond_118
    function_optimizer: function_optimizer did nothing. time = 0.015ms.
    function_optimizer: function_optimizer did nothing. time = 0.002ms.

    Traceback (most recent call last):
    File "model.py", line 231, in <module>
    tflite_model = converter.convert()
    File "/home/es/venv/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 729, in wrapper
    return self._convert_and_export_metrics(convert_func, *args, **kwargs)
    File "/home/es/venv/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 715, in _convert_and_export_metrics
    result = convert_func(self, *args, **kwargs)
    File "/home/es/venv/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 1123, in convert
    self._freeze_keras_model())
    File "/home/es/venv/lib/python3.8/site-packages/tensorflow/lite/python/convert_phase.py", line 218, in wrapper
    raise error from None  # Re-throws the exception.
    File "/home/es/venv/lib/python3.8/site-packages/tensorflow/lite/python/convert_phase.py", line 208, in wrapper
    return func(*args, **kwargs)
    File "/home/es/venv/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 1079, in _freeze_keras_model
    _convert_to_constants.convert_variables_to_constants_v2_as_graph(
    File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/framework/convert_to_constants.py", line 1234, in    
    convert_variables_to_constants_v2_as_graph
    frozen_func = _construct_concrete_function(func, output_graph_def,
    File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/framework/convert_to_constants.py", line 1078, in    
    _construct_concrete_function
    new_func = wrap_function.function_from_graph_def(output_graph_def,
    File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/eager/wrap_function.py", line 650, in    
    function_from_graph_def
    wrapped_import = wrap_function(_imports_graph_def, [])
    File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/eager/wrap_function.py", line 621, in wrap_function
    func_graph.func_graph_from_py_func(
    File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 1007, in   
    func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
     File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/eager/wrap_function.py", line 87, in __call__
     return self.call_with_variable_creator_scope(self._fn)(*args, **kwargs)
     File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/eager/wrap_function.py", line 93, in wrapped
     return fn(*args, **kwargs)
     File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/eager/wrap_function.py", line 648, in _imports_graph_def
     importer.import_graph_def(graph_def, name="")
     File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py", line 549, in new_func
     return func(*args, **kwargs)
     File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/framework/importer.py", line 400, in import_graph_def
     return _import_graph_def_internal(
     File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/framework/importer.py", line 501, in     
      _import_graph_def_internal
      raise ValueError(str(e))

     ValueError: Input 0 of node sequential/module_wrapper/mylayer/StatefulPartitionedCall/AssignVariableOp was passed int32     
     from Func/sequential/module_wrapper/mylayer/StatefulPartitionedCall/input/_1:0 incompatible with expected resource.

**Comment by mohantym** [comment]
Hi @sunw70 !
Work around is to add the op from OpResolver in the C++ code.

```
static tflite::MicroMutableOpResolver<1> micro_op_resolver; /* no of times I have added any ops through ops resolver
micro_op_resolver.AddWhile(); /*Adding while op */
```
[Ref](https://github.com/tensorflow/tflite-micro/issues/284#issuecomment-880339107)


Thank you!
