### ISSUE TITLE
Tensorflow 2.5 and above causes crash on load on Ubuntu 20.04

### ISSUE THREAD

**Issue by sbrl** [tensorflow/tensorflow#52384]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: Ubuntu 20.04
- TensorFlow installed from (source or binary): `sudo pip3 install tensorflow`
- TensorFlow version: 2.5+
- Python version: 3.8.10
- Installed using virtualenv? pip? conda?: pip `sudo pip3 install tensorflow`
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): Not relevant, but `gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0`
- CUDA/cuDNN version: Not installed
- GPU model and memory: GeForce GTX 750 Ti [nouveau drivers installed, CUDA is NOT installed, not currently using the GPU]

**Describe the problem**

If I install Tensorflow 2.5 or above and then attempt to import it in a simple Python program, it causes an instant and highly reproducible crash.

I don't care about GPU support. I just want to be able to use Tensorflow at all....

**Provide the exact sequence of commands / steps that you executed before running into the problem**

First, install Tensorflow:

```bash
sudo pip3 install tensorflow==2.5
```

OR

```bash
sudo pip3 install tensorflow==2.6
```

OR

```bash
sudo pip3 install tensorflow
```

Then, create a simple test program:

```python
#/usr/bin/env python3

import tensorflow as tf

print(tf.__version__)
```

Finally, chmod and run the test program:

```bash
chmod +x path/to/test.py
path/to/test.py
```

See crash.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Example crash from tensorflow 2.5:

```
2021-10-14 16:46:53.912576: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-10-14 16:46:53.912599: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "./src/image_classifier.py", line 10, in <module>
    import tensorflow as tf
  File "/home/bryan-smithl/.local/lib/python3.8/site-packages/tensorflow/__init__.py", line 436, in <module>
    _ll.load_library(_main_dir)
  File "/home/bryan-smithl/.local/lib/python3.8/site-packages/tensorflow/python/framework/load_library.py", line 153, in load_library
    py_tf.TF_LoadLibrary(lib)
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.8/dist-packages/tensorflow/core/kernels/libtfkernel_sobol_op.so: undefined symbol: _ZN10tensorflow6StatusC1ENS_5error4CodeEN4absl14lts_2020_09_2311string_viewEOSt6vectorINS_10StackFrameESaIS7_EE
````

Example crash from Tensorflow 2.6:

```
2021-10-14 16:40:43.830370: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-10-14 16:40:43.830389: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "./src/image_classifier.py", line 10, in <module>
    import tensorflow as tf
  File "/home/bryan-smithl/.local/lib/python3.8/site-packages/tensorflow/__init__.py", line 436, in <module>
    _ll.load_library(_main_dir)
  File "/home/bryan-smithl/.local/lib/python3.8/site-packages/tensorflow/python/framework/load_library.py", line 153, in load_library
    py_tf.TF_LoadLibrary(lib)
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.8/dist-packages/tensorflow/core/kernels/libtfkernel_sobol_op.so: undefined symbol: _ZN10tensorflow14kernel_factory17OpKernelRegistrar12InitInternalEPKNS_9KernelDefEN4absl12lts_2021032411string_viewESt10unique_ptrINS0_15OpKernelFactoryESt14default_deleteIS9_EE
````

Tensorflow 2.4 and below work fine:

```
2021-10-14 16:53:07.554556: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-10-14 16:53:07.554582: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2.4.1
```

**Comment by sbrl** [comment]
> this guide

That's even worse. If I follow that guide to the letter, `tensorflow` fails to install:

```
$ pip3 install --user --upgrade tensorflow
Requirement already satisfied: tensorflow in /home/bryan-smithl/.local/lib/python3.8/site-packages (2.4.1)
Collecting tensorflow
  Downloading tensorflow-2.6.0-cp38-cp38-manylinux2010_x86_64.whl (458.4 MB)
     |████████████████████████████████| 458.4 MB 51 kB/s               
Collecting grpcio<2.0,>=1.37.0
  Downloading grpcio-1.41.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.9 MB)
     |████████████████████████████████| 3.9 MB 53.4 MB/s            
Requirement already satisfied: numpy~=1.19.2 in /home/bryan-smithl/.local/lib/python3.8/site-packages (from tensorflow) (1.19.5)
Requirement already satisfied: astunparse~=1.6.3 in /home/bryan-smithl/.local/lib/python3.8/site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: keras-preprocessing~=1.1.2 in /home/bryan-smithl/.local/lib/python3.8/site-packages (from tensorflow) (1.1.2)
Requirement already satisfied: flatbuffers~=1.12.0 in /home/bryan-smithl/.local/lib/python3.8/site-packages (from tensorflow) (1.12)
Requirement already satisfied: absl-py~=0.10 in /home/bryan-smithl/.local/lib/python3.8/site-packages (from tensorflow) (0.12.0)
Collecting h5py~=3.1.0
  Downloading h5py-3.1.0-cp38-cp38-manylinux1_x86_64.whl (4.4 MB)
     |████████████████████████████████| 4.4 MB 66.5 MB/s            
Collecting wheel~=0.35
  Downloading wheel-0.37.0-py2.py3-none-any.whl (35 kB)
Requirement already satisfied: google-pasta~=0.2 in /home/bryan-smithl/.local/lib/python3.8/site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: opt-einsum~=3.3.0 in /home/bryan-smithl/.local/lib/python3.8/site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: termcolor~=1.1.0 in /home/bryan-smithl/.local/lib/python3.8/site-packages (from tensorflow) (1.1.0)
Requirement already satisfied: keras~=2.6 in /usr/local/lib/python3.8/dist-packages (from tensorflow) (2.6.0)
Requirement already satisfied: protobuf>=3.9.2 in /home/bryan-smithl/.local/lib/python3.8/site-packages (from tensorflow) (3.17.0)
Requirement already satisfied: wrapt~=1.12.1 in /home/bryan-smithl/.local/lib/python3.8/site-packages (from tensorflow) (1.12.1)
Collecting gast==0.4.0
  Downloading gast-0.4.0-py3-none-any.whl (9.8 kB)
Requirement already satisfied: clang~=5.0 in /usr/local/lib/python3.8/dist-packages (from tensorflow) (5.0)
Requirement already satisfied: typing-extensions~=3.7.4 in /home/bryan-smithl/.local/lib/python3.8/site-packages (from tensorflow) (3.7.4.3)
Collecting tensorboard~=2.6
  Downloading tensorboard-2.7.0-py3-none-any.whl (5.8 MB)
     |████████████████████████████████| 5.8 MB 82.1 MB/s            
Collecting tensorflow-estimator~=2.6
  Downloading tensorflow_estimator-2.6.0-py2.py3-none-any.whl (462 kB)
     |████████████████████████████████| 462 kB 46.6 MB/s            
Requirement already satisfied: six~=1.15.0 in /home/bryan-smithl/.local/lib/python3.8/site-packages (from tensorflow) (1.15.0)
Requirement already satisfied: werkzeug>=0.11.15 in /home/bryan-smithl/.local/lib/python3.8/site-packages (from tensorboard~=2.6->tensorflow) (2.0.0)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/lib/python3/dist-packages (from tensorboard~=2.6->tensorflow) (2.22.0)
Requirement already satisfied: setuptools>=41.0.0 in ./lib/python3.8/site-packages (from tensorboard~=2.6->tensorflow) (44.0.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /home/bryan-smithl/.local/lib/python3.8/site-packages (from tensorboard~=2.6->tensorflow) (0.4.4)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /home/bryan-smithl/.local/lib/python3.8/site-packages (from tensorboard~=2.6->tensorflow) (0.6.1)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /home/bryan-smithl/.local/lib/python3.8/site-packages (from tensorboard~=2.6->tensorflow) (1.8.0)
Requirement already satisfied: google-auth<3,>=1.6.3 in /home/bryan-smithl/.local/lib/python3.8/site-packages (from tensorboard~=2.6->tensorflow) (1.30.0)
Requirement already satisfied: markdown>=2.6.8 in /home/bryan-smithl/.local/lib/python3.8/site-packages (from tensorboard~=2.6->tensorflow) (3.3.4)
Requirement already satisfied: rsa<5,>=3.1.4 in /home/bryan-smithl/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard~=2.6->tensorflow) (4.7.2)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /home/bryan-smithl/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard~=2.6->tensorflow) (4.2.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/bryan-smithl/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard~=2.6->tensorflow) (0.2.8)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/bryan-smithl/.local/lib/python3.8/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.6->tensorflow) (1.3.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/bryan-smithl/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard~=2.6->tensorflow) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/lib/python3/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.6->tensorflow) (3.1.0)
ERROR: Will not install to the user site because it will lack sys.path precedence to wheel in /home/bryan-smithl/Documents/venv-tensorflow/lib/python3.8/site-packages
```

> conda install cudatoolkit

I don't have conda installed.

> similar issue #45930,link

No helpful. Both of these are about CUDA support. I **do not care about CUDA or GPU support**.

**Comment by Saduf2019** [comment]
After which  you may , Prepare  venv with this version and install tensorflow with pip inside the venv and let us know.

**Comment by sbrl** [comment]
I'm not sure what you're asking @Saduf2019. Can you clarify please?
