### ISSUE TITLE
Multilingual Universal Sentence Encoder  Quantization-aware training error

### ISSUE THREAD

**Issue by ns-xinjun** [tensorflow/tensorflow#52387]
### 1. System information

- OS Platform and Distribution: Ubuntu 20.04.2
- TensorFlow installation : 2.6.0

### 2. Code
```
def create_model():        
       hub_layer = hub.KerasLayer("https://tfhub.dev/google/universal-sentence-encoder-multilingual/3", input_shape=[], 
                           dtype=tf.string, trainable=False)
        model = tf.keras.Sequential()
        model.add(hub_layer)
        model.add(tf.keras.layers.Dense(64, activation='relu'))
        model.add(tf.keras.layers.Dense(1, activation='softmax'))
        optimizer = SGD(lr=0.001, momentum=0.6, decay=1e-6)
        model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
        model.summary()
        return model

custom_objects={'KerasLayer':hub.KerasLayer}        
base_model = create_model()
with tfmot.quantization.keras.quantize_scope(custom_objects):
    q_model = tfmot.quantization.keras.quantize_model(base_model)
q_model.compile(loss=self.model_param.loss, optimizer=optimizer, metrics=self.model_param.metrics)

history = q_model.fit()
q_model.save(model_file_name)

converter = tf.lite.TFLiteConverter.from_keras_model(q_model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
    tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
    ]
quantized_tflite_model = converter.convert()
```

### 3. Failure after conversion
Conversion failed at this part :
```
with tfmot.quantization.keras.quantize_scope(custom_objects):
    q_model = tfmot.quantization.keras.quantize_model(base_model)
```
Below is the error message:

```
Traceback (most recent call last):
  File "/home/user/quant_model_multilingual.py", line 125, in qat
    **q_model = tfmot.quantization.keras.quantize_model(base_model)**
  File "/home/user/py38/lib/python3.8/site-packages/tensorflow_model_optimization/python/core/quantization/keras/quantize.py", line 138, in quantize_model
    **return quantize_apply(annotated_model)**
  File "/home/user/py38/lib/python3.8/site-packages/tensorflow_model_optimization/python/core/keras/metrics.py", line 71, in inner
    raise error
  File "/home/user/py38/lib/python3.8/site-packages/tensorflow_model_optimization/python/core/keras/metrics.py", line 66, in inner
    results = func(*args, **kwargs)
  File "/home/user/py38/lib/python3.8/site-packages/tensorflow_model_optimization/python/core/quantization/keras/quantize.py", line 436, in quantize_apply
    transformed_model, layer_quantize_map = quantize_transform.apply(
  File "/home/user/py38/lib/python3.8/site-packages/tensorflow_model_optimization/python/core/quantization/keras/default_8bit/default_8bit_quantize_layout_transform.py", line 71, in apply
    return model_transformer.ModelTransformer(
  File "/home/user/py38/lib/python3.8/site-packages/tensorflow_model_optimization/python/core/quantization/keras/graph_transformations/model_transformer.py", line 622, in transform
    transformed_model = keras.Sequential.from_config(self._config,
  File "/home/user/py38/lib/python3.8/site-packages/keras/engine/sequential.py", line 434, in from_config
    model.add(layer)
  File "/home/user/py38/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py", line 530, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/user/py38/lib/python3.8/site-packages/keras/engine/sequential.py", line 217, in add
    output_tensor = layer(self.outputs[0])
  File "/home/user/py38/lib/python3.8/site-packages/keras/engine/base_layer.py", line 976, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "/home/user/py38/lib/python3.8/site-packages/keras/engine/base_layer.py", line 1114, in _functional_construction_call
    outputs = self._keras_tensor_symbolic_call(
  File "/home/user/py38/lib/python3.8/site-packages/keras/engine/base_layer.py", line 848, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/home/user/py38/lib/python3.8/site-packages/keras/engine/base_layer.py", line 888, in _infer_output_signature
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/user/py38/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 695, in wrapper
    raise e.ag_error_metadata.to_exception(e)

    /home/user/py38/lib/python3.8/site-packages/tensorflow_model_optimization/python/core/quantization/keras/quantize_layer.py:69 quantizer_fn  *
        inputs, train_var,
    /home/user/py38/lib/python3.8/site-packages/tensorflow_model_optimization/python/core/keras/utils.py:54 smart_cond  *
        pred, true_fn=true_fn, false_fn=false_fn, name=name)
    /home/user/py38/lib/python3.8/site-packages/tensorflow_model_optimization/python/core/quantization/keras/quantizers.py:341 __call__  *
        weights['max_var'],
    /home/user/py38/lib/python3.8/site-packages/tensorflow_model_optimization/python/core/quantization/keras/quant_ops.py:79 AllValuesQuantize  *
        max_var,
    /home/user/py38/lib/python3.8/site-packages/tensorflow_model_optimization/python/core/quantization/keras/quant_ops.py:340 _FakeQuantWithMinMaxVars  *
        inputs, min_var, max_var, num_bits=num_bits, narrow_range=narrow_range)
    /home/user/py38/lib/python3.8/site-packages/tensorflow/python/ops/gen_array_ops.py:2890 fake_quant_with_min_max_vars  **
        _, _, _op, _outputs = _op_def_library._apply_op_helper(
    /home/user/py38/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py:544 _apply_op_helper
        raise TypeError("%s expected type of %s." %

    TypeError: Input 'inputs' of 'FakeQuantWithMinMaxVars' Op has type string that does not match expected type of float32.
```

It seems that the error is caused because "multilingual universal sentence encoder" has input type as tf.string, and the output to the dense layer is float32.

**Comment by sushreebarsa** [comment]
@ns-xinjun In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!
