### ISSUE TITLE
TensorRT ValueError Input 1 of node StatefulPartitionedCall was passed float from unknown:0 incompatible with expected resource

### ISSUE THREAD

**Issue by hotpeppeper** [tensorflow/tensorflow#52540]
**faild to use trt_convert to convert tensorflow .pb file to tensorrt**
**model code:**
```
inputs = keras.Input(shape=(200,), dtype="int32")
# Embed each integer in a 128-dimensional vector
x = layers.Embedding(max_features, 256)(inputs)
# Add 2 bidirectional LSTMs
# x = layers.Bidirectional(layers.LSTM(64, return_sequences=True))(x)
# x = layers.Bidirectional(layers.LSTM(64))(x)
x = layers.LSTM(64)(x)
# Add a classifier
outputs = layers.Dense(1, activation="sigmoid")(x)
model = keras.Model(inputs, outputs)
```
**convter pb to trt code**
```
model_dir = '/data/danlu/tensorrt/resnet/lstm'
opt_model_dir = '/data/danlu/tensorrt/resnet/lstm_trt'
 
precision = "FP32"
max_workspace_size_bytes = 8000000000
conversion_params = tf_trt.DEFAULT_TRT_CONVERSION_PARAMS._replace(precision_mode=precision,
                                                                  max_workspace_size_bytes=max_workspace_size_bytes,
                                                                  maximum_cached_engines=100)
converter = tf_trt.TrtGraphConverterV2(input_saved_model_dir=model_dir, conversion_params=conversion_params)
converter.convert()
 
 
def build_fn():
    Inp1 = np.random.randint(1, 200, (1, 200), dtype=np.int32)
    yield Inp1
 
 
converter.build(input_fn=build_fn)
converter.save(opt_model_dir)
```
**pb file**
[https://drive.google.com/file/d/1M4TEB3t1SDpBFj-RS7WL8AuWybZaP1YZ/view?usp=sharing](url)

**env:**
os: ubutun 16.04
python: 3.8.3
tensorflow: 2.6.0
TensorRT: 7.2.3.4
cuda: 10.2
gpu: v100:32g

**error log**
```
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/importer.py", line 496, in _import_graph_def_internal
    results = c_api.TF_GraphImportGraphDefWithResults(
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 1 of node StatefulPartitionedCall was passed float from unknown:0 incompatible with expected resource.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "trt_transfer.py", line 21, in <module>
    converter.convert()
  File "/root/anaconda3/lib/python3.8/site-packages/tensorflow/python/compiler/tensorrt/trt_convert.py", line 1087, in convert
    frozen_func = convert_to_constants.convert_variables_to_constants_v2(func)
  File "/root/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/convert_to_constants.py", line 1074, in convert_variables_to_constants_v2
    return _construct_concrete_function(func, output_graph_def,
  File "/root/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/convert_to_constants.py", line 999, in _construct_concrete_function
    new_func = wrap_function.function_from_graph_def(output_graph_def,
  File "/root/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/wrap_function.py", line 650, in function_from_graph_def
    wrapped_import = wrap_function(_imports_graph_def, [])
  File "/root/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/wrap_function.py", line 621, in wrap_function
    func_graph.func_graph_from_py_func(
  File "/root/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/wrap_function.py", line 87, in __call__
    return self.call_with_variable_creator_scope(self._fn)(*args, **kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/wrap_function.py", line 93, in wrapped
    return fn(*args, **kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/wrap_function.py", line 648, in _imports_graph_def
    importer.import_graph_def(graph_def, name="")
  File "/root/anaconda3/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/importer.py", line 400, in import_graph_def
    return _import_graph_def_internal(
  File "/root/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/importer.py", line 501, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: Input 1 of node StatefulPartitionedCall was passed float from unknown:0 incompatible with expected resource.
```

**Comment by mohantym** [comment]
Hi @hotpeppeper ! Could you look at these threads for answer ? [Link1](https://forums.developer.nvidia.com/t/valueerror-input-1-of-node-statefulpartitionedcall-was-passed-float-from-conv2d-kernel-0-incompatible-with-expected-resource/112608),[Link2](https://forums.developer.nvidia.com/t/incompatible-with-expected-resource/72935#5356209),[Link3](https://github.com/onnx/tensorflow-onnx/issues/1152) . Thanks!

**Comment by GuoGuiRong** [comment]
> Hi @hotpeppeper ! Could you look at these threads for answer ? [Link1](https://forums.developer.nvidia.com/t/valueerror-input-1-of-node-statefulpartitionedcall-was-passed-float-from-conv2d-kernel-0-incompatible-with-expected-resource/112608),[Link2](https://forums.developer.nvidia.com/t/incompatible-with-expected-resource/72935#5356209),[Link3](https://github.com/onnx/tensorflow-onnx/issues/1152) . Thanks!

This may not have any help, I still don't know how to resolve my problem

**Comment by mohantym** [comment]
Hi @GuoGuiRong ! Could you please check this [gist ](https://colab.sandbox.google.com/gist/mohantym/1812947bb3bad58b48eeddd9f43d79f1/github_52540.ipynb#scrollTo=H3yfLjsFKM6c) and let us know after configuring TensorRT?
