### ISSUE TITLE
Numpy 1.21.2/3 Causing Feature Column Unit Test Failures

### ISSUE THREAD

**Issue by wei-v-wang** [tensorflow/tensorflow#52657]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): latest test was with https://github.com/tensorflow/tensorflow/commit/94bc26a5f71ad14f2390def5a6ecead451f7c9bc (an Oct'25 2021 commit on main branch)
- Python version: 3.8
- Bazel version (if compiling from source): "We have bazel 3.7.2 installed."
- GCC/Compiler version (if compiling from source): gcc-7
- CUDA/cuDNN version: NA
- GPU model and memory: NA

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
This commit bumped up numpy version. https://github.com/tensorflow/tensorflow/commit/f96917ea887d1108358132c9dc9a0a0366e7d69e
Many CI relies on the above file to run their nightlies. 
//tensorflow/python/feature_column:feature_column_test unit test failures with numpy 1.21.2 or numpy 1.21.3 with the following error message. numpy 1.19.5 was successful. 

[2021-10-25T12:40:03.025Z] ERROR: test_fills_cols_to_vars (__main__.LinearModelTest)
[2021-10-25T12:40:03.025Z] LinearModelTest.test_fills_cols_to_vars
[2021-10-25T12:40:03.025Z] ----------------------------------------------------------------------
[2021-10-25T12:40:03.025Z] Traceback (most recent call last):
[2021-10-25T12:40:03.025Z]   File "/home/tensorflow_ci_jenkins/workspace/workspace/workspace/tensorflow-eigen-test/bazel-ci_build-cache/.cache/bazel/_bazel_tensorflow_ci_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/feature_column/feature_column_test.runfiles/org_tensorflow/tensorflow/python/feature_column/feature_column_test.py", line 1612, in test_fills_cols_to_vars
[2021-10-25T12:40:03.025Z]     self.assertAllEqual(cols_to_vars['bias'], [bias])
[2021-10-25T12:40:03.025Z]   File "/home/tensorflow_ci_jenkins/workspace/workspace/workspace/tensorflow-eigen-test/bazel-ci_build-cache/.cache/bazel/_bazel_tensorflow_ci_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/feature_column/feature_column_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 1390, in decorated
[2021-10-25T12:40:03.025Z]     return f(*args, **kwds)
[2021-10-25T12:40:03.025Z]   File "/home/tensorflow_ci_jenkins/workspace/workspace/workspace/tensorflow-eigen-test/bazel-ci_build-cache/.cache/bazel/_bazel_tensorflow_ci_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/feature_column/feature_column_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 3055, in assertAllEqual
[2021-10-25T12:40:03.025Z]     a = self._GetNdArray(a)
[2021-10-25T12:40:03.025Z]   File "/home/tensorflow_ci_jenkins/workspace/workspace/workspace/tensorflow-eigen-test/bazel-ci_build-cache/.cache/bazel/_bazel_tensorflow_ci_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/feature_column/feature_column_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 2799, in _GetNdArray
[2021-10-25T12:40:03.025Z]     return np.array(a)
[2021-10-25T12:40:03.025Z]   File "/home/tensorflow_ci_jenkins/workspace/workspace/workspace/tensorflow-eigen-test/bazel-ci_build-cache/.cache/bazel/_bazel_tensorflow_ci_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/feature_column/feature_column_test.runfiles/org_tensorflow/tensorflow/python/ops/resource_variable_ops.py", line 534, in __array__
[2021-10-25T12:40:03.025Z]     return np.asarray(self.numpy(), dtype=dtype)
[2021-10-25T12:40:03.025Z]   File "/home/tensorflow_ci_jenkins/workspace/workspace/workspace/tensorflow-eigen-test/bazel-ci_build-cache/.cache/bazel/_bazel_tensorflow_ci_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/feature_column/feature_column_test.runfiles/org_tensorflow/tensorflow/python/ops/resource_variable_ops.py", line 674, in numpy
[2021-10-25T12:40:03.025Z]     raise NotImplementedError(
[2021-10-25T12:40:03.025Z] NotImplementedError: numpy() is only available when eager execution is enabled.

**Describe the expected behavior**

The unit test should pass. 

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): yes
- Briefly describe your candidate solution(if contributing):
- Downgrade numpy to ~1.19.2 as workaround. Not sure about the root-cause and fix. 

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Simply run the //tensorflow/python/feature_column:feature_column_test unit test. 

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

An example full failure log can be found in Intel's public CI page via https://tensorflow-ci.intel.com/job/tensorflow-eigen-test/492/artifact/eigen_test.log/*view*/ (subject to expiration).

**Comment by sachinprasadhs** [comment]
Hi could you please provide the minimal reproducible code.
Also, please check the attached Gist [here](https://colab.research.google.com/gist/sachinprasadhs/e30e6375fb8c829fbfa49b2bbc4e580b/feature_columns.ipynb) with Numpy 1.21.2 and Feature column example. Thanks

**Comment by wei-v-wang** [comment]
Hi @sachinprasadhs , the reproducible code is the official TensorFlow unit test located here: 
https://github.com/tensorflow/tensorflow/blob/5f5af2a06251dbcb7ecdc2c571b42a9400aafede/tensorflow/python/feature_column/feature_column_test.py

If you run the following command with numpy 1.21.2 or numpy 1.21.3 
bazel test  //tensorflow/python/feature_column:feature_column_test

You should be able to see the errors. 

Please let me know if you insist on getting a standalone .py file.

**Comment by wei-v-wang** [comment]
Please use the following reproducer: 

import tensorflow as tf
from tensorflow.python.platform import test
from tensorflow.python.feature_column.feature_column import _LinearModel
from tensorflow.python.feature_column import feature_column as fc
from tensorflow.python.ops import variable_scope
from tensorflow.python.framework import ops 
def get_keras_linear_model_predictions(features,
                                       feature_columns,
                                       units=1,
                                       sparse_combiner='sum',
                                       weight_collections=None,
                                       trainable=True,
                                       cols_to_vars=None):
  keras_linear_model = _LinearModel(
      feature_columns,
      units,
      sparse_combiner,
      weight_collections,
      trainable,
      name='linear_model')
  retval = keras_linear_model(features)  # pylint: disable=not-callable
  if cols_to_vars is not None:
    cols_to_vars.update(keras_linear_model.cols_to_vars())
  return retval

def get_linear_model_bias(name='linear_model'):
  with variable_scope.variable_scope(name, reuse=True):
    return variable_scope.get_variable('bias_weights')

def get_linear_model_column_var(column, name='linear_model'):
  return ops.get_collection(ops.GraphKeys.GLOBAL_VARIABLES,
                            name + '/' + column.name)[0]

class Test(test.TestCase):

        def reproduce(self):
          price1 = fc._numeric_column('price1', shape=2)
          price2 = fc._numeric_column('price2')
          with ops.Graph().as_default():
            features = {'price1': [[1., 2.], [5., 6.]], 'price2': [[3.], [4.]]}
            cols_to_vars = {}
            get_keras_linear_model_predictions(
                features, [price1, price2], cols_to_vars=cols_to_vars)
            bias = get_linear_model_bias()
            price1_var = get_linear_model_column_var(price1)
            price2_var = get_linear_model_column_var(price2)
            print([bias])
            print(cols_to_vars['bias'])
            self.assertAllEqual(a=cols_to_vars['bias'], b=[bias])
            self.assertAllEqual(a=cols_to_vars[price1], b=[price1_var])
            self.assertAllEqual(a=cols_to_vars[price2], b=[price2_var])

def main():
        my_test = Test()
        my_test.reproduce()

if __name__ == "__main__":
    main()



Running with numpy1.18.5 based TF: output is the following
WARNING:tensorflow:From .../lib64/python3.6/site-packages/tensorflow/python/feature_column/feature_column.py:563: Layer.add_variable (from tensorflow.python.keras.engine.base_layer_v1) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.add_weight` method instead.
[<tf.Variable 'linear_model/bias_weights:0' shape=(1,) dtype=float32>]
ListWrapper([<tf.Variable 'linear_model/bias_weights:0' shape=(1,) dtype=float32>])

Running with numpy 1.21.4 based TF: output is the following

site-packages/tensorflow/python/keras/engine/base_layer_v1.py:1702: UserWarning: `layer.add_variable` is deprecated and will be removed in a future version. Please use `layer.add_weight` method instead.
  warnings.warn('`layer.add_variable` is deprecated and '
[<tf.Variable 'linear_model/bias_weights:0' shape=(1,) dtype=float32>]
[<tf.Variable 'linear_model/bias_weights:0' shape=(1,) dtype=float32>]
Traceback (most recent call last):
  File "standalone_feature_column.py", line 58, in <module>
    main()
  File "standalone_feature_column.py", line 55, in main
    my_test.reproduce()
  File "standalone_feature_column.py", line 49, in reproduce
    self.assertAllEqual(a=cols_to_vars['bias'], b=[bias])
  File "/root/test-py38-feature-column-venv/lib/python3.8/site-packages/tensorflow/python/framework/test_util.py", line 1383, in decorated
    return f(*args, **kwds)
  File "/root/test-py38-feature-column-venv/lib/python3.8/site-packages/tensorflow/python/framework/test_util.py", line 3048, in assertAllEqual
    a = self._GetNdArray(a)
  File "/root/test-py38-feature-column-venv/lib/python3.8/site-packages/tensorflow/python/framework/test_util.py", line 2792, in _GetNdArray
    return np.array(a)
  File "/root/test-py38-feature-column-venv/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 506, in __array__
    return np.asarray(self.numpy(), dtype=dtype)
  File "/root/test-py38-feature-column-venv/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 646, in numpy
    raise NotImplementedError(
NotImplementedError: numpy() is only available when eager execution is enabled.

**Comment by wei-v-wang** [comment]
Testing on going with PR48935 on our end. 
This page https://tensorflow-ci.intel.com/job/tensorflow-mkl-linux-cpu-pr/11933/console will show the test results with https://github.com/tensorflow/tensorflow/pull/48935

Hoping that the results still not show feature column unit failures with this PR. Let's see.

**Comment by wei-v-wang** [comment]
The above test results show that the feature column unit tests still fail even with PR#48935. 

Error message is the same as the above standalone reproducer: 

NotImplementedError: numpy() is only available when eager execution is enabled.

**Comment by sachinprasadhs** [comment]
Since, `Numpy 1.2 `compatibility require lot of changes and backward compatibility also has to be taken care of, it is already a work in progress, you can track the progress [here](https://github.com/tensorflow/tensorflow/pull/48935). 
Closing this as the duplicate to the above linked issue. Thanks!

**Comment by wei-v-wang** [comment]
The following commit temporarily skips these failed tests: 
https://github.com/tensorflow/tensorflow/commit/2efbaddd53d21fcada1e22bad86682b52ccc4d9f

**Comment by mihaimaruseac** [comment]
Yes, we had to disable those tests for now to work on the release of PYthon 3.10 wheels. The tests will have to be re-enabled though, code owners have been pinged and are working on this
