### ISSUE TITLE
ModuleNotFoundError: No module named 'tf'

### ISSUE THREAD

**Issue by a906247390** [tensorflow/tensorflow#52754]
import numpy as np
import pandas as pd
import matplotlib as plt
import tensorflow as tf
from tensorflow import keras

print(tf.__version__)

# 加载fashion_mnist数据集
fashion_mnist1 = tf.keras.datasets.fashion_mnist
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

output is
2.6.0
Traceback (most recent call last):
  File "G:/workspace/py/data analize/untitled/Tensorflow2leanProject/prectise.py", line 10, in <module>
    fashion_mnist1 = tf.keras.datasets.fashion_mnist
  File "D:\Users\Administrator\anaconda3\lib\site-packages\tensorflow\python\util\lazy_loader.py", line 62, in __getattr__
    module = self._load()
  File "D:\Users\Administrator\anaconda3\lib\site-packages\tensorflow\python\util\lazy_loader.py", line 45, in _load
    module = importlib.import_module(self.__name__)
  File "D:\Users\Administrator\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Users\Administrator\anaconda3\lib\site-packages\keras\__init__.py", line 25, in <module>
    from tf.keras import models
ModuleNotFoundError: No module named 'tf'

**Comment by a906247390** [comment]
Your reply is very helpful to me. I have newly configured Anaconda virtual environment to solve this problem
