### ISSUE TITLE
AttributeError in tensorflowjs wizard with tensorflow_estimator version 2.7.0 (but can be fixed by downgrading modules)

### ISSUE THREAD

**Issue by Rakagami** [tensorflow/tensorflow#52883]
**System information**
- Manjaro Linux x86_64
- TensorFlow installed from anaconda (implicitly thorugh `pip install "tensorflowjs[wizard]"`)
- TensorFlow version : 2.6.0
- Python version: 3.6.13
- CUDA/cuDNN version: cuda_11.4.r11.4
- GPU model and memory: NVIDIA GeForce GTX 1660 Ti, 6GB memory

**Current Behavior**
When I execute `tensorflowjs_wizard`, I get the following output:

```
Traceback (most recent call last):
  File "/home/raka/.conda/envs/tfjs_error/bin/tensorflowjs_wizard", line 5, in <module>
    from tensorflowjs.converters.wizard import pip_main
  File "/home/raka/.conda/envs/tfjs_error/lib/python3.6/site-packages/tensorflowjs/__init__.py", line 21, in <module>
    from tensorflowjs import converters
  File "/home/raka/.conda/envs/tfjs_error/lib/python3.6/site-packages/tensorflowjs/converters/__init__.py", line 21, in <module>
    from tensorflowjs.converters.converter import convert
  File "/home/raka/.conda/envs/tfjs_error/lib/python3.6/site-packages/tensorflowjs/converters/converter.py", line 37, in <module>
    from tensorflowjs.converters import tf_saved_model_conversion_v2
  File "/home/raka/.conda/envs/tfjs_error/lib/python3.6/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 39, in <module>
    import tensorflow_hub as hub
  File "/home/raka/.conda/envs/tfjs_error/lib/python3.6/site-packages/tensorflow_hub/__init__.py", line 88, in <module>
    from tensorflow_hub.estimator import LatestModuleExporter
  File "/home/raka/.conda/envs/tfjs_error/lib/python3.6/site-packages/tensorflow_hub/estimator.py", line 62, in <module>
    class LatestModuleExporter(tf.compat.v1.estimator.Exporter):
  File "/home/raka/.conda/envs/tfjs_error/lib/python3.6/site-packages/tensorflow/python/util/lazy_loader.py", line 62, in __getattr__
    module = self._load()
  File "/home/raka/.conda/envs/tfjs_error/lib/python3.6/site-packages/tensorflow/python/util/lazy_loader.py", line 45, in _load
    module = importlib.import_module(self.__name__)
  File "/home/raka/.conda/envs/tfjs_error/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/raka/.conda/envs/tfjs_error/lib/python3.6/site-packages/tensorflow_estimator/__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1 import estimator
  File "/home/raka/.conda/envs/tfjs_error/lib/python3.6/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1.estimator import experimental
  File "/home/raka/.conda/envs/tfjs_error/lib/python3.6/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py", line 10, in <module>
    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder
  File "/home/raka/.conda/envs/tfjs_error/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py", line 27, in <module>
    from tensorflow_estimator.python.estimator import estimator
  File "/home/raka/.conda/envs/tfjs_error/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 70, in <module>
    @doc_controls.inheritable_header("""\
AttributeError: module 'tensorflow.tools.docs.doc_controls' has no attribute 'inheritable_header'
```

**Expected Behavior**
The expected behavior is the output of the `tensorflowjs_wizard`  command as documented [here](https://github.com/tensorflow/tfjs/blob/master/tfjs-converter/README.md)
The error seems to have been caused by `inheritable_header` which is called from `tensorflow_estimator.python.estimator` as seen by log above. [This commit](https://github.com/tensorflow/estimator/commit/1cf920e090b02c6b3186b66a2bb2e0114476db40) shows, that the call from the estimator module was recently added with the 2.7.0 version which released yesterday.

**How I currently solved it for me**

Through downgrading tensorflow-estimator to 2.6.0 and tensorflowjs to 3.9.0 I was able to get the command `tensorflowjs_wizard` to **behave as expected**. I downgraded the python packages with the following command:

```
pip install --upgrade tensorflow-estimator==2.6.0
pip install --upgrade tensorflowjs==3.9.0
```

**[Contributing](https://www.tensorflow.org/community/contribute)**

I don't know how to fix this issue because how I solved my issue was through manual downgrading. Maybe someone who knows the code better knows what to do.

**Standalone code to reproduce the issue**

```bash
# Assuming you have already installed conda and are currently in no environment
conda create --name tfjs python=3.6
conda activate tfjs
pip install tensorflowjs[wizard]
# Here you have to refresh the terminal somehow
tensorflowjs_wizard
```
[edit: forgot to add the tensorflow version]

**Comment by mryszt** [comment]
Looks the problem is in wrong dependency in tensorflow 2.6.0. It has tensorflow-estimator~=2.6, while it shall be tensorflow-estimator~=2.6.0.
Similar thing will happen to keras, when it is not in rc phase anymore, as the same dependency (~=2.6) is set there

**Comment by pselden** [comment]
This is also breaking our TFX pipeline in BigQueryExampleGen running in dataflow -- do you know if this is going to be fixed by just releasing tensorflow 2.7, or will the version be pinned in 2.6?

**Comment by mohantym** [comment]
Hi @Rakagami! Could you please post this issue here in[ tfjs ](https://github.com/tensorflow/tfjs)repository?

**Comment by Rakagami** [comment]
The behavior changed a bit since the dependency was changed. `pip install tensorflowjs[wizard]` now installs `tensorflow-estimator` 2.6.0 on default. `tensorflowjs_wizard` still throws an error which I documented in [this new issue](https://github.com/tensorflow/tfjs/issues/5805) in the tfjs repository. I think this issue can be closed here.
