### ISSUE TITLE
py_function isn't working with CompositeTensor (especially TensorArray) tf 2.7.0

### ISSUE THREAD

**Issue by DUPASYoann** [tensorflow/tensorflow#53006]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04.6 LTS
- TensorFlow installed from (source or binary): binary (pip install tensorflow)
- TensorFlow version (use command below): .v2.7.0-rc1-69-gc256c071bb2 2.7.0
- Python version: 3.7
- CUDA/cuDNN version: 11.4
- GPU model and memory: RTX 2080 Ti 11Go

**Describe the current behavior**
Hi ! When using `tf.py_function()` with `Tout` a composite Tensor. I get an `ValueError : Attempt to convert a value (<tensorflow.python.ops.tensor_array_ops.TensorArray object at 0x7ff622c6e850>) with an unsupported type (<class 'tensorflow.python.ops.tensor_array_ops.TensorArray'>) to a Tensor` 

**Describe the expected behavior**
I should get a ArrayTensor (or a composite Tensor as specifed in the `tf.py_function` documentation, but i didn't test other composite Tensor). Auto-graph is working but when calling the iterator it fail.

**Standalone code to reproduce the issue**
```python

import tensorflow as tf

dataset = tf.data.Dataset.range(1)


@tf.function
def exemple_tf(sample):
    array = tf.py_function(exemple_py, [sample],
                           Tout=tf.TensorArraySpec(element_shape=[None, 2],
                                                   dtype=tf.dtypes.float32,
                                                   dynamic_size=False,
                                                   infer_shape=True), name="exemple")
    return sample


def exemple_py(sample):
    tensor_array = tf.TensorArray(dtype=tf.float32,
                                  size=1,
                                  dynamic_size=False,
                                  clear_after_read=False,
                                  infer_shape=False,
                                  element_shape=[None, 2])
    return tensor_array


dataset = dataset.map(exemple_tf) # Work here

for data in dataset:
    print(data) # Fail here

```

**Other info / logs**
 ```

2021-11-09 14:01:14.983740: W tensorflow/core/framework/op_kernel.cc:1733] INVALID_ARGUMENT: ValueError: Attempt to convert a value (<tensorflow.python.ops.tensor_array_ops.TensorArray object at 0x7fab6045b910>) with an unsupported type (<class 'tensorflow.python.ops.tensor_array_ops.TensorArray'>) to a Tensor.
Traceback (most recent call last):

  File "/home/environment/TensorFlow_270_37/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 273, in __call__
    return func(device, token, args)

  File "/home/environment/TensorFlow_270_37/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 151, in __call__
    outputs = self._call(device, args)

  File "/home/environment/TensorFlow_270_37/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 170, in _call
    for (x, dtype) in zip(ret, self._out_dtypes)

  File "/home/environment/TensorFlow_270_37/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 170, in <listcomp>
    for (x, dtype) in zip(ret, self._out_dtypes)

  File "/home/environment/TensorFlow_270_37/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 135, in _convert
    return ops.convert_to_tensor(value, dtype=dtype)

  File "/home/environment/TensorFlow_270_37/lib/python3.7/site-packages/tensorflow/python/profiler/trace.py", line 163, in wrapped
    return func(*args, **kwargs)

  File "/home/environment/TensorFlow_270_37/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1621, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)

  File "/home/environment/TensorFlow_270_37/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 347, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)

  File "/home/environment/TensorFlow_270_37/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 272, in constant
    allow_broadcast=True)

  File "/home/environment/TensorFlow_270_37/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 283, in _constant_impl
    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)

  File "/home/environment/TensorFlow_270_37/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 308, in _constant_eager_impl
    t = convert_to_eager_tensor(value, ctx, dtype)

  File "/home/environment/TensorFlow_270_37/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 106, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)

ValueError: Attempt to convert a value (<tensorflow.python.ops.tensor_array_ops.TensorArray object at 0x7fab6045b910>) with an unsupported type (<class 'tensorflow.python.ops.tensor_array_ops.TensorArray'>) to a Tensor.


Traceback (most recent call last):
  File "/home/ydupas/PycharmProjects/ExperimentArea/test py_function bug.py", line 27, in <module>
    for data in dataset:
  File "/home/environment/TensorFlow_270_37/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 800, in __next__
    return self._next_internal()
  File "/home/environment/TensorFlow_270_37/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 786, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "/home/environment/TensorFlow_270_37/lib/python3.7/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2845, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/home/environment/TensorFlow_270_37/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 7107, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: ValueError: Attempt to convert a value (<tensorflow.python.ops.tensor_array_ops.TensorArray object at 0x7fab6045b910>) with an unsupported type (<class 'tensorflow.python.ops.tensor_array_ops.TensorArray'>) to a Tensor.
Traceback (most recent call last):

  File "/home/environment/TensorFlow_270_37/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 273, in __call__
    return func(device, token, args)

  File "/home/environment/TensorFlow_270_37/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 151, in __call__
    outputs = self._call(device, args)

  File "/home/environment/TensorFlow_270_37/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 170, in _call
    for (x, dtype) in zip(ret, self._out_dtypes)

  File "/home/environment/TensorFlow_270_37/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 170, in <listcomp>
    for (x, dtype) in zip(ret, self._out_dtypes)

  File "/home/environment/TensorFlow_270_37/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 135, in _convert
    return ops.convert_to_tensor(value, dtype=dtype)

  File "/home/environment/TensorFlow_270_37/lib/python3.7/site-packages/tensorflow/python/profiler/trace.py", line 163, in wrapped
    return func(*args, **kwargs)

  File "/home/environment/TensorFlow_270_37/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1621, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)

  File "/home/environment/TensorFlow_270_37/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 347, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)

  File "/home/environment/TensorFlow_270_37/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 272, in constant
    allow_broadcast=True)

  File "/home/environment/TensorFlow_270_37/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 283, in _constant_impl
    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)

  File "/home/environment/TensorFlow_270_37/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 308, in _constant_eager_impl
    t = convert_to_eager_tensor(value, ctx, dtype)

  File "/home/environment/TensorFlow_270_37/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 106, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)

ValueError: Attempt to convert a value (<tensorflow.python.ops.tensor_array_ops.TensorArray object at 0x7fab6045b910>) with an unsupported type (<class 'tensorflow.python.ops.tensor_array_ops.TensorArray'>) to a Tensor.


	 [[{{function_node __inference_exemple_tf_12}}{{node exemple}}]] [Op:IteratorGetNext]

Process finished with exit code 1

```

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tensorflow 2.7, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/8745aeef128939c928d4cbc70b293f27/53006.ipynb). Thanks!
