### ISSUE TITLE
tflite-model-maker: audio_classifier's DataLoader loads .wav files as int32, resulting in TypeError when training model

### ISSUE THREAD

**Issue by ghosinski** [tensorflow/tensorflow#53013]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Custom Code
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow version (use command below): 2.7.0 (also repeated on 2.6 and 2.5)
- Python version: 3.8

**Describe the current behavior**

Following this tutorial: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/tutorials/model_maker_audio_classification.ipynb

When using my own .wav files (16kHz, Mono, float32) as the test and train data, the built in DataLoader function (audio_classifier.DataLoader) loads the arrays as int32's, which leads to this TypeError when I attempt to train the model:

```"TypeError: Input 'y' of 'FloorDiv' Op has type float32 that does not match type int32 of argument 'x'." ```

This is because the YAMnet model expects float32 as input. However, I can use the exact same .wav files as input into the TF Lite YAMnet, and the model processes an output array (1, 521) as expected - meaning these .wav files are in the correct format. It is only when I attempt to train the model via this transfer learning tutorial that this error appears, which leads me to believe it's a bug with the DataLoader. 

**Describe the expected behavior**

The DataLoader should process .wav files as float32s, and therefore allow model training.

**Standalone code to reproduce the issue**

my wav files: https://storage.googleapis.com/glass_net_wavs_zip/glass_data.zip

```python

from tflite_model_maker import audio_classifier
import os

data_dir = os.getcwd() + '\\glass_data\\sample_data'

spec = audio_classifier.YamNetSpec(
    keep_yamnet_and_custom_heads=False,
    frame_step=0.5 * audio_classifier.YamNetSpec.EXPECTED_WAVEFORM_LENGTH,
    frame_length=1 * audio_classifier.YamNetSpec.EXPECTED_WAVEFORM_LENGTH)

train_data = audio_classifier.DataLoader.from_folder(spec, os.path.join(data_dir, 'train'), cache=True)
test_data = audio_classifier.DataLoader.from_folder(spec, os.path.join(data_dir, 'test'), cache=True)
train_data, validation_data = train_data.split(0.8)

# data = audio_classifier.DataLoader.from_folder(spec=spec, data_path=data_dir)
# train_data, rest_data = data.split(0.8)
# validation_data, test_data = rest_data.split(0.5)

batch_size = 16
epochs = 100

print('Training the model')
model = audio_classifier.create(
    train_data,
    spec,
    validation_data,
    batch_size=batch_size,
    epochs=epochs)

model.evaluate(test_data)

```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow_examples\lite\model_maker\core\task\audio_classifier.py", line 148, in create
    task.train(train_data, validation_data, epochs, batch_size)
  File "C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow_examples\lite\model_maker\core\task\audio_classifier.py", line 55, in train
    train_ds, _ = self._get_dataset_and_steps(
  File "C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow_examples\lite\model_maker\core\task\audio_classifier.py", line 42, in _get_dataset_and_steps
    dataset = tf.distribute.get_strategy().distribute_datasets_from_function(
  File "C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow\python\distribute\distribute_lib.py", line 1159, in distribute_datasets_from_function
    return self._extended._distribute_datasets_from_function(  # pylint: disable=protected-access
  File "C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow\python\distribute\distribute_lib.py", line 3574, in _distribute_datasets_from_function
    return dataset_fn(InputContext())
  File "C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow_examples\lite\model_maker\core\task\custom_model.py", line 81, in _dataset_fn
    dataset = input_data.gen_dataset(
  File "C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow_examples\lite\model_maker\core\data_util\audio_dataloader.py", line 360, in gen_dataset
    ds = spec.preprocess_ds(ds, is_training=is_training, cache_fn=_cache_fn)
  File "C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow_examples\lite\model_maker\core\task\model_spec\audio_spec.py", line 523, in preprocess_ds
    ds = ds.map(self._frame, num_parallel_calls=autotune).unbatch()
  File "C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 1927, in map
    return ParallelMapDataset(
  File "C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 4522, in __init__
    self._map_func = StructuredFunctionWrapper(
  File "C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 3712, in __init__
    self._function = fn_factory()
  File "C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow\python\eager\function.py", line 3134, in get_concrete_function
    graph_function = self._get_concrete_function_garbage_collected(
  File "C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow\python\eager\function.py", line 3100, in _get_concrete_function_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow\python\eager\function.py", line 3444, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow\python\eager\function.py", line 3279, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow\python\framework\func_graph.py", line 999, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 3687, in wrapped_fn
    ret = wrapper_helper(*args)
  File "C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 3617, in wrapper_helper
    ret = autograph.tf_convert(self._func, ag_ctx)(*nested_args)
  File "C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow\python\eager\def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow\python\eager\def_function.py", line 933, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow\python\eager\def_function.py", line 763, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow\python\eager\function.py", line 3050, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow\python\eager\function.py", line 3444, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow\python\eager\function.py", line 3279, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow\python\framework\func_graph.py", line 999, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow\python\eager\def_function.py", line 672, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow\python\eager\function.py", line 3971, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow\python\framework\func_graph.py", line 986, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:
    C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow_examples\lite\model_maker\core\task\model_spec\audio_spec.py:497 _frame  *
        clips = tf.signal.frame(
    C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow\python\util\dispatch.py:206 wrapper  **
        return target(*args, **kwargs)
    C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow\python\ops\signal\shape_ops.py:181 frame
        0, 1 + (length_samples - frame_length) // frame_step)
    C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow\python\ops\math_ops.py:1250 binary_op_wrapper
        raise e
    C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow\python\ops\math_ops.py:1234 binary_op_wrapper
        return func(x, y, name=name)
    C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow\python\util\dispatch.py:206 wrapper
        return target(*args, **kwargs)
    C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow\python\ops\math_ops.py:1526 floordiv
        return gen_math_ops.floor_div(x, y, name=name)
    C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow\python\ops\gen_math_ops.py:3796 floor_div
        _, _, _op, _outputs = _op_def_library._apply_op_helper(
    C:\Users\ghosinsk\anaconda3\envs\GlassNet_v3\lib\site-packages\tensorflow\python\framework\op_def_library.py:555 _apply_op_helper
        raise TypeError(
    TypeError: Input 'y' of 'FloorDiv' Op has type float32 that does not match type int32 of argument 'x'.
```

**Comment by mohantym** [comment]
Hi @ghosinski! Could you try again after casting your input data then ? Attaching similar issues for your reference .[link1](https://stackoverflow.com/a/62282237/11530462),[link2](https://github.com/tensorflow/tensorflow/issues/33077) Thanks!

**Comment by ghosinski** [comment]
Hey @mohantym thanks so much for the follow up! The input to train a tflite_model_maker audio_classifier model is just raw .wav audio files. For example, the [tutorial ](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/tutorials/model_maker_audio_classification.ipynb) uses [these ](https://storage.googleapis.com/laurencemoroney-blog.appspot.com/birds_dataset.zip) wav files. All of the casting / pre-processing (I assume) is done via the DataLoader class, and it seems it is casting audio data to int32 instead of float32. The training_data variable (when it gets assigned by the first call to audio_classifier.DataLoader) is of type ''' <class 'tensorflow_examples.lite.model_maker.core.data_util.audio_dataloader.DataLoader'> ''' - I have no idea how I would cast this before training the model... maybe the data is under some sub attribute? But regardless it shouldn't need to cast anything as the processing is supposedly done by the DataLoader.

**Comment by mohantym** [comment]
Hi @sanatmpa1! Could you look at this issue . Attaching [Gist f](https://colab.sandbox.google.com/gist/mohantym/1069c2eec8a17574d0184138cee547d5/untitled183.ipynb)or reference.

**Comment by ghosinski** [comment]
I've figured out the source of the error:
```
spec = audio_classifier.YamNetSpec(
    keep_yamnet_and_custom_heads=False,
    frame_step=0.5 * audio_classifier.YamNetSpec.EXPECTED_WAVEFORM_LENGTH,
    frame_length=1 * audio_classifier.YamNetSpec.EXPECTED_WAVEFORM_LENGTH)
````
Multiplying by 0.5 casts the variable frame_step to float32, and the model-maker expects this to be int32. Might be good to make a note of this somewhere. 

Also, for anyone's future reference, wav files need to be 16-bit PCM when using tflite model maker. That also tripped me up for a while and isn't documented anywhere. Cheers!

**Comment by sanatmpa1** [comment]
@ghosinski,

Thanks for the detailed explanation, which may be useful for others in future. But I can already see in [this documentation](https://www.tensorflow.org/lite/api_docs/python/tflite_model_maker/audio_classifier/DataLoader#from_folder) that it already expects 16 bit PCM encoding for wav files.

>  Each .wav file corresponds to an example. Each .wav file is mono (single-channel) and has the typical 16 bit pulse-code modulation (PCM) encoding.

Hope it helps. Thanks!
