### ISSUE TITLE
Error with higher batch size in stateful LSTM layer

### ISSUE THREAD

**Issue by Krzha** [tensorflow/tensorflow#53024]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.7.0-rc1-69-gc256c071bb2 2.7.0
- Python version: 3.9.5
- CUDA/cuDNN version: 11.2/8.1.1
- GPU model and memory: GTX 1070 Ti

**Describe the current behavior**

When using a stateful LSTM layer with any batch size > 32 I get an error:
```
batch_size = 33
input_tensor = tf.keras.Input(shape=[5], batch_size=batch_size)
lstm_input = tf.keras.layers.Dense(16, activation=tf.keras.activations.elu)(input_tensor)
lstm_input = tf.expand_dims(lstm_input, axis=1)
lstm_layer = tf.keras.layers.LSTM(16, stateful=True, return_state=True)
lstm_out, h, c = lstm_layer(lstm_input)
out = tf.keras.layers.Dense(1, activation=tf.keras.activations.linear)(lstm_out)
```
```
2021-11-10 19:32:33.397959: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at cudnn_rnn_ops.cc:1517 : INVALID_ARGUMENT: Invalid input_h shape: [1,33,16] [1,32,16]
```
Any batch size <= 32 works fine
Changing the LSTM layer to stateful=False and the Input layer to batch_size=None makes the issue disappear (changing only stateful to False does not)

**Describe the expected behavior**
No difference when changing the batch size.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no

**Standalone code to reproduce the issue**
```python
import tensorflow as tf
import numpy as np


batch_size = 33

input_tensor = tf.keras.Input(shape=[5], batch_size=batch_size)
lstm_input = tf.keras.layers.Dense(16, activation=tf.keras.activations.elu)(input_tensor)
lstm_input = tf.expand_dims(lstm_input, axis=1)
lstm_layer = tf.keras.layers.LSTM(16, stateful=True, return_state=True)
lstm_out, h, c = lstm_layer(lstm_input)
out = tf.keras.layers.Dense(1, activation=tf.keras.activations.linear)(lstm_out)

model = tf.keras.Model(
    inputs=[input_tensor],
    outputs=[out, h, c])
model.compile(optimizer=tf.keras.optimizers.Adam(), loss=tf.keras.losses.MeanSquaredError())
model.summary()

input_arr = np.random.random(size=(batch_size, 5))
model.predict([input_arr])
```
**Other info / logs** Include any logs or source code that would be helpful to
Executing the above program with any batch size > 32 gives the following error:
```
2021-11-10 19:45:47.216169: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-11-10 19:45:47.636164: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 6615 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1070 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
=================================================================
 input_1 (InputLayer)        [(33, 5)]                 0         
                                                                 
 dense (Dense)               (33, 16)                  96        
                                                                 
 tf.expand_dims (TFOpLambda)  (33, 1, 16)              0         
                                                                 
 lstm (LSTM)                 [(33, 16),                2112      
                              (33, 16),                          
                              (33, 16)]                          
                                                                 
 dense_1 (Dense)             (33, 1)                   17        
                                                                 
=================================================================
Total params: 2,225
Trainable params: 2,225
Non-trainable params: 0
_________________________________________________________________
2021-11-10 19:45:48.667605: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at cudnn_rnn_ops.cc:1517 : INVALID_ARGUMENT: Invalid input_h shape: [1,33,16] [1,32,16]
Traceback (most recent call last):
  File "***\PyCharmCE2021.2\scratches\scratch.py", line 22, in <module>
    model.predict([input_arr])
  File "***\venv\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "***\venv\lib\site-packages\tensorflow\python\eager\execute.py", line 58, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:    Invalid input_h shape: [1,33,16] [1,32,16]
	 [[{{node CudnnRNN}}]]
	 [[model/lstm/PartitionedCall]] [Op:__inference_predict_function_1045]

Function call stack:
predict_function -> predict_function -> predict_function


Process finished with exit code 1
```

**Comment by sanatmpa1** [comment]
@Krzha,

I modified the last line in your code from `model.predict([input_arr])` to `model.predict(input_arr,batch_size=batch_size)` and now it works fine for batch sizes more than 32. Please find the working [gist here](https://colab.sandbox.google.com/gist/sanatmpa1/b7f680b071db6f76702c68579630f202/53024.ipynb). Thanks!

**Comment by Krzha** [comment]
Indeed it does work

I'm not sure why, but at least that solves the issues, thanks
