### ISSUE TITLE
macOS12 tensorflow-metal error

### ISSUE THREAD

**Issue by Yuri-Su** [tensorflow/tensorflow#53077]
**System information**

- OS Platform and Distribution : macOS 12.1 intel
- TensorFlow installed from (source or binary):source
- TensorFlow version (use command below):tensorflow-metal 2.6
- Python version:3.8
- GPU model and memory: AMD Radeon RX 6600

Errors will be reported when training the model
```
tensorflow.python.framework.errors_impl.AlreadyExistsError: Another metric with the same name already exists.
```
For example, the following program
```
import tensorflow as tf

print(tf.config.list_physical_devices())

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=[28, 28]),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
])
print(model.summary())

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
2021-11-16 10:59:28.127916: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/api/keras/optimizers
Traceback (most recent call last):
  File "/Volumes/Workspace/PythonProject/centernet2-tf2/main.py", line 5, in <module>
    model = tf.keras.models.Sequential([
  File "/Users/yurisu/opt/miniconda3/envs/tf-metal-2.6/lib/python3.8/site-packages/tensorflow/python/util/lazy_loader.py", line 62, in __getattr__
    module = self._load()
  File "/Users/yurisu/opt/miniconda3/envs/tf-metal-2.6/lib/python3.8/site-packages/tensorflow/python/util/lazy_loader.py", line 45, in _load
    module = importlib.import_module(self.__name__)
  File "/Users/yurisu/opt/miniconda3/envs/tf-metal-2.6/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/yurisu/opt/miniconda3/envs/tf-metal-2.6/lib/python3.8/site-packages/keras/__init__.py", line 25, in <module>
    from keras import models
  File "/Users/yurisu/opt/miniconda3/envs/tf-metal-2.6/lib/python3.8/site-packages/keras/models.py", line 20, in <module>
    from keras import metrics as metrics_module
  File "/Users/yurisu/opt/miniconda3/envs/tf-metal-2.6/lib/python3.8/site-packages/keras/metrics.py", line 26, in <module>
    from keras import activations
  File "/Users/yurisu/opt/miniconda3/envs/tf-metal-2.6/lib/python3.8/site-packages/keras/activations.py", line 20, in <module>
    from keras.layers import advanced_activations
  File "/Users/yurisu/opt/miniconda3/envs/tf-metal-2.6/lib/python3.8/site-packages/keras/layers/__init__.py", line 23, in <module>
    from keras.engine.input_layer import Input
  File "/Users/yurisu/opt/miniconda3/envs/tf-metal-2.6/lib/python3.8/site-packages/keras/engine/input_layer.py", line 21, in <module>
    from keras.engine import base_layer
  File "/Users/yurisu/opt/miniconda3/envs/tf-metal-2.6/lib/python3.8/site-packages/keras/engine/base_layer.py", line 43, in <module>
    from keras.mixed_precision import loss_scale_optimizer
  File "/Users/yurisu/opt/miniconda3/envs/tf-metal-2.6/lib/python3.8/site-packages/keras/mixed_precision/loss_scale_optimizer.py", line 18, in <module>
    from keras import optimizers
  File "/Users/yurisu/opt/miniconda3/envs/tf-metal-2.6/lib/python3.8/site-packages/keras/optimizers.py", line 26, in <module>
    from keras.optimizer_v2 import adadelta as adadelta_v2
  File "/Users/yurisu/opt/miniconda3/envs/tf-metal-2.6/lib/python3.8/site-packages/keras/optimizer_v2/adadelta.py", line 22, in <module>
    from keras.optimizer_v2 import optimizer_v2
  File "/Users/yurisu/opt/miniconda3/envs/tf-metal-2.6/lib/python3.8/site-packages/keras/optimizer_v2/optimizer_v2.py", line 36, in <module>
    keras_optimizers_gauge = tf.__internal__.monitoring.BoolGauge(
  File "/Users/yurisu/opt/miniconda3/envs/tf-metal-2.6/lib/python3.8/site-packages/tensorflow/python/eager/monitoring.py", line 360, in __init__
    super(BoolGauge, self).__init__('BoolGauge', _bool_gauge_methods,
  File "/Users/yurisu/opt/miniconda3/envs/tf-metal-2.6/lib/python3.8/site-packages/tensorflow/python/eager/monitoring.py", line 135, in __init__
    self._metric = self._metric_methods[self._label_length].create(*args)
tensorflow.python.framework.errors_impl.AlreadyExistsError: Another metric with the same name already exists.
```

These are not the issues with the CPU version. It's OK to do simple things with the GPU, but these errors will occur as soon as you train
```
import tensorflow as tf

print(tf.config.list_physical_devices())

with tf.device('/GPU'):
    a = tf.random.normal(shape=(2,), dtype=tf.float32)
    b = tf.nn.relu(a)
    print(a)

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
Metal device set to: AMD Radeon RX 6600

systemMemory: 16.00 GB
maxCacheSize: 3.99 GB

2021-11-16 10:53:19.473055: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-11-16 10:53:19.473518: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2021-11-16 10:53:19.473738: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
tf.Tensor([-1.0673397 -1.3157675], shape=(2,), dtype=float32)

```

**Comment by mohantym** [comment]
Hi @Yuri-Su! Could you try again with TF 2.7 version ?

**Comment by Yuri-Su** [comment]
> Hi @Yuri-Su! Could you try again with TF 2.7 version ?

Thank you for your reply, but the tensorflow-macos version only has TF2.5 and 2.6

**Comment by mohantym** [comment]
Agreed! @Yuri-Su . 

1.Please check once you are not using Tensorflow library in another environment or program. 
2.You can verify whether Tensorflow version and Keras version are same. if not same you can install manually same keras version as Tensorflow version to fix the issue.


Attaching  relevant threads for reference. [link1](https://discuss.tensorflow.org/t/alreadyexistserror-another-metric-with-the-same-name-already-exists/3787/18),[link2](https://stackoverflow.com/questions/58012741/error-importing-tensorflow-alreadyexistserror-another-metric-with-the-same-nam),[link3](https://github.com/keras-team/keras/issues/15579),[link4](https://github.com/tensorflow/tensorflow/issues/52951).

You can post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues) if the issue still persists.
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999) . 

Thanks!

**Comment by Yuri-Su** [comment]
> Agreed! @Yuri-Su .
> 
> 1.Please check once you are not using Tensorflow library in another environment or program. 2.You can verify whether Tensorflow version and Keras version are same. if not same you can install manually same keras version as Tensorflow version to fix the issue.
> 
> Attaching relevant threads for reference. [link1](https://discuss.tensorflow.org/t/alreadyexistserror-another-metric-with-the-same-name-already-exists/3787/18),[link2](https://stackoverflow.com/questions/58012741/error-importing-tensorflow-alreadyexistserror-another-metric-with-the-same-nam),[link3](https://github.com/keras-team/keras/issues/15579),[link4](https://github.com/tensorflow/tensorflow/issues/52951).
> 
> You can post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues) if the issue still persists. To know more see; https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999 .
> 
> Thanks!

Thanks. My problem has been solved. This is because the versions of tensorflow MacOS and keras installed by PIP do not match. Reinstall the corresponding version. Thank you very much for your method!

**Comment by mohantym** [comment]
Ok! @Yuri-Su ! Feel free to close this issue if it helped . Thanks!
