### ISSUE TITLE
I got problem when I create Interpreter using TF lite

### ISSUE THREAD

**Issue by happyEmart** [tensorflow/tensorflow#53091]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Samsung Galaxy S10+
- TensorFlow installed from (source or binary): 
- TensorFlow version (use command below): 2.7
- Python version: 3.8.10
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Hello, 
I'm trying to make an app using GPU while training with below example code.
https://github.com/tensorflow/examples/tree/master/lite/examples/model_personalization

please refer the code above,
with GPUdelegate(https://www.tensorflow.org/lite/performance/gpu_advanced),
I added "implementation 'org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly-SNAPSHOT'" in build.gradle of trasfer_api
    implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly-SNAPSHOT'
    implementation 'org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly-SNAPSHOT'
    // This dependency adds the necessary TF op support.
    implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:0.0.0-nightly-SNAPSHOT'

plus I changed LiteMultipleSignatureModel as
  LiteMultipleSignatureModel(ByteBuffer tfLiteModel, int numClasses) {
    // Initialize interpreter with GPU delegate
    Interpreter.Options options = new Interpreter.Options();
    CompatibilityList compatList = new CompatibilityList();

    if(compatList.isDelegateSupportedOnThisDevice()){
      // if the device has a supported GPU, add the GPU delegate
      GpuDelegate.Options delegateOptions = compatList.getBestOptionsForThisDevice();
      GpuDelegate gpuDelegate = new GpuDelegate(delegateOptions);
      options.addDelegate(gpuDelegate);
    } else {
      // if the GPU is not supported, run on 4 threads
      options.setNumThreads(4);
    }

    this.interpreter = new Interpreter(tfLiteModel, options);
    this.numClasses = numClasses;
  }

I tried to start the app and I found this device support GPU delegation but it failed with fatal exception as
2021-06-10 13:33:36.523 18930-18930/org.tensorflow.lite.examples.transfer E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.tensorflow.lite.examples.transfer, PID: 18930
    java.lang.IllegalArgumentException: Internal error: Error applying delegate:
        at org.tensorflow.lite.NativeInterpreterWrapper.createInterpreter(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:93)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:66)
        at org.tensorflow.lite.NativeInterpreterWrapperExperimental.<init>(NativeInterpreterWrapperExperimental.java:44)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:226)
        at org.tensorflow.lite.examples.transfer.api.LiteMultipleSignatureModel.<init>(LiteMultipleSignatureModel.java:67)

I also tried tfLiteModel to set nitivOrder like tfLiteModel.order(ByteOrder.nativeOrder() but got same result.

please help me out to find the way to resolve this problem :)

Thank you

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by srjoglekar246** [comment]
@haozha111 FYI

We do not currently support GPU acceleration on the models generated for personalization/on-device training. These graphs have some advanced data structures & properties that the mobile GPU backend can't currently handle :-). We are internally investigating ways to solve this in the coming months.
