### ISSUE TITLE
word2vec large corpus overflow

### ISSUE THREAD

**Issue by isikdogan** [tensorflow/tensorflow#531]
I get the following error when I try to run the word2vec_optimized.py file with a corpus larger than 2^31 characters.

```
external/re2/re2/re2.cc:571: RE2: invalid startpos, endpos pair. [startpos: 0, endpos: -656988395, text size: -656988395]
W tensorflow/models/embedding/word2vec_kernels.cc:38] Invalid argument: The text file corpus_stripped.txt contains too little data: 0 words
E tensorflow/core/framework/op_segment.cc:52] Create kernel failed: Invalid argument: The text file corpus_stripped.txt contains too little data: 0 words
E tensorflow/core/common_runtime/executor.cc:262] Executor failed to create kernel. Invalid argument: The text file corpus_stripped.txt contains too little data: 0 words
	 [[Node: Skipgram = Skipgram[batch_size=500, filename="corpus_stripped.txt", min_count=5, subsample=0.001, window_size=5, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
Traceback (most recent call last):
  File "word2vec_optimized.py", line 436, in <module>
    tf.app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "word2vec_optimized.py", line 418, in main
    model = Word2Vec(opts, session)
  File "word2vec_optimized.py", line 147, in __init__
    self.build_graph()
  File "word2vec_optimized.py", line 189, in build_graph
    opts.words_per_epoch) = self._session.run([words, counts, words_per_epoch])
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 368, in run
    results = self._do_run(target_list, unique_fetch_targets, feed_dict_string)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 444, in _do_run
    e.code)
tensorflow.python.framework.errors.InvalidArgumentError: The text file corpus_stripped.txt contains too little data: 0 words
	 [[Node: Skipgram = Skipgram[batch_size=500, filename="corpus_stripped.txt", min_count=5, subsample=0.001, window_size=5, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
Caused by op u'Skipgram', defined at:
  File "word2vec_optimized.py", line 436, in <module>
    tf.app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "word2vec_optimized.py", line 418, in main
    model = Word2Vec(opts, session)
  File "word2vec_optimized.py", line 147, in __init__
    self.build_graph()
  File "word2vec_optimized.py", line 187, in build_graph
    subsample=opts.subsample)
  File "/usr/lib/python2.7/site-packages/tensorflow/models/embedding/gen_word2vec.py", line 69, in skipgram
    name=name)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 664, in apply_op
    op_def=op_def)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1834, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1043, in __init__
    self._traceback = _extract_stack()
```

**Comment by zffchen78** [comment]
kyosha@gmail.com has a change, https://tensorflow-review.googlesource.com/#/c/1252/, which I think will help. You are also welcome to fix the code to fit your need. Cheers,

**Comment by isikdogan** [comment]
Thanks, I ended up using the original implementation of word2vec.
