### ISSUE TITLE
Conflicting behavior with dvc in pytest

### ISSUE THREAD

**Issue by mvggz** [tensorflow/tensorflow#53100]
Hello,

I recently came across a conflicting interaction with `dvc` (and possibly other packages presenting the same behavior) regarding the use of `sys.stdout.close()` and `sys.stderr.close()`.
In the codebase of tensorflow this is used here only:
 - https://github.com/tensorflow/tensorflow/blob/d11296a34b8b9ad798d8f273966de83dbb83de83/tensorflow/python/distribute/multi_process_runner.py#L809-L810
while it used there only in the dvc package (I put it for the sake of completeness):
 - https://github.com/iterative/dvc/blob/6c0bc9563c3ac6b104eedf6688dd79a1bc5bf4ba/dvc/daemon.py#L68-L70
 
If I understand correctly, this is done here so that threads may close more quickly as is explained in the docstring:

> We need to explicitly close them since Tensorflow may take a while to exit,
so that the reading threads in the main process can exit more quickly. 

In `dvc` they use it in a method called `_spawn_posix`, so I guess to help them deal with child processes.

I don't mean to enter into the details of the implementation of each package as it seems normal to do that kind of things there, but in the context of `pytest`, as it mocks subprocesses or at least tamper with it, it creates a conflicting resulting in a traceback:

```
Test session starts (platform: linux, Python 3.6.15, pytest 6.0.2, pytest-sugar 0.9.4)
cachedir: .pytest_cache
rootdir: /lib/data-science, configfile: setup.cfg
plugins: cov-3.0.0, sugar-0.9.4, mock-3.6.1
collecting ... 

Results (15.85s):
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 240, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 295, in _main
    config.hook.pytest_collection(session=session)
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 306, in pytest_collection
    session.perform_collect()
  File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 516, in perform_collect
    items = self._perform_collect(args, genitems)
  File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 568, in _perform_collect
    self.items.extend(self.genitems(node))
  File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 771, in genitems
    yield from self.genitems(subnode)
  File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 768, in genitems
    rep = collect_one_node(node)
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 441, in collect_one_node
    rep = ihook.pytest_make_collect_report(collector=collector)  # type: CollectReport
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/usr/local/lib/python3.6/site-packages/_pytest/capture.py", line 740, in pytest_make_collect_report
    out, err = self.read_global_capture()
  File "/usr/local/lib/python3.6/site-packages/_pytest/capture.py", line 661, in read_global_capture
    return self._global_capturing.readouterr()
  File "/usr/local/lib/python3.6/site-packages/_pytest/capture.py", line 571, in readouterr
    err = self.err.snap()
  File "/usr/local/lib/python3.6/site-packages/_pytest/capture.py", line 481, in snap
    self.tmpfile.seek(0)
ValueError: I/O operation on closed file.
```
as any of the two packages that runs after the other tries to close an already close stream.

One workaround I have for this (in case this might interest people that had the same issue) was to tamper with the two objects:
```
def pytest_configure(config):
    with ExitStack() as stack:
        for stream in (sys.stdout, sys.stderr):
            stack.enter_context(patch.object(stream, stream.close.__name__))
        yield
```
put in a `conftest.py` file at the root of the testing folder.

I guess such behavior will also arise whenever two packages make use of these same methods.
I will post an issue on `dvc` github also and reference both issues with each other.

**Comment by sachinprasadhs** [comment]
I can see that by adding `analytics = False` has resolved your problem as reported [here](https://github.com/iterative/dvc/issues/6992), in that case could you please close this issue. Thanks!
