### ISSUE TITLE
tf.function(jit_compile=True) cannot access int32 weights on GPU

### ISSUE THREAD

**Issue by jxy** [tensorflow/tensorflow#53192]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 20.04.3 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
v2.6.0-0-g919f693420e 2.6.0
- Python version:
Python 3.8.10
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
11.3 8.2
- GPU model and memory:
A100 40GB

**Describe the current behavior**

Functions with tf.function(jit_compile=True) cannot access weights of type int32 on the GPU.  It gives error at runtime
```
2021-11-24 15:12:28.148837: W tensorflow/core/framework/op_kernel.cc:1692] OP_REQUIRES failed at xla_ops.cc:238 : Invalid argument: Trying to access resource _AnonymousVar2 (defined @ /lus/theta-fs0/software/thetagpu/conda/2021-09-22/mconda3/lib/python3.8/site-packages/keras/engine/base_layer_utils.py:117) located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
```

**Describe the expected behavior**

no error

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
no
- Briefly describe your candidate solution(if contributing):
no solution

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Please just run the following code,

```
import tensorflow as tf
import tensorflow.keras as tk

class Scale(tk.layers.Layer):
    def __init__(self, c, dt):
        super(Scale, self).__init__(name='Scale')
        self.c = self.add_weight(initializer=tf.keras.initializers.Constant(c), dtype=dt)
    @tf.function(jit_compile=True)
    def call(self, x):
        return self.c*x

print('float32:', Scale(2, tf.float32)(tf.ones(4, dtype=tf.float32)))
print('int64:', Scale(2, tf.int64)(tf.ones(4, dtype=tf.int64)))
print('int32:', Scale(2, tf.int32)(tf.ones(4, dtype=tf.int32)))  # This line gives error
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Below is the output from running the above code,
```
$ python issue_int32.py 
2021-11-24 15:16:53.015406: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-11-24 15:16:53.423483: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 38458 MB memory:  -> device: 0, name: NVIDIA A100-SXM4-40GB, pci bus id: 0000:bd:00.0, compute capability: 8.0
2021-11-24 15:16:53.776487: I tensorflow/compiler/xla/service/service.cc:171] XLA service 0x562deb0ee730 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-11-24 15:16:53.776535: I tensorflow/compiler/xla/service/service.cc:179]   StreamExecutor device (0): NVIDIA A100-SXM4-40GB, Compute Capability 8.0
2021-11-24 15:16:53.818100: I tensorflow/compiler/jit/xla_compilation_cache.cc:363] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
float32: tf.Tensor([2. 2. 2. 2.], shape=(4,), dtype=float32)
int64: tf.Tensor([2 2 2 2], shape=(4,), dtype=int64)
2021-11-24 15:16:53.865986: W tensorflow/core/framework/op_kernel.cc:1692] OP_REQUIRES failed at xla_ops.cc:238 : Invalid argument: Trying to access resource _AnonymousVar2 (defined @ /lus/theta-fs0/software/thetagpu/conda/2021-09-22/mconda3/lib/python3.8/site-packages/keras/engine/base_layer_utils.py:117) located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
Traceback (most recent call last):
  File "issue_int32.py", line 14, in <module>
    print('int32:', Scale(2, tf.int32)(tf.ones(4, dtype=tf.int32)))
  File "/lus/theta-fs0/software/thetagpu/conda/2021-09-22/mconda3/lib/python3.8/site-packages/keras/engine/base_layer.py", line 1037, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/lus/theta-fs0/software/thetagpu/conda/2021-09-22/mconda3/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 885, in __call__
    result = self._call(*args, **kwds)
  File "/lus/theta-fs0/software/thetagpu/conda/2021-09-22/mconda3/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 956, in _call
    return self._concrete_stateful_fn._call_flat(
  File "/lus/theta-fs0/software/thetagpu/conda/2021-09-22/mconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1963, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/lus/theta-fs0/software/thetagpu/conda/2021-09-22/mconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 591, in call
    outputs = execute.execute(
  File "/lus/theta-fs0/software/thetagpu/conda/2021-09-22/mconda3/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Trying to access resource _AnonymousVar2 (defined @ /lus/theta-fs0/software/thetagpu/conda/2021-09-22/mconda3/lib/python3.8/site-packages/keras/engine/base_layer_utils.py:117) located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0 [Op:__inference_call_44]
```

**Comment by tilakrayal** [comment]
@sachinprasadhs ,
I was able to reproduce the issue in tf [v2.7](https://colab.research.google.com/gist/tilakrayal/1f2a2a9dd6b5d7d61e533d476e72c6f5/2-7-53192.ipynb), [v2.5](https://colab.research.google.com/gist/tilakrayal/bc1f649e43e2e0cff0392ff7ae4fc9a4/2-6-53192.ipynb) and [nightly](https://colab.research.google.com/gist/tilakrayal/9be703622882e48c696679017784b2b2/nightly.ipynb).Please find the gist.

**Comment by JXRiver** [comment]
There is a known issue with `tf.Variable`: https://www.tensorflow.org/xla/known_issues#tfvariable_on_a_different_device

The `self.v` here is an int32 `tf.Variable` that can't be placed on GPU. You are suggested to use `int64` or `int32 + jit_compile=False`.

**Comment by jxy** [comment]
Assuming the developers have a good reason for this odd behavior of `int32`, it would be useful for users to make this behavior controllable.  Is there a way to force int32 tensors on a GPU?

At the very least the error message could be much more useful that what it is now.  Complaining about an `_AnonymousVarNNN` located on a different device that where it is supposed to be is useless.

**Comment by mdanatg** [comment]
> Assuming the developers have a good reason for this odd behavior of `int32`

There is no good reason to do that. It behaves that way because TF lacks a dedicated type for shapes, which must reside on CPU. We're looking into ways to fix this, but it's complicated and will take a while.

+1  to improving the error message.

**Comment by cheshire** [comment]
@jxy @mdanatg From what I see the real bug is that device assignment is ignored and the variable is placed on CPU despite explicit GPU placement (speaking of shapes, do those ever reside inside variables though?). Once the placement on CPU happens, there's nothing much we can do: what would you expect to happen? Extra H2D copy potentially ruining performance? We can't really pattern match this case to a specific error message, as that would just create a more fragile system with more levels of indirection swallowing errors.

**Comment by mdanatg** [comment]
Just making it clearer that the variable (and which variable) was placed on CPU would help. The information is there (e.g. we have the internal name, and line number), so surfacing more clearly would help (e.g. include the actual line of code). "_AnonymousVarNNN" and "__inference_call_44" don't say much.
Agree that there's otherwise not much to do by the time things got here. Might be worth trying `tf.config.set_soft_device_placement(False)`, though that has caveats too.

**Comment by jxy** [comment]
Does leaving random comments count as activity?

**Comment by cheshire** [comment]
@jxy I'm not sure to be honest. Filing a new bug about improved error message would be probably better, what would you like to see? Just a better stack trace presentation, or TF somehow pattern-matching the error message into "ah you are using int32 weights inside a compiled function run on GPU, why not make them int64"? Or would you prefer TF to automatically copy the weights? (CC @smit-hinsu )
