### ISSUE TITLE
failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error

### ISSUE THREAD

**Issue by RaffaeleBerzoini** [tensorflow/tensorflow#53229]
**System information**
- Have I written custom code: below
- OS Platform and Distribution: Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): pip install tensorflow
- TensorFlow version (use command below): 2.3.0
- Python version: 3.8.12
- CUDA/cuDNN version: release 10.1, V10.1.243
- GPU model and memory: RTX2060 Mobile 6GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh):. Log file here [link](https://polimi365-my.sharepoint.com/:t:/g/personal/10607946_polimi_it/ESFGCuewPQRGt8Fv-dFQ61wB8TLOzfl8d1d5AaKyKiQVkg?e=33VUl1)
```Collecting system information...
Traceback (most recent call last):
  File "/tmp/check_os.py", line 17, in <module>
    platform.linux_distribution(),
AttributeError: module 'platform' has no attribute 'linux_distribution'
2021-11-29 11:17:14.503225: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "/tmp/check_tf.py", line 5, in <module>
    with tf.Session() as sess:
AttributeError: module 'tensorflow' has no attribute 'Session'
bazel: command not found
Wrote environment to tf_env.txt. You can review the contents of that file.
and use it to populate the fields in the github issue template.
```

**Describe the current behavior**
```
>>> import tensorflow as tf
2021-11-29 11:44:55.998697: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
>>> tf.config.list_physical_devices("GPU")
2021-11-29 11:45:19.987589: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2021-11-29 11:45:21.698177: E tensorflow/stream_executor/cuda/cuda_driver.cc:314] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2021-11-29 11:45:21.698239: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: raffo-OMEN15
2021-11-29 11:45:21.698251: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: raffo-OMEN15
2021-11-29 11:45:21.698392: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 470.82.0
2021-11-29 11:45:21.698442: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 470.82.0
2021-11-29 11:45:21.698453: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 470.82.0
[]
```

I don't know if it can help: the same error happens in the tensorflow docker container.

**Comment by donglinz** [comment]
I guess there is another process occupying GPU so your TF program cannot can find a memory segment in GPU to initialize CUDA. Just close another process and try again.

**Comment by RaffaeleBerzoini** [comment]
> I guess there is another process occupying GPU so your TF program cannot can find a memory segment in GPU to initialize CUDA. Just close another process and try again.

I don't think so. I check with `nvidia-smi` and this is my output:
```
raffo@raffo-OMEN15:~$ nvidia-smi
Mon Nov 29 13:36:15 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.82.00    Driver Version: 470.82.00    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   52C    P5    22W /  N/A |    376MiB /  5934MiB |     23%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1260      G   /usr/lib/xorg/Xorg                174MiB |
|    0   N/A  N/A      1962      G   /usr/bin/gnome-shell               54MiB |
|    0   N/A  N/A      8198      G   ...AAAAAAAAA= --shared-files      144MiB |
+-----------------------------------------------------------------------------+
```

**Comment by sushreebarsa** [comment]
@RaffaeleBerzoini We could see you are using TF v2.3.0 which is not actively supported ,please refer to the [comment](https://github.com/tensorflow/tensorflow/issues/52915#issuecomment-961288304).Could you please try to upgrade TF version to latest `TF v2.7.0` and refer this [tested build configurations](https://www.tensorflow.org/install/source#tested_build_configurations) ? Thanks!
