### ISSUE TITLE
Seemingly random TensorBoard logging error

### ISSUE THREAD

**Issue by mahenning** [tensorflow/tensorflow#53272]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.3
- TensorBoard version: 2.5.0
- Python version: 3.6.9
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 10.1/7
- GPU model and memory: Geforce GTX 1080

**Describe the current behavior**
When running a time neural network and saving data in tensorboard, I randomly get the following error: (By randomly I mean that I have a batch of networks that run one after the other in a batch file and it is never the completely same network to get the error. Mostly GRU or BiGRU networks. Sometimes every network runs without this problem. Sometimes multiple networks are affected.)

2021-11-28 19:11:18.779759: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at summary_kernels.cc:106 : Permission denied: ../plots/new_dataset_test/arm_pos_middle/20211128_09_56_BiGRU2l6_t750/logs/train/events.out.tfevents.1638089801.zwinge.2544663.2071.v2; Permission denied
	Failed to flush 2 events to ../plots/new_dataset_test/arm_pos_middle/20211128_09_56_BiGRU2l6_t750/logs/train/events.out.tfevents.1638089801.zwinge.2544663.2071.v2
	Could not flush events file.
(Full traceback below)

I hope I'm at the right place with this error. If I forgot any important info, please say so.

**Describe the expected behavior**
The run is completed without the error above.

**Other info / logs**:
2021-11-28 19:11:18.779759: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at summary_kernels.cc:106 : Permission denied: ../plots/new_dataset_test/arm_pos_middle/20211128_09_56_BiGRU2l6_t750/logs/train/events.out.tfevents.1638089801.zwinge.2544663.2071.v2; Permission denied
	Failed to flush 2 events to ../plots/new_dataset_test/arm_pos_middle/20211128_09_56_BiGRU2l6_t750/logs/train/events.out.tfevents.1638089801.zwinge.2544663.2071.v2
	Could not flush events file.
Traceback (most recent call last):
  File "main.py", line 312, in <module>
    main()
  File "main.py", line 241, in main
    validation_data=val_data, callbacks=keras_callbacks)
  File "/media/compute/homes/mhenning/MA/time-series-on-joints-emg/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/media/compute/homes/mhenning/MA/time-series-on-joints-emg/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1137, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/media/compute/homes/mhenning/MA/time-series-on-joints-emg/venv/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 412, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/media/compute/homes/mhenning/MA/time-series-on-joints-emg/venv/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 2179, in on_epoch_end
    self._log_epoch_metrics(epoch, logs)
  File "/media/compute/homes/mhenning/MA/time-series-on-joints-emg/venv/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 2220, in _log_epoch_metrics
    summary_ops_v2.scalar('epoch_' + name, value, step=epoch)
  File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/media/compute/homes/mhenning/MA/time-series-on-joints-emg/venv/lib/python3.6/site-packages/tensorflow/python/ops/summary_ops_v2.py", line 269, in as_default
    self.flush()
  File "/media/compute/homes/mhenning/MA/time-series-on-joints-emg/venv/lib/python3.6/site-packages/tensorflow/python/ops/summary_ops_v2.py", line 286, in flush
    return _flush_fn(writer=self)
  File "/media/compute/homes/mhenning/MA/time-series-on-joints-emg/venv/lib/python3.6/site-packages/tensorflow/python/ops/summary_ops_v2.py", line 967, in flush
    return gen_summary_ops.flush_summary_writer(resource, name=name)
  File "/media/compute/homes/mhenning/MA/time-series-on-joints-emg/venv/lib/python3.6/site-packages/tensorflow/python/ops/gen_summary_ops.py", line 201, in flush_summary_writer
    _ops.raise_from_not_ok_status(e, name)
  File "/media/compute/homes/mhenning/MA/time-series-on-joints-emg/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 6843, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.PermissionDeniedError: ../plots/new_dataset_test/arm_pos_middle/20211128_09_56_BiGRU2l6_t750/logs/train/events.out.tfevents.1638089801.zwinge.2544663.2071.v2; Permission denied
	Failed to flush 2 events to ../plots/new_dataset_test/arm_pos_middle/20211128_09_56_BiGRU2l6_t750/logs/train/events.out.tfevents.1638089801.zwinge.2544663.2071.v2
	Could not flush events file. [Op:FlushSummaryWriter]

**Comment by mohantym** [comment]
Hi @mahenning ! Have you tried from latest version  TF 2.7 yet?

**Comment by mahenning** [comment]
Not yet. As far as I know, the binaries come with support for a fixed  CUDA version. At least when I tried to run it with TF 2.4 or higher, it tried to start with CUDA 11. Unfortunately, I'm bound to CUDA 10. Is there an easy solution to run TF 2.7 with CUDA 10/CuDNN 7.x?
On my personal system, I run TF 2.4 with CUDA 11 and have not encountered this problem so far. I don't run the program in batches there, but I'm almost sure that this should not be the problem.

**Comment by mohantym** [comment]
Hi @mahenning ! Could you please provide a stand alone code to replicate the issue?

**Comment by mahenning** [comment]
I'm trying to find a minimal example to replicate. It is difficult to find, as it happens just every ~15-20 runs in my code, and not in a pattern. I'll get back here if I find a simple code that throws the error with different data.

**Comment by mohantym** [comment]
Hi @sanatmpa1! Could you please look at this issue?

**Comment by JosephCatrambone** [comment]
Just throwing my voice into the fray, I'm encountering a similar issue with Tensorboard, but from the PyTorch side.

Seems to run fine for a random number of epochs but crash eventually.

```
100%|██████████| 12501/12501 [25:41<00:00,  8.11it/s]
100%|██████████| 12501/12501 [25:33<00:00,  8.15it/s]
100%|██████████| 12501/12501 [25:35<00:00,  8.14it/s]
100%|██████████| 12501/12501 [25:35<00:00,  8.14it/s]
100%|██████████| 12501/12501 [25:37<00:00,  8.13it/s]
100%|██████████| 12501/12501 [25:36<00:00,  8.14it/s]
100%|██████████| 12501/12501 [25:36<00:00,  8.13it/s]
100%|██████████| 12501/12501 [25:35<00:00,  8.14it/s]
100%|██████████| 12501/12501 [25:37<00:00,  8.13it/s]
100%|██████████| 12501/12501 [25:37<00:00,  8.13it/s]
100%|██████████| 12501/12501 [25:35<00:00,  8.14it/s]
 14%|█▍        | 1799/12501 [03:44<14:08, 12.61it/s]Exception in thread Thread-1:
Traceback (most recent call last):
  File "E:\Applications\miniconda3\envs\venv_default\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "E:\Applications\miniconda3\envs\venv_default\lib\site-packages\tensorboard\summary\writer\event_file_writer.py", line 238, in run
    self._record_writer.write(data)
  File "E:\Applications\miniconda3\envs\venv_default\lib\site-packages\tensorboard\summary\writer\record_writer.py", line 40, in write
    self._writer.write(header + header_crc + data + footer_crc)
  File "E:\Applications\miniconda3\envs\venv_default\lib\site-packages\tensorboard\compat\tensorflow_stub\io\gfile.py", line 535, in write
    self.fs.append(self.filename, file_content, self.binary_mode)
  File "E:\Applications\miniconda3\envs\venv_default\lib\site-packages\tensorboard\compat\tensorflow_stub\io\gfile.py", line 158, in append
    self._write(filename, file_content, "ab" if binary_mode else "a")
  File "E:\Applications\miniconda3\envs\venv_default\lib\site-packages\tensorboard\compat\tensorflow_stub\io\gfile.py", line 162, in _write
    with io.open(filename, mode, encoding=encoding) as f:
PermissionError: [Errno 13] Permission denied: b'runs\\events.out.tfevents.1639411762.IVAKHNENKO.14776.0'

 14%|█▍        | 1799/12501 [04:00<14:08, 12.61it/s]
```

I thought it might have had something to do with...
- an out-of-disk-space issue, but as it turns out I've got plenty of storage.
- a simultaneous read from TensorBoard at the same time as a write, but it happens even if TensorBoard isn't active. (Though I want to recheck this.)
- file permissions, but I have all-write and all-read on the directory, and it's possible to write at least partially.

I'm running Windows 10 with TensorBoard 2.2.1 and PyTorch 1.10.

**Comment by sanatmpa1** [comment]
@mahenning,

As this looks like an issue related to `Tensorboard`. Can you please open a new issue in [tensorboad repo](https://github.com/tensorflow/tensorboard/issues)? Thanks!

**Comment by mahenning** [comment]
I opened an issue at
https://github.com/tensorflow/tensorboard/issues/5483
Thank you all for the answers!
