### ISSUE TITLE
Getting this issue while running my fit method (For CNN)

### ISSUE THREAD

**Issue by lionelsamrat10** [tensorflow/tensorflow#53281]
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_20164/3579053964.py in <module>
----> 1 history = model.fit(
      2     train_ds,
      3     epochs = EPOCH,
      4     batch_size = BATCH_SIZE,
      5     verbose = 1,

~\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\utils\traceback_utils.py in error_handler(*args, **kwargs)
     65     except Exception as e:  # pylint: disable=broad-except
     66       filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67       raise e.with_traceback(filtered_tb) from None
     68     finally:
     69       del filtered_tb

~\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\framework\func_graph.py in autograph_handler(*args, **kwargs)
   1127           except Exception as e:  # pylint:disable=broad-except
   1128             if hasattr(e, "ag_error_metadata"):
-> 1129               raise e.ag_error_metadata.to_exception(e)
   1130             else:
   1131               raise

AttributeError: in user code:

    File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\engine\training.py", line 946, in train_function  *
        return step_function(self, iterator)
    File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\engine\training.py", line 935, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\engine\training.py", line 928, in run_step  **
        outputs = model.train_step(data)
    File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\engine\training.py", line 846, in train_step
        self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\optimizer_v2\optimizer_v2.py", line 532, in minimize
        return self.apply_gradients(grads_and_vars, name=name)
    File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\optimizer_v2\optimizer_v2.py", line 668, in apply_gradients
        grads_and_vars = self._aggregate_gradients(grads_and_vars)
    File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\optimizer_v2\optimizer_v2.py", line 484, in _aggregate_gradients
        return self.gradient_aggregator(grads_and_vars)
    File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\optimizer_v2\utils.py", line 33, in all_reduce_sum_gradients
        if tf.__internal__.distribute.strategy_supports_no_merge_call():

    AttributeError: module 'tensorflow.compat.v2.__internal__.distribute' has no attribute 'strategy_supports_no_merge_call'

**Comment by sanatmpa1** [comment]
@lionelsamrat10,

Can you please fill the issue template, and also share the reproducible code to expedite the trouble-shooting process? Thanks!

**Comment by Fer020707** [comment]
Hello, in my case I am importing the following libraries while I run the example that comes as basic text classification in the official documentation of the tensorflow page (https://www.tensorflow.org/tutorials/keras/text_classification?hl=es-419). But I get the same error. My version of tensorflow is 2.7.0

`import matplotlib.pyplot as plt
import os
import re
import shutil
import string
import tensorflow as tf

from tensorflow.keras import layers
from tensorflow.keras import losses`

**Comment by jcr0269** [comment]
> Hello, in my case I am importing the following libraries while I run the example that comes as [basic text classification](https://www.tensorflow.org/tutorials/keras/text_classification?hl=es-419) in the official documentation of Tensorflow. But I get the same error. My version of tensorflow is 2.7.0
> 
> Running code for which the error occurred: `epochs = 10` `history = model.fit( train_ds, validation_data=val_ds, epochs=epochs)`
> 
> Libraries loads: `import matplotlib.pyplot as plt` `import os` `import re` `import shutil` `import string` `import tensorflow as tf` `from tensorflow.keras import layers` `from tensorflow.keras import losses`

I also am getting the same problem! I have been trying to debug it, but with no success so far.
