### ISSUE TITLE
SymbolAlreadyExposedError: Symbol random_rotation is already exposed as ('keras.preprocessing.image.random_rotation',)

### ISSUE THREAD

**Issue by akzenith** [tensorflow/tensorflow#53295]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10
- TensorFlow installed from (source or binary): cmd pip
- TensorFlow version: 
                    tensorboard                        2.7.0
                    tensorboard-data-server            0.6.1
                    tensorboard-plugin-wit             1.8.0
                    tensorflow                         2.7.0
                    tensorflow-addons                  0.15.0
                    tensorflow-estimator               2.7.0
                    tensorflow-io                      0.22.0
                    tensorflow-io-gcs-filesystem       0.22.0
                      tf-estimator-nightly               2.8.0.dev2021120309
                      tf-models-official                 2.7.0
                      tf-nightly                         2.8.0.dev20211202
                      tf-slim                            1.1.0
- Python version:  
                    Python 3.9.7
                    conda 4.10.3
- Installed using virtualenv? pip? conda?:              pip         21.2.4

- GPU model and memory:  NO GPU

**Describe the problem**
            
            raise SymbolAlreadyExposedError(
            tensorflow.python.util.tf_export.SymbolAlreadyExposedError: Symbol random_rotation is already exposed as ('keras.preprocessing.image.random_rotation',).

**Provide the exact sequence of commands / steps that you executed before running into the problem**
          VERIFICATION_SCRIPT = os.path.join('models', 'research', 'object_detection', 'builders', 'model_builder_tf2_test.py')
          # Verify Installation
          !python {VERIFICATION_SCRIPT}

**Any other info / logs**
                Traceback (most recent call last):
                  File "G:\object2\models\research\object_detection\builders\model_builder_tf2_test.py", line 25, in <module>
                    from object_detection.builders import model_builder
                  File "G:\anaconda3\lib\site-packages\object_detection-0.1-py3.9.egg\object_detection\builders\model_builder.py", line 70, in <module>
                    from object_detection.models import ssd_efficientnet_bifpn_feature_extractor as ssd_efficientnet_bifpn
                  File "G:\anaconda3\lib\site-packages\object_detection-0.1-py3.9.egg\object_detection\models\ssd_efficientnet_bifpn_feature_extractor.py", line 34, in <module>
                    from official.vision.image_classification.efficientnet import efficientnet_model
                  File "G:\anaconda3\lib\site-packages\tf_models_official-2.7.0-py3.9.egg\official\vision\image_classification\efficientnet\efficientnet_model.py", line 37, in <module>
                    from official.vision.image_classification import preprocessing
                  File "G:\anaconda3\lib\site-packages\tf_models_official-2.7.0-py3.9.egg\official\vision\image_classification\preprocessing.py", line 25, in <module>
                    from official.vision.image_classification import augment
                  File "G:\anaconda3\lib\site-packages\tf_models_official-2.7.0-py3.9.egg\official\vision\image_classification\augment.py", line 31, in <module>
                    from tensorflow.python.keras.layers.preprocessing import image_preprocessing as image_ops
                  File "G:\anaconda3\lib\site-packages\tensorflow\python\keras\layers\preprocessing\image_preprocessing.py", line 28, in <module>
                    from tensorflow.python.keras.preprocessing import image as image_preprocessing
                  File "G:\anaconda3\lib\site-packages\tensorflow\python\keras\preprocessing\__init__.py", line 22, in <module>
                    from tensorflow.python.keras.preprocessing import image
                  File "G:\anaconda3\lib\site-packages\tensorflow\python\keras\preprocessing\image.py", line 1140, in <module>
                    keras_export('keras.preprocessing.image.random_rotation')(random_rotation)
                  File "G:\anaconda3\lib\site-packages\tensorflow\python\util\tf_export.py", line 336, in __call__
                    self.set_attr(undecorated_func, api_names_attr, self._names)
                  File "G:\anaconda3\lib\site-packages\tensorflow\python\util\tf_export.py", line 351, in set_attr

**Comment by Saduf2019** [comment]
@akzenith 
Please follow [this link](https://github.com/tensorflow/tensorflow/issues/39483#issuecomment-629006902) and let us know.[[link](https://stackoverflow.com/questions/50596341/import-tensor-flow-library-error],[link1](#52980))

**Comment by Cipher-zzz** [comment]
Got same error in the version:  tf-nightly==2.9.0.dev20220109,
Fixed by installing tf-nightly==2.8.0. dev20211018.

**Comment by sarramargi** [comment]
Got same error in the version th-nightly==2.9.0.dev20220110
I could not install another version of tf-nightly without error
