### ISSUE TITLE
about how to conduct the tensor like the numpy or theao

### ISSUE THREAD

**Issue by tfka** [tensorflow/tensorflow#5332]
I can get the result by numpy or theano,but for tensorflow it may not support this
How can I do to get the result that I want
>>>import tensorflow as tf
>>> x = [[1,2,3],[4,5,6]]
>>> y = [0,1]
>>> z = [1,2]
>>> x = tf.constant(x)
>>> y = tf.constant(y)
>>> z = tf.constant(z)
>>> m = x[y,z]  # m = [2,6] is what I expect ,I just make a simple example ,Thanks
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users3/htleng/.local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 383, in _SliceHelper
    name=name)
  File "/users3/htleng/.local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 537, in strided_slice
    shrink_axis_mask=shrink_axis_mask)
  File "/users3/htleng/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2750, in strided_slice
    shrink_axis_mask=shrink_axis_mask, name=name)
  File "/users3/htleng/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
    op_def=op_def)
  File "/users3/htleng/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2382, in create_op
    set_shapes_for_outputs(ret)
  File "/users3/htleng/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1783, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/users3/htleng/.local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1645, in _DelegateStridedSliceShape
    return common_shapes.call_cpp_shape_fn(op, input_tensors_needed=[1, 2, 3])
  File "/users3/htleng/.local/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 596, in call_cpp_shape_fn
    raise ValueError(err.message)
ValueError: Shape must be rank 1 but is rank 2

**Comment by aselle** [comment]
This is almost assuredly something you do not want to do for performance reasons. You should be trying to write operations that do a lot of work per statement (i.e. in a batch-centric or simd fashion). If you are doing this for diagnostic purposes that is one thing, but model building, training and inference should not use anything like this.

If you really must do this you can use eval() or run() on a tensorflow tensor to get a numpy array back which supports individual index querying. 

For futher guidance on using TensorFlow write StackOverflow questions. This forum is for bugs and feature requests. Thank you!

**Comment by tfka** [comment]
@aselle ，I then use  tf.pack() and tf.gather_nd to get the result that I want ,but I can't get the gradient.
Any advice for me, thanks.

**Comment by aselle** [comment]
A gradient for gather_nd will be added soon, and we will also be adding tensor indirect indexing moving forward that will make the foo[tensor1] technique work.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity, we will reopen if further information becomes available. Thanks!
