### ISSUE TITLE
I am having this error in my code, "ValueError: No gradients provided for any variable:"

### ISSUE THREAD

**Issue by paktiger** [tensorflow/tensorflow#53320]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are

Epoch 1/2
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
C:\Users\BLACKP~1\AppData\Local\Temp/ipykernel_15028/4197043661.py in <module>
----> 1 history = model.fit(X_tr, np.array(y_tr), batch_size=22, epochs=2, validation_split=0.1, verbose=1)

c:\users\blackpearl\appdata\local\programs\python\python38\lib\site-packages\keras\utils\traceback_utils.py in error_handler(*args, **kwargs)
     65     except Exception as e:  # pylint: disable=broad-except
     66       filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67       raise e.with_traceback(filtered_tb) from None
     68     finally:
     69       del filtered_tb

c:\users\blackpearl\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\framework\func_graph.py in autograph_handler(*args, **kwargs)
   1127           except Exception as e:  # pylint:disable=broad-except
   1128             if hasattr(e, "ag_error_metadata"):
-> 1129               raise e.ag_error_metadata.to_exception(e)
   1130             else:
   1131               raise

ValueError: in user code:

    File "c:\users\blackpearl\appdata\local\programs\python\python38\lib\site-packages\keras\engine\training.py", line 878, in train_function  *
        return step_function(self, iterator)
    File "c:\users\blackpearl\appdata\local\programs\python\python38\lib\site-packages\keras\engine\training.py", line 867, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\users\blackpearl\appdata\local\programs\python\python38\lib\site-packages\keras\engine\training.py", line 860, in run_step  **
        outputs = model.train_step(data)
    File "c:\users\blackpearl\appdata\local\programs\python\python38\lib\site-packages\keras\engine\training.py", line 816, in train_step
        self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "c:\users\blackpearl\appdata\local\programs\python\python38\lib\site-packages\keras\optimizer_v2\optimizer_v2.py", line 532, in minimize
        return self.apply_gradients(grads_and_vars, name=name)
    File "c:\users\blackpearl\appdata\local\programs\python\python38\lib\site-packages\keras\optimizer_v2\optimizer_v2.py", line 633, in apply_gradients
        grads_and_vars = optimizer_utils.filter_empty_gradients(grads_and_vars)
    File "c:\users\blackpearl\appdata\local\programs\python\python38\lib\site-packages\keras\optimizer_v2\utils.py", line 73, in filter_empty_gradients
        raise ValueError(f"No gradients provided for any variable: {variable}. "

    ValueError: No gradients provided for any variable: (['embedding_2/embeddings:0', 'bidirectional_4/forward_lstm_4/lstm_cell_13/kernel:0', 'bidirectional_4/forward_lstm_4/lstm_cell_13/recurrent_kernel:0', 'bidirectional_4/forward_lstm_4/lstm_cell_13/bias:0', 'bidirectional_4/backward_lstm_4/lstm_cell_14/kernel:0', 'bidirectional_4/backward_lstm_4/lstm_cell_14/recurrent_kernel:0', 'bidirectional_4/backward_lstm_4/lstm_cell_14/bias:0', 'time_distributed/kernel:0', 'time_distributed/bias:0'],). Provided `grads_and_vars` is ((None, <tf.Variable 'embedding_2/embeddings:0' shape=(12962, 20) dtype=float32>), (None, <tf.Variable 'bidirectional_4/forward_lstm_4/lstm_cell_13/kernel:0' shape=(20, 300) dtype=float32>), (None, <tf.Variable 'bidirectional_4/forward_lstm_4/lstm_cell_13/recurrent_kernel:0' shape=(75, 300) dtype=float32>), (None, <tf.Variable 'bidirectional_4/forward_lstm_4/lstm_cell_13/bias:0' shape=(300,) dtype=float32>), (None, <tf.Variable 'bidirectional_4/backward_lstm_4/lstm_cell_14/kernel:0' shape=(20, 300) dtype=float32>), (None, <tf.Variable 'bidirectional_4/backward_lstm_4/lstm_cell_14/recurrent_kernel:0' shape=(75, 300) dtype=float32>), (None, <tf.Variable 'bidirectional_4/backward_lstm_4/lstm_cell_14/bias:0' shape=(300,) dtype=float32>), (None, <tf.Variable 'time_distributed/kernel:0' shape=(150, 75) dtype=float32>), (None, <tf.Variable 'time_distributed/bias:0' shape=(75,) dtype=float32>)).

**Comment by mohantym** [comment]
Hi @paktiger! Could you please fill the template from [here ](https://github.com/tensorflow/tensorflow/issues/new/choose)as it helps expedite the issue? Feel free to look at these similar issues for reference .[ link1](https://pretagteam.com/question/valueerror-no-gradients-provided-for-any-variable-when-using-modelfit),[link2](https://github.com/tensorflow/tensorflow/issues/1511). Thanks!

**Comment by paktiger** [comment]
#!/usr/bin/env python
# coding: utf-8

# In[2]:   import pandas as pd


# In[3]: data = pd.read_csv('C:/Users/BlackPearl/Desktop/Annotated Dataset/FullFile_Clean_500.tsv', encoding="latin1",sep='\t',error_bad_lines=False)


# In[4]: data.isnull().sum()

# In[7]:


data['Word'].count()


# In[7]:


data.groupby('IOB').count()


# In[13]:


data['IOB'].fillna("O",inplace= True)


# In[5]:


bool_series = pd.isnull(data['POS'])
data[bool_series]


# In[6]:


temp = []
outerList = []
for index, rows in data.iterrows():
    if rows["Word"] != ".":
        temp.append((rows["Word"], rows["POS"],rows["IOB"]))
    else:
        temp.append((rows["Word"], rows["POS"],rows["IOB"]))
        outerList.append(temp)
        temp = []


# In[7]:


words = list(set(data["Word"].values))
n_words = len(words); n_words


# In[8]:


tags = list(set(data["IOB"].values))
n_tags = len(tags); n_tags


# In[9]:


tags


# In[ ]:





# In[9]:


max_len = 85
word2idx = {w: i + 1 for i, w in enumerate(words)}
tag2idx = {t: i for i, t in enumerate(tags)}


# In[10]:


from keras.preprocessing.sequence import pad_sequences
X = [[word2idx[w[0]] for w in s] for s in outerList]


# In[11]:


X = pad_sequences(maxlen=max_len, sequences=X, padding="post", value=n_words-1)


# In[12]:


y = [[tag2idx[w[2]] for w in s] for s in outerList]


# In[13]:


y = pad_sequences(maxlen=max_len, sequences=y, padding="post", value=tag2idx["O"])


# In[14]:


from keras.utils import to_categorical


# In[15]:


y = [to_categorical(i, num_classes=n_tags) for i in y]


# In[16]:


from sklearn.model_selection import train_test_split


# In[17]:


X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2)


# In[ ]:





# In[18]:


import numpy as np
from tensorflow import keras
from tensorflow.keras import layers


# In[19]:


input = keras.Input(shape=(max_len),)


# In[20]:


model = layers.Embedding(input_dim=n_words + 1, output_dim=20, input_length=max_len, mask_zero=True)(input)  # 20-dim embedding


# In[21]:


model =  layers.Bidirectional(layers.LSTM(units=75, return_sequences=True, recurrent_dropout=0.1))(model)


# In[22]:


output = layers.Dense(75, activation="relu")(model)


# In[24]:


model = keras.Model(input,output)


# In[28]:


model.summary()


# In[ ]:





# In[ ]:





# In[26]:


model = Model(input, out)


# In[29]:


model.compile(optimizer="rmsprop",metrics=["accuracy"])


# In[30]:


model.summary()


# In[31]:


import numpy as np


# In[33]:


history = model.fit(X_tr, np.array(y_tr), batch_size=22, epochs=200, validation_split=0.1, verbose=1)


# In[35]:


from seqeval.metrics import precision_score, recall_score, f1_score, classification_report


# In[36]:


test_pred = model.predict(X_te, verbose=1)


# In[37]:


idx2tag = {i: w for w, i in tag2idx.items()}

def pred2label(pred):
    out = []
    for pred_i in pred:
        out_i = []
        for p in pred_i:
            p_i = np.argmax(p)
            out_i.append(idx2tag[p_i])
        out.append(out_i)
    return out
    
pred_labels = pred2label(test_pred)
test_labels = pred2label(y_te)


# In[32]:


print("F1-score: {:.1%}".format(f1_score(test_labels, pred_labels)))


# In[33]:


print("Precision-score: {:.1%}".format(precision_score(test_labels, pred_labels)))


# In[34]:


print("Recall-Score: {:.1%}".format(recall_score(test_labels, pred_labels)))


# In[32]:


print(classification_report(test_labels, pred_labels))

   precision    recall  f1-score   support

  Opinion       0.70      0.74      0.72     15318
   Person       0.61      0.67      0.64       516
  Feature       0.90      0.93      0.91      2915
    Movie       0.55      0.44      0.49       632

micro avg       0.72      0.76      0.74     19381
macro avg       0.72      0.76      0.74     19381precision    recall  f1-score   support

  Opinion       0.73      0.79      0.76     26735
   Person       0.78      0.70      0.74       901
  Feature       0.94      0.93      0.93      5006
    Movie       0.50      0.51      0.50      1044

micro avg       0.76      0.80      0.78     33686
macro avg       0.76      0.80      0.78     33686

# In[37]:


print("F1-score: {:.1%}".format(f1_score(test_labels, pred_labels)))


# In[38]:


print("Precision-score: {:.1%}".format(precision_score(test_labels, pred_labels)))


# In[39]:


print("Recall-Score: {:.1%}".format(recall_score(test_labels, pred_labels)))


# In[47]:


print("F1-score: {:.1%}".format(f1_score(test_labels, pred_labels)))

Different
# In[30]:


print("F1-score: {:.1%}".format(f1_score(test_labels, pred_labels)))


# In[31]:


print("Precision-score: {:.1%}".format(precision_score(test_labels, pred_labels)))


# In[32]:


print("Recall-Score: {:.1%}".format(recall_score(test_labels, pred_labels)))


# In[33]:


print(classification_report(test_labels, pred_labels))


# 100 epichos
# 

# In[38]:


print("F1-score: {:.1%}".format(f1_score(test_labels, pred_labels)))


# In[39]:


print("Precision-score: {:.1%}".format(precision_score(test_labels, pred_labels)))


# In[40]:


print("Recall-Score: {:.1%}".format(recall_score(test_labels, pred_labels)))


# In[ ]:
