### ISSUE TITLE
Unit test //tensorflow/python/ops/ragged:ragged_dispatch_test fails on AARCH64

### ISSUE THREAD

**Issue by elfringham** [tensorflow/tensorflow#53322]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): git HEAD
- Python version: 3.8.10
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 11.2.0
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

Test fails with the following error
FAIL: testRaggedDispatch18 (op=<function unsorted_segment_sqrt_n at 0xffff18e41f70>, kwargs={'data': tf.RaggedTensorValue(values=array([1., 2., 3., 4., 6.]), row_splits=array([0, 2, 5])), 'segment_ids': tf.RaggedTensorValue(values=array([0, 1, 0, 0, 0]), row_splits=array([0, 2, 5])), 'num_segments': 2}, expected=[7.0, 2.0]) (_main_.RaggedDispatchTest)
RaggedDispatchTest.testRaggedDispatch18 (op=<function unsorted_segment_sqrt_n at 0xffff18e41f70>, kwargs={'data': tf.RaggedTensorValue(values=array([1., 2., 3., 4., 6.]), row_splits=array([0, 2, 5])), 'segment_ids': tf.RaggedTensorValue(values=array([0, 1, 0, 0, 0]), row_splits=array([0, 2, 5])), 'num_segments': 2}, expected=[7.0, 2.0])
testRaggedDispatch(op=<function unsorted_segment_sqrt_n at 0xffff18e41f70>, kwargs={'data': tf.RaggedTensorValue(values=array([1., 2., 3., 4., 6.]), row_splits=array([0, 2, 5])), 'segment_ids': tf.RaggedTensorValue(values=array([0, 1, 0, 0, 0]), row_splits=array([0, 2, 5])), 'num_segments': 2}, expected=[7.0, 2.0])
----------------------------------------------------------------------

Traceback (most recent call last):
File "/home/builder/.cache/bazel/_bazel_builder/9dc2dbd69dc3512cedb530e1521082e7/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/python/ops/ragged/ragged_dispatch_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 1407, in decorated
f(self, *args, **kwargs)
File "/home/builder/.cache/bazel/_bazel_builder/9dc2dbd69dc3512cedb530e1521082e7/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/python/ops/ragged/ragged_dispatch_test.runfiles/absl_py/absl/testing/parameterized.py", line 314, in bound_param_test
return test_method(self, **testcase_params)
File "/home/builder/.cache/bazel/_bazel_builder/9dc2dbd69dc3512cedb530e1521082e7/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/python/ops/ragged/ragged_dispatch_test.runfiles/org_tensorflow/tensorflow/python/ops/ragged/ragged_dispatch_test.py", line 892, in testRaggedDispatch
assert_fn(result, expected)
File "/home/builder/.cache/bazel/_bazel_builder/9dc2dbd69dc3512cedb530e1521082e7/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/python/ops/ragged/ragged_dispatch_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 1447, in decorated
return f(*args, **kwds)
File "/home/builder/.cache/bazel/_bazel_builder/9dc2dbd69dc3512cedb530e1521082e7/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/python/ops/ragged/ragged_dispatch_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 3163, in assertAllEqual
np.testing.assert_array_equal(a, b, err_msg="\n".join(msgs))
File "/usr/local/lib/python3.8/dist-packages/numpy/testing/_private/utils.py", line 930, in assert_array_equal
assert_array_compare(operator._eq_, x, y, err_msg=err_msg,
File "/usr/local/lib/python3.8/dist-packages/numpy/testing/_private/utils.py", line 840, in assert_array_compare
raise AssertionError(msg)
AssertionError:
Arrays are not equal

not equal where = (array([0, 1]),)
not equal lhs = array([7., 2.])
not equal rhs = array([7., 2.])
Mismatched elements: 2 / 2 (100%)
Max absolute difference: 8.8817842e-16
Max relative difference: 1.26882631e-16
x: array([7., 2.])
y: array([7., 2.])

**Describe the expected behavior**

Test passes

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): yes
- Briefly describe your candidate solution(if contributing): Add a tolerance value to the test to allow minor difference in value

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

bazel test --test_timeout=300,500,-1,-1 --flaky_test_attempts=3 --test_output=all --cache_test_results=no --remote_http_cache=""  --remote_cache_proxy="" --noremote_accept_cached --config=nonccl --build_tag_filters=-no_oss,-oss_serial,-gpu,-tpu,-benchmark-test,-v1only --test_tag_filters=-no_oss,-oss_serial,-gpu,-tpu,-benchmark-test,-v1only --copt=-ffp-contract=off --verbose_failures -- //tensorflow/python/ops/ragged:ragged_dispatch_test

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by elfringham** [comment]
@cfRod @nSircombe

**Comment by sushreebarsa** [comment]
@elfringham This issue will be closed once the [PR](https://github.com/tensorflow/tensorflow/pull/53323) is merged. Thanks!
