### ISSUE TITLE
Python Configuration Error: Problem getting numpy include path while building with Bazel

### ISSUE THREAD

**Issue by nitolpalak** [tensorflow/tensorflow#53379]
<em>I am facing error trying to build tensorflow from source. My goal is to use tensorflow API in C++. I am following [this doc](https://www.tensorflow.org/install/source) for that. But whenever I run `bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package` I get `Python Configuration Error: Problem getting numpy include path.`</em>

**System information**
- OS Platform and Distribution: Ubuntu 18.04
- TensorFlow installed from: source
- TensorFlow version: 2.1
- Python version: 3.6.9
- Bazel version: 0.29.1

**Describe the problem**
I have tried to build tensorflow in Ubuntu 18.04 created in Oracle VM VirtualBox.  When I tried to run the `bazel build [--config=option] //tensorflow/tools/pip_package:build_pip_package` command to build _tensorflow cpu-only_ version, The following error message persists:
```
ERROR: no such target '//:[--config=option]': target '[--config=option]' not declared in package '' defined by /home/niaz/Desktop/TF_C++_API/tensorflow/BUILD
INFO: Elapsed time: 0.268s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
```
Then according to [this reply](https://github.com/tensorflow/tensorflow/issues/44876#issuecomment-727388512) in another issue, I changed the command into `bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package`. But then the following error persists:
```
Python Configuration Error: Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named numpy
Is numpy installed?
INFO: Elapsed time: 0.966s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded, 5 targets con\
figured)

```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
According to [the doc](https://www.tensorflow.org/install/source) I have followed the following steps to install Python and the TensorFlow package dependencies:
`sudo apt install python3-dev python3-pip`
`pip install -U --user pip numpy wheel`
`pip install -U --user keras_preprocessing --no-deps`
Then I have installed Bazel 0.29.1 from [bazel github](https://github.com/bazelbuild/bazel/releases?page=6) using _bazel-0.29.1-linux-x86_64_.
After that, I have cloned the [Tensorflow repo](https://github.com/tensorflow/tensorflow.git) and checked into _r2.1_ branch.
Then I have run `./configure` and the following is the output:
```
WARNING: Running Bazel server needs to be killed, because the startup options are different.
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.29.1 installed.
Please specify the location of python. [Default is /usr/bin/python]: 


Found possible Python library paths:
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python2.7/dist-packages]

Do you wish to build TensorFlow with XLA JIT support? [Y/n]: n
No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: n
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: n
No CUDA support will be enabled for TensorFlow.

Do you wish to download a fresh release of clang? (Experimental) [y/N]: n
Clang will not be downloaded.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native -Wno-sign-compare]: 


Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: n
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
	--config=mkl         	# Build with MKL support.
	--config=monolithic  	# Config for mostly static monolithic build.
	--config=ngraph      	# Build with Intel nGraph support.
	--config=numa        	# Build with NUMA support.
	--config=dynamic_kernels	# (Experimental) Build kernels into separate shared objects.
	--config=v2          	# Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
	--config=noaws       	# Disable AWS S3 filesystem support.
	--config=nogcp       	# Disable GCP support.
	--config=nohdfs      	# Disable HDFS support.
	--config=nonccl      	# Disable NVIDIA NCCL support.
Configuration finished

```

After that, I have run `bazel build [--config=option] //tensorflow/tools/pip_package:build_pip_package` command and the following is the output:
```
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=79
INFO: Reading rc options for 'build' from /home/niaz/Desktop/TF_C++_API/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone --strategy=Genrule=standalone -c opt --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --config=v2
INFO: Reading rc options for 'build' from /home/niaz/Desktop/TF_C++_API/tensorflow/.tf_configure.bazelrc:
  'build' options: --host_force_python=PY2 --action_env PYTHON_BIN_PATH=/usr/bin/python --action_env PYTHON_LIB_PATH=/usr/local/lib/python2.7/dist-packages --python_path=/usr/bin/python --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:v2 in file /home/niaz/Desktop/TF_C++_API/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
ERROR: Skipping '[--config=option]': no such target '//:[--config=option]': target '[--config=option]' not declared in package '' defined by /home/niaz/Desktop/TF_C++_API/tensorflow/BUILD
ERROR: no such target '//:[--config=option]': target '[--config=option]' not declared in package '' defined by /home/niaz/Desktop/TF_C++_API/tensorflow/BUILD
INFO: Elapsed time: 2.548s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
    currently loading: tensorflow/tools/pip_package
```
Then according to [this reply](https://github.com/tensorflow/tensorflow/issues/44876#issuecomment-727388512) in another issue, I changed the command to `bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package`. But then the following is the output:
```
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=79
INFO: Reading rc options for 'build' from /home/niaz/Desktop/TF_C++_API/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone --strategy=Genrule=standalone -c opt --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --config=v2
INFO: Reading rc options for 'build' from /home/niaz/Desktop/TF_C++_API/tensorflow/.tf_configure.bazelrc:
  'build' options: --host_force_python=PY2 --action_env PYTHON_BIN_PATH=/usr/bin/python --action_env PYTHON_LIB_PATH=/usr/local/lib/python2.7/dist-packages --python_path=/usr/bin/python --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:v2 in file /home/niaz/Desktop/TF_C++_API/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:opt in file /home/niaz/Desktop/TF_C++_API/tensorflow/.tf_configure.bazelrc: --copt=-march=native --copt=-Wno-sign-compare --host_copt=-march=native --define with_default_optimizations=true
INFO: Call stack for the definition of repository 'local_config_python' which is a python_configure (rule definition at /home/niaz/Desktop/TF_C++_API/tensorflow/third_party/py/python_configure.bzl:347:20):
 - /home/niaz/Desktop/TF_C++_API/tensorflow/tensorflow/workspace.bzl:77:5
 - /home/niaz/Desktop/TF_C++_API/tensorflow/WORKSPACE:19:1
ERROR: An error occurred during the fetch of repository 'local_config_python':
   Traceback (most recent call last):
	File "/home/niaz/Desktop/TF_C++_API/tensorflow/third_party/py/python_configure.bzl", line 345
		_create_local_python_repository(repository_ctx)
	File "/home/niaz/Desktop/TF_C++_API/tensorflow/third_party/py/python_configure.bzl", line 296, in _create_local_python_repository
		_get_numpy_include(repository_ctx, python_bin)
	File "/home/niaz/Desktop/TF_C++_API/tensorflow/third_party/py/python_configure.bzl", line 276, in _get_numpy_include
		_execute(repository_ctx, [python_bin, "-c",..."], <2 more arguments>)
	File "/home/niaz/Desktop/TF_C++_API/tensorflow/third_party/py/python_configure.bzl", line 56, in _execute
		_fail("\n".join([error_msg.strip() if ... ""]))
	File "/home/niaz/Desktop/TF_C++_API/tensorflow/third_party/py/python_configure.bzl", line 27, in _fail
		fail(("%sPython Configuration Error:%...)))
Python Configuration Error: Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named numpy
Is numpy installed?
INFO: Call stack for the definition of repository 'gast_archive' which is a tf_http_archive (rule definition at /home/niaz/Desktop/TF_C++_API/tensorflow/third_party/repo.bzl:121:19):
 - /home/niaz/Desktop/TF_C++_API/tensorflow/tensorflow/workspace.bzl:336:5
 - /home/niaz/Desktop/TF_C++_API/tensorflow/WORKSPACE:19:1
INFO: Call stack for the definition of repository 'astor_archive' which is a tf_http_archive (rule definition at /home/niaz/Desktop/TF_C++_API/tensorflow/third_party/repo.bzl:121:19):
 - /home/niaz/Desktop/TF_C++_API/tensorflow/tensorflow/workspace.bzl:312:5
 - /home/niaz/Desktop/TF_C++_API/tensorflow/WORKSPACE:19:1
ERROR: While resolving toolchains for target //tensorflow:libtensorflow_framework.so.2.1.4: invalid registered toolchain '@local_config_python//:py_toolchain': no such package '@local_config_python//': Traceback (most recent call last):
	File "/home/niaz/Desktop/TF_C++_API/tensorflow/third_party/py/python_configure.bzl", line 345
		_create_local_python_repository(repository_ctx)
	File "/home/niaz/Desktop/TF_C++_API/tensorflow/third_party/py/python_configure.bzl", line 296, in _create_local_python_repository
		_get_numpy_include(repository_ctx, python_bin)
	File "/home/niaz/Desktop/TF_C++_API/tensorflow/third_party/py/python_configure.bzl", line 276, in _get_numpy_include
		_execute(repository_ctx, [python_bin, "-c",..."], <2 more arguments>)
	File "/home/niaz/Desktop/TF_C++_API/tensorflow/third_party/py/python_configure.bzl", line 56, in _execute
		_fail("\n".join([error_msg.strip() if ... ""]))
	File "/home/niaz/Desktop/TF_C++_API/tensorflow/third_party/py/python_configure.bzl", line 27, in _fail
		fail(("%sPython Configuration Error:%...)))
Python Configuration Error: Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named numpy
Is numpy installed?
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: invalid registered toolchain '@local_config_python//:py_toolchain': no such package '@local_config_python//': Traceback (most recent call last):
	File "/home/niaz/Desktop/TF_C++_API/tensorflow/third_party/py/python_configure.bzl", line 345
		_create_local_python_repository(repository_ctx)
	File "/home/niaz/Desktop/TF_C++_API/tensorflow/third_party/py/python_configure.bzl", line 296, in _create_local_python_repository
		_get_numpy_include(repository_ctx, python_bin)
	File "/home/niaz/Desktop/TF_C++_API/tensorflow/third_party/py/python_configure.bzl", line 276, in _get_numpy_include
		_execute(repository_ctx, [python_bin, "-c",..."], <2 more arguments>)
	File "/home/niaz/Desktop/TF_C++_API/tensorflow/third_party/py/python_configure.bzl", line 56, in _execute
		_fail("\n".join([error_msg.strip() if ... ""]))
	File "/home/niaz/Desktop/TF_C++_API/tensorflow/third_party/py/python_configure.bzl", line 27, in _fail
		fail(("%sPython Configuration Error:%...)))
Python Configuration Error: Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named numpy
Is numpy installed?
INFO: Elapsed time: 3.397s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (70 packages loaded, 127 targets \
configured)

```

**Any other info / logs**
I have tried this with Ubuntu 20.04 first and Ubuntu 18.04 after that as according to [this bazel build doc](https://docs.bazel.build/versions/main/install-ubuntu.html) Bazel is testedly supported for Ubuntu 18.04 and Ubuntu 16.04, but the problem still persists.
I have also checked with `pip3 freeze` and `pip3 list` that `numpy==1.19.5` version exists in my environment. I am not using any virtual environment currently. I have checked some related issues but none of them solved my problem.

**Comment by sushreebarsa** [comment]
@nitolpalak We see that you are using older version of TF 2.1 , could you please try to upgrade to latest TF v2.7.0 and let us know the outcome? Thank you!

**Comment by nitolpalak** [comment]
@sushreebarsa I was able to solve the issue after installing _numpy_ and _future_ using both pip and pip3. Looks like the problem was previously I installed numpy and future only in pip3. After installing those packages in pip too, the previous error was fixed. But currently I am having a new issue. I would really like to use TF 2.1 if possible as some other libraries I am currently working with depends on this. The current error is as below:
```
[7,040 / 8,707] 6 actions running
    Compiling tensorflow/core/kernels/broadcast_to_op.cc; 723s local
    Compiling tensorflow/core/kernels/bias_op.cc; 717s local
[7,040 / 8,707] 6 actions running
    Compiling tensorflow/core/kernels/broadcast_to_op.cc; 725s local
    Compiling tensorflow/core/kernels/bias_op.cc; 719s local
ERROR: /home/niaz/Desktop/TF_C++_API/tensorflow/tensorflow/core/kernels/BUILD:1048:1: C++ compilation of rule '//tensorflow/core/kernels:broadcast_to_op' failed (Exit 4)
[7,041 / 8,707] 5 actions running
    Compiling tensorflow/core/kernels/bias_op.cc; 719s local
    Compiling tensorflow/core/kernels/conv_grad_input_ops.cc; gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
[7,041 / 8,707] 5 actions running
    Compiling tensorflow/core/kernels/bias_op.cc; 719s local
    Compiling tensorflow/core/kernels/conv_grad_input_ops.cc; [7,041 / 8,707] 5 actions running
    Compiling tensorflow/core/kernels/bias_op.cc; 719s local
    Compiling tensorflow/core/kernels/conv_grad_input_ops.cc; [7,041 / 8,707] 5 actions running
    Compiling tensorflow/core/kernels/bias_op.cc; 720s local
    Compiling tensorflow/core/kernels/conv_grad_input_ops.cc; [7,041 / 8,707] 5 actions running
    Compiling tensorflow/core/kernels/bias_op.cc; 721s local
    Compiling tensorflow/core/kernels/conv_grad_input_ops.cc; Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2744.898s, Critical Path: 725.69s
INFO: 4377 processes: 4377 local.
FAILED: Build did NOT complete successfully

```

**Comment by nitolpalak** [comment]
@sushreebarsa I have tried to build tensorflow 2.7 in my windows 10 environment and posted an issue regarding that [here](https://github.com/tensorflow/tensorflow/issues/53382)

**Comment by sushreebarsa** [comment]
@nitolpalak We are supporting TF v2.4 and later .Older versions are no longer supported.As per your above [comment](https://github.com/tensorflow/tensorflow/issues/53379#issuecomment-990528488) ,if you want to use TF v2.1 then could you please post this issue in [TF forum](https://discuss.tensorflow.org/) where there is a larger community to help? We are tracking this #53382 ticket as well. Thank you!

**Comment by TrieBr** [comment]
I solved this with `sudo apt-get install python3-numpy`.
