### ISSUE TITLE
Android Example SurfaceTextureRenderer

### ISSUE THREAD

**Issue by gitunit** [tensorflow/tensorflow#534]
i've build the app with **sdk** = 23 and **ndk** = 21 and installed the apk on a nexus 4.
*sometimes it works* but often the camera preview is visible but without results on the top.

looking into Android Monitor, i get the following error message in case when the app doesn't work:

```
12-17 19:22:08.802 30054-30283/org.tensorflow.demo E/BufferQueueProducer: [unnamed-30054-2] dequeueBuffer: BufferQueue has been abandoned
12-17 19:22:08.802 30054-30283/org.tensorflow.demo E/Legacy-CameraDevice-JNI: LegacyCameraDevice_nativeProduceFrame: Error while producing frame No such device (-19).
12-17 19:22:08.803 30054-30283/org.tensorflow.demo W/SurfaceTextureRenderer: Surface abandoned, dropping frame. 
                                                                             android.hardware.camera2.legacy.LegacyExceptionUtils$BufferQueueAbandonedException
                                                                                 at android.hardware.camera2.legacy.LegacyExceptionUtils.throwOnError(LegacyExceptionUtils.java:64)
                                                                                 at android.hardware.camera2.legacy.LegacyCameraDevice.produceFrame(LegacyCameraDevice.java:583)
                                                                                 at android.hardware.camera2.legacy.SurfaceTextureRenderer.drawIntoSurfaces(SurfaceTextureRenderer.java:752)
                                                                                 at android.hardware.camera2.legacy.GLThreadManager$1.handleMessage(GLThreadManager.java:105)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                                 at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by andrewharp** [comment]
Is this with a recent version of the repo?

Prior to commit
https://github.com/tensorflow/tensorflow/commit/cd53f3c3302c9312c1840389a9988a879b8b9dd5#diff-806cae37e77a0337eada26c104bc1c23 this would be possible due to a GC'd Surface resource.

**Comment by gitunit** [comment]
@andrewharp ok, i've rebuild with the latest pull, seems to be resolved. thx
