### ISSUE TITLE
RNN predict() raised error if shape is not the same as training set for the first time

### ISSUE THREAD

**Issue by henrysky** [tensorflow/tensorflow#53438]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 21H2 x64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): 2.7.0 source
- TensorFlow version (use command below): 2.7.0
- Python version: 3.9.7
- Bazel version (if compiling from source): 4.2.2
- GCC/Compiler version (if compiling from source): msvc v1916
- CUDA/cuDNN version: 11.5/ 8.2
- GPU model and memory: GTX1060 6GB
- 
**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1Baaf74EzBjmuCUyY8MwFOGHAJwK2BUSP?usp=sharing

**Describe the current behavior**
```python
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM

mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
sample, sample_label = x_train[0], y_train[0]

model = Sequential()

# Layers
model.add(LSTM(128, input_shape=(x_train.shape[1:]), return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(128))
model.add(Dropout(0.2))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(10, activation='softmax'))

# Optimizer
opt = tf.keras.optimizers.Adam(lr=1e-3, decay=1e-5)

#Compile
model.compile(loss='sparse_categorical_crossentropy', optimizer=opt, metrics=['accuracy'])

#Fit
model.fit(x_train, y_train, epochs=1, validation_data=(x_test, y_test))
```

and the run

```python
model.predict(x_test[0:1, :10, :])
```

raised error

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_5600/1128729238.py in <module>
      1 ans = []
      2 for i in range(1, 28):
----> 3     ans.append(model.predict(x_test[0:1, :i, :])[0])

~\miniconda3\lib\site-packages\keras\utils\traceback_utils.py in error_handler(*args, **kwargs)
     65     except Exception as e:  # pylint: disable=broad-except
     66       filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67       raise e.with_traceback(filtered_tb) from None
     68     finally:
     69       del filtered_tb

~\miniconda3\lib\site-packages\tensorflow\python\framework\func_graph.py in autograph_handler(*args, **kwargs)
   1127           except Exception as e:  # pylint:disable=broad-except
   1128             if hasattr(e, "ag_error_metadata"):
-> 1129               raise e.ag_error_metadata.to_exception(e)
   1130             else:
   1131               raise

ValueError: in user code:

    File "C:\Users\Henry\miniconda3\lib\site-packages\keras\engine\training.py", line 1621, in predict_function  *
        return step_function(self, iterator)
    File "C:\Users\Henry\miniconda3\lib\site-packages\keras\engine\training.py", line 1611, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\Henry\miniconda3\lib\site-packages\keras\engine\training.py", line 1604, in run_step  **
        outputs = model.predict_step(data)
    File "C:\Users\Henry\miniconda3\lib\site-packages\keras\engine\training.py", line 1572, in predict_step
        return self(x, training=False)
    File "C:\Users\Henry\miniconda3\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\Henry\miniconda3\lib\site-packages\keras\engine\input_spec.py", line 263, in assert_input_compatibility
        raise ValueError(f'Input {input_index} of layer "{layer_name}" is '

    ValueError: Input 0 of layer "sequential_1" is incompatible with the layer: expected shape=(None, 28, 28), found shape=(None, 1, 28)
```

But then if you run this first

```python
model.predict(x_test[0:1])
```

and then run the same code gives expected result

```python
model.predict(x_test[0:1, :10, :])
```

**Describe the expected behavior**

```python
model.predict(x_test[0:1, :10, :])
```
should run fine the first time without running `model.predict(x_test[0:1])` first.

**Briefly describe your candidate solution(if contributing):**

Something (a shape checking) is probably wrong when building the predict function for the model? thats why after the first predict() ran without error, the code will work fine.

**Comment by mohantym** [comment]
Hi @henrysky ! It seems you have raised this in Keras repo too. Could you please this close issue here as it will be tracked down there in Keras repo.
