### ISSUE TITLE
MacOS: Problem getting numpy include path.

### ISSUE THREAD

**Issue by w3sip** [tensorflow/tensorflow#53467]
<em>Please make sure that this is a bug. As per our
**Describe the current behavior**
I am able to build on my development Mac. However, running on the CI Mac node, we get an error that looks like this:

```
2021-12-17T01:27:56.6979400Z Analyzing: target //tensorflow/lite/ios:TensorFlowLiteC_static_framework (1 packages loaded, 0 targets configured)
2021-12-17T01:27:58.6232140Z Analyzing: target //tensorflow/lite/ios:TensorFlowLiteC_static_framework (21 packages loaded, 10 targets configured)
2021-12-17T01:27:58.8729360Z INFO: Repository local_execution_config_python instantiated at:
2021-12-17T01:27:58.8731780Z   /Users/runner2/.conan/data/tensorflow-lite/2.5.0.18+5089e313/ci/branch_feat_2.7.0/build/3b95326f653baf403ae4d70dae74814d9c4fef8a/tensorflow/WORKSPACE:15:14: in <toplevel>
2021-12-17T01:27:58.8734480Z   /Users/runner2/.conan/data/tensorflow-lite/2.5.0.18+5089e313/ci/branch_feat_2.7.0/build/3b95326f653baf403ae4d70dae74814d9c4fef8a/tensorflow/tensorflow/workspace2.bzl:1108:19: in workspace
2021-12-17T01:27:58.8737750Z   /Users/runner2/.conan/data/tensorflow-lite/2.5.0.18+5089e313/ci/branch_feat_2.7.0/build/3b95326f653baf403ae4d70dae74814d9c4fef8a/tensorflow/tensorflow/workspace2.bzl:84:27: in _tf_toolchains
2021-12-17T01:27:58.8739200Z   /private/var/tmp/_bazel_runner2/14b6f7e45d646cdf7b1c6e3a405fb4ce/external/tf_toolchains/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
2021-12-17T01:27:58.8740200Z   /private/var/tmp/_bazel_runner2/14b6f7e45d646cdf7b1c6e3a405fb4ce/external/tf_toolchains/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
2021-12-17T01:27:58.8740920Z Repository rule local_python_configure defined at:
2021-12-17T01:27:58.8742180Z   /Users/runner2/.conan/data/tensorflow-lite/2.5.0.18+5089e313/ci/branch_feat_2.7.0/build/3b95326f653baf403ae4d70dae74814d9c4fef8a/tensorflow/third_party/py/python_configure.bzl:275:41: in <toplevel>
2021-12-17T01:27:58.8812530Z INFO: Repository local_config_python instantiated at:
2021-12-17T01:27:58.8814680Z   /Users/runner2/.conan/data/tensorflow-lite/2.5.0.18+5089e313/ci/branch_feat_2.7.0/build/3b95326f653baf403ae4d70dae74814d9c4fef8a/tensorflow/WORKSPACE:15:14: in <toplevel>
2021-12-17T01:27:58.8816660Z   /Users/runner2/.conan/data/tensorflow-lite/2.5.0.18+5089e313/ci/branch_feat_2.7.0/build/3b95326f653baf403ae4d70dae74814d9c4fef8a/tensorflow/tensorflow/workspace2.bzl:1108:19: in workspace
2021-12-17T01:27:58.8818170Z   /Users/runner2/.conan/data/tensorflow-lite/2.5.0.18+5089e313/ci/branch_feat_2.7.0/build/3b95326f653baf403ae4d70dae74814d9c4fef8a/tensorflow/tensorflow/workspace2.bzl:94:21: in _tf_toolchains
2021-12-17T01:27:58.8818980Z Repository rule python_configure defined at:
2021-12-17T01:27:58.8820110Z   /Users/runner2/.conan/data/tensorflow-lite/2.5.0.18+5089e313/ci/branch_feat_2.7.0/build/3b95326f653baf403ae4d70dae74814d9c4fef8a/tensorflow/third_party/py/python_configure.bzl:294:35: in <toplevel>
2021-12-17T01:27:58.8864240Z ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
2021-12-17T01:27:58.8865240Z    Traceback (most recent call last):
2021-12-17T01:27:58.8867660Z 	File "/Users/runner2/.conan/data/tensorflow-lite/2.5.0.18+5089e313/ci/branch_feat_2.7.0/build/3b95326f653baf403ae4d70dae74814d9c4fef8a/tensorflow/third_party/py/python_configure.bzl", line 213, column 39, in _create_local_python_repository
2021-12-17T01:27:58.8869530Z 		numpy_include = _get_numpy_include(repository_ctx, python_bin) + "/numpy"
2021-12-17T01:27:58.8870840Z 	File "/Users/runner2/.conan/data/tensorflow-lite/2.5.0.18+5089e313/ci/branch_feat_2.7.0/build/3b95326f653baf403ae4d70dae74814d9c4fef8a/tensorflow/third_party/py/python_configure.bzl", line 187, column 19, in _get_numpy_include
2021-12-17T01:27:58.8871650Z 		return execute(
2021-12-17T01:27:58.8872840Z 	File "/Users/runner2/.conan/data/tensorflow-lite/2.5.0.18+5089e313/ci/branch_feat_2.7.0/build/3b95326f653baf403ae4d70dae74814d9c4fef8a/tensorflow/third_party/remote_config/common.bzl", line 219, column 13, in execute
2021-12-17T01:27:58.8873970Z 		fail(
2021-12-17T01:27:58.8874300Z Error in fail: Problem getting numpy include path.
2021-12-17T01:27:58.8874970Z Traceback (most recent call last):
2021-12-17T01:27:58.8875640Z   File "<string>", line 1, in <module>
2021-12-17T01:27:58.8876820Z ModuleNotFoundError: No module named 'numpy'
2021-12-17T01:27:58.8877460Z Is numpy installed?
```

The only difference is, CI node uses Homebrew python 3.8, while the dev system is using system python. 
I've tried using venv on both machines, which doesn't change the outcome. 
I've also attempted setting `PYTHON_BIN_PATH` and `PYTHON_LIB_PATH` (for both venv and direct Homebrew python scenario) with no luck.

**Describe the expected behavior**
I'd expect it to build no matter which python is being used.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by tilakrayal** [comment]
@w3sip ,
Can you please take a look at this SO link [1](https://stackoverflow.com/questions/60453261/how-to-default-python3-8-on-my-mac-using-homebrew),[2](https://stackoverflow.com/questions/60435566/python-official-newest-version-homebrew-version-and-installed-version-differ-on) and [issue](https://github.com/tensorflow/tensorflow/issues/51352) with the similar error.It helps.Thanks
