### ISSUE TITLE
error in running application and this error is showing

### ISSUE THREAD

**Issue by NamanDubey03** [tensorflow/tensorflow#53472]
Traceback (most recent call last):
  File "E:\New folder\face_mask\facemask1\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\New folder\face_mask\app\app.py", line 7, in <module>
    from deeplearning import face_mask_prediction
  File "E:\New folder\face_mask\app\deeplearning.py", line 3, in <module>
    import tensorflow as tf
  File "E:\New folder\face_mask\facemask1\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "E:\New folder\face_mask\facemask1\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "E:\New folder\face_mask\facemask1\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 79, in <module>
    raise ImportError(
ImportError: Traceback (most recent call last):
  File "E:\New folder\face_mask\facemask1\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors for some common causes and solutions.
If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.

**Comment by tilakrayal** [comment]
@NamanDubey03 ,
Can you please take a look at this [comment](https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156) from the issue with similar error.It helps.Also in order to expedite the trouble-shooting process, could you please provide the following information
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
TensorFlow installed from (source or binary):
TensorFlow version:
Python version:
Installed using virtualenv? pip? conda?:
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory:

and the exact sequence of commands / steps that you executed before running into the problem.Thanks
