### ISSUE TITLE
Can All_gather of collective_ops be used in deep learning model building and reverse optimization of the model

### ISSUE THREAD

**Issue by upwindflys** [tensorflow/tensorflow#53517]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):YES
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux CentOS 7.6.1810
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):1.15.4
- Python version:3.6.8
- Bazel version (if compiling from source):None
- GCC/Compiler version (if compiling from source):None
- CUDA/cuDNN version:None
- GPU model and memory:None

**Describe the current behavior**
I want to implement a data exchange function between workers,So I use Send/Recv of collective_ops while building a model.But errors occured when computing gradients.
> No gradient defined for operation 'CollectiveGather_1' (op type: CollectiveGather)

**Describe the expected behavior**
Normal training.

**Code to reproduce the issue**
``` python
 import tensorflow as tf
 from tensorflow.python.ops import collective_ops
 FLAGS = tf.app.flags.FLAGS
 worker_replicas=2
 def shuffle(tensor):
    batch_size = tf.shape(tensor)[0]
    rank = FLAGS.task_index
    with tf.device('/cpu:0'):
        all_idx = tf.range(worker_replicas * batch_size)
        shuffle_idx = tf.random.shuffle(all_idx)
        if FLAGS.task_index == 0:
            index_broadcast = collective_ops.broadcast_send(shuffle_idx, shape=shuffle_idx.shape,
                                                            dtype=shuffle_idx.dtype,
                                                            group_size=worker_replicas, group_key=3, instance_key=100)
        else:
            index_broadcast = collective_ops.broadcast_recv(shape=shuffle_idx.shape, dtype=shuffle_idx.dtype,
                                                            group_size=worker_replicas, group_key=3, instance_key=100)
        my_idxs = tf.slice(index_broadcast, [rank * batch_size], [batch_size])
        all_tensor = collective_ops.all_gather(
            tensor, worker_replicas, worker_replicas, worker_replicas)

    return tf.gather(all_tensor, my_idxs), shuffle_idx


```

**Other info / logs**
I insert the code snippet while model building,it shuffles tensors between workers,but the log as follows.
```
File "/home/shangyw/git_rep/test_model/deploy/model_deploy.py", line 435, in _optimize_clone
    clone_grad = optimizer.compute_gradients(sum_loss, **kwargs)
  File "/home/shangyw/virtualenv/p3_tf115/lib/python3.6/site-packages/tensorflow_core/python/training/optimizer.py", line 512, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/home/shangyw/virtualenv/p3_tf115/lib/python3.6/site-packages/tensorflow_core/python/ops/gradients_impl.py", line 158, in gradients
    unconnected_gradients)
  File "/home/shangyw/virtualenv/p3_tf115/lib/python3.6/site-packages/tensorflow_core/python/ops/gradients_util.py", line 637, in _GradientsHelper
    (op.name, op.type))
2021-12-22 11:04:07,317 - DEBUG - No gradient defined for operation 'CollectiveGather_1' (op type: CollectiveGather)
```

**Comment by tilakrayal** [comment]
@upwindflys ,
We see that you are using tf version 1.15, 1.x is not actively supported, please update to v2.7 and let us know if you are using same issue.

**Comment by upwindflys** [comment]
@tilakrayal Thank you for your reply.But there is no avaliable 2.7.x tf version, so I tried tf version 2.6,the same error occured.

```
(p3_tf2) root@147tf$ pip install tensorflow-gpu==2.7
ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==2.7 (from versions: 0.12.1, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.9.0, 1.10.0, 1.10.1, 1.11.0, 1.12.0, 1.12.2, 1.12.3, 1.13.1, 1.13.2, 1.14.0, 1.15.0, 1.15.2, 1.15.3, 1.15.4, 1.15.5, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.5.0, 2.5.1, 2.5.2, 2.6.0, 2.6.1, 2.6.2)
ERROR: No matching distribution found for tensorflow-gpu==2.7
```
```
Traceback (most recent call last):
  File "all_gather_gradient.py", line 98, in <module>
    start_process()
  File "all_gather_gradient.py", line 94, in start_process
    process_fn(worker_hosts,INDEX)
  File "all_gather_gradient.py", line 63, in process_fn
    grad = tf.gradients(loss,params)
  File "/home/shangyw/virtualenv/p3_tf2/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 172, in gradients
    unconnected_gradients)
  File "/home/shangyw/virtualenv/p3_tf2/lib/python3.6/site-packages/tensorflow/python/ops/gradients_util.py", line 636, in _GradientsHelper
    (op.name, op.type))
LookupError: No gradient defined for operation 'worker0/CollectiveGather' (op type: CollectiveGather)

```

**Comment by upwindflys** [comment]
@tilakrayal 
I tried the tf version 2.7.0 by using docker image tensorflow/tensorflow:2.7.0-gpu. But the same error occured.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/gradients_util.py", line 598, in _GradientsHelper
    grad_fn = ops.get_gradient_function(op)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py", line 2788, in get_gradient_function
    return gradient_registry.lookup(op_type)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/registry.py", line 99, in lookup
    raise LookupError(
LookupError: gradient registry has no entry for: CollectiveGather

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "all_gather_gradient.py", line 98, in <module>
    start_process()
  File "all_gather_gradient.py", line 94, in start_process
    process_fn(worker_hosts,INDEX)
  File "all_gather_gradient.py", line 63, in process_fn
    grad = tf.gradients(loss,params)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/gradients_impl.py", line 169, in gradients
    return gradients_util._GradientsHelper(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/gradients_util.py", line 626, in _GradientsHelper
    raise LookupError(
LookupError: No gradient defined for operation'worker0/CollectiveGather' (op type: CollectiveGather). In general every operation must have an associated `@tf.RegisterGradient` for correct autodiff, which this op is lacking. If you want to pretend this operation is a constant in your program, you may insert `tf.stop_gradient`. This can be useful to silence the error in cases where you know gradients are not needed, e.g. the forward pass of tf.custom_gradient. Please see more details in https://www.tensorflow.org/api_docs/python/tf/custom_gradient.

**Comment by tilakrayal** [comment]
@upwindflys ,
While trying to execute the given code i was facing different error.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/d1bfa5103ba3720b64632f01e97f9497/untitled154.ipynb) and provide the latest code to reproduce the issue.Thanks!

**Comment by upwindflys** [comment]
@tilakrayal Hi,
### Code to reproduce the issue.
```python
"""File all_gather.py"""

import numpy as np
import sys
NUM_PROCESSES = 2
NUM_TOWERS = 1

INDEX = int(sys.argv[1])
print ('Index: {}'.format(INDEX))
def process_fn(worker_hosts, task_index):
    """allgather process"""

    import time
    import tensorflow.compat.v1 as tf
    tf.disable_v2_behavior()
    from tensorflow.python.ops import collective_ops

    cluster_spec = tf.train.ClusterSpec({'worker': worker_hosts})

    # unconfigured collective_group_leader make each worker the leader
    # '/replica:0' is necessary in the configuration.
    config = tf.ConfigProto(device_count={'CPU': NUM_TOWERS})
    config.experimental.collective_group_leader = '/job:worker/replica:0/task:0'
    server = tf.train.Server(cluster_spec, config=config,
                             job_name='worker', task_index=task_index)
    with tf.Graph().as_default():
        # create weight
        all_weights = list()
        for worker_index in range(NUM_PROCESSES):
            worker_weights = list()
            with tf.variable_scope('worker{}'.format(worker_index)):
                for tower_index in range(NUM_TOWERS):
                    device = '/job:worker/replica:0/task:{}/device:CPU:{}'.format(
                        worker_index, tower_index)
                    with tf.device(device):
                        x_data = np.array([1,2])
                        y_data = x_data*0.1+0.3
                        weight = tf.get_variable(
                            'weight{}'.format(tower_index), shape=[1])
                        worker_weights.append(weight)
                        all_idx = tf.range(2)
                        shuffle_idx = tf.random.shuffle(all_idx)
                        if task_index == 0:
                            tensor = collective_ops.broadcast_send(shuffle_idx, shape=shuffle_idx.shape,
                                                                   dtype=shuffle_idx.dtype, group_size=NUM_PROCESSES,
                                                                   group_key=3, instance_key=100)
                        else:
                            tensor = collective_ops.broadcast_recv(shape=shuffle_idx.shape, dtype=shuffle_idx.dtype,
                                                                   group_size=NUM_PROCESSES, group_key=3,
                                                                   instance_key=100)
                        my_idxs = tf.slice(tensor, [INDEX * 1], [1])
                        inter_reduced = collective_ops.all_gather(
                            weight, NUM_PROCESSES, NUM_PROCESSES, NUM_PROCESSES)
                        dst = tf.gather(inter_reduced, my_idxs, axis=0)
                        biases = tf.Variable(tf.zeros([1]))
                        y = dst*x_data+biases
                        loss = tf.reduce_mean(tf.square(y-y_data
                                                        ))
                        params = [weight,biases]
                        grad = tf.gradients(loss,params)
                        grads_param = zip(grad,params)
                        optimizer = tf.train.GradientDescentOptimizer(0.01)
                        train_op = optimizer.apply_gradients(grads_param)

            all_weights.append(worker_weights)


        inter_reduced = None

        session_creator = tf.train.ChiefSessionCreator(
            master=server.target)
        with tf.train.MonitoredSession(session_creator=session_creator) \
                as mon_sess:
            result_all = mon_sess.run(all_weights)
            print('task {} sense {}'.format(task_index, result_all))
            result_inter,my_idxs_np,result_slice,_ = mon_sess.run([inter_reduced,my_idxs,dst,tensor])
            print('task {} \n inter_reduce {} \n my_idxs {} idx {} \n slice_tensor {}'.format(task_index, result_inter,my_idxs_np, _, result_slice))
            mon_sess.run(train_op)
            time.sleep(1)

def start_process():
    """start process"""
    port = 60000
    host_fmt = 'localhost:{}'
    worker_hosts = list()
    for process_index in range(NUM_PROCESSES):
        worker_hosts.append(host_fmt.format(port + process_index))
    process_fn(worker_hosts,INDEX)


if __name__ == '__main__':
    start_process()

```
### Command
`woker0: python all_gather.py 0   
worker1: python all_gather.py 1 `

**Comment by tilakrayal** [comment]
@upwindflys,
I was facing different error while trying to execute the code.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/19f7fa69150660ed4ce44b172120e4a4/untitled178.ipynb).

**Comment by upwindflys** [comment]
@tilakrayal I modified the code receiving external incoming variables.
### Code to reproduce the issue.
```python
"""Illustrate AllGather"""
import multiprocessing as mp

MP_METHOD = 'fork'  # 'fork' (UNIX), 'spawn' (WINDOWS);
import numpy as np
NUM_PROCESSES = 2
NUM_TOWERS = 1

def process_fn(worker_hosts, task_index):
    """allgather process"""

    import time
    import tensorflow.compat.v1 as tf
    tf.disable_v2_behavior()
    from tensorflow.python.ops import collective_ops

    cluster_spec = tf.train.ClusterSpec({'worker': worker_hosts})

    # unconfigured collective_group_leader make each worker the leader
    # '/replica:0' is necessary in the configuration.
    config = tf.ConfigProto(device_count={'CPU': NUM_TOWERS})
    config.experimental.collective_group_leader = '/job:worker/replica:0/task:0'
    server = tf.train.Server(cluster_spec, config=config,
                             job_name='worker', task_index=task_index)
    with tf.Graph().as_default():
        # create weight
        all_weights = list()
        # for worker_index in range(NUM_PROCESSES):
        worker_weights = list()
        with tf.variable_scope('worker{}'.format(task_index)):
            for tower_index in range(NUM_TOWERS):
                device = '/job:worker/replica:0/task:{}/device:CPU:{}'.format(
                    task_index, tower_index)
                with tf.device(device):
                    x_data = np.array([1,2])
                    y_data = x_data*0.1+0.3
                    weight = tf.get_variable(
                        'weight{}'.format(tower_index), shape=[1])


                    worker_weights.append(weight)
                    all_idx = tf.range(2)
                    shuffle_idx = tf.random.shuffle(all_idx)
                    if task_index == 0:
                        tensor = collective_ops.broadcast_send(shuffle_idx, shape=shuffle_idx.shape,
                                                               dtype=shuffle_idx.dtype, group_size=NUM_PROCESSES,
                                                               group_key=3, instance_key=100)
                    else:
                        tensor = collective_ops.broadcast_recv(shape=shuffle_idx.shape, dtype=shuffle_idx.dtype,
                                                               group_size=NUM_PROCESSES, group_key=3,
                                                               instance_key=100)
                    my_idxs = tf.slice(tensor, [task_index * 1], [1])
                    inter_reduced = collective_ops.all_gather(
                        weight, NUM_PROCESSES, NUM_PROCESSES, NUM_PROCESSES)
                    dst = tf.gather(inter_reduced, my_idxs, axis=0)

                    biases = tf.Variable(tf.zeros([1]))
                    y = dst*x_data+biases
                    # y = weight * x_data + biases
                    loss = tf.reduce_mean(tf.square(y-y_data
                                                    ))
                    params = [weight,biases]
                    grad = tf.gradients(loss,params)
                    grads_param = zip(grad,params)
                    optimizer = tf.train.GradientDescentOptimizer(0.01)
                    train_op = optimizer.apply_gradients(grads_param)


        all_weights = worker_weights
        inter_reduced = None

        session_creator = tf.train.ChiefSessionCreator(
            master=server.target)
        with tf.train.MonitoredSession(session_creator=session_creator) \
                as mon_sess:
            result_all = mon_sess.run(all_weights)
            print('task {} sense {}'.format(task_index, result_all))
            result_inter,my_idxs_np,result_slice,_ = mon_sess.run([inter_reduced,my_idxs,dst,tensor])
            print('task {} \n inter_reduce {} \n my_idxs {} idx {} \n slice_tensor {}'.format(task_index, result_inter,my_idxs_np, _, result_slice))
            mon_sess.run(train_op)
            time.sleep(1)

def start_process():
    """start process"""

    port = 60000
    host_fmt = 'localhost:{}'
    worker_hosts = list()
    for process_index in range(NUM_PROCESSES):
        worker_hosts.append(host_fmt.format(port + process_index))
    mp_ctx = mp.get_context(MP_METHOD)
    processes = list()
    for process_index in range(NUM_PROCESSES):
        process = mp_ctx.Process(target=process_fn,
                                 args=(worker_hosts, process_index,))
        processes.append(process)
        process.start()
    for process in processes:
        process.join()



if __name__ == '__main__':
    start_process()




```

**Comment by tilakrayal** [comment]
@sachinprasadhs ,
I was able to reproduce the issue in tf v2.5, v2.7 and nightly.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/d9d6490bb0f5ac3c9ac51bb31d0c3f65/untitled181.ipynb).

**Comment by sachinprasadhs** [comment]
I could not find the source for `collective_ops` which is registered under gradient function(`@ops.RegisterGradient`).
Meanwhile you can check [this](https://www.tensorflow.org/guide/create_op#implement_the_gradient_in_python) to implement the gradient in python for the custom ops.

**Comment by kaizhigaosu** [comment]
I have the same problem. Could you please solve this problem? You don't provide gradient functions for these collective_ops operations, which makes TensorFlow looks like a work-in-progress. A lot of my friends have switched to Pytorch and it looks like I have to do the same.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
