### ISSUE TITLE
TRT Converter not working in 2.7.0 version of official Image

### ISSUE THREAD

**Issue by BorisPolonsky** [tensorflow/tensorflow#53529]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): docker image `tensorflow/tensorflow:2.7.0-gpu`
- TensorFlow version (use command below): v2.7.0-rc1-69-gc256c071bb2 2.7.0
- Python version: Python 3.8.10
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: Nvidia GeForce 1050

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I tried to optimize a Tensorflow SavedModel using trt_converter. It works in official `tensorflow/tensorflow:2.3.0-gpu` yet fails in `tensorflow/tensorflow:2.7.0-gpu`
**Describe the expected behavior**

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```

input_saved_model_dir = "directory/of/tensorflow/saved_model"
output_saved_model_dir = "tensorrt-test"
converter = trt.TrtGraphConverterV2(input_saved_model_dir=input_saved_model_dir)
trt_graph = converter.convert()
converter.save(output_saved_model_dir);print("====saved====")
```
v2.7.0-rc1-69-gc256c071bb2 2.7.0
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
```
2021-12-23 09:10:04.726658: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such fil
e or directory; LD_LIBRARY_PATH: /usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2021-12-23 09:10:04.726892: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object fil
e: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2021-12-23 09:10:04.726909: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:35] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the 
missing libraries mentioned above are installed properly.
ERROR:tensorflow:Tensorflow needs to be built with TensorRT support enabled to allow TF-TRT to operate.
Traceback (most recent call last):
  File "trt.py", line 10, in <module>
    converter = trt.TrtGraphConverterV2(input_saved_model_dir=input_saved_model_dir)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/compiler/tensorrt/trt_convert.py", line 1009, in __init__
    _check_trt_version_compatibility()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/compiler/tensorrt/trt_convert.py", line 221, in _check_trt_version_compatibility
    raise RuntimeError("Tensorflow has not been built with TensorRT support.")
RuntimeError: Tensorflow has not been built with TensorRT support.
```

**Comment by mohantym** [comment]
Hi @BorisPolonsky ! Have you checked these threads yet for TensorRT installation in your environment yet? . Ref [1](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html) ,[2 ](https://github.com/prratadiya/tensorrt-installation-colab),[ 3](https://www.code-helper.com/answers/install-tensorrt-on-colab) . Thank you!

**Comment by BorisPolonsky** [comment]
> Hi @BorisPolonsky ! Have you checked these threads yet for TensorRT installation in your environment yet? . Ref [1](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html) ,[2 ](https://github.com/prratadiya/tensorrt-installation-colab),[ 3](https://www.code-helper.com/answers/install-tensorrt-on-colab) . Thank you!

I've checked the "verify your installation" part in ref [1](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html). Here's what I got in `tensorflow/tensorflow:2.7.0-gpu`:
```
dpkg -l | grep TensorRT
ii  libnvinfer-plugin8            8.0.0-1+cuda11.0                  amd64        TensorRT plugin libraries
ii  libnvinfer8                   8.0.0-1+cuda11.0                  amd64        TensorRT runtime libraries
```
As comparison, here's what I got in `tensorflow/tensorflow:2.4.0-gpu`, a version wheere `trt.TrtGraphConverterV2` works out of box:
```
dpkg -l | grep TensorRT
ii  libnvinfer-plugin7           7.1.3-1+cuda11.0                    amd64        TensorRT plugin libraries
ii  libnvinfer7                  7.1.3-1+cuda11.0                    amd64        TensorRT runtime libraries
```
I don't see any problem with TensorRT installation here. Maybe there's something wrong with `_check_trt_version_compatibility` in tf2.7?

**Comment by mohantym** [comment]
Hi @Saduf2019! Could you please look at this issue?

**Comment by Saduf2019** [comment]
@BorisPolonsky 
Is this failing on 2.6 as well for you?

**Comment by BorisPolonsky** [comment]
> @BorisPolonsky Is this failing on 2.6 as well for you?

It's not working on tf 2.6 either. The conversion process end up with `Aborted (core dumped)` message in `tensorflow/tensorflow:2.6.0-gpu`.
```
2021-12-30 23:19:23.161255: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvrtc.so.11.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2021-12-30 23:19:23.161278: F tensorflow/compiler/tf2tensorrt/stub/nvinfer_stub.cc:49] getInferLibVersion symbol not found.
Aborted (core dumped)
```
Here's TensorRT installation verification step done in the container.
```
ii  libnvinfer-plugin7           7.2.2-1+cuda11.1                    amd64        TensorRT plugin libraries
ii  libnvinfer7                  7.2.2-1+cuda11.1                    amd64        TensorRT runtime libraries
```

**Comment by apivovarov** [comment]
Boris, Tensorflow 2.7.0 (from pypi) was built with TensorRT 7 (not 8) - it needs `libnvinfer.so.7` and `libnvinfer_plugin.so.7` but you have `libnvinfer8` installed.

To test that Tensorflow can find TensorRT libraries you can do the following:
```
import tensorflow as tf
import tensorflow.compiler as tf_cc
tf_cc.tf2tensorrt._pywrap_py_utils.is_tensorrt_enabled()
```
if you do not have libnvinfer.so.7 and libnvinfer_plugin.so.7 then it will output
```
>>> cc.tf2tensorrt._pywrap_py_utils.is_tensorrt_enabled()
2022-01-06 05:37:08.526925: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2022-01-06 05:37:08.527000: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2022-01-06 05:37:08.527013: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:35] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
False
```

So, either install TRT 7.x or build TF with TRT 8.x support from source.

How to build TF with TRT support from source is described here https://apivovarov.medium.com/run-tensorflow-2-object-detection-models-with-tensorrt-on-jetson-xavier-using-tf-c-api-e34548818ac6

**Comment by BorisPolonsky** [comment]
> Boris, Tensorflow 2.7.0 (from [pypi](https://pypi.org/project/tensorflow/)) was built with TensorRT 7.2.2 (not 8.x) - it needs `libnvinfer.so.7` and `libnvinfer_plugin.so.7` but you have `libnvinfer8` installed.
> 
> TensorRT does not support forward compatibility
> 
> To test that Tensorflow can find TensorRT libraries you can do the following:
> 
> ```
> import tensorflow as tf
> import tensorflow.compiler as tf_cc
> tf_cc.tf2tensorrt._pywrap_py_utils.is_tensorrt_enabled()
> 
> print("loaded trt ver:", tf_cc.tf2tensorrt._pywrap_py_utils.get_loaded_tensorrt_version())
> print("linked trt ver:", tf_cc.tf2tensorrt._pywrap_py_utils.get_linked_tensorrt_version())
> ```
> 
> if you do not have `libnvinfer.so.7` and `libnvinfer_plugin.so.7` then it will output
> 
> ```
> >>> cc.tf2tensorrt._pywrap_py_utils.is_tensorrt_enabled()
> 2022-01-06 05:37:08.526925: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
> 2022-01-06 05:37:08.527000: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
> 2022-01-06 05:37:08.527013: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:35] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
> False
> ```
> 
> So, either install TRT 7.2.2 (or 7.2.3) or build TF with TRT 8.x support from source.
> 
> How to build TF with TRT support from source is described here https://apivovarov.medium.com/run-tensorflow-2-object-detection-models-with-tensorrt-on-jetson-xavier-using-tf-c-api-e34548818ac6

Thanks for clarifying. Looks like the official image of tf2.7 switched to a base image with TRT 8.x installed. Will the next official docker image release ensure compatibility between tensorflow and TRT so that this feature works out of box?

**Comment by apivovarov** [comment]
Setup tensorflow/tensorflow:2.7.0-gpu container
```
$ sudo docker run -it --name tf270 --gpus all tensorflow/tensorflow:2.7.0-gpu
```
Test TF/TRT
```
$ apt list --installed | grep infer

libnvinfer-plugin8/unknown,now 8.0.0-1+cuda11.0 amd64 [installed,upgradable to: 8.2.0-1+cuda11.4]
libnvinfer8/unknown,now 8.0.0-1+cuda11.0 amd64 [installed,upgradable to: 8.2.0-1+cuda11.4]


import tensorflow as tf
import tensorflow.compiler as tf_cc
tf_cc.tf2tensorrt._pywrap_py_utils.get_linked_tensorrt_version()

(7, 2, 2)
```
ok, installed TRT is 8.0.0 but Tensorflow was built and linked with TRT 7.2.2. Looks like nobody tested TensorRT with tensorflow/tensorflow:2.7.0-gpu image

BTW, tensorflow/tensorflow:2.6.1-gpu container works fine. (Cuda 11.2, TRT 7.2.2, TF 2.6.1)

**Comment by apivovarov** [comment]
To run TF 2.7.0 with TRT-7.2.3 we can use TF 2.6.1-gpu image
```
sudo docker run -it --name tf270 --gpus all tensorflow/tensorflow:2.6.1-gpu
apt update
apt upgrade

python3 -m pip install -U pip
python3 -m pip install -U tensorflow==2.7.0

apt install vim
vi /usr/local/lib/python3.8/dist-packages/tensorflow/python/compiler/tensorrt/trt_convert.py
# go to line 266 and replace `trt_utils.versionTupleToString(loaded_version)` with just `loaded_version`. Do the same for `linked_version` on line 267

export LD_LIBRARY_PATH=/usr/local/cuda-11.1/targets/x86_64-linux/lib
python3
```
Test Tensorflow/TRT
```
import tensorflow as tf
tf.test.is_gpu_available()
import tensorflow.compiler as tf_cc
tf_cc.tf2tensorrt._pywrap_py_utils.is_tensorrt_enabled()

from tensorflow.python.compiler.tensorrt import trt_convert as trt
conversion_params = trt.TrtConversionParams(precision_mode=trt.TrtPrecisionMode.FP16)

converter = trt.TrtGraphConverterV2(
    input_saved_model_dir="saved_model",
    conversion_params=conversion_params)

converter.convert()
```

**Comment by sayakpaul** [comment]
@apivovarov @BorisPolonsky any workaround for working this out on Google Colab or Kaggle Kernels? This [official Keras example](https://keras.io/examples/vision/near_dup_search/) is failing because of this.

**Comment by BorisPolonsky** [comment]
> @apivovarov @BorisPolonsky any workaround for working this out on Google Colab or Kaggle Kernels? This [official Keras example](https://keras.io/examples/vision/near_dup_search/) is failing because of this.

I use `tensorflow 2.4.0` for this purpose for now.

**Comment by sayakpaul** [comment]
I see. Do you use it on Colab?

**Comment by sayakpaul** [comment]
Yeah as I mentioned in the comment, yes.

**Comment by apivovarov** [comment]
The workaround which I mentioned above was to

**Comment by sayakpaul** [comment]
But won't be possible on Colab and Kaggle I guess.

**Comment by apivovarov** [comment]
Do you have a link to a sample Colab?

**Comment by sayakpaul** [comment]
Yeah, that is what. I was asking if there's a workaround for that.

**Comment by apivovarov** [comment]
[This Colab notebook](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb) does not have GPU at all.
```
import tensorflow as tf
print("TensorFlow version:", tf.__version__)
tf.test.is_gpu_available()
```
```
TensorFlow version: 2.7.0
False
```

**Comment by sayakpaul** [comment]
Seems like there isn't a workaround for this yet? 

I did have success with the earlier versions of TensorFlow installed on Colab.

**Comment by apacha** [comment]
> Boris, Tensorflow 2.7.0 (from [pypi](https://pypi.org/project/tensorflow/)) was built with TensorRT 7.2.2 (not 8.x) - it needs `libnvinfer.so.7` and `libnvinfer_plugin.so.7` but you have `libnvinfer8` installed.

@BorisPolonsky can you proof this, please, or tell me what I'm doing wrong? I've tried to install several versions of tensorflow from pip and **NONE** of them was built with TensorRT support. One of the wheels that I've tried is `tensorflow-2.9.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl`.

**Comment by BorisPolonsky** [comment]
> > Boris, Tensorflow 2.7.0 (from [pypi](https://pypi.org/project/tensorflow/)) was built with TensorRT 7.2.2 (not 8.x) - it needs `libnvinfer.so.7` and `libnvinfer_plugin.so.7` but you have `libnvinfer8` installed.
> 
> @BorisPolonsky can you proof this, please, or tell me what I'm doing wrong? I've tried to install several versions of tensorflow from pip and **NONE** of them was built with TensorRT support. One of the wheels that I've tried is `tensorflow-2.9.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl`.
> 
> I'm always getting
> 
> ```
> File "/home/trtuser/.local/lib/python3.8/site-packages/tensorflow/python/compiler/tensorrt/trt_convert.py", line 214, in _check_trt_version_compatibility
>     raise RuntimeError("Tensorflow has not been built with TensorRT support.")
> ```

I suggest that you should use docker and run officially built and released tensorflow (or the NVIDIA versions from NGC) images.  Manually installing ML framework with GPU support from scratch will be tedious.

**Comment by elvinagam** [comment]
This one seems to be still causing headaches...

**Comment by SuryanarayanaY** [comment]
@BorisPolonsky ,

I have tested the code mentioned in [comment](https://github.com/tensorflow/tensorflow/issues/53529#issuecomment-1035409270) and now I can see with TF2.11v, TF2.12V and tf-nightly versions are built with TF TRT versions 7.2.2, 8.4.3 and 8.4.3 versions respectively. Please refer to attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/22ec2f74eea1cfbd30c15c71d91e4c07/53529.ipynb).The same might be installed in docker images also.

It seems the issue resolved. Please check and come back if the issue still persists. Thanks!

**Comment by BorisPolonsky** [comment]
> @BorisPolonsky ,
> 
> I have tested the code mentioned in [comment](https://github.com/tensorflow/tensorflow/issues/53529#issuecomment-1035409270) and now I can see with TF2.11v, TF2.12V and tf-nightly versions are built with TF TRT versions 7.2.2, 8.4.3 and 8.4.3 versions respectively. Please refer to attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/22ec2f74eea1cfbd30c15c71d91e4c07/53529.ipynb).The same might be installed in docker images also.
> 
> It seems the issue resolved. Please check and come back if the issue still persists. Thanks!

I will close this issue. Please enforce TensorRT version verification when releasing official images in the futures.
