### ISSUE TITLE
Building with Bazel failed during fetching of repository "go sdk"

### ISSUE THREAD

**Issue by rangsimanketkaew** [tensorflow/tensorflow#53629]
Happy New Year 2022!

I've been trying to build TF 2.6 from source using Bazel on my Ubuntu machine. Unfortunately, I got stuck at the very beginning step of installing dependencies for TF. The error says that bazel failed to fetch (and also extract?) GO SDK package (see log below). My system details and building commands are also provided.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 21.04 // 16 cores AMD Ryzen 7 1700 processors with 16 GB of RAM.
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.6
- Python version: 3.9.9
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 10.3
- CUDA/cuDNN version: no
- GPU model and memory: no

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

I had cloned TF from my repo forked from the official TF repo, checkouted `r2.6`, and then configured the build (`./configure`) and left answers empty (answered No to all questions).

```
bazel build --jobs=8 --local_ram_resources="HOST_RAM*.50" \
  --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" -c opt \
  --config=noaws --config=nogcp --config=nohdfs --config=nonccl --config=v2 \
  //tensorflow:libtensorflow.so \
  //tensorflow:libtensorflow_cc.so  \
  //tensorflow:libtensorflow_framework.so  \
  //tensorflow:install_headers
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
WARNING: Output base '/home/rketka/.cache/bazel/_bazel_rketka/6f5ef4905e7610b7a736fc4fcd0da30a' is on NFS. This may lead to surprising failures and undetermined behavior.
WARNING: The following configs were expanded more than once: [v2]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=83
INFO: Reading rc options for 'build' from /home/rketka/github/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/rketka/github/tensorflow/.bazelrc:
  'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true
INFO: Reading rc options for 'build' from /home/rketka/github/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/home/rketka/miniconda3/envs/tfcc/bin/python3 --action_env PYTHON_LIB_PATH=/home/rketka/miniconda3/envs/tfcc/lib/python3.9/site-packages --python_path=/home/rketka/miniconda3/envs/tfcc/bin/python3
INFO: Found applicable config definition build:short_logs in file /home/rketka/github/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/rketka/github/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:noaws in file /home/rketka/github/tensorflow/.bazelrc: --define=no_aws_support=true
INFO: Found applicable config definition build:nogcp in file /home/rketka/github/tensorflow/.bazelrc: --define=no_gcp_support=true
INFO: Found applicable config definition build:nohdfs in file /home/rketka/github/tensorflow/.bazelrc: --define=no_hdfs_support=true
INFO: Found applicable config definition build:nonccl in file /home/rketka/github/tensorflow/.bazelrc: --define=no_nccl_support=true
INFO: Found applicable config definition build:v2 in file /home/rketka/github/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:linux in file /home/rketka/github/tensorflow/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels --distinct_host_configuration=false
INFO: Found applicable config definition build:dynamic_kernels in file /home/rketka/github/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
WARNING: Download from http://mirror.tensorflow.org/github.com/tensorflow/runtime/archive/b570a1921c9e55ac53c8972bd2bfd37cd0eb510d.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
DEBUG: /home/rketka/.cache/bazel/_bazel_rketka/6f5ef4905e7610b7a736fc4fcd0da30a/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
DEBUG: Repository io_bazel_rules_docker instantiated at:
  /home/rketka/github/tensorflow/WORKSPACE:23:14: in <toplevel>
  /home/rketka/github/tensorflow/tensorflow/workspace0.bzl:108:34: in workspace
  /home/rketka/.cache/bazel/_bazel_rketka/6f5ef4905e7610b7a736fc4fcd0da30a/external/bazel_toolchains/repositories/repositories.bzl:37:23: in repositories
Repository rule git_repository defined at:
  /home/rketka/.cache/bazel/_bazel_rketka/6f5ef4905e7610b7a736fc4fcd0da30a/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
INFO: Repository go_sdk instantiated at:
  /home/rketka/github/tensorflow/WORKSPACE:23:14: in <toplevel>
  /home/rketka/github/tensorflow/tensorflow/workspace0.bzl:120:20: in workspace
  /home/rketka/.cache/bazel/_bazel_rketka/6f5ef4905e7610b7a736fc4fcd0da30a/external/com_github_grpc_grpc/bazel/grpc_extra_deps.bzl:36:27: in grpc_extra_deps
  /home/rketka/.cache/bazel/_bazel_rketka/6f5ef4905e7610b7a736fc4fcd0da30a/external/io_bazel_rules_go/go/toolchain/toolchains.bzl:379:28: in go_register_toolchains
  /home/rketka/.cache/bazel/_bazel_rketka/6f5ef4905e7610b7a736fc4fcd0da30a/external/io_bazel_rules_go/go/private/sdk.bzl:65:21: in go_download_sdk
Repository rule _go_download_sdk defined at:
  /home/rketka/.cache/bazel/_bazel_rketka/6f5ef4905e7610b7a736fc4fcd0da30a/external/io_bazel_rules_go/go/private/sdk.bzl:53:35: in <toplevel>
ERROR: An error occurred during the fetch of repository 'go_sdk':
   Traceback (most recent call last):
	File "/home/rketka/.cache/bazel/_bazel_rketka/6f5ef4905e7610b7a736fc4fcd0da30a/external/io_bazel_rules_go/go/private/sdk.bzl", line 51, column 16, in _go_download_sdk_impl
		_remote_sdk(ctx, [url.format(filename) for url in ctx.attr.urls], ctx.attr.strip_prefix, sha256)
	File "/home/rketka/.cache/bazel/_bazel_rketka/6f5ef4905e7610b7a736fc4fcd0da30a/external/io_bazel_rules_go/go/private/sdk.bzl", line 128, column 17, in _remote_sdk
		fail("error extracting Go SDK:\n" + res.stdout + res.stderr)
Error in fail: error extracting Go SDK:
Timed out
ERROR: Analysis of target '//tensorflow:libtensorflow_framework.so' failed; build aborted: error extracting Go SDK:
Timed out
INFO: Elapsed time: 1891.172s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (23 packages loaded, 32 targets configured)
```

Any ideas to tackle this issue? Hope that the info above is sufficient, but let me know if you need further info for investigation. 

Thank you very much.
Rangsiman

**Comment by sushreebarsa** [comment]
@rangsimanketkaew Could you please let us know if this issue still persists in  latest stable TF v2.7.0 ? Thanks!

**Comment by rangsimanketkaew** [comment]
> @rangsimanketkaew Could you please let us know if this issue still persists in latest stable TF v2.7.0 ? Thanks!

Yes, I also faced the same issue in v2.7.

**Comment by rangsimanketkaew** [comment]
@sushreebarsa

> @rangsimanketkaew Could you please let us know if this issue still persists in latest stable TF v2.7.0 ? Thanks!

Yes, I also faced the same issue in v2.7.

**Comment by mohantym** [comment]
Hi @rangsimanketkaew ! This issue is not replicating with 2.9 and Bazel 5.00 (Ubuntu 18)  . Attaching [gist ](https://colab.sandbox.google.com/gist/mohantym/21d8789137a393a6a3018090ab4f16d5/tensorflow-ranking.ipynb#scrollTo=_IQp1_gflTaC)for reference. Thank you!
