### ISSUE TITLE
tf.keras k-fold save weights failed! RuntimeError: Can't decrement id ref count (unable to close file, errno = 5, error message = 'Input/output error')

### ISSUE THREAD

**Issue by mechsihao** [tensorflow/tensorflow#53634]
# Background:
I want to train a two-dense-layer classification model, I use the k-fold strategy to train it and use tf.keras.callback.checkpoint utils to save the best model weights:

`RuntimeError: Can't decrement id ref count (unable to close file, errno = 5, error message = 'Input/output error')`

I tried to change the version of h5py to fix this bug, but it did not work.(2.10.0 ~ 3.6.0).
This bug will be occured `randomly`, it seems like bugs more frequently when training cost time shorter，It seems like when training a k-fold model, the model will be saveing parallel, then this bug will be occurred.

# when I track to source code of keras, the save_weights function is just like that:
```python
def save_weights(self, filepath, overwrite=True):
    ...
    with h5py.File(filepath, 'w') as f:
        saving.save_weights_to_hdf5_group(f, self.layers)
        f.flush()
saving.save_weights_to_hdf5_group means save weights into the HDF5 group
```
# This bug can be repeated by those codes:
```python
import tensorflow as tf
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ModelCheckpoint
from sklearn.model_selection import KFold
import numpy as np

input_dim = 256
input_x = Input(input_dim,)
x = Dense(128, activation='relu')(input_x)
p = Dense(2, activation='sigmoid')(x)
model = Model(inputs=input_x, outputs=p)

model.compile(loss='mse', optimizer=Adam(1e-5), metrics = ['acc'])

sample_num = 2000
train, label = np.random.random((sample_num, input_dim)), np.random.random((sample_num, 2))
kfold = KFold(n_splits=5)
for i, (train_ind, valid_ind) in enumerate(kfold.split(list(range(sample_num)))):
    model_path = f'model-{i}.h5'
    ckpt = ModelCheckpoint(model_path, monitor='val_loss')
    model.fit([train[train_ind], label[train_ind]], label[train_ind], validation_data=[train[valid_ind], label[valid_ind]], epochs=10, batch_size=64, callbacks=[ckpt])
```
# More detailed bug information is:
```python
Traceback (most recent call last):
  File "/home/notebook/code/personal/test_sihao/gitcode/oCTS_lsh/train_tf2.py", line 36, in <module>
    current_train_pickle_path, n_fold=5, monitor='val_categorical_crossentropy')
  File "/home/notebook/data/group/sihao_work/gitcode/oCTS_lsh/classifier/b4k_classifier_tf2.py", line 186, in model_train_kfold
    self.train(model, train_D, valid_D, tmp_model_save_path, monitor=monitor)
  File "/home/notebook/data/group/sihao_work/gitcode/oCTS_lsh/classifier/b4k_classifier_tf2.py", line 159, in train
    callbacks=[early_stopping, plateau, checkpoint])
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1433, in fit_generator
    steps_name='steps_per_epoch')
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_generator.py", line 331, in model_iteration
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 311, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 969, in on_epoch_end
    self._save_model(epoch=epoch, logs=logs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 998, in _save_model
    self.model.save_weights(filepath, overwrite=True)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/network.py", line 1315, in save_weights
    self._ckpt_saved_epoch).encode('utf8')
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/opt/conda/lib/python3.7/site-packages/h5py/_hl/files.py", line 544, in __exit__
    self.close()
  File "/opt/conda/lib/python3.7/site-packages/h5py/_hl/files.py", line 526, in close
    self.id._close_open_objects(h5f.OBJ_LOCAL | h5f.OBJ_FILE)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 358, in h5py.h5f.FileID._close_open_objects
RuntimeError: Can't decrement id ref count (unable to close file, errno = 5, error message = 'Input/output error')
Segmentation fault
```

**Comment by mohantym** [comment]
Hi @mechsihao ! I was  getting different error in 2.7 and able to resolve this issue  by removing square bracket from input data, Attaching [Gist ](https://colab.sandbox.google.com/drive/1DkAch7lv_z7FZGPFwzpFxlu-ysvY9xqD?resourcekey=0-24MDgWD3WxJW9MtsdA1xYA#scrollTo=ymx1-FOnoeZN)for reference. Thanks!

**Comment by mechsihao** [comment]
> 

thanks for your reply, but I don't have permission to visit your link, could you please paste your core code here? thanks again~

**Comment by mohantym** [comment]
Sorry ! I have updated the above[ Gist](https://colab.sandbox.google.com/gist/mohantym/bd6018e0f034de475be01c3414470e73/github_53634.ipynb#scrollTo=sDltZUhPofRp) link . Thanks!

**Comment by mechsihao** [comment]
> Sorry ! I have updated the above[ Gist](https://colab.sandbox.google.com/gist/mohantym/bd6018e0f034de475be01c3414470e73/github_53634.ipynb#scrollTo=sDltZUhPofRp) link . Thanks!

Thanks~!

**Comment by mechsihao** [comment]
> Sorry ! I have updated the above[ Gist](https://colab.sandbox.google.com/gist/mohantym/bd6018e0f034de475be01c3414470e73/github_53634.ipynb#scrollTo=sDltZUhPofRp) link . Thanks!

It seems not repeat this bug, I am testing it by updatding tf version to 2.7.0

**Comment by mechsihao** [comment]
> Sorry ! I have updated the above[ Gist](https://colab.sandbox.google.com/gist/mohantym/bd6018e0f034de475be01c3414470e73/github_53634.ipynb#scrollTo=sDltZUhPofRp) link . Thanks!

it really odd, this bug cannot be repeated in the collab, but it can be easily repeated in my local ubuntu when I use the same version TensorFlow even same version of Ubuntu

bugs detail:
```python
import tensorflow as tf
print(tf.__version__)
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ModelCheckpoint
from sklearn.model_selection import KFold
import numpy as np

input_dim = 256
input_x = Input(input_dim,)
x = Dense(128, activation='relu')(input_x)
p = Dense(2, activation='sigmoid')(x)
model = Model(inputs=input_x, outputs=p)

model.compile(loss='mse', optimizer=Adam(1e-5), metrics = ['acc'])

sample_num = 2000
train, label = np.random.random((sample_num, input_dim)), np.random.random((sample_num, 2))
kfold = KFold(n_splits=5)
for i, (train_ind, valid_ind) in enumerate(kfold.split(list(range(sample_num)))):
    model_path = f'model_{i}.h5'
    ckpt = ModelCheckpoint(model_path, monitor='val_loss')
    model.fit(train[train_ind], label[train_ind], validation_data=[train[valid_ind], label[valid_ind]], epochs=10, batch_size=64, callbacks=[ckpt])
```

[output]
```python 
2.7.0
Epoch 1/10
25/25 [==============================] - 1s 9ms/step - loss: 0.0925 - acc: 0.5031 - val_loss: 0.0940 - val_acc: 0.4800
Epoch 2/10
25/25 [==============================] - 0s 4ms/step - loss: 0.0899 - acc: 0.5044 - val_loss: 0.0920 - val_acc: 0.4875
Epoch 3/10
25/25 [==============================] - 0s 5ms/step - loss: 0.0888 - acc: 0.5063 - val_loss: 0.0914 - val_acc: 0.5000
Epoch 4/10
25/25 [==============================] - 0s 4ms/step - loss: 0.0884 - acc: 0.5088 - val_loss: 0.0911 - val_acc: 0.5050
Epoch 5/10
25/25 [==============================] - 0s 6ms/step - loss: 0.0883 - acc: 0.5088 - val_loss: 0.0910 - val_acc: 0.5125
Epoch 6/10
25/25 [==============================] - 0s 5ms/step - loss: 0.0882 - acc: 0.5056 - val_loss: 0.0909 - val_acc: 0.5225
Epoch 7/10
 1/25 [>.............................] - ETA: 0s - loss: 0.0884 - acc: 0.4844
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-4a6bc3ee19e9> in <module>
     22     model_path = f'model_{i}.h5'
     23     ckpt = ModelCheckpoint(model_path, monitor='val_loss')
---> 24     model.fit(train[train_ind], label[train_ind], validation_data=[train[valid_ind], label[valid_ind]], epochs=10, batch_size=64, callbacks=[ckpt])

/opt/conda/lib/python3.7/site-packages/keras/utils/traceback_utils.py in error_handler(*args, **kwargs)
     65     except Exception as e:  # pylint: disable=broad-except
     66       filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67       raise e.with_traceback(filtered_tb) from None
     68     finally:
     69       del filtered_tb

/opt/conda/lib/python3.7/site-packages/h5py/_hl/files.py in close(self)
    441                 for id_ in file_list:
    442                     while id_.valid:
--> 443                         h5i.dec_ref(id_)
    444 
    445                 self.id.close()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5i.pyx in h5py.h5i.dec_ref()

RuntimeError: Can't decrement id ref count (unable to close file, errno = 5, error message = 'Input/output error')
```

**Comment by mohantym** [comment]
Hi @mechsihao ! I think it might be due to environment configuration or installation. Can you please update the [template](https://github.com/tensorflow/tensorflow/issues/new/choose) which will help investigate this issue further? Thank you!
