### ISSUE TITLE
Failed build: Problem getting numpy include path.

### ISSUE THREAD

**Issue by Miko2x** [tensorflow/tensorflow#53640]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Monterey 12.1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.6.2(latest - cloned yesterday)
- Python version: 3.7.2
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 4.2.2
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
I wan to build GPU Metal Delegate and get the error `Problem getting numpy include path.`. I'm pretty sure I have numpy installed for python3 and python2.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I've tried to fix the problem with this [suggestion](https://github.com/tensorflow/tensorflow/issues/53467#issuecomment-996688168), but still get the same output. Running on this command:
`bazel build --action_env PYTHON_BIN_PATH=/usr/bin/python3 --verbose_failures --config=ios_arm64 -c opt //tensorflow/lite/ios:TensorFlowLiteCMetal_framework`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**NumPy logs on python3 and python2**
```
adityadwipamungkas@Adityas-MacBook-Pro tensorflow-2.6.2 % pip3 show numpy
Name: numpy
Version: 1.21.5
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: /usr/local/lib/python3.7/site-packages
Requires: 
Required-by: 
adityadwipamungkas@Adityas-MacBook-Pro tensorflow-2.6.2 % pip show numpy
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Name: numpy
Version: 1.16.6
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: /Users/adityadwipamungkas/Library/Python/2.7/lib/python/site-packages
Requires: 
Required-by: matplotlib
```

**Configure**
```
adityadwipamungkas@Adityas-MacBook-Pro tensorflow-2.6.2 % ./configure
Found possible Python library paths:
  /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages
Please input the desired Python library path to use.  Default is [/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages]

Do you wish to build TensorFlow with ROCm support? [y/N]: N
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: N
No CUDA support will be enabled for TensorFlow.

Do you wish to download a fresh release of clang? (Experimental) [y/N]: N
Clang will not be downloaded.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -Wno-sign-compare]: 


Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: N
Not configuring the WORKSPACE for Android builds.

Do you wish to build TensorFlow with iOS support? [y/N]: y
iOS support will be enabled for TensorFlow.
```

**Output when run bazel build**
```
adityadwipamungkas@Adityas-MacBook-Pro tensorflow-2.6.2 % bazel build --action_env PYTHON_BIN_PATH=/usr/bin/python3 --verbose_failures --config=ios_arm64 -c opt //tensorflow/lite/ios:TensorFlowLiteCMetal_framework
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=159
INFO: Reading rc options for 'build' from /Users/adityadwipamungkas/Downloads/tensorflow-2.6.2/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /Users/adityadwipamungkas/Downloads/tensorflow-2.6.2/.bazelrc:
  'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true
INFO: Reading rc options for 'build' from /Users/adityadwipamungkas/Downloads/tensorflow-2.6.2/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env PYTHON_LIB_PATH=/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages --python_path=/usr/bin/python3
INFO: Found applicable config definition build:short_logs in file /Users/adityadwipamungkas/Downloads/tensorflow-2.6.2/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /Users/adityadwipamungkas/Downloads/tensorflow-2.6.2/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:ios_arm64 in file /Users/adityadwipamungkas/Downloads/tensorflow-2.6.2/.bazelrc: --config=ios --cpu=ios_arm64
INFO: Found applicable config definition build:ios in file /Users/adityadwipamungkas/Downloads/tensorflow-2.6.2/.bazelrc: --apple_platform_type=ios --apple_bitcode=embedded --copt=-fembed-bitcode --copt=-Wno-c++11-narrowing --noenable_platform_specific_config --copt=-w --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --define=with_xla_support=false
WARNING: Download from http://mirror.tensorflow.org/github.com/tensorflow/runtime/archive/b570a1921c9e55ac53c8972bd2bfd37cd0eb510d.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
DEBUG: /private/var/tmp/_bazel_adityadwipamungkas/5c73181a29c264533309cd4aec522b90/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
INFO: Repository local_execution_config_python instantiated at:
  /Users/adityadwipamungkas/Downloads/tensorflow-2.6.2/WORKSPACE:15:14: in <toplevel>
  /Users/adityadwipamungkas/Downloads/tensorflow-2.6.2/tensorflow/workspace2.bzl:1088:19: in workspace
  /Users/adityadwipamungkas/Downloads/tensorflow-2.6.2/tensorflow/workspace2.bzl:85:27: in _tf_toolchains
  /private/var/tmp/_bazel_adityadwipamungkas/5c73181a29c264533309cd4aec522b90/external/tf_toolchains/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  /private/var/tmp/_bazel_adityadwipamungkas/5c73181a29c264533309cd4aec522b90/external/tf_toolchains/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  /Users/adityadwipamungkas/Downloads/tensorflow-2.6.2/third_party/py/python_configure.bzl:275:41: in <toplevel>
INFO: Repository local_config_python instantiated at:
  /Users/adityadwipamungkas/Downloads/tensorflow-2.6.2/WORKSPACE:15:14: in <toplevel>
  /Users/adityadwipamungkas/Downloads/tensorflow-2.6.2/tensorflow/workspace2.bzl:1088:19: in workspace
  /Users/adityadwipamungkas/Downloads/tensorflow-2.6.2/tensorflow/workspace2.bzl:95:21: in _tf_toolchains
Repository rule python_configure defined at:
  /Users/adityadwipamungkas/Downloads/tensorflow-2.6.2/third_party/py/python_configure.bzl:294:35: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_python':
   Traceback (most recent call last):
        File "/Users/adityadwipamungkas/Downloads/tensorflow-2.6.2/third_party/py/python_configure.bzl", line 267, column 40, in _python_autoconf_impl
                _create_local_python_repository(repository_ctx)
        File "/Users/adityadwipamungkas/Downloads/tensorflow-2.6.2/third_party/py/python_configure.bzl", line 213, column 39, in _create_local_python_repository
                numpy_include = _get_numpy_include(repository_ctx, python_bin) + "/numpy"
        File "/Users/adityadwipamungkas/Downloads/tensorflow-2.6.2/third_party/py/python_configure.bzl", line 187, column 19, in _get_numpy_include
                return execute(
        File "/Users/adityadwipamungkas/Downloads/tensorflow-2.6.2/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
ERROR: Error fetching repository: Traceback (most recent call last):
        File "/Users/adityadwipamungkas/Downloads/tensorflow-2.6.2/third_party/py/python_configure.bzl", line 267, column 40, in _python_autoconf_impl
                _create_local_python_repository(repository_ctx)
        File "/Users/adityadwipamungkas/Downloads/tensorflow-2.6.2/third_party/py/python_configure.bzl", line 213, column 39, in _create_local_python_repository
                numpy_include = _get_numpy_include(repository_ctx, python_bin) + "/numpy"
        File "/Users/adityadwipamungkas/Downloads/tensorflow-2.6.2/third_party/py/python_configure.bzl", line 187, column 19, in _get_numpy_include
                return execute(
        File "/Users/adityadwipamungkas/Downloads/tensorflow-2.6.2/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
INFO: Repository go_sdk instantiated at:
  /Users/adityadwipamungkas/Downloads/tensorflow-2.6.2/WORKSPACE:23:14: in <toplevel>
  /Users/adityadwipamungkas/Downloads/tensorflow-2.6.2/tensorflow/workspace0.bzl:120:20: in workspace
  /private/var/tmp/_bazel_adityadwipamungkas/5c73181a29c264533309cd4aec522b90/external/com_github_grpc_grpc/bazel/grpc_extra_deps.bzl:36:27: in grpc_extra_deps
  /private/var/tmp/_bazel_adityadwipamungkas/5c73181a29c264533309cd4aec522b90/external/io_bazel_rules_go/go/toolchain/toolchains.bzl:379:28: in go_register_toolchains
  /private/var/tmp/_bazel_adityadwipamungkas/5c73181a29c264533309cd4aec522b90/external/io_bazel_rules_go/go/private/sdk.bzl:65:21: in go_download_sdk
Repository rule _go_download_sdk defined at:
  /private/var/tmp/_bazel_adityadwipamungkas/5c73181a29c264533309cd4aec522b90/external/io_bazel_rules_go/go/private/sdk.bzl:53:35: in <toplevel>
ERROR: Analysis of target '//tensorflow/lite/ios:TensorFlowLiteCMetal_framework' failed; build aborted: Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
INFO: Elapsed time: 24.504s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (27 packages loaded, 26 targets configured)
    Fetching @local_config_xcode; fetching
```

CC: @yyoon

**Comment by yyoon** [comment]
Have you run the `./configure` script from the repository root directory, before executing the `bazel build` command?
The way you specify `PYTHON_BIN_PATH` is non-standard. Usually, you'd specify the Python executable path as well as the Python package path when running the `./configure` script, and those settings will be used for all of your subsequent `bazel build` command. (i.e., you shouldn't be manually specifying `--action_env PYTHON_BIN_PATH=...` from the command line)

**Comment by Miko2x** [comment]
I've run `./configure` once again:

<img width="888" alt="Screen Shot 2022-01-05 at 15 15 21" src="https://user-images.githubusercontent.com/41611726/148183587-dac99989-85dc-4776-9796-00a20be43a11.png">

And when i take a look at the site-packages it doesn't have numpy:

<img width="740" alt="Screen Shot 2022-01-05 at 15 21 24" src="https://user-images.githubusercontent.com/41611726/148184244-9091fa89-e683-4f27-8882-6f5355a9803d.png">

Is that possible to running the command `/Applications/Xcode.app/Contents/Developer/usr/bin/python3 -m pip install numpy` to install numpy inside Xcode Contents? Or it must be re-installing the Command Line Tools?

**Comment by Miko2x** [comment]
And when I use different Python library paths `/usr/local/lib/python3.7/site-packages`. It's give me another another error message:

```
adityadwipamungkas@Adityas-MacBook-Pro tensorflow-2.6.2 % bazel build --verbose_failures --config=ios_arm64 -c opt //tensorflow/lite/ios:TensorFlowLiteCMetal_framework
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=159
INFO: Reading rc options for 'build' from /Users/adityadwipamungkas/Downloads/tensorflow-2.6.2/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /Users/adityadwipamungkas/Downloads/tensorflow-2.6.2/.bazelrc:
  'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true
INFO: Reading rc options for 'build' from /Users/adityadwipamungkas/Downloads/tensorflow-2.6.2/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env PYTHON_LIB_PATH=/usr/local/lib/python3.7/site-packages --python_path=/usr/bin/python3
INFO: Found applicable config definition build:short_logs in file /Users/adityadwipamungkas/Downloads/tensorflow-2.6.2/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /Users/adityadwipamungkas/Downloads/tensorflow-2.6.2/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:ios_arm64 in file /Users/adityadwipamungkas/Downloads/tensorflow-2.6.2/.bazelrc: --config=ios --cpu=ios_arm64
INFO: Found applicable config definition build:ios in file /Users/adityadwipamungkas/Downloads/tensorflow-2.6.2/.bazelrc: --apple_platform_type=ios --apple_bitcode=embedded --copt=-fembed-bitcode --copt=-Wno-c++11-narrowing --noenable_platform_specific_config --copt=-w --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --define=with_xla_support=false
WARNING: Download from http://mirror.tensorflow.org/github.com/tensorflow/runtime/archive/b570a1921c9e55ac53c8972bd2bfd37cd0eb510d.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
DEBUG: /private/var/tmp/_bazel_adityadwipamungkas/5c73181a29c264533309cd4aec522b90/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
DEBUG: Repository io_bazel_rules_docker instantiated at:
  /Users/adityadwipamungkas/Downloads/tensorflow-2.6.2/WORKSPACE:23:14: in <toplevel>
  /Users/adityadwipamungkas/Downloads/tensorflow-2.6.2/tensorflow/workspace0.bzl:108:34: in workspace
  /private/var/tmp/_bazel_adityadwipamungkas/5c73181a29c264533309cd4aec522b90/external/bazel_toolchains/repositories/repositories.bzl:37:23: in repositories
Repository rule git_repository defined at:
  /private/var/tmp/_bazel_adityadwipamungkas/5c73181a29c264533309cd4aec522b90/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
ERROR: /private/var/tmp/_bazel_adityadwipamungkas/5c73181a29c264533309cd4aec522b90/external/build_bazel_rules_apple/tools/realpath/BUILD:9:14: in _apple_genrule_inner rule @build_bazel_rules_apple//tools/realpath:realpath_genrule: 
Traceback (most recent call last):
        File "/private/var/tmp/_bazel_adityadwipamungkas/5c73181a29c264533309cd4aec522b90/external/build_bazel_apple_support/rules/apple_genrule.bzl", line 78, column 28, in _apple_genrule_impl
                apple_support.run_shell(
        File "/private/var/tmp/_bazel_adityadwipamungkas/5c73181a29c264533309cd4aec522b90/external/build_bazel_apple_support/lib/apple_support.bzl", line 339, column 26, in _run_shell
                ctx.actions.run_shell(**_kwargs_for_apple_platform(ctx, **kwargs))
Error in run_shell: 'command' must be of type string. passing a sequence of strings as 'command' is deprecated. To temporarily disable this check, set --incompatible_run_shell_command_string=false.
ERROR: Analysis of target '//tensorflow/lite/ios:TensorFlowLiteCMetal_framework' failed; build aborted: Analysis of target '@build_bazel_rules_apple//tools/realpath:realpath_genrule' failed
INFO: Elapsed time: 0.551s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

**Comment by yyoon** [comment]
In your screenshot, the Python lib path definitely doesn't look right: It's pointing to a python module directory contained within your Xcode installation. It should be something like `/Library/Python/3.7/site-packages` or something along this line.

For the following error:
```
Error in run_shell: 'command' must be of type string. passing a sequence of strings as 'command' is deprecated. To temporarily disable this check, set --incompatible_run_shell_command_string=false.
```

Try running `bazel build` with the suggested flag:
```
bazel build --incompatible_run_shell_command_string=false --verbose_failures --config=ios_arm64 -c opt //tensorflow/lite/ios:TensorFlowLiteCMetal_framework
```

**Comment by Miko2x** [comment]
> In your screenshot, the Python lib path definitely doesn't look right: It's pointing to a python module directory contained within your Xcode installation. It should be something like `/Library/Python/3.7/site-packages` or something along this line.
> 
> For the following error:
> 
> ```
> Error in run_shell: 'command' must be of type string. passing a sequence of strings as 'command' is deprecated. To temporarily disable this check, set --incompatible_run_shell_command_string=false.
> ```
> 
> Try running `bazel build` with the suggested flag:
> 
> ```
> bazel build --incompatible_run_shell_command_string=false --verbose_failures --config=ios_arm64 -c opt //tensorflow/lite/ios:TensorFlowLiteCMetal_framework
> ```

Yes it works! Successfully build with no error, the problem it's just wrong Python path library. But I can't use TensorFlowLiteCMetal_framework 😅 which brings up another problem. There might be a problem with the framework I'm using. Thanks @yyoon

**Comment by Miko2x** [comment]
Closing the issue

**Comment by juancrescente** [comment]
This isn't working for me
```

➜  tensorflow git:(master) ✗ bazel build --config opt  --incompatible_run_shell_command_string=false --verbose_failures --config=ios_arm64 //tensorflow/tools/lib_package:libtensorflow

WARNING: Option 'java_toolchain' is deprecated
WARNING: Option 'host_java_toolchain' is deprecated
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=80
INFO: Reading rc options for 'build' from /Users/juan.crescente/Documents/lib/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /Users/juan.crescente/Documents/lib/tensorflow/.bazelrc:
  'build' options: --define framework_shared_object=true --java_toolchain=//tensorflow/tools/toolchains/java:tf_java_toolchain --host_java_toolchain=//tensorflow/tools/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library
INFO: Reading rc options for 'build' from /Users/juan.crescente/Documents/lib/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/opt/homebrew/opt/python@3.9/bin/python3.9 --action_env PYTHON_LIB_PATH=/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages --python_path=/opt/homebrew/opt/python@3.9/bin/python3.9
INFO: Reading rc options for 'build' from /Users/juan.crescente/Documents/lib/tensorflow/.bazelrc:
  'build' options: --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/analysis,tensorflow/compiler/mlir/tfrt/tests/jit,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_tfrt,tensorflow/compiler/mlir/tfrt/tests/tf_to_corert,tensorflow/compiler/mlir/tfrt/tests/tf_to_tfrt_data,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/common,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/graph_executor,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
INFO: Found applicable config definition build:short_logs in file /Users/juan.crescente/Documents/lib/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /Users/juan.crescente/Documents/lib/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:opt in file /Users/juan.crescente/Documents/lib/tensorflow/.tf_configure.bazelrc: --copt=-Wno-sign-compare --host_copt=-Wno-sign-compare
INFO: Found applicable config definition build:ios_arm64 in file /Users/juan.crescente/Documents/lib/tensorflow/.bazelrc: --config=ios --cpu=ios_arm64
INFO: Found applicable config definition build:ios in file /Users/juan.crescente/Documents/lib/tensorflow/.bazelrc: --apple_platform_type=ios --apple_bitcode=embedded --copt=-fembed-bitcode --copt=-Wno-c++11-narrowing --noenable_platform_specific_config --copt=-w --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --define=with_xla_support=false
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1596824487 -0400"
DEBUG: Repository io_bazel_rules_docker instantiated at:
  /Users/juan.crescente/Documents/lib/tensorflow/WORKSPACE:23:14: in <toplevel>
  /Users/juan.crescente/Documents/lib/tensorflow/tensorflow/workspace0.bzl:110:34: in workspace
  /private/var/tmp/_bazel_juan.crescente/7d4fd1924864d2d6fce922e4404d7479/external/bazel_toolchains/repositories/repositories.bzl:35:23: in repositories
Repository rule git_repository defined at:
  /private/var/tmp/_bazel_juan.crescente/7d4fd1924864d2d6fce922e4404d7479/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
ERROR: /private/var/tmp/_bazel_juan.crescente/7d4fd1924864d2d6fce922e4404d7479/external/local_config_cc/BUILD:48:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'ios_arm64'
ERROR: /private/var/tmp/_bazel_juan.crescente/7d4fd1924864d2d6fce922e4404d7479/external/local_config_cc/BUILD:48:19: Analysis of target '@local_config_cc//:toolchain' failed
ERROR: Analysis of target '//tensorflow/tools/lib_package:libtensorflow' failed; build aborted: 
INFO: Elapsed time: 7.847s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (162 packages loaded, 2279 targets\
 configured)
    Fetching @icu; fetching 5s
    Fetching ...al/icu; Extracting /private/var/tmp/_bazel_juan.crescente/7d4f\
d1924864d2d6fce922e4404d7479/external/icu/temp3335231244032830633/release-69-1\
.zip
    Fetching @com_google_absl; fetching
    Fetching ...e_absl; Extracting /private/var/tmp/_bazel_juan.crescente/7d4f\
d1924864d2d6fce922e4404d7479/external/com_google_absl/temp8830191500362278687/\
215105818dfde3174fe799600bb0f3cae233d0bf.tar.gz
    Fetching @sobol_data; fetching
    Fetching ...l_data; Extracting /private/var/tmp/_bazel_juan.crescente/7d4f\
d1924864d2d6fce922e4404d7479/external/sobol_data/temp13275797610274825581/835a\
7d7b1ee3bc83e575e302a985c66ec4b65249.tar.gz

```
