### ISSUE TITLE
OSError: SavedModel file does not exist at: final_model_weights.hdf5/{saved_model.pbtxt|saved_model.pb}

### ISSUE THREAD

**Issue by 3kba** [tensorflow/tensorflow#53661]
Hey a have a problem whn i try to load the module :

my code : index.py

```
def getPrediction(filename):
     model = tf.keras.models.load_model("final_model_weights.hdf5")
     img = load_img('static/'+filename, target_size=(180, 180))
     img = img_to_array(img)
     img = img / 255
     img = np.expand_dims(img,axis=0)
     category = model.predict_classes(img)
     answer = category[0]
     probability = model.predict(img)
     probability_results = 0

     if answer == 1:
          answer = "Recycle"
          probability_results = probability[0][1]
     else:
          answer = "Organic"
          probability_results = probability[0][0]

     answer = str(answer)
     probability_results=str(probability_results)

     values = [answer, probability_results, filename]
     return values[0], values[1], values[2]
```

when i upload the image to my code i get this error :

```
OSError
OSError: SavedModel file does not exist at: final_model_weights.hdf5/{saved_model.pbtxt|saved_model.pb}

Traceback (most recent call last)
File "/home/devokba/.local/lib/python3.9/site-packages/flask/app.py", line 2091, in __call__
return self.wsgi_app(environ, start_response)
File "/home/devokba/.local/lib/python3.9/site-packages/flask/app.py", line 2076, in wsgi_app
response = self.handle_exception(e)
File "/home/devokba/.local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/home/devokba/.local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/devokba/.local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/home/devokba/.local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/home/devokba/Documents/waste-classification-model/index.py", line 42, in submit_image
getPrediction(filename)
File "/home/devokba/Documents/waste-classification-model/main.py", line 14, in getPrediction
model = tf.keras.models.load_model("final_model_weights.hdf5")
File "/home/devokba/.local/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
raise e.with_traceback(filtered_tb) from None
File "/home/devokba/.local/lib/python3.9/site-packages/tensorflow/python/saved_model/loader_impl.py", line 118, in parse_saved_model
raise IOError(
OSError: SavedModel file does not exist at: final_model_weights.hdf5/{saved_model.pbtxt|saved_model.pb}
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object


```

structure of my code : 
```
┣ Resources/
┃ ┣ Dataset/
┃ ┣ Images/
┃ ┗ Model/
┣ __pycache__/
┃ ┣ main.cpython-38.pyc
┃ ┗ main.cpython-39.pyc
┣ static/
┃ ┣ Empty_Coca_Cola_Bottle.jpg
┃ ┣ O_1.jpg
┃ ┣ O_2.jpg
┃ ┗ img1.jpeg
┣ templates/
┃ ┗ index.html
┣ .gitattributes
┣ Procfile.txt
┣ Project 3 Proposal.docx
┣ README.md
┣ final_model.ipynb
┣ final_model_weights.hdf5
┣ index.py
┣ main.py
┣ presentation_notebook.ipynb
┗ requirements.txt

```
any solution for that ??

**Comment by tilakrayal** [comment]
@3kba ,
Can you please look at this comment from the [issue](https://github.com/tensorflow/tensorflow/issues/22480) with similar error.It helps.Thanks

**Comment by 3kba** [comment]
> @3kba , Can you please look at this comment from the [issue](https://github.com/tensorflow/tensorflow/issues/22480) with similar error.It helps.Thanks

i looked before to all this issues but i didn't get the solution that's why i made this issues, So you have any solution for that ?

**Comment by 3kba** [comment]
Any solution?

**Comment by tilakrayal** [comment]
@3kba ,
In order to expedite the trouble-shooting process, could you please provide the complete code and dataset to reproduce the issue reported here.

**Comment by miaout17** [comment]
Removing comp:lite because this seems irrelevant to TFLite.

**Comment by 3kba** [comment]
sorry for late reply : 
all code : 
main.py
```
# Dependencies
import numpy as np
import keras
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.applications.vgg16 import preprocess_input
from keras.applications.vgg16 import decode_predictions
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from keras.applications.vgg16 import VGG16
import tensorflow as tf
from tensorflow.keras.models import load_model


# def predict(img_path):
def getPrediction(filename):
     model = tf.keras.models.load_model("final_model_weights.hdf5")
     img = load_img('static/'+filename, target_size=(180, 180))
     img = img_to_array(img)
     img = img / 255
     img = np.expand_dims(img,axis=0)
     category = model.predict_classes(img)
     answer = category[0]
     probability = model.predict(img)
     probability_results = 0

     if answer == 1:
          answer = "Recycle"
          probability_results = probability[0][1]
     else:
          answer = "Organic"
          probability_results = probability[0][0]

     answer = str(answer)
     probability_results=str(probability_results)

     values = [answer, probability_results, filename]
     return values[0], values[1], values[2]

```

index.py 
```
# Import Dependencies
from flask import Flask, render_template, request, redirect, flash, url_for
import main
import urllib.request
from werkzeug.utils import secure_filename
from main import getPrediction
import os


#################################################
# Flask Setup
#################################################

UPLOAD_FOLDER = 'static/'

app = Flask(__name__)                    
app.secret_key = '8662747133'
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

# Route to HTML    
@app.route('/')
def index():
    return render_template('index.html')


@app.route("/", methods = ['POST']) #/file
# Our function for pushing the image to the classifier model
def submit_image():
     if request.method == 'POST':
          if 'file' not in request.files:
               flash('No file part')
               return redirect(request.url)
          file = request.files['file']
        # Error message if no file submitted
          if file.filename == '':
            flash('No file selected for uploading')
            return redirect(request.url)
        # Return results predictive data
          if file:
            filename = secure_filename(file.filename)
            file.save(os.path.join('static/', filename))
            getPrediction(filename)
            answer, probability_results, filename = getPrediction(filename)
            flash(answer)
            flash(probability_results) # accuracy
            flash(filename)
            return redirect('/')

if __name__ == "__main__":
    app.run(debug=True)

```

**Comment by tilakrayal** [comment]
@3kba ,
Please post this issue on [keras-team/keras](https://github.com/keras-team/keras/issues) repo.
To know more refer to:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
