### ISSUE TITLE
Training a model : Error 

### ISSUE THREAD

**Issue by leenajuliet-cc** [tensorflow/tensorflow#53819]
# Train the Model
model.fit(x=train_batches,
          steps_per_epoch=len(train_batches),
          validation_data=valid_batches,
          validation_steps=len(valid_batches),
          epochs=10,
          verbose=2
)

........................................................................................................................................

ValueError                                Traceback (most recent call last)
Input In [12], in <module>
      1 # Train the Model
----> 2 model.fit(x=train_batches,
      3           steps_per_epoch=len(train_batches),
      4           validation_data=valid_batches,
      5           validation_steps=len(valid_batches),
      6           epochs=10,
      7           verbose=2
      8 )

File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\utils\traceback_utils.py:67, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     65 except Exception as e:  # pylint: disable=broad-except
     66   filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67   raise e.with_traceback(filtered_tb) from None
     68 finally:
     69   del filtered_tb

File ~\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\framework\func_graph.py:1129, in func_graph_from_py_func.<locals>.autograph_handler(*args, **kwargs)
   1127 except Exception as e:  # pylint:disable=broad-except
   1128   if hasattr(e, "ag_error_metadata"):
-> 1129     raise e.ag_error_metadata.to_exception(e)
   1130   else:
   1131     raise

ValueError: in user code:

    File "C:\Users\leena juliet\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\training.py", line 878, in train_function  *
        return step_function(self, iterator)
    File "C:\Users\leena juliet\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\training.py", line 867, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\leena juliet\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\training.py", line 860, in run_step  **
        outputs = model.train_step(data)
    File "C:\Users\leena juliet\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\training.py", line 809, in train_step
        loss = self.compiled_loss(
    File "C:\Users\leena juliet\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\compile_utils.py", line 201, in __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "C:\Users\leena juliet\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\losses.py", line 141, in __call__
        losses = call_fn(y_true, y_pred)
    File "C:\Users\leena juliet\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\losses.py", line 245, in call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "C:\Users\leena juliet\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\losses.py", line 1664, in categorical_crossentropy
        return backend.categorical_crossentropy(
    File "C:\Users\leena juliet\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\backend.py", line 4994, in categorical_crossentropy
        target.shape.assert_is_compatible_with(output.shape)

    ValueError: Shapes (None, None) and (None, 7, 7, 2) are incompatible

**Comment by tilakrayal** [comment]
@leenajuliet-cc ,
Please take a look at this SO links [1](https://stackoverflow.com/questions/61742556/valueerror-shapes-none-1-and-none-2-are-incompatible) [2](https://stackoverflow.com/questions/62449191/tensorflow-error-in-colab-valueerror-shapes-none-1-and-none-10-are-inco) and [3](https://stackoverflow.com/questions/62148806/valueerror-shapes-none-1-and-none-6-are-incompatible) with the similar error.It helps.Thanks!
