### ISSUE TITLE
ValueError: Failed to find data adapter that can handle input

### ISSUE THREAD

**Issue by wjyts1999** [tensorflow/tensorflow#53836]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): win10
- TensorFlow installed from (source or binary):pip
- TensorFlow version (use command below):2.5.0
- Python version:3.7.11
- CUDA/cuDNN version:11.2
- GPU model and memory: rtx3060 laptop 6g

problem:
```
Traceback (most recent call last):
  File "E:/python/cloud_remove_keras/train_models/train_resnet.py", line 42, in <module>
    callbacks=[cp_callback])  # Pass callback to training
  File "D:\anaconda3\envs\PyGIS\lib\site-packages\keras\engine\training.py", line 1122, in fit
    steps_per_execution=self._steps_per_execution)
  File "D:\anaconda3\envs\PyGIS\lib\site-packages\keras\engine\data_adapter.py", line 1348, in get_data_handler
    return DataHandler(*args, **kwargs)
  File "D:\anaconda3\envs\PyGIS\lib\site-packages\keras\engine\data_adapter.py", line 1136, in __init__
    adapter_cls = select_data_adapter(x, y)
  File "D:\anaconda3\envs\PyGIS\lib\site-packages\keras\engine\data_adapter.py", line 978, in select_data_adapter
    _type_name(x), _type_name(y)))
ValueError: Failed to find data adapter that can handle input: <class 'data_generator.DataGenerator'>, <class 'NoneType'>
```
networks:
```
import keras.backend as K
from keras.layers import Conv2D, Activation, Lambda, Add
from keras.models import Model, Input
from tensorflow.keras.utils import plot_model

K.set_image_data_format('channels_first')


def resBlock(input_l, feature_size, kernel_size, scale=0.1):
    """Definition of Residual Block to be repeated in body of network."""
    tmp = Conv2D(feature_size, kernel_size, kernel_initializer='he_uniform', padding='same')(input_l)
    tmp = Activation('relu')(tmp)
    tmp = Conv2D(feature_size, kernel_size, kernel_initializer='he_uniform', padding='same')(tmp)

    tmp = Lambda(lambda x: x * scale)(tmp)

    return Add()([input_l, tmp])


def res_net(input_shape=(3, 512, 512),
                  num_layers=32,
                  feature_size=256):
    """Definition of network structure. """

    # define dimensions
    input = Input(shape=input_shape)

    x = input

    # Treat the concatenation
    x = Conv2D(feature_size, (3, 3), kernel_initializer='he_uniform', padding='same')(x)
    x = Activation('relu')(x)

    # main body of network as succession of resblocks
    for i in range(num_layers):
        x = resBlock(x, feature_size, kernel_size=[3, 3])

    # One more convolution
    x = Conv2D(input_shape[0], (3, 3), kernel_initializer='he_uniform', padding='same')(x)

    # Add first layer (long skip connection)
    x = Add()([x, input])

    model = Model(inputs=input, outputs=x)

    return model
```
data generator:
```
import numpy as np
import os
from tensorflow.keras.utils import Sequence
from tensorflow.keras.preprocessing.image import load_img, img_to_array


class DataGenerator(Sequence):
    def __init__(self, infile_path, batch_size, ratio, train_available):
        super(DataGenerator, self).__init__()

        self.infile_path = infile_path
        self.batch_size = batch_size
        self.ratio = ratio
        self.train_available = train_available

        self.cloud_path = os.path.join(infile_path, 'cloudy_image')
        self.ground_path = os.path.join(infile_path, 'ground_truth')
        # 所有文件列表，在 cloudy 和 ground truth 文件夹中文件名称是一样的
        self.file_list = os.listdir(self.ground_path)
        # 打乱顺序
        np.random.shuffle(self.file_list)
        # 分割训练数据和测试数据
        n_train = int(ratio * len(self.file_list))

        self.train_file_list = self.file_list[:n_train]
        self.test_file_list = self.file_list[n_train:]

        # 将训练和测试文件保存到文件中
        # np.savetxt(os.path.join(infile_path, 'train_file_list.txt'), np.array(self.train_file_list), fmt='%s')
        # np.savetxt(os.path.join(infile_path, 'test_file_list.txt'), np.array(self.test_file_list), fmt='%s')

    def __len__(self):
        if self.train_available:
            return int(np.floor(len(self.train_file_list) / self.batch_size))
        else:
            return int(np.floor(len(self.test_file_list) / self.batch_size))

    def __getitem__(self, index):
        if self.train_available:
            file_list = self.train_file_list[index * self.batch_size:(index + 1) * self.batch_size]
            batch_x = [np.transpose(img_to_array(load_img(os.path.join(self.cloud_path, file_name)))/255.0, [2, 0, 1]) for file_name in file_list]
            batch_y = [np.transpose(img_to_array(load_img(os.path.join(self.ground_path, file_name)))/255.0, [2, 0, 1]) for file_name in file_list]

            return np.array(batch_x), np.array(batch_y)

        else:
            file_list = self.test_file_list[index * self.batch_size:(index + 1) * self.batch_size]
            batch_x = [np.transpose(img_to_array(load_img(os.path.join(self.cloud_path, file_name)))/255.0, [2, 0, 1]) for file_name in file_list]
            batch_y = [np.transpose(img_to_array(load_img(os.path.join(self.ground_path, file_name))) / 255.0, [2, 0, 1]) for file_name in file_list]
            return np.array(batch_x), np.array(batch_y)
```
train code:
```
import tensorflow as tf
import os

from data_generator import DataGenerator
from networks.resnet import res_net


params = {
    'infile_path': r"E:\python\cloud_removal\data\RICE_DATASET\RICE2",
    'batch_size': 32,
    'ratio': 0.8,
    'train_available': True
}
train_Gen = DataGenerator(**params)

params = {
    'infile_path': r"E:\python\cloud_removal\data\RICE_DATASET\RICE2",
    'batch_size': 32,
    'ratio': 0.8,
    'train_available': False
}
val_Gen = DataGenerator(**params)

model = res_net()

model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

checkpoint_path = "train_models/resnet/cp.ckpt"
checkpoint_dir = os.path.dirname(checkpoint_path)

# Create a callback that saves the model's weights
cp_callback = tf.keras.callbacks.ModelCheckpoint(filepath=checkpoint_path,
                                                 save_weights_only=True,
                                                 verbose=1)

# Train the model with the new callback
model.fit(x=train_Gen,
          validation_data=val_Gen,
          epochs=10,
          callbacks=[cp_callback])  # Pass callback to training

model.save('train_models/resnet')
```

**Comment by mohantym** [comment]
Hi @wjyts1999 ! I did not have the relevant dataset. Can you try one of following 
1. convert involved dataset to numpy arrays.
2. use tf.keras instead of keras. 
Attaching relevant thread for [reference](https://stackoverflow.com/questions/57874436/tensorflow-data-adapter-error-valueerror-failed-to-find-data-adapter-that-can) .Thanks.

**Comment by wjyts1999** [comment]
@mohantym thank you very much
