### ISSUE TITLE
[Metric] get shape of a tensor for custom metric

### ISSUE THREAD

**Issue by hoangtnm** [tensorflow/tensorflow#53851]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): conda-forge
- TensorFlow version (use command below): 2.6.2
- Python version: 3.7
- CUDA/cuDNN version: 10.2 / 7.6.5.32
- GPU model and memory: GTX 1080Ti

**Describe the current behavior**

I am implementing a custom metric for `tf.keras` which need to extract the batch dimension of input tensor `x.shape[0]` during `model.fit(...)` but it raises:

```
(None, None)
Traceback (most recent call last):
  File "train.py", line 81, in <module>
    main()
  File "train.py", line 71, in main
    use_multiprocessing=True)
  File "/opt/conda/lib/python3.7/site-packages/keras/engine/training.py", line 1184, in fit
    tmp_logs = self.train_function(iterator)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 885, in __call__
    result = self._call(*args, **kwds)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 933, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 760, in _initialize
    *args, **kwds))
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3066, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3463, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3308, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 1007, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 668, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 994, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /opt/conda/lib/python3.7/site-packages/keras/engine/training.py:853 train_function  *
        return step_function(self, iterator)
    /AgeGenderMask/metrics/age_mae.py:36 update_state  *
        self.count.assign_add(y_true.shape[0])
    /opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:857 assign_add  **
        ops.convert_to_tensor(delta, dtype=self.dtype),
    /opt/conda/lib/python3.7/site-packages/tensorflow/python/profiler/trace.py:163 wrapped
        return func(*args, **kwargs)
    /opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:1566 convert_to_tensor
        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    /opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py:346 _constant_tensor_conversion_function
        return constant(v, dtype=dtype, name=name)
    /opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py:272 constant
        allow_broadcast=True)
    /opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py:290 _constant_impl
        allow_broadcast=allow_broadcast))
    /opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/tensor_util.py:445 make_tensor_proto
        raise ValueError("None values not supported.")
```

**Describe the expected behavior**

As mentioned above.

**Standalone code to reproduce the issue**

```python
class CustomMetric(keras.metrics.Metric):
    def __init__(self, name: Optional[str] = None) -> None:
        super().__init__(name=name)
        self.total = self.add_weight("total", initializer="zero")
        self.count = self.add_weight("count", initializer="zero")

    def update_state(self, y_true, y_pred, sample_weight=None) -> None:
        self.total.assign_add(tf.reduce_sum(y_pred))
        print(y_true.shape[0]) # Cannot extract tensor's shape
        self.count.assign_add(y_true.shape[0])

    def result(self) -> tf.Tensor:
        return tf.math.divide_no_nan(self.total, self.count)

    def reset_state(self) -> None:
        self.total.assign(0)
        self.count.assign(0)
```

**Comment by sushreebarsa** [comment]
@hoangtnm 
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!

**Comment by hoangtnm** [comment]
@sushreebarsa this issue was solved. thank you.
https://github.com/keras-team/keras/issues/15932
