### ISSUE TITLE
AttributeError: 'module' object has no attribute 'learn'

### ISSUE THREAD

**Issue by austintrombley** [tensorflow/tensorflow#5392]
In your first code example you have the following function tf.contrib.learn being called:

```
  run_config = tf.contrib.learn.estimators.RunConfig(
      num_cores=3, gpu_memory_fraction=0.6)
```

But if you look at the options you won't see learn....  

```
>>> dir(tf.contrib)
['__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', 'absolute_import', 'division', 'layers', 'print_function', 'util']
```
So you get the error:
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Library/Python/2.7/site-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "<stdin>", line 6, in main
AttributeError: 'module' object has no attribute 'learn'
```

**Comment by austintrombley** [comment]
This is in your boston example as well, for the import:

NameError: global name 'learn' is not defined

**Comment by Curious72** [comment]
@austintrombley It seems to work fine ! 

`>>>import tensorflow as tf`
` >>>dir(tf.contrib)`
`['__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', 'absolute_import', 'bayesflow', 'copy_graph', 'distributions', 'division', 'factorization', 'framework', 'graph_editor', 'grid_rnn', 'layers', 'learn', 'linear_optimizer', 'lookup', 'losses', 'metrics', 'opt', 'print_function', 'quantization', 'rnn', 'session_bundle', 'slim', 'tensor_forest', 'testing', 'util']`

**Comment by aselle** [comment]
@austintrombley, it is difficult to help you when you don't provide basic information about your environment. The template in the submit github issue is information that is very useful for us to know in order to help you. Please provide that information. Thanks!

**Comment by aselle** [comment]
Thanks @Curios72 for trying this. What version/os are you using for reference so that @austintrombley can try your config?

**Comment by girving** [comment]
Closing due to lack of activity.

**Comment by cxm01** [comment]
I met similar issue, see #8794
