### ISSUE TITLE
Seg faults when build with Hadoop file system support

### ISSUE THREAD

**Issue by llhe** [tensorflow/tensorflow#5399]
When I run testes with TensorFlow hadoop file system, seg fault was found:
```
(gdb) bt
#0  0x00007f86de2ba580 in collect () from /lib64/libpython2.7.so.1.0
#1  0x00007f86de2bb227 in _PyObject_GC_Malloc () from /lib64/libpython2.7.so.1.0
#2  0x00007f86de2bb26d in _PyObject_GC_New () from /lib64/libpython2.7.so.1.0
#3  0x00007f86de21e8d2 in list_iter () from /lib64/libpython2.7.so.1.0
#4  0x00007f86de1f62be in PyObject_GetIter () from /lib64/libpython2.7.so.1.0
#5  0x00007f86de28955d in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#6  0x00007f86de28d1ad in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#7  0x00007f86de21a18d in function_call () from /lib64/libpython2.7.so.1.0
#8  0x00007f86de1f5073 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#9  0x00007f86de204085 in instancemethod_call () from /lib64/libpython2.7.so.1.0
#10 0x00007f86de1f5073 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#11 0x00007f86de24c167 in slot_tp_init () from /lib64/libpython2.7.so.1.0
#12 0x00007f86de24ae7f in type_call () from /lib64/libpython2.7.so.1.0
#13 0x00007f86de1f5073 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#14 0x00007f86de28934c in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#15 0x00007f86de28d1ad in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#16 0x00007f86de28b85f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#17 0x00007f86de28d1ad in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#18 0x00007f86de28b85f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#19 0x00007f86de28d1ad in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#20 0x00007f86de28b85f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#21 0x00007f86de28d1ad in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#22 0x00007f86de28b85f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#23 0x00007f86de28d1ad in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#24 0x00007f86de21a098 in function_call () from /lib64/libpython2.7.so.1.0
#25 0x00007f86de1f5073 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#26 0x00007f86de2883e7 in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#27 0x00007f86de28d1ad in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#28 0x00007f86de28b85f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#29 0x00007f86de28d1ad in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#30 0x00007f86de28b85f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#31 0x00007f86de28d1ad in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#32 0x00007f86de28b85f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#33 0x00007f86de28d1ad in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#34 0x00007f86de28b85f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#35 0x00007f86de28d1ad in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#36 0x00007f86de28b85f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#37 0x00007f86de28d1ad in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#38 0x00007f86de28b85f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#39 0x00007f86de28d1ad in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#40 0x00007f86de28b85f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#41 0x00007f86de28d1ad in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#42 0x00007f86de28d2b2 in PyEval_EvalCode () from /lib64/libpython2.7.so.1.0
#43 0x00007f86de2a66ef in run_mod () from /lib64/libpython2.7.so.1.0
#44 0x00007f86de2a78ae in PyRun_FileExFlags () from /lib64/libpython2.7.so.1.0
#45 0x00007f86de2a8b39 in PyRun_SimpleFileExFlags () from /lib64/libpython2.7.so.1.0
#46 0x00007f86de2b9b3f in Py_Main () from /lib64/libpython2.7.so.1.0
#47 0x00007f86dd4e6af5 in __libc_start_main () from /lib64/libc.so.6
#48 0x0000000000400721 in _start ()
```
Haven't dig into this, and this may not directly related to hadoop plugin, because it can happen without accessing any hdfs files (but `LibHDFS::Load` is indeed called). This can't be reproed without linking hadoop.

**Comment by aselle** [comment]
Please look at the issue submission template. If you want further help you will need to provide that information. Thank you.

**Comment by girving** [comment]
Closing due to lack of activity.
