### ISSUE TITLE
Creating and fitting a Trainable leaks file descriptors 

### ISSUE THREAD

**Issue by brianquinlan** [tensorflow/tensorflow#5401]
Creating a Trainable and calling fit() on it leaks file descriptors.

### Environment info
Operating System: Mac OS X

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

None

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

0.11.0rc0

If installed from source, provide 

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

```
import numpy as np
import tensorflow
from tensorflow.contrib import learn, layers

def input_fn():
    return (
        {'a': tensorflow.constant([1.1, 2.2, 3.3], dtype=tensorflow.float32)}, 
        tensorflow.constant([5.0, 8.0, 12.5], dtype=tensorflow.float32))

while True:
    linear_regressor = learn.LinearRegressor(
        feature_columns=[layers.real_valued_column('a')])
    linear_regressor.fit(input_fn=input_fn, steps=1)
```

### Logs or other output that would be helpful

Traceback (most recent call last):
  File "tensor_bug.py", line 13, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 333, in fit
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 708, in _train_model
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/graph_actions.py", line 285, in _monitored_train
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/monitored_session.py", line 368, in run
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/monitored_session.py", line 521, in run
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/monitored_session.py", line 488, in run
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/monitored_session.py", line 612, in run
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/monitored_session.py", line 634, in _call_hook_before_run
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/basic_session_run_hooks.py", line 180, in before_run
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/training/training_util.py", line 76, in write_graph
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 211, in write_string_to_file
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 89, in write
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 81, in _prewrite_check
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py", line 66, in __exit__
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/framework/errors.py", line 463, in raise_exception_on_not_ok_status
tensorflow.python.framework.errors.ResourceExhaustedError: /var/folders/6c/3pzbp8jj3zd0lkhsszmvyd5h001cct/T/tmpzr7juea4/graph.pbtxt

During the run "lsof" is indicating that the number of file descriptors used is increased on every loop iteration.

**Comment by aselle** [comment]
@martinwicke, @ilblackdragon , could you take a look.

**Comment by martinwicke** [comment]
@ispirmustafa Maybe a summarywriter or similar object is not closing a file properly?

**Comment by ispirmustafa** [comment]
Leak can be anywhere in the code since this example is running all Estimator in an infinite loop.
I'll look into it. I'll update the thread when I find the reason/fix.
