### ISSUE TITLE
keras.layers.BatchNormalization/Reshape produces dynamic tensors when converted to tflite

### ISSUE THREAD

**Issue by zacps** [tensorflow/tensorflow#54261]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 (converter), Linux 5.10.17 (tflite)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Raspberry Pi 4 Model B Rev 1.4
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8 (converter) 3.7 (tflite)
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: 

**Describe the current behavior**
Converting a model containing a `BatchNormalization` & `Reshape` layers (allowed via `SELECT_TF_OPS`) produces tensors which have dynamic size. When running this using a tflite delegate which only supports static tensors the following error occurs:

```
RuntimeError: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors (tensor#420 is a dynamic-sized tensor).
```

where `tensor#420` is:

```
{
    'name': 'model_3/batch_normalization_4/FusedBatchNormV3', 
    'index': 420, 
    'shape': array([   1,    5,    1,    1, 1024]), 
    'shape_signature': array([   1,    5,    1,    1, 1024]), 
    'dtype': <class 'numpy.float32'>, 
    'quantization': (0.0, 0), 
    'quantization_parameters': {
      'scales': array([], dtype=float32), 
      'zero_points': array([], dtype=int32), 
      'quantized_dimension': 0
    }, 
    'sparsity_parameters': {}
}
```

**Describe the expected behavior**

The converted model runs successfully on a static delegate.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no

**Standalone code to reproduce the issue**
This is reproducible with:

```python
import tensorflow as tf
from tensorflow.keras import Sequential, Input, Model
from tensorflow.keras.layers import BatchNormalization, Dense, Reshape

inputs = Input(shape=(10,))
MLP = Sequential()
MLP.add(Dense(1024*5))
MLP.add(Reshape((5,1,1,1024)))
MLP.add(BatchNormalization(axis=1))
MLP.add(Dense(1024*5))

output = MLP(inputs)

model = Model(inputs=inputs, outputs=output)
model.save('reproduce_bug')
converter = tf.lite.TFLiteConverter.from_saved_model('reproduce_bug')

converter._experimental_lower_tensor_list_ops = False
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]

tflite_model = converter.convert()

with open("reproduce_bug.tflite", "wb") as f:
    f.write(tflite_model)
```

and then on the tflite device:

```python
import tflite_runtime.interpreter as tflite

interpreter = tflite.Interpreter(model_path='reproduce_bug.tflite')

for tdetails in interpreter.get_tensor_details():
    if tdetails['index'] == 19: # or your failing index
        print(tdetails)

interpreter.allocate_tensors()
```

Note that unlike our real failing case this fails on a tensor in reshape rather than in `BatchNormalization`.

**Other info / logs** 
Full traceback:

```python-traceback
Traceback (most recent call last):
  File "inference.py", line 20, in <module>
    interpreter.allocate_tensors()
  File "/home/pi/.local/lib/python3.7/site-packages/tflite_runtime/interpreter.py", line 521, in allocate_tensors
    return self._interpreter.AllocateTensors()
RuntimeError: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors (tensor#420 is a dynamic-sized tensor).Ignoring failed application of the default TensorFlow Lite delegate indexed at 0.
```

**Comment by MeghnaNatraj** [comment]
@zacps By default, keras sets `batch_size` or the first argument of the input to be dynamic (i.e, -1). In order to fix this, please update your code as follows:

Initial code: ```inputs = Input(shape=(10,))```
Updated code: ```inputs = Input(shape=(10,), batch_size=1)```



Updated standalone code:

```
import tensorflow as tf
from tensorflow.keras import Sequential, Input, Model
from tensorflow.keras.layers import BatchNormalization, Dense, Reshape

inputs = Input(shape=(10,), batch_size=1)
MLP = Sequential()
MLP.add(Dense(1024*5))
MLP.add(Reshape((5,1,1,1024)))
MLP.add(BatchNormalization(axis=1))
MLP.add(Dense(1024*5))

output = MLP(inputs)

model = Model(inputs=inputs, outputs=output)
model.save('reproduce_bug')
converter = tf.lite.TFLiteConverter.from_saved_model('reproduce_bug')

converter._experimental_lower_tensor_list_ops = False
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]

tflite_model = converter.convert()

with open("reproduce_bug.tflite", "wb") as f:
    f.write(tflite_model)
```

The issue should be resolved.

Additionally, did you happen to modify the `tensor#420` output?

Incorrect output (as you've mentioned above):
```
{
    'name': 'model_3/batch_normalization_4/FusedBatchNormV3', 
    'index': 420, 
    'shape': array([   1,    5,    1,    1, 1024]), 
    'shape_signature': array([   1,    5,    1,    1, 1024]), 
    'dtype': <class 'numpy.float32'>, 
    'quantization': (0.0, 0), 
    'quantization_parameters': {
      'scales': array([], dtype=float32), 
      'zero_points': array([], dtype=int32), 
      'quantized_dimension': 0
    }, 
    'sparsity_parameters': {}
}
```

Correct output (notice that the `shape_signature` has a -1 at the beginning):

```
{
    'name': 'model_3/batch_normalization_4/FusedBatchNormV3', 
    'index': 420, 
    'shape': array([   1,    5,    1,    1, 1024]), 
    'shape_signature': array([   -1,    5,    1,    1, 1024]), 
    'dtype': <class 'numpy.float32'>, 
    'quantization': (0.0, 0), 
    'quantization_parameters': {
      'scales': array([], dtype=float32), 
      'zero_points': array([], dtype=int32), 
      'quantized_dimension': 0
    }, 
    'sparsity_parameters': {}
}
```
