### ISSUE TITLE
AutoGraph could not transform <function ...>

### ISSUE THREAD

**Issue by andmis** [tensorflow/tensorflow#54274]
```
INFO:tensorflow:<function train_main.<locals>.train at 0x2976dd700> is not cached for subkey ConversionOptions[{}]
INFO:tensorflow:Source code of <function train_main.<locals>.train at 0x2976dd700>:

@tf.function
def train(batch):
    s    = batch[:, start_s:    end_s]
    a    = batch[:, start_a:    end_a]
    s_   = batch[:, start_s_:   end_s_]
    r    = batch[:, start_r:    end_r]
    done = batch[:, start_done: end_done]

    noise = tf.random.normal([args.batch_size, env.action_dim])
    a_, log_π_ = actor([s, noise])
    y = r + args.gamma * (1-done) * (
    tf.minimum(critic_1_target([s_, a_]),
    critic_2_target([s_, a_]))
    - args.alpha * log_π_)

    with tf.GradientTape() as tape:
        MSBE_1 = (1/args.batch_size) * tf.reduce_sum((critic_1([s, a]) - y)**2)
    MSBE_1_grads = tape.gradient(MSBE_1, critic_1.trainable_weights)
    critic_1_optimizer.apply_gradients(zip(MSBE_1_grads, critic_1.trainable_weights))

    with tf.GradientTape() as tape:
        MSBE_2 = (1/args.batch_size) * tf.reduce_sum((critic_2([s, a]) - y)**2)
    MSBE_2_grads = tape.gradient(MSBE_2, critic_2.trainable_weights)
    critic_2_optimizer.apply_gradients(zip(MSBE_2_grads, critic_2.trainable_weights))

    noise = tf.random.normal([args.batch_size, env.action_dim])
    with tf.GradientTape() as tape:
        log_π_θ: tf.Tensor
        a_θ , log_π_θ = actor([s, noise])
        expected_reward = (1/args.batch_size) *                 tf.reduce_sum(critic_1([s, a_θ]) - args.alpha * log_π_θ)
        neg_expected_reward = -expected_reward
    expected_reward_grad = tape.gradient(neg_expected_reward, actor.trainable_weights)
    actor_optimizer.apply_gradients(zip(expected_reward_grad, actor.trainable_weights))

    polyak_average(critic_1_target.variables, critic_1.variables)
    polyak_average(critic_2_target.variables, critic_2.variables)

    if args.model_name:
        MSBE_1_log(MSBE_1)
        MSBE_2_log(MSBE_2)
        expected_reward_log(expected_reward)


INFO:tensorflow:Error transforming entity <function train_main.<locals>.train at 0x2976dd700>
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 433, in converted_call
    converted_f = _convert_actual(target_entity, program_ctx)
  File "/opt/homebrew/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 275, in _convert_actual
    transformed, module, source_map = _TRANSPILER.transform(entity, program_ctx)
  File "/opt/homebrew/lib/python3.9/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 286, in transform
    return self.transform_function(obj, user_context)
  File "/opt/homebrew/lib/python3.9/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 470, in transform_function
    nodes, ctx = super(PyToPy, self).transform_function(fn, user_context)
  File "/opt/homebrew/lib/python3.9/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 363, in transform_function
    result = self.transform_ast(node, context)
  File "/opt/homebrew/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 243, in transform_ast
    node = self.initial_analysis(node, ctx)
  File "/opt/homebrew/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 231, in initial_analysis
    node = activity.resolve(node, ctx, None)
  File "/opt/homebrew/lib/python3.9/site-packages/tensorflow/python/autograph/pyct/static_analysis/activity.py", line 709, in resolve
    return ActivityAnalyzer(context, parent_scope).visit(node)
  File "/opt/homebrew/lib/python3.9/site-packages/tensorflow/python/autograph/pyct/transformer.py", line 445, in visit
    result = super(Base, self).visit(node)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/opt/homebrew/lib/python3.9/site-packages/tensorflow/python/autograph/pyct/static_analysis/activity.py", line 601, in visit_FunctionDef
    node.body = self.visit_block(node.body)
  File "/opt/homebrew/lib/python3.9/site-packages/tensorflow/python/autograph/pyct/transformer.py", line 340, in visit_block
    replacement = self.visit(node)
  File "/opt/homebrew/lib/python3.9/site-packages/tensorflow/python/autograph/pyct/transformer.py", line 445, in visit
    result = super(Base, self).visit(node)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/opt/homebrew/lib/python3.9/site-packages/tensorflow/python/autograph/pyct/static_analysis/activity.py", line 651, in visit_With
    node = self.generic_visit(node)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 483, in generic_visit
    value = self.visit(value)
  File "/opt/homebrew/lib/python3.9/site-packages/tensorflow/python/autograph/pyct/transformer.py", line 445, in visit
    result = super(Base, self).visit(node)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/opt/homebrew/lib/python3.9/site-packages/tensorflow/python/autograph/pyct/static_analysis/activity.py", line 394, in visit_AnnAssign
    node.value = self.visit(node.value)
  File "/opt/homebrew/lib/python3.9/site-packages/tensorflow/python/autograph/pyct/transformer.py", line 431, in visit
    raise ValueError(msg)
ValueError: invalid value for "node": expected "ast.AST", got "<class 'NoneType'>"; to visit lists of nodes, use "visit_block" instead
WARNING:tensorflow:AutoGraph could not transform <function train_main.<locals>.train at 0x2976dd700> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: invalid value for "node": expected "ast.AST", got "<class 'NoneType'>"; to visit lists of nodes, use "visit_block" instead
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
```

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 12
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary (`pip3 install tensorflow-macos`)
- TensorFlow version (use command below): `unknown 2.7.0`
- Python version: 3.9.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Sorry, but I can't provide the full source code.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by andmis** [comment]
I did some investigation and the problem seems to be on the line `log_π_θ: tf.Tensor` giving a type annotation for `log_π_θ`. If I comment that line out, the issue goes away.

**Comment by sushreebarsa** [comment]
@andmis 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by gadagashwini** [comment]
@andmis 
When i tried to replicate your issue, I got `SyntaxError: invalid syntax` at `log_π_θ: tf.Tensor`. 
Help us in replicating your issue to investigate the root cause. Thanks!

**Comment by andmis** [comment]
What version of Python are you using? That line of code is a variable type annotation. Python type hinting support was introduced in 3.5, and variable type annotations specifically in 3.6. You can read more about Python type hints at <https://docs.python.org/3/library/typing.html>. See also this StackOverflow thread: <https://stackoverflow.com/questions/51789120/type-hints-syntax-error-on-python-3-5>.

Do you get that error with Python >= 3.7?

**Comment by gadagashwini** [comment]
@andmis, I am using Python version 3.7.
I get the syntax error when i am using `log_π_θ: tf.Tensor`.
Thanks!

**Comment by andmis** [comment]
Do you get a syntax error if you run the following Python program?

```python
n: int
print('Hello, world')
```

**Comment by gadagashwini** [comment]
@andmis,
I didn’t get syntax error on Python ~=3.8 for both below code snippet.
```
n: int
print('Hello, world')
```
```
import tensorflow as tf
log_π_θ: tf.Tensor
```

**Comment by andmis** [comment]
Ok, now try this:

```python
import tensorflow as tf

@tf.function
def f():
  n: int
  return 0

f()
```

**Comment by gadagashwini** [comment]
@sachinprasadhs, I am abale replicate the issue with Tensorflow 2.8. Please find the Colab gist [here](https://colab.research.google.com/drive/1Za8SUtBmyXrfnlHYAspG8Fz1VXfcqsDF?usp=sharing).  Seems Autograph function failed to read `n: int`. Thanks!

**Comment by sachinprasadhs** [comment]
The operation which you are trying is not supported in tf.function. You can silence this warning by decorating with `@tf.autograph.experimental.do_not_convert` like below.

 import tensorflow as tf

```
@tf.function
@tf.autograph.experimental.do_not_convert
def f():
  n: int
  return 0

f()
```

**Comment by andmis** [comment]
- It's not an operation, it's a type annotation.
- The error message says, `Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.`
- Type annotations like `n: int = 3` work fine, with no error. Why is `n: int = 3` ok but `n: int` not ok?
- This is obviously a bug in the parser code.
