### ISSUE TITLE
TensorflowLite model can't run on Hexagon DSP device. Failed to apply delegate: Failed: Failed to prepare graph.

### ISSUE THREAD

**Issue by chmod740** [tensorflow/tensorflow#54309]
### 1. System information

- Linux Ubuntu 16.04 / Android 10.0
- pip package
- tensorflow==2.6.2 

### 2. Code
**export tflite code:**
```python3
import numpy as np
import tensorflow as tf

# Generate tf.keras model.
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.DepthwiseConv2D(kernel_size=(1, 9), strides=(1, 1), padding='same', data_format='channels_last'))
# model.add(tf.keras.layers.Dense(2, input_shape=(3,)))
model.compile(loss=tf.keras.losses.MSE,
              optimizer=tf.keras.optimizers.RMSprop(lr=0.0001),
              metrics=[tf.keras.metrics.categorical_accuracy],
              sample_weight_mode='temporal')


x = np.random.random((1, 1, 9, 64))
y = np.random.random((1, 1, 9, 64))
model.train_on_batch(x, y)
model.predict(x)

# Save tf.keras model in H5 format.
keras_file = 'keras_model.h5'
tf.keras.models.save_model(model, keras_file)

# Convert the model.
converter = tf.lite.TFLiteConverter.from_keras_model(model)

def representative_dataset_gen():
    for _ in range(100):
        yield [np.ones([1,1,9,64]).astype(np.float32)]
# converter.quantized_input_stats = {'input' : (0., 1.)}
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
# converter.inference_type = tf.uint8
converter.representative_dataset = representative_dataset_gen

tflite_model = converter.convert()

# Save the model.
with open('model2.tflite', 'wb') as f:
  f.write(tflite_model)
```

**android project code:**
```java
package com.elevoc.demo.app.tflitetest;

import android.content.Context;
import android.content.res.AssetFileDescriptor;
import android.content.res.AssetManager;
import android.os.SystemClock;
import android.util.Log;
import org.tensorflow.lite.DataType;
import org.tensorflow.lite.HexagonDelegate;
import org.tensorflow.lite.Interpreter;
import org.tensorflow.lite.support.tensorbuffer.TensorBuffer;

import java.io.FileInputStream;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.MappedByteBuffer;
import java.nio.channels.FileChannel;
import java.util.concurrent.locks.ReentrantLock;


public class TfInter {
    private final String MODEL_NAME = "model2.tflite";
    private final ReentrantLock tfLiteLock = new ReentrantLock();

    private Context context;
    private Interpreter tfLite = null;
    private HexagonDelegate hexagonDelegate = null;

    public TfInter(Context context){
        this.context = context;
        init(context);
    }

    public void init(Context context){
        Interpreter.Options options = (new Interpreter.Options());

//        options.setNumThreads(4);

        //TODO Hexagon delegate
        // Create the Delegate instance.
        try {
            hexagonDelegate = new HexagonDelegate(context);
            options.addDelegate(hexagonDelegate);
        } catch (UnsupportedOperationException e) {
            // Hexagon delegate is not supported on this device.
            options.setNumThreads(4);
        }

        MappedByteBuffer buf = null;
        try {
            buf = loadModelFile(context.getAssets(), MODEL_NAME);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }

        try {
            tfLite = new Interpreter(buf, options);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        // create the input tensor
        int inTensorIndex = 0;
        int[] inShape = tfLite.getInputTensor(inTensorIndex).shape(); // {1, height, width, 3}
        DataType inDataType = tfLite.getInputTensor(inTensorIndex).dataType();

        // create the output tensor
        int outTensorIndex = 0;
        int[] outShape = tfLite.getOutputTensor(outTensorIndex).shape(); // {1, max_lane_count, y_anchors, x_anchors}
        DataType outDataType = tfLite.getOutputTensor(outTensorIndex).dataType();
    }

    private MappedByteBuffer loadModelFile(AssetManager assetManager, String model_name) throws IOException {
        try (AssetFileDescriptor fileDescriptor = assetManager.openFd(model_name);
             FileInputStream inputStream = new FileInputStream(fileDescriptor.getFileDescriptor())) {
            FileChannel fileChannel = inputStream.getChannel();
            long startOffset = fileDescriptor.getStartOffset();
            long declaredLength = fileDescriptor.getDeclaredLength();
            return fileChannel.map(FileChannel.MapMode.READ_ONLY, startOffset, declaredLength);
        }
    }

    public void run(){
        byte[] input_t = new byte[1*1*9*64*4];
        ByteBuffer input1 = ByteBuffer.wrap(input_t);
        DataType probabilityDataType = tfLite.getOutputTensor(0).dataType();
        TensorBuffer output1 = TensorBuffer.createFixedSize(new int[]{1, 1, 9, 64 * 4}, probabilityDataType);

        long startTimeForReference = SystemClock.uptimeMillis();

        for(int i=0;i<1000;i++){
            tfLite.run(input1, output1.getBuffer().rewind());
        }

        long endTimeForReference = SystemClock.uptimeMillis();
        Log.d("tryTimeCost", "Timecost: " + (endTimeForReference - startTimeForReference));
    }
}

```

### 5. (optional) Any other info / logs
We used a test vehicle hardware platform to execute the above java code.
We have obtained ROOT permission for this device.
The following command also executed successfully
```
adb shell setenforce 0
```
We ran the [example tflite model](https://storage.googleapis.com/download.tensorflow.org/models/mobilenet_v1_2018_08_02/mobilenet_v1_1.0_224_quant.tgz) and it worked on the Hexagon DSP device, but our own exported model didn't work correctly. 

**our own exported model file can run on cpu/gpu/nnapi, but can't run on Hexagon DSP device.**
The logs from logcat are as follows:
```
Process: com.elevoc.demo.app.tflitetest, PID: 14450
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.elevoc.demo.app.tflitetest/com.elevoc.demo.app.tflitetest.MainActivity}: java.lang.RuntimeException: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Failed: Failed to prepare graph.
    .
    Node number 3 (TfLiteHexagonDelegate) failed to prepare.
    
    Restored original execution plan after delegate application failure.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3274)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3413)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2020)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7395)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Failed: Failed to prepare graph.
    .
    Node number 3 (TfLiteHexagonDelegate) failed to prepare.
    
    Restored original execution plan after delegate application failure.
        at com.elevoc.demo.app.tflitetest.TfInter.init(TfInter.java:59)
        at com.elevoc.demo.app.tflitetest.TfInter.<init>(TfInter.java:31)
        at com.elevoc.demo.app.tflitetest.MainActivity.onCreate(MainActivity.java:15)
        at android.app.Activity.performCreate(Activity.java:7825)
        at android.app.Activity.performCreate(Activity.java:7814)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3249)
        	... 11 more
     Caused by: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Failed: Failed to prepare graph.
    .
    Node number 3 (TfLiteHexagonDelegate) failed to prepare.
    
    Restored original execution plan after delegate application failure.
        at org.tensorflow.lite.NativeInterpreterWrapper.applyDelegate(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.applyDelegates(NativeInterpreterWrapper.java:530)
        at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:93)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:66)
        at org.tensorflow.lite.NativeInterpreterWrapperExperimental.<init>(NativeInterpreterWrapperExperimental.java:44)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:226)
        at com.elevoc.demo.app.tflitetest.TfInter.init(TfInter.java:57)
        	... 17 more
```

**Comment by Wansh619** [comment]
Hi u am a absolute beginner in open source and I want to contribute can you please provide me resources for working on this issue

**Comment by sachinprasadhs** [comment]
Have you followed this documentation https://www.tensorflow.org/lite/performance/hexagon_delegate regarding supported devices and other details.
