### ISSUE TITLE
RuntimeError: Exporting/importing meta graphs is not supported when eager execution is enabled. No graph exists when eager execution is enabled.

### ISSUE THREAD

**Issue by jackiezhang11** [tensorflow/tensorflow#54339]
2022-02-11 11:05:30.792376: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "01_GenQuadProposals.py", line 82, in <module>
    CNNModel.restoreCNNSess()
  File "/home/dms/SupplementaryMaterials/CodeAndData/Code/QuadProposals/CNNQuadDetector.py", line 92, in restoreCNNSess
    saver = tf.train.import_meta_graph(self.cfg.cornerdet_sess + '.meta', import_scope="cornerdet")
  File "/home/dms/anaconda3/envs/SupplementaryMaterials/lib/python3.8/site-packages/tensorflow/python/training/saver.py", line 1460, in import_meta_graph
    return _import_meta_graph_with_return_elements(meta_graph_or_file,
  File "/home/dms/anaconda3/envs/SupplementaryMaterials/lib/python3.8/site-packages/tensorflow/python/training/saver.py", line 1472, in _import_meta_graph_with_return_elements
    raise RuntimeError("Exporting/importing meta graphs is not supported when "
RuntimeError: Exporting/importing meta graphs is not supported when eager execution is enabled. No graph exists when eager execution is enabled.

**System information**

tensorboard 2.8.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit 1.8.1
tensorflow 2.3.1
tensorflow-estimator 2.3.0
tensorflow-hub 0.12.0
tensorflow-io-gcs-filesystem 0.24.0
tensorflowjs 3.13.0
cuda 10.1
cudnn 7.6
python 3.8

has update import tensorflow. as tf  to import tensorflow.compat.v1 as tf

**Comment by tilakrayal** [comment]
@jackiezhang11 ,
Can you please take a look at this [issue](https://github.com/tensorflow/hub/issues/350) with the same error.Also please try to update to latest tf v2.7 and let us know if the issue still persists.Thanks!
