### ISSUE TITLE
RuntimeError: Exporting/importing meta graphs is not supported when eager execution is enabled. No graph exists when eager execution is enabled.

### ISSUE THREAD

**Issue by jackiezhang11** [tensorflow/tensorflow#54338]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>
2022-02-11 11:05:30.792376: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "01_GenQuadProposals.py", line 82, in <module>
    CNNModel.restoreCNNSess()
  File "/home/dms/SupplementaryMaterials/CodeAndData/Code/QuadProposals/CNNQuadDetector.py", line 92, in restoreCNNSess
    saver = tf.train.import_meta_graph(self.cfg.cornerdet_sess + '.meta', import_scope="cornerdet")
  File "/home/dms/anaconda3/envs/SupplementaryMaterials/lib/python3.8/site-packages/tensorflow/python/training/saver.py", line 1460, in import_meta_graph
    return _import_meta_graph_with_return_elements(meta_graph_or_file,
  File "/home/dms/anaconda3/envs/SupplementaryMaterials/lib/python3.8/site-packages/tensorflow/python/training/saver.py", line 1472, in _import_meta_graph_with_return_elements
    raise RuntimeError("Exporting/importing meta graphs is not supported when "
RuntimeError: Exporting/importing meta graphs is not supported when eager execution is enabled. No graph exists when eager execution is enabled.

**System information**
- TensorFlow version (you are using):
tensorboard                  2.8.0
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow                   2.3.1
tensorflow-estimator         2.3.0
tensorflow-hub               0.12.0
tensorflow-io-gcs-filesystem 0.24.0
tensorflowjs                 3.13.0
cuda                           10.1
cudnn                          7.6
python                         3.8
- Are you willing to contribute it (Yes/No):
Yes

**Describe the feature and the current behavior/state.**

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**

**Comment by jackiezhang11** [comment]
use tf.compat.v1.disable_v2_behavior() to stop all tensorflow2 behaviours  solve this problems.
