### ISSUE TITLE
"iterating over `tf.Tensor` is not allowed" when training object detection model with pyinstaller

### ISSUE THREAD

**Issue by Rayndell** [tensorflow/tensorflow#54346]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows Server 2016
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.2/8
- GPU model and memory: Nvidia GTX 1080 Ti

I am training a detection model with a Python script using the object_detection module (with TF2). The script works perfectly fine when executed with Python (python TrainSuspendedElementsDetection.py ...), apart from a load of deprecation warnings. Problems arise when I try to convert the Python script to an executable with pyinstaller (last version 4.9). When launching the executable an exception occurs at the beginning of the training loop:

Traceback (most recent call last):
  File "TrainSuspendedElementsDetection.py", line 256, in <module>
  File "tensorflow\python\platform\app.py", line 40, in run
  File "absl\app.py", line 303, in run
  File "absl\app.py", line 251, in _run_main
  File "TrainSuspendedElementsDetection.py", line 181, in main
  File "object_detection\model_lib_v2.py", line 678, in train_loop
  File "tensorflow\python\util\traceback_utils.py", line 153, in error_handler
  File "tensorflow\python\util\traceback_utils.py", line 150, in error_handler
  File "tensorflow\python\eager\def_function.py", line 910, in __call__
  File "tensorflow\python\eager\def_function.py", line 958, in _call
  File "tensorflow\python\eager\def_function.py", line 780, in _initialize
  File "tensorflow\python\eager\function.py", line 3157, in _get_concrete_function_internal_garbage_collected
  File "tensorflow\python\eager\function.py", line 3557, in _maybe_define_function
  File "tensorflow\python\eager\function.py", line 3392, in _create_graph_function
  File "tensorflow\python\framework\func_graph.py", line 1143, in func_graph_from_py_func
  File "tensorflow\python\eager\def_function.py", line 672, in wrapped_fn
  File "tensorflow\python\framework\func_graph.py", line 1118, in autograph_handler
  File "tensorflow\python\autograph\impl\api.py", line 440, in converted_call
  File "tensorflow\python\autograph\impl\api.py", line 490, in _fall_back_unconverted
  File "tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
  File "object_detection\model_lib_v2.py", line 659, in _dist_train_step
  File "tensorflow\python\framework\ops.py", line 572, in __iter__
  File "tensorflow\python\framework\ops.py", line 561, in _disallow_iteration
  File "tensorflow\python\framework\ops.py", line 525, in _disallow_when_autograph_unavailable
tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed: AutoGraph is unavailable in this runtime. See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/g3doc/reference/limitations.md#access-to-source-code for more information. 

Attached are:
- TrainSuspendedElementsDetection.py: The source code of the Python script (the problem occurs at line 181 when calling the training loop of the object_detection module)
- pipeline.config: The configuration file of the training process
- TrainSuspendedElementsDetection.spec: the spec file used by pyinstaller
- log.txt: the log file of the pyinstaller output. I saw numerous errors relative to modules not found, but it does not seem to have any impact in the execution of the progra
[pyinstaller.zip](https://github.com/tensorflow/tensorflow/files/8047968/pyinstaller.zip)
m

**Comment by Rayndell** [comment]
Update: I found some workarounds.

1) Decorate the "_dist_train_step" function in model_lib_v2.py in the object_detection module with "@tf.autograph.experimental.do_not_convert". It will apparently avoid to convert the function into a TF graph, but doing this is not satisfying since it makes the training about 10x slower.
2) In the train_loop function of the object_detection module, set the parameter num_steps_per_iteration to 1 (instead of 100), which prevents the dist_train_step function from using a "for" loop, which apparently was the cause of the previous failure. However, I do not know how this parameter will affect the efficiency of the training. If someone could enhance my knowledge with the solution to this mystery is would be greatly appreciated :-)

**Comment by sushreebarsa** [comment]
@Rayndell 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by Rayndell** [comment]
Here is a minimal example (models\research should be added to the PYTHON_PATH environment variable). It works by giving to the pipeline_config_path parameter the config file added in the zip file in the message above, but it should work with any config file from TF2 samples.

```python
import tensorflow as tf
from object_detection import model_lib_v2

tf.config.set_soft_device_placement(True)
strategy = tf.compat.v2.distribute.MirroredStrategy()
with strategy.scope():
	model_lib_v2.train_loop(
			pipeline_config_path=pipeline_config_path,
			model_dir="./Train",
			train_steps=100000,
			use_tpu=False,
			checkpoint_every_n=1000,
			checkpoint_max_to_keep=5,
			record_summaries=False,
			num_steps_per_iteration=100)
```

Note that this code works perfectly fine when executing it within the Pyton environment. Problems arise when converting the program to an executable with pyinstaller. As noted above, it works well when putting num_steps_per_iteration to the value 1, since it skips the "for" loop in the dist_train_step function.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
