### ISSUE TITLE
Error with "tf.keras.layers.Normalization" when using multiple GPU devices

### ISSUE THREAD

**Issue by FalsoMoralista** [tensorflow/tensorflow#54349]
**System information**
Tensorflow 2.7.0 (gpu)
Python 3.8
Linux ubuntu.
### Context:
I am trying to use a normalization layer as demonstrated in load model code below:
The code works normally as expected when removing ```the tf.keras.layers.Normalization``` layer and keeping the Rescaling layer. Therefore i would discard any problem related to input pipeline, tfrecord parsing, incorrect label format, etc...  ***The error occurs at the end of the epoch at validation inference.***

# Edit: 
I found out that the problem is related to running in multiple gpu devices. 
I created this [gist](https://colab.research.google.com/drive/1-6POGaRSpMhTu5gPO2XC_mtLil7eYXa6?usp=sharing) in order to test tensorflow/python versions and everything ran normally. I have even installed the exact same python version (3.8.10) to verify whether it would be the case but worked with no errors. Then, back in the original enviroment I've limited the number of gpu devices to 1 and the code ran normally.

[tfrecords](https://drive.google.com/drive/folders/1iwmkIV93KAwTh3ML0ghcy0tn8u3Ny1wH?usp=sharing) for reproducing.

### Code: 
```Python
def load_and_configure_model(optimizer, loss, metrics, path):
  model = ResNet50V2(include_top=True, weights='imagenet')
  transfer_layer = model.get_layer('avg_pool')
  resnet_submodel = Model(inputs=model.input,outputs=transfer_layer.output)
  model_config = resnet_submodel.get_config()
  
  submodel = model_config['layers']
  submodel.remove(submodel[0]) # Remove the previous input layer
  
  input_layer = keras.Input(shape=(224, 224, 3), dtype='float32',name="input") # Create a new input layer
  normalization = tf.keras.layers.Normalization(mean=[118.662, 119.194, 96.877], variance=[2769.232, 2633.742, 2702.492], axis=-1, dtype='float32')(input_layer)
  rescaling = tf.keras.layers.experimental.preprocessing.Rescaling(1./127.5, offset=-1, dtype='float32')(normalization)  
  
  new_model = Model(inputs=input_layer,outputs=rescaling) # Declare pre-processing model to be merged with the ResNet model.
  new_model_cfg = new_model.get_config() 
      
  new_model_cfg['layers'].extend(submodel) # Merge two models.

  # Replace the previous input layer with the output from the preprocessing model
  # (Connect the preprocessing model to the resnet) 
  output_name = new_model_cfg['layers'][2]['name'] # Get the output layer name (rescaling).
  
  new_model_cfg['layers'][3]['inbound_nodes'] = [[[output_name, 0, 0, {}]]] # Replace last inbound node name with the preprocessing model layer name.  
  
  new_model = new_model.__class__.from_config(new_model_cfg, custom_objects={})  # change custom objects if necessary

  # Set back pre-trained weights on new model
  weights = [layer.get_weights() for layer in resnet_submodel.layers[1:]] # For each layer (after the input_layer) in the original resnet50:
  for layer, weight in zip(new_model.layers[3:], weights): # Set imagenet weights on each new model layer.
      layer.set_weights(weight)

  for layer in new_model.layers[:]:
    layer.trainable = False
  for layer in new_model.layers[:]:      
    trainable = True
    layer.trainable = trainable # Train everything. 

  transfer_layer = new_model.get_layer('avg_pool')
  #dropout = tf.keras.layers.Dropout(rate=0.3)(transfer_layer.output)
  species = Dense(1000, activation='softmax', dtype='float32',name='species')(transfer_layer.output) # Specify dtype for handling mixed precision specifications.

  model = keras.Model(
      inputs=[new_model.inputs],
      outputs=[species],
  )
  if not path == None :
    model.load_weights(path)
  model.compile(optimizer=optimizer, loss=loss, metrics=metrics)
  return model
```

obs: the same normalization/scaling pipeline works just fine and as expected when creating a model cosisting of these two layers only as exemplified below:

```Python
normalization = tf.keras.layers.Normalization(mean=[118.662, 119.194, 96.877], variance=[2769.232, 2633.742, 2702.492], axis=-1)(input_layer)

rescaling = tf.keras.layers.experimental.preprocessing.Rescaling(1./127.5, offset=-1)(normalization)
model_2 = Model(inputs=input_layer,outputs=rescaling)

pred = model_2.predict(img)
pred = tf.cast(pred, tf.uint8)
pred = tf.squeeze(pred,axis=0)
pred = tf.io.encode_jpeg(pred)

fname = tf.constant('norm_then_scale.jpg')
fwrite = tf.io.write_file(fname, pred)


```

### Traceback:
```
Epoch 1/70
2022-02-11 17:12:35.280711: I tensorflow/stream_executor/cuda/cuda_dnn.cc:366] Loaded cuDNN version 8302
2022-02-11 17:12:35.671694: I tensorflow/stream_executor/cuda/cuda_dnn.cc:366] Loaded cuDNN version 8302
2022-02-11 17:12:37.630704: I tensorflow/stream_executor/cuda/cuda_blas.cc:1774] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
 95/100 [===========================>..] - ETA: 2s - loss: 6.9175 - categori2022-02-11 17:13:46.316950: W tensorflow/core/framework/op_kernel.cc:1733] INVALID_ARGUMENT: required broadcastable shapes
Traceback (most recent call last):
  File "flat_resnet50.py", line 263, in <module>
    history = train_model(train_path, validation_path, epochs, steps_per_epoch, resnet_50V2)
  File "flat_resnet50.py", line 82, in train_model
    history = model.fit(x=train_dataset,
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/execute.py", line 58, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: 3 root error(s) found.
  (0) INVALID_ARGUMENT:  required broadcastable shapes
	 [[node replica_1/model_2/normalization/sub
 (defined at /usr/local/lib/python3.8/dist-packages/keras/layers/preprocessing/normalization.py:257)
]]
	 [[div_no_nan/ReadVariableOp_1/_62]]
  (1) INVALID_ARGUMENT:  required broadcastable shapes
	 [[node replica_1/model_2/normalization/sub
 (defined at /usr/local/lib/python3.8/dist-packages/keras/layers/preprocessing/normalization.py:257)
]]
	 [[div_no_nan/AddN/_76]]
  (2) INVALID_ARGUMENT:  required broadcastable shapes
	 [[node replica_1/model_2/normalization/sub
 (defined at /usr/local/lib/python3.8/dist-packages/keras/layers/preprocessing/normalization.py:257)
]]
0 successful operations.
0 derived errors ignored. [Op:__inference_test_function_65650]

Errors may have originated from an input operation.
Input Source operations connected to node replica_1/model_2/normalization/sub:
In[0] cond/Identity_1 (defined at /usr/local/lib/python3.8/dist-packages/keras/engine/training.py:1355)	
In[1] model_2/normalization/sub/y:

Operation defined at: (most recent call last)
>>>   File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
>>>     self._bootstrap_inner()
>>> 
>>>   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
>>>     self.run()
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1349, in run_step
>>>     outputs = model.test_step(data)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1303, in test_step
>>>     y_pred = self(x, training=False)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/base_layer.py", line 1083, in __call__
>>>     outputs = call_fn(inputs, *args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 92, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/functional.py", line 451, in call
>>>     return self._run_internal_graph(
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/functional.py", line 589, in _run_internal_graph
>>>     outputs = node.layer(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/base_layer.py", line 1083, in __call__
>>>     outputs = call_fn(inputs, *args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 92, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/layers/preprocessing/normalization.py", line 257, in call
>>>     return ((inputs - self.mean) /
>>> 

Input Source operations connected to node replica_1/model_2/normalization/sub:
In[0] cond/Identity_1 (defined at /usr/local/lib/python3.8/dist-packages/keras/engine/training.py:1355)	
In[1] model_2/normalization/sub/y:

Operation defined at: (most recent call last)
>>>   File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
>>>     self._bootstrap_inner()
>>> 
>>>   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
>>>     self.run()
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1349, in run_step
>>>     outputs = model.test_step(data)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1303, in test_step
>>>     y_pred = self(x, training=False)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/base_layer.py", line 1083, in __call__
>>>     outputs = call_fn(inputs, *args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 92, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/functional.py", line 451, in call
>>>     return self._run_internal_graph(
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/functional.py", line 589, in _run_internal_graph
>>>     outputs = node.layer(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/base_layer.py", line 1083, in __call__
>>>     outputs = call_fn(inputs, *args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 92, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/layers/preprocessing/normalization.py", line 257, in call
>>>     return ((inputs - self.mean) /
>>> 

Input Source operations connected to node replica_1/model_2/normalization/sub:
In[0] cond/Identity_1 (defined at /usr/local/lib/python3.8/dist-packages/keras/engine/training.py:1355)	
In[1] model_2/normalization/sub/y:

Operation defined at: (most recent call last)
>>>   File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
>>>     self._bootstrap_inner()
>>> 
>>>   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
>>>     self.run()
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1349, in run_step
>>>     outputs = model.test_step(data)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1303, in test_step
>>>     y_pred = self(x, training=False)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/base_layer.py", line 1083, in __call__
>>>     outputs = call_fn(inputs, *args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 92, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/functional.py", line 451, in call
>>>     return self._run_internal_graph(
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/functional.py", line 589, in _run_internal_graph
>>>     outputs = node.layer(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/base_layer.py", line 1083, in __call__
>>>     outputs = call_fn(inputs, *args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 92, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/layers/preprocessing/normalization.py", line 257, in call
>>>     return ((inputs - self.mean) /
>>> 

Function call stack:
test_function -> test_function -> test_function

Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 27, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 35, in <module>
    apt_pkg.init_config()
apt_pkg.Error: E:Syntax error /etc/apt/apt.conf.d/20auto-upgrades:6: Extra junk at end of file

Original exception was:
Traceback (most recent call last):
  File "flat_resnet50.py", line 263, in <module>
    history = train_model(train_path, validation_path, epochs, steps_per_epoch, resnet_50V2)
  File "flat_resnet50.py", line 82, in train_model
    history = model.fit(x=train_dataset,
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/execute.py", line 58, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: 3 root error(s) found.
  (0) INVALID_ARGUMENT:  required broadcastable shapes
	 [[node replica_1/model_2/normalization/sub
 (defined at /usr/local/lib/python3.8/dist-packages/keras/layers/preprocessing/normalization.py:257)
]]
	 [[div_no_nan/ReadVariableOp_1/_62]]
  (1) INVALID_ARGUMENT:  required broadcastable shapes
	 [[node replica_1/model_2/normalization/sub
 (defined at /usr/local/lib/python3.8/dist-packages/keras/layers/preprocessing/normalization.py:257)
]]
	 [[div_no_nan/AddN/_76]]
  (2) INVALID_ARGUMENT:  required broadcastable shapes
	 [[node replica_1/model_2/normalization/sub
 (defined at /usr/local/lib/python3.8/dist-packages/keras/layers/preprocessing/normalization.py:257)
]]
0 successful operations.
0 derived errors ignored. [Op:__inference_test_function_65650]

Errors may have originated from an input operation.
Input Source operations connected to node replica_1/model_2/normalization/sub:
In[0] cond/Identity_1 (defined at /usr/local/lib/python3.8/dist-packages/keras/engine/training.py:1355)	
In[1] model_2/normalization/sub/y:

Operation defined at: (most recent call last)
>>>   File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
>>>     self._bootstrap_inner()
>>> 
>>>   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
>>>     self.run()
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1349, in run_step
>>>     outputs = model.test_step(data)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1303, in test_step
>>>     y_pred = self(x, training=False)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/base_layer.py", line 1083, in __call__
>>>     outputs = call_fn(inputs, *args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 92, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/functional.py", line 451, in call
>>>     return self._run_internal_graph(
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/functional.py", line 589, in _run_internal_graph
>>>     outputs = node.layer(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/base_layer.py", line 1083, in __call__
>>>     outputs = call_fn(inputs, *args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 92, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/layers/preprocessing/normalization.py", line 257, in call
>>>     return ((inputs - self.mean) /
>>> 

Input Source operations connected to node replica_1/model_2/normalization/sub:
In[0] cond/Identity_1 (defined at /usr/local/lib/python3.8/dist-packages/keras/engine/training.py:1355)	
In[1] model_2/normalization/sub/y:

Operation defined at: (most recent call last)
>>>   File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
>>>     self._bootstrap_inner()
>>> 
>>>   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
>>>     self.run()
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1349, in run_step
>>>     outputs = model.test_step(data)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1303, in test_step
>>>     y_pred = self(x, training=False)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/base_layer.py", line 1083, in __call__
>>>     outputs = call_fn(inputs, *args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 92, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/functional.py", line 451, in call
>>>     return self._run_internal_graph(
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/functional.py", line 589, in _run_internal_graph
>>>     outputs = node.layer(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/base_layer.py", line 1083, in __call__
>>>     outputs = call_fn(inputs, *args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 92, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/layers/preprocessing/normalization.py", line 257, in call
>>>     return ((inputs - self.mean) /
>>> 

Input Source operations connected to node replica_1/model_2/normalization/sub:
In[0] cond/Identity_1 (defined at /usr/local/lib/python3.8/dist-packages/keras/engine/training.py:1355)	
In[1] model_2/normalization/sub/y:

Operation defined at: (most recent call last)
>>>   File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
>>>     self._bootstrap_inner()
>>> 
>>>   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
>>>     self.run()
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1349, in run_step
>>>     outputs = model.test_step(data)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1303, in test_step
>>>     y_pred = self(x, training=False)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/base_layer.py", line 1083, in __call__
>>>     outputs = call_fn(inputs, *args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 92, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/functional.py", line 451, in call
>>>     return self._run_internal_graph(
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/functional.py", line 589, in _run_internal_graph
>>>     outputs = node.layer(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/engine/base_layer.py", line 1083, in __call__
>>>     outputs = call_fn(inputs, *args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 92, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.8/dist-packages/keras/layers/preprocessing/normalization.py", line 257, in call
>>>     return ((inputs - self.mean) /
>>> 

Function call stack:
test_function -> test_function -> test_function

100/100 [==============================] - ETA: 0s - loss: 6.9095 - categorical_accuracy: 0.0055
```

**Comment by sushreebarsa** [comment]
@FalsoMoralista 
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!
