### ISSUE TITLE
[v2.8.0]: Cross compiling libtensorflow.so for ARM64 fails

### ISSUE THREAD

**Issue by sdeoras** [tensorflow/tensorflow#54353]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: None
- TensorFlow installed from (source or binary): source
- TensorFlow version: v2.8.0
- Python version: 3.8.8
- Installed using virtualenv? pip? conda?: Building from source, cross-compiling for Raspberry Pi
- Bazel version (if compiling from source): Automatically done by build script via docker container
- GCC/Compiler version (if compiling from source): Automatically selected by build script via docker container
- CUDA/cuDNN version: None
- GPU model and memory: None

**Describe the problem**
I am trying to cross-compile `libtensorflow.so` to use on ARM64, but the build is failing at several steps. More info below

**Provide the exact sequence of commands / steps that you executed before running into the problem**
After downloading code and checking out `v2.8.0`, I ran following command:
```
tensorflow/tools/ci_build/ci_build.sh PI \
    tensorflow/tools/ci_build/pi/build_raspberry_pi.sh
```
This command fails due to python3.6 not being available in the docker container. To fix this issue, I installed python3.6 via following entries in the `Dockerfile` and a few other modifications as shown below. Without these modification the build would fail.
```
└─ $ ▶ git diff
diff --git a/tensorflow/tools/ci_build/Dockerfile.pi b/tensorflow/tools/ci_build/Dockerfile.pi
index 53589774291..8a021f3434e 100644
--- a/tensorflow/tools/ci_build/Dockerfile.pi
+++ b/tensorflow/tools/ci_build/Dockerfile.pi
@@ -2,6 +2,20 @@ FROM ubuntu:14.04
 
 LABEL maintainer="Jan Prach <jendap@google.com>"
 
+# install python 3.6
+RUN apt-get update
+RUN apt-get install build-essential libpq-dev libssl-dev openssl libffi-dev zlib1g-dev -y
+RUN apt-get install python3-pip python3-dev -y
+RUN apt install software-properties-common -y
+RUN apt-get install wget -y
+RUN wget https://www.python.org/ftp/python/3.6.3/Python-3.6.3.tgz
+RUN tar -xvf Python-3.6.3.tgz
+WORKDIR /Python-3.6.3
+RUN ./configure --enable-optimizations
+RUN make -j8
+RUN make install
+WORKDIR /
+
 # Copy and run the install scripts.
 COPY install/*.sh /install/
 RUN /install/install_bootstrap_deb_packages.sh
diff --git a/tensorflow/tools/ci_build/install/install_auditwheel.sh b/tensorflow/tools/ci_build/install/install_auditwheel.sh
index c84bdf4e2ec..55e9f297f06 100755
--- a/tensorflow/tools/ci_build/install/install_auditwheel.sh
+++ b/tensorflow/tools/ci_build/install/install_auditwheel.sh
@@ -27,7 +27,7 @@ patchelf_location=$(which patchelf)
 if [[ -z "$patchelf_location" ]]; then
   set -e
   # Install patchelf from source (it does not come with trusty package)
-  wget https://nixos.org/releases/patchelf/patchelf-0.9/patchelf-0.9.tar.bz2
+  wget --no-check-certificate https://nixos.org/releases/patchelf/patchelf-0.9/patchelf-0.9.tar.bz2
   tar xfa patchelf-0.9.tar.bz2
   cd patchelf-0.9
   ./configure --prefix=/usr/local
diff --git a/tensorflow/tools/ci_build/install/install_pip_packages.sh b/tensorflow/tools/ci_build/install/install_pip_packages.sh
index 18e0bf73d3a..305a8c28760 100755
--- a/tensorflow/tools/ci_build/install/install_pip_packages.sh
+++ b/tensorflow/tools/ci_build/install/install_pip_packages.sh
@@ -17,7 +17,8 @@
 set -e
 
 # Get the latest version of pip so it recognize manylinux2010
-wget https://bootstrap.pypa.io/get-pip.py
+#wget https://bootstrap.pypa.io/get-pip.py
+wget https://bootstrap.pypa.io/pip/3.6/get-pip.py
 python3.6 get-pip.py
 rm -f get-pip.py
```

At this point the build proceeds up to a point where it starts to compile tensorflow code. However, I ran into following issues:
```
INFO: Repository aarch64_compiler instantiated at:
  /workspace/WORKSPACE:15:14: in <toplevel>
  /workspace/tensorflow/workspace2.bzl:888:21: in workspace
  /workspace/tensorflow/workspace2.bzl:208:20: in _tf_repositories
  /workspace/third_party/repo.bzl:128:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  /workspace/third_party/repo.bzl:81:35: in <toplevel>
ERROR: /workspace/tensorflow/core/util/BUILD:379:24: //tensorflow/core/util:version_info_gen depends on @local_config_git//:gen/spec.json in repository @local_config_git which failed to fetch. no such package '@local_config_git//': Git Configuration Error: Traceback (most recent call last):
  File "/home/sdeoras/Downloads/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_sdeoras/eab0d61a99b6696edb3d2aff87b585e8/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 28, in <module>
    from builtins import bytes  # pylint: disable=redefined-builtin
ImportError: No module named builtins

ERROR: /workspace/tensorflow/core/util/BUILD:379:24: //tensorflow/core/util:version_info_gen depends on @local_config_git//:gen/head in repository @local_config_git which failed to fetch. no such package '@local_config_git//': Git Configuration Error: Traceback (most recent call last):
  File "/home/sdeoras/Downloads/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_sdeoras/eab0d61a99b6696edb3d2aff87b585e8/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 28, in <module>
    from builtins import bytes  # pylint: disable=redefined-builtin
ImportError: No module named builtins

ERROR: /workspace/tensorflow/core/util/BUILD:379:24: //tensorflow/core/util:version_info_gen depends on @local_config_git//:gen/branch_ref in repository @local_config_git which failed to fetch. no such package '@local_config_git//': Git Configuration Error: Traceback (most recent call last):
  File "/home/sdeoras/Downloads/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_sdeoras/eab0d61a99b6696edb3d2aff87b585e8/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 28, in <module>
    from builtins import bytes  # pylint: disable=redefined-builtin
ImportError: No module named builtins

ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Analysis failed
INFO: Elapsed time: 74.009s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (375 packages loaded, 10502 targets configured)
FAILED: Build did NOT complete successfully (375 packages loaded, 10502 targets configured)
```

Any recommendations on what to do to be able to build `libtensorflow.so` for ARM64? Alternatively, if a pre-compiled library file exists what is a download location link? Also should I be building a previous version, if so, which one?

**Comment by mohantym** [comment]
Hi @sdeoras ! Can you check these two threads on installing TFLite on ARM64 boards? Link[ 1](https://www.tensorflow.org/lite/guide/build_arm), [2](https://github.com/PINTO0309/Tensorflow-bin#usage).

**Comment by sdeoras** [comment]
hi folks, i was able to build c-lib using bazel. we can close this bug if needed. thanks.
