### ISSUE TITLE
huggingface pre_trained model loading takes full gpu memory

### ISSUE THREAD

**Issue by alanpurple** [tensorflow/tensorflow#54582]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):  N/A
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 11 x64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):  2.8.0
- Python version: 3.9.7
- Bazel version (if compiling from source): 4.2.1
- GCC/Compiler version (if compiling from source): visual studio 2019
- CUDA/cuDNN version: 11.6/8.3.2
- GPU model and memory: RTX3090 24GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
load from pre-trained transformer takes full gpu memory, so oom happens after training started
**Describe the expected behavior**
appropriate memory allocation

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): yes
- Briefly describe your candidate solution(if contributing): add options for loading pre-trained model

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

with kaggle feedback-prize data
https://www.kaggle.com/c/feedback-prize-2021/data
this code
```
import os
from tqdm import tqdm,trange
import tensorflow as tf
from tensorflow.keras import layers,Model,Input,Sequential,metrics,regularizers,optimizers,losses,activations,callbacks
from transformers import AutoTokenizer,AutoConfig,TFAutoModel
import pandas as pd
import numpy as np
from iterstrat.ml_stratifiers import MultilabelStratifiedKFold
from copy import copy,deepcopy

VER=12
EPOCHS=5
N_SPLITS=5
MAX_LEN=1024
NUM_ATTENTION_HEADS=16
ROBERTA_LARGE_PATH='../../pretrained/transformers/roberta-large/'
LRS = [1e-4, 1e-4, 1e-4, 1e-5, 1e-5,1e-5]
RUN_TRAINING=False

tokenizer=AutoTokenizer.from_pretrained(ROBERTA_LARGE_PATH+'auto_tokenizer')
config=AutoConfig.from_pretrained(ROBERTA_LARGE_PATH+'auto_config')

backbone=TFAutoModel.from_pretrained('roberta-large',config=config)

FEEDBACK_DATA_PATH='../../mldata/Feedback_Prize/'
train_df=pd.read_csv(FEEDBACK_DATA_PATH+'train.csv')

N_ID=train_df.id.nunique()
IDS=train_df.id.unique()

discourse_types=['Lead','Position','Evidence','Claim','Concluding Statement','Counterclaim','Rebuttal']
target_map = {k:i for i,k in enumerate(discourse_types)}

targets=np.load(f'../kaggle/encoded/targets_{MAX_LEN}.npy',allow_pickle=False)
train_tokens=np.load(f'../kaggle/encoded/tokens_{MAX_LEN}.npy',allow_pickle=False)
train_attention=np.load(f'../kaggle/encoded/attention_{MAX_LEN}.npy',allow_pickle=False)

test_files=os.listdir('../../mldata/Feedback_Prize/test/')
TEST_IDS=[f.replace('.txt','') for f in test_files if 'txt' in f]
print('There are',len(TEST_IDS),'test texts.')
test_tokens=np.zeros((len(TEST_IDS),MAX_LEN),dtype=np.int32)
test_attention=np.zeros((len(TEST_IDS),MAX_LEN),dtype=np.int32)
for i,id in enumerate(TEST_IDS):
    name=f'../../mldata/Feedback_Prize/test/{id}.txt'
    txt=open(name,'r').read()
    tokens=tokenizer.encode_plus(txt,max_length=MAX_LEN,padding='max_length',truncation=True,return_offsets_mapping=True)
    test_tokens[i]=tokens['input_ids']
    test_attention[i]=tokens['attention_mask']

def build_model():
    tokens=Input((MAX_LEN,),name='tokens',dtype=tf.int32)
    attention=Input((MAX_LEN,),name='attention',dtype=tf.int32)
    x=backbone(tokens,attention_mask=attention)
    x1=layers.Dropout(0.1)(x[0])
    x=layers.Dense(15,activation='softmax',dtype=tf.float32)(x1)
    model=Model(inputs=[tokens,attention],outputs=x)
    model.compile(optimizers.Adam(1e-4),losses.CategoricalCrossentropy(),[metrics.CategoricalAccuracy()])
    return model

discourse_types_ext=copy(discourse_types)
discourse_types_ext.append('blank')

def get_preds(dataset = 'train', verbose = True, text_ids = None, preds = None):
    all_predictions = []
    for id_num in range(len(preds)):
        if (id_num % 100 == 0) & (verbose): print(id_num, ', ', end = '')
        n = text_ids[id_num]
        name = f'../input/feedback-prize-2021/{dataset}/{n}.txt'
        txt = open(name, 'r').read()
        tokens = tokenizer.encode_plus(txt, max_length = MAX_LEN, padding = 'max_length', truncation = True, return_offsets_mapping = True)
        off = tokens['offset_mapping']
        w = []
        blank = True
        for i in range(len(txt)):
            if (txt[i] != ' ') & (txt[i] != '\n') & (blank == True):
                w.append(i)
                blank = False
            elif (txt[i] == ' ') | (txt[i] == '\n'):
                blank = True
        w.append(1e6)
        word_map = -1 * np.ones(MAX_LEN, dtype = 'int32')
        w_i = 0
        for i in range(len(off)):
            if off[i][1] == 0: continue
            while off[i][0] >= w[w_i + 1]: w_i += 1
            word_map[i] = int(w_i)
        pred = preds[id_num,] / 2.0
        i = 0
        while i < MAX_LEN:
            prediction = []
            start = pred[i]
            if start in [0, 1, 2, 3, 4, 5, 6, 7]:
                prediction.append(word_map[i])
                i += 1
                if i >= MAX_LEN: break
                while pred[i] == start + 0.5:
                    if not word_map[i] in prediction: prediction.append(word_map[i])
                    i += 1
                    if i >= MAX_LEN: break
            else: i += 1
            prediction = [x for x in prediction if x != -1]
            if len(prediction) > 4: all_predictions.append((n, discourse_types_ext[int(start)], ' '.join([str(x) for x in prediction])))

    # MAKE DATAFRAME
    df = pd.DataFrame(all_predictions)
    df.columns = ['id', 'class', 'predictionstring']
    return df

def calc_overlap(row):
    set_pred = set(row.predictionstring_pred.split(' '))
    set_gt = set(row.predictionstring_gt.split(' '))
    len_gt = len(set_gt)
    len_pred = len(set_pred)
    inter = len(set_gt.intersection(set_pred))
    overlap_1 = inter / len_gt
    overlap_2 = inter / len_pred
    return [overlap_1, overlap_2]

def score_feedback_comp(pred_df, gt_df):
    gt_df = gt_df[['id', 'discourse_type', 'predictionstring']].reset_index(drop = True).copy()
    pred_df = pred_df[['id', 'class', 'predictionstring']].reset_index(drop = True).copy()
    pred_df['pred_id'] = pred_df.index
    gt_df['gt_id'] = gt_df.index
    joined = pred_df.merge(gt_df, left_on = ['id', 'class'], right_on = ['id', 'discourse_type'], how = 'outer', suffixes = ('_pred', '_gt'))
    joined['predictionstring_gt'] = joined['predictionstring_gt'].fillna(' ')
    joined['predictionstring_pred'] = joined['predictionstring_pred'].fillna(' ')
    joined['overlaps'] = joined.apply(calc_overlap, axis=1)
    joined['overlap1'] = joined['overlaps'].apply(lambda x: eval(str(x))[0])
    joined['overlap2'] = joined['overlaps'].apply(lambda x: eval(str(x))[1])
    joined['potential_TP'] = (joined['overlap1'] >= 0.5) & (joined['overlap2'] >= 0.5)
    joined['max_overlap'] = joined[['overlap1','overlap2']].max(axis=1)
    tp_pred_ids = joined.query('potential_TP').sort_values('max_overlap', ascending=False).groupby(['id','predictionstring_gt']).first()['pred_id'].values
    fp_pred_ids = [p for p in joined['pred_id'].unique() if p not in tp_pred_ids]
    matched_gt_ids = joined.query('potential_TP')['gt_id'].unique()
    unmatched_gt_ids = [c for c in joined['gt_id'].unique() if c not in matched_gt_ids]
    TP = len(tp_pred_ids)
    FP = len(fp_pred_ids)
    FN = len(unmatched_gt_ids)
    my_f1_score = TP / (TP + 0.5*(FP+FN))
    return my_f1_score

EPOCHS=6

all_scores=[]
oof_preds=np.zeros((N_ID,15))
test_preds=np.zeros((len(TEST_IDS),MAX_LEN,15))
for fold,(train_idx,valid_idx) in enumerate(MultilabelStratifiedKFold(n_splits=N_SPLITS,shuffle=True,random_state=777).split(train_tokens,targets[:,0,:])):
    print('#'*25)
    print('### FOLD %i' % (fold + 1))
    print('#'*25)
    
    model=build_model()
    
    def lrfn(epoch):
        return LRS[epoch]
    
    model.fit([train_tokens[train_idx],train_attention[train_idx]],targets[train_idx],validation_data=([train_tokens[valid_idx],train_attention[valid_idx]],targets[valid_idx]),
                callbacks=[callbacks.LearningRateScheduler(lrfn,verbose=True),callbacks.ModelCheckpoint('models/%s-roberta-%i.tf'%(VER,fold),monitor='val_loss',
                                                                                                        save_best_only=True,save_weights_only=True)],
                epochs=EPOCHS,batch_size=8,verbose=1)
    pred=model.predict([train_tokens[valid_idx],train_attention[valid_idx]],batch_size=4,verbose=1)
    print(pred.shape)
    print('predicting OOF...')
    oof=get_preds(dataset='train',verbose=True,text_ids=IDS[valid_idx],preds=np.argmax(pred,axis=-1))
    f1s=[]
    CLASSES=oof['class'].unique()
    for c in CLASSES:
        pred_df = oof.loc[oof['class'] == c].copy()
        valid = train_df.loc[train_df.id.isin(IDS[valid_idx])]
        gt_df = valid.loc[valid['discourse_type'] == c].copy()
        f1 = score_feedback_comp(pred_df, gt_df)
        print(c, f1)
        f1s.append(f1)
    print()
    print('Fold score: ', np.mean(f1s))
    
    test_preds+=model.predict([test_tokens,test_attention],batch_size=4,verbose=1)/N_SPLITS
```

error
```
2022-02-25 20:42:31.859917: I tensorflow/core/common_runtime/bfc_allocator.cc:1071]      Summary of in-use Chunks by size:
2022-02-25 20:42:31.859950: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 131 Chunks of size 256 totalling 32.8KiB
2022-02-25 20:42:31.859978: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 1280 totalling 1.2KiB
2022-02-25 20:42:31.860006: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 3072 totalling 3.0KiB
2022-02-25 20:42:31.860033: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 3840 totalling 3.8KiB
2022-02-25 20:42:31.860061: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 655 Chunks of size 4096 totalling 2.56MiB
2022-02-25 20:42:31.860089: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 4352 totalling 4.2KiB
2022-02-25 20:42:31.860117: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 4864 totalling 4.8KiB
2022-02-25 20:42:31.860145: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 7168 totalling 7.0KiB
2022-02-25 20:42:31.860173: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 66 Chunks of size 16384 totalling 1.03MiB
2022-02-25 20:42:31.860201: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 19200 totalling 18.8KiB
2022-02-25 20:42:31.860228: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 2 Chunks of size 20480 totalling 40.0KiB
2022-02-25 20:42:31.860256: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 24576 totalling 24.0KiB
2022-02-25 20:42:31.860284: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 28672 totalling 28.0KiB
2022-02-25 20:42:31.860311: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 32256 totalling 31.5KiB
2022-02-25 20:42:31.860339: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 32 Chunks of size 32768 totalling 1.00MiB
2022-02-25 20:42:31.860367: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 40960 totalling 40.0KiB
2022-02-25 20:42:31.860394: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 48896 totalling 47.8KiB
2022-02-25 20:42:31.860422: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 3 Chunks of size 61440 totalling 180.0KiB
2022-02-25 20:42:31.860450: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 65536 totalling 64.0KiB
2022-02-25 20:42:31.860478: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 491520 totalling 480.0KiB
2022-02-25 20:42:31.860506: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 2 Chunks of size 2105344 totalling 4.02MiB
2022-02-25 20:42:31.860534: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 289 Chunks of size 4194304 totalling 1.13GiB
2022-02-25 20:42:31.860562: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 4578560 totalling 4.37MiB
2022-02-25 20:42:31.860590: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 139 Chunks of size 16777216 totalling 2.17GiB
2022-02-25 20:42:31.860618: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 20971520 totalling 20.00MiB
2022-02-25 20:42:31.860646: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 21258240 totalling 20.27MiB
2022-02-25 20:42:31.860674: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 25530368 totalling 24.35MiB
2022-02-25 20:42:31.860702: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 27955200 totalling 26.66MiB
2022-02-25 20:42:31.860730: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 29360128 totalling 28.00MiB
2022-02-25 20:42:31.860758: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 89 Chunks of size 33554432 totalling 2.78GiB
2022-02-25 20:42:31.860787: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 39534592 totalling 37.70MiB
2022-02-25 20:42:31.860815: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 40222720 totalling 38.36MiB
2022-02-25 20:42:31.860843: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 28 Chunks of size 134217728 totalling 3.50GiB
2022-02-25 20:42:31.860872: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 3 Chunks of size 205885440 totalling 589.04MiB
2022-02-25 20:42:31.860901: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 21 Chunks of size 536870912 totalling 10.50GiB
2022-02-25 20:42:31.860928: I tensorflow/core/common_runtime/bfc_allocator.cc:1078] Sum Total of in-use chunks: 20.86GiB2022-02-25 20:42:31.860953: I tensorflow/core/common_runtime/bfc_allocator.cc:1080] total_region_allocated_bytes_: 22729785344 memory_limit_: 22729785344 available bytes: 0 curr_region_allocation_bytes_: 45459570688
2022-02-25 20:42:31.860988: I tensorflow/core/common_runtime/bfc_allocator.cc:1086] Stats:
Limit:                     22729785344
InUse:                     22400043008
MaxInUse:                  22433597440
NumAllocs:                        5211
MaxAllocSize:                536870912
Reserved:                            0
PeakReserved:                        0
LargestFreeBlock:                    0

2022-02-25 20:42:31.861075: W tensorflow/core/common_runtime/bfc_allocator.cc:474] ***************************************************************************************************_
2022-02-25 20:42:31.861123: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at matmul_op_impl.h:681 : RESOURCE_EXHAUSTED: OOM when allocating tensor with shape[8,16,1024,1024] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "D:\repo\robertatraining\robertatraining.py", line 157, in <module>
    model.fit([train_tokens[train_idx],train_attention[train_idx]],targets[train_idx],validation_data=([train_tokens[valid_idx],train_attention[valid_idx]],targets[valid_idx]),
  File "C:\Users\alanp\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\alanp\anaconda3\lib\site-packages\tensorflow\python\eager\execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.ResourceExhaustedError: Graph execution error:

Detected at node 'model/tf_roberta_model/roberta/encoder/layer_._7/attention/self/MatMul' defined at (most recent call last):
    File "D:\repo\robertatraining\robertatraining.py", line 157, in <module>
      model.fit([train_tokens[train_idx],train_attention[train_idx]],targets[train_idx],validation_data=([train_tokens[valid_idx],train_attention[valid_idx]],targets[valid_idx]),
    File "C:\Users\alanp\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\alanp\anaconda3\lib\site-packages\keras\engine\training.py", line 1384, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\alanp\anaconda3\lib\site-packages\keras\engine\training.py", line 1021, in train_function
      return step_function(self, iterator)
    File "C:\Users\alanp\anaconda3\lib\site-packages\keras\engine\training.py", line 1010, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\alanp\anaconda3\lib\site-packages\keras\engine\training.py", line 1000, in run_step
      outputs = model.train_step(data)
    File "C:\Users\alanp\anaconda3\lib\site-packages\keras\engine\training.py", line 859, in train_step
      y_pred = self(x, training=True)
    File "C:\Users\alanp\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\alanp\anaconda3\lib\site-packages\keras\engine\base_layer.py", line 1096, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "C:\Users\alanp\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\alanp\anaconda3\lib\site-packages\keras\engine\functional.py", line 451, in call
      return self._run_internal_graph(
    File "C:\Users\alanp\anaconda3\lib\site-packages\keras\engine\functional.py", line 589, in _run_internal_graph
      outputs = node.layer(*args, **kwargs)
    File "C:\Users\alanp\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\alanp\anaconda3\lib\site-packages\keras\engine\base_layer.py", line 1096, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "C:\Users\alanp\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\alanp\anaconda3\lib\site-packages\transformers\models\roberta\modeling_tf_roberta.py", line 996, in call
      outputs = self.roberta(
    File "C:\Users\alanp\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\alanp\anaconda3\lib\site-packages\keras\engine\base_layer.py", line 1096, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "C:\Users\alanp\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\alanp\anaconda3\lib\site-packages\transformers\models\roberta\modeling_tf_roberta.py", line 755, in call
      encoder_outputs = self.encoder(
    File "C:\Users\alanp\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\alanp\anaconda3\lib\site-packages\keras\engine\base_layer.py", line 1096, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "C:\Users\alanp\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\alanp\anaconda3\lib\site-packages\transformers\models\roberta\modeling_tf_roberta.py", line 528, in call
      for i, layer_module in enumerate(self.layer):
    File "C:\Users\alanp\anaconda3\lib\site-packages\transformers\models\roberta\modeling_tf_roberta.py", line 534, in call
      layer_outputs = layer_module(
    File "C:\Users\alanp\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\alanp\anaconda3\lib\site-packages\keras\engine\base_layer.py", line 1096, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "C:\Users\alanp\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\alanp\anaconda3\lib\site-packages\transformers\models\roberta\modeling_tf_roberta.py", line 443, in call
      self_attention_outputs = self.attention(
    File "C:\Users\alanp\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\alanp\anaconda3\lib\site-packages\keras\engine\base_layer.py", line 1096, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "C:\Users\alanp\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\alanp\anaconda3\lib\site-packages\transformers\models\roberta\modeling_tf_roberta.py", line 356, in call
      self_outputs = self.self_attention(
    File "C:\Users\alanp\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\alanp\anaconda3\lib\site-packages\keras\engine\base_layer.py", line 1096, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "C:\Users\alanp\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\alanp\anaconda3\lib\site-packages\transformers\models\roberta\modeling_tf_roberta.py", line 284, in call
      attention_scores = tf.matmul(query_layer, key_layer, transpose_b=True)
Node: 'model/tf_roberta_model/roberta/encoder/layer_._7/attention/self/MatMul'
OOM when allocating tensor with shape[8,16,1024,1024] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node model/tf_roberta_model/roberta/encoder/layer_._7/attention/self/MatMul}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.
 [Op:__inference_train_function_53102]
```

[8,16,1024,1024] with tf.fload32 is just 512MB total, it doesn't make sense

just with "from_pretrained", gpu allocate almost all of its memory
![image](https://user-images.githubusercontent.com/4515120/155709476-168583f7-e1cc-495b-8ab3-2a218934d7ac.png)

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by mohantym** [comment]
Hi @alanpurple ! Can you try again after reducing max_length and input size /add more pooling layers in build_model  aside constraining [memory growth](https://www.tensorflow.org/api_docs/python/tf/config/experimental/set_memory_growth) in Gpu. You can also use tf.data to set pipe line to load the data in batches.  Attaching relevant [thread](https://stackoverflow.com/questions/63452525/oom-when-allocating-tensor-with-shape1-48-48-1024-and-type-float-on-joblocal) for reference.Thanks!

**Comment by alanpurple** [comment]
@mohantym 
same with tf.data.Dataset
```
train_ds=tf.data.Dataset.from_tensor_slices(((train_tokens[train_idx],train_attention[train_idx]),targets[train_idx])).batch(14)
        valid_ds=tf.data.Dataset.from_tensor_slices(((train_tokens[valid_idx],train_attention[valid_idx]),targets[valid_idx])).batch(4)
        model.fit(train_ds,validation_data=valid_ds,
                  callbacks=[callbacks.LearningRateScheduler(lrfn,verbose=True),callbacks.ModelCheckpoint('models/%s-roberta-%i.tf'%(VER,fold),monitor='val_loss',
                                                                                                          save_best_only=True,save_weights_only=True)],
                  epochs=EPOCHS,verbose=1)
        pred=model.predict(valid_ds,verbose=1)
```


of course no oom with max_len 256 and batch size 8.


so is this not a bug? I don't understand since 14*16*1024*1024 with float32 is just under 1GB and RTX3090 has 24GB of memory

**Comment by mohantym** [comment]
Hi @alanpurple ! Its not only about once Tensor . It is iterating for all tensors with 1GB memory size while in model.fit() operation. Glad! it got resolved though. Please move this to closed status . Thank you!

**Comment by alanpurple** [comment]
@mohantym 
so almost all 24GB of GPU memory being taken right after load pretrained BERT-LARGE is normal?

In that case, this is should be closed

**Comment by alanpurple** [comment]
@mohantym 

I think I did have some misconcept, as soon as the program load cuda context, it takes almost  all of gpu's memory, it's normal I guess....

sorry for misunderstanding( of cudnn )
