### ISSUE TITLE
TFT convert error: ValueError: Input 0 of node StatefulPartitionedCall/my_model/conv_root/AssignVariableOp was passed float from Func/StatefulPartitionedCall/input/_1:0 incompatible with expected resource.

### ISSUE THREAD

**Issue by nikshar-symbio** [tensorflow/tensorflow#54911]
**System information**
- OS is Ubuntu 18.04
- CUDA is 11.5
- Code is being run under `nvcr.io/nvidia/tensorflow:21.12-tf2-py3` (`TensorFlow` version in it is `2.6.2`)

**Describe the current behavior**
I'm trying to convert a `TensorFlow` saved model to `TF-TRT` using [tf.experimental.tensorrt.Converter](https://www.tensorflow.org/api_docs/python/tf/experimental/tensorrt/Converter)

I'm getting the following error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/importer.py", line 496, in _import_graph_def_internal
    results = c_api.TF_GraphImportGraphDefWithResults(
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 0 of node StatefulPartitionedCall/my_model/conv_root/AssignVariableOp was passed float from Func/StatefulPartitionedCall/input/_1:0 incompatible with expected resource.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tmp_stdconv_model.py", line 56, in <module>
    converter.convert()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/compiler/tensorrt/trt_convert.py", line 1198, in convert
    frozen_func = convert_to_constants.convert_variables_to_constants_v2(func)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/convert_to_constants.py", line 1153, in convert_variables_to_constants_v2
    return _construct_concrete_function(func, output_graph_def,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/convert_to_constants.py", line 1078, in _construct_concrete_function
    new_func = wrap_function.function_from_graph_def(output_graph_def,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/wrap_function.py", line 650, in function_from_graph_def
    wrapped_import = wrap_function(_imports_graph_def, [])
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/wrap_function.py", line 621, in wrap_function
    func_graph.func_graph_from_py_func(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/func_graph.py", line 1007, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/wrap_function.py", line 87, in __call__
    return self.call_with_variable_creator_scope(self._fn)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/wrap_function.py", line 93, in wrapped
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/wrap_function.py", line 648, in _imports_graph_def
    importer.import_graph_def(graph_def, name="")
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/deprecation.py", line 549, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/importer.py", line 400, in import_graph_def
    return _import_graph_def_internal(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/importer.py", line 501, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: Input 0 of node StatefulPartitionedCall/my_model/conv_root/AssignVariableOp was passed float from Func/StatefulPartitionedCall/input/_1:0 incompatible with expected resource.
```

**Standalone code to reproduce the issue**

Here's a fully reproducible code
```
import tensorflow as tf
import numpy as np


class StdConv(tf.keras.layers.Conv2D):
    """Weight Standardization Conv2D.

    See https://arxiv.org/pdf/1903.10520v1.pdf.

    """

    def _standardize_wts(self, wts):
        wts_mean = tf.math.reduce_mean(wts, axis=(0, 1, 2), keepdims=True)
        wts_var = tf.math.reduce_variance(wts, axis=(0, 1, 2), keepdims=True)
        return (wts - wts_mean) / tf.math.sqrt(wts_var + 1e-5)

    def call(self, inputs):
        standardized_wts = self._standardize_wts(self.kernel)
        self.kernel.assign(standardized_wts)
        return super().call(inputs)


class MyModel(tf.keras.Model):
    def __init__(self):
        super().__init__()
        self.root = StdConv(
            64,
            kernel_size=7,
            padding="same",
            name="conv_root",
        )

    def call(self, inputs, training=True):
        return self.root(inputs, training=training)


model = MyModel()
inp = np.ndarray((1, 256, 256, 3))
op = model(inp, training=False)
print("op shape: ", op.shape)

# save tf model
tf.keras.models.save_model(model, "stdconvmodel")


# convert to trt
params = tf.experimental.tensorrt.ConversionParams(precision_mode="FP32")

converter = tf.experimental.tensorrt.Converter(
    input_saved_model_dir="stdconvmodel", conversion_params=params
)

print("\nconverter.convert...")
converter.convert()
print("\nconverter.save...")
converter.save(trt_model)
print("\nsaved!")
```

I've tried this with a couple of other tensorflow versions, and have also tried using `trt_convert.TrtGraphConverterV2` from `tensorflow.python.compiler.tensorrt`

**Comment by nikshar-symbio** [comment]
Thanks for that suggestion.
I tried it, and it works, but the model prediction time is significantly slow. The model I'm using is a modified version of ResNet that uses the `StdConv` block show in the code above. Using the standard `model.call` method, it takes `0.02 sec` per prediction, but with the `TRT` model it takes about `3 sec`. I don't know what's causing the issue.

As another test, I repeated the same comparison with a standard ResNet50, and I get about `0.004 sec` per prediction in both cases. Interestingly, if I convert this standard ResNet50 model to `TensorFlow-TRT` (using the code in my original question), it takes about `0.003 sec`!

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

Both TFRT and TFLite converter do not support mutable resource variable use cases yet. We are working on supporting the missing features in the MLIR converter.

For TFLite converter, please use the V2 saved model converter if you have an issue related to resource variables since it has the better support in dealing with immutable resource variables than other graph representations (e.g., keras model, concrete function, and frozen graphdef).

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.
