### ISSUE TITLE
tf.distribute.experimental.CentralStorageStrategy does not work with tf.keras.layers.Discretization

### ISSUE THREAD

**Issue by cockroachzl** [tensorflow/tensorflow#54969]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: Yes
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS Linux release 7.2
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**: N/A
-   **TensorFlow installed from (source or binary)**: binary
-   **TensorFlow version (use command below)**: v2.8.0-rc1-32-g3f878cff5b6 2.8.0
-   **Python version**: 3.8.8
-   **Bazel version (if compiling from source)**: N/A
-   **GCC/Compiler version (if compiling from source)**: N/A
-   **CUDA/cuDNN version**: CUDA 11.2/cuDNN 8.2.1
-   **GPU model and memory**: two A100 GPUs, each with 40GB GPU memory
-   **Exact command to reproduce**:

### Describe the problem
I wrote a subclassed Keras model and use tf.keras.layers.Discretization to preprocessing two numerical features. In the preprocessing layer, the code also uses Normalization/StringLookup/IntegerLookup to preprocess numerical and categorical features. The training data is in TFRecord format and read using TFRecordDataset API.

The model training works fine with default strategy, tf.distribute.OneDeviceStrategy(device="/gpu:0"), and tf.distribute.MirroredStrategy(). However, the following error occurred if the distributed strategy is switched to CentralStorageStrategy.

```
INVALID_ARGUMENT:  indices[28] = -1 is not in [0, 10)
	 [[{{node MMoE/u-age_dis_embedding/embedding_lookup}}]]
```
This vocabulary size of the u-age_dis_embedding is 10, and the index is computed by the Discretization. I do not quite understand why Discretization output -1 under CentralStorageStrategy, and since the training code works fine with other distributed strategies, I guess this is a bug between CentralStorageStrategy and Discretization.

Here is the compute device info with CentralStorageStrategy.
`strategy = tf.distribute.experimental.CentralStorageStrategy()`
`INFO:tensorflow:ParameterServerStrategy (CentralStorageStrategy if you are using a single machine) with compute_devices = ['/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1'], variable_device = '/device:CPU:0'`

### Source code / logs
Here is the code snippets and the logs
```
# strategy = tf.distribute.MirroredStrategy() # this works fine
# strategy = tf.distribute.OneDeviceStrategy(device="/gpu:0") # this works fine
# strategy = tf.distribute.get_strategy() # this works fine
strategy = tf.distribute.experimental.CentralStorageStrategy() #this strategy failed
with strategy.scope():
    mmoe_model = MMoE(config, preprocessing_layer, name='MMoE')
    optimizer=tf.keras.optimizers.Adam()

    mmoe_model.compile(
        optimizer=optimizer,
    #     run_eagerly=True,
    #     jit_compile=True,
    )
dataset_train = make_dataset_ceph_v0('2022-01-20/14', num_hours=1, batch_size=4096, block_length=None, data_dir='/group/30039/sample_tfrecord/')
mmoe_model.fit(dataset_train, epochs=1)
```
```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-70-b48f111214ea> in <module>
----> 1 mmoe_model.fit(dataset_train, epochs=1)

/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/utils/traceback_utils.py in error_handler(*args, **kwargs)
     65     except Exception as e:  # pylint: disable=broad-except
     66       filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67       raise e.with_traceback(filtered_tb) from None
     68     finally:
     69       del filtered_tb

/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     52   try:
     53     ctx.ensure_initialized()
---> 54     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     55                                         inputs, attrs, num_outputs)
     56   except core._NotOkStatusException as e:

InvalidArgumentError: Graph execution error:

Detected at node 'MMoE/u-age_dis_embedding/embedding_lookup' defined at (most recent call last):
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/threading.py", line 890, in _bootstrap
      self._bootstrap_inner()
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/engine/training.py", line 1000, in run_step
      outputs = model.train_step(data)
    File "<ipython-input-22-cbffbfa5ad65>", line 245, in train_step
      y_pred = self(x, training=True)  # Forward pass y_pred[task].shape = (batch_size, 1)
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/engine/base_layer.py", line 1096, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "<ipython-input-23-0f0cbc0afd9c>", line 62, in call
      for feature_name, config in self._config.items():
    File "<ipython-input-23-0f0cbc0afd9c>", line 68, in call
      if isinstance(embedding_fn, list):
    File "<ipython-input-23-0f0cbc0afd9c>", line 69, in call
      for layer in embedding_fn:
    File "<ipython-input-23-0f0cbc0afd9c>", line 70, in call
      bottom = layer(bottom)
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/engine/base_layer.py", line 1096, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/layers/embeddings.py", line 197, in call
      out = tf.nn.embedding_lookup(self.embeddings, inputs)
Node: 'MMoE/u-age_dis_embedding/embedding_lookup'
Detected at node 'MMoE/u-age_dis_embedding/embedding_lookup' defined at (most recent call last):
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/threading.py", line 890, in _bootstrap
      self._bootstrap_inner()
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/engine/training.py", line 1000, in run_step
      outputs = model.train_step(data)
    File "<ipython-input-22-cbffbfa5ad65>", line 245, in train_step
      y_pred = self(x, training=True)  # Forward pass y_pred[task].shape = (batch_size, 1)
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/engine/base_layer.py", line 1096, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "<ipython-input-23-0f0cbc0afd9c>", line 62, in call
      for feature_name, config in self._config.items():
    File "<ipython-input-23-0f0cbc0afd9c>", line 68, in call
      if isinstance(embedding_fn, list):
    File "<ipython-input-23-0f0cbc0afd9c>", line 69, in call
      for layer in embedding_fn:
    File "<ipython-input-23-0f0cbc0afd9c>", line 70, in call
      bottom = layer(bottom)
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/engine/base_layer.py", line 1096, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/layers/embeddings.py", line 197, in call
      out = tf.nn.embedding_lookup(self.embeddings, inputs)
Node: 'MMoE/u-age_dis_embedding/embedding_lookup'
Detected at node 'MMoE/u-age_dis_embedding/embedding_lookup' defined at (most recent call last):
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/threading.py", line 890, in _bootstrap
      self._bootstrap_inner()
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/engine/training.py", line 1000, in run_step
      outputs = model.train_step(data)
    File "<ipython-input-22-cbffbfa5ad65>", line 245, in train_step
      y_pred = self(x, training=True)  # Forward pass y_pred[task].shape = (batch_size, 1)
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/engine/base_layer.py", line 1096, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "<ipython-input-23-0f0cbc0afd9c>", line 62, in call
      for feature_name, config in self._config.items():
    File "<ipython-input-23-0f0cbc0afd9c>", line 68, in call
      if isinstance(embedding_fn, list):
    File "<ipython-input-23-0f0cbc0afd9c>", line 69, in call
      for layer in embedding_fn:
    File "<ipython-input-23-0f0cbc0afd9c>", line 70, in call
      bottom = layer(bottom)
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/engine/base_layer.py", line 1096, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/keras/layers/embeddings.py", line 197, in call
      out = tf.nn.embedding_lookup(self.embeddings, inputs)
Node: 'MMoE/u-age_dis_embedding/embedding_lookup'
3 root error(s) found.
  (0) INVALID_ARGUMENT:  indices[28] = -1 is not in [0, 10)
	 [[{{node MMoE/u-age_dis_embedding/embedding_lookup}}]]
	 [[replica_1/MMoE/i-grade_embedding/embedding_lookup/_352]]
  (1) INVALID_ARGUMENT:  indices[28] = -1 is not in [0, 10)
	 [[{{node MMoE/u-age_dis_embedding/embedding_lookup}}]]
	 [[Add_41/ReadVariableOp_1/_2648]]
  (2) INVALID_ARGUMENT:  indices[28] = -1 is not in [0, 10)
	 [[{{node MMoE/u-age_dis_embedding/embedding_lookup}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_562346]
```

**Comment by tilakrayal** [comment]
@cockroachzl,
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

Could you please try with the latest tensorflow v2.17 which contains the Keras3.0 and supports the disitribution strategy for the Keras.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
