### ISSUE TITLE
seq2seq.BasicDecoder not working with seq2seq.SampleEmbeddingSampler 

### ISSUE THREAD

**Issue by neqkir** [tensorflow/tensorflow#55223]
Tensorflow 2, my code

```
def beam_evaluate_sentence(text, beam_width=3):
    
  # work on preprocessed text (lower, space before punctuation)
  text = dataset_creator.preprocess_text(text)

  text = '<start> ' + text + ' <end>'

  inputs = [tokenizer.word_index[i] for i in text.split(' ')]

  maxlen=len(inputs)

  inputs = tf.keras.preprocessing.sequence.pad_sequences([inputs],
                                                          maxlen=maxlen,
                                                          padding='post')

  inputs = tf.convert_to_tensor(inputs)
  inference_batch_size = inputs.shape[0]
  result = ''

  enc_start_state = [tf.zeros((inference_batch_size, units)), tf.zeros((inference_batch_size,units))]
  enc_out, enc_h, enc_c = encoder(inputs, enc_start_state)

  dec_h = enc_h
  dec_c = enc_c

  start_tokens = tf.fill([inference_batch_size], tokenizer.word_index['<start>'])
  end_token = tokenizer.word_index['<end>']
  
  # From official documentation
  # NOTE If you are using the BeamSearchDecoder with a cell wrapped in AttentionWrapper, then you must ensure that:
  # The encoder output has been tiled to beam_width via tfa.seq2seq.tile_batch (NOT tf.tile).
  # The batch_size argument passed to the get_initial_state method of this wrapper is equal to true_batch_size * beam_width.
  # The initial state created with get_initial_state above contains a cell_state value containing properly tiled final state from the encoder.

  enc_out = tfa.seq2seq.tile_batch(enc_out, multiplier=beam_width)
  decoder.attention_mechanism.setup_memory(enc_out)
  print("beam_with * [batch_size, max_length_input, rnn_units] :  3 * [1, 16, 1024]] :", enc_out.shape)

  # set decoder_inital_state which is an AttentionWrapperState considering beam_width
  hidden_state = tfa.seq2seq.tile_batch([enc_h, enc_c], multiplier=beam_width)
  decoder_initial_state = decoder.rnn_cell.get_initial_state(batch_size=beam_width*inference_batch_size, dtype=tf.float32)
  decoder_initial_state = decoder_initial_state.clone(cell_state=hidden_state)

  temperature_sampler = tfa.seq2seq.sampler.SampleEmbeddingSampler(softmax_temperature=TEMPERATURE)

  # Instantiate BasicDecoder object
  decoder_instance = tfa.seq2seq.BasicDecoder(cell=decoder.rnn_cell, sampler=temperature_sampler, output_layer=decoder.fc)
  # Setup Memory in decoder stack
  decoder.attention_mechanism.setup_memory(enc_out)

  decoder_initial_state = decoder.build_initial_state(inference_batch_size, [enc_h, enc_c], tf.float32)

  decoder_embedding_matrix = decoder.embedding.variables[0]

  outputs, _, _ = decoder_instance(decoder_embedding_matrix, start_tokens = start_tokens, end_token= end_token, initial_state=decoder_initial_state)
  return outputs.sample_id.numpy()
```

The problem is appearing when I switch from a greedy sampler to 

`  temperature_sampler = tfa.seq2seq.sampler.SampleEmbeddingSampler(softmax_temperature=TEMPERATURE)
`

and the issue is 

```
Traceback (most recent call last):
  File "/root/gen.py", line 268, in <module>
    sample_decoder_outputs = decoder(sample_x, initial_state)
  File "/root/.local/lib/python3.9/site-packages/keras/utils/traceback_utils.py",or_handler
    raise e.with_traceback(filtered_tb) from None
  File "/root/gen.py", line 258, in call
    outputs, _, _ = self.decoder(x, initial_state=initial_state, sequence_length=ax_length_output-1])
  File "/usr/local/lib/python3.9/dist-packages/tensorflow_addons/seq2seq/decoder.n call
    return dynamic_decode(
  File "/usr/local/lib/python3.9/dist-packages/typeguard/__init__.py", line 1033,
    retval = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/tensorflow_addons/seq2seq/decoder.n dynamic_decode
    initial_finished, initial_inputs, initial_state = decoder.initialize(
  File "/usr/local/lib/python3.9/dist-packages/tensorflow_addons/seq2seq/basic_de128, in initialize
    return self.sampler.initialize(inputs, **kwargs) + (initial_state,)
TypeError: Exception encountered when calling layer "basic_decoder" (type BasicDe

initialize() got an unexpected keyword argument 'sequence_length'

Call arguments received:
  • inputs=tf.Tensor(shape=(32, 17, 256), dtype=float32)
  • initial_state=AttentionWrapperState(cell_state=['tf.Tensor(shape=(32, 1024),  'tf.Tensor(shape=(32, 1024), dtype=float32)'], attention='tf.Tensor(shape=(32, 1t32)', alignments='tf.Tensor(shape=(32, 17), dtype=float32)', alignment_history=(te='tf.Tensor(shape=(32, 17), dtype=float32)')
  • training=None
  • kwargs={'sequence_length': ['16', '16', '16', '16', '16', '16', '16', '16', ' '16', '16', '16', '16', '16', '16', '16', '16', '16', '16', '16', '16', '16', '1'16', '16', '16', '16', '16']}

```

**Comment by mohantym** [comment]
Hi @neqkir ! Could you please share a Colab gist too?

**Comment by sonpenton7** [comment]
I am thinking there are multiple [ways](https://x8spedersapk.id/wa-gb/) this one is easy to understand !

### Method 1: As string
index = 0
next_char = tf.strings.substr(
    input_word, index, len(input_word[0].numpy()) - index, unit="UTF8_CHAR", name=None
)
end_token = len(input_word[0].numpy())
print('next_char[0].numpy(): ' + str(next_char[0].numpy()))

def f1(): 
    global pointer
    print(input_word[pointer])
    pointer = tf.add(pointer, 1)
    return
def f2(): 
    global my_index
    print('add 1')
    my_index = tf.add(my_index, 1)
    return

r = tf.cond( tf.less_equal(my_index, pointer), f1, f2 )
