### ISSUE TITLE
[TPU] TPUClusterResolver Can't Resolve TPU Metadata When Using Regional GKE Cluster

### ISSUE THREAD

**Issue by ZeroExistence** [tensorflow/tensorflow#55307]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): tensorflow/tensorflow:2.7.1, tensorflow/tensorflow:2.8.0
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.1, 2.8.0
- Python version: 3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: cloud-tpus.google.com/preemptible-v2: "8"

**Describe the current behavior**
We have a GKE regional cluster with TPU support. When I tried to create a ResNet-RS using the official TPU guide, I encountered the issue with TPUClusterResolver.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/tpu/client/client.py", line 259, in _fetch_cloud_tpu_metadata
    r = service.projects().locations().nodes().get(name=self._full_name())
  File "/usr/local/lib/python3.8/dist-packages/googleapiclient/discovery.py", line 1044, in method
    raise TypeError(
TypeError: Parameter "name" value "projects/[PROJECT-CODE]/locations/us-central1-b/nodes/us-central1-b/[TPU-RESOURCE]" does not match the pattern "^projects/[^/]+/locations/[^/]+/nodes/[^/]+$"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/models/official/vision/beta/train.py", line 70, in <module>
    app.run(main)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/root/models/official/vision/beta/train.py", line 50, in main
    distribution_strategy = distribute_utils.get_distribution_strategy(
  File "/root/models/official/common/distribute_utils.py", line 151, in get_distribution_strategy
    cluster_resolver = tpu_initialize(tpu_address)
  File "/root/models/official/common/distribute_utils.py", line 88, in tpu_initialize
    tf.config.experimental_connect_to_cluster(cluster_resolver)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/remote.py", line 141, in connect_to_cluster
    if cluster_spec_or_resolver.master() in _LOCAL_MASTERS:
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/distribute/cluster_resolver/tpu/tpu_cluster_resolver.py", line 256, in master
    cluster_spec = self.cluster_spec()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/distribute/cluster_resolver/tpu/tpu_cluster_resolver.py", line 330, in cluster_spec
    network_endpoints = self._cloud_tpu_client.network_endpoints()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/tpu/client/client.py", line 346, in network_endpoints
    response = self._fetch_cloud_tpu_metadata()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/tpu/client/client.py", line 262, in _fetch_cloud_tpu_metadata
    raise ValueError("Could not lookup TPU metadata from name '%s'. Please "
ValueError: Could not lookup TPU metadata from name 'us-central1-b/[TPU-RESOURCE]'. Please doublecheck the tpu argument in the TPUClusterResolver constructor. Exception: Parameter "name" value "projects/[PROJECT-CODE]/locations/us-central1-b/nodes/us-central1-b/[TPU-RESOURCE]" does not match the pattern "^projects/[^/]+/locations/[^/]+/nodes/[^/]+$"
```

**Describe the expected behavior**
The ResNet-RS job should run in TPU core without any issues.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): No
- Briefly describe your candidate solution(if contributing): N/A

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
https://cloud.google.com/tpu/docs/tutorials/resnet-rs-2.x
Run this guide in a regional GKE cluster with TPU support.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
```
apiVersion: v1
kind: Pod
metadata:
    endpoints.cloud-tpus.google.com/gke: grpc://10.0.0.106:8470
    name.cloud-tpus.google.com/gke: us-central1-b/[TPU-RESOURCE]
  name: gke
spec:
  containers:
  - command:
    - bash
    - -c
    - export PYTHONPATH=$PYTHONPATH:/root/models && cd /root && apt-get update &&
      apt-get install -y git && git clone https://github.com/tensorflow/models.git
      && pip3 install tf-models-nightly tensorflow-text-nightly && pip3 install -r
      models/official/requirements.txt && python3 /root/models/official/vision/beta/train.py
      --experiment=resnet_rs_imagenet --mode=train_and_eval --model_dir=$MODEL_DIR
      --tpu=$TPU_NAME --config_file=/root/models/official/vision/beta/configs/experiments/image_classification/imagenet_resnetrs50_i160.yaml
      --params_override="task.train_data.input_path=$IMAGENET_DIR/train*, task.validation_data.input_path=$IMAGENET_DIR/valid*,
      trainer.train_steps=100" && sleep 900
    env:
    - name: IMAGENET_DIR
      value: gs://cloud-tpu-test-datasets/fake_imagenet
    - name: STORAGE_BUCKET
      value: gs://xxxxx
    - name: MODEL_DIR
      value: gs://xxxxx/resnet-rs-2x_v6
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /var/secrets/google/key.json
    - name: KUBE_GOOGLE_CLOUD_TPU_ENDPOINTS
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.annotations['endpoints.cloud-tpus.google.com/gke-dgtest-tpu-resnetrs6']
    - name: TPU_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.annotations['name.cloud-tpus.google.com/gke-dgtest-tpu-resnetrs6']
    image: tensorflow/tensorflow:2.8.0
```

**Comment by tilakrayal** [comment]
@ZeroExistence ,
Please move this issue to closed status, as commented above it has been resolved.Thanks!

**Comment by tilakrayal** [comment]
@ZeroExistence ,
Can you please take a look at this issue [link](https://github.com/tensorflow/tensorflow/issues/30869) with the similar error.It helps.

**Comment by tilakrayal** [comment]
Also please move this issue to closed status as it has been resolved.Thanks!

**Comment by ZeroExistence** [comment]
Thank you @tilakrayal for checking! Moving this issue to close.
