### ISSUE TITLE
TF-lite conversion of complex abs layer not working with integer quantization with fallbacks

### ISSUE THREAD

**Issue by DanBmh** [tensorflow/tensorflow#55349]
I'm trying to optimize a speech-to-text Conformer model for tflite usage. Quantization of the model is working for _default_ optimization mode, but not when a _representative dataset_ is used. In this case it fails in inference with: `type != kTfLiteFloat32 (INT8 != FLOAT32) Node number 46 (COMPLEX_ABS) failed to prepare`

Shouldn't the model use the _float32_ fallback in this case, since I'm not enforcing _int8_ operators?

### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20:04
- TensorFlow installation (pip package or built from source): Nvidia-Docker
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.7

### 2. Failure after conversion

```
Transcribing the audio ...
Label:             they were subjected to constant surveillance and periodic searches
Traceback (most recent call last):
  File "/Scribosermo/exporting/testing_file.py", line 161, in <module>
    main()
  File "/Scribosermo/exporting/testing_file.py", line 155, in main
    test_tflite(checkpoint_tflite_quant)
  File "/Scribosermo/exporting/testing_file.py", line 118, in test_tflite
    prediction = predict(interpreter, audio)
  File "/Scribosermo/exporting/testing_file.py", line 92, in predict
    interpreter.invoke()
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 923, in invoke
    self._interpreter.Invoke()
RuntimeError: /workspace/tensorflow/lite/kernels/complex_support.cc:43 output-> \
  type != kTfLiteFloat32 (INT8 != FLOAT32)Node number 46 (COMPLEX_ABS) failed to prepare.
```

### 3. Code snippets

```python3
# Conversion settings
def export_tflite(model, save_path, optimize):

    converter = tf.lite.TFLiteConverter.from_keras_model(model)

    if optimize:
        converter.optimizations = [tf.lite.Optimize.DEFAULT]
        converter.representative_dataset = representative_dataset

    tflite_model = converter.convert()

    with open(save_path, "wb+") as file:
        file.write(tflite_model)

# Spectrogram definition
def audio_to_spect(self, audio):
        """Calculate the spectrogram"""

        # Pytorch uses a slightly different spectrogram calculation which is matched to librosa
        # unlike the default tensorflow implementation
        n_fft = 512
        nbatch = tf.shape(audio)[0]

        # Add center padding
        signal = tf.reshape(audio, [nbatch, -1])
        pad_amount = int(self.audio_window_samples // 2)
        signal = tf.pad(signal, [[0, 0], [pad_amount, pad_amount]], "REFLECT")
        signal = tf.reshape(signal, [nbatch, 1, -1])

        # Calculate short-time Fourier transforms with a differnt windowing approach
        f = tf.signal.frame(
            signal, self.audio_window_samples, self.audio_step_samples, pad_end=False
        )
        w = tf.signal.hann_window(self.audio_window_samples, periodic=False)
        stfts = tf.signal.rfft(f * w, fft_length=[n_fft])

        # Obtain the magnitude of the STFT.
        spectrogram = tf.abs(stfts) ** 2
        spectrogram = tf.squeeze(spectrogram, axis=1)

        return spectrogram
```

<br>

Related issue: https://github.com/tensorflow/tensorflow/issues/53393#issuecomment-1009703703 (was closed without solution)

**Comment by DanBmh** [comment]
Fails as well when I'm replacing the `abs` with `spectrogram = tf.math.real(stfts) ** 2 + tf.math.imag(stfts) ** 2`:

 `RuntimeError: /workspace/tensorflow/lite/kernels/complex_support.cc:43 output->type != kTfLiteFloat32 (INT8 != FLOAT32)Node number 46 (IMAG) failed to prepare.`

**Comment by mohantym** [comment]
Hi @DanBmh ! Can you please share the model along with code containing representative dataset to replicate the issue? I was going to propose these changes for [integer quantization.](https://www.tensorflow.org/lite/performance/post_training_integer_quant)  Thanks!

```
def export_tflite(model, save_path, optimize):

    converter = tf.lite.TFLiteConverter.from_keras_model(model)

    if optimize:
        converter.optimizations = [tf.lite.Optimize.DEFAULT]
        converter.representative_dataset = representative_dataset
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8 , tf.lite.OpsSet.SELECT_TF_OPS ]
   # Set the input and output tensors to uint8 (APIs added in r2.3)
    converter.inference_input_type = tf.uint8
    converter.inference_output_type = tf.uint8
    tflite_model = converter.convert()

    with open(save_path, "wb+") as file:
        file.write(tflite_model)
```

**Comment by DanBmh** [comment]
The actual model is quite complicated, but I could implement a shorter example:

```
import os

import numpy as np
import tensorflow as tf
import tflite_runtime.interpreter as tflite
from tensorflow.keras import layers as tfl
from tensorflow.python.framework.ops import enable_eager_execution

# ==================================================================================================

exportdir = "/tmp/tftests/"

# ==================================================================================================


class AudioLayer(tfl.Layer):
    def __init__(self):
        super().__init__()
        self.audio_window_samples = int(16000 * 0.025)
        self.audio_step_samples = int(16000 * 0.01)

    # ==============================================================================================

    def audio_to_spect(self, audio):
        """Calculate the spectrogram"""

        # Pytorch uses a slightly different spectrogram calculation which is matched to librosa
        # unlike the default tensorflow implementation
        n_fft = 512
        nbatch = tf.shape(audio)[0]

        # Add center padding
        signal = tf.reshape(audio, [nbatch, -1])
        pad_amount = int(self.audio_window_samples // 2)
        signal = tf.pad(signal, [[0, 0], [pad_amount, pad_amount]], "REFLECT")
        signal = tf.reshape(signal, [nbatch, 1, -1])

        # Calculate short-time Fourier transforms with a differnt windowing approach
        f = tf.signal.frame(
            signal, self.audio_window_samples, self.audio_step_samples, pad_end=False
        )
        w = tf.signal.hann_window(self.audio_window_samples, periodic=False)
        stfts = tf.signal.rfft(f * w, fft_length=[n_fft])

        # Obtain the magnitude of the STFT.
        spectrogram = tf.math.real(stfts) ** 2 + tf.math.imag(stfts) ** 2
        spectrogram = tf.squeeze(spectrogram, axis=1)

        return spectrogram

    # ==============================================================================================

    def call(self, x, training=False):  # pylint: disable=arguments-differ

        audio = tf.expand_dims(x, axis=-1)
        spectrogram = self.audio_to_spect(audio)
        return spectrogram


# ==================================================================================================


class MyModel(tf.keras.Model):  # pylint: disable=abstract-method
    def __init__(self):
        super().__init__()

        self.model = self.make_model()

    # ==============================================================================================

    def make_model(self):
        input_tensor = tfl.Input(shape=[None], name="input_samples")

        # Used for easier debugging changes
        audio = tf.identity(input_tensor)

        spectrogram = AudioLayer()(audio)

        x = tf.reduce_sum(spectrogram)
        output_tensor = tf.identity(x, name="logits")

        model = tf.keras.Model(input_tensor, output_tensor, name="name")
        return model

    # ==============================================================================================

    def summary(self):  # pylint: disable=arguments-differ
        print("")
        self.model.summary(line_length=100)

    # ==============================================================================================

    # This input signature is required that we can export and load the model in ".pb" format
    # with a variable sequence length, instead of using the one of the first input.
    @tf.function(input_signature=[tf.TensorSpec([None, None], tf.float32)])
    def call(self, x):  # pylint: disable=arguments-differ
        """Call with input shape: [1, len_signal], output shape: [1, len_steps, n_alphabet]"""

        x = self.model(x)
        return x


# ==================================================================================================


def representative_dataset():
    for i in range(100):
        data = np.random.rand(1, (i % 10 + 1) * 1000)
        yield [data.astype(np.float32)]


# ==================================================================================================


def export_tflite(model, save_path, optimize, fullint):

    converter = tf.lite.TFLiteConverter.from_keras_model(model)

    if optimize:
        converter.optimizations = [tf.lite.Optimize.DEFAULT]
    if fullint:
        converter.representative_dataset = representative_dataset

    tflite_model = converter.convert()

    with open(save_path, "wb+") as file:
        file.write(tflite_model)


# ==================================================================================================


def predict(interpreter, audio):
    """Feed an audio signal with shape [1, len_signal] into the network and get the predictions"""

    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    # Enable dynamic shape inputs
    interpreter.resize_tensor_input(input_details[0]["index"], audio.shape)
    interpreter.allocate_tensors()

    # Feed audio
    interpreter.set_tensor(input_details[0]["index"], audio)
    interpreter.invoke()

    output_data = interpreter.get_tensor(output_details[0]["index"])
    return output_data


# ==================================================================================================


def main():
    if not os.path.isdir(exportdir):
        os.makedirs(exportdir)

    # Eager execution is required for pb and tflite exports
    enable_eager_execution()

    model_tl = MyModel()
    model_tl.build(input_shape=(None, None))
    model_tl.summary()

    print("\nExporting models ...")
    export_tflite(
        model_tl, exportdir + "model_full.tflite", optimize=False, fullint=False
    )
    export_tflite(
        model_tl, exportdir + "model_quantized.tflite", optimize=True, fullint=False
    )
    export_tflite(model_tl, exportdir + "model_int.tflite", optimize=True, fullint=True)

    print("\nmodel_full:")
    interpreter = tflite.Interpreter(model_path=exportdir + "model_full.tflite")
    print("Input details:", interpreter.get_input_details())
    print(predict(interpreter, np.random.rand(1, 1234).astype(np.float32)))

    print("\nmodel_quantized:")
    interpreter = tflite.Interpreter(model_path=exportdir + "model_quantized.tflite")
    print("Input details:", interpreter.get_input_details())
    print(predict(interpreter, np.random.rand(1, 1234).astype(np.float32)))

    print("\nmodel_int:")
    interpreter = tflite.Interpreter(model_path=exportdir + "model_int.tflite")
    print("Input details:", interpreter.get_input_details())
    print(predict(interpreter, np.random.rand(1, 1234).astype(np.float32)))


# ==================================================================================================

if __name__ == "__main__":
    main()
    print("\nFINISHED")

```

**Comment by mohantym** [comment]
Ok @DanBmh ! I used tf.lite.interpreter from version 2.8 instead of tflite.interpreter from tflite_runtime. Attaching resolved [gist](https://colab.sandbox.google.com/gist/mohantym/3a378726bd039b780f5691bb631906e1/untitled328.ipynb) for reference. Thanks!

**Comment by DanBmh** [comment]
Thanks, it is working for me with `tf.lite` instead of `tflite_runtime` and `v=2.8` as well. (I kept float32 input and output)
Do you know when `tflite_runtime=2.8` will be released?
My target is a RaspberryPi and using the full tensorflow installation isn't really feasible.

**Comment by DanBmh** [comment]
I also tried the export with the full model, which is working too, but the outputs are now incorrect. 
Instead of predicting some text the model now only predicts _blank_ labels (normally the most common label), so it returns an empty text...
There was no problem with the default quantization approach without the representative dataset.
Do you have an idea about this?
Is it common that _int8_ quantization can break the model?

**Comment by mohantym** [comment]
@DanBmh ! Regarding the Raspberry pi deployment and tflite_run_time 2.8 .You can check this [repo](https://github.com/PINTO0309/TensorflowLite-bin).

**Comment by DanBmh** [comment]
I think I could solve my problem with the full model. For mel-spectrogram and feature-normalization I'm adding very small values to the tensors to prevent _log_ and _div_ with zero, but with the _int8-quantization_ those "zero-guards" are just set to zero themselves, so I'm getting _nan_ values inbetween...

Do you know the smallest value I can use? Currently I'm using `2**-5`, and `2**-6` was to small.

Thanks for the tip to the spectrogram debugging documents. You can find my complete debugging script here: https://gitlab.com/DANBER/Scribosermo/-/blob/cfc/extras/misc/complex_tflite_test.py

Regarding the version problem, it seems that _2.8_ is only required for exporting.

I also found that, presumably only in the case of the example script, using a larger number (>= 100) of representative examples decreases the performance of quantization. I think the effect could be smaller if there is a real model after the feature calculation. What do you think about this?

**Comment by mohantym** [comment]
@DanBmh ! Glad you sorted out the issue .  Check with "1.001e-5" as the minimum value to avoid zero division error.  You can batch the data in the representative dataset if you are worried about performance. Please move this to closed status if it worked. Thanks!

**Comment by DanBmh** [comment]
The smallest value working as zero-guard for `log` was `2 ** -5`, smaller values sometimes resulted in `-inf` results. The smallest value for `div` was `1/255`, smaller values sometimes resulted in `nan` results.

Batching might work here, but I think it won't work for my real representative dataset, because the audio inputs have quite different lengths.
