### ISSUE TITLE
mlflow.start_run() cases internal XLA error on TPU v2-8 with TF 2.8.0

### ISSUE THREAD

**Issue by froody** [tensorflow/tensorflow#55370]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): pre-installed on GCP TPU instance
- TensorFlow version (use command below): tpu-vm-tf-2.8.0
- Python version: 3.8.10
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: tpu v2-8, tpu-vm-tf-2.8.0

**Describe the current behavior**
```
2022-03-25 03:01:14.053145: I tensorflow/core/tpu/tpu_api_dlsym_initializer.cc:116] Libtpu path is: libtpu.so
2022-03-25 03:01:15.555809: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-03-25 03:01:29.331594: I tensorflow/compiler/xla/service/service.cc:171] XLA service 0x429e9c0 initialized for platform TPU (this does not guarantee that XLA will be used). Devices:
2022-03-25 03:01:29.331633: I tensorflow/compiler/xla/service/service.cc:179]   StreamExecutor device (0): TPU, 2a886c8
2022-03-25 03:01:29.331640: I tensorflow/compiler/xla/service/service.cc:179]   StreamExecutor device (1): TPU, 2a886c8
2022-03-25 03:01:29.331646: I tensorflow/compiler/xla/service/service.cc:179]   StreamExecutor device (2): TPU, 2a886c8
2022-03-25 03:01:29.331656: I tensorflow/compiler/xla/service/service.cc:179]   StreamExecutor device (3): TPU, 2a886c8
2022-03-25 03:01:29.331664: I tensorflow/compiler/xla/service/service.cc:179]   StreamExecutor device (4): TPU, 2a886c8
2022-03-25 03:01:29.331671: I tensorflow/compiler/xla/service/service.cc:179]   StreamExecutor device (5): TPU, 2a886c8
2022-03-25 03:01:29.331681: I tensorflow/compiler/xla/service/service.cc:179]   StreamExecutor device (6): TPU, 2a886c8
2022-03-25 03:01:29.331694: I tensorflow/compiler/xla/service/service.cc:179]   StreamExecutor device (7): TPU, 2a886c8
All devices:  [LogicalDevice(name='/device:TPU:0', device_type='TPU'), LogicalDevice(name='/device:TPU:1', device_type='TPU'), LogicalDevice(name='/device:TPU:2', device_type='TPU'), LogicalDevice(name='/device:TPU:3', device_type='TPU'), LogicalDevice(name='/device:TPU:4', device_type='TPU'), LogicalDevice(name='/device:TPU:5', device_type='TPU'), LogicalDevice(name='/device:TPU:6', device_type='TPU'), LogicalDevice(name='/device:TPU:7', device_type='TPU')]
2022-03-25 03:01:56.679371: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:237] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2022-03-25 03:01:56.701447: I tensorflow/compiler/jit/xla_compilation_cache.cc:399] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
2022-03-25 03:01:56.703897: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at xla_compile_on_demand_op.cc:183 : INTERNAL: Core halted unexpectedly: No error message available as no compiler metadata was provided.
Traceback (most recent call last):
  File "testcase.py", line 23, in <module>
    main()
  File "testcase.py", line 19, in main
    seq = tf.keras.Sequential([tf.keras.layers.Dense(512)])
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/training/tracking/base.py", line 629, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/constant_op.py", line 102, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
tensorflow.python.framework.errors_impl.InternalError: Core halted unexpectedly: No error message available as no compiler metadata was provided.
```

**Describe the expected behavior**

`tf.keras.Sequential([tf.keras.layers.Dense(512)])` returns successfully

**[Contributing](https://www.tensorflow.org/community/contribute)**

 - I doubt I can fix this myself

**Standalone code to reproduce the issue**
```
# testcase.py
import mlflow
import tensorflow as tf

def init_tf_gpus():
    resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu='local')
    tf.config.experimental_connect_to_cluster(resolver)
    # This is the TPU initialization code that has to be at the beginning.
    tf.tpu.experimental.initialize_tpu_system(resolver)
    print("All devices: ", tf.config.list_logical_devices('TPU'))

    tf.config.optimizer.set_jit(True)

    return tf.distribute.TPUStrategy(resolver)

def main():
    strategy = init_tf_gpus()
    with mlflow.start_run(run_name="test"): # disable this line to make it work
        with strategy.scope():
            seq = tf.keras.Sequential([tf.keras.layers.Dense(512)])


if __name__ == "__main__":
    main()
```
**Other info / logs** Include any logs or source code that would be helpful to

Install mlflow via `pip install mlflow`, I am using 1.24.0

**Comment by froody** [comment]
issue in mlflow: https://github.com/mlflow/mlflow/issues/5528

**Comment by sachinprasadhs** [comment]
Hi, Did you observe similar behavior in Tf-Nightly version.

**Comment by froody** [comment]
@sachinprasadhs is that "nightly" or "tpu_driver_nightly" in the tpu software version menu?

**Comment by sachinprasadhs** [comment]
It's a Tensorflow nightly version, if you are using pip then you can install using 
`pip install tf-nightly`
