### ISSUE TITLE
'Activation' object has no attribute 'kernel' applying regularization to MobileNetV3

### ISSUE THREAD

**Issue by mattpotma** [tensorflow/tensorflow#55376]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.7.0-rc1-69-gc256c071bb2, tf-nightly-2.9.0.dev20220325
- Python version: 3.9.7
- CUDA/cuDNN version: N/A 
- GPU model and memory: N/A

**Describe the current behavior**

Attempting to add regularization to MobileNetV3. The regularization appears to be applied correctly (applied to 43 Conv2D and Dense layers), but calling `model.fit` fails with the error `AttributeError: 'Activation' object has no attribute 'kernel'`.

It appears that calling `model.fit` is reapplying the regularization, but on the last `layer`, which is the output Activation. Adding regularization this way works on MobileNetV2 and custom models I've built, but only fails on MobileNetV3 (small or large).

If a default argument is used in the lambda (`layer.add_loss(lambda l=layer: regularizer(l.kernel))`), I can build and train the model, but MLFlow is unable to log the model. 

**Describe the expected behavior**

The sample script should run without fail, or at least fail similarly between MobieNetV2 and MobileNetV3.

**Standalone code to reproduce the issue**

Colab notebook (2.9.0 nightly) https://colab.research.google.com/drive/1JQxl6KyCf5vWUnFjo0qB7v_I5maMMspb#scrollTo=HAlKVbk08W3X

Standalone code:

```python
import numpy as np
import tensorflow as tf


model = tf.keras.applications.MobileNetV3Small(input_shape=(96, 96, 3))
# model = tf.keras.applications.MobileNetV2(input_shape=(96, 96, 3))
regularizer = tf.keras.regularizers.L1(1e-3)

for layer in model.layers:
    if hasattr(layer, "kernel"):
        layer.add_loss(lambda: regularizer(layer.kernel))

# Ensure regularization only applied to Conv2D or Dense layers
regularization_count = 0
for layer in model.layers:
    if layer.losses:
        regularization_count += 1
        assert isinstance(layer, tf.keras.layers.Conv2D) or isinstance(layer, tf.keras.layers.Dense)
        assert not isinstance(layer, tf.keras.layers.Activation)

print(f"Regularization added to {regularization_count} layers")

model.compile(loss="mse")
model.fit(
    np.random.randn(10, 96, 96, 3),
    np.random.randn(10, 1000),
)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Traceback from Colab notebook:

```
WARNING:tensorflow:`input_shape` is undefined or non-square, or `rows` is not 224. Weights for input shape (224, 224) will be loaded as the default.
Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/mobilenet_v3/weights_mobilenet_v3_small_224_1.0_float.h5
10734624/10734624 [==============================] - 0s 0us/step
Regularization added to 43 layers

---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

[<ipython-input-3-0ea365886076>](https://localhost:8080/#) in <module>()
     23 model.fit(
     24     np.random.randn(10, 96, 96, 3),
---> 25     np.random.randn(10, 1000),
     26 )

2 frames

[<ipython-input-3-0ea365886076>](https://localhost:8080/#) in <lambda>()
      8 for layer in model.layers:
      9     if hasattr(layer, "kernel"):
---> 10         layer.add_loss(lambda: regularizer(layer.kernel))
     11 
     12 # Ensure regularization only applied to Conv2D or Dense layers

AttributeError: in user code:

    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1051, in train_function  *
        return step_function(self, iterator)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1040, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1030, in run_step  **
        outputs = model.train_step(data)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 890, in train_step
        loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 949, in compute_loss
        y, y_pred, sample_weight, regularization_losses=self.losses)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py", line 1268, in losses
        loss_tensor = regularizer()
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py", line 1342, in _tag_callable
        loss = loss()
    File "<ipython-input-3-0ea365886076>", line 10, in <lambda>
        layer.add_loss(lambda: regularizer(layer.kernel))

    AttributeError: 'Activation' object has no attribute 'kernel'
```

**Comment by Srikeshram** [comment]
I would like to work on this issue. Can you please assign it to me?

**Comment by sushreebarsa** [comment]
@mattpotma 
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thanks!

**Comment by mattpotma** [comment]
Sorry I missed that. Cross posted to https://github.com/keras-team/keras/issues/16316. Closing this now.
