### ISSUE TITLE
Failed to call tf.convert_to_tensor for a tf.RaggedTensor with a PlaceHolder value

### ISSUE THREAD

**Issue by dandelin** [tensorflow/tensorflow#55373]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 12.3
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): https://developer.apple.com/metal/tensorflow-plugin/
- TensorFlow version (use command below): unknown 2.8.0
- Python version: 3.8.12
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: Apple M1 16.00 GB
 
**Describe the current behavior**
related issue in tensorflow-text github : https://github.com/tensorflow/text/issues/867

```
Metal device set to: Apple M1

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB

2022-03-23 16:43:41.295408: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-03-23 16:43:41.295626: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
2022-03-23 16:43:44.494936: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2022-03-23 16:43:44.530574: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-03-23 16:43:44.554177: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
Traceback (most recent call last):
  File "_text.py", line 31, in <module>
    y_txt = trimmer.trim([y_txt])[0]
  File "/Users/user/miniforge3/envs/tf/lib/python3.8/site-packages/tensorflow_text/python/ops/trimmer_ops.py", line 49, in trim
    segments = [
  File "/Users/user/miniforge3/envs/tf/lib/python3.8/site-packages/tensorflow_text/python/ops/trimmer_ops.py", line 50, in <listcomp>
    ragged_tensor.convert_to_tensor_or_ragged_tensor(s) for s in segments
  File "/Users/user/miniforge3/envs/tf/lib/python3.8/site-packages/tensorflow/python/ops/ragged/ragged_tensor.py", line 2658, in convert_to_tensor_or_ragged_tensor
    return ops.convert_to_tensor_v2_with_dispatch(
  File "/Users/user/miniforge3/envs/tf/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/user/miniforge3/envs/tf/lib/python3.8/site-packages/keras/layers/core/tf_op_layer.py", line 107, in handle
    return TFOpLambda(op)(*args, **kwargs)
  File "/Users/user/miniforge3/envs/tf/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
TypeError: Exception encountered when calling layer "tf.convert_to_tensor" (type TFOpLambda).

Failed to convert elements of tf.RaggedTensor(values=tf.RaggedTensor(values=Tensor("Placeholder:0", shape=(None,), dtype=int32), row_splits=Tensor("Placeholder_1:0", shape=(None,), dtype=int64)), row_splits=Tensor("Placeholder_2:0", shape=(None,), dtype=int64)) to Tensor. Consider casting elements to a supported type. See https://www.tensorflow.org/api_docs/python/tf/dtypes for supported TF dtypes.

Call arguments received:
  • value=tf.RaggedTensor(values=tf.RaggedTensor(values=Tensor("Placeholder:0", shape=(None,), dtype=int32), row_splits=Tensor("Placeholder_1:0", shape=(None,), dtype=int64)), row_splits=Tensor("Placeholder_2:0", shape=(None,), dtype=int64))
  • dtype=None
  • dtype_hint=None
  • name=None
```

**Describe the expected behavior**

```
Metal device set to: Apple M1

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB

2022-03-23 16:42:31.925269: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-03-23 16:42:31.925539: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
2022-03-23 16:42:36.016294: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2022-03-23 16:42:36.057489: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-03-23 16:42:36.081872: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-03-23 16:42:36.096263: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
<tf.RaggedTensor [[[101],
  [7592],
  [2088],
  [999],
  [102]]]>
```

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```python
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text

x_txt = tf.keras.layers.Input(shape=(), dtype=tf.string)
bert_pre = hub.load("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")
tokenize = hub.KerasLayer(bert_pre.tokenize)
bert_info = bert_pre.tokenize.get_special_tokens_dict()

trimmer = text.RoundRobinTrimmer(max_seq_length=40)
mlm_selector = text.RandomItemSelector(
    max_selections_per_batch=1000,
    selection_rate=0.15,
    unselectable_ids=[
        bert_info["end_of_segment_id"],
        bert_info["mask_id"],
        bert_info["padding_id"],
        bert_info["start_of_sequence_id"],
    ],
)
mask_values_chooser = text.MaskValuesChooser(
    bert_info["vocab_size"], bert_info["mask_id"], mask_token_rate=0.8
)

y_txt = tokenize(x_txt)
y_txt, _segment_id = text.combine_segments(
    [y_txt],
    bert_info["start_of_sequence_id"],
    bert_info["end_of_segment_id"],
)
y_txt = trimmer.trim([y_txt])[0]

model = tf.keras.models.Model(inputs=[x_txt], outputs=[y_txt])
print(model.predict(tf.constant(["hello world!"])))
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

This eager execution equivalent returns expected output.

```python
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text

x_txt = tf.constant(["hello world!"])
bert_pre = hub.load("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")
tokenize = hub.KerasLayer(bert_pre.tokenize)
bert_info = bert_pre.tokenize.get_special_tokens_dict()

trimmer = text.RoundRobinTrimmer(max_seq_length=40)
mlm_selector = text.RandomItemSelector(
    max_selections_per_batch=1000,
    selection_rate=0.15,
    unselectable_ids=[
        bert_info["end_of_segment_id"],
        bert_info["mask_id"],
        bert_info["padding_id"],
        bert_info["start_of_sequence_id"],
    ],
)
mask_values_chooser = text.MaskValuesChooser(
    bert_info["vocab_size"], bert_info["mask_id"], mask_token_rate=0.8
)

y_txt = tokenize(x_txt)
y_txt, _segment_id = text.combine_segments(
    [y_txt],
    bert_info["start_of_sequence_id"],
    bert_info["end_of_segment_id"],
)
y_txt = trimmer.trim([y_txt])[0]
print(y_txt)
```

**Comment by tilakrayal** [comment]
@chunduriv ,
I was able to reproduce the issue in tf v2.8, v2.7 and nightly.Please find the gist [here](https://colab.research.google.com/gist/tilakrayal/ec9f4feafa9e373daf725ba6cbbbca74/55373-2-8.ipynb).
