### ISSUE TITLE
TFLite allocate tensors fails: (CONCATENATION) failed to prepare 

### ISSUE THREAD

**Issue by ldb1026** [tensorflow/tensorflow#55424]
### 1. System information

There is a problem in the pytorch model -> tflite quantization process, the model is a multi-input multi-output structure

The model inference process is shown in the code

`    def forward(self, input_x: torch.Tensor, tdnn_s0, tdnn_s1, tdnn_s1_2):
         model_in = input_x

        conv1_inputs = torch.cat([tdnn_s0, model_in], 2) 

        conv1 = self.norm[0](self.relu(self.convs[0](conv1_inputs)).permute(0, 2, 1)).permute(0, 2, 1)

        output_conv1 = conv1

        conv2_inputs = torch.cat([tdnn_s1, conv1], 2) 
        conv2 = self.convs[1](conv2_inputs) 
        output_conv2 = conv2

        conv2_2_inputs = torch.cat([tdnn_s1_2, conv2], 2) 
        conv2_2 = self.norm[1](self.relu(self.convs[2](conv2_2_inputs)).permute(0, 2, 1)).permute(0, 2, 1)

        conv2_2 = torch.add(conv2_inputs[:,:,:-1], conv2_2)

        dense_input = conv2_2.permute(0, 2, 1)

        output = self.dense(dense_input)

        return  output, output_conv1, output_conv2`

When I quantize the model I get an error like the following, but when I comment out the quantization in the code, it works; I don't yet know where the problem is

2022-03-29 20:37:26.144668: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:345] Ignored output_format.
2022-03-29 20:37:26.144820: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:348] Ignored drop_control_dependency.
2022-03-29 20:37:26.144875: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:354] Ignored change_concat_input_ranges.
2022-03-29 20:37:26.146905: I tensorflow/cc/saved_model/reader.cc:38] Reading SavedModel from: tmp
2022-03-29 20:37:26.149434: I tensorflow/cc/saved_model/reader.cc:90] Reading meta graph with tags { serve }
2022-03-29 20:37:26.149493: I tensorflow/cc/saved_model/reader.cc:132] Reading SavedModel debug info (if present) from: tmp
2022-03-29 20:37:26.158658: I tensorflow/cc/saved_model/loader.cc:206] Restoring SavedModel bundle.
2022-03-29 20:37:26.159847: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2200000000 Hz
2022-03-29 20:37:26.178324: I tensorflow/cc/saved_model/loader.cc:190] Running initialization op on SavedModel bundle at path: tmp
2022-03-29 20:37:26.187430: I tensorflow/cc/saved_model/loader.cc:277] SavedModel load for tags { serve }; Status: success: OK. Took 40531 microseconds.
2022-03-29 20:37:26.210737: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:210] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
calib [[1, 40, 4], [1, 40, 2], [1, 160, 1], [1, 20, 1]]
Traceback (most recent call last):
  File "export_flow_layer2.py", line 207, in <module>
    main()
  File "export_flow_layer2.py", line 180, in main
    tflite_model_quant = converter.convert()
  File "/home/storage06/lidongbo/tools/anaconda3/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 921, in convert
    result = self._calibrate_quantize_model(result, **flags)
  File "/home/storage06/lidongbo/tools/anaconda3/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 521, in _calibrate_quantize_model
    calibrated = calibrate_quantize.calibrate(
  File "/home/storage06/lidongbo/tools/anaconda3/lib/python3.8/site-packages/tensorflow/lite/python/optimize/calibrator.py", line 173, in calibrate
    self._calibrator.Prepare([list(s.shape) for s in sample])
RuntimeError: tensorflow/lite/kernels/concatenation.cc:80 t->dims->data[d] != t0->dims->data[d] (160 != 40)Node number 0 (CONCATENATION) failed to prepare .

### 2. Code
``` 
      def representative_data_gen():
            for item in range(2):
                feat = torch.zeros(1, 40, 4, dtype=torch.float)
                tdnn_s0 = torch.zeros(1, 40, 2, dtype=torch.float)
                tdnn_s1 = torch.zeros(1, 160, 1, dtype=torch.float)
                tdnn_s1_2 = torch.zeros(1, 20, 1, dtype=torch.float)
                yield [feat.numpy(), tdnn_s0.numpy(), tdnn_s1.numpy(), tdnn_s1_2.numpy()]

        converter = tf.lite.TFLiteConverter.from_saved_model(args.pb_model)
        converter.optimizations = [tf.lite.Optimize.DEFAULT]
        converter.representative_dataset = representative_data_gen
        converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
        converter.inference_input_type = tf.int8
        converter.inference_output_type = tf.int8
        tflite_model_quant = converter.convert()

        with open(args.tflite, 'wb') as f:
            f.write(tflite_model_quant)
```

**Comment by mohantym** [comment]
Hi @ldb1026 ! You should use ONNX to convert Pytorch models to TF model/TF lite models . Attaching relevant threads [1](https://stackoverflow.com/questions/61679908/pytorch-convert-2d-cnn-model-to-tflite), [2](https://community.arm.com/arm-community-blogs/b/ai-and-ml-blog/posts/pytorch-to-tensorflow-lite-for-deploying-on-arm-ethos-u55-and-u65) for reference . Please revert back with a Colab gist for further assistance. Thank you!

**Comment by ldb1026** [comment]
I have successfully converted the model to a pb model, it's just that I get an error during quantization

The problem I encountered is that when I use the code to convert the pb to tflite model
if I quantify the configuration, like this

```
        converter = tf.lite.TFLiteConverter.from_saved_model(args.pb_model)
        converter.optimizations = [tf.lite.Optimize.DEFAULT]
        converter.representative_dataset = representative_data_gen
        converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
        converter.inference_input_type = tf.int8
        converter.inference_output_type = tf.int8
        tflite_model_quant = converter.convert()
```

there will be corresponding problems， that is to  paper  

> RuntimeError: tensorflow/lite/kernels/concatenation.cc:80 t->dims->data[d] != t0->dims->data[d] (20 != 40)Node number 0 (CONCATENATION) failed to prepare.

but if it is not quantized, the conversion will be successful.


Is this problem caused by the fact that the model cannot recalculate the shape due to operator collapse?

**Comment by ldb1026** [comment]
The problem is solved, the reason is that the pb model is a multi-input model, and the data returned by the function onverter.representative_dataset is not in the correct order

**Comment by mohantym** [comment]
@ldb1026 ! I suspected the same in the representative dataset aside suggesting to remove the .numpy() operation. Did  it get resolved after rearranging the inputs in order?

**Comment by ldb1026** [comment]
The problem is solved, it can be closed, thank you

**Comment by mohantym** [comment]
@ldb1026 ! Thanks for confirmation. Moving to closed status as it was marked resolved from this[ comment](https://github.com/tensorflow/tensorflow/issues/55424#issuecomment-1082821296).

**Comment by Doomski99** [comment]
Thanks @ldb1026, I had the same problem and it indeed was the order of the inputs in the representative dataset. For anyone that needs extra clarification: the input order of the actual graph (after conversion) might be different than the order as defined in your python code, and, apparently, the representative dataset needs input ordering of the post-conversion graph...
