### ISSUE TITLE
Bazel build error. Warning on retrieving an archive which is not found and then fails.

### ISSUE THREAD

**Issue by GosuPaper** [tensorflow/tensorflow#55426]
Hi fellow developers,

I am trying to build Tensorflow from source on Windows using the tutorial on the website (https://www.tensorflow.org/install/source_windows) but I have an issue when i get to the bazel build of tensorflow
I am using this command to build since I have cuda and cudnn installed on my computer. (When i did the ./configure it found them and I could specify the compute capability for example) :
`bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true --copt=-nvcc_options=disable-warnings //tensorflow/tools/pip_package:build_pip_package`

Here is the trace starting a little before it could not found an archive and then fails.
```
INFO: Repository local_config_cuda instantiated at:
  C:/users/me/desktop/ia/tensorflow-master/WORKSPACE:15:14: in <toplevel>
  C:/users/me/desktop/ia/tensorflow-master/tensorflow/workspace2.bzl:870:19: in workspace
  C:/users/me/desktop/ia/tensorflow-master/tensorflow/workspace2.bzl:96:19: in _tf_toolchains
Repository rule cuda_configure defined at:
  C:/users/me/desktop/ia/tensorflow-master/third_party/gpus/cuda_configure.bzl:1448:33: in <toplevel>
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/8b8793a6d3d528e9b190ab7f9b85fea2f1aadc2c.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
        File "C:/users/me/desktop/ia/tensorflow-master/third_party/gpus/cuda_configure.bzl", line 1401, column 38, in _cuda_autoconf_impl
                _create_local_cuda_repository(repository_ctx)
        File "C:/users/me/desktop/ia/tensorflow-master/third_party/gpus/cuda_configure.bzl", line 1239, column 56, in _create_local_cuda_repository
                host_compiler_includes + _cuda_include_path(
        File "C:/users/me/desktop/ia/tensorflow-master/third_party/gpus/cuda_configure.bzl", line 364, column 32, in _cuda_include_path
                inc_entries.append(realpath(repository_ctx, cuda_config.cuda_toolkit_path + "/include"))
        File "C:/users/me/desktop/ia/tensorflow-master/third_party/remote_config/common.bzl", line 290, column 19, in realpath
                return execute(repository_ctx, [bash_bin, "-c", "realpath \"%s\"" % path]).stdout.strip()
        File "C:/users/me/desktop/ia/tensorflow-master/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
/usr/bin/bash: line 1: realpath: command not found
ERROR: C:/users/me/desktop/ia/tensorflow-master/WORKSPACE:15:14: fetching cuda_configure rule //external:local_config_cuda: Traceback (most recent call last):
        File "C:/users/me/desktop/ia/tensorflow-master/third_party/gpus/cuda_configure.bzl", line 1401, column 38, in _cuda_autoconf_impl
                _create_local_cuda_repository(repository_ctx)
        File "C:/users/me/desktop/ia/tensorflow-master/third_party/gpus/cuda_configure.bzl", line 1239, column 56, in _create_local_cuda_repository
                host_compiler_includes + _cuda_include_path(
        File "C:/users/me/desktop/ia/tensorflow-master/third_party/gpus/cuda_configure.bzl", line 364, column 32, in _cuda_include_path
                inc_entries.append(realpath(repository_ctx, cuda_config.cuda_toolkit_path + "/include"))
        File "C:/users/me/desktop/ia/tensorflow-master/third_party/remote_config/common.bzl", line 290, column 19, in realpath
                return execute(repository_ctx, [bash_bin, "-c", "realpath \"%s\"" % path]).stdout.strip()
        File "C:/users/me/desktop/ia/tensorflow-master/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
/usr/bin/bash: line 1: realpath: command not found
INFO: Found applicable config definition build:cuda in file c:\users\me\desktop\ia\tensorflow-master\.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
INFO: Found applicable config definition build:cuda in file c:\users\me\desktop\ia\tensorflow-master\.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
ERROR: @local_config_cuda//:enable_cuda :: Error loading option @local_config_cuda//:enable_cuda: Repository command failed
/usr/bin/bash: line 1: realpath: command not found
```

I am really sorry if it appears to be a problem on my side but since I can't retrieve the archive I think it is best to start here first.
Thank you for your help and your job.

**Comment by GosuPaper** [comment]
Problem solved here :
https://discuss.tensorflow.org/t/error-building-tensorflow-2-8-in-windows-10/7984/3

**Comment by tilakrayal** [comment]
@GosuPaper ,
Please refer this link [1](https://github.com/tensorflow/tensorflow/issues/54407) and [2](https://github.com/tensorflow/tensorflow/issues/53614) with the similar error.It helps.Thanks!

**Comment by GosuPaper** [comment]
> Problem solved here : https://discuss.tensorflow.org/t/error-building-tensorflow-2-8-in-windows-10/7984/3
> 
> Sorry for the inconvenience

Here is the answer to my problem @tilakrayal . Sorry for the incovenience and thanks for your help

**Comment by tilakrayal** [comment]
@GosuPaper ,
Glad the issue is resolved for you, please feel free to move this to closed status.
