### ISSUE TITLE
tensorflow-macos version 2.8.0 cannot import keras

### ISSUE THREAD

**Issue by essandess** [tensorflow/tensorflow#55433]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
macOS 12.3
`x86_64` and `arm64` versions
tensorflow-macos 2.8.0 installed via pypi
* https://pypi.org/project/tensorflow-macos/#files
* https://files.pythonhosted.org/packages/e5/6c/05e158fd3a729c3d11720468b170bfa18db140e0091452e5bec2976e0f3d/tensorflow_macos-2.8.0-cp38-cp38-macosx_11_0_x86_64.whl

**Describe the current behavior**
These `keras` imports don't work:
```bash
python3.8 -c 'import tensorflow.keras'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow.keras'
```

```bash
python3.8 -c 'import tensorflow.keras.datasets.mnist'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow.keras'
```

```bash
python3.8 -c 'from tensorflow import keras as keras ; keras.datasets.mnist.load_data'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/util/lazy_loader.py", line 58, in __getattr__
    module = self._load()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/util/lazy_loader.py", line 41, in _load
    module = importlib.import_module(self.__name__)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
```

```bash
python3.8 -c 'from tensorflow.python import keras as keras ; keras.datasets.mnist.load_data'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'tensorflow.python.keras' has no attribute 'datasets'
```

**Describe the expected behavior**

All `keras` imports above should work.

**Comment by sushreebarsa** [comment]
@essandess To use keras ,could you please make sure that you have installed tensorflow packages successfully in your system, please check the [Build from source](https://www.tensorflow.org/install/source#macos) for macOS and refer to the tested build configurations.
Thanks!

**Comment by essandess** [comment]
@sushreebarsa `tensorflow-macos` is provided as a pre-built `.whl` by Tensorflow on pypi: https://pypi.org/project/tensorflow-macos/#files. It is installed correctly.

Also please note that the previous version 2.7.0 works correctly: https://pypi.org/project/tensorflow-macos/2.7.0/

cc: @kulinseth (`tensorflow-macos` maintainer on pypi)

**Comment by gadagashwini** [comment]
@essandess, 
Thanks for reporting this issue.
I could reproduce the issue with `Tensorflow-macos 2.8`. on macOS Monterey 12.3.

I resolved through.

```
brew install python3
python3 -m vent tf
source tf/bin/activate
python3 -m pip install -U pip
pip install tensorflow
```

**Comment by essandess** [comment]
> I could reproduce the issue with `Tensorflow-macos 2.8`. on macOS Monterey 12.3.
> 
> I resolved through.

This does not resolve the issue. It simply installs a different build of Tensorflow that does not support `tensorflow-metal` and macOS GPU support.
