### ISSUE TITLE
Tensorflow 2.8.0 | Error Message: ImportError: SystemError. | Tensorflow package error?

### ISSUE THREAD

**Issue by aldyhelnawan** [tensorflow/tensorflow#55440]
Greetings Tensorflow Support Team.
Hi, I got this error recently on my anaconda environment on my Windows 10 Machine.
### Error Message:

> ImportError: SystemError: <built-in method __contains__ of dict object at 0x000001E3DD963A48> returned a result with an error set

### System Information

> Windows 10
> Anaconda Navigator 2.1.2
> Python: 3.7.11
> Numpy: 1.21.5
> Nvidia RTX 3060 Laptop GPU
> Nvidia CUDA: 11.2
> cuDNN Version: 8.1

### I got this error when upgrade it to Tensorflow 2.8.0 (Installed using pip)
`pip install tensorflow`

Error Log:
```
(shapes_tf2) C:\Users\User>python -c "import tensorflow as tf;print(tf.__version__)"
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\VirtualEnvironment\anaconda3\envs\shapes_tf2\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "D:\VirtualEnvironment\anaconda3\envs\shapes_tf2\lib\site-packages\tensorflow\python\__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "D:\VirtualEnvironment\anaconda3\envs\shapes_tf2\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python.client import pywrap_tf_session
  File "D:\VirtualEnvironment\anaconda3\envs\shapes_tf2\lib\site-packages\tensorflow\python\client\pywrap_tf_session.py", line 19, in <module>
    from tensorflow.python.client._pywrap_tf_session import *
ImportError: SystemError: <built-in method __contains__ of dict object at 0x000001E3DD963A48> returned a result with an error set

(shapes_tf2) C:\Users\User>python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\VirtualEnvironment\anaconda3\envs\shapes_tf2\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "D:\VirtualEnvironment\anaconda3\envs\shapes_tf2\lib\site-packages\tensorflow\python\__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "D:\VirtualEnvironment\anaconda3\envs\shapes_tf2\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python.client import pywrap_tf_session
  File "D:\VirtualEnvironment\anaconda3\envs\shapes_tf2\lib\site-packages\tensorflow\python\client\pywrap_tf_session.py", line 19, in <module>
    from tensorflow.python.client._pywrap_tf_session import *
ImportError: SystemError: <built-in method __contains__ of dict object at 0x000001D6FFDF3A48> returned a result with an error set
```
### But when I'm downgrade it to 2.7.0, it runs normal. (Installed using pip)
`pip install tensorflow==2.7.0`
```
(shapes_tf2) C:\Users\User>python -c "import tensorflow as tf;print(tf.__version__)"
2.7.0

(shapes_tf2) C:\Users\User>python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
2022-03-31 02:42:33.973041: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-03-31 02:42:34.357936: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3493 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3060 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6
tf.Tensor(95.8436, shape=(), dtype=float32)
```

Any solutions for this (other than downgrade it?).
I'm not having any problem for downgrade it. I'm here to report the error I got.
Thank you in advance.

March, 31st 2022

Aldy

**Comment by tilakrayal** [comment]
@aldyhelnawan ,
Can you please try to upgrade the python and confirm if you are facing same issue.
`python3 -m venv --system-site-packages ./venv`
Also please check this [issue1](https://github.com/tensorflow/tensorflow/issues/55338#issuecomment-1075646598) and [issue2](https://github.com/tensorflow/tensorflow/issues/55377) with similar error.Thanks!

**Comment by aldyhelnawan** [comment]
@tilakrayal. Hi, thank you to response my issue.

For the issue, yes. issue1 and issue2 are similar to my issue.
For the suggestions you provide, **upgrade the python version** on my **anaconda venv** is **work** for me.

I'm update the python version using: 
`conda update python`
And the python version updated to version 3.7.13
```
(shapes_tf2) C:\Users\User>conda list python
# packages in environment at D:\VirtualEnvironment\anaconda3\envs\shapes_tf2:
#
# Name                    Version                   Build  Channel
ipython                   7.31.1           py37haa95532_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
opencv-python             4.5.5.64                 pypi_0    pypi
python                    3.7.13               h6244533_0
python-dateutil           2.8.2              pyhd3eb1b0_0
python-git                2018.2.1                 pypi_0    pypi
```

Then I upgrade the tensorflow back to version 2.8.0 using:
`pip install --upgrade tensorflow`

Last, I tested the tensorflow again and it works. This is the result:
```
(shapes_tf2) C:\Users\User>python -c "import tensorflow as tf;print(tf.__version__)"
2.8.0

(shapes_tf2) C:\Users\User>python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
2022-03-31 22:34:44.834772: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-03-31 22:34:45.752188: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3497 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3060 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6
tf.Tensor(1209.3511, shape=(), dtype=float32)
```


Once again, thank you for your support.

**Comment by tilakrayal** [comment]
@aldyhelnawan ,
Glad the suggestion worked for you to resolve the issue, please feel free to move this to closed status.
