### ISSUE TITLE
NotImplementedError: Cannot convert a symbolic Tensor (cond_2/strided_slice:0) to a numpy array.

### ISSUE THREAD

**Issue by santhoshnumberone** [tensorflow/tensorflow#55626]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Google Colab
- TensorFlow installed from (source or binary): Google Colab (default)
- TensorFlow version: 1.15.2
- Python version: 3.7.13
- Installed using virtualenv? pip? conda?: Google Colab (no env)
- Bazel version (if compiling from source): Google Colab (default)
- GCC/Compiler version (if compiling from source): Google Colab (default)
- CUDA/cuDNN version: Google Colab (default)
- GPU model and memory: Google Colab (default)

**Describe the problem**
Trying to train custom object detector referring blog [Custom object detection in the browser using TensorFlow.js](https://blog.tensorflow.org/2021/01/custom-object-detection-in-browser.html)

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Ran these blocks one after other inside Google colab

```
from google.colab import drive
drive.mount('/content/drive/')
```

```
%cd /content/drive/MyDrive/Tensorflow/models/research/
```

```
!git clone https://github.com/tensorflow/models.git
```

```
%tensorflow_version 1.x
```

```
!protoc object_detection/protos/*.proto --python_out=.
# Install TensorFlow Object Detection API.
!cp object_detection/packages/tf1/setup.py .
!python -m pip install .
```

```
!python /content/drive/MyDrive/Tensorflow/models/research/object_detection/builders/model_builder_tf1_test.py
```

```
num_classes = 1
batch_size = 96
num_steps = 7500
num_eval_steps = 1000

train_record_path = '/content/drive/MyDrive/Tensorflow/dataset/train.record'
test_record_path = '/content/drive/MyDrive/Tensorflow/dataset/test.record'
model_dir = '/content/training/'
labelmap_path = '/content/drive/MyDrive/Tensorflow/dataset/labelmap.pbtxt'

pipeline_config_path = '/content/drive/MyDrive/Tensorflow/models/research/faster_rcnn_inception_v2_coco_2018_01_28/pipeline.config'
fine_tune_checkpoint = '/content/drive/MyDrive/Tensorflow/models/research/faster_rcnn_inception_v2_coco_2018_01_28_training/faster_rcnn_inception_training.ckpt-1'
```

```
!python /content/drive/MyDrive/Tensorflow/models/research/object_detection/model_main.py \
    --pipeline_config_path={pipeline_config_path} \
    --model_dir={model_dir} \
    --alsologtostderr \
    --num_train_steps={num_steps} \
    --sample_1_of_n_eval_examples=1 \
    --num_eval_steps={num_eval_steps}
```

Error I get
```
return input_fn(**kwargs)
  File "/usr/local/lib/python3.7/dist-packages/object_detection/inputs.py", line 770, in _train_input_fn
    params=params)
  File "/usr/local/lib/python3.7/dist-packages/object_detection/inputs.py", line 913, in train_input
    reduce_to_frame_fn=reduce_to_frame_fn)
  File "/usr/local/lib/python3.7/dist-packages/object_detection/builders/dataset_builder.py", line 251, in build
    input_reader_config)
  File "/usr/local/lib/python3.7/dist-packages/object_detection/builders/dataset_builder.py", line 236, in dataset_map_fn
    fn_to_map, num_parallel_calls=num_parallel_calls)
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/data/ops/dataset_ops.py", line 1950, in map_with_legacy_function
    use_legacy_function=True))
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/data/ops/dataset_ops.py", line 3472, in __init__
    use_legacy_function=use_legacy_function)
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/data/ops/dataset_ops.py", line 2689, in __init__
    self._function.add_to_graph(ops.get_default_graph())
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/framework/function.py", line 545, in add_to_graph
    self._create_definition_if_needed()
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/framework/function.py", line 377, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/framework/function.py", line 408, in _create_definition_if_needed_impl
    capture_resource_var_by_value=self._capture_resource_var_by_value)
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/framework/function.py", line 944, in func_graph_from_py_func
    outputs = func(*func_graph.inputs)
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/data/ops/dataset_ops.py", line 2681, in wrapper_fn
    ret = _wrapper_helper(*args)
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/data/ops/dataset_ops.py", line 2652, in _wrapper_helper
    ret = autograph.tf_convert(func, ag_ctx)(*nested_args)
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/autograph/impl/api.py", line 237, in wrapper
    raise e.ag_error_metadata.to_exception(e)
NotImplementedError: in converted code:

    /usr/local/lib/python3.7/dist-packages/object_detection/data_decoders/tf_example_decoder.py:580 decode
        default_groundtruth_weights)
    /tensorflow-1.15.2/python3.7/tensorflow_core/python/util/deprecation.py:507 new_func
        return func(*args, **kwargs)
    /tensorflow-1.15.2/python3.7/tensorflow_core/python/ops/control_flow_ops.py:1235 cond
        orig_res_f, res_f = context_f.BuildCondBranch(false_fn)
    /tensorflow-1.15.2/python3.7/tensorflow_core/python/ops/control_flow_ops.py:1061 BuildCondBranch
        original_result = fn()
    /usr/local/lib/python3.7/dist-packages/object_detection/data_decoders/tf_example_decoder.py:573 default_groundtruth_weights
        dtype=tf.float32)
    /tensorflow-1.15.2/python3.7/tensorflow_core/python/ops/array_ops.py:2560 ones
        output = _constant_if_small(one, shape, dtype, name)
    /tensorflow-1.15.2/python3.7/tensorflow_core/python/ops/array_ops.py:2295 _constant_if_small
        if np.prod(shape) < 1000:
    <__array_function__ internals>:6 prod
        
    /usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py:3052 prod
        keepdims=keepdims, initial=initial, where=where)
    /usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py:86 _wrapreduction
        return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
    /tensorflow-1.15.2/python3.7/tensorflow_core/python/framework/ops.py:736 __array__
        " array.".format(self.name))

    NotImplementedError: Cannot convert a symbolic Tensor (cond_2/strided_slice:0) to a numpy array.
```

If I run this
```
import tensorflow as tf
print(tf.__version__)
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from absl import flags
import tensorflow as tf
from object_detection import model_hparams
from object_detection import model_lib

model_dir = "/content/drive/MyDrive/Tensorflow/models/research/faster_rcnn_inception_v2_coco_2018_01_28_training/"



config = tf.estimator.RunConfig(model_dir=model_dir)
pipeline_config_path= "/content/drive/MyDrive/Tensorflow/models/research/faster_rcnn_inception_v2_coco_2018_01_28/pipeline.config"
num_train_steps=100


train_and_eval_dict = model_lib.create_estimator_and_inputs(
                        run_config=config,
                        hparams=model_hparams.create_hparams(None),
                        pipeline_config_path = pipeline_config_path,
                        train_steps =num_train_steps,
                        sample_1_of_n_eval_examples = 1)

estimator = train_and_eval_dict['estimator']
train_input_fn = train_and_eval_dict['train_input_fn']
eval_input_fns = train_and_eval_dict['eval_input_fns']
eval_on_train_input_fn = train_and_eval_dict['eval_on_train_input_fn']
predict_input_fn = train_and_eval_dict['predict_input_fn']
train_steps = train_and_eval_dict['train_steps']

train_spec, eval_specs = model_lib.create_train_and_eval_specs(
        train_input_fn,
        eval_input_fns,
        eval_on_train_input_fn,
        predict_input_fn,
        train_steps,
        eval_on_train_data=False)
tf.estimator.train_and_evaluate(estimator,train_spec,eval_specs[0])
```

Error I get
```
Using TensorFlow backend.
WARNING:tensorflow:Forced number of epochs for all eval validations to be 1.
[04/14 16:53:43] tensorflow WARNING: Forced number of epochs for all eval validations to be 1.
INFO:tensorflow:Maybe overwriting train_steps: 100
[04/14 16:53:43] tensorflow INFO: Maybe overwriting train_steps: 100
INFO:tensorflow:Maybe overwriting use_bfloat16: False
[04/14 16:53:43] tensorflow INFO: Maybe overwriting use_bfloat16: False
INFO:tensorflow:Maybe overwriting sample_1_of_n_eval_examples: 1
[04/14 16:53:43] tensorflow INFO: Maybe overwriting sample_1_of_n_eval_examples: 1
INFO:tensorflow:Maybe overwriting eval_num_epochs: 1
[04/14 16:53:43] tensorflow INFO: Maybe overwriting eval_num_epochs: 1
INFO:tensorflow:Maybe overwriting load_pretrained: True
[04/14 16:53:43] tensorflow INFO: Maybe overwriting load_pretrained: True
INFO:tensorflow:Ignoring config override key: load_pretrained
[04/14 16:53:43] tensorflow INFO: Ignoring config override key: load_pretrained
WARNING:tensorflow:Expected number of evaluation epochs is 1, but instead encountered `eval_on_train_input_config.num_epochs` = 0. Overwriting `num_epochs` to 1.
[04/14 16:53:43] tensorflow WARNING: Expected number of evaluation epochs is 1, but instead encountered `eval_on_train_input_config.num_epochs` = 0. Overwriting `num_epochs` to 1.
INFO:tensorflow:create_estimator_and_inputs: use_tpu False, export_to_tpu False
[04/14 16:53:43] tensorflow INFO: create_estimator_and_inputs: use_tpu False, export_to_tpu False
INFO:tensorflow:Using config: {'_model_dir': '/content/drive/MyDrive/Tensorflow/models/research/faster_rcnn_inception_v2_coco_2018_01_28_training/', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f6e89f30590>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
[04/14 16:53:43] tensorflow INFO: Using config: {'_model_dir': '/content/drive/MyDrive/Tensorflow/models/research/faster_rcnn_inception_v2_coco_2018_01_28_training/', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f6e89f30590>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
WARNING:tensorflow:Estimator's model_fn (<function create_model_fn.<locals>.model_fn at 0x7f6e89f2f050>) includes params argument, but params are not passed to Estimator.
[04/14 16:53:43] tensorflow WARNING: Estimator's model_fn (<function create_model_fn.<locals>.model_fn at 0x7f6e89f2f050>) includes params argument, but params are not passed to Estimator.
INFO:tensorflow:Not using Distribute Coordinator.
[04/14 16:53:43] tensorflow INFO: Not using Distribute Coordinator.
INFO:tensorflow:Running training and evaluation locally (non-distributed).
[04/14 16:53:43] tensorflow INFO: Running training and evaluation locally (non-distributed).
INFO:tensorflow:Start train and evaluate loop. The evaluate will happen after every checkpoint. Checkpoint frequency is determined based on RunConfig arguments: save_checkpoints_steps None or save_checkpoints_secs 600.
[04/14 16:53:43] tensorflow INFO: Start train and evaluate loop. The evaluate will happen after every checkpoint. Checkpoint frequency is determined based on RunConfig arguments: save_checkpoints_steps None or save_checkpoints_secs 600.
WARNING:tensorflow:From /tensorflow-1.15.2/python3.7/tensorflow_core/python/training/training_util.py:236: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
[04/14 16:53:43] tensorflow WARNING: From /tensorflow-1.15.2/python3.7/tensorflow_core/python/training/training_util.py:236: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
INFO:tensorflow:Reading unweighted datasets: ['/content/drive/MyDrive/Tensorflow/dataset/train.record']
[04/14 16:53:43] tensorflow INFO: Reading unweighted datasets: ['/content/drive/MyDrive/Tensorflow/dataset/train.record']
INFO:tensorflow:Reading record datasets for input file: ['/content/drive/MyDrive/Tensorflow/dataset/train.record']
[04/14 16:53:43] tensorflow INFO: Reading record datasets for input file: ['/content/drive/MyDrive/Tensorflow/dataset/train.record']
INFO:tensorflow:Number of filenames to read: 1
[04/14 16:53:43] tensorflow INFO: Number of filenames to read: 1
WARNING:tensorflow:num_readers has been reduced to 1 to match input file shards.
[04/14 16:53:43] tensorflow WARNING: num_readers has been reduced to 1 to match input file shards.
WARNING:tensorflow:From /content/drive/MyDrive/Tensorflow/models/research/object_detection/builders/dataset_builder.py:104: parallel_interleave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.experimental.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.experimental_determinstic`.
[04/14 16:53:43] tensorflow WARNING: From /content/drive/MyDrive/Tensorflow/models/research/object_detection/builders/dataset_builder.py:104: parallel_interleave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.experimental.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.experimental_determinstic`.
WARNING:tensorflow:From /content/drive/MyDrive/Tensorflow/models/research/object_detection/builders/dataset_builder.py:236: DatasetV1.map_with_legacy_function (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.map()
[04/14 16:53:43] tensorflow WARNING: From /content/drive/MyDrive/Tensorflow/models/research/object_detection/builders/dataset_builder.py:236: DatasetV1.map_with_legacy_function (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.map()
WARNING:tensorflow:Entity <bound method TfExampleDecoder.decode of <object_detection.data_decoders.tf_example_decoder.TfExampleDecoder object at 0x7f6e89f3fc10>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Index'
[04/14 16:53:43] tensorflow WARNING: Entity <bound method TfExampleDecoder.decode of <object_detection.data_decoders.tf_example_decoder.TfExampleDecoder object at 0x7f6e89f3fc10>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Index'
WARNING: Entity <bound method TfExampleDecoder.decode of <object_detection.data_decoders.tf_example_decoder.TfExampleDecoder object at 0x7f6e89f3fc10>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Index'
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
[<ipython-input-11-ab0734737a9e>](https://localhost:8080/#) in <module>()
     39         train_steps,
     40         eval_on_train_data=False)
---> 41 tf.estimator.train_and_evaluate(estimator,train_spec,eval_specs[0])

22 frames
[/tensorflow-1.15.2/python3.7/tensorflow_core/python/autograph/impl/api.py](https://localhost:8080/#) in wrapper(*args, **kwargs)
    235       except Exception as e:  # pylint:disable=broad-except
    236         if hasattr(e, 'ag_error_metadata'):
--> 237           raise e.ag_error_metadata.to_exception(e)
    238         else:
    239           raise

NotImplementedError: in converted code:

    /content/drive/MyDrive/Tensorflow/models/research/object_detection/data_decoders/tf_example_decoder.py:580 decode
        default_groundtruth_weights)
    /tensorflow-1.15.2/python3.7/tensorflow_core/python/util/deprecation.py:507 new_func
        return func(*args, **kwargs)
    /tensorflow-1.15.2/python3.7/tensorflow_core/python/ops/control_flow_ops.py:1235 cond
        orig_res_f, res_f = context_f.BuildCondBranch(false_fn)
    /tensorflow-1.15.2/python3.7/tensorflow_core/python/ops/control_flow_ops.py:1061 BuildCondBranch
        original_result = fn()
    /content/drive/MyDrive/Tensorflow/models/research/object_detection/data_decoders/tf_example_decoder.py:573 default_groundtruth_weights
        dtype=tf.float32)
    /tensorflow-1.15.2/python3.7/tensorflow_core/python/ops/array_ops.py:2560 ones
        output = _constant_if_small(one, shape, dtype, name)
    /tensorflow-1.15.2/python3.7/tensorflow_core/python/ops/array_ops.py:2295 _constant_if_small
        if np.prod(shape) < 1000:
    <__array_function__ internals>:6 prod
        
    /usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py:3052 prod
        keepdims=keepdims, initial=initial, where=where)
    /usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py:86 _wrapreduction
        return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
    /tensorflow-1.15.2/python3.7/tensorflow_core/python/framework/ops.py:736 __array__
        " array.".format(self.name))

    NotImplementedError: Cannot convert a symbolic Tensor (cond_2/strided_slice:0) to a numpy array.
```
 What is wrong here?

**Comment by sushreebarsa** [comment]
@santhoshnumberone We  see that you are using older version of TF (v1.15) which is not actively supported so we recommend you to kindly upgrade  to the latest TF versions(2.4 or later) and let us know if it is still an issue ?Please refer [this ](https://www.tensorflow.org/guide/migrate)link for migration 
from TF v1.x to 2.x .
Thanks!

**Comment by santhoshnumberone** [comment]
> @santhoshnumberone We see that you are using older version of TF (v1.15) which is not actively supported so we recommend you to kindly upgrade to the latest TF versions(2.4 or later) and let us know if it is still an issue ?Please refer [this ](https://www.tensorflow.org/guide/migrate)link for migration from TF v1.x to 2.x . Thanks!

Thank you your response I have raised the same here [Google Colab ValueError: faster_rcnn_inception_v2 is not supported for tf version 2. See model_builder.py for features extractors compatible with different versions of Tensorflow](https://github.com/tensorflow/tensorflow/issues/55654)

**Comment by nzarnaghi** [comment]
I could solve the problem by using numpy==1.19.5, tensorflow==1.15.0, and python=3.6.6
