### ISSUE TITLE
ValueError: Input 0 of node model/prune_low_magnitude_conv2d/AssignVariableOp was passed float from model/prune_low_magnitude_conv2d/Mul/ReadVariableOp/resource:0 incompatible with expected resource.

### ISSUE THREAD

**Issue by douzaikongcheng** [tensorflow/tensorflow#55647]
### 1. System information

- OS Platform and Distribution:
centos 7
- TensorFlow installation (pip package or built from source):
pip package
- TensorFlow library (version, if pip package or github SHA, if built from source):
pip package， tensorflow2.6,  tensorflow-model-optimization==0.7.2

### 2. Code

Provide code to help us reproduce your issues using one of the following options:

`
            self.model = create_model(args['networks'])

            pruning_params = {
                'pruning_schedule':
                    PolynomialDecay(
                        initial_sparsity=0.0,
                        final_sparsity=0.50,
                        begin_step=0,
                        end_step=500000000,
                        frequency=100),
            }

            self.model = prune.prune_low_magnitude(
                self.model, **pruning_params)

        self.lg.info('Create model successfully! Params: [{:.2f}]K'.format(self.model.count_params()/1e3))
        self.lg.info('Create model successfully! Params: [{:.2f}]'.format(self.model.count_params()))

        self.train_data = train_data
        self.val_data = val_data
        self.writer = writer

        self.optimizer = tf.keras.optimizers.Adam(lr=self.opt['lr'])
        lr_scheduler = LearningRateScheduler(self.scheduler)
        epoch_end_call = Epoch_End_Callback(self.val_data, self.train_data, self.lg, self.writer, args['paths'], self.opt['val_step'], state=self.state)
        self.callback = [lr_scheduler, epoch_end_call]

        self.prune_callbacks = [
            lr_scheduler,
            epoch_end_call,
            pruning_callbacks.UpdatePruningStep(),
            pruning_callbacks.PruningSummaries(log_dir="./logs"),
        ]

    def train(self):
        if self.resume == False:
            self.model.compile(optimizer=self.optimizer, loss=self.opt['loss'])
        # history = self.model.fit(self.train_data, epochs=self.opt['epochs'], workers=self.opt['workers'], callbacks=self.callback, initial_epoch=self.state['current_epoch']+1)
        history = self.model.fit(self.train_data, epochs=self.opt['epochs'], workers=self.opt['workers'], callbacks=self.prune_callbacks, initial_epoch=self.state['current_epoch']+1)

        converter = tf.lite.TFLiteConverter.from_keras_model(self.model)
        converter._enable_tflite_resource_variables = True
        converter.optimizations = {tf.lite.Optimize.EXPERIMENTAL_SPARSITY, tf.lite.Optimize.DEFAULT}
        tflite_model = converter.convert()

        tflite_model_path = './logs/model.tflite'
        print('model is saved to {}'.format(tflite_model_path))
        with open(tflite_model_path, 'wb') as f:
            f.write(tflite_model)

`

### 3. Failure after conversion
If the conversion is successful, but the generated model is wrong, then state what is wrong:

- Model produces wrong results and/or has lesser accuracy.
- Model produces correct results, but it is slower than expected.

`
/home/usrname/anaconda3/envs/tf2.6_cudnn8.1/lib/python3.7/site-packages/keras/utils/generic_utils.py:497: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  category=CustomMaskWarning)
Traceback (most recent call last):
  File "train.py", line 68, in <module>
    solver.train()
  File "/home/usrname/SR/TF/mymodel_03/solvers/solver.py", line 122, in train
    tflite_model = converter.convert()
  File "/home/usrname/anaconda3/envs/tf2.6_cudnn8.1/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 729, in wrapper
    return self._convert_and_export_metrics(convert_func, *args, **kwargs)
  File "/home/usrname/anaconda3/envs/tf2.6_cudnn8.1/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 715, in _convert_and_export_metrics
    result = convert_func(self, *args, **kwargs)
  File "/home/usrname/anaconda3/envs/tf2.6_cudnn8.1/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 1123, in convert
    self._freeze_keras_model())
  File "/home/usrname/anaconda3/envs/tf2.6_cudnn8.1/lib/python3.7/site-packages/tensorflow/lite/python/convert_phase.py", line 218, in wrapper
    raise error from None  # Re-throws the exception.
  File "/home/usrname/anaconda3/envs/tf2.6_cudnn8.1/lib/python3.7/site-packages/tensorflow/lite/python/convert_phase.py", line 208, in wrapper
    return func(*args, **kwargs)
  File "/home/usrname/anaconda3/envs/tf2.6_cudnn8.1/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 1080, in _freeze_keras_model
    self._funcs[0], lower_control_flow=False))
  File "/home/usrname/anaconda3/envs/tf2.6_cudnn8.1/lib/python3.7/site-packages/tensorflow/python/framework/convert_to_constants.py", line 1235, in convert_variables_to_constants_v2_as_graph
    converted_input_indices)
  File "/home/usrname/anaconda3/envs/tf2.6_cudnn8.1/lib/python3.7/site-packages/tensorflow/python/framework/convert_to_constants.py", line 1080, in _construct_concrete_function
    new_output_names)
  File "/home/usrname/anaconda3/envs/tf2.6_cudnn8.1/lib/python3.7/site-packages/tensorflow/python/eager/wrap_function.py", line 650, in function_from_graph_def
    wrapped_import = wrap_function(_imports_graph_def, [])
  File "/home/usrname/anaconda3/envs/tf2.6_cudnn8.1/lib/python3.7/site-packages/tensorflow/python/eager/wrap_function.py", line 628, in wrap_function
    collections={}),
  File "/home/usrname/anaconda3/envs/tf2.6_cudnn8.1/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 1007, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/usrname/anaconda3/envs/tf2.6_cudnn8.1/lib/python3.7/site-packages/tensorflow/python/eager/wrap_function.py", line 87, in __call__
    return self.call_with_variable_creator_scope(self._fn)(*args, **kwargs)
  File "/home/usrname/anaconda3/envs/tf2.6_cudnn8.1/lib/python3.7/site-packages/tensorflow/python/eager/wrap_function.py", line 93, in wrapped
    return fn(*args, **kwargs)
  File "/home/usrname/anaconda3/envs/tf2.6_cudnn8.1/lib/python3.7/site-packages/tensorflow/python/eager/wrap_function.py", line 648, in _imports_graph_def
    importer.import_graph_def(graph_def, name="")
  File "/home/usrname/anaconda3/envs/tf2.6_cudnn8.1/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 549, in new_func
    return func(*args, **kwargs)
  File "/home/usrname/anaconda3/envs/tf2.6_cudnn8.1/lib/python3.7/site-packages/tensorflow/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/home/usrname/anaconda3/envs/tf2.6_cudnn8.1/lib/python3.7/site-packages/tensorflow/python/framework/importer.py", line 501, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: Input 0 of node model/prune_low_magnitude_conv2d/AssignVariableOp was passed float from model/prune_low_magnitude_conv2d/Mul/ReadVariableOp/resource:0 incompatible with expected resource.
`

### 4. bug
When I use tfmot to try to sparse a model and convert the model to tflite format, it reports an error：
`
ValueError: Input 0 of node model/prune_low_magnitude_conv2d/AssignVariableOp was passed float from model/prune_low_magnitude_conv2d/Mul/ReadVariableOp/resource:0 incompatible with expected resource.
`

**Comment by mohantym** [comment]
Hi @douzaikongcheng ! Could you provide the above code as Colab gist? Please try in 2.8 /2.9 or nightly version too. Attaching relevant threads for reference [1](https://github.com/tensorflow/tensorflow/issues/43833), [2](https://stackoverflow.com/questions/69590274/warning-custom-mask-layers-require-a-config-and-must-override-when-saving-the). Thank you!

**Comment by douzaikongcheng** [comment]
@[mohantym](https://github.com/mohantym), Thank you, I will try.

**Comment by mohantym** [comment]
Hi @douzaikongcheng ! Is it resolved in the 2.8 version onwards?  Please share a colab gist if you are still looking for further assistance? Thanks!

**Comment by mohantym** [comment]
Hi @douzaikongcheng !
Re-opening as requested. Please provide a colab gist to help expedite the issue.
Thank you!

**Comment by pkgoogle** [comment]
Hi @douzaikongcheng, we need more context to reproduce this issue, if you provide a colab gist this will help us immensely. Colab. https://colab.research.google.com/
