### ISSUE TITLE
java.lang.IllegalArgumentException: Error occurred when initializing ObjectDetector: Mobile SSD models are expected to have exactly 4 outputs, found 8

### ISSUE THREAD

**Issue by iamdanniemirz** [tensorflow/tensorflow#55664]
I have quantized my custom trained TensorFlow model into tflite model using the following code but when I put my quantized tflite model into Tensorflow's Object detection android app with a label file, above mentioned error occurred in android studio. Please guide me to solve this problem. Thanks a Lot.

Custom Code used for quantization of TensorFlow model:

```shell
import tensorflow as tf

converter = tf.lite.TFLiteConverter.from_saved_model("/saved_model")
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_types = [tf.float16]
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
tflite_quant_model = converter.convert()

print(len(tflite_quant_model))
with open("tflite_quant_model.tflite", "wb") as f:
    f.write(tflite_quant_model)
```

The Output which I got after adding the quantized model into Tensorflow's Android application:

```shell
E/TaskJniUtils: Error getting native address of native library: task_vision_jni
    java.lang.IllegalArgumentException: Error occurred when initializing ObjectDetector: Mobile SSD models are expected to have exactly 4 outputs, found 8
        at org.tensorflow.lite.task.vision.detector.ObjectDetector.initJniWithByteBuffer(Native Method)
        at org.tensorflow.lite.task.vision.detector.ObjectDetector.access$100(ObjectDetector.java:88)
        at org.tensorflow.lite.task.vision.detector.ObjectDetector$3.createHandle(ObjectDetector.java:223)
        at org.tensorflow.lite.task.core.TaskJniUtils.createHandleFromLibrary(TaskJniUtils.java:91)
        at org.tensorflow.lite.task.vision.detector.ObjectDetector.createFromBufferAndOptions(ObjectDetector.java:219)
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.<init>(TFLiteObjectDetectionAPIModel.java:88)
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.create(TFLiteObjectDetectionAPIModel.java:82)
        at org.tensorflow.lite.examples.detection.DetectorActivity.onPreviewSizeChosen(DetectorActivity.java:105)
        at org.tensorflow.lite.examples.detection.CameraActivity.onPreviewFrame(CameraActivity.java:200)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1221)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/tensorflow: CameraActivity: Exception!
    java.lang.IllegalStateException: Error getting native address of native library: task_vision_jni
        at org.tensorflow.lite.task.core.TaskJniUtils.createHandleFromLibrary(TaskJniUtils.java:95)
        at org.tensorflow.lite.task.vision.detector.ObjectDetector.createFromBufferAndOptions(ObjectDetector.java:219)
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.<init>(TFLiteObjectDetectionAPIModel.java:88)
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.create(TFLiteObjectDetectionAPIModel.java:82)
        at org.tensorflow.lite.examples.detection.DetectorActivity.onPreviewSizeChosen(DetectorActivity.java:105)
        at org.tensorflow.lite.examples.detection.CameraActivity.onPreviewFrame(CameraActivity.java:200)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1221)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalArgumentException: Error occurred when initializing ObjectDetector: Mobile SSD models are expected to have exactly 4 outputs, found 8
        at org.tensorflow.lite.task.vision.detector.ObjectDetector.initJniWithByteBuffer(Native Method)
        at org.tensorflow.lite.task.vision.detector.ObjectDetector.access$100(ObjectDetector.java:88)
        at org.tensorflow.lite.task.vision.detector.ObjectDetector$3.createHandle(ObjectDetector.java:223)
        at org.tensorflow.lite.task.core.TaskJniUtils.createHandleFromLibrary(TaskJniUtils.java:91)
        at org.tensorflow.lite.task.vision.detector.ObjectDetector.createFromBufferAndOptions(ObjectDetector.java:219) 
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.<init>(TFLiteObjectDetectionAPIModel.java:88) 
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.create(TFLiteObjectDetectionAPIModel.java:82) 
        at org.tensorflow.lite.examples.detection.DetectorActivity.onPreviewSizeChosen(DetectorActivity.java:105) 
        at org.tensorflow.lite.examples.detection.CameraActivity.onPreviewFrame(CameraActivity.java:200) 
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1221) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```
</details>

**Comment by mohantym** [comment]
Hi @iamdanniemirz ! Could you provide the code snippets to model files and confirm your Tensorflow version too?  It is creating an Tflite with 8 outputs where 4 output are expected. Attaching relevant [thread](https://stackoverflow.com/questions/66488745/tensorflow-lite-android-object-detection-mobile-ssd-models-are-expected-to-ha) for reference. Thanks!

**Comment by iamdanniemirz** [comment]
``"": {
  "prefix": "Model",
  "body": [
    "import tensorflow as tf",
    "",
    "converter = tf.lite.TFLiteConverter.from_saved_model(\"/saved_model\")",
    "converter.optimizations = [tf.lite.Optimize.DEFAULT]",
    "converter.target_spec.supported_types = [tf.float16]",
    "converter.target_spec.supported_ops = [",
    "  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.",
    "  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.",
    "]",
    "tflite_quant_model = converter.convert()",
    "",
    "print(len(tflite_quant_model))",
    "with open(\"tflite_quant_model.tflite\", \"wb\") as f:",
    "    f.write(tflite_quant_model)"
  ],
  "description": ""
}

**Comment by iamdanniemirz** [comment]
`import tensorflow as tf

converter = tf.lite.TFLiteConverter.from_saved_model("/saved_model")
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_types = [tf.float16]
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
tflite_quant_model = converter.convert()

print(len(tflite_quant_model))
with open("tflite_quant_model.tflite", "wb") as f:
    f.write(tflite_quant_model)`

**Comment by iamdanniemirz** [comment]
'import tensorflow as tf

converter = tf.lite.TFLiteConverter.from_saved_model("/saved_model")
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_types = [tf.float16]
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
tflite_quant_model = converter.convert()

print(len(tflite_quant_model))
with open("tflite_quant_model.tflite", "wb") as f:
    f.write(tflite_quant_model)`

**Comment by iamdanniemirz** [comment]
I have used this code from the official repository for converting tflite without quantization....
https://github.com/tensorflow/models/blob/0b5cbdcfe07b06b1c539ee4e35102f53ad0373cb/research/object_detection/exporter_main_v2.py#L52

**Comment by mohantym** [comment]
@iamdanniemirz ! Did you try the suggested setup in this [comment](https://stackoverflow.com/a/66595929/11530462)? (SSD with Fixed shape (320,320) , Using Colab , Luwang's [metadata writer](https://stackoverflow.com/a/64493506/11530462)) .Thanks!

**Comment by iamdanniemirz** [comment]
@mohantym Yes, I have tried to quantize the model using TF 2.3 aswell. But the same thing happened again. Also tried to write metadata as well using Luwang's [metadata writer](https://stackoverflow.com/a/64493506/11530462) but this code does not work for 8 outputs.

**Comment by mohantym** [comment]
Hi @sachinprasadhs ! Could you look at this issue?

**Comment by iamdanniemirz** [comment]
@sachinprasadhs @mohantym  Waiting for your kind response.

**Comment by karimnosseir** [comment]
Lu Can you please have a look

Thanks

**Comment by lu-wang-g** [comment]
I think it's the same issue as https://github.com/tensorflow/tensorflow/issues/47595, where something went wrong during conversion. The model should only have 4 outputs instead of 8. Circle back to @karimnosseir to double check the conversion step.

**Comment by iamdanniemirz** [comment]
Thanks for the kind reply @lu-wang-g . I have mentioned @fonghyalex for the proper solution he/she did for conversion and also checked issue #47595 but was not able to understand the conversion processes. Please guide me through this. Thanks a lot.

**Comment by iamdanniemirz** [comment]
Thanks, everyone for guiding me through this issue. I just solved the error by using [export_tflite_graph_tf2.py](https://github.com/tensorflow/models/blob/master/research/object_detection/export_tflite_graph_tf2.py) to convert TensorFlow graph model (pb) to tflite based graph model (pb). For converting tflite graph to proper tflite model, I used the same above mentioned [code](https://github.com/tensorflow/tensorflow/issues/55664#issuecomment-1102897855). Thanks, everyone. Now I am closing this issue.
