### ISSUE TITLE
[TRT] TF 2.9.0-rc0 ssd_mobilenet_v2 TRT FP16 conversion failed. (-1,-1,-1,3), float32

### ISSUE THREAD

**Issue by apivovarov** [tensorflow/tensorflow#55669]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.9.0-rc0

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 18.04

### Python version

3.7

### CUDA/cuDNN/TensorRT version

11.2 / 8.1.1.33 / 7.2.3-1

### GPU model and memory

Nvidia Tesla T4 16GB (aws g4dn.2xlarge)

### Current Behaviour?

```shell
ssd_mobilenet_v2 model is from TF2 model Zoo.
It was exported with `--input_type=float_image_tensor` parameter.
Exported model input is `<tf.Tensor 'input_tensor:0' shape=(None, None, None, 3) dtype=float32>`.

Converting the model to TRT with FP16 PrecisionMode fails.
Error: `ValueError: Received a shape scalar with unknown static value.  A static value of '-1' is required to represent an unknown shape.`

The conversion worked fine in TF 2.4, 2.6, 2.7, 2.8.
The issue started to happen in TF 2.9.0-rc0
```

### Standlone code to reproduce the issue
Download [SSD MobileNet v2 320x320](http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_mobilenet_v2_320x320_coco17_tpu-8.tar.gz) from [TensorFlow 2 Detection Model Zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md)

Export the model using `--input_type=float_image_tensor` parameter. 
It will create a model with input `<tf.Tensor 'input_tensor:0' shape=(None, None, None, 3) dtype=float32>`:
```shell
# Export the Model
MODEL=ssd_mobilenet_v2_320x320_coco17_tpu-8
python3 object_detection/exporter_main_v2.py \
    --input_type=float_image_tensor \
    --pipeline_config_path=$MODEL/pipeline.config \
    --trained_checkpoint_dir=$MODEL/checkpoint \
    --output_directory=output/${MODEL}_float32_batchN
```
Exported model can be downloaded from [here](https://www.dropbox.com/s/1uznvtf6u4czgot/ssd_mobilenet_v2_320x320_coco17_tpu-8_float32_batchN.tar.gz?dl=0)
```
# Convert the model to TRT FP16

cd output/ssd_mobilenet_v2_320x320_coco17_tpu-8_float32_batchN

import tensorflow as tf
from tensorflow.python.compiler.tensorrt import trt_convert as trt
conversion_params = trt.TrtConversionParams(precision_mode=trt.TrtPrecisionMode.FP16)
converter = trt.TrtGraphConverterV2(
    input_saved_model_dir="saved_model",
    conversion_params=conversion_params)
converter.convert()
```

### Relevant log output

```shell
>>> converter = trt.TrtGraphConverterV2(
...     input_saved_model_dir="saved_model",
...     conversion_params=conversion_params)
INFO:tensorflow:Linked TensorRT version: (7, 2, 2)
INFO:tensorflow:Loaded TensorRT version: (7, 2, 3)
INFO:tensorflow:Loaded TensorRT 7.2.3 and linked TensorFlow against TensorRT 7.2.2. This is supported because TensorRT minor/patch upgrades are backward compatible.
>>> converter.convert()
2022-04-19 18:59:33.559459: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-19 18:59:33.566342: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-19 18:59:33.568044: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-19 18:59:33.569815: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-19 18:59:33.570320: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-19 18:59:33.571871: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-19 18:59:33.573363: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-19 18:59:34.263138: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-19 18:59:34.264552: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-19 18:59:34.265704: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-19 18:59:34.266826: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13596 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:1e.0, compute capability: 7.5
2022-04-19 18:59:45.455700: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-19 18:59:45.457173: I tensorflow/core/grappler/devices.cc:66] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 1
2022-04-19 18:59:45.457334: I tensorflow/core/grappler/clusters/single_machine.cc:358] Starting new session
2022-04-19 18:59:45.457786: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-19 18:59:45.459086: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-19 18:59:45.460342: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-19 18:59:45.461644: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-19 18:59:45.462905: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-19 18:59:45.464134: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13596 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:1e.0, compute capability: 7.5
2022-04-19 18:59:53.296013: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-19 18:59:53.297496: I tensorflow/core/grappler/devices.cc:66] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 1
2022-04-19 18:59:53.297612: I tensorflow/core/grappler/clusters/single_machine.cc:358] Starting new session
2022-04-19 18:59:53.297949: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-19 18:59:53.299278: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-19 18:59:53.300541: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-19 18:59:53.301857: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-19 18:59:53.303121: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-19 18:59:53.304366: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13596 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:1e.0, compute capability: 7.5
2022-04-19 18:59:54.739820: W tensorflow/compiler/tf2tensorrt/convert/trt_optimization_pass.cc:186] Calibration with FP32 or FP16 is not implemented. Falling back to use_calibration = False.Note that the default value of use_calibration is True.
2022-04-19 18:59:54.922287: W tensorflow/compiler/tf2tensorrt/segment/segment.cc:952]

################################################################################
TensorRT unsupported/non-converted OP Report:
	- Placeholder -> 1267x
	- GatherV2 -> 390x
	- ConcatV2 -> 186x
	- Fill -> 184x
	- StridedSlice -> 133x
	- Sub -> 117x
	- Shape -> 117x
	- Reshape -> 113x
	- Slice -> 102x
	- Select -> 102x
	- AddV2 -> 100x
	- Less -> 94x
	- ZerosLike -> 92x
	- NonMaxSuppressionV5 -> 90x
	- Pack -> 35x
	- Merge -> 25x
	- Enter -> 25x
	- NextIteration -> 25x
	- Switch -> 25x
	- Mul -> 21x
	- Exit -> 20x
	- Identity -> 12x
	- Greater -> 12x
	- ExpandDims -> 10x
	- Cast -> 9x
	- TensorListSetItem -> 9x
	- TensorListFromTensor -> 8x
	- TensorListGetItem -> 8x
	- TensorListStack -> 8x
	- Pad -> 6x
	- DataFormatVecPermute -> 6x
	- Minimum -> 6x
	- Unpack -> 6x
	- TensorListReserve -> 4x
	- Split -> 4x
	- NoOp -> 4x
	- Maximum -> 4x
	- Range -> 3x
	- Transpose -> 3x
	- Tile -> 2x
	- TopKV2 -> 2x
	- Exp -> 2x
	- Reciprocal -> 2x
	- LoopCond -> 2x
	- LogicalAnd -> 2x
	- Sum -> 1x
	- Squeeze -> 1x
	- ResizeBilinear -> 1x
	- GreaterEqual -> 1x
	- Where -> 1x
--------------------------------------------------------------------------------
	- Total nonconverted OPs: 3402
	- Total nonconverted OP Types: 50
For more information see https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html#supported-ops.
################################################################################

2022-04-19 18:59:54.996948: W tensorflow/compiler/tf2tensorrt/segment/segment.cc:1280] The environment variable TF_TRT_MAX_ALLOWED_ENGINES=20 has no effect since there are only 3 TRT Engines with  at least minimum_segment_size=3 nodes.
2022-04-19 18:59:55.004054: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:795] Number of TensorRT candidate segments: 3
2022-04-19 18:59:55.057662: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:909] Replaced segment 0 consisting of 536 nodes by TRTEngineOp_000_000.
2022-04-19 18:59:55.058968: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:909] Replaced segment 1 consisting of 3 nodes by TRTEngineOp_000_001.
2022-04-19 18:59:55.059085: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:909] Replaced segment 2 consisting of 4 nodes by TRTEngineOp_000_002.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/compiler/tensorrt/trt_convert.py", line 1234, in convert
    [tensor.name for tensor in frozen_func.outputs])
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/wrap_function.py", line 659, in function_from_graph_def
    nest.map_structure(import_graph.as_graph_element, outputs))
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/wrap_function.py", line 336, in prune
    base_graph=self._func_graph)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/lift_to_graph.py", line 337, in lift_to_graph
    op=op, graph=graph, op_map=op_map, base_graph=base_graph)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/lift_to_graph.py", line 131, in _copy_non_source
    name=op.name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/deprecation.py", line 561, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 1963, in _create_c_op
    raise ValueError(e.message)
ValueError: Received a shape scalar with unknown static value.  A static value of '-1' is required to represent an unknown shape.
```
</details>

**Comment by apivovarov** [comment]
Workaround:
Because the issue is happening in a small segment we can skip converting it to TRT by increasing `minimum_segment_size` from 3 to 5.
```
conversion_params = trt.TrtConversionParams(precision_mode=trt.TrtPrecisionMode.FP16, 
                                            minimum_segment_size=5)
```

**Comment by apivovarov** [comment]
The issue started to happen after [PR-53171](https://github.com/tensorflow/tensorflow/pull/53171).
The change:
```
    rewriter_config_with_trt.optimizers.extend(
-        ["constfold", "layout", "constfold"])
+        ["pruning", "debug_stripper", "layout", "dependency", "constfold",
+         "common_subgraph_elimination"])
```

The issue can be resolved by removing `common_subgraph_elimination` from the list of optimizers
@Nyrio

**Comment by Nyrio** [comment]
Hi @apivovarov,
Thanks for reporting this error. I will look into this.

**Comment by Nyrio** [comment]
Hi @apivovarov,

I have made a simple reproducer without TF-TRT and opened the issue #55736

If you're interested in the details: the problem is that the model has a loop, and when reconstructing a function from the modified graph after Grappler optimization, TF fails to do a topological sort (undefined for cyclical graphs). This results in a non-deterministic non-topological order, and some nodes fail to be added if their inputs haven't been previously added. The common subgraph optimization is certainly a catalyser, but it is unclear if it is responsible for the bug.

We will reflect on whether something needs to be changed in TF-TRT.

**Comment by apivovarov** [comment]
Louis, thank you for looking into this!

Since the list of optimizers was changed in 2.9.0-rc0 from
```
"constfold", "layout", "constfold"
```
to
```
"pruning", "debug_stripper", "layout", "dependency", "constfold",  "common_subgraph_elimination"
```
And after that TF-TRT OD models tests started to fail I think it is better to use reduced list of optimizers in TF-TRT 2.9.0. e.g.
```
"pruning", "debug_stripper", "layout", "dependency", "constfold"
```
and add `"common_subgraph_elimination"` later when issue https://github.com/tensorflow/tensorflow/issues/55736 is resolved

**Comment by Nyrio** [comment]
@apivovarov @bixia1 I have opened #55820, which prevents these failures for the model you mentioned. It's not a full fix of the underlying TF bugs, but it should allow this model to convert successfully.

**Comment by tilakrayal** [comment]
@apivovarov,
The mentioned related PR https://github.com/tensorflow/tensorflow/pull/55820 has been merged and also as you mentioned above the `common_subgraph_elimination` from the list of optimizers in the mentioned file.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/compiler/tensorrt/test/tf_trt_integration_test_base.py

Also the code provided in the another [issue](https://github.com/tensorflow/tensorflow/issues/55736#issuecomment-1781508532)  also executed without any issues on both CPU and GPU with tensorflow v2.15. Thank you!
