### ISSUE TITLE
//tensorflow/tools/docs:tf_doctest fails on machines without GPU

### ISSUE THREAD

**Issue by elfringham** [tensorflow/tensorflow#55699]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

git HEAD

### Custom Code

No

### OS Platform and Distribution

CentOS 7

### Mobile device

n/a

### Python version

3.7.13

### Bazel version

5.1.1

### GCC/Compiler version

10.2.1

### CUDA/cuDNN version

n/a

### GPU model and memory

n/a

### Current Behaviour?

```shell
Unit test //tensorflow/tools/docs:tf_doctest fails when run on machine without GPU installed.
```

### Standalone code to reproduce the issue

```shell
bazel test --test_timeout=300,500,-1,-1 --flaky_test_attempts=3 --test_output=all --cache_test_results=no --noremote_accept_cached --config=nonccl --build_tag_filters=-no_oss,-oss_serial,-gpu,-tpu,-benchmark-test,-v1only,-no_aarch64,-requires-gpu --test_tag_filters=-no_oss,-oss_serial,-gpu,-tpu,-benchmark-test,-v1only,-no_aarch64,-requires-gpu --verbose_failures --build_tests_only -- //tensorflow/tools/docs:tf_doctest
```

### Relevant log output

```shell
Multiple instances similar to

----------------------------------------------------------------------
File "/root/.cache/bazel/_bazel_root/db210f68f81d95ddcca9ae96b16ed72c/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/tools/docs/tf_doctest.runfiles/org_tensorflow/tensorflow/python/types/distribute.py", line 156, in tensorflow.python.types.distribute.DistributedValues
Failed example:
    strategy = tf.distribute.MirroredStrategy(["GPU:0", "GPU:1"])
Exception raised:
    Traceback (most recent call last):
      File "/opt/python/cp37-cp37m/lib/python3.7/doctest.py", line 1337, in __run
        compileflags, 1), test.globs)
      File "<doctest tensorflow.python.types.distribute.DistributedValues[22]>", line 1, in <module>
        strategy = tf.distribute.MirroredStrategy(["GPU:0", "GPU:1"])
      File "/root/.cache/bazel/_bazel_root/db210f68f81d95ddcca9ae96b16ed72c/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/tools/docs/tf_doctest.runfiles/org_tensorflow/tensorflow/python/distribute/mirrored_strategy.py", line 287, in __init__
        self, devices=devices, cross_device_ops=cross_device_ops)
      File "/root/.cache/bazel/_bazel_root/db210f68f81d95ddcca9ae96b16ed72c/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/tools/docs/tf_doctest.runfiles/org_tensorflow/tensorflow/python/distribute/mirrored_strategy.py", line 342, in __init__
        self._initialize_strategy(devices)
      File "/root/.cache/bazel/_bazel_root/db210f68f81d95ddcca9ae96b16ed72c/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/tools/docs/tf_doctest.runfiles/org_tensorflow/tensorflow/python/distribute/mirrored_strategy.py", line 367, in _initialize_strategy
        self._collective_ops = self._make_collective_ops(devices)
      File "/root/.cache/bazel/_bazel_root/db210f68f81d95ddcca9ae96b16ed72c/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/tools/docs/tf_doctest.runfiles/org_tensorflow/tensorflow/python/distribute/mirrored_strategy.py", line 385, in _make_collective_ops
        collective_keys=self._collective_keys)
      File "/root/.cache/bazel/_bazel_root/db210f68f81d95ddcca9ae96b16ed72c/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/tools/docs/tf_doctest.runfiles/org_tensorflow/tensorflow/python/distribute/cross_device_ops.py", line 1104, in __init__
        group_key, group_size, self._collective_keys, device, options)
      File "/root/.cache/bazel/_bazel_root/db210f68f81d95ddcca9ae96b16ed72c/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/tools/docs/tf_doctest.runfiles/org_tensorflow/tensorflow/python/distribute/cross_device_utils.py", line 271, in __init__
        self._ordering_token = resource_variable_ops.ResourceVariable(0.)
      File "/root/.cache/bazel/_bazel_root/db210f68f81d95ddcca9ae96b16ed72c/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/tools/docs/tf_doctest.runfiles/org_tensorflow/tensorflow/python/util/traceback_utils.py", line 141, in error_handler
        return fn(*args, **kwargs)
      File "/root/.cache/bazel/_bazel_root/db210f68f81d95ddcca9ae96b16ed72c/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/tools/docs/tf_doctest.runfiles/org_tensorflow/tensorflow/python/ops/variables.py", line 268, in __call__
        return super(VariableMetaclass, cls).__call__(*args, **kwargs)
      File "/root/.cache/bazel/_bazel_root/db210f68f81d95ddcca9ae96b16ed72c/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/tools/docs/tf_doctest.runfiles/org_tensorflow/tensorflow/python/ops/resource_variable_ops.py", line 1670, in __init__
        validate_shape=validate_shape,
      File "/root/.cache/bazel/_bazel_root/db210f68f81d95ddcca9ae96b16ed72c/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/tools/docs/tf_doctest.runfiles/org_tensorflow/tensorflow/python/ops/resource_variable_ops.py", line 1817, in _init_from_args
        initial_value, name="initial_value", dtype=dtype)
      File "/root/.cache/bazel/_bazel_root/db210f68f81d95ddcca9ae96b16ed72c/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/tools/docs/tf_doctest.runfiles/org_tensorflow/tensorflow/python/profiler/trace.py", line 183, in wrapped
        return func(*args, **kwargs)
      File "/root/.cache/bazel/_bazel_root/db210f68f81d95ddcca9ae96b16ed72c/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/tools/docs/tf_doctest.runfiles/org_tensorflow/tensorflow/python/framework/ops.py", line 1640, in convert_to_tensor
        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
      File "/root/.cache/bazel/_bazel_root/db210f68f81d95ddcca9ae96b16ed72c/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/tools/docs/tf_doctest.runfiles/org_tensorflow/tensorflow/python/framework/tensor_conversion_registry.py", line 48, in _default_conversion_function
        return constant_op.constant(value, dtype, name=name)
      File "/root/.cache/bazel/_bazel_root/db210f68f81d95ddcca9ae96b16ed72c/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/tools/docs/tf_doctest.runfiles/org_tensorflow/tensorflow/python/framework/constant_op.py", line 268, in constant
        allow_broadcast=True)
      File "/root/.cache/bazel/_bazel_root/db210f68f81d95ddcca9ae96b16ed72c/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/tools/docs/tf_doctest.runfiles/org_tensorflow/tensorflow/python/framework/constant_op.py", line 279, in _constant_impl
        return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
      File "/root/.cache/bazel/_bazel_root/db210f68f81d95ddcca9ae96b16ed72c/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/tools/docs/tf_doctest.runfiles/org_tensorflow/tensorflow/python/framework/constant_op.py", line 304, in _constant_eager_impl
        t = convert_to_eager_tensor(value, ctx, dtype)
      File "/root/.cache/bazel/_bazel_root/db210f68f81d95ddcca9ae96b16ed72c/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/tools/docs/tf_doctest.runfiles/org_tensorflow/tensorflow/python/framework/constant_op.py", line 102, in convert_to_eager_tensor
        return ops.EagerTensor(value, ctx.device_name, dtype)
    tensorflow.python.framework.errors_impl.InvalidArgumentError: Could not satisfy device specification '/job:localhost/replica:0/task:0/device:GPU:0'. enable_soft_placement=0. Supported device types [CPU]. All available devices [/job:localhost/replica:0/task:0/device:CPU:0].
----------------------------------------------------------------------
File "/root/.cache/bazel/_bazel_root/db210f68f81d95ddcca9ae96b16ed72c/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/tools/docs/tf_doctest.runfiles/org_tensorflow/tensorflow/python/types/distribute.py", line 158, in tensorflow.python.types.distribute.DistributedValues
Failed example:
    dataset_iterator = iter(strategy.experimental_distribute_dataset(dataset))
Exception raised:
    Traceback (most recent call last):
      File "/opt/python/cp37-cp37m/lib/python3.7/doctest.py", line 1337, in __run
        compileflags, 1), test.globs)
      File "<doctest tensorflow.python.types.distribute.DistributedValues[24]>", line 1, in <module>
        dataset_iterator = iter(strategy.experimental_distribute_dataset(dataset))
    NameError: name 'strategy' is not defined
----------------------------------------------------------------------
File "/root/.cache/bazel/_bazel_root/db210f68f81d95ddcca9ae96b16ed72c/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/tools/docs/tf_doctest.runfiles/org_tensorflow/tensorflow/python/types/distribute.py", line 159, in tensorflow.python.types.distribute.DistributedValues
Failed example:
    per_replica_values = strategy.experimental_local_results(
       distributed_values)
Exception raised:
    Traceback (most recent call last):
      File "/opt/python/cp37-cp37m/lib/python3.7/doctest.py", line 1337, in __run
        compileflags, 1), test.globs)
      File "<doctest tensorflow.python.types.distribute.DistributedValues[25]>", line 1, in <module>
        per_replica_values = strategy.experimental_local_results(
    NameError: name 'strategy' is not defined
----------------------------------------------------------------------
File "/root/.cache/bazel/_bazel_root/db210f68f81d95ddcca9ae96b16ed72c/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/tools/docs/tf_doctest.runfiles/org_tensorflow/tensorflow/python/types/distribute.py", line 161, in tensorflow.python.types.distribute.DistributedValues
Failed example:
    per_replica_values
Exception raised:
    Traceback (most recent call last):
      File "/opt/python/cp37-cp37m/lib/python3.7/doctest.py", line 1337, in __run
        compileflags, 1), test.globs)
      File "<doctest tensorflow.python.types.distribute.DistributedValues[26]>", line 1, in <module>
        per_replica_values
    NameError: name 'per_replica_values' is not defined


----------------------------------------------------------------------
```
</details>

**Comment by elfringham** [comment]
@cfRod @nSircombe

**Comment by elfringham** [comment]
Introduced with commit https://github.com/tensorflow/tensorflow/commit/07e1274c3cd9c5cf52f6c6013c1205fc6e15473c

**Comment by elfringham** [comment]
Apparently resolved by https://github.com/tensorflow/tensorflow/commit/942f170b0e33d2a23ac8fca3c484bccb04615415
