### ISSUE TITLE
GPT-J saved_model conversion to fp16 TF-TRT errors with ``Message tensorflow.GraphDef exceeds maximum protobuf size of 2GB: 23499914257"

### ISSUE THREAD

**Issue by andoorve** [tensorflow/tensorflow#55692]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.8

### Custom Code

No

### OS Platform and Distribution

Ubuntu 20.04.3 LTS

### Python version

3.9

### CUDA/cuDNN version

11.4/8.1.0

### GPU model and memory

A100 40GB

### Current Behaviour?

I tried converting a saved_model of GPT-J using TF-TRT to an FP16 version. I ran into a problem with the protobuf size limit (log below), it seems the model is too large even though saving works correctly. The standalone code was executed using the tensorflow:latest-gpu image. The saved_model can be produced with the following snippet
```shell
from transformers import TFGPTJForSequenceClassification

model = TFGPTJForSequenceClassification.from_pretrained("EleutherAI/gpt-j-6B", revision="float16", from_pt=True)
# the saved_model parameter is a flag to create a SavedModel version of the model in same time than the h5 weights
model.save_pretrained("sequence_fp16_model", saved_model=True)
```
Expected Behaviour:
The saved_model should be converted into a TF-TRT version.

### Standlone code to reproduce the issue

```shell
from tensorflow.python.compiler.tensorrt import trt_convert as trt
converter = trt.TrtGraphConverterV2(input_saved_model_dir='<home_dir>/sequence_model/saved_model/1', precision_mode='FP16', use_dynamic_shape=True)
converter.convert()
converter.save('<home_dir>/seqfp16_model/saved_model/1')
```

### Relevant log output

```shell
2022-04-20 21:10:56.139648: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-20 21:10:56.733368: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 38420 MB memory:  -> device: 0, name: NVIDIA A100-SXM4-40GB, pci bus id: 0000:00:04.0, compute capability: 8.0
2022-04-20 21:11:38.182109: I tensorflow/core/grappler/devices.cc:66] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 1
2022-04-20 21:11:38.182325: I tensorflow/core/grappler/clusters/single_machine.cc:358] Starting new session
2022-04-20 21:11:38.184816: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 38420 MB memory:  -> device: 0, name: NVIDIA A100-SXM4-40GB, pci bus id: 0000:00:04.0, compute capability: 8.0
2022-04-20 21:11:39.502737: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:1164] Optimization results for grappler item: graph_to_optimize
  function_optimizer: Graph size after: 18132 nodes (17815), 21036 edges (20719), time = 829.118ms.
  function_optimizer: function_optimizer did nothing. time = 0.075ms.

Traceback (most recent call last):
  File "convert_to_fp16.py", line 3, in <module>
    converter.convert()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/compiler/tensorrt/trt_convert.py", line 1201, in convert
    frozen_func = convert_to_constants.convert_variables_to_constants_v2(func)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/convert_to_constants.py", line 1151, in convert_variables_to_constants_v2
    return _construct_concrete_function(func, output_graph_def,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/convert_to_constants.py", line 1076, in _construct_concrete_function
    new_func = wrap_function.function_from_graph_def(output_graph_def,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/wrap_function.py", line 655, in function_from_graph_def
    wrapped_import = wrap_function(_imports_graph_def, [])
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/wrap_function.py", line 619, in wrap_function
    func_graph.func_graph_from_py_func(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/func_graph.py", line 1161, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/wrap_function.py", line 83, in __call__
    return self.call_with_variable_creator_scope(self._fn)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/wrap_function.py", line 89, in wrapped
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/wrap_function.py", line 649, in _imports_graph_def
    importer.import_graph_def(graph_def, name="")
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/deprecation.py", line 548, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/importer.py", line 403, in import_graph_def
    return _import_graph_def_internal(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/importer.py", line 497, in _import_graph_def_internal
    with c_api_util.tf_buffer(graph_def.SerializeToString()) as serialized:
ValueError: Message tensorflow.GraphDef exceeds maximum protobuf size of 2GB: 23499914257
```
</details>

**Comment by kevint324** [comment]
@bixia1 @chunduriv @sushreebarsa 
any updates on this？

**Comment by tfeher** [comment]
Hi, thanks for the reminder! The error caused by the  protobuf size limit, it occurs for other large models as well (e.g. https://github.com/tensorflow/tensorrt/issues/255). 

We are currently working around this issue, by removing the graph freezing step. To enable the workaround, you can add
```python
import os
os.environ["TF_TRT_EXPERIMENTAL_FEATURES"]="disable_graph_freezing"
```
on top of your conversion script.

The `disable_graph_freezing` feature is experimental, and it needs actually to more PRs to be fully functional (#56050 and #56076).  Currently it depends on the actual representation of variables in the model, whether this will fix the issue.

Please give it a try and let us know how it goes.

**Comment by donglinz** [comment]
@tfeher Thank you for this workaround. Will try it out!

convert_variables_to_constants_v2 also hit this 2BG limitation when converting variables in saved model into constants. Do we have any workaround for this?
