### ISSUE TITLE
`function_from_graph_def` failure on a model with a loop after Grappler optimization

### ISSUE THREAD

**Issue by Nyrio** [tensorflow/tensorflow#55736]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.9

### Current Behaviour?

On a model with a loop (see simple reproducer below), `wrap_function.function_from_graph_def` fails with a `ValueError` (see log output below). This happens when the model has been frozen and optimized with Grappler. In particular, this seems to happen only if the `"common_subgraph_elimination"` optimizer is run.

I have some understanding of what is happening:
- `lift_to_graph` tries to do a topological sort of the graph. However, because of the loop, it is undefined, so some nodes are not in topological order.
- In `_copy_non_source`, when a node is processed and its inputs haven't been added to the `op_map` yet, a placeholder of the right shape and type is created.
- When the node needs to read its input int32 tensor to get a shape, if the input is a placeholder it results in the exception below.
- The bug is non-deterministic, which might be due to getting the next element in a Python set? So the failure is intermittent, with the pseudo-topological order sometimes being accidentally correct enough.

I'm not sure if the common subgraph elimination is necessary for this bug to happen, but so far I haven't reproduced it without it.

### Standalone code to reproduce the issue

```python
import tensorflow as tf
from tensorflow.python.grappler import tf_optimizer
from tensorflow.core.protobuf import meta_graph_pb2
from tensorflow.python.training.saver import export_meta_graph
from tensorflow.core.protobuf import config_pb2
from tensorflow.python.eager import wrap_function
from tensorflow.python.eager import context
from tensorflow.python.framework import convert_to_constants


class MyModel(tf.Module):
  """Simple Fibonacci model.
  To get this bug, I need a loop and two tensor arrays of the same dimensions,
  using a different dtype so the TensorListReserve nodes don't get merged.
  """
  @tf.function
  def __call__(self, n):
    ta = tf.TensorArray(tf.float32, size=n)
    tb = tf.TensorArray(tf.int32, size=n)
    ta = ta.write(0, 0.)
    ta = ta.write(1, 1.)
    tb = tb.write(0, 0)
    tb = tb.write(1, 1)

    for i in range(2, n):
      ta = ta.write(i, ta.read(i - 1) + ta.read(i - 2))
      tb = tb.write(i, tb.read(i - 1) + tb.read(i - 2))

    return ta.stack() + tf.cast(tb.stack(), dtype=tf.float32)


def run_grappler(func, graph_def):
  meta_graph = export_meta_graph(graph_def=graph_def, graph=func.graph)

  # Add a collection 'train_op' so that Grappler knows the outputs.
  fetch_collection = meta_graph_pb2.CollectionDef()
  for array in func.inputs + func.outputs:
    fetch_collection.node_list.value.append(array.name)
  meta_graph.collection_def["train_op"].CopyFrom(fetch_collection)

  # Configure Grappler to execute one pass of common subgraph elimination.
  config = config_pb2.ConfigProto()
  rewrite_options = config.graph_options.rewrite_options
  rewrite_options.optimizers.extend([
    "common_subgraph_elimination"
  ])
  rewrite_options.meta_optimizer_iterations = 1
  return tf_optimizer.OptimizeGraph(config, meta_graph)

my_model = MyModel()
func = my_model.__call__.get_concrete_function(
    tf.TensorSpec([], tf.int32))

# Freeze the function
frozen_func = convert_to_constants.convert_variables_to_constants_v2(func)

# Run common subgraph elimination
graph_def = frozen_func.graph.as_graph_def()
new_graph_def = run_grappler(func, graph_def)

# Remove the old functions from the context
for f in new_graph_def.library.function:
  while context.context().has_function(f.signature.name):
    context.context().remove_function(f.signature.name)

# Reconstruct a function from the graph definition
new_func = wrap_function.function_from_graph_def(
    new_graph_def,
    [tensor.name for tensor in frozen_func.inputs],
    [tensor.name for tensor in frozen_func.outputs])
```

### Relevant log output

```
Traceback (most recent call last):
  File "reproducer.py", line 67, in <module>
    new_func = wrap_function.function_from_graph_def(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/wrap_function.py", line 657, in function_from_graph_def
    return wrapped_import.prune(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/wrap_function.py", line 332, in prune
    lift_map = lift_to_graph.lift_to_graph(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/lift_to_graph.py", line 336, in lift_to_graph
    new_input_mutations, new_control_mutations = _copy_non_source(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/lift_to_graph.py", line 122, in _copy_non_source
    copied_op = graph.create_op(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/deprecation.py", line 561, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py", line 1970, in _create_c_op
    raise ValueError(e.message)
ValueError: Received a shape scalar with unknown static value.  A static value of '-1' is required to represent an unknown shape.
```
</details>

**Comment by tilakrayal** [comment]
@sachinprasadhs ,
I was able to reproduce the issue in tf v2.7, v2.8 and nightly.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/b4dd948df3412185a3cb46be70a3aff9/55736.ipynb).

**Comment by Nyrio** [comment]
Hi, the PR mentioned above solves the exception for the given code sample, but it isn't an exhaustive fix, only a temporary solution for some failing models.
