### ISSUE TITLE
tensorflow_datasets AttributeError: module 'distutils' has no attribute 'version' 

### ISSUE THREAD

**Issue by iwen-kang** [tensorflow/tensorflow#55744]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

binary

### Tensorflow Version

tf 2.6

### Custom Code

No

### OS Platform and Distribution

Linux

### Python version

3.7

### CUDA/cuDNN version

11.2/8.1

### Current Behaviour?

```shell
Previous tensorflow_datasets pip install worked fine: 
pip install tensorflow==2.6
pip install keras==2.6.0 
pip install --upgrade tensorflow-hub
pip install tensorflow_datasets

Just found that same pip install tensorflow_datasets broke last night:
Requirement already satisfied: six in ./anaconda3/envs/py37/lib/python3.7/site-packages (from tensorflow_datasets) (1.15.0)
Requirement already satisfied: typing-extensions; python_version < "3.8" in ./anaconda3/envs/py37/lib/python3.7/site-packages (from tensorflow_datasets) (3.7.4.3)
Collecting importlib-resources; python_version < "3.9"
Downloading https://pypi.apple.com/packages/packages/bd/4d/19cb95029e824d878d5d13b62825839b5b024a62706ea308781a9e2cf534/importlib_resources-5.7.1-py3-none-any.whl (28 kB)
Requirement already satisfied: requests>=2.19.0 in ./anaconda3/lib/python3.7/site-packages (from tensorflow_datasets) (2.22.0)
Collecting promise
Downloading https://pypi.apple.com/packages/packages/cf/9c/fb5d48abfe5d791cd496e4242ebcf87a4bb2e0c3dcd6e0ae68c11426a528/promise-2.3.tar.gz (19 kB)
Collecting googleapis-common-protos<2,>=1.52.0
Downloading https://pypi.apple.com/packages/packages/bd/f7/3b5b207a008cf5a15d623c96c59c8bc3663d4ac2618e23602a0dc2b99808/googleapis_common_protos-1.56.0-py2.py3-none-any.whl (241 kB)
Collecting zipp>=3.1.0; python_version < "3.10"
Downloading https://pypi.apple.com/packages/packages/80/0e/16a7ee38617aab6a624e95948d314097cc2669edae9b02ded53309941cfc/zipp-3.8.0-py3-none-any.whl (5.4 kB)
Requirement already satisfied: certifi>=2017.4.17 in ./anaconda3/lib/python3.7/site-packages (from requests>=2.19.0->tensorflow_datasets) (2019.11.28)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./anaconda3/lib/python3.7/site-packages (from requests>=2.19.0->tensorflow_datasets) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./anaconda3/lib/python3.7/site-packages (from requests>=2.19.0->tensorflow_datasets) (1.25.8)
Requirement already satisfied: idna<2.9,>=2.5 in ./anaconda3/lib/python3.7/site-packages (from requests>=2.19.0->tensorflow_datasets) (2.8)
Building wheels for collected packages: promise
  Building wheel for promise (setup.py): started
  Building wheel for promise (setup.py): finished with status 'done'
  Created wheel for promise: filename=promise-2.3-py3-none-any.whl size=21494 sha256=763fed2298136d167ce5bfb16930dbf4349c9f263a73bb8ac00027cb43de1d48
  Stored in directory: /root/.cache/pip/wheels/0b/1b/71/56b96659fcf28d2983ad511ceadabf12ca962ee5face504f40
Successfully built promise
Installing collected packages: dill, googleapis-common-protos, tensorflow-metadata, zipp, importlib-resources, promise, tensorflow-datasets
  Attempting uninstall: zipp
    Found existing installation: zipp 2.2.0
    Uninstalling zipp-2.2.0:
      Successfully uninstalled zipp-2.2.0
Successfully installed dill-0.3.4 googleapis-common-protos-1.56.0 importlib-resources-5.7.1 promise-2.3 tensorflow-datasets-4.5.2 tensorflow-metadata-1.7.0 zipp-3.8.0

Although pip install was successful but looks like there's a version conflict issue, it throws AttributeError from tensorflow_datasets.core import tf_compat:

Traceback (most recent call last):
  File "nt_qrewrite/data_pipeline.py", line 42, in <module>
    import tensorflow_datasets as tfds
  File "/mnt/task_runtime/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_datasets/__init__.py", line 43, in <module>
    from tensorflow_datasets.core import tf_compat
  File "/mnt/task_runtime/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_datasets/core/__init__.py", line 22, in <module>
    tf_compat.ensure_tf_install()
  File "/mnt/task_runtime/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_datasets/core/tf_compat.py", line 60, in ensure_tf_install
    tf_version = distutils.version.LooseVersion(tf.__version__)
AttributeError: module 'distutils' has no attribute 'version'

Please advise how to fix this. Thanks!
```

### Standalone code to reproduce the issue

```shell
pip install tensorflow==2.6
pip install keras==2.6.0 
pip install --upgrade tensorflow-hub
pip install tensorflow_datasets
python -c "import tensorflow_datasets as tfds; print('tfds.__version__:' + tfds.__version__)"
```

### Relevant log output

```shell
Collecting dill
Downloading https://pypi.apple.com/packages/packages/b6/c3/973676ceb86b60835bb3978c6db67a5dc06be6cfdbd14ef0f5a13e3fc9fd/dill-0.3.4-py2.py3-none-any.whl (86 kB)
Collecting tensorflow-metadata
Downloading https://pypi.apple.com/packages/packages/ed/c4/e4fa9d2725eff8eeed00f2c959d1cbb0a7f027f46ea36b9987b99d4e0d8c/tensorflow_metadata-1.7.0-py3-none-any.whl (48 kB)
Requirement already satisfied: six in ./anaconda3/envs/py37/lib/python3.7/site-packages (from tensorflow_datasets) (1.15.0)
Requirement already satisfied: typing-extensions; python_version < "3.8" in ./anaconda3/envs/py37/lib/python3.7/site-packages (from tensorflow_datasets) (3.7.4.3)
Collecting importlib-resources; python_version < "3.9"
Downloading https://pypi.apple.com/packages/packages/bd/4d/19cb95029e824d878d5d13b62825839b5b024a62706ea308781a9e2cf534/importlib_resources-5.7.1-py3-none-any.whl (28 kB)
Requirement already satisfied: requests>=2.19.0 in ./anaconda3/lib/python3.7/site-packages (from tensorflow_datasets) (2.22.0)
Collecting promise
Downloading https://pypi.apple.com/packages/packages/cf/9c/fb5d48abfe5d791cd496e4242ebcf87a4bb2e0c3dcd6e0ae68c11426a528/promise-2.3.tar.gz (19 kB)
Collecting googleapis-common-protos<2,>=1.52.0
Downloading https://pypi.apple.com/packages/packages/bd/f7/3b5b207a008cf5a15d623c96c59c8bc3663d4ac2618e23602a0dc2b99808/googleapis_common_protos-1.56.0-py2.py3-none-any.whl (241 kB)
Collecting zipp>=3.1.0; python_version < "3.10"
Downloading https://pypi.apple.com/packages/packages/80/0e/16a7ee38617aab6a624e95948d314097cc2669edae9b02ded53309941cfc/zipp-3.8.0-py3-none-any.whl (5.4 kB)
Requirement already satisfied: certifi>=2017.4.17 in ./anaconda3/lib/python3.7/site-packages (from requests>=2.19.0->tensorflow_datasets) (2019.11.28)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./anaconda3/lib/python3.7/site-packages (from requests>=2.19.0->tensorflow_datasets) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./anaconda3/lib/python3.7/site-packages (from requests>=2.19.0->tensorflow_datasets) (1.25.8)
Requirement already satisfied: idna<2.9,>=2.5 in ./anaconda3/lib/python3.7/site-packages (from requests>=2.19.0->tensorflow_datasets) (2.8)
Building wheels for collected packages: promise
  Building wheel for promise (setup.py): started
  Building wheel for promise (setup.py): finished with status 'done'
  Created wheel for promise: filename=promise-2.3-py3-none-any.whl size=21494 sha256=763fed2298136d167ce5bfb16930dbf4349c9f263a73bb8ac00027cb43de1d48
  Stored in directory: /root/.cache/pip/wheels/0b/1b/71/56b96659fcf28d2983ad511ceadabf12ca962ee5face504f40
Successfully built promise
Installing collected packages: dill, googleapis-common-protos, tensorflow-metadata, zipp, importlib-resources, promise, tensorflow-datasets
  Attempting uninstall: zipp
    Found existing installation: zipp 2.2.0
    Uninstalling zipp-2.2.0:
      Successfully uninstalled zipp-2.2.0
Successfully installed dill-0.3.4 googleapis-common-protos-1.56.0 importlib-resources-5.7.1 promise-2.3 tensorflow-datasets-4.5.2 tensorflow-metadata-1.7.0 zipp-3.8.0

Traceback (most recent call last):
  File "nt_qrewrite/data_pipeline.py", line 42, in <module>
    import tensorflow_datasets as tfds
  File "/mnt/task_runtime/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_datasets/__init__.py", line 43, in <module>
    from tensorflow_datasets.core import tf_compat
  File "/mnt/task_runtime/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_datasets/core/__init__.py", line 22, in <module>
    tf_compat.ensure_tf_install()
  File "/mnt/task_runtime/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_datasets/core/tf_compat.py", line 60, in ensure_tf_install
    tf_version = distutils.version.LooseVersion(tf.__version__)
AttributeError: module 'distutils' has no attribute 'version'
```
</details>

**Comment by sushreebarsa** [comment]
@iwen-kang I tried to replicate the issue on colab using TF v2.8.0 and didn't face any issue as reported here.Could you please have a look at this [gist ](https://colab.research.google.com/gist/sushreebarsa/c1145e6fd97f48db03fb1271357aad6c/55744.ipynb)and try with the latest TF version ?Please let us know if it helps? Thank you!
