### ISSUE TITLE
How to load TF1 `.ckpt` weights into keras model?

### ISSUE THREAD

**Issue by unsignedrant** [tensorflow/tensorflow#55763]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Source

binary

### Tensorflow Version

1.14

### Custom Code

Yes

### OS Platform and Distribution

macOS Monterey 12.3.1

### Python version

3.7

### Current Behaviour?

```shell
The code below creates a TF1 model, saves weights as `.ckpt`, creates an identical keras model. The objective is to load the saved weights from TF1 somehow using `tf.keras.Model.load_weights()` or whatever works.
```

### Standalone code to reproduce the issue

```python
  import os
  import tempfile
  import uuid
  from pathlib import Path
  
  import tensorflow as tf
  from tensorflow.keras import Input, Model
  from tensorflow.keras.layers import Conv2D, MaxPooling2D
  
  
  def create_tf1_model(saver=None, tf1_weights=None):
      x0 = tf.placeholder(tf.float32, shape=[None, None, None, 3])
      x = tf.contrib.slim.conv2d(
          x0,
          32,
          (7, 7),
          stride=(2, 2),
          padding='same',
      )
      x = tf.contrib.slim.conv2d(
          x,
          64,
          (3, 3),
          stride=(1, 1),
      )
      x = tf.contrib.slim.max_pool2d(x, [3, 3], stride=2)
      if saver and tf1_weights:
          ckpt_state = tf.train.get_checkpoint_state(tf1_weights)
          model_path = os.path.join(
              tf1_weights, os.path.basename(ckpt_state.model_checkpoint_path)
          )
          saver.restore(sess, model_path)
      return x
  
  
  def create_keras_model():
      x0 = Input((None, None, 3))
      x = Conv2D(32, (7, 7), (2, 2), 'same')(x0)
      x = Conv2D(64, (3, 3))(x)
      x = MaxPooling2D((3, 3), (2, 2))(x)
      return Model(x0, x)
  
  
  if __name__ == '__main__':
      global_step = tf.get_variable(
          'global_step', [], initializer=tf.constant_initializer(0), trainable=False
      )
      variable_averages = tf.train.ExponentialMovingAverage(0.997, global_step)
      _saver = tf.train.Saver(variable_averages.variables_to_restore())
      sess = tf.Session(config=tf.ConfigProto(allow_soft_placement=True))
      sess.run(tf.global_variables_initializer())
      tmpdir = tempfile.mkdtemp()
      create_tf1_model()
      weights_path = Path(tmpdir) / f'{uuid.uuid4()}.ckpt'
      _saver.save(sess, weights_path.as_posix())
      create_tf1_model(_saver, weights_path.parent.as_posix())
      keras_model = create_keras_model()
      keras_model.load_weights(weights_path.as_posix())  # code fails here
```

### Relevant log output

```shell
/Users/emadboctor/Desktop/ocr/eastenv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/emadboctor/Desktop/ocr/eastenv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/emadboctor/Desktop/ocr/eastenv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/emadboctor/Desktop/ocr/eastenv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/Users/emadboctor/Desktop/ocr/eastenv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/Users/emadboctor/Desktop/ocr/eastenv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/Users/emadboctor/Desktop/ocr/eastenv/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/emadboctor/Desktop/ocr/eastenv/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/emadboctor/Desktop/ocr/eastenv/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/emadboctor/Desktop/ocr/eastenv/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/Users/emadboctor/Desktop/ocr/eastenv/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/Users/emadboctor/Desktop/ocr/eastenv/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
WARNING:tensorflow:From /Users/emadboctor/Library/Application Support/JetBrains/PyCharm2022.1/scratches/scratch_1.py:45: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

WARNING:tensorflow:From /Users/emadboctor/Library/Application Support/JetBrains/PyCharm2022.1/scratches/scratch_1.py:49: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

WARNING:tensorflow:From /Users/emadboctor/Library/Application Support/JetBrains/PyCharm2022.1/scratches/scratch_1.py:50: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From /Users/emadboctor/Library/Application Support/JetBrains/PyCharm2022.1/scratches/scratch_1.py:50: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

2022-04-27 08:21:58.963602: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
WARNING:tensorflow:From /Users/emadboctor/Library/Application Support/JetBrains/PyCharm2022.1/scratches/scratch_1.py:51: The name tf.global_variables_initializer is deprecated. Please use tf.compat.v1.global_variables_initializer instead.

WARNING:tensorflow:From /Users/emadboctor/Library/Application Support/JetBrains/PyCharm2022.1/scratches/scratch_1.py:12: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From /Users/emadboctor/Desktop/ocr/eastenv/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
WARNING:tensorflow:From /Users/emadboctor/Desktop/ocr/eastenv/lib/python3.7/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:From /Users/emadboctor/Desktop/ocr/eastenv/lib/python3.7/site-packages/tensorflow/python/training/tracking/util.py:1200: NameBasedSaverStatus.__init__ (from tensorflow.python.training.tracking.util) is deprecated and will be removed in a future version.
Instructions for updating:
Restoring a name-based tf.train.Saver checkpoint using the object-based restore API. This mode uses global names to match variables, and so is somewhat fragile. It also adds new restore ops to the graph each time it is called when graph building. Prefer re-encoding training checkpoints in the object-based format: run save() on the object-based saver (the same one this message is coming from) and use that checkpoint in the future.
Traceback (most recent call last):
  File "/Users/emadboctor/Library/Application Support/JetBrains/PyCharm2022.1/scratches/scratch_1.py", line 58, in <module>
    keras_model.load_weights(weights_path.as_posix())  # code fails here
  File "/Users/emadboctor/Desktop/ocr/eastenv/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 162, in load_weights
    return super(Model, self).load_weights(filepath, by_name)
  File "/Users/emadboctor/Desktop/ocr/eastenv/lib/python3.7/site-packages/tensorflow/python/keras/engine/network.py", line 1400, in load_weights
    trackable_utils.streaming_restore(status=status, session=session)
  File "/Users/emadboctor/Desktop/ocr/eastenv/lib/python3.7/site-packages/tensorflow/python/training/tracking/util.py", line 619, in streaming_restore
    "Streaming restore not supported from name-based checkpoints when "
NotImplementedError: Streaming restore not supported from name-based checkpoints when graph building. File a feature request if this limitation bothers you. As a workaround, consider either using tf.train.Checkpoint to load name-based checkpoints or enabling eager execution.
```
</details>

**Comment by tilakrayal** [comment]
Hello @unsignedrant ,
We see that you are using tf version 1.14, 1.x is not actively supported, please update to latest stable v2.8 and let us know if you are facing same issue.Thanks!

**Comment by unsignedrant** [comment]
I'm converting 1.14 code to 2.8 so to do so, I need to run it in 1.14 and it doesn't really matter, the same issue will happen at any given version.

**Comment by tilakrayal** [comment]
@unsignedrant ,
The provided code is related to tf1 version.Can you please provide the latest version code to reproduce the issue.It helps to debug the issue.Thanks!

**Comment by unsignedrant** [comment]
I provided both codes for creating 1.x model, 2.x keras model and a demonstration of what I'm trying to achieve which again is loading weights produced by tf1 code into keras model. If you think something is preventing you from reproducing the issue, please be specific about what it is.

**Comment by tilakrayal** [comment]
@unsignedrant ,
I was facing different issue while reproducing the mentioned code.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/b82242174fbf9a1f2fc909fd4dd0592c/untitled324.ipynb) and provide the reproducible tf v2.x code.It helps to analyse the issue.Thanks!

**Comment by unsignedrant** [comment]
I don't know how many times I'll have to repeat the same information over and over. The colab notebook you sent runs tensorflow 2.8, and for the 623754th time: **TO RUN THE CODE YOU NEED TF 1.X**. Once you obtain the weights produced by **TF 1.X**, you can then load the weights in **TF2.x**.

**Comment by tilakrayal** [comment]
@unsignedrant ,
Thanks for opening this issue. Development of keras moved to another [repository](https://github.com/keras-team/keras/issues). 
 
 
Can you please post this issue on keras-team/keras [repo](https://github.com/keras-team/keras/issues).
To know more refer:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!

**Comment by unsignedrant** [comment]
here's an activity

**Comment by tilakrayal** [comment]
@unsignedrant ,

As suggested, Thanks for opening this issue. Development of keras moved to another [repository](https://github.com/keras-team/keras/issues).

Can you please post this issue on keras-team/keras [repo](https://github.com/keras-team/keras/issues).
To know more refer:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!
