### ISSUE TITLE
Build C++ interface with CUDA on CentOS 8

### ISSUE THREAD

**Issue by hoba87** [tensorflow/tensorflow#55786]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.3.4, 2.4.4, 2.5.3, 2.6.3, 2.7.1, 2.8.0

### Custom Code

No

### OS Platform and Distribution

CentOS 8.5

### Python version

3.7.9

### Bazel version

3.1.0, 3.7.2, 4.2.1 depending on tf version

### GCC/Compiler version

gcc 8.5.0

### CUDA/cuDNN version

11.4 / 8

### GPU model and memory

A10

### Current Behaviour?

```shell
Compilation without CUDA works (at least for 2.3.4 and 2.8.0). But when trying to compile with CUDA, there are bazel dependency rule errors.
Trying to fix these errors by manipulating several BUILD.bazel files lead to a linker error.
```

### Standalone code to reproduce the issue

```shell
bazel --host_jvm_args="-Djavax.net.ssl.trustStore=/usr/lib/jvm/jre-1.8.0/lib/security/cacerts" build -c opt --verbose_failures --copt=-msse4.2 --copt=-mavx --copt=-mavx2 --copt=-mfma //tensorflow:libtensorflow_cc.so

bazel --host_jvm_args="-Djavax.net.ssl.trustStore=/usr/lib/jvm/jre-1.8.0/lib/security/cacerts" build -c opt --verbose_failures --copt=-msse4.2 --copt=-mavx --copt=-mavx2 --copt=-mfma --ignore_unsupported_sandboxing --genrule_strategy=standalone --spawn_strategy=standalone -s //tensorflow:libtensorflow_cc.so
```

### Relevant log output

```shell
# Dependency Error

SUBCOMMAND: # @local_config_cuda//cuda:cuda-include [action 'Executing genrule @local_config_cuda//cuda:cuda-include', configuration: 66f33c3c630191b83595d548feb993a615231a70b964ed630e032476da6f4e55, execution platform: @local_execution_config_platform//:platform]
(cd /root/.cache/bazel/_bazel_root/3d2810fb01b0f5b49453827b3eb9fb3e/execroot/org_tensorflow && \
  exec env - \
    CUDA_TOOLKIT_PATH=/opt/nvidia/cuda-11.4 \
    GCC_HOST_COMPILER_PATH=/bin/gcc \
    LD_LIBRARY_PATH=/opt/nvidia/cuda-11.4/lib64:/opt/nvidia/cuda-11.4/lib64/stubs:/opt/nvidia/cuda-11.4/lib/lib64:/opt/nvidia/cuda-11.4/targets/x86_64-linux/lib:/opt/nvidia/cuda-11.4/extras/CUPTI/lib64:/opt/openmpi/openmpi-4.0.5/lib:/opt/pmix/pmix-3.1.5/lib:/opt/python/python-3.7.9/lib:/usr/lib64:/opt/hdf5/hdf5-1.10.7/lib:/opt/libctl/libctl-4.5.0/lib:/opt/openblas/openblas-0.3.10/lib:/opt/fftw/fftw-3.3.8/lib:/opt/harminv/harminv-1.4.1/lib:/opt/nlopt/nlopt-2.6.2/lib64:/opt/gsl/gsl-2.6/lib:/opt/libgdsii/libgdsii-0.21/lib:/opt/mpb/mpb-1.10.0/lib:/opt/opencascade/opencascade-7.4.0/lib:/opt/ffmpeg/ffmpeg-4.3.1/lib:/opt/netcdf/netcdf-c-4.7.4-f-4.5.3/lib:/opt/scalapack/scalapack-2.1.0/lib:/opt/berkeleygw/berkeleygw-2.1/lib:/opt/pnfft/pnfft-1.0.7-alpha/lib:/opt/pfft/pfft-1.0.8-alpha/lib:/opt/libvdwxc/libvdwxc-0.4.0/lib:/opt/libxc/libxc-4.3.4/lib: \
    PATH=/opt/bazel/bazel-3.7.2/bin:/opt/bazel/bazel-4.2.1/bin:/opt/bazel/bazel-4.2.2/bin:/opt/nvidia/cuda-11.4/bin:/opt/openmpi/openmpi-4.0.5/bin:/opt/pmix/pmix-3.1.5/bin:/opt/python/python-3.7.9/bin:/opt/hdf5/hdf5-1.10.7/bin:/opt/libctl/libctl-4.5.0/bin:/opt/h5utils/h5utils-1.13.1/bin:/opt/ffmpeg/ffmpeg-4.3.1/bin:/opt/netcdf/netcdf-c-4.7.4-f-4.5.3/bin:/opt/berkeleygw/berkeleygw-2.1/bin:/opt/harminv/harminv-1.4.1/bin:/opt/mpb/mpb-1.10.0/bin:/opt/gmsh/gmsh-4.8.4/bin:/usr/share/Modules/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/slurm/slurm-20.02.5/bin: \
    PYTHONPATH=/opt/python/python-3.7.9/lib: \
    PYTHON_BIN_PATH=/opt/python/python-3.7.9/bin/python3 \
    PYTHON_LIB_PATH=/opt/python/python-3.7.9/lib \
    TF2_BEHAVIOR=1 \
    TF_CUDA_COMPUTE_CAPABILITIES=7.0,7.5,8.6 \
    TF_CUDA_PATHS=/opt/nvidia/cuda-11.4 \
    TF_CUDA_VERSION=11 \
    TF_CUDNN_VERSION=8 \
    TF_NCCL_VERSION='' \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; cp -rLf "/opt/nvidia/cuda-11.4/targets/x86_64-linux/include/." "bazel-out/k8-opt/bin/external/local_config_cuda/cuda/cuda/include/" ')
ERROR: /root/.cache/bazel/_bazel_root/3d2810fb01b0f5b49453827b3eb9fb3e/external/com_google_protobuf/BUILD:110:11: undeclared inclusion(s) in rule '@com_google_protobuf//:protobuf_lite':
this rule is missing dependency declarations for the following files included by 'com_google_protobuf/src/google/protobuf/io/zero_copy_stream.cc':
  '/include/c++/8/string'
  '/include/c++/8/x86_64-redhat-linux/bits/c++config.h'
  '/include/c++/8/x86_64-redhat-linux/bits/os_defines.h'
  '/include/c++/8/x86_64-redhat-linux/bits/cpu_defines.h'
  '/include/c++/8/bits/stringfwd.h'
  '/include/c++/8/bits/memoryfwd.h'
  '/include/c++/8/bits/char_traits.h'
  '/include/c++/8/bits/stl_algobase.h'
  '/include/c++/8/bits/functexcept.h'
  '/include/c++/8/bits/exception_defines.h'
  '/include/c++/8/bits/cpp_type_traits.h'
  '/include/c++/8/ext/type_traits.h'
  '/include/c++/8/ext/numeric_traits.h'
  '/include/c++/8/bits/stl_pair.h'
  '/include/c++/8/bits/move.h'
  '/include/c++/8/bits/concept_check.h'
  '/include/c++/8/type_traits'
  '/include/c++/8/bits/stl_iterator_base_types.h'
  '/include/c++/8/bits/stl_iterator_base_funcs.h'
  '/include/c++/8/debug/assertions.h'
  '/include/c++/8/bits/stl_iterator.h'
  '/include/c++/8/bits/ptr_traits.h'
  '/include/c++/8/debug/debug.h'
  '/include/c++/8/bits/predefined_ops.h'
  '/include/c++/8/bits/postypes.h'
  '/include/c++/8/cwchar'
  '/lib/gcc/x86_64-redhat-linux/8/include/stddef.h'
  '/lib/gcc/x86_64-redhat-linux/8/include/stdarg.h'
  '/include/c++/8/cstdint'
  '/lib/gcc/x86_64-redhat-linux/8/include/stdint.h'
  '/include/c++/8/bits/allocator.h'
  '/include/c++/8/x86_64-redhat-linux/bits/c++allocator.h'
  '/include/c++/8/ext/new_allocator.h'
  '/include/c++/8/new'
  '/include/c++/8/exception'
  '/include/c++/8/bits/exception.h'
  '/include/c++/8/bits/exception_ptr.h'
  '/include/c++/8/bits/cxxabi_init_exception.h'
  '/include/c++/8/typeinfo'
  '/include/c++/8/bits/hash_bytes.h'
  '/include/c++/8/bits/nested_exception.h'
  '/include/c++/8/bits/localefwd.h'
  '/include/c++/8/x86_64-redhat-linux/bits/c++locale.h'
  '/include/c++/8/clocale'
  '/include/c++/8/iosfwd'
  '/include/c++/8/cctype'
  '/include/c++/8/bits/ostream_insert.h'
  '/include/c++/8/bits/cxxabi_forced.h'
  '/include/c++/8/bits/stl_function.h'
  '/include/c++/8/backward/binders.h'
  '/include/c++/8/bits/range_access.h'
  '/include/c++/8/initializer_list'
  '/include/c++/8/bits/basic_string.h'
  '/include/c++/8/ext/atomicity.h'
  '/include/c++/8/x86_64-redhat-linux/bits/gthr.h'
  '/include/c++/8/x86_64-redhat-linux/bits/gthr-default.h'
  '/include/c++/8/x86_64-redhat-linux/bits/atomic_word.h'
  '/include/c++/8/ext/alloc_traits.h'
  '/include/c++/8/bits/alloc_traits.h'
  '/include/c++/8/ext/string_conversions.h'
  '/include/c++/8/cstdlib'
  '/include/c++/8/bits/std_abs.h'
  '/include/c++/8/cstdio'
  '/include/c++/8/cerrno'
  '/include/c++/8/bits/functional_hash.h'
  '/include/c++/8/bits/basic_string.tcc'
  '/include/c++/8/algorithm'
  '/include/c++/8/utility'
  '/include/c++/8/bits/stl_relops.h'
  '/include/c++/8/bits/stl_algo.h'
  '/include/c++/8/bits/algorithmfwd.h'
  '/include/c++/8/bits/stl_heap.h'
  '/include/c++/8/bits/stl_tempbuf.h'
  '/include/c++/8/bits/stl_construct.h'
  '/include/c++/8/bits/uniform_int_dist.h'
  '/include/c++/8/limits'
  '/include/c++/8/iostream'
  '/include/c++/8/ostream'
  '/include/c++/8/ios'
  '/include/c++/8/bits/ios_base.h'
  '/include/c++/8/bits/locale_classes.h'
  '/include/c++/8/bits/locale_classes.tcc'
  '/include/c++/8/system_error'
  '/include/c++/8/x86_64-redhat-linux/bits/error_constants.h'
  '/include/c++/8/stdexcept'
  '/include/c++/8/streambuf'
  '/include/c++/8/bits/streambuf.tcc'
  '/include/c++/8/bits/basic_ios.h'
  '/include/c++/8/bits/locale_facets.h'
  '/include/c++/8/cwctype'
  '/include/c++/8/x86_64-redhat-linux/bits/ctype_base.h'
  '/include/c++/8/bits/streambuf_iterator.h'
  '/include/c++/8/x86_64-redhat-linux/bits/ctype_inline.h'
  '/include/c++/8/bits/locale_facets.tcc'
  '/include/c++/8/bits/basic_ios.tcc'
  '/include/c++/8/bits/ostream.tcc'
  '/include/c++/8/istream'
  '/include/c++/8/bits/istream.tcc'
  '/include/c++/8/map'
  '/include/c++/8/bits/stl_tree.h'
  '/include/c++/8/ext/aligned_buffer.h'
  '/include/c++/8/bits/stl_map.h'
  '/include/c++/8/tuple'
  '/include/c++/8/array'
  '/include/c++/8/bits/uses_allocator.h'
  '/include/c++/8/bits/invoke.h'
  '/include/c++/8/bits/stl_multimap.h'
  '/include/c++/8/memory'
  '/include/c++/8/bits/stl_uninitialized.h'
  '/include/c++/8/bits/stl_raw_storage_iter.h'
  '/include/c++/8/ext/concurrence.h'
  '/include/c++/8/bits/unique_ptr.h'
  '/include/c++/8/bits/shared_ptr.h'
  '/include/c++/8/bits/shared_ptr_base.h'
  '/include/c++/8/bits/allocated_ptr.h'
  '/include/c++/8/bits/refwrap.h'
  '/include/c++/8/bits/shared_ptr_atomic.h'
  '/include/c++/8/bits/atomic_base.h'
  '/include/c++/8/bits/atomic_lockfree_defines.h'
  '/include/c++/8/backward/auto_ptr.h'
  '/include/c++/8/set'
  '/include/c++/8/bits/stl_set.h'
  '/include/c++/8/bits/stl_multiset.h'
  '/include/c++/8/vector'
  '/include/c++/8/bits/stl_vector.h'
  '/include/c++/8/bits/stl_bvector.h'
  '/include/c++/8/bits/vector.tcc'
  '/include/c++/8/stdlib.h'
  '/include/c++/8/cstddef'
  '/lib/gcc/x86_64-redhat-linux/8/include/limits.h'
  '/lib/gcc/x86_64-redhat-linux/8/include/syslimits.h'
Target //tensorflow:libtensorflow_cc.so failed to build
INFO: Elapsed time: 33.237s, Critical Path: 3.55s
INFO: 103 processes: 92 internal, 11 local.
FAILED: Build did NOT complete successfully


# Linker Error

ERROR: /root/.cache/bazel/_bazel_root/42e04b8ffa2c97bc3b6715d4727a1211/external/com_google_protobuf/BUILD:416:10: Linking external/com_google_protobuf/protoc failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/42e04b8ffa2c97bc3b6715d4727a1211/execroot/org_tensorflow && \
  exec env - \
    CUDA_TOOLKIT_PATH=/opt/nvidia/cuda-11.4 \
    GCC_HOST_COMPILER_PATH=/bin/gcc \
    LD_LIBRARY_PATH=/opt/nvidia/cuda-11.4/lib64:/opt/nvidia/cuda-11.4/lib64/stubs:/opt/nvidia/cuda-11.4/lib/lib64:/opt/nvidia/cuda-11.4/targets/x86_64-linux/lib:/opt/nvidia/cuda-11.4/extras/CUPTI/lib64:/opt/openmpi/openmpi-4.0.5/lib:/opt/pmix/pmix-3.1.5/lib:/opt/python/python-3.7.9/lib:/usr/lib64:/opt/hdf5/hdf5-1.10.7/lib:/opt/libctl/libctl-4.5.0/lib:/opt/openblas/openblas-0.3.10/lib:/opt/fftw/fftw-3.3.8/lib:/opt/harminv/harminv-1.4.1/lib:/opt/nlopt/nlopt-2.6.2/lib64:/opt/gsl/gsl-2.6/lib:/opt/libgdsii/libgdsii-0.21/lib:/opt/mpb/mpb-1.10.0/lib:/opt/opencascade/opencascade-7.4.0/lib:/opt/ffmpeg/ffmpeg-4.3.1/lib:/opt/netcdf/netcdf-c-4.7.4-f-4.5.3/lib:/opt/scalapack/scalapack-2.1.0/lib:/opt/berkeleygw/berkeleygw-2.1/lib:/opt/pnfft/pnfft-1.0.7-alpha/lib:/opt/pfft/pfft-1.0.8-alpha/lib:/opt/libvdwxc/libvdwxc-0.4.0/lib:/opt/libxc/libxc-4.3.4/lib: \
    PATH=/opt/bazel/bazel-4.2.1/bin:/opt/bazel/bazel-4.2.2/bin:/opt/nvidia/cuda-11.4/bin:/opt/openmpi/openmpi-4.0.5/bin:/opt/pmix/pmix-3.1.5/bin:/opt/python/python-3.7.9/bin:/opt/hdf5/hdf5-1.10.7/bin:/opt/libctl/libctl-4.5.0/bin:/opt/h5utils/h5utils-1.13.1/bin:/opt/ffmpeg/ffmpeg-4.3.1/bin:/opt/netcdf/netcdf-c-4.7.4-f-4.5.3/bin:/opt/berkeleygw/berkeleygw-2.1/bin:/opt/harminv/harminv-1.4.1/bin:/opt/mpb/mpb-1.10.0/bin:/opt/gmsh/gmsh-4.8.4/bin:/usr/share/Modules/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/slurm/slurm-20.02.5/bin: \
    PWD=/proc/self/cwd \
    PYTHONPATH=/opt/python/python-3.7.9/lib: \
    PYTHON_BIN_PATH=/opt/python/python-3.7.9/bin/python3 \
    PYTHON_LIB_PATH=/opt/python/python-3.7.9/lib \
    TF2_BEHAVIOR=1 \
    TF_CUDA_COMPUTE_CAPABILITIES=7.0,7.5,8.6 \
    TF_CUDA_PATHS=/opt/nvidia/cuda-11.4 \
    TF_CUDA_VERSION=11 \
    TF_CUDNN_VERSION=8 \
    TF_NCCL_VERSION='' \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc @bazel-out/k8-opt/bin/external/com_google_protobuf/protoc-2.params)
Execution platform: @local_execution_config_platform//:platform
/bin/../lib/gcc/x86_64-redhat-linux/8/../../../../lib64/Scrt1.o: In function `_start':
(.text+0x24): undefined reference to `main'
collect2: error: ld returned 1 exit status
Target //tensorflow:libtensorflow_cc.so failed to build
INFO: Elapsed time: 4.644s, Critical Path: 0.55s
INFO: 5 processes: 5 internal.
FAILED: Build did NOT complete successfully
```
</details>

**Comment by gadagashwini** [comment]
@hoba87,
Could you try `bazel clean --expunge` followed by `bazel sync`. Thanks!

**Comment by hoba87** [comment]
for `bazel sync` I get a bunch of errors like e.g.:

```
INFO: Repository ubuntu18.04-gcc8_manylinux2014-cuda11.2-cudnn8.1-tensorrt7.2_config_python3.7 instantiated at:
  /home/common/software/tensorflow-2.8.0/WORKSPACE:15:14: in <toplevel>
  /home/common/software/tensorflow-2.8.0/tensorflow/workspace2.bzl:878:19: in workspace
  /home/common/software/tensorflow-2.8.0/tensorflow/workspace2.bzl:91:27: in _tf_toolchains
  /root/.cache/bazel/_bazel_root/42e04b8ffa2c97bc3b6715d4727a1211/external/tf_toolchains/toolchains/remote_config/configs.bzl:236:26: in initialize_rbe_configs
  /root/.cache/bazel/_bazel_root/42e04b8ffa2c97bc3b6715d4727a1211/external/tf_toolchains/toolchains/remote_config/rbe_config.bzl:121:32: in _tensorflow_rbe_config
Repository rule remote_python_configure defined at:
  /home/common/software/tensorflow-2.8.0/third_party/py/python_configure.bzl:285:42: in <toplevel>
ERROR: An error occurred during the fetch of repository 'ubuntu18.04-gcc8_manylinux2014-cuda11.2-cudnn8.1-tensorrt7.2_config_python3.7':
   Traceback (most recent call last):
	File "/home/common/software/tensorflow-2.8.0/third_party/py/python_configure.bzl", line 209, column 22, in _create_local_python_repository
		_check_python_bin(repository_ctx, python_bin)
	File "/home/common/software/tensorflow-2.8.0/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
		auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
	File "/home/common/software/tensorflow-2.8.0/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
		fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH='/usr/local/bin/python3.7' is not executable. Is it the python binary?
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/home/common/software/tensorflow-2.8.0/third_party/py/python_configure.bzl", line 209, column 22, in _create_local_python_repository
		_check_python_bin(repository_ctx, python_bin)
	File "/home/common/software/tensorflow-2.8.0/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
		auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
	File "/home/common/software/tensorflow-2.8.0/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
		fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH='/usr/local/bin/python3.7' is not executable. Is it the python binary?
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/oneapi-src/oneDNN/archive/v2.5.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
DEBUG: /root/.cache/bazel/_bazel_root/42e04b8ffa2c97bc3b6715d4727a1211/external/tf_runtime/third_party/cuda/dependencies.bzl:19:10: 
NOTICE: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
ERROR: Error fetching repository: java.io.IOException: cc_download_clang_toolchain rule //external:local_config_download_clang must create a directory
INFO: Repository build_bazel_rules_swift_local_config instantiated at:
  /home/common/software/tensorflow-2.8.0/WORKSPACE:23:14: in <toplevel>
  /home/common/software/tensorflow-2.8.0/tensorflow/workspace0.bzl:112:29: in workspace
  /root/.cache/bazel/_bazel_root/42e04b8ffa2c97bc3b6715d4727a1211/external/build_bazel_rules_swift/swift/repositories.bzl:111:11: in swift_rules_dependencies
  /root/.cache/bazel/_bazel_root/42e04b8ffa2c97bc3b6715d4727a1211/external/build_bazel_rules_swift/swift/repositories.bzl:32:18: in _maybe
Repository rule swift_autoconfiguration defined at:
  /root/.cache/bazel/_bazel_root/42e04b8ffa2c97bc3b6715d4727a1211/external/build_bazel_rules_swift/swift/internal/swift_autoconfiguration.bzl:301:42: in <toplevel>
ERROR: An error occurred during the fetch of repository 'build_bazel_rules_swift_local_config':
   Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/42e04b8ffa2c97bc3b6715d4727a1211/external/build_bazel_rules_swift/swift/internal/swift_autoconfiguration.bzl", line 299, column 32, in _swift_autoconfiguration_impl
		_create_linux_toolchain(repository_ctx)
	File "/root/.cache/bazel/_bazel_root/42e04b8ffa2c97bc3b6715d4727a1211/external/build_bazel_rules_swift/swift/internal/swift_autoconfiguration.bzl", line 211, column 13, in _create_linux_toolchain
		fail("ERROR: rules_swift uses Bazel's CROSSTOOL to link, but Swift " +
Error in fail: ERROR: rules_swift uses Bazel's CROSSTOOL to link, but Swift requires that the driver used is clang. Please set `CC=clang` in your environment before invoking Bazel.
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/42e04b8ffa2c97bc3b6715d4727a1211/external/build_bazel_rules_swift/swift/internal/swift_autoconfiguration.bzl", line 299, column 32, in _swift_autoconfiguration_impl
		_create_linux_toolchain(repository_ctx)
	File "/root/.cache/bazel/_bazel_root/42e04b8ffa2c97bc3b6715d4727a1211/external/build_bazel_rules_swift/swift/internal/swift_autoconfiguration.bzl", line 211, column 13, in _create_linux_toolchain
		fail("ERROR: rules_swift uses Bazel's CROSSTOOL to link, but Swift " +
Error in fail: ERROR: rules_swift uses Bazel's CROSSTOOL to link, but Swift requires that the driver used is clang. Please set `CC=clang` in your environment before invoking Bazel.
```

**Comment by gadagashwini** [comment]
@hoba87,

> ERROR: An error occurred during the fetch of repository 'ubuntu18.04-gcc8_manylinux2014-cuda11.2-cudnn8.1-tensorrt7.2_config_python3.7':

Tensorflow master branch has the configuration 
```
tensorflow_rbe_config(
        name = "ubuntu18.04-gcc8_manylinux2014-cuda11.2-cudnn8.1-tensorrt7.2",
        .....)
```
Could you try to build Tensorflow master branch and let us know. Thanks!

**Comment by hoba87** [comment]
```
ERROR: /home/common/software/tensorflow-master/tensorflow/BUILD:1114:21: in cc_shared_library rule //tensorflow:libtensorflow_cc.so.2.10.0: 
Traceback (most recent call last):
	File "/virtual_builtins_bzl/common/cc/experimental_cc_shared_library.bzl", line 416, column 105, in _cc_shared_library_impl
	File "/virtual_builtins_bzl/common/cc/experimental_cc_shared_library.bzl", line 340, column 37, in _filter_inputs
	File "/virtual_builtins_bzl/common/cc/experimental_cc_shared_library.bzl", line 360, column 9, in _throw_error_if_unaccounted_libs
Error in fail: The following libraries cannot be linked either statically or dynamically:
@nccl_archive//:nccl
@nccl_archive//:device
@nccl_archive//:include_hdrs
@nccl_archive//:src_hdrs
To ignore which libraries get linked statically for now, add the following to 'static_deps':
        "@nccl_archive//:__subpackages__",
ERROR: /home/common/software/tensorflow-master/tensorflow/BUILD:1114:21: Analysis of target '//tensorflow:libtensorflow_cc.so.2.10.0' failed
ERROR: Analysis of target '//tensorflow:libtensorflow_cc.so' failed; build aborted: 
```

**Comment by gadagashwini** [comment]
@hoba87 ,
Could you share the complete Log. Thanks!

**Comment by hoba87** [comment]
[bazel.log](https://github.com/tensorflow/tensorflow/files/8675934/bazel.log)

**Comment by gadagashwini** [comment]
Hi @hoba87, Have you tried `--config=nccl ` command during Tensorflow build run. Thank you!

**Comment by hoba87** [comment]
> Hi @hoba87, Have you tried `--config=nccl ` command during Tensorflow build run. Thank you!
That gives only: ERROR: Config value 'nccl' is not defined in any .rc file

At the end my workaround was to use a ubuntu docker image with fitting libc version and using that then.
