### ISSUE TITLE
Error when making directory to a google cloud storage bucket path

### ISSUE THREAD

**Issue by Monalisa98927** [tensorflow/tensorflow#55816]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.8.0

### Custom Code

Yes

### OS Platform and Distribution

CentOS Linux release 7.4.1708

### Python version

3.7

### CUDA/cuDNN version

cuda/11.2.2  cudnn/8.1a11

### Current Behaviour?

```shell
First I run `sbatch test_error.sh` on a NYU high-performance cluster. The following is the code of `test_error.sh`

And the error message in `myjob.e` is as follows...(I think the UserWarning about cloud_tpu_init has nothing to do with this issue so maybe we can ignore it here...)

A weird thing I discover is that if I don't submit `test_error.sh` to any host (such as aquila or gpu listed in `test_error.sh`) and just run 

`python -c "import tensorflow as tf; tf.io.gfile.makedirs('gs://jukemir-t5/pretrain-model/pre/')"` 

in the default host (login2), this error disappears. (However, the login2 host doesn't have enough computing resource so I have to use other host such as aquila... )


As for the gcs bucket, I have already prove that it does exist. And I gave `allUsers` the following permission:

Storage Legacy Bucket Reader
Storage Legacy Bucket Writer
Storage Legacy Object Owner
Storage Object Viewer


I put the following environment variables in `~/.bashrc` file.

export GOOGLE_APPLICATION_CREDENTIALS='/gpfsnyu/scratch/kf2395/impressive-hull-347212-9ed6d5acf8ff.json'
export TENSORSTORE_CA_BUNDLE="/etc/ssl/certs/ca-bundle.crt"
```

### Standalone code to reproduce the issue

```shell
#!/bin/bash

#SBATCH -p aquila,gpu # Partition to submit to

#SBATCH -n 1 # Number of cores

#SBATCH -N 1 # Number of nodes

#SBATCH --mem=100G # Memory pool for all cores, MB

#SBATCH -t 0-8:00

#SBATCH -o myjob.o # File to which STDOUT will be written

#SBATCH -e myjob.e # File to which STDERR will be written

#SBATCH --mail-type=ALL # Type of email notification- BEGIN,END,FAIL,ALL

#SBATCH --mail-user=kf2395@nyu.edu # Email which notifications will be sent  

#SBATCH --gres=gpu:4 # How much gpu need, n is the number

#SBATCH --export=ALL

module load cuda/11.2.2
python -c "import tensorflow as tf; tf.io.gfile.makedirs('gs://jukemir-t5/pretrain-model/pre/')"
```

### Relevant log output

```shell
2022-04-29 17:33:22.818645: W tensorflow/core/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "FAILED_PRECONDITION: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Could not resolve host: www.googleapis.com". Retrieving token from GCE failed with "FAILED_PRECONDITION: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Could not resolve host: metadata".
/gpfsnyu/scratch/kf2395/.cache/env/tf2-gpu-py3.7/lib/python3.7/site-packages/jax/__init__.py:27: UserWarning: cloud_tpu_init failed: ConnectionError(MaxRetryError("HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/attributes/agent-worker-number (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f30dab30190>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))"))
 This a JAX bug; please report an issue at https://github.com/google/jax/issues
  _warn(f"cloud_tpu_init failed: {repr(exc)}\n This a JAX bug; please report "
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/gpfsnyu/scratch/kf2395/.cache/env/tf2-gpu-py3.7/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 511, in recursive_create_dir_v2
    _pywrap_file_io.RecursivelyCreateDir(compat.path_to_bytes(path))
tensorflow.python.framework.errors_impl.FailedPreconditionError: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Could not resolve host: www.googleapis.com
	 when reading metadata of gs://jukemir-t5/pretrain-model/pre/
```
</details>

**Comment by gadagashwini** [comment]
@Monalisa98927,
Looks like issue is with redirecting http to https was not clearly defined, so the url could change when the request for https for a specific service was made, this caused an error. Could you check the Cloud instance rule for HTTP and HTTPS. Thank you!

**Comment by tilakrayal** [comment]
@Monalisa98927,
It seems that you're working with GCS. Was that your intention?

Perhaps `TFDS_DATA_DIR` variable is not set and dataset builder falls back to:

https://github.com/tensorflow/datasets/blob/8ec8cc47bc5bc406198a96e1353f0d581fed7a2d/tensorflow_datasets/core/dataset_builder.py#L287

Also can you confirm that this message is related to your dataset preparation not working? Seems like it could be just a warning that shouldn't prevent the script from executing (see https://github.com/tensorflow/datasets/issues/2761)

You can try using:

```python
tfds.core.utils.gcs_utils._is_gcs_disabled = True
os.environ['NO_GCE_CHECK'] = 'true'
```

https://github.com/tensorflow/datasets/issues/2761

Thank you!
