### ISSUE TITLE
tensorflow.python.framework.errors_impl.AlreadyExistsError: File system for s3 already registered error in load_library.py

### ISSUE THREAD

**Issue by edehino** [tensorflow/tensorflow#55932]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

'2.4.1'

### Custom Code

No

### OS Platform and Distribution

Linux Kubuntu 18.04

### Python version

Python 3.9.12

### CUDA/cuDNN version

cudatoolkit: 10.1.243 ; cudnn:7.6.5

### Current Behaviour?

```shell
I am trying to locally train a model from tensorflow using the following command:


!python3 {ws_path}models/research/object_detection/model_main_tf2.py \
    --pipeline_config_path={pipeline_config_path} \
    --model_dir={model_dir} \
    --alsologtostderr \
    --num_train_steps={num_steps} \
    --sample_1_of_n_eval_examples=1 \
    --num_eval_steps={num_eval_steps}


But an error occurred and I tried really hard to search around but I can't find anything that could be a help. The error is as follow:

tensorflow.python.framework.errors_impl.AlreadyExistsError: File system for s3 already registered
```

### Standalone code to reproduce the issue

```shell
Maybe you can look at this recently posted question in stackoverflow:
https://stackoverflow.com/questions/72080563/alreadyexistserror-file-system-for-s3-already-registered

We got the same error on anaconda3\some-path\tensorflow\python\framework\load_library.py
```

### Relevant log output

```shell
2022-05-05 15:40:47.232501: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "/home/pinky/architectures/TRAINING/faster-rcnn-tf2/models/research/object_detection/model_main_tf2.py", line 31, in <module>
    from object_detection import model_lib_v2
  File "/home/pinky/anaconda3/envs/faster-rcnn-tf2/lib/python3.9/site-packages/object_detection/model_lib_v2.py", line 30, in <module>
    from object_detection import inputs
  File "/home/pinky/anaconda3/envs/faster-rcnn-tf2/lib/python3.9/site-packages/object_detection/inputs.py", line 27, in <module>
    from object_detection.builders import model_builder
  File "/home/pinky/anaconda3/envs/faster-rcnn-tf2/lib/python3.9/site-packages/object_detection/builders/model_builder.py", line 37, in <module>
    from object_detection.meta_architectures import deepmac_meta_arch
  File "/home/pinky/anaconda3/envs/faster-rcnn-tf2/lib/python3.9/site-packages/object_detection/meta_architectures/deepmac_meta_arch.py", line 28, in <module>
    import tensorflow_io as tfio  # pylint:disable=g-import-not-at-top
  File "/home/pinky/anaconda3/envs/faster-rcnn-tf2/lib/python3.9/site-packages/tensorflow_io-0.25.0-py3.9-linux-x86_64.egg/tensorflow_io/__init__.py", line 17, in <module>
    from tensorflow_io.python.api import *  # pylint: disable=wildcard-import
  File "/home/pinky/anaconda3/envs/faster-rcnn-tf2/lib/python3.9/site-packages/tensorflow_io-0.25.0-py3.9-linux-x86_64.egg/tensorflow_io/python/api/__init__.py", line 19, in <module>
    from tensorflow_io.python.ops.io_dataset import IODataset
  File "/home/pinky/anaconda3/envs/faster-rcnn-tf2/lib/python3.9/site-packages/tensorflow_io-0.25.0-py3.9-linux-x86_64.egg/tensorflow_io/python/ops/__init__.py", line 96, in <module>
    plugin_ops = _load_library("libtensorflow_io_plugins.so", "fs")
  File "/home/pinky/anaconda3/envs/faster-rcnn-tf2/lib/python3.9/site-packages/tensorflow_io-0.25.0-py3.9-linux-x86_64.egg/tensorflow_io/python/ops/__init__.py", line 64, in _load_library
    l = load_fn(f)
  File "/home/pinky/anaconda3/envs/faster-rcnn-tf2/lib/python3.9/site-packages/tensorflow_io-0.25.0-py3.9-linux-x86_64.egg/tensorflow_io/python/ops/__init__.py", line 56, in <lambda>
    load_fn = lambda f: tf.experimental.register_filesystem_plugin(f) is None
  File "/home/pinky/anaconda3/envs/faster-rcnn-tf2/lib/python3.9/site-packages/tensorflow/python/framework/load_library.py", line 178, in register_filesystem_plugin
    py_tf.TF_RegisterFilesystemPlugin(plugin_location)
tensorflow.python.framework.errors_impl.AlreadyExistsError: File system for s3 already registered
```
</details>

**Comment by sushreebarsa** [comment]
@edehino I tried to replicate the issue on colab using TF v2.8.0 ,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/af84e3090b24d7631057db5f14d603c8/untitled639.ipynb) and confirm the same?
Thanks!
