### ISSUE TITLE
[XLA]  Regression in NLP Models w/ error Tile Op must be a compile time constant

### ISSUE THREAD

**Issue by codeislife99** [tensorflow/tensorflow#55973]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

TF 2.8

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 18.04

### Python version

3.9

### Bazel version

4.2.1

### GCC/Compiler version

9.4.0

### CUDA/cuDNN version

11.2

### GPU model and memory

Tesla V100 , 16384MiB

### Current Behaviour?

```shell
Currently it fails in masked_sparse_categorical_crossentropy loss function and complains about a Tile Op. However this op hasn't changed since TF2.7 XLA which means that the source of the error is probably somewhere since this error doesn't show up in TF2.7 XLA
```

### Standalone code to reproduce the issue

```shell
1. git clone https://github.com/huggingface/transformers.git 
2. pip3 install transformers==4.18.0, datasets==1.18.4, nltk, rouge_score, sacrebleu
3. cd transformers
4. python3 examples/tensorflow/summarization/run_summarization.py --model_name_or_path facebook/bart-base --dataset_name xsum --fp16 --do_train --output_dir ~/bart-test --per_device_train_batch_size 1 --overwrite_output_dir true --save_strategy no --num_train_epochs 1
```

### Relevant log output

```shell
2022-05-02 20:04:14.663607: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at tile_ops.cc:70 : INVALID_ARGUMENT: Input 1 to node `masked_sparse_categorical_crossentropy/RaggedReduceMean/RaggedReduceSum/RaggedSplitsToSegmentIds/Repeat/Tile` with op Tile must be a compile-time constant.

XLA compilation requires that operator arguments that represent shapes or dimensions be evaluated to concrete values at compile time. This error means that a shape or dimension argument could not be evaluated at compile time, usually because the value of the argument depends on a parameter to the computation, on a variable, or on a stateful operation such as a random number generator.

Traceback (most recent call last):
  File "run_summarization.py", line 674, in <module>
    main()
  File "run_summarization.py", line 632, in main
    steps_per_epoch=num_update_steps_per_epoch,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 55, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Detected at node 'masked_sparse_categorical_crossentropy/RaggedReduceMean/RaggedReduceSum/RaggedSplitsToSegmentIds/Repeat/Tile' defined at (most recent call last):
    File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 890, in _bootstrap
      self._bootstrap_inner()
    File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
      self.run()
    File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/keras/engine/training.py", line 1030, in run_step
      outputs = model.train_step(data)
    File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/transformers/modeling_tf_utils.py", line 1000, in train_step
      loss = self.compiled_loss(y, y_pred, sample_weight, regularization_losses=self.losses)
    File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/keras/engine/compile_utils.py", line 201, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/keras/losses.py", line 139, in __call__
      losses = call_fn(y_true, y_pred)
    File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/keras/losses.py", line 243, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "run_summarization.py", line 609, in masked_sparse_categorical_crossentropy
      losses = tf.reduce_mean(losses, axis=-1)
Node: 'masked_sparse_categorical_crossentropy/RaggedReduceMean/RaggedReduceSum/RaggedSplitsToSegmentIds/Repeat/Tile'
Detected at node 'masked_sparse_categorical_crossentropy/RaggedReduceMean/RaggedReduceSum/RaggedSplitsToSegmentIds/Repeat/Tile' defined at (most recent call last):
    File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 890, in _bootstrap
      self._bootstrap_inner()
    File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
      self.run()
    File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/keras/engine/training.py", line 1030, in run_step
      outputs = model.train_step(data)
    File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/transformers/modeling_tf_utils.py", line 1000, in train_step
      loss = self.compiled_loss(y, y_pred, sample_weight, regularization_losses=self.losses)
    File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/keras/engine/compile_utils.py", line 201, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/keras/losses.py", line 139, in __call__
      losses = call_fn(y_true, y_pred)
    File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/keras/losses.py", line 243, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "run_summarization.py", line 609, in masked_sparse_categorical_crossentropy
      losses = tf.reduce_mean(losses, axis=-1)
Node: 'masked_sparse_categorical_crossentropy/RaggedReduceMean/RaggedReduceSum/RaggedSplitsToSegmentIds/Repeat/Tile'
Detected at node 'masked_sparse_categorical_crossentropy/RaggedReduceMean/RaggedReduceSum/RaggedSplitsToSegmentIds/Repeat/Tile' defined at (most recent call last):
    File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 890, in _bootstrap
      self._bootstrap_inner()
    File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
      self.run()
    File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/keras/engine/training.py", line 1030, in run_step
      outputs = model.train_step(data)
    File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/transformers/modeling_tf_utils.py", line 1000, in train_step
      loss = self.compiled_loss(y, y_pred, sample_weight, regularization_losses=self.losses)
    File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/keras/engine/compile_utils.py", line 201, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/keras/losses.py", line 139, in __call__
      losses = call_fn(y_true, y_pred)
    File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/keras/losses.py", line 243, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "run_summarization.py", line 609, in masked_sparse_categorical_crossentropy
      losses = tf.reduce_mean(losses, axis=-1)
Node: 'masked_sparse_categorical_crossentropy/RaggedReduceMean/RaggedReduceSum/RaggedSplitsToSegmentIds/Repeat/Tile'
Detected at node 'masked_sparse_categorical_crossentropy/RaggedReduceMean/RaggedReduceSum/RaggedSplitsToSegmentIds/Repeat/Tile' defined at (most recent call last):
    File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 890, in _bootstrap
      self._bootstrap_inner()
    File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
      self.run()
    File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/keras/engine/training.py", line 1030, in run_step
      outputs = model.train_step(data)
    File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/transformers/modeling_tf_utils.py", line 1000, in train_step
      loss = self.compiled_loss(y, y_pred, sample_weight, regularization_losses=self.losses)
    File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/keras/engine/compile_utils.py", line 201, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/keras/losses.py", line 139, in __call__
      losses = call_fn(y_true, y_pred)
    File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/keras/losses.py", line 243, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "run_summarization.py", line 609, in masked_sparse_categorical_crossentropy
      losses = tf.reduce_mean(losses, axis=-1)
Node: 'masked_sparse_categorical_crossentropy/RaggedReduceMean/RaggedReduceSum/RaggedSplitsToSegmentIds/Repeat/Tile'
Detected at node 'masked_sparse_categorical_crossentropy/RaggedReduceMean/RaggedReduceSum/RaggedSplitsToSegmentIds/Repeat/Tile' defined at (most recent call last):
    File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 890, in _bootstrap
      self._bootstrap_inner()
    File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
      self.run()
    File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/keras/engine/training.py", line 1030, in run_step
      outputs = model.train_step(data)
    File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/transformers/modeling_tf_utils.py", line 1000, in train_step
      loss = self.compiled_loss(y, y_pred, sample_weight, regularization_losses=self.losses)
    File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/keras/engine/compile_utils.py", line 201, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/keras/losses.py", line 139, in __call__
      losses = call_fn(y_true, y_pred)
    File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/keras/losses.py", line 243, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "run_summarization.py", line 609, in masked_sparse_categorical_crossentropy
      losses = tf.reduce_mean(losses, axis=-1)
Node: 'masked_sparse_categorical_crossentropy/RaggedReduceMean/RaggedReduceSum/RaggedSplitsToSegmentIds/Repeat/Tile'
5 root error(s) found.
  (0) INVALID_ARGUMENT:  Input 1 to node `masked_sparse_categorical_crossentropy/RaggedReduceMean/RaggedReduceSum/RaggedSplitsToSegmentIds/Repeat/Tile` with op Tile must be a compile-time constant.

XLA compilation requires that operator arguments that represent shapes or dimensions be evaluated to concrete values at compile time. This error means that a shape or dimension argument could not be evaluated at compile time, usually because the value of the argument depends on a parameter to the computation, on a variable, or on a stateful operation such as a random number generator.

         [[{{node masked_sparse_categorical_crossentropy/RaggedReduceMean/RaggedReduceSum/RaggedSplitsToSegmentIds/Repeat/Tile}}]]
         [[cluster_14_1/xla_compile]]
         [[div_no_nan/ReadVariableOp_1/_1416]]
  (1) INVALID_ARGUMENT:  Input 1 to node `masked_sparse_categorical_crossentropy/RaggedReduceMean/RaggedReduceSum/RaggedSplitsToSegmentIds/Repeat/Tile` with op Tile must be a compile-time constant.

XLA compilation requires that operator arguments that represent shapes or dimensions be evaluated to concrete values at compile time. This error means that a shape or dimension argument could not be evaluated at compile time, usually because the value of the argument depends on a parameter to the computation, on a variable, or on a stateful operation such as a random number generator.

         [[{{node masked_sparse_categorical_crossentropy/RaggedReduceMean/RaggedReduceSum/RaggedSplitsToSegmentIds/Repeat/Tile}}]]
         [[cluster_14_1/xla_compile]]
         [[cond_2/Identity_3/_121/_3964]]
  (2) INVALID_ARGUMENT:  Input 1 to node `masked_sparse_categorical_crossentropy/RaggedReduceMean/RaggedReduceSum/RaggedSplitsToSegmentIds/Repeat/Tile` with op Tile must be a compile-time constant.

XLA compilation requires that operator arguments that represent shapes or dimensions be evaluated to concrete values at compile time. This error means that a shape or dimension argument could not be evaluated at compile time, usually because the value of the argument depends on a parameter to the computation, on a variable, or on a stateful operation such as a random number generator.

         [[{{node masked_sparse_categorical_crossentropy/RaggedReduceMean/RaggedReduceSum/RaggedSplitsToSegmentIds/Repeat/Tile}}]]
         [[cluster_14_1/xla_compile]]
         [[cluster_282_1/data_as_ctrl/_1595]]
  (3) INVALID_ARGUMENT:  Input 1 to node `masked_sparse_categorical_crossentropy/RaggedReduceMean/RaggedReduceSum/RaggedSplitsToSegmentIds/Repeat/Tile` with op Tile must be a compile-time constant.

XLA compilation requires that operator arguments that represent shapes or dimensions be evaluated to concrete values at compile time. This error means that a shape or dimension argument could not be evaluated at compile time, usually because the value of the argument depends on a parameter to the computation, on a variable, or on a stateful operation such as a random number generator.

         [[{{node masked_sparse_categorical_crossentropy/RaggedReduceMean/RaggedReduceSum/RaggedSplitsToSegmentIds/Repeat/Tile}}]]
         [[cluster_14_1/xla_compile]]
         [[cluster_264_1/merge_oidx_5/_9670]]
  (4) INVALID_ARGUMENT:  Input 1 to node `masked_sparse_categorical_crossentropy/RaggedReduceMean/RaggedReduceSum/RaggedSplitsToSegmentIds/Repeat/Tile` with op Tile must be a compile-time constant.

XLA compilation requires that operator arguments that represent shapes or dimensions be evaluated to concrete values at compile time. This error means that a shape or dimension argument could not be evaluated at compile time, usually because the value of the argument depends on a parameter to the computation, on a variable, or on a stateful operation such as a random number generator.

         [[{{node masked_sparse_categorical_crossentropy/RaggedReduceMean/RaggedReduceSum/RaggedSplitsToSegmentIds/Repeat/Tile}}]]
         [[cluster_14_1/xla_compile]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_161679]
2022-05-28 02:07:07.336896: W tensorflow/core/kernels/data/generator_dataset_op.cc:108] Error occurred when finalizing GeneratorDataset iterator: FAILED_PRECONDITION: Python interpreter state is not initialized. The process may be terminated.
         [[{{node PyFunc}}]]
```
</details>

**Comment by sushreebarsa** [comment]
@codeislife99 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by codeislife99** [comment]
[run_summarization.py code to be run with XLA Flags](https://github.com/huggingface/transformers/blob/main/examples/tensorflow/summarization/run_summarization.py)
`export XLA_FLAGS="--xla_gpu_autotune_level=2 --xla_gpu_enable_async_all_reduce" 
export TF_XLA_FLAGS="--tf_xla_auto_jit=2  --tf_xla_async_compilation"`

**Comment by codeislife99** [comment]
@sushreebarsa - If you check out the Steps to Reproduce section I have mentioned how to reproduce the issue, which I have further elaborated on in the above comment. Is there anything specific you want ?

**Comment by codeislife99** [comment]
Has there been any progress on this issue ? Were you able to replicate the issue ?

**Comment by sushreebarsa** [comment]
@codeislife99 Sorry for the late response!
 I tried to replicate the issue reported here, please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/b34e0c75c1247873c9404ec5eeb28228/untitled132.ipynb) and confirm the same ?
Thank you!

**Comment by codeislife99** [comment]
Hi, 
    No this is not the issue. Can you run it on a GPU? Right now the script is not able to run because you are running it on a CPU. You can find the CUDA versions in the issue description but that shouldn't matter for the error.

**Comment by codeislife99** [comment]
Hi @gadagashwini were you able to replicate the issue? This is a regression from TF2.6 and it seems to be really problematic as an user.

**Comment by codeislife99** [comment]
Hi, following up on this issue.

**Comment by codeislife99** [comment]
Hi, another ping on this issue. please let me know if there is somewhere else where I need to post this issue to get a response?

**Comment by codeislife99** [comment]
Hello, @sachinprasadhs any progress on this issue ?

**Comment by codeislife99** [comment]
Hello, is there anyone willing to take a look at this issue ?

**Comment by mohantym** [comment]
Hi @codeislife99 !
I am getting different error  (dataset error )in [2.9 ](https://colab.sandbox.google.com/gist/mohantym/a4e1d40c3880a54392bd58cb811a9f05/git_55973.ipynb#scrollTo=H6eCB3ORvIYT). Could you provide a colab gist from your end.
Thank you!

**Comment by sachinprasadhs** [comment]
Hi, The error which you have reported seems to have resolved, now it it throwing the error `TypeError: Dataset argument should be a datasets.Dataset!` which seems like an issue with your data pipeline.
Attached the [gist](https://colab.sandbox.google.com/gist/sachinprasadhs/768b9e881ffdfb3ed6fdfdcdc3562534/git_55973.ipynb#scrollTo=S3LyzM1pu5_V) here for reference. Thanks!
