### ISSUE TITLE
Autograph appears not to support Python variables without an initial value

### ISSUE THREAD

**Issue by jesnie** [tensorflow/tensorflow#56024]
### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.8.0

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 18.04.6 LTS

### Python version

3.10.4

### Current Behaviour?

```shell
Autograph appears not to support Python variables without an initial value.
Although this is a rarely used feature of Python, I don't see why this should cause any problems. It literally has no control flow.

In my below example `foo` works, but `bar` does not, despite them essentially only having formatting differences.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf


@tf.function
def foo(a: tf.Tensor, b: tf.Tensor) -> tf.Tensor:
    result: tf.Tensor = a + b
    return result


@tf.function
def bar(a: tf.Tensor, b: tf.Tensor) -> tf.Tensor:
    result: tf.Tensor
    result = a + b
    return result


foo(tf.constant(2), tf.constant(3))
bar(tf.constant(2), tf.constant(3))
```

### Relevant log output

```shell
2022-05-09 10:25:03.704416: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-05-09 10:25:03.707662: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory
2022-05-09 10:25:03.708246: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1850] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2022-05-09 10:25:03.708548: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:tensorflow:AutoGraph could not transform <function bar at 0x7feba9ff7130> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: invalid value for "node": expected "ast.AST", got "<class 'NoneType'>"; to visit lists of nodes, use "visit_block" instead
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
```

**Comment by bhack** [comment]
```python

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/impl/api.py", line 427, in converted_call
    converted_f = _convert_actual(target_entity, program_ctx)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/impl/api.py", line 269, in _convert_actual
    transformed, module, source_map = _TRANSPILER.transform(entity, program_ctx)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/pyct/transpiler.py", line 282, in transform
    return self.transform_function(obj, user_context)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/pyct/transpiler.py", line 466, in transform_function
    nodes, ctx = super(PyToPy, self).transform_function(fn, user_context)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/pyct/transpiler.py", line 359, in transform_function
    result = self.transform_ast(node, context)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/impl/api.py", line 237, in transform_ast
    node = self.initial_analysis(node, ctx)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/impl/api.py", line 225, in initial_analysis
    node = activity.resolve(node, ctx, None)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/pyct/static_analysis/activity.py", line 700, in resolve
    return ActivityAnalyzer(context, parent_scope).visit(node)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/pyct/transformer.py", line 441, in visit
    result = super(Base, self).visit(node)
  File "/usr/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/pyct/static_analysis/activity.py", line 592, in visit_FunctionDef
    node.body = self.visit_block(node.body)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/pyct/transformer.py", line 336, in visit_block
    replacement = self.visit(node)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/pyct/transformer.py", line 441, in visit
    result = super(Base, self).visit(node)
  File "/usr/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/pyct/static_analysis/activity.py", line 385, in visit_AnnAssign
    node.value = self.visit(node.value)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/pyct/transformer.py", line 427, in visit
    raise ValueError(msg)
ValueError: invalid value for "node": expected "ast.AST", got "<class 'NoneType'>"; to visit lists of nodes, use "visit_block" instead
```

**Comment by bhack** [comment]
@jesnie  It is solved in the next release (try TF 2.9rc2).

Please note also that usually the fix in the older versions (<=1 year) will be done if that is a security bug or if the bug is critical and impacting larger community. In this case it is working fine or not reproducible with Tensorflow 2.9.x you need to use the last RC or wait for the 2.9 stable release.

**Comment by jesnie** [comment]
Hmmm, it does appear that this has already been fixed for `2.9.0`. Thanks!
