### ISSUE TITLE
AssertionError: Bazel does not support execution of Python interpreters via labels yet

### ISSUE THREAD

**Issue by liuyang77886** [tensorflow/tensorflow#56041]
### Issue Type

Build/Install

### Source

source

### Tensorflow Version

tf1.5

### Custom Code

No

### OS Platform and Distribution

ubuntu20

### Mobile device

ubuntu20

### Python version

3.7

### Bazel version

bazel-0.26.1

### Current Behaviour?

```shell
./bazel-0.26.1-linux-x86_64 build --config=v1 --copt=-msse2  -k //tensorflow/tools/pip_package:build_pip_package
```

### Standalone code to reproduce the issue

```shell
.tf_configure.bazelrc
build --action_env PYTHON_BIN_PATH="/home/soft/anaconda3/bin/python"
build --action_env PYTHON_LIB_PATH="/home/soft/anaconda3/envs/tf/lib/python3.7/site-packages"
build --python_path="//home/soft/anaconda3/bin/python"
build:xla --define with_xla_support=true
build:opt --copt=-msse2
build:opt --host_copt=-march=native
build:opt --define with_default_optimizations=true
build:v2 --define=tf_api_version=2
test --flaky_test_attempts=3
test --test_size_filters=small,medium
test --test_tag_filters=-benchmark-test,-no_oss,-oss_serial
test --build_tag_filters=-benchmark-test,-no_oss
test --test_tag_filters=-gpu
test --build_tag_filters=-gpu
build --action_env TF_CONFIGURE_IOS="0"




ERROR: /home/soft/tensorflow-r1.15/tensorflow/core/BUILD:2760:1: Couldn't build file tensorflow/core/util/version_info.cc: Executing genrule //tensorflow/core:version_info_gen failed (Exit 1)
Traceback (most recent call last):
  File "bazel-out/host/bin/tensorflow/tools/git/gen_git_source", line 252, in <module>
    Main()
  File "bazel-out/host/bin/tensorflow/tools/git/gen_git_source", line 218, in Main
    program = python_program = FindPythonBinary(module_space)
  File "bazel-out/host/bin/tensorflow/tools/git/gen_git_source", line 60, in FindPythonBinary
    'Bazel does not support execution of Python interpreters via labels yet')
AssertionError: Bazel does not support execution of Python interpreters via labels yet
ERROR: /data/.cache/bazel/_bazel_test/9d8f535cf1766321e020e62e8d398482/external/llvm/BUILD.bazel:59:1: Couldn't build file external/llvm/include/llvm/Config/abi-breaking.h: Executing genrule @llvm//:abi_breaking_gen failed (Exit 1)
Traceback (most recent call last):
  File "bazel-out/host/bin/external/org_tensorflow/third_party/llvm/expand_cmake_vars", line 252, in <module>
    Main()
  File "bazel-out/host/bin/external/org_tensorflow/third_party/llvm/expand_cmake_vars", line 218, in Main
    program = python_program = FindPythonBinary(module_space)
  File "bazel-out/host/bin/external/org_tensorflow/third_party/llvm/expand_cmake_vars", line 60, in FindPythonBinary
    'Bazel does not support execution of Python interpreters via labels yet')
AssertionError: Bazel does not support execution of Python interpreters via labels yet
ERROR: /data/.cache/bazel/_bazel_test/9d8f535cf1766321e020e62e8d398482/external/llvm/BUILD.bazel:45:1: Couldn't build file external/llvm/include/llvm/Config/config.h: Executing genrule @llvm//:config_gen failed (Exit 1)
Traceback (most recent call last):
  File "bazel-out/host/bin/external/org_tensorflow/third_party/llvm/expand_cmake_vars", line 252, in <module>
    Main()
  File "bazel-out/host/bin/external/org_tensorflow/third_party/llvm/expand_cmake_vars", line 218, in Main
    program = python_program = FindPythonBinary(module_space)
  File "bazel-out/host/bin/external/org_tensorflow/third_party/llvm/expand_cmake_vars", line 60, in FindPythonBinary
    'Bazel does not support execution of Python interpreters via labels yet')
AssertionError: Bazel does not support execution of Python interpreters via labels yet
ERROR: /data/.cache/bazel/_bazel_test/9d8f535cf1766321e020e62e8d398482/external/llvm/BUILD.bazel:52:1: Couldn't build file external/llvm/include/llvm/Config/llvm-config.h: Executing genrule @llvm//:llvm_config_gen failed (Exit 1)
Traceback (most recent call last):
  File "bazel-out/host/bin/external/org_tensorflow/third_party/llvm/expand_cmake_vars", line 252, in <module>
    Main()
  File "bazel-out/host/bin/external/org_tensorflow/third_party/llvm/expand_cmake_vars", line 218, in Main
    program = python_program = FindPythonBinary(module_space)
  File "bazel-out/host/bin/external/org_tensorflow/third_party/llvm/expand_cmake_vars", line 60, in FindPythonBinary
    'Bazel does not support execution of Python interpreters via labels yet')
AssertionError: Bazel does not support execution of Python interpreters via labels yet
ERROR: /home/soft/tensorflow-r1.15/tensorflow/python/BUILD:6940:1: Couldn't build file tensorflow/python/framework/fast_tensor_util.cpp: Executing genrule //tensorflow/python:framework/fast_tensor_util.pyx_cython_translation failed (Exit 1)
Traceback (most recent call last):
  File "bazel-out/host/bin/external/cython/cython_binary", line 252, in <module>
    Main()
  File "bazel-out/host/bin/external/cython/cython_binary", line 218, in Main
    program = python_program = FindPythonBinary(module_space)
  File "bazel-out/host/bin/external/cython/cython_binary", line 60, in FindPythonBinary
    'Bazel does not support execution of Python interpreters via labels yet')
AssertionError: Bazel does not support execution of Python interpreters via labels yet
ERROR: /home/soft/tensorflow-r1.15/tensorflow/python/BUILD:198:1: Couldn't build file tensorflow/python/platform/build_info.py: Executing genrule //tensorflow/python:py_build_info_gen failed (Exit 1)
Traceback (most recent call last):
  File "bazel-out/host/bin/tensorflow/tools/build_info/gen_build_info", line 252, in <module>
    Main()
  File "bazel-out/host/bin/tensorflow/tools/build_info/gen_build_info", line 218, in Main
    program = python_program = FindPythonBinary(module_space)
  File "bazel-out/host/bin/tensorflow/tools/build_info/gen_build_info", line 60, in FindPythonBinary
    'Bazel does not support execution of Python interpreters via labels yet')
AssertionError: Bazel does not support execution of Python interpreters via labels yet
ERROR: /data/.cache/bazel/_bazel_test/9d8f535cf1766321e020e62e8d398482/external/grpc/BUILD:507:1: Couldn't build file external/grpc/_objs/gpr_base/log_linux.pic.o: C++ compilation of rule '@grpc//:gpr_base' failed (Exit 1)
external/grpc/src/core/lib/gpr/log_linux.cc:43:13: error: ambiguating new declaration of 'long int gettid()'
   43 | static long gettid(void) { return syscall(__NR_gettid); }
      |             ^~~~~~
In file included from /usr/include/unistd.h:1170,
                 from external/grpc/src/core/lib/gpr/log_linux.cc:41:
/usr/include/x86_64-linux-gnu/bits/unistd_ext.h:34:16: note: old declaration '__pid_t gettid()'
   34 | extern __pid_t gettid (void) __THROW;
      |                ^~~~~~
external/grpc/src/core/lib/gpr/log_linux.cc:43:13: warning: 'long int gettid()' defined but not used [-Wunused-function]
   43 | static long gettid(void) { return syscall(__NR_gettid); }
      |             ^~~~~~
ERROR: /data/.cache/bazel/_bazel_test/9d8f535cf1766321e020e62e8d398482/external/llvm/BUILD.bazel:45:1: Couldn't build file external/llvm/include/llvm/Config/config.h: Executing genrule @llvm//:config_gen failed (Exit 1)
Traceback (most recent call last):
  File "bazel-out/host/bin/external/org_tensorflow/third_party/llvm/expand_cmake_vars", line 252, in <module>
    Main()
  File "bazel-out/host/bin/external/org_tensorflow/third_party/llvm/expand_cmake_vars", line 218, in Main
    program = python_program = FindPythonBinary(module_space)
  File "bazel-out/host/bin/external/org_tensorflow/third_party/llvm/expand_cmake_vars", line 60, in FindPythonBinary
    'Bazel does not support execution of Python interpreters via labels yet')
AssertionError: Bazel does not support execution of Python interpreters via labels yet
ERROR: /data/.cache/bazel/_bazel_test/9d8f535cf1766321e020e62e8d398482/external/llvm/BUILD.bazel:59:1: Couldn't build file external/llvm/include/llvm/Config/abi-breaking.h: Executing genrule @llvm//:abi_breaking_gen failed (Exit 1)
Traceback (most recent call last):
  File "bazel-out/host/bin/external/org_tensorflow/third_party/llvm/expand_cmake_vars", line 252, in <module>
    Main()
  File "bazel-out/host/bin/external/org_tensorflow/third_party/llvm/expand_cmake_vars", line 218, in Main
    program = python_program = FindPythonBinary(module_space)
  File "bazel-out/host/bin/external/org_tensorflow/third_party/llvm/expand_cmake_vars", line 60, in FindPythonBinary
    'Bazel does not support execution of Python interpreters via labels yet')
AssertionError: Bazel does not support execution of Python interpreters via labels yet
ERROR: /data/.cache/bazel/_bazel_test/9d8f535cf1766321e020e62e8d398482/external/llvm/BUILD.bazel:52:1: Couldn't build file external/llvm/include/llvm/Config/llvm-config.h: Executing genrule @llvm//:llvm_config_gen failed (Exit 1)
Traceback (most recent call last):
  File "bazel-out/host/bin/external/org_tensorflow/third_party/llvm/expand_cmake_vars", line 252, in <module>
    Main()
  File "bazel-out/host/bin/external/org_tensorflow/third_party/llvm/expand_cmake_vars", line 218, in Main
    program = python_program = FindPythonBinary(module_space)
  File "bazel-out/host/bin/external/org_tensorflow/third_party/llvm/expand_cmake_vars", line 60, in FindPythonBinary
    'Bazel does not support execution of Python interpreters via labels yet')
AssertionError: Bazel does not support execution of Python interpreters via labels yet
ERROR: /home/soft/tensorflow-r1.15/tensorflow/core/BUILD:2760:1: Couldn't build file tensorflow/core/util/version_info.cc: Executing genrule //tensorflow/core:version_info_gen failed (Exit 1)
Traceback (most recent call last):
  File "bazel-out/host/bin/tensorflow/tools/git/gen_git_source", line 252, in <module>
    Main()
  File "bazel-out/host/bin/tensorflow/tools/git/gen_git_source", line 218, in Main
    program = python_program = FindPythonBinary(module_space)
  File "bazel-out/host/bin/tensorflow/tools/git/gen_git_source", line 60, in FindPythonBinary
    'Bazel does not support execution of Python interpreters via labels yet')
AssertionError: Bazel does not support execution of Python interpreters via labels yet
ERROR: /data/.cache/bazel/_bazel_test/9d8f535cf1766321e020e62e8d398482/external/grpc/BUILD:507:1: Couldn't build file external/grpc/_objs/gpr_base/log_linux.pic.o: C++ compilation of rule '@grpc//:gpr_base' failed (Exit 1)
external/grpc/src/core/lib/gpr/log_linux.cc:43:13: error: ambiguating new declaration of 'long int gettid()'
   43 | static long gettid(void) { return syscall(__NR_gettid); }
      |             ^~~~~~
In file included from /usr/include/unistd.h:1170,
                 from external/grpc/src/core/lib/gpr/log_linux.cc:41:
/usr/include/x86_64-linux-gnu/bits/unistd_ext.h:34:16: note: old declaration '__pid_t gettid()'
   34 | extern __pid_t gettid (void) __THROW;
      |                ^~~~~~
ERROR: /home/soft/tensorflow-r1.15/tensorflow/python/BUILD:198:1: Couldn't build file tensorflow/python/platform/build_info.py: Executing genrule //tensorflow/python:py_build_info_gen failed (Exit 1)
Traceback (most recent call last):
  File "bazel-out/host/bin/tensorflow/tools/build_info/gen_build_info", line 252, in <module>
    Main()
  File "bazel-out/host/bin/tensorflow/tools/build_info/gen_build_info", line 218, in Main
    program = python_program = FindPythonBinary(module_space)
  File "bazel-out/host/bin/tensorflow/tools/build_info/gen_build_info", line 60, in FindPythonBinary
    'Bazel does not support execution of Python interpreters via labels yet')
AssertionError: Bazel does not support execution of Python interpreters via labels yet
ERROR: /home/soft/tensorflow-r1.15/tensorflow/python/BUILD:6940:1: Couldn't build file tensorflow/python/framework/fast_tensor_util.cpp: Executing genrule //tensorflow/python:framework/fast_tensor_util.pyx_cython_translation failed (Exit 1)
Traceback (most recent call last):
  File "bazel-out/host/bin/external/cython/cython_binary", line 252, in <module>
    Main()
  File "bazel-out/host/bin/external/cython/cython_binary", line 218, in Main
    program = python_program = FindPythonBinary(module_space)
  File "bazel-out/host/bin/external/cython/cython_binary", line 60, in FindPythonBinary
    'Bazel does not support execution of Python interpreters via labels yet')
AssertionError: Bazel does not support execution of Python interpreters via labels yet
ERROR: /home/soft/tensorflow-r1.15/tensorflow/core/BUILD:2760:1: Couldn't build file tensorflow/core/util/version_info.cc: Executing genrule //tensorflow/core:version_info_gen failed (Exit 1)
Traceback (most recent call last):
  File "bazel-out/host/bin/tensorflow/tools/git/gen_git_source", line 252, in <module>
    Main()
  File "bazel-out/host/bin/tensorflow/tools/git/gen_git_source", line 218, in Main
    program = python_program = FindPythonBinary(module_space)
  File "bazel-out/host/bin/tensorflow/tools/git/gen_git_source", line 60, in FindPythonBinary
    'Bazel does not support execution of Python interpreters via labels yet')
AssertionError: Bazel does not support execution of Python interpreters via labels yet
ERROR: /data/.cache/bazel/_bazel_test/9d8f535cf1766321e020e62e8d398482/external/grpc/BUILD:507:1: Couldn't build file external/grpc/_objs/gpr_base/log_linux.pic.o: C++ compilation of rule '@grpc//:gpr_base' failed (Exit 1)
external/grpc/src/core/lib/gpr/log_linux.cc:43:13: error: ambiguating new declaration of 'long int gettid()'
   43 | static long gettid(void) { return syscall(__NR_gettid); }
      |             ^~~~~~
In file included from /usr/include/unistd.h:1170,
                 from external/grpc/src/core/lib/gpr/log_linux.cc:41:
/usr/include/x86_64-linux-gnu/bits/unistd_ext.h:34:16: note: old declaration '__pid_t gettid()'
   34 | extern __pid_t gettid (void) __THROW;
      |                ^~~~~~
ERROR: /home/soft/tensorflow-r1.15/tensorflow/python/BUILD:6940:1: Couldn't build file tensorflow/python/framework/fast_tensor_util.cpp: Executing genrule //tensorflow/python:framework/fast_tensor_util.pyx_cython_translation failed (Exit 1)
Traceback (most recent call last):
  File "bazel-out/host/bin/external/cython/cython_binary", line 252, in <module>
    Main()
  File "bazel-out/host/bin/external/cython/cython_binary", line 218, in Main
    program = python_program = FindPythonBinary(module_space)
  File "bazel-out/host/bin/external/cython/cython_binary", line 60, in FindPythonBinary
    'Bazel does not support execution of Python interpreters via labels yet')
AssertionError: Bazel does not support execution of Python interpreters via labels yet
ERROR: /data/.cache/bazel/_bazel_test/9d8f535cf1766321e020e62e8d398482/external/llvm/BUILD.bazel:45:1: Couldn't build file external/llvm/include/llvm/Config/config.h: Executing genrule @llvm//:config_gen failed (Exit 1)
Traceback (most recent call last):
  File "bazel-out/host/bin/external/org_tensorflow/third_party/llvm/expand_cmake_vars", line 252, in <module>
    Main()
  File "bazel-out/host/bin/external/org_tensorflow/third_party/llvm/expand_cmake_vars", line 218, in Main
    program = python_program = FindPythonBinary(module_space)
  File "bazel-out/host/bin/external/org_tensorflow/third_party/llvm/expand_cmake_vars", line 60, in FindPythonBinary
    'Bazel does not support execution of Python interpreters via labels yet')
AssertionError: Bazel does not support execution of Python interpreters via labels yet
ERROR: /data/.cache/bazel/_bazel_test/9d8f535cf1766321e020e62e8d398482/external/llvm/BUILD.bazel:59:1: Couldn't build file external/llvm/include/llvm/Config/abi-breaking.h: Executing genrule @llvm//:abi_breaking_gen failed (Exit 1)
Traceback (most recent call last):
  File "bazel-out/host/bin/external/org_tensorflow/third_party/llvm/expand_cmake_vars", line 252, in <module>
    Main()
  File "bazel-out/host/bin/external/org_tensorflow/third_party/llvm/expand_cmake_vars", line 218, in Main
    program = python_program = FindPythonBinary(module_space)
  File "bazel-out/host/bin/external/org_tensorflow/third_party/llvm/expand_cmake_vars", line 60, in FindPythonBinary
    'Bazel does not support execution of Python interpreters via labels yet')
AssertionError: Bazel does not support execution of Python interpreters via labels yet
ERROR: /data/.cache/bazel/_bazel_test/9d8f535cf1766321e020e62e8d398482/external/llvm/BUILD.bazel:52:1: Couldn't build file external/llvm/include/llvm/Config/llvm-config.h: Executing genrule @llvm//:llvm_config_gen failed (Exit 1)
Traceback (most recent call last):
  File "bazel-out/host/bin/external/org_tensorflow/third_party/llvm/expand_cmake_vars", line 252, in <module>
    Main()
  File "bazel-out/host/bin/external/org_tensorflow/third_party/llvm/expand_cmake_vars", line 218, in Main
    program = python_program = FindPythonBinary(module_space)
  File "bazel-out/host/bin/external/org_tensorflow/third_party/llvm/expand_cmake_vars", line 60, in FindPythonBinary
    'Bazel does not support execution of Python interpreters via labels yet')
AssertionError: Bazel does not support execution of Python interpreters via labels yet
ERROR: /home/soft/tensorflow-r1.15/tensorflow/python/BUILD:198:1: Couldn't build file tensorflow/python/platform/build_info.py: Executing genrule //tensorflow/python:py_build_info_gen failed (Exit 1)
Traceback (most recent call last):
  File "bazel-out/host/bin/tensorflow/tools/build_info/gen_build_info", line 252, in <module>
    Main()
  File "bazel-out/host/bin/tensorflow/tools/build_info/gen_build_info", line 218, in Main
    program = python_program = FindPythonBinary(module_space)
  File "bazel-out/host/bin/tensorflow/tools/build_info/gen_build_info", line 60, in FindPythonBinary
    'Bazel does not support execution of Python interpreters via labels yet')
AssertionError: Bazel does not support execution of Python interpreters via labels yet
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3.951s, Critical Path: 0.09s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

**Comment by tilakrayal** [comment]
Hello @liuyang77886 ,
We see that you are using tf version 1.15, 1.x is not actively supported, please update to latest stable version 2.8 and let us know if you are facing same issue.Thanks!

**Comment by liuyang77886** [comment]
我想编译成1.x版本。我最开始使用tf2.8源代码，使用命令./bazel-5.1.1-linux-x86_64 build --config=v1 --copt=-mavx --copt=-mavx2 --copt=-msse --copt=-msse2 --copt=-mssse3   -k //tensorflow/tools/pip_package:build_pip_package，编译出来的还是tf2，使用tf2.8源代码--config=v1不能编译出v1版本吗

**Comment by tilakrayal** [comment]
@liuyang77886 ,
As suggested, can you please try to install latest stable tensorflow v2.8 from [here](https://www.tensorflow.org/install/source#install_bazel).Also provide the error log.It helps to analyse the issue.Thanks!
