### ISSUE TITLE
Breaking change in protobuf v4.21.0-rc1 breaks `import tensorflow`

### ISSUE THREAD

**Issue by matthewfeickert** [tensorflow/tensorflow#56077]
### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9.0-rc2

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.10

### Current Behaviour?

This issue is to give a warning (that might already be known in internal CI) that [`protobuf` `v4.21.0-rc1`](https://github.com/protocolbuffers/protobuf/releases/tag/v21.0-rc1) which was released today (2022-05-11) causes breaking changes in messages between Python and C++ that affect TensorFlow and will crash with

```pytb
AttributeError: module 'google._upb._message' has no attribute 'Message'. Did you mean: 'CMessage'?
```

on `import tensorflow`.

This is somewhat noted in the `protobuf` release notes for Python

> The C extension module for Python has been rewritten to use the upb library. This is expected to deliver significant performance benefits, especially when parsing large payloads. There are some minor breaking changes, but these should not impact most users. For more information see: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

where the [Python Updates notes](https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates) mentions

> Applications that rely on sharing messages between Python and C++ break in the new version. Most developers won't be affected by this, but users of `Nucleus{.external}` and possibly other libraries may be. As a workaround, you can [set an environment variable](https://developers.google.com/protocol-buffers/docs/reference/python-generated#sharing-messages) that forces the library to preserve compatibility.

which finally in [Sharing Messages Between Python and C++](https://developers.google.com/protocol-buffers/docs/reference/python-generated#sharing-messages) tells us that

> Prior to Python 4.21.0, Python apps could share messages with C++ using a native extension. Starting in Python 4.21.0, sharing messages between Python and C++ is not supported by the default install. To enable this capability when working with 4.x and later versions of the Python API, define the environment variable, `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp`, and ensure that the Python/C++ extension is installed.

However,

```console
$ export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp
```

just now leads to an

```pytb
ImportError: cannot import name '_message' from 'google.protobuf.pyext' (/venv/lib/python3.10/site-packages/google/protobuf/pyext/__init__.py)
```

Additionally tagging @deannagarcia who released [`protobuf` `v4.21.0-rc1`](https://github.com/protocolbuffers/protobuf/releases/tag/v21.0-rc1).

This was noticed in `pyhf`'s nightly [pre-release and HEAD of dependencies CI jobs](https://github.com/scikit-hep/pyhf/runs/6398925572?check_suite_focus=true).

### Standalone code to reproduce the issue

Here's a `python:3.10` Docker image example

<details>
<summary>Click to exapnd:</summary>

```console
$ docker run --rm -ti python:3.10 /bin/bash
root@a0c6928654f7:/# python -m venv venv && . venv/bin/activate
(venv) root@a0c6928654f7:/# python -m pip --quiet install --upgrade pip setuptools wheel
(venv) root@a0c6928654f7:/# python -m pip --quiet install 'tensorflow==2.8.0'  # First show this with stable release v2.8.0
(venv) root@a0c6928654f7:/# python -m pip list | grep 'tensorflow\|protobuf'
protobuf                     3.20.1
tensorflow                   2.8.0
tensorflow-io-gcs-filesystem 0.25.0
(venv) root@a0c6928654f7:/# python -c 'import tensorflow; print(tensorflow.__version__)'
2022-05-12 03:21:47.631420: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-05-12 03:21:47.631464: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2.8.0
(venv) root@a0c6928654f7:/# python -m pip --quiet install --pre --upgrade protobuf
(venv) root@a0c6928654f7:/# python -m pip show protobuf
Name: protobuf
Version: 4.21.0rc1
Summary: 
Home-page: 
Author: 
Author-email: 
License: 
Location: /venv/lib/python3.10/site-packages
Requires: 
Required-by: tensorboard, tensorflow
(venv) root@a0c6928654f7:/# python -c 'import tensorflow'
2022-05-12 03:23:19.770470: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-05-12 03:23:19.770491: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/venv/lib/python3.10/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/venv/lib/python3.10/site-packages/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "/venv/lib/python3.10/site-packages/tensorflow/python/eager/context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "/venv/lib/python3.10/site-packages/tensorflow/core/framework/function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/venv/lib/python3.10/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/venv/lib/python3.10/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/venv/lib/python3.10/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "/venv/lib/python3.10/site-packages/tensorflow/core/framework/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/venv/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
AttributeError: module 'google._upb._message' has no attribute 'Message'. Did you mean: 'CMessage'?
(venv) root@a0c6928654f7:/# export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp  # try protobuf environment variable suggestion
(venv) root@a0c6928654f7:/# python -c 'import tensorflow'
2022-05-12 03:23:50.884921: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-05-12 03:23:50.884945: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/venv/lib/python3.10/site-packages/google/protobuf/internal/api_implementation.py:109: UserWarning: Selected implementation cpp is not available.
  warnings.warn(
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/venv/lib/python3.10/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/venv/lib/python3.10/site-packages/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "/venv/lib/python3.10/site-packages/tensorflow/python/eager/context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "/venv/lib/python3.10/site-packages/tensorflow/core/framework/function_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/venv/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 51, in <module>
    from google.protobuf.pyext import _message
ImportError: cannot import name '_message' from 'google.protobuf.pyext' (/venv/lib/python3.10/site-packages/google/protobuf/pyext/__init__.py)
(venv) root@a0c6928654f7:/# unset PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
(venv) root@a0c6928654f7:/# python -m pip --quiet install --pre --upgrade tensorflow  # Try release candidate v2.9.0-rc2
(venv) root@a0c6928654f7:/# python -m pip show tensorflow
Name: tensorflow
Version: 2.9.0rc2
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /venv/lib/python3.10/site-packages
Requires: absl-py, astunparse, flatbuffers, gast, google-pasta, grpcio, h5py, keras, keras-preprocessing, libclang, numpy, opt-einsum, packaging, protobuf, setuptools, six, tensorboard, tensorflow-estimator, tensorflow-io-gcs-filesystem, termcolor, typing-extensions, wrapt
Required-by
(venv) root@a0c6928654f7:/# python -c 'import tensorflow'
2022-05-12 03:26:20.957106: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-05-12 03:26:20.957131: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/venv/lib/python3.10/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/venv/lib/python3.10/site-packages/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "/venv/lib/python3.10/site-packages/tensorflow/python/eager/context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "/venv/lib/python3.10/site-packages/tensorflow/core/framework/function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/venv/lib/python3.10/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/venv/lib/python3.10/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/venv/lib/python3.10/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "/venv/lib/python3.10/site-packages/tensorflow/core/framework/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/venv/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
AttributeError: module 'google._upb._message' has no attribute 'Message'. Did you mean: 'CMessage'?
(venv) root@a0c6928654f7:/# export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp
(venv) root@a0c6928654f7:/# python -c 'import tensorflow'
2022-05-12 03:27:01.166115: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-05-12 03:27:01.166141: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/venv/lib/python3.10/site-packages/google/protobuf/internal/api_implementation.py:109: UserWarning: Selected implementation cpp is not available.
  warnings.warn(
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/venv/lib/python3.10/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/venv/lib/python3.10/site-packages/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "/venv/lib/python3.10/site-packages/tensorflow/python/eager/context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "/venv/lib/python3.10/site-packages/tensorflow/core/framework/function_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/venv/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 51, in <module>
    from google.protobuf.pyext import _message
ImportError: cannot import name '_message' from 'google.protobuf.pyext' (/venv/lib/python3.10/site-packages/google/protobuf/pyext/__init__.py)
```

</details>

### Relevant log output

```pytb
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/venv/lib/python3.10/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/venv/lib/python3.10/site-packages/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "/venv/lib/python3.10/site-packages/tensorflow/python/eager/context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "/venv/lib/python3.10/site-packages/tensorflow/core/framework/function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/venv/lib/python3.10/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/venv/lib/python3.10/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/venv/lib/python3.10/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "/venv/lib/python3.10/site-packages/tensorflow/core/framework/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/venv/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
AttributeError: module 'google._upb._message' has no attribute 'Message'. Did you mean: 'CMessage'?
```

```pytb
/venv/lib/python3.10/site-packages/google/protobuf/internal/api_implementation.py:109: UserWarning: Selected implementation cpp is not available.
  warnings.warn(
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/venv/lib/python3.10/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/venv/lib/python3.10/site-packages/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "/venv/lib/python3.10/site-packages/tensorflow/python/eager/context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "/venv/lib/python3.10/site-packages/tensorflow/core/framework/function_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/venv/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 51, in <module>
    from google.protobuf.pyext import _message
ImportError: cannot import name '_message' from 'google.protobuf.pyext' (/venv/lib/python3.10/site-packages/google/protobuf/pyext/__init__.py)
```

**Comment by parthea** [comment]
The issue may be resolved if you install `grpcio-tools==1.44.0`. See https://github.com/protocolbuffers/protobuf/issues/9954

**Comment by gadagashwini** [comment]
@matthewfeickert,
`tensorflow==2.9.0-rc2` support `grpcio==1.44.0` and `protobuf==3.17.3`.

Protobuf and grpcio version compatible ranges
```
protobuf>=3.9.2
grpcio<2.0,>=1.24.3
```

**Comment by matthewfeickert** [comment]
>`tensorflow==2.9.0-rc2` support `grpcio==1.44.0` and `protobuf==3.17.3`.
> 
> Protobuf and grpcio version compatible ranges
> 
> ```
> protobuf>=3.9.2
> grpcio<2.0,>=1.24.3
> ```

@gadagashwini Yes, I showed the  (relevant snippets) of `v2.9.0-rc2` `install_requires` in my previous response https://github.com/tensorflow/tensorflow/issues/56077#issuecomment-1125255060. Here is a slightly expanded view again

https://github.com/tensorflow/tensorflow/blob/84326b3712ebc48827d7a0bce087c15ab6b389a6/tensorflow/tools/pip_package/setup.py#L90-L100

As soon as `protobuf` `v4.21.0` is released then it will get picked up by TensorFlow and break installs. This is easy to fix (users just downgrade `protobuf`) but if the TensorFlow dev team can coordinate with the `protobuf` team on when release candidates will get bumped to releases, TensorFlow `v2.9.0` could be released with everything working smoothly.

@haberman I'm not sure if you're able to say yet, but do you know roughly when the `protobuf` team is targeting release of `v4.21.0`?

**Comment by haberman** [comment]
> The TensorFlow team just needs to make sure that they regenerate the _pb2.py files for the next RC or release with the appropriate version of protoc installed, given @haberman's comment https://github.com/tensorflow/tensorflow/issues/56077#issuecomment-1125199927

Yes exactly, I think regenerating the `_pb2.py` files as soon as you can is the best resolution here.

> Though I guess on some OS that requires getting it not from your package manager given:

Yes, you generally want stronger guarantees that protoc will match your runtime library. C++ requires an exact match. Other languages have been somewhat more lax, but it's best to avoid relying on that.

> do you know roughly when the protobuf team is targeting release of v4.21.0?

We are hoping to release v4.21.0 next week. Would you be able to regenerate the `_pb2.py` files in the next few days?

> Also, is there a reason the release is tagged as [v21.0-rc1 in GitHub](https://github.com/protocolbuffers/protobuf/releases/tag/v21.0-rc1) when it is v4.21.0-rc1

See the note here: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#versioning

**Comment by matthewfeickert** [comment]
This never got addressed by the TensorFlow team and now TensorFlow v2.9.0 is broken.

**Comment by matthewfeickert** [comment]
Thank you @mihaimaruseac for taking action to add an upper bound for the time being. :+1:

**Comment by mihaimaruseac** [comment]
Apologies for missing this before the release. We should be getting the patch releases tomorrow if all goes well.

**Comment by matthewfeickert** [comment]
@mihaimaruseac As the patch releases are now out (:rocket:) (e.g. [`v2.9.1`](https://github.com/tensorflow/tensorflow/releases/tag/v2.9.1)) so that there is no breaking with `python -m pip install --pre` and I assume that updates for protobuf are now on some TODO board connected somewhere to Piper I'm going to close this Issue as I assume that in the future sometime we'll be seeing the lower bond on `protobuf` get switched to `>=3.20`.
