### ISSUE TITLE
TensorFlow 2.9 ImportError: cannot import name 'keras' from 'tensorflow'

### ISSUE THREAD

**Issue by snowuyl** [tensorflow/tensorflow#56131]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.9

### Custom Code

No

### OS Platform and Distribution

MacOS 12.3.1（M1 arm64CPU)

### Python version

3.9.12

### Bazel version

5.0.0

### Current Behaviour?

```shell
A bug happened!
```

### Standalone code to reproduce the issue

```shell
bazel build -c opt //tensorflow/tools/pip_package:build_pip_package
bazel-bin/tensorflow/tools/pip_package/build_pip_package .
pip3 install tensorflow-2.9.0-cp39-cp39-macosx_12_0_arm64.whl 
python3
from tensorflow import keras
```

### Relevant log output

```shell
python3
Python 3.9.12 (main, May  8 2022, 17:57:49) 
[Clang 13.1.6 (clang-1316.0.21.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from tensorflow import keras
Traceback (most recent call last):
  File "/Users/andyueng/samba/workspace_TensorFlow2/tensorflow-2.9.0_pip_package/tensorflow/python/platform/self_check.py", line 23, in <module>
    from tensorflow.python.platform import build_info
ImportError: cannot import name 'build_info' from 'tensorflow.python.platform' (/Users/andyueng/samba/workspace_TensorFlow2/tensorflow-2.9.0_pip_package/tensorflow/python/platform/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/andyueng/samba/workspace_TensorFlow2/tensorflow-2.9.0_pip_package/tensorflow/__init__.py", line 20, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/Users/andyueng/samba/workspace_TensorFlow2/tensorflow-2.9.0_pip_package/tensorflow/python/__init__.py", line 36, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/Users/andyueng/samba/workspace_TensorFlow2/tensorflow-2.9.0_pip_package/tensorflow/python/pywrap_tensorflow.py", line 21, in <module>
    from tensorflow.python.platform import self_check
  File "/Users/andyueng/samba/workspace_TensorFlow2/tensorflow-2.9.0_pip_package/tensorflow/python/platform/self_check.py", line 25, in <module>
    raise ImportError("Could not import tensorflow. Do not import tensorflow "
ImportError: Could not import tensorflow. Do not import tensorflow from its source directory; change directory to outside the TensorFlow source tree, and relaunch your Python interpreter from there.
```
</details>

**Comment by snowuyl** [comment]
When will TensorFlow 2.9.0 release for macOS?

**Comment by tilakrayal** [comment]
Hello @snowuyl ,
For Apple M1 chip, you can install it through miniforge installers by following the guide [here](https://developer.apple.com/metal/tensorflow-plugin/).
Since, few of the mentioned packages in the above link are community build, could you wait for sometime to get the 2.9 dependencies.

**Comment by snowuyl** [comment]
% pip3 install tensorflow-macos==2.9.0
Successfully installed tensorflow-macos-2.9.0
% python3
Python 3.9.12 (main, May 8 2022, 17:57:49)
[Clang 13.1.6 (clang-1316.0.21.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

import tensorflow as tf
print(tf.version)
2.9.0
from tensorflow.keras import layers
