### ISSUE TITLE
COLAB : DNN library is not found. 

### ISSUE THREAD

**Issue by SanjayGhanagiri** [tensorflow/tensorflow#56135]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.8

### Custom Code

Yes

### OS Platform and Distribution

Colab

### Python version

3.9

### Current Behaviour?

```shell
Unable to train custom tflite model using tensorflow 2.8 version.
```

### Standalone code to reproduce the issue

```shell
https://www.tensorflow.org/lite/tutorials/model_maker_object_detection
https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/tutorials/model_maker_object_detection.ipynb

While trying to train a custom tf lite model on Colab. Training fails with above error.(DNN library is not found.)

Currently the official notebook is not accessible. Getting Notebook not found
```

### Relevant log output

```shell
UnimplementedError                        Traceback (most recent call last)
<ipython-input-10-187f39c1697e> in <module>()
----> 1 model = object_detector.create(train_data, model_spec=spec, batch_size=8, train_whole_model=True, validation_data=validation_data)

4 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     53     ctx.ensure_initialized()
     54     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 55                                         inputs, attrs, num_outputs)
     56   except core._NotOkStatusException as e:
     57     if name is not None:

UnimplementedError: Graph execution error:

DNN library is not found.
	 [[{{node stem/conv2d/Conv2D}}]] [Op:__inference_train_function_96447]
```
</details>

**Comment by BasanthVerma** [comment]
I also couldn't run the colab example on this link, the github repo link also seems to be broken https://www.tensorflow.org/lite/tutorials/model_maker_object_detection

**Comment by chintan-tiger** [comment]
I too am facing a similar issue in colab, with Conv1D. I have been using the following code and it was never an issue until before few days.
Note that this works fine on CPU. But issue occurs only when I switch to GPU in colab.
Tried rolling back from latest tensorflow version to tensorflow==2.7.0. Still facing same issue.

```
def create_model(input_shape, model_output_len):
  tf.keras.backend.clear_session()
  input_layer = Input(shape=(input_shape,1), name='input_layer')

  c1 = Conv1D(filters=128, kernel_size=8, strides=2, padding='same', activation='elu', name='Conv1D_1', \
              kernel_initializer=initializers.glorot_uniform(seed=33), bias_initializer=initializers.HeUniform(seed=33))(input_layer)
  c2 = Conv1D(filters=64, kernel_size=4, strides=1, padding='same', activation='elu', name='Conv1D_2', \
              kernel_initializer=initializers.glorot_uniform(seed=33), bias_initializer=initializers.HeUniform(seed=33))(c1)
  dense = Flatten()(c2)

  dense = Dense(units=512, \
                kernel_initializer=initializers.glorot_uniform(seed=33), bias_initializer=initializers.HeUniform(seed=33), \
                kernel_regularizer=regularizers.L2(0.01))(dense)
  dense = ELU()(dense)
  dense = Dropout(0.33, seed=33)(dense)
  dense = Dense(units=512, activation='elu', \
                kernel_initializer=initializers.glorot_uniform(seed=33), bias_initializer=initializers.HeUniform(seed=33), \
                kernel_regularizer=regularizers.L2(0.01))(dense)
  out = Dense(units=model_output_len, activation='sigmoid', name='output')(dense)

  model = Model(inputs=input_layer, outputs=out)
  return model

model = create_model(X_train_pooled_output.shape[1], y_train.shape[1])
```

```
EPOCHS = 1000
BATCH_SIZE = 1024
adam = Adam(learning_rate=0.0003)
model.compile(optimizer=adam, loss='binary_crossentropy', metrics=['accuracy', tf.keras.metrics.AUC(multi_label=True, num_thresholds=5000)])
CALLBACKS_LIST = [earlystop, lrschedule, cb_metrics]
model_hist = model.fit(x=X_train_pooled_output, y=y_train, validation_data=(X_test_pooled_output, y_test), epochs=EPOCHS, batch_size=BATCH_SIZE, verbose=True, callbacks=CALLBACKS_LIST)
```

Error as follows,

```
Epoch 1/1000
---------------------------------------------------------------------------
UnimplementedError                        Traceback (most recent call last)
[<ipython-input-93-967ca4d509d9>](https://localhost:8080/#) in <module>()
      4 model.compile(optimizer=adam, loss=weighted_binary_crossentropy, metrics=['accuracy', tf.keras.metrics.AUC(multi_label=True, num_thresholds=5000)])
      5 CALLBACKS_LIST = [earlystop, lrschedule, cb_metrics]
----> 6 model_hist = model.fit(x=X_train_pooled_output, y=y_train, validation_data=(X_test_pooled_output, y_test), epochs=EPOCHS, batch_size=BATCH_SIZE, verbose=True, callbacks=CALLBACKS_LIST)

1 frames
[/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py](https://localhost:8080/#) in error_handler(*args, **kwargs)
     65     except Exception as e:  # pylint: disable=broad-except
     66       filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67       raise e.with_traceback(filtered_tb) from None
     68     finally:
     69       del filtered_tb

[/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py](https://localhost:8080/#) in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     53     ctx.ensure_initialized()
     54     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 55                                         inputs, attrs, num_outputs)
     56   except core._NotOkStatusException as e:
     57     if name is not None:

UnimplementedError: Graph execution error:

Detected at node 'model/Conv1D_1/Conv1D' defined at (most recent call last):
    File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py", line 16, in <module>
      app.launch_new_instance()
    File "/usr/local/lib/python3.7/dist-packages/traitlets/config/application.py", line 972, in launch_instance
      app.start()
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelapp.py", line 499, in start
      self.io_loop.start()
    File "/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py", line 132, in start
      self.asyncio_loop.run_forever()
    File "/usr/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
      self._run_once()
    File "/usr/lib/python3.7/asyncio/base_events.py", line 1786, in _run_once
      handle._run()
    File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
      self._context.run(self._callback, *self._args)
    File "/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py", line 758, in _run_callback
      ret = callback()
    File "/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 536, in <lambda>
      self.io_loop.add_callback(lambda: self._handle_events(self.socket, 0))
    File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 452, in _handle_events
      self._handle_recv()
    File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 481, in _handle_recv
      self._run_callback(callback, msg)
    File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 431, in _run_callback
      callback(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
      return self.dispatch_shell(stream, msg)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
      handler(stream, idents, msg)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
      user_expressions, allow_stdin)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/ipkernel.py", line 208, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/zmqshell.py", line 537, in run_cell
      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2718, in run_cell
      interactivity=interactivity, compiler=compiler, result=result)
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2822, in run_ast_nodes
      if self.run_code(code, result):
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "<ipython-input-93-967ca4d509d9>", line 6, in <module>
      model_hist = model.fit(x=X_train_pooled_output, y=y_train, validation_data=(X_test_pooled_output, y_test), epochs=EPOCHS, batch_size=BATCH_SIZE, verbose=True, callbacks=CALLBACKS_LIST)
    File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1384, in fit
      tmp_logs = self.train_function(iterator)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1021, in train_function
      return step_function(self, iterator)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1010, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1000, in run_step
      outputs = model.train_step(data)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 859, in train_step
      y_pred = self(x, training=True)
    File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py", line 1096, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/functional.py", line 452, in call
      inputs, training=training, mask=mask)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/functional.py", line 589, in _run_internal_graph
      outputs = node.layer(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py", line 1096, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/layers/convolutional.py", line 248, in call
      outputs = self.convolution_op(inputs, self.kernel)
    File "/usr/local/lib/python3.7/dist-packages/keras/layers/convolutional.py", line 240, in convolution_op
      name=self.__class__.__name__)
Node: 'model/Conv1D_1/Conv1D'
Detected at node 'model/Conv1D_1/Conv1D' defined at (most recent call last):
    File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py", line 16, in <module>
      app.launch_new_instance()
    File "/usr/local/lib/python3.7/dist-packages/traitlets/config/application.py", line 972, in launch_instance
      app.start()
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelapp.py", line 499, in start
      self.io_loop.start()
    File "/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py", line 132, in start
      self.asyncio_loop.run_forever()
    File "/usr/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
      self._run_once()
    File "/usr/lib/python3.7/asyncio/base_events.py", line 1786, in _run_once
      handle._run()
    File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
      self._context.run(self._callback, *self._args)
    File "/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py", line 758, in _run_callback
      ret = callback()
    File "/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 536, in <lambda>
      self.io_loop.add_callback(lambda: self._handle_events(self.socket, 0))
    File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 452, in _handle_events
      self._handle_recv()
    File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 481, in _handle_recv
      self._run_callback(callback, msg)
    File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 431, in _run_callback
      callback(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
      return self.dispatch_shell(stream, msg)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
      handler(stream, idents, msg)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
      user_expressions, allow_stdin)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/ipkernel.py", line 208, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/zmqshell.py", line 537, in run_cell
      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2718, in run_cell
      interactivity=interactivity, compiler=compiler, result=result)
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2822, in run_ast_nodes
      if self.run_code(code, result):
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "<ipython-input-93-967ca4d509d9>", line 6, in <module>
      model_hist = model.fit(x=X_train_pooled_output, y=y_train, validation_data=(X_test_pooled_output, y_test), epochs=EPOCHS, batch_size=BATCH_SIZE, verbose=True, callbacks=CALLBACKS_LIST)
    File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1384, in fit
      tmp_logs = self.train_function(iterator)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1021, in train_function
      return step_function(self, iterator)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1010, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1000, in run_step
      outputs = model.train_step(data)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 859, in train_step
      y_pred = self(x, training=True)
    File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py", line 1096, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/functional.py", line 452, in call
      inputs, training=training, mask=mask)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/functional.py", line 589, in _run_internal_graph
      outputs = node.layer(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py", line 1096, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/layers/convolutional.py", line 248, in call
      outputs = self.convolution_op(inputs, self.kernel)
    File "/usr/local/lib/python3.7/dist-packages/keras/layers/convolutional.py", line 240, in convolution_op
      name=self.__class__.__name__)
Node: 'model/Conv1D_1/Conv1D'
2 root error(s) found.
  (0) UNIMPLEMENTED:  DNN library is not found.
	 [[{{node model/Conv1D_1/Conv1D}}]]
	 [[assert_greater_equal/Assert/AssertGuard/pivot_f/_3/_15]]
  (1) UNIMPLEMENTED:  DNN library is not found.
	 [[{{node model/Conv1D_1/Conv1D}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_115519]
```

**Comment by sachinprasadhs** [comment]
Model maker examples have been moved to separate repository. 
You can check the collab and github source using this path https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/models/modify/model_maker/object_detection.ipynb 
and try running the example in Tensorflow 2.9 and let us know if you face the problem again.
I will file a PR for broken link fix. Thanks!

**Comment by SanjayGhanagiri** [comment]
> 2.9

@sachinprasadhs Even after trying `!pip install  tensorflow==2.9`
and 
```
!pip install -q --use-deprecated=legacy-resolver tflite-model-maker
!pip install -q pycocotools
```
It fails to import necessary  tflite model maker imports.

from tflite_model_maker.config import QuantizationConfig


`---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
[<ipython-input-3-9b5718f30578>](https://localhost:8080/#) in <module>()
      2 import os
      3 
----> 4 from tflite_model_maker.config import QuantizationConfig
      5 from tflite_model_maker.config import ExportFormat
      6 from tflite_model_maker import model_spec

11 frames
[/usr/local/lib/python3.7/dist-packages/sounddevice.py](https://localhost:8080/#) in <module>()
     69             break
     70     else:
---> 71         raise OSError('PortAudio library not found')
     72     _lib = _ffi.dlopen(_libname)
     73 except OSError:

OSError: PortAudio library not found`

**Comment by sachinprasadhs** [comment]
Hi the issue has been resolved by installing the below required dependencies, please find the gist [here](https://colab.sandbox.google.com/gist/sachinprasadhs/fa27f14dc9e095b2e29326b9bf7b6d03/model-maker-object-detection-tutorial.ipynb) for reference.

```
!sudo apt -y install libportaudio2
!pip install -q --use-deprecated=legacy-resolver tflite-model-maker
!pip install -q pycocotools
!pip install -q opencv-python-headless==4.1.2.30
!pip uninstall -y tensorflow && pip install -q tensorflow==2.8.0
```

**Comment by iamrohit1** [comment]
> Hi the issue has been resolved by installing the below required dependencies, please find the gist [here](https://colab.sandbox.google.com/gist/sachinprasadhs/fa27f14dc9e095b2e29326b9bf7b6d03/model-maker-object-detection-tutorial.ipynb) for reference. Link to the colab in the website has been updated, it will reflect soon. Till then you can access the notebook using the link [here](https://colab.sandbox.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/models/modify/model_maker/object_detection.ipynb).
> 
> ```
> !sudo apt -y install libportaudio2
> !pip install -q --use-deprecated=legacy-resolver tflite-model-maker
> !pip install -q pycocotools
> !pip install -q opencv-python-headless==4.1.2.30
> !pip uninstall -y tensorflow && pip install -q tensorflow==2.8.0
> ```

Its now unable to import scann. Could you try running it again?

**Comment by mohantym** [comment]
Hi @SanjayGhanagiri !
I could run the [Colab notebook](https://colab.sandbox.google.com/gist/mohantym/1f8ea929c068274d4f689a3d1e14349a/model-maker-object-detection-tutorial.ipynb#scrollTo=Gb7qyhNL1yWt) in GPU run time without any issue. Could you let us know from your end.
Thank you!
