### ISSUE TITLE
 tflite_convert --saved_model_dir command throws error "SavedModel file does not exist {saved_model.pbtxt|saved_model.pb}" 

### ISSUE THREAD

**Issue by gauravxgolu** [tensorflow/tensorflow#56149]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

v2.9.0

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 18.04

### Python version

3.7.13

### Current Behaviour?

```shell
I am trying to convert the tf model to tflite model. I have downloaded the tf model "spaghettinet_edgetpu_s" from GitHub and extracted it. The extracted folder contains all te required files(.pb, .pbtxt, and others). 
Run the "tflite_convert --saved_model_dir  --output_file" command and expect to generate the tflite model file.
```

### Standalone code to reproduce the issue

```shell
1)  Downalod the model "spaghettinet_edgetpu_s"  (https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md#pixel-6-edge-tpu-models)
2) extract it.
3) Folde contains these files: ~/data/sample/model/spaghettinet_edgetpu_s$ ls
checkpoint                 graph.pbtxt                            model.ckpt-400000.index  model.tflite
frozen_inference_graph.pb  model.ckpt-400000.data-00000-of-00001  model.ckpt-400000.meta   pipeline.config
4) Run: tflite_convert   --saved_model_dir=/home/gaurav/data/sample/model/spaghettinet_edgetpu_m  --output_file=/home/gaurav/data/sample/model/model_m.tflite
```

### Relevant log output

```shell
~/data/sample/model$ tflite_convert   --saved_model_dir=/home/gaurav/data/sample/model/spaghettinet_edgetpu_m  --output_file=/home/gaurav/data/sample/model/model_m.tflite
2022-05-18 14:04:23.552150: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Traceback (most recent call last):
  File "/home/gaurav/.local/bin/tflite_convert", line 8, in <module>
    sys.exit(main())
  File "/home/gaurav/.local/lib/python3.7/site-packages/tensorflow/lite/python/tflite_convert.py", line 692, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/home/gaurav/.local/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/gaurav/.local/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/gaurav/.local/lib/python3.7/site-packages/tensorflow/lite/python/tflite_convert.py", line 675, in run_main
    _convert_tf2_model(tflite_flags)
  File "/home/gaurav/.local/lib/python3.7/site-packages/tensorflow/lite/python/tflite_convert.py", line 279, in _convert_tf2_model
    tags=_parse_set(flags.saved_model_tag_set))
  File "/home/gaurav/.local/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 1786, in from_saved_model
    saved_model = _load(saved_model_dir, tags)
  File "/home/gaurav/.local/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 782, in load
    result = load_partial(export_dir, None, tags, options)["root"]
  File "/home/gaurav/.local/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 887, in load_partial
    loader_impl.parse_saved_model_with_debug_info(export_dir))
  File "/home/gaurav/.local/lib/python3.7/site-packages/tensorflow/python/saved_model/loader_impl.py", line 57, in parse_saved_model_with_debug_info
    saved_model = parse_saved_model(export_dir)
  File "/home/gaurav/.local/lib/python3.7/site-packages/tensorflow/python/saved_model/loader_impl.py", line 116, in parse_saved_model
    f"SavedModel file does not exist at: {export_dir}{os.path.sep}"
OSError: SavedModel file does not exist at: /home/gaurav/data/sample/model/spaghettinet_edgetpu_m/{saved_model.pbtxt|saved_model.pb}
```
</details>

**Comment by gauravxgolu** [comment]
I have got the reason to throw this error. Actually, I am trying to convert tf1 generated model in tf2 installed version.

**Comment by mohantym** [comment]
Hi @gauravxgolu ! Check the 1.x and 2.x converters from [this repo](https://github.com/tensorflow/models/tree/master/research/object_detection) too?  Thank you!
