### ISSUE TITLE
Model training error

### ISSUE THREAD

**Issue by faysalhossain2007** [tensorflow/tensorflow#56208]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

2.6.2

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 18.04

### Python version

3.8.11

### Current Behaviour?

```shell
Sometimes my model works fine it goes up to 10 epochs without any problems. Sometimes it ends up by crashing the program. Even the crash occurred after a few epochs and sometimes in the middle of an epoch. My Model architecture looks like this-

Layer (type)                 Output Shape              Param #   
=================================================================
masking_2 (Masking)          (None, 200, 16)           0         
_________________________________________________________________
bidirectional_4 (Bidirection (None, 200, 512)          419328    
_________________________________________________________________
dropout_4 (Dropout)          (None, 200, 512)          0         
_________________________________________________________________
bidirectional_5 (Bidirection (None, 512)               1181184   
_________________________________________________________________
dropout_5 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 513       
=================================================================
Total params: 1,601,025
Trainable params: 1,601,025
Non-trainable params: 0
_________________________________________________________________


Here I am attaching one example where the program stops in the middle of an epoch:

1493/3750 [==========>...................] - ETA: 32:06 - loss: 2.2078 - true_positives_2: 550.0000 - false_positives_2: 2011.0000 - true_negatives_2: 7292.0000 - false_negatives_2: 2091.0000 - precision_2: 0.2148 - recall_2: 0.2083
1494/3750 [==========>...................] - ETA: 32:05 - loss: 2.2072 - true_positives_2: 550.0000 - false_positives_2: 2011.0000 - true_negatives_2: 7298.0000 - false_negatives_2: 2093.0000 - precision_2: 0.2148 - recall_2: 0.2081
1495/3750 [==========>...................] - ETA: 32:04 - loss: 2.2071 - true_positives_2: 550.0000 - false_positives_2: 2015.0000 - true_negatives_2: 7300.0000 - false_negatives_2: 2095.0000 - precision_2: 0.2144 - recall_2: 0.2079
```

### Standalone code to reproduce the issue

```shell
I am attaching my model code:


    model = Sequential()
    
    model.add(Masking(mask_value=0.0, input_shape=(maxlen, vector_dim)))
    
    for i in range(1, layers):
        model.add(Bidirectional(GRU(units=256, activation='tanh', recurrent_activation='hard_sigmoid', return_sequences=True)))
        model.add(Dropout(dropout))
        
    model.add(Bidirectional(GRU(units=256, activation='tanh', recurrent_activation='hard_sigmoid')))
    model.add(Dropout(dropout))
    
    model.add(Dense(1, activation='sigmoid'))

    if optimizer == "adam":
        optimizer = tf.keras.optimizers.Adam(learning_rate=lr)

    elif optimizer == "adamax":
        optimizer = tf.keras.optimizers.Adamax(learning_rate=lr)

    model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=[
        tf.keras.metrics.TruePositives(),
        tf.keras.metrics.FalsePositives(),
        tf.keras.metrics.TrueNegatives(),
        tf.keras.metrics.FalseNegatives(),
        tf.keras.metrics.Precision(),
        tf.keras.metrics.Recall()]
    )
 
    return model
```
```


### Relevant log output

```shell
Traceback (most recent call last):
  File "bgru_graph_grid_search.py", line 579, in <module>
    perform_grid_search()
  File "bgru_graph_grid_search.py", line 502, in perform_grid_search
    main(raw_dataset, labels, traindataSetPath, testdataSetPath, realtestdataSetPath, weightPath, resultPath,
  File "bgru_graph_grid_search.py", line 180, in main
    model.fit(train_generator, validation_steps=1, steps_per_epoch=steps_epoch, epochs=epoch, verbose=1, callbacks=[checkpoint])
  File "/home/faysal-gpu/anaconda3/envs/py37_maml/lib/python3.8/site-packages/keras/engine/training.py", line 1184, in fit
    tmp_logs = self.train_function(iterator)
  File "/home/faysal-gpu/anaconda3/envs/py37_maml/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 885, in __call__
    result = self._call(*args, **kwds)
  File "/home/faysal-gpu/anaconda3/envs/py37_maml/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 917, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/home/faysal-gpu/anaconda3/envs/py37_maml/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3039, in __call__
    return graph_function._call_flat(
  File "/home/faysal-gpu/anaconda3/envs/py37_maml/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1963, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/home/faysal-gpu/anaconda3/envs/py37_maml/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 591, in call
    outputs = execute.execute(
  File "/home/faysal-gpu/anaconda3/envs/py37_maml/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  assertion failed: [predictions must be >= 0] [Condition x >= y did not hold element-wise:] [x (sequential_2/dense_2/Sigmoid:0) = ] [[nan][nan][nan]...] [y (Cast_3/x:0) = ] [0]
	 [[{{node assert_greater_equal/Assert/AssertGuard/else/_2663/assert_greater_equal/Assert/AssertGuard/Assert}}]]
	 [[assert_greater_equal_4/Assert/AssertGuard/pivot_f/_2745/_651]]
  (1) Invalid argument:  assertion failed: [predictions must be >= 0] [Condition x >= y did not hold element-wise:] [x (sequential_2/dense_2/Sigmoid:0) = ] [[nan][nan][nan]...] [y (Cast_3/x:0) = ] [0]
	 [[{{node assert_greater_equal/Assert/AssertGuard/else/_2663/assert_greater_equal/Assert/AssertGuard/Assert}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_16916]

Function call stack:
train_function -> train_function

2022-05-22 09:13:12.319808: W tensorflow/core/kernels/data/generator_dataset_op.cc:107] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]
```
</details>

**Comment by faysalhossain2007** [comment]
I even try to increase GPU growth 

```
config = tf.compat.v1.ConfigProto(gpu_options=tf.compat.v1.GPUOptions(allow_growth=True))
sess = tf.compat.v1.Session(config=config)
```

**Comment by tilakrayal** [comment]
Hi @faysalhossain2007 ,
The code which was shared is full of [indentation errors](https://colab.research.google.com/gist/tilakrayal/2517242e75a35584dd15374dad44f30e/untitled352.ipynb). Could you share a colab gist with issue reported or simple stand alone indented code with all dependencies.  It allows us to determine the source of the issue easily. Thank you!

**Comment by tilakrayal** [comment]
@faysalhossain2007,
Thanks for opening this issue. Development of keras moved to another [repository](https://github.com/keras-team/keras/issues). 
 
 
Could you please post this issue on keras-team/keras [repo](https://github.com/keras-team/keras/issues).
To know more please refer:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!
