### ISSUE TITLE
Document Dataset.repeat(0)

### ISSUE THREAD

**Issue by jamesbraza** [tensorflow/tensorflow#56215]
### Issue Type

Documentation Bug

### Source

binary

### Tensorflow Version

2.9

### Custom Code

No

### OS Platform and Distribution

n/a

### Python version

3.10

### Bazel version

n/a

### GCC/Compiler version

n/a

### CUDA/cuDNN version

n/a

### GPU model and memory

n/a

### Current Behaviour?

```shell
When using Keras `model.fit(validation_data=val_ds)` where `val_ds` is a `Dataset` created via `val_ds.repeat(0)`, the below exception will be raised:


96/96 [==============================] - ETA: 0s - loss: 2.8148 - accuracy: 0.2789Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.8.13/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/.pyenv/versions/3.8.13/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/james/code/cs230-project/training/vgg16_train.py", line 68, in <module>
    history: tf.keras.callbacks.History = model.fit(
  File "/home/ubuntu/james/code/cs230-project/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1113, in fit
    self._eval_data_handler = data_adapter.DataHandler(
  File "/home/ubuntu/james/code/cs230-project/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 1100, in __init__
    self._adapter = adapter_cls(
  File "/home/ubuntu/james/code/cs230-project/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 779, in __init__
    peek, x = self._peek_and_restore(x)
  File "/home/ubuntu/james/code/cs230-project/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 836, in _peek_and_restore
    peek = next(x)
StopIteration


I had wanted to basically go through the list once, so I thought I should set `count=0`.  In other words, `ds.repeat` will not work when `count=0`, but does work when `count=1`.

The documentation currently documents two special cases:

> The default behavior (if count is `None` or `-1`) is for the dataset be repeated indefinitely.

Can we add information to the docs when `count=0`?  It's unclear what happens in this case.
```

### Standalone code to reproduce the issue

```shell
n/a
```

### Relevant log output

```shell
n/a
```

**Comment by jamesbraza** [comment]
Okay let me make a better repro.

Here's how to get a dataset (from [Image classification from scratch](https://keras.io/examples/vision/image_classification_from_scratch/)).

```shell
curl -O https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_5340.zip
unzip kagglecatsanddogs_5340.zip
```

Then run this:

```python
import tensorflow as tf

train_ds = tf.keras.preprocessing.image_dataset_from_directory("PetImages")

flag = False
for images, labels in train_ds.repeat(0):
    flag = True
assert flag  # Fails
```

We can see that `.repeat(0)` will not enter the `for` loop.

In my opinion, the expected behavior for `.repeat(0)` would be to move through the `Dataset` once and then `StopIteration`, because we are repeating the dataset zero times.  However, `.repeat(0)` results in a zero-length iterable.

I think this should be documented: that if you want to move through the dataset once, don't use `.repeat(0)` instead use `.repeat(1)`.

Please let me know if this still doesn't make sense and I can add more details.

**Comment by sushreebarsa** [comment]
@jamesbraza Thank you for the update!
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!

**Comment by jamesbraza** [comment]
SEE: https://github.com/keras-team/keras/issues/16578
