### ISSUE TITLE
ImportError: /home/smartcane/anaconda3/lib/python3.9/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: PyCMethod_New

### ISSUE THREAD

**Issue by sureshnnayak** [tensorflow/tensorflow#56247]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

Ubuntu 20

### Python version

3.9

### Current Behaviour?

```shell
Error while running the code
```

### Standalone code to reproduce the issue

```shell
even though TensorFlow is installed and the location is added to PYTHONPATH it throws the below error
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/smartcane/anaconda3/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: /home/smartcane/anaconda3/lib/python3.9/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: PyCMethod_New

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/smartcane/Desktop/Hand_track/SKU110K_CVPR19/object_detector_retinanet/keras_retinanet/bin/predict.py", line 23, in <module>
    from tensorflow import keras
  File "/home/smartcane/anaconda3/lib/python3.9/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/smartcane/anaconda3/lib/python3.9/site-packages/tensorflow/python/__init__.py", line 36, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/home/smartcane/anaconda3/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow.py", line 77, in <module>
    raise ImportError(
ImportError: Traceback (most recent call last):
  File "/home/smartcane/anaconda3/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: /home/smartcane/anaconda3/lib/python3.9/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: PyCMethod_New
```
</details>

**Comment by gadagashwini** [comment]
Hi @sureshnnayak,
From the given information, it seems Tensorflow built from source but from the error, it looks like you are trying to import tensorflow from anaconda library. 
I would request you to create virtual environment and install Tensorflow `pip install tensorflow` and verify. Thank you!
