### ISSUE TITLE
tf.keras.initializers.TruncatedNormal is not available when using tf.keras.models.load_model

### ISSUE THREAD

**Issue by ptarasiewiczNV** [tensorflow/tensorflow#56245]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

tensorflow/tensorflow Docker image

### Current Behaviour?

```shell
When using `tf.keras.initializers.TruncatedNormal` in a custom model, the model can be saved, but fails to load.
Adding `custom_objects={"TruncatedNormal": tf.keras.initializers.TruncatedNormal})` to `tf.keras.models.load_model` prevents the error.
I expected that passing TF classes as custom objects would not be necessary.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

@tf.keras.utils.register_keras_serializable()
class MyModel(tf.keras.Model):
    def __init__(self, initializer):
        self._config = {"initializer": initializer}
        super().__init__(inputs=[], outputs=[])
        
    def get_config(self):
        return self._config
    
    @classmethod
    def from_config(cls, config, custom_objects=None):
        return cls(**config)
    
mymodel = MyModel(initializer=tf.keras.initializers.TruncatedNormal())
tf.keras.models.save_model(mymodel, "mymodel.sm", overwrite=True)
loaded_mymodel = tf.keras.models.load_model("mymodel.sm")
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "tfbug.py", line 18, in <module>
    loaded_mymodel = tf.keras.models.load_model("mymodel.sm")
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None    
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/training/tracking/base.py", line 587, in _method_wrapper 
    result = method(self, *args, **kwargs)    
TypeError: __init__() missing 2 required positional arguments: 'inputs' and 'outputs'
```
</details>

**Comment by tilakrayal** [comment]
Hi @ptarasiewiczNV,
Thanks for opening this issue. Development of keras moved to another [repository](https://github.com/keras-team/keras/issues). 
 
 
Could you please post this issue on keras-team/keras [repo](https://github.com/keras-team/keras/issues).
To know more please refer:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!

**Comment by ptarasiewiczNV** [comment]
Ok, thank you. keras-team/keras [issue ](https://github.com/keras-team/keras/issues/16581) for reference.

**Comment by tilakrayal** [comment]
@ptarasiewiczNV,
Could you feel free to move this issue to closed status, so that we can track the issue there. Thank you!

**Comment by ptarasiewiczNV** [comment]
Yes, of course.
