### ISSUE TITLE
Remove fake quant node

### ISSUE THREAD

**Issue by curioyang** [tensorflow/tensorflow#56256]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

binary

### Tensorflow Version

tf2.6

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu20.04

### Python version

3.8

### Current Behaviour?

```shell
I got a pb with fake quant nodes. I want to remove it. I just want to use the fp32 model. I found 'drop_fake_quant' flag was removed from TOCO.
What should i do?
```

### Standalone code to reproduce the issue

```shell
I tried use TOCO by tf1.13.1 but it can't work. Here is the log.
```

### Relevant log output

```shell
$ toco --graph_def_file=tflite_graph.pb --output_file=test.tflite --input_format=TENSORFLOW_GRAPHDEF   --output_format=TFLITE   --inference_type=FLOAT --input_shape=1,512,512,3 --input_array=normalized_input_image_tensor --output_arrays=convert_scores,Squeeze --drop_fake_quant
/home/curio/env/tf1/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/curio/env/tf1/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/curio/env/tf1/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/curio/env/tf1/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/curio/env/tf1/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/curio/env/tf1/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
2022-05-25 17:44:43.220138: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2022-05-25 17:44:43.242294: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3699850000 Hz
2022-05-25 17:44:43.242535: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x171d5d0 executing computations on platform Host. Devices:
2022-05-25 17:44:43.242550: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
Traceback (most recent call last):
  File "/home/curio/env/tf1/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 426, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef mentions attr 'explicit_paddings' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_BFLOAT16, DT_FLOAT, DT_DOUBLE]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]; attr=dilations:list(int),default=[1, 1, 1, 1]>; NodeDef: {{node FeatureExtractor/MobilenetV2/Conv/Conv2D_Fold}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/curio/env/tf1/bin/toco", line 8, in <module>
    sys.exit(main())
  File "/home/curio/env/tf1/lib/python3.6/site-packages/tensorflow/lite/python/tflite_convert.py", line 442, in main    app.run(main=run_main, argv=sys.argv[:1])
  File "/home/curio/env/tf1/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run        
    _sys.exit(main(argv))
  File "/home/curio/env/tf1/lib/python3.6/site-packages/tensorflow/lite/python/tflite_convert.py", line 438, in run_main
    _convert_model(tflite_flags)
  File "/home/curio/env/tf1/lib/python3.6/site-packages/tensorflow/lite/python/tflite_convert.py", line 122, in _convert_model
    converter = _get_toco_converter(flags)
  File "/home/curio/env/tf1/lib/python3.6/site-packages/tensorflow/lite/python/tflite_convert.py", line 109, in _get_toco_converter
    return converter_fn(**converter_kwargs)
  File "/home/curio/env/tf1/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 274, in from_frozen_graph
    _import_graph_def(graph_def, name="")
  File "/home/curio/env/tf1/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/curio/env/tf1/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 430, in import_graph_def
    raise ValueError(str(e))
ValueError: NodeDef mentions attr 'explicit_paddings' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_BFLOAT16, DT_FLOAT, DT_DOUBLE]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]; attr=dilations:list(int),default=[1, 1, 1, 1]>; NodeDef: {{node FeatureExtractor/MobilenetV2/Conv/Conv2D_Fold}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
```
</details>

**Comment by mohantym** [comment]
Hi @curioyang ! Toco converter has been depreciated in 2.x versions. Could you let us know after trying the below command  with python 3.7/3.8 and TF 2.8 . Attached relevant [thread](https://www.tensorflow.org/api_docs/python/tf/compat/v1/lite/TFLiteConverter) for reference .Thank you!

`tf.compat.v1.lite.TFLiteConverter.from_frozen_graph()  `

**Comment by curioyang** [comment]
@mohantym It will create many quant nodes such as 
![image](https://user-images.githubusercontent.com/39184746/170387183-cc1801a3-99a8-45cb-bdcd-bed44e0cd99b.png)
Conv2D and DepthwiseConv2D are fp32 nodes with fp32 input and output. I just want to remove these "Quantize & Dequantize"

**Comment by mohantym** [comment]
@curioyang ! Could you share the code snippet for the saved model. Thank you!

**Comment by mohantym** [comment]
@curioyang ! Could you share the code snippet for the saved model. Thank you!
