### ISSUE TITLE
converter.convert() to a tflite file sucessfully, but interpreter.invoke() raise RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 5 (FlexSize) failed to prepare.

### ISSUE THREAD

**Issue by fjzhangcr** [tensorflow/tensorflow#56253]
### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.3

### Custom Code

Yes

### OS Platform and Distribution

windows 10

### Python version

3.7

### Current Behaviour?

```shell
A bug happened!
i have a model contains codes like this:
    grid_size = tf.shape(conv_output)[1:3] # shape=(13,13)
    x_grid,y_grid = tf.meshgrid(tf.range(grid_size[1]), tf.range(grid_size[0]))  # shape=(13,13)
i can generate tflite file sucessfully
but when i open this tflite file, and use interpreter.invoke(), the runtime error occurs:

  File "D:\Anaconda3\envs\CV_TF23_py37\lib\site-packages\tensorflow\lite\python\interpreter.py", line 524, in invoke
    self._interpreter.Invoke()

RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 5 (FlexSize) failed to prepare.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np
class CFGGG:
    SAVED_MODEL_DIR='./zz_tflite_op_support/demo'
    TFLITE_MODEL_FILENAME='./zz_tflite_op_support/demo.tflite'

inputs=tf.keras.layers.Input((5,5,2))
def pre_process(x):
    grid_x,grid_y=tf.shape(x)[1:3]
    # range_x=tf.range(5) # when replace 5 with grid_x，runtime error occurs when invoke
    # range_y=tf.range(5) # when replace 5 with grid_y，runtime error occurs when invoke
    range_x=tf.range(grid_x) 
    range_y=tf.range(grid_y) 
    x_grid,y_grid=tf.meshgrid(range_y,range_x)
    
    b=tf.stack([y_grid,x_grid],axis=-1)
    b=tf.cast(b,tf.float32)
    y=x+b
    return y
    
x=pre_process(inputs)
outputs=tf.keras.layers.Dense(10)(x)

model_debug=tf.keras.Model(inputs=inputs,outputs=x)
model_debug.summary()


model_debug.save(CFGGG.SAVED_MODEL_DIR)

converter = tf.lite.TFLiteConverter.from_saved_model(CFGGG.SAVED_MODEL_DIR)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_types = [tf.compat.v1.lite.constants.FLOAT16]
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS,
    tf.lite.OpsSet.SELECT_TF_OPS]
converter.allow_custom_ops = True


tflite_model = converter.convert()

with open(CFGGG.TFLITE_MODEL_FILENAME, 'wb') as f:
    f.write(tflite_model)
    
interpreter = tf.lite.Interpreter(model_path=CFGGG.TFLITE_MODEL_FILENAME)
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Explore the model input output shape.
print(input_details)
print(output_details)

input_shape = input_details[0]['shape']
print("input shape",input_shape)
for i, output_detail in enumerate(output_details):
    output_shape = output_detail['shape']
    print("No {} output shape {}".format(i,output_shape))


# Test the model on random input data.
input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
interpreter.set_tensor(input_details[0]['index'], input_data)
print("input data complete: ",input_data.shape)
interpreter.invoke()
# The function `get_tensor()` returns a copy of the tensor data.
# Use `tensor()` in order to get a pointer to the tensor.
for i in range(len(output_details)):
    output_data_tmp = interpreter.get_tensor(output_details[i]['index'])
    output_shape_tmp = output_data_tmp.shape
    print("invoke() complete，No {} output shape {}".format(i,output_shape_tmp))
```

### Relevant log output

```shell
INFO:tensorflow:Assets written to: ./zz_tflite_op_support/demo\assets
INFO:tensorflow:Assets written to: ./zz_tflite_op_support/demo\assets
[{'name': 'input_27', 'index': 0, 'shape': array([1, 5, 5, 2]), 'shape_signature': array([-1,  5,  5,  2]), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
[{'name': 'Identity', 'index': 25, 'shape': array([1, 5, 5, 2]), 'shape_signature': array([-1,  5,  5,  2]), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
input shape [1 5 5 2]
No 0 output shape [1 5 5 2]
intpu data complete: (1, 5, 5, 2)

Traceback (most recent call last):

  File "D:\OneDrive\AI_Working_Directory\prj_quickstart\zzz_debug_tflite_op_support.py", line 103, in <module>
    interpreter.invoke()

  File "D:\Anaconda3\envs\CV_TF23_py37\lib\site-packages\tensorflow\lite\python\interpreter.py", line 524, in invoke
    self._interpreter.Invoke()

RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 5 (FlexSize) failed to prepare.
```

**Comment by fjzhangcr** [comment]
let me update this bug:
there are 3 funciton involved here: tf.shape, tf.range, tf.meshgrid.
3 components have  7 combinations: C31+C32+C33=3+3+3+1

- shape，ok；
- range，ok，
- meshgrid，ok
- shape+range, OK
- shape+meshgrid，no need~
- range+meshgrid，ok
- shape+range+meshgrid , **BUG APPEAR!**

just switch the function inside the  function-defined model to verified~~

hope this can help~~

```
import tensorflow as tf
import numpy as np
class CFGGG:
    SAVED_MODEL_DIR='./zz_tflite_op_support/demo'
    TFLITE_MODEL_FILENAME='./zz_tflite_op_support/demo.tflite'

inputs=tf.keras.layers.Input((5,5,2))
def pre_process_shows_shape_OK(x):
    grid_x,grid_y=tf.shape(x)[1:3]
    x_grid=tf.ones([grid_x,grid_y])
    y_grid=tf.ones([grid_x,grid_y])
    b=tf.stack([x_grid,y_grid],axis=-1)
    y=x+tf.cast(b,tf.float32)
    return y
def pre_process_shows_range_meshgrid_OK(x):
    range_x=tf.range(5) # 替换为grid_x，tflite在invoke的时候就出错
    range_y=tf.range(5) # 替换为grid_y，tflite在invoke的时候就出错
    x_grid,y_grid=tf.meshgrid(range_y,range_x)
    
    b=tf.stack([y_grid,x_grid],axis=-1)
    b=tf.cast(b,tf.float32)
    y=x+b
    return y
def pre_process_shows_shape_range_meshgrid_BUG(x):
    grid_x,grid_y=tf.shape(x)[1:3]
    grid_x=tf.shape(x)[1]
    grid_y=tf.shape(x)[2]
    range_x=tf.range(grid_x) # 替换为grid_x，tflite在invoke的时候就出错
    range_y=tf.range(grid_y) # 替换为grid_y，tflite在invoke的时候就出错
    x_grid,y_grid=tf.meshgrid(range_y,range_x)
    
    b=tf.stack([y_grid,x_grid],axis=-1)
    b=tf.cast(b,tf.float32)
    y=x+b
    return y
def pre_process_shows_shape_range_OK(x):
    grid_x=tf.shape(x)[1]
    grid_y=tf.shape(x)[2]
    range_x=tf.range(grid_x) # 替换为grid_x，tflite在invoke的时候就出错
    range_y=tf.range(grid_y) # 替换为grid_y，tflite在invoke的时候就出错
    b=tf.stack([range_x,range_y],axis=-1)
    return b

# x=pre_process_shows_shape_OK(inputs)
# x=pre_process_shows_range_meshgrid_OK(inputs)
# x=pre_process_shows_shape_range_OK(inputs)
x=pre_process_shows_shape_range_meshgrid_BUG(inputs)

outputs=tf.keras.layers.Dense(10)(x)

model_debug=tf.keras.Model(inputs=inputs,outputs=x)
model_debug.summary()

model_debug.save(CFGGG.SAVED_MODEL_DIR)

# then conver to tflite, then read tflite, then  interpreter.invoke()
converter = tf.lite.TFLiteConverter.from_saved_model(CFGGG.SAVED_MODEL_DIR)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_types = [tf.compat.v1.lite.constants.FLOAT16]
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS,
    tf.lite.OpsSet.SELECT_TF_OPS]
converter.allow_custom_ops = True


tflite_model = converter.convert()

with open(CFGGG.TFLITE_MODEL_FILENAME, 'wb') as f:
    f.write(tflite_model)
    
interpreter = tf.lite.Interpreter(model_path=CFGGG.TFLITE_MODEL_FILENAME)
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Explore the model input output shape.
print(input_details)
print(output_details)

input_shape = input_details[0]['shape']
print("input shape",input_shape)
for i, output_detail in enumerate(output_details):
    output_shape = output_detail['shape']
    print("No {} output shape {}".format(i,output_shape))


# Test the model on random input data.
input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
interpreter.set_tensor(input_details[0]['index'], input_data)
print("input data complete: ",input_data.shape)
interpreter.invoke()
# The function `get_tensor()` returns a copy of the tensor data.
# Use `tensor()` in order to get a pointer to the tensor.
for i in range(len(output_details)):
    output_data_tmp = interpreter.get_tensor(output_details[i]['index'])
    output_shape_tmp = output_data_tmp.shape
    print("invoke() complete，No {} output shape {}".format(i,output_shape_tmp))
```

**Comment by mohantym** [comment]
Hi @fjzhangcr ! Could you try with below converter code snippet in the 2.8 version and let us know. Thank you!
```
converter = tf.lite.TFLiteConverter.from_saved_model(CFGGG.SAVED_MODEL_DIR)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_types = [tf.lite.float16]
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS,
    tf.lite.OpsSet.SELECT_TF_OPS]
converter.experimental new_converter = True
#converter.allow_custom_ops = True .To use [custom ops](https://www.tensorflow.org/lite/guide/ops_custom) you need to register those in lite kernel
```

**Comment by mohantym** [comment]
Hi @fjzhangcr ! Thanks for the update. [experimental_new_converter ](https://www.tensorflow.org/api_docs/python/tf/lite/TFLiteConverter#:~:text=experimental_new_converter)has been added recently to enable MLIR based conversion. Similarly experimental_new_quantizer for MLIR-based quantization ,experimental_enable_resource_variables to enable resource variables are available during conversion .

Please move this issue to closed status if it has been resolved. Thank you!

**Comment by fjzhangcr** [comment]
applogy for my delay, i have check the interpreter invoke() is ok indeed~~~but when i edgetpu-compiler the tflite file~~

`edgetpu_compiler  yolov4.tflite`

it shows

```
Edge TPU Compiler version 16.0.384591198
Started a compilation timeout timer of 180 seconds.
ERROR: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.
Compilation failed: Model failed in Tflite interpreter. Please ensure model can be loaded/run in Tflite interpreter.
Compilation child process completed within timeout period.
Compilation failed!
```

does it mean that even interpreter invoke runs well, the edge-tpu hardware may encounter other problem? like graph with  dynamic-sized tensors~~
