### ISSUE TITLE
convert to TF-Lite ValueError: Cannot iterate over a shape with unknown rank

### ISSUE THREAD

**Issue by FengMu1995** [tensorflow/tensorflow#56252]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf2.3.1

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 18.04

### Python version

3.6

### Current Behaviour?

```shell
when I convert the savedmodel to tflite model, error happens

ValueError: Cannot iterate over a shape with unknown rank.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_saved_model('model') 
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS,
    tf.lite.OpsSet.SELECT_TF_OPS
    ]
tflite_model = converter.convert()
with open('rvm.tflite', 'wb') as f:
     f.write(tflite_model)
```

### Relevant log output

```shell
2022-05-25 12:59:38.001545: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2022-05-25 12:59:38.001571: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-05-25 12:59:39.165540: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-05-25 12:59:39.165560: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2022-05-25 12:59:39.165578: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (wudi-QiTianM620-N000): /proc/driver/nvidia/version does not exist
2022-05-25 12:59:39.165701: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-05-25 12:59:39.190199: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2899885000 Hz
2022-05-25 12:59:39.190662: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55dc4ea19680 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2022-05-25 12:59:39.190693: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2022-05-25 12:59:46.493553: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-05-25 12:59:46.493624: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2022-05-25 12:59:46.608109: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816] Optimization results for grappler item: graph_to_optimize
2022-05-25 12:59:46.608136: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:818]   function_optimizer: Graph size after: 2419 nodes (2082), 6014 edges (5672), time = 50.604ms.
2022-05-25 12:59:46.608141: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:818]   function_optimizer: Graph size after: 2419 nodes (0), 6014 edges (0), time = 26.182ms.
2022-05-25 12:59:46.608144: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816] Optimization results for grappler item: __inference_cond_1_true_10408_9212
2022-05-25 12:59:46.608147: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:818]   function_optimizer: function_optimizer did nothing. time = 0.001ms.
2022-05-25 12:59:46.608150: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:818]   function_optimizer: function_optimizer did nothing. time = 0ms.
2022-05-25 12:59:46.608153: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816] Optimization results for grappler item: __inference_cond_true_8440_26709
2022-05-25 12:59:46.608156: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:818]   function_optimizer: function_optimizer did nothing. time = 0ms.
2022-05-25 12:59:46.608158: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:818]   function_optimizer: function_optimizer did nothing. time = 0ms.
2022-05-25 12:59:46.608161: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816] Optimization results for grappler item: __inference_cond_false_8441_36559
2022-05-25 12:59:46.608164: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:818]   function_optimizer: function_optimizer did nothing. time = 0.001ms.
2022-05-25 12:59:46.608167: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:818]   function_optimizer: function_optimizer did nothing. time = 0ms.
2022-05-25 12:59:46.608170: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816] Optimization results for grappler item: __inference_cond_1_false_10409_21697
2022-05-25 12:59:46.608173: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:818]   function_optimizer: function_optimizer did nothing. time = 0.001ms.
2022-05-25 12:59:46.608176: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:818]   function_optimizer: function_optimizer did nothing. time = 0ms.
Traceback (most recent call last):
  File "/home/wudi/project/project_rvm/Matting(tensorflow)/convert1.py", line 11, in <module>
    tflite_model = converter.convert()
  File "/home/wudi/Software/yes/envs/onnx2tf/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 1076, in convert
    return super(TFLiteConverterV2, self).convert()
  File "/home/wudi/Software/yes/envs/onnx2tf/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 900, in convert
    self).convert(graph_def, input_tensors, output_tensors)
  File "/home/wudi/Software/yes/envs/onnx2tf/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 633, in convert
    **converter_kwargs)
  File "/home/wudi/Software/yes/envs/onnx2tf/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 567, in toco_convert_impl
    input_tensors, output_tensors, *args, **kwargs)
  File "/home/wudi/Software/yes/envs/onnx2tf/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 458, in build_toco_convert_protos
    for dim in shape:
  File "/home/wudi/Software/yes/envs/onnx2tf/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 859, in __iter__
    raise ValueError("Cannot iterate over a shape with unknown rank.")
ValueError: Cannot iterate over a shape with unknown rank.
```
</details>

**Comment by mohantym** [comment]
Hi @FengMu1995 ! I see that you are using Python 3.6 which is not supported anymore. Could you let us know after testing with TF 2.8 and Python 3.7/3.8 .It would be great to have the code snippet for saved model too. Thank you!

**Comment by FengMu1995** [comment]
@mohantym I have just solved the issue as your advice to upgrade the python and tensorflow version.
Thank you very much.

**Comment by mohantym** [comment]
@FengMu1995 ! Thanks for the confirmation. Could we move this issue to closed status then?

**Comment by FengMu1995** [comment]
it's fine

**Comment by FengMu1995** [comment]
OK

**Comment by FengMu1995** [comment]
of cource

**Comment by mohantym** [comment]
@FengMu1995! Thanks for the confirmation. Moving this issue to closed status then.
