### ISSUE TITLE
Extract some of the weights in the saved model and assign them to another

### ISSUE THREAD

**Issue by Coding-Zuo** [tensorflow/tensorflow#56297]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

2.5

### Custom Code

Yes

### Current Behaviour?

```shell
How to extract the weights of part of the specified network from the saved model, and assign the extracted weights to another saved model with the same structure.

Also, the point is, how to write the extracted weight into the [variables.data-00000-of-00001] and [variables.index] files.

Thank you very much.
```

### Standalone code to reproduce the issue

```shell
model_1 = tf.keras.models.load_model(model_dir1, compile=False)

for layer in model_1.layers:
    print(layer.name)
    layer.set_weights([weight, bias])
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
Hi @Coding-Zuo,
In order to reproduce the issue reported here, could you provide the complete code and the dataset or colab link you are using. Thank you!

**Comment by Coding-Zuo** [comment]
`model_1 = tf.keras.models.load_model(model_dir1, compile=False)
model_1.save(output_dir, save_format='tf')
model = tf.keras.models.load_model(output_dir, compile=False)`

I load the savedmodel model and store it directly. If the model is saved in this way, it will not report an error.
However, an error is reported when loading our output model:

`Traceback (most recent call last):
  File "/home/yuhui.zuo/bert-nlu-test/ckpt1.py", line 159, in <module>
    model = tf.keras.models.load_model(output_dir, compile=False)
  File "/home/yuhui.zuo/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 206, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "/home/yuhui.zuo/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 146, in load
    keras_loader.load_layers(compile=compile)
  File "/home/yuhui.zuo/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 378, in load_layers
    self.loaded_nodes[node_metadata.node_id] = self._load_layer(
  File "/home/yuhui.zuo/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 420, in _load_layer
    obj, setter = self._revive_from_config(identifier, metadata, node_id)
  File "/home/yuhui.zuo/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 438, in _revive_from_config
    self._revive_layer_or_model_from_config(metadata, node_id))
  File "/home/yuhui.zuo/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 526, in _revive_layer_or_model_from_config
    obj._set_dtype_policy(metadata['dtype'])
AttributeError: 'Zeros' object has no attribute '_set_dtype_policy'`

**Comment by tilakrayal** [comment]
@Coding-Zuo,
Thanks for opening this issue. Development of keras moved to another [repository](https://github.com/keras-team/keras/issues). 
 
 
Could you please post this issue on keras-team/keras [repo](https://github.com/keras-team/keras/issues).
To know more please refer:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!
