### ISSUE TITLE
Fails to import tensorflow

### ISSUE THREAD

**Issue by mangelozzi** [tensorflow/tensorflow#56308]
### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

Ubuntu 20.04

### Python version

3.9

### Current Behaviour?

```shell
When try to import it has a circular import error.
```

### Standalone code to reproduce the issue

```shell
$ python
Python 3.9.13 (main, May 23 2022, 22:01:06) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2022-05-31 12:09:07.100479: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-05-31 12:09:07.100505: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/michael/.venv/ml/lib/python3.9/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/michael/.venv/ml/lib/python3.9/site-packages/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "/home/michael/.venv/ml/lib/python3.9/site-packages/tensorflow/python/eager/context.py", line 25, in <module>
    from absl import logging
  File "/home/michael/.venv/ml/lib/python3.9/site-packages/absl/logging/__init__.py", line 88, in <module>
    import timeit
  File "/home/michael/timeit.py", line 1, in <module>
    from timeit import timeit
ImportError: cannot import name 'timeit' from partially initialized module 'timeit' (most likely due to a circular import) (/home/michael/timeit.py)
>>>
```

### Relevant log output

```shell
See above
```

**Comment by mangelozzi** [comment]
I just so happened to have a file called "timeit.py" in the same dir as when I started the python repl
