### ISSUE TITLE
tensorflow.lite.python.convert_phase.ConverterError: device assign error

### ISSUE THREAD

**Issue by jyh2378** [tensorflow/tensorflow#56307]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

v2.9.0-rc2-42-g8a20d54a3c1 2.9.0

### Custom Code

No

### OS Platform and Distribution

Linux CentOS 7

### Python version

3.9.13

### CUDA/cuDNN version

11.2 / 8.1.1

### Current Behaviour?

```shell
I tried to convert the tf saved_mode(.pb) to tflite model. my computer can use gpu device, but I have error that some operation cannot assigned to gpu device. How can I fix it?
```

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/1kDOUXMha543jKJxMl0w4CEExx7G461Q6?usp=sharing
```

### Relevant log output

```shell
2022-05-31 17:55:48.396106: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-05-31 17:55:54.142361: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 30983 MB memory:  -> device: 0, name: Tesla V100-SXM2-32GB, pci bus id: 0000:15:00.0, compute capability: 7.0
2022-05-31 17:55:54.144955: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 30983 MB memory:  -> device: 1, name: Tesla V100-SXM2-32GB, pci bus id: 0000:16:00.0, compute capability: 7.0
2022-05-31 17:55:54.147135: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:2 with 30983 MB memory:  -> device: 2, name: Tesla V100-SXM2-32GB, pci bus id: 0000:3a:00.0, compute capability: 7.0
2022-05-31 17:55:54.149256: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:3 with 30983 MB memory:  -> device: 3, name: Tesla V100-SXM2-32GB, pci bus id: 0000:3b:00.0, compute capability: 7.0
2022-05-31 17:55:54.151379: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:4 with 30983 MB memory:  -> device: 4, name: Tesla V100-SXM2-32GB, pci bus id: 0000:89:00.0, compute capability: 7.0
2022-05-31 17:55:54.153498: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:5 with 30983 MB memory:  -> device: 5, name: Tesla V100-SXM2-32GB, pci bus id: 0000:8a:00.0, compute capability: 7.0
2022-05-31 17:55:54.155614: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:6 with 30983 MB memory:  -> device: 6, name: Tesla V100-SXM2-32GB, pci bus id: 0000:b2:00.0, compute capability: 7.0
2022-05-31 17:55:54.157735: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:7 with 30983 MB memory:  -> device: 7, name: Tesla V100-SXM2-32GB, pci bus id: 0000:b3:00.0, compute capability: 7.0
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'pwcnet/featpyr/conv1a/kernel:0' shape=(3, 3, 3, 16) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'pwcnet/featpyr/conv1a/bias:0' shape=(16,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'pwcnet/featpyr/conv1aa/kernel:0' shape=(3, 3, 16, 16) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'pwcnet/featpyr/conv1aa/bias:0' shape=(16,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'pwcnet/featpyr/conv1b/kernel:0' shape=(3, 3, 16, 16) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'pwcnet/featpyr/conv1a/kernel:0' shape=(3, 3, 3, 16) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'pwcnet/featpyr/conv1a/bias:0' shape=(16,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'pwcnet/featpyr/conv1aa/kernel:0' shape=(3, 3, 16, 16) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'pwcnet/featpyr/conv1aa/bias:0' shape=(16,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'pwcnet/featpyr/conv1b/kernel:0' shape=(3, 3, 16, 16) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'pwcnet/featpyr/conv1a/kernel:0' shape=(3, 3, 3, 16) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'pwcnet/featpyr/conv1a/bias:0' shape=(16,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'pwcnet/featpyr/conv1aa/kernel:0' shape=(3, 3, 16, 16) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'pwcnet/featpyr/conv1aa/bias:0' shape=(16,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'pwcnet/featpyr/conv1b/kernel:0' shape=(3, 3, 16, 16) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'pwcnet/featpyr/conv1a/kernel:0' shape=(3, 3, 3, 16) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'pwcnet/featpyr/conv1a/bias:0' shape=(16,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'pwcnet/featpyr/conv1aa/kernel:0' shape=(3, 3, 16, 16) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'pwcnet/featpyr/conv1aa/bias:0' shape=(16,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'pwcnet/featpyr/conv1b/kernel:0' shape=(3, 3, 16, 16) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
2022-05-31 17:56:01.538586: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:362] Ignored output_format.
2022-05-31 17:56:01.538654: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:365] Ignored drop_control_dependency.
2022-05-31 17:56:01.539779: I tensorflow/cc/saved_model/reader.cc:43] Reading SavedModel from: ./models/saved_model
2022-05-31 17:56:01.562091: I tensorflow/cc/saved_model/reader.cc:81] Reading meta graph with tags { serve }
2022-05-31 17:56:01.562154: I tensorflow/cc/saved_model/reader.cc:122] Reading SavedModel debug info (if present) from: ./models/saved_model
2022-05-31 17:56:01.640074: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:354] MLIR V1 optimization pass is not enabled
2022-05-31 17:56:01.711920: I tensorflow/cc/saved_model/loader.cc:301] SavedModel load for tags { serve }; Status: fail: INVALID_ARGUMENT: Cannot assign a device for operation pwcnet/featpyr/strided_slice: {{node pwcnet/featpyr/strided_slice}} was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
         [[pwcnet/featpyr/strided_slice]]. Took 172109 microseconds.
2022-05-31 17:56:01.712003: E tensorflow/compiler/mlir/tensorflow/translate/tf_mlir_translate.cc:199] Failed to load saved model v1 './models/saved_model': INVALID_ARGUMENT: Cannot assign a device for operation pwcnet/featpyr/strided_slice: {{node pwcnet/featpyr/strided_slice}} was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
         [[pwcnet/featpyr/strided_slice]]
Traceback (most recent call last):
  File "/home1/irteam/users/yeonghwa.jin/tfoptflow/tfoptflow/export_tflite.py", line 51, in <module>
    export_tflite(saved_model_dir)
  File "/home1/irteam/users/yeonghwa.jin/tfoptflow/tfoptflow/export_tflite.py", line 42, in export_tflite
    tflite_model = converter.convert()
  File "/home1/irteam/.pyenv/versions/tf2.9.0_cuda11.2_cudnn8.1.1/lib/python3.9/site-packages/tensorflow/lite/python/lite.py", line 929, in wrapper
    return self._convert_and_export_metrics(convert_func, *args, **kwargs)
  File "/home1/irteam/.pyenv/versions/tf2.9.0_cuda11.2_cudnn8.1.1/lib/python3.9/site-packages/tensorflow/lite/python/lite.py", line 908, in _convert_and_export_metrics
    result = convert_func(self, *args, **kwargs)
  File "/home1/irteam/.pyenv/versions/tf2.9.0_cuda11.2_cudnn8.1.1/lib/python3.9/site-packages/tensorflow/lite/python/lite.py", line 1212, in convert
    return self._convert_from_saved_model(graph_def)
  File "/home1/irteam/.pyenv/versions/tf2.9.0_cuda11.2_cudnn8.1.1/lib/python3.9/site-packages/tensorflow/lite/python/lite.py", line 1095, in _convert_from_saved_model
    result = _convert_saved_model(**converter_kwargs)
  File "/home1/irteam/.pyenv/versions/tf2.9.0_cuda11.2_cudnn8.1.1/lib/python3.9/site-packages/tensorflow/lite/python/convert_phase.py", line 212, in wrapper
    raise converter_error from None  # Re-throws the exception.
  File "/home1/irteam/.pyenv/versions/tf2.9.0_cuda11.2_cudnn8.1.1/lib/python3.9/site-packages/tensorflow/lite/python/convert_phase.py", line 205, in wrapper
    return func(*args, **kwargs)
  File "/home1/irteam/.pyenv/versions/tf2.9.0_cuda11.2_cudnn8.1.1/lib/python3.9/site-packages/tensorflow/lite/python/convert.py", line 809, in convert_saved_model
    data = convert(
  File "/home1/irteam/.pyenv/versions/tf2.9.0_cuda11.2_cudnn8.1.1/lib/python3.9/site-packages/tensorflow/lite/python/convert.py", line 311, in convert
    raise converter_error
tensorflow.lite.python.convert_phase.ConverterError: Cannot assign a device for operation pwcnet/featpyr/strided_slice: {{node pwcnet/featpyr/strided_slice}} was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
         [[pwcnet/featpyr/strided_slice]]
```
</details>

**Comment by jyh2378** [comment]
saved_model is created from this repo: https://github.com/philferriere/tfoptflow
saved_model file: https://drive.google.com/file/d/1X0NA8VIALBtfoZOulq1HL90qXG6LrcEx/view?usp=sharing

**Comment by mohantym** [comment]
Hi @jyh2378 ! Thanks for reporting this bug. @sachinprasadhs ! Could you please look at this issue. Attached [2.8](https://colab.sandbox.google.com/gist/mohantym/da720a0afb0733088fe8d78659a78a7b/export_tflite.ipynb#scrollTo=thLdaUuudNas),[ 2.9](https://colab.sandbox.google.com/gist/mohantym/121ad16e654ae29b569252c27ca96460/export_tflite.ipynb#scrollTo=w-azc4YleXDM) and [nightly ](https://colab.sandbox.google.com/gist/mohantym/621a0d52b3b5f17faf878f71229965b3/export_tflite.ipynb#scrollTo=UIRdQ8_R_NK-)gist for reference. Thank you!

**Comment by sachinprasadhs** [comment]
If the OP is not registered for GPU or if that cannot be used in GPU, it gives `ConverterError`. 
Instead of explicit device placement, can you make it fallback to default device. 
After following above steps, if you still face the same error uncomment the below part in your code.
```
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
```
which allows the ops to fallback to select Tf ops when builtin op fails.

**Comment by jyh2378** [comment]
@sachinprasadhs Thank you. It really helped me a lot.
