### ISSUE TITLE
Unit test atrous_conv2d_test is flaky with oneDNN on AARCH64

### ISSUE THREAD

**Issue by elfringham** [tensorflow/tensorflow#56320]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

git HEAD

### Custom Code

No

### OS Platform and Distribution

CentOS 7

### Mobile device

n/a

### Python version

3.8.13

### Bazel version

5.1.1

### GCC/Compiler version

10.2.1

### CUDA/cuDNN version

n/a

### GPU model and memory

n/a

### Current Behaviour?

```shell
The unit test is flaky and sometimes that is enough to fail the test even with the retries.
```

### Standalone code to reproduce the issue

```shell
bazel test --test_timeout=300,500,-1,-1 --flaky_test_attempts=3 --test_output=all --cache_test_results=no --jobs=75 --config=nonccl --config=mkl_aarch64 --copt=-fopenmp --linkopt=-lgomp --copt=-mtune=generic --copt=-march=armv8-a --copt=-O3 --verbose_failures --test_env=TF_ENABLE_ONEDNN_OPTS=1 --build_tag_filters=-no_oss,-oss_serial,-gpu,-tpu,-benchmark-test,-v1only,-no_aarch64,-requires-gpu --test_tag_filters=-no_oss,-oss_serial,-gpu,-tpu,-benchmark-test,-v1only,-no_aarch64,-requires-gpu --build_tests_only -- //tensorflow/python/kernel_tests/nn_ops:atrous_conv2d_test_cpu
```

### Relevant log output

```shell
INFO: From Testing //tensorflow/python/kernel_tests/nn_ops:atrous_conv2d_test_cpu (shard 1 of 2):
==================== Test output for //tensorflow/python/kernel_tests/nn_ops:atrous_conv2d_test_cpu (shard 1 of 2):
2022-06-01 09:32:57.698421: I tensorflow/core/util/util.cc:175] Experimental oneDNN custom operations are on. If you experience issues, please turn them off by setting the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
WARNING:tensorflow:Please fix your imports. Module tensorflow.python.training.tracking.base has been moved to tensorflow.python.trackable.base. The old module will be deleted in version 2.11.
WARNING:tensorflow:Please fix your imports. Module tensorflow.python.training.checkpoint_management has been moved to tensorflow.python.checkpoint.checkpoint_management. The old module will be deleted in version 2.9.
WARNING:tensorflow:Please fix your imports. Module tensorflow.python.training.tracking.resource has been moved to tensorflow.python.trackable.resource. The old module will be deleted in version 2.11.
Running tests under Python 3.8.13: /tmp/workspace/venv-cp38-cp38/bin/python3
[ RUN      ] AtrousConv2DTest.testAtrousConv2DForward
2022-06-01 09:32:58.982617: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:354] MLIR V1 optimization pass is not enabled
INFO:tensorflow:time(__main__.AtrousConv2DTest.testAtrousConv2DForward): 5.91s
I0601 09:33:04.815157 281473122258016 test_util.py:2458] time(__main__.AtrousConv2DTest.testAtrousConv2DForward): 5.91s
[       OK ] AtrousConv2DTest.testAtrousConv2DForward
[ RUN      ] AtrousConv2DTest.testGradient
WARNING:tensorflow:From /root/.cache/bazel/_bazel_root/7043a081cadd05f91bd91c35f2a2c120/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/python/kernel_tests/nn_ops/atrous_conv2d_test_cpu.runfiles/org_tensorflow/tensorflow/python/kernel_tests/nn_ops/atrous_conv2d_test.py:153: compute_gradient_error (from tensorflow.python.ops.gradient_checker) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.test.compute_gradient in 2.0, which has better support for functions. Note that the two versions have different usage, so code change is needed.
W0601 09:33:04.821886 281473122258016 deprecation.py:350] From /root/.cache/bazel/_bazel_root/7043a081cadd05f91bd91c35f2a2c120/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/python/kernel_tests/nn_ops/atrous_conv2d_test_cpu.runfiles/org_tensorflow/tensorflow/python/kernel_tests/nn_ops/atrous_conv2d_test.py:153: compute_gradient_error (from tensorflow.python.ops.gradient_checker) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.test.compute_gradient in 2.0, which has better support for functions. Note that the two versions have different usage, so code change is needed.
WARNING:tensorflow:From /root/.cache/bazel/_bazel_root/7043a081cadd05f91bd91c35f2a2c120/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/python/kernel_tests/nn_ops/atrous_conv2d_test_cpu.runfiles/org_tensorflow/tensorflow/python/ops/gradient_checker.py:390: compute_gradient (from tensorflow.python.ops.gradient_checker) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.test.compute_gradient in 2.0, which has better support for functions. Note that the two versions have different usage, so code change is needed.
W0601 09:33:04.822114 281473122258016 deprecation.py:350] From /root/.cache/bazel/_bazel_root/7043a081cadd05f91bd91c35f2a2c120/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/python/kernel_tests/nn_ops/atrous_conv2d_test_cpu.runfiles/org_tensorflow/tensorflow/python/ops/gradient_checker.py:390: compute_gradient (from tensorflow.python.ops.gradient_checker) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.test.compute_gradient in 2.0, which has better support for functions. Note that the two versions have different usage, so code change is needed.
INFO:tensorflow:time(__main__.AtrousConv2DTest.testGradient): 0.74s
I0601 09:33:05.552801 281473122258016 test_util.py:2458] time(__main__.AtrousConv2DTest.testGradient): 0.74s
[  FAILED  ] AtrousConv2DTest.testGradient
[ RUN      ] AtrousConv2DTransposeTest.testAtrousConv2DTransposeForward
INFO:tensorflow:time(__main__.AtrousConv2DTransposeTest.testAtrousConv2DTransposeForward): 5.66s
I0601 09:33:11.212162 281473122258016 test_util.py:2458] time(__main__.AtrousConv2DTransposeTest.testAtrousConv2DTransposeForward): 5.66s
[       OK ] AtrousConv2DTransposeTest.testAtrousConv2DTransposeForward
[ RUN      ] AtrousDepthwiseConv2DTest.testAtrousDepthwiseConv2DForward
INFO:tensorflow:time(__main__.AtrousDepthwiseConv2DTest.testAtrousDepthwiseConv2DForward): 6.57s
I0601 09:33:17.780310 281473122258016 test_util.py:2458] time(__main__.AtrousDepthwiseConv2DTest.testAtrousDepthwiseConv2DForward): 6.57s
[       OK ] AtrousDepthwiseConv2DTest.testAtrousDepthwiseConv2DForward
======================================================================
FAIL: testGradient (__main__.AtrousConv2DTest)
AtrousConv2DTest.testGradient
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/7043a081cadd05f91bd91c35f2a2c120/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/python/kernel_tests/nn_ops/atrous_conv2d_test_cpu.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 1625, in decorated
    return f(self, *args, **kwargs)
  File "/root/.cache/bazel/_bazel_root/7043a081cadd05f91bd91c35f2a2c120/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/python/kernel_tests/nn_ops/atrous_conv2d_test_cpu.runfiles/org_tensorflow/tensorflow/python/kernel_tests/nn_ops/atrous_conv2d_test.py", line 158, in testGradient
    self.assertLess(err, err_tolerance)
AssertionError: 0.9331526160240173 not less than 0.001

----------------------------------------------------------------------
Ran 4 tests in 18.879s

FAILED (failures=1)
atrous_conv2d gradient err = 0.933153 
================================================================================
```
</details>

**Comment by elfringham** [comment]
@cfRod @nSircombe
