### ISSUE TITLE
ZeroDivisionError on GradientTape.gradient when computing a loss from concatting scalar values

### ISSUE THREAD

**Issue by str4si** [tensorflow/tensorflow#56335]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.8.0

### Custom Code

Yes

### OS Platform and Distribution

18.04.1-Ubuntu

### Python version

3.8.10

### Bazel version

-

### GCC/Compiler version

-

### CUDA/cuDNN version

cuda11.3/cudnn8.2.1

### GPU model and memory

Tesla V100

### Current Behaviour?

```shell
a ZeroDivisionError on GradientTape.gradient when computing a loss from concatting scalar values using for example loss=tf.math.reduce_mean(tf.concat([self.trainable_var]*10,0))
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

class CustomModel(tf.keras.models.Model):
    def __init__(self):
        super(CustomModel, self).__init__()
        self.var = tf.Variable(initial_value=0.1, dtype=tf.float32, trainable=True)

    def loss(self):
        return tf.math.reduce_mean(tf.concat([self.var]*10,0))


model = CustomModel()

with tf.GradientTape() as gt:
    loss = model.loss()
    gt.gradient(loss, model.trainable_variables)
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "tensorflow_crash.py.py", line 18, in <module>
    gt.gradient(loss, model.trainable_variables)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/backprop.py", line 1081, in gradient
    flat_grad = imperative_grad.imperative_grad(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/imperative_grad.py", line 67, in imperative_grad
    return pywrap_tfe.TFE_Py_TapeGradient(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/backprop.py", line 156, in _gradient_function
    return grad_fn(mock_op, *out_grads)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/array_grad.py", line 228, in _ConcatGradV2
    return _ConcatGradHelper(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/array_grad.py", line 116, in _ConcatGradHelper
    concat_dim._numpy().item(0) % input_values[0]._rank())  # pylint: disable=protected-access
ZeroDivisionError: integer division or modulo by zero
```
</details>

**Comment by tilakrayal** [comment]
Hi @str4si,
I tried to execute the given code in an alternative approach. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/37e3cdd3268ef2d0c54b80f9d0a2e8e5/56335.ipynb). Thank you!
