### ISSUE TITLE
Locating the numpy include path can fail incorrectly

### ISSUE THREAD

**Issue by SnoopJ** [tensorflow/tensorflow#56373]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

Many versions. Affects 2.9.1 and HEAD (as of ee96662)

### Custom Code

Yes

### OS Platform and Distribution

Most. Reproduced on Ubuntu 20.04

### Mobile device

N/A

### Python version

3.8.10

### Bazel version

5.1.1

### GCC/Compiler version

9.4.0

### CUDA/cuDNN version

N/A

### GPU model and memory

N/A

### NOTE: This is a re-filing of #56346 to use the issue template and add a complete reproduction

[`_get_numpy_include()`](https://github.com/tensorflow/tensorflow/blob/d7e521a1ad21681855b439b9c2a05837c804e488/third_party/py/python_configure.bzl#L188-L201) will fail if importing `numpy` causes _anything_ to be written to stderr, even if the command succeeds. I found this while helping a user in #python on the Libera.chat IRC network debug [a failure](https://github.com/google/yggdrasil-decision-forests/issues/19) when building `yggdrasil-decision-forests`. When they import `numpy` on their system, they get the following non-fatal warning:

```
OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
```

Which causes `execute()` to fail. It looks like the `allow_failure` parameter for that function is meant to address this, so adding this argument should fix the issue in this specific case, but I'm not sure what the other implications might be. (as an aside, this parameter is confusingly documented, I have opened #56345 to address that)

Insight from someone who is more familiar with TF's build system would be appreciated, but inspecting stdout/stderr strikes me as a very strange way to work out whether or not the executed process failed. Is there a reason this bit of code does not check the [`return_code`](https://bazel.build/rules/lib/exec_result) of the raw execution?

### Standalone code to reproduce the issue

Below is a `Dockerfile` that should completely reproduce the problem.

**NOTE** that this example does modify `numpy` to issue a guaranteed warning, but as linked above, warnings _can_ occur in `numpy` and its dependencies.

```Dockerfile
FROM ubuntu:20.04 as repro                                                        
                                                                                  
ENV DEBIAN_FRONTEND=noninteractive                                                
ENV LANG C.UTF-8                                                                  
                                                                                  
RUN apt update && \                                                               
    apt install -y \                                                              
        curl \                                                                    
        git \                                                                     
        python3 python3-pip                                                       
                                                                                  
# install bazel                                                                   
RUN apt install apt-transport-https curl gnupg -y && \                            
    curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.g
pg && \                                                                           
    mv bazel.gpg /etc/apt/trusted.gpg.d/ && \                                     
    echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list && \                                    
    apt update && apt install bazel -y && \                                       
    apt update && apt full-upgrade -y && \                                        
    apt install bazel-1.0.0 -y                                                    
                                                                                  
RUN python3 -m pip install numpy==1.22.4 && \                                     
    # NOTE: the below modifies numpy in-place to reliably simulate warnings       
    # that might be emitted in normal operation of numpy (e.g. OpenBLAS can       
    # issue warnings). This can cause a build of TensorFlow to fail incorrectly   
    sed -i "38i\    warnings.warn('example warning (written to stderr)')" /usr/local/lib/python3.8/dist-packages/numpy/lib/utils.py                                 
                                                                                  
RUN git clone --depth=1 https://github.com/tensorflow/tensorflow/ /tmp/tensorflow 
                                                                                  
WORKDIR /tmp/tensorflow                                                           
CMD ["/bin/sh", "-c", "bazel build //tensorflow"]
```

### Relevant log output

```shell
$ docker build -t tfbug:repro .
# ... snip ...
Successfully tagged tfbug:repro

$ docker run -it tfbug:repro
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=0
INFO: Reading rc options for 'build' from /tmp/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /tmp/tensorflow/.bazelrc:
  'build' options: --define framework_shared_object=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library --experimental_link_static_libraries_once=false --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/ir,tensorflow/compiler/mlir/tfrt/tests/analysis,tensorflow/compiler/mlir/tfrt/tests/jit,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_tfrt,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_jitrt,tensorflow/compiler/mlir/tfrt/tests/tf_to_corert,tensorflow/compiler/mlir/tfrt/tests/tf_to_tfrt_data,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/common,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/graph_executor,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
INFO: Found applicable config definition build:short_logs in file /tmp/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /tmp/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:linux in file /tmp/tensorflow/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++17 --host_cxxopt=-std=c++17 --config=dynamic_kernels --distinct_host_configuration=false --experimental_guard_against_concurrent_changes
INFO: Found applicable config definition build:dynamic_kernels in file /tmp/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/62a3081341bdbe5614899de6a1aa3ec183810229.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
INFO: Repository local_config_python instantiated at:
  /tmp/tensorflow/WORKSPACE:15:14: in <toplevel>
  /tmp/tensorflow/tensorflow/workspace2.bzl:870:19: in workspace
  /tmp/tensorflow/tensorflow/workspace2.bzl:100:21: in _tf_toolchains
Repository rule python_configure defined at:
  /tmp/tensorflow/third_party/py/python_configure.bzl:298:35: in <toplevel>
INFO: Repository local_execution_config_python instantiated at:
  /tmp/tensorflow/WORKSPACE:15:14: in <toplevel>
  /tmp/tensorflow/tensorflow/workspace2.bzl:870:19: in workspace
  /tmp/tensorflow/tensorflow/workspace2.bzl:90:27: in _tf_toolchains
  /tmp/tensorflow/tensorflow/tools/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  /tmp/tensorflow/tensorflow/tools/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  /tmp/tensorflow/third_party/py/python_configure.bzl:279:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_python':
   Traceback (most recent call last):
        File "/tmp/tensorflow/third_party/py/python_configure.bzl", line 271, column 40, in _python_autoconf_impl
                _create_local_python_repository(repository_ctx)
        File "/tmp/tensorflow/third_party/py/python_configure.bzl", line 216, column 39, in _create_local_python_repository
                numpy_include = _get_numpy_include(repository_ctx, python_bin) + "/numpy"
        File "/tmp/tensorflow/third_party/py/python_configure.bzl", line 190, column 19, in _get_numpy_include
                return execute(
        File "/tmp/tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Problem getting numpy include path.
/usr/local/lib/python3.8/dist-packages/numpy/lib/utils.py:38: UserWarning: example warning (written to stderr)
  warnings.warn('example warning (written to stderr)')
Is numpy installed?
ERROR: /tmp/tensorflow/WORKSPACE:15:14: fetching python_configure rule //external:local_config_python: Traceback (most recent call last):
        File "/tmp/tensorflow/third_party/py/python_configure.bzl", line 271, column 40, in _python_autoconf_impl
                _create_local_python_repository(repository_ctx)
        File "/tmp/tensorflow/third_party/py/python_configure.bzl", line 216, column 39, in _create_local_python_repository
                numpy_include = _get_numpy_include(repository_ctx, python_bin) + "/numpy"
        File "/tmp/tensorflow/third_party/py/python_configure.bzl", line 190, column 19, in _get_numpy_include
                return execute(
        File "/tmp/tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Problem getting numpy include path.
/usr/local/lib/python3.8/dist-packages/numpy/lib/utils.py:38: UserWarning: example warning (written to stderr)
  warnings.warn('example warning (written to stderr)')
Is numpy installed?
INFO: Repository go_sdk instantiated at:
  /tmp/tensorflow/WORKSPACE:23:14: in <toplevel>
  /tmp/tensorflow/tensorflow/workspace0.bzl:134:20: in workspace
  /root/.cache/bazel/_bazel_root/e5cce820cc082410b4fcc604db349066/external/com_github_grpc_grpc/bazel/grpc_extra_deps.bzl:36:27: in grpc_extra_deps
  /root/.cache/bazel/_bazel_root/e5cce820cc082410b4fcc604db349066/external/io_bazel_rules_go/go/toolchain/toolchains.bzl:379:28: in go_register_toolchains
  /root/.cache/bazel/_bazel_root/e5cce820cc082410b4fcc604db349066/external/io_bazel_rules_go/go/private/sdk.bzl:65:21: in go_download_sdk
Repository rule _go_download_sdk defined at:
  /root/.cache/bazel/_bazel_root/e5cce820cc082410b4fcc604db349066/external/io_bazel_rules_go/go/private/sdk.bzl:53:35: in <toplevel>
ERROR: Analysis of target '//tensorflow:tensorflow' failed; build aborted: Problem getting numpy include path.
/usr/local/lib/python3.8/dist-packages/numpy/lib/utils.py:38: UserWarning: example warning (written to stderr)
  warnings.warn('example warning (written to stderr)')
Is numpy installed?
INFO: Elapsed time: 116.976s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (33 packages loaded, 15 targets co\
nfigured)
$ docker run -it tfbug:repro python3 -c "import numpy; print(numpy.get_include())"  # demonstration: get_include() succeeds just fine
/usr/local/lib/python3.8/dist-packages/numpy/lib/utils.py:38: UserWarning: example warning (written to stderr)
  warnings.warn('example warning (written to stderr)')
/usr/local/lib/python3.8/dist-packages/numpy/core/include
$ echo $?  # the return code of the process is zero, there was no failure
0
```
</details>

**Comment by sushreebarsa** [comment]
@SnoopJeDi Thank you for reporting this issue!
It will be closed once the PR is merged. Thank you!

**Comment by SnoopJeDi** [comment]
As described in #56399, this failure goes beyond the numpy-specific case.

**Comment by Arnold1** [comment]
hi @sushreebarsa  - can we please merge that pr - I still see that problem with tensorflow 2.9.1 ...

**Comment by aniruthraj** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
