### ISSUE TITLE
ImportError: cannot import name 'full_type_pb2'

### ISSUE THREAD

**Issue by jq460** [tensorflow/tensorflow#56378]
### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf.2.6

### Custom Code

Yes

### OS Platform and Distribution

Windows10 x64

### Python version

3.6.8

### Current Behaviour?

```shell
When import tensorflow raise ImportError: cannot import name 'full_type_pb2'
```

### Standalone code to reproduce the issue

```shell
use anaconda-4.12.0 to create python env.
Package                 Version
----------------------- ------------
absl-py                 0.15.0
astunparse              1.6.3
atomicwrites            1.4.0
attrs                   21.4.0
cached-property         1.5.2
cachetools              4.2.4
certifi                 2021.10.8
cffi                    1.15.0
charset-normalizer      2.0.10
clang                   5.0
cloudpickle             2.0.0
colorama                0.4.4
configparser            3.7.5
cycler                  0.11.0
dataclasses             0.8
deap                    1.3.1
decorator               4.4.2
enum34                  1.1.10
esdk-obs-python         3.21.8
flatbuffers             1.12
future                  0.18.2
gast                    0.4.0
google-auth             1.35.0
google-auth-oauthlib    0.4.6
google-pasta            0.2.0
grpcio                  1.43.0
h5py                    3.1.0
hyperopt                0.2.7
idna                    3.3
importlib-metadata      4.8.3
importlib-resources     5.4.0
joblib                  1.1.0
jsonschema              3.2.0
keras                   2.6.0
Keras-Preprocessing     1.1.2
kiwisolver              1.3.1
lightgbm                3.3.2
lxml                    4.9.0
Markdown                3.3.6
matplotlib              3.3.4
mip                     1.13.0
more-itertools          8.12.0
mpmath                  1.2.1
networkx                2.5.1
numpy                   1.19.5
oauthlib                3.1.1
opt-einsum              3.3.0
packaging               21.3
pandas                  1.1.5
Pillow                  8.4.0
pip                     21.3.1
pluggy                  0.13.1
protobuf                4.21.0
py                      1.11.0
py4j                    0.10.9.5
pyaml                   21.10.1
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pycparser               2.21
pycryptodome            3.10.1
pyparsing               3.0.7
pyrsistent              0.18.0
pytest                  4.6.11
python-dateutil         2.8.2
python-docx             0.8.11
python-intervals        1.10.0.post1
pytz                    2021.3
PyWavelets              1.1.1
PyYAML                  6.0
requests                2.26.0
requests-oauthlib       1.3.0
rsa                     4.8
ruamel.yaml             0.16.13
ruamel.yaml.clib        0.2.6
scikit-learn            0.23.2
scikit-optimize         0.8.1
scipy                   1.4.1
setuptools              47.1.1
simon                   1.0.8
six                     1.15.0
sympy                   1.9
tensorboard             2.6.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1
tensorflow              2.6.2
tensorflow-estimator    2.6.0
termcolor               1.1.0
threadpoolctl           3.1.0
tqdm                    4.64.0
typing-extensions       3.7.4.3
urllib3                 1.26.8
wcwidth                 0.2.5
Werkzeug                2.0.2
wheel                   0.37.1
wincertstore            0.2
wrapt                   1.12.1
xgboost                 1.4.2
zipp                    3.6.0
```

### Relevant log output

Traceback (most recent call last):
  File "D:\solution_utils.py", line 17, in <module>
    import tensorflow as tf
  File "C:\Users\jq\AppData\Roaming\Python\Python36\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\jq\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\__init__.py", line 46, in <module>
    from tensorflow.python import data
  File "C:\Users\jq\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\data\__init__.py", line 25, in <module>
    from tensorflow.python.data import experimental
  File "C:\Users\jq\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\data\experimental\__init__.py", line 97, in <module>
    from tensorflow.python.data.experimental import service
  File "C:\Users\jq\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\data\experimental\service\__init__.py", line 353, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "C:\Users\jq\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\data\experimental\ops\data_service_ops.py", line 26, in <module>
    from tensorflow.python.data.experimental.ops import compression_ops
  File "C:\Users\jq\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\data\experimental\ops\compression_ops.py", line 20, in <module>
    from tensorflow.python.data.util import structure
  File "C:\Users\jq\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\data\util\structure.py", line 26, in <module>
    from tensorflow.python.data.util import nest
  File "C:\Users\jq\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\data\util\nest.py", line 40, in <module>
    from tensorflow.python.framework import sparse_tensor as _sparse_tensor
  File "C:\Users\jq\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\sparse_tensor.py", line 28, in <module>
    from tensorflow.python.framework import constant_op
  File "C:\Users\jq\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\constant_op.py", line 29, in <module>
    from tensorflow.python.eager import execute
  File "C:\Users\jq\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\eager\execute.py", line 28, in <module>
    from tensorflow.python.framework import ops
  File "C:\Users\jq\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\ops.py", line 54, in <module>
    from tensorflow.python.framework import cpp_shape_inference_pb2
  File "C:\Users\jq\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\cpp_shape_inference_pb2.py", line 16, in <module>
    from tensorflow.core.framework import full_type_pb2 as tensorflow_dot_core_dot_framework_dot_full__type__pb2
ImportError: cannot import name 'full_type_pb2'

**Comment by mohantym** [comment]
Hi @jq460 ! 
Could you create a new environment and test with Python 3.7/3.8 (Python 3.7 is the minimum version now)  and let us know. Thank you!

**Comment by jq460** [comment]
python==3.8.0
import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jq\.conda\envs\simon3.8\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\jq\.conda\envs\simon3.8\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\jq\.conda\envs\simon3.8\lib\site-packages\tensorflow\python\eager\context.py", line 32, in <module>
    from tensorflow.core.framework import function_pb2
  File "C:\Users\jq\.conda\envs\simon3.8\lib\site-packages\tensorflow\core\framework\function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "C:\Users\jq\.conda\envs\simon3.8\lib\site-packages\tensorflow\core\framework\attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "C:\Users\jq\.conda\envs\simon3.8\lib\site-packages\tensorflow\core\framework\tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "C:\Users\jq\.conda\envs\simon3.8\lib\site-packages\tensorflow\core\framework\resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "C:\Users\jq\.conda\envs\simon3.8\lib\site-packages\tensorflow\core\framework\tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "C:\Users\jq\.conda\envs\simon3.8\lib\site-packages\google\protobuf\descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
