### ISSUE TITLE
No gradients provided for any variable

### ISSUE THREAD

**Issue by unsignedrant** [tensorflow/tensorflow#56396]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.9.1

### Custom Code

Yes

### OS Platform and Distribution

macOS Monterey 12.4

### Python version

3.10.4

### Current Behaviour?

[distilbert-base-uncased.txt](https://huggingface.co/distilbert-base-uncased/blob/main/vocab.txt)

Loss is provided and I get an error. To make it work, modify the commented line and replace `return loss` with `return 'mse'` and it should work fine.

### Standalone code to reproduce the issue

```shell
import random
import string

import numpy as np
import tensorflow as tf
import tensorflow_models as tfm
from keras import Model
from keras.layers import Dense, Dropout, Input
from transformers import TFAutoModel


def calculate_loss(pad_val, max_val):
    def loss(y_true, y_pred):
        pad_indices = tf.where(y_true == pad_val)
        y_true = tf.tensor_scatter_nd_update(
            y_true,
            pad_indices,
            tf.ones(tf.shape(pad_indices)[0], y_true.dtype) * max_val,
        )
        actual_orders = tf.argsort(tf.argsort(y_true))
        predicted_orders = tf.argsort(tf.argsort(y_pred))
        return tf.reduce_sum(tf.abs(actual_orders - predicted_orders))

    return loss  # change this with 'mse' and the error is gone


def create_model(input_shape, bert_head):
    ids = Input(input_shape, dtype='int32', name='input_ids')
    masks = Input(input_shape, dtype='int32', name='attention_mask')
    x0 = dict(input_ids=ids, attention_mask=masks)
    x = bert_head(x0)[0]
    x = Dropout(0.2)(x)
    x = Dense(64)(x)
    x = Dropout(0.2)(x)
    output = Dense(1, 'sigmoid')(x)
    return Model(x0, output)


class DatasetGen:
    def __init__(self, tokenizer, packer, min_seq_length, max_seq_length):
        self.tokenizer = tokenizer
        self.packer = packer
        self.min_seq_length = min_seq_length
        self.max_seq_length = max_seq_length

    def process_xy(self, x, y):
        tokens = self.tokenizer(x)
        x = self.packer(tokens)
        x['input_ids'] = x['input_word_ids']
        x['attention_mask'] = x['input_mask']
        del x['input_word_ids']
        del x['input_type_ids']
        del x['input_mask']
        return x, tf.expand_dims(y, -1)

    def dummy_dataset(self, batch_size=4, size=1000):
        s = string.ascii_letters + 10 * ' '
        xs = []
        ys = []
        for _ in range(size):
            x, y = [], []
            seq_length = random.randint(self.min_seq_length, self.max_seq_length)
            for i in range(seq_length):
                x.append(''.join(random.choice(s) for _ in range(50, 150)))
                y.append(i)
            pad_size = self.max_seq_length - seq_length
            xs.append(np.pad(np.array(x), [0, pad_size]))
            ys.append(np.pad(np.array(y), [0, pad_size]))
        return (
            tf.data.Dataset.from_tensor_slices((xs, ys))
            .batch(batch_size)
            .map(self.process_xy)
        )


if __name__ == '__main__':
    pretrained_model = 'distilbert-base-uncased'
    cache_dir = 'transformers-cache'
    head = TFAutoModel.from_pretrained(pretrained_model, cache_dir=cache_dir)
    tokenizer = tfm.nlp.layers.BertTokenizer(
        vocab_file='distilbert-base-uncased.txt'
    )
    packer = tfm.nlp.layers.BertPackInputs(
        50, special_tokens_dict=tokenizer.get_special_tokens_dict()
    )
    data_gen = DatasetGen(tokenizer, packer, 10, 50)
    dataset = data_gen.dummy_dataset()
    model = create_model((None,), head)
    model.compile('adam', calculate_loss(0, 1))
    model.fit(dataset, batch_size=4)
```

### Relevant log output

```shell
/usr/local/opt/python@3.10/bin/python3.10 /Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py --multiprocess --qt-support=auto --client 127.0.0.1 --port 49349 --file "/Users/user/Library/Application Support/JetBrains/PyCharm2022.1/scratches/scratch_1.py"
Connected to pydev debugger (build 221.5787.24)
2022-06-08 04:01:25.576194: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Some layers from the model checkpoint at distilbert-base-uncased were not used when initializing TFDistilBertModel: ['vocab_transform', 'vocab_layer_norm', 'vocab_projector', 'activation_13']
- This IS expected if you are initializing TFDistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFDistilBertModel were initialized from the model checkpoint at distilbert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertModel for predictions without further training.
WARNING:tensorflow:The dtype of the target tensor must be floating (e.g. tf.float32) when calling GradientTape.gradient, got tf.int32
WARNING:tensorflow:The dtype of the target tensor must be floating (e.g. tf.float32) when calling GradientTape.gradient, got tf.int32
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/var/folders/_0/8cr6pwvs1jg99fgtf2_33lsm0000gn/T/__autograph_generated_file56mk7ojv.py", line 15, in tf__train_function
    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
ValueError: in user code:

    File "/usr/local/lib/python3.10/site-packages/keras/engine/training.py", line 1051, in train_function  *
        return step_function(self, iterator)
    File "/usr/local/lib/python3.10/site-packages/keras/engine/training.py", line 1040, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.10/site-packages/keras/engine/training.py", line 1030, in run_step  **
        outputs = model.train_step(data)
    File "/usr/local/lib/python3.10/site-packages/keras/engine/training.py", line 893, in train_step
        self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "/usr/local/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 539, in minimize
        return self.apply_gradients(grads_and_vars, name=name)
    File "/usr/local/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 640, in apply_gradients
        grads_and_vars = optimizer_utils.filter_empty_gradients(grads_and_vars)
    File "/usr/local/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/utils.py", line 73, in filter_empty_gradients
        raise ValueError(f"No gradients provided for any variable: {variable}. "

    ValueError: No gradients provided for any variable: (['tf_distil_bert_model/distilbert/embeddings/word_embeddings/weight:0', 'tf_distil_bert_model/distilbert/embeddings/position_embeddings/embeddings:0', 'tf_distil_bert_model/distilbert/embeddings/LayerNorm/gamma:0', 'tf_distil_bert_model/distilbert/embeddings/LayerNorm/beta:0', 'tf_distil_bert_model/distilbert/transformer/layer_._0/attention/q_lin/kernel:0', 'tf_distil_bert_model/distilbert/transformer/layer_._0/attention/q_lin/bias:0', 'tf_distil_bert_model/distilbert/transformer/layer_._0/attention/k_lin/kernel:0', 'tf_distil_bert_model/distilbert/transformer/layer_._0/attention/k_lin/bias:0', 'tf_distil_bert_model/distilbert/transformer/layer_._0/attention/v_lin/kernel:0', 'tf_distil_bert_model/distilbert/transformer/layer_._0/attention/v_lin/bias:0', 'tf_distil_bert_model/distilbert/transformer/layer_._0/attention/out_lin/kernel:0', 'tf_distil_bert_model/distilbert/transformer/layer_._0/attention/out_lin/bias:0', 'tf_distil_bert_model/distilbert/transformer/layer_._0/sa_layer_norm/gamma:0', 'tf_distil_bert_model/distilbert/transformer/layer_._0/sa_layer_norm/beta:0', 'tf_distil_bert_model/distilbert/transformer/layer_._0/ffn/lin1/kernel:0', 'tf_distil_bert_model/distilbert/transformer/layer_._0/ffn/lin1/bias:0', 'tf_distil_bert_model/distilbert/transformer/layer_._0/ffn/lin2/kernel:0', 'tf_distil_bert_model/distilbert/transformer/layer_._0/ffn/lin2/bias:0', 'tf_distil_bert_model/distilbert/transformer/layer_._0/output_layer_norm/gamma:0', 'tf_distil_bert_model/distilbert/transformer/layer_._0/output_layer_norm/beta:0', 'tf_distil_bert_model/distilbert/transformer/layer_._1/attention/q_lin/kernel:0', 'tf_distil_bert_model/distilbert/transformer/layer_._1/attention/q_lin/bias:0', 'tf_distil_bert_model/distilbert/transformer/layer_._1/attention/k_lin/kernel:0', 'tf_distil_bert_model/distilbert/transformer/layer_._1/attention/k_lin/bias:0', 'tf_distil_bert_model/distilbert/transformer/layer_._1/attention/v_lin/kernel:0', 'tf_distil_bert_model/distilbert/transformer/layer_._1/attention/v_lin/bias:0', 'tf_distil_bert_model/distilbert/transformer/layer_._1/attention/out_lin/kernel:0', 'tf_distil_bert_model/distilbert/transformer/layer_._1/attention/out_lin/bias:0', 'tf_distil_bert_model/distilbert/transformer/layer_._1/sa_layer_norm/gamma:0', 'tf_distil_bert_model/distilbert/transformer/layer_._1/sa_layer_norm/beta:0', 'tf_distil_bert_model/distilbert/transformer/layer_._1/ffn/lin1/kernel:0', 'tf_distil_bert_model/distilbert/transformer/layer_._1/ffn/lin1/bias:0', 'tf_distil_bert_model/distilbert/transformer/layer_._1/ffn/lin2/kernel:0', 'tf_distil_bert_model/distilbert/transformer/layer_._1/ffn/lin2/bias:0', 'tf_distil_bert_model/distilbert/transformer/layer_._1/output_layer_norm/gamma:0', 'tf_distil_bert_model/distilbert/transformer/layer_._1/output_layer_norm/beta:0', 'tf_distil_bert_model/distilbert/transformer/layer_._2/attention/q_lin/kernel:0', 'tf_distil_bert_model/distilbert/transformer/layer_._2/attention/q_lin/bias:0', 'tf_distil_bert_model/distilbert/transformer/layer_._2/attention/k_lin/kernel:0', 'tf_distil_bert_model/distilbert/transformer/layer_._2/attention/k_lin/bias:0', 'tf_distil_bert_model/distilbert/transformer/layer_._2/attention/v_lin/kernel:0', 'tf_distil_bert_model/distilbert/transformer/layer_._2/attention/v_lin/bias:0', 'tf_distil_bert_model/distilbert/transformer/layer_._2/attention/out_lin/kernel:0', 'tf_distil_bert_model/distilbert/transformer/layer_._2/attention/out_lin/bias:0', 'tf_distil_bert_model/distilbert/transformer/layer_._2/sa_layer_norm/gamma:0', 'tf_distil_bert_model/distilbert/transformer/layer_._2/sa_layer_norm/beta:0', 'tf_distil_bert_model/distilbert/transformer/layer_._2/ffn/lin1/kernel:0', 'tf_distil_bert_model/distilbert/transformer/layer_._2/ffn/lin1/bias:0', 'tf_distil_bert_model/distilbert/transformer/layer_._2/ffn/lin2/kernel:0', 'tf_distil_bert_model/distilbert/transformer/layer_._2/ffn/lin2/bias:0', 'tf_distil_bert_model/distilbert/transformer/layer_._2/output_layer_norm/gamma:0', 'tf_distil_bert_model/distilbert/transformer/layer_._2/output_layer_norm/beta:0', 'tf_distil_bert_model/distilbert/transformer/layer_._3/attention/q_lin/kernel:0', 'tf_distil_bert_model/distilbert/transformer/layer_._3/attention/q_lin/bias:0', 'tf_distil_bert_model/distilbert/transformer/layer_._3/attention/k_lin/kernel:0', 'tf_distil_bert_model/distilbert/transformer/layer_._3/attention/k_lin/bias:0', 'tf_distil_bert_model/distilbert/transformer/layer_._3/attention/v_lin/kernel:0', 'tf_distil_bert_model/distilbert/transformer/layer_._3/attention/v_lin/bias:0', 'tf_distil_bert_model/distilbert/transformer/layer_._3/attention/out_lin/kernel:0', 'tf_distil_bert_model/distilbert/transformer/layer_._3/attention/out_lin/bias:0', 'tf_distil_bert_model/distilbert/transformer/layer_._3/sa_layer_norm/gamma:0', 'tf_distil_bert_model/distilbert/transformer/layer_._3/sa_layer_norm/beta:0', 'tf_distil_bert_model/distilbert/transformer/layer_._3/ffn/lin1/kernel:0', 'tf_distil_bert_model/distilbert/transformer/layer_._3/ffn/lin1/bias:0', 'tf_distil_bert_model/distilbert/transformer/layer_._3/ffn/lin2/kernel:0', 'tf_distil_bert_model/distilbert/transformer/layer_._3/ffn/lin2/bias:0', 'tf_distil_bert_model/distilbert/transformer/layer_._3/output_layer_norm/gamma:0', 'tf_distil_bert_model/distilbert/transformer/layer_._3/output_layer_norm/beta:0', 'tf_distil_bert_model/distilbert/transformer/layer_._4/attention/q_lin/kernel:0', 'tf_distil_bert_model/distilbert/transformer/layer_._4/attention/q_lin/bias:0', 'tf_distil_bert_model/distilbert/transformer/layer_._4/attention/k_lin/kernel:0', 'tf_distil_bert_model/distilbert/transformer/layer_._4/attention/k_lin/bias:0', 'tf_distil_bert_model/distilbert/transformer/layer_._4/attention/v_lin/kernel:0', 'tf_distil_bert_model/distilbert/transformer/layer_._4/attention/v_lin/bias:0', 'tf_distil_bert_model/distilbert/transformer/layer_._4/attention/out_lin/kernel:0', 'tf_distil_bert_model/distilbert/transformer/layer_._4/attention/out_lin/bias:0', 'tf_distil_bert_model/distilbert/transformer/layer_._4/sa_layer_norm/gamma:0', 'tf_distil_bert_model/distilbert/transformer/layer_._4/sa_layer_norm/beta:0', 'tf_distil_bert_model/distilbert/transformer/layer_._4/ffn/lin1/kernel:0', 'tf_distil_bert_model/distilbert/transformer/layer_._4/ffn/lin1/bias:0', 'tf_distil_bert_model/distilbert/transformer/layer_._4/ffn/lin2/kernel:0', 'tf_distil_bert_model/distilbert/transformer/layer_._4/ffn/lin2/bias:0', 'tf_distil_bert_model/distilbert/transformer/layer_._4/output_layer_norm/gamma:0', 'tf_distil_bert_model/distilbert/transformer/layer_._4/output_layer_norm/beta:0', 'tf_distil_bert_model/distilbert/transformer/layer_._5/attention/q_lin/kernel:0', 'tf_distil_bert_model/distilbert/transformer/layer_._5/attention/q_lin/bias:0', 'tf_distil_bert_model/distilbert/transformer/layer_._5/attention/k_lin/kernel:0', 'tf_distil_bert_model/distilbert/transformer/layer_._5/attention/k_lin/bias:0', 'tf_distil_bert_model/distilbert/transformer/layer_._5/attention/v_lin/kernel:0', 'tf_distil_bert_model/distilbert/transformer/layer_._5/attention/v_lin/bias:0', 'tf_distil_bert_model/distilbert/transformer/layer_._5/attention/out_lin/kernel:0', 'tf_distil_bert_model/distilbert/transformer/layer_._5/attention/out_lin/bias:0', 'tf_distil_bert_model/distilbert/transformer/layer_._5/sa_layer_norm/gamma:0', 'tf_distil_bert_model/distilbert/transformer/layer_._5/sa_layer_norm/beta:0', 'tf_distil_bert_model/distilbert/transformer/layer_._5/ffn/lin1/kernel:0', 'tf_distil_bert_model/distilbert/transformer/layer_._5/ffn/lin1/bias:0', 'tf_distil_bert_model/distilbert/transformer/layer_._5/ffn/lin2/kernel:0', 'tf_distil_bert_model/distilbert/transformer/layer_._5/ffn/lin2/bias:0', 'tf_distil_bert_model/distilbert/transformer/layer_._5/output_layer_norm/gamma:0', 'tf_distil_bert_model/distilbert/transformer/layer_._5/output_layer_norm/beta:0', 'dense/kernel:0', 'dense/bias:0', 'dense_1/kernel:0', 'dense_1/bias:0'],). Provided `grads_and_vars` is ((None, <tf.Variable 'tf_distil_bert_model/distilbert/embeddings/word_embeddings/weight:0' shape=(30522, 768) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/embeddings/position_embeddings/embeddings:0' shape=(512, 768) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/embeddings/LayerNorm/gamma:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/embeddings/LayerNorm/beta:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._0/attention/q_lin/kernel:0' shape=(768, 768) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._0/attention/q_lin/bias:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._0/attention/k_lin/kernel:0' shape=(768, 768) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._0/attention/k_lin/bias:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._0/attention/v_lin/kernel:0' shape=(768, 768) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._0/attention/v_lin/bias:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._0/attention/out_lin/kernel:0' shape=(768, 768) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._0/attention/out_lin/bias:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._0/sa_layer_norm/gamma:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._0/sa_layer_norm/beta:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._0/ffn/lin1/kernel:0' shape=(768, 3072) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._0/ffn/lin1/bias:0' shape=(3072,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._0/ffn/lin2/kernel:0' shape=(3072, 768) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._0/ffn/lin2/bias:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._0/output_layer_norm/gamma:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._0/output_layer_norm/beta:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._1/attention/q_lin/kernel:0' shape=(768, 768) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._1/attention/q_lin/bias:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._1/attention/k_lin/kernel:0' shape=(768, 768) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._1/attention/k_lin/bias:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._1/attention/v_lin/kernel:0' shape=(768, 768) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._1/attention/v_lin/bias:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._1/attention/out_lin/kernel:0' shape=(768, 768) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._1/attention/out_lin/bias:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._1/sa_layer_norm/gamma:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._1/sa_layer_norm/beta:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._1/ffn/lin1/kernel:0' shape=(768, 3072) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._1/ffn/lin1/bias:0' shape=(3072,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._1/ffn/lin2/kernel:0' shape=(3072, 768) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._1/ffn/lin2/bias:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._1/output_layer_norm/gamma:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._1/output_layer_norm/beta:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._2/attention/q_lin/kernel:0' shape=(768, 768) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._2/attention/q_lin/bias:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._2/attention/k_lin/kernel:0' shape=(768, 768) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._2/attention/k_lin/bias:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._2/attention/v_lin/kernel:0' shape=(768, 768) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._2/attention/v_lin/bias:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._2/attention/out_lin/kernel:0' shape=(768, 768) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._2/attention/out_lin/bias:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._2/sa_layer_norm/gamma:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._2/sa_layer_norm/beta:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._2/ffn/lin1/kernel:0' shape=(768, 3072) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._2/ffn/lin1/bias:0' shape=(3072,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._2/ffn/lin2/kernel:0' shape=(3072, 768) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._2/ffn/lin2/bias:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._2/output_layer_norm/gamma:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._2/output_layer_norm/beta:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._3/attention/q_lin/kernel:0' shape=(768, 768) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._3/attention/q_lin/bias:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._3/attention/k_lin/kernel:0' shape=(768, 768) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._3/attention/k_lin/bias:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._3/attention/v_lin/kernel:0' shape=(768, 768) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._3/attention/v_lin/bias:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._3/attention/out_lin/kernel:0' shape=(768, 768) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._3/attention/out_lin/bias:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._3/sa_layer_norm/gamma:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._3/sa_layer_norm/beta:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._3/ffn/lin1/kernel:0' shape=(768, 3072) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._3/ffn/lin1/bias:0' shape=(3072,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._3/ffn/lin2/kernel:0' shape=(3072, 768) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._3/ffn/lin2/bias:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._3/output_layer_norm/gamma:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._3/output_layer_norm/beta:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._4/attention/q_lin/kernel:0' shape=(768, 768) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._4/attention/q_lin/bias:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._4/attention/k_lin/kernel:0' shape=(768, 768) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._4/attention/k_lin/bias:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._4/attention/v_lin/kernel:0' shape=(768, 768) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._4/attention/v_lin/bias:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._4/attention/out_lin/kernel:0' shape=(768, 768) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._4/attention/out_lin/bias:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._4/sa_layer_norm/gamma:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._4/sa_layer_norm/beta:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._4/ffn/lin1/kernel:0' shape=(768, 3072) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._4/ffn/lin1/bias:0' shape=(3072,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._4/ffn/lin2/kernel:0' shape=(3072, 768) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._4/ffn/lin2/bias:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._4/output_layer_norm/gamma:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._4/output_layer_norm/beta:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._5/attention/q_lin/kernel:0' shape=(768, 768) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._5/attention/q_lin/bias:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._5/attention/k_lin/kernel:0' shape=(768, 768) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._5/attention/k_lin/bias:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._5/attention/v_lin/kernel:0' shape=(768, 768) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._5/attention/v_lin/bias:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._5/attention/out_lin/kernel:0' shape=(768, 768) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._5/attention/out_lin/bias:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._5/sa_layer_norm/gamma:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._5/sa_layer_norm/beta:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._5/ffn/lin1/kernel:0' shape=(768, 3072) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._5/ffn/lin1/bias:0' shape=(3072,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._5/ffn/lin2/kernel:0' shape=(3072, 768) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._5/ffn/lin2/bias:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._5/output_layer_norm/gamma:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'tf_distil_bert_model/distilbert/transformer/layer_._5/output_layer_norm/beta:0' shape=(768,) dtype=float32>), (None, <tf.Variable 'dense/kernel:0' shape=(768, 64) dtype=float32>), (None, <tf.Variable 'dense/bias:0' shape=(64,) dtype=float32>), (None, <tf.Variable 'dense_1/kernel:0' shape=(64, 1) dtype=float32>), (None, <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32>)).

python-BaseException

Process finished with exit code 137 (interrupted by signal 9: SIGKILL)
```
</details>

**Comment by sushreebarsa** [comment]
@unsignedrant Could you please confirm if it is a duplicate ticket of #[16663](https://github.com/keras-team/keras/issues/16663). Thank you!

**Comment by sushreebarsa** [comment]
@unsignedrant Could you please move this issue to closed status as we will track this issue there in keras-team/keras repo ?
Thank you!

**Comment by unsignedrant** [comment]
Thanks, I will. For the time being, are there any known workarounds?
