### ISSUE TITLE
Warnings (or any stderr writes) cause Python configuration to fail

### ISSUE THREAD

**Issue by SnoopJ** [tensorflow/tensorflow#56399]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

v2.5.0 (and many others)

### Custom Code

No

### OS Platform and Distribution

Ubuntu 22.04

### Mobile device

N/A

### Python version

3.10

### Bazel version

4.2.2

### GCC/Compiler version

11.2.0

### CUDA/cuDNN version

N/A

### GPU model and memory

N/A

### Current Behaviour?

The [current definition](https://github.com/tensorflow/tensorflow/blob/7fd6bc43e4d2ba1ee06ae80316e24ec43e997987/third_party/remote_config/common.bzl#L229) of the `execute()` helper for TensorFlow treats any writes to `stderr` as a fatal error.

This causes #56373, and can also cause the `third_party/py/python_configure.bzl` helpers [`_get_python_include(), _get_python_import_lib_name()`](https://github.com/tensorflow/tensorflow/blob/7fd6bc43e4d2ba1ee06ae80316e24ec43e997987/third_party/py/python_configure.bzl#L150-L186) to fail if the Python runtime issues any warnings, which is not an uncommon event. The `Dockerfile` attached to this issue illustrates a downstream failure caused by a warning issued in Python 3.10 because of the [deprecation of `distutils` (PEP 632)](https://www.python.org/dev/peps/pep-0632/)

I have observed this behavior in 2.5.0, but this failure mode should be common to most extant versions of TensorFlow.

### Standalone code to reproduce the issue

Sorry about the state of this reproduction, I did try to make a simpler one that depended only on the `tensorflow` repo but couldn't whittle it down any further.

```Dockerfile
FROM ubuntu:22.04 as repro

ENV DEBIAN_FRONTEND=noninteractive
ENV LANG C.UTF-8

# install Python (and numpy)
RUN apt update && \
    apt install -y \
        git \
        wget \
        python3 python3-pip && \
    python3 -m pip install numpy==1.22.4

# install bazel
RUN apt install -y apt-transport-https curl gnupg && \
    curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg && \
    mv bazel-archive-keyring.gpg /usr/share/keyrings && \
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list && \
    apt update && \
    apt install -y bazel-4.2.2

RUN git clone --branch 0.2.4 --depth=1 https://github.com/google/yggdrasil-decision-forests/ /tmp/yggdrasil-decision-forests

WORKDIR /tmp/yggdrasil-decision-forests
CMD ["/bin/sh", "-c", "bazel-4.2.2 build //yggdrasil_decision_forests/cli:all"]
```

### Relevant log output

```shell
$ docker build -t tfrepro:bug .
# ... snip ...
Successfully tagged tfrepro:bug
$ docker run -it tfrepro:bug
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=0
INFO: Reading rc options for 'build' from /tmp/yggdrasil-decision-forests/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec --incompatible_restrict_string_escapes=false
INFO: Reading rc options for 'build' from /tmp/yggdrasil-decision-forests/.bazelrc:
  'build' options: -c opt --spawn_strategy=standalone --announce_rc --noincompatible_strict_action_env --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --define=grpc_no_ares=true --color=yes
DEBUG: /root/.cache/bazel/_bazel_root/46fba50116469a0e63844a2e4aed5fee/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/46fba50116469a0e63844a2e4aed5fee/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'farmhash_archive' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/46fba50116469a0e63844a2e4aed5fee/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/46fba50116469a0e63844a2e4aed5fee/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/46fba50116469a0e63844a2e4aed5fee/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'zlib' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/46fba50116469a0e63844a2e4aed5fee/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'rules_cc' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/46fba50116469a0e63844a2e4aed5fee/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/46fba50116469a0e63844a2e4aed5fee/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'bazel_skylib' because it already exists.
INFO: Repository local_execution_config_python instantiated at:
  /tmp/yggdrasil-decision-forests/WORKSPACE:38:4: in <toplevel>
  /root/.cache/bazel/_bazel_root/46fba50116469a0e63844a2e4aed5fee/external/org_tensorflow/tensorflow/workspace2.bzl:1108:19: in workspace
  /root/.cache/bazel/_bazel_root/46fba50116469a0e63844a2e4aed5fee/external/org_tensorflow/tensorflow/workspace2.bzl:84:27: in _tf_toolchains
  /root/.cache/bazel/_bazel_root/46fba50116469a0e63844a2e4aed5fee/external/tf_toolchains/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  /root/.cache/bazel/_bazel_root/46fba50116469a0e63844a2e4aed5fee/external/tf_toolchains/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  /root/.cache/bazel/_bazel_root/46fba50116469a0e63844a2e4aed5fee/external/org_tensorflow/third_party/py/python_configure.bzl:275:41: in <toplevel>
INFO: Repository local_config_python instantiated at:
  /tmp/yggdrasil-decision-forests/WORKSPACE:38:4: in <toplevel>
  /root/.cache/bazel/_bazel_root/46fba50116469a0e63844a2e4aed5fee/external/org_tensorflow/tensorflow/workspace2.bzl:1108:19: in workspace
  /root/.cache/bazel/_bazel_root/46fba50116469a0e63844a2e4aed5fee/external/org_tensorflow/tensorflow/workspace2.bzl:94:21: in _tf_toolchains
Repository rule python_configure defined at:
  /root/.cache/bazel/_bazel_root/46fba50116469a0e63844a2e4aed5fee/external/org_tensorflow/third_party/py/python_configure.bzl:294:35: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/46fba50116469a0e63844a2e4aed5fee/external/org_tensorflow/third_party/py/python_configure.bzl", line 212, column 41, in _create_local_python_repository
		python_include = _get_python_include(repository_ctx, python_bin)
	File "/root/.cache/bazel/_bazel_root/46fba50116469a0e63844a2e4aed5fee/external/org_tensorflow/third_party/py/python_configure.bzl", line 152, column 21, in _get_python_include
		result = execute(
	File "/root/.cache/bazel/_bazel_root/46fba50116469a0e63844a2e4aed5fee/external/org_tensorflow/third_party/remote_config/common.bzl", line 219, column 13, in execute
		fail(
Error in fail: Problem getting python include path.
<string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
<string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
Is the Python binary path set up right? (See ./configure or PYTHON_BIN_PATH.) Is distutils installed?
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/46fba50116469a0e63844a2e4aed5fee/external/org_tensorflow/third_party/py/python_configure.bzl", line 212, column 41, in _create_local_python_repository
		python_include = _get_python_include(repository_ctx, python_bin)
	File "/root/.cache/bazel/_bazel_root/46fba50116469a0e63844a2e4aed5fee/external/org_tensorflow/third_party/py/python_configure.bzl", line 152, column 21, in _get_python_include
		result = execute(
	File "/root/.cache/bazel/_bazel_root/46fba50116469a0e63844a2e4aed5fee/external/org_tensorflow/third_party/remote_config/common.bzl", line 219, column 13, in execute
		fail(
Error in fail: Problem getting python include path.
<string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
<string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
Is the Python binary path set up right? (See ./configure or PYTHON_BIN_PATH.) Is distutils installed?
INFO: Repository remote_coverage_tools instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:11:13: in <toplevel>
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/46fba50116469a0e63844a2e4aed5fee/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository go_sdk instantiated at:
  /tmp/yggdrasil-decision-forests/WORKSPACE:42:4: in <toplevel>
  /root/.cache/bazel/_bazel_root/46fba50116469a0e63844a2e4aed5fee/external/org_tensorflow/tensorflow/workspace0.bzl:117:20: in workspace
  /root/.cache/bazel/_bazel_root/46fba50116469a0e63844a2e4aed5fee/external/com_github_grpc_grpc/bazel/grpc_extra_deps.bzl:36:27: in grpc_extra_deps
  /root/.cache/bazel/_bazel_root/46fba50116469a0e63844a2e4aed5fee/external/io_bazel_rules_go/go/toolchain/toolchains.bzl:379:28: in go_register_toolchains
  /root/.cache/bazel/_bazel_root/46fba50116469a0e63844a2e4aed5fee/external/io_bazel_rules_go/go/private/sdk.bzl:65:21: in go_download_sdk
Repository rule _go_download_sdk defined at:
  /root/.cache/bazel/_bazel_root/46fba50116469a0e63844a2e4aed5fee/external/io_bazel_rules_go/go/private/sdk.bzl:53:35: in <toplevel>
ERROR: Analysis of target '//yggdrasil_decision_forests/cli:infer_dataspec' failed; build aborted: Problem getting python include path.
<string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
<string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
Is the Python binary path set up right? (See ./configure or PYTHON_BIN_PATH.) Is distutils installed?
INFO: Elapsed time: 54.150s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (16 packages loaded, 172 targets c\
onfigured)
    Fetching ...docker; Cloning 251f6a68b439744094faff800cd029798edf9faa of ht\
tps://github.com/bazelbuild/rules_docker.git
```
</details>

**Comment by SnoopJeDi** [comment]
Do any of the maintainers know why `execute()` treats `stderr` writes as failures of the invoked process? I tried to follow the blame back as far as I could, but it looks like this function's history extends longer than the record visible in this repository, and there has never been a rationale given in the source code for this behavior.

It seems like the `execute()` helper should probably use the [`return_code`](https://bazel.build/rules/lib/exec_result) of the process to work out if the invoked process succeeded. If there isn't a specific reason to ignore the return code and focus on the content of the streams, I am willing to write a PR for the necessary changes.

**Comment by SnoopJeDi** [comment]
Alternatively, here is a patch that fixes **only** the failure reported in this issue, leaving the fairly antisocial behavior of `execute()` alone and fixing only some of the places that Python warnings can cause failures (I'm sure there are others):

```diff
diff --git a/third_party/py/python_configure.bzl b/third_party/py/python_configure.bzl
index 300cbfb6c71..2304366e338 100644
--- a/third_party/py/python_configure.bzl
+++ b/third_party/py/python_configure.bzl
@@ -165,6 +165,7 @@ def _get_python_include(repository_ctx, python_bin):
         error_details = ("Is the Python binary path set up right? " +
                          "(See ./configure or " + PYTHON_BIN_PATH + ".) " +
                          "Is distutils installed?"),
+        allow_failure = True,
     )
     return result.stdout.splitlines()[0]
 
@@ -182,6 +183,7 @@ def _get_python_import_lib_name(repository_ctx, python_bin):
         error_msg = "Problem getting python import library.",
         error_details = ("Is the Python binary path set up right? " +
                          "(See ./configure or " + PYTHON_BIN_PATH + ".) "),
+        allow_failure = True,
     )
     return result.stdout.splitlines()[0]
```

**Comment by sushreebarsa** [comment]
@SnoopJeDi Could you refer to the tested build [configurations](https://www.tensorflow.org/install/source#tested_build_configurations) and try with the latest TF version 2.9.0. Please let us know if it helps? Thank you!

**Comment by SnoopJeDi** [comment]
I tried to update the example `Dockerfile` to 2.9.0 but wasn't successful.

I am quite confident that this issue is present in 2.9.0 and the current `HEAD` of the repository, because the issue is that the `execute()` function treats stderr writes as fatal errors, and this is going to cause a lot of artificial failures with misleading error messages.

**Comment by geraldstanje** [comment]
Hi @gadagashwini i still see that error with tensorflow 2.9.1 - can we please merge it since its a bug?

**Comment by SuryanarayanaY** [comment]
Hi @SnoopJ ,

Could you please confirm if this is still an issue ? I have gone through the issue and I couldn't find reproducible code to check this issue.I am not quite follow through the issue and request you to check whether it is still same issue and if so request you to confirm and discuss. Thanks!

**Comment by SnoopJ** [comment]
> Hi @SnoopJ ,
> 
> Could you please confirm if this is still an issue ? I have gone through the issue and I couldn't find reproducible code to check this issue.I am not quite follow through the issue and request you to check whether it is still same issue and if so request you to confirm and discuss. Thanks!

The [code responsible for this bug](https://github.com/tensorflow/tensorflow/blob/127943ad063b999bf645d7d3946490f638ad92c8/third_party/remote_config/common.bzl#L229) has not changed since I filed my report, this bug is still present in TensorFlow's build system.

To reproduce the bug, any build that includes a write to `stderr` will trigger the bug. I am afraid I do not have time to put more effort into updating the reproducer I attached to this issue, but a good way to do that would be to add an extra call to `execute()` that echos something to `stderr`, which should be enough to trigger the faulty behavior.

**Comment by aniruthraj** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
