### ISSUE TITLE
tf.nn.max_pool2d data_format check is wrong for GPU

### ISSUE THREAD

**Issue by teenylasers** [tensorflow/tensorflow#56397]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.8

### GCC/Compiler version

9.4.0

### CUDA/cuDNN version

11.2/8.0

### Current Behaviour?

```shell
Even though tf.nn.max_pool2d is supposed to run on GPU, the operation always fails with the data_format check that says 'NCHW' is not supposed for CPU.
```

### Standalone code to reproduce the issue

```shell
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.debugging.set_log_device_placement(True)
>>> print(tf.config.list_physical_devices('GPU'))
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
>>> test = tf.constant([[[[1,1,1], [1,2,1], [1,1,1]]]])
2022-06-07 19:48:03.741097: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-06-07 19:48:04.333505: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 10341 MB memory:  -> device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1
2022-06-07 19:48:04.336454: I tensorflow/core/common_runtime/eager/execute.cc:1323] Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
>>> tf.nn.max_pool2d(test, 2, 1, 'SAME', 'NCHW')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jq/.local/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/jq/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 7164, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Default MaxPoolingOp only supports NHWC on device type CPU [Op:MaxPool]
>>> with tf.device("GPU:0"):
...     tf.nn.max_pool2d(test, 2, 1, 'SAME', 'NCHW')
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/jq/.local/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/jq/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 7164, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Default MaxPoolingOp only supports NHWC on device type CPU [Op:MaxPool]
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@teenylasers Reopening this issue as it is not resolved. Thank you!

**Comment by gadagashwini** [comment]
Hi @teenylasers,
Little modified your code and its working fine.
```
import tensorflow as tf
tf.debugging.set_log_device_placement(True)
print(tf.config.list_physical_devices('GPU'))
x = tf.constant([[1., 1., 1.],
                 [1., 1., 1.],
                 [1., 1., 1]])
x = x[tf.newaxis, :, :, tf.newaxis]
result = tf.nn.max_pool2d(x, ksize=(2, 2), strides=(2, 2),
                          padding='SAME', data_format='NCHW')
result[0, :, :, 0]
```

**Output**
```
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op StridedSlice in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op MaxPool in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op StridedSlice in device /job:localhost/replica:0/task:0/device:GPU:0
<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>
```

**Comment by teenylasers** [comment]
I did in the original bug report. The code was line by line done in a
Python session.
