### ISSUE TITLE
tf.data.experimental.load() no longer working

### ISSUE THREAD

**Issue by CORRELU** [tensorflow/tensorflow#56391]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

2.8

### Custom Code

No

### OS Platform and Distribution

Windows 10

### Python version

3.9

### CUDA/cuDNN version

11.2

### GPU model and memory

NVIDIA Quadro T2000

### Current Behaviour?

```shell
Hi, I've been trying to load my own tf.data dataset using the tf.data.experimental.load() command.
The data being loaded has been created in a different script using the tf.data.experimental.save() command
When I attempt to load the data it gives me an error and I cannot seem to be able to fix it.
Any help appreciated.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

tf_train = tf.data.experimental.load(
    r'D:/data/train_w512_small',
    element_spec=None,
    compression=None,
    reader_func=None
)
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Users\CORRELU\AppData\Roaming\Python\Python39\site-packages\IPython\core\interactiveshell.py", line 3251, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-11-4ae4a880fc8d>", line 1, in <module>
    tf_train = tf.data.experimental.load(
  File "C:\Users\CORRELU\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\data\experimental\ops\io.py", line 310, in load
    return _LoadDataset(
  File "C:\Users\CORRELU\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\data\experimental\ops\io.py", line 216, in __init__
    encoded_spec = f.read()
  File "C:\Users\CORRELU\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\lib\io\file_io.py", line 114, in read
    self._preread_check()
  File "C:\Users\CORRELU\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\lib\io\file_io.py", line 76, in _preread_check
    self._read_buf = _pywrap_file_io.BufferedInputStream(
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: D:/data/train_w512_small\dataset_spec.pb : The system cannot find the path specified.
; No such process
```
</details>

**Comment by mohantym** [comment]
Hi @CORRELU ! Could you pass the element spec of the dataset instead of None and let us know (also suggests to remove read mode and provide path only). Attached relevant [thread](https://www.tensorflow.org/api_docs/python/tf/data/experimental/load#:~:text=Note%20that%20to%20load%20a%20previously%20saved%20dataset%2C%20you%20need%20to%20specify%20element_spec%20%2D%2D%20a%20type%20signature%20of%20the%20elements%20of%20the%20saved%20dataset%2C%20which%20can%20be%20obtained%20via%20tf.data.Dataset.element_spec.%20This%20requirement%20exists%20so%20that%20shape%20inference%20of%20the%20loaded%20dataset%20does%20not%20need%20to%20perform%20I/O.) for reference. Thank you!

**Comment by CORRELU** [comment]
Hi, thanks for getting back to me so quickly. I've obtained the element spect through 
`tf_train.element_spec `
which output the following
```
(TensorSpec(shape=(None, None, 5), dtype=tf.float32, name=None),
 TensorSpec(shape=(None, None, 5), dtype=tf.float32, name=None))
```
How do I specify this in the load function? Just copy as is like below?
```
tf_train = tf.data.experimental.load(
    r'D:\data\train_w512_small',
    element_spec=(TensorSpec(shape=(None, None, 5), dtype=tf.float32, name=None), TensorSpec(shape=(None, None, 5), dtype=tf.float32, name=None)),
    compression=None,
    reader_func=None,
)
```
If I try the snippet above it tells me TensorSpec is not defined, hence I believe I've got the wrong syntax... What's the right way?

**Comment by mohantym** [comment]
@CORRELU ! It should be tf.TensorSpec instead of TensorSpec
 ```
tf_train = tf.data.experimental.load(
    "D:/data/train_w512_small",
    element_spec=(tf.TensorSpec(shape=(None, None, 5), dtype=tf.float32), tf.TensorSpec(shape=(None, None, 5), dtype=tf.float32)),

    compression=None,
    reader_func=None,
)
```

**Comment by CORRELU** [comment]
Hey!
I've tried specifying the tensorspec with read mode 
tf_train = tf.data.experimental.load(
    r'D:\data\train_w512_small',
    element_spec=(tf.TensorSpec(shape=(None, None, 5), dtype=tf.float32, name=None),
                  tf.TensorSpec(shape=(None, None, 5), dtype=tf.float32, name=None)),
    compression=None,
    reader_func=None,
)
and without read mode
```
tf_train = tf.data.experimental.load(
    "D:/data/train_w512_small",
    element_spec=(tf.TensorSpec(shape=(None, None, 5), dtype=tf.float32, name=None),
                  tf.TensorSpec(shape=(None, None, 5), dtype=tf.float32, name=None)),
    compression=None,
    reader_func=None,
)
```
but now a different error is shown:
```
Traceback (most recent call last):
  File "C:\Users\CORRELU\AppData\Roaming\Python\Python39\site-packages\IPython\core\interactiveshell.py", line 3251, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-26-86f81db49f36>", line 1, in <module>
    tf_val = tf.data.experimental.load(
  File "C:\Users\CORRELU\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\data\experimental\ops\io.py", line 310, in load
    return _LoadDataset(
  File "C:\Users\CORRELU\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\data\experimental\ops\io.py", line 231, in __init__
    variant_tensor = gen_experimental_dataset_ops.load_dataset(
  File "C:\Users\CORRELU\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\ops\gen_experimental_dataset_ops.py", line 6118, in load_dataset
    return load_dataset_eager_fallback(
  File "C:\Users\CORRELU\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\ops\gen_experimental_dataset_ops.py", line 6180, in load_dataset_eager_fallback
    _result = _execute.execute(b"LoadDataset", 1, inputs=_inputs_flat,
  File "C:\Users\CORRELU\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\eager\execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.NotFoundError: Could not find metadata file. [Op:LoadDataset]
```
Hope this helps?

**Comment by mohantym** [comment]
Ok @CORRELU !  Could you check this[ thread ](https://stackoverflow.com/a/71249724/11530462) with a similar error stack trace . Please provide a minimal stand alone code with dataset for further assistance. Thank you!

**Comment by CORRELU** [comment]
I managed to fix it. I'm really embarassed but the problem was that I saved the tf.data objects with a typo in the name, hence the load function could not fetch the data.

**Comment by mohantym** [comment]
@CORRELU ! Thanks for the update!
