### ISSUE TITLE
`reduce_retracing` causing: "Called a function referencing variables which have been deleted..."

### ISSUE THREAD

**Issue by jesnie** [tensorflow/tensorflow#56414]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.9.1

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 18.04.6 LTS

### Python version

3.10.4

### Current Behaviour?

```shell
When I run the below code I get the error:
"Called a function referencing variables which have been deleted. This likely means that function-local variables were created and not referenced elsewhere in the program. This is generally a mistake; consider storing variables in an object attribute on first call."

I do not get the error if:
1: I use an older version of TensorFlow (with experimental_relax_shapes instead of reduce_retracing)
2: I set `reduce_retracing=False`.
3: I remove one of the `tf.function` calls.

I'm not sure exactly what's going on here, but there is some kind of interaction that is unstable.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

reduce_retracing = True
v = tf.Variable(0.0)

@tf.function(reduce_retracing=reduce_retracing)
def f(x: tf.Tensor) -> tf.Tensor:
    return x

@tf.function(reduce_retracing=reduce_retracing)
def loss() -> tf.Tensor:
    return f(v)

optimiser = tf.keras.optimizers.SGD()
optimiser.minimize(loss, var_list=[v])
optimiser.minimize(loss, var_list=[v])
```

### Relevant log output

```shell
2022-06-09 15:38:18.788974: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-06-09 15:38:18.792122: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory
2022-06-09 15:38:18.792632: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1850] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2022-06-09 15:38:18.792867: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/home/jesper/src/GPflow/tf29_error.py", line 16, in <module>
    optimiser.minimize(loss, var_list=[v])
  File "/home/jesper/src/GPflow/.venv/max310/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 537, in minimize
    grads_and_vars = self._compute_gradients(
  File "/home/jesper/src/GPflow/.venv/max310/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 581, in _compute_gradients
    loss = loss()
  File "/home/jesper/src/GPflow/.venv/max310/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/jesper/src/GPflow/.venv/max310/lib/python3.10/site-packages/tensorflow/python/framework/func_graph.py", line 587, in deref
    raise AssertionError(
AssertionError: Called a function referencing variables which have been deleted. This likely means that function-local variables were created and not referenced elsewhere in the program. This is generally a mistake; consider storing variables in an object attribute on first call.
```
</details>

**Comment by tilakrayal** [comment]
@chunduriv,
I was able to reproduce the issue in tensorflow v2.8, v2.9 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/b0797b86bc36e6285b8bb69afcb6ef3a/56414.ipynb).

**Comment by JXRiver** [comment]
This should be fixed with the latest tf-nightly.
