### ISSUE TITLE
Executing genrule //tensorflow:tf_python_api_gen_v2 failed: (Exit 1): bash.exe failed: error executing command

### ISSUE THREAD

**Issue by Loldude0** [tensorflow/tensorflow#56426]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

Windows 11 10.0.22000

### Python version

3.10.5

### Bazel version

5.0.0

### Current Behaviour?

```shell
intel-tensorflow failed to build. I followed the intel guide at https://www.intel.com/content/www/us/en/developer/articles/guide/optimization-for-tensorflow-installation-guide.html to no avail multiple times. I have been trying for days to get it to build. I'm sorry if this issue is not in a proper format.
```

### Standalone code to reproduce the issue

```shell
Follow the intel guide at https://www.intel.com/content/www/us/en/developer/articles/guide/optimization-for-tensorflow-installation-guide.html
Python version - 3.10.5
Bazel version - 5.0.0
pip version - 22.1.2
bash version - 5.1.016-1
cpu - i5 - 1135g7 (supports AVX instructions as far as I'm aware)
release version used - 2.9.1(intel tensorflow)
build command used -  --output_base="C:/one_dnn_dir_final" build --announce_rc --config=opt --config=mkl --action_env=PATH=""C:/Python3/Scripts/";"C:/Python3/";"D:/output_dir/external/mkl/windows/lib";"C:/ProgramData/chocolatey/bin";"C:/msys64/usr/bin;C:/msys64";'C:/Program Files/Git/cmd';'C:/Program Files/Git/usr/bin';'C:/Program Files (x86)/Intel/oneAPI/tbb/latest/redist/intel64/vc_mt/';'C:/Program Files (x86)/Intel/oneAPI/tbb/latest/redist/ia32/vc_mt/';'C:/Program Files (x86)/Intel/oneAPI/compiler/latest/windows/redist/intel64_win/compiler';'C:/Program Files (x86)/Intel/oneAPI/compiler/latest/windows/redist/ia32_win/compiler';'C:/Program Files/Eclipse Adoptium/jdk-17.0.1.12-hotspot/bin';'C:/Program Files/Microsoft/jdk-11.0.12.7-hotspot/bin';'C:/Program Files (x86)/Common Files/Oracle/Java/javapath';"C:/WINDOWS/system32";"C:/WINDOWS";"C:/WINDOWS/System32/Wbem";"C:/WINDOWS/System32/WindowsPowerShell/v1.0/";"C:/WINDOWS/System32/OpenSSH/";'C:/Program Files/Microsoft SQL Server/150/Tools/Binn/';'C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/';'C:/Program Files/dotnet/';'C:/Program Files/PowerShell/7/';"C:/one_dnn_dir_final";"C:/Python2/";"C:/Users/aryan/AppData/Local/Microsoft/WindowsApps";'C:/Users/aryan/AppData/Local/Programs/Microsoft VS Code/bin';"C:/Users/aryan/.dotnet/tools";'C:/Program Files/JetBrains/IntelliJ IDEA Community Edition 2021.3.1/bin';" --noincompatible_do_not_split_linking_cmdline --define=no_tensorflow_py_deps=true tensorflow/tools/pip_package:build_pip_package
```

### Relevant log output

```shell
ERROR: C:/users/aryan/tensorflow/tensorflow/BUILD:1263:19: Executing genrule //tensorflow:tf_python_api_gen_v2 failed: (Exit 1): bash.exe failed: error executing command
  cd /d C:/one_dnn_dir_final/execroot/org_tensorflow
  SET PATH=C:/Python3/Scripts/;C:/Python3/;D:/output_dir/external/mkl/windows/lib;C:/ProgramData/chocolatey/bin;C:/msys64/usr/bin;C:/msys64;'C:/Program Files/Git/cmd';'C:/Program Files/Git/usr/bin';'C:/Program Files (x86)/Intel/oneAPI/tbb/latest/redist/intel64/vc_mt/';'C:/Program Files (x86)/Intel/oneAPI/tbb/latest/redist/ia32/vc_mt/';'C:/Program Files (x86)/Intel/oneAPI/compiler/latest/windows/redist/intel64_win/compiler';'C:/Program Files (x86)/Intel/oneAPI/compiler/latest/windows/redist/ia32_win/compiler';'C:/Program Files/Eclipse Adoptium/jdk-17.0.1.12-hotspot/bin';'C:/Program Files/Microsoft/jdk-11.0.12.7-hotspot/bin';'C:/Program Files (x86)/Common Files/Oracle/Java/javapath';C:/WINDOWS/system32;C:/WINDOWS;C:/WINDOWS/System32/Wbem;C:/WINDOWS/System32/WindowsPowerShell/v1.0/;C:/WINDOWS/System32/OpenSSH/;'C:/Program Files/Microsoft SQL Server/150/Tools/Binn/';'C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/';'C:/Program Files/dotnet/';'C:/Program Files/PowerShell/7/';C:/one_dnn_dir_final;C:/Python2/;C:/Users/aryan/AppData/Local/Microsoft/WindowsApps;'C:/Users/aryan/AppData/Local/Programs/Microsoft VS Code/bin';C:/Users/aryan/.dotnet/tools;'C:/Program Files/JetBrains/IntelliJ IDEA Community Edition 2021.3.1/bin';
    SET PYTHON_BIN_PATH=C:/Python3/python.exe
    SET PYTHON_LIB_PATH=C:/Python3/lib/site-packages
    SET RUNFILES_MANIFEST_ONLY=1
    SET TF2_BEHAVIOR=1
  C:\msys64\usr\bin\bash.exe bazel-out/x64_windows-opt/bin/tensorflow/tf_python_api_gen_v2.genrule_script.sh
# Configuration: b2a8c312d15b397779224698fb37130236d93adde6a3e7a989797461b4f2abae
# Execution platform: @local_execution_config_platform//:platform
Traceback (most recent call last):
  File "\\?\C:\Users\aryan\AppData\Local\Temp\Bazel.runfiles_qkyau8g0\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\\?\C:\Users\aryan\AppData\Local\Temp\Bazel.runfiles_qkyau8g0\runfiles\org_tensorflow\tensorflow\python\tools\api\generator\create_python_api.py", line 22, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "\\?\C:\Users\aryan\AppData\Local\Temp\Bazel.runfiles_qkyau8g0\runfiles\org_tensorflow\tensorflow\python\__init__.py", line 36, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "\\?\C:\Users\aryan\AppData\Local\Temp\Bazel.runfiles_qkyau8g0\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow.py", line 77, in <module>
    raise ImportError(
ImportError: Traceback (most recent call last):
  File "\\?\C:\Users\aryan\AppData\Local\Temp\Bazel.runfiles_qkyau8g0\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.


Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors for some common causes and solutions.
If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
ERROR: C:/users/aryan/tensorflow/tensorflow/lite/python/BUILD:68:10 Middleman _middlemen/tensorflow_Slite_Spython_Stflite_Uconvert.exe-runfiles failed: (Exit 1): bash.exe failed: error executing command
  cd /d C:/one_dnn_dir_final/execroot/org_tensorflow
  SET PATH=C:/Python3/Scripts/;C:/Python3/;D:/output_dir/external/mkl/windows/lib;C:/ProgramData/chocolatey/bin;C:/msys64/usr/bin;C:/msys64;'C:/Program Files/Git/cmd';'C:/Program Files/Git/usr/bin';'C:/Program Files (x86)/Intel/oneAPI/tbb/latest/redist/intel64/vc_mt/';'C:/Program Files (x86)/Intel/oneAPI/tbb/latest/redist/ia32/vc_mt/';'C:/Program Files (x86)/Intel/oneAPI/compiler/latest/windows/redist/intel64_win/compiler';'C:/Program Files (x86)/Intel/oneAPI/compiler/latest/windows/redist/ia32_win/compiler';'C:/Program Files/Eclipse Adoptium/jdk-17.0.1.12-hotspot/bin';'C:/Program Files/Microsoft/jdk-11.0.12.7-hotspot/bin';'C:/Program Files (x86)/Common Files/Oracle/Java/javapath';C:/WINDOWS/system32;C:/WINDOWS;C:/WINDOWS/System32/Wbem;C:/WINDOWS/System32/WindowsPowerShell/v1.0/;C:/WINDOWS/System32/OpenSSH/;'C:/Program Files/Microsoft SQL Server/150/Tools/Binn/';'C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/';'C:/Program Files/dotnet/';'C:/Program Files/PowerShell/7/';C:/one_dnn_dir_final;C:/Python2/;C:/Users/aryan/AppData/Local/Microsoft/WindowsApps;'C:/Users/aryan/AppData/Local/Programs/Microsoft VS Code/bin';C:/Users/aryan/.dotnet/tools;'C:/Program Files/JetBrains/IntelliJ IDEA Community Edition 2021.3.1/bin';
    SET PYTHON_BIN_PATH=C:/Python3/python.exe
    SET PYTHON_LIB_PATH=C:/Python3/lib/site-packages
    SET RUNFILES_MANIFEST_ONLY=1
    SET TF2_BEHAVIOR=1
  C:\msys64\usr\bin\bash.exe bazel-out/x64_windows-opt/bin/tensorflow/tf_python_api_gen_v2.genrule_script.sh
# Configuration: b2a8c312d15b397779224698fb37130236d93adde6a3e7a989797461b4f2abae
# Execution platform: @local_execution_config_platform//:platform
INFO: Elapsed time: 11069.283s, Critical Path: 848.02s
INFO: 11287 processes: 24 internal, 11263 local.
FAILED: Build did NOT complete successfully
```
</details>

**Comment by gadagashwini** [comment]
Hi @Loldude0, Follow the steps mentioned on official website of [Tensorflow](https://www.tensorflow.org/install/source_windows) to build Tensorflow from source. Tensorflow suggest to install all the pre-requisite packages to avoid errors. Thank you!

**Comment by Loldude0** [comment]
Hello @gadagashwini , I wanted to take advantage of Intel's performance tweaks and MKL and AVX-512 instructions in its Tensorflow fork hence I did not try building the official Tensorflow. Thanks.

**Comment by Loldude0** [comment]
I'll try building it again that way. Thanks!

**Comment by gadagashwini** [comment]
HI @Loldude0, Did you try to build Tensorflow with `--config=mkl`. Thank you!

**Comment by Loldude0** [comment]
> HI @Loldude0, Did you try to build Tensorflow with `--config=mkl`. Thank you!

Hello, due to frustration on failed builds, I simply installed the pre-built version of Intel® Optimization for TensorFlow and moved on. Thanks a lot for the help!

**Comment by akote123** [comment]
Hi, Is there any solution for this error if we are building from source
