### ISSUE TITLE
Lite Model Maker Object Detection not accepting background data

### ISSUE THREAD

**Issue by austinlovell25** [tensorflow/tensorflow#56449]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Source

binary

### Tensorflow Version

tf 2.8.0

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 16.04

### Python version

3.9.12

### Current Behaviour?

```shell
I cannot figure out how background data is supposed to be configured for TensorFlow Lite Model Maker Object Detection. I followed the tutorial found here (https://www.tensorflow.org/lite/models/modify/model_maker/object_detection), only replacing the tutorial dataset with my custom dataset. Everything is working correctly, and the model loads data and trains fine when all background data is removed, except I cannot figure out how background image data, which are the jpeg files in the dataset that have no associated bounding boxes, are supposed to be formatted in the .CSV file. This has resulted in a large number of false positives in my model.
```

### Standalone code to reproduce the issue

```shell
Following the formatting found here (https://cloud.google.com/vision/automl/object-detection/docs/csv-format), lines of background data in my .csv file are formatted as follows.

TEST,/folder/im3.jpeg,,,,,,,,,

However, when I try to load the CSV file into the dataset as per the tutorial, the program throws an error. It seems to be treating the CSV lines containing background data as it would treat a CSV line containing a bounding box, and I am not sure why it is not recognizing the CSV line as a line of background data.
```

### Relevant log output

```shell
Traceback (most recent call last):
File “makemodel.py”, line 20, in
train_data, validation_data, test_data = object_detector.DataLoader.from_csv(filename=os.getcwd() + ‘/csvfile.csv’, )
File “/home/m/.local/lib/python3.9/site-packages/tensorflow_examples/lite/model_maker/core/data_util/object_detector_dataloader.py”, line 292, in from_csv
cache_writer.write_files(cache_files, csv_lines=csv_lines)
File “/home/m/.local/lib/python3.9/site-packages/tensorflow_examples/lite/model_maker/core/data_util/object_detector_dataloader_util.py”, line 247, in write_files
for idx, xml_dict in enumerate(self._get_xml_dict(*args, **kwargs)):
File “/home/m/.local/lib/python3.9/site-packages/tensorflow_examples/lite/model_maker/core/data_util/object_detector_dataloader_util.py”, line 381, in _get_xml_dict
lines)
File “/home/m/.local/lib/python3.9/site-packages/tensorflow_examples/lite/model_maker/core/data_util/object_detector_dataloader_util.py”, line 337, in _get_xml_dict_from_csv_lines
xmin, ymin = float(line[3]) * width, float(line[4]) * height
ValueError: could not convert string to float:
```
</details>

**Comment by mohantym** [comment]
Hi @austinlovell25 ! Could you print the values of line[3] and line[4] here.

**Comment by austinlovell25** [comment]
> Hi @austinlovell25 ! Could you share the values of line[3] and line[4] here. I suspect that they might contain extra spaces or string characters.

I added 2 lines to output line[3] and line[4]. Here is the console log from that.

```
0.397129
0.398333
0.051000
0.021050
0.322000
0.089100
0.475000
0.286500
0.705000
0.159200
0.293000
0.340800
0.804000
0.404192
0.473000
0.399400
0.315000
0.420450


Traceback (most recent call last):
  File "/home/m/model_maker_test/makemodel.py", line 28, in <module>
    train_data, validation_data, test_data = object_detector.DataLoader.from_csv(filename=os.getcwd() + '/testfile.csv', cache_dir="cachedir")
  File "/home/m/miniconda3/envs/tf/lib/python3.9/site-packages/tensorflow_examples/lite/model_maker/core/data_util/object_detector_dataloader.py", line 292, in from_csv
    cache_writer.write_files(cache_files, csv_lines=csv_lines)
  File "/home/m/miniconda3/envs/tf/lib/python3.9/site-packages/tensorflow_examples/lite/model_maker/core/data_util/object_detector_dataloader_util.py", line 247, in write_files
    for idx, xml_dict in enumerate(self._get_xml_dict(*args, **kwargs)):
  File "/home/m/miniconda3/envs/tf/lib/python3.9/site-packages/tensorflow_examples/lite/model_maker/core/data_util/object_detector_dataloader_util.py", line 382, in _get_xml_dict
    xml_dict = _get_xml_dict_from_csv_lines(self.images_dir, image_filename,
  File "/home/m/miniconda3/envs/tf/lib/python3.9/site-packages/tensorflow_examples/lite/model_maker/core/data_util/object_detector_dataloader_util.py", line 337, in _get_xml_dict_from_csv_lines
    xmin, ymin = float(line[3]) * width, float(line[4]) * height
ValueError: could not convert string to float: ''

```

The two blank lines at the end are from the background data line, and they are what is causing the error. Also, I tried reading my CSV file into pandas DataFrame, and I found that the blank values in my CSV file are passed into pandas DataFrame as NaN values. Not sure if that helps or not.

**Comment by mohantym** [comment]
@austinlovell25 ! I suggest removing the blank lines or rows containing NAN values which might be causing the false positives in the first case. Thank you!

**Comment by austinlovell25** [comment]
> @austinlovell25 ! I suggest removing the blank lines or rows containing NAN values which might be causing the false positives in the first case. Thank you!

The program works when I do this, and this is what I have been doing while testing. However, this means that the model will not be training on any of the background data that I would like to give it. Is there anyway for me to actually train the model on background images that have no bounding boxes?

**Comment by mohantym** [comment]
@austinlovell25 ! I am afraid that training will work without the bounding boxes . You can label the background objects (as others) with a bounding box to train with objects in focus.  Please move this closed status if it is resolved . Thank you!

**Comment by mohantym** [comment]
Hi @austinlovell25 !

Thanks for the feedback. 
My thought is using  image segmentation for background image detection would give a new direction on this as we give the boundary boxes of object that need to be detection. Providing null boundary box co-ordinates might not work. 

But using image segmenation or other methods along the present object detection might give the required results.
Feel free to re-open this issue if it is scope of  improvement.

Thank you!
