### ISSUE TITLE
Saved h5 failed to load with custom layers using hdf5_format

### ISSUE THREAD

**Issue by sunweilunformatech** [tensorflow/tensorflow#56448]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.6 - 2.9

### Custom Code

Yes

### Current Behaviour?

```shell
Model loading fails with custom layer using hdf5_format lib.
It works with keras.models.load_model or with version TF 2.5.x, but starts failing from TF 2.6+. See log for details.
```

### Standalone code to reproduce the issue

```shell
from tensorflow import keras
import h5py
from tensorflow.python.keras.saving import hdf5_format


class CustomLayer(keras.layers.Layer):
    """combine multiple activations weighted by learnable variables"""
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def get_config(self):
        return {}

    def build(self, input_shape):
        return

    def call(self, inputs):
        return inputs
    
path = 'test.h5'
    
x = keras.Input((5))
y = CustomLayer()(x)
model = keras.Model(x, y)
model.build(x)
model.save(path)

# this works ok
custom_objects = {'CustomLayer': CustomLayer}
model = keras.models.load_model(path, custom_objects=custom_objects)

# this fails
with h5py.File('test.h5', mode='r') as f:
    saved_model = hdf5_format.load_model_from_hdf5(
        f, custom_objects=custom_objects)
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "model_save.py", line 36, in <module>
    saved_model = hdf5_format.load_model_from_hdf5(
  File "/opt/conda/envs/iris/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 180, in load_model_from_hdf5
    model = model_config_lib.model_from_config(model_config,
  File "/opt/conda/envs/iris/lib/python3.8/site-packages/tensorflow/python/keras/saving/model_config.py", line 52, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/opt/conda/envs/iris/lib/python3.8/site-packages/tensorflow/python/keras/layers/serialization.py", line 163, in deserialize
    return generic_utils.deserialize_keras_object(
  File "/opt/conda/envs/iris/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 674, in deserialize_keras_object
    deserialized_obj = cls.from_config(
  File "/opt/conda/envs/iris/lib/python3.8/site-packages/tensorflow/python/keras/engine/functional.py", line 667, in from_config
    input_tensors, output_tensors, created_layers = reconstruct_from_config(
  File "/opt/conda/envs/iris/lib/python3.8/site-packages/tensorflow/python/keras/engine/functional.py", line 1310, in reconstruct_from_config
    layer_output_tensors = layer._inbound_nodes[node_index].output_tensors
IndexError: list index out of range
```
</details>

**Comment by sushreebarsa** [comment]
@gowthamkpr I was able to replicate the issue, please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/2b54197632d5b5e9e130a0f331e31c81/56448.ipynb#scrollTo=wyKHnXPDqKGk) for reference. Thank you!
