### ISSUE TITLE
Failed to load delegate from libedgetpu.so.1 M.2 Accelerator with Dual Edge TPU

### ISSUE THREAD

**Issue by tehniemer** [tensorflow/tensorflow#56451]
### Issue Type
Support
### Source
binary
### Tensorflow Version
2.9.1
### Custom Code
No
### OS Platform and Distribution
Debian GNU/Linux 11 (bullseye)
### Python version
3.9.2

### Current Behaviour?
The image classifier test from https://www.coral.ai/docs/m2/get-started/ fails. I had this coral device installed and working in Frigate for months before it quit.

### Standalone code to reproduce the issue
```shell
user@nvr:~/coral/pycoral$ python3 examples/classify_image.py --model test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels test_data/inat_bird_labels.txt --input test_data/parrot.jpg
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/coral/pycoral/examples/classify_image.py", line 121, in <module>
    main()
  File "/home/user/coral/pycoral/examples/classify_image.py", line 71, in main
    interpreter = make_interpreter(*args.model.split('@'))
  File "/usr/lib/python3/dist-packages/pycoral/utils/edgetpu.py", line 87, in make_interpreter
    delegates = [load_edgetpu_delegate({'device': device} if device else {})]
  File "/usr/lib/python3/dist-packages/pycoral/utils/edgetpu.py", line 52, in load_edgetpu_delegate
    return tflite.load_delegate(_EDGETPU_SHARED_LIB, options or {})
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1
```

### Any other info / logs
```shell
user@nvr:~/coral/pycoral$ ls /dev/apex_0
/dev/apex_0
```
```shell
user@nvr:/root$ lspci -nn | grep 089a
01:00.0 System peripheral [0880]: Global Unichip Corp. Coral Edge TPU [1ac1:089a]
```
```shell
root@nvr:~# dmesg | grep apex
[    3.313709] apex 0000:01:00.0: enabling device (0100 -> 0102)
[    3.314038] apex 0000:01:00.0: Couldn't initialize interrupts: -22
[    8.471106] apex 0000:01:00.0: Apex performance not throttled due to temperature
```
```shell
root@nvr:~# dmesg | grep 089a
[    0.315384] pci 0000:01:00.0: [1ac1:089a] type 00 class 0x0000ff
```
```shell
root@nvr:~# id user
uid=1000(user) gid=1000(user) groups=1000(user),24(cdrom),25(floppy),27(sudo),29(audio),30(dip),44(video),46(plugdev),107(render),109(netdev),1001(apex)
```

**Comment by mohantym** [comment]
Hi @techniemer! Could you follow these things and let us know. 

1. Ensure the Coral device is plugged in while inference is happening.
2. Check the permissions on your /dev/apex_0 device.
3. Add the user to plugdev group.

Attached a similar issue [1](https://github.com/tensorflow/tensorflow/issues/35054) and [2 ](https://github.com/tensorflow/tensorflow/issues/32743#issuecomment-543806766)with similar error stack trace .

Please post on Coral [Edge Tpu support ](https://github.com/google-coral/edgetpu/issues)for further assistance. 
Thank you!

**Comment by tehniemer** [comment]
@mohantym see https://github.com/google-coral/edgetpu/issues/611

**Comment by mohantym** [comment]
@tehniemer ! Could you please close this thread here. Thank you!
