### ISSUE TITLE
fixed issue

### ISSUE THREAD

**Issue by GravermanDev** [tensorflow/tensorflow#56500]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.9.1

### Custom Code

Yes

### OS Platform and Distribution

Windows 1-

### Python version

3.9.5

### Current Behaviour?

```shell
I wanted to train my machine learning model on this environment, unfortunately this bug appeared. I don't know if this is my issue or bug in Tensorflow's code
```

### Standalone code to reproduce the issue

```shell
from collections import Counter
from keras import layers
import numpy as np
import tensorflow as tf
from rl.agents.dqn import DQNAgent
from rl.policy import LinearAnnealedPolicy, EpsGreedyQPolicy
from rl.memory import SequentialMemory
import keras
import random
import gym

class Env(gym.Env):
    def __init__(self):
        self.observation_space = gym.spaces.MultiDiscrete([50 for _ in range(9)] + [60000, 60000, 60000])
        self.action_space = gym.spaces.Discrete(12)
        self.stepsLeft = 20000
        self.state = self.reset()
        # Step mapping is a varible showing what each action does, this prevents wall of 12 if statements
        # first 3 numbers are the row you take, second 3 is the one you perform the operation on, 7th number means either adding or substacting
        self.StepMapping = {0: [0, 1, 2, 3, 4, 5, -1], 1: [0, 1, 2, 6, 7, 8, -1], 2: [3, 4, 5, 0, 1, 2, -1],
                            3: [3, 4, 5, 6, 7, 8, -1], 4: [6, 7, 8, 0, 1, 2, -1], 5: [6, 7, 8, 3, 4, 5, 1],
                            6: [0, 1, 2, 3, 4, 5, 1], 7: [0, 1, 2, 6, 7, 8, 1], 8: [3, 4, 5, 0, 1, 2, 1],
                            9: [3, 4, 5, 6, 7, 8, 1], 10: [6, 7, 8, 0, 1, 2, 1], 11: [6, 7, 8, 3, 4, 5, 1]}

    def step(self, action):
        reward = -1
        done = False
        self.stepsLeft -= 1
        self.state[self.StepMapping[action][3]] += self.state[self.StepMapping[action][0]] * self.StepMapping[action][6]
        self.state[self.StepMapping[action][4]] += self.state[self.StepMapping[action][1]] * self.StepMapping[action][6]
        self.state[self.StepMapping[action][5]] += self.state[self.StepMapping[action][2]] * self.StepMapping[action][6]
        # this wierd reward system should make AI lean towards the solution and not astronomically big numbers
        wholeSystem = abs(self.state[0]) + abs(self.state[1]) + abs(self.state[2]) + abs(self.state[3]) + abs(
            self.state[4]) + abs(self.state[5]) + abs(self.state[6]) + abs(self.state[7]) + abs(self.state[8])
        if wholeSystem > 10000: reward = -10
        if wholeSystem < 400: reward = 1
        if wholeSystem < 200: reward = 5
        if wholeSystem < 100: reward = 10
        if wholeSystem < 50: reward = 20
        if self.stepsLeft == 0:
            done = True
        if self.done():
            done = True
            reward = 100000
            print("holy shit")
        return self.state, reward, done, {}

    def reset(self):
        # in case you don't understand my genius way of calling varibles:
        # lsq - left side of quation, rsq - right side of quation
        x, y, z = random.randint(0, 200), random.randint(0, 200), random.randint(0, 200)
        lsq = [random.randint(0, 49), random.randint(0, 49), random.randint(0, 49),
               random.randint(0, 49), random.randint(0, 49), random.randint(0, 49),
               random.randint(0, 49), random.randint(0, 49), random.randint(0, 49)]
        rsq = [lsq[0] * x + lsq[1] * y + lsq[2] * z,
               lsq[3] * x + lsq[4] * y + lsq[5] * z,
               lsq[6] * x + lsq[7] * y + lsq[8] * z]
        return lsq + rsq

    def done(self):
        state = [[self.state[0], self.state[1], self.state[2]], [self.state[3], self.state[4], self.state[5]], [self.state[6], self.state[7], self.state[8]]]
        found = [0, 1, 2]
        savedIndexes = []
        try:
            for i in range(3):
                if Counter(state[i])[0] == 2:
                    found.pop(found.index(2))
                    savedIndexes = np.where(np.array(state[i]) == 0)[0].tolist()
            for i in range(3):
                if 0 not in state[i]: found.pop(found.index(0))
                if Counter(state[i])[0] == 1:
                    if state[i].index(0) in savedIndexes:
                        found.pop(found.index(1))
                    else: return False
        except ValueError: return False
        if not found: return True
        else: return False

env = Env()

model = keras.Sequential()
model.add(layers.Flatten(input_shape=(1, 12)))
model.add(layers.Dense(256, activation='relu', batch_input_shape=(12,)))
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dense(12))

model.compile(loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
              optimizer=keras.optimizers.Adam(lr=0.001), metrics=["accuracy"])

policy = LinearAnnealedPolicy(EpsGreedyQPolicy(), attr='eps', value_max=1.0, value_min=0.1, value_test=0.2, nb_steps=10000)
memory = SequentialMemory(limit=50000, window_length=1)
DQN = DQNAgent(model=model, memory=memory, policy=policy, nb_actions=12, nb_steps_warmup=10, target_model_update=1e-2)

DQN.compile(tf.keras.optimizers.Adam(learning_rate=1e-4), metrics=['mae'])
DQN.fit(env, nb_steps=2000000, visualize=False, verbose=1)

model.save('workingmodel.h5')
scores = DQN.test(env, nb_episodes=1000000, visualize=True)
print(np.mean(scores.history['episode_reward']))
```

### Relevant log output

```shell
D:\PycharmProjects\AI\venv\lib\site-packages\keras\optimizers\optimizer_v2\adam.py:110: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)
Training for 2000000 steps ...
Interval 1 (0 steps performed)
D:\PycharmProjects\AI\venv\lib\site-packages\keras\engine\training_v1.py:2067: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,
    1/10000 [..............................] - ETA: 14:50 - reward: 1.0000D:\PycharmProjects\AI\venv\lib\site-packages\rl\memory.py:37: UserWarning: Not enough entries to sample without replacement. Consider increasing your warm-up phase to avoid oversampling!
  warnings.warn('Not enough entries to sample without replacement. Consider increasing your warm-up phase to avoid oversampling!')
D:\PycharmProjects\AI\venv\lib\site-packages\rl\memory.py:38: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  batch_idxs = np.random.random_integers(low, high - 1, size=size)
   12/10000 [..............................] - ETA: 6:11 - reward: -0.6667D:\PycharmProjects\AI\venv\lib\site-packages\rl\memory.py:38: DeprecationWarning: This function is deprecated. Please call randint(1, 11 + 1) instead
  batch_idxs = np.random.random_integers(low, high - 1, size=size)
D:\PycharmProjects\AI\venv\lib\site-packages\rl\memory.py:38: DeprecationWarning: This function is deprecated. Please call randint(1, 12 + 1) instead
  batch_idxs = np.random.random_integers(low, high - 1, size=size)
D:\PycharmProjects\AI\venv\lib\site-packages\rl\memory.py:38: DeprecationWarning: This function is deprecated. Please call randint(1, 13 + 1) instead
  batch_idxs = np.random.random_integers(low, high - 1, size=size)
D:\PycharmProjects\AI\venv\lib\site-packages\rl\memory.py:38: DeprecationWarning: This function is deprecated. Please call randint(1, 14 + 1) instead
  batch_idxs = np.random.random_integers(low, high - 1, size=size)
D:\PycharmProjects\AI\venv\lib\site-packages\rl\memory.py:38: DeprecationWarning: This function is deprecated. Please call randint(1, 15 + 1) instead
  batch_idxs = np.random.random_integers(low, high - 1, size=size)
D:\PycharmProjects\AI\venv\lib\site-packages\rl\memory.py:38: DeprecationWarning: This function is deprecated. Please call randint(1, 16 + 1) instead
  batch_idxs = np.random.random_integers(low, high - 1, size=size)
D:\PycharmProjects\AI\venv\lib\site-packages\rl\memory.py:38: DeprecationWarning: This function is deprecated. Please call randint(1, 17 + 1) instead
  batch_idxs = np.random.random_integers(low, high - 1, size=size)
   29/10000 [..............................] - ETA: 3:25 - reward: -0.8621D:\PycharmProjects\AI\venv\lib\site-packages\rl\memory.py:38: DeprecationWarning: This function is deprecated. Please call randint(1, 18 + 1) instead
  batch_idxs = np.random.random_integers(low, high - 1, size=size)
D:\PycharmProjects\AI\venv\lib\site-packages\rl\memory.py:38: DeprecationWarning: This function is deprecated. Please call randint(1, 19 + 1) instead
  batch_idxs = np.random.random_integers(low, high - 1, size=size)
D:\PycharmProjects\AI\venv\lib\site-packages\rl\memory.py:38: DeprecationWarning: This function is deprecated. Please call randint(1, 20 + 1) instead
  batch_idxs = np.random.random_integers(low, high - 1, size=size)
D:\PycharmProjects\AI\venv\lib\site-packages\rl\memory.py:38: DeprecationWarning: This function is deprecated. Please call randint(1, 21 + 1) instead
  batch_idxs = np.random.random_integers(low, high - 1, size=size)
D:\PycharmProjects\AI\venv\lib\site-packages\rl\memory.py:38: DeprecationWarning: This function is deprecated. Please call randint(1, 22 + 1) instead
  batch_idxs = np.random.random_integers(low, high - 1, size=size)
D:\PycharmProjects\AI\venv\lib\site-packages\rl\memory.py:38: DeprecationWarning: This function is deprecated. Please call randint(1, 23 + 1) instead
  batch_idxs = np.random.random_integers(low, high - 1, size=size)
D:\PycharmProjects\AI\venv\lib\site-packages\rl\memory.py:38: DeprecationWarning: This function is deprecated. Please call randint(1, 24 + 1) instead
  batch_idxs = np.random.random_integers(low, high - 1, size=size)
D:\PycharmProjects\AI\venv\lib\site-packages\rl\memory.py:38: DeprecationWarning: This function is deprecated. Please call randint(1, 25 + 1) instead
  batch_idxs = np.random.random_integers(low, high - 1, size=size)
D:\PycharmProjects\AI\venv\lib\site-packages\rl\memory.py:38: DeprecationWarning: This function is deprecated. Please call randint(1, 26 + 1) instead
  batch_idxs = np.random.random_integers(low, high - 1, size=size)
D:\PycharmProjects\AI\venv\lib\site-packages\rl\memory.py:38: DeprecationWarning: This function is deprecated. Please call randint(1, 27 + 1) instead
  batch_idxs = np.random.random_integers(low, high - 1, size=size)
D:\PycharmProjects\AI\venv\lib\site-packages\rl\memory.py:38: DeprecationWarning: This function is deprecated. Please call randint(1, 28 + 1) instead
  batch_idxs = np.random.random_integers(low, high - 1, size=size)
D:\PycharmProjects\AI\venv\lib\site-packages\rl\memory.py:38: DeprecationWarning: This function is deprecated. Please call randint(1, 29 + 1) instead
  batch_idxs = np.random.random_integers(low, high - 1, size=size)
D:\PycharmProjects\AI\venv\lib\site-packages\rl\memory.py:38: DeprecationWarning: This function is deprecated. Please call randint(1, 30 + 1) instead
  batch_idxs = np.random.random_integers(low, high - 1, size=size)
D:\PycharmProjects\AI\venv\lib\site-packages\rl\memory.py:38: DeprecationWarning: This function is deprecated. Please call randint(1, 31 + 1) instead
  batch_idxs = np.random.random_integers(low, high - 1, size=size)
 6720/10000 [===================>..........] - ETA: 25s - reward: -9.9231Traceback (most recent call last):
File "D:\PycharmProjects\AI\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-0e6266aa34dd>", line 1, in <cell line: 1>
    runfile('D:/PycharmProjects/AI/Linear Algebra AI.py', wdir='D:/PycharmProjects/AI')
  File "D:\JetBrains\PyCharm Community Edition 2021.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\JetBrains\PyCharm Community Edition 2021.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/PycharmProjects/AI/Linear Algebra AI.py", line 95, in <module>
    DQN.fit(env, nb_steps=2000000, visualize=False, verbose=1)
  File "D:\PycharmProjects\AI\venv\lib\site-packages\rl\core.py", line 168, in fit
    action = self.forward(observation)
  File "D:\PycharmProjects\AI\venv\lib\site-packages\rl\agents\dqn.py", line 224, in forward
    q_values = self.compute_q_values(state)
  File "D:\PycharmProjects\AI\venv\lib\site-packages\rl\agents\dqn.py", line 68, in compute_q_values
    q_values = self.compute_batch_q_values([state]).flatten()
  File "D:\PycharmProjects\AI\venv\lib\site-packages\rl\agents\dqn.py", line 63, in compute_batch_q_values
    q_values = self.model.predict_on_batch(batch)
  File "D:\PycharmProjects\AI\venv\lib\site-packages\keras\engine\training_v1.py", line 1200, in predict_on_batch
    outputs = self.predict_function(inputs)
  File "D:\PycharmProjects\AI\venv\lib\site-packages\keras\backend.py", line 4269, in __call__
    array_vals.append(np.asarray(value,
OverflowError: int too large to convert to float
```
</details>

**Comment by GravermanDev** [comment]
I found the issue, my environment had a bug and the observation was too big of a number
