### ISSUE TITLE
UNKNOWN: KeyError: 331 in `tf.data.Dataset`

### ISSUE THREAD

**Issue by gcuder** [tensorflow/tensorflow#56517]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.9.1

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.8

### CUDA/cuDNN version

11.2

### GPU model and memory

NVIDIA GTX 2080Ti

### Current Behaviour?

```shell
During training using a data pipeline constructed with `tf.data.Dataset.from_generator(...)` an error occurs stochastically. The error does not interrupt the training but still I cannot find the issue in my code.
```

### Standalone code to reproduce the issue

```shell
import functools
import os

import numpy as np
import tensorflow as tf
from itranslate.text_models.utility.data_reading import load_records, parse_example
from tensorflow.python.data.ops.options import AutoShardPolicy

NUM_TRAIN_SAMPLES = 1000
NUM_DEV_SAMPLES = 10

def get_dataset(split: str, batch_size: int, max_length: int = 64):
    # Number generator
    def generator():
        for i in range(num_samples):
            _dims = np.random.randint(low=1, high=max_length, size=1)
            x = np.zeros(_dims, dtype=np.int32) + np.random.randint(low=1, high=5000, size=1)
            y = np.zeros(_dims, dtype=np.int32) + np.random.randint(low=1, high=5000, size=1)
            yield {'sources': x, 'targets': y}

    assert split in ("train", "dev")
    is_training = split == "train"

    num_samples = NUM_TRAIN_SAMPLES if is_training else NUM_DEV_SAMPLES
    options = tf.data.Options()
    options.experimental_distribute.auto_shard_policy = AutoShardPolicy.DATA
    options.experimental_deterministic = False
    dataset = tf.data.Dataset.from_generator(
        lambda: generator(),
        output_signature={
            'sources': tf.TensorSpec(shape=(None,), dtype=tf.int32),
            'targets': tf.TensorSpec(shape=(None,), dtype=tf.int32)
        }
    ).with_options(options=options)

    dataset = dataset.padded_batch(batch_size=batch_size)

    def map_to_example(example):
        sources, targets = example['sources'], example['targets']
        return sources, targets

    dataset = dataset.map(map_to_example, num_parallel_calls=tf.data.AUTOTUNE)

    if is_training:
        dataset = dataset.shuffle(buffer_size=256)

    return dataset.repeat().prefetch(tf.data.AUTOTUNE)


def main():
    max_length = 64

    train_batch_size = 64
    valid_batch_size = 16

    # noinspection PyArgumentEqualDefault
    strategy = tf.distribute.MirroredStrategy(devices=["GPU:0", "GPU:1"])
    with strategy.scope():
        optimizer = tf.keras.optimizers.Adam()
        # Model
        inputs = tf.keras.layers.Input(shape=(None,), dtype=tf.int32)
        x = inputs
        x = tf.keras.layers.Embedding(input_dim=5000,
                                      output_dim=64)(x)
        x = tf.keras.layers.Dense(5000)(x)
        model = tf.keras.Model(inputs=inputs, outputs=x)
        model.compile(loss='sparse_categorical_crossentropy', optimizer=optimizer)
        model.summary()

        train_data = get_dataset(
            split="train",
            batch_size=train_batch_size,
            max_length=max_length
        )

        valid_data = get_dataset(
            split="dev",
            batch_size=valid_batch_size,
            max_length=max_length,
        )

        model.fit(
            train_data,
            epochs=200,
            steps_per_epoch=5000,
            validation_data=valid_data,
            validation_steps=3
        )


if __name__ == '__main__':
    main()
```

### Relevant log output

```shell
5000/5000 [==============================] - ETA: 0s - loss: 5.93492022-06-21 07:14:06.835116: W tensorflow/core/framework/op_kernel.cc:1733] UNKNOWN: KeyError: 331
Traceback (most recent call last):

  File "/home/gc/miniconda3/envs/itranslate-translation-v2/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 270, in __call__
    ret = func(*args)

  File "/home/gc/miniconda3/envs/itranslate-translation-v2/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "/home/gc/miniconda3/envs/itranslate-translation-v2/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1132, in finalize_py_func
    generator_state.iterator_completed(iterator_id)

  File "/home/gc/miniconda3/envs/itranslate-translation-v2/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 853, in iterator_completed
    del self._iterators[self._normalize_id(iterator_id)]

KeyError: 331
```
</details>

**Comment by sachinprasadhs** [comment]
While reproducing your issue I'm getting` ModuleNotFoundError: No module named 'itranslate.text_models'` even after installing `pip install itranslate`, could you please share the colab gist. Thanks!

**Comment by gcuder** [comment]
Sorry, my bad. Here's the updated code

```python
import functools
import os

import numpy as np
import tensorflow as tf
from tensorflow.python.data.ops.options import AutoShardPolicy

NUM_TRAIN_SAMPLES = 1000
NUM_DEV_SAMPLES = 10

def get_dataset(split: str, batch_size: int, max_length: int = 64):
    # Number generator
    def generator():
        for i in range(num_samples):
            _dims = np.random.randint(low=1, high=max_length, size=1)
            x = np.zeros(_dims, dtype=np.int32) + np.random.randint(low=1, high=5000, size=1)
            y = np.zeros(_dims, dtype=np.int32) + np.random.randint(low=1, high=5000, size=1)
            yield {'sources': x, 'targets': y}

    assert split in ("train", "dev")
    is_training = split == "train"

    num_samples = NUM_TRAIN_SAMPLES if is_training else NUM_DEV_SAMPLES
    options = tf.data.Options()
    options.experimental_distribute.auto_shard_policy = AutoShardPolicy.DATA
    options.experimental_deterministic = False
    dataset = tf.data.Dataset.from_generator(
        lambda: generator(),
        output_signature={
            'sources': tf.TensorSpec(shape=(None,), dtype=tf.int32),
            'targets': tf.TensorSpec(shape=(None,), dtype=tf.int32)
        }
    ).with_options(options=options)

    dataset = dataset.padded_batch(batch_size=batch_size)

    def map_to_example(example):
        sources, targets = example['sources'], example['targets']
        return sources, targets

    dataset = dataset.map(map_to_example, num_parallel_calls=tf.data.AUTOTUNE)

    if is_training:
        dataset = dataset.shuffle(buffer_size=256)

    return dataset.repeat().prefetch(tf.data.AUTOTUNE)


def main():
    max_length = 64

    train_batch_size = 64
    valid_batch_size = 16

    # noinspection PyArgumentEqualDefault
    strategy = tf.distribute.MirroredStrategy(devices=["GPU:0", "GPU:1"])
    with strategy.scope():
        optimizer = tf.keras.optimizers.Adam()
        # Model
        inputs = tf.keras.layers.Input(shape=(None,), dtype=tf.int32)
        x = inputs
        x = tf.keras.layers.Embedding(input_dim=5000,
                                      output_dim=64)(x)
        x = tf.keras.layers.Dense(5000)(x)
        model = tf.keras.Model(inputs=inputs, outputs=x)
        model.compile(loss='sparse_categorical_crossentropy', optimizer=optimizer)
        model.summary()

        train_data = get_dataset(
            split="train",
            batch_size=train_batch_size,
            max_length=max_length
        )

        valid_data = get_dataset(
            split="dev",
            batch_size=valid_batch_size,
            max_length=max_length,
        )

        model.fit(
            train_data,
            epochs=200,
            steps_per_epoch=5000,
            validation_data=valid_data,
            validation_steps=3
        )


if __name__ == '__main__':
    main()
```

**Comment by sachinprasadhs** [comment]
I'm able to run without any error for the initial epoch, please find the attached gist [here](https://colab.sandbox.google.com/gist/sachinprasadhs/e74dbd43e7908140956bf71e10ad06d7/untitled65.ipynb). Thanks!
