### ISSUE TITLE
alueError: `validation_split` is only supported for Tensors or NumPy arrays, found following types in the input: [<class 'int'>]

### ISSUE THREAD

**Issue by kusumlata123** [tensorflow/tensorflow#56544]
### Issue Type

Bug

### Source

source

### Tensorflow Version

tensorflow version 2.4.0

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 20.0

### Python version

python 3.7.6

### Current Behaviour?

```shell
thesre should be no error because  x_train and y_train both are <class 'numpy.ndarray'>
<class 'numpy.ndarray'>
```

### Standalone code to reproduce the issue

```shell
rint('Build model...')
    # posEmbeddings = np.identity(len(pos2Idx)+3, dtype='float32') 
    # print("posEmbeddings")
    # print(posEmbeddings)
    # print("posEmbeddings shape")
    # print(posEmbeddings.shape)
    # #print(type(pos_tag_train))
    # word embedding layersplit_data_train_test(X_word, pos_tag, label) 
    print("shape of train data")
    print(X_word_train.shape)
    print("Word input layer")
    word_in = tf.keras.Input(shape=(max_len,), name='words_input')
    print("shape of word_in")
    print(word_in.shape)
    print("word_in")
    print(word_in)
    #word_in_1 =tf.keras.layers.Dense(8, activation='relu')(word_in)
    print("word embedding layer")
    emb_word = PretrainedwordembedLayer(word_in)
    print("emd_word")
    print( emb_word)
    
    # input and embeddings for characters
    print("Character input layer")
    char_in = tf.keras.Input(shape=(max_len, max_len_char,),name='char_input')
    print("character embedding layer")
    emb_char = TimeDistributed(Embedding(input_dim=n_chars + 2, output_dim=20,input_length=max_len_char, mask_zero=True))(char_in)
    print("character embedding")
    print(emb_char.shape)
    # character LSTM to get word encodings by characters
    print("character LSTM to get word encodings by characters")
    char_enc = TimeDistributed(LSTM(units=40, return_sequences=False,recurrent_dropout=0))(emb_char)
    print("char_enc")
    print(char_enc.shape)
   
    # main LSTM
    print("main LSTM")
    x = keras.layers.concatenate([emb_word, char_enc])
    x = SpatialDropout1D(0.3)(x)
    main_lstm = Bidirectional(LSTM(units=200, return_sequences=True, recurrent_dropout=0))(x)
    out = TimeDistributed(Dense(n_tags+1, activation="softmax"))(main_lstm)
    #crf = CRF(n_tags+1)
    #out1=crf(out)
    model =  tf.compat.v1.keras.Model([word_in, char_in], out)    
    
    #Train the model
    print("Train the model")
    model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=['accuracy'])
    model.summary()
    

    y_train=np.array(y_train)
    print(y_train[1])
    X_word_train=np.array(X_word_train)
    X_char_train=np.array(X_char_train)
    print(type(X_word_train))
    print(type(X_char_train))


    print(" y_train shape")
    print(y_train.shape)
    history = model.fit([X_word_train,X_char_train.reshape((len(X_char_train),max_len,max_len_char)), max_len], y_train.reshape(len(y_train),max_len,1), batch_size=5, epochs=50, validation_split=0.2, verbose=1)
    
    plt.show()
    lstm_y_pred = model.predict([np.array(X_word_test),np.array(X_char_test).reshape((len(X_char_test),max_len,max_len_char))])
    print("LSTM predicted")
```

### Relevant log output

```shell
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
 y_train shape
(2745, 100)
Traceback (most recent call last):
  File "MDLSTM7withoutpos.py", line 340, in <module>
    model_build(input_file)
  File "MDLSTM7withoutpos.py", line 259, in model_build
    history = model.fit([X_word_train,X_char_train.reshape((len(X_char_train),max_len,max_len_char)), max_len], y_train.reshape(len(y_train),max_len,1), batch_size=5, epochs=50, validation_split=0.2, verbose=1, validation_steps=1)
  File "/home/dr/anaconda3/envs/MENT/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1041, in fit
    (x, y, sample_weight), validation_split=validation_split))
  File "/home/dr/anaconda3/envs/MENT/lib/python3.7/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 1359, in train_validation_split
    "arrays, found following types in the input: {}".format(unsplitable))
ValueError: `validation_split` is only supported for Tensors or NumPy arrays, found following types in the input: [<class 'int'>]
```

**Comment by tilakrayal** [comment]
Hi @kusumlata123,
Tensorflow version 2.4 not actively supported. Hence, kindly update to latest stable version 2.9 and let us know if you are facing the same issue. Thank you!

**Comment by coder330** [comment]
ValueError: `validation_split` is only supported for Tensors or NumPy arrays, found following types in the input: [<class 'int'>]
how to resolve this error

Please guide me to resolve this error.
Mentioned the code below:
X = X/255.0
model = Sequential()
model.add(Conv2D(64, (3,3), input_shape = X.shape[1:]))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Conv2D(64, (3,3)))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(64))
model.add(Dense(1))
model.add(Activation('sigmoid'))
model.compile(optimizer="adam",loss = "CategoricalCrossentropy",metrics=["accuracy"],)
model.fit(X,y, batch_size = 32, epochs = 10, validation_split=0.1 )
