### ISSUE TITLE
Issue with building Tensorflow with NCCL from source

### ISSUE THREAD

**Issue by kamalbowselvam** [tensorflow/tensorflow#56554]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

Ubuntu 20.04.4 LTS (Focal Fossa)

### Python version

3.8.10

### Bazel version

5.1.1

### GCC/Compiler version

9.4.0

### CUDA/cuDNN version

Cuda 11.6 / cuDNN 8.4.1

### GPU model and memory

Tesla P100-PCIE-12GB

### Current Behaviour?

```shell
I am trying to build TensorFlow from source on my ubuntu machine. I installed bazel and configured everything properly for CUDA. When I run 


bazel build -c opt //tensorflow:libtensorflow_cc
```
I get the following error: 

```
INFO: Build option --define has changed, discarding analysis cache.
ERROR: /data/softs/tensorflow/tensorflow/BUILD:1153:21: in cc_shared_library rule //tensorflow:libtensorflow_cc.so.2.10.0: 
Traceback (most recent call last):
        File "/virtual_builtins_bzl/common/cc/experimental_cc_shared_library.bzl", line 416, column 105, in _cc_shared_library_impl
        File "/virtual_builtins_bzl/common/cc/experimental_cc_shared_library.bzl", line 340, column 37, in _filter_inputs
        File "/virtual_builtins_bzl/common/cc/experimental_cc_shared_library.bzl", line 360, column 9, in _throw_error_if_unaccounted_libs
Error in fail: The following libraries cannot be linked either statically or dynamically:
@nccl_archive//:nccl
@nccl_archive//:device
@nccl_archive//:net
@nccl_archive//:include_hdrs
@nccl_archive//:src_hdrs
To ignore which libraries get linked statically for now, add the following to 'static_deps':
        "@nccl_archive//:__subpackages__",
ERROR: /data/softs/tensorflow/tensorflow/BUILD:1153:21: Analysis of target '//tensorflow:libtensorflow_cc.so.2.10.0' failed
ERROR: Analysis of target '//tensorflow:tensorflow_cc' failed; build aborted: 
INFO: Elapsed time: 6.706s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 28476 targets configured)

```
but when I run with --config=nonccl, everything works fine. Could some one tell me why I getting this error for NCCL and how to fix. 

I also installed nccl-local-repo-ubuntu2004-2.12.12-cuda11.6_1.0-1_amd64 on my machine successfully but still I am not able to build with NCCL.
```


### Standalone code to reproduce the issue

```shell
1) Download Tensorflow and configure it with bazel for CUDA 
2) Run bazel build -c opt //tensorflow:tensorflow_cc
```

### Relevant log output

```shell
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=161
INFO: Reading rc options for 'build' from /data/softs/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /data/softs/tensorflow/.bazelrc:
  'build' options: --define framework_shared_object=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library --experimental_link_static_libraries_once=false
INFO: Reading rc options for 'build' from /data/softs/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env PYTHON_LIB_PATH=/usr/lib/python3.8/dist-packages --python_path=/usr/bin/python3 --config=tensorrt --action_env CUDA_TOOLKIT_PATH=/usr/local/cuda-11.6 --action_env TF_CUDA_COMPUTE_CAPABILITIES=3.5,7.0 --action_env LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64 --action_env GCC_HOST_COMPILER_PATH=/usr/bin/x86_64-linux-gnu-gcc-9 --config=cuda
INFO: Reading rc options for 'build' from /data/softs/tensorflow/.bazelrc:
  'build' options: --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/ir,tensorflow/compiler/mlir/tfrt/tests/analysis,tensorflow/compiler/mlir/tfrt/tests/jit,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_tfrt,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_jitrt,tensorflow/compiler/mlir/tfrt/tests/tf_to_corert,tensorflow/compiler/mlir/tfrt/tests/tf_to_tfrt_data,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/common,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/graph_executor,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
INFO: Found applicable config definition build:short_logs in file /data/softs/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /data/softs/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:tensorrt in file /data/softs/tensorflow/.bazelrc: --repo_env TF_NEED_TENSORRT=1
INFO: Found applicable config definition build:cuda in file /data/softs/tensorflow/.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
INFO: Found applicable config definition build:linux in file /data/softs/tensorflow/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++17 --host_cxxopt=-std=c++17 --config=dynamic_kernels --distinct_host_configuration=false --experimental_guard_against_concurrent_changes
INFO: Found applicable config definition build:dynamic_kernels in file /data/softs/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
INFO: Build option --define has changed, discarding analysis cache.
ERROR: /data/softs/tensorflow/tensorflow/BUILD:1153:21: in cc_shared_library rule //tensorflow:libtensorflow_cc.so.2.10.0: 
Traceback (most recent call last):
        File "/virtual_builtins_bzl/common/cc/experimental_cc_shared_library.bzl", line 416, column 105, in _cc_shared_library_impl
        File "/virtual_builtins_bzl/common/cc/experimental_cc_shared_library.bzl", line 340, column 37, in _filter_inputs
        File "/virtual_builtins_bzl/common/cc/experimental_cc_shared_library.bzl", line 360, column 9, in _throw_error_if_unaccounted_libs
Error in fail: The following libraries cannot be linked either statically or dynamically:
@nccl_archive//:nccl
@nccl_archive//:device
@nccl_archive//:net
@nccl_archive//:include_hdrs
@nccl_archive//:src_hdrs
To ignore which libraries get linked statically for now, add the following to 'static_deps':
        "@nccl_archive//:__subpackages__",
ERROR: /data/softs/tensorflow/tensorflow/BUILD:1153:21: Analysis of target '//tensorflow:libtensorflow_cc.so.2.10.0' failed
ERROR: Analysis of target '//tensorflow:tensorflow_cc' failed; build aborted: 
INFO: Elapsed time: 6.706s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 28476 targets configured)
```
</details>

**Comment by chunduriv** [comment]
@kamalbowselvam,

Could you try with tested build configurations as shown below and let us know?

![image](https://user-images.githubusercontent.com/74177924/175481112-27f6e1fa-8b68-4c6b-9724-d5b3de3d909d.png)

Thank you.

**Comment by kamalbowselvam** [comment]
Hi, 


I tried to build with the above mentioned configuration and i am getting this error: 

Tensorflow - 2.9.0
Python - 3.8 
GCC - 9.4.0
Bazel - 5.0.0 
CUDA - 11.2
cuDNN - 8.1


```
ERROR: An error occurred during the fetch of repository 'llvm-raw':
   Traceback (most recent call last):
        File "/tensorflow/third_party/repo.bzl", line 64, column 33, in _tf_http_archive_impl
                ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz, https://github.com/llvm/llvm-project/archive/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz] to /root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/external/llvm-raw/temp15505930333885082835/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz: Read timed out
ERROR: /tensorflow/WORKSPACE:11:14: fetching _tf_http_archive rule //external:llvm-raw: Traceback (most recent call last):
        File "/tensorflow/third_party/repo.bzl", line 64, column 33, in _tf_http_archive_impl
                ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz, https://github.com/llvm/llvm-project/archive/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz] to /root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/external/llvm-raw/temp15505930333885082835/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz: Read timed out
INFO: Found applicable config definition build:cuda in file /tensorflow/.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
ERROR: @local_config_cuda//:enable_cuda :: Error loading option @local_config_cuda//:enable_cuda: no such package '@llvm-raw//utils/bazel': java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz, https://github.com/llvm/llvm-project/archive/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz] to /root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/external/llvm-raw/temp15505930333885082835/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz: Read timed out
````

The given http link given for llvm seems to be not available. Could you please tell how to fix this ?

**Comment by chunduriv** [comment]
@kamalbowselvam,

The timeout issue is due to github. Note that the .zip version of the same URL works fine. Try changing [this line](https://github.com/tensorflow/tensorflow/blob/master/third_party/llvm/workspace.bzl#L16) to .zip should work. Thank you.

**Comment by kamalbowselvam** [comment]
It worked, Thank you for helping me with this.
