### ISSUE TITLE
tf.scatter_nd doesn't support int32 updates when some indices are out of bounds

### ISSUE THREAD

**Issue by wangwei-cmd** [tensorflow/tensorflow#56567]
### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf2.6

### Custom Code

Yes

### OS Platform and Distribution

win10

### Python version

3.9

### Current Behaviour?

```shell
When the type of updates is int32 and some of the indices are out of bound, tf.scatter_nd can't return the expected value.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

print(tf.scatter_nd(tf.constant([[0],[1],[2]]), tf.constant([10,11,12],dtype=tf.int32), [5]))
print(tf.scatter_nd(tf.constant([[-1],[1],[2]]), tf.constant([10,11,12],dtype=tf.float32), [5]))
print(tf.scatter_nd(tf.constant([[-1],[1],[2]]), tf.constant([10,11,12],dtype=tf.int32), [5]))
```

### Relevant log output

```shell
tf.Tensor([10 11 12  0  0], shape=(5,), dtype=int32)
tf.Tensor([ 0. 11. 12.  0.  0.], shape=(5,), dtype=float32)
2022-06-24 23:12:02.730401: W tensorflow/core/framework/op_kernel.cc:1692] OP_REQUIRES failed at scatter_nd_op.cc:130 : Invalid argument: indices[0] = [-1] does not index into shape [5]
print(tf.scatter_nd(tf.constant([[-1],[1],[2]]), tf.constant([10,11,12],dtype=tf.int32), [5]))
  File "D:\miniconda\envs\tf2.6\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 9006, in scatter_nd
    return scatter_nd_eager_fallback(
  File "D:\miniconda\envs\tf2.6\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 9049, in scatter_nd_eager_fallback   
    _result = _execute.execute(b"ScatterNd", 1, inputs=_inputs_flat,
  File "D:\miniconda\envs\tf2.6\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0] = [-1] does not index into shape [5] [Op:ScatterNd]
```

**Comment by tilakrayal** [comment]
Hi @chunduriv,
I was able to reproduce the issue on tensorflow v2.8, v2.9 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/b4c866ae706d36dada73ff9d71230ba7/56567.ipynb).

**Comment by chunduriv** [comment]
@wangwei-cmd,

According to [scatter_nd](https://www.tensorflow.org/api_docs/python/tf/scatter_nd) documentation -

> Note that on CPU, if an out of bound index is found, an error is returned. On GPU, if an out of bound index is found, the index is ignored.

On windows using `TF2.9.1` the `tf.scatter_nd` doesn't support if some indices are out of bounds.

>>>
>>> print(tf.scatter_nd(tf.constant([[-1],[1],[2]]), tf.constant([10,11,12],dtype=tf.float32), [5]))
2022-07-01 17:18:04.169866: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at scatter_nd_op.cc:131 : INVALID_ARGUMENT: indices[0] = [-1] does not index into shape [5]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\XXXXXXXX\.conda\envs\tf\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 9166, in scatter_nd
    return scatter_nd_eager_fallback(
  File "C:\Users\XXXXXXXX\.conda\envs\tf\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 9215, in scatter_nd_eager_fallback
    _result = _execute.execute(b"ScatterNd", 1, inputs=_inputs_flat,
  File "C:\Users\CV00616867\.conda\envs\tf\lib\site-packages\tensorflow\python\eager\execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0] = [-1] does not index into shape [5] [Op:ScatterNd]

>>> print(tf.scatter_nd(tf.constant([[-1],[1],[2]]), tf.constant([10,11,12],dtype=tf.int32), [5]))
2022-07-01 17:18:07.161196: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at scatter_nd_op.cc:131 : INVALID_ARGUMENT: indices[0] = [-1] does not index into shape [5]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\XXXXXXXX\.conda\envs\tf\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 9166, in scatter_nd
    return scatter_nd_eager_fallback(
  File "C:\Users\XXXXXXXX\.conda\envs\tf\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 9215, in scatter_nd_eager_fallback
    _result = _execute.execute(b"ScatterNd", 1, inputs=_inputs_flat,
  File "C:\Users\XXXXXXXX\.conda\envs\tf\lib\site-packages\tensorflow\python\eager\execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0] = [-1] does not index into shape [5] [Op:ScatterNd]

**Comment by hrbigelow** [comment]
I can confirm this is the case, not just for `tf.scatter_nd` but for `tf.tensor_scatter_nd_{add,max,min,sub,update}`.

However, the bug only occurs when `params` is type int32.  If `indices` (and `shape`) are type int32, but `params` is either `int64`, `float32`, `float64`, it works:

```
idx32 = tf.cast(idx_ten, dtype=tf.int32)
idx64 = tf.cast(idx_ten, dtype=tf.int64)
sh32 = tf.cast(shape_ten, dtype=tf.int32)
sh64 = tf.cast(shape_ten, dtype=tf.int64)
upd32 = tf.cast(upd_ten, dtype=tf.int32)
upd64 = tf.cast(upd_ten, dtype=tf.int64)
updf32 = tf.cast(upd_ten, dtype=tf.float32)
updf64 = tf.cast(upd_ten, dtype=tf.float64)

# integer type for index and shape must match:
ipdb> tf.scatter_nd(idx64, updf64, sh32)
*** tensorflow.python.framework.errors_impl.InvalidArgumentError: cannot compute ScatterNd as input #2(zero-based) was expected to be a int64 tensor but is a int32 tensor [Op:ScatterNd]

# all of these work  (using float32, float64, or int64 updates)
tf.scatter_nd(idx32, updf32, sh32)
tf.scatter_nd(idx32, upd64, sh32) 
tf.scatter_nd(idx32, updf64, sh32)
tf.scatter_nd(idx64, upd64, sh64)
tf.scatter_nd(idx64, updf32, sh64)
tf.scatter_nd(idx64, updf64, sh64)

# using int32 for the updates does not work (for either int32 or int64 indices and shape)
tf.scatter_nd(idx32, upd32, sh32)
2022-07-11 12:08:21.502263: W tensorflow/core/framework/op_kernel.cc:1692] OP_REQUIRES failed at scatter_nd_op.cc:130 : Invalid argument: indices[1,0] = [-1] does not index into shape [8]
*** tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[1,0] = [-1] does not index into shape [8] 
tf.scatter_nd(idx64, upd32, sh64)
2022-07-11 12:08:49.281631: W tensorflow/core/framework/op_kernel.cc:1692] OP_REQUIRES failed at scatter_nd_op.cc:130 : Invalid argument: indices[1,0] = [-1] does not index into shape [8]
*** tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[1,0] = [-1] does not index into shape [8]
```

I looked at the code, and cannot tell what could be the problem.  This is the only line in which the kernel is sensitive to the update (and output) type `T`: [Here](https://github.com/tensorflow/tensorflow/blob/79e24d571d6a52dba0c7c563b079fcc5ba462e88/tensorflow/core/kernels/scatter_nd_op_gpu.cu.cc#L118)  

or 4th line from bottom.  Any ideas?  I would also like to solve this bug.

```c++

template <typename T, typename Index, scatter_nd_op::UpdateOp op, int IXDIM>
__global__ void ScatterNdOpKernel(
    const Index* indices, const T* updates, T* out,
    const Eigen::array<Eigen::DenseIndex, IXDIM> output_shape_prefix,
    const Eigen::array<int64, IXDIM> batch_strides, const int64 num_indices,
    const Index slice_size) {
  auto update = LeftUpdate<T, op>();

  GPU_1D_KERNEL_LOOP(index, num_indices) {
    Index i = 0;
    bool out_of_bounds = false;
#pragma unroll
    for (int dim = 0; dim < IXDIM; ++dim) {
      int offset = (IXDIM * index + dim);
      const Index ix_d = internal::SubtleMustCopy(ldg(indices + offset));
      out_of_bounds |= !FastBoundsCheck(ix_d, output_shape_prefix[dim]);
      i += ix_d * batch_strides[dim] * slice_size;
    }
    if (!out_of_bounds) {
#pragma unroll
      for (int si = 0; si < slice_size; si++) {
        update(out + i + si, ldg(updates + (index * slice_size + si)));
      }
    }
  }

```

**Comment by hrbigelow** [comment]
My vote would be to change the CPU behavior to be like the GPU behavior, with a possible non-default fallback to the old behavior.  It is hard to imagine users who actually rely on the CPU behavior, because then they would not be able to run their model on GPU at all without accepting the different behavior.  So, although technically this is a change in behavior, my guess is there will be almost no-one who would object to this change.

Thoughts?
