### ISSUE TITLE
Compiled code executes wrong branch

### ISSUE THREAD

**Issue by jesnie** [tensorflow/tensorflow#56560]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.9.1

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 18.04.6 LTS

### Python version

3.10.4

### Current Behaviour?

```shell
When I compile my code with `tf.function` it tries to execute the wrong branch of an if-statement, leading to a crash.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf


def inner_dim(x):
    shape = tf.shape(x)
    if tf.size(shape) > 0:
        return shape[-1]
    else:
        return tf.ones((), dtype=shape.dtype)


compiled_inner_dim = tf.function(inner_dim)

small_tensor = tf.ones(())
large_tensor = tf.ones((2,))

print("--------------------------------------------------")
print(inner_dim(large_tensor))  # Works.
print("--------------------------------------------------")
print(inner_dim(small_tensor))  # Works.
print("--------------------------------------------------")
print(compiled_inner_dim(large_tensor))  # Works.
print("--------------------------------------------------")
print(compiled_inner_dim(small_tensor))  # slice index -1 of dimension 0 out of bounds.
print("--------------------------------------------------")
```

### Relevant log output

```shell
2022-06-24 09:54:35.277941: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-06-24 09:54:35.277971: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: jesper-desktop
2022-06-24 09:54:35.277980: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: jesper-desktop
2022-06-24 09:54:35.278030: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 495.29.5
2022-06-24 09:54:35.278050: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 495.29.5
2022-06-24 09:54:35.278057: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 495.29.5
2022-06-24 09:54:35.278256: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
--------------------------------------------------
tf.Tensor(2, shape=(), dtype=int32)
--------------------------------------------------
tf.Tensor(1, shape=(), dtype=int32)
--------------------------------------------------
tf.Tensor(2, shape=(), dtype=int32)
--------------------------------------------------
Traceback (most recent call last):
  File "/home/jesper/src/GPflow/test_wtf.py", line 23, in <module>
    print(compiled_inner_dim(small_tensor))
  File "/home/jesper/src/GPflow/.venv/max310/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/tmp/__autograph_generated_fileyqfznmym.py", line 36, in tf__inner_dim
    ag__.if_stmt(ag__.converted_call(ag__.ld(tf).size, (ag__.ld(shape),), None, fscope) > 0, if_body, else_body, get_state, set_state, ('do_return', 'retval_'), 2)
  File "/tmp/__autograph_generated_fileyqfznmym.py", line 23, in if_body
    retval_ = ag__.ld(shape)[-1]
ValueError: in user code:

    File "/home/jesper/src/GPflow/test_wtf.py", line 7, in inner_dim  *
        return shape[-1]

    ValueError: slice index -1 of dimension 0 out of bounds. for '{{node cond/strided_slice}} = StridedSlice[Index=DT_INT32, T=DT_INT32, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1](cond/strided_slice/Shape, cond/strided_slice/stack, cond/strided_slice/stack_1, cond/strided_slice/stack_2)' with input shapes: [0], [1], [1], [1] and with computed input tensors: input[1] = <-1>, input[2] = <0>, input[3] = <1>.
```
</details>

**Comment by mohantym** [comment]
Hi @gowthamkpr ! Could you look at this issue. Attached gist in [2.8](https://colab.sandbox.google.com/gist/mohantym/c04e7b15ca831b543ea14fa7da700090/git_56560.ipynb), [2.9](https://colab.sandbox.google.com/gist/mohantym/c4e7e2b3f1a3e4b22f6047cf4e1a8e39/git_56560.ipynb#scrollTo=sjy3FKvOTAS2) and [nightly.](https://colab.sandbox.google.com/gist/mohantym/7db5c5d80214436c64f833f38d62d4b1/git_56560.ipynb#scrollTo=sjy3FKvOTAS2) Thank you!

**Comment by bhack** [comment]
Have you tried to use `len(shape)` instead of `tf.size`?
