### ISSUE TITLE
ImportError: ../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found

### ISSUE THREAD

**Issue by AnkS4** [tensorflow/tensorflow#56562]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.8

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 16.04

### Python version

3.8.5

### GCC/Compiler version

gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609

### Current Behaviour?

```shell
Failed to load the native TensorFlow runtime.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/aimluser/miniconda3/envs/application_env/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", lin
e 60, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: /home/aimluser/miniconda3/envs/application_env/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (requ
ired by /home/aimluser/miniconda3/envs/application_env/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_interna
l.so)

During handling of the above exception, another exception occurred:

import tensorflow as tf
  File "/home/aimluser/miniconda3/envs/application_env/lib/python3.8/site-packages/tensorflow/__init__.py", line 37, in <module
>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/aimluser/miniconda3/envs/application_env/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 36, in 
<module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/home/aimluser/miniconda3/envs/application_env/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", lin
e 75, in <module>
    raise ImportError(
ImportError: Traceback (most recent call last):
  File "/home/aimluser/miniconda3/envs/application_env/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", lin
e 60, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: /home/aimluser/miniconda3/envs/application_env/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (requ
ired by /home/aimluser/miniconda3/envs/application_env/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_interna
l.so)


Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors for some common causes and solutions.
If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above t
his error message.
```
</details>

**Comment by gadagashwini** [comment]
Hi @AnkS4, GCC version required for Tensorflow v2.6 is 7.3.1. Take a look at similar issue thread [here](https://stackoverflow.com/questions/54948216/usr-lib-x86-64-linux-gnu-libstdc-so-6-version-glibcxx-3-4-21-not-found-req). Thank you!
