### ISSUE TITLE
Why does object-detection script require audio software?

### ISSUE THREAD

**Issue by Russ76** [tensorflow/tensorflow#56576]
This is from lite/examples/object_detection/raspberry_pi

Is something mixed up with the efficientdet_lite model? It gives me a fatal error for not finding PortAudio library! But i wanted to do object detection with the camera! Earlier, in the setup phase, it seemed satisfied with my installed software.

steve@raspberrypi:~/examples/tensorflow_examples/examples/lite/examples/object_detection/raspberry_pi $ python3 detect.py \
  --model efficientdet_lite0.tflite
Traceback (most recent call last):
  File "/home/steve/examples/tensorflow_examples/examples/lite/examples/object_detection/raspberry_pi/detect.py", line 20, in <module>
    from tflite_support.task import core
  File "/home/steve/.local/lib/python3.9/site-packages/tflite_support/__init__.py", line 53, in <module>
    from tflite_support import task
  File "/home/steve/.local/lib/python3.9/site-packages/tflite_support/task/__init__.py", line 28, in <module>
    from . import audio
  File "/home/steve/.local/lib/python3.9/site-packages/tflite_support/task/audio/__init__.py", line 20, in <module>
    from tensorflow_lite_support.python.task.audio import audio_classifier
  File "/home/steve/.local/lib/python3.9/site-packages/tensorflow_lite_support/python/task/audio/audio_classifier.py", line 18, in <module>
    from tensorflow_lite_support.python.task.audio.core import audio_record
  File "/home/steve/.local/lib/python3.9/site-packages/tensorflow_lite_support/python/task/audio/core/audio_record.py", line 17, in <module>
    import sounddevice as sd
  File "/home/steve/.local/lib/python3.9/site-packages/sounddevice.py", line 71, in <module>
    raise OSError('PortAudio library not found')
OSError: PortAudio library not found

**Comment by Russ76** [comment]
Well, I installed libportaudio2 and this cured the problem. I don't know why Tensorflow Lite core must load audio modules, when it is memory constrained, but there you have it. It must want the complete Swiss army knife.

**Comment by khanhlvg** [comment]
We've fixed the issue with audio dependency in the master branch. You can try it with `pip install tflite-support-nightly`. It'll be available in the next stable release (0.4.2)
