### ISSUE TITLE
tensorflow:AutoGraph could not transform lambda and will run it as-is.

### ISSUE THREAD

**Issue by DerGodoot** [tensorflow/tensorflow#56593]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.4.1

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 22.04

### Python version

3.9.12

### Current Behaviour?

```shell
I zipped 2 tf.data.Dataset and filtered the new dataset based on the first value in the resulting tuples.
This worked, but gave me a warning and asked me to report this to the tensoflow team.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import pandas as pd
import numpy as np


tf.autograph.set_verbosity(10,alsologtostdout=True)
in_size_test = 5
df_test =pd.DataFrame(range(1,18))
df_test_y = pd.DataFrame([range(2,19),range(3,20)]).transpose()

ds_debug1= tf.keras.preprocessing.timeseries_dataset_from_array(
    data=df_test, 
    targets = np.roll(df_test_y, shift=-in_size_test+1,axis=0),
    sequence_length=in_size_test, 
    sequence_stride=1, 
    sampling_rate=1,
    shuffle=False)

ds_debug2= tf.keras.preprocessing.timeseries_dataset_from_array(
    data=df_test, 
    targets = np.roll(df_test_y, shift=-in_size_test+1,axis=0),
    sequence_length=in_size_test, 
    sequence_stride=1, 
    sampling_rate=1,
    shuffle=False)
ds_debug = tf.data.Dataset.zip((ds_debug1, ds_debug2)).unbatch()

ds_debug.filter(lambda z1,z2:tf.math.reduce_any(z1[0][0] == 5))
```

### Relevant log output

```shell
python debug.py 
2022-06-27 15:32:46.330009: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-06-27 15:32:46.330175: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-06-27 15:32:46.330983: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
Converted call: <function timeseries_dataset_from_array.<locals>.<lambda> at 0x7f04d2bae310>
    args: (<tf.Tensor 'args_0:0' shape=() dtype=int64>, <tf.Tensor 'args_1:0' shape=(13,) dtype=int32>)
    kwargs: {}

Allowlisted: <function timeseries_dataset_from_array.<locals>.<lambda> at 0x7f04d2bae310>: DoNotConvert rule for tensorflow
Converted call: <function sequences_from_indices.<locals>.<lambda> at 0x7f04d2baeee0>
    args: (<tf.Tensor 'args_0:0' shape=(17, 1) dtype=int64>, <tf.Tensor 'args_1:0' shape=(None,) dtype=int32>)
    kwargs: {}

Allowlisted: <function sequences_from_indices.<locals>.<lambda> at 0x7f04d2baeee0>: DoNotConvert rule for tensorflow
Converted call: <function timeseries_dataset_from_array.<locals>.<lambda> at 0x7f04cceb5040>
    args: (<tf.Tensor 'args_0:0' shape=() dtype=int64>, <tf.Tensor 'args_1:0' shape=(13,) dtype=int32>)
    kwargs: {}

Allowlisted: <function timeseries_dataset_from_array.<locals>.<lambda> at 0x7f04cceb5040>: DoNotConvert rule for tensorflow
Converted call: <function sequences_from_indices.<locals>.<lambda> at 0x7f04cceb5310>
    args: (<tf.Tensor 'args_0:0' shape=(17, 2) dtype=int64>, <tf.Tensor 'args_1:0' shape=() dtype=int32>)
    kwargs: {}

Allowlisted: <function sequences_from_indices.<locals>.<lambda> at 0x7f04cceb5310>: DoNotConvert rule for tensorflow
Converted call: <function timeseries_dataset_from_array.<locals>.<lambda> at 0x7f04cceb5a60>
    args: (<tf.Tensor 'args_0:0' shape=() dtype=int64>, <tf.Tensor 'args_1:0' shape=(13,) dtype=int32>)
    kwargs: {}

Allowlisted: <function timeseries_dataset_from_array.<locals>.<lambda> at 0x7f04cceb5a60>: DoNotConvert rule for tensorflow
Converted call: <function sequences_from_indices.<locals>.<lambda> at 0x7f04cceb5af0>
    args: (<tf.Tensor 'args_0:0' shape=(17, 1) dtype=int64>, <tf.Tensor 'args_1:0' shape=(None,) dtype=int32>)
    kwargs: {}

Allowlisted: <function sequences_from_indices.<locals>.<lambda> at 0x7f04cceb5af0>: DoNotConvert rule for tensorflow
Converted call: <function timeseries_dataset_from_array.<locals>.<lambda> at 0x7f04ccee3160>
    args: (<tf.Tensor 'args_0:0' shape=() dtype=int64>, <tf.Tensor 'args_1:0' shape=(13,) dtype=int32>)
    kwargs: {}

Allowlisted: <function timeseries_dataset_from_array.<locals>.<lambda> at 0x7f04ccee3160>: DoNotConvert rule for tensorflow
Converted call: <function sequences_from_indices.<locals>.<lambda> at 0x7f04ccee31f0>
    args: (<tf.Tensor 'args_0:0' shape=(17, 2) dtype=int64>, <tf.Tensor 'args_1:0' shape=() dtype=int32>)
    kwargs: {}

Allowlisted: <function sequences_from_indices.<locals>.<lambda> at 0x7f04ccee31f0>: DoNotConvert rule for tensorflow
Converted call: <function normalize_to_dense.<locals>.normalize at 0x7f04ccee35e0>
    args: ((<tf.Tensor 'args_0:0' shape=(None, None, 1) dtype=int64>, <tf.Tensor 'args_1:0' shape=(None, 2) dtype=int64>), (<tf.Tensor 'args_2:0' shape=(None, None, 1) dtype=int64>, <tf.Tensor 'args_3:0' shape=(None, 2) dtype=int64>))
    kwargs: {}

Allowlisted: <function normalize_to_dense.<locals>.normalize at 0x7f04ccee35e0>: DoNotConvert rule for tensorflow
Converted call: <function <lambda> at 0x7f04ccee3820>
    args: ((<tf.Tensor 'args_0:0' shape=(None, 1) dtype=int64>, <tf.Tensor 'args_1:0' shape=(2,) dtype=int64>), (<tf.Tensor 'args_2:0' shape=(None, 1) dtype=int64>, <tf.Tensor 'args_3:0' shape=(2,) dtype=int64>))
    kwargs: {}

Not allowed: <method-wrapper '__call__' of function object at 0x7f04ccee3820>: default rule
Not allowed: <function <lambda> at 0x7f04ccee3820>: default rule
<function <lambda> at 0x7f04ccee3820> is not cached for subkey ConversionOptions[{}]
Source code of <function <lambda> at 0x7f04ccee3820>:

lambda z1,z2:tf.math.reduce_any(z1[0][0] == 5)

Error transforming entity <function <lambda> at 0x7f04ccee3820>
Traceback (most recent call last):
  File "/home/mspils/anaconda3/envs/wl/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 447, in converted_call
    converted_f = _convert_actual(target_entity, program_ctx)
  File "/home/mspils/anaconda3/envs/wl/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 284, in _convert_actual
    transformed, module, source_map = _TRANSPILER.transform(entity, program_ctx)
  File "/home/mspils/anaconda3/envs/wl/lib/python3.9/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 286, in transform
    return self.transform_function(obj, user_context)
  File "/home/mspils/anaconda3/envs/wl/lib/python3.9/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 470, in transform_function
    nodes, ctx = super(PyToPy, self).transform_function(fn, user_context)
  File "/home/mspils/anaconda3/envs/wl/lib/python3.9/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 363, in transform_function
    result = self.transform_ast(node, context)
  File "/home/mspils/anaconda3/envs/wl/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 252, in transform_ast
    node = self.initial_analysis(node, ctx)
  File "/home/mspils/anaconda3/envs/wl/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 239, in initial_analysis
    node = qual_names.resolve(node)
  File "/home/mspils/anaconda3/envs/wl/lib/python3.9/site-packages/tensorflow/python/autograph/pyct/qual_names.py", line 252, in resolve
    return QnResolver().visit(node)
  File "/home/mspils/anaconda3/envs/wl/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/home/mspils/anaconda3/envs/wl/lib/python3.9/ast.py", line 492, in generic_visit
    new_node = self.visit(old_value)
  File "/home/mspils/anaconda3/envs/wl/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/home/mspils/anaconda3/envs/wl/lib/python3.9/ast.py", line 483, in generic_visit
    value = self.visit(value)
  File "/home/mspils/anaconda3/envs/wl/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/home/mspils/anaconda3/envs/wl/lib/python3.9/ast.py", line 492, in generic_visit
    new_node = self.visit(old_value)
  File "/home/mspils/anaconda3/envs/wl/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/home/mspils/anaconda3/envs/wl/lib/python3.9/site-packages/tensorflow/python/autograph/pyct/qual_names.py", line 230, in visit_Subscript
    node = self.generic_visit(node)
  File "/home/mspils/anaconda3/envs/wl/lib/python3.9/ast.py", line 492, in generic_visit
    new_node = self.visit(old_value)
  File "/home/mspils/anaconda3/envs/wl/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/home/mspils/anaconda3/envs/wl/lib/python3.9/site-packages/tensorflow/python/autograph/pyct/qual_names.py", line 232, in visit_Subscript
    if not isinstance(s, gast.Index):
AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:AutoGraph could not transform <function <lambda> at 0x7f04ccee3820> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING: AutoGraph could not transform <function <lambda> at 0x7f04ccee3820> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
```
</details>

**Comment by sushreebarsa** [comment]
@DerGodoot I tried to replicate the issue on colab, could you please find the [gist](https://colab.research.google.com/gist/sushreebarsa/dbe1f45da0e936b8456b669cf722ab7d/56593.ipynb#scrollTo=TJANtabLyOF_) and confirm the issue?
Thank you!

**Comment by DerGodoot** [comment]
@sushreebarsa Ah alright, looks like the old TF version was the issue.
Maybe change the warning to only create issued if the used version is the most current one? :)
Just saying "Please report this to the TensorFlow team." seems like it could create lots of unnecessarily opened issues.

**Comment by sushreebarsa** [comment]
@DerGodoot Thank you for the update! Could you please let us know if this reported issue is resolved ?
Thank you!
