### ISSUE TITLE
InvalidArgumentError: Removed XLA support for adding ragged Tensors in TF 2.9

### ISSUE THREAD

**Issue by SebastianCa** [tensorflow/tensorflow#56595]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9.1

### Custom Code

Yes

### Current Behaviour?

```shell
Adding two ragged Tensors in XLA mode does not work anymore in TF 2.9 (the same code works until TF 2.8). 

Please note that it seems this is not just related to the addition, the same happens for the element-wise multiplication and a similar behaviour can be even observed for tf.broadcast().

I have the impression this issue only occurs if the ragged dimension is located between two non-ragged dimensions.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
print('Tensorflow version: ', tf.__version__)

outer_dim = 7 # arbitrary
inner_dim = 2 # arbitrary
row_splits = [0, 1, 3, outer_dim] # some random splits
rt_shape = [outer_dim, inner_dim]

def run_graph():   

    x = tf.RaggedTensor.from_row_splits(
                values=tf.ones(rt_shape, dtype=tf.float32),
                row_splits=row_splits)
    
    y = tf.RaggedTensor.from_row_splits(
                values=tf.ones(rt_shape, dtype=tf.float32),
                row_splits=row_splits)

    print("Shape of x:", x.shape)
    print("Shape of y:", y.shape)

    z = tf.add(x, y) # this add causes the problem (with XLA)
    print("Shape of z:", z.shape)
    return z

print("---Running in Graph mode---")
tf.function(run_graph)()

print("\n---Running in XLA mode---")
tf.function(run_graph, jit_compile=True)()
```

### Relevant log output

```shell
Tensorflow version:  2.9.1
---Running in Graph mode---
Shape of x: (3, None, 2)
Shape of y: (3, None, 2)
Shape of z: (3, None, 2)

---Running in XLA mode---
Shape of x: (3, None, 2)
Shape of y: (3, None, 2)
Shape of z: (3, None, 2)
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
/home/projects/XLA_RT_BUG.ipynb Cell 3' in <module>
     24 tf.function(run_graph)()
     26 print("\n---Running in XLA mode---")
---> 27 tf.function(run_graph, jit_compile=True)()

[...]

InvalidArgumentError: Detected unsupported operations when trying to compile graph __inference_run_graph_2782[_XlaMustCompile=true,config_proto=9241198235816212909,executor_type=11160318154034397263] on XLA_GPU_JIT: RaggedRange (No registered 'RaggedRange' OpKernel for XLA_GPU_JIT devices compatible with node {{node RaggedRange_2}}){{node RaggedRange_2}}
The op is created at: 

[...]

File "<ipython-input-4-00ab54ea3ce6>", line 27, in <module>
  tf.function(run_graph, jit_compile=True)()
File "<ipython-input-4-00ab54ea3ce6>", line 19, in run_graph
  z = tf.add(x, y) # this add causes the problem (with XLA) [Op:__inference_run_graph_2782]
```
</details>

**Comment by tilakrayal** [comment]
@chunduriv,
I was able to reproduce the issue. Code works fine with TF v2.8, whereas with TF v2.9 and TF-nightly the code got executed with error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/fae1d2764a2ed37893e78538d548377f/56595-cpu.ipynb). Thank you!

**Comment by cheshire** [comment]
I don't think RaggedTensors ever worked in XLA - what HLO did they produce?

**Comment by SebastianCa** [comment]
I would like to reopen this issue as it has not been solved.

> I don't think RaggedTensors ever worked in XLA - what HLO did they produce?

The above example works in TF <=2.8, i.e., RaggedTensors have been supported in XLA in the past.

**Comment by cheshire** [comment]
They've never been; it must have been a bug it did not error out before.
