### ISSUE TITLE
ImportError: dlopen(/Users/nurujjamanpollob/miniforge3/lib/python3.9/site-packages/tensorflow/python/_pywrap_dtensor_device.so, 0x0002): Symbol not found: __ZN10tensorflow31MaybeRaiseExceptionFromTFStatusEP9TF_StatusP7_object

### ISSUE THREAD

**Issue by nurujjamanpollob** [tensorflow/tensorflow#56616]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Source

binary

### Tensorflow Version

2.7.0

### Custom Code

Yes

### OS Platform and Distribution

macOS 12.4 on M1 Pro ARM64

### Python version

3.9

### Current Behaviour?

```shell
ImportError: dlopen(/Users/nurujjamanpollob/miniforge3/lib/python3.9/site-packages/tensorflow/python/_pywrap_dtensor_device.so, 0x0002): Symbol not found: __ZN10tensorflow31MaybeRaiseExceptionFromTFStatusEP9TF_StatusP7_object
  Referenced from: /Users/nurujjamanpollob/miniforge3/lib/python3.9/site-packages/tensorflow/python/_pywrap_dtensor_device.so
  Expected in: /Users/nurujjamanpollob/miniforge3/lib/python3.9/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
```

### Standalone code to reproduce the issue

```shell
import tensorflow as ts
import numpy as np

from tensorflow.keras import Sequential as Sq
from tensorflow.keras.layers import Dense as Den
from tensorflow.keras.layers import MaxPooling2D as Max
from tensorflow.keras.layers import Conv2D as conv

# Entry point of python programme
from callbacks.TrainingEpochCallback import EpochCallBack


def program_entry():
    # Get inbuilt dataset
    data = ts.keras.datasets.fashion_mnist

    # Tuples of training data sets by calling load_data() method
    (training_images, training_labels), (test_images, test_labels) = data.load_data()

    # Create a new array, of 'training_images' pixel representation, each pixel range is between 0 - 255, so divide
    # Each of them array element with 255, should make it under zero and one, this is called normalizing the image
    # it will help ML model enhance performance
    training_images = training_images / 255.0

    # Create a new array, of 'training_images' pixel representation, each pixel range is between 0 - 255, so divide
    # Each of them array element with 255, should make it under zero and one, this is called normalizing the image
    # it will help ML model enhance performance
    test_images = test_images / 255.0

    # Create a Sequential model instance with a simple Neural Network Layer
    # That contains 128 layer and 128 neuron
    l0 = [
        conv(64, (3, 3), activation='relu', input_shape=(28, 28, 1)),
        Max(pool_size=(2, 2)),
        conv(64, (3, 3), activation='relu'),
        Max(pool_size=(2, 2)),
        ts.keras.layers.Flatten(),
        Den(128, activation='relu'),
        Den(10, activation='softmax')
    ]

    model = Sq(l0)

    # Configures the model for training
    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    # Trains the model for a fixed number of epochs (iterations on a dataset)
    model.fit(training_images, training_labels, epochs=50)

    # Evaluate the model with test data set
    model.evaluate(test_images, test_labels)

    # Make prediction on test data set
    classifications = model.predict(test_images)
    print(classifications[0])
    print(test_labels[0])


# Press the green button in the gutter to run the script.
if __name__ == '__main__':
    # Entry point to program
    program_entry()
```

### Relevant log output

```shell
Users/nurujjamanpollob/miniforge3/bin/python /Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevconsole.py --mode=client --port=51223
import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['/Volumes/Projects/learning/Four-K-Pixel-AI'])
PyDev console: starting.
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:00:33) 
[Clang 13.0.1 ] on darwin
runfile('/Volumes/Projects/learning/Four-K-Pixel-AI/main.py', wdir='/Volumes/Projects/learning/Four-K-Pixel-AI')
Traceback (most recent call last):
  File "/Users/nurujjamanpollob/miniforge3/lib/python3.9/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Volumes/Projects/learning/Four-K-Pixel-AI/main.py", line 4, in <module>
    from tensorflow.keras import Sequential as Sq
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/nurujjamanpollob/miniforge3/lib/python3.9/site-packages/keras/api/_v2/keras/__init__.py", line 12, in <module>
    from keras import __version__
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/nurujjamanpollob/miniforge3/lib/python3.9/site-packages/keras/__init__.py", line 24, in <module>
    from keras import models
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/nurujjamanpollob/miniforge3/lib/python3.9/site-packages/keras/models/__init__.py", line 18, in <module>
    from keras.engine.functional import Functional
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/nurujjamanpollob/miniforge3/lib/python3.9/site-packages/keras/engine/functional.py", line 24, in <module>
    from keras.dtensor import layout_map as layout_map_lib
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/nurujjamanpollob/miniforge3/lib/python3.9/site-packages/keras/dtensor/__init__.py", line 22, in <module>
    from tensorflow.compat.v2.experimental import dtensor as dtensor_api  # pylint: disable=g-import-not-at-top
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/nurujjamanpollob/miniforge3/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v2/experimental/dtensor/__init__.py", line 8, in <module>
    from tensorflow.dtensor.python.api import call_with_layout
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/nurujjamanpollob/miniforge3/lib/python3.9/site-packages/tensorflow/dtensor/python/__init__.py", line 18, in <module>
    from tensorflow.dtensor.python import mesh_util
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/nurujjamanpollob/miniforge3/lib/python3.9/site-packages/tensorflow/dtensor/python/mesh_util.py", line 21, in <module>
    from tensorflow.dtensor.python import api
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/nurujjamanpollob/miniforge3/lib/python3.9/site-packages/tensorflow/dtensor/python/api.py", line 22, in <module>
    from tensorflow.dtensor.python import dtensor_device
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/nurujjamanpollob/miniforge3/lib/python3.9/site-packages/tensorflow/dtensor/python/dtensor_device.py", line 28, in <module>
    from tensorflow.python import _pywrap_dtensor_device
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: dlopen(/Users/nurujjamanpollob/miniforge3/lib/python3.9/site-packages/tensorflow/python/_pywrap_dtensor_device.so, 0x0002): Symbol not found: __ZN10tensorflow31MaybeRaiseExceptionFromTFStatusEP9TF_StatusP7_object
  Referenced from: /Users/nurujjamanpollob/miniforge3/lib/python3.9/site-packages/tensorflow/python/_pywrap_dtensor_device.so
  Expected in: /Users/nurujjamanpollob/miniforge3/lib/python3.9/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
```
</details>

**Comment by nurujjamanpollob** [comment]
> @nurujjamanpollob, I was able to execute the provided code without any errors/issue. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/346aeb07154fca3b95c79d1377189ae3/untitled405.ipynb) and let us know if the issues still persists. Thank you!

Okay, it seems reinstalling miniforge and tensorflow and numpy fixed this issue. Thank you 🥰

**Comment by tilakrayal** [comment]
@nurujjamanpollob,
Glad the issue is resolved for you, please feel free to move this to closed status. Thank you!

**Comment by nurujjamanpollob** [comment]
If anyone faces the same issue:

Reinstall miniforge, to do so, you need to delete the `miniforge3` directory using this command: 

`rm -rf ~/miniforge3`

You need to check your `SHELL` name. In that case, run `echo $SHELL` to check the shell name. In my case, it is` /bin/zsh `so my SHELL is `zsh`

The below command is for `zsh`

cd to /Users/<username> and run this command: `sudo vim .zshrc`

So, you will be able to see the content inside .zshrc file, now find this code fragment, and delete it:

<pre>
<code>
 #>>> conda initialize >>>
   #!! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/nurujjamanpollob/miniforge3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/nurujjamanpollob/miniforge3/etc/profile.d/conda.sh" ]; then
        . "/Users/nurujjamanpollob/miniforge3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/nurujjamanpollob/miniforge3/bin:$PATH"
    fi
fi
unset __conda_setup
#<<< conda initialize <<<
</code>
</pre>
hit **esc** and then **:x** enter to save changes.

then run this command:

`source .zshrc`

To reinstall miniforge to install the TensorFlow package on mac, follow instructions from this URL: [https://www.machinecoderguy.com/setup-your-development-environment-for-tensorflow/](url)
