### ISSUE TITLE
tensorflow.python.compiler.tensorrt converter build Bert model error

### ISSUE THREAD

**Issue by Jiayuli-CU** [tensorflow/tensorflow#56708]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9.1 (git version: v2.9.0-18-gd8ce9f9c301)

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 18.04

### Python version

3.8

### CUDA/cuDNN version

CUDA 11.4

### Current Behaviour?

```shell
A bug happened when convert a pre-trained bert model to tensorRT using converter.build() inside the tensorflow.python.compiler.tensorrt package. When I remove the line converter.build(), the converted model is successfully saved, but same error happens when I tried to inference the converted model with:

iterator = iter(test_dataset.take(1))
x = iterator.next()[0]['input_ids']
converted_model = tf.saved_model.load('models/bert-fp32')
infer = converted_model.signatures['serving_default']
output_layer = list(infer.structured_outputs.keys())[0]
infer(input_ids=x)[output_layer]
```

### Standalone code to reproduce the issue

```shell
import numpy as np
import os

import tensorflow as tf
import tensorflow_datasets as tfds
from tensorflow.python.compiler.tensorrt import trt_convert as trt
from transformers import (BertTokenizer, TFBertForSequenceClassification,
                          glue_convert_examples_to_features)

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

data = tfds.load('glue/mrpc')
train_dataset = glue_convert_examples_to_features(data['train'], tokenizer, max_length=128, task='mrpc').batch(1)
test_dataset = glue_convert_examples_to_features(data['test'], tokenizer, max_length=128, task='mrpc').batch(1)

model_raw = TFBertForSequenceClassification.from_pretrained('bert-base-uncased')
optimizer = tf.keras.optimizers.Adam(learning_rate=3e-5)
loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
model_raw.compile(optimizer=optimizer, loss=loss, metrics=['accuracy'])
model_raw.fit(train_dataset, epochs=10, steps_per_epoch=115, shuffle=True)
model_raw.save('models/bert-raw')

def input_fn():
    input_shapes = [[(1, 128)],[(1, 128)],[(4, 128)]]
    for shapes in input_shapes:
        yield [np.zeros(x, dtype=np.int32) for x in shapes]

conversion_params = trt.TrtConversionParams(
    precision_mode=trt.TrtPrecisionMode.FP32
)
converter = trt.TrtGraphConverterV2(
    input_saved_model_dir='models/bert-raw',
    conversion_params=conversion_params
)
converter.convert()
converter.build(input_fn)
```

### Relevant log output

```shell
2022-07-08 03:24:55.251359: W tensorflow/compiler/tf2tensorrt/segment/segment.cc:1229] A total of 39 segments with at least minimum_segment_size=3 nodes have been found. TF-TRT will only convert the 20 largest segments. You can change this behavior by modifying the environment variable TF_TRT_MAX_ALLOWED_ENGINES=20
2022-07-08 03:24:55.252060: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:795] Number of TensorRT candidate segments: 20
2022-07-08 03:24:55.268302: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:909] Replaced segment 0 consisting of 13 nodes by TRTEngineOp_000_000.
2022-07-08 03:24:55.268416: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:909] Replaced segment 1 consisting of 13 nodes by TRTEngineOp_000_001.
2022-07-08 03:24:55.268518: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:909] Replaced segment 2 consisting of 13 nodes by TRTEngineOp_000_002.
2022-07-08 03:24:55.268599: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:909] Replaced segment 3 consisting of 13 nodes by TRTEngineOp_000_003.
2022-07-08 03:24:55.268676: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:909] Replaced segment 4 consisting of 13 nodes by TRTEngineOp_000_004.
2022-07-08 03:24:55.268752: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:909] Replaced segment 5 consisting of 13 nodes by TRTEngineOp_000_005.
2022-07-08 03:24:55.268856: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:909] Replaced segment 6 consisting of 13 nodes by TRTEngineOp_000_006.
2022-07-08 03:24:55.268933: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:909] Replaced segment 7 consisting of 13 nodes by TRTEngineOp_000_007.
2022-07-08 03:24:55.269024: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:909] Replaced segment 8 consisting of 13 nodes by TRTEngineOp_000_008.
2022-07-08 03:24:55.269103: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:909] Replaced segment 9 consisting of 13 nodes by TRTEngineOp_000_009.
2022-07-08 03:24:55.269176: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:909] Replaced segment 10 consisting of 13 nodes by TRTEngineOp_000_010.
2022-07-08 03:24:55.269270: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:909] Replaced segment 11 consisting of 13 nodes by TRTEngineOp_000_011.
2022-07-08 03:24:55.269358: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:909] Replaced segment 12 consisting of 13 nodes by TRTEngineOp_000_012.
2022-07-08 03:24:55.269433: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:909] Replaced segment 13 consisting of 13 nodes by TRTEngineOp_000_013.
2022-07-08 03:24:55.269522: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:909] Replaced segment 14 consisting of 13 nodes by TRTEngineOp_000_014.
2022-07-08 03:24:55.269595: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:909] Replaced segment 15 consisting of 13 nodes by TRTEngineOp_000_015.
2022-07-08 03:24:55.269664: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:909] Replaced segment 16 consisting of 12 nodes by TRTEngineOp_000_016.
2022-07-08 03:24:55.269735: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:909] Replaced segment 17 consisting of 13 nodes by TRTEngineOp_000_017.
2022-07-08 03:24:55.269821: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:909] Replaced segment 18 consisting of 13 nodes by TRTEngineOp_000_018.
2022-07-08 03:24:55.269905: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:909] Replaced segment 19 consisting of 13 nodes by TRTEngineOp_000_019.
2022-07-08 03:25:15.215526: W tensorflow/core/framework/op_kernel.cc:1733] INVALID_ARGUMENT: required broadcastable shapes
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
Input In [5], in <cell line: 15>()
     23 converter.convert()
     24 ###
---> 25 converter.build(input_fn)
     26 ###
     27 converter.save('models/bert-' + name)

File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/tensorflow/python/compiler/tensorrt/trt_convert.py:1316, in TrtGraphConverterV2.build(self, input_fn)
   1314     func(**{k: ops.convert_to_tensor(v) for k, v in inp.items()})
   1315   else:
-> 1316     func(*map(ops.convert_to_tensor, inp))
   1318 if self._need_trt_profiles():
   1319   # Disable profile generation.
   1320   self._for_each_trt_node(self._converted_graph_def,
   1321                           partial(_set_profile_generation_mode, False))

File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/tensorflow/python/eager/function.py:1602, in ConcreteFunction.__call__(self, *args, **kwargs)
   1552 def __call__(self, *args, **kwargs):
   1553   """Executes the wrapped function.
   1554 
   1555   ConcreteFunctions have two signatures:
   (...)
   1600     TypeError: If the arguments do not match the function's signature.
   1601   """
-> 1602   return self._call_impl(args, kwargs)

File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/tensorflow/python/eager/wrap_function.py:243, in WrappedFunction._call_impl(self, args, kwargs, cancellation_manager)
    241   return self._call_flat(args, self.captured_inputs)
    242 else:
--> 243   return super(WrappedFunction, self)._call_impl(
    244       args, kwargs, cancellation_manager)

File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/tensorflow/python/eager/function.py:1620, in ConcreteFunction._call_impl(self, args, kwargs, cancellation_manager)
   1617     except TypeError:
   1618       raise structured_err
-> 1620 return self._call_with_flat_signature(args, kwargs, cancellation_manager)

File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/tensorflow/python/eager/function.py:1669, in ConcreteFunction._call_with_flat_signature(self, args, kwargs, cancellation_manager)
   1664   if not isinstance(
   1665       arg, (ops.Tensor, resource_variable_ops.BaseResourceVariable)):
   1666     raise TypeError(f"{self._flat_signature_summary()}: expected argument "
   1667                     f"#{i}(zero-based) to be a Tensor; "
   1668                     f"got {type(arg).__name__} ({arg}).")
-> 1669 return self._call_flat(args, self.captured_inputs, cancellation_manager)

File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/tensorflow/python/eager/function.py:1860, in ConcreteFunction._call_flat(self, args, captured_inputs, cancellation_manager)
   1856 possible_gradient_type = gradients_util.PossibleTapeGradientTypes(args)
   1857 if (possible_gradient_type == gradients_util.POSSIBLE_GRADIENT_TYPES_NONE
   1858     and executing_eagerly):
   1859   # No tape is watching; skip to running the function.
-> 1860   return self._build_call_outputs(self._inference_function.call(
   1861       ctx, args, cancellation_manager=cancellation_manager))
   1862 forward_backward = self._select_forward_and_backward_functions(
   1863     args,
   1864     possible_gradient_type,
   1865     executing_eagerly)
   1866 forward_function, args_with_tangents = forward_backward.forward()

File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/tensorflow/python/eager/function.py:497, in _EagerDefinedFunction.call(self, ctx, args, cancellation_manager)
    495 with _InterpolateFunctionError(self):
    496   if cancellation_manager is None:
--> 497     outputs = execute.execute(
    498         str(self.signature.name),
    499         num_outputs=self._num_outputs,
    500         inputs=args,
    501         attrs=attrs,
    502         ctx=ctx)
    503   else:
    504     outputs = execute.execute_with_cancellation(
    505         str(self.signature.name),
    506         num_outputs=self._num_outputs,
   (...)
    509         ctx=ctx,
    510         cancellation_manager=cancellation_manager)

File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/tensorflow/python/eager/execute.py:54, in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     52 try:
     53   ctx.ensure_initialized()
---> 54   tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     55                                       inputs, attrs, num_outputs)
     56 except core._NotOkStatusException as e:
     57   if name is not None:

InvalidArgumentError: Graph execution error:

Detected at node 'StatefulPartitionedCall/tf_bert_for_sequence_classification/bert/embeddings/add/add' defined at (most recent call last):
    File "/anaconda/envs/azureml_py38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/anaconda/envs/azureml_py38/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/ipykernel_launcher.py", line 16, in <module>
      app.launch_new_instance()
    File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/traitlets/config/application.py", line 972, in launch_instance
      app.start()
    File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/ipykernel/kernelapp.py", line 677, in start
      self.io_loop.start()
    File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 199, in start
      self.asyncio_loop.run_forever()
    File "/anaconda/envs/azureml_py38/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
      self._run_once()
    File "/anaconda/envs/azureml_py38/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
      handle._run()
    File "/anaconda/envs/azureml_py38/lib/python3.8/asyncio/events.py", line 81, in _run
      self._context.run(self._callback, *self._args)
    File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 457, in dispatch_queue
      await self.process_one()
    File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 446, in process_one
      await dispatch(*args)
    File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 353, in dispatch_shell
      await result
    File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 648, in execute_request
      reply_content = await reply_content
    File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 353, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/ipykernel/zmqshell.py", line 533, in run_cell
      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
    File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2880, in run_cell
      result = self._run_cell(
    File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2935, in _run_cell
      return runner(coro)
    File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
      coro.send(None)
    File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3134, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3337, in run_ast_nodes
      if await self.run_code(code, result, async_=asy):
    File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3397, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "/tmp/ipykernel_89514/223432839.py", line 23, in <cell line: 15>
      converter.convert()
Node: 'StatefulPartitionedCall/tf_bert_for_sequence_classification/bert/embeddings/add/add'
required broadcastable shapes
	 [[{{node StatefulPartitionedCall/tf_bert_for_sequence_classification/bert/embeddings/add/add}}]] [Op:__inference_pruned_43829]
```
</details>

**Comment by sushreebarsa** [comment]
@Jiayuli-CU I tried to replicate the issue on colab and didn’t see the reported error. Please find the gist [here ](https://colab.research.google.com/gist/sushreebarsa/ead1c230590d7bf1eab221b051721bb0/56708.ipynb#scrollTo=xL4hoHwKlEL-)for reference and let me know if I'm missing something to reproduce the issue. Thank you!

**Comment by Jiayuli-CU** [comment]
@sushreebarsa Your code stops before converter.build() because certain packages are missing. You need to install TensorRT first. https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html

**Comment by gowthamkpr** [comment]
@Jiayuli-CU Please try using `tf.experimental.tensorrt.Converter` to convert your saved model. Please take a look at the doc [here](https://www.tensorflow.org/api_docs/python/tf/experimental/tensorrt/Converter). Please let me know if you are still running into the same error. Thanks!

**Comment by Jiayuli-CU** [comment]
> @Jiayuli-CU Please try using `tf.experimental.tensorrt.Converter` to convert your saved model. Please take a look at the doc [here](https://www.tensorflow.org/api_docs/python/tf/experimental/tensorrt/Converter). Please let me know if you are still running into the same error. Thanks!

Got the same error message after using `tf.experimental.tensorrt.Converter` follwing the official doc.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
