### ISSUE TITLE
fault_tolerance_test fails one some systems

### ISSUE THREAD

**Issue by Flamefire** [tensorflow/tensorflow#56717]
### Issue Type

Bug

### Source

source

### Tensorflow Version

2.7.1

### Custom Code

No

### OS Platform and Distribution

Linux RHEL 7

### Python version

3.9.6

### Bazel version

3.7.2

### GCC/Compiler version

11.2

### CUDA/cuDNN version

11.4.1 / cuDNN 8.2.2.26

### GPU model and memory

8 * Tesla A100

### Current Behaviour?

```shell
When running the test suite during/after the build the test `//tensorflow/python/data/experimental/kernel_tests/service:fault_tolerance_test` fails on this system, while it seemingly passes on another system.
It seems to be very flaky or dependent on the number of CPUs/GPUs. This system has 96 cores and 8 GPUs.
Output is something like
> //tensorflow/python/data/experimental/kernel_tests/service:fault_tolerance_test (2/20 cached) FAILED in 18 out of 20 in 13.5s
```

### Standalone code to reproduce the issue

```shell
Run the following build command: `bazel test --config=noaws --config=nogcp --config=nohdfs --compilation_mode=opt --config=opt --subcommands --verbose_failures --jobs=1 --distinct_host_configuration=false --test_output=errors --build_tests_only --local_test_jobs=1 -- //tensorflow/python/data/experimental/kernel_tests/service:fault_tolerance_test`
```

### Relevant log output

```shell
======================================================================
FAIL: testAddWorkerMidJob_test_mode_eager_tfapiversion_2 (__main__.FaultToleranceTest)
FaultToleranceTest.testAddWorkerMidJob_test_mode_eager_tfapiversion_2
testAddWorkerMidJob_test_mode_eager_tfapiversion_2(mode='eager', tf_api_version=2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/software/TensorFlow/2.7.1-foss-2021b-CUDA-11.4.1/lib/python3.9/site-packages/absl/testing/parameterized.py", line 314, in bound_param_test
    return test_method(self, **testcase_params)
  File "/dev/shm/s3248973-EasyBuild/TensorFlow/2.7.1/foss-2021b-CUDA-11.4.1/tmpBD23m_-bazel-tf/69a307561ec5a7cdace7b5c5a8971ea2/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/data/experimental/kernel_tests/service/fault_tolerance_test.runfiles/org_tensorflow/tensorflow/python/framework/test_combinations.py", line 366, in decorated
    execute_test_method()
  File "/dev/shm/s3248973-EasyBuild/TensorFlow/2.7.1/foss-2021b-CUDA-11.4.1/tmpBD23m_-bazel-tf/69a307561ec5a7cdace7b5c5a8971ea2/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/data/experimental/kernel_tests/service/fault_tolerance_test.runfiles/org_tensorflow/tensorflow/python/framework/test_combinations.py", line 349, in execute_test_method
    test_method(**kwargs_to_pass)
  File "/dev/shm/s3248973-EasyBuild/TensorFlow/2.7.1/foss-2021b-CUDA-11.4.1/tmpBD23m_-bazel-tf/69a307561ec5a7cdace7b5c5a8971ea2/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/data/experimental/kernel_tests/service/fault_tolerance_test.runfiles/org_tensorflow/tensorflow/python/data/experimental/kernel_tests/service/fault_tolerance_test.py", line 220, in testAddWorkerMidJob
    self.assertCountEqual(2 * list(range(num_elements)), results)
AssertionError: Element counts were not equal:
```

**Comment by Flamefire** [comment]
[Build output](https://github.com/tensorflow/tensorflow/files/9072881/tfBuild.log.txt) and [Test log file](https://github.com/tensorflow/tensorflow/files/9072882/tfTest.log.txt) of a test with `--test_env=CUDA_VISIBLE_DEVICES='1,2,3,4'`

See also https://github.com/tensorflow/tensorflow/commit/c08fda5cb7927acb5c20fa031c2d28f80d4a03c5 which disables this test on mac

**Comment by mohantym** [comment]
Hi @Flamefire !
Could you re-test with the below command and let us know .
`bazel test --config=noaws --config=nogcp --config=nohdfs --compilation_mode=opt -c opt --subcommands --verbose_failures --jobs=1 --distinct_host_configuration=false --test_output=errors --build_tests_only --local_test_jobs=1 -- //tensorflow/python/data/experimental/kernel_tests/service:fault_tolerance_test`

Attached gist in [2.9](https://colab.sandbox.google.com/gist/mohantym/aa9e8323c60bce58ea117b43995b3080/tensorflow-ranking.ipynb#scrollTo=_IQp1_gflTaC) for reference.
Thank you!

**Comment by Flamefire** [comment]
So the change is: `--config=opt` replaced by `-c opt`, correct?

Same issue. I also checked the Bazel output, started a new bash and set up the environment for this test as per the Bazel output, changed the CWD to `.../execroot/org_tensorflow/bazel-out/k8-opt/bin` and ran `tensorflow/python/data/experimental/kernel_tests/service/fault_tolerance_test`. Same error.

```
Ran 41 tests in 19.142s

FAILED (failures=1, errors=6, skipped=22)
```

From what I can tell the test is faulty. See for example this error log:
```
ERROR: testRestartWorker_test_mode_eager_tfapiversion_2_usesameport_True_faulttolerantmode_True_workdir_tmpworkdirplaceholder (__main__.FaultToleranceTest)
FaultToleranceTest.testRestartWorker_test_mode_eager_tfapiversion_2_usesameport_True_faulttolerantmode_True_workdir_tmpworkdirplaceholder
testRestartWorker_test_mode_eager_tfapiversion_2_usesameport_True_faulttolerantmode_True_workdir_tmpworkdirplaceholder(mode='eager', tf_api_version=2, use_same_port=True, fault_tolerant_mode=True, work_dir='tmp_work_dir_placeholder')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dev/shm/s3248973-EasyBuild/TensorFlow/2.7.1/foss-2021b-CUDA-11.4.1/tmp5xgzay-bazel-tf/69a307561ec5a7cdace7b5c5a8971ea2/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/data/experimental/kernel_tests/service/fault_tolerance_test.runfiles/org_tensorflow/tensorflow/python/data/ops/iterator_ops.py", line 800, in __next__
    return self._next_internal()
  File "/dev/shm/s3248973-EasyBuild/TensorFlow/2.7.1/foss-2021b-CUDA-11.4.1/tmp5xgzay-bazel-tf/69a307561ec5a7cdace7b5c5a8971ea2/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/data/experimental/kernel_tests/service/fault_tolerance_test.runfiles/org_tensorflow/tensorflow/python/data/ops/iterator_ops.py", line 783, in _next_internal
    ret = gen_dataset_ops.iterator_get_next(
  File "/dev/shm/s3248973-EasyBuild/TensorFlow/2.7.1/foss-2021b-CUDA-11.4.1/tmp5xgzay-bazel-tf/69a307561ec5a7cdace7b5c5a8971ea2/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/data/experimental/kernel_tests/service/fault_tolerance_test.runfiles/org_tensorflow/tensorflow/python/ops/gen_dataset_ops.py", line 2845, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/dev/shm/s3248973-EasyBuild/TensorFlow/2.7.1/foss-2021b-CUDA-11.4.1/tmp5xgzay-bazel-tf/69a307561ec5a7cdace7b5c5a8971ea2/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/data/experimental/kernel_tests/service/fault_tolerance_test.runfiles/org_tensorflow/tensorflow/python/framework/ops.py", line 7107, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence [Op:IteratorGetNext]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/software/TensorFlow/2.7.1-foss-2021b-CUDA-11.4.1/lib/python3.9/site-packages/absl/testing/parameterized.py", line 314, in bound_param_test
    return test_method(self, **testcase_params)
  File "/dev/shm/s3248973-EasyBuild/TensorFlow/2.7.1/foss-2021b-CUDA-11.4.1/tmp5xgzay-bazel-tf/69a307561ec5a7cdace7b5c5a8971ea2/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/data/experimental/kernel_tests/service/fault_tolerance_test.runfiles/org_tensorflow/tensorflow/python/framework/test_combinations.py", line 366, in decorated
    execute_test_method()
  File "/dev/shm/s3248973-EasyBuild/TensorFlow/2.7.1/foss-2021b-CUDA-11.4.1/tmp5xgzay-bazel-tf/69a307561ec5a7cdace7b5c5a8971ea2/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/data/experimental/kernel_tests/service/fault_tolerance_test.runfiles/org_tensorflow/tensorflow/python/framework/test_combinations.py", line 349, in execute_test_method
    test_method(**kwargs_to_pass)
  File "/dev/shm/s3248973-EasyBuild/TensorFlow/2.7.1/foss-2021b-CUDA-11.4.1/tmp5xgzay-bazel-tf/69a307561ec5a7cdace7b5c5a8971ea2/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/data/experimental/kernel_tests/service/fault_tolerance_test.runfiles/org_tensorflow/tensorflow/python/data/experimental/kernel_tests/service/fault_tolerance_test.py", line 245, in testRestartWorker
    val = next(iterator).numpy()
  File "/dev/shm/s3248973-EasyBuild/TensorFlow/2.7.1/foss-2021b-CUDA-11.4.1/tmp5xgzay-bazel-tf/69a307561ec5a7cdace7b5c5a8971ea2/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/data/experimental/kernel_tests/service/fault_tolerance_test.runfiles/org_tensorflow/tensorflow/python/data/ops/iterator_ops.py", line 802, in __next__
    raise StopIteration
StopIteration
```

So we have a `raise StopIteration` in a `__next__` function which is a valid (Python) way to signal the end-of-sequence. Going up the stack to the `val = next(iterator).numpy()` line we have this code https://github.com/tensorflow/tensorflow/blob/v2.7.1/tensorflow/python/data/experimental/kernel_tests/service/fault_tolerance_test.py#L242-L247 or in master https://github.com/tensorflow/tensorflow/blob/51fe2b12452415e9a96751b5e5df0c8567f6c561/tensorflow/python/data/experimental/kernel_tests/service/fault_tolerance_test.py#L239-L244

So there the comment clearly states "There may have been some elements prefetched from the first worker before it was stopped." yet it unconditionally(!) calls `next(iterator)` in a `while True` loop

Not only is that code better written as `while next(iterator).numpy() != 0` but the case that the iterator is exhausted before it returns `0` isn't handled at all! So better would be:
```
# For loops handle StopIteration and call `next` already
for val in iterator:
    if val.numpy() == 0:
        break
```

To further investigate this I added `print` statements to the loops at https://github.com/tensorflow/tensorflow/blob/51fe2b12452415e9a96751b5e5df0c8567f6c561/tensorflow/python/data/experimental/kernel_tests/service/fault_tolerance_test.py#L234 and https://github.com/tensorflow/tensorflow/blob/51fe2b12452415e9a96751b5e5df0c8567f6c561/tensorflow/python/data/experimental/kernel_tests/service/fault_tolerance_test.py#L242 to print out the values from `next(iterator)`

The first loop prints out tensors with 0-49, the 2nd 50-99. So it looks like the comment "The dataset starts over now that we read from the new worker." doesn't seem to hold: The dataset continues till the end.

I'm not sure where the mistake is and what the expected behavior should be. To me it looks like the fault tolerance works very well: The dataset is not disturbed by the worker restart (if that really happens)

I hope that helps

**Comment by mohantym** [comment]
Hi @gadagashwini ! 
Could you look at this issue, Attached [2.7 ](https://colab.sandbox.google.com/gist/mohantym/b8ec0c73e4fbcbf9fb816830d88e5396/tensorflow-ranking.ipynb), [2.8](https://colab.sandbox.google.com/gist/mohantym/fc688a1720d0bc2b25eab68dc85f782a/tensorflow-ranking.ipynb), [2.9](https://colab.sandbox.google.com/gist/mohantym/aa9e8323c60bce58ea117b43995b3080/tensorflow-ranking.ipynb#scrollTo=_IQp1_gflTaC) and [nightly](https://colab.sandbox.google.com/gist/mohantym/94f962610a74d79363b136646cf2a682/tensorflow-ranking.ipynb#scrollTo=bm6xYiPWG9nl) gist for reference (--config=opt is not working rather than - c opt) 
Thank you!

**Comment by SuryanarayanaY** [comment]
Hi @Flamefire ,

The PR proposed by you has been merged.Is it good to to close the issue now? Please check and confirm. Thanks!

**Comment by Flamefire** [comment]
@SuryanarayanaY I haven't proposed a PR to tensorflow to fix this issue so this is (likely) still an issue which needs investigation and a fix. See my comment above:

> I'm not sure where the mistake is and what the expected behavior should be. To me it looks like the fault tolerance works very well: The dataset is not disturbed by the worker restart (if that really happens)

If you were referring to https://github.com/easybuilders/easybuild-easyconfigs/pull/15882: This is a PR against something **using** TF were in order to run the tests I disabled the test which is seemingly broken as reported in this issue. So that is only a workaround and not even to TF so the issue in TF is unaffected by that PR.

**Comment by SuryanarayanaY** [comment]
@Flamefire ,

Could you please confirm whether this issue is specific to RHEL7 or to your particular system with the mentioned CPUs and GPUs?I can see you mentioned that the test passes in other system.

Please also confirm if this is still an issue with latest version ? 

Also currently TF supports Ubuntu Linux instructions officially as per this [source](https://www.tensorflow.org/install/source#:~:text=Build%20a%20TensorFlow%20pip%20package%20from%20source%20and%20install%20it%20on%20Ubuntu%20Linux%20and%20macOS.%20While%20the%20instructions%20might%20work%20for%20other%20systems%2C%20it%20is%20only%20tested%20and%20supported%20for%20Ubuntu%20and%20macOS.).

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

**Comment by Kayyuri** [comment]
Hi @Flamefire,
Thank you so much for filing this issue! We truly appreciate your support. At the moment, this request is not prioritized and mark it for community contributions. If you would like to contribute on a fix, please feel free to fork the repository and submit a pull request in accordance with the TensorFlow [CONTRIBUTION GUIDELINES](https://www.tensorflow.org/community/contribute/code) and link this issue in your PR to ensure the maintainers can easily review and collaborate.
To avoid duplicate work, please leave a comment here if you decide to take it on!

Thank you again for your interest and we look forward to seeing your contributions!
