### ISSUE TITLE
TPU pod  v4 "RuntimeError: TPU cores on each host is not same." 

### ISSUE THREAD

**Issue by naumanjaved** [tensorflow/tensorflow#56760]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

TF 2.9.1

### Custom Code

Yes

### Python version

Python 3.8.10

### Current Behaviour?

```shell
I am trying to run a model on cloud TPU V4 POD. The V4 TPU is created with version tpu-vm-tf-2.9.1-pod-v4 and environment variables/package installations set according to the guide here: https://cloud.google.com/tpu/docs/v4-users-guide

When initializing the TPU strategy, which works perfectly fine on a V4-8 running version v2-alpha-tpuv4, I get a RuntimeError stating "TPU cores on each host is not same. This should not happen!"  Any help would be appreciated.
```

### Standalone code to reproduce the issue

```shell
import time
import os
import subprocess
import sys
import re
import argparse
import collections
import gzip
import math
import shutil
import matplotlib.pyplot as plt
import wandb
import numpy as np
import time
from datetime import datetime
import random

import seaborn as sns

import tensorflow as tf
import tensorflow.experimental.numpy as tnp
import tensorflow_addons as tfa
from tensorflow import strings as tfs
from tensorflow.keras import mixed_precision
from scipy import stats

resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu=‘tpupod’)
tf.config.experimental_connect_to_cluster(resolver)
tf.tpu.experimental.initialize_tpu_system(resolver)
strategy = tf.distribute.experimental.TPUStrategy(resolver)
```

### Relevant log output

```shell
2022-07-13 19:28:05.566390: I tensorflow/core/tpu/tpu_api_dlsym_initializer.cc:116] Libtpu path is: libtpu.so
Missing key: 'TWIST' in 'tpu-env' (yaml) instance metadata.
test.py:25: DeprecationWarning: Please use `pearsonr` from the `scipy.stats` namespace, the `scipy.stats.stats` namespace is deprecated.
  from scipy.stats.stats import pearsonr
2022-07-13 19:28:20.657469: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-07-13 19:28:20.835472: I tensorflow/compiler/xla/service/service.cc:170] XLA service 0x2727500 initialized for platform TPU (this does not guarantee that XLA will be used). Devices:
2022-07-13 19:28:20.835513: I tensorflow/compiler/xla/service/service.cc:178]   StreamExecutor device (0): TPU, 2a886c8
2022-07-13 19:28:20.835519: I tensorflow/compiler/xla/service/service.cc:178]   StreamExecutor device (1): TPU, 2a886c8
2022-07-13 19:28:20.835523: I tensorflow/compiler/xla/service/service.cc:178]   StreamExecutor device (2): TPU, 2a886c8
2022-07-13 19:28:20.835527: I tensorflow/compiler/xla/service/service.cc:178]   StreamExecutor device (3): TPU, 2a886c8
2022-07-13 19:28:21.026508: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job worker -> {0 -> 10.28.0.20:8470, 1 -> 10.28.0.19:8470}
2022-07-13 19:28:21.026560: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:44426}
2022-07-13 19:28:21.043816: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job worker -> {0 -> 10.28.0.20:8470, 1 -> 10.28.0.19:8470}
2022-07-13 19:28:21.043844: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:44426}
2022-07-13 19:28:21.045847: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:438] Started server with target: grpc://localhost:44426
WARNING:absl:`tf.distribute.experimental.TPUStrategy` is deprecated, please use  the non experimental symbol `tf.distribute.TPUStrategy` instead.
Traceback (most recent call last):
  File "test.py", line 43, in <module>
    strategy = tf.distribute.experimental.TPUStrategy(resolver)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/distribute/tpu_strategy.py", line 696, in __init__
    TPUExtended(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/distribute/tpu_strategy.py", line 864, in __init__
    self._tpu_metadata = self._tpu_cluster_resolver.get_tpu_system_metadata()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/distribute/cluster_resolver/tpu/tpu_cluster_resolver.py", line 297, in get_tpu_system_metadata
    tpu_system_metadata_lib._query_tpu_system_metadata(  # pylint: disable=protected-access
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/tpu/tpu_system_metadata.py", line 123, in _query_tpu_system_metadata
    raise RuntimeError(
RuntimeError: TPU cores on each host is not same. This should not happen!. devices: [_DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 0, 0), _DeviceAttributes(/job:localhost/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 0, 0), _DeviceAttributes(/job:localhost/replica:0/task:0/device:TPU:0, TPU, 0, 0), _DeviceAttributes(/job:localhost/replica:0/task:0/device:TPU:1, TPU, 0, 0), _DeviceAttributes(/job:localhost/replica:0/task:0/device:TPU:2, TPU, 0, 0), _DeviceAttributes(/job:localhost/replica:0/task:0/device:TPU:3, TPU, 0, 0), _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, 0, 0), _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 0, 0), _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 0, 0), _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:1, TPU, 0, 0), _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:2, TPU, 0, 0), _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:3, TPU, 0, 0), _DeviceAttributes(/job:worker/replica:0/task:1/device:CPU:0, CPU, 0, 0), _DeviceAttributes(/job:worker/replica:0/task:1/device:TPU_SYSTEM:0, TPU_SYSTEM, 0, 0), _DeviceAttributes(/job:worker/replica:0/task:1/device:TPU:0, TPU, 0, 0), _DeviceAttributes(/job:worker/replica:0/task:1/device:TPU:1, TPU, 0, 0), _DeviceAttributes(/job:worker/replica:0/task:1/device:TPU:2, TPU, 0, 0), _DeviceAttributes(/job:worker/replica:0/task:1/device:TPU:3, TPU, 0, 0)]
```
</details>

**Comment by tilakrayal** [comment]
@naumanjaved,
I ran the provided code and faced a different error, Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/11476aaf5e7aeb0268c09300b46d47b2/untitled429.ipynb) and share all dependencies to replicate the issue. Thank you!

**Comment by naumanjaved** [comment]
Thanks for looking into this.

The error I am describing seems to be specific to a TPU v4 VM running version tpu-vm-tf-2.9.1-pod-v4 and only occurs with a V4-16 configuration or above.  I am not sure how to link a TPU VM pod to the collab notebook to recreate the issue exactly - any recommendation for how to go about doing this? I believe that the HTTP error in the linked collab notebook is resulting from there not being an attached TPU pod(unless I am missing something). 

Thanks!

**Comment by naumanjaved** [comment]
Hello! Just wondering if there are any recommendations for this error. Thanks so much!

**Comment by naumanjaved** [comment]
Thanks so much

with tpu name set to local, as follows:

```
import tensorflow as tf

import tensorflow_addons as tfa
from tensorflow import strings as tfs
from tensorflow.keras import mixed_precision

resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu='local')
tf.config.experimental_connect_to_cluster(resolver)
tf.tpu.experimental.initialize_tpu_system(resolver)
strategy = tf.distribute.TPUStrategy(resolver)
    

with strategy.scope():

    tf.config.optimizer.set_jit(True)


    BATCH_SIZE_PER_REPLICA = 4
    NUM_REPLICAS = strategy.num_replicas_in_sync
    GLOBAL_BATCH_SIZE = BATCH_SIZE_PER_REPLICA * NUM_REPLICAS
    print(GLOBAL_BATCH_SIZE)
    print(NUM_REPLICAS)
```
I receive: 

2022-07-19 19:00:39.720777: I tensorflow/core/tpu/tpu_api_dlsym_initializer.cc:116] Libtpu path is: libtpu.so
Missing key: 'TWIST' in 'tpu-env' (yaml) instance metadata.
test.py:25: DeprecationWarning: Please use `pearsonr` from the `scipy.stats` namespace, the `scipy.stats.stats` namespace is deprecated.
  from scipy.stats.stats import pearsonr
2022-07-19 19:00:41.111211: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-07-19 19:00:41.146032: I tensorflow/compiler/xla/service/service.cc:170] XLA service 0x764ef00 initialized for platform TPU (this does not guarantee that XLA will be used). Devices:
2022-07-19 19:00:41.146076: I tensorflow/compiler/xla/service/service.cc:178]   StreamExecutor device (0): TPU, 2a886c8
2022-07-19 19:00:41.146082: I tensorflow/compiler/xla/service/service.cc:178]   StreamExecutor device (1): TPU, 2a886c8
2022-07-19 19:00:41.146086: I tensorflow/compiler/xla/service/service.cc:178]   StreamExecutor device (2): TPU, 2a886c8
2022-07-19 19:00:41.146091: I tensorflow/compiler/xla/service/service.cc:178]   StreamExecutor device (3): TPU, 2a886c8
2022-07-19 19:00:42.268562: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at tpu_configuration_ops.cc:342 : FAILED_PRECONDITION: 'CLOUD_TPU_TASK_ID' not specified for a multi-host job.
Traceback (most recent call last):
  File "test.py", line 46, in <module>
    tf.tpu.experimental.initialize_tpu_system(resolver)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/tpu/tpu_strategy_util.py", line 110, in initialize_tpu_system
    output = _tpu_init_fn()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 2453, in __call__
    return graph_function._call_flat(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 1860, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 497, in call
    outputs = execute.execute(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.FailedPreconditionError: Graph execution error:

'CLOUD_TPU_TASK_ID' not specified for a multi-host job.
	 [[{{node configure_tpu_host/_2}}]] [Op:__inference__tpu_init_fn_4]

**Comment by sachinprasadhs** [comment]
@naumanjaved , Did you try specifying grpc address or by leaving the tpu="" for it to identify the available TPU.

**Comment by tilakrayal** [comment]
@naumanjaved,
AFAIK you will get the following error if you don't set **TPU_LOAD_LIBRARY=0**. Could you please set as mentioned and try to follow the process to execute the code. 

Also please have a look at this [comment](https://github.com/tensorflow/tensorflow/issues/53296#issuecomment-1832822090) for the similar issue. Thank you!
