### ISSUE TITLE
[TF.io] Incompatible with AWS S3 filepaths

### ISSUE THREAD

**Issue by neel04** [tensorflow/tensorflow#56814]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

RHEL

### Python version

3.7.12

### Current Behaviour?

Apparently, from the AWS logs it seems the Headers are obtained but the response body is empty.

I'm using `TFDS`, However its accessing (via `etils`) the TF backend to create a stream for the S3 object. Hence why its reproducible from a `TF` method. 

This was the full error from TFDS, for those interested, to verify that it does indeed call `tf.io` as a backend to execute the request. 

```
Traceback (most recent call last):
  File "scripts/kecam_tester.py", line 47, in <module>
    description='Preprocessed TFRecords of BDD100K dataset, long only, delayed by 60 frames for each tuple.',
  File "/home/awesome/.local/lib/python3.7/site-packages/tensorflow_datasets/core/folder_dataset/write_metadata_utils.py", line 80, in write_metadata
    f for f in data_dir.iterdir() if naming.FilenameInfo.is_valid(f.name)
  File "/home/awesome/.local/lib/python3.7/site-packages/tensorflow_datasets/core/folder_dataset/write_metadata_utils.py", line 80, in <listcomp>
    f for f in data_dir.iterdir() if naming.FilenameInfo.is_valid(f.name)
  File "/home/awesome/.local/lib/python3.7/site-packages/etils/epath/gpath.py", line 126, in iterdir
    for f in self._backend.listdir(self._path_str):
  File "/home/awesome/.local/lib/python3.7/site-packages/etils/epath/backend.py", line 191, in listdir
    return self.gfile.listdir(path)
  File "/home/awesome/.local/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 769, in list_directory_v2
    message="Could not find directory {}".format(path))
tensorflow.python.framework.errors_impl.NotFoundError: Could not find directory s3://s-laion/ssd-videos/new_tfrecs
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

# Insert any S3 filepath
tf.io.gfile.listdir('s3://...')
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/awesome/.local/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 769, in list_directory_v2
    message="Could not find directory {}".format(path))
tensorflow.python.framework.errors_impl.NotFoundError: Could not find directory s3://...
```
</details>

**Comment by neel04** [comment]
`tf_io` is a seperate package - the traceback doesn't reach it, only to the core TF modules 🤷

**Comment by neel04** [comment]
Obviously, I checked it the filepaths with both `boto3` and `smart_open`. The issue is a bug with TF alone, reproducible on other S3 buckets

**Comment by gowthamkpr** [comment]
This is not possible as of now. Please take a look at this workaround [here](https://github.com/tensorflow/tensorflow/issues/43344#issuecomment-1092262374). Also please go through this [issue](https://github.com/tensorflow/io/issues/1252). Thanks!
