### ISSUE TITLE
tensorflow.python.framework.errors_impl.DataLossError: corrupted record at 0 [Op:IteratorGetNext] when reading from S3 storage

### ISSUE THREAD

**Issue by omrialmog** [tensorflow/tensorflow#56855]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

v2.8.1-10-g2ea19cbb575 2.8.2

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 18.04

### Python version

3.8.10

### Current Behaviour?

```shell
Hello,

We see the error in "Relevant log output" when training using tensorflow-cpu. We were able to create a small stress test that exhibits the same failure. Both the training and stress test are essentially loading tf-records from S3 and we have seen the failure occur anywhere from ~30min to 20+ hours.

This happens when we run with single process as well as when we run with 8 processes. When running with 8 processes, one process fails and the rest keep running, but other processes may proceed to fail in the same manner later on if we let it keep running.

We are running on AWS with various instance types. The dataset used is imagenet tf-records stored on an S3 bucket.

To reproduce we do the following: 
0. (Place the imagenet tf-records onto S3) and set TRAIN_TFRECORDS_PATH in data.py
1. Launch an EC2 instance with a Deep Learning AMI (Ubuntu 18.04) Version 50.0 AMI (for example ami-0050625d58fa27b6d on us-west-2)
2. Run tensorflow docker -- tensorflow/tensorflow:2.8.2
3. pip install psutil -y
4. Copy two files below (data.py and run.sh)
5. chmod u+x run.sh
6. run.sh
```

### Standalone code to reproduce the issue

```shell
run.sh:
for i in {0..7}
do
   python data.py -p $i 2>&1 | tee "error${i}.log" &
done

data.py:
import tensorflow as tf
import tensorflow_io as tfio
import copy
from pathlib import Path
import os
import argparse
import psutil
from datetime import datetime

TRAIN_TFRECORDS_PATH = "s3://test/tf_records/"
IMAGE_SIZE = (192, 192)


def _image_shape(image):
    shape = tf.shape(image)
    return shape[0], shape[1]

def read_tfrecord(example):
    features = {
        "image": tf.io.FixedLenFeature([], tf.string),
        "label": tf.io.FixedLenFeature([], tf.int64)
    }
    example = tf.io.parse_single_example(example, features)
    image = tf.image.decode_jpeg(example["image"])
    class_num = example["label"]
    return image, class_num


def resize_and_crop_image(image):
    image = tf.image.crop_to_bounding_box(image, 0, 0, 16, 16)
    return image


def normalize(image, dtype):
    imagenet_mean = tf.constant([0.485, 0.456, 0.406], dtype=dtype) * 255
    imagenet_std = tf.constant([0.229, 0.224, 0.225], dtype=dtype) * 255
    image = tf.cast(image, dtype=dtype)
    image = (image - imagenet_mean) / imagenet_std
    return image

s3_filenames = [
    f'{TRAIN_TFRECORDS_PATH}5.99.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.0.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.1.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.10.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.100.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.101.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.102.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.103.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.104.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.105.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.106.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.107.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.108.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.109.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.11.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.110.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.111.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.112.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.113.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.114.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.115.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.116.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.117.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.118.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.119.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.12.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.120.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.121.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.122.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.123.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.124.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.125.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.126.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.127.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.128.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.129.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.13.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.130.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.131.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.132.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.133.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.134.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.135.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.136.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.137.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.138.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.139.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.14.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.140.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.141.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.142.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.143.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.144.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.145.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.146.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.147.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.148.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.149.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.15.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.150.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.151.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.152.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.153.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.154.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.155.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.156.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.157.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.158.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.159.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.16.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.160.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.161.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.162.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.163.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.164.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.165.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.166.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.167.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.168.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.169.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.17.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.170.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.171.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.172.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.173.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.174.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.175.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.176.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.177.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.178.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.179.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.18.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.180.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.181.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.182.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.183.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.184.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.185.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.186.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.187.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.188.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.189.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.19.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.190.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.191.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.192.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.193.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.194.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.195.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.196.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.197.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.198.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.199.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.2.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.20.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.200.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.201.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.202.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.203.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.204.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.205.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.206.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.207.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.208.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.209.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.21.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.210.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.211.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.212.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.213.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.214.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.215.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.216.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.217.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.218.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.22.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.220.tfrecord',
    f'{TRAIN_TFRECORDS_PATH}6.221.tfrecord'
]


def init_train_dataset(s3_filenames_list):

    def tfrecord_parser_fn(raw_record):
        image, label = read_tfrecord(raw_record)
        dataset = {"image": image, "label": label}
        return dataset, label

    def preprocess_sample(features, label):
        features["image"] = resize_and_crop_image(features["image"])
        return features, label

    print("Loading data from S3")
    filenames = s3_filenames_list

    print(f"using the following file {filenames}")

    train_dataset = tf.data.TFRecordDataset(filenames=filenames)
    train_dataset = train_dataset.repeat().map(tfrecord_parser_fn).map(
        preprocess_sample).batch(200)
    return train_dataset


def remove_missing_rec(listin):
    tmp_list = copy.deepcopy(listin)
    for tfrec in tmp_list:
        if not tf.io.gfile.exists(tfrec):
            print('record is missing ',tfrec);
            listin.remove(tfrec)
    print("list size: ",len(listin))
    return listin



def main(p,s3_filenames):
    pid = os.getpid()
    print('LIST LENGTH BEFORE REMOVE: ', len(s3_filenames))
    s3_filenames = remove_missing_rec(s3_filenames);
    print('LIST LENGTH AFTER REMOVE: ', len(s3_filenames))
    dataset = init_train_dataset(s3_filenames)
    dataset_iter = iter(dataset)
    print("****************************  PROCESS ID: ",pid,"  ******************************")
    process = psutil.Process(pid)
    for i,data in enumerate(dataset_iter):
        print("Dataset loaded p: ",p," iter: ",i)
        if i%30==0:
            print("time: ",datetime.now().time())
            used_mem = psutil.virtual_memory().used
            print("used Virtual memory: {} Mb".format(used_mem / 1024 / 1024))
            mem_info = process.memory_info()
            print("Process memory: {} Mb".format(mem_info.rss / 1024 / 1024))

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('-p', type=int, required=True,help="proc number")
    args = parser.parse_args()
    p = args.p
    main(p,s3_filenames)
```

### Relevant log output

```shell
...
Dataset loaded p:  0  iter:  13291
Dataset loaded p:  0  iter:  13292
Dataset loaded p:  0  iter:  13293
Dataset loaded p:  0  iter:  13294
Dataset loaded p:  0  iter:  13295
Dataset loaded p:  0  iter:  13296
Dataset loaded p:  0  iter:  13297
Dataset loaded p:  0  iter:  13298
Dataset loaded p:  0  iter:  13299
Dataset loaded p:  0  iter:  13300
Dataset loaded p:  0  iter:  13301
Dataset loaded p:  0  iter:  13302
Dataset loaded p:  0  iter:  13303
Dataset loaded p:  0  iter:  13304
Dataset loaded p:  0  iter:  13305
Dataset loaded p:  0  iter:  13306
Dataset loaded p:  0  iter:  13307
Dataset loaded p:  0  iter:  13308
Traceback (most recent call last):
  File "data.py", line 263, in <module>
    main(p,s3_filenames)
  File "data.py", line 248, in main
    for i,data in enumerate(dataset_iter):
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 836, in __next__
    return self._next_internal()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 819, in _next_internal
    ret = gen_dataset_ops.iterator_get_next(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2923, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py", line 7186, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.DataLossError: corrupted record at 0 [Op:IteratorGetNext]
```
</details>

**Comment by tilakrayal** [comment]
@omrialmog,
Could you please try using `tf.data.experimental.ignore_errors()` which would solve the problem here. 

Also please take a look at this doc [link](https://www.tensorflow.org/api_docs/python/tf/data/experimental/ignore_errors) for the reference. Thank you!

**Comment by omrialmog** [comment]
Hi @tilakrayal, we can try that but its not really a permanent solution since it ignores any errors even if they are not this particular error. We dont want to always ignore errors, we want to make sure we still catch errors in the future. Do you have any tips on why this might be occurring?
Thanks!

**Comment by tilakrayal** [comment]
@omrialmog,
As the error suggested, the `record 0` was corrupted. Could you please check that record which was corrupted and try to execute the code again. Thank you!

**Comment by omrialmog** [comment]
@tilakrayal,
record 0 usually indicates the iterator didn't get anything and not a corrupted error.
We are thinking for some reason the iterator is not receiving any items at some point in time during the loading and thats what this error is hitting. 

Another data point that supports this is that all the records are being repeated over and over forever (until the error), and by the time we get to the error the records themselves have been used over many times. The records themselves are not corrupted in this scenario otherwise they would fail the first time we load them.

**Comment by gowthamkpr** [comment]
@omrialmog Did you use compression for this dataset? If you use GZIP compression, you should use `raw_dataset = tf.data.TFRecordDataset( output_path, compression_type = 'GZIP' )`. Also can you please look into this [explanation](https://forums.developer.nvidia.com/t/datalosserror-corrupted-record-at-0-when-using-tfrecords-with-detectnet/201243/13) and let me know if it helps. Also can you please provide us the code you used to convert images to tfrecords. Thanks!

**Comment by omrialmog** [comment]
Hi @gowthamkpr,

Thanks for the reply with more information.
We do not use any compression for the tf-records unfortunately, we thought the same looking at other issues but we dont use any Gzip.
I will try to find the code we used to do the image conversion - Im pretty sure its standard use for that.

We read the data like you listed, please see the line below:
train_dataset = tf.data.TFRecordDataset(filenames=filenames)

**Comment by houruiyan** [comment]
Hi, maybe you can change your code as this `raw_dataset = tf.data.TFRecordDataset(VALID_FILENAMES, compression_type="ZLIB")`. 
Actually, my dataset are TFRecord files. It also is not the compressed file. When I did not add `compression_type="ZLIB"`, it has the same problem as yours. But when I add `compression_type="ZLIB"`, it works.
