### ISSUE TITLE
Differentiate a tuple with `tape.jacobian`

### ISSUE THREAD

**Issue by rmoyard** [tensorflow/tensorflow#56912]
### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9.1

### Custom Code

Yes

### OS Platform and Distribution

MacOs

### Mobile device

-

### Python version

3.9

### Bazel version

-

### GCC/Compiler version

-

### CUDA/cuDNN version

-

### GPU model and memory

-

### Current Behaviour?

```shell
I expect to able to differentiate a function returning a tuple of TensorFlow tensors, but unfortunately it is not possible because tuples have no shape. Could you provide me a work around for this? Maybe something with ragged tensors is possible here?
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

def circuit(params):
    return params[0] ** 2, params[1::] ** 3

x = tf.Variable([0.1, 0.2, 0.3])

with tf.GradientTape() as tape:
    out = circuit(x)

jac = tape.jacobian(out, x)
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/Users/.../test.py", line 14, in <module>
    jac = tape.jacobian(out, x)
  File "/Users/.../lib/python3.9/site-packages/tensorflow/python/eager/backprop.py", line 1183, in jacobian
    target_static_shape = target.shape
AttributeError: 'tuple' object has no attribute 'shape'
```

**Comment by tilakrayal** [comment]
@chunduriv,
I was able to reproduce the issue on tensorflow v2.8, v2.9 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/44d5887b6a1eded9f2737fab77ae5920/56912.ipynb).

**Comment by rmoyard** [comment]
Any update on this issue? @sachinprasadhs

**Comment by dwierichs** [comment]
I suppose a workaround is
```python
import tensorflow as tf

def circuit(params):
    return params[0] ** 2, params[1::] ** 3

x = tf.Variable([0.1, 0.2, 0.3])

with tf.GradientTape(persistent=True) as tape:
    out = circuit(x)

jac = tuple(tape.jacobian(val, x) for val in out)
```
Is the above a reasonable workaround? :thinking: How about performance of this repeated differentiation? Are there situations where this would lead to excessive retracing? :thinking:

**Comment by Kayyuri** [comment]
Hi @rmoyard, Apologies for the late response and thank you for your patience.
`tape.jacobian` expects single tensor, so you can’t pass a tuple directly to it. To fix this, either combine the outputs into one tensor using `tf.concat` before passing it to `tape.jacobian`, or compute the Jacobian for each output separately.

Thanks!
