### ISSUE TITLE
INVALID_ARGUMENT:  assertion failed: [predictions must be <= 1]

### ISSUE THREAD

**Issue by Blackbird95x** [tensorflow/tensorflow#56962]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Source

binary

### Tensorflow Version

tf2.9.1

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 22.04

### Python version

3.9.12

### CUDA/cuDNN version

CUDA 11.7 / cuDNN 8.4

### GPU model and memory

Geforce RTX 2080TI

### Current Behaviour?

```shell
So I got a Deep Knowledge Tracing Project from GitHub which is open for use by anyone and I wrote it to my use-case. I now trying to train the model in a Jupyter Notebook environment. And when I use the Model.fit() method I get the error output displayed below.
```

### Standalone code to reproduce the issue

```shell
Here is a Link to a repo with everything needed for this error to reproduce

https://github.com/Blackbird95x/Issue_Repo.git
```

### Relevant log output

```shell
2022-07-31 22:35:39.354415: W tensorflow/core/common_runtime/forward_type_inference.cc:231] Type inference failed. This indicates an invalid graph that escaped type checking. Error message: INVALID_ARGUMENT: expected compatible input types, but input 1:
type_id: TFT_OPTIONAL
args {
  type_id: TFT_PRODUCT
  args {
    type_id: TFT_TENSOR
    args {
      type_id: TFT_INT32
    }
  }
}
 is neither a subtype nor a supertype of the combined inputs preceding it:
type_id: TFT_OPTIONAL
args {
  type_id: TFT_PRODUCT
  args {
    type_id: TFT_TENSOR
    args {
      type_id: TFT_FLOAT
    }
  }
}

	while inferring type of node 'cond_21/output/_23'
2022-07-31 22:35:39.756638: I tensorflow/stream_executor/cuda/cuda_dnn.cc:384] Loaded cuDNN version 8100

---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
Input In [9], in <cell line: 1>()
----> 1 history = student_model.fit(dataset = train_set,
      2                             epochs = epochs,
      3                             verbose = verbose,
      4                             validation_data = val_set,
      5                             callbacks = [
      6                                 tf.keras.callbacks.CSVLogger(f"({log_dir}/train.log"),
      7                                 tf.keras.callbacks.ModelCheckpoint(best_model_weights,
      8                                                                    save_best_only = True,
      9                                                                    save_weights_only = True),
     10                                 tf.keras.callbacks.TensorBoard(log_dir=log_dir)
     11                             ])

File ~/project_Bachelor/deep_Knowledge_Tracing/deepkt.py:136, in DKTModel.fit(self, dataset, epochs, verbose, callbacks, validation_data, shuffle, initial_epoch, steps_per_epoch, validation_steps, validation_freq)
     64 def fit (self,
     65         dataset,
     66         epochs = 1,
   (...)
     73         validation_steps = None,
     74         validation_freq = 1):
     75     """Trains the model for a fixed number of epochs(iterations on a dataset).
     76     Arguments:
     77         dataset: A tf.data.dataset. Should return a tuple of '(inputs,(skills,targets))'
   (...)
    134     
    135     """
--> 136     return super(DKTModel, self).fit (x=dataset,
    137                                         epochs = epochs,
    138                                         verbose = verbose,
    139                                         callbacks = callbacks,
    140                                         validation_data = validation_data,
    141                                         shuffle = shuffle,
    142                                         initial_epoch = initial_epoch,
    143                                         steps_per_epoch = steps_per_epoch,
    144                                         validation_steps = validation_steps,
    145                                         validation_freq = validation_freq)

File ~/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py:67, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     65 except Exception as e:  # pylint: disable=broad-except
     66   filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67   raise e.with_traceback(filtered_tb) from None
     68 finally:
     69   del filtered_tb

File ~/anaconda3/lib/python3.9/site-packages/tensorflow/python/eager/execute.py:54, in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     52 try:
     53   ctx.ensure_initialized()
---> 54   tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     55                                       inputs, attrs, num_outputs)
     56 except core._NotOkStatusException as e:
     57   if name is not None:

InvalidArgumentError: Graph execution error:

Detected at node 'assert_less_equal/Assert/AssertGuard/Assert' defined at (most recent call last):
    File "/home/dennis/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/home/dennis/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py", line 16, in <module>
      app.launch_new_instance()
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py", line 846, in launch_instance
      app.start()
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 677, in start
      self.io_loop.start()
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 199, in start
      self.asyncio_loop.run_forever()
    File "/home/dennis/anaconda3/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
      self._run_once()
    File "/home/dennis/anaconda3/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
      handle._run()
    File "/home/dennis/anaconda3/lib/python3.9/asyncio/events.py", line 80, in _run
      self._context.run(self._callback, *self._args)
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 471, in dispatch_queue
      await self.process_one()
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 460, in process_one
      await dispatch(*args)
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 367, in dispatch_shell
      await result
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 662, in execute_request
      reply_content = await reply_content
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 360, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/ipykernel/zmqshell.py", line 532, in run_cell
      return super().run_cell(*args, **kwargs)
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2881, in run_cell
      result = self._run_cell(
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2936, in _run_cell
      return runner(coro)
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
      coro.send(None)
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3135, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3338, in run_ast_nodes
      if await self.run_code(code, result, async_=asy):
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3398, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "/tmp/ipykernel_30263/708048511.py", line 1, in <cell line: 1>
      history = student_model.fit(dataset = train_set,
    File "/home/dennis/project_Bachelor/deep_Knowledge_Tracing/deepkt.py", line 136, in fit
      return super(DKTModel, self).fit (x=dataset,
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/keras/engine/training.py", line 1409, in fit
      tmp_logs = self.train_function(iterator)
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/keras/engine/training.py", line 1051, in train_function
      return step_function(self, iterator)
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/keras/engine/training.py", line 1040, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/keras/engine/training.py", line 1030, in run_step
      outputs = model.train_step(data)
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/keras/engine/training.py", line 894, in train_step
      return self.compute_metrics(x, y, y_pred, sample_weight)
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/keras/engine/training.py", line 987, in compute_metrics
      self.compiled_metrics.update_state(y, y_pred, sample_weight)
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/keras/engine/compile_utils.py", line 501, in update_state
      metric_obj.update_state(y_t, y_p, sample_weight=mask)
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/keras/utils/metrics_utils.py", line 70, in decorated
      update_op = update_state_fn(*args, **kwargs)
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/keras/metrics/base_metric.py", line 140, in update_state_fn
      return ag_update_state(*args, **kwargs)
    File "/home/dennis/project_Bachelor/deep_Knowledge_Tracing/metrics.py", line 16, in update_state
      super(AUC, self).update_state(y_true=true,
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/keras/metrics/metrics.py", line 1759, in update_state
      return metrics_utils.update_confusion_matrix_variables(
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/keras/utils/metrics_utils.py", line 606, in update_confusion_matrix_variables
      tf.debugging.assert_less_equal(
Node: 'assert_less_equal/Assert/AssertGuard/Assert'
Detected at node 'assert_less_equal/Assert/AssertGuard/Assert' defined at (most recent call last):
    File "/home/dennis/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/home/dennis/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py", line 16, in <module>
      app.launch_new_instance()
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py", line 846, in launch_instance
      app.start()
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 677, in start
      self.io_loop.start()
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 199, in start
      self.asyncio_loop.run_forever()
    File "/home/dennis/anaconda3/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
      self._run_once()
    File "/home/dennis/anaconda3/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
      handle._run()
    File "/home/dennis/anaconda3/lib/python3.9/asyncio/events.py", line 80, in _run
      self._context.run(self._callback, *self._args)
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 471, in dispatch_queue
      await self.process_one()
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 460, in process_one
      await dispatch(*args)
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 367, in dispatch_shell
      await result
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 662, in execute_request
      reply_content = await reply_content
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 360, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/ipykernel/zmqshell.py", line 532, in run_cell
      return super().run_cell(*args, **kwargs)
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2881, in run_cell
      result = self._run_cell(
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2936, in _run_cell
      return runner(coro)
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
      coro.send(None)
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3135, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3338, in run_ast_nodes
      if await self.run_code(code, result, async_=asy):
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3398, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "/tmp/ipykernel_30263/708048511.py", line 1, in <cell line: 1>
      history = student_model.fit(dataset = train_set,
    File "/home/dennis/project_Bachelor/deep_Knowledge_Tracing/deepkt.py", line 136, in fit
      return super(DKTModel, self).fit (x=dataset,
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/keras/engine/training.py", line 1409, in fit
      tmp_logs = self.train_function(iterator)
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/keras/engine/training.py", line 1051, in train_function
      return step_function(self, iterator)
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/keras/engine/training.py", line 1040, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/keras/engine/training.py", line 1030, in run_step
      outputs = model.train_step(data)
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/keras/engine/training.py", line 894, in train_step
      return self.compute_metrics(x, y, y_pred, sample_weight)
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/keras/engine/training.py", line 987, in compute_metrics
      self.compiled_metrics.update_state(y, y_pred, sample_weight)
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/keras/engine/compile_utils.py", line 501, in update_state
      metric_obj.update_state(y_t, y_p, sample_weight=mask)
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/keras/utils/metrics_utils.py", line 70, in decorated
      update_op = update_state_fn(*args, **kwargs)
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/keras/metrics/base_metric.py", line 140, in update_state_fn
      return ag_update_state(*args, **kwargs)
    File "/home/dennis/project_Bachelor/deep_Knowledge_Tracing/metrics.py", line 16, in update_state
      super(AUC, self).update_state(y_true=true,
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/keras/metrics/metrics.py", line 1759, in update_state
      return metrics_utils.update_confusion_matrix_variables(
    File "/home/dennis/anaconda3/lib/python3.9/site-packages/keras/utils/metrics_utils.py", line 606, in update_confusion_matrix_variables
      tf.debugging.assert_less_equal(
Node: 'assert_less_equal/Assert/AssertGuard/Assert'
2 root error(s) found.
  (0) INVALID_ARGUMENT:  assertion failed: [predictions must be <= 1] [Condition x <= y did not hold element-wise:] [x (Sum_5:0) = ] [[[1][1.00000012][0.99999994]]...] [y (Cast_11/x:0) = ] [1]
	 [[{{node assert_less_equal/Assert/AssertGuard/Assert}}]]
	 [[assert_less_equal_1/Assert/AssertGuard/pivot_f/_79/_131]]
  (1) INVALID_ARGUMENT:  assertion failed: [predictions must be <= 1] [Condition x <= y did not hold element-wise:] [x (Sum_5:0) = ] [[[1][1.00000012][0.99999994]]...] [y (Cast_11/x:0) = ] [1]
	 [[{{node assert_less_equal/Assert/AssertGuard/Assert}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_7474]

​
```
</details>

**Comment by sushreebarsa** [comment]
@gadagashwini I was able to replicate the issue, please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/44dd00632842eb434a1cb9953f4fb7bc/untitled77.ipynb). Thank you!

**Comment by gadagashwini** [comment]
Hi @Blackbird95x, `InvalidArgumentError: Graph execution error:` says that you need to increase your batch_size while training model. The data huge to fit the model. Hence use batch_size. Thank you!

**Comment by Blackbird95x** [comment]
Hey @gadagashwini  I just tried to train the model with batch_ size = 64 and 128 both with the same result.

**Comment by gadagashwini** [comment]
Hi @Blackbird95x, While I was trying to replicate issue, I am getting an error `ModuleNotFoundError: No module named 'deep_Knowledge_Tracing'`. Kindly provide more information to reproduce the issue. Thank you!
