### ISSUE TITLE
build failure on Debian

### ISSUE THREAD

**Issue by hans-ekbrand** [tensorflow/tensorflow#56963]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

current master

### Custom Code

No

### OS Platform and Distribution

Linux Debian Unstable

### Python version

3.10

### Bazel version

5.1.1

### GCC/Compiler version

9.5

### CUDA/cuDNN version

11.4/8.2

### GPU model and memory

I configured Cuda compute level 6.1 (GTX 1060)

### Current Behaviour?

```shell
The build failed when running a bash command:


ERROR: /home/hans/src/tensorflow/tensorflow/BUILD:1396:19: Executing genrule //tensorflow:tf_python_api_gen_v2 failed: (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument skipped)
```

```
ERROR: /home/hans/src/tensorflow/tensorflow/lite/python/BUILD:68:10 Middleman _middlemen/tensorflow_Slite_Spython_Stflite_Uconvert-runfiles failed: (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument skipped)
```

See the Relevant log output below for more of the build log.
```


### Standalone code to reproduce the issue

```shell
bazel build --config=nogcp //tensorflow/tools/pip_package:build_pip_package
```
```


### Relevant log output

```shell
INFO: Found applicable config definition build:short_logs in file /home/hans/src/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/hans/src/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:cuda in file /home/hans/src/tensorflow/.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
INFO: Found applicable config definition build:nogcp in file /home/hans/src/tensorflow/.bazelrc: --define=no_gcp_support=true
INFO: Found applicable config definition build:linux in file /home/hans/src/tensorflow/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++17 --host_cxxopt=-std=c++17 --config=dynamic_kernels --distinct_host_configuration=false --experimental_guard_against_concurrent_changes
INFO: Found applicable config definition build:dynamic_kernels in file /home/hans/src/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/021b5f0d3daea2d1666599d7d9c471a426c35f65.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/114df244ec50ce0145702974335965c3aa2c3dcc.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
DEBUG: /home/hans/.cache/bazel/_bazel_hans/e1debe52b9a35d05215b3a49132625cd/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:118:10:
Auto-Configuration Warning: 'TMP' environment variable is not set, using 'C:\Windows\Temp' as default
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/abseil/abseil-cpp/archive/273292d1cfc0a94a65082ee350509af1d113344d.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/pytorch/cpuinfo/archive/5e63739504f0f8e18e941bd63b2d6d42536c7d90.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/6b409ac0a3090ebe74d0cdfb494c4cd91485ad39.zip failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/nvidia/nccl/archive/v2.13.4-1.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/NVIDIA/cudnn-frontend/archive/refs/tags/v0.6.2.zip failed: class java.io.FileNotFoundException GET returned 404 Not Found
INFO: Analyzed target //tensorflow/tools/pip_package:build_pip_package (511 packages loaded, 36686 targets configured).
INFO: Found 1 target...
ERROR: /home/hans/src/tensorflow/tensorflow/BUILD:1396:19: Executing genrule //tensorflow:tf_python_api_gen_v2 failed: (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument skipped)
2022-07-31 23:38:36.549685: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/home/hans/.cache/bazel/_bazel_hans/e1debe52b9a35d05215b3a49132625cd/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: /home/hans/.cache/bazel/_bazel_hans/e1debe52b9a35d05215b3a49132625cd/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZTIN6icu_678ByteSinkE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hans/.cache/bazel/_bazel_hans/e1debe52b9a35d05215b3a49132625cd/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 22, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/home/hans/.cache/bazel/_bazel_hans/e1debe52b9a35d05215b3a49132625cd/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 36, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/home/hans/.cache/bazel/_bazel_hans/e1debe52b9a35d05215b3a49132625cd/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 77, in <module>
    raise ImportError(
ImportError: Traceback (most recent call last):
  File "/home/hans/.cache/bazel/_bazel_hans/e1debe52b9a35d05215b3a49132625cd/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: /home/hans/.cache/bazel/_bazel_hans/e1debe52b9a35d05215b3a49132625cd/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZTIN6icu_678ByteSinkE


Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors for some common causes and solutions.
If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/hans/src/tensorflow/tensorflow/lite/python/BUILD:68:10 Middleman _middlemen/tensorflow_Slite_Spython_Stflite_Uconvert-runfiles failed: (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument skipped)
INFO: Elapsed time: 33090.674s, Critical Path: 280.90s
INFO: 121408 processes: 98221 internal, 23187 local.
FAILED: Build did NOT complete successfully
```
</details>

**Comment by tilakrayal** [comment]
@hans-ekbrand,
Could you please provide the source from where you are trying to install the tensorflow. It helps us to analyse and provide the CUDA, cudNN and the bazel version which are compatible for the respective tensorflow version. 

Also please take a look at this [comment](https://github.com/tensorflow/tensorflow/issues/41490#issuecomment-661106497) from the developer for the similar error. Thank you!

**Comment by hans-ekbrand** [comment]
> Could you please provide the source from where you are trying to install the tensorflow. It helps us to analyse and provide the CUDA, cudNN and the bazel version which are compatible for the respective tensorflow version.

The source I tried to build has this as the last log entry
```
commit cf67a8102c0f9d390aa1b43dc5daa363e753393c (HEAD -> master, origin/master, origin/HEAD)
Author: A. Unique TensorFlower <gardener@tensorflow.org>
Date:   Sun Jul 31 02:01:52 2022 -0700

    Update GraphDef version to 1209.
    
    PiperOrigin-RevId: 464355826

```

> Also please take a look at this [comment](https://github.com/tensorflow/tensorflow/issues/41490#issuecomment-661106497) from the developer for the similar error. 

Indeed the error looks similar. My question in https://github.com/tensorflow/tensorflow/issues/41490 about which versions of icu is compatible was never answered, and here are the currently installed versions:

```
ii  icu-devtools                               67.1-4                          amd64        Development utilities for International Components for Unicode
ii  libharfbuzz-icu0:amd64                     2.6.7-1                         amd64        OpenType text shaping engine ICU backend
ii  libicu-dev:amd64                           67.1-4                          amd64        Development files for International Components for Unicode
ii  libicu63:amd64                             63.1-6+deb10u1                  amd64        International Components for Unicode
ii  libicu67:amd64                             67.1-4                          amd64        International Components for Unicode
ii  libicu71:amd64                             71.1-3                          amd64        International Components for Unicode
```

**Comment by gadagashwini** [comment]
Hi @hans-ekbrand, Looks like issue with Python module. Could you try to install python3 module `request`. 
`pip3 install requests`. Thank you!

**Comment by hans-ekbrand** [comment]
> Hi @hans-ekbrand, Looks like issue with Python module. Could you try to install python3 module `request`.
> `pip3 install requests`. Thank you!

requests is already installed:

```
$ pip list | grep requests
requests               2.23.0
```

**Comment by SuryanarayanaY** [comment]
Hi @hans-ekbrand ,

Could you please confirm if this is still an issue for you. 

Can you confirm adding the flag `--noincompatible_do_not_split_linking_cmdline` to your command helps you which seems resolved for few users as per the source from [here](https://github.com/tensorflow/tensorflow/issues/37076#issuecomment-597971693).

Also please find the tested configurations from [here](https://www.tensorflow.org/install/source#linux).

Please go through the above resources and confirm if this is still having same problem. Thanks!
