### ISSUE TITLE
Cannot build branch r2.9 on Windows 11

### ISSUE THREAD

**Issue by cidzerda-unity** [tensorflow/tensorflow#56973]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.9

### Custom Code

No

### OS Platform and Distribution

Windows 11 Enterprise version 21H2 OS build 22000.795

### Python version

3.9.7

### Bazel version

5.0.0

### GCC/Compiler version

Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30146 for x64

### Current Behaviour?

```shell
I downloaded and installed all of the prerequisites mentioned on the [TensorFlow Build from source on Windows](https://www.tensorflow.org/install/source_windows) page, ran `python configure.py`, accepted all of the defaults, and ran `bazel build //tensorflow/tools/pip_package:build_pip_package`, as that page directed.  That produces an error as given in the "relevant log output" section.
```

### Standalone code to reproduce the issue

```shell
Install Python 3.9.7.
Install Bazel 5.0.0.
Install Visual Studio Build Tools 2019.
Open an elevated "x64 Native Tools Command Prompt for VS 2019" and run the following commands.
git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow
git switch r2.9
python -m venv venv
venv\Scripts\activate
pip3 install -U six numpy wheel packaging
pip3 install -U keras_preprocessing --no-deps
python configure.py
bazel build //tensorflow/tools/pip_package:build_pip_package
```

### Relevant log output

```shell
(venv) C:\Users\Tenchumaru\Documents\GitHub\tensorflow>python configure.py
You have bazel 5.0.0 installed.
Please specify the location of python. [Default is C:\Users\Tenchumaru\Documents\GitHub\tensorflow\venv\Scripts\python.exe]:


Found possible Python library paths:
  C:\Users\Tenchumaru\Documents\GitHub\tensorflow\venv\lib\site-packages
Please input the desired Python library path to use.  Default is [C:\Users\Tenchumaru\Documents\GitHub\tensorflow\venv\lib\site-packages]

Do you wish to build TensorFlow with ROCm support? [y/N]:
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]:
No CUDA support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]:


Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]:
Eigen strong inline overridden.

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]:
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=mkl_aarch64    # Build with oneDNN and Compute Library for the Arm Architecture (ACL).
        --config=monolithic     # Config for mostly static monolithic build.
        --config=numa           # Build with NUMA support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
        --config=v1             # Build with TensorFlow 1 API instead of TF 2 API.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=nogcp          # Disable GCP support.
        --config=nonccl         # Disable NVIDIA NCCL support.

(venv) C:\Users\Tenchumaru\Documents\GitHub\tensorflow>bazel build //tensorflow/tools/pip_package:build_pip_package
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=147
INFO: Reading rc options for 'build' from c:\users\tenchumaru\documents\github\tensorflow\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=C:/Users/Tenchumaru/Documents/GitHub/tensorflow/venv/Scripts/python.exe
INFO: Reading rc options for 'build' from c:\users\tenchumaru\documents\github\tensorflow\.bazelrc:
  'build' options: --define framework_shared_object=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library
INFO: Reading rc options for 'build' from c:\users\tenchumaru\documents\github\tensorflow\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=C:/Users/Tenchumaru/Documents/GitHub/tensorflow/venv/Scripts/python.exe --action_env PYTHON_LIB_PATH=C:/Users/Tenchumaru/Documents/GitHub/tensorflow/venv/lib/site-packages --python_path=C:/Users/Tenchumaru/Documents/GitHub/tensorflow/venv/Scripts/python.exe --copt=/d2ReducedOptimizeHugeFunctions --host_copt=/d2ReducedOptimizeHugeFunctions --define=override_eigen_strong_inline=true
INFO: Reading rc options for 'build' from c:\users\tenchumaru\documents\github\tensorflow\.bazelrc:
  'build' options: --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/ir,tensorflow/compiler/mlir/tfrt/tests/analysis,tensorflow/compiler/mlir/tfrt/tests/jit,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_tfrt,tensorflow/compiler/mlir/tfrt/tests/tf_to_corert,tensorflow/compiler/mlir/tfrt/tests/tf_to_tfrt_data,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/common,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/graph_executor,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
INFO: Found applicable config definition build:short_logs in file c:\users\tenchumaru\documents\github\tensorflow\.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file c:\users\tenchumaru\documents\github\tensorflow\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:windows in file c:\users\tenchumaru\documents\github\tensorflow\.bazelrc: --copt=/W0 --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=/experimental:preprocessor --host_copt=/experimental:preprocessor --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --verbose_failures --features=compiler_param_file --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file c:\users\tenchumaru\documents\github\tensorflow\.bazelrc: --define framework_shared_object=false
INFO: Repository llvm-project instantiated at:
  C:/users/tenchumaru/documents/github/tensorflow/WORKSPACE:15:14: in <toplevel>
  C:/users/tenchumaru/documents/github/tensorflow/tensorflow/workspace2.bzl:880:21: in workspace
  C:/users/tenchumaru/documents/github/tensorflow/tensorflow/workspace2.bzl:519:15: in _tf_repositories
  C:/users/tenchumaru/documents/github/tensorflow/third_party/llvm/setup.bzl:22:19: in llvm_setup
Repository rule llvm_configure defined at:
  C:/users/tenchumaru/_bazel_tenchumaru/vswyg4al/external/llvm-raw/utils/bazel/configure.bzl:83:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'llvm-project':
   Traceback (most recent call last):
        File "C:/users/tenchumaru/_bazel_tenchumaru/vswyg4al/external/llvm-raw/utils/bazel/configure.bzl", line 73, column 25, in _llvm_configure_impl
                _overlay_directories(repository_ctx)
        File "C:/users/tenchumaru/_bazel_tenchumaru/vswyg4al/external/llvm-raw/utils/bazel/configure.bzl", line 62, column 13, in _overlay_directories
                fail(("Failed to execute overlay script: '{cmd}'\n" +
Error in fail: Failed to execute overlay script: 'C:/Users/Tenchumaru/Documents/GitHub/tensorflow/venv/Scripts/python.exe C:/users/tenchumaru/_bazel_tenchumaru/vswyg4al/external/llvm-raw/utils/bazel/overlay_directories.py --src C:/users/tenchumaru/_bazel_tenchumaru/vswyg4al/external/llvm-raw --overlay C:/users/tenchumaru/_bazel_tenchumaru/vswyg4al/external/llvm-raw/utils/bazel/llvm-project-overlay --target .'
Exited with code 1
stdout:

stderr:
Traceback (most recent call last):
  File "C:\users\tenchumaru\_bazel_tenchumaru\vswyg4al\external\llvm-raw\utils\bazel\overlay_directories.py", line 92, in <module>
    main(parse_arguments())
  File "C:\users\tenchumaru\_bazel_tenchumaru\vswyg4al\external\llvm-raw\utils\bazel\overlay_directories.py", line 80, in main
    _symlink_abs(os.path.join(args.overlay, relpath),
  File "C:\users\tenchumaru\_bazel_tenchumaru\vswyg4al\external\llvm-raw\utils\bazel\overlay_directories.py", line 64, in _symlink_abs
    os.symlink(os.path.abspath(from_path), os.path.abspath(to_path))
OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\users\\tenchumaru\\_bazel_tenchumaru\\vswyg4al\\external\\llvm-raw\\utils\\bazel\\llvm-project-overlay\\.bazelignore' -> 'C:\\users\\tenchumaru\\_bazel_tenchumaru\\vswyg4al\\external\\llvm-project\\.bazelignore'

ERROR: C:/users/tenchumaru/documents/github/tensorflow/WORKSPACE:15:14: fetching llvm_configure rule //external:llvm-project: Traceback (most recent call last):
        File "C:/users/tenchumaru/_bazel_tenchumaru/vswyg4al/external/llvm-raw/utils/bazel/configure.bzl", line 73, column 25, in _llvm_configure_impl
                _overlay_directories(repository_ctx)
        File "C:/users/tenchumaru/_bazel_tenchumaru/vswyg4al/external/llvm-raw/utils/bazel/configure.bzl", line 62, column 13, in _overlay_directories
                fail(("Failed to execute overlay script: '{cmd}'\n" +
Error in fail: Failed to execute overlay script: 'C:/Users/Tenchumaru/Documents/GitHub/tensorflow/venv/Scripts/python.exe C:/users/tenchumaru/_bazel_tenchumaru/vswyg4al/external/llvm-raw/utils/bazel/overlay_directories.py --src C:/users/tenchumaru/_bazel_tenchumaru/vswyg4al/external/llvm-raw --overlay C:/users/tenchumaru/_bazel_tenchumaru/vswyg4al/external/llvm-raw/utils/bazel/llvm-project-overlay --target .'
Exited with code 1
stdout:

stderr:
Traceback (most recent call last):
  File "C:\users\tenchumaru\_bazel_tenchumaru\vswyg4al\external\llvm-raw\utils\bazel\overlay_directories.py", line 92, in <module>
    main(parse_arguments())
  File "C:\users\tenchumaru\_bazel_tenchumaru\vswyg4al\external\llvm-raw\utils\bazel\overlay_directories.py", line 80, in main
    _symlink_abs(os.path.join(args.overlay, relpath),
  File "C:\users\tenchumaru\_bazel_tenchumaru\vswyg4al\external\llvm-raw\utils\bazel\overlay_directories.py", line 64, in _symlink_abs
    os.symlink(os.path.abspath(from_path), os.path.abspath(to_path))
OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\users\\tenchumaru\\_bazel_tenchumaru\\vswyg4al\\external\\llvm-raw\\utils\\bazel\\llvm-project-overlay\\.bazelignore' -> 'C:\\users\\tenchumaru\\_bazel_tenchumaru\\vswyg4al\\external\\llvm-project\\.bazelignore'

INFO: Repository build_bazel_rules_android instantiated at:
  C:/users/tenchumaru/documents/github/tensorflow/WORKSPACE:15:14: in <toplevel>
  C:/users/tenchumaru/documents/github/tensorflow/tensorflow/workspace2.bzl:880:21: in workspace
  C:/users/tenchumaru/documents/github/tensorflow/tensorflow/workspace2.bzl:785:20: in _tf_repositories
  C:/users/tenchumaru/documents/github/tensorflow/third_party/repo.bzl:128:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  C:/users/tenchumaru/documents/github/tensorflow/third_party/repo.bzl:81:35: in <toplevel>
INFO: Repository flatbuffers instantiated at:
  C:/users/tenchumaru/documents/github/tensorflow/WORKSPACE:15:14: in <toplevel>
  C:/users/tenchumaru/documents/github/tensorflow/tensorflow/workspace2.bzl:873:28: in workspace
  C:/users/tenchumaru/documents/github/tensorflow/tensorflow/workspace2.bzl:66:16: in _initialize_third_party
  C:/users/tenchumaru/documents/github/tensorflow/third_party/flatbuffers/workspace.bzl:6:20: in repo
  C:/users/tenchumaru/documents/github/tensorflow/third_party/repo.bzl:128:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  C:/users/tenchumaru/documents/github/tensorflow/third_party/repo.bzl:81:35: in <toplevel>
ERROR: C:/users/tenchumaru/documents/github/tensorflow/tensorflow/tools/pip_package/BUILD:277:10: //tensorflow/tools/pip_package:build_pip_package depends on //tensorflow/compiler/mlir/tensorflow:gen_mlir_passthrough_op_py in repository @ which failed to fetch. no such package '@llvm-project//mlir': Failed to execute overlay script: 'C:/Users/Tenchumaru/Documents/GitHub/tensorflow/venv/Scripts/python.exe C:/users/tenchumaru/_bazel_tenchumaru/vswyg4al/external/llvm-raw/utils/bazel/overlay_directories.py --src C:/users/tenchumaru/_bazel_tenchumaru/vswyg4al/external/llvm-raw --overlay C:/users/tenchumaru/_bazel_tenchumaru/vswyg4al/external/llvm-raw/utils/bazel/llvm-project-overlay --target .'
Exited with code 1
stdout:

stderr:
Traceback (most recent call last):
  File "C:\users\tenchumaru\_bazel_tenchumaru\vswyg4al\external\llvm-raw\utils\bazel\overlay_directories.py", line 92, in <module>
    main(parse_arguments())
  File "C:\users\tenchumaru\_bazel_tenchumaru\vswyg4al\external\llvm-raw\utils\bazel\overlay_directories.py", line 80, in main
    _symlink_abs(os.path.join(args.overlay, relpath),
  File "C:\users\tenchumaru\_bazel_tenchumaru\vswyg4al\external\llvm-raw\utils\bazel\overlay_directories.py", line 64, in _symlink_abs
    os.symlink(os.path.abspath(from_path), os.path.abspath(to_path))
OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\users\\tenchumaru\\_bazel_tenchumaru\\vswyg4al\\external\\llvm-raw\\utils\\bazel\\llvm-project-overlay\\.bazelignore' -> 'C:\\users\\tenchumaru\\_bazel_tenchumaru\\vswyg4al\\external\\llvm-project\\.bazelignore'

ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.685s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    currently loading: tensorflow/lite/python ... (3 packages)
    Fetching https://storage.googleapis.com/mirror.tensorflow.org/github.com/bazelbuild/rules_android/archive/v0.1.1.zip
    Fetching https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/flatbuffers/archive/v1.12.0.tar.gz
```
</details>

**Comment by gadagashwini** [comment]
Hi @cidzerda-unity,
Tensorflow build need Developer Mode to be turned on. The command prompt must be “Run as Admin” for the bazel build. 

Build the TensorFlow C++ DLL with this command:
`bazel build tensorflow:tensorflow.dll
`

Follow the workaround mentioned on similar issue [here](https://discuss.tensorflow.org/t/error-building-tensorflow-2-8-in-windows-10/7984/13?u=ashwini_gadag). Thank you!

**Comment by cidzerda-unity** [comment]
The output is different but it still fails.
```
(venv) C:\Users\Tenchumaru\Documents\GitHub\tensorflow>bazel build tensorflow:tensorflow.dll
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=147
INFO: Reading rc options for 'build' from c:\users\tenchumaru\documents\github\tensorflow\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=C:/Users/Tenchumaru/Documents/GitHub/tensorflow/venv/Scripts/python.exe
INFO: Reading rc options for 'build' from c:\users\tenchumaru\documents\github\tensorflow\.bazelrc:
  'build' options: --define framework_shared_object=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library
INFO: Reading rc options for 'build' from c:\users\tenchumaru\documents\github\tensorflow\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=C:/Users/Tenchumaru/Documents/GitHub/tensorflow/venv/Scripts/python.exe --action_env PYTHON_LIB_PATH=C:/Users/Tenchumaru/Documents/GitHub/tensorflow/venv/lib/site-packages --python_path=C:/Users/Tenchumaru/Documents/GitHub/tensorflow/venv/Scripts/python.exe --copt=/d2ReducedOptimizeHugeFunctions --host_copt=/d2ReducedOptimizeHugeFunctions --define=override_eigen_strong_inline=true
INFO: Reading rc options for 'build' from c:\users\tenchumaru\documents\github\tensorflow\.bazelrc:
  'build' options: --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/ir,tensorflow/compiler/mlir/tfrt/tests/analysis,tensorflow/compiler/mlir/tfrt/tests/jit,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_tfrt,tensorflow/compiler/mlir/tfrt/tests/tf_to_corert,tensorflow/compiler/mlir/tfrt/tests/tf_to_tfrt_data,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/common,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/graph_executor,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
INFO: Found applicable config definition build:short_logs in file c:\users\tenchumaru\documents\github\tensorflow\.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file c:\users\tenchumaru\documents\github\tensorflow\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:windows in file c:\users\tenchumaru\documents\github\tensorflow\.bazelrc: --copt=/W0 --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=/experimental:preprocessor --host_copt=/experimental:preprocessor --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --verbose_failures --features=compiler_param_file --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file c:\users\tenchumaru\documents\github\tensorflow\.bazelrc: --define framework_shared_object=false
INFO: Repository local_execution_config_python instantiated at:
  C:/users/tenchumaru/documents/github/tensorflow/WORKSPACE:15:14: in <toplevel>
  C:/users/tenchumaru/documents/github/tensorflow/tensorflow/workspace2.bzl:870:19: in workspace
  C:/users/tenchumaru/documents/github/tensorflow/tensorflow/workspace2.bzl:91:27: in _tf_toolchains
  C:/users/tenchumaru/documents/github/tensorflow/tensorflow/tools/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  C:/users/tenchumaru/documents/github/tensorflow/tensorflow/tools/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  C:/users/tenchumaru/documents/github/tensorflow/third_party/py/python_configure.bzl:279:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/users/tenchumaru/documents/github/tensorflow/third_party/py/python_configure.bzl", line 212, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/users/tenchumaru/documents/github/tensorflow/third_party/py/python_configure.bzl", line 143, column 52, in _check_python_bin
                result = raw_exec(repository_ctx, [get_bash_bin(repository_ctx), "-c", cmd])
        File "C:/users/tenchumaru/documents/github/tensorflow/third_party/remote_config/common.bzl", line 88, column 26, in get_bash_bin
                bash_bin_path = which(repository_ctx, "bash")
        File "C:/users/tenchumaru/documents/github/tensorflow/third_party/remote_config/common.bzl", line 27, column 22, in which
                out = execute(
        File "C:/users/tenchumaru/documents/github/tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
INFO: Could not find files for the given pattern(s).
ERROR: C:/users/tenchumaru/documents/github/tensorflow/WORKSPACE:15:14: fetching local_python_configure rule //external:local_execution_config_python: Traceback (most recent call last):
        File "C:/users/tenchumaru/documents/github/tensorflow/third_party/py/python_configure.bzl", line 212, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/users/tenchumaru/documents/github/tensorflow/third_party/py/python_configure.bzl", line 143, column 52, in _check_python_bin
                result = raw_exec(repository_ctx, [get_bash_bin(repository_ctx), "-c", cmd])
        File "C:/users/tenchumaru/documents/github/tensorflow/third_party/remote_config/common.bzl", line 88, column 26, in get_bash_bin
                bash_bin_path = which(repository_ctx, "bash")
        File "C:/users/tenchumaru/documents/github/tensorflow/third_party/remote_config/common.bzl", line 27, column 22, in which
                out = execute(
        File "C:/users/tenchumaru/documents/github/tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
INFO: Could not find files for the given pattern(s).
INFO: Repository go_sdk instantiated at:
  C:/users/tenchumaru/documents/github/tensorflow/WORKSPACE:23:14: in <toplevel>
  C:/users/tenchumaru/documents/github/tensorflow/tensorflow/workspace0.bzl:134:20: in workspace
  C:/users/tenchumaru/_bazel_tenchumaru/vswyg4al/external/com_github_grpc_grpc/bazel/grpc_extra_deps.bzl:36:27: in grpc_extra_deps
  C:/users/tenchumaru/_bazel_tenchumaru/vswyg4al/external/io_bazel_rules_go/go/toolchain/toolchains.bzl:379:28: in go_register_toolchains
  C:/users/tenchumaru/_bazel_tenchumaru/vswyg4al/external/io_bazel_rules_go/go/private/sdk.bzl:65:21: in go_download_sdk
Repository rule _go_download_sdk defined at:
  C:/users/tenchumaru/_bazel_tenchumaru/vswyg4al/external/io_bazel_rules_go/go/private/sdk.bzl:53:35: in <toplevel>
ERROR: Analysis of target '//tensorflow:tensorflow.dll' failed; build aborted: Repository command failed
INFO: Could not find files for the given pattern(s).
INFO: Elapsed time: 0.498s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded, 0 targets configured)
    Fetching @local_config_python; fetching
    Fetching @io_bazel_rules_docker; Cloning 9bfcd7dbf0294ed9d11a99da6363fc28df904502 of https://github.com/bazelbuild/rules_docker.git
    Fetching https://dl.google.com/go/go1.12.5.windows-amd64.zip
```

**Comment by gadagashwini** [comment]
Hi @cidzerda-unity, You need to install `MSYS2`. [Install MSYS2](https://www.msys2.org/) for the bin tools needed to build TensorFlow. Make sure all the pre-required software installed. Kindly follow the instructions mentioned [here](https://www.tensorflow.org/install/source_windows). Thank you!

**Comment by cidzerda-unity** [comment]
We have a different solution now so this is no longer a problem.
