### ISSUE TITLE
MatrixTriangularSolve error: "InvalidArgumentError: Input matrix is not invertible."

### ISSUE THREAD

**Issue by hosford42** [tensorflow/tensorflow#57003]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

v2.7.0-rc1-69-gc256c071bb2

### Custom Code

No

### OS Platform and Distribution

Ubuntu 20.04.4 LTS

### Mobile device

n/a

### Python version

3.8.10

### Bazel version

n/a

### GCC/Compiler version

n/a

### CUDA/cuDNN version

n/a

### GPU model and memory

n/a

### Current Behaviour?

When a matrix is not invertible, I get an exception, `tensorflow.python.framework.errors_impl.InvalidArgumentError: Input matrix is not invertible. [Op:MatrixTriangularSolve]`, while computing the gradient.

I expected the gradient to be filled with NaN values in the appropriate locations, as occurs on the forward pass.

In the code sample I provide below, note that there are two sets of data stored in `x`. The first one has an ill-defined cholesky decomposition of the covariance matrix, whereas the second one is fine. I could still use the gradient of the second one to adjust my parameters, despite it being in the same batch with the first one, but I am prevented from doing so because the MatrixTriangularSolve operation raises a hard exception rather than filling the appropriate portion of the gradient tensor with NaNs (as is the typical behavior for other ops). Even if I split the data into separate batches, Keras will still choke on this hard exception and fail to complete the training epoch.

If MatrixTriangularSolve returns NaNs in the gradient, users can add their own code to assert that NaNs are not present in the gradient and raise a hard exception, if that is the desired behavior. Or, importantly, we have the option to use a function with a custom gradient on the input tensor and block the NaN gradients from corrupting our parameters while continuing to train. But as long as MatrixTriangularSolve raises an exception itself, users are left with little to no control over how the problem is handled.

### Standalone code to reproduce the issue

```python3
import tensorflow as tf
import tensorflow_probability as tfp

x = tf.Variable([[[-0.96169615, 0.03600049, -0.86897445],
                  [0.14993548, 0.32782674, 0.05467033],
                  [0.70350194, 0.45990896, 0.24882722]],
                 [[0.19966352, 0.22277904, 0.18279016],
                  [0.996189, 0.8356074, 0.32451844],
                  [0.9954922, 0.95547783, 0.7614579]]])
with tf.GradientTape() as tape:
    y = tfp.stats.cholesky_covariance(x, sample_axis=1)
    tf.print(y)
g = tape.gradient(y, x)
```

### Relevant log output

```python3
2022-08-03 15:25:26.880273: W tensorflow/core/kernels/linalg/cholesky_op.cc:56] Cholesky decomposition was not successful. Eigen::LLT failed with error code 1. Filling lower-triangular output with NaNs.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-106-5ae22a61c2ce>", line 10, in <module>
    g = tape.gradient(y, x)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/backprop.py", line 1084, in gradient
    flat_grad = imperative_grad.imperative_grad(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/imperative_grad.py", line 71, in imperative_grad
    return pywrap_tfe.TFE_Py_TapeGradient(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/backprop.py", line 159, in _gradient_function
    return grad_fn(mock_op, *out_grads)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/linalg_grad.py", line 471, in _CholeskyGrad
    l_inverse = linalg_ops.matrix_triangular_solve(l,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py", line 7107, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input matrix is not invertible. [Op:MatrixTriangularSolve]
[[[nan 0 -2.78880322e+11]
  [nan nan 0]
  [nan nan nan]]
 [[0.375321597 0 0]
  [0.317106605 0.049177371 0]
  [0.169663742 0.178507909 0.000427246094]]]
```
</details>

**Comment by mohantym** [comment]
Hi @hosford42 !
This issue seems to be resolving in [2.9](https://colab.sandbox.google.com/gist/mohantym/b18b6978b2039a5f3f9d754c966d0241/git_57003.ipynb#scrollTo=dBaQkf4v_hKD) and [nightly](https://colab.sandbox.google.com/gist/mohantym/6869348fa0ebb2cf73cde51b33974e8a/git_57003.ipynb#scrollTo=dBaQkf4v_hKD) . Could you let us know from your end.
Thank you!

**Comment by hosford42** [comment]
@mohantym I'll take a look tomorrow. Thank you, and sorry for the delayed response.

**Comment by mohantym** [comment]
@hosford42 !
Please give us an update after your trial.
Thank you!

**Comment by hosford42** [comment]
I've confirmed it works as expected with tensorflow 2.9.1. I'll go ahead and close the issue. Thanks!
