### ISSUE TITLE
ValueError: Protocol message has no oneof "optional_autotune_algorithm" field.

### ISSUE THREAD

**Issue by CharlesbrownK** [tensorflow/tensorflow#57036]
I just start learning tensorflow object detection API. I'm using [this video](https://www.youtube.com/watch?v=yqkISICHH-U) to learn tensorflow object detection. At 8553s, I run the same code, but my command prompt said ```ValueError: Protocol message has no oneof "optional_autotune_algorithm" field.``` I have no idea how to solve this. I use 2.9.1 tensorflow, 3.9.0 python, and Windows os. Also, I don't use cudnn because I use Radeon rx580.

Below is all of my error:
```
Traceback (most recent call last):
  File "C:\Tensorflow-object-detection\TFODCourse\Tensorflow\models\research\object_detection\model_main_tf2.py", line 114, in <module>
    tf.compat.v1.app.run()
  File "C:\Tensorflow-object-detection\TFODCourse\tfod\lib\site-packages\tensorflow\python\platform\app.py", line 36, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Tensorflow-object-detection\TFODCourse\tfod\lib\site-packages\absl\app.py", line 312, in run
    _run_main(main, args)
  File "C:\Tensorflow-object-detection\TFODCourse\tfod\lib\site-packages\absl\app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "C:\Tensorflow-object-detection\TFODCourse\Tensorflow\models\research\object_detection\model_main_tf2.py", line 105, in main
    model_lib_v2.train_loop(
  File "C:\Tensorflow-object-detection\TFODCourse\tfod\lib\site-packages\object_detection-0.1-py3.9.egg\object_detection\model_lib_v2.py", line 605, in train_loop
    load_fine_tune_checkpoint(
  File "C:\Tensorflow-object-detection\TFODCourse\tfod\lib\site-packages\object_detection-0.1-py3.9.egg\object_detection\model_lib_v2.py", line 401, in load_fine_tune_checkpoint
    _ensure_model_is_built(model, input_dataset, unpad_groundtruth_tensors)
  File "C:\Tensorflow-object-detection\TFODCourse\tfod\lib\site-packages\object_detection-0.1-py3.9.egg\object_detection\model_lib_v2.py", line 161, in _ensure_model_is_built
    features, labels = iter(input_dataset).next()
  File "C:\Tensorflow-object-detection\TFODCourse\tfod\lib\site-packages\tensorflow\python\distribute\input_lib.py", line 1431, in __iter__
    iterators = _create_iterators_per_worker(
  File "C:\Tensorflow-object-detection\TFODCourse\tfod\lib\site-packages\tensorflow\python\distribute\input_lib.py", line 1857, in _create_iterators_per_worker
    iterator = _SingleWorkerOwnedDatasetIterator(
  File "C:\Tensorflow-object-detection\TFODCourse\tfod\lib\site-packages\tensorflow\python\distribute\input_lib.py", line 1761, in __init__
    super(_SingleWorkerOwnedDatasetIterator,
  File "C:\Tensorflow-object-detection\TFODCourse\tfod\lib\site-packages\tensorflow\python\distribute\input_lib.py", line 1585, in __init__
    self._make_iterator()
  File "C:\Tensorflow-object-detection\TFODCourse\tfod\lib\site-packages\tensorflow\python\distribute\input_lib.py", line 1792, in _make_iterator
    self._create_owned_multi_device_iterator()
  File "C:\Tensorflow-object-detection\TFODCourse\tfod\lib\site-packages\tensorflow\python\distribute\input_lib.py", line 1783, in _create_owned_multi_device_iterator
    self._iterator = multi_device_iterator_ops.OwnedMultiDeviceIterator(
  File "C:\Tensorflow-object-detection\TFODCourse\tfod\lib\site-packages\tensorflow\python\data\ops\multi_device_iterator_ops.py", line 473, in __init__
    experimental_slack = dataset.options().experimental_slack
  File "C:\Tensorflow-object-detection\TFODCourse\tfod\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 4010, in options
    return self._dataset.options()
  File "C:\Tensorflow-object-detection\TFODCourse\tfod\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 453, in options
    options = self._options_tensor_to_options(self._options())
  File "C:\Tensorflow-object-detection\TFODCourse\tfod\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 443, in _options_tensor_to_options
    options._from_proto(pb)  # pylint: disable=protected-access
  File "C:\Tensorflow-object-detection\TFODCourse\tfod\lib\site-packages\tensorflow\python\data\ops\options.py", line 610, in _from_proto
    self.autotune._from_proto(pb.autotune_options)  # pylint: disable=protected-access
  File "C:\Tensorflow-object-detection\TFODCourse\tfod\lib\site-packages\tensorflow\python\data\ops\options.py", line 241, in _from_proto
    if pb.WhichOneof("optional_autotune_algorithm") is not None:
ValueError: Protocol message has no oneof "optional_autotune_algorithm" field.
```

**Comment by sushreebarsa** [comment]
@CharlesbrownK 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thank you!
