### ISSUE TITLE
Android digit_classifier not working at all

### ISSUE THREAD

**Issue by bogdantmm92** [tensorflow/tensorflow#57064]
The android [digit_classifier](https://github.com/tensorflow/examples/tree/master/lite/examples/digit_classifier/android) is not detecting the correct digit.

**Comment by mohantym** [comment]
Hi @bogdantmm92 !
Work around is to use CNN instead of defaults one in the model part. Once you get the lite model using CNN upload it to assets  file.

Attached [gist ](https://colab.sandbox.google.com/gist/mohantym/52654626843322ed1d05d05fa857bdd0/mnist_tflite.ipynb)for reference.

**Comment by bogdantmm92** [comment]
Hey @mohantym that doesn't seem to help. The app crashes when initializing the interpreter. 
Commenting out this line `options.setUseNNAPI(true)` fixed the crash but not the predictions.
I get the same random predictions. Could it be something in the format of the pixels fed to the tflite model?

**Comment by mohantym** [comment]
@bogdantmm92 ! 

What is your Android and TF version. I am not getting crash here in Android Chipmunk and Pixel 5 in emulator or Also in Samsung Galaxy A20s. 
I agree current TFlite model in asset not efficient , But it was better after uncommenting the CNN code snippet mentioned in above gist.

Thank you!

**Comment by bogdantmm92** [comment]
Galaxy S22, Android 12.

`/org.tensorflow.lite.examples.digitclassifier E/AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
    Process: org.tensorflow.lite.examples.digitclassifier, PID: 5290
    java.lang.IllegalArgumentException: Internal error: Error applying delegate: 
        at org.tensorflow.lite.NativeInterpreterWrapper.createInterpreter(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:105)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:72)
        at org.tensorflow.lite.NativeInterpreterWrapperExperimental.<init>(NativeInterpreterWrapperExperimental.java:44)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:227)
        at org.tensorflow.lite.examples.digitclassifier.DigitClassifier.initializeInterpreter(DigitClassifier.kt:52)
        at org.tensorflow.lite.examples.digitclassifier.DigitClassifier.access$initializeInterpreter(DigitClassifier.kt:18)
        at org.tensorflow.lite.examples.digitclassifier.DigitClassifier$initialize$1.run(DigitClassifier.kt:34)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)`

**Comment by mohantym** [comment]
Ok @bogdantmm92 !
Thanks for the update.

@sachinprasadhs !
Could you look at this issue.

Thank you!

**Comment by bogdantmm92** [comment]
Attaching a [link](https://drive.google.com/file/d/1SumAwiVQx36fkbBwZ9zW8Mcg7_3PDiE7/view?usp=sharing) to the tflite model that crashes on Android.

**Comment by bogdantmm92** [comment]
It looks that Conv2D filter doesn't work with the tflite option `options.setUseNNAPI(true)`. If I remove this line `options.setUseNNAPI(true),` the app runs fine

**Comment by pjpratik** [comment]
Hi @bogdantmm92 

The codelabs for [digit classifier](https://developer.android.com/codelabs/digit-classifier-tflite#0) provides a way of imporving the digit classification accuracy by using image augmentation. 

Please try [this](https://developer.android.com/codelabs/digit-classifier-tflite#6) colab which helps to imporve accuracy and let us know if it helps.

Thank you.

**Comment by pjpratik** [comment]
Closing as stale. Please reopen if you'd like to work on this further. Thanks!
