### ISSUE TITLE
AttributeError: type object 'NewBase' has no attribute 'is_abstract'  when I have update SIX

### ISSUE THREAD

**Issue by anthonyyuan** [tensorflow/tensorflow#5707]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/Library/Python/2.7/site-packages/tensorflow/python/__init__.py", line 98, in <module>
    from tensorflow.python.platform import test
  File "/Library/Python/2.7/site-packages/tensorflow/python/platform/test.py", line 63, in <module>
    from tensorflow.python.framework import test_util
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/test_util.py", line 43, in <module>
    from tensorflow.python.platform import googletest
  File "/Library/Python/2.7/site-packages/tensorflow/python/platform/googletest.py", line 32, in <module>
    from tensorflow.python.platform import benchmark  # pylint: disable=unused-import
  File "/Library/Python/2.7/site-packages/tensorflow/python/platform/benchmark.py", line 122, in <module>
    class Benchmark(six.with_metaclass(_BenchmarkRegistrar, object)):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six.py", line 566, in with_metaclass
    return meta("NewBase", bases, {})
  File "/Library/Python/2.7/site-packages/tensorflow/python/platform/benchmark.py", line 117, in __new__
    if not newclass.is_abstract():
AttributeError: type object 'NewBase' has no attribute 'is_abstract'

**Comment by prb12** [comment]
Please could you provide the information requested in the issue reporting template.

**Comment by michaelisard** [comment]
Closing due to lack of response.
