### ISSUE TITLE
 Compile failed with c++17 using gcc

### ISSUE THREAD

**Issue by yinciki** [tensorflow/tensorflow#57127]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

tf 2.7

### Custom Code

No

### Python version

3.6.8

### Bazel version

4.2.1

### GCC/Compiler version

8.3.1

### CUDA/cuDNN version

11.0/8

### GPU model and memory

Nvidia A100

### Current Behaviour?

```shell
I compiled tf 2.7 with command: "bazel build --config=cuda --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --cxxopt=-std=c++1z //tensorflow/tools/pip_package:build_pip_package" and this error occured:
ImportError: /root/.cache/bazel/_bazel_root/75033a8ead962ac817396f45646bf4d8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN10tensorflow11GetNodeAttrERKNS_9AttrSliceEN4absl12lts_2021032411string_viewEPNS_18PartialTensorShapeE

I used c++ 17 since I needed to import rocksdb(c++17 required) in my project, and followed this 
 issue(https://github.com/tensorflow/tensorflow/issues/23561) I rebuilt tf.
Any workaround suggest?
```

### Standalone code to reproduce the issue

```shell
bazel build --config=cuda --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --cxxopt=-std=c++1z //tensorflow/tools/pip_package:build_pip_package
```

### Relevant log output

```shell
ERROR: /root/git/tensorflow/tensorflow/BUILD:1258:19: Executing genrule //tensorflow:tf_python_api_gen_v2 failed (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/75033a8ead962ac817396f45646bf4d8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: /root/.cache/bazel/_bazel_root/75033a8ead962ac817396f45646bf4d8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN10tensorflow11GetNodeAttrERKNS_9AttrSliceEN4absl12lts_2021032411string_viewEPNS_18PartialTensorShapeE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/75033a8ead962ac817396f45646bf4d8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 26, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/root/.cache/bazel/_bazel_root/75033a8ead962ac817396f45646bf4d8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 40, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/root/.cache/bazel/_bazel_root/75033a8ead962ac817396f45646bf4d8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 80, in <module>
    f'{traceback.format_exc()}'
ImportError: Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/75033a8ead962ac817396f45646bf4d8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: /root/.cache/bazel/_bazel_root/75033a8ead962ac817396f45646bf4d8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN10tensorflow11GetNodeAttrERKNS_9AttrSliceEN4absl12lts_2021032411string_viewEPNS_18PartialTensorShapeE


Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors for some common causes and solutions.
If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /root/git/tensorflow/tensorflow/tools/pip_package/BUILD:70:10 Executing genrule //tensorflow/python/keras/api:keras_python_api_gen failed (Exit 1): bash failed: error executing command
```
</details>

**Comment by mohantym** [comment]
@yinciki !
Build seems to be passing with below command.
`bazel build --config=cuda --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --cxxopt=-std=c++17 //tensorflow/tools/pip_package:build_pip_package`

Could you let us know from your end.
Thank you!

**Comment by yinciki** [comment]
> @yinciki ! Build seems to be passing with below command. `bazel build --config=cuda --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --cxxopt=-std=c++17 //tensorflow/tools/pip_package:build_pip_package`
> 
> Could you let us know from your end. Thank you!

Thanks. I tried but got the same error:
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/75033a8ead962ac817396f45646bf4d8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 26, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/root/.cache/bazel/_bazel_root/75033a8ead962ac817396f45646bf4d8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 40, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/root/.cache/bazel/_bazel_root/75033a8ead962ac817396f45646bf4d8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 80, in <module>
    f'{traceback.format_exc()}'
ImportError: Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/75033a8ead962ac817396f45646bf4d8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: /root/.cache/bazel/_bazel_root/75033a8ead962ac817396f45646bf4d8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN10tensorflow11GetNodeAttrERKNS_9AttrSliceEN4absl12lts_2021032411string_viewEPNS_18PartialTensorShapeE

**Comment by mohantym** [comment]
Hi @sachinprasadhs !
Could you look at this issue.
Thank you!

**Comment by gadagashwini** [comment]
Hi @yinciki, By default, build TF in C++ 17 mode.
Take a look at this reference [link](https://github.com/tensorflow/tensorflow/blob/master/.bazelrc#L334). Thank you!

**Comment by yinciki** [comment]
@gadagashwini Thank you for your reply!
I followed the ref and used the command : 
bazel build --config=cuda --host_cxxopt=-std=c++17 //tensorflow/tools/pip_package:build_pip_package 
and build succeeded but I found that the tf built in this way still used absl::lts_20210324::string_view which was not the new feature in c++17. Any othre suggestions ? 

detailed log:
nm -A libtensorflow_framework.so.2 2>/dev/null | grep "GetNodeAttr"
c++filt _ZN10tensorflow11GetNodeAttrERKNS_9AttrSliceEN4absl12lts_2021032411string_viewEPNS_11TensorShapeE
tensorflow::GetNodeAttr(tensorflow::AttrSlice const&, absl::lts_20210324::string_view, tensorflow::TensorShape*)

**Comment by Weili17** [comment]
> @yinciki ! Build seems to be passing with below command. `bazel build --config=cuda --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --cxxopt=-std=c++17 //tensorflow/tools/pip_package:build_pip_package`
> 
> Could you let us know from your end. Thank you!

I use theses flags to build the framework so with c++ standard, but it fails and reports linked error. Could you help to figure out what's wrong?

build cmd: bazel build --config=cuda --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --cxxopt=-std=c++17 //tensorflow:libtensorflow_cc.so

gcc version: 8.3

Linking tensorflow/libtensorflow_cc.so.2.8.4 failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc @bazel-out/k8-opt/bin/tensorflow/libtensorflow_cc.so.2.8.4-2.params
/usr/bin/ld: bazel-out/k8-opt/bin/tensorflow/core/kernels/libunique_op_gpu.pic.lo(unique_op_gpu_0.cu.pic.o): in function `tensorflow::kernel_factory::OpKernelRegistrar::OpKernelRegistrar(tensorflow::KernelDef const*, absl::lts_20210324::string_view, tensorflow::OpKernel* (*)(tensorflow::OpKernelConstruction*))':
tmpxft_00003846_00000000-6_unique_op_gpu_0.cu.cudafe1.cpp:(.text._ZN10tensorflow14kernel_factory17OpKernelRegistrarC2EPKNS_9KernelDefEN4absl12lts_2021032411string_viewEPFPNS_8OpKernelEPNS_20OpKernelConstructionEE[_ZN10tensorflow14kernel_factory17OpKernelRegistrarC5EPKNS_9KernelDefEN4absl12lts_2021032411string_viewEPFPNS_8OpKernelEPNS_20OpKernelConstructionEE]+0x50): undefined reference to `tensorflow::kernel_factory::OpKernelRegistrar::InitInternal(tensorflow::KernelDef const*, absl::lts_20210324::string_view, std::unique_ptr<tensorflow::kernel_factory::OpKernelFactory, std::default_delete<tensorflow::kernel_factory::OpKernelFactory> >)'

**Comment by Weili17** [comment]
> @gadagashwini Thank you for your reply! I followed the ref and used the command : bazel build --config=cuda --host_cxxopt=-std=c++17 //tensorflow/tools/pip_package:build_pip_package and build succeeded but I found that the tf built in this way still used absl::lts_20210324::string_view which was not the new feature in c++17. Any othre suggestions ?
> 
> detailed log: nm -A libtensorflow_framework.so.2 2>/dev/null | grep "GetNodeAttr" c++filt _ZN10tensorflow11GetNodeAttrERKNS_9AttrSliceEN4absl12lts_2021032411string_viewEPNS_11TensorShapeE tensorflow::GetNodeAttr(tensorflow::AttrSlice const&, absl::lts_20210324::string_view, tensorflow::TensorShape*)

I met the same problem with you, did you figure out how to solve this?

![image](https://user-images.githubusercontent.com/31896190/222695778-44691e35-8b93-4742-99ff-6d848c507ba2.png)

**Comment by SuryanarayanaY** [comment]
Hi @yinciki ,

I am eager to know the status of this issue. Could you please check with latest versions and confirm whether this is still an issue. Please refer to tested configurations of bazel,python,GCC , CUDA and cuDNN versions w.r.t TF versions [here](https://www.tensorflow.org/install/source#linux).
