### ISSUE TITLE
Problems importing Tensorflow to PyCharm and IDLE

### ISSUE THREAD

**Issue by leslietso** [tensorflow/tensorflow#5715]
I am currently trying to use Tensorflow on PyCharm and IDLE. However, whenever I try to import Tensorflow (import tensorflow as tf), I get the following error:

```
Traceback (most recent call last):
  File "/Users/leslie/PycharmProjects/untitled/tensor.py", line 2, in <module>
    import tensorflow as tf
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): Library not loaded: @rpath/libcudart.8.0.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
  Reason: image not found
```

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

From looking around online, it seems that I need to install cuda on my machine. However, I do not have a NVIDIA graphics card nor a cuda-enabled card.

### Environment info
Operating System:
Mac OS 10.12
Tensorflow 0.11.0

**Comment by leslietso** [comment]
Please ignore. Somehow I had managed to install the wrong version of Tensorflow.
