### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by sidml** [tensorflow/tensorflow#57181]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

binary

### Tensorflow Version

tf 2.6

### Custom Code

Yes

### OS Platform and Distribution

Linux 5.4.0-1089, 18.04.1-Ubuntu SMP

### Python version

3.9

### GPU model and memory

v100

### Current Behaviour?

```shell
The same code works on colab. However, when I run on VM, I get Segmentation fault (core dumped). This error is very cryptic. Please let me know how to get more detailed error for easier debugging.
BTW I have also tried the latest stable tf build 2.9 and tf-nightly build. Both crash with the same error.
Thanks.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf


class ConvBlock:
    def __init__(
        self,
        c_in,
        c_out,
        kernel_size=3,
        stride=1,
        padding=1,
        bias=False,
        K=1,
        backbone="residual",
    ):
        super(ConvBlock, self).__init__()

        self.f = tf.keras.layers.Conv2D(
            c_out,
            kernel_size=kernel_size,
            strides=stride,
            padding="SAME",
            use_bias=bias,
            activation=None,
        )
        self.g = tf.keras.layers.Conv2D(
            c_out,
            kernel_size=3,
            strides=1,
            padding="SAME",
            use_bias=False,
            activation=None,
        )
        self.K = K
        self.backbone = backbone

        self.bn_out = tf.keras.layers.BatchNormalization()
        self.bn_f1 = tf.keras.layers.BatchNormalization()
        self.c_out = c_out

    def __call__(self, x):
        f = self.f(tf.keras.layers.Activation("relu")(self.bn_f1(x)))
        h = f


        bn_g = tf.keras.layers.BatchNormalization()
        h = self.g(tf.keras.layers.Activation("relu")(bn_g(h)))

        return h


def net(backbone="cnn", K=5):

    inp = tf.keras.Input((28, 28, 1))

    conv = ConvBlock(1, 1, 3, K=K, backbone=backbone)
    x = conv(inp)
    f1 = x
    x = tf.keras.layers.Activation("relu")(x)

    avg_pool = tf.keras.layers.AveragePooling2D(pool_size=(4, 4))
    x = avg_pool(x)
    f2 = x
    flatten = tf.keras.layers.Flatten()
    x = flatten(x)

    fc = tf.keras.layers.Dense(10)
    out = fc(x)

    return tf.keras.Model(inp, [out, f1, f2])

if __name__=="__main__":
    import numpy as np
    model = net(backbone="cnn")
    model.compile()
    x = np.zeros((28, 28, 1))
    print(model(x))
```

### Relevant log output

```shell
2022-08-16 14:01:30.779185: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-08-16 14:01:31.772277: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 14645 MB memory:  -> device: 0, name: Tesla V100-PCIE-16GB, pci bus id: 0001:00:00.0, compute capability: 7.0
Segmentation fault (core dumped)
```
</details>

**Comment by gadagashwini** [comment]
Hi @sidml, Use below code snippet at the beginning of the your code to Get the detailed error log.
```
import logging
logger = tf.get_logger()
logger.setLevel(logging.ERROR)
```

Complete error log of given code snippet.
```
Traceback (most recent call last):
  File "/home/gadag/57181.py", line 80, in <module>
    print(model(x))
  File "/home/gadag/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/gadag/anaconda3/lib/python3.9/site-packages/keras/engine/input_spec.py", line 248, in assert_input_compatibility
    raise ValueError(
ValueError: Exception encountered when calling layer "model" (type Functional).

Input 0 of layer "dense" is incompatible with the layer: expected axis -1 of input shape to have value 49, but received input with shape (28, 0)

Call arguments received by layer "model" (type Functional):
  • inputs=tf.Tensor(shape=(28, 28, 1), dtype=float64)
  • training=False
  • mask=None 
```
Error message says shape mismatch. Check your input data shape and expected input shape of Model. Thank you!

**Comment by sidml** [comment]
@gadagashwini 
Thanks. Yes, the input shape should have been (1, 28, 28,1). I missed it while writing this toy example.
I added the logger code snippet but I still get  only `Segmentation fault (core dumped)`. 
Is there anything else that I can do to get a more detailed error log ?
Thanks.

**Comment by gadagashwini** [comment]
Hi @sidml, Could you try the workaround mentioned [here](https://stackoverflow.com/a/13654489/14290244). Thank you!

**Comment by sidml** [comment]
@gadagashwini 
I tried the above code and i still get `get only Segmentation fault (core dumped)`.
Thanks.

**Comment by gadagashwini** [comment]
Hi @sidml, Could you try with Tf v2.9. I tried with `Tf v2.9.2`. Thank you!
