### ISSUE TITLE
TensorRT conversion: tensorflow.GraphDef exceeds maximum protobuf size of 2GB

### ISSUE THREAD

**Issue by davi000015** [tensorflow/tensorflow#57183]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

tf 2.8

### Custom Code

No

### Current Behaviour?

```shell
Hi, we have a model that we want to convert using TensorRT as supported by TensorFlow.
The original model size is 6191909 bytes, with variable size 2308318345 bytes.

Is there anyway to enable converting this model to TensorRT optimised model?
Converting using precision FP16 doesn't seem to work.
```

### Standalone code to reproduce the issue

```shell
We can reproduce by performing TensorRT optimisation on a model larger than 2GB
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/local/bin/tensord", line 33, in <module>
    sys.exit(load_entry_point('tensord', 'console_scripts', 'tensord')())
  File "/tensord/tensord/cli.py", line 61, in main
    CLI()
  File "/tensord/tensord/cli.py", line 30, in __init__
    getattr(self, args.command)()
  File "/tensord/tensord/cli.py", line 46, in optimize
    optimize.cli(sys.argv[2:])
  File "/tensord/tensord/commands/optimize.py", line 87, in cli
    optimize(**vars(args))
  File "/tensord/tensord/commands/optimize.py", line 70, in optimize
    inference_optimizer.optimize()
  File "/tensord/tensord/inference/tensorrt_optimizer.py", line 79, in optimize
    converter.convert(input_fields=params.input_fields, unpack=params.unpack)
  File "/tensord/tensord/inference/tensorrt.py", line 1213, in convert
    self._saved_model, func, frozen_func = load_frozen_func(self._input_saved_model_dir, input_fields, unpack)
  File "/tensord/tensord/inference/optimizer.py", line 76, in load_frozen_func
    frozen_func = convert_variables_to_constants_v2(concrete_func, lower_control_flow=False)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/convert_to_constants.py", line 1151, in convert_variables_to_constants_v2
    return _construct_concrete_function(func, output_graph_def,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/convert_to_constants.py", line 1076, in _construct_concrete_function
    new_func = wrap_function.function_from_graph_def(output_graph_def,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/wrap_function.py", line 655, in function_from_graph_def
    wrapped_import = wrap_function(_imports_graph_def, [])
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/wrap_function.py", line 619, in wrap_function
    func_graph.func_graph_from_py_func(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/func_graph.py", line 1161, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/wrap_function.py", line 83, in __call__
    return self.call_with_variable_creator_scope(self._fn)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/wrap_function.py", line 89, in wrapped
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/wrap_function.py", line 649, in _imports_graph_def
    importer.import_graph_def(graph_def, name="")
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/deprecation.py", line 548, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/importer.py", line 403, in import_graph_def
    return _import_graph_def_internal(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/importer.py", line 497, in _import_graph_def_internal
    with c_api_util.tf_buffer(graph_def.SerializeToString()) as serialized:
ValueError: Message tensorflow.GraphDef exceeds maximum protobuf size of 2GB: 2310494883
```
</details>

**Comment by mohantym** [comment]
Hi @davi000015 !
Yes! Protobuf has size constraint of 2GB. Could you comment in this [issue ](https://github.com/tensorflow/tensorflow/issues/51870)and close this issue as duplicate. 
Thank you!
