### ISSUE TITLE
freeze_graph not working as expected

### ISSUE THREAD

**Issue by leslietso** [tensorflow/tensorflow#5720]
I am currently attempting to export a protobuf file to Android. To do that, I generated a .pbtxt file using http://pastebin.com/HcWA0xMQ to run freeze_graph on. I saved the protobuf file as text because when I try to save it as binary and run it with freeze_graph, I get the following error:

```
Traceback (most recent call last):
  File "/Users/leslie/tensorflow-master/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 135, in <module>
    tf.app.run()
  File "/Users/leslie/tensorflow-master/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/Users/leslie/tensorflow-master/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 132, in main
    FLAGS.output_graph, FLAGS.clear_devices, FLAGS.initializer_nodes)
  File "/Users/leslie/tensorflow-master/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 98, in freeze_graph
    text_format.Merge(f.read().decode("utf-8"), input_graph_def)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x96 in position 331: invalid start byte
```

After generating the frozen graph with the .pbtxt file, I tried to run it on Android but for some reason am getting the same output every time regardless of the input. I also noticed, that the frozen graph is actually smaller than the checkpoint file even though it's supposed to be bigger according to the pre-release documentation I got ([deploying.txt](https://github.com/tensorflow/tensorflow/files/601596/deploying.txt)).

### Environment info
Operating System:
Mac OS 10.12
Tensorflow 0.11.0
Android Cyanogenmod 12

Code to create .pb file for `freeze_graph`: http://pastebin.com/HcWA0xMQ
My checkpoint file: [Y6_1476978999.zip](https://github.com/tensorflow/tensorflow/files/601598/Y6_1476978999.zip)

**Comment by skye** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
