### ISSUE TITLE
Tutorial throws error

### ISSUE THREAD

**Issue by ejboettcher** [tensorflow/tensorflow#57201]
https://github.com/tensorflow/docs/blob/master/site/en/tutorials/images/transfer_learning_with_hub.ipynb

at 
```python
result = classifier.predict(grace_hopper[np.newaxis, ...])
result.shape
```

throws the following error.
------------------------------

---------------------------------------------------------------------------
UnimplementedError                        Traceback (most recent call last)
[<ipython-input-14-c951ede0675b>](https://localhost:8080/#) in <module>
----> 1 result = classifier.predict(grace_hopper[np.newaxis, ...])
      2 result.shape

1 frames
[/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py](https://localhost:8080/#) in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     53     ctx.ensure_initialized()
     54     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 55                                         inputs, attrs, num_outputs)
     56   except core._NotOkStatusException as e:
     57     if name is not None:

UnimplementedError: Graph execution error:

Detected at node 'predict/MobilenetV2/Conv/Conv2D' defined at (most recent call last):
    File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py", line 16, in <module>
      app.launch_new_instance()
    File "/usr/local/lib/python3.7/dist-packages/traitlets/config/application.py", line 846, in launch_instance
      app.start()
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelapp.py", line 612, in start
      self.io_loop.start()
    File "/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py", line 132, in start
      self.asyncio_loop.run_forever()
    File "/usr/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
      self._run_once()
    File "/usr/lib/python3.7/asyncio/base_events.py", line 1786, in _run_once
      handle._run()
    File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
      self._context.run(self._callback, *self._args)
    File "/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py", line 758, in _run_callback
      ret = callback()
    File "/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1233, in inner
      self.run()
    File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1147, in run
      yielded = self.gen.send(value)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 365, in process_one
      yield gen.maybe_future(dispatch(*args))
    File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 326, in wrapper
      yielded = next(result)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 268, in dispatch_shell
      yield gen.maybe_future(handler(stream, idents, msg))
    File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 326, in wrapper
      yielded = next(result)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 545, in execute_request
      user_expressions, allow_stdin,
    File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 326, in wrapper
      yielded = next(result)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/ipkernel.py", line 306, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/zmqshell.py", line 536, in run_cell
      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2855, in run_cell
      raw_cell, store_history, silent, shell_futures)
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2881, in _run_cell
      return runner(coro)
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
      coro.send(None)
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3058, in run_cell_async
      interactivity=interactivity, compiler=compiler, result=result)
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3249, in run_ast_nodes
      if (await self.run_code(code, result,  async_=asy)):
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "<ipython-input-12-7db51c8d2d71>", line 4, in <module>
      hub.KerasLayer(classifier_model, input_shape=IMAGE_SHAPE+(3,))
    File "/usr/local/lib/python3.7/dist-packages/tensorflow_hub/keras_layer.py", line 153, in __init__
      self._func = load_module(handle, tags, self._load_options)
    File "/usr/local/lib/python3.7/dist-packages/tensorflow_hub/keras_layer.py", line 449, in load_module
      return module_v2.load(handle, tags=tags, options=set_load_options)
    File "/usr/local/lib/python3.7/dist-packages/tensorflow_hub/module_v2.py", line 106, in load
      obj = tf.compat.v1.saved_model.load_v2(module_path, tags=tags)
Node: 'predict/MobilenetV2/Conv/Conv2D'
DNN library is not found.
	 [[{{node predict/MobilenetV2/Conv/Conv2D}}]] [Op:__inference_predict_function_35179]

**Comment by ejboettcher** [comment]
I was able to get the tutorial to run if I forced the version to be 2.7.
```python
!pip install tensorflow==2.7
```

I would like to know how to run this tutorial using tensorflow 2.9.  Thank you.

**Comment by tilakrayal** [comment]
@ejboettcher,
I was able to execute the code on tensorflow v2.9 wiht out any errors/issues. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/26cc6f3486c85d1500aaa381f8e31228/transfer_learning_with_hub.ipynb) and please create a virtual environment and test your code again. Thank you!

**Comment by ejboettcher** [comment]
That is weird.  I ran your code fine but from the Google Tutorials in Colab I can not run the same notebook.
https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/images/transfer_learning_with_hub.ipynb

I checked and it is the same TF version.

**Comment by ejboettcher** [comment]
I found the difference!!!  I have GPU enabled and you do not.  If you switch your run time to use GPU you will run into the same issue.

This is a bug in TF.

**Comment by tilakrayal** [comment]
@ejboettcher,
I was able to execute the code without any issues on **tensorflow-gpu v2.9**. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/79917d457259f0e54275aa39e464a116/57201.ipynb).

As a workaround for the time being, you may try running **!apt install --allow-change-held-packages libcudnn8=8.1.0.77-1+cuda11.2** and let us know if that fixes your issues. Please take a look at this [comment](https://github.com/googlecolab/colabtools/issues/2600#issuecomment-1061312120) from the issue with a similar error and this bug is not related TF. Thank you!

**Comment by ejboettcher** [comment]
@tilakrayal 
Please run your lab in google Co-lab with GPU enabled.   It does not work in Google's colab.

That is the issue.  It will only run in Google's colab if you switch to version 2.7 (with GPU)  or run it without GPU in version 2.9.  


The only control I have in Co-lab is to run with and without GPU.  I really do not have control of the environment :-(.  I wish there was a requirement.txt file so that I can run it.

**Comment by tilakrayal** [comment]
@ejboettcher,
I tried to execute the code on GPU enabled only and was able to execute without any issues. Please try to execute  **!apt install --allow-change-held-packages libcudnn8=8.1.0.77-1+cuda11.2** before code. Thank you!
![image](https://user-images.githubusercontent.com/81610181/185379317-10ce8506-f90c-4110-9c49-ad56c303e9c5.png)

**Comment by ejboettcher** [comment]
Thank you @tilakrayal 
That did fix the issue of running this in CoLab with TF 2.9 + GPU.  
**BUT**
The tutorial does not run by itself without you injecting code if you are using the GPU as default.  
You either have to switch to Non GPU, switch to TF 2.7 or change  libcudnn8-dev to libcudnn8. 

The purpose of the tutorials is that it should just run in colabs so that you can focus of the material and not trouble shooting the environment.  It is really hard to trouble shoot the environment when you are not given a build eg requirements.txt file.

**Comment by tilakrayal** [comment]
@ejboettcher,
Ideally it should run but as there was an issue from google colab side, it was failing with the error which is not related to tensorflow. Please take a look at this [comment](https://github.com/googlecolab/colabtools/issues/2600#issuecomment-1061312120) from the **GoogleColab/ColabTools** team. 

As this is not from the TF related issue, I request please feel free to move this issue to closed status and raise the issue in **GoogleColab/ColabTools** repo for the assistance. Thank you!

**Comment by ejboettcher** [comment]
@tilakrayal 
I thought that you and colab were the same group.  My bad.
**BUT** could you add a co-lab work around in your tutorial until co-labs get their act together.

Take care, Issue open for me but closed for you.
