### ISSUE TITLE
testTFLiteGraphDef and similar tests in lite_test.py fail on s390x arch

### ISSUE THREAD

**Issue by rposts** [tensorflow/tensorflow#57215]
### 1. System information

- OS Platform and Distribution: Ubuntu 20.04
- TensorFlow installation: Built from source
- TensorFlow library : 2.9.1

### 2. Code

bazel test -s --config=dbg --define=tensorflow_mkldnn_contraction_kernel=0 --define tflite_with_xnnpack=false --test_tag_filters=-gpu,-benchmark-test,-v1only,-no_oss,-oss_serial -k --test_timeout 300,450,1200,3600 --build_tests_only --test_output=errors //tensorflow/lite/python:lite_test

### 3. Problem
Tensorflow Lite test (e.g., `testTFLiteGraphDef`) uses `ssd_mobilenet_v1_quantized_300x300_coco14_sync_2018_07_18.tar.gz` FrozenGraph model [here](https://github.com/tensorflow/tensorflow/blob/d8ce9f9c301d021a69953134185ab728c1c248d3/tensorflow/lite/python/lite_test.py#L1873) generated on little-endian arch.  This causes problems during import of the graph on `s390x` arch and the process fails with this error:

```
ERROR: testTFLiteGraphDef (__main__.FromFrozenGraphObjectDetection)
FromFrozenGraphObjectDetection.testTFLiteGraphDef
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/.cache/bazel/_bazel_rishi/8f98aac813e58b2da3802c4fdafe023a/execroot/org_tensorflow/bazel-out/s390x-dbg/bin/tensorflow/lite/python/lite_test.runfiles/org_tensorflow/tensorflow/python/framework/importer.py", line 499, in _import_graph_def_internal
    results = c_api.TF_GraphImportGraphDefWithResults(
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot reshape a tensor with 32 elements to shape [536870912,16777216] (9007199254740992 elements) for '{{node FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_1_depthwise/BatchNorm_Fold/scale_reshape}} = Reshape[T=DT_FLOAT, Tshape=DT_INT32](FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_1_depthwise/BatchNorm_Fold/mul, FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_1_depthwise/BatchNorm_Fold/scale_reshape/shape)' with input shapes: [32], [2] and with input tensors computed as partial shapes: input[1] = [536870912,16777216].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/.cache/bazel/_bazel_rishi/8f98aac813e58b2da3802c4fdafe023a/execroot/org_tensorflow/bazel-out/s390x-dbg/bin/tensorflow/lite/python/lite_test.runfiles/org_tensorflow/tensorflow/lite/python/lite_test.py", line 1899, in testTFLiteGraphDef
    converter = lite.TFLiteConverter.from_frozen_graph(self._graph_def_file,
  File "/home/.cache/bazel/_bazel_rishi/8f98aac813e58b2da3802c4fdafe023a/execroot/org_tensorflow/bazel-out/s390x-dbg/bin/tensorflow/lite/python/lite_test.runfiles/org_tensorflow/tensorflow/lite/python/lite.py", line 2674, in from_frozen_graph
    _import_graph_def(graph_def, name="")
  File "/home/.cache/bazel/_bazel_rishi/8f98aac813e58b2da3802c4fdafe023a/execroot/org_tensorflow/bazel-out/s390x-dbg/bin/tensorflow/lite/python/lite_test.runfiles/org_tensorflow/tensorflow/python/util/deprecation.py", line 561, in new_func
    return func(*args, **kwargs)
  File "/home/.cache/bazel/_bazel_rishi/8f98aac813e58b2da3802c4fdafe023a/execroot/org_tensorflow/bazel-out/s390x-dbg/bin/tensorflow/lite/python/lite_test.runfiles/org_tensorflow/tensorflow/python/framework/importer.py", line 403, in import_graph_def
    return _import_graph_def_internal(
  File "/home/.cache/bazel/_bazel_rishi/8f98aac813e58b2da3802c4fdafe023a/execroot/org_tensorflow/bazel-out/s390x-dbg/bin/tensorflow/lite/python/lite_test.runfiles/org_tensorflow/tensorflow/python/framework/importer.py", line 504, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: Cannot reshape a tensor with 32 elements to shape [536870912,16777216] (9007199254740992 elements) for '{{node FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_1_depthwise/BatchNorm_Fold/scale_reshape}} = Reshape[T=DT_FLOAT, Tshape=DT_INT32](FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_1_depthwise/BatchNorm_Fold/mul, FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_1_depthwise/BatchNorm_Fold/scale_reshape/shape)' with input shapes: [32], [2] and with input tensors computed as partial shapes: input[1] = [536870912,16777216].

```

After examining associated `pbtxt` file I noticed that `tensor_content` fields of the model may have contents that are in little-endian order. While a simple change to byte-swapping tensor_content prior to [MakeNode](https://github.com/tensorflow/tensorflow/blob/d8ce9f9c301d021a69953134185ab728c1c248d3/tensorflow/core/common_runtime/graph_constructor.cc#L1250) fixes the immedidate issue, subsequent calls to convert function fails with similar error.

I wanted to generate this model on `s390x` to see if there is a way around this issue. From my understanding frozen inference graphs are generated using the v1.1x release version of TensorFlow. Following the [instructions](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md) I tried to generate inference graph on `TF 2.9.1` but model generation failed with following error:

```
host:/home/tests/models/research# python ./object_detection/export_inference_graph.py     --input_type=${INPUT_TYPE}     --pipeline_config_path=${PIPELINE_CONFIG_PATH}     --trained_checkpoint_prefix=${TRAINED_CKPT_PREFIX}     --output_directory=${EXPORT_DIR}
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.11) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "./object_detection/export_inference_graph.py", line 205, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/platform/app.py", line 36, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "./object_detection/export_inference_graph.py", line 193, in main
    exporter.export_inference_graph(
  File "/home/tests/models/research/object_detection/exporter.py", line 611, in export_inference_graph
    detection_model = model_builder.build(pipeline_config.model,
  File "/home/tests/models/research/object_detection/builders/model_builder.py", line 1252, in build
    return build_func(getattr(model_config, meta_architecture), is_training,
  File "/home/tests/models/research/object_detection/builders/model_builder.py", line 402, in _build_ssd_model
    _check_feature_extractor_exists(ssd_config.feature_extractor.type)
  File "/home/tests/models/research/object_detection/builders/model_builder.py", line 267, in _check_feature_extractor_exists
    raise ValueError(
ValueError: ssd_mobilenet_v1 is not supported for tf version 2. See `model_builder.py` for features extractors compatible with different versions of Tensorflow
```

Apparently, this model is no longer supported in `TF 2.x`.

I am wondering if this testcase makes sense on big-endian archs given that reference model can no longer be generated on `TF 2.x`. Are there other ways of regenerating it so it can be consumed on `big-endian` archs?  I have already tried converting it to `SavedModel` format to no avail.

Thanks for any input.

**Comment by mohantym** [comment]
Hi @rposts!
Sorry for the late response.
Above tests seem to be passing when -v1only flag is removed. Attached [gist](https://colab.sandbox.google.com/gist/mohantym/e483f3d1a2520350dbdfc9b8416dcb5c/tensorflow-ranking.ipynb#scrollTo=vDXp-0XmqYkc) for reference.

Could you give let us know from your end.

Thank you!

**Comment by rposts** [comment]
Thanks @mohantym - that did not fix it. Remember, this problem occurs on big-endian arch (`s390x`). Do you know if there is a way to generate this model for TF 2.x? As noted above I already tried to export inference_graph as per instructions noted in the docs.

**Comment by rposts** [comment]
Closing as this may be address by https://github.com/tensorflow/tensorflow/pull/58601
