### ISSUE TITLE
Saving and loading with an empty model layer

### ISSUE THREAD

**Issue by stridge-cruxml** [tensorflow/tensorflow#57222]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

v2.8.0-rc1-32-g3f878cff5b6 2.8.0

### Custom Code

No

### OS Platform and Distribution

Ubuntu 20.04

### Python version

3.8.10

### Current Behaviour?

```shell
When trying to load a saved keras model containing an empty sequential model, an exception is thrown.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np

class TestBlock(tf.keras.Model):
  def __init__(self):
    super().__init__()
    self.shortcut = tf.keras.Sequential()
    self.dense = tf.keras.layers.Dense(5)
    self.relu = tf.keras.layers.ReLU()

  def call(self, input_vector):
    shortcut = self.shortcut(input_vector)
    dense = self.dense(input_vector)
    return self.relu(shortcut + dense)

if __name__ == "__main__":
  model = TestBlock()
  model.build((1,5))
  model.compile(loss="categorical_crossentropy")
  checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(
    filepath="checkpoints",
    save_best_only=True,
    mode="auto",
  )
  train_data = tf.data.Dataset.from_tensor_slices((np.ones((20,5)), np.zeros((20,5)))).batch(1)
  model.fit(train_data,
    epochs=1,
    callbacks=[checkpoint_callback],
  )
  print("Saving ...")
  model.save("test_model")
  print("Loading ...")
  loaded_model = tf.keras.models.load_model("test_model")
```

### Relevant log output

```shell
2022-08-19 12:17:00.131391: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in pe
rformance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-08-19 12:17:00.599398: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 6666 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 206
0 SUPER, pci bus id: 0000:29:00.0, compute capability: 7.5
20/20 [==============================] - 0s 1ms/step - loss: 0.0000e+00ING:tensorflow:Can save best model only with val_loss available, skipping.
Saving ...
2022-08-19 12:17:01.354210: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
Loading ...
Traceback (most recent call last):
  File "test_seq_model.py", line 34, in <module>
    loaded_model = tf.keras.models.load_model("test_model")
  File "/xxxxx/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/xxxxx/keras/saving/saved_model/load.py", line 700, in _reconstruct_model
    if config['layers'][0]['class_name'] == 'InputLayer':
IndexError: list index out of range
```
</details>

**Comment by tilakrayal** [comment]
@stridge-cruxml,
Could you please try loading the model with **`tf.saved_model.load("PATH")`**. I tried the alternative approach and was able to load the model without any issue. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/b9a52acf633f62ab782a08536b9c1dea/57222.ipynb). Thank you!

**Comment by stridge-cruxml** [comment]
@tilakrayal thanks for the quick response!

Yes, I found that work around. However this is not ideal as it loads as tensorflow model not keras model.
The other work around (if its just a shortcut layer) is to use `tf.keras.layer.Layer()` instead of Sequential().

But my purpose of reporting this, is this is a case that should work and should be supported but isn't.

**Comment by tilakrayal** [comment]
@stridge-cruxml,
Thanks for opening this issue. Development of keras moved to another [repository](https://github.com/keras-team/keras/issues). 
 
 
Could you please post this issue on keras-team/keras [repo](https://github.com/keras-team/keras/issues).
To know more please refer:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!
