### ISSUE TITLE
Segmentation violation error after call to the go._Cfunc_TF_NewSession

### ISSUE THREAD

**Issue by lukasz-pyrzyk** [tensorflow/tensorflow#5733]
The error repeats locally after manual build of the Tensorflow and in the docker container, based mostly on the [Dockerfile.devel](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/Dockerfile.devel)

### Exception:

```
fatal error: unexpected signal during runtime execution                                
[signal SIGSEGV: segmentation violation code=0x1 addr=0x13 pc=0x7f37136ca51f]          
                                                                                       
runtime stack:                                                                         
runtime.throw(0x770629, 0x2a)                                                          
        /usr/local/go/src/runtime/panic.go:566 +0x95                                   
runtime.sigpanic()                                                                     
        /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x2cc                           
                                                                                       
goroutine 1 [syscall, locked to thread]:                                               
runtime.cgocall(0x6b5900, 0xc420049aa8, 0x7f3700000000)                                
        /usr/local/go/src/runtime/cgocall.go:131 +0x110 fp=0xc420049a78 sp=0xc420049a38
github.com/tensorflow/tensorflow/tensorflow/go._Cfunc_TF_NewSession(0x7f37000008c0, 0x7f3700130a80, 0x7f3700002be0, 0x0)                                                      
        ??:0 +0x4e fp=0xc420049aa8 sp=0xc420049a78                                     
github.com/tensorflow/tensorflow/tensorflow/go.NewSession(0xc4200fa010, 0xc420049c90, 0x1, 0x1, 0xc420494060)
        /go/src/github.com/tensorflow/tensorflow/tensorflow/go/session.go:51 +0x17e fp=0xc420049b30 sp=0xc420049aa8
main.recognize(0xc4200e4570, 0xc420130044, 0x449f, 0x44b7, 0xc4201344fa, 0x0, 0x1, 0x76aa86, 0x1b)
        /go/src/Cerber/tensorflow.go:46 +0x55e fp=0xc420049d48 sp=0xc420049b30
main.HandleSendCommand()
        /go/src/Cerber/sendCommand.go:9 +0x239 fp=0xc420049e48 sp=0xc420049d48
main.mainLoop(0x78f270)
        /go/src/Cerber/main.go:44 +0x2b fp=0xc420049e98 sp=0xc420049e48
main.main()
        /go/src/Cerber/main.go:28 +0x4a2 fp=0xc420049f48 sp=0xc420049e98
runtime.main()
        /usr/local/go/src/runtime/proc.go:183 +0x1f4 fp=0xc420049fa0 sp=0xc420049f48
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420049fa8 sp=0xc420049fa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 25 [IO wait]:
net.runtime_pollWait(0x7f37145e4ff8, 0x72, 0x3)
        /usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc420057100, 0x72, 0xc420505758, 0xc420016160)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc420057100, 0xac3ee0, 0xc420016160)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc4200570a0, 0xc42052a000, 0x8000, 0x8000, 0x0, 0xac3ee0, 0xc420016160)
        /usr/local/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc420028100, 0xc42052a000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:173 +0x70
crypto/tls.(*block).readFromUntil(0xc42023a3f0, 0x7f37145e5218, 0xc420028100, 0x5, 0xc420028100, 0x1)
        /usr/local/go/src/crypto/tls/conn.go:476 +0x91
crypto/tls.(*Conn).readRecord(0xc420073880, 0x78fa17, 0xc420073988, 0xc42002b800)
        /usr/local/go/src/crypto/tls/conn.go:578 +0xc4
crypto/tls.(*Conn).Read(0xc420073880, 0xc4201e1000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1113 +0x116
bufio.(*Reader).fill(0xc4203186c0)
        /usr/local/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Read(0xc4203186c0, 0xc4204fda78, 0x9, 0x9, 0xfef, 0x11, 0x0)
        /usr/local/go/src/bufio/bufio.go:209 +0x1bc
io.ReadAtLeast(0xac1da0, 0xc4203186c0, 0xc4204fda78, 0x9, 0x9, 0x9, 0xc420505c80, 0x50dbce, 0xc420073880)
        /usr/local/go/src/io/io.go:307 +0xa4
io.ReadFull(0xac1da0, 0xc4203186c0, 0xc4204fda78, 0x9, 0x9, 0xc420505c78, 0x457770, 0xc4200001a0)
        /usr/local/go/src/io/io.go:325 +0x58
net/http.http2readFrameHeader(0xc4204fda78, 0x9, 0x9, 0xac1da0, 0xc4203186c0, 0x0, 0x0, 0x1884012202, 0xc4200f2320)
        /usr/local/go/src/net/http/h2_bundle.go:779 +0x7b
net/http.(*http2Framer).ReadFrame(0xc4204fda40, 0xc42048c000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/h2_bundle.go:1001 +0xa4
net/http.(*http2clientConnReadLoop).run(0xc420505f80, 0x78f470, 0xc420020f90)
        /usr/local/go/src/net/http/h2_bundle.go:6004 +0xbb
net/http.(*http2ClientConn).readLoop(0xc420090ea0)
        /usr/local/go/src/net/http/h2_bundle.go:5937 +0xa6
created by net/http.(*http2Transport).newClientConn
        /usr/local/go/src/net/http/h2_bundle.go:5314 +0x709
```

### Container details:
```
$ go env
GOARCH="amd64" GOBIN="" GOEXE="" GOHOSTARCH="amd64" GOHOSTOS="linux" GOOS="linux" GOPATH="/go" GORACE="" GOROOT="/usr/local/go" GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64" CC="gcc" GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build477629842=/tmp/go-build -gno-record-gcc-switches" CXX="g++" CGO_ENABLED="1"
```

```
$ bazel version
Build label: 0.3.2 Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar Build time: Fri Oct 7 17:25:10 2016 (1475861110) Build timestamp: 1475861110 Build timestamp as int: 1475861110
```

```
$ g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609 Copyright (C) 2015 Free Software Foundation, Inc. This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
$ g++ -v
Using built-in specs.

COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper                        
Target: x86_64-linux-gnu                                                               
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.4' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu                 
Thread model: posix                                                                    
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 
```

**Comment by asimshankar** [comment]
@lukasz-pyrzyk : Could you provide some code snippet to reproduce this? 

Looking at the stacktrace, I don't see anything obvious in the C API or the Go code (since the Go code does seem to ensure that `TF_NewSession` gets all valid, non-NULL arguments. If that's the case, then the segfault would appear to trigger inside the C++ runtime due to some peculiarity of the input its currently getting. Any hints on reproducing this, or any more characteristics about the calling code will greatly help. For example, are you setting `SessionOptions.Target` and if so, what to?

**Comment by asimshankar** [comment]
Also, if possible, can you run with `GOTRACEBACK=crash` (see https://golang.org/pkg/runtime/) so the core dump can be inspected in case reproducing it is hard.

**Comment by lukasz-pyrzyk** [comment]
Hi @asimshankar,

I tried to reproduce the issue today without success.. I think we can close the issue

**Comment by asimshankar** [comment]
Thanks for following up.
