### ISSUE TITLE
Computing `jacobian` or `batch_jacobian` with `experimental_pfor=True` errors when loading a `tf.saved_model` that uses an LSTM layer

### ISSUE THREAD

**Issue by cammyoung** [tensorflow/tensorflow#57343]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.8.2

### Custom Code

No

### Python version

3.7.13

### Current Behaviour?

```shell
An error occurs when using `experimental_use_pfor=True` for both `tf.GradientTape.jacobian` and `tf.GradientTape.batch_jacobian` on a `tf.saved_model` that uses an LSTM layer. This error does not occur when `experimental_use_pfor=False` or when the layer is something other than LSTM.

I would expect that this computation could happen with `experimental_use_pfor=True` regardless of the choice of layers in the model or using a saved_model.
```

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/1vIjQ21ixCoJ-MheucKKtog6jcMr-JHwZ?usp=sharing
```

### Relevant log output

```shell
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/backprop.py in jacobian(self, target, sources, unconnected_gradients, parallel_iterations, experimental_use_pfor)
   1182         output = pfor_ops.pfor(loop_fn, target_size,
-> 1183                                parallel_iterations=parallel_iterations)
   1184       except ValueError as err:

9 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/parallel_for/control_flow_ops.py in pfor(loop_fn, iters, fallback_to_while_loop, parallel_iterations)
    201     f = def_function.function(f)
--> 202   outputs = f()
    203   if functions_run_eagerly is not None:

/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/traceback_utils.py in error_handler(*args, **kwargs)
    152       filtered_tb = _process_traceback_frames(e.__traceback__)
--> 153       raise e.with_traceback(filtered_tb) from None
    154     finally:

/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/func_graph.py in autograph_handler(*args, **kwargs)
   1146             if hasattr(e, "ag_error_metadata"):
-> 1147               raise e.ag_error_metadata.to_exception(e)
   1148             else:

ValueError: in user code:

    File "/usr/local/lib/python3.7/dist-packages/six.py", line 703, in reraise
        raise value

    ValueError: Required handle data not set for <tf.Tensor 'gradients/while_grad/gradients/grad_ys_3/pfor/Identity:0' shape=() dtype=variant>


During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-24-f6e4f092a8b4> in <module>
     14     pred = my_model(x)
     15 
---> 16 j = tape.jacobian(pred, x, experimental_use_pfor=True)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/backprop.py in jacobian(self, target, sources, unconnected_gradients, parallel_iterations, experimental_use_pfor)
   1189                 "jacobian computation. Vectorization can be disabled by setting"
   1190                 " experimental_use_pfor to False."),
-> 1191             sys.exc_info()[2])
   1192     else:
   1193       if context.executing_eagerly() and not self._persistent:

/usr/local/lib/python3.7/dist-packages/six.py in reraise(tp, value, tb)
    700                 value = tp()
    701             if value.__traceback__ is not tb:
--> 702                 raise value.with_traceback(tb)
    703             raise value
    704         finally:

/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/backprop.py in jacobian(self, target, sources, unconnected_gradients, parallel_iterations, experimental_use_pfor)
   1181       try:
   1182         output = pfor_ops.pfor(loop_fn, target_size,
-> 1183                                parallel_iterations=parallel_iterations)
   1184       except ValueError as err:
   1185         six.reraise(

/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/parallel_for/control_flow_ops.py in pfor(loop_fn, iters, fallback_to_while_loop, parallel_iterations)
    200       def_function.run_functions_eagerly(False)
    201     f = def_function.function(f)
--> 202   outputs = f()
    203   if functions_run_eagerly is not None:
    204     def_function.run_functions_eagerly(functions_run_eagerly)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/traceback_utils.py in error_handler(*args, **kwargs)
    151     except Exception as e:
    152       filtered_tb = _process_traceback_frames(e.__traceback__)
--> 153       raise e.with_traceback(filtered_tb) from None
    154     finally:
    155       del filtered_tb

/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/func_graph.py in autograph_handler(*args, **kwargs)
   1145           except Exception as e:  # pylint:disable=broad-except
   1146             if hasattr(e, "ag_error_metadata"):
-> 1147               raise e.ag_error_metadata.to_exception(e)
   1148             else:
   1149               raise

ValueError: in user code:

    File "/usr/local/lib/python3.7/dist-packages/six.py", line 703, in reraise
        raise value

    ValueError: Required handle data not set for <tf.Tensor 'gradients/while_grad/gradients/grad_ys_3/pfor/Identity:0' shape=() dtype=variant>

Encountered an exception while vectorizing the jacobian computation. Vectorization can be disabled by setting experimental_use_pfor to False.
```
</details>

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue on tensorflow [v2.8](https://colab.research.google.com/gist/tilakrayal/a77fe2c6c4d10e7df9dcd8f621f3ea48/tensorflow_pfor_savedmodel_bug.ipynb), [v2.9](https://colab.research.google.com/gist/tilakrayal/701e2c0a4dfea601f3887148346977f5/2-9tensorflow_pfor_savedmodel_bug.ipynb) and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/ece69dd25605aac97ef01d96be73c6e5/2-11tensorflow_pfor_savedmodel_bug.ipynb).

**Comment by aniruthraj** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
