### ISSUE TITLE
model.save: Tried to export a function which references 'untracked' resource even though the tensor should be tracked

### ISSUE THREAD

**Issue by singinwhale** [tensorflow/tensorflow#57363]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9.1

### Custom Code

No

### OS Platform and Distribution

Windows 10

### Python version

3.7.13

### CUDA/cuDNN version

11.7.0_516.01/8100

### Current Behaviour?

```shell
I do not understand why this particular tensor (StylePredictionModelDummy/dummy_conv/kernel:0) is not tracked. As you can see my model (style_transfer_model) is created with the Tensorflow functional API and the untracked tensor in question is instantiated as part of StylePredictionModelDummy.__init__() in line 92 and assigned as a class property to self.feature_extractor which is what the error recommends to do to track the value.

The outputs of StylePredictionModelDummy(line 93) are split up(lines 100-105) and routed to the ConditionalInstanceNormalization(line 71) layers as scale and bias inside of the expand layers (line 109). So it also can't be that the tensor is just not used because it is used.

I expect the tensor to be tracked and that the model can be saved.
```

### Standalone code to reproduce the issue

https://colab.research.google.com/drive/1HFq2k12IGO6bsnbd8WWvg3yci6g12BD0?usp=sharing
```python
import numpy as np
import tensorflow as tf

class DummyModel(tf.keras.Model):
    feature_extractor = None

    def __init__(self, name="StylePredictionModelDummy"):
        super().__init__(name=name)

        self.feature_extractor = tf.keras.layers.Conv2D(1, 9, 5, padding='same', name="dummy_conv")

    def call(self, inputs, training=None, mask=None):
        x = self.feature_extractor(inputs)
        return x

image_shape = (None, 960//4, 1920//4, 3)

model = DummyModel()
element = tf.convert_to_tensor(np.zeros((1, image_shape[1], image_shape[2], 3)))

# call once to build model
result = model(element)

model.save(filepath="%TEMP%/model", include_optimizer=False, save_format='tf')
```

### Relevant log output

```shell
C:\condaEnvs\realtime-style-transfer\python.exe C:/projects/realtime-style-transfer/save_using_checkpoint.py -C C:\projects\realtime-style-transfer\logs\2022-08-22-10-47-13.310922\last_training_checkpoint -o C:\projects\realtime-style-transfer\temp\saved.tf 
tensorflow - DEBUG - Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client. (tpu_cluster_resolver.py:32 @ 2022-08-22 10:55:32,983)
2022-08-22 10:55:35.933767: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
tensorflow - WARNING - `input_shape` is undefined or non-square, or `rows` is not 224. Weights for input shape (224, 224) will be loaded as the default. (mobilenet_v3.py:256 @ 2022-08-22 10:55:35,939)
models.stylePrediction - INFO - Using 100 style parameters (stylePrediction.py:24 @ 2022-08-22 10:55:37,877)
models.stylePrediction - DEBUG - Using 192 norm parameters (stylePrediction.py:33 @ 2022-08-22 10:55:37,882)
tensorflow - WARNING - `input_shape` is undefined or non-square, or `rows` is not 224. Weights for input shape (224, 224) will be loaded as the default. (mobilenet_v3.py:256 @ 2022-08-22 10:55:37,883)
root - INFO - Running inference to build model... (save_using_checkpoint.py:49 @ 2022-08-22 10:55:44,154)
root - INFO - Saving model... (save_using_checkpoint.py:55 @ 2022-08-22 10:55:47,613)
tensorflow - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model. (saving_utils.py:328 @ 2022-08-22 10:55:47,613)
absl - WARNING - Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 67). These functions will not be directly callable after loading. (save.py:233 @ 2022-08-22 10:56:36,316)
Traceback (most recent call last):
  File "C:\projects\realtime-style-transfer\save_using_checkpoint.py", line 56, in <module>
    style_transfer_model.save(filepath=str(outpath), include_optimizer=False, save_format='tf')
  File "C:\condaEnvs\realtime-style-transfer\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\condaEnvs\realtime-style-transfer\lib\site-packages\tensorflow\python\saved_model\save.py", line 473, in _map_captures_to_created_tensors
    raise AssertionError(
AssertionError: Tried to export a function which references 'untracked' resource Tensor("52018:0", shape=(), dtype=resource). TensorFlow objects (e.g. tf.Variable) captured by functions must be 'tracked' by assigning them to an attribute of a tracked object or assigned to an attribute of the main object directly. See the information below:
	Function name = b'__inference_signature_wrapper_53008'
	Captured Tensor = <ResourceHandle(name="Resource-218-at-0x231ff25da30", device="/job:localhost/replica:0/task:0/device:CPU:0", container="Anonymous", type="class tensorflow::Var", dtype and shapes : "[ DType enum: 1, Shape: [3,3,3,16] ]")>
	Trackable referencing this tensor = <tf.Variable 'Conv/kernel:0' shape=(3, 3, 3, 16) dtype=float32>

Process finished with exit code 1
```
</details>

**Comment by singinwhale** [comment]
https://stackoverflow.com/questions/73416907/model-save-tried-to-export-a-function-which-references-untracked-resource-eve/73459151#73459151

The error is due to using a static class member instead of a normal attribute:
```python3

class DummyModel(tf.keras.Model):
    feature_extractor = None # <- this is the problem
    def __init__(self):
```

**Comment by sushreebarsa** [comment]
@singinwhale I tried to replicate the issue on colab, please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/23a67337dc53404d88848614b87e50e0/57363.ipynb) and confirm the same. 
Thank you!
