### ISSUE TITLE
Unable to crosscompile TFLite kernel tests with CMake

### ISSUE THREAD

**Issue by robert-kalmar** [tensorflow/tensorflow#57391]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

tf 2.10.0 RC1

### Custom Code

No

### OS Platform and Distribution

Linux

### Python version

N/A

### Bazel version

N/A

### CUDA/cuDNN version

N/A

### GPU model and memory

N/A

### Current Behaviour?

```shell
Unable to cross-build TensorFlow Lite Kernel tests with CMake. Issue identified on r2.10 release branch. 
The problem is tracked down to flatbuffers library update. Flatbuffers 2.0.6 attempts to generate files with built flatc compiler, if Python3 interpretter is available. At crosscompilation, this compiler is build for target archtitecture hence not working on host.

Solution is to disable the Python lookup for flatbuffers in flatbuffers.cmake file:

-DCMAKE_DISABLE_FIND_PACKAGE_Python3=TRUE
```
```


### Standalone code to reproduce the issue

```shell
$ mkdir build-native-tools && cd build-native-tools
$ cmake ../tensorflow/lite/tools/cmake/native_tools/flatbuffers/  -DCMAKE_INSTALL_PREFIX=./
$ make -j8 install
$ cd ..
$ mkdir build && cd build
$ # activate cross SDK
$ cmake -DCMAKE_TOOLCHAIN_FILE=${OE_CMAKE_TOOLCHAIN_FILE}  \
        -DTFLITE_ENABLE_XNNPACK=on -DTFLITE_ENABLE_RUY=on \
        -DTFLITE_HOST_TOOLS_DIR=../build-native-tools/ \
        -DTFLITE_KERNEL_TEST=On \
        ../tensorflow/lite/
$ make -j8 add_test
```

### Relevant log output

```shell
Running scripts/generate_code.py...
[ 37%] Building C object _deps/xnnpack-build/CMakeFiles/XNNPACK.dir/src/f32-vbinary/gen/vmulc-minmax-neon-x8.c.o
Traceback (most recent call last):
  File "/home/nxf39574/REPOS/tensorflow-imx/build/flatbuffers/scripts/generate_code.py", line 148, in <module>
    flatc(
  File "/home/nxf39574/REPOS/tensorflow-imx/build/flatbuffers/scripts/generate_code.py", line 82, in flatc
    result = subprocess.run(cmd, cwd=str(cwd), check=True)
  File "/opt/sdk-5.15.32_2.0.0-RC1/sysroots/x86_64-pokysdk-linux/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/sdk-5.15.32_2.0.0-RC1/sysroots/x86_64-pokysdk-linux/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/sdk-5.15.32_2.0.0-RC1/sysroots/x86_64-pokysdk-linux/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/nxf39574/REPOS/tensorflow/build/flatbuffers-flatc/src/flatbuffers-flatc-build/flatc'
make[6]: *** [CMakeFiles/flatc.dir/build.make:563: flatc] Error 1
make[6]: *** Deleting file 'flatc'
make[5]: *** [CMakeFiles/Makefile2:83: CMakeFiles/flatc.dir/all] Error 2
make[4]: *** [Makefile:136: all] Error 2
make[3]: *** [CMakeFiles/flatbuffers-flatc.dir/build.make:86: flatbuffers-flatc/src/flatbuffers-flatc-stamp/flatbuffers-flatc-build] Error 2
make[2]: *** [CMakeFiles/Makefile2:1516: CMakeFiles/flatbuffers-flatc.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
```
</details>

**Comment by mohantym** [comment]
Thanks @robert-kalmar for the PR #57393 . This issue will be closed once PR is merged.

**Comment by sachinprasadhs** [comment]
@robert-kalmar , I see that your linked PR is merged, if your issue is resolved, could you please close the issue. Thanks!

**Comment by robert-kalmar** [comment]
@sachinprasadhs , the PR containing the fix is merged in 2.10.0, the PR was sent to release branch. The same error is on master branch, here the PR is still under review - https://github.com/tensorflow/tensorflow/pull/56602. Can you please help to push the review forward? 

Thanks

**Comment by madaosik** [comment]
@sachinprasadhs, I just came across this issue in both the v2.11.0 tag and the current master branch.

The [PR](https://github.com/tensorflow/tensorflow/pull/56602) linked to this issue by @robert-kalmar contains all the necessary fixes to make the TF Lite with unit tests once again cross-compilable using CMake.

@sachinprasadhs, @terryheo, can you please help by pushing the review of the referred PR so that this issue is resolved?

**Comment by pkgoogle** [comment]
Hi @robert-kalmar, are you still looking to integrate your PR here? Thanks for your help.
