### ISSUE TITLE
LSTM layer not support bf16 

### ISSUE THREAD

**Issue by ZhaoqiongZ** [tensorflow/tensorflow#57411]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9.1

### Custom Code

Yes

### OS Platform and Distribution

 Ubuntu 22.04.1 LTS

### Python version

3.7

### Current Behaviour?

```shell
I trid do mix_precision with keras policy, get the error "Value passed to parameter 'input' has DataType bfloat16 not in list of allowed values: float16, float32, float64"

Why not support LSTM layer BF16 ? Is it a accuracy loss concern or something else?
Will it be possible to support LSTM with BF16?
If not, can we add it to something like DenyList to run LSTM with FP32 automatically rather than throw this error?
```

### Standalone code to reproduce the issue

```shell
from tensorflow.keras.models import Sequential
from tensorflow.keras import mixed_precision
from tensorflow.keras.layers import LSTM, Embedding

policy = mixed_precision.Policy('mixed_bfloat16')
mixed_precision.set_global_policy(policy)
vocab_size = 1000

# define model
def customer_model():
    model = Sequential()
    model.add(Embedding(vocab_size, 512, input_length=50))
    model.add(LSTM(128, return_sequences=True))
    return model
def test_model():
    model = Sequential()
    model.add(Embedding(vocab_size, 128, input_length=50))
    model.add(LSTM(4, dtype='float32',  return_sequences=True))    
    return model

model = customer_model()
model.summary()
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "reproduce_error.py", line 23, in <module>
    model = customer_model()
  File "reproduce_error.py", line 13, in customer_model
    model.add(LSTM(128, return_sequences=True))
  File "/home/sdp/miniconda3/envs/tensorflow_2.9.1/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py", line 587, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/sdp/miniconda3/envs/tensorflow_2.9.1/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/sdp/miniconda3/envs/tensorflow_2.9.1/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py", line 58, in _SatisfiesTypeConstraint
    raise TypeError(
TypeError: Exception encountered when calling layer "lstm" (type LSTM).Value passed to parameter 'input' has DataType bfloat16 not in list of allowed values: float16, float32, float64Call arguments received by layer "lstm" (type LSTM):
  • inputs=tf.Tensor(shape=(None, 50, 512), dtype=bfloat16)
  • mask=None
  • training=None
  • initial_state=None
```
</details>

**Comment by tilakrayal** [comment]
@ZhaoqiongZ,
I tried to execute the below code at the head of the file and was able to execute without any issue. Kindly find the alternative approach and let us know if it is working in this case. Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/da9e9e67f17373ffa834077136580955/57411.ipynb). 

**from tensorflow.python.framework.ops import disable_eager_execution
disable_eager_execution()**

Thank you!

**Comment by ZhaoqiongZ** [comment]
@tilakrayal  
Thanks very much for the quick response, it worked!
Could you please give me a quick explain about why it work and what is the root cause for the first error?

**Comment by tilakrayal** [comment]
@ZhaoqiongZ,
Here we are trying to execute the code after disabling eager execution as mentioned below. There was no issue with the code.

**disable_eager_execution()**.  Thank you!

**Comment by ZhaoqiongZ** [comment]
Thanks

**Comment by yufang67** [comment]
Is there a way to LSTM with bfloat16 on eager mode (without disable_eager_execution()) ?

thanks,
