### ISSUE TITLE
error in `tf.train.import_meta_graph()`

### ISSUE THREAD

**Issue by wwdok** [tensorflow/tensorflow#57454]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

binary

### Tensorflow Version

tf 2.3.0

### Custom Code

No

### OS Platform and Distribution

Windows 10

### Python version

3.8.10

### Current Behaviour?

```shell
I am trying to convert ckpt to pb format of this model : https://github.com/isohrab/Pupil-locator/tree/master/models/3A4Bh-Ref25/best_loss with below code, but it reports error : 

Traceback (most recent call last):
  File "d:/AI/PythonScripts/TF_ckpt_to_pb.py", line 21, in <module>
    saver = tf.train.import_meta_graph(input_checkpoint + '.meta')
  File "C:\Users\weida\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\training\saver.py", line 1460, in import_meta_graph
    return _import_meta_graph_with_return_elements(meta_graph_or_file,
  File "C:\Users\weida\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\training\saver.py", line 1481, in _import_meta_graph_with_return_elements   
    meta_graph.import_scoped_meta_graph_with_return_elements(
  File "C:\Users\weida\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\framework\meta_graph.py", line 794, in import_scoped_meta_graph_with_return_elements
    imported_return_elements = importer.import_graph_def(
  File "C:\Users\weida\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\weida\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\framework\importer.py", line 400, in import_graph_def
    return _import_graph_def_internal(
  File "C:\Users\weida\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\framework\importer.py", line 501, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: Node 'gradients/InceptionV4/Block_B3/branch_0/batch_normalization/cond/FusedBatchNorm_1_grad/FusedBatchNormGrad' has an _output_shapes attribute inconsistent with the GraphDef for output #3: Dimension 0 in both shapes must be equal, but are 0 and 192. Shapes are [0] and [192].
```

this error occurs at step of `tf.train.import_meta_graph()`.
```


### Standalone code to reproduce the issue

```shell
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import os.path

MODEL_DIR = r"D:\AI\repos\Pupil-locator\models\3A4Bh-Ref25\best_loss"
MODEL_NAME = "Pupil-locator.pb"
output_node_names = ['InceptionV4/y']

checkpoint = tf.train.get_checkpoint_state(MODEL_DIR) 
input_checkpoint = checkpoint.model_checkpoint_path
print("==>> input_checkpoint: ", input_checkpoint)
output_graph = os.path.join(MODEL_DIR, MODEL_NAME)

with tf.Session() as sess:
    # Restore the graph
    saver = tf.train.import_meta_graph(input_checkpoint + '.meta')

    # Load weights
    # ckpt = tf.train.get_checkpoint_state(MODEL_DIR)
    # if ckpt:
    #     saver.restore(sess, ckpt.model_checkpoint_path)
        # saver.restore(sess, tf.train.latest_checkpoint('.'))
    # var_SRGAN_g = tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES)

    # # Freeze the graph
    # frozen_graph_def = tf.graph_util.convert_variables_to_constants(sess, sess.graph_def, output_node_names)

    # # tf.train.write_graph(frozen_graph_def,MODEL_DIR,MODEL_NAME,as_text=False)

    # # Save the frozen graph
    # with open(output_graph, 'wb') as f:
    #     f.write(frozen_graph_def.SerializeToString())
    #     print("%d ops in the final graph." % len(frozen_graph_def.node))
```
```


### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@wwdok Could you please upgrade to latest TF version as older versions are not actively supported and let us know the outcome. I tried to replicate the issue and faced different outcome. Please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/b194bdefca61d79ae53357049fe8365a/57454.ipynb) and confirm the same. Thank you!

**Comment by AndreyOrb** [comment]
I had the same exception with TF 2.8

ValueError: Node '/BatchNorm/cond/FusedBatchNorm_1_grad/FusedBatchNormGrad' has an _output_shapes attribute inconsistent with the GraphDef for output #3: Dimension 0 in both shapes must be equal, but are 0 and 512. Shapes are [0] and [512].

Changing to the latest TF 2.10 didn't help to resolve the problem.

**Comment by gadagashwini** [comment]
Hi @wwdok, Issue with input data shape.
in your case, x/y has shape [512, 0] while x/y has shape [512]. they are not compatible. Please try to reshape input data using tf.reshape(y, [-1, 1]). Thank you!

**Comment by Rupesh4604** [comment]
Could you pls check this error: 

tensorflow.python.framework.errors_impl.InvalidArgumentError: Node 'gradients/refinement1/bn2/cond/FusedBatchNorm_1_grad/FusedBatchNormGrad' has an _output_shapes attribute inconsistent with the GraphDef for output #3: Dimension 0 in both shapes must be equal, but are 0 and 256. Shapes are [0] and [256].

**Comment by Rupesh4604** [comment]
I have cloned the following repo "https://github.com/rmkemker/EarthMapper/tree/master"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\examples\example_pipeline.py", line 111, in <module>
    pipe.fit(X , y_train, X, y_val)
  File "C:\rupesh\4th_year\Final_project\EarthMapper-master\EarthMapper\pipeline.py", line 194, in fit
    X_train = fe.transform(X_train)
  File "C:\rupesh\4th_year\Final_project\EarthMapper-master\EarthMapper\feature_extraction\scae.py", line 106, in transform
    clear_devices=True)
  File "C:\Users\rupes\anaconda3\envs\Env2\lib\site-packages\tensorflow\python\training\saver.py", line 1467, in import_meta_graph
    **kwargs)[0]
  File "C:\Users\rupes\anaconda3\envs\Env2\lib\site-packages\tensorflow\python\training\saver.py", line 1491, in _import_meta_graph_with_return_elements
    **kwargs))
  File "C:\Users\rupes\anaconda3\envs\Env2\lib\site-packages\tensorflow\python\framework\meta_graph.py", line 806, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "C:\Users\rupes\anaconda3\envs\Env2\lib\site-packages\tensorflow\python\util\deprecation.py", line 549, in new_func
    return func(*args, **kwargs)
  File "C:\Users\rupes\anaconda3\envs\Env2\lib\site-packages\tensorflow\python\framework\importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "C:\Users\rupes\anaconda3\envs\Env2\lib\site-packages\tensorflow\python\framework\importer.py", line 501, in _import_graph_def_internal    
    raise ValueError(str(e))
ValueError: Node 'gradients/refinement1/bn2/cond/FusedBatchNorm_1_grad/FusedBatchNormGrad' has an _output_shapes attribute inconsistent with the GraphDef for output #3: Dimension 0 in both shapes must be equal, but are 0 and 256. Shapes are [0] and [256].
