### ISSUE TITLE
Tensorflow loading RGB image from directory as 5-D tensor

### ISSUE THREAD

**Issue by jaybhanushali99** [tensorflow/tensorflow#57476]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9.1

### Custom Code

No

### OS Platform and Distribution

Windows 10

### Python version

3.9

### Current Behaviour?

```shell
Using the function 

train_ds = image_dataset_from_directory(
  data_dir,
  validation_split=0.2,
  subset="training",
  seed=42,
  image_size=(224, 224),
  crop_to_aspect_ratio=True,
  shuffle=True,
  batch_size=BATCH_SIZE)

Generates both the images and labels correctly.
However on performing any data augmentation:

rescale = tf.keras.Sequential([
  layers.Rescaling(1./255)
])
data_augmentation = tf.keras.Sequential([
  layers.RandomFlip("horizontal_and_vertical"),
  layers.RandomRotation(0.2),
])

def prepare(ds, shuffle=False, augment=False,batch_size=18):
  # Resize and rescale all datasets.
  ds = ds.map(lambda x, y: (rescale(x), y), 
              num_parallel_calls=AUTOTUNE)

  if shuffle:
    ds = ds.shuffle(1000)

  # Batch all datasets.
  ds = ds.batch(batch_size)

  # Use data augmentation only on the training set.
  if augment:
    ds = ds.map(lambda x, y: (data_augmentation(x, training=True), y), 
                num_parallel_calls=AUTOTUNE)

  # Use buffered prefetching on all datasets.
  return ds.prefetch(buffer_size=AUTOTUNE)

The error shows that image is being passed as 5-D tensor. I believe it is also passing labels with the image data during augmentation (in x instead of y) even though it is defined explicitly in the lambda function.
```

### Standalone code to reproduce the issue

```shell
#Load dataset
train_ds = image_dataset_from_directory(
  data_dir,
  validation_split=0.2,
  subset="training",
  seed=42,
  image_size=(224, 224),
  crop_to_aspect_ratio=True,
  shuffle=True,
  batch_size=BATCH_SIZE)

#Data augmentation
rescale = tf.keras.Sequential([
  layers.Rescaling(1./255)
])
data_augmentation = tf.keras.Sequential([
  layers.RandomFlip("horizontal_and_vertical"),
  layers.RandomRotation(0.2),
])

def prepare(ds, shuffle=False, augment=False,batch_size=18):
  # Resize and rescale all datasets.
  ds = ds.map(lambda x, y: (rescale(x), y), 
              num_parallel_calls=AUTOTUNE)

  if shuffle:
    ds = ds.shuffle(1000)

  # Batch all datasets.
  ds = ds.batch(batch_size)

  # Use data augmentation only on the training set.
  if augment:
    ds = ds.map(lambda x, y: (data_augmentation(x, training=True), y), 
                num_parallel_calls=AUTOTUNE)

  # Use buffered prefetching on all datasets.
  return ds.prefetch(buffer_size=AUTOTUNE)

# Augment the data
train_ds = prepare(train_ds,shuffle=True,augment=True,batch_size=BATCH_SIZE)
```

### Relevant log output

```shell
2022-08-27 12:52:41.780851: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-08-27 12:52:42.109996: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 21676 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:09:00.0, compute capability: 8.6
Found 540 files belonging to 18 classes.
Using 432 files for training.
Traceback (most recent call last):
  File "c:\Users\Admin\Documents\GitHub\RoughSpecimenClassification\main.py", line 34, in <module>
    train_ds = prepare(train_ds,shuffle=True,augment=True,batch_size=BATCH_SIZE)
  File "c:\Users\Admin\Documents\GitHub\RoughSpecimenClassification\augmentation.py", line 26, in prepare
    ds = ds.map(lambda x, y: (data_augmentation(x, training=True), y),
  File "C:\ProgramData\Anaconda3\envs\tfenv\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 2050, in map
    return ParallelMapDataset(
  File "C:\ProgramData\Anaconda3\envs\tfenv\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 5284, in __init__
    self._map_func = structured_function.StructuredFunctionWrapper(
  File "C:\ProgramData\Anaconda3\envs\tfenv\lib\site-packages\tensorflow\python\data\ops\structured_function.py", line 271, in __init__
    self._function = fn_factory()
  File "C:\ProgramData\Anaconda3\envs\tfenv\lib\site-packages\tensorflow\python\eager\function.py", line 2567, in get_concrete_function
    graph_function = self._get_concrete_function_garbage_collected(
  File "C:\ProgramData\Anaconda3\envs\tfenv\lib\site-packages\tensorflow\python\eager\function.py", line 2533, in _get_concrete_function_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "C:\ProgramData\Anaconda3\envs\tfenv\lib\site-packages\tensorflow\python\eager\function.py", line 2711, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\ProgramData\Anaconda3\envs\tfenv\lib\site-packages\tensorflow\python\eager\function.py", line 2627, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "C:\ProgramData\Anaconda3\envs\tfenv\lib\site-packages\tensorflow\python\framework\func_graph.py", line 1141, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\ProgramData\Anaconda3\envs\tfenv\lib\site-packages\tensorflow\python\data\ops\structured_function.py", line 248, in wrapped_fn
    ret = wrapper_helper(*args)
  File "C:\ProgramData\Anaconda3\envs\tfenv\lib\site-packages\tensorflow\python\data\ops\structured_function.py", line 177, in wrapper_helper
    ret = autograph.tf_convert(self._func, ag_ctx)(*nested_args)
  File "C:\ProgramData\Anaconda3\envs\tfenv\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 692, in wrapper
    raise e.ag_error_metadata.to_exception(e)
  File "C:\ProgramData\Anaconda3\envs\tfenv\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 689, in wrapper
    return converted_call(f, args, kwargs, options=options)
  File "C:\ProgramData\Anaconda3\envs\tfenv\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 439, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Temp\__autograph_generated_file9cp3lsbh.py", line 5, in <lambda>
    tf__lam = lambda x, y: ag__.with_function_scope(lambda lscope: (ag__.converted_call(data_augmentation, (x,), dict(training=True), lscope), y), 'lscope', ag__.STD)
  File "C:\ProgramData\Anaconda3\envs\tfenv\lib\site-packages\tensorflow\python\autograph\core\function_wrappers.py", line 113, in with_function_scope
    return thunk(scope)
  File "C:\Users\Admin\AppData\Local\Temp\__autograph_generated_file9cp3lsbh.py", line 5, in <lambda>
    tf__lam = lambda x, y: ag__.with_function_scope(lambda lscope: (ag__.converted_call(data_augmentation, (x,), dict(training=True), lscope), y), 'lscope', ag__.STD)
  File "C:\ProgramData\Anaconda3\envs\tfenv\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 377, in converted_call
    return _call_unconverted(f, args, kwargs, options)
  File "C:\ProgramData\Anaconda3\envs\tfenv\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 458, in _call_unconverted
    return f(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\tfenv\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\ProgramData\Anaconda3\envs\tfenv\lib\site-packages\keras\layers\preprocessing\image_preprocessing.py", line 392, in call
    raise ValueError('Image augmentation layers are expecting inputs to be '
ValueError: in user code:

    File "c:\Users\Admin\Documents\GitHub\RoughSpecimenClassification\augmentation.py", line 26, in None  *
        lambda x, y: (data_augmentation(x, training=True), y)
    File "C:\ProgramData\Anaconda3\envs\tfenv\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler  **
        raise e.with_traceback(filtered_tb) from None
    File "C:\ProgramData\Anaconda3\envs\tfenv\lib\site-packages\keras\layers\preprocessing\image_preprocessing.py", line 392, in call
        raise ValueError('Image augmentation layers are expecting inputs to be '

    ValueError: Exception encountered when calling layer "random_flip" (type RandomFlip).

    Image augmentation layers are expecting inputs to be rank 3 (HWC) or 4D (NHWC) tensors. Got shape: (None, None, 224, 224, 3)

    Call arguments received by layer "random_flip" (type RandomFlip):
      • inputs=tf.Tensor(shape=(None, None, 224, 224, 3), dtype=float32)
      • training=True
```
</details>

**Comment by sushreebarsa** [comment]
@jaybhanushali99 I tried to replicate the issue, could you find the gist [here](https://colab.research.google.com/gist/sushreebarsa/f5ca750d8ab2548c6570283143fb13d0/untitled104.ipynb) and confirm the same? Thank you!

**Comment by jaybhanushali99** [comment]
> @jaybhanushali99 I tried to replicate the issue, could you find the gist [here](https://colab.research.google.com/gist/sushreebarsa/f5ca750d8ab2548c6570283143fb13d0/untitled104.ipynb) and confirm the same? Thank you!

Yes can confirm that  I am facing this issue.

**Comment by sachinprasadhs** [comment]
This seems like an issue with the Keras API.
Development of keras moved to separate repository https://github.com/keras-team/keras/issues

Please post this issue on keras-team/keras repo.
To know more see;
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!
