### ISSUE TITLE
Tensorflow macOS 12.5.1 

### ISSUE THREAD

**Issue by arinconh** [tensorflow/tensorflow#57483]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

2.9.1

### Custom Code

Yes

### OS Platform and Distribution

MacOS 12.5

### Python version

3.10.6

### Current Behaviour?

```shell
I followed this tutorial: https://www.youtube.com/watch?v=4nY5lDBXdOg to install tensorflow in my Mac. But I still do not manage to run tensorflow in my jupyter lab
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
```

### Relevant log output

```shell
--------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/__init__.py:61, in <module>
     60 sys.setdlopenflags(_default_dlopen_flags | ctypes.RTLD_GLOBAL)
---> 61 from tensorflow.python import pywrap_tensorflow
     62 sys.setdlopenflags(_default_dlopen_flags)

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py:28, in <module>
     27         return _mod
---> 28 _pywrap_tensorflow = swig_import_helper()
     29 del swig_import_helper

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py:24, in swig_import_helper()
     23 try:
---> 24     _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
     25 finally:

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/imp.py:243, in load_module(name, file, filename, details)
    242     else:
--> 243         return load_dynamic(name, filename, file)
    244 elif type_ == PKG_DIRECTORY:

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/imp.py:343, in load_dynamic(name, path, file)
    341 spec = importlib.machinery.ModuleSpec(
    342     name=name, loader=loader, origin=path)
--> 343 return _load(spec)

ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/_pywrap_tensorflow.so, 0x000A): tried: '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/_pywrap_tensorflow.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
Input In [1], in <cell line: 1>()
----> 1 import tensorflow as tf

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/__init__.py:24, in <module>
     21 from __future__ import print_function
     23 # pylint: disable=wildcard-import
---> 24 from tensorflow.python import *
     25 # pylint: enable=wildcard-import
     26 
     27 # Lazily import the `tf.contrib` module. This avoids loading all of the
     28 # dependencies of `tf.contrib` at `import tensorflow` time.
     29 class _LazyContribLoader(object):

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/__init__.py:72, in <module>
     67 except ImportError:
     68   msg = """%s\n\nFailed to load the native TensorFlow runtime.\n
     69 See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error\n
     70 for some common reasons and solutions.  Include the entire stack trace
     71 above this error message when asking for help.""" % traceback.format_exc()
---> 72   raise ImportError(msg)
     74 # Protocol buffers
     75 from tensorflow.core.framework.graph_pb2 import *

ImportError: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/_pywrap_tensorflow.so, 0x000A): tried: '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/_pywrap_tensorflow.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))


Failed to load the native TensorFlow runtime.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
​
```
</details>

**Comment by phoomp** [comment]
Hi, @arinconh, it seems like your version of TensorFlow was compiled for ```x86_64```, but you are trying to install it on  Apple Silicon (```arm64```). 

Hence, this error: 
```
tried: '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/_pywrap_tensorflow.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
```

Can you try the following? (It's slightly different from the video.)

```
conda create --name {a new env}
conda activate {new env}
conda install -c apple tensorflow-deps
python -m pip install tensorflow-macos
python -m pip install tensorflow-metal
```

If that still fails, can you provide the terminal output for this command? `file $(which python)`

**Comment by sushreebarsa** [comment]
@arinconh Could you please refer to the [comment](https://github.com/tensorflow/tensorflow/issues/57483#issuecomment-1229440132) above and let us know if it helps?
Thank you!
