### ISSUE TITLE
Converting a TF model to TFLite and then to EdgeTPU

### ISSUE THREAD

**Issue by gsirocco** [tensorflow/tensorflow#57490]
I'm trying to convert a simple add model from TF to TFLite to EdgeTPU
However, it seems this conversion is caught in a catch 22 scenario.
If I specify int8 data type as below, it ends up wanting to use the FlexAddV2 TF op, which fails to convert to EdgeTPU.
If I specify as int32 data type instead, it is able to use regular ADD op, but the data type is incompatible with EdgeTPU and says the data type is supported so it only runs on CPU. Is there any way to get this to convert for EdgeTPU as INT8 so it can run on TPU?

### 1. System information

- OS Platform and Distribution: Linux Ubuntu 20.04.4 LTS (Focal Fossa)
- TensorFlow installation (pip package or built from source): pip package
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.9.1

### 2. Code

Provide code to help us reproduce your issues using one of the following options:
input = keras.Input(shape=(32,), name="dummy_input", dtype=tf.int8)
output = tf.add(input, 1)
model = keras.Model(inputs=input, outputs=output)
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
tflite_quant_model = converter.convert()

$ edgetpu_compiler -s testmodel.tflite
Edge TPU Compiler version 16.0.384591198
Started a compilation timeout timer of 180 seconds.
ERROR: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.
ERROR: Node number 0 (FlexAddV2) failed to prepare.

Compilation failed: Model failed in Tflite interpreter. Please ensure model can be loaded/run in Tflite interpreter.
Compilation child process completed within timeout period.
Compilation failed!

### 3. Failure after conversion
If the conversion is successful, but the generated model is wrong, then state what is wrong:

- Model produces wrong results and/or has lesser accuracy.
- Model produces correct results, but it is slower than expected.

INT8 conversion, resulting in unsupported op:

edgetpu_compiler -s testmodel.tflite
Edge TPU Compiler version 16.0.384591198
Started a compilation timeout timer of 180 seconds.
ERROR: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.
ERROR: Node number 0 (FlexAddV2) failed to prepare.

Compilation failed: Model failed in Tflite interpreter. Please ensure model can be loaded/run in Tflite interpreter.
Compilation child process completed within timeout period.
Compilation failed!

INT32 conversion, resulting in invalid data type for TPU:

$ edgetpu_compiler -s testmodel.tflite
Edge TPU Compiler version 16.0.384591198
Started a compilation timeout timer of 180 seconds.

Model compiled successfully in 0 ms.

Input model: testmodel.tflite
Input size: 936.00B
Output model: testmodel_edgetpu.tflite
Output size: 476.00B
On-chip memory used for caching model parameters: 0.00B
On-chip memory remaining for caching model parameters: 0.00B
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 0
Total number of operations: 1
Operation log: testmodel_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 0
Number of operations that will run on CPU: 1

Operator                       Count      Status

ADD                            1          Operation is working on an unsupported data type
Compilation child process completed within timeout period.
Compilation succeeded!

**Comment by mohantym** [comment]
Hi @gsirocco !
Could you use a representative dataset (yield tf.int8/np.int8 data type ) and use supported ops syntax like below and let us know.
```

converter.target_spec.supported_ops = [
tf.lite.OpsSet.TFLITE_BUILTINS_INT8, # enable TensorFlow Lite ops.
tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
```

Attached relevant  threads [1](https://www.tensorflow.org/lite/performance/post_training_integer_quant#convert_using_integer-only_quantization) and [2](https://coral.ai/docs/edgetpu/tflite-python/#update-existing-tf-lite-code-for-the-edge-tpu)  for reference.

Thank you!

**Comment by gsirocco** [comment]
I have run the following, but it is still complaining that it needs FlexAddV2:

import tensorflow as tf
from tensorflow import keras
import numpy as np

def representative_dataset():
    for _ in range(100):
      data = np.random.rand(1, 32)
      yield [data.astype(np.int8)]

input = keras.Input(shape=(32,), name="dummy_input", dtype=tf.int8)
output = tf.add(input, 1)
model = keras.Model(inputs=input, outputs=output)
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS_INT8, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
converter.inference_input_type = tf.int8  # or tf.uint8
converter.inference_output_type = tf.int8  # or tf.uint8
tflite_quant_model = converter.convert()


Output:

2022-08-29 14:58:18.241402: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-08-29 14:58:18.241515: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-08-29 14:58:19.273233: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-08-29 14:58:19.273261: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-08-29 14:58:19.273275: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ubuntugsosnow): /proc/driver/nvidia/version does not exist
2022-08-29 14:58:19.273585: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
/home/gsosnow/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/convert.py:766: UserWarning: Statistics for quantized inputs were expected, but not specified; continuing anyway.
  warnings.warn("Statistics for quantized inputs were expected, but not "
2022-08-29 14:58:19.513212: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:362] Ignored output_format.
2022-08-29 14:58:19.513238: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:365] Ignored drop_control_dependency.
2022-08-29 14:58:19.514302: I tensorflow/cc/saved_model/reader.cc:43] Reading SavedModel from: /tmp/tmp2nbpvsye
2022-08-29 14:58:19.515041: I tensorflow/cc/saved_model/reader.cc:81] Reading meta graph with tags { serve }
2022-08-29 14:58:19.515068: I tensorflow/cc/saved_model/reader.cc:122] Reading SavedModel debug info (if present) from: /tmp/tmp2nbpvsye
2022-08-29 14:58:19.516323: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:354] MLIR V1 optimization pass is not enabled
2022-08-29 14:58:19.516678: I tensorflow/cc/saved_model/loader.cc:228] Restoring SavedModel bundle.
2022-08-29 14:58:19.526968: I tensorflow/cc/saved_model/loader.cc:212] Running initialization op on SavedModel bundle at path: /tmp/tmp2nbpvsye
2022-08-29 14:58:19.530414: I tensorflow/cc/saved_model/loader.cc:301] SavedModel load for tags { serve }; Status: success: OK. Took 16115 microseconds.
2022-08-29 14:58:19.535114: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:263] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2022-08-29 14:58:19.541989: W tensorflow/compiler/mlir/lite/flatbuffer_export.cc:1901] TFLite interpreter needs to link Flex delegate in order to run the model since it contains the following Select TFop(s):
Flex ops: FlexAddV2
Details:
        tf.AddV2(tensor<?x32xi8>, tensor<i8>) -> (tensor<?x32xi8>) : {device = ""}
See instructions: https://www.tensorflow.org/lite/guide/ops_select
2022-08-29 14:58:19.542019: I tensorflow/compiler/mlir/lite/flatbuffer_export.cc:1972] Estimated count of arithmetic ops: 0  ops, equivalently 0  MACs

Estimated count of arithmetic ops: 0  ops, equivalently 0  MACs
INFO: Created TensorFlow Lite delegate for select TF ops.
INFO: TfLiteFlexDelegate delegate: 1 nodes delegated out of 1 nodes with 1 partitions.

fully_quantize: 0, inference_type: 6, input_inference_type: 9, output_inference_type: 9
2022-08-29 14:58:19.546896: I tensorflow/compiler/mlir/lite/flatbuffer_export.cc:1972] Estimated count of arithmetic ops: 0  ops, equivalently 0  MACs

Estimated count of arithmetic ops: 0  ops, equivalently 0  MACs

**Comment by mohantym** [comment]
@gsirocco !
Thanks for the update. 
I see a line on MLIR in stack trace.
`tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:263] disabling MLIR crash reproducer, set env var MLIR_CRASH_REPRODUCER_DIRECTORY to enable.`
Could you please  give one more try with below syntax . Passing to @sachinprasadhs  for faster resolution.
```
import tensorflow as tf
from tensorflow import keras
import numpy as np

def representative_dataset():
for _ in range(100):
data = np.random.rand(1, 32)
yield [data.astype(np.int8)]

input = keras.Input(shape=(32,), name="dummy_input", dtype=tf.int8)
output = tf.add(input, 1)
model = keras.Model(inputs=input, outputs=output)
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset
converter.target_spec.supported_ops = [
tf.lite.OpsSet.TFLITE_BUILTINS_INT8, # enable TensorFlow Lite ops.
tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
converter.inference_input_type = tf.int8 # or tf.uint8
converter.inference_output_type = tf.int8 # or tf.uint8
converter.experimental_new_quantizer = True // It will enable conversion and quantization of MLIR ops
tflite_quant_model = converter.convert()
```

Thank you!

**Comment by gsirocco** [comment]
I added the line:  converter.experimental_new_quantizer = True // It will enable conversion and quantization of MLIR ops
However, it did not seem to help, here is the output. Thanks!

$ python t2tf.py
2022-08-30 05:03:33.488129: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-08-30 05:03:33.488156: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-08-30 05:03:34.507121: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-08-30 05:03:34.507147: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-08-30 05:03:34.507163: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ubuntugsosnow): /proc/driver/nvidia/version does not exist
2022-08-30 05:03:34.507351: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
/home/gsosnow/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/convert.py:766: UserWarning: Statistics for quantized inputs were expected, but not specified; continuing anyway.
  warnings.warn("Statistics for quantized inputs were expected, but not "
2022-08-30 05:03:34.763784: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:362] Ignored output_format.
2022-08-30 05:03:34.763804: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:365] Ignored drop_control_dependency.
2022-08-30 05:03:34.764475: I tensorflow/cc/saved_model/reader.cc:43] Reading SavedModel from: /tmp/tmpnjzjl5f6
2022-08-30 05:03:34.764915: I tensorflow/cc/saved_model/reader.cc:81] Reading meta graph with tags { serve }
2022-08-30 05:03:34.764938: I tensorflow/cc/saved_model/reader.cc:122] Reading SavedModel debug info (if present) from: /tmp/tmpnjzjl5f6
2022-08-30 05:03:34.765907: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:354] MLIR V1 optimization pass is not enabled
2022-08-30 05:03:34.766257: I tensorflow/cc/saved_model/loader.cc:228] Restoring SavedModel bundle.
2022-08-30 05:03:34.777494: I tensorflow/cc/saved_model/loader.cc:212] Running initialization op on SavedModel bundle at path: /tmp/tmpnjzjl5f6
2022-08-30 05:03:34.780786: I tensorflow/cc/saved_model/loader.cc:301] SavedModel load for tags { serve }; Status: success: OK. Took 16316 microseconds.
2022-08-30 05:03:34.785121: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:263] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2022-08-30 05:03:34.793081: W tensorflow/compiler/mlir/lite/flatbuffer_export.cc:1901] TFLite interpreter needs to link Flex delegate in order to run the model since it contains the following Select TFop(s):
Flex ops: FlexAddV2
Details:
        tf.AddV2(tensor<?x32xi8>, tensor<i8>) -> (tensor<?x32xi8>) : {device = ""}
See instructions: https://www.tensorflow.org/lite/guide/ops_select
2022-08-30 05:03:34.793119: I tensorflow/compiler/mlir/lite/flatbuffer_export.cc:1972] Estimated count of arithmetic ops: 0  ops, equivalently 0  MACs

Estimated count of arithmetic ops: 0  ops, equivalently 0  MACs
INFO: Created TensorFlow Lite delegate for select TF ops.
INFO: TfLiteFlexDelegate delegate: 1 nodes delegated out of 1 nodes with 1 partitions.

fully_quantize: 0, inference_type: 6, input_inference_type: 9, output_inference_type: 9
2022-08-30 05:03:34.799030: I tensorflow/compiler/mlir/lite/flatbuffer_export.cc:1972] Estimated count of arithmetic ops: 0  ops, equivalently 0  MACs

Estimated count of arithmetic ops: 0  ops, equivalently 0  MACs

**Comment by gsirocco** [comment]
Hi I was just checking if there was any insight to how to convert a TF model that uses the tf.add() op with int8 data type, but does not use the FlexAddV2 TF op, so it can be converted to EdgeTPU? If I convert to EdgeTPU with FlexAddV2, it fails. Thanks!!!

**Comment by gsirocco** [comment]
I have added the line (converter.target_spec.supported_types = [tf.int8]) for the post training quantization.
It looks like it's not using the FlexAddV2 anymore, but is failing for some other reason.
That 'tf.AddV2' op is neither a custom op nor a flex op??
Thanks!

`import tensorflow as tf
from tensorflow import keras
import numpy as np
import random

def representative_dataset():
    for _ in range(100):
        #data = random.randint(0, 1)
        #yield [data]
        data = np.random.rand(32)*2
        yield [data.astype(np.int8)]

input = keras.Input(shape=(32,), name="dummy_input", dtype=tf.int8)
output = tf.add(input, 1)
model = keras.Model(inputs=input, outputs=output)
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset
converter.target_spec.supported_ops = [
tf.lite.OpsSet.TFLITE_BUILTINS_INT8, # enable TensorFlow Lite ops.
tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
`converter.target_spec.supported_types = [tf.int8]
converter.inference_input_type = tf.int8 # or tf.uint8
converter.inference_output_type = tf.int8 # or tf.uint8
converter.experimental_new_quantizer = True # It will enable conversion and quantization of MLIR ops
tflite_quant_model = converter.convert()
`

Output from running the conversion:

`2022-09-01 14:40:33.947073: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-09-01 14:40:33.947098: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-09-01 14:40:34.954701: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-09-01 14:40:34.954726: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-09-01 14:40:34.954741: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ubuntugsosnow): /proc/driver/nvidia/version does not exist
2022-09-01 14:40:34.954944: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
/home/gsosnow/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/convert.py:766: UserWarning: Statistics for quantized inputs were expected, but not specified; continuing anyway.
  warnings.warn("Statistics for quantized inputs were expected, but not "
2022-09-01 14:40:35.192240: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:362] Ignored output_format.
2022-09-01 14:40:35.192268: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:365] Ignored drop_control_dependency.
2022-09-01 14:40:35.193142: I tensorflow/cc/saved_model/reader.cc:43] Reading SavedModel from: /tmp/tmprndll_uk
2022-09-01 14:40:35.193790: I tensorflow/cc/saved_model/reader.cc:81] Reading meta graph with tags { serve }
2022-09-01 14:40:35.193826: I tensorflow/cc/saved_model/reader.cc:122] Reading SavedModel debug info (if present) from: /tmp/tmprndll_uk
2022-09-01 14:40:35.195221: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:354] MLIR V1 optimization pass is not enabled
2022-09-01 14:40:35.195628: I tensorflow/cc/saved_model/loader.cc:228] Restoring SavedModel bundle.
2022-09-01 14:40:35.207140: I tensorflow/cc/saved_model/loader.cc:212] Running initialization op on SavedModel bundle at path: /tmp/tmprndll_uk
2022-09-01 14:40:35.211039: I tensorflow/cc/saved_model/loader.cc:301] SavedModel load for tags { serve }; Status: success: OK. Took 17900 microseconds.
2022-09-01 14:40:35.215280: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:263] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
loc(callsite(callsite(fused["AddV2:", callsite("model/tf.math.add/Add@__inference__wrapped_model_22"("/home/gsosnow/anaconda3/lib/python3.9/site-packages/tensorflow/python/saved_model/save.py":1325:0) at callsite("/home/gsosnow/anaconda3/lib/python3.9/site-packages/tensorflow/python/saved_model/save.py":1290:0 at callsite("/home/gsosnow/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/lite.py":1248:0 at callsite("/home/gsosnow/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/convert_phase.py":205:0 at callsite("/home/gsosnow/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/lite.py":1318:0 at callsite("/home/gsosnow/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/lite.py":1338:0 at callsite("/home/gsosnow/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/lite.py":908:0 at callsite("/home/gsosnow/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/lite.py":929:0 at "/home/gsosnow/doc/gt2tf.py":27:0))))))))] at fused["PartitionedCall:", callsite("PartitionedCall@__inference_signature_wrapper_75"("/home/gsosnow/anaconda3/lib/python3.9/site-packages/tensorflow/python/saved_model/save.py":1325:0) at callsite("/home/gsosnow/anaconda3/lib/python3.9/site-packages/tensorflow/python/saved_model/save.py":1290:0 at callsite("/home/gsosnow/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/lite.py":1248:0 at callsite("/home/gsosnow/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/convert_phase.py":205:0 at callsite("/home/gsosnow/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/lite.py":1318:0 at callsite("/home/gsosnow/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/lite.py":1338:0 at callsite("/home/gsosnow/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/lite.py":908:0 at callsite("/home/gsosnow/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/lite.py":929:0 at "/home/gsosnow/doc/gt2tf.py":27:0))))))))]) at fused["PartitionedCall:", "PartitionedCall"])): error: 'tf.AddV2' op is neither a custom op nor a flex op
error: failed while converting: 'main':
Some ops are not supported by the native TFLite runtime, you can enable TF kernels fallback using TF Select. See instructions: https://www.tensorflow.org/lite/guide/ops_select
TF Select ops: AddV2
Details:
        tf.AddV2(tensor<?x32xi8>, tensor<i8>) -> (tensor<?x32xi8>) : {device = ""}

Traceback (most recent call last):
  File "/home/gsosnow/doc/gt2tf.py", line 27, in <module>
    tflite_quant_model = converter.convert()
  File "/home/gsosnow/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/lite.py", line 929, in wrapper
    return self._convert_and_export_metrics(convert_func, *args, **kwargs)
  File "/home/gsosnow/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/lite.py", line 908, in _convert_and_export_metrics
    result = convert_func(self, *args, **kwargs)
  File "/home/gsosnow/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/lite.py", line 1338, in convert
    saved_model_convert_result = self._convert_as_saved_model()
  File "/home/gsosnow/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/lite.py", line 1320, in _convert_as_saved_model
    return super(TFLiteKerasModelConverterV2,
  File "/home/gsosnow/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/lite.py", line 1131, in convert
    result = _convert_graphdef(
  File "/home/gsosnow/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/convert_phase.py", line 212, in wrapper
    raise converter_error from None  # Re-throws the exception.
  File "/home/gsosnow/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/convert_phase.py", line 205, in wrapper
    return func(*args, **kwargs)
  File "/home/gsosnow/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/convert.py", line 794, in convert_graphdef
    data = convert(
  File "/home/gsosnow/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/convert.py", line 311, in convert
    raise converter_error
tensorflow.lite.python.convert_phase.ConverterError: /home/gsosnow/anaconda3/lib/python3.9/site-packages/tensorflow/python/saved_model/save.py:1325:0: error: 'tf.AddV2' op is neither a custom op nor a flex op
<unknown>:0: note: loc(fused["PartitionedCall:", "PartitionedCall"]): called from
/home/gsosnow/anaconda3/lib/python3.9/site-packages/tensorflow/python/saved_model/save.py:1325:0: note: Error code: ERROR_NEEDS_FLEX_OPS
<unknown>:0: error: failed while converting: 'main':
Some ops are not supported by the native TFLite runtime, you can enable TF kernels fallback using TF Select. See instructions: https://www.tensorflow.org/lite/guide/ops_select
TF Select ops: AddV2
Details:
        tf.AddV2(tensor<?x32xi8>, tensor<i8>) -> (tensor<?x32xi8>) : {device = ""}
`

**Comment by gsirocco** [comment]
Hi, just checking if I can get any feedback on this issue. Is it something that I am doing wrong, or is it an issue that's a known limitation or new bug?

We have several TF models that take too long to execute as TF or TFLite models, so we need to try to execute them on HW such as TPU to see if they can meet performance goals. So being able to convert TF models to TFLite and then to Edge TPU is critical. It seems like this shouldn't be too hard. Please help in anyway possible and don't hesitate to provide any guidance on how to accomplish this goal, such as maybe even directly implementing the models in TFLite or something if possible. I appreciate any assistance since I am at a dead end currently.

**Comment by gsirocco** [comment]
Hi @sachinprasadhs and @mohantym
I was just checking if you had any feedback on this issue as it is quite critical for our product development to be able to utilize the TPU for performance gain. Any update would be greatly appreciated.
Thanks!!

**Comment by gsirocco** [comment]
fyi, this was resolved in google-coral/edgetpu github issue:
https://github.com/google-coral/edgetpu/issues/655
