### ISSUE TITLE
M1 tf.gather_nd: InvalidArgumentError: Multiple OpKernel registrations match NodeDef at the same priority

### ISSUE THREAD

**Issue by RyanSaxe** [tensorflow/tensorflow#57549]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.9.2

### Custom Code

Yes

### OS Platform and Distribution

MacOS Monterey 12.5

### Python version

3.10

### Current Behaviour?

```shell
tf.gather_nd should properly have a gradient of shape (2,6) in the code below connecting the (very bad and toy) loss to the defined variable. However, it appears that the kernel sets the same priority for some operations and cannot resolve the graph.

Furthermore, I have observed the following *extremely weird* behavior:

If you change the code to `indexed_v = tf.gather_nd(v + 0.0, indices)`, there is no error.

I have also confirmed that this issue does not occur if I go back to a much older version of tensorflow: `2.4.0-rc0`

Lastly, for reproducibility, I set up my virtual environment with the following executions

>>> conda create -n tf_bug_test python=3.10
>>> conda activate tf_bug_test
>>> conda install -c apple tensorflow-deps
>>> python -m pip install tensorflow-macos

Note that if I install tensorflow-metal, the same error will happen but it will specify the computation is on GPU instead of CPU.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np

time = 100
products = 6
var_dim = 2

which_parameter_to_grab = np.random.binomial(1, p=0.1,size=(time, products))
v = tf.Variable(tf.ones((2,products)),name="test",dtype=tf.float32,shape=(var_dim,products))
# generate random indices for grabbing a parameter 
indices = np.stack(
    (which_parameter_to_grab, np.tile(np.arange(products)[None, :], (time, 1))),
    axis=2,
).astype(int)

opt_fcn = tf.keras.optimizers.Adam(learning_rate=1e-3)

with tf.GradientTape() as tape:
    indexed_v = tf.gather_nd(v, indices)
    loss_val = tf.reduce_mean(tf.math.square(indexed_v))
grads = tape.gradient(loss_val, [v])
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/Users/ryansaxe/Documents/bug_reproduce.py", line 21, in <module>
    grads = tape.gradient(loss_val, [v])
  File "/Users/ryansaxe/miniforge3/envs/tf_bug_test/lib/python3.10/site-packages/tensorflow/python/eager/backprop.py", line 1100, in gradient
    flat_grad = imperative_grad.imperative_grad(
  File "/Users/ryansaxe/miniforge3/envs/tf_bug_test/lib/python3.10/site-packages/tensorflow/python/eager/imperative_grad.py", line 67, in imperative_grad
    return pywrap_tfe.TFE_Py_TapeGradient(
  File "/Users/ryansaxe/miniforge3/envs/tf_bug_test/lib/python3.10/site-packages/tensorflow/python/eager/backprop.py", line 157, in _gradient_function
    return grad_fn(mock_op, *out_grads)
  File "/Users/ryansaxe/miniforge3/envs/tf_bug_test/lib/python3.10/site-packages/tensorflow/python/ops/array_grad.py", line 736, in _ResourceGatherNdGrad
    ref_shape = gen_resource_variable_ops.variable_shape(ref, indices.dtype)
  File "/Users/ryansaxe/miniforge3/envs/tf_bug_test/lib/python3.10/site-packages/tensorflow/python/ops/gen_resource_variable_ops.py", line 1341, in variable_shape
    _ops.raise_from_not_ok_status(e, name)
  File "/Users/ryansaxe/miniforge3/envs/tf_bug_test/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 7164, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Multiple OpKernel registrations match NodeDef at the same priority '{{node VariableShape}}': 'op: "VariableShape" device_type: "CPU" constraint { name: "out_type" allowed_values { list { type: DT_INT64 } } }' and 'op: "VariableShape" device_type: "CPU" constraint { name: "out_type" allowed_values { list { type: DT_INT64 } } }'
	 when instantiating VariableShape [Op:VariableShape]
```
</details>

**Comment by gadagashwini** [comment]
Hi @RyanSaxe, I tried to replicate given issue, but I am getting different error.Could you take look at error and help us in reproducing this issue.

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/gadag/tensorflow-metal/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/gadag/tensorflow-metal/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 7164, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.NotFoundError: No registered 'ResourceGatherNd' OpKernel for 'GPU' devices compatible with node {{node ResourceGatherNd}
```

**Comment by gadagashwini** [comment]
Hi @RyanSaxe, I used `python -m pip install tensorflow-metal` to get Tensorflow on Mac. Thank you!

**Comment by RyanSaxe** [comment]
Now that this has been reopened, how can I help here. From what I understand:

1. You have confirmed that this code is causing an error on specifically M1 hardware
2. My system and your system have slightly different errors but they are clearly related as they both have to do with the kernel related to this specific operation 

I cannot seem to produce the error you shared on my system, but any error here is a problem as it is not performing as intended. Please let me know if I can provide more information to help in the resolution of this bug.

**Comment by sergey-a-berezin** [comment]
To add my voice, I'm having the same problem with the latest  `tensorflow-macos==2.12.0` and `tensorflow-metal==0.8.0`, MacBook Air M1 2020, Ventura 13.4, python 3.10.11:

```python
import tensorflow as tf

# with tf.device('/device:cpu:0'):  # works fine
with tf.device('/device:gpu:0'):  # crashes
    x = tf.Variable(tf.random.normal((3, 3))) # crashes on GPU
   #  x = tf.random.normal((3, 3)) # works on both CPU and GPU

idx = tf.random.uniform((2, 2), minval=0, maxval=3, dtype=tf.int32)
tf.gather_nd(x, idx)
```
Crashes with:
```
InvalidArgumentError: Cannot assign a device for operation ResourceGatherNd: 
Could not satisfy explicit device specification '/job:localhost/replica:0/task:0/device:GPU:0' 
because no supported kernel for GPU devices is available.
```
Changing the device to `device:cpu:0` makes the example work fine. FWIW, `tf.gather` works fine on both GPU and CPU.
Also, the issue is only with variables allocated on GPU. Using a non-variable `Tensor` also works fine on both devices.

**Comment by sachinprasadhs** [comment]
Hi, 

The issue seems to be resolved with the latest Tensorflow version.

You can now install Tensorflow package on M1 from 2.13 using pip install Tensorflow.

Below is the command to install Tensorflow package, once it is installed, code mentioned in the issue runs without any error. 

`!pip install tensorflow==2.13rc1`

**Comment by RahulSajnani** [comment]
> In colab, with CPU runtime the code is getting executed without any error, attached gist [here](https://colab.sandbox.google.com/gist/sachinprasadhs/6c28fd2530d18727ad72d5af4c0f0f5c/57549.ipynb) for reference. In M1 mac, I'm getting different error. Note: I have installed tensorflow-metal to use GPU in my instance. <img alt="image" width="1549" src="https://user-images.githubusercontent.com/73069040/202049142-4fa25ca3-9377-4ad6-81dd-ec79ccd880fa.png">

Did you find a solution? @sachinprasadhs installing tf 2.13rc1 did not help me.
