### ISSUE TITLE
Why is `tf.Conv2D` treated as a SELECT op?

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/tensorflow#57550]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS (Intel)
- TensorFlow installation (pip package or built from source): `pip`
- TensorFlow library (version, if pip package or github SHA, if built from source): TensorFlow 2.9.1

### 2. Code

```py
from transformers import TFMobileViTForImageClassification
import tensorflow as tf

model = TFMobileViTForImageClassification.from_pretrained("apple/mobilevit-xx-small")

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()
with open("mobilevit_xxs.tflite", "wb") as f:
    f.write(tflite_model)
```

Install `transformers` by running `pip install git+https://github.com/sayakpaul/transformers@feat/tf-mobilevit`.

### 3. Failure ~after~ before conversion

```bash
Some ops are not supported by the native TFLite runtime, you can enable TF kernels fallback using TF Select. See instructions: https://www.tensorflow.org/lite/guide/ops_select
TF Select ops: Conv2D
Details:
	tf.Conv2D(tensor<?x?x?x?xf32>, tensor<1x1x64x48xf32>) -> (tensor<?x?x?x48xf32>) : {data_format = "NHWC", dilations = [1, 1, 1, 1], explicit_paddings = [], padding = "VALID", strides = [1, 1, 1, 1], use_cudnn_on_gpu = true}
	tf.Conv2D(tensor<?x?x?x?xf32>, tensor<1x1x80x64xf32>) -> (tensor<?x?x?x64xf32>) : {data_format = "NHWC", dilations = [1, 1, 1, 1], explicit_paddings = [], padding = "VALID", strides = [1, 1, 1, 1], use_cudnn_on_gpu = true}
	tf.Conv2D(tensor<?x?x?x?xf32>, tensor<1x1x96x80xf32>) -> (tensor<?x?x?x80xf32>) : {data_format = "NHWC", dilations = [1, 1, 1, 1], explicit_paddings = [], padding = "VALID", strides = [1, 1, 1, 1], use_cudnn_on_gpu = true}

Traceback (most recent call last):
  File "playground_tf.py", line 72, in <module>
    tflite_model = converter.convert()
  File "/Users/sayakpaul/.local/bin/.virtualenvs/hf/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 929, in wrapper
    return self._convert_and_export_metrics(convert_func, *args, **kwargs)
  File "/Users/sayakpaul/.local/bin/.virtualenvs/hf/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 908, in _convert_and_export_metrics
    result = convert_func(self, *args, **kwargs)
  File "/Users/sayakpaul/.local/bin/.virtualenvs/hf/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 1338, in convert
    saved_model_convert_result = self._convert_as_saved_model()
  File "/Users/sayakpaul/.local/bin/.virtualenvs/hf/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 1320, in _convert_as_saved_model
    return super(TFLiteKerasModelConverterV2,
  File "/Users/sayakpaul/.local/bin/.virtualenvs/hf/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 1131, in convert
    result = _convert_graphdef(
  File "/Users/sayakpaul/.local/bin/.virtualenvs/hf/lib/python3.8/site-packages/tensorflow/lite/python/convert_phase.py", line 212, in wrapper
    raise converter_error from None  # Re-throws the exception.
  File "/Users/sayakpaul/.local/bin/.virtualenvs/hf/lib/python3.8/site-packages/tensorflow/lite/python/convert_phase.py", line 205, in wrapper
    return func(*args, **kwargs)
  File "/Users/sayakpaul/.local/bin/.virtualenvs/hf/lib/python3.8/site-packages/tensorflow/lite/python/convert.py", line 794, in convert_graphdef
    data = convert(
  File "/Users/sayakpaul/.local/bin/.virtualenvs/hf/lib/python3.8/site-packages/tensorflow/lite/python/convert.py", line 311, in convert
    raise converter_error
tensorflow.lite.python.convert_phase.ConverterError: /Users/sayakpaul/.local/bin/.virtualenvs/hf/lib/python3.8/site-packages/keras/engine/base_layer.py:1014:0: error: 'tf.Conv2D' op is neither a custom op nor a flex op
<unknown>:0: note: loc(fused["StatefulPartitionedCall:", "StatefulPartitionedCall"]): called from
/Users/sayakpaul/.local/bin/.virtualenvs/hf/lib/python3.8/site-packages/keras/engine/base_layer.py:1014:0: note: Error code: ERROR_NEEDS_FLEX_OPS
/Users/sayakpaul/.local/bin/.virtualenvs/hf/lib/python3.8/site-packages/keras/engine/base_layer.py:1014:0: error: 'tf.Conv2D' op is neither a custom op nor a flex op
<unknown>:0: note: loc(fused["StatefulPartitionedCall:", "StatefulPartitionedCall"]): called from
/Users/sayakpaul/.local/bin/.virtualenvs/hf/lib/python3.8/site-packages/keras/engine/base_layer.py:1014:0: note: Error code: ERROR_NEEDS_FLEX_OPS
/Users/sayakpaul/.local/bin/.virtualenvs/hf/lib/python3.8/site-packages/keras/engine/base_layer.py:1014:0: error: 'tf.Conv2D' op is neither a custom op nor a flex op
<unknown>:0: note: loc(fused["StatefulPartitionedCall:", "StatefulPartitionedCall"]): called from
/Users/sayakpaul/.local/bin/.virtualenvs/hf/lib/python3.8/site-packages/keras/engine/base_layer.py:1014:0: note: Error code: ERROR_NEEDS_FLEX_OPS
<unknown>:0: error: failed while converting: 'main':
Some ops are not supported by the native TFLite runtime, you can enable TF kernels fallback using TF Select. See instructions: https://www.tensorflow.org/lite/guide/ops_select
TF Select ops: Conv2D
Details:
	tf.Conv2D(tensor<?x?x?x?xf32>, tensor<1x1x64x48xf32>) -> (tensor<?x?x?x48xf32>) : {data_format = "NHWC", dilations = [1, 1, 1, 1], explicit_paddings = [], padding = "VALID", strides = [1, 1, 1, 1], use_cudnn_on_gpu = true}
	tf.Conv2D(tensor<?x?x?x?xf32>, tensor<1x1x80x64xf32>) -> (tensor<?x?x?x64xf32>) : {data_format = "NHWC", dilations = [1, 1, 1, 1], explicit_paddings = [], padding = "VALID", strides = [1, 1, 1, 1], use_cudnn_on_gpu = true}
	tf.Conv2D(tensor<?x?x?x?xf32>, tensor<1x1x96x80xf32>) -> (tensor<?x?x?x80xf32>) : {data_format = "NHWC", dilations = [1, 1, 1, 1], explicit_paddings = [], padding = "VALID", strides = [1, 1, 1, 1], use_cudnn_on_gpu = true}
```

If I add the select OPS during conversion, it passes:

```py
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS,  # Enable TensorFlow Lite ops.
    tf.lite.OpsSet.SELECT_TF_OPS,  # Enable TensorFlow ops.
]
```

With the following info:

```bash
WARNING:absl:Found untraced functions such as conv_stem_layer_call_fn, conv_stem_layer_call_and_return_conditional_losses, encoder_layer_call_fn, encoder_layer_call_and_return_conditional_losses, conv_1x1_exp_layer_call_fn while saving (showing 5 of 512). These functions will not be directly callable after loading.
2022-08-31 12:21:18.548394: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:362] Ignored output_format.
2022-08-31 12:21:18.548415: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:365] Ignored drop_control_dependency.
2022-08-31 12:21:23.916667: W tensorflow/compiler/mlir/lite/flatbuffer_export.cc:1901] TFLite interpreter needs to link Flex delegate in order to run the model since it contains the following Select TFop(s):
Flex ops: FlexConv2D
Details:
	tf.Conv2D(tensor<?x?x?x?xf32>, tensor<1x1x64x48xf32>) -> (tensor<?x?x?x48xf32>) : {data_format = "NHWC", dilations = [1, 1, 1, 1], explicit_paddings = [], padding = "VALID", strides = [1, 1, 1, 1], use_cudnn_on_gpu = true}
	tf.Conv2D(tensor<?x?x?x?xf32>, tensor<1x1x80x64xf32>) -> (tensor<?x?x?x64xf32>) : {data_format = "NHWC", dilations = [1, 1, 1, 1], explicit_paddings = [], padding = "VALID", strides = [1, 1, 1, 1], use_cudnn_on_gpu = true}
	tf.Conv2D(tensor<?x?x?x?xf32>, tensor<1x1x96x80xf32>) -> (tensor<?x?x?x80xf32>) : {data_format = "NHWC", dilations = [1, 1, 1, 1], explicit_paddings = [], padding = "VALID", strides = [1, 1, 1, 1], use_cudnn_on_gpu = true}
See instructions: https://www.tensorflow.org/lite/guide/ops_select
```

_**But my question is, why is Conv2D a select OP?**_

Attached is the SavedModel file for better investigation. 

[1.zip](https://github.com/tensorflow/tensorflow/files/9459235/1.zip)

### 4. (optional) RNN conversion support
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

### 5. (optional) Any other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by mohantym** [comment]
Hi @sayakpaul !
Could you check the solution in this [gist](https://colab.sandbox.google.com/gist/mohantym/1182222b6741c31848e8ca27d61657ef/git_57550.ipynb) and let us know.
Thank you!

**Comment by sayakpaul** [comment]
For converting with the select OPs, there isn't any problem. Please read the issue description. My question is why do I need to include the select op spec for a tf.Conv2D.

**Comment by mohantym** [comment]
@sayakpaul !
Conv2D is part of allowed [Select ops operators](https://www.tensorflow.org/lite/guide/op_select_allowlist#:~:text=raw_ops.ControlTrigger-,raw_ops.Conv2D,-raw_ops.Conv2DBackpropFilter) list. So, I used select ops syntax along using 

> experimental_new_converter = True and enable_resource_variables = True

  flag during conversion( as it was pre-trained model).
Thank you!

**Comment by sayakpaul** [comment]
I am still not sure why select op is needed for a tf.Conv2D. It's unnecessary if try to convert a model (say `tf.keras.applications.ResNet50`).

@khanlvg could you advise?

**Comment by mohantym** [comment]
@sachinprasadhs ! 
Could you look at this query.
Thank you!

**Comment by sachinprasadhs** [comment]
As of now Tensorflow Lite builtin operator library supports only limited number of Tensorflow operators. 
For the the model which is not convertible, with the use of SELECT OPS it will allow ops to fallback to the TFLite builtin op.
For more details, refer this link https://www.tensorflow.org/lite/guide/ops_select. Thanks!

**Comment by sayakpaul** [comment]
I think you're still missing the point. I keep asking why Conv2D would be selected as the SELECT OP. Your answer actually does not tell me that.

**Comment by mkolodziejczyk-piap** [comment]
I have similar problem, trying to convert YOLOX model from mmdetection (pytorch -> ONNX -> tf -> tf lite conversion pipeline):
```
TF Select ops: Conv2D, NonMaxSuppressionV4, Range, Transpose
Details:
	tf.Conv2D(tensor<?x?x?x?xf32>, tensor<3x3x12x80xf32>) -> (tensor<?x?x?x80xf32>) : {data_format = "NHWC", device = "", dilations = [1, 1, 1, 1], explicit_paddings = [], padding = "VALID", strides = [1, 1, 1, 1], use_cudnn_on_gpu = true}
	tf.NonMaxSuppressionV4(tensor<?x?xf32>, tensor<?xf32>, tensor<i32>, tensor<f32>, tensor<f32>) -> (tensor<?xi32>, tensor<i32>) : {pad_to_max_output_size = false}
	tf.Range(tensor<i64>, tensor<i64>, tensor<i64>) -> (tensor<?xi64>) : {device = ""}
	tf.Transpose(tensor<?x?x?x?x?x?xf32>, tensor<6xi32>) -> (tensor<?x?x?x?x?x?xf32>) : {device = ""}
```
All those are valid [tfl_ops](https://www.tensorflow.org/mlir/tfl_ops)

**Comment by tmlstrong** [comment]
@sayakpaul Because Conv2D that you using have dimension is 5, tflite support is 4. You can quick solve by reduce dimension from 5 to 4 by remove batch dimension

**Comment by sayakpaul** [comment]
Thanks. Any code snippets?

**Comment by sachinprasadhs** [comment]
This is what it is restricting in the code to check if the input rank is 4 or not, when it fails to match this criteria, it is falling back to the `Select OPS`.

https://github.com/tensorflow/tensorflow/blob/5c12e9c120748b8c2a58342c08f6b91d9b545075/tensorflow/compiler/mlir/lite/ir/tfl_ops.cc#L1233-L1252

**Comment by trieu1162000** [comment]
Hi @mkolodziejczyk-piap , 
Have you solved the issue? It would be greatly appreciated if you could help share the guideline to overcome it.
BRs,
