### ISSUE TITLE
Resource Exhausted Error MNIST Example with CPU and Python3 (3.4.3)

### ISSUE THREAD

**Issue by dlmacedo** [tensorflow/tensorflow#576]
I am having a Resource Exhausted Error in MNIST demo model with CPU and Python3 (3.4.3) [I am using Ubuntu 14.04LTS VMWare with 3 GB over a Windows 10 System; PIP Installation, No VirtualEnv, No Docker]:

$ python -m tensorflow.models.image.mnist.convolutional

david@ubuntu:~$ 
david@ubuntu:~$ python3 -m tensorflow.models.image.mnist.convolutional
Extracting data/train-images-idx3-ubyte.gz
Extracting data/train-labels-idx1-ubyte.gz
Extracting data/t10k-images-idx3-ubyte.gz
Extracting data/t10k-labels-idx1-ubyte.gz
I tensorflow/core/common_runtime/local_device.cc:40] Local device intra op parallelism threads: 1
I tensorflow/core/common_runtime/direct_session.cc:58] Direct session inter op parallelism threads: 1
Initialized!
Epoch 0.00
Minibatch loss: 12.053, learning rate: 0.010000
Minibatch error: 90.6%
W tensorflow/core/kernels/conv_ops.cc:178] Resource exhausted: OOM when allocating tensor with shapedim { size: 5000 } dim { size: 28 } dim { size: 28 } dim { size: 32 }
W tensorflow/core/common_runtime/executor.cc:1076] 0x579eaa0 Compute status: Resource exhausted: OOM when allocating tensor with shapedim { size: 5000 } dim { size: 28 } dim { size: 28 } dim { size: 32 }
	 [[Node: Conv2D_2 = Conv2D[T=DT_FLOAT, padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Const, Variable/read)]]
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 428, in _do_run
    target_list)
tensorflow.python.pywrap_tensorflow.StatusNotOK: Resource exhausted: OOM when allocating tensor with shapedim { size: 5000 } dim { size: 28 } dim { size: 28 } dim { size: 32 }
	 [[Node: Conv2D_2 = Conv2D[T=DT_FLOAT, padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Const, Variable/read)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/models/image/mnist/convolutional.py", line 290, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/models/image/mnist/convolutional.py", line 278, in main
    error_rate(validation_prediction.eval(), validation_labels))
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 460, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 2910, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 368, in run
    results = self._do_run(target_list, unique_fetch_targets, feed_dict_string)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 444, in _do_run
    e.code)
tensorflow.python.framework.errors.ResourceExhaustedError: OOM when allocating tensor with shapedim { size: 5000 } dim { size: 28 } dim { size: 28 } dim { size: 32 }
	 [[Node: Conv2D_2 = Conv2D[T=DT_FLOAT, padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Const, Variable/read)]]
Caused by op 'Conv2D_2', defined at:
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/models/image/mnist/convolutional.py", line 290, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/models/image/mnist/convolutional.py", line 250, in main
    validation_prediction = tf.nn.softmax(model(validation_data_node))
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/models/image/mnist/convolutional.py", line 188, in model
    padding='SAME')
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 211, in conv2d
    use_cudnn_on_gpu=use_cudnn_on_gpu, name=name)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/op_def_library.py", line 664, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 1834, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 1043, in __init__
    self._traceback = _extract_stack()

david@ubuntu:~$ 
david@ubuntu:~$

**Comment by dgcaron** [comment]
i am getting the exact same error when running this command in a docker container on windows 7 and the virtualbox host image.
