### ISSUE TITLE
Failed to import tensorflow on jetson xavier NX development kit even after installing tensorflow module

### ISSUE THREAD

**Issue by Gullipall-Rajesh-Kr** [tensorflow/tensorflow#57624]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

2.10.0rc3

### Custom Code

Yes

### Mobile device

Jetson Xavier NX platform ubuntu 20.04

### Current Behaviour?

```shell
showing Failed to load the native TensorFlow runtime.
```

### Standalone code to reproduce the issue

```shell
https://learnopencv.com/understanding-multiple-object-tracking-using-deepsort/
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: /usr/local/lib/python3.8/dist-packages/tensorflow/python/../../tensorflow_cpu_aws.libs/libgomp-d22c30c5.so.1.0.0: cannot allocate memory in static TLS block

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "detect_track.py", line 34, in <module>
    from deep_sort.tools import generate_detections as gdet
  File "/home/xaviernx/Desktop/pycharm projects/Detect_track/yolov5/deep_sort/tools/generate_detections.py", line 7, in <module>
    import tensorflow.compat.v1 as tf
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/__init__.py", line 36, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 77, in <module>
    raise ImportError(
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: /usr/local/lib/python3.8/dist-packages/tensorflow/python/../../tensorflow_cpu_aws.libs/libgomp-d22c30c5.so.1.0.0: cannot allocate memory in static TLS block


Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors for some common causes and solutions.
If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.
```
</details>

**Comment by mohantym** [comment]
Hi @Gullipall-Rajesh-Kr !
I think you changed code at line 7 from generate_detections.py 

`import tensorflow as tf
`

to 

`import tensorflow.compat.v1  as tf`

If you want to use compat.v1 mode , you should disable v2 behavior too.
```
import tensorflow.compat.v1  as tf
tf.disable_v2_behavior() 
```

But it is suggested to go with only as mentioned in the [original code](https://github.com/nwojke/deep_sort/blob/master/tools/generate_detections.py#:~:text=import%20tensorflow%20as%20tf).
`import tensorflow as tf`  # 2.x code base

Thank you!
