### ISSUE TITLE
ImportError: cannot import name 'test' from partially initialized module 'tensorflow._api.v2.__internal__'

### ISSUE THREAD

**Issue by fregire** [tensorflow/tensorflow#57625]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.9.2

### Custom Code

Yes

### OS Platform and Distribution

Debian GNU/Linux 11 (bullseye)

### Python version

3.9.9

### Current Behaviour?

```shell
I'm using tensorflow in docker container, but i get this error when trying to import this module.
Error can be solved if i install another or same version of this module (but for production its bad solution)
I have installed this packages (pip freeze):
absl-py==1.2.0
anyio==3.4.0
asgi-lifespan==1.0.1
asgiref==3.4.1
astroid==2.11.7
astunparse==1.6.3
asyncio-dgram==2.1.2
attrs==22.1.0
autoflake==1.4
bandit==1.7.4
black==22.3.0
cachetools==5.2.0
certifi==2021.10.8
charset-normalizer==2.0.7
click==8.1.3
dataclasses==0.6
deap==1.3.1
dill==0.3.5.1
fastapi==0.73.0
flatbuffers==1.12
gast==0.4.0
gitdb==4.0.9
GitPython==3.1.27
google-auth==2.11.0
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
grpcio==1.48.1
h11==0.12.0
h5py==3.7.0
httpcore==0.14.7
httptools==0.3.0
httpx==0.22.0
idna==3.3
importlib-metadata==4.12.0
iniconfig==1.1.1
isort==5.10.1
joblib==0.17.0
keras==2.9.0
Keras-Preprocessing==1.1.2
lazy-object-proxy==1.7.1
libclang==14.0.6
lxml==4.7.1
Markdown==3.4.1
MarkupSafe==2.1.1
mccabe==0.7.0
mypy==0.942
mypy-extensions==0.4.3
numpy==1.21.3
oauthlib==3.2.0
opt-einsum==3.3.0
packaging==21.3
pandas==1.3.4
pathspec==0.10.1
pbr==5.10.0
platformdirs==2.5.2
plotly==4.8.1
pluggy==1.0.0
protobuf==3.19.4
py==1.11.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pydantic==1.9.0
pyflakes==2.5.0
pylint==2.13.2
pyparsing==3.0.9
pytest==7.1.1
pytest-asyncio==0.18.3
pytest-timeout==2.1.0
python-dateutil==2.8.2
python-dotenv==0.19.2
pytz==2021.3
PyYAML==6.0
requests==2.26.0
requests-oauthlib==1.3.1
retrying==1.3.3
rfc3986==1.5.0
rsa==4.9
scapy==2.4.5
scikit-learn==0.24.2
scipy==1.7.2
six==1.16.0
smmap==5.0.0
sniffio==1.2.0
starlette==0.17.1
stevedore==4.0.0
stopit==1.1.2
tensorboard==2.9.1
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow==2.9.2
tensorflow-estimator==2.9.0
tensorflow-io-gcs-filesystem==0.26.0
termcolor==1.1.0
threadpoolctl==3.0.0
toml==0.10.2
tomli==2.0.1
TPOT==0.11.5
tqdm==4.62.3
types-PyYAML==6.0.5
typing-extensions==3.10.0.2
update-checker==0.18.0
urllib3==1.26.7
uvicorn==0.17.1
uvloop==0.16.0
vulture==2.3
watchgod==0.7
websockets==10.1
Werkzeug==2.2.2
wrapt==1.14.1
zipp==3.8.1
```

### Standalone code to reproduce the issue

```shell
root@c666258f6b9d:/app# python3
Python 3.9.9 (main, Mar 28 2022, 09:18:32) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
```

### Relevant log output

```shell
2022-09-06 09:42:52.620866: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-09-06 09:42:52.620890: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/tensorflow/__init__.py", line 45, in <module>
    from ._api.v2 import __internal__
  File "/usr/local/lib/python3.9/site-packages/tensorflow/_api/v2/__internal__/__init__.py", line 22, in <module>
    from . import test
ImportError: cannot import name 'test' from partially initialized module 'tensorflow._api.v2.__internal__' (most likely due to a circular import) (/usr/local/lib/python3.9/site-packages/tensorflow/_api/v2/__internal__/__init__.py)
```
</details>

**Comment by fregire** [comment]
Problem was in Dockerfile:
`
find /usr/local -depth \
        \( \
            \( -type d -a \( -name test -o -name tests -o -name idle_test \) \) \
            -o \( -type f -a \( -name '*.pyc' -o -name '*.pyo' -o -name '*.exe' \) \) \
        \) -exec rm -rf '{}' +
`
This command removed folder 'test' which was used in tensorflow
