### ISSUE TITLE
Unified Memory feature seems not working correctly

### ISSUE THREAD

**Issue by satoshi-iwata** [tensorflow/tensorflow#57627]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 22.04.1 LTS

### Python version

3.10.4

### CUDA/cuDNN version

11.7/8.5.0

### Current Behaviour?

I am trying to use Unified Memory feature guided by the link below.
https://stackoverflow.com/questions/58025069/how-to-enable-cuda-unified-memory-in-tensorflow-v2

However, it results in either an incorrect result or an error. I would really appreciate it if someone could check if it is a bug or my miss use.

Amount of device memory is 40 GB and amount of host memory is 503 GiB.

An result of 40GiB.py is below: 1 + 1 becomes 0.
```
2022-09-06 19:47:39.927372: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-09-06 19:47:41.557960: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-09-06 19:47:42.842460: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 323169 MB memory:  -> device: 0, name: NVIDIA A100-PCIE-40GB, pci bus id: 0000:1f:00.0, compute capability: 8.0
2022-09-06 19:47:42.844257: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 323169 MB memory:  -> device: 1, name: NVIDIA A100-PCIE-40GB, pci bus id: 0000:8b:00.0, compute capability: 8.0
2022-09-06 19:47:42.872079: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 323169 MB memory:  -> device: 0, name: NVIDIA A100-PCIE-40GB, pci bus id: 0000:1f:00.0, compute capability: 8.0
2022-09-06 19:47:42.873286: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 323169 MB memory:  -> device: 1, name: NVIDIA A100-PCIE-40GB, pci bus id: 0000:8b:00.0, compute capability: 8.0
tf.Tensor([[1. 1. 1. ... 1. 1. 1.]], shape=(1, 10737418240), dtype=float32)
tf.Tensor([[1. 1. 1. ... 1. 1. 1.]], shape=(1, 10737418240), dtype=float32)
tf.Tensor([[0. 0. 0. ... 0. 0. 0.]], shape=(1, 10737418240), dtype=float32)
```

An result of 40GB.py is below: CUDA_ERROR_ILLEGAL_ADDRESS
```
2022-09-06 19:51:12.360869: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-09-06 19:51:14.110566: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-09-06 19:51:15.392251: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 323169 MB memory:  -> device: 0, name: NVIDIA A100-PCIE-40GB, pci bus id: 0000:1f:00.0, compute capability: 8.0
2022-09-06 19:51:15.394253: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 323169 MB memory:  -> device: 1, name: NVIDIA A100-PCIE-40GB, pci bus id: 0000:8b:00.0, compute capability: 8.0
2022-09-06 19:51:15.422149: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 323169 MB memory:  -> device: 0, name: NVIDIA A100-PCIE-40GB, pci bus id: 0000:1f:00.0, compute capability: 8.0
2022-09-06 19:51:15.423485: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 323169 MB memory:  -> device: 1, name: NVIDIA A100-PCIE-40GB, pci bus id: 0000:8b:00.0, compute capability: 8.0
tf.Tensor([[1. 1. 1. ... 1. 1. 1.]], shape=(1, 10000000000), dtype=float32)
tf.Tensor([[1. 1. 1. ... 1. 1. 1.]], shape=(1, 10000000000), dtype=float32)
Traceback (most recent call last):
  File "/home/siwata/40GB.py", line 17, in <module>
    print(c)
  File "/home/siwata/.local/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 1097, in __str__
    value_text(self, is_repr=False), self.shape, self.dtype.name)
  File "/home/siwata/.local/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 260, in value_text
    text = numpy_text(tensor, is_repr=is_repr)
  File "/home/siwata/.local/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 231, in numpy_text
    text = repr(tensor._numpy()) if is_repr else str(tensor._numpy())
  File "/home/siwata/.local/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 1127, in _numpy
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InternalError: Could not synchronize CUDA stream: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
```

### Standalone code to reproduce the issue

40GiB.py
```python
import tensorflow as tf
from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession

config = ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 8
config.gpu_options.allow_growth = True
session = InteractiveSession(config=config)

with tf.device("/gpu:0"):
    size = 1024 ** 3 * 10 # 40 GiB
    a = tf.ones([1, size])
    print(a)
    b = tf.ones([1, size])
    print(b)
    c = tf.add(a, b)
    print(c)
```

40GB.py
```python
import tensorflow as tf
from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession

config = ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 8
config.gpu_options.allow_growth = True
session = InteractiveSession(config=config)

with tf.device("/gpu:0"):
    size = 1000 ** 3 * 10 # 40 GB
    a = tf.ones([1, size])
    print(a)
    b = tf.ones([1, size])
    print(b)
    c = tf.add(a, b)
    print(c)
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @satoshi-iwata !
Actually , Tensorflow has 2GB  Tensor size constraint . If I reduce the size to 2048 GB works.  Ref [gist](https://colab.sandbox.google.com/gist/mohantym/2f120eb6d1856f0a7931204aee8c9dca/git_57627.ipynb).
If you are handling a huge dataset (like 1 TBs) , You can opt for multi GPU/TPU distribution strategy and use batches of dataset which shall reduce the tensor size. Ref [doc](https://www.tensorflow.org/guide/distributed_training#mirroredstrategy:~:text=mirrored_strategy%20%3D%20tf.distribute.MirroredStrategy(devices%3D%5B%22/gpu%3A0%22%2C%20%22/gpu%3A1%22%5D).

Thank you!

**Comment by satoshi-iwata** [comment]
Hi @mohantym !
Thanks for your reply. Could you possibly point a document or a number of line of source code noting the maximum size of a Tensor? I tried to find it, but I could not.

I am confused that I could successfully run a program with tensors of 4GiB, which exceeds the 2GiB constraint.
Does the word "constraint" mean that it results in an unexpected behavior, instead of causing an error?

Another program I tried with 4 GiB tensors.
```python
import tensorflow as tf
from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession

config = ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 8
config.gpu_options.allow_growth = True
session = InteractiveSession(config=config)

with tf.device("/gpu:0"):
    size = 1024 ** 3 * 1 # 4 GiB
    a = tf.ones([1, size])
    print("a: ", a)
    b = tf.ones([1, size])
    print("b: ", b)
    c = tf.add(a, b)
    print("c: ", c)

    one = tf.constant(1.0)
    two = tf.constant(2.0)

    print("a equals to [1.]: ", tf.math.reduce_all(tf.math.equal(a, one)))
    print("b equals to [1.]: ", tf.math.reduce_all(tf.math.equal(b, one)))
    print("c equals to [2.]: ", tf.math.reduce_all(tf.math.equal(c, two)))
```

A result given by the program above.
```
2022-09-07 17:38:11.768953: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-09-07 17:38:13.420543: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-09-07 17:38:14.711898: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 323169 MB memory:  -> device: 0, name: NVIDIA A100-PCIE-40GB, pci bus id: 0000:1f:00.0, compute capability: 8.0
2022-09-07 17:38:14.713789: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 323169 MB memory:  -> device: 1, name: NVIDIA A100-PCIE-40GB, pci bus id: 0000:8b:00.0, compute capability: 8.0
2022-09-07 17:38:14.741612: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 323169 MB memory:  -> device: 0, name: NVIDIA A100-PCIE-40GB, pci bus id: 0000:1f:00.0, compute capability: 8.0
2022-09-07 17:38:14.742890: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 323169 MB memory:  -> device: 1, name: NVIDIA A100-PCIE-40GB, pci bus id: 0000:8b:00.0, compute capability: 8.0
a:  tf.Tensor([[1. 1. 1. ... 1. 1. 1.]], shape=(1, 1073741824), dtype=float32)
b:  tf.Tensor([[1. 1. 1. ... 1. 1. 1.]], shape=(1, 1073741824), dtype=float32)
c:  tf.Tensor([[2. 2. 2. ... 2. 2. 2.]], shape=(1, 1073741824), dtype=float32)
a equals to [1.]:  tf.Tensor(True, shape=(), dtype=bool)
b equals to [1.]:  tf.Tensor(True, shape=(), dtype=bool)
c equals to [2.]:  tf.Tensor(True, shape=(), dtype=bool)
```

**Comment by mohantym** [comment]
@satoshi-iwata !
I took reference on 2GB tensor size constraint from this [thread](https://github.com/tensorflow/tensorflow/issues/51870). In my case , it is failing in both GPU and CPU . 

@gadagashwini !
Could you look at this issue.

Thank you!

**Comment by gadagashwini** [comment]
I could able to replicate the issue with CUDA 11.4 and Tensorflow 2.9.

```
Traceback (most recent call last):
  File "/home/gadag/576271.py", line 13, in <module>
    print(a)
  File "/home/gadag/anaconda3/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 1093, in __str__
    value_text(self, is_repr=False), self.shape, self.dtype.name)
  File "/home/gadag/anaconda3/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 258, in value_text
    text = numpy_text(tensor, is_repr=is_repr)
  File "/home/gadag/anaconda3/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 229, in numpy_text
    text = repr(tensor._numpy()) if is_repr else str(tensor._numpy())
  File "/home/gadag/anaconda3/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 1123, in _numpy
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InternalError: Could not synchronize CUDA stream: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
```

**Comment by gadagashwini** [comment]
Hi @satoshi-iwata, Could you take a look at similar issue [here](https://discuss.tensorflow.org/t/mult-gpus-training-with-unified-memory/6428). Thank you!

**Comment by satoshi-iwata** [comment]
@mohantym 
Thank you for the link. If I hit the constraint, I believe I should get a raised error, though I did not. So, my problem may be another problem. Anyway, thanks for your help!

**Comment by satoshi-iwata** [comment]
Hi @gadagashwini !
Thanks for your comment. Actually, I have found it but it seemed a feature specific to XLA and I believe it is not for me. Moreover, even though I tried to use it, it raised another error and seemed not working properly. In addition, stats gained using  NVIDIA Nsight Systems show `cuMemAlloc` instead of `cuMemAllocManaged`. So, I believe the function does not work.

Program I tried: xla.py
```python
import tensorflow as tf

@tf.function(jit_compile=True)
def recompiled_on_launch():
    size = 1024 ** 3 * 10 # 40 GiB
    a = tf.ones([1, size])
    b = tf.ones([1, size])
    c = tf.add(a, b)
    return c

print(recompiled_on_launch())
```

A result
```
$ TF_XLA_FLAGS=--tf_xla_enable_xla_devices TF_FORCE_UNIFIED_MEMORY=1 XLA_PYTHON_CLIENT_MEM_FRACTION=8.0 nsys profile --stats=true python3 xla.py
2022-09-08 17:39:39.661560: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-09-08 17:39:42.293138: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-09-08 17:39:42.440802: I tensorflow/compiler/xla/service/service.cc:170] XLA service 0x556a73ab7b30 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2022-09-08 17:39:42.440849: I tensorflow/compiler/xla/service/service.cc:178]   StreamExecutor device (0): Host, Default Version
2022-09-08 17:39:43.050468: I tensorflow/compiler/xla/service/service.cc:170] XLA service 0x556a73b3a560 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2022-09-08 17:39:43.050537: I tensorflow/compiler/xla/service/service.cc:178]   StreamExecutor device (0): NVIDIA A100-PCIE-40GB, Compute Capability 8.0
2022-09-08 17:39:43.050552: I tensorflow/compiler/xla/service/service.cc:178]   StreamExecutor device (1): NVIDIA A100-PCIE-40GB, Compute Capability 8.0
2022-09-08 17:39:44.538802: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 38278 MB memory:  -> device: 0, name: NVIDIA A100-PCIE-40GB, pci bus id: 0000:1f:00.0, compute capability: 8.0
2022-09-08 17:39:44.543530: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 38278 MB memory:  -> device: 1, name: NVIDIA A100-PCIE-40GB, pci bus id: 0000:8b:00.0, compute capability: 8.0
2022-09-08 17:39:45.391060: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at xla_ops.cc:296 : INVALID_ARGUMENT: Incompatible shapes: [1,10737418240] vs. [1,10737418240]
         [[{{node Add}}]]
Traceback (most recent call last):
  File "/home/siwata/xla.py", line 11, in <module>
    print(recompiled_on_launch())
  File "/home/siwata/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/siwata/.local/lib/python3.10/site-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [1,10737418240] vs. [1,10737418240]
         [[{{node Add}}]] [Op:__inference_recompiled_on_launch_11]
...
CUDA API Statistics:

 Time (%)  Total Time (ns)  Num Calls    Avg (ns)      Med (ns)     Min (ns)    Max (ns)   StdDev (ns)           Name
 --------  ---------------  ---------  ------------  ------------  ----------  ----------  -----------  ----------------------
     88.7       49,718,165          1  49,718,165.0  49,718,165.0  49,718,165  49,718,165          0.0  cuMemAlloc_v2
      9.6        5,380,078          2   2,690,039.0   2,690,039.0   2,576,009   2,804,069    161,262.8  cuMemHostAlloc
      1.0          554,497         20      27,724.9       5,742.5       1,938     217,008     62,204.7  cuStreamCreate
      0.4          220,274        378         582.7         542.0         370       1,702        175.5  cuGetProcAddress
      0.1           83,185          2      41,592.5      41,592.5      14,951      68,234     37,676.8  cuMemGetInfo_v2
      0.1           46,420          2      23,210.0      23,210.0      19,690      26,730      4,978.0  cuCtxSynchronize
      0.1           38,407          1      38,407.0      38,407.0      38,407      38,407          0.0  cuMemsetD32_v2
      0.1           28,829         20       1,441.5       1,047.5         389       6,759      1,389.0  cuEventCreate
      0.0            2,786          1       2,786.0       2,786.0       2,786       2,786          0.0  cuInit
      0.0              391          1         391.0         391.0         391         391          0.0  cuModuleGetLoadingMode
...
```

If I run the program above with the array size of 40 MiB, instead of 40 GiB, it finishes without an error and the result is the one expected. However, it uses `cuMemAlloc` instead of `cuMemAllocManaged` too.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
