### ISSUE TITLE
dataset_fn: Table not initialized when saved preprocessor is loaded

### ISSUE THREAD

**Issue by cnglen** [tensorflow/tensorflow#57694]
# env

- Python 3.9.12 (main, Apr  5 2022, 01:53:17) 

- tf.__version__ == '2.10.0'

In distributed training,  I use tf.distribute.ParameterServerStrategy. 

- If I use the **saved** preprocessor(), an error raised. "Table not initialized."

- If I **construct** preprocessor(), no error.

The code is below, save it to demo.py: 

``` python

#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse
import multiprocessing
from typing import Dict, List

import portpicker
import tensorflow as tf


class MyPreprocessor(tf.keras.Model):
    def __init__(self):
        super().__init__(trainable=False)
        self._lookup = {}
        self._lookup["hour"] = tf.keras.layers.StringLookup(vocabulary=["00", "01", "02", "03", "04", "05"])

    def call(self, batch: Dict):
        ans = {}
        ans["lookup"] = self._lookup["hour"](batch["hour"])
        return ans

    def adapt(self, save_path="/tmp/preprocessor"):
        ds = tf.data.Dataset.from_tensor_slices(
            {
                "hour": ["01", "03", "04", "05", "01"],
            }
        )
        ds = ds.batch(2).map(self)
        _ = next(iter(ds))
        self.save("/tmp/preprocessor", save_traces=True)


def create_in_process_cluster(n_worker: int, n_ps: int = 1) -> "ClusterResolver":
    """Creates and starts local servers and returns the cluster_resolver."""
    worker_ports = [portpicker.pick_unused_port() for _ in range(n_worker)]
    ps_ports = [portpicker.pick_unused_port() for _ in range(n_ps)]

    cluster_dict = {}
    cluster_dict["worker"] = ["localhost:%s" % port for port in worker_ports]
    if n_ps > 0:
        cluster_dict["ps"] = ["localhost:%s" % port for port in ps_ports]

    cluster_spec = tf.train.ClusterSpec(cluster_dict)

    # Workers need some inter_ops threads to work properly.
    worker_config = tf.compat.v1.ConfigProto()
    if multiprocessing.cpu_count() < n_worker + 1:
        worker_config.inter_op_parallelism_threads = n_worker + 1

    for i in range(n_worker):
        tf.distribute.Server(cluster_spec, job_name="worker", task_index=i, config=worker_config, protocol="grpc")

    for i in range(n_ps):
        tf.distribute.Server(cluster_spec, job_name="ps", task_index=i, protocol="grpc")

    cluster_resolver = tf.distribute.cluster_resolver.SimpleClusterResolver(cluster_spec, rpc_layer="grpc")
    return cluster_resolver


def demo_ps(flag="ok"):

    n_worker, n_ps = 3, 1
    cluster_resolver = create_in_process_cluster(n_worker=n_worker, n_ps=n_ps)
    variable_partitioner = tf.distribute.experimental.partitioners.MinSizePartitioner(min_shard_bytes=(256 << 10), max_shards=n_ps)
    strategy = tf.distribute.ParameterServerStrategy(
        cluster_resolver,
        variable_partitioner=variable_partitioner,
    )
    coordinator = tf.distribute.coordinator.ClusterCoordinator(strategy=strategy)

    with coordinator.strategy.scope():
        p_construct = MyPreprocessor()
        p_construct.adapt("/tmp/preprocessor")
        p_loaded = tf.keras.models.load_model("/tmp/preprocessor")

        def dataset_fn(input_context):
            ds = (
                tf.data.Dataset.from_tensor_slices(
                    {
                        "hour": ["01", "01", "01", "05", "05", "05"],
                    }
                )
                .batch(3)
                .repeat(16)
                .map(p_loaded if flag == "bad" else p_construct)
            )
            return ds

    @tf.function
    def per_worker_dataset_fn():
        return strategy.distribute_datasets_from_function(dataset_fn=dataset_fn, options=None)

    ds = coordinator.create_per_worker_dataset(per_worker_dataset_fn)
    dsit = iter(ds)

    @tf.function
    def train_step_fn(iterator):
        z = next(iterator)
        tf.print(z)
        return z

    for i in range(5):
        coordinator.schedule(train_step_fn, args=(dsit,))

    coordinator.join()


def check_preprocessor():
    p_construct = MyPreprocessor()
    p_construct.adapt("/tmp/preprocessor")
    p_loaded = tf.keras.models.load_model("/tmp/preprocessor")

    for p in [p_construct, p_loaded]:
        print(p._lookup["hour"].get_vocabulary())


if __name__ == "__main__":

    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", "-m", default="demo_bad")
    args = parser.parse_args()
    print(args)

    if args.mode == "check_preprocessors":
        check_preprocessor()
    elif args.mode == "demo_ok":
        demo_ps("ok")
    elif args.mode == "demo_bad":
        demo_ps("bad")
    else:
        raise ValueError("only check_preprocessors/demo_ok/demo_bad supported")

```

# Output of `python demo.py`

- `python demo.py -m check_preprocessor`: Make sure both preprocessors has the same vocabulary
- `python demo.py -m demo_bad`: Show the error
- `python demo.py -m demo_ok`: this works( but should not be used for very large data)

## python demo.py -m check_preprocessors

2022-09-15 12:15:37.962618: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Namespace(mode='check_preprocessors')
2022-09-15 12:15:41.228254: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.

['[UNK]', '00', '01', '02', '03', '04', '05']
['[UNK]', '00', '01', '02', '03', '04', '05']

## python demo.py -m demo_bad

2022-09-15 12:15:19.220947: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Namespace(mode='demo_bad')
2022-09-15 12:15:22.503514: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-09-15 12:15:22.506460: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job ps -> {0 -> localhost:52592}
2022-09-15 12:15:22.506480: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job worker -> {0 -> localhost:52589, 1 -> localhost:52590, 2 -> localhost:52591}
2022-09-15 12:15:22.506599: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:438] Started server with target: grpc://localhost:52589
2022-09-15 12:15:22.513135: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job ps -> {0 -> localhost:52592}
2022-09-15 12:15:22.513177: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job worker -> {0 -> localhost:52589, 1 -> localhost:52590, 2 -> localhost:52591}
2022-09-15 12:15:22.555869: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:438] Started server with target: grpc://localhost:52590
2022-09-15 12:15:22.569988: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job ps -> {0 -> localhost:52592}
2022-09-15 12:15:22.570037: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job worker -> {0 -> localhost:52589, 1 -> localhost:52590, 2 -> localhost:52591}
2022-09-15 12:15:22.570326: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:438] Started server with target: grpc://localhost:52591
2022-09-15 12:15:22.578150: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job ps -> {0 -> localhost:52592}
2022-09-15 12:15:22.578189: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job worker -> {0 -> localhost:52589, 1 -> localhost:52590, 2 -> localhost:52591}
2022-09-15 12:15:22.620104: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:438] Started server with target: grpc://localhost:52592
2022-09-15 12:15:22.639992: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job ps -> {0 -> localhost:52592}
2022-09-15 12:15:22.640025: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job worker -> {0 -> localhost:52589, 1 -> localhost:52590, 2 -> localhost:52591}
2022-09-15 12:15:22.640080: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job chief -> {0 -> localhost:34262}
2022-09-15 12:15:22.650400: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job ps -> {0 -> localhost:52592}
2022-09-15 12:15:22.650423: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job worker -> {0 -> localhost:52589, 1 -> localhost:52590, 2 -> localhost:52591}
2022-09-15 12:15:22.684019: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job chief -> {0 -> localhost:34262}
2022-09-15 12:15:22.684142: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job ps -> {0 -> localhost:52592}
2022-09-15 12:15:22.684202: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job ps -> {0 -> localhost:52592}
2022-09-15 12:15:22.684235: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job worker -> {0 -> localhost:52589, 1 -> localhost:52590, 2 -> localhost:52591}
2022-09-15 12:15:22.684282: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job chief -> {0 -> localhost:34262}
2022-09-15 12:15:22.747368: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job ps -> {0 -> localhost:52592}
2022-09-15 12:15:22.747487: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job worker -> {0 -> localhost:52589, 1 -> localhost:52590, 2 -> localhost:52591}
2022-09-15 12:15:22.747513: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job chief -> {0 -> localhost:34262}
2022-09-15 12:15:22.747548: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job worker -> {0 -> localhost:52589, 1 -> localhost:52590, 2 -> localhost:52591}
2022-09-15 12:15:22.747652: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job chief -> {0 -> localhost:34262}
2022-09-15 12:15:22.747679: I tensorflow/core/distributed_runtime/eager/eager_service_impl.cc:275] Creating sync eager service context with rendezvous_id on host qimaodeMacBook-Pro.local /job:ps/replica:0/task:0
2022-09-15 12:15:22.814046: I tensorflow/core/distributed_runtime/eager/eager_service_impl.cc:275] Creating sync eager service context with rendezvous_id on host qimaodeMacBook-Pro.local /job:worker/replica:0/task:0
2022-09-15 12:15:22.814158: I tensorflow/core/distributed_runtime/eager/eager_service_impl.cc:275] Creating sync eager service context with rendezvous_id on host qimaodeMacBook-Pro.local /job:worker/replica:0/task:2
2022-09-15 12:15:22.814265: I tensorflow/core/distributed_runtime/eager/eager_service_impl.cc:275] Creating sync eager service context with rendezvous_id on host qimaodeMacBook-Pro.local /job:worker/replica:0/task:1
2022-09-15 12:15:22.817835: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job ps -> {0 -> localhost:52592}
2022-09-15 12:15:22.817886: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job worker -> {0 -> localhost:52589, 1 -> localhost:52590, 2 -> localhost:52591}
2022-09-15 12:15:22.883315: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job chief -> {0 -> localhost:34262}
2022-09-15 12:15:22.884199: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:438] Started server with target: grpc://localhost:34262
WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.
2022-09-15 12:15:23.511333: W tensorflow/core/framework/dataset.cc:769] Input of GeneratorDatasetOp::Dataset will not be optimized because the dataset does not implement the AsGraphDefInternal() method needed to apply optimizations.
2022-09-15 12:15:23.545379: W tensorflow/core/framework/op_kernel.cc:1780] OP_REQUIRES failed at lookup_table_op.cc:929 : FAILED_PRECONDITION: Table not initialized.
2022-09-15 12:15:23.545648: W tensorflow/core/framework/op_kernel.cc:1780] OP_REQUIRES failed at lookup_table_op.cc:929 : FAILED_PRECONDITION: Table not initialized.
2022-09-15 12:15:23.545861: W tensorflow/core/framework/op_kernel.cc:1780] OP_REQUIRES failed at lookup_table_op.cc:929 : FAILED_PRECONDITION: Table not initialized.
2022-09-15 12:15:23.546399: W ./tensorflow/core/distributed_runtime/eager/destroy_tensor_handle_node.h:58] Ignoring an error encountered when deleting remote tensors handles: INVALID_ARGUMENT: Unable to find the relevant tensor remote_handle: Op ID: 95, Output num: 0
Additional GRPC error information from remote target /job:worker/replica:0/task:2:
:{"created":"@1663215323.546318000","description":"Error received from peer ipv6:[::1]:52591","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Unable to find the relevant tensor remote_handle: Op ID: 95, Output num: 0","grpc_status":3} [type.googleapis.com/tensorflow.core.platform.ErrorSourceProto='\x08\x05']
2022-09-15 12:15:23.550175: W tensorflow/core/framework/op_kernel.cc:1780] OP_REQUIRES failed at lookup_table_op.cc:929 : FAILED_PRECONDITION: Table not initialized.
2022-09-15 12:15:23.577872: W tensorflow/core/framework/op_kernel.cc:1780] OP_REQUIRES failed at lookup_table_op.cc:929 : FAILED_PRECONDITION: Table not initialized.
2022-09-15 12:15:23.578019: W tensorflow/core/framework/op_kernel.cc:1780] OP_REQUIRES failed at lookup_table_op.cc:929 : FAILED_PRECONDITION: Table not initialized.
2022-09-15 12:15:23.578038: W tensorflow/core/framework/op_kernel.cc:1780] OP_REQUIRES failed at lookup_table_op.cc:929 : FAILED_PRECONDITION: Table not initialized.
ERROR:tensorflow:/job:worker/task:2 encountered the following error when processing closure: FailedPreconditionError():Graph execution error:

Table not initialized.
	 [[{{node string_lookup/None_Lookup/LookupTableFindV2}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNextAsOptional]]
Additional GRPC error information from remote target /job:worker/replica:0/task:2:
:{"created":"@1663215323.545921000","description":"Error received from peer ipv6:[::1]:52591","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":" Table not initialized.\n\t [[{{node string_lookup/None_Lookup/LookupTableFindV2}}]]\n\t [[MultiDeviceIteratorGetNextFromShard]]\n\t [[RemoteCall]]\n\t [[IteratorGetNextAsOptional]]","grpc_status":9} [Op:__inference_train_step_fn_409]
2022-09-15 12:15:23.578253: W tensorflow/core/framework/op_kernel.cc:1780] OP_REQUIRES failed at lookup_table_op.cc:929 : FAILED_PRECONDITION: Table not initialized.
2022-09-15 12:15:23.643837: W tensorflow/core/framework/op_kernel.cc:1780] OP_REQUIRES failed at lookup_table_op.cc:929 : FAILED_PRECONDITION: Table not initialized.
ERROR:tensorflow:/job:worker/task:1 encountered the following error when processing closure: FailedPreconditionError():Graph execution error:

Table not initialized.
	 [[{{node string_lookup/None_Lookup/LookupTableFindV2}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNextAsOptional]]
Additional GRPC error information from remote target /job:worker/replica:0/task:1:
:{"created":"@1663215323.578301000","description":"Error received from peer ipv6:[::1]:52590","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":" Table not initialized.\n\t [[{{node string_lookup/None_Lookup/LookupTableFindV2}}]]\n\t [[MultiDeviceIteratorGetNextFromShard]]\n\t [[RemoteCall]]\n\t [[IteratorGetNextAsOptional]]","grpc_status":9} [Op:__inference_train_step_fn_409]
2022-09-15 12:15:23.650184: W tensorflow/core/framework/op_kernel.cc:1780] OP_REQUIRES failed at lookup_table_op.cc:929 : FAILED_PRECONDITION: Table not initialized.
ERROR:tensorflow:/job:worker/task:0 encountered the following error when processing closure: FailedPreconditionError():Graph execution error:

Table not initialized.
	 [[{{node string_lookup/None_Lookup/LookupTableFindV2}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNextAsOptional]]
Additional GRPC error information from remote target /job:worker/replica:0/task:0:
:{"created":"@1663215323.578288000","description":"Error received from peer ipv6:[::1]:52589","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":" Table not initialized.\n\t [[{{node string_lookup/None_Lookup/LookupTableFindV2}}]]\n\t [[MultiDeviceIteratorGetNextFromShard]]\n\t [[RemoteCall]]\n\t [[IteratorGetNextAsOptional]]","grpc_status":9} [Op:__inference_train_step_fn_409]
ERROR:tensorflow:Start cancelling closures due to error FailedPreconditionError(): Graph execution error:

Table not initialized.
	 [[{{node string_lookup/None_Lookup/LookupTableFindV2}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNextAsOptional]]
Additional GRPC error information from remote target /job:worker/replica:0/task:2:
:{"created":"@1663215323.545921000","description":"Error received from peer ipv6:[::1]:52591","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":" Table not initialized.\n\t [[{{node string_lookup/None_Lookup/LookupTableFindV2}}]]\n\t [[MultiDeviceIteratorGetNextFromShard]]\n\t [[RemoteCall]]\n\t [[IteratorGetNextAsOptional]]","grpc_status":9} [Op:__inference_train_step_fn_409]
ERROR:tensorflow:/job:worker/task:2 encountered the following error when processing closure: FailedPreconditionError():Graph execution error:

Table not initialized.
	 [[{{node string_lookup/None_Lookup/LookupTableFindV2}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNextAsOptional]]
Additional GRPC error information from remote target /job:worker/replica:0/task:2:
:{"created":"@1663215323.649936000","description":"Error received from peer ipv6:[::1]:52591","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":" Table not initialized.\n\t [[{{node string_lookup/None_Lookup/LookupTableFindV2}}]]\n\t [[MultiDeviceIteratorGetNextFromShard]]\n\t [[RemoteCall]]\n\t [[IteratorGetNextAsOptional]]","grpc_status":9} [Op:__inference_train_step_fn_409]
Traceback (most recent call last):
  File "/home/myname/myrepo/recommender/recommender/ranker/qmrs/demo.py", line 130, in <module>
    demo_ps("bad")
  File "/home/myname/myrepo/recommender/recommender/ranker/qmrs/demo.py", line 106, in demo_ps
    coordinator.join()
  File "/opt/anaconda3/lib/python3.9/site-packages/tensorflow/python/distribute/coordinator/cluster_coordinator.py", line 1107, in join
    self._cluster.join()
  File "/opt/anaconda3/lib/python3.9/site-packages/tensorflow/python/distribute/coordinator/cluster_coordinator.py", line 914, in join
    self.closure_queue.wait()
  File "/opt/anaconda3/lib/python3.9/site-packages/tensorflow/python/distribute/coordinator/cluster_coordinator.py", line 447, in wait
    self._raise_if_error()
  File "/opt/anaconda3/lib/python3.9/site-packages/tensorflow/python/distribute/coordinator/cluster_coordinator.py", line 371, in _raise_if_error
    raise self._error  # pylint: disable=raising-bad-type
  File "/opt/anaconda3/lib/python3.9/site-packages/tensorflow/python/distribute/coordinator/cluster_coordinator.py", line 704, in _process_closure
    closure.execute_on(self)
  File "/opt/anaconda3/lib/python3.9/site-packages/tensorflow/python/distribute/coordinator/cluster_coordinator.py", line 248, in execute_on
    output_values = self._function(
  File "/opt/anaconda3/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 1892, in cancellable_call
    return self._call_impl(
  File "/opt/anaconda3/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 1613, in _call_impl
    return self._call_with_structured_signature(args, kwargs,
  File "/opt/anaconda3/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 1694, in _call_with_structured_signature
    return self._call_flat(
  File "/opt/anaconda3/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 1862, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/opt/anaconda3/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 506, in call
    outputs = execute.execute_with_cancellation(
  File "/opt/anaconda3/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 106, in execute_with_cancellation
    tensors = pywrap_tfe.TFE_Py_ExecuteCancelable(ctx._handle, device_name,
tensorflow.python.framework.errors_impl.FailedPreconditionError: Graph execution error:

Table not initialized.
	 [[{{node string_lookup/None_Lookup/LookupTableFindV2}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNextAsOptional]]
Additional GRPC error information from remote target /job:worker/replica:0/task:2:
:{"created":"@1663215323.545921000","description":"Error received from peer ipv6:[::1]:52591","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":" Table not initialized.\n\t [[{{node string_lookup/None_Lookup/LookupTableFindV2}}]]\n\t [[MultiDeviceIteratorGetNextFromShard]]\n\t [[RemoteCall]]\n\t [[IteratorGetNextAsOptional]]","grpc_status":9} [Op:__inference_train_step_fn_409]

## python demo.py -m demo_ok
2022-09-15 12:15:27.024498: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Namespace(mode='demo_ok')
2022-09-15 12:15:30.312957: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-09-15 12:15:30.315815: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job ps -> {0 -> localhost:52605}
2022-09-15 12:15:30.315859: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job worker -> {0 -> localhost:52602, 1 -> localhost:52603, 2 -> localhost:52604}
2022-09-15 12:15:30.316004: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:438] Started server with target: grpc://localhost:52602
2022-09-15 12:15:30.323038: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job ps -> {0 -> localhost:52605}
2022-09-15 12:15:30.323062: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job worker -> {0 -> localhost:52602, 1 -> localhost:52603, 2 -> localhost:52604}
2022-09-15 12:15:30.365470: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:438] Started server with target: grpc://localhost:52603
2022-09-15 12:15:30.382867: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job ps -> {0 -> localhost:52605}
2022-09-15 12:15:30.382900: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job worker -> {0 -> localhost:52602, 1 -> localhost:52603, 2 -> localhost:52604}
2022-09-15 12:15:30.383070: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:438] Started server with target: grpc://localhost:52604
2022-09-15 12:15:30.392620: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job ps -> {0 -> localhost:52605}
2022-09-15 12:15:30.392657: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job worker -> {0 -> localhost:52602, 1 -> localhost:52603, 2 -> localhost:52604}
2022-09-15 12:15:30.434817: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:438] Started server with target: grpc://localhost:52605
2022-09-15 12:15:30.452386: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job ps -> {0 -> localhost:52605}
2022-09-15 12:15:30.452423: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job worker -> {0 -> localhost:52602, 1 -> localhost:52603, 2 -> localhost:52604}
2022-09-15 12:15:30.452432: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job chief -> {0 -> localhost:34276}
2022-09-15 12:15:30.463669: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job ps -> {0 -> localhost:52605}
2022-09-15 12:15:30.463701: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job ps -> {0 -> localhost:52605}
2022-09-15 12:15:30.502447: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job ps -> {0 -> localhost:52605}
2022-09-15 12:15:30.502497: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job worker -> {0 -> localhost:52602, 1 -> localhost:52603, 2 -> localhost:52604}
2022-09-15 12:15:30.502526: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job chief -> {0 -> localhost:34276}
2022-09-15 12:15:30.502585: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job ps -> {0 -> localhost:52605}
2022-09-15 12:15:30.502626: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job worker -> {0 -> localhost:52602, 1 -> localhost:52603, 2 -> localhost:52604}
2022-09-15 12:15:30.502639: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job chief -> {0 -> localhost:34276}
2022-09-15 12:15:30.561039: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job worker -> {0 -> localhost:52602, 1 -> localhost:52603, 2 -> localhost:52604}
2022-09-15 12:15:30.561155: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job chief -> {0 -> localhost:34276}
2022-09-15 12:15:30.561203: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job worker -> {0 -> localhost:52602, 1 -> localhost:52603, 2 -> localhost:52604}
2022-09-15 12:15:30.561313: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job chief -> {0 -> localhost:34276}
2022-09-15 12:15:30.561383: I tensorflow/core/distributed_runtime/eager/eager_service_impl.cc:275] Creating sync eager service context with rendezvous_id on host qimaodeMacBook-Pro.local /job:ps/replica:0/task:0
2022-09-15 12:15:30.628756: I tensorflow/core/distributed_runtime/eager/eager_service_impl.cc:275] Creating sync eager service context with rendezvous_id on host qimaodeMacBook-Pro.local /job:worker/replica:0/task:2
2022-09-15 12:15:30.628934: I tensorflow/core/distributed_runtime/eager/eager_service_impl.cc:275] Creating sync eager service context with rendezvous_id on host qimaodeMacBook-Pro.local /job:worker/replica:0/task:1
2022-09-15 12:15:30.629041: I tensorflow/core/distributed_runtime/eager/eager_service_impl.cc:275] Creating sync eager service context with rendezvous_id on host qimaodeMacBook-Pro.local /job:worker/replica:0/task:0
2022-09-15 12:15:30.632171: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job ps -> {0 -> localhost:52605}
2022-09-15 12:15:30.632264: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job worker -> {0 -> localhost:52602, 1 -> localhost:52603, 2 -> localhost:52604}
2022-09-15 12:15:30.696763: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job chief -> {0 -> localhost:34276}
2022-09-15 12:15:30.698215: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:438] Started server with target: grpc://localhost:34276
WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.
2022-09-15 12:15:31.312783: W tensorflow/core/framework/dataset.cc:769] Input of GeneratorDatasetOp::Dataset will not be optimized because the dataset does not implement the AsGraphDefInternal() method needed to apply optimizations.
{'lookup': [2 2 2]}
{'lookup': [2 2 2]}
{'lookup': [2 2 2]}
{'lookup': [6 6 6]}
{'lookup': [6 6 6]}

**Comment by cnglen** [comment]
If add the line below: 
```python 
tf.data.experimental.enable_debug_mode()
```
The error is not shown.

Any suggestions? How to debug the code?

**Comment by w-xinyi** [comment]
Thanks for reporting the issue! A fix should be submitted soon.

**Comment by sachinprasadhs** [comment]
Hi, This issue seems to be fixed by the commit https://github.com/tensorflow/tensorflow/commit/18cb93ad8b6f0c3641f9c95fbca6105e701910cc which addresses Fix load context detection for correctly restore distributed table in KPL.
Please test it in the latest Tensorflow version and let us know the outcome. Thanks!
