### ISSUE TITLE
TFLite throws an error with certain tensor value

### ISSUE THREAD

**Issue by Co1lin** [tensorflow/tensorflow#57708]
### 1. Problem

For the same model, just changing the value of a constant tensor will cause an error.

### 2. Code

See the ipynb [here](https://colab.research.google.com/drive/15pshTNxXLDObJZbwes5tCvW1RXgbAHGA?usp=sharing#scrollTo=UDfz52j1K62g)

Log:

```python
RuntimeError: Index out of range using input dim 1; input has only 1 dimsNode number 2 (TfLiteFlexDelegate) failed to invoke.
```

**Comment by mohantym** [comment]
@Co1lin !
Similar to issue #57697 . I changed the shape from shape=[1,1,2,1] to shape=(1,1,2,1)  to resolve the issue. Attached [gist](https://colab.sandbox.google.com/gist/mohantym/d843039f3f0794a02d5017f6783503e4/untitled2.ipynb#scrollTo=MASXNObaC8tj) for reference.

**Comment by Co1lin** [comment]
@mohantym Hey! Could you please ` !pip install tensorflow==2.10.0` first in CoLab and then run the code with `print(tf.__version__)` as a confirmation? I found that for the default TF version which is 2.8 in CoLab, both `[1,1,2,1]` and `(1,1,2,1)` work fine. That's reasonable because on [this page](https://www.tensorflow.org/api_docs/python/tf/constant), the shape can be a list. But for 2.10.0, both will throw an error.

![image](https://user-images.githubusercontent.com/17642707/190542735-cde19a4d-648f-435d-b2dd-0387a532a5d8.png)

**Comment by Co1lin** [comment]
I tried to figure out if there's something wrong with `return o0[:, :, 0:1, :]`. But even I replace it with `return o0`, TFLite will still throw an error (but pure TF and other backends such as XLA will not), though the error is different. I guess there's something wrong with `tf.maximum` and its broadcasting in TFLite.

Error log after replacing `return o0[:, :, 0:1, :]` with `return o0`.

```python
tf version: 2.11.0-dev20220914

loc(callsite(callsite(fused["Identity:", callsite("Identity@__inference___call___13"("/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py":880:0) at callsite("/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py":150:0 at callsite("/home/colin/code/test/scripts/tflite.py":46:0 at "/home/colin/code/test/scripts/tflite.py":81:0)))] at fused["PartitionedCall:", callsite("PartitionedCall@__inference_signature_wrapper_23"("/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/python/saved_model/save.py":1267:0) at callsite("/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/python/saved_model/save.py":1231:0 at callsite("/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/lite/python/lite.py":1452:0 at callsite("/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/lite/python/convert_phase.py":205:0 at callsite("/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/lite/python/lite.py":1482:0 at callsite("/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/lite/python/lite.py":1505:0 at callsite("/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/lite/python/lite.py":911:0 at callsite("/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/lite/python/lite.py":933:0 at callsite("/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/lite/python/lite.py":1866:0 at "/home/colin/code/test/scripts/tflite.py":23:0)))))))))]) at fused["PartitionedCall:", "PartitionedCall"])): error: 'tf.Identity' op requires the same shape for all operands and results
Traceback (most recent call last):
  File "/home/colin/code/test/scripts/tflite.py", line 81, in <module>
    simple()
  File "/home/colin/code/test/scripts/tflite.py", line 48, in simple
    runner = get_tflite_callable(m, inp)
  File "/home/colin/code/test/scripts/tflite.py", line 23, in get_tflite_callable
    tflite_bytes = converter.convert()
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/lite/python/lite.py", line 1866, in convert
    return super(TFLiteConverterV2, self).convert()
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/lite/python/lite.py", line 933, in wrapper
    return self._convert_and_export_metrics(convert_func, *args, **kwargs)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/lite/python/lite.py", line 911, in _convert_and_export_metrics
    result = convert_func(self, *args, **kwargs)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/lite/python/lite.py", line 1505, in convert
    saved_model_convert_result = self._convert_as_saved_model()
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/lite/python/lite.py", line 1485, in _convert_as_saved_model
    return self._convert_from_saved_model(graph_def)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/lite/python/lite.py", line 1099, in _convert_from_saved_model
    result = _convert_saved_model(**converter_kwargs)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/lite/python/convert_phase.py", line 212, in wrapper
    raise converter_error from None  # Re-throws the exception.
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/lite/python/convert_phase.py", line 205, in wrapper
    return func(*args, **kwargs)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/lite/python/convert.py", line 808, in convert_saved_model
    data = convert(
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/lite/python/convert.py", line 310, in convert
    raise converter_error
tensorflow.lite.python.convert_phase.ConverterError: /home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py:880:0: error: 'tf.Identity' op requires the same shape for all operands and results
<unknown>:0: note: loc(fused["PartitionedCall:", "PartitionedCall"]): called from
```

**Comment by mohantym** [comment]
@Co1lin !
Sorry for the misunderstanding . Thanks for correcting me.
@sachinprasadhs !
Could you look at this issue. Attached gist in [2.9](https://colab.sandbox.google.com/gist/mohantym/4f7cd2967b8177654947c329f9d5fefa/untitled2.ipynb#scrollTo=u5T8_NLEbIUk) (working), [2.10](https://colab.sandbox.google.com/gist/mohantym/e05c13a214b716a7eda79da3dcbc85e4/untitled2.ipynb#scrollTo=u5T8_NLEbIUk)( Failing) and [nightly](https://colab.sandbox.google.com/gist/mohantym/cd31fee95fc40866003b87cd369e3db8/untitled2.ipynb#scrollTo=UDfz52j1K62g)(Failing) for reference.

Thank you!

**Comment by mohantym** [comment]
Hi @Co1lin!
Getting a different error now in 2.11 version  .
```
ConverterError: /usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/op_def_library.py:795:0: error: 'tf.Relu' op requires the same shape for all operands and results
<unknown>:0: note: loc(fused["PartitionedCall:", "PartitionedCall"]): called from
```

Attached [gist](https://colab.sandbox.google.com/gist/mohantym/f1cc965f1251021a3322710e5263bdef/untitled2.ipynb#scrollTo=UDfz52j1K62g) in 2.11  for reference.

Thank you!

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.
