### ISSUE TITLE
Failed precondition: Could not find variable Variable. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized.

### ISSUE THREAD

**Issue by MengHao666** [tensorflow/tensorflow#57803]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Source

binary

### Tensorflow Version

tensorflow                2.6.2

### Custom Code

Yes

### OS Platform and Distribution

win10

### Python version

3.6

### Bazel version

None

### GCC/Compiler version

None

### CUDA/cuDNN version

11.6

### GPU model and memory

None

### Current Behaviour?

```shell
raceback (most recent call last):
  File "C:\Users\raphaelmeng\.conda\envs\fdfd\lib\site-packages\tensorflow\python\client\session.py", line 1375, in _do_call
    return fn(*args)
  File "C:\Users\raphaelmeng\.conda\envs\fdfd\lib\site-packages\tensorflow\python\client\session.py", line 1360, in _run_fn
    target_list, run_metadata)
  File "C:\Users\raphaelmeng\.conda\envs\fdfd\lib\site-packages\tensorflow\python\client\session.py", line 1453, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.FailedPreconditionError: 2 root error(s) found.
  (0) Failed precondition: Could not find variable Variable. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status=Not found: Resource localhost/Variable/class tensorflow::Var does not exist.
	 [[{{node image-0/GatherV2/ReadVariableOp}}]]
	 [[strided_slice_54/_289]]
  (1) Failed precondition: Could not find variable Variable. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status=Not found: Resource localhost/Variable/class tensorflow::Var does not exist.
	 [[{{node image-0/GatherV2/ReadVariableOp}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/PycharmProjects/4dFaceOptimizerIK/approximation_v2.py", line 166, in <module>
    verts0=approx.fk(conbtrol0)
  File "E:/PycharmProjects/4dFaceOptimizerIK/approximation_v2.py", line 146, in fk
    final_refineMesh=self.sess.run([self.final_refineMesh])
  File "C:\Users\raphaelmeng\.conda\envs\fdfd\lib\site-packages\tensorflow\python\client\session.py", line 968, in run
    run_metadata_ptr)
  File "C:\Users\raphaelmeng\.conda\envs\fdfd\lib\site-packages\tensorflow\python\client\session.py", line 1191, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\raphaelmeng\.conda\envs\fdfd\lib\site-packages\tensorflow\python\client\session.py", line 1369, in _do_run
    run_metadata)
  File "C:\Users\raphaelmeng\.conda\envs\fdfd\lib\site-packages\tensorflow\python\client\session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
tensorflow.python.framework.errors_impl.FailedPreconditionError: 2 root error(s) found.
  (0) Failed precondition: Could not find variable Variable. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status=Not found: Resource localhost/Variable/class tensorflow::Var does not exist.
	 [[node image-0/GatherV2/ReadVariableOp (defined at E:\PycharmProjects\4dFaceOptimizerIK\cnnModel\cnnModel.py:98) ]]
	 [[strided_slice_54/_289]]
  (1) Failed precondition: Could not find variable Variable. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status=Not found: Resource localhost/Variable/class tensorflow::Var does not exist.
	 [[node image-0/GatherV2/ReadVariableOp (defined at E:\PycharmProjects\4dFaceOptimizerIK\cnnModel\cnnModel.py:98) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node image-0/GatherV2/ReadVariableOp:
 Variable (defined at E:/PycharmProjects/4dFaceOptimizerIK/approximation_v2.py:67)

Input Source operations connected to node image-0/GatherV2/ReadVariableOp:
 Variable (defined at E:/PycharmProjects/4dFaceOptimizerIK/approximation_v2.py:67)

Original stack trace for 'image-0/GatherV2/ReadVariableOp':
  File "E:/PycharmProjects/4dFaceOptimizerIK/approximation_v2.py", line 162, in <module>
    approx=Approximator(sess)
  File "E:/PycharmProjects/4dFaceOptimizerIK/approximation_v2.py", line 78, in __init__
    mesh = buildModel(baseConfig, rigControls)
  File "E:/PycharmProjects/4dFaceOptimizerIK/approximation_v2.py", line 58, in buildModel
    model = cnnModel.buildModel(data,dataset,neutral,config)
  File "E:\PycharmProjects\4dFaceOptimizerIK\cnnModel\cnnModel.py", line 98, in buildModel
    imageInput = tf.gather(pose,index,axis=1)
  File "C:\Users\raphaelmeng\.conda\envs\fdfd\lib\site-packages\tensorflow\python\util\deprecation.py", line 549, in new_func
    return func(*args, **kwargs)
  File "C:\Users\raphaelmeng\.conda\envs\fdfd\lib\site-packages\tensorflow\python\util\dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\raphaelmeng\.conda\envs\fdfd\lib\site-packages\tensorflow\python\ops\array_ops.py", line 5052, in gather
    params, indices, axis, batch_dims=batch_dims, name=name)
  File "C:\Users\raphaelmeng\.conda\envs\fdfd\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 3821, in gather_v2
    batch_dims=batch_dims, name=name)
  File "C:\Users\raphaelmeng\.conda\envs\fdfd\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 522, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "C:\Users\raphaelmeng\.conda\envs\fdfd\lib\site-packages\tensorflow\python\profiler\trace.py", line 163, in wrapped
    return func(*args, **kwargs)
  File "C:\Users\raphaelmeng\.conda\envs\fdfd\lib\site-packages\tensorflow\python\framework\ops.py", line 1566, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\raphaelmeng\.conda\envs\fdfd\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 2023, in _dense_var_to_tensor
    return var._dense_var_to_tensor(dtype=dtype, name=name, as_ref=as_ref)  # pylint: disable=protected-access
  File "C:\Users\raphaelmeng\.conda\envs\fdfd\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1421, in _dense_var_to_tensor
    return self.value()
  File "C:\Users\raphaelmeng\.conda\envs\fdfd\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 576, in value
    return self._read_variable_op()
  File "C:\Users\raphaelmeng\.conda\envs\fdfd\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 683, in _read_variable_op
    result = read_and_set_handle()
  File "C:\Users\raphaelmeng\.conda\envs\fdfd\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 674, in read_and_set_handle
    self.handle, self._dtype)
  File "C:\Users\raphaelmeng\.conda\envs\fdfd\lib\site-packages\tensorflow\python\ops\gen_resource_variable_ops.py", line 484, in read_variable_op
    "ReadVariableOp", resource=resource, dtype=dtype, name=name)
  File "C:\Users\raphaelmeng\.conda\envs\fdfd\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 750, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "C:\Users\raphaelmeng\.conda\envs\fdfd\lib\site-packages\tensorflow\python\framework\ops.py", line 3569, in _create_op_internal
    op_def=op_def)
  File "C:\Users\raphaelmeng\.conda\envs\fdfd\lib\site-packages\tensorflow\python\framework\ops.py", line 2045, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)


Process finished with exit code 1
```

### Standalone code to reproduce the issue

```shell
# Build the approximation model
import os
import pickle
import sys
from pathlib import Path

import numpy as np
import yaml
import tensorflow.compat.v1 as tf
from collections import namedtuple

sys.path.append(os.path.join('..','cnnModel'))
sys.path.append('..')
from cnnModel import cnnModel,rigidDeformer

def buildModel(config,pose,addNeutral=True):

    with open(config['data_params']['cache_file'],'rb') as file:
        data = pickle.load(file)
    cache = data
    parts = data['vCharts']
    faces = data['faces']
    neutral = data['neutral'][data['active']].astype('float32')
    uvs = data['uv']
    if 'parameter_mask' in data:
        mask = data['parameter_mask']
    else:
        mask = None

    # Create the model
    partCount = np.max(parts)+1
    data = {'pose':pose}
    usedVerts = []
    usedUVs = []
    for i in range(partCount):
        if np.sum(parts==i) > 0:
            data['image-'+str(i)] = tf.ones(1)
        else:
            data['image-'+str(i)] = None
        ref = faces.reshape(-1)
        idx = np.arange(len(neutral))[parts==i]
        if len(idx) == 0:
            continue
        usedFaces = [True if v in idx else False for v in ref]
        usedFaces = np.sum(np.asarray(usedFaces).reshape((-1,3)),-1) == 3
        faceIdx = np.arange(len(faces))[usedFaces]
        uv = uvs[idx]
        usedUVs.append(uv)
        usedVerts.append(idx)
    idx = np.concatenate(usedVerts)
    linear = np.zeros(neutral.shape,dtype='float32')
    if addNeutral:
        linear[idx] = neutral[idx]
    else:
        neutral = linear
    data['linear'] = linear
    dataset = namedtuple('Dataset','mask usedUVs usedVerts')(mask,usedUVs,usedVerts)
    model = cnnModel.buildModel(data,dataset,neutral,config)
    model['parts'] = parts
    model['cache'] = cache
    return model

class Approximator():

    def __init__(self,  sess):
        ####
        rigControls = tf.Variable(tf.zeros([1, 172], tf.float32))

        approximation_config = 'experiments/v00_refine_model_leaky.yaml'
        with open(approximation_config) as file:
            approximationConfig = yaml.load(file)
        with tf.variable_scope('refine'):
            refineMesh = buildModel(approximationConfig, rigControls, addNeutral=False)

        base_config = 'experiments/v00_base_model_leaky.yaml'
        with open(base_config) as file:
            baseConfig = yaml.load(file)
        mesh = buildModel(baseConfig, rigControls)

        have_refineMesh = True
        refineMesh['output'] = mesh['output'] + refineMesh['output']

        print(refineMesh['output'])
        print(type(refineMesh['output']))

        # Apply ridig deformer
        # Load info about the mesh
        with open(os.path.join(baseConfig['data_params']['cache_file']), 'rb') as file:
            data = pickle.load(file)
        parts = data['vCharts']
        neutral = data['neutral'][data['active']]
        print("data['neutral'].shape=", data['neutral'].shape)
        print('neutral.shape=', neutral.shape)
        faces = data['faces']
        mask = np.arange(len(parts))[parts > -1]

        if 'rigid_files' in baseConfig['data_params']:

            cur_rigidDeformer = rigidDeformer.RigidDeformer(neutral, [f for f in
                                                                      baseConfig['data_params']['rigid_files']], mask)
            final_base_mesh = cur_rigidDeformer.deformTF(mesh['output'][0])[np.newaxis]
            if have_refineMesh:
                final_refineMesh = cur_rigidDeformer.deformTF(refineMesh['output'][0])[np.newaxis]
        else:
            final_base_mesh = mesh['output']
            if have_refineMesh:
                final_refineMesh = refineMesh['output']

        # print('final_refineMesh.shape =', final_refineMesh.eval())
        print('type(final_refineMesh) =', type(final_refineMesh))

        ####
        vars = tf.trainable_variables()
        print(vars)
        vars_to_train = vars[0]
        vars_to_load = vars[1:]
        self.saver = tf.train.Saver(vars_to_load)

        checkpoint_dir = 'E:\\PycharmProjects\\FDFD-Metahuman-Y-up\\output\\v00_refine_model_leaky'
        self.checkpointFile = tf.train.latest_checkpoint(checkpoint_dir)
        self.saver.restore(sess, self.checkpointFile)

        self.rigControls=rigControls
        self.sess=sess
        self.final_refineMesh=final_refineMesh


    def fk(self,control):
        # vars = tf.trainable_variables()
        # print("after_vars =",vars)
        self.rigControls= control
        # print('self.rigControls=',self.rigControls)
        #
        # # init = tf.global_variables_initializer()
        # # self.sess.run(init)
        # vars = tf.trainable_variables()
        # print(vars)
        # vars_to_train = vars[0]
        # vars_to_load = vars[1:]
        # saver = tf.train.Saver(vars_to_load)
        #
        # checkpoint_dir = 'E:\\PycharmProjects\\FDFD-Metahuman-Y-up\\output\\v00_refine_model_leaky'
        # checkpointFile = tf.train.latest_checkpoint(checkpoint_dir)
        # saver.restore(sess, checkpointFile)

        final_refineMesh=self.sess.run([self.final_refineMesh])
        return final_refineMesh

    def ik(self,verts):
        pass








if __name__ == '__main__':
    # Load the model from file
    with tf.Session() as sess:
        approx=Approximator(sess)


        conbtrol0=tf.zeros([1, 172], tf.float32)
        verts0=approx.fk(conbtrol0)
        print('verts0=',verts0)

        conbtrol1 = tf.ones([1, 172], tf.float32)
        verts1 = approx.fk(conbtrol1)
        print('verts1=', verts1)
```

### Relevant log output

```shell
None
```
</details>

**Comment by mohantym** [comment]
Hi @MengHao666 !

Here is my observations from template. 
You should disable v2 behavior when using compat.v1 mode .  Python 3.7 is minimum version for 2.x versions now ( You are using Python 3.6). 
```
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
```
I was not able to replicate because of error at line. 

`from cnnModel import cnnModel,rigidDeformer .
`
Could you share the cnnModel script too.

Thank you!

**Comment by MengHao666** [comment]
> Hi @MengHao666 !
> 
> Here is my observations from template. You should disable v2 behavior when using compat.v1 mode . Python 3.7 is minimum version for 2.x versions now ( You are using Python 3.6).
> 
> ```
> import tensorflow.compat.v1 as tf
> tf.disable_v2_behavior()
> ```
> 
> I was not able to replicate because of error at line.
> 
> `from cnnModel import cnnModel,rigidDeformer . ` Could you share the cnnModel script too.
> 
> Thank you!


I did what you said but still suffer same problem. Could you focused on the main pipeline ? I just define a calss and initialize a object in which I make the compute graph by tensorflow. Then, I just want to use such model twice with **fk** function. However, the above error occured.

**Comment by mohantym** [comment]
Ok @MengHao666 !
Thanks for clarifying . Could you add below line before running the session.

`tf.initialize_all_variables().run()
`

[Reference.](https://stackoverflow.com/a/71568898/11530462)

Thank you!

**Comment by MengHao666** [comment]
> Ok @MengHao666 ! Thanks for clarifying . Could you add below line before running the session with TF 2.8/2.10 version.
> 
> `tf.initialize_all_variables().run() `
> 
> [Reference.](https://stackoverflow.com/a/71568898/11530462)
> 
> Thank you!

Thanks, the error is solved.
But, the variable **verts0** and **verts1** get the same value. It seems that the compute graph doesn't update the input value.  As the input are different,  **verts0** and **verts1** shoud have different values.

**Comment by mohantym** [comment]
Hi @MengHao666 !

conbtrol0 and  conbtrol1  has same value "tf.zeros([1, 172], tf.float32)", if you want to get  label the both output differently use name parameter or tf.name_scope.

Can we mark this issue as resolved now.

Thank you!

**Comment by MengHao666** [comment]
> Hi @MengHao666 !
> 
> conbtrol0 and conbtrol1 has same value "tf.zeros([1, 172], tf.float32)", if you want to get label the both output differently use name parameter or tf.name_scope.
> 
> Can we mark this issue as resolved now.
> 
> Thank you!

Sorry, i want to use the function **fk** serveral times and compute loss for every input in an iteration fashion. Does tf 1.x not support such operation?

**Comment by mohantym** [comment]
Ok @MengHao666 !
Thanks for the update.

@gadagashwini !
Could you look at this issue.

Thank you!

**Comment by gadagashwini** [comment]
Hi @MengHao666, I tried with sample code, its working as expected. I just replaced **fk** function with multiply function. 

```
import tensorflow as tf
conbtrol0=tf.zeros([1, 172], tf.float32)
verts0= tf.math.multiply(conbtrol0, conbtrol0)
print('verts0=',verts0)

conbtrol1 = tf.ones([1, 172], tf.float32)
verts1 = tf.math.multiply(conbtrol1, conbtrol1)
print('verts1=', verts1)
```

**Output**
```
verts0= tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]], shape=(1, 172), dtype=float32)
verts1= tf.Tensor(
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1.]], shape=(1, 172), dtype=float32)
```
