### ISSUE TITLE
No registered 'MatrixDeterminant' OpKernel for XLA_GPU_JIT devices

### ISSUE THREAD

**Issue by jxy** [tensorflow/tensorflow#57807]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

binary

### Tensorflow Version

v1.12.1-81213-g53844b49ea4 2.11.0-dev20220912

### Custom Code

No

### Current Behaviour?

```shell
>>> tf.function(tf.linalg.det,jit_compile=True).get_concrete_function(tf.constant([[1,0],[0,1]],dtype=tf.float32))(tf.constant([[1,0],[0,1]],dtype=tf.float32))
2022-09-22 20:11:03.425889: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:327 : INVALID_ARGUMENT: Detected unsupported operations when trying to compile graph __inference_matrix_determinant_26[_XlaMustCompile=true,config_proto=6001324581131673121,executor_type=11160318154034397263] on XLA_GPU_JIT: MatrixDeterminant (No registered 'MatrixDeterminant' OpKernel for XLA_GPU_JIT devices compatible with node {{node MatrixDeterminant}}){{node MatrixDeterminant}}
The op is created at: 
File "<stdin>", line 1, in <module>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/gpfs/jlse-fs0/users/xjin/gpu/pyvenv_nightly/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/monomorphic_function.py", line 1473, in __call__
    return self._call_impl(args, kwargs)
  File "/gpfs/jlse-fs0/users/xjin/gpu/pyvenv_nightly/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/monomorphic_function.py", line 1482, in _call_impl
    return self._call_with_structured_signature(args, kwargs,
  File "/gpfs/jlse-fs0/users/xjin/gpu/pyvenv_nightly/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/monomorphic_function.py", line 1563, in _call_with_structured_signature
    return self._call_flat(
  File "/gpfs/jlse-fs0/users/xjin/gpu/pyvenv_nightly/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/monomorphic_function.py", line 1744, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/gpfs/jlse-fs0/users/xjin/gpu/pyvenv_nightly/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/monomorphic_function.py", line 377, in call
    outputs = execute.execute(
  File "/gpfs/jlse-fs0/users/xjin/gpu/pyvenv_nightly/lib/python3.10/site-packages/tensorflow/python/eager/execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Detected unsupported operations when trying to compile graph __inference_matrix_determinant_26[_XlaMustCompile=true,config_proto=6001324581131673121,executor_type=11160318154034397263] on XLA_GPU_JIT: MatrixDeterminant (No registered 'MatrixDeterminant' OpKernel for XLA_GPU_JIT devices compatible with node {{node MatrixDeterminant}}){{node MatrixDeterminant}}
The op is created at: 
File "<stdin>", line 1, in <module> [Op:__inference_matrix_determinant_26]
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
@tf.function(jit_compile=True)
def f(x):
    return tf.linalg.det(x)
tf.print(f(tf.constant([[1,0],[0,1]],dtype=tf.float32)))
```

### Relevant log output

_No response_</details>

**Comment by jxy** [comment]
As a workaround, `tf.linalg.logdet` uses cholesky, which works in XLA.

**Comment by mohantym** [comment]
Hi @gadagashwini !
Could you look at this feature request.
Thank you!

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
