### ISSUE TITLE
Asset file vanishes after loading & saving the model twice

### ISSUE THREAD

**Issue by supercharleszhu** [tensorflow/tensorflow#57806]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.4

### Custom Code

No

### OS Platform and Distribution

Linux

### Python version

3.8

### Current Behaviour?

When I created the tf.Module with an asset file inside the TextFileInitializer, and save & load the module twice, the asset file will vanish after the 2nd save, and the loading will fail, complaining the absolute path of that file cannot be found. 

```
import shutil
import tensorflow as tf


class PrimaryModule(tf.Module):
    def __init__(self, name=None):
        super(PrimaryModule, self).__init__(name=name)
        initializer = tf.lookup.TextFileInitializer(
            "chzhu_vocab.txt",
            key_dtype=tf.int64,
            key_index=0,
            value_dtype=tf.int64,
            value_index=1,
            delimiter=" ",
        )
        self.table = tf.lookup.StaticVocabularyTable(initializer, 1)

    @tf.function
    def __call__(self, inputs):
        return self.table.lookup(inputs)


model = PrimaryModule()
print(model(tf.constant([509323409], dtype=tf.int64)))
tf.saved_model.save(model, "asset_model")
imported_new = tf.saved_model.load("asset_model")
print(imported_new(tf.constant([509323409], dtype=tf.int64)))
tf.saved_model.save(imported_new, "wrapped_assets_model")

# Error when loading the model for the second time, it will be trying to find the original path
# instead of path in the asset folder inside model
shutil.rmtree("asset_model")
shutil.rm("chzhu_vocab.txt")
tf.saved_model.load("wrapped_assets_model")

```
Error: see full stack trace below 
```
FileNotFoundError:  chzhu_vocab.txt; No such file or directory
```

When changing `initializer` to be `self.initializer` in the object constructor, it will work as normal
```
import tensorflow as tf

class PrimaryModule(tf.Module):
    def __init__(self, name=None):
        super(PrimaryModule, self).__init__(name=name)
        self.initializer = tf.lookup.TextFileInitializer(
            "chzhu_vocab.txt",
            key_dtype=tf.int64,
            key_index=0,
            value_dtype=tf.int64,
            value_index=1,
            delimiter=" ",
        )
        self.table = tf.lookup.StaticVocabularyTable(self.initializer, 1)

    @tf.function
    def __call__(self, inputs):
        return self.table.lookup(inputs)

# ..same saving logics

```

I did a deep dive into the model saving logic in TF 2.4, and found the difference here:

When saving the model for the first time, the model saver will save the object dependencies into the SavedObjectGraph:

object_graph_def in the meta_graph_def:
```
object_graph_def {
  nodes {
    children {
      node_id: 1
      local_name: "table"
    }
    children {
      node_id: 2
      local_name: "signatures"
    }
    children {
      node_id: 5
      local_name: "__call__"
    }
    user_object {
      identifier: "_generic_user_object"
      version {
        producer: 1
        min_consumer: 1
      }
    }
  }
  nodes {
    children {
      node_id: 3
      local_name: "_initializer"
    }
    children {
      node_id: 6
      local_name: "_create_resource"
    }
    children {
      node_id: 7
      local_name: "_initialize"
    }
    children {
      node_id: 8
      local_name: "_destroy_resource"
    }
    resource {
    }
  }
…
```

As we can see above, `_initializer` is not the attribute of the top-level object and is the child of `VocabularyTable`, which is a resource object. The dependency will look like object -> table -> initializer -> Asset.

During the first time loading

* The Loader will try to recreate all the objects in the SavedObjectGraph, 

* The resource object will be recreated as _RestoredResource, which inherits the base.Trackable (not AutoTrackable). 

* When calling `_setattr_` in the _add_object_graph_edges(), it will not update _checkpoint_dependencies (unlike normal object inheriting AutoTrackable, which override the _setattr_ function to update the attribute dependencies.) Therefore, the table -> initializer -> Asset dependency is not entirely recovered.

During the second time saving, it will 

* find out the Asset objects in the object dependencies via Breadth First Traversal, and add that into asset_info. 

* in the _fill_meta_graph_def(), we will create asset_initializer_ops for all Assets in asset_info.

* in the _fill_meta_graph_def(), the asset_initializer and its downstream variables will be written into init_ops, and the main graph will be updated to initialize the variable from the corresponding asset_initializer.

However, since in the previous loading stage, the _checkpoint_dependencies will be empty for the “table” attribute, and we cannot access the Asset object via Breadth First Traversal of the object graph. Thus we are getting empty asset_info, and 2, and 3 above will not happen.

### Standalone code to reproduce the issue

```shell
import shutil
import tensorflow as tf


class PrimaryModule(tf.Module):
    def __init__(self, name=None):
        super(PrimaryModule, self).__init__(name=name)
        initializer = tf.lookup.TextFileInitializer(
            "chzhu_vocab.txt",
            key_dtype=tf.int64,
            key_index=0,
            value_dtype=tf.int64,
            value_index=1,
            delimiter=" ",
        )
        self.table = tf.lookup.StaticVocabularyTable(initializer, 1)

    @tf.function
    def __call__(self, inputs):
        return self.table.lookup(inputs)


model = PrimaryModule()
print(model(tf.constant([509323409], dtype=tf.int64)))
tf.saved_model.save(model, "asset_model")
imported_new = tf.saved_model.load("asset_model")
print(imported_new(tf.constant([509323409], dtype=tf.int64)))
tf.saved_model.save(imported_new, "wrapped_assets_model")

# Error when loading the model for the second time
shutil.rmtree("asset_model")
tf.saved_model.load("wrapped_assets_model")
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/chzhu/tf2-trainer/tf2-trainer-component-training/test/asset_testing.py", line 32, in <module>
    tf.saved_model.load("custom_model/wrapped_assets_model")
  File "/home/chzhu/tf2-trainer/build/tf2-trainer-component-training/environments/development-venv/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 859, in load
    return load_internal(export_dir, tags, options)["root"]
  File "/home/chzhu/tf2-trainer/build/tf2-trainer-component-training/environments/development-venv/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 893, in load_internal
    str(err) + "\n If trying to load on a different device from the "
FileNotFoundError:  custom_model/asset_model/assets/chzhu_vocab.txt; No such file or directory
         [[{{node StatefulPartitionedCall/text_file_init/InitializeTableFromTextFileV2}}]] [Op:__inference_restored_function_body_375]
```
</details>

**Comment by supercharleszhu** [comment]
Seems that it is fixed in this commit 
https://github.com/tensorflow/tensorflow/commit/59e882af21831eea9e24d74c9af4242cc1514c6e

Verified that it works in TF 2.9. Closing the issue.
