### ISSUE TITLE
Cannot set inter/intra_op_parallelism_threads after tfds.load

### ISSUE THREAD

**Issue by yangw1234** [tensorflow/tensorflow#57812]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.8

### Custom Code

Yes

### Current Behaviour?

```shell
Cannot set inter/intra_op_parallelism_threads after running tfds.load. Error message is "RuntimeError: Inter op parallelism cannot be modified after initialization."
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import tensorflow_datasets as tfds

(train_ds, test_ds), info = tfds.load('mnist',
                                      data_dir='/tmp/data',
                                      split=['train', 'test'],
                                      with_info=True,
                                      as_supervised=True)

print(tf.config.threading.get_inter_op_parallelism_threads()) # returns 0
tf.config.threading.set_inter_op_parallelism_threads(1)
```
```


### Relevant log output

```shell
WARNING:absl:Found a different version 3.0.1 of dataset mnist in data_dir /tmp/data. Using currently defined version 3.0.0.
2022-09-22 14:02:51.738490: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-09-22 14:02:51.738942: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
WARNING:absl:options.experimental_threading is deprecated. Use options.threading instead.
WARNING:absl:options.experimental_threading is deprecated. Use options.threading instead.
WARNING:absl:options.experimental_threading is deprecated. Use options.threading instead.
WARNING:absl:options.experimental_threading is deprecated. Use options.threading instead.
0
Traceback (most recent call last):
  File "tf_test.py", line 11, in <module>
    tf.config.threading.set_inter_op_parallelism_threads(1)
  File "/home/yang/miniconda3/envs/nano-dev/lib/python3.7/site-packages/tensorflow/python/framework/config.py", line 144, in set_inter_op_parallelism_threads
    context.context().inter_op_parallelism_threads = num_threads
  File "/home/yang/miniconda3/envs/nano-dev/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 1842, in inter_op_parallelism_threads
    "Inter op parallelism cannot be modified after initialization.")
RuntimeError: Inter op parallelism cannot be modified after initialization.
```
</details>

**Comment by tilakrayal** [comment]
@yangw1234,
Could you expose some init() or something method as part of Transform that users should run in the beginning of their program which can set up these kinds of configurations.

Also please take a look at this [comment](https://github.com/tensorflow/tensorflow/issues/51832#issuecomment-1158431103) from the developer and the SO [link](https://stackoverflow.com/questions/59616436/how-to-reset-initialization-in-tensorflow-2) with the similar error. Thank you!
