### ISSUE TITLE
Tensorflow nor working in rasperrypi 4

### ISSUE THREAD

**Issue by JIBYMARIYAJOSE** [tensorflow/tensorflow#57856]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

binary

### Tensorflow Version

2.4.0

### Custom Code

Yes

### OS Platform and Distribution

Rasbian os

### Mobile device

Ubuntu 18.04

### Python version

3.9

### Current Behaviour?

```shell
Tensorflow not getting installed with rasbian os 32 bit ,rasperrypi4- tried to install tensorflow using .whl, virtual environment, git clone but still not able install/import .please help.
```

### Standalone code to reproduce the issue

```shell
ImportError                               Traceback (most recent call last)
File ~/.local/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow.py:58
     56   sys.setdlopenflags(_default_dlopen_flags | ctypes.RTLD_LOCAL)
---> 58 from tensorflow.python.pywrap_tensorflow_internal import *
     59 from tensorflow.python.pywrap_tensorflow_internal import __version__

File ~/.local/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow_internal.py:28
     27         return _mod
---> 28 _pywrap_tensorflow_internal = swig_import_helper()
     29 del swig_import_helper

File ~/.local/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow_internal.py:24, in swig_import_helper()
     23 try:
---> 24     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     25 finally:

File /usr/lib/python3.9/imp.py:242, in load_module(name, file, filename, details)
    241     else:
--> 242         return load_dynamic(name, filename, file)
    243 elif type_ == PKG_DIRECTORY:

File /usr/lib/python3.9/imp.py:342, in load_dynamic(name, path, file)
    340 spec = importlib.machinery.ModuleSpec(
    341     name=name, loader=loader, origin=path)
--> 342 return _load(spec)

ImportError: /home/pi/.local/lib/python3.9/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: invalid ELF header

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
File <timed exec>:21

File ~/.local/lib/python3.9/site-packages/tensorflow/__init__.py:24
     21 import os as _os
     23 # pylint: disable=g-bad-import-order
---> 24 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     26 try:
     27   # Add `estimator` attribute to allow access to estimator APIs via
     28   # "tf.estimator..."
     29   from tensorflow.python.estimator.api import estimator  # pylint: disable=g-import-not-at-top

File ~/.local/lib/python3.9/site-packages/tensorflow/python/__init__.py:49
     32 # TODO(drpng): write up instructions for editing this file in a doc and point to
     33 # the doc instead.
     34 # If you want to edit this file to expose modules in public tensorflow API, you
   (...)
     44 # go/tf-wildcard-import
     45 # pylint: disable=wildcard-import,g-bad-import-order,g-import-not-at-top
     47 import numpy as np
---> 49 from tensorflow.python import pywrap_tensorflow
     51 from tensorflow.python.tools import component_api_helper
     52 component_api_helper.package_hook(
     53     parent_package_str='tensorflow.python',
     54     child_package_str=(
     55         'tensorflow_estimator.python.estimator'))

File ~/.local/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow.py:74
     69 except ImportError:
     70   msg = """%s\n\nFailed to load the native TensorFlow runtime.\n
     71 See https://www.tensorflow.org/install/errors\n
     72 for some common reasons and solutions.  Include the entire stack trace
     73 above this error message when asking for help.""" % traceback.format_exc()
---> 74   raise ImportError(msg)

ImportError: Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/pi/.local/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/pi/.local/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.9/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.9/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/pi/.local/lib/python3.9/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: invalid ELF header
```

### Relevant log output

```shell
ImportError                               Traceback (most recent call last)
File ~/.local/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow.py:58
     56   sys.setdlopenflags(_default_dlopen_flags | ctypes.RTLD_LOCAL)
---> 58 from tensorflow.python.pywrap_tensorflow_internal import *
     59 from tensorflow.python.pywrap_tensorflow_internal import __version__

File ~/.local/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow_internal.py:28
     27         return _mod
---> 28 _pywrap_tensorflow_internal = swig_import_helper()
     29 del swig_import_helper

File ~/.local/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow_internal.py:24, in swig_import_helper()
     23 try:
---> 24     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     25 finally:

File /usr/lib/python3.9/imp.py:242, in load_module(name, file, filename, details)
    241     else:
--> 242         return load_dynamic(name, filename, file)
    243 elif type_ == PKG_DIRECTORY:

File /usr/lib/python3.9/imp.py:342, in load_dynamic(name, path, file)
    340 spec = importlib.machinery.ModuleSpec(
    341     name=name, loader=loader, origin=path)
--> 342 return _load(spec)

ImportError: /home/pi/.local/lib/python3.9/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: invalid ELF header

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
File <timed exec>:21

File ~/.local/lib/python3.9/site-packages/tensorflow/__init__.py:24
     21 import os as _os
     23 # pylint: disable=g-bad-import-order
---> 24 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     26 try:
     27   # Add `estimator` attribute to allow access to estimator APIs via
     28   # "tf.estimator..."
     29   from tensorflow.python.estimator.api import estimator  # pylint: disable=g-import-not-at-top

File ~/.local/lib/python3.9/site-packages/tensorflow/python/__init__.py:49
     32 # TODO(drpng): write up instructions for editing this file in a doc and point to
     33 # the doc instead.
     34 # If you want to edit this file to expose modules in public tensorflow API, you
   (...)
     44 # go/tf-wildcard-import
     45 # pylint: disable=wildcard-import,g-bad-import-order,g-import-not-at-top
     47 import numpy as np
---> 49 from tensorflow.python import pywrap_tensorflow
     51 from tensorflow.python.tools import component_api_helper
     52 component_api_helper.package_hook(
     53     parent_package_str='tensorflow.python',
     54     child_package_str=(
     55         'tensorflow_estimator.python.estimator'))

File ~/.local/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow.py:74
     69 except ImportError:
     70   msg = """%s\n\nFailed to load the native TensorFlow runtime.\n
     71 See https://www.tensorflow.org/install/errors\n
     72 for some common reasons and solutions.  Include the entire stack trace
     73 above this error message when asking for help.""" % traceback.format_exc()
---> 74   raise ImportError(msg)

ImportError: Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/pi/.local/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/pi/.local/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.9/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.9/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/pi/.local/lib/python3.9/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: invalid ELF header
```
</details>

**Comment by JIBYMARIYAJOSE** [comment]
I tried the first option using  tflite.but not working. Showing the
same error.

**Comment by mohantym** [comment]
Ok @JIBYMARIYAJOSE !
Thanks for the update .
Could you test with instruction from Option 2 (Pinto0's wheels) or [ TFlite-run time ](https://www.tensorflow.org/lite/guide/python)document.

Thank you!

**Comment by JIBYMARIYAJOSE** [comment]
I have tried with pintoo whl files but failed with same error

**Comment by mohantym** [comment]
Ok @JIBYMARIYAJOSE !
Thanks for sharing your results. ( Sounds a bit surprising though). 

@sachinprasadhs !
Could you look at this issue.

Thank you!

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
