### ISSUE TITLE
Import error Mac M1 

### ISSUE THREAD

**Issue by BenjaminDEMAILLE** [tensorflow/tensorflow#57933]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

TensorFlow-macos 

### Custom Code

No

### OS Platform and Distribution

macOS Monterey 

### Python version

3.10.6

### Current Behaviour?

```shell
see below
```

### Standalone code to reproduce the issue

```shell
3.10.6 (main, Aug 30 2022, 04:58:14) [Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.10/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/opt/homebrew/lib/python3.10/site-packages/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "/opt/homebrew/lib/python3.10/site-packages/tensorflow/python/eager/context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "/opt/homebrew/lib/python3.10/site-packages/tensorflow/core/framework/function_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/opt/homebrew/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: dlopen(/opt/homebrew/lib/python3.10/site-packages/google/protobuf/pyext/_message.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace (__ZNK6google8protobuf10TextFormat21FastFieldValuePrinter19PrintMessageContentERKNS0_7MessageEiibPNS1_17BaseTextGeneratorE)
```

### Relevant log output

```shell
No
```
</details>

**Comment by tilakrayal** [comment]
@BenjaminDEMAILLE,
Could you please take a look at the https://github.com/tensorflow/tensorflow/issues/57185#issuecomment-1219698610 from the developer for the similar issue while installing the Tensorflow on Apple M1. Thank you!
