### ISSUE TITLE
Error loading fashion_mnist dataset

### ISSUE THREAD

**Issue by Urkchar** [tensorflow/tensorflow#57945]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.10

### Custom Code

Yes

### OS Platform and Distribution

Microsoft Windows 10 Home ersion 10.0.19043 Build 19043

### Python version

3.9

### CUDA/cuDNN version

CUDA-11.2.2 cuDNN-8.1.0.77

### GPU model and memory

GeForce GTX 1070

### Current Behaviour?

```shell
I expected to be able to load the `fashion_mnist` data. This might be an issue with converting `:` to `%3A` in the urls on `fashion_mnist.py`.
Here is the code from `fashion_mnist.py` that I think is relevant.

    dirname = os.path.join("datasets", "fashion-mnist")
    base = "https://storage.googleapis.com/tensorflow/tf-keras-datasets/"
    files = [
        "train-labels-idx1-ubyte.gz",
        "train-images-idx3-ubyte.gz",
        "t10k-labels-idx1-ubyte.gz",
        "t10k-images-idx3-ubyte.gz",
    ]

    paths = []
    for fname in files:
        paths.append(get_file(fname, origin=base + fname, cache_subdir=dirname))

As you can see, `base` and `fname` are getting combined using string concatenation instead of something like urljoin. 
Relevant stackoverflow question: https://stackoverflow.com/questions/27115803/urllib-error-urlerror-urlopen-error-unknown-url-type-https
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
fashion_mnist = tf.keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()
```

### Relevant log output

```shell
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/train-labels-idx1-ubyte.gz
Traceback (most recent call last):
  File "C:\Users\urkch\miniconda3\envs\tf\lib\site-packages\keras\utils\data_utils.py", line 296, in get_file
    urlretrieve(origin, fpath, DLProgbar())
  File "C:\Users\urkch\miniconda3\envs\tf\lib\site-packages\keras\utils\data_utils.py", line 84, in urlretrieve
    response = urlopen(url, data)
  File "C:\Users\urkch\miniconda3\envs\tf\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\urkch\miniconda3\envs\tf\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "C:\Users\urkch\miniconda3\envs\tf\lib\urllib\request.py", line 539, in _open
    return self._call_chain(self.handle_open, 'unknown',
  File "C:\Users\urkch\miniconda3\envs\tf\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\urkch\miniconda3\envs\tf\lib\urllib\request.py", line 1417, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\urkch\AppData\Local\Programs\Python\Python_Projects\tensorflow\Basic classification Classify images of clothing\classify.py", line 12, in <module>
    (train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()
  File "C:\Users\urkch\miniconda3\envs\tf\lib\site-packages\keras\datasets\fashion_mnist.py", line 93, in load_data
    paths.append(get_file(fname, origin=base + fname, cache_subdir=dirname))
  File "C:\Users\urkch\miniconda3\envs\tf\lib\site-packages\keras\utils\data_utils.py", line 300, in get_file
    raise Exception(error_msg.format(origin, e.errno, e.reason))
Exception: URL fetch failure on https://storage.googleapis.com/tensorflow/tf-keras-datasets/train-labels-idx1-ubyte.gz: None -- unknown url type: https
```
</details>

**Comment by sushreebarsa** [comment]
@Urkchar I was able to execute the provided code in colab, could you please have a look at the [gist](https://colab.research.google.com/gist/sushreebarsa/119fff0ebfbfbe78ee23129c1c79c11f/57945.ipynb) here and confirm the same?
Thank you!

**Comment by Urkchar** [comment]
I can confirm that gist you provided works. What next?

**Comment by Urkchar** [comment]
Installing `openssl` in my conda environment solved this issue.

**Comment by Urkchar** [comment]
It seems like my installation of openssl was faulty or something. Installing it again seemed to fix it.
