### ISSUE TITLE
Build Failed   for CUDA 11.7 

### ISSUE THREAD

**Issue by cosmic-blunder** [tensorflow/tensorflow#57941]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2

### Custom Code

No

### OS Platform and Distribution

Linux mint 21

### Python version

3.10

### Bazel version

3.1.0

### GCC/Compiler version

Ubuntu clang version 14.0.0-1ubuntu1 Target: x86_64-pc-linux-gnu Thread model: posix InstalledDir: /usr/bin

### CUDA/cuDNN version

11.7/8.5

### GPU model and memory

RTX 3050 Ti

### Current Behaviour?

```shell
WARNING: The following configs were expanded more than once: [cuda_clang, using_cuda, v2]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=238
INFO: Reading rc options for 'build' from /home/dlock/deepSpeech-proj/DeepSpeech/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/dlock/deepSpeech-proj/DeepSpeech/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --copt=-DTFLITE_WITH_RUY_GEMV --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=v2
INFO: Reading rc options for 'build' from /home/dlock/deepSpeech-proj/DeepSpeech/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/home/dlock/anaconda3/bin/python3 --action_env PYTHON_LIB_PATH=/home/dlock/anaconda3/lib/python3.9/site-packages --python_path=/home/dlock/anaconda3/bin/python3 --config=xla --action_env CUDA_TOOLKIT_PATH=/usr/local/cuda-11.7 --action_env TF_CUDA_COMPUTE_CAPABILITIES=8.6 --action_env LD_LIBRARY_PATH=/usr/local/cuda-11.7/lib64: --config=cuda_clang --action_env CLANG_CUDA_COMPILER_PATH=/usr/bin/clang --config=cuda_clang --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:v2 in file /home/dlock/deepSpeech-proj/DeepSpeech/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file /home/dlock/deepSpeech-proj/DeepSpeech/tensorflow/.bazelrc: --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true
INFO: Found applicable config definition build:cuda_clang in file /home/dlock/deepSpeech-proj/DeepSpeech/tensorflow/.bazelrc: --config=using_cuda --define=using_cuda_clang=true --define=using_clang=true --action_env TF_CUDA_CLANG=1
INFO: Found applicable config definition build:using_cuda in file /home/dlock/deepSpeech-proj/DeepSpeech/tensorflow/.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain
INFO: Found applicable config definition build:cuda_clang in file /home/dlock/deepSpeech-proj/DeepSpeech/tensorflow/.bazelrc: --config=using_cuda --define=using_cuda_clang=true --define=using_clang=true --action_env TF_CUDA_CLANG=1
INFO: Found applicable config definition build:using_cuda in file /home/dlock/deepSpeech-proj/DeepSpeech/tensorflow/.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain
INFO: Found applicable config definition build:opt in file /home/dlock/deepSpeech-proj/DeepSpeech/tensorflow/.tf_configure.bazelrc: --copt=-march=native --copt=-Wno-sign-compare --host_copt=-march=native --define with_default_optimizations=true
INFO: Found applicable config definition build:cuda in file /home/dlock/deepSpeech-proj/DeepSpeech/tensorflow/.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file /home/dlock/deepSpeech-proj/DeepSpeech/tensorflow/.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain
INFO: Found applicable config definition build:v2 in file /home/dlock/deepSpeech-proj/DeepSpeech/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:linux in file /home/dlock/deepSpeech-proj/DeepSpeech/tensorflow/.bazelrc: --copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
INFO: Found applicable config definition build:dynamic_kernels in file /home/dlock/deepSpeech-proj/DeepSpeech/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
INFO: Repository local_config_cuda instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule cuda_configure defined at:
  /home/dlock/deepSpeech-proj/DeepSpeech/tensorflow/third_party/gpus/cuda_configure.bzl:1399:18: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
	File "/home/dlock/deepSpeech-proj/DeepSpeech/tensorflow/third_party/gpus/cuda_configure.bzl", line 1369
		_create_local_cuda_repository(<1 more arguments>)
	File "/home/dlock/deepSpeech-proj/DeepSpeech/tensorflow/third_party/gpus/cuda_configure.bzl", line 1051, in _create_local_cuda_repository
		_find_libs(repository_ctx, <2 more arguments>)
	File "/home/dlock/deepSpeech-proj/DeepSpeech/tensorflow/third_party/gpus/cuda_configure.bzl", line 598, in _find_libs
		_check_cuda_libs(repository_ctx, <2 more arguments>)
	File "/home/dlock/deepSpeech-proj/DeepSpeech/tensorflow/third_party/gpus/cuda_configure.bzl", line 500, in _check_cuda_libs
		execute(repository_ctx, <1 more arguments>)
	File "/home/dlock/deepSpeech-proj/DeepSpeech/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
		fail(<1 more arguments>)
Repository command failed
Expected even number of arguments
INFO: Repository rules_cc instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule tf_http_archive defined at:
  /home/dlock/deepSpeech-proj/DeepSpeech/tensorflow/third_party/repo.bzl:136:19: in <toplevel>
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/dlock/deepSpeech-proj/DeepSpeech/tensorflow/third_party/gpus/cuda_configure.bzl", line 1369
		_create_local_cuda_repository(<1 more arguments>)
	File "/home/dlock/deepSpeech-proj/DeepSpeech/tensorflow/third_party/gpus/cuda_configure.bzl", line 1051, in _create_local_cuda_repository
		_find_libs(repository_ctx, <2 more arguments>)
	File "/home/dlock/deepSpeech-proj/DeepSpeech/tensorflow/third_party/gpus/cuda_configure.bzl", line 598, in _find_libs
		_check_cuda_libs(repository_ctx, <2 more arguments>)
	File "/home/dlock/deepSpeech-proj/DeepSpeech/tensorflow/third_party/gpus/cuda_configure.bzl", line 500, in _check_cuda_libs
		execute(repository_ctx, <1 more arguments>)
	File "/home/dlock/deepSpeech-proj/DeepSpeech/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
		fail(<1 more arguments>)
Repository command failed
Expected even number of arguments
WARNING: Target pattern parsing failed.
ERROR: no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/dlock/deepSpeech-proj/DeepSpeech/tensorflow/third_party/gpus/cuda_configure.bzl", line 1369
		_create_local_cuda_repository(<1 more arguments>)
	File "/home/dlock/deepSpeech-proj/DeepSpeech/tensorflow/third_party/gpus/cuda_configure.bzl", line 1051, in _create_local_cuda_repository
		_find_libs(repository_ctx, <2 more arguments>)
	File "/home/dlock/deepSpeech-proj/DeepSpeech/tensorflow/third_party/gpus/cuda_configure.bzl", line 598, in _find_libs
		_check_cuda_libs(repository_ctx, <2 more arguments>)
	File "/home/dlock/deepSpeech-proj/DeepSpeech/tensorflow/third_party/gpus/cuda_configure.bzl", line 500, in _check_cuda_libs
		execute(repository_ctx, <1 more arguments>)
	File "/home/dlock/deepSpeech-proj/DeepSpeech/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
		fail(<1 more arguments>)
Repository command failed
Expected even number of arguments
INFO: Elapsed time: 0.363s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package
```

### Standalone code to reproduce the issue

```shell
azel build --config=opt --config=cuda --config=v2 //tensorflow/tools/pip_package:build_pip_package
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@cosmic-blunder Could you please make sure to follow the instructions mentioned [here](https://www.tensorflow.org/install/source) and check the tested build configuration as well. Please let us know if it helps?
Thank you!
