### ISSUE TITLE
Tensorflow Build Fail with `config=asan/msan/ubsan`

### ISSUE THREAD

**Issue by Kristoff-starling** [tensorflow/tensorflow#58013]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

tf 2.10

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.8.13

### Bazel version

5.3.0

### GCC/Compiler version

9.4.0

### Current Behaviour?

```shell
TensorFlow cannot be successfully built from source with address/memory/undefined
behavior sanitizers.
```

### Standalone code to reproduce the issue

```shell
bazel build --config=asan //tensorflow/tools/pip_package:build_pip_package
bazel build --config=msan //tensorflow/tools/pip_package:build_pip_package
bazel build --config=ubsan //tensorflow/tools/pip_package:build_pip_package
```

### Relevant log output

```shell
For ubsan, the building gets stuck at linking:
[12,750 / 12,808] .../python:_pywrap_tensorflow_internal.so; 15247s local  // cannot terminate

For asan/msan, the building fails with the following message:
ERROR: /home/yuyao/.cache/bazel/_bazel_yuyao/ccc1279be1ec9be064e98d7fead8e6f8/external/libjpeg_turbo/BUILD.bazel:227:8: Executing genrule @libjpeg_turbo//:simd_x86_64_assemblage23 failed: (Exit 1): bash failed: error executing command 
  (cd /home/yuyao/.cache/bazel/_bazel_yuyao/ccc1279be1ec9be064e98d7fead8e6f8/execroot/org_tensorflow && \
  exec env - \
    PATH=/home/yuyao/.cache/bazelisk/downloads/bazelbuild/bazel-5.3.0-linux-x86_64/bin:/home/yuyao/.local/bin:/usr/local/cuda/compute-sanitizer:/usr/local/cuda/bin:/home/yuyao/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/bin/remote-cli:/home/yuyao/.conda/envs/ten-sanitizer/bin:/opt/miniconda3/condabin:/home/yuyao/.local/bin:/usr/local/cuda/compute-sanitizer:/usr/local/cuda/bin:/opt/miniconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
    PYTHON_BIN_PATH=/opt/miniconda3/bin/python3 \
    PYTHON_LIB_PATH=/opt/miniconda3/lib/python3.8/site-packages \
    TF2_BEHAVIOR=1 \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; for out in bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jccolor-avx2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jccolor-sse2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jcgray-avx2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jcgray-sse2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jchuff-sse2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jcphuff-sse2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jcsample-avx2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jcsample-sse2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jdcolor-avx2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jdcolor-sse2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jdmerge-avx2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jdmerge-sse2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jdsample-avx2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jdsample-sse2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jfdctflt-sse.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jfdctfst-sse2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jfdctint-avx2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jfdctint-sse2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jidctflt-sse2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jidctfst-sse2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jidctint-avx2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jidctint-sse2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jidctred-sse2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jquantf-sse2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jquanti-avx2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jquanti-sse2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jsimdcpu.o; do
  bazel-out/k8-opt/bin/external/nasm/nasm -f elf64    -DELF -DPIC -D__x86_64__    -I $(dirname bazel-out/k8-opt/bin/external/libjpeg_turbo/jconfig.h)/    -I $(dirname bazel-out/k8-opt/bin/external/libjpeg_turbo/jconfigint.h)/    -I $(dirname external/libjpeg_turbo/simd/nasm/jsimdcfg.inc.h)/    -I $(dirname external/libjpeg_turbo/simd/x86_64/jccolext-sse2.asm)/    -o $out    $(dirname external/libjpeg_turbo/simd/x86_64/jccolext-sse2.asm)/$(basename ${out%.o}.asm)
done')
# Configuration: 014280d9fadad28e5975c79178a18398bf834eb4a872c13f9a858491aca2ea7f
# Execution platform: @local_execution_config_platform//:platform

=================================================================
==3375800==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 14584 byte(s) in 360 object(s) allocated from:
    #0 0x7fc521520808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x56236ccd4a17 in nasm_malloc external/nasm/nasmlib/malloc.c:75
    #2 0x56236ccd4a17 in nasm_strcat external/nasm/nasmlib/malloc.c:123
    #3 0x56236cc7505a in find_label external/nasm/asm/labels.c:227
    #4 0x56236cc7535c in is_extern external/nasm/asm/labels.c:285
    #5 0x56236cc6ba70 in expr6 external/nasm/asm/eval.c:937
    #6 0x56236cc6be81 in expr5 external/nasm/asm/eval.c:567
    #7 0x56236cc6cf94 in expr4 external/nasm/asm/eval.c:542
    #8 0x56236cc6d107 in expr3 external/nasm/asm/eval.c:508
    #9 0x56236cc6d577 in expr2 external/nasm/asm/eval.c:482
    #10 0x56236cc6da47 in expr1 external/nasm/asm/eval.c:456
    #11 0x56236cc6df1b in expr0 external/nasm/asm/eval.c:430
    #12 0x56236cc6fa3c in evaluate external/nasm/asm/eval.c:988
    #13 0x56236cc7acf8 in parse_line external/nasm/asm/parser.c:879
    #14 0x56236cc54c8a in assemble_file external/nasm/asm/nasm.c:1502
    #15 0x56236cc527c8 in main external/nasm/asm/nasm.c:617
    #16 0x7fc520f14082 in __libc_start_main ../csu/libc-start.c:308

Direct leak of 14584 byte(s) in 360 object(s) allocated from:
    #0 0x7fc521520808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x56236ccd4a17 in nasm_malloc external/nasm/nasmlib/malloc.c:75
    #2 0x56236ccd4a17 in nasm_strcat external/nasm/nasmlib/malloc.c:123
    #3 0x56236cc7505a in find_label external/nasm/asm/labels.c:227
    #4 0x56236cc75286 in lookup_label external/nasm/asm/labels.c:268
    #5 0x56236cc6ba23 in expr6 external/nasm/asm/eval.c:918
    #6 0x56236cc6be81 in expr5 external/nasm/asm/eval.c:567
    #7 0x56236cc6cf94 in expr4 external/nasm/asm/eval.c:542
    #8 0x56236cc6d107 in expr3 external/nasm/asm/eval.c:508
    #9 0x56236cc6d577 in expr2 external/nasm/asm/eval.c:482
    #10 0x56236cc6da47 in expr1 external/nasm/asm/eval.c:456
    #11 0x56236cc6df1b in expr0 external/nasm/asm/eval.c:430
    #12 0x56236cc6fa3c in evaluate external/nasm/asm/eval.c:988
    #13 0x56236cc7acf8 in parse_line external/nasm/asm/parser.c:879
    #14 0x56236cc54c8a in assemble_file external/nasm/asm/nasm.c:1502
    #15 0x56236cc527c8 in main external/nasm/asm/nasm.c:617
    #16 0x7fc520f14082 in __libc_start_main ../csu/libc-start.c:308

Direct leak of 8409 byte(s) in 207 object(s) allocated from:
    #0 0x7fc521520808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x56236ccd4a17 in nasm_malloc external/nasm/nasmlib/malloc.c:75
    #2 0x56236ccd4a17 in nasm_strcat external/nasm/nasmlib/malloc.c:123
    #3 0x56236cc7505a in find_label external/nasm/asm/labels.c:227
    #4 0x56236cc75b5e in define_label external/nasm/asm/labels.c:452
    #5 0x56236cc7a75d in parse_line external/nasm/asm/parser.c:489
    #6 0x56236cc54c8a in assemble_file external/nasm/asm/nasm.c:1502
    #7 0x56236cc527c8 in main external/nasm/asm/nasm.c:617
    #8 0x7fc520f14082 in __libc_start_main ../csu/libc-start.c:308

Direct leak of 5632 byte(s) in 32 object(s) allocated from:
    #0 0x7fc521520808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x56236ccd485c in nasm_malloc external/nasm/nasmlib/malloc.c:75
    #2 0x56236cc8fd04 in do_directive external/nasm/asm/preproc.c:3062
    #3 0x56236cc9bd6f in pp_getline external/nasm/asm/preproc.c:5216
    #4 0x56236cc54c38 in assemble_file external/nasm/asm/nasm.c:1488
    #5 0x56236cc527c8 in main external/nasm/asm/nasm.c:617
    #6 0x7fc520f14082 in __libc_start_main ../csu/libc-start.c:308

Direct leak of 768 byte(s) in 192 object(s) allocated from:
    #0 0x7fc521520808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x56236ccd485c in nasm_malloc external/nasm/nasmlib/malloc.c:75
    #2 0x56236cc84113 in new_Token external/nasm/asm/preproc.c:1222
    #3 0x56236cc9d1ed in expand_mmacro external/nasm/asm/preproc.c:4901
    #4 0x56236cc9d1ed in pp_getline external/nasm/asm/preproc.c:5255
    #5 0x56236cc54c38 in assemble_file external/nasm/asm/nasm.c:1488
    #6 0x56236cc527c8 in main external/nasm/asm/nasm.c:617
    #7 0x7fc520f14082 in __libc_start_main ../csu/libc-start.c:308

Direct leak of 312 byte(s) in 3 object(s) allocated from:
    #0 0x7fc521520a06 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:153
    #1 0x56236ccd4894 in nasm_zalloc external/nasm/nasmlib/malloc.c:85
    #2 0x56236ccae79f in elf_make_section external/nasm/output/outelf.c:396
    #3 0x56236ccae79f in elf_section_names external/nasm/output/outelf.c:463
    #4 0x56236cc678f9 in process_directives external/nasm/asm/directiv.c:249
    #5 0x56236cc54c6e in assemble_file external/nasm/asm/nasm.c:1498
    #6 0x56236cc527c8 in main external/nasm/asm/nasm.c:617
    #7 0x7fc520f14082 in __libc_start_main ../csu/libc-start.c:308

Direct leak of 128 byte(s) in 4 object(s) allocated from:
    #0 0x7fc521520808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x56236ccd485c in nasm_malloc external/nasm/nasmlib/malloc.c:75
    #2 0x56236cc87f4b in pp_reset external/nasm/asm/preproc.c:5031
    #3 0x56236cc54a08 in assemble_file external/nasm/asm/nasm.c:1481
    #4 0x56236cc527c8 in main external/nasm/asm/nasm.c:617
    #5 0x7fc520f14082 in __libc_start_main ../csu/libc-start.c:308

Indirect leak of 1536 byte(s) in 64 object(s) allocated from:
    #0 0x7fc521520808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x56236ccd485c in nasm_malloc external/nasm/nasmlib/malloc.c:75
    #2 0x56236cc9c9fb in pp_getline external/nasm/asm/preproc.c:5227
    #3 0x56236cc54c38 in assemble_file external/nasm/asm/nasm.c:1488
    #4 0x56236cc527c8 in main external/nasm/asm/nasm.c:617
    #5 0x7fc520f14082 in __libc_start_main ../csu/libc-start.c:308

Indirect leak of 24 byte(s) in 2 object(s) allocated from:
    #0 0x7fc521520808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x56236ccd492f in nasm_malloc external/nasm/nasmlib/malloc.c:75
    #2 0x56236ccd492f in nasm_strdup external/nasm/nasmlib/malloc.c:104
    #3 0x56236ccae846 in elf_make_section external/nasm/output/outelf.c:407
    #4 0x56236ccae846 in elf_section_names external/nasm/output/outelf.c:463
    #5 0x56236cc678f9 in process_directives external/nasm/asm/directiv.c:249
    #6 0x56236cc54c6e in assemble_file external/nasm/asm/nasm.c:1498
    #7 0x56236cc527c8 in main external/nasm/asm/nasm.c:617
    #8 0x7fc520f14082 in __libc_start_main ../csu/libc-start.c:308

SUMMARY: AddressSanitizer: 45977 byte(s) leaked in 1224 allocation(s).
Target //tensorflow/tools/pip_package:build_pip_package failed to build
ERROR: /home/yuyao/dev/tensorflow/tensorflow/python/framework/BUILD:598:27 Linking tensorflow/python/framework/_op_def_util.so failed: (Exit 1): bash failed: error executing command 
  (cd /home/yuyao/.cache/bazel/_bazel_yuyao/ccc1279be1ec9be064e98d7fead8e6f8/execroot/org_tensorflow && \
  exec env - \
    PATH=/home/yuyao/.cache/bazelisk/downloads/bazelbuild/bazel-5.3.0-linux-x86_64/bin:/home/yuyao/.local/bin:/usr/local/cuda/compute-sanitizer:/usr/local/cuda/bin:/home/yuyao/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/bin/remote-cli:/home/yuyao/.conda/envs/ten-sanitizer/bin:/opt/miniconda3/condabin:/home/yuyao/.local/bin:/usr/local/cuda/compute-sanitizer:/usr/local/cuda/bin:/opt/miniconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
    PYTHON_BIN_PATH=/opt/miniconda3/bin/python3 \
    PYTHON_LIB_PATH=/opt/miniconda3/lib/python3.8/site-packages \
    TF2_BEHAVIOR=1 \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; for out in bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jccolor-avx2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jccolor-sse2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jcgray-avx2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jcgray-sse2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jchuff-sse2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jcphuff-sse2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jcsample-avx2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jcsample-sse2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jdcolor-avx2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jdcolor-sse2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jdmerge-avx2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jdmerge-sse2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jdsample-avx2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jdsample-sse2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jfdctflt-sse.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jfdctfst-sse2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jfdctint-avx2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jfdctint-sse2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jidctflt-sse2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jidctfst-sse2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jidctint-avx2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jidctint-sse2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jidctred-sse2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jquantf-sse2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jquanti-avx2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jquanti-sse2.o bazel-out/k8-opt/bin/external/libjpeg_turbo/simd/x86_64/jsimdcpu.o; do
  bazel-out/k8-opt/bin/external/nasm/nasm -f elf64    -DELF -DPIC -D__x86_64__    -I $(dirname bazel-out/k8-opt/bin/external/libjpeg_turbo/jconfig.h)/    -I $(dirname bazel-out/k8-opt/bin/external/libjpeg_turbo/jconfigint.h)/    -I $(dirname external/libjpeg_turbo/simd/nasm/jsimdcfg.inc.h)/    -I $(dirname external/libjpeg_turbo/simd/x86_64/jccolext-sse2.asm)/    -o $out    $(dirname external/libjpeg_turbo/simd/x86_64/jccolext-sse2.asm)/$(basename ${out%.o}.asm)
done')
# Configuration: 014280d9fadad28e5975c79178a18398bf834eb4a872c13f9a858491aca2ea7f
# Execution platform: @local_execution_config_platform//:platform
```
</details>

**Comment by Kristoff-starling** [comment]
A relevant issue is #50892. I'm curious about whether ASAN is supported now and have I done anything incorrectly when building with ubsan. Thanks!

**Comment by tilakrayal** [comment]
@Kristoff-starling,
Could you please take a look at this [comment](https://github.com/tensorflow/tensorflow/issues/55183) from the developer for the similar issue and let us know if it is working in your case. Thank you!

**Comment by Kristoff-starling** [comment]
Hi @tilakrayal,
Sorry for the late response! I've checked the building options mentioned in the comment and relevant scripts in OSS-Fuzz. Those options work well when used for building a single fuzz target but fail when I use them to build the entire TensorFlow `.whl` package. The error messages (using Clang/Clang++ as compilers) are
```bash
ERROR: /root/.cache/bazel/_bazel_root/1c025c2968c1aa16bac5eca67aaf21d1/external/llvm-project/mlir/BUILD.bazel:6969:10: Compiling mlir/tools/mlir-tblgen/mlir-tblgen.cpp failed: undeclared inclusion(s) in rule '@llvm-project//mlir:mlir-tblgen':
this rule is missing dependency declarations for the following files included by 'mlir/tools/mlir-tblgen/mlir-tblgen.cpp':
  'bazel-out/k8-opt-exec-50AE0418/bin/external/llvm-project/llvm/Demangle.cppmap'
  'bazel-out/k8-opt-exec-50AE0418/bin/external/llvm_terminfo/terminfo.cppmap'
  'bazel-out/k8-opt-exec-50AE0418/bin/external/llvm_zlib/zlib.cppmap'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```
What I'm focusing on is to run some Python programs with TensorFlow imported and use sanitizers to check their status. I notice that in OSS-Fuzz there's a project called "tensorflow-py" which aims at doing this, but I think it uses sanitizers only on the Python code level. That's why I want to manually build TensorFlow with sanitizers from source. Can you offer me some suggestions on how to use sanitizers to check C/C++ code while running Python program? Thanks a lot!

**Comment by Kristoff-starling** [comment]
I got it. Thanks a lot and I'll close this issue.
