### ISSUE TITLE
tf.raw_ops.TruncateDiv documentation is not consistent

### ISSUE THREAD

**Issue by KareemMAX** [tensorflow/tensorflow#58019]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Source

binary

### Tensorflow Version

2.9.1

### Custom Code

No

### Current Behaviour?

```shell
`tf.raw_ops.TruncateDiv` is only supporting integer values, while it is written in the first line in the documentation. The parameters section is saying that all numeric dtypes are allowed.
```

### Standalone code to reproduce the issue

```shell
tf.raw_ops.TruncateDiv(x=np.array(1.), y=np.array(1.))
```

### Relevant log output

```shell
>>> tf.raw_ops.TruncateDiv(x=np.array(1.), y=np.array(1.))
2022-10-07 22:46:30.214942: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-10-07 22:46:30.214981: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-10-07 22:46:30.214999: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (653368f87bf1): /proc/driver/nvidia/version does not exist
2022-10-07 22:46:30.215221: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/usr/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/tf_export.py", line 400, in wrapper
    return f(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 11558, in truncate_div
    return truncate_div_eager_fallback(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 11603, in truncate_div_eager_fallback
    _result = _execute.execute(b"TruncateDiv", 1, inputs=_inputs_flat,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.NotFoundError: Could not find device for node: {{node TruncateDiv}} = TruncateDiv[T=DT_DOUBLE]
All kernels registered for op TruncateDiv:
  device='GPU'; T in [DT_UINT64]
  device='GPU'; T in [DT_UINT32]
  device='GPU'; T in [DT_INT8]
  device='GPU'; T in [DT_INT64]
  device='GPU'; T in [DT_INT16]
  device='GPU'; T in [DT_UINT16]
  device='GPU'; T in [DT_UINT8]
  device='CPU'; T in [DT_INT64]
  device='CPU'; T in [DT_INT32]
  device='CPU'; T in [DT_INT16]
  device='CPU'; T in [DT_INT8]
  device='CPU'; T in [DT_UINT64]
  device='CPU'; T in [DT_UINT32]
  device='CPU'; T in [DT_UINT16]
  device='CPU'; T in [DT_UINT8]
 [Op:TruncateDiv]
```
</details>

**Comment by bhack** [comment]
The proto of the ops is correctly accepting float/double:

But at the same time we don't have registered generated kernel for float/double:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/mlir_generated/gpu_op_div.cc#L42:L45

@d0k

**Comment by bhack** [comment]
See also:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/cwise_op_div.cc

**Comment by mohantym** [comment]
Hi @bhack @KareemMAX 
Thanks for the pointers. I am trying to come with a PR to register them in kernels  and will test it with a test case prior to it.
Thank you!

**Comment by mohantym** [comment]
Ok @cantonios !
Thanks for the tip.  I will change the info in website then.
Thank you!
