### ISSUE TITLE
ONEDNN - Layer Normalization error

### ISSUE THREAD

**Issue by Chizkiyahu** [tensorflow/tensorflow#58077]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.9.2 v2.9.1-132-g18960c44ad3 2.9.2

### Custom Code

No

### OS Platform and Distribution

ubuntu 18, ubuntu 20,redhat 7

### Python version

3.8

### GCC/Compiler version

7.5.0 

### Current Behaviour?

```shell
the model predicts without errors
```

### Standalone code to reproduce the issue

```shell
import os
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '1'
import tensorflow as tf
import numpy as np

input_layer = tf.keras.layers.Input(shape=(3,24), dtype=np.float32)
data = tf.quantization.fake_quant_with_min_max_vars(inputs=input_layer, min=0, max=3.5, num_bits=8)
data = tf.keras.layers.LayerNormalization(axis=[-2,-1], center=True,scale=True)(data)
data = tf.quantization.fake_quant_with_min_max_vars(inputs=data, min=0, max=3.5, num_bits=8)
model = tf.keras.Model(inputs=input_layer, outputs=data)
model.compile()
model.summary()

data = np.random.rand(1,3,24)
res = model.predict(data)
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/python/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/path/to/python/python3.8/site-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Detected at node 'model/layer_normalization/add' defined at (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/path/to/python/python3.8/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/path/to/python/python3.8/site-packages/keras/engine/training.py", line 2033, in predict
      tmp_batch_outputs = self.predict_function(iterator)
    File "/path/to/python/python3.8/site-packages/keras/engine/training.py", line 1845, in predict_function
      return step_function(self, iterator)
    File "/path/to/python/python3.8/site-packages/keras/engine/training.py", line 1834, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/path/to/python/python3.8/site-packages/keras/engine/training.py", line 1823, in run_step
      outputs = model.predict_step(data)
    File "/path/to/python/python3.8/site-packages/keras/engine/training.py", line 1791, in predict_step
      return self(x, training=False)
    File "/path/to/python/python3.8/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/path/to/python/python3.8/site-packages/keras/engine/training.py", line 490, in __call__
      return super().__call__(*args, **kwargs)
    File "/path/to/python/python3.8/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/path/to/python/python3.8/site-packages/keras/engine/base_layer.py", line 1014, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/path/to/python/python3.8/site-packages/keras/utils/traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "/path/to/python/python3.8/site-packages/keras/engine/functional.py", line 458, in call
      return self._run_internal_graph(
    File "/path/to/python/python3.8/site-packages/keras/engine/functional.py", line 596, in _run_internal_graph
      outputs = node.layer(*args, **kwargs)
    File "/path/to/python/python3.8/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/path/to/python/python3.8/site-packages/keras/engine/base_layer.py", line 1014, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/path/to/python/python3.8/site-packages/keras/utils/traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "/path/to/python/python3.8/site-packages/keras/layers/normalization/layer_normalization.py", line 324, in call
      outputs = outputs + tf.cast(offset, outputs.dtype)
Node: 'model/layer_normalization/add'
scale must be 1D tensor[1,3,24]
	 [[{{node model/layer_normalization/add}}]] [Op:__inference_predict_function_217]
```
</details>

**Comment by tilakrayal** [comment]
@Chizkiyahu,
Thanks for opening this issue. Development of keras moved to another [repository](https://github.com/keras-team/keras/issues). 
 
 
Could you please post this issue on keras-team/keras [repo](https://github.com/keras-team/keras/issues).
To know more please refer:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!

**Comment by Chizkiyahu** [comment]
I open [issue in Keras repo](https://github.com/keras-team/keras/issues/17148)
but in my debug the bug is probably in this repo

**Comment by tilakrayal** [comment]
@Chizkiyahu,
Could you please move this issue to closed status, since it is already being tracked there in Keras repo. Thank you!
