### ISSUE TITLE
Op:HashTableV2 Support on GPU

### ISSUE THREAD

**Issue by nipun450** [tensorflow/tensorflow#58153]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

binary

### Tensorflow Version

2.8.0

### Custom Code

No

### Python version

3.8.0

### Current Behaviour?

```shell
When I try to force either IntegerLookups or StringLookups to happen on the GPU, the program errors out. The issue seems to be that the Op:HashTableV2 isn't supported on GPUs. Is it possible to support their implementation on GPUs? If not, is it possible to provide some pointers on how I could create a PR to support GPU implementation myself? Thanks! Please let me know if I can provide any additional information to clarify. Thanks!
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
tf.config.set_soft_device_placement(False)
tf.debugging.set_log_device_placement(True)
with tf.device('/GPU:0'):
    vocab = ["a", "b", "c", "d"]
    data = tf.constant([["a", "c", "d", "d"], ["d", "z", "b", "z"]])
    layer = tf.keras.layers.StringLookup(
        vocabulary=vocab, output_mode='count')
    layer(data)


import tensorflow as tf
tf.config.set_soft_device_placement(False)
tf.debugging.set_log_device_placement(True)
with tf.device('/GPU:0'):
    vocab = [12, 36, 1138, 42]
    data = tf.constant([[12, 1138, 42, 42],[42, 7, 36, 7]]) # Note OOV tokens
    layer = tf.keras.layers.IntegerLookup(vocabulary=vocab, output_mode='count')
    layer(data)
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/home/jovyan/.local/lib/python3.8/site-packages/keras/layers/preprocessing/string_lookup.py", line 326, in __init__
    super(StringLookup, self).__init__(
  File "/home/jovyan/.local/lib/python3.8/site-packages/keras/layers/preprocessing/index_lookup.py", line 289, in __init__
    self.set_vocabulary(vocabulary, idf_weights)
  File "/home/jovyan/.local/lib/python3.8/site-packages/keras/layers/preprocessing/index_lookup.py", line 485, in set_vocabulary
    self.lookup_table = self._lookup_table_from_tokens(tokens)
  File "/home/jovyan/.local/lib/python3.8/site-packages/keras/layers/preprocessing/index_lookup.py", line 707, in _lookup_table_from_tokens
    return tf.lookup.StaticHashTable(initializer, self._default_value)
  File "/home/jovyan/.local/lib/python3.8/site-packages/tensorflow/python/training/tracking/resource.py", line 104, in __call__
    return previous_getter(*args, **kwargs)
  File "/home/jovyan/.local/lib/python3.8/site-packages/tensorflow/python/training/tracking/resource.py", line 99, in <lambda>
    previous_getter = lambda *a, **kw: default_resource_creator(None, *a, **kw)
  File "/home/jovyan/.local/lib/python3.8/site-packages/tensorflow/python/training/tracking/resource.py", line 96, in default_resource_creator
    obj.__init__(*a, **kw)
  File "/home/jovyan/.local/lib/python3.8/site-packages/tensorflow/python/ops/lookup_ops.py", line 348, in __init__
    super(StaticHashTable, self).__init__(default_value, initializer)
  File "/home/jovyan/.local/lib/python3.8/site-packages/tensorflow/python/ops/lookup_ops.py", line 199, in __init__
    self._resource_handle = self._create_resource()
  File "/home/jovyan/.local/lib/python3.8/site-packages/tensorflow/python/ops/lookup_ops.py", line 358, in _create_resource
    table_ref = gen_lookup_ops.hash_table_v2(
  File "/home/jovyan/.local/lib/python3.8/site-packages/tensorflow/python/ops/gen_lookup_ops.py", line 466, in hash_table_v2
    _ops.raise_from_not_ok_status(e, name)
  File "/home/jovyan/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 7186, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Could not satisfy device specification '/job:localhost/replica:0/task:0/device:GPU:0'. enable_soft_placement=0. Supported device types [CPU]. All available devices [/job:localhost/replica:0/task:0/device:GPU:0, /job:localhost/replica:0/task:0/device:CPU:0]. [Op:HashTableV2] name: hash_table
```
</details>

**Comment by tilakrayal** [comment]
@nipun450,
I tried to execute the mentioned code in the alternative approach and was able to execute without any issue/error. Could you please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/c521fc35edc0edf3e98eb8ac6438d5fe/untitled700.ipynb) and check if it works in this case. Thank you!

**Comment by nipun450** [comment]
Thanks for the prompt response! As seen in the notebook, the HashTableV2 and LookupTableFindV2 execute on the CPU. I wanted these to execute on the GPU instead, hence the feature request!

**Comment by sushreebarsa** [comment]
@sachinprasadhs I was able to replicate this issue on the GPU using TF v2.11, please find the [gist](https://colab.research.google.com/gist/sushreebarsa/19215fb835f5fbd57a448d958ef752f9/58153.ipynb) here.  
Thank you!

**Comment by eyalhir74** [comment]
@sushreebarsa @sachinprasadhs 
Is there an update on this? I'm also trying to figure whether we can run HashTableV2 on the GPU

**Comment by eyalhir74** [comment]
@sushreebarsa @sachinprasadhs @tilakrayal 
Any update on this? Can the LookupTableFindV2 and HashTableV2 be placed on the GPU now?

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
