### ISSUE TITLE
Keras model breaks upon saving and loading when input is broadcasted

### ISSUE THREAD

**Issue by f90** [tensorflow/tensorflow#58151]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.8.1

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 18

### Python version

3.7.9

### Current Behaviour?

When defining a Keras model using functional API, the model accepts inputs that need to be broadcasted to the predefined input shape. But after saving and loading the model, it suddenly throws an error. 

This only appears if the input shape is defined "wrongly", i.e. Keras needs to broadcast the actual input to fit to the predefined input shape. Still, I would expect the model not to change behaviour after saving and loading at all. 

This bug can be quite devastating as during long training runs, you would not notice any problems. When loading the model later to evaluate, it would suddenly break, however.

### Standalone code to reproduce the issue

```shell
# Model works with an input, then breaks with the same input after you save and load it
# Must be related to the broadcasting happening with the language input (as it is wrongly set to (None,) instead of ())

import tensorflow as tf


class InnerModel(tf.keras.Model):
    def __init__(self) -> None:
        super().__init__()
        # Optionally some layers here

    def call(self, inputs: tf.Tensor, training: bool) -> tf.Tensor:
        audio, lang = inputs
        # Optionally some processing here
        return lang


def get_model():
    audio = tf.keras.Input(shape=(None, 1))
    lang = tf.keras.Input(shape=(None,), dtype=tf.string)  # Fixed by setting shape=()
    inner_model = InnerModel()
    out = inner_model([audio, lang])
    return tf.keras.Model(inputs=[audio, lang], outputs=[out])


model = get_model()
_ = model([tf.zeros((1, 1000, 1)), tf.constant(["fr"])], training=False)

# Save + load
model.save("test")  # Also breaks with tf.keras.models.save_model(model, "test")
model = tf.keras.models.load_model("test")

# Do inference again
_ = model([tf.zeros((1, 1000, 1)), tf.constant(["fr"])], training=False)
```

### Relevant log output

```shell
/Users/dstoller/.pyenv/versions/lyric-align-baseline/bin/python /Users/dstoller/IdeaProjects/lyric-align-baseline/lyric_align_baseline/keras_shape_bug.py
2022-10-15 15:27:20.163674: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
2022-10-15 15:27:20.361789: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.
Traceback (most recent call last):
  File "/Users/dstoller/IdeaProjects/lyric-align-baseline/lyric_align_baseline/keras_shape_bug.py", line 31, in <module>
    _ = model([tf.zeros((1, 1000, 1)), tf.constant(["fr"])], training=False)
  File "/Users/dstoller/.pyenv/versions/lyric-align-baseline/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/dstoller/.pyenv/versions/lyric-align-baseline/lib/python3.7/site-packages/tensorflow/python/saved_model/function_deserialization.py", line 284, in restored_function_body
    "Could not find matching concrete function to call loaded from the "
ValueError: Exception encountered when calling layer "inner_model" (type InnerModel).

Could not find matching concrete function to call loaded from the SavedModel. Got:
  Positional arguments (2 total):
    * [<tf.Tensor 'inputs:0' shape=(1, 1000, 1) dtype=float32>, <tf.Tensor 'inputs_1:0' shape=(1,) dtype=string>]
    * False
  Keyword arguments: {}

 Expected these arguments to match one of the following 4 option(s):

Option 1:
  Positional arguments (2 total):
    * [TensorSpec(shape=(None, None, 1), dtype=tf.float32, name='inputs/0'), TensorSpec(shape=(None, None), dtype=tf.string, name='inputs/1')]
    * False
  Keyword arguments: {}

Option 2:
  Positional arguments (2 total):
    * [TensorSpec(shape=(None, None, 1), dtype=tf.float32, name='inputs/0'), TensorSpec(shape=(None, None), dtype=tf.string, name='inputs/1')]
    * True
  Keyword arguments: {}

Option 3:
  Positional arguments (2 total):
    * [TensorSpec(shape=(None, None, 1), dtype=tf.float32, name='input_1'), TensorSpec(shape=(None, None), dtype=tf.string, name='input_2')]
    * False
  Keyword arguments: {}

Option 4:
  Positional arguments (2 total):
    * [TensorSpec(shape=(None, None, 1), dtype=tf.float32, name='input_1'), TensorSpec(shape=(None, None), dtype=tf.string, name='input_2')]
    * True
  Keyword arguments: {}

Call arguments received:
  • args=(['tf.Tensor(shape=(1, 1000, 1), dtype=float32)', 'tf.Tensor(shape=(1,), dtype=string)'],)
  • kwargs={'training': 'False'}

Process finished with exit code 1
```
</details>

**Comment by f90** [comment]
Thanks for looking into this! I posted it [here](https://github.com/keras-team/keras/issues/17171) on the Keras repo.

**Comment by tiruk007** [comment]
@f90 
Could you please close this issue and track this on [keras-team/keras repo.](https://github.com/keras-team/keras/issues).
Thank you!
