### ISSUE TITLE
Mobile SSD model generates only 1 output

### ISSUE THREAD

**Issue by baqwas** [tensorflow/tensorflow#58189]
### 1. System information

- Used Colab
- Used Jupyter under Ubuntu 22.04 to emulate same exercise (_i.e._ build ._tflite_ and ._txt_ files)

Running original Tensorflow Lite tutorial on **flowers** image classification with only one change in parameter for _model_spec_ as noted below.

### 2. Code

Total newbie here, sorry!

- Performed Android Studio development for the classification tutorial on flowers.
- Deployed to Pixel 2 XL
- The app runs fine
- Ran the flowers tutorial in Colab to generate the ._tflite_ and ._txt_ files.
- Deployed to another Android device (?) where the error message is:
_Mobile SSD models are expected to have exactly 4 outputs, found 1_

Don't have access to the source code for the another Android app. However, this app reads the COCO ._tflite_ model without errors. So the issue lies in my understanding of how I should specify the parameters to generate the .tflite model file in the expected format.

#### Option A: Reference colab notebooks

1)  Reference [TensorFlow Model Colab](https://www.tensorflow.org/lite/models/modify/model_maker/image_classification): Demonstrate how to build your TF model.
2)  Reference [Image Classifier](https://github.com/lmoroney/odmlbook): Sample runs fine when built under Dolphin 2021.3.1 and ported to Pixel 2 XL.

#### Option B: Paste your code here or provide a link to a custom end-to-end colab

How to change the following statement to meet the requirement: _Mobile SSD models are expected to have exactly 4 outputs, found 1_

```
model = image_classifier.create(train_data, model_spec=model_spec.get('mobilenet_v2'), validation_data=validation_data)
```
Don't know how what parameter to set to obtain a ._tflite_ model file that will meet the requirement. Did a cursory search for links to the documentation for **image_classifier.create** method but couldn't find anything owing to my inexperience.

### 3. Failure after conversion

Not performing any conversion. Would like to perform conversion if that approach is recommended but then I'm totally ignorant about conversion and some links to more detailed information on conversion would be helpful.

- Model cannot be read in a very simple end-user operation because Mobile SSD models are expected to have exactly 4 outputs, found 1

### 4. (optional) RNN conversion support
not applicable

### 5. (optional) Any other info / logs

The following will not be helpful (because I do not have access to the underlying source code and cannot provide it for further support purposes) but I have included it nevertheless for completeness:

```
2022-10-20 09:21:36.336 2300-2477/com.qualcomm.ftcrobotcontroller E/AndroidRuntime: FATAL EXCEPTION: VuforiaFrameGenerator
    Process: com.qualcomm.ftcrobotcontroller, PID: 2300
    java.lang.AssertionError: Error occurred when initializing ObjectDetector: Mobile SSD models are expected to have exactly 4 outputs, found 1
        at org.tensorflow.lite.task.vision.detector.ObjectDetector.initJniWithByteBuffer(Native Method)
        at org.tensorflow.lite.task.vision.detector.ObjectDetector.access$100(ObjectDetector.java:86)
        at org.tensorflow.lite.task.vision.detector.ObjectDetector$3.createHandle(ObjectDetector.java:211)
        at org.tensorflow.lite.task.core.TaskJniUtils.createHandleFromLibrary(TaskJniUtils.java:91)
        at org.tensorflow.lite.task.vision.detector.ObjectDetector.createFromBufferAndOptions(ObjectDetector.java:207)
        at org.firstinspires.ftc.robotcore.internal.tfod.TfodFrameManager2$RecognizerPipeline2.<init>(TfodFrameManager2.java:66)
        at org.firstinspires.ftc.robotcore.internal.tfod.TfodFrameManager2$RecognizerPipeline2.<init>(TfodFrameManager2.java:55)
        at org.firstinspires.ftc.robotcore.internal.tfod.TfodFrameManager2.createRecognizerPipeline(TfodFrameManager2.java:52)
        at org.firstinspires.ftc.robotcore.internal.tfod.TfodFrameManager$MainPipeline.init(TfodFrameManager.java:227)
        at org.firstinspires.ftc.robotcore.internal.tfod.VuforiaFrameGenerator.run(VuforiaFrameGenerator.java:147)
        at java.lang.Thread.run(Thread.java:761)

```

**Comment by mohantym** [comment]
Hi @baqwas !
Sorry for the late response.

Could you use [metadata writer ](https://www.tensorflow.org/lite/models/convert/metadata_writer_tutorial)to normalize the ssd model then port to your android application.
[Reference.](https://github.com/tensorflow/tensorflow/issues/47595#issuecomment-797248210)
Thank you!

**Comment by baqwas** [comment]
@mohantym 

Thank you very much. I will try your suggestion.

Kind regards.
