### ISSUE TITLE
Failed to load the native TensorFlow runtime

### ISSUE THREAD

**Issue by Begowur** [tensorflow/tensorflow#58186]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.10

### Custom Code

No

### Python version

3.9

### Current Behaviour?

```shell
Testing tensorflow
```

### Standalone code to reproduce the issue

```shell
(venv) C:\AMAZON\test>python -m pip install tensorflow
Requirement already satisfied: tensorflow in c:\amazon\test\venv\lib\site-packages (2.10.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: absl-py>=1.0.0 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (1.3.0)
Requirement already satisfied: tensorboard<2.11,>=2.10 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (2.10.1)
Requirement already satisfied: libclang>=13.0.0 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (14.0.6)
Requirement already satisfied: flatbuffers>=2.0 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (22.9.24)
Requirement already satisfied: keras<2.11,>=2.10.0 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (2.10.0)
Requirement already satisfied: numpy>=1.20 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (1.22.4)
Requirement already satisfied: setuptools in c:\amazon\test\venv\lib\site-packages (from tensorflow) (60.2.0)
Requirement already satisfied: packaging in c:\amazon\test\venv\lib\site-packages (from tensorflow) (21.3)
Requirement already satisfied: six>=1.12.0 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (1.16.0)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (0.4.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (2.0.1)
Requirement already satisfied: google-pasta>=0.1.1 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: tensorflow-estimator<2.11,>=2.10.0 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (2.10.0)
Collecting keras-preprocessing>=1.1.1
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (1.14.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (1.49.1)
Requirement already satisfied: protobuf<3.20,>=3.9.2 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (3.19.6)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (0.27.0)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (4.4.0)
Requirement already satisfied: h5py>=2.9.0 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (3.7.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\amazon\test\venv\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.37.1)
Requirement already satisfied: werkzeug>=1.0.1 in c:\amazon\test\venv\lib\site-packages (from tensorboard<2.11,>=2.10->tensorflow) (2.2.2)
Requirement already satisfied: google-auth<3,>=1.6.3 in c:\amazon\test\venv\lib\site-packages (from tensorboard<2.11,>=2.10->tensorflow) (2.12.0)       
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in c:\amazon\test\venv\lib\site-packages (from tensorboard<2.11,>=2.10->tensorflow) (0.4.6)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in c:\amazon\test\venv\lib\site-packages (from tensorboard<2.11,>=2.10->tensorflow) (0.6.1)
Requirement already satisfied: markdown>=2.6.8 in c:\amazon\test\venv\lib\site-packages (from tensorboard<2.11,>=2.10->tensorflow) (3.4.1)
Requirement already satisfied: requests<3,>=2.21.0 in c:\amazon\test\venv\lib\site-packages (from tensorboard<2.11,>=2.10->tensorflow) (2.28.1)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in c:\amazon\test\venv\lib\site-packages (from tensorboard<2.11,>=2.10->tensorflow) (1.8.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\amazon\test\venv\lib\site-packages (from packaging->tensorflow) (2.4.7)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\amazon\test\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.11,>=2.10->tensorflow) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\amazon\test\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.11,>=2.10->tensorflow) (4.9)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\amazon\test\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.11,>=2.10->tensorflow) (5.2.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\amazon\test\venv\lib\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.11,>=2.10->tensorflow) (1.3.1)
Requirement already satisfied: importlib-metadata>=4.4 in c:\amazon\test\venv\lib\site-packages (from markdown>=2.6.8->tensorboard<2.11,>=2.10->tensorflow) (5.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\amazon\test\venv\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.11,>=2.10->tensorflow) (1.26.12)
Requirement already satisfied: certifi>=2017.4.17 in c:\amazon\test\venv\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.11,>=2.10->tensorflow) (2022.9.24)
Requirement already satisfied: idna<4,>=2.5 in c:\amazon\test\venv\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.11,>=2.10->tensorflow) (3.4)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\amazon\test\venv\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.11,>=2.10->tensorflow) (2.1.1)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\amazon\test\venv\lib\site-packages (from werkzeug>=1.0.1->tensorboard<2.11,>=2.10->tensorflow) (2.1.1)
Requirement already satisfied: zipp>=0.5 in c:\amazon\test\venv\lib\site-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard<2.11,>=2.10->tensorflow) (3.9.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\amazon\test\venv\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.11,>=2.10->tensorflow) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in c:\amazon\test\venv\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.11,>=2.10->tensorflow) (3.2.1)
Installing collected packages: keras-preprocessing
  Attempting uninstall: keras-preprocessing
    Found existing installation: Keras-Preprocessing 1.0.5
    Uninstalling Keras-Preprocessing-1.0.5:
      Successfully uninstalled Keras-Preprocessing-1.0.5
Successfully installed keras-preprocessing-1.1.2

(venv) C:\AMAZON\test>conda create --name tensorflow-env python=3.8 pip
'conda' is not recognized as an internal or external command,
operable program or batch file.

(venv) C:\AMAZON\test>conda activate tensorflow-env
'conda' is not recognized as an internal or external command,
operable program or batch file.

(venv) C:\AMAZON\test>pip install tensorflow
Requirement already satisfied: tensorflow in c:\amazon\test\venv\lib\site-packages (2.10.0)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (1.49.1)
Requirement already satisfied: keras-preprocessing>=1.1.1 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (1.1.2)
Requirement already satisfied: absl-py>=1.0.0 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (1.3.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (2.0.1)
Requirement already satisfied: keras<2.11,>=2.10.0 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (2.10.0)
Requirement already satisfied: flatbuffers>=2.0 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (22.9.24)
Requirement already satisfied: tensorflow-estimator<2.11,>=2.10.0 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (2.10.0)
Requirement already satisfied: protobuf<3.20,>=3.9.2 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (3.19.6)
Requirement already satisfied: numpy>=1.20 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (1.22.4)
Requirement already satisfied: libclang>=13.0.0 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (14.0.6)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (0.27.0)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (4.4.0)
Requirement already satisfied: tensorboard<2.11,>=2.10 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (2.10.1)
Requirement already satisfied: packaging in c:\amazon\test\venv\lib\site-packages (from tensorflow) (21.3)
Requirement already satisfied: six>=1.12.0 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (1.16.0)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (0.4.0)
Requirement already satisfied: h5py>=2.9.0 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (3.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: setuptools in c:\amazon\test\venv\lib\site-packages (from tensorflow) (60.2.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\amazon\test\venv\lib\site-packages (from tensorflow) (1.14.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\amazon\test\venv\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.37.1)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in c:\amazon\test\venv\lib\site-packages (from tensorboard<2.11,>=2.10->tensorflow) (1.8.1)
Requirement already satisfied: werkzeug>=1.0.1 in c:\amazon\test\venv\lib\site-packages (from tensorboard<2.11,>=2.10->tensorflow) (2.2.2)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in c:\amazon\test\venv\lib\site-packages (from tensorboard<2.11,>=2.10->tensorflow) (0.4.6)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in c:\amazon\test\venv\lib\site-packages (from tensorboard<2.11,>=2.10->tensorflow) (0.6.1)
Requirement already satisfied: requests<3,>=2.21.0 in c:\amazon\test\venv\lib\site-packages (from tensorboard<2.11,>=2.10->tensorflow) (2.28.1)
Requirement already satisfied: google-auth<3,>=1.6.3 in c:\amazon\test\venv\lib\site-packages (from tensorboard<2.11,>=2.10->tensorflow) (2.12.0)       
Requirement already satisfied: markdown>=2.6.8 in c:\amazon\test\venv\lib\site-packages (from tensorboard<2.11,>=2.10->tensorflow) (3.4.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\amazon\test\venv\lib\site-packages (from packaging->tensorflow) (2.4.7)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\amazon\test\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.11,>=2.10->tensorflow) (4.9)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\amazon\test\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.11,>=2.10->tensorflow) (0.2.8)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\amazon\test\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.11,>=2.10->tensorflow) (5.2.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\amazon\test\venv\lib\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.11,>=2.10->tensorflow) (1.3.1)
Requirement already satisfied: importlib-metadata>=4.4 in c:\amazon\test\venv\lib\site-packages (from markdown>=2.6.8->tensorboard<2.11,>=2.10->tensorflow) (5.0.0)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\amazon\test\venv\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.11,>=2.10->tensorflow) (2.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\amazon\test\venv\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.11,>=2.10->tensorflow) (1.26.12)
Requirement already satisfied: certifi>=2017.4.17 in c:\amazon\test\venv\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.11,>=2.10->tensorflow) (2022.9.24)
Requirement already satisfied: idna<4,>=2.5 in c:\amazon\test\venv\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.11,>=2.10->tensorflow) (3.4)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\amazon\test\venv\lib\site-packages (from werkzeug>=1.0.1->tensorboard<2.11,>=2.10->tensorflow) (2.1.1)
Requirement already satisfied: zipp>=0.5 in c:\amazon\test\venv\lib\site-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard<2.11,>=2.10->tensorflow) (3.9.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\amazon\test\venv\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.11,>=2.10->tensorflow) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in c:\amazon\test\venv\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.11,>=2.10->tensorflow) (3.2.1)

(venv) C:\AMAZON\test>python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
Traceback (most recent call last):
  File "C:\AMAZON\test\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: %1 is not a valid Win32 application.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\AMAZON\test\venv\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\AMAZON\test\venv\lib\site-packages\tensorflow\python\__init__.py", line 36, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "C:\AMAZON\test\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 77, in <module>
    raise ImportError(
ImportError: Traceback (most recent call last):
  File "C:\AMAZON\test\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: %1 is not a valid Win32 application.


Failed to load the native TensorFlow runtime.
```

### Relevant log output

_No response_</details>

**Comment by tiruk007** [comment]
Hi @Begowur,
Sorry for the late reply. Try `pip install tensorflow-cpu` instead of `pip install tensorflow` for CPU setup and refer to [Install TensorFlow with pip](https://www.tensorflow.org/install/pip) for GPU setup. Could you please refer to similar [issue 1](https://github.com/tensorflow/tensorflow/issues/45287) and [issue 2](https://github.com/tensorflow/tensorflow/issues/22794) and let us know if it helps.

Thank you.
