### ISSUE TITLE
How to use non-zero values in sparse tensors for constructing graph in tensorflow 1.x

### ISSUE THREAD

**Issue by NwpuPc** [tensorflow/tensorflow#58214]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

binary

### Tensorflow Version

v1.14.0-rc1-22-gaf24dc91b5 1.14.0

### Custom Code

Yes

### OS Platform and Distribution

x86_64 GNU/Linux

### Python version

3.6.9

### Current Behaviour?

```shell
How to use non-zero values in sparse tensors for constructing graph in tensorflow 1.x
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np

# batch_size, slot_num, fea_num(not fixed) [2,3,4]
sparse = tf.sparse.placeholder(tf.float32)
def model(x):
    net_out = tf.layers.dense(
        inputs=x,
        units=10,
        activation=tf.sigmoid,
        name="fc1")
    net_out = tf.layers.dense(
        inputs=net_out,
        units=2,
        activation=tf.sigmoid,
        name='fc2')
    return net_out

def nothing(x):
    # fake because of 0
    return x[:,:,:,:2]

def model_cond(x):
    return tf.cond(tf.abs(tf.reduce_sum(x,axis=2)) < 1e-8, lambda: model(x), lambda: nothing(x))

# to dense
dense = tf.sparse.to_dense(sparse)

# fake encode
dense_ex = tf.expand_dims(dense, -1)
k = 10
dense_tile = tf.tile(dense_ex, [1,1,1,k])

# model
dense_re = tf.reshape(dense_tile, [2,3,-1,k])
#fc = model(dense_re)
fc = model_cond(dense_re)

# pooling
# batch_size, slot_num, dim [2,3,4,2]
fc_pool = tf.reduce_sum(fc, axis=2)

indices = np.array([[0, 0, 1], [0,1,0],[0,2,2],[1,0,0],[1,1,1],[1,2,2],[1,2,3]], dtype=np.int64)
values = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0], dtype=np.float32)
shape = np.array([2, 3, 4], dtype=np.int64)

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
res=sess.run([dense,dense_ex,dense_tile,fc,fc_pool], feed_dict={sparse:(indices, values, shape)})
for v in res:
    print(v)
    print("----------")
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1864, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape must be rank 0 but is rank 3 for 'cond/Switch' (op: 'Switch') with input shapes: [2,3,10], [2,3,10].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_sparse.py", line 43, in <module>
    fc = model_cond(dense_re)
  File "test_sparse.py", line 24, in model_cond
    return tf.cond(tf.abs(tf.reduce_sum(x,axis=2)) < 1e-8, lambda: model(x), lambda: nothing(x))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1965, in cond
    p_2, p_1 = switch(pred, pred)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 308, in switch
    return gen_control_flow_ops.switch(data, pred, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_control_flow_ops.py", line 935, in switch
    "Switch", data=data, pred=pred, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 2027, in __init__
    control_input_ops)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1867, in _create_c_op
    raise ValueError(str(e))
ValueError: Shape must be rank 0 but is rank 3 for 'cond/Switch' (op: 'Switch') with input shapes: [2,3,10], [2,3,10].
```
</details>

**Comment by tiruk007** [comment]
Hi @NwpuPc, 
Sorry for the late reply. I observed that you are using an older version of TF(1.x) which is not actively supported. Could you please upgrade to the latest TF version and let us know if the issue still persists in the latest TF version?

Thank you!

**Comment by NwpuPc** [comment]
Thank you for your reply. I have solved the problem using RaggedTensor.

**Comment by NwpuPc** [comment]
@tiruk007 Thank you for your reply. I have solved the problem using RaggedTensor.

**Comment by tiruk007** [comment]
@NwpuPc 
Could you please close this issue if it is resolved ?
Thank you!
