### ISSUE TITLE
An error occurred during the fetch of repository 'local_config_cuda'

### ISSUE THREAD

**Issue by Johnsyisme** [tensorflow/tensorflow#58210]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

tf 2.8

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.9

### Bazel version

4.2.1

### GCC/Compiler version

9.4.0

### CUDA/cuDNN version

CUDA 11.7 /cuDNN 8

### GPU model and memory

A100 80G

### Current Behaviour?

```shell
A bug happened!
```

### Standalone code to reproduce the issue

```shell
git clone https://github.com/tensorflow/tensorflow tensorflow -b v2.8.0 --depth=1
```

### Relevant log output

```shell
ERROR: An error occurred during the fetch of repository 'local_config_cuda':                                   
   Traceback (most recent call last):                                                                          
        File "/home/xizhang/software/dpmd/tensorflow/third_party/gpus/cuda_configure.bzl", line 1401, column 38
, in _cuda_autoconf_impl                                                                                       
                _create_local_cuda_repository(repository_ctx)                                                  
        File "/home/xizhang/software/dpmd/tensorflow/third_party/gpus/cuda_configure.bzl", line 1076, column 27
, in _create_local_cuda_repository                                                                             
                cuda_libs = _find_libs(repository_ctx, check_cuda_libs_script, cuda_config)                    
        File "/home/xizhang/software/dpmd/tensorflow/third_party/gpus/cuda_configure.bzl", line 606, column 21,
 in _find_libs                                                                                                 
                _check_cuda_libs(repository_ctx, check_cuda_libs_script, check_cuda_libs_params.values())      
        File "/home/xizhang/software/dpmd/tensorflow/third_party/gpus/cuda_configure.bzl", line 501, column 28,
 in _check_cuda_libs                                                                                           
                checked_paths = execute(repository_ctx, [python_bin, "-c", cmd]).stdout.splitlines()           
        File "/home/xizhang/software/dpmd/tensorflow/third_party/remote_config/common.bzl", line 230, column 13
, in execute                                                                                                   
                fail(                                                                                          
Error in fail: Repository command failed
Expected even number of arguments
ERROR: Error fetching repository: Traceback (most recent call last):
        File "/home/xizhang/software/dpmd/tensorflow/third_party/gpus/cuda_configure.bzl", line 1401, column 38, in _cuda_autoconf_impl
                _create_local_cuda_repository(repository_ctx)
        File "/home/xizhang/software/dpmd/tensorflow/third_party/gpus/cuda_configure.bzl", line 1076, column 27, in _create_local_cuda_repository
                cuda_libs = _find_libs(repository_ctx, check_cuda_libs_script, cuda_config)        File "/home/xizhang/software/dpmd/tensorflow/third_party/gpus/cuda_configure.bzl", line 606, column 21, in _find_libs
                _check_cuda_libs(repository_ctx, check_cuda_libs_script, check_cuda_libs_params.values())
        File "/home/xizhang/software/dpmd/tensorflow/third_party/gpus/cuda_configure.bzl", line 501, column 28, in _check_cuda_libs
                checked_paths = execute(repository_ctx, [python_bin, "-c", cmd]).stdout.splitlines()
        File "/home/xizhang/software/dpmd/tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
Expected even number of arguments
INFO: Found applicable config definition build:cuda in file /home/xizhang/software/dpmd/tensorflow/.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
INFO: Found applicable config definition build:cuda in file /home/xizhang/software/dpmd/tensorflow/.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
ERROR: @local_config_cuda//:enable_cuda :: Error loading option @local_config_cuda//:enable_cuda: Repository command failed
Expected even number of arguments
```
</details>

**Comment by tiruk007** [comment]
Hi @Johnsyisme 
Sorry for the late reply. I'm able to clone the tensorflow repository without any problem on Ubuntu. I observed that you are using GCC 9.4.0 and CUDA 11.7 which is incompatible with TF v2.8.0. Could you please create a virtual environment and try to install the tensorflow as mentioned in this official document [link](https://www.tensorflow.org/install/source) and have a look at the [compatible](https://www.tensorflow.org/install/source#gpu) tested build configurations as well.  Please find the attached screenshot for reference. 

Thank you!

![Screenshot from 2022-10-26 21-53-50](https://user-images.githubusercontent.com/111861663/198086157-3733b538-5af7-44ba-af7e-b66d25300b70.png)

**Comment by jung-youjin** [comment]
Hi, is this solved?
