### ISSUE TITLE
ModuleNotFoundError: No module named 'google.protobuf' under Ubuntu Jammy

### ISSUE THREAD

**Issue by berndporr** [tensorflow/tensorflow#58247]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

v2.10.0

### Custom Code

No

### OS Platform and Distribution

Ubuntu 22.04.1 LTS

### Python version

3.10.6

### Bazel version

5.1.1

### GCC/Compiler version

gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0

### CUDA/cuDNN version

cudnn-local-repo-ubuntu2204-8.6.0.163_1.0-1_amd64

### GPU model and memory

NVIDIA Corporation GM206 [GeForce GTX 950] (rev a1)

### Current Behaviour?

```shell
Followed the standard instruction to compile TF from source.
The command:
bazel build --config=cuda --local_ram_resources=8192 //tensorflow/tools/pip_package:build_pip_package
fails with:
ERROR: /home/bernd/tensorflow/tensorflow/BUILD:1397:19: Executing genrule //tensorflow:tf_python_api_gen_v2 failed: (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument skipped)
2022-10-21 21:31:14.939452: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-21 21:31:15.169373: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
Traceback (most recent call last):
  File "/home/bernd/.cache/bazel/_bazel_bernd/2716ba2e215c041a26405d6ef9e43b69/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 22, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/home/bernd/.cache/bazel/_bazel_bernd/2716ba2e215c041a26405d6ef9e43b69/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "/home/bernd/.cache/bazel/_bazel_bernd/2716ba2e215c041a26405d6ef9e43b69/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/eager/context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "/home/bernd/.cache/bazel/_bazel_bernd/2716ba2e215c041a26405d6ef9e43b69/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/core/framework/function_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google.protobuf'
Target //tensorflow/tools/pip_package:build_pip_package failed to build

If I just run that script:
python /home/bernd/.cache/bazel/_bazel_bernd/2716ba2e215c041a26405d6ef9e43b69/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/core/framework/function_pb2.py
Traceback (most recent call last):
  File "/home/bernd/.cache/bazel/_bazel_bernd/2716ba2e215c041a26405d6ef9e43b69/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/core/framework/function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
ModuleNotFoundError: No module named 'tensorflow'
then protobuf can be found (my install) but not tensorflow which looks like a virtual environment issue.
```

### Standalone code to reproduce the issue

```shell
git checkout v2.10.0
./configure
Default but with cuda = y
bazel build --config=cuda --local_ram_resources=8192 //tensorflow/tools/pip_package:build_pip_package
```

### Relevant log output

```shell
ERROR: /home/bernd/tensorflow/tensorflow/BUILD:1397:19: Executing genrule //tensorflow:tf_python_api_gen_v2 failed: (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument skipped)
2022-10-21 21:31:14.939452: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-21 21:31:15.169373: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
Traceback (most recent call last):
  File "/home/bernd/.cache/bazel/_bazel_bernd/2716ba2e215c041a26405d6ef9e43b69/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 22, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/home/bernd/.cache/bazel/_bazel_bernd/2716ba2e215c041a26405d6ef9e43b69/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "/home/bernd/.cache/bazel/_bazel_bernd/2716ba2e215c041a26405d6ef9e43b69/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/eager/context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "/home/bernd/.cache/bazel/_bazel_bernd/2716ba2e215c041a26405d6ef9e43b69/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/core/framework/function_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google.protobuf'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/bernd/tensorflow/tensorflow/python/tools/BUILD:313:10 Middleman _middlemen/tensorflow_Spython_Stools_Ssaved_Umodel_Ucli-runfiles failed: (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument skipped)
```
</details>

**Comment by pwuertz** [comment]
Issue also present in latest release `v2.11.0-rc1`

**Comment by pwuertz** [comment]
> Have you tried the same removing "--config=cuda"?

Removing `--config=cuda` from the build command doesn't seem to effect that error.

By the way, what is the effect of using/not-using `--config=cuda` with `bazel build`, given that I enabled and configured CUDA support within `./configure`?

**Comment by pwuertz** [comment]
The Tensorflow build seems to choke on the `python3-protobuf` package for some reason. Installing `protobuf` via pip fixed the issue here:
```
pip install protobuf==3.19
```

**Comment by bhack** [comment]
> The Tensorflow build seems to choke on the python3-protobuf package for some reason. Installing protobuf via pip fixed the issue here:

Yes sorry I just looked at the first error on the 2nd log.

I think it is an instance of the old
https://github.com/tensorflow/tensorflow/issues/6341

@berndporr Can you try to install protobuf from pip?

**Comment by berndporr** [comment]
Hang in there. Server with the GPU card has been playing up. Now with new power supply!

**Comment by berndporr** [comment]
Now I'm getting this protobuf related error:
```
Traceback (most recent call last):
  File "/home/bernd/.cache/bazel/_bazel_bernd/2716ba2e215c041a26405d6ef9e43b69/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 22, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/home/bernd/.cache/bazel/_bazel_bernd/2716ba2e215c041a26405d6ef9e43b69/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "/home/bernd/.cache/bazel/_bazel_bernd/2716ba2e215c041a26405d6ef9e43b69/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/eager/context.py", line 28, in <module>
    from tensorflow.core.framework import function_pb2
  File "/home/bernd/.cache/bazel/_bazel_bernd/2716ba2e215c041a26405d6ef9e43b69/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/core/framework/function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/home/bernd/.cache/bazel/_bazel_bernd/2716ba2e215c041a26405d6ef9e43b69/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/home/bernd/.cache/bazel/_bazel_bernd/2716ba2e215c041a26405d6ef9e43b69/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/home/bernd/.cache/bazel/_bazel_bernd/2716ba2e215c041a26405d6ef9e43b69/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/core/framework/resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "/home/bernd/.cache/bazel/_bazel_bernd/2716ba2e215c041a26405d6ef9e43b69/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/core/framework/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/usr/local/lib/python3.10/dist-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/bernd/tensorflow/tensorflow/python/tools/BUILD:81:10 Middleman _middlemen/tensorflow_Spython_Stools_Sfreeze_Ugraph-runfiles failed: (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument skipped)
INFO: Elapsed time: 14566.792s, Critical Path: 923.90s
INFO: 20638 processes: 258 internal, 20380 local.
FAILED: Build did NOT complete successfully

```

**Comment by bhack** [comment]
I think we are using https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/release/requirements_common.txt#L12

**Comment by berndporr** [comment]
```
Collecting protobuf==3.19.3
  Downloading protobuf-3.19.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 6.6 MB/s eta 0:00:00
Installing collected packages: protobuf
  Attempting uninstall: protobuf
    Found existing installation: protobuf 4.21.9
    Uninstalling protobuf-4.21.9:
      Successfully uninstalled protobuf-4.21.9
```
and
```
INFO: Analyzed target //tensorflow/tools/pip_package:build_pip_package (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //tensorflow/tools/pip_package:build_pip_package up-to-date:
  bazel-bin/tensorflow/tools/pip_package/build_pip_package
INFO: Elapsed time: 12.254s, Critical Path: 10.93s
INFO: 3 processes: 1 internal, 2 local.
INFO: Build completed successfully, 3 total actions

```
@bhack that's done the trick. Thank you. Now building the wheel.

**Comment by berndporr** [comment]
```
bernd@bp-dst5:~$ python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
2022-11-03 16:44:44.752424: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-11-03 16:44:47.089734: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-11-03 16:44:47.474073: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-11-03 16:44:47.474604: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
bernd@bp-dst5:~$ 
```
No idea what that means but hope that's OK!

**Comment by bhack** [comment]
@berndporr Yes it is ok that one is https://github.com/tensorflow/tensorflow/issues/58428

**Comment by bhack** [comment]
Can we close this?

**Comment by berndporr** [comment]
Yes! :)
