### ISSUE TITLE
Failing to fit an lstm model.fit(x=g,) with generator `g`, custom loss function and `run_eagerly` is False

### ISSUE THREAD

**Issue by jmp75** [tensorflow/tensorflow#58258]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

v2.10.0-rc3-6-g359c3cdfc5f 2.10.0

### Custom Code

Yes

### OS Platform and Distribution

Linux xxxxxx 5.10.0-19-amd64   SMP Debian 5.10.149-1 (2022-10-17) x86_64 GNU/Linux

### Python version

python  3.9.13   h9a8a25e_0_cpython    conda-forge

### CUDA/cuDNN version

cudatoolkit  11.2.2  hbe64b41_10  conda-forge,  cudnn  8.1.0.77  h90431f1_0  conda-forge

### GPU model and memory

Quadro RTX 4000, 8GB

### Current Behaviour?

I was trying to rerun some earlier work, that used to work on TF 2.6.0 I think (not sure). 

In a nutshell, extracted for a repro gist thereafter: 

```python
def create_and_fit(x, run_eagerly):
    model = new_model()
    model.compile(optimizer=Adam(learning_rate=1e-4), loss=mean_absolute_error_na, metrics=[some_metric], run_eagerly=run_eagerly)
    return model.fit(
        x,
        steps_per_epoch=steps_per_epoch,
        epochs=epochs,
        validation_data=None
    )
```

if x is a `<generator object train_generator_batch>` and `run_eagerly` is `False`, it seems that invalid ground truth observations `y_true` is passed to the custom loss function, which reports:

```text
Epoch 1/5
y_true = Tensor("mean_absolute_error_na/remove_squeezable_dimensions/Squeeze:0", shape=(None, None), dtype=float32)
y_pred = Tensor("model_1/dense_1/BiasAdd:0", shape=(16, 1), dtype=float32)
etc etc stack trace...
    ValueError: y_true and y_pred do not have compatible shapes: (None, None) and (16, 1). Respective types are <class 'tensorflow.python.framework.ops.Tensor'> and <class 'tensorflow.python.framework.ops.Tensor'>
```

Model fitting works however if `run_eagerly` is True, or if x is passed a dataset created with `tf.data.Dataset.from_generator`.

Note that I run the jupyter python kernel launched via `optirun` to access the GPU, in case this has relevance. The bug anyway occurs also if forcing the execution on the CPU.

### Standalone code to reproduce the issue

A self-contained notebook (python file obtained with jupytext) is available at [this gist](https://gist.github.com/jmp75/d55e5f73e337012ba610c72d20a4398f)

### Relevant log output

```shell
Epoch 1/5
y_true = Tensor("mean_absolute_error_na/remove_squeezable_dimensions/Squeeze:0", shape=(None, None), dtype=float32)
y_pred = Tensor("model_1/dense_1/BiasAdd:0", shape=(16, 1), dtype=float32)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In [40], line 1
----> 1 create_and_fit(train_gen, run_eagerly = False)

Cell In [37], line 4, in create_and_fit(x, run_eagerly)
      2 model = new_model()
      3 model.compile(optimizer=Adam(learning_rate=1e-4), loss=mean_absolute_error_na, metrics=[some_metric], run_eagerly=run_eagerly)
----> 4 return model.fit(
      5     x,
      6     steps_per_epoch=steps_per_epoch,
      7     epochs=epochs,
      8     validation_data=None
      9 )

File ~/miniconda/envs/my_env_name/lib/python3.9/site-packages/keras/utils/traceback_utils.py:70, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     67     filtered_tb = _process_traceback_frames(e.__traceback__)
     68     # To get the full stack trace, call:
     69     # `tf.debugging.disable_traceback_filtering()`
---> 70     raise e.with_traceback(filtered_tb) from None
     71 finally:
     72     del filtered_tb

File /tmp/__autograph_generated_file7kl24yk4.py:15, in outer_factory.<locals>.inner_factory.<locals>.tf__train_function(iterator)
     13 try:
     14     do_return = True
---> 15     retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
     16 except:
     17     do_return = False

File /tmp/__autograph_generated_filexp4m9ubh.py:11, in outer_factory.<locals>.inner_factory.<locals>.tf__mean_absolute_error_na(y_true, y_pred)
      9 do_return = False
     10 retval_ = ag__.UndefinedReturnValue()
---> 11 (y_true_m, y_pred_m) = ag__.converted_call(ag__.ld(remove_items_missing_observations), (ag__.ld(y_true), ag__.ld(y_pred)), None, fscope)
     12 try:
     13     do_return = True

File /tmp/__autograph_generated_filei0twifpa.py:24, in outer_factory.<locals>.inner_factory.<locals>.tf__remove_items_missing_observations(y_true, y_pred)
     22 def else_body():
     23     pass
---> 24 ag__.if_stmt(ag__.ld(y_true).shape != ag__.ld(y_pred).shape, if_body, else_body, get_state, set_state, (), 0)
     25 try:
     26     do_return = True

File /tmp/__autograph_generated_filei0twifpa.py:20, in outer_factory.<locals>.inner_factory.<locals>.tf__remove_items_missing_observations.<locals>.if_body()
     18 ag__.ld(print)(f'y_true = {ag__.ld(y_true)}')
     19 ag__.ld(print)(f'y_pred = {ag__.ld(y_pred)}')
---> 20 raise ag__.converted_call(ag__.ld(ValueError), (f'y_true and y_pred do not have compatible shapes: {ag__.ld(y_true).shape} and {ag__.ld(y_pred).shape}. Respective types are {ag__.converted_call(ag__.ld(type), (ag__.ld(y_true),), None, fscope)} and {ag__.converted_call(ag__.ld(type), (ag__.ld(y_pred),), None, fscope)}',), None, fscope)

ValueError: in user code:

    File "/home/xxxyyy/miniconda/envs/my_env_name/lib/python3.9/site-packages/keras/engine/training.py", line 1160, in train_function  *
        return step_function(self, iterator)
    File "/tmp/ipykernel_36702/144245855.py", line 13, in mean_absolute_error_na  *
        y_true_m, y_pred_m = remove_items_missing_observations(y_true, y_pred)
    File "/tmp/ipykernel_36702/144245855.py", line 8, in remove_items_missing_observations  *
        raise ValueError(f"y_true and y_pred do not have compatible shapes: {y_true.shape} and {y_pred.shape}. Respective types are {type(y_true)} and {type(y_pred)}")

    ValueError: y_true and y_pred do not have compatible shapes: (None, None) and (16, 1). Respective types are <class 'tensorflow.python.framework.ops.Tensor'> and <class 'tensorflow.python.framework.ops.Tensor'>
```
</details>

**Comment by tilakrayal** [comment]
@jmp75,
To work in Graph mode, Please remove or comment out the raise **ValueError()** and code works without any issue.  Under the  Graph mode TF automatically creates placeholders for the None shapes and it is an intended behaviour. 
Please refer to attached gist [here](https://colab.research.google.com/gist/tilakrayal/15d3b2c468b8b578732f11fc5f4db3f0/58258.ipynb).  Thank you!

**Comment by jmp75** [comment]
Thank you for this, I'll study this and communicate to colleagues.
