### ISSUE TITLE
TF built from source produces different XLA compiler results

### ISSUE THREAD

**Issue by pranavladkat** [tensorflow/tensorflow#58310]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

xla

### Source

source

### Tensorflow Version

tf.__git_version__ = v2.10.0-rc3-6-g359c3cdfc5f

### Custom Code

No

### OS Platform and Distribution

Linux

### Python version

3.9

### Bazel version

5.3.0

### GCC/Compiler version

gcc (GCC) 7.3.1

### CUDA/cuDNN version

Cuda 11.8, cudnn 8.6

### GPU model and memory

Nvidia A100, 40gb

### Current Behaviour?

```shell
I'm seeing different XLA compiler output when I use the prebuilt binaries and when I built the tensorflow from source.

I followed the steps outlines here (https://www.tensorflow.org/install/source#install_gpu_support_optional_linux_only) to built the tf from source. Specifically I ran following commands to build tf from source:


$ git clone tensorflow
$ ./configure
$ bazelisk build --config=cuda --config=opt  //tensorflow/tools/pip_package:build_pip_package --verbose_failures
$ ./bazel-bin/tensorflow/tools/pip_package/build_pip_package --nightly_flag /tmp/tensorflow_pkg
$ pip install ./tf_nightly-2.12.0-cp39-cp39-linux_x86_64.whl
```

The code pasted below runs as expected with prebuilt binaries (tested with 2.10, 2.11.rc1, tf_nightly) and produces desired output (please see output below), however the tensorflow built from source gives several errors while compiling graph using XLA. I failed to understand why I get different results when I compile from source and what can I change to get same output as prebuilt binaries.

I need to upgrade cudnn library dependency (during compile time) in order to support `conv2d` op with `bfloat16` dtype. The binaries vended through pip are compiled with cudnn 8.1 and do not support this use case.
```


### Standalone code to reproduce the issue

```shell
I used following example to reproduce the issue. (The script does not use conv2d layer, hence it works as expected with prebuilt binaries.) 



import argparse
import gzip
import numpy
import os
import struct
import urllib.request
import numpy as np
import sys
import os
import time
import tensorflow as tf
import random


print(f"tf.__file__ = {tf.__file__}, tf.__git_version__ = {tf.__git_version__}")

tf.keras.mixed_precision.set_global_policy('bfloat16')

# to achieve reproduceable numbers on GPU, please install: `pip install tensorflow-determinism`
# https://github.com/NVIDIA/framework-determinism
os.environ['TF_DETERMINISTIC_OPS'] = '1'


def download_file(url, dir,  rank=0):
    filename = dir + "/" + url.split('/')[-1]
    if not os.path.exists(filename):
        if rank == 0:
            # only rank 0 downloads the file
            print(f"Downloading {url} to {filename}")
            urllib.request.urlretrieve(url, filename)
    return filename


def extract_images(filename):
    with gzip.open(filename, 'rb') as f:
        magic = struct.unpack(">i", f.read(4))[0]  # convert to little endian
        if magic != 2051:
            raise ValueError(f'Invalid magic number {magic} in MNIST image file: {filename}')
        num_images = struct.unpack(">i", f.read(4))[0]  # convert to little endian
        num_rows = struct.unpack(">i", f.read(4))[0]  # convert to little endian
        num_cols = struct.unpack(">i", f.read(4))[0]  # convert to little endian
        buf = f.read(num_rows * num_cols * num_images)
        data = numpy.frombuffer(buf, dtype=numpy.uint8)
        data = data.reshape(num_images, num_rows, num_cols)
        return data


def extract_labels(filename):
    with gzip.open(filename, 'rb') as f:
        magic = struct.unpack(">i", f.read(4))[0]  # convert to little endian
        if magic != 2049:
            raise ValueError(f'Invalid magic number {magic} in MNIST image file: {filename}')
        num_images = struct.unpack(">i", f.read(4))[0]  # convert to little endian
        buf = f.read(num_images)
        data = numpy.frombuffer(buf, dtype=numpy.uint8)
        data = data.reshape(num_images)
        return data


def flatten_normalize_images(data):
    assert data.shape[1] == 28 and data.shape[2] == 28
    data = data.reshape(data.shape[0], data.shape[1] * data.shape[2])
    output = numpy.array(data, dtype=numpy.float32)
    output = (output - 128.)/128.
    return output


def read_mnist_dataset(rank=0, size=1, local_rank=0, data_dir='/tmp/tensorflow/mnist/input_data'):
    """
    Downloads and extracts mnist dataset and returns data in numpy format
    """
    # yann.lecun.com website oftens report 503 http error
    # train_image_url = 'http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz'
    # train_label_url = 'http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz'
    # test_image_url = 'http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz'
    # test_label_url = 'http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz'
    train_image_url = 'https://ossci-datasets.s3.amazonaws.com/mnist/train-images-idx3-ubyte.gz'
    train_label_url = 'https://ossci-datasets.s3.amazonaws.com/mnist/train-labels-idx1-ubyte.gz'
    test_image_url = 'https://ossci-datasets.s3.amazonaws.com/mnist/t10k-images-idx3-ubyte.gz'
    test_label_url = 'https://ossci-datasets.s3.amazonaws.com/mnist/t10k-labels-idx1-ubyte.gz'

    if local_rank == 0:
        if not os.path.exists(data_dir):
            os.makedirs(data_dir)

    train_image_filename = download_file(train_image_url, data_dir, local_rank)
    train_label_filename = download_file(train_label_url, data_dir, local_rank)
    test_image_filename = download_file(test_image_url, data_dir, local_rank)
    test_label_filename = download_file(test_label_url, data_dir, local_rank)

    train_images = extract_images(train_image_filename)
    train_labels = extract_labels(train_label_filename)
    test_images = extract_images(test_image_filename)
    test_labels = extract_labels(test_label_filename)

    # filter data such that, first sample is picked from row with index `rank` and next samples are offsets of `size`
    train_images = train_images[rank::size]
    train_labels = train_labels[rank::size]
    test_images = test_images[rank::size]
    test_labels = test_labels[rank::size]
    return (train_images, train_labels), (test_images, test_labels)


@tf.function(jit_compile=True)
def training_step(model, loss, tape, opt, images, labels):
    with tape:
        probs = model(images, training=True)
        print(f"labels = {labels.shape}, probs = {probs.shape}")
        loss_value = loss(labels, probs)
    grads = tape.gradient(loss_value, model.trainable_variables)
    opt.apply_gradients(zip(grads, model.trainable_variables))
    return loss_value


# @tf.function
# def run_eval(model, test_dataset):
#     num_correct = 0
#     for (images, labels) in test_dataset:
#         logits = model(images)
#         correct = tf.equal(tf.argmax(logits, 1), labels)
#         num_correct += tf.reduce_sum(tf.cast(correct, tf.int32))
#     return num_correct


def main(_):
    print(f"Tensorflow version : {tf.__version__}")
    # get rank and size of current process
    rank = 0
    size = 1
    local_rank = 0
    # select unique gpu
    gpus = tf.config.experimental.list_physical_devices('GPU')
    if gpus:
        device_id = local_rank
        tf.config.experimental.set_visible_devices(gpus[device_id], 'GPU')
        tf.config.experimental.set_memory_growth(gpus[device_id], True)
    # set random seed for consistent initialization of weights
    tf.random.set_seed(args.seed)
    np.random.seed(args.seed)
    random.seed(args.seed)

    (x_train, y_train), (x_test, y_test) = read_mnist_dataset(rank, size, local_rank, args.data_dir)

    # flatten and normalize images
    x_train = flatten_normalize_images(x_train)
    x_test = flatten_normalize_images(x_test)
    # convert labels to int64
    y_train = y_train.astype(np.int64)
    y_test = y_test.astype(np.int64)

    # training dataset
    print(f"batch size: {args.batch_size}")
    train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))
    train_dataset = train_dataset.batch(args.batch_size)
    # test dataset
    test_dataset = tf.data.Dataset.from_tensor_slices((x_test, y_test)).batch(10000)

    mnist_model = tf.keras.Sequential([
        tf.keras.Input(shape=(28*28,)),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dense(32, activation='relu'),
        tf.keras.layers.Dense(10, activation='softmax')
    ])

    # # set model weights using numpy to ensure repeatability
    # weights = mnist_model.get_weights()
    # weights[:] = [np.random.normal(scale=1.0 / math.sqrt(float(w.shape[0])), size=w.shape).astype('float32')
    #               for w in weights]
    # for w in weights:
    #     if len(w.shape) == 1:
    #         # zero out baises
    #         w.fill(0.)
    # mnist_model.set_weights(weights)

    loss = tf.losses.SparseCategoricalCrossentropy()
    # loss = tf.losses.CategoricalCrossentropy()
    tape = tf.GradientTape()
    opt = tf.optimizers.SGD(0.01 * size)

    step = 0
    total_time_start = time.time()
    for epoch in range(1, int(args.num_epochs)+1):
        epoch_time_start = time.time()
        # train
        for (images, labels) in train_dataset:
            loss_value = training_step(mnist_model, loss, tape, opt, images, labels)
            loss_value = tf.cast(loss_value, tf.float32)
            if step == 0:
                for weight in mnist_model.trainable_variables:
                    print(f"weight name = {weight.name}, dtype = {weight.dtype}")
            if step % 50 == 0 and rank == 0:
                print(f"Epoch {epoch} Step #{step} \tLoss: {loss_value:.6f}")
            step += 1
        epoch_time_end = time.time()
        # if rank == 0:
        #     correct_count = run_eval(mnist_model, test_dataset)
        #     print(f"Epoch {epoch} Eval accuracy {float(correct_count)/10000.0*100.0:.2f}% \t"
        #           f"epoch time = {epoch_time_end - epoch_time_start:.3f}s")

    total_time_end = time.time()
    if rank == 0:
        print(f"Execution time: {(total_time_end - total_time_start):.3f}s")


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--data-dir', type=str, help='Directory for storing input data',
                        dest="data_dir", default='/tmp/tensorflow/mnist/input_data')
    parser.add_argument('--batch-size', type=int, help='batch size used for training',
                        dest="batch_size", default=128)
    parser.add_argument('--seed', type=int, help='random seed', dest="seed", default=17)
    parser.add_argument('--num-epochs', type=int, help='Number of epochs', dest="num_epochs", default=1)
    parser.set_defaults(enable_chkpt=False)
    args, unparsed = parser.parse_known_args()

    main([sys.argv[0]] + unparsed)

```
```


### Relevant log output

```shell
Output with tensorflow built from source:


$ python example.py
2022-10-25 17:58:24.444147: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
tf.__file__ = /home/ec2-user/workspace/tensorflow/tensorflow/__init__.py, tf.__git_version__ = v1.12.1-83529-g3e25aa44bcc
Tensorflow version : 2.12.0
batch size: 128
2022-10-25 17:58:29.400442: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-25 17:58:30.151968: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1614] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 38210 MB memory:  -> device: 0, name: NVIDIA A100-SXM4-40GB, pci bus id: 0000:10:1c.0, compute capability: 8.0
labels = (128,), probs = (128, 10)
Traceback (most recent call last):
  File "/home/ec2-user/workspace/Radiate/Radiate/examples/tf_mnist_xla.py", line 216, in <module>
    main([sys.argv[0]] + unparsed)
  File "/home/ec2-user/workspace/Radiate/Radiate/examples/tf_mnist_xla.py", line 186, in main
    loss_value = training_step(mnist_model, loss, tape, opt, images, labels)
  File "/home/ec2-user/workspace/tensorflow/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/tmp/__autograph_generated_filefhbvrr0s.py", line 13, in tf__training_step
    loss_value = ag__.converted_call(ag__.ld(loss), (ag__.ld(labels), ag__.ld(probs)), None, fscope)
  File "/home/ec2-user/workspace/tensorflow/keras/losses.py", line 151, in __call__
    losses = call_fn(y_true, y_pred)
  File "/home/ec2-user/workspace/tensorflow/keras/losses.py", line 271, in call
    return ag_fn(y_true, y_pred, **self._fn_kwargs)
  File "/home/ec2-user/workspace/tensorflow/keras/losses.py", line 2085, in sparse_categorical_crossentropy
    return backend.sparse_categorical_crossentropy(
  File "/home/ec2-user/workspace/tensorflow/keras/backend.py", line 5633, in sparse_categorical_crossentropy
    res = tf.nn.sparse_softmax_cross_entropy_with_logits(
ValueError: in user code:

    File "/home/ec2-user/workspace/Radiate/Radiate/examples/tf_mnist_xla.py", line 109, in training_step  *
        loss_value = loss(labels, probs)
    File "/home/ec2-user/workspace/tensorflow/keras/losses.py", line 151, in __call__  **
        losses = call_fn(y_true, y_pred)
    File "/home/ec2-user/workspace/tensorflow/keras/losses.py", line 271, in call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "/home/ec2-user/workspace/tensorflow/keras/losses.py", line 2085, in sparse_categorical_crossentropy
        return backend.sparse_categorical_crossentropy(
    File "/home/ec2-user/workspace/tensorflow/keras/backend.py", line 5633, in sparse_categorical_crossentropy
        res = tf.nn.sparse_softmax_cross_entropy_with_logits(

    ValueError: Unexpected input_shape with unknown rank for '{{node sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/strided_slice}} = StridedSlice[Index=DT_INT32, T=DT_INT32, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1](sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/Shape_2, sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/strided_slice/stack, sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/strided_slice/stack_1, sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/strided_slice/stack_2)' with input shapes: [2], [1], [1], [1] and with computed input tensors: input[3] = <1>.
```

Output with prebuilt tensorflow:

```
$ python example.py
 2022-10-25 17:57:57.978782: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
 To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
 2022-10-25 17:57:58.134458: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
 2022-10-25 17:57:58.638380: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/amazon/openmpi/lib:/opt/amazon/efa/lib64:/opt/amazon/openmpi/lib64:/usr/local/cuda/efa/lib:/usr/local/cuda/lib:/usr/local/cuda:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/targets/x86_64-linux/lib:/usr/local/lib:/usr/lib:/lib:
 2022-10-25 17:57:58.638468: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/amazon/openmpi/lib:/opt/amazon/efa/lib64:/opt/amazon/openmpi/lib64:/usr/local/cuda/efa/lib:/usr/local/cuda/lib:/usr/local/cuda:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/targets/x86_64-linux/lib:/usr/local/lib:/usr/lib:/lib:
 2022-10-25 17:57:58.638476: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
 tf.__file__ = /usr/local/lib/python3.9/site-packages/tensorflow/__init__.py, tf.__git_version__ = v2.10.0-rc3-6-g359c3cdfc5f
 Tensorflow version : 2.10.0
 batch size: 128
 2022-10-25 17:58:02.897929: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
 To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
 2022-10-25 17:58:03.600789: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 38224 MB memory:  -> device: 0, name: NVIDIA A100-SXM4-40GB, pci bus id: 0000:10:1c.0, compute capability: 8.0
 2022-10-25 17:58:04.567559: I tensorflow/compiler/xla/service/service.cc:173] XLA service 0x20510010 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
 2022-10-25 17:58:04.567586: I tensorflow/compiler/xla/service/service.cc:181]   StreamExecutor device (0): NVIDIA A100-SXM4-40GB, Compute Capability 8.0
 2022-10-25 17:58:04.581599: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
 2022-10-25 17:58:05.091994: I tensorflow/compiler/jit/xla_compilation_cache.cc:476] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
 weight name = dense/kernel:0, dtype = <dtype: 'bfloat16'>
 weight name = dense/bias:0, dtype = <dtype: 'bfloat16'>
 weight name = dense_1/kernel:0, dtype = <dtype: 'bfloat16'>
 weight name = dense_1/bias:0, dtype = <dtype: 'bfloat16'>
 weight name = dense_2/kernel:0, dtype = <dtype: 'bfloat16'>
 weight name = dense_2/bias:0, dtype = <dtype: 'bfloat16'>
 Epoch 1 Step #0        Loss: 2.765625
 Epoch 1 Step #50       Loss: 1.531250
 Epoch 1 Step #100      Loss: 1.039062
 Epoch 1 Step #150      Loss: 0.945312
 Epoch 1 Step #200      Loss: 0.656250
 Epoch 1 Step #250      Loss: 0.652344
 Epoch 1 Step #300      Loss: 0.566406
 Epoch 1 Step #350      Loss: 0.710938
 Epoch 1 Step #400      Loss: 0.679688
 Epoch 1 Step #450      Loss: 0.582031
 Execution time: 3.818s
```
```
</details>

**Comment by bhack** [comment]
Have you already tryied to compile from the `nightly` git branch just to be sure to be on the same commit as the last nightly wheel?

**Comment by mohantym** [comment]
Hi @pranavladkat !

Please use "git checkout master" while building from source and use  "pip install tf-nightly" to install latest binary to see the  difference on same commit .

Thank you!

**Comment by bhack** [comment]
> Please use "git checkout master" ..

Do you meant `git checkout nightly`? As that branch is required to be position on the same commit as the nightly wheels.

**Comment by mohantym** [comment]
@bhack !
Sorry! I meant "git checkout nightly " and "pip install tf-nightly" . Thanks for correcting me.
Thank you!

**Comment by pranavladkat** [comment]
Thank you for the reply. I retried the above steps with latest nightly build and cherry-picking exact same commit  (e.g. in this case, `git checkout 8aa3c875bb1`) to build from source and I still see the same error as posted in issue description.

```
# git version for nightly build
tf.__git_version__ = v2.11.0-rc0-5-g8aa3c875bb1

# git version for build from source (when checked out exact same command as prebuilt nightly)
tf.__git_version__ = v2.11.0-rc1-0-g8aa3c875bb1

# git version for build from source of `nightly` branch
tf.__git_version__ = v1.12.1-83506-gf14bcf2d49a
``` 

I followed these exact steps to build from source:
```
$ git checkout 8aa3c875bb1
$ bazelisk build --config=cuda --config=opt  //tensorflow/tools/pip_package:build_pip_package --verbose_failures
$ ./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg ~/workspace/tensorflow/ --gpu --nightly_flag
$ pip install ./tf_nightly_gpu-2.11.0rc1-cp39-cp39-linux_x86_64.whl
```

**Comment by mohantym** [comment]
ok @pranavladkat !
Thanks for sharing your observations.

@sushreebarsa !
Could you look at this issue.

Thank you!

**Comment by pranavladkat** [comment]
Hi,

Is there any progress on this issue?

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
