### ISSUE TITLE
CHECK fail in `tf.raw_ops.ResourceGather` when `dtype` value is mismatch with dtype value of `indices`

### ISSUE THREAD

**Issue by jdanceze** [tensorflow/tensorflow#58315]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.10

### Custom Code

No

### OS Platform and Distribution

Ubuntu 20.04.4 LTS

### Python version

3.8

### Current Behaviour?

```shell
When passing `dtype` value to `tf.raw_ops.ResourceGather` that is not match with the dtype value of `indices`, it will trigger Aborted (core dumped) cause the program termination.
```

### Standalone code to reproduce the issue

```shell
from tensorflow.python.eager import context
import tensorflow as tf


input1 = tf.raw_ops.VarHandleOp(dtype=tf.int32, shape=[2, 3], shared_name=context.anonymous_name())
indice = tf.ones(dtype=tf.int32, shape=[1, 0])

tf.raw_ops.ResourceGather(resource=input1,indices=indice,dtype=tf.bool)
```

### Relevant log output

```shell
2022-10-26 02:57:29.368524: F tensorflow/core/framework/tensor.cc:719] Check failed: dtype() == expected_dtype (3 vs. 10) bool expected, got int32
--Type <RET> for more, q to quit, c to continue without paging--bt 10

Thread 1 "python" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt 10
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f175fc14859 in __GI_abort () at abort.c:79
#2  0x00007f1746aaac5c in tensorflow::internal::LogMessageFatal::~LogMessageFatal (this=0x7ffe3a2ccf90, 
    __in_chrg=<optimized out>, __vtt_parm=<optimized out>) at tensorflow/core/platform/default/logging.cc:375
#3  0x00007f171b4ef733 in tensorflow::Tensor::CheckType (this=0x1465150, expected_dtype=tensorflow::DT_BOOL)
    at tensorflow/core/framework/tensor.cc:719
#4  0x00007f173823a0ae in tensorflow::Tensor::shaped<bool, 1ul> (this=0x1465150, new_sizes=...)
    at ./tensorflow/core/framework/tensor.h:890
#5  0x00007f1738239660 in tensorflow::Tensor::flat<bool> (this=0x1465150) at ./tensorflow/core/framework/tensor.h:564
#6  0x00007f173ccf9361 in tensorflow::Status tensorflow::EnsureSparseVariableAccess<Eigen::ThreadPoolDevice, bool>(tensorflow::OpKernelContext*, tensorflow::Var*) ()
   from /usr/local/lib/python3.8/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#7  0x00007f173cccf684 in tensorflow::ResourceGatherOp<Eigen::ThreadPoolDevice, bool, long>::Compute(tensorflow::OpKernelContext*) () from /usr/local/lib/python3.8/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#8  0x00007f171b7eac82 in tensorflow::ThreadPoolDevice::Compute (this=0x3e4ed40, op_kernel=0x50bf030, context=0x7ffe3a2cda40)
    at tensorflow/core/common_runtime/threadpool_device.cc:184
#9  0x00007f171b69709c in tensorflow::(anonymous namespace)::SingleThreadedExecutorImpl::Run (this=0x50ce2c0, args=...)
    at tensorflow/core/common_runtime/single_threaded_executor.cc:445
```
</details>

**Comment by tilakrayal** [comment]
@jdanceze,
Could you please take a look at this comment and also I tried to execute the mentioned code on alternative appraoch and was executed without any issue/error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/755b0da14d27fb238785305c9b2020d0/untitled714.ipynb). Thank you!

**Comment by bhack** [comment]
@tilakrayal Please check internally with the teams how we need to handle assert issues on raw ops after we have declassified these as security bugs.

Cause in the last few days we had many tickets like this one.

**Comment by jdanceze** [comment]
@tilakrayal according to your colab, the crash will only trigger when dtype in `tf.raw_ops.ResourceGather`  is not match with dtype of `indice`. Hence, if both dtype is `tf.int32`, it will not trigger crash.

**Comment by JW1992** [comment]
@jdanceze using your code snippet I got error "InvalidArgumentError: Value for attr 'Tindices' of resource is not in the list of allowed values: int32, int64" instead of the "Check failed" in tensor.cc.

Did you intend to use the following example instead? (notice I swapped the definition of `input`` and `indice`)
```
from tensorflow.python.eager import context
import tensorflow as tf


input1 = tf.raw_ops.VarHandleOp(dtype=tf.int32, shape=[2, 3], shared_name=context.anonymous_name())
indice = tf.ones(dtype=tf.int32, shape=[1, 0])

tf.raw_ops.ResourceGather(resource=input1,indices=indice,dtype=tf.bool)
```

**Comment by jdanceze** [comment]
@JW1992 Yes, I made the mistake in my code snippet. The crash used to be reproduced from your snippet.

**Comment by sushreebarsa** [comment]
@jdanceze Could you please confirm if this is still an issue ?
Thank you!
