### ISSUE TITLE
Failed to build TF with ROCm >=5.2

### ISSUE THREAD

**Issue by njzjz** [tensorflow/tensorflow#58348]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

TF 2.10

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04.4 LTS

### Python version

3.8.10

### Bazel version

5.3.0

### GCC/Compiler version

9.4.0

### GPU model and memory

AMD MI210

### Current Behaviour?

When I build TF from source with ROCm 5.3.0, the error happens:

```
ERROR: An error occurred during the fetch of repository 'local_config_rocm':
   Traceback (most recent call last):
	File "/global/home/jzzeng/packages/tensorflow/tensorflow-2.10/third_party/gpus/rocm_configure.bzl", line 869, column 38, in _rocm_autoconf_impl
		_create_local_rocm_repository(repository_ctx)
	File "/global/home/jzzeng/packages/tensorflow/tensorflow-2.10/third_party/gpus/rocm_configure.bzl", line 547, column 35, in _create_local_rocm_repository
		rocm_config = _get_rocm_config(repository_ctx, bash_bin, find_rocm_config_script)
	File "/global/home/jzzeng/packages/tensorflow/tensorflow-2.10/third_party/gpus/rocm_configure.bzl", line 395, column 30, in _get_rocm_config
		config = find_rocm_config(repository_ctx, find_rocm_config_script)
	File "/global/home/jzzeng/packages/tensorflow/tensorflow-2.10/third_party/gpus/rocm_configure.bzl", line 373, column 41, in find_rocm_config
		exec_result = _exec_find_rocm_config(repository_ctx, script_path)
	File "/global/home/jzzeng/packages/tensorflow/tensorflow-2.10/third_party/gpus/rocm_configure.bzl", line 369, column 19, in _exec_find_rocm_config
		return execute(repository_ctx, [python_bin, "-c", decompress_and_execute_cmd])
	File "/global/home/jzzeng/packages/tensorflow/tensorflow-2.10/third_party/remote_config/common.bzl", line 230, column 13, in execute
		fail(
Error in fail: Repository command failed

A bug happened!ERROR: #define "ROCRAND_VERSION" is either
not present in file /global/software/rocm/rocm-5.3.0/rocrand/include/rocrand_version.h OR
its value is not an integer literal
```

`/global/software/rocm/rocm-5.3.0/rocrand/include/rocrand_version.h` gives:

```
/*
    Copyright (c) 2022 Advanced Micro Devices, Inc. All rights reserved.
*/

#ifndef ROCM_WRAPPER_ROCRAND_VERSION_H
#define ROCM_WRAPPER_ROCRAND_VERSION_H

#if defined(ROCM_NO_WRAPPER_HEADER_WARNING) || defined(ROCM_WRAPPER_GAVE_WARNING)
/* include file */
#include "../../include/rocrand/rocrand_version.h"
#else
/* give warning */
#if defined(_MSC_VER)
#pragma message(": warning:This file is deprecated. Use the header file from /opt/rocm-5.3.0/include/rocrand/rocrand_version.h by using #include <rocrand/rocrand_version.h>")
#elif defined(__GNUC__)
#pragma message(": warning : This file is deprecated. Use the header file from /opt/rocm-5.3.0/include/rocrand/rocrand_version.h by using #include <rocrand/rocrand_version.h>")
#endif
/* include file */
#define ROCM_WRAPPER_GAVE_WARNING
#include "../../include/rocrand/rocrand_version.h"
#undef ROCM_WRAPPER_GAVE_WARNING
#endif /* defined(ROCM_NO_WRAPPER_HEADER_WARNING) || defined(ROCM_WRAPPER_GAVE_WARNING) */

#endif /* ROCM_WRAPPER_ROCRAND_VERSION_H */
```

So in ROCm >=5.2, the version should be read from `include/rocrand/rocrand_version.h` instead of `rocrand/include/rocrand_version.h`. It looks that TensorFlow does not handle this thing.

Note that in ROCm 5.1, `rocrand/include/rocrand_version.h` does have version information.

### Standalone code to reproduce the issue

```shell
Build from source against ROCm >=5.2
```

### Relevant log output

_No response_</details>

**Comment by bhack** [comment]
https://github.com/tensorflow/tensorflow/pull/56762

**Comment by sushreebarsa** [comment]
@njzjz Could you check the PR mentioned above and let us know if it helped ?
Thank you!
