### ISSUE TITLE
'ValueError: Graph already contains one or more main ops under the collection saved_model_main_op'. this error occurred When `add_meta_graph_and_variables` method is called more than once, with argument `main_op`

### ISSUE THREAD

**Issue by H-Yin** [tensorflow/tensorflow#58364]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 1.15

### Custom Code

No

### OS Platform and Distribution

CentOS Linux release 7.7.1908

### Python version

3.7.6

### CUDA/cuDNN version

10.1

### Current Behaviour?

```shell
A bug happened!
```

### Standalone code to reproduce the issue

```shell
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

import shutil
import tensorflow as tf
import tensorflow.compat.v1 as tf1
tf1.logging.set_verbosity(tf1.logging.ERROR)
print(tf.__version__)

export_dir = 'res/model'
name = tf1.placeholder(tf.string, name='name')
name_vocab_initializer = tf.lookup.KeyValueTensorInitializer(tf.constant(['a', 'b', 'c']), tf.constant([1, 2, 3]),)
name_vocab_table = tf.lookup.StaticHashTable(name_vocab_initializer, 0)
name_index = name_vocab_table.lookup(name)

name_emb_table = tf1.get_variable('name_emb_table', dtype=tf.float32, shape=[5, 5])
name_emb = tf.nn.embedding_lookup(name_emb_table, name_index, name='name_emb')
# training stage
with tf1.Session() as sess:
    sess.run(tf1.global_variables_initializer())
    sess.run(tf1.tables_initializer())
    print(sess.run(name_emb, feed_dict={name : ['a', 'b', 'c']}))
    # Saving a better model is a common operation in training stage, then simulate this scenario with iteration
    for _ in range(10):
        shutil.rmtree(export_dir, ignore_errors=True)
        builder = tf1.saved_model.builder.SavedModelBuilder(export_dir)
        predict_signature = tf1.saved_model.signature_def_utils.build_signature_def(
            inputs={
                'input' : tf1.saved_model.utils.build_tensor_info(name)
            },
            outputs={
                'output' : tf1.saved_model.utils.build_tensor_info(name_emb)
            },
            method_name=tf1.saved_model.signature_constants.PREDICT_METHOD_NAME
        )
        builder.add_meta_graph_and_variables(
            sess,
            [tf.saved_model.SERVING],
            signature_def_map = {
                tf1.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY: predict_signature
            },
            main_op = tf.tables_initializer()
        )
        builder.save()

# inference stage
with tf1.Session() as sess:
    tf1.saved_model.loader.load(sess, [tf.saved_model.SERVING], export_dir)
    name = sess.graph.get_tensor_by_name('name:0')
    name_emb = sess.graph.get_tensor_by_name('name_emb:0')
    res = sess.run(name_emb, feed_dict={
        name : ['a', 'b', 'c']
    })
    print(res)
```

### Relevant log output

```shell
1.15.5
[[-0.61052984 -0.07456124  0.5581994   0.04198807 -0.49397054]
 [ 0.53618276  0.18003893  0.01871365 -0.4160051  -0.43389118]
 [ 0.01618445 -0.04085767 -0.3247591  -0.6272572  -0.75671464]]
Traceback (most recent call last):
  File "test_main_op.py", line 43, in <module>
    main_op = tf.tables_initializer()
  File "/data/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/data/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/saved_model/builder_impl.py", line 585, in add_meta_graph_and_variables
    self._add_collections(assets_collection, main_op, None)
  File "/data/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/saved_model/builder_impl.py", line 443, in _add_collections
    self._maybe_add_main_op(main_op)
  File "/data/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/saved_model/builder_impl.py", line 490, in _maybe_add_main_op
    "collection {}.".format(init_op_key))
ValueError: Graph already contains one or more main ops under the collection saved_model_main_op.
```
</details>

**Comment by tilakrayal** [comment]
@H-Yin,
Tensorflow version 1.x is not actively supported. Hence, kindly update to the latest stable version 2.10 and let us know if you are facing the same issue. Thank you!
