### ISSUE TITLE
High Batch Size Exceeds Memory

### ISSUE THREAD

**Issue by MarkKocherovsky** [tensorflow/tensorflow#58373]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Source

source

### Tensorflow Version

tf 2.10

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 22.04

### Python version

3.10

### CUDA/cuDNN version

11.8

### GPU model and memory

NVIDIA GTX 1080Ti

### Current Behaviour?

```shell
I'm trying to train a model on a large dataset (not a tf dataset) with a batch size of 1500. Linux then reports that the allocation exceeds available memory:
```

### Standalone code to reproduce the issue

```shell
from keras.layers.core import Dense, Dropout, Activation
from tensorflow.keras import optimizers, models, layers, callbacks

def build_classifier_model():
    text_input = tf.keras.layers.Input(shape = (), dtype = tf.string, name = 'text')
    preprocessing_layer = hub.KerasLayer(tfhub_handle_preprocess, name = 'preprocessing')
    encoder_inputs = preprocessing_layer(text_input)
    encoder = hub.KerasLayer(tfhub_handle_encoder, trainable=True, name='BERT_encoder')
    outputs = encoder(encoder_inputs)
    net = outputs['pooled_output']
    net = Dropout(0.1)(net)
    net = Dense(1024, activation = 'relu', name = 'hidde')(net)
    net = Dense(256, activation = 'relu', name = 'hidden')(net)
    net = Dense(256, activation = 'relu', name = 'hidden_')(net)
    net = Dense(128, activation = 'relu', name = 'hidden_l')(net)
    net = Dense(64, activation = 'relu', name = 'hidden_la')(net)
    net = Dense(64, activation = 'relu', name = 'hidden_lay')(net)
    net = Dense(16, activation = 'relu', name = 'hidden_laye')(net)
    net = Dense(3, activation='softmax', name='output')(net)
    return tf.keras.Model(text_input, net)
    
def load_callbacks(patience_num, filename):
  return [
    callbacks.EarlyStopping(
        monitor = 'val_loss',
        patience = patience_num
    ),
    callbacks.ModelCheckpoint(
        filepath = f'{filename}.h5',
        monitor = 'val_loss',
        save_best_only = True,
        verbose = 1
    )
  ]

loss = tf.keras.losses.CategoricalCrossentropy(from_logits = False)
metrics = tf.metrics.CategoricalAccuracy()
optimizer = optimizers.RMSprop(learning_rate = 0.001)
epochs = 5
batch_size = round(train_x.shape[0]/10)
batch_size = 1500

model = build_classifier_model()

model.compile(optimizer = optimizer, loss = loss, metrics = metrics)

print("Training:")
history = model.fit(x = train_x, y = train_y, epochs = epochs, validation_data = (val_x, val_y), callbacks = load_callbacks(10, 'model'), verbose = 1)
print("Testing:")
model.evaluate(test_x, test_y)
```
```


### Relevant log output

```shell
Epoch 1/5
2022-10-30 14:08:24.668673: W tensorflow/core/common_runtime/bfc_allocator.cc:479] Allocator (GPU_0_bfc) ran out of memory trying to allocate 375.00MiB (rounded to 393216000)requested by op model/BERT_encoder/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/bert_encoder/StatefulPartitionedCall/transformer/layer_0/self_attention/einsum_1/Einsum
If the cause is memory fragmentation maybe the environment variable 'TF_GPU_ALLOCATOR=cuda_malloc_async' will improve the situation. 
Current allocation summary follows.
Current allocation summary follows.
2022-10-30 14:08:24.668778: I tensorflow/core/common_runtime/bfc_allocator.cc:1033] BFCAllocator dump for GPU_0_bfc
2022-10-30 14:08:24.668825: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (256): 	Total Chunks: 90, Chunks in use: 89. 22.5KiB allocated for chunks. 22.2KiB in use in bin. 2.7KiB client-requested in use in bin.
2022-10-30 14:08:24.668864: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (512): 	Total Chunks: 3, Chunks in use: 3. 1.5KiB allocated for chunks. 1.5KiB in use in bin. 1.5KiB client-requested in use in bin.
2022-10-30 14:08:24.668900: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (1024): 	Total Chunks: 7, Chunks in use: 7. 7.2KiB allocated for chunks. 7.2KiB in use in bin. 7.0KiB client-requested in use in bin.
2022-10-30 14:08:24.668938: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (2048): 	Total Chunks: 162, Chunks in use: 162. 326.5KiB allocated for chunks. 326.5KiB in use in bin. 324.0KiB client-requested in use in bin.
2022-10-30 14:08:24.668976: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (4096): 	Total Chunks: 10, Chunks in use: 10. 40.8KiB allocated for chunks. 40.8KiB in use in bin. 40.0KiB client-requested in use in bin.
...
2022-10-30 14:08:24.676197: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5492170d00 of size 32768 next 421
2022-10-30 14:08:24.676243: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5492178d00 of size 256 next 422
2022-10-30 14:08:24.676291: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] Free  at 7f5492178e00 of size 65565184 next 18446744073709551615
2022-10-30 14:08:24.676338: I tensorflow/core/common_runtime/bfc_allocator.cc:1069] Next region of size 2097152
2022-10-30 14:08:24.676387: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c00000 of size 256 next 1
2022-10-30 14:08:24.676433: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c00100 of size 1280 next 2
2022-10-30 14:08:24.676481: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c00600 of size 256 next 3
2022-10-30 14:08:24.676528: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c00700 of size 256 next 8
2022-10-30 14:08:24.676573: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c00800 of size 256 next 9
2022-10-30 14:08:24.676620: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c00900 of size 256 next 10
2022-10-30 14:08:24.676665: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c00a00 of size 256 next 11
2022-10-30 14:08:24.676711: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c00b00 of size 2048 next 13
2022-10-30 14:08:24.676759: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c01300 of size 2048 next 14
2022-10-30 14:08:24.676806: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c01b00 of size 2048 next 15
2022-10-30 14:08:24.676851: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c02300 of size 2048 next 18
2022-10-30 14:08:24.676898: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c02b00 of size 2048 next 20
2022-10-30 14:08:24.676944: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c03300 of size 2048 next 21
2022-10-30 14:08:24.676992: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c03b00 of size 2048 next 22
2022-10-30 14:08:24.677038: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c04300 of size 8192 next 23
2022-10-30 14:08:24.677085: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c06300 of size 2048 next 25
2022-10-30 14:08:24.677129: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c06b00 of size 2048 next 26
2022-10-30 14:08:24.677177: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c07300 of size 4096 next 27
2022-10-30 14:08:24.677222: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c08300 of size 2048 next 28
2022-10-30 14:08:24.677269: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c08b00 of size 2048 next 30
2022-10-30 14:08:24.677315: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c09300 of size 2048 next 32
2022-10-30 14:08:24.677361: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c09b00 of size 2048 next 34
2022-10-30 14:08:24.677406: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c0a300 of size 2048 next 35
2022-10-30 14:08:24.677483: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c0ab00 of size 2048 next 36
2022-10-30 14:08:24.677531: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c0b300 of size 2048 next 37
2022-10-30 14:08:24.677577: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c0bb00 of size 2048 next 38
2022-10-30 14:08:24.677621: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c0c300 of size 8192 next 41
2022-10-30 14:08:24.677666: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c0e300 of size 2048 next 43
2022-10-30 14:08:24.677711: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c0eb00 of size 2048 next 44
2022-10-30 14:08:24.677756: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c0f300 of size 2048 next 45
2022-10-30 14:08:24.677801: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c0fb00 of size 2048 next 47
2022-10-30 14:08:24.677846: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c10300 of size 2048 next 49
2022-10-30 14:08:24.677891: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c10b00 of size 2048 next 50
2022-10-30 14:08:24.677936: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c11300 of size 2048 next 52
2022-10-30 14:08:24.677981: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c11b00 of size 2048 next 54
2022-10-30 14:08:24.678026: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c12300 of size 2048 next 55
2022-10-30 14:08:24.678070: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c12b00 of size 2048 next 56
2022-10-30 14:08:24.678119: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c13300 of size 3328 next 6
2022-10-30 14:08:24.678161: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f5526c14000 of size 120064 next 7
2022-10-30 14:08:24.678198: I tensorflow/core
...
2022-10-30 14:08:24.698266: I tensorflow/core/common_runtime/bfc_allocator.cc:1097] 1 Chunks of size 1309184 totalling 1.25MiB
2022-10-30 14:08:24.698292: I tensorflow/core/common_runtime/bfc_allocator.cc:1097] 1 Chunks of size 1536000 totalling 1.46MiB
2022-10-30 14:08:24.698317: I tensorflow/core/common_runtime/bfc_allocator.cc:1097] 1 Chunks of size 1773056 totalling 1.69MiB
2022-10-30 14:08:24.698343: I tensorflow/core/common_runtime/bfc_allocator.cc:1097] 1 Chunks of size 1858816 totalling 1.77MiB
2022-10-30 14:08:24.698370: I tensorflow/core/common_runtime/bfc_allocator.cc:1097] 1 Chunks of size 2092544 totalling 2.00MiB
2022-10-30 14:08:24.698396: I tensorflow/core/common_runtime/bfc_allocator.cc:1097] 3 Chunks of size 2097152 totalling 6.00MiB
2022-10-30 14:08:24.698423: I tensorflow/core/common_runtime/bfc_allocator.cc:1097] 30 Chunks of size 4194304 totalling 120.00MiB
2022-10-30 14:08:24.698449: I tensorflow/core/common_runtime/bfc_allocator.cc:1097] 1 Chunks of size 4862976 totalling 4.64MiB
2022-10-30 14:08:24.698475: I tensorflow/core/common_runtime/bfc_allocator.cc:1097] 1 Chunks of size 5973760 totalling 5.70MiB
2022-10-30 14:08:24.698501: I tensorflow/core/common_runtime/bfc_allocator.cc:1097] 1 Chunks of size 6291456 totalling 6.00MiB
2022-10-30 14:08:24.698528: I tensorflow/core/common_runtime/bfc_allocator.cc:1097] 2 Chunks of size 62509056 totalling 119.23MiB
2022-10-30 14:08:24.698556: I tensorflow/core/common_runtime/bfc_allocator.cc:1097] 1 Chunks of size 67108864 totalling 64.00MiB
2022-10-30 14:08:24.698583: I tensorflow/core/common_runtime/bfc_allocator.cc:1097] 1 Chunks of size 143654912 totalling 137.00MiB
2022-10-30 14:08:24.698609: I tensorflow/core/common_runtime/bfc_allocator.cc:1097] 9 Chunks of size 393216000 totalling 3.30GiB
2022-10-30 14:08:24.698635: I tensorflow/core/common_runtime/bfc_allocator.cc:1097] 3 Chunks of size 786432000 totalling 2.20GiB
2022-10-30 14:08:24.698661: I tensorflow/core/common_runtime/bfc_allocator.cc:1101] Sum Total of in-use chunks: 6.03GiB
2022-10-30 14:08:24.698687: I tensorflow/core/common_runtime/bfc_allocator.cc:1103] total_region_allocated_bytes_: 7449870336 memory_limit_: 7449870336 available bytes: 0 curr_region_allocation_bytes_: 8589934592
2022-10-30 14:08:24.698723: I tensorflow/core/common_runtime/bfc_allocator.cc:1109] Stats: 
Limit:                      7449870336
InUse:                      6473138688
MaxInUse:                   6473138688
NumAllocs:                     1187339
MaxAllocSize:                786432000
Reserved:                            0
PeakReserved:                        0
LargestFreeBlock:                    0

2022-10-30 14:08:24.698838: W tensorflow/core/common_runtime/bfc_allocator.cc:491] *************************************_____***************************_************___***************
2022-10-30 14:08:24.698902: W tensorflow/core/framework/op_kernel.cc:1780] OP_REQUIRES failed at einsum_op_impl.h:598 : RESOURCE_EXHAUSTED: OOM when allocating tensor with shape[1500,128,8,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "/home/mark/Documents/NLP/naive/naive_2.py", line 314, in <module>
    history = model.fit(x = train_x, y = train_y, epochs = epochs, validation_data = (val_x, val_y), batch_size = batch_size, callbacks = load_callbacks(10, 'model'), verbose = 1)
  File "/home/mark/miniconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/mark/miniconda3/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.ResourceExhaustedError: Graph execution error:

OOM when allocating tensor with shape[1500,128,8,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node transformer/layer_0/self_attention/einsum_1/Einsum}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.
 [Op:__inference_train_function_286118]
```
```
</details>

**Comment by aliashori75** [comment]
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)

**Comment by SuryanarayanaY** [comment]
@MarkKocherovsky, 
Could you please use the below code to list out GPU devices first 
`physical_devices =tf.config.list_physical_devices('GPU')`
and then try to use below code to allow the Memory growth using
`tf.config.experimental.set_memory_growth(physical_devices[0], True)`
Please take a look at the official document for the [reference](https://www.tensorflow.org/api_docs/python/tf/config/experimental/set_memory_growth). 
Thankyou

**Comment by MarkKocherovsky** [comment]
I have the following code close to the top of the program:

```
gpus = tf.config.experimental.list_physical_devices('GPU')
print()
print(gpus)
print()
for gpu in gpus:
	tf.config.experimental.set_memory_growth(gpu, True)
```

Which returns the following log on startup
```
2022-10-31 12:49:01.926597: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-31 12:49:02.029534: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-10-31 12:49:02.489421: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.8/lib64::/home/mark/miniconda3/lib/
2022-10-31 12:49:02.489482: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.8/lib64::/home/mark/miniconda3/lib/
2022-10-31 12:49:02.489489: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2022-10-31 12:49:03.163230: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-31 12:49:03.183179: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-31 12:49:03.183339: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

Getting Data
2022-10-31 12:49:03.188100: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-31 12:49:03.188701: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-31 12:49:03.188839: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-31 12:49:03.188943: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-31 12:49:03.558822: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-31 12:49:03.559003: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-31 12:49:03.559168: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-31 12:49:03.559280: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 7011 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1
```

**Comment by SuryanarayanaY** [comment]
Hi @MarkKocherovsky,
At present TF2.10 actively supports CUDA versions upto 11.2 .Please refer tested configurations [here](https://www.tensorflow.org/install/source#gpu).
I request you to please try tested configurations as per [tensorflow official documenation ](https://www.tensorflow.org/install/source).

**Comment by MarkKocherovsky** [comment]
So should I manually downgrade to 11.2?

**Comment by SuryanarayanaY** [comment]
Hi @MarkKocherovsky ,
You can do that.Please follow the procedure to install tensorflow with GPU as per the documentation attached [here](https://www.tensorflow.org/install/pip#step-by-step_instructions).
Please follow it and let us know if any problem persists in installing Tensorflow with GPU.

Also i believe that batch_size of 1500 may be very high and also i see your network is also deeper and bigger it may needs High RAM resources.Could you please also check with lower Batch sizes if working fine or not.If works with lower batch sizes and not working with Higher batch sizes probably its Out Of Memory issue with RAM.Then in that case you should opt for Higher Resources.

**Comment by MarkKocherovsky** [comment]
I will try downgrading my CUDA, but I will say that it does work with smaller batch sizes, so I'll look into Higher Resources. Is that a specific option I can enable?

**Comment by SuryanarayanaY** [comment]
Yes @MarkKocherovsky ,
Please opt for Higher Resources for training on high batch sizes.You can opt for distributed training on multi GPUs as mentioned here [tensorflow.org](https://www.tensorflow.org/guide/distributed_training) for better performance.Please try this and reach out us incase of any issues.
Thankyou!
