### ISSUE TITLE
Confusing Problems(Not a ndarray) occur when training wGAN with tensorflow.keras API : train_on_batch

### ISSUE THREAD

**Issue by MuellerJY** [tensorflow/tensorflow#58429]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf2.4.0

### Custom Code

No

### OS Platform and Distribution

Windows 10

### Python version

3.8

### CUDA/cuDNN version

Cuda compilation tools, release 11.1, V11.1.74;

### GPU model and memory

NVIDIA GeForce RTX 2080 Ti

### Current Behaviour?

```shell
Thanks to listen to my troubles!
It's my first time to call for help here.
I'm trying to train a wGAN with tensorflow.keras API.
It's confusing that the code seems to be able to work (loss can be correctly printed by epochs at the start).
But few epochs later, strange bug occurs as follow:(loss during training is remained)
--------------------------------
1 [D:-147.46, -46.00, -35.65, -138.93] [G:-481.90, 121.64, -221.78, -450.19] [L2_train:0.09970, 0.18841, 0.15391] [L2_val:0.07979, 0.07859, 0.04204] [L2_test:0.05952, 0.06244, 0.03242]
2 [D:-66.22, -26.87, -30.62, -29.14] [G:1.39, 206.37, 81.76, -345.29] [L2_train:0.09337, 0.14223, 0.13607] [L2_val:0.06910, 0.07733, 0.06625] [L2_test:0.06862, 0.08175, 0.07353]
3 [D:-54.95, -18.99, -16.84, -35.61] [G:235.31, 328.33, 220.04, -362.90] [L2_train:0.08394, 0.09853, 0.13101] [L2_val:0.04700, 0.05218, 0.04421] [L2_test:0.04917, 0.04784, 0.04229]
4 [D:-27.29, -11.39, -12.51, -9.55] [G:544.69, 333.72, 438.66, -258.71] [L2_train:0.04703, 0.06783, 0.06758] [L2_val:0.03517, 0.02774, 0.02109] [L2_test:0.03086, 0.02149, 0.01878]
5 [D:-91.86, -5.06, -46.21, -85.04] [G:33.63, 147.32, 290.38, -437.90] [L2_train:0.03059, 0.09686, 0.07675] [L2_val:0.04741, 0.10769, 0.09652] [L2_test:0.05370, 0.11032, 0.08847]
6 [D:-128.18, -37.26, -70.93, -83.93] [G:103.86, 301.46, 285.43, -505.10] [L2_train:0.02071, 0.05535, 0.05631] [L2_val:0.15789, 0.19782, 0.23549] [L2_test:0.15388, 0.18545, 0.21865]
7 [D:-133.02, -34.37, -73.45, -96.01] [G:-246.37, 155.21, 177.28, -604.51] [L2_train:0.02656, 0.05191, 0.07738] [L2_val:0.07032, 0.07954, 0.10540] [L2_test:0.12615, 0.10203, 0.17840]
8 [D:-40.16, -9.07, -24.21, -21.30] [G:19.53, 46.06, 206.59, -257.90] [L2_train:0.02747, 0.06426, 0.05750] [L2_val:0.02567, 0.04412, 0.02398] [L2_test:0.02138, 0.04012, 0.01959]
9 [D:-17.11, -5.28, -5.77, -11.56] [G:209.23, 72.47, 119.92, -9.19] [L2_train:0.03270, 0.05385, 0.06082] [L2_val:0.04001, 0.04625, 0.04980] [L2_test:0.03669, 0.03864, 0.08824]
10 [D:-46.63, -10.17, -22.81, -32.98] [G:244.32, -120.41, 301.34, 37.02] [L2_train:0.02382, 0.04930, 0.08281] [L2_val:0.01641, 0.04040, 0.04434] [L2_test:0.01816, 0.04293, 0.04300]
11 [D:-17.25, -3.89, -8.81, -8.89] [G:346.39, 128.02, 417.59, -222.40] [L2_train:0.02294, 0.07087, 0.04800] [L2_val:0.02236, 0.01953, 0.02654] [L2_test:0.05305, 0.04639, 0.07816]
Traceback (most recent call last):
  File "Compound_Model_Novel.py", line 504, in <module>
    sa_wgan_gp.train()
  File "Compound_Model_Novel.py", line 356, in train
    g_loss_train = self.gan_model.train_on_batch(
  File "E:\anaconda\envs\cnnGAN\lib\site-packages\tensorflow\python\keras\engine\training_v1.py", line 1088, in train_on_batch
    outputs = self.train_function(ins)  # pylint: disable=not-callable
  File "E:\anaconda\envs\cnnGAN\lib\site-packages\tensorflow\python\keras\backend.py", line 3956, in __call__
    fetched = self._callable_fn(*array_vals,
  File "E:\anaconda\envs\cnnGAN\lib\site-packages\tensorflow\python\client\session.py", line 1480, in __call__
    ret = tf_session.TF_SessionRunCallable(self._session._session,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Not a ndarray.
------------------------------------------------------
My doubts lie in the following points：
1. I do not understand why "Not a ndarray" will occur in my code in line "g_loss_train = self.gan_model.train_on_batch(...", which functions as gan_model training. In this function only inputs and target are fed self.gan_model.
2. Why this bug does not occur at the start of the training?
3. What will cause such bug during training process? "Not a ndarray" refers to what? My inputs, targets or others?
4. How to fix it

Deeply appreciated to your attention!
```

### Standalone code to reproduce the issue

```shell
None
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @MuellerJY !
2.4 version is outdated now. I would suggest you test in 2.9/2.10 version. 
If the error persists, you can use make_ndarray to convert the tensors to nd array prior training.

Please post this issue on [keras-team/keras repo](https://github.com/keras-team/keras/issues) for further assistance.
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999) . Thank you!

**Comment by mohantym** [comment]
Ok @MuellerJY !
Thanks for the update. Closing this issue here as it will be tracked in [Keras ](https://github.com/keras-team/keras/issues/17212 repo.

Thank you!
