### ISSUE TITLE
Request Tensorflow Docker container be expanded to support running all models.

### ISSUE THREAD

**Issue by garrettkajmowicz** [tensorflow/tensorflow#58443]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

binary

### Tensorflow Version

tf 2.9.1

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 22.04 LTS

### Python version

3.8

### Current Behaviour?

```shell
I'm creating a Docker container in which I want to run the TensorFlow object detection code provided in the model zoo. I expected to be able to download the TensorFlow Docker container, clone the relevant source, and be off to the races.

Instead, I found that I was missing a lot of required packages. I found references which suggested to use the provided setup script located here:

https://github.com/tensorflow/models/blob/master/research/object_detection/packages/tf2/setup.py
Unfortunately, this led to a number of strange conflicts which I determined to be due to differing versions of opencv-python and opencv-python-headless, neither of which I'd manually installed. Everything was pulled in by the script and associated dependencies.

Given that both the TensorFlow Dockerfile and the models setup script are forcing versions of packages less than head-of-line, I request that a fuller and known-working Docker image be provided.

Thank you.
```

### Standalone code to reproduce the issue

```shell
https://github.com/tensorflow/models/blob/master/research/object_detection/packages/tf2/setup.py
```

### Relevant log output

```shell
pip3 list would end up showing
opencv-python                 4.6.0.66
opencv-python-headless        4.5.2.52

This results in the following backtrace:
Traceback (most recent call last):
  File "model_main_tf2.py", line 31, in <module>
    from object_detection import model_lib_v2
  File "/opt/models/research/object_detection/model_lib_v2.py", line 29, in <module>
    from object_detection import eval_util
  File "/opt/models/research/object_detection/eval_util.py", line 36, in <module>
    from object_detection.metrics import lvis_evaluation
  File "/opt/models/research/object_detection/metrics/lvis_evaluation.py", line 23, in <module>
    from lvis import results as lvis_results
  File "/usr/local/lib/python3.8/dist-packages/lvis/__init__.py", line 5, in <module>
    from lvis.vis import LVISVis
  File "/usr/local/lib/python3.8/dist-packages/lvis/vis.py", line 1, in <module>
    import cv2
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.8/dist-packages/cv2/mat_wrapper/__init__.py", line 33, in <module>
    cv._registerMatType(Mat)
AttributeError: partially initialized module 'cv2' has no attribute '_registerMatType' (most likely due to a circular import)
```
</details>

**Comment by bhack** [comment]
I think that the original "research" Dockerfile is in this repository:

https://github.com/tensorflow/models/blob/master/research/object_detection/dockerfiles/tf2/Dockerfile

Also the new model garden object detection is at:
https://github.com/tensorflow/models/tree/master/official/vision#object-detection-and-instance-segmentation

We are also building object detection in Keras-cv:
https://github.com/keras-team/keras-cv/issues?q=is%3Aissue+is%3Aopen+label%3Aobject-detection-landing
