### ISSUE TITLE
Unit test nn_ops:pooling_ops_3d_test_cpu broken with oneDNN enabled

### ISSUE THREAD

**Issue by elfringham** [tensorflow/tensorflow#58446]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

git HEAD

### Custom Code

No

### OS Platform and Distribution

Ubuntu 20.04

### Mobile device

n/a

### Python version

3.8.10

### Bazel version

5.3.0

### GCC/Compiler version

9.3.1

### CUDA/cuDNN version

n/a

### GPU model and memory

n/a

### Current Behaviour?

```shell
//tensorflow/python/kernel_tests/nn_ops:pooling_ops_3d_test_cpu fails with
tensorflow.python.framework.errors_impl.AbortedError: {{function_node __wrapped____MklNativeAvgPool3DGrad_device_/job:localhost/replica:0/task:0/device:CPU:0}} Compute received an exception:Status: 2, message: could not create a descriptor for a pooling backward propagation primitive, in file tensorflow/core/kernels/mkl/mkl_avgpooling_op.cc:298 [Op:AvgPool3DGrad]
```

### Standalone code to reproduce the issue

```shell
bazel --bazelrc=/usertools/cpu.bazelrc test --config=sigbuild_local_cache --cache_test_results=no --crosstool_top="@sigbuild-r2.10_config_cuda//crosstool:toolchain" --jobs=16 --test_timeout=30,50,-1,-1 --test_env=TF_ENABLE_ONEDNN_OPTS=1 -- //tensorflow/python/kernel_tests/nn_ops:pooling_ops_3d_test_cpu
```

### Relevant log output

```shell
======================================================================
ERROR: testAvgPool3dGradEmptyInput (__main__.PoolingTest)
PoolingTest.testAvgPool3dGradEmptyInput
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/e953b164f58eb4c9598ad736d787ff39/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/nn_ops/pooling_ops_3d_test_cpu.runfiles/org_tensorflow/tensorflow/python/kernel_tests/nn_ops/pooling_ops_3d_test.py", line 152, in testAvgPool3dGradEmptyInput
    t = gen_nn_ops.AvgPool3DGrad(
  File "/root/.cache/bazel/_bazel_root/e953b164f58eb4c9598ad736d787ff39/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/nn_ops/pooling_ops_3d_test_cpu.runfiles/org_tensorflow/tensorflow/python/util/tf_export.py", line 422, in wrapper
    return f(**kwargs)
  File "/root/.cache/bazel/_bazel_root/e953b164f58eb4c9598ad736d787ff39/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/nn_ops/pooling_ops_3d_test_cpu.runfiles/org_tensorflow/tensorflow/python/ops/gen_nn_ops.py", line 448, in avg_pool3d_grad
    _ops.raise_from_not_ok_status(e, name)
  File "/root/.cache/bazel/_bazel_root/e953b164f58eb4c9598ad736d787ff39/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/nn_ops/pooling_ops_3d_test_cpu.runfiles/org_tensorflow/tensorflow/python/framework/ops.py", line 7215, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.AbortedError: {{function_node __wrapped____MklNativeAvgPool3DGrad_device_/job:localhost/replica:0/task:0/device:CPU:0}} Compute received an exception:Status: 2, message: could not create a descriptor for a pooling backward propagation primitive, in file tensorflow/core/kernels/mkl/mkl_avgpooling_op.cc:298 [Op:AvgPool3DGrad]
```
</details>

**Comment by elfringham** [comment]
@nSircombe @cfRod

**Comment by elfringham** [comment]
Introduced by https://github.com/tensorflow/tensorflow/commit/41affcdc1919df3e29684a946416192bfbc36eee

**Comment by preethivenkatesh** [comment]
hi, there is an internal ticket that is currently being worked on to fix this bug.

**Comment by agramesh1** [comment]
@cantonios PR for a fix has been submitted. https://github.com/tensorflow/tensorflow/pull/58525

**Comment by elfringham** [comment]
PR merged
