### ISSUE TITLE
tf.queue.FIFOQueue not savable by tf.saved_model.save in tf2.10

### ISSUE THREAD

**Issue by timedcy** [tensorflow/tensorflow#58466]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.10

### Custom Code

No

### OS Platform and Distribution

windows 10

### Python version

3.7

### CUDA/cuDNN version

8.2.1

### Current Behaviour?

```shell
tensorflow cannot save successfully when there exists `tf.queue.FIFOQueue` variable in cumstum layers by `tf.saved_model.save`
```

### Standalone code to reproduce the issue

```shell
import numpy as np
import tensorflow as tf

from tensorflow import keras as K


class HashtableEmb(K.Model):
    def __init__(self, training=True, key_dtype=tf.int64, value_dtype=tf.int32):
        K.Model.__init__(self)
        self.training = training
        self.key_dtype = key_dtype
        self.value_dtype = value_dtype

    def build(self, input_shape):
        self.DEFAULT_KEY = 0
        self.DEFAULT_VALUE = 0
        self.default_key = tf.constant(self.DEFAULT_KEY, dtype=self.key_dtype)
        self.empty_key = np.iinfo(np.int64).max
        self.deleted_key = np.iinfo(np.int64).min
        self.default_value = tf.constant(self.DEFAULT_VALUE, dtype=self.value_dtype)
        kw = dict(key_dtype=self.key_dtype, value_dtype=self.value_dtype,
                  default_value=self.default_value, empty_key=self.empty_key, deleted_key=self.deleted_key)
        self.index_table = tf.lookup.experimental.DenseHashTable(**kw)
        if self.training:
            self.index_table.insert(self.default_key, self.default_value)
        self.default_ids_queue = tf.queue.FIFOQueue(2_000_000, self.key_dtype, shapes=[],
                                                    name=f'default_ids_queue')
        self.built = True

    def call(self, ids, training=None):
        flatten_ids = tf.reshape(ids, [-1])
        ids_value = self.index_table.lookup(flatten_ids)
        if training: self.update_stat(flatten_ids)
        ids_index_orig = tf.reshape(ids_value, tf.shape(ids))
        return ids_index_orig

    def get_config(self):
        return dict(
            training=self.training,
            key_dtype=self.key_dtype,
            value_dtype=self.value_dtype,
            **(super(K.Model, self).get_config()))

    def update_stat(self, flatten_ids):
        flatten_ids = tf.identity(flatten_ids)
        self.default_ids_queue.enqueue_many(flatten_ids)  # comment this line, no exception


class TestModel(tf.keras.Model):
    def __init__(self):
        super(TestModel, self).__init__()

    def build(self, input_shape):
        self.hashemb = HashtableEmb()
        self.built = True

    def call(self, x, training=None):
        return {'y_click': self.hashemb(x['a'], training=training)}
 

if __name__ == '__main__':
    m = TestModel()
    print(m({'a': tf.convert_to_tensor([[2], [200]], dtype=tf.int64)}))
    signatures = {'serving_default': tf.function(m.call).get_concrete_function(
        x={'a': tf.TensorSpec([None, 1], dtype=tf.int64)}, training=False)}
    tf.saved_model.save(m, r'G:\t\test_model_save', signatures=signatures)
    m2 = tf.saved_model.load(r'G:\t\test_model_save')
    print(m2({'a': tf.convert_to_tensor([[2], [200]], dtype=tf.int64)}))
```

### Relevant log output

```shell
2022-11-07 13:43:01.371282: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 2824 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 960M, pci bus id: 0000:01:00.0, compute capability: 5.0
{'y_click': <tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[0],
       [0]])>}
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\ai_tf2\lib\site-packages\tensorflow\python\saved_model\function_serialization.py", line 60, in serialize_concrete_function
    bound_inputs.append(node_ids[capture])
  File "C:\ProgramData\Anaconda3\envs\ai_tf2\lib\site-packages\tensorflow\python\util\object_identity.py", line 135, in __getitem__
    return self._storage[self._wrap_key(key)]
KeyError: <_ObjectIdentityWrapper wrapping <tf.Tensor: shape=(), dtype=resource, value=<ResourceHandle(name="28", device="/job:localhost/replica:0/task:0/device:CPU:0", container="localhost", type="class tensorflow::QueueInterface", dtype and shapes : "[  ]")>>>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/code/save_queue_op_test.py", line 71, in <module>
    tf.saved_model.save(m, r'G:\t\test_model_save', signatures=signatures)
  File "C:\ProgramData\Anaconda3\envs\ai_tf2\lib\site-packages\tensorflow\python\saved_model\save.py", line 1232, in save
    save_and_return_nodes(obj, export_dir, signatures, options)
  File "C:\ProgramData\Anaconda3\envs\ai_tf2\lib\site-packages\tensorflow\python\saved_model\save.py", line 1268, in save_and_return_nodes
    _build_meta_graph(obj, signatures, options, meta_graph_def))
  File "C:\ProgramData\Anaconda3\envs\ai_tf2\lib\site-packages\tensorflow\python\saved_model\save.py", line 1441, in _build_meta_graph
    return _build_meta_graph_impl(obj, signatures, options, meta_graph_def)
  File "C:\ProgramData\Anaconda3\envs\ai_tf2\lib\site-packages\tensorflow\python\saved_model\save.py", line 1406, in _build_meta_graph_impl
    asset_info.asset_index)
  File "C:\ProgramData\Anaconda3\envs\ai_tf2\lib\site-packages\tensorflow\python\saved_model\save.py", line 968, in _serialize_object_graph
    concrete_function, saveable_view.captured_tensor_node_ids)
  File "C:\ProgramData\Anaconda3\envs\ai_tf2\lib\site-packages\tensorflow\python\saved_model\function_serialization.py", line 63, in serialize_concrete_function
    f"Failed to add concrete function '{concrete_function.name}' to object-"
KeyError: 'Failed to add concrete function \'b\'__inference_test_model_layer_call_fn_262\'\' to object-based SavedModel as it captures tensor <tf.Tensor: shape=(), dtype=resource, value=<ResourceHandle(name="28", device="/job:localhost/replica:0/task:0/device:CPU:0", container="localhost", type="class tensorflow::QueueInterface", dtype and shapes : "[  ]")>> which is unsupported or not reachable from root. One reason could be that a stateful object or a variable that the function depends on is not assigned to an attribute of the serialized trackable object (see SaveTest.test_captures_unreachable_variable).'
```
</details>

**Comment by bhack** [comment]
Have you checked https://github.com/keras-team/keras/issues/16015 ?

**Comment by mohantym** [comment]
Hi @timedcy!

Please post this issue on [keras-team/Keras repo](https://github.com/keras-team/keras/issues) for further assistance.

To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999) .

 Thank you!!

**Comment by gowthamkpr** [comment]
Serialization does not seem to be supported for tf.queue.FIFOqueue. For more details and in depth explanation, please look at the following [comment](https://github.com/keras-team/keras/issues/17223#issuecomment-1312073797). Thanks!
