### ISSUE TITLE
Parallel loading of nested ExtensionTypes produces shape mismatch

### ISSUE THREAD

**Issue by thoomi** [tensorflow/tensorflow#58522]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.10

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.8

### GPU model and memory

Nvidia Geforce 1080 Ti

### Current Behaviour?

```shell
For some reason tensor `b2` has the shape of `a` and that does not match the definition. This happens not every time I run the exact same code but only sometimes. It seems to work with Tensorflow 2.9 though...
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf


class A(tf.experimental.ExtensionType):
    a1: tf.Tensor

    class Spec:
        def __init__(self):
            self.a1 = tf.TensorSpec(shape=[2, 1], dtype=tf.float16)


class B(tf.experimental.ExtensionType):
    b1: tf.Tensor
    b2: tf.Tensor
    a: A

    class Spec:
        def __init__(self):
            self.b1 = tf.TensorSpec(shape=[2, 5], dtype=tf.float16)
            self.b2 = tf.TensorSpec(shape=[2, 6], dtype=tf.float32)
            self.a = A.Spec()


def loading_fn():
    objects = B(
        tf.zeros(shape=[2, 5], dtype=tf.float16),
        tf.zeros(shape=[2, 6], dtype=tf.float32),
        A(tf.zeros(shape=[2, 1], dtype=tf.float16)),
    )

    return objects


def func(i):
    return tf.py_function(loading_fn, inp=[], Tout=B.Spec())


dataset = tf.data.Dataset.from_tensor_slices([i for i in range(10)])
dataset = dataset.map(func, num_parallel_calls=10)

for _ in range(10):
    for path in iter(dataset):
        pass
```

### Relevant log output

```shell
2022-11-10 14:44:32.830413: W tensorflow/core/framework/op_kernel.cc:1768] INVALID_ARGUMENT: ValueError: py_function: func=<function loading_fn at 0x7fc368151a60> returned [B(b1=<tf.Tensor: shape=(2, 5), dtype=float16, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float16)>, b2=<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>, a=A(a1=<tf.Tensor: shape=(2, 6), dtype=float16, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float16)>))], which did not match Tout=[B.Spec(b1=TensorSpec(shape=(2, 5), dtype=tf.float16, name=None), b2=TensorSpec(shape=(2, 6), dtype=tf.float32, name=None), a=A.Spec(a1=TensorSpec(shape=(2, 1), dtype=tf.float16, name=None)))].
In particular, B(b1=<tf.Tensor: shape=(2, 5), dtype=float16, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float16)>, b2=<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>, a=A(a1=<tf.Tensor: shape=(2, 6), dtype=float16, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float16)>)) is not compatible with B.Spec(b1=TensorSpec(shape=(2, 5), dtype=tf.float16, name=None), b2=TensorSpec(shape=(2, 6), dtype=tf.float32, name=None), a=A.Spec(a1=TensorSpec(shape=(2, 1), dtype=tf.float16, name=None))).
Traceback (most recent call last):

  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/script_ops.py", line 269, in __call__
    return func(device, token, args)

  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/script_ops.py", line 147, in __call__
    outputs = self._call(device, args)

  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/script_ops.py", line 154, in _call
    ret = self._func(*args)

  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/script_ops.py", line 824, in wrapped_func
    raise ValueError(

ValueError: py_function: func=<function loading_fn at 0x7fc368151a60> returned [B(b1=<tf.Tensor: shape=(2, 5), dtype=float16, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float16)>, b2=<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>, a=A(a1=<tf.Tensor: shape=(2, 6), dtype=float16, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float16)>))], which did not match Tout=[B.Spec(b1=TensorSpec(shape=(2, 5), dtype=tf.float16, name=None), b2=TensorSpec(shape=(2, 6), dtype=tf.float32, name=None), a=A.Spec(a1=TensorSpec(shape=(2, 1), dtype=tf.float16, name=None)))].
In particular, B(b1=<tf.Tensor: shape=(2, 5), dtype=float16, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float16)>, b2=<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>, a=A(a1=<tf.Tensor: shape=(2, 6), dtype=float16, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float16)>)) is not compatible with B.Spec(b1=TensorSpec(shape=(2, 5), dtype=tf.float16, name=None), b2=TensorSpec(shape=(2, 6), dtype=tf.float32, name=None), a=A.Spec(a1=TensorSpec(shape=(2, 1), dtype=tf.float16, name=None))).


2022-11-10 14:44:32.838758: W tensorflow/core/framework/op_kernel.cc:1768] INVALID_ARGUMENT: ValueError: py_function: func=<function loading_fn at 0x7fc368151a60> returned [B(b1=<tf.Tensor: shape=(2, 5), dtype=float16, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float16)>, b2=<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.],
       [0.]], dtype=float32)>, a=A(a1=<tf.Tensor: shape=(2, 1), dtype=float16, numpy=
array([[0.],
       [0.]], dtype=float16)>))], which did not match Tout=[B.Spec(b1=TensorSpec(shape=(2, 5), dtype=tf.float16, name=None), b2=TensorSpec(shape=(2, 6), dtype=tf.float32, name=None), a=A.Spec(a1=TensorSpec(shape=(2, 1), dtype=tf.float16, name=None)))].
In particular, B(b1=<tf.Tensor: shape=(2, 5), dtype=float16, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float16)>, b2=<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.],
       [0.]], dtype=float32)>, a=A(a1=<tf.Tensor: shape=(2, 1), dtype=float16, numpy=
array([[0.],
       [0.]], dtype=float16)>)) is not compatible with B.Spec(b1=TensorSpec(shape=(2, 5), dtype=tf.float16, name=None), b2=TensorSpec(shape=(2, 6), dtype=tf.float32, name=None), a=A.Spec(a1=TensorSpec(shape=(2, 1), dtype=tf.float16, name=None))).
Traceback (most recent call last):

  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/script_ops.py", line 269, in __call__
    return func(device, token, args)

  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/script_ops.py", line 147, in __call__
    outputs = self._call(device, args)

  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/script_ops.py", line 154, in _call
    ret = self._func(*args)

  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/script_ops.py", line 824, in wrapped_func
    raise ValueError(

ValueError: py_function: func=<function loading_fn at 0x7fc368151a60> returned [B(b1=<tf.Tensor: shape=(2, 5), dtype=float16, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float16)>, b2=<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.],
       [0.]], dtype=float32)>, a=A(a1=<tf.Tensor: shape=(2, 1), dtype=float16, numpy=
array([[0.],
       [0.]], dtype=float16)>))], which did not match Tout=[B.Spec(b1=TensorSpec(shape=(2, 5), dtype=tf.float16, name=None), b2=TensorSpec(shape=(2, 6), dtype=tf.float32, name=None), a=A.Spec(a1=TensorSpec(shape=(2, 1), dtype=tf.float16, name=None)))].
In particular, B(b1=<tf.Tensor: shape=(2, 5), dtype=float16, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float16)>, b2=<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.],
       [0.]], dtype=float32)>, a=A(a1=<tf.Tensor: shape=(2, 1), dtype=float16, numpy=
array([[0.],
       [0.]], dtype=float16)>)) is not compatible with B.Spec(b1=TensorSpec(shape=(2, 5), dtype=tf.float16, name=None), b2=TensorSpec(shape=(2, 6), dtype=tf.float32, name=None), a=A.Spec(a1=TensorSpec(shape=(2, 1), dtype=tf.float16, name=None))).


Traceback (most recent call last):
  File "test.py", line 42, in <module>
    for path in iter(dataset):
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 766, in __next__
    return self._next_internal()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 749, in _next_internal
    ret = gen_dataset_ops.iterator_get_next(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 3017, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py", line 7209, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__IteratorGetNext_output_types_3_device_/job:localhost/replica:0/task:0/device:CPU:0}} ValueError: py_function: func=<function loading_fn at 0x7fc368151a60> returned [B(b1=<tf.Tensor: shape=(2, 5), dtype=float16, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float16)>, b2=<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.],
       [0.]], dtype=float32)>, a=A(a1=<tf.Tensor: shape=(2, 1), dtype=float16, numpy=
array([[0.],
       [0.]], dtype=float16)>))], which did not match Tout=[B.Spec(b1=TensorSpec(shape=(2, 5), dtype=tf.float16, name=None), b2=TensorSpec(shape=(2, 6), dtype=tf.float32, name=None), a=A.Spec(a1=TensorSpec(shape=(2, 1), dtype=tf.float16, name=None)))].
In particular, B(b1=<tf.Tensor: shape=(2, 5), dtype=float16, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float16)>, b2=<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.],
       [0.]], dtype=float32)>, a=A(a1=<tf.Tensor: shape=(2, 1), dtype=float16, numpy=
array([[0.],
       [0.]], dtype=float16)>)) is not compatible with B.Spec(b1=TensorSpec(shape=(2, 5), dtype=tf.float16, name=None), b2=TensorSpec(shape=(2, 6), dtype=tf.float32, name=None), a=A.Spec(a1=TensorSpec(shape=(2, 1), dtype=tf.float16, name=None))).
Traceback (most recent call last):

  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/script_ops.py", line 269, in __call__
    return func(device, token, args)

  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/script_ops.py", line 147, in __call__
    outputs = self._call(device, args)

  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/script_ops.py", line 154, in _call
    ret = self._func(*args)

  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/script_ops.py", line 824, in wrapped_func
    raise ValueError(

ValueError: py_function: func=<function loading_fn at 0x7fc368151a60> returned [B(b1=<tf.Tensor: shape=(2, 5), dtype=float16, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float16)>, b2=<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.],
       [0.]], dtype=float32)>, a=A(a1=<tf.Tensor: shape=(2, 1), dtype=float16, numpy=
array([[0.],
       [0.]], dtype=float16)>))], which did not match Tout=[B.Spec(b1=TensorSpec(shape=(2, 5), dtype=tf.float16, name=None), b2=TensorSpec(shape=(2, 6), dtype=tf.float32, name=None), a=A.Spec(a1=TensorSpec(shape=(2, 1), dtype=tf.float16, name=None)))].
In particular, B(b1=<tf.Tensor: shape=(2, 5), dtype=float16, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float16)>, b2=<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.],
       [0.]], dtype=float32)>, a=A(a1=<tf.Tensor: shape=(2, 1), dtype=float16, numpy=
array([[0.],
       [0.]], dtype=float16)>)) is not compatible with B.Spec(b1=TensorSpec(shape=(2, 5), dtype=tf.float16, name=None), b2=TensorSpec(shape=(2, 6), dtype=tf.float32, name=None), a=A.Spec(a1=TensorSpec(shape=(2, 1), dtype=tf.float16, name=None))).


         [[{{node EagerPyFunc}}]] [Op:IteratorGetNext]
```
</details>

**Comment by bhack** [comment]
I cannot reproduce this on TF 2.10.

Can you try to reproduce this with TF `2.11.0-rc2`?

**Comment by tilakrayal** [comment]
@thoomi,
I was able to execute the code without any issue/error on tensorflow cpu and [gpu](https://colab.research.google.com/gist/tilakrayal/30f739d829a43d7c113a9ab06640e10a/gpu751.ipynb) v2.9, v2.10 and nightly(2.12.0-dev20221110). Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/a727361cbdb6f21e227fd6ec0cc25eaa/cpu750.ipynb#scrollTo=zuCuupA0jrtq). Thank you!

**Comment by thoomi** [comment]
@bhack yes I could reproduce the issue with TF `2.11.0-rc2` but not with `2.9.1`. But as I mentioned in the description the problem occurs not every time I run the code which makes it little difficult to consistently reproduce the error. 
I tried to come up with another gist to run into that error "more frequently":

```python
import tensorflow as tf


class A(tf.experimental.ExtensionType):
    a1: tf.Tensor

    class Spec:
        def __init__(self):
            self.a1 = tf.TensorSpec(shape=[2, 11], dtype=tf.float16)


class B(tf.experimental.ExtensionType):
    b1: tf.Tensor
    b2: tf.Tensor
    b3: tf.Tensor
    b4: tf.Tensor
    b5: tf.Tensor
    b6: tf.Tensor
    b7: tf.Tensor
    b8: tf.Tensor
    b9: tf.Tensor
    b10: tf.Tensor
    a: A

    class Spec:
        def __init__(self):
            self.b1 = tf.TensorSpec(shape=[2, 1], dtype=tf.float32)
            self.b2 = tf.TensorSpec(shape=[2, 2], dtype=tf.float16)
            self.b3 = tf.TensorSpec(shape=[2, 3], dtype=tf.int8)
            self.b4 = tf.TensorSpec(shape=[2, 4], dtype=tf.int16)
            self.b5 = tf.TensorSpec(shape=[2, 5], dtype=tf.int32)
            self.b6 = tf.TensorSpec(shape=[2, 6], dtype=tf.bfloat16)
            self.b7 = tf.TensorSpec(shape=[2, 7], dtype=tf.float64)
            self.b8 = tf.TensorSpec(shape=[2, 8], dtype=tf.int64)
            self.b9 = tf.TensorSpec(shape=[2, 9], dtype=tf.uint8)
            self.b10 = tf.TensorSpec(shape=[2, 10], dtype=tf.uint16)
            self.a = A.Spec()


def loading_fn():
    objects = B(
        1 * tf.ones(shape=[2, 1], dtype=tf.float32),
        2 * tf.ones(shape=[2, 2], dtype=tf.float16),
        3 * tf.ones(shape=[2, 3], dtype=tf.int8),
        4 * tf.ones(shape=[2, 4], dtype=tf.int16),
        5 * tf.ones(shape=[2, 5], dtype=tf.int32),
        6 * tf.ones(shape=[2, 6], dtype=tf.bfloat16),
        7 * tf.ones(shape=[2, 7], dtype=tf.float64),
        8 * tf.ones(shape=[2, 8], dtype=tf.int64),
        9 * tf.ones(shape=[2, 9], dtype=tf.uint8),
        10 * tf.ones(shape=[2, 10], dtype=tf.uint16),
        A(11 * tf.ones(shape=[2, 11], dtype=tf.float16)),
    )

    return objects


def func(i):
    return tf.py_function(loading_fn, inp=[], Tout=B.Spec())


dataset = tf.data.Dataset.from_tensor_slices([i for i in range(10)])
dataset = dataset.map(func, num_parallel_calls=10)

for _ in range(10):
    for path in iter(dataset):
        pass
```

I tried reproducing it with Google Colab as well, please see the gist of it [here](https://colab.research.google.com/gist/thoomi/ad8bb293e6662faab7d9c12dc4864099/untitled0.ipynb). It produced this error:

> InvalidArgumentError: {{function_node __wrapped__IteratorGetNext_output_types_11_device_/job:localhost/replica:0/task:0/device:CPU:0}} ValueError: py_function: func=<function loading_fn at 0x7f3cd8ffa7a0> returned [B(b1=<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>, b2=<tf.Tensor: shape=(2, 6), dtype=float16, numpy=
array([[2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.]], dtype=float16)>, b3=<tf.Tensor: shape=(2, 3), dtype=int8, numpy=
array([[3, 3, 3],
       [3, 3, 3]], dtype=int8)>, b4=<tf.Tensor: shape=(2, 4), dtype=int16, numpy=
array([[4, 4, 4, 4],
       [4, 4, 4, 4]], dtype=int16)>, b5=<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]], dtype=int32)>, b6=<tf.Tensor: shape=(2, 6), dtype=bfloat16, numpy=
array([[6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6]], dtype=bfloat16)>, b7=<tf.Tensor: shape=(2, 7), dtype=float64, numpy=
array([[7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7.]])>, b8=<tf.Tensor: shape=(2, 8), dtype=int64, numpy=
array([[8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8]])>, b9=<tf.Tensor: shape=(2, 9), dtype=uint8, numpy=
array([[9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9]], dtype=uint8)>, b10=<tf.Tensor: shape=(2, 10), dtype=uint16, numpy=
array([[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]], dtype=uint16)>, a=A(a1=<tf.Tensor: shape=(2, 11), dtype=float16, numpy=
array([[11., 11., 11., 11., 11., 11., 11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11., 11., 11., 11., 11., 11., 11.]],
      dtype=float16)>))], which did not match Tout=[B.Spec(b1=TensorSpec(shape=(2, 1), dtype=tf.float32, name=None), b2=TensorSpec(shape=(2, 2), dtype=tf.float16, name=None), b3=TensorSpec(shape=(2, 3), dtype=tf.int8, name=None), b4=TensorSpec(shape=(2, 4), dtype=tf.int16, name=None), b5=TensorSpec(shape=(2, 5), dtype=tf.int32, name=None), b6=TensorSpec(shape=(2, 6), dtype=tf.bfloat16, name=None), b7=TensorSpec(shape=(2, 7), dtype=tf.float64, name=None), b8=TensorSpec(shape=(2, 8), dtype=tf.int64, name=None), b9=TensorSpec(shape=(2, 9), dtype=tf.uint8, name=None), b10=TensorSpec(shape=(2, 10), dtype=tf.uint16, name=None), a=A.Spec(a1=TensorSpec(shape=(2, 11), dtype=tf.float16, name=None)))].

If you look at the reported tensor `b2` it has the wrong shape of `(2, 6)`, but should have been `(2, 2)`. 

Hope this helps :) Thanks for looking into it!

**Comment by bhack** [comment]
I've tried some runs but I cannot reproduce it. Probably you could `set_shape` in you py_function. 

As py_function has some limits (see Doc) you could explore also what I've suggested in https://github.com/tensorflow/tensorflow/issues/58448#issuecomment-1313695458

**Comment by thoomi** [comment]
>  Probably you could set_shape in you py_function.

Good point! I`ve tried that already in our code but the we are still running into the issue.

**Comment by thoomi** [comment]
I tried to use `git bisect` to narrow down the commit that introduced the error and arrived at commit [c1286fe88e14146a47d5a64d5de17f6479d2e21f](https://github.com/tensorflow/tensorflow/commit/c1286fe88e14146a47d5a64d5de17f6479d2e21f)

> commit c1286fe88e14146a47d5a64d5de17f6479d2e21f
> Author: Sagun Bajra <sagunb@google.com>
> Date:   Fri Apr 15 09:12:51 2022 -0700
> 
>    Enable eager op as function mode in tf nightly.
>    
>    PiperOrigin-RevId: 442029734
>
> tensorflow/python/eager/context.py | 3 ++-
> 1 file changed, 2 insertions(+), 1 deletion(-)

I'm not sure about what's activated with this flag that could lead to the error I am seeing. But I hope it helps narrowing down the issue :)

**Comment by janbernloehr** [comment]
@bhack @sagunb : we cannot update from tensorflow 2.9 because of this bug. any updates on this when this will be resolved?

**Comment by mys007** [comment]
This could have a common root cause with https://github.com/tensorflow/tensorflow/issues/58676 and https://github.com/tensorflow/tensorflow/issues/58140 (TF_RUN_EAGER_OP_AS_FUNCTION env variable).

**Comment by thoomi** [comment]
Setting the `TF_RUN_EAGER_OP_AS_FUNCTION` to `false` helps and solves the issue for TF 2.10. However this flag was removed in TF 2.11 and we are still running into the same problem there.

**Comment by rrajkumar1990** [comment]
Hi @mys007  - w.r.to #58140(https://github.com/tensorflow/tensorflow/issues/58140), 
The issue is mainly with memory and performance.I am using Retinanet tensorflow  graph model. Ported it with compat.v1 methods till Version 2.8 it was fine.
When I upgraded to 2.9.1 or 2.10.0 or 2.11.0 versions , I am seeing issue with memory usage and performance. 
I tried  "TF_RUN_EAGER_OP_AS_FUNCTION" in 2.9.1 /2.10.0/2.11.0 but still the memory and performance issue persists. For detailed numbers. Please refer that defect.
Thanks

**Comment by sagunb** [comment]
@JXRiver would you happen to know of any limitations of loading ExtensionTypes in parallel?

**Comment by janbernloehr** [comment]
We run into the same issue when using NamedTuples instead of ExtensionTypes

**Comment by JXRiver** [comment]
This may be related to `py_function`. py_function requires GIL and is generally not recommended to be used in tf.data except for experimental purpose. See the limitation part of https://www.tensorflow.org/api_docs/python/tf/py_function.

Did you try use `tf.funciton` instead of `py_function`?

**Comment by janbernloehr** [comment]
We unfortunately cannot use tf.function in our scenario because we call into a python library. We also had no issues with this until TF 2.10 was released.

**Comment by JXRiver** [comment]
I think it is related to `py_function`. I was able to repro the issue. But when I replace the `py_function` with `tf.function`, the error went away.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

I tried to execute the mentioned code on Tensorflow v2.17 and it was executed without error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/d615540d44479f609041593c2e69a65b/untitled2244.ipynb).

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
