### ISSUE TITLE
ModuleNotFoundError: No module named '_pywrap_tensorflow'   Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by cool-man-vk** [tensorflow/tensorflow#58547]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.10

### Custom Code

Yes

### Current Behaviour?

```shell
A bug happened!
```

### Standalone code to reproduce the issue

```shell
Saying gpu problem
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Users\rrvig\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rrvig\AppData\Local\Programs\Python\Python311\Lib\imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rrvig\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow\python\__init__.py", line 66, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\rrvig\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
                         ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rrvig\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ModuleNotFoundError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Dev\flutter projects\mlh_cropance\python\app.py", line 8, in <module>
    import keras
  File "C:\Users\rrvig\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\__init__.py", line 20, in <module>
    from keras import distribute
  File "C:\Users\rrvig\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\distribute\__init__.py", line 18, in <module>
    from keras.distribute import sidecar_evaluator
  File "C:\Users\rrvig\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\distribute\sidecar_evaluator.py", line 17, in <module>
    import tensorflow.compat.v2 as tf
  File "C:\Users\rrvig\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\rrvig\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow\python\__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\rrvig\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rrvig\AppData\Local\Programs\Python\Python311\Lib\imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rrvig\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow\python\__init__.py", line 66, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\rrvig\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
                         ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rrvig\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ModuleNotFoundError: No module named '_pywrap_tensorflow'


Failed to load the native TensorFlow runtime.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```
</details>

**Comment by mohantym** [comment]
Hi @cool-man-vk !
Python 3.11 has not been added as supported version yet and in the road map for future releases.
[Ref.](https://www.tensorflow.org/install)
Could you share the reproducible command  and OS details too to replicate this issue.
Thank you!

**Comment by cool-man-vk** [comment]
My python version is 3.11.0 and I migrated to tensorflow 1.0.0 as I was facing issues in the latest version.
![image](https://user-images.githubusercontent.com/76818423/203766391-a81705b9-19a5-4105-8a8c-8bb0d490a8e0.png)

**Comment by mohantym** [comment]
Hi @cool-man-vk !
Would it be possible to share the commands?
Can i go with below command. 
```
conda create --name tf_gpu python=3.11
conda deactivate
conda activate tf_gpu

conda install -c conda-forge cudatoolkit=11.2 cudnn=8.1.0
pip install tensorflow==2.10
```
Thank you!

**Comment by cool-man-vk** [comment]
Yes Mohan.
`pip install tensorflow==1.0.0`

> This is the command which I've tried. And installed the tf succesfully.
> But when I use in python ,
> it arises this error.

**Comment by mohantym** [comment]
Hey @cool-man-vk !

1.x version are not supported any more.  Please go through tested configs from [2.x documentation](https://www.tensorflow.org/install/pip) (2.10 , Python 3.7-3.10).

Thank you!

**Comment by mohantym** [comment]
Hey @cool-man-vk !

1.x version are not supported any more.  Please go through tested configs from [2.x documentation](https://www.tensorflow.org/install/pip) (2.10 , Python 3.7-3.10). For 1.0.0 , Max supported python version is Python 3.6 .

Feel free to open if you are facing issue in 2.x versions. 

Thank you!
