### ISSUE TITLE
Tensorflow Lite 2.11.0-rc2 CMake build system broken

### ISSUE THREAD

**Issue by DwayneDuane** [tensorflow/tensorflow#58611]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.11.0-rc2

### Custom Code

No

### OS Platform and Distribution

Android

### Mobile device

N/A

### Python version

3.9

### Bazel version

N/A

### GCC/Compiler version

Android NDK 24

### CUDA/cuDNN version

N/A

### GPU model and memory

N/A

### Current Behaviour?

Unable to cross compile TFLite 2.11.0-rc2 for Android, using CMake.
I understand that v2.11.0 is still a release candidate. But I want to bring this issue to your attention. We rely heavily on TFLite (and the CMake workflow) in our production and we are looking forward to upgrading to v2.11.0, once it is officially released, to take advantage of fixes to long standing bugs and issues.

Here is the command I used to build:

```shell
mkdir tflite.build.android && cd tflite.build.android

cmake -G "Unix Makefiles" -DCMAKE_SYSTEM_NAME=Android -DANDROID_ABI=arm64-v8a -DANDROID_STL=c++_shared -DANDROID_NATIVE_API_LEVEL=27 -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_TOOLCHAIN_FILE=$HOME/Android/Sdk/ndk/24.0.8215888/build/cmake/android.toolchain.cmake -DTFLITE_ENABLE_XNNPACK=ON -DTFLITE_ENABLE_GPU=ON -DTFLITE_ENABLE_NNAPI=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF ../tensorflow/tensorflow/lite

make -j4
```
, and I get the following error:
```
 28%] Linking CXX executable flatc
cd /home/myname/myworkingdir/tflite.build.android/_deps/flatbuffers-build && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/flatc.dir/link.txt --verbose=1
/home/myname/Android/Sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android27 --sysroot=/home/myname/Android/Sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fexceptions -frtti -stdlib=libc++ -O3 -DNDEBUG -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Qunused-arguments -Wl,--no-undefined  -Wl,--gc-sections CMakeFiles/flatc.dir/src/idl_parser.cpp.o CMakeFiles/flatc.dir/src/idl_gen_text.cpp.o CMakeFiles/flatc.dir/src/reflection.cpp.o CMakeFiles/flatc.dir/src/util.cpp.o CMakeFiles/flatc.dir/src/idl_gen_cpp.cpp.o CMakeFiles/flatc.dir/src/idl_gen_csharp.cpp.o CMakeFiles/flatc.dir/src/idl_gen_dart.cpp.o CMakeFiles/flatc.dir/src/idl_gen_kotlin.cpp.o CMakeFiles/flatc.dir/src/idl_gen_go.cpp.o CMakeFiles/flatc.dir/src/idl_gen_java.cpp.o CMakeFiles/flatc.dir/src/idl_gen_ts.cpp.o CMakeFiles/flatc.dir/src/idl_gen_php.cpp.o CMakeFiles/flatc.dir/src/idl_gen_python.cpp.o CMakeFiles/flatc.dir/src/idl_gen_lobster.cpp.o CMakeFiles/flatc.dir/src/idl_gen_lua.cpp.o CMakeFiles/flatc.dir/src/idl_gen_rust.cpp.o CMakeFiles/flatc.dir/src/idl_gen_fbs.cpp.o CMakeFiles/flatc.dir/src/idl_gen_grpc.cpp.o CMakeFiles/flatc.dir/src/idl_gen_json_schema.cpp.o CMakeFiles/flatc.dir/src/idl_gen_swift.cpp.o CMakeFiles/flatc.dir/src/flatc.cpp.o CMakeFiles/flatc.dir/src/flatc_main.cpp.o CMakeFiles/flatc.dir/src/bfbs_gen_lua.cpp.o CMakeFiles/flatc.dir/src/code_generators.cpp.o CMakeFiles/flatc.dir/grpc/src/compiler/cpp_generator.cc.o CMakeFiles/flatc.dir/grpc/src/compiler/go_generator.cc.o CMakeFiles/flatc.dir/grpc/src/compiler/java_generator.cc.o CMakeFiles/flatc.dir/grpc/src/compiler/python_generator.cc.o CMakeFiles/flatc.dir/grpc/src/compiler/swift_generator.cc.o CMakeFiles/flatc.dir/grpc/src/compiler/ts_generator.cc.o -o flatc   -latomic -lm 
Running scripts/generate_code.py...
cd /home/myname/myworkingdir/tflite.build.android/flatbuffers && /usr/bin/python3.9 scripts/generate_code.py --flatc /home/myname/myworkingdir/tflite.build.android/_deps/flatbuffers-build/flatc --skip-gen-reflection
Traceback (most recent call last):
  File "/home/myname/myworkingdir/tflite.build.android/flatbuffers/scripts/generate_code.py", line 148, in <module>
    flatc(
  File "/home/myname/myworkingdir/tflite.build.android/flatbuffers/scripts/generate_code.py", line 82, in flatc
    result = subprocess.run(cmd, cwd=str(cwd), check=True)
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/myname/myworkingdir/tflite.build.android/_deps/flatbuffers-build/flatc'
make[2]: *** [_deps/flatbuffers-build/CMakeFiles/flatc.dir/build.make:566: _deps/flatbuffers-build/flatc] Error 1
make[2]: *** Deleting file '_deps/flatbuffers-build/flatc'
make[2]: Leaving directory '/home/myname/myworkingdir/tflite.build.android'
make[1]: *** [CMakeFiles/Makefile2:4720: _deps/flatbuffers-build/CMakeFiles/flatc.dir/all] Error 2
make[1]: Leaving directory '/home/myname/myworkingdir/tflite.build.android'
make: *** [Makefile:139: all] Error 2
```

The problem seems to be that Python tries to invoke the `flatbuffers/scripts/generate_code.py` script, which attempts to run `/home/myname/myworkingdir/tflite.build.android/_deps/flatbuffers-build/flatc`, which does not exist. 

TFLite v2.10.1 builds fine, but as far as I can tell, for v2.10.1m there is no attempt to invoke `generate_code.py` or `_deps/flatbuffers-build/flatc`

### Standalone code to reproduce the issue

```shell
mkdir tflite.build.android && cd tflite.build.android

cmake -G "Unix Makefiles" -DCMAKE_SYSTEM_NAME=Android -DANDROID_ABI=arm64-v8a -DANDROID_STL=c++_shared -DANDROID_NATIVE_API_LEVEL=27 -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_TOOLCHAIN_FILE=$HOME/Android/Sdk/ndk/24.0.8215888/build/cmake/android.toolchain.cmake -DTFLITE_ENABLE_XNNPACK=ON -DTFLITE_ENABLE_GPU=ON -DTFLITE_ENABLE_NNAPI=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF ../tensorflow/tensorflow/lite

make -j4
```

### Relevant log output

```shell
28%] Linking CXX executable flatc
cd /home/myname/myworkingdir/tflite.build.android/_deps/flatbuffers-build && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/flatc.dir/link.txt --verbose=1
/home/myname/Android/Sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android27 --sysroot=/home/myname/Android/Sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fexceptions -frtti -stdlib=libc++ -O3 -DNDEBUG -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Qunused-arguments -Wl,--no-undefined  -Wl,--gc-sections CMakeFiles/flatc.dir/src/idl_parser.cpp.o CMakeFiles/flatc.dir/src/idl_gen_text.cpp.o CMakeFiles/flatc.dir/src/reflection.cpp.o CMakeFiles/flatc.dir/src/util.cpp.o CMakeFiles/flatc.dir/src/idl_gen_cpp.cpp.o CMakeFiles/flatc.dir/src/idl_gen_csharp.cpp.o CMakeFiles/flatc.dir/src/idl_gen_dart.cpp.o CMakeFiles/flatc.dir/src/idl_gen_kotlin.cpp.o CMakeFiles/flatc.dir/src/idl_gen_go.cpp.o CMakeFiles/flatc.dir/src/idl_gen_java.cpp.o CMakeFiles/flatc.dir/src/idl_gen_ts.cpp.o CMakeFiles/flatc.dir/src/idl_gen_php.cpp.o CMakeFiles/flatc.dir/src/idl_gen_python.cpp.o CMakeFiles/flatc.dir/src/idl_gen_lobster.cpp.o CMakeFiles/flatc.dir/src/idl_gen_lua.cpp.o CMakeFiles/flatc.dir/src/idl_gen_rust.cpp.o CMakeFiles/flatc.dir/src/idl_gen_fbs.cpp.o CMakeFiles/flatc.dir/src/idl_gen_grpc.cpp.o CMakeFiles/flatc.dir/src/idl_gen_json_schema.cpp.o CMakeFiles/flatc.dir/src/idl_gen_swift.cpp.o CMakeFiles/flatc.dir/src/flatc.cpp.o CMakeFiles/flatc.dir/src/flatc_main.cpp.o CMakeFiles/flatc.dir/src/bfbs_gen_lua.cpp.o CMakeFiles/flatc.dir/src/code_generators.cpp.o CMakeFiles/flatc.dir/grpc/src/compiler/cpp_generator.cc.o CMakeFiles/flatc.dir/grpc/src/compiler/go_generator.cc.o CMakeFiles/flatc.dir/grpc/src/compiler/java_generator.cc.o CMakeFiles/flatc.dir/grpc/src/compiler/python_generator.cc.o CMakeFiles/flatc.dir/grpc/src/compiler/swift_generator.cc.o CMakeFiles/flatc.dir/grpc/src/compiler/ts_generator.cc.o -o flatc   -latomic -lm 
Running scripts/generate_code.py...
cd /home/myname/myworkingdir/tflite.build.android/flatbuffers && /usr/bin/python3.9 scripts/generate_code.py --flatc /home/myname/myworkingdir/tflite.build.android/_deps/flatbuffers-build/flatc --skip-gen-reflection
Traceback (most recent call last):
  File "/home/myname/myworkingdir/tflite.build.android/flatbuffers/scripts/generate_code.py", line 148, in <module>
    flatc(
  File "/home/myname/myworkingdir/tflite.build.android/flatbuffers/scripts/generate_code.py", line 82, in flatc
    result = subprocess.run(cmd, cwd=str(cwd), check=True)
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/myname/myworkingdir/tflite.build.android/_deps/flatbuffers-build/flatc'
make[2]: *** [_deps/flatbuffers-build/CMakeFiles/flatc.dir/build.make:566: _deps/flatbuffers-build/flatc] Error 1
make[2]: *** Deleting file '_deps/flatbuffers-build/flatc'
make[2]: Leaving directory '/home/myname/myworkingdir/tflite.build.android'
make[1]: *** [CMakeFiles/Makefile2:4720: _deps/flatbuffers-build/CMakeFiles/flatc.dir/all] Error 2
make[1]: Leaving directory '/home/myname/myworkingdir/tflite.build.android'
make: *** [Makefile:139: all] Error 2
```
</details>

**Comment by Aryanryn09** [comment]
hey i am a beginner in this community can i help you solve this issue

**Comment by tiruk007** [comment]
@Aryanryn09 
Could you please refer to the [Cross compilation TensorFlow Lite with CMake](https://www.tensorflow.org/lite/guide/build_cmake_arm) and [Build TensorFlow Lite with CMake](https://www.tensorflow.org/lite/guide/build_cmake) and let us know if it helps.
Thank you!

**Comment by DwayneDuane** [comment]
@tiruk007, Tensorflow Lite v 2.11.0 was just released, but I get the same build error. I will close this ticket and file a new one for V2.11.0. I tried https://www.tensorflow.org/lite/guide/build_cmake but it doesn't help. Please see the new ticket (https://github.com/tensorflow/tensorflow/issues/58636) for more details.
