### ISSUE TITLE
MoviNet has memory leak

### ISSUE THREAD

**Issue by rsandler00** [tensorflow/tensorflow#58642]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.10.0

### Custom Code

Yes

### OS Platform and Distribution

Windows 10 (recreated in Ubuntu 20.4)

### Mobile device

NA

### Python version

3.9

### CUDA/cuDNN version

11.2 / 8.1

### Current Behaviour?

Repeated inference calls to MoviNet (loaded from SavedModel) continuously increase memory usage until a crash occurs.

### Standalone code to reproduce the issue

The process to recreate is somewhat long, so full code cannot be provided. The steps are:

1. Create movinet network:
```shell
    from official.projects.movinet.modeling import movinet, movinet_layers, movinet_model
    backbone = movinet.Movinet(model_id=model_id)   # output_states=False
    model = movinet_model.MovinetClassifier(backbone=backbone, num_classes=600, output_states=False)
    model.build([1, 1, 1, 1, 3])

    checkpoint_dir = download_and_extract_file(model_id=model_id)
    checkpoint_path = os.path.join(checkpoint_dir, 'ckpt-1')
    checkpoint = tf.train.Checkpoint(model=model)
    status = checkpoint.restore(checkpoint_path)
    status.assert_existing_objects_matched()

    model = build_classifier(backbone=backbone, input_shape= input_shape, num_classes=n_output_classes,
                             movinet_layers_to_freeze = movinet_layers_to_freeze)
```

2. Fine-tune the model

3. Convert to savedmodel:
```
tf.keras.models.save_model(self.net, path, signatures=None)
```

4. Load savedmodel:
```
model = tf.keras.models.load_model(savedmodel_path, custom_objects={'tf': tf, 'K': tf.keras.backend})
```

5. Perform inference in a for loop:
```
for i in range(n_samples):
    out[i] = model(input[i], training=training)
```

### Relevant log output

I have ran this from my Windows PC, as well as EC2 instances with and without a GPU. I used ClearML to log machine stats over iterations and saw the following:

CPU-Only:
![image](https://user-images.githubusercontent.com/19536781/203179971-490e64f6-b198-43c6-a2dc-500c8190ccae.png)

Note that in the beginning, there is alot of writing to disk (orange) while RAM stays constant (blue). After a certain amount of writing to disk, RAM starts being used until it is depleted and program crashes. 

GPU:
The same behavior appears on GPU machines, with the addition that when it starts writing to RAM, GPU starts filling up as well (top plot, blue/green lines):
![image](https://user-images.githubusercontent.com/19536781/203180382-19affc22-bd43-4dc0-8a48-e97e7e80422d.png)

I have tried this on my windows machine as well, and observed the same behavior (RAM usage increasing until crash occurs) in Task Manager. 

```
</details>

**Comment by Hyperparticle** [comment]
Thank you for the detailed info, it's quite useful.

I've not been aware of any memory leaks throughout my testing of MoViNet, but I could give you some pointers on helping you diagnose the issue.

1. Which version of the model are you using? If it's the default a non-streaming version, then it would be very strange to experience any kind of memory leak, as the model itself should not be storing anything. If you made any of your own modifications, please give a short description.
2. Given that this issue has not been brought up before (to the best of my knowledge), could you try exporting and running the model with an earlier version of TensorFlow, i.e., a version built more than 6 months ago? Perhaps a newly introduced bug in TF is introducing the memory leak.
3. How are you doing the savedmodel export? Can you try running the original savedmodel or TF Lite model from TF Hub? If the original exported model does not have the issue, then there might be some bug in the export logic with `tf.keras.models.save_model`. I've had some weird issues before when running `save_model`, so it might be worth investigating.
4. Is your own internal logic saving anything between loops? Does the issue go away if you swap out the model with a trivial savedmodel that takes the input image and outputs a label?

I hope these help. If you can try to give more info from some of the above steps, this can help me provide more targeted assistance.

**Comment by sushreebarsa** [comment]
@rsandler00 Could you please refer the comment above and provide the update on this ?
Thank you!

**Comment by rsandler00** [comment]
1. Not sure what you mean by "model version", but I am using a2. I load it as described above:
```
 backbone = movinet.Movinet(model_id=model_id)   # output_states=False
    model = movinet_model.MovinetClassifier(backbone=backbone, num_classes=600, output_states=False)
    ```
2. I tested w/ 2.8.1 ad had the same issue
3. To convert to savedmodel I do:
```
tf.keras.models.save_model(self.net, path, signatures=None)
```
I have not tried w/ hub version, but I will do so soon
4. I thoroughly tested w/ other models and very basic for loops, and that is not the issue. 

I can also upload the savedmodel files w/ minimally reproducable code to replicate:
```
import numpy as np
import tensorflow as tf
import psutil
from tqdm import tqdm 

from algorithms.model import Model # internal code needed to successfully load savedmodel due to presumed bug

model = tf.keras.models.load_model(savedmodel_path, custom_objects={'tf': tf, 'K': tf.keras.backend, 'Model': 3})
input = np.random.random((1, 20, 256, 256, 3))
for i in tqdm(range(30)):
    if i % 3 == 0:
        mem_info = psutil.virtual_memory()._asdict()
        print(f'(i={i}) RAM Used: {mem_info["used"] / 1e9:.2f} GB ({mem_info["percent"]}%)')
    model(input)
```

**Comment by rsandler00** [comment]
Ok, I was just able to fully reproduce the issue w/ the SavedModel from TFHub. 

I downloaded the following SavedModel file: https://tfhub.dev/tensorflow/movinet/a2/base/kinetics-600/classification/3


And reproduced w/ this code:
```
import numpy as np
import tensorflow as tf
import psutil
from tqdm import tqdm

# This import is critical for savedmodel to load correctly cuz of weird TF savedmodel voodoo...
from official.projects.movinet.modeling import movinet, movinet_layers, movinet_model

# path to DLd SM file from https://tfhub.dev/tensorflow/movinet/a2/base/kinetics-600/classification/3
savedmodel_path = 'C:\\Users\\Administrator\\Downloads\sm'  

model = tf.keras.models.load_model(savedmodel_path, custom_objects={'tf': tf, 'K': tf.keras.backend})
input = np.random.random((1, 20, 256, 256, 3))
for i in tqdm(range(30)):
    if i % 3 == 0:
        mem_info = psutil.virtual_memory()._asdict()
        print(f'(i={i}) RAM Used: {mem_info["used"] / 1e9:.2f} GB ({mem_info["percent"]}%)')
    model(input)
```

This is my full console output. Notice RAM printouts at the end - in 30 samples my RAM usage went from 69.3% to 72.7%. This trend continues until crash due to no RAM...

```
C:\code\ai_dev\venv\Scripts\python.exe "C:\Program Files\JetBrains\PyCharm Community Edition 2021.3\plugins\python-ce\helpers\pydev\pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 62770 --file C:/Users/Administrator/AppData/Roaming/JetBrains/PyCharmCE2021.3/scratches/scratch_1.py
Connected to pydev debugger (build 213.5744.248)
C:\code\ai_dev\venv\lib\site-packages\tensorflow_addons\utils\ensure_tf_install.py:53: UserWarning: Tensorflow Addons supports using Python ops for all Tensorflow versions above or equal to 2.4.0 and strictly below 2.7.0 (nightly versions are not supported). 
 The versions of TensorFlow you are currently using is 2.10.0 and is not supported. 
Some things might work, some things might not.
If you were to encounter a bug, do not file an issue.
If you want to make sure you're using a tested and supported configuration, either change the TensorFlow version or the TensorFlow Addons's version. 
You can find the compatibility matrix in TensorFlow Addon's readme:
https://github.com/tensorflow/addons
  warnings.warn(
import sys; print('Python %s on %s' % (sys.version, sys.platform))
model = tf.keras.models.load_model(savedmodel_path, custom_objects={'tf': tf, 'K': tf.keras.backend})
Python 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 14:02:34) [MSC v.1928 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.30.1 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 7.30.1
Python 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 14:02:34) [MSC v.1928 64 bit (AMD64)] on win32
2022-11-27 11:53:08.375774: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-11-27 11:53:08.695317: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 7440 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3080, pci bus id: 0000:0a:00.0, compute capability: 8.6
w
Traceback (most recent call last):
  File "C:\code\ai_dev\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-74c7db5447c3>", line 1, in <module>
    w
NameError: name 'w' is not defined
input = np.random.random((1, 20, 256, 256, 3))
for i in tqdm(range(30)):
    if i % 3 == 0:
        mem_info = psutil.virtual_memory()._asdict()
        print(f'(i={i}) RAM Used: {mem_info["used"] / 1e9:.2f} GB ({mem_info["percent"]}%)')
    model(input)
w=4
  0%|          | 0/30 [00:00<?, ?it/s]2022-11-27 11:53:37.042835: I tensorflow/compiler/xla/service/service.cc:173] XLA service 0x27b9ed76e10 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
(i=0) RAM Used: 20.93 GB (61.1%)
2022-11-27 11:53:37.042982: I tensorflow/compiler/xla/service/service.cc:181]   StreamExecutor device (0): NVIDIA GeForce RTX 3080, Compute Capability 8.6
2022-11-27 11:53:37.645016: I tensorflow/stream_executor/cuda/cuda_dnn.cc:384] Loaded cuDNN version 8101
2022-11-27 11:53:39.400588: I tensorflow/compiler/jit/xla_compilation_cache.cc:476] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
2022-11-27 11:53:40.230562: I tensorflow/stream_executor/cuda/cuda_dnn.cc:5025] Disabling cuDNN frontend for the following convolution:
  input: {count: 1 feature_map_count: 40 spatial: 1 1 1  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX}
  filter: {output_feature_map_count: 16 input_feature_map_count: 40 layout: OutputInputYX shape: 1 1 1 }
  {zero_padding: 0 0 0  pad_alignment: default filter_strides: 1 1 1  dilation_rates: 1 1 1 }
  ... because it uses an identity activation.
2022-11-27 11:53:40.313617: I tensorflow/stream_executor/cuda/cuda_dnn.cc:5025] Disabling cuDNN frontend for the following convolution:
  input: {count: 1 feature_map_count: 16 spatial: 1 1 1  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX}
  filter: {output_feature_map_count: 40 input_feature_map_count: 16 layout: OutputInputYX shape: 1 1 1 }
  {zero_padding: 0 0 0  pad_alignment: default filter_strides: 1 1 1  dilation_rates: 1 1 1 }
  ... because it uses an identity activation.
WARNING:tensorflow:5 out of the last 5 calls to <bound method Conv.call of <official.vision.modeling.layers.nn_layers.Conv3D object at 0x0000027B9B049A00>> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:5 out of the last 5 calls to <bound method Conv.call of <official.vision.modeling.layers.nn_layers.Conv3D object at 0x0000027B9B049A00>> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:6 out of the last 6 calls to <bound method Conv.call of <official.vision.modeling.layers.nn_layers.Conv3D object at 0x0000027B9B15C3A0>> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:6 out of the last 6 calls to <bound method Conv.call of <official.vision.modeling.layers.nn_layers.Conv3D object at 0x0000027B9B15C3A0>> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
2022-11-27 11:53:40.904291: W tensorflow/compiler/xla/service/gpu/gpu_conv_algorithm_picker.cc:727] None of the algorithms provided by cuDNN heuristics worked; trying fallback algorithms.  Conv: (f32[1,20,64,64,40]{3,2,1,4,0}, u8[0]{0}) custom-call(f32[1,20,64,64,40]{3,2,1,4,0}, f32[3,3,3,1,40]{2,1,0,3,4}), window={size=3x3x3 pad=1_1x1_1x1_1}, dim_labels=b012f_012io->b012f, feature_group_count=40, custom_call_target="__cudnn$convForward", backend_config="{\"conv_result_scale\":1,\"activation_mode\":\"0\",\"side_input_scale\":0}"
2022-11-27 11:53:42.140495: W tensorflow/compiler/xla/service/gpu/gpu_conv_algorithm_picker.cc:727] None of the algorithms provided by cuDNN heuristics worked; trying fallback algorithms.  Conv: (f32[1,20,64,64,64]{3,2,1,4,0}, u8[0]{0}) custom-call(f32[1,20,64,64,64]{3,2,1,4,0}, f32[3,3,3,1,64]{2,1,0,3,4}), window={size=3x3x3 pad=1_1x1_1x1_1}, dim_labels=b012f_012io->b012f, feature_group_count=64, custom_call_target="__cudnn$convForward", backend_config="{\"conv_result_scale\":1,\"activation_mode\":\"0\",\"side_input_scale\":0}"
2022-11-27 11:53:42.457439: I tensorflow/stream_executor/cuda/cuda_dnn.cc:5025] Disabling cuDNN frontend for the following convolution:
  input: {count: 1 feature_map_count: 64 spatial: 1 1 1  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX}
  filter: {output_feature_map_count: 16 input_feature_map_count: 64 layout: OutputInputYX shape: 1 1 1 }
  {zero_padding: 0 0 0  pad_alignment: default filter_strides: 1 1 1  dilation_rates: 1 1 1 }
  ... because it uses an identity activation.
2022-11-27 11:53:42.526737: I tensorflow/stream_executor/cuda/cuda_dnn.cc:5025] Disabling cuDNN frontend for the following convolution:
  input: {count: 1 feature_map_count: 16 spatial: 1 1 1  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX}
  filter: {output_feature_map_count: 64 input_feature_map_count: 16 layout: OutputInputYX shape: 1 1 1 }
  {zero_padding: 0 0 0  pad_alignment: default filter_strides: 1 1 1  dilation_rates: 1 1 1 }
  ... because it uses an identity activation.
2022-11-27 11:53:43.005281: I tensorflow/stream_executor/cuda/cuda_dnn.cc:5025] Disabling cuDNN frontend for the following convolution:
  input: {count: 1 feature_map_count: 96 spatial: 1 1 1  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX}
  filter: {output_feature_map_count: 24 input_feature_map_count: 96 layout: OutputInputYX shape: 1 1 1 }
  {zero_padding: 0 0 0  pad_alignment: default filter_strides: 1 1 1  dilation_rates: 1 1 1 }
  ... because it uses an identity activation.
2022-11-27 11:53:43.080687: I tensorflow/stream_executor/cuda/cuda_dnn.cc:5025] Disabling cuDNN frontend for the following convolution:
  input: {count: 1 feature_map_count: 24 spatial: 1 1 1  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX}
  filter: {output_feature_map_count: 96 input_feature_map_count: 24 layout: OutputInputYX shape: 1 1 1 }
  {zero_padding: 0 0 0  pad_alignment: default filter_strides: 1 1 1  dilation_rates: 1 1 1 }
  ... because it uses an identity activation.
2022-11-27 11:53:43.557255: W tensorflow/compiler/xla/service/gpu/gpu_conv_algorithm_picker.cc:727] None of the algorithms provided by cuDNN heuristics worked; trying fallback algorithms.  Conv: (f32[1,20,32,32,120]{3,2,1,4,0}, u8[0]{0}) custom-call(f32[1,20,32,32,120]{3,2,1,4,0}, f32[3,3,3,1,120]{2,1,0,3,4}), window={size=3x3x3 pad=1_1x1_1x1_1}, dim_labels=b012f_012io->b012f, feature_group_count=120, custom_call_target="__cudnn$convForward", backend_config="{\"conv_result_scale\":1,\"activation_mode\":\"0\",\"side_input_scale\":0}"
2022-11-27 11:53:43.766094: I tensorflow/stream_executor/cuda/cuda_dnn.cc:5025] Disabling cuDNN frontend for the following convolution:
  input: {count: 1 feature_map_count: 120 spatial: 1 1 1  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX}
  filter: {output_feature_map_count: 32 input_feature_map_count: 120 layout: OutputInputYX shape: 1 1 1 }
  {zero_padding: 0 0 0  pad_alignment: default filter_strides: 1 1 1  dilation_rates: 1 1 1 }
  ... because it uses an identity activation.
2022-11-27 11:53:43.840040: I tensorflow/stream_executor/cuda/cuda_dnn.cc:5025] Disabling cuDNN frontend for the following convolution:
  input: {count: 1 feature_map_count: 32 spatial: 1 1 1  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX}
  filter: {output_feature_map_count: 120 input_feature_map_count: 32 layout: OutputInputYX shape: 1 1 1 }
  {zero_padding: 0 0 0  pad_alignment: default filter_strides: 1 1 1  dilation_rates: 1 1 1 }
  ... because it uses an identity activation.
2022-11-27 11:53:44.196746: W tensorflow/compiler/xla/service/gpu/gpu_conv_algorithm_picker.cc:727] None of the algorithms provided by cuDNN heuristics worked; trying fallback algorithms.  Conv: (f32[1,20,32,32,96]{3,2,1,4,0}, u8[0]{0}) custom-call(f32[1,20,32,32,96]{3,2,1,4,0}, f32[3,3,3,1,96]{2,1,0,3,4}), window={size=3x3x3 pad=1_1x1_1x1_1}, dim_labels=b012f_012io->b012f, feature_group_count=96, custom_call_target="__cudnn$convForward", backend_config="{\"conv_result_scale\":1,\"activation_mode\":\"0\",\"side_input_scale\":0}"
2022-11-27 11:53:45.005478: I tensorflow/stream_executor/cuda/cuda_dnn.cc:5025] Disabling cuDNN frontend for the following convolution:
  input: {count: 1 feature_map_count: 240 spatial: 1 1 1  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX}
  filter: {output_feature_map_count: 64 input_feature_map_count: 240 layout: OutputInputYX shape: 1 1 1 }
  {zero_padding: 0 0 0  pad_alignment: default filter_strides: 1 1 1  dilation_rates: 1 1 1 }
  ... because it uses an identity activation.
2022-11-27 11:53:45.076900: I tensorflow/stream_executor/cuda/cuda_dnn.cc:5025] Disabling cuDNN frontend for the following convolution:
  input: {count: 1 feature_map_count: 64 spatial: 1 1 1  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX}
  filter: {output_feature_map_count: 240 input_feature_map_count: 64 layout: OutputInputYX shape: 1 1 1 }
  {zero_padding: 0 0 0  pad_alignment: default filter_strides: 1 1 1  dilation_rates: 1 1 1 }
  ... because it uses an identity activation.
2022-11-27 11:53:45.779619: I tensorflow/stream_executor/cuda/cuda_dnn.cc:5025] Disabling cuDNN frontend for the following convolution:
  input: {count: 1 feature_map_count: 160 spatial: 1 1 1  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX}
  filter: {output_feature_map_count: 40 input_feature_map_count: 160 layout: OutputInputYX shape: 1 1 1 }
  {zero_padding: 0 0 0  pad_alignment: default filter_strides: 1 1 1  dilation_rates: 1 1 1 }
  ... because it uses an identity activation.
2022-11-27 11:53:45.865167: I tensorflow/stream_executor/cuda/cuda_dnn.cc:5025] Disabling cuDNN frontend for the following convolution:
  input: {count: 1 feature_map_count: 40 spatial: 1 1 1  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX}
  filter: {output_feature_map_count: 160 input_feature_map_count: 40 layout: OutputInputYX shape: 1 1 1 }
  {zero_padding: 0 0 0  pad_alignment: default filter_strides: 1 1 1  dilation_rates: 1 1 1 }
  ... because it uses an identity activation.
2022-11-27 11:53:46.997732: I tensorflow/stream_executor/cuda/cuda_dnn.cc:5025] Disabling cuDNN frontend for the following convolution:
  input: {count: 1 feature_map_count: 192 spatial: 1 1 1  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX}
  filter: {output_feature_map_count: 48 input_feature_map_count: 192 layout: OutputInputYX shape: 1 1 1 }
  {zero_padding: 0 0 0  pad_alignment: default filter_strides: 1 1 1  dilation_rates: 1 1 1 }
  ... because it uses an identity activation.
2022-11-27 11:53:47.083829: I tensorflow/stream_executor/cuda/cuda_dnn.cc:5025] Disabling cuDNN frontend for the following convolution:
  input: {count: 1 feature_map_count: 48 spatial: 1 1 1  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX}
  filter: {output_feature_map_count: 192 input_feature_map_count: 48 layout: OutputInputYX shape: 1 1 1 }
  {zero_padding: 0 0 0  pad_alignment: default filter_strides: 1 1 1  dilation_rates: 1 1 1 }
  ... because it uses an identity activation.
2022-11-27 11:53:48.990525: I tensorflow/stream_executor/cuda/cuda_dnn.cc:5025] Disabling cuDNN frontend for the following convolution:
  input: {count: 1 feature_map_count: 144 spatial: 1 1 1  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX}
  filter: {output_feature_map_count: 40 input_feature_map_count: 144 layout: OutputInputYX shape: 1 1 1 }
  {zero_padding: 0 0 0  pad_alignment: default filter_strides: 1 1 1  dilation_rates: 1 1 1 }
  ... because it uses an identity activation.
2022-11-27 11:53:49.068802: I tensorflow/stream_executor/cuda/cuda_dnn.cc:5025] Disabling cuDNN frontend for the following convolution:
  input: {count: 1 feature_map_count: 40 spatial: 1 1 1  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX}
  filter: {output_feature_map_count: 144 input_feature_map_count: 40 layout: OutputInputYX shape: 1 1 1 }
  {zero_padding: 0 0 0  pad_alignment: default filter_strides: 1 1 1  dilation_rates: 1 1 1 }
  ... because it uses an identity activation.
2022-11-27 11:53:49.729509: I tensorflow/stream_executor/cuda/cuda_dnn.cc:5025] Disabling cuDNN frontend for the following convolution:
  input: {count: 1 feature_map_count: 480 spatial: 1 1 1  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX}
  filter: {output_feature_map_count: 120 input_feature_map_count: 480 layout: OutputInputYX shape: 1 1 1 }
  {zero_padding: 0 0 0  pad_alignment: default filter_strides: 1 1 1  dilation_rates: 1 1 1 }
  ... because it uses an identity activation.
2022-11-27 11:53:49.804658: I tensorflow/stream_executor/cuda/cuda_dnn.cc:5025] Disabling cuDNN frontend for the following convolution:
  input: {count: 1 feature_map_count: 120 spatial: 1 1 1  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX}
  filter: {output_feature_map_count: 480 input_feature_map_count: 120 layout: OutputInputYX shape: 1 1 1 }
  {zero_padding: 0 0 0  pad_alignment: default filter_strides: 1 1 1  dilation_rates: 1 1 1 }
  ... because it uses an identity activation.
2022-11-27 11:53:50.376111: I tensorflow/stream_executor/cuda/cuda_dnn.cc:5025] Disabling cuDNN frontend for the following convolution:
  input: {count: 1 feature_map_count: 384 spatial: 1 1 1  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX}
  filter: {output_feature_map_count: 96 input_feature_map_count: 384 layout: OutputInputYX shape: 1 1 1 }
  {zero_padding: 0 0 0  pad_alignment: default filter_strides: 1 1 1  dilation_rates: 1 1 1 }
  ... because it uses an identity activation.
2022-11-27 11:53:50.469892: I tensorflow/stream_executor/cuda/cuda_dnn.cc:5025] Disabling cuDNN frontend for the following convolution:
  input: {count: 1 feature_map_count: 96 spatial: 1 1 1  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX}
  filter: {output_feature_map_count: 384 input_feature_map_count: 96 layout: OutputInputYX shape: 1 1 1 }
  {zero_padding: 0 0 0  pad_alignment: default filter_strides: 1 1 1  dilation_rates: 1 1 1 }
  ... because it uses an identity activation.
2022-11-27 11:53:51.732227: I tensorflow/stream_executor/cuda/cuda_dnn.cc:5025] Disabling cuDNN frontend for the following convolution:
  input: {count: 1 feature_map_count: 576 spatial: 1 1 1  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX}
  filter: {output_feature_map_count: 144 input_feature_map_count: 576 layout: OutputInputYX shape: 1 1 1 }
  {zero_padding: 0 0 0  pad_alignment: default filter_strides: 1 1 1  dilation_rates: 1 1 1 }
  ... because it uses an identity activation.
2022-11-27 11:53:51.819448: I tensorflow/stream_executor/cuda/cuda_dnn.cc:5025] Disabling cuDNN frontend for the following convolution:
  input: {count: 1 feature_map_count: 144 spatial: 1 1 1  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX}
  filter: {output_feature_map_count: 576 input_feature_map_count: 144 layout: OutputInputYX shape: 1 1 1 }
  {zero_padding: 0 0 0  pad_alignment: default filter_strides: 1 1 1  dilation_rates: 1 1 1 }
  ... because it uses an identity activation.
2022-11-27 11:53:52.173105: I tensorflow/stream_executor/cuda/cuda_dnn.cc:5025] Disabling cuDNN frontend for the following convolution:
  input: {count: 1 feature_map_count: 640 spatial: 1 1 1  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX}
  filter: {output_feature_map_count: 2048 input_feature_map_count: 640 layout: OutputInputYX shape: 1 1 1 }
  {zero_padding: 0 0 0  pad_alignment: default filter_strides: 1 1 1  dilation_rates: 1 1 1 }
  ... because it uses an identity activation.
2022-11-27 11:53:52.282455: I tensorflow/stream_executor/cuda/cuda_dnn.cc:5025] Disabling cuDNN frontend for the following convolution:
  input: {count: 1 feature_map_count: 2048 spatial: 1 1 1  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX}
  filter: {output_feature_map_count: 600 input_feature_map_count: 2048 layout: OutputInputYX shape: 1 1 1 }
  {zero_padding: 0 0 0  pad_alignment: default filter_strides: 1 1 1  dilation_rates: 1 1 1 }
  ... because it uses an identity activation.
 10%|█         | 3/30 [00:25<03:14,  7.19s/it](i=3) RAM Used: 23.75 GB (69.3%)
 20%|██        | 6/30 [00:39<02:10,  5.42s/it](i=6) RAM Used: 23.90 GB (69.7%)
 30%|███       | 9/30 [00:53<01:44,  5.00s/it](i=9) RAM Used: 24.04 GB (70.1%)
 40%|████      | 12/30 [01:08<01:28,  4.94s/it](i=12) RAM Used: 24.44 GB (71.3%)
 50%|█████     | 15/30 [01:23<01:13,  4.92s/it](i=15) RAM Used: 24.55 GB (71.6%)
 60%|██████    | 18/30 [01:38<00:59,  4.93s/it](i=18) RAM Used: 24.66 GB (72.0%)
 70%|███████   | 21/30 [01:52<00:43,  4.81s/it](i=21) RAM Used: 24.63 GB (71.9%)
 80%|████████  | 24/30 [02:06<00:28,  4.71s/it](i=24) RAM Used: 24.77 GB (72.3%)
 90%|█████████ | 27/30 [02:20<00:13,  4.65s/it](i=27) RAM Used: 24.92 GB (72.7%)
100%|██████████| 30/30 [02:33<00:00,  5.13s/it]
```

**Comment by Hyperparticle** [comment]
I suspect there might be some issue with `tf.function` retracing, as evidenced by this warning:
```
WARNING:tensorflow:5 out of the last 5 calls to <bound method Conv.call> triggered tf.function retracing.
```

It's very possible that a new graph is being constructed on each call, causing them to build up in memory. We have a `tf.function` wrapper around our 3D convolution [here](https://github.com/tensorflow/models/blob/master/official/vision/modeling/layers/nn_layers.py#L1053), which I believe is what is being retraced.


I believe by default we recommend wrapping the entire savedmodel in a `tf.function` to optimize the entire graph.

Can you try something like this in your code?

```python
model = tf.keras.models.load_model(...)
model = tf.function(model, jit_compile=True)  # Can also try the reduce_retracing=True option, or set jit_compile=False
```

I would also try swapping out a2 base with a2 stream ([hub link](https://tfhub.dev/tensorflow/movinet/a2/stream/kinetics-600/classification/3), [docs](https://github.com/tensorflow/models/tree/master/official/projects/movinet#prediction-examples)), as that version uses (2+1)D convolutions and should not have the tf.function wrapper.

Let me know once you've tried a few of these options. Thanks for continuing to provide detailed info!

**Comment by rsandler00** [comment]
@Hyperparticle using 
```
model = tf.function(model, jit_compile=True)
```
Did indeed solve the problem! Thanks so much!

**Comment by Hyperparticle** [comment]
Excellent! Glad I could help. Please reopen this issue if you still have a memory leak, or open a new one if you encounter a different issue.

**Comment by sushreebarsa** [comment]
@rsandler00 Could you please confirm if this issue has been resolved and close this ticket?
Thank you!
