### ISSUE TITLE
Have TensorFlow Lite convert keras.LSTM layers without requiring Flex ops

### ISSUE THREAD

**Issue by andreasavio** [tensorflow/tensorflow#58668]
**System information**
- OS Platform and Distribution: macOS Monterey 12.6
- TensorFlow installed from: binary
- TensorFlow version: 2.10.0
- Keras version: 2.10.0

**Provide the text output from tflite_convert**

```python
2022-11-24 12:05:13.342007: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-11-24 12:05:16.822583: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:absl:Found untraced functions such as lstm_cell_layer_call_fn, lstm_cell_layer_call_and_return_conditional_losses while saving (showing 2 of 2). These functions will not be directly callable after loading.
2022-11-24 12:05:47.471765: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:362] Ignored output_format.
2022-11-24 12:05:47.471809: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:365] Ignored drop_control_dependency.
2022-11-24 12:05:47.472616: I tensorflow/cc/saved_model/reader.cc:45] Reading SavedModel from: /var/folders/sn/0dslr5js3rz6pht1s02qxbf00000gr/T/tmpl3_86lch
2022-11-24 12:05:47.484736: I tensorflow/cc/saved_model/reader.cc:89] Reading meta graph with tags { serve }
2022-11-24 12:05:47.484760: I tensorflow/cc/saved_model/reader.cc:130] Reading SavedModel debug info (if present) from: /var/folders/sn/0dslr5js3rz6pht1s02qxbf00000gr/T/tmpl3_86lch
2022-11-24 12:05:47.528960: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:354] MLIR V1 optimization pass is not enabled
2022-11-24 12:05:47.536418: I tensorflow/cc/saved_model/loader.cc:229] Restoring SavedModel bundle.
2022-11-24 12:05:47.592653: I tensorflow/cc/saved_model/loader.cc:213] Running initialization op on SavedModel bundle at path: /var/folders/sn/0dslr5js3rz6pht1s02qxbf00000gr/T/tmpl3_86lch
2022-11-24 12:05:47.635483: I tensorflow/cc/saved_model/loader.cc:305] SavedModel load for tags { serve }; Status: success: OK. Took 162893 microseconds.
2022-11-24 12:05:47.754083: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
loc(callsite(callsite(callsite(fused["TensorListReserve:", callsite("TensorArrayV2_1@__inference_standard_lstm_639"("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/python/saved_model/save.py":1268:0) at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/python/saved_model/save.py":1232:0 at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":1249:0 at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/convert_phase.py":205:0 at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":1319:0 at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":1339:0 at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":908:0 at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":930:0 at "/Users/andreasavio/yousician/dsp_research/tensorflow/test.py":26:0))))))))] at fused["PartitionedCall:", callsite("model/lstm/PartitionedCall@__inference__wrapped_model_912"("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/python/saved_model/save.py":1268:0) at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/python/saved_model/save.py":1232:0 at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":1249:0 at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/convert_phase.py":205:0 at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":1319:0 at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":1339:0 at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":908:0 at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":930:0 at "/Users/andreasavio/yousician/dsp_research/tensorflow/test.py":26:0))))))))]) at fused["StatefulPartitionedCall:", callsite("StatefulPartitionedCall@__inference_signature_wrapper_2769"("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/python/saved_model/save.py":1268:0) at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/python/saved_model/save.py":1232:0 at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":1249:0 at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/convert_phase.py":205:0 at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":1319:0 at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":1339:0 at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":908:0 at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":930:0 at "/Users/andreasavio/yousician/dsp_research/tensorflow/test.py":26:0))))))))]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"])): error: 'tf.TensorListReserve' op requires element_shape to be static during TF Lite transformation pass
loc(callsite(callsite(callsite(fused["TensorListReserve:", callsite("TensorArrayV2_1@__inference_standard_lstm_639"("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/python/saved_model/save.py":1268:0) at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/python/saved_model/save.py":1232:0 at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":1249:0 at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/convert_phase.py":205:0 at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":1319:0 at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":1339:0 at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":908:0 at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":930:0 at "/Users/andreasavio/yousician/dsp_research/tensorflow/test.py":26:0))))))))] at fused["PartitionedCall:", callsite("model/lstm/PartitionedCall@__inference__wrapped_model_912"("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/python/saved_model/save.py":1268:0) at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/python/saved_model/save.py":1232:0 at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":1249:0 at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/convert_phase.py":205:0 at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":1319:0 at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":1339:0 at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":908:0 at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":930:0 at "/Users/andreasavio/yousician/dsp_research/tensorflow/test.py":26:0))))))))]) at fused["StatefulPartitionedCall:", callsite("StatefulPartitionedCall@__inference_signature_wrapper_2769"("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/python/saved_model/save.py":1268:0) at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/python/saved_model/save.py":1232:0 at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":1249:0 at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/convert_phase.py":205:0 at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":1319:0 at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":1339:0 at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":908:0 at callsite("/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":930:0 at "/Users/andreasavio/yousician/dsp_research/tensorflow/test.py":26:0))))))))]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"])): error: failed to legalize operation 'tf.TensorListReserve' that was explicitly marked illegal
error: Lowering tensor list ops is failed. Please consider using Select TF ops and disabling `_experimental_lower_tensor_list_ops` flag in the TFLite converter object. For example, converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]\n converter._experimental_lower_tensor_list_ops = False
Traceback (most recent call last):
  File "/Users/andreasavio/yousician/dsp_research/tensorflow/test.py", line 26, in <module>
    content = converter.convert()
  File "/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 930, in wrapper
    return self._convert_and_export_metrics(convert_func, *args, **kwargs)
  File "/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 908, in _convert_and_export_metrics
    result = convert_func(self, *args, **kwargs)
  File "/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 1339, in convert
    saved_model_convert_result = self._convert_as_saved_model()
  File "/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 1322, in _convert_as_saved_model
    self).convert(graph_def, input_tensors, output_tensors)
  File "/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 1132, in convert
    result = _convert_graphdef(
  File "/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/convert_phase.py", line 212, in wrapper
    raise converter_error from None  # Re-throws the exception.
  File "/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/convert_phase.py", line 205, in wrapper
    return func(*args, **kwargs)
  File "/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/convert.py", line 794, in convert_graphdef
    data = convert(
  File "/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/lite/python/convert.py", line 311, in convert
    raise converter_error
tensorflow.lite.python.convert_phase.ConverterError: /Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/python/saved_model/save.py:1268:0: error: 'tf.TensorListReserve' op requires element_shape to be static during TF Lite transformation pass
<unknown>:0: note: loc(fused["StatefulPartitionedCall:", "StatefulPartitionedCall"]): called from
/Users/andreasavio/yousician/tensorflow_distros/2.10.0/lib/python3.10/site-packages/tensorflow/python/saved_model/save.py:1268:0: error: failed to legalize operation 'tf.TensorListReserve' that was explicitly marked illegal
<unknown>:0: note: loc(fused["StatefulPartitionedCall:", "StatefulPartitionedCall"]): called from
<unknown>:0: error: Lowering tensor list ops is failed. Please consider using Select TF ops and disabling `_experimental_lower_tensor_list_ops` flag in the TFLite converter object. For example, converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]\n converter._experimental_lower_tensor_list_ops = False
```

**Standalone code to reproduce the issue** 

```python
import tensorflow as tf
import keras

num_rows = 10
num_cols = 10

model_input = keras.layers.Input(shape=(num_rows, num_cols))
model_output = keras.layers.LSTM(
    input_shape=(num_rows, num_cols),
    units=2,
    return_sequences=True,
    kernel_initializer="glorot_uniform",
    recurrent_initializer="orthogonal",
    unit_forget_bias=True,
    recurrent_activation="sigmoid",
    activation="tanh",
)(model_input)

model = keras.Model(inputs=[model_input], outputs=model_output)
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS,
    tf.lite.OpsSet.SELECT_TF_OPS # Conversion fails without this line
]

content = converter.convert()
```

The model consists of a single Keras `LSTM` layer, other than the input.

**Any other info / logs**

In TensorFlow 2.10, models that contain `LSTM` layers from Keras require Flex ops when exported to TensorFlow Lite. Since TensorFlow Lite seems to have its own in-built [LSTM op](https://www.tensorflow.org/mlir/tfl_ops#tflbasic_lstm_mlirtflbasiclstmop), would it be possible to avoid Flex ops in the conversion above?

**Comment by tiruk007** [comment]
@andreasavio 
Sorry for the late reply.
I tried with an alternate approach to convert the model on Colab using TF v2.10. Could you please find the gist [here](https://colab.research.google.com/gist/tiruk007/f05a6e2a47943ae1e04495f306ef5c71/58668.ipynb) for reference and let us know if it helps.
Thank you!
