### ISSUE TITLE
AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute '_unique_id'

### ISSUE THREAD

**Issue by AngraPatrick** [tensorflow/tensorflow#58686]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.10

### Custom Code

Yes

### OS Platform and Distribution

Debian64 ( Unix )

### Python version

3.10.4

### Current Behaviour?

```shell
Hello to Everyone

I need to training an Actor network for a reinforcement learning algorithm but in time i am trying to predict continuous actions i have a problem with the function: 

self.Actor.optimizer.apply_gradients ( zip ( grads2 , std ) )

also this one gives me the same error:
self.Actor.optimizer.apply_gradients ( zip ( [ grads1 , grads2 ] , [ self.Actor.model.trainable_variables , std ] ) )

Please note that with the following function all goes well:
self.Actor.optimizer.minimize ( loss_actions , var_list = [ self.Actor.model.trainable_variables , std ] , tape = tape_actions )

the problem seems to be caused by the external variable std ( that it is not internal to the model ), Did I make some mistakes? is there a way to clip_by_norm the std variable's gradients ?

Best Regards Samir
```

### Standalone code to reproduce the issue

```shell
one = tf.ones ( self.settings.action_size , dtype = float )
std = tf.Variable ( one , dtype = float , name = 'std' )

sample = self.replay.sample ()

with tf.GradientTape ( persistent = False ) as tape_actions :
     tape_actions.reset ()
               
     actions_local = self.Actor.model ( sample [ 0 ] )

     tfp_dist  = tfp.distributions.Normal ( loc = actions_local , scale = std )
     new_probs = tfp_dist.log_prob        (       sample [ 1 ]                )
     new_probs = tf.math.reduce_sum       (       new_probs     , axis  = 1   )
     new_probs = tf.math.exp              (       new_probs                   )

     ratio = new_probs / sample [ 3 ] # >= 0

     ratio = tf.math.reduce_min (
             tf.convert_to_tensor ( [ ratio * sample [ 4 ] , \
             tf.clip_by_value     (   ratio , clip_value_min = 1 - 0.1 ,
                                              clip_value_max = 1 + 0.1 ) * sample [ 4 ] ] ) ,
                                   axis = 0 )

     loss_actions = - tf.math.reduce_mean ( ratio )

grads = tape_actions.gradient ( loss_actions , [ self.Actor.model.trainable_variables , std ] )

grads1 = [ tf.clip_by_norm ( t = w , clip_norm = 0.75 ) for w in grads [ 0 ] ]
grads2 = [ tf.clip_by_norm ( t = w , clip_norm = 0.75 ) for w in grads [ 1 ] ]

self.Actor.optimizer.apply_gradients ( zip ( grads1 , self.Actor.model.trainable_variables ) )
self.Actor.optimizer.apply_gradients ( zip ( grads2 ,                                  std ) )
```

### Relevant log output

```shell
1/1250/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "/home/kaumi/Git/deepL_RL2/4.ML_Agents/14.p2_continuous-control/Reacher_exam_code/Reacher.py", line 43, in <module>
    future.cross_entropy_loss ()
  File "/home/kaumi/Git/deepL_RL2/4.ML_Agents/14.p2_continuous-control/Reacher_exam_code/agent.py", line 295, in cross_entropy_loss
    self.play_EP ( ie , self.settings.envs.reset ( train_mode = True ) [ self.settings.brain_name ] )
  File "/home/kaumi/Git/deepL_RL2/4.ML_Agents/14.p2_continuous-control/Reacher_exam_code/agent.py", line 78, in play_EP
    print ( '' ) ; self.training_for_elite (real_steps_to_train) ; print ( '' )
  File "/home/kaumi/Git/deepL_RL2/4.ML_Agents/14.p2_continuous-control/Reacher_exam_code/agent.py", line 169, in training_for_elite
    self.training ( self.future_rewards_elite , real_steps_to_train )
  File "/home/kaumi/Git/deepL_RL2/4.ML_Agents/14.p2_continuous-control/Reacher_exam_code/agent.py", line 272, in training
    self.Actor.optimizer.apply_gradients ( zip ( grads2 ,                                  std ) )
  File "/home/kaumi/.local/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 695, in apply_gradients
    self._create_all_weights(var_list)
  File "/home/kaumi/.local/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 959, in _create_all_weights
    self._create_slots(var_list)
  File "/home/kaumi/.local/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/adam.py", line 126, in _create_slots
    self.add_slot(var, "m")
  File "/home/kaumi/.local/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 1017, in add_slot
    var_key = _var_key(var)
  File "/home/kaumi/.local/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 1650, in _var_key
    return var._unique_id
  File "/home/kaumi/.local/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 446, in __getattr__
    self.__getattribute__(name)
AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute '_unique_id'
```
</details>

**Comment by AngraPatrick** [comment]
resolved with: self.Actor.optimizer.apply_gradients ( zip ( [ grads2 ] , [ std ]  ) )

**Comment by tilakrayal** [comment]
@AngraPatrick,
Glad the issue is resolved for you, please feel free to move this to closed status. Thank you!

**Comment by makhmudjumanazarov** [comment]
AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'float_val'
