### ISSUE TITLE
TensorFlow Lite Model Maker has version conflict during install

### ISSUE THREAD

**Issue by maxnuggets** [tensorflow/tensorflow#58680]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.10

### Custom Code

No

### OS Platform and Distribution

Windows 11 22H2

### Python version

3.17.13 and 3.10.8

### Current Behaviour?

```shell
I was trying to install the tflite-model-maker through "pip install tflite-model-maker" in my terminal, I tried it with the different versions of python I have (in visual studio code, terminal) as mentioned above. I want to use tflite-model-maker to try the mobilenetv3. But in all of them, I get the error below. I also tried installing it with conda but failed too. btw Im new so I dont really know if this is from source or binary, so I just put "source" in Source field above. Thank you very much for your help.
```

### Standalone code to reproduce the issue

```shell
pip install tflite-model-maker
```

### Relevant log output

```shell
Using cached sentencepiece-0.1.83.tar.gz (497 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Jericho Longabela\AppData\Local\Temp\pip-install-9g31z9dp\sentencepiece_693a5d046a70461f8838ce79e5f24100\setup.py", line 29, in <module>
          with codecs.open(os.path.join('..', 'VERSION'), 'r', 'utf-8') as f:
        File "C:\Program Files\Python310\lib\codecs.py", line 905, in open
          file = builtins.open(filename, mode, buffering)
      FileNotFoundError: [Errno 2] No such file or directory: '..\\VERSION'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
</details>

**Comment by tiruk007** [comment]
@maxnuggets 
 Could you please refer to [TensorFlow Lite Model Maker](https://www.tensorflow.org/lite/models/modify/model_maker) and let us know if it is helps.
Thank you !

**Comment by Hatzen** [comment]
i run into the exact same problem.  

`pip install tflite-model-maker-nightly`
as well as
`pip install tflite-model-maker` leading to the exact same error.  
For me happening on windows 11 with python 3.10.9 installed.    

<details>
<summary> exact error </summary>   
  
```
  
Collecting sentencepiece
  Using cached sentencepiece-0.1.96-cp310-cp310-win_amd64.whl (1.1 MB)
  Using cached sentencepiece-0.1.95.tar.gz (508 kB)
  Preparing metadata (setup.py) ... done
  Using cached sentencepiece-0.1.94.tar.gz (507 kB)
  Preparing metadata (setup.py) ... done
  Using cached sentencepiece-0.1.91.tar.gz (500 kB)
  Preparing metadata (setup.py) ... done
  Using cached sentencepiece-0.1.86.tar.gz (495 kB)
  Preparing metadata (setup.py) ... done
  Using cached sentencepiece-0.1.83.tar.gz (497 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\kaiha\AppData\Local\Temp\pip-install-_xb3rhgm\sentencepiece_6d5129b49d784a438149fcbc0eac5540\setup.py", line 29, in <module>
          with codecs.open(os.path.join('..', 'VERSION'), 'r', 'utf-8') as f:   
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\codecs.py", line 906, in open
          file = builtins.open(filename, mode, buffering)
      FileNotFoundError: [Errno 2] No such file or directory: '..\\VERSION'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
   
```  
  
</details>

**Comment by tiruk007** [comment]
@Hatzen 
I was able to install tflite-model-maker on windows without any issue. Please find the below screenshots for reference:
![Screenshot 2022-12-20 8 21 17 AM](https://user-images.githubusercontent.com/111861663/208571414-85f409fe-b44b-48aa-8669-97bcce59adc9.png)
 
![Screenshot 2022-12-20 8 25 31 AM](https://user-images.githubusercontent.com/111861663/208571402-a8ee2b31-989b-4f99-983f-7f24a73d7996.png)
Thank you!
