### ISSUE TITLE
ImportError: libflatbuffers.so.2

### ISSUE THREAD

**Issue by ANTZ314** [tensorflow/tensorflow#58716]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

binary

### Tensorflow Version

2.4

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 22.04

### Mobile device

Linux Ubuntu 22.04

### Python version

3.9.15

### Bazel version

n/a

### GCC/Compiler version

gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0

### CUDA/cuDNN version

11.7.0 / 8.4.1.50

### GPU model and memory

Nvidia Geforce RTX 3060

### Current Behaviour?

```shell
In a separate environment without Spyder5 the installation and import works:

>>> import tensorflow
2022-11-28 21:11:44.598535: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
>>> print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))
Num GPUs Available:  1
```
```


### Standalone code to reproduce the issue

```shell
In Spyder5 installed conda environment, after attempting multiple installs in anaconda env:

conda install tensorflow-gpu -c conda-forge
conda install -c anaconda tensorflow-gpu
```
Error received with standard:
```
import tensorflow as tf
```
Error report below:
```


### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/antz/anaconda3/envs/vit-env/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: libflatbuffers.so.2: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/antz/anaconda3/envs/vit-env/lib/python3.10/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/antz/anaconda3/envs/vit-env/lib/python3.10/site-packages/tensorflow/python/__init__.py", line 36, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/home/antz/anaconda3/envs/vit-env/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py", line 77, in <module>
    raise ImportError(
ImportError: Traceback (most recent call last):
  File "/home/antz/anaconda3/envs/vit-env/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: libflatbuffers.so.2: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors for some common causes and solutions.
If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.
```
```
</details>

**Comment by mohantym** [comment]
Hi @ANTZ314 !
Please avoid multiple installations while setting up Tensorflow.

Could  you created a fresh environment through conda and  install tensoflow through pip instead of Conda.
Attached  ["pip install Instruction for linux"](https://www.tensorflow.org/install/pip#linux) for reference.
Thank you!
