### ISSUE TITLE
'utf-8' codec can't decode byte 0xcd in position 133: invalid continuation byte

### ISSUE THREAD

**Issue by eagl69** [tensorflow/tensorflow#58798]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.11

### Custom Code

No

### OS Platform and Distribution

windows 64

### Current Behaviour?

```shell
secundum commendationem feci replacement error est, nunc aliud 
with tf.io.gfile.GFile(path, 'r') as fid:

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 133: invalid continuation byte
```

### Standalone code to reproduce the issue

```shell
https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html#preparing-the-dataset
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Python\TensorFlow_Trainin_Custom\venv\lib\site-packages\object_detection\utils\label_map_util.py", line 133, in load_labelmap
    label_map_string = fid.read()
  File "C:\Python\TensorFlow_Trainin_Custom\venv\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 116, in read
    self._preread_check()
  File "C:\Python\TensorFlow_Trainin_Custom\venv\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 77, in _preread_check
    self._read_buf = _pywrap_file_io.BufferedInputStream(
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 133: invalid continuation byte
```
</details>

**Comment by tiruk007** [comment]
@eagl69 
Could you please provide a reproducible sample code as colab gist to reproduce this issue.

Thank you!
