### ISSUE TITLE
Error following installation, helop requested

### ISSUE THREAD

**Issue by ajeb78** [tensorflow/tensorflow#58908]
### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.11.0-cp310

### Custom Code

No

### OS Platform and Distribution

Linux Kubuntu 22.04

### Python version

3.10

### CUDA/cuDNN version

Cuda framework 12.0

### Current Behaviour?

```shell
I installed tensorflow into a new python virtual environment using the following commands:

mkdir tensorflow_files
cd tensorflow_files
python3 -m venv virtualenv
source virtualenv/bin/activate
pip install --upgrade TensorFlow
```
Having done so, tensorflow doesn't work, to the extent of not even being able to import it, see error messages below:

```
(virtualenv) adrian@arcturus:~/tensorflow_files$ python3
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2022-12-15 23:35:07.846430: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/home/adrian/tensorflow_files/virtualenv/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: /home/adrian/tensorflow_files/virtualenv/lib/python3.10/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringB5cxx11ERKNS_15OpKernelContextEb

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/adrian/tensorflow_files/virtualenv/lib/python3.10/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/adrian/tensorflow_files/virtualenv/lib/python3.10/site-packages/tensorflow/python/__init__.py", line 36, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/home/adrian/tensorflow_files/virtualenv/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py", line 77, in <module>
    raise ImportError(
ImportError: Traceback (most recent call last):
  File "/home/adrian/tensorflow_files/virtualenv/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: /home/adrian/tensorflow_files/virtualenv/lib/python3.10/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringB5cxx11ERKNS_15OpKernelContextEb


Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors for some common causes and solutions.
If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.
```
```


### Standalone code to reproduce the issue

```shell
See installation description above.
```

### Relevant log output

```shell
(virtualenv) adrian@arcturus:~/tensorflow_files$ python3
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2022-12-15 23:35:07.846430: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/home/adrian/tensorflow_files/virtualenv/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: /home/adrian/tensorflow_files/virtualenv/lib/python3.10/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringB5cxx11ERKNS_15OpKernelContextEb

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/adrian/tensorflow_files/virtualenv/lib/python3.10/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/adrian/tensorflow_files/virtualenv/lib/python3.10/site-packages/tensorflow/python/__init__.py", line 36, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/home/adrian/tensorflow_files/virtualenv/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py", line 77, in <module>
    raise ImportError(
ImportError: Traceback (most recent call last):
  File "/home/adrian/tensorflow_files/virtualenv/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: /home/adrian/tensorflow_files/virtualenv/lib/python3.10/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringB5cxx11ERKNS_15OpKernelContextEb


Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors for some common causes and solutions.
If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.
```

**Comment by tiruk007** [comment]
@ajeb78 
I was able to install and import the tensorflow in a python environment without a problem. Could you please refer to the below screenshots and [official documentation](https://www.tensorflow.org/install/pip#linux) :
![Screenshot from 2022-12-21 17-29-07](https://user-images.githubusercontent.com/111861663/208910651-d22dbf61-0858-46a4-bc88-cafd57cac26a.png)
![Screenshot from 2022-12-21 17-32-53](https://user-images.githubusercontent.com/111861663/208910669-2c506526-d3c0-4247-a8e0-cf433d6c16dd.png)

Thank you!
