### ISSUE TITLE
Unable to jit_compile and run function on CPU on tpu-vm

### ISSUE THREAD

**Issue by rivershah** [tensorflow/tensorflow#58934]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

v2.11.0-0-gd5b57ca9 2.11.0

### Custom Code

No

### OS Platform and Distribution

Linux t1v-n-92ea8b2a-w-0 5.15.0-1022-gcp #29~20.04.1-Ubuntu SMP Sat Oct 29 18:17:56 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Python version

3.8

### Current Behaviour?

On a `v3-8` TPU-VM running tensorflow version: `tpu-vm-tf-2.11.0` I am unable to `jit_compile` a basic function and run it on CPU. Can you please guide me how to run jit_compiled functions on TPU VM's CPU.

### Standalone code to reproduce the issue

```shell
import os

os.environ["TPU_NAME"] = "local"
os.environ["TPU_LOAD_LIBRARY"] = "1"

import tensorflow as tf

tf.debugging.set_log_device_placement(True)

print("All devices: ", tf.config.list_logical_devices())

a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]])
b = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]])


@tf.function(jit_compile=True)
def jit_test(a, b):
    c = tf.matmul(a, b)
    return a + b + c


with tf.device(":/TPU:0"):
    print(jit_test(a, b))
    print("Success!")


with tf.device(":/CPU:0"):
    print(jit_test(a, b))  # This will fail
    print("Will crash prior to getting here")
```

### Relevant log output

```shell
2022-12-19 10:13:18.533185: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-19 10:13:18.717772: I tensorflow/core/tpu/tpu_initializer_helper.cc:275] Libtpu path is: libtpu.so
D1219 10:13:18.874059745   34863 config.cc:113]              gRPC EXPERIMENT tcp_frame_size_tuning               OFF (default:OFF)
D1219 10:13:18.874080489   34863 config.cc:113]              gRPC EXPERIMENT tcp_read_chunks                     OFF (default:OFF)
D1219 10:13:18.874093652   34863 config.cc:113]              gRPC EXPERIMENT tcp_rcv_lowat                       OFF (default:OFF)
D1219 10:13:18.874100741   34863 config.cc:113]              gRPC EXPERIMENT peer_state_based_framing            OFF (default:OFF)
D1219 10:13:18.874107419   34863 config.cc:113]              gRPC EXPERIMENT flow_control_fixes                  OFF (default:OFF)
D1219 10:13:18.874114099   34863 config.cc:113]              gRPC EXPERIMENT memory_pressure_controller          OFF (default:OFF)
D1219 10:13:18.874121059   34863 config.cc:113]              gRPC EXPERIMENT periodic_resource_quota_reclamation ON  (default:ON)
D1219 10:13:18.874127645   34863 config.cc:113]              gRPC EXPERIMENT unconstrained_max_quota_buffer_size OFF (default:OFF)
D1219 10:13:18.874134219   34863 config.cc:113]              gRPC EXPERIMENT new_hpack_huffman_decoder           OFF (default:OFF)
D1219 10:13:18.874140862   34863 config.cc:113]              gRPC EXPERIMENT event_engine_client                 OFF (default:OFF)
D1219 10:13:18.874147728   34863 config.cc:113]              gRPC EXPERIMENT monitoring_experiment               ON  (default:ON)
D1219 10:13:18.874154168   34863 config.cc:113]              gRPC EXPERIMENT promise_based_client_call           OFF (default:OFF)
I1219 10:13:18.874398506   34863 ev_epoll1_linux.cc:121]     grpc epoll fd: 6
D1219 10:13:18.874414089   34863 ev_posix.cc:141]            Using polling engine: epoll1
D1219 10:13:18.874434253   34863 dns_resolver_ares.cc:824]   Using ares dns resolver
D1219 10:13:18.874733217   34863 lb_policy_registry.cc:45]   registering LB policy factory for "priority_experimental"
D1219 10:13:18.874748219   34863 lb_policy_registry.cc:45]   registering LB policy factory for "outlier_detection_experimental"
D1219 10:13:18.874756312   34863 lb_policy_registry.cc:45]   registering LB policy factory for "weighted_target_experimental"
D1219 10:13:18.874763493   34863 lb_policy_registry.cc:45]   registering LB policy factory for "pick_first"
D1219 10:13:18.874770671   34863 lb_policy_registry.cc:45]   registering LB policy factory for "round_robin"
D1219 10:13:18.874783165   34863 lb_policy_registry.cc:45]   registering LB policy factory for "ring_hash_experimental"
D1219 10:13:18.874810477   34863 lb_policy_registry.cc:45]   registering LB policy factory for "grpclb"
D1219 10:13:18.874843143   34863 lb_policy_registry.cc:45]   registering LB policy factory for "rls_experimental"
D1219 10:13:18.874864810   34863 lb_policy_registry.cc:45]   registering LB policy factory for "xds_cluster_manager_experimental"
D1219 10:13:18.874872835   34863 lb_policy_registry.cc:45]   registering LB policy factory for "xds_cluster_impl_experimental"
D1219 10:13:18.874880753   34863 lb_policy_registry.cc:45]   registering LB policy factory for "cds_experimental"
D1219 10:13:18.874888414   34863 lb_policy_registry.cc:45]   registering LB policy factory for "xds_cluster_resolver_experimental"
D1219 10:13:18.874895665   34863 certificate_provider_registry.cc:35] registering certificate provider factory for "file_watcher"
I1219 10:13:18.895383666   34863 socket_utils_common_posix.cc:336] TCP_USER_TIMEOUT is available. TCP_USER_TIMEOUT will be used thereafter
2022-12-19 10:13:18.913051: I tensorflow/core/tpu/tpu_initializer_helper.cc:225] GetTpuPjrtApi not found
2022-12-19 10:13:21.766915: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-19 10:13:26.260445: I tensorflow/compiler/xla/service/service.cc:173] XLA service 0x63c6900 initialized for platform TPU (this does not guarantee that XLA will be used). Devices:
2022-12-19 10:13:26.260485: I tensorflow/compiler/xla/service/service.cc:181]   StreamExecutor device (0): TPU, 2a886c8
2022-12-19 10:13:26.260499: I tensorflow/compiler/xla/service/service.cc:181]   StreamExecutor device (1): TPU, 2a886c8
2022-12-19 10:13:26.260511: I tensorflow/compiler/xla/service/service.cc:181]   StreamExecutor device (2): TPU, 2a886c8
2022-12-19 10:13:26.260524: I tensorflow/compiler/xla/service/service.cc:181]   StreamExecutor device (3): TPU, 2a886c8
2022-12-19 10:13:26.260536: I tensorflow/compiler/xla/service/service.cc:181]   StreamExecutor device (4): TPU, 2a886c8
2022-12-19 10:13:26.260549: I tensorflow/compiler/xla/service/service.cc:181]   StreamExecutor device (5): TPU, 2a886c8
2022-12-19 10:13:26.260561: I tensorflow/compiler/xla/service/service.cc:181]   StreamExecutor device (6): TPU, 2a886c8
2022-12-19 10:13:26.260573: I tensorflow/compiler/xla/service/service.cc:181]   StreamExecutor device (7): TPU, 2a886c8
All devices:  [LogicalDevice(name='/device:CPU:0', device_type='CPU'), LogicalDevice(name='/device:TPU_SYSTEM:0', device_type='TPU_SYSTEM'), LogicalDevice(name='/device:TPU:0', device_type='TPU'), LogicalDevice(name='/device:TPU:1', device_type='TPU'), LogicalDevice(name='/device:TPU:2', device_type='TPU'), LogicalDevice(name='/device:TPU:3', device_type='TPU'), LogicalDevice(name='/device:TPU:4', device_type='TPU'), LogicalDevice(name='/device:TPU:5', device_type='TPU'), LogicalDevice(name='/device:TPU:6', device_type='TPU'), LogicalDevice(name='/device:TPU:7', device_type='TPU')]
input: (_Arg): /job:localhost/replica:0/task:0/device:CPU:0
2022-12-19 10:13:26.286675: I tensorflow/core/common_runtime/placer.cc:114] input: (_Arg): /job:localhost/replica:0/task:0/device:CPU:0
_EagerConst: (_EagerConst): /job:localhost/replica:0/task:0/device:CPU:0
2022-12-19 10:13:26.286733: I tensorflow/core/common_runtime/placer.cc:114] _EagerConst: (_EagerConst): /job:localhost/replica:0/task:0/device:CPU:0
output_RetVal: (_Retval): /job:localhost/replica:0/task:0/device:CPU:0
2022-12-19 10:13:26.286753: I tensorflow/core/common_runtime/placer.cc:114] output_RetVal: (_Retval): /job:localhost/replica:0/task:0/device:CPU:0
2022-12-19 10:13:26.287893: I tensorflow/core/common_runtime/eager/execute.cc:1445] Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
2022-12-19 10:13:26.288240: I tensorflow/core/common_runtime/eager/execute.cc:1445] Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
2022-12-19 10:13:26.361102: I tensorflow/core/common_runtime/eager/execute.cc:1445] Executing op __inference_jit_test_11 in device /job:localhost/replica:0/task:0/device:TPU:0
2022-12-19 10:13:26.473898: I tensorflow/compiler/jit/xla_compilation_cache.cc:477] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
tf.Tensor(
[[ 32.  40.  48.]
 [ 74.  91. 108.]
 [116. 142. 168.]], shape=(3, 3), dtype=float32)
Success!
2022-12-19 10:13:26.477187: I tensorflow/core/common_runtime/eager/execute.cc:1445] Executing op __inference_jit_test_11 in device /job:localhost/replica:0/task:0/device:CPU:0
2022-12-19 10:13:26.478142: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:417 : NOT_FOUND: could not find registered transfer manager for platform Host -- check target linkage
Traceback (most recent call last):
  File "notebooks/tpu_vm_test.py", line 28, in <module>
    print(jit_test(a, b))  # This will fail
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.NotFoundError: could not find registered transfer manager for platform Host -- check target linkage [Op:__inference_jit_test_11]
D1219 10:13:26.848936447   34863 init.cc:190]                grpc_shutdown starts clean-up now
```
</details>

**Comment by tilakrayal** [comment]
@sushreebarsa,
I was able to reproduce the issue on tensorflow v2.9, v2.11and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/293a6d7574be8e6b7dfff34f3cd6228c/untitled805.ipynb).

**Comment by rivershah** [comment]
@sushreebarsa Any update on this please?

**Comment by rivershah** [comment]
@tilakrayal @sushreebarsa Can this please be looked at? In case you are not the appropriate assignee, can we please have another contributor to help look at this issue. Thank you.

**Comment by SuryanarayanaY** [comment]
The code works fine on GPU environment as per attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/13412c73391e41402c210ec52e64d4b4/58934-gpu.ipynb) on Colab and also on VM with GPU it works fine as per snapshot below.

<img width="1506" alt="Screenshot 2023-01-17 at 3 41 47 PM" src="https://user-images.githubusercontent.com/116063290/212870869-e1b508d3-ece6-4bc1-8d5a-244129c5c294.png">

@sachinprasadhs Could you please check the issue as I don't have TPU environment to replicate.

**Comment by sachinprasadhs** [comment]
Could you try using [CentralStorageStrategy](https://www.tensorflow.org/guide/distributed_training#centralstoragestrategy)  which will enable the variables to be placed on CPU when using `tpustrategy`.
This will create a CentralStorageStrategy instance which will use all visible GPUs and CPU. Update to variables on replicas will be aggregated before being applied to variables.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
