### ISSUE TITLE
TensorFlow device is mapped to multiple devices when using tf.estimator models and setting visible device using TF v1 api with TF2.11

### ISSUE THREAD

**Issue by LuFinch** [tensorflow/tensorflow#58952]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.11

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04.3 LTS

### Python version

python 3.9

### CUDA/cuDNN version

CUDA 11.3

### Current Behaviour?

```shell
When running models implemented with tf.estimator/Horovod to use multi-cards (like starting a 2ranks job in a host with 4 GTX-1080), we need to set visiable device for each process so that these processes will use different GPU cards. Just follow [link](https://github.com/horovod/horovod/blob/master/docs/tensorflow.rst#:~:text=and%20so%20forth.-,For%20TensorFlow%20v1%3A,-config%20%3D%20tf).

Following above mentioned settings, multi-cards job works well when using TF2.10, but throws Tensorflow Device mapping error when using TF2.11. This error only exists when using model implemented by tf.estimator and setting visible device with tf.ConfigProto().gpu_options.visible_device_list.

It seems that this error is relative to this [commit]( https://github.com/tensorflow/tensorflow/commit/16ea0f8995a9b087ff7e50bbf5a03e58e3c5002e#:~:text=if-,context.is_custom_device,-(device_string)%3A). When calling context.is_cutom_device(), this API would create TFE_Context that would create TF devices. However, program would also create TF devices when create Session with the aboved mentioned config, and these two TF device creation would conflicts.

To reproduce this error, you need to install horovod and using multi card machine to run below code with:

horovodrun -np N python xxx.py

where N denotes the number of processes to be started.
```

### Standalone code to reproduce the issue

```shell
import pandas as pd
import tensorflow as tf
import tensorflow.compat.v1 as tf1
global is_mpi
try:
    import horovod.tensorflow as hvd
    hvd.init()
    is_mpi = hvd.size()
except ImportError:
    is_mpi = 0
    print("No MPI horovod support, this is running in no-MPI mode!")

session_config = tf1.ConfigProto()
if is_mpi:
  session_config.gpu_options.visible_device_list = str(hvd.local_rank())

run_config = tf.estimator.RunConfig(session_config=session_config)

x_train = pd.read_csv('https://storage.googleapis.com/tf-datasets/titanic/train.csv')
x_train['sex'].replace(('male', 'female'), (0, 1), inplace=True)
x_train['alone'].replace(('n', 'y'), (0, 1), inplace=True)
x_train['class'].replace(('First', 'Second', 'Third'), (1, 2, 3), inplace=True)
x_train.drop(['embark_town', 'deck'], axis=1, inplace=True)
y_train = x_train.pop('survived')

# Data setup for TensorFlow 1 with `tf.estimator`
def _input_fn():
  return tf1.data.Dataset.from_tensor_slices((dict(x_train), y_train)).batch(32)

FEATURE_NAMES = [
    'age', 'fare', 'sex', 'n_siblings_spouses', 'parch', 'class', 'alone'
]
feature_columns = []
for fn in FEATURE_NAMES:
  feat_col = tf1.feature_column.numeric_column(fn, dtype=tf.float32)
  feature_columns.append(feat_col)

linear_estimator = tf.estimator.LinearEstimator(
    head=tf.estimator.BinaryClassHead(),
    feature_columns=feature_columns,
    model_dir="./model",
    config=run_config)
linear_estimator.train(input_fn=_input_fn, steps=1000)
```

### Relevant log output

```shell
[1]<stderr>:2022-12-19 16:12:04.169004: E tensorflow/core/common_runtime/session.cc:91] Failed to create session: ALREADY_EXISTS: TensorFlow device (GPU:0) is being mapped to multiple devices (1 now, and 0 previously), which is not supported. This may be the result of providing different GPU configurations (ConfigProto.gpu_options, for example different visible_device_list) when creating multiple Sessions in the same process. This is not currently supported, see https://github.com/tensorflow/tensorflow/issues/19083
[1]<stderr>:2022-12-19 16:12:04.169026: E tensorflow/c/c_api.cc:2209] ALREADY_EXISTS: TensorFlow device (GPU:0) is being mapped to multiple devices (1 now, and 0 previously), which is not supported. This may be the result of providing different GPU configurations (ConfigProto.gpu_options, for example different visible_device_list) when creating multiple Sessions in the same process. This is not currently supported, see https://github.com/tensorflow/tensorflow/issues/19083
[1]<stderr>:Traceback (most recent call last):
[1]<stderr>:  File "/home/yangshe1/lufengqing/issue_case/case.py", line 43, in <module>
[1]<stderr>:    linear_estimator.train(input_fn=_input_fn, steps=1000)
[1]<stderr>:  File "/home/yangshe1/miniconda3/envs/lfq_/lib/python3.9/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 360, in train
[1]<stderr>:    loss = self._train_model(input_fn, hooks, saving_listeners)
[1]<stderr>:  File "/home/yangshe1/miniconda3/envs/lfq_/lib/python3.9/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1186, in _train_model
[1]<stderr>:    return self._train_model_default(input_fn, hooks, saving_listeners)
[1]<stderr>:  File "/home/yangshe1/miniconda3/envs/lfq_/lib/python3.9/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1217, in _train_model_default
[1]<stderr>:    return self._train_with_estimator_spec(estimator_spec, worker_hooks,
[1]<stderr>:  File "/home/yangshe1/miniconda3/envs/lfq_/lib/python3.9/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1512, in _train_with_estimator_spec
[1]<stderr>:    with training.MonitoredTrainingSession(
[1]<stderr>:  File "/home/yangshe1/miniconda3/envs/lfq_/lib/python3.9/site-packages/tensorflow/python/training/monitored_session.py", line 606, in MonitoredTrainingSession
[1]<stderr>:    return MonitoredSession(
[1]<stderr>:  File "/home/yangshe1/miniconda3/envs/lfq_/lib/python3.9/site-packages/tensorflow/python/training/monitored_session.py", line 1050, in __init__
[1]<stderr>:    super(MonitoredSession, self).__init__(
[1]<stderr>:  File "/home/yangshe1/miniconda3/envs/lfq_/lib/python3.9/site-packages/tensorflow/python/training/monitored_session.py", line 753, in __init__
[1]<stderr>:    self._sess = _RecoverableSession(self._coordinated_creator)
[1]<stderr>:  File "/home/yangshe1/miniconda3/envs/lfq_/lib/python3.9/site-packages/tensorflow/python/training/monitored_session.py", line 1259, in __init__
[1]<stderr>:    _WrappedSession.__init__(self, self._create_session())
[1]<stderr>:  File "/home/yangshe1/miniconda3/envs/lfq_/lib/python3.9/site-packages/tensorflow/python/training/monitored_session.py", line 1264, in _create_session
[1]<stderr>:    return self._sess_creator.create_session()
[1]<stderr>:  File "/home/yangshe1/miniconda3/envs/lfq_/lib/python3.9/site-packages/tensorflow/python/training/monitored_session.py", line 906, in create_session
[1]<stderr>:    self.tf_sess = self._session_creator.create_session()
[1]<stderr>:  File "/home/yangshe1/miniconda3/envs/lfq_/lib/python3.9/site-packages/tensorflow/python/training/monitored_session.py", line 665, in create_session
[1]<stderr>:    return self._get_session_manager().prepare_session(
[1]<stderr>:  File "/home/yangshe1/miniconda3/envs/lfq_/lib/python3.9/site-packages/tensorflow/python/training/session_manager.py", line 309, in prepare_session
[1]<stderr>:    sess, is_loaded_from_checkpoint = self._restore_checkpoint(
[1]<stderr>:  File "/home/yangshe1/miniconda3/envs/lfq_/lib/python3.9/site-packages/tensorflow/python/training/session_manager.py", line 218, in _restore_checkpoint
[1]<stderr>:    sess = session.Session(self._target, graph=self._graph, config=config)
[1]<stderr>:  File "/home/yangshe1/miniconda3/envs/lfq_/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1604, in __init__
[1]<stderr>:    super(Session, self).__init__(target, graph, config=config)
[1]<stderr>:  File "/home/yangshe1/miniconda3/envs/lfq_/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 712, in __init__
[1]<stderr>:    self._session = tf_session.TF_NewSessionRef(c_graph, opts)
[1]<stderr>:tensorflow.python.framework.errors_impl.AlreadyExistsError: TensorFlow device (GPU:0) is being mapped to multiple devices (1 now, and 0 previously), which is not supported. This may be the result of providing different GPU configurations (ConfigProto.gpu_options, for example different visible_device_list) when creating multiple Sessions in the same process. This is not currently supported, see https://github.com/tensorflow/tensorflow/issues/19083
```
</details>

**Comment by mohantym** [comment]
Ok @LuFinch !
Thanks for sharing your observation w.r.to tf.estimator and Horovod multi-GPU card.
Just quick observation here. If you are trying to use compat.v1 mode, you need to disable v2 behavior  too as below.

```

import tensorflow.compat.v1 as tf1
 tf.disable_v2_behavior()
```
@SuryanarayanaY 
Could you look at this issue. Attached [gist ](https://b.corp.google.com/issues/179712661)for reference.

Thank you!

**Comment by LuFinch** [comment]
I have tried `tensorflow.compat.v1.disable_v2_behavior()` but it does not work and throw the same error.

**Comment by SuryanarayanaY** [comment]
Hi @LuFinch ,
I Just to remind you about the Warning for the [tf.estimator](https://www.tensorflow.org/guide/estimator) API as below.

> Warning: Estimators are not recommended for new code. Estimators run [v1.Session](https://www.tensorflow.org/api_docs/python/tf/compat/v1/Session)-style code which is more difficult to write correctly, and can behave unexpectedly, especially when combined with TF 2 code. Estimators do fall under our [compatibility guarantees](https://tensorflow.org/guide/versions), but will receive no fixes other than security vulnerabilities. See the [migration guide](https://tensorflow.org/guide/migrate?_gl=1*kz7rdh*_ga*MTM4Mzg1ODAxNi4xNjY1OTkwMTQ1*_ga_W0YLR4190T*MTY3MTYzNjAwMi4yMzQuMS4xNjcxNjM2MzMwLjAuMC4w) for details.

I tried to replicate the issue on a Multi GPU VM. I referred the [source](https://horovod.ai/getting-started/) to install horovod and used this command 
`HOROVOD_GPU_OPERATIONS=NCCL pip install horovod` to install horovod with GPU support but this failed.

Could you please confirm the commands you used for installing horovod and also to replicate the problem so that i can try to replicate it and for doing needful.

Thankyou!

**Comment by LuFinch** [comment]
Hi @SuryanarayanaY， thanks for your time.

I know that tf.estimator API is not recommanded. However, a part of models we used were implemented by v1 style, and we just want to use them without changing any code or adding any TF2 code.

I use the same command to install horovod and it works. Could you please try again?

If you can't install it, you can also replace
```
if is_mpi:
  session_config.gpu_options.visible_device_list = str(hvd.local_rank())
```
with 
```
if True:
  session_config.gpu_options.visible_device_list = str(1)
```
and directly run it with  `python xxx.py` without horovod to reproduce it in single process case.

Thanks you !

**Comment by SuryanarayanaY** [comment]
Hi @LuFinch ,
I tried with TF 2.10V and found no error as below.
<img width="1512" alt="Screenshot 2022-12-29 at 7 57 13 PM" src="https://user-images.githubusercontent.com/116063290/209967797-747066f2-8d59-41a2-9926-883aa18c1195.png">
However with tf-nightly i replicated the error you mentioned as below.
<img width="1512" alt="Screenshot 2022-12-29 at 7 57 24 PM" src="https://user-images.githubusercontent.com/116063290/209967854-09c69357-7dcf-4076-9f22-656f1ed1190d.png">
Could you please refer to #19083 and #18861 related to similar issue and confirm if got any insights there ?

Thankyou!

**Comment by LuFinch** [comment]
Hi @SuryanarayanaY. I have checked these two issues before.

But the senario is different here.

As we mentioned aboved, if we set 
```
if True:
  session_config.gpu_options.visible_device_list = str(1)
```
and run it with `python xxx.py`,  it is actually a single process job using physical GPU 1 instead of a multi-processes or multi-threads job. I think it is a normal case that some customers want to run TF job with specific GPU. 

Can you help to find out the error reason?

Thanks!

**Comment by SuryanarayanaY** [comment]
Hi @LuFinch ,

Please refer to the Documentation [Source](https://www.tensorflow.org/guide/distributed_training) on Distribution Training w.r.t  Estimator API.

<img width="1259" alt="Screenshot 2023-01-06 at 5 00 50 PM" src="https://user-images.githubusercontent.com/116063290/211004372-8006b712-a66d-49d7-847d-2a0b1e7cdc6d.png">

As estimator API has limited support and also Training/Evaluation are under experimental and hence can't predict the behaviour.

Thank you!

**Comment by mmseerrttt** [comment]
I met the same issue, is there any suggestions?

**Comment by mmseerrttt** [comment]
[fdaf]( https://github.com/tensorflow/tensorflow/issues/58952)
