### ISSUE TITLE
Unable to use any augmentation layer within `tf.data` with XLA enabled, in `MultiWorkerMirroredStrategy`

### ISSUE THREAD

**Issue by MasterSkepticista** [tensorflow/tensorflow#58961]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

v2.11.0-rc2-17-gd5b57ca93e5 2.11.0

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.8

### CUDA/cuDNN version

CUDA 11.8, cuDNN 8.7

### GPU model and memory

RTX 3090, 24GB

### Current Behaviour?

Data Augmentation is generally offloaded to CPU to enable parallelism using `tf.data.Dataset.map(...)` operation.

This works as expected, with XLA enabled, on single-node training. But using `MultiWorkerMirroredStrategy()`, with XLA enabled, `GraphExecutionError` occurs.

With XLA disabled, `tf.data` based augmentation works fine.

### Standalone code to reproduce the issue

```shell
# NCCL AllReduce is being used.
strategy = tf.distribute.MultiWorkerMirroredStrategy(...)  # Fails with `jit_compile=True` below
strategy = tf.distribute.OneDeviceStrategy('/gpu:0')  # Works with `jit_compile=True`
(raw_train_ds, raw_test_ds), ds_info = tfds.load(...)

"""Build model in distributed scope"""
with strategy.scope():
  augmentation = tf.keras.Sequential([
    layers.RandomFlip(),
    layers.RandomZoom(0.1),
    layers.RandomTranslation(0.2, 0.2),
  ])
  
  backbone = tf.keras.applications.ResNet50V2(
    weights=None,
    include_top=False,
    input_shape=(*IMG_SIZE, 3),
    pooling='max'
  )
  backbone.trainable = True
  model = tf.keras.Sequential([
    layers.Input((*IMG_SIZE, 3)),
    backbone,
    layers.Dense(ds_info.features['label'].num_classes,
  ])
  optimizer = tf.optimizers.SGD(
    learning_rate=LR * strategy.num_replicas_in_sync,
    momentum=0.9,
    weight_decay=1e-4)

  model.compile(
      loss=tf.losses.SparseCategoricalCrossentropy(from_logits=True),
      optimizer=optimizer,
      metrics=['accuracy'],
      jit_compile=True)

  if WORKER_RANK == 0: model.summary()
train_ds = (raw_train_ds.shard(WORLD_SIZE, WORKER_RANK)
                          .shuffle(8192)
                          .map(decode_example(IMG_SIZE), tf.data.AUTOTUNE)
                          .map(lambda x, y: (augmentation(x, training=True), y), tf.data.AUTOTUNE)
                          .batch(global_batch_size)
                          .prefetch(tf.data.AUTOTUNE))
test_ds = (raw_test_ds.shard(WORLD_SIZE, WORKER_RANK)
                        .map(decode_example(IMG_SIZE), tf.data.AUTOTUNE)
                        .batch(global_batch_size)
                        .prefetch(tf.data.AUTOTUNE))
model.fit(train_ds, 
            epochs=100,
            validation_data=test_ds)
```

### Relevant log output

```shell
Error log (you may see duplication of lines, since this is the output of 2 nodes running the same code via MPI):

2022-12-20 21:55:47.039610: I tensorflow/compiler/jit/xla_compilation_cache.cc:477] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
2022-12-20 21:55:54.181560: I tensorflow/compiler/jit/xla_compilation_cache.cc:477] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
Traceback (most recent call last):
  File "main.py", line 167, in <module>
    main()
  File "main.py", line 160, in main
    model.fit(train_ds, 
  File "/home/mpiuser/.local/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/mpiuser/.local/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InternalError: Graph execution error:

Detected at node 'StatefulPartitionedCall' defined at (most recent call last):
    File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
      self._bootstrap_inner()
    File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
Node: 'StatefulPartitionedCall'
Detected at node 'StatefulPartitionedCall' defined at (most recent call last):
    File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
      self._bootstrap_inner()
    File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
Node: 'StatefulPartitionedCall'
2 root error(s) found.
  (0) INTERNAL:  tensorflow/compiler/xla/service/gpu/nccl_utils.cc:266: NCCL operation ncclCommInitRank(comm.get(), nranks, id, rank) failed: remote process exited or there was a network error
         [[{{node StatefulPartitionedCall}}]]
         [[Reshape_6/_62]]
  (1) INTERNAL:  tensorflow/compiler/xla/service/gpu/nccl_utils.cc:266: NCCL operation ncclCommInitRank(comm.get(), nranks, id, rank) failed: remote process exited or there was a network error
         [[{{node StatefulPartitionedCall}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_35379]
Traceback (most recent call last):
  File "main.py", line 167, in <module>
    main()
  File "main.py", line 160, in main
    model.fit(train_ds, 
  File "/home/mpiuser/.local/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/mpiuser/.local/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InternalError: Graph execution error:

Detected at node 'StatefulPartitionedCall' defined at (most recent call last):
    File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
      self._bootstrap_inner()
    File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
Node: 'StatefulPartitionedCall'
Detected at node 'StatefulPartitionedCall' defined at (most recent call last):
    File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
      self._bootstrap_inner()
    File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
Node: 'StatefulPartitionedCall'
2 root error(s) found.
  (0) INTERNAL:  tensorflow/compiler/xla/service/gpu/nccl_utils.cc:266: NCCL operation ncclCommInitRank(comm.get(), nranks, id, rank) failed: remote process exited or there was a network error
         [[{{node StatefulPartitionedCall}}]]
         [[Reshape_6/_62]]
  (1) INTERNAL:  tensorflow/compiler/xla/service/gpu/nccl_utils.cc:266: NCCL operation ncclCommInitRank(comm.get(), nranks, id, rank) failed: remote process exited or there was a network error
         [[{{node StatefulPartitionedCall}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_34897]
```
</details>

**Comment by tilakrayal** [comment]
@SuryanarayanaY,
There is already a PR [#10845](https://github.com/tensorflow/models/pull/10845) raised for the similar issue mentioned that it is the bug of `tf.distribute and xla`. Could you please take a look at this issue. Thank you!

**Comment by SuryanarayanaY** [comment]
Hi @MasterSkepticista ,

have you referred the attached [demo](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras) for Multi worker training ? Can you refer it and confirm whether it is useful for your case?

To replicate and check the issue we need more details like `cluster _resolver` you used in `tf.distribute.MultiWorkerMirroredStrategy()`, the dataset you have used in `tfds.load()`, `TF_CONFIG` details you used and variables like `IMG_SIZE, WORLD_SIZE, WORKER_RANK` etc.

Please provide all those details to replicate and check the issue.

Thankyou!

**Comment by MasterSkepticista** [comment]
It seems `jit_compile` is incompatible with AllReduce across workers, as is the case in `MultiWorkerMirroredStrategy`, mentioned [here](https://github.com/tensorflow/tensorflow/issues/45940#issuecomment-759746281). I went with the suggestion to compile specific steps while leaving the remainder to XLA autoclustering.
Closing this issue for now.
