### ISSUE TITLE
__init__() got an unexpected keyword argument 'reduction'

### ISSUE THREAD

**Issue by yunhao-tech** [tensorflow/tensorflow#58972]
### Issue Type

Support

### Source

source

### Tensorflow Version

tf 2.7.0

### Custom Code

Yes

### OS Platform and Distribution

Windows 10

### Python version

3.8.3

### Current Behaviour?

```shell
Compile a model with `metrics=[tf.keras.losses.XXX]` does not raise error. The training process seems also good. However, if we save the model and try to reload it, it does not work.

Now I know we could not use `tf.keras.losses` in `metrics`, we must use some functions in `tf.keras.metrics` or some customized metrics. But the error message "__init__() got an unexpected keyword argument 'reduction'" gives no information. 

Why not raise an error during the training or even during the compiling? That would be much more friendly for new comers.
```

### Standalone code to reproduce the issue

```shell
import numpy as np
from tensorflow.keras.layers import Dense, Dropout
import tensorflow as tf

input_length = 2
latent_dim = 512
output_length = 2

model = tf.keras.Sequential([
    Dense(latent_dim, activation='relu', input_shape=(input_length,)),
    Dropout(rate=0.5),
    Dense(units=latent_dim, activation='relu'),
    Dense(units=output_length),
  ])

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
        loss=tf.keras.losses.MeanSquaredError(),
        metrics=[tf.keras.losses.MeanAbsoluteError()])

x_train = np.ones(shape=(150000, 2))
y_train = np.ones(shape=(150000, 2))

history = model.fit(x_train, y_train, epochs=2, batch_size=128)

model.save('saved_model/my_model')
pretrained = tf.keras.models.load_model('saved_model/my_model')
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "d:/VScode/M2-SMC/debug.py", line 26, in <module>
    pretrained = tf.keras.models.load_model('saved_model/my_model')
  File "C:\Users\yunhao\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\yunhao\anaconda3\lib\site-packages\keras\engine\base_layer.py", line 784, in from_config
    return cls(**config)
TypeError: __init__() got an unexpected keyword argument 'reduction'
```

**Comment by deepNeuralNick** [comment]
i would like to resolve this issue if there are no available assignees  and it needs resolution.

**Comment by tiruk007** [comment]
@yunhao-tech 
I was able to reproduce the issue on colab using TF v2.11. Please find the gist [here](https://colab.research.google.com/gist/tiruk007/2dbe0afc37df36d78fd167261dd6c3f6/untitled48.ipynb) for reference.
This issue seems to be keras issue.Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999.
Thank you!

**Comment by yunhao-tech** [comment]
@tiruk007 Thank you! 
I'll post it on keras repo.

**Comment by tiruk007** [comment]
@yunhao-tech 
Could you please close the issue, Since this issue will be triaged on Keras repo.

Thank you!
