### ISSUE TITLE
Installing sktime all_extras got compatible issues with tensorflow

### ISSUE THREAD

**Issue by xxl4tomxu98** [tensorflow/tensorflow#58975]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

M1 macbook metal tf2.5

### Custom Code

Yes

### OS Platform and Distribution

Mac OS 13.1

### Mobile device

M1 macbook 2020

### Python version

3.9

### GPU model and memory

apple metal

### Current Behaviour?

```shell
A bug happened!
```

### Standalone code to reproduce the issue

```shell
I am trying to install sktime with all soft dependencies including tensorflow,
when I do developer install "pip install -e ."[all_extras,dev]" I got this error: "ERROR: Ignored the following versions that require a different python version: 0.52.0 Requires-Python >=3.6,<3.9; 0.52.0rc3 Requires-Python >=3.6,<3.9
ERROR: Could not find a version that satisfies the requirement tensorflow; extra == "all_extras" (from sktime[all-extras,dev]) (from versions: none)
ERROR: No matching distribution found for tensorflow; extra == "all_extras""
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@xxl4tomxu98,
Could you please try to install the Python version which is **>=3.6 and <3.9** and let us know if you are facing the same issue. Also we recommend to install the latest stable version where there is a high possibility that this was fixed. Thank you!

**Comment by xxl4tomxu98** [comment]
The following is what I got when I created python 3.8 version using "conda create -n sktime-dev python=3.8", and then "conda activate sktime-dev", and then "pip install -e .[all_extras,dev]" and the error is as following:

extra options: '-faltivec -I/System/Library/Frameworks/vecLib.framework/Headers'
            clang: numpy/core/src/multiarray/array_assign_scalar.c
            clang: numpy/core/src/multiarray/alloc.c
            clang: numpy/core/src/multiarray/buffer.c
            clang: numpy/core/src/multiarray/conversion_utils.c
            clang: numpy/core/src/multiarray/datetime_strings.c
            clang: numpy/core/src/multiarray/descriptor.c
            clang: numpy/core/src/multiarray/common.c
            clang: build/src.macosx-11.0-arm64-3.8/numpy/core/src/multiarray/einsum.c
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: numpy/core/src/multiarray/hashdescr.c
            clang: build/src.macosx-11.0-arm64-3.8/numpy/core/src/multiarray/lowlevel_strided_loops.c
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: numpy/core/src/multiarray/multiarraymodule.c
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: numpy/core/src/multiarray/nditer_constr.c
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: numpy/core/src/multiarray/refcount.c
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: numpy/core/src/multiarray/scalarapi.c
            clang: numpy/core/src/multiarray/temp_elide.c
            clang: numpy/core/src/multiarray/vdot.c
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: build/src.macosx-11.0-arm64-3.8/numpy/core/src/umath/loops.c
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: numpy/core/src/umath/ufunc_object.c
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: numpy/core/src/umath/ufunc_type_resolution.c
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: numpy/core/src/common/array_assign.c
            clang: build/src.macosx-11.0-arm64-3.8/numpy/core/src/npymath/ieee754.c
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: numpy/core/src/common/ucsnarrow.c
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: build/src.macosx-11.0-arm64-3.8/numpy/core/src/common/npy_cpu_features.c
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: /private/var/folders/50/zx6p2vtx3h9bvdft7b3h85sm0000gn/T/pip-install-8r_vptpw/numpy_99bc95ff8ac74139aa6de758ed12d4b3/numpy/_build_utils/src/apple_sgemv_fix.c
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            Running from numpy source directory.
            /private/var/folders/50/zx6p2vtx3h9bvdft7b3h85sm0000gn/T/pip-build-env-n_5x0ru4/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py:265: UserWarning: Unknown distribution option: 'define_macros'
              warnings.warn(msg)
            error: Command "clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/tomxu/miniforge3/envs/sktime-dev/include -arch arm64 -fPIC -O2 -isystem /Users/tomxu/miniforge3/envs/sktime-dev/include -arch arm64 -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DNO_ATLAS_INFO=3 -DHAVE_CBLAS -Ibuild/src.macosx-11.0-arm64-3.8/numpy/core/src/umath -Ibuild/src.macosx-11.0-arm64-3.8/numpy/core/src/npymath -Ibuild/src.macosx-11.0-arm64-3.8/numpy/core/src/common -Inumpy/core/include -Ibuild/src.macosx-11.0-arm64-3.8/numpy/core/include/numpy -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/Users/tomxu/miniforge3/envs/sktime-dev/include/python3.8 -Ibuild/src.macosx-11.0-arm64-3.8/numpy/core/src/common -Ibuild/src.macosx-11.0-arm64-3.8/numpy/core/src/npymath -c numpy/core/src/multiarray/alloc.c -o build/temp.macosx-11.0-arm64-cpython-38/numpy/core/src/multiarray/alloc.o -MMD -MF build/temp.macosx-11.0-arm64-cpython-38/numpy/core/src/multiarray/alloc.o.d -faltivec -I/System/Library/Frameworks/vecLib.framework/Headers" failed with exit status 1
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
      Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by xxl4tomxu98** [comment]
Question, since all of my setup is python3.9, creating python3.8 seems to be awkward. is there a way to do this with python3.9 with all_extras?

**Comment by SuryanarayanaY** [comment]
Hi @xxl4tomxu98 ,
For latest Versions of Tensorflow, let's say if you use TF2.11 then Python versions 3.7-3.10 are supported as per [source](https://www.tensorflow.org/install/pip#software_requirements).Kindly upgrade to TF 2.10v or 2.11v to keep your Python environment same.Also please refer to Developer [comment](https://github.com/tensorflow/tensorflow/issues/59014#issuecomment-1365275934) regarding older versions related.

**Comment by xxl4tomxu98** [comment]
@SuryanarayanaY , TF2.11 available in Mac RAM M1 format?, can you please provide a link for instruction to update from TF2.5 to TF2.11 in ARM? Thanks

**Comment by xxl4tomxu98** [comment]
@SuryanarayanaY , I also tried to do  "pip install -e .[dev]" first with success and then separately install most recent TF2.11 and other related dependencies, it allows me to import TF2.11, but when it is used to fit and predict, it gives this error:

Metal device set to: Apple M1

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
=================================================================
 input_1 (InputLayer)        [(None, 100, 6)]          0         
                                                                 
 conv1d (Conv1D)             (None, 94, 6)             258       
                                                                 
 average_pooling1d (AverageP  (None, 31, 6)            0         
 ooling1D)                                                       
                                                                 
 conv1d_1 (Conv1D)           (None, 25, 12)            516       
                                                                 
 average_pooling1d_1 (Averag  (None, 8, 12)            0         
 ePooling1D)                                                     
                                                                 
 flatten (Flatten)           (None, 96)                0         
                                                                 
 dense (Dense)               (None, 4)                 388       
                                                                 
=================================================================
Total params: 1,162
Trainable params: 1,162
Non-trainable params: 0
_________________________________________________________________
Epoch 1[/200](https://file+.vscode-resource.vscode-cdn.net/200)
/Users/tomxu/miniforge3/envs/sktime-dev/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:808: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
2022-12-29 12:04:05.465251: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-12-29 12:04:05.465271: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: )
2022-12-29 12:04:05.622791: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2022-12-29 12:04:05.851814: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2022-12-29 12:04:05.993145: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:418 : NOT_FOUND: could not find registered platform with id: 0x13f038990
2022-12-29 12:04:05.993172: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:418 : NOT_FOUND: could not find registered platform with id: 0x13f038990
2022-12-29 12:04:06.003877: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:418 : NOT_FOUND: could not find registered platform with id: 0x13f038990
2022-12-29 12:04:06.005433: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:418 : NOT_FOUND: could not find registered platform with id: 0x13f038990
2022-12-29 12:04:06.009941: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:418 : NOT_FOUND: could not find registered platform with id: 0x13f038990
2022-12-29 12:04:06.009960: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:418 : NOT_FOUND: could not find registered platform with id: 0x13f038990

Output exceeds the size limit. Open the full output data in a text editor
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
Cell In[4], line 2
      1 network = CNNClassifier(n_epochs=200, verbose=True)
----> 2 network.fit(X_train, y_train)
      3 network.score(X_test, y_test)

File ~/Documents/sktime/sktime/classification/base.py:191, in BaseClassifier.fit(self, X, y)
    186         raise AttributeError(
    187             "self.n_jobs must be set if capability:multithreading is True"
    188         )
    190 # pass coerced and checked data to inner _fit
--> 191 self._fit(X, y)
    192 self.fit_time_ = int(round(time.time() * 1000)) - start
    194 # this should happen last

File ~/Documents/sktime/sktime/classification/deep_learning/cnn.py:181, in CNNClassifier._fit(self, X, y)
    179 if self.verbose:
    180     self.model_.summary()
--> 181 self.history = self.model_.fit(
    182     X,
    183     y_onehot,
    184     batch_size=self.batch_size,
    185     epochs=self.n_epochs,
    186     verbose=self.verbose,
    187     callbacks=self._callbacks,
    188 )
    189 return self

File ~/miniforge3/envs/sktime-dev/lib/python3.9/site-packages/keras/utils/traceback_utils.py:70, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     67     filtered_tb = _process_traceback_frames(e.__traceback__)
     68     # To get the full stack trace, call:
     69     # `tf.debugging.disable_traceback_filtering()`
---> 70     raise e.with_traceback(filtered_tb) from None
     71 finally:
     72     del filtered_tb

File ~/miniforge3/envs/sktime-dev/lib/python3.9/site-packages/tensorflow/python/eager/execute.py:52, in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     50 try:
     51   ctx.ensure_initialized()
---> 52   tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     53                                       inputs, attrs, num_outputs)
     54 except core._NotOkStatusException as e:
     55   if name is not None:

NotFoundError: Graph execution error:
Detected at node 'StatefulPartitionedCall_4' defined at (most recent call last):
    File "/Users/tomxu/miniforge3/envs/sktime-dev/lib/python3.9/runpy.py", line 197, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/Users/tomxu/miniforge3/envs/sktime-dev/lib/python3.9/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/Users/tomxu/miniforge3/envs/sktime-dev/lib/python3.9/site-packages/ipykernel_launcher.py", line 17, in <module>
      app.launch_new_instance()
    File "/Users/tomxu/miniforge3/envs/sktime-dev/lib/python3.9/site-packages/traitlets/config/application.py", line 1041, in launch_instance
      app.start()
    File "/Users/tomxu/miniforge3/envs/sktime-dev/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 711, in start
      self.io_loop.start()
    File "/Users/tomxu/miniforge3/envs/sktime-dev/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 215, in start
      self.asyncio_loop.run_forever()
    File "/Users/tomxu/miniforge3/envs/sktime-dev/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
      self._run_once()
    File "/Users/tomxu/miniforge3/envs/sktime-dev/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
      handle._run()
    File "/Users/tomxu/miniforge3/envs/sktime-dev/lib/python3.9/asyncio/events.py", line 80, in _run
      self._context.run(self._callback, *self._args)
    File "/Users/tomxu/miniforge3/envs/sktime-dev/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
      await self.process_one()
    File "/Users/tomxu/miniforge3/envs/sktime-dev/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 499, in process_one
      await dispatch(*args)
    File "/Users/tomxu/miniforge3/envs/sktime-dev/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 406, in dispatch_shellawait result
    File "/Users/tomxu/miniforge3/envs/sktime-dev/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 729, in execute_request
      reply_content = await reply_content
    File "/Users/tomxu/miniforge3/envs/sktime-dev/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 411, in do_execute
      res = shell.run_cell(
    File "/Users/tomxu/miniforge3/envs/sktime-dev/lib/python3.9/site-packages/ipykernel/zmqshell.py", line 530, in run_cell
      return super().run_cell(*args, **kwargs)
    File "/Users/tomxu/miniforge3/envs/sktime-dev/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2940, in run_cell
      result = self._run_cell(
    File "/Users/tomxu/miniforge3/envs/sktime-dev/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2995, in _run_cell
      return runner(coro)
    File "/Users/tomxu/miniforge3/envs/sktime-dev/lib/python3.9/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
      coro.send(None)
    File "/Users/tomxu/miniforge3/envs/sktime-dev/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3194, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "/Users/tomxu/miniforge3/envs/sktime-dev/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3373, in run_ast_nodes
      if await self.run_code(code, result, async_=asy):
    File "/Users/tomxu/miniforge3/envs/sktime-dev/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3433, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "/var/folders/50/zx6p2vtx3h9bvdft7b3h85sm0000gn/T/ipykernel_51235/1980619450.py", line 2, in <module>
      network.fit(X_train, y_train)
    File "/Users/tomxu/Documents/sktime/sktime/classification/base.py", line 191, in fit
      self._fit(X, y)File "/Users/tomxu/Documents/sktime/sktime/classification/deep_learning/cnn.py", line 181, in _fit
      self.history = self.model_.fit(
    File "/Users/tomxu/miniforge3/envs/sktime-dev/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/Users/tomxu/miniforge3/envs/sktime-dev/lib/python3.9/site-packages/keras/engine/training.py", line 1650, in fit
      tmp_logs = self.train_function(iterator)
    File "/Users/tomxu/miniforge3/envs/sktime-dev/lib/python3.9/site-packages/keras/engine/training.py", line 1249, in train_function
      return step_function(self, iterator)
    File "/Users/tomxu/miniforge3/envs/sktime-dev/lib/python3.9/site-packages/keras/engine/training.py", line 1233, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/Users/tomxu/miniforge3/envs/sktime-dev/lib/python3.9/site-packages/keras/engine/training.py", line 1222, in run_step
      outputs = model.train_step(data)
    File "/Users/tomxu/miniforge3/envs/sktime-dev/lib/python3.9/site-packages/keras/engine/training.py", line 1027, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "/Users/tomxu/miniforge3/envs/sktime-dev/lib/python3.9/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 527, in minimize
      self.apply_gradients(grads_and_vars)
    File "/Users/tomxu/miniforge3/envs/sktime-dev/lib/python3.9/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1140, in apply_gradients
      return super().apply_gradients(grads_and_vars, name=name)
    File "/Users/tomxu/miniforge3/envs/sktime-dev/lib/python3.9/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 634, in apply_gradients
      iteration = self._internal_apply_gradients(grads_and_vars)
    File "/Users/tomxu/miniforge3/envs/sktime-dev/lib/python3.9/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1166, in _internal_apply_gradients
...
    File "/Users/tomxu/miniforge3/envs/sktime-dev/lib/python3.9/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1211, in apply_grad_to_update_var
      return self._update_step_xla(grad, var, id(self._var_key(var)))
Node: 'StatefulPartitionedCall_4'
could not find registered platform with id: 0x13f038990
	 [[{{node StatefulPartitionedCall_4}}]] [Op:__inference_train_function_1051]

**Comment by SuryanarayanaY** [comment]
Hi @xxl4tomxu98 ,
> warnings.warn(
> 2022-12-29 12:04:05.465251: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
> 2022-12-29 12:04:05.465271: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: )

It seems you are trying to use GPU on MacOS. Currently Tensorflow GPU not supported on MacOS.Please refer to attached documentation for  [pip](https://www.tensorflow.org/install/pip#macos) and [source](https://www.tensorflow.org/install/source#cpu_2) installations and tested configurations.Can you please try on CPU versions and let us know if any problem arises there.
Thank you!

**Comment by xxl4tomxu98** [comment]
M1 Macbook has 8 core GPU that can be used for ML purposes. I have successfully used M1 GPU for tensorflow using Apple Metal package. I am surprized you don't seem to have knowledge of it.

**Comment by SuryanarayanaY** [comment]
Hi @xxl4tomxu98,
For `tensorflow` currently no official GPU support for MacOS. If you are using Metal Plugin which uses `tensorflow-macos` you need to follow instructions by Apple [here](https://developer.apple.com/metal/tensorflow-plugin/) since `tensorflow` and `tensorflow-macos` both are different and `tensorflow-macos` maintained by Apple.Please refer to developer comments on similar issue [here](https://github.com/tensorflow/tensorflow/issues/11085).For tensorflow you need to follow instructions mentioned in earlier comment.

Can you please confirm which instructions you have followed ?
If you are using metal plugin instructions can you try below commands and let us know if it works.

```
python -m pip install tensorflow-macos sktime
pip install -e ."[all_extras,dev] "
```
Thank you!
