### ISSUE TITLE
Loaded runtime CuDNN library: 8.0.5 but source was compiled with: 8.1.0

### ISSUE THREAD

**Issue by Anil-io** [tensorflow/tensorflow#58986]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

binary

### Tensorflow Version

2.10.1

### Custom Code

Yes

### OS Platform and Distribution

Windows 11

### Python version

3.10.8

### CUDA/cuDNN version

11.2/8.1..33

### GPU model and memory

NVIDIA QUADRO P620 / 4096 MB

### Current Behaviour?

```shell
The program runs when i am using only CPU but i get the CUDNN version mismatch when trying to Run the program using GPU.
```

### Standalone code to reproduce the issue

```shell
import os
import cv2
import glob
import random
import numpy as np
from tqdm import tqdm
from PIL import Image
import tensorflow as tf
from itertools import chain
import matplotlib.pyplot as plt
from skimage.transform import resize
from skimage.io import imread, imshow

# tensorboard --logdir=logs/ --host localhost --port 8088

seed = 42
np.random.seed = seed

#Resizing images is optional, CNNs are ok with large images
SIZE_X = 256        #Resize images (height  = X, width = Y)
SIZE_Y = 256
CHANNELS = 3


# TRAIN_DATA= 'SegTrackv2_Dataset/SegTrackv2/Train/Images'
# TEST_DATA = 'SegTrackv2_Dataset/SegTrackv2/Test/Images'

# TRAIN_DATA= 'Train/Images'
# TEST_DATA = 'Test/Images'

TRAIN_DATA= 'PatchTrain/Images'
TEST_DATA = 'PatchTest/Images'

train_ids = next(os.walk(TRAIN_DATA))[1]
test_ids = next(os.walk(TEST_DATA))[1]
classnames = test_ids

train_count = 0
test_count = 0
mask_count = 0

train_img_list = []
mask_img_list = []
test_img_list = []

# Get the list of all images in the training input and mask subfolders 

for names in train_ids:
    train_path = (os.path.join(f'{TRAIN_DATA}/{names}/Images'))
    train_img = glob.glob(f'{train_path}/**.png')
    train_img.extend(glob.glob(f'{train_path}/**.bmp'))
    train_img_list = list(chain(train_img, train_img_list))
    train_count = len(train_img_list)


    mask_path = (os.path.join(f'{TRAIN_DATA}/{names}/Masks'))
    mask_img = glob.glob(f'{mask_path}/**.png')
    mask_img.extend(glob.glob(f'{mask_path}/**.bmp'))
    mask_img_list = list(chain(mask_img, mask_img_list))
    mask_count =  len(mask_img_list)


    test_path = (os.path.join(f'{TEST_DATA}/{names}/Images'))
    test_img = glob.glob(f'{test_path}/**.png')
    test_img.extend(glob.glob(f'{test_path}/**.bmp'))
    test_img_list = list(chain(test_img, test_img_list))
    test_count = len(test_img_list)

# Create numpy array to store the images

X_train = np.zeros((train_count, SIZE_X, SIZE_Y,CHANNELS), dtype=np.uint8)
Y_train = np.zeros((train_count, SIZE_X, SIZE_Y), dtype=bool)    # Mask is the boolian value of segmented Images

# Resize Images and masks to the desired input size of convolutional layer

print('Resizing training images and masks')
for i in tqdm(range((100))): # train_count
    
    img = cv2.imread(train_img_list[i], cv2.IMREAD_COLOR)       
    img = cv2.resize(img, (SIZE_Y, SIZE_X))
    img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
    X_train[i] = img                # Fill empty X_train with values from img
       
    
    mask = cv2.imread(mask_img_list[i], 0)       
    mask = cv2.resize(mask, (SIZE_Y, SIZE_X))    
    Y_train[i] = mask 
     
# Resize test images

X_test = np.zeros((test_count, SIZE_X, SIZE_Y,CHANNELS), dtype=np.uint8)
sizes_test = []
print('Resizing test images') 
for t in tqdm(range(50)): # test_count
    
    img = cv2.imread(test_img_list[t],cv2.IMREAD_COLOR)
    img = cv2.resize(img, (SIZE_Y, SIZE_X))
    img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
    X_test[t] = img

print('Done!')

X_VAL = X_train[int(X_train.shape[0]*0.8):]
Y_VAL = Y_train[int(X_train.shape[0]*0.8):]

# Plot some random Training images and their corresponding masks

for i in range(1,7,2):
    ix = random.randint(0, train_count)
    plt.subplot(3,2,i)
    plt.title('X_train',fontsize = 5)
    plt.imshow(X_train[ix])
    plt.imshow(Y_train[ix],cmap='jet', alpha=0.5)

    plt.subplot(3,2,i+1)
    plt.title('Y_train',fontsize = 5)
    plt.imshow(np.squeeze(Y_train[ix]))


plt.show()


#Build the model

inputs = tf.keras.layers.Input((SIZE_X, SIZE_Y, CHANNELS))
s = tf.keras.layers.Lambda(lambda x: x / 255)(inputs)

#Contraction path

c1 = tf.keras.layers.Conv2D(16, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(s)
c1 = tf.keras.layers.Dropout(0.1)(c1)
c1 = tf.keras.layers.Conv2D(16, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c1)
p1 = tf.keras.layers.MaxPooling2D((2, 2))(c1)

c2 = tf.keras.layers.Conv2D(32, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(p1)
c2 = tf.keras.layers.Dropout(0.1)(c2)
c2 = tf.keras.layers.Conv2D(32, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c2)
p2 = tf.keras.layers.MaxPooling2D((2, 2))(c2)
 
c3 = tf.keras.layers.Conv2D(64, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(p2)
c3 = tf.keras.layers.Dropout(0.2)(c3)
c3 = tf.keras.layers.Conv2D(64, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c3)
p3 = tf.keras.layers.MaxPooling2D((2, 2))(c3)
 
c4 = tf.keras.layers.Conv2D(128, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(p3)
c4 = tf.keras.layers.Dropout(0.2)(c4)
c4 = tf.keras.layers.Conv2D(128, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c4)
p4 = tf.keras.layers.MaxPooling2D(pool_size=(2, 2))(c4)
 
c5 = tf.keras.layers.Conv2D(256, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(p4)
c5 = tf.keras.layers.Dropout(0.3)(c5)
c5 = tf.keras.layers.Conv2D(256, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c5)

#Expansive path 

u6 = tf.keras.layers.Conv2DTranspose(128, (2, 2), strides=(2, 2), padding='same')(c5)
u6 = tf.keras.layers.concatenate([u6, c4])
c6 = tf.keras.layers.Conv2D(128, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(u6)
c6 = tf.keras.layers.Dropout(0.2)(c6)
c6 = tf.keras.layers.Conv2D(128, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c6)
 
u7 = tf.keras.layers.Conv2DTranspose(64, (2, 2), strides=(2, 2), padding='same')(c6)
u7 = tf.keras.layers.concatenate([u7, c3])
c7 = tf.keras.layers.Conv2D(64, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(u7)
c7 = tf.keras.layers.Dropout(0.2)(c7)
c7 = tf.keras.layers.Conv2D(64, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c7)
 
u8 = tf.keras.layers.Conv2DTranspose(32, (2, 2), strides=(2, 2), padding='same')(c7)
u8 = tf.keras.layers.concatenate([u8, c2])
c8 = tf.keras.layers.Conv2D(32, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(u8)
c8 = tf.keras.layers.Dropout(0.1)(c8)
c8 = tf.keras.layers.Conv2D(32, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c8)
 
u9 = tf.keras.layers.Conv2DTranspose(16, (2, 2), strides=(2, 2), padding='same')(c8)
u9 = tf.keras.layers.concatenate([u9, c1], axis=3)
c9 = tf.keras.layers.Conv2D(16, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(u9)
c9 = tf.keras.layers.Dropout(0.1)(c9)
c9 = tf.keras.layers.Conv2D(16, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c9)
 
outputs = tf.keras.layers.Conv2D(1, (1, 1), activation='sigmoid')(c9)
 
####################################################################

model = tf.keras.Model(inputs=[inputs], outputs=[outputs])
opt = tf.keras.optimizers.Adam(learning_rate=0.001)
model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])
model.summary()


####################################################################
#Modelcheckpoint

checkpointer = tf.keras.callbacks.ModelCheckpoint('model_for_nuclei.h5', verbose=1, save_best_only=True)

callbacks = [
        tf.keras.callbacks.EarlyStopping(patience=2, monitor='val_loss'), # Patience = 3
        tf.keras.callbacks.TensorBoard(log_dir='logs')]

results = model.fit(X_train, Y_train, validation_split=0.1, batch_size=64, epochs=10, callbacks=callbacks) # val_split = 0.1

#####################################################################


idx = random.randint(0, len(X_train))

preds_train = model.predict(X_train[:int(X_train.shape[0]*0.8)], verbose=1)
preds_val = model.predict(X_VAL, verbose=1)
preds_test = model.predict(X_test, verbose=1)

 
preds_train_t = (preds_train > 0.5).astype(np.uint8)
preds_val_t =   (preds_val   > 0.5).astype(np.uint8)
preds_test_t =  (preds_test  > 0.5).astype(np.uint8)


# Perform a sanity check on some random training samples


for i in range(1,10,3):
    
    ix = random.randint(0, len(preds_train_t))
    plt.subplot(3,3,i)
    plt.title('X_train',fontsize = 5)
    plt.imshow(X_train[ix])
    plt.imshow(np.squeeze(preds_train_t[ix]),cmap = 'jet',alpha=0.5)

    plt.subplot(3,3,i+1)
    plt.title('Y_train',fontsize = 5)
    plt.imshow(Y_train[ix])

    plt.subplot(3,3,i+2)
    plt.title('Predict_Train',fontsize = 5)
    plt.imshow(np.squeeze(preds_train_t[ix]))      

plt.show()

# Perform a sanity check on some random Validation samples


for i in range(1,10,3):
    ix = random.randint(0, len(preds_val_t))
    
    plt.subplot(3,3,i)
    plt.title('X_val',fontsize = 5)
    plt.imshow(X_VAL[ix])
    plt.imshow(np.squeeze(preds_val_t[ix]),cmap = 'jet',alpha=0.5)

    plt.subplot(3,3,i+1)
    plt.title('Y_val',fontsize = 5)
    plt.imshow(Y_VAL[ix])

    plt.subplot(3,3,i+2)
    plt.title('Predict_Val',fontsize = 5)
    plt.imshow(np.squeeze(preds_val_t[ix]))
   
plt.show()

# Model Prediction on test Images 
for j in range(3):
    for i in range(1,7,2):
        
        ix = random.randint(0, len(preds_test_t))
        
        plt.subplot(3,2,i)
        plt.title('X_test',fontsize = 5)
        plt.imshow(X_test[ix])
        plt.imshow(np.squeeze(preds_test_t[ix]),cmap = 'jet',alpha=0.5)

        plt.subplot(3,2,i+1)
        plt.title('Predict_Test',fontsize = 5)
        plt.imshow(np.squeeze(preds_test_t[ix]))
        
    plt.show()

print('Done!')
```

### Relevant log output

```shell
PS C:\Users\AGIXAnilKumar\Pictures\Datasets> & C:/Users/AGIXAnilKumar/AppData/Local/Programs/Python/Python310/python.exe "c:/Users/AGIXAnilKumar/Pictures/Datasets/Segmentation_UNET copy.py"
Resizing training images and masks
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 253.25it/s]
Resizing test images
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:00<00:00, 390.69it/s]
Done!
2022-12-22 12:29:16.179310: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-22 12:29:16.624929: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 2783 MB memory:  -> device: 0, name: Quadro P620, pci bus id: 0000:01:00.0, compute capability: 6.1
Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 input_1 (InputLayer)           [(None, 256, 256, 3  0           []
                                )]

 lambda (Lambda)                (None, 256, 256, 3)  0           ['input_1[0][0]']

 conv2d (Conv2D)                (None, 256, 256, 16  448         ['lambda[0][0]']
                                )

 dropout (Dropout)              (None, 256, 256, 16  0           ['conv2d[0][0]']
                                )

 conv2d_1 (Conv2D)              (None, 256, 256, 16  2320        ['dropout[0][0]']
                                )

 max_pooling2d (MaxPooling2D)   (None, 128, 128, 16  0           ['conv2d_1[0][0]']
                                )

 conv2d_2 (Conv2D)              (None, 128, 128, 32  4640        ['max_pooling2d[0][0]']
                                )

 dropout_1 (Dropout)            (None, 128, 128, 32  0           ['conv2d_2[0][0]']
                                )

 conv2d_3 (Conv2D)              (None, 128, 128, 32  9248        ['dropout_1[0][0]']
                                )

 max_pooling2d_1 (MaxPooling2D)  (None, 64, 64, 32)  0           ['conv2d_3[0][0]']

 conv2d_4 (Conv2D)              (None, 64, 64, 64)   18496       ['max_pooling2d_1[0][0]']

 dropout_2 (Dropout)            (None, 64, 64, 64)   0           ['conv2d_4[0][0]']

 conv2d_5 (Conv2D)              (None, 64, 64, 64)   36928       ['dropout_2[0][0]']

 max_pooling2d_2 (MaxPooling2D)  (None, 32, 32, 64)  0           ['conv2d_5[0][0]']

 conv2d_6 (Conv2D)              (None, 32, 32, 128)  73856       ['max_pooling2d_2[0][0]']

 dropout_3 (Dropout)            (None, 32, 32, 128)  0           ['conv2d_6[0][0]']

 conv2d_7 (Conv2D)              (None, 32, 32, 128)  147584      ['dropout_3[0][0]']

 max_pooling2d_3 (MaxPooling2D)  (None, 16, 16, 128)  0          ['conv2d_7[0][0]']

 conv2d_8 (Conv2D)              (None, 16, 16, 256)  295168      ['max_pooling2d_3[0][0]']

 dropout_4 (Dropout)            (None, 16, 16, 256)  0           ['conv2d_8[0][0]']

 conv2d_9 (Conv2D)              (None, 16, 16, 256)  590080      ['dropout_4[0][0]']

 conv2d_transpose (Conv2DTransp  (None, 32, 32, 128)  131200     ['conv2d_9[0][0]']
 ose)

 concatenate (Concatenate)      (None, 32, 32, 256)  0           ['conv2d_transpose[0][0]',
                                                                  'conv2d_7[0][0]']

 conv2d_10 (Conv2D)             (None, 32, 32, 128)  295040      ['concatenate[0][0]']

 dropout_5 (Dropout)            (None, 32, 32, 128)  0           ['conv2d_10[0][0]']

 conv2d_11 (Conv2D)             (None, 32, 32, 128)  147584      ['dropout_5[0][0]']

 conv2d_transpose_1 (Conv2DTran  (None, 64, 64, 64)  32832       ['conv2d_11[0][0]']
 spose)

 concatenate_1 (Concatenate)    (None, 64, 64, 128)  0           ['conv2d_transpose_1[0][0]',
                                                                  'conv2d_5[0][0]']

 conv2d_12 (Conv2D)             (None, 64, 64, 64)   73792       ['concatenate_1[0][0]']

 dropout_6 (Dropout)            (None, 64, 64, 64)   0           ['conv2d_12[0][0]']

 conv2d_13 (Conv2D)             (None, 64, 64, 64)   36928       ['dropout_6[0][0]']

 conv2d_transpose_2 (Conv2DTran  (None, 128, 128, 32  8224       ['conv2d_13[0][0]']
 spose)                         )

 concatenate_2 (Concatenate)    (None, 128, 128, 64  0           ['conv2d_transpose_2[0][0]',
                                )                                 'conv2d_3[0][0]']

 conv2d_14 (Conv2D)             (None, 128, 128, 32  18464       ['concatenate_2[0][0]']
                                )

 dropout_7 (Dropout)            (None, 128, 128, 32  0           ['conv2d_14[0][0]']
                                )

 conv2d_15 (Conv2D)             (None, 128, 128, 32  9248        ['dropout_7[0][0]']
                                )

 conv2d_transpose_3 (Conv2DTran  (None, 256, 256, 16  2064       ['conv2d_15[0][0]']
 spose)                         )

 concatenate_3 (Concatenate)    (None, 256, 256, 32  0           ['conv2d_transpose_3[0][0]',
                                )                                 'conv2d_1[0][0]']

 conv2d_16 (Conv2D)             (None, 256, 256, 16  4624        ['concatenate_3[0][0]']
                                )

 dropout_8 (Dropout)            (None, 256, 256, 16  0           ['conv2d_16[0][0]']
                                )

 conv2d_17 (Conv2D)             (None, 256, 256, 16  2320        ['dropout_8[0][0]']
                                )

 conv2d_18 (Conv2D)             (None, 256, 256, 1)  17          ['conv2d_17[0][0]']

==================================================================================================
Total params: 1,941,105
Trainable params: 1,941,105
Non-trainable params: 0
__________________________________________________________________________________________________
Epoch 1/10
2022-12-22 12:29:19.513315: E tensorflow/stream_executor/cuda/cuda_dnn.cc:377] Loaded runtime CuDNN library: 8.0.5 but source was compiled with: 8.1.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2022-12-22 12:29:19.514953: W tensorflow/core/framework/op_kernel.cc:1780] OP_REQUIRES failed at conv_ops_fused_impl.h:601 : UNIMPLEMENTED: DNN library is not found.
Traceback (most recent call last):
  File "c:\Users\AGIXAnilKumar\Pictures\Datasets\Segmentation_UNET copy.py", line 199, in <module>
    results = model.fit(X_train, Y_train, validation_split=0.1, batch_size=64, epochs=10, callbacks=callbacks) # val_split = 0.1
  File "C:\Users\AGIXAnilKumar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\AGIXAnilKumar\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\eager\execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnimplementedError: Graph execution error:

Detected at node 'model/conv2d/Relu' defined at (most recent call last):
    File "c:\Users\AGIXAnilKumar\Pictures\Datasets\Segmentation_UNET copy.py", line 199, in <module>
      results = model.fit(X_train, Y_train, validation_split=0.1, batch_size=64, epochs=10, callbacks=callbacks) # val_split = 0.1
    File "C:\Users\AGIXAnilKumar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\AGIXAnilKumar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 1564, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\AGIXAnilKumar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 1160, in train_function
      return step_function(self, iterator)
    File "C:\Users\AGIXAnilKumar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 1146, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\AGIXAnilKumar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 1135, in run_step
      outputs = model.train_step(data)
    File "C:\Users\AGIXAnilKumar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 993, in train_step
      y_pred = self(x, training=True)
    File "C:\Users\AGIXAnilKumar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\AGIXAnilKumar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 557, in __call__
      return super().__call__(*args, **kwargs)
    File "C:\Users\AGIXAnilKumar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\AGIXAnilKumar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\base_layer.py", line 1097, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "C:\Users\AGIXAnilKumar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\utils\traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\AGIXAnilKumar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\functional.py", line 510, in call
      return self._run_internal_graph(inputs, training=training, mask=mask)
    File "C:\Users\AGIXAnilKumar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\functional.py", line 667, in _run_internal_graph
      outputs = node.layer(*args, **kwargs)
    File "C:\Users\AGIXAnilKumar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\AGIXAnilKumar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\base_layer.py", line 1097, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "C:\Users\AGIXAnilKumar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\utils\traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\AGIXAnilKumar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\layers\convolutional\base_conv.py", line 314, in call
      return self.activation(outputs)
    File "C:\Users\AGIXAnilKumar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\activations.py", line 317, in relu
      return backend.relu(
    File "C:\Users\AGIXAnilKumar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\backend.py", line 5366, in relu
      x = tf.nn.relu(x)
Node: 'model/conv2d/Relu'
DNN library is not found.
         [[{{node model/conv2d/Relu}}]] [Op:__inference_train_function_3360]
```
</details>

**Comment by tilakrayal** [comment]
@Anil-io,
Tensorflow v2.11 is compatible with cuDNN 8.1.0 and CUDA 11.2. Could you please try with the mentioned compatible version from [here](https://www.tensorflow.org/install/source_windows#gpu) and release notes for the [reference](https://github.com/tensorflow/tensorflow/releases/tag/v2.11.0). 
Also please check at this path "Control Panel ->System and Security->System->Advanced System settings" , and the [link](https://towardsdatascience.com/installing-tensorflow-with-cuda-cudnn-and-gpu-support-on-windows-10-60693e46e781) as well. Thank you!

**Comment by Anil-io** [comment]
@tilakrayal Thank you for your response. I had to reinstall CUDA toolkit v11.8 and cuDNN v.8.6 and that has solved the issue. the mentioned compatible versions in tensorflow website didn't work for me.

**Comment by tilakrayal** [comment]
@Anil-io,
I tried to follow the tested build [configurations](https://www.tensorflow.org/install/source_windows#gpu) and install the tensorflow v2.10 as mentioned here and it was installed without any issues. The tested build configurations which are mentioned are tested on various platforms with the compatible CUDA, compiler and cuDNN and it will be successfully installed. 
![Screenshot (105)](https://user-images.githubusercontent.com/81610181/209804748-12ffaf35-9af7-460e-97b3-ac2c12487e6b.png)


Thank you!
