### ISSUE TITLE
NotImplementedError: Cannot convert a symbolic tf.Tensor (strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported.

### ISSUE THREAD

**Issue by UnivexDont** [tensorflow/tensorflow#58993]
### 1. System information

- MacOS (m1):
- Conda:
- TensorFlow library (version=2.10):
MacOS

### 2. Code

Provide code to help us reproduce your issues using one of the following options:

#### Option A: Reference colab notebooks

1) get_concrete_function()

```
import coremltools as ct
import tensorflow as tf
import talib as ta
import numpy as np
import os

tf.config.experimental_run_functions_eagerly(True)

@tf.function(input_signature=[tf.TensorSpec(shape=None, dtype=tf.float32)])


def gelu_tanh_activation(features):
    featureSize = 6
    xFeatures = [0]*featureSize
    for i in range(0, featureSize):
        xFeatures[i] = float(features[i])
    return ta.MA(np.array(xFeatures).astype('double'), timeperiod = 2)

conc_func = gelu_tanh_activation.get_concrete_function()

# # provide the concrete fucntion as a list
mlmodel = ct.convert([conc_func])
mlmodel.save(os.environ['HOME'] + '/ModelSHSZ/release/ConcFunc')
```

### Error and Logs

Traceback (most recent call last):
  File "/Users/thao/Private/TFLite/covert.py", line 20, in <module>
    conc_func = gelu_tanh_activation.get_concrete_function()
  File "/Users/thao/miniforge3/lib/python3.10/site-packages/tensorflow/python/eager/def_function.py", line 1239, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/Users/thao/miniforge3/lib/python3.10/site-packages/tensorflow/python/eager/def_function.py", line 1219, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/Users/thao/miniforge3/lib/python3.10/site-packages/tensorflow/python/eager/def_function.py", line 785, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/Users/thao/miniforge3/lib/python3.10/site-packages/tensorflow/python/eager/function.py", line 2523, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/Users/thao/miniforge3/lib/python3.10/site-packages/tensorflow/python/eager/function.py", line 2760, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/Users/thao/miniforge3/lib/python3.10/site-packages/tensorflow/python/eager/function.py", line 2670, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/Users/thao/miniforge3/lib/python3.10/site-packages/tensorflow/python/framework/func_graph.py", line 1247, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/Users/thao/miniforge3/lib/python3.10/site-packages/tensorflow/python/eager/def_function.py", line 677, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/Users/thao/miniforge3/lib/python3.10/site-packages/tensorflow/python/framework/func_graph.py", line 1233, in autograph_handler
    raise e.ag_error_metadata.to_exception(e)
  File "/Users/thao/miniforge3/lib/python3.10/site-packages/tensorflow/python/framework/func_graph.py", line 1222, in autograph_handler
    return autograph.converted_call(
  File "/Users/thao/miniforge3/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 439, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "/var/folders/3r/ptdgzwkd4y72zwkryhpz5h7c0000gn/T/__autograph_generated_fileja51y05y.py", line 26, in tf__gelu_tanh_activation
    retval_ = ag__.converted_call(ag__.ld(ta).MA, (ag__.converted_call(ag__.converted_call(ag__.ld(np).array, (ag__.ld(xFeatures),), None, fscope).astype, ('double',), None, fscope),), dict(timeperiod=2), fscope)
  File "/Users/thao/miniforge3/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 371, in converted_call
    return py_builtins.overload_of(f)(*args)
  File "/Users/thao/miniforge3/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 924, in __array__
    raise NotImplementedError(
NotImplementedError: in user code:

    File "/Users/thao/Private/TFLite/covert.py", line 17, in gelu_tanh_activation  *
        return ta.MA(np.array(xFeatures).astype('double'), timeperiod = 2)

    NotImplementedError: Cannot convert a symbolic tf.Tensor (strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported.

**Comment by tiruk007** [comment]
@sushreebarsa 
I was able to reproduce the issue on Colab using  TF v2.11. Please find the gist [here](https://colab.research.google.com/gist/tiruk007/4d2d32c76a33c83396532f9640d7797e/58993.ipynb#scrollTo=DF5LJgER_yhE) for reference.
Thank you!

**Comment by UnivexDont** [comment]
> @sushreebarsa I was able to reproduce the issue on Colab using TF v2.11. Please find the gist [here](https://colab.research.google.com/gist/tiruk007/4d2d32c76a33c83396532f9640d7797e/58993.ipynb#scrollTo=DF5LJgER_yhE) for reference. Thank you!
```
import coremltools as ct
import tensorflow as tf
import numpy as np
import os

tf.config.experimental_run_functions_eagerly(True)

@tf.function(input_signature=[tf.TensorSpec(shape=None, dtype=tf.float32)])
def gelu_tanh_activation(features):
    featureSize = 6
    xFeatures = [0]*featureSize
    for i in range(0, featureSize):
        xFeatures[i] = float(features[i])
    return np.array(xFeatures).astype('double')

conc_func = gelu_tanh_activation.get_concrete_function()

# # provide the concrete fucntion as a list
mlmodel = ct.convert([conc_func])
mlmodel.save('/content/model/')
```

**Comment by pjpratik** [comment]
@UnivexDont Mixing numpy ops and tf ops is not suggested The workaround is to return `xFeatures` a list instead of converting into numpy array.
Code
```
import coremltools as ct
import tensorflow as tf
import numpy as np
import os

tf.config.experimental_run_functions_eagerly(True)

@tf.function(input_signature=[tf.TensorSpec(shape=[None], dtype=tf.float32)])
def gelu_tanh_activation(features):
    featureSize = 6
    xFeatures = [0]*featureSize
    for i in range(0, featureSize):
        xFeatures[i] = float(features[i])
    
    return xFeatures

conc_func = gelu_tanh_activation.get_concrete_function()

# # provide the concrete fucntion as a list
mlmodel = ct.convert([conc_func])
mlmodel.save('/content/test.mlmodel')

```
Let us know if that helps. Thank you.
