### ISSUE TITLE
RuntimeError: MetaGraphDef when converting to tflite

### ISSUE THREAD

**Issue by josago97** [tensorflow/tensorflow#59020]
### 1. System information

- OS Platform and Distribution: Windows 10 Pro 21H2
- TensorFlow installation: 2.10.0
- TensorFlow library: pip package

### 2. Code

converter = tf.lite.TFLiteConverter.from_saved_model(input_model_path) # path to the SavedModel directory
converter.allow_custom_ops = True
converter.optimizations =  [tf.lite.Optimize.DEFAULT]]
tflite_model = converter.convert()

I am using this model: https://drive.google.com/file/d/1zyEqDumc296TiZ6WxsgVPBDJVIMWvZKf/view?usp=share_link

### 3. Failure after conversion
I get this error:

C:\Users\JOSE\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\saved_model\loader_impl.py:102: RuntimeWarning: Unexpected end-group tag: Not all data was converted
  saved_model.ParseFromString(file_content)
Traceback (most recent call last):
  File "D:\JOSE\Documents\Proyectos C#\Pokedex\Pokedex.ModelBuilder\bin\Debug\net6.0\Workspace\tflite_converter.py", line 16, in <module>
    convert_model('.', 'D:\JOSE\Documents\Proyectos C#\Pokedex\Pokedex.ModelBuilder\bin\Debug\net6.0\Workspace\model')
  File "D:\JOSE\Documents\Proyectos C#\Pokedex\Pokedex.ModelBuilder\bin\Debug\net6.0\Workspace\tflite_converter.py", line 5, in convert_model
    converter = tf.lite.TFLiteConverter.from_saved_model(input_model_path) # path to the SavedModel directory
  File "C:\Users\JOSE\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\lite\python\lite.py", line 1789, in from_saved_model
    saved_model = _load(saved_model_dir, tags)
  File "C:\Users\JOSE\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\saved_model\load.py", line 800, in load
    result = load_partial(export_dir, None, tags, options)["root"]
  File "C:\Users\JOSE\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\saved_model\load.py", line 949, in load_partial
    root = load_v1_in_v2.load(export_dir, tags)
  File "C:\Users\JOSE\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\saved_model\load_v1_in_v2.py", line 284, in load
    result = loader.load(tags=tags)
  File "C:\Users\JOSE\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\saved_model\load_v1_in_v2.py", line 209, in load
    meta_graph_def = self.get_meta_graph_def_from_tags(tags)
  File "C:\Users\JOSE\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\saved_model\load_v1_in_v2.py", line 88, in get_meta_graph_def_from_tags
    return super(_EagerSavedModelLoader, self).get_meta_graph_def_from_tags(
  File "C:\Users\JOSE\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\saved_model\loader_impl.py", line 394, in get_meta_graph_def_from_tags
    raise RuntimeError(
RuntimeError: MetaGraphDef associated with tags {'serve'} could not be found in SavedModel, with available tags '[]'. To inspect available tag-sets in the SavedModel, please use the SavedModel CLI: `saved_model_cli`.

**Comment by tiruk007** [comment]
@josago97 
Could you please provide complete code or Colab gist for reproducing the issue reported here ?
Thank you!

**Comment by josago97** [comment]
I am generating the model through ML.NET (https://github.com/dotnet/machinelearning), this is the code I use (https://github.com/josago97/Pokedex/blob/main/Pokedex.ModelBuilder/ModelTrainer.cs). To convert that model to TFLite I am using the code that I have put above, this would be the complete code:

```
import tensorflow as tf

def convert_model(input_model_path, output_model_name):
    # Convert the model
    converter = tf.lite.TFLiteConverter.from_saved_model(input_model_path) # path to the SavedModel directory
    converter.allow_custom_ops = True
    converter.optimizations =  [tf.lite.Optimize.DEFAULT]
    tflite_model = converter.convert()
    
    # Save the model.
    with open(output_model_name + '.tflite', 'wb') as f:
      f.write(tflite_model)


if __name__ == '__main__':
    print(tf.__version__)
    convert_model('.', 'D:\JOSE\Documents\Proyectos C#\Pokedex\Pokedex.ModelBuilder\bin\Debug\net6.0\Workspace\model')
```

**Comment by tiruk007** [comment]
@josago97 
The machine learning (ML) models you use with TensorFlow Lite are originally built and trained using TensorFlow core libraries and tools. We can only convert TensorFlow models which are stored using the SavedModel format and is generated either using the high-level tf.keras.* APIs (a Keras model) or the low-level tf.* APIs (from which you generate concrete functions).Could you please refer to the [Model conversion overview](https://www.tensorflow.org/lite/models/convert) and [Colab gist](https://colab.research.google.com/gist/tiruk007/74a17dcec6f1c6f9918db218daf36536/untitled61.ipynb) for reference.

Thank you!

**Comment by josago97** [comment]
OK thanks. I will try to generate the model with keras as you tell me.

**Comment by tiruk007** [comment]
@josago97 
Could you please close the issue if it is resolved ?
Thank you!
