### ISSUE TITLE
Unable to build in WSL2

### ISSUE THREAD

**Issue by heliumsea** [tensorflow/tensorflow#59068]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.11

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 22.04 in WSL2

### Python version

3.10

### Bazel version

5.3.0

### GCC/Compiler version

11.3.0

### CUDA/cuDNN version

11.2/8.1

### GPU model and memory

1080Ti with 11GB memory

### Current Behaviour?

```shell
First, it got two warnings:

WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/071fc48c32248196b17912cdab206f29fa6ded38.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/1ec021467da65c06cd4aa24ce81898b0759bd16b.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found

Then, got errors:

ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
        File "/home/someone/code/tensorflow/third_party/gpus/cuda_configure.bzl", line 1430, column 38, in _cuda_autoconf_impl
                _create_local_cuda_repository(repository_ctx)
        File "/home/someone/code/tensorflow/third_party/gpus/cuda_configure.bzl", line 1007, column 35, in _create_local_cuda_repository
                cuda_config = _get_cuda_config(repository_ctx, find_cuda_config_script)
        File "/home/someone/code/tensorflow/third_party/gpus/cuda_configure.bzl", line 747, column 52, in _get_cuda_config
                compute_capabilities = compute_capabilities(repository_ctx),
        File "/home/someone/code/tensorflow/third_party/gpus/cuda_configure.bzl", line 473, column 32, in compute_capabilities
                auto_configure_fail("Invalid compute capability: %s" % capability)
        File "/home/someone/code/tensorflow/third_party/gpus/cuda_configure.bzl", line 353, column 9, in auto_configure_fail
                fail("\n%sCuda Configuration Error:%s %s\n" % (red, no_color, msg))
Error in fail:
Cuda Configuration Error: Invalid compute capability: compute_112
ERROR: /home/someone/code/tensorflow/WORKSPACE:15:14: fetching cuda_configure rule //external:local_config_cuda: Traceback (most recent call last):
        File "/home/someone/code/tensorflow/third_party/gpus/cuda_configure.bzl", line 1430, column 38, in _cuda_autoconf_impl
                _create_local_cuda_repository(repository_ctx)
        File "/home/someone/code/tensorflow/third_party/gpus/cuda_configure.bzl", line 1007, column 35, in _create_local_cuda_repository
                cuda_config = _get_cuda_config(repository_ctx, find_cuda_config_script)
        File "/home/someone/code/tensorflow/third_party/gpus/cuda_configure.bzl", line 747, column 52, in _get_cuda_config
                compute_capabilities = compute_capabilities(repository_ctx),
        File "/home/someone/code/tensorflow/third_party/gpus/cuda_configure.bzl", line 473, column 32, in compute_capabilities
                auto_configure_fail("Invalid compute capability: %s" % capability)
        File "/home/someone/code/tensorflow/third_party/gpus/cuda_configure.bzl", line 353, column 9, in auto_configure_fail
                fail("\n%sCuda Configuration Error:%s %s\n" % (red, no_color, msg))
Error in fail:
Cuda Configuration Error: Invalid compute capability: compute_112
INFO: Found applicable config definition build:cuda in file /home/someone/code/tensorflow/.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
INFO: Found applicable config definition build:cuda in file /home/someone/code/tensorflow/.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
ERROR: @local_config_cuda//:enable_cuda :: Error loading option @local_config_cuda//:enable_cuda:
Cuda Configuration Error: Invalid compute capability: compute_112
```

### Standalone code to reproduce the issue

```shell
./configure

bazel build --config=cuda //tensorflow/tools/pip_package:build_pip_package
```

### Relevant log output

_No response_</details>

**Comment by nitins17** [comment]
Can you try with Cuda 11.8 and cuDNN 8.6?

**Comment by heliumsea** [comment]
@nitins17 I had tried 11.8 + 8.7 and got the same error. Do I still need to try 11.8 + 8.6?
Combinations I tried: 
cuda 11.8 + cuDNN 8.7, 
cuda 11.4 + cuDNN 8.7, 
cuda 11.2 + cuDNN 8.1.

**Comment by heliumsea** [comment]
I solved this problem. The compute compatibility should be 6.1, but I set 11.8. You can close this issue.
