### ISSUE TITLE
Blas SGEMM launch failed issue 

### ISSUE THREAD

**Issue by mertalbaba** [tensorflow/tensorflow#59128]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

2.4.0

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.8

### CUDA/cuDNN version

11.0/10.1

### GPU model and memory

Quadro RTX 6000 24GB

### Current Behaviour?

```shell
Constantly gettin Blas SGEMM launch failed error on a multi-gpu server. 

Tried this 
os.environ["CUDA_VISIBLE_DEVICES"]="1"
gpus = tf.config.list_physical_devices('GPU')
if gpus:
  # Restrict TensorFlow to only use the first GPU
  try:
    tf.config.set_visible_devices(gpus[0], 'GPU')
    tf.config.set_memory_growth(physical_devices[0], True)
    logical_gpus = tf.config.list_logical_devices('GPU')
  except RuntimeError as e:
    # Visible devices must be set before GPUs have been initialized
    print(e)
```

### Standalone code to reproduce the issue

```shell
Traceback (most recent call last):
  File "trainAllPPOs_server.py", line 209, in <module>
    train()
  File "trainAllPPOs_server.py", line 77, in train
    embd = tcn.get_embedding(state, normalize=True)
  File "/local/home/balbaba/GIRL/TCN.py", line 50, in get_embedding
    return self.model(inputs/127.5 - 1)
  File "/local/home/balbaba/.virtualenvs/venvgirl/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1012, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/local/home/balbaba/.virtualenvs/venvgirl/lib/python3.8/site-packages/tensorflow/python/keras/engine/functional.py", line 424, in call
    return self._run_internal_graph(
  File "/local/home/balbaba/.virtualenvs/venvgirl/lib/python3.8/site-packages/tensorflow/python/keras/engine/functional.py", line 560, in _run_internal_graph
    outputs = node.layer(*args, **kwargs)
  File "/local/home/balbaba/.virtualenvs/venvgirl/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1012, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/local/home/balbaba/.virtualenvs/venvgirl/lib/python3.8/site-packages/tensorflow/python/keras/engine/functional.py", line 424, in call
    return self._run_internal_graph(
  File "/local/home/balbaba/.virtualenvs/venvgirl/lib/python3.8/site-packages/tensorflow/python/keras/engine/functional.py", line 560, in _run_internal_graph
    outputs = node.layer(*args, **kwargs)
  File "/local/home/balbaba/.virtualenvs/venvgirl/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1012, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/local/home/balbaba/.virtualenvs/venvgirl/lib/python3.8/site-packages/tensorflow/python/keras/layers/convolutional.py", line 248, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/local/home/balbaba/.virtualenvs/venvgirl/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/local/home/balbaba/.virtualenvs/venvgirl/lib/python3.8/site-packages/tensorflow/python/ops/nn_ops.py", line 1013, in convolution_v2
    return convolution_internal(
  File "/local/home/balbaba/.virtualenvs/venvgirl/lib/python3.8/site-packages/tensorflow/python/ops/nn_ops.py", line 1143, in convolution_internal
    return op(
  File "/local/home/balbaba/.virtualenvs/venvgirl/lib/python3.8/site-packages/tensorflow/python/ops/nn_ops.py", line 2597, in _conv2d_expanded_batch
    return gen_nn_ops.conv2d(
  File "/local/home/balbaba/.virtualenvs/venvgirl/lib/python3.8/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 932, in conv2d
    _ops.raise_from_not_ok_status(e, name)
  File "/local/home/balbaba/.virtualenvs/venvgirl/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 6862, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InternalError: Blas SGEMM launch failed : m=9216, n=64, k=64 [Op:Conv2D]
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@mertalbaba,
I tried to execute the mentioned without any issue/error on tensorflow latest version. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/f1f91d480dda97e21d6e9ef752469a43/untitled844.ipynb). 

TensorFlow will by default only use a single GPU. To use multiple GPUs you need to either do data or model parallelism. The easiest way to do data parallelism is using distribution strategies; take a look at mirrored strategy or our [tf2 guide on distributed training](https://www.tensorflow.org/alpha/guide/distribute_strategy).
