### ISSUE TITLE
Stop exposing `tensorboard` console script in standard Tensorflow package?

### ISSUE THREAD

**Issue by stefan6419846** [tensorflow/tensorflow#59183]
### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

2.11.0

### Custom Code

No

### OS Platform and Distribution

OpenSUSE Leap 15.3

### Current Behaviour?

```shell
The *tensorflow_cpu* Python package exposes the `tensorboard` command, leading to a duplicate declaration of the corresponding entry point. For environments where such duplicate commands are considered bad behavior, an exception has to be added.

There is some documentation on this inside the corresponding code: https://github.com/tensorflow/tensorflow/blob/3b43530ab8d9513f78368652e22558b4a1286ee4/tensorflow/tools/pip_package/setup.py#L183-L188 Doing a `git blame`, this seems to have been introduced in https://github.com/tensorflow/tensorflow/commit/05c491d30888088873fedfbe81bca378c8c3fc87, which does not seem to provide any additional details on it as well.

For me this sounds like an issue which should rather be fixed within *pip* instead of working around this in *tensorflow* for multiple years. Having a quick look at the issue tracker there, I could not find an issue which describes such a behavior. Has anything been done to possibly fix this/get this fixed for *pip*?
```

### Standalone code to reproduce the issue

```shell
`grep -r "tensorboard.main:run_main" .`, where `.` is the directory of the virtual environment the TensorFlow and TensorBoard packages have been installed inside. This will produce a result inside `entry_points.txt` for `tensorboard` and `tensorflow_cpu`.
```

**Comment by mohantym** [comment]
@stefan6419846 !
Thanks for sharing your observation on duplicacy w.rto tensorboard and tensorflow-cpu.


As per this [comments ](https://github.com/tensorflow/tensorflow/blob/3b43530ab8d9513f78368652e22558b4a1286ee4/tensorflow/tools/pip_package/setup.py#L183-L188:~:text=%23%20We%20need%20to,if%20building%20tf_nightly.) , It is already excluding the installation of tensorboard script in nightly version.

Not sure on coming with a fix to avoid of duplication of commands in setup.py for now.

@SuryanarayanaY !
Could you look this issue.

Thank you!

**Comment by SpecLad** [comment]
This is preventing TensorFlow from being installed with [installer](https://installer.readthedocs.io/):

```console
# python -m installer tensorboard-2.12.1-py3-none-any.whl
# python -m installer tensorflow-2.12.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/venv/lib/python3.8/site-packages/installer/__main__.py", line 98, in <module>
    _main(sys.argv[1:], "python -m installer")
  File "/opt/venv/lib/python3.8/site-packages/installer/__main__.py", line 94, in _main
    installer.install(source, destination, {})
  File "/opt/venv/lib/python3.8/site-packages/installer/_core.py", line 87, in install
    record = destination.write_script(
  File "/opt/venv/lib/python3.8/site-packages/installer/destinations.py", line 230, in write_script
    entry = self.write_to_fs(
  File "/opt/venv/lib/python3.8/site-packages/installer/destinations.py", line 167, in write_to_fs
    raise FileExistsError(message)
FileExistsError: File already exists: /opt/venv/bin/tensorboard
```

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

**Comment by stefan6419846** [comment]
This seems to still be an issue: https://github.com/tensorflow/tensorflow/blob/36a0ea85c4953cf157b27f647a9423a2cc235a8c/tensorflow/tools/pip_package/setup.py#L177-L182 and https://github.com/tensorflow/tensorboard/blob/947a790ba42905af45fff4759fff4129c616160d/tensorboard/pip_package/setup.py#L34-L36
