### ISSUE TITLE
[macos-arm64] //tensorflow/python:nn_batchnorm_test_cpu fails in macos Arm64

### ISSUE THREAD

**Issue by nitins17** [tensorflow/tensorflow#59206]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf nightly

### Custom Code

Yes

### OS Platform and Distribution

macOS Monterey 12.4, Arm64

### Python version

3.9.9

### Bazel version

5.3.0

### GCC/Compiler version

Clang from Xcode 13.4

### Current Behaviour?

```shell
ERROR: testBasic (__main__.MomentsTest)
MomentsTest.testBasic
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_admin/4a764cdae64932883d338b1294a81bf1/execroot/org_tensorflow/bazel-out/darwin_arm64-opt/bin/tensorflow/python/nn_batchnorm_test_cpu.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 1624, in decorated
    return f(self, *args, **kwargs)
  File "/private/var/tmp/_bazel_admin/4a764cdae64932883d338b1294a81bf1/execroot/org_tensorflow/bazel-out/darwin_arm64-opt/bin/tensorflow/python/nn_batchnorm_test_cpu.runfiles/org_tensorflow/tensorflow/python/ops/nn_batchnorm_test.py", line 522, in testBasic
    self.RunMomentTest(
  File "/private/var/tmp/_bazel_admin/4a764cdae64932883d338b1294a81bf1/execroot/org_tensorflow/bazel-out/darwin_arm64-opt/bin/tensorflow/python/nn_batchnorm_test_cpu.runfiles/org_tensorflow/tensorflow/python/ops/nn_batchnorm_test.py", line 499, in RunMomentTest
    x_numpy = x_numpy.astype(np.float128)
  File "/Users/admin/tf_macos_ci_job/.tf-venv/lib/python3.9/site-packages/numpy/__init__.py", line 313, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float128'

----------------------------------------------------------------------
```
```


### Standalone code to reproduce the issue

```shell
Run `bazel --bazelrc="macos.bazelrc" test //tensorflow/python:nn_batchnorm_test_cpu` from the TensorFlow root directory. 

Bazel configs I used are in https://gist.github.com/nitins17/73e0818b3a6bec240775c2619540a979
```

### Relevant log output

_No response_</details>

**Comment by SuryanarayanaY** [comment]
Hi @nitins17 ,
The tested configurations until latest version 2.11V is attached [here](https://www.tensorflow.org/install/source#macos). Iam not sure yet for nightly build what configurations are tested or being tested.

<img width="1512" alt="Screenshot 2023-01-12 at 6 34 31 PM" src="https://user-images.githubusercontent.com/116063290/212079287-e342035d-22a2-4be3-aa20-7fc088187343.png">


Can you test with tested configurations mentioned and confirm whether the problem still exists.Meanwhile I will also try to build as per your given configurations.

**Comment by kulinseth** [comment]
```
ERROR: testBasic (__main__.MomentsTest)
MomentsTest.testBasic
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_admin/4a764cdae64932883d338b1294a81bf1/execroot/org_tensorflow/bazel-out/darwin_arm64-opt/bin/tensorflow/python/nn_batchnorm_test_cpu.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 1624, in decorated
    return f(self, *args, **kwargs)
  File "/private/var/tmp/_bazel_admin/4a764cdae64932883d338b1294a81bf1/execroot/org_tensorflow/bazel-out/darwin_arm64-opt/bin/tensorflow/python/nn_batchnorm_test_cpu.runfiles/org_tensorflow/tensorflow/python/ops/nn_batchnorm_test.py", line 522, in testBasic
    self.RunMomentTest(
  File "/private/var/tmp/_bazel_admin/4a764cdae64932883d338b1294a81bf1/execroot/org_tensorflow/bazel-out/darwin_arm64-opt/bin/tensorflow/python/nn_batchnorm_test_cpu.runfiles/org_tensorflow/tensorflow/python/ops/nn_batchnorm_test.py", line 499, in RunMomentTest
    x_numpy = x_numpy.astype(np.float128)
  File "/Users/admin/tf_macos_ci_job/.tf-venv/lib/python3.9/site-packages/numpy/__init__.py", line 313, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float128'

----------------------------------------------------------------------
```
@nitins17 , this issue is a numpy issue. We don't have `float128` support for M1. We can skip this test till numpy adds that support.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
