### ISSUE TITLE
Test failure due to inconsistencies related to MKL 

### ISSUE THREAD

**Issue by Flamefire** [tensorflow/tensorflow#59252]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

Linux RHEL 7

### Python version

3.10

### Bazel version

5.1.1

### GCC/Compiler version

11.3

### Current Behaviour?

```shell
I see failing tests while running `bazel test`.

The `testGetMemoryInfoCPU` is guarded by a skip `if test_util.IsMklEnabled():`
And the other tests has a similar condition.

So it looks like `IsMklEnabled` doesn't return true when it should. Further investigation leads to several macros in the build files:

- `IsMklEnabled` returns true when `defined(INTEL_MKL) && defined(ENABLE_MKL)`
- There is `if_mkl([":mkl_cpu_allocator"])` which is why `testGetMemoryInfoCPU` fails when true
- `if_mkl` is true on `linux_x86_64` unconditionally
- `if_mkl(["-DINTEL_MKL"])`
- `if_enable_mkl(["-DENABLE_MKL"])`

I'd suggest to simplify this so either there is MKL or there is not. Having multiple macros with different defaults doesn't make sense to me. Or maybe the default for "ENABLE_MKL" should be the same as for "INTEL_MKL", e.g. True on x86
```

### Standalone code to reproduce the issue

```shell
bazel test
```

### Relevant log output

```shell
FAIL: testGetMemoryInfoCPU (__main__.ContextTest)
ContextTest.testGetMemoryInfoCPU
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dev/shm/jfg508/TensorFlow/2.9.1/foss-2022a/TensorFlow/bazel-root/bac5198b45911f6921886c0013c301e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/eager/context_test_cpu.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 2229, in decorated
    return func(self, *args, **kwargs)
  File "/dev/shm/jfg508/TensorFlow/2.9.1/foss-2022a/TensorFlow/bazel-root/bac5198b45911f6921886c0013c301e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/eager/context_test_cpu.runfiles/org_tensorflow/tensorflow/python/eager/context_test.py", line 141, in testGetMemoryInfoCPU
    with self.assertRaisesRegex(ValueError, 'Allocator stats not available'):
AssertionError: ValueError not raised

FAIL: test_simple (__main__.NodeFileWriterTest)
NodeFileWriterTest.test_simple
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dev/shm/jfg508/TensorFlow/2.9.1/foss-2022a/TensorFlow/bazel-root/bac5198b45911f6921886c0013c301e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/framework/node_file_writer_test_cpu.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 2157, in decorated
    return func(self, *args, **kwargs)
  File "/dev/shm/jfg508/TensorFlow/2.9.1/foss-2022a/TensorFlow/bazel-root/bac5198b45911f6921886c0013c301e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/framework/node_file_writer_test_cpu.runfiles/org_tensorflow/tensorflow/python/framework/node_file_writer_test.py", line 142, in test_simple
    self.assertEqual(node_def1.op, 'MatMul')
AssertionError: 
- _MklMatMul
? ----
+ MatMul
```
</details>

**Comment by VRehnberg** [comment]
I have the same problem with Bazel 5.0.0 as well. Though, I only experience this problem when installing on the nodes where we have GPUs. But, I experience it consistently on both SkyLake CPUs (with V100 or T4 GPUs) and IceLake CPUs (with A40 or A100 GPUs).

## Relevant logs with Bazel 5.0.0
```
======================================================================
FAIL: test_simple (__main__.NodeFileWriterTest)
NodeFileWriterTest.test_simple
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dev/shm/TensorFlow/2.9.1/foss-2022a/TensorFlow/bazel-root/084a70f7f2c001309f3903f9b7d82f51/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/framework/node_file_writer_test_cpu.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 2157, in decorated
    return func(self, *args, **kwargs)
  File "/dev/shm/TensorFlow/2.9.1/foss-2022a/TensorFlow/bazel-root/084a70f7f2c001309f3903f9b7d82f51/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/framework/node_file_writer_test_cpu.runfiles/org_tensorflow/tensorflow/python/framework/node_file_writer_test.py", line 142, in test_simple
    self.assertEqual(node_def1.op, 'MatMul')
AssertionError: 
- _MklMatMul
? ----
+ MatMul


======================================================================
FAIL: test_simpleWithEagerOpAsFunctionEnabled (__main__.NodeFileWriterTest)
NodeFileWriterTest.test_simpleWithEagerOpAsFunctionEnabled
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dev/shm/TensorFlow/2.9.1/foss-2022a/TensorFlow/bazel-root/084a70f7f2c001309f3903f9b7d82f51/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/framework/node_file_writer_test_cpu.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 1127, in wrapper
    return fn(*args, **kwargs)
  File "/dev/shm/TensorFlow/2.9.1/foss-2022a/TensorFlow/bazel-root/084a70f7f2c001309f3903f9b7d82f51/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/framework/node_file_writer_test_cpu.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 2157, in decorated
    return func(self, *args, **kwargs)
  File "/dev/shm/TensorFlow/2.9.1/foss-2022a/TensorFlow/bazel-root/084a70f7f2c001309f3903f9b7d82f51/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/framework/node_file_writer_test_cpu.runfiles/org_tensorflow/tensorflow/python/framework/node_file_writer_test.py", line 142, in test_simple
    self.assertEqual(node_def1.op, 'MatMul')
AssertionError: 
- _MklMatMul
? ----
+ MatMul

```

**Comment by Flamefire** [comment]
The issue might have been fixed by https://github.com/tensorflow/tensorflow/commit/5ec3d2e626589540bcfbeb7dac40255034e587df
