### ISSUE TITLE
How to copy a session which can run with options?

### ISSUE THREAD

**Issue by Kobe972** [tensorflow/tensorflow#59265]
### Issue Type

Others

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.8.0

### Custom Code

Yes

### OS Platform and Distribution

Windows 11

### Python version

3.10

### Current Behaviour?

```shell
Here's part of my code:

 def fun(self):
        self.lr=1e-2
        self.gen_optimizer()
        self.sess.run(tf.variables_initializer(self._optimizer.variables()))
        self.sess_backup=copy.copy(self.sess)
        #tf.train.Saver().save(self.sess,'tmp.ckpt')
        for u in range(0,self.num_test_users): 
            print('Evaluating user',u,':')
            self.sess=copy.copy(self.sess_backup)
            #tf.train.Saver().restore(self.sess,'tmp.ckpt') 
            #self.sess.run(tf.variables_initializer(self._optimizer.variables()))
            violated,mask,label=self.voilate(12,u)
            for i in range(0,self.adapt_itrs): #local adaption
                self.local_adapt_train(i,violated,mask,label,u)

I want to totally restore the session each time it enters the for loop. Just as what is commented out, I tried to use tf.train.Saver, but it can't totally restore: in the for loop, the model is trained several times using sess.run, and as time goes by, the running speed is slower and slower, which means that there must be redundant graphs stored in self.sess. So I tried to use copy.copy to copy the whole session as a backup to be restored later, but it reports that `Run with options is not supported for this session.` since the following steps use the feed_dict.
```

### Standalone code to reproduce the issue

```shell
Here's a meaning less program but it can clarify my problem:

import copy
import tensorflow.compat.v1 as tf
import numpy as np
tf.disable_v2_behavior()
sess=tf.Session()
_input=tf.placeholder(dtype=tf.float32, shape=[100, 20], name="input")
_output=tf.placeholder(dtype=tf.float32, shape=[100, 1], name="output")
W = tf.get_variable(name="W", initializer=tf.truncated_normal(shape=[20, 1],
                                         mean=0, stddev=0.03),dtype=tf.float32)
output=tf.matmul(_input,W)
loss=tf.reduce_sum(tf.square(_output-output))
_optimizer = tf.train.AdamOptimizer(0.01)
optimizer = _optimizer.minimize(loss, global_step=tf.Variable(0, trainable=False))
input_mat=np.random.rand(100,20)
output_mat=input_mat@np.random.rand(20,1)
init=tf.global_variables_initializer()
sess.run(init)
_,l=sess.run([optimizer,loss],feed_dict={_input:input_mat,_output:output_mat})
for i in range(5):
    '''
    Each time entering the loop, reset the session to the original one.
    Don't use tf.train.Saver, because it cannot totally restore the whole session since the running speed
    is still lower and lower.
    '''
    sess2=copy.copy(sess)
    _,l=sess2.run([optimizer,loss],feed_dict={_input:input_mat,_output:output_mat}) #Reports "Run with options is not supported for this session."
    sess2.close()
sess.close()
```

### Relevant log output

```shell
= RESTART: D:/programming/python/research_backup/AutoRec/Autorec_filmtrust_exp2/try.py
WARNING:tensorflow:From D:\Users\myhac\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\compat\v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Traceback (most recent call last):
  File "D:\Users\myhac\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\client\session.py", line 1377, in _do_call
    return fn(*args)
  File "D:\Users\myhac\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\client\session.py", line 1360, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "D:\Users\myhac\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\client\session.py", line 1453, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.UnimplementedError: Run with options is not supported for this session.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/programming/python/research_backup/AutoRec/Autorec_filmtrust_exp2/try.py", line 26, in <module>
    _,l=sess2.run([optimizer,loss],feed_dict={_input:input_mat,_output:output_mat}) #Reports "Run with options is not supported for this session."
  File "D:\Users\myhac\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\client\session.py", line 967, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "D:\Users\myhac\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\client\session.py", line 1190, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "D:\Users\myhac\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\client\session.py", line 1370, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "D:\Users\myhac\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\client\session.py", line 1396, in _do_call
    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
tensorflow.python.framework.errors_impl.UnimplementedError: Graph execution error:

Run with options is not supported for this session.
```
```

**Comment by DURGESH716** [comment]
In TensorFlow, you can use the `tf.Session.run()` method to run a session with options. To copy a session with options, you can use the `tf.Session.clone()` method. This method creates a new session with the same settings as the original session, including the session options. For example:
```
# Create original session
original_session = tf.Session(config=tf.ConfigProto(allow_soft_placement=True))

# Clone the session
cloned_session = original_session.clone()
```


You can then use the `cloned_session` object to run operations and evaluate tensors, just like you would with the original session.

Alternatively, you can also create a new session with the same options as the original session by passing the options to the `tf.Session()` constructor when creating the new session. For example:
```
# Create original session
original_session = tf.Session(config=tf.ConfigProto(allow_soft_placement=True))

# Create new session with same options as original session
cloned_session = tf.Session(config=original_session.config)

```

**Comment by Kobe972** [comment]
> 

It shows that sess has no attribute 'clone'. I replaced `sess2=copy.copy(sess)` with `sess2=sess.clone()`, and the error log is:
```
Traceback (most recent call last):
  File "D:\programming\python\research_backup\AutoRec\Autorec_filmtrust_exp2\try.py", line 25, in <module>
    sess2=sess.clone()
AttributeError: 'Session' object has no attribute 'clone'. Did you mean: 'close'?
```

**Comment by Kobe972** [comment]
> 

The code runs, however, unfortunately, something changes next time when entering the for loop, since sess2.run consumes more time. This is my overall code:
```python
import copy
import tensorflow.compat.v1 as tf
import numpy as np
from time import time
tf.disable_v2_behavior()
sess=tf.Session()
_input=tf.placeholder(dtype=tf.float32, shape=[10000, 20], name="input")
_output=tf.placeholder(dtype=tf.float32, shape=[10000, 1], name="output")
W = tf.get_variable(name="W", initializer=tf.truncated_normal(shape=[20, 1],
                                         mean=0, stddev=0.03),dtype=tf.float32)
output=tf.matmul(_input,W)
loss=tf.reduce_sum(tf.square(_output-output))
_optimizer = tf.train.AdamOptimizer(0.01)
optimizer = _optimizer.minimize(loss, global_step=tf.Variable(0, trainable=False))
input_mat=np.random.rand(10000,20)
output_mat=input_mat@np.random.rand(20,1)
init=tf.global_variables_initializer()
sess.run(init)
_,l=sess.run([optimizer,loss],feed_dict={_input:input_mat,_output:output_mat})
tf.train.Saver().save(sess,'./')
t=time()
for i in range(10000):
    if (i+1)%100==0:
        print(time()-t)
        t=time()
    sess2=tf.Session()
    tf.train.Saver().restore(sess2,'./')
    _,l=sess2.run([optimizer,loss],feed_dict={_input:input_mat,_output:output_mat}) #Reports "Run with options is not supported for this session."
    sess2.close()
sess.close()
```
The output is
```
3.409499168395996
6.0418853759765625
8.92863917350769
12.089853763580322
16.55520009994507
19.047667026519775
22.33715510368347
25.662793159484863
```

**Comment by DURGESH716** [comment]
The code is absolutely correct, if it's time consuming, you can train your model on Google Colab or using Kaggle Kernels.

As the performance on these platforms is absolutely fantastic and is free of cost.

**Comment by Kobe972** [comment]
> The code is absolutely correct, if it's time consuming, you can train your model on Google Colab or using Kaggle Kernels.
> 
> As the performance on these platforms is absolutely fantastic and is free of cost.

I think it has nothing to do with the training platform, since I have implemented it on multiple platforms, including my laboratory's server. The main problem is not that the program is time consuming. In fact, the speed is acceptable at first few iterations. But as time goes by, it becomes slower and slower. For the examplified program, I'm not aiming at reduce the costed time to something like 2 sec or 1 sec, instead, I want **all** printed time interval to be 3 seconds, just like the first one hundred  iterations.

**Comment by DURGESH716** [comment]
I got it !!! Please try this optimized code:
```
import copy
import tensorflow.compat.v1 as tf
import numpy as np
from time import time

tf.disable_v2_behavior()
sess=tf.Session()
_input=tf.placeholder(dtype=tf.float32, shape=[10000, 20], name="input")
_output=tf.placeholder(dtype=tf.float32, shape=[10000, 1], name="output")
W = tf.get_variable(name="W", initializer=tf.truncated_normal(shape=[20, 1],
                                         mean=0, stddev=0.03),dtype=tf.float32)
output=tf.matmul(_input,W)
loss=tf.nn.l2_loss(_output-output)
_optimizer = tf.train.AdamOptimizer(0.01)
optimizer = _optimizer.minimize(loss, global_step=tf.Variable(0, trainable=False))
input_mat=np.random.rand(10000,20)
output_mat=input_mat@np.random.rand(20,1)
init=tf.global_variables_initializer()
sess.run(init)
_,l=sess.run([optimizer,loss],feed_dict={_input:input_mat,_output:output_mat})

t=time()
for i in range(10000):
    _,l=sess.run([optimizer,loss],feed_dict={_input:input_mat,_output:output_mat})
    if (i+1)%1000==0:
        print(time()-t)
        t=time()

tf.train.Saver().save(sess,'./')
sess.close()

```

**Comment by tiruk007** [comment]
@Kobe972 
The Session was designed for TensorFlow v1. Session does not work with either eager execution or [tf.function](https://www.tensorflow.org/api_docs/python/tf/function), and you should not invoke it directly. To migrate code that uses sessions to TF2, rewrite the code without it. See the [migration guide](https://www.tensorflow.org/guide/migrate#1_replace_v1sessionrun_calls) on replacing Session.run calls and please refer to [Functions, not sessions](https://www.tensorflow.org/guide/migrate/tf1_vs_tf2#functions_not_sessions).

Thank you!

**Comment by Kobe972** [comment]
> I got it !!! Please try this optimized code:
> 
> ```
> import copy
> import tensorflow.compat.v1 as tf
> import numpy as np
> from time import time
> 
> tf.disable_v2_behavior()
> sess=tf.Session()
> _input=tf.placeholder(dtype=tf.float32, shape=[10000, 20], name="input")
> _output=tf.placeholder(dtype=tf.float32, shape=[10000, 1], name="output")
> W = tf.get_variable(name="W", initializer=tf.truncated_normal(shape=[20, 1],
>                                          mean=0, stddev=0.03),dtype=tf.float32)
> output=tf.matmul(_input,W)
> loss=tf.nn.l2_loss(_output-output)
> _optimizer = tf.train.AdamOptimizer(0.01)
> optimizer = _optimizer.minimize(loss, global_step=tf.Variable(0, trainable=False))
> input_mat=np.random.rand(10000,20)
> output_mat=input_mat@np.random.rand(20,1)
> init=tf.global_variables_initializer()
> sess.run(init)
> _,l=sess.run([optimizer,loss],feed_dict={_input:input_mat,_output:output_mat})
> 
> t=time()
> for i in range(10000):
>     _,l=sess.run([optimizer,loss],feed_dict={_input:input_mat,_output:output_mat})
>     if (i+1)%1000==0:
>         print(time()-t)
>         t=time()
> 
> tf.train.Saver().save(sess,'./')
> sess.close()
> ```

Your code is different from my original code, since I restore the model at each beginning of the for loop. The problem appears to has to do with the computation graph. So I use tf.reset_default_graph at the begining of the for loop and rebuild variables. It works out, but rebuilding all variables each time I want to restore the session is inconvinient. It seems that there's not a satisfying solution in tensorflow.compat.v1

**Comment by Kobe972** [comment]
> @Kobe972 The Session was designed for TensorFlow v1. Session does not work with either eager execution or [tf.function](https://www.tensorflow.org/api_docs/python/tf/function), and you should not invoke it directly. To migrate code that uses sessions to TF2, rewrite the code without it. See the [migration guide](https://www.tensorflow.org/guide/migrate#1_replace_v1sessionrun_calls) on replacing Session.run calls and please refer to [Functions, not sessions](https://www.tensorflow.org/guide/migrate/tf1_vs_tf2#functions_not_sessions).
> 
> Thank you!

Thanks! It looks sound. I'll try tf.2

**Comment by tiruk007** [comment]
@Kobe972 
Thanks for the reply !  
Please try in TF v2.x and let us know, Is the issue still persists.

Thank you!

**Comment by Kobe972** [comment]
> @Kobe972 Thanks for the reply ! As mentioned above [comment](https://github.com/tensorflow/tensorflow/issues/59265#issuecomment-1386430303). Could you please update the status once you tried on TF v2.x and let us know, Is the issue still persists.
> 
> Thank you!

I solved the problem using a more sophisicated method which I mentioned before. I will try it if I am available.

**Comment by tiruk007** [comment]
@Kobe972 
Could you please feel free to close the issue if it is resolved ?

Thank you!

**Comment by Kobe972** [comment]
> 

Yes. Thank you!
