### ISSUE TITLE
I have some problems I think it is connected with dataset that i make myself

### ISSUE THREAD

**Issue by naurner** [tensorflow/tensorflow#59262]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf 2

### Custom Code

Yes

### Current Behaviour?

```shell
I got an Error with model.fit
For your information, I will also add that the table used for the dataset 
consists of 2 columns, one of which contains the paths to the images on
 the disk, and the second one contains the labels for each image. 
 And I’m also new to github and therefore I don’t know how to make it so
 that you can run all the code because I don’t really want to share a huge
 folder with files, I can also clarify that the training arrays consist of 800 .png images
```

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/1VsjzbjAhZru1kdY7iElxQWrsIW9rMfGA?usp=sharing
```

### Relevant log output

```shell
UnimplementedError                        Traceback (most recent call last)
<ipython-input-27-c0002c3040bd> in <module>
----> 1 model.fit(x_train, y_train, epochs=10)

1 frames
/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     52   try:
     53     ctx.ensure_initialized()
---> 54     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     55                                         inputs, attrs, num_outputs)
     56   except core._NotOkStatusException as e:

UnimplementedError: Graph execution error:

Detected at node 'sparse_categorical_crossentropy/Cast' defined at (most recent call last):
    File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.8/dist-packages/ipykernel_launcher.py", line 16, in <module>
      app.launch_new_instance()
    File "/usr/local/lib/python3.8/dist-packages/traitlets/config/application.py", line 992, in launch_instance
      app.start()
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/kernelapp.py", line 612, in start
      self.io_loop.start()
    File "/usr/local/lib/python3.8/dist-packages/tornado/platform/asyncio.py", line 149, in start
      self.asyncio_loop.run_forever()
    File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
      self._run_once()
    File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
      handle._run()
    File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
      self._context.run(self._callback, *self._args)
    File "/usr/local/lib/python3.8/dist-packages/tornado/ioloop.py", line 690, in <lambda>
      lambda f: self._run_callback(functools.partial(callback, future))
    File "/usr/local/lib/python3.8/dist-packages/tornado/ioloop.py", line 743, in _run_callback
      ret = callback()
    File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 787, in inner
      self.run()
    File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 748, in run
      yielded = self.gen.send(value)
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/kernelbase.py", line 365, in process_one
      yield gen.maybe_future(dispatch(*args))
    File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 209, in wrapper
      yielded = next(result)
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/kernelbase.py", line 268, in dispatch_shell
      yield gen.maybe_future(handler(stream, idents, msg))
    File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 209, in wrapper
      yielded = next(result)
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/kernelbase.py", line 543, in execute_request
      self.do_execute(
    File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 209, in wrapper
      yielded = next(result)
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/ipkernel.py", line 306, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/zmqshell.py", line 536, in run_cell
      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 2854, in run_cell
      result = self._run_cell(
    File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 2881, in _run_cell
      return runner(coro)
    File "/usr/local/lib/python3.8/dist-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
      coro.send(None)
    File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 3057, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 3249, in run_ast_nodes
      if (await self.run_code(code, result,  async_=asy)):
    File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "<ipython-input-27-c0002c3040bd>", line 1, in <module>
      model.fit(x_train, y_train, epochs=10)
    File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1409, in fit
      tmp_logs = self.train_function(iterator)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1051, in train_function
      return step_function(self, iterator)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1040, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1030, in run_step
      outputs = model.train_step(data)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 890, in train_step
      loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 948, in compute_loss
      return self.compiled_loss(
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/compile_utils.py", line 201, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "/usr/local/lib/python3.8/dist-packages/keras/losses.py", line 139, in __call__
      losses = call_fn(y_true, y_pred)
    File "/usr/local/lib/python3.8/dist-packages/keras/losses.py", line 243, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/losses.py", line 1860, in sparse_categorical_crossentropy
      return backend.sparse_categorical_crossentropy(
    File "/usr/local/lib/python3.8/dist-packages/keras/backend.py", line 5223, in sparse_categorical_crossentropy
      target = cast(target, 'int64')
    File "/usr/local/lib/python3.8/dist-packages/keras/backend.py", line 2066, in cast
      return tf.cast(x, dtype)
Node: 'sparse_categorical_crossentropy/Cast'
Cast string to int64 is not supported
	 [[{{node sparse_categorical_crossentropy/Cast}}]] [Op:__inference_train_function_469]
```
</details>

**Comment by DURGESH716** [comment]
Here are a couple of things to check that might be causing the error:

1. Make sure that the paths to the images in your dataset are correct and that the images are present at those locations.

2. Ensure that the labels in your dataset are in the correct format and are compatible with the model you are using.

3. Verify that the image data has been preprocessed correctly. (e.g resize, normalize)

4. Make sure that the data is loaded in the correct format (e.g. numpy array, tensors)

5. If you are using a pre-trained model, make sure that the input shape and data format match the pre-trained model

6. It's also important to check if you have the correct version of Tensorflow or Keras.

**Comment by DURGESH716** [comment]
Also , as I can see that the data is not present in the given path on this colab link: https://colab.research.google.com/drive/1VsjzbjAhZru1kdY7iElxQWrsIW9rMfGA?usp=sharing

**Comment by naurner** [comment]
Yes, it's also because i don't used to use colab, before thus i used anaconda, all pathes lead to images on my drive, but now I understand, that i don't preprocessed my data, tomorrow i will try to do it, because today i already go sleep. And in adition i want to say thanks for your help and sorry for my English. My English is not so good, because it's not my first language.

**Comment by naurner** [comment]
Hello from all from Kyrgyzstan

**Comment by DURGESH716** [comment]
No problem @naurner, If your problem solves tomorrow you can close this issue, else you may seek help anytime.

**Comment by gaikwadrahul8** [comment]
Hi, @naurner 

I found articles which will help you to understand how to use customized image datasets for multi-class image classification problem please have look into these articles [article-1](https://www.analyticsvidhya.com/blog/2021/07/step-by-step-guide-for-image-classification-on-custom-datasets/), [article-2](https://www.geeksforgeeks.org/multiclass-image-classification-using-transfer-learning/) and if you're using any sample notebook as reference to solve your multi-class image classification problem, could you please share with us as Google colab notebook with some sample rows of your excel file which you're using as dataset so we'll try to replicate your issue from our end ? Thank you!

**Comment by naurner** [comment]
Oh, hello yes i will try it and share to you my notebooks, but not now, because now i am going to work and will be free only at evening

**Comment by gaikwadrahul8** [comment]
Hi, @naurner 

Sure, please take your time, no hurry at all whenever you get time please share Google Colab notebook with some sample rows of your excel file which you're using as dataset. Thank you!
