### ISSUE TITLE
Failed to build android demo

### ISSUE THREAD

**Issue by sobinzeng** [tensorflow/tensorflow#5935]
build android demo with "bazel build //tensorflow/examples/android:tensorflow_demo"

**Environment:**
OS: OSX 10.11.6  64bit
branch: master
python:2.7.10
AndroidSDK: 24 BuildToolsVersion: 24.0.1
NDK: 24

To build an android apk, i suppose cuda is not required, so there is following cuda error.
**ls -l /path/to/cuda/lib/libcud***
ls: /path/to/cuda/lib/libcud*: No such file or directory
**python -c "import tensorflow; print(tensorflow.__version__)"**
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "tensorflow/python/__init__.py", line 60, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
ImportError: cannot import name pywrap_tensorflow
**git rev-parse HEAD:** 5657d0dee8d87f4594b3e5902ed3e3ca8d6dfc0a
**bazel version:**
Build label: 0.4.0-homebrew
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Nov 2 19:15:37 2016 (1478114137)
Build timestamp: 1478114137
Build timestamp as int: 1478114137

-------------------------OUTPUT-------------------------

**ERROR:** /Volumes/ext/data/workspace/research/ai/tensorflow/tensorflow/examples/android/BUILD:53:1: Processing Android resources for //tensorflow/examples/android:tensorflow_demo failed: sandbox-exec failed: error executing command 
  (cd /private/var/tmp/_bazel_Yeeio/a35c6185f684e2289845701b593f9bd2/bazel-sandbox/7fdb6518-a872-4a3c-96e6-64bf6e8713e4-13/execroot/tensorflow && \
  exec env - \
  /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_Yeeio/a35c6185f684e2289845701b593f9bd2/bazel-sandbox/7fdb6518-a872-4a3c-96e6-64bf6e8713e4-13/sandbox.sb bazel-out/host/bin/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/AndroidResourceProcessingAction --buildToolsVersion 24.0.1 --aapt bazel-out/host/bin/external/androidsdk/aapt_binary --annotationJar external/androidsdk/tools/support/annotations.jar --androidJar external/androidsdk/platforms/android-24/android.jar --primaryData tensorflow/examples/android/res:external/inception5h:tensorflow/examples/android/AndroidManifest.xml --rOutput bazel-out/local-fastbuild/bin/tensorflow/examples/android/tensorflow_demo_symbols/R.txt --srcJarOutput bazel-out/local-fastbuild/bin/tensorflow/examples/android/tensorflow_demo.srcjar --proguardOutput bazel-out/local-fastbuild/bin/tensorflow/examples/android/proguard/tensorflow_demo/_tensorflow_demo_proguard.cfg --mainDexProguardOutput bazel-out/local-fastbuild/bin/tensorflow/examples/android/proguard/tensorflow_demo/main_dex_tensorflow_demo_proguard.cfg --manifestOutput bazel-out/local-fastbuild/bin/tensorflow/examples/android/tensorflow_demo_processed_manifest/AndroidManifest.xml --resourcesOutput bazel-out/local-fastbuild/bin/tensorflow/examples/android/tensorflow_demo_files/resource_files.zip --packagePath bazel-out/local-fastbuild/bin/tensorflow/examples/android/tensorflow_demo.ap_ --debug --packageForR org.tensorflow.demo).
十一月 29, 2016 8:29:03 下午 com.google.devtools.build.android.AndroidResourceProcessingAction main
严重: Error during merging resources
Error: tensorflow/examples/android/res/layout/activity_camera.xml: Operation not permitted
	at com.android.ide.common.res2.MergingException$Builder.build(MergingException.java:129)
	at com.google.devtools.build.android.AndroidResourceProcessor.mergeData(AndroidResourceProcessor.java:1141)
	at com.google.devtools.build.android.AndroidResourceProcessingAction.main(AndroidResourceProcessingAction.java:245)
Caused by: java.nio.file.FileSystemException: tensorflow/examples/android/res/layout/activity_camera.xml: Operation not permitted
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at com.google.devtools.build.android.DataValueFileWithIds.parse(DataValueFileWithIds.java:49)
	at com.google.devtools.build.android.ParsedAndroidData$ResourceFileVisitor.visitFile(ParsedAndroidData.java:306)
	at com.google.devtools.build.android.ParsedAndroidData$ResourceFileVisitor.visitFile(ParsedAndroidData.java:245)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at com.google.devtools.build.android.ParsedAndroidData$ParsedAndroidDataBuildingPathWalker.walkResources(ParsedAndroidData.java:204)
	at com.google.devtools.build.android.UnvalidatedAndroidDirectories.walk(UnvalidatedAndroidDirectories.java:80)
	at com.google.devtools.build.android.ParsedAndroidData.from(ParsedAndroidData.java:348)
	at com.google.devtools.build.android.AndroidResourceProcessor.mergeData(AndroidResourceProcessor.java:1137)
	... 1 more

Exception in thread "main" Error: tensorflow/examples/android/res/layout/activity_camera.xml: Operation not permitted
	at com.android.ide.common.res2.MergingException$Builder.build(MergingException.java:129)
	at com.google.devtools.build.android.AndroidResourceProcessor.mergeData(AndroidResourceProcessor.java:1141)
	at com.google.devtools.build.android.AndroidResourceProcessingAction.main(AndroidResourceProcessingAction.java:245)
Caused by: java.nio.file.FileSystemException: tensorflow/examples/android/res/layout/activity_camera.xml: Operation not permitted
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at com.google.devtools.build.android.DataValueFileWithIds.parse(DataValueFileWithIds.java:49)
	at com.google.devtools.build.android.ParsedAndroidData$ResourceFileVisitor.visitFile(ParsedAndroidData.java:306)
	at com.google.devtools.build.android.ParsedAndroidData$ResourceFileVisitor.visitFile(ParsedAndroidData.java:245)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at com.google.devtools.build.android.ParsedAndroidData$ParsedAndroidDataBuildingPathWalker.walkResources(ParsedAndroidData.java:204)
	at com.google.devtools.build.android.UnvalidatedAndroidDirectories.walk(UnvalidatedAndroidDirectories.java:80)
	at com.google.devtools.build.android.ParsedAndroidData.from(ParsedAndroidData.java:348)
	at com.google.devtools.build.android.AndroidResourceProcessor.mergeData(AndroidResourceProcessor.java:1137)
	... 1 more
Target //tensorflow/examples/android:tensorflow_demo failed to build

**Comment by poxvoculi** [comment]
Thanks for posting the failing command and what look like full stack traces.  Could you also provide the rest of the information requested by the new issue template, e.g. the platform you're running on, version, and any failure analysis you've done yourself.

**Comment by sobinzeng** [comment]
@poxvoculi thank you,  i added the additional information to the issue, looking forward for your help :)

**Comment by petewarden** [comment]
Any ideas on this @andrewharp? The relevant errors appear to be:
`
Error during merging resources
Error: tensorflow/examples/android/res/layout/activity_camera.xml: Operation not permitted
`

**Comment by andrewharp** [comment]
@sobinzeng Can you ensure that the file exists and is readable by the user bazel runs as?

**Comment by sobinzeng** [comment]
i'm sure the related files exist, and they have rw access.

**Comment by andrewharp** [comment]
You may have luck debugging your sandbox with --sandbox_debug: https://bazel.build/blog/2016/03/18/sandbox-easier-debug.html

Maybe take a look at tensorflow/examples/android/res/layout/activity_camera.xml there and see what the permissions are on the file?

**Comment by BulletShadow** [comment]
The permissions on the file as follow:

ls -la tensorflow/examples/android/res/layout/activity_camera.xml 
-rw-rw-rw-  1 Yeeio  staff  966 11 23 12:44 tensorflow/examples/android/res/layout/activity_camera.xml

**Comment by andrewharp** [comment]
@BulletShadow You are having the exact same issue as @sobinzeng?

**Comment by BulletShadow** [comment]
sorry， i didn't noticed i changed the account, both BulletShadow & sobinzeng are my accounts.

**Comment by andrewharp** [comment]
And you're listing the file as it is inside the sandbox (not in the repo)?

For odd build issues like this it tends to be fastest just to reclone the repo.

```
git clone --recurse-submodules https://github.com/tensorflow/tensorflow.git
cd tensorflow/
cat ~/WORKSPACE_ANDROID >> WORKSPACE 
bazel build //tensorflow/examples/android:tensorflow_demo
```

Where my WORKSPACE_ANDROID file contains the following (adjust for your system):
```
android_sdk_repository(
    name = "androidsdk",
    api_level = 23,
    build_tools_version = "23.0.1",
    # Replace with path to Android SDK on your system
    path = "/usr/local/google/home/andrewharp/android/sdk",
)

android_ndk_repository(
    name="androidndk",
    path="/usr/local/google/home/andrewharp/android/ndk",
    api_level=21)
```

**Comment by andrewharp** [comment]
Closing due to inactivity; please respond if the issue persists despite following the directions above.
