### ISSUE TITLE
Bad file descriptor when running tensorflow.python.keras.utils.data_utils._hash_file

### ISSUE THREAD

**Issue by dmc1778** [tensorflow/tensorflow#59361]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

2.10.0

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.9

### Current Behaviour?

```shell
Probably due to Nan or negative argument
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import os
import numpy as np
from tensorflow.python.keras.utils import data_utils
try:
  arg_0 = True
  arg_1 = "nan"
  arg_2 = -0.3344762570580887
  out = data_utils._hash_file(arg_0,arg_1,arg_2,)
except Exception as e:
  print("Error:"+str(e))
```
```


### Relevant log output

```shell
2023-01-21 13:28:52.803828: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-21 13:28:53.097843: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-01-21 13:28:53.923396: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/lib/
2023-01-21 13:28:53.923579: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/lib/
2023-01-21 13:28:53.923589: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "/media/nimashiri/SSD/testing_results/orion/tf-2.10.0/orion_bugs/tensorflow.python.keras.utils.data_utils._hash_file.py", line 9, in <module>
    out = data_utils._hash_file(arg_0,arg_1,arg_2,)
  File "/home/nimashiri/anaconda3/envs/tf-2.10/lib/python3.9/site-packages/tensorflow/python/keras/utils/data_utils.py", line 321, in _hash_file
    for chunk in iter(lambda: fpath_file.read(chunk_size), b''):
  File "/home/nimashiri/anaconda3/envs/tf-2.10/lib/python3.9/site-packages/tensorflow/python/keras/utils/data_utils.py", line 321, in <lambda>
    for chunk in iter(lambda: fpath_file.read(chunk_size), b''):
TypeError: argument should be integer or None, not 'float'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/nimashiri/SSD/testing_results/orion/tf-2.10.0/orion_bugs/tensorflow.python.keras.utils.data_utils._hash_file.py", line 11, in <module>
    print("Error:"+str(e))
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
OSError: [Errno 9] Bad file descriptor

```
```
</details>

**Comment by gaikwadrahul8** [comment]
Hi, @nimashiri 

Apologize for the delay and I was able to replicate the issue without any error, for your reference I have added [gist file ](https://colab.research.google.com/gist/gaikwadrahul8/693e212e68153b997a39028180da0488/test-hash-file.ipynb)and It seems like you're not passing expected arguments with expected datatypes as per the [function definition](https://github.com/keras-team/keras/blob/a39f10acf3eac5e6ef69d084616982a4d4ebd8bb/keras/utils/data_utils.py#L247) because of that reason you're getting this error `Bad file descriptor` 

I have also replicated on Ubuntu 22.04 with Tensorflow version==2.10 and it's working as expected if I'm passing correct arguments to the function and for your reference I have added screenshot below

![image](https://user-images.githubusercontent.com/115997457/215028064-80e1298e-b587-4e01-9afc-d96bb5dc2a94.png)

if issue still persists please let us know ? or Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!

**Comment by mihaimaruseac** [comment]
Not a vuln
