### ISSUE TITLE
Model saving with optimizer throws attribute error

### ISSUE THREAD

**Issue by phrasenmaeher** [tensorflow/tensorflow#59428]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

tf 2.11

### Custom Code

No

### OS Platform and Distribution

macOS Monterey

### Python version

3.10.8

### Current Behaviour?

```shell
When saving a model after it has been compiled with an optimizer (e.g., `SGD`),
an attribute error is thrown.
This is alleviated by setting `include_optimizer=False` when saving.
By default this switch is set to `True`.
```

### Standalone code to reproduce the issue

```python
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential(
    [
        keras.Input(shape=(28, 28, 1)),
        layers.Conv2D(32, kernel_size=(3, 3), activation="relu"),
        layers.MaxPooling2D(pool_size=(2, 2)),
        layers.Conv2D(64, kernel_size=(3, 3), activation="relu"),
        layers.MaxPooling2D(pool_size=(2, 2)),
        layers.Flatten(),
        layers.Dropout(0.5),
        layers.Dense(10, activation="softmax"),
    ]
)

model.save("test") #runs fine

optimizer = tf.keras.optimizers.SGD(),
model.compile(optimizer, loss=tf.keras.losses.SparseCategoricalCrossentropy())

model.save("test") #throws error
```

### Relevant log output

```python
AttributeError                            Traceback (most recent call last)
Cell In[22], line 1
----> 1 model.save("test")

File ~/miniforge3/envs/a/lib/python3.10/site-packages/keras/utils/traceback_utils.py:70, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     67     filtered_tb = _process_traceback_frames(e.__traceback__)
     68     # To get the full stack trace, call:
     69     # `tf.debugging.disable_traceback_filtering()`
---> 70     raise e.with_traceback(filtered_tb) from None
     71 finally:
     72     del filtered_tb

File ~/miniforge3/envs/a/lib/python3.10/site-packages/keras/saving/legacy/saving_utils.py:211, in model_metadata(model, include_optimizer, require_config)
    198             raise NotImplementedError(
    199                 "Optimizers loaded from a SavedModel cannot be saved. "
    200                 "If you are calling `model.save` or "
   (...)
    204                 "delete the optimizer from the model."
    205             )
    206         else:
    207             optimizer_config = {
    208                 "class_name": keras.utils.get_registered_name(
    209                     model.optimizer.__class__
    210                 ),
--> 211                 "config": model.optimizer.get_config(),
    212             }
    213         metadata["training_config"]["optimizer_config"] = optimizer_config
    214 return metadata

AttributeError: 'tuple' object has no attribute 'get_config'
```
</details>

**Comment by synandi** [comment]
Hi @phrasenmaeher , a workaround is to pass  the optimizer as a string in the compile method  like below
```
model.compile('sgd', loss=tf.keras.losses.SparseCategoricalCrossentropy())
```
Please find the gist [here](https://colab.sandbox.google.com/gist/synandi/b1a5c92bdccf3882c0d66d18a53bb532/59428.ipynb). Thank you!

**Comment by phrasenmaeher** [comment]
The workaround you proposed does indeed alleviate the problem.
However, it lacks the possibility to pass custom parameters to the optimizer.

Further, the model training does not seem to work when passing the optimizer object (Again, it works fine when passing the optimiser's name).

See code below.

```python
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np

model = keras.Sequential(
    [
        keras.Input(shape=(28, 28, 1)),
        layers.Conv2D(32, kernel_size=(3, 3), activation="relu"),
        layers.MaxPooling2D(pool_size=(2, 2)),
        layers.Conv2D(64, kernel_size=(3, 3), activation="relu"),
        layers.MaxPooling2D(pool_size=(2, 2)),
        layers.Flatten(),
        layers.Dropout(0.5),
        layers.Dense(10, activation="softmax"),
    ]
)

x = np.random.random((128,28,28,1))
y = np.random.random((128, 10))

optimizer = tf.keras.optimizers.SGD(),
model.compile(optimizer, loss=tf.keras.losses.CategoricalCrossentropy())

model.fit(x=x, y=y, batch_size=32) #training fails

#Alternative way:
model.compile('sgd', loss=tf.keras.losses.CategoricalCrossentropy())
model.fit(x=x, y=y, batch_size=32) #training works
```

See below stack trace for the error message:

```python
AttributeError                            Traceback (most recent call last)
Cell In[47], line 1
----> 1 model.fit(x=x, y=y, batch_size=32)

File ~/miniforge3/envs/a/lib/python3.10/site-packages/keras/utils/traceback_utils.py:70, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     67     filtered_tb = _process_traceback_frames(e.__traceback__)
     68     # To get the full stack trace, call:
     69     # `tf.debugging.disable_traceback_filtering()`
---> 70     raise e.with_traceback(filtered_tb) from None
     71 finally:
     72     del filtered_tb

File /var/folders/ys/tyxvjkxn6ljcy0g2vkm65hp80000gn/T/__autograph_generated_file2dg_d4gj.py:15, in outer_factory.<locals>.inner_factory.<locals>.tf__train_function(iterator)
     13 try:
     14     do_return = True
---> 15     retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
     16 except:
     17     do_return = False

AttributeError: in user code:

    File "/Users/pascal/miniforge3/envs/a/lib/python3.10/site-packages/keras/engine/training.py", line 1249, in train_function  *
        return step_function(self, iterator)
    File "/Users/pascal/miniforge3/envs/a/lib/python3.10/site-packages/keras/engine/training.py", line 1233, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/Users/pascal/miniforge3/envs/a/lib/python3.10/site-packages/keras/engine/training.py", line 1222, in run_step  **
        outputs = model.train_step(data)
    File "/Users/pascal/miniforge3/envs/a/lib/python3.10/site-packages/keras/engine/training.py", line 1027, in train_step
        self.optimizer.minimize(loss, self.trainable_variables, tape=tape)

    AttributeError: 'tuple' object has no attribute 'minimize'
```

**Comment by sushreebarsa** [comment]
@phrasenmaeher I was able to replicate this issue, please find the [gist](https://colab.research.google.com/gist/sushreebarsa/8f1f927a33881200e45d2b767900d6cf/59428.ipynb) here.
It is more related to Keras as we are getting the error for model saving here that is throwing attribute error.
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues) as Keras development is fully moving to [github.com/keras-team/keras](http://github.com/keras-team/keras). All issues and PRs related to keras will be addressed in that repo.
To know more see this TF forum discussion ; 
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!

**Comment by sushreebarsa** [comment]
Closing as a stale. Please feel free to reopen if you still have any concern.
Thank you!
