### ISSUE TITLE
Segfault when running tf.math.unsorted_segment_sqrt_n

### ISSUE THREAD

**Issue by dmc1778** [tensorflow/tensorflow#59445]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

binary

### Tensorflow Version

2.10.0

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.9

### Current Behaviour?

```shell
A bug happened!
```

### Standalone code to reproduce the issue

```shell
https://drive.google.com/drive/folders/1T5VPLUmmxfkNzgNEb768xiMTDpKp-s2o?usp=share_link
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@dmc1778 I tried to replicate the issue on colab where the code is crashing with TF v2.11.
Please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/f88ebc06af584cf33e98e8084495fbcc/59445.ipynb) and check the error log as below which is due to memory allocation that is intended.

Timestamp | Level | Message
-- | -- | --
Feb 3, 2023, 2:59:47 PM | WARNING | WARNING:root:kernel d8417cd3-cc20-4482-a0a1-0deb3d2cdc37 restarted
Feb 3, 2023, 2:59:47 PM | INFO | KernelRestarter: restarting kernel (1/5), keep random ports
Feb 3, 2023, 2:59:42 PM | WARNING | tcmalloc: large alloc 6803537920 bytes == 0x19e456000 @ 0x7ffa028ff680 0x7ffa02920824 0x7ffa02920b8a 0x7ff9b596b84c 0x7ff9b653b53b 0x7ff9b65dabfd 0x7ff9b63f6e1a 0x7ff9b63f7a0c 0x7ff9b63f7c15 0x7ff9b63f9f23 0x7ff9c08c4af5 0x7ff9b6797719 0x7ff9b66c3feb 0x7ff9b668c86a 0x7ff9b669c8fd 0x7ff9b66a2ac9 0x7ff9bc71b202 0x7ff9bc6debb5 0x7ff9bc6df773 0x7ff9c3f4208c 0x7ff9bc6d8e41 0x7ff9bc6da292 0x7ff9bc6c361a 0x7ff9bc7259d4 0x7ff9bc399717 0x7ff9bbf4bd33 0x7ff9b4798d55 0x7ff9b47c3858 0x5f5b39 0x5f6706 0x571143
Feb 3, 2023, 2:59:42 PM | WARNING | 2023-02-03 09:29:42.521818: W tensorflow/tsl/framework/cpu_allocator_impl.cc:82] Allocation of 6803535392 exceeds 10% of free system memory.
Feb 3, 2023, 2:59:39 PM | WARNING | tcmalloc: large alloc 3401768960 bytes == 0x19e456000 @ 0x7ffa028ff680 0x7ffa0291fff4 0x7ff9bde9aa14 0x7ff9b6797719 0x7ff9b66c3feb 0x7ff9b668c86a 0x7ff9b669c8fd 0x7ff9b66a2ac9 0x7ff9bc71b202 0x7ff9bc6debb5 0x7ff9bc6df773 0x7ff9c3f4208c 0x7ff9bc6d8e41 0x7ff9bc6da292 0x7ff9bc6c361a 0x7ff9bc7259d4 0x7ff9bc399717 0x7ff9bbf4bd33 0x7ff9b4798d55 0x7ff9b47c3858 0x5f5b39 0x5f6706 0x571143 0x569d8a 0x5f60c3 0x570b82 0x5f5ee6 0x56bab6 0x569d8a 0x5f60c3 0x5f52b2
Feb 3, 2023, 2:59:32 PM | WARNING | tcmalloc: large alloc 6803537920 bytes == 0x8364000 @ 0x7ffa028ff680 0x7ffa02920824 0x7ffa02920b8a 0x7ff9b596b84c 0x7ff9b653b53b 0x7ff9b65dabfd 0x7ff9b63f6e1a 0x7ff9b63f7a0c 0x7ff9b63f7c15 0x7ff9bde9a792 0x7ff9b6797719 0x7ff9b66c3feb 0x7ff9b668c86a 0x7ff9b669c8fd 0x7ff9b66a2ac9 0x7ff9bc71b202 0x7ff9bc6debb5 0x7ff9bc6df773 0x7ff9c3f4208c 0x7ff9bc6d8e41 0x7ff9bc6da292 0x7ff9bc6c361a 0x7ff9bc7259d4 0x7ff9bc399717 0x7ff9bbf4bd33 0x7ff9b4798d55 0x7ff9b47c3858 0x5f5b39 0x5f6706 0x571143 0x569d8a
Feb 3, 2023, 2:59:32 PM | WARNING | 2023-02-03 09:29:32.818096: W tensorflow/tsl/framework/cpu_allocator_impl.cc:82] Allocation of 6803535392 exceeds 10% of free system memory.
Feb 3, 2023, 2:59:32 PM | WARNING | 2023-02-03 09:29:32.725227: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:267] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
Feb 3, 2023, 2:59:27 PM | WARNING | 2023-02-03 09:29:27.188678: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Feb 3, 2023, 2:59:27 PM | WARNING | 2023-02-03 09:29:27.188654: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/loc

**Comment by mihaimaruseac** [comment]
This is a vulnerability that needs fixing.

@sushreebarsa  Given that this is a vulnerability, don't be too eager to close it (by adding the label).

@dmc1778 please stop posting vulns on GitHub. Please consult SECURITY.md for how to properly and ethically disclose them.

**Comment by SuryanarayanaY** [comment]
@dmc1778 ,
I tried to replicate the issue with tf2.10v and `got OOM error` due to high input size argument.Ran the code multiple times and got the same error `but not segfault`.

`OOM when allocating tensor with shape[850441924,11,3] and type double on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:UnsortedSegmentSum]`

```
(tf2.10) suryanarayanay@surya-ubuntu-22-04:~$ python 59445.py
2023-02-06 16:11:50.859782: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-06 16:11:50.982170: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-02-06 16:11:51.022300: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-02-06 16:11:51.590695: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/suryanarayanay/miniconda3/envs/tf2.10/lib/
2023-02-06 16:11:51.590824: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/suryanarayanay/miniconda3/envs/tf2.10/lib/
2023-02-06 16:11:51.590845: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2.10.0
2023-02-06 16:11:56.423337: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-06 16:11:57.707714: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 38239 MB memory:  -> device: 0, name: NVIDIA A100-SXM4-40GB, pci bus id: 0000:00:04.0, compute capability: 8.0
2023-02-06 16:11:57.709280: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 38239 MB memory:  -> device: 1, name: NVIDIA A100-SXM4-40GB, pci bus id: 0000:00:05.0, compute capability: 8.0
2023-02-06 16:12:08.436121: W tensorflow/core/common_runtime/bfc_allocator.cc:479] Allocator (GPU_0_bfc) ran out of memory trying to allocate 209.10GiB (rounded to 224516668160)requested by op UnsortedSegmentSum
If the cause is memory fragmentation maybe the environment variable 'TF_GPU_ALLOCATOR=cuda_malloc_async' will improve the situation. 
Current allocation summary follows.
Current allocation summary follows.
2023-02-06 16:12:08.436165: I tensorflow/core/common_runtime/bfc_allocator.cc:1033] BFCAllocator dump for GPU_0_bfc
2023-02-06 16:12:08.436175: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (256):  Total Chunks: 3, Chunks in use: 2. 768B allocated for chunks. 512B in use in bin. 12B client-requested in use in bin.
2023-02-06 16:12:08.436182: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (512):  Total Chunks: 1, Chunks in use: 1. 512B allocated for chunks. 512B in use in bin. 264B client-requested in use in bin.
2023-02-06 16:12:08.436195: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (1024):    Total Chunks: 1, Chunks in use: 1. 1.2KiB allocated for chunks. 1.2KiB in use in bin. 1.0KiB client-requested in use in bin.
2023-02-06 16:12:08.436206: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (2048):    Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2023-02-06 16:12:08.436213: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (4096):    Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2023-02-06 16:12:08.436228: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (8192):    Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2023-02-06 16:12:08.436235: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (16384):   Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2023-02-06 16:12:08.436241: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (32768):   Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2023-02-06 16:12:08.436247: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (65536):   Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2023-02-06 16:12:08.436253: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (131072):  Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2023-02-06 16:12:08.436260: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (262144):  Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2023-02-06 16:12:08.436269: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (524288):  Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2023-02-06 16:12:08.436275: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (1048576): Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2023-02-06 16:12:08.436284: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (2097152): Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2023-02-06 16:12:08.436291: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (4194304): Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2023-02-06 16:12:08.436300: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (8388608): Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2023-02-06 16:12:08.436307: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (16777216): Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2023-02-06 16:12:08.436316: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (33554432): Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2023-02-06 16:12:08.436323: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (67108864): Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2023-02-06 16:12:08.436332: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (134217728):        Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2023-02-06 16:12:08.436343: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (268435456):        Total Chunks: 3, Chunks in use: 1. 37.34GiB allocated for chunks. 6.34GiB in use in bin. 6.34GiB client-requested in use in bin.
2023-02-06 16:12:08.436354: I tensorflow/core/common_runtime/bfc_allocator.cc:1056] Bin for 209.10GiB was 256.00MiB, Chunk State: 
2023-02-06 16:12:08.436372: I tensorflow/core/common_runtime/bfc_allocator.cc:1062]   Size: 6.34GiB | Requested Size: 6.34GiB | in_use: 0 | bin_num: 20, prev:   Size: 256B | Requested Size: 4B | in_use: 1 | bin_num: -1, next:   Size: 6.34GiB | Requested Size: 6.34GiB | in_use: 1 | bin_num: -1
2023-02-06 16:12:08.436389: I tensorflow/core/common_runtime/bfc_allocator.cc:1062]   Size: 24.67GiB | Requested Size: 0B | in_use: 0 | bin_num: 20, prev:   Size: 6.34GiB | Requested Size: 6.34GiB | in_use: 1 | bin_num: -1
2023-02-06 16:12:08.436394: I tensorflow/core/common_runtime/bfc_allocator.cc:1069] Next region of size 40096497664
2023-02-06 16:12:08.436423: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f3b7e000000 of size 512 next 1
2023-02-06 16:12:08.436436: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f3b7e000200 of size 1280 next 2
2023-02-06 16:12:08.436442: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f3b7e000700 of size 256 next 3
2023-02-06 16:12:08.436450: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] Free  at 7f3b7e000800 of size 256 next 4
2023-02-06 16:12:08.436458: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f3b7e000900 of size 256 next 5
2023-02-06 16:12:08.436466: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] Free  at 7f3b7e000a00 of size 6803535616 next 6
2023-02-06 16:12:08.436474: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] InUse at 7f3d1385c100 of size 6803535616 next 7
2023-02-06 16:12:08.436482: I tensorflow/core/common_runtime/bfc_allocator.cc:1089] Free  at 7f3ea90b7800 of size 26489423872 next 18446744073709551615
2023-02-06 16:12:08.436490: I tensorflow/core/common_runtime/bfc_allocator.cc:1094]      Summary of in-use Chunks by size: 
2023-02-06 16:12:08.436500: I tensorflow/core/common_runtime/bfc_allocator.cc:1097] 2 Chunks of size 256 totalling 512B
2023-02-06 16:12:08.436508: I tensorflow/core/common_runtime/bfc_allocator.cc:1097] 1 Chunks of size 512 totalling 512B
2023-02-06 16:12:08.436517: I tensorflow/core/common_runtime/bfc_allocator.cc:1097] 1 Chunks of size 1280 totalling 1.2KiB
2023-02-06 16:12:08.436525: I tensorflow/core/common_runtime/bfc_allocator.cc:1097] 1 Chunks of size 6803535616 totalling 6.34GiB
2023-02-06 16:12:08.436533: I tensorflow/core/common_runtime/bfc_allocator.cc:1101] Sum Total of in-use chunks: 6.34GiB
2023-02-06 16:12:08.436541: I tensorflow/core/common_runtime/bfc_allocator.cc:1103] total_region_allocated_bytes_: 40096497664 memory_limit_: 40096497664 available bytes: 0 curr_region_allocation_bytes_: 80192995328
2023-02-06 16:12:08.436571: I tensorflow/core/common_runtime/bfc_allocator.cc:1109] Stats: 
Limit:                     40096497664
InUse:                      6803537920
MaxInUse:                  13607073792
NumAllocs:                           7
MaxAllocSize:               6803535616
Reserved:                            0
PeakReserved:                        0
LargestFreeBlock:                    0

2023-02-06 16:12:08.436592: W tensorflow/core/common_runtime/bfc_allocator.cc:491] *_______________******************__________________________________________________________________
2023-02-06 16:12:08.436715: W tensorflow/core/framework/op_kernel.cc:1780] OP_REQUIRES failed at segment_reduction_ops_impl.h:498 : RESOURCE_EXHAUSTED: OOM when allocating tensor with shape[850441924,11,3] and type double on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "/home/suryanarayanay/59445.py", line 15, in <module>
    tensorflow.math.unsorted_segment_sqrt_n(**data)
  File "/home/suryanarayanay/miniconda3/envs/tf2.10/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/suryanarayanay/miniconda3/envs/tf2.10/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 7209, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.ResourceExhaustedError: {{function_node __wrapped__UnsortedSegmentSum_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[850441924,11,3] and type double on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:UnsortedSegmentSum]
(tf2.10) suryanarayanay@surya-ubuntu-22-04:~$ 
```
Tested the code with tf-nightly(2.12.0-dev20230201) and got same OOM error in multiple runs.Please refer to attached log.

```
(tf) suryanarayanay@surya-ubuntu-22-04:~$ python 59445.py
2023-02-06 16:19:20.706179: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-02-06 16:19:20.748331: E tensorflow/tsl/lib/monitoring/collection_registry.cc:81] Cannot register 2 metrics with the same name: /tensorflow/core/bfc_allocator_delay
2023-02-06 16:19:20.763808: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-06 16:19:21.464718: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2.12.0-dev20230201
2023-02-06 16:19:27.976909: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1635] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 38201 MB memory:  -> device: 0, name: NVIDIA A100-SXM4-40GB, pci bus id: 0000:00:04.0, compute capability: 8.0
2023-02-06 16:19:27.978495: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1635] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 38201 MB memory:  -> device: 1, name: NVIDIA A100-SXM4-40GB, pci bus id: 0000:00:05.0, compute capability: 8.0
2023-02-06 16:19:38.704583: W tensorflow/tsl/framework/bfc_allocator.cc:485] Allocator (GPU_0_bfc) ran out of memory trying to allocate 209.10GiB (rounded to 224516668160)requested by op UnsortedSegmentSum
If the cause is memory fragmentation maybe the environment variable 'TF_GPU_ALLOCATOR=cuda_malloc_async' will improve the situation. 
Current allocation summary follows.
Current allocation summary follows.
2023-02-06 16:19:38.704648: I tensorflow/tsl/framework/bfc_allocator.cc:1039] BFCAllocator dump for GPU_0_bfc
2023-02-06 16:19:38.704657: I tensorflow/tsl/framework/bfc_allocator.cc:1046] Bin (256):        Total Chunks: 3, Chunks in use: 2. 768B allocated for chunks. 512B in use in bin. 12B client-requested in use in bin.
2023-02-06 16:19:38.704665: I tensorflow/tsl/framework/bfc_allocator.cc:1046] Bin (512):        Total Chunks: 1, Chunks in use: 1. 512B allocated for chunks. 512B in use in bin. 264B client-requested in use in bin.
2023-02-06 16:19:38.704678: I tensorflow/tsl/framework/bfc_allocator.cc:1046] Bin (1024):       Total Chunks: 1, Chunks in use: 1. 1.2KiB allocated for chunks. 1.2KiB in use in bin. 1.0KiB client-requested in use in bin.
2023-02-06 16:19:38.704686: I tensorflow/tsl/framework/bfc_allocator.cc:1046] Bin (2048):       Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2023-02-06 16:19:38.704695: I tensorflow/tsl/framework/bfc_allocator.cc:1046] Bin (4096):       Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2023-02-06 16:19:38.704702: I tensorflow/tsl/framework/bfc_allocator.cc:1046] Bin (8192):       Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2023-02-06 16:19:38.704714: I tensorflow/tsl/framework/bfc_allocator.cc:1046] Bin (16384):      Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2023-02-06 16:19:38.704728: I tensorflow/tsl/framework/bfc_allocator.cc:1046] Bin (32768):      Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2023-02-06 16:19:38.704737: I tensorflow/tsl/framework/bfc_allocator.cc:1046] Bin (65536):      Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2023-02-06 16:19:38.704746: I tensorflow/tsl/framework/bfc_allocator.cc:1046] Bin (131072):     Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2023-02-06 16:19:38.704753: I tensorflow/tsl/framework/bfc_allocator.cc:1046] Bin (262144):     Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2023-02-06 16:19:38.704760: I tensorflow/tsl/framework/bfc_allocator.cc:1046] Bin (524288):     Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2023-02-06 16:19:38.704767: I tensorflow/tsl/framework/bfc_allocator.cc:1046] Bin (1048576):    Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2023-02-06 16:19:38.704776: I tensorflow/tsl/framework/bfc_allocator.cc:1046] Bin (2097152):    Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2023-02-06 16:19:38.704785: I tensorflow/tsl/framework/bfc_allocator.cc:1046] Bin (4194304):    Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2023-02-06 16:19:38.704794: I tensorflow/tsl/framework/bfc_allocator.cc:1046] Bin (8388608):    Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2023-02-06 16:19:38.704803: I tensorflow/tsl/framework/bfc_allocator.cc:1046] Bin (16777216):   Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2023-02-06 16:19:38.704813: I tensorflow/tsl/framework/bfc_allocator.cc:1046] Bin (33554432):   Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2023-02-06 16:19:38.704822: I tensorflow/tsl/framework/bfc_allocator.cc:1046] Bin (67108864):   Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2023-02-06 16:19:38.704832: I tensorflow/tsl/framework/bfc_allocator.cc:1046] Bin (134217728):  Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2023-02-06 16:19:38.704842: I tensorflow/tsl/framework/bfc_allocator.cc:1046] Bin (268435456):  Total Chunks: 3, Chunks in use: 1. 37.30GiB allocated for chunks. 6.34GiB in use in bin. 6.34GiB client-requested in use in bin.
2023-02-06 16:19:38.704856: I tensorflow/tsl/framework/bfc_allocator.cc:1062] Bin for 209.10GiB was 256.00MiB, Chunk State: 
2023-02-06 16:19:38.704960: I tensorflow/tsl/framework/bfc_allocator.cc:1068]   Size: 6.34GiB | Requested Size: 6.34GiB | in_use: 0 | bin_num: 20, prev:   Size: 256B | Requested Size: 4B | in_use: 1 | bin_num: -1, next:   Size: 6.34GiB | Requested Size: 6.34GiB | in_use: 1 | bin_num: -1
2023-02-06 16:19:38.704974: I tensorflow/tsl/framework/bfc_allocator.cc:1068]   Size: 24.63GiB | Requested Size: 0B | in_use: 0 | bin_num: 20, prev:   Size: 6.34GiB | Requested Size: 6.34GiB | in_use: 1 | bin_num: -1
2023-02-06 16:19:38.704980: I tensorflow/tsl/framework/bfc_allocator.cc:1075] Next region of size 40056651776
2023-02-06 16:19:38.704990: I tensorflow/tsl/framework/bfc_allocator.cc:1095] InUse at 7f32ac000000 of size 512 next 1
2023-02-06 16:19:38.704999: I tensorflow/tsl/framework/bfc_allocator.cc:1095] InUse at 7f32ac000200 of size 1280 next 2
2023-02-06 16:19:38.705007: I tensorflow/tsl/framework/bfc_allocator.cc:1095] InUse at 7f32ac000700 of size 256 next 3
2023-02-06 16:19:38.705014: I tensorflow/tsl/framework/bfc_allocator.cc:1095] Free  at 7f32ac000800 of size 256 next 4
2023-02-06 16:19:38.705023: I tensorflow/tsl/framework/bfc_allocator.cc:1095] InUse at 7f32ac000900 of size 256 next 5
2023-02-06 16:19:38.705031: I tensorflow/tsl/framework/bfc_allocator.cc:1095] Free  at 7f32ac000a00 of size 6803535616 next 6
2023-02-06 16:19:38.705039: I tensorflow/tsl/framework/bfc_allocator.cc:1095] InUse at 7f344185c100 of size 6803535616 next 7
2023-02-06 16:19:38.705047: I tensorflow/tsl/framework/bfc_allocator.cc:1095] Free  at 7f35d70b7800 of size 26449577984 next 18446744073709551615
2023-02-06 16:19:38.705055: I tensorflow/tsl/framework/bfc_allocator.cc:1100]      Summary of in-use Chunks by size: 
2023-02-06 16:19:38.705067: I tensorflow/tsl/framework/bfc_allocator.cc:1103] 2 Chunks of size 256 totalling 512B
2023-02-06 16:19:38.705077: I tensorflow/tsl/framework/bfc_allocator.cc:1103] 1 Chunks of size 512 totalling 512B
2023-02-06 16:19:38.705086: I tensorflow/tsl/framework/bfc_allocator.cc:1103] 1 Chunks of size 1280 totalling 1.2KiB
2023-02-06 16:19:38.705095: I tensorflow/tsl/framework/bfc_allocator.cc:1103] 1 Chunks of size 6803535616 totalling 6.34GiB
2023-02-06 16:19:38.705104: I tensorflow/tsl/framework/bfc_allocator.cc:1107] Sum Total of in-use chunks: 6.34GiB
2023-02-06 16:19:38.705112: I tensorflow/tsl/framework/bfc_allocator.cc:1109] Total bytes in pool: 40056651776 memory_limit_: 40056651776 available bytes: 0 curr_region_allocation_bytes_: 80113303552
2023-02-06 16:19:38.705147: I tensorflow/tsl/framework/bfc_allocator.cc:1114] Stats: 
Limit:                     40056651776
InUse:                      6803537920
MaxInUse:                  13607073792
NumAllocs:                           7
MaxAllocSize:               6803535616
Reserved:                            0
PeakReserved:                        0
LargestFreeBlock:                    0

2023-02-06 16:19:38.705179: W tensorflow/tsl/framework/bfc_allocator.cc:497] *_______________******************__________________________________________________________________
2023-02-06 16:19:38.705352: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at segment_reduction_ops_impl.h:492 : RESOURCE_EXHAUSTED: OOM when allocating tensor with shape[850441924,11,3] and type double on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "/home/suryanarayanay/59445.py", line 15, in <module>
    tensorflow.math.unsorted_segment_sqrt_n(**data)
  File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 7262, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.ResourceExhaustedError: {{function_node __wrapped__UnsortedSegmentSum_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[850441924,11,3] and type double on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:UnsortedSegmentSum]
(tf) suryanarayanay@surya-ubuntu-22-04:~$ 
```

**Comment by mihaimaruseac** [comment]
In this case, we can close this. Please reopen if segfault can occur without reaching OOM
