### ISSUE TITLE
RuntimeError: merge_call called while defining a new graph or a tf.function.

### ISSUE THREAD

**Issue by innat** [tensorflow/tensorflow#59487]
**System information**.
- Have I written custom code: Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- TensorFlow version (use command below): 2.6, 2.9

---

## Describe the problem

I have code that works fine but gives the following error if I use `with strategy.scope()`.

>  RuntimeError: `merge_call` called while defining a new graph or a tf.function. This can often happen if the function `fn` passed to `strategy.run()` contains a nested `@tf.function`, and the nested `@tf.function` contains a synchronization point, such as aggregating gradients (e.g, optimizer.apply_gradients), or if the function `fn` uses a control flow statement which contains a synchronization point in the body. Such behaviors are not yet supported. Instead, please avoid nested `tf.function`s or control flow statements that may potentially cross a synchronization boundary, for example, wrap the `fn` passed to `strategy.run` or the entire `strategy.run` inside a `tf.function` or move the control flow out of `fn`

## Describe the expected behavior

I think, It should work.

- Do you want to contribute a PR? (yes/no): No.
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions

## Standalone code to reproduce the issue

The code is for gradient accumulation techniques. Here it is done by overriding the `trian_step` with `fit` method.  This code works fine (as said above) without `with strategy.scope()`. Now, I like to use it for multi-gpu cases, and so I use strategy scope but ened up the the above mentioned error.

[Gist.](https://colab.research.google.com/drive/1yTu-qM4zTxtzNE7Ki6FvSyD9ijhvHdnw?usp=sharing)
## Follow-up Questions

1. In the above gist, for multi-gpu training, do I need to adjust anythong for `BATCH_SIZE = 32 * strategy.num_replicas_in_sync` inside the `train_step` method? Or it will be handled auto?
2. In the above gist, I use mixed precisoin technique, and so I also wrap ([as described](https://www.tensorflow.org/api_docs/python/tf/keras/mixed_precision/LossScaleOptimizer)) optimizer with `LossScaleOptimizer` and use `optimizer.get_scaled_loss(loss)` and `optimizer.get_unscaled_gradients(gradients)`. 
But the [official documentation](https://www.tensorflow.org/api_docs/python/tf/keras/mixed_precision/LossScaleOptimizer) talks about normal `fit` and custom loop training cases. In case of custom loop, it's suggested to wrap the optimizer and scale the loss and gradient but what about the combination of `fit` and custom loop (overriding `train_step`)? Does it sill need to wrap the optimizer and scale the loss and gradient or it will be handled by the API?

---

Others: https://github.com/keras-team/keras/issues/16633 cc @chenmoneygithub @nikitamaia @bhack

**Comment by innat** [comment]
From keras team cc. @ianstenbit

> This seems like a constraint of tf.distribute that we can't work around fully in the Keras train_step, so from the Keras POV I think there's nothing to be done

cc. @rchao
 > this appears not supported by tf.distribute at this time, and I would recommend filing an issue on tf.distribute if you would like such support.

**Comment by gaikwadrahul8** [comment]
Hi, @SuryanarayanaY 

Could you please look into this issue ? Thank you!

**Comment by SuryanarayanaY** [comment]
More context is available at keras repo #17429. Reproducible code attached [here](https://colab.research.google.com/gist/SuryanarayanaY/342b9f55642234ca69b604f80bb9ccb3/17429-grad_accumulation-on-multi-gpu-r1.ipynb).

Getting the below error when tried aggregating gradients inside nested tf.function which is not yet supported.

> RuntimeError: merge_call called while defining a new graph or a tf.function. This can often happen if the function fn passed to strategy.run() contains a nested @tf.function, and the nested @tf.function contains a synchronization point, such as aggregating gradients (e.g, optimizer.apply_gradients), or if the function fn uses a control flow statement which contains a synchronization point in the body. Such behaviors are not yet supported. Instead, please avoid nested tf.functions or control flow statements that may potentially cross a synchronization boundary, for example, wrap the fn passed to strategy.run or the entire strategy.run inside a tf.function or move the control flow out of fn. If you are subclassing a tf.keras.Model, please avoid decorating overridden methods test_step and train_step in tf.function

The code works fine in Eager mode by setting `model.compile(run_eagerly=True)` and the same code tested with `model.compile(run_eagerly=False)` and execution terminated with runtime error.

The code testing done on a 4-GPU VM and log stack attached below.

```
2023-01-31 07:07:25.352993: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2.11.0
(tf) suryanarayanay@ubuntu-20-04-test-gpu-surya:~$ python 17429_grad_accumulation_on_multi_gpu_r1.py 
2023-01-31 07:07:51.782069: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-31 07:07:51.904569: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-01-31 07:07:52.652556: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/suryanarayanay/miniconda3/envs/tf/lib/
2023-01-31 07:07:52.652650: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/suryanarayanay/miniconda3/envs/tf/lib/
2023-01-31 07:07:52.652665: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-01-31 07:07:57.538546: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1613] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 38321 MB memory:  -> device: 0, name: NVIDIA A100-SXM4-40GB, pci bus id: 0000:00:04.0, compute capability: 8.0
2023-01-31 07:07:57.542046: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1613] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 38397 MB memory:  -> device: 1, name: NVIDIA A100-SXM4-40GB, pci bus id: 0000:00:05.0, compute capability: 8.0
2023-01-31 07:07:57.544451: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1613] Created device /job:localhost/replica:0/task:0/device:GPU:2 with 38397 MB memory:  -> device: 2, name: NVIDIA A100-SXM4-40GB, pci bus id: 0000:00:06.0, compute capability: 8.0
2023-01-31 07:07:57.546846: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1613] Created device /job:localhost/replica:0/task:0/device:GPU:3 with 38397 MB memory:  -> device: 3, name: NVIDIA A100-SXM4-40GB, pci bus id: 0000:00:07.0, compute capability: 8.0
run_eagerly=True in model.compile()
Epoch 1/3
WARNING:tensorflow:Using MirroredStrategy eagerly has significant overhead currently. We will be working on improving this in the future, but for now please wrap `call_for_each_replica` or `experimental_run` or `run` inside a tf.function to get the best performance.
    1/10000 [..............................] - ETA: 10:05:14 - loss: 2.4525 - accuracy: 0.0000e+00WARNING:tensorflow:Using MirroredStrategy eagerly has significant overhead currently. We will be working on improving this in the future, but for now please wrap `call_for_each_replica` or `experimental_run` or `run` inside a tf.function to get the best performance.
    2/10000 [..............................] - ETA: 13:17 - loss: 2.4092 - accuracy: 0.0000e+00   WARNING:tensorflow:Using MirroredStrategy eagerly has significant overhead currently. We will be working on improving this in the future, but for now please wrap `call_for_each_replica` or `experimental_run` or `run` inside a tf.function to get the best performance.
    3/10000 [..............................] - ETA: 13:05 - loss: 2.2790 - accuracy: 0.0556    WARNING:tensorflow:Using MirroredStrategy eagerly has significant overhead currently. We will be working on improving this in the future, but for now please wrap `call_for_each_replica` or `experimental_run` or `run` inside a tf.function to get the best performance.
    4/10000 [..............................] - ETA: 13:04 - loss: 2.2379 - accuracy: 0.0833WARNING:tensorflow:Using MirroredStrategy eagerly has significant overhead currently. We will be working on improving this in the future, but for now please wrap `call_for_each_replica` or `experimental_run` or `run` inside a tf.function to get the best performance.
    9/10000 [..............................] - ETA: 12:57 - loss: 2.2492 - accuracy: 0.12962023-01-31 07:08:07.888400: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
2023-01-31 07:08:07.890184: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:234] Falling back to the CUDA driver for PTX compilation; ptxas does not support CC 8.0
2023-01-31 07:08:07.890206: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:237] Used ptxas at ptxas
2023-01-31 07:08:08.300869: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
WARNING:tensorflow:5 out of the last 5 calls to <function _BaseOptimizer._update_step_xla at 0x7fdb5c3a7ee0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:6 out of the last 6 calls to <function _BaseOptimizer._update_step_xla at 0x7fdb5c3a7ee0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
2023-01-31 07:08:08.704035: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
2023-01-31 07:08:09.118594: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
   49/10000 [..............................] - ETA: 25:40 - loss: 2.1064 - accuracy: 0.3367WARNING:tensorflow:5 out of the last 5 calls to <function _apply_all_reduce.<locals>._all_reduce at 0x7fdafc248040> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
   59/10000 [..............................] - ETA: 23:38 - loss: 2.0726 - accuracy: 0.3644WARNING:tensorflow:6 out of the last 6 calls to <function _apply_all_reduce.<locals>._all_reduce at 0x7fdafc1869d0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
10000/10000 [==============================] - 849s 85ms/step - loss: 0.2937 - accuracy: 0.9195
Epoch 2/3
10000/10000 [==============================] - 843s 84ms/step - loss: 0.1309 - accuracy: 0.9622
Epoch 3/3
10000/10000 [==============================] - 844s 84ms/step - loss: 0.0918 - accuracy: 0.9725
run_eagerly=False in model.compile()
Epoch 1/2
Traceback (most recent call last):
  File "/home/suryanarayanay/17429_grad_accumulation_on_multi_gpu_r1.py", line 94, in <module>
    custom_model.fit(x_train, y_train, batch_size=6, epochs=2, verbose = 1)
  File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/tmp/__autograph_generated_filesrk22zi7.py", line 15, in tf__train_function
    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
  File "/home/suryanarayanay/17429_grad_accumulation_on_multi_gpu_r1.py", line 42, in train_step
    tf.cond(
  File "/home/suryanarayanay/17429_grad_accumulation_on_multi_gpu_r1.py", line 49, in apply_accu_gradients
    self.optimizer.apply_gradients(zip(self.gradient_accumulation, self.trainable_variables))
RuntimeError: in user code:

    File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py", line 1249, in train_function  *
        return step_function(self, iterator)
    File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py", line 1233, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py", line 1222, in run_step  **
        outputs = model.train_step(data)
    File "/home/suryanarayanay/17429_grad_accumulation_on_multi_gpu_r1.py", line 42, in train_step
        tf.cond(
    File "/home/suryanarayanay/17429_grad_accumulation_on_multi_gpu_r1.py", line 49, in apply_accu_gradients
        self.optimizer.apply_gradients(zip(self.gradient_accumulation, self.trainable_variables))
    File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/keras/mixed_precision/loss_scale_optimizer.py", line 1301, in apply_gradients
        grads_and_vars = self._optimizer.aggregate_gradients(grads_and_vars)
    File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1105, in aggregate_gradients
        return optimizer_utils.all_reduce_sum_gradients(grads_and_vars)
    File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/keras/optimizers/optimizer_v2/utils.py", line 42, in all_reduce_sum_gradients
        reduced = tf.distribute.get_replica_context().merge_call(

    RuntimeError: `merge_call` called while defining a new graph or a tf.function. This can often happen if the function `fn` passed to `strategy.run()` contains a nested `@tf.function`, and the nested `@tf.function` contains a synchronization point, such as aggregating gradients (e.g, optimizer.apply_gradients), or if the function `fn` uses a control flow statement which contains a synchronization point in the body. Such behaviors are not yet supported. Instead, please avoid nested `tf.function`s or control flow statements that may potentially cross a synchronization boundary, for example, wrap the `fn` passed to `strategy.run` or the entire `strategy.run` inside a `tf.function` or move the control flow out of `fn`. If you are subclassing a `tf.keras.Model`, please avoid decorating overridden methods `test_step` and `train_step` in `tf.function`.

(tf) suryanarayanay@ubuntu-20-04-test-gpu-surya:~$ 
```
This issue requests for implementation of new functionality(aggregating gradients) that is not available with tf.distribute.MirroredStrategy() in graph mode. 

Thanks!

**Comment by SuryanarayanaY** [comment]
With tf-nightly(2.12.0-dev20230130) the code not worked with Eager mode also.

```
(tf) suryanarayanay@ubuntu-20-04-test-gpu-surya:~$ python 17429_grad_accumulation_on_multi_gpu_r1.py 
2023-01-31 10:07:52.406093: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-01-31 10:07:52.445358: E tensorflow/tsl/lib/monitoring/collection_registry.cc:81] Cannot register 2 metrics with the same name: /tensorflow/core/bfc_allocator_delay
2023-01-31 10:07:52.460322: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-31 10:07:53.319303: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-01-31 10:07:57.883002: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1634] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 38253 MB memory:  -> device: 0, name: NVIDIA A100-SXM4-40GB, pci bus id: 0000:00:04.0, compute capability: 8.0
2023-01-31 10:07:57.885538: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1634] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 38365 MB memory:  -> device: 1, name: NVIDIA A100-SXM4-40GB, pci bus id: 0000:00:05.0, compute capability: 8.0
2023-01-31 10:07:57.887951: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1634] Created device /job:localhost/replica:0/task:0/device:GPU:2 with 38365 MB memory:  -> device: 2, name: NVIDIA A100-SXM4-40GB, pci bus id: 0000:00:06.0, compute capability: 8.0
2023-01-31 10:07:57.890324: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1634] Created device /job:localhost/replica:0/task:0/device:GPU:3 with 38365 MB memory:  -> device: 3, name: NVIDIA A100-SXM4-40GB, pci bus id: 0000:00:07.0, compute capability: 8.0
2.12.0-dev20230130
run_eagerly=True in model.compile()
2023-01-31 10:08:01.559815: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [60000,28,28]
         [[{{node Placeholder/_10}}]]
2023-01-31 10:08:01.560213: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_11' with dtype float and shape [60000,10]
         [[{{node Placeholder/_11}}]]
WARNING:tensorflow:Using MirroredStrategy eagerly has significant overhead currently. We will be working on improving this in the future, but for now please wrap `call_for_each_replica` or `experimental_run` or `run` inside a tf.function to get the best performance.
    1/10000 [..............................] - ETA: 7:30:56 - loss: 2.3636 - accuracy: 0.1667WARNING:tensorflow:Using MirroredStrategy eagerly has significant overhead currently. We will be working on improving this in the future, but for now please wrap `call_for_each_replica` or `experimental_run` or `run` inside a tf.function to get the best performance.
    2/10000 [..............................] - ETA: 14:37 - loss: 2.4168 - accuracy: 0.0833  WARNING:tensorflow:Using MirroredStrategy eagerly has significant overhead currently. We will be working on improving this in the future, but for now please wrap `call_for_each_replica` or `experimental_run` or `run` inside a tf.function to get the best performance.
    3/10000 [..............................] - ETA: 14:03 - loss: 2.4220 - accuracy: 0.0556WARNING:tensorflow:Using MirroredStrategy eagerly has significant overhead currently. We will be working on improving this in the future, but for now please wrap `call_for_each_replica` or `experimental_run` or `run` inside a tf.function to get the best performance.
    4/10000 [..............................] - ETA: 13:50 - loss: 2.4324 - accuracy: 0.0833WARNING:tensorflow:Using MirroredStrategy eagerly has significant overhead currently. We will be working on improving this in the future, but for now please wrap `call_for_each_replica` or `experimental_run` or `run` inside a tf.function to get the best performance.
    9/10000 [..............................] - ETA: 13:43 - loss: 2.3421 - accuracy: 0.14812023-01-31 10:08:06.531002: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at nccl_ops.cc:108 : UNKNOWN: Error invoking NCCL: unhandled cuda error
2023-01-31 10:08:06.531069: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at nccl_ops.cc:108 : UNKNOWN: Error invoking NCCL: unhandled cuda error
2023-01-31 10:08:06.531128: I tensorflow/core/common_runtime/executor.cc:1197] [/job:localhost/replica:0/task:0/device:GPU:3] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): UNKNOWN: Error invoking NCCL: unhandled cuda error
         [[{{node NcclAllReduce_3}}]]
2023-01-31 10:08:06.531153: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at nccl_ops.cc:108 : UNKNOWN: Error invoking NCCL: unhandled cuda error
2023-01-31 10:08:06.531209: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at nccl_ops.cc:108 : UNKNOWN: Error invoking NCCL: unhandled cuda error
2023-01-31 10:08:06.531258: I tensorflow/core/common_runtime/executor.cc:1197] [/job:localhost/replica:0/task:0/device:GPU:2] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): UNKNOWN: Error invoking NCCL: unhandled cuda error
         [[{{node NcclAllReduce_2}}]]
2023-01-31 10:08:06.531280: I tensorflow/core/common_runtime/executor.cc:1197] [/job:localhost/replica:0/task:0/device:GPU:1] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): UNKNOWN: Error invoking NCCL: unhandled cuda error
         [[{{node NcclAllReduce_1}}]]
2023-01-31 10:08:06.531319: I tensorflow/core/common_runtime/executor.cc:1197] [/job:localhost/replica:0/task:0/device:GPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): UNKNOWN: Error invoking NCCL: unhandled cuda error
         [[{{node NcclAllReduce}}]]
Traceback (most recent call last):
  File "/home/suryanarayanay/17429_grad_accumulation_on_multi_gpu_r1.py", line 73, in <module>
    custom_model.fit(x_train, y_train, batch_size=6, epochs=1, verbose = 1)
  File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnknownError: Graph execution error:

Detected at node 'NcclAllReduce' defined at (most recent call last):
    File "/home/suryanarayanay/17429_grad_accumulation_on_multi_gpu_r1.py", line 73, in <module>
      custom_model.fit(x_train, y_train, batch_size=6, epochs=1, verbose = 1)
    File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py", line 1650, in fit
      tmp_logs = self.train_function(iterator)
    File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py", line 1249, in train_function
      return step_function(self, iterator)
    File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py", line 1233, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/keras/optimizers/optimizer_v2/utils.py", line 175, in _all_reduce_sum_fn
      return distribution.extended.batch_reduce_to(
    File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/ops/nccl_ops.py", line 218, in _all_reduce
      for t in tensors:
    File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/ops/nccl_ops.py", line 221, in _all_reduce
      res.append(
Node: 'NcclAllReduce'
Detected at node 'NcclAllReduce_3' defined at (most recent call last):
    File "/home/suryanarayanay/17429_grad_accumulation_on_multi_gpu_r1.py", line 73, in <module>
      custom_model.fit(x_train, y_train, batch_size=6, epochs=1, verbose = 1)
    File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py", line 1650, in fit
      tmp_logs = self.train_function(iterator)
    File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py", line 1249, in train_function
      return step_function(self, iterator)
    File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py", line 1233, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/keras/optimizers/optimizer_v2/utils.py", line 175, in _all_reduce_sum_fn
      return distribution.extended.batch_reduce_to(
    File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/ops/nccl_ops.py", line 218, in _all_reduce
      for t in tensors:
    File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/ops/nccl_ops.py", line 221, in _all_reduce
      res.append(
Node: 'NcclAllReduce_3'
Detected at node 'NcclAllReduce_2' defined at (most recent call last):
    File "/home/suryanarayanay/17429_grad_accumulation_on_multi_gpu_r1.py", line 73, in <module>
      custom_model.fit(x_train, y_train, batch_size=6, epochs=1, verbose = 1)
    File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py", line 1650, in fit
      tmp_logs = self.train_function(iterator)
    File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py", line 1249, in train_function
      return step_function(self, iterator)
    File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py", line 1233, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/keras/optimizers/optimizer_v2/utils.py", line 175, in _all_reduce_sum_fn
      return distribution.extended.batch_reduce_to(
    File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/ops/nccl_ops.py", line 218, in _all_reduce
      for t in tensors:
    File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/ops/nccl_ops.py", line 221, in _all_reduce
      res.append(
Node: 'NcclAllReduce_2'
Detected at node 'NcclAllReduce_1' defined at (most recent call last):
    File "/home/suryanarayanay/17429_grad_accumulation_on_multi_gpu_r1.py", line 73, in <module>
      custom_model.fit(x_train, y_train, batch_size=6, epochs=1, verbose = 1)
    File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py", line 1650, in fit
      tmp_logs = self.train_function(iterator)
    File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py", line 1249, in train_function
      return step_function(self, iterator)
    File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/keras/engine/training.py", line 1233, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/keras/optimizers/optimizer_v2/utils.py", line 175, in _all_reduce_sum_fn
      return distribution.extended.batch_reduce_to(
    File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/ops/nccl_ops.py", line 218, in _all_reduce
      for t in tensors:
    File "/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/ops/nccl_ops.py", line 221, in _all_reduce
      res.append(
Node: 'NcclAllReduce_1'
4 root error(s) found.
  (0) UNKNOWN:  Error invoking NCCL: unhandled cuda error
         [[{{node NcclAllReduce}}]]
  (1) UNKNOWN:  Error invoking NCCL: unhandled cuda error
         [[{{node NcclAllReduce_3}}]]
  (2) UNKNOWN:  Error invoking NCCL: unhandled cuda error
         [[{{node NcclAllReduce_2}}]]
  (3) UNKNOWN:  Error invoking NCCL: unhandled cuda error
         [[{{node NcclAllReduce_1}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference__all_reduce_7886]
(tf) suryanarayanay@ubuntu-20-04-test-gpu-surya:~$ 
```

**Comment by innat** [comment]
Similar issue https://github.com/tensorflow/models/issues/9972
