### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by smarthmaster** [tensorflow/tensorflow#59509]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.11

### Custom Code

Yes

### OS Platform and Distribution

windows 11

### Python version

3.10

### Current Behaviour?

```shell
A bug happened!

I am getting the error that the list index is out of range in the provided code.

2023-02-01 12:50:34.742912: W tensorflow/core/framework/op_kernel.cc:1818] UNKNOWN: IndexError: list index out of range
Traceback (most recent call last):

  File "D:\python\lib\site-packages\tensorflow\python\ops\script_ops.py", line 269, in __call__
    return func(device, token, args)

  File "D:\python\lib\site-packages\tensorflow\python\ops\script_ops.py", line 147, in __call__
    outputs = self._call(device, args)

  File "D:\python\lib\site-packages\tensorflow\python\ops\script_ops.py", line 154, in _call
    ret = self._func(*args)

  File "D:\python\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\cavir\AppData\Local\Temp\__autograph_generated_file9w2jtgyr.py", line 23, in helper
    col = ag__.ld(fen)[1]

IndexError: list index out of range


2023-02-01 12:50:34.792828: W t50ensorflow/core/framework/op_kernel.cc:1818] UNKNOWN: IndexError: list index out of range
Traceback (most recent call last):

  File "D:\python\lib\site-packages\tensorflow\python\ops\script_ops.py", line 269, in __call__
    return func(device, token, args)

  File
"D:\pyth42on\lib\site-packages\tensorflow\python\ops\script_ops.py", lin
e 147rn2k2r/ppp1n1bp/4p1p1/4N3/5B2/8/PPP2PPP/RN3RK1, in __call__

 outputs = self._call(device, args)

  File "D:\python\lib\site-packages\tensorflow\python\ops\script_ops.py", line 154, in _call
    ret = self._func(*args)

  File "D:\python\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\cavir\AppData\Local\Temp\__autograph_generated_file9w2jtgyr.py", line 23, in helper
    col = ag__.ld(fen)[1]

IndexError: list index out of range


2023-02-01 12:50:34.826137: W tensorflow/core/framework/op_kernel.cc:1818] UNKNOWN: IndexError: list index out of range
Traceback (most recent call last):

  File "D:\python\lib\site-packages\tensorflow\python\ops\script_ops.py", line 269, in __call__
    return func(device, token, args)

  File "D:\python\lib\site-packages\tensorflow\python\ops\script_ops.py", line 147, in __call__
    outputs = self._call(device, args)

  File "D:\python\lib\site-packages\tensorflow\python\ops\script_ops.py", line 154, in _call
    ret = self._func(*args)

  File "D:\python\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\cavir\AppData\Local\Temp\__autograph_generated_file9w2jtgyr.py", line 23, in helper
    col = ag__.ld(fen)[1]

IndexError: list index out of range


2023-02-01 12:50:34.853068: W tensorflow/core/framework/op_kernel.cc:1818] UNKNOWN: IndexError: list index out of range
Traceback (most recent call last):

  File "D:\python\lib\site-packages\tensorflow\python\ops\script_ops.py", line 269, in __call__
    return func(device, token, args)

  File "D:\python\lib\site-packages\tensorflow\python\ops\script_ops.py", line 147, in __call__
    outputs = self._call(device, args)

  File "D:\python\lib\site-packages\tensorflow\python\ops\script_ops.py", line 154, in _call
    ret = self._func(*args)

  File "D:\python\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\cavir\AppData\Local\Temp\__autograph_generated_file9w2jtgyr.py", line 23, in helper
    col = ag__.ld(fen)[1]

IndexError: list index out of range


2023-02-01 12:50:34.879556: W tensorflow/core/framework/op_kernel.cc:1818] UNKNOWN: IndexError: list index out of range
Traceback (most recent call last):

  File "D:\python\lib\site-packages\tensorflow\python\ops\script_ops.py", line 269, in __call__
    return func(device, token, args)

  File "D:\python\lib\site-packages\tensorflow\python\ops\script_ops.py", line 147, in __call__
    outputs = self._call(device, args)

  File "D:\python\lib\site-packages\tensorflow\python\ops\script_ops.py", line 154, in _call
    ret = self._func(*args)

  File "D:\python\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\cavir\AppData\Local\Temp\__autograph_generated_file9w2jtgyr.py", line 23, in helper
    col = ag__.ld(fen)[1]

IndexError: list index out of range


2023-02-01 12:50:34.909811: W tensorflow/core/framework/op_kernel.cc:1818] UNKNOWN: IndexError: list index out of range
Traceback (most recent call last):

  File "D:\python\lib\site-packages\tensorflow\python\ops\script_ops.py", line 269, in __call__
    return func(device, token, args)

  File "D:\python\lib\site-packages\tensorflow\python\ops\script_ops.py", line 147, in __call__
    outputs = self._call(device, args)

  File "D:\python\lib\site-packages\tensorflow\python\ops\script_ops.py", line 154, in _call
    ret = self._func(*args)

  File "D:\python\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\cavir\AppData\Local\Temp\__autograph_generated_file9w2jtgyr.py", line 23, in helper
    col = ag__.ld(fen)[1]

IndexError: list index out of range


2023-02-01 12:50:34.936740: W tensorflow/core/framework/op_kernel.cc:1818] UNKNOWN: IndexError: list index out of range
Traceback (most recent call last):

  File "D:\python\lib\site-packages\tensorflow\python\ops\script_ops.py", line 269, in __call__
    return func(device, token, args)

  File "D:\python\lib\site-packages\tensorflow\python\ops\script_ops.py", line 147, in __call__
    outputs = self._call(device, args)

  File "D:\python\lib\site-packages\tensorflow\python\ops\script_ops.py", line 154, in _call
    ret = self._func(*args)

  File "D:\python\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\cavir\AppData\Local\Temp\__autograph_generated_file9w2jtgyr.py", line 23, in helper
    col = ag__.ld(fen)[1]

IndexError: list index out of range


2023-02-01 12:50:34.975022: W tensorflow/core/framework/op_kernel.cc:1818] UNKNOWN: IndexError: list index out of range
Traceback (most recent call last):

  File "D:\python\lib\site-packages\tensorflow\python\ops\script_ops.py", line 269, in __call__
    return func(device, token, args)

  File "D:\python\lib\site-packages\tensorflow\python\ops\script_ops.py", line 147, in __call__
    outputs = self._call(device, args)

  File "D:\python\lib\site-packages\tensorflow\python\ops\script_ops.py", line 154, in _call
    ret = self._func(*args)

  File "D:\python\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\cavir\AppData\Local\Temp\__autograph_generated_file9w2jtgyr.py", line 23, in helper
    col = ag__.ld(fen)[1]

IndexError: list index out of range


2023-02-01 12:50:35.014221: W tensorflow/core/framework/op_kernel.cc:1818] UNKNOWN: IndexError: list index out of range
Traceback (most recent call last):

  56
60
6k1/ppp2p1p/5q2/5P2/5r2/2PQ1N1P/PP3PK1/R7File "D:\python\lib\site-packages\tensorflow\python\ops\script_ops.py", line 269, in __call__
    return func(device, token, args)

  File "D:\python\lib\site-packages\tensorflow\python\ops\script_ops.py", line 147, in __call__
    outputs = self._call(device, args)

  File "D:\python\lib\site-packages\tensorflow\python\ops\script_ops.py", line 154, in _call

    ret = self._func(*args)

  File "D:\python\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\cavir\AppData\Local\Temp\__autograph_generated_file9w2jtgyr.py", line 23, in helper
    col = ag__.ld(fen)[1]

IndexError: list index out of range


2023-02-01 12:50:35.059909: W tensorflow/core/framework/op_kernel.cc:1818] UNKNOWN: IndexError: list index out of range
Traceback (most recent call last):

  File "D:\python\lib\site-packages\tensorflow\python\ops\script_ops.py", line 269, in __call__
    return func(device, token, args)

  File "D:\python\lib\site-packages\tensorflow\python\ops\script_ops.py", line 147, in __call__
    outputs = self._call(device, args)

  File "D:\python\lib\site-packages\tensorflow\python\ops\script_ops.py", line 154, in _call
    ret = self._func(*args)

  File "D:\python\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\cavir\AppData\Local\Temp\__autograph_generated_file9w2jtgyr.py", line 23, in helper
    col = ag__.ld(fen)[1]

IndexError: list index out of range
```

### Standalone code to reproduce the issue

```shell
https://github.com/smarthmaster/issue
it is the code and the basic in.txt is this
r3r1k1/1p3ppp/p2q4/3b4/3p4/P2P4/1P1Q1PPP/R3R1K1  0  2
2r1r1k1/1p3ppp/p2q4/3b4/3p4/P2P4/1P1Q1PPP/R3R1K1  56  58
2r1r1k1/1p3ppp/p2q4/3b4/3p4/P2P4/1P1Q1PPP/2R1R1K1  27  18
2r1r1k1/1p3ppp/p1bq4/8/3p4/P2P4/1P1Q1PPP/2R1R1K1  55  47
2r1r1k1/1p3ppp/p1bq4/8/3p4/P2P3P/1P1Q1PP1/2R1R1K1  19  27
2r1r1k1/1p3ppp/p1b5/3q4/3p4/P2P3P/1P1Q1PP1/2R1R1K1  53  45
2r1r1k1/1p3ppp/p1b5/3q4/3p4/P2P1P1P/1P1Q2P1/2R1R1K1  27  19
2r1r1k1/1p3ppp/p1bq4/8/3p4/P2P1P1P/1P1Q2P1/2R1R1K1  49  33
2r1r1k1/1p3ppp/p1bq4/8/1P1p4/P2P1P1P/3Q2P1/2R1R1K1  19  22
2r1r1k1/1p3ppp/p1b3q1/8/1P1p4/P2P1P1P/3Q2P1/2R1R1K1  58  34
2r1r1k1/1p3ppp/p1b3q1/8/1PRp4/P2P1P1P/3Q2P1/4R1K1  2  3
3rr1k1/1p3ppp/p1b3q1/8/1PRp4/P2P1P1P/3Q2P1/4R1K1  62  53
3rr1k1/1p3ppp/p1b3q1/8/1PRp4/P2P1P1P/3Q1KP1/4R3  18  25
3rr1k1/1p3ppp/p5q1/1b6/1PRp4/P2P1P1P/3Q1KP1/4R3  34  10
3rr1k1/1pR2ppp/p5q1/1b6/1P1p4/P2P1P1P/3Q1KP1/4R3  25  18
3rr1k1/1pR2ppp/p1b3q1/8/1P1p4/P2P1P1P/3Q1KP1/4R3  60  59
3rr1k1/1pR2ppp/p1b3q1/8/1P1p4/P2P1P1P/3Q1KP1/3R4  22  19
3rr1k1/1pR2ppp/p1bq4/8/1P1p4/P2P1P1P/3Q1KP1/3R4  10  13
3rr1k1/1p3Rpp/p1bq4/8/1P1p4/P2P1P1P/3Q1KP1/3R4  6  0
3rr3/1p3kpp/p1bq4/8/1P1p4/P2P1P1P/3Q1KP1/3R4  51  30
3rr3/1p3kpp/p1bq4/6Q1/1P1p4/P2P1P1P/5KP1/3R4  13  6
3rr1k1/1p4pp/p1bq4/6Q1/1P1p4/P2P1P1P/5KP1/3R4  30  60
rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR  11  27
rnbqkbnr/ppp1pppp/8/3p4/4P3/8/PPPP1PPP/RNBQKBNR  36  27
rnbqkbnr/ppp1pppp/8/3P4/8/8/PPPP1PPP/RNBQKBNR  3  0
rnb1kbnr/ppp1pppp/8/3q4/8/8/PPPP1PPP/RNBQKBNR  51  35
rnb1kbnr/ppp1pppp/8/3q4/3P4/8/PPP2PPP/RNBQKBNR  27  20
rnb1kbnr/ppp1pppp/4q3/8/3P4/8/PPP2PPP/RNBQKBNR  61  52
rnb1kbnr/ppp1pppp/4q3/8/3P4/8/PPP1BPPP/RNBQK1NR  10  18
rnb1kbnr/pp2pppp/2p1q3/8/3P4/8/PPP1BPPP/RNBQK1NR  57  42
rnb1kbnr/pp2pppp/2p1q3/8/3P4/2N5/PPP1BPPP/R1BQK1NR  20  22
rnb1kbnr/pp2pppp/2p3q1/8/3P4/2N5/PPP1BPPP/R1BQK1NR  54  46
rnb1kbnr/pp2pppp/2p3q1/8/3P4/2N3P1/PPP1BP1P/R1BQK1NR  2  29
rn2kbnr/pp2pppp/2p3q1/5b2/3P4/2N3P1/PPP1BP1P/R1BQK1NR  62  45
rn2kbnr/pp2pppp/2p3q1/5b2/3P4/2N2NP1/PPP1BP1P/R1BQK2R  50  0
rn2kbnr/pp2pppp/2p3q1/8/3P4/2N2NP1/PPb1BP1P/R1BQK2R  59  51
rn2kbnr/pp2pppp/2p3q1/8/3P4/2N2NP1/PPbQBP1P/R1B1K2R  50  29
rn2kbnr/pp2pppp/2p3q1/5b2/3P4/2N2NP1/PP1QBP1P/R1B1K2R  60  62
rn2kbnr/pp2pppp/2p3q1/5b2/3P4/2N2NP1/PP1QBP1P/R1B2RK1  29  47
rn2kbnr/pp2pppp/2p3q1/8/3P4/2N2NPb/PP1QBP1P/R1B2RK1  45  39
rn2kbnr/pp2pppp/2p3q1/8/3P3N/2N3Pb/PP1QBP1P/R1B2RK1  22  20
rn2kbnr/pp2pppp/2p1q3/8/3P3N/2N3Pb/PP1QBP1P/R1B2RK1  61  60
rn2kbnr/pp2pppp/2p1q3/8/3P3N/2N3Pb/PP1QBP1P/R1B1R1K1  20  11
rn2kbnr/pp1qpppp/2p5/8/3P3N/2N3Pb/PP1QBP1P/R1B1R1K1  52  45
rn2kbnr/pp1qpppp/2p5/8/3P3N/2N2BPb/PP1Q1P1P/R1B1R1K1  47  38
rn2kbnr/pp1qpppp/2p5/8/3P2bN/2N2BP1/PP1Q1P1P/R1B1R1K1  51  37
rn2kbnr/pp1qpppp/2p5/8/3P1QbN/2N2BP1/PP3P1P/R1B1R1K1  45  0
rn2kbnr/pp1qpppp/2p5/8/3P1Q1N/2N2bP1/PP3P1P/R1B1R1K1  39  45
rn2kbnr/pp1qpppp/2p5/8/3P1Q2/2N2NP1/PP3P1P/R1B1R1K1  12  20
rn2kbnr/pp1q1ppp/2p1p3/8/3P1Q2/2N2NP1/PP3P1P/R1B1R1K1  35  27
rn2kbnr/pp1q1ppp/2p1p3/3P4/5Q2/2N2NP1/PP3P1P/R1B1R1K1  27  0
rn2kbnr/pp1q1ppp/4p3/3p4/5Q2/2N2NP1/PP3P1P/R1B1R1K1  58  44
rn2kbnr/pp1q1ppp/4p3/3p4/5Q2/2N1BNP1/PP3P1P/R3R1K1  5  19
rn2k1nr/pp1q1ppp/3bp3/3p4/5Q2/2N1BNP1/PP3P1P/R3R1K1  45  28
rn2k1nr/pp1q1ppp/3bp3/3pN3/5Q2/2N1B1P1/PP3P1P/R3R1K1  11  12
rn2k1nr/pp2qppp/3bp3/3pN3/5Q2/2N1B1P1/PP3P1P/R3R1K1  42  25
rn2k1nr/pp2qppp/3bp3/1N1pN3/5Q2/4B1P1/PP3P1P/R3R1K1  1  11
r3k1nr/pp1nqppp/3bp3/1N1pN3/5Q2/4B1P1/PP3P1P/R3R1K1  25  10
r3k1nr/ppNnqppp/3bp3/3pN3/5Q2/4B1P1/PP3P1P/R3R1K1  10  0
r3k1nr/ppbnqppp/4p3/3pN3/5Q2/4B1P1/PP3P1P/R3R1K1  44  35
r3k1nr/ppbnqppp/4p3/3pN3/3B1Q2/6P1/PP3P1P/R3R1K1  28  0
r3k1nr/ppb1qppp/4p3/3pn3/3B1Q2/6P1/PP3P1P/R3R1K1  35  28
r3k1nr/ppb1qppp/4p3/3pB3/5Q2/6P1/PP3P1P/R3R1K1  28  0
r3k1nr/pp2qppp/4p3/3pb3/5Q2/6P1/PP3P1P/R3R1K1  37  28
r3k1nr/pp2qppp/4p3/3pQ3/8/6P1/PP3P1P/R3R1K1  13  21
r3k1nr/pp2q1pp/4pp2/3pQ3/8/6P1/PP3P1P/R3R1K1  28  42
r3k1nr/pp2q1pp/4pp2/3p4/8/2Q3P1/PP3P1P/R3R1K1  20  28
r3k1nr/pp2q1pp/5p2/3pp3/8/2Q3P1/PP3P1P/R3R1K1  42  24
r3k1nr/pp2q1pp/5p2/Q2pp3/8/6P1/PP3P1P/R3R1K1  9  17
r3k1nr/p3q1pp/1p3p2/Q2pp3/8/6P1/PP3P1P/R3R1K1  24  59
rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR  12  20
rnbqkbnr/pppp1ppp/4p3/8/4P3/8/PPPP1PPP/RNBQKBNR  57  42
rnbqkbnr/pppp1ppp/4p3/8/4P3/2N5/PPPP1PPP/R1BQKBNR  10  18
rnbqkbnr/pp1p1ppp/2p1p3/8/4P3/2N5/PPPP1PPP/R1BQKBNR  62  45
rnbqkbnr/pp1p1ppp/2p1p3/8/4P3/2N2N2/PPPP1PPP/R1BQKB1R  11  19
rnbqkbnr/pp3ppp/2ppp3/8/4P3/2N2N2/PPPP1PPP/R1BQKB1R  51  35
rnbqkbnr/pp3ppp/2ppp3/8/3PP3/2N2N2/PPP2PPP/R1BQKB1R  6  21
rnbqkb1r/pp3ppp/2pppn2/8/3PP3/2N2N2/PPP2PPP/R1BQKB1R  58  44
rnbqkb1r/pp3ppp/2pppn2/8/3PP3/2N1BN2/PPP2PPP/R2QKB1R  5  12
rnbqk2r/pp2bppp/2pppn2/8/3PP3/2N1BN2/PPP2PPP/R2QKB1R  61  43
rnbqk2r/pp2bppp/2pppn2/8/3PP3/2NBBN2/PPP2PPP/R2QK2R  4  6
rnbq1rk1/pp2bppp/2pppn2/8/3PP3/2NBBN2/PPP2PPP/R2QK2R  59  51
rnbq1rk1/pp2bppp/2pppn2/8/3PP3/2NBBN2/PPPQ1PPP/R3K2R  20  28
rnbq1rk1/pp2bppp/2pp1n2/4p3/3PP3/2NBBN2/PPPQ1PPP/R3K2R  35  28
rnbq1rk1/pp2bppp/2pp1n2/4P3/4P3/2NBBN2/PPPQ1PPP/R3K2R  28  0
rnbq1rk1/pp2bppp/2p2n2/4p3/4P3/2NBBN2/PPPQ1PPP/R3K2R  48  40
rnbq1rk1/pp2bppp/2p2n2/4p3/4P3/P1NBBN2/1PPQ1PPP/R3K2R  3  10
rnb2rk1/ppq1bppp/2p2n2/4p3/4P3/P1NBBN2/1PPQ1PPP/R3K2R  55  47
rnb2rk1/ppq1bppp/2p2n2/4p3/4P3/P1NBBN1P/1PPQ1PP1/R3K2R  2  20
```

### Relevant log output

_No response_</details>

**Comment by smarthmaster** [comment]
@gaikwadrahul8 please respond to this

**Comment by DURGESH716** [comment]
Hello @smarthmaster 
This error message is indicating an issue with a TensorFlow script, specifically with the line `col = ag__.ld(fen)[1].` The message says that the list index is out of range, which means that the code is trying to access an element of a list that does not exist. This could be because the list is empty, or because the index being accessed is too large for the size of the list. To resolve this issue, you may want to check the input `fen` to ensure it is not empty and that it is being passed the correct value. Additionally, you may want to verify that the index `[1]` is the appropriate index for the list returned by `ag__.ld(fen).`

**Comment by DURGESH716** [comment]
Let me know if it helps ?

**Comment by smarthmaster** [comment]
the problem is arising in model.fit
def preprocess(inp):
    def helper(inp):
        fen, moved_from, moved_to = inp.numpy().decode().split('  ')
        print(fen,'done')
        moved_from = int(moved_from) 
        moved_to = int(moved_to) 

        fen = fen.split()
        print(fen)
        col = fen[1]
        fen = fen[0]

        if col == 'b':
            fen = invert_fen(fen)
            moved_from = 63 - moved_from
            moved_to = 63 - moved_to

        if TRAIN_MOVE_FROM:
            moved_from_board = number_to_board(num=moved_from)
        else:
            moved_to_board = number_to_board(num=moved_to)

        board = fen_to_matrix(fen=fen)

        if col == 'b':
            if TRAIN_MOVE_FROM:
                moved_from_board = np.flip(moved_from_board, axis=1)
            else:
                moved_to_board = np.flip(moved_to_board, axis=1)

        if TRAIN_MOVE_FROM:
            return board, moved_from_board
        else:
            return board, moved_to_board
    
    # return tf.random.normal((8, 8))
    return tf.py_function(func=helper, inp=[inp], Tout=[tf.int32, tf.int32])

ds = tf.data.TextLineDataset('out.txt').repeat()
ds = ds.shuffle(buffer_size=1000)
# ds = ds.batch(BATCH_SIZE)
ds = ds.map(preprocess, num_parallel_calls=tf.data.AUTOTUNE)

train = ds.skip(VAL_SIZE).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
val = ds.take(VAL_SIZE).batch(BATCH_SIZE)

class SaveModel(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs=None):
        name = 'gm_from/model{}.h5'.format(epoch + 1)
        self.model.save(name, overwrite=True,)

cbk = SaveModel()

tensorboard_callback = tf.keras.callbacks.TensorBoard(
    log_dir='logs/callback',
    profile_batch='10,14',
)

# print('Fitting...')

# model.load_weights('checkpoints/ckpt')

model.fit(
    train,
    epochs=EPOCHS, 
    steps_per_epoch=STEPS_PER_EPOCH, 
    validation_data=val,
    callbacks=[tensorboard_callback],
    verbose=0,
)


this is the code

and out.txt is a file with data like
4r2k/3q2pp/6p1/1p2R3/3n1BPb/3P3P/PP6/3Q1RK1  4  5
5r1k/3q2pp/6p1/1p2R3/3n1BPb/3P3P/PP6/3Q1RK1  37  44
5r1k/3q2pp/6p1/1p2R3/3n2Pb/3PB2P/PP6/3Q1RK1  5  2
2r4k/3q2pp/6p1/1p2R3/3n2Pb/3PB2P/PP6/3Q1RK1  28  36
2r4k/3q2pp/6p1/1p6/3nR1Pb/3PB2P/PP6/3Q1RK1  35  20
2r4k/3q2pp/4n1p1/1p6/4R1Pb/3PB2P/PP6/3Q1RK1  43  35
2r4k/3q2pp/4n1p1/1p6/3PR1Pb/4B2P/PP6/3Q1RK1  15  31
2r4k/3q2p1/4n1p1/1p5p/3PR1Pb/4B2P/PP6/3Q1RK1  35  27
2r4k/3q2p1/4n1p1/1p1P3p/4R1Pb/4B2P/PP6/3Q1RK1  20  30
2r4k/3q2p1/6p1/1p1P2np/4R1Pb/4B2P/PP6/3Q1RK1  44  30
2r4k/3q2p1/6p1/1p1P2Bp/4R1Pb/7P/PP6/3Q1RK1  30  0
2r4k/3q2p1/6p1/1p1P2bp/4R1P1/7P/PP6/3Q1RK1  38  31
2r4k/3q2p1/6p1/1p1P2bP/4R3/7P/PP6/3Q1RK1  11  0
2r4k/6p1/6p1/1p1P2bP/4R3/7q/PP6/3Q1RK1  59  38
2r4k/6p1/6p1/1p1P2bP/4R1Q1/7q/PP6/5RK1  30  44
2r4k/6p1/6p1/1p1P3P/4R1Q1/4b2q/PP6/5RK1  36  44
2r4k/6p1/6p1/1p1P3P/6Q1/4R2q/PP6/5RK1  38  0
2r4k/6p1/6p1/1p1P3P/6q1/4R3/PP6/5RK1  44  60
rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR  10  26
rnbqkbnr/pp1ppppp/8/2p5/4P3/8/PPPP1PPP/RNBQKBNR  57  42
rnbqkbnr/pp1ppppp/8/2p5/4P3/2N5/PPPP1PPP/R1BQKBNR  1  18
r1bqkbnr/pp1ppppp/2n5/2p5/4P3/2N5/PPPP1PPP/R1BQKBNR  51  43
r1bqkbnr/pp1ppppp/2n5/2p5/4P3/2NP4/PPP2PPP/R1BQKBNR  8  16
r1bqkbnr/1p1ppppp/p1n5/2p5/4P3/2NP4/PPP2PPP/R1BQKBNR  58  51
r1bqkbnr/1p1ppppp/p1n5/2p5/4P3/2NP4/PPPB1PPP/R2QKBNR  12  20
r1bqkbnr/1p1p1ppp/p1n1p3/2p5/4P3/2NP4/PPPB1PPP/R2QKBNR  55  47
r1bqkbnr/1p1p1ppp/p1n1p3/2p5/4P3/2NP3P/PPPB1PP1/R2QKBNR  11  27
r1bqkbnr/1p3ppp/p1n1p3/2pp4/4P3/2NP3P/PPPB1PP1/R2QKBNR  36  27
r1bqkbnr/1p3ppp/p1n1p3/2pP4/8/2NP3P/PPPB1PP1/R2QKBNR  27  0
r1bqkbnr/1p3ppp/p1n5/2pp4/8/2NP3P/PPPB1PP1/R2QKBNR  42  27
r1bqkbnr/1p3ppp/p1n5/2pN4/8/3P3P/PPPB1PP1/R2QKBNR  3  0
r1b1kbnr/1p3ppp/p1n5/2pq4/8/3P3P/PPPB1PP1/R2QKBNR  48  40
r1b1kbnr/1p3ppp/p1n5/2pq4/8/P2P3P/1PPB1PP1/R2QKBNR  6  21
r1b1kb1r/1p3ppp/p1n2n2/2pq4/8/P2P3P/1PPB1PP1/R2QKBNR  50  42
r1b1kb1r/1p3ppp/p1n2n2/2pq4/8/P1PP3P/1P1B1PP1/R2QKBNR  18  28
r1b1kb1r/1p3ppp/p4n2/2pqn3/8/P1PP3P/1P1B1PP1/R2QKBNR  59  32
r1b1kb1r/1p3ppp/p4n2/2pqn3/Q7/P1PP3P/1P1B1PP1/R3KBNR  9  25
r1b1kb1r/5ppp/p4n2/1ppqn3/Q7/P1PP3P/1P1B1PP1/R3KBNR  32  24
r1b1kb1r/5ppp/p4n2/Qppqn3/8/P1PP3P/1P1B1PP1/R3KBNR  43  0
r1b1kb1r/5ppp/p4n2/Qppq4/8/P1Pn3P/1P1B1PP1/R3KBNR  60  59
r1b1kb1r/5ppp/p4n2/Qppq4/8/P1Pn3P/1P1B1PP1/R2K1BNR  53  0
r1b1kb1r/5ppp/p4n2/Qppq4/8/P1P4P/1P1B1nP1/R2K1BNR  59  50
r1b1kb1r/5ppp/p4n2/Qppq4/8/P1P4P/1PKB1nP1/R4BNR  63  0
r1b1kb1r/5ppp/p4n2/Qppq4/8/P1P4P/1PKB2P1/R4BNn  61  25
r1b1kb1r/5ppp/p4n2/QBpq4/8/P1P4P/1PKB2P1/R5Nn  2  11
r3kb1r/3b1ppp/p4n2/QBpq4/8/P1P4P/1PKB2P1/R5Nn  25  11
r3kb1r/3B1ppp/p4n2/Q1pq4/8/P1P4P/1PKB2P1/R5Nn  27  0
r3kb1r/3q1ppp/p4n2/Q1p5/8/P1P4P/1PKB2P1/R5Nn  62  45
r3kb1r/3q1ppp/p4n2/Q1p5/8/P1P2N1P/1PKB2P1/R6n  63  53
r3kb1r/3q1ppp/p4n2/Q1p5/8/P1P2N1P/1PKB1nP1/R7  45  28
r3kb1r/3q1ppp/p4n2/Q1p1N3/8/P1P4P/1PKB1nP1/R7  11  29
r3kb1r/5ppp/p4n2/Q1p1Nq2/8/P1P4P/1PKB1nP1/R7  50  58
r3kb1r/5ppp/p4n2/Q1p1Nq2/8/P1P4P/1P1B1nP1/R1K5  29  36
r3kb1r/5ppp/p4n2/Q1p1N3/4q3/P1P4P/1P1B1nP1/R1K5  28  13
r3kb1r/5Npp/p4n2/Q1p5/4q3/P1P4P/1P1B1nP1/R1K5  4  0
r4b1r/5kpp/p4n2/Q1p5/4q3/P1P4P/1P1B1nP1/R1K5  24  10
r4b1r/2Q2kpp/p4n2/2p5/4q3/P1P4P/1P1B1nP1/R1K5  36  12
r4b1r/2Q1qkpp/p4n2/2p5/8/P1P4P/1P1B1nP1/R1K5  10  12
r4b1r/4Qkpp/p4n2/2p5/8/P1P4P/1P1B1nP1/R1K5  12  0
r6r/4bkpp/p4n2/2p5/8/P1P4P/1P1B1nP1/R1K5  51  60
rnbqkbnr/pppppppp/8/8/3P4/8/PPP1PPPP/RNBQKBNR  14  22
rnbqkbnr/pppppp1p/6p1/8/3P4/8/PPP1PPPP/RNBQKBNR  52  44
rnbqkbnr/pppppp1p/6p1/8/3P4/4P3/PPP2PPP/RNBQKBNR  5  14
rnbqk1nr/ppppppbp/6p1/8/3P4/4P3/PPP2PPP/RNBQKBNR  62  45
rnbqk1nr/ppppppbp/6p1/8/3P4/4PN2/PPP2PPP/RNBQKB1R  12  20
rnbqk1nr/pppp1pbp/4p1p1/8/3P4/4PN2/PPP2PPP/RNBQKB1R  57  42
rnbqk1nr/pppp1pbp/4p1p1/8/3P4/2N1PN2/PPP2PPP/R1BQKB1R  6  12
rnbqk2r/ppppnpbp/4p1p1/8/3P4/2N1PN2/PPP2PPP/R1BQKB1R  42  36
rnbqk2r/ppppnpbp/4p1p1/8/3PN3/4PN2/PPP2PPP/R1BQKB1R  4  6

please see and check 

also thank you @DURGESH716 for your help but it doesn't work for me in this case

**Comment by DURGESH716** [comment]
Ok !!! For specifically `model.fit` try the below steps:
1) Make sure that the data in the out.txt file is properly formatted and contains the correct information that you expect.
2) Check that the hyperparameters such as EPOCHS and STEPS_PER_EPOCH are set to appropriate values.
3) Print out the shapes of the data inputs and outputs to make sure they are correct.
4) If you are encountering an error, look at the error message and traceback to try to identify what the problem is.
5) You may also want to consider using TensorBoard to visualize the model's performance and check for any signs of overfitting or underfitting.

**Comment by DURGESH716** [comment]
Try these and update me

**Comment by smarthmaster** [comment]
yeah, actually the dataset was not in correct format also can you help because it takes hours for 500000lines of data to be processed on my laptop with intel i5 with average speed of 2.12ghz. is there a workaround for this

**Comment by DURGESH716** [comment]
Definitely you can use Google Colab for the same

**Comment by smarthmaster** [comment]
it is also slow

**Comment by gaikwadrahul8** [comment]
Hi, @DURGESH716  Thank you for your pointers 

Hi, @smarthmaster 
Apologize for the delay and as you confirmed there was issue with dataset format and sometimes `IndexError: list index out of range`error occurs due to training and testing dataset shapes are not in correct format so sometimes you have to do reshape operation to make those in correct format and also sometimes it happens due to `model.fit()` hyperparameters like `epochs` and `steps_per_epoch` values and you can refer our official documentation for `model.fit()` arguments with expected values [here](https://www.tensorflow.org/api_docs/python/tf/keras/Model#fit)

If you're looking to train your 5,00,000 lines of data then you can train on Google Colab with GPU setting by changing runtime to GPU and even you can go with Google Cloud platform option where you'll get $300 credit with new account but you'll have to add billing account details(Credit card) and make sure that you don't cross Free $300 limit or else it will deducted from your credit card. For your reference I have added one good [reference](https://medium.com/google-cloud/how-to-run-deep-learning-models-on-google-cloud-platform-in-6-steps-4950a57acfa5) which will help to do training on GCP if you wish 

If you need any further assistance please let us know or Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!

**Comment by smarthmaster** [comment]
no thank you
