### ISSUE TITLE
Tensorflow ROCm - Faceswap - Anaconda Enviroment

### ISSUE THREAD

**Issue by linuxreitt** [tensorflow/tensorflow#59601]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tensorflow-rocm 2.10.1.540 / tensorflow 2.2.3

### Custom Code

Yes

### OS Platform and Distribution

Linux PikaOS 22.10

### Python version

3.8.16

### GPU model and memory

AMD RX6800XT

### Current Behaviour?

```shell
Installed faceswap in anaconda enviroment and then ran the gui as below.

$ python faceswap.py gui
Setting Faceswap backend to ROCM
02/07/2023 22:26:06 INFO     Log level set to: INFO
02/07/2023 22:26:06 ERROR    There was an error importing Tensorflow. This is most likely because you do not have TensorFlow installed, or you are trying to run tensorflow-gpu on a system without an Nvidia graphics card. Original import error: Traceback (most recent call last):
02/07/2023 22:26:06 ERROR      File "/home/michael/anaconda3/envs/Faceswap-ROCm/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 62, in <module>
02/07/2023 22:26:06 ERROR        from tensorflow.python._pywrap_tensorflow_internal import *
02/07/2023 22:26:06 ERROR    ImportError: librccl.so.1: cannot open shared object file: No such file or directory
02/07/2023 22:26:06 ERROR    
02/07/2023 22:26:06 ERROR    
02/07/2023 22:26:06 ERROR    Failed to load the native TensorFlow runtime.
02/07/2023 22:26:06 ERROR    See https://www.tensorflow.org/install/errors for some common causes and solutions.
02/07/2023 22:26:06 ERROR    If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.
```

### Standalone code to reproduce the issue

```shell
python faceswap.py gui
```

### Relevant log output

```shell
cat <<EOF > /tmp/check_os.py
import platform
print("""os: %s
os kernel version: %s
os release version: %s
os platform: %s
linux distribution: %s
echo "cat ${OUTPUT_FILE}"ate the fields in the github issue template." of that file."e" >> ${OUTPUT_FILE}E}
Collecting system information...
Traceback (most recent call last):
  File "/tmp/check_os.py", line 17, in <module>
    platform.linux_distribution(),
AttributeError: module 'platform' has no attribute 'linux_distribution'
2023-02-07 22:30:47.806461: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 AVX_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/home/michael/anaconda3/envs/Faceswap-ROCm/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: librccl.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/check_tf.py", line 1, in <module>
    import tensorflow as tf;
  File "/home/michael/anaconda3/envs/Faceswap-ROCm/lib/python3.8/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/michael/anaconda3/envs/Faceswap-ROCm/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 36, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/home/michael/anaconda3/envs/Faceswap-ROCm/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 77, in <module>
    raise ImportError(
ImportError: Traceback (most recent call last):
  File "/home/michael/anaconda3/envs/Faceswap-ROCm/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: librccl.so.1: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors for some common causes and solutions.
If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.
Command 'bazel' not found, but can be installed with:
sudo apt install bazel-bootstrap
Wrote environment to tf_env.txt. You can review the contents of that file.
and use it to populate the fields in the github issue template.

cat tf_env.txt
```
</details>

**Comment by sushreebarsa** [comment]
@linuxreitt Could you please make sure to check this tested build configuration as mentioned [here](https://www.tensorflow.org/install/source#tested_build_configurations) and use the latest TF version.
Thank you!
