### ISSUE TITLE
[tensorflow_datasets 3.1.0]: ValueError(_NAME_STR_ERR.format(name_str)) when loading huggingface dataset

### ISSUE THREAD

**Issue by YuliyaPylypiv** [tensorflow/tensorflow#59622]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

binary

### Tensorflow Version

2.11.0

### Custom Code

No

### OS Platform and Distribution

macOS

### Python version

3.8, 3.9, 3.10

### Current Behaviour?

```shell
ValueError(_NAME_STR_ERR.format(name_str)) when loading huggingface dataset via tensorflow_datasets.load()
```

### Standalone code to reproduce the issue

```shell
import tensorflow_datasets
data = tensorflow_datasets.load('huggingface:glue/mrpc')
```

### Relevant log output

```shell
pip show tensorflow_datasets 
Name: tensorflow-datasets
Version: 3.1.0
Summary: tensorflow/datasets is a library of datasets ready to use with TensorFlow.
Home-page: https://github.com/tensorflow/datasets
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/local/conda/envs/tf_base/lib/python3.8/site-packages/tensorflow_datasets/core/api_utils.py", line 69, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "/Users/local/conda/envs/tf_base/lib/python3.8/site-packages/tensorflow_datasets/core/registered.py", line 356, in load
    name, name_builder_kwargs = _dataset_name_and_kwargs_from_name_str(name)
  File "/Users/local/conda/envs/tf_base/lib/python3.8/site-packages/tensorflow_datasets/core/registered.py", line 391, in _dataset_name_and_kwargs_from_name_str
    raise ValueError(_NAME_STR_ERR.format(name_str))
ValueError: Parsing builder name string huggingface:glue/mrpc failed.
The builder name string must be of the following format:
  dataset_name[/config_name][:version][/kwargs]

  Where:

    * dataset_name and config_name are string following python variable naming.
    * version is of the form x.y.z where {x,y,z} can be any digit or *.
    * kwargs is a comma list separated of arguments and values to pass to
      builder.

  Examples:
    my_dataset
    my_dataset:1.2.*
    my_dataset/config1
    my_dataset/config1:1.*.*
    my_dataset/config1/arg1=val1,arg2=val2
    my_dataset/config1:1.2.3/right=True,foo=bar,rate=1.2
```
</details>

**Comment by YuliyaPylypiv** [comment]
Closing, tensorflow_datasets 3.1.0 is too old
