### ISSUE TITLE
Image Recognition: No route to host when run classify_image.py

### ISSUE THREAD

**Issue by universewill** [tensorflow/tensorflow#5962]
I read this tutorial: https://www.tensorflow.org/versions/r0.12/tutorials/image_recognition/index.html

I encountered IOError when run 'python classify_image.py' in terminal.
It seems that i can not get access to 'http://download.tensorflow.org'.
Also i get access denied when use chrome to browse 'http://download.tensorflow.org'
How can i execute the inception-v3 example correctly?

The error is as follow:

> ➜  imagenet git:(master) ✗ python classify_image.py
Traceback (most recent call last):
  File "classify_image.py", line 227, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/Users/universe/Program/conda/anaconda/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "classify_image.py", line 190, in main
    maybe_download_and_extract()
  File "classify_image.py", line 182, in maybe_download_and_extract
    filepath, _ = urllib.request.urlretrieve(DATA_URL, filepath, _progress)
  File "/Users/universe/Program/conda/anaconda/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/Users/universe/Program/conda/anaconda/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/Users/universe/Program/conda/anaconda/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/Users/universe/Program/conda/anaconda/lib/python2.7/urllib.py", line 350, in open_http
    h.endheaders(data)
  File "/Users/universe/Program/conda/anaconda/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/Users/universe/Program/conda/anaconda/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/Users/universe/Program/conda/anaconda/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/Users/universe/Program/conda/anaconda/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/Users/universe/Program/conda/anaconda/lib/python2.7/socket.py", line 575, in create_connection
    raise err
IOError: [Errno socket error] [Errno 65] No route to host

**Comment by universewill** [comment]
I reinstall tensorflow using pip, but the problem still exists

**Comment by universewill** [comment]
I modified the '/etc/hosts' file and the problem is solved
