### ISSUE TITLE
flatc Errno 8 Exec format error when building for android

### ISSUE THREAD

**Issue by turgut-baba** [tensorflow/tensorflow#59666]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

2.12

### Custom Code

Yes

### OS Platform and Distribution

Debian 11 

### Mobile device

Android 

### Python version

3.9.2

### Bazel version

6.0.0

### GCC/Compiler version

10.2.1

### GPU model and memory

nvidia 

### Current Behaviour?

```shell
I have a c++ code base that can be used on different applications with different UI's. Currently I've run the Build with CMake example on the documentation and it worked on my linux debian machine. However I want to build tflite for android devices too so I tried the "Specifics of Android cross-compilation" part with NDK 25.0.8775105 as my path provided. It eventually did finish the cmake run.
```

### Standalone code to reproduce the issue

```shell
After that I've tried running `cmake --build .` which caused me to get an error regarding `OSError: [Errno 8] Exec format error:` I can see that it's trying to find something like `#!/bin/sh` but I cannot add it since flatc is produced and deleted during the cmake run.
```

### Relevant log output

```shell
[ 21%] Built target flathash
[ 21%] Linking CXX executable flatc
Running scripts/generate_code.py...
Traceback (most recent call last):
  File "/home/tb/Desktop/tensorflow/tflite_android_build/flatbuffers/scripts/generate_code.py", line 148, in <module>
    flatc(
  File "/home/tb/Desktop/tensorflow/tflite_android_build/flatbuffers/scripts/generate_code.py", line 82, in flatc
    result = subprocess.run(cmd, cwd=str(cwd), check=True)
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/tb/Desktop/tensorflow/tflite_android_build/_deps/flatbuffers-build/flatc'
gmake[2]: *** [_deps/flatbuffers-build/CMakeFiles/flatc.dir/build.make:540: _deps/flatbuffers-build/flatc] Error 1
gmake[2]: *** Deleting file '_deps/flatbuffers-build/flatc'
gmake[1]: *** [CMakeFiles/Makefile2:4987: _deps/flatbuffers-build/CMakeFiles/flatc.dir/all] Error 2
gmake: *** [Makefile:149: all] Error 2
```
</details>

**Comment by synandi** [comment]
Hi @turgut-baba, Please find the latest official pre release of TF v2.12 [here](https://github.com/tensorflow/tensorflow/tree/v2.12.0-rc0) and confirm if you are trying with the same source. Thank you!

**Comment by turgut-baba** [comment]
When opening the issue, the steps I've provided was from the r2.11 branch
(git cehckout r2.11) mostly, I've switched to r2.12 at some point but I
will try to do it with the latest release you've provided and will inform
you on the results.

**Comment by turgut-baba** [comment]
When I've tried to run `bazel build -c opt --config=elinux_aarch64
//tensorflow/lite:libtensorflowlite.so --fat_apk_cpu=arm64-v8a` on the
branch you've provided, I got this error on compilation:
```
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=211
INFO: Reading rc options for 'build' from
/home/tb/Desktop/tensorflow/tensorflow_src/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from
/home/tb/Desktop/tensorflow/tensorflow_src/.bazelrc:
  'build' options: --define framework_shared_object=true --define
tsl_protobuf_header_only=true --define=use_fast_cpp_protos=true
--define=allow_oversize_protos=true --spawn_strategy=standalone -c opt
--announce_rc --define=grpc_no_ares=true
--noincompatible_remove_legacy_whole_archive
--enable_platform_specific_config --define=with_xla_support=true
--config=short_logs --config=v2 --define=no_aws_support=true
--define=no_hdfs_support=true --experimental_cc_shared_library
--experimental_link_static_libraries_once=false
--incompatible_enforce_config_setting_visibility
--deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/ir,tensorflow/compiler/mlir/tfrt/tests/analysis,tensorflow/compiler/mlir/tfrt/tests/jit,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_tfrt,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_jitrt,tensorflow/compiler/mlir/tfrt/tests/tf_to_corert,tensorflow/compiler/mlir/tfrt/tests/tf_to_tfrt_data,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/graph_executor,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
INFO: Found applicable config definition build:short_logs in file
/home/tb/Desktop/tensorflow/tensorflow_src/.bazelrc:
--output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file
/home/tb/Desktop/tensorflow/tensorflow_src/.bazelrc:
--define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:elinux_aarch64 in file
/home/tb/Desktop/tensorflow/tensorflow_src/.bazelrc: --config=elinux
--cpu=aarch64 --distinct_host_configuration=true
INFO: Found applicable config definition build:elinux in file
/home/tb/Desktop/tensorflow/tensorflow_src/.bazelrc:
***@***.***_config_embedded_arm//:toolchain
***@***.***_tools//tools/cpp:toolchain
INFO: Found applicable config definition build:linux in file
/home/tb/Desktop/tensorflow/tensorflow_src/.bazelrc: --host_copt=-w
--copt=-Wno-all --copt=-Wno-extra --copt=-Wno-deprecated
--copt=-Wno-deprecated-declarations --copt=-Wno-ignored-attributes
--copt=-Wno-array-bounds --copt=-Wunused-result
--copt=-Werror=unused-result --copt=-Wswitch --copt=-Werror=switch
--copt=-Wno-error=unused-but-set-variable --define=PREFIX=/usr
--define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include
--define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++17
--host_cxxopt=-std=c++17 --config=dynamic_kernels
--distinct_host_configuration=false
--experimental_guard_against_concurrent_changes
INFO: Found applicable config definition build:dynamic_kernels in file
/home/tb/Desktop/tensorflow/tensorflow_src/.bazelrc:
--define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
INFO: Analyzed target //tensorflow/lite:libtensorflowlite.so (0 packages
loaded, 0 targets configured).
INFO: Found 1 target...
ERROR:
/home/tb/Desktop/tensorflow/tensorflow_src/tensorflow/lite/kernels/BUILD:737:11:
Compiling tensorflow/lite/kernels/rfft2d.cc failed: (Exit 1):
aarch64-none-linux-gnu-gcc failed: error executing command (from target
//tensorflow/lite/kernels:builtin_op_kernels)
/home/tb/.cache/bazel/_bazel_tb/f8bd8a53c316ccb93548129bbd0ade7a/external/aarch64_linux_toolchain/bin/aarch64-none-linux-gnu-gcc
-fstack-protector -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections ...
(remaining 165 arguments skipped)
In file included from
/home/tb/.cache/bazel/_bazel_tb/f8bd8a53c316ccb93548129bbd0ade7a/external/aarch64_linux_toolchain/aarch64-none-linux-gnu/include/c++/11.3.1/bits/specfun.h:46,
                 from
/home/tb/.cache/bazel/_bazel_tb/f8bd8a53c316ccb93548129bbd0ade7a/external/aarch64_linux_toolchain/aarch64-none-linux-gnu/include/c++/11.3.1/cmath:1935,
                 from
/home/tb/.cache/bazel/_bazel_tb/f8bd8a53c316ccb93548129bbd0ade7a/external/aarch64_linux_toolchain/aarch64-none-linux-gnu/include/c++/11.3.1/math.h:36,
                 from tensorflow/lite/kernels/rfft2d.cc:16:
/home/tb/.cache/bazel/_bazel_tb/f8bd8a53c316ccb93548129bbd0ade7a/external/aarch64_linux_toolchain/aarch64-none-linux-gnu/include/c++/11.3.1/limits:1673:7:
internal compiler error: Illegal instruction
 1673 |       min() _GLIBCXX_USE_NOEXCEPT { return __FLT_MIN__; }
      |       ^~~
0x7f77d6d9dd5f ???
./signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://bugs.linaro.org/> for instructions.
ERROR:
/home/tb/Desktop/tensorflow/tensorflow_src/tensorflow/lite/BUILD:717:11:
Compiling tensorflow/lite/optional_debug_tools.cc failed: (Exit 1):
aarch64-none-linux-gnu-gcc failed: error executing command (from target
//tensorflow/lite:optional_debug_tools)
/home/tb/.cache/bazel/_bazel_tb/f8bd8a53c316ccb93548129bbd0ade7a/external/aarch64_linux_toolchain/bin/aarch64-none-linux-gnu-gcc
-fstack-protector -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections ...
(remaining 71 arguments skipped)
In file included from
/home/tb/.cache/bazel/_bazel_tb/f8bd8a53c316ccb93548129bbd0ade7a/external/aarch64_linux_toolchain/aarch64-none-linux-gnu/include/c++/11.3.1/bits/specfun.h:46,
                 from
/home/tb/.cache/bazel/_bazel_tb/f8bd8a53c316ccb93548129bbd0ade7a/external/aarch64_linux_toolchain/aarch64-none-linux-gnu/include/c++/11.3.1/cmath:1935,
                 from
/home/tb/.cache/bazel/_bazel_tb/f8bd8a53c316ccb93548129bbd0ade7a/external/aarch64_linux_toolchain/aarch64-none-linux-gnu/include/c++/11.3.1/complex:44,
                 from ./tensorflow/lite/core/interpreter.h:32,
                 from ./tensorflow/lite/optional_debug_tools.h:22,
                 from tensorflow/lite/optional_debug_tools.cc:15:
/home/tb/.cache/bazel/_bazel_tb/f8bd8a53c316ccb93548129bbd0ade7a/external/aarch64_linux_toolchain/aarch64-none-linux-gnu/include/c++/11.3.1/limits:1673:7:
internal compiler error: Illegal instruction
 1673 |       min() _GLIBCXX_USE_NOEXCEPT { return __FLT_MIN__; }
      |       ^~~
0x7f80b425fd5f ???
./signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://bugs.linaro.org/> for instructions.
Target //tensorflow/lite:libtensorflowlite.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.296s, Critical Path: 0.85s
INFO: 9 processes: 9 internal.
ERROR: Build did NOT complete successfully
```

**Comment by turgut-baba** [comment]
Update: apparently I've  forgot to run `./configure`, however I still got
an error after running (Reminder: I still cant configure ./WORKSPACE):
```
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=211
INFO: Reading rc options for 'build' from
/home/tb/Desktop/tensorflow/tensorflow_src/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from
/home/tb/Desktop/tensorflow/tensorflow_src/.bazelrc:
  'build' options: --define framework_shared_object=true --define
tsl_protobuf_header_only=true --define=use_fast_cpp_protos=true
--define=allow_oversize_protos=true --spawn_strategy=standalone -c opt
--announce_rc --define=grpc_no_ares=true
--noincompatible_remove_legacy_whole_archive
--enable_platform_specific_config --define=with_xla_support=true
--config=short_logs --config=v2 --define=no_aws_support=true
--define=no_hdfs_support=true --experimental_cc_shared_library
--experimental_link_static_libraries_once=false
--incompatible_enforce_config_setting_visibility
INFO: Reading rc options for 'build' from
/home/tb/Desktop/tensorflow/tensorflow_src/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python3
--action_env PYTHON_LIB_PATH=/usr/lib/python3/dist-packages
--python_path=/usr/bin/python3
INFO: Reading rc options for 'build' from
/home/tb/Desktop/tensorflow/tensorflow_src/.bazelrc:
  'build' options:
--deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/ir,tensorflow/compiler/mlir/tfrt/tests/analysis,tensorflow/compiler/mlir/tfrt/tests/jit,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_tfrt,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_jitrt,tensorflow/compiler/mlir/tfrt/tests/tf_to_corert,tensorflow/compiler/mlir/tfrt/tests/tf_to_tfrt_data,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/graph_executor,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
INFO: Found applicable config definition build:short_logs in file
/home/tb/Desktop/tensorflow/tensorflow_src/.bazelrc:
--output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file
/home/tb/Desktop/tensorflow/tensorflow_src/.bazelrc:
--define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:elinux_aarch64 in file
/home/tb/Desktop/tensorflow/tensorflow_src/.bazelrc: --config=elinux
--cpu=aarch64 --distinct_host_configuration=true
INFO: Found applicable config definition build:elinux in file
/home/tb/Desktop/tensorflow/tensorflow_src/.bazelrc:
***@***.***_config_embedded_arm//:toolchain
***@***.***_tools//tools/cpp:toolchain
INFO: Found applicable config definition build:linux in file
/home/tb/Desktop/tensorflow/tensorflow_src/.bazelrc: --host_copt=-w
--copt=-Wno-all --copt=-Wno-extra --copt=-Wno-deprecated
--copt=-Wno-deprecated-declarations --copt=-Wno-ignored-attributes
--copt=-Wno-array-bounds --copt=-Wunused-result
--copt=-Werror=unused-result --copt=-Wswitch --copt=-Werror=switch
--copt=-Wno-error=unused-but-set-variable --define=PREFIX=/usr
--define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include
--define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++17
--host_cxxopt=-std=c++17 --config=dynamic_kernels
--distinct_host_configuration=false
--experimental_guard_against_concurrent_changes
INFO: Found applicable config definition build:dynamic_kernels in file
/home/tb/Desktop/tensorflow/tensorflow_src/.bazelrc:
--define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
INFO: Build options --action_env and --python_path have changed, discarding
analysis cache.
INFO: Analyzed target //tensorflow/lite:libtensorflowlite.so (88 packages
loaded, 10692 targets configured).
INFO: Found 1 target...
ERROR:
/home/tb/.cache/bazel/_bazel_tb/f8bd8a53c316ccb93548129bbd0ade7a/external/XNNPACK/BUILD.bazel:5212:19:
Compiling src/operator-utils.c failed: (Exit 1): aarch64-none-linux-gnu-gcc
failed: error executing command (from target @XNNPACK//:operator_utils)
/home/tb/.cache/bazel/_bazel_tb/f8bd8a53c316ccb93548129bbd0ade7a/external/aarch64_linux_toolchain/bin/aarch64-none-linux-gnu-gcc
-fstack-protector -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections ...
(remaining 77 arguments skipped)
In file included from external/XNNPACK/src/operator-utils.c:12:
external/XNNPACK/src/xnnpack/math.h: In function 'min':
external/XNNPACK/src/xnnpack/math.h:35:3: internal compiler error: Illegal
instruction
   35 |   return XNN_UNPREDICTABLE(b < a) ? b : a;
      |   ^~~~~~
0x7f033ebc9d5f ???
./signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
0x7f033ebb4d09 __libc_start_main
../csu/libc-start.c:308
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://bugs.linaro.org/> for instructions.
Target //tensorflow/lite:libtensorflowlite.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 4.524s, Critical Path: 0.25s
INFO: 16 processes: 10 internal, 6 local.
ERROR: Build did NOT complete successfully
```

**Comment by turgut-baba** [comment]
Rest of the methods I've tried, including the `cmake with amd` method, gave
similar results on the branch you've provided.

**Comment by turgut-baba** [comment]
I've deleted all the files, git clone again, checkout to the branch you linked, did everything the same, same result.

**Comment by synandi** [comment]
Thank you for the update @turgut-baba. It seems like we have to dig more into this issue, we will update soon here. Thanks!

**Comment by turgut-baba** [comment]
Also, I've opened another issue tackling more stuff I've tried: https://github.com/tensorflow/tensorflow/issues/59692

**Comment by gaikwadrahul8** [comment]
Hi, @pjpratik 

Could you please look into this issue ?

**Comment by pjpratik** [comment]
Hi @turgut-baba, sorry for delayed response.

As suggested [here](https://github.com/tensorflow/tensorflow/issues/59692#issuecomment-1451090438), can you please build on latest stable branch 2.11 and let us know if the issue still persists.

Thanks.
