### ISSUE TITLE
tensorflow js 4.2.0 version with Vue3 about version dependency problem

### ISSUE THREAD

**Issue by myplc** [tensorflow/tensorflow#59676]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

4.2.0

### Custom Code

Yes

### OS Platform and Distribution

windows10

### Python version

2.7 and 3.9

### GPU model and memory

4G

### Current Behaviour?

```shell
Uncaught (in promise) TypeError: (0 , _environment__WEBPACK_IMPORTED_MODULE_6__.env)(...).platform.isTypedArray is not a function
    at isTypedArray (util.js:194:71)
    at inferShape (tensor_util_env.js:38:58)
    at Module.tensor (tensor.js:193:85)
    at tfex (tfjs.js:27:66)
    at Proxy.get (index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/components/tf1.vue?vue&type=script&lang=js:33:60)
    at onClick._cache.<computed>._cache.<computed> (index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/templateLoader.js??ruleSet[1].rules[3]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/components/tf1.vue?vue&type=template&id=4498369f:21:59)
    at callWithErrorHandling (runtime-core.esm-bundler.js:290:18)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:298:17)
    at HTMLButtonElement.invoker (runtime-dom.esm-bundler.js:473:82)
```

### Standalone code to reproduce the issue

```shell
In version 4.2.0 it doesn't run when importing to vue3.

after suffering
I found that downgrading the version fixed the problem.
4.1.0 and below no problem.
```

### Relevant log output

_No response_</details>

**Comment by synandi** [comment]
@myplc,
Could you please post this issue in [tensorflow/tfjs](https://github.com/tensorflow/tfjs/issues) repo to get the right help there?
Thanks!
