### ISSUE TITLE
fused_batch_norm throws ValueError for partially known 2D-Tensor

### ISSUE THREAD

**Issue by abred** [tensorflow/tensorflow#5988]
I'm trying to use the new fused_batch_norm layer (as I also have this problem #3290)
Using it for 4D Tensors works fine so far (as in: it doens't crash)
However, when using 2D Tensors ([None, X]) I get this error:

> Traceback (most recent call last):
...
  File "/home/userName/.local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 177, in func_with_args
    return func(*args, **current_args)
  File "/home/userName/.local/lib/python2.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 467, in batch_norm
    scope=scope)
  File "/home/userName/.local/lib/python2.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 350, in _fused_batch_norm
    outputs = array_ops.reshape(outputs, original_shape)
  File "/home/userName/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2448, in reshape
    name=name)
  File "/home/userName/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 503, in apply_op
    as_ref=input_arg.is_ref).dtype.name
  File "/home/userName/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 669, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/userName/.local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 194, in _tensor_shape_tensor_conversion_function
    "Cannot convert a partially known TensorShape to a Tensor: %s" % s)
ValueError: Cannot convert a partially known TensorShape to a Tensor: (?, 256)

Same code works for the normal batch_norm layer.
Also works if I reshape it manually to [None, 1, 1, X] before calling fused_batch_norm

Cuda 8.0, cuDNN 5.1, tf r0.12

**Comment by zhangyaobit** [comment]
@abred, thanks for reporting the issue. Could you give a minimum example that reproduces the error? Is the first dimension of the 2D Tensor known? Could you set its shape to a complete shape, rather than a partially known shape (that is what is being complained)? Could you also share the code snippet of your manual reshape? I am curious why your manual reshape succeeded without complaining about partial shape info, while the internal reshape failed.

**Comment by abred** [comment]
here is a small example:
https://gist.github.com/abred/daf06a496ebb585212529b7c0ecbad02

the first dimension of the 2D Tensor is not known (None/-1)
when I change it to a fixed number it works.
I included the reshapes in the code snippet (def batch_norm), so when you run it as-is it should work (comment the if..reshapes to get the error)

**Comment by abred** [comment]
still occurring with 0.12.1

**Comment by zhangyaobit** [comment]
This issue has been resolved with the two commits below:

https://github.com/tensorflow/tensorflow/commits?author=zhangyaobit&since=2017-03-17T07:00:00Z&until=2017-03-18T07:00:00Z
