### ISSUE TITLE
RuntimeError for minimal RNNCell example

### ISSUE THREAD

**Issue by lobachevzky** [tensorflow/tensorflow#5989]
I am just trying to get a simple RNNCell to work. This simple code:

    with tf.Session() as sess:
        x = tf.Variable(np.ones((2, 3)))
        tf.global_variables_initializer().run()
        out, state = BasicRNNCell(4)(x, x)

Throws the following error:

    /Users/ethan/env/bin/python /Users/ethan/tf-bug/main.py
    Traceback (most recent call last):
      File "/Users/ethan/tf-bug/main.py", line 8, in <module>
        out, state = BasicRNNCell(4)(x, x)
      File "/Users/ethan/env/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell.py", line 200, in __call__
        output = self._activation(_linear([inputs, state], self._num_units, True))
      File "/Users/ethan/env/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell.py", line 905, in _linear
        "Matrix", [total_arg_size, output_size], dtype=dtype)
      File "/Users/ethan/env/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1024, in get_variable
        custom_getter=custom_getter)
      File "/Users/ethan/env/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 850, in get_variable
        custom_getter=custom_getter)
      File "/Users/ethan/env/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 346, in get_variable
        validate_shape=validate_shape)
      File "/Users/ethan/env/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 331, in _true_getter
        caching_device=caching_device, validate_shape=validate_shape)
      File "/Users/ethan/env/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 677, in _get_single_variable
        expected_shape=shape)
      File "/Users/ethan/env/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 224, in __init__
        expected_shape=expected_shape)
      File "/Users/ethan/env/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 327, in _init_from_args
        initial_value(), name="initial_value", dtype=dtype)
      File "/Users/ethan/env/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 665, in <lambda>
        shape.as_list(), dtype=dtype, partition_info=partition_info)
      File "/Users/ethan/env/lib/python2.7/site-packages/tensorflow/python/ops/init_ops.py", line 284, in _initializer
        dtype, seed=seed)
      File "/Users/ethan/env/lib/python2.7/site-packages/tensorflow/python/ops/random_ops.py", line 231, in random_uniform
        minval = ops.convert_to_tensor(minval, dtype=dtype, name="min")
      File "/Users/ethan/env/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 683, in convert_to_tensor
        dtype.name, ret.dtype.name))
    RuntimeError: min: Conversion function <function _constant_tensor_conversion_function at 0x10cb461b8> for type <type 'object'> returned incompatible dtype: requested = float64_ref, actual = float64

    Process finished with exit code 1

This is the output of `pip show tensorflow`:

 > Name: tensorflow
 > Version: 0.12.0rc0
 > Summary: TensorFlow helps the tensors flow
 > Home-page: http://tensorflow.org/
 > Author: Google Inc.
 > Author-email: opensource@google.com
 > License: Apache 2.0
 > Location: /Users/ethan/env/lib/python2.7/site-packages
 > Requires: numpy, mock, wheel, six, protobuf

Thanks!

**Comment by tfboyd** [comment]
Automatically closing due to lack of recent activity. We hope that you were able to resolve it on your own. However, since this is a support issue rather than a bug or feature request, you will probably get more information by posting it on StackOverflow.

**Comment by zwep** [comment]
Facing the same issue here... anyone else has this same problem?

**Comment by ebrevdo** [comment]
Try passing x through tf.identity:

x = tf.identity(x)

Before passing to the rnn.
