### ISSUE TITLE
//tensorflow/python/kernel_tests/proto:decode_proto_op_test fails with protobuf > 3.20.3

### ISSUE THREAD

**Issue by elfringham** [tensorflow/tensorflow#59930]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

git HEAD

### Custom Code

No

### OS Platform and Distribution

Ubuntu 20.04

### Mobile device

n/a

### Python version

3.9.16

### Bazel version

5.3.0

### GCC/Compiler version

9.4.0

### CUDA/cuDNN version

n/a

### GPU model and memory

n/a

### Current Behaviour?

```shell
The test fails
```

### Standalone code to reproduce the issue

```shell
bazel test --test_timeout=300,500,-1,-1 --flaky_test_attempts=3 --test_output=all --cache_test_results=no --noremote_accept_cached --test_env=TF_ENABLE_ONEDNN_OPTS=1 --build_tag_filters=-no_oss,-oss_serial,-gpu,-tpu,-benchmark-test,-v1only,-requires-gpu --test_tag_filters=-no_oss,-oss_serial,-gpu,-tpu,-benchmark-test,-v1only,-requires-gpu --verbose_failures --build_tests_only --jobs=16 -- //tensorflow/python/kernel_tests/proto:decode_proto_op_test
```

### Relevant log output

```shell
ERROR: testBinaryDisordereddefaults (__main__.DecodeProtoOpTest)
DecodeProtoOpTest.testBinaryDisordereddefaults
testBinaryDisordereddefaults(values {
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/e953b164f58eb4c9598ad736d787ff39/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/proto/decode_proto_op_test.runfiles/absl_py/absl/testing/parameterized.py", line 316, in bound_param_test
    return test_method(self, *testcase_params)
  File "/root/.cache/bazel/_bazel_root/e953b164f58eb4c9598ad736d787ff39/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/proto/decode_proto_op_test.runfiles/org_tensorflow/tensorflow/python/kernel_tests/proto/decode_proto_op_test_base.py", line 223, in testBinaryDisordered
    self._runDecodeProtoTests(
  File "/root/.cache/bazel/_bazel_root/e953b164f58eb4c9598ad736d787ff39/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/proto/decode_proto_op_test.runfiles/org_tensorflow/tensorflow/python/kernel_tests/proto/decode_proto_op_test_base.py", line 206, in _runDecodeProtoTests
    self._compareProtos(batch_shape, sizes, fields, field_dict)
  File "/root/.cache/bazel/_bazel_root/e953b164f58eb4c9598ad736d787ff39/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/proto/decode_proto_op_test.runfiles/org_tensorflow/tensorflow/python/kernel_tests/proto/decode_proto_op_test_base.py", line 142, in _compareProtos
    self._compareValues(fd, values.flat,
  File "/root/.cache/bazel/_bazel_root/e953b164f58eb4c9598ad736d787ff39/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/proto/decode_proto_op_test.runfiles/org_tensorflow/tensorflow/python/kernel_tests/proto/decode_proto_op_test_base.py", line 57, in _compareValues
    if fd.cpp_type == fd.CPPTYPE_FLOAT:
AttributeError: 'google._upb._message.FieldDescriptor' object has no attribute 'CPPTYPE_FLOAT'
```
</details>

**Comment by gaikwadrahul8** [comment]
Hi, @SuryanarayanaY 

Could you please look into this issue ? Thank you!

**Comment by SuryanarayanaY** [comment]
@elfringham ,

I have replicated the reported test failure and got the same error reported by you.

`AttributeError: 'google._upb._message.FieldDescriptor' object has no attribute 'CPPTYPE_FLOAT'`

Please refer to attached log below and acknowledge.Please note that I used the same bazel environment that used for #59931, in which ticket also reported error replicated.

[59930_logs.txt](https://github.com/tensorflow/tensorflow/files/11007494/59930_logs.txt)

**Comment by elfringham** [comment]
@SuryanarayanaY Yes, that matches the failure I see.

**Comment by SuryanarayanaY** [comment]
CC - @learning-to-play

**Comment by learning-to-play** [comment]
@SuryanarayanaY Please feel free to add @vam-google for issues related to protobuf version mismatch.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
