### ISSUE TITLE
`pip install tensorflow-gpu` gives `setuptools.extern.packaging.requirements.InvalidRequirement`

### ISSUE THREAD

**Issue by SamuelMarks** [tensorflow/tensorflow#60074]
### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

binary

### Tensorflow Version

2.12.0

### Custom Code

No

### OS Platform and Distribution

Ubuntu 22.10

### Python version

Python 3.10.7

### Current Behaviour?

```shell
My GPU [AMD Ryzen™ 9 6900HX with Radeon™ Graphics × 16] wasn't detected on the regular `pip install tensorflow`, StackOverflow told others to `pip install tensorflow-gpu` which gave me:

$ pip install tensorflow-gpu
Collecting tensorflow-gpu
  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [39 lines of output]
      Traceback (most recent call last):
        File "tfenv3/lib/python3.10/site-packages/setuptools/_vendor/packaging/requirements.py", line 35, in __init__
          parsed = parse_requirement(requirement_string)
        File "tfenv3/lib/python3.10/site-packages/setuptools/_vendor/packaging/_parser.py", line 64, in parse_requirement
          return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
        File "tfenv3/lib/python3.10/site-packages/setuptools/_vendor/packaging/_parser.py", line 82, in _parse_requirement
          url, specifier, marker = _parse_requirement_details(tokenizer)
        File "tfenv3/lib/python3.10/site-packages/setuptools/_vendor/packaging/_parser.py", line 126, in _parse_requirement_details
          marker = _parse_requirement_marker(
        File "tfenv3/lib/python3.10/site-packages/setuptools/_vendor/packaging/_parser.py", line 147, in _parse_requirement_marker
          tokenizer.raise_syntax_error(
        File "tfenv3/lib/python3.10/site-packages/setuptools/_vendor/packaging/_tokenizer.py", line 163, in raise_syntax_error
          raise ParserSyntaxError(
      setuptools.extern.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after name and no valid version specifier)
          python_version>"3.7"
                        ^
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-1uf6oamu/tensorflow-gpu_f068f7e6c62d42d8b5619a7789641e46/setup.py", line 40, in <module>
          setuptools.setup()
        File "tfenv3/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
          _install_setup_requires(attrs)
        File "tfenv3/lib/python3.10/site-packages/setuptools/__init__.py", line 78, in _install_setup_requires
          dist.parse_config_files(ignore_option_errors=True)
        File "tfenv3/lib/python3.10/site-packages/setuptools/dist.py", line 887, in parse_config_files
          self._finalize_requires()
        File "tfenv3/lib/python3.10/site-packages/setuptools/dist.py", line 594, in _finalize_requires
          self._move_install_requirements_markers()
        File "tfenv3/lib/python3.10/site-packages/setuptools/dist.py", line 634, in _move_install_requirements_markers
          inst_reqs = list(_reqs.parse(spec_inst_reqs))
        File "tfenv3/lib/python3.10/site-packages/setuptools/_vendor/packaging/requirements.py", line 37, in __init__
          raise InvalidRequirement(str(e)) from e
      setuptools.extern.packaging.requirements.InvalidRequirement: Expected end or semicolon (after name and no valid version specifier)
          python_version>"3.7"
                        ^
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

FYI: Running versions setuptools-67.6.0 wheel-0.40.0 pip-23.0.1
```


### Standalone code to reproduce the issue

```shell
N/A
```

**Comment by wty-yy** [comment]
It seems that tensorflow-gpu is not available for 2.12 - https://pypi.org/project/tensorflow-gpu/
Instead to install tensorflow 2.12, I found it can't detect GPU, cuda, and it can't display the missing files like tensorflow-gpu. 
But tensorflow-gpu 2.10.1 can detect GPU, cuda. It's so confusing.

My cuda version is 11.8

**Comment by tilakrayal** [comment]
@SamuelMarks,
In tensorflow v2.12, removed redundant packages **tensorflow-gpu and tf-nightly-gpu**. These packages were removed and replaced with packages that direct users to switch to **tensorflow or tf-nightly respectively**. 

Please take a look at the official release doc for the reference.
https://github.com/tensorflow/tensorflow/releases

Since TensorFlow 2.1, the only difference between these two sets of packages was their names, so there is no loss of functionality or GPU support. See https://pypi.org/project/tensorflow-gpu for more details.
https://pypi.org/project/tensorflow-gpu/

`Tensorflow-gpu` has been removed. Please install tensorflow instead. The tensorflow package supports GPU accelerated operations via Nvidia CUDA. Thank you!

**Comment by SamuelMarks** [comment]
Ah, ok.

Just to confirm, TensorFlow doesn't support my Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M]?

(I might need to look closer into ROCm)

**Comment by tilakrayal** [comment]
@SamuelMarks,
The **!pip install tensorflow-gpu and tf-nightly-gpu** were removed from tensorflow v2.12. We can directly use **pip install tensorflow** for the gpu.
https://pypi.org/project/tensorflow-gpu/
 Thank you!
