### ISSUE TITLE
Unintuitive error messages when using functions that require a axis parameter

### ISSUE THREAD

**Issue by maexlich** [tensorflow/tensorflow#6008]
Multiple tensorflow functions (I tested tf.argmax,tf.argmin), that require axis parameters to be provided, show very unintuitive error messages if the axis parameter is omitted.

It would probably be more convenient to either throw exceptions earlier with more intuitive error descriptions ('Axis parameter must be passed/must not be None') or to define the axis parameters as a required positional parameters. 

### Environment info
Operating System:
OS X 10.11.6, running with cpu backend

1. A link to the pip package you installed:
https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.0rc0-py3-none-any.whl
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.:
0.12.0-rc0

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
```
import tensorflow as tf
t =tf.get_variable('test', shape=[100])
maxt = tf.argmax(t)
```

### Logs or other output that would be helpful
Exception:
```
Traceback (most recent call last):
  File "/Users/maexlich/.virtualenvs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 490, in apply_op
    preferred_dtype=default_dtype)
  File "/Users/maexlich/.virtualenvs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 669, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Users/maexlich/.virtualenvs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/Users/maexlich/.virtualenvs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/Users/maexlich/.virtualenvs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 360, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/maexlich/.virtualenvs/tensorflow/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-8fd26b27f1ef>", line 1, in <module>
    max = tf.argmax(t)
  File "/Users/maexlich/.virtualenvs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py", line 249, in argmax
    return gen_math_ops.arg_max(input, axis, name)
  File "/Users/maexlich/.virtualenvs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/gen_math_ops.py", line 168, in arg_max
    name=name)
  File "/Users/maexlich/.virtualenvs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 503, in apply_op
    as_ref=input_arg.is_ref).dtype.name
  File "/Users/maexlich/.virtualenvs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 669, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Users/maexlich/.virtualenvs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/Users/maexlich/.virtualenvs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/Users/maexlich/.virtualenvs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 360, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.
```

**Comment by martinwicke** [comment]
@aselle This looks like a bug to me, but you know that code better now, wdyt?

**Comment by aselle** [comment]
Thanks for the issue @maexlich. Unfortunately, the current state of affairs is part of the process of renaming the arguments to be "axis". To support the old argument during deprecation, we have to make axis have a default of None, which is invalid. This code is going to go away, and axis will go back to being required. That will be happening soon, but if it is delayed, I will see if I can do a quick step of throwing exceptions when axis is None in these cases.

**Comment by tfboyd** [comment]
Automatically closing due to lack of recent activity. We hope that you were able to resolve it on your own. However, since this is a support issue rather than a bug or feature request, you will probably get more information by posting it on StackOverflow.
