### ISSUE TITLE
Build failure - stablehlo "File name too long"

### ISSUE THREAD

**Issue by bondhugula** [tensorflow/tensorflow#60126]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

git 1dce1ddd62b4d9f7434bffa347defe0ad286bfab Mar 26

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 22.04.2 LTS

### Python version

3.10.6

### Bazel version

5.3.0

### GCC/Compiler version

11.3.0

### Current Behaviour?

```shell
TF build fails due to an issue with stablehlo integration.

$ bazel build //tensorflow/tools/pip_package:build_pip_package


g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

uday@polymage-gpu-laptop:~/csa/courses/e0255/2023/e0255-asst-2/tensorflow$ bazel build //tensorflow/tools/pip_package:build_pip_package
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=146
INFO: Reading rc options for 'build' from /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/.bazelrc:
  'build' options: --define framework_shared_object=true --define tsl_protobuf_header_only=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library --experimental_link_static_libraries_once=false --incompatible_enforce_config_setting_visibility
INFO: Reading rc options for 'build' from /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env PYTHON_LIB_PATH=/usr/lib/python3/dist-packages --python_path=/usr/bin/python3
INFO: Reading rc options for 'build' from /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/.bazelrc:
  'build' options: --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/ir,tensorflow/compiler/mlir/tfrt/tests/analysis,tensorflow/compiler/mlir/tfrt/tests/jit,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_tfrt,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_jitrt,tensorflow/compiler/mlir/tfrt/tests/tf_to_corert,tensorflow/compiler/mlir/tfrt/tests/tf_to_tfrt_data,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/graph_executor,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
INFO: Found applicable config definition build:short_logs in file /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:linux in file /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/.bazelrc: --host_copt=-w --copt=-Wno-all --copt=-Wno-extra --copt=-Wno-deprecated --copt=-Wno-deprecated-declarations --copt=-Wno-ignored-attributes --copt=-Wno-array-bounds --copt=-Wunused-result --copt=-Werror=unused-result --copt=-Wswitch --copt=-Werror=switch --copt=-Wno-error=unused-but-set-variable --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++17 --host_cxxopt=-std=c++17 --config=dynamic_kernels --experimental_guard_against_concurrent_changes
INFO: Found applicable config definition build:dynamic_kernels in file /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
INFO: Build options --copt and --linkopt have changed, discarding analysis cache.
INFO: Repository stablehlo instantiated at:
  /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/WORKSPACE:15:14: in <toplevel>
  /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/tensorflow/workspace2.bzl:965:28: in workspace
  /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/tensorflow/workspace2.bzl:83:14: in _initialize_third_party
  /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/third_party/stablehlo/workspace.bzl:11:20: in repo
  /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/third_party/repo.bzl:136:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/third_party/repo.bzl:89:35: in <toplevel>
INFO: Repository 'stablehlo' used the following cache hits instead of downloading the corresponding file.
 * Hash '1295d499727ed77e34f8c3c82f7fc68d95ca6044da82579ac9d51b510c5b2cd7' for https://storage.googleapis.com/mirror.tensorflow.org/github.com/openxla/stablehlo/archive/ef7a111784a2a5574de0b1165e3bdfc5397dce5a.zip
If the definition of 'stablehlo' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'stablehlo':
   Traceback (most recent call last):
	File "/home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/third_party/repo.bzl", line 73, column 33, in _tf_http_archive_impl
		ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error extracting /home/uday/.cache/bazel/_bazel_uday/77f8878d03275bdd27457b5be533415a/external/stablehlo/temp12753699981416543916/ef7a111784a2a5574de0b1165e3bdfc5397dce5a.zip to /home/uday/.cache/bazel/_bazel_uday/77f8878d03275bdd27457b5be533415a/external/stablehlo/temp12753699981416543916: /home/uday/.cache/bazel/_bazel_uday/77f8878d03275bdd27457b5be533415a/external/stablehlo/stablehlo/testdata/vmap_dot_general_batch_dimensions_lhs_float32_8_4_3_3_4__rhs_float32_4_8_3_4_2__dimensionnumbers____4_3___3_2_____0_1___1_0_dynamic.mlir.0_9_0.bc (File name too long)
ERROR: /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/WORKSPACE:15:14: fetching _tf_http_archive rule //external:stablehlo: Traceback (most recent call last):
	File "/home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/third_party/repo.bzl", line 73, column 33, in _tf_http_archive_impl
		ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error extracting /home/uday/.cache/bazel/_bazel_uday/77f8878d03275bdd27457b5be533415a/external/stablehlo/temp12753699981416543916/ef7a111784a2a5574de0b1165e3bdfc5397dce5a.zip to /home/uday/.cache/bazel/_bazel_uday/77f8878d03275bdd27457b5be533415a/external/stablehlo/temp12753699981416543916: /home/uday/.cache/bazel/_bazel_uday/77f8878d03275bdd27457b5be533415a/external/stablehlo/stablehlo/testdata/vmap_dot_general_batch_dimensions_lhs_float32_8_4_3_3_4__rhs_float32_4_8_3_4_2__dimensionnumbers____4_3___3_2_____0_1___1_0_dynamic.mlir.0_9_0.bc (File name too long)
ERROR: /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/WORKSPACE:15:14: fetching _tf_http_archive rule //external:stablehlo: Traceback (most recent call last):
	File "/home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/third_party/repo.bzl", line 73, column 33, in _tf_http_archive_impl
		ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error extracting /home/uday/.cache/bazel/_bazel_uday/77f8878d03275bdd27457b5be533415a/external/stablehlo/temp12753699981416543916/ef7a111784a2a5574de0b1165e3bdfc5397dce5a.zip to /home/uday/.cache/bazel/_bazel_uday/77f8878d03275bdd27457b5be533415a/external/stablehlo/temp12753699981416543916: /home/uday/.cache/bazel/_bazel_uday/77f8878d03275bdd27457b5be533415a/external/stablehlo/stablehlo/testdata/vmap_dot_general_batch_dimensions_lhs_float32_8_4_3_3_4__rhs_float32_4_8_3_4_2__dimensionnumbers____4_3___3_2_____0_1___1_0_dynamic.mlir.0_9_0.bc (File name too long)
INFO: Repository icu instantiated at:
  /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/WORKSPACE:15:14: in <toplevel>
  /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/tensorflow/workspace2.bzl:965:28: in workspace
  /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/tensorflow/workspace2.bzl:72:8: in _initialize_third_party
  /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/third_party/icu/workspace.bzl:8:20: in repo
  /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/third_party/repo.bzl:136:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/third_party/repo.bzl:89:35: in <toplevel>
INFO: Repository go_sdk instantiated at:
  /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/WORKSPACE:23:14: in <toplevel>
  /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/tensorflow/workspace0.bzl:135:20: in workspace
  /home/uday/.cache/bazel/_bazel_uday/77f8878d03275bdd27457b5be533415a/external/com_github_grpc_grpc/bazel/grpc_extra_deps.bzl:36:27: in grpc_extra_deps
  /home/uday/.cache/bazel/_bazel_uday/77f8878d03275bdd27457b5be533415a/external/io_bazel_rules_go/go/private/sdk.bzl:431:28: in go_register_toolchains
  /home/uday/.cache/bazel/_bazel_uday/77f8878d03275bdd27457b5be533415a/external/io_bazel_rules_go/go/private/sdk.bzl:130:21: in go_download_sdk
Repository rule _go_download_sdk defined at:
  /home/uday/.cache/bazel/_bazel_uday/77f8878d03275bdd27457b5be533415a/external/io_bazel_rules_go/go/private/sdk.bzl:117:35: in <toplevel>
INFO: Repository XNNPACK instantiated at:
  /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/WORKSPACE:15:14: in <toplevel>
  /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/tensorflow/workspace2.bzl:972:21: in workspace
  /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/tensorflow/workspace2.bzl:144:20: in _tf_repositories
  /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/third_party/repo.bzl:136:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/third_party/repo.bzl:89:35: in <toplevel>
INFO: Repository boringssl instantiated at:
  /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/WORKSPACE:15:14: in <toplevel>
  /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/tensorflow/workspace2.bzl:972:21: in workspace
  /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/tensorflow/workspace2.bzl:565:20: in _tf_repositories
  /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/third_party/repo.bzl:136:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/third_party/repo.bzl:89:35: in <toplevel>
ERROR: /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/tensorflow/tools/pip_package/BUILD:192:10: //tensorflow/tools/pip_package:licenses depends on @stablehlo//:LICENSE in repository @stablehlo which failed to fetch. no such package '@stablehlo//': java.io.IOException: Error extracting /home/uday/.cache/bazel/_bazel_uday/77f8878d03275bdd27457b5be533415a/external/stablehlo/temp12753699981416543916/ef7a111784a2a5574de0b1165e3bdfc5397dce5a.zip to /home/uday/.cache/bazel/_bazel_uday/77f8878d03275bdd27457b5be533415a/external/stablehlo/temp12753699981416543916: /home/uday/.cache/bazel/_bazel_uday/77f8878d03275bdd27457b5be533415a/external/stablehlo/stablehlo/testdata/vmap_dot_general_batch_dimensions_lhs_float32_8_4_3_3_4__rhs_float32_4_8_3_4_2__dimensionnumbers____4_3___3_2_____0_1___1_0_dynamic.mlir.0_9_0.bc (File name too long)
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: 
INFO: Elapsed time: 1.345s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 4299 targets configured)
```

```
$ java --version
openjdk 11.0.18 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)
```
```


### Standalone code to reproduce the issue

```shell
Clone official TF repo at 1dce1ddd62b4d9f7434bffa347defe0ad286bfab (Mar 26):

Use default configure:

$ bazel build //tensorflow/tools/pip_package:build_pip_package
```

### Relevant log output

```
g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

uday@polymage-gpu-laptop:~/csa/courses/e0255/2023/e0255-asst-2/tensorflow$ bazel build //tensorflow/tools/pip_package:build_pip_package
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=146
INFO: Reading rc options for 'build' from /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/.bazelrc:
  'build' options: --define framework_shared_object=true --define tsl_protobuf_header_only=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library --experimental_link_static_libraries_once=false --incompatible_enforce_config_setting_visibility
INFO: Reading rc options for 'build' from /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env PYTHON_LIB_PATH=/usr/lib/python3/dist-packages --python_path=/usr/bin/python3
INFO: Reading rc options for 'build' from /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/.bazelrc:
  'build' options: --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/ir,tensorflow/compiler/mlir/tfrt/tests/analysis,tensorflow/compiler/mlir/tfrt/tests/jit,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_tfrt,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_jitrt,tensorflow/compiler/mlir/tfrt/tests/tf_to_corert,tensorflow/compiler/mlir/tfrt/tests/tf_to_tfrt_data,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/graph_executor,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
INFO: Found applicable config definition build:short_logs in file /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:linux in file /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/.bazelrc: --host_copt=-w --copt=-Wno-all --copt=-Wno-extra --copt=-Wno-deprecated --copt=-Wno-deprecated-declarations --copt=-Wno-ignored-attributes --copt=-Wno-array-bounds --copt=-Wunused-result --copt=-Werror=unused-result --copt=-Wswitch --copt=-Werror=switch --copt=-Wno-error=unused-but-set-variable --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++17 --host_cxxopt=-std=c++17 --config=dynamic_kernels --experimental_guard_against_concurrent_changes
INFO: Found applicable config definition build:dynamic_kernels in file /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
INFO: Build options --copt and --linkopt have changed, discarding analysis cache.
INFO: Repository stablehlo instantiated at:
  /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/WORKSPACE:15:14: in <toplevel>
  /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/tensorflow/workspace2.bzl:965:28: in workspace
  /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/tensorflow/workspace2.bzl:83:14: in _initialize_third_party
  /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/third_party/stablehlo/workspace.bzl:11:20: in repo
  /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/third_party/repo.bzl:136:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/third_party/repo.bzl:89:35: in <toplevel>
INFO: Repository 'stablehlo' used the following cache hits instead of downloading the corresponding file.
 * Hash '1295d499727ed77e34f8c3c82f7fc68d95ca6044da82579ac9d51b510c5b2cd7' for https://storage.googleapis.com/mirror.tensorflow.org/github.com/openxla/stablehlo/archive/ef7a111784a2a5574de0b1165e3bdfc5397dce5a.zip
If the definition of 'stablehlo' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'stablehlo':
   Traceback (most recent call last):
	File "/home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/third_party/repo.bzl", line 73, column 33, in _tf_http_archive_impl
		ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error extracting /home/uday/.cache/bazel/_bazel_uday/77f8878d03275bdd27457b5be533415a/external/stablehlo/temp12753699981416543916/ef7a111784a2a5574de0b1165e3bdfc5397dce5a.zip to /home/uday/.cache/bazel/_bazel_uday/77f8878d03275bdd27457b5be533415a/external/stablehlo/temp12753699981416543916: /home/uday/.cache/bazel/_bazel_uday/77f8878d03275bdd27457b5be533415a/external/stablehlo/stablehlo/testdata/vmap_dot_general_batch_dimensions_lhs_float32_8_4_3_3_4__rhs_float32_4_8_3_4_2__dimensionnumbers____4_3___3_2_____0_1___1_0_dynamic.mlir.0_9_0.bc (File name too long)
ERROR: /home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/WORKSPACE:15:14: fetching _tf_http_archive rule //external:stablehlo: Traceback (most recent call last):
	File "/home/uday/csa/courses/e0255/2023/e0255-asst-2/tensorflow/third_party/repo.bzl", line 73, column 33, in _tf_http_archive_impl
		ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error extracting /home/uday/.cache/bazel/_bazel_uday/77f8878d03275bdd27457b5be533415a/external/stablehlo/temp12753699981416543916/ef7a111784a2a5574de0b1165e3bdfc5397dce5a.zip to /home/uday/.cache/bazel/_bazel_uday/77f8878d03275bdd27457b5be533415a/external/stablehlo/temp12753699981416543916: /home/uday/.cache/bazel/_bazel_uday/77f8878d03275bdd27457b5be533415a/external/stablehlo/stablehlo/testdata/vmap_dot_general_batch_dimensions_lhs_float32_8_4_3_3_4__rhs_float32_4_8_3_4_2__dimensionnumbers____4_3___3_2_____0_1___1_0_dynamic.mlir.0_9_0.bc (File name too long)
```
```
</details>

**Comment by bondhugula** [comment]
CC: @joker-eph

**Comment by joker-eph** [comment]
`/home/uday/.cache/bazel/_bazel_uday/77f8878d03275bdd27457b5be533415a/external/stablehlo/temp12753699981416543916: /home/uday/.cache/bazel/_bazel_uday/77f8878d03275bdd27457b5be533415a/external/stablehlo/stablehlo/testdata/vmap_dot_general_batch_dimensions_lhs_float32_8_4_3_3_4__rhs_float32_4_8_3_4_2__dimensionnumbers____4_3___3_2_____0_1___1_0_dynamic.mlir.0_9_0.bc`

@burmako

**Comment by bondhugula** [comment]
> Hi folks! Thank you for reporting - we'll look into this shortly.
> 
> In the meanwhile, do you happen to know what's the maximum filename length expected here? `/home/uday/.cache/bazel/_bazel_uday/77f8878d03275bdd27457b5be533415a/external/stablehlo/stablehlo/testdata/vmap_dot_general_batch_dimensions_lhs_float32_8_4_3_3_4__rhs_float32_4_8_3_4_2__dimensionnumbers____4_3___3_2_____0_1___1_0_dynamic.mlir.0_9_0.bc` is 252 characters long, and I'm not currently sure if this limit is imposed by Bazel, by Java or by something else.

Although Java is reporting this via an exception, I think it's the OS file system that's imposing the limit -- it might be the 255 byte limit (see https://en.wikipedia.org/wiki/Ext4) that this is exceeding. Can you go with `dims` instead of `dimensions` everywhere in that? I don't know if that'll provide a guarantee though.

**Comment by burmako** [comment]
I've tried to reproduce this on my machine which has the same version of Bazel and of Python, although it runs a different distribution of Linux ([gLinux](https://en.wikipedia.org/wiki/GLinux) rather than Ubuntu - not sure if that matters - although my filesystem is ext4, the same as yours) and unfortunately wasn't able to reproduce the issue.

Fwiw the equivalent path to the problematic file in the Bazel cache on my machine has 275 characters in it, and it seems to work properly. (My home directory is located elsewhere, and the path to that is longer than `/home/$USER`).

Can you tell more about the problem that you're encountering? Did it start happening only recently? Is there anything that could be unusual about the environment, or it's pretty much a stock configuration?

By the way, I'm open to abbreviating the filenames as needed, but would like to debug this a bit further, so that we get this right the first time and make sure this doesn't happen again.

**Comment by bondhugula** [comment]
> I've tried to reproduce this on my machine which has the same version of Bazel and of Python, although it runs a different distribution of Linux ([gLinux](https://en.wikipedia.org/wiki/GLinux) rather than Ubuntu - not sure if that matters - although my filesystem is ext4, the same as yours) and unfortunately wasn't able to reproduce the issue.
> 
> Fwiw the equivalent path to the problematic file in the Bazel cache on my machine has 275 characters in it, and it seems to work properly. (My home directory is located elsewhere, and the path to that is longer than `/home/$USER`).
> 
> Can you tell more about the problem that you're encountering? Did it start happening only recently? Is there anything that could be unusual about the environment, or it's pretty much a stock configuration?
> 
> By the way, I'm open to abbreviating the filenames as needed, but would like to debug this a bit further, so that we get this right the first time and make sure this doesn't happen again.

Even I wasn't able to reproduce this on another Ubuntu 22.04 LTS - so, it looks like there was something different with that environment or the file system configuration. I'll be able to post more details tomorrow.

**Comment by anuth212** [comment]
I'd like to help work on this issue.

**Comment by burmako** [comment]
@anuth212 Thank you for your offer to help! Can you try to reproduce this issue? This is currently an open question - how to reproduce and minimize the bug (because the most straightforward approach of cloning the repo and running Bazel works fine).

**Comment by janpfeifer** [comment]
Just on a related note, I've been trying to build OpenXLA (outside of tensorflow), who also depends on `stablehlo`, and see the same problem during my build:

```
INFO: repository @stablehlo' used the following cache hits instead of downloading the corresponding file.
 * Hash '5f4f2dbba503bc18e1a64c3b87a51b8571519ca18158937e3048c094ae90e548' for https://storage.googleapis.com/mirror.tensorflow.org/github.com/openxla/stablehlo/archive/458bdd95771e9861e6488868e315a1b0340058ba.zip
If the definition of 'repository @stablehlo' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'stablehlo':
   Traceback (most recent call last):
        File "/mnt/.cache/external/xla/third_party/repo.bzl", line 73, column 33, in _tf_http_archive_impl
                ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error extracting /mnt/.cache/external/stablehlo/temp1913717006884866717/458bdd95771e9861e6488868e315a1b0340058ba.zip to /mnt/.cache/external/stablehlo/temp1913717006884866717: /mnt/.cache/external/stablehlo/stablehlo/testdata/vmap_dot_general_batch_dimensions_lhs_float32_8_4_3_3_4__rhs_float32_4_8_3_4_2__dimensionnumbers____4_3___3_2_____0_1___1_0_dynamic.mlir.0_9_0.bc (File name too long)
ERROR: /mnt/WORKSPACE:73:15: fetching _tf_http_archive rule //external:stablehlo: Traceback (most recent call last):
        File "/mnt/.cache/external/xla/third_party/repo.bzl", line 73, column 33, in _tf_http_archive_impl
                ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error extracting /mnt/.cache/external/stablehlo/temp1913717006884866717/458bdd95771e9861e6488868e315a1b0340058ba.zip to /mnt/.cache/external/stablehlo/temp1913717006884866717: /mnt/.cache/external/stablehlo/stablehlo/testdata/vmap_dot_general_batch_dimensions_lhs_float32_8_4_3_3_4__rhs_float32_4_8_3_4_2__dimensionnumbers____4_3___3_2_____0_1___1_0_dynamic.mlir.0_9_0.bc (File name too long)
I
```

I'm compiling it using a vanilla `tensorflow/tensorflow:devel-gpu` docker, with the exception that I upgraded Bazel to 6.1.1 (likely unrelated).

**Comment by janpfeifer** [comment]
I cross-posted the issue in `openxla/stablehlo` repository, in [https://github.com/openxla/stablehlo/issues/1364](here).

Also I checked the largest files are 142 chars in length, and using zip from the command line they extract normally. It could be an indication of an issue with the Java class doing this (?? I have no idea what goes inside bazel)

**Comment by fleiner** [comment]
I ran into the same issue, the filename length is 146 char, which is larger than what cryptfs supports (143 chars). This fs is used at least by some linux distros when using an encrypted home directory. A simple workaround is to symlink $HOME/.cache/bazel to a directory on a standard ext4 partition, tensorflow should then build correctly.

**Comment by janpfeifer** [comment]
Thanks, yes, I mentioned the same in the cross issue -- https://github.com/openxla/stablehlo/issues/1364 (I notice I linked it wrong above, apologies). They suggest they are going to configure it to limit them to be shorter, but I did the same, I linked the source code directory to a directory in a plain (unenctrypted) ext4 partition, and it's been working fine.

**Comment by bondhugula** [comment]
This issue is indeed due to the file system not supporting file names of that length as @fleiner describes. I had ecryptfs on Ubuntu 22.04 for my home dir.
```
mount | grep home
/dev/nvme0n1p8 on /home type ext4 (rw,relatime)
/home/.ecryptfs/uday/.Private on /home/uday type ecryptfs (rw,nosuid,nodev,relatime,ecryptfs_fnek_sig=334469eedce0651c,ecryptfs_sig=502c59492f8f5636,ecryptfs_cipher=aes,ecryptfs_key_bytes=16,ecryptfs_unlink_sigs)
```
Having the bazel cache or the entire home drive on a typical ext4 or xfs will workaround the issue.

**Comment by MatthewSerres345** [comment]
@fleiner fleiner The best suggestion I could give you is to try LONGPATHTOOL. It always helps me to resolve problems with path too long or filename too long. Thank you.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
