### ISSUE TITLE
WSL2 fit function not works tensorflow 2.12.0

### ISSUE THREAD

**Issue by yatebyaeby** [tensorflow/tensorflow#60254]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

v2.12.0-rc1-12-g0db597d0d75 2.12.0

### Custom Code

No

### OS Platform and Distribution

WSL2 Ubuntu / Windows 10 19044 64bit

### Python version

3.10.9-3.10.10

### Bazel version

-

### GCC/Compiler version

-

### CUDA/cuDNN version

11.8.0 / 8.6.0.163

### GPU model and memory

1050ti 4GB

### Current Behaviour?

```shell
Installed all using this instructions https://www.tensorflow.org/install/pip?hl=ru#windows-wsl2
Python see my GPU, but model.fit function not works.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
from tensorflow.python.client import device_lib
import numpy as np
print(tf.__version__)

print(f"Tensor Flow Version: {tf.__version__}")
print(f"Keras Version: {tf.keras.__version__}")
print()
gpu = len(tf.config.list_physical_devices('GPU'))>0
print("GPU is", "available" if gpu else "NOT AVAILABLE")

samples = np.array([
    [u'Россия', 0],
    [u'Вчера смотрел в кино - потрясающий фильм! Актёры высшие, невероятные декорации, безудержный драйв на протяжении всего фильма. Давно не испытывал такого восторга от просмотра! 10/10', 1],
    [u'Норм фильм,в своём стиле не понимаю что другие ожидали))одно смутило когда сцена в клубе все танчили пока бойня была типо ниче не замечая а как картежника завалили все с истериками побежали,типа хуясе тут все в настаящую))))да и пёсель зачетный))', 1],
    [u'Да пипец блин, меня хватило на 10 минут. Это днище', 0],
    [u'Бредовый фильм не советую', 0],
])

test = np.array([
    [u'Фильм говно', 0],
    [u'Классный фильм', 1],
    [u'Не советую к просмотру', 0],
    [u'Тупой фильм', 0],
])

train_text = []
train_label = []

test_text = []
test_label = []

for sample in samples:
    train_text.append(sample[0])
    train_label.append(float(sample[1]))

for tst in test:
    test_text.append(tst[0])
    test_label.append(float(tst[1]))

dataset = {'train': 0, 'test': 0}

dataset['train'] = tf.data.Dataset.from_tensor_slices((train_text, train_label))
dataset['test'] = tf.data.Dataset.from_tensor_slices((test_text, test_label))

train_dataset, test_dataset = dataset['train'], dataset['test']

for text, lable in train_dataset.take(2):
    print(text)

BUFFER_SIZE = 10000
BATCH_SIZE = 128

train_dataset = train_dataset.shuffle(BUFFER_SIZE).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
test_dataset = test_dataset.batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

VOCAB_SIZE = 20000
encoder = tf.keras.layers.TextVectorization(
    standardize='lower',
    max_tokens=VOCAB_SIZE,
    encoding='utf-8')
encoder.adapt(train_dataset.map(lambda text, label: text))


model = tf.keras.Sequential([
    encoder,
    tf.keras.layers.Embedding(
        input_dim=len(encoder.get_vocabulary()),
        output_dim=64,
        # Use masking to handle the variable sequence lengths
        mask_zero=True),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(128)),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(1)
])

model.compile(loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              optimizer=tf.keras.optimizers.Adam(1e-4),
              metrics=['accuracy'])

history = model.fit(train_dataset, epochs=250,
                    validation_data=test_dataset)
                

sample_text = 'меня хватило на 10 минут'
predictions = model.predict(np.array([sample_text]))
print(predictions)
```

### Relevant log output

```shell
2023-04-06 12:06:58.601576: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-06 12:07:00.057818: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2.12.0
Tensor Flow Version: 2.12.0
Keras Version: 2.12.0

2023-04-06 12:07:01.276945: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:982] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-04-06 12:07:01.462465: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:982] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-04-06 12:07:01.462581: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:982] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
GPU is available
2023-04-06 12:07:01.477422: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:982] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-04-06 12:07:01.477546: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:982] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-04-06 12:07:01.477680: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:982] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-04-06 12:07:06.851452: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:982] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-04-06 12:07:06.852698: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:982] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-04-06 12:07:06.852765: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1722] Could not identify NUMA node of platform GPU id 0, defaulting to 0.  Your kernel may not have been built with NUMA support.
2023-04-06 12:07:06.852885: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:982] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-04-06 12:07:06.873685: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1635] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 2519 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1
2023-04-06 12:07:17.597288: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_1' with dtype float and shape [92]
         [[{{node Placeholder/_1}}]]
tf.Tensor(b'\xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f', shape=(), dtype=string)
tf.Tensor(b'\xd0\x92\xd1\x87\xd0\xb5\xd1\x80\xd0\xb0 \xd1\x81\xd0\xbc\xd0\xbe\xd1\x82\xd1\x80\xd0\xb5\xd0\xbb \xd0\xb2 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe - \xd0\xbf\xd0\xbe\xd1\x82\xd1\x80\xd1\x8f\xd1\x81\xd0\xb0\xd1\x8e\xd1\x89\xd0\xb8\xd0\xb9 \xd1\x84\xd0\xb8\xd0\xbb\xd1\x8c\xd0\xbc! \xd0\x90\xd0\xba\xd1\x82\xd1\x91\xd1\x80\xd1\x8b \xd0\xb2\xd1\x8b\xd1\x81\xd1\x88\xd0\xb8\xd0\xb5, \xd0\xbd\xd0\xb5\xd0\xb2\xd0\xb5\xd1\x80\xd0\xbe\xd1\x8f\xd1\x82\xd0\xbd\xd1\x8b\xd0\xb5 \xd0\xb4\xd0\xb5\xd0\xba\xd0\xbe\xd1\x80\xd0\xb0\xd1\x86\xd0\xb8\xd0\xb8, \xd0\xb1\xd0\xb5\xd0\xb7\xd1\x83\xd0\xb4\xd0\xb5\xd1\x80\xd0\xb6\xd0\xbd\xd1\x8b\xd0\xb9 \xd0\xb4\xd1\x80\xd0\xb0\xd0\xb9\xd0\xb2 \xd0\xbd\xd0\xb0 \xd0\xbf\xd1\x80\xd0\xbe\xd1\x82\xd1\x8f\xd0\xb6\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb8 \xd0\xb2\xd1\x81\xd0\xb5\xd0\xb3\xd0\xbe \xd1\x84\xd0\xb8\xd0\xbb\xd1\x8c\xd0\xbc\xd0\xb0. \xd0\x94\xd0\xb0\xd0\xb2\xd0\xbd\xd0\xbe \xd0\xbd\xd0\xb5 \xd0\xb8\xd1\x81\xd0\xbf\xd1\x8b\xd1\x82\xd1\x8b\xd0\xb2\xd0\xb0\xd0\xbb \xd1\x82\xd0\xb0\xd0\xba\xd0\xbe\xd0\xb3\xd0\xbe \xd0\xb2\xd0\xbe\xd1\x81\xd1\x82\xd0\xbe\xd1\x80\xd0\xb3\xd0\xb0 \xd0\xbe\xd1\x82 \xd0\xbf\xd1\x80\xd0\xbe\xd1\x81\xd0\xbc\xd0\xbe\xd1\x82\xd1\x80\xd0\xb0! 10/10', shape=(), dtype=string)2023-04-06 12:07:18.366287: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_1' with dtype float and shape [92]
         [[{{node Placeholder/_1}}]]
2023-04-06 12:07:18.366750: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype string and shape [92]
         [[{{node Placeholder/_0}}]]
2023-04-06 12:07:23.301274: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_1' with dtype float and shape [92]
         [[{{node Placeholder/_1}}]]
2023-04-06 12:07:23.301919: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype string and shape [92]
         [[{{node Placeholder/_0}}]]
Epoch 1/250
2023-04-06 12:07:26.986857: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/ReverseV2_grad/ReverseV2/ReverseV2/axis' with dtype int32 and shape [1]
         [[{{node gradients/ReverseV2_grad/ReverseV2/ReverseV2/axis}}]]
2023-04-06 12:07:30.238269: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/ReverseV2_grad/ReverseV2/ReverseV2/axis' with dtype int32 and shape [1]
         [[{{node gradients/ReverseV2_grad/ReverseV2/ReverseV2/axis}}]]
2023-04-06 12:07:31.901964: W tensorflow/core/common_runtime/type_inference.cc:339] Type inference failed. This indicates an invalid graph that escaped type checking. Error message: INVALID_ARGUMENT: expected compatible input types, but input 1:
type_id: TFT_OPTIONAL
args {
  type_id: TFT_PRODUCT
  args {
    type_id: TFT_TENSOR
    args {
      type_id: TFT_INT32
    }
  }
}
 is neither a subtype nor a supertype of the combined inputs preceding it:
type_id: TFT_OPTIONAL
args {
  type_id: TFT_PRODUCT
  args {
    type_id: TFT_TENSOR
    args {
      type_id: TFT_FLOAT
    }
  }
}

        while inferring type of node 'cond_40/output/_23'
2023-04-06 12:07:38.520941: I tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:424] Loaded cuDNN version 8600
2023-04-06 12:07:39.881521: I tensorflow/compiler/xla/service/service.cc:169] XLA service 0x1da1c010 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2023-04-06 12:07:39.881632: I tensorflow/compiler/xla/service/service.cc:177]   StreamExecutor device (0): NVIDIA GeForce GTX 1050 Ti, Compute Capability 6.1
2023-04-06 12:07:39.994222: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2023-04-06 12:07:40.402391: W tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:530] Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice. This may result in compilation or runtime failures, if the program we try to run uses routines from libdevice.
Searched for CUDA in the following directories:
  ./cuda_sdk_lib
  /usr/local/cuda-11.8
  /usr/local/cuda
  .
You can choose the search directory by setting xla_gpu_cuda_data_dir in HloModule's DebugOptions.  For most apps, setting the environment variable XLA_FLAGS=--xla_gpu_cuda_data_dir=/path/to/cuda will work.
2023-04-06 12:07:40.405914: W tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:274] libdevice is required by this HLO module but was not found at ./libdevice.10.bc
2023-04-06 12:07:40.408337: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:362 : INTERNAL: libdevice not found at ./libdevice.10.bc
2023-04-06 12:07:40.408428: I tensorflow/core/common_runtime/executor.cc:1197] [/job:localhost/replica:0/task:0/device:GPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INTERNAL: libdevice not found at ./libdevice.10.bc
         [[{{node StatefulPartitionedCall_10}}]]
2023-04-06 12:07:40.444717: W tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:274] libdevice is required by this HLO module but was not found at ./libdevice.10.bc
2023-04-06 12:07:40.445387: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:362 : INTERNAL: libdevice not found at ./libdevice.10.bc
2023-04-06 12:07:40.475982: W tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:274] libdevice is required by this HLO module but was not found at ./libdevice.10.bc
2023-04-06 12:07:40.476520: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:362 : INTERNAL: libdevice not found at ./libdevice.10.bc
2023-04-06 12:07:40.509245: W tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:274] libdevice is required by this HLO module but was not found at ./libdevice.10.bc
2023-04-06 12:07:40.509756: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:362 : INTERNAL: libdevice not found at ./libdevice.10.bc
Traceback (most recent call last):
  File "/home/yatebyaeby/test.py", line 168, in <module>
    history = model.fit(train_dataset, epochs=250,
  File "/home/yatebyaeby/miniconda3/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/yatebyaeby/miniconda3/lib/python3.10/site-packages/tensorflow/python/eager/execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InternalError: Graph execution error:

Detected at node 'StatefulPartitionedCall_10' defined at (most recent call last):
    File "/home/yatebyaeby/test.py", line 168, in <module>
      history = model.fit(train_dataset, epochs=250,
    File "/home/yatebyaeby/miniconda3/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/home/yatebyaeby/miniconda3/lib/python3.10/site-packages/keras/engine/training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "/home/yatebyaeby/miniconda3/lib/python3.10/site-packages/keras/engine/training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "/home/yatebyaeby/miniconda3/lib/python3.10/site-packages/keras/engine/training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/yatebyaeby/miniconda3/lib/python3.10/site-packages/keras/engine/training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "/home/yatebyaeby/miniconda3/lib/python3.10/site-packages/keras/engine/training.py", line 1054, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "/home/yatebyaeby/miniconda3/lib/python3.10/site-packages/keras/optimizers/optimizer.py", line 543, in minimize
      self.apply_gradients(grads_and_vars)
    File "/home/yatebyaeby/miniconda3/lib/python3.10/site-packages/keras/optimizers/optimizer.py", line 1174, in apply_gradients
      return super().apply_gradients(grads_and_vars, name=name)
    File "/home/yatebyaeby/miniconda3/lib/python3.10/site-packages/keras/optimizers/optimizer.py", line 650, in apply_gradients
      iteration = self._internal_apply_gradients(grads_and_vars)
    File "/home/yatebyaeby/miniconda3/lib/python3.10/site-packages/keras/optimizers/optimizer.py", line 1200, in _internal_apply_gradients
      return tf.__internal__.distribute.interim.maybe_merge_call(
    File "/home/yatebyaeby/miniconda3/lib/python3.10/site-packages/keras/optimizers/optimizer.py", line 1250, in _distributed_apply_gradients_fn
      distribution.extended.update(
    File "/home/yatebyaeby/miniconda3/lib/python3.10/site-packages/keras/optimizers/optimizer.py", line 1245, in apply_grad_to_update_var
      return self._update_step_xla(grad, var, id(self._var_key(var)))
Node: 'StatefulPartitionedCall_10'
libdevice not found at ./libdevice.10.bc
         [[{{node StatefulPartitionedCall_10}}]] [Op:__inference_train_function_14740]
```
</details>

**Comment by bhagirath20** [comment]
I am not getting any error on Python 3.9.16 for your code. try to use this or reproduce error with TF nightly. it may indicate that there are compatibility issues between TensorFlow and that specific version of Python.

Here are a few things you could try to resolve the issue:

Check if the version of TensorFlow you are using is compatible with Python 3.10.9-3.10.10. You can do this by checking the TensorFlow documentation or release notes.

Update your version of TensorFlow to a more recent version that is compatible with Python 3.10.9-3.10.10.

Downgrade your version of Python to one that is compatible with your version of TensorFlow.

Check if there are any other dependencies or packages that are causing conflicts with TensorFlow and try to resolve those issues.

If none of the above steps work, consider reaching out again.

**Comment by yatebyaeby** [comment]
какая блять ебанина, нахуй вы это придумали блять, через две жопы запускать обучение
