### ISSUE TITLE
Cannot compile TensorFlow 2.10 with GPu support on Windows

### ISSUE THREAD

**Issue by Rayndell** [tensorflow/tensorflow#60264]
### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

tf 2.10

### Custom Code

No

### OS Platform and Distribution

Windows Server 2016

### Python version

3.8.8

### Bazel version

5.1.0

### CUDA/cuDNN version

11.8/8.6

### GPU model and memory

Nvidia GeForce GTX 1080 Ti

### Current Behaviour?

```shell
I am running into issues with bazel when trying to compile TensorFlow 2.10 with CUDA 11.8. I know that this configuration has not been tested, but I need to compile TF with GPU support on native Windows since we are integrating it into our software in my company. Hence the 2.10 version which is the last one with native Windows GPU support. I build against CUDA 11.8 since it is one that support the latest Nvidia GPUs. I used Bazel 5.1.0 since it is the one that apparently should be used with TensorFlow 2.10.

Basically, everything went fine with the configuration until I try to lauch bazel with the following command:

bazel --output_user_root=D:/TensorFlow/bazel-out build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package

Before that everything went well with the configure.py script, which automatically found Python and CUDA 11.8.

The first error message I get is this one :
ERROR: D:/tensorflow/tensorflow/WORKSPACE:15:14: fetching llvm_configure rule //external:llvm-project
File "D:/tensorflow/bazel-out/zfk46uyn/external/llvm-raw/utils/bazel/configure.bzl", line 74, column 25, in _llvm_configure_impl
                _overlay_directories(repository_ctx)
        File "D:/tensorflow/bazel-out/zfk46uyn/external/llvm-raw/utils/bazel/configure.bzl", line 63, column 13, in _overlay_directories
                fail(("Failed to execute overlay script: '{cmd}'\n" +
Error in fail: Failed to execute overlay script: 'C:/Python38/python.exe D:/tensorflow/bazel-out/zfk46uyn/external/llvm-raw/utils/bazel/overlay_directories.py --src D:/tensorflow/bazel-out/zfk46uyn/external/llvm-raw --overlay D:/tensorflow/bazel-out/zfk46uyn/external/llvm-raw/utils/bazel/llvm-project-overlay --target .'

Everything subsequent error seem to depend on that first error. I added the full log to this message.

Many thanks for your kind help.
```

### Standalone code to reproduce the issue

```shell
git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow
git checkout r2.10
python ./configure.py
bazel --output_user_root=D:/TensorFlow/bazel-out build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package
```

### Relevant log output

```shell
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=120
INFO: Reading rc options for 'build' from d:\tensorflow\tensorflow\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=C:/Python38/python.exe
INFO: Reading rc options for 'build' from d:\tensorflow\tensorflow\.bazelrc:
  'build' options: --define framework_shared_object=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library --experimental_link_static_libraries_once=false
INFO: Reading rc options for 'build' from d:\tensorflow\tensorflow\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=C:/Python38/python.exe --action_env PYTHON_LIB_PATH=C:/Python38/lib/site-packages --python_path=C:/Python38/python.exe --action_env CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8 --action_env CUDNN_INSTALL_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8 --action_env TF_CUDA_COMPUTE_CAPABILITIES=3.5,5.2,6.1,7.0,7.5,8.6,8.9 --config=cuda --copt=/d2ReducedOptimizeHugeFunctions --host_copt=/d2ReducedOptimizeHugeFunctions
INFO: Reading rc options for 'build' from d:\tensorflow\tensorflow\.bazelrc:
  'build' options: --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/ir,tensorflow/compiler/mlir/tfrt/tests/analysis,tensorflow/compiler/mlir/tfrt/tests/jit,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_tfrt,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_jitrt,tensorflow/compiler/mlir/tfrt/tests/tf_to_corert,tensorflow/compiler/mlir/tfrt/tests/tf_to_tfrt_data,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/common,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/graph_executor,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
INFO: Found applicable config definition build:short_logs in file d:\tensorflow\tensorflow\.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file d:\tensorflow\tensorflow\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:cuda in file d:\tensorflow\tensorflow\.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
INFO: Found applicable config definition build:opt in file d:\tensorflow\tensorflow\.tf_configure.bazelrc: --copt=/arch:AVX --host_copt=/arch:AVX
INFO: Found applicable config definition build:cuda in file d:\tensorflow\tensorflow\.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
INFO: Found applicable config definition build:windows in file d:\tensorflow\tensorflow\.bazelrc: --copt=/W0 --host_copt=/W0 --copt=/Zc:__cplusplus --host_copt=/Zc:__cplusplus --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --features=compiler_param_file --copt=/d2ReducedOptimizeHugeFunctions --host_copt=/d2ReducedOptimizeHugeFunctions --cxxopt=/std:c++17 --host_cxxopt=/std:c++17 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=/experimental:preprocessor --host_copt=/experimental:preprocessor --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --verbose_failures --features=compiler_param_file --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file d:\tensorflow\tensorflow\.bazelrc: --define framework_shared_object=false --experimental_link_static_libraries_once=false
INFO: Repository llvm-project instantiated at:
  D:/tensorflow/tensorflow/WORKSPACE:15:14: in <toplevel>
  D:/tensorflow/tensorflow/tensorflow/workspace2.bzl:889:21: in workspace
  D:/tensorflow/tensorflow/tensorflow/workspace2.bzl:527:15: in _tf_repositories
  D:/tensorflow/tensorflow/third_party/llvm/setup.bzl:22:19: in llvm_setup
Repository rule llvm_configure defined at:
  D:/tensorflow/bazel-out/zfk46uyn/external/llvm-raw/utils/bazel/configure.bzl:84:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'llvm-project':
   Traceback (most recent call last):
        File "D:/tensorflow/bazel-out/zfk46uyn/external/llvm-raw/utils/bazel/configure.bzl", line 74, column 25, in _llvm_configure_impl
                _overlay_directories(repository_ctx)
        File "D:/tensorflow/bazel-out/zfk46uyn/external/llvm-raw/utils/bazel/configure.bzl", line 63, column 13, in _overlay_directories
                fail(("Failed to execute overlay script: '{cmd}'\n" +
Error in fail: Failed to execute overlay script: 'C:/Python38/python.exe D:/tensorflow/bazel-out/zfk46uyn/external/llvm-raw/utils/bazel/overlay_directories.py --src D:/tensorflow/bazel-out/zfk46uyn/external/llvm-raw --overlay D:/tensorflow/bazel-out/zfk46uyn/external/llvm-raw/utils/bazel/llvm-project-overlay --target .'
Exited with code 1
stdout:

stderr:
Traceback (most recent call last):
  File "D:/tensorflow/bazel-out/zfk46uyn/external/llvm-raw/utils/bazel/overlay_directories.py", line 92, in <module>
    main(parse_arguments())
  File "D:/tensorflow/bazel-out/zfk46uyn/external/llvm-raw/utils/bazel/overlay_directories.py", line 80, in main
    _symlink_abs(os.path.join(args.overlay, relpath),
  File "D:/tensorflow/bazel-out/zfk46uyn/external/llvm-raw/utils/bazel/overlay_directories.py", line 64, in _symlink_abs
    os.symlink(os.path.abspath(from_path), os.path.abspath(to_path))
OSError: [WinError 1314] Le client ne dispose pas dÆun privilÞge nÚcessaire: 'D:\\tensorflow\\bazel-out\\zfk46uyn\\external\\llvm-raw\\utils\\bazel\\llvm-project-overlay\\.bazelignore' -> 'D:\\tensorflow\\bazel-out\\zfk46uyn\\external\\llvm-project\\.bazelignore'

ERROR: D:/tensorflow/tensorflow/WORKSPACE:15:14: fetching llvm_configure rule //external:llvm-project: Traceback (most recent call last):
        File "D:/tensorflow/bazel-out/zfk46uyn/external/llvm-raw/utils/bazel/configure.bzl", line 74, column 25, in _llvm_configure_impl
                _overlay_directories(repository_ctx)
        File "D:/tensorflow/bazel-out/zfk46uyn/external/llvm-raw/utils/bazel/configure.bzl", line 63, column 13, in _overlay_directories
                fail(("Failed to execute overlay script: '{cmd}'\n" +
Error in fail: Failed to execute overlay script: 'C:/Python38/python.exe D:/tensorflow/bazel-out/zfk46uyn/external/llvm-raw/utils/bazel/overlay_directories.py --src D:/tensorflow/bazel-out/zfk46uyn/external/llvm-raw --overlay D:/tensorflow/bazel-out/zfk46uyn/external/llvm-raw/utils/bazel/llvm-project-overlay --target .'
Exited with code 1
stdout:

stderr:
Traceback (most recent call last):
  File "D:/tensorflow/bazel-out/zfk46uyn/external/llvm-raw/utils/bazel/overlay_directories.py", line 92, in <module>
    main(parse_arguments())
  File "D:/tensorflow/bazel-out/zfk46uyn/external/llvm-raw/utils/bazel/overlay_directories.py", line 80, in main
    _symlink_abs(os.path.join(args.overlay, relpath),
  File "D:/tensorflow/bazel-out/zfk46uyn/external/llvm-raw/utils/bazel/overlay_directories.py", line 64, in _symlink_abs
    os.symlink(os.path.abspath(from_path), os.path.abspath(to_path))
OSError: [WinError 1314] Le client ne dispose pas dÆun privilÞge nÚcessaire: 'D:\\tensorflow\\bazel-out\\zfk46uyn\\external\\llvm-raw\\utils\\bazel\\llvm-project-overlay\\.bazelignore' -> 'D:\\tensorflow\\bazel-out\\zfk46uyn\\external\\llvm-project\\.bazelignore'

INFO: Repository flatbuffers instantiated at:
  D:/tensorflow/tensorflow/WORKSPACE:15:14: in <toplevel>
  D:/tensorflow/tensorflow/tensorflow/workspace2.bzl:882:28: in workspace
  D:/tensorflow/tensorflow/tensorflow/workspace2.bzl:61:16: in _initialize_third_party
  D:/tensorflow/tensorflow/third_party/flatbuffers/workspace.bzl:6:20: in repo
  D:/tensorflow/tensorflow/third_party/repo.bzl:136:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  D:/tensorflow/tensorflow/third_party/repo.bzl:89:35: in <toplevel>
ERROR: D:/tensorflow/tensorflow/tensorflow/tools/pip_package/BUILD:278:10: //tensorflow/tools/pip_package:build_pip_package depends on //tensorflow/compiler/mlir/tensorflow:gen_mlir_passthrough_op_py in repository @ which failed to fetch. no such package '@llvm-project//mlir': Failed to execute overlay script: 'C:/Python38/python.exe D:/tensorflow/bazel-out/zfk46uyn/external/llvm-raw/utils/bazel/overlay_directories.py --src D:/tensorflow/bazel-out/zfk46uyn/external/llvm-raw --overlay D:/tensorflow/bazel-out/zfk46uyn/external/llvm-raw/utils/bazel/llvm-project-overlay --target .'
Exited with code 1
stdout:

stderr:
Traceback (most recent call last):
  File "D:/tensorflow/bazel-out/zfk46uyn/external/llvm-raw/utils/bazel/overlay_directories.py", line 92, in <module>
    main(parse_arguments())
  File "D:/tensorflow/bazel-out/zfk46uyn/external/llvm-raw/utils/bazel/overlay_directories.py", line 80, in main
    _symlink_abs(os.path.join(args.overlay, relpath),
  File "D:/tensorflow/bazel-out/zfk46uyn/external/llvm-raw/utils/bazel/overlay_directories.py", line 64, in _symlink_abs
    os.symlink(os.path.abspath(from_path), os.path.abspath(to_path))
OSError: [WinError 1314] Le client ne dispose pas dÆun privilÞge nÚcessaire: 'D:\\tensorflow\\bazel-out\\zfk46uyn\\external\\llvm-raw\\utils\\bazel\\llvm-project-overlay\\.bazelignore' -> 'D:\\tensorflow\\bazel-out\\zfk46uyn\\external\\llvm-project\\.bazelignore'

ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Analysis failed
INFO: Elapsed time: 1.558s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (38 packages loaded, 2 targets configured)
    currently loading: tensorflow/lite/python ... (2 packages)
    Fetching https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/flatbuffers/archive/v2.0.6.tar.gz
```

**Comment by Rayndell** [comment]
Oh, and I have already tried some workarounds, like creating a CUDNN_INSTALL_PATH environment variable and enablind the Developer mode, like suggested in this post : https://discuss.tensorflow.org/t/error-building-tensorflow-2-8-in-windows-10/7984

**Comment by pogrushan** [comment]
The error message you are seeing suggests that there is an issue with the LLVM project in your TensorFlow build.

Here are some possible steps you can try to resolve the error:

Check your LLVM version: TensorFlow 2.10 requires LLVM 9.0, which you can download from the LLVM website. Make sure to download the correct version of LLVM that matches your system.

Check your Bazel version: Make sure that you have installed the correct version of Bazel that matches the TensorFlow version you are trying to build. You can find the required Bazel version in the TensorFlow documentation.

Clean the Bazel cache: Try cleaning the Bazel cache by running "bazel clean" in your TensorFlow source directory. This will clear any cached build artifacts that may be causing issues.

Rebuild the LLVM project: Try rebuilding the LLVM project by running "bazel build //external:llvm-project" in your TensorFlow source directory. This will rebuild the LLVM project from scratch.

Rebuild TensorFlow: Once you have rebuilt the LLVM project, try rebuilding TensorFlow by running "bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package" in your TensorFlow source directory. This will create a new TensorFlow pip package with GPU support.

**Comment by Rayndell** [comment]
Thank you very much for your answer.

I'm using Bazel 5.1.0, which is the correct version that should be used with TF 2.10.
I installed LLVM 9.0 on my system, however it does not seem to change anything (LLVM install folder has been added to the Windows Path) as it still tries to fetch the llvm project.
Finally, i tried building the llvm project manually with the bazel command and had this error:

ERROR: D:/tensorflow/tensorflow/WORKSPACE:15:14: in llvm_configure rule //external:llvm-project: Found reference to a workspace rule in a context where a build rule was expected; probably a reference to a target in that external repository, properly specified as @reponame//path/to/package:target, should have been specified by the requesting rule.

A bazel clean did not help.

**Comment by Rayndell** [comment]
I have some updates. After some further manual cleaning another error came out:

ERROR: An error occurred during the fetch of repository 'envoy_api':
   Traceback (most recent call last):
        File "D:/tensorflow/bazel-out/zfk46uyn/external/bazel_tools/tools/build_defs/repo/http.bzl", line 100, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/envoyproxy/data-plane-api/archive/c83ed7ea9eb5fb3b93d1ad52b59750f1958b8bde.tar.gz] to D:/tensorflow/bazel-out/zfk46uyn/external/envoy_api/temp17372839701998073658/c83ed7ea9eb5fb3b93d1ad52b59750f1958b8bde.tar.gz: Unknown host: codeload.github.com

So it seems I have troubles fetching the envoy_api project now... In general I also have a lot of warnings stating that files were not found when trying to download some projects:

WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/6ca793b5d862ef6c50f242d77a811f06cce9b60a.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/0538e5431afdb1fa05bdcedf70ee502ccfcd112a.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://github.com/envoyproxy/data-plane-api/archive/c83ed7ea9eb5fb3b93d1ad52b59750f1958b8bde.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Unknown host: codeload.github.com

**Comment by pogrushan** [comment]
You can find the download link for the c83ed7ea9eb5fb3b93d1ad52b59750f1958b8bde.tar.gz file in the error message. Download the file and extract it to the D:/tensorflow/bazel-out/zfk46uyn/external/envoy_api directory.

Once the file is in the correct directory, try running the build command again and see if the issue is resolved.
I'm afraid if this does not work, it may either be a network issue (your ISP forbids you from visiting the urls) or a bazel issue.

**Comment by Rayndell** [comment]
So, I am progressing a little bit. Basically I had troubles creating symlinks under my account for some reason. I started from the beginning from a fresh Windows account on my machine and this solved it.

However, I am still running into issues when linking the project:

ERROR: D:/tensorflow/tensorflow/tensorflow/BUILD:1034:21: Linking tensorflow/libtensorflow_framework.so.2.10.1 failed: (Exit 1189): link.exe failed: error executing command
  cd /d D:/tensorflow/bazel-out/zfk46uyn/execroot/org_tensorflow
  SET INCLUDE=C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include;C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\ATLMFC\include;C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\VS\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um
    SET LIB=C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\ATLMFC\lib\x64;C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\lib\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.22000.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22000.0\\um\x64
    SET PATH=C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64;C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\VC\VCPackages;C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\bin\Roslyn;C:\Program Files\Microsoft Visual Studio\2022\Professional\Team Tools\Performance Tools\x64;C:\Program Files\Microsoft Visual Studio\2022\Professional\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\;C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\CommonExtensions\Microsoft\FSharp\Tools;C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\\x64;C:\Program Files (x86)\Windows Kits\10\bin\\x64;C:\Program Files\Microsoft Visual Studio\2022\Professional\\MSBuild\Current\Bin\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\;C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\Tools\;;C:\Windows\system32;C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\VC\Linux\bin\ConnectionManagerExe
    SET PWD=/proc/self/cwd
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=C:\Users\AURELI~1\AppData\Local\Temp
    SET TMP=C:\Users\AURELI~1\AppData\Local\Temp
  C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64\link.exe @bazel-out/x64_windows-opt-exec-50AE0418/bin/tensorflow/libtensorflow_framework.so.2.10.1-2.params
# Configuration: 235f51f52e7e1d2ff49596414691042bdab9491882365c09175bc46cf2ee6814
# Execution platform: @local_execution_config_platform//:platform
LINK : warning LNK4044: option '/lm' non reconnue ; ignorée
LINK : fatal error LNK1189: limite de 65535 objets dépassée pour la bibliothèque
Target //tensorflow:tensorflow_cc.dll failed to build

What I understood from the last LINK error (it is in french, it means "Link error 1189 library limit of 65535 objects exceeded") is that MSVC is trying to create a dll or a lib with too many objects in it. As I understood it is a MSVC limitation, however it is strange I did not encounter this error before, since I previously built the 2.4 TF version without any of this type.

So, is there a means to overcome this limitation (seems unlikely), or to prevent TF from putting too many objects in the binaries? For example by choosing which objects to exclude from the compilation (I certainly do not need all that exists in the TensorFlow release)?

**Comment by SuryanarayanaY** [comment]
@Rayndell ,

Could you please cross check with the tested configuration for TF2.10 versions (CUDA=11.2 and cuDNN=8.1) and let us know if the build has any problem. We can't guarantee that CUDA 11.8 works with Tf2.10v or not. But if the build fails with CUDA-11.2 then definitely we will have a look .

Thanks!

**Comment by Rayndell** [comment]
Thanks for the response. Actually I succeeded by downgrading to the 2.7 version (haven't tested 2.8 and 2.9) and using Python 3.9. The built went well with CUDA 11.8. I am not sure if I will have the time to re-test the 2.10 build with lower versions of CUDA though.

**Comment by SuryanarayanaY** [comment]
@Rayndell ,

Higher CUDA versions may also work if taken care of backward compatibility.Since we have tested configurations and also documented them we recommend users to follow same and we guarantee that they work and if not will be taken care by us.

In case your purpose resolved can we mark it as closed ? Please spare some time to close the issue and in future if have any problems please feel free to open a ticket. Thanks!

**Comment by manswad** [comment]
Hi does anyone has the 3 files which the above guy mentioned and have link of.

Those sites are now unaccessible 

Thanks
