### ISSUE TITLE
ImportError: DLL load failed while importing _pywrap_dtensor_device: The specified procedure could not be found.

### ISSUE THREAD

**Issue by faguilarc** [tensorflow/tensorflow#60405]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.12

### Custom Code

No

### OS Platform and Distribution

Windows 10 

### Python version

3.10.4

### CUDA/cuDNN version

no

### GPU model and memory

no

### Current Behaviour?

I just upgraded tensorflow to 2.12.x and I get the following error when I run a .py in my project:
ImportError: DLL load failed while importing _pywrap_dtensor_device: The specified procedure could not be found.

How can I solve that ??

### Standalone code to reproduce the issue

```shell
Traceback (most recent call last):
  File "C:\Users\FRANK-PC\Documents\GitHub\Syntactic-analysis-system-of-Cuban-addresses\examples\generate_and_save_data_set.py", line 3, in <module>
    from src.data_realism_converter.data_set_adapter import DataSetAdapter
  File "C:\Users\FRANK-PC\Documents\GitHub\Syntactic-analysis-system-of-Cuban-addresses\src\data_realism_converter\data_set_adapter.py", line 2, in <module>
    from keras.utils import pad_sequences, to_categorical
  File "C:\Users\FRANK-PC\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\__init__.py", line 21, in <module>
    from keras import models
  File "C:\Users\FRANK-PC\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\models\__init__.py", line 18, in <module>
    from keras.engine.functional import Functional
  File "C:\Users\FRANK-PC\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\functional.py", line 26, in <module>
    from keras import backend
  File "C:\Users\FRANK-PC\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\backend.py", line 34, in <module>
    from keras.dtensor import dtensor_api as dtensor
  File "C:\Users\FRANK-PC\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\dtensor\__init__.py", line 22, in <module>
    from tensorflow.compat.v2.experimental import dtensor as dtensor_api
  File "C:\Users\FRANK-PC\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\_api\v2\compat\v2\experimental\dtensor\__init__.py", line 8, in <module>
    from tensorflow.dtensor.python.accelerator_util import initialize_accelerator_system
  File "C:\Users\FRANK-PC\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\dtensor\python\accelerator_util.py", line 24, in <module>
    from tensorflow.dtensor.python import tpu_util
  File "C:\Users\FRANK-PC\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\dtensor\python\tpu_util.py", line 24, in <module>
    from tensorflow.dtensor.python import dtensor_device
  File "C:\Users\FRANK-PC\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\dtensor\python\dtensor_device.py", line 27, in <module>
    from tensorflow.dtensor.python import layout as layout_lib
  File "C:\Users\FRANK-PC\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\dtensor\python\layout.py", line 25, in <module>
    from tensorflow.python import _pywrap_dtensor_device
ImportError: DLL load failed while importing _pywrap_dtensor_device: The specified procedure could not be found.
```

### Relevant log output

_No response_</details>

**Comment by synandi** [comment]
Hi @faguilarc, 
Thanks for reporting the issue!
Could you please confirm that you installed Tensorflow using pip and kindly share the steps you have followed to install Tensorflow. Thank you!

**Comment by faguilarc** [comment]
i don't know what is the reason, i had to downgrade, and after uninstalling everything for the fifteenth time it stopped giving me problems. Thanks
