### ISSUE TITLE
AutoGraph error when function is inside a match 

### ISSUE THREAD

**Issue by AndreasMadsen** [tensorflow/tensorflow#60458]
### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

binary

### Tensorflow Version

2.13.0-dev20230501

### Custom Code

No

### OS Platform and Distribution

Google Colab

### Python version

3.10.11

### Current Behaviour?

When a `tf.data.Dataset.map` function is defined inside a `match` scope and used by `tf.data.Dataset.apply` the AutoGraph fails. This should not happen, as the match statement should be irrelevant to the function definition. I suspect this error happens in more AutoGraph cases than just `tf.data.Dataset.map` via `tf.data.Dataset.apply`.

The issue is reproduced on Google Colab with both nightly (2.13.0-dev20230501) and 2.12.

### Standalone code to reproduce the issue

```shell
See https://colab.research.google.com/drive/1x07aUgISrYQohsG7FYmc70LeYjVcGixG#scrollTo=auSxkDSinh3R


import tensorflow as tf

parameter = 'a'

match parameter:
    case 'a':
        def fn(ds):
            return ds.map(lambda x: x + 1)

dataset = tf.data.Dataset.range(1) \
    .apply(fn)

for x in dataset:
    print(x)
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 427, in converted_call
    converted_f = _convert_actual(target_entity, program_ctx)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 269, in _convert_actual
    transformed, module, source_map = _TRANSPILER.transform(entity, program_ctx)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/pyct/transpiler.py", line 282, in transform
    return self.transform_function(obj, user_context)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/pyct/transpiler.py", line 466, in transform_function
    nodes, ctx = super(PyToPy, self).transform_function(fn, user_context)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/pyct/transpiler.py", line 342, in transform_function
    node, source = parser.parse_entity(fn, future_features=future_features)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/pyct/parser.py", line 145, in parse_entity
    return _parse_lambda(entity)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/pyct/parser.py", line 275, in _parse_lambda
    lambda_nodes.extend(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/pyct/parser.py", line 275, in <genexpr>
    lambda_nodes.extend(
  File "/usr/lib/python3.10/ast.py", line 390, in walk
    todo.extend(iter_child_nodes(node))
  File "/usr/lib/python3.10/ast.py", line 272, in iter_child_nodes
    for name, field in iter_fields(node):
  File "/usr/lib/python3.10/ast.py", line 260, in iter_fields
    for field in node._fields:
AttributeError: 'NoneType' object has no attribute '_fields'
WARNING:tensorflow:AutoGraph could not transform <function fn.<locals>.<lambda> at 0x7f9fc56e9870> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'NoneType' object has no attribute '_fields'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
2.13.0-dev20230501
Converted call: <function fn.<locals>.<lambda> at 0x7f9fc56e9870>
    args: (<tf.Tensor 'args_0:0' shape=() dtype=int64>,)
    kwargs: {}

Not allowed: <method-wrapper '__call__' of function object at 0x7f9fc56e9870>: default rule
Not allowed: <function fn.<locals>.<lambda> at 0x7f9fc56e9870>: default rule
<function fn.<locals>.<lambda> at 0x7f9fc56e9870> is not cached for subkey ConversionOptions[{}]
Error transforming entity <function fn.<locals>.<lambda> at 0x7f9fc56e9870>
WARNING: AutoGraph could not transform <function fn.<locals>.<lambda> at 0x7f9fc56e9870> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'NoneType' object has no attribute '_fields'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
tf.Tensor(1, shape=(), dtype=int64)
```

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue on tensorflow v2.11, v2.12 and tf-nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/685e8063991716febd945da49dd5ff14/untitled1102.ipynb).

**Comment by burnpanck** [comment]
Potential duplicate of #57166

**Comment by kiransair** [comment]
Hi @AndreasMadsen, In the latest tensorflow version i was able to execute the code without any error. please refer to this [gist](https://gist.github.com/kiransair/7a7a469d0d821ae42038f4beb6114265) for working code example. Thank You.

**Comment by AndreasMadsen** [comment]
The notebook I linked to prints:

```
Collecting tf-nightly
  Downloading tf_nightly-2.19.0.dev20241204-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from tf-nightly) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tf-nightly) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.10/dist-packages (from tf-nightly) (24.3.25)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from tf-nightly) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from tf-nightly) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.10/dist-packages (from tf-nightly) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from tf-nightly) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from tf-nightly) (24.2)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.10/dist-packages (from tf-nightly) (4.25.5)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.10/dist-packages (from tf-nightly) (2.32.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from tf-nightly) (75.1.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from tf-nightly) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from tf-nightly) (2.5.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.10/dist-packages (from tf-nightly) (4.12.2)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from tf-nightly) (1.16.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.10/dist-packages (from tf-nightly) (1.68.0)
Collecting tb-nightly~=2.19.0.a (from tf-nightly)
  Downloading tb_nightly-2.19.0a20241121-py3-none-any.whl.metadata (1.6 kB)
Collecting keras-nightly>=3.6.0.dev (from tf-nightly)
  Downloading keras_nightly-3.7.0.dev2024120503-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in /usr/local/lib/python3.10/dist-packages (from tf-nightly) (1.26.4)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.10/dist-packages (from tf-nightly) (3.12.1)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from tf-nightly) (0.4.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.10/dist-packages (from tf-nightly) (0.37.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from astunparse>=1.6.0->tf-nightly) (0.45.0)
Requirement already satisfied: rich in /usr/local/lib/python3.10/dist-packages (from keras-nightly>=3.6.0.dev->tf-nightly) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.10/dist-packages (from keras-nightly>=3.6.0.dev->tf-nightly) (0.0.8)
Requirement already satisfied: optree in /usr/local/lib/python3.10/dist-packages (from keras-nightly>=3.6.0.dev->tf-nightly) (0.13.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tf-nightly) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tf-nightly) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tf-nightly) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tf-nightly) (2024.8.30)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tb-nightly~=2.19.0.a->tf-nightly) (3.7)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tb-nightly~=2.19.0.a->tf-nightly) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from tb-nightly~=2.19.0.a->tf-nightly) (3.1.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.10/dist-packages (from werkzeug>=1.0.1->tb-nightly~=2.19.0.a->tf-nightly) (3.0.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich->keras-nightly>=3.6.0.dev->tf-nightly) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich->keras-nightly>=3.6.0.dev->tf-nightly) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich->keras-nightly>=3.6.0.dev->tf-nightly) (0.1.2)
Downloading tf_nightly-2.19.0.dev20241204-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (632.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 632.3/632.3 MB 3.0 MB/s eta 0:00:00
Downloading keras_nightly-3.7.0.dev2024120503-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 45.8 MB/s eta 0:00:00
Downloading tb_nightly-2.19.0a20241121-py3-none-any.whl (5.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 87.5 MB/s eta 0:00:00
Installing collected packages: tb-nightly, keras-nightly, tf-nightly
Successfully installed keras-nightly-3.7.0.dev2024120503 tb-nightly-2.19.0a20241121 tf-nightly-2.19.0.dev20241204
2.19.0-dev20241204
Converted call: <function fn.<locals>.<lambda> at 0x784f69552ef0>
    args: (<tf.Tensor 'args_0:0' shape=() dtype=int64>,)
    kwargs: {}

Not allowed: <method-wrapper '__call__' of function object at 0x784f69552ef0>: default rule
Not allowed: <function fn.<locals>.<lambda> at 0x784f69552ef0>: default rule
<function fn.<locals>.<lambda> at 0x784f69552ef0> is not cached for subkey ConversionOptions[{}]
Source code of <function fn.<locals>.<lambda> at 0x784f69552ef0>:

lambda x: x + 1

Transformed <function fn.<locals>.<lambda> at 0x784f69552ef0>:

# coding=utf-8
tf__lam = lambda x: ag__.with_function_scope(lambda lscope: x + 1, 'lscope', ag__.STD)

Defaults of <function outer_factory.<locals>.inner_factory.<locals>.<lambda> at 0x784f695537f0> : None
KW defaults of <function outer_factory.<locals>.inner_factory.<locals>.<lambda> at 0x784f695537f0> : None
Calling <function outer_factory.<locals>.inner_factory.<locals>.<lambda> at 0x784f695537f0> with
    x: Tensor("args_0:0", shape=(), dtype=int64)

AttributeError: module 'ml_dtypes' has no attribute 'float8_e3m4'
tf.Tensor(1, shape=(), dtype=int64)
```

**Comment by Kayyuri** [comment]
Hi,
Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
