### ISSUE TITLE
CUDA_ERROR_OUT_OF_MEMORY (Memory Available)

### ISSUE THREAD

**Issue by camj256** [tensorflow/tensorflow#6048]
Tensorflow is failing like so - very odd since I have memory available and it sees that. This runs fine in CPU only.

Ubuntu 16.04, Cuda 8.0, CUDNN 5.1 for 8.0, Nvidia 367.57 driver, tensorflow_gpu-0.12.0rc0-cp27-none-linux_x86_64.whl. The rest you can see in the log. I have also tried with CUDNN 5.0 with the same result. Cuda 7.5 works for me but is very slow.

**Log:**
```
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Exceptions: 0
1403
1403
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 660
major: 3 minor: 0 memoryClockRate (GHz) 1.0975
pciBusID 0000:02:00.0
Total memory: 1.99GiB
Free memory: 1.43GiB
W tensorflow/stream_executor/cuda/cuda_driver.cc:590] creating context when one is currently active; existing: 0x2c47900
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 1 with properties: 
name: GeForce GTX 660
major: 3 minor: 0 memoryClockRate (GHz) 1.0975
pciBusID 0000:01:00.0
Total memory: 1.99GiB
Free memory: 1.41GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:777] Peer access not supported between device ordinals 0 and 1
I tensorflow/core/common_runtime/gpu/gpu_device.cc:777] Peer access not supported between device ordinals 1 and 0
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 1 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y N 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 1:   N Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 660, pci bus id: 0000:02:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:1) -> (device: 1, name: GeForce GTX 660, pci bus id: 0000:01:00.0)
E tensorflow/stream_executor/cuda/cuda_driver.cc:1002] failed to allocate 198.83M (208486400 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
Traceback (most recent call last):
  File "build.py", line 84, in <module>
    model = tflearn.DNN(net)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/models/dnn.py", line 63, in __init__
    best_val_accuracy=best_val_accuracy)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/trainer.py", line 135, in __init__
    keep_checkpoint_every_n_hours=keep_checkpoint_every_n_hours)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1000, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1021, in build
    raise ValueError("No variables to save")
ValueError: No variables to save
```

**Code:**
```
net = tflearn.input_data(shape=[None, 5])
net = tflearn.fully_connected(net, 64)
net = tflearn.fully_connected(net, 64)
net = tflearn.fully_connected(net, 2, activation='softmax')
net = tflearn.regression(net)

# Training
model = tflearn.DNN(net)
model.fit(X, Y, n_epoch=10000, batch_size=64, show_metric=True)

for x in range(0,50):
    rand = randint(0,len(X))
    print(model.predict([X[rand]]), Y[rand])

model.save("model.tfl")
```

**Comment by poxvoculi** [comment]
The python stack trace doesn't seem to accurately identify where the failing memory allocation is happening.  In general, nothing in a TF program should be calling CudaDriver::DeviceAllocate directly, except the initial allocation of most of the device memory into a pool that will later be sub-allocated.  Your GPUs are rather small.  I can't tell whether the initial allocation is failing, or something later.  

You might try adjusting the fraction of visible memory that TF tries to take in its initial allocation.
For example:

# Assume that you have 12GB of GPU memory and want to allocate ~4GB:
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.333)

sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))

**Comment by jart** [comment]
Closing due to inactivity. If @poxvoculi's response didn't help and you are still encountering this issue, please let us know, and I'll re-open.

**Comment by cnzero** [comment]
@jart Hi. I am a new learner of TF. And I have similar problem as the above. I have tested the solution of @poxvoculi , but it didn't work anyway.
The following is my problem description:
Codes are from the TF official website, [Basic usage](https://www.tensorflow.org/get_started/get_started#basic_usage)
I set up a virtual environment of Python+TensorFlow-gpu on Ubuntu 16.04
terminal prompting information as following:
```
(tfStarted) zero@zero:$ python officialBasicUsage.py 
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmpJkInjp
WARNING:tensorflow:Rank of input Tensor (1) should be the same as output_rank (2) for column. Will attempt to expand dims. It is highly recommended that you resize your input, as this behavior may change.
WARNING:tensorflow:From /home/zero/ownCloud/DeepLearning/TensorflowCode/tfStarted/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/head.py:1362: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.835
pciBusID 0000:03:00.0
Total memory: 7.92GiB
Free memory: 7.30GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:03:00.0)
E tensorflow/stream_executor/cuda/cuda_driver.cc:1002] failed to allocate 7.92G (8499167232 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
WARNING:tensorflow:Rank of input Tensor (1) should be the same as output_rank (2) for column. Will attempt to expand dims. It is highly recommended that you resize your input, as this behavior may change.
WARNING:tensorflow:From /home/zero/ownCloud/DeepLearning/TensorflowCode/tfStarted/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/head.py:1362: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:03:00.0)
W tensorflow/core/framework/op_kernel.cc:993] Out of range: RandomShuffleQueue '_1_enqueue_input/random_shuffle_queue' is closed and has insufficient elements (requested 4, current size 0)
	 [[Node: random_shuffle_queue_DequeueUpTo = QueueDequeueUpToV2[component_types=[DT_INT64, DT_DOUBLE, DT_DOUBLE, DT_DOUBLE], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](enqueue_input/random_shuffle_queue, random_shuffle_queue_DequeueUpTo/n)]]
WARNING:tensorflow:Skipping summary for global_step, must be a float or np.float32.

```
Even through solution of poxvoculi was involved, problem  is still there. 
I have searched such problem in Google with keywords--"failed to allocate from device CUDA_ERROR_OUT_OF_MEMORY"
And there is a similar Q&A in [stackoverflow](http://stackoverflow.com/questions/34514324/error-using-tensorflow-with-gpu), like poxvoculi's, but it doesn't work.
So, what's the real problem? GPU capacity allocation error? or others?
And how can I solve this? Thank you very much.

**Comment by poxvoculi** [comment]
Please look again at my earlier post and the stackoverlfow post you cite.  According to your logging messages, you're trying to allocate 7.92GB from a GPU that has only 7.30GB free.  You need to reduce the allocation fraction using tf.GPUOptions.

**Comment by cnzero** [comment]
@poxvoculi  You are right. I am a bit careless. 
But there are some warnings even though answers are showed. 
Maybe I am a beginner to TensorFlow, it needs some time to grasp TensorFlow basic concepts. 
Thank you very much.

**Comment by jart** [comment]
@cnzero We're glad you've chosen to use TensorFlow. We put a lot of work into this library and hope it serves you well. In return we ask that the community be respectful of the fact that this issue tracker is for bugs and feature requests, not an escalation path for [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow).

**Comment by xiangqian0011** [comment]
meeting same quetion:CUDA_ERROR_OUT_OF_MEMORY
2017-07-12 16:37:11.170870: I tensorflow/core/common_runtime/gpu/gpu_device.cc:996] Creating TensorFlow device (/gpu:2) -> (device: 2, name: GeForce GTX 1080, pci bus id: 0000:05:00.0)
2017-07-12 16:37:11.207585: E tensorflow/stream_executor/cuda/cuda_driver.cc:924] failed to allocate 198.29M (207925248 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2017-07-12 16:37:23.575049: E tensorflow/stream_executor/cuda/cuda_blas.cc:365] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2017-07-12 16:37:23.575072: W tensorflow/stream_executor/stream.cc:1601] attempting to perform BLAS operation using StreamExecutor without BLAS support
2017-07-12 16:37:23.575157: F tensorflow/cc/tutorials/example_trainer.cc:129] Non-OK-status: session->Run({{"x", x}}, {"y:0", "y_normalized:0"}, {}, &outputs) status: Internal: Blas GEMV launch failed:  m=2, n=2
	 [[Node: y = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](Cast, _arg_x_0_0/_11)]]
Aborted (core dumped)

**Comment by rishabhmalhotra** [comment]
Since this still seems to be a major issue, just wondering if we can use CUDA through numba and force the GPU to kill all existing processes (which should automatically release memory)...

**Comment by poxvoculi** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by GraphGrailAi** [comment]
I was experienced memory error in Ubuntu 18.10. When i changed resolution of my monitor from 4k to fullhd (1920-1080) memory available become 438mb and neural network training started. I was really surprised by this behavior.

By the way, i have Nvidia 1080 with 8gb memory, still dont know why only 400mb available
