### ISSUE TITLE
ROCm: Importing PyTorch before TensorFlow causes TensorFlow to fail completely

### ISSUE THREAD

**Issue by hameerabbasi** [tensorflow/tensorflow#60642]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

v2.11.1-3812-gef4eebff7d4 2.11.1

### Custom Code

No

### OS Platform and Distribution

Arch Linux (EndeavourOS)

### Python version

3.10.11

### CUDA/cuDNN version

ROCm 5.4.3

### GPU model and memory

Radeon VII/16 GiB

### Current Behaviour?

The title suffices. A workaround is to ensure `tensorflow` is imported before `torch`.

### Standalone code to reproduce the issue

```shell
python -c "import torch; import tensorflow as tf; tf.zeros(1)"
```

### Relevant log output

```shell
2023-05-19 22:22:33.756830: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
v2.11.1-3812-gef4eebff7d4 2.11.1
(sd) [habbasi@hameer-imacpro11 kohya-trainer]$ python -c "import tensorflow as tf; import torch; tf.zeros(1)"
2023-05-19 22:25:50.708366: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-19 22:25:53.172076: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:843] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-05-19 22:25:53.172177: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:843] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-05-19 22:25:53.172216: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:843] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-05-19 22:25:53.172542: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-19 22:25:53.173978: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:843] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-05-19 22:25:53.174095: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:843] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-05-19 22:25:53.174137: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:843] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/habbasi/mambaforge/envs/sd/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/habbasi/mambaforge/envs/sd/lib/python3.10/site-packages/tensorflow/python/eager/context.py", line 588, in ensure_initialized
    context_handle = pywrap_tfe.TFE_NewContext(opts)
tensorflow.python.framework.errors_impl.InternalError: hipGetDevice() failed. Status: invalid device ordinal
```
</details>

xref pytorch/pytorch#101900

**Comment by tilakrayal** [comment]
@hameerabbasi,
Thank you for the issue. This problem is not there in Colab which has both TF 2.12 and Torch 2.0. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/3c935855712bb540bb8d202103b7e536/untitled1164.ipynb).

Could you please take a look at this comment from the developer and the issue is still open.
https://github.com/tensorflow/tensorflow/issues/60109#issuecomment-1500575888

Thank you!

**Comment by hameerabbasi** [comment]
I think that issue is different, for a number of reasons:
- I have to endure TF is imported first, not the other way around
- Nothing hangs, I actually get a HIP error which leads me to believe that the issue is ROCm/AMD related, but I do not have an NVidia GPU available to check on

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

**Comment by hameerabbasi** [comment]
Hello! I'm travelling and should have access to the ROCm system next week; however it contains a Radeon VII which doesn't work with the latest ROCm.

I will close this as I believe it stemmed from different C++ ABIs used by PyTorch and TensorFlow; which changed with the 2.7 release I believe.
