### ISSUE TITLE
RNN Tutorial Code cant find sample data

### ISSUE THREAD

**Issue by sshleifer** [tensorflow/tensorflow#6068]
Followed the directions here on my mac
https://www.tensorflow.org/versions/master/tutorials/recurrent/index.html#recurrent-neural-networks

```
cd tensorflow/models/rnn/ptb
python ptb_word_lm.py --data_path=/tmp/simple-examples/data/ --model small
```

```
Traceback (most recent call last):
  File "ptb_word_lm.py", line 368, in <module>
    tf.app.run()
  File "/Users/shleifer/flow/kensho-learn/kml/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "ptb_word_lm.py", line 315, in main
    raw_data = reader.ptb_raw_data(FLAGS.data_path)
  File "/Users/shleifer/flow/kensho-learn/kml/lib/python2.7/site-packages/tensorflow/models/rnn/ptb/reader.py", line 73, in ptb_raw_data
    word_to_id = _build_vocab(train_path)
  File "/Users/shleifer/flow/kensho-learn/kml/lib/python2.7/site-packages/tensorflow/models/rnn/ptb/reader.py", line 34, in _build_vocab
    data = _read_words(filename)
  File "/Users/shleifer/flow/kensho-learn/kml/lib/python2.7/site-packages/tensorflow/models/rnn/ptb/reader.py", line 30, in _read_words
    return f.read().decode("utf-8").replace("\n", "<eos>").split()
  File "/Users/shleifer/flow/kensho-learn/kml/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 106, in read
    self._preread_check()
  File "/Users/shleifer/flow/kensho-learn/kml/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 73, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/Users/shleifer/flow/kensho-learn/kml/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: /tmp/simple-examples/data/ptb.train.txt
```

Versions:

tensorflow==0.12.0rc0

I think I am missing something simple. Where should the data directory be? thanks

**Comment by FCInter** [comment]
You can just cd to the directory where you put the code files, and run the following command:
`wget http://www.fit.vutbr.cz/~imikolov/rnnlm/simple-examples.tgz`
`tar xvf simple-examples.tgz`
`python ptb_word_lm.py --data_path=simple-examples/data/`
This gets the code to find the data file. However, you may find the code is still not executable and reports new errors like "module does not have an attribute 'deprecate' ".

**Comment by xusong2008** [comment]
maybe deprecated?

**Comment by sshleifer** [comment]
yeah i figured it out fee free to close

**Comment by aselle** [comment]
@wolffg  could we update this in the docs to not have "/tmp" in the example command line maybe just "simple-examples/..." so that it is clear it is relative from where you tar xvfz'd it (maybe add a comment)

**Comment by chrisrytting** [comment]
The same issue for me was solved by getting rid of the `/tmp`

**Comment by saurabhvyas** [comment]
Thank you @chrisrytting  @aselle

**Comment by wolffg** [comment]
I updated this for clarity, please see #9059.
