### ISSUE TITLE
Inconsistency-bug in `tf.raw_ops.Acos` between jit mode and normal mode

### ISSUE THREAD

**Issue by Lyutoon** [tensorflow/tensorflow#60764]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.14.0

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 20.04

### Mobile device

Ubuntu 20.04

### Python version

3.8.10

### Current Behaviour?

There is an inconsistency bug between **jit compile mode** and **normal mode** in `tf.raw_ops.Acos` which result in inconsistent computational result (mainly occur while dtype is complex, it seems that there are something wrong in the support of complex number).
But expectedly, the computational result have to be the same.

### Standalone code to reproduce the issue

```shell
import os 
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import tensorflow as tf
import numpy as np

x = tf.cast(tf.random.uniform([2, 1, 3, 4], dtype=tf.dtypes.float32, maxval=60000), dtype=tf.complex128)

@tf.function(jit_compile=True)
def fuzz_jit():
    y = tf.raw_ops.Acos(
        x = x
    )
    return y

def fuzz_normal():
    y = tf.raw_ops.Acos(
        x = x
    )
    return y

y1 = fuzz_jit()
print('[+] JIT ok')
y2 = fuzz_normal()
print('[+] Normal ok')
np.testing.assert_allclose(y1.numpy(), y2.numpy(), rtol=1e-4, atol=1e-4)
```

### Relevant log output

```shell
% python test.py
[+] JIT ok
[+] Normal ok
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    np.testing.assert_allclose(y1.numpy(), y2.numpy(), rtol=1e-4, atol=1e-4)
  File "/usr/local/lib/python3.8/dist-packages/numpy/testing/_private/utils.py", line 1530, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/usr/local/lib/python3.8/dist-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.0001, atol=0.0001

Mismatched elements: 24 / 24 (100%)
Max absolute difference: 23.34874158
Max relative difference: 2.00000002
 x: array([[[[4.020810e-07+11.649195j, 3.918355e-07+11.63629j ,
          6.167066e-09 +9.56048j , 2.750275e-10 +8.005427j],
         [3.286194e-07+11.548319j, 8.673153e-08+10.882277j,...
 y: array([[[[0.-11.649196j, 0.-11.63629j , 0. -9.56048j , 0. -8.005427j],
         [0.-11.548319j, 0.-10.882278j, 0.-10.521193j, 0.-10.125081j],
         [0.-10.732039j, 0. -7.92731j , 0.-11.674371j, 0.-11.332818j]]],...
```
</details>

**Comment by Lyutoon** [comment]
Hi @tilakrayal 
Thanks for your reply! I've checked your colab code. But the main reason I open this issue is that the outputs between JIT mode and normal mode corresponding to the same input are inconsistent. However, from my perspective, no matter when, the operator must produce the same output when it is given the same input.
What do you think?
Thanks!

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
