### ISSUE TITLE
TF throws: "'visible_device_list' listed an invalid Device id" when using non-GPU PluggableDevices

### ISSUE THREAD

**Issue by mergian** [tensorflow/tensorflow#60895]
### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

2.12.0

### Custom Code

Yes

### OS Platform and Distribution

Linux CentOS

### CUDA/cuDNN version

11.8

### Current Behaviour?

When using PluggableDevice API together with GPU devices, TF crashes with `tensorflow.python.framework.errors_impl.InvalidArgumentError: 'visible_device_list' listed an invalid Device id '2' but visible device count is 2` when calling `tf.device('/GPU:0')`

**For reproducing the error, it is necessary to have a PluggableDevice Plugin loaded and to have GPUs within the same system!!!**

Here the list of devices within my system:
```python3
# tf.config.list_physical_devices()
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:VE:0', device_type='VE'), PhysicalDevice(name='/physical_device:VE:1', device_type='VE'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
```

I traced down the error to be thrown here. It gets thrown in
https://github.com/tensorflow/tensorflow/blob/e32f5b90ec16e88b23be8a5189e52ea9a420e999/tensorflow/tsl/framework/device_id_utils.cc#L46

However, it is caused by wrong values stored in the gpu_options, which get initialized here:
https://github.com/tensorflow/tensorflow/blob/0db597d0d758aba578783b5bf46c889700a45085/tensorflow/python/eager/context.py#L1206

The list of gpu_devices and ALL pluggable_devices get combined, even if they are not of the same device_type. So the list of `compatible_devices` will be:
```
[
	PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'),
	PhysicalDevice(name='/physical_device:VE:0', device_type='VE'),
	PhysicalDevice(name='/physical_device:VE:1', device_type='VE')
]
```

This causes the `visible_device_list` to be `['0', '1', '2']`, which contains invalid GPU device indices. These then get passed to `ParseVisibleDeviceList`, which throws this error.

To fix this error, it suffices to change this line:
https://github.com/tensorflow/tensorflow/blob/0db597d0d758aba578783b5bf46c889700a45085/tensorflow/python/eager/context.py#L1216

and replace it to:
```python
if dev not in gpu_devices and dev.device_type == "GPU":
```

This way, the list of `compatible_devices` will only populated with other GPUs, not with any other device types.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
print(*tf.config.list_physical_devices(), sep='\n')
tf.device('/GPU:0')
```

### Relevant log output

```shell
PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')
PhysicalDevice(name='/physical_device:VE:0', device_type='VE')
PhysicalDevice(name='/physical_device:VE:1', device_type='VE')
PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/.../.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 5577, in device_v2
    return device(device_name)
  File "/.../.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 5526, in device
    return context.device(device_name_or_function)
  File "/.../.local/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 2348, in device
    ensure_initialized()
  File "/.../.local/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 2143, in ensure_initialized
    context().ensure_initialized()
  File "/.../.local/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 583, in ensure_initialized
    context_handle = pywrap_tfe.TFE_NewContext(opts)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 'visible_device_list' listed an invalid Device id '2' but visible device count is 2
```

**Comment by SuryanarayanaY** [comment]
Hi @mergian ,

Thanks for reporting. I think reproduction of this issue needs non-NVIDIA GPUs,If I am not wrong. I am assuming that you have non-GPU pluggable devices which are actually identified as GPU by TF which is the problem,right?

I did refer some resources [gpu-plugins ](https://www.tensorflow.org/install/gpu_plugins) and [pluggable-device-for-tensorflow.md](https://github.com/tensorflow/community/blob/master/rfcs/20200624-pluggable-device-for-tensorflow.md).As per my understanding from here if the pluggable device registered as GPU then it shall be added  to GPU list and implementation done accordingly. 

As per my understanding there might be non GPU pluggable devices also which can be usable by TF. At least this is my understanding from the `.readme` file attached earlier in this comment and correct me if I am wrong. In Your proposed code all the devices which are not registered as GPU will be ignored right.I think in that case we need to check for more. Please share your thoughts .

**Comment by mergian** [comment]
Dear @SuryanarayanaY 

yes you are correct.

Our PluggableDevice plugin adds non-GPU devices. The code that I marked however assumes all PluggableDevices to be GPUs, therefore the `visible_devices` list will be populated with invalid ids, which then later cause errors when being checked internally.

My proposal is, that for this particular code pice, that looks for TensorFlow-Native-GPUs and PluggableDevice-GPUs and combines them, to check if the `.device_type` is really `GPU`.

If needed it should be possible to create a fake PluggableDevice-Plugin, that creates non existing devices. Then you could reproduce this error even without having our devices available. But I think could take some hours to do so.

**Comment by SuryanarayanaY** [comment]
Hi @mergian ,

Thanks for confirmation. With your proposal only PluggableDevice-GPUs can be detectable y TF. I doubt whether this implementation only limited to GPUs as .[readme](https://github.com/tensorflow/community/blob/master/rfcs/20200624-pluggable-device-for-tensorflow.md) talks about more than GPU type devices. I would like to hear from dev team on this.But I feel there is some cases not covered in implementation.

Thanks!

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
