### ISSUE TITLE
NoClassDefFoundError: GpuDelegateFactory$Options not found

### ISSUE THREAD

**Issue by ZTMIDGO** [tensorflow/tensorflow#61091]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

False

### Source

source

### Tensorflow Version

TF2.12

### Custom Code

Yes

### OS Platform and Distribution

Android 12

### Mobile device

Android 12

### Current Behaviour?

The GPU is not being used correctly.

### Standalone code to reproduce the issue

```shell
implementation 'org.tensorflow:tensorflow-lite:2.12.0'
 implementation 'org.tensorflow:tensorflow-lite-gpu:2.12.0'

Interpreter.Options options = new Interpreter.Options();
options.addDelegate(new GpuDelegate());

File file = new File(getFilesDir().getAbsolutePath()+"/movenet_thunder.tflite");
Interpreter interpreter = new Interpreter(file, options);
```

### Relevant log output

```shell
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.litesnap.open.flow.diffusion, PID: 13553
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/tensorflow/lite/gpu/GpuDelegateFactory$Options;
        at org.tensorflow.lite.gpu.GpuDelegate.<init>(GpuDelegate.java:53)
        at com.litesnap.open.flow.diffusion.MainActivity$1.onClick(MainActivity.java:27)
        at android.view.View.performClick(View.java:7792)
        at android.widget.TextView.performClick(TextView.java:16112)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1131)
        at android.view.View.performClickInternal(View.java:7769)
        at android.view.View.access$3800(View.java:910)
        at android.view.View$PerformClick.run(View.java:30218)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8663)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.tensorflow.lite.gpu.GpuDelegateFactory$Options" on path: DexPathList[[zip file "/data/app/~~oMimw9IoQp1ajJTsKEnrxQ==/com.litesnap.open.flow.diffusion-s0YwqVUhGU20kZbxCKdqXw==/base.apk"],nativeLibraryDirectories=[/data/app/~~oMimw9IoQp1ajJTsKEnrxQ==/com.litesnap.open.flow.diffusion-s0YwqVUhGU20kZbxCKdqXw==/lib/arm64, /data/app/~~oMimw9IoQp1ajJTsKEnrxQ==/com.litesnap.open.flow.diffusion-s0YwqVUhGU20kZbxCKdqXw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at org.tensorflow.lite.gpu.GpuDelegate.<init>(GpuDelegate.java:53) 
        at com.litesnap.open.flow.diffusion.MainActivity$1.onClick(MainActivity.java:27) 
        at android.view.View.performClick(View.java:7792) 
        at android.widget.TextView.performClick(TextView.java:16112) 
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1131) 
        at android.view.View.performClickInternal(View.java:7769) 
        at android.view.View.access$3800(View.java:910) 
        at android.view.View$PerformClick.run(View.java:30218) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:226) 
        at android.os.Looper.loop(Looper.java:313) 
        at android.app.ActivityThread.main(ActivityThread.java:8663) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 
```
</details>

**Comment by tilakrayal** [comment]
@ZTMIDGO,
Could you please provide the complete standalone code to reproduce the issue and also it helps to analyse the issue in an effective way. Thank you!
