### ISSUE TITLE
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by KaushalNaresh** [tensorflow/tensorflow#61250]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

1.0.1

### Custom code

Yes

### OS platform and distribution

Ubuntu 20.04

### Python version

3.6

### GCC/compiler version

9.4.0

### CUDA/cuDNN version

nvcc --version gives 10.1 nvidia-smi gives CUDA Version: 12.2 

### Current behavior?

ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory

### Standalone code to reproduce the issue

```shell
This error occured when I imported tensorflow
import tensorflow as tf

To resolve this issue I have set my $CUDA_HOME=/usr/lib/cuda/
and $LD_LIBRARY_PATH=usr/lib/cuda/lib64

But surprisingly usr/lib/cuda/lib64 is empty. I dont have cuda folder in usr/local directory.
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/nkaushal/anaconda3/envs/lipnet3.6/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/nkaushal/anaconda3/envs/lipnet3.6/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/home/nkaushal/anaconda3/envs/lipnet3.6/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/home/nkaushal/anaconda3/envs/lipnet3.6/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/nkaushal/anaconda3/envs/lipnet3.6/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nkaushal/anaconda3/envs/lipnet3.6/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/nkaushal/anaconda3/envs/lipnet3.6/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/nkaushal/anaconda3/envs/lipnet3.6/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/nkaushal/anaconda3/envs/lipnet3.6/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/home/nkaushal/anaconda3/envs/lipnet3.6/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/home/nkaushal/anaconda3/envs/lipnet3.6/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/nkaushal/anaconda3/envs/lipnet3.6/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by SuryanarayanaY** [comment]
Hi @KaushalNaresh ,

Could you please confirm the TF version you are using? 

Could you please refer to the similar issues attached here [#5344](https://github.com/tensorflow/tensorflow/issues/5343) and [#4944](https://github.com/BVLC/caffe/issues/4944).

If you are using TF1.0.* supported CUDA version is CUDA-8 and it seems you have installed CUDA 12.2 which is not compatible. Please refer to tested configurations [here](https://www.tensorflow.org/install/source#gpu).



tensorflow_gpu-1.0.0 | 2.7, 3.3-3.6 | GCC 4.8 | Bazel 0.4.2 | 5.1 | 8
-- | -- | -- | -- | -- | --


Also 1.x versions not supported now and hence request you to use latest versions of Tf2.x.

Thanks!

**Comment by KaushalNaresh** [comment]
Hi I was using tf-gpu 1.0.1 because I was trying to replicate one old repository.

I will try to install compatible TF for my CUDA but the link you have provided doesn't have CUDA 12.2 so can you point me out the correct version of tf-gpu that goes well with my CUDA??

Thanks

**Comment by SuryanarayanaY** [comment]
Hi @KaushalNaresh ,

For the tf-gpu 1.0.1 version required CUDA version has to be CUDA 8 and cuDNN 5.1 versions.

Because TF documentation instruction updates and keep them for latest stable release only.

You may refer to [Nvidia](https://developer.nvidia.com/cuda-80-ga2-download-archive) website for this or can search in internet for same.Since the version is too old I am not sure of official instructions at that time.

Thanks!

**Comment by SuryanarayanaY** [comment]
Hi @KaushalNaresh ,

Tensorflow users has to follow tested [configurations](https://www.tensorflow.org/install/source#gpu) mentioned in documentation. Each version of TF will be tested with some CUDA and cuDNN versions and users has to install those versions only as other advanced versions are yet to test with TF and may raise compatibility issues.

For latest version(TF2.13) CUDA 11.8 is the tested version hence CUDA>11.8 may raise compatibility issues.Hence you have to stick to the tested configurations only. In future versions TF might be tested with CUDA 12.2 also but for now you need to use tested configurations only.

Thanks!
