### ISSUE TITLE
`MeanAbsoluteError` returns "nan" when given empty tensors

### ISSUE THREAD

**Issue by FGRCL** [tensorflow/tensorflow#61281]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

v1.12.1-96880-g4499c968316 2.14.0-dev20230714

### Custom code

No

### OS platform and distribution

macOS 13.2.1

### Mobile device

v

### Python version

3.11.4

### Bazel version

n/a

### GCC/compiler version

n/a

### CUDA/cuDNN version

n/a

### GPU model and memory

n/a

### Current behavior?

When using `MeanAbsoluteError.update_state(y_true, y_pred)` if `y_true` and `y_pred` happen to be empty tensors of size 0, all subsequent call to   `MeanAbsoluteError.result()` will yield "nan" until the internal state of the metric is reset. 

Since calling `MeanAbsoluteError.result()` before any result has been passed returns 0.0, I would expect empty tensors to be ignored when passed to `MeanAbsoluteError.update_state(y_true, y_pred)`.

I've only tested this issue with `MeanAbsoluteError`, but it seems likely that it would happen with other metrics.

### Standalone code to reproduce the issue

```shell
from unittest import TestCase

from tensorflow import constant, float32, reduce_mean
from tensorflow import ragged
from tensorflow.python.keras.metrics import MeanAbsoluteError


class TestEmptyTensorMetrics(TestCase):
    def test_no_data(self):
        metric = MeanAbsoluteError()

        result = metric.result()

        expected = constant(0.0)
        self.assertEqual(expected, result)

    def test_empty_array(self):
        metric = MeanAbsoluteError()
        y_true = constant([])
        y_pred = constant([])

        metric.update_state(y_true, y_pred)
        result = metric.result()

        expected = constant(0.0)
        self.assertEqual(expected, result)

    def test_multiple_batches(self):
        metric = MeanAbsoluteError()
        y_true_batches = constant([
            [39, 22, 73],
            [22, 50, 23]
        ], dtype=float32)
        y_pred_batches = constant([
            [80, 59, 52],
            [87, 8, 38],
        ], dtype=float32)

        for y_true, y_pred in zip(y_true_batches, y_pred_batches):
            metric.update_state(y_true, y_pred)
        result = metric.result()

        expected = reduce_mean(abs(y_true_batches - y_pred_batches))
        self.assertAlmostEqual(expected.numpy(), result.numpy(), 5)

    def test_multiple_batches_with_empty_array(self):
        metric = MeanAbsoluteError()
        y_true_batches = ragged.constant([
            [39, 22, 73],
            [],
            [22, 50, 23]
        ], dtype=float32)
        y_pred_batches = ragged.constant([
            [80, 59, 52],
            [],
            [87, 8, 38],
        ], dtype=float32)

        for y_true, y_pred in zip(y_true_batches, y_pred_batches):
            metric.update_state(y_true, y_pred)
        result = metric.result()

        expected = reduce_mean(abs(y_true_batches - y_pred_batches).flat_values)
        self.assertAlmostEqual(expected.numpy(), result.numpy(), 5)
```
```


### Relevant log output

```shell
2023-07-14 14:54:43.650532: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:tensorflow:From /Users/francois/.local/share/virtualenvs/sandbox-w3BOTv5B/lib/python3.11/site-packages/tensorflow/python/ops/distributions/distribution.py:259: ReparameterizationType.__init__ (from tensorflow.python.ops.distributions.distribution) is deprecated and will be removed after 2019-01-01.
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
WARNING:tensorflow:From /Users/francois/.local/share/virtualenvs/sandbox-w3BOTv5B/lib/python3.11/site-packages/tensorflow/python/ops/distributions/bernoulli.py:165: RegisterKL.__init__ (from tensorflow.python.ops.distributions.kullback_leibler) is deprecated and will be removed after 2019-01-01.
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
test_empty_array (nanbug.TestEmptyTensorMetrics.test_empty_array) ... FAIL
test_multiple_batches (nanbug.TestEmptyTensorMetrics.test_multiple_batches) ... ok
test_multiple_batches_with_empty_array (nanbug.TestEmptyTensorMetrics.test_multiple_batches_with_empty_array) ... FAIL
test_no_data (nanbug.TestEmptyTensorMetrics.test_no_data) ... ok

======================================================================
FAIL: test_empty_array (nanbug.TestEmptyTensorMetrics.test_empty_array)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/francois/Documents/sandbox/nanbug.py", line 26, in test_empty_array
    self.assertEqual(expected, result)
AssertionError: <tf.Tensor: shape=(), dtype=float32, numpy=0.0> != <tf.Tensor: shape=(), dtype=float32, numpy=nan>

======================================================================
FAIL: test_multiple_batches_with_empty_array (nanbug.TestEmptyTensorMetrics.test_multiple_batches_with_empty_array)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/francois/Documents/sandbox/nanbug.py", line 64, in test_multiple_batches_with_empty_array
    self.assertAlmostEqual(expected.numpy(), result.numpy(), 5)
AssertionError: 36.833332 != nan within 5 places (nan difference)

----------------------------------------------------------------------
Ran 4 tests in 0.104s

FAILED (failures=2)
```

**Comment by SuryanarayanaY** [comment]
Hi @FGRCL ,

I have gone through the issue and replicated the reported behaviour and attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/fff1cc34b602cdc91dcafb5f3a0051ba/61281_nightly.ipynb) for reference. What I observed is even with Numpy for empty arrays Numpy also generating `nan` only which is same as TF behaviour with empty Tensors of shape=(0,) .

This is a different case which needs to be discussed. Tensorflow implemented numpy like behaviour for empty tensors.

IMO, Assertion error is expected since NaN is some undefined value.

Can you check the numpy behaviour and comment. AFAIK it's possible to implement exception of ValueError if the input is empty tensor/array. But we need to take Dev team confirmation on this.

Thanks!

**Comment by SuryanarayanaY** [comment]
Hi @FGRCL ,

AFAIK by default `reset_state()` will be called at the end of each epoch/step during training. So in that case this should not be a problem. WDYT ?

**Comment by SuryanarayanaY** [comment]
Hi @FGRCL ,

Apologies.This got slipped from my TODO list.This seems change in API design and needs to be addressed in [Keras](https://github.com/keras-team/keras/issues) repo. Would you mind opening this issue at Keras repo? Thanks!
