### ISSUE TITLE
AttributeError: cython_sources when installing tflite-model-maker

### ISSUE THREAD

**Issue by ljmerza** [tensorflow/tensorflow#61337]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

v2.13.0-rc2-7-g1cb1a030a62 2.13.0

### Custom code

Yes

### OS platform and distribution

ubuntu 20

### Python version

 3.10.6

### Current behavior?

when trying to install `tflite-model-maker` i get an error:

```
running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/home/cubxi/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/cubxi/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/cubxi/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-koysxeoc/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-koysxeoc/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-koysxeoc/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/tmp/pip-build-env-koysxeoc/overlay/local/lib/python3.10/dist-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-koysxeoc/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-koysxeoc/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-koysxeoc/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-koysxeoc/overlay/local/lib/python3.10/dist-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-koysxeoc/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-koysxeoc/overlay/local/lib/python3.10/dist-packages/setuptools/command/egg_info.py", line 314, in run
          self.find_sources()
        File "/tmp/pip-build-env-koysxeoc/overlay/local/lib/python3.10/dist-packages/setuptools/command/egg_info.py", line 322, in find_sources
          mm.run()
        File "/tmp/pip-build-env-koysxeoc/overlay/local/lib/python3.10/dist-packages/setuptools/command/egg_info.py", line 551, in run
          self.add_defaults()
        File "/tmp/pip-build-env-koysxeoc/overlay/local/lib/python3.10/dist-packages/setuptools/command/egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "/tmp/pip-build-env-koysxeoc/overlay/local/lib/python3.10/dist-packages/setuptools/command/sdist.py", line 104, in add_defaults
          super().add_defaults()
        File "/tmp/pip-build-env-koysxeoc/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/tmp/pip-build-env-koysxeoc/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "<string>", line 201, in get_source_files
        File "/tmp/pip-build-env-koysxeoc/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
```

### Standalone code to reproduce the issue

```shell
run `pip install -q tflite-model-maker`
```

**Comment by meetkarthiksv89** [comment]
facing this on macOS too. Any solutions for this?

**Comment by sushreebarsa** [comment]
@ljmerza There are a few dependencies like numpy that need a specific version installation. Did you try to upgrade the numpy version by using` pip install numpy==1.23.4`. Can you also use colab fallback as a workaround?
Thank you!

**Comment by temilolafaith** [comment]
@sushreebarsa I tried your fix and I'm still running into same error

**Comment by JohnFarl** [comment]
> Hi @ljmerza @temilolafaith
> 
> There is a known issue of tflite model maker installation if you are using python >=3.10. Please use Python 3.9 or [Mediapipe Model Maker](https://developers.google.com/mediapipe/solutions/model_maker) as a workaround.
> 
> Thanks.

Also mediapipe-model-maker is broken. On windows I get this error during setup when it starts to get PyYAML dependency

```
Downloading PyYAML-5.4.1.tar.gz (175 kB)
     ---------------------------------------- 175.1/175.1 kB 2.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.

...
\Lib\site-packages\setuptools\_distutils\cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
```

**Comment by pjpratik** [comment]
Hi @JohnFarl 

Could you please try again as I was successfully able to install mediapipe model maker on ubuntu(colab). Please find the [gist](https://colab.research.google.com/gist/pjpratik/dbb294b5537ee15bde72ca1471f0d834/61337.ipynb).

Thanks.

**Comment by JohnFarl** [comment]
> Hi @JohnFarl
> 
> Could you please try again as I was successfully able to install mediapipe model maker on ubuntu(colab). Please find the [gist](https://colab.research.google.com/gist/pjpratik/dbb294b5537ee15bde72ca1471f0d834/61337.ipynb).
> 
> Thanks.

I confirm that mediapipe model maker installation fails on Windows. (Python 3.11)

**Comment by pkgoogle** [comment]
Hi @ljmerza, I was able to install if I downgraded Python to 3.9.17, can you try that out to see if you are able to continue that way?

If you are using conda you can do so like this:
```py
conda create -n your_env_name python=3.9
conda activate your_env_name
pip install -q tflite-model-maker
```

**Comment by ChurikiTenna** [comment]
> Hi @ljmerza @temilolafaith
> 
> There is a known issue of tflite model maker installation if you are using python >=3.10. Please use Python 3.9 or [Mediapipe Model Maker](https://developers.google.com/mediapipe/solutions/model_maker) as a workaround.
> 
> Thanks.

Downgraded from 3.10.9 to Python 3.9.6. 
Still experiencing the same error.

% python3 --version
Python 3.9.6

**Comment by JohnFarl** [comment]
Problem is still here unsolved. This automatic issue close should be disabled or set to a reasonable amount of time.

**Comment by pkgoogle** [comment]
Hi @lu-wang-g, assigning this to you to consolidate tflite-model-maker issues. Thanks.

**Comment by bduyng** [comment]
I got the same issue and was able to fix by using this [hack](https://discuss.python.org/t/getting-requirements-to-build-wheel-did-not-run-successfully-exit-code-1/30365/2):

```bash
echo "Cython<3" > cython_constraint.txt
$ PIP_CONSTRAINT=cython_constraint.txt pip install "tflite-model-maker"
```

**Comment by vpmalley** [comment]
I was able to solve that dependency issue by installing `cython` and `pyyaml` before installing the model maker, based on [that answer on Stackoverflow](https://stackoverflow.com/a/77491847/1181162), with:
```
$ pip install "cython<3.0.0" wheel
$ pip install "pyyaml==5.4.1" // pip install "pyyaml<6.0" probably also works
```

Until the next dependency conflict...

**Comment by katie1006** [comment]
What ended up working for me was a combination of @bduyng and @vpmalley's solutions.

This is what I did, in order
```
pip install "cython<3.0.0" wheel  // succeeded

pip install "pyyaml==5.4.1"  // failed with the same error

echo "Cython<3" > cython_constraint.txt
PIP_CONSTRAINT=cython_constraint.txt pip install "pyyaml==5.4.1"  // succeeded

PIP_CONSTRAINT=cython_constraint.txt pip install "tflite-model-maker"  // failed with the same error

pip install "tflite-model-maker"  // worked!
```

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
