### ISSUE TITLE
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by Nithin061** [tensorflow/tensorflow#61379]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

v2.13.0

### Custom code

Yes

### OS platform and distribution

Linux

### Python version

3.8

### Bazel version

5.3.0

### GCC/compiler version

9.4.0

### Current behavior?

WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/pilotfiber.dl.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz failed: class javax.net.ssl.SSLHandshakeException PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
WARNING: Download from https://pilotfiber.dl.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz failed: class javax.net.ssl.SSLHandshakeException PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
ERROR: An error occurred during the fetch of repository 'gif':
   Traceback (most recent call last):
        File "/home/hvn1kor/mnt/ws/tensorflow/third_party/repo.bzl", line 73, column 33, in _tf_http_archive_impl
                ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/pilotfiber.dl.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz, https://pilotfiber.dl.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz] to /home/hvn1kor/.cache/bazel/_bazel_hvn1kor/91c0f0c6277b7e83e39dca13c8fc40a9/external/gif/temp6645244175742553415/giflib-5.2.1.tar.gz: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
ERROR: /home/hvn1kor/mnt/ws/tensorflow/WORKSPACE:15:14: fetching _tf_http_archive rule //external:gif: Traceback (most recent call last):        File "/home/hvn1kor/mnt/ws/tensorflow/third_party/repo.bzl", line 73, column 33, in _tf_http_archive_impl
                ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/pilotfiber.dl.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz, https://pilotfiber.dl.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz] to /home/hvn1kor/.cache/bazel/_bazel_hvn1kor/91c0f0c6277b7e83e39dca13c8fc40a9/external/gif/temp6645244175742553415/giflib-5.2.1.tar.gz: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
ERROR: /home/hvn1kor/mnt/ws/tensorflow/tensorflow/tools/pip_package/BUILD:205:10: //tensorflow/tools/pip_package:licenses depends on @gif//:COPYING in repository @gif which failed to fetch. no such package '@gif//': java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/pilotfiber.dl.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz, https://pilotfiber.dl.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz] to /home/hvn1kor/.cache/bazel/_bazel_hvn1kor/91c0f0c6277b7e83e39dca13c8fc40a9/external/gif/temp6645244175742553415/giflib-5.2.1.tar.gz: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed   
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted:
INFO: Elapsed time: 35.731s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 4 targets configured)

### Standalone code to reproduce the issue

```shell
bazel build //tensorflow/tools/pip_package:build_pip_package
```

**Comment by Nithin061** [comment]
hi @SuryanarayanaY,

Can youplease help m to resovle the issue

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
