### ISSUE TITLE
Distributed training with parameter servers example using a single binary

### ISSUE THREAD

**Issue by ali-raza-tariq** [tensorflow/tensorflow#61457]
Hello everyone! I am sorry if this is a duplicate issue but from my considerable search - I could not find a single end-to-end distributed parameter-server example to run using tensorflow (using the keras api with `.fit()` method). Also, for some reason - the documentation for parameter-server strategy seems a lot more confusing and difficult to get started with, compared to multi-worker strategy. 

I have been running training jobs using the estimator api before and now trying to update it to TF2.x style distributed training job with parameter-server training strategy using a single binary file for all workers and parameter-servers. I started with the example in documentation here (https://www.tensorflow.org/tutorials/distribute/parameter_server_training) and modified the code to be used as a single binary. 

Code:
```
import tensorflow_datasets as tfds
import tensorflow as tf

import os

cluster_resolver = tf.distribute.cluster_resolver.TFConfigClusterResolver()
if cluster_resolver.task_type in ("worker", "ps"):
  # Start a TensorFlow server and wait.
  server = tf.distribute.Server(cluster_resolver.cluster_spec(),
                                      job_name=cluster_resolver.task_type,
                                      task_index=cluster_resolver.task_id,
                                      protocol=cluster_resolver.rpc_layer or "grpc",
                                      start=True)
  server.join()
else:
  ## parameter-server
  strategy = tf.distribute.ParameterServerStrategy(cluster_resolver=cluster_resolver)
  global_batch_size = 64
  x = tf.random.uniform((10, 10))
  y = tf.random.uniform((10,))
  dataset = tf.data.Dataset.from_tensor_slices((x, y)).shuffle(10).repeat()
  dataset = dataset.batch(global_batch_size)
  dataset = dataset.prefetch(2)
  with strategy.scope():
    model = tf.keras.models.Sequential([tf.keras.layers.Dense(10)])
    model.compile(tf.keras.optimizers.legacy.SGD(), loss="mse", steps_per_execution=10)
  working_dir = "./my_working_dir"
  log_dir = os.path.join(working_dir, "log")
  ckpt_filepath = os.path.join(working_dir, "ckpt")
  backup_dir = os.path.join(working_dir, "backup")
  callbacks = [
    tf.keras.callbacks.TensorBoard(log_dir=log_dir),
    tf.keras.callbacks.ModelCheckpoint(filepath=ckpt_filepath),
    tf.keras.callbacks.BackupAndRestore(backup_dir=backup_dir),
  ]
  model.fit(dataset, epochs=5, steps_per_epoch=20, callbacks=callbacks)
```

To my understanding, all workers and paramter-servers will start and wait for chief to assign the tasks. Chief or coordinator (documentation uses them interchangeably but is there any difference between the two?) will automatically divide the work based on the information it gets from `cluster_resolver` (let me know if that's wrong interpretation). In any case, I would highly appreciate if someone can point out what I am doing wrong in this example because I have not been able to get it to work!

**Comment by tilakrayal** [comment]
@ali-raza-tariq,
**ClusterResolvers** are a way for TensorFlow to communicate with various cluster management systems (e.g. GCE, AWS, etc...) and gives TensorFlow necessary information to set up distributed training.

By letting TensorFlow communicate with these systems, we will be able to automatically discover and resolve IP addresses for various TensorFlow workers. This will eventually allow us to automatically recover from underlying machine failures and scale TensorFlow worker clusters up and down.

Could you please take a look at the official document for the information on cluster_resolver.
https://www.tensorflow.org/api_docs/python/tf/distribute/cluster_resolver/ClusterResolver
https://www.tensorflow.org/api_docs/python/tf/distribute/cluster_resolver/TFConfigClusterResolver

Also provide the complete error log to debug the issue. Thank you!

**Comment by ali-raza-tariq** [comment]
Hi @tilakrayal thank you for your response. First of all, does this mean the `Chief` no longer participates in the training? Previously, `Chief` (also referred to as `worker0`) used to be just another worker with some extra coordination responsibilities. Secondly, kindly let me know if there are any end to end examples using using `Keras` new style of code (specifically for the `parameterServerStrategy`). This code is just an example using snippets of code I took from the tensorflow documentation from the link above. Which is why I shared the code to make sure I am not doing something fundamentally wrong in the training job. For the error log of this code, kindly look below:

```
2023-08-03 18:36:29.506681: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-03 18:36:32.165950: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:449] Started server with target: grpc://tfjob-keras-new1-chief-0.ali.svc:2222
Epoch 1/5
2023-08-03 18:36:34.137661: W tensorflow/core/distributed_runtime/rpc/grpc_worker_service.cc:510] RecvTensor cancelled for -7156144820392730089
/usr/local/lib/python3.8/dist-packages/tensorflow/python/data/ops/dataset_ops.py:468: UserWarning: To make it possible to preserve tf.data options across serialization boundaries, their implementation has moved to be part of the TensorFlow graph. As a consequence, the options value is in general no longer known at graph construction time. Invoking this method in graph mode retains the legacy behavior of the original implementation, but note that the returned value might not reflect the actual value of the options.
  warnings.warn("To make it possible to preserve tf.data options across "
Traceback (most recent call last):
  File "/app/keras_to_est_github_issue.py", line 39, in <module>
    model.fit(dataset, epochs=5, steps_per_epoch=20, callbacks=callbacks)
  File "/usr/local/lib/python3.8/dist-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/execute.py", line 53, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.NotFoundError: Graph execution error:

Detected at node 'SaveV2_1' defined at (most recent call last):
    File "/app/keras_to_est_github_issue.py", line 39, in <module>
      model.fit(dataset, epochs=5, steps_per_epoch=20, callbacks=callbacks)
    File "/usr/local/lib/python3.8/dist-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/src/engine/training.py", line 1809, in fit
      callbacks.on_epoch_end(epoch, epoch_logs)
    File "/usr/local/lib/python3.8/dist-packages/keras/src/callbacks.py", line 453, in on_epoch_end
      callback.on_epoch_end(epoch, logs)
    File "/usr/local/lib/python3.8/dist-packages/keras/src/callbacks.py", line 1483, in on_epoch_end
      self._save_model(epoch=epoch, batch=None, logs=logs)
    File "/usr/local/lib/python3.8/dist-packages/keras/src/callbacks.py", line 1577, in _save_model
      self.model.save(
    File "/usr/local/lib/python3.8/dist-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/src/engine/training.py", line 3000, in save
      saving_api.save_model(
    File "/usr/local/lib/python3.8/dist-packages/keras/src/saving/saving_api.py", line 149, in save_model
      return legacy_sm_saving_lib.save_model(
    File "/usr/local/lib/python3.8/dist-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/src/saving/legacy/save.py", line 168, in save_model
      saved_model_save.save(
    File "/usr/local/lib/python3.8/dist-packages/keras/src/saving/legacy/saved_model/save.py", line 98, in save
      saved_nodes, node_paths = save_lib.save_and_return_nodes(
    File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/checkpoint/functional_saver.py", line 404, in tf_function_save
      save_fn()
Node: 'SaveV2_1'
Detected at node 'SaveV2_1' defined at (most recent call last):
    File "/app/keras_to_est_github_issue.py", line 39, in <module>
      model.fit(dataset, epochs=5, steps_per_epoch=20, callbacks=callbacks)
    File "/usr/local/lib/python3.8/dist-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/src/engine/training.py", line 1809, in fit
      callbacks.on_epoch_end(epoch, epoch_logs)
    File "/usr/local/lib/python3.8/dist-packages/keras/src/callbacks.py", line 453, in on_epoch_end
      callback.on_epoch_end(epoch, logs)
    File "/usr/local/lib/python3.8/dist-packages/keras/src/callbacks.py", line 1483, in on_epoch_end
      self._save_model(epoch=epoch, batch=None, logs=logs)
    File "/usr/local/lib/python3.8/dist-packages/keras/src/callbacks.py", line 1577, in _save_model
      self.model.save(
    File "/usr/local/lib/python3.8/dist-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/src/engine/training.py", line 3000, in save
      saving_api.save_model(
    File "/usr/local/lib/python3.8/dist-packages/keras/src/saving/saving_api.py", line 149, in save_model
      return legacy_sm_saving_lib.save_model(
    File "/usr/local/lib/python3.8/dist-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/src/saving/legacy/save.py", line 168, in save_model
      saved_model_save.save(
    File "/usr/local/lib/python3.8/dist-packages/keras/src/saving/legacy/saved_model/save.py", line 98, in save
      saved_nodes, node_paths = save_lib.save_and_return_nodes(
    File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/checkpoint/functional_saver.py", line 404, in tf_function_save
      save_fn()
Node: 'SaveV2_1'
./my_working_dir/ckpt/variables/variables_temp; No such file or directory
         [[{{node SaveV2_1}}]]
Additional GRPC error information from remote target /job:ps/replica:0/task:0/device:CPU:0:
:{"created":"@1691087794.137754197","description":"Error received from peer ipv4:10.244.68.164:2222","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":" ./my_working_dir/ckpt/variables/variables_temp; No such file or directory\n\t [[{{node SaveV2_1}}]]","grpc_status":5} [Op:__inference_tf_function_save_1362]
2023-08-03 18:36:34.512110: I tensorflow/core/common_runtime/eager/kernel_and_device.cc:94] Ignoring error status when releasing multi-device function handle UNIMPLEMENTED: Releasing a multi-device component handle on a remote device is not yet implemented.
```

**Comment by ali-raza-tariq** [comment]
Hi @jamesmullenbach, thank you so much for the detailed response! yes it has cleared things up for me.
