### ISSUE TITLE
Error starting Tensorflow in Python

### ISSUE THREAD

**Issue by nnagarajan** [tensorflow/tensorflow#61688]
### Issue type

Others

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

2.13.0

### Custom code

Yes

### OS platform and distribution

Rocky Linux 8.8

### Python version

3.9

### CUDA/cuDNN version

12

### GPU model and memory

24 GB

### Current behavior?

Unable to load tensorflow in python with CUDA 12.2. Looking for some pointers

### Standalone code to reproduce the issue

```shell
pip install tensorflow
python
>>> import tensorflow as tf
 python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"                                                                                
2023-08-24 15:39:47.107770: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-08-24 15:39:47.108805: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.                                                                          
2023-08-24 15:39:47.130307: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.                                                                          
2023-08-24 15:39:47.130612: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.                       
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.                                                                            
2023-08-24 15:39:47.496076: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT                                                                                      
2023-08-24 15:39:48.008342: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355                                                                                
2023-08-24 15:39:48.023762: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would
like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.                                                              
Skipping registering GPU devices...
[]
```

**Comment by SuryanarayanaY** [comment]
@nnagarajan ,

For enabling GPU you need to follow additional instructions mentioned in documentation [here](https://www.tensorflow.org/install/pip#linux).

Please check and if you still have issue the let us know.Thanks!

**Comment by nnagarajan** [comment]
Thank you for the instructions @SuryanarayanaY , missed to install cudatookit. After installing the toolkit TF can now recognize the GPU but there are couple of warnings, 

1. TF using CPU optimization
```
This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
```
2. NUMA not available
```
successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
```

Looking for suggestions to resolve these warnings as well. 



```
python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
2023-08-28 12:46:34.327130: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-08-28 12:46:34.351325: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-28 12:46:34.723738: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-08-28 12:46:35.245761: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-08-28 12:46:35.260189: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-08-28 12:46:35.260380: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
```

**Comment by SuryanarayanaY** [comment]
Hi @nnagarajan ,

> ```
> This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
> ```

This is not warning. This is just information giving to user that the binaries are optimized for CPU to give better performance.

> ```
> successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> ```

This is just a warning not an error and should not affect TF. To get rid of this warning you can refer the attached [source](https://github.com/tensorflow/tensorflow/issues/42738#issuecomment-922422874).

Alternatively you can use the below command to suppress the warnings.

```
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
```

Thanks!

**Comment by Ricky24680** [comment]
`python3 -c  "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))" 
2023-12-21 17:13:28.613069: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-12-21 17:13:28.666215: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-21 17:13:29.376597: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-12-21 17:13:30.488571: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
[]`
I have a same error,but After installing the toolkit,it doesn't work

**Comment by Ricky24680** [comment]
![微信截图_20231221172531](https://github.com/tensorflow/tensorflow/assets/150895609/5253d621-f60c-4738-8346-b2a1953fd0bf)
I had a similar problem, but installing cudatoolkit = 11.8 in the environment didn't solve it.

**Comment by Ricky24680** [comment]
> ![微信截图_20231221172531](https://private-user-images.githubusercontent.com/150895609/292157753-5253d621-f60c-4738-8346-b2a1953fd0bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNTExNDcsIm5iZiI6MTcwMzE1MDg0NywicGF0aCI6Ii8xNTA4OTU2MDkvMjkyMTU3NzUzLTUyNTNkNjIxLWY2MGMtNDczOC04MzQ2LWIyYTE5NTNmZDBiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMVQwOTI3MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZWFiZjU5ZDBlYTM4NzI1MmZiNDA4ZTAyYmZkMjVlZmNlOGJjNDdiNGYwZjJkZjI0ZDU4NmZiNDBhZTJlMTRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5eEzAmy557YWhfochLlmWa-Gdr354J-B2fF9MgEJHk0) I had a similar problem, but installing cudatoolkit = 11.8 in the environment didn't solve it.

my env: python 3.10  cuda 12.2  cudatoolkit 11.8.0

**Comment by Zazbhai** [comment]
I Am Running On Cpu And getting The Following Issue:


2023-12-30 12:06:56.760763: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

with lots of other warnings 

i have tried env method but didn't work for me

**Comment by Quoc-Tuan** [comment]
> I Am Running On Cpu And getting The Following Issue:
> 
> 2023-12-30 12:06:56.760763: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
> 
> with lots of other warnings
> 
> i have tried env method but didn't work for me

To turn off this warning you can set the environment variable `export TF_ENABLE_ONEDNN_OPTS=0`.
> 2023-12-30 12:06:56.760763: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

**Comment by corporateGhost** [comment]
> > I Am Running On Cpu And getting The Following Issue:
> > 2023-12-30 12:06:56.760763: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
> > with lots of other warnings
> > i have tried env method but didn't work for me
> 
> To turn off this warning you can set the environment variable `export TF_ENABLE_ONEDNN_OPTS=0`.
> 
> > 2023-12-30 12:06:56.760763: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

Where can do this ?

**Comment by Peymanjabraelzade** [comment]
plz help
when i am import tensorflow mode cpu , his error :
 import tensorflow as tf
2024-07-14 15:34:19.207908: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-07-14 15:34:21.073824: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

**Comment by Tuong15** [comment]
(new_env) C:\Users\caoba\Desktop\TuongCar\filerun>python chay.py
2024-12-03 15:53:39.266350: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE SSE2 SSE3 SSE4.1 SSE4.2 AVX AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "chay.py", line 43, in <module>
    model = load_model('model.h5')
  File "C:\Users\caoba\anaconda3\envs\new_env\lib\site-packages\keras\src\saving\saving_api.py", line 238, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\caoba\anaconda3\envs\new_env\lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\caoba\anaconda3\envs\new_env\lib\site-packages\keras\src\engine\base_layer.py", line 870, in from_config
    raise TypeError(
TypeError: Error when deserializing class 'InputLayer' using config={'batch_shape': [None, 66, 200, 3], 'dtype': 'float32', 'sparse': False, 'name': 'input_layer'}.

Exception encountered: Unrecognized keyword arguments: ['batch_shape']
