### ISSUE TITLE
_pywrap_tensorflow_internal.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Aismart20170718** [tensorflow/tensorflow#61717]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf2.6.2

### Custom code

Yes

### OS platform and distribution

ubuntu20.04

### Mobile device

rk3588

### Python version

python3.8

### Current behavior?

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: /usr/local/lib/python3.8/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so: cannot open shared object file: No such file or directory

### Standalone code to reproduce the issue

```shell
import tensorflow
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: /usr/local/lib/python3.8/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so: cannot open shared object file: No such file or directory
```

**Comment by SuryanarayanaY** [comment]
HI @Aismart20170718 ,

Could you please confirm the build command used along with bazel and GCC versions? Also 2.6 version is quiet older and not actively supported. Could you please try the build with latest versions? Thanks!
