### ISSUE TITLE
[Compression]Compression issues of File isn't open for reading with r0.12

### ISSUE THREAD

**Issue by Viscoo** [tensorflow/tensorflow#6177]
I have met a problem with the model of  Compression again.

[https://github.com/tensorflow/models/tree/master/compression](url)
I use the OS of Ubuntu 14.04 LTS and the version of Tensorflow is r0.12

The error print as:
Traceback (most recent call last):
  File "encoder.py", line 103, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "encoder.py", line 99, in main
    np.savez_compressed(code_file, shape=int_codes.shape, codes=export)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 600, in savez_compressed
    _savez(file, args, kwds, True)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 642, in _savez
    zipf.write(tmpfile, arcname=fname)
  File "/usr/lib/python2.7/zipfile.py", line 1139, in write
    zinfo.header_offset = self.fp.tell()    # Start of header bytes
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 141, in tell
    "File isn't open for reading")
tensorflow.python.framework.errors_impl.PermissionDeniedError: File isn't open for reading
Exception tensorflow.python.framework.errors_impl.PermissionDeniedError: PermissionDeniedError() in <bound method ZipFile.__del__ of <zipfile.ZipFile object at 0x7f368ed35a50>> ignored

**Comment by Viscoo** [comment]
Find the solution at [https://github.com/tensorflow/models/issues/500](url)

**Comment by michaelisard** [comment]
Is that solution working? Can I close the issue?

**Comment by gunan** [comment]
Closing due to inactivity.
The link you have seems to be broken, and issue number 500 in models repo seems to be unrelated.
For posterity, could you repaste which issue/pr you think resolves the problem?
