### ISSUE TITLE
Cannot create interpreter when using GPU-Delegate or NNAPI-Delegate

### ISSUE THREAD

**Issue by JHarzenetter** [tensorflow/tensorflow#61792]
**System information**
- Android Device information: samsung/a14mnseea/a14m:13/TP1A.220624.014/A145RXXU2AWG3:user/release-keys
- TensorFlow Lite in Play Services SDK version (found in `build.gradle`):
  - com.google.android.gms:play-services-tflite-java:16.1.0
  - com.google.android.gms:play-services-tflite-support:16.1.0
  - com.google.android.gms:play-services-tflite-gpu:16.2.0
- Google Play Services version: 23.33.16

**Standalone code to reproduce the issue**

        var useGpu = Tasks.await(TfLiteGpu.isGpuDelegateAvailable(context));
        var optionsBuilder = TfLiteInitializationOptions.builder();

        optionsBuilder.setEnableGpuDelegateSupport(useGpu);

        Tasks.await(TfLite.initialize(context, optionsBuilder.build()));

        var options =  new InterpreterApi.Options();
        if(useGpu){
            options.addDelegateFactory(new GpuDelegateFactory());
        }

        /*delegate = new NnApiDelegate();
        options.addDelegate(delegate);
        options.setUseNNAPI(true);*/

        options.setRuntime(InterpreterApi.Options.TfLiteRuntime.FROM_SYSTEM_ONLY);

        //load Model from App assets
        interpreter = InterpreterApi.create(new File(modelPath), options);

**Any other info / logs**
I oriented my code on the official documentation [on here](https://www.tensorflow.org/lite/android/delegates/gpu)

Logcat-Output:
java.lang.IllegalArgumentException: Internal error: Cannot create interpreter: 
                                                                                                    	at com.google.android.gms.tflite.NativeInterpreterWrapper.createInterpreter(Native Method)
                                                                                                    	at com.google.android.gms.tflite.NativeInterpreterWrapper.zzl(com.google.android.gms:play-services-tflite-java@@16.1.0:34)
                                                                                                    	at com.google.android.gms.tflite.NativeInterpreterWrapper.<init>(com.google.android.gms:play-services-tflite-java@@16.1.0:6)
                                                                                                    	at com.google.android.gms.tflite.zzd.<init>(com.google.android.gms:play-services-tflite-java@@16.1.0:1)
                                                                                                    	at com.google.android.gms.tflite.InterpreterFactoryImpl.create(com.google.android.gms:play-services-tflite-java@@16.1.0:2)
                                                                                                    	at org.tensorflow.lite.InterpreterApi.create(InterpreterApi.java:336)
                                                                                                    	at com.example.tfliteaudio.TFLiteEngine.initialize(TFLiteEngine.java:83)
                                                                                                    	at com.example.tfliteaudio.MainActivity.lambda$transcribeAudio$5(MainActivity.java:143)
                                                                                                    	at com.example.tfliteaudio.MainActivity.$r8$lambda$1xqJ9hAvPXTc26gXgWfy8QcV0VE(Unknown Source:0)
                                                                                                    	at com.example.tfliteaudio.MainActivity$$ExternalSyntheticLambda2.run(Unknown Source:2)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)

**Comment by pjpratik** [comment]
Hi @JHarzenetter 

Could you please provide more information related to the issue?

What was the output when `TfLiteGpu.isGpuDelegateAvailable(context)` is printed?

You might not need the org.tensorflow:tensorflow-lite-task-vision-play-services dependency if you are using InterpreterApi.

Thanks.

**Comment by JHarzenetter** [comment]
Hi @pjpratik 

if you mean the result of ```TfLiteGpu.isGpuDelegateAvailable(context)```, it returns true.

I tried to improve the performance of the model with those delegates. I used the official TF-Website for this, but this isn't working for me. 
I tested everything again on a Pixel 6 and got the same result.

Hope this helps

**Comment by pjpratik** [comment]
Hi @JHarzenetter 

Thanks for the information. 

When you say performance, it is related to the delegate performance w.r.t to cpu or something else? Can you please provide more context regarding this?

Also, if you can provide the android studio project or a toy version that reproduces the issue will help us to investigate the cause better.

Thanks.

**Comment by JHarzenetter** [comment]
Hi @pjpratik 

We're trying to implement a Speechrecognition based on [this Repository](https://github.com/nyadla-sys/whisper.tflite/tree/main/android_example).
*Heads up if you try this Repo: it only works correctly with audio captured by the app itself.*

The Main Change, i have made so far, is the migration to the play-services Version of TF (as recommended). 

With performance i meant the time it takes to transcribe the passed audio. We tried to lower it with the given delegates and ran into this issue.

Thanks

**Comment by pjpratik** [comment]
Hi @JHarzenetter 

Thanks for the information. 

Can you confirm that you have followed this [migration document](https://www.tensorflow.org/lite/android/play_services#migrating) for migrating from stand-alone TensorFlow Lite to the Play services API?

Thanks.

**Comment by JHarzenetter** [comment]
Hi @pjpratik 

yes that's the document i followed for the migration

**Comment by pkgoogle** [comment]
Hi @JHarzenetter, can you fork that repo and make the minimal changes to reproduce your issue? We don't know how exactly you changed it and any little change can potentially be the culprit. Thanks for your help.
