### ISSUE TITLE
Error installing build from source

### ISSUE THREAD

**Issue by sparrow84001** [tensorflow/tensorflow#61822]
WSL2 - Ubantu-22.4
When configured I use 

"Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: N
Not configuring the WORKSPACE for Android builds."

But when I build I get this error 

"ERROR: Traceback (most recent call last):
        File "/home/n3/.cache/bazel/_bazel_n3/6f14c15d85335b4cb3c9403635dfd45f/external/build_bazel_rules_apple/apple/internal/transition_support.bzl", line 547, column 46, in <toplevel>
                _apple_platform_split_transition = transition(
Error in transition: Invalid transition input '//command_line_option:incompatible_enable_apple_toolchain_resolution'. Cannot transition on --experimental_* or --incompatible_* options
ERROR: /mnt/d/TensorflowC/tensorflow/WORKSPACE:88:14: error loading package '@com_github_grpc_grpc//src/compiler': at /home/n3/.cache/bazel/_bazel_n3/6f14c15d85335b4cb3c9403635dfd45f/external/com_github_grpc_grpc/bazel/grpc_build_system.bzl:28:6: at /home/n3/.cache/bazel/_bazel_n3/6f14c15d85335b4cb3c9403635dfd45f/external/build_bazel_rules_apple/apple/ios.bzl:33:5: at /home/n3/.cache/bazel/_bazel_n3/6f14c15d85335b4cb3c9403635dfd45f/external/build_bazel_rules_apple/apple/internal/ios_rules.bzl:95:5: initialization of module 'apple/internal/transition_support.bzl' failed and referenced by '//external:grpc_python_plugin'"

This is an iOS support error, right? 
I couldn't configure any iOS and Android WORKSPACE so why do I get this error?

**Comment by sushreebarsa** [comment]
@sparrow84001 Could you please elaborate on the steps you followed?
If you are using WSL2 for GPU access for a later version of 2.10 on windows, then please make sure that you have followed the steps mentioned [here](https://www.tensorflow.org/install/pip#windows-wsl2). Thank you!

**Comment by sparrow84001** [comment]
1) I tried Check this #60144 that uses **onednn (intel opt)**
2) That's why I use build from source. I want to use **cudnn (nvidia opt)** .
3) errors 

     **1st error**

            " ERROR: Traceback (most recent call last):
        File "/home/n3/.cache/bazel/_bazel_n3/6f14c15d85335b4cb3c9403635dfd45f/external/build_bazel_rules_apple/apple/internal/transition_support.bzl", line 547, column 46, in <toplevel>
                _apple_platform_split_transition = transition(Error in transition: Invalid transition input '//command_line_option:incompatible_enable_apple_toolchain_resolution'. Cannot transition on --experimental_* or --incompatible_* options" "

    **2nd error**

        " ERROR: /mnt/d/TensorflowC/tensorflow/WORKSPACE:88:14: error loading package '@com_github_grpc_grpc//src/compiler': at /home/n3/.cache/bazel/_bazel_n3/6f14c15d85335b4cb3c9403635dfd45f/external/com_github_grpc_grpc/bazel/grpc_build_system.bzl:28:6: at /home/n3/.cache/bazel/_bazel_n3/6f14c15d85335b4cb3c9403635dfd45f/external/build_bazel_rules_apple/apple/ios.bzl:33:5: at /home/n3/.cache/bazel/_bazel_n3/6f14c15d85335b4cb3c9403635dfd45f/external/build_bazel_rules_apple/apple/internal/ios_rules.bzl:95:5: initialization of module 'apple/internal/transition_support.bzl' failed and referenced by '//external:grpc_python_plugin' "


4) Check the attached video.

https://github.com/tensorflow/tensorflow/assets/37022413/b8bba37c-6335-494c-ab44-64e12f4dc94c

**Comment by tbe** [comment]
Same issue happens here, trying to build tensorflow inside a docker container. Seems not limited to WSL2

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
