### ISSUE TITLE
Problem installing tensorflow 2.13.0

### ISSUE THREAD

**Issue by ihh** [tensorflow/tensorflow#61922]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.13.0

### Custom code

No

### OS platform and distribution

Linux Ubuntu 22.04, Lambda Labs TensorBook

### Mobile device

n/a

### Python version

3.11.5

### CUDA/cuDNN version

8.6.0.163

### Current behavior?

TensorFlow 2.1.13 won't run because of an undefined symbol in libtensorflow_cc, apparently a google.protobuf.Message symbol.

### Standalone code to reproduce the issue

```shell
I am on a LambdaLabs TensorBook. This does come with a preloaded tensorflow installation in /usr/lib/python3/dist-packages
However my reading of the error messages on install does not seem to suggest that conflict with that package is to blame here.

Installing per instructions here: https://www.tensorflow.org/install/pip

~~~
conda create --name cuda11
conda activate cuda11
conda install python
conda install -c conda-forge cudatoolkit=11.8.0
python3 -m pip install nvidia-cudnn-cu11==8.6.0.163 tensorflow==2.13.
python3 -c "import tensorflow"
~~~

...yields the following error message...

~~~
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yam/miniconda3/envs/cuda11/lib/python3.11/site-packages/tensorflow/__init__.py", line 38, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/yam/miniconda3/envs/cuda11/lib/python3.11/site-packages/tensorflow/python/__init__.py", line 36, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/home/yam/miniconda3/envs/cuda11/lib/python3.11/site-packages/tensorflow/python/pywrap_tensorflow.py", line 26, in <module>
    self_check.preload_check()
  File "/home/yam/miniconda3/envs/cuda11/lib/python3.11/site-packages/tensorflow/python/platform/self_check.py", line 63, in preload_check
    from tensorflow.python.platform import _pywrap_cpu_feature_guard
ImportError: /home/yam/miniconda3/envs/cuda11/lib/python3.11/site-packages/tensorflow/python/platform/../../libtensorflow_cc.so.2: undefined symbol: _ZN6google8protobuf7Message19CopyWithSourceCheckERS1_RKS1_
~~~

pip package info:

~~~
(cuda11) yam@TensorYam:~$ python -m pip list
Package                      Version
---------------------------- ---------
absl-py                      2.0.0
astunparse                   1.6.3
cachetools                   5.3.1
certifi                      2023.7.22
charset-normalizer           3.2.0
flatbuffers                  23.5.26
gast                         0.4.0
google-auth                  2.23.0
google-auth-oauthlib         1.0.0
google-pasta                 0.2.0
grpcio                       1.58.0
h5py                         3.9.0
idna                         3.4
keras                        2.13.1
libclang                     16.0.6
Markdown                     3.4.4
MarkupSafe                   2.1.3
numpy                        1.24.3
nvidia-cublas-cu11           11.11.3.6
nvidia-cudnn-cu11            8.6.0.163
oauthlib                     3.2.2
opt-einsum                   3.3.0
packaging                    23.1
pip                          23.2.1
protobuf                     4.24.3
pyasn1                       0.5.0
pyasn1-modules               0.3.0
requests                     2.31.0
requests-oauthlib            1.3.1
rsa                          4.9
setuptools                   68.0.0
six                          1.16.0
tensorboard                  2.13.0
tensorboard-data-server      0.7.1
tensorflow                   2.13.0
tensorflow-estimator         2.13.0
tensorflow-io-gcs-filesystem 0.34.0
termcolor                    2.3.0
typing_extensions            4.5.0
urllib3                      1.26.16
Werkzeug                     2.3.7
wheel                        0.38.4
wrapt                        1.15.0
~~~
```

**Comment by SuryanarayanaY** [comment]
Hi @ihh,

This seems to be environment issue. We have observed that with protobuf 4.24.3 version there seems some problem as in other ticket #61551 user confirmed segmentation fault with this protobuf version. That issue is under review now.

Could you please try with any other protobuf version mentioned below.May be 4.23.4 or something and let us know the outcome.

    'protobuf>=3.20.3,<5.0.0dev,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5'

Thank you!

**Comment by ihh** [comment]
Thanks @SuryanarayanaY. Unfortunately this does not resolve the problem:

~~~
$ pip uninstall tensorflow protobuf
$ python3 -m pip install nvidia-cudnn-cu11==8.6.0.163 protobuf==4.23.4 tensorflow==2.13.*
...
Using cached protobuf-4.23.4-cp37-abi3-manylinux2014_x86_64.whl (304 kB)
Using cached tensorflow-2.13.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (524.2 MB)
Installing collected packages: protobuf, tensorflow
Successfully installed protobuf-4.23.4 tensorflow-2.13.0
$ python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yam/miniconda3/envs/jax-cuda11/lib/python3.11/site-packages/tensorflow/__init__.py", line 38, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/yam/miniconda3/envs/jax-cuda11/lib/python3.11/site-packages/tensorflow/python/__init__.py", line 36, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/home/yam/miniconda3/envs/jax-cuda11/lib/python3.11/site-packages/tensorflow/python/pywrap_tensorflow.py", line 26, in <module>
    self_check.preload_check()
  File "/home/yam/miniconda3/envs/jax-cuda11/lib/python3.11/site-packages/tensorflow/python/platform/self_check.py", line 63, in preload_check
    from tensorflow.python.platform import _pywrap_cpu_feature_guard
ImportError: /home/yam/miniconda3/envs/jax-cuda11/lib/python3.11/site-packages/tensorflow/python/platform/../../libtensorflow_cc.so.2: undefined symbol: _ZN6google8protobuf7Message19CopyWithSourceCheckERS1_RKS1_
~~~

**Comment by ihh** [comment]
> Hi @ihh ,
> 
> We are able to install tensorflow==2.13 successfully on Ubuntu22. Just to cross check,could you please uninstall tensorflow and try with fresh environment and also with latest version i.e. 2.14 as well and let us know the outcome.

Apologies for the slow reply. A fresh install worked, thank you. I think there was some cross-contamination between different package versions.
