### ISSUE TITLE
KeyError: 'min'

### ISSUE THREAD

**Issue by pzy2000** [tensorflow/tensorflow#61963]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf 2.13

### Custom code

Yes

### OS platform and distribution

5.15.90.1-microsoft-standard-WSL2

### CUDA/cuDNN version

12.2

### Current behavior?

Traceback (most recent call last):
  File "o2k.py", line 11, in <module>
    k_model = onnx_to_keras(onnx_model, ['input.1'], name_policy='renumerate', verbose=True)
  File "/root/miniconda3/envs/onnx/lib/python3.8/site-packages/onnx2keras/converter.py", line 175, in onnx_to_keras
    AVAILABLE_CONVERTERS[node_type](
  File "/root/miniconda3/envs/onnx/lib/python3.8/site-packages/onnx2keras/operation_layers.py", line 31, in convert_clip
    if params['min'] == 0:
KeyError: 'min'

### Standalone code to reproduce the issue

```shell
from onnx2keras import onnx_to_keras
import keras
import onnx
import sys
# sys.path.append("/root/MR")
onnx_model = onnx.load('ssd_bmv1_torch.onnx')
onnx_inputs = onnx_model.graph.input
print("===========================")
print(onnx_inputs)
# onnx_model = onnx.load('vgg11.onnx')
k_model = onnx_to_keras(onnx_model, ['input.1'], name_policy='renumerate', verbose=True)
keras.models.save_model(k_model, 'ssd_bmv1_torch.h5', overwrite=True, save_format="h5")

onnx file can be downloaded at https://pan.xunlei.com/s/VNf1O2DqsdqdbTYYpyemSqveA1?pwd=by77#
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "o2k.py", line 11, in <module>
    k_model = onnx_to_keras(onnx_model, ['input.1'], name_policy='renumerate', verbose=True)
  File "/root/miniconda3/envs/onnx/lib/python3.8/site-packages/onnx2keras/converter.py", line 175, in onnx_to_keras
    AVAILABLE_CONVERTERS[node_type](
  File "/root/miniconda3/envs/onnx/lib/python3.8/site-packages/onnx2keras/operation_layers.py", line 31, in convert_clip
    if params['min'] == 0:
KeyError: 'min'
```

**Comment by mihaimaruseac** [comment]
This at most belongs to keras, not TF
