### ISSUE TITLE
ModuleNotFoundError: No module named 'resource'

### ISSUE THREAD

**Issue by jsmith173** [tensorflow/tensorflow#61980]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

v2.13.0-rc2-7-g1cb1a030a62 2.13.0

### Custom code

No

### OS platform and distribution

Windows 11

### Python version

3.11.5

### Current behavior?

Python test code
`import tensorflow_datasets as tfds`

Produces
ModuleNotFoundError: No module named 'resource'

### Standalone code to reproduce the issue

```shell
Python test code
import tensorflow_datasets as tfds
```

### Relevant log output

```shell
c:\xxxx\Devel Files\Other\Work\Python\image_class_transferlearning>python64.bat test.py
Traceback (most recent call last):
  File "c:\xxxx\Devel Files\Other\Work\Python\image_class_transferlearning\test.py", line 1, in <module>
    import tensorflow_datasets as tfds
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow_datasets\__init__.py", line 43, in <module>
    import tensorflow_datasets.core.logging as _tfds_logging
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow_datasets\core\__init__.py", line 22, in <module>
    from tensorflow_datasets.core import community
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow_datasets\core\community\__init__.py", line 18, in <module>
    from tensorflow_datasets.core.community.huggingface_wrapper import mock_builtin_to_use_gfile
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow_datasets\core\community\huggingface_wrapper.py", line 31, in <module>
    from tensorflow_datasets.core import dataset_builder
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow_datasets\core\dataset_builder.py", line 44, in <module>
    from tensorflow_datasets.core import split_builder as split_builder_lib
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow_datasets\core\split_builder.py", line 37, in <module>
    from tensorflow_datasets.core import writer as writer_lib
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow_datasets\core\writer.py", line 33, in <module>
    from tensorflow_datasets.core import shuffle
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow_datasets\core\shuffle.py", line 20, in <module>
    import resource
ModuleNotFoundError: No module named 'resource'
```

**Comment by tilakrayal** [comment]
@jsmith173,
Have you got the chance to have a look at this commit where the PR  was raised for the similar issue in the [tensorflow/datasets](https://github.com/tensorflow/datasets/issues) repo and it was merged.
https://github.com/tensorflow/datasets/commit/82215c7cf4b3e6df706a72c9b7ad8cede09f4d84

```
def _increase_open_files_limit():
  """Attempts to increase the maximum number of open file descriptors."""
  """Attempts to increase the maximum number of open file descriptors on UNIX."""
  try:
    import resource  # pylint: disable=g-import-not-at-top
  except ModuleNotFoundError:
    logging.error(
        "Missing `resource` module, can't automatically increase the maximum"
        ' number of open file descriptors on your system. Try increasing it'
        ' manually.'
    )
    return
```


Also the developer also confirmed the issue has been resolved for the Windows machine. 
https://github.com/tensorflow/datasets/issues/5075#issuecomment-1727676597

Thank you!

**Comment by jsmith173** [comment]
Sorry I can't test it this way.
I've found an older version on my computer that works.
Thanks for your help!

**Comment by tilakrayal** [comment]
@jsmith173,
Glad the issue was resolved. Could you please feel free to move this issue to closed status. Thank you!

**Comment by funnymdpee** [comment]
Hello, I been troubled with this problem too. You said you found an older version on your computer, could you please tell me which one's version did you changed.

**Comment by jsmith173** [comment]
Working package version: 4.9.2 (tensorflow_datasets)

**Comment by funnymdpee** [comment]
> Working package version: 4.9.2 (tensorflow_datasets)

Thank you!

**Comment by colaquafina** [comment]
Thanks, I also solve this problem by installing version 4.9.2
