### ISSUE TITLE
Support Python 3.12

### ISSUE THREAD

**Issue by MartinNowak** [tensorflow/tensorflow#62003]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf 2.15.0.dev

### Custom code

No

### OS platform and distribution

Linux Fedora 39

### Python version

3.12

### Current behavior?

No Python3.12 compatbility and wheels.

This issue can be used as a tracking issue. This includes:

 - [ ] TensorFlow builds fully on Python 3.12
 - [ ] All TensorFlow tests pass on Python 3.12
 - [ ] All CI is run and green on Python 3.12
 - [ ] Wheels are uploaded to PyPI for [tf-nightly](https://pypi.org/project/tf-nightly/#files)
   - [ ] Linux
   - [ ] macOS
   - [ ] Windows
 - [ ] Wheels are uploaded to PyPI for at least one TensorFlow release

### Standalone code to reproduce the issue

```shell
python3.12 -m venv venv
source venv/bin/activate
pip install -U pip setuptools wheel
pip install tf-nightly --pre
```

### Relevant log output

```shell
ERROR: Could not find a version that satisfies the requirement tf-nightly (from versions: none)
ERROR: No matching distribution found for tf-nightly

Prior editiions:
- [2011/3.11](https://github.com/tensorflow/tensorflow/issues/58032#issuecomment-1279963648)
- [2010/3.10](https://github.com/tensorflow/tensorflow/issues/51776#issuecomment-934569048)
- [2009/3.9](https://github.com/tensorflow/tensorflow/issues/44485)
- [2008/3.8](https://github.com/tensorflow/tensorflow/issues/33374)

TF 2.14 has just shipped, meaning we'll likely have to wait for TF 2.15/2.16 again.
```

**Comment by OH-AU** [comment]
More an FYI: Was able to compile/build a wheel "successfully" using the latest pull from master by forcing --repo_env=TF_PYTHON_VERSION=3.11 - Unfortunately, although the wheel was successfully created under python/3.12.0, it (perhaps understandably) refused to install with the message:
ERROR: tensorflow-2.15.0-cp311-cp311-linux_x86_64.whl is not a supported wheel on this platform. Extracting the wheel also results in a similar error: "module was compiled for Python 3.11"
Is it possible to force an attempt for a cp312 compatible build?

**Comment by plopresti** [comment]
It's easy enough to edit tensorflow/tools/toolchains/python/python_repo.bzl to add "3.12" to VERSIONS, which will let you set TF_PYTHON_VERSION=3.12.

But then you will encounter this build failure:

> ERROR: Traceback (most recent call last):
> 	File ".../tensorflow/WORKSPACE", line 32, column 27, in <toplevel>
> 		python_register_toolchains(
> 	File ".../.cache/bazel/.../40192ecc60b78c448056886e209e7d2b/external/rules_python/python/repositories.bzl", line 532, column 31, in python_register_toolchains
> 		sha256 = tool_versions[python_version]["sha256"].get(platform, None)
> Error: key "3.12" not found in dictionary

I am pretty sure this cannot be made to work until [rules_python](https://github.com/bazelbuild/rules_python) gets support for 3.12, and I do not even see an open issue for that yet.

**Comment by mihaimaruseac** [comment]
The TF build process is quite long, taking several weeks. Since Python 3.12 was not released at the time of TF branch cut it couldn't be supported by the newly released TF.

The team is working to reduce the time window between a Python version and the time TF supports it, but support cannot be added after the branch was cuit.

**Comment by plopresti** [comment]
Python's development process includes a pretty lengthy beta + release candidate cycle. Python 3.12 candidate 1 was released on 8/6, for example.

If someone submitted a pull request to add support for a Python beta or release candidate, would it be accepted? For future reference.

**Comment by mihaimaruseac** [comment]
If CI can support testing with new versions of Python, then I think that should be possible. However, note that TF has a large number of dependencies and those will need to work before TF can support the new version of Python.

We've had issues in the past where some dependency did not release a wheel for new version of Python for nearly half a year.

**Comment by cclauss** [comment]
> TF has a large number of dependencies and those will need to work before TF can support the new version of Python.

Can we have a checklist of those deps that are not yet shipping Py3.12 versions?

**Comment by mihaimaruseac** [comment]
cc @MichaelHudgins for 

> > TF has a large number of dependencies and those will need to work before TF can support the new version of Python.
> 
> Can we please have a checklist of those deps that are not yet shipping Py3.12 versions?
> 
> * [x]  [rules_python v0.26.0](https://github.com/bazelbuild/rules_python/releases) has some level of Py3.12 support

**Comment by mihaimaruseac** [comment]
That being said, have a look at #62155

**Comment by MichaelHudgins** [comment]
On at least the Linux side our upstream dependencies are present and we have local 3.12 builds successful with some test errors that will still need addressed.  We are in the process of adding 3.12 to the CI system and hope to have nightlies soon.

**Comment by dishb** [comment]
Has there been any progress on this issue?

I tried installing TF with these commands:

```bash
python3 -m venv .venv  # create a virtual environment named .venv
source ./.venv/bin/activate  # activate the venv
pip3 install tensorflow  # install
```

I am running Python 3.12.0 on an M2 Macbook Air (not sure if this helps with the architecture my computer is running) with macOS 14.1.1

**Comment by mihaimaruseac** [comment]
`tf-nightly` would be the first one to get support.

https://pypi.org/project/tf-nightly/#files already shows some `cp312` files, so this should work already

**Comment by dishb** [comment]
@mihaimaruseac  - Seems like the file is for Linux, but thank you for pointing this out! Will wait for the macOS version :)

**Comment by mihaimaruseac** [comment]
MacOS is no longer released officially by the Google team, it's a partner project so it takes longer due to synchronization needs, etc.

**Comment by rafa-br34** [comment]
How about the windows version?

**Comment by mihaimaruseac** [comment]
That is also built by partners. Google only builds the Linux wheels now

**Comment by cclauss** [comment]
Who are the "partners"?  Do they have GitHub repos that MacOS and Windows users can contribute to?

**Comment by dishb** [comment]
Try checking the @Google organization?

**Comment by cclauss** [comment]
;-) 2.6k repos.

**Comment by dishb** [comment]
> ;-) 2.6k repos.

Can't you commit directly to this repo?

**Comment by mihaimaruseac** [comment]
> Who are the "partners"? Do they have GitHub repos that MacOS and Windows users can contribute to?

https://blog.tensorflow.org/2022/09/announcing-tensorflow-official-build-collaborators.html

They contribute directly here, in this repository, but they need to release separate wheels that TF then installs. For example https://pypi.org/project/tensorflow-intel/ for windows

**Comment by rafa-br34** [comment]
Is there any known ETA for Python 3.12 compatibility?

**Comment by soumyo40** [comment]
Any updates?

**Comment by mihaimaruseac** [comment]
Same status as [3 weeks ago](https://github.com/tensorflow/tensorflow/issues/62003#issuecomment-1837679866). There has been no release of TensorFlow stable, only nightly releases

**Comment by johnthagen** [comment]
Could we also add to the checklist:

- [ ] Python 3.12 wheels for [`tflite-runtime-nightly`](https://pypi.org/project/tflite-runtime-nightly)?

**Comment by MaverickAlonso** [comment]
hi, any new status?

**Comment by mihaimaruseac** [comment]
> Same status as [3 weeks ago](https://github.com/tensorflow/tensorflow/issues/62003#issuecomment-1837679866). There has been no release of TensorFlow stable, only nightly releases

This is still true

**Comment by cbouss** [comment]
It's here: https://github.com/tensorflow/tensorflow/releases/tag/v2.16.1

**Comment by mihaimaruseac** [comment]
Awesome. Then this can be closed now, right?

Thank you for the patience

**Comment by johnthagen** [comment]
`tflite-runtime-nightly` still does not have 3.12 wheels

- https://pypi.org/project/tflite-runtime-nightly/2.17.0.dev20240306/#files

**Comment by blthayer** [comment]
@johnthagen @terryheo @mihaimaruseac - as far as I can tell, there are still no Python 3.12 wheels for `tflite-runtime`. It would be very useful if `tensorflow`/Google would publish Python 3.12 wheels for `tflite-runtime` to PyPI. Thank you!

**Comment by cclauss** [comment]
Yes but… Python 3.13 beta was released yesterday which is traditionally soon the sign that the current release will be supported by TF.

**Comment by johnthagen** [comment]
> Yes but… Python 3.13 beta was released yesterday 

I may be missing what you mean by this, but we're specifically referring to 3.**12** (released Oct 2023) support that is missing for `tflite-runtime` rather than anything related to 3.**13**.

**Comment by cclauss** [comment]
I meant that if you look back in time… when Python.next goes beta it is usually a sign that TF will soon support Python.current.

**Comment by blthayer** [comment]
Bump - would be very useful to have `tflite-runtime` wheels for Python 3.12 (and it's surprising we don't seeing as `tflite-runtime` is a subset of `tensorflow` and `tensorflow` has 3.12 wheels...)

**Comment by aallan** [comment]
Another nudge for a `tflite-runtime` wheel for Python 3.12.

**Comment by johnthagen** [comment]
@gbaned [You helped with the Python 3.11 `tflite-runtime` PR process](https://github.com/tensorflow/tensorflow/pull/60182#issuecomment-1559506572). Would you be able to assist with 3.12 `tflite-runtime` support?

**Comment by bperseghetti** [comment]
@johnthagen  I think I get why maybe there has not been as much momentum to get tflite_runtime working, there were a lot of minor oddities to get it to properly cross-compile and build.

Here's the branch with minor changes to allow people  to build wheels properly again:
https://github.com/rudislabs/tensorflow/tree/pr-python312-tflite_runtime

Just run:
```bash
git clone -b pr-python312-tflite_runtime https://github.com/rudislabs/tensorflow
cd tensorflow/tensorflow/lite/tools/pip_package/
make docker-build
``` 

## Here is a zip of the wheel for aarch64 (what I needed it for):
[tflite_runtime-2.19.0-cp312-cp312-linux_aarch64.zip](https://github.com/user-attachments/files/17198956/tflite_runtime-2.19.0-cp312-cp312-linux_aarch64.zip)

But you can just as easily choose to build it for native or armhf.

## Few things to note about the needed changes:

- [Python 3.12 dropped support for `distutils`, you can only find it in `python3-setuptools`](https://github.com/rudislabs/tensorflow/blob/75ce24d1155a8aceb34a6ed41a097b32872dc7b2/tensorflow/lite/tools/pip_package/Dockerfile.py3#L70)
- [Ubuntu 24.04 make it somewhat painful to cross-compile, you have to explicitly set `Architectures:` for ports.ubuntu.com that is not included by default in `/etc/apt/sources.list.d/ubuntu.sources` ](https://github.com/rudislabs/tensorflow/blob/75ce24d1155a8aceb34a6ed41a097b32872dc7b2/tensorflow/lite/tools/pip_package/Dockerfile.py3#L40-L59)
- [Docker base `ubuntu:24.04` image comes with a default user `ubuntu` that has a matching GID/UID as system default of 1000 which causes issues in current script](https://github.com/rudislabs/tensorflow/blob/75ce24d1155a8aceb34a6ed41a097b32872dc7b2/tensorflow/lite/tools/pip_package/Dockerfile.py3#L17)
- [pip throws errors/warnings when trying to install packages in 24.04 unless you override it with `--break-system-packages` (doesn't break anything since it's all in a container)](https://github.com/rudislabs/tensorflow/blob/75ce24d1155a8aceb34a6ed41a097b32872dc7b2/tensorflow/lite/tools/pip_package/Dockerfile.py3#L76)

@samypr100 feel free to open up a PR with any of this (but if you want to add me as a `Co-authored-by:` I wouldn't mind 😉). [I think it's somewhat similar to what I did for 3.10 but just a few extra steps](https://github.com/tensorflow/tensorflow/issues/56137#issuecomment-1367563496), looks like [most of that thankfully got in one way or another](https://github.com/tensorflow/tensorflow/pull/59423).

**Comment by cclauss** [comment]
Python 3.13 will be released on Monday.

**Comment by bperseghetti** [comment]
> Python 3.13 will be released on Monday. https://peps.python.org/pep-0719

Glad I could beat the trend?

**Comment by johnthagen** [comment]
@terryheo Does @bperseghetti's branch help the tflite team add 3.12 support?

- https://github.com/tensorflow/tensorflow/issues/62003#issuecomment-2384741963

**Comment by mihaimaruseac** [comment]
> Python 3.13 will be released on Monday. https://peps.python.org/pep-0719

Unfortunately, TF already cut the branch for the next release, so Python 3.13 support will come next year. I suggest opening a new issue to track 3.13 support, to keep this on TFLite (ARLite now?) supporting 3.12.

**Comment by johnthagen** [comment]
> I suggest opening a new issue to track 3.13 support ... to keep this on TFLite

Agreed, though I think @cclauss was more saying that 3.13 is releasing imminently, but since tflite-runtime doesn't support 3.12 yet, it will soon be _two_ versions behind.

> TFLite (ARLite now?)

I think you mean LiteRT (short for Lite Runtime)?

- https://ai.google.dev/edge/litert

**Comment by mihaimaruseac** [comment]
> I think you mean LiteRT (short for Lite Runtime)?

Yeah. Too early for me to remember names correctly. Thank you.

And yes, I agree, LiteRT will be too versions behind now, but probably now that it gets separated from TF we could open an issue against the new repo for it.

**Comment by johnthagen** [comment]
> Probably now that it gets separated from TF

At least as of today, it's still in this repo and being updated by the TF team:

- https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite

**Comment by mihaimaruseac** [comment]
https://github.com/google-ai-edge/litert

Just like XLA, the repo is not fully excised from TF. There is a separate repo for just LiteRT and the same code gets merged in the TF monorepo too.

However, it looks like the other repo doesn't yet allow code submissions, but issues could possibly be opened?

**Comment by mihaimaruseac** [comment]
Yes, TFLite is separating from TensorFlow and will have separate release cycles, separate teams working on it (already the case), separate repositories.

LiteRT issues should be brought up in those repos in the future (https://github.com/google-ai-edge/litert)

Since TF cannot do anything anymore for TFLite, is there anything else left here or we can close this?

**Comment by bperseghetti** [comment]
> Yes, TFLite is separating from TensorFlow and will have separate release cycles, separate teams working on it (already the case), separate repositories.
> 
> LiteRT issues should be brought up in those repos in the future (https://github.com/google-ai-edge/litert)
> 
> Since TF cannot do anything anymore for TFLite, is there anything else left here or we can close this?

I think this should be left open till LiteRT is more than just a repo containing a somewhat stale submodule of TF and is an actual contributable project, assumably when that happens there would also be an [announcement and the README and repos would be updated (or so the current REAME seems to claim)](https://github.com/google-ai-edge/LiteRT/blob/ca9dfe7050c8de742a3089ae90c0094fe996ffee/README.md?plain=1#L10-L14).

In it's current form the only way to contribute to LiteRT anyhow is to contribute to TF.  The TF submodule in LiteRT is pretty old (right now) relative to the overall development speed of the project [2 months ago/2,521 commits](https://github.com/google-ai-edge/LiteRT/tree/cfc768386cec8fe14751be3c2f483029243160d4/third_party). It doesn't even have the [latest updates in it to TFLite for the LiteRT renames](https://github.com/tensorflow/tensorflow/commits/master/tensorflow/lite?since=2024-08-28&until=2024-10-28).

**Comment by johnthagen** [comment]
On the latest `ai-edge-litert-nightly` both x86 and ARM64 wheels appear for Linux 😱 🚀

- https://pypi.org/project/ai-edge-litert-nightly/1.0.1.dev20250112/#files

So I think after the next stable release of `ai-edge-litert` comes out, this issue can finally be closed.

**Comment by johnthagen** [comment]
As of `ai-edge-litert` 1.1.0, Python 3.12 wheels are published for all the platforms that `tflite-runtime` once supported

- https://pypi.org/project/ai-edge-litert/1.1.0/#files

I think this issue can be closed 🚀 .

**Comment by aallan** [comment]
> I think this issue can be closed 🚀 .

More or less in time to open the "Support Python 3.13" issue.

**Comment by mihaimaruseac** [comment]
That already exists, #78774 

Closing this one as resolved.
