### ISSUE TITLE
Inconsistent API for ones_initializer/zeros_initializer

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#6202]
This [cl](https://github.com/tensorflow/tensorflow/commit/cfb2280d3f6ced298681bd1141479a59a06abde8) has removed `shape` argument from `ones_initializer`, however, this argument remains for `zeros_initializer`.

This is a breaking change so maybe it should be mentioned in RELEASE.md with instructions on how code should transition (ie `ones_initializer` should be replaced with `ones_initializer()`). Currently older code that works in 0.11 fails in 0.12 with obscure message

ie

```
    update = tf.get_variable(name="update", shape=[params_size], dtype=dtype,
                             initializer=tf.ones_initializer)

```

fails with
```
...
    initial_value(), name="initial_value", dtype=dtype)
  File "/home/yaroslav/.conda/envs/openai/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 665, in <lambda>
    shape.as_list(), dtype=dtype, partition_info=partition_info)
TypeError: ones_initializer() got multiple values for argument 'dtype'

```

@itsmeolivia

**Comment by yaroslavvb** [comment]
BTW, this seems to be fixed in https://github.com/tensorflow/tensorflow/pull/6339 (ie, syntax is consistent, both of them need to be tf.ones_initializer() and tf.zeros_initializer() ) , except maybe RELEASE.md could mention that people should add "()" to their tf.ones_initializer

**Comment by tvkpz** [comment]
I get
  
TypeError: zeros_initializer() got multiple values for keyword argument 'dtype'
for the inception model command:

bazel-bin/tensorflow_serving/example/inception_export --checkpoint_dir=inception-v3 --export_dir=inception-export

NOTE: I am able to successfully run the MNIST example for tensorflow serving but not the inception one.
I have tried all the recommendations mentioned previously.

The trace is as follows:

Traceback (most recent call last):
  File "/root/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/tf_serving/tensorflow_serving/example/inception_export.py", line 169, in <module>
    tf.app.run()
  File "/root/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/root/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/tf_serving/tensorflow_serving/example/inception_export.py", line 165, in main
    export()
  File "/root/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/tf_serving/tensorflow_serving/example/inception_export.py", line 79, in export
    logits, _ = inception_model.inference(images, NUM_CLASSES + 1)
  File "/root/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/inception_model/inception/inception_model.py", line 87, in inference
    scope=scope)
  File "/root/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/inception_model/inception/slim/inception_model.py", line 87, in inception_v3
    scope='conv0')
  File "/root/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/inception_model/inception/slim/scopes.py", line 155, in func_with_args
    return func(*args, **current_args)
  File "/root/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/inception_model/inception/slim/ops.py", line 234, in conv2d
    outputs = batch_norm(conv, **batch_norm_params)
  File "/root/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/inception_model/inception/slim/scopes.py", line 155, in func_with_args
    return func(*args, **current_args)
  File "/root/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/inception_model/inception/slim/ops.py", line 90, in batch_norm
    restore=restore)
  File "/root/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/inception_model/inception/slim/scopes.py", line 155, in func_with_args
    return func(*args, **current_args)
  File "/root/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/inception_model/inception/slim/variables.py", line 289, in variable
    trainable=trainable, collections=collections)
  File "/root/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/org_tensorflow/tensorflow/python/ops/variable_scope.py", line 1063, in get_variable
    custom_getter=custom_getter)
  File "/root/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/org_tensorflow/tensorflow/python/ops/variable_scope.py", line 889, in get_variable
    custom_getter=custom_getter)
  File "/root/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/org_tensorflow/tensorflow/python/ops/variable_scope.py", line 347, in get_variable
    validate_shape=validate_shape)
  File "/root/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/org_tensorflow/tensorflow/python/ops/variable_scope.py", line 332, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/root/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/org_tensorflow/tensorflow/python/ops/variable_scope.py", line 683, in _get_single_variable
    validate_shape=validate_shape)
  File "/root/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/org_tensorflow/tensorflow/python/ops/variables.py", line 225, in __init__
    expected_shape=expected_shape)
  File "/root/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/org_tensorflow/tensorflow/python/ops/variables.py", line 322, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)
  File "/root/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/org_tensorflow/tensorflow/python/ops/variable_scope.py", line 672, in <lambda>
    shape.as_list(), dtype=dtype, partition_info=partition_info)
TypeError: zeros_initializer() got multiple values for keyword argument 'dtype'

**Comment by tlbtlbtlb** [comment]
@tvkpz The semantics of tf.zeros_initializer went through multiple changes between recent tensorflow versions. The latest git master of universe-starter-agent uses `tf.constant_initializer(0.0)`, which has been stable. So checking out should fix it.

**Comment by tvkpz** [comment]
This is a reference is to a different project that includes tensorflow. Confused about what changes I need to make in the tensorflow-serving branch to get rid of this issue.

Appreciate if you can spell out the exact changes I need to make.

**Comment by tlbtlbtlb** [comment]
`tf.zeros_initializer` had multiple incompatible API changes between 0.11, 0.12, and -master.
If you need compatibility across versions, use `tf.constant_initializer(0.0)` instead.

**Comment by alexminnaar** [comment]
I am also running into this problem when following the TensorFlow serving tutorial here https://tensorflow.github.io/serving/serving_inception.html

**Comment by neuralearner** [comment]
Still experience the same issue here. Just did a fresh clone of tf_serving to export weights which has the latest tensorflow as well

**Comment by yaroslavvb** [comment]
@neuralearner The issue I described is due to API change affecting user code and can be fixed by changing tf.ones_initializer to tf.ones_initializer() in your program

**Comment by tvkpz** [comment]
I see that the .pyc files have the zero_initializer. Has anyone tried replacing the zero_initializer function with constant_initializer and regenerated the pyc files. In that case please outline the steps you followed.

**Comment by alexminnaar** [comment]
@neuralearner I got it working by changing tf.ones_initializer to tf.ones_initializer() and tf.zeros_initializer to tf.zeros_initializer() in `/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/inception_model/inception/slim/ops.py`.  [This issue](https://github.com/tensorflow/serving/issues/250) helped me solve the problem.

**Comment by tvkpz** [comment]
Thanks @alexminnaar ! This solution worked for me. There were a few more hacks required.

For those trying please also note that you need to change all tf.histogram_summary and tf.scalar_summary to tf.summary.histogram and tf.summary.scalar, to successfully load and export the model as indicated in the post pointed by @alexminnaar above

**Comment by vrv** [comment]
@aselle wrote a tool to try to upgrade code (at least at 0.11?) to 1.0 APIs.  See https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/compatibility and send PRs / file bugs for better functionality :)
