### ISSUE TITLE
Shape inference for tf.gather is inconsistent with/without --tf_mlir_enable_mlir_bridge

### ISSUE THREAD

**Issue by tqxia** [tensorflow/tensorflow#62088]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.14

### Custom code

Yes

### Python version

3.11

### Current behavior?

Please refer to the "Relevant log output" section for detailed description of current behavior.

### Standalone code to reproduce the issue

```shell
# Run the code snippet with the following flags to reproduce the issue:
# TF_XLA_FLAGS="--tf_mlir_enable_mlir_bridge --tf_xla_enable_xla_devices --tf_xla_auto_jit=2 --tf_xla_cpu_global_jit --tf_xla_min_cluster_size=1"

import tensorflow as tf

params = tf.constant([
    [0, 0, 1, 0, 2],
    [3, 0, 0, 0, 4],
    [0, 5, 0, 6, 0]])
indices = tf.constant([
    [2, 4],
    [0, 4]])

print(tf.gather(params, indices, axis=1, batch_dims=1))
```

### Relevant log output

```shell
When mlir bridge is disabled, the code snippet works without any error. The return value of tf.gather is [[1 2][3 4]]


when mlir bridge is enabled, the code snippet returned with error:

2023-10-11 11:43:24.846292: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at xla_ops.cc:841 : INVALID_ARGUMENT: Shape used to set computation result layout (s32[3,2]{1,0}) is not compatible with result shape (s32[2,2])
Traceback (most recent call last):
  File "/tf/playground/test_gather.py", line 37, in <module>
    print(tf.gather(params, indices, validate_indices=True, axis=1, batch_dims=1).numpy())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.11/dist-packages/tensorflow/python/framework/ops.py", line 5888, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__GatherV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Shape used to set computation result layout (s32[3,2]{1,0}) is not compatible with result shape (s32[2,2])
         [[{{node cluster_1_1/xla_compile}}]] [Op:GatherV2] name:
```

**Comment by tqxia** [comment]
Personally I digged into this issue a little bit.

When mlir bridge is enabled, ops roughly go through the following transformations:

graph -> tf dialect -> mhlo dialect -> xla hlo dialect -> some backend stuff...

Taking gather as an example, after transforming to tf.GatherV2, TensorFlowShapeInferencePass will be run at some stage to do shape inference. This pass eventually invokes GatherV2's OpShapeInferenceFn to do the actual work, which deduces the output shape based on the formula:

def batched_result_shape(p_shape, i_shape, axis=0, batch_dims=0):
  return p_shape[:axis] + i_shape[batch_dims:] + p_shape[axis+1:]

(https://www.tensorflow.org/versions/r2.14/api_docs/python/tf/gather)

But looks like the doc does not tell us what to do when the batch_dim dimensions of params and indices disagree.

Should the formula be updated to something like:

def batched_result_shape(p_shape, i_shape, axis=0, batch_dims=0):
  return i_shape[:batch_dims] + p_shape[batch_dims:axis] + i_shape[batch_dims:] + p_shape[axis+1:] 

or, should we just add a validation check to count the mismatch of batch_dim dimensions of params and indices?
