### ISSUE TITLE
tf.strings.to_number cannot convert positive integers prefixed with "+" when out_type is tf.int32 or tf.int64

### ISSUE THREAD

**Issue by sapphire008** [tensorflow/tensorflow#62191]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tf 2.11.0, 2.13.0, 2.14.0

### Custom code

Yes

### OS platform and distribution

MacOS 13.1

### Mobile device

Macbook Pro

### Python version

3.10.6

### Current behavior?

Converting string to numbers with "+"  throws errors in TF 2.11.0, 2.13.0, 2.14.0 when `out_type=tf.int64` or `out_type=tf.in32`. Not expecting error to be thrown and strings can be correctly converted into integers. For example, I would like to parse timezone information from a string (using substring)

```python 
t = tf.constant([
    "2023-05-07 17:32:25-08:00", # utc: next day
    "2023-05-07 05:32:25+11:00", # utc: previous day
    "2023-05-07 05:32:25-08:00", # utc: same date
    "2023-02-29 23:32:15-04:00", # leap year
    ]
)

```

### Standalone code to reproduce the issue

```shell
Code to reproduce


import tensorflow

# these are all okay
tf.string.to_number(tf.constant("-11"), out_type=tf.int64)
tf.string.to_number(tf.constant("11"), out_type=tf.int64)
tf.string.to_number(tf.constant("+11"), out_type=tf.float32)

# this throws the error below
tf.strings.to_number(tf.constant("+11"), out_type=tf.int64)
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/edward/opt/miniforge3/envs/testtf214/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/edward/opt/miniforge3/envs/testtf214/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 5888, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__StringToNumber_device_/job:localhost/replica:0/task:0/device:CPU:0}} StringToNumberOp could not correctly convert string: +11 [Op:StringToNumber] name:
```

**Comment by SuryanarayanaY** [comment]
Hi @sapphire008 ,

I have replicated the reported behaviour in tf-nightly and attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/1353285f9ddac2e974e5de832752b68b/62191.ipynb) here for reference.

We will look into it and update you. Thanks!

**Comment by fsx950223** [comment]
I have fixed the issue on local environment, but I can't open a PR on tsl repo since "An owner of this repository has limited the ability to open a pull request to users that are collaborators on this repository".

**Comment by Venkat6871** [comment]
Hi @sapphire008 ,
Apologies for the delay, and thank you for your patience. I tried running your code on Colab using the latest TensorFlow version (2.19.0), and I did not encounter any issues, it appears to be resolved in the latest version.
I am attaching a [gist](https://colab.sandbox.google.com/gist/Venkat6871/a2d71c2ea1b45374a1788c2ac0909656/62191_tf_2-19-0-v.ipynb) here for your reference.

Thank you!
