### ISSUE TITLE
//tensorflow/python/eager:forwardprop_test test fails on AARCH64

### ISSUE THREAD

**Issue by elfringham** [tensorflow/tensorflow#62208]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

git HEAD

### Custom code

No

### OS platform and distribution

Ubuntu 20.04

### Mobile device

n/a

### Python version

3.9.17

### Bazel version

6.1.0

### GCC/compiler version

17.0.0

### CUDA/cuDNN version

n/a

### GPU model and memory

n/a

### Current behavior?

Since Eigen was updated, the unit test //tensorflow/python/eager:forwardprop_test now fails.
Eigen was updated by https://github.com/tensorflow/tensorflow/commit/57e6377cf9879e33f3612f1ffd3619b6513e5296
It looks like this commit in Eigen is the problem.
https://gitlab.com/libeigen/eigen/-/commit/81b48065ea673cd352d11ef9b6a3d86778ac962d

This seems to only affect AARCH64 and not x86.

### Standalone code to reproduce the issue

```shell
bazel test --cache_test_results=no --build_tests_only --config=mkl_aarch64_threadpool --test_env=TF_ENABLE_ONEDNN_OPTS=1 --copt=-flax-vector-conversions --test_env=TF2_BEHAVIOR=1 --test_env=PORTSERVER_ADDRESS=@unittest-portserver --test_size_filters=small,medium --test_output=errors --verbose_failures=true --test_keep_going --notest_verbose_timeout_warnings --test_tag_filters=--oss_serial,-no_oss,-oss_excluded,-v1only,-benchmark-test,-no_aarch64,-no_oss_py38,-no_oss_py39,-no_oss_py310 --jobs=75 -- //tensorflow/python/eager:forwardprop_test
```

### Relevant log output

```shell
======================================================================
FAIL: testNumericHigherOrder (__main__.ForwardpropTest)
ForwardpropTest.testNumericHigherOrder
Warms up, gets object counts, runs the test, checks for new objects.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andrew/src/tf_test/tensorflow-git/bazel-ci_build-cache/.cache/bazel/_bazel_andrew/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/python/eager/forwardprop_test_cpu.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 713, in decorator
    f(self, *args, **kwargs)
  File "/home/andrew/src/tf_test/tensorflow-git/bazel-ci_build-cache/.cache/bazel/_bazel_andrew/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/python/eager/forwardprop_test_cpu.runfiles/org_tensorflow/tensorflow/python/eager/forwardprop_test.py", line 455, in testNumericHigherOrder
    _test_gradients(
  File "/home/andrew/src/tf_test/tensorflow-git/bazel-ci_build-cache/.cache/bazel/_bazel_andrew/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/python/eager/forwardprop_test_cpu.runfiles/org_tensorflow/tensorflow/python/eager/forwardprop_test.py", line 215, in _test_gradients
    _test_gradients(
  File "/home/andrew/src/tf_test/tensorflow-git/bazel-ci_build-cache/.cache/bazel/_bazel_andrew/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/python/eager/forwardprop_test_cpu.runfiles/org_tensorflow/tensorflow/python/eager/forwardprop_test.py", line 215, in _test_gradients
    _test_gradients(
  File "/home/andrew/src/tf_test/tensorflow-git/bazel-ci_build-cache/.cache/bazel/_bazel_andrew/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/python/eager/forwardprop_test_cpu.runfiles/org_tensorflow/tensorflow/python/eager/forwardprop_test.py", line 231, in _test_gradients
    testcase.assertAllClose(sym_jac_back, sym_jac_fwd, rtol=srtol, atol=satol)
  File "/home/andrew/src/tf_test/tensorflow-git/bazel-ci_build-cache/.cache/bazel/_bazel_andrew/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/python/eager/forwardprop_test_cpu.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 1657, in decorated
    return f(*args, **kwds)
           ^^^^^^^^^^^^^^^^
  File "/home/andrew/src/tf_test/tensorflow-git/bazel-ci_build-cache/.cache/bazel/_bazel_andrew/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/python/eager/forwardprop_test_cpu.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 3293, in assertAllClose
    self._assertAllCloseRecursive(a, b, rtol=rtol, atol=atol, msg=msg)
  File "/home/andrew/src/tf_test/tensorflow-git/bazel-ci_build-cache/.cache/bazel/_bazel_andrew/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/python/eager/forwardprop_test_cpu.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 3229, in _assertAllCloseRecursive
    self._assertArrayLikeAllClose(
  File "/home/andrew/src/tf_test/tensorflow-git/bazel-ci_build-cache/.cache/bazel/_bazel_andrew/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/python/eager/forwardprop_test_cpu.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 3186, in _assertArrayLikeAllClose
    np.testing.assert_allclose(
  File "/home/andrew/src/tf_test/tensorflow-git/bazel-ci_build-cache/.cache/bazel/_bazel_andrew/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/python/eager/forwardprop_test_cpu.runfiles/pypi_numpy/site-packages/numpy/testing/_private/utils.py", line 1527, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/home/andrew/src/tf_test/tensorflow-git/bazel-ci_build-cache/.cache/bazel/_bazel_andrew/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/python/eager/forwardprop_test_cpu.runfiles/pypi_numpy/site-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-06, atol=1e-06
Mismatched value: a is different from b. 
not close where = (array([0]), array([0]), array([2]))
not close lhs = [-155.46957]
not close rhs = [-155.46982]
not close dif = [0.00024414]
not close tol = [0.00015647]
dtype = float32, shape = (1, 4, 4)
Mismatched elements: 1 / 16 (6.25%)
Max absolute difference: 0.00024414
Max relative difference: 1.5703409e-06
 x: array([[[-4755.0654  ,  -139.43396 ,  -155.46957 ,   158.52019 ],
        [ -139.43398 ,  -119.946   ,   -26.157635,    20.20992 ],
        [ -155.4697  ,   -26.15764 ,   428.02136 ,  -365.0485  ],...
 y: array([[[-4755.0654  ,  -139.43398 ,  -155.46982 ,   158.52022 ],
        [ -139.43399 ,  -119.946014,   -26.157648,    20.209923],
        [ -155.46967 ,   -26.157635,   428.02112 ,  -365.04846 ],...

----------------------------------------------------------------------
Ran 13 tests in 95.972s

FAILED (failures=1)
================================================================================
```

**Comment by elfringham** [comment]
Issue raised on Eigen https://gitlab.com/libeigen/eigen/-/issues/2738
