### ISSUE TITLE
Building pip package broken by new shared object in build

### ISSUE THREAD

**Issue by elfringham** [tensorflow/tensorflow#62336]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

git HEAD

### Custom code

No

### OS platform and distribution

Ubuntu 20.04

### Mobile device

n/a

### Python version

3.9.17

### Bazel version

6.1.0

### GCC/compiler version

17.0.0

### CUDA/cuDNN version

n/a

### GPU model and memory

n/a

### Current behavior?

Auditwheel used during pip package creation fails due to unable to locate needed shared object.

Failure introduced by https://github.com/tensorflow/tensorflow/commit/96c01ac84cc5befb70d258a2ef06846a71d2bc0c

### Standalone code to reproduce the issue

```shell
$ bazel build --config=mkl_aarch64_threadpool --copt=-flax-vector-conversions --define=tf_api_version=2 --verbose_failures --jobs=100 -- //tensorflow/tools/pip_package:build_pip_package
$ bazel-bin/tensorflow/tools/pip_package/build_pip_package --cpu --project_name tensorflow_aarch64 ./tensorflow-pkg
$ auditwheel repair --plat manylinux2014_aarch64 -w /tensorflow/whl /workspace/tensorflow-pkg/tensorflow_aarch64-2.16.0-cp310-cp310-linux_aarch64.whl
```

### Relevant log output

```shell
INFO:auditwheel.main_repair:Repairing tensorflow_aarch64-2.16.0-cp310-cp310-linux_aarch64.whl
Traceback (most recent call last):
  File "/usr/local/bin/auditwheel", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/auditwheel/main.py", line 59, in main
    rval = args.func(args, p)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/auditwheel/main_repair.py", line 173, in execute
    out_wheel = repair_wheel(
                ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/auditwheel/repair.py", line 80, in repair_wheel
    raise ValueError(
ValueError: Cannot repair wheel, because required library "_pywrap_tensorflow_internal.so" could not be located
```

**Comment by elfringham** [comment]
Fixed by https://github.com/tensorflow/tensorflow/commit/ac91facc65a890dd703367a1fe5a14512de52012
