### ISSUE TITLE
@python_version_repo no longer visible after hermetic python changes

### ISSUE THREAD

**Issue by oberluz** [tensorflow/tensorflow#62340]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.14.0

### Custom code

Yes

### Bazel version

6.1.0

### Current behavior?

+load("@python//:defs.bzl", "interpreter")
+load("@rules_python//python:pip.bzl", "package_annotation", "pip_parse")
+
+

and the error is:

ERROR: Traceback (most recent call last):
File "/home/eyeot-demo/src/pycoral/WORKSPACE", line 100, column 49, in <toplevel>
load("@rules_python//python:repositories.bzl", "python_register_toolchains")
Error: file '@rules_python//python:repositories.bzl' does not contain symbol 'python_register_toolchains'
ERROR: error loading package '': Encountered error while reading extension file 'py_version.bzl': no such package '@python_version_repo//': error loading package 'external': Could not load //external package
Loading: 0 packages loaded

Could you suggest if I'm missing something?

### Standalone code to reproduce the issue

```shell
https://github.com/oberluz/pycoral/tree/2_14_0
```

**Comment by tilakrayal** [comment]
@oberluz,
Could you please provide the python version and the environment details where you are trying to install the tensorflow. It helps to debug the issue. Thank you!

**Comment by oberluz** [comment]
Python 3.11
ubuntu 22.04
arch amd64 (k8)

**Comment by pkgoogle** [comment]
I'm getting what looks like a different error when following the instructions:

that is after I do this:
```
git clone --recurse-submodules https://github.com/google-coral/pycoral
cd pycoral
git submodule init && git submodule update
sudo scripts/build.sh
```

```
SUBCOMMAND: # @com_google_absl//absl/hash:hash [action 'Compiling absl/hash/internal/hash.cc', configuration: 11cae9684ea823b3911201bf8ead584031fd2c07b224432188557a50a44d29ae, execution platform: @local_execution_config_platform//:platform]
(cd /root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/pycoral && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
    PWD=/proc/self/cwd \
  /usr/bin/arm-linux-gnueabihf-gcc -fPIC -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-march=armv7-a' '-mfpu=neon-vfpv4' -g0 -O3 -DNDEBUG '-D_FORTIFY_SOURCE=2' -ffunction-sections -fdata-sections -funsafe-math-optimizations -ftree-vectorize '-std=c++14' -MD -MF bazel-out/armv7a-opt/bin/external/com_google_absl/absl/hash/_objs/hash/hash.d '-frandom-seed=bazel-out/armv7a-opt/bin/external/com_google_absl/absl/hash/_objs/hash/hash.o' -iquote external/com_google_absl -iquote bazel-out/armv7a-opt/bin/external/com_google_absl '-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION' '-ffp-contract=off' -Wall -Wextra -Wcast-qual -Wconversion-null -Wmissing-declarations -Woverlength-strings -Wpointer-arith -Wundef -Wunused-local-typedefs -Wunused-result -Wvarargs -Wvla -Wwrite-strings -Wno-missing-field-initializers -Wno-sign-compare -DNOMINMAX -no-canonical-prefixes -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/com_google_absl/absl/hash/internal/hash.cc -o bazel-out/armv7a-opt/bin/external/com_google_absl/absl/hash/_objs/hash/hash.o)
SUBCOMMAND: # @clog//:clog [action 'Linking external/clog/libclog.a', configuration: 11cae9684ea823b3911201bf8ead584031fd2c07b224432188557a50a44d29ae, execution platform: @local_execution_config_platform//:platform]
(cd /root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/pycoral && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
    PWD=/proc/self/cwd \
  /usr/bin/arm-linux-gnueabihf-ar @bazel-out/armv7a-opt/bin/external/clog/libclog.a-2.params)
SUBCOMMAND: # @com_google_absl//absl/strings:cord [action 'Compiling absl/strings/cord.cc', configuration: 11cae9684ea823b3911201bf8ead584031fd2c07b224432188557a50a44d29ae, execution platform: @local_execution_config_platform//:platform]
(cd /root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/pycoral && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
    PWD=/proc/self/cwd \
  /usr/bin/arm-linux-gnueabihf-gcc -fPIC -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-march=armv7-a' '-mfpu=neon-vfpv4' -g0 -O3 -DNDEBUG '-D_FORTIFY_SOURCE=2' -ffunction-sections -fdata-sections -funsafe-math-optimizations -ftree-vectorize '-std=c++14' -MD -MF bazel-out/armv7a-opt/bin/external/com_google_absl/absl/strings/_objs/cord/cord.d '-frandom-seed=bazel-out/armv7a-opt/bin/external/com_google_absl/absl/strings/_objs/cord/cord.o' -iquote external/com_google_absl -iquote bazel-out/armv7a-opt/bin/external/com_google_absl '-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION' '-ffp-contract=off' -Wall -Wextra -Wcast-qual -Wconversion-null -Wmissing-declarations -Woverlength-strings -Wpointer-arith -Wundef -Wunused-local-typedefs -Wunused-result -Wvarargs -Wvla -Wwrite-strings -Wno-missing-field-initializers -Wno-sign-compare -DNOMINMAX -no-canonical-prefixes -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/com_google_absl/absl/strings/cord.cc -o bazel-out/armv7a-opt/bin/external/com_google_absl/absl/strings/_objs/cord/cord.o)
INFO: From Compiling tensorflow/lite/kernels/local_response_norm.cc:
In file included from external/ruy/ruy/pack.h:94,
                 from external/ruy/ruy/create_trmul_params.h:30,
                 from external/ruy/ruy/frontend.h:30,
                 from external/ruy/ruy/ruy.h:23,
                 from external/org_tensorflow/tensorflow/lite/kernels/cpu_backend_gemm_ruy.h:21,
                 from external/org_tensorflow/tensorflow/lite/kernels/cpu_backend_gemm.h:25,
                 from external/org_tensorflow/tensorflow/lite/kernels/internal/optimized/optimized_ops.h:45,
                 from external/org_tensorflow/tensorflow/lite/kernels/local_response_norm.cc:17:
external/ruy/ruy/pack_arm.h:492:9: warning: multi-line comment [-Wcomment]
  492 | #endif  // (RUY_PLATFORM_NEON_64 || RUY_PLATFORM_NEON_32) && \
      |         ^
In file included from external/org_tensorflow/tensorflow/lite/kernels/local_response_norm.cc:17:
external/org_tensorflow/tensorflow/lite/kernels/internal/optimized/optimized_ops.h: In instantiation of 'void tflite::optimized_ops::Transpose3D(const tflite::TransposeParams&, const tflite::RuntimeShape&, const T*, const tflite::RuntimeShape&, T*) [with T = float]':
external/org_tensorflow/tensorflow/lite/kernels/internal/optimized/optimized_ops.h:7376:16:   required from 'void tflite::optimized_ops::TransposeImpl(const tflite::TransposeParams&, const tflite::RuntimeShape&, const T*, const tflite::RuntimeShape&, T*) [with T = float; int N = 5]'
external/org_tensorflow/tensorflow/lite/kernels/internal/optimized/optimized_ops.h:7435:26:   required from 'void tflite::optimized_ops::Transpose(const tflite::TransposeParams&, const tflite::RuntimeShape&, const T*, const tflite::RuntimeShape&, T*) [with T = float; int N = 5]'
external/org_tensorflow/tensorflow/lite/kernels/internal/optimized/optimized_ops.h:8027:70:   required from here
external/org_tensorflow/tensorflow/lite/kernels/internal/optimized/optimized_ops.h:7305:7: warning: variable 's1' set but not used [-Wunused-but-set-variable]
 7305 |   int s1, s2, s3;
      |       ^~
SUBCOMMAND: # @org_tensorflow//tensorflow/lite/kernels/internal:quantization_util [action 'Compiling tensorflow/lite/kernels/internal/quantization_util.cc', configuration: 11cae9684ea823b3911201bf8ead584031fd2c07b224432188557a50a44d29ae, execution platform: @local_execution_config_platform//:platform]
(cd /root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/pycoral && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
    PWD=/proc/self/cwd \
  /usr/bin/arm-linux-gnueabihf-gcc -fPIC -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-march=armv7-a' '-mfpu=neon-vfpv4' -g0 -O3 -DNDEBUG '-D_FORTIFY_SOURCE=2' -ffunction-sections -fdata-sections -funsafe-math-optimizations -ftree-vectorize '-std=c++14' -MD -MF bazel-out/armv7a-opt/bin/external/org_tensorflow/tensorflow/lite/kernels/internal/_objs/quantization_util/quantization_util.d '-frandom-seed=bazel-out/armv7a-opt/bin/external/org_tensorflow/tensorflow/lite/kernels/internal/_objs/quantization_util/quantization_util.o' -iquote external/org_tensorflow -iquote bazel-out/armv7a-opt/bin/external/org_tensorflow '-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION' '-ffp-contract=off' -DFARMHASH_NO_CXX_STRING -Wno-sign-compare -O3 -fno-exceptions -no-canonical-prefixes -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/org_tensorflow/tensorflow/lite/kernels/internal/quantization_util.cc -o bazel-out/armv7a-opt/bin/external/org_tensorflow/tensorflow/lite/kernels/internal/_objs/quantization_util/quantization_util.o)
SUBCOMMAND: # @flatbuffers//src:flatbuffers [action 'Compiling src/code_generators.cpp', configuration: 11cae9684ea823b3911201bf8ead584031fd2c07b224432188557a50a44d29ae, execution platform: @local_execution_config_platform//:platform]
(cd /root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/pycoral && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
    PWD=/proc/self/cwd \
  /usr/bin/arm-linux-gnueabihf-gcc -fPIC -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-march=armv7-a' '-mfpu=neon-vfpv4' -g0 -O3 -DNDEBUG '-D_FORTIFY_SOURCE=2' -ffunction-sections -fdata-sections -funsafe-math-optimizations -ftree-vectorize '-std=c++14' -MD -MF bazel-out/armv7a-opt/bin/external/flatbuffers/src/_objs/flatbuffers/code_generators.d '-frandom-seed=bazel-out/armv7a-opt/bin/external/flatbuffers/src/_objs/flatbuffers/code_generators.o' -iquote external/flatbuffers -iquote bazel-out/armv7a-opt/bin/external/flatbuffers -Ibazel-out/armv7a-opt/bin/external/flatbuffers/src/_virtual_includes/flatbuffers '-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION' '-ffp-contract=off' -no-canonical-prefixes -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/flatbuffers/src/code_generators.cpp -o bazel-out/armv7a-opt/bin/external/flatbuffers/src/_objs/flatbuffers/code_generators.o)
SUBCOMMAND: # @org_tensorflow//tensorflow/lite/kernels/internal:transpose_utils [action 'Linking external/org_tensorflow/tensorflow/lite/kernels/internal/libtranspose_utils.a', configuration: 11cae9684ea823b3911201bf8ead584031fd2c07b224432188557a50a44d29ae, execution platform: @local_execution_config_platform//:platform]
(cd /root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/pycoral && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
    PWD=/proc/self/cwd \
  /usr/bin/arm-linux-gnueabihf-ar @bazel-out/armv7a-opt/bin/external/org_tensorflow/tensorflow/lite/kernels/internal/libtranspose_utils.a-2.params)
SUBCOMMAND: # @flatbuffers//src:flatbuffers [action 'Compiling src/idl_parser.cpp', configuration: 11cae9684ea823b3911201bf8ead584031fd2c07b224432188557a50a44d29ae, execution platform: @local_execution_config_platform//:platform]
(cd /root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/pycoral && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
    PWD=/proc/self/cwd \
  /usr/bin/arm-linux-gnueabihf-gcc -fPIC -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-march=armv7-a' '-mfpu=neon-vfpv4' -g0 -O3 -DNDEBUG '-D_FORTIFY_SOURCE=2' -ffunction-sections -fdata-sections -funsafe-math-optimizations -ftree-vectorize '-std=c++14' -MD -MF bazel-out/armv7a-opt/bin/external/flatbuffers/src/_objs/flatbuffers/idl_parser.d '-frandom-seed=bazel-out/armv7a-opt/bin/external/flatbuffers/src/_objs/flatbuffers/idl_parser.o' -iquote external/flatbuffers -iquote bazel-out/armv7a-opt/bin/external/flatbuffers -Ibazel-out/armv7a-opt/bin/external/flatbuffers/src/_virtual_includes/flatbuffers '-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION' '-ffp-contract=off' -no-canonical-prefixes -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/flatbuffers/src/idl_parser.cpp -o bazel-out/armv7a-opt/bin/external/flatbuffers/src/_objs/flatbuffers/idl_parser.o)
ERROR: /root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/ruy/ruy/BUILD:576:11: Compiling ruy/pack_arm.cc failed: (Exit 1): arm-linux-gnueabihf-gcc failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/sandbox/processwrapper-sandbox/1468/execroot/pycoral && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
    PWD=/proc/self/cwd \
  /usr/bin/arm-linux-gnueabihf-gcc -fPIC -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-march=armv7-a' '-mfpu=neon-vfpv4' -g0 -O3 -DNDEBUG '-D_FORTIFY_SOURCE=2' -ffunction-sections -fdata-sections -funsafe-math-optimizations -ftree-vectorize '-std=c++14' -MD -MF bazel-out/armv7a-opt/bin/external/ruy/ruy/_objs/pack_arm/pack_arm.d '-frandom-seed=bazel-out/armv7a-opt/bin/external/ruy/ruy/_objs/pack_arm/pack_arm.o' -iquote external/ruy -iquote bazel-out/armv7a-opt/bin/external/ruy -iquote external/cpuinfo -iquote bazel-out/armv7a-opt/bin/external/cpuinfo -iquote external/clog -iquote bazel-out/armv7a-opt/bin/external/clog -Ibazel-out/armv7a-opt/bin/external/cpuinfo/_virtual_includes/cpuinfo -Ibazel-out/armv7a-opt/bin/external/clog/_virtual_includes/clog '-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION' '-ffp-contract=off' -Wall -Wextra -Wc++14-compat -Wundef '-mfpu=neon' -O3 -no-canonical-prefixes -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/ruy/ruy/pack_arm.cc -o bazel-out/armv7a-opt/bin/external/ruy/ruy/_objs/pack_arm/pack_arm.o)
Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox arm-linux-gnueabihf-gcc failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/sandbox/processwrapper-sandbox/1468/execroot/pycoral && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
    PWD=/proc/self/cwd \
  /usr/bin/arm-linux-gnueabihf-gcc -fPIC -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-march=armv7-a' '-mfpu=neon-vfpv4' -g0 -O3 -DNDEBUG '-D_FORTIFY_SOURCE=2' -ffunction-sections -fdata-sections -funsafe-math-optimizations -ftree-vectorize '-std=c++14' -MD -MF bazel-out/armv7a-opt/bin/external/ruy/ruy/_objs/pack_arm/pack_arm.d '-frandom-seed=bazel-out/armv7a-opt/bin/external/ruy/ruy/_objs/pack_arm/pack_arm.o' -iquote external/ruy -iquote bazel-out/armv7a-opt/bin/external/ruy -iquote external/cpuinfo -iquote bazel-out/armv7a-opt/bin/external/cpuinfo -iquote external/clog -iquote bazel-out/armv7a-opt/bin/external/clog -Ibazel-out/armv7a-opt/bin/external/cpuinfo/_virtual_includes/cpuinfo -Ibazel-out/armv7a-opt/bin/external/clog/_virtual_includes/clog '-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION' '-ffp-contract=off' -Wall -Wextra -Wc++14-compat -Wundef '-mfpu=neon' -O3 -no-canonical-prefixes -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/ruy/ruy/pack_arm.cc -o bazel-out/armv7a-opt/bin/external/ruy/ruy/_objs/pack_arm/pack_arm.o)
Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox
In file included from external/ruy/ruy/pack_arm.cc:16:
external/ruy/ruy/pack_arm.h:492:9: warning: multi-line comment [-Wcomment]
  492 | #endif  // (RUY_PLATFORM_NEON_64 || RUY_PLATFORM_NEON_32) && \
      |         ^
external/ruy/ruy/pack_arm.cc: In function 'void ruy::Pack8bitColMajorForNeon4Cols(const ruy::PackParams8bit&)':
external/ruy/ruy/pack_arm.cc:469:72: error: 'asm' operand has impossible constraints
  469 |         "q4", "q5", "q6", "q7", "q8", "q9", "q10", "q11", "q12", "q13");
      |                                                                        ^
Target //src:_pywrap_coral failed to build
INFO: Elapsed time: 21.281s, Critical Path: 20.12s
INFO: 445 processes: 185 internal, 260 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
make: *** [Makefile:152: pybind] Error 1
make: Leaving directory '/workspace'
make: *** [/usr/local/google/home/xxxxx/git/pycoral/libcoral/docker/docker.mk:40: docker-build] Error 1
```

Can you let us know your exact commands? preferably with a fresh repo. I see a lot of cached actions, can you try clearing your docker cache to see if that changes anything?

Thanks for your help.

**Comment by oberluz** [comment]
Hi,

https://github.com/google-coral/pycoral is the wrong repo. Work in this repo stopped a couple of years back and it only supports Tensorflow v2.0.0. Note the release page only provides wheels for v2.0.0.

I cloned it to https://github.com/oberluz/pycoral.git and have ported to support Tensorflow v2.7.0 and v2.13.0. Each of these is on a separate branch for now. Support for Python 3.11 was introduced in Tensorflow v2.12.0.

This issue relates to branch 2_14_0. So you should clone (recursively)the repo I mentioned with branch 2_14_0.

I do not work for google. I'm just providing community support after a lot of people complained in the google-coral about lack of progress.

Note that https://github.com/oberluz/pycoral.git uses libedgepu and libcoral repos which I also cloned and modified to support 2.7, 2.13 and 2.14. These are linked as submodules (hence cursive clone)

Thanks for your help

**Comment by pkgoogle** [comment]
@oberluz,

Thanks for your help, I'm reaching the following error now, hopefully you can help me get past it:

My steps:
```
git clone --recurse-submodules https://github.com/oberluz/pycoral.git
cd pycoral
git submodule init && git submodule update
DOCKER_CPUS="k8" ./scripts/build.sh --python_versions 310
```

```
DOCKER_CPUS="k8" ./scripts/build.sh --python_versions 310
+++ dirname ./scripts/build.sh
++ cd ./scripts
++ pwd
+ readonly SCRIPT_DIR=/usr/local/google/home/xxxxx/git/pycoral/scripts
+ SCRIPT_DIR=/usr/local/google/home/xxxxxx/git/pycoral/scripts
+ readonly MAKEFILE=/usr/local/google/home/xxxxxx/git/pycoral/scripts/../Makefile
+ MAKEFILE=/usr/local/google/home/xxxxxx/git/pycoral/scripts/../Makefile
+ readonly DOCKER_CPUS=k8
+ DOCKER_CPUS=k8
+ PYTHON_VERSIONS='36 37 38 39'
+ [[ 2 -gt 0 ]]
+ case "$1" in
+ PYTHON_VERSIONS=310
+ shift
+ shift
+ [[ 0 -gt 0 ]]
+ for python_version in ${PYTHON_VERSIONS}
++ docker_image 310
++ case $1 in
++ echo 'Unsupported python version: 310'
Unsupported python version: 310
++ exit 1
+ make DOCKER_CPUS=k8 DOCKER_IMAGE= 'DOCKER_TARGETS=pybind tflite wheel tflite-wheel' -f /usr/local/google/home/xxxxxx/git/pycoral/scripts/../Makefile docker-build
docker build  -t "coral-edgetpu-" \
    --build-arg IMAGE= /usr/local/google/home/xxxxx/git/pycoral/libcoral/docker
[+] Building 0.0s (0/0)                                                         
ERROR: invalid tag "coral-edgetpu-": invalid reference format
make: *** [/usr/local/google/home/xxxxxx/git/pycoral/libcoral/docker/docker.mk:31: docker-image] Error 1
```

You may want to update your compilation instructions on your README so that it points to your new repo rather than the original.

**Comment by oberluz** [comment]
Hi,

try as follows:

```
$ git clone https://github.com/google-coral/pycoral
$ cd pycoral
$ git checkout 2_14_0
$ git submodule update --init --recursive
$ DOCKER_CPUS="k8" ./scripts/build.sh --python_versions 310
```

**Comment by pkgoogle** [comment]
I was able to reproduce with the following steps:

```
$ git clone https://github.com/oberluz/pycoral.git
$ cd pycoral
$ git checkout 2_14_0
$ git submodule update --init --recursive
$ DOCKER_CPUS="k8" ./scripts/build.sh --python_versions 310
```

After the docker finishes
```
make: Entering directory '/workspace'
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/769f5cc9b8732933140b09e8808d13614182b496.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/668e33c6401abe7844691fb7d47a3cf2d2012dbc.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
 checking cached actions
 checking cached actions
 checking cached actions
 checking cached actions
ERROR: Traceback (most recent call last):
	File "/workspace/WORKSPACE", line 100, column 49, in <toplevel>
		load("@rules_python//python:repositories.bzl", "python_register_toolchains")
Error: file '@rules_python//python:repositories.bzl' does not contain symbol 'python_register_toolchains'
ERROR: Error computing the main repository mapping: Encountered error while reading extension file 'py_version.bzl': no such package '@python_version_repo//': error loading package 'external': Could not load //external package
 checking cached actions
PYTHON_BIN_PATH=/usr/bin/python3 bazel build --sandbox_debug --compilation_mode=opt --copt=-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION --cpu=k8 --linkopt=-L/workspace/libedgetpu_bin/direct/k8 --linkopt=-l:libedgetpu.so.1 --linkopt=-Wl,--strip-all \
    --embed_label='TENSORFLOW_COMMIT=' \
    --stamp \
    //src:_pywrap_coral
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/668e33c6401abe7844691fb7d47a3cf2d2012dbc.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/769f5cc9b8732933140b09e8808d13614182b496.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
ERROR: Traceback (most recent call last):
	File "/workspace/WORKSPACE", line 100, column 49, in <toplevel>
		load("@rules_python//python:repositories.bzl", "python_register_toolchains")
Error: file '@rules_python//python:repositories.bzl' does not contain symbol 'python_register_toolchains'
ERROR: Error computing the main repository mapping: Encountered error while reading extension file 'py_version.bzl': no such package '@python_version_repo//': error loading package 'external': Could not load //external package
Loading: 
make: *** [Makefile:154: pybind] Error 1
make: Leaving directory '/workspace'
make: *** [/usr/local/google/home/xxxxxxx/git/pycoral/libcoral/docker/docker.mk:40: docker-build] Error 1
```

Hi @terryheo, can you please take a look? Thanks.

**Comment by oberluz** [comment]
@terryheo just to clarify, if I use the previous commit in the 2_14_0 branch which didn't have the hermetic python definitions the behaviour is as follows (the definitions were added in an attempt to fix this error):

```
Loading: 1 packages loaded
PYTHON_BIN_PATH=/usr/bin/python3 bazel build --sandbox_debug --compilation_mode=opt --copt=-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION --cpu=k8 --linkopt=-L/workspace/libedgetpu_bin/direct/k8 --linkopt=-l:libedgetpu.so.1 --linkopt=-Wl,--strip-all \
    --embed_label='TENSORFLOW_COMMIT=4dacf3f368eb7965e9b5c3bbdd5193986081c3b2' \
    --stamp \
    //src:_pywrap_coral
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/668e33c6401abe7844691fb7d47a3cf2d2012dbc.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/769f5cc9b8732933140b09e8808d13614182b496.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/081771d4a0e9d7d3aa0eed2ef389fa4700dfb23e.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
INFO: Repository go_sdk instantiated at:
  /workspace/WORKSPACE:37:14: in <toplevel>
  /home/eyeot-demo/.cache/bazel/_bazel_eyeot-demo/eab0d61a99b6696edb3d2aff87b585e8/external/org_tensorflow/tensorflow/workspace0.bzl:135:20: in workspace
  /home/eyeot-demo/.cache/bazel/_bazel_eyeot-demo/eab0d61a99b6696edb3d2aff87b585e8/external/com_github_grpc_grpc/bazel/grpc_extra_deps.bzl:36:27: in grpc_extra_deps
  /home/eyeot-demo/.cache/bazel/_bazel_eyeot-demo/eab0d61a99b6696edb3d2aff87b585e8/external/io_bazel_rules_go/go/private/sdk.bzl:431:28: in go_register_toolchains
  /home/eyeot-demo/.cache/bazel/_bazel_eyeot-demo/eab0d61a99b6696edb3d2aff87b585e8/external/io_bazel_rules_go/go/private/sdk.bzl:130:21: in go_download_sdk
Repository rule _go_download_sdk defined at:
  /home/eyeot-demo/.cache/bazel/_bazel_eyeot-demo/eab0d61a99b6696edb3d2aff87b585e8/external/io_bazel_rules_go/go/private/sdk.bzl:117:35: in <toplevel>
ERROR: /workspace/src/BUILD:67:17: While resolving toolchains for target //src:_pywrap_coral.so: invalid registered toolchain '@local_execution_config_python//:py_toolchain': error loading package '@local_execution_config_python//': Unable to find package for @python//:defs.bzl: The repository '@python' could not be resolved: Repository '@python' is not defined.
ERROR: Analysis of target '//src:_pywrap_coral' failed; build aborted: 
INFO: Elapsed time: 2.569s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (20 packages loaded, 10 targets configured)
    currently loading: @local_execution_config_python// ... (15 packages)
make: *** [Makefile:154: pybind] Error 1
make: Leaving directory '/workspace'
make: *** [/home/eyeot-demo/src/pycoral/libcoral/docker/docker.mk:40: docker-build] Error 1
```

**Comment by oberluz** [comment]
@pkgoogle it seems @terryheo is not going to pick this up. Could yo reassign to someone else?

**Comment by oberluz** [comment]
Hi @pkgoogle I understand. I'll wait as I tried fixing it for a few days before raising this issue and didn't get anywhere...

**Comment by gaikwadrahul8** [comment]
Hi, @oberluz 

Thanks for raising this issue. Are you aware of the migration to [LiteRT](https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/)? This transition is aimed at enhancing our project's capabilities and providing improved support and focus for our users. As we believe this issue is still relevant to LiteRT we are moving your issue there. Please follow progress here: 
https://github.com/google-ai-edge/LiteRT/issues/99

Let us know if you have any questions. Thanks.
