### ISSUE TITLE
KeyError: 'CreateRangeDecoder'

### ISSUE THREAD

**Issue by ZH-1225** [tensorflow/tensorflow#62387]
Traceback (most recent call last):
  File "/home/xzh/.local/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 3022, in op_def_for_type
    return self._op_def_cache[type]
KeyError: 'CreateRangeDecoder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xzh/.local/bin/tflite_convert", line 8, in <module>
    sys.exit(main())
  File "/home/xzh/.local/lib/python3.10/site-packages/tensorflow/lite/python/tflite_convert.py", line 690, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/home/xzh/.local/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/xzh/.local/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/xzh/.local/lib/python3.10/site-packages/tensorflow/lite/python/tflite_convert.py", line 673, in run_main
    _convert_tf2_model(tflite_flags)
  File "/home/xzh/.local/lib/python3.10/site-packages/tensorflow/lite/python/tflite_convert.py", line 274, in _convert_tf2_model
    converter = lite.TFLiteConverterV2.from_saved_model(
  File "/home/xzh/.local/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 2073, in from_saved_model
    saved_model = _load(saved_model_dir, tags)
  File "/home/xzh/.local/lib/python3.10/site-packages/tensorflow/python/saved_model/load.py", line 900, in load
    result = load_partial(export_dir, None, tags, options)["root"]
  File "/home/xzh/.local/lib/python3.10/site-packages/tensorflow/python/saved_model/load.py", line 1031, in load_partial
    loader = Loader(object_graph_proto, saved_model_proto, export_dir,
  File "/home/xzh/.local/lib/python3.10/site-packages/tensorflow/python/saved_model/load.py", line 161, in __init__
    function_deserialization.load_function_def_library(
  File "/home/xzh/.local/lib/python3.10/site-packages/tensorflow/python/saved_model/function_deserialization.py", line 456, in load_function_def_library
    func_graph = function_def_lib.function_def_to_graph(
  File "/home/xzh/.local/lib/python3.10/site-packages/tensorflow/python/framework/function_def_to_graph.py", line 91, in function_def_to_graph
    graph_def, nested_to_flat_tensor_name = function_def_to_graph_def(
  File "/home/xzh/.local/lib/python3.10/site-packages/tensorflow/python/framework/function_def_to_graph.py", line 330, in function_def_to_graph_def
    op_def = default_graph.op_def_for_type(node_def.op)  # pylint: disable=protected-access
  File "/home/xzh/.local/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 3025, in op_def_for_type
    self._op_def_for_type(type)
RuntimeError: Op type not registered 'CreateRangeDecoder' in binary running on xzh-virtual-machine. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib (e.g. `tf.contrib.resampler`), accessing should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

**Comment by Venkat6871** [comment]
Hi **@ZH-1225** ,
Can you add templates.
Thank you!
