### ISSUE TITLE
Encountering an error when using " tf.config.experimental.enable_op_determinism() 

### ISSUE THREAD

**Issue by k1379432** [tensorflow/tensorflow#62449]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tf2.10

### Custom code

Yes

### OS platform and distribution

Windows

### Mobile device

Windows

### Python version

3.7

### CUDA/cuDNN version

cuDNN11.2/CUDA 11.2

### GPU model and memory

NVIDIA GeForce RTX 2080 Ti

### Current behavior?

"I'm encountering an error in the optimizer_v2.py file when using " tf.config.experimental.enable_op_determinism() ", and I'm unsure how to resolve it

### Standalone code to reproduce the issue

```shell
from tensorflow.keras.models import *
from tensorflow.keras.layers import *

from tensorflow.keras.applications import ResNet50, ResNet101, ResNet152, NASNetMobile
#from tensorflow.keras.applications import EfficientNetB4, EfficientNetB5, EfficientNetV2S, ConvNeXtBase
import tensorflow.keras.backend as K
import tensorflow as tf 
import random
import os 






def random_seed(seed):
    os.environ['PYTHONHASHSEED'] = str(seed) # Python general
    random.seed(seed) # Python random
    tf.random.set_seed(seed)
    tf.keras.utils.set_random_seed(seed)
    tf.compat.v1.set_random_seed(42)
    os.environ['TF_CUDNN_DETERMINISTIC'] = '1' 
    tf.config.experimental.enable_op_determinism()
    
random_seed(42)
```

### Relevant log output

```shell
2023-11-21 20:44:13.447175: I tensorflow/stream_executor/cuda/cuda_dnn.cc:384] Loaded cuDNN version 8100
Traceback (most recent call last):
  File "training2.py", line 155, in <module>
    callbacks=[ checkpoint, logger, early_stop ])
  File "C:\Users\LAB\anaconda3\envs\test2\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\LAB\anaconda3\envs\test2\lib\site-packages\tensorflow\python\eager\execute.py", line 55, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.UnimplementedError: Graph execution error:

Detected at node 'gradient_tape/model/FPN2.upsample/resize/ResizeNearestNeighborGrad' defined at (most recent call last):
    File "training2.py", line 155, in <module>
      callbacks=[ checkpoint, logger, early_stop ])
    File "C:\Users\LAB\anaconda3\envs\test2\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\LAB\anaconda3\envs\test2\lib\site-packages\keras\engine\training.py", line 1409, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\LAB\anaconda3\envs\test2\lib\site-packages\keras\engine\training.py", line 1051, in train_function
      return step_function(self, iterator)
    File "C:\Users\LAB\anaconda3\envs\test2\lib\site-packages\keras\engine\training.py", line 1040, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\LAB\anaconda3\envs\test2\lib\site-packages\keras\engine\training.py", line 1030, in run_step
      outputs = model.train_step(data)
    File "C:\Users\LAB\anaconda3\envs\test2\lib\site-packages\keras\engine\training.py", line 893, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "C:\Users\LAB\anaconda3\envs\test2\lib\site-packages\keras\optimizers\optimizer_v2\optimizer_v2.py", line 538, in minimize
      loss, var_list=var_list, grad_loss=grad_loss, tape=tape)
    File "C:\Users\LAB\anaconda3\envs\test2\lib\site-packages\keras\optimizers\optimizer_v2\optimizer_v2.py", line 590, in _compute_gradients
      grads_and_vars = self._get_gradients(tape, loss, var_list, grad_loss)
    File "C:\Users\LAB\anaconda3\envs\test2\lib\site-packages\keras\optimizers\optimizer_v2\optimizer_v2.py", line 471, in _get_gradients
      grads = tape.gradient(loss, var_list, grad_loss)
Node: 'gradient_tape/model/FPN2.upsample/resize/ResizeNearestNeighborGrad'
A deterministic GPU implementation of ResizeNearestNeighborGrad is not currently available.
         [[{{node gradient_tape/model/FPN2.upsample/resize/ResizeNearestNeighborGrad}}]] [Op:__inference_train_function_36513]
2023-11-21 20:44:16.419233: W tensorflow/core/kernels/data/generator_dataset_op.cc:108] Error occurred when finalizing GeneratorDataset iterator: FAILED_PRECONDITION: Python interpreter state is not initialized. The process may be terminated.
         [[{{node PyFunc}}]]
```

**Comment by sushreebarsa** [comment]
@k1379432 Please try to upgrade to the latest TF version. I tried it on colab and didn't face any issue, please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/20f9ca2a12c62aec2f71db21b244a951/62449.ipynb). We need to check whether it is an issue with windows OS ? 
Thank you!

**Comment by Masumekeshavarzi** [comment]
change the interpolation in your upsampling from NearestNeighbor.... to bilinear
