### ISSUE TITLE
When I import tensorflow as tf with python=3.9.6,there are errors

### ISSUE THREAD

**Issue by ABtwo** [tensorflow/tensorflow#62479]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tensorflow-GPU 2.6

### Custom code

Yes

### Python version

3.9

### CUDA/cuDNN version

12.3 cudnn version :8.9.6

### Current behavior?

 import tensorflow as tf
C:\Users\dell\.conda\envs\tf-gpu\lib\site-packages\tensorflow\python\framework\dtypes.py:585: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  np.object,
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\dell\.conda\envs\tf-gpu\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\dell\.conda\envs\tf-gpu\lib\site-packages\tensorflow\python\__init__.py", line 46, in <module>
    from tensorflow.python import data
  File "C:\Users\dell\.conda\envs\tf-gpu\lib\site-packages\tensorflow\python\data\__init__.py", line 25, in <module>
    from tensorflow.python.data import experimental
  File "C:\Users\dell\.conda\envs\tf-gpu\lib\site-packages\tensorflow\python\data\experimental\__init__.py", line 97, in <module>
    from tensorflow.python.data.experimental import service
  File "C:\Users\dell\.conda\envs\tf-gpu\lib\site-packages\tensorflow\python\data\experimental\service\__init__.py", line 353, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "C:\Users\dell\.conda\envs\tf-gpu\lib\site-packages\tensorflow\python\data\experimental\ops\data_service_ops.py", line 26, in <module>
    from tensorflow.python.data.experimental.ops import compression_ops
  File "C:\Users\dell\.conda\envs\tf-gpu\lib\site-packages\tensorflow\python\data\experimental\ops\compression_ops.py", line 20, in <module>
    from tensorflow.python.data.util import structure
  File "C:\Users\dell\.conda\envs\tf-gpu\lib\site-packages\tensorflow\python\data\util\structure.py", line 26, in <module>
    from tensorflow.python.data.util import nest
  File "C:\Users\dell\.conda\envs\tf-gpu\lib\site-packages\tensorflow\python\data\util\nest.py", line 40, in <module>
    from tensorflow.python.framework import sparse_tensor as _sparse_tensor
  File "C:\Users\dell\.conda\envs\tf-gpu\lib\site-packages\tensorflow\python\framework\sparse_tensor.py", line 28, in <module>
    from tensorflow.python.framework import constant_op
  File "C:\Users\dell\.conda\envs\tf-gpu\lib\site-packages\tensorflow\python\framework\constant_op.py", line 29, in <module>
    from tensorflow.python.eager import execute
  File "C:\Users\dell\.conda\envs\tf-gpu\lib\site-packages\tensorflow\python\eager\execute.py", line 27, in <module>
    from tensorflow.python.framework import dtypes
  File "C:\Users\dell\.conda\envs\tf-gpu\lib\site-packages\tensorflow\python\framework\dtypes.py", line 585, in <module>
    np.object,
  File "C:\Users\dell\.conda\envs\tf-gpu\lib\site-packages\numpy\__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
and the version of numpy is 1.26.
```

### Relevant log output

```shell
import tensorflow as tf
C:\Users\dell\.conda\envs\tf-gpu\lib\site-packages\tensorflow\python\framework\dtypes.py:585: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  np.object,
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\dell\.conda\envs\tf-gpu\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\dell\.conda\envs\tf-gpu\lib\site-packages\tensorflow\python\__init__.py", line 46, in <module>
    from tensorflow.python import data
  File "C:\Users\dell\.conda\envs\tf-gpu\lib\site-packages\tensorflow\python\data\__init__.py", line 25, in <module>
    from tensorflow.python.data import experimental
  File "C:\Users\dell\.conda\envs\tf-gpu\lib\site-packages\tensorflow\python\data\experimental\__init__.py", line 97, in <module>
    from tensorflow.python.data.experimental import service
  File "C:\Users\dell\.conda\envs\tf-gpu\lib\site-packages\tensorflow\python\data\experimental\service\__init__.py", line 353, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "C:\Users\dell\.conda\envs\tf-gpu\lib\site-packages\tensorflow\python\data\experimental\ops\data_service_ops.py", line 26, in <module>
    from tensorflow.python.data.experimental.ops import compression_ops
  File "C:\Users\dell\.conda\envs\tf-gpu\lib\site-packages\tensorflow\python\data\experimental\ops\compression_ops.py", line 20, in <module>
    from tensorflow.python.data.util import structure
  File "C:\Users\dell\.conda\envs\tf-gpu\lib\site-packages\tensorflow\python\data\util\structure.py", line 26, in <module>
    from tensorflow.python.data.util import nest
  File "C:\Users\dell\.conda\envs\tf-gpu\lib\site-packages\tensorflow\python\data\util\nest.py", line 40, in <module>
    from tensorflow.python.framework import sparse_tensor as _sparse_tensor
  File "C:\Users\dell\.conda\envs\tf-gpu\lib\site-packages\tensorflow\python\framework\sparse_tensor.py", line 28, in <module>
    from tensorflow.python.framework import constant_op
  File "C:\Users\dell\.conda\envs\tf-gpu\lib\site-packages\tensorflow\python\framework\constant_op.py", line 29, in <module>
    from tensorflow.python.eager import execute
  File "C:\Users\dell\.conda\envs\tf-gpu\lib\site-packages\tensorflow\python\eager\execute.py", line 27, in <module>
    from tensorflow.python.framework import dtypes
  File "C:\Users\dell\.conda\envs\tf-gpu\lib\site-packages\tensorflow\python\framework\dtypes.py", line 585, in <module>
    np.object,
  File "C:\Users\dell\.conda\envs\tf-gpu\lib\site-packages\numpy\__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

**Comment by vikasr54389** [comment]
hello have u installed tensorflow library

**Comment by sushreebarsa** [comment]
@ABtwo Please try to upgrade to the latest TF version as you are using an older version. If you are not using a virtual environment, you may need to uninstall Python 3.9.6 and install a different version of Python, such as Python 3.8 or Python 3.10. 
Please have a look at the following code to execute the same in virtual environment;
```
python3.8 -m venv tfenv
source tfenv/bin/activate
pip install tensorflow
```


Thank you!

**Comment by chinworker** [comment]
I also met this problem. and i browsered https://numpy.org/devdocs/release/1.20.0-notes.html found that it's obviously tensorflow are using numpy before 2.0 and accroding to numpy notes np.object can be safely change to object may someone do a favour to catch up with numpy's version.
