### ISSUE TITLE
 Op type not registered 'DisableCopyOnRead'

### ISSUE THREAD

**Issue by pedro21900** [tensorflow/tensorflow#62489]
I'm running my model in java and I get this error. My project was all done in Python, what should I do to solve this problem? Do I register this in Python or adjust it in Java?

Restoring SavedModel bundle.

```python
2023-11-27 16:43:21.653275: I tensorflow/cc/saved_model/loader.cc:151] Running initialization op on SavedModel bundle at path: /home/lenonn/git/fill-evidence/src/main/resources/ml_fill_evidence
2023-11-27 16:43:21.656519: I tensorflow/cc/saved_model/loader.cc:311] SavedModel load for tags { serve }; Status: success. Took 46958 microseconds.
org.tensorflow.TensorFlowException: Op type not registered 'DisableCopyOnRead' in binary running on rpawsds077523. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
        at org.tensorflow.SavedModelBundle.load(Native Method)
        at org.tensorflow.SavedModelBundle.access$000(SavedModelBundle.java:27)
        at org.tensorflow.SavedModelBundle$Loader.load(SavedModelBundle.java:32)
        at org.tensorflow.SavedModelBundle.load(SavedModelBundle.java:95)
        at site.horizon.fillevidence.service.TensorFlowInferenceService.exec(TensorFlowInferenceService.java:28)
        at site.horizon.fillevidence.FillEvidenceApplication.run(FillEvidenceApplication.java:28)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:768)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
        at site.horizon.fillevidence.FillEvidenceApplication.main(FillEvidenceApplication.java:21)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:50)

```

**Comment by sushreebarsa** [comment]
@pedro21900 Could you please let us know the TF version you are using here?
I tried to replicate the issue and faced another [error](https://colab.research.google.com/gist/sushreebarsa/159fb268b06d7e90f30d20452758dc08/62489.ipynb) so could you please provide all the dependencies to replicate the issue reported. Thank you!

**Comment by pedro21900** [comment]
Any ideas what to do

**Comment by pedro21900** [comment]
```xml 
<dependency>
			<groupId>org.tensorflow</groupId>
			<artifactId>tensorflow</artifactId>
			<version>1.15.0</version>
</dependency>
```
