### ISSUE TITLE
Issue in instally Tensorflow-gpu

### ISSUE THREAD

**Issue by jatindarkumar12** [tensorflow/tensorflow#62613]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

latest

### Custom code

Yes

### Mobile device

windows

### Python version

3.11.5

### CUDA/cuDNN version

12.3 cuda

### GPU model and memory

nvidia gtx 1650

### Current behavior?

Actually sir , i want to train my tensorflow model on my gpu 
but when i setup my gpu 
so every setup is done 
but in last when i run this command " pip install tensorflow-gpu"
it give me error 
why?

### Standalone code to reproduce the issue

```shell
see above
```

### Relevant log output

```shell
Collecting tensorflow-gpu
  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      Traceback (most recent call last):
        File "C:\ProgramData\anaconda3\Lib\site-packages\setuptools\_vendor\packaging\requirements.py", line 35, in __init__
          parsed = _parse_requirement(requirement_string)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\ProgramData\anaconda3\Lib\site-packages\setuptools\_vendor\packaging\_parser.py", line 64, in parse_requirement
          return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\ProgramData\anaconda3\Lib\site-packages\setuptools\_vendor\packaging\_parser.py", line 82, in _parse_requirement
          url, specifier, marker = _parse_requirement_details(tokenizer)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\ProgramData\anaconda3\Lib\site-packages\setuptools\_vendor\packaging\_parser.py", line 126, in _parse_requirement_details
          marker = _parse_requirement_marker(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\ProgramData\anaconda3\Lib\site-packages\setuptools\_vendor\packaging\_parser.py", line 147, in _parse_requirement_marker
          tokenizer.raise_syntax_error(
        File "C:\ProgramData\anaconda3\Lib\site-packages\setuptools\_vendor\packaging\_tokenizer.py", line 165, in raise_syntax_error
          raise ParserSyntaxError(
      setuptools.extern.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after name and no valid version specifier)
          python_version>"3.7"
                        ^

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Jatindar Kumar\AppData\Local\Temp\pip-install-6mm7r8qr\tensorflow-gpu_1cfe51ebc0264a7b8bb3ba70f4f234d8\setup.py", line 40, in <module>
          setuptools.setup()
        File "C:\ProgramData\anaconda3\Lib\site-packages\setuptools\__init__.py", line 106, in setup
          _install_setup_requires(attrs)
        File "C:\ProgramData\anaconda3\Lib\site-packages\setuptools\__init__.py", line 77, in _install_setup_requires
          dist.parse_config_files(ignore_option_errors=True)
        File "C:\ProgramData\anaconda3\Lib\site-packages\setuptools\dist.py", line 900, in parse_config_files
          self._finalize_requires()
        File "C:\ProgramData\anaconda3\Lib\site-packages\setuptools\dist.py", line 597, in _finalize_requires
          self._move_install_requirements_markers()
        File "C:\ProgramData\anaconda3\Lib\site-packages\setuptools\dist.py", line 637, in _move_install_requirements_markers
          inst_reqs = list(_reqs.parse(spec_inst_reqs))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\ProgramData\anaconda3\Lib\site-packages\setuptools\_vendor\packaging\requirements.py", line 37, in __init__
          raise InvalidRequirement(str(e)) from e
      setuptools.extern.packaging.requirements.InvalidRequirement: Expected end or semicolon (after name and no valid version specifier)
          python_version>"3.7"
                        ^
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by sushreebarsa** [comment]
@jatindarkumar12  Make sure you are using the latest version of pip. You can update pip by running the following command:
```
python -m pip install --upgrade pip

```
You can install TensorFlow with the following command:
```
python -m pip install tensorflow
```
You may need to install additional build dependencies for TensorFlow. The specific dependencies will vary depending on your operating system and environment. You can find instructions for installing build dependencies on the TensorFlow website: https://www.tensorflow.org/install

Thank you!

**Comment by MichaelHudgins** [comment]
Following up on the above.  We do not publish to the `tensorflow-gpu` pypi repository since 2.12.   The base `tensorflow` package has had NVIDIA GPU support since 2.1.0. so you likely should be pip installing using `tensorflow` and not `tensorflow-gpu`.  See https://pypi.org/project/tensorflow-gpu/ for more info on this modification.
