### ISSUE TITLE
Error in `pip install tensorflow-gpu`

### ISSUE THREAD

**Issue by BaseMax** [tensorflow/tensorflow#62675]
```
Microsoft Windows [Version 10.0.22631.2861]
(c) Microsoft Corporation. All rights reserved.

C:\Users\MAX>pip install tensorflow-gpu
Defaulting to user installation because normal site-packages is not writeable
Collecting tensorflow-gpu
  Downloading tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [58 lines of output]
      Traceback (most recent call last):
        File "C:\Users\MAX\AppData\Local\Temp\pip-build-env-jmodbs81\overlay\Lib\site-packages\setuptools\_vendor\packaging\requirements.py", line 35, in __init__
          parsed = _parse_requirement(requirement_string)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\MAX\AppData\Local\Temp\pip-build-env-jmodbs81\overlay\Lib\site-packages\setuptools\_vendor\packaging\_parser.py", line 64, in parse_requirement
          return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\MAX\AppData\Local\Temp\pip-build-env-jmodbs81\overlay\Lib\site-packages\setuptools\_vendor\packaging\_parser.py", line 82, in _parse_requirement
          url, specifier, marker = _parse_requirement_details(tokenizer)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\MAX\AppData\Local\Temp\pip-build-env-jmodbs81\overlay\Lib\site-packages\setuptools\_vendor\packaging\_parser.py", line 126, in _parse_requirement_details
          marker = _parse_requirement_marker(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\MAX\AppData\Local\Temp\pip-build-env-jmodbs81\overlay\Lib\site-packages\setuptools\_vendor\packaging\_parser.py", line 147, in _parse_requirement_marker
          tokenizer.raise_syntax_error(
        File "C:\Users\MAX\AppData\Local\Temp\pip-build-env-jmodbs81\overlay\Lib\site-packages\setuptools\_vendor\packaging\_tokenizer.py", line 165, in raise_syntax_error
          raise ParserSyntaxError(
      setuptools.extern.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after name and no valid version specifier)
          python_version>"3.7"
                        ^

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "C:\Users\MAX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\MAX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\MAX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\MAX\AppData\Local\Temp\pip-build-env-jmodbs81\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\MAX\AppData\Local\Temp\pip-build-env-jmodbs81\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\MAX\AppData\Local\Temp\pip-build-env-jmodbs81\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\MAX\AppData\Local\Temp\pip-build-env-jmodbs81\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 40, in <module>
        File "C:\Users\MAX\AppData\Local\Temp\pip-build-env-jmodbs81\overlay\Lib\site-packages\setuptools\__init__.py", line 102, in setup
          _install_setup_requires(attrs)
        File "C:\Users\MAX\AppData\Local\Temp\pip-build-env-jmodbs81\overlay\Lib\site-packages\setuptools\__init__.py", line 73, in _install_setup_requires
          dist.parse_config_files(ignore_option_errors=True)
        File "C:\Users\MAX\AppData\Local\Temp\pip-build-env-jmodbs81\overlay\Lib\site-packages\setuptools\dist.py", line 629, in parse_config_files
          self._finalize_requires()
        File "C:\Users\MAX\AppData\Local\Temp\pip-build-env-jmodbs81\overlay\Lib\site-packages\setuptools\dist.py", line 364, in _finalize_requires
          self._normalize_requires()
        File "C:\Users\MAX\AppData\Local\Temp\pip-build-env-jmodbs81\overlay\Lib\site-packages\setuptools\dist.py", line 379, in _normalize_requires
          self.install_requires = list(map(str, _reqs.parse(install_requires)))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\MAX\AppData\Local\Temp\pip-build-env-jmodbs81\overlay\Lib\site-packages\setuptools\_vendor\packaging\requirements.py", line 37, in __init__
          raise InvalidRequirement(str(e)) from e
      setuptools.extern.packaging.requirements.InvalidRequirement: Expected end or semicolon (after name and no valid version specifier)
          python_version>"3.7"
                        ^
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

More details:

```
C:\Users\MAX>python --version
Python 3.12.1

C:\Users\MAX>pip --version
pip 23.3.2 from C:\Users\MAX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pip (python 3.12)

C:\Users\MAX>where python
C:\Users\MAX\AppData\Local\Microsoft\WindowsApps\python.exe
```

**Comment by sushreebarsa** [comment]
@BaseMax Please make sure that you have followed the official [doc ](https://www.tensorflow.org/install/source_windows)  and also referred the gpu support [guide](https://www.tensorflow.org/install/pip#windows-wsl2) .
Thank you!

**Comment by SunilKumarPradhan** [comment]
# Setting up TensorFlow with GPU on Windows - Step-by-Step Guide

## Document Formatting for Notepad:

To enhance readability, follow these steps in Notepad:
1. Navigate to [FILE EDIT FORMAT VIEW HELP] above tabs.
2. Go to `FORMAT` and select `Word Wrap`.

## Installation Steps:

### 1. Download Anaconda:
   - Link: [Anaconda](https://www.anaconda.com/download)

### 2. Download Visual Studio C++ Redistributables:
   - Link: [Visual Studio C++ Redistributables](https://aka.ms/vs/17/release/vc_redist.x64.exe)

### 3. TensorFlow-GPU Installation:
   - Visit [TensorFlow Installation Guide](https://www.tensorflow.org/install/source_windows) and go to the TensorFlow-GPU section.
   - Check for the latest versions and requirements.

### 4. Anaconda Environment Setup:

   a. Open Anaconda prompt as administrator.
   
   b. Create a new environment:
      ```
      conda create -n tf_gpu python==3.9
      ```

   c. Activate the environment:
      ```
      conda activate tf_gpu
      ```

### 5. Install CUDA and cuDNN:

   a. Check the required versions from the TensorFlow-GPU section (Step 3).

   b. Install CUDA and cuDNN using conda:
      ```
      conda install cudatoolkit=11.2 cudnn=8.1 -c=conda-forge
      ```

### 6. Install TensorFlow-GPU:

   Install the latest TensorFlow-GPU version (replace 2.10.0 with the latest version):
```
pip install --upgrade tensorflow-gpu==2.10.0
```
### Verification:
1. Open Python: via cmd/ powershell.
```python```

2. Import TensorFlow:
```import tensorflow as tf```

3. Check GPU availability:
```print(tf.test.is_gpu_available())```

## Shortcuts:

- To stop a current process: `Ctrl+C`



###

**Comment by SunilKumarPradhan** [comment]
@BaseMax I hope this clears out the issue . The issue above was mainly due to version conflict.

**Comment by Ericva** [comment]
> # Setting up TensorFlow with GPU on Windows - Step-by-Step Guide
> ## Document Formatting for Notepad:
> To enhance readability, follow these steps in Notepad:
> 
> 1. Navigate to [FILE EDIT FORMAT VIEW HELP] above tabs.
> 2. Go to `FORMAT` and select `Word Wrap`.
> 
> ## Installation Steps:
> ### 1. Download Anaconda:
> * Link: [Anaconda](https://www.anaconda.com/download)
> 
> ### 2. Download Visual Studio C++ Redistributables:
> * Link: [Visual Studio C++ Redistributables](https://aka.ms/vs/17/release/vc_redist.x64.exe)
> 
> ### 3. TensorFlow-GPU Installation:
> * Visit [TensorFlow Installation Guide](https://www.tensorflow.org/install/source_windows) and go to the TensorFlow-GPU section.
> * Check for the latest versions and requirements.
> 
> ### 4. Anaconda Environment Setup:
> a. Open Anaconda prompt as administrator.
> 
> b. Create a new environment: `conda create -n tf_gpu python==3.9`
> 
> c. Activate the environment: `conda activate tf_gpu`
> 
> ### 5. Install CUDA and cuDNN:
> a. Check the required versions from the TensorFlow-GPU section (Step 3).
> 
> b. Install CUDA and cuDNN using conda: `conda install cudatoolkit=11.2 cudnn=8.1 -c=conda-forge`
> 
> ### 6. Install TensorFlow-GPU:
> Install the latest TensorFlow-GPU version (replace 2.10.0 with the latest version):
> 
> ```
> pip install --upgrade tensorflow-gpu==2.10.0
> ```
> 
> ### Verification:
> 1. Open Python: via cmd/ powershell.
>    `python`
> 2. Import TensorFlow:
>    `import tensorflow as tf`
> 3. Check GPU availability:
>    `print(tf.test.is_gpu_available())`
> 
> ## Shortcuts:
> * To stop a current process: `Ctrl+C`

thanks a lot~  It helps me solov the problem~
