### ISSUE TITLE
Unable to build TensorFlow without TensorRT

### ISSUE THREAD

**Issue by torotoki** [tensorflow/tensorflow#62689]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

nightly

### Custom code

Yes

### OS platform and distribution

Linux Ubuntu 22.04

### Python version

3.11

### Bazel version

6.1.0

### GCC/compiler version

clang-16

### CUDA/cuDNN version

CUDA 12.0.1/cuDNN 8.8

### GPU model and memory

GTX 1060

### Current behavior?

I followed the [tutorial](https://www.tensorflow.org/install/source) to build the TensorFlow nightly source code, but it aborted and asserted an error related to TensorRT, even though I had configured it to build TensorFlow *without* TensorRT.

Please see the attached Dockerfile for reproduction steps.
Then, I executed:
```
>>> cd tensorflow
>>> ./configure
You have bazel 6.1.0 installed.
Please specify the location of python. [Default is /usr/bin/python3]:


Found possible Python library paths:
  /usr/lib/python3/dist-packages
  /usr/local/lib/python3.10/dist-packages
Please input the desired Python library path to use.  Default is [/usr/lib/python3/dist-packages]

Do you wish to build TensorFlow with ROCm support? [y/N]: N
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Do you wish to build TensorFlow with TensorRT support? [y/N]: N
No TensorRT support will be enabled for TensorFlow.

Found CUDA 12.0 in:
    /usr/local/cuda-12.0/targets/x86_64-linux/lib
    /usr/local/cuda-12.0/targets/x86_64-linux/include
Found cuDNN 8 in:
    /usr/lib/x86_64-linux-gnu
    /usr/include


Please specify a list of comma-separated CUDA compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus. Each capability can be specified as "x.y" or "compute_xy" to include both virtual and binary GPU code, or as "sm_xy" to only include the binary code.
Please note that each additional compute capability significantly increases your build time and binary size, and that TensorFlow only supports compute capabilities >= 3.5 [Default is: 3.5,7.0]:


Do you want to use clang as CUDA compiler? [Y/n]: Y
Clang will be used as CUDA compiler.

Please specify clang path that to be used as host compiler. [Default is /usr/lib/llvm-16/bin/clang]:


You have Clang 16.0.6 installed.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -Wno-sign-compare]:


Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]:
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=mkl_aarch64    # Build with oneDNN and Compute Library for the Arm Architecture (ACL).
        --config=monolithic     # Config for mostly static monolithic build.
        --config=numa           # Build with NUMA support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
        --config=v1             # Build with TensorFlow 1 API instead of TF 2 API.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=nogcp          # Disable GCP support.
        --config=nonccl         # Disable NVIDIA NCCL support.
Configuration finished
```
```
>>> bazel build --config=dbg //tensorflow/tools/pip_package:build_pip_package
ERROR: /tensorflow/WORKSPACE:84:14: fetching tensorrt_configure rule //external:local_config_tensorrt: Traceback (most recent call last):
        File "/tensorflow/third_party/tensorrt/tensorrt_configure.bzl", line 300, column 38, in _tensorrt_configure_impl
                _create_local_tensorrt_repository(repository_ctx)
        File "/tensorflow/third_party/tensorrt/tensorrt_configure.bzl", line 159, column 30, in _create_local_tensorrt_repository
                config = find_cuda_config(repository_ctx, ["cuda", "tensorrt"])
        File "/tensorflow/third_party/gpus/cuda_configure.bzl", line 652, column 26, in find_cuda_config
                exec_result = execute(repository_ctx, [python_bin, repository_ctx.attr._find_cuda_config] + cuda_libraries)
        File "/tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
Could not find any NvInferVersion.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
        'local/cuda/extras/CUPTI/include'
        'targets/x86_64-linux/include'
of:
        '/lib'
        '/lib32'
        '/usr'
        '/usr/lib/x86_64-linux-gnu'
        '/usr/local/cuda'
        '/usr/local/cuda/targets/x86_64-linux/lib'
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': no such package '@local_config_tensorrt//': Repository command failed
Could not find any NvInferVersion.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
        'local/cuda/extras/CUPTI/include'
        'targets/x86_64-linux/include'
of:
        '/lib'
        '/lib32'
        '/usr'
        '/usr/lib/x86_64-linux-gnu'
        '/usr/local/cuda'
        '/usr/local/cuda/targets/x86_64-linux/lib'
WARNING: Target pattern parsing failed.
ERROR: no such package '@local_config_tensorrt//': Repository command failed
Could not find any NvInferVersion.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
        'local/cuda/extras/CUPTI/include'
        'targets/x86_64-linux/include'
of:
        '/lib'
        '/lib32'
        '/usr'
        '/usr/lib/x86_64-linux-gnu'
        '/usr/local/cuda'
        '/usr/local/cuda/targets/x86_64-linux/lib'
INFO: Elapsed time: 0.171s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package
```

In fact, the `NvInferVersion.h` file does not exist, but to my knowledge, `NvInferVersion.h` is supposed to be a header file for TensorRT. 

### Standalone code to reproduce the issue

See my Dockerfile that I reproduced the error on this:
https://gist.github.com/torotoki/8f88a4dd932c882018ccc3f38aab2ae7

**Comment by sushreebarsa** [comment]
@torotoki 
During the configuration stage, explicitly disable TensorRT using the following command:

Bash
```
./configure  --no_tensorrt
```
Please double-check the generated .config file to ensure TensorRT is indeed disabled.
Thank you!

**Comment by torotoki** [comment]
@sushreebarsa 
```
>>> ./configure --no_tensorrt
usage: configure.py [-h] [--workspace WORKSPACE]
configure.py: error: unrecognized arguments: --no_tensorrt
```

**Comment by TheophileH** [comment]
Hello!
Another way to build from source is to use TensorFlow v2.14 which seems more stable.

- check out another release branch
`git checkout r2.14`
-  Run the configuration script
`./configure`
- Use **nvcc** instead of Clang to compile cuda.
> Do you want to use Clang to build TensorFlow? [Y/n] **N**


Continue with the instructions as described [here](https://www.tensorflow.org/install/source#configure_the_build).

I hope this helps.

**Comment by shkarupa-alex** [comment]
Same issue with TF 2.16.1

**Comment by vidlb** [comment]
Same with TF 2.17.0, so I'm switching to 2.18rc

**Comment by zzwu29** [comment]
> Hello! Another way to build from source is to use python3.10 with TensorFlow v2.14 which seems more stable.
> 
> * check out another release branch
>   `git checkout r2.14`
> * Run the configuration script
>   `./configure`
> * Use **nvcc** instead of Clang to compile cuda.
> 
> > Do you want to use Clang to build TensorFlow? [Y/n] **N**
> 
> Continue with the instructions as described [here](https://www.tensorflow.org/install/source#configure_the_build).
> 
> I hope this helps.

Good Solution! Thanks a lot.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

In the latest tensorflow v2.18, TensorRT support is disabled in CUDA builds for code health improvement.
https://github.com/tensorflow/tensorflow/releases

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
