### ISSUE TITLE
tflite_runtime ImportError: /lib64/libm.so.6: version `GLIBC_2.27' not found

### ISSUE THREAD

**Issue by ydy1127** [tensorflow/tensorflow#62755]
Dear TensorFlow Team,
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS Linux 7 (Core)
- Python version: Python 3.7.16
- TensorFlow installation (pip package or built from source): tflite-runtime-2.11.0

### 2. Code and issue

tflite-runtime is installed successfully, but an error occurs when the tflite-runtime package is imported.  Some of the solutions we have found require root permission, how to solve the problem without root permission

```
python3 -m pip install tflite-runtime
>>> import tflite_runtime.interpreter as tflite
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yuandy/anaconda3/envs/tflite/lib/python3.7/site-packages/tflite_runtime/interpreter.py", line 33, in <module>
    from tflite_runtime import _pywrap_tensorflow_interpreter_wrapper as _interpreter_wrapper
ImportError: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/yuandy/anaconda3/envs/tflite/lib/python3.7/site-packages/tflite_runtime/_pywrap_tensorflow_interpreter_wrapper.so)

```
It would be great if you could let me know.

Best,
Danyang Yuan

**Comment by LakshmiKalaKadali** [comment]
Hi @ydy1127,

I reproduced the code  with tensorflow 2.15 latest version. It works fine and there is no import error.  Please upgrade to the  latest tensorflow version. If the problem persists, please let us know.

Thank You

**Comment by ydy1127** [comment]
Hi LakshmiKalaKadali，

Based on the information you provided, I recreated the Conda environment with Python 3.10.12 and then installed tensorflow 2.15.0. The problem persists, as shown below.

````
Python 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2024-01-22 11:26:32.545016: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-01-22 11:26:32.547237: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-01-22 11:26:32.590044: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-01-22 11:26:32.590079: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-01-22 11:26:32.591447: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-01-22 11:26:32.599425: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-01-22 11:26:32.599712: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-01-22 11:26:33.217922: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
>>> import tflite_runtime.interpreter as tflite
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yuandy/anaconda3/envs/tensorflow/lib/python3.10/site-packages/tflite_runtime/interpreter.py", line 33, in <module>
    from tflite_runtime import _pywrap_tensorflow_interpreter_wrapper as _interpreter_wrapper
ImportError: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/yuandy/anaconda3/envs/tensorflow/lib/python3.10/site-packages/tflite_runtime/_pywrap_tensorflow_interpreter_wrapper.so)
````

From the error message, it seems that the system does not have a GPU and the GLIBC library version is too low.
Can you provide a version of the GLIBC library on your system?

Thank You,
Danyang Yuan

**Comment by LakshmiKalaKadali** [comment]
Hi @ydy1127,

Regarding the GLIBC_2.27 not found error: The  error is due to incompatibility between GLIBC version of TFLite and the version available on your system. First, know the  glibc version of your system. Refer this [link](https://iq.opengenus.org/find-glibc-version/) to know the  version. If it is a lower version, upgrade glibc version using the commands ```sudo apt-get update``` and ```sudo apt-get install libc6```. Then  run ``` import tflite_runtime.interpreter as tflite```. In my old post, i have used  glibc  2.35 version.

Upon observing the error log, if you want to use GPU acceleration, install necessary GPU drivers.

Thank You.
