### ISSUE TITLE
RuntimeError: Op type not registered 'CreateRangeEncoder' in binary running

### ISSUE THREAD

**Issue by ZH-1225** [tensorflow/tensorflow#62771]
### Issue type

Others

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tf2.14.0

### Custom code

Yes

### OS platform and distribution

windows x64

### Python version

3.9.13

### Current behavior?

I do not know what caused the Op type not registered 'CreateRangeEncoder'

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

# 加载 SavedModel
saved_model_path = "./bls2017"
loaded_model = tf.saved_model.load(saved_model_path)

# 创建 TFLite 转换器
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_path)

# 转换模型为 TensorFlow Lite 格式
tflite_model = converter.convert()

# 保存 TensorFlow Lite 模型
with open("converted_model.tflite", "wb") as f:
    f.write(tflite_model)
```

### Relevant log output

```shell
2024-01-10 10:33:25.218158: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE SSE2 SSE3 SSE4.1 SSE4.2 AVX AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "E:\Pycharm_File\Video_Fuse\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 3022, in op_def_for_type
    return self._op_def_cache[type]
KeyError: 'CreateRangeEncoder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Pycharm_File\Video_Fuse\学习tensorflow\savemodel_to_lite\init.py", line 5, in <module>
    loaded_model = tf.saved_model.load(saved_model_path)
  File "E:\Pycharm_File\Video_Fuse\venv\lib\site-packages\tensorflow\python\saved_model\load.py", line 900, in load
    result = load_partial(export_dir, None, tags, options)["root"]
  File "E:\Pycharm_File\Video_Fuse\venv\lib\site-packages\tensorflow\python\saved_model\load.py", line 1031, in load_partial
    loader = Loader(object_graph_proto, saved_model_proto, export_dir,
  File "E:\Pycharm_File\Video_Fuse\venv\lib\site-packages\tensorflow\python\saved_model\load.py", line 161, in __init__
    function_deserialization.load_function_def_library(
  File "E:\Pycharm_File\Video_Fuse\venv\lib\site-packages\tensorflow\python\saved_model\function_deserialization.py", line 456, in load_function_def_library
    func_graph = function_def_lib.function_def_to_graph(
  File "E:\Pycharm_File\Video_Fuse\venv\lib\site-packages\tensorflow\python\framework\function_def_to_graph.py", line 91, in function_def_to_graph
    graph_def, nested_to_flat_tensor_name = function_def_to_graph_def(
  File "E:\Pycharm_File\Video_Fuse\venv\lib\site-packages\tensorflow\python\framework\function_def_to_graph.py", line 330, in function_def_to_graph_def
    op_def = default_graph.op_def_for_type(node_def.op)  # pylint: disable=protected-access
  File "E:\Pycharm_File\Video_Fuse\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 3025, in op_def_for_type
    self._op_def_for_type(type)
RuntimeError: Op type not registered 'CreateRangeEncoder' in binary running on PC-20230214ZYNL. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib (e.g. `tf.contrib.resampler`), accessing should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

进程已结束,退出代码1
```

**Comment by tilakrayal** [comment]
@ZH-1225,
In the above mentioned you are trying to use the model `"./bls2017"`. Could you please share the dependencies to reproduce the issue in an effective way. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/aca383c518106cc72f3e1a2f42d969a2/untitled1652.ipynb). Thank you!

**Comment by ZH-1225** [comment]
> @ZH-1225， 上面提到你正在尝试使用该模型`"./bls2017"`。您能否分享依赖项以有效地重现该问题。[请在这里](https://colab.research.google.com/gist/tilakrayal/aca383c518106cc72f3e1a2f42d969a2/untitled1652.ipynb)找到它的要点。谢谢你！
I Add a line :
converter.target_spec.supported_ops = [
        tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS
]
solved the problem thank you!

**Comment by tilakrayal** [comment]
@ZH-1225,
Glad the issue was resolved. Could you please feel free to move this issue to the closed status. Thank you!
