### ISSUE TITLE
Cannot import name synthetic - when using add_arg_scope

### ISSUE THREAD

**Issue by PatWie** [tensorflow/tensorflow#6281]
### Environment info
Operating System:
Ubuntu 16.04
Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
````
/path/to/opt/cuda/toolkit_tensorflow/cuda/lib/libcudadevrt.a
/path/to/opt/cuda/toolkit_tensorflow/cuda/lib/libcudart.so -> libcudart.so.8.0
/path/to/opt/cuda/toolkit_tensorflow/cuda/lib/libcudart.so.8.0 -> libcudart.so.8.0.44
/path/to/opt/cuda/toolkit_tensorflow/cuda/lib/libcudart.so.8.0.44
/path/to/opt/cuda/toolkit_tensorflow/cuda/lib/libcudart_static.a
/path/to/opt/cuda/toolkit_tensorflow/cuda/lib/libcudnn.so -> libcudnn.so.5
/path/to/opt/cuda/toolkit_tensorflow/cuda/lib/libcudnn.so.5 -> libcudnn.so.5.1.5
/path/to/opt/cuda/toolkit_tensorflow/cuda/lib/libcudnn.so.5.1.3
/path/to/opt/cuda/toolkit_tensorflow/cuda/lib/libcudnn.so.5.1.5
/path/to/opt/cuda/toolkit_tensorflow/cuda/lib/libcudnn_static.a
````
If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
9c41d5f64efedf44d30e5cc21f900ea07097395c

2. The output of `bazel version`
````
Build label: 0.3.2-2016-10-18 (@8fd25d7)
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Oct 18 13:58:42 2016 (1476799122)
Build timestamp: 1476799122
Build timestamp as int: 1476799122
````

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
````python
import tensorflow as tf

@tf.contrib.framework.add_arg_scope
def my_func(*args, **kwargs):
    pass

````

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

````
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py", line 29, in <module>
    from tensorflow.contrib import factorization
  File "/home/user/.local/lib/python2.7/site-packages/tensorflow/contrib/factorization/__init__.py", line 24, in <module>
    from tensorflow.contrib.factorization.python.ops.gmm import *
  File "/home/user/.local/lib/python2.7/site-packages/tensorflow/contrib/factorization/python/ops/gmm.py", line 30, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/home/user/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/__init__.py", line 66, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/home/user/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/__init__.py", line 23, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/home/user/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 26, in <module>
    from tensorflow.contrib.learn.python.learn import datasets
  File "/home/user/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/__init__.py", line 29, in <module>
    from tensorflow.contrib.learn.python.learn.datasets import synthetic
ImportError: cannot import name synthetic
````

**Comment by andydavis1** [comment]
Closing as it looks like #6283 was committed.
