### ISSUE TITLE
TensorFlow Serving Broken ?

### ISSUE THREAD

**Issue by dangithubs** [tensorflow/tensorflow#6282]
I am running TensorFlow from branch r0.11 along with Bazel 0.3.2. I have managed to build TF and with the work arounds to several bugs get TensorBoard up and running. The last problem I am trying to overcome is TensorFlow Serving.

Currently when I try and run: bazel build tensorflow_serving/...

I get the following crash :

bazel build tensorflow_serving/...
.........
WARNING: /home/ubuntu/.cache/bazel/_bazel_ubuntu/7317d353d890cf5e09cb18f5cfc053f7/external/inception_model/WORKSPACE:1: Workspace name in /home/ubuntu/.cache/bazel/_bazel_ubuntu/7317d353d890cf5e09cb18f5cfc053f7/external/inception_model/WORKSPACE (@inception) does not match the name given in the repository's definition (@inception_model); this will cause a build error in future versions.
ERROR: /home/ubuntu/.cache/bazel/_bazel_ubuntu/7317d353d890cf5e09cb18f5cfc053f7/external/org_tensorflow/tensorflow/core/BUILD:1121:1: no such target '@org_tensorflow//tensorflow/tools/git:gen/spec.json': target 'gen/spec.json' not declared in package 'tensorflow/tools/git' defined by /home/ubuntu/.cache/bazel/_bazel_ubuntu/7317d353d890cf5e09cb18f5cfc053f7/external/org_tensorflow/tensorflow/tools/git/BUILD and referenced by '@org_tensorflow//tensorflow/core:version_info_gen'.
ERROR: /home/ubuntu/.cache/bazel/_bazel_ubuntu/7317d353d890cf5e09cb18f5cfc053f7/external/org_tensorflow/tensorflow/core/BUILD:1121:1: no such target '@org_tensorflow//tensorflow/tools/git:gen/head': target 'gen/head' not declared in package 'tensorflow/tools/git' defined by /home/ubuntu/.cache/bazel/_bazel_ubuntu/7317d353d890cf5e09cb18f5cfc053f7/external/org_tensorflow/tensorflow/tools/git/BUILD and referenced by '@org_tensorflow//tensorflow/core:version_info_gen'.
ERROR: /home/ubuntu/.cache/bazel/_bazel_ubuntu/7317d353d890cf5e09cb18f5cfc053f7/external/org_tensorflow/tensorflow/core/BUILD:1121:1: no such target '@org_tensorflow//tensorflow/tools/git:gen/branch_ref': target 'gen/branch_ref' not declared in package 'tensorflow/tools/git' defined by /home/ubuntu/.cache/bazel/_bazel_ubuntu/7317d353d890cf5e09cb18f5cfc053f7/external/org_tensorflow/tensorflow/tools/git/BUILD and referenced by '@org_tensorflow//tensorflow/core:version_info_gen'.
ERROR: Analysis of target '//tensorflow_serving/model_servers:server_core' failed; build aborted.
INFO: Elapsed time: 2.908s

Is this a known problem ?

If I run the following as I am using GPU processing (working on AWS) :

bazel build -c opt --config=cuda tensorflow_serving/...

I get this error:

bazel build -c opt --config=cuda tensorflow_serving/...
ERROR: /home/ubuntu/.cache/bazel/_bazel_ubuntu/7317d353d890cf5e09cb18f5cfc053f7/external/local_config_cuda/crosstool/BUILD:4:1: Traceback (most recent call last):
	File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/7317d353d890cf5e09cb18f5cfc053f7/external/local_config_cuda/crosstool/BUILD", line 4
		error_gpu_disabled()
	File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/7317d353d890cf5e09cb18f5cfc053f7/external/local_config_cuda/crosstool/error_gpu_disabled.bzl", line 3, in error_gpu_disabled
		fail("ERROR: Building with --config=c...")
ERROR: Building with --config=cuda but TensorFlow is not configured to build with GPU support. Please re-run ./configure and enter 'Y' at the prompt to build with GPU support.
ERROR: no such target '@local_config_cuda//crosstool:toolchain': target 'toolchain' not declared in package 'crosstool' defined by /home/ubuntu/.cache/bazel/_bazel_ubuntu/7317d353d890cf5e09cb18f5cfc053f7/external/local_config_cuda/crosstool/BUILD.
INFO: Elapsed time: 0.275s

Both these issues seem to be related to the cache. The second message is odd as GPU processing is enabled and is being used when I run TensorFlow.  Is there a safe way of removing the cache and rebuilding just the bits needed for TensorFlow Serving ? Do you have to install TensorFlow Serving before you install TensorFlow ? I don't want to rebuild everything if I can help it ?

**Comment by dangithubs** [comment]
Guys you can close this one. The above occurs when you have TensorFlow installed and then you try and install TensorFlow Serving. I overcome the above by doing a clean build of TensorFlow Serving without having TensorFlow installed and allowing it to pull its own version of TensorFlow from the Git repo.

When I have done subsequent builds, following that approach has resulted in no errors.
