### ISSUE TITLE
Permission denied: '/usr/local/lib/python2.7/dist-packages/protobuf-3.1.0.post1-py2.7.egg/EGG-INFO/namespace_packages.txt'

### ISSUE THREAD

**Issue by Dav-Jay** [tensorflow/tensorflow#6284]
Operating System: **Ubuntu 14.04**
Tensorflow version: **0.12.0rc1**

hi all, I have successfully installed tensorflow in my computer, but I encountered the following problem when `import tensorflow` in python 2.7 environment: 

```
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so.4 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so.7.0 locally
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tensorflow/_python_build/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/tensorflow/_python_build/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/tensorflow/_python_build/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/usr/local/lib/python2.7/dist-packages/protobuf-3.1.0.post1-py2.7.egg/google/__init__.py", line 2, in <module>
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2760, in <module>
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 738, in subscribe
    callback(dist)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2760, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2314, in activate
    for pkg in self._get_metadata('namespace_packages.txt'):
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2305, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1369, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1361, in get_metadata
    return self._get(self._fn(self.egg_info,name))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1470, in _get
    stream = open(path, 'rb')
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/protobuf-3.1.0.post1-py2.7.egg/EGG-INFO/namespace_packages.txt'
```

By searching online, I can solve this error by 
```
sudo chmod o+r /usr/local/lib/python2.7/dist-packages/protobuf-3.1.0.post1-py2.7.egg/EGG-INFO/namespace_packages.txt
```
However, does anyone has other solutions, since I **DO NOT** want use `sudo` frequently? 

Btw, can anyone solve another confusion of mine? I installed tensorflow from source according to the tensorflow's [tutorial.](https://www.tensorflow.org/versions/r0.12/get_started/os_setup.html#installing-from-sources) But I don't quite understand the differences of the following commands used in my installation:
```
sudo pip install /tmp/tensorflow_pkg/tensorflow-0.12.0rc1-py2-none-any.whl
```
and
```
python setup.py develop
```

It seems to me that these two commands all install tensorflow in my system and they all need sudo privilege to work. I also see from tensorflow installation guide that the second command is for development. Could anyone explain in more detail about the differences and purposes of them?

Thanks in advance!

**Comment by martinwicke** [comment]
You should only have to run the `sudo chmod...` command once.

The first of these commands installs tensorflow from a binary distribution, the second install symbolic links to a source version, so if you change the python during development this is immediately reflected in the installed version, which is very convenient.
