### ISSUE TITLE
load_model() cannot load model from previous version

### ISSUE THREAD

**Issue by eneskelestemur** [tensorflow/tensorflow#63021]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.14 and tf 2.15

### Custom code

Yes

### Current behavior?

Hello, 

I was trying to load a model I previously saved with tf 2.14, and got the displayed error. I realized that the model was saved with tf 2.14, and the environment I was trying to load the model in was tf 2.15. I'm not sure if this is an expected behavior, but it seemed odd since the version difference wasn't that big.

### Standalone code to reproduce the issue

```shell
# previously saved model with tf 2.14
# import tensorflow as tf
# from tensorflow import keras
# import numpy as np

# # print version
# print(tf.__version__)

# # random data
# data = np.random.random((100, 10))
# labels = np.random.random((100, ))

# # simple model
# normalizer = keras.layers.Normalization()
# normalizer.adapt(data)
# model = keras.Sequential()
# model.add(normalizer)
# model.add(keras.layers.Dense(10))
# model.add(keras.layers.Dense(1))
# model.compile(loss='mean_squared_error', optimizer='adam')
# model.fit(data, labels, epochs=10, verbose=2)
# model.save('test.keras')


### loading with tf 2.15 ###
import tensorflow as tf
from tensorflow import keras

# print version
print(tf.__version__)

# load model
model = keras.models.load_model('test.keras')
```

### Relevant log output

```shell
2.15.0

Traceback (most recent call last):
  File "/work/users/e/n/enesk/phakinpro/test_load.py", line 8, in <module>
    model = keras.models.load_model('test.keras')
  File "/nas/longleaf/home/enesk/miniforge3/envs/tf/lib/python3.9/site-packages/keras/src/saving/saving_api.py", line 254, in load_model
    return saving_lib.load_model(
  File "/nas/longleaf/home/enesk/miniforge3/envs/tf/lib/python3.9/site-packages/keras/src/saving/saving_lib.py", line 281, in load_model
    raise e
  File "/nas/longleaf/home/enesk/miniforge3/envs/tf/lib/python3.9/site-packages/keras/src/saving/saving_lib.py", line 246, in load_model
    model = deserialize_keras_object(
  File "/nas/longleaf/home/enesk/miniforge3/envs/tf/lib/python3.9/site-packages/keras/src/saving/serialization_lib.py", line 728, in deserialize_keras_object
    instance = cls.from_config(inner_config)
  File "/nas/longleaf/home/enesk/miniforge3/envs/tf/lib/python3.9/site-packages/keras/src/engine/sequential.py", line 471, in from_config
    model.add(layer)
  File "/nas/longleaf/home/enesk/miniforge3/envs/tf/lib/python3.9/site-packages/tensorflow/python/trackable/base.py", line 204, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/nas/longleaf/home/enesk/miniforge3/envs/tf/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/nas/longleaf/home/enesk/miniforge3/envs/tf/lib/python3.9/site-packages/keras/src/layers/preprocessing/normalization.py", line 188, in build
    raise ValueError(
ValueError: All `axis` values to be kept must have known shape. Got axis: (-1,), input shape: [None, None], with unknown axis at index: 1
```

**Comment by Venkat6871** [comment]
Hi **@eneskelestemur** ,
Sorry for late reply, I tried to run your code on Colab using TF v2.14 and 2.15. Please find the [gist](https://colab.sandbox.google.com/gist/Venkat6871/71d4dbeea1ad6d3e712ce4554d783763/63021_2-14-v-2-15.ipynb) here for reference. 
Thanks you!

**Comment by Venkat6871** [comment]
Hi @eneskelestemur ,

I tried to run your code on colab using TF v2.16.1 with nightly now it is working fine. Could you please check with recent version. Here i providing [gist](https://colab.sandbox.google.com/gist/Venkat6871/37e51a98566ab8faefa4ddd3d9397d02/63021_2-16-1-nightly.ipynb) for your reference.

Thank you
