### ISSUE TITLE
Unable to  build the pip package after building the package builder

### ISSUE THREAD

**Issue by sumanth1989** [tensorflow/tensorflow#63302]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.15

### Custom code

No

### OS platform and distribution

Ubuntu 20.04

### Python version

3.10

### Bazel version

6.1.0

### GCC/compiler version

clang 16

### CUDA/cuDNN version

8.9

### GPU model and memory

NVIDIA A100-SXM4-80GB 

### Current behavior?

After running the bazel package builder i am trying to build the pip package when i see the following error. Also important to note that i had to supply the --output-name and --project-name flags (since they are mandatory). This is not reflected in the guide to build tf from source. I also dont understand what headers need to be supplied. I see a command line option to supply headers though for the whl build.

 Traceback (most recent call last):
  File "/home/administrator/tensorinstall/tensorflow/./bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow/tensorflow/tools/pip_package/build_pip_package.py", line 333, in <module>
    prepare_wheel_srcs(args.headers, args.srcs, args.xla_aot,
  File "/home/administrator/tensorinstall/tensorflow/./bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow/tensorflow/tools/pip_package/build_pip_package.py", line 175, in prepare_wheel_srcs
    prepare_headers(headers, os.path.join(srcs_dir, "tensorflow/include"))
  File "/home/administrator/tensorinstall/tensorflow/./bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow/tensorflow/tools/pip_package/build_pip_package.py", line 90, in prepare_headers
    for file in headers:
TypeError: 'NoneType' object is not iterable

### Standalone code to reproduce the issue

```shell
bazel build //tensorflow/tools/pip_package:build_pip_package

./bazel-bin/tensorflow/tools/pip_package/build_pip_package --output-name /tmp/tensorflow_pkg --project-name tensor
```

### Relevant log output

```shell
sudo ./bazel-bin/tensorflow/tools/pip_package/build_pip_package --output-name /tmp/tensorflow_pkg --project-name tensor
Traceback (most recent call last):
  File "/home/administrator/tensorinstall/tensorflow/./bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow/tensorflow/tools/pip_package/build_pip_package.py", line 333, in <module>
    prepare_wheel_srcs(args.headers, args.srcs, args.xla_aot,
  File "/home/administrator/tensorinstall/tensorflow/./bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow/tensorflow/tools/pip_package/build_pip_package.py", line 175, in prepare_wheel_srcs
    prepare_headers(headers, os.path.join(srcs_dir, "tensorflow/include"))
  File "/home/administrator/tensorinstall/tensorflow/./bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow/tensorflow/tools/pip_package/build_pip_package.py", line 90, in prepare_headers
    for file in headers:
TypeError: 'NoneType' object is not iterable
```

**Comment by vladbelit** [comment]
Please see https://github.com/tensorflow/tensorflow/issues/63298

**Comment by sumanth1989** [comment]
@vladbelit , i ran into that issue  mentioned in #63298 previously. In order to fix it i editted the "/home/administrator/tensorinstall/tensorflow/tensorflow/tools/pip_package/BUILD" file. 
i changed the following lines after which the package built succesfully

py_binary(
    name = "build_pip_package", # changed from "build_pip_package_py"
    srcs = ["build_pip_package.py"],
    main = "build_pip_package.py",

**Comment by GuoHuanyu** [comment]
> @vladbelit , i ran into that issue mentioned in #63298 previously. In order to fix it i editted the "/home/administrator/tensorinstall/tensorflow/tensorflow/tools/pip_package/BUILD" file. i changed the following lines after which the package built succesfully
> 
> py_binary( name = "build_pip_package", # changed from "build_pip_package_py" srcs = ["build_pip_package.py"], main = "build_pip_package.py",

SAME error, thanks, package have built succesfully

**Comment by darus90** [comment]
> @vladbelit , i ran into that issue mentioned in #63298 previously. In order to fix it i editted the "/home/administrator/tensorinstall/tensorflow/tensorflow/tools/pip_package/BUILD" file. i changed the following lines after which the package built succesfully
> 
> py_binary( name = "build_pip_package", # changed from "build_pip_package_py" srcs = ["build_pip_package.py"], main = "build_pip_package.py",

bazel build --repo_env=TF_PYTHON_VERSION=3.10 //tensorflow/tools/pip_package:build_pip_package --repo_env=WHEEL_NAME=tensorflow-cuda-rt
.
.
.
INFO: Build completed successfully, 4 total actions
(cuda12-1) administrador@admin-pc:~/tensorflow$ ./bazel-bin/tensorflow/tools/pip_package/build_pip_package --output-name /SSD/tmp/.tmp/tensorflow_pkg_wheel
usage: build_pip_package.py [-h] --output-name OUTPUT_NAME --project-name PROJECT_NAME [--headers HEADERS] [--srcs SRCS] [--xla_aot XLA_AOT] [--version VERSION] [--collab COLLAB]
build_pip_package.py: error: the following arguments are required: --project-name
(cuda12-1) administrador@admin-pc:~/tensorflow$ ./bazel-bin/tensorflow/tools/pip_package/build_pip_package --output-name /SSD/tmp/.tmp/tensorflow_pkg_wheel --project-name tensorflow-cuda-rt
Traceback (most recent call last):
  File "/home/administrador/tensorflow/./bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow/tensorflow/tools/pip_package/build_pip_package.py", line 343, in <module>
    prepare_wheel_srcs(args.headers, args.srcs, args.xla_aot,
  File "/home/administrador/tensorflow/./bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow/tensorflow/tools/pip_package/build_pip_package.py", line 175, in prepare_wheel_srcs
    prepare_headers(headers, os.path.join(srcs_dir, "tensorflow/include"))
  File "/home/administrador/tensorflow/./bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow/tensorflow/tools/pip_package/build_pip_package.py", line 90, in prepare_headers
    for file in headers:
TypeError: 'NoneType' object is not iterable
(cuda12-1) administrador@admin-pc:~/tensorflow$

**Comment by tilakrayal** [comment]
@sumanth1989,
Apologies for the delay. Could you please try to install the latest tensorflow v2.17 and provide the update if you are facing the same issue in the current version. Thank you!
