### ISSUE TITLE
Tensorflow import error

### ISSUE THREAD

**Issue by athenax246** [tensorflow/tensorflow#63363]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.13.0

### Custom code

Yes

### OS platform and distribution

Win 11

### Python version

3.9.7

### Current behavior?

I intalled tensorflow, but it gives an error when I try to import it.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
```

### Relevant log output

```shell
runfile('X:/Nano-Photonics and Quantum Optics Lab!/ML Project/Tkinter learning/Tkinter Git - GitLab/Inverse_Design_Periodic_GUI_CustomModern.py', wdir='X:/Nano-Photonics and Quantum Optics Lab!/ML Project/Tkinter learning/Tkinter Git - GitLab')
Traceback (most recent call last):

  File "X:\Nano-Photonics and Quantum Optics Lab!\ML Project\Tkinter learning\Tkinter Git - GitLab\Inverse_Design_Periodic_GUI_CustomModern.py", line 20, in <module>
    import tensorflow as tf  #print(tf.__version__)

  File "C:\Users\athen\anaconda3\lib\site-packages\tensorflow\__init__.py", line 469, in <module>
    _keras._load()

  File "C:\Users\athen\anaconda3\lib\site-packages\tensorflow\python\util\lazy_loader.py", line 41, in _load
    module = importlib.import_module(self.__name__)

  File "C:\Users\athen\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

  File "C:\Users\athen\anaconda3\lib\site-packages\keras\__init__.py", line 20, in <module>
    from keras import distribute

  File "C:\Users\athen\anaconda3\lib\site-packages\keras\distribute\__init__.py", line 18, in <module>
    from keras.distribute import sidecar_evaluator

  File "C:\Users\athen\anaconda3\lib\site-packages\keras\distribute\sidecar_evaluator.py", line 22, in <module>
    from keras.optimizers.optimizer_experimental import (

  File "C:\Users\athen\anaconda3\lib\site-packages\keras\optimizers\__init__.py", line 25, in <module>
    from keras import backend

  File "C:\Users\athen\anaconda3\lib\site-packages\keras\backend\__init__.py", line 3, in <module>
    from keras.backend import experimental

  File "C:\Users\athen\anaconda3\lib\site-packages\keras\backend\experimental\__init__.py", line 3, in <module>
    from keras.src.backend import disable_tf_random_generator

  File "C:\Users\athen\anaconda3\lib\site-packages\keras\src\__init__.py", line 21, in <module>
    from keras.src import applications

  File "C:\Users\athen\anaconda3\lib\site-packages\keras\src\applications\__init__.py", line 18, in <module>
    from keras.src.applications.convnext import ConvNeXtBase

  File "C:\Users\athen\anaconda3\lib\site-packages\keras\src\applications\convnext.py", line 28, in <module>
    from keras.src import backend

  File "C:\Users\athen\anaconda3\lib\site-packages\keras\src\backend.py", line 35, in <module>
    from keras.src.engine import keras_tensor

  File "C:\Users\athen\anaconda3\lib\site-packages\keras\src\engine\keras_tensor.py", line 19, in <module>
    from keras.src.utils import object_identity

  File "C:\Users\athen\anaconda3\lib\site-packages\keras\src\utils\__init__.py", line 20, in <module>
    from keras.src.saving.serialization_lib import deserialize_keras_object

  File "C:\Users\athen\anaconda3\lib\site-packages\keras\src\saving\serialization_lib.py", line 28, in <module>
    from keras.src.saving.legacy.saved_model.utils import in_tf_saved_model_scope

  File "C:\Users\athen\anaconda3\lib\site-packages\keras\src\saving\legacy\saved_model\utils.py", line 30, in <module>
    from keras.src.utils.layer_utils import CallFunctionSpec

  File "C:\Users\athen\anaconda3\lib\site-packages\keras\src\utils\layer_utils.py", line 26, in <module>
    from keras.src import initializers

  File "C:\Users\athen\anaconda3\lib\site-packages\keras\src\initializers\__init__.py", line 23, in <module>
    from keras.src.initializers import initializers_v1

  File "C:\Users\athen\anaconda3\lib\site-packages\keras\src\initializers\initializers_v1.py", line 32, in <module>
    keras_export(v1=["keras.initializers.Zeros", "keras.initializers.zeros"])(

  File "C:\Users\athen\anaconda3\lib\site-packages\tensorflow\python\util\tf_export.py", line 348, in __call__
    self.set_attr(undecorated_func, api_names_attr, self._names)

  File "C:\Users\athen\anaconda3\lib\site-packages\tensorflow\python\util\tf_export.py", line 363, in set_attr
    raise SymbolAlreadyExposedError(

SymbolAlreadyExposedError: Symbol Zeros is already exposed as ().
```

**Comment by vedchaudhari** [comment]
if you have a function or variable named Zeros in your code and you also import tensorflow, which also defines a symbol named Zeros, it can lead to this conflict.

**Comment by tilakrayal** [comment]
@athenax246,
Could you please provide the steps you followed to install the tensorflow on the Windows machine. With the error I assume that the tensorflow was not properly installed and also while installation the compatible tested build configurations have to follow for the smooth installation.
https://www.tensorflow.org/install/source_windows

Thank you!

**Comment by athenax246** [comment]
Thanks for you reply, I am using tensorflow in the Anaconda environment.
For installation, I used:
conda create --name tf_cpu
conda activate tf_cpu

**Comment by tilakrayal** [comment]
@athenax246,
I tried to install the tensorflow v2.13 on Windows 11 using conda and it was installed without any issue/error and also I am able to import the tensorflow. Kindly find the screenshot for the reference.
![tf2 13](https://github.com/tensorflow/tensorflow/assets/81610181/ec17c15b-7c35-491a-8dd8-da0e3d55ae0f)
Thank you!

**Comment by athenax246** [comment]
Problem solved, thanks so much!

**Comment by tilakrayal** [comment]
@athenax246,
Glad the issue is resolved for you, Could you please feel free to move this to closed status. Thank you!
