### ISSUE TITLE
Can't develop TensorBoard under macOS

### ISSUE THREAD

**Issue by exialym** [tensorflow/tensorflow#6337]
I read [DEVELOPMENT.md](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorboard/DEVELOPMENT.md)
After npm run prepare finished, gulp come up with error:

> [23:42:32] Using gulpfile ~/Desktop/Going/tensorflow-master/tensorflow/tensorboard/gulpfile.js
(node:20770) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[23:42:32] Starting 'watch'...
[23:42:32] Finished 'watch' after 129 ms
[23:42:32] Starting 'first-compile'...
[23:42:41] Finished 'first-compile' after 9.16 s
[23:42:41] Starting 'server'...
[23:42:41] Finished 'server' after 17 ms
[23:42:41] Starting 'default'...
[23:42:41] Finished 'default' after 18 μs
[23:42:41] Webserver started at http://0.0.0.0:8000
2016-12-15 23:42 gulp[20770] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1022:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1282:11)

macOS 10.12.1
➜  tensorboard gulp -v
[23:44:58] CLI version 3.9.1
[23:44:58] Local version 3.9.1
➜  tensorboard node -v
v7.2.1
➜  tensorboard npm -v
3.10.10
➜  tensorboard bower -v
1.8.0

**Comment by wchargin** [comment]
Due to the great efforts of @jart, you no longer need gulp, bower, or any of their co-conspirators to develop or run TensorBoard! Perhaps try again using our new repository at https://github.com/tensorflow/tensorboard/blob/master/README.md?
