### ISSUE TITLE
Error Loading Model with Bidirectional GRU layers

### ISSUE THREAD

**Issue by kreouzisv** [tensorflow/tensorflow#63404]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

v2.15.0-2-g0b15fdfcb3f 2.15.0

### Custom code

Yes

### Current behavior?

model saving with the layers specified errors in loading ; unexpected since other architectures are supported for saving .keras models with effective loading afterwards with current tf version and keras > 3.0.0

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Bidirectional, GRU, Dense, Input
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

# Data Pre omitted

# Define the model
embedding_dim = 100
model = Sequential([
    Input(shape=(maxlen,)),
    Embedding(max_features, embedding_dim),
    Bidirectional(GRU(64, return_sequences=True)),
    Bidirectional(GRU(64)),
    Dense(3, activation='softmax')  # Adjusted for 3 categories
])

# Compile the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',  # Adjusted for multi-class classification
              metrics=['accuracy'])

# Model summary
model.summary()

# Train the model
model.fit(train_x, train_y,
                    batch_size=100,
                    epochs=10,
                    validation_data=(val_x, val_y))


# Save the model in the native Keras format
model.save('my_model.keras')

# Load the model
loaded_model = tf.keras.models.load_model('my_model.keras')
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/data/host-category-classification/data/databases/t.py", line 101, in <module>
    loaded_model = tf.keras.models.load_model('my_model.keras')
  File "/ENTER/envs/tf-gpu/lib/python3.10/site-packages/keras/src/saving/saving_api.py", line 176, in load_model
    return saving_lib.load_model(
  File "/ENTER/envs/tf-gpu/lib/python3.10/site-packages/keras/src/saving/saving_lib.py", line 192, in load_model
    _raise_loading_failure(error_msgs)
  File "/ENTER/envs/tf-gpu/lib/python3.10/site-packages/keras/src/saving/saving_lib.py", line 273, in _raise_loading_failure
    raise ValueError(msg)
ValueError: A total of 2 objects could not be loaded. Example error message for object <GRUCell name=gru_cell, built=True>:

Layer 'gru_cell' expected 3 variables, but received 0 variables during loading. Expected: ['kernel', 'recurrent_kernel', 'bias']
```

**Comment by tilakrayal** [comment]
@kreouzisv,
I ran the code and face a different error, Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/508d5841c05beb7031238a44dae82f07/untitled1755.ipynb) and share all dependencies to replicate the issue or share a colab gist with the reported error. Thank you!
