### ISSUE TITLE
Error in einsum with unspecified dimensions

### ISSUE THREAD

**Issue by noammor** [tensorflow/tensorflow#6384]
Code:

    import tensorflow as tf
    
    x = tf.placeholder(dtype=tf.int32)
    
    A = tf.random_normal([13, x, 512])
    B = tf.random_normal([512, 3])
    C = tf.einsum('ijk,kl->ijl', A, B)
    
    with tf.Session() as sess:
        print(sess.run(C, {x: 7}))

Output:

    Traceback (most recent call last):
      File "/home/noam/code/test/test_einsum.py", line 7, in <module>
        C = tf.einsum('ijk,kl->ijl', A, B)
      File "/home/noam/miniconda3/envs/ml/lib/python3.5/site-packages/tensorflow/python/ops/special_math_ops.py", line 212, in einsum
        axes_to_sum)
      File "/home/noam/miniconda3/envs/ml/lib/python3.5/site-packages/tensorflow/python/ops/special_math_ops.py", line 341, in _einsum_reduction
        product = _reshape_if_necessary(product, uncompacted_shape)
      File "/home/noam/miniconda3/envs/ml/lib/python3.5/site-packages/tensorflow/python/ops/special_math_ops.py", line 366, in _reshape_if_necessary
        return array_ops.reshape(tensor, new_shape)
      File "/home/noam/miniconda3/envs/ml/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2448, in reshape
        name=name)
      File "/home/noam/miniconda3/envs/ml/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 493, in apply_op
        raise err
      File "/home/noam/miniconda3/envs/ml/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 490, in apply_op
        preferred_dtype=default_dtype)
      File "/home/noam/miniconda3/envs/ml/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 669, in convert_to_tensor
        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
      File "/home/noam/miniconda3/envs/ml/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
        return constant(v, dtype=dtype, name=name)
      File "/home/noam/miniconda3/envs/ml/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
        tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
      File "/home/noam/miniconda3/envs/ml/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 441, in make_tensor_proto
        tensor_proto.string_val.extend([compat.as_bytes(x) for x in proto_values])
      File "/home/noam/miniconda3/envs/ml/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 441, in <listcomp>
        tensor_proto.string_val.extend([compat.as_bytes(x) for x in proto_values])
      File "/home/noam/miniconda3/envs/ml/lib/python3.5/site-packages/tensorflow/python/util/compat.py", line 65, in as_bytes
        (bytes_or_text,))
    TypeError: Expected binary or unicode string, got 13

Using Tensorflow version 0.12.0-rc0, also tested and fails the same way on 0.12.0-rc1.

**Comment by asrivat1** [comment]
Having the same issue. Does anyone know of a workaround until this gets fixed?

**Comment by j88k** [comment]
I'm having the same issuse.

@asrivat1: I guess you've doing something like multiplication of each element of the batch of shape [B,I,J] with a matrix of shape [J,K]. In that case you could just reshape the batch to [B*I,J] and do the ordinary tf.matmul to obtain the result of shape [B*I,K], and then reshape this to [B,I,K]. To do the reshaping you can determine the tensor shapes with tf.shape.

**Comment by aselle** [comment]
This appears to work for me on python2.7 just fine. It appears you are using python3. Perhaps try forcing the string to be bytes and/or unicode. Are you all using Python 3?

**Comment by asrivat1** [comment]
I'm in 2.7. @aselle are you on 0.12.0-rc1? I found two workarounds. The first is to pad out the shape of the tensors to some fixed size using 0s via `tf.pad`, and this fixes the `tf.einsum` bug. The other solution is what @j88k suggested, and it's about 80% faster for my program. Also worth noting that for joining on multiple dimensions, `tf.batch_matmul` works wonders. The only disadvantage is that according to `Timeline` I'm now spending as much time transposing and reshaping my tensors as I am actually multiplying them.

**Comment by asrivat1** [comment]
Also worth noting I'm using Cython and Anaconda. It's possible that's part of the problem.

**Comment by rsethur** [comment]
+1
I'm having the same error using einsum where one of the dims is unknown.
It will be great to have this fixed.

**Comment by noammor** [comment]
@aselle - Tested on 2.7, fails the same way:

	Traceback (most recent call last):
	  File "/tmp/test.py", line 7, in <module>
		C = tf.einsum('ijk,kl->ijl', A, B)
	  File "/home/noam/miniconda3/envs/2.7test/lib/python2.7/site-packages/tensorflow/python/ops/special_math_ops.py", line 212, in einsum
		axes_to_sum)
	  File "/home/noam/miniconda3/envs/2.7test/lib/python2.7/site-packages/tensorflow/python/ops/special_math_ops.py", line 341, in _einsum_reduction
		product = _reshape_if_necessary(product, uncompacted_shape)
	  File "/home/noam/miniconda3/envs/2.7test/lib/python2.7/site-packages/tensorflow/python/ops/special_math_ops.py", line 366, in _reshape_if_necessary
		return array_ops.reshape(tensor, new_shape)
	  File "/home/noam/miniconda3/envs/2.7test/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2448, in reshape
		name=name)
	  File "/home/noam/miniconda3/envs/2.7test/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 493, in apply_op
		raise err
	TypeError: Expected binary or unicode string, got 13


Tensorflow 0.12.1, installed from `pip`. I created a fresh empty anaconda environment (`conda create -n 2.7test python=2.7`), issued `pip install tensorflow` and ran the code in the original bug report.

**Comment by michaelisard** [comment]
Could you try building master from source? A [fix](https://github.com/tensorflow/tensorflow/commit/30d2a2235a66e158757b13b6dd0bab7bf5e60492) went in  that isn't in r0.12 that sounds as if it might address the issue, at least from the title.

**Comment by noammor** [comment]
@michaelisard I didn't build from source, but I did add the line:

    new_shape = tuple(-1 if x is None else x for x in new_shape)

to `tensorflow/python/ops/special_math_ops.py` in 0.12.1 manually, and it does seem to fix the issue. I probably won't have time to build from source in the upcoming week.

**Comment by michaelisard** [comment]
OK I will close for now but please reopen if the problem doesn't go away with the new code.

**Comment by asrivat1** [comment]
Just built from source and can confirm that this is now working. Thanks!
