### ISSUE TITLE
Mac: OSError: [Errno 1] Operation not permitted: '/tmp/pip-XcfgD6-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'

### ISSUE THREAD

**Issue by tiansiyuan** [tensorflow/tensorflow#64]

**Comment by tiansiyuan** [comment]
Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/req/req_set.py", line 640, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/req/req_install.py", line 716, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/req/req_uninstall.py", line 125, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/utils/__init__.py", line 315, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-XcfgD6-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'

**Comment by mrry** [comment]
I'm not sure exactly what command you're running, but you'll probably need administrator privileges to uninstall from that directory. Try running the same command again prefixed by `sudo`.

**Comment by vrv** [comment]
Also: see https://github.com/tensorflow/tensorflow/issues/11 for common OS X installation issues.

**Comment by tiansiyuan** [comment]
sudo -H pip install https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl

**Comment by tiansiyuan** [comment]
it relates to uninstalling six 1.4.1

**Comment by tiansiyuan** [comment]
I install python via brew and now it works.

So we can say that it does not work with the default python on MacOS 10.11.1 (15B42)

**Comment by spk921** [comment]
I got this error following 

Exception:
Traceback (most recent call last):
  File "/Users/sangpil_kim/tensorflow/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/Users/sangpil_kim/tensorflow/lib/python2.7/site-packages/pip/commands/install.py", line 305, in run
    wb.build(autobuilding=True)
  File "/Users/sangpil_kim/tensorflow/lib/python2.7/site-packages/pip/wheel.py", line 705, in build
    self.requirement_set.prepare_files(self.finder)
  File "/Users/sangpil_kim/tensorflow/lib/python2.7/site-packages/pip/req/req_set.py", line 334, in prepare_files
    functools.partial(self._prepare_file, finder))
  File "/Users/sangpil_kim/tensorflow/lib/python2.7/site-packages/pip/req/req_set.py", line 321, in _walk_req_to_install
    more_reqs = handler(req_to_install)
  File "/Users/sangpil_kim/tensorflow/lib/python2.7/site-packages/pip/req/req_set.py", line 491, in _prepare_file
    session=self.session)
  File "/Users/sangpil_kim/tensorflow/lib/python2.7/site-packages/pip/download.py", line 825, in unpack_url
    session,
  File "/Users/sangpil_kim/tensorflow/lib/python2.7/site-packages/pip/download.py", line 673, in unpack_http_url
    from_path, content_type = _download_http_url(link, session, temp_dir)
  File "/Users/sangpil_kim/tensorflow/lib/python2.7/site-packages/pip/download.py", line 857, in _download_http_url
    stream=True,
  File "/Users/sangpil_kim/tensorflow/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/Users/sangpil_kim/tensorflow/lib/python2.7/site-packages/pip/download.py", line 373, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/Users/sangpil_kim/tensorflow/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/sangpil_kim/tensorflow/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Users/sangpil_kim/tensorflow/lib/python2.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/Users/sangpil_kim/tensorflow/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)


However, I solved problem by downloading .whl file manually ( https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl ) and run $pip install tensorflow-0.5.0-py2-none-any.whl  

I don't know why but it worked

**Comment by jctobin** [comment]
It worked because there have been issues with openssl, python2.7.10, and homebrew. By downloading it manually you avoided the Requests part that is currently problematic between between the three

**Comment by javierfdr** [comment]
Actually entering the url manually you can see there is no SSL certificate enabled for the site. 
It works if you do 

```
pip install http://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl 
```

(this is changing https by http).

**Comment by vrv** [comment]
Closing for now as there seems to be some resolution here (though using an esoteric solution).

**Comment by yoni** [comment]
Still getting this issue with both 0.5 and 0.6 versions of tensorflow. I'm using a `virtualenv` setup. Oddly, I get the error within `ipython` sessions, but don't get the error when running `python`.

**Comment by lvguanming** [comment]
the best way is use `virtualenv` , not use python env of system default. ［Just walk on by］

**Comment by ateixeiramunoz** [comment]
I finally did it like this, when reading [this link](https://github.com/donnemartin/haxor-news/issues/54)

`sudo -H pip install https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl --upgrade --ignore-installed`

**Comment by whitebread** [comment]
Solved it via @ateixeiramunoz 's comment

**Comment by AIROBOTAI** [comment]
@ateixeiramunoz 's answer worked. ```--upgrade --ignore-installed``` is the key.

**Comment by CrashRain** [comment]
@ateixeiramunoz 's answer works perfectly

**Comment by saliksyed** [comment]
Thanks @ateixeiramunoz  -- worked for me as well.
