### ISSUE TITLE
Unable to run model builder test for Object Detection API

### ISSUE THREAD

**Issue by smtc7648** [tensorflow/tensorflow#64152]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

v2.16.1-0-g5bc9d26649c 2.16.1

### Custom code

No

### OS platform and distribution

Mac OS Sonoma 14.4

### Python version

3.10

### Current behavior?

While running the below script
python3 models/research/object_detection/builders/model_builder_tf2_test.py

I'm getting following error:
Traceback (most recent call last):
  File "/Users/smitparmar/Desktop/ML/custom-object-detection/models/research/object_detection/builders/model_builder_tf2_test.py", line 24, in <module>
    from object_detection.builders import model_builder
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/object_detection/builders/model_builder.py", line 26, in <module>
    from object_detection.builders import hyperparams_builder
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/object_detection/builders/hyperparams_builder.py", line 27, in <module>
    from object_detection.core import freezable_sync_batch_norm
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/object_detection/core/freezable_sync_batch_norm.py", line 20, in <module>
    class FreezableSyncBatchNorm(tf.keras.layers.experimental.SyncBatchNormalization
AttributeError: module 'keras._tf_keras.keras.layers' has no attribute 'experimental'

### Standalone code to reproduce the issue

```shell
https://drive.google.com/file/d/18z2bj-xRlXT2J6QvplLiYv2uoLei_1bX/view?usp=sharing
```

### Relevant log output

```shell
This output is from google colab and above one is from my local machine Apple MacBook Pro with M1 Pro. (Tensowflow Metal is also installed)

2024-03-21 11:07:15.432006: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-03-21 11:07:16.927430: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/models/research/object_detection/builders/model_builder_tf2_test.py", line 24, in <module>
    from object_detection.builders import model_builder
  File "/usr/local/lib/python3.10/dist-packages/object_detection/builders/model_builder.py", line 26, in <module>
    from object_detection.builders import hyperparams_builder
  File "/usr/local/lib/python3.10/dist-packages/object_detection/builders/hyperparams_builder.py", line 27, in <module>
    from object_detection.core import freezable_sync_batch_norm
  File "/usr/local/lib/python3.10/dist-packages/object_detection/core/freezable_sync_batch_norm.py", line 20, in <module>
    class FreezableSyncBatchNorm(tf.keras.layers.experimental.SyncBatchNormalization
AttributeError: module 'keras._tf_keras.keras.layers' has no attribute 'experimental'
```

**Comment by NBCBM** [comment]
import tensorflow as tf
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.models import Model
from tensorflow.keras.applications import EfficientNetB0

# Example usage of BatchNormalization
inputs = tf.keras.Input(shape=(32, 32, 3))
x = EfficientNetB0(include_top=False, input_tensor=inputs)
x = BatchNormalization()(x.output)
outputs = tf.keras.layers.Dense(10, activation='softmax')(x)
model = Model(inputs=inputs, outputs=outputs)

# Rest of your code

**Comment by smtc7648** [comment]
> import tensorflow as tf
> from tensorflow.keras.layers import BatchNormalization
> from tensorflow.keras.models import Model
> from tensorflow.keras.applications import EfficientNetB0
> 
> # Example usage of BatchNormalization
> inputs = tf.keras.Input(shape=(32, 32, 3))
> x = EfficientNetB0(include_top=False, input_tensor=inputs)
> x = BatchNormalization()(x.output)
> outputs = tf.keras.layers.Dense(10, activation='softmax')(x)
> model = Model(inputs=inputs, outputs=outputs)
> 
> # Rest of your code
> 

Thanks for the response.
Could you please check the link mentioned above?

**Comment by mark-nicepants** [comment]
Following this tutorial i also ran into the same problem. 
https://blog.roboflow.com/train-a-tensorflow2-object-detection-model/

It points to this Colab:
https://colab.research.google.com/drive/1sLqFKVV94wm-lglFq_0kGo2ciM0kecWD

And after a couple of steps (not Roboflow related part of the setup). It crashes on this step:

![image](https://github.com/tensorflow/tensorflow/assets/62654433/c569a3a6-394f-49ce-abbd-b8d294374fc3)

**Comment by smtc7648** [comment]
Hey @mark-nicepants, Thanks for your response. I'll surely try out your suggestion.
However, I was able to get some success and will share the link shortly.

**Comment by chenchen1022** [comment]
> rtly.

Hi Smit, i was using the same colab.and crashed at the exact spot, would you mind share the link that you got it worked?

**Comment by tilakrayal** [comment]
@smtc7648,
As mentioned above, if the issue got resolved could you please feel free to move this issue to closed status. Thank you!
