### ISSUE TITLE
rnn_cell has no BasicLSTMCell

### ISSUE THREAD

**Issue by xusong2008** [tensorflow/tensorflow#6432]
lstm_cell = tf.contrib.rnn.BasicLSTMCell(
AttributeError: 'module' object has no attribute 'BasicLSTMCell'.

Is it been replaced by other cell?

**Comment by gunan** [comment]
rnn is being moved into core.
You can use BasicLSTMCell through
`tf.nn.rnn_cell.BasicLSTMCell`

I was able to verify this in 0.12

**Comment by sharod** [comment]
gunan I hwas having the same problem as xusong2008 . I replaced tf.contrib.rnn.BasicLSTMCell by tf.nn.rnn_cell. BasicLSTMCell as you said but now a new error is being shown:

Traceback (most recent call last):
  File "ptb_word_lm.py", line 362, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "ptb_word_lm.py", line 324, in main
    m = PTBModel(is_training=True, config=config, input_=train_input)
  File "ptb_word_lm.py", line 110, in __init__
    self._initial_state = cell.zero_state(batch_size, data_type())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn_cell.py", line 166, in zero_state
    for s in state_size_flat]
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn_cell.py", line 79, in _state_size_with_prefix
    result_state_size = tensor_shape.as_shape(state_size).as_list()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_shape.py", line 815, in as_shape
    return TensorShape(shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_shape.py", line 448, in __init__
    self._dims = [as_dimension(dims)]
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_shape.py", line 374, in as_dimension
    return Dimension(value)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_shape.py", line 33, in __init__
    self._value = int(value)
TypeError: int() argument must be a string or a number, not 'BasicLSTMCell'

Pls help soon !!

**Comment by gunan** [comment]
Looks like your is a breakage in one of the models in our models repository.
COuld you file an issue in tensorflow/models repository for a fix for that?

**Comment by nealwu** [comment]
@sharod I think I saw you open an issue in github.com/tensorflow/models and close it later -- did you end up figuring it out?

**Comment by userljw** [comment]
AttributeError: module 'tensorflow.contrib.rnn' has no attribute 'static_rnn'

**Comment by nealwu** [comment]
@userljw please upgrade your TensorFlow installation to 1.4. [`static_rnn`](https://www.tensorflow.org/api_docs/python/tf/nn/static_rnn) should be available.
