### ISSUE TITLE
BasicLSTMCell problem

### ISSUE THREAD

**Issue by sharod** [tensorflow/tensorflow#6458]
In the ptb_rnn_lm.py I have replaced tf.contrib.rnn.BasicLSTMCell by tf.nn.rnn_cell.BasicLSTMCell as suggested in [https://github.com/tensorflow/tensorflow/issues/6432](url) but now a new error is being shown:

Traceback (most recent call last):
File "ptb_word_lm.py", line 362, in
tf.app.run()
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
sys.exit(main(sys.argv[:1] + flags_passthrough))
File "ptb_word_lm.py", line 324, in main
m = PTBModel(is_training=True, config=config, input_=train_input)
File "ptb_word_lm.py", line 110, in init
self._initial_state = cell.zero_state(batch_size, data_type())
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn_cell.py", line 166, in zero_state
for s in state_size_flat]
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn_cell.py", line 79, in _state_size_with_prefix
result_state_size = tensor_shape.as_shape(state_size).as_list()
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_shape.py", line 815, in as_shape
return TensorShape(shape)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_shape.py", line 448, in init
self._dims = [as_dimension(dims)]
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_shape.py", line 374, in as_dimension
return Dimension(value)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_shape.py", line 33, in init
self._value = int(value)
TypeError: int() argument must be a string or a number, not 'BasicLSTMCell'

Pls help soon !!

**Comment by gunan** [comment]
As stated in #6432 yours seems to be an issue with `ptb_word_lm.py`

Please, next time include clearer reproduction instructions, as we cannot help anything we cannot reproduce.

@nealwu could you take a look at this, I tink you recently moved this model?

**Comment by sharod** [comment]
Ok, I solved this problem. I had changed something in the code and had mistyped a few things. Thanks for the quick help.
