### ISSUE TITLE
AttributeError: 'module' object has no attribute 'legacy_seq2seq'

### ISSUE THREAD

**Issue by sharod** [tensorflow/tensorflow#6468]
I am running the ptb_rnn_lm.py. The tensorflow version is 0.12. The error is occurring in the line:

loss = tf.contrib.legacy_seq2seq.sequence_loss_by_example(
        [logits],
        [tf.reshape(input_.targets, [-1])],
        [tf.ones([batch_size * num_steps], dtype=data_type())])

The entire error log is:

Traceback (most recent call last):
  File "ptb_word_lm.py", line 364, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "ptb_word_lm.py", line 326, in main
    m = PTBModel(is_training=True, config=config, input_=train_input)
  File "ptb_word_lm.py", line 144, in __init__
    loss = tf.contrib.legacy_seq2seq.sequence_loss_by_example(
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 35, in __getattr__
    return getattr(contrib, item)
AttributeError: 'module' object has no attribute 'legacy_seq2seq'

Pls help soon !!

**Comment by sharod** [comment]
I even downloaded and manually copied the legacy_sec2sec folder into the contrib folder. Unfortunately this didnt work either. Pls help !!

**Comment by sharod** [comment]
I have worked this out. I am using tf.nn.seq2seq.sequence_loss_by_example.This is working.

**Comment by mlad3n** [comment]
I had the same problem, followed the help for modules and found this function:

loss = tf.contrib.seq2seq.loss.seq2seq_loss

but now I get this because it returns Nan:

Traceback (most recent call last):
  File "/Users/mladenman/machine_translation2/0_basic/03_rnn/ptb_word_lm.py", line 363, in <module>
    tf.app.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/Users/mladenman/machine_translation2/0_basic/03_rnn/ptb_word_lm.py", line 325, in main
    m = PTBModel(is_training=True, config=config, input_=train_input)
  File "/Users/mladenman/machine_translation2/0_basic/03_rnn/ptb_word_lm.py", line 147, in __init__
    self._cost = cost = tf.reduce_sum(loss) / batch_size
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py", line 1173, in reduce_sum
    _ReductionDims(input_tensor, axis, reduction_indices),
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py", line 1126, in _ReductionDims
    return range(0, array_ops.rank(x))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 296, in rank
    return rank_internal(input, name, optimize=True)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 316, in rank_internal
    input_tensor = ops.convert_to_tensor(input)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 669, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 360, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.

**Comment by sharod** [comment]
It seemed like its working but it may not. Getting a new error, which may be connected to this change:

raceback (most recent call last):
File "ptb_word_lm.py", line 364, in
tf.app.run()
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
sys.exit(main(sys.argv[:1] + flags_passthrough))
File "ptb_word_lm.py", line 350, in main
verbose=True)
File "ptb_word_lm.py", line 279, in run_epoch
vals = session.run(fetches, feed_dict)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 717, in run
run_metadata_ptr)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 915, in _run
feed_dict_string, options, run_metadata)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _do_run
target_list, options, run_metadata)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 985, in _do_call
raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InvalidArgumentError: logits and labels must have the same first dimension, got logits shape [400,10000] and labels shape [420]
[[Node: Train/Model/sequence_loss_by_example/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits = SparseSoftmaxCrossEntropyWithLogits[T=DT_FLOAT, Tlabels=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](Train/Model/add, Train/Model/sequence_loss_by_example/Reshape/_129)]]
[[Node: Train/Model/truediv/_153 = _Recvclient_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_1023_Train/Model/truediv", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]]

Caused by op u'Train/Model/sequence_loss_by_example/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits', defined at:
File "ptb_word_lm.py", line 364, in
tf.app.run()
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
sys.exit(main(sys.argv[:1] + flags_passthrough))
File "ptb_word_lm.py", line 326, in main
m = PTBModel(is_training=True, config=config, input_=train_input)
File "ptb_word_lm.py", line 147, in init
[tf.ones([batch_size * num_steps], dtype=data_type())])
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/seq2seq.py", line 1017, in sequence_loss_by_example
logit, target)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 764, in sparse_softmax_cross_entropy_with_logits
precise_logits, labels, name=name)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 1857, in _sparse_softmax_cross_entropy_with_logits
features=features, labels=labels, name=name)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
op_def=op_def)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2380, in create_op
original_op=self._default_original_op, op_def=op_def)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1298, in init
self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): logits and labels must have the same first dimension, got logits shape [400,10000] and labels shape [420]
[[Node: Train/Model/sequence_loss_by_example/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits = SparseSoftmaxCrossEntropyWithLogits[T=DT_FLOAT, Tlabels=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](Train/Model/add, Train/Model/sequence_loss_by_example/Reshape/_129)]]
[[Node: Train/Model/truediv/_153 = _Recvclient_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_1023_Train/Model/truediv", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]]

**Comment by mlad3n** [comment]
I had the same problem as you, applied your change and now it works fine, so I don't think its about that line(model is still training i will update when it finishes)

**Comment by sharod** [comment]
mlad3n I am sharing my code please please take a look:

[http://pastebin.com/FM6M43w7](http://pastebin.com/FM6M43w7)

The error is as I stated above. I am new to tensorflow.

**Comment by mlad3n** [comment]
My code:
http://pastebin.com/6BSp8qhX

I'm running it with python 3.5

**Comment by sharod** [comment]
I tried it on python 2.7. I just changed the concat_v2 to concat, with the order of arguments changed as suggested [here](https://github.com/tensorflow/tensorflow/issues/6345). But the same issue I told before is coming up. Canu pls share ur reader.py code too? As the reader.py I had didnt contain ptb_producer. I manually added that function in my code. It would be a big help if u share the reader.py code. Thanks in advance !!

**Comment by shakacs** [comment]
i tried mlad3n's code on python 3.5, the same exception of mismatched shape occured as sharod, i used the reader.py as given in the master branch.

**Comment by shakacs** [comment]
try change slice back into strided_slice would fix the problem.

**Comment by gunan** [comment]
The file you are suign has been moved here:
`https://github.com/tensorflow/models/tree/master/tutorials/rnn/ptb`

Are you sure you have all the updates that are made in that file?

**Comment by michaelisard** [comment]
I assume tensorflow/models #824 will fix this but please respond to this issue once that PR lands, if it doesn't.

**Comment by gunan** [comment]
Closing due to inactivity. I think the models repository was updated to fix this issue, too.
