### ISSUE TITLE
ptb_rnn_lm.py error:tensorflow.python.framework.errors.InvalidArgumentError: logits and labels must have the same first dimension, got logits shape [400,10000] and labels shape [420] 

### ISSUE THREAD

**Issue by sharod** [tensorflow/tensorflow#6469]
Getting the error:
tensorflow.python.framework.errors.InvalidArgumentError: logits and labels must have the same first dimension, got logits shape [400,10000] and labels shape [420]

The code is available here:
[http://pastebin.com/FM6M43w7](http://pastebin.com/FM6M43w7)

I am giving the full error log here:

Traceback (most recent call last):
  File "ptb_word_lm.py", line 364, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "ptb_word_lm.py", line 350, in main
    verbose=True)
  File "ptb_word_lm.py", line 279, in run_epoch
    vals = session.run(fetches, feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 717, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 915, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 985, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InvalidArgumentError: logits and labels must have the same first dimension, got logits shape [400,10000] and labels shape [420]
	 [[Node: Train/Model/sequence_loss_by_example/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits = SparseSoftmaxCrossEntropyWithLogits[T=DT_FLOAT, Tlabels=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](Train/Model/add, Train/Model/sequence_loss_by_example/Reshape/_129)]]
	 [[Node: Train/Model/truediv/_153 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_1023_Train/Model/truediv", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'Train/Model/sequence_loss_by_example/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits', defined at:
  File "ptb_word_lm.py", line 364, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "ptb_word_lm.py", line 326, in main
    m = PTBModel(is_training=True, config=config, input_=train_input)
  File "ptb_word_lm.py", line 147, in __init__
    [tf.ones([batch_size * num_steps], dtype=data_type())])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/seq2seq.py", line 1017, in sequence_loss_by_example
    logit, target)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 764, in sparse_softmax_cross_entropy_with_logits
    precise_logits, labels, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 1857, in _sparse_softmax_cross_entropy_with_logits
    features=features, labels=labels, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2380, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1298, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): logits and labels must have the same first dimension, got logits shape [400,10000] and labels shape [420]
	 [[Node: Train/Model/sequence_loss_by_example/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits = SparseSoftmaxCrossEntropyWithLogits[T=DT_FLOAT, Tlabels=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](Train/Model/add, Train/Model/sequence_loss_by_example/Reshape/_129)]]
	 [[Node: Train/Model/truediv/_153 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_1023_Train/Model/truediv", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

**Comment by gunan** [comment]
The file you are suign has been moved here:
`https://github.com/tensorflow/models/tree/master/tutorials/rnn/ptb`

Are you sure you have all the updates that are made in that file?

**Comment by michaelisard** [comment]
I am closing due to lack of activity but please reopen if necessary.

**Comment by joa23** [comment]
Same problem here, plus a bunch of old version references like tf.contrib.rnn.BasicLSTMCell vs tf.nn.rnn_cell.BasicLSTMCell. It is an extra challenge for newbies when the tutorials are not running. ;)

**Comment by sjurgis** [comment]
Same problems here too :) after finally solving legacy API mismatches, came into this logits issue.

Interestingly it all mismatches by 20 units. It's either 420/400 when using small model, or 720/700 when using medium and large.

**Comment by RudrakshTuwani** [comment]
Yep, same problem. Interestingly, the difference between the actual shape and mismatch shape is always 20. Also, I printed the labels shape going into the seq2seq loss function, it is of the right shape there. I'm almost sure that the error is due to change in seq2seq code.

Any help would be highly appreciated !

**Comment by johnlarkin1** [comment]
Did anyone figure out a fix for this? I am also having the mismatches shape issue, off by 420 to 400. Thanks so much!

**Comment by RudrakshTuwani** [comment]
Using code from 0.12 master branch fixed it for me.

I think it is something to do with replacing. tf.strided_slice with
tf.slice.

**Comment by johnlarkin1** [comment]
Hey, 

 

No, unfortunately I already made the change from tf.strided_slice to tf.slice, so I don’t think it’s that.  Do you have any other suggestions? I really appreciate the help! 

 

Are you saying you used version 0.12.0 instead of 0.12.1? Because that would be helpful and I can just use that version perhaps. 

 

All the best,

John

**Comment by RudrakshTuwani** [comment]
Sorry for not being clear enough.

I meant use the tutorial code from 0.12 branch if you're using tf 0.12. or
above.

I had replaced the  tf.strided_slice with tf.slice as well, but I guess
there are some additional changes to be made .

**Comment by johnlarkin1** [comment]
Oh no you’re absolutely perfect! Ok I will try that. That helps a bunch. What version is the master currently on? It seems weird to me that they wouldn’t have it be the most up to date version? 

 

Thanks again! I really appreciate it.

 

John

**Comment by RudrakshTuwani** [comment]
No problem!

Oh, I think it's something to do with Google's indexing. There is no link
on the tensorflow website, so the usual way for people to get the code is
to  google it and hence, reach the old code. Atleast this is what happened
with me.

Let me know if it works for you. I'm  working on making a  simpler
implementation of the same on tensorflow  as  an exercise. I'll send you
that if the current one doesn't work.

On 23-Jan-2017 9:03 PM, "John Larkin" <notifications@github.com> wrote:

Oh no you’re absolutely perfect! Ok I will try that. That helps a bunch.
What version is the master currently on? It seems weird to me that they
wouldn’t have it be the most up to date version?



Thanks again! I really appreciate it.




John

**Comment by colmantse** [comment]
Hi, I am using r.12.0 and I switched to branch r.12.0 as suggested, this saved me from the loads of trivialities encountered previously but the 420x400 dimension prob persists, would be great if anyone can help!

**Comment by RudrakshTuwani** [comment]
Sorry for the bit of self promotion. Here's the link to my modified implementation of the same. I haven't changed it around much besides adding some extra comments and functions for getting predictions from user input.

https://github.com/RudrakshTuwani/Neural_Networks/blob/master/Language%20Model%20-%20Tensorflow%20Port%20(Complete).ipynb
