### ISSUE TITLE
tensorflow_model_optimization,quantization.keras.quantize_model raises exception on its documentation example

### ISSUE THREAD

**Issue by valerioa** [tensorflow/tensorflow#64721]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

2.16.1

### Custom code

Yes

### OS platform and distribution

Linux Ubuntu 22.04

### Python version

3.11.5

### CUDA/cuDNN version

12.3

### GPU model and memory

NVIDIA GeForce RTX 4060 8GB

### Current behavior?

The example program in the documentation of  tensorflow_model_optimization,quantization.keras.quantize_model does not run successfully

```
import keras
from keras import layers
import tensorflow_model_optimization as tfmot
model = tfmot.quantization.keras.quantize_model(
      keras.Sequential([
          layers.Dense(10, activation='relu', input_shape=(100,)),
          layers.Dense(2, activation='sigmoid')
      ]))
```

```
Python 3.11.5 (main, Sep 29 2023, 17:18:47) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import keras
>>> from keras import layers
>>> import tensorflow_model_optimization as tfmot
>>> model = tfmot.quantization.keras.quantize_model(
...       keras.Sequential([
...           layers.Dense(10, activation='relu', input_shape=(100,)),
...           layers.Dense(2, activation='sigmoid')
...       ]))
/home/valerio/py3-tf-nightly/lib/python3.11/site-packages/keras/src/layers/core/dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
2024-03-28 20:45:09.603570: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1928] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 6086 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4060, pci bus id: 0000:01:00.0, compute capability: 8.9
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/valerio/py3-tf-nightly/lib/python3.11/site-packages/tensorflow_model_optimization/python/core/quantization/keras/quantize.py", line 135, in quantize_model
    raise ValueError(
ValueError: `to_quantize` can only either be a keras Sequential or Functional model.
```

### Standalone code to reproduce the issue

```shell
import keras
from keras import layers
import tensorflow_model_optimization as tfmot
model = tfmot.quantization.keras.quantize_model(
      keras.Sequential([
          layers.Dense(10, activation='relu', input_shape=(100,)),
          layers.Dense(2, activation='sigmoid')
      ]))
```
```


### Relevant log output

```shell
/home/valerio/py3-tf-nightly/lib/python3.11/site-packages/keras/src/layers/core/dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
2024-03-28 20:45:09.603570: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1928] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 6086 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4060, pci bus id: 0000:01:00.0, compute capability: 8.9
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/valerio/py3-tf-nightly/lib/python3.11/site-packages/tensorflow_model_optimization/python/core/quantization/keras/quantize.py", line 135, in quantize_model
    raise ValueError(
ValueError: `to_quantize` can only either be a keras Sequential or Functional model.
```

**Comment by menotar1** [comment]
I encountered this problem. Where is the solution to the problem?

**Comment by valerioa** [comment]
keras.Sequential and tf_keras.Sequential are different classes. They have different signatures.

Run as:

```
import keras
from keras import layers
import tensorflow_model_optimization as tfmot
model = tfmot.quantization.keras.quantize_model(
      keras.Sequential([
          layers.Dense(10, activation='relu', input_shape=(100,)),
          layers.Dense(2, activation='sigmoid')
      ]))
```
it will not work. But run as:

```
import tf_keras
from tf_keras import layers
import tensorflow_model_optimization as tfmot
    
model = tfmot.quantization.keras.quantize_model(
       tf_keras.Sequential([
           layers.Dense(10, activation='relu', input_shape=(100,)),
           layers.Dense(2, activation='sigmoid')
       ]))
```
It will work.

keras.Sequential's signature  is ` keras.src.models.sequential.Sequential`

tf_keras.Sequential's is `tf_keras.src.engine.sequential.Sequential`

**Comment by valerioa** [comment]
The tensorflow team should probably update the `tensorflow_model_optimization` examples
