### ISSUE TITLE
Issue with tf v0.12.0 when using split

### ISSUE THREAD

**Issue by KeithYin** [tensorflow/tensorflow#6501]
the code run correctly with tf 0.12rc1.0, but when using 0.12.0, an error occured. 
here is the log. 
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcurand.so.8.0 locally
W tensorflow/core/platform/cpu_feature_guard.cc:95] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:95] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:95] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:95] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "/home/keith/PycharmProjects/pic2sentence/Model.py", line 359, in <module>
    tf.app.run()
  File "/home/keith/workspace/tfboy_2.7/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/keith/PycharmProjects/pic2sentence/Model.py", line 343, in main
    model = Model()
  File "/home/keith/PycharmProjects/pic2sentence/Model.py", line 42, in __init__
    outputs = self.alex_net2(self.encoder_inputs, is_training)  # [None, 4096]
  File "/home/keith/PycharmProjects/pic2sentence/Model.py", line 124, in alex_net2
    conv2_in = conv(maxpool1, conv2W, conv2b, k_h, k_w, c_o, s_h, s_w, padding="SAME", group=group)
  File "/home/keith/PycharmProjects/pic2sentence/Model.py", line 91, in conv
    input_groups = tf.split(3, group, input)
  File "/home/keith/workspace/tfboy_2.7/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1319, in split
    split_dim=axis, num_split=num_or_size_splits, value=value, name=name)
  File "/home/keith/workspace/tfboy_2.7/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3385, in _split
    num_split=num_split, name=name)
  File "/home/keith/workspace/tfboy_2.7/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 509, in apply_op
    (prefix, dtypes.as_dtype(input_arg.type).name))
TypeError: Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32.

**Comment by yaroslavvb** [comment]
split argument order changed in HEAD -- https://github.com/tensorflow/tensorflow/blob/64edd34ce69b4a8033af5d217cb8894105297d8a/RELEASE.md

**Comment by KeithYin** [comment]
@yaroslavvb Thanks a lot

**Comment by HRLTY** [comment]
@yaroslavvb  Thanks. I thought my python release has bug...
