### ISSUE TITLE
Tensorboard AttributeError: 'module' object has no attribute 'cpu_count'

### ISSUE THREAD

**Issue by StrangeTcy** [tensorflow/tensorflow#6513]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
Some people report having similar problems with 'module' objects having no attribute something-or-other and claim they were solved by upgrading.

### Environment info
Operating System:
Ubuntu 17.04 x64
Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
```
-rw-r--r-- 1 root root   558720 сен 15 02:02 /usr/local/cuda/lib64/libcudadevrt.a
-rw-r--r-- 1 root root   383336 дек 23 01:26 /usr/local/cuda/lib64/libcudart.so
-rw-r--r-- 1 root root   383336 дек 23 01:25 /usr/local/cuda/lib64/libcudart.so.7.5
lrwxrwxrwx 1 root root       19 дек 23 02:17 /usr/local/cuda/lib64/libcudart.so.8.0 -> libcudart.so.8.0.44
-rw-r--r-- 1 root root   415432 сен 15 02:02 /usr/local/cuda/lib64/libcudart.so.8.0.44
-rw-r--r-- 1 root root   775162 сен 15 02:02 /usr/local/cuda/lib64/libcudart_static.a
lrwxrwxrwx 1 root root       13 дек 23 02:17 /usr/local/cuda/lib64/libcudnn.so -> libcudnn.so.5
lrwxrwxrwx 1 root root       17 дек 23 02:17 /usr/local/cuda/lib64/libcudnn.so.5 -> libcudnn.so.5.1.5
-rwxr-xr-x 1 root root 79337624 дек 22 04:25 /usr/local/cuda/lib64/libcudnn.so.5.1.5
-rw-r--r-- 1 root root 69756172 дек 22 04:25 /usr/local/cuda/lib64/libcudnn_static.a

```
(yes, it's an unholy mess, with russian date format. sorry)

If installed from binary pip package, provide:

1. A link to the pip package you installed: 
https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-0.12.0-cp27-none-linux_x86_64.whl
as per[ instructions](https://www.tensorflow.org/get_started/os_setup)
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
```
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
0.12.0
```

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
```
cd example; 
python /usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/tensorboard.py --logdir=/home/myname/example/log_simple_graph
```

### What other attempted solutions have you tried?
See above; I've tried to run the actual `tensorboard.py` instead of just `tensorboard --logdir=`

### Logs or other output that would be helpful
Running `cd example; 
python /usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/tensorboard.py --logdir=/home/myname/example/log_simple_graph` results in:
```
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/tensorboard.py", line 34, in <module>
    from tensorflow.tensorboard.backend import server
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/backend/server.py", line 37, in <module>
    from tensorflow.tensorboard.backend import handler
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/backend/handler.py", line 43, in <module>
    from tensorflow.tensorboard.plugins import REGISTERED_PLUGINS
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/plugins/__init__.py", line 20, in <module>
    from tensorflow.tensorboard.plugins.projector.plugin import ProjectorPlugin
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/plugins/projector/plugin.py", line 27, in <module>
    from tensorflow.contrib.tensorboard.plugins.projector import PROJECTOR_FILENAME
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/__init__.py", line 27, in <module>
    from tensorflow.contrib import factorization
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/factorization/__init__.py", line 24, in <module>
    from tensorflow.contrib.factorization.python.ops.gmm import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/factorization/python/ops/gmm.py", line 30, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/__init__.py", line 66, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/__init__.py", line 23, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 27, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/__init__.py", line 269, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.classifier import Classifier
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/classifier.py", line 25, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 52, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/learn_io/__init__.py", line 22, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/learn_io/dask_io.py", line 26, in <module>
    import dask.dataframe as dd
  File "/usr/local/lib/python2.7/dist-packages/dask/dataframe/__init__.py", line 5, in <module>
    from .io import (from_array, from_pandas, from_bcolz,
  File "/usr/local/lib/python2.7/dist-packages/dask/dataframe/io/__init__.py", line 6, in <module>
    from .csv import read_csv, to_csv, read_table
  File "/usr/local/lib/python2.7/dist-packages/dask/dataframe/io/csv.py", line 147, in <module>
    CPU_COUNT = psutil.cpu_count()
AttributeError: 'module' object has no attribute 'cpu_count'

```

I've been following [this](https://www.oreilly.com/learning/hello-tensorflow) intro, and the code from there worked perfectly for me (apart from some warnings about deprecations).

**Comment by gunan** [comment]
As your logs show, the error is thrown due to a missing function call in psutil library.
https://github.com/giampaolo/psutil/blob/master/HISTORY.rst#200

cpu_count seems to be added in version 2.0.0 of psutil.
So running the following command should fix your problem:
```
sudo pip install --upgrade psutil
```
Also the stacktrace shows that this is a call in `dask` library. So this issue is better reported to dask library.

**Comment by StrangeTcy** [comment]
I tried upgrading `psutil`, but somehow that didn't work. Anyway, it does now. Thanks!

**Comment by haolsun** [comment]
Did you solve the problem? I have upgraded psutil, however, it didn't work. My OS is  ubuntu 14.04.

**Comment by xiaohujecky** [comment]
@StrangeTcy how did you fix your problem? I came across  the same problem.
