### ISSUE TITLE
tensorflow (0.12.0) doesn't work with libcudart.so.8.0.44

### ISSUE THREAD

**Issue by FrankYu** [tensorflow/tensorflow#6514]
Hi，
I'm using cuda-8.0 on centos7.3, and I install tensorflow(0.12.0)  with pip.
when I tried to import tensorflow, it report "ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory".
I'm sure libcudart.so.8.0 does exist. tensorflow-0.12.0 should works with cuda-8.0 according the docs.

```
# python -c 'import tensorflow'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 60, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.
# ll  /usr/local/cuda/lib64/libcudart.so*
lrwxrwxrwx. 1 root root     16 Dec 20 16:22 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.8.0
lrwxrwxrwx. 1 root root     19 Dec 20 16:22 /usr/local/cuda/lib64/libcudart.so.8.0 -> libcudart.so.8.0.44
-rwxr-xr-x. 1 root root 415432 Dec 20 16:22 /usr/local/cuda/lib64/libcudart.so.8.0.44
# pip list|grep tensorflow
tensorflow (0.12.0)
tensorflow-gpu (0.12.0)
```

**Comment by gunan** [comment]
TensorFlow only has official Ubuntu support.
For CentOS, we have not tested our pip packages.

Possible issues that come to my mind, did you check your LD_LIBRARY_PATH, does it include the directory /usr/local/cuda/lib64/ ?
If not, could you try adding that folder to your LD_LIBRARY_PATH and try again?

**Comment by FrankYu** [comment]
@gunan 
Thanks. it's LD_LIBRARY_PATH's problem.
Any plan official support TensorFlow on CentOS?

**Comment by gunan** [comment]
Not in our short term plans, but things may change.
I am glad that we were able to resolve your problem.
