### ISSUE TITLE
[DOCS] Missing complex input for Round op

### ISSUE THREAD

**Issue by LucaTamSapienza** [tensorflow/tensorflow#65317]
### Issue type

Documentation Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

2.15.0

### Custom code

No

### OS platform and distribution

MacOS Sonoma

### Python version

3.9

### Current behavior?

While testing the `Round` operation, I noticed an inconsistency with the [documentation](https://www.tensorflow.org/api_docs/python/tf/raw_ops/Round). On the official page, it's described that a complex tensor can be passed as input. However, when I try to replicate this in my environment, it doesn't work as expected. I have to apply the `Round` operation separately to the real and imaginary parts of the tensor to achieve the desired result.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
x = tf.constant([1+2j, 3+4j])
rounded = tf.raw_ops.Round(x=x)
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lucatam/Documents/OpenSourceProject/openvino/opvenv/lib/python3.9/site-packages/tensorflow/python/util/tf_export.py", line 403, in wrapper
    return f(**kwargs)
  File "/Users/lucatam/Documents/OpenSourceProject/openvino/opvenv/lib/python3.9/site-packages/tensorflow/python/ops/gen_math_ops.py", line 8770, in round
    _ops.raise_from_not_ok_status(e, name)
  File "/Users/lucatam/Documents/OpenSourceProject/openvino/opvenv/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 5883, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.NotFoundError: Could not find device for node: {{node Round}} = Round[T=DT_COMPLEX128]
All kernels registered for op Round:
  device='XLA_CPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_INT16, DT_INT8, DT_COMPLEX64, DT_INT64, DT_BFLOAT16, DT_COMPLEX128, DT_HALF]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_INT32]
  device='CPU'; T in [DT_INT64]
 [Op:Round] name:
```

**Comment by SuryanarayanaY** [comment]
Hi @LucaTamSapienza ,

Thanks for reporting. IMO, complex data types not supported for this Op as per below code. 

https://github.com/tensorflow/tensorflow/blob/a787405cf0adab1793b8f01c32d222ec469c8818/tensorflow/core/kernels/cwise_ops.h#L513
May need to update the same wrt documentation. Also I am not sure for what case rounding is applicable to int32, int_64 . 

Will propose some modifications and let's hear from dev team.

**Comment by Venkat6871** [comment]
Hi @LucaTamSapienza ,
Apologies for the delay, and thank you for your patience.

You are correct that complex inputs are currently not supported for the Round op, even though they appear in the type constraint. This behavior is being addressed in the following PR raised by @VibhorGautam
https://github.com/tensorflow/tensorflow/pull/111885
The PR adds a clearer error message for complex inputs and updates the documentation accordingly.

Thanks @VibhorGautam for the contribution! Once the PR is merged, this issue should be resolved.

**Comment by Kayyuri** [comment]
Hi @LucaTamSapienza,
Thank you so much for filing this issue! We truly appreciate your support. At the moment, this request is not prioritized and mark it for community contributions. If you would like to contribute on a fix, please feel free to fork the repository and submit a pull request in accordance with the TensorFlow [CONTRIBUTION GUIDELINES](https://www.tensorflow.org/community/contribute/code) and link this issue in your PR to ensure the maintainers can easily review and collaborate.
To avoid duplicate work, please leave a comment here if you decide to take it on!

Thank you again for your interest and we look forward to seeing your contributions!

**Comment by qiu-tiandev** [comment]
Hi! I'd like to work on this issue. I'll add proper error handling for complex dtypes in tf.math.round and update the documentation accordingly.
