### ISSUE TITLE
InvalidArgumentError (see above for traceback): Nan in summary histogram for: dnn/hiddenlayer_0_activation

### ISSUE THREAD

**Issue by omarshehab** [tensorflow/tensorflow#6534]
I am trying to do regression for my own data following the example of [Deep Neural Network Regression with Boston Data](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/learn/boston.py).

Following is my code.

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from sklearn import cross_validation
from sklearn import metrics
from sklearn import preprocessing
import tensorflow as tf
from tensorflow.contrib import learn
from numpy import genfromtxt
import numpy as np


def main():
  # Load dataset
  # ARM4mDec2002Jul2015OklahomaV2_mar_apr_may_date_time_normalized_16000_test_data_x.csv
  # ARM4mDec2002Jul2015OklahomaV2_mar_apr_may_date_time_normalized_16000_test_data_y.csv

  x_test = genfromtxt('ARM4mDec2002Jul2015OklahomaV2_mar_apr_may_date_time_normalized_16000_test_data_x.csv', delimiter=',')
  y_test = genfromtxt('ARM4mDec2002Jul2015OklahomaV2_mar_apr_may_date_time_normalized_16000_test_data_y.csv', delimiter=',')
  x_test = x_test.astype(np.float32, copy=False)
  y_test = y_test.astype(np.float32, copy=False)
  
  # ARM4mDec2002Jul2015OklahomaV2_mar_apr_may_date_time_normalized_16000_training_data_x.csv
  # ARM4mDec2002Jul2015OklahomaV2_mar_apr_may_date_time_normalized_16000_training_data_y.csv

  x_train = genfromtxt('ARM4mDec2002Jul2015OklahomaV2_mar_apr_may_date_time_normalized_16000_training_data_x.csv', delimiter=',')
  y_train = genfromtxt('ARM4mDec2002Jul2015OklahomaV2_mar_apr_may_date_time_normalized_16000_training_data_y.csv', delimiter=',')
  x_train = x_train.astype(np.float32, copy=False)
  y_train = y_train.astype(np.float32, copy=False)
  
  # ARM4mDec2002Jul2015OklahomaV2_mar_apr_may_date_time_normalized_16000_validate_data_x.csv
  # ARM4mDec2002Jul2015OklahomaV2_mar_apr_may_date_time_normalized_16000_validate_data_y.csv

  # Scale data (training set) to 0 mean and unit standard deviation.
  # scaler = preprocessing.StandardScaler()
  # x_train = scaler.fit_transform(x_train)

  # Build 2 layer fully connected DNN with 10, 10 units respectively.
  feature_columns = learn.infer_real_valued_columns_from_input(x_train)
  regressor = learn.DNNRegressor(
      feature_columns=feature_columns, hidden_units=[10, 10],optimizer=tf.train.GradientDescentOptimizer(
      learning_rate=0.1))

  # Fit
  regressor.fit(x_train, y_train, steps=5000, batch_size=1)

  # Predict and score
  y_predicted = list(
      regressor.predict(scaler.transform(x_test), as_iterable=True))
  score = metrics.mean_squared_error(y_predicted, y_test)

  print('MSE: {0:f}'.format(score))


if __name__ == '__main__':
  tf.app.run()
```

I am getting the following error.

> >>> arm_data_regression.main()
> WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmpIda516
> INFO:tensorflow:Using default config.
> INFO:tensorflow:Using config: {'save_summary_steps': 100, '_num_ps_replicas': 0, '_task_type': None, '_environment': 'local', '_is_chief': True, 'save_checkpoints_secs': 600, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f5464bf7a10>, 'tf_config': gpu_options {
>   per_process_gpu_memory_fraction: 1
> }
> , '_task_id': 0, 'tf_random_seed': None, 'keep_checkpoint_every_n_hours': 10000, '_evaluation_master': '', 'save_checkpoints_steps': None, '_master': '', 'keep_checkpoint_max': 5}
> WARNING:tensorflow:From arm_data_regression.py:45 in main.: calling fit (from tensorflow.contrib.learn.python.learn.estimators.estimator) with x is deprecated and will be removed after 2016-12-01.
> Instructions for updating:
> Estimator is decoupled from Scikit Learn interface by moving into
> separate class SKCompat. Arguments x, y and batch_size are only
> available in the SKCompat class, Estimator will only accept input_fn.
> Example conversion:
>   est = Estimator(...) -> est = SKCompat(Estimator(...))
> WARNING:tensorflow:From arm_data_regression.py:45 in main.: calling fit (from tensorflow.contrib.learn.python.learn.estimators.estimator) with y is deprecated and will be removed after 2016-12-01.
> Instructions for updating:
> Estimator is decoupled from Scikit Learn interface by moving into
> separate class SKCompat. Arguments x, y and batch_size are only
> available in the SKCompat class, Estimator will only accept input_fn.
> Example conversion:
>   est = Estimator(...) -> est = SKCompat(Estimator(...))
> WARNING:tensorflow:From arm_data_regression.py:45 in main.: calling fit (from tensorflow.contrib.learn.python.learn.estimators.estimator) with batch_size is deprecated and will be removed after 2016-12-01.
> Instructions for updating:
> Estimator is decoupled from Scikit Learn interface by moving into
> separate class SKCompat. Arguments x, y and batch_size are only
> available in the SKCompat class, Estimator will only accept input_fn.
> Example conversion:
>   est = Estimator(...) -> est = SKCompat(Estimator(...))
> INFO:tensorflow:Summary name dnn/hiddenlayer_0:fraction_of_zero_values is illegal; using dnn/hiddenlayer_0_fraction_of_zero_values instead.
> INFO:tensorflow:Summary name dnn/hiddenlayer_0:activation is illegal; using dnn/hiddenlayer_0_activation instead.
> INFO:tensorflow:Summary name dnn/hiddenlayer_1:fraction_of_zero_values is illegal; using dnn/hiddenlayer_1_fraction_of_zero_values instead.
> INFO:tensorflow:Summary name dnn/hiddenlayer_1:activation is illegal; using dnn/hiddenlayer_1_activation instead.
> INFO:tensorflow:Summary name logits:fraction_of_zero_values is illegal; using logits_fraction_of_zero_values instead.
> INFO:tensorflow:Summary name logits:activation is illegal; using logits_activation instead.
> INFO:tensorflow:Create CheckpointSaverHook.
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "arm_data_regression.py", line 45, in main
>     regressor.fit(x_train, y_train, batch_size=1)
>   File "/home/shehab/.local/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 191, in new_func
>     return func(*args, **kwargs)
>   File "/home/shehab/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 355, in fit
>     max_steps=max_steps)
>   File "/home/shehab/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 733, in _train_model
>     max_steps=max_steps)
>   File "/home/shehab/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/graph_actions.py", line 301, in _monitored_train
>     None)
>   File "/home/shehab/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 473, in run
>     run_metadata=run_metadata)
>   File "/home/shehab/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 628, in run
>     run_metadata=run_metadata)
>   File "/home/shehab/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 595, in run
>     return self._sess.run(*args, **kwargs)
>   File "/home/shehab/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 729, in run
>     run_metadata=run_metadata)
>   File "/home/shehab/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 595, in run
>     return self._sess.run(*args, **kwargs)
>   File "/home/shehab/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 766, in run
>    run_metadata_ptr)
>   File "/home/shehab/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 964, in _run
>     feed_dict_string, options, run_metadata)
>   File "/home/shehab/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1014, in _do_run
>     target_list, options, run_metadata)
>   File "/home/shehab/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1034, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: dnn/hiddenlayer_0_activation
> 	 [[Node: dnn/hiddenlayer_0_activation = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](dnn/hiddenlayer_0_activation/tag, dnn/hiddenlayer_0/hiddenlayer_0/Relu)]]
> 
> Caused by op u'dnn/hiddenlayer_0_activation', defined at:
>   File "<stdin>", line 1, in <module>
>   File "arm_data_regression.py", line 45, in main
>     regressor.fit(x_train, y_train, batch_size=1)
>   File "/home/shehab/.local/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 191, in new_func
>     return func(*args, **kwargs)
>   File "/home/shehab/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 355, in fit
>     max_steps=max_steps)
>   File "/home/shehab/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 699, in _train_model
>     train_ops = self._get_train_ops(features, labels)
>   File "/home/shehab/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 219, in _get_train_ops
>     logits = self._logits(features, is_training=True)
>   File "/home/shehab/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 312, in _logits
>     logits = self._dnn_logits(features, is_training)
>   File "/home/shehab/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 295, in _dnn_logits
>     features, self._dnn_feature_columns, is_training)
>   File "/home/shehab/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/composable_model.py", line 360, in build_model
>     self._add_hidden_layer_summary(net, scope.name)
>   File "/home/shehab/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/composable_model.py", line 322, in _add_hidden_layer_summary
>     summary.histogram("%s:activation" % tag, value)
>   File "/home/shehab/.local/lib/python2.7/site-packages/tensorflow/python/summary/summary.py", line 205, in histogram
>     tag=scope.rstrip('/'), values=values, name=scope)
>   File "/home/shehab/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_logging_ops.py", line 139, in _histogram_summary
>     name=name)
>   File "/home/shehab/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 759, in apply_op
>     op_def=op_def)
>   File "/home/shehab/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2240, in create_op
>     original_op=self._default_original_op, op_def=op_def)
>   File "/home/shehab/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1128, in __init__
>     self._traceback = _extract_stack()
> 
> InvalidArgumentError (see above for traceback): Nan in summary histogram for: dnn/hiddenlayer_0_activation
> 	 [[Node: dnn/hiddenlayer_0_activation = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](dnn/hiddenlayer_0_activation/tag, dnn/hiddenlayer_0/hiddenlayer_0/Relu)]]

Am I passing any deprecated argument to DNNRegressor.fit()?

**Comment by michaelisard** [comment]
This type of usage question is better asked on [Stackoverflow](http://stackoverflow.com/questions/tagged/tensorflow). Github issues are for bug reports and installation issues.
