### ISSUE TITLE
Unable to run Object Detection API i.e. AttributeError: module 'keras._tf_keras.keras.layers' has no attribute 'experimental'

### ISSUE THREAD

**Issue by girraj96** [tensorflow/tensorflow#65463]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.15.0

### Custom code

Yes

### OS platform and distribution

Apple M2

### Python version

3.11

### Current behavior?

Command : python object_detection/builders/model_builder_tf2_test.py

Output : 

I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-11 12:54:15.652670: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/models/research/object_detection/builders/model_builder_tf2_test.py", line 24, in <module>
    from object_detection.builders import model_builder
  File "/usr/local/lib/python3.10/dist-packages/object_detection/builders/model_builder.py", line 26, in <module>
    from object_detection.builders import hyperparams_builder
  File "/usr/local/lib/python3.10/dist-packages/object_detection/builders/hyperparams_builder.py", line 27, in <module>
    from object_detection.core import freezable_sync_batch_norm
  File "/usr/local/lib/python3.10/dist-packages/object_detection/core/freezable_sync_batch_norm.py", line 20, in <module>
    class FreezableSyncBatchNorm(tf.keras.layers.experimental.SyncBatchNormalization
AttributeError: module 'keras._tf_keras.keras.layers' has no attribute 'experimental'

### Standalone code to reproduce the issue

```shell
Step 1 - Open Google collab's new note
Step 2 - command  

!git clone https://github.com/tensorflow/models.git

Step 3 - command 

%cd models/research
# Compile protos.
!protoc object_detection/protos/*.proto --python_out=.
# Install TensorFlow Object Detection API.
!cp object_detection/packages/tf2/setup.py .
!python -m pip install . 

Step 4 - command 

!python object_detection/builders/model_builder_tf2_test.py
```

**Comment by tilakrayal** [comment]
@girraj96,
The temporary workaround for the issue is Could you please try to limit the versions of **tf-models-official >=2.5.1, <2.16.0** and comment out keras in the **research/object_detection/packages/tf2/setup.py**. By default tensorflow v2.16.1 import keras3.0.

https://github.com/tensorflow/tensorflow/issues/56889

For further queries please try to connect with [tensorflow/models](https://github.com/tensorflow/models) repo for the quick resolution.

Thank you!

**Comment by girraj96** [comment]
Thanks it's working now

**Comment by Knitrino** [comment]
Can anyone provide more clarity on these issues? I've been attempting to install for 4 full days now, and have tried just about every permutation of tensorflow, keras, and associated modules, and now I've started looping through python versions. I must have created and destroyed my environment 500 times by now. I've been attempting to follow this, as well as [56889](https://github.com/tensorflow/tensorflow/issues/56889) and [64349] https://github.com/tensorflow/tensorflow/issues/64349. What is the magic combination????

When using Tensorflow 2.13.1 and python 3.10.16 (I think, I've tried so many different things it's hard to recall) I got exactly the keras error shown above. I've tried installing specific versions and commenting out the keras line in setup.py. Most recently, I've tried to repeat exactly what's here, "limit the versions of tf-models-official >=2.5.1, <2.16.0 and comment out keras in the research/object_detection/packages/tf2/setup.py" In this case, I don't get as far as the error above, instead I get errors when installing once it gets to pyyaml (shown below). I just can't keep banging my head against the wall. People are clearly getting this working, but I just don't know how and I can't seem to find good documentation anywhere. I think I'll go back to tf 2.13.1 and python 3.10, as that's the closest I feel I've gotten. I would be so grateful for any help and detailed steps to solve. These vagaries aren't working for me.

TensorFlow version

2.15.0

Custom code

Yes

OS platform and distribution

Apple M1, OS 15.0.1

Python version

3.11

Current behavior?

Command : nano setup.py # to comment out keras and limit tf-models-official
pip install .

Output :
...
Using cached PyYAML-5.3.1.tar.gz (269 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [37 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/t1/l60yx2313fngr2npyppl3pj40000gn/T/pip-install-ajgfzqpd/pyyaml_0348f4f3a1d64963a758e601302e6265/setup.py", line 291, in <module>
          setup(
        File "/opt/anaconda3/envs/tf_env/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 186, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/opt/anaconda3/envs/tf_env/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 202, in run_commands
          dist.run_commands()
        File "/opt/anaconda3/envs/tf_env/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 983, in run_commands
          self.run_command(cmd)
        File "/opt/anaconda3/envs/tf_env/lib/python3.11/site-packages/setuptools/dist.py", line 999, in run_command
          super().run_command(command)
        File "/opt/anaconda3/envs/tf_env/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 1002, in run_command
          cmd_obj.run()
        File "/opt/anaconda3/envs/tf_env/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 312, in run
          self.find_sources()
        File "/opt/anaconda3/envs/tf_env/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 320, in find_sources
          mm.run()
        File "/opt/anaconda3/envs/tf_env/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 543, in run
          self.add_defaults()
        File "/opt/anaconda3/envs/tf_env/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 581, in add_defaults
          sdist.add_defaults(self)
        File "/opt/anaconda3/envs/tf_env/lib/python3.11/site-packages/setuptools/command/sdist.py", line 109, in add_defaults
          super().add_defaults()
        File "/opt/anaconda3/envs/tf_env/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 239, in add_defaults
          self._add_defaults_ext()
        File "/opt/anaconda3/envs/tf_env/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 324, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/t1/l60yx2313fngr2npyppl3pj40000gn/T/pip-install-ajgfzqpd/pyyaml_0348f4f3a1d64963a758e601302e6265/setup.py", line 199, in get_source_files
          self.cython_sources(ext.sources, ext)
          ^^^^^^^^^^^^^^^^^^^
        File "/opt/anaconda3/envs/tf_env/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 120, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
