### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: logs

### ISSUE THREAD

**Issue by advancedits** [tensorflow/tensorflow#6589]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

None

### Environment info
Operating System:
Mac OS X El Capitan

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:
Used steps shown here with docker
https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/#3

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
I am following all the steps in this tutorial
https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/#3 but I am getting the following error

`COMPUTER_NAME:tf_files USERNAME$ docker run -it -v $HOME/tf_files:/tf_files  gcr.io/tensorflow/tensorflow:latest-devel
root@e6a49799067c:~# cd /tensorflow/
root@e6a49799067c:/tensorflow# git pull
remote: Counting objects: 1444, done.
remote: Compressing objects: 100% (719/719), done.
remote: Total 1444 (delta 693), reused 490 (delta 490), pack-reused 221
Receiving objects: 100% (1444/1444), 1.36 MiB | 469.00 KiB/s, done.
Resolving deltas: 100% (753/753), completed with 239 local objects.
From https://github.com/tensorflow/tensorflow
 * [new branch]      fix-dbpedia -> origin/fix-dbpedia
   8308ecd..fa4ba83  master     -> origin/master
   9381242..1092f91  r1.0       -> origin/r1.0
 * [new tag]         0.12.1     -> 0.12.1
Already up-to-date.
root@e6a49799067c:/tensorflow# python tensorflow/examples/image_retraining/retrain.py \ --bottleneck_dir=/tf_files/bottlenecks \ --how_many_training_steps 500 \ --model_dir=/tf_files/inception \ --output_graph=/tf_files/retrained_graph.pb \ --output_labels=/tf_files/retrained_labels.txt \ --image_dir /tf_files/flower_photos
>> Downloading inception-2015-12-05.tgz 100.0%
Successfully downloaded inception-2015-12-05.tgz 88931400 bytes.
Looking for images in '.git'
No files found
Looking for images in 'logs'
Traceback (most recent call last):
  File "tensorflow/examples/image_retraining/retrain.py", line 1012, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "tensorflow/examples/image_retraining/retrain.py", line 757, in main
    FLAGS.validation_percentage)
  File "tensorflow/examples/image_retraining/retrain.py", line 148, in create_image_lists
    file_list.extend(gfile.Glob(file_glob))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 269, in get_matching_files
    compat.as_bytes(filename), status)]
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: logs`

### What other attempted solutions have you tried?
Tried install tensorflow 0.11 in docker but that didn't help

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by advancedits** [comment]
The issue seemed to have been with my retrain statement. I changed it to this and it worked

`python tensorflow/examples/image_retraining/retrain.py --bottleneck_dir=/tf_files/bottlenecks --model_dir=/tf_files/inception --output_graph=/tf_files/retrained_graph.pb --output_labels=/tf_files/retrained_labels.txt --image_dir /tf_files/flower_photos`

**Comment by EAZYE9000** [comment]
python -c "import tensorflow; print(tensorflow.__version__)"
0.12.1

**Comment by EAZYE9000** [comment]
Looking for images in '.git'
No files found
Looking for images in 'refs'
Traceback (most recent call last):
  File "tensorflow/examples/image_retraining/retrain.py", line 1012, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "tensorflow/examples/image_retraining/retrain.py", line 757, in main
    FLAGS.validation_percentage)
  File "tensorflow/examples/image_retraining/retrain.py", line 148, in create_image_lists
    file_list.extend(gfile.Glob(file_glob))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 269, in get_matching_files
    compat.as_bytes(filename), status)]
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: refs

**Comment by avi-jain** [comment]
^Getting a similar error. Retrain command seems fine. Have you managed to resolve this?

**Comment by TonySnark** [comment]
Getting same error.

**Comment by EAZYE9000** [comment]
It was months ago I got this. Run me through what you're trying to do, maybe I can help. @avi-jain @TonySnark

**Comment by TonySnark** [comment]
Thanks easye. I have a feeling it's a file structure problem...

I cd to a models-master dir. In there, I have a tf_files dir with my image folders.

I run Retrain.py from models-master, and it works fine. Spits out /bottlenecks /inception /retrained_labels.txt and /retrained_graph.pb in the tf_files folder.

Again from models-master, I run label_image.py as it is on "tensor flow for poets" tutorial:
https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/?utm_campaign=chrome_series_machinelearning_063016&utm_source=gdev&utm_medium=yt-desc#5

errors below:
`(tensorflow) Benjamins-Mac-Pro:models-master tonysnark$ python3 label_image.py /Users/tonysnark/Downloads/20158069_10104845333160530_2508081536327318535_o.jpg
Traceback (most recent call last):
  File "label_image.py", line 15, in <module>
    in tf.gfile.GFile("retrained_labels.txt")]
  File "label_image.py", line 14, in <listcomp>
    label_lines = [line.rstrip() for line 
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 213, in __next__
    return self.next()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 207, in next
    retval = self.readline()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 176, in readline
    self._preread_check()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 78, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: retrained_labels.txt
`

**Comment by drashmi29** [comment]
even I am facing same issue:
 File "object_detection/create_flower_tf_record.py", line 216, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "object_detection/create_flower_tf_record.py", line 195, in main
    examples_list = dataset_util.read_examples_list(examples_path)
  File "/home/rashmi/models/object_detection/utils/dataset_util.py", line 59, in read_examples_list
    lines = fid.readlines()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 181, in readlines
    self._preread_check()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 78, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: annotations/trainval.txt

**Comment by onlyak** [comment]
Can someone help me out with this problem?

Traceback (most recent call last):
  File "export_inference_graph.py", line 106, in <module>
    tf.app.run()
  File "/home/foss/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "export_inference_graph.py", line 99, in main
    text_format.Merge(f.read(), pipeline_config)
  File "/home/foss/anaconda3/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 118, in read
    self._preread_check()
  File "/home/foss/anaconda3/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 78, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/home/foss/anaconda3/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/home/foss/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: training/to/ssd_inception_v2.config

**Comment by cancoo** [comment]
I am facing same issue, any update ?

**Comment by roblee357** [comment]
I am facing same issue, any update ?

**Comment by hamzamk** [comment]
Guys, it has been months. Has anyone found a solution or quit tensorflow?

**Comment by hamzamk** [comment]
@advancedits @EAZYE9000 @avi-jain @TonySnark @drashmi29

**Comment by onlyak** [comment]
@hamzamk Can you share the error which you are getting? It will be easy to figure it out.

**Comment by hamzamk** [comment]
@onlyak 
**What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?**
https://github.com/tensorflow/models/issues/2246

**Environment info**

Environment:
Ubuntu 16.04
CUDA 8.0 and 6.0, TF 1.4.0, Python 3.5

I am using conda virtual environment, below are my paths from the bashrc file:
#added by me for protobuf
export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim

#To the Ob folder 
export MODELS=/home/hamza/anaconda3/envs/tensorflow/models/research
export PYTHONPATH=$MODELS:$MODELS/slim
export OBJ_DET=$MODELS/object_detection

#further i add for the custom training of mobilenet
export PYTHONPATH=$OBJ_DET
export PYTHONPATH=$OBJ_DET/training


Errors are the follow:

when i enter the command
python3 train.py --logtostderr --train_dir=training/ --pipeline_config_path=~/Desktop/ssd_mobilenet_v1_pets.config

or 

python $OBJ_DET/train.py --logtostderr --train_dir=training --pipeline_config_path=training/ssd_mobilenet_v1_pets.config
i get the following error:

tensorflow.python.framework.errors_impl.NotFoundError: ~/Desktop/ssd_mobilenet_v1_pets.config; No such file or directory

the file ssd_mobilenet_v1_pets.config is in training folder

**Comment by AP8050** [comment]
I am facing same issue...please any one help me to solve this issue...

**Comment by Amandeep-iOS** [comment]
Hi Everyone,

With regards to :- 

tensorflow.python.framework.errors_impl.NotFoundError: training/to/ssd_inception_v2.config

Make sure in your terminal you are not in /training path as if you are already in /training folder than edit path to /to/ssd_inception_v2.config

Thanks

**Comment by okoliechykwuka** [comment]
> Hi Everyone,
> 
> With regards to :-
> 
> tensorflow.python.framework.errors_impl.NotFoundError: training/to/ssd_inception_v2.config
> 
> Make sure in your terminal you are not in /training path as if you are already in /training folder than edit path to /to/ssd_inception_v2.config
> 
> Thanks

I don't understand you description on this issue. It is not really clear to anyone
