### ISSUE TITLE
Incapable of loading a tf v1 model

### ISSUE THREAD

**Issue by Afganitia** [tensorflow/tensorflow#65945]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.16.1

### Custom code

Yes

### OS platform and distribution

Windows 10

### Python version

3.12

### Current behavior?

I expected tf to load the model (it is a v1 model, but in theory this is houw you should load them?).

Model in question: https://drive.google.com/file/d/1TnN1j34owIPMyi7gRZJO3UAwZhNtXQ9i/view?usp=drive_link

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import os

# Define the path to the directory
directory_path = r"D:\Admin\Documents\Universitat\UdG\TFM\Modelos\trn-_cnn_random__random_sp_gpu-cnn_for_random_pfam-5356760"

# Print the contents of the directory
print("Contents of the directory:")
for item in os.listdir(directory_path):
    print(item)

# Define the correct path to the SavedModel directory
saved_model_path = r"D:\Admin\Documents\Universitat\UdG\TFM\Modelos\trn-_cnn_random__random_sp_gpu-cnn_for_random_pfam-5356760\saved_model.pb"

# Load the SavedModel
loaded_model = tf.saved_model.load(saved_model_path)
```

### Relevant log output

```shell
C:\Python312\python.exe C:\Users\Admin\AppData\Roaming\JetBrains\PyCharmCE2024.1\scratches\scratch.py 
2024-04-17 18:44:10.129957: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-04-17 18:44:11.239742: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Contents of the directory:
saved_model.pb
variables
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\JetBrains\PyCharmCE2024.1\scratches\scratch.py", line 16, in <module>
    loaded_model = tf.saved_model.load(saved_model_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\tensorflow\python\saved_model\load.py", line 912, in load
    result = load_partial(export_dir, None, tags, options)["root"]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\tensorflow\python\saved_model\load.py", line 1016, in load_partial
    loader_impl.parse_saved_model_with_debug_info(export_dir))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\tensorflow\python\saved_model\loader_impl.py", line 59, in parse_saved_model_with_debug_info
    saved_model = parse_saved_model(export_dir)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\tensorflow\python\saved_model\loader_impl.py", line 119, in parse_saved_model
    raise IOError(
OSError: SavedModel file does not exist at: D:\Admin\Documents\Universitat\UdG\TFM\Modelos\trn-_cnn_random__random_sp_gpu-cnn_for_random_pfam-5356760\saved_model.pb\{saved_model.pbtxt|saved_model.pb}

Process finished with exit code 1
```

**Comment by sushreebarsa** [comment]
@Afganitia Could you please consider upgrading your TF v1 model to TF2 format. Please refer to [this](https://www.tensorflow.org/guide/migrate/upgrade) guide for migration. 
Thank you!
