### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by KeithYin** [tensorflow/tensorflow#6598]
i have encounter an type error issue, and tried `import sys; reload(sys); sys.setdefaultencoding('UTF8')`.but i didn't work.
here is the detail
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so.8.0 locally
E tensorflow/core/framework/op_kernel.cc:925] OpKernel ('op: "NegTrain" device_type: "CPU"') for unknown op: NegTrain
E tensorflow/core/framework/op_kernel.cc:925] OpKernel ('op: "Skipgram" device_type: "CPU"') for unknown op: Skipgram
Traceback (most recent call last):
  File "Model_Multi_Gpu.py", line 371, in <module>
    tf.app.run()
  File "/home/rootuser/.virtualenvs/tfrc1py2/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "Model_Multi_Gpu.py", line 355, in main
    model = Model(train_scope,4)
  File "Model_Multi_Gpu.py", line 85, in __init__
    avaraged_grads = self.avg_grads()
  File "Model_Multi_Gpu.py", line 91, in avg_grads
    averaged_grads.append(tf.reduce_mean(grads_per_var))
  File "/home/rootuser/.virtualenvs/tfrc1py2/local/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 1329, in reduce_mean
    _ReductionDims(input_tensor, axis, reduction_indices),
  File "/home/rootuser/.virtualenvs/tfrc1py2/local/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 1178, in _ReductionDims
    return range(0, array_ops.rank(x))
  File "/home/rootuser/.virtualenvs/tfrc1py2/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 342, in rank
    return rank_internal(input, name, optimize=True)
  File "/home/rootuser/.virtualenvs/tfrc1py2/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 362, in rank_internal
    input_tensor = ops.convert_to_tensor(input)
  File "/home/rootuser/.virtualenvs/tfrc1py2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 645, in convert_to_tensor
    as_ref=False)
  File "/home/rootuser/.virtualenvs/tfrc1py2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 710, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/rootuser/.virtualenvs/tfrc1py2/local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/rootuser/.virtualenvs/tfrc1py2/local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/rootuser/.virtualenvs/tfrc1py2/local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 441, in make_tensor_proto
    tensor_proto.string_val.extend([compat.as_bytes(x) for x in proto_values])
  File "/home/rootuser/.virtualenvs/tfrc1py2/local/lib/python2.7/site-packages/tensorflow/python/util/compat.py", line 65, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got <tensorflow.python.framework.ops.IndexedSlices object at 0x7fa82ab1cf50>

what should i do to correct it? thanks a lot

**Comment by inflation** [comment]
What you have is a TensorFlow op, so maybe you can run it and get the value.

**Comment by yaroslavvb** [comment]
This doesn't seem like a feature request or a bug in TensorFlow, could you repost this on stackoverflow instead with tensorflow tag? That tag is monitored by TF team and many volunteers
