### ISSUE TITLE
`histogram_fixed_width` type errors and GPU issues

### ISSUE THREAD

**Issue by willcrichton** [tensorflow/tensorflow#6650]
With the following script:

```python
import tensorflow as tf

with tf.device('/gpu:0'):
    image = tf.zeros([200, 200, 3], dtype=tf.int32)
    hist_range = tf.constant([0, 255], dtype=tf.int32)
    hist = histogram_fixed_width(image, hist_range, nbins=16, dtype=tf.int32)

with tf.Session() as sess:
    sess.run(hist)
```

Gives the following error:

```
Traceback (most recent call last):
  File "hist.py", line 5, in <module>
    hist = tf.histogram_fixed_width(image, hist_range, nbins=16, dtype=tf.int32)
  File "/home/wcrichto/.env/local/lib/python2.7/site-packages/tensorflow/python/ops/histogram_ops.py", line 84, in histogram_fixed_width
    indices = math_ops.floor(nbins_float * scaled_values, name='indices')
  File "/home/wcrichto/.env/local/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 805, in binary_op_wrapper
    y = ops.convert_to_tensor(y, dtype=x.dtype.base_dtype, name="y")
  File "/home/wcrichto/.env/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 651, in convert_to_tensor
    as_ref=False)
  File "/home/wcrichto/.env/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 716, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/wcrichto/.env/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 589, in _TensorTensorConversionFunction
    % (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype float32 for Tensor with dtype float64: 'Tensor("histogram_fixed_width/scaled_values:0", shape=(120000,), dtype=float64)'
```

I believe the issue here is this line: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/histogram_ops.py#L75

It should say `to_double` instead of `to_float`. However, even if you fix this, you then get this error: 

```
Caused by op u'histogram_fixed_width', defined at:
  File "hist.py", line 79, in <module>
    hist = histogram_fixed_width(image, hist_range, nbins=16, dtype=tf.int32)
  File "hist.py", line 74, in histogram_fixed_width
    name=scope)
  File "/home/wcrichto/.env/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 2952, in unsorted_segment_sum
    num_segments=num_segments, name=name)
  File "/home/wcrichto/.env/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/wcrichto/.env/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2392, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/wcrichto/.env/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Cannot assign a device to node 'histogram_fixed_width': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
	 [[Node: histogram_fixed_width = UnsortedSegmentSum[T=DT_INT32, Tindices=DT_INT32, _device="/device:GPU:0"](histogram_fixed_width/ones_like, histogram_fixed_width/Cast, histogram_fixed_width/nbins)]]
```

I ran this both with the TF version from `pip install tensorflow-gpu` as well as when building from source with `--config=cuda` and got this error. However, the source makes it seem like this should work: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/segment_reduction_ops.cc#L323

**Comment by michaelisard** [comment]
@sherrym can you see what's going wrong here?

**Comment by fab-jul** [comment]
I have the same issue. For me, the following work-around helps for now: cast the first two arguments of `tf.histogram_fixed_width` to `float32`.

**Comment by gunan** [comment]
Automatically closing due to recent activity.
Please feel free to reopen if this is still an issue.
You can also send a pull request fixing the problem, if you have a proposed fix.

**Comment by fab-jul** [comment]
This is still an issue in TF 1.2
