### ISSUE TITLE
Initialize variable failure when importing graph_def

### ISSUE THREAD

**Issue by DjangoPeng** [tensorflow/tensorflow#6653]
In r0.12, I'm trying to write a graph_def at local and import it in another server. But when I `session.run(a)` after `session.run(global_variables_initializer())`, it raises a `FailedPreconditionError: Attempting to use uninitialized value a` .

### Write graph
```python
import tensorflow as tf

a = tf.Variable(1, name='a', dtype=tf.int32)
b = tf.Variable(2, name='b', dtype=tf.int32)
c = a + b
d = tf.Variable(c, name='d', dtype=tf.int32)
sess = tf.Session()
tf.train.write_graph(sess.graph, /tmp/PJT', 'test.pb', as_text=False)
```
### Import graph
```python
import tensorflow as tf
from tensorflow.core.framework import graph_pb2

graph_pb = '/home/mind/PJT/test.pb'
graph_def = graph_pb2.GraphDef()

with open(graph_pb, 'rb') as f:
    graph_def.ParseFromString(f.read())

tf.import_graph_def(graph_def, name='')
sess = tf.Session()
a = sess.graph.get_tensor_by_name('a:0')
sess.run(tf.global_variables_initializer())
sess.run(a)
```
### Error log
```
FailedPreconditionErrorTraceback (most recent call last)
<ipython-input-43-574ff7291e3a> in <module>()
      2 a = sess.graph.get_tensor_by_name('a:0')
      3 sess.run(tf.global_variables_initializer())
----> 4 sess.run(a)

/home/mind/anaconda2/envs/tf_0.12/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in run(self, fetches, feed_dict, options, run_metadata)
    764     try:
    765       result = self._run(None, fetches, feed_dict, options_ptr,
--> 766                          run_metadata_ptr)
    767       if run_metadata:
    768         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/home/mind/anaconda2/envs/tf_0.12/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _run(self, handle, fetches, feed_dict, options, run_metadata)
    962     if final_fetches or final_targets:
    963       results = self._do_run(handle, final_targets, final_fetches,
--> 964                              feed_dict_string, options, run_metadata)
    965     else:
    966       results = []

/home/mind/anaconda2/envs/tf_0.12/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1012     if handle is None:
   1013       return self._do_call(_run_fn, self._session, feed_dict, fetch_list,
-> 1014                            target_list, options, run_metadata)
   1015     else:
   1016       return self._do_call(_prun_fn, self._session, handle, feed_dict,

/home/mind/anaconda2/envs/tf_0.12/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _do_call(self, fn, *args)
   1032         except KeyError:
   1033           pass
-> 1034       raise type(e)(node_def, op, message)
   1035 
   1036   def _extend_graph(self):

FailedPreconditionError: Attempting to use uninitialized value a
	 [[Node: _send_a_0 = _Send[T=DT_INT32, client_terminated=true, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=784291433964173963, tensor_name="a:0", _device="/job:localhost/replica:0/task:0/cpu:0"](a)]]
```

@mrry Could you have a look?

**Comment by zakizhou** [comment]
Maybe this will work:
add `init` op(like `tf.global_variables_initializer`) to the original graph, and in the second graph import the original one and get this `init` op with `graph.get_operation_by_name` and run the op with `sess.run(init)`

**Comment by DjangoPeng** [comment]
@zakizhou Thanks for your advice. I tried it, and got some interesting and unreasonable results.
### Write graph
```python
import tensorflow as tf
a = tf.Variable(1, name='a', dtype=tf.int32)
b = tf.Variable(2, name='b', dtype=tf.int32)
init_op = tf.global_variables_initializer() 
sess = tf.Session()
tf.train.write_graph(sess.graph, '/tmp/PJT', 'test.pb', as_text=False)
```
### Import graph
```python
import tensorflow as tf
from tensorflow.core.framework import graph_pb2

graph_pb = '/tmp/PJT/test.pb'
graph_def = graph_pb2.GraphDef()
with open(graph_pb, 'rb') as f:
    graph_def.ParseFromString(f.read())
tf.import_graph_def(graph_def, name='')
sess = tf.Session()
a = sess.graph.get_tensor_by_name('a:0')
d = sess.graph.as_graph_element('d:0')
init_op = sess.graph.get_operation_by_name('init')

sess.run(init_op)
sess.run(a)
```
At first time I run the `import graph` snippet, it raise same error as below:
```
FailedPreconditionError: Attempting to use uninitialized value b
	 [[Node: b/read = Identity[T=DT_INT32, _class=["loc:@b"], _device="/job:localhost/replica:0/task:0/cpu:0"](b)]]
	 [[Node: b/Assign/_12 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_14_b/Assign", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'b/read', defined at:
  File "/home/mind/anaconda2/envs/tf_0.12/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/mind/anaconda2/envs/tf_0.12/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/mind/anaconda2/envs/tf_0.12/lib/python2.7/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/home/mind/anaconda2/envs/tf_0.12/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/mind/anaconda2/envs/tf_0.12/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 474, in start
    ioloop.IOLoop.instance().start()
  File "/home/mind/anaconda2/envs/tf_0.12/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/home/mind/anaconda2/envs/tf_0.12/lib/python2.7/site-packages/tornado/ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "/home/mind/anaconda2/envs/tf_0.12/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/mind/anaconda2/envs/tf_0.12/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/home/mind/anaconda2/envs/tf_0.12/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/mind/anaconda2/envs/tf_0.12/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/home/mind/anaconda2/envs/tf_0.12/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/mind/anaconda2/envs/tf_0.12/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/mind/anaconda2/envs/tf_0.12/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/mind/anaconda2/envs/tf_0.12/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "/home/mind/anaconda2/envs/tf_0.12/lib/python2.7/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/mind/anaconda2/envs/tf_0.12/lib/python2.7/site-packages/ipykernel/zmqshell.py", line 501, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/mind/anaconda2/envs/tf_0.12/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/mind/anaconda2/envs/tf_0.12/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2827, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/mind/anaconda2/envs/tf_0.12/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-e62bd92e6511>", line 1, in <module>
    tf.import_graph_def(graph_def, name='')
  File "/home/mind/anaconda2/envs/tf_0.12/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 285, in import_graph_def
    op_def=op_def)
  File "/home/mind/anaconda2/envs/tf_0.12/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2240, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/mind/anaconda2/envs/tf_0.12/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value b
	 [[Node: b/read = Identity[T=DT_INT32, _class=["loc:@b"], _device="/job:localhost/replica:0/task:0/cpu:0"](b)]]
	 [[Node: b/Assign/_12 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_14_b/Assign", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
```

The most unreasonable thing is when I separately run `sess.run(init_op)` again, everything goes well. I don't know why it works, and I think you can reproduce it.

**Comment by zakizhou** [comment]
@DjangoPeng Personally I seldom use low level functions like `tf.import_graph_def`, instead I use `tf.train.import_meta_graph`(which internelly calls `import_graph_def`), especially after v0.12, this funtion supports much more things than before like changing the inputs of the original graph and will do all the dirty work for you including import graph def and restore variables from checkpoints.

**Comment by DjangoPeng** [comment]
@zakizhou I had a try of [tf.train.import_meta_graph](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/api_docs/python/functions_and_classes/shard8/tf.train.import_meta_graph.md), and I always restore fail. Could you show me a use case? I attached my test snippet below:
### Save model
```python
import tensorflow as tf
a = tf.Variable(1, name='a', dtype=tf.int32)
b = tf.Variable(2, name='b', dtype=tf.int32)
c = a + b
init_op = tf.global_variables_initializer() 
saver = tf.train.Saver(tf.trainable_variables())
sess = tf.Session()
sess.run(init_op)  #  I have to run it twice times to avoid the same error above.
sess.run(d)
saver.save(sess, '/tmp/PJT/model-0')
```
Then I get the model file as below:
```
model-0.meta
model-0.index
model-0.data-00000-of-00001
```
### Restore model
```python
import tensorflow as tf
with tf.Session() as sess:
    new_saver = tf.train.import_meta_graph('/home/mind/PJT/model-0.meta')
    new_saver.restore(sess, 'model-0.data-00000-of-00001') # It raise NotFoundError
```
Error log:
```
NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model-0.data-00000-of-00001
...
```

**Comment by zakizhou** [comment]
change `new_saver.restore(sess, 'model-0.data-00000-of-00001')` to `new_saver.restore(sess, 'model-0')` and have a try

**Comment by DjangoPeng** [comment]
It raises the same NotFoundError.

**Comment by a574824551** [comment]
try this:
```python
gd = sess.graph.as_graph_def()
for node in gd.node:
    if node.op == 'RefSwitch':
        node.op = 'Switch'
        for index in range(len(node.input)):
            if 'moving_' in node.input[index]:
                node.input[index] = node.input[index] + '/read'
    elif node.op == 'AssignSub':
        node.op = 'Sub'
        if 'use_locking' in node.attr: del node.attr['use_locking']
    elif node.op == 'AssignAdd':
        node.op = 'Add'
        if 'use_locking' in node.attr: del node.attr['use_locking']

constant_graph = graph_util.convert_variables_to_constants(sess, gd, ['output_res'])
with tf.gfile.FastGFile('./pb_model/model.pb', mode='wb') as f:
    f.write(constant_graph.SerializeToString())
```

ref: https://github.com/davidsandberg/facenet/issues/161
