### ISSUE TITLE
stuck at installing tensorflow

### ISSUE THREAD

**Issue by yogashreeNaik** [tensorflow/tensorflow#67067]
Traceback (most recent call last):
  File "C:\Users\AVITA\anaconda3\envs\myEnv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AVITA\Desktop\Yogashree\pyprojects\test.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\AVITA\anaconda3\envs\myEnv\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\AVITA\anaconda3\envs\myEnv\lib\site-packages\tensorflow\python\__init__.py", line 36, in <module>       
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "C:\Users\AVITA\anaconda3\envs\myEnv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 77, in <module>
    raise ImportError(
ImportError: Traceback (most recent call last):
  File "C:\Users\AVITA\anaconda3\envs\myEnv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.

**Comment by yogashreeNaik** [comment]
> Hi **@yogashreeNaik** ,
> 
> * Could you check the version of tensorflow you are using is compatible with your system and python environment.
> * Ensure that all necessary system dependencies, such as CUDA and cuDNN for GPU support, are correctly installed and compatible with your TensorFlow version.
> * Try reinstalling TensorFlow in your virtual environment, By using pip:
> 
> ```
> pip uninstall tensorflow
> pip install tensorflow
> ```
> 
> Thank you!

I'll it . Thank you..

**Comment by Venkat6871** [comment]
Hi @yogashreeNaik ,
- Could you please confirm if this issue is resolved for you ? Please feel free to close the issue.

Thank you!

**Comment by yogashreeNaik** [comment]
> Hi @yogashreeNaik ,
> 
> * Could you please confirm if this issue is resolved for you ? Please feel free to close the issue.
> 
> Thank you!

Yeah, it's resolved now, thank you!!
