### ISSUE TITLE
problem with converted custom model at TensorFlow Lite

### ISSUE THREAD

**Issue by rkdtmdals7710** [tensorflow/tensorflow#67086]
I created a tflite model from yolov5n  [export.py -- weights mymodel.pt -- include tflite] for the learning model I learned from yolov5n. By the way, /home/pi1/Desktop/project3/examples/lite/examples/object_detection/raspberry_pi. It works fine when I run the existing detect.py , but when I use the above model, I get the following error. 

(0507) pi1@raspberrypi:~/Desktop/project3/examples/lite/examples/object_detection/raspberry_pi $ python detect.py --model mymodel.tflite
Traceback (most recent call last):
  File "detect.py", line 15, in <module>
    import tensorflow_io as tfio
  File "/home/pi1/miniconda3/envs/0507/lib/python3.7/site-packages/tensorflow_io/__init__.py", line 17, in <module>
    from tensorflow_io.python.api import *  # pylint: disable=wildcard-import
  File "/home/pi1/miniconda3/envs/0507/lib/python3.7/site-packages/tensorflow_io/python/api/__init__.py", line 19, in <module>
    from tensorflow_io.python.ops.io_dataset import IODataset
  File "/home/pi1/miniconda3/envs/0507/lib/python3.7/site-packages/tensorflow_io/python/ops/__init__.py", line 24, in <module>
    import tensorflow as tf
  File "/home/pi1/miniconda3/envs/0507/lib/python3.7/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/pi1/miniconda3/envs/0507/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "/home/pi1/miniconda3/envs/0507/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 28, in <module>
    from tensorflow.core.framework import function_pb2
  File "/home/pi1/miniconda3/envs/0507/lib/python3.7/site-packages/tensorflow/core/framework/function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/home/pi1/miniconda3/envs/0507/lib/python3.7/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/home/pi1/miniconda3/envs/0507/lib/python3.7/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/home/pi1/miniconda3/envs/0507/lib/python3.7/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "/home/pi1/miniconda3/envs/0507/lib/python3.7/site-packages/tensorflow/core/framework/tensor_shape_pb2.py", line 42, in <module>
    serialized_options=None, file=DESCRIPTOR),
  File "/home/pi1/miniconda3/envs/0507/lib/python3.7/site-packages/google/protobuf/descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

When I downgrade protobuf, I get the following error. Please solve the problem.

(0507) pi1@raspberrypi:~/Desktop/project3/examples/lite/examples/object_detection/raspberry_pi $ python detect.py --model mymodel.tflite
/home/pi1/miniconda3/envs/0507/lib/python3.7/site-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/home/pi1/miniconda3/envs/0507/lib/python3.7/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ['/home/pi1/miniconda3/envs/0507/lib/python3.7/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so: undefined symbol: _ZN10tensorflow8internal15LogMessageFatalC1EPKci']
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/home/pi1/miniconda3/envs/0507/lib/python3.7/site-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: libtensorflow_io.so, from paths: ['/home/pi1/miniconda3/envs/0507/lib/python3.7/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']
caused by: ['/home/pi1/miniconda3/envs/0507/lib/python3.7/site-packages/tensorflow_io/python/ops/libtensorflow_io.so: undefined symbol: _ZN10tensorflow4data11DatasetBase8FinalizeEPNS_15OpKernelContextESt8functionIFNS_8StatusOrISt10unique_ptrIS1_NS_4core15RefCountDeleterEEEEvEE']
  warnings.warn(f"file system plugins are not loaded: {e}")
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Traceback (most recent call last):
  File "detect.py", line 152, in <module>
    main()
  File "detect.py", line 148, in main
    int(args.numThreads), bool(args.enableEdgeTPU))
  File "detect.py", line 65, in run
    detector = vision.ObjectDetector.create_from_options(options)
  File "/home/pi1/miniconda3/envs/0507/lib/python3.7/site-packages/tensorflow_lite_support/python/task/vision/object_detector.py", line 91, in create_from_options
    options.base_options.to_pb2(), options.detection_options.to_pb2())
RuntimeError: Input tensor has type kTfLiteFloat32: it requires specifying NormalizationOptions metadata to preprocess input images.

**Comment by sushreebarsa** [comment]
@rkdtmdals7710 For such issues the recommended solution is to upgrade your protobuf to version 3.19.0 or later. You can usually do this using your package manager (e.g., `pip install --upgrade protobuf`).
Also please verify the TensorFlow IO Installation,

```
pip install tensorflow-io
import tensorflow_io as tfio
print(tfio.__version__)


```
Thank you!
