### ISSUE TITLE
Installed succesfully, but went wrong and outputed  ‘undefined symbol: zgelsd_’ when testing

### ISSUE THREAD

**Issue by MichaelLiang12** [tensorflow/tensorflow#6712]
### Environment info
Operating System: Ubuntu14.04, python3.4.3

**I installed tensorflow using pip3 succesfully** from https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-0.12.1-cp34-cp34m-linux_x86_64.whl

**When I tried to test it using offical test code, it went wrong as follows:**
/usr/bin/python3.4 /home/daisy/PycharmProjects/miachaelLiang/test_tensorflow.py
Traceback (most recent call last):
  File "/home/daisy/PycharmProjects/miachaelLiang/test_tensorflow.py", line 9, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/__init__.py", line 44, in <module>
    import numpy as np
  File "/usr/local/lib/python3.4/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/local/lib/python3.4/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/local/lib/python3.4/dist-packages/numpy/lib/__init__.py", line 18, in <module>
    from .polynomial import *
  File "/usr/local/lib/python3.4/dist-packages/numpy/lib/polynomial.py", line 20, in <module>
    from numpy.linalg import eigvals, lstsq, inv
  File "/usr/local/lib/python3.4/dist-packages/numpy/linalg/__init__.py", line 51, in <module>
    from .linalg import *
  File "/usr/local/lib/python3.4/dist-packages/numpy/linalg/linalg.py", line 29, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg
### ImportError:
 **/usr/local/lib/python3.4/dist-packages/numpy/linalg/lapack_lite.cpython-34m.so: undefined symbol: zgelsd_**

**Comment by martinwicke** [comment]
This looks to me like your numpy installation is broken. Numpy appears installed by linked incorrectly to lapack. Not much we can do about this in TensorFlow.
