### ISSUE TITLE
tf.map_fn throws error...sometimes.... 

### ISSUE THREAD

**Issue by usmcamp0811** [tensorflow/tensorflow#6730]
### Environment info
Operating System: Ubuntu 16.04

Installed version of CUDA and cuDNN: 
	libcudart.so.8.0 (libc6,x86-64) => /usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudart.so.8.0
	libcudart.so.7.5 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcudart.so.7.5
	libcudart.so (libc6,x86-64) => /usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudart.so
	libcudart.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcudart.so
	libcuda.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcuda.so.1
	libcuda.so.1 (libc6) => /usr/lib/i386-linux-gnu/libcuda.so.1
	libcuda.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcuda.so
	libcuda.so (libc6) => /usr/lib/i386-linux-gnu/libcuda.so

pip install tensorflow-gpu
 0.12.0-rc1

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
I posted to the below stackoverflow link with some code and my initial problem that I mostly fixed, but it does seem that there is a problem with the tf.map_fn()
http://stackoverflow.com/questions/41534866/image-distortion-returns-error-the-tensor-returned-for-reshape-50-was-not-vali/41536952?noredirect=1#comment70281037_41536952 

I was trying to use tf.map_fn to distort a batch of images and it throws an error sometimes... the batch starts its life as a TFRecords file of flat images. The batch is turned into 4d tensor by tf.reshape then put through tf.map_fn(image distortion function) and then reshaped back into a flat 2d tensor. Most of the time I get a reshape error but not all the time. The times I don't get the error, the code will run for all epochs...

`/home/mcamp/anaconda3/bin/python "/media/mcamp/Local SSHD/Python Projects/GarageDoor2/train_model.py"
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 960
major: 5 minor: 2 memoryClockRate (GHz) 1.342
pciBusID 0000:01:00.0
Total memory: 3.94GiB
Free memory: 2.53GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 960, pci bus id: 0000:01:00.0)
*
Traceback (most recent call last):
  File "/home/mcamp/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1021, in _do_call
    return fn(*args)
  File "/home/mcamp/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1003, in _run_fn
    status, run_metadata)
  File "/home/mcamp/anaconda3/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/mcamp/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: The tensor returned for Reshape_3:0 was not valid.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/mcamp/Local SSHD/Python Projects/GarageDoor2/train_model.py", line 44, in <module>
    model.train(training_data, epochs=FLAGS.n_epochs)
  File "/media/mcamp/Local SSHD/Python Projects/GarageDoor2/ConvNetClass.py", line 190, in train
    training_data_dict['y_train_batch']]) #4
  File "/home/mcamp/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/home/mcamp/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "/home/mcamp/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "/home/mcamp/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: The tensor returned for Reshape_3:0 was not valid.`

**Comment by yaroslavvb** [comment]
Could you give instructions on how to reproduce this?

**Comment by usmcamp0811** [comment]
`   
def read_and_decode(filename_queue,imshape=160*160*3):
    reader = tf.TFRecordReader()
    _, serialized_example = reader.read(filename_queue)
    features = tf.parse_single_example(
        serialized_example,
        features={
            'image_raw': tf.FixedLenFeature([], tf.string),
            'label': tf.FixedLenFeature([], tf.int64),
            'height': tf.FixedLenFeature([], tf.int64),
            'width': tf.FixedLenFeature([], tf.int64),
            'depth': tf.FixedLenFeature([], tf.int64)
        })

    image = tf.decode_raw(features['image_raw'], tf.uint8)
    image.set_shape([imshape])
    image = tf.cast(image, tf.float32)

    label = tf.cast(features['label'], tf.int32)

    return image, label


def inputs(train_dir, file, batch_size, num_epochs, n_classes, one_hot_labels=False, imshape=160*160*3):

    if not num_epochs: num_epochs = None
    filename = os.path.join(train_dir, file)

    # with tf.name_scope('input'):
    filename_queue = tf.train.string_input_producer(
        [filename], num_epochs=num_epochs)

    image, label = read_and_decode(filename_queue, imshape)

    if one_hot_labels:
        label = tf.one_hot(label, n_classes, dtype=tf.int32)

    example_batch, label_batch = tf.train.shuffle_batch(
        [image, label], batch_size=batch_size, num_threads=2,
        capacity=1000, enqueue_many=False,
        # Ensures a minimum amount of shuffling of examples.
        min_after_dequeue=10, name=file)

    return example_batch, label_batch

 def random_distorer(self, image):
        image = tf.image.random_brightness(image, max_delta=32. / 255.)
        image = tf.image.random_saturation(image, lower=0.5, upper=1.5)
        image = tf.image.random_hue(image, max_delta=0.2)
        image = tf.image.random_contrast(image, lower=0.5, upper=1.5)
        image = tf.image.random_flip_up_down(image)
        image = tf.image.random_flip_left_right(image)
        return image`

`    def train(self, training_data_dict, epochs=500, distort=True):
        self.training_data_dict = training_data_dict # a dictionary of image batch queues
        distorted_image = tf.reshape(training_data_dict['X_train_batch'], [-1, 160, 160, 3]) #1
        if distort is True:
            distorted_image = tf.map_fn(lambda img: self.random_distorer(img), distorted_image) #2
        distorted_image = tf.reshape(distorted_image, [-1, 76800])  # 3
        for epoch in range(epochs):
            x_test, y_test = self.sess.run([training_data_dict['X_test_batch'], training_data_dict['y_test_batch']])
            distortedX, x_train, y_train = self.sess.run([distorted_image, training_data_dict['X_train_batch'],
                                                          training_data_dict['y_train_batch']]) #4
            if epoch%300 == 0:
                if self.distort is True:
                    print('Distorting color in training images...')
                distortedX, x_train, y_train = self.sess.run([distorted_image, training_data_dict['X_train_batch'],
                                                              training_data_dict['y_train_batch']])
                summary, loss, train_accuracy = self.sess.run([self.merged, self.train_step, self.accuracy], feed_dict={
                    self.x: distortedX, self.y_: y_train, self.keep_prob: self.dropout})
                print("Step %d, Distorted Training accuracy %g" % (epoch, train_accuracy))
            else:
                summary, loss, train_accuracy = self.sess.run([self.merged, self.train_step, self.accuracy], feed_dict={
                    self.x: x_train, self.y_: y_train, self.keep_prob: self.dropout})
                if epoch%100 == 0:
                    print("Step %d, Training accuracy %g" % (epoch, train_accuracy))
                self.train_writer.add_summary(summary, epoch)
            if epoch%100 == 0:
                summary, test_accuracy = self.sess.run([self.merged, self.accuracy], feed_dict={
                    self.x: x_test, self.y_: y_test, self.keep_prob: 1.0})
                print("Test Accuracy %g"% test_accuracy)
                self.test_writer.add_summary(summary, epoch)
            if epoch%500 == 0:
                print('Saving model...')
                self.saver.save(self.sess, self.model_dir+'model.ckpt', epoch)
            if epoch == epochs:
                print('Saving model...')
                self.saver.save(self.sess, self.model_dir+'model.ckpt', epoch)


training_data = dict()
training_data['X_train_batch'], training_data['y_train_batch'] = inputs(FLAGS.train_dir,
                                                                  FLAGS.train_file,
                                                                  FLAGS.batch_size,
                                                                  FLAGS.n_epochs,
                                                                  FLAGS.n_classes,
                                                                  one_hot_labels=True,
                                                                  imshape=76800)


training_data['X_test_batch'], training_data['y_test_batch'] = inputs(FLAGS.train_dir,
                                                                FLAGS.test_file,
                                                                FLAGS.batch_size,
                                                                FLAGS.n_epochs,
                                                                FLAGS.n_classes,
                                                                one_hot_labels=True,
                                                                imshape=76800)

network_architecture = dict(W_conv1=[5, 5, 3, 25],
                            W_conv2=[5, 5, 25, 50],
                            W_fc1=[40 * 40 * 50, 1024],
                            W_fc2=[1024, 2])

model = BasicConvNet(76800, 2, network_architecture, batch_size=30,
                     imshape=(160,160,3), dropout=0.5, model_dir='./modeltest/', histograms=False)
model.train(training_data, epochs=FLAGS.n_epochs, distort=True)
`

More or less thats the code.. sorry to throw a ton of code on here.. I'm still pretty much a novice and if I did something wrong elsewhere didn't want to send anyone on a wild goose hunt. But like I said it runs about a quarter of the time no problem.. so I don't think its entirely me..

**Comment by yaroslavvb** [comment]
Hm, I think this needs a bit more isolation/reproducible instructions before being actionable as a bug

**Comment by yaroslavvb** [comment]
One thing I see here -- you are potentially modifying the same Graph from different threads. However, Graph object is not thread safe for writing from multiple threads. Also I'm not sure you need `map_fn` here, if you need `k` different random distorters, you can call your `random_distorter` function several times and resulting tensors will give you different distortions on each session run

**Comment by jart** [comment]
Closing due to seven days of no activity. If provided new information, I will re-open.
