### ISSUE TITLE
 Run tutorials convolutional.py,  resource exhausted: OOM

### ISSUE THREAD

**Issue by gotope** [tensorflow/tensorflow#676]
My PC has Nvidia GTX960 2G memory, while run the convolutional.py of tutorials failed,
the tensorflow version is 0.6,  need some modify on  convolutional.py?

$ cd tensorflow/models/image/mnist
$ python convolutional.py
Minibatch loss: 0.739, learning rate: 0.006302
Minibatch error: 0.0%
Validation error: 2.0%
Epoch 9.84
......
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:403]      Summary of in-use Chunks by size: 
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:406] 28 Chunks of size 256 totalling 7.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:406] 1 Chunks of size 1280 totalling 1.2KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:406] 4 Chunks of size 2048 totalling 8.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:406] 3 Chunks of size 3328 totalling 9.8KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:406] 3 Chunks of size 20480 totalling 60.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:406] 1 Chunks of size 100352 totalling 98.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:406] 3 Chunks of size 204800 totalling 600.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:406] 1 Chunks of size 1605632 totalling 1.53MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:406] 1 Chunks of size 4941824 totalling 4.71MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:406] 3 Chunks of size 6422528 totalling 18.38MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:406] 1 Chunks of size 13302272 totalling 12.69MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:406] 1 Chunks of size 31360000 totalling 29.91MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:406] 1 Chunks of size 1636141568 totalling 1.52GiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:410] Sum Total of in-use chunks: 1.59GiB
W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:166] Ran out of memory trying to allocate 39.06MiB.  See logs for memory state
W tensorflow/core/kernels/conv_ops.cc:288] Resource exhausted: OOM when allocating tensor with shapedim { size: 10000 } dim { size: 32 } dim { size: 32 } dim { size: 1 }
W tensorflow/core/common_runtime/executor.cc:1076] 0x5a5c0d0 Compute status: Resource exhausted: OOM when allocating tensor with shapedim { size: 10000 } dim { size: 32 } dim { size: 32 } dim { size: 1 }
	 [[Node: Conv2D_4 = Conv2D[T=DT_FLOAT, padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](Const_1, Variable/read)]]
W tensorflow/core/common_runtime/executor.cc:1076] 0x62eaae0 Compute status: Resource exhausted: OOM when allocating tensor with shapedim { size: 10000 } dim { size: 32 } dim { size: 32 } dim { size: 1 }
	 [[Node: Conv2D_4 = Conv2D[T=DT_FLOAT, padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](Const_1, Variable/read)]]
	 [[Node: Softmax_2/_53 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_753_Softmax_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/image/mnist/convolutional.py", line 292, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/image/mnist/convolutional.py", line 283, in main
    test_error = error_rate(test_prediction.eval(), test_labels)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 460, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2910, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 368, in run
    results = self._do_run(target_list, unique_fetch_targets, feed_dict_string)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 444, in _do_run
    e.code)
tensorflow.python.framework.errors.ResourceExhaustedError: OOM when allocating tensor with shapedim { size: 10000 } dim { size: 32 } dim { size: 32 } dim { size: 1 }
	 [[Node: Conv2D_4 = Conv2D[T=DT_FLOAT, padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](Const_1, Variable/read)]]
	 [[Node: Softmax_2/_53 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_753_Softmax_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
Caused by op u'Conv2D_4', defined at:
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/image/mnist/convolutional.py", line 292, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/image/mnist/convolutional.py", line 253, in main
    test_prediction = tf.nn.softmax(model(test_data_node))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/image/mnist/convolutional.py", line 190, in model
    padding='SAME')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 211, in conv2d
    use_cudnn_on_gpu=use_cudnn_on_gpu, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 664, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1834, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1043, in __init__
    self._traceback = _extract_stack()

**Comment by vincentvanhoucke** [comment]
Dupe: https://github.com/tensorflow/tensorflow/issues/609
