### ISSUE TITLE
mnist preload data reader example fails 

### ISSUE THREAD

**Issue by davidslac** [tensorflow/tensorflow#6814]
I am using tensorflow version 12, following the documentation at 

https://www.tensorflow.org/how_tos/reading_data/

which points to the example:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/how_tos/reading_data/fully_connected_preloaded_var.py

however, when I run that example, I get errors about un-initialized variables. Here is the output:

```
python tf_mnist_preload.py 
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Extracting /tmp/data/train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting /tmp/data/train-labels-idx1-ubyte.gz
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting /tmp/data/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting /tmp/data/t10k-labels-idx1-ubyte.gz
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID 0000:87:00.0
Total memory: 11.17GiB
Free memory: 11.11GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:87:00.0)
W tensorflow/core/framework/op_kernel.cc:975] Failed precondition: Attempting to use uninitialized value input/input_producer/input_producer/fraction_of_32_full/limit_epochs/epochs
	 [[Node: input/input_producer/input_producer/fraction_of_32_full/limit_epochs/CountUpTo = CountUpTo[T=DT_INT64, _class=["loc:@input/input_producer/input_producer/fraction_of_32_full/limit_epochs/epochs"], limit=2, _device="/job:localhost/replica:0/task:0/cpu:0"](input/input_producer/input_producer/fraction_of_32_full/limit_epochs/epochs)]]
W tensorflow/core/framework/op_kernel.cc:975] Out of range: FIFOQueue '_1_input/batch/fifo_queue' is closed and has insufficient elements (requested 100, current size 0)
	 [[Node: input/batch = QueueDequeueMany[_class=["loc:@input/batch/fifo_queue"], component_types=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input/batch/fifo_queue, input/batch/n)]]
Saving
Done training for 2 epochs, 0 steps.
Traceback (most recent call last):
  File "tf_mnist_preload.py", line 195, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/davidsch/miniconda2/envs/mlearn/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "tf_mnist_preload.py", line 147, in main
    run_training()
  File "tf_mnist_preload.py", line 142, in run_training
    coord.join(threads)
  File "/home/davidsch/miniconda2/envs/mlearn/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 386, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/davidsch/miniconda2/envs/mlearn/lib/python2.7/site-packages/tensorflow/python/training/queue_runner_impl.py", line 234, in _run
    sess.run(enqueue_op)
  File "/home/davidsch/miniconda2/envs/mlearn/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/home/davidsch/miniconda2/envs/mlearn/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "/home/davidsch/miniconda2/envs/mlearn/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "/home/davidsch/miniconda2/envs/mlearn/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value input/input_producer/input_producer/fraction_of_32_full/limit_epochs/epochs
	 [[Node: input/input_producer/input_producer/fraction_of_32_full/limit_epochs/CountUpTo = CountUpTo[T=DT_INT64, _class=["loc:@input/input_producer/input_producer/fraction_of_32_full/limit_epochs/epochs"], limit=2, _device="/job:localhost/replica:0/task:0/cpu:0"](input/input_producer/input_producer/fraction_of_32_full/limit_epochs/epochs)]]
	 [[Node: input/input_producer/input_producer/fraction_of_32_full/limit_epochs/CountUpTo/_12 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_13_input/input_producer/input_producer/fraction_of_32_full/limit_epochs/CountUpTo", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'input/input_producer/input_producer/fraction_of_32_full/limit_epochs/CountUpTo', defined at:
  File "tf_mnist_preload.py", line 195, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/davidsch/miniconda2/envs/mlearn/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "tf_mnist_preload.py", line 147, in main
    run_training()
  File "tf_mnist_preload.py", line 63, in run_training
    [input_images, input_labels], num_epochs=FLAGS.num_epochs)
  File "/home/davidsch/miniconda2/envs/mlearn/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 305, in slice_input_producer
    shared_name=shared_name)
  File "/home/davidsch/miniconda2/envs/mlearn/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 262, in range_input_producer
    shared_name, name, "fraction_of_%d_full" % capacity)
  File "/home/davidsch/miniconda2/envs/mlearn/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 156, in input_producer
    input_tensor = limit_epochs(input_tensor, num_epochs)
  File "/home/davidsch/miniconda2/envs/mlearn/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 96, in limit_epochs
    counter = epochs.count_up_to(num_epochs)
  File "/home/davidsch/miniconda2/envs/mlearn/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 652, in count_up_to
    return state_ops.count_up_to(self._variable, limit=limit)
  File "/home/davidsch/miniconda2/envs/mlearn/lib/python2.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 126, in count_up_to
    result = _op_def_lib.apply_op("CountUpTo", ref=ref, limit=limit, name=name)
  File "/home/davidsch/miniconda2/envs/mlearn/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "/home/davidsch/miniconda2/envs/mlearn/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2240, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/davidsch/miniconda2/envs/mlearn/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value input/input_producer/input_producer/fraction_of_32_full/limit_epochs/epochs
	 [[Node: input/input_producer/input_producer/fraction_of_32_full/limit_epochs/CountUpTo = CountUpTo[T=DT_INT64, _class=["loc:@input/input_producer/input_producer/fraction_of_32_full/limit_epochs/epochs"], limit=2, _device="/job:localhost/replica:0/task:0/cpu:0"](input/input_producer/input_producer/fraction_of_32_full/limit_epochs/epochs)]]
	 [[Node: input/input_producer/input_producer/fraction_of_32_full/limit_epochs/CountUpTo/_12 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_13_input/input_producer/input_producer/fraction_of_32_full/limit_epochs/CountUpTo", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

```

**Comment by jart** [comment]
@mrry I'm noticing two recent issues about "attempting to use uninitialized value" in the past couple days. Mind taking a look?

See also: https://github.com/tensorflow/tensorflow/issues/6785

**Comment by mrry** [comment]
I suspect this has been broken since 4c85a95925a68fec324f70cd0d7f3d4548f97a38, which made the internal variable in a `tf.train.slice_input_producer()` a local variable, but didn't add any code to initialize the local variables in this example.

Assigning to @ilblackdragon, who made that change.

**Comment by MarkDaoust** [comment]
This is working in both r1.2 and master.
