### ISSUE TITLE
Go: Unable to set shape attributes on operations

### ISSUE THREAD

**Issue by sdeoras** [tensorflow/tensorflow#6833]
Hi TensorFlow/Go team, I am attaching a code snippet that is failing due to the way shape argument is expected.

cc: @asimshankar and referencing [this](https://github.com/tensorflow/tensorflow/issues/10#issuecomment-272461355) discussion

```

package bugs

import (
	tf "github.com/tensorflow/tensorflow/tensorflow/go"
	"github.com/tensorflow/tensorflow/tensorflow/go/op"
	"testing"
)

func TestVarHandleOpShape(t *testing.T) {
	scope := op.NewScope()
	_ = op.VarHandleOp(scope, tf.Int32, []int64{2, 3})
	_, err := scope.Finalize()
	if err != nil {
		t.Fatal(err)
	}
}

/*
=== RUN   TestVarHandleOpShape
--- FAIL: TestVarHandleOpShape (0.00s)
        bugs_test.go:14: failed to add operation "VarHandleOp": AttrValue had value with type 'list(int)' when 'shape' expected
                         for attr 'shape'
                        ; NodeDef: VarHandleOp = VarHandleOp[_class=[], container="", dtype=DT_INT32, shape=[2, 3], shared_name=""](); Op<name=VarHandleOp; signature= -> resource:resource; attr=container:string,default=""; attr=shared_name:string,default=""; attr=dtype:type; attr=shape:shape; is_stateful=true> (Stacktrace: goroutine 6 [running]:
                runtime/debug.Stack(0x0, 0x0, 0x0)
                        /usr/lib/golang/src/runtime/debug/stack.go:24 +0x79
                github.com/tensorflow/tensorflow/tensorflow/go/op.(*Scope).UpdateErr(0xc420012570, 0x51d427, 0xb, 0x79fba0, 0xc420054048)
                        /home/sdeoras/go/src/github.com/tensorflow/tensorflow/tensorflow/go/op/scope.go:113 +0x72
                github.com/tensorflow/tensorflow/tensorflow/go/op.(*Scope).AddOperation(0xc420012570, 0x51d427, 0xb, 0x51d427, 0xb, 0x0, 0x0, 0x0, 0xc4200125a0, 0xc420012540)
                        /home/sdeoras/go/src/github.com/tensorflow/tensorflow/tensorflow/go/op/scope.go:78 +0xf9
                github.com/tensorflow/tensorflow/tensorflow/go/op.VarHandleOp(0xc420012570, 0xc400000003, 0xc4200106e0, 0x2, 0x2, 0x0, 0x0, 0x0, 0x1123b1d4, 0xc420051f78)
                        /home/sdeoras/go/src/github.com/tensorflow/tensorflow/tensorflow/go/op/wrappers.go:14045 +0x27d
                bitbucket.hgst.com/x/tensorflow.git/bugs.TestVarHandleOpShape(0xc4200b8240)
                        /home/sdeoras/go/src/bitbucket.hgst.com/x/tensorflow.git/bugs/bugs_test.go:11 +0x96
                testing.tRunner(0xc4200b8240, 0x52bb48)
                        /usr/lib/golang/src/testing/testing.go:610 +0x81
                created by testing.(*T).Run
                        /usr/lib/golang/src/testing/testing.go:646 +0x2ec
                )
FAIL
exit status 1
FAIL    bitbucket.hgst.com/x/tensorflow.git/bugs        0.134s
*/

```

**Comment by sdeoras** [comment]
Thank you folks. It is working great!
