### ISSUE TITLE
occasional GraphHandle not found error

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#6837]
We occasionally get this error like below on universe-starter-agent. This is on a dedicated box and the code doesn't handle task restarts, so the common scenario doesn't apply . @mrry any idea if there's any way to get this error without a task restart?

https://github.com/openai/universe/issues/112

```
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1021, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1003, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.AbortedError: Graph handle is not found: 000000000000000d

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/experiment/universe-starter-agent/a3c.py", line 92, in run
    self._run()
  File "/experiment/universe-starter-agent/a3c.py", line 101, in _run
    self.queue.put(next(rollout_provider), timeout=600.0)
  File "/experiment/universe-starter-agent/a3c.py", line 139, in env_runner
    summary_writer.add_summary(summary, policy.global_step.eval())
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variables.py", line 515, in eval
    return self._variable.eval(session=session)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 575, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3633, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.AbortedError: Graph handle is not found: 000000000000000d

[2017-01-10 06:27:56,508] Received signal 15: exiting
I tensorflow/core/distributed_runtime/master_session.cc:891] DeregisterGraph error: Aborted: Graph handle is not found: 000000000000002c. Possibly, this worker just restarted.
[2017-01-10 06:27:56,601] Killing and removing container: id=e8bf782d91fa3d6e3bb685e37ed4f9622f054bfb281f1e1e61021f1ed6798a06
```

**Comment by mrry** [comment]
Can you describe the exact setup? I'm not sure what "dedicated box" and "common scenario" mean.

Is it possible that some other  thread could have decided to close the session before that exception was raised? I think if a `close()` and a `run()` issue concurrently, it's possible to see a partially-shut-down state, which would correspond to this error message.

(If no process restarted, I'd be very surprised if this happened, because the sequence of events is:

1. Master calls register graph.
2. Worker receives register graph call.
3. Worker atomically invents a handle and registers it in its `GraphMgr` [(code)](https://github.com/tensorflow/tensorflow/blob/018583b064f40fa1f3cabb7eef0a5ac6b169275d/tensorflow/core/distributed_runtime/graph_mgr.cc#L240).
4. Worker sends handle back to master.
6. Master stores that handle in the `MasterSession`.
7. Later, master attempts to deregister a graph (presumably when closing a session), using the handle it received from the worker.
8. Worker receives deregister graph call.
9. Worker atomically removes the graph associated with the given handle in its `GraphMgr` [(code)](https://github.com/tensorflow/tensorflow/blob/018583b064f40fa1f3cabb7eef0a5ac6b169275d/tensorflow/core/distributed_runtime/graph_mgr.cc#L252).

I suppose it's possible that the DeregisterGraph call could have been retransmitted by gRPC, with the second response taking precedence. Perhaps we should ignore failures from the `DeregisterGraph` RPC.)

**Comment by yaroslavvb** [comment]
Thanks for the explanation! We indeed had threads calling `sess.run` and `sess.close` in parallel
