### ISSUE TITLE
Error when tensorflow installed with conda virtual environment in windows 10

### ISSUE THREAD

**Issue by Qingmu** [tensorflow/tensorflow#6862]
### Environment info
Operating System:
    windows 10

I was trying to install tensorflow in `windows 10` with the guidance of the `readme.md`.
Because the version of `python` in my pc is `2.7.X` which is not compatiable with the guidance as it say  `python version=3.5`. Therefore, I use `conda create --name tensorflow python=3.5` to create a virtual environmnt and install tensorflow.

However, an error occurs:
Traceback (most recent call last):
  File "D:\Program Files\anaconda\envs\tensorflow\Scripts\pip-script.py", line 5, in <module>
    sys.exit(pip.main())
  File "D:\Program Files\anaconda\envs\tensorflow\lib\site-packages\pip\__init__.py", line 249, in main
    return command.main(cmd_args)
  File "D:\Program Files\anaconda\envs\tensorflow\lib\site-packages\pip\basecommand.py", line 252, in main
    pip_version_check(session)
  File "D:\Program Files\anaconda\envs\tensorflow\lib\site-packages\pip\utils\outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "D:\Program Files\anaconda\envs\tensorflow\lib\site-packages\pip\utils\__init__.py", line 838, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "D:\Program Files\anaconda\envs\tensorflow\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 644, in __init__
    self.add_entry(entry)
  File "D:\Program Files\anaconda\envs\tensorflow\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 700, in add_entry
    for dist in find_distributions(entry, True):
  File "D:\Program Files\anaconda\envs\tensorflow\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1949, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "D:\Program Files\anaconda\envs\tensorflow\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "D:\Program Files\anaconda\envs\tensorflow\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1823, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "D:\Program Files\anaconda\envs\tensorflow\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1703, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "D:\Program Files\anaconda\envs\tensorflow\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1643, in load
    mtime = os.stat(path).st_mtime
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'D:\\Program Files\\anaconda\\envs\\tensorflow\\lib\\site-packages\\setuptools-27.2.0-py3.5.egg'

Besides, the ananconda is installed in `'D:\\Program Files\\anaconda`, while there is no file folder `D:\\Program Files\\anaconda\\envs\\tensorflow\\lib`.
After searching in stackoverflow, I didn't find the same problem, since most guys just install tf in other systems. 

Is it that conda virtual environment of `python=3.5` not  compatiable with tf in windows?? And why tf in windows doesn't support python 2.7?? 

Thanks!

**Comment by soloice** [comment]
No idea about how to solve this.
I installed Anaconda both 2 and 3 (They can coexist with each other, see [Install Anaconda both 2 and 3](http://blog.csdn.net/infin1te/article/details/50445217)) on win7 and use the Python 3.5 environment for Tensorflow.  It works very well.

**Comment by jart** [comment]
What version of conda are you running? Do you think this issue is being caused by https://github.com/conda/conda/issues/3494?

**Comment by Qingmu** [comment]
@jart the version of my anaconda is 4.2.0 python 2.7.
#3494 is quite similiar to my issue.

Since the  windows version only support `python 3.5`, I am thinking change my python from version 2.7 to 3.5.

**Comment by jart** [comment]
So the problem with your setup was that you were using Python 3.5 inside a Python 2.7 environment? In that case, it sounds like your issue has been resolved. If things end up not being resolved, let me know and I'll re-open this issue.
