### ISSUE TITLE
Protobuf import issue

### ISSUE THREAD

**Issue by mattdns100689** [tensorflow/tensorflow#6863]
I am trying to run tensorboard but I am getting the following import error on mac osx;

`AttributeError: module 'pkg_resources' has no attribute 'declare_namespace'`

I have tried reinstalling setuptools and distribute. This is coming up as an error in python 3.5 even though my tensorflow is installed in 2.7; I.e. 

```
 File "/Library/Frameworks/Python.framework/Versions/3.5/bin/tensorboard", line 7, in <module>
    from tensorflow.tensorboard.tensorboard import main
```

**Comment by jart** [comment]
Thank you for bringing this to our attention @mattdns100689. What version of TensorFlow are you using? Can you share the full backtrace?

**Comment by mattdns100689** [comment]
I have installed it for both 2.7 and 3.5 and get the same error on both.

```
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.dylib locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.dylib locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.dylib locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.1.dylib locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.dylib locally
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/tensorboard", line 7, in <module>
    from tensorflow.tensorboard.tensorboard import main
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/google/protobuf/__init__.py", line 37, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
AttributeError: module 'pkg_resources' has no attribute 'declare_namespace'
```

**Comment by jart** [comment]
This stacktrace is going into the Protobuf codebase so this doesn't look like a bug in TensorFlow. It looks like something is wrong with the setuptools on your system. Maybe try reinstalling it? You can also try installing TensorFlow inside a virtualenv.
