### ISSUE TITLE
Trouble Running TensorFlow v2.16.1 with NVIDIA GeForce 940MX GPU #914

### ISSUE THREAD

**Issue by KushanManahara** [tensorflow/tensorflow#68696]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

tf 2.16.1

### Custom code

Yes

### OS platform and distribution

Linux

### Mobile device

Linux

### Python version

3.12

### CUDA/cuDNN version

12.4/V11.8.89

### Current behavior?

I attempted to run **TensorFlow version 2.16.1** on my local machine, which is equipped with an NVIDIA GeForce 940MX GPU. However, I encountered a kernel crash error while executing the following code in a Jupyter Notebook cell, 

This code snippet worked perfectly fine when I used **TensorFlow v2.4.1**, which I installed using Conda (`conda install anaconda::tensorflow-gpu==2.4.1`). However, after upgrading to TensorFlow v2.16.1 via Conda (`conda install anaconda::tensorflow-gpu==2.16.11`), the kernel crashed with the error message: 
_**"The Kernel crashed while executing code in the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure."**_

**System Configuration:**

- CUDA Version: 12.4
- cuDNN Version: Not specified
- GPU: NVIDIA GeForce 940MX
- Driver Version: 550.54.14

**Issue is,**
- Verified that the code runs **successfully with TensorFlow v2.4.1**.
- Encountered a **kernel crash error** when running the code **with TensorFlow v2.16.1**.

Seeking guidance on how to resolve the kernel crash issue and successfully run TensorFlow v2.16.1 with my NVIDIA GeForce 940MX GPU. Any insights, troubleshooting steps, or workaround suggestions would be greatly appreciated.

Thank you for your assistance!

### Standalone code to reproduce the issue

```shell
model = keras.Sequential(
    [
        keras.layers.Flatten(input_shape=(28, 28)),
        keras.layers.Dense(100, activation="relu"),
        keras.layers.Dense(10, activation="sigmoid"),
    ]
)
```

### Relevant log output

```shell
16:43:31.562 [info] Generated code for 5 = <ipython-input-5-4e58535241f8> with 6 lines
16:43:32.012 [error] Disposing session as kernel process died ExitCode: undefined, Reason: 2024-05-27 16:43:14.979186: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-27 16:43:31.611060: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-05-27 16:43:31.678484: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-05-27 16:43:31.678870: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-05-27 16:43:31.679090: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2343] TensorFlow was not built with CUDA kernel binaries compatible with compute capability 5.0. CUDA kernels will be jit-compiled from PTX, which could take 30 minutes or longer.
2024-05-27 16:43:31.680484: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-05-27 16:43:31.680861: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-05-27 16:43:31.681155: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-05-27 16:43:31.681340: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2343] TensorFlow was not built with CUDA kernel binaries compatible with compute capability 5.0. CUDA kernels will be jit-compiled from PTX, which could take 30 minutes or longer.
2024-05-27 16:43:31.741853: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-05-27 16:43:31.742222: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-05-27 16:43:31.742465: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-05-27 16:43:31.742647: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1928] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1169 MB memory:  -> device: 0, name: NVIDIA GeForce 940MX, pci bus id: 0000:01:00.0, compute capability: 5.0

16:43:32.071 [info] Cell 4 completed in -1716808411.592s (start: 1716808411592, end: undefined)
16:43:38.622 [error] Failed to write data to the kernel channel shell [
  <Buffer 3c 49 44 53 7c 4d 53 47 3e>,
  <Buffer 64 34 30 65 66 35 36 34 32 62 65 33 61 61 63 36 30 32 62 32 61 65 33 32 30 36 62 30 36 36 34 36 61 33 39 38 32 61 62 32 31 32 39 39 64 34 62 33 38 37 ... 14 more bytes>,
  <Buffer 7b 22 64 61 74 65 22 3a 22 32 30 32 34 2d 30 35 2d 32 37 54 31 31 3a 31 33 3a 33 38 2e 36 32 31 5a 22 2c 22 6d 73 67 5f 69 64 22 3a 22 34 62 61 36 35 ... 177 more bytes>,
  <Buffer 7b 7d>,
  <Buffer 7b 7d>,
  <Buffer 7b 22 73 69 6c 65 6e 74 22 3a 66 61 6c 73 65 2c 22 73 74 6f 72 65 5f 68 69 73 74 6f 72 79 22 3a 66 61 6c 73 65 2c 22 75 73 65 72 5f 65 78 70 72 65 73 ... 12329 more bytes>
] Error: Socket is closed
    at a.postToSocket (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.4.0-linux-x64/dist/extension.node.js:318:10349)
    at /home/~/.vscode/extensions/ms-toolsai.jupyter-2024.4.0-linux-x64/dist/extension.node.js:318:10099 {
  errno: 9,
  code: 'EBADF'
}
```

**Comment by Sr1ya** [comment]
To troubleshoot the kernel crash issue with TensorFlow v2.16.1, it's crucial to ensure that the environment is correctly set up and all dependencies are compatible. Here’s a detailed approach to diagnose and potentially resolve the problem.

### Steps to Reproduce the Issue

1. **Set Up the Environment**: Create a clean environment and install the required packages.

    ```sh
    conda create -n tf_env python=3.10
    conda activate tf_env
    conda install tensorflow-gpu==2.16.1
    ```

2. **Verify CUDA and cuDNN Versions**: Ensure the correct versions of CUDA and cuDNN are installed.

    ```sh
    conda install cudatoolkit=12.4 cudnn=8.9
    ```

3. **Install Jupyter Notebook**:

    ```sh
    conda install jupyter
    ```

4. **Install IPython Kernel**:

    ```sh
    pip install ipykernel
    python -m ipykernel install --user --name=tf_env --display-name "Python (tf_env)"
    ```

5. **Launch Jupyter Notebook**:

    ```sh
    jupyter notebook
    ```

6. **Run the Provided Code**:
    In a new Jupyter notebook cell, execute the following code:

    ```python
    import tensorflow as tf
    from tensorflow import keras

    model = keras.Sequential(
        [
            keras.layers.Flatten(input_shape=(28, 28)),
            keras.layers.Dense(100, activation="relu"),
            keras.layers.Dense(10, activation="sigmoid"),
        ]
    )
    print("Model created successfully")
    ```

### Diagnose the Error
Based on the provided log output, the error messages indicate potential issues with CUDA compatibility and kernel binaries. The critical error messages are:

1. **CUDA Kernel Compatibility**:
    ```
    TensorFlow was not built with CUDA kernel binaries compatible with compute capability 5.0. CUDA kernels will be jit-compiled from PTX, which could take 30 minutes or longer.
    ```

2. **NUMA Node Read Failures**:
    ```
    successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero.
    ```

### Potential Solutions

1. **Ensure Correct CUDA Installation**:
   Ensure that the CUDA installation is complete and the paths are correctly set.

    ```sh
    nvcc --version
    ```

    Verify that the CUDA version matches the expected version (12.4).

2. **Check GPU Driver**:
   Ensure that the GPU driver is up to date and compatible with the CUDA version.

    ```sh
    nvidia-smi
    ```

    Verify that the driver version supports CUDA 12.4.

3. **Update TensorFlow**:
   If using the nightly version or building from source, ensure the latest updates are included:

    ```sh
    pip install tf-nightly-gpu
    ```

4. **Environment Variables**:
   Set the environment variables to ensure TensorFlow uses the correct CUDA and cuDNN libraries.

    ```sh
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64
    export CUDA_HOME=/usr/local/cuda
    ```

5. **Check Compute Capability**:
   The GeForce 940MX has a compute capability of 5.0, which is quite old. Make sure TensorFlow is configured to support this.

### Full Reproduction Script

```python
import tensorflow as tf
from tensorflow import keras

# Define a simple model
model = keras.Sequential(
    [
        keras.layers.Flatten(input_shape=(28, 28)),
        keras.layers.Dense(100, activation="relu"),
        keras.layers.Dense(10, activation="sigmoid"),
    ]
)

print("Model created successfully")

# Verify GPU availability
print("TensorFlow version:", tf.__version__)
print("Is TensorFlow built with CUDA:", tf.test.is_built_with_cuda())
print("Is GPU available:", tf.config.list_physical_devices('GPU'))
```

### Additional Steps

1. **Consult TensorFlow GitHub Issues**:
   Search for similar issues in the [TensorFlow GitHub repository](https://github.com/tensorflow/tensorflow/issues).

2. **Revert to an Older TensorFlow Version**:
   If the issue persists, consider using an older TensorFlow version that you know works:

    ```sh
    conda install tensorflow-gpu==2.4.1
    ```

**Comment by sushreebarsa** [comment]
@KushanManahara If you're using TensorFlow v2.16.1, kindly ensure your CUDA and cuDNN versions are compatible. 
Please refer to TensorFlow [documentation](https://www.tensorflow.org/install/pip) for supported versions for TensorFlow v2.16.1 and let us know?
Thank you!
