### ISSUE TITLE
Switching branches forces ./configure and bazel rebuild

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#6911]
Right now switching branches requires running ./configure which then makes next `bazel test` rebuild everything.

In particular on 32 core Xeon, switching branches/`./configure` makes `bazel test learning/python/...` run 17 minutes longer because it's building stuff from scratch. This makes it hard for open-source contributors to work on more than one Pull Request at a time.

In particular, the error from `bazel test` when switching git branches is as follows:

```
ERROR: /home/yaroslav/tensorflow.git/tensorflow/tensorflow/core/BUILD:1194:1: Executing genrule //tensorflow/core:version_info_gen failed: bash failed:\
 error executing command /bin/bash -c ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited\
 with status 1.
Traceback (most recent call last):
  File "tensorflow/tools/git/gen_git_source.py", line 260, in <module>
    generate(args.generate)
  File "tensorflow/tools/git/gen_git_source.py", line 211, in generate
    (old_branch, new_branch))
RuntimeError: Run ./configure again, branch was 'refs/heads/match-once-fix' but is now 'refs/heads/symbolic-gradient-fix'
_
```

**Comment by yaroslavvb** [comment]
Not sure how feasible it is to relax this check, maybe someone familiar with bazel can comment, cc @damienmg

**Comment by damienmg** [comment]
Why is changing branch needs reconfiguration?

As the future, we will need less and less ./configure (like in next bazel release) and should be able to keep the configuration in another cache (so you can switch in between branch and get cache hits, probably in a few months).

**Comment by yaroslavvb** [comment]
cc @aselle who added this check

**Comment by aselle** [comment]
It should be possible to have a ./configure --update-git or something that does only the part that of configure that needs to be redone. The point of this is so that __git_version__ is correct in compiled binaries, which is important for support and bug fixing, but I agree that having to rebuild everything just to update the file that bazel uses to acquire __git_version__ is onerous.

**Comment by gunan** [comment]
I think as we removed `bazel clean` from configure script, this issue should now be fixed.
I will close this issue, but please feel free to reopen if this is still not resolved after installing `bazel 0.5.0` and using master.

**Comment by singam-sanjay** [comment]
I got the same error on branching from r1.2,
`RuntimeError: Run ./configure again, branch was 'refs/heads/r1.2' but is now 'refs/heads/trace_learning_XLA_ops'
`
Using Ubuntu 16.04 and bazel 0.5.2 provided by apt-get.

**Comment by yaroslavvb** [comment]
So I've just tried at head and this is happening again. After switching branches, I get this from bazel

```
ERROR: /home/yaroslav/Dropbox/git0/tensorflow/tensorflow/core/BUILD:1620:1: Couldn't build file tensorflow/core/util/version_info.cc: Executing genrule //tensorflow/core:version_info_gen failed (Exit 1)
Traceback (most recent call last):
  File "tensorflow/tools/git/gen_git_source.py", line 264, in <module>
    generate(args.generate)
  File "tensorflow/tools/git/gen_git_source.py", line 215, in generate
    (old_branch, new_branch))
RuntimeError: Run ./configure again, branch was 'refs/heads/master' but is now 'refs/heads/bytes_in_use'
ERROR: /home/yaroslav/Dropbox/git0/tensorflow/tensorflow/core/BUILD:1620:1: Couldn't build file tensorflow/core/util/version_info.cc: Executing genrule //tensorflow/core:version_info_gen failed (Exit 1)
Traceback (most recent call last):
  File "tensorflow/tools/git/gen_git_source.py", line 264, in <module>
    generate(args.generate)
  File "tensorflow/tools/git/gen_git_source.py", line 215, in generate
    (old_branch, new_branch))
RuntimeError: Run ./configure again, branch was 'refs/heads/master' but is now 'refs/heads/bytes_in_use'
```

**Comment by yaroslavvb** [comment]
Looks like commenting out the lines which throw this exception in gen_git_source.py fixes the issue

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.
