### ISSUE TITLE
DLL

### ISSUE THREAD

**Issue by 2chayma** [tensorflow/tensorflow#69163]
PS C:\Users\HP-MSi> & C:/Users/HP-MSi/AppData/Local/Programs/Python/Python312/python.exe c:/Users/HP-MSi/Desktop/MP2IASER/S4/Tâches/chokri/LSTM1.py
Traceback (most recent call last):
  File "C:\Users\HP-MSi\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 70, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: Une routine d’initialisation d’une bibliothèque de liens dynamiques (DLL) a échoué.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\HP-MSi\Desktop\MP2IASER\S4\Tâches\chokri\LSTM1.py", line 10, in <module>
    import tensorflow as tf
  File "C:\Users\HP-MSi\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\__init__.py", line 38, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow  # pylint: disable=unused-import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP-MSi\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 85, in <module>
    raise ImportError(
ImportError: Traceback (most recent call last):
  File "C:\Users\HP-MSi\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 70, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: Une routine d’initialisation d’une bibliothèque de liens dynamiques (DLL) a échoué.      

Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors for some common causes and solutions.
If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.
PS C:\Users\HP-MSi>

**Comment by sushreebarsa** [comment]
@2chayma Could you please ensure that you have a TensorFlow version compatible with your Python version ? Please follow this guide for compatibility. Kindly provide more [details](https://www.tensorflow.org/install/pip) on the reported issue?
Thank you!
