### ISSUE TITLE
GPU MaxPool gradient ops do not yet have a deterministic XLA implementation

### ISSUE THREAD

**Issue by wx0608** [tensorflow/tensorflow#69417]
### Issue type

Feature Request

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf 2.16

### Custom code

Yes

### OS platform and distribution

Linux Ubuntu 22.04

### Python version

3.9.19

### CUDA/cuDNN version

12.4/8.9.7.29

### GPU model and memory

NVIDIA GeForce RTX 3090

### Current behavior?

When TF deterministic was set, runtime exception was thrown at MaxPooling2D().

### Standalone code to reproduce the issue

```shell
When TF deterministic was set, runtime exception was thrown at MaxPooling2D().
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/ws/miniconda3/envs/tf216/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-3dda39ff370e>", line 1, in <module>
    runfile('/mnt/projects/Projects/Test_Classification/train_model.py', wdir='/mnt/projects/Projects/Test_Classification')
  File "/opt/pycharm-community-2024.1/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/opt/pycharm-community-2024.1/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/mnt/projects/Projects/Test_Classification/train_model.py", line 956, in <module>
    history = model.fit(x_train, y_train,
  File "/home/ws/miniconda3/envs/tf216/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/ws/miniconda3/envs/tf216/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 53, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnimplementedError: Graph execution error:
Detected at node gradient_tape/functional_1_1/max_pooling2d_4_1/MaxPool2d/MaxPoolGrad defined at (most recent call last):
<stack traces unavailable>
GPU MaxPool gradient ops do not yet have a deterministic XLA implementation.
	 [[{{node gradient_tape/functional_1_1/max_pooling2d_4_1/MaxPool2d/MaxPoolGrad}}]]
	tf2xla conversion failed while converting __inference_one_step_on_data_13588[]. Run with TF_DUMP_GRAPH_PREFIX=/path/to/dump/dir and --vmodule=xla_compiler=2 to obtain a dump of the compiled functions.
	 [[StatefulPartitionedCall]] [Op:__inference_one_step_on_iterator_14045]
```

**Comment by tilakrayal** [comment]
@wx0608,
Could you please share a reproducible code/colab gist that supports your statement so that the issue can be easily understood? Thank you!

**Comment by Masumekeshavarzi** [comment]
I am using DeepLabV3+ with Resent backbone and I am getting the same error when I want to have reproducible results. I put these lines as well:
SEED=123
tf.keras.utils.set_random_seed(SEED)
os.environ['PYTHONHASHSEED'] = str(SEED)
random.seed(SEED)
tf.random.set_seed(SEED)
np.random.seed(SEED)

os.environ['TF_DETERMINISTIC_OPS'] = '1'
os.environ['TF_CUDNN_DETERMINISTIC'] = '1'
tf.config.experimental.enable_op_determinism()

from [here](https://github.com/tensorflow/community/blob/master/rfcs/20210119-determinism.md#random-ops)  I realied that TF_CUDNN_DETERMINISTIC. When set to 'true' or '1', this selects deterministic gradient algorithms for tf.nn.max_pool*d and tf.keras.layers.MaxPool*D ,
but still get this error :GPU MaxPool gradient ops do not yet have a deterministic XLA implementation

before I has same problem with Upsampling layers in which we should use bilinear interpolation not Nearestneighbor , but with MaxPooling layers I dont know what should be changed. Please leave any meassage that might be helpful.

**Comment by deeepwin** [comment]
Same here. Setting:

```
os.environ['TF_DETERMINISTIC_OPS'] = '0' 

or

tf.config.experimental.enable_op_determinism()
```

to make code deterministic, causes:

```
tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnimplementedError: GPU MaxPool gradient ops do not yet have a deterministic XLA implementation.
         [[{{node gradient_tape/test-Actor/enc_max_2/MaxPool/MaxPoolGrad}}]] [Op:__inference__train_10443]
```

using that Tensorflow code:

```
        def encoder_block(x, filters, pool_size):
            x = conv_block(x, filters)
            p = KL.MaxPool2D(pool_size, name=self._unique_name('enc_max'))(x)
            return x, p
```

tensorflow: 2.11.0
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Wed_Jun__9_20:32:38_PDT_2021
Cuda compilation tools, release 11.3, V11.3.122
Build cuda_11.3.r11.3/compiler.30059648_0

**Comment by deeepwin** [comment]
Seems when disabling XLA the error disappears:

```
@TF.function(jit_compile=False)
 def train():
```

**Comment by deeepwin** [comment]
Seems when disabling XLA, error disappers for MaxPooling2D:

```
@TF.function(jit_compile=False)
 def _train()
```

**Comment by flacle** [comment]
Hi. If possible, please also consider deterministic XLA for `MaxPool1D`. Let me know in case a separate issue is needed here or in another repo.

**Comment by tilakrayal** [comment]
@wx0608,
Could you please check whether this issue is resolved with the latest tensorflow v2.17 which contains Keras 3.0 version. As Keras3 now built to support multiple backends there are some changes in design.

Thank you!

**Comment by deeepwin** [comment]
Tested with Keras 3.0, Tensorflow 2.17. Still same error:

`GPU MaxPool gradient ops do not yet have a deterministic XLA implementation.
         [[{{node gradient_tape/test-5321-Actor_1/enc_max_26_1/MaxPool2d/MaxPoolGrad}}]]`

For me MaxPool1D is not an option.

**Comment by summa-code** [comment]
I am having the same issue with MaxPool1D

**Comment by steveepreston** [comment]
this issue still exist.
how to solve or bypass it?

**Comment by IsaraAomi** [comment]
I have the same problem about MaxPooling2D.
The following tutorial about reproducibility of keras confirmed that the same error occurs:
https://keras.io/examples/keras_recipes/reproducibility_recipes/

**Comment by tombinic** [comment]
Hi! Any news about that? I'm using tensorflow 2.16.1 and I'm obtaining the same error.

**Comment by Frightera** [comment]
> I have the same problem about MaxPooling2D. The following tutorial about reproducibility of keras confirmed that the same error occurs: https://keras.io/examples/keras_recipes/reproducibility_recipes/

I wrote this guide when Keras had `jit_compile = None` (Keras 2 or tf-keras) in the compile method. Now, Keras 3 uses `jit_compile = "auto"` (trying to use XLA) for the TensorFlow backend, which is the root of the error.

You can simply pass `jit_compile = False` if you're using Keras 3.

**Comment by tombinic** [comment]
Thank you. This worked for me!

**Comment by blastbeng** [comment]
> > I have the same problem about MaxPooling2D. The following tutorial about reproducibility of keras confirmed that the same error occurs: https://keras.io/examples/keras_recipes/reproducibility_recipes/
> 
> I wrote this guide when Keras had `jit_compile = None` (Keras 2 or tf-keras) in the compile method. Now, Keras 3 uses `jit_compile = "auto"` (trying to use XLA) for the TensorFlow backend, which is the root of the error.
> 
> You can simply pass `jit_compile = False` if you're using Keras 3.

Hi, I have been trying to solve this error adding 

```@tf.function(jit_compile=False)
def train(self, df_train_norm, df_test_norm, train_results, test_results, force_train=False, save_model=True):```

to my train function.
But now when calling `df_train_norm.copy()`

I have the following error:

`AttributeError: 'SymbolicTensor' object has no attribute 'copy'`

Is this the correct way to solve the "**GPU MaxPool gradient ops do not yet have a deterministic XLA implementation**" Error?
Where do I have to add **jit_compile=False**?
Thanks

**Comment by tombinic** [comment]
As stated here:

https://github.com/tensorflow/tensorflow/issues/69417#issuecomment-2387147015

You have to put jit_compile=False in the compile method.

**Comment by blastbeng** [comment]
> As stated here:
> 
> [#69417 (comment)](https://github.com/tensorflow/tensorflow/issues/69417#issuecomment-2387147015)
> 
> You have to put jit_compile=False in the compile method.

Adding that to the compile method results in:

`TypeError: To be compatible with tf.function, Python functions must return zero or more Tensors or ExtensionTypes or None values; in compilation of <function ClassifierKerasLinear.compile_model at 0x7fdf24272320>, found return value of type Functional, which is not a Tensor or ExtensionType.`


My compile method:



```
    @tf.function(jit_compile=False)
    def compile_model(self, model):
        optimizer = tf.keras.optimizers.Adam(learning_rate=self.learning_rate)
        model.compile(metrics=['mae', 'mse'], loss='mse', optimizer=optimizer)

        return model
```

**Comment by tombinic** [comment]
I mean this:
```

model.compile(metrics=['mae', 'mse'], loss='mse', optimizer=optimizer, jit_compile=False)
```

**Comment by blastbeng** [comment]
> I mean this:
> 
> ```
> 
> model.compile(metrics=['mae', 'mse'], loss='mse', optimizer=optimizer, jit_compile=False)
> ```

Looks like it workkedd =)) Thanks

**Comment by Kayyuri** [comment]
Hi @wx0608, 
As mentioned by @Frightera, The root cause is the change in default behavior within Keras 3. It uses` jit_compile=auto` (which tries to enable XLA compilation when using the TensorFlow backend) , whereas older versions (Keras 2/tf.keras) defaulted to` jit_compile=None`. Since setting` jit_compile=auto` will leads to errors. 
So with the current implementation, You can compile the model using` jit_compile=False`. Please refer to this PR [#1941](https://github.com/keras-team/keras-io/pull/1941) for more information.

Please let me know if this fixes the issue with the latest versions of tensorflow or if you’re still encountering any issues? 
Thank you!
