### ISSUE TITLE
TensorFlow for Python3.4::The specified key does not exist

### ISSUE THREAD

**Issue by monajalal** [tensorflow/tensorflow#6942]
I am trying to install TensorFlow for GPU and I have CUDA8 and CUDNN in Ubuntu 14.04.
Here's the errors I received. Please suggest solution:
```

$ sudo pip3 install --upgrade $TF_BINARY_URL
Downloading/unpacking https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-0.12.1-cp34
  HTTP error 404 while getting https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-0.12.1-cp34
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1198, in prepare_files
    do_download,
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1376, in unpack_url
    self.session,
  File "/usr/lib/python3/dist-packages/pip/download.py", line 547, in unpack_http_url
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.2.1-py2.py3-none-any.whl/requests/models.py", line 773, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found

Storing debug log for failure in /home/mona/.pip/pip.log
```

Here's the log:
```
  1 ------------------------------------------------------------
  2 /usr/bin/pip3 run on Wed Jan 18 16:30:31 2017
  3 Downloading/unpacking https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-0.12.1-cp34
  4   HTTP error 404 while getting https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-0.12.1-cp34
  5 Cleaning up...
  6   Removing temporary dir /tmp/pip_build_root...
  7 Exception:
  8 Traceback (most recent call last):
  9   File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
 10     status = self.run(options, args)
 11   File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 278, in run
 12     requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
 13   File "/usr/lib/python3/dist-packages/pip/req.py", line 1198, in prepare_files
 14     do_download,
 15   File "/usr/lib/python3/dist-packages/pip/req.py", line 1376, in unpack_url
 16     self.session,
 17   File "/usr/lib/python3/dist-packages/pip/download.py", line 547, in unpack_http_url
 18     resp.raise_for_status()
 19   File "/usr/share/python-wheels/requests-2.2.1-py2.py3-none-any.whl/requests/models.py", line 773, in raise_for_status
 20     raise HTTPError(http_error_msg, response=self)
 21 requests.exceptions.HTTPError: 404 Client Error: Not Found

```

![screenshot from 2017-01-18 16-29-24](https://cloud.githubusercontent.com/assets/1892917/22085884/aafbcb72-dd9b-11e6-99e9-6acea8f25526.png)

**Comment by malzantot** [comment]
I guess you used incomplete link:

try : 
`https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-0.12.1-cp27-none-linux_x86_64.whl`

instead of 
`https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-0.12.1-cp34`

**Comment by monajalal** [comment]
Thank you! I see what happened! I'm so embarrassed thanks to that horizontal scroll 
![screenshot from 2017-01-18 16-59-44](https://cloud.githubusercontent.com/assets/1892917/22086699/979c4ddc-dd9f-11e6-8948-2335c908aa56.png)

**Comment by malzantot** [comment]
No worries, glad it helped :)
