### ISSUE TITLE
tflite model maker not install 

### ISSUE THREAD

**Issue by ALAZZURRI** [tensorflow/tensorflow#69431]
i want install tflite-model-maker but i face issue when install 
i do this 

1. install python 3.12.4
2. create Virtual Environments and Activate  
3.  inside env use " pip install tflite-model-maker"

env_name>pip install tflite-model-maker
Collecting tflite-model-maker
  Using cached tflite_model_maker-0.4.3-py3-none-any.whl.metadata (5.4 kB)
Collecting tf-models-official==2.3.0 (from tflite-model-maker)
  Using cached tf_models_official-2.3.0-py2.py3-none-any.whl.metadata (1.3 kB)
Collecting numpy<1.23.4,>=1.17.3 (from tflite-model-maker)
  Using cached numpy-1.23.3.tar.gz (10.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "C:\Users\aalrahahleh\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\aalrahahleh\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\aalrahahleh\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "C:\Users\aalrahahleh\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\aalrahahleh\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "C:\Users\aalrahahleh\AppData\Local\Temp\pip-build-env-e6sy9x22\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "C:\Users\aalrahahleh\AppData\Local\Temp\pip-build-env-e6sy9x22\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "C:\Users\aalrahahleh\AppData\Local\Temp\pip-build-env-e6sy9x22\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Venkat6871** [comment]
Hi **@ALAZZURRI** ,
- I was able to reproduce same issue. here i am providing screenshots for reference.
<img width="1495" alt="image" src="https://github.com/tensorflow/tensorflow/assets/147127861/3c23b9e9-799f-4de9-a4f7-4ef57b2adce0">
<img width="1495" alt="image (2)" src="https://github.com/tensorflow/tensorflow/assets/147127861/b32a72fd-2822-442a-9e33-b95b7a31e50c">
Thank you!

**Comment by micahchenn** [comment]
i am having the same issue please help urgently

**Comment by sawantkumar** [comment]
Hi @ALAZZURRI , 

This issue is unlikely to be resolved soon. However there are few option that you can explore like MediaPipe Model Maker.
Please look at [this](https://github.com/tensorflow/tensorflow/issues/62658) old issue for more details.

**Comment by architjaiswal** [comment]
I'm having the same issue installing tflite model maker on WSL2 windows 11. Has anyone found a solution?
