### ISSUE TITLE
Invalid argument: Cannot parse tensor from proto:  dtype: DT_FLOAT

### ISSUE THREAD

**Issue by lokesh005** [tensorflow/tensorflow#6971]
@lukaszkaiser I am facing the same problem. I have same specification as the previous one. My code is
`Final_dataset.csv` contains 456 X 147457

    `train = pd.read_csv('Final_dataset.csv')
     x = tf.placeholder(tf.float32, shape=[None, 128*128*3])
     y_ = tf.placeholder(tf.float32, shape=[None, 128*256*3])
     W = tf.Variable(tf.zeros([128*128*3,128*256*3]))
     b = tf.Variable(tf.zeros([128*256*3]))`

Whenever I run below command
     `sess.run(tf.global_variables_initializer())`

I am getting this error

    `W tensorflow/core/framework/op_kernel.cc:965] Invalid argument: Cannot parse tensor from proto:    dtype: DT_FLOAT
      tensor_shape {
          dim {
             size: 49152
          }
          dim {
             size: 98304
          }
      }
      float_val: 0

      E tensorflow/core/common_runtime/executor.cc:390] Executor failed to create kernel. Invalid argument: Cannot parse tensor from proto: dtype: DT_FLOAT
      tensor_shape {
         dim {
            size: 49152
         }
        dim {
            size: 98304
        }
     }
    float_val: 0

	 [[Node: zeros_2 = Const[dtype=DT_FLOAT, value=<Invalid TensorProto: dtype: DT_FLOAT tensor_shape { dim { size: 49152 } dim { size: 98304 } } float_val: 0>, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
       Traceback (most recent call last):
        File "<stdin>", line 1, in <module>
        File "/home/lokesh/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
         File "/home/lokesh/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
        File "/home/lokesh/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1014, in _do_run
    target_list, options, run_metadata)
       File "/home/lokesh/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
     tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot parse tensor from proto: dtype: DT_FLOAT
     tensor_shape {
       dim {
          size: 49152
        }
        dim {
            size: 98304
        }
     }
      float_val: 0

	 [[Node: zeros_2 = Const[dtype=DT_FLOAT, value=<Invalid TensorProto: dtype: DT_FLOAT tensor_shape { dim { size: 49152 } dim { size: 98304 } } float_val: 0>, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

    Caused by op u'zeros_2', defined at:
    File "<stdin>", line 1, in <module>
    File "/home/lokesh/.local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1437, in zeros
    output = constant(zero, shape=shape, dtype=dtype, name=name)
     File "/home/lokesh/.local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 169, in constant
    attrs={"value": tensor_value, "dtype": dtype_value}, name=name).outputs[0]
     File "/home/lokesh/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2240, in create_op
    original_op=self._default_original_op, op_def=op_def)
     File "/home/lokesh/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

    InvalidArgumentError (see above for traceback): Cannot parse tensor from proto: dtype: DT_FLOAT
    tensor_shape {
     dim {
        size: 49152
     }
     dim {
       size: 98304
     }
     }
     float_val: 0

	 [[Node: zeros_2 = Const[dtype=DT_FLOAT, value=<Invalid TensorProto: dtype: DT_FLOAT tensor_shape { dim { size: 49152 } dim { size: 98304 } } float_val: 0>, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
`

**Comment by lukaszkaiser** [comment]
Without the dataset (or, preferably, a smaller one for testing) it is not possible to reproduce your problem. Please prepare a smaller dataset and a minimal python code that causes the problem, then attach the small CSV file and the python file so that we can reproduce the problem. Thanks.

**Comment by asimshankar** [comment]
Please also include all the other information asked for in the new issue template, like the version of TensorFlow being used.

**Comment by lokesh005** [comment]
Specifications: 
Operating System: ubuntu 16.04
CPU version, no cuda installed
I installed that from pip3
tensorflow version: 0.10, link: [https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0-cp34-cp34m-linux_x86_64.whl](https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0-cp34-cp34m-linux_x86_64.whl)

Test file:
[Test.zip](https://github.com/tensorflow/tensorflow/files/719558/Test.zip)

Above is the test file contains 10 rows X 147457 columns.

So the code is:
 
     train = pd.read_csv('Test.csv')
     x = tf.placeholder(tf.float32, shape=[None, 128*128*3])
     y_ = tf.placeholder(tf.float32, shape=[None, 128*256*3])
     W = tf.Variable(tf.zeros([128*128*3,128*256*3]))
     b = tf.Variable(tf.zeros([128*256*3])

Error is same as that of above.

**Comment by asimshankar** [comment]
It would help if you could provide the full program to execute. In this case, after correcting for some syntax errors in your snippet above, I'm assuming it was something like:

```python
import tensorflow as tf
import pandas as pd
train = pd.read_csv('Test.csv')
x = tf.placeholder(tf.float32, shape=[None, 128*128*3])
y_ = tf.placeholder(tf.float32, shape=[None, 128*256*3])
W = tf.Variable(tf.zeros([128*128*3,128*256*3]))
b = tf.Variable(tf.zeros([128*256*3]))
tf.Session().run(tf.global_variables_initializer())
```
A couple of things:

- `tf.global_variables_initializer()` did not exist in release 0.10, which you pointed to. It was added in 0.12, so are you sure you're using 0.10?
- I'm not quite sure how the `csv` file is playing a role here since the code snipped does nothing with it. Do you have the same problem without the `pd.read_csv` line?
- The `W` matrix is pretty big (roughly 18GB, given its shape of (128*128*3) x (128*256*3)), so I'm guessing you're running this on a pretty beefy machine :)

If I scale down the weight matrix just so that I can quickly run it without needing 18GB of RAM (`W = tf.Variable(tf.zeros([128*3,256*3]))`) , the modified snippet works out just fine in 0.12 but fails in 0.10 because `tf.global_variables_initializer()` does not exist. 

I suspect there is some other code that you're running that is leading to this problem, and you're not using 0.10 but some other version.

To provide useful help, it would help to have a self-contained reproducible example with the exact version you're using (you can use `print tf.__version__` to get to that as well)

**Comment by lokesh005** [comment]
@asimshankar Sorry the tensorflow version is
      `>>> print(tf.__version__)` 
              `0.12.1`
I am trying to run it on my local system only. I have 8GB of RAM and 1TB HDD.

The error is not coming without the `pd.read`_csv line.

 **I suspect there is some other code that you're running that is leading to this problem, and you're not using 0.10 but some other version.**
    No @asimshankar,  what I am doing is that I am pasting the code one by one on the terminal in the sequence given above. But as soon as I am entering the command `sess.run(tf.global_variables_initializer())` I am getting the error.

 I am changing the code that is given [here](https://www.tensorflow.org/tutorials/mnist/pros/). In this link the code is for the grey image, I am changing it **to make it work for the original image**(containing RGB).

Below is the code that I am using
[For test.py.tar.gz](https://github.com/tensorflow/tensorflow/files/720795/For.test.py.tar.gz)
Code is very similar to as shown [here](https://www.tensorflow.org/tutorials/mnist/pros/)

**Comment by asimshankar** [comment]
I'm sorry, I am unable to reproduce your problem. Please list out the full code you're running, starting from a clean slate. For example, I ran the following snippet and it succeeds. Does it work for your? If it does, what precise changes cause it to fail?

```python
python
import tensorflow as tf
print tf.__version__
x = tf.placeholder(tf.float32, shape=[None, 128*128*3])
y_ = tf.placeholder(tf.float32, shape=[None, 128*256*3])
W = tf.Variable(tf.zeros([128*3,256*3]))
b = tf.Variable(tf.zeros([128*256*3]))
tf.Session().run(tf.global_variables_initializer())
```

Note that I have changed the shape of the `W` variable to be much smaller.
If you're using the size mentioned in your snippet earlier of `[128*128*3,128*256*3]` on your 8GB machine, then you will run into trouble as this tensor would require 18GB and will cause your system to thrash heavily.

**Comment by lokesh005** [comment]
@asimshankar when I am running the last command of your code( I have changed the shape of W as you said) `tf.Session().run(tf.global_variables_initializer())` then I am getting the error. 
I have sent you my code that I am running in the zip folder.

To be precise I want to work with the colored image, so I am modifying the code given[here](https://www.tensorflow.org/tutorials/mnist/pros/).
Hope you understand!

**Comment by lokesh005** [comment]
Is there anybody to help me?

**Comment by pj-parag** [comment]
Facing similar issue:
`W tensorflow/core/framework/op_kernel.cc:965] Invalid argument: Cannot parse tensor from proto: dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 377788
  }
  dim {
    size: 377724
  }
}
float_val: 0
`

**Comment by mayankj08** [comment]
Even I am facing same issue. Is there any solution for same?

2017-06-02 16:20:59.440852: W tensorflow/core/framework/op_kernel.cc:1142] Invalid argument: Cannot parse tensor from proto: dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 15900942
  }
  dim {
    size: 53003
  }
}
float_val: 0

**Comment by Lukeeeeee** [comment]
## same issue here, when run 
```
            with tf.device('/gpu:1'):
                self.sess.run(tf.global_variables_initializer())
```

Limit:                 68719476736
InUse:                        2816
MaxInUse:                  4197120
NumAllocs:                      54
MaxAllocSize:              4194304

2017-07-27 20:05:05.729344: W tensorflow/core/common_runtime/bfc_allocator.cc:277] *___________________________________________________________________________________________________
2017-07-27 20:05:07.050444: W tensorflow/core/framework/op_kernel.cc:1148] Invalid argument: Cannot parse tensor from proto: dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 200704
  }
  dim {
    size: 802816
  }
}
float_val: 0


Process finished with exit code 137 (interrupted by signal 9: SIGKILL)

**Comment by LeviZell** [comment]
I have the same issue

**Comment by LeviZell** [comment]
+1 on this issue

**Comment by pribadihcr** [comment]
+1
017-11-07 17:01:24.884678: W tensorflow/core/framework/op_kernel.cc:1182] Invalid argument: Cannot parse tensor from proto: dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 832
  }
  dim {
    size: 832
  }
  dim {
    size: 832
  }
  dim {
    size: 216
  }
}
float_val: 0

2017-11-07 17:01:24.884742: E tensorflow/core/common_runtime/executor.cc:643] Executor failed to create kernel. Invalid argument: Cannot parse tensor from proto: dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 832
  }
  dim {
    size: 832
  }
  dim {
    size: 832
  }
  dim {
    size: 216
  }
}
float_val: 0

	 [[Node: conv12/W/Momentum/Initializer/zeros = Const[_class=["loc:@conv12/W"], dtype=DT_FLOAT, value=<Invalid TensorProto: dtype: DT_FLOAT tensor_shape { dim { size: 832 } dim { size: 832 } dim { size: 832 } dim { size: 216 } } float_val: 0>, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
2017-11-07 17:01:24.896778: W tensorflow/core/framework/op_kernel.cc:1182] Invalid argument: Cannot parse tensor from proto: dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 832
  }
  dim {
    size: 832
  }
  dim {
    size: 832
  }
  dim {
    size: 216
  }
}
float_val: 0

2017-11-07 17:01:24.897232: E tensorflow/core/common_runtime/executor.cc:643] Executor failed to create kernel. Invalid argument: Cannot parse tensor from proto: dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 832
  }
  dim {
    size: 832
  }
  dim {
    size: 832
  }
  dim {
    size: 216
  }
}
float_val: 0

**Comment by huyvohcmc** [comment]
+1
```
Cannot parse tensor from proto: dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 230400
  }
  dim {
    size: 7200
  }
}
float_val: 0
```

**Comment by pgalilea** [comment]
Same problem here.

Windows 10 x64, Python 3.5.2, TF 1.4.0, 8Gb RAM

**Comment by wangzhenhui1992** [comment]
the same problem 


`InvalidArgumentError (see above for traceback): Cannot parse tensor from proto: dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 150528
  }
  dim {
    size: 150528
  }
}
float_val: 0

	 [[Node: training/SGD/Const = Const[dtype=DT_FLOAT, value=<Invalid TensorProto: dtype: DT_FLOAT tensor_shape { dim { size: 150528 } dim { size: 150528 } } float_val: 0>, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
`

**Comment by rsathishr** [comment]
Same Problem, pls guide me

InvalidArgumentError: Cannot parse tensor from proto: dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 3840000
  }
  dim {
    size: 1024
  }
}
float_val: 0

**Comment by asimshankar** [comment]
@lokesh005 @rsathishr @wangzhenhui1992 @pgalilea @huyvohcmc @pribadihcr @LeviZell @Lukeeeeee @mayankj08 @pj-parag - Sorry to hear this, but it would help if more detailed information was provided. Is everyone using 1.4.0? Can you provide a short snippet that reproduces the problem?

For example, in a [previous comment](https://github.com/tensorflow/tensorflow/issues/6971#issuecomment-274227371) I had provided a sample snippet (which doesn't reproduce the problem for me though). If that snippet causes you trouble, please do provide the full output (including the version information printed by the line `print(tf.__version__)`). @lokesh005 - I'm not clear from your responses as to which version you're using, and you pointed to "modifications" to the tutorial code, but without knowing what those modifications are, it will be hard to diagnose the issue. 

Looking forward to some more detailed information.

Thanks.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue? Please update the label and/or status accordingly.

**Comment by asimshankar** [comment]
Closing this due to inactivity. If this problem is encountered, please feel free to reopen but do provide all the details asked for in the new issue template and in https://github.com/tensorflow/tensorflow/issues/6971#issuecomment-352522044 

A more detailed description on how to reproduce the problem will help us diagnose it. Thanks!

**Comment by BrazilForever11** [comment]
I experienced the same issue. Reducing vector size solved the problem, alternatively one can try machine with more RAM.

**Comment by yotamfr** [comment]
Same Issue:


STACK TRACE...



Creating and compiling model...

Fitting model...
Train on 15 samples, validate on 3 samples
Epoch 1/20
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1326     try:
-> 1327       return fn(*args)
   1328     except errors.OpError as e:

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _run_fn(session, feed_dict, fetch_list, target_list, options, run_metadata)
   1305                                    feed_dict, fetch_list, target_list,
-> 1306                                    status, run_metadata)
   1307 

C:\ProgramData\Anaconda3\lib\contextlib.py in __exit__(self, type, value, traceback)
     87             try:
---> 88                 next(self.gen)
     89             except StopIteration:

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py in raise_exception_on_not_ok_status()
    465           compat.as_text(pywrap_tensorflow.TF_Message(status)),
--> 466           pywrap_tensorflow.TF_GetCode(status))
    467   finally:

InvalidArgumentError: Cannot parse tensor from proto: dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 200000000
  }
  dim {
    size: 1024
  }
}
float_val: 0

	 [[Node: training_6/SGD/Const_8 = Const[dtype=DT_FLOAT, value=<Invalid TensorProto: dtype: DT_FLOAT tensor_shape { dim { size: 200000000 } dim { size: 1024 } } float_val: 0>, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-45-fcfc7f69b24a> in <module>()
     20                 validation_data=([X1_valid, X2_valid], y_valid),
     21                 verbose=1,
---> 22                 callbacks=callbacks)

C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
   1596                               initial_epoch=initial_epoch,
   1597                               steps_per_epoch=steps_per_epoch,
-> 1598                               validation_steps=validation_steps)
   1599 
   1600     def evaluate(self, x, y,

C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py in _fit_loop(self, f, ins, out_labels, batch_size, epochs, verbose, callbacks, val_f, val_ins, shuffle, callback_metrics, initial_epoch, steps_per_epoch, validation_steps)
   1181                     batch_logs['size'] = len(batch_ids)
   1182                     callbacks.on_batch_begin(batch_index, batch_logs)
-> 1183                     outs = f(ins_batch)
   1184                     if not isinstance(outs, list):
   1185                         outs = [outs]

C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py in __call__(self, inputs)
   2268                 value = (indices, sparse_coo.data, sparse_coo.shape)
   2269             feed_dict[tensor] = value
-> 2270         session = get_session()
   2271         updated = session.run(self.outputs + [self.updates_op],
   2272                               feed_dict=feed_dict,

C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py in get_session()
    165     if not _MANUAL_VAR_INIT:
    166         with session.graph.as_default():
--> 167             _initialize_variables()
    168     return session
    169 

C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py in _initialize_variables()
    339     if uninitialized_variables:
    340         sess = get_session()
--> 341         sess.run(tf.variables_initializer(uninitialized_variables))
    342 
    343 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in run(self, fetches, feed_dict, options, run_metadata)
    893     try:
    894       result = self._run(None, fetches, feed_dict, options_ptr,
--> 895                          run_metadata_ptr)
    896       if run_metadata:
    897         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1122     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1123       results = self._do_run(handle, final_targets, final_fetches,
-> 1124                              feed_dict_tensor, options, run_metadata)
   1125     else:
   1126       results = []

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1319     if handle is None:
   1320       return self._do_call(_run_fn, self._session, feeds, fetches, targets,
-> 1321                            options, run_metadata)
   1322     else:
   1323       return self._do_call(_prun_fn, self._session, handle, feeds, fetches)

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1338         except KeyError:
   1339           pass
-> 1340       raise type(e)(node_def, op, message)
   1341 
   1342   def _extend_graph(self):

InvalidArgumentError: Cannot parse tensor from proto: dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 200000000
  }
  dim {
    size: 1024
  }
}
float_val: 0

	 [[Node: training_6/SGD/Const_8 = Const[dtype=DT_FLOAT, value=<Invalid TensorProto: dtype: DT_FLOAT tensor_shape { dim { size: 200000000 } dim { size: 1024 } } float_val: 0>, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op 'training_6/SGD/Const_8', defined at:
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2698, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2802, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-45-fcfc7f69b24a>", line 22, in <module>
    callbacks=callbacks)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 1575, in fit
    self._make_train_function()
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 960, in _make_train_function
    loss=self.total_loss)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\optimizers.py", line 165, in get_updates
    moments = [K.zeros(shape) for shape in shapes]
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\optimizers.py", line 165, in <listcomp>
    moments = [K.zeros(shape) for shape in shapes]
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 625, in zeros
    return variable(tf.constant_initializer(0., dtype=tf_dtype)(shape),
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\init_ops.py", line 203, in __call__
    verify_shape=verify_shape)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py", line 106, in constant
    attrs={"value": tensor_value, "dtype": dtype_value}, name=name).outputs[0]
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Cannot parse tensor from proto: dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 200000000
  }
  dim {
    size: 1024
  }
}
float_val: 0

	 [[Node: training_6/SGD/Const_8 = Const[dtype=DT_FLOAT, value=<Invalid TensorProto: dtype: DT_FLOAT tensor_shape { dim { size: 200000000 } dim { size: 1024 } } float_val: 0>, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

**Comment by dhirajpatnaik16297** [comment]
You can find some solutions here
https://stackoverflow.com/questions/46941747/tensorflow-error-cannot-parse-tensor-from-proto

**Comment by VenkateshSoni** [comment]
Can we open this issue again?
I am facing same issue on AWS Sagemaker Notebook - 32GB RAM.
Dimension of my dataset is 408 * 241390, whenever use the initializer command -
 self.sess.run(tf.global_variables_initializer())

it shoes me this error - 
Invalid argument: Cannot parse tensor from proto: dtype: DT_FLOAT
