### ISSUE TITLE
tensorflow MNIST getting error IOError: Not a gzipped file

### ISSUE THREAD

**Issue by charlesfayal** [tensorflow/tensorflow#6982]
When I try to run the basic tutorial example I get this as a return:

Traceback (most recent call last):
  File "TensorFlowBasicTutorial", line 76, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "TensorFlowBasicTutorial", line 23, in main
    mnist = input_data.read_data_sets(FLAGS.data_dir, one_hot=True)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 213, in read_data_sets
    train_images = extract_images(f)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 53, in extract_images
    magic = _read32(bytestream)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 35, in _read32
    return numpy.frombuffer(bytestream.read(4), dtype=dt)[0]
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 303, in _read
    self._read_gzip_header()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 197, in _read_gzip_header
    raise IOError, 'Not a gzipped file'
IOError: Not a gzipped file

I uninstalled tensorflow and reinstalled tensor flow with no results. 
I have seen some information about installing the file locally, but then how do import the data? I am rather new to python so I do not know how to do this.

Thanks!

**Comment by yaroslavvb** [comment]
seems like network problems can cause error, try solution here?
https://perrohunter.com/fix-ioerror-not-a-gzipped-file-in-tensorflow-docker-example/

**Comment by aselle** [comment]
Closing due to lack of recent activity. Please update the issue if it persists and we will reopen.

**Comment by giuliohome** [comment]
I'm having this issue if I run the sample convolutional_network.py from from a newly launched environment of https://codeenv.com/env/codeenv/14/tensor-flow/

**Comment by giuliohome** [comment]
screenshot [here](https://snag.gy/q7WQCn.jpg)

**Comment by giuliohome** [comment]
ops... there is already a mnist folder pre-installed :-) I'll try with that one! sorry, ignore my above messages

**Comment by premnarayanpatidar** [comment]
HI,
i encounter same issue, struggle a lot trying this and that, the simple answer for which i tried randomly and works for me is unzip the file manually and keep only unzipped files to your directory and try to run the command, cheers

**Comment by manikaaggarwal** [comment]
I am facing the same problem.

**Comment by deepankerkoul** [comment]
Yep, still an active problem

`y_train = np.frombuffer(lbpath.read(), np.uint8, offset=8)
  File "C:\Program Files\Python37\lib\gzip.py", line 276, in read
    return self._buffer.read(size)
  File "C:\Program Files\Python37\lib\gzip.py", line 463, in read
    if not self._read_gzip_header():
  File "C:\Program Files\Python37\lib\gzip.py", line 411, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'<!')`
