### ISSUE TITLE
TypeError: inputs must be a sequence occure in Bidirectional RNN

### ISSUE THREAD

**Issue by SunnerLi** [tensorflow/tensorflow#7005]
Sorry to bother.
I just use the bidirectional rnn now.
However, I just encounter some problem.
```terminal
Traceback (most recent call last):
  File "test1.py", line 19, in <module>
    sequence_length=length(sequence),
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn.py", line 530, in bidirectional_rnn
    raise TypeError("inputs must be a sequence")
TypeError: inputs must be a sequence
```
I don't know what the problem it is?
The following show my code.
```python
import tensorflow as tf

max_length = 100
frame_size = 64
num_hidden = 200

def length(sequence):
    used = tf.sign(tf.reduce_max(tf.abs(sequence), reduction_indices=2))
    length = tf.reduce_sum(used, reduction_indices=1)
    length = tf.cast(length, tf.int32)
    return length

sequence = tf.placeholder(tf.float32, [None, max_length, frame_size])
output, state = tf.nn.bidirectional_rnn(
    tf.nn.rnn_cell.GRUCell(num_hidden),
    tf.nn.rnn_cell.GRUCell(num_hidden),
    sequence,
    dtype=tf.float32,
    sequence_length=length(sequence),
)
```

The code I refer to the [blog](https://danijar.com/variable-sequence-lengths-in-tensorflow/) that other issue demonstrate and recommond.

---
I try to figure out why the exception was raise.
```python
import tensorflow as tf
import collections

self.input_sentences = tf.placeholder(tf.float32, [None, sequence_length, embedding_size])
print "six: ", isinstance(self.length, collections.Sequence)
```
This is the part of my code.
However, the result is shown below:
```
six:  False
```
Is somebody encounter such this problem?
or how can I solve this?

I use CPU only, the OS is ubuntu 16.04
the version of tensorflow is 0.12.1

**Comment by asimshankar** [comment]
This question is probably better posed on [stackoverflow](http://stackoverflow.com/questions/tagged/tensorflow) as we try to keep the github issues focused on bugs and feature requests. Thanks.

**Comment by SunnerLi** [comment]
I found the solution at last.
The following show the revised code:
```python
import tensorflow as tf

max_length = 82
frame_size = 2
num_hidden = 64

def length(sequence):
    used = tf.sign(tf.reduce_max(tf.abs(sequence), reduction_indices=2))
    length = tf.reduce_sum(used, reduction_indices=1)
    return length

_input = tf.placeholder(tf.float32, [None, max_length, 100])
_taggg = tf.placeholder(tf.float32, [None, max_length, 2])

output, state, _ = tf.nn.bidirectional_rnn(
    tf.nn.rnn_cell.MultiRNNCell([tf.nn.rnn_cell.LSTMCell(num_hidden)]),
    tf.nn.rnn_cell.MultiRNNCell([tf.nn.rnn_cell.LSTMCell(num_hidden)]),
    tf.unpack(tf.transpose(_input, perm=[1, 0, 2])),
    dtype=tf.float32,
    sequence_length=length(_taggg),
)
```
You should unpack the input as the list, and the list will be transfer to the sequence by tensorflow automatically. 
The last but not least, output of the function is three args.

**Comment by mmuratarat** [comment]
it means;
dim0 -> dim1
dim1 -> dim0
dim2 -> dim2
