### ISSUE TITLE
Failure loading saved model (with tf2onnx)

### ISSUE THREAD

**Issue by kupix** [tensorflow/tensorflow#70196]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf 2.18

### Custom code

No

### OS platform and distribution

Linux Ubuntu 22.04

### Python version

3.10.12

### Current behavior?

Current behaviour: TF is unable to load a previously saved model, reporting "AttributeError: '_UserObject' object has no attribute 'add_slot'".
Expected behaviour: TF loads the previously saved model and converts it to ONNX. 
See also similar, also unresolved issue: https://github.com/tensorflow/tensorflow/issues/61972

### Standalone code to reproduce the issue

```shell
git clone https://vcgit.hhi.fraunhofer.de/jvet-ahg-nnvc/VVCSoftware_VTM
cd VVCSoftware_VTM
git checkout VTM-11.0_nnvc
cd training/training_scripts/NN_Post_Filtering/scripts/resources/orig_base_models/

python3 -m pip install tf-nightly onnx
python3 -m tf2onnx.convert --saved-model ./model1
```

### Relevant log output

```shell
2024-06-21 14:24:04.004487: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-06-21 14:24:04.004758: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-06-21 14:24:04.007946: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-06-21 14:24:04.048536: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-21 14:24:04.658015: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/usr/lib/python3.10/runpy.py:126: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
2024-06-21 14:24:05,131 - WARNING - '--tag' not specified for saved_model. Using --tag serve
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/john/venv/lib/python3.10/site-packages/tf2onnx/convert.py", line 714, in <module>
    main()
  File "/home/john/venv/lib/python3.10/site-packages/tf2onnx/convert.py", line 242, in main
    graph_def, inputs, outputs, initialized_tables, tensors_to_rename = tf_loader.from_saved_model(
  File "/home/john/venv/lib/python3.10/site-packages/tf2onnx/tf_loader.py", line 636, in from_saved_model
    _from_saved_model_v2(model_path, input_names, output_names,
  File "/home/john/venv/lib/python3.10/site-packages/tf2onnx/tf_loader.py", line 570, in _from_saved_model_v2
    imported = tf.saved_model.load(model_path, tags=tag)  # pylint: disable=no-value-for-parameter
  File "/home/john/venv/lib/python3.10/site-packages/tensorflow/python/saved_model/load.py", line 912, in load
    result = load_partial(export_dir, None, tags, options)["root"]
  File "/home/john/venv/lib/python3.10/site-packages/tensorflow/python/saved_model/load.py", line 1042, in load_partial
    loader = Loader(object_graph_proto, saved_model_proto, export_dir,
  File "/home/john/venv/lib/python3.10/site-packages/tensorflow/python/saved_model/load.py", line 223, in __init__
    self._load_all()
  File "/home/john/venv/lib/python3.10/site-packages/tensorflow/python/saved_model/load.py", line 320, in _load_all
    self._load_nodes()
  File "/home/john/venv/lib/python3.10/site-packages/tensorflow/python/saved_model/load.py", line 529, in _load_nodes
    slot_variable = optimizer_object.add_slot(
AttributeError: '_UserObject' object has no attribute 'add_slot'
```

**Comment by sushreebarsa** [comment]
@kupix Could you please ensure that any environment variables required for TensorFlow compatibility are set properly?
Please make sure you are using compatible versions of TensorFlow and tf2onnx. Kindly use the latest TF v2.16 as the nightly builds might cause some issues.
Thank you!
