### ISSUE TITLE
ImportError: cannot import name control_flow_ops

### ISSUE THREAD

**Issue by monajalal** [tensorflow/tensorflow#7020]
Please suggest fixes. I just recently installed tf for Python2.7 on Ubuntu 14.04 and CUDA8. 
```
mona@pascal:~/computer_vision/distracted-drivers-tf$ python main.py 
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so.5.0 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so.8.0 locally
/usr/local/lib/python2.7/dist-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from model import Model
  File "/home/mona/computer_vision/distracted-drivers-tf/model.py", line 6, in <module>
    from layers import Input
  File "/home/mona/computer_vision/distracted-drivers-tf/layers.py", line 4, in <module>
    from tensorflow.python import control_flow_ops
ImportError: cannot import name control_flow_ops

```

**Comment by drpngx** [comment]
You are not supposed to use `control_flow_ops` directly, since this is not part of the public API. Please use `import tensorflow as tf` and then `tf.cond` etc directly.

**Comment by gunan** [comment]
Closing due to lack of recent activity.
Please reopen if you still run into this problem when trying to use `tf.cond`.

**Comment by nemonameless** [comment]
`from tensorflow.python.ops import control_flow_ops`
