### ISSUE TITLE
CUDA 11.4 Build error

### ISSUE THREAD

**Issue by basi880830** [tensorflow/tensorflow#70268]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.8.4

### Custom code

No

### OS platform and distribution

win10

### Python version

3.7

### Bazel version

4.2.1

### GCC/compiler version

13.3.0

### CUDA/cuDNN version

11.4/

### GPU model and memory

g

### Current behavior?

When I built tensorflow, I issued the command "bazel build --config=opt --config=v2 --config=cuda --local_cpu_resources=1 --local_ram_resources=2048 --verbose_failures --define=no_tensorflow_py_deps=true // tensorflow :tensorflow_cc.dll" error occurred."bazel clean --expunge" was used before issuing this command.

### Standalone code to reproduce the issue

```shell
(Tensorflow) E:\tensorflow-2.8.4>bazel build --config=opt --config=v2 --config=cuda --local_cpu_resources=1 --local_ram_resources=2048 --verbose_failures --define=no_tensorflow_py_deps=true //tensorflow:tensorflow_cc.dll
Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [v2, cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=191
INFO: Reading rc options for 'build' from e:\tensorflow-2.8.4\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=C:/Users/USER/anaconda3/envs/Tensorflow/python.exe
INFO: Reading rc options for 'build' from e:\tensorflow-2.8.4\.bazelrc:
  'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library
INFO: Reading rc options for 'build' from e:\tensorflow-2.8.4\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=C:/Users/USER/anaconda3/envs/Tensorflow/python.exe --action_env PYTHON_LIB_PATH=C:/Users/USER/anaconda3/envs/Tensorflow/lib/site-packages --python_path=C:/Users/USER/anaconda3/envs/Tensorflow/python.exe --action_env CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.4 --action_env CUDNN_INSTALL_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.4 --action_env TF_CUDA_COMPUTE_CAPABILITIES=6.1 --action_env LD_LIBRARY_PATH=C:Program FilesNVIDIA GPU Computing ToolkitCUDAv11.4libx64 --config=cuda --copt=/d2ReducedOptimizeHugeFunctions --host_copt=/d2ReducedOptimizeHugeFunctions
INFO: Reading rc options for 'build' from e:\tensorflow-2.8.4\.bazelrc:
  'build' options: --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/analysis,tensorflow/compiler/mlir/tfrt/tests/jit,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_tfrt,tensorflow/compiler/mlir/tfrt/tests/tf_to_corert,tensorflow/compiler/mlir/tfrt/tests/tf_to_tfrt_data,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/common,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/fallback,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
INFO: Found applicable config definition build:short_logs in file e:\tensorflow-2.8.4\.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file e:\tensorflow-2.8.4\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:cuda in file e:\tensorflow-2.8.4\.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
INFO: Found applicable config definition build:opt in file e:\tensorflow-2.8.4\.tf_configure.bazelrc: --copt=/arch:AVX --host_copt=/arch:AVX
INFO: Found applicable config definition build:v2 in file e:\tensorflow-2.8.4\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:cuda in file e:\tensorflow-2.8.4\.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
INFO: Found applicable config definition build:windows in file e:\tensorflow-2.8.4\.bazelrc: --copt=/W0 --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=/experimental:preprocessor --host_copt=/experimental:preprocessor --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --verbose_failures --features=compiler_param_file --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file e:\tensorflow-2.8.4\.bazelrc: --define framework_shared_object=false
INFO: Repository local_config_cuda instantiated at:
  E:/tensorflow-2.8.4/WORKSPACE:15:14: in <toplevel>
  E:/tensorflow-2.8.4/tensorflow/workspace2.bzl:879:19: in workspace
  E:/tensorflow-2.8.4/tensorflow/workspace2.bzl:96:19: in _tf_toolchains
Repository rule cuda_configure defined at:
  E:/tensorflow-2.8.4/third_party/gpus/cuda_configure.bzl:1448:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
        File "E:/tensorflow-2.8.4/third_party/gpus/cuda_configure.bzl", line 1401, column 38, in _cuda_autoconf_impl
                _create_local_cuda_repository(repository_ctx)
        File "E:/tensorflow-2.8.4/third_party/gpus/cuda_configure.bzl", line 1179, column 17, in _create_local_cuda_repository
                cc = find_cc(repository_ctx)
        File "E:/tensorflow-2.8.4/third_party/gpus/cuda_configure.bzl", line 216, column 34, in find_cc
                return _get_msvc_compiler(repository_ctx)
        File "E:/tensorflow-2.8.4/third_party/gpus/cuda_configure.bzl", line 133, column 61, in _get_msvc_compiler
                return find_msvc_tool(repository_ctx, vc_path, "cl.exe").replace("\\", "/")
Error: 'NoneType' value has no field or method 'replace'
ERROR: Error fetching repository: Traceback (most recent call last):
        File "E:/tensorflow-2.8.4/third_party/gpus/cuda_configure.bzl", line 1401, column 38, in _cuda_autoconf_impl
                _create_local_cuda_repository(repository_ctx)
        File "E:/tensorflow-2.8.4/third_party/gpus/cuda_configure.bzl", line 1179, column 17, in _create_local_cuda_repository
                cc = find_cc(repository_ctx)
        File "E:/tensorflow-2.8.4/third_party/gpus/cuda_configure.bzl", line 216, column 34, in find_cc
                return _get_msvc_compiler(repository_ctx)
        File "E:/tensorflow-2.8.4/third_party/gpus/cuda_configure.bzl", line 133, column 61, in _get_msvc_compiler
                return find_msvc_tool(repository_ctx, vc_path, "cl.exe").replace("\\", "/")
Error: 'NoneType' value has no field or method 'replace'
INFO: Found applicable config definition build:cuda in file e:\tensorflow-2.8.4\.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
INFO: Found applicable config definition build:cuda in file e:\tensorflow-2.8.4\.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
WARNING: The following configs were expanded more than once: [v2, cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
ERROR: @local_config_cuda//:enable_cuda :: Error loading option @local_config_cuda//:enable_cuda: 'NoneType' value has no field or method 'replace'
```

**Comment by sushreebarsa** [comment]
@basi880830 It seems that you are using an old TF version which is not actively supported. Could you please upgrade to the latest by referring to this [documentation](https://www.tensorflow.org/install/source_windows#tested_build_configurations) and let us know?
Thank you!

**Comment by basi880830** [comment]
Thanks for the suggestion. I changed tenserflow to 2.9.3 and bazel to the corresponding version 5.0.0, which is currently being built.

**Comment by sushreebarsa** [comment]
@basi880830 Could you please confirm if the issue has been resolved and move this issue to closed status?
Thank you!
