### ISSUE TITLE
Is there any GPU implementation of tf.stack for int64? 

### ISSUE THREAD

**Issue by amortazi** [tensorflow/tensorflow#7027]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by amortazi** [comment]
I am wondering if there is any GPU implementation of tf.stack? It seems that tf.stack only can run on CPU. Is there any equivalent command that I can use it in GPU? 
Thanks

**Comment by yaroslavvb** [comment]
Native op seems to be called Pack and I see a GPU kernel registration for it in [pack_ops.cc](https://github.com/tensorflow/tensorflow/blob/64edd34ce69b4a8033af5d217cb8894105297d8a/tensorflow/core/kernels/pack_op.cc#L142)

**Comment by drpngx** [comment]
Yes, to second what @yaroslavvb said, there is one and it's calling [`ConcatGPU`](https://www.github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/pack_op.cc#L116) if the conditions are right. You shouldn't have to do anything to invoke it.

**Comment by amortazi** [comment]
@yaroslavvb thanks for response. but it seems that tf.pack also just runs in CPU. I am using tf.device to put it in the gpu, but after looking at log_device_placement, it is still pinned to CPU. DO u have any suggestion? I can upload the code if u want it. Thanks

**Comment by yaroslavvb** [comment]
what if you run with soft_device_placement=False? Also, I'm not sure where
log_device_placement takes assignments from, I normally look at
run_metadata to see where it gets put

run_metadata = tf.RunMetadata()
run_options = tf.RunOptions(trace_level=tf.RunOptions.FULL_TRACE)
sess.run(.., options=run_options, run_metadata=run_metadata)
print(run_metadata)

**Comment by amortazi** [comment]
@yaroslavvb I got following error with soft_device_placement=False:
InvalidArgumentError (see above for traceback): Cannot assign a device to node 'pack': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
	 [[Node: pack = Pack[N=4, T=DT_INT64, axis=0, _device="/device:GPU:0"](mul_1, floordiv, floordiv_1, mul_3)]]

Unfortunately, it is in the middle of my CNN and it causes data passes to CPU and increases my training time significantly. I appreciate if u have any solution for it.

**Comment by drpngx** [comment]
Oh, it's `dtypes.int64`. The GPU number types are float and double.

**Comment by drpngx** [comment]
Could you try to add `TF_CALL_int64(REGISTER_GPU)` in `pack_ops.cc`?

**Comment by amortazi** [comment]
I need to install tf from source, i am working on it!

**Comment by amortazi** [comment]
@drpngx should I just add TF_CALL_int64(REGISTER_GPU) in pack)ops.cc? May i ask where I should add it in the code? 
Thanks,
Ali

**Comment by drpngx** [comment]
Just before the `#undef` (here)[https://github.com/tensorflow/tensorflow/blob/64edd34ce69b4a8033af5d217cb8894105297d8a/tensorflow/core/kernels/pack_op.cc#L148] should be fine.

**Comment by amortazi** [comment]
I am using tensorflow 0.12 which tf.pack is not defined for this version. So, I have to use tf.stack here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/stack_ops.cc#L265

Would you tell me how I should this file to work with int64?

**Comment by drpngx** [comment]
`tf.stack` just calls the [pack op](https://www.github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/array_ops.py#L843). It's confusing just for historical reasons. So the omdification in `pack_ops.cc` is correct.

**Comment by amortazi** [comment]
It didn't work after applying the changes. Still tf.stack is pinned to CPU:

> stack: (Pack): /job:localhost/replica:0/task:0/cpu:0
2017-01-25 19:16:59: I tensorflow/core/common_runtime/simple_placer.cc:841] stack: (Pack)/job:localhost/replica:0/task:0/cpu:0

I am using tf.device to pin it to GPU (with allow_soft_placement = True).
Any suggestion?

**Comment by amortazi** [comment]
And this is an error I got with allow_soft_placement = False : 

> InvalidArgumentError (see above for traceback): Cannot assign a device to node 'stack': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
	 [[Node: stack = Pack[N=4, T=DT_INT64, axis=0, _device="/device:GPU:0"](mul_1, floordiv, floordiv_1, mul_3)]]

**Comment by drpngx** [comment]
It means that the registration did not work, for some reason.

Could you go to [`NewSession`](https://www.github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/direct_session.cc#L130) then call [`LogAllRegisteredKernels`](https://www.github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/op_kernel.h#L1118) and see if it's there? It should not be, but you should see the CPU versions.

**Comment by amortazi** [comment]
Would you provide some hints how I should do it? Is there any example?

**Comment by drpngx** [comment]
Just go to the code in NewSession linked above, then add LogAllRegisteredKernels(). In the `#include` section, add `#include "tensorflow/core/framework/op_kernel.h`, then rebuild etc.

**Comment by amortazi** [comment]
I reseted my computer and now when I wanna to build tf again I got this error:


> ERROR: /home/user/.cache/bazel/_bazel_user/f9f5c94ad789d21bcfdb930889866229/external/local_config_cuda/crosstool/BUILD:4:1: Traceback (most recent call last):
	File "/home/user/.cache/bazel/_bazel_user/f9f5c94ad789d21bcfdb930889866229/external/local_config_cuda/crosstool/BUILD", line 4
		error_gpu_disabled()
	File "/home/user/.cache/bazel/_bazel_user/f9f5c94ad789d21bcfdb930889866229/external/local_config_cuda/crosstool/error_gpu_disabled.bzl", line 3, in error_gpu_disabled
		fail("ERROR: Building with --config=c...")
ERROR: Building with --config=cuda but TensorFlow is not configured to build with GPU support. Please re-run ./configure and enter 'Y' at the prompt to build with GPU support.
ERROR: no such target '@local_config_cuda//crosstool:toolchain': target 'toolchain' not declared in package 'crosstool' defined by /home/user/.cache/bazel/_bazel_user/f9f5c94ad789d21bcfdb930889866229/external/local_config_cuda/crosstool/BUILD.

There is an issue about that in the following link but it didn't work for me:
https://github.com/tensorflow/tensorflow/issues/4841

**Comment by drpngx** [comment]
That's odd. Did you try to re-run configure as instructed?

**Comment by amortazi** [comment]
Yes, even I installed bazel again.

**Comment by drpngx** [comment]
You did answer "Y" at the configure right? It should have run `bazel fetch ...` and gotten what was needed. Could you try bazel fetch ... by hand again to see?

**Comment by amortazi** [comment]
Yes,I answered Y. It was working before I restarted my computer. I did it, it didn't work.

**Comment by drpngx** [comment]
What do you have in this file: `third_party/gpus/crosstool/BUILD` ?

**Comment by amortazi** [comment]
It is empty!

**Comment by drpngx** [comment]
That's the right content. Can you do:

```
find tensorflow -type f -name BUILD |xargs grep -n error_gpu_disabled
```
?

**Comment by amortazi** [comment]
it returned nothing.

**Comment by drpngx** [comment]
That's strange.  Could you blow your cache again (`bazel --clean`) and run?

**Comment by amortazi** [comment]
bazel --clean returned error. but bazel clean worked fine. Is that fine?

**Comment by drpngx** [comment]
Yes sorry. Could run `find . -type f -name BUILD|xargs grep -n error_gpu_disabled`?

**Comment by amortazi** [comment]
it returned nothing. Also, I did bazel clean and run it again, but it returned same error.

**Comment by drpngx** [comment]
How about `git clone` to another directory and try from there?

**Comment by amortazi** [comment]
I got same error! :(

**Comment by drpngx** [comment]
I'm slowly running out of ideas. If you have tensorflow installed, please `pip uninstall` it.

Also, report the output of

```
declare -x
```

You could try to use the docker file and build in a docker environment, roughly speaking:
```
cd tensorflow/tools/docker
sudo docker build -t tfbuild  -f Dockerfile.cpu-devel
sudo docker run -it -v /tmp:/tmp tfbuild bash
cd /tmp
git clone ....
```
and build from source there.

I have to ask -- are you sure you are building in the right directory?

**Comment by rizar** [comment]
I am not sure I understand the status of this issue. It is pretty clear from the code that by default the GPU kernel is not registered for `scatter_nd`. I make this conclusion by observing that the [following lines for CPU kernels](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/scatter_nd_op.cc#L377):

```
TF_CALL_NUMBER_TYPES(REGISTER_SCATTER_ND_ADD_SUB_CPU);
// TODO(simister): Re-enable all types after binary size is under control.
TF_CALL_NUMBER_TYPES(REGISTER_SCATTER_ND_UPDATE_CPU);
TF_CALL_NUMBER_TYPES(REGISTER_SCATTER_ND_CPU);
```

and only two respective lines for GPU kernels 

```
TF_CALL_GPU_NUMBER_TYPES_NO_HALF(REGISTER_SCATTER_ND_ADD_SUB_GPU);
TF_CALL_GPU_NUMBER_TYPES_NO_HALF(REGISTER_SCATTER_ND_UPDATE_GPU);
# where is the third one??
``` 

@drpngx is the third kernel left out intentionally? If yes, is enabling a GPU implementation for `scatter_nd` in the timeline?

I'd like to note that this issue has a nasty side-effect: `scatter_nd` is used in the gradient of `gather_nd`, and because of the lack of the GPU kernel, the `gather_nd` gradient is computed on CPU...

**Comment by yaroslavvb** [comment]
It looks like @drasmuss looked at this issue in https://github.com/tensorflow/tensorflow/issues/7026#issuecomment-277005409 and found that scatter_nd GPU implementation doesn't exist

**Comment by drpngx** [comment]
Yeah, we were trying to add it to see what happens but somehow the thread died out. Please try it out if you have cycles.

**Comment by rizar** [comment]
Oops, this is a wrong issue, I will continue in #7026.

**Comment by girving** [comment]
@drpngx What's the status here?

**Comment by yongtang** [comment]
I think the issue has been resolved through:
https://github.com/tensorflow/tensorflow/commit/fdf4ad4c35e925bf3d944dac5b91efcc64b2c8b3#diff-53b0b5ca00738b21110fb55fda34b0c6

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by drpngx** [comment]
Looks like this has been resolved. Feel free to reopen if I misunderstood.
