### ISSUE TITLE
model.fit ValueError: Cannot take the length of shape with unknown rank.

### ISSUE THREAD

**Issue by Mr-narimani99** [tensorflow/tensorflow#70311]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.17

### Custom code

Yes

### Current behavior?

i got a code that it works for other person who rwote it on youtube.
i will be thanks full to you if you help me to fix thsi bug.
but when i run it it shows error. and says:
Traceback (most recent call last):
  File "e:\Master\t2\MVAA\HW_07\Retina-Blood-Vessel-Segmentation-using-UNET-in-TensorFlow-main\train.py", line 116, in <module>
    model.fit(
  File "C:\Users\Mohammad\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Mohammad\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\metrics\reduction_metrics.py", line 38, in reduce_to_samplewise_values
    values_ndim = len(values.shape)
                  ^^^^^^^^^^^^^^^^^
ValueError: Cannot take the length of shape with unknown rank.

### Standalone code to reproduce the issue

```shell
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"
import numpy as np
import cv2
from glob import glob
from sklearn.utils import shuffle
import tensorflow as tf
from tensorflow.keras.callbacks import ModelCheckpoint, CSVLogger, ReduceLROnPlateau, EarlyStopping, TensorBoard
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import Recall, Precision
from model import build_unet
from metrics import dice_loss, dice_coef, iou

H = 512
W = 512

def create_dir(path):
    if not os.path.exists(path):
        os.makedirs(path)

def load_data(path):
    x = sorted(glob(os.path.join(path, "image", "*.jpg")))
    y = sorted(glob(os.path.join(path, "mask", "*.jpg")))
    return x, y

def shuffling(x, y):
    x, y = shuffle(x, y, random_state=42)
    return x, y

def read_image(path):
    path = path.decode()
    x = cv2.imread(path, cv2.IMREAD_COLOR)
    x = cv2.resize(x, (W, H))
    x = x/255.0
    x = x.astype(np.float32)
    return x

def read_mask(path):
    path = path.decode()
    x = cv2.imread(path, cv2.IMREAD_GRAYSCALE)  ## (512, 512)
    x = cv2.resize(x, (W, H))
    x = x/255.0
    x = x.astype(np.float32)    
    x = np.expand_dims(x, axis=-1)              ## (512, 512, 1)
    return x

def tf_parse(x, y):
    def _parse(x, y):
        x = read_image(x)
        y = read_mask(y)
        return x, y

    x, y = tf.numpy_function(_parse, [x, y], [tf.float32, tf.float32])
    x.set_shape([H, W, 3])
    y.set_shape([H, W, 1])
    return x, y

def tf_dataset(X, Y, batch_size=2):
    dataset = tf.data.Dataset.from_tensor_slices((X, Y))
    dataset = dataset.map(tf_parse)
    dataset = dataset.batch(batch_size)
    dataset = dataset.prefetch(5)   
    return dataset

if __name__ == "__main__":
    """ Seeding """
    np.random.seed(42)
    tf.random.set_seed(42)

    """ Directory to save files """
    create_dir("files")

    """ Hyperparameters """
    batch_size = 4
    lr = 1e-4
    num_epochs = 100
    model_path = os.path.join("files", "model.h5.keras")
    csv_path = os.path.join("files", "data.csv.keras")

    """ Dataset """
    dataset_path = "new_datas"
    train_path = os.path.join(dataset_path, "train")
    valid_path = os.path.join(dataset_path, "test")

    train_x, train_y = load_data(train_path)
    train_x, train_y = shuffling(train_x, train_y)
    valid_x, valid_y = load_data(valid_path)

    print(f"Train: {len(train_x)} - {len(train_y)}")
    print(f"Valid: {len(valid_x)} - {len(valid_y)}")
    train_dataset = tf_dataset(train_x, train_y, batch_size=batch_size)
    valid_dataset = tf_dataset(valid_x, valid_y , batch_size=batch_size)
    for x,y in train_dataset:
        print(x.shape,y.shape)
    for x,y in valid_dataset:
        print(x.shape,y.shape)
    train_steps = len(train_x)//batch_size
    valid_setps = len(valid_x)//batch_size

    if len(train_x) % batch_size != 0:
        train_steps += 1
    if len(valid_x) % batch_size != 0:
        valid_setps += 1

    """ Model """
    model = build_unet((H, W, 3))
    model.compile(loss=dice_loss, optimizer=Adam(lr), metrics=[dice_coef, iou, Recall(), Precision()])
    # model.summary()

    callbacks = [
        ModelCheckpoint(model_path, verbose=1, save_best_only=True),
        ReduceLROnPlateau(monitor="val_loss", factor=0.1, patience=5, min_lr=1e-6, verbose=1),
        CSVLogger(csv_path),
        EarlyStopping(monitor="val_loss", patience=10, restore_best_weights=False)
    ]
    model.fit(
        train_dataset,
        epochs=num_epochs,
        callbacks=callbacks,
        verbose=2,
        validation_data=valid_dataset,
        steps_per_epoch=train_steps,
        validation_steps=valid_setps
        )
```

**Comment by Venkat6871** [comment]
Hi **@mrezaanony** ,
- I reproduced the code shared but facing different error .Could you please share the colab gist with all the dependencies to analyze more of it.
Thank you!

**Comment by mrezaanony** [comment]
Hi@Venkat6871
unfortunatly i have deleted all my files. i dont have the many more.

**Comment by Venkat6871** [comment]
Hi @Mr-narimani99 ,
Apologies for the delay. I tried with sample code, and it is working fine for me. I am providing a [gist](https://colab.research.google.com/gist/Venkat6871/9ddf52e94cdc7b81c348edefdcbbe150/70311_tf-nightly-v.ipynb) for reference. If I am wrong, then please let me know.
Thank you!
