### ISSUE TITLE
replicated function tf.where()?

### ISSUE THREAD

**Issue by iarroyof** [tensorflow/tensorflow#7042]
Hi all,

I have a problem adding an Embedding layer to a `Sequential` model.

```
from keras.layers import Embedding
from keras.layers import Dense, Input, Flatten
from keras.layers import Conv1D, MaxPooling1D, Embedding
from keras.models import Model
from keras.models import Sequential
from keras.layers import LSTM,Bidirectional

embedding_layer = Embedding(len(word_index) + 1,
                            EMBEDDING_DIM,
                            weights=[embedding_matrix],
                            input_length=MAX_SEQUENCE_LENGTH*2,
                             dropout=0.2,
                            trainable=False)

model = Sequential()
model.add(embedding_layer)
model.add(Bidirectional(LSTM(100, dropout_W=0.2, dropout_U=0.2)))
model.add(Dense(200))
model.add(Dense(6, activation='softmax'))
```

I have the next error:
```
Traceback (most recent call last):
  File "recurrent_ltsm.py", line 201, in <module>
    model.add(embedding_layer)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 299, in add
    layer.create_input_layer(batch_input_shape, input_dtype)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 401, in create_input_layer
    self(x)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 572, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 635, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 166, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/embeddings.py", line 123, in call
    B = K.random_binomial((self.input_dim,), p=retain_p) * (1. / retain_p)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 2895, in random_binomial
    tf.zeros(shape, dtype=dtype))
TypeError: where() takes at most 2 arguments (3 given)
```
I have seen two versions of `tf.where()` in the documentation:

[https://www.tensorflow.org/versions/r0.10/api_docs/python/control_flow_ops/comparison_operators#where](url)
and 
[https://www.tensorflow.org/api_docs/python/math_ops/sequence_comparison_and_indexing#where](url)

Any idea why the program confuses them?

```
python -c 'import tensorflow as tf; print tf.__version__'
0.10.0
```

Thank you very much.

**Comment by drpngx** [comment]
Could you try with a more recent version of tensorflow?

**Comment by iarroyof** [comment]
Hi @drpngx I tried by installing version 0.12, but a new error raises 

```
Using TensorFlow backend.
RuntimeError: module compiled against API version 0xa but this version of numpy is 0x9
Traceback (most recent call last):
  File "/almac/ignacio/nlp-pipeline/recurrent_ltsm.py", line 126, in <module>
    from keras.preprocessing.text import Tokenizer
  File "/usr/local/lib/python2.7/dist-packages/keras/__init__.py", line 2, in <module>
    from . import backend
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/__init__.py", line 67, in <module>
    from .tensorflow_backend import *
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 1, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 60, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: numpy.core.multiarray failed to import

Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.
```

**Comment by drpngx** [comment]
Are you installing from source? If so, you need to `cd ..` or somewhere else.

If not, then it looks like a problem with numpy. stackoverflow says that `sudo pip install -U numpy` might improve things (upgrade numpy).

**Comment by drpngx** [comment]
Can you try the steps above?

**Comment by iarroyof** [comment]
Hi @drpngx I tried what you kindly suggested, but the error is the same.
Given I'm in Kears, Theano works well at the moment.

**Comment by drpngx** [comment]
OK, I'm not sure what it is. This is a keras issue, perhaps @fchollet can help you. Best is to ask on stackoverflow, where we monitor all questions with tag `tensorflow`.
