### ISSUE TITLE
LSTM model conversion failed from 'from_keras_model'

### ISSUE THREAD

**Issue by KarenMars** [tensorflow/tensorflow#70502]
### Issue
Hi, I am trying to convert my lstm-based model into tflite format, and I am using the [official lstm conversion code](https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/experimental_new_converter/Keras_LSTM_fusion_Codelab.ipynb) from the tensorflow colab. In the code given in the colab, the conversion works fine with `from_saved_model`, however, when I using the `from_keras_model` for the conversion, the conversion is failed. Please check the below code and logs for more information, thank you for any help : )

### 1. System information

- OS Platform and Distribution: 22.04.1
- TensorFlow installation: pip package
- TensorFlow library: 2.12.1

### 2. Code
```python
import numpy as np
import tensorflow as tf

model = tf.keras.models.Sequential([
    tf.keras.layers.Input(shape=(28, 28), name='input'),
    tf.keras.layers.LSTM(20, time_major=False, return_sequences=True),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(10, activation=tf.nn.softmax, name='output')
])
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
model.summary()

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
x_train = x_train.astype(np.float32)
x_test = x_test.astype(np.float32)

_FAST_TRAINING = True
_EPOCHS = 5
if _FAST_TRAINING:
  _EPOCHS = 1
  _TRAINING_DATA_COUNT = 1000
  x_train = x_train[:_TRAINING_DATA_COUNT]
  y_train = y_train[:_TRAINING_DATA_COUNT]

model.fit(x_train, y_train, epochs=_EPOCHS)
model.evaluate(x_test, y_test, verbose=0)

run_model = tf.function(lambda x: model(x))
# This is important, let's fix the input size.
BATCH_SIZE = 1
STEPS = 28
INPUT_SIZE = 28
concrete_func = run_model.get_concrete_function(
    tf.TensorSpec([BATCH_SIZE, STEPS, INPUT_SIZE], model.inputs[0].dtype))

# model directory.
MODEL_DIR = "keras_lstm"
model.save(MODEL_DIR, save_format="tf", signatures=concrete_func)

# from saved model
converter = tf.lite.TFLiteConverter.from_saved_model(MODEL_DIR)
tflite_model = converter.convert()
open("saved_lstm_model.tflite", "wb").write(tflite_model)
print('convert from saved model successfully!')
# from keras model
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
open("keras_lstm_model.tflite", "wb").write(tflite_model)

```

### 3. logs
```
// the conversion is failed by 'from_keras_model'
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
=================================================================
 lstm (LSTM)                 (None, 28, 20)            3920      
                                                                 
 flatten (Flatten)           (None, 560)               0         
                                                                 
 output (Dense)              (None, 10)                5610      
                                                                 
=================================================================
Total params: 9,530
Trainable params: 9,530
Non-trainable params: 0
_________________________________________________________________

 1/32 [..............................] - ETA: 26s - loss: 2.3000 - accuracy: 0.0625
10/32 [========>.....................] - ETA: 0s - loss: 2.2685 - accuracy: 0.1688 
14/32 [============>.................] - ETA: 0s - loss: 2.2432 - accuracy: 0.2165
19/32 [================>.............] - ETA: 0s - loss: 2.2064 - accuracy: 0.2730
24/32 [=====================>........] - ETA: 0s - loss: 2.1691 - accuracy: 0.3190
30/32 [===========================>..] - ETA: 0s - loss: 2.1254 - accuracy: 0.3646
32/32 [==============================] - 1s 10ms/step - loss: 2.1139 - accuracy: 0.3760
convert from saved model successfully!

WARNING:absl:Found untraced functions such as _update_step_xla, lstm_cell_layer_call_fn, lstm_cell_layer_call_and_return_conditional_losses while saving (showing 3 of 3). These functions will not be directly callable after loading.
WARNING:absl:Found untraced functions such as _update_step_xla, lstm_cell_layer_call_fn, lstm_cell_layer_call_and_return_conditional_losses while saving (showing 3 of 3). These functions will not be directly callable after loading.
loc(callsite(callsite(callsite(fused["TensorListReserve:", callsite("TensorArrayV2_1@__inference_standard_lstm_17957"("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/python/saved_model/save.py":1276:0) at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/python/saved_model/save.py":1240:0 at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":1283:0 at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/convert_phase.py":205:0 at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":1353:0 at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":1373:0 at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":940:0 at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":962:0 at "/Github_repo/draft/save_lstm_model.py":50:0))))))))] at fused["PartitionedCall:", callsite("sequential/lstm/PartitionedCall@__inference__wrapped_model_18239"("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/python/saved_model/save.py":1276:0) at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/python/saved_model/save.py":1240:0 at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":1283:0 at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/convert_phase.py":205:0 at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":1353:0 at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":1373:0 at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":940:0 at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":962:0 at "/Github_repo/draft/save_lstm_model.py":50:0))))))))]) at fused["StatefulPartitionedCall:", callsite("StatefulPartitionedCall@__inference_signature_wrapper_20177"("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/python/saved_model/save.py":1276:0) at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/python/saved_model/save.py":1240:0 at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":1283:0 at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/convert_phase.py":205:0 at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":1353:0 at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":1373:0 at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":940:0 at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":962:0 at "/Github_repo/draft/save_lstm_model.py":50:0))))))))]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"])): error: 'tf.TensorListReserve' op requires element_shape to be static during TF Lite transformation pass
loc(callsite(callsite(callsite(fused["TensorListReserve:", callsite("TensorArrayV2_1@__inference_standard_lstm_17957"("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/python/saved_model/save.py":1276:0) at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/python/saved_model/save.py":1240:0 at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":1283:0 at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/convert_phase.py":205:0 at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":1353:0 at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":1373:0 at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":940:0 at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":962:0 at "/Github_repo/draft/save_lstm_model.py":50:0))))))))] at fused["PartitionedCall:", callsite("sequential/lstm/PartitionedCall@__inference__wrapped_model_18239"("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/python/saved_model/save.py":1276:0) at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/python/saved_model/save.py":1240:0 at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":1283:0 at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/convert_phase.py":205:0 at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":1353:0 at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":1373:0 at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":940:0 at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":962:0 at "/Github_repo/draft/save_lstm_model.py":50:0))))))))]) at fused["StatefulPartitionedCall:", callsite("StatefulPartitionedCall@__inference_signature_wrapper_20177"("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/python/saved_model/save.py":1276:0) at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/python/saved_model/save.py":1240:0 at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":1283:0 at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/convert_phase.py":205:0 at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":1353:0 at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":1373:0 at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":940:0 at callsite("/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/lite.py":962:0 at "/Github_repo/draft/save_lstm_model.py":50:0))))))))]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"])): error: failed to legalize operation 'tf.TensorListReserve' that was explicitly marked illegal
error: Lowering tensor list ops is failed. Please consider using Select TF ops and disabling `_experimental_lower_tensor_list_ops` flag in the TFLite converter object. For example, converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]\n converter._experimental_lower_tensor_list_ops = False
Traceback (most recent call last):
  File "/Github_repo/draft/save_lstm_model.py", line 50, in <module>
    tflite_model = converter.convert()
  File "/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 962, in wrapper
    return self._convert_and_export_metrics(convert_func, *args, **kwargs)
  File "/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 940, in _convert_and_export_metrics
    result = convert_func(self, *args, **kwargs)
  File "/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 1373, in convert
    saved_model_convert_result = self._convert_as_saved_model()
  File "/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 1356, in _convert_as_saved_model
    self).convert(graph_def, input_tensors, output_tensors)
  File "/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 1166, in convert
    result = _convert_graphdef(
  File "/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/convert_phase.py", line 212, in wrapper
    raise converter_error from None  # Re-throws the exception.
  File "/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/convert_phase.py", line 205, in wrapper
    return func(*args, **kwargs)
  File "/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/convert.py", line 817, in convert_graphdef
    data = convert(
  File "/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/lite/python/convert.py", line 322, in convert
    raise converter_error
tensorflow.lite.python.convert_phase.ConverterError: /Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/python/saved_model/save.py:1276:0: error: 'tf.TensorListReserve' op requires element_shape to be static during TF Lite transformation pass
<unknown>:0: note: loc(fused["StatefulPartitionedCall:", "StatefulPartitionedCall"]): called from
/Github_repo/temp_folder/backend/venv/lib/python3.10/site-packages/tensorflow/python/saved_model/save.py:1276:0: error: failed to legalize operation 'tf.TensorListReserve' that was explicitly marked illegal
<unknown>:0: note: loc(fused["StatefulPartitionedCall:", "StatefulPartitionedCall"]): called from
<unknown>:0: error: Lowering tensor list ops is failed. Please consider using Select TF ops and disabling `_experimental_lower_tensor_list_ops` flag in the TFLite converter object. For example, converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]\n converter._experimental_lower_tensor_list_ops = False
```

**Comment by tilakrayal** [comment]
@KarenMars,

Add `tf.lite.OpsSet.SELECT_TF_OPS`  to the converter's target spec: 

``` python 
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS] 
```

to expand the range of supported operations. 

Also could you please try to change the following lines of code:

   ```python
    converter = tf.lite.TFLiteConverter.from_keras_model( enc_model )
    buffer = converter.convert()
    open( 'enc_model.tflite' , 'wb' ).write( buffer ) 
```
to 

```python
converter = tf.lite.TFLiteConverter.from_keras_model( enc_model )
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.experimental_new_converter=True
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,*tf.lite.OpsSet.SELECT_TF_OPS]
buffer = converter.convert()
open( 'enc_model.tflite' , 'wb' ).write( buffer ). 
```

Thank you!

**Comment by KarenMars** [comment]
Hi,

Thank you very much for the help, when I added the code you provided, the conversion from `from_keras_model` can work.

However, when I visualize these tflite models from `from_saved_model` and `from_keras_model`, it can be seen that the tflite model from `from_keras_model` uses many extra operators for the LSTM opertator. I assume that is because of the settings of `converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,*tf.lite.OpsSet.SELECT_TF_OPS]`. I wonder why the conversion from the keras model cannot support the lstm operators. And whether these extra operators will have different computation efficiency compared with a single lstm operator. Looking forward to your reply, and thank you very much.

![image](https://github.com/tensorflow/tensorflow/assets/32601780/ee6bd31f-77f0-4eee-9a81-d57aa2cfba80)

![image](https://github.com/tensorflow/tensorflow/assets/32601780/a2209c75-eea2-4f63-ab62-c807fdf8aa03)

**Comment by KarenMars** [comment]
Hi, do we have any updates of this issue, thank you very much ~

**Comment by pkgoogle** [comment]
Hi @KarenMars can you provide your current script which produces the non-optimal tflite model. You can skip the training steps since we're mainly focusing on the architectural issues w/ the conversion and not the value of the weights. I would say this is likely an optimization bug... have you tried seeing what the performance/efficiency differences are? I suspect they are different but it'll be interesting if the converted version is actually more performant than the correct tflite op. Which would mean it converts to a more optimal form -- I don't think this is a the case but in that case I would actually not call it a bug. Thanks for your help.
