### ISSUE TITLE
TensorFlow- Recurrent Neural networks.

### ISSUE THREAD

**Issue by ymakkapa** [tensorflow/tensorflow#7053]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by ymakkapa** [comment]
I got the files reader.py and ptb_word_lm.py from google and tried running them as "python ptb_word_lm.py --data_path=/tmp/simple-examples/data/ --model small". Please help me in resolving these errors.
Errors:
Traceback (most recent call last):
File "ptb_word_lm.py", line 321, in <module>
tf.app.run()
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
sys.exit(main(sys.argv[:1] + flags_passthrough))
File "ptb_word_lm.py", line 268, in main
raw_data = reader.ptb_raw_data(FLAGS.data_path)
File "/home/ymakkapa/TensorFlow/reader.py", line 51, in ptb_raw_data
word_to_id = _build_vocab(train_path)
File "/home/ymakkapa/TensorFlow/reader.py", line 17, in _build_vocab
data = _read_words(filename)
File "/home/ymakkapa/TensorFlow/reader.py", line 13, in _read_words
return f.read().decode("utf-8").replace("\n", "<eos>").split()
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 106, in read
self._preread_check()
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 73, in _preread_check
compat.as_bytes(self.__name), 1024 * 512, status)
File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
self.gen.next()
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 469, in raise_exception_on_not_ok_status
pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: /tmp/simple-examples/data/ptb.train.t

**Comment by yaroslavvb** [comment]
Sounds like you are missing input files (your /tmp/simple-examples/data directory doesn't have the train files). These kinds of questions are best asked on stackoverflow, this list is for bugs in TensorFlow itself + feature requests
