### ISSUE TITLE
Loading Files with New Tensorflow

### ISSUE THREAD

**Issue by danielmogilny** [tensorflow/tensorflow#7133]
Using newest version of Tensorflow on Linux.

Ok so I had a working Saver.restore going for literally months and everyone was fine:
saver = tf.train.Saver()
saver.restore(sess, "deep_tweet_lstm_w-300000")

deep_tweet_lstm_w-300000 was the name of the file with the data points.

Ever since updating my Tensorflow I get this error: 
NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for deep_tweet_lstm_w-300000

I honestly find this change infuriating, how in the world do I load this file with the new Tensorflow?

**Comment by yaroslavvb** [comment]
1. Can you be more specific with the versions
2. Could you try to switch back to older version and see if the problem persists (use virtualenv or conda env to easily switch between versions)

**Comment by danielmogilny** [comment]
I'm using 0.12.1 while before I used 0.11

**Comment by yaroslavvb** [comment]
Can you try with tf 0.11 from inside virtual env?

IE, if you use conda, 

```
conda create -n tf11-2 python=3.5 
source activate tf11-2
pip install -I --upgrade setuptools
export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.11.0rc0-cp35-cp35m-linux_x86_64.whl
pip install --upgrade $TF_BINARY_URL

```

**Comment by IgnacioCarlucho** [comment]
I have the exact same Issue with tensorflow version 0.12.1

**Comment by danielmogilny** [comment]
I solved it by just downgrading in the end.


Sent from my Samsung device

-------- Original message --------

**Comment by girving** [comment]
It certainly sounds like there was a regression here, but we'd need more detail to debug.

@rohan100jain Is it possible your change in cl/134036016 broke TensorSliceReader for globs without wildcards?

**Comment by gsh199449** [comment]
I have the same problem. I'm using the Tensorflow 1.0 with GPU on Windows 10. I tried some suggest in other issues, such as remove the special chars in checkpoint name, using absolute path. But still have this problem. Cloud you tell me how to solve this? Thank you.

Some output infomation are as follow:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/workspace/keras_summary/src/classificatio/preprocess.py", line 107, in <module>
    saver.restore(sess, "D:\\workspace\\keras_summary\\abstract\\model_ckpt")
  File "D:\workspace\keras_summary\lib\site-packages\tensorflow\python\training\saver.py", line 1439, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "D:\workspace\keras_summary\lib\site-packages\tensorflow\python\client\session.py", line 767, in run
    run_metadata_ptr)
  File "D:\workspace\keras_summary\lib\site-packages\tensorflow\python\client\session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "D:\workspace\keras_summary\lib\site-packages\tensorflow\python\client\session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "D:\workspace\keras_summary\lib\site-packages\tensorflow\python\client\session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for D:\workspace\keras_summary\abstract\model_ckpt
	 [[Node: save/RestoreV2_11 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_11/tensor_names, save/RestoreV2_11/shape_and_slices)]]
	 [[Node: save/RestoreV2_4/_19 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_132_save/RestoreV2_4", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op 'save/RestoreV2_11', defined at:
  File "D:/workspace/keras_summary/src/classificatio/preprocess.py", line 106, in <module>
    saver = tf.train.Saver()
  File "D:\workspace\keras_summary\lib\site-packages\tensorflow\python\training\saver.py", line 1051, in __init__
    self.build()
  File "D:\workspace\keras_summary\lib\site-packages\tensorflow\python\training\saver.py", line 1081, in build
    restore_sequentially=self._restore_sequentially)
  File "D:\workspace\keras_summary\lib\site-packages\tensorflow\python\training\saver.py", line 675, in build
    restore_sequentially, reshape)
  File "D:\workspace\keras_summary\lib\site-packages\tensorflow\python\training\saver.py", line 402, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "D:\workspace\keras_summary\lib\site-packages\tensorflow\python\training\saver.py", line 242, in restore_op
    [spec.tensor.dtype])[0])
  File "D:\workspace\keras_summary\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 668, in restore_v2
    dtypes=dtypes, name=name)
  File "D:\workspace\keras_summary\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "D:\workspace\keras_summary\lib\site-packages\tensorflow\python\framework\ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "D:\workspace\keras_summary\lib\site-packages\tensorflow\python\framework\ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for D:\workspace\keras_summary\abstract\model_ckpt
	 [[Node: save/RestoreV2_11 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_11/tensor_names, save/RestoreV2_11/shape_and_slices)]]
	 [[Node: save/RestoreV2_4/_19 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_132_save/RestoreV2_4", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

**Comment by IgnacioCarlucho** [comment]
I had the same issue, but I notice that tensorflow does not save the file as I define it. 
For instance if I save it as: 

`saver = tf.train.Saver()
save_path = saver.save(sess, 'dropout.ckpt', global_step = 0)`
 
Then there will be no file called "dropout.ckpt" 
But there will be a file: "dropout.ckpt-0.meta" . And loading this file successfully loads the tensorflow model. Therefore I will load it as: 

`new_saver = tf.train.import_meta_graph("dropout.ckpt-0.meta")
new_saver.restore(sess, tf.train.latest_checkpoint('./'))`

In you case, I think you are using keras.. In that case you can load and save using: 

`model.save('my_model.h5')  # creates a HDF5 file 'my_model.h5'
del model  # deletes the existing model
model = load_model('my_model.h5') # and loads it (just to check)
`

**Comment by rohan100jain** [comment]
deep_tweet_lstm_w-300000 does look like a valid prefix path that should be loadable. The latest_checkpoint function as recommended by Ignacio should work but would be good to see why reference to a specific checkpoint doesn't work.

Could you print out the ls result from the working directory? Would be good to see what files are on disk.

**Comment by rohan100jain** [comment]
Actually https://github.com/tensorflow/tensorflow/issues/6893 might give us a hint as to what might be going on...

if you put ./ in front of the path, does it work?

**Comment by gsh199449** [comment]
@rohan100jain `./` doesn't work on Windows 10. But I found when I using `model_ckpt-10000` which contains the global step number, tensorflow can load the parameters successfully.

**Comment by girving** [comment]
@rohan100jain What's the status?

**Comment by IceCubePill** [comment]
@gsh199449  could you tell me about how to deal with this problem detailedly？I have the same problem too

**Comment by gsh199449** [comment]
@IceCubePill Add global step number after the model name, like "model_ckpt-10000". 10000 is the global step number. Use this file name in the load function.

**Comment by danielmogilny** [comment]
My issue happened between updates when Tensorflow changed its save system. I fixed it by downgrading to the old Tensorflow

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
A member of the TensorFlow organization has replied after the stat:awaiting tensorflower label was applied.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.
