### ISSUE TITLE
tf.data.Dataset.from_generator: TypeError: '>' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by dauso** [tensorflow/tensorflow#71330]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.13.1

### Custom code

Yes

### OS platform and distribution

Linux

### Python version

3.8

### Current behavior?

TF dataset created from numpy array and tensorf slices works fine while TF dataset created from generator passes Nonetype object to custom metric function and results in following error -

`    TypeError: '>' not supported between instances of 'NoneType' and 'int'`

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np
from tensorflow.keras.layers import Input, Conv2D
from tensorflow.keras.models import Model
from tensorflow.keras.metrics import MeanIoU

np.random.seed(1)

NUM_OF_CLASSES = 3

NUM_SAMPLES = 1000
BATCH_SIZE = 32
IMAGE_SIZE = (224, 224)

# Example dataset generation
input_images = np.random.rand(NUM_SAMPLES, IMAGE_SIZE[0], IMAGE_SIZE[1], 3).astype(np.float32)
masks = np.random.randint(0, NUM_OF_CLASSES, size=(NUM_SAMPLES, IMAGE_SIZE[0], IMAGE_SIZE[1]), dtype=np.int32)

class TestMeanIou(MeanIoU):
    def update_state(self, y_true, y_pred, sample_weight=None):
        y_true = tf.cast(y_true, tf.int32)
        return super().update_state(y_true, tf.argmax(y_pred, axis=-1), sample_weight)

# Example dataset generation function
def generate_dataset(num_samples):
    for i in range(num_samples):
        input_image = input_images[i]
        mask = masks[i]

        yield input_image, mask

def from_generator():
    print("\ntf.data.Dataset.from_generator")

    dataset = tf.data.Dataset.from_generator(generate_dataset, args=[NUM_SAMPLES],
                    output_types=(tf.float32, tf.int32, tf.float32))
    dataset = dataset.batch(BATCH_SIZE).prefetch(buffer_size=tf.data.AUTOTUNE)

    return dataset

def process_data(input_image, mask):
    # example process function
    return input_image, mask

def from_numpy_array():
    print("\ntf.data.Dataset.from_tensor_slices")

    dataset = tf.data.Dataset.from_tensor_slices((input_images, masks))
    dataset = dataset.map(process_data)
    dataset = dataset.shuffle(NUM_SAMPLES).batch(BATCH_SIZE).prefetch(buffer_size=tf.data.AUTOTUNE)

    return dataset

if __name__=='__main__':
    input_image = Input(shape=(IMAGE_SIZE[0], IMAGE_SIZE[1], 3))
    output = Conv2D(NUM_OF_CLASSES, 1, activation='softmax', name='output')(input_image)

    model = Model(inputs=input_image, outputs=[output])
    model.compile(optimizer='adam',
                  loss={'output': 'sparse_categorical_crossentropy'},
                  metrics={'output': [TestMeanIou(num_classes=NUM_OF_CLASSES)]})
    model.summary()


    '''
    tf.data.Dataset.from_tensor_slices
    This works
    '''
    dataset = from_numpy_array()

    model.fit(dataset, epochs=2)    # train


    '''
    tf.data.Dataset.from_generator
    This results in following error -

    File "./venv/lib/python3.8/site-packages/keras/src/metrics/iou_metrics.py", line 123, in update_state  **
        if y_true.shape.ndims > 1:

    TypeError: '>' not supported between instances of 'NoneType' and 'int'
    '''
    # get tf dataset
    dataset = from_generator()

    model.fit(dataset, epochs=2)    # train
```

### Relevant log output

```shell
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
=================================================================
 input_1 (InputLayer)        [(None, 224, 224, 3)]     0         
                                                                 
 output (Conv2D)             (None, 224, 224, 3)       12        
                                                                 
=================================================================
Total params: 12 (48.00 Byte)
Trainable params: 12 (48.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

tf.data.Dataset.from_tensor_slices
Epoch 1/2
32/32 [==============================] - 2s 43ms/step - loss: 1.1880 - test_mean_iou: 0.1375
Epoch 2/2
32/32 [==============================] - 1s 42ms/step - loss: 1.1675 - test_mean_iou: 0.1479

tf.data.Dataset.from_generator
Epoch 1/2
Traceback (most recent call last):
  File "tf_dataset_test.py", line 86, in <module>
    model.fit(dataset, epochs=2)    # train
  File "./venv/lib/python3.8/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/tmp/7993776.1.aib4.q/__autograph_generated_filevzr2jken.py", line 15, in tf__train_function
    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
  File "/tmp/7993776.1.aib4.q/__autograph_generated_fileqrp0encq.py", line 14, in tf__update_state
    retval_ = ag__.converted_call(ag__.converted_call(ag__.ld(super), (), None, fscope).update_state, (ag__.ld(y_true), ag__.converted_call(ag__.ld(tf).argmax, (ag__.ld(y_pred),), dict(axis=(- 1)), fscope), ag__.ld(sample_weight)), None, fscope)
TypeError: in user code:

    File "./venv/lib/python3.8/site-packages/keras/src/engine/training.py", line 1338, in train_function  *
        return step_function(self, iterator)
    File "tf_dataset_test.py", line 22, in update_state  *
        return super().update_state(y_true, tf.argmax(y_pred, axis=-1), sample_weight)
    File "./venv/lib/python3.8/site-packages/keras/src/metrics/iou_metrics.py", line 123, in update_state  **
        if y_true.shape.ndims > 1:

    TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

**Comment by tilakrayal** [comment]
@dauso,
You should use `sample_weight` instead. `class_weight` is not supported for 3+ dimensional targets because the concept of class is ambiguous in that case.

Also please try to take a look at the similar issues for the reference.
https://github.com/tensorflow/tensorflow/issues/47032
https://github.com/keras-team/keras/issues/3653
https://github.com/tensorflow/tensorflow/issues/43248

Thank you!

**Comment by dauso** [comment]
- This is not a weights issue, right? There are no weights provided, only input image and mask arrays. The error is about **y_true** in the IoU metric function.
- The example code given above also shows 2D arrays, not 3D. If you change input image images from 3 channel to a grayscale, we still get the same behavior.

Changing the IoU metric function above to print arguments shows the difference in `y_true`.

```
class TestMeanIou(MeanIoU):
    def update_state(self, y_true, y_pred, sample_weight=None):
        print("y_true", type(y_true), y_true)
        print("y_pred", type(y_pred), y_pred)
        print("sample_weight", type(sample_weight), sample_weight)

        y_true = tf.cast(y_true, tf.int32)
        return super().update_state(y_true, tf.argmax(y_pred, axis=-1), sample_weight)
 ```
 
**Output logs:**

Numpy (`tf.data.Dataset.from_tensor_slices`) -
**y_true: Tensor("IteratorGetNext:1", shape=(None, 224, 224), dtype=int32)**
```
y_true <class 'tensorflow.python.framework.ops.Tensor'> Tensor("IteratorGetNext:1", shape=(None, 224, 224), dtype=int32)
y_pred <class 'tensorflow.python.framework.ops.Tensor'> Tensor("model/output/Softmax:0", shape=(None, 224, 224, 3), dtype=float32)
sample_weight <class 'NoneType'> None
```

Generator (`tf.data.Dataset.from_generator`) -
**y_true: Tensor("IteratorGetNext:1", dtype=int32)**
```
y_true <class 'tensorflow.python.framework.ops.Tensor'> Tensor("IteratorGetNext:1", dtype=int32)
y_pred <class 'tensorflow.python.framework.ops.Tensor'> Tensor("model/output/Softmax:0", shape=(None, None, None, 3), dtype=float32)
sample_weight <class 'NoneType'> None
```

**Comment by dauso** [comment]
Based on [@yufengma reply](https://github.com/tensorflow/tensorflow/issues/43248#issuecomment-804594808) in #43248, adding `output_shapes` fixed the issue.

```
def from_generator():
    print("\ntf.data.Dataset.from_generator")

    dataset = tf.data.Dataset.from_generator(generate_dataset, args=[NUM_SAMPLES],
                    output_types=(tf.float32, tf.int32),
                    output_shapes=((IMAGE_SIZE[0], IMAGE_SIZE[1], 3), (IMAGE_SIZE[0], IMAGE_SIZE[1]))
                    )
    dataset = dataset.batch(BATCH_SIZE).prefetch(buffer_size=tf.data.AUTOTUNE)
```
