### ISSUE TITLE
TFLite-Model-Maker running error: AttributeError: module 'numpy' has no attribute 'object'.

### ISSUE THREAD

**Issue by libofei2004** [tensorflow/tensorflow#71587]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

tf2.9.3

### Custom code

Yes

### OS platform and distribution

windows11

### Python version

3.9

### Current behavior?

I installed TFLite-Model-Maker with command : pip3 install tflite-model-maker , 
and run my code:

```
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'
import numpy as np
print("numpy version:", np.__version__)
import os
import tensorflow as tf
from tflite_model_maker import model_spec
from tflite_model_maker import object_detector
from tflite_model_maker.object_detector import DataLoader

data_dir = 'C:\\workspace\\imgupload\\img\\selected1\\bt3\\train\\shot'

data_loader = DataLoader.from_pascal_voc(data_dir)

train_data, validation_data, test_data = data_loader.load()

model_spec = model_spec.get('efficientdet_lite0')

model = object_detector.create(train_data, model_spec=model_spec, validation_data=validation_data, epochs=50, batch_size=8, train_whole_model=True)

print(model.evaluate(test_data))

model.export(export_dir='./exported_model')
```

The error is reported:
FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  np.uint8, np.uint16, np.object, np.bool]
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\libof\myenv1\lib\site-packages\tflite_model_maker\__init__.py", line 44, in <module>
    from tflite_model_maker import audio_classifier
  File "C:\Users\libof\myenv1\lib\site-packages\tflite_model_maker\audio_classifier\__init__.py", line 24, in <module>
    from tensorflow_examples.lite.model_maker.core.data_util.audio_dataloader import DataLoader
  File "C:\Users\libof\myenv1\lib\site-packages\tensorflow_examples\lite\model_maker\core\data_util\audio_dataloader.py", line 27, in <module>
    from tensorflow_examples.lite.model_maker.core.task.model_spec import audio_spec
  File "C:\Users\libof\myenv1\lib\site-packages\tensorflow_examples\lite\model_maker\core\task\model_spec\__init__.py", line 20, in <module>
    from tensorflow_examples.lite.model_maker.core.task.model_spec import audio_spec
  File "C:\Users\libof\myenv1\lib\site-packages\tensorflow_examples\lite\model_maker\core\task\model_spec\audio_spec.py", line 29, in <module>
    from tensorflow_examples.lite.model_maker.core.task import model_util
  File "C:\Users\libof\myenv1\lib\site-packages\tensorflow_examples\lite\model_maker\core\task\model_util.py", line 28, in <module>
    from tensorflowjs.converters import converter as tfjs_converter
  File "C:\Users\libof\myenv1\lib\site-packages\tensorflowjs\__init__.py", line 21, in <module>
    from tensorflowjs import converters
  File "C:\Users\libof\myenv1\lib\site-packages\tensorflowjs\converters\__init__.py", line 21, in <module>
    from tensorflowjs.converters.converter import convert
  File "C:\Users\libof\myenv1\lib\site-packages\tensorflowjs\converters\converter.py", line 35, in <module>
    from tensorflowjs.converters import keras_h5_conversion as conversion
  File "C:\Users\libof\myenv1\lib\site-packages\tensorflowjs\converters\keras_h5_conversion.py", line 33, in <module>
    from tensorflowjs import write_weights  # pylint: disable=import-error
  File "C:\Users\libof\myenv1\lib\site-packages\tensorflowjs\write_weights.py", line 25, in <module>
    from tensorflowjs import read_weights
  File "C:\Users\libof\myenv1\lib\site-packages\tensorflowjs\read_weights.py", line 28, in <module>
    np.uint8, np.uint16, np.object, np.bool]
  File "C:\Users\libof\myenv1\lib\site-packages\numpy\__init__.py", line 353, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20;

![image](https://github.com/tensorflow/tensorflow/assets/10001548/a4184a14-8bda-45a6-a1c5-c211eafb0959)
![image](https://github.com/tensorflow/tensorflow/assets/10001548/b6c2b355-4b7c-458d-9e8b-59f7418b09ee)

### Standalone code to reproduce the issue

```shell
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'
import numpy as np
print("numpy version:", np.__version__)
import os
import tensorflow as tf
from tflite_model_maker import model_spec
from tflite_model_maker import object_detector
from tflite_model_maker.object_detector import DataLoader

data_dir = 'C:\\workspace\\imgupload\\img\\selected1\\bt3\\train\\shot'

data_loader = DataLoader.from_pascal_voc(data_dir)

train_data, validation_data, test_data = data_loader.load()

model_spec = model_spec.get('efficientdet_lite0')

model = object_detector.create(train_data, model_spec=model_spec, validation_data=validation_data, epochs=50, batch_size=8, train_whole_model=True)

print(model.evaluate(test_data))

model.export(export_dir='./exported_model')
```

**Comment by tilakrayal** [comment]
@libofei2004,
This issue is the known issue, Could you please use [mediapipe model maker](https://developers.google.com/mediapipe/solutions/model_maker) instead for now. Here is also a [gist](https://colab.sandbox.google.com/gist/pkgoogle/93fb7581fab1ea14728c61adf584ca13/media_pipe_example.ipynb) that runs through some image classification examples with mediapipe model maker, including quantization: gist. If you can't accomplish your goals with mediapipe-model-maker please let us know and we'll see if there is a way to accomplish your goals.

https://github.com/tensorflow/tensorflow/issues/60431

Thank you!

**Comment by libofei2004** [comment]
@tilakrayal Thank you, now I have installed mediapipe_model_maker, but when I run my code, the error occured:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\libof\env1\lib\site-packages\mediapipe_model_maker\__init__.py", line 17, in <module>
    from mediapipe_model_maker.python.vision import image_classifier
  File "C:\Users\libof\env1\lib\site-packages\mediapipe_model_maker\python\vision\image_classifier\__init__.py", line 16, in <module>
    from mediapipe_model_maker.python.vision.image_classifier import dataset
  File "C:\Users\libof\env1\lib\site-packages\mediapipe_model_maker\python\vision\image_classifier\dataset.py", line 21, in <module>
    import tensorflow_datasets as tfds
  File "C:\Users\libof\env1\lib\site-packages\tensorflow_datasets\__init__.py", line 43, in <module>
    import tensorflow_datasets.core.logging as _tfds_logging
  File "C:\Users\libof\env1\lib\site-packages\tensorflow_datasets\core\__init__.py", line 22, in <module>
    from tensorflow_datasets.core import community
  File "C:\Users\libof\env1\lib\site-packages\tensorflow_datasets\core\community\__init__.py", line 18, in <module>
    from tensorflow_datasets.core.community.huggingface_wrapper import mock_builtin_to_use_gfile
  File "C:\Users\libof\env1\lib\site-packages\tensorflow_datasets\core\community\huggingface_wrapper.py", line 31, in <module>
    from tensorflow_datasets.core import dataset_builder
  File "C:\Users\libof\env1\lib\site-packages\tensorflow_datasets\core\dataset_builder.py", line 34, in <module>
    from tensorflow_datasets.core import dataset_info
  File "C:\Users\libof\env1\lib\site-packages\tensorflow_datasets\core\dataset_info.py", line 47, in <module>
    from tensorflow_datasets.core import file_adapters
  File "C:\Users\libof\env1\lib\site-packages\tensorflow_datasets\core\file_adapters.py", line 29, in <module>
    from array_record.python import array_record_module
ImportError: cannot import name 'array_record_module' from 'array_record.python' (C:\Users\libof\env1\lib\site-packages\array_record\python\__init__.py)

my code is:
`import os
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'
 
from mediapipe_model_maker import object_detector

train_dataset_path = 'C:\\workspace\\imgupload\\img\\selected1\\bt3\\train\\shot'
validation_dataset_path = 'C:\\workspace\\imgupload\\img\\selected1\\bt3\\train\\shot'
cache_dir = 'C:\\workspace\\imgupload\\img\\selected1\\tmp'

train_data = object_detector.Dataset.from_pascal_voc_folder(
    train_dataset_path,
    cache_dir=cache_dir)
 
validate_data = object_detector.Dataset.from_pascal_voc_folder(
    validation_dataset_path,
    cache_dir=cache_dir)

hparams = object_detector.HParams(batch_size=8, learning_rate=0.3, epochs=50, export_dir='exported_model')
options = object_detector.ObjectDetectorOptions(
    supported_model=object_detector.SupportedModels.MOBILENET_V2,
    hparams=hparams)

model = object_detector.ObjectDetector.create(
    train_data=train_data,
    validation_data=validate_data,
    options=options)

loss, coco_metrics = model.evaluate(validate_data, batch_size=4)
print(f"Validation loss: {loss}")
print(f"Validation coco metrics: {coco_metrics}")

model.export_model('dogs.tflite')`

![image](https://github.com/user-attachments/assets/b4efb490-ef13-41e3-8c4c-f8f36e419aa6)

**Comment by sawantkumar** [comment]
Hi @libofei2004 ,

I am not able to replicate this issue since i keep getting the below error, can you please upload a jupyter notebook with the code and the dataset so that i will be able to replicate this issue ?

`    return cache_files.TFRecordCacheFiles(
  File "<string>", line 6, in __init__
  File "/home/sawantkumar/work/python_wor/myenv/lib/python3.9/site-packages/mediapipe_model_maker/python/core/data/cache_files.py", line 53, in __post_init__
    raise ValueError(
ValueError: num_shards must be greater than 0, got 0`

**Comment by libofei2004** [comment]
@sawantkumar  my code is shown above. I think the problem is caused by conflicting versions of dependencies.

**Comment by libofei2004** [comment]
@tilakrayal I use "pip3 install mediapipe-model-maker“ to install mediapipe-model-maker,  my version is 0.1.0.1,  but the latest version is 0.2.1.4 in https://pypi.org/project/mediapipe-model-maker/, I don't know why?

**Comment by pkgoogle** [comment]
Hi @libofei2004, there is probably some weird conflict w/ your previous installation.. can you try with a fresh conda environment or a fresh venv python environment? Let us know what happens.
