### ISSUE TITLE
Can't quantize nodes of an RNN ("The node has inputs from different frames.")

### ISSUE THREAD

**Issue by reuben** [tensorflow/tensorflow#7162]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

I found a few similar, but not equivalent, problems with frozen/quantized graphs:

Cannot import graph_def for 8-bit Quantized cnn model #5470

tf.import_graph_def: graph_def is invalid at node #4044

Unable to import frozen graph with batchnorm #3628 

### Environment info
Operating System: Ubuntu 16.10

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

```
-rw-r--r-- 1 root root   558720 Sep 14 20:02 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 Sep 14 20:05 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root root       19 Sep 14 20:05 /usr/local/cuda/lib64/libcudart.so.8.0 -> libcudart.so.8.0.44
-rw-r--r-- 1 root root   415432 Sep 14 20:02 /usr/local/cuda/lib64/libcudart.so.8.0.44
-rw-r--r-- 1 root root   775162 Sep 14 20:02 /usr/local/cuda/lib64/libcudart_static.a
lrwxrwxrwx 1 root root       13 Jan 27 22:01 /usr/local/cuda/lib64/libcudnn.so -> libcudnn.so.5
lrwxrwxrwx 1 root root       17 Jan 27 22:01 /usr/local/cuda/lib64/libcudnn.so.5 -> libcudnn.so.5.1.5
-rwxr-xr-x 1 root root 79337624 Jan 27 22:01 /usr/local/cuda/lib64/libcudnn.so.5.1.5
-rw-r--r-- 1 root root 69756172 Jan 27 22:01 /usr/local/cuda/lib64/libcudnn_static.a
```

If installed from binary pip package, provide:

1. A link to the pip package you installed: https://pypi.python.org/pypi/tensorflow-gpu
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`:

```
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
0.12.1
```

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

I reduced this to a simple RNN model available here on branch tf_issue_7162: https://github.com/reuben/tf-export-test/tree/tf_issue_7162

You don't have to train it again, the repository includes a checkpoint with trained weights. If you run the commands starting from the freeze_graph in the [README](https://github.com/reuben/tf-export-test/blob/master/README.md) there, you get this error when importing the quantized graph:

```
Traceback (most recent call last):
  File "import.py", line 14, in <module>
    imports = tf.import_graph_def(pb, name="")
  File "/home/reuben/.local/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 339, in import_graph_def
    % (input_name,)))
ValueError: graph_def is invalid at node u'RNN/cond/Greater/y': More inputs specified ('RNN/cond/Switch:0') than the op expects..
```

**Comment by reuben** [comment]
This error happens whether or not you freeze the graph first.

**Comment by reuben** [comment]
I can still reproduce this with TensorFlow 1.0.

**Comment by reuben** [comment]
I reduced the test case to a much simpler graph:

```python
lstm_cell = tf.contrib.rnn.BasicLSTMCell(64)

outputs, _ = tf.nn.dynamic_rnn(lstm_cell,
    dtype=tf.float32,
    inputs=tf.constant([[[1.,1.,1.]], [[1.,1.,0.]]]),
    sequence_length=tf.constant([3,2]))

pred = tf.add(outputs, tf.constant(0.), name="y")
```

I reused the repository for a different (but related) issue, #7949. So the code for this is now on branch tf_issue_7162 there: https://github.com/reuben/tf-export-test/tree/tf_issue_7162

**Comment by reuben** [comment]
Over in issue #7949 @petewarden suggested that I use the new transform_graph tool instead of quantize_graph.py, and that worked for weights quantization. On the other hand, when using that tool to quantize the graph, I run into a different problem:

```
Traceback (most recent call last):
  File "import.py", line 19, in <module>
    result = sess.run(y)
  File "/home/reuben/.virtualenvs/deepspeech/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/reuben/.virtualenvs/deepspeech/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/reuben/.virtualenvs/deepspeech/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/reuben/.virtualenvs/deepspeech/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: The node 'rnn/while/basic_lstm_cell/basic_lstm_cell/MatMul_eightbit/rnn/while/basic_lstm_cell/basic_lstm_cell/MatMul/Enter/reshape' has inputs from different frames. The input 'rnn/while/basic_lstm_cell/basic_lstm_cell/MatMul/Enter' is in frame 'rnn/while/rnn/while/'. The input 'rnn/while/basic_lstm_cell/basic_lstm_cell/MatMul_eightbit/rnn/while/basic_lstm_cell/basic_lstm_cell/concat/reshape_dims' is in frame ''.
```

This, coincidentally, is the same problem I was running into originally over in issue #7949.

**Comment by saria85** [comment]
hi

I am getting this error when doing optimization

ValueError: graph_def is invalid at node 'word_embeddings/Variable/Assign': Input tensor 'word_embeddings/Variable:0' Cannot convert a tensor of type float32 to an input of type float32_ref

input_graph_def = tf.GraphDef()
    checkpoint = tf.train.get_checkpoint_state(model_dir)
    input_checkpoint = checkpoint.model_checkpoint_path

    absolute_model_folder = "/".join(input_checkpoint.split('/')[:-1])
    output_graph = absolute_model_folder + "/frozen_model.pb"

    with tf.gfile.FastGFile(output_graph, 'rb') as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
        _ = tf.import_graph_def(graph_def, name='')
    output_graph_def = optimize_for_inference_lib.optimize_for_inference(
        graph_def,
        [''],
        [''],
        tf.float32.as_datatype_enum)
 any help is greatly appreciated

**Comment by petewarden** [comment]
Can you share the graph file you're using and the command line you're running? You can either share it as an attachment here, or email it to petewarden@google.com. That will help me debug what's going wrong.

**Comment by kdavis-mozilla** [comment]
@petewarden Did you see the minimal example @reuben set up[[1](https://github.com/reuben/tf-export-test/tree/tf_issue_7162)].

**Comment by wodesuck** [comment]
Any progress? I meet the same issues as [reubne mentioned](https://github.com/tensorflow/tensorflow/issues/7162#issuecomment-283412259).

**Comment by wodesuck** [comment]
@reuben @petewarden I fixed it by adding control input to the constant node #9792

**Comment by lissyx** [comment]
Looks like this fixes the problem on our network as well. I just tested applying the documented transforms for "8 bits calculations", and the resulting file does indeed work.

More precisely, `add_default_attributes strip_unused_nodes(type=float, shape="1,299,299,3") remove_nodes(op=Identity, op=CheckNumerics) fold_old_batch_norms quantize_weights quantize_nodes strip_unused_nodes sort_by_execution_order'` produced a network where our "output_node" is removed.

But `add_default_attributes strip_unused_nodes(type=float, shape="1,299,299,3")  fold_old_batch_norms quantize_weights quantize_nodes strip_unused_nodes sort_by_execution_order'` produces a network where we can do inference.

**Comment by lissyx** [comment]
@wodesuck Experimenting with your fixed, I spotted that even models without a RNN layer (actually we do use `tf.nn.bidirectional_dynamic_rnn()`) do not report the same inference time. From the benchmark I could run locally, I identified, on our mozilla/DeepSpeech model nuking the bidirectionnal dynamic layers:
 - model 8-bitized with transform tool without any change shows inference time ~ 0.8secs
 - model 8-bitized with fixed transform tools shows inference time ~1.1secs

**Comment by wodesuck** [comment]
@lissyx Maybe the control inputs slow down the model. Actually, only for those nodes within a while loop (e.g. nodes in dynamic_rnn), it is necessary to add control inputs when quantizing them.

Personally, I add it iff the node name contain "/rnn/while/". This is a simple method but work for my model 😥, I think you can try it too. And I expect someone prove a more precise way to identify nodes in while loop 😄 .

**Comment by lissyx** [comment]
Thanks @wodesuck ! When you say that you add it if and only if the name contains `/rnn/while/`, I'm unsure about something: are you referring to transformation applied by `transform_graph` ? If so, it means you changed the code from your PR to limit the scope to control loops ?

**Comment by wodesuck** [comment]
@lissyx That's right.

Here is the code, it is not suit for general use (maybe someone have a node name "while" or a while loop name without "while"), so I don't add it in the PR. Besides, there's more works could do to optimize a specific model (run some benchmark & try to optimize the bottleneck), I had customized a lot in my `transform_graph`.
```c++
          // Add some common constants we need for reshaping inputs.
          NodeDef reshape_dims;
          reshape_dims.set_op("Const");
          reshape_dims.set_name(unique_input_name + "/reshape_dims");
          if (float_node.name().find("/while/") != string::npos) {
            AddNodeInput("^" + input_name, &reshape_dims);
          }
          SetNodeAttr("dtype", DT_INT32, &reshape_dims);
          Tensor reshape_dims_tensor(DT_INT32, {1});
          reshape_dims_tensor.flat<int32>()(0) = -1;
          SetNodeTensorAttr<int32>("value", reshape_dims_tensor, &reshape_dims);
          new_nodes->push_back(reshape_dims);

          NodeDef reduction_dims;
          reduction_dims.set_op("Const");
          reduction_dims.set_name(unique_input_name + "/reduction_dims");
          if (float_node.name().find("/while/") != string::npos) {
            AddNodeInput("^" + input_name, &reduction_dims);
          }
          SetNodeAttr("dtype", DT_INT32, &reduction_dims);
          Tensor reduction_dims_tensor(DT_INT32, {1});
          reduction_dims_tensor.flat<int32>()(0) = 0;
          SetNodeTensorAttr<int32>("value", reduction_dims_tensor,
                                   &reduction_dims);
          new_nodes->push_back(reduction_dims);
```

**Comment by lissyx** [comment]
Thanks for the confirmation @wodesuck

**Comment by philipperemy** [comment]
Any chance that this problem gets solved?

**Comment by yuanhua8** [comment]
I think this problem is not fully solved. quantize_graph.py still generate model with this issue. there is no explanation on this issue. why a const node need a control input dependency on another node?

**Comment by wodesuck** [comment]
@yuanhua8 First, `quantize_graph.py` seems no longer maintained, you could use `transform_graph` instead. Second, all nodes within a tf control loop need a property called "frame" to run properly, while quantization adding const nodes without "frame" will break it. So, it is necessary to add control input to make sure nodes having a correct "frame".

**Comment by yuanhua8** [comment]
@wodesuck, thanks daniel for your answer. I like the python code since more easy to modify it(for example I want to convert something in side meta_graph), but it looks a known bug not fixed in python code.... 
thanks for your information.

**Comment by yuanhua8** [comment]
also find that in bug in the quantize_graph.py which call remove_training_nodes. suppose a const name has a control dependency on an identity node which depend on switch node. after  idenity is remvoed. const should just have control dependency on switch node, not use switch node as input

**Comment by philipperemy** [comment]
@yuanhua8 yes they remove all the nodes that no do impact the inference of the output node specified.

But as you said, it might be a problem since many of us use the identity trick to name a node in the network.

**Comment by barak-hurwitz** [comment]
Hi,

I'm also getting similar errors ,trying to run inference after quantize_nodes transform operation in GTT.
Started with the code from NMT tutorial https://github.com/tensorflow/nmt
Freezed the graph into PB , used the GTT tool to transform the graph and load it back for the inference part. 

Error message : 
'dynamic_seq2seq/encoder/bidirectional_rnn/..../basic_lstm_cell/basic_lstm_cell/concat/reshape_dims' is in frame ''.

tried this solution , did'nt work. https://github.com/tensorflow/tensorflow/commit/17ce98437f34ab5439b3e46adb2eb5b692c48abd

any idea how to fix this issue? 
thanks

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
A member of the TensorFlow organization has replied after the stat:awaiting tensorflower label was applied.

**Comment by petewarden** [comment]
I believe this is related to #3628, since it seems like there are certain graphs we have trouble freezing due to their structure. I haven't had a chance to dig in deeper, but it seems worth keeping open since there seem to be multiple problems in this area. I'm also cc-ing Suharsh, since he's been looking at issues around freeze_graph.

**Comment by petewarden** [comment]
(reopening, since I hit the wrong button and just meant to comment!)

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @petewarden, @suharshs: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by dreamibor** [comment]
For any one who still got the problem:

TensorFlow fixed this issue in their source code from r1.5, but that comes with a new problem with graph binary version, so you have to keep using TensorFlow r1.5 or above to inference the quantized model.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @petewarden, @suharshs: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @petewarden, @suharshs: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @petewarden, @suharshs: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by efeiefei** [comment]
I have similar errors when quantize_nodes for [Tensor2Tensor Transformer](https://github.com/tensorflow/tensor2tensor) model.
It's no problem after freeze_graph, it's also no problem with quantize_weights. But when I qutize_nodes, it will:
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: The node 'transformer/while/body/parallel_0/body/decoder/layer_prepostprocess/layer_norm/add_1/eightbit' has inputs from different frames. The input 'transformer/while/body/parallel_0/body/decoder/layer_prepostprocess/layer_norm/add_1_eightbit/transformer/while/body/parallel_0/body/decoder/layer_prepostprocess/layer_norm/add_1/Enter/quantize' is in frame 'transformer/while/while_context'. The input 'transformer/while/body/parallel_0/body/decoder/layer_prepostprocess/layer_norm/mul_1/eightbit/requantize' is in frame ''.
```
I have tried TF1.4 and TF1.7, and the error is the same.
Can anyone help me?

**Comment by efeiefei** [comment]
@wodesuck @petewarden 
Can you help me?

**Comment by tensorflowbutler** [comment]
Nagging Assignees @petewarden, @suharshs: It has been 18 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @petewarden, @suharshs: It has been 33 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by lmatt-bit** [comment]
@efeiefei i have the same issue with transformer model. Do you fix it now?

**Comment by tensorflowbutler** [comment]
Nagging Assignees @petewarden, @suharshs: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @petewarden, @suharshs: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @petewarden, @suharshs: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @petewarden, @suharshs: It has been 60 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @petewarden, @suharshs, @raghuraman-k: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by zh794390558** [comment]
This is not work for me
```
--transforms='
  add_default_attributes
  strip_unused_nodes(type=float, shape="-1,480000")
  remove_nodes(op=CheckNumerics)
 fold_constants(ignore_errors=true)
  fold_batch_norms
  fold_old_batch_norms
  quantize_weights
  quantize_nodes
  strip_unused_nodes
  sort_by_execution_order
  '
```

But this work fine 

```
--transforms='
  add_default_attributes
  strip_unused_nodes(type=float, shape="-1,480000")
  remove_nodes(op=CheckNumerics)
  fold_batch_norms
  fold_old_batch_norms
  quantize_weights
  quantize_nodes
  strip_unused_nodes
  sort_by_execution_order
  '
```

**Comment by wt-huang** [comment]
Closing this for now as there is a working solution.

**Comment by rzou15** [comment]
> @efeiefei i have the same issue with transformer model. Do you fix it now?

I also met this issue. Did you fix it? and would you plz share? Many thx!
