### ISSUE TITLE
freeze graph fail by using the published checkpoint file: Attempting to use uninitialized value

### ISSUE THREAD

**Issue by civilman628** [tensorflow/tensorflow#7172]
I am using the latest Tensorflow code on Ubuntu 16.04

1. I download **Inception-ResNet-v2** model from the link https://github.com/tensorflow/models/tree/master/slim    
the check point file is:
http://download.tensorflow.org/models/inception_resnet_v2_2016_08_30.tar.gz

2. use the code below to get graph define, which output is **graph.pbtxt**

```
import tensorflow as tf
from nets import inception_resnet_v2
import numpy as np

x = tf.placeholder(shape=[1,299,299,3], dtype=tf.float32)
inception_resnet_v2 = inception_resnet_v2.inception_resnet_v2(x)

sess = tf.Session()
tf.train.write_graph(sess.graph_def, './', 'graph.pbtxt')
```
3, use the freeze graph tool to get **.pb** file. 

`bazel-bin/tensorflow/python/tools/freeze_graph
 --input_graph=/home/scopeserver/RaidDisk/DeepLearning/mwang/Model_backup2/slim/graph.pbtxt --input_checkpoint=/home/scopeserver/RaidDisk/DeepLearning/mwang/Model_backup2/slim/inception_resnet_v2_2016_08_30.ckpt  
--output_graph=/tmp/frozen_graph.pb --output_node_names=InceptionResnetV2/Logits/Predictions`

i get the error:

```
Traceback (most recent call last):
  File "/home/scopeserver/RaidDisk/DeepLearning/mwang/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 218, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/scopeserver/RaidDisk/DeepLearning/mwang/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/scopeserver/RaidDisk/DeepLearning/mwang/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 150, in main
    FLAGS.variable_names_blacklist)
  File "/home/scopeserver/RaidDisk/DeepLearning/mwang/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 138, in freeze_graph
    variable_names_blacklist=variable_names_blacklist)
  File "/home/scopeserver/RaidDisk/DeepLearning/mwang/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/framework/graph_util_impl.py", line 218, in convert_variables_to_constants
    returned_variables = sess.run(variable_names)
  File "/home/scopeserver/RaidDisk/DeepLearning/mwang/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/scopeserver/RaidDisk/DeepLearning/mwang/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/scopeserver/RaidDisk/DeepLearning/mwang/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/scopeserver/RaidDisk/DeepLearning/mwang/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: **Attempting to use uninitialized value InceptionResnetV2/Repeat_1/block17_16/Branch_1/Conv2d_0c_7x1/biases**
	 [[Node: _send_InceptionResnetV2/Repeat_1/block17_16/Branch_1/Conv2d_0c_7x1/biases_0 = _Send[T=DT_FLOAT, client_terminated=true, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=4447330825950993621, tensor_name="InceptionResnetV2/Repeat_1/block17_16/Branch_1/Conv2d_0c_7x1/biases:0", _device="/job:localhost/replica:0/task:0/cpu:0"](InceptionResnetV2/Repeat_1/block17_16/Branch_1/Conv2d_0c_7x1/biases)]]


```

**Comment by civilman628** [comment]
I try to freeze the model: inception v2, and get similar error as well. Please notice you need change num_classes=1000, to num_classes=1001 in .py file.

Traceback (most recent call last):
  File "/home/scopeserver/RaidDisk/DeepLearning/mwang/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 218, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/scopeserver/RaidDisk/DeepLearning/mwang/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/scopeserver/RaidDisk/DeepLearning/mwang/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 150, in main
    FLAGS.variable_names_blacklist)
  File "/home/scopeserver/RaidDisk/DeepLearning/mwang/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 138, in freeze_graph
    variable_names_blacklist=variable_names_blacklist)
  File "/home/scopeserver/RaidDisk/DeepLearning/mwang/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/framework/graph_util_impl.py", line 218, in convert_variables_to_constants
    returned_variables = sess.run(variable_names)
  File "/home/scopeserver/RaidDisk/DeepLearning/mwang/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/scopeserver/RaidDisk/DeepLearning/mwang/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/scopeserver/RaidDisk/DeepLearning/mwang/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/scopeserver/RaidDisk/DeepLearning/mwang/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: **Attempting to use uninitialized value InceptionV2/Mixed_3b/Branch_1/Conv2d_0a_1x1/biases**
	 [[Node: _send_InceptionV2/Mixed_3b/Branch_1/Conv2d_0a_1x1/biases_0 = _Send[T=DT_FLOAT, client_terminated=true, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=8458274957196541200, tensor_name="InceptionV2/Mixed_3b/Branch_1/Conv2d_0a_1x1/biases:0", _device="/job:localhost/replica:0/task:0/cpu:0"](InceptionV2/Mixed_3b/Branch_1/Conv2d_0a_1x1/biases)]]

**Comment by civilman628** [comment]
so the question is how to freeze the published .ckpt model files successfully

**Comment by yaroslavvb** [comment]
You are not using correct model for that checkpoint, as you mention in referenced issues, pre-trained checkpoint files are useless by themselves, you need to use the code that created the model that generated it.

**Comment by yaroslavvb** [comment]
I think this is a documentation issue, can you say where you found the place that mentions the checkpoint (http://download.tensorflow.org/models/inception_resnet_v2_2016_08_30.tar.gz). That same document should also describe how to load it

**Comment by Lucas2012** [comment]
I'm also curious about how to use/load the checkpoint model. I tried using the nets.inception_v4 or nets.inception_res_v2 codes but it didn't work for me. #7173 

Thanks.

**Comment by yaroslavvb** [comment]
@sguada -- do you know how are people coming across these checkpoints/where the docs should go?

**Comment by civilman628** [comment]
I download the checkpoint file from the page: https://github.com/tensorflow/models/tree/master/slim

You can see a table here: https://github.com/tensorflow/models/tree/master/slim#pre-trained-models

It has all checkpoint files for inception v1-v4... I just use the published check point files.

**Comment by Lucas2012** [comment]
@yaroslavvb I also got the checkpoint files from the webpage @civilman628 mentioned.

**Comment by yaroslavvb** [comment]
I see....it may be a problem with the checkpoints then, that page lists @nathansilberman @sguada  are maintainers

**Comment by civilman628** [comment]
i figure out how to use them. the code below is to export .pbtxt file for inception_resnet_v2.

Use this .pbtxt and the published .ckpt to  freeze graph, if you want to get .pb file.

if you want to load other models or get other .pbtxt files, just change the key word **inception_resnet_v2** to other model name, such as **inception_v2**, **inception_v3**

the first node of .pb file is **Placeholder**, which is the input 4D tensor of image, such as [1,299,299,3]

```
import tensorflow as tf
import tensorflow.contrib.slim as slim
from nets.inception_resnet_v2 import inception_resnet_v2, inception_resnet_v2_arg_scope
import numpy as np

height = 299
width = 299
channels = 3

# Create graph
X = tf.placeholder(tf.float32, shape=[None, height, width, channels])
with slim.arg_scope(inception_resnet_v2_arg_scope()):
    logits, end_points = inception_resnet_v2(X, num_classes=1001,is_training=False)
predictions = end_points["Predictions"]
saver = tf.train.Saver()

X_test = np.ones((1,299,299,3))  # a fake image, you can use your own image

# Execute graph
with tf.Session() as sess:
    saver.restore(sess, "./inception_resnet_v2.ckpt")
    predictions_val = predictions.eval(feed_dict={X: X_test})
    tf.train.write_graph(sess.graph_def, './', 'resnetv2.pbtxt')
```

**Comment by civilman628** [comment]
the cmd to free graph for the model, pay attention to ouput node name, you can get it from .pbtxt file.

bazel-bin/tensorflow/python/tools/freeze_graph --input_graph=/home/scopeserver/RaidDisk/DeepLearning/resnetv2.pbtxt --input_checkpoint=/home/scopeserver/RaidDisk/DeepLearning/slim/inception_resnet_v2.ckpt --output_graph=./inception_resetv2.pb --output_node_names=**InceptionResnetV2/Logits/Predictions**

**Comment by sguada** [comment]
No sure why this is assigned to me, seems solved. Feel free to re-open if there is still an issue.

**Comment by lminer** [comment]
I am getting this issue when I try to freeze the graph from a checkpoint file for a model that I created myself. I was not seeing this error in 0.12.x

**Comment by brucelau-github** [comment]
I have the same issue on how to use my fine-tuned checkpoint files to predict the image. I will try freeze graph now. the document is very poor on this topic.

**Comment by chenweiqian** [comment]
@civilman628 hi, i run tensorflow SSD model on android. The android studio didn't throw error. But i can't detect anything.I test my pb file, it's seems right. I don't know why. could you give me some advices? Thanks!!

**Comment by abhiML** [comment]
Hi @civilman628 could you explain in detail as to how to get the output_node_names from the .pbtxt file?

**Comment by civilman628** [comment]
@abhiML  you need read the paper to see which node is for prediction. .pbtxt contains all node names.

**Comment by anne1994** [comment]
@civilman628 
I have used the slim/inception_v3 model. 
finetuned it and got the graph.pbtxt , .cpkt files. 
I am trying to freeze the finetuned result( graph.pbtxt, .cpkt) but I am getting the same error. How did you get past the error to generate a frozen.pb ?

**Comment by anne1994** [comment]
my errors:
1)
Traceback (most recent call last):
  File "freeze_graph.py", line 255, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "freeze_graph.py", line 187, in main
    FLAGS.variable_names_blacklist)
  File "freeze_graph.py", line 179, in freeze_graph
    variable_names_blacklist)
  File "freeze_graph.py", line 116, in freeze_graph_with_def_protos
    variable_names_blacklist=variable_names_blacklist)
TypeError: convert_variables_to_constants() got an unexpected keyword argument 'variable_names_blackl          ist'

2)
Traceback (most recent call last):
  File "freeze_graph.py", line 255, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "freeze_graph.py", line 187, in main
    FLAGS.variable_names_blacklist)
  File "freeze_graph.py", line 179, in freeze_graph
    variable_names_blacklist)
  File "freeze_graph.py", line 115, in freeze_graph_with_def_protos
    output_node_names.split(","))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/graph_util_impl.py", line 226, in co                    nvert_variables_to_constants
    returned_variables = sess.run(variable_names)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value accuracy                    /total
         [[Node: accuracy/total/_1558 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/                    replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor                    _name="edge_1172_accuracy/total", _device="/job:localhost/replica:0/task:0/gpu:0"](accuracy/total)]]

**Comment by parthg** [comment]
To add my 2 cents:

If the final goal is to use a pre-trained model to predict or extract features for new images, there is no need to generate intermediate .pbtxt file and consecutively freeze it. If you already know the layer names, below is the example of how to use ResNet50 model to extract features (inspired a bit from @civilman628 's answer and documentation on [resnet_v1.py](https://github.com/tensorflow/models/blob/master/slim/nets/resnet_v1.py)):

```python
from tensorflow.contrib.slim.nets import resnet_v1
import tensorflow as tf
import tensorflow.contrib.slim as slim

# Create graph
inputs = tf.placeholder(tf.float32, shape=[batch_size, height, width, channels])
with slim.arg_scope(resnet_v1.resnet_arg_scope()):
        net, end_points = resnet_v1.resnet_v1_50(inputs, is_training=False)

saver = tf.train.Saver()    

with tf.Session() as sess:
        saver.restore(sess, '.resnet_v1_50.ckpt')
        representation_tensor = sess.graph.get_tensor_by_name('resnet_v1_50/pool5:0') # if you don't know names like these, consider referring to corresponding model file or generate .pbtxt file as mentioned in  @civilman628 's answer above
        img = ...  #load image here with size [1, 224,224, 3]
        features = sess.run(representation_tensor, {'Placeholder:0': x})
```

**Comment by abviv** [comment]
One of the issue which i'm facing is 
1) I have a pre-trained model created with a  frozen graph.py with the file name classify_image_graph_def.pb, how do i make a predictions with just this file alone. I'm new to TF and there are lots of formats and its quite confusing. 
2) I have a folder and it contains a set of images on which i have to make a predictions.

**Comment by ldocao** [comment]
did you have a look at #6953 ?

**Comment by bikong2** [comment]
@civilman628 
followed your solution, it's ok! many thanks

**Comment by amaresh943** [comment]
i downloaded the pre-trained model "faster_rcnn_inception_v2_coco_2018_01_28" to detect objects using opencv3.4.1 in object detection c++, but in this folder there is no any .pbtxt file, so it is not running. can anyone help me to get the .pbtxt file for the "faster_rcnn_inception_v2_coco_2018_01_28" ???
