### ISSUE TITLE
MacOSX ImportError: dlopen(/usr/local/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): Library not loaded: @rpath/libcudart.8.0.dylib

### ISSUE THREAD

**Issue by tloo** [tensorflow/tensorflow#7174]
Installed tensorflow for python3.5 on Mac, try the testing code as follows: 

```
import tensorflow as tf

hello = tf.constant("test")
sess = tf.Session()
print(sess.run(hello))
```

It is working when run it from the terminal. But if I run it from eclipse, will get this exception:
```
warning: Debugger speedups using cython not found. Run '"/usr/local/bin/python3.5" "/Users/leitian/.p2/pool/plugins/org.python.pydev_5.5.0.201701191708/pysrc/setup_cython.py" build_ext --inplace' to build.
pydev debugger: starting (pid: 978)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/usr/local/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): Library not loaded: @rpath/libcudart.8.0.dylib
  Referenced from: /usr/local/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/leitian/.p2/pool/plugins/org.python.pydev_5.5.0.201701191708/pysrc/pydevd.py", line 1537, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Users/leitian/.p2/pool/plugins/org.python.pydev_5.5.0.201701191708/pysrc/pydevd.py", line 976, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/leitian/.p2/pool/plugins/org.python.pydev_5.5.0.201701191708/pysrc/_pydev_imps/_pydev_execfile.py", line 25, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/leitian/code/python/eclipse-ws/TestTF/Hello.py", line 1, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 60, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/usr/local/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): Library not loaded: @rpath/libcudart.8.0.dylib
  Referenced from: /usr/local/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so
  Reason: image not found


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.
```

**Comment by yaroslavvb** [comment]
it sounds like your eclipse is not propagating the ld_library_path/dyld_library_path/path env vars correctly, this sounds like a good q to ask on stackoverflow rather than a bug in tensorflow itself

**Comment by tloo** [comment]
thanks @yaroslavvb , I put in stackoverflow, but not body answered me yet:
http://stackoverflow.com/questions/41949689/import-tensorflow-failed-in-eclipse
Just have a try here.
