### ISSUE TITLE
Error while creating quantized graph using bazel tool

### ISSUE THREAD

**Issue by panky8070** [tensorflow/tensorflow#7217]
Hi, 
I am trying to quantize the already stripped and retrained inception graph using the following bazel commands, also I am using docker environment in ubuntu 16.10:

bazel build tensorflow/contrib/quantization/tools:quantize_graph
bazel-bin/tensorflow/contrib/quantization/tools/quantize_graph \    
  --input=/face_tf_train/new_retrained_graph.pb \
  --output_node_names=final_result \
  --output=/face_tf_train/new_stripped_quantized_graph.pb \
  --mode=eightbit  
I am bit new in python and tensorflow, I am not sure what is happening. I want to use the quantized graph for ios mobile app which I am able to compile and run. 
Any help could be very much appriciated. 

I am getting folowing error in the command promt : 
root@f098a9662116:/tensorflow# bazel build tensorflow/contrib/quantization/tools:quantize_graph
INFO: Reading 'startup' options from /root/.bazelrc: --batch
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 1 target...
Target //tensorflow/contrib/quantization/tools:quantize_graph up-to-date:
  bazel-bin/tensorflow/contrib/quantization/tools/quantize_graph
INFO: Elapsed time: 37.731s, Critical Path: 24.75s
root@f098a9662116:/tensorflow# bazel-bin/tensorflow/contrib/quantization/tools/quantize_graph \    
Traceback (most recent call last):
  File "/tensorflow/bazel-bin/tensorflow/contrib/quantization/tools/quantize_graph.runfiles/org_tensorflow/tensorflow/contrib/quantization/tools/quantize_graph.py", line 1003, in <module>
    tf.app.run()
  File "/tensorflow/bazel-bin/tensorflow/contrib/quantization/tools/quantize_graph.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/tensorflow/bazel-bin/tensorflow/contrib/quantization/tools/quantize_graph.runfiles/org_tensorflow/tensorflow/contrib/quantization/tools/quantize_graph.py", line 985, in main
    data = f.read()
  File "/tensorflow/bazel-bin/tensorflow/contrib/quantization/tools/quantize_graph.runfiles/org_tensorflow/tensorflow/python/lib/io/file_io.py", line 101, in read
    compat.as_bytes(self.__name), status)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/tensorflow/bazel-bin/tensorflow/contrib/quantization/tools/quantize_graph.runfiles/org_tensorflow/tensorflow/python/framework/errors.py", line 463, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors.FailedPreconditionError: .

Regards,
Pankaj Wasnik

**Comment by panky8070** [comment]
Hi, 
Can you please look into the issue ?

Regards,
Pankaj

**Comment by rakdl** [comment]
@petewarden please take a look, this error comes up trying to quantize any model at the moment.

**Comment by swarathesh** [comment]
http://stackoverflow.com/questions/38428718/install-tensorflow-with-quantization-support

**Comment by swarathesh** [comment]
im facing the similar issue , is there any fix

**Comment by Androbin** [comment]
May be related to #8698

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.

**Comment by 1int** [comment]
I am facing the very same
