### ISSUE TITLE
tensorflow.python.framework.errors_impl.AbortedError: Exception encountered when calling MaxPooling1D.call()

### ISSUE THREAD

**Issue by Jacob-yen** [tensorflow/tensorflow#72411]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.17 and 2.18.0.dev20240717 

### Custom code

Yes

### OS platform and distribution

Ubuntu 20.04.3 LTS (x86_64)

### Python version

Python version: 3.10.14 

### Current behavior?

I encountered a bug in TensorFlow when using the `tf.keras.layers.MaxPool1D` API after setting the input data format to 'channels_first'. The `tf.keras.layers.MaxPool1D` throws an `tensorflow.python.framework.errors_impl.AbortedError` exception. However, the average pooling operator executes successfully without any exceptions. The code is as follows:

```python
import tensorflow as tf
data_format = "channels_first"
tf.compat.v1.keras.backend.set_image_data_format(data_format=data_format)

pool_size = 2
strides = 2
padding = "valid"
pool_func = tf.keras.layers.MaxPool1D(pool_size=pool_size, strides=strides, padding=padding) # tensorflow.python.framework.errors_impl.AbortedError
# pool_func = tf.keras.layers.AvgPool1D(pool_size=pool_size, strides=strides, padding=padding) # success

input_tensor = tf.random.uniform([1, 5, 1], dtype=tf.float32)
input_tensor = tf.identity(input_tensor)

output_tensor = pool_func(input_tensor)

print(output_tensor.shape)

```

The error message was as follows:

```shell
# Output for tf.keras.layers.MaxPool1D + channel_first: exception
Traceback (most recent call last):
  File "/data/test.py", line 15, in <module>
    output_tensor = pool_func(input_tensor)
  File "/data/anacondas/envs/code/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/data/anacondas/envs/code/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 5983, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.AbortedError: Exception encountered when calling MaxPooling1D.call().

{{function_node __wrapped__MaxPool_device_/job:localhost/replica:0/task:0/device:CPU:0}} Compute received an exception:Status: 2, message: could not create a descriptor for a pooling forward propagation primitive, in file tensorflow/core/kernels/mkl/mkl_maxpooling_op.cc:211 [Op:MaxPool] name: 

Arguments received by MaxPooling1D.call():
  • inputs=tf.Tensor(shape=(1, 5, 1), dtype=float32)

# output for tf.keras.layers.MaxPool1D + channel_last: success

# output for tf.keras.layers.AvgPool1D + channel_first/channel_last: success
```

The above code would throw an exception on `tf-2.17` and `tf-nightly 2.18.0.dev20240717` (nightly-build).

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
data_format = "channels_first"
tf.compat.v1.keras.backend.set_image_data_format(data_format=data_format)

pool_size = 2
strides = 2
padding = "valid"
pool_func = tf.keras.layers.MaxPool1D(pool_size=pool_size, strides=strides, padding=padding) # tensorflow.python.framework.errors_impl.AbortedError
# pool_func = tf.keras.layers.AvgPool1D(pool_size=pool_size, strides=strides, padding=padding) # success

input_tensor = tf.random.uniform([1, 5, 1], dtype=tf.float32)
input_tensor = tf.identity(input_tensor)

output_tensor = pool_func(input_tensor)

print(output_tensor.shape)
```

### Relevant log output

```shell
# Output for tf.keras.layers.MaxPool1D + channel_first: exception
Traceback (most recent call last):
  File "/data/test.py", line 15, in <module>
    output_tensor = pool_func(input_tensor)
  File "/data/anacondas/envs/code/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/data/anacondas/envs/code/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 5983, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.AbortedError: Exception encountered when calling MaxPooling1D.call().

{{function_node __wrapped__MaxPool_device_/job:localhost/replica:0/task:0/device:CPU:0}} Compute received an exception:Status: 2, message: could not create a descriptor for a pooling forward propagation primitive, in file tensorflow/core/kernels/mkl/mkl_maxpooling_op.cc:211 [Op:MaxPool] name: 

Arguments received by MaxPooling1D.call():
  • inputs=tf.Tensor(shape=(1, 5, 1), dtype=float32)

# output for tf.keras.layers.MaxPool1D + channel_last: success

# output for tf.keras.layers.AvgPool1D + channel_first/channel_last: success
```

**Comment by Jacob-yen** [comment]
The same issue occurs with MaxPool2D and MaxPool3D.

**Comment by tilakrayal** [comment]
@Jacob-yen,
I tried to execute the code on tensorflow tf-nightly where it was executed without any issues or errors. Kindly find the gist of it [here](https://colab.sandbox.google.com/gist/tilakrayal/add3aa39a5813b2ba58339ced3b01c62/untitled2022.ipynb). The tf-nightly(2.18.0-dev20240722) contains keras3.0 where we should import keras and keras.layers.MaxPool1D   and try to execute the code. Thank you!

**Comment by Jacob-yen** [comment]
Thank you for your prompt reply. I tried the notebook, and it works well.

However, the above code still crashes on my Linux server with tf-nightly (2.18.0-dev20240722). To investigate the issue, I tested the code on three different servers, installing the same dependency packages with Python 3.10. 
```
Package                      Version
---------------------------- -------------------
absl-py                      2.1.0
astunparse                   1.6.3
certifi                      2024.7.4
charset-normalizer           3.3.2
flatbuffers                  24.3.25
gast                         0.6.0
google-pasta                 0.2.0
grpcio                       1.65.1
h5py                         3.11.0
idna                         3.7
keras-nightly                3.4.1.dev2024072503
libclang                     18.1.1
Markdown                     3.6
markdown-it-py               3.0.0
MarkupSafe                   2.1.5
mdurl                        0.1.2
ml-dtypes                    0.4.0
namex                        0.0.8
numpy                        1.26.4
opt-einsum                   3.3.0
optree                       0.12.1
packaging                    24.1
pip                          24.0
protobuf                     4.25.4
Pygments                     2.18.0
requests                     2.32.3
rich                         13.7.1
setuptools                   69.5.1
six                          1.16.0
tb-nightly                   2.18.0a20240724
tensorboard-data-server      0.7.2
tensorflow-io-gcs-filesystem 0.37.1
termcolor                    2.4.0
tf_nightly                   2.18.0.dev20240722
typing_extensions            4.12.2
urllib3                      2.2.2
Werkzeug                     3.0.3
wheel                        0.43.0
wrapt                        1.16.0

```

I found that two servers with `Python 3.10.14 and GCC 11.2.0` crashed, while the other server with `Python 3.10.4 and GCC 7.5.0` ran the code without any problems.

I'm not sure what caused the crash, but it may be a compatibility issue between the TensorFlow version and the GCC version.

I will temporarily close the issue until further reasons are found.
