### ISSUE TITLE
TfLiteVision can't be initialised

### ISSUE THREAD

**Issue by ThomasRichtsfeld** [tensorflow/tensorflow#72561]
**System information**
- Android Device information: `samsung/o1sxeea/o1s:14/UP1A.231005.007/G991BXXSBGXED:user/release-keys`
- TensorFlow Lite in Play Services SDK version:

```
tflite_vision = { module = "org.tensorflow:tensorflow-lite-task-vision-play-services", version.ref = "0.4.4" }
tflite_gpu = { module = "com.google.android.gms:play-services-tflite-gpu", version = "16.2.0" }
tflite_java = { module = "com.google.android.gms:play-services-tflite-java", version = "16.2.0-beta02" }
tflite_support = { module = "com.google.android.gms:play-services-tflite-support", version = "16.1.0" }
tflite_metadata = { module = "org.tensorflow:tensorflow-lite-metadata", version.ref = "0.4.4" }
```

- Google Play Services version: `24.26.32`

**Code to reproduce the issue**
The app prints a stacktrace in the logs but doesn't crash when calling inside the activities `onCreate` function:

```
    TfLiteVision.initialize(
        context,
        TfLiteInitializationOptions.builder().setEnableGpuDelegateSupport(isGpuDelegateAvailable).build()
    )
```

Log that is printed:
```
Failed to get service from broker.  
java.lang.SecurityException: Unknown calling package name 'com.google.android.gms'.
at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
at android.os.Parcel.createException(Parcel.java:3053)
at android.os.Parcel.readException(Parcel.java:3036)
at android.os.Parcel.readException(Parcel.java:2978)
at m.hv.q(:com.google.android.gms.policy_tflite_dynamite_dynamite@242327803@242327801042.644155124.644155124:206)
at m.gi.run(:com.google.android.gms.policy_tflite_dynamite_dynamite@242327803@242327801042.644155124.644155124:54)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:230)
at android.os.Looper.loop(Looper.java:319)
at android.os.HandlerThread.run(HandlerThread.java:67)
```

It further prints the following warning

```
Unable to update local snapshot for com.google.android.libraries.consentverifier#com.google.android.gms, may result in stale flags. (Ask Gemini)
                                                                                         java.util.concurrent.ExecutionException: m.up: 17: 17: API: Phenotype.API is not available on this device. Connection failed with: dd{statusCode=DEVELOPER_ERROR, resolution=null, message=null}
                                                                                         	at m.aot.s(:com.google.android.gms.policy_tflite_dynamite_dynamite@242327803@242327801042.644155124.644155124:21)
                                                                                         	at m.aot.get(:com.google.android.gms.policy_tflite_dynamite_dynamite@242327803@242327801042.644155124.644155124:3)
                                                                                         	at m.aqc.g(:com.google.android.gms.policy_tflite_dynamite_dynamite@242327803@242327801042.644155124.644155124:11)
                                                                                         	at m.wh.d(:com.google.android.gms.policy_tflite_dynamite_dynamite@242327803@242327801042.644155124.644155124:1)
                                                                                         	at m.vz.run(:com.google.android.gms.policy_tflite_dynamite_dynamite@242327803@242327801042.644155124.644155124:5)
                                                                                         	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
                                                                                         	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                         	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
                                                                                         	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                         	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                         	at java.lang.Thread.run(Thread.java:1012)
                                                                                         Caused by: m.up: 17: 17: API: Phenotype.API is not available on this device. Connection failed with: dd{statusCode=DEVELOPER_ERROR, resolution=null, message=null}
                                                                                         	at m.uq.a(:com.google.android.gms.policy_tflite_dynamite_dynamite@242327803@242327801042.644155124.644155124:13)
                                                                                         	at m.aob.f(:com.google.android.gms.policy_tflite_dynamite_dynamite@242327803@242327801042.644155124.644155124:3)
                                                                                         	at m.aod.run(:com.google.android.gms.policy_tflite_dynamite_dynamite@242327803@242327801042.644155124.644155124:130)
                                                                                         	at m.apn.execute(:com.google.android.gms.policy_tflite_dynamite_dynamite@242327803@242327801042.644155124.644155124:1)
                                                                                         	at m.aot.q(:com.google.android.gms.policy_tflite_dynamite_dynamite@242327803@242327801042.644155124.644155124:1)
                                                                                         	at m.aot.m(:com.google.android.gms.policy_tflite_dynamite_dynamite@242327803@242327801042.644155124.644155124:101)
                                                                                         	at m.aot.d(:com.google.android.gms.policy_tflite_dynamite_dynamite@242327803@242327801042.644155124.644155124:19)
                                                                                         	at m.tb.d(:com.google.android.gms.policy_tflite_dynamite_dynamite@242327803@242327801042.644155124.644155124:1)
                                                                                         	at m.ta.a(:com.google.android.gms.policy_tflite_dynamite_dynamite@242327803@242327801042.644155124.644155124:35)
                                                                                         	at m.nn.run(:com.google.android.gms.policy_tflite_dynamite_dynamite@242327803@242327801042.644155124.644155124:12)
                                                                                         	at m.apn.execute(:com.google.android.gms.policy_tflite_dynamite_dynamite@242327803@242327801042.644155124.644155124:1)
                                                                                         	at m.no.a(:com.google.android.gms.policy_tflite_dynamite_dynamite@242327803@242327801042.644155124.644155124:12)
                                                                                         	at m.ob.b(:com.google.android.gms.policy_tflite_dynamite_dynamite@242327803@242327801042.644155124.644155124:36)
                                                                                         	at m.og.j(:com.google.android.gms.policy_tflite_dynamite_dynamite@242327803@242327801042.644155124.644155124:20)
                                                                                         	at m.ni.run(:com.google.android.gms.policy_tflite_dynamite_dynamite@242327803@242327801042.644155124.644155124:736)
                                                                                         	at m.apn.execute(:com.google.android.gms.policy_tflite_dynamite_dynamite@242327803@242327801042.644155124.644155124:1)
                                                                                         	at m.nj.a(:com.google.android.gms.policy_tflite_dynamite_dynamite@242327803@242327801042.644155124.644155124:8)
                                                                                         	at m.ob.b(:com.google.android.gms.policy_tflite_dynamite_dynamite@242327803@242327801042.644155124.644155124:36)
                                                                                         	at m.oc.c(:com.google.android.gms.policy_tflite_dynamite_dynamite@242327803@242327801042.644155124.644155124:25)
                                                                                         	at m.fh.c(:com.google.android.gms.policy_tflite_dynamite_dynamite@242327803@242327801042.644155124.644155124:7)
                                                                                         	at m.gg.t(:com.google.android.gms.policy_tflite_dynamite_dynamite@242327803@242327801042.644155124.644155124:48)
11:12:04.781 21705-23046 MobStoreFlagStore       com.app.app.stagingserver     W  	at m.gg.f(:com.google.android.gms.policy_tflite_dynamite_dynamite@242327803@242327801042.644155124.644155124:10) (Ask Gemini)
                                                                                         	at m.gg.j(:com.google.android.gms.policy_tflite_dynamite_dynamite@242327803@242327801042.644155124.644155124:178)
                                                                                         	at m.gg.i(:com.google.android.gms.policy_tflite_dynamite_dynamite@242327803@242327801042.644155124.644155124:2)
                                                                                         	at m.gi.run(:com.google.android.gms.policy_tflite_dynamite_dynamite@242327803@242327801042.644155124.644155124:82)
                                                                                         	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                         	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                         	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                         	at android.os.Looper.loop(Looper.java:319)
                                                                                         	at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                         Caused by: m.em: 17: API: Phenotype.API is not available on this device. Connection failed with: dd{statusCode=DEVELOPER_ERROR, resolution=null, message=null}
                                                                                         	at m.hm.a(:com.google.android.gms.policy_tflite_dynamite_dynamite@242327803@242327801042.644155124.644155124:13)
                                                                                         	at m.fh.c(:com.google.android.gms.policy_tflite_dynamite_dynamite@242327803@242327801042.644155124.644155124:3)
                                                                                         	... 10 more
```

**Comment by bxvd** [comment]
I am having the same issue but with the Interpreter API instead of Task Vision.

```
implementation 'com.google.android.gms:play-services-tflite-java:16.0.1'
implementation 'com.google.android.gms:play-services-tflite-gpu:16.1.0'
implementation 'com.google.android.gms:play-services-tflite-support:16.0.1'
```

```kotlin
TfLite.initialize(context, TfLiteInitializationOptions.builder()
  .setEnableGpuDelegateSupport(true)
  .build())
```

**Comment by gaikwadrahul8** [comment]
Hi, @pkgoogle

Please take look into this issue. Thank you

**Comment by pkgoogle** [comment]
Hi @ThomasRichtsfeld, are you doing this in a custom app or are you following an example/documentation? For either case which of these would be closest to your use case? https://github.com/tensorflow/examples/tree/master/lite/examples, https://github.com/google-ai-edge/litert-samples/tree/main/examples. Thanks for any additional information you can provide.

**Comment by ThomasRichtsfeld** [comment]
@pkgoogle I am not sure if any of those fit as I was not able to find the code snippet that caused the trouble for us:
```
    TfLiteVision.initialize(
        context,
        TfLiteInitializationOptions.builder().setEnableGpuDelegateSupport(isGpuDelegateAvailable).build()
    )
```

We use it in the app of our company to do some image inference.
I am not sure if it matters how we use TfLite as the code I shared above is the one that has to be executed before using anything else from the TfLite API

**Comment by pkgoogle** [comment]
So the tflite_support library is not recommended for current development: https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/, since you are having an issue with it -- can you try using [MediaPipe Tasks](https://ai.google.dev/edge/mediapipe/solutions/tasks) instead?
