### ISSUE TITLE
Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by MikeyD-rbg** [tensorflow/tensorflow#72629]
Trying to run a captcha solving python script and got this error;

Traceback (most recent call last):
  File "C:\Users\micha\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 70, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\micha\Documents\PythonProgramming\IG\pytesseract_solver.py", line 9, in <module>
    import tensorflow
  File "C:\Users\micha\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow  # pylint: disable=unused-import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\micha\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 85, in <module>
    raise ImportError(
ImportError: Traceback (most recent call last):
  File "C:\Users\micha\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 70, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors for some common causes and solutions.
If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.

**Comment by tilakrayal** [comment]
@MikeyD-rbg,
Could you please provide the tensorflow and the compatible version which you are trying to install. Also there are at least 3 possible scenarios:

```python
- You need to install the MSVC 2019 redistributable
- Your CPU does not support AVX2 instructions
- Your CPU/Python is on 32 bits
- There is a library that is in a different location/not installed on your system that cannot be loaded.
```

https://github.com/tensorflow/tensorflow/issues/61887

Thank you!
