### ISSUE TITLE
CUDA_ERROR_OUT_OF_MEMORY

### ISSUE THREAD

**Issue by heojiwoong** [tensorflow/tensorflow#7272]
i tried to excute chabot application (DeepQA). but i found out error.
this is the problem screen.....

E tensorflow/core/common_runtime/direct_session.cc:135] Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 18446744073648275456
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    chatbot.main()
  File "/home/deepl/Desktop/chatbot/DeepQA-master/chatbot/chatbot.py", line 179, in main
    log_device_placement=False)  # Too verbose ?
  File "/home/deepl/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1186, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/home/deepl/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 551, in __init__
    self._session = tf_session.TF_NewDeprecatedSession(opts, status)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/deepl/.local/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InternalError: Failed to create session.

i don't know how to solve this problem.. 
if you know to solve this problem, please comment for me. thank you for reading.

**Comment by yaroslavvb** [comment]
It sounds like your network is requiring more memory than is available. This list is for bugs/features in TensorFlow itself, and your issue sounds like something on user end

**Comment by heojiwoong** [comment]
Today i executed this program. then, it worked very well.. I think that this program concerned about network temporarily. (case by case).  Now it work well, but I'm afraid that it doesn't work again..
I'm gonna notice you that promgram's ouput. thank you for your comment! :)

**Comment by girving** [comment]
Closing since it sounds like the problem evaporated.
