### ISSUE TITLE
Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by joshuaemmanuel30** [tensorflow/tensorflow#73220]
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\joshua\Desktop\Intelligent-Face-Recognition-Attendance-System-main\app.py", line 12, in <module>
    from detection.face_matching import detect_faces, align_face
  File "C:\Users\joshua\Desktop\Intelligent-Face-Recognition-Attendance-System-main\detection\__init__.py", line 1, in <module>
    from .face_matching import *
  File "C:\Users\joshua\Desktop\Intelligent-Face-Recognition-Attendance-System-main\detection\face_matching.py", line 4, in <module>
    from deepface import DeepFace
  File "C:\Users\joshua\AppData\Local\Programs\Python\Python310\lib\site-packages\deepface\DeepFace.py", line 15, in <module>
    import tensorflow as tf
  File "C:\Users\joshua\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\__init__.py", line 38, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\joshua\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 85, in <module>
    raise ImportError(
ImportError: Traceback (most recent call last):
  File "C:\Users\joshua\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 70, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors for some common causes and solutions.
If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.
PS C:\Users\joshua\Desktop\Intelligent-Face-Recognition-Attendance-System-main> python app.py 
Traceback (most recent call last):
  File "C:\Users\joshua\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 70, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\joshua\Desktop\Intelligent-Face-Recognition-Attendance-System-main\app.py", line 12, in <module>
    from detection.face_matching import detect_faces, align_face
  File "C:\Users\joshua\Desktop\Intelligent-Face-Recognition-Attendance-System-main\detection\__init__.py", line 1, in <module>
    from .face_matching import *
  File "C:\Users\joshua\Desktop\Intelligent-Face-Recognition-Attendance-System-main\detection\face_matching.py", line 4, in <module>
    from deepface import DeepFace
  File "C:\Users\joshua\AppData\Local\Programs\Python\Python310\lib\site-packages\deepface\DeepFace.py", line 15, in <module>
    import tensorflow as tf
  File "C:\Users\joshua\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\__init__.py", line 38, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\joshua\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 85, in <module>
    raise ImportError(
ImportError: Traceback (most recent call last):
  File "C:\Users\joshua\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 70, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

**Comment by AdvaitDongre** [comment]
so here are a couple of my suggestions, you can try and see if it works: 
1. As of now, TensorFlow does not officially support Python 3.10. You may need to downgrade your Python version to 3.8 or 3.9.
2. try installing tensorflow-cpu it generally solves DLL issues:
```pip install tensorflow-cpu
```
3. check the installation of tensorflow
```import tensorflow as tf
print(tf.__version__)
```

**Comment by tilakrayal** [comment]
@joshuaemmanuel30,
Could you please provide the tensorflow and the compatible version which you are trying to install. Also there are at least 3 possible scenarios:

```python
- You need to install the MSVC 2019 redistributable
- Your CPU does not support AVX2 instructions
- Your CPU/Python is on 32 bits
- There is a library that is in a different location/not installed on your system that cannot be loaded.
```

https://github.com/tensorflow/tensorflow/issues/61887

Thank you!

**Comment by socampo17** [comment]
@tilakrayal  if my processor does not support avx2 instructions, it means that i will can not use tf? thank you

**Comment by tilakrayal** [comment]
@socampo17,
Please take a look at the hardware requirements from the official [document](https://www.tensorflow.org/install/pip#hardware_requirements) and try to follow the same for the smoother installation. Thank you!
