### ISSUE TITLE
 Auto-Configuration Error: Invalid compute capability: "6.0"

### ISSUE THREAD

**Issue by Randl** [tensorflow/tensorflow#7324]
```
Extracting Bazel installation...
.
INFO: Starting clean.
INFO: Output base moved to /home/chaimb/.cache/bazel/_bazel_chaimb/acf2af86672e1552dfd6edd47d54a950_tmp_31124 for deletion
WARNING: Output base '/home/chaimb/.cache/bazel/_bazel_chaimb/acf2af86672e1552dfd6edd47d54a950' is on NFS. This may lead to surprising failures and undetermined behavior.
............
ERROR: package contains errors: tensorflow/stream_executor.
ERROR: error loading package 'tensorflow/stream_executor': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "/home/chaimb/tensorflow/tensorflow/third_party/gpus/cuda_configure.bzl", line 824
                _create_cuda_repository(repository_ctx)
        File "/home/chaimb/tensorflow/tensorflow/third_party/gpus/cuda_configure.bzl", line 736, in _create_cuda_repository
                _get_cuda_config(repository_ctx)
        File "/home/chaimb/tensorflow/tensorflow/third_party/gpus/cuda_configure.bzl", line 590, in _get_cuda_config
                struct(cuda_toolkit_path = cuda_toolkit..., <5 more arguments>)
        File "/home/chaimb/tensorflow/tensorflow/third_party/gpus/cuda_configure.bzl", line 595, in struct
                _compute_capabilities(repository_ctx)
        File "/home/chaimb/tensorflow/tensorflow/third_party/gpus/cuda_configure.bzl", line 337, in _compute_capabilities
                auto_configure_fail("Invalid compute capability: %s"...)
        File "/home/chaimb/tensorflow/tensorflow/third_party/gpus/cuda_configure.bzl", line 93, in auto_configure_fail
                fail("
%sAuto-Configuration Error:%s ...))

Auto-Configuration Error: Invalid compute capability: "6.0"
.
```
Works with default compute capability.
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
https://github.com/tensorflow/tensorflow/issues/4105
### Environment info
Operating System:
Ubuntu 16.04
Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
CUDA 8.0
```
-rw-r--r-- 1 root root    558720 Sep 15 02:02 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root        16 Sep 15 02:05 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root root        19 Sep 15 02:05 /usr/local/cuda/lib64/libcudart.so.8.0 -> libcudart.so.8.0.44
-rw-r--r-- 1 root root    415432 Sep 15 02:02 /usr/local/cuda/lib64/libcudart.so.8.0.44
-rw-r--r-- 1 root root    775162 Sep 15 02:02 /usr/local/cuda/lib64/libcudart_static.a
-rw-r--r-- 1 root root 105920110 Feb  7 10:47 /usr/local/cuda/lib64/libcudnn_static.a
```

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
`eb225d71b394c24f49a2e07f685be94d4ab7496f`
2. The output of `bazel version`
```
Build label: 0.4.4
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Feb 1 18:54:21 2017 (1485975261)
Build timestamp: 1485975261
Build timestamp as int: 1485975261

```
### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
It crashes directly after I pick `configure` options

**Comment by girving** [comment]
@zheng-xq Should 6 be supported?

**Comment by yaroslavvb** [comment]
6.0, 6.1 is Pascal TitanX, P100 cards. I routinely enter those in configure (5 days ago when I tried last it worked)

**Comment by yaroslavvb** [comment]
According to https://github.com/tensorflow/tensorflow/issues/6914, you guys are already building with 6.0

**Comment by girving** [comment]
@jart Any ideas for this cuda/bazel issue?

**Comment by jart** [comment]
Maybe it's too early for me, but how is it possible for this condition to fail for the input "6.0"? Unless that's some kind of unicode dot, I don't understand how this is possible.

```python
    parts = capability.split(".")
    if len(parts) != 2 or not parts[0].isdigit() or not parts[1].isdigit():
      auto_configure_fail("Invalid compute capability: %s" % capability)
```

**Comment by jart** [comment]
Oh I see, somehow that value is getting quoted. Looking into this further…

**Comment by girving** [comment]
@jart Did your search come up with anything?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by jart** [comment]
Closing due to inactivity. If this is still an issue, let me know and I'll reopen.
