### ISSUE TITLE
TensorBuffer does not support data type: INT32

### ISSUE THREAD

**Issue by RaoufiTech** [tensorflow/tensorflow#73295]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.16.1

### Custom code

Yes

### OS platform and distribution

Windows 11 x64

### Mobile device

Andorid Studio virtual device: Medium Phone

### Current behavior?

My app is crashing with the error: TensorBuffer does not support data type: INT32.
I expected it to work normally and not to crash.

### Standalone code to reproduce the issue

```java

package com.example.bert_app;

import android.os.Bundle;
import android.util.Log;
import androidx.appcompat.app.AppCompatActivity;
import org.tensorflow.lite.Interpreter;
import org.tensorflow.lite.support.common.FileUtil;
import org.tensorflow.lite.support.tensorbuffer.TensorBuffer;
import org.tensorflow.lite.DataType;
import com.example.bert_app.tokenizerimpl.BertTokenizer;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

public class MainActivity extends AppCompatActivity {
    private static final String TAG = "MainActivity";
    private static final String MODEL_PATH = "bert_ner_model.tflite";
    private static final int MAX_SEQ_LENGTH = 512;

    private Interpreter tfliteInterpreter;
    private BertTokenizer tokenizer;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        // tokenizer
        tokenizer = new BertTokenizer(this, "vocab.txt", true, true, new ArrayList<>(),
                "[UNK]", "[SEP]", "[PAD]", "[CLS]", "[MASK]", true);

        try {
            tfliteInterpreter = new Interpreter(FileUtil.loadMappedFile(this, MODEL_PATH));
        } catch (Exception e) {
            Log.e(TAG, "Error loading model", e);
        }

        
        String inputText = "I am Wolfgang and I live in Berlin.";
        List<String> tokenizedInput = tokenizer.tokenize(inputText);
        List<Integer> inputIds = tokenizer.convert_tokens_to_ids(tokenizedInput);

        while (inputIds.size() < MAX_SEQ_LENGTH) {
            inputIds.add(tokenizer.convert_tokens_to_ids(Collections.singletonList("[PAD]")).get(0));
        }
        if (inputIds.size() > MAX_SEQ_LENGTH) {
            inputIds = inputIds.subList(0, MAX_SEQ_LENGTH);
        }

        List<Integer> segmentIds = new ArrayList<>(Collections.nCopies(MAX_SEQ_LENGTH, 0));

        List<Integer> attentionMask = new ArrayList<>();
        for (int i = 0; i < MAX_SEQ_LENGTH; i++) {
            attentionMask.add(Objects.equals(inputIds.get(i), tokenizer.convert_tokens_to_ids(Collections.singletonList("[PAD]")).get(0)) ? 0 : 1);
        }

        runInference(inputIds, attentionMask, segmentIds);
    }

    private void runInference(List<Integer> inputIds, List<Integer> attentionMask, List<Integer> segmentIds) {
        int[] inputIdsArray = listToIntArray(inputIds);
        int[] attentionMaskArray = listToIntArray(attentionMask);
        int[] segmentIdsArray = listToIntArray(segmentIds);

        for (int i = 0; i < tfliteInterpreter.getInputTensorCount(); i++) {
            Log.d(TAG, "Input Tensor " + i + ": " + tfliteInterpreter.getInputTensor(i).dataType());
        }
        for (int i = 0; i < tfliteInterpreter.getOutputTensorCount(); i++) {
            Log.d(TAG, "Output Tensor " + i + ": " + tfliteInterpreter.getOutputTensor(i).dataType());
        }

        TensorBuffer inputIdsBuffer = TensorBuffer.createFixedSize(new int[]{1, MAX_SEQ_LENGTH}, DataType.INT32);
        inputIdsBuffer.loadArray(inputIdsArray);

        TensorBuffer attentionMaskBuffer = TensorBuffer.createFixedSize(new int[]{1, MAX_SEQ_LENGTH}, DataType.INT32);
        attentionMaskBuffer.loadArray(attentionMaskArray);

        TensorBuffer segmentIdsBuffer = TensorBuffer.createFixedSize(new int[]{1, MAX_SEQ_LENGTH}, DataType.INT32);
        segmentIdsBuffer.loadArray(segmentIdsArray);

        TensorBuffer outputBuffer = TensorBuffer.createFixedSize(new int[]{1, MAX_SEQ_LENGTH, 2}, DataType.FLOAT32);  // Assuming output is of shape [1, MAX_SEQ_LENGTH, 2]

        Object[] inputs = {inputIdsBuffer.getBuffer(), attentionMaskBuffer.getBuffer(), segmentIdsBuffer.getBuffer()};
        Map<Integer, Object> outputs = new HashMap<>();
        outputs.put(0, outputBuffer.getBuffer());
        

        tfliteInterpreter.runForMultipleInputsOutputs(inputs, outputs);

        //  output
        float[] outputArray = outputBuffer.getFloatArray();
        processOutput(outputArray);
    }

    private int[] listToIntArray(List<Integer> list) {
        int[] array = new int[list.size()];
        for (int i = 0; i < list.size(); i++) {
            array[i] = list.get(i);
        }
        return array;
    }

    private void processOutput(float[] outputArray) {
        for (float value : outputArray) {
            Log.d(TAG, "Output: " + value);
        }
    }
}
```

### Relevant log output

```shell
024-08-07 16:03:11.485  8162-8162  MainActivity            com.example.bert_app                 D  Input Tensor 0: INT32
2024-08-07 16:03:11.485  8162-8162  MainActivity            com.example.bert_app                 D  Input Tensor 1: INT32
2024-08-07 16:03:11.485  8162-8162  MainActivity            com.example.bert_app                 D  Input Tensor 2: INT32
2024-08-07 16:03:11.485  8162-8162  MainActivity            com.example.bert_app                 D  Output Tensor 0: FLOAT32
2024-08-07 16:03:11.489  8162-8162  AndroidRuntime          com.example.bert_app                 D  Shutting down VM
2024-08-07 16:03:11.491  8162-8162  AndroidRuntime          com.example.bert_app                 E  FATAL EXCEPTION: main (Ask Gemini)
                                                                                                    Process: com.example.bert_app, PID: 8162
                                                                                                    java.lang.AssertionError: TensorBuffer does not support data type: INT32
                                                                                                    	at org.tensorflow.lite.support.tensorbuffer.TensorBuffer.createFixedSize(TensorBuffer.java:82)
                                                                                                    	at com.example.bert_app.MainActivity.runInference(MainActivity.java:85)
                                                                                                    	at com.example.bert_app.MainActivity.onCreate(MainActivity.java:68)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8980)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8958)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1526)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4029)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4234)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:112)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:174)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:109)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2635)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8699)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
2024-08-07 16:03:11.502  8162-8162  Process                 com.example.bert_app                 I  Sending signal. PID: 8162 SIG: 9
```

**Comment by sawantkumar** [comment]
Hi @AiTester950 ,

By looking at the below error , it looks like DataType.INT32 is not supported by TensorBuffer , can you use DataType.FLOAT32  instead and let me know if it worked for you.

**Comment by AiTester950** [comment]
Hey
FLOAT32 works but the ai model that I am working with needs INT32...

**Comment by sawantkumar** [comment]
Hi @AiTester950 ,

You will need to use Bytebuffer to accomplish your task . However the output can still handled as a FLOAT32 TensorBuffer .
Please take a look at [this](https://developer.android.com/reference/java/nio/ByteBuffer)
