### ISSUE TITLE
Building from Source without internet connection

### ISSUE THREAD

**Issue by NEGU93** [tensorflow/tensorflow#73572]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

Branch r2.17

### Custom code

Yes

### OS platform and distribution

Debian 11 Linux 5.10.0-28-amd64 x86_64

### Python version

Python 3.9.2

### Bazel version

bazel 6.5.0

### GCC/compiler version

gcc (Debian 10.2.1-6) 10.2.1 20210110

### Current behavior?

Context:

I have my computer blocked from internet. 
Furthemore, as I run it in a VM, my VM does not have AVX available and I do not have access to the host machine to change this.
Because all TF 2.x.x compiled versions use AVX, I decided to compile tf myself. I cloned the repo and switch to branch `r.2.17`.
At first, many files failed to be found, I downloaded each file in the error message and copied to a `../shared_folder/dist` folder. I then use:

`bazel build //tensorflow/tools/pip_package:wheel --repo_env=WHEEL_NAME=tensorflow_cpu --distdir ../shared_folder/dist` 

Although I downloaded like 30 packages already, it seems to be advancing, however, now I get an error message that I do not know how to get passed. The not found file does not really have a file name but it is: `[https://golang.org/dl/?mode=json&include=all, https://golang.google.cn/dl/?mode=json&include=all]`. Normally it was a `[github.com/<stuff>/<filename>.tar.gz]` and just downloading `<filename>.tar.gz` into `../shared_folder/dist`  worked.

I put `which bazel` and saw it is installed in `/usr/bin/bazel` but there is no folder, I installed it using the `sudo apt install ./bazel_6.5.0-linux-x86_64.deb` and I don't see any file to change any link.

This [link](https://stackoverflow.com/questions/39032329/is-there-any-way-to-build-tensorflow-from-source-without-having-internet) is what I want, but it's quite outdated and the solution is no longer viable (or at least it needs some modifications I could not find).

### Standalone code to reproduce the issue

```shell
Not possible I believe. If there is a way, please let me know.
```

### Relevant log output

```shell
INFO: Reading 'startup' options from /home/abarrachina/tensorflow/.bazelrc: --windows_enable_symlinks
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=190
INFO: Reading rc options for 'build' from /home/abarrachina/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/abarrachina/tensorflow/.bazelrc:
  'build' options: --define framework_shared_object=true --define tsl_protobuf_header_only=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --features=-force_no_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library --experimental_link_static_libraries_once=false --incompatible_enforce_config_setting_visibility
INFO: Reading rc options for 'build' from /home/abarrachina/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env PYTHON_LIB_PATH=/usr/lib/python3/dist-packages --python_path=/usr/bin/python3
INFO: Found applicable config definition build:short_logs in file /home/abarrachina/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/abarrachina/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:linux in file /home/abarrachina/tensorflow/.bazelrc: --host_copt=-w --copt=-Wno-all --copt=-Wno-extra --copt=-Wno-deprecated --copt=-Wno-deprecated-declarations --copt=-Wno-ignored-attributes --copt=-Wno-array-bounds --copt=-Wunused-result --copt=-Werror=unused-result --copt=-Wswitch --copt=-Werror=switch --copt=-Wno-error=unused-but-set-variable --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++17 --host_cxxopt=-std=c++17 --config=dynamic_kernels --experimental_guard_against_concurrent_changes
INFO: Found applicable config definition build:dynamic_kernels in file /home/abarrachina/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
INFO: Repository go_sdk instantiated at:
  /home/abarrachina/tensorflow/WORKSPACE:103:14: in <toplevel>
  /home/abarrachina/tensorflow/tensorflow/workspace0.bzl:135:20: in workspace
  /home/abarrachina/.cache/bazel/_bazel_abarrachina/7bf8e2307b94e4bac50e88e2b60f4f57/external/com_github_grpc_grpc/bazel/grpc_extra_deps.bzl:36:27: in grpc_extra_depscd BUI
  /home/abarrachina/.cache/bazel/_bazel_abarrachina/7bf8e2307b94e4bac50e88e2b60f4f57/external/io_bazel_rules_go/go/private/sdk.bzl:431:28: in go_register_toolchains
  /home/abarrachina/.cache/bazel/_bazel_abarrachina/7bf8e2307b94e4bac50e88e2b60f4f57/external/io_bazel_rules_go/go/private/sdk.bzl:130:21: in go_download_sdk
Repository rule _go_download_sdk defined at:
  /home/abarrachina/.cache/bazel/_bazel_abarrachina/7bf8e2307b94e4bac50e88e2b60f4f57/external/io_bazel_rules_go/go/private/sdk.bzl:117:35: in <toplevel>
WARNING: Download from https://golang.org/dl/?mode=json&include=all failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Unknown host: golang.org
WARNING: Download from https://golang.google.cn/dl/?mode=json&include=all failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Unknown host: golang.google.cn
ERROR: An error occurred during the fetch of repository 'go_sdk':
   Traceback (most recent call last):
	File "/home/abarrachina/.cache/bazel/_bazel_abarrachina/7bf8e2307b94e4bac50e88e2b60f4f57/external/io_bazel_rules_go/go/private/sdk.bzl", line 71, column 21, in _go_download_sdk_impl
		ctx.download(
Error in download: java.io.IOException: Error downloading [https://golang.org/dl/?mode=json&include=all, https://golang.google.cn/dl/?mode=json&include=all] to /home/abarrachina/.cache/bazel/_bazel_abarrachina/7bf8e2307b94e4bac50e88e2b60f4f57/external/go_sdk/versions.json: Unknown host: golang.google.cn
ERROR: /home/abarrachina/tensorflow/WORKSPACE:103:14: fetching _go_download_sdk rule //external:go_sdk: Traceback (most recent call last):
	File "/home/abarrachina/.cache/bazel/_bazel_abarrachina/7bf8e2307b94e4bac50e88e2b60f4f57/external/io_bazel_rules_go/go/private/sdk.bzl", line 71, column 21, in _go_download_sdk_impl
		ctx.download(
Error in download: java.io.IOException: Error downloading [https://golang.org/dl/?mode=json&include=all, https://golang.google.cn/dl/?mode=json&include=all] to /home/abarrachina/.cache/bazel/_bazel_abarrachina/7bf8e2307b94e4bac50e88e2b60f4f57/external/go_sdk/versions.json: Unknown host: golang.google.cn
ERROR: Analysis of target '//tensorflow/tools/pip_package:wheel' failed; build aborted: java.io.IOException: Error downloading [https://golang.org/dl/?mode=json&include=all, https://golang.google.cn/dl/?mode=json&include=all] to /home/abarrachina/.cache/bazel/_bazel_abarrachina/7bf8e2307b94e4bac50e88e2b60f4f57/external/go_sdk/versions.json: Unknown host: golang.google.cn
INFO: Elapsed time: 0.637s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (5 packages loaded, 41 targets configured)
    currently loading: @rules_python//python/runfiles ... (7 packages)
    Fetching repository @pypi_typing_extensions; starting
```

**Comment by joydeep049** [comment]
If this issue is free to work on, can I try?
@NEGU93

**Comment by NEGU93** [comment]
I'm sorry, not sure what you mean. If I can give you the VM file directly? If so, I'm afraid not. It's my company work so I cannot share it. This is also the reason I have this complex environment and restrictions.

**Comment by joydeep049** [comment]
I didn't mean that. I meant can i work on solving this issue?
How do I work on issues here? Do they get assigned to somenone on asking? Or some other way?

**Comment by tilakrayal** [comment]
@NEGU93,
Generally, it is not suggestible to do this process because Bazel automatically caches the external dependencies it downloads. As the alternative you can try to build the docker or the another VM environment and try to use that.

https://discuss.ai.google.dev/t/tensorflow-installation-without-internet/31021
https://discuss.ai.google.dev/t/installing-tf-on-offline-ubuntu/29473/3
https://github.com/tensorflow/tensorflow/issues/3194

Thank you!
