### ISSUE TITLE
there is a error when i import tensorflow in python script

### ISSUE THREAD

**Issue by mathfinder** [tensorflow/tensorflow#7373]
after i finish 'Configure the installation' step without finishing 'create the pip package and install'step.
there is a error when i import tensorflow in python script.
i type 'import tensorflow' in my python script and run it.i get this error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 60, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory

Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.
`
i install the latest version tensorflow from sourse on ubuntu15.04 with cuda7.5 and cudnn5. in 'Configure the installation' step,i set cuda version 7.5.

**Comment by girving** [comment]
Are you building it from sources, but still trying to import an installed version?  How did TensorFlow get into `/usr/local/lib/python2.7/dist-packages`?

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
