### ISSUE TITLE
tf.sparse.reduce_sum error in JIT

### ISSUE THREAD

**Issue by edbosne** [tensorflow/tensorflow#74131]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

v2.17.0-rc1-2-gad6d8cc177d

### Custom code

Yes

### OS platform and distribution

Ubuntu Mate 22.04

### Python version

Python 3.10.12

### CUDA/cuDNN version

CUDA 12.3

### Current behavior?

Error when using tf.sparse.reduce_sum and JIT compilation.

I have written a layer that passes all my unit tests except when I use in a model with predict or train. 
Would that make sense with the JIT compilation on? I am not fully certain how and when this works.

Anyway, I am not exactly sure why my layer code fails, but I think that this minimum reproducible example captures the issue.

### Standalone code to reproduce the issue

```shell
import numpy as np
import tensorflow as tf

batch_size = 4
input_shape = (3, 3)

indices = np.array([[0, 0, 0], [0, 0, 1], [1, 0, 0], [1, 0, 1], [2, 0, 0], [2, 0, 1], [3, 0, 0], [3, 0, 1]])
inputs = tf.sparse.SparseTensor(dense_shape=(batch_size, *input_shape),
                                indices=indices,
                                values=[9, 1, 9, 1, 9, 1, 9, 1])


@tf.function(input_signature=[tf.SparseTensorSpec(
    shape=(4, 3, 3),
    dtype=tf.dtypes.int32)], jit_compile=True)
def get_batch_sum(inputs):
    # same problem with tf.sparse.reduce_max
    return tf.sparse.reduce_sum(tf.sparse.reduce_sum(inputs, axis=1, output_is_sparse=True), axis=1)


sum_out = get_batch_sum(inputs)
print(sum_out)
```

### Relevant log output

```shell
2024-08-20 16:31:01.690779: W tensorflow/core/framework/op_kernel.cc:1840] OP_REQUIRES failed at xla_ops.cc:577 : INVALID_ARGUMENT: Detected unsupported operations when trying to compile graph __inference_get_batch_sum_15[_XlaMustCompile=true,config_proto=6001324581131673121,executor_type=11160318154034397263] on XLA_GPU_JIT: SparseReduceSumSparse (No registered 'SparseReduceSumSparse' OpKernel for XLA_GPU_JIT devices compatible with node {{node SparseReduceSumSparse}}){{node SparseReduceSumSparse}}
The op is created at: 
File ".config/JetBrains/PyCharmCE2023.3/scratches/scratch_30.py", line 21, in <module>
File ".config/JetBrains/PyCharmCE2023.3/scratches/scratch_30.py", line 18, in get_batch_sum
	tf2xla conversion failed while converting __inference_get_batch_sum_15[_XlaMustCompile=true,config_proto=6001324581131673121,executor_type=11160318154034397263]. Run with TF_DUMP_GRAPH_PREFIX=/path/to/dump/dir and --vmodule=xla_compiler=2 to obtain a dump of the compiled functions.
Traceback (most recent call last):
(...)  

File ".config/JetBrains/PyCharmCE2023.3/scratches/scratch_30.py", line 18, in get_batch_sum
	tf2xla conversion failed while converting __inference_get_batch_sum_15[_XlaMustCompile=true,config_proto=6001324581131673121,executor_type=11160318154034397263]. Run with TF_DUMP_GRAPH_PREFIX=/path/to/dump/dir and --vmodule=xla_compiler=2 to obtain a dump of the compiled functions. [Op:__inference_get_batch_sum_15]
```

**Comment by Venkat6871** [comment]
I tried to run your code on Colab using TF v2.15.0, nightly and faced the same issue. Please find the [gist](https://colab.research.google.com/gist/Venkat6871/ccb48727fe4acd9ae9425bb6d1fb573c/74131_2-15-0-nightly-v.ipynb) here for reference.
Thank you!

**Comment by felbecker** [comment]
This also happens for other sparse ops: `tf.sparse.reorder` and `tf.sparse.softmax`.
Reproducable with code very closely related to above.

**Comment by Venkat6871** [comment]
Hi @edbosne ,
Thank you so much for filing this issue. We truly appreciate your support. At the moment, this request is not prioritized and mark it for community contributions. If you would like to contribute on a fix, please feel free to fork the repository and submit a pull request in accordance with the TensorFlow [CONTRIBUTION GUIDELINES](https://www.tensorflow.org/community/contribute/code) and link this issue in your PR to ensure the maintainers can easily review and collaborate.
To avoid duplicate work, please leave a comment here if you decide to take it on!

Thank you again for your interest and we look forward to seeing your contributions!
