### ISSUE TITLE
Issues when converting tensorflow built-in keras-based models to tensorflow lite

### ISSUE THREAD

**Issue by yonghyunee** [tensorflow/tensorflow#74280]
Hello Tensorflow Support
I am contacting you because I am getting the following error while converting a model created with Keras embedded in Tensorflow to Tensorflow Lite.

The model I created used the basic structure of Bidirectional LSTM with dropout, regularization, and dense layers.

I've attached the code to convert my model to Tensorflow Lite and the message when the error occurred.

I hope this will solve your problem.

Best regards,
Yonghyun Lee

[Code to convert my model to Tensorflow Lite].

import tensorflow as tf

model = tf.keras.models.load_model(“./input_h5/input.h5”, compile=False, safe_mode=False)

tf.saved_model.save(model, './input_h5/saved_model_dir')
converter = tf.lite.TFLiteConverter.from_saved_model(“./input_h5/saved_model_dir”)
tflmodel = converter.convert()
with open(“./output_tflite/output.tflite”, “wb”) as file:
    file.write(tflmodel)

[Error Message]
2024-08-22 11:09:03.490341: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1724292544.933616 42872 tf_tfl_flatbuffer_helpers.cc:392] Ignored output_format.
W0000 00:00:1724292544.934307 42872 tf_tfl_flatbuffer_helpers.cc:395] Ignored drop_control_dependency.
2024-08-22 11:09:04.937226: I tensorflow/cc/saved_model/reader.cc:83] Reading SavedModel from: ./input_h5/saved_model_dir
2024-08-22 11:09:04.941589: I tensorflow/cc/saved_model/reader.cc:52] Reading meta graph with tags { serve }
2024-08-22 11:09:04.941738: I tensorflow/cc/saved_model/reader.cc:147] Reading SavedModel debug info (if present) from: ./input_h5/saved_model_dir
2024-08-22 11:09:04.961054: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:388] MLIR V1 optimization pass is not enabled
2024-08-22 11:09:04.964133: I tensorflow/cc/saved_model/loader.cc:236] Restoring SavedModel bundle.
2024-08-22 11:09:05.075893: I tensorflow/cc/saved_model/loader.cc:220] Running initialization op on SavedModel bundle at path: ./input_h5/saved_model_dir
2024-08-22 11:09:05.112269: I tensorflow/cc/saved_model/loader.cc:462] SavedModel load for tags { serve }; Status: success: OK. Took 174732 microseconds.
2024-08-22 11:09:05.185339: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
loc(fused[“ReadVariableOp:”, “sequential_11_1/bidirectional_22_1/backward_lstm_22_1/while/lstm_cell_1/add_1/ReadVariableOp@sequential_11_1_bidirectional_22_1_backward_lstm_22_1_while_body_613”]): error: missing attribute 'value'
LLVM ERROR: Failed to infer result type(s).

**Comment by tilakrayal** [comment]
@yonghyunee ,
Could you please provide the tensorflow version you are using. This issue was resolved in latest tensorflow v2.17 and tf-nightly. Please try with those versions and let me know if you are facing the same issue. Thank you!

**Comment by yonghyunee** [comment]
Hello
I succeeded in converting it to keras h5 -> tensorflow lite using the method you told me above. In the process of applying the model, the following error appears, so can you tell me the solution to this error?

[Error]
Exception in thread Thread-2 (receive_message):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/root/gait_phase_estimation/main.py", line 27, in receive_message
    interpreter.allocate_tensors()
  File "/usr/lib/python3.10/site-packages/tflite_runtime/interpreter.py", line 531, in allocate_tensors
    return self._interpreter.AllocateTensors()
RuntimeError: Select TensorFlow op(s), included in the given model, is(are) not supported by this interpreter. Make sure you apply/link the Flex delegate before inference. For the Android, it can be resolved by adding "org.tensorflow:tensorflow-lite-select-tf-ops" dependency. See instructions: https://www.tensorflow.org/lite/guide/ops_selectNode number 15 (FlexTensorListReserve) failed to prepare.Select TensorFlow op(s), included in the given model, is(are) not supported by this interpreter. Make sure you apply/link the Flex delegate before inference. For the Android, it can be resolved by adding "org.tensorflow:tensorflow-lite-select-tf-ops" dependency. See instructions: https://www.tensorflow.org/lite/guide/ops_selectNode number 15 (FlexTensorListReserve) failed to prepare.

[Model Convert Code]
import tensorflow as tf


model = tf.keras.models.load_model("./input_h5/input.h5", compile=False, safe_mode=False)

tf.saved_model.save(model, './input_h5/saved_model_dir')

converter = tf.lite.TFLiteConverter.from_saved_model("./input_h5/saved_model_dir")
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
converter._experimental_lower_tensor_list_ops = False
converter.experimental_enable_resource_variables = True
tflmodel = converter.convert()
with open("./output_tflite/output.tflite", "wb") as file:
    file.write(tflmodel)
    
[Versions]
Where the tensorflow-lite model runs :
python 3.10.14
tflite-runtime 2.14.0

Where the tensorflow-lite model converter runs :
python 3.11.9
tf_keras                     2.16.0
tf-nightly                   2.18.0.dev20240822
tf_nightly_intel             2.18.0.dev20240822
tensorflow                   2.17.0
tensorflow-intel             2.17.0

Thank you

Best regards,
Yonghyun Lee

**Comment by gaikwadrahul8** [comment]
Hi, @yonghyunee 

I apologize for the delayed in my response, if possible could you please help me with your Google colab notebook where you created your model with bidirectional LSTM with dropout, regularization, and dense layers which will help us to investigate this issue further from our end ? 

Thank you for your cooperation and patience.
