### ISSUE TITLE
Failed to build from source for r0.12 about :_rules_closure: no such attribute 'urls"

### ISSUE THREAD

**Issue by moveforever** [tensorflow/tensorflow#7433]
Hi, I'm trying to install tensorflow r0.12 on a cluster with CentOS. i came across with following errors:
```
ERROR: /data0/title/tensorflow/WORKSPACE:3:1: //external:io_bazel_rules_closure: no such attribute 'urls' in 'http_archive' rule.
ERROR: /data0/title/tensorflow/WORKSPACE:3:1: //external:io_bazel_rules_closure: missing value for mandatory attribute 'url' in 'http_archive' rule.
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package '@io_bazel_rules_closure//closure': error loading package 'external': Could not load //external package.

```

bazel 0.4.0
cuda 7.5
cudnn 5.1
small help will welcome, tks.

**Comment by gunan** [comment]
Please upgrade to bazel version 0.4.1 or higher.
We had to make backwards incompatible changes to our build files, so any bazel version before 0.4.1 will not work.

**Comment by moveforever** [comment]
another question: i upgrade bazel to 0.4.2, and then recompile, i came across with another following error:
```
java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@org_polymer_webcomponentsjs' (requested by nodes 'REPOSITORY:@org_polymer_webcomponentsjs')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:429)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:501)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Invalid EvalException:
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.Semaphore.acquire(Semaphore.java:312)
	at com.google.devtools.build.lib.bazel.repository.downloader.HttpDownloader.download(HttpDownloader.java:196)
	at com.google.devtools.build.lib.bazel.repository.skylark.SkylarkRepositoryContext.downloadAndExtract(SkylarkRepositoryContext.java:594)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callMethod(FuncallExpression.java:316)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeObjectMethod(FuncallExpression.java:732)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeObjectMethod(FuncallExpression.java:784)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:770)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:48)
	at com.google.devtools.build.lib.syntax.ExpressionStatement.doExec(ExpressionStatement.java:46)
	at com.google.devtools.build.lib.syntax.Statement.exec(Statement.java:37)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:136)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:439)
	at com.google.devtools.build.lib.bazel.repository.skylark.SkylarkRepositoryFunction.fetch(SkylarkRepositoryFunction.java:106)
	at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:155)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:370)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:501)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

	at com.google.devtools.build.lib.syntax.EvalException.<init>(EvalException.java:112)
	at com.google.devtools.build.lib.syntax.EvalException$EvalExceptionWithJavaCause.<init>(EvalException.java:209)
	at com.google.devtools.build.lib.syntax.EvalException$EvalExceptionWithJavaCause.<init>(EvalException.java:217)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callMethod(FuncallExpression.java:344)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeObjectMethod(FuncallExpression.java:732)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeObjectMethod(FuncallExpression.java:784)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:770)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:48)
	at com.google.devtools.build.lib.syntax.ExpressionStatement.doExec(ExpressionStatement.java:46)
	at com.google.devtools.build.lib.syntax.Statement.exec(Statement.java:37)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:136)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:439)
	at com.google.devtools.build.lib.bazel.repository.skylark.SkylarkRepositoryFunction.fetch(SkylarkRepositoryFunction.java:106)
	at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:155)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:370)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@org_polymer_webcomponentsjs' (requested by nodes 'REPOSITORY:@org_polymer_webcomponentsjs')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:429)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:501)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Invalid EvalException:
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.Semaphore.acquire(Semaphore.java:312)
	at com.google.devtools.build.lib.bazel.repository.downloader.HttpDownloader.download(HttpDownloader.java:196)
	at com.google.devtools.build.lib.bazel.repository.skylark.SkylarkRepositoryContext.downloadAndExtract(SkylarkRepositoryContext.java:594)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callMethod(FuncallExpression.java:316)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeObjectMethod(FuncallExpression.java:732)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeObjectMethod(FuncallExpression.java:784)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:770)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:48)
	at com.google.devtools.build.lib.syntax.ExpressionStatement.doExec(ExpressionStatement.java:46)
	at com.google.devtools.build.lib.syntax.Statement.exec(Statement.java:37)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:136)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:439)
	at com.google.devtools.build.lib.bazel.repository.skylark.SkylarkRepositoryFunction.fetch(SkylarkRepositoryFunction.java:106)
	at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:155)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:370)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:501)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

	at com.google.devtools.build.lib.syntax.EvalException.<init>(EvalException.java:112)
	at com.google.devtools.build.lib.syntax.EvalException$EvalExceptionWithJavaCause.<init>(EvalException.java:209)
	at com.google.devtools.build.lib.syntax.EvalException$EvalExceptionWithJavaCause.<init>(EvalException.java:217)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callMethod(FuncallExpression.java:344)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeObjectMethod(FuncallExpression.java:732)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeObjectMethod(FuncallExpression.java:784)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:770)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:48)
	at com.google.devtools.build.lib.syntax.ExpressionStatement.doExec(ExpressionStatement.java:46)
	at com.google.devtools.build.lib.syntax.Statement.exec(Statement.java:37)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:136)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:439)
	at com.google.devtools.build.lib.bazel.repository.skylark.SkylarkRepositoryFunction.fetch(SkylarkRepositoryFunction.java:106)
	at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:155)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:370)
	... 4 more
```

**Comment by moveforever** [comment]
i compile again, it appeared a new error:
```
ERROR: /data0/title/download/tensorflow/tensorflow/workspace.bzl:423:3: no such package '@junit_jar//jar': Error downloading [https://github.com/junit-team/junit4/releases/download/r4.12/junit-4.12.jar] to /root/.cache/bazel/_bazel_root/d5c4498fef8d232536c486a547731ad0/external/junit_jar/junit-4.12.jar: Tried to reconnect at offset 189,857 but server didn't support it and referenced by '//external:junit'.
ERROR: /data0/title/download/tensorflow/tensorflow/workspace.bzl:423:3: no such package '@junit_jar//jar': Error downloading [https://github.com/junit-team/junit4/releases/download/r4.12/junit-4.12.jar] to /root/.cache/bazel/_bazel_root/d5c4498fef8d232536c486a547731ad0/external/junit_jar/junit-4.12.jar: Tried to reconnect at offset 189,857 but server didn't support it and referenced by '//external:junit'.
ERROR: Evaluation of query "deps((((//tensorflow/... - //tensorflow/contrib/nccl/...) - //tensorflow/examples/android/...) union @bazel_tools//tools/jdk:toolchain))" failed: errors were encountered while computing transitive closure.
```

**Comment by gunan** [comment]
This one looks like a transient download error. Please try again.

**Comment by moveforever** [comment]
i have a try

**Comment by moveforever** [comment]
i have a try. it seems to configure successfully. And then i run `bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package`. it appear error followed:
```
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 1 target...
ERROR: /root/.cache/bazel/_bazel_root/d5c4498fef8d232536c486a547731ad0/external/pcre/BUILD.bazel:5:1: undeclared inclusion(s) in rule '@pcre//:pcre':
this rule is missing dependency declarations for the following files included by 'external/pcre/pcre_byte_order.c':
  '/lib/gcc/x86_64-redhat-linux/4.8.3/include/limits.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.3/include/syslimits.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.3/include/stddef.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.3/include/stdarg.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.3/include/stdint.h'.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3.348s, Critical Path: 0.60s
```

**Comment by amel2houwi** [comment]
ERROR: Evaluation of query "deps(((//tensorflow/... - //tensorflow/contrib/nccl/...) - //tensorflow/examples/android/...))" failed: errors were encountered while computing transitive closure.

**Comment by gunan** [comment]
@moveforever The key in your error message is this part:
```
  '/lib/gcc/x86_64-redhat-linux/4.8.3/include/limits.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.3/include/syslimits.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.3/include/stddef.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.3/include/stdarg.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.3/include/stdint.h'.
```
You may need to reinstall gcc and g++.

@amel2houwi please file a new issue by filling out the full form. If you are on windows, this is a known issue. If you check out r1.0 branch, you should be able to build fine.

**Comment by limingfan** [comment]
i just met the same problem, i was stuck when upgrade the bazel 0.4.2, then  the same java error occured
how did you solve it ,i compile again, but make no use

**Comment by gunan** [comment]
@limingfan Which version of the repo are you trying to build?
I recommend building 1.0, or if you really need an older version 0.12.

Bazel and TF are both very quickly evolving, and both had to have a lot of backwards/forwards incompatible changes. So older versions may be more difficult to build.

**Comment by ritikajain7** [comment]
Hi I tried installing SyntaxNet today and I am stuck with the below error: Can somebody please guide me whats wrong here. 
ERROR: Error downloading [http://bazel-mirror.storage.googleapis.com/repo1.maven.org/maven2/com/google/guava/guava/20.0/guava-20.0.jar, http://repo1.maven.org/maven2/com/google/guava/guava/20.0/guava-20.0.jar, http://maven.ibiblio.org/maven2/com/google/guava/guava/20.0/guava-20.0.jar] to /home/gemini/.cache/bazel/_bazel_gemini/0d0ea192abd8cc4ee452d1e7288e5f03/external/com_google_guava/guava-20.0.jar: All mirrors are down: [Checksum was 4b52abfc70f48238e972dd7e49ef73adf7e36ff34eaaa97c2482a1f8ca8d3123 but wanted 36a666e3b71ae7f0f0dca23654b67e086e6c93d192f60ba5dfd5519db6c288c8, Checksum was f64edf0b2bb22bb37860a54e8d79fdb500ac88bb51c598bf66b953fc8b59997b but wanted 36a666e3b71ae7f0f0dca23654b67e086e6c93d192f60ba5dfd5519db6c288c8, Checksum was feee555b39925f3c22dbe1838cea193aef2bea7c2745066ef8c05be98fc72928 but wanted 36a666e3b71ae7f0f0dca23654b67e086e6c93d192f60ba5dfd5519db6c288c8] and referenced by '@io_bazel_rules_closure//java/io/bazel/rules/closure:ClosureWorker'.

ERROR:  java.io.IOException: Error downloading [http://bazel-mirror.storage.googleapis.com/repo1.maven.org/maven2/com/google/guava/guava/20.0/guava-20.0.jar, http://repo1.maven.org/maven2/com/google/guava/guava/20.0/guava-20.0.jar, http://maven.ibiblio.org/maven2/com/google/guava/guava/20.0/guava-20.0.jar] to /home/gemini/.cache/bazel/_bazel_gemini/0d0ea192abd8cc4ee452d1e7288e5f03/external/com_google_guava/guava-20.0.jar: All mirrors are down: [Checksum was 4b52abfc70f48238e972dd7e49ef73adf7e36ff34eaaa97c2482a1f8ca8d3123 but wanted 36a666e3b71ae7f0f0dca23654b67e086e6c93d192f60ba5dfd5519db6c288c8, Checksum was f64edf0b2bb22bb37860a54e8d79fdb500ac88bb51c598bf66b953fc8b59997b but wanted 36a666e3b71ae7f0f0dca23654b67e086e6c93d192f60ba5dfd5519db6c288c8, Checksum was feee555b39925f3c22dbe1838cea193aef2bea7c2745066ef8c05be98fc72928 but wanted 36a666e3b71ae7f0f0dca23654b67e086e6c93d192f60ba5dfd5519db6c288c8] and referenced by '@com_google_template_soy//:com_google_template_soy'.

ERROR: Evaluation of query "deps(((//tensorflow/... - //tensorflow/contrib/nccl/...) - //tensorflow/examples/android/...))" failed: errors were encountered while computing transitive closure.
