### ISSUE TITLE
ValueError: Variable d_bn1/d_bn1_2/d_bn1_2/moments/moments_1/mean/ExponentialMovingAverage/biased does not exist

### ISSUE THREAD

**Issue by ansu1234** [tensorflow/tensorflow#7462]
I am trying to run the model from here, http://bamos.github.io/2016/08/09/deep-completion/ , but i am facing this issue. Kindly suggest some approach.
Traceback (most recent call last):
  File "train-dcgan.py", line 39, in <module>
    is_crop=False, checkpoint_dir=FLAGS.checkpoint_dir)
  File "/Users/asuma2/Code/GAN/ImageCompletion/dcgan-completion.tensorflow/model.py", line 65, in __init__
    self.build_model()
  File "/Users/asuma2/Code/GAN/ImageCompletion/dcgan-completion.tensorflow/model.py", line 81, in build_model
    self.D_, self.D_logits_ = self.discriminator(self.G, reuse=True)
  File "/Users/asuma2/Code/GAN/ImageCompletion/dcgan-completion.tensorflow/model.py", line 312, in discriminator
    h1 = lrelu(self.d_bn1(conv2d(h0, self.df_dim*2, name='d_h1_conv')))
  File "/Users/asuma2/Code/GAN/ImageCompletion/dcgan-completion.tensorflow/ops.py", line 34, in __call__
    ema_apply_op = self.ema.apply([batch_mean, batch_var])
  File "/Users/asuma2/miniconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 391, in apply
    self._averages[var], var, decay, zero_debias=zero_debias))
  File "/Users/asuma2/miniconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 70, in assign_moving_average
    update_delta = _zero_debias(variable, value, decay)
  File "/Users/asuma2/miniconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 177, in _zero_debias
    trainable=False)
  File "/Users/asuma2/miniconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1024, in get_variable
    custom_getter=custom_getter)
  File "/Users/asuma2/miniconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 850, in get_variable
    custom_getter=custom_getter)
  File "/Users/asuma2/miniconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 346, in get_variable
    validate_shape=validate_shape)
  File "/Users/asuma2/miniconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 331, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/Users/asuma2/miniconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 650, in _get_single_variable
    "VarScope?" % name)
ValueError: Variable d_bn1/d_bn1_2/d_bn1_2/moments/moments_1/mean/ExponentialMovingAverage/biased does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

**Comment by aselle** [comment]
In general we cannot support other TensorFlow examples written by others. On the other hand, this question should be asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by ustcxxs** [comment]
you should change the version of tensorflow
