### ISSUE TITLE
imagnet example classify_image.py results in `AttrValue missing value with expected type 'bool'`

### ISSUE THREAD

**Issue by shackenberg** [tensorflow/tensorflow#747]
Hi,

after having gotten the mnist example to run, I tried the imagenet/classify_image.py, but the script results an `AttrValue missing value with expected type 'bool'` error.

I use a ec2 g2.2xlarge with GRID K520 and ubuntu 14.04. For the installation I used [erikbern's install-tensorflow.sh](https://gist.github.com/erikbern/78ba519b97b440e10640), but used the cuda 7.0 deb installer and installed Tensorflow master (22b6b23d9778fe7ef53e1597248558f21d1dda48) instead of 0.5.0.

This is the complete error message
```bash
python classify_image.py
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcublas.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcudnn.so.6.5 locally
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcurand.so.7.0 locally
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:909] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_init.cc:103] Found device 0 with properties:
name: GRID K520
major: 3 minor: 0 memoryClockRate (GHz) 0.797
pciBusID 0000:00:03.0
Total memory: 4.00GiB
Free memory: 3.95GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:127] DMA: 0
I tensorflow/core/common_runtime/gpu/gpu_init.cc:137] 0:   Y
I tensorflow/core/common_runtime/gpu/gpu_device.cc:707] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GRID K520, pci bus id: 0000:00:03.0)
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:43] Allocating 3.66GiB bytes.
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] GPU 0 memory begins at 0x7022a0000 extends to 0x7ec588000
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:67] Creating bin of max chunk size 1.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:67] Creating bin of max chunk size 2.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:67] Creating bin of max chunk size 4.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:67] Creating bin of max chunk size 8.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:67] Creating bin of max chunk size 16.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:67] Creating bin of max chunk size 32.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:67] Creating bin of max chunk size 64.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:67] Creating bin of max chunk size 128.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:67] Creating bin of max chunk size 256.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:67] Creating bin of max chunk size 512.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:67] Creating bin of max chunk size 1.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:67] Creating bin of max chunk size 2.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:67] Creating bin of max chunk size 4.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:67] Creating bin of max chunk size 8.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:67] Creating bin of max chunk size 16.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:67] Creating bin of max chunk size 32.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:67] Creating bin of max chunk size 64.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:67] Creating bin of max chunk size 128.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:67] Creating bin of max chunk size 256.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:67] Creating bin of max chunk size 512.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:67] Creating bin of max chunk size 1.00GiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:67] Creating bin of max chunk size 2.00GiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:67] Creating bin of max chunk size 4.00GiB
E tensorflow/core/framework/op_segment.cc:53] Create kernel failed: Invalid argument: AttrValue missing value with expected type 'bool'
         for attr 'align_corners'
        ; NodeDef: ResizeBilinear = ResizeBilinear[T=DT_FLOAT, align_corners=<Unknown AttrValue type>, _device="/job:localhost/replica:0/task:0/cpu:0"](ExpandDims/_3, ResizeBilinear/size/_5); Op<name=ResizeBilinear; signature=images:T, size:int32 -> resized_images:float; attr=T:type,allowed=[DT_UINT8, DT_INT8, DT_INT16, DT_INT32, DT_INT64, DT_FLOAT, DT_DOUBLE]; attr=align_corners:bool,default=false>
E tensorflow/core/common_runtime/executor.cc:265] Executor failed to create kernel. Invalid argument: AttrValue missing value with expected type 'bool'
         for attr 'align_corners'
        ; NodeDef: ResizeBilinear = ResizeBilinear[T=DT_FLOAT, align_corners=<Unknown AttrValue type>, _device="/job:localhost/replica:0/task:0/cpu:0"](ExpandDims/_3, ResizeBilinear/size/_5); Op<name=ResizeBilinear; signature=images:T, size:int32 -> resized_images:float; attr=T:type,allowed=[DT_UINT8, DT_INT8, DT_INT16, DT_INT32, DT_INT64, DT_FLOAT, DT_DOUBLE]; attr=align_corners:bool,default=false>
         [[Node: ResizeBilinear = ResizeBilinear[T=DT_FLOAT, align_corners=<Unknown AttrValue type>, _device="/job:localhost/replica:0/task:0/cpu:0"](ExpandDims/_3, ResizeBilinear/size/_5)]]
Traceback (most recent call last):
  File "classify_image.py", line 214, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "classify_image.py", line 210, in main
    run_inference_on_image(image)
  File "classify_image.py", line 173, in run_inference_on_image
    {'DecodeJpeg/contents:0': image_data})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 388, in run
    results = self._do_run(target_list, unique_fetch_targets, feed_dict_string)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 464, in _do_run
    e.code)
tensorflow.python.framework.errors.InvalidArgumentError: AttrValue missing value with expected type 'bool'
         for attr 'align_corners'
        ; NodeDef: ResizeBilinear = ResizeBilinear[T=DT_FLOAT, align_corners=<Unknown AttrValue type>, _device="/job:localhost/replica:0/task:0/cpu:0"](ExpandDims/_3, ResizeBilinear/size/_5); Op<name=ResizeBilinear; signature=images:T, size:int32 -> resized_images:float; attr=T:type,allowed=[DT_UINT8, DT_INT8, DT_INT16, DT_INT32, DT_INT64, DT_FLOAT, DT_DOUBLE]; attr=align_corners:bool,default=false>
         [[Node: ResizeBilinear = ResizeBilinear[T=DT_FLOAT, align_corners=<Unknown AttrValue type>, _device="/job:localhost/replica:0/task:0/cpu:0"](ExpandDims/_3, ResizeBilinear/size/_5)]]
Caused by op u'ResizeBilinear', defined at:
  File "classify_image.py", line 214, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "classify_image.py", line 210, in main
    run_inference_on_image(image)
  File "classify_image.py", line 160, in run_inference_on_image
    create_graph()
  File "classify_image.py", line 143, in create_graph
    _ = tf.import_graph_def(graph_def, name='')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 243, in import_graph_def
    compute_shapes=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1882, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1081, in __init__
    self._traceback = _extract_stack()
```

**Comment by vrv** [comment]
I think I fixed this in 5853ad99dd3f8b443fdb97d83de35fe057db9e7f
