### ISSUE TITLE
Contrib breaks rendering with gym

### ISSUE THREAD

**Issue by act65** [tensorflow/tensorflow#7486]
Using; pyenv, python 3.5.2, tensorflow 0.12, gym 0.7.3, ubuntu 14.04.5 lts, pyglet 1.2.4.

(1) Runs perfectly fine. I see a little game of pong...
```
import tensorflow as tf
import gym
env = gym.make("Pong-v0")
env.reset()
for _ in range(1000):
    env.render()
    env.step(env.action_space.sample()) # take a random action
``` 

***
(2) _Raises_: `ImportError` from pyglet.gl due to `'NoneType' object has no attribute 'decode'` in pyglet/compat.py.
```
import tensorflow as tf
import tensorflow.contrib.slim as slim
import gym
env = gym.make("Pong-v0")
env.reset()
for _ in range(1000):
    env.render()
    env.step(env.action_space.sample()) # take a random action
``` 

I doubt the problem is tf.slim. But one of the contrib modules seems to break `pyglet.gl`.

**Comment by yaroslavvb** [comment]
Could you isolate the problem a bit better? (ie, is this a bug in TensorFlow, or in gym? )

**Comment by act65** [comment]
The renderer works, but then I do it again but import tensorflow.contrib and it breaks. It must be tensorflow?!?

**Comment by yaroslavvb** [comment]
ps, one debugging tip is to do `python -m pdb script.py` and then press C, it'll break you into debugger so you can poke around to see why it's trying to call `decode` on a `None` object

**Comment by act65** [comment]
well here is the full traceback if it helps.

```
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
[2017-02-15 11:29:59,704] Making new env: Pong-v0
Traceback (most recent call last):
  File "script.py", line 7, in <module>
    env.render()
  File "/home/ws_sc_2/.pyenv/versions/3.5.2/lib/python3.5/site-packages/gym/core.py", line 174, in render
    return self._render(mode=mode, close=close)
  File "/home/ws_sc_2/.pyenv/versions/3.5.2/lib/python3.5/site-packages/gym/envs/atari/atari_env.py", line 119, in _render
    from gym.envs.classic_control import rendering
  File "/home/ws_sc_2/.pyenv/versions/3.5.2/lib/python3.5/site-packages/gym/envs/classic_control/rendering.py", line 23, in <module>
    from pyglet.gl import *
  File "/home/ws_sc_2/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pyglet/gl/__init__.py", line 236, in <module>
    import pyglet.window
  File "/home/ws_sc_2/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pyglet/window/__init__.py", line 1816, in <module>
    gl._create_shadow_window()
  File "/home/ws_sc_2/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pyglet/gl/__init__.py", line 205, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/home/ws_sc_2/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pyglet/window/xlib/__init__.py", line 163, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/ws_sc_2/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pyglet/window/__init__.py", line 504, in __init__
    config = screen.get_best_config(template_config)
  File "/home/ws_sc_2/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pyglet/canvas/base.py", line 161, in get_best_config
    configs = self.get_matching_configs(template)
  File "/home/ws_sc_2/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pyglet/canvas/xlib.py", line 179, in get_matching_configs
    configs = template.match(canvas)
  File "/home/ws_sc_2/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pyglet/gl/xlib.py", line 29, in match
    have_13 = info.have_version(1, 3)
  File "/home/ws_sc_2/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pyglet/gl/glx_info.py", line 86, in have_version
    client_version = self.get_client_version().split()[0]
  File "/home/ws_sc_2/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pyglet/gl/glx_info.py", line 118, in get_client_version
    return asstr(glXGetClientString(self.display, GLX_VERSION))
  File "/home/ws_sc_2/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pyglet/compat.py", line 88, in asstr
    return s.decode("utf-8")
AttributeError: 'NoneType' object has no attribute 'decode'
```

**Comment by yaroslavvb** [comment]
any idea why `s` is None there?

**Comment by yaroslavvb** [comment]
The reason I ask is because it's not clear that it's a tensorflow issue. It could be a bad interaction between TF and Gym that should be fixed on Gym side

**Comment by act65** [comment]
yea, fair point, I see how I might not be an issue with TF. and no, I dont have any idea why `s` is None. thus why I am here...

**Comment by aselle** [comment]
Maybe move this below import gym?
`import tensorflow.contrib.slim as slim`
But generally, I agree, it's not clear that this is a tensorflow issue.

**Comment by act65** [comment]
yea, I tried below. same issue

**Comment by yaroslavvb** [comment]
@act65 it may be worth filing an issue under https://github.com/openai/gym/issues since other users of gym may have ran into this issue before

**Comment by act65** [comment]
ah, I probably should have checked gym's issues... it seems you have already met a similar issue? https://github.com/openai/gym/issues/403

**Comment by yaroslavvb** [comment]
Ah, yes, indeed, it looks like I solved this exact issue and forgot about it. Good thing that Github never forgets
