### ISSUE TITLE
tensorflow.python.framework.errors_impl.InternalError

### ISSUE THREAD

**Issue by suoyike1** [tensorflow/tensorflow#74999]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tf-gpu 1.13.1

### Custom code

No

### OS platform and distribution

ubuntu18.04

### Mobile device

/

### Python version

3.7

### Bazel version

0.19.2

### GCC/compiler version

4.8

### CUDA/cuDNN version

10.0

### GPU model and memory

8G

### Current behavior?

when train a model it stop early then i get bug

### Standalone code to reproduce the issue

```shell
https://github.com/MarlonCajamarca/Keras-LSTM-Trajectory-Prediction/blob/5297ab5e649971ed42ca9f8efa9fe925b7da982b/Train_Test_Scripts/LSTM_trainer.py
```

### Relevant log output

```shell
(lstm) wd@wd-Lenovo-Legion-Y9000K2021H:~/cjy2024.3/Keras-LSTM-Trajectory-Prediction/Train_Test_Scripts$ python LSTM_trainer.py  /home/wd/cjy2024.3/Keras-LSTM-Trajectory-Prediction/output_folder/train-test.h5  /home/wd/cjy2024.3/Keras-LSTM-Trajectory-Prediction/output_folder  config_lstm.json
Using TensorFlow backend.
2024-09-03 14:49:26.341775: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
2024-09-03 14:49:26.364931: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2304000000 Hz
2024-09-03 14:49:26.365397: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55c1dcd26d90 executing computations on platform Host. Devices:
2024-09-03 14:49:26.365410: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2024-09-03 14:49:26.452693: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2024-09-03 14:49:26.453128: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55c1dcbe8a90 executing computations on platform CUDA. Devices:
2024-09-03 14:49:26.453144: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): NVIDIA GeForce RTX 3070 Laptop GPU, Compute Capability 8.6
2024-09-03 14:49:26.453219: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: NVIDIA GeForce RTX 3070 Laptop GPU major: 8 minor: 6 memoryClockRate(GHz): 1.56
pciBusID: 0000:01:00.0
totalMemory: 7.77GiB freeMemory: 6.92GiB
2024-09-03 14:49:26.453229: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2024-09-03 14:49:26.453726: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2024-09-03 14:49:26.453732: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2024-09-03 14:49:26.453735: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2024-09-03 14:49:26.453774: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6733 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 3070 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6)
 Datasets successfully loaded!
 X_train shape : (392399, 4, 15) 
 Y_train shape : (392399, 4, 30)
 --> LSTM model instantiation started!
WARNING:tensorflow:From /home/wd/anaconda3/envs/lstm/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
 --> LSTM model successfully created...
____________________________________________________________________________________________________________________________________________________________________________________
Layer (type)                                                                     Output Shape                                                            Param #                    
====================================================================================================================================================================================
lstm_inputs (InputLayer)                                                         (None, None, 15)                                                        0                          
____________________________________________________________________________________________________________________________________________________________________________________
Bidirectional_lstm_1 (Bidirectional)                                             (None, None, 1024)                                                      2166784                    
____________________________________________________________________________________________________________________________________________________________________________________
Bidirectional_lstm_2 (Bidirectional)                                             (None, None, 960)                                                       5783040                    
____________________________________________________________________________________________________________________________________________________________________________________
Bidirectional_lstm_3 (Bidirectional)                                             (None, None, 640)                                                       3281920                    
____________________________________________________________________________________________________________________________________________________________________________________
time_distributed_0 (TimeDistributed)                                             (None, None, 256)                                                       164096                     
____________________________________________________________________________________________________________________________________________________________________________________
time_distributed_1 (TimeDistributed)                                             (None, None, 128)                                                       32896                      
____________________________________________________________________________________________________________________________________________________________________________________
time_distributed_output (TimeDistributed)                                        (None, None, 30)                                                        3870                       
====================================================================================================================================================================================
Total params: 11,432,606
Trainable params: 11,432,606
Non-trainable params: 0
____________________________________________________________________________________________________________________________________________________________________________________
create_models have done_______
compile_models have done_______
Overview hyperparameters used on training :  ARCH--15i_30o_10sld_norm3_vill_cascade2-_Data-_final_concat512___bs-512_lr-0.01_loss-mae_opt-Ranger_BD-True_BDmrg-concat_amsG-False_DP-False_sw-0.9_sync-1_act-selu_minLR-1e-05_ptc-10_ep-100
[Errno 17] File exists: '/home/wd/cjy2024.3/Keras-LSTM-Trajectory-Prediction/output_folder/ARCH--15i_30o_10sld_norm3_vill_cascade2-_Data-_final_concat512___bs-512_lr-0.01_loss-mae_opt-Ranger_BD-True_BDmrg-concat_amsG-False_DP-False_sw-0.9_sync-1_act-selu_minLR-1e-05_ptc-10_ep-100'
WARNING:tensorflow:From /home/wd/anaconda3/envs/lstm/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Train on 333539 samples, validate on 58860 samples
Epoch 1/100
2024-09-03 14:52:29.476637: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
2024-09-03 15:03:24.097886: E tensorflow/stream_executor/cuda/cuda_dnn.cc:82] CUDNN_STATUS_EXECUTION_FAILED
in tensorflow/stream_executor/cuda/cuda_dnn.cc(1477): 'cudnnRNNForwardTraining( cudnn.handle(), rnn_desc.handle(), model_dims.seq_length, input_desc.handles(), input_data.opaque(), input_h_desc.handle(), input_h_data.opaque(), input_c_desc.handle(), input_c_data.opaque(), rnn_desc.params_handle(), params.opaque(), output_desc.handles(), output_data->opaque(), output_h_desc.handle(), output_h_data->opaque(), output_c_desc.handle(), output_c_data->opaque(), workspace.opaque(), workspace.size(), reserve_space.opaque(), reserve_space.size())'
2024-09-03 15:03:24.097921: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at cudnn_rnn_ops.cc:1224 : Internal: Failed to call ThenRnnForward with model config: [rnn_mode, rnn_input_mode, rnn_direction_mode]: 2, 0, 0 , [num_layers, input_size, num_units, dir_count, seq_length, batch_size]: [1, 15, 512, 1, 4, 512] 
2024-09-03 15:03:24.097988: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at cudnn_rnn_ops.cc:1224 : Internal: Failed to call ThenRnnForward with model config: [rnn_mode, rnn_input_mode, rnn_direction_mode]: 2, 0, 0 , [num_layers, input_size, num_units, dir_count, seq_length, batch_size]: [1, 15, 512, 1, 4, 512] 
Traceback (most recent call last):
  File "LSTM_trainer.py", line 450, in <module>
    LstmTrainer(args.dataset, args.output, hyperparameters, args.use_checkpoint).run()
  File "LSTM_trainer.py", line 77, in run
    self.fit_models()
  File "LSTM_trainer.py", line 235, in fit_models
    callbacks=[early_stop, model_checkpoint])
  File "/home/wd/anaconda3/envs/lstm/lib/python3.7/site-packages/keras/engine/training.py", line 1039, in fit
    validation_steps=validation_steps)
  File "/home/wd/anaconda3/envs/lstm/lib/python3.7/site-packages/keras/engine/training_arrays.py", line 199, in fit_loop
    outs = f(ins_batch)
  File "/home/wd/anaconda3/envs/lstm/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/home/wd/anaconda3/envs/lstm/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/home/wd/anaconda3/envs/lstm/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/home/wd/anaconda3/envs/lstm/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InternalError: Failed to call ThenRnnForward with model config: [rnn_mode, rnn_input_mode, rnn_direction_mode]: 2, 0, 0 , [num_layers, input_size, num_units, dir_count, seq_length, batch_size]: [1, 15, 512, 1, 4, 512] 
         [[{{node Bidirectional_lstm_1/CudnnRNN_1}}]]
         [[{{node loss/mul}}]]

```

Tue Sep  3 15:01:13 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.223.02   Driver Version: 470.223.02   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| N/A   52C    P8    19W /  N/A |   1699MiB /  7957MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1269      G   /usr/lib/xorg/Xorg                 38MiB |
|    0   N/A  N/A      1341      G   /usr/bin/gnome-shell              106MiB |
|    0   N/A  N/A      1710      G   /usr/lib/xorg/Xorg                354MiB |
|    0   N/A  N/A      2184      G   /usr/bin/gnome-shell               50MiB |
|    0   N/A  N/A      2545      G   /usr/lib/firefox/firefox          156MiB |
|    0   N/A  N/A     14950      C   python                            987MiB |
+-----------------------------------------------------------------------------+

**Comment by Venkat6871** [comment]
Hi **@suoyike1** ,
We see that you are using old version of tensorflow (1.x) which is not actively supported, We recommend that you upgrade to 2.6.0 and let us know if the issue still persists in newer versions.
Thank you!

**Comment by Venkat6871** [comment]
Hi @suoyike1 ,
Apologies for the delay. Actually, I meant to say that you need to upgrade to version 2.16.0 or 2.17.0. Please let us know if the issue still persists in the newer versions. However, I mistakenly typed 2.6.0 instead of 2.16.0. I apologize for this earlier miscommunication.
Thank you!

**Comment by suoyike1** [comment]
thank you all very much! I had address this problem for upgrading 2.6.0. Nothing more happy than code run correctly! thanks again!
