### ISSUE TITLE
No module named copy_reg - Installation Issue

### ISSUE THREAD

**Issue by udaysinghcode** [tensorflow/tensorflow#75]
Currently this is my output after installing Tensorflow. I thought it installed six as well, but was wondering why copyreg doesn't exist in six. Anyone know what to do?

tensorflow % python                                                   

Python 2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

Input:
import tensorflow as tf

Result:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/tensorflow/__init__.py", line 4, in <module>
    from tensorflow.python import *
  File "/Library/Python/2.7/site-packages/tensorflow/python/__init__.py", line 13, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/Library/Python/2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 8, in <module>
    from google.protobuf import reflection as _reflection
  File "/Library/Python/2.7/site-packages/google/protobuf/reflection.py", line 58, in <module>
    from google.protobuf.internal import python_message as message_impl
  File "/Library/Python/2.7/site-packages/google/protobuf/internal/python_message.py", line 59, in <module>
    import six.moves.copyreg as copyreg
ImportError: No module named copyreg

**Comment by vrv** [comment]
Please see if our detailed installation instructions page helps:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#common_install_problems

**Comment by udaysinghcode** [comment]
@vrv Just saw this minutes after I posted. Thanks, but I got it all figured out, I forgot to use Python 2.7.10 and was using the 2.7.6 that comes with my computer.

**Comment by ShoujunChen** [comment]
Below solution in detailed installation page resolved my issue:

Upgrade the system-wide copy of six:

sudo easy_install -U six
