### ISSUE TITLE
Saver seems broken: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model.ckpt-0

### ISSUE THREAD

**Issue by JianbangZ** [tensorflow/tensorflow#751]
Updated to the last commit of 1/11. Saver seems broken. Here is the stack. 

File "cnn_eval.py", line 132, in evaluate
    eval_once(saver, summary_writer, logits, top_k_op,labels, names, prob, summary_op)
  File "cnn_eval.py", line 43, in eval_once
    saver.restore(sess, ckpt.model_checkpoint_path)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 904, in restore
    sess.run([self._restore_op_name], {self._filename_tensor_name: save_path})
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 388, in run
    results = self._do_run(target_list, unique_fetch_targets, feed_dict_string)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 464, in _do_run
    e.code)
tensorflow.python.framework.errors.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model.ckpt-0
         [[Node: save/restore_slice_2 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_2/tensor_name, save/restore_slice_2/shape_and_slice)]]
Caused by op u'save/restore_slice_2', defined at:
  File "cnn_eval.py", line 147, in <module>
    tf.app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "cnn_eval.py", line 143, in main
    evaluate()
  File "cnn_eval.py", line 121, in evaluate
    saver = tf.train.Saver(variables_to_restore)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 723, in __init__
    restore_sequentially=restore_sequentially)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 432, in build
    filename_tensor, vars_to_save, restore_sequentially, reshape)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 191, in _AddRestoreOps
    values = self.restore_op(filename_tensor, vs, preferred_shard)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 106, in restore_op
    preferred_shard=preferred_shard)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/io_ops.py", line 192, in _restore_slice
    preferred_shard, name=name)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 271, in _restore_slice
    preferred_shard=preferred_shard, name=name)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 659, in apply_op
    op_def=op_def)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1882, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1081, in __init__
    self._traceback = _extract_stack()

**Comment by sherrym** [comment]
Could you please try the following in order?

1. Roll tensorflow/python/training/saver.py back to 1c579361cd1e088dd5e05a394b1561a73e3667ba and see if it works?

2. Check the paths in {your-saver-dir}/checkpoint to make sure they are pointing to the right files. Also please attach a copy in this report.

3. Attach your cnn_eval.py.

Thanks,
Sherry

**Comment by JianbangZ** [comment]
Sherry,
I haven't tried everything you said, but I do find the cause is the model file path in checkpint file is incorrect. 
Here I attach my training script to and evaluation script , as you can see from cnn_train.py, even the FLAGS.train_dir is already defined, it's excluded for some reason
For a older version I use (till Jan 5), the checkpoint file look like:
    model_checkpoint_path: "./train/model.ckpt-XXX"
    all_model_checkpoint_paths: "./train/model.ckpt-XXX"
With Yesterday's version (till Jan 11), the checkpoint file look like:
    model_checkpoint_path: "model.ckpt-XXX"
    all_model_checkpoint_paths: "model.ckpt-XXX"
[cnn_eval_train.zip](https://github.com/tensorflow/tensorflow/files/88055/cnn_eval_train.zip)

**Comment by sherrym** [comment]
The problem is caused by the fix for #571.

I will contact MarkDaoust to see if he can provide a fix today. In the meantime, you can do one of the following:
- Rollback to 1c579361cd1e088dd5e05a394b1561a73e3667ba (before the fix for #571)

or

- Add this line to your code that restores from checkpoint:

if ckpt and ckpt.model_checkpoint_path:
  model_checkpoint_path = ckpt.model_checkpoint_path
  if not os.path.isabs(model_checkpoint_path):
    model_checkpoint_path = os.path.relpath(model_checkpoint_path, save_dir)
  # Replace all ckpt.model_checkpoint_path with model_checkpoint_path to make sure
  # we are using the correct path.
  saver.restore(sess, model_checkpoint_path)
  global_step = model_checkpoint_path

Please let me know if it works for you.

Thanks,
Sherry

**Comment by MarkDaoust** [comment]
Sorry about that.

It sounds like you've working on this already.

You've probably already figured out that maybe one starting point could be moving the [`path.join` in `saver.latest_checkpoint`](https://github.com/tensorflow/tensorflow/blob/eef2aaa3f7931cc3c0e7bbc6757386cfbcf5e3ef/tensorflow/python/training/saver.py#L923-L925) to the [end of `saver.get_checkpoint_state`](https://github.com/tensorflow/tensorflow/blob/eef2aaa3f7931cc3c0e7bbc6757386cfbcf5e3ef/tensorflow/python/training/saver.py#L550), and applying it instead to all the paths in `ckp` (unless I've missed something else). 
I'd also add asserts to the tests checking that all the file paths returned from `save.last_checkpoints` and  `tf.train.get_checkpoint_state` exist (which would have caught this bug).

Just let me know if you want any of that in a pull request, or if there's anything else I can do.

**Comment by nitish11** [comment]
The issue is because of compatibility with versions of tensorflow on which the model is built.
To downgrade tensorflow to v.0.11.0 :  
```
TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.11.0rc0-cp27-none-linux_x86_64.whl
sudo pip install --upgrade $TF_BINARY_URL
```

**Comment by Erdos001** [comment]
after the tensorflow r12, the model will be saced in folder with three files like:
XXX.meta
XXX.ckpt-250000.index
XXX.data-00000-of-00001
and I restore the model with code like this:
saver = tf.train.import_meta_graph('./src/models/20170512-110547/model-20170512-110547.meta')
                saver.restore(sess,tf.train.latest_checkpoint('./src/models/20170512-110547/'))
 it dosen't work
TypeError: expected bytes, NoneType found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/train_tripletloss.py", line 483, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "src/train_tripletloss.py", line 170, in main
    saver.restore(sess,tf.train.latest_checkpoint('/home/tools/Tools/raoqiang/facenet/src/models/20170512-110547/'))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1457, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1039, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1021, in _run_fn
    status, run_metadata)
SystemError: <built-in function TF_Run> returned a result with an error set


finally I find a solution:
--image_size 160 \
--optimizer ADAM
--model_def models.inception_resnet_v1 \
 I changed the --optimizer ADAGRAD to --optimizer ADAM
