### ISSUE TITLE
ImportError: No module named '_pywrap_tensorflow'

### ISSUE THREAD

**Issue by DutchDandy** [tensorflow/tensorflow#7529]
When I try to run a simple test to see if Tensorflow works I get the following error. I already tried to upgrade tensorflow with: `$pip tensorflow -- upgrade` and with: `pip install -- upgrade https://storage.googleapis.com/tensorflow/windows/gpu/tensorflow_gpu-1.0.0rc2-cp35m-win-amd64.whl`

But I  keep on getting the response in my Command Line that everything is up to date, yet this is my error:

  ```
File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 903, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: Kan opgegeven module niet vinden.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\__init__.py", line 66, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 21, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow')
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Gebruiker\Desktop\Sentiment.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 903, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: Kan opgegeven module niet vinden.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\__init__.py", line 66, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 21, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow')
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow'
````

**Comment by Carmezim** [comment]
You need `MSVCP140.DLL` in your system. Check if it is in your `PATH` and if it's not install [Visual C++ Redistributable 2015 x64](https://www.microsoft.com/en-us/download/details.aspx?id=53587)

**Comment by codeloverr** [comment]
I am getting the same error in Ubuntu 16.04 with TF v1.0 rc2. I have installed from sources.

**Comment by Carmezim** [comment]
@codeloverr please see if [this](http://stackoverflow.com/questions/35953210/error-running-basic-tensorflow-example) helps you.

**Comment by DutchDandy** [comment]
@Carmezim 

Thank you for the suggestions. I checked the path and installed  Visual C++ Redistributable 2015 x64.

`Traceback (most recent call last):
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 903, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: Een initialisatieroutine van de dynamic link library (DLL-bestand) is mislukt.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\__init__.py", line 66, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 21, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow')
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Gebruiker\Desktop\Sentiment.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 903, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: Een initialisatieroutine van de dynamic link library (DLL-bestand) is mislukt.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\__init__.py", line 66, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 21, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow')
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow'`

I noticed that with some other (statistical) modules (SKlearn) I have the same problems.

Do you have any other ideas on how I could solve this?

**Comment by Carmezim** [comment]
If you are sure it's not a missing `MSVCP140.DLL`, I am out of ideas for this one then for now, as yourself already pointed out it's not a TensorFlow specific issue. 
Maybe @mrry can help.
I would suggest to post it on StackOverflow.

**Comment by DutchDandy** [comment]
@Carmezim, thank you anyway! I uninstalled sklearn and now it functions, but it does not seems to do the trick for TensorFlow.

**Comment by Carmezim** [comment]
@DutchDandy Did you mean you uninstalled then installed sklearn again and it worked but the same process didn't yield the same result with TensorFlow?

**Comment by DutchDandy** [comment]
@Carmezim Exactly that.

**Comment by Carmezim** [comment]
@DutchDandy  Well, that error usually comes from the mentioned missing DLL, if your CUDA and cuDNN are properly installed. 
The other alternative is to replace your python distribution for the Anaconda one as this is a Python.org distribution specific problem or wait if other folks can help on this one.

**Comment by mrry** [comment]
Since you're running the GPU version, have you ensured that `%CUDA_HOME%` is set, and the CUDA and cuDNN DLLs are in your `%PATH%`?

**Comment by DutchDandy** [comment]
@mrry 
Thank you for the suggestion.

I decided to work around my Windows problem, by doing the rest of my programming on a VPS with Ubuntu, that seems to have done the trick for the problems with Tensorflow.

**Comment by Carmezim** [comment]
@DutchDandy a quick follow up. Another folk was having a similar issue [#7705] and it was that cuDNN wasn't properly installed missing some DLLs on his `%PATH%` as @mrry suggested.

**Comment by Caesarzhang** [comment]
@mrry  When you say`%CUDA_HOME%` , do you mean `%CUDA_PATH%` ?
I'm facing with the same problem, and I can only see `%CUDA_PATH%` in my environment variable.

**Comment by Madhivarman** [comment]
when i installed 

` export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.11.0rc2-py2-none-any.whl`

and upgraded in my linux machine i get  following error

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 21, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _pywrap_tensorflow

**Comment by gunan** [comment]
Please install a later version, 0.11 may have some issues, may be incompatible with the latestruntimes, we have not ran any tests on that pip package for almost a year now.

**Comment by rama199310** [comment]
i am getting below error after installation of tensorflow :

Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\python38\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
  File "C:\python38\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\python38\lib\site-packages\tensorflow\python\__init__.py", line 54, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\python38\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\python38\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ModuleNotFoundError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chatgui.py", line 7, in <module>
    from keras.models import load_model
  File "C:\python38\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\python38\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\python38\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\python38\lib\site-packages\keras\backend\__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "C:\python38\lib\site-packages\keras\backend\load_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "C:\python38\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "C:\python38\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\python38\lib\site-packages\tensorflow\python\__init__.py", line 60, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\python38\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
  File "C:\python38\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\python38\lib\site-packages\tensorflow\python\__init__.py", line 54, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\python38\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\python38\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ModuleNotFoundError: No module named '_pywrap_tensorflow'


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.

**Comment by mihaimaruseac** [comment]
Please open a new issue, filling in the template. and posting the error logs using markdown markup (see the M and the down arrow button just above the green "Comment" button, click on it for a primer)

Note that we don't have a pip released for python3.8.

**Comment by Sumitrke88** [comment]
I have installed python 3.7, Keras 2.4.3, and TensorFlow 1.0.0
now upgraded version 
pip install --upgrade tensorflow but still have the same version 

Requirement already up-to-date: tensorflow in c:\programdata\anaconda3\lib\site-packages (1.0.0)
Requirement already satisfied, skipping upgrade: six>=1.10.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (1.14.0)
Requirement already satisfied, skipping upgrade: numpy>=1.11.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (1.18.1)
Requirement already satisfied, skipping upgrade: protobuf>=3.1.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (3.11.3)
Requirement already satisfied, skipping upgrade: wheel>=0.26 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (0.34.2)
Requirement already satisfied, skipping upgrade: setuptools in c:\programdata\anaconda3\lib\site-packages (from protobuf>=3.1.0->tensorflow) (45.2.0.post20200210)
Note: you may need to restart the kernel to use updated packages.

======== If import the keras then show the error ==========
import keras
ImportError                               Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in swig_import_helper()
     17         try:
---> 18             fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
     19         except ImportError:

C:\ProgramData\Anaconda3\lib\imp.py in find_module(name, path)
    295     else:
--> 296         raise ImportError(_ERR_MSG.format(name), name=name)
    297 

ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\__init__.py in <module>
     65     # use `dlopen()` for dynamic loading.
---> 66     from tensorflow.python import pywrap_tensorflow
     67 except ImportError:

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     27             return _mod
---> 28     _pywrap_tensorflow = swig_import_helper()
     29     del swig_import_helper

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in swig_import_helper()
     19         except ImportError:
---> 20             import _pywrap_tensorflow
     21             return _pywrap_tensorflow

ModuleNotFoundError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\keras\__init__.py in <module>
      2 try:
----> 3     from tensorflow.keras.layers.experimental.preprocessing import RandomRotation
      4 except ImportError:

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\__init__.py in <module>
     23 # pylint: disable=wildcard-import
---> 24 from tensorflow.python import *
     25 # pylint: enable=wildcard-import

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\__init__.py in <module>
     71 above this error message when asking for help.""" % traceback.format_exc()
---> 72   raise ImportError(msg)
     73 

ImportError: Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
  File "C:\ProgramData\Anaconda3\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 66, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ModuleNotFoundError: No module named '_pywrap_tensorflow'


Failed to load the native TensorFlow runtime.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-3-88d96843a926> in <module>
----> 1 import keras

C:\ProgramData\Anaconda3\lib\site-packages\keras\__init__.py in <module>
      4 except ImportError:
      5     raise ImportError(
----> 6         'Keras requires TensorFlow 2.2 or higher. '
      7         'Install TensorFlow via `pip install tensorflow`')
      8 

ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`

**Comment by Sumitrke88** [comment]
I also have MSVCP140.DLL

> I have installed python 3.7, Keras 2.4.3, and TensorFlow 1.0.0
> now upgraded version
> pip install --upgrade tensorflow but still have the same version
> 
> Requirement already up-to-date: tensorflow in c:\programdata\anaconda3\lib\site-packages (1.0.0)
> Requirement already satisfied, skipping upgrade: six>=1.10.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (1.14.0)
> Requirement already satisfied, skipping upgrade: numpy>=1.11.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (1.18.1)
> Requirement already satisfied, skipping upgrade: protobuf>=3.1.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (3.11.3)
> Requirement already satisfied, skipping upgrade: wheel>=0.26 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (0.34.2)
> Requirement already satisfied, skipping upgrade: setuptools in c:\programdata\anaconda3\lib\site-packages (from protobuf>=3.1.0->tensorflow) (45.2.0.post20200210)
> Note: you may need to restart the kernel to use updated packages.
> 
> =### **======= If import the keras then show the error ======**====
> import keras
> ImportError Traceback (most recent call last)
> C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in swig_import_helper()
> 17 try:
> ---> 18 fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(**file**)])
> 19 except ImportError:
> 
> C:\ProgramData\Anaconda3\lib\imp.py in find_module(name, path)
> 295 else:
> --> 296 raise ImportError(_ERR_MSG.format(name), name=name)
> 297
> 
> ImportError: No module named '_pywrap_tensorflow'
> 
> During handling of the above exception, another exception occurred:
> 
> ModuleNotFoundError Traceback (most recent call last)
> C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python__init__.py in
> 65 # use `dlopen()` for dynamic loading.
> ---> 66 from tensorflow.python import pywrap_tensorflow
> 67 except ImportError:
> 
> C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in
> 27 return _mod
> ---> 28 _pywrap_tensorflow = swig_import_helper()
> 29 del swig_import_helper
> 
> C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in swig_import_helper()
> 19 except ImportError:
> ---> 20 import _pywrap_tensorflow
> 21 return _pywrap_tensorflow
> 
> ModuleNotFoundError: No module named '_pywrap_tensorflow'
> 
> During handling of the above exception, another exception occurred:
> 
> ImportError Traceback (most recent call last)
> C:\ProgramData\Anaconda3\lib\site-packages\keras__init__.py in
> 2 try:
> ----> 3 from tensorflow.keras.layers.experimental.preprocessing import RandomRotation
> 4 except ImportError:
> 
> C:\ProgramData\Anaconda3\lib\site-packages\tensorflow__init__.py in
> 23 # pylint: disable=wildcard-import
> ---> 24 from tensorflow.python import *
> 25 # pylint: enable=wildcard-import
> 
> C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python__init__.py in
> 71 above this error message when asking for help.""" % traceback.format_exc()
> ---> 72 raise ImportError(msg)
> 73
> 
> ImportError: Traceback (most recent call last):
> File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
> fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(**file**)])
> File "C:\ProgramData\Anaconda3\lib\imp.py", line 296, in find_module
> raise ImportError(_ERR_MSG.format(name), name=name)
> ImportError: No module named '_pywrap_tensorflow'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python__init__.py", line 66, in
> from tensorflow.python import pywrap_tensorflow
> File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in
> _pywrap_tensorflow = swig_import_helper()
> File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
> import _pywrap_tensorflow
> ModuleNotFoundError: No module named '_pywrap_tensorflow'
> 
> Failed to load the native TensorFlow runtime.
> 
> See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error
> 
> for some common reasons and solutions. Include the entire stack trace
> above this error message when asking for help.
> 
> During handling of the above exception, another exception occurred:
> 
> ImportError Traceback (most recent call last)
> in
> ----> 1 import keras
> 
> C:\ProgramData\Anaconda3\lib\site-packages\keras__init__.py in
> 4 except ImportError:
> 5 raise ImportError(
> ----> 6 'Keras requires TensorFlow 2.2 or higher. '
> 7 'Install TensorFlow via `pip install tensorflow`')
> 8
> 
> ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`

I also have MSVCP140.DLL file in my C:\windows\system32\ location
