### ISSUE TITLE
Bazel build fails on RISC-V (riscv64) architecture for TensorFlow 2.17.0

### ISSUE THREAD

**Issue by hansu2022** [tensorflow/tensorflow#75555]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.17.0

### Custom code

Yes

### OS platform and distribution

Linux openeuler-riscv-4-2 6.6.0

### Mobile device

no

### Python version

3.11.6

### Bazel version

6.5.0

### GCC/compiler version

12.3.1

### CUDA/cuDNN version

no

### GPU model and memory

no

### Current behavior?

I am trying to build TensorFlow 2.17.0 on a RISC-V (riscv64) architecture using Bazel 6.5.0. The Bazel version is installed from an RPM package that has successfully passed C++ and Java tests in examples.
When I run the following command to build the TensorFlow pip package:The build fails with the following error:RROR: An error occurred during the fetch of repository 'python': No platform declared for host OS linux on arch riscv64
It seems that the `riscv64` architecture is not supported in the current Bazel rules for Python toolchains.
### Full error log:ERROR: An error occurred during the fetch of repository 'python':
No platform declared for host OS linux on arch riscv64
ERROR: Error computing the main repository mapping: no such package '@python//': No platform declared for host OS linux on arch riscv64

### Standalone code to reproduce the issue

```shell
git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow
git checkout tags/v2.17.0
./configure
export TF_PYTHON_VERSION=3.11
bazel build //tensorflow/tools/pip_package:wheel --repo_env=WHEEL_NAME=tensorflow
```

### Relevant log output

```shell
INFO: Reading 'startup' options from /home/chenweijia/tf/tensorflow/.bazelrc: --windows_enable_symlinks
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=119
INFO: Reading rc options for 'clean' from /home/chenweijia/tf/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'clean' from /home/chenweijia/tf/tensorflow/.bazelrc:
  Inherited 'build' options: --define framework_shared_object=true --define tsl_protobuf_header_only=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --features=-force_no_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library --experimental_link_static_libraries_once=false --incompatible_enforce_config_setting_visibility
INFO: Reading rc options for 'clean' from /home/chenweijia/tf/tensorflow/.tf_configure.bazelrc:
  Inherited 'build' options: --action_env PYTHON_BIN_PATH=/home/chenweijia/tf/venv00/bin/python3 --action_env PYTHON_LIB_PATH=/home/chenweijia/tf/venv00/lib/python3.11/site-packages --python_path=/home/chenweijia/tf/venv00/bin/python3
INFO: Found applicable config definition build:short_logs in file /home/chenweijia/tf/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/chenweijia/tf/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:linux in file /home/chenweijia/tf/tensorflow/.bazelrc: --host_copt=-w --copt=-Wno-all --copt=-Wno-extra --copt=-Wno-deprecated --copt=-Wno-deprecated-declarations --copt=-Wno-ignored-attributes --copt=-Wno-array-bounds --copt=-Wunused-result --copt=-Werror=unused-result --copt=-Wswitch --copt=-Werror=switch --copt=-Wno-error=unused-but-set-variable --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++17 --host_cxxopt=-std=c++17 --config=dynamic_kernels --experimental_guard_against_concurrent_changes
INFO: Found applicable config definition build:dynamic_kernels in file /home/chenweijia/tf/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
(venv00) [openeuler@openeuler-riscv-4-2 tensorflow]$ bazel build //tensorflow/tools/pip_package:wheel --repo_env=WHEEL_NAME=tensorflow
Starting local Bazel server and connecting to it...
... still trying to connect to local Bazel server (251492) after 10 seconds ...
INFO: Reading 'startup' options from /home/chenweijia/tf/tensorflow/.bazelrc: --windows_enable_symlinks
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=119
INFO: Reading rc options for 'build' from /home/chenweijia/tf/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/chenweijia/tf/tensorflow/.bazelrc:
  'build' options: --define framework_shared_object=true --define tsl_protobuf_header_only=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --features=-force_no_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library --experimental_link_static_libraries_once=false --incompatible_enforce_config_setting_visibility
INFO: Reading rc options for 'build' from /home/chenweijia/tf/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/home/chenweijia/tf/venv00/bin/python3 --action_env PYTHON_LIB_PATH=/home/chenweijia/tf/venv00/lib/python3.11/site-packages --python_path=/home/chenweijia/tf/venv00/bin/python3
INFO: Found applicable config definition build:short_logs in file /home/chenweijia/tf/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/chenweijia/tf/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:linux in file /home/chenweijia/tf/tensorflow/.bazelrc: --host_copt=-w --copt=-Wno-all --copt=-Wno-extra --copt=-Wno-deprecated --copt=-Wno-deprecated-declarations --copt=-Wno-ignored-attributes --copt=-Wno-array-bounds --copt=-Wunused-result --copt=-Werror=unused-result --copt=-Wswitch --copt=-Werror=switch --copt=-Wno-error=unused-but-set-variable --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++17 --host_cxxopt=-std=c++17 --config=dynamic_kernels --experimental_guard_against_concurrent_changes
INFO: Found applicable config definition build:dynamic_kernels in file /home/chenweijia/tf/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
INFO: Repository python instantiated at:
  /home/chenweijia/tf/tensorflow/WORKSPACE:45:27: in <toplevel>
  /home/openeuler/.cache/bazel/_bazel_openeuler/6f797a0931e8bb7410946b7d443abe30/external/rules_python/python/repositories.bzl:603:22: in python_register_toolchains
Repository rule toolchain_aliases defined at:
  /home/openeuler/.cache/bazel/_bazel_openeuler/6f797a0931e8bb7410946b7d443abe30/external/rules_python/python/private/toolchains_repo.bzl:236:36: in <toplevel>
ERROR: An error occurred during the fetch of repository 'python':
   Traceback (most recent call last):
        File "/home/openeuler/.cache/bazel/_bazel_openeuler/6f797a0931e8bb7410946b7d443abe30/external/rules_python/python/private/toolchains_repo.bzl", line 149, column 38, in _toolchain_aliases_impl
                host_platform = get_host_platform(os_name, arch)
        File "/home/openeuler/.cache/bazel/_bazel_openeuler/6f797a0931e8bb7410946b7d443abe30/external/rules_python/python/private/toolchains_repo.bzl", line 325, column 13, in get_host_platform
                fail("No platform declared for host OS {} on arch {}".format(os_name, arch))
Error in fail: No platform declared for host OS linux on arch riscv64
ERROR: /home/chenweijia/tf/tensorflow/WORKSPACE:45:27: fetching toolchain_aliases rule //external:python: Traceback (most recent call last):
        File "/home/openeuler/.cache/bazel/_bazel_openeuler/6f797a0931e8bb7410946b7d443abe30/external/rules_python/python/private/toolchains_repo.bzl", line 149, column 38, in _toolchain_aliases_impl
                host_platform = get_host_platform(os_name, arch)
        File "/home/openeuler/.cache/bazel/_bazel_openeuler/6f797a0931e8bb7410946b7d443abe30/external/rules_python/python/private/toolchains_repo.bzl", line 325, column 13, in get_host_platform
                fail("No platform declared for host OS {} on arch {}".format(os_name, arch))
Error in fail: No platform declared for host OS linux on arch riscv64
INFO: Repository bazel_skylib instantiated at:
  /home/chenweijia/tf/tensorflow/WORKSPACE:10:13: in <toplevel>
Repository rule http_archive defined at:
  /home/openeuler/.cache/bazel/_bazel_openeuler/6f797a0931e8bb7410946b7d443abe30/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
ERROR: Error computing the main repository mapping: no such package '@python//': No platform declared for host OS linux on arch riscv64
Loading:
```

**Comment by tilakrayal** [comment]
@hansu2022,
Looks like similar type of
