### ISSUE TITLE
issues install on windows conda env

### ISSUE THREAD

**Issue by alexxucui** [tensorflow/tensorflow#7556]
I have tried to install the tensorflow non-gpu version in the conda env using pip but I got following error:

    "AttributeError: 'NoneType' object has no attribute 'splitlines'" 

But when I install the gpu version it seems fine. Any ideas?

**Comment by Carmezim** [comment]
What code are you trying to run, could you please share an entire log?
Thank you.

**Comment by achase90** [comment]
I'm seeing the same problem. 

Here's my python version:
`Python 3.5.2 |Anaconda 4.3.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)] on win32
`
Pip version is:
` pip 9.0.1`
and the command I'm trying to run:
`pip install --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-0.12.0rc0-cp35-cp35m-win_amd64.whl`

And I get the error:
```
pip install --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-0.12.0rc0-cp35-cp35m-win_amd64.whl
Collecting tensorflow==0.12.0rc0 from https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-0.12.0rc0-cp35-cp35m-win_amd64.whl
  Downloading https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-0.12.0rc0-cp35-cp35m-win_amd64.whl (12.2MB)
    100% |################################| 12.2MB 103kB/s
Requirement already up-to-date: wheel>=0.26 in c:\users\adam\anaconda3\lib\site-packages (from tensorflow==0.12.0rc0)
Exception:
Traceback (most recent call last):
  File "C:\Users\adam\Anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\adam\Anaconda3\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "C:\Users\adam\Anaconda3\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "C:\Users\adam\Anaconda3\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\Users\adam\Anaconda3\lib\site-packages\pip\req\req_set.py", line 666, in _prepare_file
    check_dist_requires_python(dist)
  File "C:\Users\adam\Anaconda3\lib\site-packages\pip\utils\packaging.py", line 48, in check_dist_requires_python
    feed_parser.feed(metadata)
  File "C:\Users\adam\Anaconda3\lib\email\feedparser.py", line 177, in feed
    self._input.push(data)
  File "C:\Users\adam\Anaconda3\lib\email\feedparser.py", line 101, in push
    parts = data.splitlines(True)
AttributeError: 'NoneType' object has no attribute 'splitlines'


```

**Comment by alexxucui** [comment]
@achase90 I tried to use the conda install and seems to be fine:
`conda install -c conda-forge tensorflow=1.0.0`

**Comment by Carmezim** [comment]
It seems a problem with the Anaconda distribution and not TensorFlow build itself. 
@achase90 Could you try with `conda install` as @alexxucui pointed?

**Comment by achase90** [comment]
Thanks for the help, yes, it fixed it.

**Comment by Carmezim** [comment]
This can be closed now.

**Comment by aselle** [comment]
Thanks @Carmzim and @alexxucui.
