### ISSUE TITLE
Delete some files on Windows10 occured error!

### ISSUE THREAD

**Issue by linrio** [tensorflow/tensorflow#7582]
### Environment info
Operating System: Win10

Installed version of CUDA and cuDNN: No
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide: Yes

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`. 1.0.0

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).
In pycharm, the error log is :
```
"D:\Program Files (x86)\Miniconda3\python.exe" G:/codes/tensorflow/models-master/autoencoder/AdditiveGaussianNoiseAutoencoderRunner.py
Extracting MNIST_data\train-images-idx3-ubyte.gz
Extracting MNIST_data\train-labels-idx1-ubyte.gz
Extracting MNIST_data\t10k-images-idx3-ubyte.gz
Extracting MNIST_data\t10k-labels-idx1-ubyte.gz
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "BestSplits" device_type: "CPU"') for unknown op: BestSplits
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "CountExtremelyRandomStats" device_type: "CPU"') for unknown op: CountExtremelyRandomStats
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "FinishedNodes" device_type: "CPU"') for unknown op: FinishedNodes
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "GrowTree" device_type: "CPU"') for unknown op: GrowTree
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ReinterpretStringToFloat" device_type: "CPU"') for unknown op: ReinterpretStringToFloat
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "SampleInputs" device_type: "CPU"') for unknown op: SampleInputs
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ScatterAddNdim" device_type: "CPU"') for unknown op: ScatterAddNdim
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNInsert" device_type: "CPU"') for unknown op: TopNInsert
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNRemove" device_type: "CPU"') for unknown op: TopNRemove
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TreePredictions" device_type: "CPU"') for unknown op: TreePredictions
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "UpdateFertileSlots" device_type: "CPU"') for unknown op: UpdateFertileSlots
Traceback (most recent call last):
  File "G:/codes/tensorflow/models-master/autoencoder/AdditiveGaussianNoiseAutoencoderRunner.py", line 32, in <module>
    scale = 0.01)
  File "G:\codes\tensorflow\models-master\autoencoder\autoencoder_models\DenoisingAutoencoder.py", line 25, in __init__
    self.cost = 0.5 * tf.reduce_sum(tf.pow(tf.sub(self.reconstruction, self.x), 2.0))
AttributeError: module 'tensorflow' has no attribute 'sub'

```
I clean some files on **c:**,   then i run the model zoo's example `models-master/autoencoder/AdditiveGaussianNoiseAutoencoderRunner.py` , unfortunately, it occurs the above error, what's happen?

**Comment by Baschdl** [comment]
Did you remove files related to tensorflow? Is your code correct? 
You maybe wanted to use the method `tf. subtract` instead of `tf.sub`[https://www.tensorflow.org/api_docs/python/tf/subtract]( https://www.tensorflow.org/api_docs/python/tf/subtract)

**Comment by shiyemin** [comment]
Release Note of V1.0.0:

tf.mul, tf.sub and tf.neg are deprecated in favor of tf.multiply, tf.subtract and tf.negative.

**Comment by aselle** [comment]
Also, if you have code that is failing like this, you can try to upgrade the code using the upgrade script we provide to change calls to the 1.0 versions
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/compatibility
Fix the python traceback first and then see if your other errors remain. Thanks!

**Comment by linrio** [comment]
@Baschdl  @shiyemin Thanks! I replaced the `tf.sub` to `tf.subtract`, the error disappeared.

**Comment by linrio** [comment]
@aselle However, I utilized your method to upgrade script, the bug still occurs:
```
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "BestSplits" device_type: "CPU"') for unknown op: BestSplits
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "CountExtremelyRandomStats" device_type: "CPU"') for unknown op: CountExtremelyRandomStats
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "FinishedNodes" device_type: "CPU"') for unknown op: FinishedNodes
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "GrowTree" device_type: "CPU"') for unknown op: GrowTree
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ReinterpretStringToFloat" device_type: "CPU"') for unknown op: ReinterpretStringToFloat
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "SampleInputs" device_type: "CPU"') for unknown op: SampleInputs
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ScatterAddNdim" device_type: "CPU"') for unknown op: ScatterAddNdim
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNInsert" device_type: "CPU"') for unknown op: TopNInsert
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNRemove" device_type: "CPU"') for unknown op: TopNRemove
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TreePredictions" device_type: "CPU"') for unknown op: TreePredictions
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "UpdateFertileSlots" device_type: "CPU"') for unknown op: UpdateFertileSlots
```

**Comment by aselle** [comment]
@mrry, is there a list of known ops that aren't available in windows?

**Comment by mrry** [comment]
The [CMake readme](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/README.md) has a list of missing ops, but I don't know if people have been keeping it up-to-date as they add new ops  (though it looks promising that the [list of files excluded from the Windows build](https://github.com/tensorflow/tensorflow/blob/43c71a03380d8de18202cc399563814b2f438cd2/tensorflow/contrib/cmake/tf_core_kernels.cmake#L93) only includes quantization-related ops).

Contrib support is spotty, but all of the `tensor_forest` ops in the error message that [@linrio quoted](https://github.com/tensorflow/tensorflow/issues/7582#issuecomment-281032555) have been available at HEAD for some time now.

**Comment by aselle** [comment]
@linrio, could you compile from source and see if that solves your issues. Otherwise, you will need to wait for the next release which resolves those ops being missing.

**Comment by mrry** [comment]
@linrio Or use a nightly build, which should also have these ops built in.

Note however that if you aren't using `tf.contrib.tensor_forest`, you can safely ignore these error messages.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
