### ISSUE TITLE
Virtualenv setup returns ImportError

### ISSUE THREAD

**Issue by s-lee** [tensorflow/tensorflow#7591]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
http://stackoverflow.com/questions/42274018/virtualenv-setup-returns-importerror?noredirect=1#comment71721085_42274018

### Environment info
Operating System: OS X El Capitan 10.11.5

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
I am trying to install tensorflow with virtualenv, but I get the following error when I run "virtualenv --system-site-packages tensorflow". I am currently working this on macOS with python3.5.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "~/tensorflow/lib/python3.5/tempfile.py", line 45, in <module>
    from random import Random as _Random
ImportError: cannot import name 'Random'
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/virtualenv", line 11, in <module>
sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/virtualenv.py", line 713, in main
symlink=options.symlink)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/virtualenv.py", line 945, in create_environment
download=download,
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/virtualenv.py", line 901, in install_wheel
call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/virtualenv.py", line 797, in call_subprocess
% (cmd_desc, proc.returncode))
OSError: Command ~/tensorflow/bin/python3.5 - setuptools pip wheel failed with error code 1

**Comment by aselle** [comment]
Maybe try a different directory as your virtualenv dir i.e.
```
virtualenv --system-site-packages ~/foo
```
maybe you have some already existing tensorflow dir that is conflicting.
