### ISSUE TITLE
Code error when feature name has multiple `_`

### ISSUE THREAD

**Issue by jinqishen0725** [tensorflow/tensorflow#75996]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tf 2.17.0

### Custom code

Yes

### OS platform and distribution

5.15.149-99.162.amzn2.x86_64

### Python version

Python 3.10.14

### Current behavior?

Expect there shouldn't be errors just by changing feature name. 

### Standalone code to reproduce the issue
This is a code sample that will work normally

```
import tensorflow as tf
from tensorflow.keras.layers import Input, Dense, Concatenate
from tensorflow.keras import Model

import pandas as pd
import numpy as np

df = pd.DataFrame()
numeric_feature_name = 'a' * 27
categorical_feature_name = 'b' * 11
df[numeric_feature_name] = range(1000)
df[categorical_feature_name] = 'a'
df['label'] = 1

numeric_feature_layer = tf.keras.Input(shape=(1,), name=numeric_feature_name, dtype='float32')
categorical_feature_layer = tf.keras.Input(shape=(1,), name=categorical_feature_name, dtype="string")
encoding_layer = get_category_encoding_layer(vocab=['a'])
encoded_categorical_feature = encoding_layer(categorical_feature_layer)

all_inputs = [numeric_feature_layer, categorical_feature_layer]
encoded_features = [numeric_feature_layer, encoded_categorical_feature]
concat_features = Concatenate()(encoded_features)
output = Dense(units=1, activation='sigmoid')(concat_features)
model = Model(inputs=all_inputs, outputs=output)

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

dataframe_x = df[[numeric_feature_name, categorical_feature_name]]
dataframe_y = df['label']
df2 = ((dict(dataframe_x), dataframe_y))
ds = tf.data.Dataset.from_tensor_slices(df2)
ds = ds.batch(32)
ds_train = ds

model.fit(
    ds_train,
    epochs=10,
    batch_size=300,
    verbose=1
)
```

However, if I change the feature name, the same code will throw error

```
df = pd.DataFrame()
## Just change the feature name here
numeric_feature_name = 'a_b_c_d_e_f_g' 
categorical_feature_name = 'a_b_c_d_e_f'
df[numeric_feature_name] = range(1000)
df[categorical_feature_name] = 'a'
df['label'] = 1

numeric_feature_layer = tf.keras.Input(shape=(1,), name=numeric_feature_name, dtype='float32')
categorical_feature_layer = tf.keras.Input(shape=(1,), name=categorical_feature_name, dtype="string")
encoding_layer = get_category_encoding_layer(vocab=['a'])
encoded_categorical_feature = encoding_layer(categorical_feature_layer)

all_inputs = [numeric_feature_layer, categorical_feature_layer]
encoded_features = [numeric_feature_layer, encoded_categorical_feature]
concat_features = Concatenate()(encoded_features)
output = Dense(units=1, activation='sigmoid')(concat_features)
model = Model(inputs=all_inputs, outputs=output)

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

dataframe_x = df[[numeric_feature_name, categorical_feature_name]]
dataframe_y = df['label']
df2 = ((dict(dataframe_x), dataframe_y))
ds = tf.data.Dataset.from_tensor_slices(df2)
ds = ds.batch(32)
ds_train = ds

model.fit(
    ds_train,
    epochs=10,
    batch_size=300,
    verbose=1
)
```

We have tested that this error is on 2.17.0 and if we are using 2.15 tensorflow, both codes will run smoothly.
```


### Relevant log output

```shell
Epoch 1/10
2024-09-18 05:28:05.240962: W tensorflow/core/framework/op_kernel.cc:1817] OP_REQUIRES failed at cast_op.cc:122 : UNIMPLEMENTED: Cast string to float is not supported
---------------------------------------------------------------------------
UnimplementedError                        Traceback (most recent call last)
Cell In[14], line 8
      5 ds = ds.batch(32)
      6 ds_train = ds
----> 8 model.fit(
      9     ds_train,
     10     epochs=10,
     11     batch_size=300,
     12     verbose=1
     13 )

File ~/.airconda-environments/production--payments--tensorflow--ray_tf215--v0.0.1/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py:122, in filter_traceback.<locals>.error_handler(*args, **kwargs)
    119     filtered_tb = _process_traceback_frames(e.__traceback__)
    120     # To get the full stack trace, call:
    121     # `keras.config.disable_traceback_filtering()`
--> 122     raise e.with_traceback(filtered_tb) from None
    123 finally:
    124     del filtered_tb

File ~/.airconda-environments/production--payments--tensorflow--ray_tf215--v0.0.1/lib/python3.10/site-packages/tensorflow/python/eager/execute.py:53, in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     51 try:
     52   ctx.ensure_initialized()
---> 53   tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     54                                       inputs, attrs, num_outputs)
     55 except core._NotOkStatusException as e:
     56   if name is not None:

UnimplementedError: Graph execution error:

Detected at node functional_5_1/Cast defined at (most recent call last):
  File "/home/jinqi_shen/.airconda-environments/production--payments--tensorflow--ray_tf215--v0.0.1/lib/python3.10/runpy.py", line 196, in _run_module_as_main

  File "/home/jinqi_shen/.airconda-environments/production--payments--tensorflow--ray_tf215--v0.0.1/lib/python3.10/runpy.py", line 86, in _run_code

  File "/home/jinqi_shen/.local/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>

  File "/home/jinqi_shen/.local/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance

  File "/home/jinqi_shen/.local/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 739, in start

  File "/home/jinqi_shen/.local/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 205, in start

  File "/home/jinqi_shen/.airconda-environments/production--payments--tensorflow--ray_tf215--v0.0.1/lib/python3.10/asyncio/base_events.py", line 603, in run_forever

  File "/home/jinqi_shen/.airconda-environments/production--payments--tensorflow--ray_tf215--v0.0.1/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once

  File "/home/jinqi_shen/.airconda-environments/production--payments--tensorflow--ray_tf215--v0.0.1/lib/python3.10/asyncio/events.py", line 80, in _run

  File "/home/jinqi_shen/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue

  File "/home/jinqi_shen/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 534, in process_one

  File "/home/jinqi_shen/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell

  File "/home/jinqi_shen/.local/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 362, in execute_request

  File "/home/jinqi_shen/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 778, in execute_request

  File "/home/jinqi_shen/.local/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 449, in do_execute

  File "/home/jinqi_shen/.local/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 549, in run_cell

  File "/home/jinqi_shen/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell

  File "/home/jinqi_shen/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell

  File "/home/jinqi_shen/.local/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner

  File "/home/jinqi_shen/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async

  File "/home/jinqi_shen/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes

  File "/home/jinqi_shen/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code

  File "/tmp/ipykernel_37779/4021243845.py", line 8, in <module>

  File "/home/jinqi_shen/.airconda-environments/production--payments--tensorflow--ray_tf215--v0.0.1/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/home/jinqi_shen/.airconda-environments/production--payments--tensorflow--ray_tf215--v0.0.1/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py", line 320, in fit

  File "/home/jinqi_shen/.airconda-environments/production--payments--tensorflow--ray_tf215--v0.0.1/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py", line 121, in one_step_on_iterator

  File "/home/jinqi_shen/.airconda-environments/production--payments--tensorflow--ray_tf215--v0.0.1/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py", line 108, in one_step_on_data

  File "/home/jinqi_shen/.airconda-environments/production--payments--tensorflow--ray_tf215--v0.0.1/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py", line 51, in train_step

  File "/home/jinqi_shen/.airconda-environments/production--payments--tensorflow--ray_tf215--v0.0.1/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/home/jinqi_shen/.airconda-environments/production--payments--tensorflow--ray_tf215--v0.0.1/lib/python3.10/site-packages/keras/src/layers/layer.py", line 901, in __call__

  File "/home/jinqi_shen/.airconda-environments/production--payments--tensorflow--ray_tf215--v0.0.1/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/home/jinqi_shen/.airconda-environments/production--payments--tensorflow--ray_tf215--v0.0.1/lib/python3.10/site-packages/keras/src/ops/operation.py", line 46, in __call__

  File "/home/jinqi_shen/.airconda-environments/production--payments--tensorflow--ray_tf215--v0.0.1/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 156, in error_handler

  File "/home/jinqi_shen/.airconda-environments/production--payments--tensorflow--ray_tf215--v0.0.1/lib/python3.10/site-packages/keras/src/models/functional.py", line 167, in call

  File "/home/jinqi_shen/.airconda-environments/production--payments--tensorflow--ray_tf215--v0.0.1/lib/python3.10/site-packages/keras/src/models/functional.py", line 258, in _standardize_inputs

  File "/home/jinqi_shen/.airconda-environments/production--payments--tensorflow--ray_tf215--v0.0.1/lib/python3.10/site-packages/keras/src/models/functional.py", line 218, in _convert_inputs_to_tensors

  File "/home/jinqi_shen/.airconda-environments/production--payments--tensorflow--ray_tf215--v0.0.1/lib/python3.10/site-packages/keras/src/ops/core.py", line 822, in convert_to_tensor

  File "/home/jinqi_shen/.airconda-environments/production--payments--tensorflow--ray_tf215--v0.0.1/lib/python3.10/site-packages/keras/src/backend/tensorflow/core.py", line 132, in convert_to_tensor

Cast string to float is not supported
	 [[{{node functional_5_1/Cast}}]] [Op:__inference_one_step_on_iterator_6125]
```

**Comment by Venkat6871** [comment]
Hi @jinqishen0725 ,
Apologies for the delay. I tried running your code on Colab using TensorFlow v2.15.0 and v2.17.0 and encountered a different issue. Could you please provide the gist with all the dependencies? This will help us analyze the problem more effectively. Please find the [gist](https://colab.sandbox.google.com/gist/Venkat6871/6febcaaa9c58d4aa6a08d293feaf9526/75996_tf-2-15-0-2-17-0-v.ipynb) I created here for reference.

Thank you!

**Comment by jinqishen0725** [comment]
Oh, my bad that forgot to provide that function for embedding layer. It is a short one. 
```
def get_category_encoding_layer(vocab):
    index = tf.keras.layers.StringLookup(vocabulary=vocab, mask_token=None, oov_token="[UNK]")
    encoder = tf.keras.layers.CategoryEncoding(num_tokens=len(vocab) + 1, output_mode="one_hot")
    return lambda feature: encoder(index(feature))
```

I also created the gist like you mentioned. Hopefully that will be helpful. 
https://colab.research.google.com/drive/1UKvcfstKAgtJK3l7z6f2-rb2A33KDDzF?usp=sharing

**Comment by Venkat6871** [comment]
Hi **@jinqishen0725** ,
Thank you for the provided code snippet. I tried running your code on Colab using TensorFlow 2.17.0 and the nightly version, and I am facing the same issue. I also tried it on TensorFlow 2.15.0, but it is not working there either. I am providing the [gist](https://colab.sandbox.google.com/gist/Venkat6871/7d3477c2e7a318bf88dba93a0f244fe2/75996_tf-2-15-0-2-17-0-nightly-v.ipynb) for reference.
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues) as this issue is more related to keras

Thank you!

**Comment by jinqishen0725** [comment]
Hi @Venkat6871, I am very sure it can be run under tensorflow 2.15.0. Please see the following [gist](https://colab.research.google.com/drive/1qM_j_ifGl48APNuWFkHvZjNp1UT1COy1?usp=sharing) that only include 2.15.0. For your error in the gist, I actually cannot reproduce ...

**Comment by Venkat6871** [comment]
Hi **@jinqishen0725** ,
I tried to run your code on Colab using TF v2.15.0 and faced the same issue. Please find the [gist](https://colab.sandbox.google.com/gist/Venkat6871/6eb1252802308fb3a0e2c5a78eff4463/75996_tf-2-15-0.ipynb) here for the reference. 
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues) as this issue is more related to keras
Thank you!

**Comment by jinqishen0725** [comment]
@Venkat6871 just to confirm, so in your new gist, looks like you did run both codes successfully with 2.15.0, but the same code failed when you upgrade to 2.17.0, is it correct? I don't see what is the same issue you faced in your new gist with 2.15.0. 
<img width="780" alt="image" src="https://github.com/user-attachments/assets/53238bdb-6af3-48ad-bf80-339a74591e26">

**Comment by jinqishen0725** [comment]
Thanks @Venkat6871 for confirming on this! In this case, this should be more likely to be a tensorflow package issue I suppose, is it correct?

**Comment by Venkat6871** [comment]
Hi **@jinqishen0725** ,
Though it is a TensorFlow package, the APIs are related to Keras. Moreover, TensorFlow 2.17.0 includes Keras 3.0, which might be the reason for the error or failure. Therefore, I suggest raising the issue with the Keras team or in the Keras [repository](https://github.com/keras-team/keras/issues) for a quicker resolution.
Thank you!

**Comment by jinqishen0725** [comment]
@Venkat6871 So have you checked the issue further? What is the reason you think it is a Keras issue? If you just don't want to look further, can you loop in another person for checking? I just cannot imagine why letting someone looking at it is so hard ...

**Comment by Kayyuri** [comment]
Hi @jinqishen0725,
Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

I tried to reproduce the provided code with the latest` tf-nightly` version and able to run this code without any issues. I am attaching the [gist](https://colab.sandbox.google.com/gist/Kayyuri/1e60e95429fdb5535c24028fa0198e8d/75996.ipynb) file for the reference.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.
Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
