### ISSUE TITLE
Error importing TensorFlow in Jupyter Notebook

### ISSUE THREAD

**Issue by aakaashjois** [tensorflow/tensorflow#7602]
I am unable to import TensorFlow in Jupyter Notebook. I have attached the error log at the end of the post. I am able to import the CPU Version of the TensorFlow with no issue. I am also able to import TensorFlow in Python Console launched from Terminal. The path to python executable is same in both Console and Jupyter Notebook (`sys.executable` gave the output as `/Users/Aakaash/miniconda3/bin/python` for both).

## EDIT:
I installed [JupyterLab](https://github.com/jupyterlab/jupyterlab) and to my surprise, TensorFlow imports with no errors when I open the ipynb file in JupyterLab. The problem arises only when I open the ipynb file with Jupyter Notebook.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
I posted a question on StackOverflow and I was told to file an issue on GitHub.

http://stackoverflow.com/questions/42273323/error-importing-tensorflow-gpu-in-jupyter-notebook?noredirect=1#comment71720944_42273323

### Environment info
Operating System: MacOS Sierra 10.12.3

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
````
lrwxr-xr-x  1 root     wheel        33 Feb 16 15:34 /usr/local/cuda/lib/libcuda.1.dylib -> /usr/local/cuda/lib/libcuda.dylib
-rwxr-xr-x  1 root     wheel     13504 Jan 25 01:28 /usr/local/cuda/lib/libcuda.dylib
lrwxr-xr-x@ 1 root     wheel        45 Nov  4 00:10 /usr/local/cuda/lib/libcudadevrt.a -> /Developer/NVIDIA/CUDA-8.0/lib/libcudadevrt.a
lrwxr-xr-x@ 1 root     wheel        50 Nov  4 00:10 /usr/local/cuda/lib/libcudart.8.0.dylib -> /Developer/NVIDIA/CUDA-8.0/lib/libcudart.8.0.dylib
lrwxr-xr-x@ 1 root     wheel        46 Nov  4 00:10 /usr/local/cuda/lib/libcudart.dylib -> /Developer/NVIDIA/CUDA-8.0/lib/libcudart.dylib
lrwxr-xr-x@ 1 root     wheel        49 Nov  4 00:10 /usr/local/cuda/lib/libcudart_static.a -> /Developer/NVIDIA/CUDA-8.0/lib/libcudart_static.a
-rwxr-xr-x@ 1 Aakaash  staff  82210088 Nov  7 13:28 /usr/local/cuda/lib/libcudnn.5.dylib
lrwxr-xr-x@ 1 Aakaash  staff        16 Nov  7 13:49 /usr/local/cuda/lib/libcudnn.dylib -> libcudnn.5.dylib
-rw-r--r--@ 1 Aakaash  staff  66197088 Nov  7 13:28 /usr/local/cuda/lib/libcudnn_static.a
````
If installed from binary pip package, provide:

1. A link to the pip package you installed:
I used `pip install tensorflow-gpu`
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`:
````
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.8.0.dylib locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.5.dylib locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.8.0.dylib locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.1.dylib locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.8.0.dylib locally
1.0.0
````

### Logs or other output that would be helpful
````
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/Users/Aakaash/miniconda3/lib/python3.5/site-packages/tensorflow/python/__init__.py in <module>()
     60     sys.setdlopenflags(_default_dlopen_flags | ctypes.RTLD_GLOBAL)
---> 61     from tensorflow.python import pywrap_tensorflow
     62     sys.setdlopenflags(_default_dlopen_flags)

/Users/Aakaash/miniconda3/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py in <module>()
     27             return _mod
---> 28     _pywrap_tensorflow = swig_import_helper()
     29     del swig_import_helper

/Users/Aakaash/miniconda3/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py in swig_import_helper()
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
     25             finally:

/Users/Aakaash/miniconda3/lib/python3.5/imp.py in load_module(name, file, filename, details)
    241         else:
--> 242             return load_dynamic(name, filename, file)
    243     elif type_ == PKG_DIRECTORY:

/Users/Aakaash/miniconda3/lib/python3.5/imp.py in load_dynamic(name, path, file)
    341             name=name, loader=loader, origin=path)
--> 342         return _load(spec)
    343 

ImportError: dlopen(/Users/Aakaash/miniconda3/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): Library not loaded: @rpath/libcudart.8.0.dylib
  Referenced from: /Users/Aakaash/miniconda3/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so
  Reason: image not found

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-a649b509054f> in <module>()
----> 1 import tensorflow

/Users/Aakaash/miniconda3/lib/python3.5/site-packages/tensorflow/__init__.py in <module>()
     22 
     23 # pylint: disable=wildcard-import
---> 24 from tensorflow.python import *
     25 # pylint: enable=wildcard-import
     26 

/Users/Aakaash/miniconda3/lib/python3.5/site-packages/tensorflow/python/__init__.py in <module>()
     70 for some common reasons and solutions.  Include the entire stack trace
     71 above this error message when asking for help.""" % traceback.format_exc()
---> 72   raise ImportError(msg)
     73 
     74 # Protocol buffers

ImportError: Traceback (most recent call last):
  File "/Users/Aakaash/miniconda3/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/Aakaash/miniconda3/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/Users/Aakaash/miniconda3/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/Users/Aakaash/miniconda3/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/Aakaash/miniconda3/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/Aakaash/miniconda3/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): Library not loaded: @rpath/libcudart.8.0.dylib
  Referenced from: /Users/Aakaash/miniconda3/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so
  Reason: image not found


Failed to load the native TensorFlow runtime.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
````

**Comment by carlthome** [comment]
Could you run `env | grep LD_LIBRARY_PATH` in your terminal and share the output?

**Comment by aakaashjois** [comment]
@carlthome It does not return any output when I run that in the terminal.

**Comment by carlthome** [comment]
Then TensorFlow is unable to find your CUDA install, most likely. Try adding
```
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib64:/usr/local/cuda/lib"
```
to ~/.bashrc (assuming you're using Ubuntu or Debian), and open a new terminal and try `python -c 'import tensorflow'` and see if it finds CUDA.

Semi-related: https://github.com/tensorflow/tensorflow/issues/2626

**Comment by aakaashjois** [comment]
I am using Mac OS and it worked. I had done `export DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:/usr/local/cuda/lib$DYLD_LIBRARY_PATH` following the CuDNN Install Guide provided by Nvidia. I guess that does not work.

Thank you so much for the help!

**Comment by carlthome** [comment]
Cool. Have fun building computational graphs! :smile:  Don't forget to close the issue.

**Comment by aakaashjois** [comment]
Thank you! Closing the issue now.
