### ISSUE TITLE
iris_monitors.py broken in release r1.0 due to inacurate MetricSpec namespace

### ISSUE THREAD

**Issue by chidochipotle** [tensorflow/tensorflow#7637]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

`tf.contrib.learn.metric_spec.MetricSpec` should be changed to `MetricSpec` in iris_monitors.py in release 1.0.0

No need to import MetricSpec in iris_monitors.py it's already imported on line 24 in commit [fa4ba830f437fdb9dc1085b4d68a3bab41a16e20](https://github.com/tensorflow/tensorflow/blob/fa4ba830f437fdb9dc1085b4d68a3bab41a16e20/tensorflow/examples/tutorials/monitors/iris_monitors.py):
`tensorflow.contrib.learn.python.learn.metric_spec import MetricSpec`

### Environment info
Operating System:
>tensorflow/tensorflow/examples/tutorials/monitors$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
>tensorflow/tensorflow/examples/tutorials/monitors$ uname -a
Linux panchito 4.4.0-62-generic-tuxonice #83~ppa1-Ubuntu SMP Thu Feb 2 23:17:45 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
```
repositories/tensorflow/tensorflow/examples/tutorials/monitors$ python -c "import tensorflow; print(tensorflow.__version__)"
1.0.0
```
If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

repositories/tensorflow/tensorflow/examples/tutorials/monitors$ python iris_monitors.py
Traceback (most recent call last):
  File "iris_monitors.py", line 116, in <module>
    tf.app.run()
  File "/home/chidochipotle/anaconda3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "iris_monitors.py", line 42, in main
    tf.contrib.learn.metric_spec.MetricSpec(
AttributeError: module 'tensorflow.contrib.learn' has no attribute 'metric_spec'

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by chidochipotle** [comment]
Needs many more changes to work, iris_monitors.py seems to be is totally broken with r1.0 I am just too newbie to understand what's wrong ...

After fixing a couple of more inaccurate imports I get lots of warnings when I run it:

```
dkor@panchito:~/repositories/tensorflow/tensorflow/examples/tutorials/monitors$ python iris_monitors.py 
WARNING:tensorflow:From /home/dkor/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/monitors.py:322: BaseMonitor.__init__ (from tensorflow.contrib.learn.python.learn.monitors) is deprecated and will be removed after 2016-12-05.
Instructions for updating:
Monitors are deprecated. Please use tf.train.SessionRunHook.
WARNING:tensorflow:From /home/dkor/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/monitors.py:322: BaseMonitor.__init__ (from tensorflow.contrib.learn.python.learn.monitors) is deprecated and will be removed after 2016-12-05.
Instructions for updating:
Monitors are deprecated. Please use tf.train.SessionRunHook.
INFO:tensorflow:Using config: {'_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fdc67b414e0>, '_is_chief': True, '_tf_random_seed': None, '_task_type': None, '_keep_checkpoint_max': 5, '_master': '', '_keep_checkpoint_every_n_hours': 10000, '_save_summary_steps': 100, '_environment': 'local', '_save_checkpoints_secs': 1, '_num_ps_replicas': 0, '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1
}
, '_save_checkpoints_steps': None, '_task_id': 0, '_evaluation_master': ''}
/home/dkor/anaconda3/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py:247: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  equality = a == b
WARNING:tensorflow:From iris_monitors.py:104: calling BaseEstimator.fit (from tensorflow.contrib.learn.python.learn.estimators.estimator) with x is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:From iris_monitors.py:104: calling BaseEstimator.fit (from tensorflow.contrib.learn.python.learn.estimators.estimator) with y is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
WARNING:tensorflow:From /home/dkor/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/head.py:1362: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
INFO:tensorflow:Create CheckpointSaverHook.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
INFO:tensorflow:Saving checkpoints for 851 into /tmp/iris_model/model.ckpt.
INFO:tensorflow:loss = 0.0496295, step = 851
WARNING:tensorflow:From /home/dkor/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/monitors.py:712: calling BaseEstimator.evaluate (from tensorflow.contrib.learn.python.learn.estimators.estimator) with x is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:From /home/dkor/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/monitors.py:712: calling BaseEstimator.evaluate (from tensorflow.contrib.learn.python.learn.estimators.estimator) with y is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
WARNING:tensorflow:From /home/dkor/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/head.py:1362: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
INFO:tensorflow:Starting evaluation at 2017-02-17-23:21:20
INFO:tensorflow:Finished evaluation at 2017-02-17-23:21:21
INFO:tensorflow:Saving dict for global step 851: accuracy = 0.966667, auc = 0.998333, global_step = 851, loss = 0.0598002, precision = 1.0, recall = 1.0
WARNING:tensorflow:Skipping summary for global_step, must be a float or np.float32.
INFO:tensorflow:Validation (step 851): precision = 1.0, auc = 0.998333, loss = 0.0598002, recall = 1.0, accuracy = 0.966667, global_step = 851
INFO:tensorflow:Saving checkpoints for 852 into /tmp/iris_model/model.ckpt.
WARNING:tensorflow:From /home/dkor/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/monitors.py:712: calling BaseEstimator.evaluate (from tensorflow.contrib.learn.python.learn.estimators.estimator) with x is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:From /home/dkor/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/monitors.py:712: calling BaseEstimator.evaluate (from tensorflow.contrib.learn.python.learn.estimators.estimator) with y is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
WARNING:tensorflow:From /home/dkor/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/head.py:1362: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
INFO:tensorflow:Starting evaluation at 2017-02-17-23:21:23
INFO:tensorflow:Finished evaluation at 2017-02-17-23:21:23
INFO:tensorflow:Saving dict for global step 852: accuracy = 0.966667, auc = 0.998333, global_step = 852, loss = 0.0556784, precision = 1.0, recall = 1.0
WARNING:tensorflow:Skipping summary for global_step, must be a float or np.float32.
INFO:tensorflow:Validation (step 901): precision = 1.0, auc = 0.998333, loss = 0.0556784, recall = 1.0, accuracy = 0.966667, global_step = 852
INFO:tensorflow:Saving checkpoints for 902 into /tmp/iris_model/model.ckpt.
INFO:tensorflow:global_step/sec: 23.6534
INFO:tensorflow:loss = 0.0484522, step = 951
WARNING:tensorflow:From /home/dkor/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/monitors.py:712: calling BaseEstimator.evaluate (from tensorflow.contrib.learn.python.learn.estimators.estimator) with x is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:From /home/dkor/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/monitors.py:712: calling BaseEstimator.evaluate (from tensorflow.contrib.learn.python.learn.estimators.estimator) with y is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
WARNING:tensorflow:From /home/dkor/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/head.py:1362: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
INFO:tensorflow:Starting evaluation at 2017-02-17-23:21:24
INFO:tensorflow:Finished evaluation at 2017-02-17-23:21:25
INFO:tensorflow:Saving dict for global step 902: accuracy = 0.966667, auc = 0.998333, global_step = 902, loss = 0.0556355, precision = 1.0, recall = 1.0
WARNING:tensorflow:Skipping summary for global_step, must be a float or np.float32.
INFO:tensorflow:Validation (step 951): precision = 1.0, auc = 0.998333, loss = 0.0556355, recall = 1.0, accuracy = 0.966667, global_step = 902
INFO:tensorflow:Saving checkpoints for 952 into /tmp/iris_model/model.ckpt.
WARNING:tensorflow:From /home/dkor/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/monitors.py:712: calling BaseEstimator.evaluate (from tensorflow.contrib.learn.python.learn.estimators.estimator) with x is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:From /home/dkor/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/monitors.py:712: calling BaseEstimator.evaluate (from tensorflow.contrib.learn.python.learn.estimators.estimator) with y is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
WARNING:tensorflow:From /home/dkor/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/head.py:1362: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
INFO:tensorflow:Starting evaluation at 2017-02-17-23:21:26
INFO:tensorflow:Finished evaluation at 2017-02-17-23:21:26
INFO:tensorflow:Saving dict for global step 952: accuracy = 0.966667, auc = 0.998333, global_step = 952, loss = 0.0556713, precision = 1.0, recall = 1.0
WARNING:tensorflow:Skipping summary for global_step, must be a float or np.float32.
INFO:tensorflow:Validation (step 1001): precision = 1.0, auc = 0.998333, loss = 0.0556713, recall = 1.0, accuracy = 0.966667, global_step = 952
INFO:tensorflow:Saving checkpoints for 1002 into /tmp/iris_model/model.ckpt.
INFO:tensorflow:global_step/sec: 31.7257
INFO:tensorflow:loss = 0.0475382, step = 1051
WARNING:tensorflow:From /home/dkor/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/monitors.py:712: calling BaseEstimator.evaluate (from tensorflow.contrib.learn.python.learn.estimators.estimator) with x is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:From /home/dkor/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/monitors.py:712: calling BaseEstimator.evaluate (from tensorflow.contrib.learn.python.learn.estimators.estimator) with y is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
WARNING:tensorflow:From /home/dkor/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/head.py:1362: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
INFO:tensorflow:Starting evaluation at 2017-02-17-23:21:27
INFO:tensorflow:Finished evaluation at 2017-02-17-23:21:28
INFO:tensorflow:Saving dict for global step 1002: accuracy = 0.966667, auc = 0.998333, global_step = 1002, loss = 0.0556784, precision = 1.0, recall = 1.0
WARNING:tensorflow:Skipping summary for global_step, must be a float or np.float32.
INFO:tensorflow:Validation (step 1051): precision = 1.0, auc = 0.998333, loss = 0.0556784, recall = 1.0, accuracy = 0.966667, global_step = 1002
INFO:tensorflow:Saving checkpoints for 1052 into /tmp/iris_model/model.ckpt.
WARNING:tensorflow:From /home/dkor/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/monitors.py:712: calling BaseEstimator.evaluate (from tensorflow.contrib.learn.python.learn.estimators.estimator) with x is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:From /home/dkor/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/monitors.py:712: calling BaseEstimator.evaluate (from tensorflow.contrib.learn.python.learn.estimators.estimator) with y is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
WARNING:tensorflow:From /home/dkor/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/head.py:1362: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
INFO:tensorflow:Starting evaluation at 2017-02-17-23:21:29
INFO:tensorflow:Finished evaluation at 2017-02-17-23:21:29
INFO:tensorflow:Saving dict for global step 1052: accuracy = 0.966667, auc = 0.998333, global_step = 1052, loss = 0.0557572, precision = 1.0, recall = 1.0
WARNING:tensorflow:Skipping summary for global_step, must be a float or np.float32.
INFO:tensorflow:Validation (step 1101): precision = 1.0, auc = 0.998333, loss = 0.0557572, recall = 1.0, accuracy = 0.966667, global_step = 1052
INFO:tensorflow:Saving checkpoints for 1102 into /tmp/iris_model/model.ckpt.
INFO:tensorflow:global_step/sec: 32.9999
INFO:tensorflow:loss = 0.0466149, step = 1151
WARNING:tensorflow:From /home/dkor/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/monitors.py:712: calling BaseEstimator.evaluate (from tensorflow.contrib.learn.python.learn.estimators.estimator) with x is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:From /home/dkor/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/monitors.py:712: calling BaseEstimator.evaluate (from tensorflow.contrib.learn.python.learn.estimators.estimator) with y is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
WARNING:tensorflow:From /home/dkor/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/head.py:1362: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
INFO:tensorflow:Starting evaluation at 2017-02-17-23:21:30
INFO:tensorflow:Finished evaluation at 2017-02-17-23:21:31
INFO:tensorflow:Saving dict for global step 1102: accuracy = 0.966667, auc = 0.998333, global_step = 1102, loss = 0.0559047, precision = 1.0, recall = 1.0
WARNING:tensorflow:Skipping summary for global_step, must be a float or np.float32.
INFO:tensorflow:Validation (step 1151): precision = 1.0, auc = 0.998333, loss = 0.0559047, recall = 1.0, accuracy = 0.966667, global_step = 1102
INFO:tensorflow:Stopping. Best step: 951 with loss = 0.05563554912805557.
INFO:tensorflow:Saving checkpoints for 1151 into /tmp/iris_model/model.ckpt.
INFO:tensorflow:Loss for final step: 0.0466149.
WARNING:tensorflow:From iris_monitors.py:108: calling BaseEstimator.evaluate (from tensorflow.contrib.learn.python.learn.estimators.estimator) with x is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:From iris_monitors.py:108: calling BaseEstimator.evaluate (from tensorflow.contrib.learn.python.learn.estimators.estimator) with y is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
WARNING:tensorflow:From /home/dkor/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/head.py:1362: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
INFO:tensorflow:Starting evaluation at 2017-02-17-23:21:32
INFO:tensorflow:Finished evaluation at 2017-02-17-23:21:32
INFO:tensorflow:Saving dict for global step 1151: accuracy = 0.966667, auc = 0.998333, global_step = 1151, loss = 0.0619039
WARNING:tensorflow:Skipping summary for global_step, must be a float or np.float32.
Accuracy: 0.966667
WARNING:tensorflow:From /home/dkor/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py:374: calling BaseEstimator.predict (from tensorflow.contrib.learn.python.learn.estimators.estimator) with x is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
Predictions: [1, 2]
dkor@panchito:~/repositories/tensorflow/tensorflow/examples/tutorials/monitors$ 


```

**Comment by jheffez** [comment]
I'm getting the errors using the latest nightly TF build (3/3/2017) with the Iris dataset. I see this issue as closed. So how was it fixed?
using python 3.5.1 on Windows, no gpu.
code is the same as the example in https://www.tensorflow.org/get_started/tflearn

Errors:

C:\Users\Jake\py\my_env\lib\site-packages\tensorflow\python\util\deprecation.py:248: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  equality = a == b
WARNING:tensorflow:From C:\Users\Jake\py\files\Iris\test1.py:32: calling BaseEstimator.fit (from tensorflow.contrib.learn.python.learn.estimators.estimator) with y is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:From C:\Users\Jake\py\files\Iris\test1.py:32: calling BaseEstimator.fit (from tensorflow.contrib.learn.python.learn.estimators.estimator) with x is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:From C:\Users\Jake\py\my_env\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\head.py:527: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
2017-03-03 09:33:56.774205: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE instructions, but these are available on your machine and could speed up CPU computations.
2017-03-03 09:33:56.774305: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE2 instructions, but these are available on your machine and could speed up CPU computations.
2017-03-03 09:33:56.775876: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
2017-03-03 09:33:56.776302: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-03-03 09:33:56.776872: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-03-03 09:33:56.777305: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-03-03 09:33:56.777783: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-03-03 09:33:56.778242: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
WARNING:tensorflow:From C:\Users\Jake\py\my_env\lib\site-packages\tensorflow\python\util\deprecation.py:335: calling DNNClassifier.predict (from tensorflow.contrib.learn.python.learn.estimators.dnn) with outputs=None is deprecated and will be removed after 2017-03-01.
Instructions for updating:
Please switch to predict_classes, or set `outputs` argument.
WARNING:tensorflow:From C:\Users\Jake\py\my_env\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\dnn.py:395: calling BaseEstimator.predict (from tensorflow.contrib.learn.python.learn.estimators.estimator) with x is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
Predictions: [1, 2, 0]

**Comment by terrytangyuan** [comment]
Use learn.MetricSpec instead

**Comment by jheffez** [comment]
I'm new to this and using the tensorflow site as a learning resource. If recent code changes break the learn example than for the sake of clear/concise learning it would require updating the tensorflow site with the corrected code. Specifically: https://www.tensorflow.org/get_started/tflearn
