### ISSUE TITLE
ImportError: No module named 'tensorflow.contrib.distributions.python.ops.bijectors'

### ISSUE THREAD

**Issue by robbiewu007** [tensorflow/tensorflow#7640]
I want to run tensorflow 1.0 RC2 on windows 10, but encounter issues #7540, #7500, then follow the suggestion to install Nightly Build version (http://ci.tensorflow.org/view/Nightly/job/nightly-win/DEVICE=cpu,OS=windows/87/artifact/cmake_build/tf_python/dist/tensorflow-1.0.0-cp35-cp35m-win_amd64.whl),  but still encounter the following issue:
=================================
(tensorflow_py35) C:\Work\tensorflow\tensorflow\examples\tutorials\mnist>python mnist_softmax.py
Traceback (most recent call last):
  File "mnist_softmax.py", line 28, in <module>
    from tensorflow.examples.tutorials.mnist import input_data
  File "C:\Miniconda3\envs\tensorflow_py35\lib\site-packages\tensorflow\examples\tutorials\mnist\__init__.py", line 21, in <module>
    from tensorflow.examples.tutorials.mnist import input_data
  File "C:\Miniconda3\envs\tensorflow_py35\lib\site-packages\tensorflow\examples\tutorials\mnist\input_data.py", line 29, in <module>
    from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets
  File "C:\Miniconda3\envs\tensorflow_py35\lib\site-packages\tensorflow\contrib\__init__.py", line 22, in <module>
    from tensorflow.contrib import bayesflow
  File "C:\Miniconda3\envs\tensorflow_py35\lib\site-packages\tensorflow\contrib\bayesflow\__init__.py", line 24, in <module>
    from tensorflow.contrib.bayesflow.python.ops import entropy
  File "C:\Miniconda3\envs\tensorflow_py35\lib\site-packages\tensorflow\contrib\bayesflow\python\ops\entropy.py", line 23, in <module>
    from tensorflow.contrib.bayesflow.python.ops.entropy_impl import *
  File "C:\Miniconda3\envs\tensorflow_py35\lib\site-packages\tensorflow\contrib\bayesflow\python\ops\entropy_impl.py", line 30, in <module>
    from tensorflow.contrib.bayesflow.python.ops import variational_inference
  File "C:\Miniconda3\envs\tensorflow_py35\lib\site-packages\tensorflow\contrib\bayesflow\python\ops\variational_inference.py", line 26, in <module>
    from tensorflow.contrib.bayesflow.python.ops.variational_inference_impl import *
  File "C:\Miniconda3\envs\tensorflow_py35\lib\site-packages\tensorflow\contrib\bayesflow\python\ops\variational_inference_impl.py", line 29, in <module>
    from tensorflow.contrib.bayesflow.python.ops import stochastic_graph as sg
  File "C:\Miniconda3\envs\tensorflow_py35\lib\site-packages\tensorflow\contrib\bayesflow\python\ops\stochastic_graph.py", line 28, in <module>
    from tensorflow.contrib.bayesflow.python.ops import stochastic_tensor
  File "C:\Miniconda3\envs\tensorflow_py35\lib\site-packages\tensorflow\contrib\bayesflow\python\ops\stochastic_tensor.py", line 39, in <module>
    from tensorflow.contrib.distributions.python.ops import distribution
  File "C:\Miniconda3\envs\tensorflow_py35\lib\site-packages\tensorflow\contrib\distributions\__init__.py", line 91, in <module>
    from tensorflow.contrib.distributions.python.ops.conditional_transformed_distribution import *
  File "C:\Miniconda3\envs\tensorflow_py35\lib\site-packages\tensorflow\contrib\distributions\python\ops\conditional_transformed_distribution.py", line 22, in <module>
    from tensorflow.contrib.distributions.python.ops import transformed_distribution
  File "C:\Miniconda3\envs\tensorflow_py35\lib\site-packages\tensorflow\contrib\distributions\python\ops\transformed_distribution.py", line 24, in <module>
    from tensorflow.contrib.distributions.python.ops.bijectors import identity as identity_lib
ImportError: No module named 'tensorflow.contrib.distributions.python.ops.bijectors'

**Comment by aselle** [comment]
Are these problems present if you try TensorFlow 1.0 (newer than RC2)?

**Comment by robbiewu007** [comment]
patch of #7617 fix the issue, the latest master auto-build works fine.
