### ISSUE TITLE
ailed to synchronize the stop event: CUDA_ERROR_UNKNOWN: unknown error

### ISSUE THREAD

**Issue by arun-kumark** [tensorflow/tensorflow#76456]
Hello together,

I am trying to run the new-benchmark AI for my new platform:
https://pypi.org/project/new-ai-benchmark/

My System configuration is as follows:
*  TF Version: 2.17.0
*  Platform: Linux-6.8.0-45-generic-x86_64-with-glibc2.35
*  CPU: 13th Gen Intel(R) Core(TM) i9-13900E
*  CPU RAM: 62 GB
*  GPU/0: NVIDIA L4
*  GPU RAM: 20.3 GB
*  CUDA Version: 12.4
*  CUDA Build: V12.4.131

While executing the program, at any point of time while running, it fails to complete.

2024-09-25 10:02:40.968881: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:1857] failed to synchronize the stop event: CUDA_ERROR_UNKNOWN: unknown error
E0000 00:00:1727251360.968902    4778 gpu_timer.cc:162] INTERNAL: Error destroying CUDA event: CUDA_ERROR_UNKNOWN: unknown error
E0000 00:00:1727251360.968910    4778 gpu_timer.cc:168] INTERNAL: Error destroying CUDA event: CUDA_ERROR_UNKNOWN: unknown error
2024-09-25 10:02:40.969770: I tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc(6053): 'status'
[[{{node resnet_v2_152/block2/unit_8/bottleneck_v2/conv2/Conv2D}}]]
2024-09-25 10:02:40.969784: I tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc(6053): 'status'
[[{{node resnet_v2_152/block2/unit_8/bottleneck_v2/conv2/Conv2D}}]]
[[output/_3]]
2024-09-25 10:02:40.969798: I tensorflow/core/framework/local_rendezvous.cc:423] Local rendezvous recv item cancelled. Key hash: 16128423615390660009
2024-09-25 10:02:40.992816: W tensorflow/compiler/mlir/tools/kernel_gen/tf_gpu_runtime_wrappers.cc:40] 'cuModuleUnload(it.second)' failed with 'CUDA_ERROR_UNKNOWN'

2024-09-25 10:02:40.992867: W tensorflow/compiler/mlir/tools/kernel_gen/tf_gpu_runtime_wrappers.cc:40] 'cuModuleUnload(it.second)' failed with 'CUDA_ERROR_UNKNOWN'

2024-09-25 10:02:40.992874: W tensorflow/compiler/mlir/tools/kernel_gen/tf_gpu_runtime_wrappers.cc:40] 'cuModuleUnload(it.second)' failed with 'CUDA_ERROR_UNKNOWN'

2024-09-25 10:02:40.992880: W tensorflow/compiler/mlir/tools/kernel_gen/tf_gpu_runtime_wrappers.cc:40] 'cuModuleUnload(it.second)' failed with 'CUDA_ERROR_UNKNOWN'

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tensorflow/python/client/session.py", line 1401, in _do_call
    return fn(*args)
  File "/usr/lib/python3/dist-packages/tensorflow/python/client/session.py", line 1384, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "/usr/lib/python3/dist-packages/tensorflow/python/client/session.py", line 1477, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.

Any clue ?

Thank you
Arun

**Comment by Venkat6871** [comment]
Hi **@arun-kumark** ,
Apologies for the delay. There seems to be a version mismatch, please check the version compatibility. I am providing the [documentation](https://www.tensorflow.org/install/source#gpu) for your reference. Could you also please explain the exact steps you followed?
Thank you!

**Comment by arun-kumark** [comment]
Hi Venkat, 
I am setting up the environment on my freshly installed Ubuntu 22.04LTS using the Lambda:
https://lambdalabs.com/blog/nvidia-ngc-tutorial-run-pytorch-docker-container-using-nvidia-container-toolkit-on-ubuntu

This container set up the CUDA, TensorFlow and CuDNN in reliable way.

I prepared two setups, one with the L4 Nvidia GPU card and another on my ZBook with RTX3000 GPU.

On RTX3000 GPU notebook, the things go smooth, and benchmarking test passes.

While running exactly the same scripts, they never completes and break away in the mid.

I am using the following repository to test the Ai benchmarking score:
https://pypi.org/project/new-ai-benchmark/

Do you have further comments to test/share.

Thank you for the document, yes my setup meets the matching installation with Lambda:
_```
<html>
<body>

tensorflow-2.17.0 | 3.9-3.12 | Clang 17.0.6 | Bazel 6.5.0 | 8.9 | 12.3
-- | -- | -- | -- | -- | --



</body>
</html>
```_
thanks 
Arun

**Comment by arun-kumark** [comment]
My Python version is 3.10.12, which comes by default with Ubuntu 22.04LTS. But the same version works well on other notebook.

Kind Regards
Arun

**Comment by Kayyuri** [comment]
Hi,
Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
