### ISSUE TITLE
'NoneType' object has no attribute 'keys' in version 1.0

### ISSUE THREAD

**Issue by essank** [tensorflow/tensorflow#7659]
I was trying to run tensorflow in docker. The command was this:

```
python tensorflow/examples/image_retraining/retrain.py \
--bottleneck_dir=/tf_files/bottlenecks \
--how_many_training_steps 500 \
--model_dir=/tf_files/inception \
--output_graph=/tf_files/retrained_graph.pb \
--output_labels=/tf_files/retrained_labels.txt \
--image_dir /tf_files/flower_photos
```

I put the error I got in the log  

### Environment info
Operating System: OS X

2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`. 
version 1.0

### Logs or other output that would be helpful
```
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
Image directory '/tf_files/flower_photos' not found.
Traceback (most recent call last):
  File "tensorflow/examples/image_retraining/retrain.py", line 1052, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "tensorflow/examples/image_retraining/retrain.py", line 775, in main
    class_count = len(image_lists.keys())
AttributeError: 'NoneType' object has no attribute 'keys'
```

**Comment by microtony** [comment]
`Image directory '/tf_files/flower_photos' not found.`
You don't have the flower_photos directory. Therefore images cannot be loaded resulting in a NoneType.
You can download the images from http://download.tensorflow.org/example_images/flower_photos.tgz

**Comment by aselle** [comment]
@essank, let us know if @microtony's suggestion worked. Thanks @microtony!

**Comment by essank** [comment]
yes the problem was here 
``` Image directory '/tf_files/flower_photos' not found ```
I tried to do this:
```
mkdir tf_files
cd tf_files
curl -O http://download.tensorflow.org/example_images/flower_photos.tgz
tar xzf flower_photos.tgz
```
it's working!

@microtony @aselle thanks guys!

**Comment by constantinembufung** [comment]
not working for me

**Comment by TheCaffeineDev** [comment]
python retrain.py --image_dir flower_photos
