### ISSUE TITLE
TypeError: run() got an unexpected keyword argument 'feedis_dict'

### ISSUE THREAD

**Issue by LewisHorsleyUK** [tensorflow/tensorflow#7694]
I get this error when trying to add the feedis_dict to a self.sess.run command:

`Traceback (most recent call last):
  File "spritegen.py", line 71, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "spritegen.py", line 54, in main
    dcgan.train(FLAGS)
  File "/home/lewis/Documents/Sprite Generator/Sprite-Generator/dcgan.py", line 211, in train
    summary_str = self.sess.run([dis_optim, self.dis_sum],feedis_dict = {self.inputs: batch_images, self.z: batch_z})
TypeError: run() got an unexpected keyword argument 'feedis_dict'
`
Any suggestions as to why feedis_dict is unexpected ? I believe im using tensorflow gpu 1.0.0

**Comment by yaroslavvb** [comment]
This question may be more appropriate for stackoverflow
