### ISSUE TITLE
Custom activation functions cause TensorFlow to crash

### ISSUE THREAD

**Issue by AtticusBeachy** [tensorflow/tensorflow#77048]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.17.0

### Custom code

Yes

### OS platform and distribution

Linux Mint 22

### Python version

3.12.7

### Current behavior?

I expected the code to run. Instead, TensorFlow crashes. 

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
from tensorflow.keras.utils import get_custom_objects
from tensorflow.keras.layers import Activation

def fourier_activation_lambda(freq):
    fn = lambda x : tf.sin(freq*x)
    return(fn)

freq = 1.0
fourier = fourier_activation_lambda(freq)

get_custom_objects()["fourier"] = Activation(fourier)

print(3*"\n")
print(f"After addition: {get_custom_objects()=}")

x_input = tf.keras.Input(shape=[5])
activation = "fourier"
layer_2 = tf.keras.layers.Dense(100, input_shape = [5],
                                activation=activation,
                                )(x_input)

model = tf.keras.Model(inputs=x_input, outputs=layer_2)
model.compile(optimizer='adam', loss='mse')
model.summary()
```

### Relevant log output

```shell
# Output of print statement:
get_custom_objects()={'fourier': <Activation name=activation, built=False>}

# Error message:
Traceback (most recent call last):
  File "/home/orca/Downloads/minimal_tf_err.py", line 20, in <module>
    layer_2 = tf.keras.layers.Dense(100, input_shape = [5],
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/orca/.local/lib/python3.12/site-packages/keras/src/layers/core/dense.py", line 89, in __init__
    self.activation = activations.get(activation)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/orca/.local/lib/python3.12/site-packages/keras/src/activations/__init__.py", line 104, in get
    raise ValueError(
ValueError: Could not interpret activation function identifier: fourier
```

**Comment by tilakrayal** [comment]
@AtticusBeachy,
Looks like this issue is more related to Keras. Could you please raise the request in the Keras-team/keras repo from [here](https://github.com/keras-team/keras/issues) for the quick resolution. Thank you!

**Comment by AtticusBeachy** [comment]
Okay, I have reposted in the [Keras repo](https://github.com/keras-team/keras/issues/20333).
