### ISSUE TITLE
Buzel build error.

### ISSUE THREAD

**Issue by kinDSa** [tensorflow/tensorflow#7766]
Hello,
  I am using TensorFlow Android Camera Demo. I follow step given in README file.

  1) Import andorid project
  2) Install bazel using chocolaty
  3) Edit in workspace file.
 
 While I run bazel build command :
 bazel build -c opt //tensorflow/examples/android:tensorflow_demo

 I getting error that **Couldn't find java at '$(ls -d C:/Program\ Files/Java/jdk* | sort | tail -n 1)/bin/java.exe**'.

My JDK is installed at C:\Program Files (x86)\Java\jdk1.8.0_66\bin . I also set environment variable    JAVA_HOME="$(ls -d C:/Program\ Files/Java/jdk* | sort | tail -n 1)"
BAZEL_SH=c:/tools/msys64/usr/bin/bash.exe

**Comment by andrewharp** [comment]
Unfortunately Bazel doesn't support Android on Windows yet -- see [roadmap](https://bazel.build/roadmap.html).

We're working on a full gradle/cmake/makefile solution that will work on Windows, but until then you can use the [prebuilt libs](https://ci.tensorflow.org/view/Nightly/job/nightly-android/) and just drop libtensorflow_demo.so and libtensorflow_inference.so into your app.

**Comment by kinDSa** [comment]
@andrewharp, As per your suggestion I use prebuilt libs (libtensorflow_demo.so and libtensorflow_inference.so) in jniLibs and comment line related to bazel build in build.gradle.while I run project the and get error 

`No implementation found for long org.tensorflow.contrib.android.RunStats.allocate() (tried Java_org_tensorflow_contrib_android_RunStats_allocate and Java_org_tensorflow_contrib_android_RunStats_allocate__)`

`dlopen("/data/app/org.tensorflow.demo-1/lib/arm/libtensorflow_inference.so", RTLD_LAZY) failed: dlopen failed: "/data/app/org.tensorflow.demo-1/lib/arm/libtensorflow_inference.so" is too small to be an ELF executable: only found 0 bytes`

`  java.lang.RuntimeException: Native TF methods not found; check that the correct native libraries are present and loaded.
                                                                         at org.tensorflow.contrib.android.TensorFlowInferenceInterface.<init>(TensorFlowInferenceInterface.java:57)
                                                                         at org.tensorflow.demo.StylizeActivity.onPreviewSizeChosen(StylizeActivity.java:368)
                                                                         at org.tensorflow.demo.CameraActivity$1.onPreviewSizeChosen(CameraActivity.java:158)
                                                                         at org.tensorflow.demo.CameraConnectionFragment.setUpCameraOutputs(CameraConnectionFragment.java:394)
                                                                         at org.tensorflow.demo.CameraConnectionFragment.openCamera(CameraConnectionFragment.java:411)
                                                                         at org.tensorflow.demo.CameraConnectionFragment.access$000(CameraConnectionFragment.java:63)
                                                                         at org.tensorflow.demo.CameraConnectionFragment$1.onSurfaceTextureAvailable(CameraConnectionFragment.java:94)`


Have you any idea that why these error occurs. can you provide exact step for non bazel build in android studio in windows os.

**Comment by andrewharp** [comment]
@kinDSa If you do `unzip -v bazel-bin/tensorflow/examples/android/tensorflow_demo.apk`, what does it print out?

**Comment by kinDSa** [comment]
@andrewharp 
 `unzip:  cannot find or open bazel-bin/tensorflow/examples/android/tensorflow_demo.apk, bazel-bin/tensorflow/examples/android/tensorflow_demo.apk.zip or bazel-bin/tensorflow/examples/android/tensorflow_demo.apk.ZIP.
`

**Comment by andrewharp** [comment]
Sorry, that's the bazel output location. If you unzip the apk that gradle produces instead what does it say?

**Comment by kinDSa** [comment]
@andrewharp  while I unzip apk  produce by gradle I get output which attach in these file: [output.txt](https://github.com/tensorflow/tensorflow/files/816410/output.txt)

**Comment by andrewharp** [comment]
@kinDSa Somehow your armeabi-v7a file is 0 bytes:
`      0  Stored        0   0% 1980-00-00 00:00 00000000  lib/armeabi-v7a/libtensorflow_inference.so`

If you look in your libs/ directory, is the file there also 0 bytes? If so, try downloading again and make sure it gets overwritten properly.

**Comment by kinDSa** [comment]
@andrewharp Thank you, Now I successfully run TensorFlow Android Camera Demo after replacing libtensorflow_inference.so

**Comment by andrewharp** [comment]
Great!
