### ISSUE TITLE
pip3 No matching distribution found on OSX 10.9.5 py3.5

### ISSUE THREAD

**Issue by yasirs** [tensorflow/tensorflow#7793]
I am trying to install tensorflow in a virtualenv environment on OSX. 

I think I have a good Python version (3.5). This is what it says:
```
$ python
Python 3.5.2 (default, Oct  1 2016, 01:07:00) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
```

that happens when I give the pip install command:

```
$ pip3 install -vvv --upgrade tensorflow
Collecting tensorflow
  1 location(s) to search for versions of tensorflow:
  * https://pypi.python.org/simple/tensorflow/
  Getting page https://pypi.python.org/simple/tensorflow/
  Looking up "https://pypi.python.org/simple/tensorflow/" in the cache
  Current age based on date: 471
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 471
  Analyzing links from page https://pypi.python.org/simple/tensorflow/
    Skipping link https://pypi.python.org/packages/00/16/c8ba385fc6511ca362f32326cd1d6a99bbbabbc8341607ff70c290e0be7b/tensorflow-0.12.1-cp34-cp34m-manylinux1_x86_64.whl#md5=981c0a406eb9865423b11c03b489040d (from https://pypi.python.org/simple/tensorflow/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/01/c5/adefd2d5c83e6d8b4a8efa5dd00e44dc05de317b744fb58aef6d8366ce2b/tensorflow-0.12.0-cp27-cp27mu-manylinux1_x86_64.whl#md5=ebcd1b32ccf2279bfa688542cbdad5fb (from https://pypi.python.org/simple/tensorflow/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/03/51/b68d9d6481d16fd709290030ae8a8a13212587bc87fae718e521bdafa723/tensorflow-0.12.0rc1-cp27-cp27mu-manylinux1_x86_64.whl#md5=9329984aa4f6388f5ec2a170e4ae968e (from https://pypi.python.org/simple/tensorflow/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/0c/7c/29ac00dd86a419a6ecba16d2c319598adb92b261e7984666305f411bbd7d/tensorflow-1.0.0-cp35-cp35m-macosx_10_11_x86_64.whl#md5=51b1aba26e837825a4f1eafd2eb81fe7 (from https://pypi.python.org/simple/tensorflow/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/0d/d7/b49a6ceb055f392f91bce25eb6e1665f9b2f0a4628f7acdbccf1cd1d0ee6/tensorflow-1.0.0-cp27-cp27m-macosx_10_11_x86_64.whl#md5=51235fbe34e705bcdb1b5bbd6a482c57 (from https://pypi.python.org/simple/tensorflow/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/11/c9/2ec86336a8a401a57fabed5b10ee7f0493fc334b33e9672766b1149dd923/tensorflow-0.12.0-cp35-cp35m-win_amd64.whl#md5=d515d2ae08ae25fc8bf81e3374448146 (from https://pypi.python.org/simple/tensorflow/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/16/6e/fa1f09a32d3ba5bf6a2b79c6ec16a43c91e3a79e0035ab3eb52ecad22e0d/tensorflow-0.12.1-cp35-cp35m-macosx_10_11_x86_64.whl#md5=faf5d055cdaecd75e5f0b37a04676102 (from https://pypi.python.org/simple/tensorflow/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/25/23/24681ce011cd33ea5b22b8efd0f28a3f1294085c6ca6f70cc3abd62bf75d/tensorflow-0.12.0rc1-cp35-cp35m-macosx_10_11_x86_64.whl#md5=6c964e9575ed88892b94195a05aa8e65 (from https://pypi.python.org/simple/tensorflow/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/25/c4/162ea5fa9e012f5a5e125105f6b290e56f9fd617a7aadd57d9a26bb386ca/tensorflow-0.12.0rc1-cp34-cp34m-manylinux1_x86_64.whl#md5=4e77b31ae9fc0e36489875ce0f72b267 (from https://pypi.python.org/simple/tensorflow/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/33/4b/20e517870effa573405d30dafc22f330f24c0a8928659b4ad5a44b9a9af2/tensorflow-0.12.0rc0-cp35-cp35m-macosx_10_11_x86_64.whl#md5=8d1376a68f768efa57b1344fc2df0472 (from https://pypi.python.org/simple/tensorflow/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/33/ab/3a62133d6c9f6281959f3ca96ad2a796fb4fed8d642c4f33d9fd97d8bf6f/tensorflow-0.12.0rc1-cp27-cp27m-macosx_10_11_x86_64.whl#md5=491802c10e992905d7e80108b9b16920 (from https://pypi.python.org/simple/tensorflow/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/34/53/0e10581ad88bca25e5005874e46130b12efbd5eb1bda493dbf9b1648cbe2/tensorflow-0.12.1-cp27-cp27m-macosx_10_11_x86_64.whl#md5=d3f44a0596a623458c42c2a694abb0af (from https://pypi.python.org/simple/tensorflow/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/3f/8a/e80e2fef57bb1ffcff65c597adcddd5a0de17d7a7da5a6187503a28e9d66/tensorflow-1.0.0-cp33-cp33m-manylinux1_x86_64.whl#md5=ed46aa42e9716649572e0f861210b8f5 (from https://pypi.python.org/simple/tensorflow/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/48/58/b71480f9ec9d08d581d672a81b15ab5fec36a5fcda2093558a23614d8468/tensorflow-1.0.0-cp36-cp36m-manylinux1_x86_64.whl#md5=2742cfc22068004af8a1f31071d96546 (from https://pypi.python.org/simple/tensorflow/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/4a/c3/1ad85e5c4fde90b2e9a5101283d97dd41ba6c24f44a1c3a8495ef7098bb5/tensorflow-0.12.0rc0-cp35-cp35m-win_amd64.whl#md5=dad56a38acf7ca501b1bfeeef53f3710 (from https://pypi.python.org/simple/tensorflow/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/64/9c/72aff7713c507f7e6c15df011e0ed18ac85e5bfa16c3763d8cba44585d79/tensorflow-0.12.0rc0-cp34-cp34m-manylinux1_x86_64.whl#md5=93431c5cd8a019d08a72e6c0a75eaaf4 (from https://pypi.python.org/simple/tensorflow/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/64/a3/0054a3329579de44d557f491adbcaf8127809a7992bc46af80f0a589e29b/tensorflow-0.12.1-cp35-cp35m-win_amd64.whl#md5=d657836c76a5cd3c6d5560034bd7ade6 (from https://pypi.python.org/simple/tensorflow/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/65/a3/40bbfb783d955c1a959c8fa939f63b00d4fac9d0c3777e0607d39e31ba0a/tensorflow-1.0.0-cp36-cp36m-macosx_10_11_x86_64.whl#md5=5926a0360b2979cb969e8c38a18f9c0a (from https://pypi.python.org/simple/tensorflow/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/66/47/d6bb91a11684733ad565b891d561097ef10f8cb7bae87e5ad692207024e3/tensorflow-0.12.0rc1-cp35-cp35m-manylinux1_x86_64.whl#md5=2351fe799a0869487699537ab0e33019 (from https://pypi.python.org/simple/tensorflow/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/67/06/15153c48b2281bc59f8a70f2ae681723ece29ebc0015883117fb28abaf68/tensorflow-0.12.0rc0-cp35-cp35m-manylinux1_x86_64.whl#md5=ebc1ee880633a60e5256e745a27d4058 (from https://pypi.python.org/simple/tensorflow/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/7b/c5/a97ed48fcc878e36bb05a3ea700c077360853c0994473a8f6b0ab4c2ddd2/tensorflow-1.0.0-cp27-cp27mu-manylinux1_x86_64.whl#md5=a7483a4da4d70cc628e9e207238f77c0 (from https://pypi.python.org/simple/tensorflow/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/7e/c6/837f4e249aae5c86a632eaaa9779e601eca1487772f8ad75c347bf9e813f/tensorflow-0.12.1-cp27-cp27mu-manylinux1_x86_64.whl#md5=c98fd26b79a97cc490c942bbafed5462 (from https://pypi.python.org/simple/tensorflow/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/7e/ea/e42e47ddb39d2043a06dc93b5aec042bae8571be52ea664aa03246a83c32/tensorflow-0.12.0-cp35-cp35m-macosx_10_11_x86_64.whl#md5=f8b165ae638eb169220ccbf02658475b (from https://pypi.python.org/simple/tensorflow/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/90/cf/1d1e12f9f39b6a0ed1c49792ef5ce7615dddc2ce7287fc83ede0dddb9b3c/tensorflow-0.12.0rc0-cp27-cp27m-macosx_10_11_x86_64.whl#md5=7be7b7488a6be83546758a40d5442901 (from https://pypi.python.org/simple/tensorflow/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/91/7c/98b25b74241194d4312a7e230c85a77b254224191dbf17b484811f8a9f61/tensorflow-0.12.1-cp36-cp36m-macosx_10_11_x86_64.whl#md5=3b2f5f08fe61471ea973a4bdbdfbae43 (from https://pypi.python.org/simple/tensorflow/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/96/d6/096f6624a8a48d41801eb23863d35a37532baf32f6d3aa2e03c96f66e6ab/tensorflow-0.12.0-cp34-cp34m-manylinux1_x86_64.whl#md5=a6a0af9cf2a5fc33053f638b05cb3940 (from https://pypi.python.org/simple/tensorflow/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/9e/7c/f50ca985e43cff46a6d92abb088e8328b9be13335dc44af291ac1ed11862/tensorflow-0.12.0-cp35-cp35m-manylinux1_x86_64.whl#md5=2c07109df1a9865a7a44b6fe08756e8d (from https://pypi.python.org/simple/tensorflow/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/a7/86/cb47c1213779939583091fc97e0950c323d655186824cdbc0f657f42930c/tensorflow-0.12.0-cp27-cp27m-macosx_10_11_x86_64.whl#md5=fc429a5b5b74517e08216ee8b1d04e59 (from https://pypi.python.org/simple/tensorflow/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/b0/a6/a8b857c8b383c4a2a3dece8a3c0f86e9273b8fd7ce31528f8ac809fc5910/tensorflow-1.0.0-cp35-cp35m-manylinux1_x86_64.whl#md5=88f8b298a2efb3f2d236019c5dcc1220 (from https://pypi.python.org/simple/tensorflow/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/b2/da/9132af1e2ef3771b63619072a6d82800bd60acbf2c8bea8e4f26514c768a/tensorflow-0.12.0rc1-cp35-cp35m-win_amd64.whl#md5=69b6c2e9440fd2d7a2d86249933fcde0 (from https://pypi.python.org/simple/tensorflow/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/c0/9c/f094a4a79a5d45612394d97c27d03837a8f012f5f7ad085f2705b4ca0510/tensorflow-1.0.0-cp34-cp34m-manylinux1_x86_64.whl#md5=1e137fc0cb113d544758ba4a3334b3d6 (from https://pypi.python.org/simple/tensorflow/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/ce/2c/6a1cf90746879c2d05df04efc86a8b1edd79d7b06323a5c8fa63f5520824/tensorflow-1.0.0-cp35-cp35m-win_amd64.whl#md5=7e73a31ef4eb5914991cb2ad401fd21d (from https://pypi.python.org/simple/tensorflow/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/e5/5c/56e6522fdcd6f8739dcbc4de62e8b0040e141785bb42e5b53a83b0ba3e58/tensorflow-0.12.1-cp35-cp35m-manylinux1_x86_64.whl#md5=c6e3ba8579754f37d37be26e863f9d95 (from https://pypi.python.org/simple/tensorflow/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/e7/73/85ff235957f2652f78a2cd7f0a045d3f983302991cb7af2fddedf27d56fe/tensorflow-0.12.1-cp33-cp33m-manylinux1_x86_64.whl#md5=d77e48ef3b45e543ca165db93f27e0ff (from https://pypi.python.org/simple/tensorflow/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/e9/a5/45b172f20e2fabd19c7f18a44570fc82acc4c628ec9bc4b313de39c4fe37/tensorflow-0.12.1-cp36-cp36m-manylinux1_x86_64.whl#md5=def6ab7dc3930f34f3000caef34f4333 (from https://pypi.python.org/simple/tensorflow/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/f6/2a/e5bb6320a3fc2886f2677ffa0d4396eefb5914cfc19db94e672c650f0700/tensorflow-0.12.0rc0-cp27-cp27mu-manylinux1_x86_64.whl#md5=00a6b89122d86fd527558a2740fd6f8f (from https://pypi.python.org/simple/tensorflow/); it is not compatible with this Python
  Could not find a version that satisfies the requirement tensorflow (from versions: )
Cleaning up...
No matching distribution found for tensorflow
Exception information:
Traceback (most recent call last):
  File "/Users/myname/Envs/tensorflow/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Users/myname/Envs/tensorflow/lib/python3.5/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/Users/myname/Envs/tensorflow/lib/python3.5/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/Users/myname/Envs/tensorflow/lib/python3.5/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/Users/myname/Envs/tensorflow/lib/python3.5/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/Users/myname/Envs/tensorflow/lib/python3.5/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/Users/myname/Envs/tensorflow/lib/python3.5/site-packages/pip/index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for tensorflow
```

These are my current packages in this environment:
```
$ pip freeze
appdirs==1.4.0
nose==1.3.7
packaging==16.8
pbr==1.10.0
pyparsing==2.1.10
QScintilla==2.9.2
sip==4.18
six==1.10.0
stevedore==1.20.0
virtualenv==15.1.0
virtualenv-clone==0.2.6
virtualenvwrapper==4.7.2

```

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

StackOverflow has questions that deal with the period before the tensorflow wheel was on PyPi, or when the Python is not 64-bit or earlier than 3.5.

### Environment info
Operating System:
OSX 10.9.5
Installed version of CUDA and cuDNN: I don't have CUDA I believe.

**Comment by yasirs** [comment]
Ok, so it seems the problem might be that the wheels are provided for OSX 10.11 only and I have OSX 10.9.5. I don't want to reinstall my OS and break things on my work machine. So I downloaded the OSX 10.11 .whl file from Pypi and renamed it to OSX_10_9. This worked fine, and I was able to install tensorflow. 

```
$ cp ~/Downloads/tensorflow-1.0.0-cp35-cp35m-macosx_10_11_x86_64.whl ~/Downloads/tensorflow-1.0.0-cp35-cp35m-macosx_10_9_x86_64.whl
$ pip install ~/Downloads/tensorflow-1.0.0-cp35-cp35m-macosx_10_9_x86_64.whl 
```
I was able to run the hello world validation, and it just gave me the SSE warning (copied below). I hope the library is safe to run. I would request Pypi wheels to include support for OSX 10.9 and 10.11 as well. Or do you recommend people install from source on these versions?

```
In [1]: import tensorflow as tf

In [2]: sess = tf.Session()
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.

In [3]: hello = tf.constant('Hello, TensorFlow!')

In [4]: print(sess.run(hello))
b'Hello, TensorFlow!'

```

**Comment by poxvoculi** [comment]
OSX versions below 10.11 are not supported by the TF team, but you may find community support elsewhere.  The warnings you see are merely to let you know that performance will be better if you compile specifically for your machine.
