### ISSUE TITLE
TypeError: zeros_initializer() takes at least 1 argument

### ISSUE THREAD

**Issue by gitmcdull** [tensorflow/tensorflow#7835]
Tensorflow 0.12.1 (4d924e7)
I cloned the up-to-dated tensorflow-models today. 

I got the following error msg:
Traceback (most recent call last):
  File "/home/omnisky/data/tensorflow-models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception/flowers_train.py", line 41, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/home/omnisky/data/tensorflow-models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception/flowers_train.py", line 37, in main
    inception_train.train(dataset)
  File "/home/omnisky/data/tensorflow-models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception/inception_train.py", line 241, in train
    scope, reuse_variables)
  File "/home/omnisky/data/tensorflow-models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception/inception_train.py", line 109, in _tower_loss
    scope=scope)
  File "/home/omnisky/data/tensorflow-models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception/inception_model.py", line 87, in inference
    scope=scope)
  File "/home/omnisky/data/tensorflow-models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception/slim/inception_model.py", line 87, in inception_v3
    scope='conv0')
  File "/home/omnisky/data/tensorflow-models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception/slim/scopes.py", line 155, in func_with_args
    return func(*args, **current_args)
  File "/home/omnisky/data/tensorflow-models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception/slim/ops.py", line 234, in conv2d
    outputs = batch_norm(conv, **batch_norm_params)
  File "/home/omnisky/data/tensorflow-models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception/slim/scopes.py", line 155, in func_with_args
    return func(*args, **current_args)
  File "/home/omnisky/data/tensorflow-models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception/slim/ops.py", line 88, in batch_norm
    initializer=tf.zeros_initializer(),
TypeError: zeros_initializer() takes at least 1 argument (0 given)

I read through previous issues on zeors_initializer() & ones_initializer(). And I replaced zeros_initializer() w/ constant_initializer(0.0), but got the new error:
Traceback (most recent call last):
  File "/home/omnisky/data/tensorflow-models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception/flowers_train.py", line 41, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/home/omnisky/data/tensorflow-models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception/flowers_train.py", line 37, in main
    inception_train.train(dataset)
  File "/home/omnisky/data/tensorflow-models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception/inception_train.py", line 241, in train
    scope, reuse_variables)
  File "/home/omnisky/data/tensorflow-models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception/inception_train.py", line 109, in _tower_loss
    scope=scope)
  File "/home/omnisky/data/tensorflow-models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception/inception_model.py", line 87, in inference
    scope=scope)
  File "/home/omnisky/data/tensorflow-models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception/slim/inception_model.py", line 125, in inception_v3
    net = tf.concat([branch1x1, branch5x5, branch3x3dbl, branch_pool], 3)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1075, in concat
    dtype=dtypes.int32).get_shape(
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 669, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

Anybody can help? Thanks a lot!

**Comment by yaroslavvb** [comment]
Sounds like a snag with TF 1.0 transition. Can you run with "python -m pdb script.py", and use "up/down/print" to get the relevant values (ie, it was expecting int32, what was the actual value it got, and why?) this may need reading source-code around those lines

**Comment by gitmcdull** [comment]
Thanks a lot for your info. 

I run into this issue when i perform the following command. (This command comes from Nvidia's official tutorial on using Tensorflow. http://www.nvidia.com/object/gpu-accelerated-applications-tensorflow-running-jobs.html.)

bazel-bin/inception/flowers_train --train_dir=$FLOWERS_DIR/train --data_dir=$FLOWERS_DIR/data --pretrained_model_checkpoint_path=$INCEPTION_DIR/inception-v3/model.ckpt-157585 --fine_tune=True --initial_learning_rate=0.001 -input_queue_memory_factor=1 --max_steps=500 --num_gpus 1 --batch_size=64

Therefore, I failed to use "python -m pdb script.py" to debug. 

As its error msg indicated, "TypeError: Expected int32, got list containing Tensors of type '_Message' instead." 

Does this msg provide any info useful? Look forward to your kindly support.:-)

**Comment by yaroslavvb** [comment]
BTW, you are using TF 12.1, while a lot of models have been updated to TF 1.0, can you try to use TF 1.0 instead?

**Comment by gitmcdull** [comment]
@yaroslavvb Thanks a lot for you advices. 

I tried to install tensorflow-gpu V1.0.0 using 2 approaches. 
1. build from source code followed the instructions on https://github.com/tensorflow/tensorflow/blob/v1.0.0/tensorflow/g3doc/get_started/os_setup.md;
2. sudo pip install --upgrade tensorflow-gpu
Both of these approaches give rise to the error I mentioned earlier when trying Nvidia's official instructions on running tensorflow jobs (http://www.nvidia.com/object/gpu-accelerated-applications-tensorflow-running-jobs.html). 

Unfortunately, I even run into more troubles as for V1.0.0. 
V0.12.0: only inception not pass
V1.0.0: NONE of inception, mnist, lstm pass

1. inception V3 error:
omnisky@omnisky:~/data/tensorflow-models/inception$ bazel-bin/inception/flowers_train --train_dir=$FLOWERS_DIR/train --data_dir=$FLOWERS_DIR/data --pretrained_model_checkpoint_path=$INCEPTION_DIR/inception-v3/model.ckpt-157585 --fine_tune=True --initial_learning_rate=0.001 -input_queue_memory_factor=1 --max_steps=500 --num_gpus 1 --batch_size=64
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "/home/omnisky/data/tensorflow-models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception/flowers_train.py", line 41, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/omnisky/data/tensorflow-models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception/flowers_train.py", line 37, in main
    inception_train.train(dataset)
  File "/home/omnisky/data/tensorflow-models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception/inception_train.py", line 217, in train
    num_preprocess_threads=num_preprocess_threads)
  File "/home/omnisky/data/tensorflow-models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception/image_processing.py", line 136, in distorted_inputs
    num_readers=FLAGS.num_readers)
  File "/home/omnisky/data/tensorflow-models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception/image_processing.py", line 490, in batch_inputs
    example_serialized)
  File "/home/omnisky/data/tensorflow-models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception/image_processing.py", line 397, in parse_example_proto
    bbox = tf.concat(0, [ymin, xmin, ymax, xmax])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1047, in concat
    dtype=dtypes.int32).get_shape(
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 651, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 716, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

2. mnist model error:
omnisky@omnisky:~/data/tensorflow$ python -m tensorflow.models.image.mnist.convolutional
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Extracting data/train-images-idx3-ubyte.gz
Extracting data/train-labels-idx1-ubyte.gz
Extracting data/t10k-images-idx3-ubyte.gz
Extracting data/t10k-labels-idx1-ubyte.gz
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/image/mnist/convolutional.py", line 339, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/image/mnist/convolutional.py", line 231, in main
    logits, train_labels_node))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 1684, in sparse_softmax_cross_entropy_with_logits
    labels, logits)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 1533, in _ensure_xent_args
    "named arguments (labels=..., logits=..., ...)" % name)
ValueError: Only call `sparse_softmax_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)

3. lstm model error: it seems /models has been removed
omnisky@omnisky:~/app/sourceCode$ python tensorflow/tensorflow/models/rnn/ptb/ptb_word_lm.py --data=./simple-examples/data --model=small
python: can't open file 'tensorflow/tensorflow/models/rnn/ptb/ptb_word_lm.py': [Errno 2] No such file or directory

**Comment by gitmcdull** [comment]
I found it was caused by a switch of parameter positions in tf.concat. But another error popped up "AttributeError: 'module' object has no attribute 'image_summary'". I will probably give up inception and go on with TF-slim instead. Thank you anyway. @yaroslavvb

**Comment by yaroslavvb** [comment]
@gitmcdull ps, conversion script is at https://www.tensorflow.org/install/migration . Not sure what the status of 1.0 models, I've had to upgrade resnet [myself](https://github.com/tensorflow/models/pull/959), it might help to file bugs on tensorflow/models with respective maintainers if you see any that aren't 1.0 ready
