### ISSUE TITLE
TensorFlow's introductory examples errors

### ISSUE THREAD

**Issue by elavi001** [tensorflow/tensorflow#7841]
I am following along from this point: https://www.tensorflow.org/get_started/get_started#basic_usage
It is a linear regression example.

I have approached this execution from two angles:

Angle 1: Running python and copying one line at a time.
When run this line:  estimator = `tf.contrib.learn.LinearRegressor(feature_columns=features)`

I get this issue: `WARNING:tensorflow:Using temporary folder as model directory: C:\Users\elavi\AppData\Local\Temp\tmprirdvmnn
INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1
}
, '_task_type': None, '_save_checkpoints_steps': None, '_master': '', '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x0000021D2049C390>, '_task_id': 0, '_save_checkpoints_secs': 600, '_save_summary_steps': 100, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_evaluation_master': '', '_tf_random_seed': None, '_environment': 'local', '_num_ps_replicas': 0}`

Angle 2: It may be more helpful to see how I run it as a script as a whole. The output is:
`WARNING:tensorflow:Using temporary folder as model directory: C:\Users\elavi\AppData\Local\Temp\tmp41huenz5
WARNING:tensorflow:Rank of input Tensor (1) should be the same as output_rank (2) for column. Will attempt to expand dims. It is highly recommended that you resize your input, as this behavior may change.
WARNING:tensorflow:From C:\Users\elavi\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\head.py:521: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
2017-02-24 00:02:36.386704: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE instructions, but these are available on your machine and could speed up CPU computations.
2017-02-24 00:02:36.388071: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE2 instructions, but these are available on your machine and could speed up CPU computations.
2017-02-24 00:02:36.389235: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
2017-02-24 00:02:36.389290: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-02-24 00:02:36.390010: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-02-24 00:02:36.390894: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-02-24 00:02:36.391659: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-02-24 00:02:36.392248: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
WARNING:tensorflow:Rank of input Tensor (1) should be the same as output_rank (2) for column. Will attempt to expand dims. It is highly recommended that you resize your input, as this behavior may change.
WARNING:tensorflow:From C:\Users\elavi\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\head.py:521: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:Skipping summary for global_step, must be a float or np.float32.
`

I am interested in what is going on but I really need things simplified. A list of steps to fix this would be great. Also, if there are any better ways I could pose my problems in the future, please let me know.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
Many. The issue is that I am very new. My ability to understand solutions is very small. I am not well versed with the required terminology. So I have seen this problem posed and closed but I just can't follow along.

### Environment info
Operating System: Windows 10

Installed version of CUDA and cuDNN: I have the latest version but I probably shouldn't because I do not have a dedicated graphics card. (I am doing initial development on Microsoft Surface Pro 4) 

TF Version
1.0.0-rc2

**Comment by poxvoculi** [comment]
All I see in the output you posted are warnings, not errors.  Those warnings point out issues you ought to be aware of, but should not prevent a correct evaluation.  If you ignore those warnings, does the example not work?

**Comment by wenquanzhao** [comment]
Same problem for me

**Comment by ElliotVilhelm** [comment]
same problem here

**Comment by yaroslavvb** [comment]
@wenquanzhao / @ElliotVilhelm can you see if poxvoculli's reply addresses your problem (ie, the solution is to ignore these messages)

**Comment by elavi001** [comment]
@poxvoculi @yaroslavvb 
 No it doesn't. If it did, the expected output would at least include
`{'loss': 5.9819476e-11, 'global_step': 1000}` According to the example by TF.

**Comment by aselle** [comment]
Make sure a print is working for you at all ...
you can surround the final print in that code with

```
print("STARTING")
print(estimator.evaluate(input_fn=input_fn, steps=10))
print("ENDING")
```
See if you can see either of those added prints working.

**Comment by elavi001** [comment]
@aselle 
The result is
`STARTING
WARNING:tensorflow:Using temporary folder as model directory: C:\Users\elavi\AppData\Local\Temp\tmp_ukogsp9
WARNING:tensorflow:Rank of input Tensor (1) should be the same as output_rank (2) for column. Will attempt to expand dims. It is highly recommended that you resize your input, as this behavior may change.
WARNING:tensorflow:From C:\Users\elavi\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\head.py:521: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
2017-02-27 11:35:27.716156: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE instructions, but these are available on your machine and could speed up CPU computations.
2017-02-27 11:35:27.716322: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE2 instructions, but these are available on your machine and could speed up CPU computations.
2017-02-27 11:35:27.719845: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
2017-02-27 11:35:27.720688: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-02-27 11:35:27.721719: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-02-27 11:35:27.722310: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-02-27 11:35:27.722955: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-02-27 11:35:27.723499: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
WARNING:tensorflow:Rank of input Tensor (1) should be the same as output_rank (2) for column. Will attempt to expand dims. It is highly recommended that you resize your input, as this behavior may change.
WARNING:tensorflow:From C:\Users\elavi\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\head.py:521: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:Skipping summary for global_step, must be a float or np.float32.
WARNING:tensorflow:Rank of input Tensor (1) should be the same as output_rank (2) for column. Will attempt to expand dims. It is highly recommended that you resize your input, as this behavior may change.
WARNING:tensorflow:From C:\Users\elavi\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\head.py:521: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:Skipping summary for global_step, must be a float or np.float32.
{'loss': 1.209928e-08, 'global_step': 1000}
ENDING`

So something is certainly working. I have questions though:
1. Every time I run the same code, the loss changes. Why?
2. Why did you pick steps = 10?
3. Least importantly, am I going to have to perpetually live with these warnings?

**Comment by aselle** [comment]
Your last three lines here
```
list of tags to a scalar summary op is no longer supported. WARNING:tensorflow:Skipping
summary for global_step, must be a float or np.float32. {'loss': 1.209928e-08, 'global_step': 1000} ENDING
```
have 
```
{'loss': 1.209928e-08, 'global_step': 1000} 
```
So it did work. the loss became effectively zero (1e-8 is about zero for the purposes of this discussion). The loss changes because the examples are ordered randomly and the weights are initialized randomly. That means that the exact numeric values are not deterministic (this is inherent in stochastic gradient descent learning approaches).

TensorFlow is verbose on startup so it is hard to see the result, but it is there.

**Comment by elavi001** [comment]
@aselle I see, thank you! I still don't like the warnings but I am glad this all works! 

For future TF Beginners, the example code on the TF website is missing this line where it prints the estimator results at the end:
`print(estimator.evaluate(input_fn=input_fn)`

Thanks to everybody on this thread, I am closing it now.

**Comment by poxvoculi** [comment]
It might be helpful to take a look at an overview of TensorFlow logging.
<https://www.tensorflow.org/get_started/monitors>  There are multiple
levels of logging available, and their labels are somewhat arbitrary.
ERROR is supposed to be used for things which are really errors, i.e. a
value has been encountered somewhere which is outside of the legal range,
and correct computation cannot continue, but maybe we can unwind up the
stack and retry something.  FATAL is even more severe, it means the program
must terminate now.   There are multiple gentler logging levels for
informational or debugging messages.  WARNING is intermediate, for
something that isn't definitely an error, but you ought to know about.
 (WARNING also has the sometimes useful property that it flushes to the log
file immediately, so it should be there if a hard program failure occurs
soon afterward.)  According to the documentation I cited, the default
logging level is WARN, which means that logging messages of lesser severity
will likely not display to novices, and if one of the TF developers wants
to make sure you see a message, it needs to be a WARNING.  So, some of
these WARNINGs are just messages that someone hopes will help users
self-diagnose a non-optimal situation without needing to post issues here.

**Comment by JavascriptMick** [comment]
I managed to suppress all the warnings with this.  

```
# https://github.com/tensorflow/tensorflow/issues/7778
# TF_CPP_MIN_LOG_LEVEL is a TensorFlow environment variable responsible for the logs, 
# to silence INFO logs set it to 1, to filter out WARNING 2 and to additionally silence ERROR logs (not recommended) set it to 3
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

import numpy as np
import tensorflow as tf

# supress 'monitor' warnings...
# https://www.tensorflow.org/get_started/monitors
tf.logging.set_verbosity(tf.logging.ERROR)
```

**Comment by tonytangau** [comment]
You have to set the `model_dir`, eg. if you want to store the outputs in `./output `folder:

`estimator = tf.contrib.learn.LinearRegressor(feature_columns=features, model_dir='./output')`

Same thing if you follow the next example (Custom model):

`estimator = tf.contrib.learn.Estimator(model_fn=model,model_dir='./output')`

Then you can use TensorBoard to show the result:
`>tensorboard --logdir=output`

<img width="730" alt="tb" src="https://cloud.githubusercontent.com/assets/2390257/26750453/63e5c074-4855-11e7-9cee-349b73f2d9f9.PNG">

**Comment by hj3yoo** [comment]
@tonytangau I was actually having an error with a huge stack for this tutorial, and adding model_dir DID fix the error somehow... how could this even be the case?
```
C:\Users\Username\AppData\Local\Programs\Python\Python36\python.exe C:/Users/Username/git/TensorFlowTutorial/tf_contrib_learn_tutorial.py
WARNING:tensorflow:Using temporary folder as model directory: C:\Users\Username\AppData\Local\Temp\tmprgntzl60
WARNING:tensorflow:From C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\head.py:625: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
Traceback (most recent call last):
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1139, in _do_call
    return fn(*args)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1121, in _run_fn
    status, run_metadata)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\contextlib.py", line 89, in __exit__
    next(self.gen)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: Failed to rename: C:\Users\Username\AppData\Local\Temp\tmprgntzl60\model.ckpt-1_temp_ea3d2f00fe2043578134043560b310e6/part-00000-of-00001.index.tempstate17313616136446688854 to: C:\Users\Username\AppData\Local\Temp\tmprgntzl60\model.ckpt-1_temp_ea3d2f00fe2043578134043560b310e6/part-00000-of-00001.index : The process cannot access the file because it is being used by another process.

	 [[Node: save/SaveV2 = SaveV2[dtypes=[DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](save/ShardedFilename, save/SaveV2/tensor_names, save/SaveV2/shape_and_slices, global_step, linear/bias_weight/part_0/read, linear/regression_head/linear/bias_weight/part_0/Ftrl/read, linear/regression_head/linear/bias_weight/part_0/Ftrl_1/read, linear/x/weight/part_0/read, linear/regression_head/linear/x/weight/part_0/Ftrl/read, linear/regression_head/linear/x/weight/part_0/Ftrl_1/read)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Username/git/TensorFlowTutorial/tf_contrib_learn_tutorial.py", line 52, in <module>
    main()
  File "C:/Users/Username/git/TensorFlowTutorial/tf_contrib_learn_tutorial.py", line 42, in main
    estimator.fit(input_fn=input_fn, steps=1000)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\util\deprecation.py", line 289, in new_func
    return func(*args, **kwargs)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 455, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 1007, in _train_model
    _, loss = mon_sess.run([model_fn_ops.train_op, model_fn_ops.loss])
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 505, in run
    run_metadata=run_metadata)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 842, in run
    run_metadata=run_metadata)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 798, in run
    return self._sess.run(*args, **kwargs)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 960, in run
    run_metadata=run_metadata))
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\basic_session_run_hooks.py", line 368, in after_run
    self._save(global_step, run_context.session)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\basic_session_run_hooks.py", line 384, in _save
    self._get_saver().save(session, self._save_path, global_step=step)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 1488, in save
    raise exc
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 1472, in save
    {self.saver_def.filename_tensor_name: checkpoint_file})
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 789, in run
    run_metadata_ptr)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Failed to rename: C:\Users\Username\AppData\Local\Temp\tmprgntzl60\model.ckpt-1_temp_ea3d2f00fe2043578134043560b310e6/part-00000-of-00001.index.tempstate17313616136446688854 to: C:\Users\Username\AppData\Local\Temp\tmprgntzl60\model.ckpt-1_temp_ea3d2f00fe2043578134043560b310e6/part-00000-of-00001.index : The process cannot access the file because it is being used by another process.

	 [[Node: save/SaveV2 = SaveV2[dtypes=[DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](save/ShardedFilename, save/SaveV2/tensor_names, save/SaveV2/shape_and_slices, global_step, linear/bias_weight/part_0/read, linear/regression_head/linear/bias_weight/part_0/Ftrl/read, linear/regression_head/linear/bias_weight/part_0/Ftrl_1/read, linear/x/weight/part_0/read, linear/regression_head/linear/x/weight/part_0/Ftrl/read, linear/regression_head/linear/x/weight/part_0/Ftrl_1/read)]]

Caused by op 'save/SaveV2', defined at:
  File "C:/Users/Username/git/TensorFlowTutorial/tf_contrib_learn_tutorial.py", line 52, in <module>
    main()
  File "C:/Users/Username/git/TensorFlowTutorial/tf_contrib_learn_tutorial.py", line 42, in main
    estimator.fit(input_fn=input_fn, steps=1000)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\util\deprecation.py", line 289, in new_func
    return func(*args, **kwargs)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 455, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 1003, in _train_model
    config=self._session_config
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 352, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 648, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 477, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 822, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 827, in _create_session
    return self._sess_creator.create_session()
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 538, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 403, in create_session
    self._scaffold.finalize()
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 205, in finalize
    self._saver.build()
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 1170, in build
    restore_sequentially=self._restore_sequentially)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 685, in build
    save_tensor = self._AddShardedSaveOps(filename_tensor, per_device)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 361, in _AddShardedSaveOps
    return self._AddShardedSaveOpsForV2(filename_tensor, per_device)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 335, in _AddShardedSaveOpsForV2
    sharded_saves.append(self._AddSaveOps(sharded_filename, saveables))
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 276, in _AddSaveOps
    save = self.save_op(filename_tensor, saveables)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 219, in save_op
    tensors)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 745, in save_v2
    tensors=tensors, name=name)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

FailedPreconditionError (see above for traceback): Failed to rename: C:\Users\Username\AppData\Local\Temp\tmprgntzl60\model.ckpt-1_temp_ea3d2f00fe2043578134043560b310e6/part-00000-of-00001.index.tempstate17313616136446688854 to: C:\Users\Username\AppData\Local\Temp\tmprgntzl60\model.ckpt-1_temp_ea3d2f00fe2043578134043560b310e6/part-00000-of-00001.index : The process cannot access the file because it is being used by another process.

	 [[Node: save/SaveV2 = SaveV2[dtypes=[DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](save/ShardedFilename, save/SaveV2/tensor_names, save/SaveV2/shape_and_slices, global_step, linear/bias_weight/part_0/read, linear/regression_head/linear/bias_weight/part_0/Ftrl/read, linear/regression_head/linear/bias_weight/part_0/Ftrl_1/read, linear/x/weight/part_0/read, linear/regression_head/linear/x/weight/part_0/Ftrl/read, linear/regression_head/linear/x/weight/part_0/Ftrl_1/read)]]


Process finished with exit code 1
```

**Comment by hj3yoo** [comment]
@tonytangau Unlike elvai001's case, mine DOES end up in an error if I don't explicitly add model_dir into the parameter like you've mentioned :/

**Comment by sedziwoj** [comment]
Tutorial code should always work and give exactly the same result. 
Not mention "warning" is something i should not ignore and should not be in tutorial code. 
If someone think in the opposite way, sorry but it make bad image of project, some people are not capable to make human communication even if they are good at same others things.
For me it is a message: "I will have more problems in future" so before to invest money and time in it, i will try the other solution. Sorry but it is always hard at start and when creator do not care about clean, working code, it gets much harder.

**Comment by drvladb** [comment]
same here
