### ISSUE TITLE
No kernels registered for op `Conv2DBackpropInputV2`

### ISSUE THREAD

**Issue by LongZE666** [tensorflow/tensorflow#78431]
### Issue type

Documentation Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf 2.16.1

### Custom code

Yes

### Current behavior?

The existence of operator `Conv2DBackpropInputV2` is described in the official website document.https://www.tensorflow.org/api_docs/python/tf/raw_ops/Conv2DBackpropInputV2.
However, during my actual execution, the following error message appears:

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

input_sizes = tf.constant(1, shape=[4], dtype=tf.int32)
filter_tensor = tf.constant(2, shape=[4], dtype=tf.float32)
out_backprop = tf.constant(5, shape=[1, 5, 5, 2], dtype=tf.float32)

strides = [1, 1, 1, 1]
padding = "SAME"

tf.raw_ops.Conv2DBackpropInputV2(
    input=input_sizes,
    filter=filter_tensor,
    out_backprop=out_backprop,
    strides=strides,
    padding=padding
)
```

### Relevant log output

```shell
2024-10-21 12:30:18.492624: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/mnt/tests/Conv2DBackpropInput.py", line 10, in <module>
    tf.raw_ops.Conv2DBackpropInputV2(
  File "/mnt/origin/venv/tensorflow-nightly/lib/python3.11/site-packages/tensorflow/python/util/tf_export.py", line 377, in wrapper
    return f(**kwargs)
           ^^^^^^^^^^^
  File "/mnt/origin/venv/tensorflow-nightly/lib/python3.11/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 2030, in conv2d_backprop_input_v2
    _ops.raise_from_not_ok_status(e, name)
  File "/mnt/origin/venv/tensorflow-nightly/lib/python3.11/site-packages/tensorflow/python/framework/ops.py", line 5983, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tensorflow.python.framework.errors_impl.NotFoundError: Could not find device for node: {{node Conv2DBackpropInputV2}} = Conv2DBackpropInputV2[T=DT_INT32, data_format="NHWC", dilations=[1, 1, 1, 1], explicit_paddings=[], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true]
All kernels registered for op Conv2DBackpropInputV2:
  <no registered kernels>
 [Op:Conv2DBackpropInputV2] name:
```

**Comment by Venkat6871** [comment]
I tried to run your code on colab using Tensorflow 2.17.0 and nightly versions. And faced the same issue. Please find the [gist](https://colab.sandbox.google.com/gist/Venkat6871/579d3fcc1d9ca68f810bb8a1a1cdf4ad/78431_2-17-0-nightly-v.ipynb) here for reference.
Thank you!

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

From the example shared, this appears to be related to invoking `tf.raw_ops.Conv2DBackpropInputV2` with a configuration for which no compatible kernels are registered. In the reproducer, the operation fails with a `NotFoundError` indicating that no matching execution kernels could be found for the provided inputs and attributes.
Using the fully supported primary operation `tf.raw_ops.Conv2DBackpropInput` or higher-level APIs such as `tf.nn.conv2d_transpose` may help avoid this issue.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
