### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.python.client'

### ISSUE THREAD

**Issue by metehanozdeniz** [tensorflow/tensorflow#78466]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.15.0

### Custom code

No

### OS platform and distribution

Linux Ubuntu 24.04.1 LTS

### Python version

3.10.9

### CUDA/cuDNN version

12.7/12.0.140

### GPU model and memory

RTX 3050 4 GB

### Current behavior?

Whenever I try to convert onnx model to tensorflow I get this error.

~~~shell
$ onnx-tf convert -i yolov7.onnx -o tensorflow-model/
~~~

output:

~~~
Traceback (most recent call last):
  File "/home/metehan/miniconda3/envs/yolov7/bin/onnx-tf", line 5, in <module>
    from onnx_tf.cli import main
  File "/home/metehan/miniconda3/envs/yolov7/lib/python3.10/site-packages/onnx_tf/__init__.py", line 1, in <module>
    from . import backend
  File "/home/metehan/miniconda3/envs/yolov7/lib/python3.10/site-packages/onnx_tf/backend.py", line 25, in <module>
    from onnx_tf.common import data_type
  File "/home/metehan/miniconda3/envs/yolov7/lib/python3.10/site-packages/onnx_tf/common/__init__.py", line 14, in <module>
    from tensorflow.python.client import device_lib
ModuleNotFoundError: No module named 'tensorflow.python.client'
~~~

### Standalone code to reproduce the issue

```python
import onnx
from onnx_tf.backend import prepare

onnx_model = onnx.load("yolov7-tinny.onnx")
tf_rep = prepare(onnx_model)
tf_rep.export_graph("tensorflow-model.pb")
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/metehan/miniconda3/envs/yolov7/bin/onnx-tf", line 5, in <module>
    from onnx_tf.cli import main
  File "/home/metehan/miniconda3/envs/yolov7/lib/python3.10/site-packages/onnx_tf/__init__.py", line 1, in <module>
    from . import backend
  File "/home/metehan/miniconda3/envs/yolov7/lib/python3.10/site-packages/onnx_tf/backend.py", line 25, in <module>
    from onnx_tf.common import data_type
  File "/home/metehan/miniconda3/envs/yolov7/lib/python3.10/site-packages/onnx_tf/common/__init__.py", line 14, in <module>
    from tensorflow.python.client import device_lib
ModuleNotFoundError: No module named 'tensorflow.python.client'
```

**Comment by Venkat6871** [comment]
Hi **@metehanozdeniz** ,
Apologies for the delay. Could you please provide the model you are using? It would be helpful to replicate the issue.
Thank you!
