### ISSUE TITLE
mnist.input_data.read_data_sets() cause Segmentation Fault upon exiting

### ISSUE THREAD

**Issue by cw1204772** [tensorflow/tensorflow#7854]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your 
While I was trying the [MNIST tutorial](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/mnist/mnist_softmax.py), I found my tensorflow output Segmentation Fault (Core Dumped). 

However, my mnist_softmax.py can still operates normally, outputing correct output on the terminal. It prints out the core dumped when the program exits.

After some try and error, I think it's this line 
`mnist = input_data.read_data_sets(FLAGS.data_dir, one_hot=True)` 
causing program to Core dumped upon exiting. Maybe this is a r1.0 bug?

### Environment info
Operating System: Ubuntu 14.04.5 LTS
CUDA 8.0
CuDNN 5.1.5

Tensorflow r1.0 installed from source:
1. The commit hash: 29a6b4661258ef99842904d7c54993c963a8c2c0
2. The output of `bazel version`
Build label: 0.4.4
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Feb 1 18:54:21 2017 (1485975261)
Build timestamp: 1485975261
Build timestamp as int: 1485975261

### If possible, provide a minimal reproducible example
The same code as [MNIST tutorial](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/mnist/mnist_softmax.py)

### What other attempted solutions have you tried?
I've tried out the [Getting Started tutorial](https://www.tensorflow.org/get_started/get_started#complete_program), and it worked perfectly. 
I've try to comment each line to figure out which line cause the error. The result is 
`mnist = input_data.read_data_sets(FLAGS.data_dir, one_hot=True)` seems to cause the problem.

### Logs or other output that would be helpful
```
$ python example.py
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Extracting /tmp/tensorflow/mnist/input_data/train-images-idx3-ubyte.gz
Extracting /tmp/tensorflow/mnist/input_data/train-labels-idx1-ubyte.gz
Extracting /tmp/tensorflow/mnist/input_data/t10k-images-idx3-ubyte.gz
Extracting /tmp/tensorflow/mnist/input_data/t10k-labels-idx1-ubyte.gz
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:910] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties:
name: GeForce GTX 770
major: 3 minor: 0 memoryClockRate (GHz) 1.1105
pciBusID 0000:01:00.0
Total memory: 1.95GiB
Free memory: 1.66GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 770, pci bus id: 0000:01:00.0)
0.917
Segmentation fault (core dumped)
```

**Comment by sharkdtu** [comment]
The same problem hit me

**Comment by aselle** [comment]
I tried with cuda 8.0 and cudnn 5.0 on ubuntu 14, and it works fine for me on the 1.0 release version. @gunan, @zheng-xq, have you seen any reports of this happening? Could you try from take r1.0 or from a pre-build binary.

**Comment by mkamranmalik** [comment]
While I was trying "https://www.tensorflow.org/get_started/mnist/beginners" and trying to run below commands and facing time out exception. (I am using window 7 and tensorflow v.1
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

**Comment by gunan** [comment]
@aselle I have not seen any other reports of this.
@cw1204772 Could you try to get a stack trace for us to inspect?

@mkamranmalik You are seeing a different error, on a different Operating system. Your report here will just confuse us when trying to help our with the actual issue reported at the top.
You need to file a new issue by filling in all the information we are requesting for us to be able to help you out.

**Comment by cw1204772** [comment]
Back trace result using gdb
```
#0  0x00007ffff782dc37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff7831028 in __GI_abort () at abort.c:89
#2  0x00007ffff786a2a4 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7ffff79786b0 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff787655e in malloc_printerr (ptr=<optimized out>, str=0x7ffff7974801 "free(): invalid pointer", action=1) at malloc.c:4996
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3840
#5  0x00007fffe19b53e3 in ufunc_dealloc (ufunc=0xa4c570) at numpy/core/src/umath/ufunc_object.c:4992
#6  0x000000000055a657 in ?? ()
#7  0x000000000055a52f in ?? ()
#8  0x000000000045b2cf in _PyImport_Fini ()
#9  0x0000000000437d51 in Py_Finalize ()
#10 0x000000000044f993 in Py_Main ()
#11 0x00007ffff7818f45 in __libc_start_main (main=0x44f9c2 <main>, argc=2, argv=0x7fffffffdde8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffddd8) at libc-start.c:287
#12 0x0000000000578c4e in _start ()
```

Terminal message during execution: (only use 10 epoch for inferencing mode)
```
Starting program: /usr/bin/python mnist.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff3647700 (LWP 9936)]
[New Thread 0x7ffff2e46700 (LWP 9937)]
[New Thread 0x7ffff0645700 (LWP 9938)]
[New Thread 0x7fffede44700 (LWP 9939)]
[New Thread 0x7fffeb643700 (LWP 9940)]
[New Thread 0x7fffe8e42700 (LWP 9941)]
[New Thread 0x7fffe6641700 (LWP 9942)]
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
[Thread 0x7fffe6641700 (LWP 9942) exited]
[Thread 0x7ffff3647700 (LWP 9936) exited]
[Thread 0x7ffff2e46700 (LWP 9937) exited]
[Thread 0x7fffe8e42700 (LWP 9941) exited]
[Thread 0x7fffeb643700 (LWP 9940) exited]
[Thread 0x7fffede44700 (LWP 9939) exited]
[Thread 0x7ffff0645700 (LWP 9938) exited]
Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
[New Thread 0x7fffe6641700 (LWP 9945)]
[New Thread 0x7fffe8e42700 (LWP 9946)]
[New Thread 0x7fffeb643700 (LWP 9947)]
[New Thread 0x7fffede44700 (LWP 9948)]
[New Thread 0x7fffbbf85700 (LWP 9949)]
[New Thread 0x7fffbb784700 (LWP 9950)]
[New Thread 0x7fffbaf83700 (LWP 9951)]
[New Thread 0x7fffba782700 (LWP 9952)]
[New Thread 0x7fffb9f81700 (LWP 9953)]
[New Thread 0x7fffb9780700 (LWP 9954)]
[New Thread 0x7fffb8f7f700 (LWP 9955)]
[New Thread 0x7fffb877e700 (LWP 9956)]
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:910] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 770
major: 3 minor: 0 memoryClockRate (GHz) 1.1105
pciBusID 0000:01:00.0
Total memory: 1.95GiB
Free memory: 1.55GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 770, pci bus id: 0000:01:00.0)
[New Thread 0x7fffb7f7d700 (LWP 9957)]
[New Thread 0x7fffb5756700 (LWP 9958)]
[New Thread 0x7fffb4f55700 (LWP 9959)]
[New Thread 0x7fffb4754700 (LWP 9960)]
[New Thread 0x7fffb3f53700 (LWP 9961)]
[New Thread 0x7fffb3752700 (LWP 9962)]
[New Thread 0x7fffb2f51700 (LWP 9963)]
[New Thread 0x7fffb2750700 (LWP 9964)]
[New Thread 0x7fffb1f4f700 (LWP 9965)]
[New Thread 0x7fffb174e700 (LWP 9966)]
[New Thread 0x7fffb09ff700 (LWP 9967)]
0/1000
0.458
[Thread 0x7fffb7f7d700 (LWP 9957) exited]
[Thread 0x7fffb5756700 (LWP 9958) exited]
```

**Comment by cw1204772** [comment]
What really boggles me is when I try to back traced today, it come up with a slightly different back traced message. (Core dumped at the exit of the program)
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff787601f in _int_free (av=0x7ffff7bb5760 <main_arena>, p=<optimized out>,
    have_lock=0) at malloc.c:3996
3996    malloc.c: No such file or directory.
(gdb) bt
#0  0x00007ffff787601f in _int_free (av=0x7ffff7bb5760 <main_arena>, p=<optimized out>,
    have_lock=0) at malloc.c:3996
#1  0x00000000004f7c6c in ?? ()
#2  0x00000000004f78c4 in ?? ()
#3  0x000000000055a657 in ?? ()
#4  0x000000000059fc62 in ?? ()
#5  0x0000000000507eb0 in PyDict_SetItem ()
#6  0x00000000004f7f71 in _PyModule_Clear ()
#7  0x00000000004c7d61 in PyImport_Cleanup ()
#8  0x0000000000437d4c in Py_Finalize ()
#9  0x000000000044f993 in Py_Main ()
#10 0x00007ffff7818f45 in __libc_start_main (main=0x44f9c2 <main>, argc=2,
    argv=0x7fffffffe438, init=<optimized out>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7fffffffe428) at libc-start.c:287
#11 0x0000000000578c4e in _start ()
```

**Comment by gunan** [comment]
@jhseu Any ideas on this one?

**Comment by jhseu** [comment]
Same issue as https://github.com/tensorflow/tensorflow/issues/6968. Known issue with Ubuntu 14.04.

You can either upgrade Ubuntu or install numpy from source with OpenBLAS disabled.

**Comment by asimshankar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
