### ISSUE TITLE
Grouped Conv3D convolutions don't work with some of the number of input filters

### ISSUE THREAD

**Issue by dan-kazbek** [tensorflow/tensorflow#78984]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

tf 2.9.1

### Custom code

Yes

### OS platform and distribution

Linux Ubuntu 20.04

### Python version

3.8.10

### CUDA/cuDNN version

CUDA version 11.2, cuDNN version 8.1.0

### GPU model and memory

NVIDIA A100 80GB

### Current behavior?

As the title says, grouped 3D convolutions don't work if we have some specific combinations of input / output filters and batch size.  If I try to execute the standalone code I provided, the script crashes with the log output I provided. If I reduce the number of groups  to 1, the calculations proceed as expected.
If I reduce the `batch_size` to 8, the forward pass of the layers is performed successfully, but the following warning is shown:
```
2024-10-29 21:25:47.628087: W tensorflow/compiler/xla/service/gpu/gpu_conv_algorithm_picker.cc:727] None of the algorithms provided by cuDNN heuristics worked; trying fallback algorithms.  Conv: (f32[8,64,64,64,128]{3,2,1,4,0}, u8[0]{0}) custom-call(f32[8,64,64,64,512]{3,2,1,4,0}, f32[1,1,1,256,128]{2,1,0,3,4}), window={size=1x1x1}, dim_labels=b012f_012io->b012f, feature_group_count=2, custom_call_target="__cudnn$convForward", backend_config="{\"conv_result_scale\":1,\"activation_mode\":\"0\",\"side_input_scale\":0}"
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
from keras import layers

conv_layer = layers.Conv3D(
    kernel_size=1,
    filters=128,
    groups=2,
)

batch_size = 16
layer_input = tf.random.normal((batch_size, 64, 64, 64, 512))
output = conv_layer(layer_input)
print(output.shape)
```

### Relevant log output

```shell
2024-10-29 21:18:03.441000: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-10-29 21:18:04.710425: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 78924 MB memory:  -> device: 0, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:35:00.0, compute capability: 8.0
2024-10-29 21:18:04.712408: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 78924 MB memory:  -> device: 1, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:36:00.0, compute capability: 8.0
2024-10-29 21:18:06.075880: I tensorflow/compiler/xla/service/service.cc:170] XLA service 0x47fb3520 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2024-10-29 21:18:06.075966: I tensorflow/compiler/xla/service/service.cc:178]   StreamExecutor device (0): NVIDIA A100 80GB PCIe, Compute Capability 8.0
2024-10-29 21:18:06.075979: I tensorflow/compiler/xla/service/service.cc:178]   StreamExecutor device (1): NVIDIA A100 80GB PCIe, Compute Capability 8.0
2024-10-29 21:18:06.742974: I tensorflow/stream_executor/cuda/cuda_dnn.cc:384] Loaded cuDNN version 8100
2024-10-29 21:18:08.492106: I tensorflow/compiler/jit/xla_compilation_cache.cc:478] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
2024-10-29 21:18:08.492559: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at xla_ops.cc:296 : UNKNOWN: Failed to determine best cudnn convolution algorithm for:
%cudnn-conv = (f32[16,64,64,64,128]{3,2,1,4,0}, u8[0]{0}) custom-call(f32[16,64,64,64,512]{3,2,1,4,0} %copy, f32[1,1,1,256,128]{2,1,0,3,4} %copy.1), window={size=1x1x1}, dim_labels=b012f_012io->b012f, feature_group_count=2, custom_call_target="__cudnn$convForward", metadata={op_type="Conv3D" op_name="Conv3D" source_file="/home/ssh/.local/lib/python3.8/site-packages/keras/layers/convolutional/base_conv.py" source_line=225}, backend_config="{\"conv_result_scale\":1,\"activation_mode\":\"0\",\"side_input_scale\":0}"

Original error: UNKNOWN: CUDNN_STATUS_NOT_SUPPORTED
in tensorflow/stream_executor/cuda/cuda_dnn.cc(3520): 'op' CUDNN_BACKEND_OPERATION: cudnnFinalize Failed

To ignore this failure and try to use a fallback algorithm (which may have suboptimal performance), use XLA_FLAGS=--xla_gpu_strict_conv_algorithm_picker=false.  Please also file a bug for the root cause of failing autotuning.
Traceback (most recent call last):
  File "xla_test.py", line 12, in <module>
    output = conv_layer(layer_input)
  File "/home/ssh/.local/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/ssh/.local/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnknownError: Exception encountered when calling layer "conv3d" (type Conv3D).

Failed to determine best cudnn convolution algorithm for:
%cudnn-conv = (f32[16,64,64,64,128]{3,2,1,4,0}, u8[0]{0}) custom-call(f32[16,64,64,64,512]{3,2,1,4,0} %copy, f32[1,1,1,256,128]{2,1,0,3,4} %copy.1), window={size=1x1x1}, dim_labels=b012f_012io->b012f, feature_group_count=2, custom_call_target="__cudnn$convForward", metadata={op_type="Conv3D" op_name="Conv3D" source_file="/home/ssh/.local/lib/python3.8/site-packages/keras/layers/convolutional/base_conv.py" source_line=225}, backend_config="{\"conv_result_scale\":1,\"activation_mode\":\"0\",\"side_input_scale\":0}"

Original error: UNKNOWN: CUDNN_STATUS_NOT_SUPPORTED
in tensorflow/stream_executor/cuda/cuda_dnn.cc(3520): 'op' CUDNN_BACKEND_OPERATION: cudnnFinalize Failed

To ignore this failure and try to use a fallback algorithm (which may have suboptimal performance), use XLA_FLAGS=--xla_gpu_strict_conv_algorithm_picker=false.  Please also file a bug for the root cause of failing autotuning. [Op:__inference__jit_compiled_convolution_op_28]

Call arguments received by layer "conv3d" (type Conv3D):
  • inputs=tf.Tensor(shape=(16, 64, 64, 64, 512), dtype=float32)
```

**Comment by tilakrayal** [comment]
@dan-kazbek,
Looks like this is an issue which is related to Keras. So, could you please raise the issue in the [Keras-team/Keras](https://github.com/keras-team/keras/issues) repo for the quick resolution. Thank you!
