### ISSUE TITLE
Error calc. gradient? ValueError: None values not supported.

### ISSUE THREAD

**Issue by davidz3ng** [tensorflow/tensorflow#7930]
```
Traceback (most recent call last):
  File "cnn_mnist.py", line 140, in <module>
    adv_x = fgsm(batch_xs[0], y_conv, 0.3)
  File "cnn_mnist.py", line 43, in fgsm
    signed_grad = tf.sign(grad)
  File "C:\Users\soone\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\math_ops.py", line 452, in sign
    return gen_math_ops.sign(x, name=name)
  File "C:\Users\soone\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 2447, in sign
    result = _op_def_lib.apply_op("Sign", x=x, name=name)
  File "C:\Users\soone\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 504, in apply_op
    values, as_ref=input_arg.is_ref).dtype.name
  File "C:\Users\soone\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 716, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\soone\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "C:\Users\soone\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "C:\Users\soone\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 360, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.
```

Hi guys. I'm new to tensorflow and is trying to work on a project for creating adversarial samples for fooling an MNIST classifier. 

I found there was a fast gradient sign method and I tried to implement this in my code. However whenever I try to calculate the gradient I would always get "None values" even though I'm sure all the weights are loaded properly. 

Any help is appreciated. Thank you!

**Comment by rvijay1234** [comment]
Were you able to solve it? I am facing the same problem

**Comment by davidz3ng** [comment]
I believe I solved the issue by passing the placeholder X instead of batch_xs[0]
