### ISSUE TITLE
Tensorflow Build for Alpine on Multiple Architectures

### ISSUE THREAD

**Issue by els8482** [tensorflow/tensorflow#79327]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.5.0

### Custom code

No

### OS platform and distribution

Linux Alpine 3.18

### Python version

3.11.10-r1

### Bazel version

6.5.0

### GCC/compiler version

12.2.1_git20220924-r10

### Current behavior?

Expected behavior: Successful build.
Actual behavior: A python related error is printed to the console and the build fails.

I'm trying to build Tensorflow 2.15.0 on Alpine Linux 3.18. My objective is to build Alpine compatible wheels for x86 and Arm64.

To do this I plan to dow a build inside docker:
1/ Install Python 3.11.10-r1, along with any dependencies,
2/ Download Bazel 6.5.0 , do a bootstrap build, using scripts/bootstrap/compile.sh,
3/ Trigger the Tensorflow build using Bazel,
4/ Export the wheel that has been built.

The first two steps are working fine, however I'm getting an error that I don't understand from Bazel when building Tensorflow.

From what I understand Bazel bunks down to system processes for the python components, so I have verified that the packages that it appears to be failing on are available on Alpine by downloading and installing them outside of Bazel.

I would be grateful if anyone could help me with the following questions:
a) Increase the debug output from Bazel,
b) Explain how Bazel and Tensorflow specifically uses pipy,
c) And hence explain the error above?

Any help would be gratefully received.
Bryan

### Standalone code to reproduce the issue

```shell
FROM docker-default-virtual.health.artifactory.tio.systems/core-container-alpine318:latest

RUN cat > /etc/apk/repositories <<EOF
https://dl-cdn.alpinelinux.org/alpine/v$(cut -d'.' -f1,2 /etc/alpine-release)/main/
https://dl-cdn.alpinelinux.org/alpine/v$(cut -d'.' -f1,2 /etc/alpine-release)/community/
EOF

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk
ENV LOCAL_RESOURCES=2048,.5,1.0
ENV BAZEL_VERSION=6.5.0
RUN apk add --no-cache python3 python3-tkinter py3-numpy py3-numpy-f2py freetype libpng libjpeg-turbo imagemagick graphviz git

RUN apk add --no-cache --virtual=.build-deps \
        bash \
        cmake \
        curl \
        freetype-dev \
        g++ \
        libjpeg-turbo-dev \
        libpng-dev \
        linux-headers \
        make \
        musl-dev \
        openblas-dev \
        openjdk17 \
        patch \
        perl \
        python3-dev \
        py3-numpy-dev \
        rsync \
        sed \
        swig \
        zip \
        py3-pip \
        clang \
    && cd /tmp \
    && pip3 install --no-cache-dir wheel

RUN ls /usr/lib/jvm/

ENV UNZIP_DISABLE_ZIPBOMB_DETECTION=TRUE

# Bazel download
RUN curl -SLO https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-dist.zip \
    && mkdir bazel-${BAZEL_VERSION} \
    && unzip -qd bazel-${BAZEL_VERSION} bazel-${BAZEL_VERSION}-dist.zip

ENV BAZEL_DEBUG_JAVA_COMPILATION=true
ENV BAZEL_BOOTSTRAP_STARTUP_OPTIONS=""
ENV EXTRA_BAZEL_ARGS="--tool_java_runtime_version=local_jdk"

# Bazel install
RUN cd bazel-${BAZEL_VERSION} \
    && sed -i -e 's/-classpath/-J-Xmx8192m -J-Xms128m -classpath/g' scripts/bootstrap/compile.sh \
    && sed -i -e 's/-jar/--add-opens java.base\/java.lang=ALL-UNNAMED -jar/g' scripts/bootstrap/compile.sh \
    && bash compile.sh \
    && cp -p output/bazel /usr/bin/

# Download Tensorflow
ENV TENSORFLOW_VERSION=2.15.0
RUN cd /tmp \
    && curl -SL https://github.com/tensorflow/tensorflow/archive/v${TENSORFLOW_VERSION}.tar.gz \
        | tar xzf -
        
RUN apk add --no-cache hdf5-dev \
    && pip install --upgrade certifi packaging opt-einsum keras tensorflow_estimator \
    && which python \
    && which python3 \
    && ls -R /root/.cache/

RUN pip install astunparse

# Build Tensorflow
RUN cd /tmp/tensorflow-${TENSORFLOW_VERSION} \
    && : musl-libc does not have "secure_getenv" function \
    && export PYTHON_BIN_PATH="$(which python)" \
    && export TF_PYTHON_VERSION="$(${PYTHON_BIN_PATH} --version | sed -E -e 's/Python //' -e 's/.[0-9]+//')" \
    #&& sed -i -e '/JEMALLOC_HAVE_SECURE_GETENV/d' third_party/jemalloc.BUILD \
    #&& sed -i -e '/define TF_GENERATE_BACKTRACE/d' tensorflow/core/platform/default/stacktrace.h \
    #&& sed -i -e '/define TF_GENERATE_STACKTRACE/d' tensorflow/core/platform/stacktrace_handler.cc \
    #&& sed -i -e 's/workspace(name = "org_tensorflow")/workspace(name = "org_tensorflow")\n\nload("@bazel_tools\/\/tools\/build_defs\/repo:http.bzl", "http_archive")/g' WORKSPACE \
    && PYTHON_LIB_PATH=/usr/lib/python${TF_PYTHON_VERSION}/site-packages \
        CC_OPT_FLAGS="-march=native" \
        TF_NEED_JEMALLOC=1 \
        TF_NEED_GCP=0 \
        TF_NEED_HDFS=0 \
        TF_NEED_S3=0 \
        TF_ENABLE_XLA=0 \
        TF_NEED_GDR=0 \
        TF_NEED_VERBS=0 \
        TF_NEED_OPENCL=0 \
        TF_NEED_CUDA=0 \
        TF_NEED_MPI=0 \
        bash configure

RUN export PYTHON_BIN_PATH="$(which python)" \
    && export TF_PYTHON_VERSION="$(${PYTHON_BIN_PATH} --version | sed -E -e 's/Python //' -e 's/.[0-9]+//')" \
    &&cd /tmp/tensorflow-${TENSORFLOW_VERSION} \
    && bazel clean --expunge \
    && bazel build -c opt --define=no_tensorflow_py_deps=true --verbose_failures //tensorflow/tools/pip_package:build_pip_package

RUN cd /tmp/tensorflow-${TENSORFLOW_VERSION} \
    && ./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg

RUN cp /tmp/tensorflow_pkg/tensorflow-${TENSORFLOW_VERSION}-cp36-cp36m-linux_x86_64.whl /root

# Make sure it's built properly
RUN pip3 install --no-cache-dir /root/tensorflow-${TENSORFLOW_VERSION}-cp36-cp36m-linux_x86_64.whl \
    && python3 -c 'import tensorflow'

#RUN python3 -c 'import tensorflow as tf; print("TensorFlow version:", tf.__version__)'
```

### Relevant log output

```shell
00:21:54  #15 54.60 Analyzing: target //tensorflow/tools/pip_package:build_pip_package (129 packages loaded, 431 targets configured)
00:21:54  #15 55.31 INFO: Repository pypi_packaging instantiated at:
00:21:54  #15 55.31   /tmp/tensorflow-2.15.0/WORKSPACE:70:13: in <toplevel>
00:21:54  #15 55.31   /root/.cache/bazel/_bazel_root/96fc12a8fd07b4bb0604d61746db3a5b/external/pypi/requirements.bzl:49:20: in install_deps
00:21:54  #15 55.31 Repository rule whl_library defined at:
00:21:54  #15 55.31   /root/.cache/bazel/_bazel_root/96fc12a8fd07b4bb0604d61746db3a5b/external/rules_python/python/pip_install/pip_repository.bzl:697:30: in <toplevel>
00:21:54  #15 55.33 ERROR: An error occurred during the fetch of repository 'pypi_packaging':
00:21:54  #15 55.33    Traceback (most recent call last):
00:21:54  #15 55.33 	File "/root/.cache/bazel/_bazel_root/96fc12a8fd07b4bb0604d61746db3a5b/external/rules_python/python/pip_install/pip_repository.bzl", line 596, column 13, in _whl_library_impl
00:21:54  #15 55.33 		fail("whl_library %s failed: %s (%s) error code: '%s'" % (rctx.attr.name, result.stdout, result.stderr, result.return_code))
00:21:54  #15 55.33 Error in fail: whl_library pypi_packaging failed:  (src/main/tools/process-wrapper-legacy.cc:80: "execvp(/root/.cache/bazel/_bazel_root/96fc12a8fd07b4bb0604d61746db3a5b/external/python_x86_64-unknown-linux-gnu/bin/python3, ...)": No such file or directory
00:21:54  #15 55.33 ) error code: '1'
00:21:54  #15 55.33 ERROR: /tmp/tensorflow-2.15.0/WORKSPACE:70:13: fetching whl_library rule //external:pypi_packaging: Traceback (most recent call last):
00:21:54  #15 55.33 	File "/root/.cache/bazel/_bazel_root/96fc12a8fd07b4bb0604d61746db3a5b/external/rules_python/python/pip_install/pip_repository.bzl", line 596, column 13, in _whl_library_impl
00:21:54  #15 55.33 		fail("whl_library %s failed: %s (%s) error code: '%s'" % (rctx.attr.name, result.stdout, result.stderr, result.return_code))
00:21:54  #15 55.33 Error in fail: whl_library pypi_packaging failed:  (src/main/tools/process-wrapper-legacy.cc:80: "execvp(/root/.cache/bazel/_bazel_root/96fc12a8fd07b4bb0604d61746db3a5b/external/python_x86_64-unknown-linux-gnu/bin/python3, ...)": No such file or directory
00:21:54  #15 55.33 ) error code: '1'
00:21:54  #15 55.33 INFO: Repository org_brotli instantiated at:
00:21:54  #15 55.33   /tmp/tensorflow-2.15.0/WORKSPACE:84:14: in <toplevel>
00:21:54  #15 55.33   /tmp/tensorflow-2.15.0/tensorflow/workspace2.bzl:928:21: in workspace
00:21:54  #15 55.33   /tmp/tensorflow-2.15.0/tensorflow/workspace2.bzl:874:20: in _tf_repositories
00:21:54  #15 55.33   /tmp/tensorflow-2.15.0/third_party/repo.bzl:136:21: in tf_http_archive
00:21:54  #15 55.33 Repository rule _tf_http_archive defined at:
00:21:54  #15 55.33   /tmp/tensorflow-2.15.0/third_party/repo.bzl:89:35: in <toplevel>
00:21:54  #15 55.33 INFO: Repository stablehlo instantiated at:
00:21:54  #15 55.33   /tmp/tensorflow-2.15.0/WORKSPACE:84:14: in <toplevel>
00:21:54  #15 55.33   /tmp/tensorflow-2.15.0/tensorflow/workspace2.bzl:921:28: in workspace
00:21:54  #15 55.33   /tmp/tensorflow-2.15.0/tensorflow/workspace2.bzl:88:14: in _initialize_third_party
00:21:54  #15 55.33   /tmp/tensorflow-2.15.0/third_party/stablehlo/workspace.bzl:11:20: in repo
00:21:54  #15 55.33   /tmp/tensorflow-2.15.0/third_party/repo.bzl:136:21: in tf_http_archive
00:21:54  #15 55.33 Repository rule _tf_http_archive defined at:
00:21:54  #15 55.33   /tmp/tensorflow-2.15.0/third_party/repo.bzl:89:35: in <toplevel>
00:21:54  #15 55.38 INFO: Repository com_google_absl instantiated at:
00:21:54  #15 55.38   /tmp/tensorflow-2.15.0/WORKSPACE:84:14: in <toplevel>
00:21:54  #15 55.38   /tmp/tensorflow-2.15.0/tensorflow/workspace2.bzl:921:28: in workspace
00:21:54  #15 55.38   /tmp/tensorflow-2.15.0/tensorflow/workspace2.bzl:63:9: in _initialize_third_party
00:21:54  #15 55.38   /tmp/tensorflow-2.15.0/third_party/absl/workspace.bzl:39:20: in repo
00:21:54  #15 55.38   /tmp/tensorflow-2.15.0/third_party/repo.bzl:136:21: in tf_http_archive
00:21:54  #15 55.38 Repository rule _tf_http_archive defined at:
00:21:54  #15 55.38   /tmp/tensorflow-2.15.0/third_party/repo.bzl:89:35: in <toplevel>
00:21:54  #15 55.40 ERROR: /tmp/tensorflow-2.15.0/tensorflow/python/framework/BUILD:299:18: //tensorflow/python/framework:framework depends on @pypi_packaging//:pkg in repository @pypi_packaging which failed to fetch. no such package '@pypi_packaging//': whl_library pypi_packaging failed:  (src/main/tools/process-wrapper-legacy.cc:80: "execvp(/root/.cache/bazel/_bazel_root/96fc12a8fd07b4bb0604d61746db3a5b/external/python_x86_64-unknown-linux-gnu/bin/python3, ...)": No such file or directory
00:21:54  #15 55.40 ) error code: '1'
00:21:54  #15 55.43 ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: 
00:21:55  #15 55.46 INFO: Elapsed time: 51.759s
00:21:55  #15 55.46 INFO: 0 processes.
00:21:55  #15 55.46 FAILED: Build did NOT complete successfully (147 packages loaded, 515 targets configured)
00:22:03  #15 ERROR: process "/bin/sh -c export PYTHON_BIN_PATH=\"$(which python)\"     && export TF_PYTHON_VERSION=\"$(${PYTHON_BIN_PATH} --version | sed -E -e 's/Python //' -e 's/.[0-9]+//')\"     &&cd /tmp/tensorflow-${TENSORFLOW_VERSION}     && bazel clean --expunge     && bazel build -c opt --define=no_tensorflow_py_deps=true --verbose_failures //tensorflow/tools/pip_package:build_pip_package" did not complete successfully: exit code: 1
00:22:03  ------
00:22:03   > [12/15] RUN export PYTHON_BIN_PATH="$(which python)"     && export TF_PYTHON_VERSION="$(${PYTHON_BIN_PATH} --version | sed -E -e 's/Python //' -e 's/.[0-9]+//')"     &&cd /tmp/tensorflow-2.15.0     && bazel clean --expunge     && bazel build -c opt --define=no_tensorflow_py_deps=true --verbose_failures //tensorflow/tools/pip_package:build_pip_package:
00:22:03  55.38   /tmp/tensorflow-2.15.0/third_party/absl/workspace.bzl:39:20: in repo
00:22:03  55.38   /tmp/tensorflow-2.15.0/third_party/repo.bzl:136:21: in tf_http_archive
00:22:03  55.38 Repository rule _tf_http_archive defined at:
00:22:03  55.38   /tmp/tensorflow-2.15.0/third_party/repo.bzl:89:35: in <toplevel>
00:22:03  55.40 ERROR: /tmp/tensorflow-2.15.0/tensorflow/python/framework/BUILD:299:18: //tensorflow/python/framework:framework depends on @pypi_packaging//:pkg in repository @pypi_packaging which failed to fetch. no such package '@pypi_packaging//': whl_library pypi_packaging failed:  (src/main/tools/process-wrapper-legacy.cc:80: "execvp(/root/.cache/bazel/_bazel_root/96fc12a8fd07b4bb0604d61746db3a5b/external/python_x86_64-unknown-linux-gnu/bin/python3, ...)": No such file or directory
00:22:03  55.40 ) error code: '1'
00:22:03  55.43 ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: 
00:22:03  55.46 INFO: Elapsed time: 51.759s
00:22:03  55.46 INFO: 0 processes.
00:22:03  55.46 FAILED: Build did NOT complete successfully (147 packages loaded, 515 targets configured)
00:22:03  ------
00:22:03  WARNING: No output specified with docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load
00:22:03  Dockerfile:109
00:22:03  --------------------
00:22:03   108 |     # --local_resources ${LOCAL_RESOURCES}
00:22:03   109 | >>> RUN export PYTHON_BIN_PATH="$(which python)" \
00:22:03   110 | >>>     && export TF_PYTHON_VERSION="$(${PYTHON_BIN_PATH} --version | sed -E -e 's/Python //' -e 's/.[0-9]+//')" \
00:22:03   111 | >>>     &&cd /tmp/tensorflow-${TENSORFLOW_VERSION} \
00:22:03   112 | >>>     && bazel clean --expunge \
00:22:03   113 | >>>     && bazel build -c opt --define=no_tensorflow_py_deps=true --verbose_failures //tensorflow/tools/pip_package:build_pip_package
00:22:03   114 |     
00:22:03  --------------------
00:22:03  ERROR: failed to solve: process "/bin/sh -c export PYTHON_BIN_PATH=\"$(which python)\"     && export TF_PYTHON_VERSION=\"$(${PYTHON_BIN_PATH} --version | sed -E -e 's/Python //' -e 's/.[0-9]+//')\"     &&cd /tmp/tensorflow-${TENSORFLOW_VERSION}     && bazel clean --expunge     && bazel build -c opt --define=no_tensorflow_py_deps=true --verbose_failures //tensorflow/tools/pip_package:build_pip_package" did not complete successfully: exit code: 1
```

**Comment by tilakrayal** [comment]
@els8482,
I request you to take a look at this https://github.com/tensorflow/tensorflow/issues/62899 where a similar issue has been proposed and it is still open. Also I request to follow the similar issue which has been proposed to have the updates on the similar issue. Thank you!
