### ISSUE TITLE
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by BaseMax** [tensorflow/tensorflow#79362]
My OS is Windows server which but this is a VM on a VDS - big server.

```
soft Windows [Version 10.0.20348.2762]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Administrator>cd Desktop

C:\Users\Administrator\Desktop>cd max

C:\Users\Administrator\Desktop\MAX>dir
 Volume in drive C has no label.
 Volume Serial Number is BE46-6828

 Directory of C:\Users\Administrator\Desktop\MAX

11/04/2024  02:49 PM    <DIR>          .
11/04/2024  02:15 PM    <DIR>          ..
07/19/2024  04:17 PM             8,187 api.py
07/19/2024  02:49 PM         5,282,219 epoch-100-new-model.keras
07/19/2024  04:30 PM               191 gunicorn_config.py
10/02/2024  11:05 AM    <DIR>          myenv
11/04/2024  02:49 PM    <DIR>          old
10/30/2024  09:33 AM                 0 python
07/19/2024  04:28 PM                23 README.md
10/03/2024  12:26 AM               787 requirements.txt
10/03/2024  01:24 AM               509 run_server.py
11/04/2024  02:03 PM    <DIR>          temp_images
10/03/2024  12:24 AM    <DIR>          tensorflow-env
10/03/2024  12:24 AM    <DIR>          tensorflow-envsource
11/04/2024  02:03 PM    <DIR>          __pycache__
               7 File(s)      5,291,916 bytes
               8 Dir(s)  35,836,018,688 bytes free

C:\Users\Administrator\Desktop\MAX>python api.py
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 70, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\MAX\api.py", line 2, in <module>
    import keras
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\__init__.py", line 4, in <module>
    from keras.api import DTypePolicy
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\api\__init__.py", line 8, in <module>
    from keras.api import activations
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\api\activations\__init__.py", line 7, in <module>
    from keras.src.activations import deserialize
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\__init__.py", line 1, in <module>
    from keras.src import activations
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\activations\__init__.py", line 3, in <module>
    from keras.src.activations.activations import elu
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\activations\activations.py", line 1, in <module>
    from keras.src import backend
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\backend\__init__.py", line 9, in <module>
    from keras.src.backend.common.dtypes import result_type
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\backend\common\__init__.py", line 2, in <module>
    from keras.src.backend.common.dtypes import result_type
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\backend\common\dtypes.py", line 5, in <module>
    from keras.src.backend.common.variables import standardize_dtype
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\backend\common\variables.py", line 11, in <module>
    from keras.src.utils.module_utils import tensorflow as tf
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\utils\__init__.py", line 1, in <module>
    from keras.src.utils.audio_dataset_utils import audio_dataset_from_directory
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\utils\audio_dataset_utils.py", line 4, in <module>
    from keras.src.utils import dataset_utils
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\utils\dataset_utils.py", line 9, in <module>
    from keras.src import tree
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\tree\__init__.py", line 1, in <module>
    from keras.src.tree.tree_api import assert_same_structure
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\tree\tree_api.py", line 6, in <module>
    from keras.src.tree import optree_impl as tree_impl
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\tree\optree_impl.py", line 17, in <module>
    from tensorflow.python.trackable.data_structures import ListWrapper
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\__init__.py", line 38, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 85, in <module>
    raise ImportError(
ImportError: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 70, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors for some common causes and solutions.
If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.

C:\Users\Administrator\Desktop\MAX>myenv\Scripts\activate

(myenv) C:\Users\Administrator\Desktop\MAX>python api.py
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 70, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\MAX\api.py", line 2, in <module>
    import keras
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\__init__.py", line 4, in <module>
    from keras.api import DTypePolicy
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\api\__init__.py", line 8, in <module>
    from keras.api import activations
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\api\activations\__init__.py", line 7, in <module>
    from keras.src.activations import deserialize
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\__init__.py", line 1, in <module>
    from keras.src import activations
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\activations\__init__.py", line 3, in <module>
    from keras.src.activations.activations import elu
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\activations\activations.py", line 1, in <module>
    from keras.src import backend
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\backend\__init__.py", line 9, in <module>
    from keras.src.backend.common.dtypes import result_type
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\backend\common\__init__.py", line 2, in <module>
    from keras.src.backend.common.dtypes import result_type
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\backend\common\dtypes.py", line 5, in <module>
    from keras.src.backend.common.variables import standardize_dtype
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\backend\common\variables.py", line 11, in <module>
    from keras.src.utils.module_utils import tensorflow as tf
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\utils\__init__.py", line 1, in <module>
    from keras.src.utils.audio_dataset_utils import audio_dataset_from_directory
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\utils\audio_dataset_utils.py", line 4, in <module>
    from keras.src.utils import dataset_utils
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\utils\dataset_utils.py", line 9, in <module>
    from keras.src import tree
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\tree\__init__.py", line 1, in <module>
    from keras.src.tree.tree_api import assert_same_structure
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\tree\tree_api.py", line 6, in <module>
    from keras.src.tree import optree_impl as tree_impl
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\tree\optree_impl.py", line 17, in <module>
    from tensorflow.python.trackable.data_structures import ListWrapper
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\__init__.py", line 38, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 85, in <module>
    raise ImportError(
ImportError: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 70, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors for some common causes and solutions.
If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.

(myenv) C:\Users\Administrator\Desktop\MAX>
(myenv) C:\Users\Administrator\Desktop\MAX>
(myenv) C:\Users\Administrator\Desktop\MAX>python run_server.py
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 70, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\MAX\run_server.py", line 1, in <module>
    import api
  File "C:\Users\Administrator\Desktop\MAX\api.py", line 2, in <module>
    import keras
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\__init__.py", line 4, in <module>
    from keras.api import DTypePolicy
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\api\__init__.py", line 8, in <module>
    from keras.api import activations
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\api\activations\__init__.py", line 7, in <module>
    from keras.src.activations import deserialize
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\__init__.py", line 1, in <module>
    from keras.src import activations
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\activations\__init__.py", line 3, in <module>
    from keras.src.activations.activations import elu
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\activations\activations.py", line 1, in <module>
    from keras.src import backend
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\backend\__init__.py", line 9, in <module>
    from keras.src.backend.common.dtypes import result_type
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\backend\common\__init__.py", line 2, in <module>
    from keras.src.backend.common.dtypes import result_type
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\backend\common\dtypes.py", line 5, in <module>
    from keras.src.backend.common.variables import standardize_dtype
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\backend\common\variables.py", line 11, in <module>
    from keras.src.utils.module_utils import tensorflow as tf
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\utils\__init__.py", line 1, in <module>
    from keras.src.utils.audio_dataset_utils import audio_dataset_from_directory
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\utils\audio_dataset_utils.py", line 4, in <module>
    from keras.src.utils import dataset_utils
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\utils\dataset_utils.py", line 9, in <module>
    from keras.src import tree
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\tree\__init__.py", line 1, in <module>
    from keras.src.tree.tree_api import assert_same_structure
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\tree\tree_api.py", line 6, in <module>
    from keras.src.tree import optree_impl as tree_impl
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\tree\optree_impl.py", line 17, in <module>
    from tensorflow.python.trackable.data_structures import ListWrapper
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\__init__.py", line 38, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 85, in <module>
    raise ImportError(
ImportError: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 70, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors for some common causes and solutions.
If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.
```

```
(myenv) C:\Users\Administrator\Desktop\MAX>python --version
Python 3.9.0
```

**Comment by tilakrayal** [comment]
@BaseMax,
Could you please provide the tensorflow and the compatible version which you are trying to install. Also there are at least 3 possible scenarios:

```python
- You need to install the MSVC 2019 redistributable
- Your CPU does not support AVX2 instructions
- Your CPU/Python is on 32 bits
- There is a library that is in a different location/not installed on your system that cannot be loaded.
```
https://github.com/tensorflow/tensorflow/issues/61887

Thank you!

**Comment by mihaimaruseac** [comment]
Duplicate of https://github.com/tensorflow/tensorflow/issues/19584. Please do a search before opening new issues. This is a very old issue and manifests because old PCs with Windows cannot load libraries needed by TF because they have very old architecture sets.

**Comment by Fayer0n** [comment]
Update the MSVC like this download link ：https://download.visualstudio.microsoft.com/download/pr/285b28c7-3cf9-47fb-9be8-01cf5323a8df/8F9FB1B3CFE6E5092CF1225ECD6659DAB7CE50B8BF935CB79BFEDE1F3C895240/VC_redist.x64.exe
