### ISSUE TITLE
tf.autodiff.ForwardAccumulator._watch(primal, tangent) erroneously refers to dtype.is_floating which does not exist for a Keras layer.

### ISSUE THREAD

**Issue by mikefairbank** [tensorflow/tensorflow#79523]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.17.0

### Custom code

No

### OS platform and distribution

Linux ubuntu 24.04

### Python version

3.12.3

### Current behavior?

The bug is that in tf.autodiff.ForwardAccumulator._watch(primal, tangent), it refers to the attribute primal.dtype.is_floating, but this causes a crash, as primal.dtype is now a string type variable, and so does not have the attribute "is_floating".

Here is the error message I see, from the standalone code below.

  File "/home/me/.local/lib/python3.12/site-packages/tensorflow/python/eager/forwardprop.py", line 411, in _watch
    if not primal.dtype.is_floating:
           ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'is_floating'

### Standalone code to reproduce the issue

```shell
import tensorflow as tf 
x = tf.constant([[2.0, 3.0], [1.0, 4.0]])
targets = tf.constant([[1.], [-1.]])
dense = tf.keras.layers.Dense(1)
dense.build([None, 2])
with tf.autodiff.ForwardAccumulator(
   primals=dense.kernel,
   tangents=tf.constant([[1.], [0.]])) as acc:
  loss = tf.reduce_sum((dense(x) - targets) ** 2.)
print(acc.jvp(loss))
```

**Comment by mikefairbank** [comment]
The standalone code I gave to reproduce this issue is the example code given at https://www.tensorflow.org/api_docs/python/tf/autodiff/ForwardAccumulator , so that code really should work.

**Comment by Venkat6871** [comment]
Hi **@mikefairbank** ,
Apologies for the delay, and thank you for raising your concern here. By default the colab notebook is using tensorflow v2.17 which contains keras3.0 which was causing the error. Could you please try to import keras2.0 with the below commands.
```
!pip install tf-keras

import tf_keras as keras
```
Also I have modified some steps and then the code was executed without error/fail. Kindly find the gist of it [here](https://colab.sandbox.google.com/gist/Venkat6871/7444fac2775c239a2c07edf7faae4cea/79523_tf-2-18-0-v.ipynb).
Thank you!

**Comment by mikefairbank** [comment]
Thank you for looking into this.  The fix you suggested works well for me.  I've switched to tf-keras from keras, and pip upgraded my tensorflow versions to 2.18 now (for both tensorflow and tf-keras).

There still seems to be the same bug though affecting tf.keras:

  File "/home/me/.local/lib/python3.12/site-packages/tensorflow/python/eager/forwardprop.py", line 411, in _watch
    if not primal.dtype.is_floating:
           ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'is_floating'

Is that something that can/should be fixed?  Should the user just _know_ to use tf_keras and not tf.keras?  That doesn't seem right!

**Comment by mikefairbank** [comment]
Also, the example code in https://www.tensorflow.org/api_docs/python/tf/autodiff/ForwardAccumulator will need changing to use tf-keras instead of tf.keras.  I think the needed solution is to fix forwardprop.py, line 411 so that it can handle string dtypes.

**Comment by MrChike** [comment]
So this task has been closed then.

**Comment by mikefairbank** [comment]
Please don't close it.  I think:
1.  the example code in https://www.tensorflow.org/api_docs/python/tf/autodiff/ForwardAccumulator will need changing to use tf-keras instead of tf.keras
2. The code in tf.keras has this bug still: 

File "/home/me/.local/lib/python3.12/site-packages/tensorflow/python/eager/forwardprop.py", line 411, in _watch
if not primal.dtype.is_floating:
^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'is_floating'

We can work around this by switching tf-keras for tf.keras, but I'm not sure that is the permanent solution to this problem.

**Comment by gaikwadrahul8** [comment]
Hi, @mikefairbank
I apologize for the delayed response, It seems like this issue is happening because of [TensorFlow + Keras 2 backwards compatibility](https://keras.io/getting_started/) From TensorFlow 2.0 to TensorFlow 2.15 (included), doing `pip install tensorflow` will also install the corresponding version of Keras 2 – for instance, `pip install tensorflow==2.14.0` will install `keras==2.14.0`. That version of Keras is then available via both import keras and from tensorflow import keras (the [tf.keras](https://www.tensorflow.org/api_docs/python/tf/keras) namespace).

Starting with `TensorFlow 2.16`, doing `pip install tensorflow` will install `Keras 3`. When you have TensorFlow >= 2.16 and Keras 3, then by default from tensorflow import keras ([tf.keras](https://www.tensorflow.org/api_docs/python/tf/keras)) will be Keras 3.

Meanwhile, the legacy Keras 2 package is still being released regularly and is available on PyPI as tf_keras (or equivalently tf-keras – note that - and _ are equivalent in PyPI package names). To use it, you can install it via pip install tf_keras then import it via import tf_keras as keras.

Should you want [tf.keras](https://www.tensorflow.org/api_docs/python/tf/keras) to stay on Keras 2 after upgrading to TensorFlow 2.16+, you can configure your TensorFlow installation so that [tf.keras](https://www.tensorflow.org/api_docs/python/tf/keras) points to tf_keras. To achieve this:

1. Make sure to install `tf_keras`. Note that TensorFlow does not install it by default.
2. Export the environment variable `TF_USE_LEGACY_KERAS=1`.

I have submitted PR to update example https://github.com/tensorflow/tensorflow/pull/83318

Thank you for your cooperation and patience.

**Comment by mihaimaruseac** [comment]
From my understanding of the comments posted here, the same error occurs when using either `keras` or `tf-keras`, right?

**Comment by gaikwadrahul8** [comment]
Hi, @mihaimaruseac 
Today, I have tried different combinations of TensorFlow versions and Keras versions along with standalone installing Keras without installing the `tf_keras` and setting up environment variable `TF_USE_LEGACY_KERAS=1 ` it is throwing this error message `AttributeError: 'str' object has no attribute 'is_floating'` for examples mentioned for [tf.autodiff.ForwardAccumulator](https://www.tensorflow.org/api_docs/python/tf/autodiff/ForwardAccumulator) but when I install `tf_keras` manually and setting up environment variable `TF_USE_LEGACY_KERAS=1 ` the examples are working as expected please refer this [gist-file](https://colab.research.google.com/gist/gaikwadrahul8/d1a6b2b563eb63a0ceb8c1fa260196a0/testing-tf-core-issue-79523.ipynb) where I did all the experiments with different versions of TensorFlow and Keras even I checked by installing Keras package standalone but examples did not work as expected

If I am not wrong examples mentioned for [tf.autodiff.ForwardAccumulator](https://www.tensorflow.org/api_docs/python/tf/autodiff/ForwardAccumulator) are working with `Keras 2` but it is not working with `Keras 3 ` so should we proceed with making the [tf.autodiff.ForwardAccumulator](https://www.tensorflow.org/api_docs/python/tf/autodiff/ForwardAccumulator) API compatible with Keras 3 or are the below proposed changes sufficient for the time being? 

I have missed something here please let me know. Thank you

```
>>> # Please install pip install tf_keras before executing below examples
>>> import os
>>> import numpy as np
>>> import tensorflow as tf
>>> os.environ["TF_USE_LEGACY_KERAS"] = "1"
```

**Comment by mihaimaruseac** [comment]
I tried it myself. First, setup:

```bash
[...]$ pip list
Package                      Version
---------------------------- -------------------
absl-py                      2.1.0
astunparse                   1.6.3
certifi                      2024.12.14
charset-normalizer           3.4.0
flatbuffers                  24.3.25
gast                         0.6.0
google-pasta                 0.2.0
grpcio                       1.68.1
h5py                         3.12.1
idna                         3.10
keras-nightly                3.7.0.dev2024122303
libclang                     18.1.1
Markdown                     3.7
markdown-it-py               3.0.0
MarkupSafe                   3.0.2
mdurl                        0.1.2
ml_dtypes                    0.5.0
namex                        0.0.8
numpy                        2.1.3
opt_einsum                   3.4.0
optree                       0.13.1
packaging                    24.2
pip                          24.0
protobuf                     5.29.2
Pygments                     2.18.0
requests                     2.32.3
rich                         13.9.4
setuptools                   70.3.0
six                          1.17.0
tb-nightly                   2.19.0a20241223
tensorboard-data-server      0.7.2
tensorflow-io-gcs-filesystem 0.37.1
termcolor                    2.5.0
tf_nightly                   2.19.0.dev20241219
typing_extensions            4.12.2
urllib3                      2.3.0
Werkzeug                     3.1.3
wheel                        0.45.1
wrapt                        1.17.0
[...]$ echo ${TF_USE_LEGACY_KERAS:-unset}
unset
```

Then, reproduction

```python
>>> import tensorflow as tf 
2024-12-23 11:00:56.974298: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-12-23 11:00:56.978166: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-12-23 11:00:56.986610: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1734980457.003693 2169296 cuda_dnn.cc:8501] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1734980457.007630 2169296 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-12-23 11:00:57.021934: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
>>> x = tf.constant([[2.0, 3.0], [1.0, 4.0]])
E0000 00:00:1734980461.384182 2169296 cuda_executor.cc:1189] INTERNAL: CUDA Runtime error: Failed call to cudaGetRuntimeVersion: Error loading CUDA libraries. GPU will not be used.: Error loading CUDA libraries. GPU will not be used.
W0000 00:00:1734980461.386100 2169296 gpu_device.cc:2342] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
>>> targets = tf.constant([[1.], [-1.]])
>>> dense = tf.keras.layers.Dense(1)
>>> dense.build([None, 2])
>>> with tf.autodiff.ForwardAccumulator(primals=dense.kernel, tangents=tf.constant([[1.], [0.]])) as acc:
...   loss = tf.reduce_sum((dense(x) - targets) ** 2.)
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/tf/venv/lib/python3.11/site-packages/tensorflow/python/eager/forwardprop.py", line 372, in __init__
    self._watch(primals, tangents)
  File "/tmp/tf/venv/lib/python3.11/site-packages/tensorflow/python/eager/forwardprop.py", line 423, in _watch
    nest.map_structure(_watch, primals, tangents)
  File "/tmp/tf/venv/lib/python3.11/site-packages/tensorflow/python/util/nest.py", line 628, in map_structure
    return nest_util.map_structure(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tf/venv/lib/python3.11/site-packages/tensorflow/python/util/nest_util.py", line 1065, in map_structure
    return _tf_core_map_structure(func, *structure, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tf/venv/lib/python3.11/site-packages/tensorflow/python/util/nest_util.py", line 1105, in _tf_core_map_structure
    [func(*x) for x in entries],
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tf/venv/lib/python3.11/site-packages/tensorflow/python/util/nest_util.py", line 1105, in <listcomp>
    [func(*x) for x in entries],
     ^^^^^^^^
  File "/tmp/tf/venv/lib/python3.11/site-packages/tensorflow/python/eager/forwardprop.py", line 411, in _watch
    if not primal.dtype.is_floating:
           ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'is_floating'
```

Minimizing:

```python
>>> tf.autodiff.ForwardAccumulator(primals=dense.kernel, tangents=tf.constant([[1.], [0.]]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/tf/venv/lib/python3.11/site-packages/tensorflow/python/eager/forwardprop.py", line 372, in __init__
    self._watch(primals, tangents)
  File "/tmp/tf/venv/lib/python3.11/site-packages/tensorflow/python/eager/forwardprop.py", line 423, in _watch
    nest.map_structure(_watch, primals, tangents)
  File "/tmp/tf/venv/lib/python3.11/site-packages/tensorflow/python/util/nest.py", line 628, in map_structure
    return nest_util.map_structure(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tf/venv/lib/python3.11/site-packages/tensorflow/python/util/nest_util.py", line 1065, in map_structure
    return _tf_core_map_structure(func, *structure, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tf/venv/lib/python3.11/site-packages/tensorflow/python/util/nest_util.py", line 1105, in _tf_core_map_structure
    [func(*x) for x in entries],
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tf/venv/lib/python3.11/site-packages/tensorflow/python/util/nest_util.py", line 1105, in <listcomp>
    [func(*x) for x in entries],
     ^^^^^^^^
  File "/tmp/tf/venv/lib/python3.11/site-packages/tensorflow/python/eager/forwardprop.py", line 411, in _watch
    if not primal.dtype.is_floating:
           ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'is_floating'
```

Using only constants:

```python
>>> tf.autodiff.ForwardAccumulator(primals=tf.constant([[0.], [1.]]), tangents=tf.constant([[1.], [0.]]))
<tensorflow.python.eager.forwardprop.ForwardAccumulator object at 0x7faeb00ba150>
```

So, the issue is on the keras layer:

```python
>>> tf.constant([[0.], [1.]]).dtype
tf.float32
>>> dense.kernel.dtype
'float32'
```

We should make the code compatible with both TF-Keras and Keras 3.

**Comment by mihaimaruseac** [comment]
Now that the issue is isolated, installing `tf_keras-nightly` directly results in both keras versions being installed:

```console
[...]$ pip list | grep keras
keras-nightly                3.7.0.dev2024122303
tf_keras-nightly             2.19.0.dev2024122310
```

Testing

```python
[...]$ python
Python 3.11.9 (main, Jun 19 2024, 00:38:48) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf 
2024-12-23 11:10:20.719619: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-12-23 11:10:20.722685: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-12-23 11:10:20.731190: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1734981020.746389 2173405 cuda_dnn.cc:8501] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1734981020.750512 2173405 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-12-23 11:10:20.766911: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
>>> l = tf.keras.layers.Dense(1)
>>> l.build([None, 2])
E0000 00:00:1734981044.048778 2173405 cuda_executor.cc:1189] INTERNAL: CUDA Runtime error: Failed call to cudaGetRuntimeVersion: Error loading CUDA libraries. GPU will not be used.: Error loading CUDA libraries. GPU will not be used.
W0000 00:00:1734981044.050537 2173405 gpu_device.cc:2342] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
>>> l.kernel.dtype
'float32'
```

This is not good. Let's set the environment variable:

```python
[...]$ export TF_USE_LEGACY_KERAS=1
[...]$ python
Python 3.11.9 (main, Jun 19 2024, 00:38:48) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf 
2024-12-23 11:11:13.884706: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-12-23 11:11:13.887806: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-12-23 11:11:13.896277: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1734981073.910177 2173913 cuda_dnn.cc:8501] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1734981073.914621 2173913 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-12-23 11:11:13.928734: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
>>> l = tf.keras.layers.Dense(1)
>>> l.build([None, 2])
E0000 00:00:1734981083.268596 2173913 cuda_executor.cc:1189] INTERNAL: CUDA Runtime error: Failed call to cudaGetRuntimeVersion: Error loading CUDA libraries. GPU will not be used.: Error loading CUDA libraries. GPU will not be used.
W0000 00:00:1734981083.270463 2173913 gpu_device.cc:2342] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
>>> l.kernel.dtype
tf.float32
```

So, this should likely be a bug reported on Keras and what we can do for TF is to suggest to set the environment variable (in tutorial, I'm not sure we should do that in code since the code works perfect when not using Keras at all)
