### ISSUE TITLE
Problem running Convolutional.py

### ISSUE THREAD

**Issue by singhakshayraj** [tensorflow/tensorflow#796]
I am trying to run the convolutional.py through the tensorflow virtualenv i am getting an error as follows 
Traceback (most recent call last):
  File "convolutional.py", line 290, in <module>
    tf.app.run()
  File "/home/akshay/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "convolutional.py", line 121, in main
    train_data_filename = maybe_download('train-images-idx3-ubyte.gz')
  File "convolutional.py", line 56, in maybe_download
    os.mkdir(WORK_DIRECTORY)
OSError: [Errno 13] Permission denied: 'data'

I am getting this error even when i am running as super user.

**Comment by vincentvanhoucke** [comment]
You don't have permission to create a directory in your current working directory. We won't attempt to change that programmatically for you since it might have unintended consequences.

**Comment by singhakshayraj** [comment]
I tried changing the permissions,working now.
Thanks!

**Comment by druncat** [comment]
Hi,
Recently I tried to check tensorflow with : python -m tensorflow.models.image.mnist.convolutional.
And I get same error:

(tensorflowGPU)administrator@zsp515-6a:/home$ python -m tensorflow.models.image.mnist.convolutional
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/administrator/tensorflowGPU/lib/python2.7/site-packages/tensorflow/models/image/mnist/convolutional.py", line 316, in <module>
    tf.app.run()
  File "/home/administrator/tensorflowGPU/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/home/administrator/tensorflowGPU/lib/python2.7/site-packages/tensorflow/models/image/mnist/convolutional.py", line 122, in main
    train_data_filename = maybe_download('train-images-idx3-ubyte.gz')
  File "/home/administrator/tensorflowGPU/lib/python2.7/site-packages/tensorflow/models/image/mnist/convolutional.py", line 57, in maybe_download
    tf.gfile.MakeDirs(WORK_DIRECTORY)
  File "/home/administrator/tensorflowGPU/local/lib/python2.7/site-packages/tensorflow/python/platform/gfile.py", line 294, in MakeDirs
    os.makedirs(path, mode)
  File "/home/administrator/tensorflowGPU/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
**OSError: [Errno 13] Permission denied: 'data'**

What name of the folder ,current working directory, in this/my case?﻿
Thanks.

**Comment by vrv** [comment]
For now, I recommend cloning the git repository into another directory and running that version of the file.  I think we'd have to rewrite our tutorials and examples to not assume relative path otherwise.

**Comment by kchopra456** [comment]
Probably you are facing problem when a download request is made by the maybe_download function call in base.py file.

There is a conflict in the permissions of the temporary files and I myself couldn't work out a way to change the permissions, but was able to work around the problem.

Do the following...

 - Download the four .gz files of the MNIST data set from the link ( http://yann.lecun.com/exdb/mnist/ )
 - Then make a folder names MNIST_data (or your choice in your working directory/ site packages folder in the tensorflow\examples folder).
 - Directly copy paste the files into the folder.
 - Copy the address of the folder (it probably will be 
( C:\Python\Python35\Lib\site-packages\tensorflow\examples\tutorials\mnist\MNIST_data  ))
 - Change the "\" to "/" as "\" is used for escape characters, to access the folder locations.
 - Lastly, if you are following the tutorials, your call function would be **( mnist = input_data.read_data_sets("MNIST_data/", one_hot=True) )** ;
change the **"MNIST_data/"** parameter to your **folder location**. As in my case would be *( mnist = input_data.read_data_sets("C:/Python/Python35/Lib/site-packages/tensorflow/examples/tutorials/mnist/MNIST_data", one_hot=True) )*

Then it's all done.
Hope it works for you.
