### ISSUE TITLE
Configuration Error: --define PYTHON_BIN_PATH='C:/Users/LENOVO/AppData/Local/Programs/Python/Python313/python.exe' is not executable. Is it the python binary?

### ISSUE THREAD

**Issue by 6VastUniverse** [tensorflow/tensorflow#79757]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.6.0

### Custom code

Yes

### OS platform and distribution

Windows11 x64

### Python version

3.13.0

### Bazel version

3.7.2

### GCC/compiler version

14.2.0

### Current behavior?

```
bazel build --config=opt //tensorflow:tensorflow_cc.dll
INFO: Reading 'startup' options from d:\users\lenovo\desktop\tensorflow-master\.bazelrc: --output_user_root=D:/Users/LENOVO/Desktop/tensorflow-master/build-output
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=120
INFO: Reading rc options for 'build' from d:\users\lenovo\desktop\tensorflow-master\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=C:/Users/LENOVO/AppData/Local/Programs/Python/Python313/python.exe
INFO: Reading rc options for 'build' from d:\users\lenovo\desktop\tensorflow-master\.bazelrc:
  'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true
INFO: Reading rc options for 'build' from d:\users\lenovo\desktop\tensorflow-master\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=C:/Users/LENOVO/AppData/Local/Programs/Python/Python313/python.exe --action_env PYTHON_LIB_PATH=C:/Users/LENOVO/AppData/Local/Programs/Python/Python313/Lib/site-packages --python_path=C:/Users/LENOVO/AppData/Local/Programs/Python/Python313/python.exe --copt=/d2ReducedOptimizeHugeFunctions --host_copt=/d2ReducedOptimizeHugeFunctions --define=override_eigen_strong_inline=true
INFO: Found applicable config definition build:short_logs in file d:\users\lenovo\desktop\tensorflow-master\.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file d:\users\lenovo\desktop\tensorflow-master\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:opt in file d:\users\lenovo\desktop\tensorflow-master\.tf_configure.bazelrc: --copt=/arch:AVX --host_copt=/arch:AVX
INFO: Found applicable config definition build:windows in file d:\users\lenovo\desktop\tensorflow-master\.bazelrc: --copt=/W0 --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=/experimental:preprocessor --host_copt=/experimental:preprocessor --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --verbose_failures --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file d:\users\lenovo\desktop\tensorflow-master\.bazelrc: --define framework_shared_object=false
WARNING: Download from http://mirror.tensorflow.org/github.com/tensorflow/runtime/archive/b570a1921c9e55ac53c8972bd2bfd37cd0eb510d.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
DEBUG: D:/users/lenovo/desktop/tensorflow-master/build-output/ijcwdbxz/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
INFO: Repository local_execution_config_python instantiated at:
  D:/users/lenovo/desktop/tensorflow-master/WORKSPACE:15:14: in <toplevel>
  D:/users/lenovo/desktop/tensorflow-master/tensorflow/workspace2.bzl:1088:19: in workspace
  D:/users/lenovo/desktop/tensorflow-master/tensorflow/workspace2.bzl:85:27: in _tf_toolchains
  D:/users/lenovo/desktop/tensorflow-master/build-output/ijcwdbxz/external/tf_toolchains/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  D:/users/lenovo/desktop/tensorflow-master/build-output/ijcwdbxz/external/tf_toolchains/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  D:/users/lenovo/desktop/tensorflow-master/third_party/py/python_configure.bzl:275:41: in <toplevel>
INFO: Repository local_config_python instantiated at:
  D:/users/lenovo/desktop/tensorflow-master/WORKSPACE:15:14: in <toplevel>
  D:/users/lenovo/desktop/tensorflow-master/tensorflow/workspace2.bzl:1088:19: in workspace
  D:/users/lenovo/desktop/tensorflow-master/tensorflow/workspace2.bzl:95:21: in _tf_toolchains
Repository rule python_configure defined at:
  D:/users/lenovo/desktop/tensorflow-master/third_party/py/python_configure.bzl:294:35: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "D:/users/lenovo/desktop/tensorflow-master/third_party/py/python_configure.bzl", line 209, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "D:/users/lenovo/desktop/tensorflow-master/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
                auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
        File "D:/users/lenovo/desktop/tensorflow-master/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
                fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH='C:/Users/LENOVO/AppData/Local/Programs/Python/Python313/python.exe' is not executable. Is it the python binary?
INFO: Repository go_sdk instantiated at:
  D:/users/lenovo/desktop/tensorflow-master/WORKSPACE:23:14: in <toplevel>
  D:/users/lenovo/desktop/tensorflow-master/tensorflow/workspace0.bzl:120:20: in workspace
  D:/users/lenovo/desktop/tensorflow-master/build-output/ijcwdbxz/external/com_github_grpc_grpc/bazel/grpc_extra_deps.bzl:36:27: in grpc_extra_deps
  D:/users/lenovo/desktop/tensorflow-master/build-output/ijcwdbxz/external/io_bazel_rules_go/go/toolchain/toolchains.bzl:379:28: in go_register_toolchains
  D:/users/lenovo/desktop/tensorflow-master/build-output/ijcwdbxz/external/io_bazel_rules_go/go/private/sdk.bzl:65:21: in go_download_sdk
Repository rule _go_download_sdk defined at:
  D:/users/lenovo/desktop/tensorflow-master/build-output/ijcwdbxz/external/io_bazel_rules_go/go/private/sdk.bzl:53:35: in <toplevel>
INFO: Repository rules_java instantiated at:
  D:/users/lenovo/desktop/tensorflow-master/WORKSPACE:23:14: in <toplevel>
  D:/users/lenovo/desktop/tensorflow-master/tensorflow/workspace0.bzl:120:20: in workspace
  D:/users/lenovo/desktop/tensorflow-master/build-output/ijcwdbxz/external/com_github_grpc_grpc/bazel/grpc_extra_deps.bzl:29:18: in grpc_extra_deps
  D:/users/lenovo/desktop/tensorflow-master/build-output/ijcwdbxz/external/com_google_protobuf/protobuf_deps.bzl:34:21: in protobuf_deps
Repository rule http_archive defined at:
  D:/users/lenovo/desktop/tensorflow-master/build-output/ijcwdbxz/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: Analysis of target '//tensorflow:tensorflow_cc.dll' failed; build aborted: Configuration Error: --define PYTHON_BIN_PATH='C:/Users/LENOVO/AppData/Local/Programs/Python/Python313/python.exe' is not executable. Is it the python binary?
INFO: Elapsed time: 1.363s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    currently loading: @bazel_tools//tools/jdk
    Fetching ...docker; Cloning 251f6a68b439744094faff800cd029798edf9faa of https://github.com/bazelbuild/rules_docker\
.git
make: *** [makefile:4: all] Error 1
```
'C:/Users/LENOVO/AppData/Local/Programs/Python/Python313/python.exe' is a valid executable file

### Standalone code to reproduce the issue

```shell
python ./configure.py
bazel build --config=opt //tensorflow:tensorflow_cc.dll
```

### Relevant log output

```shell
bazel build --config=opt //tensorflow:tensorflow_cc.dll
INFO: Reading 'startup' options from d:\users\lenovo\desktop\tensorflow-master\.bazelrc: --output_user_root=D:/Users/LENOVO/Desktop/tensorflow-master/build-output
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=120
INFO: Reading rc options for 'build' from d:\users\lenovo\desktop\tensorflow-master\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=C:/Users/LENOVO/AppData/Local/Programs/Python/Python313/python.exe
INFO: Reading rc options for 'build' from d:\users\lenovo\desktop\tensorflow-master\.bazelrc:
  'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true
INFO: Reading rc options for 'build' from d:\users\lenovo\desktop\tensorflow-master\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=C:/Users/LENOVO/AppData/Local/Programs/Python/Python313/python.exe --action_env PYTHON_LIB_PATH=C:/Users/LENOVO/AppData/Local/Programs/Python/Python313/Lib/site-packages --python_path=C:/Users/LENOVO/AppData/Local/Programs/Python/Python313/python.exe --copt=/d2ReducedOptimizeHugeFunctions --host_copt=/d2ReducedOptimizeHugeFunctions --define=override_eigen_strong_inline=true
INFO: Found applicable config definition build:short_logs in file d:\users\lenovo\desktop\tensorflow-master\.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file d:\users\lenovo\desktop\tensorflow-master\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:opt in file d:\users\lenovo\desktop\tensorflow-master\.tf_configure.bazelrc: --copt=/arch:AVX --host_copt=/arch:AVX
INFO: Found applicable config definition build:windows in file d:\users\lenovo\desktop\tensorflow-master\.bazelrc: --copt=/W0 --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=/experimental:preprocessor --host_copt=/experimental:preprocessor --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --verbose_failures --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file d:\users\lenovo\desktop\tensorflow-master\.bazelrc: --define framework_shared_object=false
WARNING: Download from http://mirror.tensorflow.org/github.com/tensorflow/runtime/archive/b570a1921c9e55ac53c8972bd2bfd37cd0eb510d.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
DEBUG: D:/users/lenovo/desktop/tensorflow-master/build-output/ijcwdbxz/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
INFO: Repository local_execution_config_python instantiated at:
  D:/users/lenovo/desktop/tensorflow-master/WORKSPACE:15:14: in <toplevel>
  D:/users/lenovo/desktop/tensorflow-master/tensorflow/workspace2.bzl:1088:19: in workspace
  D:/users/lenovo/desktop/tensorflow-master/tensorflow/workspace2.bzl:85:27: in _tf_toolchains
  D:/users/lenovo/desktop/tensorflow-master/build-output/ijcwdbxz/external/tf_toolchains/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  D:/users/lenovo/desktop/tensorflow-master/build-output/ijcwdbxz/external/tf_toolchains/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  D:/users/lenovo/desktop/tensorflow-master/third_party/py/python_configure.bzl:275:41: in <toplevel>
INFO: Repository local_config_python instantiated at:
  D:/users/lenovo/desktop/tensorflow-master/WORKSPACE:15:14: in <toplevel>
  D:/users/lenovo/desktop/tensorflow-master/tensorflow/workspace2.bzl:1088:19: in workspace
  D:/users/lenovo/desktop/tensorflow-master/tensorflow/workspace2.bzl:95:21: in _tf_toolchains
Repository rule python_configure defined at:
  D:/users/lenovo/desktop/tensorflow-master/third_party/py/python_configure.bzl:294:35: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "D:/users/lenovo/desktop/tensorflow-master/third_party/py/python_configure.bzl", line 209, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "D:/users/lenovo/desktop/tensorflow-master/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
                auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
        File "D:/users/lenovo/desktop/tensorflow-master/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
                fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH='C:/Users/LENOVO/AppData/Local/Programs/Python/Python313/python.exe' is not executable. Is it the python binary?
INFO: Repository go_sdk instantiated at:
  D:/users/lenovo/desktop/tensorflow-master/WORKSPACE:23:14: in <toplevel>
  D:/users/lenovo/desktop/tensorflow-master/tensorflow/workspace0.bzl:120:20: in workspace
  D:/users/lenovo/desktop/tensorflow-master/build-output/ijcwdbxz/external/com_github_grpc_grpc/bazel/grpc_extra_deps.bzl:36:27: in grpc_extra_deps
  D:/users/lenovo/desktop/tensorflow-master/build-output/ijcwdbxz/external/io_bazel_rules_go/go/toolchain/toolchains.bzl:379:28: in go_register_toolchains
  D:/users/lenovo/desktop/tensorflow-master/build-output/ijcwdbxz/external/io_bazel_rules_go/go/private/sdk.bzl:65:21: in go_download_sdk
Repository rule _go_download_sdk defined at:
  D:/users/lenovo/desktop/tensorflow-master/build-output/ijcwdbxz/external/io_bazel_rules_go/go/private/sdk.bzl:53:35: in <toplevel>
INFO: Repository rules_java instantiated at:
  D:/users/lenovo/desktop/tensorflow-master/WORKSPACE:23:14: in <toplevel>
  D:/users/lenovo/desktop/tensorflow-master/tensorflow/workspace0.bzl:120:20: in workspace
  D:/users/lenovo/desktop/tensorflow-master/build-output/ijcwdbxz/external/com_github_grpc_grpc/bazel/grpc_extra_deps.bzl:29:18: in grpc_extra_deps
  D:/users/lenovo/desktop/tensorflow-master/build-output/ijcwdbxz/external/com_google_protobuf/protobuf_deps.bzl:34:21: in protobuf_deps
Repository rule http_archive defined at:
  D:/users/lenovo/desktop/tensorflow-master/build-output/ijcwdbxz/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: Analysis of target '//tensorflow:tensorflow_cc.dll' failed; build aborted: Configuration Error: --define PYTHON_BIN_PATH='C:/Users/LENOVO/AppData/Local/Programs/Python/Python313/python.exe' is not executable. Is it the python binary?
INFO: Elapsed time: 1.363s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    currently loading: @bazel_tools//tools/jdk
    Fetching ...docker; Cloning 251f6a68b439744094faff800cd029798edf9faa of https://github.com/bazelbuild/rules_docker\
.git
make: *** [makefile:4: all] Error 1
```

**Comment by tilakrayal** [comment]
@6VastUniverse,
Please do the following steps to fix it manually.

**Step 1.** Open the `python_configure.bzl `file, in my example the file path from [here](https://github.com/tensorflow/tensorflow/blob/master/third_party/py/python_configure.bzl#L128)

`cmd += "system(\"%s script.py\");" % python_bin.replace("\\","/")`

**Step 2.** Rerun the build command. Then, you can go further and see another error "invalid escape sequence".

ERROR
C:/users/username/_bazel_username/external/local_execution_config_python/BUILD:11:24: invalid escape sequence: \U     
ERROR: C:/users/username/_bazel_username/external/local_execution_config_python/BUILD:17:24: invalid escape sequence: \U 

**Step 3**. Open the BUILD file, in my example the file path is C:/external/local_execution_config_python/BUILD, and replace every \ with \\ at line 11 and 17.

**Step 4.** Continue the build process.

could you please try adding python definitions in the {project}/WORKSPACE file, then it might work. and Project can be built successfully.  Also please set the Java path as mentioned below. Add JAVA_HOME in the environmental variables

set JAVA_HOME = C:\Program Files\Eclipse Adoptium\jdk-17.0.4.101-hotspot

If you still get an issue, run bazel clean --expunge command to clear bazel cache and re-rerun the build command

Refer similar issue [here](https://github.com/google/mediapipe/issues/724#issue-622686030). Thank you!
