### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by flyi** [tensorflow/tensorflow#7995]
Traceback (most recent call last):
  File "d:\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "d:\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 906, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Python\Python35\lib\site-packages\tensorflow\python\__init__.py", line 66, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "d:\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 21, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "d:\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow')
  File "d:\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "d:\Python\Python35\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "d:\Python\Python35\lib\site-packages\tensorflow\python\__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "d:\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "d:\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 906, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Python\Python35\lib\site-packages\tensorflow\python\__init__.py", line 66, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "d:\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 21, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "d:\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow')
  File "d:\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow'

Failed to load the native TensorFlow runtime.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

====
Finally,I find the **solution**:
Install [Microsoft Visual C++ 2015 Redistributable Update 3 x64.](https://www.microsoft.com/en-us/download/details.aspx?id=53587)

**Comment by Carmezim** [comment]
Great that you solved. If you're not facing any other issues this can be closed now.

**Comment by tatatodd** [comment]
@flyi Thanks for posting your problems and the fix!

I'm closing this out.  If you have any other problems, feel free to open a new issue.  Thanks!

**Comment by specman** [comment]
that link returned an no webpage found error.

**Comment by flyi** [comment]
@specman 
Yes,that link returned 404. So I post my solution.

**Comment by ybsave** [comment]
I have similar problem. After installation of MS VC++ 2015 Redistributable Update 3 x64, the problem still exists. Here are the error message when I "import tensorflow":

Traceback (most recent call last):
  File "D:\Programs\Python35\lib\site-packages\tensorflow\python\pywrap_tensorfl
ow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "D:\Programs\Python35\lib\importlib\__init__.py", line 126, in import_mod
ule
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 914, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Programs\Python35\lib\site-packages\tensorflow\python\pywrap_tensorfl
ow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\Programs\Python35\lib\site-packages\tensorflow\python\pywrap_tensorfl
ow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\Programs\Python35\lib\site-packages\tensorflow\python\pywrap_tensorfl
ow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "D:\Programs\Python35\lib\importlib\__init__.py", line 126, in import_mod
ule
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Programs\Python35\lib\site-packages\tensorflow\__init__.py", line 24,
 in <module>
    from tensorflow.python import *
  File "D:\Programs\Python35\lib\site-packages\tensorflow\python\__init__.py", l
ine 51, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "D:\Programs\Python35\lib\site-packages\tensorflow\python\pywrap_tensorfl
ow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "D:\Programs\Python35\lib\site-packages\tensorflow\python\pywrap_tensorfl
ow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "D:\Programs\Python35\lib\importlib\__init__.py", line 126, in import_mod
ule
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 914, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Programs\Python35\lib\site-packages\tensorflow\python\pywrap_tensorfl
ow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\Programs\Python35\lib\site-packages\tensorflow\python\pywrap_tensorfl
ow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\Programs\Python35\lib\site-packages\tensorflow\python\pywrap_tensorfl
ow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "D:\Programs\Python35\lib\importlib\__init__.py", line 126, in import_mod
ule
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow_internal'


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_probl
ems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by hughlomas** [comment]
Same here, didn't work for me either. Can we please re-open this? @tatatodd

**Comment by specman** [comment]
I just downloaded Anaconda and got it through there. fwiw.

**Comment by Yoshiharo** [comment]
This is my code:

#matplotlib inline
import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np
from sklearn.metrics import confusion_matrix

tf.__version__
from tensorflow.examples.tutorials.mnist import input_data
data = input_data.read_data_sets("data/MNIST/", one_hot=True)

print("Size of:")
print("- Training-set:\t\t{}".format(len(data.train.labels)))
print("- Test-set:\t\t{}".format(len(data.test.labels)))
print("- Validation-set:\t\t".format(len(data.validation.labels)))

data.test.labels[0:5, :]
data.test.cls = np.array([label.argmax() for label in data.test.labels])
data.test.cls[0:5]


----------------------------------------------------------------------------------------
In it i'm getting the following error:-

Traceback (most recent call last):
  File "C:/Users/KumarRaja/Desktop/skywalker.py", line 5, in <module>
    from sklearn.metrics import confusion_matrix
  File "C:\Users\KumarRaja\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\__init__.py", line 57, in <module>
    from .base import clone
  File "C:\Users\KumarRaja\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\base.py", line 10, in <module>
    from scipy import sparse
  File "C:\Users\KumarRaja\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\sparse\__init__.py", line 221, in <module>
    from .csr import *
  File "C:\Users\KumarRaja\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\sparse\csr.py", line 15, in <module>
    from ._sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks, \
  File "C:\Users\KumarRaja\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\sparse\_sparsetools.py", line 7, in <module>
    __bootstrap__()
  File "C:\Users\KumarRaja\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\sparse\_sparsetools.py", line 6, in __bootstrap__
    imp.load_dynamic(__name__,__file__)
  File "C:\Users\KumarRaja\AppData\Local\Programs\Python\Python35\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.
----------------------------------------------------------------------------------------------------

Please anyone help me in resolving the error.And i have tried to remove the error by downloading the missing dll's and putting them to their respective location but it still won't working. If anyone find any possible solution it would be very helpful to share it as soon as possible....

**Comment by ybsave** [comment]
@hughlomas Hi, have you tried to use cuDNN 5.1 instead of the newest 6.x? Also, please try to use python 3.5, but not 3.6. These work for me.

**Comment by Yoshiharo** [comment]
Hello,

        I'm not using GPU instead I'm using CPU installation so there is no need of any cuDNN in it. Please visit the code again and have a review over it.

Thanks & Regards,



RAJAT KUMAR

Technical Trainee

FUJITSU CONSULTING INDIA
 Talwade, Pune
Office: +91-020-2769001

Mobile: + 91 9411292603

Email: Rajat.Kumar@in.fujitsu.com<mailto:Rajat.Kumar@in.fujitsu.com>

Shaping Tomorrow with You

________________________________

**Comment by felixshiyong** [comment]
I use the latest CUDA 8.0 and cuDNN6.0 for Windows 10, and it works well.

**Comment by Yoshiharo** [comment]
Hello,

        Thanks for your response but I want it for windows 7 and I'm not using the GPU , I'm using  CPU which does not include CUDA and cuDNN.

Thanks & Regards,



RAJAT KUMAR

Technical Trainee

FUJITSU CONSULTING INDIA
 Talwade, Pune
Office: +91-020-2769001

Mobile: + 91 9411292603

Email: Rajat.Kumar@in.fujitsu.com<mailto:Rajat.Kumar@in.fujitsu.com>

Shaping Tomorrow with You

________________________________

**Comment by jingyibo123** [comment]
Same problem here, worked after changing to cuDNN5.1 instead of 6.0.
win10 x64
Python 3.5
Tensorflow-gpu 1.1.0

**Comment by Yoshiharo** [comment]
Hello,

ok thanks for the reply and let me try it with your solution on my system.

Thanks & Regards,



RAJAT KUMAR

Technical Trainee

FUJITSU CONSULTING INDIA
 Talwade, Pune
Office: +91-020-2769001

Mobile: + 91 9411292603

Email: Rajat.Kumar@in.fujitsu.com<mailto:Rajat.Kumar@in.fujitsu.com>

Shaping Tomorrow with You

________________________________

**Comment by MPRAV** [comment]
Not sure why this error is coming for CPU systems. Facing the same.

**Comment by MPRAV** [comment]
have a look at this link for workaround https://github.com/tensorflow/tensorflow/issues/17386
