### ISSUE TITLE
tf.contrib.slim API not support tensorflow newest API

### ISSUE THREAD

**Issue by jinfagang** [tensorflow/tensorflow#8004]
I like using slim write cnn net structures, but there is something emergency to catch up tensorflow newest API, 
this simple code got deprecate warning follow!
```
predictions = inference.lenet(images, num_classes=FLAGS.num_classes+1, activation_fn=None)
slim.losses.softmax_cross_entropy(predictions, labels)
```

```
softmax_cross_entropy (from tensorflow.contrib.losses.python.losses.loss_ops) is deprecated and will be removed after 2016-12-30.
Instructions for updating:
Use tf.losses.softmax_cross_entropy instead.
WARNING:tensorflow:From /usr/local/lib/python3.6/site-packages/tensorflow/contrib/losses/python/losses/loss_ops.py:394: compute_weighted_loss (from tensorflow.contrib.losses.python.losses.loss_ops) is deprecated and will be removed after 2016-12-30.
Instructions for updating:
Use tf.losses.compute_weighted_loss instead.
```
I think this is essue about slim.losses, however I tried using `tf.losses.softmax_cross_entropy`instead, got this error:
```
Traceback (most recent call last):
  File "train_tiny5_tensorflow.py", line 154, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_tiny5_tensorflow.py", line 150, in main
    run_training()
  File "train_tiny5_tensorflow.py", line 128, in run_training
    tf.losses.softmax_cross_entropy(predictions, labels)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/losses/losses_impl.py", line 529, in softmax_cross_entropy
    name="xentropy")
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1617, in softmax_cross_entropy_with_logits
    precise_logits, labels, name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 2265, in _softmax_cross_entropy_with_logits
    features=features, labels=labels, name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 585, in apply_op
    param_name=input_name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 61, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'features' has DataType int32 not in list of allowed values: float16, float32, float64
```

**Comment by pobingwanghai** [comment]
I meet the same situation too, the newest api document doesn't have slim

**Comment by jinfagang** [comment]
@pobingwanghai I trend to abandom slim and use plane tensorflow to write layers, it's more powerful and let's you controll everything.

**Comment by tatatodd** [comment]
Closing this out, please follow up on #7993

**Comment by vaklyuenkov** [comment]
Instead: 
 ```
     #############################
      # Specify the loss function #
      #############################
      if 'AuxLogits' in end_points:
      # slim.losses.softmax_cross_entropy(
       tf.losses.softmax_cross_entropy(
    end_points['AuxLogits'], labels, weights=0.4,
            label_smoothing=FLAGS.label_smoothing, scope='aux_loss')
     #slim.losses.softmax_cross_entropy(
      tf.losses.softmax_cross_entropy(
          logits, labels, weights=1.0, label_smoothing=FLAGS.label_smoothing)
      return end_points
```
I use:

```
 #############################
      # Specify the loss function #
      #############################
      if 'AuxLogits' in end_points:
     
       tf.losses.softmax_cross_entropy(
    end_points['AuxLogits'], labels, weights=0.4,
            label_smoothing=FLAGS.label_smoothing, scope='aux_loss')

      tf.losses.softmax_cross_entropy(
          logits, labels, weights=1.0, label_smoothing=FLAGS.label_smoothing)
      return end_points
```

in tf r1.0.

Training run without any errors. Can anyone say -is it correct loss function calculation? 
Thank u!
