### ISSUE TITLE
Connection timed out when loading MNIST

### ISSUE THREAD

**Issue by akaraspt** [tensorflow/tensorflow#8009]
Hi,

I got **Connection timed out** error when I was trying to load MNIST data using tensorflow script.
```
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets('MNIST_data', one_hot=True)
```

Error:
```
Traceback (most recent call last):
  File "create_mnistm.py", line 9, in <module>
    mnist = input_data.read_data_sets('MNIST_data', one_hot=True)
  File "/home/user/miniconda2/envs/domain_adapt/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 211, in read_data_sets
    SOURCE_URL + TRAIN_IMAGES)
  File "/home/user/miniconda2/envs/domain_adapt/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 208, in maybe_download
    temp_file_name, _ = urlretrieve_with_retry(source_url)
  File "/home/user/miniconda2/envs/domain_adapt/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 165, in wrapped_fn
    return fn(*args, **kwargs)
  File "/home/user/miniconda2/envs/domain_adapt/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 190, in urlretrieve_with_retry
    return urllib.request.urlretrieve(url, filename)
  File "/home/user/miniconda2/envs/domain_adapt/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/home/user/miniconda2/envs/domain_adapt/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/home/user/miniconda2/envs/domain_adapt/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/home/user/miniconda2/envs/domain_adapt/lib/python2.7/urllib.py", line 350, in open_http
    h.endheaders(data)
  File "/home/user/miniconda2/envs/domain_adapt/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/home/user/miniconda2/envs/domain_adapt/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/home/user/miniconda2/envs/domain_adapt/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/home/user/miniconda2/envs/domain_adapt/lib/python2.7/httplib.py", line 821, in connect
    self.timeout, self.source_address)
  File "/home/user/miniconda2/envs/domain_adapt/lib/python2.7/socket.py", line 575, in create_connection
    raise err
IOError: [Errno socket error] [Errno 110] Connection timed out
```

### Environment info
Operating System: Ubuntu 16.04

Installed version of CUDA and cuDNN: 
```
-rw-r--r-- 1 root root   558720 Jan 19 11:54 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 Jan 19 11:54 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root root       19 Jan 19 11:54 /usr/local/cuda/lib64/libcudart.so.8.0 -> libcudart.so.8.0.44
-rwxr-xr-x 1 root root   415432 Jan 19 11:54 /usr/local/cuda/lib64/libcudart.so.8.0.44
-rw-r--r-- 1 root root   775162 Jan 19 11:54 /usr/local/cuda/lib64/libcudart_static.a
-rwxr-xr-x 1 root root 79337624 Jan 19 12:13 /usr/local/cuda/lib64/libcudnn.so
-rwxr-xr-x 1 root root 79337624 Jan 19 12:13 /usr/local/cuda/lib64/libcudnn.so.5
-rwxr-xr-x 1 root root 79337624 Jan 19 12:13 /usr/local/cuda/lib64/libcudnn.so.5.1.5
-rw-r--r-- 1 root root 69756172 Jan 19 12:13 /usr/local/cuda/lib64/libcudnn_static.a
```

The output from `python -c "import tensorflow; print(tensorflow.__version__)"`:
```
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
0.12.1
```

**Comment by akaraspt** [comment]
Oh it seems the server is down.
