### ISSUE TITLE
SavedModelBundle.load call results in Could not find variable sequential/conv2d_1/kernel

### ISSUE THREAD

**Issue by avinash10584** [tensorflow/tensorflow#80191]
I saved the sequential model in Python and I am using it in Java but keep getting this error,

2024-11-18 10:08:07.698839: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: FAILED_PRECONDITION: Could not find variable sequential/conv2d_1/kernel. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status error message=Resource localhost/sequential/conv2d_1/kernel/class tensorflow::Var does not exist.
	 [[{{function_node __inference_serving_default_8088}}{{node sequential_1/conv2d_1_2/convolution/ReadVariableOp}}]]
Exception in thread "main" org.tensorflow.exceptions.TFFailedPreconditionException: Could not find variable sequential/conv2d_1/kernel. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status error message=Resource localhost/sequential/conv2d_1/kernel/class tensorflow::Var does not exist.
	 [[{{function_node __inference_serving_default_8088}}{{node sequential_1/conv2d_1_2/convolution/ReadVariableOp}}]]
	at org.tensorflow.internal.c_api.AbstractTF_Status.throwExceptionIfNotOK(AbstractTF_Status.java:84)
	at org.tensorflow.Session.run(Session.java:826)
	at org.tensorflow.Session$Runner.runHelper(Session.java:549)

[model.zip](https://github.com/user-attachments/files/17802418/model.zip)

I have tested the model in Python with below code and that works fine

 ```
   prediction_tensors = model.signatures["serving_default"](tf.cast(new_image, tf.float32))
    for _, values in prediction_tensors.items():
        predictions = values.numpy()[0]
    #print('  Output with input', img_path, ': ', predictions)
    percent = round(np.max(predictions)*100,2)
    result  = CATEGORIES[np.argmax(predictions)]
```

Java code,
```

public static float[] predict3(String modelPath, float[][][][] imageTensorData) {

        System.out.println(TensorFlow.version());
        try(SavedModelBundle model = SavedModelBundle.load(modelPath, "serve")) {
        
        Signature sig = model.signatures().get(0);
        Session sess = model.session();
        TensorFunction func =  model.function("serving_default");

        TFloat32 rank3Tensor = TFloat32.tensorOf(StdArrays.ndCopyOf(imageTensorData));
        Tensor result = func.call(rank3Tensor);
        }
        return null;
    }

```

**Comment by Venkat6871** [comment]
Hi **@avinash10584** ,
Please post this issue in the specific repository for faster resolution: https://github.com/tensorflow/java.
Thank you!
