### ISSUE TITLE
Unable to run tensorflow on Android through android studio

### ISSUE THREAD

**Issue by SeanTyco** [tensorflow/tensorflow#8059]
The build is successful but the app crashes immediately when it's brought up on any device.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
https://github.com/tensorflow/tensorflow/issues/7256
https://github.com/tensorflow/tensorflow/issues/3444 (assembleDebug error - resolved)

### Environment info
Operating System:
Running Android Studio 2.2.3 on Mac with Sierra 10.12.3
Trying to run on a virtual Nexus 7 with Marshmallow x86

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
I followed the instructions in the tensorflow GitHub readme [here]([https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android]).

### What other attempted solutions have you tried?
I am able to compile using bazel build but I cannot get it running through Android Studio. I tried using a Pixel C and a Visual Land Prestige.

### Logs or other output that would be helpful
03/03 10:27:22: Launching android
$ adb shell am start -n "org.tensorflow.demo/org.tensorflow.demo.ClassifierActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 4001 on device emulator-5554
I/InstantRun: Instant Run Runtime started. Android package is org.tensorflow.demo, real application class is null.

              [ 03-03 10:27:22.381  1648: 1669 D/         ]
              HostConnection::get() New Host Connection established 0x9d43f2c0, tid 1669
D/tensorflow: CameraActivity: onCreate org.tensorflow.demo.ClassifierActivity@9ad6111
D/tensorflow: CameraActivity: onStart org.tensorflow.demo.ClassifierActivity@9ad6111
D/tensorflow: CameraActivity: onResume org.tensorflow.demo.ClassifierActivity@9ad6111
D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true

                  [ 03-03 10:27:22.710  4001: 4001 D/         ]
                  HostConnection::get() New Host Connection established 0xaa7bfb80, tid 4001

                  [ 03-03 10:27:22.840  4001: 4017 D/         ]
                  HostConnection::get() New Host Connection established 0xb2d1a000, tid 4017
I/OpenGLRenderer: Initialized EGL, version 1.4
W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
I/CameraManagerGlobal: Connecting to camera service
I/tensorflow: CameraConnectionFragment: Adding size: 640x480
I/tensorflow: CameraConnectionFragment: Not adding size: 352x288
I/tensorflow: CameraConnectionFragment: Not adding size: 320x240
I/tensorflow: CameraConnectionFragment: Not adding size: 176x144
I/tensorflow: CameraConnectionFragment: Chosen size: 640x480
I/TensorFlowImageClassifier: Reading labels from: imagenet_comp_graph_label_strings.txt
E/art: No implementation found for long org.tensorflow.contrib.android.RunStats.allocate() (tried Java_org_tensorflow_contrib_android_RunStats_allocate and Java_org_tensorflow_contrib_android_RunStats_allocate__)
I/TensorFlowInferenceInterface: Loading tensorflow_inference.
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: org.tensorflow.demo, PID: 4001
                  java.lang.RuntimeException: Error initializing TensorFlow!
                      at org.tensorflow.demo.ClassifierActivity.onPreviewSizeChosen(ClassifierActivity.java:131)
                      at org.tensorflow.demo.CameraActivity$1.onPreviewSizeChosen(CameraActivity.java:158)
                      at org.tensorflow.demo.CameraConnectionFragment.setUpCameraOutputs(CameraConnectionFragment.java:394)
                      at org.tensorflow.demo.CameraConnectionFragment.openCamera(CameraConnectionFragment.java:411)
                      at org.tensorflow.demo.CameraConnectionFragment.access$000(CameraConnectionFragment.java:63)
                      at org.tensorflow.demo.CameraConnectionFragment$1.onSurfaceTextureAvailable(CameraConnectionFragment.java:94)
                      at android.view.TextureView.getHardwareLayer(TextureView.java:368)
                      at android.view.View.updateDisplayListIfDirty(View.java:15151)
                      at android.view.View.draw(View.java:15948)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                      at android.view.View.updateDisplayListIfDirty(View.java:15169)
                      at android.view.View.draw(View.java:15948)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                      at android.view.View.draw(View.java:16181)
                      at android.view.View.updateDisplayListIfDirty(View.java:15174)
                      at android.view.View.draw(View.java:15948)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                      at android.view.View.updateDisplayListIfDirty(View.java:15169)
                      at android.view.View.draw(View.java:15948)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                      at android.view.View.updateDisplayListIfDirty(View.java:15169)
                      at android.view.View.draw(View.java:15948)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                      at android.view.View.draw(View.java:16181)
                      at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2690)
                      at android.view.View.updateDisplayListIfDirty(View.java:15174)
                      at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
                      at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
                      at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
                      at android.view.ViewRootImpl.draw(ViewRootImpl.java:2615)
                      at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2434)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2067)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                      at android.view.Choreographer.doFrame(Choreographer.java:606)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                   Caused by: java.lang.RuntimeException: Native TF methods not found; check that the correct native libraries are present and loaded.
                      at org.tensorflow.contrib.android.TensorFlowInferenceInterface.<init>(TensorFlowInferenceInterface.java:57)
                      at org.tensorflow.demo.TensorFlowImageClassifier.create(TensorFlowImageClassifier.java:101)
                      at org.tensorflow.demo.ClassifierActivity.onPreviewSizeChosen(ClassifierActivity.java:121)
                      at org.tensorflow.demo.CameraActivity$1.onPreviewSizeChosen(CameraActivity.java:158) 
                      at org.tensorflow.demo.CameraConnectionFragment.setUpCameraOutputs(CameraConnectionFragment.java:394) 
                      at org.tensorflow.demo.CameraConnectionFragment.openCamera(CameraConnectionFragment.java:411) 
                      at org.tensorflow.demo.CameraConnectionFragment.access$000(CameraConnectionFragment.java:63) 
                      at org.tensorflow.demo.CameraConnectionFragment$1.onSurfaceTextureAvailable(CameraConnectionFragment.java:94) 
                      at android.view.TextureView.getHardwareLayer(TextureView.java:368) 
                      at android.view.View.updateDisplayListIfDirty(View.java:15151) 
                      at android.view.View.draw(View.java:15948) 
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3609) 
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399) 
                      at android.view.View.updateDisplayListIfDirty(View.java:15169) 
                      at android.view.View.draw(View.java:15948) 
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3609) 
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399) 
                      at android.view.View.draw(View.java:16181) 
                      at android.view.View.updateDisplayListIfDirty(View.java:15174) 
                      at android.view.View.draw(View.java:15948) 
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3609) 
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399) 
                      at android.view.View.updateDisplayListIfDirty(View.java:15169) 
                      at android.view.View.draw(View.java:15948) 
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3609) 
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399) 
                      at android.view.View.updateDisplayListIfDirty(View.java:15169) 
                      at android.view.View.draw(View.java:15948) 
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3609) 
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399) 
                      at android.view.View.draw(View.java:16181) 
                      at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2690) 
                      at android.view.View.updateDisplayListIfDirty(View.java:15174) 
                      at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281) 
                      at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287) 
                      at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322) 
                      at android.view.ViewRootImpl.draw(ViewRootImpl.java:2615) 
                      at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2434) 
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2067) 
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107) 
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013) 
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858) 
                      at android.view.Choreographer.doCallbacks(Choreographer.java:670) 
                      at android.view.Choreographer.doFrame(Choreographer.java:606) 
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844) 
                      at android.os.Handler.handleCallback(Handler.java:739) 
                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                      at android.os.Looper.loop(Looper.java:148) 
                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
Application terminated.

**Comment by andrewharp** [comment]
Relevant line from Exception (it's sort of hidden in the middle):

> Caused by: java.lang.RuntimeException: Native TF methods not found; check that the correct native libraries are present and loaded.

The most likely cause is that you're only packaging armeabi-v7a libs for an x86 emulated device. Bazel builds multiple ABIs, but the gradle.build only specifies armeabi-v7a, so you should change that to x86 or x86_64.

**Comment by SeanTyco** [comment]
I did change the cpuType in the build.gradle to x86. I also tried to install the demo on a Pixel C using the armeabi-v7a cpuType.

**Comment by andrewharp** [comment]
Hmm, what do you see when you run `unzip -v tensorflow_demo.apk`? (change the filename to whatever the actual output location from gradle is)

**Comment by SeanTyco** [comment]
unzip -v android-debug.apk 
Archive:  android-debug.apk
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
    3444  Defl:N     1033  70% 00-00-1980 00:00 9cf79666  AndroidManifest.xml
     773  Defl:N      602  22% 00-00-1980 00:00 fdcf1a2f  META-INF/CERT.RSA
    4775  Defl:N     2220  54% 00-00-1980 00:00 0676efa1  META-INF/CERT.SF
    4713  Defl:N     2180  54% 00-00-1980 00:00 5de00cd7  META-INF/MANIFEST.MF
     461  Defl:N      292  37% 00-00-1980 00:00 eafcece9  assets/BUILD
   11416  Defl:N     4452  61% 00-00-1980 00:00 c04c6f58  assets/LICENSE
   10492  Defl:N     5554  47% 00-00-1980 00:00 bdb9b97a  assets/imagenet_comp_graph_label_strings.txt
   42335  Defl:N     4901  88% 00-00-1980 00:00 90dd4646  assets/multibox_location_priors.txt
18556306  Defl:N 16704579  10% 00-00-1980 00:00 cdeb207e  assets/multibox_model.pb
  563897  Defl:N   270926  52% 00-00-1980 00:00 7d7f4ff3  assets/stylize_quantized.pb
53884595  Defl:N 50111288   7% 00-00-1980 00:00 6d3b8d15  assets/tensorflow_inception_graph.pb
  131978  Stored   131978   0% 00-00-1980 00:00 3228d14c  assets/thumbnails/style0.jpg
  113303  Stored   113303   0% 00-00-1980 00:00 13596907  assets/thumbnails/style1.jpg
  151688  Stored   151688   0% 00-00-1980 00:00 a3e9c196  assets/thumbnails/style10.jpg
  181154  Stored   181154   0% 00-00-1980 00:00 adb4f0a3  assets/thumbnails/style11.jpg
  107888  Stored   107888   0% 00-00-1980 00:00 79dbb7d0  assets/thumbnails/style12.jpg
  198586  Stored   198586   0% 00-00-1980 00:00 c97505a9  assets/thumbnails/style13.jpg
  104584  Stored   104584   0% 00-00-1980 00:00 5832132a  assets/thumbnails/style14.jpg
  152269  Stored   152269   0% 00-00-1980 00:00 005ad28f  assets/thumbnails/style15.jpg
  168251  Stored   168251   0% 00-00-1980 00:00 6bccba6c  assets/thumbnails/style16.jpg
  146736  Stored   146736   0% 00-00-1980 00:00 132cbdcb  assets/thumbnails/style17.jpg
  173496  Stored   173496   0% 00-00-1980 00:00 9a6a37a7  assets/thumbnails/style18.jpg
  227300  Stored   227300   0% 00-00-1980 00:00 a11b35b4  assets/thumbnails/style19.jpg
  140121  Stored   140121   0% 00-00-1980 00:00 34147cc2  assets/thumbnails/style2.jpg
  134506  Stored   134506   0% 00-00-1980 00:00 3df5a425  assets/thumbnails/style20.jpg
  138136  Stored   138136   0% 00-00-1980 00:00 0754c15d  assets/thumbnails/style21.jpg
  168478  Stored   168478   0% 00-00-1980 00:00 25998a8e  assets/thumbnails/style22.jpg
  108525  Stored   108525   0% 00-00-1980 00:00 91f2c6b0  assets/thumbnails/style23.jpg
  131414  Stored   131414   0% 00-00-1980 00:00 ead622b6  assets/thumbnails/style24.jpg
  190320  Stored   190320   0% 00-00-1980 00:00 b39eb2ce  assets/thumbnails/style25.jpg
  181100  Stored   181100   0% 00-00-1980 00:00 a86a5141  assets/thumbnails/style3.jpg
  181565  Stored   181565   0% 00-00-1980 00:00 9dfc14ff  assets/thumbnails/style4.jpg
  162432  Stored   162432   0% 00-00-1980 00:00 2e8636d3  assets/thumbnails/style5.jpg
  167919  Stored   167919   0% 00-00-1980 00:00 560fdd11  assets/thumbnails/style6.jpg
   97875  Stored    97875   0% 00-00-1980 00:00 684b2c5b  assets/thumbnails/style7.jpg
  121177  Stored   121177   0% 00-00-1980 00:00 d552dee2  assets/thumbnails/style8.jpg
  208059  Stored   208059   0% 00-00-1980 00:00 83817fe1  assets/thumbnails/style9.jpg
     740  Defl:N      471  36% 00-00-1980 00:00 481c4d20  classes.dex
   64752  Defl:N    32965  49% 00-00-1980 00:00 f7b87071  classes2.dex
  484649  Defl:N   180245  63% 00-00-1980 00:00 ff23ba2f  instant-run.zip
  742980  Defl:N   306495  59% 00-00-1980 00:00 60d11c46  lib/x86/libtensorflow_demo.so
     234  Stored      234   0% 00-00-1980 00:00 c560f719  res/drawable-hdpi-v4/tile.9.png
     728  Stored      728   0% 00-00-1980 00:00 9be31f46  res/drawable-xhdpi-v4/ic_action_info.png
    5855  Stored     5855   0% 00-00-1980 00:00 284931e6  res/drawable-xhdpi-v4/ic_launcher.png
     404  Defl:N      228  44% 00-00-1980 00:00 97e57137  res/layout/activity_camera.xml
     960  Defl:N      395  59% 00-00-1980 00:00 0df7a886  res/layout/camera_connection_fragment.xml
    1356  Defl:N      501  63% 00-00-1980 00:00 fd74248b  res/layout/camera_connection_fragment_stylize.xml
     784  Defl:N      319  59% 00-00-1980 00:00 3cce775d  res/layout/camera_connection_fragment_tracking.xml
    4616  Stored     4616   0% 00-00-1980 00:00 be2ae3b9  resources.arsc
--------          -------  ---                            -------
78380125         71629939   9%                            49 files

**Comment by andrewharp** [comment]
You're missing libtensorflow_inference.so for some reason. Check the bazel logs and bazel-bin dir to see if you can figure out what happened to it?

**Comment by SeanTyco** [comment]
I found it in the bazel-bin at /tensorflow/contrib/android/libtensorflow_inference.so.

**Comment by andrewharp** [comment]
Ok -- is that from the command-line bazel build or from the gradle build inside Android Studio (if the former then make sure you `bazel clean` first)?

Does it make its way into the libs/ dir in the project when you build, and does the Android Studio/gradle log give any indication why it's not being packaged?

**Comment by SeanTyco** [comment]
I'm assuming you mean the jniLibs directory? If so then, no, I only see the libtensorflow_demo.so not the libtensorflow_inference.so library. 

I did do a bagel clean before running in android studio and the libtensorflow_inference.so is built at the location /tensorflow/contrib/android/libtensorflow_inference.so. I don't see any indication as to why it's not being packaged in the log files. Is there a particular log file (what are the steps to output the log file) that you're talking about?

**Comment by andrewharp** [comment]
@SeanTyco I was able to reproduce this locally -- the problem is that gradle is only looking for .so files under tensorflow/examples/android and not tensorflow/contrib/android as well (where libtensorflow_inference.so resides).

If you change add another "from" directive to "copyNativeLibs" so that it looks like the following:
```
task copyNativeLibs(type: Copy) {
    from('../../../bazel-bin/tensorflow/contrib/android/') { include '*.so' }
    from('../../../bazel-bin/tensorflow/examples/android/') { include '*.so' }
    into nativeDir
    duplicatesStrategy = 'include'
    dependsOn 'buildNative'
}
```
it should work.

I also had to switch my local gradle plugin defined in the build.gradle from 2.2.0 to 2.3.0 to deal with a !zip.isFile() problem, just in case you run into that too.

Will check in a full fix soon.

**Comment by SeanTyco** [comment]
In case anyone else is looking, I initially got the following, even when doing a 'bazel clean' before building:
```
:copyNativeLibs FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':copyNativeLibs'.
> Could not copy file '.../1a4c05cdb2ca1de9a943143330f40f73/execroot/tensorflow/bazel-out/x86-4.9-gnu-libstdcpp-opt/bin/tensorflow/examples/android/libtensorflow_demo.so' to '.../tensorflow/tensorflow/examples/android/libs/x86/libtensorflow_demo.so'.
```
You have to open permissions on the .so file in the `.../tensorflow/tensorflow/examples/android/libs/x86/`  directory.

**Comment by andrewharp** [comment]
Yes, it turns out that bazel creates the files as read-only by default. To prevent this from happening on subsequent builds you can add a "fileMode 0644" to the copyNativeLibs task in build.gradle (I'm in the process of submitting a fix for this currently).

**Comment by ArtsiomCh** [comment]
Have similar problems starting on real device (LP5.1) successfully created apk with Android studio.
Apk created by Bazel works fine. Comparing two apks (Old - android-debug.apk from Android studio; New - tensorflow_demo.apk from Bazel) shows the next:
![image](https://cloud.githubusercontent.com/assets/14268320/23840746/a72deb64-079f-11e7-8285-292d33820226.png)
Looks like existence of libtensorflow_inference.so doesn't metter. It's not exist at tensorflow_demo.apk from Bazel and apk work fine.

PS Logcat (through Android Monitor in Android Studio) when starting android-debug.apk shows next error:
03-12 23:53:26.525 26147-26147/org.tensorflow.demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: org.tensorflow.demo, PID: 26147
                                                                     java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.tensorflow.demo-1/base.apk", zip file "/data/app/org.tensorflow.demo-1/split_lib_slice_0_apk.apk", ....<censored>... ],nativeLibraryDirectories=[/data/app/org.tensorflow.demo-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libtensorflow_demo.so"
Looks like libtensorflow_demo.so is included in Libs but not linked for some reason... Will keep investigating.

**Comment by andrewharp** [comment]
@ArtsiomCh You need to build both `tensorflow/examples/android:libtensorflow_demo.so` and `tensorflow/contrib/android:libtensorflow_inference.so` and make sure they both make it into the APK. The former contains the image pre-processing and tracking code used by the examples, and the latter contains TensorFlow itself.

**Comment by ArtsiomCh** [comment]
I thought so too. But the trick is that apk built by bazel (`bazel build -c opt //tensorflow/examples/android:tensorflow_demo`) does not contain `libtensorflow_inference.so` either but only `libtensorflow_demo.so` in /lib. And its work fine on real device.
I would presume `libtensorflow_demo.so` include functionality of `libtensorflow_inference.so`.

**Comment by rtjarvis** [comment]
I am having a similar issue. I am using my own retrained model (which I have stripped) and put in assets. I have updated ClassifierActivity with appropriate values. 

I am running on a real android device (API 24) and I get "No implementation found for long org.tensorflow.contrib.android.RunStats.allocate()" from logcat. Both lib/armeabi-v7a/libtensorflow_demo.so and lib/armeabi-v7a/libtensorflow_inference.so are in the resulting APK.

Full stack:
`
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: org.tensorflow.demo, PID: 13456
                                                                     java.lang.UnsupportedOperationException: Op BatchNormWithGlobalNormalization is not available in GraphDef version 21. It has been removed in version 9. Use tf.nn.batch_normalization().
                                                                         at org.tensorflow.Graph.importGraphDef(Native Method)
                                                                         at org.tensorflow.Graph.importGraphDef(Graph.java:118)
                                                                         at org.tensorflow.Graph.importGraphDef(Graph.java:102)
                                                                         at org.tensorflow.contrib.android.TensorFlowInferenceInterface.load(TensorFlowInferenceInterface.java:414)
                                                                         at org.tensorflow.contrib.android.TensorFlowInferenceInterface.initializeTensorFlow(TensorFlowInferenceInterface.java:95)
                                                                         at org.tensorflow.demo.TensorFlowImageClassifier.create(TensorFlowImageClassifier.java:106)
                                                                         at org.tensorflow.demo.ClassifierActivity.onPreviewSizeChosen(ClassifierActivity.java:118)
                                                                         at org.tensorflow.demo.CameraActivity$1.onPreviewSizeChosen(CameraActivity.java:158)
                                                                         at org.tensorflow.demo.CameraConnectionFragment.setUpCameraOutputs(CameraConnectionFragment.java:408)
                                                                         at org.tensorflow.demo.CameraConnectionFragment.openCamera(CameraConnectionFragment.java:415)
                                                                         at org.tensorflow.demo.CameraConnectionFragment.access$000(CameraConnectionFragment.java:64)
                                                                         at org.tensorflow.demo.CameraConnectionFragment$1.onSurfaceTextureAvailable(CameraConnectionFragment.java:95)
                                                                         at android.view.TextureView.getHardwareLayer(TextureView.java:387)
                                                                         at android.view.TextureView.draw(TextureView.java:325)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:16116)
                                                                         at android.view.View.draw(View.java:16900)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:16111)
                                                                         at android.view.View.draw(View.java:16900)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                         at android.view.View.draw(View.java:17137)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:16116)
                                                                         at android.view.View.draw(View.java:16900)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:16111)
                                                                         at android.view.View.draw(View.java:16900)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:16111)
                                                                         at android.view.View.draw(View.java:16900)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                         at android.view.View.draw(View.java:17137)
                                                                         at com.android.internal.policy.DecorView.draw(DecorView.java:751)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:16116)
                                                                         at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:656)
                                                                         at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:662)
                                                                         at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:770)
                                                                         at android.view.ViewRootImpl.draw(ViewRootImpl.java:2830)
                                                                         at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2638)
                                                                         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2245)
                                                                         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1272)
                                                                         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6396)
                                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
                                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:683)
                                                                         at android.view.Choreographer.doFrame(Choreographer.java:619)
                                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
                                                                         at android.os.Handler.handleCallback(Handler.java:751)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6209)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
03-15 08:16:54.573 13456-13456/org.tensorflow.demo E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)`

 Anyone help?

**Comment by ArtsiomCh** [comment]
Hi, @rtjarvis. 
Looks like you are using some deprecated function in your code:
`BatchNormWithGlobalNormalization is not available in GraphDef version 21. It has been removed in version 9. Use tf.nn.batch_normalization().`
Also I would suggest to use Bazel to build. Looks like building with Android studio is still a bit experimental and need some fine tuning.

**Comment by rtjarvis** [comment]
@ArtsiomCh - thanks. I guessed that this might be the challenge but I've only just built my model by following the tutorial for retaining the inception classifier. I was expecting it to be compatible!

**Comment by SeanTyco** [comment]
Somewhat along those lines, what function should be used to output a custom model for the demo code to load the graph and weights? I am using tf.train.Saver(), which outputs an index, a meta and a checkpoint file. However, I'm not sure what to use in the demo android code in place of tensorflow_inception_graph.pb?

**Comment by tkaye407** [comment]
@SeanTyco 
Look into the script freeze_graph.py published by TensorFlow
