### ISSUE TITLE
Hi, I am using TF 1.0.0 on ubuntu 16.04 64bit os , I also meets this error, can you help to resolve it, thank you.

### ISSUE THREAD

**Issue by bkovalev** [tensorflow/tensorflow#8060]
```
bazel-bin/inception/imagenet_train --num_gpus=2 --batch_size=32 --train_dir=/data/imagenet-train --data_dir=/data/imagenet-data                                                              
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally             
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally                
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally              
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally                 
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally             
Traceback (most recent call last):                                                                                    
  File "/root/tensorflow/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/imagenet_train.py", line 41, in <module>                                                                                          
    tf.app.run()                                                                                                      
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run                    
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))                                                                
  File "/root/tensorflow/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/imagenet_train.py", line 37, in main                                                                                              
    inception_train.train(dataset)                                                                                    
  File "/root/tensorflow/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/inception_train.py", line 217, in train                                                                                           
    num_preprocess_threads=num_preprocess_threads)                                                                    
  File "/root/tensorflow/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/image_processing.py", line 136, in distorted_inputs                                                                               
    num_readers=FLAGS.num_readers)                                                                                    
  File "/root/tensorflow/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/image_processing.py", line 490, in batch_inputs
    example_serialized)
  File "/root/tensorflow/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/image_processing.py", line 397, in parse_example_proto
    bbox = tf.concat(0, [ymin, xmin, ymax, xmax])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1029, in concat
    dtype=dtypes.int32).get_shape(
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 637, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 702, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 110, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 99, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.
```

**Comment by tfboyd** [comment]
I did a quick test and I get the same error.  The models repo is being rebuilt, but I will try to take a look at the possible root cause.   I suspect an issue when it was upgraed to TF 1.0 but that is just an off-the-cuff wild guess.

**Comment by tfboyd** [comment]
My fast response is because if you are like me you are playing on the weekend and want this to work.  I will try to do a PR tomorrow but I am virtually sure the issues starts here

`inception/image_processing.py", line 397, in parse_example_proto bbox = tf.concat(0, [ymin, xmin, ymax, xmax])`

Concat changed in TF 1.0, the 0 goes at the end.  But there is more tf.image_summary also changed.  I suggest running the tf [migration script](https://www.tensorflow.org/install/migration) on the file.

**Comment by tfboyd** [comment]
Took me a week rather than one day.  Here is the PR.  I tested it locally and works with TF 1.0. Sorry tensorflow/models is a bit tough.  We are working on it.  

https://github.com/tensorflow/models/pull/1150

Marking closed.
