### ISSUE TITLE
unexpected pipe read status

### ISSUE THREAD

**Issue by Cynthia0629** [tensorflow/tensorflow#8092]
Hello,everyone!
I am new about tensorflow,and I am just trying to build tensorflow from source according to the steps described step by step, but I get the following error, Is there anyone who can help on it? That would be very kind of you!
Thank you very much!

cynthia@cynthia-pc:~/tensorflow$ ./configure

..........continue........
then the result came with the following......
I guess that maybe something wrong with my bazel ,but I'm new about this,and I'm really no idea how to solve it.

unexpected pipe read status: No such file or directory
Server presumed dead. Now printing '/home/cynthia/.cache/bazel/_bazel_cynthia/581b5660c7c191b39a76e8a607014a30/server/jvm.out':
Java HotSpot(TM) Server VM warning: You have loaded library /home/cynthia/.cache/bazel/_bazel_cynthia/install/6a615f09339464d6ea7e8fe00f96c132/_embedded_binaries/libunix.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c ', or link it with '-z noexecstack'.
JNI initialization failed: /home/cynthia/.cache/bazel/_bazel_cynthia/install/6a615f09339464d6ea7e8fe00f96c132/_embedded_binaries/libunix.so: /home/cynthia/.cache/bazel/_bazel_cynthia/install/6a615f09339464d6ea7e8fe00f96c132/_embedded_binaries/libunix.so: wrong ELF class: ELFCLASS64 (Possible cause: architecture word width mismatch). Possibly your installation has been corrupted; if this problem persists, try 'rm -fr /home/cynthia/.cache/bazel/_bazel_cynthia/install/6a615f09339464d6ea7e8fe00f96c132'.
java.lang.UnsatisfiedLinkError: /home/cynthia/.cache/bazel/_bazel_cynthia/install/6a615f09339464d6ea7e8fe00f96c132/_embedded_binaries/libunix.so: /home/cynthia/.cache/bazel/_bazel_cynthia/install/6a615f09339464d6ea7e8fe00f96c132/_embedded_binaries/libunix.so: wrong ELF class: ELFCLASS64 (Possible cause: architecture word width mismatch)
at java.lang.ClassLoader$NativeLibrary.load(Native Method)
at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
at java.lang.Runtime.loadLibrary0(Runtime.java:870)
at java.lang.System.loadLibrary(System.java:1122)
at com.google.devtools.build.lib.UnixJniLoader.loadJni(UnixJniLoader.java:28)
at com.google.devtools.build.lib.unix.ProcessUtils.(ProcessUtils.java:28)
at com.google.devtools.build.lib.util.ProcessUtils.getpid(ProcessUtils.java:47)
at com.google.devtools.build.lib.util.OsUtils.forceJNI(OsUtils.java:55)
at com.google.devtools.build.lib.util.OsUtils.maybeForceJNI(OsUtils.java:43)
at com.google.devtools.build.lib.runtime.BlazeRuntime.newRuntime(BlazeRuntime.java:934)
at com.google.devtools.build.lib.runtime.BlazeRuntime.createBlazeRPCServer(BlazeRuntime.java:838)
at com.google.devtools.build.lib.runtime.BlazeRuntime.serverMain(BlazeRuntime.java:777)
at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:565)
at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:57)

**Comment by prb12** [comment]
Superficially, this looks like a 32/64 bit problem with bazel or java JDK installation.  Could you please double check that you followed the instructions here https://bazel.build/versions/master/docs/install.html

**Comment by asimshankar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by Yevgnen** [comment]
Similar here on ubuntu 16.04 with output

```
(deep) user@user:~/Downloads/tensorflow-1.1.0$ ./configure
Please specify the location of python. [Default is /home/user/.virtualenvs/deep/bin/python]:
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]:
Do you wish to use jemalloc as the malloc implementation? [Y/n]
jemalloc enabled
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N]
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N]
No Hadoop File System support will be enabled for TensorFlow
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N]
No XLA support will be enabled for TensorFlow
Found possible Python library paths:
  /home/user/.virtualenvs/deep/lib/python3.6/site-packages
Please input the desired Python library path to use.  Default is [/home/user/.virtualenvs/deep/lib/python3.6/site-packages]

Using python library path: /home/user/.virtualenvs/deep/lib/python3.6/site-packages
Do you wish to build TensorFlow with OpenCL support? [y/N]
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N]
No CUDA support will be enabled for TensorFlow
Configuration finished
...........
unexpected pipe read status: (error: 2): No such file or directory
Server presumed dead. Now printing '/home/user/.cache/bazel/_bazel_user/143f576e9f98f3e1c355aa517023abba/server/jvm.out':
java.lang.ExceptionInInitializerError
	at java.lang.J9VMInternals.ensureError(J9VMInternals.java:141)
	at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:130)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.skyFunctions(SkyframeExecutor.java:351)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.init(SkyframeExecutor.java:578)
	at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.init(SequencedSkyframeExecutor.java:249)
	at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.create(SequencedSkyframeExecutor.java:208)
	at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.create(SequencedSkyframeExecutor.java:156)
	at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutorFactory.create(SequencedSkyframeExecutorFactory.java:50)
	at com.google.devtools.build.lib.runtime.WorkspaceBuilder.build(WorkspaceBuilder.java:86)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.initWorkspace(BlazeRuntime.java:204)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.newRuntime(BlazeRuntime.java:1011)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.createBlazeRPCServer(BlazeRuntime.java:838)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.serverMain(BlazeRuntime.java:777)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:565)
	at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:57)
Caused by: java.lang.ClassCastException: com.ibm.lang.management.UnixExtendedOperatingSystem incompatible with com.sun.management.OperatingSystemMXBean
	at com.google.devtools.build.lib.util.ResourceUsage.<clinit>(ResourceUsage.java:45)
	... 13 more
```

I have no idea about which file is not found according to `unexpected pipe read status: (error: 2): No such file or directory`.

**Comment by denisalevi** [comment]
Had the same error as @Yevgnen. Using the 'testing' version of babel instead of the 'stable' version solved it for me (see [this section in the install instructions](https://bazel.build/versions/master/docs/install-ubuntu.html#1-add-bazel-distribution-uri-as-a-package-source-one-time-setup)).

If it helps, I'm on
```
Distributor ID: LinuxMint
Description:    Linux Mint 18.1 Serena
Release:        18.1
Codename:       serena
```
with
```
Linux version 4.4.0-53-generic (buildd@lcy01-28) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016
```

**Comment by jingw222** [comment]
@prb12 same issue here. I installed Bazel using custom APT repository. Do I have to install Java JDK then?

**Comment by Chejo-gt** [comment]
Hello I had the same issue, I uninstall jdk 1.9, checked that was installed JDK 1.8 after it installed open jdk 1.8 and finally it works.  Check this https://alliseesolutions.wordpress.com/2016/09/08/install-gpu-tensorflow-from-sources-w-ubuntu-16-04-and-cuda-8-0-rc/

**Comment by kylehounslow** [comment]
I had this issue:  
  
`Extracting Bazel installation...
..........
unexpected pipe read status: (error: 2): No such file or directory
Server presumed dead. Now printing '/home/kyle/.cache/bazel/_bazel_kyle/c7d12c37ed7a4d74cf8d7e2aae5a727d/server/jvm.out':
java.lang.ExceptionInInitializerError
	at java.lang.J9VMInternals.ensureError(J9VMInternals.java:141)
	at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:130)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.skyFunctions(SkyframeExecutor.java:348)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.init(SkyframeExecutor.java:586)
	at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.init(SequencedSkyframeExecutor.java:252)
	at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.create(SequencedSkyframeExecutor.java:211)
	at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.create(SequencedSkyframeExecutor.java:162)
	at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutorFactory.create(SequencedSkyframeExecutorFactory.java:48)
	at com.google.devtools.build.lib.runtime.WorkspaceBuilder.build(WorkspaceBuilder.java:81)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.initWorkspace(BlazeRuntime.java:204)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.newRuntime(BlazeRuntime.java:1023)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.createBlazeRPCServer(BlazeRuntime.java:850)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.serverMain(BlazeRuntime.java:789)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:570)
	at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:56)
Caused by: java.lang.ClassCastException: com.ibm.lang.management.UnixExtendedOperatingSystem incompatible with com.sun.management.OperatingSystemMXBean
	at com.google.devtools.build.lib.util.ResourceUsage.<clinit>(ResourceUsage.java:45)
	... 13 more`

Turns out I simply did not have jdk1.8 installed. Looks like the custom APT installation does not include this by default. 
  Solved by `sudo apt-get install openjdk-8-jdk`.

**Comment by bendaf** [comment]
I had the same issue. Installing jdk manually solved the issue.
