### ISSUE TITLE
Error while install tensorflow via recommended method on Getting Started guide

### ISSUE THREAD

**Issue by abhi18av** [tensorflow/tensorflow#8096]
I'm having trouble install the Tensorflow engine via  `conda` and `pip3`. I'm pasting the information regarding the python toolchain and the system I'm trying to install on.

```sh
❯ conda install -c conda-forge tensorflow
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /Users/eklavya/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    tensorflow-1.0.0           |           py35_0        32.7 MB  conda-forge

The following NEW packages will be INSTALLED:

    mock:       2.0.0-py35_0  conda-forge
    pbr:        1.10.0-py35_0 conda-forge
    protobuf:   3.2.0-py35_0  conda-forge
    tensorflow: 1.0.0-py35_0  conda-forge

The following packages will be SUPERCEDED by a higher-priority channel:

    conda:      4.2.13-py35_0             --> 4.2.13-py35_0 conda-forge
    conda-env:  2.6.0-0                   --> 2.6.0-0       conda-forge

Proceed ([y]/n)? y

Fetching packages ...
An unexpected error has occurred.#####################################################                 | ETA:  0:02:21  50.21 kB/s
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 1.21.3
         python version : 3.5.2.final.0
       requests version : 2.10.0
       root environment : /Users/eklavya/anaconda  (writable)
    default environment : /Users/eklavya/anaconda
       envs directories : /Users/eklavya/anaconda/envs
          package cache : /Users/eklavya/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False



`$ /Users/eklavya/anaconda/bin/conda install -c conda-forge tensorflow`




    Traceback (most recent call last):
      File "/Users/eklavya/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 228, in _error_catcher
        yield
      File "/Users/eklavya/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 310, in read
        data = self._fp.read(amt)
      File "/Users/eklavya/anaconda/lib/python3.5/http/client.py", line 448, in read
        n = self.readinto(b)
      File "/Users/eklavya/anaconda/lib/python3.5/http/client.py", line 488, in readinto
        n = self.fp.readinto(b)
      File "/Users/eklavya/anaconda/lib/python3.5/socket.py", line 575, in readinto
        return self._sock.recv_into(b)
      File "/Users/eklavya/anaconda/lib/python3.5/ssl.py", line 929, in recv_into
        return self.read(nbytes, buffer)
      File "/Users/eklavya/anaconda/lib/python3.5/ssl.py", line 791, in read
        return self._sslobj.read(len, buffer)
      File "/Users/eklavya/anaconda/lib/python3.5/ssl.py", line 575, in read
        v = self._sslobj.read(len, buffer)
    socket.timeout: The read operation timed out
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/eklavya/anaconda/lib/python3.5/site-packages/requests/models.py", line 664, in generate
        for chunk in self.raw.stream(chunk_size, decode_content=True):
      File "/Users/eklavya/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 353, in stream
        data = self.read(amt=amt, decode_content=decode_content)
      File "/Users/eklavya/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 320, in read
        flush_decoder = True
      File "/Users/eklavya/anaconda/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/Users/eklavya/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 233, in _error_catcher
        raise ReadTimeoutError(self._pool, None, 'Read timed out.')
    requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/eklavya/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 421, in download
        for chunk in resp.iter_content(2**14):
      File "/Users/eklavya/anaconda/lib/python3.5/site-packages/requests/models.py", line 671, in generate
        raise ConnectionError(e)
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/eklavya/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/Users/eklavya/anaconda/lib/python3.5/site-packages/conda/plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/Users/eklavya/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 135, in execute_instructions
        cmd(state, arg)
      File "/Users/eklavya/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "/Users/eklavya/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 353, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "/Users/eklavya/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 440, in download
        raise CondaRuntimeError("Could not open %r for writing (%s)." % (pp, e))
    conda.exceptions.CondaRuntimeError: Runtime error: Could not open '/Users/eklavya/anaconda/pkgs/tensorflow-1.0.0-py35_0.tar.bz2.part' for writing (HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.).
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/eklavya/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/eklavya/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/Users/eklavya/anaconda/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/eklavya/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 422, in install
        raise CondaSystemExit('Exiting', e)
      File "/Users/eklavya/anaconda/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/Users/eklavya/anaconda/lib/python3.5/site-packages/conda/cli/common.py", line 573, in json_progress_bars
        yield
      File "/Users/eklavya/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open '/Users/eklavya/anaconda/pkgs/tensorflow-1.0.0-py35_0.tar.bz2.part' for writing (HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.).

```
### Environment info
Operating System:

```sh
❯ uname -a
Darwin abhinavs-MBP.Home 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
                                                                                                                                  
```
### Other attempts

I've also tried installing via the pip3 package
```sh
❯ pip3 install tensorflow    
Collecting tensorflow
  Could not find a version that satisfies the requirement tensorflow (from versions: )
No matching distribution found for tensorflow
                                                                                                                                  
~   
❯ pip3 install tensorflow-gpu
Collecting tensorflow-gpu
  Could not find a version that satisfies the requirement tensorflow-gpu (from versions: )
No matching distribution found for tensorflow-gpu
                                                                                                                                  
```

**Comment by abhi18av** [comment]
Tried the alternative suggested by the site

The first part is completed without issues
```sh
~   
❯ export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/gpu/tensorflow_gpu-0.12.1-py3-none-any.whl
                                                                                                                                  
~   
❯ pip3 install --ignore-installed --upgrade $TF_BINARY_URL
Collecting tensorflow-gpu==0.12.1 from https://storage.googleapis.com/tensorflow/mac/gpu/tensorflow_gpu-0.12.1-py3-none-any.whl
  Downloading https://storage.googleapis.com/tensorflow/mac/gpu/tensorflow_gpu-0.12.1-py3-none-any.whl (83.6MB)
    100% |████████████████████████████████| 83.6MB 6.9kB/s 
Collecting protobuf>=3.1.0 (from tensorflow-gpu==0.12.1)
  Downloading protobuf-3.2.0-py2.py3-none-any.whl (360kB)
    100% |████████████████████████████████| 368kB 71kB/s 
Collecting six>=1.10.0 (from tensorflow-gpu==0.12.1)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting wheel>=0.26 (from tensorflow-gpu==0.12.1)
  Downloading wheel-0.29.0-py2.py3-none-any.whl (66kB)
    100% |████████████████████████████████| 71kB 78kB/s 
Collecting numpy>=1.11.0 (from tensorflow-gpu==0.12.1)
  Downloading numpy-1.12.0-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (4.4MB)
    100% |████████████████████████████████| 4.4MB 50kB/s 
Collecting setuptools (from protobuf>=3.1.0->tensorflow-gpu==0.12.1)
  Downloading setuptools-34.3.1-py2.py3-none-any.whl (389kB)
    100% |████████████████████████████████| 399kB 78kB/s 
Collecting appdirs>=1.4.0 (from setuptools->protobuf>=3.1.0->tensorflow-gpu==0.12.1)
  Downloading appdirs-1.4.2-py2.py3-none-any.whl
Collecting packaging>=16.8 (from setuptools->protobuf>=3.1.0->tensorflow-gpu==0.12.1)
  Downloading packaging-16.8-py2.py3-none-any.whl
Collecting pyparsing (from packaging>=16.8->setuptools->protobuf>=3.1.0->tensorflow-gpu==0.12.1)
  Downloading pyparsing-2.1.10-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 63kB/s 
Installing collected packages: six, appdirs, pyparsing, packaging, setuptools, protobuf, wheel, numpy, tensorflow-gpu
Successfully installed appdirs-1.4.2 numpy-1.12.0 packaging-16.8 protobuf-3.2.0 pyparsing-2.1.10 setuptools-34.3.1 six-1.10.0 tensorflow-gpu-0.12.1 wheel-0.29.0
```

But when I actually try to import tensorflow, the session raises the following error

```python3

~
❯ python3
Python 3.5.2 |Anaconda custom (x86_64)| (default, Jul  2 2016, 17:52:12)
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "/Users/eklavya/anaconda/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/eklavya/anaconda/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/Users/eklavya/anaconda/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/Users/eklavya/anaconda/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/eklavya/anaconda/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/eklavya/anaconda/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): Library not loaded: @rpath/libcudart.8.0.dylib
  Referenced from: /Users/eklavya/anaconda/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/eklavya/anaconda/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/eklavya/anaconda/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 60, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Users/eklavya/anaconda/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/eklavya/anaconda/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/Users/eklavya/anaconda/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/Users/eklavya/anaconda/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/eklavya/anaconda/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/eklavya/anaconda/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): Library not loaded: @rpath/libcudart.8.0.dylib
  Referenced from: /Users/eklavya/anaconda/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so
  Reason: image not found


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.
>>>
```

**Comment by prb12** [comment]
Could you please clarify exactly which instructions you are following?

I infer from the error messages above that you are running on Mac.  Are you following the instructions here: https://www.tensorflow.org/install/install_mac ?

Your output suggests that you are alternating between a CPU-only installation and a GPU enabled installation which is unable to find the Nvidia CUDA8 libraries.  Could you double-check the section entitled 'Requirements to run TensorFlow with GPU support' on that page?

**Comment by abhi18av** [comment]
@prb12 

Yes, you are right. I tried installing the the gpu version once the first install failed.

Moreover when I tried uninstalling the `tensorflow` it raised `not installed` error

```sh
❯ pip3 uninstall tensorflow
Cannot uninstall requirement tensorflow, not installed
```

Nor can I install tensorflow again.
```sh
❯ pip3 install tensorflow
Collecting tensorflow
  Could not find a version that satisfies the requirement tensorflow (from versions: )
No matching distribution found for tensorflow
```

**Comment by abhi18av** [comment]
So, I ran the command again.

```sh 

> sudo pip3 install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.0.0-py3-none-any.whl
```
And it install without issues.

But raises the same error while importing the tensorflow package in a session.

**Comment by prb12** [comment]
@abhi18av I suspect that your original problem was due to trying to `import tensorflow` while running python in a directory with a subdir named tensorflow?  Could you please try this in a different directory?

```
❯ pip3 uninstall tensorflow
Cannot uninstall requirement tensorflow, not installed
```
This is mentioned in the instructions on https://www.tensorflow.org/install/install_mac:
> Optional. If Step 5 failed (typically because you invoked a pip version lower than 8.1), install TensorFlow in the active virtualenv environment by issuing a command of the following format...

**Comment by abhi18av** [comment]
@prb12 not really. I know that it mentions "using from diff directory" but I was trying to invoke it from the default shell log in - `~/ `

**Comment by abhi18av** [comment]
However it mentions that my `pip` is out of date.

```sh

   99% |████████████████████████████████| 39.3MB 50kB/s eta 0:0    99% |████████████████████████████████| 39.3MB 53kB/s eta 0:0    99% |████████████████████████████████| 39.3MB 50kB/s eta 0:0    100% |████████████████████████████████| 39.4MB 20kB/s 
Requirement already up-to-date: six>=1.10.0 in /usr/local/lib/python3.5/site-packages (from tensorflow==1.0.0)
Requirement already up-to-date: wheel>=0.26 in /usr/local/lib/python3.5/site-packages (from tensorflow==1.0.0)
Requirement already up-to-date: numpy>=1.11.0 in /usr/local/lib/python3.5/site-packages (from tensorflow==1.0.0)
Requirement already up-to-date: protobuf>=3.1.0 in /usr/local/lib/python3.5/site-packages (from tensorflow==1.0.0)
Requirement already up-to-date: setuptools in /usr/local/lib/python3.5/site-packages (from protobuf>=3.1.0->tensorflow==1.0.0)
Requirement already up-to-date: packaging>=16.8 in /usr/local/lib/python3.5/site-packages (from setuptools->protobuf>=3.1.0->tensorflow==1.0.0)
Requirement already up-to-date: appdirs>=1.4.0 in /usr/local/lib/python3.5/site-packages (from setuptools->protobuf>=3.1.0->tensorflow==1.0.0)
Requirement already up-to-date: pyparsing in /usr/local/lib/python3.5/site-packages (from packaging>=16.8->setuptools->protobuf>=3.1.0->tensorflow==1.0.0)
Installing collected packages: tensorflow
  Found existing installation: tensorflow 1.0.0
    Uninstalling tensorflow-1.0.0:
      Successfully uninstalled tensorflow-1.0.0
Successfully installed tensorflow-1.0.0
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
                                                                
~   725s

```
But the pip versions for both python2 and python3 are up to date. Can't figure out the issue.

```sh
❯ pip --version
pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
                                                                
~   
❯ pip3 --version
pip 9.0.1 from /Users/eklavya/anaconda/lib/python3.5/site-packages (python 3.5)
                                                                
~   
❯ 
```

@prb12 I appreciate you time 👍

**Comment by prb12** [comment]
This thread is getting very confused by lots of different unrelated symptoms.

Let's focus on your comment from 5 days ago, where you successfully installed tensorflow and then when you tried to `import tensorflow` but got an error.

When I scroll your console output to the right, I notice that the long line with the error message is talking about trying to load the CUDA8.0 runtime:

```
ImportError: dlopen(/Users/eklavya/anaconda/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): Library not loaded: @rpath/libcudart.8.0.dylib
  Referenced from: /Users/eklavya/anaconda/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so
  Reason: image not found
```

Are you sure that a) you installed the CUDA8.0 runtime correctly, and b) are the cuda libraries on you `LD_LIBRARY_PATH` environment variable?

**Comment by abhi18av** [comment]
@prb12 , I am happy to report that the installation finally got working though I have no idea how.
The only difference there was between running the basic `conda install` again was different - updated - versions of pip3.

```sh

❯ conda install -c conda-forge tensorflow
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /Users/eklavya/anaconda:

The following NEW packages will be INSTALLED:

    mock:       2.0.0-py35_0  conda-forge
    pbr:        1.10.0-py35_0 conda-forge
    protobuf:   3.2.0-py35_0  conda-forge
    tensorflow: 1.0.0-py35_0  conda-forge

The following packages will be SUPERCEDED by a higher-priority channel:

    conda:      4.3.14-py35_0             --> 4.2.13-py35_0 conda-forge
    conda-env:  2.6.0-0                   --> 2.6.0-0       conda-forge

Proceed ([y]/n)? y

tensorflow-1.0 100% |##################################################################################| Time: 0:00:26   1.31 MB/s
                                                                                                                                  
~   104s
❯ refresh
```

Able to import the library now.

```python3                                                                                                                                  
~   
❯ python3
Python 3.5.2 |Anaconda custom (x86_64)| (default, Jul  2 2016, 17:52:12) 
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
>>> 
```



As far as the error regarding the lack of CUDA-8 installation, unfortunately I'm unable to update to macOS Sierra ( req. for CUDA-8 ) for a couple months more at least so I'll have to make do with the CPU version. 


I'll close this issue as the issue has been sorted out, but please do comment your views on what might've caused the trouble in the first place.


The fact that it throws up some "Tensorflow library wasn't compiled with..." might be relevant for a future reader.


```python

>>> import tensorflow as tf
>>> 
>>> # Simple hello world using TensorFlow
... 
>>> # Create a Constant op
... # The op is added as a node to the default graph.
... #
... # The value returned by the constructor represents the output
... # of the Constant op.
... hello = tf.constant('Hello, TensorFlow!')
>>> 
>>> # Start tf session
... sess = tf.Session()
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
>>> 
>>> # Run the op
... print(sess.run(hello))
b'Hello, TensorFlow!'
>>> 
```

**Comment by abhi18av** [comment]
Thank you @prb12 @aselle  for you time and patience. I appreciate it 👍

**Comment by abhi18av** [comment]
Relevant issues

https://github.com/tensorflow/tensorflow/issues/7778

https://github.com/tensorflow/tensorflow/issues/7778

**Comment by mukta121** [comment]
I am having same issues issues am i am not able to install  tensorflow on anaconda .Error my mac throws is  The directory '/Users/muktamani/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/muktamani/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

But I could sort out with conda install -c conda-forge tensorflow
Thanks @abhi18av

**Comment by SuMyatNoe29** [comment]
I've trying so many tools to install TensorFlow on my mac. But I finally installed with this conda environment. Thanks bro!

**Comment by feiwww** [comment]
I had same problem when using virtulenv, but I installed tensorflow successfully after try "**sudo pip install --default-timeout=100 future**".
