### ISSUE TITLE
Error when calling tf.train.Save()

### ISSUE THREAD

**Issue by Narukamiko** [tensorflow/tensorflow#8152]
```
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key q_network/Variable_1 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key q_network/Variable_2 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key q_network/Variable_7 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key q_network/Variable_3 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key q_network/Variable_5 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key q_network/Variable_4 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key q_network/Variable_6 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key q_network/Variable not found in checkpoint
Traceback (most recent call last):
  File "AI_control_4layer.py", line 191, in <module>
    restore_net(sess,path)
  File "AI_control_4layer.py", line 108, in restore_net
    saver.restore(sess, path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1439, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key q_network/Variable_1 not found in checkpoint
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]

Caused by op u'save/RestoreV2_1', defined at:
  File "AI_control_4layer.py", line 191, in <module>
    restore_net(sess,path)
  File "AI_control_4layer.py", line 107, in restore_net
    saver = tf.train.Saver()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1051, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1081, in build
    restore_sequentially=self._restore_sequentially)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 675, in build
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 402, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 242, in restore_op
    [spec.tensor.dtype])[0])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 668, in restore_v2
    dtypes=dtypes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Key q_network/Variable_1 not found in checkpoint
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]
```

How can I solve it?

**Comment by MicaelCarvalho** [comment]
Please follow guidelines for posting issues, or at least enclose your _things_ in code/quote/etc formatting.

Your problem is probably related to variables in your graph that didn't exist when you saved your checkpoint, meaning they can't be loaded because they weren't there before.

**Comment by prb12** [comment]
As @MicaelCarvalho says, please can you try deleting your checkpoint.

**Comment by asimshankar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
