### ISSUE TITLE
runtime error of combing tensorflow CTC and SynthText

### ISSUE THREAD

**Issue by chuckbasstan123** [tensorflow/tensorflow#8176]
Hi,

I met a runtime error during training when I tried to applied **tensorflow built-in CTC** loss function  (https://www.tensorflow.org/versions/r0.10/api_docs/python/nn/conectionist_temporal_classification__ctc_) to **SynthText dataset**. http://www.robots.ox.ac.uk/~vgg/data/scenetext/ 
It said " Not enough time for target transition sequence (required: 4, available: 0)". 
Here is the some info for environment: tensorflow version '0.12.0-rc0'.

I am able to apply **tensorflow built-in CTC** to **Synth90K Dataset** with great performance (http://www.robots.ox.ac.uk/~vgg/data/text/). 

It seems like the **SynthText dataset** is not compilable with **tensorflow built-in CTC** but **Synth90K Dataset** could. 

Please find the error message as reference

step 980, loss = 50.17 (92.1 examples/sec; 0.695 sec/batch)
W tensorflow/core/framework/op_kernel.cc:975] Invalid argument: Not enough time for target transition sequence (required: 4, available: 0), skipping data instance in batch: 28
Traceback (most recent call last):
  File "multi-gpu-train.py", line 305, in <module>
    tf.app.run()
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "multi-gpu-train.py", line 301, in main
    train()
  File "multi-gpu-train.py", line 270, in train
    _, loss_value = sess.run([train_op, loss])
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Not enough time for target transition sequence (required: 4, available: 0), skipping data instance in batch: 28
	 [[Node: tower_0/CTCLoss = CTCLoss[ctc_merge_repeated=true, preprocess_collapse_repeated=false, _device="/job:localhost/replica:0/task:0/cpu:0"](tower_0/transpose_2/_555, tower_0/Where, tower_0/sub_2/_557, tower_0/Sum_1/_559)]]

Caused by op u'tower_0/CTCLoss', defined at:
  File "multi-gpu-train.py", line 305, in <module>
    tf.app.run()
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "multi-gpu-train.py", line 301, in main
    train()
  File "multi-gpu-train.py", line 179, in train
    loss,logits_op,images,labels = tower_loss(scope)
  File "multi-gpu-train.py", line 79, in tower_loss
    _ = network2.loss(logits,images, labels)
  File "/home/ubuntu/experiments/network2_dev/network2.py", line 61, in loss
    out = tf.nn.ctc_loss(logit, to_sparse(y), seq_len, time_major=False)
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/ctc_ops.py", line 145, in ctc_loss
    ctc_merge_repeated=ctc_merge_repeated)
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_ctc_ops.py", line 164, in _ctc_loss
    name=name)
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2240, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Not enough time for target transition sequence (required: 4, available: 0), skipping data instance in batch: 28
	 [[Node: tower_0/CTCLoss = CTCLoss[ctc_merge_repeated=true, preprocess_collapse_repeated=false, _device="/job:localhost/replica:0/task:0/cpu:0"](tower_0/transpose_2/_555, tower_0/Where, tower_0/sub_2/_557, tower_0/Sum_1/_559)]]

**Comment by prb12** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
