### ISSUE TITLE
Bug in contrib/tensor_forest/python/tensor_forest_test.py

### ISSUE THREAD

**Issue by artzers** [tensorflow/tensorflow#8229]
My environment is Win7 x64, python 3.5, tensorflow r1.0 GPU version.
I download contrib/tensor_forest/python/tensor_forest_test.py and run 'python test.py' in console.  Then the following error information shows:

..E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\co
re\framework\op_kernel.cc:943] OpKernel ('op: "BestSplits" device_type: "CPU"')
for unknown op: BestSplits
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "CountExtremelyRandomStats" device_t
ype: "CPU"') for unknown op: CountExtremelyRandomStats
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "FinishedNodes" device_type: "CPU"')
 for unknown op: FinishedNodes
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "GrowTree" device_type: "CPU"') for
unknown op: GrowTree
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "ReinterpretStringToFloat" device_ty
pe: "CPU"') for unknown op: ReinterpretStringToFloat
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "SampleInputs" device_type: "CPU"')
for unknown op: SampleInputs
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "ScatterAddNdim" device_type: "CPU"'
) for unknown op: ScatterAddNdim
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "TopNInsert" device_type: "CPU"') fo
r unknown op: TopNInsert
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "TopNRemove" device_type: "CPU"') fo
r unknown op: TopNRemove
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "TreePredictions" device_type: "CPU"
') for unknown op: TreePredictions
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "UpdateFertileSlots" device_type: "C
PU"') for unknown op: UpdateFertileSlots
.EEEEE.
======================================================================
ERROR: testInferenceConstruction (__main__.TensorForestTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\test.py", line 90, in testInferenceConstruction
    graph = graph_builder.inference_graph(input_data)
  File "F:\Anaconda3\lib\site-packages\tensorflow\contrib\tensor_forest\python\t
ensor_forest.py", line 459, in inference_graph
    **inference_args))
  File "F:\Anaconda3\lib\site-packages\tensorflow\contrib\tensor_forest\python\t
ensor_forest.py", line 958, in inference_graph
    valid_leaf_threshold=self.params.valid_leaf_threshold)
  File "F:\Anaconda3\lib\site-packages\tensorflow\contrib\tensor_forest\python\o
ps\gen_tensor_forest_ops.py", line 662, in tree_predictions
    name=name)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_librar
y.py", line 763, in apply_op
    op_def=op_def)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line
 2397, in create_op
    set_shapes_for_outputs(ret)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line
 1757, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line
 1707, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes
.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes
.py", line 670, in _call_cpp_shape_fn_impl
    status)
  File "F:\Anaconda3\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.p
y", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'T
reePredictions'

======================================================================
ERROR: testInferenceConstructionSparse (__main__.TensorForestTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\test.py", line 143, in testInferenceConstructionSparse
    graph = graph_builder.inference_graph(input_data)
  File "F:\Anaconda3\lib\site-packages\tensorflow\contrib\tensor_forest\python\t
ensor_forest.py", line 459, in inference_graph
    **inference_args))
  File "F:\Anaconda3\lib\site-packages\tensorflow\contrib\tensor_forest\python\t
ensor_forest.py", line 958, in inference_graph
    valid_leaf_threshold=self.params.valid_leaf_threshold)
  File "F:\Anaconda3\lib\site-packages\tensorflow\contrib\tensor_forest\python\o
ps\gen_tensor_forest_ops.py", line 662, in tree_predictions
    name=name)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_librar
y.py", line 763, in apply_op
    op_def=op_def)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line
 2397, in create_op
    set_shapes_for_outputs(ret)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line
 1757, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line
 1707, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes
.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes
.py", line 670, in _call_cpp_shape_fn_impl
    status)
  File "F:\Anaconda3\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.p
y", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'T
reePredictions'

======================================================================
ERROR: testTrainingConstructionClassification (__main__.TensorForestTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\test.py", line 58, in testTrainingConstructionClassification
    graph = graph_builder.training_graph(input_data, input_labels)
  File "F:\Anaconda3\lib\site-packages\tensorflow\contrib\tensor_forest\python\t
ensor_forest.py", line 425, in training_graph
    **tree_kwargs))
  File "F:\Anaconda3\lib\site-packages\tensorflow\contrib\tensor_forest\python\t
ensor_forest.py", line 705, in training_graph
    regression=self.params.regression))
  File "F:\Anaconda3\lib\site-packages\tensorflow\contrib\tensor_forest\python\o
ps\gen_tensor_forest_ops.py", line 224, in count_extremely_random_stats
    regression=regression, name=name)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_librar
y.py", line 763, in apply_op
    op_def=op_def)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line
 2397, in create_op
    set_shapes_for_outputs(ret)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line
 1757, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line
 1707, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes
.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes
.py", line 670, in _call_cpp_shape_fn_impl
    status)
  File "F:\Anaconda3\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.p
y", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'C
ountExtremelyRandomStats'

======================================================================
ERROR: testTrainingConstructionClassificationSparse (__main__.TensorForestTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\test.py", line 120, in testTrainingConstructionClassificationSparse
    graph = graph_builder.training_graph(input_data, input_labels)
  File "F:\Anaconda3\lib\site-packages\tensorflow\contrib\tensor_forest\python\t
ensor_forest.py", line 425, in training_graph
    **tree_kwargs))
  File "F:\Anaconda3\lib\site-packages\tensorflow\contrib\tensor_forest\python\t
ensor_forest.py", line 705, in training_graph
    regression=self.params.regression))
  File "F:\Anaconda3\lib\site-packages\tensorflow\contrib\tensor_forest\python\o
ps\gen_tensor_forest_ops.py", line 224, in count_extremely_random_stats
    regression=regression, name=name)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_librar
y.py", line 763, in apply_op
    op_def=op_def)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line
 2397, in create_op
    set_shapes_for_outputs(ret)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line
 1757, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line
 1707, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes
.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes
.py", line 670, in _call_cpp_shape_fn_impl
    status)
  File "F:\Anaconda3\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.p
y", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'C
ountExtremelyRandomStats'

======================================================================
ERROR: testTrainingConstructionRegression (__main__.TensorForestTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\test.py", line 75, in testTrainingConstructionRegression
    graph = graph_builder.training_graph(input_data, input_labels)
  File "F:\Anaconda3\lib\site-packages\tensorflow\contrib\tensor_forest\python\t
ensor_forest.py", line 425, in training_graph
    **tree_kwargs))
  File "F:\Anaconda3\lib\site-packages\tensorflow\contrib\tensor_forest\python\t
ensor_forest.py", line 705, in training_graph
    regression=self.params.regression))
  File "F:\Anaconda3\lib\site-packages\tensorflow\contrib\tensor_forest\python\o
ps\gen_tensor_forest_ops.py", line 224, in count_extremely_random_stats
    regression=regression, name=name)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_librar
y.py", line 763, in apply_op
    op_def=op_def)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line
 2397, in create_op
    set_shapes_for_outputs(ret)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line
 1757, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line
 1707, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes
.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes
.py", line 670, in _call_cpp_shape_fn_impl
    status)
  File "F:\Anaconda3\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.p
y", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'C
ountExtremelyRandomStats'

----------------------------------------------------------------------
Ran 9 tests in 2.945s

FAILED (errors=5)

**Comment by mrry** [comment]
Support for the `tf.contrib.tensor_forest` submodule was not included in TensorFlow 1.0, but it has been fixed at HEAD. Can you try upgrading to a nightly build of TensorFlow and see if the problem persists?

**Comment by artzers** [comment]
@mrry  well, it is OK using nightly version.
It shows:
 DeprecationWarning: Please use assertEqual instead. self.assertEquals(2, hparams.num_classes)
Ran 9 tests in 7.760s

OK

However this nightly version also show these warning info:

2017-03-09 12:45:53.258939: W c:\tf_jenkins\home\workspace\nightly-win\device\gp
u\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow li
brary wasn't compiled to use SSE instructions, but these are available on your m
achine and could speed up CPU computations.
2017-03-09 12:45:53.259939: W c:\tf_jenkins\home\workspace\nightly-win\device\gp
u\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow li
brary wasn't compiled to use SSE2 instructions, but these are available on your
machine and could speed up CPU computations.
2017-03-09 12:45:53.260939: W c:\tf_jenkins\home\workspace\nightly-win\device\gp
u\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow li
brary wasn't compiled to use SSE3 instructions, but these are available on your
machine and could speed up CPU computations.
2017-03-09 12:45:53.261939: W c:\tf_jenkins\home\workspace\nightly-win\device\gp
u\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow li
brary wasn't compiled to use SSE4.1 instructions, but these are available on you
r machine and could speed up CPU computations.
2017-03-09 12:45:53.262939: W c:\tf_jenkins\home\workspace\nightly-win\device\gp
u\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow li
brary wasn't compiled to use SSE4.2 instructions, but these are available on you
r machine and could speed up CPU computations.
2017-03-09 12:45:53.263939: W c:\tf_jenkins\home\workspace\nightly-win\device\gp
u\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow li
brary wasn't compiled to use AVX instructions, but these are available on your m
achine and could speed up CPU computations.
2017-03-09 12:45:53.263939: W c:\tf_jenkins\home\workspace\nightly-win\device\gp
u\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow li
brary wasn't compiled to use AVX2 instructions, but these are available on your
machine and could speed up CPU computations.
2017-03-09 12:45:53.264940: W c:\tf_jenkins\home\workspace\nightly-win\device\gp
u\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow li
brary wasn't compiled to use FMA instructions, but these are available on your m
achine and could speed up CPU computations.

So I continue to use tf r1.0 and wait for your good news.

**Comment by mrry** [comment]
It sounds like the issue has been fixed in that case. You can safely ignore the warnings about SSE and AVX in the nightly build...
