### ISSUE TITLE
Model in Android Studio app, written in Java. Unexpected failure when preparing tensor allocations

### ISSUE THREAD

**Issue by susiecamazotz** [tensorflow/tensorflow#82464]
Hi, i have problem in my Java app in Android studio, main issue is when model is used. Can someone help?

### 1. System information

- OS Platform: Windows 10
- TensorFlow library: TensorFlow version: 2.12.0

### Reference colab notebooks

https://colab.research.google.com/gist/ymodak/e96a4270b953201d5362c61c1e8b78aa/tensorflow-datasets.ipynb

### 2. Code

    private void performObjectDetection() {
        Log.d("ObjectDetection", "Starting object detection process...");
        String tfliteVersion = TensorFlowLite.runtimeVersion();
        Log.d("TensorFlowLite", "TensorFlow Lite Runtime Version: " + tfliteVersion);

        if (videoFeedView.getBitmap() != null) {
            Bitmap frameBitmap = videoFeedView.getBitmap();

            Log.d("ObjectDetection", "Frame captured for processing: " +
                    frameBitmap.getWidth() + "x" + frameBitmap.getHeight());

            try {
                // Preprocess the frame
                float[] inputTensor = preprocessFrame(frameBitmap);
                Log.d("ObjectDetection", "Input tensor prepared. Shape: [1, 640, 640, 3]");
                Log.d("ObjectDetection", "Input tensor size: " + inputTensor.length);
                Log.d("ObjectDetection", "First 10 tensor values: " +
                        inputTensor[0] + ", " + inputTensor[1] + ", " + inputTensor[2] + "...");

                // Initialize output tensor matching the model's output shape
                float[][][] outputTensor = new float[1][5][8400];

                // Allocate tensors and run inference
                try {
                    tfliteInterpreter.allocateTensors(); // Ensure tensors are allocated
                    Log.d("ObjectDetection", "Tensors allocated successfully.");
                    tfliteInterpreter.run(inputTensor, outputTensor);
                    Log.d("ObjectDetection", "Inference completed.");
                } catch (Exception e) {
                    Log.e("ObjectDetection", "Error during inference: ", e);
                    return;
                }

                // Process the model output
                processOutput(outputTensor);

            } catch (Exception e) {
                Log.e("ObjectDetection", "Error during preprocessing or detection: ", e);
            }
        } else {
            Log.w("ObjectDetection", "No frame available for processing.");
        }
    }

    private void processOutput(float[][][] outputTensor) {
        Log.d("ObjectDetection", "Processing output tensor...");

        // Iterate through detections
        for (int i = 0; i < outputTensor[0][4].length; i++) {
            float confidence = outputTensor[0][4][i]; // Confidence score

            if (confidence > 0.2) { // Adjust confidence threshold as needed
                float xCenter = outputTensor[0][0][i];
                float yCenter = outputTensor[0][1][i];
                float width = outputTensor[0][2][i];
                float height = outputTensor[0][3][i];

                Log.d("ObjectDetection", "Detection " + i + ": Confidence=" + confidence);

                // Convert YOLO format (x_center, y_center, width, height) to bounding box
                float left = xCenter - width / 2;
                float top = yCenter - height / 2;
                float right = xCenter + width / 2;
                float bottom = yCenter + height / 2;

                Log.d("ObjectDetection", "Bounding box - Left: " + left + ", Top: " + top +
                        ", Right: " + right + ", Bottom: " + bottom);

                // Update detection overlay (implement this method to draw bounding boxes)
                updateDetectionOverlay(left, top, right, bottom, "Detected Object");
            }
        }
    }

    private float[] preprocessFrame(Bitmap frameBitmap) {
        int modelInputSize = 640;

        // Resize the frame to 640x640 (no padding)
        Bitmap resizedBitmap = Bitmap.createScaledBitmap(frameBitmap, modelInputSize, modelInputSize, true);

        // Create a tensor for the input
        float[] inputTensor = new float[modelInputSize * modelInputSize * 3];
        int[] pixelValues = new int[modelInputSize * modelInputSize];
        resizedBitmap.getPixels(pixelValues, 0, modelInputSize, 0, 0, modelInputSize, modelInputSize);

        for (int i = 0; i < pixelValues.length; i++) {
            int pixel = pixelValues[i];

            // Normalize RGB values to [0, 1]
            inputTensor[i * 3] = ((pixel >> 16) & 0xFF) / 255.0f; // Red
            inputTensor[i * 3 + 1] = ((pixel >> 8) & 0xFF) / 255.0f; // Green
            inputTensor[i * 3 + 2] = (pixel & 0xFF) / 255.0f; // Blue
        }
        return inputTensor;
    }

    private void updateDetectionOverlay(float left, float top, float right, float bottom, String label) {
        detectionOverlayView.setBoundingBox(left, top, right, bottom, label);
    }

    private void clearDetectionOverlay() {
        detectionOverlayView.clearBoundingBox();
    }

    private MappedByteBuffer loadModelFile(Context context, String modelPath) throws IOException {
        AssetFileDescriptor fileDescriptor = context.getAssets().openFd(modelPath);
        FileInputStream inputStream = new FileInputStream(fileDescriptor.getFileDescriptor());
        FileChannel fileChannel = inputStream.getChannel();
        long startOffset = fileDescriptor.getStartOffset();
        long declaredLength = fileDescriptor.getDeclaredLength();
        return fileChannel.map(FileChannel.MapMode.READ_ONLY, startOffset, declaredLength);
    }

### 3. Logs from Logcat in Android Studio
2024-12-08 05:05:05.366  9739-9739  ObjectDetection         com.dji.sdk.sample                   D  Attempting to load TensorFlow Lite model...
2024-12-08 05:05:05.398  9739-9739  ObjectDetection         com.dji.sdk.sample                   D  TensorFlow Lite model loaded successfully.
2024-12-08 05:05:05.401  9739-9739  ObjectDetection         com.dji.sdk.sample                   D  Input shape: [1, 640, 640, 3]
2024-12-08 05:05:05.401  9739-9739  ObjectDetection         com.dji.sdk.sample                   D  Output shape: [1, 5, 8400]
2024-12-08 05:05:05.457  9739-9739  ObjectDetection         com.dji.sdk.sample                   D  Initialization complete.
2024-12-08 05:05:11.316  9739-9739  ObjectDetection         com.dji.sdk.sample                   D  Starting object detection...
2024-12-08 05:05:11.322  9739-9739  ObjectDetection         com.dji.sdk.sample                   D  Starting object detection process...
2024-12-08 05:05:11.369  9739-9739  ObjectDetection         com.dji.sdk.sample                   D  Frame captured for processing: 2292x1080
2024-12-08 05:05:11.422  9739-9739  ObjectDetection         com.dji.sdk.sample                   D  Input tensor prepared. Shape: [1, 640, 640, 3]
2024-12-08 05:05:11.422  9739-9739  ObjectDetection         com.dji.sdk.sample                   D  Input tensor size: 1228800
2024-12-08 05:05:11.422  9739-9739  ObjectDetection         com.dji.sdk.sample                   D  First 10 tensor values: 0.0, 0.0, 0.0...
2024-12-08 05:05:11.422  9739-9739  ObjectDetection         com.dji.sdk.sample                   D  Tensors allocated successfully.
2024-12-08 05:05:11.427  9739-9739  ObjectDetection         com.dji.sdk.sample                   E  Error during inference: 
                                                                                                    java.lang.IllegalStateException: Internal error: Unexpected failure when preparing tensor allocations: tensorflow/lite/kernels/pad.cc:79 SizeOfDimension(op_context->paddings, 0) != op_context->dims (4 != 1)
                                                                                                    Node number 0 (PAD) failed to prepare.
                                                                                                    	at org.tensorflow.lite.NativeInterpreterWrapper.allocateTensors(Native Method)
                                                                                                    	at org.tensorflow.lite.NativeInterpreterWrapper.allocateTensorsIfNeeded(:308)
                                                                                                    	at org.tensorflow.lite.NativeInterpreterWrapper.run(:248)
                                                                                                    	at org.tensorflow.lite.InterpreterImpl.runForMultipleInputsOutputs(:101)
                                                                                                    	at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(:77)
                                                                                                    	at org.tensorflow.lite.InterpreterImpl.run(:94)
                                                                                                    	at org.tensorflow.lite.Interpreter.run(:77)
                                                                                                    	at com.dji.sdk.sample.internal.view.FullScreenVideoViewZPI.performObjectDetection(:521)
                                                                                                    	at com.dji.sdk.sample.internal.view.FullScreenVideoViewZPI.access$900(:56)
                                                                                                    	at com.dji.sdk.sample.internal.view.FullScreenVideoViewZPI$5.run(:480)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:204)
                                                                                                    	at android.os.Looper.loop(Looper.java:291)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8134)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1019)

**Comment by gaikwadrahul8** [comment]
Hi, @susiecamazotz 
I apologize for the delayed response, I see you're using object detection model so I would suggest you to please have a look into this [TensorFlow Lite Object Detection Android Demo](https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android) example which may resolve your issue and to run that demo example successfully you'll have to change this line `distributionUrl=https\://services.gradle.org/distributions/gradle-8.4-bin.zip` to this `distributionUrl=https\://services.gradle.org/distributions/gradle-7.6.2-bin.zip` in `gradle-wrapper.properties` and things are working as expected

If your issue still persists please let us know with updated error log for further investigation, if possible could you please help us with your Github repo along with your model to replicate the same behaviour from our end ?

Thank you for your cooperation and patience.
