### ISSUE TITLE
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

### ISSUE THREAD

**Issue by kuluofenghun** [tensorflow/tensorflow#8267]
I am using tensorflow (1.0.0) in Ubuntu 14.04. When I train a cnn model ,I got a error as follow:

/usr/local/lib/python2.7/dist-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
2017-03-10 15:03:03,616 : INFO : building model...
Traceback (most recent call last):
  File "cnn.py", line 205, in <module>
    train()
  File "cnn.py", line 202, in train
    cnn_model.build_model(sentence_words, vector_length, num_classes, filter_sizes, num_filters)
  File "cnn.py", line 61, in build_model
    h_pool = tf.concat(3, pooled_outputs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1047, in concat
    dtype=dtypes.int32).get_shape(
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 651, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 716, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

How can I resolve this question?

**Comment by Geekking** [comment]
It's because of the tensorflow has updated the parameter order of concat,  you could try modifying to tf.concat(pooled_outputs, 3)

**Comment by prb12** [comment]
Please see the TF1.0 migration documentation https://www.tensorflow.org/install/migration

This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by stein2013** [comment]
Thank u! I solved it. @Geekking

**Comment by alexiskattan** [comment]
@stein2013 how did you solve it?

**Comment by cryptox31** [comment]
@alexiskattan just do a 
`git checkout master` in the /models/ directory it should update to the new tensorflow apis.
