### ISSUE TITLE
ImportError: No module named 'tensorflow.contrib.ffmpeg.ops'

### ISSUE THREAD

**Issue by gcoter** [tensorflow/tensorflow#8271]
### Environment info
Operating System: Windows 10

Installed version of CUDA and cuDNN: CUDA 8.0, cuDNN 5.1

If installed from binary pip package, provide:

1. A link to the pip package you installed: `tensorflow_gpu-1.0.1-cp35-cp35m-win_amd64.whl`
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`: 1.0.1

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

`python -c "from tensorflow.contrib import ffmpeg"`

Output:

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Guillaume COTER\Anaconda3\lib\site-packages\tensorflow\contrib\ffmpeg\__init__.py", line 26, in <module>
    from tensorflow.contrib.ffmpeg.ffmpeg_ops import decode_audio
  File "C:\Users\Guillaume COTER\Anaconda3\lib\site-packages\tensorflow\contrib\ffmpeg\ffmpeg_ops.py", line 23, in <module>
    from tensorflow.contrib.ffmpeg.ops import gen_decode_audio_op_py
ImportError: No module named 'tensorflow.contrib.ffmpeg.ops'`

**Comment by mrry** [comment]
The `tf.contrib.ffmpeg` ops aren't currently supported on Windows. As far as I remember, they rely on some POSIX-specific code for running a subprocess that would need to be ported to using `CreateProcess()`. I've assigned @fredbertsch, who's the owner of that code, to comment on the chances of this being supported on Windows in the future.

**Comment by Aesthetic** [comment]
Same question, any news on support?

**Comment by gunan** [comment]
@fredbertsch Any comments on windows support?

**Comment by vorkuta** [comment]
Having the same issue here on Win10. Everything else is working fine.

**Comment by Sylvus** [comment]
Same problem here, is there a workaround?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assigneee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
A member of the TensorFlow organization has replied after the stat:awaiting tensorflower label was applied.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by lostmsu** [comment]
@mrry irrespectively of support for the module itself, it breaks inspection module, as `ismodule` fails to inspect `tensorflow.contrib.ffmpeg` as a member of `tensorflow.contrib`
