### ISSUE TITLE
Can't generate documentations

### ISSUE THREAD

**Issue by marulitua** [tensorflow/tensorflow#8302]
I cannot run gen_docs.sh on my machine.

I already run the configuration script.

This is the last error message
http://sprunge.us/MVJS

I am using tensorflow 1.0 with CUDA capability
http://sprunge.us/dhQT

This is my list of CUDA libs
http://sprunge.us/Gdfh

I am on arch linux btw.

What sould i do ?

**Comment by prb12** [comment]
@marulitua None of the links in your issue report work for me.

Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by marulitua** [comment]
I am on Arch Linux 64 bit
`uname -a`
```
Linux singularity 4.10.1-1-ARCH #1 SMP PREEMPT Sun Feb 26 21:08:53 UTC 2017 x86_64 GNU/Linux
```

I am using tensorflow 1.0 with CUDA capability
`python -c "import tensorflow; print(tensorflow.__version__)"`
```
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
1.0.0
```

`ls -l /opt/cuda/lib64`
```
total 1415152
-rw-r--r-- 1 root root  53464088 Feb 28 18:43 libcublas_device.a
lrwxrwxrwx 1 root root        16 Feb 28 18:43 libcublas.so -> libcublas.so.8.0
lrwxrwxrwx 1 root root        19 Feb 28 18:43 libcublas.so.8.0 -> libcublas.so.8.0.61
-rwxr-xr-x 1 root root  42505456 Feb 28 18:43 libcublas.so.8.0.61
-rw-r--r-- 1 root root  49080634 Feb 28 18:43 libcublas_static.a
-rw-r--r-- 1 root root    556000 Feb 28 18:43 libcudadevrt.a
lrwxrwxrwx 1 root root        16 Feb 28 18:43 libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root root        19 Feb 28 18:43 libcudart.so.8.0 -> libcudart.so.8.0.61
-rwxr-xr-x 1 root root    415432 Feb 28 18:43 libcudart.so.8.0.61
-rw-r--r-- 1 root root    775162 Feb 28 18:43 libcudart_static.a
-rwxr-xr-x 1 root root  79337624 Dec 25 15:14 libcudnn.so
-rwxr-xr-x 1 root root  79337624 Dec 25 15:14 libcudnn.so.5
-rwxr-xr-x 1 root root  79337624 Dec 25 15:14 libcudnn.so.5.1.5
-rw-r--r-- 1 root root  69756172 Dec 25 15:14 libcudnn_static.a
lrwxrwxrwx 1 root root        15 Feb 28 18:43 libcufft.so -> libcufft.so.8.0
lrwxrwxrwx 1 root root        18 Feb 28 18:43 libcufft.so.8.0 -> libcufft.so.8.0.61
-rwxr-xr-x 1 root root 146765440 Feb 28 18:43 libcufft.so.8.0.61
-rw-r--r-- 1 root root 129661426 Feb 28 18:43 libcufft_static.a
lrwxrwxrwx 1 root root        16 Feb 28 18:43 libcufftw.so -> libcufftw.so.8.0
lrwxrwxrwx 1 root root        19 Feb 28 18:43 libcufftw.so.8.0 -> libcufftw.so.8.0.61
-rwxr-xr-x 1 root root    476840 Feb 28 18:43 libcufftw.so.8.0.61
-rw-r--r-- 1 root root     42294 Feb 28 18:43 libcufftw_static.a
lrwxrwxrwx 1 root root        17 Feb 28 18:43 libcuinj64.so -> libcuinj64.so.8.0
lrwxrwxrwx 1 root root        20 Feb 28 18:43 libcuinj64.so.8.0 -> libcuinj64.so.8.0.61
-rwxr-xr-x 1 root root   6403784 Feb 28 18:43 libcuinj64.so.8.0.61
-rw-r--r-- 1 root root   1649302 Feb 28 18:43 libculibos.a
lrwxrwxrwx 1 root root        16 Feb 28 18:43 libcurand.so -> libcurand.so.8.0
lrwxrwxrwx 1 root root        19 Feb 28 18:43 libcurand.so.8.0 -> libcurand.so.8.0.61
-rwxr-xr-x 1 root root  59163968 Feb 28 18:43 libcurand.so.8.0.61
-rw-r--r-- 1 root root  59359140 Feb 28 18:43 libcurand_static.a
lrwxrwxrwx 1 root root        18 Feb 28 18:43 libcusolver.so -> libcusolver.so.8.0
lrwxrwxrwx 1 root root        21 Feb 28 18:43 libcusolver.so.8.0 -> libcusolver.so.8.0.61
-rwxr-xr-x 1 root root  53866552 Feb 28 18:43 libcusolver.so.8.0.61
-rw-r--r-- 1 root root  22386284 Feb 28 18:43 libcusolver_static.a
lrwxrwxrwx 1 root root        18 Feb 28 18:43 libcusparse.so -> libcusparse.so.8.0
lrwxrwxrwx 1 root root        21 Feb 28 18:43 libcusparse.so.8.0 -> libcusparse.so.8.0.61
-rwxr-xr-x 1 root root  43034120 Feb 28 18:43 libcusparse.so.8.0.61
-rw-r--r-- 1 root root  51650816 Feb 28 18:43 libcusparse_static.a
lrwxrwxrwx 1 root root        14 Feb 28 18:43 libnppc.so -> libnppc.so.8.0
lrwxrwxrwx 1 root root        17 Feb 28 18:43 libnppc.so.8.0 -> libnppc.so.8.0.61
-rwxr-xr-x 1 root root    456512 Feb 28 18:43 libnppc.so.8.0.61
-rw-r--r-- 1 root root     24512 Feb 28 18:43 libnppc_static.a
lrwxrwxrwx 1 root root        16 Feb 28 18:43 libnppial.so -> libnppial.so.8.0
lrwxrwxrwx 1 root root        19 Feb 28 18:43 libnppial.so.8.0 -> libnppial.so.8.0.61
-rwxr-xr-x 1 root root  10116032 Feb 28 18:43 libnppial.so.8.0.61
lrwxrwxrwx 1 root root        16 Feb 28 18:43 libnppicc.so -> libnppicc.so.8.0
lrwxrwxrwx 1 root root        19 Feb 28 18:43 libnppicc.so.8.0 -> libnppicc.so.8.0.61
-rwxr-xr-x 1 root root   3790368 Feb 28 18:43 libnppicc.so.8.0.61
lrwxrwxrwx 1 root root        17 Feb 28 18:43 libnppicom.so -> libnppicom.so.8.0
lrwxrwxrwx 1 root root        20 Feb 28 18:43 libnppicom.so.8.0 -> libnppicom.so.8.0.61
-rwxr-xr-x 1 root root   1030800 Feb 28 18:43 libnppicom.so.8.0.61
lrwxrwxrwx 1 root root        17 Feb 28 18:43 libnppidei.so -> libnppidei.so.8.0
lrwxrwxrwx 1 root root        20 Feb 28 18:43 libnppidei.so.8.0 -> libnppidei.so.8.0.61
-rwxr-xr-x 1 root root   7098600 Feb 28 18:43 libnppidei.so.8.0.61
lrwxrwxrwx 1 root root        15 Feb 28 18:43 libnppif.so -> libnppif.so.8.0
lrwxrwxrwx 1 root root        18 Feb 28 18:43 libnppif.so.8.0 -> libnppif.so.8.0.61
-rwxr-xr-x 1 root root  47868176 Feb 28 18:43 libnppif.so.8.0.61
lrwxrwxrwx 1 root root        15 Feb 28 18:43 libnppig.so -> libnppig.so.8.0
lrwxrwxrwx 1 root root        18 Feb 28 18:43 libnppig.so.8.0 -> libnppig.so.8.0.61
-rwxr-xr-x 1 root root  21052640 Feb 28 18:43 libnppig.so.8.0.61
lrwxrwxrwx 1 root root        15 Feb 28 18:43 libnppim.so -> libnppim.so.8.0
lrwxrwxrwx 1 root root        18 Feb 28 18:43 libnppim.so.8.0 -> libnppim.so.8.0.61
-rwxr-xr-x 1 root root   4333920 Feb 28 18:43 libnppim.so.8.0.61
lrwxrwxrwx 1 root root        14 Feb 28 18:43 libnppi.so -> libnppi.so.8.0
lrwxrwxrwx 1 root root        17 Feb 28 18:43 libnppi.so.8.0 -> libnppi.so.8.0.61
-rwxr-xr-x 1 root root 108924816 Feb 28 18:43 libnppi.so.8.0.61
-rw-r--r-- 1 root root 136645168 Feb 28 18:43 libnppi_static.a
lrwxrwxrwx 1 root root        16 Feb 28 18:43 libnppist.so -> libnppist.so.8.0
lrwxrwxrwx 1 root root        19 Feb 28 18:43 libnppist.so.8.0 -> libnppist.so.8.0.61
-rwxr-xr-x 1 root root  14270440 Feb 28 18:43 libnppist.so.8.0.61
lrwxrwxrwx 1 root root        16 Feb 28 18:43 libnppisu.so -> libnppisu.so.8.0
lrwxrwxrwx 1 root root        19 Feb 28 18:43 libnppisu.so.8.0 -> libnppisu.so.8.0.61
-rwxr-xr-x 1 root root    448016 Feb 28 18:43 libnppisu.so.8.0.61
lrwxrwxrwx 1 root root        16 Feb 28 18:43 libnppitc.so -> libnppitc.so.8.0
lrwxrwxrwx 1 root root        19 Feb 28 18:43 libnppitc.so.8.0 -> libnppitc.so.8.0.61
-rwxr-xr-x 1 root root   2897184 Feb 28 18:43 libnppitc.so.8.0.61
lrwxrwxrwx 1 root root        14 Feb 28 18:43 libnpps.so -> libnpps.so.8.0
lrwxrwxrwx 1 root root        17 Feb 28 18:43 libnpps.so.8.0 -> libnpps.so.8.0.61
-rwxr-xr-x 1 root root   8178184 Feb 28 18:43 libnpps.so.8.0.61
-rw-r--r-- 1 root root  10741440 Feb 28 18:43 libnpps_static.a
lrwxrwxrwx 1 root root        16 Feb 28 18:43 libnvblas.so -> libnvblas.so.8.0
lrwxrwxrwx 1 root root        19 Feb 28 18:43 libnvblas.so.8.0 -> libnvblas.so.8.0.61
-rwxr-xr-x 1 root root    498088 Feb 28 18:43 libnvblas.so.8.0.61
lrwxrwxrwx 1 root root        17 Feb 28 18:43 libnvgraph.so -> libnvgraph.so.8.0
lrwxrwxrwx 1 root root        20 Feb 28 18:43 libnvgraph.so.8.0 -> libnvgraph.so.8.0.61
-rwxr-xr-x 1 root root   5213656 Feb 28 18:43 libnvgraph.so.8.0.61
-rw-r--r-- 1 root root   8169056 Feb 28 18:43 libnvgraph_static.a
lrwxrwxrwx 1 root root        24 Feb 28 18:43 libnvrtc-builtins.so -> libnvrtc-builtins.so.8.0
lrwxrwxrwx 1 root root        27 Feb 28 18:43 libnvrtc-builtins.so.8.0 -> libnvrtc-builtins.so.8.0.61
-rwxr-xr-x 1 root root   9656680 Feb 28 18:43 libnvrtc-builtins.so.8.0.61
lrwxrwxrwx 1 root root        15 Feb 28 18:43 libnvrtc.so -> libnvrtc.so.8.0
lrwxrwxrwx 1 root root        18 Feb 28 18:43 libnvrtc.so.8.0 -> libnvrtc.so.8.0.61
-rwxr-xr-x 1 root root  18512120 Feb 28 18:43 libnvrtc.so.8.0.61
lrwxrwxrwx 1 root root        18 Feb 28 18:43 libnvToolsExt.so -> libnvToolsExt.so.1
lrwxrwxrwx 1 root root        22 Feb 28 18:43 libnvToolsExt.so.1 -> libnvToolsExt.so.1.0.0
-rwxr-xr-x 1 root root     37136 Feb 28 18:43 libnvToolsExt.so.1.0.0
lrwxrwxrwx 1 root root        14 Feb 28 18:43 libOpenCL.so -> libOpenCL.so.1
lrwxrwxrwx 1 root root        16 Feb 28 18:43 libOpenCL.so.1 -> libOpenCL.so.1.0
lrwxrwxrwx 1 root root        18 Feb 28 18:43 libOpenCL.so.1.0 -> libOpenCL.so.1.0.0
-rw-r--r-- 1 root root     25840 Feb 28 18:43 libOpenCL.so.1.0.0
drwxr-xr-x 2 root root      4096 Mar  5 16:29 stubs
```

`ls -lah /usr/lib/libcud*`
```
lrwxrwxrwx 1 root root   12 Feb 27 17:36 /usr/lib/libcuda.so -> libcuda.so.1
lrwxrwxrwx 1 root root   17 Feb 27 17:36 /usr/lib/libcuda.so.1 -> libcuda.so.378.13
-rwxr-xr-x 2 root root 8.3M Feb 27 17:36 /usr/lib/libcuda.so.378.13
```

`bazel info`
```
Warning: ignoring _JAVA_OPTIONS in environment.
bazel-bin: /home/maruli/.cache/bazel/_bazel_maruli/07eb648f17e77e5bc907dc6be9df5c3a/execroot/tensorflow/bazel-out/local-py3-opt/bin
bazel-genfiles: /home/maruli/.cache/bazel/_bazel_maruli/07eb648f17e77e5bc907dc6be9df5c3a/execroot/tensorflow/bazel-out/local-py3-opt/genfiles
bazel-testlogs: /home/maruli/.cache/bazel/_bazel_maruli/07eb648f17e77e5bc907dc6be9df5c3a/execroot/tensorflow/bazel-out/local-py3-opt/testlogs
command_log: /home/maruli/.cache/bazel/_bazel_maruli/07eb648f17e77e5bc907dc6be9df5c3a/command.log
committed-heap-size: 838MB
execution_root: /home/maruli/.cache/bazel/_bazel_maruli/07eb648f17e77e5bc907dc6be9df5c3a/execroot/tensorflow
gc-count: 24
gc-time: 1347ms
install_base: /home/maruli/.cache/bazel/_bazel_maruli/install/b9af16fe5222092c9bdd576f898b1e18
max-heap-size: 1825MB
message_log: /home/maruli/.cache/bazel/_bazel_maruli/07eb648f17e77e5bc907dc6be9df5c3a/message.log
output_base: /home/maruli/.cache/bazel/_bazel_maruli/07eb648f17e77e5bc907dc6be9df5c3a
output_path: /home/maruli/.cache/bazel/_bazel_maruli/07eb648f17e77e5bc907dc6be9df5c3a/execroot/tensorflow/bazel-out
package_path: %workspace%
release: release 0.4.4- (@non-git)
server_pid: 12761
used-heap-size: 422MB
workspace: /media/uno/repos/tensorflow
```
Git commit hash
`git rev-parse HEAD`
```
f1ffbc548906e379d423633f76edc558be8284e7
```

I got the following error when i run gen_docs.sh

```
/media/uno/repos/tensorflow/tensorflow /media/uno/repos/tensorflow/tensorflow/tools/docs
Warning: ignoring _JAVA_OPTIONS in environment.
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
WARNING: /media/uno/repos/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:exporter': Use SavedModel Builder instead.
WARNING: /media/uno/repos/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:gc': Use SavedModel instead.
INFO: Found 1 target...
Target //tensorflow/python:gen_docs_combined up-to-date:
  bazel-bin/tensorflow/python/gen_docs_combined
INFO: Elapsed time: 7.777s, Critical Path: 6.52s

INFO: Running command line: bazel-bin/tensorflow/python/gen_docs_combined '--out_dir=/media/uno/repos/tensorflow/tensorflow/g3doc/api_docs/python'
Traceback (most recent call last):
  File "/home/maruli/.cache/bazel/_bazel_maruli/07eb648f17e77e5bc907dc6be9df5c3a/execroot/tensorflow/bazel-out/local-py3-opt/bin/tensorflow/python/gen_docs_combined.runfiles/org_tensorflow/tensorflow/python/framework/gen_docs_combined.py", line 332, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/maruli/.cache/bazel/_bazel_maruli/07eb648f17e77e5bc907dc6be9df5c3a/execroot/tensorflow/bazel-out/local-py3-opt/bin/tensorflow/python/gen_docs_combined.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/maruli/.cache/bazel/_bazel_maruli/07eb648f17e77e5bc907dc6be9df5c3a/execroot/tensorflow/bazel-out/local-py3-opt/bin/tensorflow/python/gen_docs_combined.runfiles/org_tensorflow/tensorflow/python/framework/gen_docs_combined.py", line 286, in main
    module_to_name = get_module_to_name(module_names())
  File "/home/maruli/.cache/bazel/_bazel_maruli/07eb648f17e77e5bc907dc6be9df5c3a/execroot/tensorflow/bazel-out/local-py3-opt/bin/tensorflow/python/gen_docs_combined.runfiles/org_tensorflow/tensorflow/python/framework/gen_docs_combined.py", line 112, in get_module_to_name
    return collections.OrderedDict([(find_module(tf, x), x) for x in names])
  File "/home/maruli/.cache/bazel/_bazel_maruli/07eb648f17e77e5bc907dc6be9df5c3a/execroot/tensorflow/bazel-out/local-py3-opt/bin/tensorflow/python/gen_docs_combined.runfiles/org_tensorflow/tensorflow/python/framework/gen_docs_combined.py", line 112, in <listcomp>
    return collections.OrderedDict([(find_module(tf, x), x) for x in names])
  File "/home/maruli/.cache/bazel/_bazel_maruli/07eb648f17e77e5bc907dc6be9df5c3a/execroot/tensorflow/bazel-out/local-py3-opt/bin/tensorflow/python/gen_docs_combined.runfiles/org_tensorflow/tensorflow/python/framework/gen_docs_combined.py", line 102, in find_module
    name, s, parent_module.__name__, dir(parent_module)))
ValueError: Module not found: tf.contrib.distributions.bijector. Submodule bijector not found in parent module tensorflow.contrib.distributions. Possible candidates are ['Bernoulli', 'BernoulliWithSigmoidProbs', 'Beta', 'BetaWithSoftplusConcentration', 'Binomial', 'Categorical', 'Chi2', 'Chi2WithAbsDf', 'ConditionalDistribution', 'ConditionalTransformedDistribution', 'Dirichlet', 'DirichletMultinomial', 'Distribution', 'ExpRelaxedOneHotCategorical', 'Exponential', 'ExponentialWithSoftplusRate', 'FULLY_REPARAMETERIZED', 'Gamma', 'GammaWithSoftplusConcentrationRate', 'Geometric', 'InverseGamma', 'InverseGammaWithSoftplusConcentrationRate', 'Laplace', 'LaplaceWithSoftplusScale', 'Logistic', 'Mixture', 'Multinomial', 'MultivariateNormalDiag', 'MultivariateNormalDiagPlusLowRank', 'MultivariateNormalDiagWithSoftplusScale', 'MultivariateNormalTriL', 'NOT_REPARAMETERIZED', 'NegativeBinomial', 'Normal', 'NormalWithSoftplusScale', 'OneHotCategorical', 'Poisson', 'QuantizedDistribution', 'RegisterKL', 'RelaxedBernoulli', 'RelaxedOneHotCategorical', 'ReparameterizationType', 'StudentT', 'StudentTWithAbsDfSoftplusScale', 'TransformedDistribution', 'Uniform', 'WishartCholesky', 'WishartFull', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_allowed_symbols', 'kl', 'matrix_diag_transform', 'normal_conjugates_known_scale_posterior', 'normal_conjugates_known_scale_predictive', 'softplus_inverse']
ERROR: Non-zero return code '1' from command: Process exited with status 1.
```

Btw, when i run the configuration script i choose to not build tensorflow with cuda capability.
I don't know if it have any correlation with the error.

**Comment by prb12** [comment]
@langmore The error seems to be related to `tf.contrib.distributions`.  Have you any idea why this might be happening?

**Comment by langmore** [comment]
This is probably related to [this change](https://github.com/tensorflow/tensorflow/commit/988a443383a56619aeaa73354146579addfb13ad)

**Comment by prb12** [comment]
@langmore Thanks.

**Comment by ebrevdo** [comment]
I don't think it's caused by that change. Wonder where the reference to distributions.bijector is from... Perhaps an outdated me file?  Josh?

**Comment by josh11b** [comment]
gen_docs.sh is no longer the way to generate documentation.  See https://github.com/tensorflow/tensorflow/tree/master/tensorflow/g3doc
for the new commands to run.

**Comment by marulitua** [comment]
@josh11b I am on commit 03d31c77703304087d66bd0f608a3de745fadf67 
but when i run 
`
bazel run -- tensorflow/tools/docs:generate \
    --src_dir=tensorflow/docs_src/ \
    --output_dir=/tmp/tfdocs/
`

it produced the following error
```
tensorflow ➤ bazel run -- tensorflow/tools/docs:generate \                                                                              git:master
    --src_dir=tensorflow/docs_src/ \
    --output_dir=/tmp/tfdocs/
Warning: ignoring _JAVA_OPTIONS in environment.
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
WARNING: /media/uno/repos/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:exporter': Use SavedModel Builder instead.
WARNING: /media/uno/repos/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:gc': Use SavedModel instead.
INFO: Found 1 target...
Target //tensorflow/tools/docs:generate up-to-date:
  bazel-bin/tensorflow/tools/docs/generate
INFO: Elapsed time: 0.496s, Critical Path: 0.00s

INFO: Running command line: bazel-bin/tensorflow/tools/docs/generate '--src_dir=tensorflow/docs_src/' '--output_dir=/tmp/tfdocs/'
WARNING:tensorflow:VARIABLES collection name is deprecated, please use GLOBAL_VARIABLES instead; VARIABLES will be removed after 2017-03-02.
Writing docs for tf (<module 'tensorflow' from '/home/maruli/.cache/bazel/_bazel_maruli/07eb648f17e77e5bc907dc6be9df5c3a/execroot/tensorflow/bazel-out/local-py3-opt/bin/tensorflow/tools/docs/generate.runfiles/org_tensorflow/tensorflow/__init__.py'>).
ERROR: Handle doc reference "@{$adding_an_op}"
ERROR: Handle doc reference "@{$variables}"
ERROR: Handle doc reference "@{$variable_scope}"
ERROR: Handle doc reference "@{$variable_scope}"
ERROR: Handle doc reference "@{$python/image}"
ERROR: Handle doc reference "@{$python/nn}"
ERROR: Handle doc reference "@{$python/python_io}"
ERROR: Handle doc reference "@{$python/summary}"
ERROR: Handle doc reference "@{$python/test}"
ERROR: Handle doc reference "@{$python/train}"
ERROR: Handle doc reference "@{$variable_scope}"
Writing docs for tf.AggregationMethod (<class 'tensorflow.python.ops.gradients_impl.AggregationMethod'>).
Writing docs for tf.Assert (<function Assert at 0x7f76c12a99d8>).
Writing docs for tf.AttrValue (<class 'tensorflow.core.framework.attr_value_pb2.AttrValue'>).
Writing docs for tf.ConditionalAccumulator (<class 'tensorflow.python.ops.data_flow_ops.ConditionalAccumulator'>).
Traceback (most recent call last):
  File "/home/maruli/.cache/bazel/_bazel_maruli/07eb648f17e77e5bc907dc6be9df5c3a/execroot/tensorflow/bazel-out/local-py3-opt/bin/tensorflow/tools/docs/generate.runfiles/org_tensorflow/tensorflow/tools/docs/generate.py", line 51, in <module>
    sys.exit(doc_generator.build(flags))
  File "/home/maruli/.cache/bazel/_bazel_maruli/07eb648f17e77e5bc907dc6be9df5c3a/execroot/tensorflow/bazel-out/local-py3-opt/bin/tensorflow/tools/docs/generate.runfiles/org_tensorflow/tensorflow/tools/docs/generate_lib.py", line 494, in build
    yaml_toc=self.yaml_toc)
  File "/home/maruli/.cache/bazel/_bazel_maruli/07eb648f17e77e5bc907dc6be9df5c3a/execroot/tensorflow/bazel-out/local-py3-opt/bin/tensorflow/tools/docs/generate.runfiles/org_tensorflow/tensorflow/tools/docs/generate_lib.py", line 131, in write_docs
    f.write(pretty_docs.build_md_page(page_info))
  File "/home/maruli/.cache/bazel/_bazel_maruli/07eb648f17e77e5bc907dc6be9df5c3a/execroot/tensorflow/bazel-out/local-py3-opt/bin/tensorflow/tools/docs/generate.runfiles/org_tensorflow/tensorflow/tools/docs/pretty_docs.py", line 41, in build_md_page
    return _build_class_page(page_info)
  File "/home/maruli/.cache/bazel/_bazel_maruli/07eb648f17e77e5bc907dc6be9df5c3a/execroot/tensorflow/bazel-out/local-py3-opt/bin/tensorflow/tools/docs/generate.runfiles/org_tensorflow/tensorflow/tools/docs/pretty_docs.py", line 128, in _build_class_page
    parts.append(h3.format(**method_info.__dict__))
AttributeError: '_MethodInfo' object has no attribute '__dict__'
ERROR: Non-zero return code '1' from command: Process exited with status 1.
```
I think we still have the problem.

**Comment by ebrevdo** [comment]
I think Martin is looking at this.

**Comment by martinwicke** [comment]
Are you running this on python3? I doubt the doc generator works on python3 at the moment.

**Comment by marulitua** [comment]
Yes, indeed. I am using python3. I am sorry but  i cannot try it on python2.
So, i think we can close this issue.
Thanks all.
