### ISSUE TITLE
[Windows Build] "RECURSIVE_PKG:rootedPath" Path Casing Error

### ISSUE THREAD

**Issue by Carmezim** [tensorflow/tensorflow#8314]
Windows 10
Bazel 0.4.5
Visual C++ 2015
Msys2 v20160205
Python 3.5 (python.org distribution)

Configuring TensorFlow on Windows generates an error related to path case sensitivity:

```
Adriano@Adriano MSYS /c/Users/Adriano/Documents/tensorflow
$ ./configure
Please specify the location of python. [Default is /c/Users/Adriano/AppData/Local/Programs/Python/Python35/python]:
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]:
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N] y
XLA JIT support will be enabled for TensorFlow
Found possible Python library paths:
  C:\Users\Adriano\AppData\Local\Programs\Python\Python35
  C:\Users\Adriano\AppData\Local\Programs\Python\Python35\lib\site-packages
Please input the desired Python library path to use.  Default is [C:\Users\Adriano\AppData\Local\Programs\Python\Python35]

Using python library path: C:\Users\Adriano\AppData\Local\Programs\Python\Python35
Junction created for util\python\python_include <<===>> C:\Users\Adriano\AppData\Local\Programs\Python\Python35\include
Junction created for util\python\python_lib <<===>> C:\Users\Adriano\AppData\Local\Programs\Python\Python35
Junction created for third_party\py\numpy\numpy_include <<===>> C:\Users\Adriano\AppData\Local\Programs\Python\Python35\lib\site-packages\numpy\core\include
Do you wish to build TensorFlow with CUDA support? [y/N] y
CUDA support will be enabled for TensorFlow
Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 8.0
Please specify the location where CUDA 8.0 toolkit is installed. Refer to README.md for more details. [Default is C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0]:
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 5.1
Please specify the location where cuDNN 5.1 library is installed. Refer to README.md for more details. [Default is C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0]:
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 5.0
..................................................
java.lang.RuntimeException: Unrecoverable error while evaluating node 'FILE:[C:/users/adriano/documents/tensorflow]/[tensorflow/tools/git/gen/head]' (requested by nodes 'RECURSIVE_PKG:rootedPath=[C:/users/adriano/documents/tensorflow]/[tensorflow/tools/git/gen/head], excludedPaths=<omitted>)')
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:448)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:501)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: relativePath 'C:/Users/Adriano/Documents/tensorflow/.git/HEAD' is absolute, but it's not under root 'C:/users/adriano/documents/tensorflow'
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:383)
        at com.google.devtools.build.lib.util.Preconditions.checkArgument(Preconditions.java:90)
        at com.google.devtools.build.lib.vfs.RootedPath.toRootedPath(RootedPath.java:56)
        at com.google.devtools.build.lib.vfs.RootedPath.toRootedPath(RootedPath.java:73)
        at com.google.devtools.build.lib.vfs.RootedPath.toRootedPathMaybeUnderRoot(RootedPath.java:83)
        at com.google.devtools.build.lib.skyframe.FileFunction.getSymlinkTargetRootedPath(FileFunction.java:176)
        at com.google.devtools.build.lib.skyframe.FileFunction.compute(FileFunction.java:101)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:374)
        ... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'FILE:[C:/users/adriano/documents/tensorflow]/[tensorflow/tools/git/gen/head]' (requested by nodes 'RECURSIVE_PKG:rootedPath=[C:/users/adriano/documents/tensorflow]/[tensorflow/tools/git/gen/head], excludedPaths=<omitted>)')
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:448)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:501)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: relativePath 'C:/Users/Adriano/Documents/tensorflow/.git/HEAD' is absolute, but it's not under root 'C:/users/adriano/documents/tensorflow'
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:383)
        at com.google.devtools.build.lib.util.Preconditions.checkArgument(Preconditions.java:90)
        at com.google.devtools.build.lib.vfs.RootedPath.toRootedPath(RootedPath.java:56)
        at com.google.devtools.build.lib.vfs.RootedPath.toRootedPath(RootedPath.java:73)
        at com.google.devtools.build.lib.vfs.RootedPath.toRootedPathMaybeUnderRoot(RootedPath.java:83)
        at com.google.devtools.build.lib.skyframe.FileFunction.getSymlinkTargetRootedPath(FileFunction.java:176)
        at com.google.devtools.build.lib.skyframe.FileFunction.compute(FileFunction.java:101)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:374)
        ... 4 more
```

Steps to reproduce:
- Clone TensorFlow repo
- `./configure`

**Comment by prb12** [comment]
@mrry Have you encountered anything like this before?

**Comment by prb12** [comment]
@Carmezim Could you also please provide the commit version of your repo.

**Comment by mrry** [comment]
Nope, sounds like Bazel's sandboxing is unhappy. As a short-term workaround, the CMake build in `tensorflow/contrib/cmake` should work fine.

@meteorcloudy: have you seen this error before?

**Comment by Carmezim** [comment]
@prb12 Sure a91be11e5d228848e9648f1e63e6d509754befb9

**Comment by Carmezim** [comment]
I think this issue is fixed on bazel current rc. I received this error on rc3 if not mistaken and on current it does not occur so I am closing this issue.

**Comment by Carmezim** [comment]
@mrry I am having no luck with bazel (#8482) then I decided to build with CMake but the `COMPILER_OPT_ARCH_NATIVE_SUPPORTED` test fails even with the instructions available (`gcc march=native` shows them enabled, mavx, mfma, msse etc).
Would you have any tip on this?
Thanks!
