### ISSUE TITLE
when i use tensorflow v1.01  python3 there are SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by andongchen** [tensorflow/tensorflow#8341]
when i use tensorflow-gpu v1.01  python3.5 there are SyntaxError: invalid syntax
but i only install tensorflow-gpu v1.01 python2.7 there are no  SyntaxError: invalid syntax
like i use tensorboard when i have installed tensorflow-gpu v1.01 python3.5

 #cy@cy:~/PycharmProjects/models-master/slim$ tensorboard --logdir=./
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "/usr/local/bin/tensorboard", line 7, in <module>
    from tensorflow.tensorboard.tensorboard import main
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/tensorboard/tensorboard.py", line 34, in <module>
    from tensorflow.tensorboard.backend import server
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/tensorboard/backend/server.py", line 38, in <module>
    from tensorflow.tensorboard.plugins.projector import plugin as projector_plugin
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/tensorboard/plugins/projector/plugin.py", line 27, in <module>
    from tensorflow.contrib.tensorboard.plugins.projector import PROJECTOR_FILENAME
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/__init__.py", line 29, in <module>
    from tensorflow.contrib import factorization
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/factorization/__init__.py", line 24, in <module>
    from tensorflow.contrib.factorization.python.ops.gmm import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/factorization/python/ops/gmm.py", line 32, in <module>
    from tensorflow.contrib.learn.python.learn import graph_actions
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/__init__.py", line 70, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/__init__.py", line 23, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 25, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/estimators/__init__.py", line 310, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py", line 29, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import dnn_linear_combined
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 33, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 51, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/learn_io/__init__.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/learn_io/dask_io.py", line 26, in <module>
    import dask.dataframe as dd
  File "/home/cy/.local/lib/python3.5/site-packages/dask/dataframe/__init__.py", line 3, in <module>
    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
  File "/home/cy/.local/lib/python3.5/site-packages/dask/dataframe/core.py", line 11, in <module>
    import pandas as pd
  File "/home/cy/.local/lib/python3.5/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat.numpy import *
  File "/home/cy/.local/lib/python3.5/site-packages/pandas/compat/__init__.py", line 357, in <module>
    from dateutil import parser as _date_parser
  File "/home/cy/.local/lib/python3.5/site-packages/dateutil/parser.py", line 158
    l.append("%s=%s" % (attr, `value`))
                              ^
SyntaxError: invalid syntax

#cy@cy:~/PycharmProjects/models-master/slim$ python3 train_image_classifier.py 
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "train_image_classifier.py", line 24, in <module>
    from datasets import dataset_factory
  File "/home/cy/PycharmProjects/models-master/slim/datasets/dataset_factory.py", line 21, in <module>
    from datasets import cifar10
  File "/home/cy/PycharmProjects/models-master/slim/datasets/cifar10.py", line 30, in <module>
    slim = tf.contrib.slim
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py", line 35, in __getattr__
    contrib = importlib.import_module('tensorflow.contrib')
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/__init__.py", line 29, in <module>
    from tensorflow.contrib import factorization
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/factorization/__init__.py", line 24, in <module>
    from tensorflow.contrib.factorization.python.ops.gmm import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/factorization/python/ops/gmm.py", line 32, in <module>
    from tensorflow.contrib.learn.python.learn import graph_actions
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/__init__.py", line 70, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/__init__.py", line 23, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 25, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/estimators/__init__.py", line 310, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py", line 29, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import dnn_linear_combined
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 33, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 51, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/learn_io/__init__.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/learn_io/dask_io.py", line 26, in <module>
    import dask.dataframe as dd
  File "/home/cy/.local/lib/python3.5/site-packages/dask/dataframe/__init__.py", line 3, in <module>
    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
  File "/home/cy/.local/lib/python3.5/site-packages/dask/dataframe/core.py", line 11, in <module>
    import pandas as pd
  File "/home/cy/.local/lib/python3.5/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat.numpy import *
  File "/home/cy/.local/lib/python3.5/site-packages/pandas/compat/__init__.py", line 357, in <module>
    from dateutil import parser as _date_parser
  File "/home/cy/.local/lib/python3.5/site-packages/dateutil/parser.py", line 158
    l.append("%s=%s" % (attr, `value`))
                              ^
SyntaxError: invalid syntax

**Comment by MicaelCarvalho** [comment]
It seems to be a bad installation, try reinstalling TF.

And please follow guidelines for filling an issue: You did not provide most of the required information for a proper analysis of the problem (when you start a new issue, by default the template tells you what to do, you only have to fill in the fields, instead of erasing it all and writing over it). Also, enclose your outputs with the code tag, so they can be more easily read. ;-)

**Comment by gunan** [comment]
Moreover, the file syntax error is emitted from is here:
```
File "/home/cy/.local/lib/python3.5/site-packages/dateutil/parser.py", line 158
l.append("%s=%s" % (attr, value))
^
SyntaxError: invalid syntax
```
That is not really a TensorFlow file. I think some other package in your python installation may be corrupted. A google search seems to support this theory:
https://www.google.com/search?q="dateutil%2Fparser.py"%2C+line+158"+invalid+syntax&oq="dateutil%2Fparser.py"%2C+line+158"+invalid+syntax

Which people point to a bug in dateutil package.
Please make sure to search for relevant bugs before filing issues.
