### ISSUE TITLE
Quantize Neural Networks with TensorFlow doesn't work on my models

### ISSUE THREAD

**Issue by riless** [tensorflow/tensorflow#8347]
I'm following this [tutorial here](https://www.tensorflow.org/performance/quantization).

And this code works fine.
```
curl http://download.tensorflow.org/models/image/imagenet/inception-2015-12-05.tgz -o /tmp/inceptionv3.tgz
tar xzf /tmp/inceptionv3.tgz -C /tmp/
bazel build tensorflow/tools/quantization/tools:quantize_graph
bazel-bin/tensorflow/tools/quantization/tools/quantize_graph \
  --input=/tmp/classify_image_graph_def.pb \
  --output_node_names="softmax" --output=/tmp/quantized_graph.pb \
  --mode=eightbit
```

But when I try with another .pb it does not work, it tells me that the output node does not exist.

**With non frozen .pb**
```
Traceback (most recent call last):
  File "/sandbox/tensorflow/bazel-bin/tensorflow/tools/quantization/quantize_graph.runfiles/org_tensorflow/tensorflow/tools/quantization/quantize_graph.py", line 1304, in <module>
    app.run()
  File "/sandbox/tensorflow/bazel-bin/tensorflow/tools/quantization/quantize_graph.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/sandbox/tensorflow/bazel-bin/tensorflow/tools/quantization/quantize_graph.runfiles/org_tensorflow/tensorflow/tools/quantization/quantize_graph.py", line 1271, in main
    tf_graph.ParseFromString(data)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/message.py", line 185, in ParseFromString
    self.MergeFromString(serialized)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py", line 1091, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py", line 1117, in InternalParse
    new_pos = local_SkipField(buffer, new_pos, end, tag_bytes)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/decoder.py", line 850, in SkipField
    return WIRETYPE_TO_SKIPPER[wire_type](buffer, pos, end)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/decoder.py", line 820, in _RaiseInvalidWireType
    raise _DecodeError('Tag had invalid wire type.')
google.protobuf.message.DecodeError: Tag had invalid wire type.

```

**With frozen .pb**

```
Traceback (most recent call last):
  File "/sandbox/tensorflow/bazel-bin/tensorflow/tools/quantization/quantize_graph.runfiles/org_tensorflow/tensorflow/tools/quantization/quantize_graph.py", line 1304, in <module>
    app.run()
  File "/sandbox/tensorflow/bazel-bin/tensorflow/tools/quantization/quantize_graph.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/sandbox/tensorflow/bazel-bin/tensorflow/tools/quantization/quantize_graph.runfiles/org_tensorflow/tensorflow/tools/quantization/quantize_graph.py", line 1295, in main
    output_graph = rewriter.rewrite(FLAGS.output_node_names.split(","))
  File "/sandbox/tensorflow/bazel-bin/tensorflow/tools/quantization/quantize_graph.runfiles/org_tensorflow/tensorflow/tools/quantization/quantize_graph.py", line 400, in rewrite
    for output_node_name in output_node_names
KeyError: 'my_output_node'
```

I'm sure the output_node_names is correct.

Is there any requirements on the .pb file so the tool can quantize it ?

nb: one should edit the doc because the tool is no longer in `tensorflow/tools/quantization/tools:quantize_graph` but `tensorflow/tools/quantization:quantize_graph`

**Comment by concretevitamin** [comment]
@petewarden could you take a look?

**Comment by abidrahmank** [comment]
Me too had the same issue, because I gave wrong name in "output_node_names". And I worked fine for my own network stored as frozen .pb file. Are you sure you passed all the four params correctly, especially the output_node_names?

**Comment by abagshaw** [comment]
Same problem here, I get `KeyError: 'output'` (`output`) is the name of my output node.

**Comment by mddrill** [comment]
I'm getting this issue also, I've confirmed that I'm using the right output names by using the summarize graph tool mentioned here https://github.com/thtrieu/darkflow/issues/143#issuecomment-292825749

**Comment by mddrill** [comment]
I figured out the source of the error. I was using `tf.identity` ops to name my output tensors. The call to `graph_util.remove_training_nodes` on line 413 in `quantize_graph.py` removes all identity ops from the graph causing a KeyError. Apparently,

> "There are nodes like Identity and CheckNumerics that are only useful
>   during training, and can be removed in graphs that will be used for
>   nothing but inference. Here we identify and remove them, returning an
>   equivalent graph. To be specific, CheckNumerics nodes are always removed, and
>   Identity nodes that aren't involved in control edges are spliced out so that
>   their input and outputs are directly connected."

from the comment on tensorflow/python/framework/graph_util_impl.py

I don't know what the best workaround would be, for now I'm just going to change line 417 from `self.set_input_graph(graph_util.remove_training_nodes(self.input_graph))` to `self.set_input_graph(self.input_graph)`

As far as I know there are no CheckNumeric ops in my network and the only identity calls are the output nodes, so hopefully this won't affect much.

**Comment by girving** [comment]
Glad you found a workaround!
