### ISSUE TITLE
mnist_softmax.py has "TimeoutError: [WinError 10060]" ...

### ISSUE THREAD

**Issue by NatLun091238** [tensorflow/tensorflow#8399]
The code https://www.tensorflow.org/code/tensorflow/examples/tutorials/mnist/mnist_softmax.py
does not run on TensorFlow (Windows installation)

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

Quite similar problem reported here: http://stackoverflow.com/questions/40467893/running-mnist-softmax-py-on-tensorflow-installed-with-docker However, no solution there...

### Environment info
Operating System: Windows 10 pro (Intel(R) Core(TM) i7 6500U CPU) 
TensorFlow installed: pip install -U tensorflow; Python 3.5.2 :: Anaconda custom (64-bit)
------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "C:\Users\natlun\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Users\natlun\AppData\Local\Continuum\Anaconda3\lib\http\client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "C:\Users\natlun\AppData\Local\Continuum\Anaconda3\lib\http\client.py", line 1151, in _send_request
    self.endheaders(body)
  File "C:\Users\natlun\AppData\Local\Continuum\Anaconda3\lib\http\client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "C:\Users\natlun\AppData\Local\Continuum\Anaconda3\lib\http\client.py", line 934, in _send_output
    self.send(msg)
  File "C:\Users\natlun\AppData\Local\Continuum\Anaconda3\lib\http\client.py", line 877, in send
    self.connect()
  File "C:\Users\natlun\AppData\Local\Continuum\Anaconda3\lib\http\client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Users\natlun\AppData\Local\Continuum\Anaconda3\lib\socket.py", line 711, in create_connection
    raise err
  File "C:\Users\natlun\AppData\Local\Continuum\Anaconda3\lib\socket.py", line 702, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\natlun\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 714, in runfile
    execfile(filename, namespace)
  File "C:\Users\natlun\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 89, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "C:/Users/natlun/Documents/Python Scripts/mnist_softmax03.py", line 92, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "C:\Users\natlun\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "C:/Users/natlun/Documents/Python Scripts/mnist_softmax03.py", line 20, in main
    mnist = input_data.read_data_sets(FLAGS.data_dir, one_hot=True)
  File "C:\Users\natlun\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\mnist.py", line 211, in read_data_sets
    SOURCE_URL + TRAIN_IMAGES)
  File "C:\Users\natlun\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\base.py", line 208, in maybe_download
    temp_file_name, _ = urlretrieve_with_retry(source_url)
  File "C:\Users\natlun\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\base.py", line 165, in wrapped_fn
    return fn(*args, **kwargs)
  File "C:\Users\natlun\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\base.py", line 190, in urlretrieve_with_retry
    return urllib.request.urlretrieve(url, filename)
  File "C:\Users\natlun\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 188, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\natlun\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\natlun\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 466, in open
    response = self._open(req, data)
  File "C:\Users\natlun\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 484, in _open
    '_open', req)
  File "C:\Users\natlun\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Users\natlun\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Users\natlun\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060]>

**Comment by MicaelCarvalho** [comment]
This issue is already solved with PR #8171.

Related to issues #8159, #8134, #8126, #8116, #8113 and #8009.

Next TF release will bring the fix.

**Comment by LeonMac** [comment]
hello, I just meet the same issue and looking forward the solution.
It looks like a server relevant issue that too many worldwide download/pull data request at the same time, crashed the mnist data server, which is on Yann LeCun's website (a personal website)?

**Comment by asross** [comment]
> This issue is already solved with PR #8171.

They actually rejected the PR because:

> We do not have the permission from Yann Lecun to mirror these files.
> Therefore, we cannot accept this PR. We are looking into modifying our tutorials to not depend on > mnist dataset.

So I think this will continue to be an issue with no resolution except manually downloading the MNIST files and placing them in the right directory. You should be able to download them from https://web.archive.org/web/20160828233817/http://yann.lecun.com/exdb/mnist/.

**Comment by aselle** [comment]
Yes, it is really unfortunate that this happens. We're looking for a solution...

**Comment by yxiaohui** [comment]
I can download it from [http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz](http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz) with browser. But when running code, WinError 10060 occurred.

**Comment by martinwicke** [comment]
This error indicates that a timeout occurred while trying to download the files. It's not something we can fix unfortunately. The intermittent availability of MNIST is covered in other issues, so I will close this one as a duplicate.

**Comment by slideWXY** [comment]
You could fix that by using tensorflow command 

from tensorflow.examples.tutorials.mnist import input_data

after that :+1: 
mnist = input_data.read_data_sets("path/to/your/data/", one_hot=True)
