### ISSUE TITLE
Tensorflow_gpu crash on windows server 2012(Nightly build Feb 15, 2017 1:25:00 AM)

### ISSUE THREAD

**Issue by alarmz** [tensorflow/tensorflow#8422]
### Environment info
Operating System:
Windows Server 2012 R2
GPU GeForce GTX 750 and 1080 in two windows server workstation.

Installed version of CUDA and cuDNN: 
CUDA 8.0 installed
CuDNN download, and set path to system environment variable %PATH%

If installed from binary pip package, provide:
I install the fallow whl: "tensorflow_gpu-1.0.0rc2-cp35-cp35m-win_amd64.whl"
http://ci.tensorflow.org/view/Nightly/job/nightly-win/85/DEVICE=gpu,OS=windows/artifact/cmake_build/tf_python/dist/tensorflow_gpu-1.0.0rc2-cp35-cp35m-win_amd64.whl

I only import tensorflow, and it's crash.
-------------------------------------------------
```
(venv64) C:\work\keras01>python
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\work\keras01\venv64\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, i
n swig_import_helper
    return importlib.import_module(mname)
  File "C:\work\keras01\venv64\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 906, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\work\keras01\venv64\lib\site-packages\tensorflow\python\__init__.py", line 66, in <module
>
    from tensorflow.python import pywrap_tensorflow
  File "C:\work\keras01\venv64\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 21, i
n <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\work\keras01\venv64\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, i
n swig_import_helper
    return importlib.import_module('_pywrap_tensorflow')
  File "C:\work\keras01\venv64\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\work\keras01\venv64\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\work\keras01\venv64\lib\site-packages\tensorflow\python\__init__.py", line 72, in <module
>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\work\keras01\venv64\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, i
n swig_import_helper
    return importlib.import_module(mname)
  File "C:\work\keras01\venv64\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 906, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\work\keras01\venv64\lib\site-packages\tensorflow\python\__init__.py", line 66, in <module
>
    from tensorflow.python import pywrap_tensorflow
  File "C:\work\keras01\venv64\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 21, i
n <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\work\keras01\venv64\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, i
n swig_import_helper
    return importlib.import_module('_pywrap_tensorflow')
  File "C:\work\keras01\venv64\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow'


Failed to load the native TensorFlow runtime.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#im
port_error

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by jubjamie** [comment]
Have you followed the advice given regarding the _pywrap_tensorflow problem. Check out: [https://stackoverflow.com/q/42011070](https://stackoverflow.com/q/42011070)

It looks like you are missing a DLL. However, I had this problem not long ago even though I did have the DLL. Just ensure that your environment variables are set correctly. If playing around with that doesn't work i'll try and remember the other troubleshooting steps I did to fix it. (As it was a bit tricky to solve!)

**Comment by alarmz** [comment]
Thanks your reply, my computer has already install visual studio 2015 and also install 2015 Redistributable
in previous version of tensorflow_gpu 0.12.x don't have this issue.

**Comment by jubjamie** [comment]
Can you try installing via pip install tensorflow-gpu

I seem to recall that the nightly build I used threw this error even though the DLL was there and set up correctly. Installing straight from pip solved this issue. Uninstall the current version first.

**Comment by gunan** [comment]
Sometimes pip may misbehave on windows.
Could you try this command out with an administrator terminal:
```
pip install --ignore-installed --upgrade tensorflow-gpu
```

**Comment by asimshankar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by sheshappanavar** [comment]
Though I am able to import tensorflow, I am not able to create a session and test it.
It gives below error.


(tensorflow-gpu) C:\Users\ssheshap>python
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  5 2016, 11:41:13) [MSC v
.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.Session()
2017-11-16 19:52:51.979025: W c:\l\work\tensorflow-1.1.0\tensorflow\core\platfor
m\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE ins
tructions, but these are available on your machine and could speed up CPU comput
ations.
2017-11-16 19:52:51.979894: W c:\l\work\tensorflow-1.1.0\tensorflow\core\platfor
m\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE2 in
structions, but these are available on your machine and could speed up CPU compu
tations.
2017-11-16 19:52:51.980766: W c:\l\work\tensorflow-1.1.0\tensorflow\core\platfor
m\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 in
structions, but these are available on your machine and could speed up CPU compu
tations.
2017-11-16 19:52:51.981665: W c:\l\work\tensorflow-1.1.0\tensorflow\core\platfor
m\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1
instructions, but these are available on your machine and could speed up CPU com
putations.
2017-11-16 19:52:51.982829: W c:\l\work\tensorflow-1.1.0\tensorflow\core\platfor
m\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2
instructions, but these are available on your machine and could speed up CPU com
putations.
2017-11-16 19:52:51.984912: W c:\l\work\tensorflow-1.1.0\tensorflow\core\platfor
m\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX ins
tructions, but these are available on your machine and could speed up CPU comput
ations.
2017-11-16 19:52:52.026790: E c:\l\work\tensorflow-1.1.0\tensorflow\stream_execu
tor\cuda\cuda_driver.cc:405] failed call to cuInit: CUDA_ERROR_UNKNOWN
2017-11-16 19:52:52.031638: I c:\l\work\tensorflow-1.1.0\tensorflow\stream_execu
tor\cuda\cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for hos
t: WIN-0LVFD08FG54
2017-11-16 19:52:52.033113: I c:\l\work\tensorflow-1.1.0\tensorflow\stream_execu
tor\cuda\cuda_diagnostics.cc:165] hostname: WIN-0LVFD08FG54
<tensorflow.python.client.session.Session object at 0x0000000C22A2B358>
>>> exit()

Please help.
Thanks
