### ISSUE TITLE
im2txt checkpoint issue

### ISSUE THREAD

**Issue by mustafaxfe** [tensorflow/tensorflow#8447]
I have compiled tensorflow from source. I have followed steps at https://github.com/tensorflow/models/tree/master/im2txt. But when I run bazel-bin/im2txt/run_inference, it gives an error:

`bazel-bin/im2txt/run_inference   --checkpoint_path=${CHECKPOINT_DIR}   --vocab_file=${VOCAB_FILE}   --input_files=${IMAGE_FILE} --checkpoint_path="/home/raspberry/models/im2txt/im2txt_pretrained/model.ckpt-2000000"`

And error:

 Traceback (most recent call last):
  File "/home/raspberry/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/run_inference.py", line 83, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/raspberry/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/run_inference.py", line 63, in main
    restore_fn(sess)
  File "/home/raspberry/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/inference_utils/inference_wrapper_base.py", line 96, in _restore_fn
    saver.restore(sess, checkpoint_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1428, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Tensor name "lstm/basic_lstm_cell/biases" not found in checkpoint files /home/raspberry/models/im2txt/im2txt_pretrained/model.ckpt-2000000
	 [[Node: save/RestoreV2_380 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_380/tensor_names, save/RestoreV2_380/shape_and_slices)]]

Caused by op u'save/RestoreV2_380', defined at:
  File "/home/raspberry/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/run_inference.py", line 83, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/raspberry/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/run_inference.py", line 49, in main
    FLAGS.checkpoint_path)
  File "/home/raspberry/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/inference_utils/inference_wrapper_base.py", line 116, in build_graph_from_config
    saver = tf.train.Saver()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1040, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1070, in build
    restore_sequentially=self._restore_sequentially)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 675, in build
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 402, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 242, in restore_op
    [spec.tensor.dtype])[0])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 668, in restore_v2
    dtypes=dtypes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Tensor name "lstm/basic_lstm_cell/biases" not found in checkpoint files /home/raspberry/models/im2txt/im2txt_pretrained/model.ckpt-2000000
	 [[Node: save/RestoreV2_380 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_380/tensor_names, save/RestoreV2_380/shape_and_slices)]]

**Comment by mustafaxfe** [comment]
I have downgraded to 0.12 . But it still gives errors
`
bazel-bin/im2txt/run_inference   --checkpoint_path=${CHECKPOINT_DIR}   --vocab_file=${VOCAB_FILE}   --input_files=${IMAGE_FILE} --checkpoint_path="/home/raspberry/models/im2txt/im2txt_pretrained/model.ckpt-2000000"`

Traceback (most recent call last):
  File "/home/raspberry/workspace/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/run_inference.py", line 83, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/home/raspberry/workspace/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/run_inference.py", line 49, in main
    FLAGS.checkpoint_path)
  File "/home/raspberry/workspace/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/inference_utils/inference_wrapper_base.py", line 115, in build_graph_from_config
    self.build_model(model_config)
  File "/home/raspberry/workspace/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/inference_wrapper.py", line 36, in build_model
    model.build()
  File "/home/raspberry/workspace/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/show_and_tell_model.py", line 356, in build
    self.build_model()
  File "/home/raspberry/workspace/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/show_and_tell_model.py", line 247, in build_model
    lstm_cell = tf.contrib.rnn.BasicLSTMCell(
AttributeError: 'module' object has no attribute 'BasicLSTMCell'

**Comment by concretevitamin** [comment]
@cshallue  @ebrevdo does this have something to do with the recent RNN refactors?

**Comment by cshallue** [comment]
@mustafaxfe @concretevitamin 

Yes, this has to do with the RNN refactors. It looks like what's happened here is you trained your model with a previous version of TF, and now it won't open with the new version of TF. Downgrading the TF version on its own won't help, because this repository's code has been updated for TF 1.0.

It's quite simple to rename the offending Variables in your previous checkpoint. I believe this will work, although you may need to tweak it a bit.

```
vars_to_rename = {
      "rnn/BasicLSTMCell/Linear/Matrix": "lstm/basic_lstm_cell/weights",
      "rnn/BasicLSTMCell/Linear/Bias": "lstm/basic_lstm_cell/biases",
}
new_checkpoint_vars = {}
reader = tf.train.NewCheckpointReader(path_to_checkpoint)
for old_name in reader.get_variable_to_shape_map():
  if old_name in vars_to_rename:
    new_name = vars_to_rename[old_name]
  else:
    new_name = old_name
  new_checkpoint_vars[new_name] = tf.Variable(reader.get_tensor(old_name))

init = tf.global_variables_initializer()
saver = tf.train.Saver(new_checkpoint_vars)

with tf.Session() as sess:
  sess.run(init)
  saver.save(sess, path_to_new_checkpoint)
```

**Comment by mustafaxfe** [comment]
What will I do with this little code segment. I am not proficient programmer yet. But I have been studying...
Anyway I edited it as I can:
```
import tensorflow as tf
vars_to_rename = {
      "rnn/BasicLSTMCell/Linear/Matrix": "lstm/basic_lstm_cell/weights",
      "rnn/BasicLSTMCell/Linear/Bias": "lstm/basic_lstm_cell/biases",
}
new_checkpoint_vars = {}
reader = tf.train.NewCheckpointReader("/home/workspace/models/im2txt")
for old_name in reader.get_variable_to_shape_map():
  if old_name in vars_to_rename:
    new_name = vars_to_rename[old_name]
  else:
    new_name = old_name
  new_checkpoint_vars[new_name] = tf.Variable(reader.get_tensor(old_name))

init = tf.global_variables_initializer()
saver = tf.train.Saver(new_checkpoint_vars)

with tf.Session() as sess:
  sess.run(init)
  saver.save(sess, path_to_new_checkpoint)
```

**Comment by cshallue** [comment]
I just posted explicit instructions [here](https://github.com/tensorflow/models/issues/466)

**Comment by concretevitamin** [comment]
Thanks @cshallue!  I'm closing this issue for now; feel free to follow up in the other issue if it does not work for you @mustafaxfe.
