### ISSUE TITLE
[Windows - Bazel] ERROR: Executing genrule @llvm//:datatypes_gen failed

### ISSUE THREAD

**Issue by Carmezim** [tensorflow/tensorflow#8482]
Windows 10
Bazel 0.4.5
Visual C++ 2015
Msys2 v20160205
Python 3.5 (python.org distribution)

I am getting these genrule errors when building.

Configuring:
```
Adriano@Adriano MSYS /c/tensorflow
$ ./configure
Please specify the location of python. [Default is /c/Users/Adriano/AppData/Local/Programs/Python/Python35/python]:
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]:
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N] y
XLA JIT support will be enabled for TensorFlow
Found possible Python library paths:
  C:\Users\Adriano\AppData\Local\Programs\Python\Python35
  C:\Users\Adriano\AppData\Local\Programs\Python\Python35\lib\site-packages
Please input the desired Python library path to use.  Default is [C:\Users\Adriano\AppData\Local\Programs\Python\Python35]

Using python library path: C:\Users\Adriano\AppData\Local\Programs\Python\Python35
Junction created for util\python\python_include <<===>> C:\Users\Adriano\AppData\Local\Programs\Python\Python35\include
Junction created for util\python\python_lib <<===>> C:\Users\Adriano\AppData\Local\Programs\Python\Python35
Junction created for third_party\py\numpy\numpy_include <<===>> C:\Users\Adriano\AppData\Local\Programs\Python\Python35\lib\site-packages\numpy\core\include
Do you wish to build TensorFlow with CUDA support? [y/N] y
CUDA support will be enabled for TensorFlow
Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 8.0
Please specify the location where CUDA 8.0 toolkit is installed. Refer to README.md for more details. [Default is C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0]:
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 5.1
Please specify the location where cuDNN 5.1 library is installed. Refer to README.md for more details. [Default is C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0]:
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 5.0
.......................................................................................
INFO: All external dependencies fetched successfully.
Configuration finished
```

Building:
```

$ export BUILD_OPTS='--cpu=x64_windows_msvc --host_cpu=x64_windows_msvc --copt=/w --verbose_failures --experimental_ui'

Adriano@Adriano MSYS /c/tensorflow
$ bazel build -c opt $BUILD_OPTS --config=win-cuda tensorflow/tools/pip_package:build_pip_package
INFO: Analysed target //tensorflow/tools/pip_package:build_pip_package.
INFO: Found 1 target...
INFO: From Compiling tensorflow/core/util/version_info.cc [for host]:
Warning: Unmatched arguments: -Iexternal/gemmlowp -fno-exceptions -msse3
INFO: From Compiling tensorflow/core/lib/hash/crc32c_accelerate.cc [for host]:
Warning: Unmatched arguments: -Iexternal/gemmlowp -fno-exceptions -msse3 -msse4.2
Slow read: a 67403059-byte read from C:/tools/msys64/tmp/_bazel_adriano/x1e5egqw/external/local_config_cuda/cuda/include/sobol_direction_vectors.h took 9044ms.
INFO: From Compiling external/farmhash_archive/src/farmhash.cc [for host]:
C:\tools\msys64\tmp\_bazel_adriano\x1e5egqw\execroot\tensorflow\external\farmhash_archive\src\farmhash.cc(394): note: see reference to function template instantiation 'T util::DebugTweak<uint64_t>(T)' being compiled
        with
        [
            T=uint64_t
        ]
C:\tools\msys64\tmp\_bazel_adriano\x1e5egqw\execroot\tensorflow\external\farmhash_archive\src\farmhash.cc(1879): note: see reference to function template instantiation 'T util::DebugTweak<uint32_t>(T)' being compiled
        with
        [
            T=uint32_t
        ]
ERROR: C:/tools/msys64/tmp/_bazel_adriano/x1e5egqw/external/llvm/BUILD:162:1: Executing genrule @llvm//:datatypes_gen failed: bash.exe failed: error executing command
  cd C:/tools/msys64/tmp/_bazel_adriano/x1e5egqw/execroot/tensorflow
  SET PATH=C:\tools\msys64\usr\bin;C:\Users\Adriano\AppData\Local\Programs\Python\Python35\;C:\bazel\;c;C:\tools\msys64\Program Files\Java\jdk1.8.0_112\;C:\tools\msys64\usr\local\bin;C:\tools\msys64\usr\bin;C:\tools\msys64\usr\bin;C:\tools\msys64\opt\bin;C:\Windows\System32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\tools\msys64\usr\bin\site_perl;C:\tools\msys64\usr\bin\vendor_perl;C:\tools\msys64\usr\bin\core_perl
  C:/tools/msys64/usr/bin/bash.exe -c source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/third_party/llvm/expand_cmake_vars "HAVE_DIRENT_H=1" "HAVE_DLFCN_H=1" "HAVE_ERRNO_H=1" "HAVE_EXECINFO_H=1" "HAVE_FCNTL_H=1" "HAVE_INTTYPES_H=1" "HAVE_PTHREAD_H=1" "HAVE_SIGNAL_H=1" "HAVE_STDINT_H=1" "HAVE_SYS_IOCTL_H=1" "HAVE_SYS_MMAN_H=1" "HAVE_SYS_PARAM_H=1" "HAVE_SYS_RESOURCE_H=1" "HAVE_SYS_STAT_H=1" "HAVE_SYS_TIME_H=1" "HAVE_SYS_TYPES_H=1" "HAVE_TERMIOS_H=1" "HAVE_UNISTD_H=1" "HAVE_ZLIB_H=1" "HAVE_BACKTRACE=1" "HAVE_DLOPEN=1" "HAVE_FUTIMES=1" "HAVE_GETCWD=1" "HAVE_GETPAGESIZE=1" "HAVE_GETRLIMIT=1" "HAVE_GETRUSAGE=1" "HAVE_GETTIMEOFDAY=1" "HAVE_INT64_T=1" "HAVE_ISATTY=1" "HAVE_LIBEDIT=1" "HAVE_LIBPTHREAD=1" "HAVE_LIBZ=1" "HAVE_MKDTEMP=1" "HAVE_MKSTEMP=1" "HAVE_MKTEMP=1" "HAVE_PREAD=1" "HAVE_PTHREAD_GETSPECIFIC=1" "HAVE_PTHREAD_MUTEX_LOCK=1" "HAVE_PTHREAD_RWLOCK_INIT=1" "HAVE_REALPATH=1" "HAVE_SBRK=1" "HAVE_SETENV=1" "HAVE_SETRLIMIT=1" "HAVE_SIGALTSTACK=1" "HAVE_STRERROR=1" "HAVE_STRERROR_R=1" "HAVE_STRTOLL=1" "HAVE_SYSCONF=1" "HAVE_UINT64_T=1" "HAVE__UNWIND_BACKTRACE=1" "ENABLE_BACKTRACES=1" "LLVM_BINDIR=/dev/null" "LLVM_DISABLE_ABI_BREAKING_CHECKS_ENFORCING=0" "LLVM_ENABLE_ABI_BREAKING_CHECKS=0" "LLVM_ENABLE_THREADS=1" "LLVM_ENABLE_ZLIB=1" "LLVM_HAS_ATOMICS=1" "LLVM_INCLUDEDIR=/dev/null" "LLVM_INFODIR=/dev/null" "LLVM_MANDIR=/dev/null" "LLVM_NATIVE_TARGET=1" "LLVM_NATIVE_TARGETINFO=1" "LLVM_NATIVE_TARGETMC=1" "LLVM_NATIVE_ASMPRINTER=1" "LLVM_NATIVE_ASMPARSER=1" "LLVM_NATIVE_DISASSEMBLER=1" "LLVM_ON_UNIX=1" "LLVM_PREFIX=/dev/null" "LLVM_VERSION_MAJOR=0" "LLVM_VERSION_MINOR=0" "LLVM_VERSION_PATCH=0" "LTDL_SHLIB_EXT=.so" "PACKAGE_NAME=llvm" "PACKAGE_STRING=llvm tensorflow-trunk" "PACKAGE_VERSION=tensorflow-trunk" "RETSIGTYPE=void" "LLVM_HOST_TRIPLE=x86_64-unknown-linux_gnu" "LLVM_DEFAULT_TARGET_TRIPLE=x86_64-unknown-linux_gnu" "LLVM_NATIVE_ARCH=X86" "HAVE_MALLOC_H=1" "HAVE_LINK_H=1" "HAVE_MALLINFO=1" "HAVE_FUTIMENS=1"< external/llvm/include/llvm/Support/DataTypes.h.cmake > bazel-out/host/genfiles/external/llvm/include/llvm/Support/DataTypes.h: com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1
Traceback (most recent call last):
  File "C:\Users\Adriano\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Adriano\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "bazel-out\host\bin\third_party\llvm\expand_cmake_vars\__main__.py", line 168, in <module>
  File "bazel-out\host\bin\third_party\llvm\expand_cmake_vars\__main__.py", line 115, in Main
  File "bazel-out\host\bin\third_party\llvm\expand_cmake_vars\__main__.py", line 98, in CreateModuleSpace
  File "C:\Users\Adriano\AppData\Local\Programs\Python\Python35\lib\zipfile.py", line 1009, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '\\\\?\\bazel-out\\host\\bin\\third_party\\llvm\\expand_cmake_vars'
ERROR: C:/tools/msys64/tmp/_bazel_adriano/x1e5egqw/external/llvm/BUILD:183:1: declared output 'external/llvm/include/llvm/Config/abi-breaking.h' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely)
ERROR: C:/tools/msys64/tmp/_bazel_adriano/x1e5egqw/external/llvm/BUILD:176:1: declared output 'external/llvm/include/llvm/Config/llvm-config.h' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely)
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 205.884s, Critical Path: 69.60s
FAILED: Build did NOT complete successfully
```

**Comment by Carmezim** [comment]
cc @gunan @meteorcloudy

**Comment by meteorcloudy** [comment]
```
FileNotFoundError: [Errno 2] No such file or directory: '\\\\?\\bazel-out\\host\\bin\\third_party\\llvm\\expand_cmake_vars'
```
This is obviously a bug in Bazel's python stub template, sorry I didn't test 0.4.5 for TensorFlow GPU build, I'll fix it at Bazel HEAD soon.

**Comment by Carmezim** [comment]
This issue was fixed at Bazel's HEAD by [this commit](https://github.com/bazelbuild/bazel/commit/dce45d3151742338057f88f0a459ff442e05726f) so I am closing it.

For reference this is the issue on Bazel repo:
https://github.com/bazelbuild/bazel/issues/2708

**Comment by Carmezim** [comment]
@meteorcloudy  Do you know when there will be an rc with the fix? Unfortunately when I tried compiling from source at HEAD it terminates immediately as in ([issue](https://github.com/bazelbuild/bazel/issues/1275)):

```
$ ./compile.sh
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh compile /path/to/bazel
🍃  Building Bazel from scratch
```
Thanks

**Comment by meteorcloudy** [comment]
@Carmezim you can just build Bazel from HEAD by Bazel, `bazel build src:bazel`

**Comment by meteorcloudy** [comment]
But the GPU build is lack of maintenance for a long time, not sure it still works...

**Comment by Carmezim** [comment]
@meteorcloudy Ah, sorry, I've made a little confusion, I'd built with bazel afterwards but wasn't finding the binary, that is at bazel-bin. Thanks a lot.  I can update you if it builds successfully for GPU.

**Comment by Carmezim** [comment]
@meteorcloudy I got this when building for GPU, so I guess it does not work
```
$ bazel build -c opt $BUILD_OPTS --config=win-cuda tensorflow/tools/pip_package:build_pip_package
WARNING: C:/tensorflow/tensorflow/workspace.bzl:30:5:
Current Bazel is not a release version, cannot check for compatibility.
WARNING: C:/tensorflow/tensorflow/workspace.bzl:31:5: Make sure that you are running at least Bazel 0.4.5.
.
ERROR: no such target '//:FilesNVIDIA': target 'FilesNVIDIA' not declared in package '' defined by C:/tensorflow/BUILD.
INFO: Elapsed time: 2.239s

```

**Comment by Carmezim** [comment]
@meteorcloudy it indeed does not work for GPU support

```
$ bazel build -c opt $BUILD_OPTS --config=win-cuda tensorflow/tools/pip_package:build_pip_package
WARNING: C:/tensorflow/tensorflow/workspace.bzl:30:5:
Current Bazel is not a release version, cannot check for compatibility.
WARNING: C:/tensorflow/tensorflow/workspace.bzl:31:5: Make sure that you are running at least Bazel 0.4.5.
.
ERROR: no such target '//:GPU': target 'GPU' not declared in package '' defined by C:/tensorflow/BUILD.
INFO: Elapsed time: 9.422s
```

**Comment by mbartosi** [comment]
Same here on Gentoo Linux:

bazel build --config=opt --verbose_failures --config=cuda //tensorflow/tools/pip_package:build_pip_package
WARNING: /home/marek/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:exporter': Use SavedModel Builder instead.
WARNING: /home/marek/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:gc': Use SavedModel instead.
INFO: Found 1 target...
INFO: From Compiling external/protobuf/src/google/protobuf/compiler/js/embed.cc [for host]:
external/protobuf/src/google/protobuf/compiler/js/embed.cc:37:12: warning: unused variable 'output_file' [-Wunused-const-variable]
const char output_file[] = "well_known_types_embed.cc";
           ^
1 warning generated.
ERROR: /home/marek/.cache/bazel/_bazel_marek/c5662dc3bfe34c32bb2b10b5482b0731/external/llvm/BUILD:168:1: Executing genrule @llvm//:datatypes_gen failed: bash failed: error executing command 
  (cd /home/marek/.cache/bazel/_bazel_marek/c5662dc3bfe34c32bb2b10b5482b0731/execroot/tensorflow && \
  exec env - \
    CLANG_CUDA_COMPILER_PATH=/usr/lib/llvm/4/bin/clang \
    CUDA_TOOLKIT_PATH=/usr/local/cuda \
    CUDNN_INSTALL_PATH=/opt/cuda \
    PATH=/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/5.4.0:/usr/lib/llvm/4/bin:/opt/cuda/bin:/opt/cuda/libnvvp \
    PYTHON_BIN_PATH=/usr/bin/python \
    TF_CUDA_CLANG=1 \
    TF_CUDA_COMPUTE_CAPABILITIES=5.0 \
    TF_CUDA_VERSION=8.0 \
    TF_CUDNN_VERSION=6 \
    TF_NEED_CUDA=1 \
    TF_NEED_OPENCL=0 \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/third_party/llvm/expand_cmake_vars "HAVE_DIRENT_H=1" "HAVE_DLFCN_H=1" "HAVE_ERRNO_H=1" "HAVE_EXECINFO_H=1" "HAVE_FCNTL_H=1" "HAVE_INTTYPES_H=1" "HAVE_PTHREAD_H=1" "HAVE_SIGNAL_H=1" "HAVE_STDINT_H=1" "HAVE_SYS_IOCTL_H=1" "HAVE_SYS_MMAN_H=1" "HAVE_SYS_PARAM_H=1" "HAVE_SYS_RESOURCE_H=1" "HAVE_SYS_STAT_H=1" "HAVE_SYS_TIME_H=1" "HAVE_SYS_TYPES_H=1" "HAVE_TERMIOS_H=1" "HAVE_UNISTD_H=1" "HAVE_ZLIB_H=1" "HAVE_BACKTRACE=1" "BACKTRACE_HEADER=execinfo.h" "HAVE_DLOPEN=1" "HAVE_FUTIMES=1" "HAVE_GETCWD=1" "HAVE_GETPAGESIZE=1" "HAVE_GETRLIMIT=1" "HAVE_GETRUSAGE=1" "HAVE_GETTIMEOFDAY=1" "HAVE_INT64_T=1" "HAVE_ISATTY=1" "HAVE_LIBEDIT=1" "HAVE_LIBPTHREAD=1" "HAVE_LIBZ=1" "HAVE_MKDTEMP=1" "HAVE_MKSTEMP=1" "HAVE_MKTEMP=1" "HAVE_PREAD=1" "HAVE_PTHREAD_GETSPECIFIC=1" "HAVE_PTHREAD_MUTEX_LOCK=1" "HAVE_PTHREAD_RWLOCK_INIT=1" "HAVE_REALPATH=1" "HAVE_SBRK=1" "HAVE_SETENV=1" "HAVE_SETRLIMIT=1" "HAVE_SIGALTSTACK=1" "HAVE_STRERROR=1" "HAVE_STRERROR_R=1" "HAVE_STRTOLL=1" "HAVE_SYSCONF=1" "HAVE_UINT64_T=1" "HAVE__UNWIND_BACKTRACE=1" "ENABLE_BACKTRACES=1" "LLVM_BINDIR=/dev/null" "LLVM_DISABLE_ABI_BREAKING_CHECKS_ENFORCING=0" "LLVM_ENABLE_ABI_BREAKING_CHECKS=0" "LLVM_ENABLE_THREADS=1" "LLVM_ENABLE_ZLIB=1" "LLVM_HAS_ATOMICS=1" "LLVM_INCLUDEDIR=/dev/null" "LLVM_INFODIR=/dev/null" "LLVM_MANDIR=/dev/null" "LLVM_NATIVE_TARGET=1" "LLVM_NATIVE_TARGETINFO=1" "LLVM_NATIVE_TARGETMC=1" "LLVM_NATIVE_ASMPRINTER=1" "LLVM_NATIVE_ASMPARSER=1" "LLVM_NATIVE_DISASSEMBLER=1" "LLVM_ON_UNIX=1" "LLVM_PREFIX=/dev/null" "LLVM_VERSION_MAJOR=0" "LLVM_VERSION_MINOR=0" "LLVM_VERSION_PATCH=0" "LTDL_SHLIB_EXT=.so" "PACKAGE_NAME=llvm" "PACKAGE_STRING=llvm tensorflow-trunk" "PACKAGE_VERSION=tensorflow-trunk" "RETSIGTYPE=void" "LLVM_HOST_TRIPLE=x86_64-unknown-linux_gnu" "LLVM_DEFAULT_TARGET_TRIPLE=x86_64-unknown-linux_gnu" "LLVM_NATIVE_ARCH=X86" "HAVE_MALLOC_H=1" "HAVE_LINK_H=1" "HAVE_MALLINFO=1" "HAVE_FUTIMENS=1"< external/llvm/include/llvm/Support/DataTypes.h.cmake > bazel-out/local_linux-py3-opt/genfiles/external/llvm/include/llvm/Support/DataTypes.h'): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 127.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 20.079s, Critical Path: 10.94s
