### ISSUE TITLE
import error after installing tensorflow from source

### ISSUE THREAD

**Issue by prakashyadav008** [tensorflow/tensorflow#8530]
i have build tensorflow from source and got a lot of warning but it was done without errors.But now when I import tensorflow it is giving the error mentioned below:

`p_rakash@prakash008:~$ python3
Python 3.5.2 |Anaconda 4.3.1 (64-bit)| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "/home/prakash/anaconda3/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
ImportError: cannot import name 'pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/prakash/anaconda3/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/prakash/anaconda3/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/prakash/anaconda3/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
ImportError: cannot import name 'pywrap_tensorflow'`_

any suggestion..?
I have a nvidia 720m gpu and python 3.5.2 from anaconda and I hav installed the gpu version of tensorflow.

**Comment by skye** [comment]
Are you running Python from the TensorFlow source directory? See https://www.tensorflow.org/versions/master/get_started/os_setup#import_error

**Comment by asimshankar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
