### ISSUE TITLE
pool allocator spending more than 18h to allocate and still not finished

### ISSUE THREAD

**Issue by kirk86** [tensorflow/tensorflow#8536]
Hey guys, I've been having this issue which I don't really understand if it's related to memory issues or not. I've tested it on cpu and the code runs fine without any issues. On gpu I get the following messages:

```
2017-03-18 14:21:51,379 INFO - I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties:
2017-03-18 14:21:51,379 INFO - name: Tesla K80
2017-03-18 14:21:51,379 INFO - major: 3 minor: 7 memoryClockRate (GHz) 0.8235
2017-03-18 14:21:51,380 INFO - pciBusID 0000:00:1e.0
2017-03-18 14:21:51,380 INFO - Total memory: 11.17GiB
2017-03-18 14:21:51,380 INFO - Free memory: 11.11GiB
2017-03-18 14:21:51,381 INFO -  DMA: 0
2017-03-18 14:21:51,381 INFO -  Y
2017-03-18 14:21:51,394 INFO - Creating TensorFlow device (/gpu:0) -> 
(device: 0, name: Tesla K80, pci bus id: 0000:00:1e.0) 2017-03-18 14:22:06,005
PoolAllocator: After 2898 get requests, put_count=2334 evicted_count=1000 
eviction_rate=0.428449 and unsatisfied allocation rate=0.574189
2017-03-18 14:22:06,025 INFO - Raising pool_size_limit_ from 100 to 110
2017-03-18 14:48:17,797 INFO -  PoolAllocator: After 2898 get requests, put_count=3604
 evicted_count=2000 eviction_rate=0.554939 and unsatisfied allocation rate=0.452381
2017-03-18 14:48:17,800 INFO - Raising pool_size_limit_ from 193 to 212
2017-03-18 15:30:38,803 INFO - PoolAllocator: After 2898 get requests, put_count=2881 
evicted_count=1000 eviction_rate=0.347102 and unsatisfied allocation rate=0.364734
2017-03-18 15:30:38,806 INFO - Raising pool_size_limit_ from 449 to 493
2017-03-18 16:46:39,551 INFO - PoolAllocator: After 8694 get requests, put_count=8682 
evicted_count=1000 eviction_rate=0.115181 and unsatisfied allocation rate=0.128479
2017-03-18 16:46:39,554 INFO - Raising pool_size_limit_ from 1158 to 1273
```
It's been like this for 18h and still no output or training has started, is this a known issue. Why does it take so long for the memory allocator to finish?

**Comment by concretevitamin** [comment]
Are you sure (1) your training hasn't started, and (2) is it not a memory problem in your model?

For (1), check if there's any event/checkpoint files being outputted.  For (2), check your input pipeline, etc.

A relevant SO question and answer that explains what the pool allocator messages mean:  http://stackoverflow.com/questions/35151207/how-to-interpret-poolallocator-messages-in-tensorflow

**Comment by skye** [comment]
@kirk86 can you collect a stack trace from the TensorFlow process while it's hanging? You can use gdb like this:
```
$ gdb
(gdb) attach <tensorflow process id>
```
If gdb gives you a weird message about ptrace, run the following in a terminal and try attaching again:
`$ echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope`

Once you're attached in gdb, collect stack traces with all the threads:
`(gdb) thread apply all bt`

**Comment by kirk86** [comment]
@skye Sure I'll give it a try, can't give no promises though since I have no control over the environment. It runs inside in a docker container (as far as I know) which is being created and destroyed every time I execute the code. Think of it sth equivalent of google cloud. Let me see what I can collect and I'll get back to you guys. Thanks for the advice.

**Comment by kirk86** [comment]
@skye Hi, may I ask for a clarification. So I'm running the code inside a multiplexer session and I try to follow your example. When I run the code since it runs on multicore machine it creates pid's for each core. Which one should I choose according to you example?

When I gdb on one of the pid's then I only get information about reading symbols and loaded symbols is that the expected result?

**Comment by skye** [comment]
Actually, looking at your log again, it's not clear to me that the problem is in the allocator. It just happens that the last LOG message was from there, but it could be hanging anywhere.

Could you provide the information asked for in the new issue template, like a repro script for the hang? Thanks.

**Comment by kirk86** [comment]
@skye hello, so I've created a gist with an example https://gist.github.com/kirk86/99211bd0ea3489915738701285c58c30. The example works fine on cpu but on a gpu with 12GB ram it gives me error exhausted message even when I reduce the batch_size to 1.

Here's the output message that I get:

```
ResourceExhaustedErrorTraceback (most recent call last)
/output/run.py in <module>()
     40     model.fit(trX, [np.expand_dims(trX_mask[:, :, :, 0], axis=3), trY], batch_size=1, nb_epoch=40,
     41               shuffle=True, validation_data=(valX, [np.expand_dims(valX_mask[:, :, :, 0], axis=3), valY]),
---> 42               verbose=1)
     43     # classes = {0: 'ALB', 1: 'BET', 2: 'DOL', 3: 'LAG', 4: 'NoF',
     44     #            5: 'OTHER', 6: 'SHARK', 7: 'YFT'}

/usr/local/lib/python2.7/site-packages/keras/engine/training.pyc in fit(self, x, y, batch_size, nb_epoch, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch)
   1194                               val_f=val_f, val_ins=val_ins, shuffle=shuffle,
   1195                               callback_metrics=callback_metrics,
-> 1196                               initial_epoch=initial_epoch)
   1197 
   1198     def evaluate(self, x, y, batch_size=32, verbose=1, sample_weight=None):

/usr/local/lib/python2.7/site-packages/keras/engine/training.pyc in _fit_loop(self, f, ins, out_labels, batch_size, nb_epoch, verbose, callbacks, val_f, val_ins, shuffle, callback_metrics, initial_epoch)
    889                 batch_logs['size'] = len(batch_ids)
    890                 callbacks.on_batch_begin(batch_index, batch_logs)
--> 891                 outs = f(ins_batch)
    892                 if not isinstance(outs, list):
    893                     outs = [outs]

/usr/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.pyc in __call__(self, inputs)
   1939                 value = (indices, sparse_coo.data, sparse_coo.shape)
   1940             feed_dict[tensor] = value
-> 1941         session = get_session()
   1942         updated = session.run(self.outputs + [self.updates_op],
   1943                               feed_dict=feed_dict)

/usr/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.pyc in get_session()
    123         session = _SESSION
    124     if not _MANUAL_VAR_INIT:
--> 125         _initialize_variables()
    126     return session
    127 

/usr/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.pyc in _initialize_variables()
    280         sess = get_session()
    281         if hasattr(tf, 'variables_initializer'):
--> 282             sess.run(tf.variables_initializer(uninitialized_variables))
    283         else:
    284             sess.run(tf.initialize_variables(uninitialized_variables))

/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in run(self, fetches, feed_dict, options, run_metadata)
    765     try:
    766       result = self._run(None, fetches, feed_dict, options_ptr,
--> 767                          run_metadata_ptr)
    768       if run_metadata:
    769         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _run(self, handle, fetches, feed_dict, options, run_metadata)
    963     if final_fetches or final_targets:
    964       results = self._do_run(handle, final_targets, final_fetches,
--> 965                              feed_dict_string, options, run_metadata)
    966     else:
    967       results = []

/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1013     if handle is None:
   1014       return self._do_call(_run_fn, self._session, feed_dict, fetch_list,
-> 1015                            target_list, options, run_metadata)
   1016     else:
   1017       return self._do_call(_prun_fn, self._session, handle, feed_dict,

/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _do_call(self, fn, *args)
   1033         except KeyError:
   1034           pass
-> 1035       raise type(e)(node_def, op, message)
   1036 
   1037   def _extend_graph(self):

ResourceExhaustedError: OOM when allocating tensor with shape[8388608,64]
	 [[Node: random_uniform_28 = Add[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](random_uniform_28/mul, random_uniform_28/min)]]

Caused by op u'random_uniform_28', defined at:
  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 474, in start
    ioloop.IOLoop.instance().start()
  File "/usr/local/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/usr/local/lib/python2.7/site-packages/tornado/ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "/usr/local/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/local/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python2.7/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python2.7/site-packages/ipykernel/zmqshell.py", line 501, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2827, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-285366c3fbbf>", line 1, in <module>
    get_ipython().magic(u'run -i run.py')
  File "/usr/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2158, in magic
    return self.run_line_magic(magic_name, magic_arg_s)
  File "/usr/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2079, in run_line_magic
    result = fn(*args,**kwargs)
  File "<decorator-gen-57>", line 2, in run
  File "/usr/local/lib/python2.7/site-packages/IPython/core/magic.py", line 188, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)
  File "/usr/local/lib/python2.7/site-packages/IPython/core/magics/execution.py", line 742, in run
    run()
  File "/usr/local/lib/python2.7/site-packages/IPython/core/magics/execution.py", line 728, in run
    exit_ignore=exit_ignore)
  File "/usr/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2481, in safe_execfile
    self.compile if kw['shell_futures'] else None)
  File "/usr/local/lib/python2.7/site-packages/IPython/utils/py3compat.py", line 289, in execfile
    builtin_mod.execfile(filename, *where)
  File "/output/run.py", line 39, in <module>
    model = unet((512, 512, 3))
  File "/output/unet.py", line 203, in unet
    dense1 = Dense(64, activation='relu', name='fc1')(flat)
  File "/usr/local/lib/python2.7/site-packages/keras/engine/topology.py", line 546, in __call__
    self.build(input_shapes[0])
  File "/usr/local/lib/python2.7/site-packages/keras/layers/core.py", line 798, in build
    constraint=self.W_constraint)
  File "/usr/local/lib/python2.7/site-packages/keras/engine/topology.py", line 418, in add_weight
    weight = initializer(shape, name=name)
  File "/usr/local/lib/python2.7/site-packages/keras/initializations.py", line 66, in glorot_uniform
    return uniform(shape, s, name=name)
  File "/usr/local/lib/python2.7/site-packages/keras/initializations.py", line 33, in uniform
    return K.random_uniform_variable(shape, -scale, scale, name=name)
  File "/usr/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 634, in random_uniform_variable
    low, high, dtype=tf_dtype, seed=seed)(shape)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/init_ops.py", line 180, in __call__
    dtype, seed=self.seed)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/random_ops.py", line 246, in random_uniform
    return math_ops.add(rnd * (maxval - minval), minval, name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 73, in add
    result = _op_def_lib.apply_op("Add", x=x, y=y, name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[8388608,64]
	 [[Node: random_uniform_28 = Add[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](random_uniform_28/mul, random_uniform_28/min)]]
```

**Comment by skye** [comment]
This seems like a different problem than the hang you originally posted, no? Perhaps there's some other application using the GPU's memory, the `nvidia_smi` command will tell you which processes are using how much memory. I can try to repro once I have access to a beefy GPU.

**Comment by kirk86** [comment]
@skye thanks a lot. Yes you're right this was a bit different in terms of environment. I'll also try to provide more info about the first original problem. Didn't had the time or the resources available. I'll try it over the weekend.

**Comment by Peri044** [comment]
@kirk86 Hey kirk86, I'm facing a similar issue to your first original problem. It takes hours and is not going any further. Any leads on this? Thanks

**Comment by kirk86** [comment]
@Peri044 Hey, have you checked reducing the batch size. Does it happen the same even with batch size of 1?
