### ISSUE TITLE
error when attempting to run image_retraining

### ISSUE THREAD

**Issue by sria91** [tensorflow/tensorflow#8575]
### Environment info
Operating System: Ubuntu Linux 16.04 LTS

Installed from source
1. Tensorflow version: 1.0.1
2. The output of `bazel version`: 
```
Build label: 0.4.5
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Mar 16 12:19:38 2017 (1489666778)
Build timestamp: 1489666778
Build timestamp as int: 1489666778
```
### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
Link to the tutorial: https://www.tensorflow.org/tutorials/image_retraining
```
bazel-bin/tensorflow/examples/image_retraining/retrain --image_dir ~/flower_photos
```

### Logs or other output that would be helpful
```
Traceback (most recent call last):
  File "/home/sria91/Development/tensorflow-1.0.1/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/examples/image_retraining/retrain.py", line 1052, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/sria91/Development/tensorflow-1.0.1/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/sria91/Development/tensorflow-1.0.1/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/examples/image_retraining/retrain.py", line 768, in main
    maybe_download_and_extract()
  File "/home/sria91/Development/tensorflow-1.0.1/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/examples/image_retraining/retrain.py", line 305, in maybe_download_and_extract
    tarfile.open(filepath, 'r:gz').extractall(dest_directory)
  File "/usr/lib/python3.5/tarfile.py", line 1996, in extractall
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.5/tarfile.py", line 2038, in extract
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.5/tarfile.py", line 2108, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/lib/python3.5/tarfile.py", line 2156, in makefile
    copyfileobj(source, target, tarinfo.size, ReadError)
  File "/usr/lib/python3.5/tarfile.py", line 241, in copyfileobj
    buf = src.read(BUFSIZE)
  File "/usr/lib/python3.5/gzip.py", line 274, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.5/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.5/gzip.py", line 480, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
```

**Comment by derekhh** [comment]
I think the error `EOFError: Compressed file ended before the end-of-stream marker was reached` means the model file you've downloaded `http://download.tensorflow.org/models/image/imagenet/inception-2015-12-05.tgz` is incomplete. Try to download the model file again.

**Comment by sria91** [comment]
@derekhh Many thanks, that helped.

**Comment by Srigowri** [comment]
I came across the same error.I abruptly stopped when inception was being downloaded. @sria91  where have you saved the downloaded model?

**Comment by sria91** [comment]
@Srigowri By default, the model gets downloaded to `/tmp/imagenet`. Delete that folder and run `image_retraining` again.

**Comment by Srigowri** [comment]
Thanks 👍  @sria91
