### ISSUE TITLE
OutOfMemoryError: Java heap space on Tensorflow tests execution

### ISSUE THREAD

**Issue by Nayana-ibm** [tensorflow/tensorflow#8579]
Executing Tensorflow test suite using command: 

    bazel test //tensorflow/...

throws Out of memory issue: 

    INFO: Found 1886 targets and 1155 test targets...
    INFO: Elapsed time: 291.775s, Critical Path: 0.91s
    java.lang.OutOfMemoryError: Java heap space
            at com.google.devtools.build.skyframe.SkyKey.create(SkyKey.java:57)
            at com.google.devtools.build.lib.skyframe.ArtifactSkyKey.key(ArtifactSkyKey.java:43)
            at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.toKeys(ActionExecutionFunction.java:576)
            at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:158)
            at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:370)
            at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:501)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
            at java.lang.Thread.run(Thread.java:745)
    Java heap space
    
    bazel ran out of memory and crashed.

I have tried below options still issue persists. 

> export _JAVA_OPTIONS="-Xms1024m -Xmx1024m"
> 
> export JVM_ARGS="-Xmx1024m -XX:MaxPermSize=256m"
> 
> export JVM_ARGS="-XX:PermSize=64M -XX:MaxPermSize=256m"

Also, changed the file from bazel code: scripts/bootstrap/compile.sh

`" run "${JAVAC}" -J-Xms1g -J-Xmx1g -classpath "${classpath}" -sourcepath "${sourcepath}"`"

Machine configurations: Ubuntu distribution, openjdk8, RAM 16G
TensorFlow : master

**Comment by Nayana-ibm** [comment]
Below command worked from me: 

`bazel  --host_jvm_args="-Xms512m" --host_jvm_args="-Xmx1024m"  test //tensorflow/...`

**Comment by skye** [comment]
Thank you for sharing the solution to your problem!
