### ISSUE TITLE
SyntaxError: name '_googletest_temp_dir' is used prior to global declaration

### ISSUE THREAD

**Issue by doantientai** [tensorflow/tensorflow#8664]
I am following tutorial https://www.tensorflow.org/tutorials/image_retraining

The code successfully complied with Bazel but failed to run with command

`bazel-bin/tensorflow/examples/image_retraining/retrain --image_dir ~/flower_photos`

With a very strange ERROR:

> Traceback (most recent call last):
  File "/home/tai/Desktop/TaiM2/tensorflow/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/examples/image_retraining/retrain.py", line 79, in <module>
    import tensorflow as tf
  File "/home/tai/Desktop/TaiM2/tensorflow/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/tai/Desktop/TaiM2/tensorflow/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 104, in <module>
    from tensorflow.python.platform import test
  File "/home/tai/Desktop/TaiM2/tensorflow/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/python/platform/test.py", line 38, in <module>
    from tensorflow.python.framework import test_util as _test_util
  File "/home/tai/Desktop/TaiM2/tensorflow/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 46, in <module>
    from tensorflow.python.platform import googletest
  File "/home/tai/Desktop/TaiM2/tensorflow/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/python/platform/googletest.py", line 118
    global _googletest_temp_dir
SyntaxError: name '_googletest_temp_dir' is used prior to global declaration

When I run the **retrain.py** directly with python, the error did not show up. It only happens when I use bazel. Can anyone explain why?

**Comment by gunan** [comment]
This is fixed at head by commit https://github.com/tensorflow/tensorflow/commit/81fcc25ae5c92318ff607a5be3ff06446e232134
