### ISSUE TITLE
Symbol not found: _SSLCreateContext in Python REPL

### ISSUE THREAD

**Issue by ivijay** [tensorflow/tensorflow#8772]
I have installed tensorflow 1.0.1 (cpu version) on Mac as following .
 
`sudo pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.0.1-py2-none-any.whl`

At the end of installation, I got the following message:
`Successfully installed tensorflow-1.0.1`

But unable to import the libraries in python.

### Environment info
Operating System:
Mac version:
```
Software:
    System Software Overview:
      System Version: Mac OS X 10.7.5 (11G63)
      Kernel Version: Darwin 11.4.2
      64-bit Kernel and Extensions: Yes

```
Python version: 
```
$ python
Python 2.7.1 (r271:86832, Jul 31 2011, 19:30:53) 
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2335.15.00)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 

```
Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
```
$ ls -l /path/to/cuda/lib/libcud*
ls: /path/to/cuda/lib/libcud*: No such file or directory
```
If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

```
$ python -c "import tensorflow; print(tensorflow.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mobility1/tensorflow/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/mobility1/tensorflow/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Users/mobility1/tensorflow/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/mobility1/tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/Users/mobility1/tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: dlopen(/Users/mobility1/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): Symbol not found: _SSLCreateContext
  Referenced from: /Users/mobility1/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
  Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
 in /Users/mobility1/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so


Failed to load the native TensorFlow runtime.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

```

**Comment by aselle** [comment]
You are using an old version of mac os (lion). We do not support older than El Capitan (10.11).
-A
