### ISSUE TITLE
uninstall tensorflow from windows

### ISSUE THREAD

**Issue by ymakkapa** [tensorflow/tensorflow#8785]
Hello,
I installed python and tensorflow in windows 10. How can I uninstall it?

Thanks in advance

**Comment by Carmezim** [comment]
Hi @ymakkapa, `pip uninstall tensorflow` will do it if you installed through `pip`.

**Comment by ymakkapa** [comment]
Hi @Carmezim , I did as you said. It processed for a while and I got the following errors
![uninstall](https://cloud.githubusercontent.com/assets/20130992/24431763/f609b332-13eb-11e7-8559-32330a3fbae5.PNG)

**Comment by Carmezim** [comment]
Can you show what you did before please? Did you install it with `pip install` without GPU support right?
Also, upgrade pip as the warning message suggests.

**Comment by ymakkapa** [comment]
I cannot show as I closed that window. I installed it with pip and without GPU.

**Comment by Carmezim** [comment]
Can you reproduce it and share the steps?

**Comment by ymakkapa** [comment]
Hi, running the same line again gives the following output. I think tensorflow is uninstalled
C:\WINDOWS\system32>pip uninstall tensorflow
Cannot uninstall requirement tensorflow, not installed
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by Carmezim** [comment]
It is uninstalled. If you don't have any other questions, the issue can be closed now otherwise feel free to ask. 
Thank you for opening the issue and bearing with me.

**Comment by sewnet** [comment]
I have a similar issue. I have installed tensorflow GPU version successfully.
But  when I try to import tensorflow in a python program, I get a similar error.
I then uninstalled the GPU version, keeping only the CPU version.

Then, import tensorflow, works fine for me.
But I need to work on the GPU version. Help me solve the problem. Please!!

**Comment by fzr2009** [comment]
I too have same issue, as I install tensflow-gpu 1.8.0 using pip but when I uninstall it and it does not.

![tensor issue](https://user-images.githubusercontent.com/36807429/39409312-2288920c-4bfe-11e8-9242-19306835d079.PNG)

**Comment by fzr2009** [comment]
I did " pip uninstall tensorflow-gpu " and " pip uninstall tensorflow-gpu==1.8.0 ", this happens

![tensor issue 2](https://user-images.githubusercontent.com/36807429/39409327-9dafc25c-4bfe-11e8-9c3e-13f9cd173151.PNG)

**Comment by mangozy** [comment]
Same thing happened to me too!
![capture](https://user-images.githubusercontent.com/32133971/41425574-233d9338-6fcf-11e8-96bd-5c7148719ed4.PNG)

**Comment by fzqneo** [comment]
Why was this closed? Is it fixed?

**Comment by oxygenxo** [comment]
pip uninstall tensorflow on Windows fails with the same error on my machines. There is no reason to close this issue.

**Comment by harry67yqh** [comment]
@maxamante 's solution works well. The install directory of tensorflow does have a path which is too long.

**Comment by Umar-Ayub** [comment]
This issue should not be closed. I have the same error and I tried @maxamante  solution on two different Windows systems and it doesn't change anything for me. Below is the traceback I got. Please help:

Exception:
Traceback (most recent call last):
  File "C:\Users\ua12\AppData\Local\conda\conda\envs\DLCdependencies\lib\shutil.py", line 544, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'c:\\users\\ua12\\appdata\\local\\conda\\conda\\envs\\dlcdependencies\\lib\\site-packages\\tensorflow\\include\\tensorflow\\include\\external\\eigen_archive\\unsupported\\eigen\\cxx11\\src\\tensor\\tensorsyclconverttodeviceexpression.h' -> 'C:\\Users\\ua12\\AppData\\Local\\Temp\\pip-uninstall-n6zjpcds\\users\\ua12\\appdata\\local\\conda\\conda\\envs\\dlcdependencies\\lib\\site-packages\\tensorflow\\include\\tensorflow\\include\\external\\eigen_archive\\unsupported\\eigen\\cxx11\\src\\tensor\\tensorsyclconverttodeviceexpression.h'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ua12\AppData\Local\conda\conda\envs\DLCdependencies\lib\site-packages\pip\_internal\basecommand.py", line 228, in main
    status = self.run(options, args)
  File "C:\Users\ua12\AppData\Local\conda\conda\envs\DLCdependencies\lib\site-packages\pip\_internal\commands\uninstall.py", line 68, in run
    auto_confirm=options.yes, verbose=self.verbosity > 0,
  File "C:\Users\ua12\AppData\Local\conda\conda\envs\DLCdependencies\lib\site-packages\pip\_internal\req\req_install.py", line 661, in uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  File "C:\Users\ua12\AppData\Local\conda\conda\envs\DLCdependencies\lib\site-packages\pip\_internal\req\req_uninstall.py", line 219, in remove
    renames(path, new_path)
  File "C:\Users\ua12\AppData\Local\conda\conda\envs\DLCdependencies\lib\site-packages\pip\_internal\utils\misc.py", line 273, in renames
    shutil.move(old, new)
  File "C:\Users\ua12\AppData\Local\conda\conda\envs\DLCdependencies\lib\shutil.py", line 558, in move
    copy_function(src, real_dst)
  File "C:\Users\ua12\AppData\Local\conda\conda\envs\DLCdependencies\lib\shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\ua12\AppData\Local\conda\conda\envs\DLCdependencies\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ua12\\AppData\\Local\\Temp\\pip-uninstall-n6zjpcds\\users\\ua12\\appdata\\local\\conda\\conda\\envs\\dlcdependencies\\lib\\site-packages\\tensorflow\\include\\tensorflow\\include\\external\\eigen_archive\\unsupported\\eigen\\cxx11\\src\\tensor\\tensorsyclconverttodeviceexpression.h'
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by willSapgreen** [comment]
Please reopen this issue because @maxamante 's approach doesn't resolve the issue,
and I have the same error as @Umar-Ayub does on TensorFlow GPU version 1.10.0
Thank you.

**Comment by bhumireddyc** [comment]
Does the below mean tensorflow is uninstalled?

>>conda remove -n tensorflow pip python=3.6
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.4
  latest version: 4.5.11

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: C:\Users\Chand\Anaconda3\envs\tensorflow

  removed specs:
    - pip
    - python=3.6


The following packages will be REMOVED:

    certifi:      2018.8.24-py36_1
    pip:          10.0.1-py36_0
    python:       3.6.6-hea74fb7_0
    setuptools:   40.2.0-py36_0
    wheel:        0.31.1-py36_0
    wincertstore: 0.2-py36h7fe50ca_0

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

**Comment by maxamante** [comment]
@Umar-Ayub @willSapgreen Are you trying to uninstall? Do the files exist even though a FileNotFoundError is raised?

**Comment by ddomit** [comment]
I have the same problem!! I already tried the solution mentioned here of enabling long paths but im still getting the same results. Please Help!



Exception:
Traceback (most recent call last):
  File "c:\users\daniel domit\appdata\local\conda\conda\envs\robond\lib\shutil.py", line 544, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'c:\\users\\daniel domit\\appdata\\local\\conda\\conda\\envs\\robond\\lib\\site-packages\\tensorflow\\include\\tensorflow\\include\\external\\eigen_archive\\unsupported\\eigen\\cxx11\\src\\tensor\\tensorcontractionthreadpool.h' -> 'C:\\Users\\DANIEL~1\\AppData\\Local\\Temp\\pip-uninstall-lyhm1m_z\\users\\daniel domit\\appdata\\local\\conda\\conda\\envs\\robond\\lib\\site-packages\\tensorflow\\include\\tensorflow\\include\\external\\eigen_archive\\unsupported\\eigen\\cxx11\\src\\tensor\\tensorcontractionthreadpool.h'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

**Comment by amanharitsh123** [comment]
Why the issue is closed? we are still facing this problem

**Comment by amanharitsh123** [comment]
I have found a workaround , 
`pip show tensorflow-gpu` 
Open the installed directory as shown by the above output and delete all tensorflow folders there.

**Comment by cssaheel** [comment]
just go to C:\Users\USERNAME\AppData\Local\Programs\Python\Python35\Lib\site-packages
and rename the folder of tensorflow to something else. That worked for me!

**Comment by amritarana** [comment]
> I have a similar issue. I have installed tensorflow GPU version successfully.
> But when I try to import tensorflow in a python program, I get a similar error.
> I then uninstalled the GPU version, keeping only the CPU version.
> 
> Then, import tensorflow, works fine for me.
> But I need to work on the GPU version. Help me solve the problem. Please!!

how did you uninstall the GPU version. I have tensorflow-gpu==1.12.0. I couldn't uninstall it using pip.

**Comment by zhouxf53** [comment]
> pip show tensorflow-gpu

Worked for me as well

**Comment by prabindh** [comment]
Since the issue is really due to long file name, it should be temporarily fixed using the Registry-longfilename setting as mentioned at - https://github.com/conda/conda/issues/7203. This setting can be changed back to 0 after the uninstall to avoid breaking other tools. Worked for me (Conda Py3.7/tf1.13).

**Comment by RohanKPatil** [comment]
The uninstall worked successfully for me with `conda uninstall tensorflow`. pip was giving me the same error.

**Comment by hjnnjh** [comment]
> @fzr2009 @mangozy @anyoneelse I ran into this issue recently. I was able to fix it by allowing [longer filenames in Python](https://docs.python.org/3/using/windows.html#removing-the-max-path-limitation).

Thank you, it's useful.

**Comment by Jyothif** [comment]
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "C:\Users\hello\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\hello\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\hello\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\hello\Anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\hello\Anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hello\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-d6579f534729>", line 1, in <module>
    import tensorflow
  File "C:\Users\hello\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\hello\Anaconda3\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\hello\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\hello\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\hello\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\hello\Anaconda3\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\hello\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\hello\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\hello\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\hello\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\hello\Anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\hello\Anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hello\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2040, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'ImportError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hello\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\hello\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\hello\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\hello\Anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\hello\Anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hello\Anaconda3\lib\site-packages\IPython\core\ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)

**Comment by Jyothif** [comment]
I am also facing the same issue please someone help me on this

**Comment by Rajesh16702** [comment]
The pip uninstall was taking longer time even 2 hour and nothing happens. I went to the tensorflow location and deleted the folder. e.g. for me the path was- C:\Users\Username\Anaconda3\Lib\site-packages. I deleted anything that starts with tensor.
 I then install tensorflow using conda and then keras.
