### ISSUE TITLE
tensorflow can not be imported in python

### ISSUE THREAD

**Issue by himanshubdave** [tensorflow/tensorflow#8789]
Tensorflow  (CPU) can not be imported in python 2.7 

Operating System: Linux; output of uname -a
Linux laptop 4.4.14 #2 SMP Fri Jun 24 13:38:27 CDT 2016 x86_64 Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz GenuineIntel GNU/Linux

Installed version of CUDA and cuDNN: NONE 

Installed within virtualenv, via pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.0.1-cp27-none-linux_x86_64.whl

Output from python while attempting to import tensorflow:
-------------------------------------------------------------------------
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/tensorflow/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/opt/tensorflow/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/opt/tensorflow/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/opt/tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/opt/tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: /opt/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: PyUnicodeUCS4_AsUTF8String

Failed to load the native TensorFlow runtime.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error

**Comment by gunan** [comment]
Which linux distribution are you using?
I think you are running into this:

https://github.com/tensorflow/tensorflow/issues/5336

**Comment by himanshubdave** [comment]
Thanks gunan.
I am using slackware 14.2 (63-bit).
On checking various issues (including the one that Gunan pointed out), I decided to compile TensorFlow from source. That involved first installing Bazel on my system, but it was successful and now I am able to import tensorflow in python and run various example programs.
