### ISSUE TITLE
Unable to run example convolutional.py

### ISSUE THREAD

**Issue by waoudi** [tensorflow/tensorflow#880]
Hello,
I did the three differents installations
based on pip
based on virtualenv 
based on docker.
i am on Virtual Machine (VM Virtual Box) with Ubuntu.

and i have these errors when trying to run :

root@b6782358bd01:/usr/local/lib/python2.7/dist-packages/tensorflow/models/image/mnist# python -m tensorflow.models.image.mnist.convolutional
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/image/mnist/convolutional.py", line 290, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/image/mnist/convolutional.py", line 121, in main
    train_data_filename = maybe_download('train-images-idx3-ubyte.gz')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/image/mnist/convolutional.py", line 59, in maybe_download
    filepath, _ = urllib.request.urlretrieve(SOURCE_URL + filename, filepath)
  File "/usr/lib/python2.7/urllib.py", line 94, in urlretrieve
    return _urlopener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 240, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 208, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 352, in open_http
    'got a bad status line', None)
IOError: ('http protocol error', 0, 'got a bad status line', None)

i did not suceed with the three methods. can anyone who has found these issues help me. Thanks in advance. Best Regards.

**Comment by vincentvanhoucke** [comment]
The server hosting MNIST is currently down.

**Comment by marcoslin** [comment]
The source of the dataset http://yann.lecun.com/exdb/mnist/ is down since at least this past Sunday.  Anyone know of alternate URL?

**Comment by vincentvanhoucke** [comment]
https://www.reddit.com/r/MachineLearning/comments/42ic2y/does_anyone_know_where_to_download_the_mnist/
might help.

**Comment by marcoslin** [comment]
Great tip.  Thanks!!!

@waoudi I got my

```
python -m tensorflow.models.image.mnist.convolutional
```
to work by modifying the line 37 of `/usr/local/lib/python2.7/dist-packages/tensorflow/models/image/mnist/convolutional.py` to:

```
SOURCE_URL = 'https://github.com/HIPS/hypergrad/raw/master/data/mnist/'
```

Hopefully http://yann.lecun.com/ will come back online soon.

**Comment by bellaj** [comment]
http://yann.lecun.com/exdb/mnist/ it is back again
