### ISSUE TITLE
Tensorboard broken on latest source

### ISSUE THREAD

**Issue by raghakot** [tensorflow/tensorflow#8888]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Ubuntu 16.04

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
```
-rw-r--r-- 1 root root   556000 Mar  4 15:04 libcudadevrt.a
lrwxrwxrwx 1 root root       16 Mar  4 15:04 libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root root       19 Mar  4 15:04 libcudart.so.8.0 -> libcudart.so.8.0.61
-rwxr-xr-x 1 root root   415432 Mar  4 15:04 libcudart.so.8.0.61
-rw-r--r-- 1 root root   775162 Mar  4 15:04 libcudart_static.a
-rwxr-xr-x 1 root root 84163560 Mar  4 15:06 libcudnn.so
-rwxr-xr-x 1 root root 84163560 Mar  4 15:06 libcudnn.so.5
-rwxr-xr-x 1 root root 84163560 Mar  4 15:06 libcudnn.so.5.1.10
-rw-r--r-- 1 root root 70364814 Mar  4 15:06 libcudnn_static.a
```

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
9738902a46f633c10149d02584484db0b1f2626a

2. The output of `bazel version`
```
Build label: 0.4.5
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Mar 16 12:19:38 2017 (1489666778)
Build timestamp: 1489666778
Build timestamp as int: 1489666778
```

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).
Fails with the following error.
```
Traceback (most recent call last):
  File "/usr/local/bin/tensorboard", line 7, in <module>
    from tensorflow.tensorboard.tensorboard import main
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/tensorboard.py", line 33, in <module>
    from tensorflow.tensorboard.backend import application
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/backend/application.py", line 47, in <module>
    from tensorflow.tensorboard.plugins.projector import projector_plugin
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/plugins/projector/projector_plugin.py", line 30, in <module>
    from tensorflow.contrib.tensorboard.plugins.projector import projector_config_pb2
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/__init__.py", line 59, in <module>
    from tensorflow.contrib import tensorboard
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tensorboard/__init__.py", line 22, in <module>
ragha@ragha-gpu:~/dsb-2017$ tensorboard
Traceback (most recent call last):
  File "/usr/local/bin/tensorboard", line 7, in <module>
    from tensorflow.tensorboard.tensorboard import main
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/tensorboard.py", line 33, in <module>
    from tensorflow.tensorboard.backend import application
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/backend/application.py", line 47, in <module>
    from tensorflow.tensorboard.plugins.projector import projector_plugin
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/plugins/projector/projector_plugin.py", line 30, in <module>
    from tensorflow.contrib.tensorboard.plugins.projector import projector_config_pb2
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/__init__.py", line 59, in <module>
    from tensorflow.contrib import tensorboard
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tensorboard/__init__.py", line 22, in <module>
    from tensorflow.contrib.tensorboard import plugins
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tensorboard/plugins/__init__.py", line 22, in <module>
    from tensorflow.contrib.tensorboard.plugins import projector
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tensorboard/plugins/projector/__init__.py", line 34, in <module>
    from tensorflow.tensorboard.plugins.projector import projector_plugin
ImportError: cannot import name projector_plugin
```

**Comment by xyzzhangfan** [comment]
Hi, I have the same problem. I don't know the reason but I solved by the following step
sudo vim /usr/local/bin/tensorboard
add  

from tensorflow.contrib import bayesflow 

before
 
from tensorflow.tensorboard.tensorboard import main

I noticed if just import bayesflow and then import main, it is fine. But if changing the order, it will have error like you.

**Comment by raghakot** [comment]
Thanks. That does make it run again.

**Comment by aselle** [comment]
@gunan and @jart, could you look into this?

**Comment by jart** [comment]
Possibly cause could be b1d6de28c5600e179d979cc635c812aca955d046 PTAL @dsmilkov.

**Comment by dsmilkov** [comment]
It was related to a circular dependency. I have a fix - will send an internal change for review now.

**Comment by towardthesea** [comment]
Please keep me update about this also! I got exactly the same problem with `tensorboard`.

Thanks

**Comment by aselle** [comment]
Thanks for preparing the fix @dsmilkov.

**Comment by dsmilkov** [comment]
Commit 663eaa05bf1bfa2e84d60b16dc6f4d49cecc8b9a should fix it. Feel free to reopen if the issue still exists.

**Comment by suiyuan2009** [comment]
It's ok now.

**Comment by gunan** [comment]
Please file tensorboard issues under the new tensorboard repository at github.com/tensorflow/tensorboard
