### ISSUE TITLE
Bijectors in contrib.distributions not available

### ISSUE THREAD

**Issue by dustinvtran** [tensorflow/tensorflow#8908]
In 1.1.0rc0 and beyond, all bijectors are moved into a subdirectory in contrib.distributions. This seems to make it unavailable?
```python
ds = tf.contrib.distributions
ds.bijectors
## Traceback (most recent call last):
##   File "<stdin>", line 1, in <module>
## AttributeError: 'module' object has no attribute 'bijectors'

ds.Bijector
## Traceback (most recent call last):
##   File "<stdin>", line 1, in <module>
## AttributeError: 'module' object has no attribute 'Bijector'
```
In my install location of `/Users/dvt/Envs/tf1.1/lib/python2.7/site-packages/tensorflow/contrib/distributions`, it seems like it would be imported, as the following line exists:
```python
from tensorflow.contrib.distributions.python.ops.bijectors import *
```
However, inspecting the `ds` submodule, no bijectors are available.
```python
ds.__dict__.keys()
## ['Deterministic', '__path__', 'QuantizedDistribution', 'softplus_inverse', 'Mixture', 'ExpRelaxedOneHotCategorical', 'ConditionalTransformedDistribution', 'Exponential', 'ConditionalDistribution', '__file__', 'StudentTWithAbsDfSoftplusScale', 'RelaxedOneHotCategorical', 'StudentT', 'ReparameterizationType', 'Categorical', 'MultivariateNormalTriL', 'VectorDeterministic', 'TransformedDistribution', 'Chi2', 'MultivariateNormalDiagPlusLowRank', '_allowed_symbols', 'Gamma', 'normal_conjugates_known_scale_predictive', '__builtins__', 'WishartFull', '__name__', 'Normal', 'ExponentialWithSoftplusRate', 'InverseGamma', 'WishartCholesky', 'Distribution', 'RelaxedBernoulli', 'Bernoulli', 'Beta', 'Binomial', '__doc__', 'BetaWithSoftplusConcentration', 'MultivariateNormalDiagWithSoftplusScale', 'NOT_REPARAMETERIZED', 'BernoulliWithSigmoidProbs', 'Laplace', 'GammaWithSoftplusConcentrationRate', 'Poisson', 'FULLY_REPARAMETERIZED', 'DirichletMultinomial', 'matrix_diag_transform', 'RegisterKL', 'InverseGammaWithSoftplusConcentrationRate', 'Uniform', 'NegativeBinomial', 'Geometric', 'LaplaceWithSoftplusScale', '__package__', 'Dirichlet', 'MultivariateNormalDiag', 'Logistic', 'Chi2WithAbsDf', 'NormalWithSoftplusScale', 'normal_conjugates_known_scale_posterior', 'kl', 'Multinomial', 'OneHotCategorical']
```

**Comment by aselle** [comment]
Please take  look @ebrevdo

**Comment by deoxyribose** [comment]
A workaround:
```
import sys
sys.path.insert(0, tf.__path__[0] + '/contrib/distributions/python/ops')
import bijectors as bijector
```

**Comment by ebrevdo** [comment]
Does this work?

from tensorflow.contrib.distributions.python.ops import bijectors as bijector

**Comment by dustinvtran** [comment]
Yes.

**Comment by ebrevdo** [comment]
Use that for now.  We're shuffling things around to get part of the code
into core and I think some of these issues will be fixed then.
