### ISSUE TITLE
Segmentation fault: 11 (Python3, Conda env, GPU)

### ISSUE THREAD

**Issue by JAStark** [tensorflow/tensorflow#8913]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
I've tried importing numpy or scipy before importing tensorflow, but it does not help from [issue #2034](https://github.com/tensorflow/tensorflow/issues/2034)

### Environment info
Operating System: Max OSX 10.12.3

Installed version of CUDA and cuDNN: 
```
(bigfish) jenniferstark@Jennifers-MacBook-Pro:~/Documents/Repositories/bigfish$ brew cask info cuda
cuda: 8.0.61
https://developer.nvidia.com/cuda-zone
Not installed
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/cuda.rb
==> Name
Nvidia CUDA
==> Artifacts
(bigfish) jenniferstark@Jennifers-MacBook-Pro:~/Documents/Repositories/bigfish$ 
```
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
```
(bigfish) jenniferstark@Jennifers-MacBook-Pro:~/Documents/Repositories/bigfish$ ls -l /Users/jenniferstark/cuda/lib*
total 289880
lrwxr-xr-x  1 jenniferstark  staff    13B Mar  4 19:32 libcuda.1.dylib@ -> libcuda.dylib
-rwxr-xr-x@ 1 jenniferstark  staff    78M Nov  7 02:58 libcudnn.5.dylib*
lrwxr-xr-x@ 1 jenniferstark  staff    16B Nov  7 03:19 libcudnn.dylib@ -> libcudnn.5.dylib
-rw-r--r--@ 1 jenniferstark  staff    63M Nov  7 02:58 libcudnn_static.a
```

If installed from binary pip package, provide:

1. A link to the pip package you installed: 
* https://www.tensorflow.org/versions/master/install/install_mac#NVIDIARequirements  
* Installing for Anaconda, GPU, Python3  inside a conda environment.
using command:
```
/bigfish$ pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/mac/gpu/tensorflow_gpu-1.0.1-py3-none-any.whl
Collecting tensorflow-gpu==1.0.1 from https://storage.googleapis.com/tensorflow/mac/gpu/tensorflow_gpu-1.0.1-py3-none-any.whl
  Downloading https://storage.googleapis.com/tensorflow/mac/gpu/tensorflow_gpu-1.0.1-py3-none-any.whl (89.0MB)
    100% |████████████████████████████████| 89.0MB 9.7kB/s 
Collecting protobuf>=3.1.0 (from tensorflow-gpu==1.0.1)
  Using cached protobuf-3.2.0-py2.py3-none-any.whl
Collecting numpy>=1.11.0 (from tensorflow-gpu==1.0.1)
  Using cached numpy-1.12.1-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting six>=1.10.0 (from tensorflow-gpu==1.0.1)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting wheel>=0.26 (from tensorflow-gpu==1.0.1)
  Using cached wheel-0.29.0-py2.py3-none-any.whl
Collecting setuptools (from protobuf>=3.1.0->tensorflow-gpu==1.0.1)
  Downloading setuptools-34.3.3-py2.py3-none-any.whl (389kB)
    100% |████████████████████████████████| 399kB 1.8MB/s 
Collecting appdirs>=1.4.0 (from setuptools->protobuf>=3.1.0->tensorflow-gpu==1.0.1)
  Using cached appdirs-1.4.3-py2.py3-none-any.whl
Collecting packaging>=16.8 (from setuptools->protobuf>=3.1.0->tensorflow-gpu==1.0.1)
  Using cached packaging-16.8-py2.py3-none-any.whl
Collecting pyparsing (from packaging>=16.8->setuptools->protobuf>=3.1.0->tensorflow-gpu==1.0.1)
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl
Installing collected packages: appdirs, six, pyparsing, packaging, setuptools, protobuf, numpy, wheel, tensorflow-gpu
Successfully installed appdirs-1.4.3 numpy-1.12.1 packaging-16.8 protobuf-3.2.0 pyparsing-2.2.0 setuptools-34.3.3 six-1.10.0 tensorflow-gpu-1.0.1 wheel-0.29.0
```

2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
```
(bigfish) jenniferstark@Jennifers-MacBook-Pro:~/Documents/Repositories/bigfish$ python -c "import tensorflow; print(tensorflow.__version__)"
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.8.0.dylib locally
Segmentation fault: 11
(bigfish) jenniferstark@Jennifers-MacBook-Pro:~/Documents/Repositories/bigfish$ 
```

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
```
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:52:12) 
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.__version__
'1.12.1'
>>> import tensorflow
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.8.0.dylib locally
Segmentation fault: 11
```

### What other attempted solutions have you tried?
* Installing the equivalent version for CPU Python3 version based on [these](https://www.tensorflow.org/versions/master/install/install_mac#NVIDIARequirements  ) instructions worked fine. e.g.: 
```/bigfish$ pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.0.1-py3-none-any.whl
```
Seems like the solution for issue #2034 was for python2 and solved by using an older version of numpy, so not relevant here.

**Comment by JAStark** [comment]
Additional information: 
When running from Spyder, I get this Traceback
```
import keras
Using TensorFlow backend.
Traceback (most recent call last):

  File "<ipython-input-2-c74e2bd4ca71>", line 1, in <module>
    import keras

  File "/Users/jenniferstark/anaconda/envs/bigfish/lib/python3.5/site-packages/keras/__init__.py", line 3, in <module>
    from . import activations

  File "/Users/jenniferstark/anaconda/envs/bigfish/lib/python3.5/site-packages/keras/activations.py", line 3, in <module>
    from . import backend as K

  File "/Users/jenniferstark/anaconda/envs/bigfish/lib/python3.5/site-packages/keras/backend/__init__.py", line 64, in <module>
    from .tensorflow_backend import *

  File "/Users/jenniferstark/anaconda/envs/bigfish/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 1, in <module>
    import tensorflow as tf

  File "/Users/jenniferstark/anaconda/envs/bigfish/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *

  File "/Users/jenniferstark/anaconda/envs/bigfish/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 72, in <module>
    raise ImportError(msg)

ImportError: Traceback (most recent call last):
  File "/Users/jenniferstark/anaconda/envs/bigfish/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/jenniferstark/anaconda/envs/bigfish/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/Users/jenniferstark/anaconda/envs/bigfish/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/Users/jenniferstark/anaconda/envs/bigfish/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/jenniferstark/anaconda/envs/bigfish/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/jenniferstark/anaconda/envs/bigfish/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): Library not loaded: @rpath/libcudart.8.0.dylib
  Referenced from: /Users/jenniferstark/anaconda/envs/bigfish/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so
  Reason: image not found


Failed to load the native TensorFlow runtime.
```

My `.bash_profile` _should_ be right, but I've followed so many different tutorials, that I may have mixed up different ways of setting things up. It's totally possible I've messed up here 😢 

**Path to library in question:**
` /Developer/NVIDIA/CUDA-8.0/lib/libcudart.8.0.dylib ` 

**.bash_profile**
```
#export PATH=/Developer/NVIDIA/CUDA-8.0/bin:$PATH
export PATH=/Developer/NVIDIA/CUDA-8.0/bin${PATH:+:${PATH}}   # from http://docs.nvidia.com/cuda/cuda-installation-guide-mac-os-x/#axzz4aOAsXP00
export DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:$CUDA_HOME/lib:/Developer/NVIDIA/CUDA-8.0/lib"
export DYLD_LIBRARY_PATH=/Developer/NVIDIA/CUDA-8.0/lib${DYLD_LIBRARY_PATH:+:${DYLD_LIBRARY_PATH}}  # from http://docs.nvidia.com/cuda/cuda-installation-guide-mac-os-x/#axzz4aOAsXP00

# NVIDIA cuDNN extracted to ~/
#export CUDA_ROOT=~/cuda
#export LIBRARY_PATH=$CUDA_ROOT/lib:$CUDA_ROOT/lib64:$LIBRARY_PATH


####
# INSTALLING TENSORFLOW-GPU FOR PYTHON 3
# pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/mac/gpu/tensorflow_gpu-1.0.0-py3-none-any.whl
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/Users/jenniferstark/cuda/lib"
export CUDA_HOME=/Users/jenniferstark/local/cuda
```

Thank you in advance!!!

**Comment by gunan** [comment]
In my macbookpro, I expanded my `DYLD_LIBRARY_PATH` as follows to get around this issue.
cant verify further as the macbook I tried this on is now a brick, but I hope this helps:
```
export DYLD_LIBRARY_PATH=/Developer/NVIDIA/CUDA-8.0:/Developer/NVIDIA/CUDA-8.0/lib:/usr/local/cuda:/usr/local/cuda/lib:$DYLD_LIBRARY_PATH
```

We seem to be resolving some libraries with the `lib` in the path and some without.
That seems to be causing the problem.

**Comment by JAStark** [comment]
@gunan thank you so much! My `.bash_profile` now reads
```
export DYLD_LIBRARY_PATH=/Developer/NVIDIA/CUDA-8.0:/Developer/NVIDIA/CUDA-8.0/lib:/usr/local/cuda:/usr/local/cuda/lib:$DYLD_LIBRARY_PATH 

export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/Users/jenniferstark/cuda/lib"
export CUDA_HOME=/Users/jenniferstark/cuda
```
**keras** and **tensorflow** now each import successfully. Running 
```
import tensorflow as tf

# Creates a graph.
a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
c = tf.matmul(a, b)

# Creates a session with log_device_placement set to True.
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))

# Runs the op.
print sess.run(c)
``` 
also _seems_ to do what it should, as far as I can tell. **However**, now when I try to run my keras cnn model, I run into an issue with scipy.linalg, which is called in [Keras' image preprocessing code](https://github.com/fchollet/keras/blob/master/keras/preprocessing/image.py):
```
(bigfish) jenniferstark@Jennifers-MacBook-Pro:~/Documents/Repositories/kaggle/bigfish/src/models$ python train_keras_model.py 
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.8.0.dylib locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.5.dylib locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.8.0.dylib locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.1.dylib locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.8.0.dylib locally
Traceback (most recent call last):
  File "train_keras_model.py", line 5, in <module>
    from keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img
  File "/Users/jenniferstark/anaconda/envs/bigfish/lib/python3.5/site-packages/keras/preprocessing/image.py", line 10, in <module>
    from scipy import linalg
  File "/Users/jenniferstark/anaconda/envs/bigfish/lib/python3.5/site-packages/scipy/linalg/__init__.py", line 175, in <module>
    from .misc import *
  File "/Users/jenniferstark/anaconda/envs/bigfish/lib/python3.5/site-packages/scipy/linalg/misc.py", line 5, in <module>
    from .blas import get_blas_funcs
  File "/Users/jenniferstark/anaconda/envs/bigfish/lib/python3.5/site-packages/scipy/linalg/blas.py", line 155, in <module>
    from scipy.linalg import _fblas
ImportError: dlopen(/Users/jenniferstark/anaconda/envs/bigfish/lib/python3.5/site-packages/scipy/linalg/_fblas.cpython-35m-darwin.so, 2): Library not loaded: /usr/local/lib/libgcc_s.1.dylib
  Referenced from: /Users/jenniferstark/anaconda/envs/bigfish/lib/python3.5/site-packages/scipy/linalg/_fblas.cpython-35m-darwin.so
  Reason: image not found
```
**While** in Spyder, I still get what appears to be the _original_ error:
```
import keras
Using TensorFlow backend.
Traceback (most recent call last):

  File "<ipython-input-4-c74e2bd4ca71>", line 1, in <module>
    import keras

  File "/Users/jenniferstark/anaconda/envs/bigfish/lib/python3.5/site-packages/keras/__init__.py", line 3, in <module>
    from . import activations

  File "/Users/jenniferstark/anaconda/envs/bigfish/lib/python3.5/site-packages/keras/activations.py", line 3, in <module>
    from . import backend as K

  File "/Users/jenniferstark/anaconda/envs/bigfish/lib/python3.5/site-packages/keras/backend/__init__.py", line 64, in <module>
    from .tensorflow_backend import *

  File "/Users/jenniferstark/anaconda/envs/bigfish/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 1, in <module>
    import tensorflow as tf

  File "/Users/jenniferstark/anaconda/envs/bigfish/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *

  File "/Users/jenniferstark/anaconda/envs/bigfish/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 72, in <module>
    raise ImportError(msg)

ImportError: Traceback (most recent call last):
  File "/Users/jenniferstark/anaconda/envs/bigfish/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/jenniferstark/anaconda/envs/bigfish/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/Users/jenniferstark/anaconda/envs/bigfish/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/Users/jenniferstark/anaconda/envs/bigfish/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/jenniferstark/anaconda/envs/bigfish/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/jenniferstark/anaconda/envs/bigfish/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): Library not loaded: @rpath/libcudart.8.0.dylib
  Referenced from: /Users/jenniferstark/anaconda/envs/bigfish/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so
  Reason: image not found


Failed to load the native TensorFlow runtime.
```

So now I am unsure whether this issue is related to TensorFlow, Keras, or Scipy 😟 

Again, thank you in advance 🤖

**Comment by JAStark** [comment]
```
>>> keras.__version__
'2.0.1'
>>> scipy.__version__
'0.19.0'
>>> tensorflow.__version__
'1.0.1'
```

**Comment by JAStark** [comment]
Ok, I downgraded scipy based on [this](http://stackoverflow.com/questions/38854513/conda-python-import-error-image-not-found-in-jupyter-notebook-only)
```
 conda install scipy=0.17.0
```
which seems to have helped (at least in the terminal. Spyder still displays original error).
Now I get memory issues, which I think are unrelated to this original issue, so I'm going to close this issue. 

Thanks 👯‍♂️
