### ISSUE TITLE
Bazel test failure in TF (Assertion errors) on Ubuntu 16.04 on pcc64le architecture

### ISSUE THREAD

**Issue by sandipmgiri** [tensorflow/tensorflow#8945]
###Environment info:
Operating System: Ubuntu 16.04 (ppc64le)

###Installed version of CUDA and cuDNN: cuda & OpenCL disabled and all other features enabled

###Build and test INFO
Built TF (version 1.0.1) successfully on Ubuntu 16.04 and RHEL 7.3. 
Now I am trying to run the bazel tests -  12 tests are failing out of 1044. Please find the attachment for log details.

Thanks!

[C-C++Test Failure  analysis for TF.xlsx](https://github.com/tensorflow/tensorflow/files/892266/C-C.Test.Failure.analysis.for.TF.xlsx)

**Comment by asimshankar** [comment]
The architecture being used is not one that we currently support. For example, some of the tests are failing with `py-cpuinfo currently only works on X86 and some ARM CPUs`. Community contributions in keeping TensorFlow chugging along with ppc64le are welcome!

**Comment by gunan** [comment]
the tests that mention tolerance are failing because the test tolerance bounds are too tight.
They may need the bounds to be loosened a little and they will pass.

py-cpuinfo exactly as @asimshankar described.

The above is as much information as I can provide on the failures based on very little information you have on the spreadsheet. If you read the full logs, you should be able to debug the issues in more detail.

**Comment by sandipmgiri** [comment]
I was looking for the way to adjust the bounds as needed, but didn't get much information about this. Could you please guide me about how to bounds the tolerance to loosened ?  

Please find the attached log for more details.

[ternary_ops_test_cpu.log.txt](https://github.com/tensorflow/tensorflow/files/904680/ternary_ops_test_cpu.log.txt)

**Comment by sandipmgiri** [comment]
Now `py-cpuinfo` community made it work on `ppc64le` (added ppc64le support for `py-cpuinfo`). now that `Exception: py-cpuinfo currently only works on X86 and some ARM CPUs ` error is gone, but I'm getting some another error :

```
$ bazel test -c opt//tensorflow/tools/test:rnn_op_benchmark
-----------------------------------------------------------------------------
..
----------------------------------------------------------------------

Ran 2 tests in 0.008s

OK
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/tools/test/rnn_op_benchmark.runfiles/org_tensorflow/tensorflow/tools/test/run_and_gather_logs.py", line 99, in <module>
    app.run()
  File "/root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/tools/test/rnn_op_benchmark.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/tools/test/rnn_op_benchmark.runfiles/org_tensorflow/tensorflow/tools/test/run_and_gather_logs.py", line 78, in main
    test_args)
  File "/root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/tools/test/rnn_op_benchmark.runfiles/org_tensorflow/tensorflow/tools/test/run_and_gather_logs_lib.py", line 145, in run_and_gather_logs
    log_files=log_files), mangled_test_name)
  File "/root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/tools/test/rnn_op_benchmark.runfiles/org_tensorflow/tensorflow/tools/test/run_and_gather_logs_lib.py", line 76, in process_test_logs
    system_info_lib.gather_machine_configuration())
  File "/root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/tools/test/rnn_op_benchmark.runfiles/org_tensorflow/tensorflow/tools/test/system_info_lib.py", line 44, in gather_machine_configuration
    config.cpu_info.CopyFrom(gather_cpu_info())
  File "/root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/tools/test/rnn_op_benchmark.runfiles/org_tensorflow/tensorflow/tools/test/system_info_lib.py", line 98, in gather_cpu_info
    l2_cache_size = re.match(r'(\d+)', str(info['l2_cache_size']))
KeyError: 'l2_cache_size'
```
 I would like to understand comments/suggestions on this.Thanks!

**Comment by sandipmgiri** [comment]
Hi @gunan,  as you said "need tolerance bounds to be loosened a little and test will pass" 

For me 4 tests are passing after adjusting the tolerance and the details are as follows :

1.  `//tensorflow/compiler/tests:pooling_ops_test_cpu `
    Need to change tolerance from rtol=1e-05 to rtol=1 

2. ` //tensorflow/python/kernel_tests:summary_image_op_test   `    
    Need to change tolerance from rtol=1e-06 to rtol=1 

3.  `//tensorflow/python/kernel_tests:linalg_grad_test   `   
    To pass this test need to add 0.01 in rtol i.e rtol=tol+0.01 (initially rtol=0.16 and now 0.17)
   
4.  `//tensorflow/contrib/image:image_ops_test`           
  Here we need to change comparison function for ppc64le i.e. from assertAllEqual  to assertAllClose 
  (as we can not pass tolerance argument to assertAllEqual function) 
  Once changed the comparison function pass rtol = 1e-1 and test will execute successfully

Above tests are passed successfully on X86 without changing the tolerance . But to pass these tests on ppc64le we need to adjust the tolerance like we did above.

So as per my point of view - to implement above changes, we should add the power specific condition for these tests : 
e.g. For test ` //tensorflow/python/kernel_tests:linalg_grad_test` need following action : 

`self.assertAllClose(theoretical, numerical, atol=tol, rtol=tol)`

It could be changed to :

```
if platform.machine() == "ppc64le":
     self.assertAllClose(theoretical, numerical, atol=tol+0.01, rtol=tol)
else 
    self.assertAllClose(theoretical, numerical, atol=tol, rtol=tol)
```

Please provide your comments/suggestions on this.Thanks!

**Comment by gunan** [comment]
I am worried about 1e-2 or 1e-1 tolerance, which seems too high to me.
It is possible there is a bug with the code on ppc64?

CC @Nayana-ibm who also is working on getting TF to build and run on ppc64 machines. (Big endian in their case, but maybe there is some information that could be shared.)

**Comment by Nayana-ibm** [comment]
We had not observed above test failure on Ubuntu distribution. 
On RHEL distribution, we had observed `//tensorflow/python/kernel_tests:summary_image_op_test `failure however test was passing  on re-running test on high memory vm.
Please note we had executed tests for Tensorflow v0.10.0

**Comment by gunan** [comment]
As we do not have access to ppc64le machines, we will not be able to officially support the architecture ourselves.
Looking at the test results you had, it looks like there is a problem in the code that cause the issues.
We welcome any contributions to fix the issues. I will mark this as contributions welcome, and leave it open.

**Comment by sandipmgiri** [comment]
I reran the above test cases on high end vm, but still same test failures were observed (Looks like failures related to TF v1.0.1 and ppc64le platform).

@gunan, as you said "It is possible there is a bug with the code on ppc64?"
I have done some investigation around these test failures :  

1. //tensorflow/compiler/tests:pooling_ops_test_cpu
     The test expects **avg_pool** o/p as [ 7. , 8. , 9. , 11.5, 12.5, 13.5] but gets [ 7. , 8. , 9. , 11.5, 9. , 13.5] (4th entry is different)

     The error looks like :
```
  F.
  ======================================================================
  FAIL: testAvgPoolSamePadding (__main__.PoolingTest)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/compiler/tests/pooling_ops_test_cpu.runfiles/org_tensorflow/tensorflow/compiler/tests/pooling_ops_test.py", line 288, in testAvgPoolSamePadding
    expected=expected_output)
  File "/root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/compiler/tests/pooling_ops_test_cpu.runfiles/org_tensorflow/tensorflow/compiler/tests/pooling_ops_test.py", line 125, in _VerifyValues
    data_format, expected)
  File "/root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/compiler/tests/pooling_ops_test_cpu.runfiles/org_tensorflow/tensorflow/compiler/tests/pooling_ops_test.py", line 108, in _VerifyOneTest
    self.assertAllClose(expected, actual.flatten(), rtol=1e-5, atol=1e-6)
  File "/root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/compiler/tests/pooling_ops_test_cpu.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 485, in assertAllClose
    np.testing.assert_allclose(a, b, rtol=rtol, atol=atol)
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 1411, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 796, in assert_array_compare
    raise AssertionError(msg)

    AssertionError:
    Not equal to tolerance rtol=1e-05, atol=1e-06
    (mismatch 16.6666666667%)
    x: array([ 7. , 8. , 9. , 11.5, 12.5, 13.5])
    y: array([ 7. , 8. , 9. , 11.5, 9. , 13.5], dtype=float32)
    ----------------------------------------------------------------------
   Ran 2 tests in 0.368s

   FAILED (failures=1)
   not close where =  (array([4]),)
   not close lhs =  [ 12.5]
   not close rhs =  [ 9.]
   not close dif =  [ 3.5]
   not close tol =  [  9.10000017e-05]
   dtype = float64, shape = (6,)

```

2. //tensorflow/python/kernel_tests:summary_image_op_test

     This test is failing due to **summary.image** function returning incorrect value (0 vs expected 1) 

     The error looks like :
  
```
     F..
     ======================================================================
     FAIL: testImageSummary (__main__.SummaryImageOpTest)
     ----------------------------------------------------------------------
     Traceback (most recent call last):
       File "/root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/python/kernel_tests/summary_image_op_test.runfiles/org_tensorflow/tensorflow/python/kernel_tests/summary_image_op_test.py", line 83, in testImageSummary
         self.assertAllClose(image, adjusted[0])
       File "/root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/python/kernel_tests/summary_image_op_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 485, in assertAllClose
         np.testing.assert_allclose(a, b, rtol=rtol, atol=atol)
       File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 1411, in assert_allclose
         verbose=verbose, header=header, equal_nan=equal_nan)
       File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 796, in assert_array_compare
         raise AssertionError(msg)

         AssertionError:
         Not equal to tolerance rtol=1e-06, atol=1e-06

        (mismatch 2.85714285714%)

     Expected                            Actual

       ([[[[ ....                                  ([[[[ ....

        [[ 136.],                                [[ 136.], 
         [ 106.],                                [ 106.],
         [ 240.],                                [ 240.],
         [ 125.],                                [ 125.],                              
         [  47.],                                [  47.],
         [ 105.],                                [ 105.],
         [   1.]],                               [   0.]],

        .....]]]                                      .....]]]
         ----------------------------------------------------------------------
         Ran 3 tests in 0.113s

        FAILED (failures=1)
        not close where =  (array([3]), array([6]), array([0]))
        not close lhs =  [0]
        not close rhs =  [ 1.]
        not close dif =  [ 1.]
        not close tol =  [  1.99999999e-06]
        dtype = uint8, shape = (5, 7, 1)

```

3. //tensorflow/python/kernel_tests:linalg_grad_test
  
	This test is failing due to  **compute_gradient**  function returning incorrect value (-0.27654076 vs expected -0.09766237) 


	 The error looks like :
```
         ..F.........
	  ======================================================================
	  FAIL: test_MatrixSolveLsGradient_float32_10_10_1e-06 (__main__.MatrixBinaryFunctorGradientTest)
	  ----------------------------------------------------------------------
	  Traceback (most recent call last):
	  File "/root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/python/kernel_tests/linalg_grad_test.runfiles/org_tensorflow/tensorflow/python/kernel_tests/linalg_grad_test.py", line 129, in Test
    	    self.assertAllClose(theoretical, numerical, atol=tol, rtol=tol)
	  File "/root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/python/kernel_tests/linalg_grad_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 485, in assertAllClose
	    np.testing.assert_allclose(a, b, rtol=rtol, atol=atol)
	  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 1411, in assert_allclose
    	    verbose=verbose, header=header, equal_nan=equal_nan)
	  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 796, in assert_array_compare
	    raise AssertionError(msg)
  
          AssertionError:
	  Not equal to tolerance rtol=0.16, atol=0.16

	  (mismatch 0.01%)
	   x: array([[-0.27454 ,  0.232044,  0.238228, ..., -0.034112, -0.373461, 0.033982],
                         [-0.781968,  3.879236, -0.101676, ..., -2.040482, -3.555872,...
 	   y: array([[-0.27545 ,  0.234431,  0.2381  , ..., -0.040039, -0.382814, 0.036853],
          	         [-0.782201,  3.879493, -0.102113, ..., -2.039877, -3.555654,...
            ----------------------------------------------------------------------
           Ran 12 tests in 1.460s

          FAILED (failures=1)
          not close where =  (array([40]), array([33]))
          not close lhs =  [-0.27654076]
          not close rhs =  [-0.09766237]
          not close dif =  [ 0.1788784]
          not close tol =  [ 0.17562598]
          dtype = float32, shape = (100, 100)
```

4. //tensorflow/contrib/image:image_ops_test

	This test is failing due to **rotate** function returning incorrect value (32 vs expected 33)
	Error looks like :
```
        ======================================================================
	FAIL: test_rotate_even (__main__.ImageOpsTestGpu)
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/image/image_ops_test.runfiles/org_tensorflow/tensorflow/contrib/image/python/kernel_tests/image_ops_test.py", line 75, in test_rotate_even
	    [1, 7, 13, 19, 25, 31], [0, 6, 12, 18, 24, 30]]])
	  File "/root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/image/image_ops_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 535, in assertAllEqual
	    np.testing.assert_array_equal(a, b)
	  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 871, in assert_array_equal
	    verbose=verbose, header='Arrays are not equal')
	  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 796, in assert_array_compare
	    raise AssertionError(msg)

	AssertionError:
	Arrays are not equal
	(mismatch 1.85185185185%)


	Expected =                                                                  Actual = 

	[[[0,  1,  2,  3,  4,  5],                                             [[[ 0  1  2  3  4  5]  
	  [6,  7,  8,  9,  10, 11],                                             [ 6  7  8  9 10 11]
	  [12, 13, 14, 15, 16, 17],                                             [12 13 14 15 16 17]
	  [18, 19, 20, 21, 22, 23],                                             [18 19 20 21 22 23]
	  [24, 25, 26, 27, 28, 29],                                             [24 25 26 27 28 29] 
	  [30, 31, 32, 33, 34, 35]],                                            [30 31 32 33 34 35]]
	 [[0,  3,  4,  11, 17, 0],                                              [[ 0  3  4 11 17  0]
	  [2,  3,  9,  16, 23, 23],                                             [ 2  3  9 16 23 23]
	  [1,  8,  15, 21, 22, 29],                                             [ 1  8 15 21 22 29]
	  [6,  13, 20, 21, 27, 34],                                             [  6 13 20 20 27 34]   
	 [12, 18, 19, 26, "33", 33],                                            [12 18 19 26 "32" 33]
	  [0,  18, 24, 31, 32, 0]],                                             [ 0 18 24 31 32  0]]         
	 [[5,  11, 17, 23, 29, 35],                                             [[ 5 11 17 23 29 35] 
	  [4,  10, 16, 22, 28, 34],                                             [ 4 10 16 22 28 34]
	  [3,  9,  15, 21, 27, 33],                                             [ 3  9 15 21 27 33]
	  [2,  8,  14, 20, 26, 32],                                             [ 2  8 14 20 26 32]
	  [1,  7,  13, 19, 25, 31],                                             [ 1  7 13 19 25 31]
	  [0,  6,  12, 18, 24, 30]]])                                           [ 0  6 12 18 24 30]]]
          ----------------------------------------------------------------------
         Ran 8 tests in 31.264s

        FAILED (failures=2)
       not equal where =  (array([1, 1]), array([3, 4]), array([3, 4]))
       not equal lhs =  [20 32]
       not equal rhs =  [21 33]
       not equal where =  (array([1, 1]), array([3, 4]), array([3, 4]))
       not equal lhs =  [20 32]
       not equal rhs =  [21 33]

```

In above tests checking 2 arrays are equal or not (expected and actual) each array has 100+ entries, out of which only one entry mismatching and test fails.
Here very difficult to pinpoint the issue on power platform as all entries matching except one. For now I think better solution would be just change the tolerance as required (like I mentioned in previous comment). Please provide your view on this.Thanks!

**Comment by gunan** [comment]
My concern is, we have very numerical differences.
It is possible TF is just not working on ppc64le, and it needs to be fixed.
If we suppress these warnings, sure you might have all tests passing, but people using TF may run into worse issues getting wrong outputs, models not converging, etc.

IMO these numerical differences are too large to ignore, and will cause issues using TF on ppc platform. Therefore, I am against changing tolerances fro `1e-6` to `10`. You can just create a fork of TensorFlow and make those changes there. But I think you will eventually need to debug and get to the bottom of these differences, because they look like real bugs with TF on ppc64le to me.

**Comment by sandipmgiri** [comment]
Thanks @gunan , for your suggestions and pointers. 

Now I am debugging more into these failures and trying to find the root cause.

**Comment by sandipmgiri** [comment]
This GitHub issue was created for 12 test failures , now all got resolved for me. Please find the details below (currently I am working on TF1.3.1 ):

**1     //tensorflow/compiler/tests:binary_ops_test_cpu** 

This test was failing with the error : `nan vs expected inf.`
I ran sample code using inputs equivalent to ones used in the test case and using tensorflow "realdiv" API :
	
```
	>>> import tensorflow as tf
	>>> import numpy as np
	>>> sess = tf.Session()
	>>> dtype = np.float32
	>>> a =  np.array([3, 3, -1.5, -8, 44], dtype=dtype)
	>>> b = np.array([2, -2, 7, -4, 0], dtype=dtype)
	>>> pb = tf.placeholder(b.dtype, b.shape, name="b")
	>>> pa = tf.placeholder(a.dtype, a.shape, name="a")
	>>> output = tf.realdiv(pa, pb)
	>>> result = sess.run(output, {pa: a, pb: b})
	>>> print(result)
	[ 1.5        -1.5        -0.21428572    2.     inf]
	
```

This is printing results as expected by the test case.

**2   //tensorflow/contrib/image:image_ops_test**

This test was failing on RHEL7.3 vm. Now this machine upgraded to RHEL7.4.
I reran "image_ops_test"  test on new OS and test passed successfully without any changes.

**3	//tensorflow/tools/test:cast_op_benchmark
4	//tensorflow/tools/test:rnn_op_benchmark**

Submitted code changes to fix these 2 tests.
Relevant commit : https://github.com/tensorflow/tensorflow/commit/69ba4d3d49bd5775131ae7f00830a41f478dbbf5

( Note - Changes are available in TF1.3.1 )

**5      //tensorflow/python/kernel_tests:sparse_matmul_op_test
6	//tensorflow/core/kernels:sparse_matmul_op_test_gpu**

These 2 tests fixed in PR https://github.com/tensorflow/tensorflow/pull/12138


( Note - Changes are not available in TF1.3.1 )

**7	//tensorflow/compiler/tests:pooling_ops_test_cpu
8	//tensorflow/python/kernel_tests:linalg_grad_test
9	//tensorflow/compiler/tests:ternary_ops_test_cpu**

These 3 tests are passing in TF1.3.1 (without any changes).

**10 //tensorflow/python/kernel_tests:summary_image_op_test test fixed in PR** https://github.com/tensorflow/tensorflow/pull/15147

( Note - Changes are not available in TF1.3.1 )

**11	//tensorflow/core:platform_profile_utils_cpu_utils_test
12	//tensorflow/python/kernel_tests:cast_op_test**

These 2 tests fixed in PR  https://github.com/tensorflow/tensorflow/pull/10522
( Note - Changes are available in TF1.3.1 )

Thanks !!!
