### ISSUE TITLE
Tensorflow results in Segmenation fault 

### ISSUE THREAD

**Issue by sachinprabhu007** [tensorflow/tensorflow#8946]
Hello

I have installed tensorflow gpu version with python2.7. It results in following error once i define Session. I am unable to train my model. Please assist

```
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library lib                                                                                                         cublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library lib                                                                                                         cudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library lib                                                                                                         cufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library lib                                                                                                         cuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library lib                                                                                                         curand.so locally
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:925] successful NUMA node rea                                                                                                         d from SysFS had negative value (-1), but there must be at least one NUMA node, so r                                                                                                         eturning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties                                                                                                         :
name: Tesla K40c
major: 3 minor: 5 memoryClockRate (GHz) 0.745
pciBusID 0000:02:00.0
Total memory: 11.17GiB
Free memory: 11.10GiB
W tensorflow/stream_executor/cuda/cuda_driver.cc:572] creating context when one is c                                                                                                         urrently active; existing: 0x248a6e0
Segmentation fault (core dumped)

```

**Comment by asimshankar** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case.   We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by sachinprabhu007** [comment]
**System details** : ubuntu 14.04 x86_64 
**Tensorflow version:** 0.10.0

I installed it as binary 
i.e i followed this - > 

```
# Ubuntu/Linux 64-bit, GPU enabled, Python 2.7
# Requires CUDA toolkit 7.5 and CuDNN v5. For other versions, see "Install from sources" below.
$ export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.10.0-cp27-none-linux_x86_64.whl

 sudo pip install --upgrade $TF_BINARY_URL

```
I just found out its due to **Session()** as i tried basic program i.e 

`>>> import tensorflow as tf
>>> hello = tf.constant('Hello, TensorFlow!')
>>> sess = tf.Session()`

 
I am using tensorflow cpu version as of now since gpu dint work. I am able to train my model with the same. But I would really appreciate if you could please help me with gpu version 


Thanks!

**Comment by asimshankar** [comment]
Seems like you're using a very old version of TensorFlow.

Could you try with the latest version (1.0)?

**Comment by sachinprabhu007** [comment]
Tried with Tensoflow Version 1.0 

Results in following error as i execute commands in python shell : 

Will be waiting for reply. 

Thanks 
```
Python 2.7.6 (default, Oct 26 2016, 20:30:19)
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.7.5 locally
>>> hello = tf.constant('hi,tensorflow')
>>> sess = tf.Session()
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:910] successful NUMA node                                                                                                              read from SysFS had negative value (-1), but there must be at least one NUMA no                                                                                                             de, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with prop                                                                                                             erties:
name: Tesla K40c
major: 3 minor: 5 memoryClockRate (GHz) 0.745
pciBusID 0000:02:00.0
Total memory: 11.17GiB
Free memory: 11.10GiB
W tensorflow/stream_executor/cuda/cuda_driver.cc:590] creating context when one                                                                                                              is currently active; existing: 0x2e0fe90
E tensorflow/core/common_runtime/direct_session.cc:137] Internal: failed initial                                                                                                             izing StreamExecutor for CUDA device ordinal 1: Internal: failed call to cuDevic                                                                                                             ePrimaryCtxRetain: CUDA_ERROR_INVALID_DEVICE
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.                                                                                                             py", line 1187, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.                                                                                                             py", line 552, in __init__
    self._session = tf_session.TF_NewDeprecatedSession(opts, status)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/error                                                                                                             s_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InternalError: Failed to create session.

```

**Comment by gunan** [comment]
This error looks suspicious:
```
W tensorflow/stream_executor/cuda/cuda_driver.cc:590] creating context when one  is currently active; existing: 0x2e0fe90
E tensorflow/core/common_runtime/direct_session.cc:137] Internal: failed initializing StreamExecutor for CUDA device ordinal 1: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_INVALID_DEVICE
```
Is there any chance you are running two TF programs at the same time?

You can find more similar issues here:
https://github.com/NVIDIA/nvidia-docker/issues/262
https://github.com/tensorflow/tensorflow/issues/152

**Comment by michaelisard** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
