### ISSUE TITLE
import error in ipython but not in python

### ISSUE THREAD

**Issue by erag996** [tensorflow/tensorflow#9041]
-*I have installed TensorFlow installed with virtualenv Linux(Ubuntu 16.10) with this codes*
```shell
 sudo apt-get install python-pip python-dev python-virtualenv
(tensorflow)$ pip install --upgrade tensorflow      # for Python 2.7
```
- *TensorFlow version 1.0.1
- *Command to reproduce the error after installing the module through pip*
```python
import tensorflow as tf
```

### Logs from ipython
```ipython
Python 2.7.12+ (default, Sep 17 2016, 12:08:02) 
Type "copyright", "credits" or "license" for more information.

IPython 5.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import tensorflow as tf
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-41389fad42b5> in <module>()
----> 1 import tensorflow as tf

/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py in <module>()
     22 
     23 # pylint: disable=wildcard-import
---> 24 from tensorflow.python import *
     25 # pylint: enable=wildcard-import
     26 

/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py in <module>()
     70 for some common reasons and solutions.  Include the entire stack trace
     71 above this error message when asking for help.""" % traceback.format_exc()
---> 72   raise ImportError(msg)
     73 
     74 # Protocol buffers

ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by asimshankar** [comment]
This suggests some configuration issue with your virtualenv and ipython. The error you're getting suggests that it's trying to load CUDA, which means it is using the `tensorflow-gpu` pip package while your `pip install` command suggested it was installing the CPU-only version of TensorFlow.

Since this appears to be an issue with your virtualenv/ipython setup and not with TensorFlow, I'm going to close this out. You might also want to take a look at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/install/install_linux.md#common-installation-problems

Hope that helps.

**Comment by erag996** [comment]
Thanks @asimshankar this was helpfull and my problem is solved
