### ISSUE TITLE
Any idea why "failed to create cublas handle"?

### ISSUE THREAD

**Issue by 714586886** [tensorflow/tensorflow#9077]
When I run a demo of Faster R-CNN,I meet an error,I have spend a whole week on it,but not work:

Env:
- *OS*:Ubuntu16.04
- *TensorFlow version*:1.0.1
- *TensorFlow installed from (source or binary)?*:binary
- *CUDA/cuDNN version*:CUDA8.0 cuDNN5.1
- *GPU Model and Memory*: GTX 950 2G
- *Exact command to reproduce*:python ./tools/demo.py --model model_path

See https://github.com/smallcorgi/Faster-RCNN_TF

The error as follows:

W tensorflow/core/common_runtime/bfc_allocator.cc:217] Ran out of memory trying to allocate 791.02MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W tensorflow/core/common_runtime/bfc_allocator.cc:217] Ran out of memory trying to allocate 1.08GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W tensorflow/core/common_runtime/bfc_allocator.cc:217] Ran out of memory trying to allocate 1.08GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
E tensorflow/stream_executor/cuda/cuda_blas.cc:372] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
W tensorflow/stream_executor/stream.cc:1390] attempting to perform BLAS operation using StreamExecutor without BLAS support
Traceback (most recent call last):
  File "./tools/demo.py", line 126, in <module>
    _, _= im_detect(sess, net, im)
  File "/home/tangshouquan/Faster-RCNN_TF/tools/../lib/fast_rcnn/test.py", line 179, in im_detect
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Blas SGEMM launch failed : m=1369, n=18, k=512
	 [[Node: rpn_cls_score/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](rpn_conv/3x3/rpn_conv/3x3, rpn_cls_score/weights/read)]]
	 [[Node: cls_score/cls_score/_109 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_357_cls_score/cls_score", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'rpn_cls_score/Conv2D', defined at:
  File "./tools/demo.py", line 114, in <module>
    net = get_network(args.demo_net)
  File "/home/tangshouquan/Faster-RCNN_TF/tools/../lib/networks/factory.py", line 28, in get_network
    return networks.VGGnet_test()
  File "/home/tangshouquan/Faster-RCNN_TF/tools/../lib/networks/VGGnet_test.py", line 16, in __init__
    self.setup()
  File "/home/tangshouquan/Faster-RCNN_TF/tools/../lib/networks/VGGnet_test.py", line 40, in setup
    .conv(1,1,len(anchor_scales)*3*2,1,1,padding='VALID',relu = False,name='rpn_cls_score'))
  File "/home/tangshouquan/Faster-RCNN_TF/tools/../lib/networks/network.py", line 25, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
  File "/home/tangshouquan/Faster-RCNN_TF/tools/../lib/networks/network.py", line 109, in conv
    conv = convolve(input, kernel)
  File "/home/tangshouquan/Faster-RCNN_TF/tools/../lib/networks/network.py", line 100, in <lambda>
    convolve = lambda i, k: tf.nn.conv2d(i, k, [1, s_h, s_w, 1], padding=padding)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 396, in conv2d
    data_format=data_format, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

InternalError (see above for traceback): Blas SGEMM launch failed : m=1369, n=18, k=512
	 [[Node: rpn_cls_score/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](rpn_conv/3x3/rpn_conv/3x3, rpn_cls_score/weights/read)]]
	 [[Node: cls_score/cls_score/_109 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_357_cls_score/cls_score", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

**Comment by asimshankar** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  **Make sure you also include the exact command if possible to produce  the output included in your test case**.   We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by 714586886** [comment]
@asimshankar Thanks

**Comment by 714586886** [comment]
@aselle help me，please...I changed tensorflow from 1.0.1 to 0.12.1 and reinstall CUDA,but not work.

**Comment by jart** [comment]
That question might be more appropriate for [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow).

**Comment by kleinash** [comment]
Was this ever solved? Please see my issue: https://github.com/tensorflow/models/issues/2857
