### ISSUE TITLE
hi everyone! im having this issue when trying to import tensorflow, i've tried all the techniques i've found on stackoverflow and here at GH but they still don't work

### ISSUE THREAD

**Issue by StormArnaud** [tensorflow/tensorflow#9156]
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AM
D64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", l
ine 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 906, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: Le module spécifié est introuvable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\python35\lib\site-packages\tensorflow\python\__init__.py", line 66, i
n <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", l
ine 21, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", l
ine 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow')
  File "C:\python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\python35\lib\site-packages\tensorflow\__init__.py", line 24, in <modu
le>
    from tensorflow.python import *
  File "C:\python35\lib\site-packages\tensorflow\python\__init__.py", line 72, i
n <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", l
ine 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 906, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: Le module spécifié est introuvable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\python35\lib\site-packages\tensorflow\python\__init__.py", line 66, i
n <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", l
ine 21, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", l
ine 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow')
  File "C:\python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow'

Failed to load the native TensorFlow runtime.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_st
arted/os_setup.md#import_error

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
>>>

**Comment by jart** [comment]
This might be a better question for [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow).
