### ISSUE TITLE
Unable to use ci_build to build tensorflow

### ISSUE THREAD

**Issue by nqbao** [tensorflow/tensorflow#9178]
### You must complete this information or else your issue will be closed
- *Have I written custom code (as opposed to using a stock example script provided in TensorFlow)?*: No
- *TensorFlow installed from (source or binary)?*: Source
- *TensorFlow version*: `master` and  `f8dce81aeaff40dc78d398741854ad8766806f91`
- *Bazel version (if compiling from source)*: 0.4.5 
- *CUDA/cuDNN version*: N/A
- *GPU Model and Memory*: N/A
- *Exact command to reproduce*:

`tensorflow/tools/ci_build/ci_build.sh CPU bazel test //tensorflow/...`

Note: make sure you run with a clean state machine

### Describe the problem clearly

I'm trying to use ci_build tool to build tensorflow from source, but I am always got the error at step `/install/install_buildifier.sh`

```
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
____Loading package: buildifier
____Loading package: @bazel_tools//tools/cpp
____Loading package: @bazel_tools//tools/jdk
____Loading package: @local_config_xcode//
____Loading package: @local_jdk//
____Loading package: @local_config_cc//
____Loading complete.  Analyzing...
____Loading package:
____Loading package: @bazel_tools//tools/genrule
____Downloading https://storage.googleapis.com/golang/go1.7.4.linux-amd64.tar.gz: 4,184,939 bytes
____Downloading https://storage.googleapis.com/golang/go1.7.4.linux-amd64.tar.gz: 8,690,539 bytes
____Downloading https://storage.googleapis.com/golang/go1.7.4.linux-amd64.tar.gz: 14,736,235 bytes
____Downloading https://storage.googleapis.com/golang/go1.7.4.linux-amd64.tar.gz: 19,537,920 bytes
____Downloading https://storage.googleapis.com/golang/go1.7.4.linux-amd64.tar.gz: 24,485,888 bytes
____Downloading https://storage.googleapis.com/golang/go1.7.4.linux-amd64.tar.gz: 29,597,696 bytes
____Downloading https://storage.googleapis.com/golang/go1.7.4.linux-amd64.tar.gz: 34,791,424 bytes
____Downloading https://storage.googleapis.com/golang/go1.7.4.linux-amd64.tar.gz: 39,903,232 bytes
____Downloading https://storage.googleapis.com/golang/go1.7.4.linux-amd64.tar.gz: 45,064,192 bytes
____Downloading https://storage.googleapis.com/golang/go1.7.4.linux-amd64.tar.gz: 50,339,840 bytes
____Downloading https://storage.googleapis.com/golang/go1.7.4.linux-amd64.tar.gz: 55,648,256 bytes
____Downloading https://storage.googleapis.com/golang/go1.7.4.linux-amd64.tar.gz: 61,497,344 bytes
____Downloading https://storage.googleapis.com/golang/go1.7.4.linux-amd64.tar.gz: 67,166,208 bytes
____Downloading https://storage.googleapis.com/golang/go1.7.4.linux-amd64.tar.gz: 73,048,064 bytes
____Downloading https://storage.googleapis.com/golang/go1.7.4.linux-amd64.tar.gz: 78,733,312 bytes
____Loading package: @io_bazel_rules_go_toolchain//
ERROR: /buildifier/build/BUILD.bazel:4:1: no such package '@org_golang_x_tools//cmd/goyacc': no such package '@io_bazel_rules_go_repository_tools//': Traceback (most recent call last):
    File "/root/.cache/bazel/_bazel_root/972a279007c925820266f3ac7b1d6afd/external/io_bazel_rules_go/go/private/go_repositories.bzl", line 85
        _fetch_repository_tools_deps(ctx, goroot, gopath)
    File "/root/.cache/bazel/_bazel_root/972a279007c925820266f3ac7b1d6afd/external/io_bazel_rules_go/go/private/go_repositories.bzl", line 54, in _fetch_repository_tools_deps
        ctx.download_and_extract('%s/archive/%s.zip' % (dep.repo,...), <4 more arguments>)
java.io.IOException: Prefix buildifier-4190564903f61ddc94bcfda3dc2cdd32d4b330e5 was given, but not found in the zip and referenced by '//build:parse.y.go_yacc'.
ERROR: Analysis of target '//buildifier:buildifier' failed; build aborted.
____Elapsed time: 10.455s
```

I did google around and may be this is root cause https://github.com/bazelbuild/rules_go/issues/361

**Comment by asimshankar** [comment]
To build TensorFlow from sources, please follow [the procedure outlined in the website](https://www.tensorflow.org/install/install_sources).

The scripts in the `ci_build` directory are specific to the machine setup on the continuous integration Jenkins worker machines (ci.tensorflow.org). 

Since using the ci_build scripts for purposes other than the continuous integration setup is not a supported use case, I'd like to close this issue out.

**Comment by nqbao** [comment]
`ci_build` script is very helpful to me. By the way, I found the root cause of the problem: buildifier is renamed to buildtools. So the ci will fail if you run with from the beginning. I upgrade to the right version and it works now.

```
--- a/tensorflow/tools/ci_build/install/install_buildifier.sh
+++ b/tensorflow/tools/ci_build/install/install_buildifier.sh
@@ -17,7 +17,7 @@
 set -e
 BUILDIFIER_DIR="buildifier"
 mkdir ${BUILDIFIER_DIR}
-curl -Ls https://github.com/bazelbuild/buildifier/archive/0.4.3.tar.gz | \
+curl -Ls https://github.com/bazelbuild/buildtools/archive/0.4.5.tar.gz | \
     tar -C "${BUILDIFIER_DIR}" --strip-components=1 -xz
 pushd ${BUILDIFIER_DIR}
```
Can i open a PR for this?
