### ISSUE TITLE
tensorflow 1.0.1 + Python3 - TypeError: string argument expected, got 'NoneType'

### ISSUE THREAD

**Issue by puneet336** [tensorflow/tensorflow#9184]
Hi all,
I am trying to install tensorflow 1.0.1 from source on RHEL 6.6 with CUDA 7.5 & CUDNN 5.0.5.
I am repeatedly getting following error-

$ pip3 install ./tensorflow-1.0.1-cp36-cp36m-linux_x86_64.whl --root="$INSTALL_ROOT_DIR" 
Processing ./tensorflow-1.0.1-cp36-cp36m-linux_x86_64.whl
Requirement already satisfied: protobuf>=3.1.0 in /home/apps/PYTHONPACKAGES/3.6.0/ucs4/gnu/493/PROTOBUF/3.2.0/gnu/lib/python3.6/site-packages/protobuf-3.2.0-py3.6.egg (from tensorflow==1.0.1)
Exception:
Traceback (most recent call last):
  File "/home/soft/PYTHON/3.6.0/ucs4/gnu/447/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/soft/PYTHON/3.6.0/ucs4/gnu/447/lib/python3.6/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/home/soft/PYTHON/3.6.0/ucs4/gnu/447/lib/python3.6/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/soft/PYTHON/3.6.0/ucs4/gnu/447/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/soft/PYTHON/3.6.0/ucs4/gnu/447/lib/python3.6/site-packages/pip/req/req_set.py", line 666, in _prepare_file
    check_dist_requires_python(dist)
  File "/home/soft/PYTHON/3.6.0/ucs4/gnu/447/lib/python3.6/site-packages/pip/utils/packaging.py", line 48, in check_dist_requires_python
    feed_parser.feed(metadata)
  File "/home/soft/PYTHON/3.6.0/ucs4/gnu/447/lib/python3.6/email/feedparser.py", line 175, in feed
    self._input.push(data)
  File "/home/soft/PYTHON/3.6.0/ucs4/gnu/447/lib/python3.6/email/feedparser.py", line 103, in push
    self._partial.write(data)
TypeError: string argument expected, got 'NoneType'

Please let me know if any further information is required from my side to debug this issue.
Though, I  have previously compiled tf-1.0.1 using python 2.7, but currently, I have to stick to python3 for this installation.

**Comment by asimshankar** [comment]
As requested in the new issue template, please include the exact command if possible to produce  the output included in your test case.   We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by puneet336** [comment]
Hi,
I have shared the complete command and the error log. 
Do i need to share the build log for "tensorflow-1.0.1-cp36-cp36m-linux_x86_64.whl" ?

**Comment by drpngx** [comment]
Unfortunately we don't support redhat 6 or python 3.5. We support centos/redhat 7 and python 3.5 only.

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
