### ISSUE TITLE
spectral ops make freeze_graph tool trigger "No OpKernel was registered ..." error

### ISSUE THREAD

**Issue by Androbin** [tensorflow/tensorflow#9240]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04.2 LTS
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: v1.1.0-rc1-253-gd5a9356 1.1.0-rc1
- **Bazel version (if compiling from source)**: 0.4.5
- **CUDA/cuDNN version**: 8.0/5.1
- **GPU model and memory**: NVIDIA Geforce GTX 750 Ti
- **Exact command to reproduce**: bazel-bin/tensorflow/python/tools/freeze_graph --input_graph=model.pb --input_checkpoint=model.ckpt --output_graph=frozen_model.pb --output_node_names=y_conv

### Describe the problem
The [`freeze_graph`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/freeze_graph.py) tool malfunctions when processing a graph containing [spectral ops](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/api_guides/python/spectral_ops.md).
Without spectral ops, everything works just fine, all the way to inference.

Might this have something to do with the fact that spectral ops don't have a CPU implementation yet?
And if so, why would this lead to this error?

### Source code / logs
```
Traceback (most recent call last):
  File "bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 1136, in _do_call
    return fn(*args)
  File "bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 1114, in _run_fn
    self._extend_graph()
  File "bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 1163, in _extend_graph
    self._session, graph_def.SerializeToString(), status)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'RFFT' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

	 [[Node: rfft = RFFT[](framesig, Const_1)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 218, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 150, in main
    FLAGS.variable_names_blacklist)
  File "bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 128, in freeze_graph
    saver.restore(sess, input_checkpoint)
  File "bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 1545, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 786, in run
    run_metadata_ptr)
  File "bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 994, in _run
    feed_dict_string, options, run_metadata)
  File "bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 1129, in _do_run
    target_list, options, run_metadata)
  File "bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 1149, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'RFFT' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

	 [[Node: rfft = RFFT[](framesig, Const_1)]]

Caused by op 'rfft', defined at:
  File "bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 218, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 150, in main
    FLAGS.variable_names_blacklist)
  File "bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 103, in freeze_graph
    _ = importer.import_graph_def(input_graph_def, name="")
  File "bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/framework/importer.py", line 308, in import_graph_def
    op_def=op_def)
  File "bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'RFFT' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

	 [[Node: rfft = RFFT[](framesig, Const_1)]]
```

**Comment by asimshankar** [comment]
You are correct, this error is because of the lack of a CPU kernel for these ops. The error message is:

```
 No OpKernel was registered to support Op 'RFFT' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>
```

@petewarden : Is `freeze_graph.py` meant to work for GPU devices?

which means that there are "no registered kernels" for the "CPU" device.

**Comment by Androbin** [comment]
@asimshankar Why would `freeze_graph` need to run a `Session` anyway?
Shouldn't it just rewrite the graph to replace `Variable`s by respective `Constant`s?

**Comment by Androbin** [comment]
Keeping on hold until #9029 is merged (with RFFT support)

**Comment by Androbin** [comment]
#9029 got merged, closing
