### ISSUE TITLE
tf.conv2d ValueError

### ISSUE THREAD

**Issue by xXDavidHuangXx** [tensorflow/tensorflow#9243]
I believe the following is a bug

ValueError: Shape must be rank 4 but is rank 1 for 'Conv2D' (op: 'Conv2D') with input shapes: [1,1,64,256], [4].

Full Traceback:
Traceback (most recent call last):
  File "chat.py", line 17, in <module>
    conv1 = tf.nn.conv2d(input=embed_a,filter=[1,8,256,128],strides=[1,1,8,256],padding="VALID")
  File "/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 396, in conv2d
    data_format=data_format, name=name)
  File "/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2329, in create_op
    set_shapes_for_outputs(ret)
  File "/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1717, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1667, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Shape must be rank 4 but is rank 1 for 'Conv2D' (op: 'Conv2D') with input shapes: [1,1,64,256], [4].

I believe that a tensor of shape [1,1,64,256] should be Rank 4 not Rank 1.

**Comment by fangjufa** [comment]
@xXDavidHuangXx  is your problem solved?Now I bumped into the same one.Pls tell me your solution if you solved, thanks.

**Comment by ilkarman** [comment]
I have same issue

> ValueError: Shape must be rank 4 but is rank 1 for 'Conv2D' (op: 'Conv2D') with input shapes: [?,28,28,1], [4].

For

```
x = tf.placeholder(tf.float32, shape=[None, 28, 28, 1], name="x")  
conv1 = tf.nn.conv2d(x, filter=[5, 5, 1, 20], strides=[1, 1, 1, 1], padding='VALID')
```

**Comment by NickTGraham** [comment]
@ilkarman I had the same issue. I found the error a bit confusing. The problem wasn't with the input but with the filter. I had to create a variable instead of just passing in a list.

Here is what I did, based on the example [here](https://github.com/tensorflow/models/blob/master/tutorials/image/cifar10/cifar10.py ): 
```
filter = tf.get_variable('weights', [5, 5, 1, 64], initializer=tf.truncated_normal_initializer(stddev=5e-2, dtype=tf.float32), dtype=tf.float32)
conv = tf.nn.conv2d(x, filter, [1,1,1,1], padding = "SAME")
```

**Comment by Spandyie** [comment]
Has this error been resolved , I am getting same error with MNIST data set

**Comment by Teslaxhub** [comment]
tf.nn.conv2d           : is MUCH complicated, say,the filter need to be specified first
tf.layers.Conv2D       : recomended
tf.layers.conv2d       : IS DEPRECATED，Use tf.keras.layers.Conv2D instead.
tf.keras.layers.Conv2D : recomended
