### ISSUE TITLE
Issue with OpenCL Supported Bazel Compilation of Tensorflow 1.1 (From Source) on UBUNTU 14.04.3

### ISSUE THREAD

**Issue by rahasayantan** [tensorflow/tensorflow#9246]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: UBUNTU 14.04.3-->Trusty
- **TensorFlow installed from (source or binary)**:Source
- **TensorFlow version (use command below)**:1.1.0 (Used git to clone repo)
- **Bazel version (if compiling from source)**:0.4.5
- **CUDA/cuDNN version**:NA
- **OPENCL Version**:
			  Platform Version:				 OpenCL 2.0 AMD-APP (1800.11)
			  Platform Name:				 AMD Accelerated Parallel Processing
			  Platform Vendor:				 Advanced Micro Devices, Inc.
			  Platform Extensions:				 cl_khr_icd cl_amd_event_callback cl_amd_offline_devices 
- **GPU model and memory**:
			  Platform Name:				 AMD Accelerated Parallel Processing
			Number of devices:				 2
			  Device Type:					 CL_DEVICE_TYPE_GPU
			  Board name:					 AMD Radeon (TM) R5 M335
                          Memory: 4096 MB 

- **Exact command to reproduce**:
		bazel build --config opt --config=sycl //tensorflow/tools/pip_package:build_pip_package

- ** G++/GCC version**:
	g++ (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

I have compiled CPP programs, they work fine.

-- ** Python**: I am using Anaconda distribution Python for 2.7.2. (Anaconda - 2.4.3)
### Describe the problem

I am trying to compile Tensorflow with OPENCL support (experimental) on UBUNTU 14.04.3. I have an AMD GPU. I have followed the instructions from this site: https://github.com/benoitsteiner/tensorflow-opencl/blob/master/tensorflow/g3doc/get_started/os_setup.md#installing-from-sources
Everything works ok till the bazel compile step. When I try to compile with the following command: bazel build --config opt --config=sycl //tensorflow/tools/pip_package:build_pip_package
I get the following error:
#################################################
..............................
WARNING: /home/sayantan/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:exporter': Use SavedModel Builder instead.
WARNING: /home/sayantan/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:gc': Use SavedModel instead.
INFO: Found 1 target...
ERROR: /home/sayantan/tensorflow/tensorflow/core/BUILD:1292:1: C++ compilation of rule '//tensorflow/core:lib_hash_crc32c_accelerate_internal' failed: computecpp failed: error executing command external/local_config_sycl/crosstool/computecpp -Wall -msse3 -g0 -O2 -DNDEBUG -g0 '-std=c++11' -MD -MF ... (remaining 27 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
/usr/share/bash-completion/completions/g++: 41: /usr/share/bash-completion/completions/g++: Syntax error: "(" unexpected (expecting "fi")
Traceback (most recent call last):
  File "external/local_config_sycl/crosstool/computecpp", line 88, in <module>
    sys.exit(main())
  File "external/local_config_sycl/crosstool/computecpp", line 59, in main
    return subprocess.call([CPU_CXX_COMPILER] + compiler_flags)
  File "/home/sayantan/anaconda2/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/home/sayantan/anaconda2/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/home/sayantan/anaconda2/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 146.513s, Critical Path: 3.91s
#################################################

When I execute with more verbosity, I get teh following error:(bazel build --config opt --config=sycl //tensorflow/tools/pip_package:build_pip_package --verbose_failures)
#################################################
WARNING: /home/sayantan/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:exporter': Use SavedModel Builder instead.
WARNING: /home/sayantan/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:gc': Use SavedModel instead.
INFO: Found 1 target...
ERROR: /home/sayantan/.cache/bazel/_bazel_sayantan/6f05f78a1e215999d72e42c1e87a8c1d/external/protobuf/BUILD:241:1: C++ compilation of rule '@protobuf//:js_embed' failed: computecpp failed: error executing command 
  (cd /home/sayantan/.cache/bazel/_bazel_sayantan/6f05f78a1e215999d72e42c1e87a8c1d/execroot/tensorflow && \
  exec env - \
    LD_LIBRARY_PATH=/usr/lib32:/usr/local/computecpp/lib \
    PATH=/home/sayantan/bin:/home/sayantan/anaconda2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/sayantan/bin \
  external/local_config_sycl/crosstool/computecpp -Wall -msse3 -g0 -O2 -DNDEBUG -g0 '-std=c++11' -MD -MF bazel-out/host/bin/external/protobuf/_objs/js_embed/external/protobuf/src/google/protobuf/compiler/js/embed.d '-frandom-seed=bazel-out/host/bin/external/protobuf/_objs/js_embed/external/protobuf/src/google/protobuf/compiler/js/embed.o' -iquote external/protobuf -iquote bazel-out/host/genfiles/external/protobuf -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/protobuf/src/google/protobuf/compiler/js/embed.cc -o bazel-out/host/bin/external/protobuf/_objs/js_embed/external/protobuf/src/google/protobuf/compiler/js/embed.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
/usr/share/bash-completion/completions/g++: 41: /usr/share/bash-completion/completions/g++: Syntax error: "(" unexpected (expecting "fi")
Traceback (most recent call last):
  File "external/local_config_sycl/crosstool/computecpp", line 88, in <module>
    sys.exit(main())
  File "external/local_config_sycl/crosstool/computecpp", line 59, in main
    return subprocess.call([CPU_CXX_COMPILER] + compiler_flags)
  File "/home/sayantan/anaconda2/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/home/sayantan/anaconda2/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/home/sayantan/anaconda2/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 10.148s, Critical Path: 8.76s

################################################

Please let me know if there are any fixes or if I can do something to get round this issue.
Thanks and regards
Sayantan

**Comment by rahasayantan** [comment]
Solved issue by upgrading g++ to 4.9
