### ISSUE TITLE
Android demo crashes on Android 6 devices

### ISSUE THREAD

**Issue by thagikura** [tensorflow/tensorflow#925]
When I tried to run the Android demo, it instantly crashed when I opened the app.
The CameraConnectionFragment doesn't handle the runtime permission for camera.

The code needs to handle the runtime permission.

```
01-29 17:23:43.694 15962-15962/org.tensorflow.demo E/AndroidRuntime: FATAL EXCEPTION: main
Process: org.tensorflow.demo, PID: 15962
java.lang.SecurityException
    at android.os.BinderProxy.transactNative(Native Method)
    at android.os.BinderProxy.transact(Binder.java:503)
    at android.hardware.ICameraService$Stub$Proxy.connectDevice(ICameraService.java:364)
    at java.lang.reflect.Method.invoke(Native Method)
    at android.hardware.camera2.utils.Decorator.invoke(Decorator.java:80)
    at java.lang.reflect.Proxy.invoke(Proxy.java:393)
    at $Proxy0.connectDevice(Unknown Source)
    at android.hardware.camera2.CameraManager.openCameraDeviceUserAsync(CameraManager.java:321)
    at android.hardware.camera2.CameraManager.openCamera(CameraManager.java:457)
    at org.tensorflow.demo.CameraConnectionFragment.openCamera(CameraConnectionFragment.java:380)
    at org.tensorflow.demo.CameraConnectionFragment.access$000(CameraConnectionFragment.java:63)
    at org.tensorflow.demo.CameraConnectionFragment$1.onSurfaceTextureAvailable(CameraConnectionFragment.java:96)
    at android.view.TextureView.getHardwareLayer(TextureView.java:368)
    at android.view.View.updateDisplayListIfDirty(View.java:15151)
    at android.view.View.draw(View.java:15948)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
    at android.view.View.updateDisplayListIfDirty(View.java:15169)
    at android.view.View.draw(View.java:15948)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
    at android.view.View.draw(View.java:16181)
    at android.view.View.updateDisplayListIfDirty(View.java:15174)
    at android.view.View.draw(View.java:15948)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
    at android.view.View.updateDisplayListIfDirty(View.java:15169)
    at android.view.View.draw(View.java:15948)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
    at android.view.View.updateDisplayListIfDirty(View.java:15169)
    at android.view.View.draw(View.java:15948)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
    at android.view.View.draw(View.java:16181)
    at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2690)
    at android.view.View.updateDisplayListIfDirty(View.java:15174)
    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:2615)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2434)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2067)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
    at android.view.Choreographer.doCallbacks(Choreographer.java:670)
    at android.view.Choreographer.doFrame(Choreographer.java:606)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by thagikura** [comment]
Fixed by #926, but the demo app still crashes due to another error.
I'll close this issue and file another one.
