### ISSUE TITLE
InvalidArgumentError when running word2vec_basic.py

### ISSUE THREAD

**Issue by Strideradu** [tensorflow/tensorflow#9257]
### System information
- Just running the word2vec_basic.py
- Windows 10 64bir
- b'unknown' 0.12.head (I installed 0.12 first then uninstalled old version and install new version to 1.0)
- GTX 760 4GB

### Describe the problem

```
Invalid argument: indices[0] = 4575361316406883040 is not in [0, 50000)
         [[Node: nce_loss/embedding_lookup = Gather[Tindices=DT_INT64, Tparams=DT_FLOAT, _class=["loc:@Variable_1"], validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Variable_1/read, nce_loss/concat)]]
W c:\tensorflow\tensorflow\tensorflow\core\framework\op_kernel.cc:975] Invalid argument: indices[0] = 4575361316406883040 is not in [0, 50000)
         [[Node: nce_loss/embedding_lookup = Gather[Tindices=DT_INT64, Tparams=DT_FLOAT, _class=["loc:@Variable_1"], validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Variable_1/read, nce_loss/concat)]]
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1021, in _do_call
    return fn(*args)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1003, in _run_fn
    status, run_metadata)
  File "C:\Anaconda3\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0] = 4575361316406883040 is not in [0, 50000)
         [[Node: nce_loss/embedding_lookup = Gather[Tindices=DT_INT64, Tparams=DT_FLOAT, _class=["loc:@Variable_1"], validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Variable_1/read, nce_loss/concat)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\word2vec_basic.py", line 232, in <module>
    _, loss_val = session.run([optimizer, loss], feed_dict=feed_dict)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 766, in run
    run_metadata_ptr)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0] = 4575361316406883040 is not in [0, 50000)
         [[Node: nce_loss/embedding_lookup = Gather[Tindices=DT_INT64, Tparams=DT_FLOAT, _class=["loc:@Variable_1"], validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Variable_1/read, nce_loss/concat)]]

Caused by op 'nce_loss/embedding_lookup', defined at:
  File ".\word2vec_basic.py", line 199, in <module>
    num_classes=vocabulary_size))
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\nn_impl.py", line 1044, in nce_loss
    name=name)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\nn_impl.py", line 891, in _compute_sampled_logits
    weights, all_ids, partition_strategy=partition_strategy)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\embedding_ops.py", line 111, in embedding_lookup
    validate_indices=validate_indices)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 1293, in gather
    validate_indices=validate_indices, name=name)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2371, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1258, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): indices[0] = 4575361316406883040 is not in [0, 50000)
         [[Node: nce_loss/embedding_lookup = Gather[Tindices=DT_INT64, Tparams=DT_FLOAT, _class=["loc:@Variable_1"], validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Variable_1/read, nce_loss/concat)]]
```
It seems that somehow indices[num] point to a very large number that not in the vocabulary vector?

I found there are also two cases in https://github.com/dennybritz/cnn-text-classification-tf/issues/17 but cannot find the solution

**Comment by Strideradu** [comment]
It seems due to the version conflict, solved

**Comment by zhangwbnn** [comment]
@Strideradu  what did you mean "It seems due to the version conflict"?, I faced with this problem too, how did you solve it? thanks!

**Comment by Strideradu** [comment]
@zhangwbnn you may want to check the version of Tensorflow. That time I thought I updated my 0.12 to 1.0 but later I found seems not and I uninstalled old tensorflow and reinstalled again

**Comment by hadikazemi** [comment]
word2vec_basic.py works on 1.0.0-rc2 but not 1.2.0-rc1:

> Caused by op u'nce_loss/embedding_lookup', defined at:
  File "/home/hadi/Projects/NLP/word2vec.py", line 171, in <module>
    num_classes=vocabulary_size))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_impl.py", line 1151, in nce_loss
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_impl.py", line 970, in _compute_sampled_logits
    weights, all_ids, partition_strategy=partition_strategy)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/embedding_ops.py", line 122, in embedding_lookup
    return maybe_normalize(_do_gather(params[0], ids, name=name))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/embedding_ops.py", line 42, in _do_gather
    return array_ops.gather(params, ids, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 1179, in gather
    validate_indices=validate_indices, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2511, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1267, in __init__
    self._traceback = _extract_stack()
InvalidArgumentError (see above for traceback): indices[0] = -1 is not in [0, 50000)
	 [[Node: nce_loss/embedding_lookup = Gather[Tindices=DT_INT64, Tparams=DT_FLOAT, _class=["loc:@Variable_1"], validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Variable_1/read, nce_loss/concat)]]

**Comment by marc88** [comment]
I get the following error too after running an embedding layer as;

`Embedding(23624, 50, input_length=5, trainable=False)`

> InvalidArgumentError (see above for traceback): **indices[6,4]** = 23624 is not in [0, 23624)
> 	 [[Node: embedding_1/embedding_lookup = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@embedding_1/embeddings"], validate_indices=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](embedding_1/embeddings/read, embedding_1/Cast)]]

Each datapoint here is a number(index). Upon checking indices[6,4] I found the following

```
print(ar_train_data[6,4])
5088
```
The training stops towards the end of the first epoch with this error.
am amazed! 5088 is no where out of range for [0, 23624).  Can anyone suggest what could be the issue here?
Please suggest if additional code snippets are required for clarity.

Keras version - 2.2.4
tensorflow version: 1.5.0

Regards
