### ISSUE TITLE
Tutorial has error: Recurrent Neural Networks

### ISSUE THREAD

**Issue by kevinashaw** [tensorflow/tensorflow#9294]
Tutorial URL: https://www.tensorflow.org/tutorials/recurrent
I'm going through the tutorial listed above and I think there is a mistake in the very first code example:
```
lstm = tf.contrib.rnn.BasicLSTMCell(lstm_size)
# Initial state of the LSTM memory.
state = tf.zeros([batch_size, lstm.state_size])
```
An error is reported for the third line:
```
ValueError: setting an array element with a sequence.
```
If one prints the `lstm.state_size` object (where say, lstm_size = 50) one finds:
```
LSTMStateTuple(c=50, h=50)
```
I'm guessing this should be:
```
lstm = tf.contrib.rnn.BasicLSTMCell(lstm_size)
# Initial state of the LSTM memory.
state = tf.zeros([batch_size, lstm_size])
```
But frankly there are numerous other errors in this tutorial as well, so I'm not sure.  I will continue to report them as I find them.
Version: tensorflow_gpu-1.0.1-cp27-none-linux_x86_64.whl
Running on Ubuntu 14.04

**Comment by drpngx** [comment]
Thanks for reporting! It would be great if you could update us on additional errors as you follow along.

@ebrevdo FYI

**Comment by kevinashaw** [comment]
Will do.  The API change for TF1.0.1, especially for the RNN classes, has caused confusion and there is a real shortage of working RNN code samples.  The vast majority of the code examples on StackOverflow are from mid-2016 and they no longer work with the new API.  Thanks.

**Comment by ebrevdo** [comment]
Indeed, the tutorial has a one line warning:

"The basic pseudocode is as follows:"

we should really just highlight that in red above each code example.

And at the top we should link to the real code:

https://github.com/tensorflow/models/tree/master/tutorials/rnn/ptb

that code looks to be up to date.

**Comment by Engineero** [comment]
I just ran across the same problem. My concern is that `state = tf.zeros([batch_size, lstm_size])` might not capture what needs to be captured. In the current API, the `lstm_state` is a tuple of `(c, h)` or `(memory, output)`, which should have size `[lstm_size, 2]`. Would this then require us to write `state = tf.zeros([batch_size, lstm_size, 2])`?

I am working through this as I type this. So far I have not quite hit on the solution.

**Comment by kevinashaw** [comment]
@ebrevdo : Thank you for your help!
I saw the "pseudocode" warning, but those two lines of code look like they should be self-contained.  Also, regardless of highlighting in red, the pseudocode should be solid starting point for working code.  There is so little working TF RNN code after the API change that this one document becomes a critical resource.
I can also confirm that the repo [link](https://github.com/tensorflow/models) in the tutorial does not link to the file that you [referenced](https://github.com/tensorflow/models/tree/master/tutorials/rnn/ptb).  Thank you for providing.  I will note that that code, as a tutorial example, is somewhat opaque.

**Comment by kevinashaw** [comment]
@ebrevdo @drpngx : Would you like me to report additional errors on this thread, or on a new thread?

**Comment by drpngx** [comment]
I wonder if you could just edit the doc and send a PR when done

**Comment by kevinashaw** [comment]
I would be glad to, but I'm not clear on what 'truth' is at this point.
Here is the second code sample:
```
# Placeholder for the inputs in a given iteration.
num_steps  = 20
batch_size = 1000
lstm_size  = 50
words = tf.placeholder(tf.int32, [batch_size, num_steps])

lstm = tf.contrib.rnn.BasicLSTMCell(lstm_size)
# Initial state of the LSTM memory.
initial_state = state = tf.zeros([batch_size, lstm.state_size])

for i in range(num_steps):
    # The value of state is updated after processing each batch of words.
    output, state = lstm(words[:, i], state)
```
Which yields: `ValueError: setting an array element with a sequence.` on the `tf.zeros` line.
I'm working on finding an executable replacement, but haven't found it yet.  I'm not clear on what the proper shape for the `state` should be.

**Comment by kevinashaw** [comment]
Following @Engineero's recommendation, I can use `tf.zeros([batch_size, lstm_size, 2])` and I then get an error on the last line (`lstm()`) with:
```
TypeError: 'Tensor' object is not iterable.
```
Which is opaque to me, since it does not look like we are iterating on a Tensor.

**Comment by Engineero** [comment]
@kevinashaw I think it needs to be `state = lstm.zero_state(batch_size, dtype=tf.float32)` or some other value for `dtype`, depending on the problem. This should create a zeroed-out initial state tensor based on the network's state parameters.

**Comment by kevinashaw** [comment]
@Engineero : Thanks.
I have updated the test code, but it still fails with the same error `not iterable` message:
```
# Placeholder for the inputs in a given iteration.
num_steps  = 20
batch_size = 1000
lstm_size  = 50
words = tf.placeholder(tf.int32, [batch_size, num_steps])

lstm = tf.contrib.rnn.BasicLSTMCell(lstm_size)
# Initial state of the LSTM memory.
initial_state = state = tf.zeros(batch_size, dtype=tf.float32)

for i in range(num_steps):
    # The value of state is updated after processing each batch of words.
    output, state = lstm(words[:, i], state)
```

**Comment by kevinashaw** [comment]
Not to be too nit-picky about the tutorial, but the example code uses `state_is_tuple=False` which is now deprecated.  So the sample code should probably be updated.  I, myself, am still in clear on how this changes the code, but I hope to work it out soon.

**Comment by Engineero** [comment]
@kevinashaw that is not what I wrote. You are still using `tf.zeros(...)`. Should be `lstm.zero_state(...)` I think.

**Comment by kevinashaw** [comment]
My bad.  Sorry.  Retrying...

**Comment by kevinashaw** [comment]
With the new state initialization line:
```
initial_state = state = lstm.zero_state(batch_size, dtype=tf.float32)
```
The new error is thrown on the last line: 
```
ValueError: linear is expecting 2D arguments: [TensorShape([Dimension(1000)]), 
    TensorShape([Dimension(1000), Dimension(50)])]
```
Here is the full code sample:
```
# Placeholder for the inputs in a given iteration.
num_steps  = 20
batch_size = 1000
lstm_size  = 50
words = tf.placeholder(tf.int32, [batch_size, num_steps])

lstm = tf.contrib.rnn.BasicLSTMCell(lstm_size)
# Initial state of the LSTM memory.
initial_state = state = lstm.zero_state(batch_size, dtype=tf.float32)

for i in range(num_steps):
    # The value of state is updated after processing each batch of words.
    output, state = lstm(words[:, i], state)
```
If one does the following to determine the shape and type of `state`:
```
print(tf.shape(state))
print(state)
```
the following is printed:
```
Tensor("Shape:0", shape=(3,), dtype=int32)
LSTMStateTuple(c=<tf.Tensor 'zeros_11:0' shape=(1000, 50) dtype=float32>, h=<tf.Tensor 'zeros_12:0' shape=(1000, 50) dtype=float32>)
```

**Comment by Engineero** [comment]
@kevinashaw that's where I am now too. It seems like we are not presenting arguments to the `__call__` method of `lstm` correctly. I am working a different problem, but same issue.

**Comment by kevinashaw** [comment]
@Engineero : Here is a dumb question that you may be able to help with.  If TF is capable of auto-unrolling LSTMs, then why do we need to use the `for` loop (in the sample above) to feed in the words one at a time?  I've never understood this.

**Comment by ebrevdo** [comment]
You don't.  We should really change the tutorial to use tf.nn.dynamic_rnn
-- which handles most of this for you.

**Comment by Engineero** [comment]
@kevinashaw I am not positive, but I think by doing that we are taking control of how many unrolling steps are performed. TF will still handle the actual unrolling when we execute our training process, but I think making it explicit gives us more control. Or maybe that line is necessary in order to tell TF to do unrolling in the first place? Again, I am not sure.

**Comment by kevinashaw** [comment]
It seems the unrolling should only be necessary for the training process.  At inference-time, it should function on a sample-by-sample basis.  But I guess it is just a memory vs speed trade-off question.

**Comment by kevinashaw** [comment]
@ebrevdo : could we get a short snippet of sample code using `tf.nn.dynamic_rnn`?  :-)

**Comment by ebrevdo** [comment]
While this tutorial is just a little outdated (they still point to RNNCells
in tf.nn.rnn_cell instead of tf.contrib.rnn), a lot of the examples are
still very good:

http://www.wildml.com/2016/08/rnns-in-tensorflow-a-practical-guide-and-undocumented-features/

**Comment by Engineero** [comment]
@ebrevdo this may be a separate issue, but on that tutorial that you linked, do you have any idea how one should replace `tf.contrib.learn.run_n(...)` calls? It gives a depreciation warning with the following:

> Instructions for updating:
> graph_actions.py will be deleted. Use tf.train.* utilities instead. You can use learn/estimators/estimator.py as an example.

The file this sends you to does not seem to be very helpful.

Thanks!

**Comment by ebrevdo** [comment]
@martinwicke what's the replacement for tf.contrib.learn.run_n?

**Comment by martinwicke** [comment]
We have none. It was never used after initial experimentation, so we decided to scrap it altogether. You can get the same behavior using `tf.contrib.training.train`, if you need feeds, with a Hook to add the feeds.

**Comment by Engineero** [comment]
For the record, I found [this gist][1] to be helpful. He also has [a blog][2] where he talks about some of the undocumented features of an older version of TensorFlow. You still have to change out `tf.nn.rnn_cell` for `tf.contrib.rnn`, but this helped me get something going.

That said, I am now having an issue where my network is not updating at all. I train it for several epochs and get the exact same results every time.

[1]: https://gist.github.com/danijar/61f9226f7ea498abce36187ddaf51ed5
[2]: http://www.wildml.com/2016/08/rnns-in-tensorflow-a-practical-guide-and-undocumented-features/

**Comment by kevinashaw** [comment]
@Engineero : Thanks!

**Comment by kevinashaw** [comment]
Following the discussion in #9699, I've at least found a solution to the initial_state problem.  It would probably make sense to reference it in the new tutorial/documentation.   The problem with the initial_state is not that `zero_state` produces incorrect results :
```
initial_state = lstm_cells.zero_state(batch_size, tf.float32)
```
Its that the batch_size value is a constant.  For the training data, the size of the batch will *always* match the batch_size.  But for Testing data it usually never will.  Testing is done on a much large set, or atleast a set that has a size that varies from the batch_size.  Hence, for testing data, the `initial_state` from the test data will still have a size of `batch_size` but the test data itself will not.
The solution is surprisingly simple, just let batch_size vary according to the data set brought in:
```
batch_size_var  = tf.shape(Xin)[0]
initial_state = lstm_cells.zero_state(batch_size_var, tf.float32) 
```
Where Xin is the data input tensor.  Now `initial_state` will always match the size of the data set.

**Comment by ebrevdo** [comment]
Right. tf.nn.dynamic_rnn will call zero_state for you with the right value
of you pass in just the dtype argument and not an initial state.

**Comment by kevinashaw** [comment]
Thanks!  The documentation regarding that feature is somewhat thin for tf.nn.dynamic_rnn.

**Comment by lancerts** [comment]
@martinwicke , for https://github.com/dennybritz/tf-rnn/blob/master/sequence_example.ipynb  as mentioned eariler changed  tf.contrib.learn.run_n(...) to tf.contrib.training.train in the code, but it seems running into the inifinite loop.

**Comment by martinwicke** [comment]
Yes, you'll have to limit the number of steps using a [`StepCounterHook`](https://www.tensorflow.org/api_docs/python/tf/train/StopAtStepHook) or make sure your input function throws an appropriate exception after the training data is depleted (either `StopIteration` or `OutOfRangeError`).

**Comment by Jennydariska** [comment]
sorry, I would like to ask something. I got the same error when I was training my NeuronNetwork, when I wanted to have the prediction. this is the code ` # 6.  Definition del model
def model_fn1(features, labels, mode=None, params=None, config=None):
    # 6.1. Connect the first hidden layer to the # (features["x"]) with relu activation
    hidden = tf.layers.dense(features["x"], 10,
                             activation=tf.nn.relu)

    # 6.2. Connect the second hidden layer to the first hidden with elu activation
    hidden1 = tf.layers.dense(hidden, 10, activation=tf.nn.relu)

    # 6.3. Connect output to the the second hidden layer without activation
    out_y = tf.layers.dense(hidden1, 22)
    out_y = tf.reshape(out_y, [-1, 22])

    # 6.4. Provide an estimator spec for `ModeKeys.PREDICT`.
    if mode == tf.estimator.ModeKeys.PREDICT:
        return tf.estimator.EstimatorSpec(
            mode=mode,
            predictions=dict(out_y))

    # 6.5. Calculate loss using mean squared error and another approach
    loss = tf.losses.mean_squared_error(labels, out_y)

    # 6.6. Training sub-graph
    optimizer = tf.train.GradientDescentOptimizer(
        learning_rate=0.01)
    train_op = optimizer.minimize(
        loss=loss, global_step=tf.train.get_global_step())

    # 6.7 Calculate root mean squared error as additional eval metric
    eval_metric_ops = {
        "rmse": tf.metrics.root_mean_squared_error(
            tf.cast(labels, tf.float64), out_y)
    }

    # 6.8. Provide an estimator spec for `ModeKeys.EVAL` and `ModeKeys.TRAIN` modes.
    return tf.estimator.EstimatorSpec(
        mode=mode,
        loss=loss,
        train_op=train_op,
        eval_metric_ops=eval_metric_ops)


# 7. Creation of an estimator
estimator1 = tf.estimator.Estimator(model_fn=model_fn1, params=None,
                                    model_dir='/home/jennydariska/targetDirectory/project_1/project1/test/')

# 8. Running of our model
with tf.Session() as session:

    input_fn = tf.estimator.inputs.numpy_input_fn(x={"x": x_train}, y=y_train,
                                                  shuffle=True, num_epochs=None)

    train_input_fn = tf.estimator.inputs.numpy_input_fn(x={"x": x_train}, y=y_train,
                                                        num_epochs=None, shuffle=False)

    eval_input_fn = tf.estimator.inputs.numpy_input_fn(x={"x": x_eval}, y=y_eval,
                                                       num_epochs=1, shuffle=False)
    # 8.1 Training of the estimator
    estimator1.train(input_fn=input_fn, steps=5000)

    # 8.2 Evaluation of how well our model did.
    train_metrics = estimator1.evaluate(input_fn=train_input_fn, steps=500)
    eval_metrics = estimator1.evaluate(input_fn=eval_input_fn)
    print("train metrics: %r" % train_metrics)
    print("eval metrics: %r" % eval_metrics)
    print("Loss: %s" % eval_metrics["loss"])

    # 8.3 Prediction for the news samples
    predict_input_fn = tf.estimator.inputs.numpy_input_fn(
        x={"x": new_samples}, num_epochs=1,
        shuffle=False)

    predictions = estimator1.predict(input_fn=predict_input_fn)
    print(predictions)

    for i in enumerate(predictions):
        print("Prediction %s: " % i )
` and this is the output: train metrics: {'loss': 0.49825639, 'global_step': 65001, 'rmse': 0.70587265}
eval metrics: {'loss': 0.056399819, 'global_step': 65001, 'rmse': 0.24770115}
Loss: 0.0563998
<generator object predict at 0x7fea697b3b40>
Traceback (most recent call last):
  File "/home/jennydariska/Mytest/project1/finale3.py", line 141, in <module>
    for i in enumerate(predictions):
  File "/home/jennydariska/targetDirectory/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 339, in predict
    model_fn_lib.ModeKeys.PREDICT)
  File "/home/jennydariska/targetDirectory/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 614, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/jennydariska/Mytest/project1/finale3.py", line 83, in model_fn1
    predictions=dict(out_y))
  File "/home/jennydariska/targetDirectory/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 476, in __iter__
    raise TypeError("'Tensor' object is not iterable.")
TypeError: 'Tensor' object is not iterable.

Process finished with exit code 1
. what should i do please.?

**Comment by Baschdl** [comment]
@kevinashaw Did you finally find a solution for the linear problem?

    ValueError: linear is expecting 2D arguments: [TensorShape([Dimension(1000)]), 
    TensorShape([Dimension(1000), Dimension(50)])]

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by martinwicke** [comment]
@MarkDaoust @mhyttsten, something to consider when thinking about the fate of our tutorials.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by MarkDaoust** [comment]
While it could use some modernization, the tutorial is working fine now.

**Comment by numericlee** [comment]
Thanks to @kevinashaw for pointing out this problem. 
As far as I can see @MarkDaoust @drpngx  
 the tutorial code posted here and at [TF site](https://www.tensorflow.org/tutorials/recurrent) still has the same errors after nearly 12 months

I did try making some of the modifications suggested above, they don't appear to solve the issue


```
Xin =tf.random_normal((100,100))

batch_size_var  = tf.shape(Xin)[0]
lstm = tf.nn.rnn_cell.LSTMCell(lstm_size) #with dynamic rnn the reference to .LSTMCell is invalid
hidden_state = lstm_cells.zero_state(batch_size_var, tf.float32) 
current_state = lstm_cells.zero_state(batch_size_var, tf.float32)
```
Is there another RNN tutorial anyone can recommend?

**Comment by SurfingWave** [comment]
How about try to use `lstm.state_size[0]` or `lstm.state_size[1]` instead of just using `lstm.state_size`
