### ISSUE TITLE
wide_n_deep meets kint32max bug.

### ISSUE THREAD

**Issue by gusuperstar** [tensorflow/tensorflow#9337]
I am trying to run a wide_n_deep model on a large dataset ------ I copy and paste adult.data 100 times as training data(adult.data.new 3256200 lines), and take adult.test as test data.

with command:
python wide_n_deep_tutorial.py --model_type=wide_n_deep --train_data=data/adult.data.new --test_data=data/adult.test

When I run the same model on original set of this, i.e. ~ 32562 set, the model runs fine. But when it tries on this 3256200 set, it throws up the following stack trace and exits.

Am I missing something here? The memory stats look fine when the program is running.

[libprotobuf ERROR google/protobuf/io/zero_copy_stream_impl_lite.cc:173] Cannot allocate buffer larger than kint32max for StringOutputStream.
Traceback (most recent call last):
  File "/var/dl/runtime/script/wide_n_deep_tutorial.py", line 234, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/var/dl/runtime/script/wide_n_deep_tutorial.py", line 197, in main
    FLAGS.train_data, FLAGS.test_data)
  File "/var/dl/runtime/script/wide_n_deep_tutorial.py", line 186, in train_and_eval
    m.fit(input_fn=lambda: input_fn(df_train), steps=train_steps)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 280, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 426, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 984, in _train_model
    _, loss = mon_sess.run([model_fn_ops.train_op, model_fn_ops.loss])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 462, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 786, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 744, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 883, in run
    feed_dict, options)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 909, in _call_hook_before_run
    request = hook.before_run(run_context)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/basic_session_run_hooks.py", line 340, in before_run
    "graph.pbtxt")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/graph_io.py", line 67, in write_graph
    file_io.atomic_write_string_to_file(path, str(graph_def))
ValueError: Unable to convert message to str

**Comment by drpngx** [comment]
Basically, graph is too big. This is not a bug in tensorflow itself, I would suggest you ask on stackoverflow for ways to reduce the graph size.

```
Cannot allocate buffer larger than kint32max for StringOutputStream.
```
