### ISSUE TITLE
Android Demo app & Yolo 2 - OutOfMemoryError 

### ISSUE THREAD

**Issue by anonym24** [tensorflow/tensorflow#9343]
I have successfully run Android Demo with Tiny Yolo (_graph-tiny-yolo-voc.pb_ - 60mb),:

```
  private static final String YOLO_MODEL_FILE = "file:///android_asset/graph-yolo-voc.pb";
  private static final int YOLO_INPUT_SIZE = 416;
  private static final String YOLO_INPUT_NAME = "input";
  private static final String YOLO_OUTPUT_NAMES = "output";
  private static final int YOLO_BLOCK_SIZE = 32;
  private static final boolean USE_YOLO = true;
```

I also decided to try Yolo 2 (_graph-yolo-voc.pb_ - 193mb),
but I get _OutOfMemoryError_ when I run _TF Detect_
My phone has 3 GB of RAM 
But I know that is just android java limit and has nothing to do with current available/free memory
and we can use NDK to bypass this limit.

I also tried to run with:
```
     <activity android:name="org.tensorflow.demo.DetectorActivity"
                  android:largeHeap="true"
```
but didn't help

And also:
```
<activity android:name="org.tensorflow.demo.DetectorActivity"
                  android:largeHeap="true"
                  android:hardwareAccelerated="false"
```
App runs ok, but nothing happens, it just shows black screen, no camera frames..

Is there a way to run app with big .pb files?  
_TensorFlowInferenceInterface_ needs _AssetManager_ and _string file name_, then I guess it just uses default java IO to read file,
mb it's better to process all of this with NDK somehow?

**Comment by drpngx** [comment]
@andrewharp in case there is an easy answer. The graph doesn't seem that big.

This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by andrewharp** [comment]
@anonym24 
193mb is bigger than anything I've ever run on Android :)  I'd suggest trying to [quantize](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/README.md#eight-bit-calculations) the graph to bring the size down as much as possible as a first step.

Can you provide the relevant logcat section? Is this just while the file is being read to the buffer or during graphdef initialization?

**Comment by andrewharp** [comment]
@anonym24 Also, we used to have a [native codepath](https://github.com/tensorflow/tensorflow/blob/r1.0/tensorflow/contrib/android/jni/jni_utils.cc) for loading graphs, but simplified to use Java when we switched to the Java API.

You could try resurrecting it, and if it resolves your issue then we can consider re-adding it as an augmentation/replacement to the default codepath.

@asimshankar If you have any comments on integrating this smoothly with the Java API.

**Comment by anonym24** [comment]
@andrewharp here's an error code:

```
04-21 09:40:52.731 31597-31597/org.tensorflow.demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: org.tensorflow.demo, PID: 31597
                                                                     java.lang.OutOfMemoryError: Failed to allocate a 202728962 byte allocation with 14422192 free bytes and 171MB until OOM
                                                                         at org.tensorflow.contrib.android.TensorFlowInferenceInterface.loadGraph(TensorFlowInferenceInterface.java:377)
                                                                         at org.tensorflow.contrib.android.TensorFlowInferenceInterface.<init>(TensorFlowInferenceInterface.java:96)
                                                                         at org.tensorflow.demo.TensorFlowYoloDetector.create(TensorFlowYoloDetector.java:111)
                                                                         at org.tensorflow.demo.DetectorActivity.onPreviewSizeChosen(DetectorActivity.java:131)
                                                                         at org.tensorflow.demo.CameraActivity$1.onPreviewSizeChosen(CameraActivity.java:159)
                                                                         at org.tensorflow.demo.CameraConnectionFragment.setUpCameraOutputs(CameraConnectionFragment.java:421)
                                                                         at org.tensorflow.demo.CameraConnectionFragment.openCamera(CameraConnectionFragment.java:428)
                                                                         at org.tensorflow.demo.CameraConnectionFragment.access$000(CameraConnectionFragment.java:64)
                                                                         at org.tensorflow.demo.CameraConnectionFragment$1.onSurfaceTextureAvailable(CameraConnectionFragment.java:95)
                                                                         at android.view.TextureView.getHardwareLayer(TextureView.java:368)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                         at android.view.View.draw(View.java:15971)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15193)
                                                                         at android.view.View.draw(View.java:15971)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
                                                                         at android.view.View.draw(View.java:16204)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15198)
                                                                         at android.view.View.draw(View.java:15971)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15193)
                                                                         at android.view.View.draw(View.java:15971)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15193)
                                                                         at android.view.View.draw(View.java:15971)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
                                                                         at android.view.View.draw(View.java:16204)
                                                                         at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2690)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15198)
                                                                         at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:282)
                                                                         at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:288)
                                                                         at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:323)
                                                                         at android.view.ViewRootImpl.draw(ViewRootImpl.java:2642)
                                                                         at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2461)
                                                                         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2094)
                                                                         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1134)
                                                                         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6045)
                                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
                                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:672)
                                                                         at android.view.Choreographer.doFrame(Choreographer.java:608)
                                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5441)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
04-21 09:40:52.740 1501-2367/? E/ActivityManager: Invalid thumbnail dimensions: 0x0
```
my normal free memory (1.0-1.4 gb): 

![screenshot_2017-04-21-09-42-38-371_com miui home](https://cloud.githubusercontent.com/assets/8851301/25265837/8886bd48-2677-11e7-99df-d1e3261e6cbd.png)

**Comment by anonym24** [comment]
@andrewharp  

> I'd suggest trying to quantize the graph to bring the size down as much as possible as a first step.

I get an error:

```
~/Desktop/tensorflow-master$ bazel build tensorflow/tools/graph_transforms:transform_graph
ERROR: /home/osboxes/Desktop/tensorflow-master/tensorflow/core/BUILD:1357:1: no such target '//tensorflow/tools/git:gen/spec.json': target 'gen/spec.json' not declared in package 'tensorflow/tools/git' defined by /home/osboxes/Desktop/tensorflow-master/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'.
ERROR: /home/osboxes/Desktop/tensorflow-master/tensorflow/core/BUILD:1357:1: no such target '//tensorflow/tools/git:gen/head': target 'gen/head' not declared in package 'tensorflow/tools/git' defined by /home/osboxes/Desktop/tensorflow-master/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'.
ERROR: /home/osboxes/Desktop/tensorflow-master/tensorflow/core/BUILD:1357:1: no such target '//tensorflow/tools/git:gen/branch_ref': target 'gen/branch_ref' not declared in package 'tensorflow/tools/git' defined by /home/osboxes/Desktop/tensorflow-master/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'.
ERROR: Analysis of target '//tensorflow/tools/graph_transforms:transform_graph' failed; build aborted.

```

**Comment by andrewharp** [comment]
You'll need to run configure first before building TF desktop binaries.

**Comment by anonym24** [comment]
yeah I removed my question, found out

**Comment by asimshankar** [comment]
@andrewharp : Regarding https://github.com/tensorflow/tensorflow/issues/9343#issuecomment-295959477 - I wonder that instead of doing something like that, should we get the saved model format going on Android and use that instead?

**Comment by anonym24** [comment]
@andrewharp I know I can build it on linux. I have vmware with ubuntu where I also build .pb files, but don't feel comfortable. How to do it in Windows. I  found https://github.com/tensorflow/tensorflow/tree/r0.12/tensorflow/contrib/cmake
but will `cmake .. -A x64 -DCMAKE_BUILD_TYPE=Release` be equal to `./configure`?

**Comment by andrewharp** [comment]
I'm not sure; no harm in running ./configure anyway though. Perhaps you could try the docker solution at the bottom of the readme, as it seems easier?

**Comment by anonym24** [comment]
@andrewharp  

> quantize the graph

I have built: `bazel build tensorflow/tools/graph_transforms:transform_graph`
Now I'm trying the second line, but I'm not sure what happens, looks like it asks for different parameters:

```
osboxes@osboxes:~/Desktop/tensorflow-master$ bazel-bin/tensorflow/tools/graph_transforms/transform_graph \
> --in_graph=graph-yolo-voc.pb \
> --out_graph=graph-yolo-voc-opt.pb \
> --inputs='Mul' \
> --outputs='softmax' \
> --transforms='
>   add_default_attributes
>   strip_unused_nodes(type=float, shape="1,299,299,3")
>   remove_nodes(op=Identity, op=CheckNumerics)
>   fold_constants(ignore_errors=true)
>   fold_batch_norms
>   fold_old_batch_norms
>   quantize_weights
>   quantize_nodes
>   strip_unused_nodes
>   sort_by_execution_order'
2017-04-23 10:35:57.903947: I tensorflow/tools/graph_transforms/transform_graph.cc:257] Applying add_default_attributes
2017-04-23 10:35:58.162621: I tensorflow/tools/graph_transforms/transform_graph.cc:257] Applying strip_unused_nodes
2017-04-23 10:35:58.162877: E tensorflow/tools/graph_transforms/transform_graph.cc:203] Input node softmax not found in graph
2017-04-23 10:35:58.162919: E tensorflow/tools/graph_transforms/transform_graph.cc:204] usage: bazel-bin/tensorflow/tools/graph_transforms/transform_graph
Flags:
	--in_graph=""                    	string	input graph file name
	--out_graph=""                   	string	output graph file name
	--inputs=""                      	string	inputs
	--outputs=""                     	string	outputs
	--transforms=""                  	string	list of transforms
	--output_as_text=false           	bool	whether to write the graph in text protobuf format

Transforms are:
add_default_attributes
backport_concatv2
backport_tensor_array_v3
fold_batch_norms
fold_constants
fold_old_batch_norms
freeze_requantization_ranges
fuse_pad_and_conv
fuse_resize_and_conv
fuse_resize_pad_and_conv
insert_logging
merge_duplicate_nodes
obfuscate_names
quantize_nodes
quantize_weights
remove_attribute
remove_device
remove_nodes
rename_attribute
rename_op
rewrite_quantized_stripped_model_for_hexagon
round_weights
set_device
sort_by_execution_order
sparsify_gather
strip_unused_nodes

osboxes@osboxes:~/Desktop/tensorflow-master$ 

```

**Comment by anonym24** [comment]
@andrewharp 

> have a native codepath for loading graphs

Also could you help me with resurrecting it? I just don't work with C++/NDK in Android Studio. I have successfully set bazel/worksplace/ndk for Android demo on Ubuntu and I can build project without errors (though it takes some time)
