### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Birkoniajack** [tensorflow/tensorflow#9364]
Trying to get tensorflow to work for my final bit on dissertation but anytime I try to install it in virtual box ubuntu linux 64bit, I get this error I've tried the CPU/GPU version but I can only seem to get the python3 version working but I need the python2.

I get this error message each time..  

 99% |████████████████████████████████| 44.1MB 14.8MB/s eta 0:00:01Exception:
Traceback (most recent call last):
  File "/home/tay/tensorflow/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/tay/tensorflow/local/lib/python2.7/site-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/home/tay/tensorflow/local/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/tay/tensorflow/local/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/tay/tensorflow/local/lib/python2.7/site-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/home/tay/tensorflow/local/lib/python2.7/site-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/home/tay/tensorflow/local/lib/python2.7/site-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/home/tay/tensorflow/local/lib/python2.7/site-packages/pip/download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/home/tay/tensorflow/local/lib/python2.7/site-packages/pip/download.py", line 605, in _download_url
    consume(downloaded_chunks)
  File "/home/tay/tensorflow/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 870, in consume
    deque(iterator, maxlen=0)
  File "/home/tay/tensorflow/local/lib/python2.7/site-packages/pip/download.py", line 571, in written_chunks
    for chunk in chunks:
  File "/home/tay/tensorflow/local/lib/python2.7/site-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/home/tay/tensorflow/local/lib/python2.7/site-packages/pip/download.py", line 560, in resp_read
    decode_content=False):
  File "/home/tay/tensorflow/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/response.py", line 432, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/tay/tensorflow/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/response.py", line 380, in read
    data = self._fp.read(amt)
  File "/home/tay/tensorflow/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/filewrapper.py", line 63, in read
    self._close()
  File "/home/tay/tensorflow/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/filewrapper.py", line 50, in _close
    self.__callback(self.__buf.getvalue())
  File "/home/tay/tensorflow/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/controller.py", line 275, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/home/tay/tensorflow/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/serialize.py", line 87, in dumps
    ).encode("utf8"),
MemoryError

**Comment by drpngx** [comment]
Are you using ubuntu 16? My guess is that you need to increase memory allocation on virtualbox.

**Comment by Birkoniajack** [comment]
I ended up installing a real version of linux but i assume memory allocation was the reason!

Thanks for the reply.
