### ISSUE TITLE
TensorFlow Retrain  Android Error

### ISSUE THREAD

**Issue by ManoharKowshik** [tensorflow/tensorflow#9365]
I have my own custom created .pb file and string text using TensorFlow Retrain Model
https://www.tensorflow.org/versions/r0.10/how_tos/image_retraining/
Then i have created .so file By building tensorflow
bazel build -c opt //tensorflow/examples/android:tensorflow_demo
 
When i load both into androidstudio and run the app i get below error

No Operation named [input] in the Graph
                                                                                  at org.tensorflow.Session$Runner.operationByName(Session.java:297)
                                                                                  at org.tensorflow.Session$Runner.feed(Session.java:115)
                                                                                  at org.tensorflow.contrib.android.TensorFlowInferenceInterface.addFeed(TensorFlowInferenceInterface.java:439)
                                                                                  at org.tensorflow.contrib.android.TensorFlowInferenceInterface.fillNodeFloat(TensorFlowInferenceInterface.java:188)
                                                                                  at com.mindorks.tensorflowexample.TensorFlowImageClassifier.recognizeImage(TensorFlowImageClassifier.java:146)
                                                                                  at com.mindorks.tensorflowexample.MainActivity$1.onPictureTaken(MainActivity.java:81)
                                                                                  at com.flurgle.camerakit.CameraView$CameraListenerMiddleWare.onPictureTaken(CameraView.java:296)
                                                                                  at com.flurgle.camerakit.Camera1$2.onPictureTaken(Camera1.java:185)
                                                                                  at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1201)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:135)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5253)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)

I have created input_node as "Mul:0" and Out_put node as "Final_result" while building

**Comment by andrewharp** [comment]
If you switch from Inception-v1 to Inception-v3 you'll also need to update the values in ClassifierActivity according to the comment there. The name of the input node is no longer "input".

**Comment by ManoharKowshik** [comment]
Yes i very much agree with you. I have made corresponding changes in classifierActivity as well..Like below

private static final int NUM_CLASSES = 1001;
  private static final int INPUT_SIZE = 224;
  private static final int IMAGE_MEAN = 117;
  private static final float IMAGE_STD = 1;
  private static final String INPUT_NAME = "Mul:0";
  private static final String OUTPUT_NAME = "final_result:0";

  private static final String MODEL_FILE = "file:///android_asset/tensorflow_inception_graph.pb";
  private static final String LABEL_FILE =
      "file:///android_asset/imagenet_comp_graph_label_strings.txt";


and in ImageClassifier.java also i have made the same changes as well

private static final int NUM_CLASSES = 1001;
  private static final int INPUT_SIZE = 224;
  private static final int IMAGE_MEAN = 117;
  private static final float IMAGE_STD = 1;
  private static final String INPUT_NAME = "Mul:0";
  private static final String OUTPUT_NAME = "final_result:0";

  private static final String MODEL_FILE = "file:///android_asset/tensorflow_inception_graph.pb";
  private static final String LABEL_FILE =
      "file:///android_asset/imagenet_comp_graph_label_strings.txt";
I then build the tensorflow..

**Comment by andrewharp** [comment]
If you've updated the code as described I'm not sure what's going on, as the logcat clearly shows that it's looking for a node named "input". Are you sure the APK is actually getting rebuilt properly and pushed to device?

Also you should only have to edit ClassifierActivity.java. Just adding fields to TensorFlowImageClassifier.jaa (if that's what you meant) won't do anything by itself.

**Comment by ManoharKowshik** [comment]
Okay..DO i need to change anything c++ code ..Like add input_name or out_put name in any .cc code so that it links between java and c++ code?

**Comment by andrewharp** [comment]
No, changing the graph to use is done entirely in Java in the demo src code.

**Comment by ManoharKowshik** [comment]
Okay..Thanks for replying ..Just confirm me is this correct...Sorry to bother
1. I will retrain my custom model generat .pb file and txt file and give input_Name and out_putname as "Mul" and "final_result" during label_image build.
2. Then as per your help will change ClassifierActivity.java  to update Defaut values. Then build to generate infernce.so file by 

bazel build -c opt //tensorflow/contrib/android:libtensorflow_inference.so \
   --crosstool_top=//external:android/crosstool \
   --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
   --cpu=armeabi-v7a

3. Create Java jar file by 

bazel build //tensorflow/contrib/android:android_tensorflow_inference_java

4. Open android studio create my sample app. Add jar file in libs and .so file in jniLibs and graphs in assets folder.

Now run the app..Correct right?

**Comment by andrewharp** [comment]
The build.gradle file should handle all of the building for you, assuming you're running on Linux. You should just need to update the values in ClassifierActivity.java to point to your retrained graph assuming you have Bazel installed correctly etc.

**Comment by ManoharKowshik** [comment]
The problem is i am building in linux VM and then need to load on android studio in windows.. Could you help me with that?

Is there a tutorial for that?

**Comment by andrewharp** [comment]
Building the native libraries stays exactly the same regardless of the
graph you use (unless you're building with selective registration). To
build android tensorflow on windows follow this workaround:
https://github.com/tensorflow/tensorflow/issues/6385#issuecomment-285208600

Or just manually add the libraries as the comment above suggests.

**Comment by ManoharKowshik** [comment]
Code is working..Thanks for the info

**Comment by GehenHe** [comment]
@andrewharp 
I try to use a model which require multi-input , how can I configure multi-input for this model in tensorflow android?[details is here](https://stackoverflow.com/questions/44693500/tensorflow-android-demo-use-cumstom-model-with-multi-input)
