### ISSUE TITLE
Tensorflow is still taking up all GPU memory despite allocation of memory

### ISSUE THREAD

**Issue by yujulucy** [tensorflow/tensorflow#9400]
**System Information:**
- OS Platform: Linux Ubuntu 16.04
- TensorFlow installed from binary
- TensorFlow version: 1.0.1
- CUDA version: 8.0
- cuDNN version: 5.1

output for print(tf.GIT_VERSION, tf.VERSION):
('v1.0.0-65-g4763edf-dirty', '1.0.1')

**Problem:**
I have three codes running GPU-enabled TensorFlow. Currently, when the GPU is allocated for two of the processes, the GPU does get allocated. However, no matter how much GPU I allocate to the last process, it takes up all the GPU, disallowing other two processes to run simultaneously. 

**First process (the one with problem)**
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 1060
major: 6 minor: 1 memoryClockRate (GHz) 1.6705
pciBusID 0000:01:00.0
Total memory: 5.93GiB
Free memory: 5.68GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1060, pci bus id: 0000:01:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1060, pci bus id: 0000:01:00.0)

**Second process:**
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 1060
major: 6 minor: 1 memoryClockRate (GHz) 1.6705
pciBusID 0000:01:00.0
Total memory: 5.93GiB
Free memory: 237.00MiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1060, pci bus id: 0000:01:00.0)
E tensorflow/stream_executor/cuda/cuda_driver.cc:1002] failed to allocate 1.19G (1273049856 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
E tensorflow/stream_executor/cuda/cuda_driver.cc:1002] failed to allocate 1.07G (1145744896 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
E tensorflow/stream_executor/cuda/cuda_driver.cc:1002] failed to allocate 983.40M (1031170560 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
E tensorflow/stream_executor/cuda/cuda_driver.cc:1002] failed to allocate 885.06M (928053504 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
E tensorflow/stream_executor/cuda/cuda_driver.cc:1002] failed to allocate 796.55M (835248128 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
E tensorflow/stream_executor/cuda/cuda_driver.cc:1002] failed to allocate 716.90M (751723264 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
E tensorflow/stream_executor/cuda/cuda_driver.cc:1002] failed to allocate 645.21M (676550912 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
E tensorflow/stream_executor/cuda/cuda_driver.cc:1002] failed to allocate 580.69M (608896000 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
E tensorflow/stream_executor/cuda/cuda_driver.cc:1002] failed to allocate 522.62M (548006400 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
E tensorflow/stream_executor/cuda/cuda_driver.cc:1002] failed to allocate 470.36M (493205760 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
E tensorflow/stream_executor/cuda/cuda_driver.cc:1002] failed to allocate 423.32M (443885312 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
E tensorflow/stream_executor/cuda/cuda_driver.cc:1002] failed to allocate 380.99M (399496960 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
E tensorflow/stream_executor/cuda/cuda_driver.cc:1002] failed to allocate 342.89M (359547392 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
E tensorflow/stream_executor/cuda/cuda_driver.cc:1002] failed to allocate 308.60M (323592704 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
E tensorflow/stream_executor/cuda/cuda_driver.cc:1002] failed to allocate 277.74M (291233536 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
E tensorflow/stream_executor/cuda/cuda_driver.cc:1002] failed to allocate 249.97M (262110208 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
E tensorflow/stream_executor/cuda/cuda_driver.cc:1002] failed to allocate 224.97M (235899392 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
WARNING:apscheduler.scheduler:Execution of job "session (trigger: interval[0:00:01], next run at: 2017-04-24 11:24:48.702309)" skipped: maximum number of running instances reached (1)
E tensorflow/stream_executor/cuda/cuda_dnn.cc:397] could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
E tensorflow/stream_executor/cuda/cuda_dnn.cc:364] could not destroy cudnn handle: CUDNN_STATUS_BAD_PARAM
F tensorflow/core/kernels/conv_ops.cc:605] Check failed: stream->parent()->GetConvolveAlgorithms(&algorithms) 

**The code I am using to allocate GPU for the first process:**
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.3)
sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options, log_device_placement=False))

I have also looked up stackoverflow but it does not seem to have the same problems raised.
Some pages I referred to:
http://stackoverflow.com/questions/34199233/how-to-prevent-tensorflow-from-allocating-the-totality-of-a-gpu-memory 
https://www.tensorflow.org/tutorials/using_gpu 
https://github.com/tensorflow/tensorflow/issues/398

**Comment by PhilJd** [comment]
How much memory does your last process consume if you start this one on its own? CUDA_ERROR_OUT_OF_MEMORY usually states that a model is too big and doesn't fit in the pre-allocated memory.

**Comment by vijpandaturtle** [comment]
I am facing similar issues with memory allocation in tensorflow and i'm really unable to figure out what to do.. currently i am trying to train a cnn for a kaggle dataset of 48x48 pixel images and this is the code 
https://github.com/vijpandaturtle/facial-expressions
Everytime i make even a small change in my layers, it keeps throwing the following error 

Training on the data
---------------------------------------------------------------------------
ResourceExhaustedError                    Traceback (most recent call last)
/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1021     try:
-> 1022       return fn(*args)
   1023     except errors.OpError as e:

/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/client/session.py in _run_fn(session, feed_dict, fetch_list, target_list, options, run_metadata)
   1003                                  feed_dict, fetch_list, target_list,
-> 1004                                  status, run_metadata)
   1005 

/home/carnd/anaconda3/envs/dl/lib/python3.5/contextlib.py in __exit__(self, type, value, traceback)
     65             try:
---> 66                 next(self.gen)
     67             except StopIteration:

/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py in raise_exception_on_not_ok_status()
    468           compat.as_text(pywrap_tensorflow.TF_Message(status)),
--> 469           pywrap_tensorflow.TF_GetCode(status))
    470   finally:

ResourceExhaustedError: OOM when allocating tensor with shape[73728,2304]
	 [[Node: truncated_normal_4/TruncatedNormal = TruncatedNormal[T=DT_INT32, dtype=DT_FLOAT, seed=0, seed2=0, _device="/job:localhost/replica:0/task:0/gpu:0"](truncated_normal_4/shape)]]

During handling of the above exception, another exception occurred:

ResourceExhaustedError                    Traceback (most recent call last)
<ipython-input-56-ab81f6da0f51> in <module>()
      2 print("Training on the data")
      3 with tf.Session() as sess:
----> 4     sess.run(tf.global_variables_initializer())
      5 
      6     for epoch in range(epochs):

/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    765     try:
    766       result = self._run(None, fetches, feed_dict, options_ptr,
--> 767                          run_metadata_ptr)
    768       if run_metadata:
    769         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
    963     if final_fetches or final_targets:
    964       results = self._do_run(handle, final_targets, final_fetches,
--> 965                              feed_dict_string, options, run_metadata)
    966     else:
    967       results = []

/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1013     if handle is None:
   1014       return self._do_call(_run_fn, self._session, feed_dict, fetch_list,
-> 1015                            target_list, options, run_metadata)
   1016     else:
   1017       return self._do_call(_prun_fn, self._session, handle, feed_dict,

/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1033         except KeyError:
   1034           pass
-> 1035       raise type(e)(node_def, op, message)
   1036 
   1037   def _extend_graph(self):

ResourceExhaustedError: OOM when allocating tensor with shape[73728,2304]
	 [[Node: truncated_normal_4/TruncatedNormal = TruncatedNormal[T=DT_INT32, dtype=DT_FLOAT, seed=0, seed2=0, _device="/job:localhost/replica:0/task:0/gpu:0"](truncated_normal_4/shape)]]

Caused by op 'truncated_normal_4/TruncatedNormal', defined at:
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 474, in start
    ioloop.IOLoop.instance().start()
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/tornado/ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/ipykernel/zmqshell.py", line 501, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-53-742fe13e3ffc>", line 40, in <module>
    logits = conv_net(x, keep_prob)
  File "<ipython-input-53-742fe13e3ffc>", line 18, in conv_net
    neural_net = fully_conn(neural_net, 2304)
  File "<ipython-input-51-91b00ac8f4d7>", line 10, in fully_conn
    weights_full = tf.Variable(tf.truncated_normal([dimension, num_outputs], stddev = 0.05))
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/ops/random_ops.py", line 174, in truncated_normal
    seed2=seed2)
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/ops/gen_random_ops.py", line 293, in _truncated_normal
    seed=seed, seed2=seed2, name=name)
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[73728,2304]
	 [[Node: truncated_normal_4/TruncatedNormal = TruncatedNormal[T=DT_INT32, dtype=DT_FLOAT, seed=0, seed2=0, _device="/job:localhost/replica:0/task:0/gpu:0"](truncated_normal_4/shape)]]


I am using a g2.2x large aws instance to train my model on this dataset
https://www.kaggle.com/c/challenges-in-representation-learning-facial-expression-recognition-challenge
Thanks !

**Comment by drpngx** [comment]
just checking: did you use `list_devices` before?
(See https://github.com/tensorflow/tensorflow/issues/8021)

**Comment by vijpandaturtle** [comment]
No i don't think so

**Comment by drpngx** [comment]
It might be another problem with initialization. Could you try to remove all preamble to see what makes it fail?

**Comment by vijpandaturtle** [comment]
Ah yes!! I'll post a snippet of a part of the code that kept throwing the error as i changed it 
So basically the errors kept popping up the minute i change the stride of my convolutional layer from (2,2)
to (1,1)
I'm also posting a snippet of my network

    # The first three convolutional + maxpooling layers
    neural_net = conv2d_maxpool(x, 32, (5,5), (1,1), (2,2), (1,1))
    neural_net = conv2d_maxpool(neural_net, 64, (1,1), (2,2), (4,4), (2,2))
    neural_net = conv2d_maxpool(neural_net, 64, (2,2), (1,1), (2,2), (1,1))
    neural_net = conv2d_maxpool(neural_net, 128, (2,2), (1,1), (2,2), (1,1))

    # Layer to flatten the tensor from the convolutional layers
    neural_net = flatten(neural_net)
    
    # Two fully connected layers with dropout
    neural_net = fully_conn(neural_net, 2304)
    neural_net = tf.nn.dropout(neural_net, keep_prob)
    neural_net = fully_conn(neural_net, 1152)
    neural_net = tf.nn.dropout(neural_net, keep_prob)
    neural_net = fully_conn(neural_net, 576)
    
    # Layer for output
    neural_net = output(neural_net, 7)

Here i have defined  custom wrappers for each layer ..which you can find in my repo

**Comment by drpngx** [comment]
So, to be clear, if you use `(1, 1)` instead of `(2, 2)` in the code above, then it works?

**Comment by PhilJd** [comment]
As far as I understood it, it works when he uses strides (2, 2), which makes more sense to me, as using strides of (1,1) doubles the memory necessary to store the activations compared to strides of 2.

**Comment by yujulucy** [comment]
@PhilJd The second process need less than 10% of the GPU to run. 10% of the GPU is 600MB.

**Comment by yujulucy** [comment]
I have just realized that the first process with the problem prints out **I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1060, pci bus id: 0000:01:00.0)** twice. Other processes only prints out once. Does this mean that double the amount of GPU I specified is allocated to this process?

**Comment by yujulucy** [comment]
@drpngx Using list_devices() prints out one extra **I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1060, pci bus id: 0000:01:00.0)**

**Comment by vijpandaturtle** [comment]
@drpngx the network keeps throwing an error if i change the stride from (2,2) to (1,1)
so i'm unable to figure out a way to get my network to improve its accuracy because the (2,2) stride is causing the network to lose lots of information.

**Comment by drpngx** [comment]
@vijpandaturtle you might be facing another problem. Could you open another issue?

@yujulucy that's very informative (printing out twice). If you had a python/c++ stack trace for each of the print outs, that would be useful.

**Comment by vijpandaturtle** [comment]
Sure i'll do that

**Comment by tbchj** [comment]
@yujulucy  I  tried before, and I found that if I run standalone training(not distribute training), the code you wrote: 
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.3)
sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options, log_device_placement=False))
 works, but if run distribute training, and it didn't work. i also want to know how to solve it.
focus on it.

**Comment by cwhipkey** [comment]
@tbchj @yujulucy - when you write that this works in standalone training, but not with distributed training - can you post the example of how distributed training is set up?  Distributed training setup should also be able to take a 'config' parameter - you can try passing your config to that setup as well?

**Comment by tensorflowbutler** [comment]
This issue is automatically closed due to lack of activity. Please re-open if this is still an issue for you. Thanks!

**Comment by oliverhu** [comment]
@cwhipkey the memory allocation happens right after you call `tf.train.ClusterSpec` before the distributed session starts.

@tbchj have you found a solution? This issue is bombing our containers :(

**Comment by cwhipkey** [comment]
What does the tf.train.Server call look like?  Are you passing in the 'config' parameter?

**Comment by oliverhu** [comment]
Yes, I also tried putting config there, didn't work. Tried both `config.gpu_options.per_process_gpu_memory_fraction = 0.2` and `config.gpu_options.allow_growth=True`

``` 67         config = tf.ConfigProto()
 68         config.gpu_options.per_process_gpu_memory_fraction = 0.2
 69         server = tf.train.Server(tf_cluster_spec,
 70                                  job_name=job_name,
 71                                  task_index=task_index,
 72                                  config=config)```

**Comment by oliverhu** [comment]
@cwhipkey  above

**Comment by GoingMyWay** [comment]
See [this question](https://stackoverflow.com/questions/47910681/tensorflow-setting-allow-growth-to-true-does-still-allocate-memory-of-all-my-gp)

Set `os.environ['TF_FORCE_GPU_ALLOW_GROWTH'] = 'true'` in Python code.
