### ISSUE TITLE
Batch + dynamic_pad + squeeze + one_hot + dynamic_rnn throws shape error

### ISSUE THREAD

**Issue by EdeMeijer** [tensorflow/tensorflow#9455]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04.1 LTS (Xenial Xerus)
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: v1.1.0-rc2-259-g34c738c
- **Bazel version (if compiling from source)**: 0.4.5
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Python version**: 3.5.2
- **Exact command to reproduce**: `python ./bug.py`

### Describe the problem

A certain combination of ops causes `tf.nn.dynamic_rnn` to throw a `ValueError: Input size (depth of inputs) must be accessible via shape inference, but saw value None.` during compilation of the graph. I will attach the script to reproduce the issue and the required tfrecords file.

The problem seems to be a combination of batching with `dynamic_pad` enabled, and `squeeze` + `one_hot`. I use `squeeze` + `one_hot` because `SequenceExample` gives me a `[examples x time_steps x 1]` tensor, and `one_hot` adds another dimension, so I first need to get rid of the last dimension to get a `[examples x time_steps x 3]` one-hot encoded tensor.

A few observations:

- When excluding `availability_one_hot` from the `lstm_inputs` concat, the script runs ok.
- When commenting out the `dynamic_rnn` op and evaluating `print(sess.run(tf.shape(lstm_inputs)))` instead, the output is `[2 8 4]`, which is the correct shape (1 normal feature + 3 from the one-hot encoding = 4 features)`.
- I tried to recreate the batch with a `tf.constant()` literal, but using that the graph worked fine, so the batching with dynamic padding is needed to reproduce the issue. 

### Source code / logs

Script + data file: [bug.zip](https://github.com/tensorflow/tensorflow/files/957645/bug.zip)

Output:
```
Traceback (most recent call last):
  File "/home/ede/repos/xxx/xxx/misc/tftest/bug.py", line 38, in <module>
    inputs=lstm_inputs
  File "/home/ede/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/rnn.py", line 582, in dynamic_rnn
    dtype=dtype)
  File "/home/ede/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/rnn.py", line 652, in _dynamic_rnn_loop
    "Input size (depth of inputs) must be accessible via shape inference,"
ValueError: Input size (depth of inputs) must be accessible via shape inference, but saw value None.
```

**Comment by EdeMeijer** [comment]
Okay, I figured out that the static shape information was lost at the `squeeze` op because I didn't specify an axis. Adding `axis=2` fixes it. I suppose this isn't so much of a bug but rather lack of understanding from my end. Will close this as the problem is resolved.
