### ISSUE TITLE
graph_transforms tool obfuscate_names won't work

### ISSUE THREAD

**Issue by thisismohitgupta** [tensorflow/tensorflow#9494]
### System information

- **OS Platform and Distribution : Ubuntu 16.04**
**GIT_VERSION: v1.1.0-rc0-61-g1ec6ed5**
**Tensorflow Version: 1.1.0**

```
bazel-bin/tensorflow/tools/graph_transforms/transform_graph \
--in_graph=MYMODEL.pb \
--out_graph=MYMODEL_OPT.pb \
--inputs='input_feed:0,Squeeze_1:0,lstm/state_feed:0' \
--outputs='lstm/initial_state:0,softmax:0,lstm/state:0' \
--transforms='
  obfuscate_names'
```

Bug: Model as follows (Inception V3) -> (LSTM)
I used the graph_transform tool to obfuscate names using the obfuscate_names command for android deployment. model seems to work fine on android but when I try to obfuscate names problems start to surface.

logs
```
Caused by: java.io.IOException: Not a valid TensorFlow Graph serialization: Node 'rY' expects to be colocated with unknown node 'logits/biases'
                                                                                 at org.tensorflow.contrib.android.TensorFlowInferenceInterface.loadGraph(TensorFlowInferenceInterface.java:392)
                                                                                 at org.tensorflow.contrib.android.TensorFlowInferenceInterface.<init>(TensorFlowInferenceInterface.java:96)
                                                                                 at com.example.thisismohit.local.MainActivity.onCreate(MainActivity.java:158) 
                                                                                 at android.app.Activity.performCreate(Activity.java:6283) 
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119) 
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646) 
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2758) 
                                                                                 at android.app.ActivityThread.access$900(ActivityThread.java:177) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:145) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5942) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195) 

```

**Comment by girving** [comment]
@petewarden Do you know what this error means?

**Comment by petewarden** [comment]
I think the issue is that the old node names (before the obsfucation) are still being used for colocation attributes. Since collocation not usually needed on mobile devices, you could try also running a graph transform to get rid of the attribute that defines it. Something like

--transforms='remove_attribute(attribute_name=_class)'

https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/graph_transforms/#remove_attribute

Let me know if that workaround helps. The real fix is to update the node names in the attribute to the obsfucated versions, but that would be fairly involved.

**Comment by thisismohitgupta** [comment]
remove_attribute(attribute_name=_class) works automagically. Thanks...
