### ISSUE TITLE
sigmoid_cross_entropy_loss_with_logits: ReLU input is not finite

### ISSUE THREAD

**Issue by yoavz** [tensorflow/tensorflow#950]
```
W tensorflow/core/common_runtime/executor.cc:1076] 0x7fc328bccbd0 Compute status: Invalid argument: ReluGrad input is not finite. : Tensor had NaN values
	 [[Node: nl_1_hs_100_lr_0p1/gradients/nl_1_hs_100_lr_0p1/logistic_loss/Relu_grad/nl_1_hs_100_lr_0p1/logistic_loss/Relu/CheckNumerics = CheckNumerics[T=DT_FLOAT, message="ReluGrad input is not finite.", _device="/job:localhost/replica:0/task:0/cpu:0"](nl_1_hs_100_lr_0p1/add)]]
W tensorflow/core/common_runtime/executor.cc:1076] 0x7fc328bccbd0 Compute status: Invalid argument: ReluGrad input is not finite. : Tensor had NaN values
	 [[Node: nl_1_hs_100_lr_0p1/gradients/nl_1_hs_100_lr_0p1/logistic_loss/Relu_grad/nl_1_hs_100_lr_0p1/logistic_loss/Relu/CheckNumerics = CheckNumerics[T=DT_FLOAT, message="ReluGrad input is not finite.", _device="/job:localhost/replica:0/task:0/cpu:0"](nl_1_hs_100_lr_0p1/add)]]
	 [[Node: _send_nl_1_hs_100_lr_0p1/div_1_0 = _Send[T=DT_FLOAT, client_terminated=true, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=6247430638048453470, tensor_name="nl_1_hs_100_lr_0p1/div_1:0", _device="/job:localhost/replica:0/task:0/cpu:0"](nl_1_hs_100_lr_0p1/div_1)]]
Traceback (most recent call last):
  File "rnn.py", line 80, in <module>
    training=True)
  File "rnn.py", line 18, in run_epoch
    model.seq_targets: seq_targets
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 368, in run
    results = self._do_run(target_list, unique_fetch_targets, feed_dict_string)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 444, in _do_run
    e.code)
tensorflow.python.framework.errors.InvalidArgumentError: ReluGrad input is not finite. : Tensor had NaN values
	 [[Node: nl_1_hs_100_lr_0p1/gradients/nl_1_hs_100_lr_0p1/logistic_loss/Relu_grad/nl_1_hs_100_lr_0p1/logistic_loss/Relu/CheckNumerics = CheckNumerics[T=DT_FLOAT, message="ReluGrad input is not finite.", _device="/job:localhost/replica:0/task:0/cpu:0"](nl_1_hs_100_lr_0p1/add)]]
Caused by op u'nl_1_hs_100_lr_0p1/gradients/nl_1_hs_100_lr_0p1/logistic_loss/Relu_grad/nl_1_hs_100_lr_0p1/logistic_loss/Relu/CheckNumerics', defined at:
  File "rnn.py", line 70, in <module>
    train_model = Model(set_config(config, "train"))
  File "/Users/yoav/projects/music_rnn/model.py", line 61, in __init__
    .minimize(self.loss)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 186, in minimize
    aggregation_method=aggregation_method)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 232, in compute_gradients
    aggregation_method=aggregation_method)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/gradients.py", line 445, in gradients
    in_grads = _AsList(grad_fn(op_wrapper, *out_grads))
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/nn_grad.py", line 126, in _ReluGrad
    t = _VerifyTensor(op.inputs[0], op.name, "ReluGrad input is not finite.")
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/nn_grad.py", line 119, in _VerifyTensor
    verify_input = array_ops.check_numerics(t, message=msg)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 48, in check_numerics
    name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 664, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1834, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1043, in __init__
    self._traceback = _extract_stack()

...which was originally created as op u'nl_1_hs_100_lr_0p1/logistic_loss/Relu', defined at:
  File "rnn.py", line 70, in <module>
    train_model = Model(set_config(config, "train"))
  File "/Users/yoav/projects/music_rnn/model.py", line 58, in __init__
    losses = tf.nn.sigmoid_cross_entropy_with_logits(outputs, targets_concat)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/nn.py", line 273, in sigmoid_cross_entropy_with_logits
    return math_ops.add(nn_ops.relu(logits) - logits * targets,
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 547, in relu
    return _op_def_lib.apply_op("Relu", features=features, name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 664, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1834, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1043, in __init__
    self._traceback = _extract_stack()
```

When training a model using tf.nn.sigmoid_cross_entropy_loss_with_logits and RMSPropOptimizer, I am running into a ReLu gradient error. Since the initial learning rate for this instance of the model is quite high and this is a RNN, I am pretty confident that this is an exploding gradient issue with my model. However, the ReLU operation that my model is exploding on is part of an optimization to "ensure stability and avoid overflow", but it seems to be having the opposite effect.

**Comment by yoavz** [comment]
For quick reference, here is the full source code of sigimoid_cross_entropy_with_logits

```
def sigmoid_cross_entropy_with_logits(logits, targets, name=None):
  """Computes sigmoid cross entropy given `logits`.

  Measures the probability error in discrete classification tasks in which each
  class is independent and not mutually exclusive.  For instance, one could
  perform multilabel classification where a picture can contain both an elephant
  and a dog at the same time.

  For brevity, let `x = logits`, `z = targets`.  The logistic loss is

        z * -log(sigmoid(x)) + (1 - z) * -log(1 - sigmoid(x))
      = z * -log(1 / (1 + exp(-x))) + (1 - z) * -log(exp(-x) / (1 + exp(-x)))
      = z * log(1 + exp(-x)) + (1 - z) * (-log(exp(-x)) + log(1 + exp(-x)))
      = z * log(1 + exp(-x)) + (1 - z) * (x + log(1 + exp(-x))
      = (1 - z) * x + log(1 + exp(-x))
      = x - x * z + log(1 + exp(-x))

  To ensure stability and avoid overflow, the implementation uses

      max(x, 0) - x * z + log(1 + exp(-abs(x)))

  `logits` and `targets` must have the same type and shape.

  Args:
    logits: A `Tensor` of type `float32` or `float64`.
    targets: A `Tensor` of the same type and shape as `logits`.
    name: A name for the operation (optional).

  Returns:
    A `Tensor` of the same shape as `logits` with the componentwise
    logistic losses.
  """
  with ops.op_scope([logits, targets], name, "logistic_loss") as name:
    logits = ops.convert_to_tensor(logits, name="logits")
    targets = ops.convert_to_tensor(targets, name="targets")
    # The logistic loss formula from above is
    #   x - x * z + log(1 + exp(-x))
    # For x < 0, a more numerically stable formula is
    #   -x * z + log(1 + exp(x))
    # To avoid branching, we use the combined version
    #   max(x, 0) - x * z + log(1 + exp(-abs(x)))
    return math_ops.add(nn_ops.relu(logits) - logits * targets,
                        math_ops.log(1 + math_ops.exp(-math_ops.abs(logits))),
                        name=name)

```

**Comment by yaroslavvb** [comment]
This sounds like an issue with your model rather than a bug in TensorFlow, you may get more help from stackoverflow community on an issue like this

**Comment by yoavz** [comment]
@yaroslavvb: Sorry, I should have been more clear: I agree with you that this is an exploding gradient issue with my model. 

The reason I believe this **is** also a bug with tensorflow is that I am using a loss function from the official tensorflow API (sigmoid_cross_entropy_loss_with_logits). The documentation of this function leads me to believe that it is supposed to ensure numerical stability during training, and this is a counterexample where it did not. Perhaps I am misunderstanding the documentation?

**Comment by yaroslavvb** [comment]
Numerical stability means the result of computation is more accurate. But when you have exploding gradients, the growth in magnitudes is a feature of your model rather than some numerical error. It's like putting i=i**2 in a loop, you are going to run out of range at some point.
