### ISSUE TITLE
Try launch tensorflow and get error

### ISSUE THREAD

**Issue by tonymdsl** [tensorflow/tensorflow#9603]
i have install tensorflow on windows 10 and when i put a demo he gives me this error plz help me tanks

![capturar](https://cloud.githubusercontent.com/assets/17919329/25643061/65e33d62-2f95-11e7-9d78-18ad59ec8526.JPG)

**Comment by Carmezim** [comment]
Could you please try to install [Microsoft Visual C++ 2015 Redistributable Update 3](https://www.microsoft.com/en-us/download/details.aspx?id=53587) and let me know if it solves for you?
In a future situation when you need to report an issue please fill the template and post your log instead of screenshots as it helps us assess the situation, otherwise is quite difficult.

**Comment by dzid26** [comment]
I have same error and above solution doesn't work. 
(Windows 10)

**Comment by Carmezim** [comment]
@dzid26 Could you please provide all the info (OS, Python distribution and version, TensorFlow version, stack trace etc and other relevant information)? Otherwise we won't be able to help you. Thanks.

**Comment by dzid26** [comment]
Win10 64bit, 
Python.org v3.5.2:4def2a2901a5, MSC v.1900 64 bit (AMD64)] on win32
Tensorflow 0.11.10 for GPU, 


```
> >pip3 install --upgrade tensorflow-gpu
> Requirement already up-to-date: tensorflow-gpu in c:\program files\python35\lib\site-packages
> Requirement already up-to-date: werkzeug>=0.11.10 in c:\program files\python35\lib\site-packages (from tensorflow-gpu)
> Collecting protobuf>=3.2.0 (from tensorflow-gpu)
>   Downloading protobuf-3.3.0.tar.gz (271kB)
>     100% |################################| 276kB 1.0MB/s
> Requirement already up-to-date: wheel>=0.26 in c:\program files\python35\lib\site-packages (from tensorflow-gpu)
> Requirement already up-to-date: six>=1.10.0 in c:\program files\python35\lib\site-packages (from tensorflow-gpu)
> Requirement already up-to-date: numpy>=1.11.0 in c:\program files\python35\lib\site-packages (from tensorflow-gpu)
> Requirement already up-to-date: setuptools in c:\program files\python35\lib\site-packages (from protobuf>=3.2.0->tensorflow-gpu)
> Requirement already up-to-date: appdirs>=1.4.0 in c:\program files\python35\lib\site-packages (from setuptools->protobuf>=3.2.0->tensorflow-gpu)
> Requirement already up-to-date: packaging>=16.8 in c:\program files\python35\lib\site-packages (from setuptools->protobuf>=3.2.0->tensorflow-gpu)
> Requirement already up-to-date: pyparsing in c:\program files\python35\lib\site-packages (from packaging>=16.8->setuptools->protobuf>=3.2.0->tensorflow-gpu)
> Building wheels for collected packages: protobuf
>   Running setup.py bdist_wheel for protobuf ... done
>   Stored in directory: C:\Users\dzidm\AppData\Local\pip\Cache\wheels\1b\42\a0\4c7343df5b629ec9c75655468dce7652b28026896b0209ba55
> Successfully built protobuf
> Installing collected packages: protobuf
>   Found existing installation: protobuf 3.2.0
>     Uninstalling protobuf-3.2.0:
>       Successfully uninstalled protobuf-3.2.0
> Successfully installed protobuf-3.3.0
```




And then the full error:
```
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Program Files\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 906, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Program Files\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\__init__.py", line 51, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Program Files\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 906, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Program Files\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow_internal'
```

**Comment by Carmezim** [comment]
@dzid26 could you check if your cuDNN and CUDA DLLs are properly set in your `%PATH%`?

**Comment by dzid26** [comment]
![image](https://cloud.githubusercontent.com/assets/841061/25648829/ff785c2a-2f9d-11e7-97f9-5ed3196f5d9e.png)
Seems ok, I guess. The same error was present, when I tried running the command without cuDNN even being installed.
I am actually surprised that the error message isntt more detailed. Is there a way to see what DLL is it complaining about ?

**Comment by Carmezim** [comment]
Your CUDA is an unsupported version. TensorFlow only supports CUDA 8.0 and cuDNN 5.1 on WIndows.

**Comment by Carmezim** [comment]
@skye shouldn't we wait if @tonymdsl solved on his side?

**Comment by Carmezim** [comment]
@dzid26 @tonymdsl did you have any progress with the solution provided? Please let us know if it worked. Thanks!

**Comment by tonymdsl** [comment]
No is the same error 


Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Users\Tonymds\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\Tonymds\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 906, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: Impossível localizar o módulo especificado.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Tonymds\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Tonymds\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Tonymds\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\Tonymds\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Tonymds\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\Tonymds\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\__init__.py", line 51, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Tonymds\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Tonymds\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\Tonymds\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 906, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: Impossível localizar o módulo especificado.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Tonymds\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Tonymds\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Tonymds\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\Tonymds\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow_internal'


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
>>> hello = tf.constant('Hello, TensorFlow!')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'tf' is not defined
>>> sess = tf.Session()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'tf' is not defined

**Comment by tonymdsl** [comment]
![capturar](https://cloud.githubusercontent.com/assets/17919329/25676826/6ec74896-303b-11e7-8b76-b295ee59f174.JPG)

**Comment by Carmezim** [comment]
Just by seeing your `%PATH%` screenshot is still difficult to infer everything is properly installed. Could you make sure your cuDNN DLLs are properly set as CUDA's? This is most likely a CUDA/cuDNN misconfiguration, assuming of course your TF version is the latest with GPU support as you didn't specify.

**Comment by tonymdsl** [comment]
is working now the problem is i use cudNN 6.0 and now i put the cudNN 5.1 and now it's working tank u very much for the help

**Comment by Carmezim** [comment]
TensorFlow only supports cuDNN 5.1 on Windows, glad it's working now! 
Thank you for reporting, this issue can be closed.

**Comment by dzid26** [comment]
Finally it worked for me too. But it was not obvious that /bin folder
within cudann was supposed to be add.

Also this instruction on the website is inaccurate because CUDA 8.0
documentation doesn't mention setting up %path%. And that is not even
relevant, since the path is added automatically by the installer.

The main problem is with cudann nvidia's instructions.



Anyway, hopefully better installation process will be developed in the
future. Thanks guys

Radek

**Comment by mrry** [comment]
For users who find this issue when searching for the error message, I've created a script for diagnosing common TensorFlow on Windows installation issues. Please download the script from https://gist.github.com/mrry/ee5dbcfdd045fa48a27d56664411d41c and run `python tensorflow_self_check.py`. It will print suggestions for how to fix your installation. Let me know if you are still facing problems after running the script.
