### ISSUE TITLE
ValueError:tensorflow

### ISSUE THREAD

**Issue by leenabharambe** [tensorflow/tensorflow#9613]
when I'm trying to run the tensorflow odel with my data generating an error as:

Traceback (most recent call last):
  File "/home/ubuntu/tensorflow/models/summarization/bazel-bin/textsum/seq2seq_attention.runfiles/__main__/textsum/seq2seq_attention.py", line 214, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/ubuntu/tensorflow/models/summarization/bazel-bin/textsum/seq2seq_attention.runfiles/__main__/textsum/seq2seq_attention.py", line 209, in main
    decoder = seq2seq_attention_decode.BSDecoder(model, batcher, hps, vocab)
  File "/home/ubuntu/tensorflow/models/summarization/textsum/seq2seq_attention_decode.py", line 95, in __init__
    self._model.build_graph()
  File "/home/ubuntu/tensorflow/models/summarization/textsum/seq2seq_attention_model.py", line 296, in build_graph
    self._add_seq2seq()
  File "/home/ubuntu/tensorflow/models/summarization/textsum/seq2seq_attention_model.py", line 224, in _add_seq2seq
    tf.log(tf.nn.softmax(model_outputs[-1])), hps.batch_size*2)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 1970, in top_k
    return gen_nn_ops._top_kv2(input, k=k, sorted=sorted, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 2462, in _top_kv2
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2397, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1757, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1707, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 675, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: input must have last dimension >= k = 128 but is 102 for 'seq2seq/decode_output/TopKV2' (op: 'TopKV2') with input shapes: [64,102], [].

**Comment by skye** [comment]
Please fill out [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new), as this isn't enough information to help you. Thanks!

**Comment by girving** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
