### ISSUE TITLE
Can't load the model file from model_dir in CNN text classifier

### ISSUE THREAD

**Issue by SakthivelAnand** [tensorflow/tensorflow#9618]
Dear all,
I am working on NLP using tensor flow, i am using thhe text classifier using cnn from the tensor flow git hub example, where i stored my trained model by passing "model_dir" argument successfully , but when i try to reload the model it says an error
Error occurring part of my code is, 

"
classifier = learn.Estimator(model_fn=cnn_model,model_dir = "/home/local/models/")
#classifier.fit(x_train, y_train, steps=1000)
y_predicted = [p['class'] for p in classifier.predict(x_test, as_iterable=True)]
print(y_predicted)
"
this is a code when i try to reload the model file files from the "model_dir" which is already stored in it when train.

The error is ,

"
Traceback (most recent call last):
  File "CNN_Text.py", line 114, in <module>
    y_predicted = [p['class'] for p in classifier.predict(x_test, as_iterable=True)]
  File "/home/local/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 281, in new_func
    return func(*args, **kwargs)
  File "/home/local/tensorflow/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 565, in predict
    as_iterable=as_iterable)
  File "/home/local/tensorflow/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 857, in _infer_model
    infer_ops = self._get_predict_ops(features)
  File "/home/local/tensorflow/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1188, in _get_predict_ops
    return self._call_model_fn(features, labels, model_fn_lib.ModeKeys.INFER)
  File "/home/local/tensorflow/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1103, in _call_model_fn
    model_fn_results = self._model_fn(features, labels, **kwargs)
  File "CNN_Text.py", line 31, in cnn_model
    target = tf.one_hot(target, 2, 1, 0)
  File "/home/local/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 2156, in one_hot
    name)
  File "/home/local/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1848, in _one_hot
    axis=axis, name=name)
  File "/home/local/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 509, in apply_op
    (input_name, err))
ValueError: Tried to convert 'indices' to a tensor and failed. Error: None values not supported.
"

Please help me to solve this problem.
Thank you in advance.

**Comment by drpngx** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
