### ISSUE TITLE
inception/imagenet_distributed_train running is faild

### ISSUE THREAD

**Issue by bkovalev** [tensorflow/tensorflow#9620]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Not - Use last TF master and last Models
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:   Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: from source ( dramatically less compilation number of files, less in 100 files.)
- **TensorFlow version (use command below)**: 'v1.1.0-rc2-607-g550df41', '1.1.0-rc2' 

- **Bazel version (if compiling from source)**: 0.4.5
- **CUDA/cuDNN version**: 8.0, 6
- **GPU model and memory**: Nvidia P100 PCI - 16 GB
- **Exact command to reproduce**:
On ps - bazel-bin/inception/imagenet_distributed_train --job_name='ps' --task_id=0 --ps_hosts='11.11.11.31:2222' --worker_hosts='11.11.11.41:2222,11.11.11.41:2223'

All good 

INFO:tensorflow:PS hosts are: ['11.11.11.31:2222']
INFO:tensorflow:Worker hosts are: ['11.11.11.41:2222', '11.11.11.41:2223']
2017-05-03 11:12:54.447399: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:215] Initialize GrpcChannelCache for job ps -> {0 -> localhost:2222}
2017-05-03 11:12:54.447459: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:215] Initialize GrpcChannelCache for job worker -> {0 -> 11.11.11.41:2222, 1 -> 11.11.11.41:2223}
2017-05-03 11:12:54.456646: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:296] Started server with target: grpc://localhost:2222

### Describe the problem

On Worker 

CUDA_VISIBLE_DEVICES='1' bazel-bin/inception/imagenet_distributed_train --batch_size=128 --job_name='worker' --ps_hosts='11.11.11.31:2222' --worker_hosts='11.11.11.41:2222,11.11.11.41:2223' --data_dir=/data/imagenet_data/ --train_dir=/data/imagenet_train/ --task_id=1

It's failed with
 INFO:tensorflow:PS hosts are: ['11.11.11.31:2222']                                                                
INFO:tensorflow:Worker hosts are: ['11.11.11.41:2222', '11.11.11.41:2223']                                        
2017-05-03 11:24:17.640127: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:215] Initialize GrpcChannelCache for job ps -> {0 -> 11.11.11.31:2222}                                                                        
2017-05-03 11:24:17.640169: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:215] Initialize GrpcChannelCache for job worker -> {0 -> 11.11.11.41:2222, 1 -> localhost:2223}                                               
2017-05-03 11:24:17.648767: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:296] Started server with target: grpc://localhost:2223                                                                                     
Traceback (most recent call last):                                                                                
  File "/root/models/inception/bazel-bin/inception/imagenet_distributed_train.runfiles/inception/inception/imagenet_distributed_train.py", line 66, in <module>                                                                     
    tf.app.run()                                                                                                  
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run                
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))                                                            
  File "/root/models/inception/bazel-bin/inception/imagenet_distributed_train.runfiles/inception/inception/imagenet_distributed_train.py", line 62, in main
    inception_distributed_train.train(server.target, dataset, cluster_spec)
  File "/root/models/inception/bazel-bin/inception/imagenet_distributed_train.runfiles/inception/inception/inception_distributed_train.py", line 157, in train
    inception.loss(logits, labels)
  File "/root/models/inception/bazel-bin/inception/imagenet_distributed_train.runfiles/inception/inception/inception_model.py", line 128, in loss
    weight=1.0)
  File "/root/models/inception/bazel-bin/inception/imagenet_distributed_train.runfiles/inception/inception/slim/losses.py", line 166, in cross_entropy_loss
    cross_entropy = tf.contrib.nn.deprecated_flipped_softmax_cross_entropy_with_logits(
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/lazy_loader.py", line 53, in __getattr__
    module = self._load()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/lazy_loader.py", line 42, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/__init__.py", line 34, in <module>
    from tensorflow.contrib import image
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/image/__init__.py", line 39, in <module>
    from tensorflow.contrib.image.python.ops.single_image_random_dot_stereograms import single_image_random_dot_stereograms
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/image/python/ops/single_image_random_dot_stereograms.py", line 26, in <module>
    "_single_image_random_dot_stereograms.so"))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/util/loader.py", line 55, in load_op_library
    ret = load_library.load_op_library(path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/image/python/ops/_single_image_random_dot_stereograms.so: undefined symbol: _ZN6google8protobuf8internal10LogMessageC1ENS0_8LogLevelEPKci

Thanks,

Boris

**Comment by bkovalev** [comment]
More simple;

bazel-bin/inception/imagenet_train --batch_size=128 --train_dir=/data/imagenet_train/ --num_gpus=1 --data_dir=/data/imagenet_data/ 

Traceback (most recent call last):                   
  File "/root/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/imagenet_train.py", line 41, in <module>                                                                                             
    tf.app.run()                                                                                                  
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run                
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))                                                            
  File "/root/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/imagenet_train.py", line 37, in main                                                                                                 
    inception_train.train(dataset)                                                                                
  File "/root/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/inception_train.py", line 241, in train                                                                                              
    scope, reuse_variables)                                                                                       
  File "/root/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/inception_train.py", line 114, in _tower_loss                                                                                        
    inception.loss(logits, labels, batch_size=split_batch_size)                                                   
  File "/root/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/inception_model.py", line 128, in loss                                                                                               
    weight=1.0)                                                                                                   
  File "/root/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/slim/losses.py", line 166, in cross_entropy_loss                                                                                     
    cross_entropy = tf.contrib.nn.deprecated_flipped_softmax_cross_entropy_with_logits(                           
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/lazy_loader.py", line 53, in __getattr__    
    module = self._load()                                                                                         
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/lazy_loader.py", line 42, in _load          
    module = importlib.import_module(self.__name__)                                                               
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module                                      
    __import__(name)                                                                                              
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/__init__.py", line 34, in <module>              
    from tensorflow.contrib import image                                                                          
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/image/__init__.py", line 39, in <module>        
    from tensorflow.contrib.image.python.ops.single_image_random_dot_stereograms import single_image_random_dot_stereograms                                                                                                         
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/image/python/ops/single_image_random_dot_stereograms.py", line 26, in <module>                                                                                    
    "_single_image_random_dot_stereograms.so"))                                                                   
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/util/loader.py", line 55, in load_op_library    
    ret = load_library.load_op_library(path)                                                                      
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library                                                                                                            
    None, None, error_msg, error_code)                                                                            
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/image/python/ops/_single_image_random_dot_stereograms.so: undefined symbol: _ZN6google8protobuf8internal10LogMessageC1ENS0_8LogLevelEPKci

**Comment by drpngx** [comment]
Here's the error:
```
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/image/python/ops/_single_image_random_dot_stereograms.so: undefined symbol: _ZN6google8protobuf8internal10LogMessageC1ENS0_8LogLevelEPKci
(google::protobuf::internal::LogMessage::LogMessage(google::protobuf::LogLevel, char const*, int)
)
```
It looks like something is wrong in your installation. Perhaps tensorflow is not loaded or linking properly there. You could try to install the protobuf library on all slaves, which might result in some instability.
/CC: @skye

**Comment by MtDersvan** [comment]
Happened to me when I was building latest tensorflow/serving.

**Comment by yony228** [comment]
Is there someone fix this? 
By the way,I used oracle jdk for my env.

**Comment by waaran** [comment]
It happens randomly. I've encountered the similar issue. Just tried again and it worked!

tensorflow.python.framework.errors_impl.NotFoundError: /home/serving/bazel-bin/tensorflow_serving/example/mnist_saved_model.runfiles/org_tensorflow/tensorflow/contrib/image/python/ops/_single_image_random_dot_stereograms.so: undefined symbol: _ZN6google8protobuf8internal10LogMessageC1ENS0_8LogLevelEPKci

**Comment by mahnunchik** [comment]
Any news?

**Comment by yony228** [comment]
I find some reason:there is a env is not setted correct by the script.

_Sent from my Xiaomi MIX using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by tensorflowbutler** [comment]
This issue is automatically closed due to lack of activity. Please re-open if this is still an issue for you. Thanks!
