### ISSUE TITLE
separable_conv2d() got an unexpected keyword argument 'rate'

### ISSUE THREAD

**Issue by Raniazy** [tensorflow/tensorflow#9630]
When running : 
```
model = Xception(include_top=True, weights='imagenet')
```
I'm getting this error : 

```
Traceback (most recent call last):
  File "/home/username/PycharmProjects/segmentation/data/xception.py", line 273, in <module>
    model = Xception(include_top=True, weights='imagenet')
  File "/home/username/PycharmProjects/segmentation/data/xception.py", line 155, in Xception
    x = SeparableConv2D(128, (3, 3), padding='same', use_bias=False, name='block2_sepconv1')(x)
  File "/home/username/.virtualenvs/cv/lib/python3.5/site-packages/keras/engine/topology.py", line 578, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/username/.virtualenvs/cv/lib/python3.5/site-packages/keras/layers/convolutional.py", line 986, in call
    padding=self.padding)
  File "/home/username/.virtualenvs/cv/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2967, in separable_conv2d
    rate=dilation_rate)
TypeError: separable_conv2d() got an unexpected keyword argument 'rate'
```

**Comment by fchollet** [comment]
It looks like you are using an outdated version of TensorFlow where `tf.nn.separable_conv2d` did not yet support the `rate` argument. Update to the latest version.
