### ISSUE TITLE
`reload(tensorflow)` fails

### ISSUE THREAD

**Issue by drasmuss** [tensorflow/tensorflow#9636]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.1.0
- **Bazel version (if compiling from source)**:
- **Exact command to reproduce**:

``` python
from importlib import reload
import tensorflow
reload(tensorflow)
```

fails with error

```
Traceback (most recent call last):
  File "...\lib\importlib\__init__.py", line 166, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 626, in _exec
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "...\lib\site-packages\tensorflow\__init__.py", line 50, in <module>
    del python
NameError: name 'python' is not defined
```

**Comment by drpngx** [comment]
Hi @drasmuss while it's easy to fix that one problem, the library was not designed to do that. It will have issues later with gradient registration and the like.

**Comment by girving** [comment]
Closing as not feasible given importance.
