### ISSUE TITLE
Test failure on Mac: //tensorflow/python:directory_watcher_test

### ISSUE THREAD

**Issue by caisq** [tensorflow/tensorflow#964]
The following Python unit test fails on Mac: **//tensorflow/python:directory_watcher_test**

Below is the log with detailed error info:
```
..F...F...
======================================================================
FAIL: testFinishesLoadingFileWhenSwitchingToNewFile (__main__.DirectoryWatcherTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jenkins/workspace/experimental-cais-tensorflow-mac-python27-copt_pip_install-test/pip_install_tests/directory_watcher_test.py", line 102, in testFinishesLoadingFileWhenSwitchingToNewFile
    self.assertWatcherYields(['b', 'c'])
  File "/Users/jenkins/workspace/experimental-cais-tensorflow-mac-python27-copt_pip_install-test/pip_install_tests/directory_watcher_test.py", line 63, in assertWatcherYields
    self.assertEqual(list(self._watcher.Load()), values)
AssertionError: Lists differ: ['c'] != ['b', 'c']

First differing element 0:
c
b

Second list contains 1 additional elements.
First extra element 1:
c

- ['c']
+ ['b', 'c']

======================================================================
FAIL: testMultipleWrites (__main__.DirectoryWatcherTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jenkins/workspace/experimental-cais-tensorflow-mac-python27-copt_pip_install-test/pip_install_tests/directory_watcher_test.py", line 82, in testMultipleWrites
    self.assertWatcherYields(['x', 'y', 'z'])
  File "/Users/jenkins/workspace/experimental-cais-tensorflow-mac-python27-copt_pip_install-test/pip_install_tests/directory_watcher_test.py", line 63, in assertWatcherYields
    self.assertEqual(list(self._watcher.Load()), values)
AssertionError: Lists differ: [] != ['x', 'y', 'z']

Second list contains 3 additional elements.
First extra element 0:
x

- []
+ ['x', 'y', 'z']

----------------------------------------------------------------------
Ran 10 tests in 0.051s

FAILED (failures=2)
```

**Comment by caisq** [comment]
Machine machine details:
OS: "Darwin", 
Kernel: "15.3.0", 
Architecture: "i386", 
Bazel_version: "Build label: 0.1.4-homebrew", 
Java_version: "1.8.0_65", 
Python_version: "2.7.10", 
gpp_version: "Apple LLVM version 7.0.2 (clang-700.1.81)"

**Comment by vrv** [comment]
Okay, I think I have a fix for this on Mac.  @danmane in case he's interested.

The problem seems to be that in the DirectoryWatcherTest, the ByteLoader implementation assumes that you can read EOF from a file, have another thread append to the file, and then continue reading from the last known seek position.  Apparently this breaks under mac os x but not under linux.

I changed the ByteLoader code to keep track of the number of bytes read, and when you see EOF, to try seeking to the current number of bytes read and trying again to read from the file.  I couldn't find any documentation on this behavior difference between OS X and Linux though.  I'll try to send a review in tomorrow.

**Comment by caisq** [comment]
Thanks, @vrv. Looking forward to seeing the fix.

**Comment by danmane** [comment]
Thanks @vrv!
