### ISSUE TITLE
add a image with summary for showing  in tensorboard

### ISSUE THREAD

**Issue by jeansely** [tensorflow/tensorflow#9656]
Hi,
for add a image to graph for showing in tensorboard , i used below code. but the tensorflow error that :"TypeError: Parameter to MergeFrom() must be instance of same class: expected Summary got Tensor. for field Event.summary"

the code :
<<  _**writer =tf.summary.FileWriter('C:\Program Files\python3.5\logs',graph=tf.get_default_graph())**_
<v
<<tf.Tensor 'Slice_2:0' shape=(1, 152, 138, 1) dtype=float32>
<<**_imgsumarry=tf.summary.image('image', v, 3 ,collections=None)_**
<imgsumarry
<<tf.Tensor 'image_2:0' shape=() dtype=string>
<< **writer.add_summary(imgsumarry)**

full error:

Traceback (most recent call last):
  File "C:\Program Files\python3.5\python-3.5.3.amd64\lib\site-packages\google\protobuf\internal\python_message.py", line 516, in init
    copy.MergeFrom(new_val)
  File "C:\Program Files\python3.5\python-3.5.3.amd64\lib\site-packages\google\protobuf\internal\python_message.py", line 1208, in MergeFrom
    'expected %s got %s.' % (cls.__name__, msg.__class__.__name__))
TypeError: Parameter to MergeFrom() must be instance of same class: expected Summary got Tensor.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#579>", line 1, in <module>
    writer.add_summary(imgsumarry)
  File "C:\Program Files\python3.5\python-3.5.3.amd64\lib\site-packages\tensorflow\python\summary\writer\writer.py", line 113, in add_summary
    event = event_pb2.Event(summary=summary)
  File "C:\Program Files\python3.5\python-3.5.3.amd64\lib\site-packages\google\protobuf\internal\python_message.py", line 518, in init
    _ReraiseTypeErrorWithFieldName(message_descriptor.name, field_name)
  File "C:\Program Files\python3.5\python-3.5.3.amd64\lib\site-packages\google\protobuf\internal\python_message.py", line 446, in _ReraiseTypeErrorWithFieldName
    six.reraise(type(exc), exc, sys.exc_info()[2])
  File "C:\Program Files\python3.5\python-3.5.3.amd64\lib\site-packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Program Files\python3.5\python-3.5.3.amd64\lib\site-packages\google\protobuf\internal\python_message.py", line 516, in init
    copy.MergeFrom(new_val)
  File "C:\Program Files\python3.5\python-3.5.3.amd64\lib\site-packages\google\protobuf\internal\python_message.py", line 1208, in MergeFrom
    'expected %s got %s.' % (cls.__name__, msg.__class__.__name__))
TypeError: Parameter to MergeFrom() must be instance of same class: expected Summary got Tensor. for field Event.summary

**Comment by ppwwyyxx** [comment]
You need to eval the `imgsumarry` tensor to get a string first.

**Comment by jeansely** [comment]
Many Thanks
