### ISSUE TITLE
Unable to run GMM estimator in TF 1.1 but I can run in TF 1.0

### ISSUE THREAD

**Issue by vinay-hebb** [tensorflow/tensorflow#9682]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: custom code
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 7 64 bit
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.1 (tensorflow-1.1.0-cp35-cp35m-win_amd64)
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**: Run the below code in Python IDLE
- Used PIP installation for CPU only

### Describe the problem
I have used following code in TF 1.0 and TF 1.1. In TF 1.0, it executes and crashes in TF 1.1. In TF 1.0, I dont know any way to get weights(or prior probabilities) for each component in a given GMM. Changes related to weights are added in TF 1.1. Hence I need to run TF 1.1
```
from tensorflow.contrib.factorization.python.ops import gmm as gmm_lib 
import random 
import numpy as np
import tensorflow as tf
mu, sigma = 0, 0.1
x_1d = 10*np.random.randn(100000, 1).astype('f') + 50
gmm = gmm_lib.GMM(1,random_seed=0) 
gmm.fit(x_1d)
```

### Source code / logs
I got the below crash in TF 1.1

WARNING:tensorflow:Using temporary folder as model directory: C:\Users\HVINAY~1.COR\AppData\Local\Temp\tmptpejli7d

Warning (from warnings module):
  File "<Python Installed Directory>\lib\site-packages\tensorflow\python\util\deprecation.py", line 248
    equality = a == b
FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
WARNING:tensorflow:From C:\Users\hvinay.CORP\Documents\TF\GMMEst.py:11: calling BaseEstimator.fit (from tensorflow.contrib.learn.python.learn.estimators.estimator) with x is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
Traceback (most recent call last):
  File "<Python Installed Directory>\lib\site-packages\tensorflow\python\client\session.py", line 1039, in _do_call
    return fn(*args)
  File "<Python Installed Directory>\lib\site-packages\tensorflow\python\client\session.py", line 1021, in _run_fn
    status, run_metadata)
  File "<Python Installed Directory>\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "<Python Installed Directory>\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input' with dtype float
	 [[Node: input = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hvinay.CORP\Documents\TF\GMMEst.py", line 11, in <module>
    gmm.fit(x_1d)
  File "<Python Installed Directory>\lib\site-packages\tensorflow\python\util\deprecation.py", line 281, in new_func
    return func(*args, **kwargs)
  File "<Python Installed Directory>\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 414, in fit
    SKCompat(self).fit(x, y, batch_size, steps, max_steps, monitors)
  File "<Python Installed Directory>\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 1317, in fit
    monitors=all_monitors)
  File "<Python Installed Directory>\lib\site-packages\tensorflow\python\util\deprecation.py", line 281, in new_func
    return func(*args, **kwargs)
  File "<Python Installed Directory>\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 430, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "<Python Installed Directory>\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 974, in _train_model
    config=config_pb2.ConfigProto(allow_soft_placement=True)
  File "<Python Installed Directory>\lib\site-packages\tensorflow\python\training\monitored_session.py", line 333, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "<Python Installed Directory>\lib\site-packages\tensorflow\python\training\monitored_session.py", line 627, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "<Python Installed Directory>\lib\site-packages\tensorflow\python\training\monitored_session.py", line 456, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "<Python Installed Directory>\lib\site-packages\tensorflow\python\training\monitored_session.py", line 800, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "<Python Installed Directory>\lib\site-packages\tensorflow\python\training\monitored_session.py", line 805, in _create_session
    return self._sess_creator.create_session()
  File "<Python Installed Directory>\lib\site-packages\tensorflow\python\training\monitored_session.py", line 517, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "<Python Installed Directory>\lib\site-packages\tensorflow\python\training\monitored_session.py", line 393, in create_session
    init_fn=self._scaffold.init_fn)
  File "<Python Installed Directory>\lib\site-packages\tensorflow\python\training\session_manager.py", line 262, in prepare_session
    sess.run(init_op, feed_dict=init_feed_dict)
  File "<Python Installed Directory>\lib\site-packages\tensorflow\python\client\session.py", line 778, in run
    run_metadata_ptr)
  File "<Python Installed Directory>\lib\site-packages\tensorflow\python\client\session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "<Python Installed Directory>\lib\site-packages\tensorflow\python\client\session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "<Python Installed Directory>\lib\site-packages\tensorflow\python\client\session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input' with dtype float
	 [[Node: input = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op 'input', defined at:
  File "<string>", line 1, in <module>
  File "<Python Installed Directory>\lib\idlelib\run.py", line 124, in main
    ret = method(*args, **kwargs)
  File "<Python Installed Directory>\lib\idlelib\run.py", line 351, in runcode
    exec(code, self.locals)
  File "C:\Users\hvinay.CORP\Documents\TF\GMMEst.py", line 11, in <module>
    gmm.fit(x_1d)
  File "<Python Installed Directory>\lib\site-packages\tensorflow\python\util\deprecation.py", line 281, in new_func
    return func(*args, **kwargs)
  File "<Python Installed Directory>\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 414, in fit
    SKCompat(self).fit(x, y, batch_size, steps, max_steps, monitors)
  File "<Python Installed Directory>\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 1317, in fit
    monitors=all_monitors)
  File "<Python Installed Directory>\lib\site-packages\tensorflow\python\util\deprecation.py", line 281, in new_func
    return func(*args, **kwargs)
  File "<Python Installed Directory>\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 430, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "<Python Installed Directory>\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 925, in _train_model
    features, labels = input_fn()
  File "<Python Installed Directory>\lib\site-packages\tensorflow\contrib\learn\python\learn\learn_io\data_feeder.py", line 430, in input_builder
    self._input_dtype, 'input')
  File "<Python Installed Directory>\lib\site-packages\tensorflow\contrib\learn\python\learn\learn_io\data_feeder.py", line 426, in get_placeholder
    dtypes.as_dtype(dtype), [None] + shape[1:], name=name_prepend)
  File "<Python Installed Directory>\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1507, in placeholder
    name=name)
  File "<Python Installed Directory>\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 1997, in _placeholder
    name=name)
  File "<Python Installed Directory>\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "<Python Installed Directory>\lib\site-packages\tensorflow\python\framework\ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "<Python Installed Directory>\lib\site-packages\tensorflow\python\framework\ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'input' with dtype float
	 [[Node: input = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

**Comment by martinwicke** [comment]
Ashish, can you take a look?

**Comment by yifeif** [comment]
@xavigonzalvo could you take a look? Thanks!

**Comment by xavigonzalvo** [comment]
Please use input_fn not data directly.

**Comment by vinay-hebb** [comment]
Thanks. I will try this.
