### ISSUE TITLE
Import errors 

### ISSUE THREAD

**Issue by GospodinNoob** [tensorflow/tensorflow#9726]
### System information
- Trying to run tutorial code
- Win8.1
- pip3 install --upgrade tensorflow 
- can't run programm to write version (can't run any code with import tensorflow)

Traceback (most recent call last):
  File "C:\Users\home-pc\AppData\Local\Programs\Python\Python35-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
  File "C:\Users\home-pc\AppData\Local\Programs\Python\Python35-32\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\home-pc\AppData\Local\Programs\Python\Python35-32\lib\site-packages\tensorflow\python\__init__.py", line 54, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\home-pc\AppData\Local\Programs\Python\Python35-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\Users\home-pc\AppData\Local\Programs\Python\Python35-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/home-pc/PycharmProjects/untitled6/b.py", line 1, in <module>
    import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)
  File "C:\Users\home-pc\AppData\Local\Programs\Python\Python35-32\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\home-pc\AppData\Local\Programs\Python\Python35-32\lib\site-packages\tensorflow\python\__init__.py", line 60, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\home-pc\AppData\Local\Programs\Python\Python35-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
  File "C:\Users\home-pc\AppData\Local\Programs\Python\Python35-32\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\home-pc\AppData\Local\Programs\Python\Python35-32\lib\site-packages\tensorflow\python\__init__.py", line 54, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\home-pc\AppData\Local\Programs\Python\Python35-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\Users\home-pc\AppData\Local\Programs\Python\Python35-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ImportError: No module named '_pywrap_tensorflow'

Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.

**Comment by mcenderdragon** [comment]
I have the same problem. I already tried this solution(#97 installign VS C++ 2015) but it did not help.

**Comment by Androbin** [comment]
[https://www.tensorflow.org/install/install_sources#common_installation_problems](https://www.tensorflow.org/install/install_sources#common_installation_problems)

> [35953210](http://stackoverflow.com/q/35953210) | Invoking `python` or `ipython` generates the following error:
> ImportError: cannot import name pywrap_tensorflow

**Comment by mcenderdragon** [comment]
@Androbin, nope this is also not helping me :/

**Comment by GospodinNoob** [comment]
@Androbin it's solution for ubuntu, i use windows8.1

**Comment by drpngx** [comment]
It's a windows issue, most likely due to missing dependencies. Could you run the dependency walker on the `pywrap_internal_tensorflow` library? I am guessing it's CUDA. Please double check that you have those installed, including CUPTI.

**Comment by iysaleh** [comment]
I'm not sure if this is it at all, but I believe the general consensus is that you don't attempt to use 32-bit python with Tensorflow on Windows... I only say that you are based on your folder name 'Python35-32'

**Comment by GospodinNoob** [comment]
Tesrflow requires only amd CPU?

**Comment by GospodinNoob** [comment]
@drpngx, CUDA could not install, so i install tensorflow-cpu-only with anaconda and it's fix this problems. Example prject works, but now i have some warnings

2017-05-07 14:37:35.667977: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE instructions, but these are available on your machine and could speed up CPU computations.
2017-05-07 14:37:35.668324: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE2 instructions, but these are available on your machine and could speed up CPU computations.
2017-05-07 14:37:35.668662: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
2017-05-07 14:37:35.668993: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-05-07 14:37:35.669359: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-05-07 14:37:35.669736: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.

What are these instructions? How i may use them?
