### ISSUE TITLE
MAC pip install operation not permitted

### ISSUE THREAD

**Issue by aertoria** [tensorflow/tensorflow#98]
MBP 2014. Intel CPU.

Any thoughts? Below was running with sudo

Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 640, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 716, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req/req_uninstall.py", line 125, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 315, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-bX2I_b-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'

**Comment by mrry** [comment]
Hi there, we've seen quite a few configurations where it's been difficult to upgrade the `six` library shipped with OS X to the appropriate version. The most successful approach so far has been to use [HomeBrew](http://brew.sh/), and `brew install python` to get a clean Python setup.

Alternatively, some people have had luck using `sudo easy_install -U six` to upgrade `six` before installing TensorFlow.

Can you try one of these approaches and let us know if it works? Thanks!

**Comment by vrv** [comment]
(Please re-open if that does not solve the problem, or if our documentation here does not help: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#common_install_problems)
