### ISSUE TITLE
Freezing graphs with custom ops

### ISSUE THREAD

**Issue by rajatvikramsingh** [tensorflow/tensorflow#9920]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04 and MacOS Sierra
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: master (quite recent)
- **Bazel version (if compiling from source)**: 0.4.5
- **Exact command to reproduce**: freeze_graph

### Describe the problem
I've asked my question on StackOverflow here:
http://stackoverflow.com/questions/43880729/using-new-op-while-importing-graph-in-tensorflow
I'm trying to freeze a model which contains a custom op. But `freeze_graph` gives the following error: 
```
Traceback (most recent call last):
  File "<local path>/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 202, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "<local path>/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "<local path>/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 134, in main
    FLAGS.variable_names_blacklist)
  File "<local path>/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 99, in freeze_graph
    _ = importer.import_graph_def(input_graph_def, name="")
  File "<local path>/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/framework/importer.py", line 260, in import_graph_def
    raise ValueError('No op named %s in defined operations.' % node.op)
ValueError: No op named RoiPool in defined operations.
```
I was suggested on StackOverflow to build `freeze_graph` with my custom op as a dependency. I did that, but `freeze_graph` still gives the same error. 

It was also suggested for me to open a **feature request** to make an easier-to-use interface for using freeze_graph with custom ops.

### Source code / logs
Here is the freeze_graph command I'm using: 
`bazel-bin/tensorflow/python/tools/freeze_graph --input_graph=<local path>/data/graph_vgg.pb --input_checkpoint=<local path>/data/VGGnet_fast_rcnn_iter_70000.ckpt --output_node_names="cls_prob,bbox_pred" --output_graph=<local path>/graph_frozen.pb`

**Comment by skye** [comment]
@petewarden FYI

**Comment by gunan** [comment]
@aselle could you chime in

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activityand the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
A member of the TensorFlow organization has replied after the stat:awaiting tensorflower label was applied.

**Comment by drpngx** [comment]
I guess we'd need for `freeze_graph` to load some binary to do that? I'm not sure how this would work.

@rajatvikramsingh if you create a rule that's like `freeze_graph` but links with your binary, possibly loads a DSO if you have created one, would that work for you?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by hajungong007** [comment]
hi，I have the same proble, how you solve it?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by drpngx** [comment]
See resolution above.
