### ISSUE TITLE
AttributeError: type object 'NewBase' has no attribute 'is_abstract'

### ISSUE THREAD

**Issue by 9970557164** [tensorflow/tensorflow#9930]
------------------------

### System information
- 
-OS Platform and Distribution  =Ubuntu 14.04
- **TensorFlow installed = 
 i mtrying to install tensorflow using following link

https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.1.0-cp27-none-linux_x86_64.whl

### Describe the problem
when i am trying to import tensorflow its not working what to do you can check following logs

### Source code / logs
root@ubuntu:/home/vivek# python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 104, in <module>
    from tensorflow.python.platform import test
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/test.py", line 38, in <module>
    from tensorflow.python.framework import test_util as _test_util
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/test_util.py", line 45, in <module>
    from tensorflow.python.platform import googletest
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/googletest.py", line 33, in <module>
    from tensorflow.python.platform import benchmark  # pylint: disable=unused-import
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/benchmark.py", line 119, in <module>
    class Benchmark(six.with_metaclass(_BenchmarkRegistrar, object)):
  File "/usr/lib/python2.7/dist-packages/six.py", line 617, in with_metaclass
    return meta("NewBase", bases, {})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/benchmark.py", line 114, in __new__
    if not newclass.is_abstract():
AttributeError: type object 'NewBase' has no attribute 'is_abstract'
root@ubuntu:/home/vivek#

**Comment by skye** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it sounds like a setup problem. There is also a larger community that reads questions there. Thanks!
