### ISSUE TITLE
graph_editor.copy_with_input_replacements crashes for some orderings of inputs

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#9978]
Graph editor copy_with_input_replacements  visits nodes in order provided, and assumes that op referenced by "op._original_op" has already already been visited. When this assumption is false, it fails with KeyError inside transform.py

Reproducible case

```
import tensorflow as tf
import numpy as np
import tensorflow.contrib.graph_editor as ge

if __name__=='__main__':
  params = tf.Variable(1, dtype=np.float32, name="params")
  temp = tf.reduce_sum(params, name="sum_temp")
  cost1 = tf.square(temp, name="cost1")
  gradients1 = tf.gradients([cost1], [params])
  ops = tf.get_default_graph().get_operations()
  ops = list(sorted(ops, key=lambda op: op.name))
  copied_sgv, info = ge.copy_with_input_replacements(ge.sgv(ops), {})
```
It fails with following error

```
Traceback (most recent call last):
  File "graph_editor_test.py", line 13, in <module>
    copied_sgv, info = ge.copy_with_input_replacements(ge.sgv(ops), {})
  File "/Users/yaroslav/anaconda/envs/memory/lib/python3.5/site-packages/tensorflow/contrib/graph_editor/transform.py", line 620, in copy_with_input_replacements
    sgv, dst_graph, dst_scope, src_scope, reuse_dst_scope=reuse_dst_scope)
  File "/Users/yaroslav/anaconda/envs/memory/lib/python3.5/site-packages/tensorflow/contrib/graph_editor/transform.py", line 436, in __call__
    self._copy_ops(info)
  File "/Users/yaroslav/anaconda/envs/memory/lib/python3.5/site-packages/tensorflow/contrib/graph_editor/transform.py", line 450, in _copy_ops
    op_, op_outputs_ = self.transform_op_handler(info, op)
  File "/Users/yaroslav/anaconda/envs/memory/lib/python3.5/site-packages/tensorflow/contrib/graph_editor/transform.py", line 173, in copy_op_handler
    original_op = info.transform_original_op_handler(info, op._original_op)
  File "/Users/yaroslav/anaconda/envs/memory/lib/python3.5/site-packages/tensorflow/contrib/graph_editor/transform.py", line 125, in transform_op_if_inside_handler
    return info.transformed_ops[op]
KeyError: <tf.Operation 'sum_temp' type=Sum>
```

A work-around is to clear `_original_op` entries for all ops

```
def clear_original_ops(ops):
  for op in ops:
    op._original_op = None
```

@purpledog

**Comment by skye** [comment]
@sherrym can you comment or redirect to someone who can? Thanks!

**Comment by sherrym** [comment]
Frank Perbet. I am not sure if he has a github account.

**Comment by yaroslavvb** [comment]
It's @purpledog . Simple fix would be just to remove anything to do with `_original_op`. That field hasn't been touched for 2 years, not sure if it's actually used by anything. I've been using graph editor recently and can aggregate all the fixes into PRs if there's interest in checking them in

**Comment by purpledog** [comment]
Yaroslav, your fixes would be very welcome.

**Comment by poolio** [comment]
@yaroslavvb I'd tremendously appreciate a PR for the fixes as I've been having issues with _original_op as well (#9125)

**Comment by yaroslavvb** [comment]
@poolio ps, as a temporary work-around, the hack I used was just to grep for "original_op" inside contrib.graph_editor and commented out lines that set original op

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by sushreebarsa** [comment]
@yaroslavvb TF v1.x is not actively supported and tf.contrib is no longer supported in TensorFlow 2.x. Here is the [migration](https://www.tensorflow.org/guide/migrate) guide. Please create a new issue if it is still valid for 2.x. Thank you!
